### ISSUE TITLE
[HOLD for payment 2023-09-11] [$1000] Distance Request preview doesn't load

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26504] opened 2023-09-01 17:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

# This issue is only present on the last main
# This issue requires an immediate action. If you're posting a proposal, make sure you can open a PR within 6 hours of proposal approval

## Action Performed:

1. Go to a workspace chat
2. Click "+" next to the text composer and click "Request money"
3. Click "Distance request" tab
4. Click "Start" and type any US address. Click any address suggestion.
5. Click "Finish" and and type any US address. Click any address suggestion. Make sure that the address is not the same address from Step 4.
6. Click "Next" and on the next page, click "Save"
7. Check that the distance request preview shown on the bottom of the workspace chat is infinitely loading.

_This is a bug reported [in this PR](https://github.com/Expensify/App/pull/25707#issuecomment-1702140383)_

## Expected Result:
The preview should be loaded with correct data

## Actual Result:
The preview doesn't load

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

https://github.com/Expensify/App/assets/98560306/6c2021f4-9d11-4d7f-9591-dd259d600f11

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010faa8f0f2edce9aa</li>
        <li>Upwork Job ID: 1697665999018233856</li>
        <li>Last Price Increase: 2023-09-01</li>
<li>Automatic offers: </li>
<ul>
<li>jeet-dhandha | Contributor | 26458647</li>
</ul></li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-09-01 17:47
<img width="159" alt="Screenshot 2023-09-01 at 11 17 09 PM" src="https://github.com/Expensify/App/assets/59088937/13636d0e-9c01-4109-a7fd-b66690d5b82f">

This is two buggy :)

**Comment by shubham1206agra** [comment] 2023-09-01 17:49
@hayata-suenaga Have you removed the distance request from the latest main?

**Comment by hayata-suenaga** [comment] 2023-09-01 17:50
@shubham1206agra 
No we didn't

**Comment by b4s36t4** [comment] 2023-09-01 17:52
@hayata-suenaga Can you link a video, just to confirm what I'm experience is same or not.

**Comment by hayata-suenaga** [comment] 2023-09-01 17:53
@b4s36t4 I updated the OP to include the video

**Comment by shubham1206agra** [comment] 2023-09-01 17:53
Working on Safari

<img width="590" alt="Screenshot 2023-09-01 at 11 23 16 PM" src="https://github.com/Expensify/App/assets/58412969/a8723b92-1af2-48f3-9511-ce989eb7e137">

**Comment by shubham1206agra** [comment] 2023-09-01 18:19
I found the problem @hayata-suenaga

**Comment by shubham1206agra** [comment] 2023-09-01 18:20
tryResolveUrlFromApiRoot giving `/receipts/w_5486f01c48729e148e9ba0354138110639a523bd.png` for input of `https://www.expensify.com/receipts/w_5486f01c48729e148e9ba0354138110639a523bd.png`

**Comment by shubham1206agra** [comment] 2023-09-01 18:21
But it should remain `https://www.expensify.com/receipts/w_5486f01c48729e148e9ba0354138110639a523bd.png`

**Comment by b4s36t4** [comment] 2023-09-01 18:21
@shubham1206agra No that's not the issue.

**Comment by shubham1206agra** [comment] 2023-09-01 18:22
<img width="1512" alt="Screenshot 2023-09-01 at 11 51 53 PM" src="https://github.com/Expensify/App/assets/58412969/550f873b-a989-47c5-a984-b1a2b47bb920">

**Comment by shubham1206agra** [comment] 2023-09-01 18:22
See this

**Comment by shubham1206agra** [comment] 2023-09-01 18:25
Wait

**Comment by joh42** [comment] 2023-09-01 18:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance request previews respond with 404s
### What is the root cause of that problem?
The problem is that image URLs are always converted to the current root:

https://github.com/Expensify/App/blob/2fd54c1e47eea713b2c81631caccfb6816916d95/src/components/ReportActionItem/ReportActionItemImage.js#L41

But distance request previews are only visible through the original URL.
### What changes do you think we should make in order to solve the problem?


I suggest we add a new prop, perhaps called `keepOriginalSource` that we pass down from the MoneyRequestPreview.

I think the correct way to pass this would be `keepOriginalSource={props.transaction.category === 'Car'}`, but I could be wrong.

If this is true in ReportActionItemImage, we do not replace the URL. The code would look something like:

```
let thumbnailSource = thumbnail;
if (!keepOriginalSource) {
    thumbnailSource = tryResolveUrlFromApiRoot(thumbnail);
}
```


### What alternative solutions did you explore? (Optional)

**Comment by joh42** [comment] 2023-09-01 18:48
Proposal ready for review @hayata-suenaga

**Comment by joh42** [comment] 2023-09-01 18:53
This is what the result looks like:

https://github.com/Expensify/App/assets/138504087/3100c01b-d2bb-47ae-ae9e-4012963ca019

**Comment by jeet-dhandha** [comment] 2023-09-01 19:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Receipts image when fetched returns a 404 error.

### What is the root cause of that problem?
- Issue with the proxy server as we might not have access to `/receipts` endpoint on expensify server.

### What changes do you think we should make in order to solve the problem?
- Like show here for `/chat-attachments` we might need to handle `/receipts` endpoint as well.

https://github.com/Expensify/App/blob/2fd54c1e47eea713b2c81631caccfb6816916d95/web/proxy.js#L27-L38

- Also I think we need to add a new entry in `webpack.dev.js` for `/receipts` endpoint just like we have for `/chat-attachments` endpoint.

https://github.com/Expensify/App/blob/2fd54c1e47eea713b2c81631caccfb6816916d95/config/webpack/webpack.dev.js#L24-L26


### What alternative solutions did you explore? (Optional)
- Quick fix could be like this:

https://github.com/Expensify/App/blob/2fd54c1e47eea713b2c81631caccfb6816916d95/src/components/ReportActionItem/ReportActionItemImage.js#L41

```diff
- const thumbnailSource = tryResolveUrlFromApiRoot(thumbnail);
+ let thumbnailSource = tryResolveUrlFromApiRoot(thumbnail)
+ if (thumbnailSource.startsWith('/receipts')) {
+     thumbnailSource = thumbnailSource.replace('/receipts', CONST.EXPENSIFY_URL + '/receipts');
}

```

**Comment by shubham1206agra** [comment] 2023-09-01 19:15
My confusion creating problems

**Comment by napster125** [comment] 2023-09-01 19:34
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Distance Request preview doesn't load
### What is the root cause of that problem?
There are two main problems.
- We may not have access to the `/receipts` endpoint on the Expensify server because we are currently accessing it on localhost.
- We are encountering a lot of console errors due to incorrect usage of `React.memo` on the Image component.
### What changes do you think we should make in order to solve the problem?
We need to change some code in Image component.
https://github.com/Expensify/App/blob/e460459ce0393edfcbda8ddbc5197a84b38bbac8/src/components/Image/index.js#L55

```
return prevProps.source=== nextProps.source || prevProps.source.uri === nextProps.source.uri;
```

https://github.com/Expensify/App/blob/e460459ce0393edfcbda8ddbc5197a84b38bbac8/src/components/Image/index.js#L22

```
if (propsSource.uri.startsWith('/receipts'))
  imageUri = propsSource.uri.replace('/receipts', `${CONST.EXPENSIFY_URL}/receipts`);

return {uri: `${imageUri}?encryptedAuthToken=${encodeURIComponent(authToken)}`}; 

```

### What alternative solutions did you explore? (Optional)
n/a

#### Result
![image](https://github.com/Expensify/App/assets/136573674/bd2d2704-654a-4a44-af81-7f68a8b47a4a)

**Comment by Pluto0104** [comment] 2023-09-01 20:11
distance request preview works fine on staging and production.

**Comment by arosiclair** [comment] 2023-09-01 20:38
@jeet-dhandha's [proposal](https://github.com/Expensify/App/issues/26504#issuecomment-1703216724) looks promising let's implement it

**Comment by jeet-dhandha** [comment] 2023-09-01 20:45
I will create a PR in short while 👍 .

**Comment by napster125** [comment] 2023-09-01 20:48
@b4s36t4 how do you think about tons of console errors from your [comment](https://expensify.slack.com/archives/C01GTK53T8Q/p1693598067317209?thread_ts=1693590778.075089&cid=C01GTK53T8Q)? Is this not a bug?

**Comment by napster125** [comment] 2023-09-01 20:55
Sorry, @b4s36t4 the url was incorrect. could you please take a look again please? 🙏

**Comment by b4s36t4** [comment] 2023-09-01 20:56
@napster125 , let sync on slack not on GH and that too different issue. Ping on slack. Mahesh Vagicherla is my slack name.

**Comment by jeet-dhandha** [comment] 2023-09-01 21:23
I will add screenshots in a while. 👍

**Comment by jeet-dhandha** [comment] 2023-09-01 21:51
Done with PR. Please review as soon as possible.

**Comment by hayata-suenaga** [comment] 2023-09-01 22:09
@strepanier03 for clarification, we didn't use the help of @sobitneupane in selecting the proposal.
For PR review, we're using the help of @allroundexperts 

So I unassigned @sobitneupane and @allroundexperts as C+ for this issue

**Comment by neil-marcellini** [comment] 2023-09-01 22:26
I added this to the project as low priority because it only occurs in the dev environment for contributors testing against staging, due to the proxy.

**Comment by strepanier03** [comment] 2023-09-14 20:26
@JmillsExpensify - Payment has been requested by @allroundexperts and the payment summary can be found in this [comment](https://github.com/Expensify/App/issues/26504#issuecomment-1707512638).

**Comment by strepanier03** [comment] 2023-09-18 20:32
@JmillsExpensify - I'm unsure if this has been paid but a friendly bump just in case. Thank you!

**Comment by strepanier03** [comment] 2023-09-21 21:55
I see a comment from Jason in Slack that this doesn't need to stay open so I'm going to close it. Jason has the request.

**Closed by strepanier03** 2023-09-21 21:55 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 12:44
$1,500 payment for @allroundexperts approved based on BZ summary.
