### ISSUE TITLE
[HOLD for payment 2023-08-07] [$1000] App only displays tooltip on long reply in thread message from concierge

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22609] opened 2023-07-11 03:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Search for new user eg: [testing123467@gmail.com](mailto:testing123467@gmail.com)
3. Concierge will display 'first time chatting' message, hover on it and click on reply in thread
4. In LHN, hover on three dots on the reply in thread report of concierge and observe that it displays the complete message in tooltip
5. Open any other report and send long text
6. Click on reply in thread on long text
7. In LHN, hover on three dots on the reply in thread report of long text and observe that app does not display any tooltip
## Expected Result: 
App should display tooltip (to display full message) on hover over three dots in LHN for long text reply in thread report as it does for concierge reply in thread report
## Actual Result: 
App does not display tooltip (to display full message) on hover over three dots in LHN for long text reply in thread report

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0f8423f8-5704-47e0-bc45-3f7d2d2210cf

https://github.com/Expensify/App/assets/43996225/7ecef03d-462f-454b-afec-2c976d4461a3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689012283926099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01019167e09bdf2205</li>
        <li>Upwork Job ID: 1678698491007807488</li>
        2023-07-11<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>StevenKKC | Contributor | 25729137</li>
<li>dhanashree-sawant | Reporter | 25729138</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-11 06:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Reactions get copied to clipboard after triple clicking and copying a comment.

### What is the root cause of that problem?
Comments and reactions are displayed in one container.
By triple clicking a comment, both the comment and reactions in the container will be selected.
As a result, the reactions are copied together.

### What changes do you think we should make in order to solve the problem?
We should disable selecting reactions.

In the app, there are three types of report action item: `ReportActionItemDraft`, `ReportActionItemSingle` and `ReportActionItemGrouped`.
If we edit a comment, `ReportActionItemDraft` will be displayed. This type cannot be selected, so we can ignore it.

In below screenshot, first comment `test 1` is `ReportActionItemSingle`, and second comment `test 2` is `ReportActionItemGrouped`.

We should add `styles.userSelectNone` to other report action items.


### What alternative solutions did you explore? (Optional)
None.





## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In workspace information, user is taken to sub-sub thread/replies when clicking on “Go to #admins room” or "Go to #announce room".

### What is the root cause of that problem?
If user click on “Go to #admins room” or "Go to #announce room", `goToRoom` is called.


If a user creates a thread on the workspace, the thread has a `CONST.REPORT.CHAT_TYPE.POLICY_ADMINS` or `CONST.REPORT.CHAT_TYPE.POLICY_ANNOUNCE` `chatType`, and `policyID` is equal to workspace's `policyID`.
So the thread is selected, and user is taken to the thread.

### What changes do you think we should make in order to solve the problem?
We should select correct workspace room in `goToRoom`.
Workspace's admin or announce room have null `parentReportID` and `parentReportActionID`, and thread have non-null ID.
We should check `parentReportID` and `parentReportActionID` as below.
```js
    const goToRoom = useCallback(
        (type) => {
-			const room = _.find(props.reports, (report) => report && report.policyID === policy.id && report.chatType === type);
+            const room = _.find(props.reports, (report) => report && report.policyID === policy.id && report.chatType === type && !report.parentReportID && !report.parentReportActionID);
            Navigation.navigate(ROUTES.getReportRoute(room.reportID));
        },
        [props.reports, policy],
    );

```
### What alternative solutions did you explore? (Optional)
None.






## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Reactions get copied to clipboard after triple clicking and copying a comment.

### What is the root cause of that problem?
Comments and reactions are displayed in one container.
By triple clicking a comment, both the comment and reactions in the container will be selected.
As a result, the reactions are copied together.

### What changes do you think we should make in order to solve the problem?
We should disable selecting reactions.

In the app, there are three types of report action item: `ReportActionItemDraft`, `ReportActionItemSingle` and `ReportActionItemGrouped`.
If we edit a comment, `ReportActionItemDraft` will be displayed. This type cannot be selected, so we can ignore it.

In below screenshot, first comment `test 1` is `ReportActionItemSingle`, and second comment `test 2` is `ReportActionItemGrouped`.

We should add `styles.userSelectNone` to other report action items.


### What alternative solutions did you explore? (Optional)
None.





## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking back button after clicking on menu gets back to list of workspace on admins channel.

### What is the root cause of that problem?
If the user clicks on the workspace name on the report detail page, the navigation will create a new item in the `RightModalNavigator` because `Report_Details_Root` and `Workspace_Initial` are different screens in `linkingConfig.js`.
Therefore, there are two items in the `RightModalNavigator`.

Since menu item and workspace initial page are on the same screen, new item will be added to `Workspace_Initial`.

When the user clicks the back button, navigation will iterate `Workspace_Settings` routes and return 0.
The `fallbackRoute` will be navigated accordingly.

Because `fallbackRoute` is `ROUTES.SETTINGS_WORKSPACES`, we'll be returned to the list of workspaces.

### What changes do you think we should make in order to solve the problem?
We can remove `fallbackRoute`.
```js

```
### What alternative solutions did you explore? (Optional)
None.





## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User details message click button does not open user report page

### What is the root cause of that problem?
If user A click message button on user B's detail page, `Report.navigateToAndOpenReport` is called, and then `ReportUtils.getChatByParticipants` is called.



In `ReportUtils.getChatByParticipants` function, will iterate all report actions and find the first report which participant id is equal to user B's account id.


`ReportUtils.getChatByParticipants` does not filter money request report and report actions is stored randomly, so money request report which participant id is equal to user B's account id maybe returned.
If user A create task and assign to user B, and then go to userB's detail page and click message button, the task report also maybe returned.

### What changes do you think we should make in order to solve the problem?
If this is not intended, we can add `onlyIncludeChatReport` parameter to `ReportUtils.getChatByParticipants` with `false` default value.
And pass `true` to `ReportUtils.getChatByParticipants` function.

```js
-	function getChatByParticipants(newParticipantList) {
+	function getChatByParticipants(newParticipantList, onlyIncludeChatReport = false) {
		newParticipantList.sort();
		return _.find(allReports, (report) => {
			// If the report has been deleted, or there are no participants (like an empty #admins room) then skip it
			if (!report || !report.participantAccountIDs || isThread(report)) {
				return false;
			}

+			if (onlyIncludeChatReport && !isChatReport(report)) {
+				return false;
+			}

			// Only return the room if it has all the participants and is not a policy room
			return !isUserCreatedPolicyRoom(report) && _.isEqual(newParticipantList, _.sortBy(report.participantAccountIDs));
		});
}
```

```js
function navigateToAndOpenReportWithAccountIDs(participantAccountIDs) {
    let newChat = {};
-   const chat = ReportUtils.getChatByParticipants(participantAccountIDs);
+   const chat = ReportUtils.getChatByParticipants(participantAccountIDs, false);
    if (!chat) {
        newChat = ReportUtils.buildOptimisticChatReport(participantAccountIDs);
    }
    const reportID = chat ? chat.reportID : newChat.reportID;

    // We want to pass newChat here because if anything is passed in that param (even an existing chat), we will try to create a chat on the server
    openReport(reportID, [], newChat, '0', false, participantAccountIDs);
    Navigation.dismissModal(reportID);
}
```
### What alternative solutions did you explore? (Optional)
None.



## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Back button ends the split bill page after open user detail page. 

### What is the root cause of that problem?
The following code is called if clicks the user on the split bill confirmation page.
https://github.com/Expensify/App/blob/a2a521d9ac1f22ccf50cd973d7704d82337522da/src/components/MoneyRequestConfirmationList.js#L199-L204

The Money Request page and the Profile page are separate screens, seperate RHP flows.
As a result, the following code will replace navigation routes. and the money request flow will be removed after navigating to the user profile page.
https://github.com/Expensify/App/blob/a2a521d9ac1f22ccf50cd973d7704d82337522da/src/libs/Navigation/linkTo.js#L80-L90

Therefore clicking back will close the modal and end the split bill process.
### What changes do you think we should make in order to solve the problem?
According to the above code comments, replacing routes when changing flow is intended.
However, I think navigating from split bill or money request to user detail page should follow the same flow and not replace routes.
We can change this line as below.
```js
-   if (targetName === NAVIGATORS.RIGHT_MODAL_NAVIGATOR) {
+   if (targetName === NAVIGATORS.RIGHT_MODAL_NAVIGATOR && minimalAction.payload.name !== 'Profile') {
```

### What alternative solutions did you explore? (Optional)
None.



## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task thread gets hidden when clicking on other chats.

### What is the root cause of that problem?
The root cause is that task thread have a empty `lastMessageText`, so `ReportUtils.shouldReportBeInOptionList` returns false, and then gets hidden in LHN.
https://github.com/Expensify/App/blob/197cf7dd27431bf665e2c0b9aa0dabbb3d5465f8/src/libs/ReportUtils.js#L2021-L2024

### What changes do you think we should make in order to solve the problem?
We can change above code as below.
```js
-   if (isThread(report) && !report.lastMessageText) {
+   if (isThread(report) && !isTaskReport(report) && !report.lastMessageText) {
```

After change code as above, task thread does not get hidden, but because task report does not have a `participantAccountIDs`, red dot error will appear in LHN.
We can add `participantAccountIDs` in `ReportUtils.buildOptimisticTaskReport` as below.
```js
function buildOptimisticTaskReport(ownerEmail, ownerAccountID, assigneeAccountID = 0, parentReportID, title, description) {
    return {
        reportID: generateReportID(),
        reportName: title,
        description,
        ownerEmail,
        ownerAccountID,
        // managerEmail: assignee,
        managerID: assigneeAccountID,
        type: CONST.REPORT.TYPE.TASK,
        parentReportID,
        stateNum: CONST.REPORT.STATE_NUM.OPEN,
        statusNum: CONST.REPORT.STATUS.OPEN,
+       participantAccountIDs: [assigneeAccountID],
    };
}
```
### What alternative solutions did you explore? (Optional)
None.





## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For the same account, changing the default contact method on one device is not always dynamically applied to other devices.

### What is the root cause of that problem?
In Profile page, contact method is displayed by below code.
https://github.com/Expensify/App/blob/5cca3c1436cab81b013c7d1d77660b1595a6fcdf/src/pages/settings/Profile/ProfilePage.js#L70-L75

After user changes the default contact method on one device, BE will push the events that contains updated `session` and `personalDetailsList`.
`session` includes new default contact method, but `personalDetailsList` does not have new contact method.

So the default method does not update dynamically.

### What changes do you think we should make in order to solve the problem?
There are two solutions.
. Modify BE in order to push `personalDetailsList` that includes new default contact method.
. Modify App in order to display new default contact method contained in `session`. 
For this, we add `session` props in `ProfilePage.js`, and add `propTypes` and `defaultProps` for `session`.
```js
export default compose(
    ...
    withOnyx({
        ...
+       session: {
+           key: ONYXKEYS.SESSION,
+       },
    }),
)(ProfilePage);
```
And display new default contact method contained in `session`.  as below.
```js
-   title: props.formatPhoneNumber(lodashGet(currentUserDetails, 'login', '')),
+   title: props.formatPhoneNumber(props.session.email),
```
### What alternative solutions did you explore? (Optional)
None.









## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Green dot doesn't appear automatically when assigning task to self repeatedly.

### What is the root cause of that problem?
The root cause is that LHN does not re-render when assigning task to self.

If assigning task to self, BE responds only one report, i.e. task report.
And if assigning task to others, BE will respond two reports.
One is a task report, and another is a assignee's chat report, and assignee's chat report has a `lastMessageText`.


SidebarLinks retrieve reports with using `chatReportSelector`, and in this function there is no `managerEmail`.
So when assigning task to self, side bar will not be re-render.
And when assigning task to others, since there is a another chat report which has a `lastMessageText`, side bar will be re-render.


### What changes do you think we should make in order to solve the problem?
We can add `managerEmail` property to `chatReportSelector` as below.
```js
const chatReportSelector = (report) =>
    report && {
        ...
+       managerEmail: report.managerEmail,
    };
```
### What alternative solutions did you explore? (Optional)
None.








## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App does not remove dot from amount in split bill after first try.

### What is the root cause of that problem?
App convert amount to smallest unit and update `iou.amount` `onyx` data when navigate to next page.
Because amount will be converted to float, so dot will be removed.

But if  `iou.amount` `props`

But app does not update `state`.

After go to next page, amount first convert to string and then convert to number.

So prevdot will be removed.


The root cause is that LHN does not re-render when assigning task to self.

If assigning task to self, BE responds only one report, i.e. task report.
And if assigning task to others, BE will respond two reports.
One is a task report, and another is a assignee's chat report, and assignee's chat report has a `lastMessageText`.


SidebarLinks retrieve reports with using `chatReportSelector`, and in this function there is no `managerEmail`.
So when assigning task to self, side bar will not be re-render.
And when assigning task to others, since there is a another chat report which has a `lastMessageText`, side bar will be re-render.


### What changes do you think we should make in order to solve the problem?
We can add `managerEmail` property to `chatReportSelector` as below.
```js
const chatReportSelector = (report) =>
    report && {
        ...
+       managerEmail: report.managerEmail,
    };
```
### What alternative solutions did you explore? (Optional)
None.



I think clear `linkMetadata` in `expandURLPreview` would be better.
```js
function expandURLPreview(reportID, reportActionID) {
    API.write(
        'ExpandURLPreview', {
            reportID,
            reportActionID,
        },
        {
            optimisticData: [
                {
                    onyxMethod: Onyx.METHOD.MERGE,
                    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`,
                    value: {
                        [reportActionID]: {
                            linkMetadata: [],
                        },
                    }
                },
            ],
        }
    );
}
```




## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy button does not work while requesting money in newly registered users.
(console error does not appear)

### What is the root cause of that problem?
When display `REPORTPREVIEW`, the message is retrieved using `ReportUtils.getReportPreviewMessage`.
https://github.com/Expensify/App/blob/5723571398adc89c53e17e9dfca387493d3ae631/src/components/ReportActionItem/ReportPreview.js#L100

When copy to clipboard, just copy the report action's last html message.
https://github.com/Expensify/App/blob/5723571398adc89c53e17e9dfca387493d3ae631/src/pages/home/report/ContextMenu/ContextMenuActions.js#L175-L176

If reqeust money with newly registered user, BE responds the report action that contains empty html message.
So copy to clipboard does not work.
But if request money with old accounts, the report action contains correct html message, so copy to clipboard works well.

### What changes do you think we should make in order to solve the problem?
We can generate correct message in [copy to clipboard handler](https://github.com/Expensify/App/blob/5723571398adc89c53e17e9dfca387493d3ae631/src/pages/home/report/ContextMenu/ContextMenuActions.js#L174-L195) just like in chat report.
```js
	onPress: (closePopover, {reportAction, selection}) => {
		const message = _.last(lodashGet(reportAction, 'message', [{}]));
-       const messageHtml = lodashGet(message, 'html', '');

+		let messageHtml = '';
+		if (reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.REPORTPREVIEW) {
+			const iouReport = ReportUtils.getReport(ReportActionUtils.getIOUReportIDFromReportActionPreview(reportAction));
+			messageHtml = ReportUtils.getReportPreviewMessage(iouReport, reportAction);
+		} else {
+			messageHtml = lodashGet(message, 'html', '');
+		}

```
### What alternative solutions did you explore? (Optional)
None.





## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App only displays tooltip on long reply in thread message from concierge.

### What is the root cause of that problem?
When hover over three dots in LHN, the report title is displayed by below code.
https://github.com/Expensify/App/blob/882026d659629d47cda410d120a00ac2a2cc0c61/src/components/LHNOptionsList/OptionRowLHN.js#L191-L201

And tooltip is displayed only if `displayNamesWithTooltips.length > 1`.
https://github.com/Expensify/App/blob/882026d659629d47cda410d120a00ac2a2cc0c61/src/components/DisplayNames/index.js#L114-L121

`displayNamesWithTooltips` is generated as below.
https://github.com/Expensify/App/blob/882026d659629d47cda410d120a00ac2a2cc0c61/src/libs/SidebarUtils.js#L299-L300

That is, displayNamesWithTooltips is generated for first 10 participants.
If reply in thread of concierge message, the report participants includes concierge and current user, so `displayNamesWithTooltips.length > 1` will be true, and then tooltip is shown.
But on the reply in thread report of long text, the report participants only include current user, so tooltip is not shown.

### What changes do you think we should make in order to solve the problem?
If this is not intended, we can remove checking `displayNamesWithTooltips.length` as below.

```js
-	{this.props.displayNamesWithTooltips.length > 1 && Boolean(this.state.isEllipsisActive) && (
+	{Boolean(this.state.isEllipsisActive) && (
		<View style={styles.displayNameTooltipEllipsis}>
			<Tooltip text={this.props.fullTitle}>
				{/* There is some Gap for real ellipsis so we are adding 4 `.` to cover */}
				<Text>....</Text>
			</Tooltip>
		</View>
	)}

```
### What alternative solutions did you explore? (Optional)
None.

**Comment by StevenKKC** [comment] 2023-07-11 06:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App only displays tooltip on long reply in thread message from concierge.

### What is the root cause of that problem?
When hover over three dots in LHN, the report title is displayed by below code.
https://github.com/Expensify/App/blob/882026d659629d47cda410d120a00ac2a2cc0c61/src/components/LHNOptionsList/OptionRowLHN.js#L191-L201

And tooltip is displayed only if `displayNamesWithTooltips.length > 1`.
https://github.com/Expensify/App/blob/882026d659629d47cda410d120a00ac2a2cc0c61/src/components/DisplayNames/index.js#L114-L121

`displayNamesWithTooltips` is generated as below.
https://github.com/Expensify/App/blob/882026d659629d47cda410d120a00ac2a2cc0c61/src/libs/SidebarUtils.js#L299-L300

That is, displayNamesWithTooltips is generated for first 10 participants.
If reply in thread of concierge message, the report participants includes concierge and current user, so `displayNamesWithTooltips.length > 1` will be true, and then tooltip is shown.
But on the reply in thread report of long text, the report participants only include current user, so tooltip is not shown.

### What changes do you think we should make in order to solve the problem?
If this is not intended, we can remove checking `displayNamesWithTooltips.length` as below.

```js
-	{this.props.displayNamesWithTooltips.length > 1 && Boolean(this.state.isEllipsisActive) && (
+	{Boolean(this.state.isEllipsisActive) && (
		<View style={styles.displayNameTooltipEllipsis}>
			<Tooltip text={this.props.fullTitle}>
				{/* There is some Gap for real ellipsis so we are adding 4 `.` to cover */}
				<Text>....</Text>
			</Tooltip>
		</View>
	)}

```
### What alternative solutions did you explore? (Optional)
None.

**Comment by Skalakid** [comment] 2023-07-12 13:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App does not display tooltip (to display full message) on hover over three dots in LHN for long text reply in thread report

### What is the root cause of that problem?
The problem is with the condition that defines if the tooltip should render:
```
 {this.props.displayNamesWithTooltips.length > 1 && Boolean(this.state.isEllipsisActive) && (
 ...
```
As we can see we check if `displayNamesWithTooltips` array has more than 1 item. But what if we have 1 item but with a really long display name? We don't cover this case.

### What changes do you think we should make in order to solve the problem?


In my opinion, we should change the mentioned condition in `DisplayNames/index.js` to:
```
 {this.props.displayNamesWithTooltips.length > 1 || Boolean(this.state.isEllipsisActive) && (
 ...
```
Changing `&&` to `||` will make this condition more flexible and will fix the problem

**Comment by bfitzexpensify** [comment] 2023-07-17 09:33
I think it makes sense to have the LHN tooltip for all chats where we can't show the full message in the LHN

**Comment by bfitzexpensify** [comment] 2023-07-19 08:38
@allroundexperts given that, do we have a proposal that fits best?

**Comment by NikkiWines** [comment] 2023-07-25 00:21
Oops sorry for the delay here, didn't realize you all were waiting on me. 

Just a quick clarification, since I'm seeing different behavior locally than what's described in the OP 

> 1. Open the app
> 2. Search for new user eg: [testing123467@gmail.com](mailto:testing123467@gmail.com)
> 3. Concierge will display 'first time chatting' message, hover on it and click on reply in thread
> 4. In LHN, hover on three dots on the reply in thread report of concierge and observe that it displays the complete message in tooltip
> 5. Open any other report and send long text
> 6. Click on reply in thread on long text
> 7. In LHN, hover on three dots on the reply in thread report of long text and observe that app does not display any tooltip

For step 4, I don't see the full message as a tooltip. In fact, the behavior is consistent in that the chats that don't have a display name associated with them do not have a tooltip. 

If this is in fact still a bug and it's specific to circumstances where the user is creating a thread from a whisper message from concierge then I think we should dig into whether or not we want whisper messages to be interactive 🤔

**Comment by NikkiWines** [comment] 2023-07-25 00:56
Oh, yep @allroundexperts, you're right - thank you! That's a very specific place to hover 😄 

In that case, I can reproduce the bug, and I asked about whether or not we want to allow threading from Concierge whispers, and seems we do. Given that, I agree with @allroundexperts's assessment and we can move forward with @StevenKKC's proposal

**Comment by StevenKKC** [comment] 2023-07-25 09:51
@allroundexperts [PR](https://github.com/Expensify/App/pull/23533) is ready for review.

**Comment by bfitzexpensify** [comment] 2023-08-07 12:58
Job assigned July 25th, merged July 26th — eligible for #urgency bonus 

Amounts owed here for payment:

**Reporting:** @dhanashree-sawant - $250 - paid out via Upwork ✅ 
**Contributor:** @StevenKKC - $1500 (contributor + #urgency bonus) - paid out via Upwork ✅ 
**C+**: @allroundexperts - $1500 (C+ & #urgency bonus) - to be paid via manual request

**Comment by bfitzexpensify** [comment] 2023-08-10 14:09
Bump to complete BZ checklist @allroundexperts - thank you!

**Comment by NikkiWines** [comment] 2023-08-14 14:07
@allroundexperts please complete the [following checklist](https://github.com/Expensify/App/issues/22609#issuecomment-1658919359) 🙇

**Comment by JmillsExpensify** [comment] 2023-08-15 16:19
Reviewed the details for @allroundexperts. Approved for payment in NewDot based on the BZ payment summary above.

**Comment by bfitzexpensify** [comment] 2023-08-17 10:41
>Open any report and send a long message (more than 2 lines).
>Start a thread from the sent message.
>In LHN, hover on three dots on the message of the thread report.
>Verify that the app displays a tooltip showing the entire sent message.

I like this, simple and effective. I've opened https://github.com/Expensify/Expensify/issues/308796 to add this as a regression test. 

All payments now complete, as is the BZ checklist, so we're all done here, closing this out. Thanks everyone!

**Closed by bfitzexpensify** 2023-08-17 10:41 UTC
Labels: External, Daily, Awaiting Payment, Bug
