### ISSUE TITLE
[HOLD for payment 2024-08-13] [$250] iOS - Workspace - Dropdown button is not disabled when no selection is made

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46619] opened 2024-07-31 22:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/45732
**Version Number:** 9.0.15-4
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings > Members.
3. Invite a few members if there is no members.
4. Long press on any member.
5. Tap Select.
6. Unselect the member.
7. Tap on the dropdown button.

## Expected Result:
Dropdown button should be disabled when no selection is made (same behavior on Search).

## Actual Result:
Dropdown button is not disabled when no selection is made. Remove members option is present when no member is selected.

This issue happens for other pages like Categories, Taxes, Tags etc

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bacdc03a-123c-41c8-b2a1-0caea99e0bcf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01646ead25f1035d7c</li>
        <li>Upwork Job ID: 1818788590509081901</li>
        <li>Last Price Increase: 2024-07-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by neonbhai** [comment] 2024-07-31 22:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dropdown button is not disabled when no selection is made

### What is the root cause of that problem?
We don't disable the button when no members are selected:

### What changes do you think we should make in order to solve the problem?
We will add a disabled prop checking `selectedEmployees.length` here:


https://github.com/Expensify/App/blob/00a45ac282dc5fe95f008600908ac7301be75e68/src/pages/workspace/WorkspaceMembersPage.tsx#L510-L515

### Additionally:
We will also not add the Remove Members option here if `selectedEmployees.length` is zero
https://github.com/Expensify/App/blob/00a45ac282dc5fe95f008600908ac7301be75e68/src/pages/workspace/WorkspaceMembersPage.tsx#L467-L472

**Comment by neonbhai** [comment] 2024-07-31 23:46
Thank you for assigning, raising PR soon!

**Comment by jayeshmangwani** [comment] 2024-08-01 11:12
@neonbhai Please let us know once you raise the PR.

**Comment by roryabraham** [comment] 2024-08-01 20:29
confirmed that this is fixed on staging

**Comment by lschurr** [comment] 2024-08-13 18:04
@neonbhai - Offer sent in Upwork :)

**Comment by lschurr** [comment] 2024-08-13 18:14
All set. Payment summary is correct.

**Closed by lschurr** 2024-08-13 18:14 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by jayeshmangwani** [comment] 2024-08-13 18:18
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/46096
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/46096#issuecomment-2286849031
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- [ ]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **NO, IMO, there's no need to create a test for this since we missed including it as part of the new feature.**
- [ ]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by jayeshmangwani** [comment] 2024-08-15 18:15
Requested on ND as per https://github.com/Expensify/App/issues/46619#issuecomment-2286820306

**Comment by JmillsExpensify** [comment] 2024-08-21 10:56
$250 approved for @jayeshmangwani
