### ISSUE TITLE
Always close the statement even after visiting multiple statement pages

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#9712] opened 2022-07-05 18:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Copy this URL into your browser: https://new.expensify.com/statements/202112/
2. Then this one: https://new.expensify.com/statements/202201/
3. Then this one: https://new.expensify.com/statements/202202/
4. Click the `X` on the statement page in the rightDocked side modal - observe you're returned to the URL in #2. 
5. Click the `X` again - observe that you're returned to the URL in #1. 
6. Click the `X` again - observe that the rightDocked side modal closes

## Expected Result:
Describe what you think should've happened
1. Clicking the close button (`X`) on the modal should close the statement modal and not redirect to the last statement you visited

## Actual Result:
Describe what actually happened
1. You get redirected to the last statement 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Yes, you can either just adjust the URL or just keep pressing `X` until you close the modal out

## Platform:

Where is this issue occurring?

- Web x
- iOS
- Android
- Desktop App
- Mobile Web x

**Version Number:** v1.1.78-8
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![9aAfBSiKNJ](https://user-images.githubusercontent.com/16232057/177435268-7a8598b2-68c2-4afc-a00d-bd439aff34d7.gif)

**Upwork URL:** https://www.upwork.com/jobs/~01ce48a3c10dcdbe87
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2022-07-05 22:45
Job on Upwork here: https://www.upwork.com/jobs/~01ce48a3c10dcdbe87

@thienlnam, just to check, does the contributor need access to a beta for this?

**Comment by parasharrajat** [comment] 2022-07-05 22:54
Can someone improve _the Action Performed_ and add steps for _how to navigate to statements_?

**Comment by blockchainFull** [comment] 2022-07-05 23:20
I think we need to check route, state, history of this project.
All the redirects depends on them in react.

**Comment by marcaaron** [comment] 2022-07-05 23:20
+1 - it would be helpful to have a video of the existing behavior. I'm not even sure what is being asked here.

**Comment by trjExpensify** [comment] 2022-07-05 23:56
Fair, it's just copying those three URLs above into the browser and clicking `X` on the modal. I've improve the steps a bit with the below to make that clearer, gif included! 

1. Copy this URL into your browser: https://new.expensify.com/statements/202112/
2. Then this one: https://new.expensify.com/statements/202201/
3. Then this one: https://new.expensify.com/statements/202202/
4. Click the `X` on the statement page in the rightDocked side modal - observe you're returned to the URL in #2. 
5. Click the `X` again - observe that you're returned to the URL in #1. 
6. Click the `X` again - observe that the rightDocked side modal closes

@thienlnam can confirm if there are beta requirements to know about for this project for external.

**Comment by parasharrajat** [comment] 2022-07-06 00:15
I may have found another issue. When I open the URL https://new.expensify.com/statements/202112/ on the browser. I see a blank page. 
![image](https://user-images.githubusercontent.com/24370807/177435751-6d25b509-ca15-4a97-b5a1-a270325137aa.png). 

Request return 404 for the page (the reason could be that report is not generated for my account yet). But I think it should be 200 with some sort of UI Or we can handle this ourselves in the App and show a UI when 404 is returned. 

Logic would be: 
1. Make the fetch call directly to the statement resource URL and do not pass the URL to `src` of the iframe we are using. 
2. Now based on the response shows the Error UI etc. 
3. If the response is 200, use the `frame.srcdoc` prop and assign it to the response body.

**Comment by marcaaron** [comment] 2022-07-06 00:23
Ok, super weird now that I understand it...

@parasharrajat nice catch, but not really what we are trying to fix here so maybe we can create a new issue for that.

**Comment by marcaaron** [comment] 2022-07-06 00:26
`WalletStatementPage` is doing a `Navigation.dismissModal(true)`

https://github.com/Expensify/App/blob/35a41d99fe751d9952fa5401bd38c87d6bf3d5ba/src/pages/wallet/WalletStatementPage.js#L110-L110

So why are we trying to navigate to the previous route in the `history`? Maybe this will be fixed in https://github.com/Expensify/App/pull/9718.

**Comment by marcaaron** [comment] 2022-07-06 00:27
@thienlnam Anyway to reproduce this on dev? When I check out a statement it just looks like this...

![2022-07-05_14-27-25](https://user-images.githubusercontent.com/32969087/177437894-18c9ac22-75db-4374-994b-bfb030fac453.png)

**Comment by thienlnam** [comment] 2022-07-06 00:36
> WalletStatementPage is doing a Navigation.dismissModal(true)

Yeah I'm not sure, I messed around with it a bit and it seemed to be some react-navigation bug.  Another thing I was thinking was that the way we've been accessing the statement is modifying the URL so maybe it has to do with that? But the history seems intact so I'm not sure


> @thienlnam Anyway to reproduce this on dev? When I check out a statement it just looks like this...

Should be able to see the statement on dev, any console errors when you see this in the modal? Though I think if you're able to bring up the modal, you should be able to test it still by navigating to multiple statement links and clicking the X and just ignoring what is inside the modal 

> @thienlnam can confirm if there are beta requirements to know about for this project for external.

I think you can still test this without seeing what is actually in the modal since this is mostly about the navigation part of the modal

**Comment by marcaaron** [comment] 2022-07-06 00:47
>seemed to be some react-navigation bug

I would guess it has more to do with our ever evolving "custom actions" than any issue with `react-navigation`, but both are possible. Will do some debugging.

**Comment by marcaaron** [comment] 2022-07-06 01:10
What's even weirder is that this doesn't happen with something like the "settings" page which is also a "modal stack". The state looks the same as this more or less.

**Comment by thienlnam** [comment] 2022-07-06 01:16
> The navigation state looks normal, but for some reason going back here causes the entire app to reload

Yeah I think it's because we're accessing it by modifying the URL instead of having a dedicated button that opens `Navigation.navigate(statement_route)`.  Kind of like how if you click on another chat in the LHN the app won't reload, but if you manually edit the reportID in the URL it will cause it to reload.  Not sure how it all plays into how the last page in the stack is the previous statement link though

**Comment by marcaaron** [comment] 2022-07-06 01:24
Ah ok, so, this is not unique to the statements. The same issue will happen if you navigate to something like

https://new.expensify.com/settings/payments
https://new.expensify.com/settings/preferences

**Comment by marcaaron** [comment] 2022-07-06 01:26
P.S. this issue is fixed by https://github.com/Expensify/App/pull/9718 so I'm going to make it internal and assign myself.

**Comment by trjExpensify** [comment] 2022-07-06 12:07
Kewl, taken it down from Upwork.

**Closed** 2022-07-20 17:54 UTC
Labels: Engineering, Weekly, Improvement, Internal, Overdue
