### ISSUE TITLE
[$250] Invoice - 0.00 displayed on Pay button for invoice receiver

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51312] opened 2024-10-23 08:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5113365
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/ and log in
2. Create a workspace if there is no any
3. Navigate to the workspace settings > More features
4. Enable the Invoice option
5. Click on FAB > Send invoice
6. Select an invoice receiver
7. Enter the company info and send the invoice
8. Log in with the invoice receiver account in incognito
9. Navigate to the invoice room

## Expected Result:
The correct amount is displayed on the Pay button

## Actual Result:
0.00 is displayed on the Pay button

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d265440b-b54a-44c7-b8c4-bc5581f0b9ba

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849917912281837951</li>
        <li>Upwork Job ID: 1849917912281837951</li>
        <li>Last Price Increase: 2024-11-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @NikkiWines</details>

**Comment by IuliiaHerets** [comment] 2024-10-23 08:46
We think that this bug might be related to #vip-bills

**Comment by IuliiaHerets** [comment] 2024-10-23 08:46
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Tony-MK** [comment] 2024-10-23 22:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

0.00 displayed on Pay button for invoice receiver

### What is the root cause of that problem?

Since the `nonReimbursableTotal` for invoice reports is the same as it's `total`, [`reimbursableSpend`], from the [`ReportPreview.getMoneyRequestSpendBreakdown`](https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/components/ReportActionItem/ReportPreview.tsx#L133) function will be `0`.

https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/libs/ReportUtils.ts#L2760-L2761


### What changes do you think we should make in order to solve the problem?


Change the [`ReportPreview.getSettlementAmount`](https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/components/ReportActionItem/ReportPreview.tsx#L237) function over [here](https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/components/ReportActionItem/ReportPreview.tsx#L246) to use `totalDisplaySpend` if `isInvoiceRoom` is `true`.

https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/components/ReportActionItem/ReportPreview.tsx#L246

```
return CurrencyUtils.convertToDisplayString(
         isInvoiceRoom ? totalDisplaySpend : reimbursableSpend, 
         iouReport?.currency
);
```

**Comment by Tony-MK** [comment] 2024-10-23 22:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

0.00 displayed on Pay button for invoice receiver

### What is the root cause of that problem?

Since the `nonReimbursableTotal` for invoice reports is the same as it's `total`, the `reimbursableSpend`, which is calculated from the [`ReportPreview.getMoneyRequestSpendBreakdown`](https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/components/ReportActionItem/ReportPreview.tsx#L133) function, will be `0`.

https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/libs/ReportUtils.ts#L2760-L2761


### What changes do you think we should make in order to solve the problem?


Change the [`ReportPreview.getSettlementAmount`](https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/components/ReportActionItem/ReportPreview.tsx#L237) function over [here](https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/components/ReportActionItem/ReportPreview.tsx#L246) to use `totalDisplaySpend` if `isInvoiceRoom` is `true`.

https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/components/ReportActionItem/ReportPreview.tsx#L246

```
return CurrencyUtils.convertToDisplayString(
         isInvoiceRoom ? totalDisplaySpend : reimbursableSpend, 
         iouReport?.currency
);
```

**Comment by MitchExpensify** [comment] 2024-10-25 20:56
Lets fix!

**Comment by FitseTLT** [comment] 2024-10-25 22:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invoice - 0.00 displayed on Pay button for invoice receiver

### What is the root cause of that problem?
reimbursable spend is calculated by subtracting non-reimbursable from the total
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/ReportUtils.ts#L2776
but for invoice `nonReimbursableSpend` is equal to the total
### What changes do you think we should make in order to solve the problem?

We should add an exception for invoices and set `nonReimbursableSpend` 0, so:
```
nonReimbursableSpend = isInvoiceReport(report) ? 0 : nonReimbursableSpend;
            const reimbursableSpend = totalDisplaySpend - nonReimbursableSpend;

```
then also here
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/IOU.ts#L6784
```
    let total = (iouReport?.total ?? 0) - (isInvoiceReport ? 0 : iouReport?.nonReimbursableTotal ?? 0);

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-10-29 14:09
@dukenv0307 I am surprised how you are taking this matter into a discussion because the missed point is important and will obviously create a regression and also you shouldn't forget the suggested changes were
>const reimbursableSpend = isInvoiceReport(report) ? totalDisplaySpend : totalDisplaySpend - nonReimbursableSpend;

which will only fix reimbursableSpend but doesn't fix the value for nonReimbursableSpend here
https://github.com/Expensify/App/blob/f251dbcdfdafc492d9a9908cbf40e4630b7b6d9d/src/libs/ReportUtils.ts#L2764
that would cause the `out-of-pocket` amount to be displayed in money report
<img width="441" alt="image" src="https://github.com/user-attachments/assets/383eea44-0e8a-4d7d-b6bd-8b7ce1d60f67">

**Comment by NikkiWines** [comment] 2024-11-01 20:59
Sorry for the delay. I'm not sure either solution is entirely correct to be honest. 

@twilight2294 you're correct in your statement here:

> For invoices we ask the end user to pay the amount and hence it i same as total

But your solution doesn't fully resolve the issue, since (as @FitseTLT outlined) there are a couple of other cases where we end up having a display mismatches due to the same type of `totalDisplaySpend - nonReimbursableSpend` calculation.

It's true that this issue was opened for this particular flow, but we prefer more comprehensive solutions that solve the problem in its entirety, if there's the same bug in multiple flows/areas. 

@FitseTLT, I don't think we want to modify `nonReimbursableSpend` here - @twilight2294  is right that value correct, it's the logic used to determine `totalDisplaySpend` (or `total`) that's incorrect (in multiple locations) 

Ideally, I think we'd add a case or adjustment in all the relevant areas to adjust the `totalSpend`/`total` calculation, based on whether or not the report is an invoice.

**Comment by FitseTLT** [comment] 2024-11-01 21:20
>@FitseTLT, I don't think we want to modify nonReimbursableSpend here - @twilight2294 is right that value correct, it's the logic used to determine totalDisplaySpend (or total) that's incorrect (in multiple locations)

@NikkiWines @twilight2294 is not correct. If the value of nonReimbursableSpend is not going to be fixed then the money report view will show `out of pocket`(non reimbursable) and `Company Spend`(reimbursable) value equal to the total which is wrong and confusing and that should be fixed too.
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/25eb53ee-4752-4458-ae4d-d1241f159e33">

**Comment by MitchExpensify** [comment] 2024-11-04 23:36
What are your thoughts on next steps here @dukenv0307 ?

**Comment by NikkiWines** [comment] 2024-11-05 02:30
> I agree with you @NikkiWines !, how should we move forward here ?

@twilight2294 The best thing to do would be to update your proposal, as @Tony-MK has done, to account for a new approach. 

> @NikkiWines @twilight2294 is not correct. If the value of nonReimbursableSpend is not going to be fixed then the money report view will show out of pocket(non reimbursable) and Company Spend(reimbursable) value equal to the total which is wrong and confusing and that should be fixed too.

@FitseTLT I think there may be a misunderstanding. I agree that we need to update the view to show the correct value for `out of pocket spend` when the report is an invoice - but I think the correct way to do that is by accounting for whether or not the report is an invoice when we're determining the amount to display in the component itself - not by changing the `nonReimbursableSpend` value that we're returning from the backend. Hopefully that makes sense? 

> According this https://github.com/Expensify/App/issues/51312#issuecomment-2452582144, the solution for my https://github.com/Expensify/App/issues/51312#issuecomment-2433575175 already did not adjust or modify the value for reimbursableSpend/ nonReimbursableSpend in the [getMoneyRequestSpendBreakdown](https://github.com/Expensify/App/blob/b87ec1ffed2887cf53cfb3bf25a34f691313a9bd/src/libs/ReportUtils.ts#L2764) function.

@dukenv0307, can you review @Tony-MK's updated proposal, please 🙇 However, @Tony-MK, I don't think we'd want to update `convertToDisplayString` to do anything over than convert the inputted value to a formatted string, as that muddies the purpose of the function.

**Comment by Tony-MK** [comment] 2024-11-05 08:55
> @dukenv0307, can you review @Tony-MK's updated proposal, please 🙇 However, @Tony-MK, I don't think we'd want to update convertToDisplayString to do anything over than convert the inputted value to a formatted string, as that muddies the purpose of the function.


I believe `totalDisplaySpend` is already a number but there are already several functions where `totalDisplaySpend` is used with `convertToDisplayString` like my proposal such as [`getReportAutomaticallyForwardedMessage`](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/ReportUtils.ts#L4680), [`getIOUForwardedMessage`](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/ReportUtils.ts#L4699) and [`getIOUReportActionMessage`](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/ReportUtils.ts#L4728).

**Comment by Tony-MK** [comment] 2024-11-05 08:56
> @dukenv0307, can you review @Tony-MK's updated proposal, please 🙇 However, @Tony-MK, I don't think we'd want to update convertToDisplayString to do anything over than convert the inputted value to a formatted string, as that muddies the purpose of the function.


I believe `totalDisplaySpend` is already a number but there are already several functions where `totalDisplaySpend` is used with `convertToDisplayString` like in my proposal such as [`getReportAutomaticallyForwardedMessage`](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/ReportUtils.ts#L4680), [`getIOUForwardedMessage`](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/ReportUtils.ts#L4699) and [`getIOUReportActionMessage`](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/ReportUtils.ts#L4728).

**Comment by FitseTLT** [comment] 2024-11-05 11:18
> BTW I think it would be better to update logic inside `getMoneyRequestSpendBreakdown` like @twilight2294's [proposal](https://github.com/Expensify/App/issues/51312#issuecomment-2431558200)

I am sorry @dukenv0307 I am not understanding why we are still in a re-review stage. As you have stated in you review this can be ideally fixed in the BE, because I don't think paying invoices is a new feature and this problem existed for long and this might be a new change in BE that is setting non reimbursable value same as the total. So if the current behavior is correct or if FE change is preferred I have already stated a full proposal which is accepted.
And on this 
>@FitseTLT I think there may be a misunderstanding. I agree that we need to update the view to show the correct value for out of pocket spend when the report is an invoice - but I think the correct way to do that is by accounting for whether or not the report is an invoice when we're determining the amount to display in the component itself - not by changing the nonReimbursableSpend value that we're returning from the backend.

@dukenv0307  I did not say we need a backend change I am only suggesting a change in `getMoneyRequestSpendBreakdown` by changing the value of nonReimbursableSpend too as it is used in money report view to show the value that is payed `out of pocket` and making that update in that function is more central way of doing it instead of changing it in specific instances of the functions usage. Currently of course it is only [here](https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/components/ReportActionItem/MoneyReportView.tsx#L58) that we use the value of `nonReimbursable` value returned from the function but in all other instances we are only using the total and reimbursable values but there could be case in the future where we might want to use nonReimbursable so I still think we need to getMoneyRequestSpendBreakdown just like my proposal which returns nonReimbursableSpend as 0 for invoices reports.

**Comment by FitseTLT** [comment] 2024-11-07 12:18
> > I think the correct way to do that is by accounting for whether or not the report is an invoice when we're determining the amount to display in the component itself - not by changing the nonReimbursableSpend value that we're returning from the backend.
> 
> @FitseTLT Can you update your proposal based on this comment? We should apply the different logic for invoice report (i.e: fix out of pocket bug)

My proposal is already handling it.
I am suggesting to return 0 for nonReimbursableSpend in `getMoneyRequestSpendBreakdown` for invoice report
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/ReportUtils.ts#L2776
but for invoice `nonReimbursableSpend` is equal to the total

We should add an exception for invoices and set `nonReimbursableSpend` 0, changing:
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/ReportUtils.ts#L2772
```
nonReimbursableSpend = isInvoiceReport(report) ? 0 : nonReimbursableSpend;
```
that will fix the reimbursable we calculate here
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/ReportUtils.ts#L2776
and we will have correct values returned by getMoneyRequestSpendBreakdown
that will fix, currently, the only instance where we use nonReimbursable value we use on MoneyReportView here
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/components/ReportActionItem/MoneyReportView.tsx#L58

**Comment by Tony-MK** [comment] 2024-11-07 22:40
## Proposal
[Updated](https://github.com/Expensify/App/issues/51312#issuecomment-2433575175) conditions for the affected components display the correct amount. 

##

> > I agree that we need to update the view to show the correct value for out of pocket spend when the report is an invoice
> 
> @Tony-MK @twilight2294 Can you share your screenshot about this bug.

Hey @dukenv0307, when testing my proposal, the "out of pocket" bug was not applicable since my proposal does not change either the value of `total`, `reimbursableSpend`, or `nonReimbursableSpend` in the [getMoneyRequestSpendBreakdown](https://github.com/Expensify/App/blob/b87ec1ffed2887cf53cfb3bf25a34f6913a9bd/src/libs/ReportUtils.ts#L2764) function.

https://github.com/Expensify/App/blob/aedbbde0317b720151a75dbe0b6a7ddea52a20cd/src/components/ReportActionItem/MoneyReportView.tsx#L60

Furthermore, the `reimbursableSpend` for invoice reports will be `0`, like in this instance, hence, the breakdown will not show since `shouldShowBreakdown` will be `false`

If `shouldShowTotal` is `true`, only the `total` can be shown and the value of `total` is already correct.

**Comment by NikkiWines** [comment] 2024-11-13 00:47
@dukenv0307 just fyi from [this earlier comment](https://github.com/Expensify/App/issues/51312#issuecomment-2456098416) I think we'd rather not alter the value of `nonReimbursableSpend` since it's the value we're returning from the backend. 🙇

**Comment by Tony-MK** [comment] 2024-11-13 08:28
> @dukenv0307 just fyi from [this earlier comment](https://github.com/Expensify/App/issues/51312#issuecomment-2456098416) I think we'd rather not alter the value of `nonReimbursableSpend` since it's the value we're returning from the backend. 🙇

@dukenv0307, Can you explain why my [proposal](https://github.com/Expensify/App/issues/51312#issuecomment-2433575175) is not sufficient. Both prospals have more or less the same approach by altering the value of `nonReimbursableSpend` but mine considers a different approach and works fine.

**Comment by FitseTLT** [comment] 2024-11-13 11:20
@dukenv0307 [Updated](https://github.com/Expensify/App/issues/51312#issuecomment-2438957599) to give an alternative according to https://github.com/Expensify/App/issues/51312#issuecomment-2472044160

**Comment by FitseTLT** [comment] 2024-11-14 11:51
> @FitseTLT @twilight2294 Since you're fixing the `getMoneyRequestSpendBreakdown` function that is used in many places. Did you cover these cases?

@dukenv0307 It is only here
https://github.com/Expensify/App/blob/4d9be4eb2537b49fa6cf35135770cf3c6d62a1cd/src/components/ReportActionItem/MoneyReportView.tsx#L58
that we are using the nonReimbursableSpend (which is the value which we are not fixing in getMoneyRequestSpendBreakdown) and as you can clearly see from the condition here
https://github.com/Expensify/App/blob/4d9be4eb2537b49fa6cf35135770cf3c6d62a1cd/src/components/ReportActionItem/MoneyReportView.tsx#L58
we only show the break down when there is some value to be paid from the company (company spend) and some value paid out of pocket which sum up to the totalDisplaySpend. But in invoices case we know all the 0 amount is paid out of pocket so we should hide the break down. I had already updated my proposal notifying you [here](https://github.com/Expensify/App/issues/51312#issuecomment-2473286024) before even you asked 👍

**Comment by Tony-MK** [comment] 2024-11-15 15:06
> @Tony-MK I don't think it's a good idea to change formattedAmount in the specific place. We're using getMoneyRequestSpendBreakdown in many places, so I think the best solution would be fixing the logic in getMoneyRequestSpendBreakdown to avoid the inconsistency bug.

>> Ideally, I think we'd add a case or adjustment in all the relevant areas to adjust the totalSpend/total calculation, based on whether or not the report is an invoice - instead of adjusting the value for reimbursableSpend/ nonReimbursableSpend themselves. Hope this makes sense!


Hey @dukenv0307, according to the @NikkiWines responses, [here](https://github.com/Expensify/App/issues/51312#issuecomment-2456098416) and [here](https://github.com/Expensify/App/issues/51312#issuecomment-2452582144), I believe she suggested that we should determine the **_amount to display in the component itself_** instead of altering the values of `reimbursableSpend/ nonReimbursableSpend` in the `getMoneyRequestSpendBreakdown` function.

I believe is this the direction we are supposed to be taking.

Or am I mistaken?

Thanks

**Comment by FitseTLT** [comment] 2024-11-18 09:00
@dukenv0307 Even with your logic here

>For Out of pocket error, we should use totalDisplaySpend - nonReimbursableSpend instead of checking this is the invoice request or not

It's not about fixing that value in regards to out of pocket error, it's all about should we show it or not? and the chosen proposal is trying to fix the value that is displayed which leads to showing Out of pocket `0`. But there is no point in showing zero values in the breakdown. You can clearly infer that from here
https://github.com/Expensify/App/blob/4d9be4eb2537b49fa6cf35135770cf3c6d62a1cd/src/components/ReportActionItem/MoneyReportView.tsx#L60
We don't show breakdown if either out of pocket or company spend values are zero. BTW this is the only reason I didn't chose to fix the value displayed I could have easily done that. However it is totally illogical to show it and if we are not going to show it we shouldn't fix it. In terms of how we should hide it I have also gave you another option of checking the equality of reimbursable and nonReimbursable, we can should whichever fits better. 👍 

cc @NikkiWines

**Comment by FitseTLT** [comment] 2024-11-19 10:25
@dukenv0307  bump on my comment [here](https://github.com/Expensify/App/issues/51312#issuecomment-2482332801) The proper proposal is not selected on the last review. Thx 👍 

cc @NikkiWines

**Comment by NikkiWines** [comment] 2024-11-20 12:55
sorry for the delay, doing a little bit more investigation into this to confirm if the value coming from the backend is incorrect or not

**Comment by FitseTLT** [comment] 2024-11-20 14:39
> sorry for the delay, doing a little bit more investigation into this to confirm if the value coming from the backend is incorrect or not

Ok thanks @NikkiWines When you decide to fix it in FE please give a sec to my [comment](https://github.com/Expensify/App/issues/51312#issuecomment-2482332801), I think there is no purpose of showing `0` `out of pocket` in the report view break down instead we should hide it. 👍

**Comment by NikkiWines** [comment] 2024-11-22 19:20
Not overdue, investigation ongoing

**Comment by NikkiWines** [comment] 2024-11-27 16:59
Internal PR is in review for this now. @MitchExpensify can we offer some level of compensation here for the time/effort spent trying to resolve this issue? Thanks🙇

**Comment by MitchExpensify** [comment] 2024-11-30 17:26
For sure! @FitseTLT @dukenv0307 does $100 each sound fair for your time here?

**Comment by FitseTLT** [comment] 2024-11-30 18:26
> For sure! @FitseTLT @dukenv0307 does $100 each sound fair for your time here?

I am Ok with it 👍

**Comment by MitchExpensify** [comment] 2024-12-02 16:25
Great, offers sent to you both [here](https://www.upwork.com/jobs/~021863619397060460354) @FitseTLT @dukenv0307

**Comment by MitchExpensify** [comment] 2024-12-03 23:09
@FitseTLT - Paid
@dukenv0307 - Waiting on acceptance

**Comment by MitchExpensify** [comment] 2024-12-05 22:29
Still waiting for you to accept the offer here @dukenv0307 https://www.upwork.com/nx/wm/offer/105160257

**Comment by MitchExpensify** [comment] 2024-12-11 20:23
Paid thanks!

**Closed by MitchExpensify** 2024-12-11 20:23 UTC
Labels: Reviewing, Daily, Internal, Bug
