### ISSUE TITLE
[$1000] LHN - Uh-oh something went wrong screen displayed after splitting bill and returning online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26885] opened 2023-09-06 15:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and log into the same account on main and secondary device
2. Disable the internet on the main device
3. Tap FAB > Split bill
4. Split bill with 2 users
5. On the secondary device split the same bill with same users
6. Enable the internet connection on the main device
5. Navigate to LHN

## Expected Result:
User is returned online and can keep using the app

## Actual Result:
After returning online the "Uh-oh something went wrong" screen is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e50e521e-fbbe-4786-911c-5abc6176e2f5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018cf27bdeeb75326a</li>
        <li>Upwork Job ID: 1699877376966991872</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2023-09-07 10:05
Reassigning as I'm going OOO until Tuesday! (I'm in PORTUGAL @NicMendonca !)

**Comment by MitchExpensify** [comment] 2023-09-07 10:06
Will take it back upon return

**Comment by MitchExpensify** [comment] 2023-09-12 14:35
Taking this back @NicMendonca , thanks for looking after it while I was on vacation!

**Comment by MitchExpensify** [comment] 2023-09-18 21:47
Doubled!

**Comment by studentofcoding** [comment] 2023-09-18 23:03
Tested on Android, iPhone and Mac but the bug didn’t showed and it's run as Expected outcomes

**Comment by zukilover** [comment] 2023-09-18 23:17
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Splitting bill on offline mode causes screen error

### What is the root cause of that problem?
`MoneyRequestParticipantsSelector` is evaluating new chat options within `useEffect`. This sometimes lead to infinite loop:
https://github.com/Expensify/App/blob/2905e6d9115522f6d4a4cd0b510dd580ccf5894e/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L207-L209

### What changes do you think we should make in order to solve the problem?
Memoize `chatOptions` and move it out of the `useEffect` to avoid memory leak , e.g.:
```
    const chatOptions = useMemo(() => OptionsListUtils.getNewChatOptions(
        reports,
        personalDetails,
        betas,
        searchTerm,
        participants,
        CONST.EXPENSIFY_EMAILS,

        // If we are using this component in the "Request money" flow then we pass the includeOwnedWorkspaceChats argument so that the current user
        // sees the option to request money from their admin on their own Workspace Chat.
        iouType === CONST.IOU.MONEY_REQUEST_TYPE.REQUEST,

        // We don't want to include any P2P options like personal details or reports that are not workspace chats for certain features.
        !isDistanceRequest,
    ), [betas, reports, participants, personalDetails, translate, searchTerm, iouType, isDistanceRequest])
    
    useEffect(() => {
        
        setNewChatOptions({
            recentReports: chatOptions.recentReports,
            personalDetails: chatOptions.personalDetails,
            userToInvite: chatOptions.userToInvite,
        });
    }, [setNewChatOptions, chatOptions]);
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by zukilover** [comment] 2023-09-20 11:27
@0xmiroslav Hi, I should rephrase it better. By sometimes I mean when we turn off the network.

**Comment by zukilover** [comment] 2023-09-20 13:41
The infinite loop flag is raised by this operation:

`[info] [Onyx] merge() called for key: iou properties: id,amount,currency,comment,participants,participantAccountIDs,merchant,category,created,receiptPath,receiptSource,transactionID,billable - ""`

[infinite.webm](https://github.com/Expensify/App/assets/371291/abb3eb48-ae8e-451c-bc29-70c526e899a7)

**Comment by MitchExpensify** [comment] 2023-09-21 18:06
Do you agree that is the root cause of the infinite loop @0xmiroslav ?

**Comment by zukilover** [comment] 2023-09-21 23:44
@0xmiroslav if we take a look at how split bill works:

- it takes the user to /request/new/participants/
- then it takes to /split/new/confirmation/

in this case, :iouType is changed from `request` to `split`. With the existing `useEffect` execution, it's trying to evaluate `includeOwnedWorkspaceChats` for `chatOptions` by comparing `iouType === CONST.IOU.MONEY_REQUEST_TYPE.REQUEST`. This is the root cause because the evaluation should be done outside of the effect itself.

As for the `iou properties` infinite operation, that I can say is the result of that problem.

**Comment by MitchExpensify** [comment] 2023-09-26 06:13
Does @zukilover 's response answer your question here @0xmiroslav ? Lets keep the momentum up here

**Comment by mvtglobally** [comment] 2023-09-28 03:24
Issue not reproducible during KI retests. (First week)

**Comment by MitchExpensify** [comment] 2023-09-30 00:46
closing as not reproducible

**Comment by MitchExpensify** [comment] 2023-09-30 05:33
Will take another look at this soon

**Comment by MitchExpensify** [comment] 2023-10-03 16:26
Circling back here, mind expanding on what the "split flow" issue you mention [here](https://github.com/Expensify/App/issues/26885#issuecomment-1741622524) is @0xmiroslav ?

**Comment by MitchExpensify** [comment] 2023-10-03 23:05
Got it, thank you! What edit to the Repro steps, expected result, and actual result do you suggest @0xmiroslav ?

**Comment by mvtglobally** [comment] 2023-10-05 03:02
Issue not reproducible during KI retests. (Second week)

**Comment by MitchExpensify** [comment] 2023-10-09 22:55
What are your recommended next steps for this issue @0xmiroslav ?

**Comment by mvtglobally** [comment] 2023-10-12 03:42
Issue not reproducible during KI retests. (Third week)

**Comment by MitchExpensify** [comment] 2023-10-14 18:14
How did your retest go @0xmiroslav ?

**Comment by MitchExpensify** [comment] 2023-11-09 20:48
Not going to double as this is already higher than our baseline - Still waiting on proposals, Melvin!

**Comment by zukilover** [comment] 2023-11-21 14:00
I can no longer reproduce the issue. @0xmiroslav

**Comment by zukilover** [comment] 2023-11-21 14:08
Yes. This is what I've got:


https://github.com/Expensify/App/assets/371291/58016bf0-1fa5-45c3-a8fd-dd807b67e6e4

**Comment by rezkiy37** [comment] 2023-11-28 16:28
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2023-11-29 15:03
Guys, I have a question. So, I've tested and can confirm that this behaviour with the error message - "Unexpected error creating this chat, please try again later. There is a previously existing chat between these users". However, I don't think that it is a bug. It looks like a normal reaction of the app. Moreover, after refresh, those chats are aligned. 

https://github.com/Expensify/App/assets/57314631/c1ee0cd6-de93-4575-8a64-488e746cf215

**Comment by rezkiy37** [comment] 2023-11-29 15:07
I see. It also makes sense from this perspective. However, I would like to align an expected behavior with someone from the Expensify team.

cc @MitchExpensify

**Comment by rezkiy37** [comment] 2023-11-29 15:14
Hm, a good point. I will try to test as many cases as I can and will post a summury.

**Comment by rezkiy37** [comment] 2023-11-30 16:12
I've tested today with other scenarios: 

#### Different amount and same users

https://github.com/Expensify/App/assets/57314631/92e475f2-6021-41dc-8455-e93b902233e3

#### Different users and same amount

https://github.com/Expensify/App/assets/57314631/87da105f-5fa8-4967-bd3f-59e0f1a64708

For both I didn't get any errors. However, the backend created "Hidden" users. Does someone know why some users appear as "Hidden"?

**Comment by rezkiy37** [comment] 2023-11-30 16:35
> > For both I didn't get any errors.
> 
> You tested with completely new accounts every time, right?

Yep, I split bills only with new accounts.

**Comment by rezkiy37** [comment] 2023-12-04 10:15
Melvin, I am gonna work on this issue today.

**Comment by hayata-suenaga** [comment] 2023-12-04 21:54
@0xmiroslav did you get any error code (a string like this one? `8230FE6F-E7AE-4FF3-90B8-B2F64EA46D0C`)?

**Comment by rezkiy37** [comment] 2023-12-05 09:58
@hayata-suenaga, fyi: https://github.com/Expensify/App/issues/26885#issuecomment-1838891260.

**Comment by hayata-suenaga** [comment] 2023-12-07 16:50
yep I'm working on it

**Comment by hayata-suenaga** [comment] 2023-12-11 19:38
will work later this week.

**Comment by hayata-suenaga** [comment] 2023-12-12 23:18
### Memo for myself

[Auth code where the error is thrown](https://github.com/Expensify/Auth/blob/1fe49606377038b1ce7d32e00f0d1b1c3a819d83/auth/lib/Transaction.cpp#L1735-L1740)

[Condition](https://github.com/Expensify/Auth/blob/1fe49606377038b1ce7d32e00f0d1b1c3a819d83/auth/lib/Transaction.cpp#L1738C36-L1738C67): `chatReportID != newChatReportID`

In `Transaction::createMoneyRequest`, if the participants of a report is the same, the `createChatReport` method of `Report` will return the existing report for these participants.

When a report is created as a result of a split money request, the...

**Comment by hayata-suenaga** [comment] 2023-12-12 23:36
@0xmiroslav could you check if the issue happens when a IOU chat report already exists between the two parties?

**Comment by rezkiy37** [comment] 2023-12-13 13:04
@hayata-suenaga, do you mean this case?

https://github.com/Expensify/App/assets/57314631/a42a4d3d-f2e4-42cb-9370-8843dfc4e1e6

**Comment by rezkiy37** [comment] 2023-12-15 14:29
No update.

**Comment by hayata-suenaga** [comment] 2023-12-15 17:57
sorry I'm checking this today

**Comment by rezkiy37** [comment] 2023-12-18 10:01
Melvin, no "overdue". Waiting on some update from @hayata-suenaga.

**Comment by rezkiy37** [comment] 2023-12-20 09:49
No update.

**Comment by hayata-suenaga** [comment] 2023-12-20 21:08
checking with the internal team if the but is worth fixing

**Comment by MitchExpensify** [comment] 2023-12-21 13:50
This scenario is too much of an edge case for us to prioritize right now so we have decided it is best to close it for now

**Closed by MitchExpensify** 2023-12-21 13:50 UTC
Labels: Engineering, Daily, Internal, Bug
