### ISSUE TITLE
[$500] Android - Workspace-Tapping on triangle button user directed to "Get assistance" page for an second

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32845] opened 2023-12-11 17:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Workspaces --- Workspace --- Settings
4. Tap question mark on top
5. Tap explore help document
6. Tap Triangle icon at bottom right

## Expected Result:
User must be directed to concierge page on tapping triangle button.

## Actual Result:
User directed to "Get assistance" page for an second and then only directed to concierge page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5d740796-db37-47d0-bb6f-e67e87823645

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c891886ac837a3ba</li>
        <li>Upwork Job ID: 1734270044995203072</li>
        <li>Last Price Increase: 2023-12-18</li>
    </ul>
</details>

**Comment by burczu** [comment] 2023-12-14 07:37
Not overdue - I'll review the proposal soon.

**Comment by burczu** [comment] 2023-12-19 11:31
@miljakljajic Sorry for the late answer - I've just tried to test the proposal from @ZhenjaHorbach but I could not reproduce the issue. It seems like the triangle on the `help.expensify.com` does not appear anymore. Could you confirm? Or maybe I'm doing it wrong? :)

https://github.com/Expensify/App/assets/7771498/a86472b3-2fdb-4245-b3a7-38b54d163362

**Comment by burczu** [comment] 2023-12-22 07:18
@miljakljajic jentle bump ;)

**Comment by burczu** [comment] 2023-12-22 13:38
Hey @miljakljajic! I'll be OOO till January 6th, and right after that I'm leaving the C+ role and joining Waves. Could you assign another C+ engineer to handle this issue from now on? Thanks.

**Comment by miljakljajic** [comment] 2023-12-22 13:41
Sorry to miss this! I will try to reproduce and re-assign. Have a lovely break!

**Comment by miljakljajic** [comment] 2023-12-22 13:45
I think we can actually close this out, it doesn't fit high on our company priorities and seems like we've updated the flow anyway.

**Closed by miljakljajic** 2023-12-22 13:45 UTC
Labels: External, Daily, Help Wanted, Bug
