### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Customers and Projects have option as `Sage Intacct Employee Default` 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45823] opened 2024-07-20 13:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @sakluger 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721402815163979

## Action Performed:

Pre-testing requirement: Make sure that your test account is on the intacctOnNewExpensify beta

1. Open any workspace settings
2. Enable accounting
3. Connect to Intacct
4. Click on Import 

## Expected Result:
Customers and Projects dimensions should have `Tag` and `Report field` options only; `Employee Default` should not be an option

## Actual Result:
`Sage Intacct Employee Default` shows as an option for Customers and Projects  dimensions 

NOTE: For me it projects is showing as `Tags`
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (6)](https://github.com/user-attachments/assets/6a602979-c3d8-40f7-9d47-9ae05b419df7)
![Snip - (3) New Expensify - Google Chrome](https://github.com/user-attachments/assets/aff047ff-dc39-4c83-9a1b-1070da77e1e5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fea203f70b955c11</li>
        <li>Upwork Job ID: 1815806282266209115</li>
        <li>Last Price Increase: 2024-07-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by stephanieelliott** [comment] 2024-07-23 17:48
Updated the issue body to be a bit more clear -- the Customer and Project dimensions should show the `Report Field` and `Tag` options ONLY;  `Employee Default` should not show as an option for these dimensions and needs to be removed.

**Comment by jayeshmangwani** [comment] 2024-07-25 04:47
Hey @dominictb 👋 , I have a hard time reaching this page. 

Just a question: how can we reach this page and reproduce the issue?

**Comment by stephanieelliott** [comment] 2024-07-25 20:11
@jayeshmangwani how far are you able to get on the repro steps -- are you able to reach `Connect to Intacct`? If not, you likely need to complete the pre-requisite steps described in https://github.com/Expensify/App/issues/45938#issue-2423611937, more specifically we need to add you to the `intacctOnNewExpensify` beta. If you can share the email address for the test account you're using, I can add you to that beta.

**Comment by jayeshmangwani** [comment] 2024-07-25 20:19
> more specifically we need to add you to the intacctOnNewExpensify beta. If you can share the email address for the test account you're using, I can add you to that beta.

Please add jm98289517+46@gmail.com , I will try to connect with this user

**Comment by SzymczakJ** [comment] 2024-07-29 10:38
I was implementing this and [Sage Intacct design doc ](https://docs.google.com/document/d/1k3ZFw8KB55yPUSCG6KYZlwpwEtmRt3eUshwxs7bZq5I/edit)didn't state anything like this, do we have a main source of truth?

**Comment by SzymczakJ** [comment] 2024-07-29 12:04
Sorry for the confusion, I should have read the whole thread before writing comments 😅. Can this issue be assigned as I already have context and I am author of this implementation?

**Comment by JmillsExpensify** [comment] 2024-07-30 03:55
Assigned @SzymczakJ since he implemented this feature.

**Comment by hungvu193** [comment] 2024-08-01 02:27
I'll review PR today 😄

**Comment by jayeshmangwani** [comment] 2024-08-01 06:29
@stephanieelliott Please assign this issue to @hungvu193 as they reviewed the original PR that worked on this feature and have more context. I am unassigning myself.

**Comment by hungvu193** [comment] 2024-08-02 08:12
@Gonals https://github.com/Expensify/App/pull/46505 will be ready for your final review

**Comment by hungvu193** [comment] 2024-08-15 03:38
@stephanieelliott  No payment is needed for me. Feel free to close

**Closed** 2024-08-16 00:58 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
