### ISSUE TITLE
[$1000] IOS - After selecting emoji app freezes 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#19578] opened 2023-05-25 02:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app 
2. Navigate to any chat 
3. Click on Emoji in composer 
4. select any emoji 
5. try to navigate anywhere 

## Expected Result:
User should be able to select emoji and navigate to other tasks 

## Actual Result:
app is freezing after selecting emoji 

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [X] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17-5
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/4de92ce7-e5e6-47d3-8f1d-f62ab9f5a9bb

https://github.com/Expensify/App/assets/43995119/5bdb703a-c6e4-46a4-b9db-2fb1b49ef6b1

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010beb4382d002b4de</li>
        <li>Upwork Job ID: 1661931648909586432</li>
        <li>Last Price Increase: 2023-05-26</li>
    </ul>
</details>

**Comment by maddylewis** [comment] 2023-05-26 03:05
i was able to repro this in browserstack.

**Comment by esh-g** [comment] 2023-05-26 12:48
Okay, I am investigating this..

**Comment by esh-g** [comment] 2023-05-26 14:58
Very strange... I tried to check why it was okay when dismissed without adding emoji and not when adding the emoji, and I traced it to some state updating in the `updateComment` in `ReportActionComposer` but after that I can't seem to see exactly why this disparity occurs...  I guess maybe it is because of the poor animation performance of this library after all 😕
I would like to apologise for not testing this thoroughly..

cc @aimane-chnaif

**Comment by mountiny** [comment] 2023-05-26 16:12
@techievivek I will take this over if that works for you as its a regression from PR I have been CME on

**Comment by esh-g** [comment] 2023-05-26 16:13
Should I make a new PR to fix this now?

**Comment by esh-g** [comment] 2023-05-26 16:15
> @esh-g yes, you haven't found solution yet with native animation right?

Currently I haven't... So I guess we'll just have to revert the changes

**Comment by esh-g** [comment] 2023-05-26 16:57
https://github.com/Expensify/App/pull/19680 PR is here
@aimane-chnaif @mountiny

**Comment by mountiny** [comment] 2023-05-29 09:48
@esh-g This is unfortunate, what are we going to do about the payments here. The previous features had to be fully reverted so we are back at the beginning here. 

What are the next steps, have you been able to identify the root cause?

**Comment by mountiny** [comment] 2023-05-29 09:51
Going to close this issue in favour of the original one here https://github.com/Expensify/App/issues/17982

**Closed by mountiny** 2023-05-29 09:51 UTC
Labels: External, Daily, Bug

**Comment by esh-g** [comment] 2023-05-29 09:55
@mountiny It seems related to the performance of the library itself because I wasn't able to find anything wrong with other components... I would like to apologise for this and I think there would be no need of payment as nothing was implemented... But, I surely will try this feature again using re-animated and the next time will be sure to put in a lot of testing. Forgive me for the inconvenience

**Comment by mountiny** [comment] 2023-05-29 10:09
No worries @esh-g this happens and we appreciate your help and passion for the project ❤️
