### ISSUE TITLE
[HOLD for payment 2024-09-19] [$250] Tags - App closes RHP after upgrade and clicking back button in GL code page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48207] opened 2024-08-28 19:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a Collect workspace.
3. Go to Categories.
4. Click on any category > GL code/Payroll code.
5. Click Upgrade > Click Got it, thanks.
6. On the code editor page, click on the app back button.
7. Note that app returns to category details RHP.
8. Create a Collect workspace.
9. Go to Tags.
10. Add a tag > Click on tag > GL code.
11. Click Upgrade > Click Got it, thanks.
12. On the code editor page, click on the app back button.

## Expected Result:
App will return to tag details RHP after upgrade and clicking back button in GL code page.

## Actual Result:
App closes RHP after upgrade and clicking back button in GL code page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/56a2a78c-4564-4cd5-961a-d4cc2b8cccc6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3d86efe655bb313</li>
        <li>Upwork Job ID: 1829329439413113957</li>
        <li>Last Price Increase: 2024-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103806540</li>
<li>Krishna2323 | Contributor | 103806542</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by IuliiaHerets** [comment] 2024-08-28 19:34
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment] 2024-08-28 19:34
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-08-28 19:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- App closes RHP after upgrade and clicking back button in GL code page

### What is the root cause of that problem?
We are not giving goBack callback here
https://github.com/FitseTLT/App/blob/ac5ee2ef790231c67ca3ddb14dc481d77da5bcea/src/pages/workspace/tags/TagGLCodePage.tsx#L58
### What changes do you think we should make in order to solve the problem?

We should give the goBack as
```
            onBackButtonPress={() => Navigation.goBack(ROUTES.WORKSPACE_TAGS_SETTINGS.getRoute(route.params.policyID))}

```
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-09-02 23:34
CC: @garrettmknight @allroundexperts upgrades related!

**Comment by stephanieelliott** [comment] 2024-09-04 02:25
Hey @MonilBhavsar can you confirm the proposal selected [here](https://github.com/Expensify/App/issues/48207#issuecomment-2322867708)?

**Comment by MonilBhavsar** [comment] 2024-09-04 02:52
Looks good!

**Comment by stephanieelliott** [comment] 2024-09-11 02:38
PR was merged to main 🎉

**Comment by stephanieelliott** [comment] 2024-09-24 21:37
Oop yea looks like automation didn't work, this was ready to pay out on 9/16. Setting up for payment now.

**Comment by stephanieelliott** [comment] 2024-09-24 21:39
Summarizing payment on this issue: 

 - Contributor: @Krishna2323 $250 via Upwork -- PAID 
 - Contributor+: @ZhenjaHorbach $250 $250 via Upwork -- PAID 
 
 Upwork job is here: https://www.upwork.com/jobs/~01b3d86efe655bb313

**Comment by stephanieelliott** [comment] 2024-09-24 21:42
Regression test issue here: https://github.com/Expensify/Expensify/issues/430822

**Closed by stephanieelliott** 2024-09-24 21:42 UTC
Labels: Reviewing, External, Weekly, Bug
