### ISSUE TITLE
[$500] Details - Cursor is not pointer when hovered over the Avatar in workspace invite message page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29456] opened 2023-10-12 15:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697038101560199

## Action Performed:
1. Create a group with some users and go to group details.
2. Observe hovering on avatar has pointer cursor.
3. Create a workspace if haven't already,
4. Navigate to Invite Members in workspace
5. Invite some some members Click Next
6. Hover over the avatar for users

## Expected Result:
Cursor should be pointer when hovered over the Avatar

## Actual Result:
Cursor is not Pointer

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/2b73750c-9d54-41c8-972d-27d8bc0e540c

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/0923aecd-5ca3-4200-97b8-cf0ae71aca97

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf3ed02adac008de</li>
        <li>Upwork Job ID: 1712483295213932544</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 27231740</li>
<li>dukenv0307 | Contributor | 27231741</li>
<li>ishpaul777 | Reporter | 27231743</li>
</ul></li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-10-12 15:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent cursor when hovering over the users avatars in the invite message page


### What is the root cause of that problem?
The `MultipleAvatars` component is usually used withing a Pressable, which automatically applies a `cursor:pointer`. but in this case, we are wrapping the `MultipleAvatars` with a `View` component that does not give it the wanted `cursor:pointer` styling 

### What changes do you think we should make in order to solve the problem?
We can add `styles.cursorPointer` to wrapper View 

https://github.com/Expensify/App/blob/9e6af2b50faf574452ffa27dad10bc72e6c03e21/src/pages/workspace/WorkspaceInviteMessagePage.js#L200

### What alternative solutions did you explore? (Optional)

N/A

**Comment by akinwale** [comment] 2023-10-13 04:54
After reviewing the proposals, the solution in @dukenv0307's [proposal](https://github.com/Expensify/App/issues/29456#issuecomment-1759880360) is the most complete as it would properly fix the issue and add functionality that would maintain consistency with other parts of the app, if the issue is considered worth fixing.

🎀 👀 🎀 C+ reviewed.

**Comment by chiragsalian** [comment] 2023-10-17 02:55
Proposal LGTM, feel free to create a PR @dukenv0307.

**Comment by akinwale** [comment] 2023-10-17 12:09
@dukenv0307 I believe the main goal is to maintain consistency across the app, so if there are other parts of the app where avatars are clickable as identified in case 2 (oblique avatars), then you should apply that change in your PR too. Otherwise, let's just stick with case 1.

@garrettmknight can also share some thoughts on this.

**Comment by akinwale** [comment] 2023-10-18 06:56
@chiragsalian @garrettmknight bump for feedback to this [comment](https://github.com/Expensify/App/issues/29456#issuecomment-1765993891). Thanks.

**Comment by chiragsalian** [comment] 2023-10-19 00:35
hmm oops i'm sorry i think i might have steered this in a wrong direction. I originally thought that those avatars were clickable and hence we wanted to show pointer icon. I see now that they weren't clickable to begin with so not showing pointer is correct. Cause if we show pointer icon and the user attempts to click it and nothing happens showing the pointer is bad user feedback.

**My new thoughts**:
1. I do not think we should make avatar clickable throughout the app to show user details, at least not yet and that would be a much larger discussion if we did want to implement that.
2. I think if we only wanted avatars in workspace to be clickable to show user details that's fine with me, but even that is a new feature. I don't think this new feature is really needed right now.

So i think next steps is do nothing and close this out. 
@garrettmknight let me know if you disagree. I think the behavior is working as expected i.e., pointer only for clickable items and the avatar here is not clickable.

**Comment by akinwale** [comment] 2023-10-19 05:41
> So i think next steps is do nothing and close this out. @garrettmknight let me know if you disagree. I think the behavior is working as expected i.e., pointer only for clickable items and the avatar here is not clickable.

@chiragsalian I think we can we put this on hold while we have a broader discussion about the expected behaviour. I can also start a discussion on Slack for this. What do you reckon?

**Comment by chiragsalian** [comment] 2023-10-19 19:50
yes looks like garrett hasn't had a chance to check this out yet. Sure yes can you begin a discussion on slack.

**Comment by akinwale** [comment] 2023-10-23 11:22
Started a Slack conversation: https://expensify.slack.com/archives/C01GTK53T8Q/p1698059982808569

**Comment by garrettmknight** [comment] 2023-10-23 19:21
Commented as much in the thread (thanks for starting it @akinwale), but I agree with @chiragsalian that the behavior that exists is expected. Closing this one, sorry it took a little while!

**Closed by garrettmknight** 2023-10-23 19:21 UTC
Labels: External, Daily, Bug

**Comment by chiragsalian** [comment] 2023-10-31 23:42
I'll let garrett handle the payment and decision. Personally, i think no because we normally pay for merged code. A person can spend days on a PR but if it's not merged we don't normally pay them despite the amount of effort put into it. With that said there are exceptions so I'll let garrett decide this.

**Comment by garrettmknight** [comment] 2023-11-01 14:20
Hey @dukenv0307 - there are issues where we don't merge the code and pay for the work done when it's significant. In this case, we didn't have an approved PR or even a PR up and submitted so I don't think it meets the bar for full or partial payment.
