### ISSUE TITLE
[HOLD for payment 2024-10-29] [$250] [Dupe Detection] Unable to resolve duplicates on one-expense reporrts

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49793] opened 2024-09-26 14:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727339112704349

## Action Performed:
1. Create a new workspace, upgrade to Control
2. Make sure you’re on the duplicate detection beta
3. Enabled delayed submission with a weekly frequency. Enable approvals (with you as the approver)
4. Have user a submit a report, with the merchant McDonalds for $50. Approve the report
5. Have the user create another expense report for the same merchant and amount (McDonalds and $50)
6. Have the user submit the report
## Expected Result:
 The approver is able to resolve a duplicate
## Actual Result:
The approver is unable to resolve the duplicate, as no resolve duplicate button appears
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![CleanShot 2024-09-26 at 10 21 23@2x](https://github.com/user-attachments/assets/d0111050-c76e-45a1-b8c9-e20167626ea8)

![Snip - (4) New Expensify - Google Chrome](https://github.com/user-attachments/assets/4d7d06d1-5397-4791-9e54-02fd315671a3)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839321413603387914</li>
        <li>Upwork Job ID: 1839321413603387914</li>
        <li>Last Price Increase: 2024-09-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by dannymcclain** [comment] 2024-09-26 15:06
One way we could handle this is by adding a `Resolve duplicates` button to the header, like so:
![image](https://github.com/user-attachments/assets/0524c1b2-515c-4ccf-9968-91474288b4a2)

cc @JmillsExpensify @Expensify/design

**Comment by JmillsExpensify** [comment] 2024-09-26 15:13
Nice, I like that idea!

**Comment by dubielzyk-expensify** [comment] 2024-09-26 23:17
Same. Looks good to me

**Comment by pecanoro** [comment] 2024-09-27 13:29
@shubham1206agra The duplicates might be in a different report

**Comment by sobitneupane** [comment] 2024-09-30 09:07
Thanks for the proposal @daledah 

> We should remove canUseDupeDetection check in

I am not sure how is the change related to this issue. Dupe Detection is behind beta and the function is serving the purpose.

Can you please add more details to the 2nd point in your proposal.

**Comment by dylanexpensify** [comment] 2024-09-30 20:30
@sobitneupane thoughts now?

**Comment by sobitneupane** [comment] 2024-10-01 09:54
Thanks for the proposal @daledah 

We would prefer not to display the 'Resolve Duplicate' button in the Expense Report that contains several "batched" expenses, as shown in the Result section of your proposal.

<img width="440" alt="Screenshot 2024-10-01 at 15 22 46" src="https://github.com/user-attachments/assets/e63bf227-8600-42e5-859a-77e689a5061e">

Currently, we already display the 'Resolve Duplicate' button within a transaction for Expense Report that contains several "batched" expenses. However, when there is only one expense, the button is not shown. The only page where we would like to add the 'Resolve Duplicate' button is:

<img width="1440" alt="Screenshot 2024-10-01 at 15 20 40" src="https://github.com/user-attachments/assets/07fcfa06-cd51-4108-a271-f263a1dd7f20">

Expected UI: https://github.com/Expensify/App/issues/49793#issuecomment-2377242596

**Comment by sobitneupane** [comment] 2024-10-01 10:01
@dannymcclain  Should we use the text "Review duplicates" instead of "Resolve duplicate", since that is the term currently being used? https://github.com/Expensify/App/issues/49793#issuecomment-2377242596

<img width="1074" alt="Screenshot 2024-10-01 at 15 42 00" src="https://github.com/user-attachments/assets/3e6b7a59-6477-40cc-961e-a3e18804498b">

**Comment by dannymcclain** [comment] 2024-10-01 13:29
>Should we use the text "Review duplicates" instead of "Resolve duplicate", since that is the term currently being used?

This is a good question for @JmillsExpensify — I'm tempted to say let's use the language we already have, but I'm not 100% sure.

**Comment by pecanoro** [comment] 2024-10-01 15:13
Yeah, let's keep the language that we already have, no need to change it for now.

**Comment by dylanexpensify** [comment] 2024-10-01 21:59
@daledah when can we expect updated proposal?

**Comment by sobitneupane** [comment] 2024-10-02 10:17
Thanks for the update, @daledah.

[The proposal](https://github.com/Expensify/App/issues/49793#issuecomment-2377146847) from @daledah looks good to me. However, we still need some styling changes to achieve [the requested UI](https://github.com/Expensify/App/issues/49793#issuecomment-2377242596).

🎀 👀 🎀 C+ reviewed

**Comment by pecanoro** [comment] 2024-10-02 15:19
Assigning @daledah to the issue!

**Comment by JmillsExpensify** [comment] 2024-10-04 07:47
Awesome, thanks for the quick work on this one!

**Comment by dylanexpensify** [comment] 2024-10-15 12:45
Reassigning as I head to parental leave next week! Thanks Matt!

**Comment by mallenexpensify** [comment] 2024-11-05 22:33
@daledah , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021853927916382654201

@sobitneupane , plz fill out the BZ checklist above, I imagine we want a test case for this

**Comment by sobitneupane** [comment] 2024-11-06 14:06
**Regression Test Proposal**

1. Create an expense report and submit it in a control workspace.
2. Create another report with the same amount and merchant as step 1.
3. Open the expense report submitted in step 2
4. Verify that: "Review duplicates" button appears.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2024-11-06 14:16
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/40153

> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/40153#issuecomment-2459870163

> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

https://github.com/Expensify/App/issues/49793#issuecomment-2459847200

**Comment by mallenexpensify** [comment] 2024-11-07 00:29
Contributor: @daledah paid $250 via Upwork
Contributor+: @sobitneupane owed $250 via NewDot

Test case created
- https://github.com/Expensify/Expensify/issues/442377 

Thanks!

**Closed by mallenexpensify** 2024-11-07 00:29 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-12 10:51
$250 approved for @sobitneupane
