### ISSUE TITLE
[$1000] Dev: Web - Open any workspace chat redirect to Concierge chat and delete workspace chat from LHN.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23126] opened 2023-07-18 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account on a DEV (confirm you use all beta by return true in canUseAllBetas).
2. Go to Settings > workspaces and create a new workspace.
3. From LHN open the new workspace chat (with square logo).

## Expected Result:
App should open workspace chat.

## Actual Result:
App open workspace chat for a second then redirect to Concierge chat and delete workspace chat from LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev: 1.3.41-3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/658ea1ca-afb6-4d3b-901d-f1d6532f7199

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmedGaber93
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689681903439209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01499fba47fa05425a</li>
        <li>Upwork Job ID: 1682138530723598336</li>
        <li>Last Price Increase: 2023-07-20</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-18 20:31
This seems to be a BE issue.
When open workspace chat, BE responds 403 error with empty chat data, so the workspace chat will be redirected to Concierge and removed from LHN.
![Screenshot 2023-07-18 162948](https://github.com/Expensify/App/assets/131836113/3240aed0-a516-4108-b5c3-ba401f4c189a)

**Comment by alexpensify** [comment] 2023-07-20 21:21
I've assigned the `External` label here.

**Comment by Mkneeshaw** [comment] 2023-07-21 01:50
Do you still need external help on this?

**Comment by alexpensify** [comment] 2023-07-22 15:42
@Mkneeshaw - Yes, share a proposal and it will be reviewed. Thanks!

**Comment by alexpensify** [comment] 2023-07-24 21:28
No update, waiting on proposals here

**Comment by rushatgabhane** [comment] 2023-07-25 19:22
waiting on proposal or reproduction steps

**Comment by alexpensify** [comment] 2023-07-26 21:50
@pecanoro - I need help testing on dev here or identifying if this is a backend issue. Thanks!

**Comment by pecanoro** [comment] 2023-07-27 09:54
I tried to reproduce this in a few different ways and I am also not able to replicate the behavior so I am going to close this issue. @ahmedGaber93 I am sorry, but we can't invest more time in this if there is no way for us to check what's wrong. Did you try logging out, clearing onyx data and trying again?

**Closed by pecanoro** 2023-07-27 09:54 UTC
Labels: External, Engineering, Daily, Needs Reproduction, Help Wanted, Bug

**Comment by ahmedGaber93** [comment] 2023-07-27 19:39
> Did you try logging out, clearing onyx data and trying again?

@pecanoro yes, I did.
This issue is completely reproducible in dev, I can't try to reproduce it in production because it is a beta feature.
It also reproduced here https://github.com/Expensify/App/issues/23126#issuecomment-1640953209 by @StevenKKC 
also reported again in slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1690114048571269?thread_ts=1690114048.571269&cid=C049HHMV9SM) 

We can get some help from one of C+ or internal developers?
