### ISSUE TITLE
[HOLD for payment 2023-06-28] [$1000] Web- Tread - Copy to clipboard on parent [deleted message] does not work

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20074] opened 2023-06-02 16:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Open any other platform (eg: notepad) and write anything in it, copy that text
4. Send any message eg: Hello test
5. Click on reply to thread on message
6. Delete the message
7. On [deleted message] click on copy to clipboard
8. Paste the text anywhere to observe that app displays copied text from step 3

## Expected Result:
App should not display the 'copy to clipboard' icon on message if it does nothing on click
@parasharrajat recommended [here](https://expensify.slack.com/archives/C049HHMV9SM/p1686016945288399?thread_ts=1684408470.433469&cid=C049HHMV9SM)
Hide the icon for this case and also other icons which has no effect.
- From mini-content menu.
- From Context menu.

## Actual Result:
App displays copy to clipboard on [deleted message] even though that option does nothing on click

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0f11dba4-f07d-4c27-8996-9068cc5b765f

https://github.com/Expensify/App/assets/93399543/e4182e4f-764a-45eb-8065-2bc959812fee

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684408470433469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dfe7568572f0563a</li>
        <li>Upwork Job ID: 1665912794319777792</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-06-06 01:36
Posted in [the thread ](https://expensify.slack.com/archives/C049HHMV9SM/p1686015330907719?thread_ts=1684408470.433469&cid=C049HHMV9SM)and shared with room. 

Gut check... when a message with a thread has been deleted it shows [Deleted message] . When you hover over Copy to clipboard, the icon is clickable but, since the message is deleted, nothing happens.
1, Is this expected behaviour? If so we can :donothing:
2. Since nothing happens when you click Copy to clipboard, so that icon be unclickable for deleted messages?

**Comment by mallenexpensify** [comment] 2023-06-06 02:46
@aimane-chnaif , please review @dhairyasenjaliya 's proposal above
https://github.com/Expensify/App/issues/20074#issuecomment-1574271738

**Comment by techievivek** [comment] 2023-06-08 12:31
Yeah, agree to hide them. Thanks

**Comment by mallenexpensify** [comment] 2023-06-09 19:03
@aimane-chnaif @dhairyasenjaliya @dhanashree-sawant hired, please accept. 
https://www.upwork.com/jobs/~01dfe7568572f0563a

**Comment by joekaufmanexpensify** [comment] 2023-06-12 19:12
Coming from the above linked issue @0xmiroslav and I were thinking it could make sense to include the issue we worked on as part of the eventual regression test steps here. 

Our issue was specifically removing the download button from the clipboard menu after deleting the parent image/attachment of a thread (given there is no longer anything to download). And we were thinking the eventual regression test steps in this issue could be: 

1. Send any message (or any attachment) in any chat room
2. Thread that message
3. Send any message on that thread
4. Delete parent message
5. Hover [Deleted message]
6. Verify that context menu shows only "Mark as unread" icon, no other icons show

This would cover the cases across both issues. Thoughts on that?

**Comment by joekaufmanexpensify** [comment] 2023-06-20 20:53
I was assigned this [bug report](https://github.com/Expensify/App/issues/21103), that relates to this issue. I see the PR here is on staging. When I test this on staging, the comment action menu doesn't change for deleted messages until you leave the chat and go back to it. 

This means you can "delete" a message twice, which is causing some odd behavior. Is this expected after the PR in this issue? 

https://github.com/Expensify/App/assets/54866469/9f3bc969-73f7-4ff8-959b-96dd41ca8685

**Comment by techievivek** [comment] 2023-06-22 16:16
@aimane-chnaif 
> yes, it's known issue and out of scope for that PR.

Is this reproducible on PROD as well?

**Comment by joekaufmanexpensify** [comment] 2023-06-22 16:24
Yeah it is for me.

**Comment by Pujan92** [comment] 2023-06-26 21:29
I think https://github.com/Expensify/App/issues/21632 regression from here(where the icons should hide immediately on delete), which I tried to explain [here](https://github.com/Expensify/App/issues/21632#issuecomment-1608279699)

**Comment by techievivek** [comment] 2023-06-30 05:33
Agree. I and Joe talked about it and decided to treat it as separate issues.

**Comment by techievivek** [comment] 2023-06-30 05:36
Hi, @mallenexpensify have we finished paying contributors for this issue? Or is that pending?

**Comment by techievivek** [comment] 2023-07-03 08:23
Not overdue, waiting for the payments to be done.

**Comment by techievivek** [comment] 2023-07-04 07:10
Not overdue, gentle bump @mallenexpensify

**Comment by techievivek** [comment] 2023-07-10 13:16
Gentle bump @mallenexpensify to finish the payment here.

**Comment by mallenexpensify** [comment] 2023-07-12 01:50
Sorry for the delay, I was out a couple days and missed the bumps. 
Everyone is paid, inc the 50% urgency bonus. since the PR was help up on Vivek being OOO and, more importantly, because changes weren't needed.  

@aimane-chnaif can you please complete the checklist?
https://github.com/Expensify/App/issues/20074#issuecomment-1599951029

**Comment by mallenexpensify** [comment] 2023-07-14 19:34
Thanks @aimane-chnaif, created the TestRail GH https://github.com/Expensify/Expensify/issues/300023

**Comment by mallenexpensify** [comment] 2023-07-14 19:35
@aimane-chnaif does any of this need to be completed? 
<img width="784" alt="image" src="https://github.com/Expensify/App/assets/22508304/835652f3-2462-4009-a90d-9327b36e8288">

**Closed** 2023-07-15 00:06 UTC
Labels: External, Daily, Awaiting Payment, Bug
