### ISSUE TITLE
Split - Participant list does not scroll to the top after selecting split participants

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36893] opened 2024-02-20 14:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to FAB > Request money > Manual.
3. Enter amount > Next.
4. Scroll down the list.
5. Click Split.

## Expected Result:
The list will scroll up to the top each time a member is selected as split participant.

## Actual Result:
The list does not scroll up to the top each time a member is selected as split participant.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b007000b-66b9-43ad-8c05-170485bdb1e0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-02-20 14:49
@alexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment] 2024-02-20 14:51
We think that this bug might be related to #vip-split-p2p-chat-groups
CC @arielgreen

**Comment by aneequeahmad** [comment] 2024-02-20 18:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Participant list doesn't scroll up to the top each time a member is selected as split participant.

### What is the root cause of that problem?
This bug occured due to commit `#ec73a6ca5d` where this code was removed from `useEffect` which has the logic to scroll to top when section list changes. 

     if (sections.length > 0) {
            updateAndScrollToFocusedIndex(0);
     }

### What changes do you think we should make in order to solve the problem?

We can add the logic back in useEffect to scroll to top when a new item is added in section.

Also the code to avoid changing focus if the textInputValue remains unchanged is added in useEffect which if needed can be added after the code i proposed so that when the item is selected it shouldn't return before doing anything

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.
N/A

**Comment by alexpensify** [comment] 2024-02-21 01:37
I'm still catching up from being OOO and will test later this week.

**Comment by alexpensify** [comment] 2024-02-23 00:04
Still on my testing list

**Comment by alexpensify** [comment] 2024-02-27 00:58
I didn't get a chance to test over the weekend, but it's on my list for tomorrow.

**Comment by alexpensify** [comment] 2024-03-01 02:00
I ran out of time today and will have to test it next week. 

## Heads up, I will be offline until Tuesday, March 5, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the Open Source Slack Room-- thanks!

**Comment by alexpensify** [comment] 2024-03-05 19:05
I'm catching up from being OOO and will test soon.

**Comment by alexpensify** [comment] 2024-03-06 18:10
I confirmed this experience but will need to check with Design for feedback: 

![2024-03-06_10-08-59](https://github.com/Expensify/App/assets/8107070/d4ed2d03-b83e-40c2-9ac1-40e4a21dd7a3)

**Comment by alexpensify** [comment] 2024-03-06 18:12
@Expensify/design - I need some feedback here. Should the list scroll to the top when you make a selection? I don't think it should and would make a weird jumping experience. You'd need to continue to scroll back down if you need to select more. I think we leave the list as is and the person should scroll up to confirm their selections. Thanks for the feedback!

**Comment by shawnborton** [comment] 2024-03-06 18:30
Hmm I'm not too sure. I can totally see both sides of this... it's nice to scroll to the top to see the existing selections, but at the same time, scrolling might lose your position in a long list.

**Comment by dannymcclain** [comment] 2024-03-06 19:13
I'm in favor of not automatically scrolling the list. I kinda think it would be more annoying than helpful. After each selection, you'll have to wait for the UI to automatically scroll to the top and then re-scroll back down to make further selections. Feels like over-solving to me.

**Comment by shawnborton** [comment] 2024-03-06 19:43
Cool, I can get down with that! So maybe this is not a bug then and we can close. But of course, we can always wait until the third judge of the supreme design court weighs in.

**Comment by dubielzyk-expensify** [comment] 2024-03-06 23:43
Agreed 100%. Don't think we should scroll up

**Comment by dannymcclain** [comment] 2024-03-07 14:20
Alright! Let's go ahead and close this.

**Comment by shawnborton** [comment] 2024-03-07 14:38
Done!

**Closed by shawnborton** 2024-03-07 14:38 UTC
Labels: Daily, Bug

**Comment by alexpensify** [comment] 2024-03-07 15:40
Thanks Design!
