### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000] The Keyboard shortcuts modal does not render correctly when the window is resized.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21643] opened 2023-06-26 20:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Opened the Website.
2. Navigated to the Settings page, then to the About page.
3. Clicked on "View keyboard shortcuts".
4. Decreased the window size.
5. Maximized the browser window.
6. Observed that the Keyboard shortcuts modal is not in the center of the page.
## Expected Result:
 The Keyboard shortcuts modal should be in the center of the page.
## Actual Result: 
The Keyboard shortcuts modal does not render correctly when the window is resized.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e4024b74-7373-48e0-804c-191c727a07a6

https://github.com/Expensify/App/assets/43996225/3022b0b7-6945-4e72-a9b9-3600c532284e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687297558102969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a27dd51f1042e7a5</li>
        <li>Upwork Job ID: 1673922198285770752</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-06-26 22:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Keyboard shortcuts modal does not render correctly when the window is resized.

### What is the root cause of that problem?
`Warning: Updating a style property during rerender (flex) when a conflicting property is set (flexShrink) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values.` 
As the error mentions don't mix the shorthand and no-shorthand properties and seems that we are doing here(where `modalContainerStyle` contains shorthand property `flex: 1` and `innerContainerStyle` has properties of `keyboardShortcutModalContainer` which are non-shorthand). 
https://github.com/Expensify/App/blob/1a2072fd6d1d4da13d110fb4d63da00097022a91/src/styles/getModalStyles/getBaseModalStyles.js#L252
https://github.com/Expensify/App/blob/d76b1addefaf57c4299a74d8f6350e2602ad5a80/src/components/KeyboardShortcutsModal.js#L159
https://github.com/Expensify/App/blob/d76b1addefaf57c4299a74d8f6350e2602ad5a80/src/styles/styles.js#L2998-L3003

### What changes do you think we should make in order to solve the problem?
As for the modal container type we are using the flex shorthand syntax here, let's do the same for the `keyboardShortcutModalContainer` to avoid this conflict issue.

Instead of 
https://github.com/Expensify/App/blob/d76b1addefaf57c4299a74d8f6350e2602ad5a80/src/styles/styles.js#L2998-L3003
Update to
```
flex: '0 0 auto',
```

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/14358475/ef9dae20-30f0-4133-98f1-c13d476be404

</details>

**Comment by tjferriss** [comment] 2023-06-28 05:12
I'm able to reproduce this one.

<img width="1100" alt="Screenshot 2023-06-27 at 22 11 34" src="https://github.com/Expensify/App/assets/8292562/73966978-ad0a-4d41-b67f-f080778dbd31">

**Comment by Pujan92** [comment] 2023-06-28 16:30
> @Pujan92 your change reverts [this change](https://github.com/Expensify/App/commit/9e0932ca20c6475742fae857ffb301a0ec9ed8ab#diff-8ab8ba45ab927f1430b8d1209d187e003a9cdfe476f809e4483ef64cdba253eb) and cause regression on native. 

Yes @0xmiroslav , I updated my proposal with the opposite change.

> Overriding with `flex: 0` should be enough to fix this issue.

I think flex: 0 won't work as it makes flexGrow: 0, flexShrink: 1, flexBasis: 0%', is it working for you?

**Comment by Pujan92** [comment] 2023-06-28 16:36
For me the modal doesn't take any height(seems due to flexGrow and flexBasis both are 0). 

https://github.com/Expensify/App/assets/14358475/2a359c25-6561-43fa-9531-a8288a610b0f

I applied below changes, is that correct?
```
keyboardShortcutModalContainer: {
        maxHeight: '100%',
        flex: 0,
        // flexShrink: 0,
        // flexGrow: 0,
        // flexBasis: 'auto',
    },
```

**Comment by Pujan92** [comment] 2023-06-28 16:42
Oh, Ok. I thought each normal property needs to remove so I take out flexBasis also. I don't know but earlier the console error throws for all these 3 properties. But yes it is working now and not throwing any error with your change.

**Comment by tjferriss** [comment] 2023-07-12 05:56
@GItGudRatio can you please apply to the job post here for payment? https://www.upwork.com/jobs/~01a27dd51f1042e7a5

@0xmiroslav can you get started on the checklist?

**Comment by tjferriss** [comment] 2023-07-12 19:52
@0xmiroslav and @Tushu17 payments have been sent. @GItGudRatio once you accept the offer, I'll process your payment and we can close the issue.

**Closed** 2023-07-12 20:39 UTC
Labels: External, Daily, Awaiting Payment, Bug
