### ISSUE TITLE
[$1000] Web - Workspace - Flickering tooltips and avatar on the General Settings page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18456] opened 2023-05-04 22:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
and login in expensifail account
2. Create workspace and upload custom avatar for workspace
3. Go offline
4. Delete custom avatar and press Save and back to General settings page
5. Move cursor to Back Button and to X (close) button

## Expected Result:
1. The default avatar is dimmed and does not flicker
2. No flickering when hovering over buttons

## Actual Result:
1. Default workspace avatar flickers after removing custom avatar offline
2. When you move the cursor first time over the buttons 'Back' and 'Close', the tooltip flickers from top to bottom (in offline and online mode)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.10.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/236347091-05908a5d-2e30-4606-b3ac-036177eb9a12.mp4

https://user-images.githubusercontent.com/93399543/236347122-a4e8c5e2-e64f-4508-98ec-d7dfcbac6f1c.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd583fbdb2fa5da3</li>
        <li>Upwork Job ID: 1654585926592741376</li>
        <li>Last Price Increase: 2023-05-05</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2023-05-05 20:36
Reproduced and doesn't seem to be a dupe

**Comment by httol** [comment] 2023-05-06 00:58
Can not reproduce this issue

Safari version: 16.2 (18614.3.7.1.5)
Chrome version: 112.0.5615.137

**Comment by httol** [comment] 2023-05-06 01:02
Contributor details
Your Expensify account email: 895652159@qq.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f8ba1e589b86cff7

**Comment by kushu7** [comment] 2023-05-06 05:48
Contributor details
Your Expensify account email: rahulkushwaha931@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b9fbc93d272a627d

**Comment by kushu7** [comment] 2023-05-06 07:37
Not able to reproduce it.
OS: macOS
Chrome version: 113.0.5672.63 (Official Build) (arm64)
Safari version: 16.4 (18615.1.26.110.1)

**Comment by MitchExpensify** [comment] 2023-05-06 22:52
When I reproduced I thought I saw it flicker once so it wasn't a like for like reproduction. Seeing as two others cannot reproduce like for like, I'm going to close this issue

**Closed by MitchExpensify** 2023-05-06 22:52 UTC
Labels: External, Daily, Help Wanted, Bug
