### ISSUE TITLE
[PAID] [$1000]  App crashes when splitting a bill offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14355] opened 2023-01-17 14:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go offline
2. Open the global create menu (big green :heavy_plus_sign:)
3. Select Split Bill
4. Enter an amount
5. Enter the email of exactly one other user who you have never chatted with before
6. Add a memo to the request
7. Split the bill to finalize the request

## Expected Result:
You should be taken to a 1:1 chat with that user
You should a normal message that says Split $X with <email> for <memo>
You should see another IOU action that says: Requested $(X/2) from <email> for <memo>

## Actual Result:
The app crashes and you land on the error boundary

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.55-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image (2)](https://user-images.githubusercontent.com/43996225/212924467-5db69111-c1f0-43e6-96b2-1af91be961e0.png)

https://user-images.githubusercontent.com/43996225/212924507-aa0dda41-1e31-40c5-8f0d-275183219a06.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673903364260589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e5bf073f9b98c1b</li>
        <li>Upwork Job ID: 1615404129941577728</li>
        <li>Last Price Increase: 2023-01-17</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-01-17 17:48
**Proposal**

We can validate first the `IOUReportID` to avoid the error.

```diff
diff --git a/src/libs/IOUUtils.js b/src/libs/IOUUtils.js
index 5c1538682..681ada7c6 100644
--- a/src/libs/IOUUtils.js
+++ b/src/libs/IOUUtils.js
@@ -82,7 +82,7 @@ function getIOUReportActions(reportActions, iouReport, type = '', pendingAction
     return _.chain(reportActions)
         .filter(action => action.originalMessage
             && action.actionName === CONST.REPORT.ACTIONS.TYPE.IOU
-            && action.originalMessage.IOUReportID.toString() === iouReport.reportID.toString())
+            && action.originalMessage.IOUReportID && action.originalMessage.IOUReportID.toString() === iouReport.reportID.toSt
ring())
         .filter(action => (!_.isEmpty(type) ? action.originalMessage.type === type : true))
         .filter(action => (!_.isEmpty(pendingAction) ? action.pendingAction === pendingAction : true))
         .filter(action => (filterRequestsInDifferentCurrency ? action.originalMessage.currency !== iouReport.currency : true))
```

**Comment by tienifr** [comment] 2023-01-17 17:55
# Proposal 

We should check that both `action.originalMessage.IOUReportID` and `iouReport.IOUReportID` are not nil to avoid such crashes
```diff
diff --git a/src/libs/IOUUtils.js b/src/libs/IOUUtils.js
index 5c1538682c..009dea1687 100644
--- a/src/libs/IOUUtils.js
+++ b/src/libs/IOUUtils.js
@@ -81,6 +81,8 @@ function updateIOUOwnerAndTotal(iouReport, actorEmail, amount, currency, type =
 function getIOUReportActions(reportActions, iouReport, type = '', pendingAction = '', filterRequestsInDifferentCurrency = false) {
     return _.chain(reportActions)
         .filter(action => action.originalMessage
+            && !_.isNil(action.originalMessage.IOUReportID)
+            && !_.isNil(iouReport.reportID)
             && action.actionName === CONST.REPORT.ACTIONS.TYPE.IOU
             && action.originalMessage.IOUReportID.toString() === iouReport.reportID.toString())
         .filter(action => (!_.isEmpty(type) ? action.originalMessage.type === type : true))

```

**Comment by Pujan92** [comment] 2023-01-17 19:10
I don't think we need to validate `iouReport. reportID ` too as it will be available due to the fact we are generating it.

https://github.com/Expensify/App/blob/3636f1fb323d86ba8e944b9b1d0e1ae584afabdd/src/libs/ReportUtils.js#L725

**Comment by fedirjh** [comment] 2023-01-17 21:09
### Proposal

#### Root Issue
This is a regression from https://github.com/Expensify/App/commit/966e018a5e1d8cd0d6e2e1b364605b7d9583dea4 , removing this line `&& action.originalMessage.type === type` introduced an error in filtering `reportActions` 

This is an example of IOU report action that causes this issue , this reportAction does not have `IOUReportID` ( it's `undefined` ) hence converting it's value `.toString()`  will cause an error

<img width="832" alt="Screenshot 2023-01-17 at 10 00 18 PM" src="https://user-images.githubusercontent.com/36869046/213011412-cb8d7f63-5673-45e3-97b0-678e3d565129.png">

#### Solution

Rollback old code that validates `action.originalMessage.type` by it's `type`

```diff
diff --git a/src/libs/IOUUtils.js b/src/libs/IOUUtils.js
index 5c1538682c..0e06b5a16e 100644
--- a/src/libs/IOUUtils.js
+++ b/src/libs/IOUUtils.js
@@ -82,6 +82,7 @@ function getIOUReportActions(reportActions, iouReport, type = '', pendingAction
     return _.chain(reportActions)
         .filter(action => action.originalMessage
             && action.actionName === CONST.REPORT.ACTIONS.TYPE.IOU
+            && action.originalMessage.type === type
             && action.originalMessage.IOUReportID.toString() === iouReport.reportID.toString())
         .filter(action => (!_.isEmpty(type) ? action.originalMessage.type === type : true))
         .filter(action => (!_.isEmpty(pendingAction) ? action.pendingAction === pendingAction : true))

```

**Comment by strepanier03** [comment] 2023-01-18 00:59
@sobitneupane - A few proposals coming through, thanks for taking a look. I'll circle back tomorrow to check in for any updates.

**Comment by sobitneupane** [comment] 2023-01-18 04:23
@Ollyws Can you please elaborate how [re-ordering](https://github.com/Expensify/App/issues/14355#issuecomment-1386189985) will solve the issue?

**Comment by sobitneupane** [comment] 2023-01-18 16:29
@Ollyws Thanks for the clarification. 

@Ollyws's [proposal](https://github.com/Expensify/App/issues/14355#issuecomment-1386189985) looks good to me.

I will like to suggest a minor change in the proposal if it doesn't change the expected output.

```diff
function getIOUReportActions(reportActions, iouReport, type = '', pendingAction = '', filterRequestsInDifferentCurrency = false) {
    return _.chain(reportActions)
        .filter(action => action.originalMessage
            && action.actionName === CONST.REPORT.ACTIONS.TYPE.IOU
-            && action.originalMessage.IOUReportID.toString() === iouReport.reportID.toString())
-        .filter(action => (!_.isEmpty(type) ? action.originalMessage.type === type : true))
+            && (!_.isEmpty(type) ? action.originalMessage.type === type : true))
+        .filter(action => action.originalMessage.IOUReportID.toString() === iouReport.reportID.toString())
        .filter(action => (!_.isEmpty(pendingAction) ? action.pendingAction === pendingAction : true))
        .filter(action => (filterRequestsInDifferentCurrency ? action.originalMessage.currency !== iouReport.currency : true))
        .value();
}
```
🎀👀🎀 C+ reviewed

cc: @yuwenmemon

**Comment by yuwenmemon** [comment] 2023-01-18 20:45
Sounds good thanks! @Ollyws Please submit a PR at your earliest convenience.

**Comment by strepanier03** [comment] 2023-01-19 01:49
Thank you everyone for moving this along!

**Comment by strepanier03** [comment] 2023-01-20 22:59
PR review is waiting on @yuwenmemon but he's OoO today. I'll take this into consideration when assessing the bonus for merge during payout.

**Comment by strepanier03** [comment] 2023-01-24 23:06
### Most recent update

PR is merged and awaiting deploy to staging, all good here for now.

**Comment by strepanier03** [comment] 2023-01-30 22:24
@sobitneupane and @Ollyws - Please feel free to apply for the job [here](https://www.upwork.com/jobs/~013e5bf073f9b98c1b) and I'll keep an eye open for your application so I can send you offers. If we get this taken care of now I will be able to pay more promptly on 2023-02-02. Thanks!

----

Will work on reg test now.

**Comment by strepanier03** [comment] 2023-01-31 23:23
@sobitneupane and @Ollyws - I've accepted your proposals and extended the offer, thank you for taking care of it so quickly.

**Comment by strepanier03** [comment] 2023-02-01 23:36
@sobitneupane or @yuwenmemon - Can one of you please finish the three steps in this [checklist](https://github.com/Expensify/App/issues/14355#issuecomment-1405494163)?

**Comment by strepanier03** [comment] 2023-02-01 23:52
Reg test buddy check [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1675295415585879).

**Comment by sobitneupane** [comment] 2023-02-02 04:28
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x] The PR that introduced the bug has been identified. Link to the PR: 

https://github.com/Expensify/App/pull/13329

> * [x]  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/13329#issuecomment-1413134866

> * [ ]  [@sobitneupane / @yuwenmemon] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Offline tests are already included in the PR review checklist. So, I don't think any update in the PR review checklist will be necessary.

**Comment by strepanier03** [comment] 2023-02-02 22:41
@sobitneupane and @Ollyws have been paid and contracts closed in UpWork, thank you both for your hard work. 

This GH will stay open until the reg test is resolved.

**Comment by strepanier03** [comment] 2023-02-03 23:56
Bumped reg test buddy-check.

**Comment by yuwenmemon** [comment] 2023-02-06 21:57
@strepanier03 Are we good to close this out?

**Comment by strepanier03** [comment] 2023-02-07 16:01
Nope, not ready to close yet, the reg test isn't added.

**Closed** 2023-02-07 17:17 UTC
Labels: External, Daily, Awaiting Payment, Bug
