### ISSUE TITLE
Wallet amount and wallet loader should be of the same height so that flicker does not happen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21204] opened 2023-06-21 13:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App on a slow connection
2. Go to Settings > Payments
3. Observe the Payment Methods section before the wallet amount load and after the amount loads (The prerequisite is that the user should be in beta for Using the Wallet)
## Expected Result: 
The wallet loader and wallet amount should have the same height so that after the wallet amount loads, the Payment methods should not change their place.
## Actual Result: 
After the wallet amount loads, Payment methods shift downwards from than initial place.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-06-15 at 12 24 52 PM](https://github.com/Expensify/App/assets/43996225/e163dd67-8460-4fce-95df-fdd82dc8704a)

https://github.com/Expensify/App/assets/43996225/ace8c3b3-1ff8-4993-ba9b-a730aac61d4e

https://github.com/Expensify/App/assets/43996225/66550fa1-3d1a-4028-a8f2-fb4e17499572

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686812654298169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment] 2023-06-21 13:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The wallet amount and wallet loader should be of the same height so that flicker does not happen after the amount loads

### What is the root cause of that problem?
The issue is more like a UI polish. The root cause is that the Loader and wallet amount component has different heights.

### What changes do you think we should make in order to solve the problem?
This is Loader Component, and its height is 37
https://github.com/Expensify/App/blob/7b00c47ee7debf7137417ac768efe8d4c6b872d0/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L339-L342

This is the Wallet amount Component, and its height is 67
https://github.com/Expensify/App/blob/7b00c47ee7debf7137417ac768efe8d4c6b872d0/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L344-L351

To solve this flicker, We can set minHight 67(or slightly more prominent than 67 for the safer side) to the parent View of the Loader and Wallet so that flicker does not happen when the parent View height changes from 37 to 67

https://github.com/Expensify/App/blob/7b00c47ee7debf7137417ac768efe8d4c6b872d0/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L337

```
    minHeight: 70
```

### What alternative solutions did you explore? (Optional)

**Comment by jayeshmangwani** [comment] 2023-06-21 13:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The wallet amount and wallet loader should be of the same height so that flicker does not happen after the amount loads

### What is the root cause of that problem?
The issue is more like a UI polish. The root cause is that the Loader and wallet amount component has different heights.

### What changes do you think we should make in order to solve the problem?
This is Loader Component, and its height is 37
https://github.com/Expensify/App/blob/7b00c47ee7debf7137417ac768efe8d4c6b872d0/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L339-L342

This is the Wallet amount Component, and its height is 67
https://github.com/Expensify/App/blob/7b00c47ee7debf7137417ac768efe8d4c6b872d0/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L344-L351

To solve this flicker, We can set minHight 67(or slightly more prominent than 67 for the safer side) to the parent View of the Loader and Wallet so that flicker does not happen when the parent View height changes from 37 to 67

https://github.com/Expensify/App/blob/7b00c47ee7debf7137417ac768efe8d4c6b872d0/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L337

```
    minHeight: 70
```

and need to wrap ActivityIndicator in parent View and need to add alignItems and justifyContent, 'center'

https://github.com/Expensify/App/blob/7b00c47ee7debf7137417ac768efe8d4c6b872d0/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L339-L342

```
    <View style={{flex:1, alignItems: 'center', justifyContent: 'center'}}>
        <ActivityIndicator
            color={themeColors.spinner}
            size="large"
        />
    </View>
```

<details>
  <summary>Result</summary>
  
  

https://github.com/Expensify/App/assets/35371050/08804271-9772-4264-aec7-2a9d24213292


  
</details>



### What alternative solutions did you explore? (Optional)
none

**Comment by joekaufmanexpensify** [comment] 2023-06-21 20:51
I don't think this is a bug. The experience to open the payments page works right now with no issues. It's just when there's a slow connection, there's a slight flicker before the wallet balance loads. 

There is no flicker at all with a normal connection. I don't think we need to change anything, as an occasional flicker on a slow connection isn't really a bug (especially when the product is working as expected). 

Closing for now, but happy to discuss further if y'all disagree!

**Closed by joekaufmanexpensify** 2023-06-21 20:51 UTC
Labels: Daily, Bug
