### ISSUE TITLE
[$500] Web- FAB - FAB menu disappears when User navigates to other browser tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33620] opened 2023-12-26 20:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB button
3. Navigate to other browser tab
4. Go back to the new dot tab

## Expected Result:
FAB menu should remain open when user switch between tabs

## Actual Result:
FAB menu disappears when User navigates to other browser tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c2475944-6b4a-4236-8a37-7ecc8db4aa02

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a81cd0b08cffe17</li>
        <li>Upwork Job ID: 1739741026048409600</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-12-26 20:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 FAB menu disappears when User navigates to other browser tab

### What is the root cause of that problem?
We are currently hiding the menu when sidebar screen loses focus
### What changes do you think we should make in order to solve the problem?

We should check if the client is active tab before hiding
### What alternative solutions did you explore? (Optional)

**Comment by hungdvu1710** [comment] 2023-12-27 05:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
FAB menu disappears when User navigates to other browser tab

### What is the root cause of that problem?

We currently have an event specifically dedicated to closing the popover once the page lost focus in [PopoverProvider](https://github.com/Expensify/App/blob/main/src/components/PopoverProvider/index.tsx)

```js
    React.useEffect(() => {
        const listener = () => {
            if (document.hasFocus()) {
                return;
            }
            closePopover();
        };
        document.addEventListener('visibilitychange', listener);
        return () => {
            document.removeEventListener('visibilitychange', listener);
        };
    }, [closePopover]);
```

### What changes do you think we should make in order to solve the problem?
We can consider removing this event. This event is only created for this specific use case and is only applicable to this FAB menu.

### What alternative solutions did you explore? (Optional)
Leave it there since this might be an expected behavior

**Comment by hungdvu1710** [comment] 2023-12-27 05:32
Contributor details
Your Expensify account email: hungvsme@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d71743d0b623826f

**Comment by JmillsExpensify** [comment] 2024-01-23 14:45
Thanks for the bump! I agree, I don't think this is a requirement or bug.

**Closed by JmillsExpensify** 2024-01-23 14:45 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
