### ISSUE TITLE
[HOLD for payment 2023-12-28] [$500] Workspace - Currencies do not load after transition from OldDot when other user logged in ND

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31789] opened 2023-11-23 17:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to OldDot Expensify and log in with an existing account which has a workspace
2. Open new tab > navigate to NewDot Expensify and log in with different account
3. In the OldDot tab, navigate to the workspace and click on it
4. Click on Settings > Default currency

## Expected Result:
A list of all available currencies should be shown

## Actual Result:
The list is empty, even the default currency is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/25646ed7-6d70-4d78-a9f3-420f5ace77e9

![Bug6288641_1700751338388!chrome_IGeqITBXT9](https://github.com/Expensify/App/assets/78819774/ee15dd8e-f1d4-4695-a9c1-50fcce1b196e)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019bf54ae70b3509e1</li>
        <li>Upwork Job ID: 1727745677732249600</li>
        <li>Last Price Increase: 2023-11-23</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27885178</li>
<li>AmjedNazzal | Contributor | 27885180</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cubuspl42</details>

**Comment by zukilover** [comment] 2023-11-24 09:49
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Currency list is not loaded when transitioning from OldDot to NewDot with different account.

### What is the root cause of that problem?
Currency list is loaded by `openApp()` method. In `AuthScreens`, when transitioning, this method will be called if app is logging as a new user (different user):
https://github.com/Expensify/App/blob/a2fc32bbfb8d5917e83134568187529d488812e2/src/libs/Navigation/AppNavigator/AuthScreens.js#L160-L161

The problem is, upon transitioning to a new user, app is logging out:
https://github.com/Expensify/App/blob/a2fc32bbfb8d5917e83134568187529d488812e2/src/libs/Navigation/AppNavigator/AuthScreens.js#L164-L167

then redirected to `LogInWithShortLivedAuthTokenPage` to initiate `signInWithShortLivedAuthToken`:
https://github.com/Expensify/App/blob/a2fc32bbfb8d5917e83134568187529d488812e2/src/pages/LogInWithShortLivedAuthTokenPage.js#L60-L63

In this state, user has logged in with the email from the transition, i.e. email from the URL params is the same as the session email, thus the app is treating it as a login from the same email.

### What changes do you think we should make in order to solve the problem?
There needs to be a way of storing the previous session's email so that it can be compared accurately with the email from the new session.

1. Add new property in the `Session` store:
```javascript
     /** The user's email of the previous session */
    previousSessionEmail?: string;
```

2. Create new utility to store the previous session email:
```javascript
function setPreviousSessionEmail(email: string) {
    Onyx.merge(ONYXKEYS.SESSION, {previousSessionEmail: email});
}
```

3. In `LogInWithShortLivedAuthTokenPage`, we store the email before logging in with the new one:
```javascript
       if (shortLivedAuthToken && !props.account.isLoading) {
            Session.setPreviousSessionEmail(props.session.email)
            Session.signInWithShortLivedAuthToken(email, shortLivedAuthToken);
            return;
        }
``` 

4. Compare the emails to mark the login session as a new login in `AuthScreen`:
```javascript
const isTransitioningFromUser = SessionUtils.isLoggingInAsNewUser(currentUrl, session.previousSessionEmail);
const shouldGetAllData = isUsingMemoryOnlyKeys || SessionUtils.didUserLogInDuringSession() || isLoggingInAsNewUser || isTransitioningFromUser;
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by conorpendergrast** [comment] 2023-11-24 10:04
Reproduced. Seems like it could be relatively rare in the real world, but we have plenty of customers with multiple user accounts!

**Comment by AmjedNazzal** [comment] 2023-11-24 10:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Currencies do not load after transition from OldDot when other user logged in ND

### What is the root cause of that problem?

The cause of this issue starts in this code: 

https://github.com/Expensify/App/blob/a2fc32bbfb8d5917e83134568187529d488812e2/src/libs/SessionUtils.ts#L32-L45

So in this code we are returning `false` if `session?.authToken`, and since we are deeplinking to the workspace settings from OD we would be using `Session.signInWithShortLivedAuthToken` which means `session?.authToken` will be indeed populated resulting in `AuthScreens` to call `App.reconnectApp` instead of `App.openApp` resulting in the onyx store not getting populated properly which is the reason that as you will see in the screenshot below, the LHN would be not populated either:

<img width="1280" alt="nolhn" src="https://github.com/Expensify/App/assets/74202751/182ee8a8-b1c8-40e6-9207-cf64d5359259">

### What changes do you think we should make in order to solve the problem?

We can do the following: 

1) We would add a new entry to Session.ts to watch for if the login was with short lived token

```javascript
signedInWithShortLivedAuthToken?: boolean;
```

2) We would then add a temporary onyx merge in `signInWithShortLivedAuthToken` within the `optimisticData` but remove it in `successData` to allow `App.openApp` to be called at least once when using short lived token

```javascript
function signInWithShortLivedAuthToken(email: string, authToken: string) {
  const optimisticData: OnyxUpdate[] = [
      .....
      {
          onyxMethod: Onyx.METHOD.MERGE,
          key: ONYXKEYS.SESSION,
          value: {
              signedInWithShortLivedAuthToken: true,
          },
      },
  ];
  const successData: OnyxUpdate[] = [
      ....
      {
          onyxMethod: Onyx.METHOD.MERGE,
          key: ONYXKEYS.SESSION,
          value: {
              signedInWithShortLivedAuthToken: undefined,
          },
      },
];
```

3) Finally in `SessionUtils.isLoggingInAsNewUser` we would check this new session value and if it's true we return true for `loggedInDuringSession`

```javascript
Onyx.connect({
  key: ONYXKEYS.SESSION,
  callback: (session) => {
    ....
    if (session?.signedInWithShortLivedAuthToken) {
      loggedInDuringSession = true;
    }
```

### Result

https://github.com/Expensify/App/assets/74202751/17937b3a-a7db-4f8b-937c-4c9960642c08

**Comment by conorpendergrast** [comment] 2023-11-29 13:16
@cubuspl42 there are two proposals for your review here!

**Comment by cubuspl42** [comment] 2023-11-29 14:46
C+ reviewed 🎀 👀 🎀

While both proposals sound fine, I prefer the solution by @AmjedNazzal. During the PR phase, I would suggest exploring whether the new introduced property (`signedInWithShortLivedAuthToken`) could possibly be merged with (`authToken`) as a union.

**Comment by AmjedNazzal** [comment] 2023-11-29 18:41
Thank you! offer accepted and PR will be up within a day.

**Comment by francoisl** [comment] 2024-01-02 18:46
@conorpendergrast this is ready for payment.

**Comment by thienlnam** [comment] 2024-01-04 22:50
Adding another BZ member that can issue payment while Connor is OOO - cc @sophiepintoraetz Looks like this is ready for payment

**Comment by sophiepintoraetz** [comment] 2024-01-04 23:19
We did say that payments might be a little slower with the holidays but in any case, I have paid @AmjedNazzal - just waiting on @cubuspl42 to [complete the checklist](https://github.com/Expensify/App/issues/31789#issuecomment-1865487656).

**Comment by cubuspl42** [comment] 2024-01-05 11:53
- The PR that introduced the bug has been identified. Link to the PR:
    - N/A (This is an interaction between OldDot and NewDot, both sides would need to be analyzed to point to specific PRs with certainty, while the OldDot code is not available)
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
  - Sign in to OldDot (staging) using account A
  - Sign in to NewDot (staging) using account B
  - From OldDot, go to Settings > Workspaces and click on a workspace
  - Once the NewDot app loads, go to (Your workspace) > Settings > Default currency and verify that the currency list is populated

**Comment by conorpendergrast** [comment] 2024-01-08 20:56
This was caught by Applause during testing, so I think it's already captured under existing regression testing. I think it's likely we don't need a new test as a result, but if anyone disagrees, comment and let me know! 

Apart from that, we're all done here. Thanks!

**Closed by conorpendergrast** 2024-01-08 20:56 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
