### ISSUE TITLE
[HOLD for payment 2023-12-06] [$500] IOU-App crashes on tapping split bill created in #announce as split bill participant

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31136] opened 2023-11-09 16:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap profile icon---Workspaces--Create a Workspace
3. Tap members
4. Invite members to Workspace
5. Tap on 3dots--#announce
6. Tap plus icon -- Split money
7. Enter an amount and tap next
8. Tap split amount
10. Now login new dot as a member of Workspace (ie.split bill participant)
11. Navigate to announce room'
12. Tap on split bill skeleton

## Expected Result:
Tapping on split bill skeleton in #announce room from Workspace member (ie.split bill participant) account, app must not crash.

## Actual Result:
Tapping on split bill skeleton in #announce room from Workspace member (ie.split bill participant) account, app crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6270142_1699544413023!Screenshot_20231109-150804_New_Expensify](https://github.com/Expensify/App/assets/115492554/c0d37a10-38b5-4411-90fd-01f76e38afc7)

https://github.com/Expensify/App/assets/115492554/11af2c07-5c0a-47bc-9dad-e8769b735c36

[Bug6270142_1699544234017!crash.txt](https://github.com/Expensify/App/files/13310158/Bug6270142_1699544234017.crash.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ba842ed3953850f</li>
        <li>Upwork Job ID: 1722645379128688640</li>
        <li>Last Price Increase: 2023-11-09</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 27647078</li>
</ul></li>
    </ul>
</details>

**Comment by kuttyhub** [comment] 2023-11-09 20:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes on tapping split bill created

### What is the root cause of that problem?
The root cause of this bug arises while the transaction object passed as `undefined` for the required props in [SplitBillDetailsPage](https://github.com/Expensify/App/blob/732aad9ac67d8bbef2b1a1f18216bfb2194c907a/src/pages/iou/SplitBillDetailsPage.js#L40).

why it becomes undefined is because the Onyx store doesn't have the transaction data and returns undefined. and you can see details in the below video.
 
https://github.com/Expensify/App/assets/71143839/c1a1be34-5dfb-4894-8eeb-21b6c708b9fb

### What changes do you think we should make to solve the problem?
1. while triggering the navigation we can have check whether the Transaction has data or not.
2. Fix the missing transaction records in the Onyx store - ( New to the Expensify ecosystem, any help or suggestion would be great).

### What alternative solutions did you explore? (Optional)
prevent the clicking action itself with an appropriate hint when on the loading state or the transition becomes empty.

**Comment by DylanDylann** [comment] 2023-11-10 05:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- IOU-App crashes on tapping split bill created in #announce as split bill participant

### What is the root cause of that problem?
- When the transaction data is not available, clicking on split bill action will open the [SplitBillDetailsPage](https://github.com/Expensify/App/blob/main/src/pages/iou/SplitBillDetailsPage.js). In this page, we call the function [getTransactionDetails](https://github.com/Expensify/App/blob/99dd643d0fb918bfea00bdace6f51d14ba75e745/src/libs/ReportUtils.js#L1601) with the first param (transaction) is empty, that lead to the bug "Uncaught TypeError: Cannot read properties of undefined (reading 'reportID')".
- And the error that transaction data is empty occurs inconsistently, so maybe it is BE isssue.

### What changes do you think we should make in order to solve the problem?
- We need to handle the case: The transaction is empty.
- **Firstly**, we need to prevent user from clicking on the split bill preview that will navigate the user to  [SplitBillDetailsPage](https://github.com/Expensify/App/blob/main/src/pages/iou/SplitBillDetailsPage.js). Do it by updating:
https://github.com/Expensify/App/blob/99dd643d0fb918bfea00bdace6f51d14ba75e745/src/components/ReportActionItem/MoneyRequestPreview.js#L359
to:
````diff
        <PressableWithFeedback
+            disabled={isEmpty(props.transaction) && props.isBillSplit}
````
- **Secondly**, we need to prevent user from opening the [SplitBillDetailsPage](https://github.com/Expensify/App/blob/main/src/pages/iou/SplitBillDetailsPage.js) by deeplink. Do it by dismissing the RHN or displaying PageNotFoundView if the transaction is empty by adding the below logic to to [SplitBillDetailsPage](https://github.com/Expensify/App/blob/main/src/pages/iou/SplitBillDetailsPage.js):
````diff
+   if (isEmpty(props.transaction)) {
+       return <NotFoundPage />;
+   }
````

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mananjadhav** [comment] 2023-11-10 22:19
Thanks for the proposals folks. I can see all of them have correct RCA.  Essentially we need to fix property access on transaction. Hence, I am going ahead with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/31136#issuecomment-1804143072).

🎀 👀 🎀 C+ reviewed.

**Comment by DylanDylann** [comment] 2023-11-11 00:28
@mananjadhav I have a question that if we go with @bernhardoj proposal, what will be displayed when the transaction data is not available?

**Comment by Christinadobrzyn** [comment] 2023-11-20 05:12
I'm going ooo until Monday Nov 27th so going to assign another BZ teammate to monitor this until I'm back. Thanks!

Status- reviewing PR

**Comment by Christinadobrzyn** [comment] 2023-11-28 20:10
Looks like this [blocker](https://github.com/Expensify/App/issues/32122#issuecomment-1829938047) is not a blocker but behaving as expected. It just might need design to review it. 

@mananjadhav @grgia @bernhardoj can you just confirm there's no regression with our [PR](https://github.com/Expensify/App/pull/31291) as it relates to this [GH](https://github.com/Expensify/App/issues/32122)?

**Comment by Christinadobrzyn** [comment] 2023-12-06 01:26
prepping for payment

Payouts due:

Issue Reporter: NA
Contributor: $500 @bernhardoj (in Upwork)
Contributor+: $500 @mananjadhav (in NewExpensify)

Eligible for 50% #urgency bonus? NA

Upwork job is [here](https://www.upwork.com/jobs/~012ba842ed3953850f).

@mananjadhav do we need a regression test for this?

**Comment by mananjadhav** [comment] 2023-12-06 02:54
Yes because this resulted in the app crash I think it makes sense to add the regression test here. We can add the QA steps from the PR body for the regression test.

I couldn't link any exact PR and it looks like this exists since a long time.

**Comment by Christinadobrzyn** [comment] 2023-12-06 16:51
Awesome! Made this regression test - https://github.com/Expensify/Expensify/issues/344480

There's no regression so paying this out based on this [payment structure](https://github.com/Expensify/App/issues/31136#issuecomment-1841926598). Gonna close this out!

**Closed by Christinadobrzyn** 2023-12-06 16:51 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-12-11 01:35
$500 payment approved for @mananjadhav based on [this comment](https://github.com/Expensify/App/issues/31136#issuecomment-1841926598).
