### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] Android-IOU-Tapping thread reply of expense hold offline, hmm not here displayed briefly

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49268] opened 2024-09-16 13:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Open 1:1 with an user
3. Go offline
4. Create a expense
5. Long press the expense to hold and unhold the expense
6. Open the expense
7. Tap header -- delete expense
8. Go online
9. Note deleted message with thread reply displayed little delay
10. Tap on reply

## Expected Result:
Tapping thread reply of expense hold offline, hmm not here must not be displayed briefly.

## Actual Result:
Tapping thread reply of expense hold offline, hmm not here displayed briefly.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4ad47104-3a16-4692-9976-cad4b1a72bcd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837165313806139268</li>
        <li>Upwork Job ID: 1837165313806139268</li>
        <li>Last Price Increase: 2024-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 104226323</li>
<li>nkdengineer | Contributor | 104226325</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by IuliiaHerets** [comment] 2024-09-16 13:50
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-09-17 10:23
@IuliiaHerets The video in OP doesn't match the step. Can you please update the video?

**Comment by muttmuure** [comment] 2024-09-17 18:30
No overdue

**Comment by IuliiaHerets** [comment] 2024-09-17 19:17
Uploaded a correct video, sorry for it

**Comment by nkdengineer** [comment] 2024-09-25 07:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tapping thread reply of expense hold offline, hmm not here displayed briefly.

### What is the root cause of that problem?
1. When we hold the transaction, we have an add comment but we don't update the `childVisibleActionCount` of parent report action then when we delete the money request, the `iouReport` is marked as pending delete in offline and it's cleared in success data here

https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/libs/actions/IOU.ts#L5956-L5960

### What changes do you think we should make in order to solve the problem?
When we hold a transaction here, we should update parentReportAction in optimistic data by using `getOptimisticDataForParentReportAction` function as we do in other places

```
const optimisticParentReportActions = ReportUtils.getOptimisticDataForParentReportAction(reportID, currentTime, 'add');
optimisticParentReportActions.forEach((optimisticParentReportAction) => {
    if (!optimisticParentReportAction) {
        return;
    }
    optimisticData.push(optimisticParentReportAction);
});
```
https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/libs/actions/IOU.ts#L7837

We also have another problem after doing that, the expense report still displays as the combined report. The RCA is we don't check the `singleAction` is deleted or not. To fix that we should return early if the `singleAction` is deleted

```
if (((originalMessage?.deleted ?? '') !== '' || isDeletedAction(singleAction)) && isMoneyRequestAction(singleAction)) {
    return;
}
```
https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/libs/ReportActionsUtils.ts#L1049


### What alternative solutions did you explore? (Optional)


### Result


https://github.com/user-attachments/assets/650d6e11-f34a-4d70-92aa-a9ec9cb16729

**Comment by muttmuure** [comment] 2024-09-25 16:46
@akinwale proposal above for you

**Comment by akinwale** [comment] 2024-10-02 04:18
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/49268#issuecomment-2373304087) works here.

🎀👀🎀 C+ reviewed.

**Comment by akinwale** [comment] 2024-10-25 15:18
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify
2. Open or start a 1:1 chat with a user
3. Go offline
4. Create an expense
5. Select or long-press the expense, and then Hold the expense
6. Unhold the expense
7. Open the expense
8. Tap the header and select Delete expense
9. Go online
10. Verify that the deleted message with thread reply is displayed after a small delay
11. Tap on reply
12. Verify that tapping reply to the thread of the expense that was held offline does not cause the hmm not here must page to be displayed.

Do we agree 👍 or 👎?

**Comment by nkdengineer** [comment] 2024-10-30 18:06
@muttmuure We're ready for payment here.

**Comment by muttmuure** [comment] 2024-10-30 18:54
Paid

**Closed by muttmuure** 2024-10-30 18:54 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
