### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250] `Receipt required over undefined` is shown in the violation message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43939] opened 2024-06-18 17:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718718827355089
 
## Action Performed:
Precondition : As a admin set up expense violation as " Receipt required amount" to "0" in OldDot control policy
1. Invite an employee to the above policy
2. As a employee submit a report without receipt
3. As an admin open the report submitted
## Expected Result:
 Correct error message for the receipt required violation should appear
## Actual Result:
 "receipt required over undefined" message appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Snip - (51) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/a45c8a08-4ca6-427e-b73c-5e313516e13e)
![image (6)](https://github.com/Expensify/App/assets/38435837/004d78d7-6ae1-4ad8-a441-faec2acc03fc)
![image (7)](https://github.com/Expensify/App/assets/38435837/61aa0791-458f-46f3-a0c3-968b5905a02f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e9b622536ce232c5</li>
        <li>Upwork Job ID: 1803138142417847354</li>
        <li>Last Price Increase: 2024-06-18</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 102810235</li>
<li>abzokhattab | Contributor | 102810237</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by abzokhattab** [comment] 2024-06-18 19:50
https://github.com/Expensify/App/blob/ec9ce7c4df73c65c716dd170cd30bba963b29a7c/src/languages/en.ts#L3141

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Receipt required over undefined is shown in the violation message
### What is the root cause of that problem?
 
in the current case, the user submits a report without a receipt meaning the expected error should be `Receipt required`

currently in the translation we check if the params object exists but we dont check if the value of the `formattedLimit` is undefined.

https://github.com/Expensify/App/blob/ec9ce7c4df73c65c716dd170cd30bba963b29a7c/src/languages/en.ts#L3140

### What changes do you think we should make in order to solve the problem?


change [this](https://github.com/Expensify/App/blob/ec9ce7c4df73c65c716dd170cd30bba963b29a7c/src/languages/en.ts#L3140)         

```js
receiptRequired: (params: ViolationsReceiptRequiredParams) => `Receipt required${params?.formattedLimit ? ` over ${params.formattedLimit}${params.category ? ' category limit' : ''}` : ''}`,
```

**Comment by garatkarr** [comment] 2024-06-18 21:06
I'm new here so not sure how the backend works yet but it seems to me this may be a backend issue. Onyx Pub/Sub sends the following when "Receipt Required Amount" is greater than 0:

`{
            "onyxMethod": "mergecollection",
            "key": "transactionViolations_",
            "value": {
                "transactionViolations_5942621983798817006": [
                    {
                        "type": "violation",
                        "name": "receiptRequired",
                        "data": {
                            "formattedLimit": "$0.01"
                        }
                    }
                ]
            }
        }`

but when it is 0, `data` is null like in this example:
`{
            "onyxMethod": "mergecollection",
            "key": "transactionViolations_",
            "value": {
                "transactionViolations_5942621983798817006": [
                    {
                        "type": "violation",
                        "name": "receiptRequired",
                        "data": null
                    }
                ]
            }
        },`

This is probably a backend issue with the common mistake of using something like `if(dollarAmount)` because a $0.00 amount is still a value and should not be treated as false. The backend code needs to perhaps check for not `null` and not `undefined` using `===` (strict equality)

**Comment by ahmedGaber93** [comment] 2024-06-19 20:31
reviewing

**Comment by ahmedGaber93** [comment] 2024-06-19 21:38
@abzokhattab Thanks for the proposal.

Your proposal looks good, but I think your code logic not cover all cases here https://github.com/Expensify/App/pull/33969#discussion_r1493071149. Could you please update it?

Try this in your browser console.
```javascript
const receiptRequired = (params) =>
          `Receipt required${params.category ?? params.formattedLimit ? ` over ${params.formattedLimit ?? ''}${params.category ? ' category limit' : ''}` : ''}`;


console.log(receiptRequired({}))
console.log(receiptRequired({ formattedLimit: '$500' }))
console.log(receiptRequired({ category: 'travel' }))
console.log(receiptRequired({ formattedLimit: '$500', category: 'travel' }))
```

**Comment by abzokhattab** [comment] 2024-06-20 06:46
okay i updated the proposal to produce exactly the same expected output <img width="1407" alt="image" src="https://github.com/Expensify/App/assets/59809993/403942b2-0a87-4332-b941-abd0cd4a168c">

**Comment by abzokhattab** [comment] 2024-06-23 11:46
The PR is ready.

**Comment by puneetlath** [comment] 2024-07-16 20:09
@ahmedGaber93 friendly reminder about the checklist.

**Comment by ahmedGaber93** [comment] 2024-07-17 03:36
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/33969
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/33969#discussion_r1680359718
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug. Yes
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
Precondition : As a admin set up expense violation as " Receipt required amount" to "0" in OldDot control policy

1. Invite an employee to the above policy
2. As a employee submit a report without receipt
3. As an admin open the report submitted
4. Validate that the correct translation is shown ("receipt required").

Do we agree 👍 or 👎

**Comment by puneetlath** [comment] 2024-07-17 14:53
Regression test issue: https://github.com/Expensify/Expensify/issues/413396

All paid. Thanks everyone!

**Closed by puneetlath** 2024-07-17 14:53 UTC
Labels: External, Daily, Awaiting Payment, Bug
