### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Android - LHN - Long pressing on stacked avatars results in transparency issue with avatars

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27396] opened 2023-09-14 01:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed
Precondition: User has a workspace IOU and a thread in room
1. Launch New Expensify app
2. Long press on workspace IOU row in LHN
3. Long press on the message thread row in LHN

## Expected Result:
There is no visual issues with the avatars

## Actual Result:
When long pressing on workspace IOU row in LHN, a circular overlay is seen instead of square overlay over the workspace avatar.
As for the message thread, the user avatar overlaps with workspace avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2fc43252-9512-45b3-916b-a433d98b28a3

![Bug6199499_Screenshot_20230914-032450_New_Expensify_resized](https://github.com/Expensify/App/assets/78819774/a5ca2f0d-ad63-45d0-a136-346349e7ab89)

![Bug6199499_Screenshot_20230914-040224_Gallery (2)](https://github.com/Expensify/App/assets/78819774/74a6941d-7292-4353-8624-aa16f1744b7d)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0181b4bbc15e998db5</li>
        <li>Upwork Job ID: 1702221104396021760</li>
        <li>Last Price Increase: 2023-09-14</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26771145</li>
</ul></li>
    </ul>
</details>

**Comment by imranaalam** [comment] 2023-09-14 09:29
Of course, I apologize for the oversight. I'll provide the complete structure with both the descriptive and code elements, and then I'll provide the full code at the end.

---

**Problem Statement:**  
When long pressing on the workspace IOU row in the LHN of the New Expensify app, a circular overlay is observed instead of the expected square overlay over the workspace avatar. Additionally, in the message thread, the user avatar overlaps with the workspace avatar.

**Root Cause:**  
1. The `AvatarOverlay` style definition in `styles.js` uses a `borderRadius` based on the avatar's width, creating a circular overlay for square avatars.
2. Utility functions in `StyleUtils.js` produce circular avatars or overlays when given non-square dimensions.
3. The `variables.ts` file might have inconsistent `componentBorderRadius*` values for different avatar sizes.

**Proposed Solution:**

1. **Adjust `AvatarOverlay` in `styles.js`:**  
   - Change the `borderRadius` of the `AvatarOverlay` style definition to use a consistent square border radius value, ensuring that the overlay remains square regardless of the avatar's size.
     - **Old Code**:
     ```javascript
     AvatarOverlay: {
         ...commonStyles.avatarNormal,
         borderRadius: AVATAR_SIZE.NORMAL,
     },
     ```
     - **New Code**:
     ```javascript
     AvatarOverlay: {
         ...commonStyles.avatarNormal,
         borderRadius: variables.componentBorderRadiusNormal,
     },
     ```

2. **Modify Utility Functions in `StyleUtils.js`:**
   - For the `getAvatarBorderRadius` function: Adjust it to return a consistent square border radius for avatars, particularly when dealing with workspace avatars.
     - **Old Code**:
     ```javascript
     function getAvatarBorderRadius(size, type) {
         // ... other conditions
     }
     ```
     - **New Code**:
     ```javascript
     function getAvatarBorderRadius(size, type) {
         if (type === CONST.ICON_TYPE_WORKSPACE) {
             return {borderRadius: variables.componentBorderRadiusNormal};
         }
         // ... other conditions
     }
     ```

   - For the `getHorizontalStackedOverlayAvatarStyle` function: Ensure the overlay is square by setting its `borderRadius` to a consistent square value.
     - **Old Code**:
     ```javascript
     function getHorizontalStackedOverlayAvatarStyle(oneAvatarSize, oneAvatarBorderWidth) {
         return {
             // ... other styles
         }
     }
     ```
     - **New Code**:
     ```javascript
     function getHorizontalStackedOverlayAvatarStyle(oneAvatarSize, oneAvatarBorderWidth) {
         return {
             // ... other styles
             borderRadius: variables.componentBorderRadiusNormal,
         }
     }
     ```

3. **Consistent Avatar Dimensions:** 
   - Make sure all avatar components in the application have equal width and height, ensuring a square appearance. Additionally, apply a consistent border radius to maintain the desired avatar shape.
     - **Old Code**:
     ```javascript
     AvatarComponent: {
         // ... other styles
     },
     ```
     - **New Code**:
     ```javascript
     AvatarComponent: {
         width: AVATAR_SIZE.NORMAL,
         height: AVATAR_SIZE.NORMAL,
         borderRadius: variables.componentBorderRadiusNormal,
     },
     ```
 **Full Code Changes:**

```javascript
// styles.js
AvatarOverlay: {
    ...commonStyles.avatarNormal,
    borderRadius: variables.componentBorderRadiusNormal,
},

// StyleUtils.js
function getAvatarBorderRadius(size, type) {
    if (type === CONST.ICON_TYPE_WORKSPACE) {
        return {borderRadius: variables.componentBorderRadiusNormal};
    }
    // ... other conditions
}

function getHorizontalStackedOverlayAvatarStyle(oneAvatarSize, oneAvatarBorderWidth) {
    return {
        // ... other styles
        borderRadius: variables.componentBorderRadiusNormal,
    }
}

// Any component or file where AvatarComponent is defined
AvatarComponent: {
    width: AVATAR_SIZE.NORMAL,
    height: AVATAR_SIZE.NORMAL,
    borderRadius: variables.componentBorderRadiusNormal,
},
```


**Alternative Solution:**  
1. Introduce a new style variable specifically for avatars and overlays.
2. Adopt a visual testing framework to detect inconsistencies automatically.

---

**Comment by imranaalam** [comment] 2023-09-14 09:47
---

**Problem Statement:**
When long pressing on the workspace IOU row in the LHN (Left Hand Navigation) of the New Expensify app, a circular overlay is observed instead of the expected square overlay over the workspace avatar. Additionally, for the message thread, the user avatar overlaps with the workspace avatar.

**Root Cause:**
The circular overlay arises due to the `borderRadius` property of the `AvatarOverlay` style in the `styles.js` file. This property is set to the avatar's width, resulting in a circular overlay when the avatar's width and height are equal.

**Proposed Solution:**
1. **Adjust AvatarOverlay in `styles.js`:** Change the `borderRadius` of the `AvatarOverlay` style definition to use a consistent square border radius value. 
    - **Old Code:**
      ```javascript
      AvatarOverlay: {
          ...commonStyles.avatarNormal,
          borderRadius: AVATAR_SIZE.NORMAL,
      },
      ```
    - **New Code:**
      ```javascript
      AvatarOverlay: {
          ...commonStyles.avatarNormal,
          borderRadius: variables.componentBorderRadiusNormal,
      },
      ```

2. **Consistent Avatar Dimensions:** Ensure all avatar components in the application have equal width and height. From our examination, the avatar components already adhere to this principle.

**Alternative Solution:**
Introduce a new style variable specifically for avatars and overlays to ensure a consistent square appearance. Additionally, consider implementing a visual testing framework or tool that can automatically detect visual inconsistencies in avatars or other UI elements, catching visual issues early in the development cycle and preventing them from reaching production.

---

**Comment by narefyev91** [comment] 2023-09-15 07:57
Proposal from @bernhardoj looks good to me https://github.com/Expensify/App/issues/27396#issuecomment-1719637570 thanks for detail explanation!
🎀 👀 🎀 C+ reviewed

**Comment by laurenreidexpensify** [comment] 2023-09-18 08:16
@MonilBhavsar bump ^^

**Comment by MonilBhavsar** [comment] 2023-09-20 06:47
Sorry been dealing with a fire. Taking a look now

**Comment by MonilBhavsar** [comment] 2023-09-20 06:51
Proposal looks good to me. Looks like we have seen similar issues with only Android in the past. If we can add some test steps to prevent it from happening

**Comment by Pujan92** [comment] 2023-09-27 11:59
@bernhardoj Seems regression of crashes after this PR merged. https://expensify.slack.com/archives/C049HHMV9SM/p1695796696023189

**Comment by MonilBhavsar** [comment] 2023-09-28 02:34
Thank you!

**Comment by laurenreidexpensify** [comment] 2023-10-11 10:17
Payment Summary: 

-  External issue reporter - Applause N/A 
-  Contributor that fixed the issue - @narefyev91 expert contributor N/A 
-  Contributor+ that helped on the issue and/or PR - @narefyev91 = payment issued in Upwork $500 

@narefyev91 please advise on checklist above thanks so we can close this out

**Comment by laurenreidexpensify** [comment] 2023-10-13 13:08
Bump for checklist @narefyev91

**Comment by MonilBhavsar** [comment] 2023-10-13 13:12
> Payment Summary:
> 
> * External issue reporter - Applause N/A
> * Contributor that fixed the issue - @narefyev91 expert contributor N/A
> * Contributor+ that helped on the issue and/or PR - @narefyev91 = payment issued in Upwork $500
> 
> @narefyev91 please advise on checklist above thanks so we can close this out

@laurenreidexpensify contributor that fixed the issue should be @bernhardoj ?

**Comment by situchan** [comment] 2023-10-13 13:35
There was regression - https://github.com/Expensify/App/issues/28317

**Comment by narefyev91** [comment] 2023-10-16 08:12
- The PR that introduced the bug has been identified. Link to the PR - current PR was fixing missing functionality and second one already fix regression from initial one
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by MonilBhavsar** [comment] 2023-10-18 06:55
Looks like we're good to close this issue?

**Comment by MonilBhavsar** [comment] 2023-10-18 11:56
@laurenreidexpensify yes, there was a regression coming from this PR which was fixed by @bernhardoj

**Closed** 2023-10-20 10:41 UTC
Labels: External, Daily, Awaiting Payment, Bug
