### ISSUE TITLE
[HOLD for payment 2024-07-10] Expense - "started settling up.." thread header shows infinite skeleton

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44338] opened 2024-06-24 21:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-9
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Admin and employee are in the same workspace.
- The workspace is connected to Wells Fargo bank account.
- Employee does not have a bank account.

1. Go to staging.new.expensify.com
2. [Employee] Submit an expense to the workspace chat.
3. [Admin] Go to workspace chat with employee.
4. [Admin] Approve the expense.
5. [Admin] Pay with Expensify the expense.
6. [Admin] Wait for "started settling up.." message to show up, then right click on it > Reply in thread.

## Expected Result:
"started settling up.." thread header will display content.

## Actual Result:
"started settling up.." thread header shows infinite skeleton.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/1934b257-064b-49cf-900c-0ab47b78ed3e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by m-natarajan** [comment] 2024-06-24 21:10
We think that this bug might be related to #wave-collect - Release 1

**Comment by aldo-expensify** [comment] 2024-06-24 22:54
I think the cause is this:  https://github.com/Expensify/App/pull/40168/files#r1651736267

**Comment by aldo-expensify** [comment] 2024-06-24 23:01
PR up: https://github.com/Expensify/App/pull/44357

**Comment by nkdengineer** [comment] 2024-06-25 03:01
Thanks @aldo-expensify for the fix, I was not available last night.

**Comment by mountiny** [comment] 2024-06-25 10:41
The CPed Pr was validated

**Comment by strepanier03** [comment] 2024-07-02 19:05
It doesn't look like we need to pay anyone for this but I believe we still need to do the checklist, at least the reg test part. 

@aldo-expensify - Can you take a look at the checklist and fill out anything that is necessary? If we don't need a reg test, feel free to just close this out as done.

**Closed** 2024-07-11 01:32 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
