### ISSUE TITLE
[$250] BUG: Pay button is not visible above the keyboard on the IOU confirmation page

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#11722] opened 2022-10-11 16:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with any account
2. If needed, start a chat with someone other than concierge by clicking the green plus, New chat, typing in a valid email, and selecting that person.
3. Click the plus at the bottom left, Send money
4. Enter an amount and hit next

## Expected Result:
The pay button appears above the keyboard

## Actual Result:
The pay button is hidden below the keyboard and there is extra gray space below it.

## Workaround:
Scroll down and click the button, ignore the ugly space below it.

## Platform:

Where is this issue occurring?
- Mobile Web iOS / Safari
- Android / Chrome?

**Version Number:** v1.2.11-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**
https://user-images.githubusercontent.com/26260477/194914536-aa182e74-6c8a-4162-9fe0-3f6203337e7d.mp4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @neil-marcellini 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2022-10-12 19:35
I am removing the Help Wanted label and putting this on hold for https://github.com/Expensify/App/issues/10273

**Comment by mountiny** [comment] 2022-10-21 18:01
Still on hold

**Comment by tgolen** [comment] 2022-10-31 16:47
This is no longer on hold and can have proposals created for it with the new code.

**Comment by mountiny** [comment] 2022-10-31 16:59
Making this Weekly an waiting for proposals, unassigned, Tim and Kosuke as I was assigned by the External label.

Waiting for proposals. 

@kbecciv @mvtglobally Can you please confirm this is still reproducible?

**Comment by tgolen** [comment] 2022-10-31 17:07
@vitHoracek I wanted to keep this assigned to me so I could keep an eye on the proposals to ensure they are not hacks or workarounds with some of the foundational changes I made. I'll let you lead this issue, but I'll just be lurking in the background.

**Comment by mountiny** [comment] 2022-10-31 17:08
@tgolen No problem, thank you for clarifying! 🙌

**Comment by JmillsExpensify** [comment] 2022-11-02 19:54
@conorpendergrast  Given that we're still early and no proposals have been accepted, I'm assigning myself per the new BZ process: https://stackoverflow.com/c/expensify/questions/14597/14598#14598.

**Comment by JmillsExpensify** [comment] 2022-11-02 19:56
Btw, we still need this issue tested, thanks Applause!

**Comment by JmillsExpensify** [comment] 2022-11-06 02:38
@vitHoracek for clarity, did you test on Android?

**Comment by mountiny** [comment] 2022-11-06 10:00
@JmillsExpensify nope, only on iOS. Dont own Android, but thinking of getting some troubleshooting.

**Comment by JmillsExpensify** [comment] 2022-11-06 20:14
Ok thanks! I just confirmed on iOS as well. The pay button doesn't appear above the keyboard. 

Contributors - this issue is open for proposals. Related Upwork job is here: https://www.upwork.com/jobs/~01092b6ed16494aaaa.

**Comment by Santhosh-Sellavel** [comment] 2022-11-06 20:27
This is working fine in Android!
https://user-images.githubusercontent.com/85645967/200193378-ea6e3ceb-8355-4e0f-8f90-51c7813a3cee.mp4

This issue is a common issue that occurs on most screens not just on this page.

**Comment by JmillsExpensify** [comment] 2022-11-06 20:39
Thank you for stepping in and helping confirm on Android! In fact, I just realized that this issue is a dupe of https://github.com/Expensify/App/issues/10670. I'm going to close this issue and add these testing steps to the linked issue. We can continue working through things there.

**Closed by JmillsExpensify** 2022-11-06 20:39 UTC
Labels: External, Engineering, Daily, Improvement, Bug
