### ISSUE TITLE
[$250] Web - infinite spinner when clicking on Concierge icon, also it displayed as the default icon for new accounts

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10925] opened 2022-09-09 14:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Create and validate expensifail new account
3. Click on Concierge icon

## Expected Result:
1. Detail page should be open when clicking on Concierge icon
2. Must have a special badge for the Concierge icon

## Actual Result:
1. Infinite spinner when clicking on Concierge icon
2. Concierge icon displayed as the default icon

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.99.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any new accounts

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![0909](https://user-images.githubusercontent.com/93399543/189375414-ea82121e-cae0-4943-852b-3da38e2d9538.png)

https://user-images.githubusercontent.com/93399543/189375416-8b9ce355-2fbb-496c-ba6a-7aa4cf9d5b4e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2022-09-09 14:38
We logged similar issue on build 1.1.94.4 https://github.com/Expensify/App/issues/10699

**Comment by Julesssss** [comment] 2022-09-09 14:45
> Infinite spinner when clicking on Concierge icon

This seems distinct from the linked issue. Let's solve this on this issue

**Comment by youssef-lr** [comment] 2022-09-09 16:11
Is it normal that I don't see Concierge right away after creating a new account?

<img width="1800" alt="Screen Shot 2022-09-09 at 17 11 05" src="https://user-images.githubusercontent.com/9680864/189394466-801a61a7-0756-4932-aa79-5ac276b6290c.png">

**Comment by luacmartins** [comment] 2022-09-09 17:22
I'm also unable to reproduce this. @kbecciv is this consistently reproducible by the team?

https://user-images.githubusercontent.com/22219519/189408947-9b844a68-aea5-467c-8b13-4c55dec07c74.mov

**Comment by MonilBhavsar** [comment] 2022-09-09 18:39
In newly created account, I don't see concierge chat at all. Is this expected or is it because of some beta?

> edit: it takes a while but Concierge chat appears

@youssef-lr Did you do anything? and after how much time did it appear?

**Comment by youssef-lr** [comment] 2022-09-09 18:41
Concierge chat only appears to me after I sign up on OldDot with the newly
created account.

**Comment by aldo-expensify** [comment] 2022-09-11 17:19
@youssef-lr yes, there is a bug that is causing that accounts under a domain with domain chat don't get the Concierge chat created. This should be fixed soon in production when this PR is deployed: https://github.com/Expensify/Web-Expensify/pull/34790 .

**Comment by aldo-expensify** [comment] 2022-09-11 19:13
I failed to reproduce... but I did have to go to OldDot to get the Concierge chat created. @kbecciv how did you get to have the Concierge chat following the steps listed? those steps with a expensifail account end up without a Concierge chat.

**Comment by Julesssss** [comment] 2022-09-12 09:08
I am also unable to reproduce after creating a new account on old dot. 

@yuwenmemon I'm removing the deployBlocker label as **A)** It's not consistently reproducible, and **B)** it's a pretty minor issue (users can still chat with concierge)

**Comment by deetergp** [comment] 2022-09-12 16:33
I'm pretty sure this can be worked on by an external contributor.

**Comment by kevinksullivan** [comment] 2022-09-13 20:14
Just to be clear @deetergp , should this GH solve for both of the mentioned problems?

- Infinite spinner when clicking on Concierge icon
- Concierge icon displayed as the default icon

**Comment by deetergp** [comment] 2022-09-14 00:04
@kevinksullivan Hmm… That's a good question. Let's get some proposals for the infinite spinner issue and if the concierge icon issue turns out to be unrelated maybe we can spin it out to its own issue.

**Comment by kevinksullivan** [comment] 2022-09-19 16:13
Ok I am just going to keep the issues together for posting to upwork then, since I don't want to prematurely divide them up if they are closely related.

**Comment by kevinksullivan** [comment] 2022-09-19 16:15
https://www.upwork.com/jobs/~01f623d5c09c0fbbcd

**Comment by srikarparsi** [comment] 2022-09-28 18:08
@kevinksullivan @parasharrajat should we double the price on this issue or close it since we can't reproduce?

**Comment by kevinksullivan** [comment] 2022-09-29 14:51
I can't reproduce either so I'm going to close it out.

**Closed by kevinksullivan** 2022-09-29 14:51 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
