### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] Mark down - Copying and pasting part of a code block doesn't work

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43551] opened 2024-06-12 11:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open any chat report
3. Send a code block using opening three back ticks and closing three back ticks at the end
4. Select part of the sent code block and press ctrl + c to copy and paste it on the compose box

## Expected Result:
The copied code block is pasted

## Actual Result:
Nothing gets pasted in the compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6728d623-7b1b-4ddf-8d57-604d9d52ff73

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd2b97089b315a6c</li>
        <li>Upwork Job ID: 1800965003148739899</li>
        <li>Last Price Increase: 2024-06-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by izarutskaya** [comment] 2024-06-12 11:40
@alexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by danieldoglas** [comment] 2024-06-12 15:19
I think this was caused by https://github.com/Expensify/App/pull/43270

Reverting that PR solved the issue for me locally.

**Comment by danieldoglas** [comment] 2024-06-12 15:21
@mollfpr @rlinoz @SzymczakJ can you please check what's going on here? Seems related to https://github.com/Expensify/App/pull/43270

**Comment by rlinoz** [comment] 2024-06-12 16:12
Indeed reverting the PR fixes it

**Comment by rlinoz** [comment] 2024-06-12 16:23
Not adding the `excludeStyles` as a dependency here https://github.com/Expensify/App/pull/43270/files#diff-a1120b846ebeebcc99d15542e13bd9537c273751a97bce6a0de03295ec98d2baR89 fixes it, but I don't understand why

**Comment by SzymczakJ** [comment] 2024-06-12 16:40
On it. I'll try to find solution ASAP

**Comment by alexpensify** [comment] 2024-06-12 19:13
Ok, I've updated the assignments here to reflect everyone who is helping to address this issue.

**Comment by danieldoglas** [comment] 2024-06-13 12:41
Removing blocker label since it was CP'd

**Comment by alexpensify** [comment] 2024-06-20 22:07
@situchan—I've sent you the offer via Upwork. Please accept it. Then, I'll complete the payment process. Thanks!

**Comment by alexpensify** [comment] 2024-06-20 22:11
@situchan - I've sent over an offer via Upwork. Please accept, and then I can complete the payment process. Thanks!

**Comment by alexpensify** [comment] 2024-06-24 21:59
All set here, I've completed the payment process. All actions are complete here -- closing!

**Closed by alexpensify** 2024-06-24 21:59 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Awaiting Payment, Bug
