### ISSUE TITLE
[HOLD for payment 2024-02-07] [$1000] Chat - Hover color is not displayed even on move of cursor on changing windows and back

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29077] opened 2023-10-09 10:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Hover on any message
4. Use CMD+TAB to change window and use it again to get back to app
5. Move cursor over the same message and observe that no hover color is displayed

## Expected Result:
App should display hover color on message when we move cursor over that message

## Actual Result:
App does not display hover color on message when we hover on the message, change window and again visit the app and move the cursor on that message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.79-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/66cc5bd5-a1fb-401b-a2cf-21f7491d0fc3

https://github.com/Expensify/App/assets/115492554/f82cd807-4a18-46fa-85fe-11283bbf610c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696667037989909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f7a0e22541d49f4</li>
        <li>Upwork Job ID: 1711324702431768576</li>
        <li>Last Price Increase: 2023-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 28117244</li>
<li>Krishna2323 | Contributor | 28117245</li>
</ul></li>
    </ul>
</details>

**Comment by chamysoftware** [comment] 2023-10-09 14:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When switching to a different window, the hover effect is lost. 
And the hover effect is not working untill we do mouse out and mouse enter again.

### What is the root cause of that problem?
In the Hoverable component (src/components/Hoverable/index.js), 
we're removing the hover effect when document is losing visibility.
But we're not setting the hover back when the document is gaining the visibility back.

### What changes do you think we should make in order to solve the problem?
We need to add a mouse over event handler in addition to the other handlers here: https://github.com/Expensify/App/blob/3007017c1848a46cc70faf1618957f1289859788/src/components/Hoverable/index.js#L157-L170
On mouse over, we need to set is hovered to true. 

We need to do this in a way that it doesn't trigger additional re-renders. I see we already have a class property called `isHoveredRef` and a method called `setIsHovered` on the component. We can use this to efficiently set the hovered state. We can call `setIsHovered(true)` function only when `isHoveredRef` is false.


### What alternative solutions did you explore? (Optional)
NA

**Comment by Mostick** [comment] 2023-10-09 14:36
I have found the issue and have a fix for it. 
You just need to handle additional (or replace existing) mouse event in one of your components.

**Comment by dylanexpensify** [comment] 2023-10-09 15:04
@0xmiroslav mind reviewing proposals? 🙇‍♂️

**Comment by yh-0218** [comment] 2023-10-10 06:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hover color is not displayed even on move of cursor on changing windows and back
### What is the root cause of that problem?
Because we don't have function to control Mouse Movement.
### What changes do you think we should make in order to solve the problem?
We can add onMouseMove event after onMouseLeave event.
```
onMouseMove: (el) => {
                if (this.isHoveredRef) {
                    return
                }
                this.setIsHovered(true);
                if (_.isFunction(child.props.onMouseMove)) {
                    child.props.onMouseMove(el);
                }
},
```
https://github.com/Expensify/App/blob/8d42ad3221927f5bf0e83b6d0e8c90038d03f4e5/src/components/Hoverable/index.js#L164-L171
### What alternative solutions did you explore? (Optional)

**Comment by Vadym-33** [comment] 2023-10-10 06:49
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Hover color is not displayed even on move of cursor on changing windows and back
### What is the root cause of that problem?
Because we don't have function to control `Mouse Movement`.
### What changes do you think we should make in order to solve the problem?
We need to add onMouseMove event to 
https://github.com/Expensify/App/blob/8d42ad3221927f5bf0e83b6d0e8c90038d03f4e5/src/components/Hoverable/index.js#L142
```
onMouseMove: (el) => {
                if (_.isFunction(child.props.onMouseMove)) {
                    child.props.onMouseMove(el);
                }
                if (this.isHoveredRef) {
                    return
                }
                this.setIsHovered(true);
},
```
### What alternative solutions did you explore? (Optional)

**Comment by dylanexpensify** [comment] 2023-10-10 19:11
reviewing tomorrow AM!

**Comment by chamysoftware** [comment] 2023-10-12 12:29
@dylanexpensify a gentle reminder to review the Proposals here :)

**Comment by chamysoftware** [comment] 2023-10-12 13:35
@0xmiroslav, just checked. My proposal above works even when the mouse is not moved: 

https://github.com/Expensify/App/assets/140621077/620491e7-c7a8-42e2-a780-211b6ac85025

I'm not touching the mouse while recording the screen

**Comment by Vadym-33** [comment] 2023-10-12 13:46
hello @0xmiroslav Do you check my proposal?

**Comment by dylanexpensify** [comment] 2023-10-16 09:33
bump @0xmiroslav ^ 🙇‍♂️

**Comment by Vadym-33** [comment] 2023-10-18 09:19
Hello, @dylanexpensify How to think about [my proposal](https://github.com/Expensify/App/issues/29077#issuecomment-1754520081)

**Comment by yh-0218** [comment] 2023-10-18 09:40
@dylanexpensify 
If we want to change hover status when only back and move on that, then we can like this.
Need to update `checkHover` function
```
checkHover(e) {
        if (!this.wrapperView) {
            return;
        }

        if (this.wrapperView.contains(e.target)) {
            if (!this.state.isHovered) {this.setIsHovered(true);}
            return;
        }

        this.setIsHovered(false);
 }
```
https://github.com/Expensify/App/blob/2ff8c496c98773b3e95a949e2ea82356e35460c9/src/components/Hoverable/index.js#L108

**Comment by dylanexpensify** [comment] 2023-10-30 09:39
Doubling!

**Comment by yh-0218** [comment] 2023-10-30 11:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hover color is not displayed even on move of cursor on changing windows and back
### What is the root cause of that problem?
We don't have controller of mouse move.
### What changes do you think we should make in order to solve the problem?
We need to add mouth move event
```
onMouseMove: enableHoveredOnMouseMove,
```
https://github.com/Expensify/App/blob/e99c297332c738475cfe5701e0a00ba0b5d58029/src/components/Hoverable/index.js#L213
And need to update code
```
if (shouldHandleScroll && isScrolling.current && hovered === isHovered) {
```
https://github.com/Expensify/App/blob/e99c297332c738475cfe5701e0a00ba0b5d58029/src/components/Hoverable/index.js#L69
### What alternative solutions did you explore? (Optional)

https://github.com/Expensify/App/assets/65789015/4e085b63-7c07-49d4-8c02-0ac196794e53

**Comment by dylanexpensify** [comment] 2023-11-06 10:17
@0xmiroslav we have proposals to review! 🙇

**Comment by dylanexpensify** [comment] 2023-11-07 09:59
internal application now 😢

**Comment by dylanexpensify** [comment] 2023-11-14 09:56
Nice, looking forward to the update @0xmiroslav!

**Comment by Julesssss** [comment] 2023-11-20 15:19
> updating today

Bumping this @0xmiroslav, any thoughts?

**Comment by dylanexpensify** [comment] 2023-12-05 20:08
Nice, @0xmiroslav to confirm!

**Comment by dylanexpensify** [comment] 2023-12-11 08:42
bump @0xmiroslav 🙇‍♂️

**Comment by dylanexpensify** [comment] 2023-12-13 08:47
bump @0xmiroslav

**Comment by dylanexpensify** [comment] 2023-12-20 09:32
bump @0xmiroslav

**Comment by dylanexpensify** [comment] 2024-01-09 12:23
@0xmiroslav update?

**Comment by Julesssss** [comment] 2024-01-15 09:51
Not overdue, update expected today

**Comment by dylanexpensify** [comment] 2024-01-17 09:29
@0xmiroslav please give an update or we can re-assign my friend

**Comment by Julesssss** [comment] 2024-01-17 10:11
[Bumped in Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1705486152200809)

**Comment by Julesssss** [comment] 2024-01-23 10:23
Hey @Krishna2323, sorry for the delay. I agree and will assign now.

**Comment by mallenexpensify** [comment] 2024-01-24 01:19
@jjcoffee reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by jjcoffee** [comment] 2024-01-24 12:52
Thanks! Top of my list for review tomorrow.

**Comment by jjcoffee** [comment] 2024-01-24 12:55
Ah just noticed, @0xmiroslav already completed the review. I think it's fair that they get paid for that! cc @mallenexpensify

**Comment by mallenexpensify** [comment] 2024-01-27 18:32
ah.. thanks, I think I was looking for 'merged' vs 'completed review', appreciate the headsup, if no additional work is needed on the PR, @0xmiroslav will be fully compensated.

**Comment by mvtglobally** [comment] 2024-01-30 04:56
Issue not reproducible during KI retests. (First week)

**Comment by dylanexpensify** [comment] 2024-01-31 10:02
@Krishna2323 can you add video to confirm?

**Comment by dylanexpensify** [comment] 2024-02-07 10:29
today!

**Comment by Julesssss** [comment] 2024-02-09 09:28
> @mallenexpensify, is @0xmiroslav still active on this? If not the who will complete the checklist 🤔

I just checked them off. THis wasn't a regression and is too minor for a regression test IMO

**Comment by dylanexpensify** [comment] 2024-02-12 10:24
Payment summary:
- Contributor+: @0xmiroslav $1000
- Contributor: @Krishna2323 $1000
- Reporter: @dhanashree-sawant $50

**Comment by dhanashree-sawant** [comment] 2024-02-12 11:31
Thanks @dylanexpensify, I have accepted the offer.

**Comment by dylanexpensify** [comment] 2024-02-12 12:02
done!

**Closed by dylanexpensify** 2024-02-12 12:02 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
