### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] Search - Attachment from qa.guide loads infinitely when opened in Search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50006] opened 2024-10-01 16:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM
3. Send the following message. (The message is from [qa.guide@team.expensify.com](mailto:qa.guide@team.expensify.com)
in #admins)
![Setup Guide GIF](https://d2k5nsl2zxldvw.cloudfront.net/images/animations/animation_setupguide.gif
)
4. Go to Search > Chat
5. Click on the message sent in Step 3

## Expected Result:
The attachment will load without issue

## Actual Result:
The attachment loads infinitely
This issue only happens to this specific attachment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e01f2bbd-a43a-4abd-a34e-271b8b8ee4f1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841561644716083523</li>
        <li>Upwork Job ID: 1841561644716083523</li>
        <li>Last Price Increase: 2024-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104307339</li>
<li>shahinyan11 | Contributor | 104307340</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment] 2024-10-01 16:25
We think that this bug might be related to #wave-control

**Comment by huult** [comment] 2024-10-03 07:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Attachment from qa.guide loads infinitely when opened in Search

### What is the root cause of that problem?

When opening an image from `Search`, `isAuthTokenRequired` is [`true`](https://github.com/Expensify/App/blob/e61ee7fbe60acc12879b9d5cc6ef92c4a0b98caa/src/pages/home/report/ReportAttachments.tsx#L49) in AttachmentModal. In this case, an auth token must be included in the image request. This issue causes the error logs shown below:

- <img width="1508" alt="Screenshot 2024-10-03 at 13 59 04" src="https://github.com/user-attachments/assets/41f4aa79-2129-42c8-a10a-886344548ac5">


https://github.com/Expensify/App/blob/e61ee7fbe60acc12879b9d5cc6ef92c4a0b98caa/src/pages/home/report/ReportAttachments.tsx#L49

### What changes do you think we should make in order to solve the problem?
To resolve this issue, we should remove this condition, like this:
```diff
// .src/pages/home/report/ReportAttachments.tsx#L49
        <AttachmentModal
            ....
            shouldShowNotFoundPage={!isLoadingApp && type !== CONST.ATTACHMENT_TYPE.SEARCH && !report?.reportID}
-            isAuthTokenRequired={type === CONST.ATTACHMENT_TYPE.SEARCH}
        />
```

**Comment by suneox** [comment] 2024-10-03 16:50
We’re still awaiting a proposal on this issue. The RCA and solution provided by @huult proposal are not correct.

**Comment by shahinyan11** [comment] 2024-10-03 17:04
@suneox @lanitochka17  I think the "Action performed:" steps  and the provided video are not clear to users who are not familiar with Expensify. How to see `#admins` chat ? What steps should be done to have this message in somewhere to copy and test

**Comment by suneox** [comment] 2024-10-03 17:17
@shahinyan11 At step 3 you have to copy content after `Send the following message ( ... )` to step 4

**Comment by shahinyan11** [comment] 2024-10-03 17:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Attachment from qa.guide loads infinitely when opened in Search

### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/ba9af8f082e76fc7da666e7f128574761fa97012/src/components/Image/index.tsx#L53C1-L55C23) we add `X-Chat-Attachment-Token` key in headers and it cause CORS error 
### What changes do you think we should make in order to solve the problem?
Add `mode: 'no-cors'` in returned object [here](https://github.com/Expensify/App/blob/ba9af8f082e76fc7da666e7f128574761fa97012/src/components/Image/index.tsx#L51C24-L56C18) obj
```
{
    ...propsSource,
    mode: 'no-cors',
    headers: {
        [CONST.CHAT_ATTACHMENT_TOKEN_KEY]: authToken,
    },
};
```

### What alternative solutions did you explore? (Optional)
Or the CORS should be fixed on backend side

**Comment by shahinyan11** [comment] 2024-10-03 18:04
> @shahinyan11 At step 3 you have to copy content `Send the following message ( ... ) included image`

@suneox Thanks for your help.

**Comment by huult** [comment] 2024-10-04 01:47
## [Proposal Updated](https://github.com/Expensify/App/issues/50006#issuecomment-2390673485)

- Update the RCA.
- Update the solution to resolve this issue.

@suneox, could you please check again? Thank you.

**Comment by suneox** [comment] 2024-10-04 11:38
Thanks for all the proposals. I don’t think this issue is related to CORS blocking, since the images from both the chat and the search load the same resource url, just only the headers being different.

https://github.com/user-attachments/assets/a366626c-ed5f-4f8a-9b30-1c047b5ee101

@shahinyan11 Your solution doesn't work on my side

> To resolve this issue, we can read the image from the cache to display it when opening the attachment. To retrieve the image from the cache, we update the parameters in the URL to match those of the previous image load.

@huult Could you please explain why updating the reportID parameter in the URL allows us to get a cached image, even though the image source (attachment?source) from URL does not change?

**Comment by shahinyan11** [comment] 2024-10-04 12:38
@suneox Do you mean that my solution doesn't work at all or it's a workaround?

**Comment by suneox** [comment] 2024-10-04 15:28
> @suneox Do you mean that my solution doesn't work at all or it's a workaround?

@shahinyan11  Your solution doesn’t work as expected, the image still loads indefinitely

https://github.com/user-attachments/assets/598f84b5-9f89-4a63-aa7d-f9e7a1f0d875

**Comment by shahinyan11** [comment] 2024-10-05 13:36
## Proposal
[Updated](https://github.com/Expensify/App/issues/50006#issuecomment-2392003066). I have updated the RCA and solution

**Comment by huult** [comment] 2024-10-06 16:34
## [Proposal update](https://github.com/Expensify/App/issues/50006#issuecomment-2390673485)

- Update RCA

Hi @suneox , could you please check it again? thanks

**Comment by suneox** [comment] 2024-10-06 18:33
Thanks for all the updates. I’ll reevaluate them within today.

**Comment by suneox** [comment] 2024-10-07 17:54
Although both solutions can resolve the issue but @shahinyan11’s solution is simpler. Instead of always setting `isAuthTokenRequired` in the attachment search case, we will retrieve the `isAuthTokenRequired` status from the previous thumbnail so we can proceed with @shahinyan11 [solution](https://github.com/Expensify/App/issues/50006#issuecomment-2392003066).

🎀 👀 🎀 C+ reviewed

**Comment by suneox** [comment] 2024-10-22 18:06
### Checklist

- [x] [@suneox] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/47690
- [x] [@suneox] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. [Link to comment](https://github.com/Expensify/App/pull/47690/files#r1811169194)
- [x] [@suneox] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: *N/A*
- [x] [@suneox] Determine if we should create a regression test for this bug: *N/A*
- [x] [@suneox] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again. *N/A*

**Comment by garrettmknight** [comment] 2024-10-24 17:27
All paid out!

**Closed by garrettmknight** 2024-10-24 17:27 UTC
Labels: External, Daily, Awaiting Payment, Bug
