### ISSUE TITLE
[HOLD for payment 2024-07-26] [$250] Expense- Zeros are added to currency that does not support decimal and unable to delete amount

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43215] opened 2024-06-06 19:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4600954
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Go to + > Submit expense > Manual.
4. Select a currency that does not support decimal places (MRO).
5. Enter amount > Next.
6. On confirmation page, click Amount.
7. Attempt to delete the amount.

## Expected Result:
In Step 6, zeros will not be added to the amount since MRO does not support decimal places.
In Step 7, user will be able to delete the amount in the input.
## Actual Result:
In Step 6, zeros are added to the amount since MRO does not support decimal places.
In Step 7, user is unable to delete the amount in the input.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/74aefadc-00aa-4132-a0a9-9c3ece1fbc4f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016395490df57af5ba</li>
        <li>Upwork Job ID: 1798895579857281936</li>
        <li>Last Price Increase: 2024-06-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by m-natarajan** [comment] 2024-06-06 19:12
@greg-schroeder FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-06 19:12
We think that this bug might be related to #wave-collect - Release 1

**Comment by dangrous** [comment] 2024-06-06 19:19
popping in here - likely from https://github.com/Expensify/App/pull/40062

**Comment by neil-marcellini** [comment] 2024-06-06 20:13
Frontend specific

**Comment by mountiny** [comment] 2024-06-06 21:02
Commented [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1717707731225389?thread_ts=1717701070.288499&cid=C01GTK53T8Q) but I dont think this has to be a deploy blocker

**Comment by dangrous** [comment] 2024-06-06 21:07
agreed, I think we can do this as a follow up

**Comment by greg-schroeder** [comment] 2024-06-11 01:53
Proposal review underway

**Comment by greg-schroeder** [comment] 2024-06-11 01:58
Bump @shubham1206agra when you get a chance :)

**Comment by sakluger** [comment] 2024-06-11 14:37
If this is a deploy blocker from https://github.com/Expensify/App/issues/34894, should we have @abzokhattab take a look first?

**Comment by abzokhattab** [comment] 2024-06-11 15:07
let me know if you want me to work on it

**Comment by dangrous** [comment] 2024-06-11 15:55
@abzokhattab yeah if you can see if you can fix this one along with https://github.com/Expensify/App/issues/43243 that would be great!

**Comment by greg-schroeder** [comment] 2024-06-28 09:20
Added @eVoloshchak per above comment

**Comment by greg-schroeder** [comment] 2024-06-28 09:21
PR is in review still - does this need internal approval?

**Comment by dangrous** [comment] 2024-07-08 08:50
I can grab this one @MonilBhavsar since it's a regression from one of mine

**Comment by greg-schroeder** [comment] 2024-07-16 22:08
PR pending one final review from @eVoloshchak

**Comment by dangrous** [comment] 2024-07-18 14:27
PR is merged! We should get the bot here soon to start the final payment/close process

**Comment by greg-schroeder** [comment] 2024-07-22 11:50
closing per above

**Closed** 2024-07-22 11:49 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
