### ISSUE TITLE
Workspace - Error on Employee workspace chat when Admin remove it from workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34545] opened 2024-01-15 22:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login as Admin
2. Navigate to Workspace> invite members page
3. Invite user B
4. Remove user B
5. Login as user B
6. Navigate to the workspace chat

## Expected Result:
Workspace chat should be archived and there should no be error messages

## Actual Result:
"Policy does not exist or you do not have access. Try refreshing the page." error message appears on Employee workspace chat when Admin remove it from Workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/17707c93-8685-4271-a15f-3c6e5662db9e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cead22** [comment] 2024-01-15 22:34
@lanitochka17 can you check what API call triggered the error? And just to confirm, this can't be reproduced in production?

**Comment by cead22** [comment] 2024-01-16 00:19
Per discussion in this thread https://expensify.slack.com/archives/C01GTK53T8Q/p1705364273810119?thread_ts=1705357942.034469&cid=C01GTK53T8Q, I'm going to close this and open a deploy blocker issue in E/E since this seems to be a backend problem

**Closed by cead22** 2024-01-16 00:19 UTC
Labels: Engineering, Daily
