### ISSUE TITLE
Duplicate Messages appearing in compose box after message sent (then app closed soon after)

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11293] opened 2022-09-26 19:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sent message
2. Immediately quit NewDot after
3. Opened NewDot next morn and see a draft message for the one sent yesterday

## Expected Result:
No duplicated messages should appear 

## Actual Result:
Multiple messages appear in the conversation  

Related issues: 
https://github.com/Expensify/App/issues/10615 
https://github.com/Expensify/App/issues/10550

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

<img width="337" alt="image - 2022-09-26T155043 972" src="https://user-images.githubusercontent.com/43995119/192367035-25151f30-85bc-49a4-ab26-925836bba511.png">
[duplicates at startup.txt](https://github.com/Expensify/App/files/9649237/duplicates.at.startup.txt)
[scroll to make duplicate message.txt](https://github.com/Expensify/App/files/9649238/scroll.to.make.duplicate.message.txt)

https://user-images.githubusercontent.com/43995119/192367043-56fb3a0e-cff1-4cac-a367-5de4a9ad344c.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663776833139009?thread_ts=1663714013.290919&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-09-26 20:57
Surely we have already logged this somewhere...? It's the same bug that will be fixed by `sequenceNumber` deprecation which @roryabraham is writing the detailed portion for now.

**Comment by mallenexpensify** [comment] 2022-09-27 00:21
What's different for this, or what I hadn't experienced is the duplicate is in the compose box. Updated title 
> [HOLD Sequence #] Duplicate Messages appearing in compose box after message sent (then app closed soon after)

https://github.com/Expensify/Expensify/issues/227234

I'd assign to myself to _monitor_ or test once the time is right but I'm OOO for a month soon

**Comment by Christinadobrzyn** [comment] 2022-10-20 05:07
Since this is on hold until https://github.com/Expensify/Expensify/issues/227234 is resolved, going to move this to weekly

**Comment by aldo-expensify** [comment] 2022-10-26 22:02
This is probably the same thing, but I can consistently reproduce it with the following steps:

1. Send the following message in a chat:
`
This is the list of domains that I'm explicitly ignoring in the Firm MRR query: 'aol.com', 'att.net', 'bellsouth.net', 'bills.expensify.com', 'expensify.cash', 'btinternet.com', 'cheerful.com', 'chromeexpensify.com', 'comcast.net', 'cox.net', 'evernote.user', 'expensify.sms', 'gmail.com', 'gmail.con', 'googlemail.com', 'hey.com', 'hotmail.co.uk', 'hotmail.com', 'hotmail.fr', 'hotmail.it', 'icloud.com', 'live.com', 'mac.com', 'mail.ru', 'me.com', 'msn.com', 'outlook.com', 'privaterelay.appleid.com', 'qq.com', 'sasktel.net', 'sbcglobal.net', 'verizon.net', 'yahoo.ca', 'yahoo.co.in', 'yahoo.co.uk', 'yahoo.com.br', 'yahoo.com', 'ymail.com', 'expensifail.com' 
`
2. Click on a different chat
3. Click on the chat where you sent the first message on step 1.
4. You should see it repeating

Weirdly this doesn't happen to me with any message, but with this specific content it does.

**Comment by Christinadobrzyn** [comment] 2022-11-02 03:26
I can replicate that in staging. 

1. Open a chat in [staging](https://staging.new.expensify.com/r/68947221)
2. Copy & paste `This is the list of domains that I'm explicitly ignoring in the Firm MRR query: 'aol.com', 'att.net', 'bellsouth.net', 'bills.expensify.com', 'expensify.cash', 'btinternet.com', 'cheerful.com', 'chromeexpensify.com', 'comcast.net', 'cox.net', 'evernote.user', 'expensify.sms', 'gmail.com', 'gmail.con', 'googlemail.com', 'hey.com', 'hotmail.co.uk', 'hotmail.com', 'hotmail.fr', 'hotmail.it', 'icloud.com', 'live.com', 'mac.com', 'mail.ru', 'me.com', 'msn.com', 'outlook.com', 'privaterelay.appleid.com', 'qq.com', 'sasktel.net', 'sbcglobal.net', 'verizon.net', 'yahoo.ca', 'yahoo.co.in', 'yahoo.co.uk', 'yahoo.com.br', 'yahoo.com', 'ymail.com', 'expensifail.com'` 
3. Go to a different chat
4. Go back to the original chat and you can see the message dupe

![2022-11-02_11-11-40 (1)](https://user-images.githubusercontent.com/51066321/199386885-bdf79522-7726-41de-a5de-af49f729c991.gif)

So should this stay on hold for this? https://github.com/Expensify/Expensify/issues/227234

I'm not really sure what to do here...

**Comment by mallenexpensify** [comment] 2022-11-02 20:32
Yeah.. I'd recommend keeping it on hold pending #227234 in E/E.  It'll be addressed there.  As far as the BZ role here.. I'd stay on top of the tracking issue and, if progress isn't being made, ping the folks assigned there.

**Comment by Christinadobrzyn** [comment] 2022-11-11 07:44
Still on hold waiting for - https://github.com/Expensify/Expensify/issues/227234

**Comment by Christinadobrzyn** [comment] 2022-11-21 08:27
Stil tracking https://github.com/Expensify/Expensify/issues/227234

**Comment by Christinadobrzyn** [comment] 2022-11-29 07:03
Stil tracking https://github.com/Expensify/Expensify/issues/227234

**Comment by JmillsExpensify** [comment] 2022-12-01 18:42
Just came across this one. I'm taking over since I'm on the linked Sequence Numbers doc.

**Comment by JmillsExpensify** [comment] 2022-12-05 13:41
Still on hold for sequence numbers, which is starting to pick up the pace.

**Comment by JmillsExpensify** [comment] 2022-12-27 20:13
Same same, though we're making great progress.

**Comment by JmillsExpensify** [comment] 2023-01-11 05:48
Still on hold for the navigation project.

**Comment by JmillsExpensify** [comment] 2023-02-02 15:47
Unable to reproduce this one now. Closing.

**Closed by JmillsExpensify** 2023-02-02 15:47 UTC
Labels: Monthly, Bug

**Comment by mallenexpensify** [comment] 2023-02-03 00:13
This issue used to happen to me frequently, not able to reproduce on two tries either!
