### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] Can click on the space on the right to change the default skin tone

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#28917] opened 2023-10-05 13:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Send a message
3. Hover on message and click add reaction
4. Hover on space on the right of "change the default skin tone", Observe clickable
## Expected Result: 
Can not click on space on the right of "change the default skin tone"
## Actual Result: 
Can click on space on the right of "change the default skin tone"
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/e8517601-7846-4c54-b8f0-18d771fa2cab

https://github.com/Expensify/App/assets/38435837/4d5200d0-9cd7-40ee-a671-646087d9ac85

https://github.com/Expensify/App/assets/38435837/0355ffe9-8913-4106-9bc8-fa2c7ebc48a0

https://github.com/Expensify/App/assets/38435837/430fde74-c3cd-41b9-907c-40c3bacd683f

https://github.com/Expensify/App/assets/38435837/065aaff6-1560-4cba-aec2-76e569775a48

https://github.com/Expensify/App/assets/38435837/2f5ed479-8dd7-4ab0-8d3e-117c8410c7c2

https://github.com/Expensify/App/assets/38435837/1346c888-b734-46c1-aaad-346193dfcf63

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696424388503359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da9a465c887f2507</li>
        <li>Upwork Job ID: 1709929828423364608</li>
        <li>Last Price Increase: 2023-10-05</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Contributor | 27095403</li>
<li>namhihi237 | Reporter | 27095405</li>
</ul></li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment] 2023-10-05 13:53
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Able to click on the space on the right to 'change the default skin tone'
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/a07bb1537063122b481722573c382f4a42fc9a22/src/components/EmojiPicker/EmojiSkinToneList.js#L47-L57
styles.flex1 is causing the issue to occupy all the space available.
### What changes do you think we should make in order to solve the problem?
Remove styles.flex1 from and add styles.ml4 to the <Text component where 'emojiPicker.skinTonePickerLabel' is there.
Solution would look something like this.
Tested and works fine in all platform
```javascript
  <PressableWithoutFeedback
          onPress={toggleIsSkinToneListVisible}
          style={[styles.flexRow, styles.alignSelfCenter, styles.justifyContentStart, styles.alignItemsCenter]}
          accessibilityLabel={props.translate('emojiPicker.skinTonePickerLabel')}
          accessibilityRole={CONST.ACCESSIBILITY_ROLE.BUTTON}
    >
          <View style={[styles.emojiItem, styles.justifyContentCenter]}>
                 <Text style={[styles.emojiText, styles.ph2, styles.textNoWrap]}>{currentSkinTone.code}</Text>
          </View>
          <Text style={[styles.emojiSkinToneTitle,styles.ml4]}>{props.translate('emojiPicker.skinTonePickerLabel')}</Text>
  </PressableWithoutFeedback>
``` 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by m-natarajan** [comment] 2023-10-05 13:54
## Proposal by @namhihi237 
### Please re-state the problem that we are trying to solve in this issue.
 We want to fix can not click on the space on the right of "change the default skin tone"
### What is the root cause of that problem?
We are having `PressableWithoutFeedback` wrap icon and text. it is taking up the entire width.
https://github.com/Expensify/App/blob/24aa7c12c269796008f6a96ae153fbd8ced5b43b/src/components/EmojiPicker/EmojiSkinToneList.js#L47-L57
### What changes do you think we should make in order to solve the problem?
We should remove flex1 in `Pressable Without Feedback` so that it no longer takes up the entire width
```js
<PressableWithoutFeedback
    style={[styles.flexRow, styles.alignSelfCenter, styles.justifyContentStart, styles.alignItemsCenter]}
>
       <View style={[styles.emojiItem, styles.justifyContentCenter, styles.mh2]}>
            <Text style={[styles.emojiText]}>{currentSkinTone.code}</Text>
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by Pujan92** [comment] 2023-10-05 14:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
An entire row of the skin tone is pressable

### What is the root cause of that problem?
We have given flex1 for the Pressable which will take available width.
https://github.com/Expensify/App/blob/76c971b1430df7ddbfe2ce4a80c400ab4e9d1fd6/src/components/EmojiPicker/EmojiSkinToneList.js#L49

### What changes do you think we should make in order to solve the problem?
We need to make below changes

1) Remove flex1 style from the Pressable

2) Add `styles.wAuto` to the wrapper `View` of the currentSkinTone
https://github.com/Expensify/App/blob/76c971b1430df7ddbfe2ce4a80c400ab4e9d1fd6/src/components/EmojiPicker/EmojiSkinToneList.js#L53

Why? bcoz style class `emojiItem` contains prop `width: 12.5%` and if we take out flex1 from parent then the width gets reduced and this 12.5% width won't be sufficient for the currentSkinTone. So with `styles.wAuto` it will override the width and take the required width.

3) Remove width 100% from the `emojiSkinToneTitle` otherwise it overflows and creates an issue for native.
https://github.com/Expensify/App/blob/76c971b1430df7ddbfe2ce4a80c400ab4e9d1fd6/src/components/EmojiPicker/EmojiSkinToneList.js#L56C47-L56C47
https://github.com/Expensify/App/blob/76c971b1430df7ddbfe2ce4a80c400ab4e9d1fd6/src/styles/styles.js#L1745-L1746

**Comment by Pujan92** [comment] 2023-10-10 13:53
@allroundexperts [PR](https://github.com/Expensify/App/pull/29177) is ready for review!

**Comment by MariaHCD** [comment] 2023-10-23 12:07
Look good to me. Although I just realized we don't have a BZ member on this issue? 😕

**Comment by MariaHCD** [comment] 2023-10-23 12:08
@MitchExpensify The PR has already been merged and deployed, we just need the payments to go out here. Thanks!

**Comment by JmillsExpensify** [comment] 2023-10-23 16:34
Need a payment summary for this issue.

**Comment by MitchExpensify** [comment] 2023-10-24 19:26
**Payment summary:**

- $750 @Pujan92 requires payment [offer](https://www.upwork.com/nx/wm/offer/27095403) (Contributor)
- $750 @allroundexperts does not require payment (Eligible for Manual Requests)
- 50 @namhihi237 requires payment [offer](https://www.upwork.com/nx/wm/offer/27095405) (Reporter)

**Comment by JmillsExpensify** [comment] 2023-10-24 19:31
$750 payment approved for @allroundexperts based on comment above.

**Comment by MitchExpensify** [comment] 2023-10-24 19:35
All paid in Upwork

**Closed by MitchExpensify** 2023-10-24 19:35 UTC
Labels: External, Daily, Awaiting Payment, Bug
