### ISSUE TITLE
[HOLD for payment 2024-08-19] Expensify Card empty state list cuts off centered modal

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#46648] opened 2024-08-01 10:43 UTC
When your screen is at a shorter size, the centered modal portion of the empty state list is cut off:

https://github.com/user-attachments/assets/37802418-1145-4fc2-9f63-2fea2b070e6c

cc @filip-solecki as we discussed in [Slack](https://expensify.slack.com/archives/C04878MDF34/p1722506420355389) 

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by shawnborton** [comment] 2024-08-01 10:44
@isabelastisser we're going to have @filip-solecki from SWM take this one.

**Comment by filip-solecki** [comment] 2024-08-01 11:09
PR is ready for review! @shawnborton

**Comment by isabelastisser** [comment] 2024-08-19 18:19
> If all contributors are agency contributors and/or not paid via NewDot or Upwork, no payment summary post is necessary.

**Comment by isabelastisser** [comment] 2024-08-19 18:20
@francoisl, do we need a regression test?

**Comment by francoisl** [comment] 2024-08-19 20:53
I would say no, this was more of a style improvement for a relatively new feature.

**Comment by isabelastisser** [comment] 2024-08-19 20:54
Thanks, Franc! Closing this.

**Closed by isabelastisser** 2024-08-19 20:54 UTC
Labels: Daily, Awaiting Payment, Bug

**Comment by ikevin127** [comment] 2024-08-20 18:30
@isabelastisser I just checked Upwork and looks like I wasn't paid for [reviewing](https://github.com/Expensify/App/pull/46649#issuecomment-2264221008) the PR for this issue.

> Skipping the payment summary for this issue since all the assignees are employees or vendors. If this is incorrect, please manually add the payment summary [SO](https://stackoverflowteams.com/c/expensify/questions/17778).

This ^ https://github.com/Expensify/App/issues/46648#issuecomment-2297132224 seems to be incorrect.

**Comment by isabelastisser** [comment] 2024-08-21 11:57
Hi @ikevin127, I apologize for the oversight! Thanks for linking the review here. I will process the payment in Upwork now.

**Comment by ikevin127** [comment] 2024-08-21 16:10
@isabelastisser No worries, I accepted the offer. Thank you!
