### ISSUE TITLE
[$250] Workspace - Long loading and errors after a new non USD WS offline and adding a bank account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41431] opened 2024-05-01 17:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4529975&group_by=cases:section_id&group_id=283225&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: Your default workspace currency shouldn't be USD
1. Log in with a new expensifail account
2. Go offline
3. Create a workspace
4. Enable Workflows in the WS settings
5. Go online
6. Start adding a bank account
7. Click on "Update to USD"

## Expected Result:
The loading shouldn't take long and there shouldn't be any errors while adding a bank account

## Actual Result:
After clicking on "Connect bank account", the loading takes up to 15 seconds or sometimes it's infinite. "Hmm it's not here" error appears briefly when it loads and the user clicks somewhere to close the "Connect bank account" modal. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d9291ee1-a600-4b9e-9788-125f3c266d90

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177c40c7be0407379</li>
        <li>Upwork Job ID: 1788976368546947072</li>
        <li>Last Price Increase: 2024-07-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment] 2024-05-01 17:30
@AndrewGable  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-01 17:31
We think that this bug might be related to #wave-collect - Release 1

**Comment by francoisl** [comment] 2024-05-01 22:03
I'm also seeing a delay on production, I think it's just because there are a bunch of sequential API requests to finish before the view can be shown (also there's some crazy flickering, looks like it's due to rerenders; but that's unrelated)

https://github.com/Expensify/App/assets/2229301/8f159d93-bade-4b13-9c15-e08cd307f7af

**Comment by AndrewGable** [comment] 2024-05-01 22:43
Agree with @francoisl if it's on production let's look at it like a normal bug.

**Comment by nkdengineer** [comment] 2024-05-10 17:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After clicking on "Connect bank account", the loading takes up to 15 seconds or sometimes it's infinite. "Hmm it's not here" error appears briefly when it loads and the user clicks somewhere to close the "Connect bank account" modal.

### What is the root cause of that problem?
When we create a workspace and enable a feature offline, the policy data is updated optimistically

https://github.com/Expensify/App/blob/52d4f31aeb9436ee009f862ec9bbde134cad84b8/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L91

1. After we go online, `CreateWorkspace` API is called first and it takes more time to complete and other APIs need to wait it before these API are called. That why the long loading occur.

2. About the not found page appears briefly, the RCA is `CreateWorkspace` API returns this feature is disabled it overrides the `optimisticData` when we enable the feature in offline. And then after `CreateWorkspace` API is complete, the enable feature API is called and the page appears again.
### What changes do you think we should make in order to solve the problem?
1. For the long loading, it's not a bug because it simply means we have to wait for the API to be called.

2. For the not found page appears briefly, when we enable feature in offline, we should add an extra field with format like `${featureName}Optimistic` as `true` in `optimisticData` of policy

Example for enable workflow we will update `areWorkflowsEnabledOptimistic` as `enable` in `optimisticData` and we will reset as `false` in `successData` and `failureData`


https://github.com/Expensify/App/blob/52d4f31aeb9436ee009f862ec9bbde134cad84b8/src/libs/actions/Policy.ts#L4373


And then in `isPolicyFeatureEnabled` we will return `true` if the featureName field or featureName optimistic field of `policy` is `true`

```
if (featureName === CONST.POLICY.MORE_FEATURES.ARE_TAXES_ENABLED) {
    return Boolean(policy?.tax?.trackingEnabled || policy?.tax?.`trackingEnabledOptimistic`);
}

return Boolean(policy?.[featureName] || policy?.[`${featureName}Optimistically`]);
```
https://github.com/Expensify/App/blob/52d4f31aeb9436ee009f862ec9bbde134cad84b8/src/libs/PolicyUtils.ts#L319
### What alternative solutions did you explore? (Optional)
NA

**Comment by JmillsExpensify** [comment] 2024-05-15 03:18
@hoangzinh thoughts on the proposal above?

**Comment by nkdengineer** [comment] 2024-05-17 00:49
@hoangzinh both `CreateWorkspace` and `EnableWorkflow` API are write API.

**Comment by nkdengineer** [comment] 2024-05-17 04:47
@hoangzinh Thanks for your information, I updated the RCA and solution https://github.com/Expensify/App/issues/41431#issuecomment-2105015885

**Comment by nkdengineer** [comment] 2024-05-21 09:08
>  Can you point me to the LOC where the queue is paused before we call EnablePolicyWorkflows API.?

@hoangzinh when we create a new workspace, we are missing some updates on our local storage and then the queue is pause here.

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/actions/OnyxUpdates.ts#L121-L130

**Comment by nkdengineer** [comment] 2024-05-24 16:10
> @nkdengineer Actually I realize that there 2 are times that it makes SequentialQueue pause. And the time related to our bug seems the OpenReimbursementAccountPage API

@hoangzinh Thanks for your feedback, the not found page still appears even we don't click on `Connect bank account` which makes `OpenReimbursementAccountPage` is called.

> Moreover, your solution might cause a regression where the network is offline, we won't trigger resolveIsReadyPromise?.()

For that, we can add the check offline to trigger`resolveIsReadyPromise?.()`

```
if (NetworkStore.isOffline() || PersistedRequests.getAll().length === 0) {
    resolveIsReadyPromise?.();
}
```

**Comment by nkdengineer** [comment] 2024-05-28 09:27
@hoangzinh I tested and sometimes the `PusherEvent` happens before `CreateWorkspace`, sometimes it happens after `CreateWorkspace`. I think it's based on backend and network. So summary of the issue's RCA is a `PusherEvent` comes between `CreateWorkspace` and `EnablePolicyWorkflows` API makes the queue is paused and then a read API is called before `EnablePolicyWorkflows` API which overrides the policy data. What do you think?

**Comment by nkdengineer** [comment] 2024-05-29 06:47
@hoangzinh Thanks for your feedback, I checked again, the queue is paused after `CreateWorkspace` API is called and before `CreateWorkspace` is complete. But the queue is unpaused after `CreateWorkspace` API is complete which makes `resolveIsReadyPromise` is resolved after `CreateWorkspace` API is complete and then the read API is called immediately

https://github.com/Expensify/App/blob/ff7ba40d79871079666ef26cd0f22706d4882bb8/src/libs/Network/SequentialQueue.ts#L132

https://github.com/Expensify/App/blob/ff7ba40d79871079666ef26cd0f22706d4882bb8/src/libs/actions/OnyxUpdateManager/index.ts#L144

<img width="1512" alt="Screenshot 2024-05-29 at 13 34 14" src="https://github.com/Expensify/App/assets/161821005/dd926411-6960-45e8-90a9-cb835e8a552a">

**Comment by mvtglobally** [comment] 2024-06-05 21:22
Issue not reproducible during KI retests. (First week)

**Comment by wildan-m** [comment] 2024-06-11 23:02
@hoangzinh I can't reproduce it anymore, seems we can close it

**Comment by JmillsExpensify** [comment] 2024-06-19 21:51
Asked QA to test again.

**Comment by kavimuru** [comment] 2024-06-20 13:23
Tester is still able to reproduce. 

https://github.com/Expensify/App/assets/43996225/7a842bd5-c5bd-49b4-b2ca-0847c956a53e

**Comment by JmillsExpensify** [comment] 2024-06-26 03:58
QA is able to reproduce so keeping this open.

**Comment by mvtglobally** [comment] 2024-07-03 14:33
Issue not reproducible during KI retests. (Second week)

**Comment by JmillsExpensify** [comment] 2024-07-09 23:46
Given that QA can no longer reproduce, and others have seen the same, I'm closing this issue.

**Closed by JmillsExpensify** 2024-07-09 23:46 UTC
Labels: External, Engineering, Weekly, Help Wanted, Overdue, Bug
