### ISSUE TITLE
[$1000] Web - Sidebar re-arrange on moving to report from split group

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23905] opened 2023-07-31 01:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Split a bill
2. Add 3 users
3. Create the bill
4. Observe the sidebar
5. Click on the bill in the split group
6. Click on any profile in split with section in the sidebar
7. Select message [name]
8. Observer the pattern
9. You can repeat from step 5 for other users

## Expected Result:
When clicking on any report, it's position in LHN should not change until data has been added to the compose box.  

## Actual Result:
The reports in LHN changes it's indexes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/88d3a3e0-2931-44e7-b395-5e6f521ec8c1

https://github.com/Expensify/App/assets/93399543/eabdaf38-c31a-4015-be63-8f1f3b61be50

**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690663983822269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01005e4b179e77b28f</li>
        <li>Upwork Job ID: 1694361641774350336</li>
        <li>Last Price Increase: 2023-08-23</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-07-31 05:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Problem was that when opening a chat from a slit bill's details the chat changes its order in the LHN list.

### What is the root cause of that problem?
- `lastVisibleActionCreated` Property of th chat is only updated when its openend. And opening can also be done when pressing on the Chat from LHN or as per shown in the video from Split Bill details.
- We are updating `lastVisibleActionCreated` of Split Bill Report's but not the User's Report.

### What changes do you think we should make in order to solve the problem?
- We need to update `lastVisibleActionCreated` to the created time of split bill reportAction for the `Split With` users report's.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by mallenexpensify** [comment] 2023-08-10 04:38
Was off for few days and swamped with a project deadline, will get to this soon

**Comment by mallenexpensify** [comment] 2023-08-23 14:50
> The reports in LHN should not change its position on moving to someone's profile.
@Krishna2323 efore I updated the expected behaviour to be more broad.  
> When clicking on any report, it's position in LHN should not change until data has been added to the compose box.  

1. I wonder why this is specifically happening with reports from split bills
2. I wonder if it's happening anywhere else.

**Comment by mallenexpensify** [comment] 2023-08-23 14:51
Removed/readded the `Bug` label to hopefully reset the timer since I didn't address this for weeks and I don't think it needs to be/go internal

**Comment by abdulrahuman5196** [comment] 2023-08-28 12:08
This only became external couple of days back. This shouldn't be internal ideally. But anyways will review the only proposal we have and update.

**Comment by mallenexpensify** [comment] 2023-09-04 23:57
@abdulrahuman5196 , please review @jeet-dhandha 's proposal when you have a minute
https://github.com/Expensify/App/issues/23905#issuecomment-1657598424

**Comment by mallenexpensify** [comment] 2023-09-05 02:24
@MitchExpensify  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by MitchExpensify** [comment] 2023-09-05 11:55
Can do @mallenexpensify

**Comment by mallenexpensify** [comment] 2023-09-11 06:32
@abdulrahuman5196 , please review @jeet-dhandha 's proposal when you have a minute
https://github.com/Expensify/App/issues/23905#issuecomment-1657598424

Thanks @MitchExpensify for 👀

**Comment by jeet-dhandha** [comment] 2023-09-13 04:20
I will get back by tomorrow. As i also forgot what the solution was as its been more than 1.5 month.

**Comment by abdulrahuman5196** [comment] 2023-09-15 17:26
We are not having any more proposals to review. @jeet-dhandha needs to update proposal

**Comment by jeet-dhandha** [comment] 2023-09-18 05:10
Proposal Updated https://github.com/Expensify/App/issues/23905#issuecomment-1657598424.

**Comment by mallenexpensify** [comment] 2023-09-19 05:58
Thanks.   @abdulrahuman5196 , can you review @jeet-dhandha 's updated proposal above?

**Comment by mallenexpensify** [comment] 2023-09-26 07:51
Reassigning C+ due to inactivity
@parasharrajat please review https://github.com/Expensify/App/issues/23905#issuecomment-1657598424

**Comment by jeet-dhandha** [comment] 2023-09-26 18:45
I will need some time to create a full proposal as all the time related implementation is a bit hard to understand so trying to figure out the best way to handle this. 👍

**Comment by jeet-dhandha** [comment] 2023-09-26 19:17
<img width="373" alt="Screenshot 2023-09-27 at 12 42 34 AM" src="https://github.com/Expensify/App/assets/78416198/b462f506-70d5-4172-a2d4-f36c6e15c2e3">


- I have user 201 (Logged In User), 202 and 203.
- Now i created group with 202 and 203. 
- Now i added a split bill. 

How should all the chats be `ordered` after the `split bill` is `created` and rest IOU Reports or Chat Reports are created or updated?

**Comment by pecanoro** [comment] 2023-09-27 03:40
Hmmm I think this might be on purpose since they get ordered from last seen, but I will check.

**Comment by jeet-dhandha** [comment] 2023-09-27 03:42
https://github.com/Expensify/App/assets/78416198/db43fcdc-889e-4ee8-99ff-584d7a98609e


Also the timestamp is updated from backend instead of using the sent `lastVisibleActionCreated`.

**Comment by pecanoro** [comment] 2023-09-27 04:05
I don't see any bugs here, I think this is working just fine. @mallenexpensify Do you have anything against closing this one?

**Comment by jeet-dhandha** [comment] 2023-09-27 04:07
@pecanoro The above video is after the fix i added for incremental “lastVisibleActionCreated”.

**Comment by jeet-dhandha** [comment] 2023-09-27 04:08
As we need incremental timestamp and also we need to stop updating “lastReadTime” to current time as its making Reports marked as read instead of showing in “bold”

**Comment by pecanoro** [comment] 2023-09-27 04:24
> As we need incremental timestamp and also we need to stop updating “lastReadTime” to current time as its making Reports marked as read instead of showing in “bold”

I see them bold unless I open them.

**Comment by jeet-dhandha** [comment] 2023-09-27 09:09
Please test same thing on “main” the IOU reports are not highlighted (gets bold).
- Also currently on main, IOU timestamp and Chat have same timestamp.

**Comment by pecanoro** [comment] 2023-09-28 06:47
> Also the timestamp is updated from backend instead of using the sent lastVisibleActionCreated.

I checked this, it should come from the back-end indeed.

**Comment by pecanoro** [comment] 2023-09-28 09:14
Ok, I think this is working as expected after checking with others, so I am going to close it.

**Closed by pecanoro** 2023-09-28 09:14 UTC
Labels: Daily, Internal, Bug
