### ISSUE TITLE
[$500] Chat – Edited text is out of the frame

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32846] opened 2023-12-11 17:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account.
3. Navigate to any chat conversation.
4. Enter several lines of text until a scroller is visible
5. Send message
6. Click on edit this message
7. Wright more text using letters q, g, y

## Expected Result:
Edited text is not out of the frame

## Actual Result:
Edited text is out of the frame

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1fb8a6e2-f0a2-41c7-9277-3794f8659a8f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114350bc651a8e598</li>
        <li>Upwork Job ID: 1734270946190327808</li>
        <li>Last Price Increase: 2023-12-25</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment] 2023-12-11 19:02
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

Chat – Edited text is out of the frame

## What is the root cause of that problem?

The main problem is that when we add a new line, the padding we use above and below the input is ignored

https://github.com/Expensify/App/blob/d8f32684270cbc8ad4a6f557bfe87b3ea362ccec/src/styles/utils/index.ts#L897-L913

As a result, the text is focused at the bottom of the text
But since some letters are higher than others
The bottom part is next to the border

## What changes do you think we should make in order to solve the problem?

I think that in this case we should not use padding, and instead we can use margin, so that the indentation we use at the bottom is more obvious

So we can update this function like (I kept the padding as it is part of other fixes (But more testing is needed here to make sure that the margin is suitable for previous fixes) :

```
function getComposeTextAreaPadding(numberOfLines: number, isComposerFullSize: boolean): ViewStyle {
    // Issue #26222: If isComposerFullSize paddingValue will always be 5 to prevent padding jumps when adding multiple lines.
    if (!isComposerFullSize) {
        if (numberOfLines === 1) {
            return {
                paddingTop: 9,
                paddingBottom: 9,
            };
        }
        // In case numberOfLines = 3, there will be a Expand Icon appearing at the top left, so it has to be recalculated so that the textArea can be full height
        if (numberOfLines === 3) {
            return {
                paddingTop: 8,
                paddingBottom: 8,
            };
        }
    }
    return {
        marginTop: 5,
        marginBottom: 5,
    };
}
```

## What alternative solutions did you explore? (Optional)
NA

**Comment by botosdavid** [comment] 2023-12-11 21:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem is that when we write new lines the padding on the bottom is no longer visible, the text "exits" its frame.
### What is the root cause of that problem?
So if we pay close attention, in the first few lines this problem is not happening, but after we add multiple lines so that the input has a scrollbar, we can see that we are not scrolled fully to the bottom of the input. We are just in the vision of the cursor, but we can scroll down a couple of pixels. 
### What changes do you think we should make in order to solve the problem?
We just need to scroll all the way down whenever we are writing on the end of the text (when our cursor is at the end). 

https://github.com/Expensify/App/assets/88627050/97b884ab-8bd4-4243-af64-663ce8a656b7


### What alternative solutions did you explore? (Optional)
Alternatively we can check if we are on the last line of the input (not just at the last character).
```
  useEffect(() => {
        if (textInput.current) {
            const cursorPosition = textInput.current.selectionStart;
            // Scroll to the bottom only if on the last position
            if (cursorPosition === value.length) {
                textInput.current.scrollTop = textInput.current.scrollHeight;
            }
        }
      }, [value]);
```

**Comment by botosdavid** [comment] 2023-12-11 21:37
Contributor details
Your Expensify account email: davidbotos60@yahoo.ro
Upwork Profile Link: https://www.upwork.com/freelancers/~01d08bd0c2eb123bd2

**Comment by dragnoir** [comment] 2023-12-12 10:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

 Edited text is out of the frame at the bottom

### What is the root cause of that problem?

This is a browser issue, it doesn't use padding at the bottom on `textarea`.

### What changes do you think we should make in order to solve the problem?

Adding scroll-padding: 10px; to src/components/Composer/index.js style will fix the issue.

![image](https://github.com/Expensify/App/assets/12425932/4d10425c-2399-4188-81af-24bb1b78cea5)


### POC
![image](https://github.com/Expensify/App/assets/12425932/5dbf45c9-8190-4ab2-8bf6-aa5af72d3650)

**Comment by prafullvyas272** [comment] 2023-12-13 03:58
Contributor details
Your Expensify account email: prafullvyas272@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0114930272380f2d09

**Comment by laurenreidexpensify** [comment] 2023-12-14 11:20
@cubuspl42 bump for review ^^ thanks

**Comment by cubuspl42** [comment] 2023-12-14 12:16
@ZhenjaHorbach 

> But more testing is needed here to make sure that the margin is suitable for previous fixes

Unfortunately, this testing should be a part of a work on a proposal. You correctly observed that the code is crafted to solve a different issue, and it's especially easy to introduce a regression in such cases. We have to be confident that the proposal both solves our current issue and doesn't introduce regressions.

@botosdavid 

Are you suggesting any code changes in your "What changes do you think we should make in order to solve the problem?" section?

> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> 
> Edited text is out of the frame at the bottom
> ### What is the root cause of that problem?
> 
> This is a browser issue, it doesn't use padding at the bottom on `textarea`.
> ### What changes do you think we should make in order to solve the problem?
> 
> Adding `scroll-padding: 10px;` to src/components/Composer/index.js `style` will fix the issue.
> 
> ![image](https://private-user-images.githubusercontent.com/12425932/289827068-4d10425c-2399-4188-81af-24bb1b78cea5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTYwNTIsIm5iZiI6MTcwMjU1NTc1MiwicGF0aCI6Ii8xMjQyNTkzMi8yODk4MjcwNjgtNGQxMDQyNWMtMjM5OS00MTg4LTgxYWYtMjRiYjFiNzhjZWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEyMDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMGUzZTMzYzU2MWEyMzM0ZDkxYTc2NWM4M2U4YzI4Yzk4MDQ1NmU2NzIzNzlkYjM2YjI4MmFhNzgxYzUzMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pjR5ldqJcQ0eebh9yROonU2kt-BBNnU7QWXS9-AbJyo)
> ### POC
> 
> ![image](https://private-user-images.githubusercontent.com/12425932/289827021-5dbf45c9-8190-4ab2-8bf6-aa5af72d3650.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTYwNTIsIm5iZiI6MTcwMjU1NTc1MiwicGF0aCI6Ii8xMjQyNTkzMi8yODk4MjcwMjEtNWRiZjQ1YzktODE5MC00YWIyLThiZjYtYWE1YWY3MmQzNjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEyMDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYTk2NDk5ZWU1YjlkNTIzNWVkNjg1YzVmYTY3ZjdmODM2MzlhMzAwYzZkMmY1MjZhMWE1MzFlODkzMjBjNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-kurcjAhgS_wihADURTSxeZ9qYmKBGLCdbj5s_m2jNY)

@dragnoir 

Have you tested this change on Chrome and Safari, both desktop and mobile?

**Comment by botosdavid** [comment] 2023-12-14 23:45
> @ZhenjaHorbach
> 
> > But more testing is needed here to make sure that the margin is suitable for previous fixes
> 
> Unfortunately, this testing should be a part of a work on a proposal. You correctly observed that the code is crafted to solve a different issue, and it's especially easy to introduce a regression in such cases. We have to be confident that the proposal both solves our current issue and doesn't introduce regressions.
> 
> @botosdavid
> 
> Are you suggesting any code changes in your "What changes do you think we should make in order to solve the problem?" section?
> 
> @dragnoir
> 
> Have you tested this change on Chrome and Safari, both desktop and mobile?

Yes, I placed the code snippet in the alternative solutions section by mistake, but I was suggesting something like that to scroll down when needed, as the padding is there already, but only not visible because we are not scrolled down fully.

**Comment by dragnoir** [comment] 2023-12-15 09:59
Testing on other platforms ASAP

**Comment by dragnoir** [comment] 2023-12-15 13:27
The scroll-padding: 10px; is working only on Chrome (where I develop XD).

I  tested the `textarea` as native in enmpty project, on some other website and it seeùs it(s all like that, same bahavior.
Also when I zoom on the DEMO provided at the top by @kbecciv , the text is not out of the frame

==> Image from the video by kbecciv
![image](https://github.com/Expensify/App/assets/12425932/50836338-ffcf-42cd-8510-c02b4c3c354f)

==> screenshot from [Mozilla web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea)
![image](https://github.com/Expensify/App/assets/12425932/dbca562a-036d-42f7-9004-d53ceac80d37)

==> screenshot from [W3Schools](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea)
![image](https://github.com/Expensify/App/assets/12425932/30729340-de49-41fc-92ab-040b38a5b252)

**Comment by laurenreidexpensify** [comment] 2023-12-18 10:42
Waiting for proposals

**Comment by cubuspl42** [comment] 2023-12-18 11:38
@ZhenjaHorbach @dragnoir Please update the proposals so they represent the best, most actionable ideas of yours

@ZhenjaHorbach I'm confused about whether you consider your primary or alternative ideas more preferable. It might be partially a linguistic issue. Sometimes I'm not sure what you mean.

@dragnoir So is your proposal now outdated, as it doesn't work on Safari?

**Comment by dragnoir** [comment] 2023-12-19 16:50
@cubuspl42 if you can check the same flow on other websites, I can see the exact bahavior (near frame text). You can zoom the browser to see the small details. I assume it's **not a bug**.

Note: the video posted by the reporter, does not show out of the frame text, just no space between text and the frame.

**Comment by cubuspl42** [comment] 2023-12-20 12:35
@dragnoir

> I assume it's not a bug.

In the case of frontend Web apps, it's an everyday reality that some problems are considered a bugs even when they come from an issue in the browsers, a specific browser, or sometimes even the standard itself. Sometimes there are reasonable workarounds. 

Still, in this case, the impact seems to be quite small and all proposals so far have some gotchas. So I would agree to close this one.

@laurenreidexpensify Would you agree?

**Closed** 2023-12-29 09:52 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
