### ISSUE TITLE
[$500] Chat - Scroll bar appears in the suggestion list when only one emoji is in the suggestion list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31001] opened 2023-11-07 15:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to any chat
3. Type :+1

## Expected Result:
There is no scroll bar on the right of the list since there is only one emoji in the suggestion list

## Actual Result:
There is a scroll bar on the right of the list when only one emoji is in the suggestion list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3e2971b9-b2de-445d-9339-a3601c17d5bc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b10f4eb010b9828</li>
        <li>Upwork Job ID: 1721906785220390912</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by DrLoopFall** [comment] 2023-11-07 16:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - Scroll bar appears in the suggestion list when only one emoji is in the suggestion list

### What is the root cause of that problem?

We are calculating `rowHeight` inside `useEffect`, so when accessing the value for [`showsVerticalScrollIndicator`](https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js#L102) we are actually using the old value.

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js#L75-L76

### What changes do you think we should make in order to solve the problem?

Move `measureHeightOfSuggestionRows` outside the `useEffect` hook so that the calculated height would be in sync.

```diff
 
+const actualHeight = measureHeightOfSuggestionRows(props.suggestions.length, props.isSuggestionPickerLarge);
 useEffect(() => {
-    rowHeight.value = withTiming(measureHeightOfSuggestionRows(props.suggestions.length, props.isSuggestionPickerLarge), {
+    rowHeight.value = withTiming(actualHeight, {

  // in <FlatList
-        showsVerticalScrollIndicator={innerHeight > rowHeight.value}
+        showsVerticalScrollIndicator={innerHeight > actualHeight}
```

**Comment by garrettmknight** [comment] 2023-11-08 21:23
Unable to reproduce on v1.3.96-15 via chrome or  v1.3.95-9 MacOS. Closing - @lanitochka17 please reopen if you can get it to show.

**Comment by DrLoopFall** [comment] 2023-11-09 02:19
Hi @garrettmknight,
Can you please check again, this issue is very much reproducible in v1.3.95-9 and v1.3.97-1.
In MacOS the scrollbar is floating(hidden when not scrolling)  by default so you have to scroll on the suggestion list, to see the scrollbar, please check the screenshot below.

**MacOS**:
<img width="800" alt="Screenshot" src="https://github.com/Expensify/App/assets/120749263/80778faf-f477-43e6-9ee5-f1062b8ff191">

In other platforms where the scrollbar is non-floating by default, you can see it without scrolling.
<img width="800" alt="Screenshot" src="https://github.com/Expensify/App/assets/120749263/aba5668d-9e1f-4481-ae58-0cac05cef16e">

**Comment by DrLoopFall** [comment] 2023-11-09 02:30
@garrettmknight, Also when using mouse instead of trackpad the scrollbar will be visible by default, so it will be visible even without scrolling.
<img width="893" alt="Screenshot" src="https://github.com/Expensify/App/assets/120749263/ec03cb39-6928-441f-8631-b4f94b86f767">

**Comment by DrLoopFall** [comment] 2023-11-10 04:55
Hi @garrettmknight @lanitochka17,
Just a friendly bump, please have a look at this.

**Comment by lanitochka17** [comment] 2023-11-10 14:48
I am able to reproduce an issue in Windows10/Chrome
Build 1.3.97-7

![scroll](https://github.com/Expensify/App/assets/78819774/ea873c64-132c-4aee-a286-2ef05e1f2d26)

**Comment by brunovjk** [comment] 2023-11-10 20:12
I was also able to reproduce it.

**Comment by brunovjk** [comment] 2023-11-10 21:40
I am able to reproduce.

**Comment by brunovjk** [comment] 2023-11-10 21:50
I was also able to reproduce ithe issue.

@bernhardoj I can reproduce your solution, it solves the problem, however it seems that the emoji and the suggestion are not aligned, the emoji is not in the center I guess. Does it make sense or is it normal behavior? Thanks.

![image](https://github.com/Expensify/App/assets/95647348/4bbde678-ad8b-4efe-ad43-8ec73423c753)

**Comment by derekops333** [comment] 2023-11-11 23:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Redundant scroll bar appears in the suggestion list when only one emoji is in the list

### What is the root cause of that problem?
In the `<BaseAutoCompleteSuggestions />` component, the `showsVerticalScrollIndicator` prop of the `<FlatList />` is always set to **true**. It is the result of the `innerHeight` and `rowHeight.value` comparison. Unfortunately, nothing triggers component re-render once the `rowHeight.value` is calculated (since it is a ref, not the state). Because of that, component keeps it's initial look where the scroll bar is visible.

### What changes do you think we should make in order to solve the problem?
Even though we still need to keep `rowHeight` as a reference, as it is right now, we need to introduce a new state:
`const [rowHeightValue, setRowHeightValue] = useState(0); `

in the `useEffect` hook, where we call `withTiming` function, we should set a third parameter of the `withTiming` function - a callback in which we will set the new state value, once the calculation is finished.
Once the state is updated, a component re-render is triggered, and we can use a new state value for the `showsVerticalScrollIndicator` comparison

Solution Video:
[Screencast from 11.11.2023. 23:52:47.webm](https://github.com/Expensify/App/assets/150390681/d4935f1b-fc42-4121-bba1-36ad9bab545c)

**Comment by derekops333** [comment] 2023-11-11 23:22
Contributor details
Your Expensify account email: derekops333@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012e0374342e1c1946

**Comment by robertKozik** [comment] 2023-11-13 16:56
Sorry for the delay on my end. I'll go through the proposals asap 👀

**Comment by robertKozik** [comment] 2023-11-13 20:56
Hi all! Once more sorry for that delay on this issue 🙇🏼  After checking all proposals I believe we should go with the solution from @bernhardoj [proposal](https://github.com/Expensify/App/issues/31001#issuecomment-1798944588). It offers easy to implement fix which covers the issue. It's also the first proposal on github issue timeline which suggests this approach (edit of the proposal is just cosmetic, it adds the code diff section only)
I want also to address other proposals which I considered, and give proper explanation on my decision:
@DrLoopFall - I've tried your solution based on proposal, what I've experienced was that the container was still scrollable - just without the visible indicator. Also perfectly I would avoid hoisting the calculations to the component function due to performance reasons
@derekops333 - I prefer to avoid introducing another state variable while we have other viable solutions without it

🎀 👀 🎀 C+ reviewed

**Comment by DrLoopFall** [comment] 2023-11-13 21:36
Hi @robertKozik,

I've tried @bernhardoj's [proposal](https://github.com/Expensify/App/issues/31001#issuecomment-1798944588), it has an issue, it causes the scrollbar to be visible while the suggestion list is animating, check the video below, where the scrollbar flashes for a quick second.

https://github.com/Expensify/App/assets/120749263/cb30d80c-073a-47b9-aecf-78e520188465


## Regarding your concerns,

> I've experienced was that the container was still scrollable

I've also mentioned about fixing the `height` in my proposal, with an explanation of why just fixing the `height` won't solve the issue.

*From my proposal*
> If wanted we can also update the height [here](https://github.com/Expensify/App/blob/b5a0a746a82d64104c6d9400d86acc83a7d312a5/src/styles/StyleUtils.ts#L1001), but only updating the height would still show the scrollbar while animating, so we need to use the above solution.

---

> Also perfectly I would avoid hoisting the calculations to the component function due to performance reasons

The [`measureHeightOfSuggestionRows`](https://github.com/Expensify/App/blob/e87d35d8af177df33c4fdfbf221ead732efec310/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js#L16-L29) only consists of a few `if`'s and `*`'s, this won't cause any slowness, can you please check the implementation of  [`measureHeightOfSuggestionRows`](https://github.com/Expensify/App/blob/e87d35d8af177df33c4fdfbf221ead732efec310/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js#L16-L29).

**Comment by DrLoopFall** [comment] 2023-11-13 22:05
@robertKozik
As, I already said in my comments ([here](https://github.com/Expensify/App/issues/31001#issuecomment-1803067172) and [here](https://github.com/Expensify/App/issues/31001#issuecomment-1803067172)), if you're using MacOS without a mouse, the above-mentioned regression can be difficult to spot, it would be visible to all the users using other platforms or MacOS with a mouse.

To test it, you may try [enabling the scrollbar](https://www.macinstruct.com/tutorials/set-scroll-bars-to-always-display-on-your-mac/) while using a MacOS with a trackpad.

**Comment by DrLoopFall** [comment] 2023-11-14 08:44
@bernhardoj,
It actually doesn't make any sense, why would anyone need a scrollbar to be shown when the list height is animating, also it looks awfully worse and buggy when we have more items in the list, check this recording.

https://github.com/Expensify/App/assets/120749263/5d198deb-7089-419c-a4a2-1b4bc10d95a9

**Comment by DrLoopFall** [comment] 2023-11-14 08:44
Hi @robertKozik,

> I've experienced was that the container was still scrollable

The issue you mentioned above was not because of my solution, it was already present, if we fix the `height` it'll cause issue #18112 again because it looks like issue #18112 was fixed based on the extra scroll height, you can check this [video](https://user-images.githubusercontent.com/25520267/241794265-dda52bf1-db43-4f45-9465-0a552b9aed80.mov) which has the extra scroll height from PR #19621 which fixes the issue.

Also, implementing @bernhardoj's [proposal](https://github.com/Expensify/App/issues/31001#issuecomment-1798944588) will make the issue #18112 reappear again.

**Comment by robertKozik** [comment] 2023-11-14 08:59
Thanks for linking the issue, as it sheds a new light on our issue. Let me get more familiar with it first and I'lll get back here soon 😉  

I agree that your changes would marginally affect the performance. What I meant when writing the reasoning why I prefered other proposal over yours @DrLoopFall was that ideally I opt for omitting recalculating any value every render, if thats possible of course

**Comment by derekops333** [comment] 2023-11-14 12:20
> Thanks for linking the issue, as it sheds a new light on our issue. Let me get more familiar with it first and I'lll get back here soon 😉
> 
> I agree that your changes would marginally affect the performance. What I meant when writing the reasoning why I prefered other proposal over yours @DrLoopFall was that ideally I opt for omitting recalculating any value every render, if thats possible of course

Solution that was proposed by the @DrLoopFall is a common React **anti-pattern**. It calls an expensive calculation inside a render function which blocks rendering of the component content and decreases the app performances. 
My solution is the only one that calls expensive `withTiming` function the minimum amount of time, does not block content rendering and takes care that the component is re-rendered only once we have a new data (height) available

**Comment by DrLoopFall** [comment] 2023-11-14 14:21
@derekops333,
 Just have a look at this [comment](https://github.com/Expensify/App/issues/31001#issuecomment-1809166806).

> The [`measureHeightOfSuggestionRows`](https://github.com/Expensify/App/blob/e87d35d8af177df33c4fdfbf221ead732efec310/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js#L16-L29) only consists of a few `if`'s and `*`'s, this won't cause any slowness, can you please check the implementation of [`measureHeightOfSuggestionRows`](https://github.com/Expensify/App/blob/e87d35d8af177df33c4fdfbf221ead732efec310/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js#L16-L29).

For your reference, this is how `measureHeightOfSuggestionRows` is implemented.

```js
const measureHeightOfSuggestionRows = (numRows, isSuggestionPickerLarge) => {
    if (isSuggestionPickerLarge) {
        if (numRows > CONST_VARIABLE) {
            return CONST_VARIABLE * CONST_VARIABLE;
        }
        return numRows * CONST_VARIABLE;
    }
    if (numRows > 2) {
        return CONST_VARIABLE * CONST_VARIABLE;
    }
    return numRows * CONST_VARIABLE;
};
```

Do you even realize that your proposed solution is the most expensive among all the proposals here, because you literally proposed using `useState`, which would require additional rerenders running hundreds of lines of codes, making it at least a thousand times more expensive than calling a simple function.

Do you even have any idea, how much expensive is to rerender?

**Comment by derekops333** [comment] 2023-11-14 14:44
FlatList component (inside of the `BaseAutoCompleteSuggestions`) receives a prop  `showsVerticalScrollIndicator={innerHeight > rowHeight.value}` (at the moment). It **requires** re-render each time the row height is changed. My solution will cause re-rendering only when it is needed - when we have a new row height calculated. If you put  `measureHeightOfSuggestionRows` inside the render function, you will need to keep it outside of `withTiming` which then changes the already existing behavior and removes the animation effect

**Comment by DrLoopFall** [comment] 2023-11-14 15:22
@derekops333,
Please study the codebase thoroughly, currently the height is animated with `react-native-reanimated`, which won't rerender for the value changes, it directly animates the view, if you want you can check by a simple `console.log` in `BaseAutoCompleteSuggestions` component.

Currently, the component `BaseAutoCompleteSuggestions` is rendered only **once** to show the suggestion list, but your solution makes it render **twice**.

> If you put `measureHeightOfSuggestionRows` inside the render function, you will need to keep it outside of `withTiming` which then changes the already existing behavior and removes the animation effect

In my proposed solution the animation is working fine, check my [proposal](https://github.com/Expensify/App/issues/31001#issuecomment-1799131937) again for more details.

**Comment by lakchote** [comment] 2023-11-20 08:55
@robertKozik, after considering @DrLoopFall's comments about a possible regression, what do you think about the proposals, especially the one you initially chose?

**Comment by robertKozik** [comment] 2023-11-22 10:24
Thanks for pointing it out @0xmiroslav if this is a dupe, I think we should close this issue then as suggested above

**Comment by garrettmknight** [comment] 2023-11-24 14:05
Cool, closing!

**Closed by garrettmknight** 2023-11-24 14:05 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
