### ISSUE TITLE
LHN not showing any pinned chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27473] opened 2023-09-14 21:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app in web

## Expected Result:
All the chats pinned should be shown on the LHN
## Actual Result:
No pinned chats are showing, just a random 3 chats.   Have to open a chat by searching it won’t show on my LHN
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**
**Issue reported by:** @coleaeason 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694047827283259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment] 2023-09-15 12:53
I can't reproduce this at all - going to tag in engineering to see if we can take a look at Cole's logs to see what might have happened

**Comment by yuwenmemon** [comment] 2023-09-19 03:29
It appears this has been fixed (as it is working on staging now but still broken on prod). Closing this out!

**Closed by yuwenmemon** 2023-09-19 03:29 UTC
Labels: Engineering, Daily, Overdue, Bug
