### ISSUE TITLE
[$500] [MEDIUM] Scan Receipt - After edit a request while scanning, red dot disappears, scanning resumes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36930] opened 2024-02-20 17:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4327869
**Email or phone of affected tester (no customers):** stela.utest+29@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: There is workspace set up with 1 employee
1. Log in in the app as employee
2. Start the request money flow > "Scan" receipt as the employee
3. Upload a blurry receipt
4. Complete the money request flow
5. While the receipt is scanning - navigate to the request conversation
6. Click on the three dot overflow menu
7. Manually edit the merchant field
8. Leave the amount field showing an error
9. Navigate to the report conversation

## Expected Result:
“Scan in progress” message is no longer displayed, a red dot appears in the preview, in the LHN, the workspace chat has a red dot in LHN

## Actual Result:
After edit a request while the receipt is scanning, when navigating back to the workspace chat, the red dot disappears and scanning resumes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ff765b82-9f4b-4d85-af5c-4f17844d21c5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197730d9217c1aabc</li>
        <li>Upwork Job ID: 1759995216592060416</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-20 17:38
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by hayata-suenaga** [comment] 2024-02-20 18:32
asking [here](https://expensify.slack.com/archives/C03TQ48KC/p1708453645812169)
and [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1708453386918369)

**Comment by hayata-suenaga** [comment] 2024-02-20 23:50
https://github.com/Expensify/App/blob/ea0c07b7671bdcde20485c48f841212d7f1a925b/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L87

**Comment by hayata-suenaga** [comment] 2024-02-21 00:05
we can figure this out with contributors first to make sure that the error is coming from the backend

and then we can have wider discussion on what has recently been changed. I already brought the discussion to the Wave 6 Slack channel that is handling the Smart Scan.

By the way, this regression doesn't prevent the user from using the app. I'll remove the deploy blocker and change the priority to daily 🙇

**Comment by hayata-suenaga** [comment] 2024-02-23 22:36
[bumping](https://expensify.slack.com/archives/C02MW39LT9N/p1708727682540419?thread_ts=1708455074.074779&cid=C02MW39LT9N) in the slack

**Comment by jacobkim9881** [comment] 2024-02-26 09:16
I can not reproduce it.

**Comment by hayata-suenaga** [comment] 2024-02-26 15:29
requested the QA team to retest

**Comment by kbecciv** [comment] 2024-02-26 16:15
Issue is no longer reproducible

https://github.com/Expensify/App/assets/93399543/2f332a60-7995-40eb-8752-c6214e9c101d

**Comment by hayata-suenaga** [comment] 2024-02-26 16:32
The QA team confirmed that the issue is no longer reproducible. Closing this issue 🙇

**Closed by hayata-suenaga** 2024-02-26 16:32 UTC
Labels: External, Engineering, Daily, Help Wanted
