### ISSUE TITLE
"Make default payment method" option isn't showing up after you get error - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11348] opened 2022-09-27 17:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > Click on bank account
2. Click "Make default payment method"
3. Type wrong password > Enter
4. Tap on "Make default payment method" again

## Expected Result:
Make default payment method" option should be shown again

## Actual Result:
"Make default payment method" doesn't show up again

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** need PROD account
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screen Shot 2022-09-27 at 1 44 44 PM](https://user-images.githubusercontent.com/43995119/192599092-b341f7bf-7f17-42b6-96e9-35605bacdf08.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662753199634729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhairyasenjaliya** [comment] 2022-09-28 09:47
I think We Should close this issue in favor of https://github.com/Expensify/App/issues/10493#issuecomment-1229930529

**Comment by ctkochan22** [comment] 2022-10-20 20:29
I'm unable to reproduce. Can you specify reproduction steps? Or can you try again, and reopen if this issue is found again:
![pFSqbRRL7r](https://user-images.githubusercontent.com/12980144/197051506-eff5a856-5f5f-4b3d-8f8f-c7d31b11f6ac.gif)

**Closed by ctkochan22** 2022-10-20 20:29 UTC
Labels: Weekly, Bug
