### ISSUE TITLE
[$250] @hidden showing when changing the room description

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42156] opened 2024-05-14 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Christinadobrzyn 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715672936960819

## Action Performed:

1.  Go to staging.new.expensify.com and login
2.  Create a workspace
3.  Go to the default room of the new workspace
4.  Click on the room name
5.  Enter @[jkljlakjfajlkjafalkj@gmail.com](mailto:jkljlakjfajlkjafalkj@gmail.com) as the description

## Expected Result:
The email address should show instead of @hidden
## Actual Result:
set the room description to @hidden (the email in the description isn't being recongnised.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/46cb2fee-521a-41d6-96a3-196ff4db7781

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb91f2e18b75ab20</li>
        <li>Upwork Job ID: 1790451664333844480</li>
        <li>Last Price Increase: 2024-05-14</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2024-05-14 18:38
Weird one - I can replicate it - only if the @ symbol precedes the email address. This is very edge case-y to me on the surface, but, I think we should support any characters being added to the description

**Comment by rossnoah** [comment] 2024-05-14 20:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem is that mentions are detected and parsed in the channel description field, instead of treating them as just text.

### What is the root cause of that problem?
The cause of the problem is parsing the description instead of handling it as a plain text field.

### What changes do you think we should make in order to solve the problem?
We should skip parsing the description on both the loading of the of the input field and when submitting the form to state/server.

**Comment by rossnoah** [comment] 2024-05-14 20:25
Contributor details
Your Expensify account email: noahwross@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ac668c122395f990

**Comment by nexpensify** [comment] 2024-05-14 22:07
Contributor details
Your Expensify account email: noahwross@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ac668c122395f990

**Comment by nexpensify** [comment] 2024-05-14 22:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem is that mentions are detected and parsed in the channel description field, instead of treating them as just text.

### What is the root cause of that problem?
The cause of the problem is parsing the description instead of handling it as a plain text field.

### What changes do you think we should make in order to solve the problem?
We should skip parsing the description on both the loading of the of the input field and when submitting the form to state/server.

**Comment by hungvu193** [comment] 2024-05-16 03:07
I believe this is BE issue @adelekennedy 

<img width="1322" alt="Screenshot 2024-05-16 at 10 07 32" src="https://github.com/Expensify/App/assets/16502320/c4d2fa6b-4627-431a-adfe-05e711350575">

**Comment by nexpensify** [comment] 2024-05-16 11:19
Depends if you want to handle mentions in descriptions or if they should just be plain text. Parts of the UI already don't render the mention so I assumed that was the desired behavior .

**Comment by adelekennedy** [comment] 2024-05-21 21:53
this a polish IMO so taking this down to a weekly unless @hungvu193, I think it will take a while for an internal engineer to pick this up, what do you think of this [alternative option](https://github.com/Expensify/App/issues/42156#issuecomment-2114957778)

**Comment by nexpensify** [comment] 2024-05-21 21:55
just to be clear this can easily be handled on the client if you just treat it as text and ignore mentions (they don't show in this field in all parts of the UI anyway)

**Comment by nexpensify** [comment] 2024-05-22 01:19
something like this https://github.com/nexpensify/ExpensifyApp/tree/skip-parsing-channel-description

**Comment by hungvu193** [comment] 2024-05-22 01:20
Please update your proposal and explain about it instead. Thank you

**Comment by nexpensify** [comment] 2024-05-22 01:26
Heres a PR https://github.com/Expensify/App/pull/42446 if your interested. I'm not really interested in being paid so not signing the CLA.

**Comment by hungvu193** [comment] 2024-05-22 01:29
Please follow our [contributing guides here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job). You shouldn't create PR until you get assigned to the issue.
Also, your solution removed the markdown support of description field, that isn't what we're looking for.

**Comment by hungvu193** [comment] 2024-06-15 00:28
BE issue

**Closed** 2024-08-12 18:50 UTC
Labels: Reviewing, Monthly, Internal, Bug, Hot Pick
