### ISSUE TITLE
[LOW] [Splits] [$500] Email-The word "pay" is not centered on the button in Gmail app email notification

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39280] opened 2024-03-29 18:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4463509
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the App
2. Request money to an account that you have access to the email inbox
3. Do not read the message in NewDot to trigger the email notification
4. Open the email on the phone Gmail App (on Android)

## Expected Result:
The "Pay" word is centered on the green button

## Actual Result:
The "Pay" word is lower on the green button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6431860_1711733114300!pay_low](https://github.com/Expensify/App/assets/78819774/cd98942d-27ce-40b2-ac4f-6c1e7a54fe13)

![viber_image_2024-03-29_14-27-42-806](https://github.com/Expensify/App/assets/78819774/89aad264-4194-4287-91bd-1c90b19e8f93)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b2cce02f5267c57</li>
        <li>Upwork Job ID: 1775244742188765184</li>
        <li>Last Price Increase: 2024-04-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-29 18:36
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by garrettmknight** [comment] 2024-04-02 19:31
I had to bump up the display/text size, but I was able to reproduce.

**Comment by garrettmknight** [comment] 2024-04-02 19:32
Adding to split since it's an IOU issue that they'll encounter.

**Comment by akinwale** [comment] 2024-04-02 20:20
@garrettmknight This is happening in emails that are sent to the user, so it would require a backend fix.

**Comment by manjitsaha** [comment] 2024-04-03 02:21
**Proposal**

I think you are using 2 tags to build that button. One serves as a container and 2nd a text.  So, using the button will definitely keep the text in center.

If you are using button then tweaking with padding or line height will work.

**Comment by manjitsaha** [comment] 2024-04-03 02:29
Contributor details
Your Expensify account email: [manjitsaha01@gmail.com](mailto:manjitsaha01@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01ff7e928882ddd88c

**Comment by garrettmknight** [comment] 2024-04-03 10:59
@akinwale fair, I'll switch internal, but would this [solution](https://github.com/Expensify/App/issues/39280#issuecomment-2032990776) essentially be the change?

**Comment by akinwale** [comment] 2024-04-04 13:55
> @akinwale fair, I'll switch internal, but would this [solution](https://github.com/Expensify/App/issues/39280#issuecomment-2032990776) essentially be the change?

I don't think so, because regular contributors do not have access to the code that handles creating or generating the email templates.

**Comment by garrettmknight** [comment] 2024-04-08 18:28
Still awaiting a volunteer.

**Comment by garrettmknight** [comment] 2024-04-10 09:59
Dropping to weekly - we're calling for volunteers in slack.

**Comment by garrettmknight** [comment] 2024-04-19 08:46
Still awaiting internal volunteer

**Comment by garrettmknight** [comment] 2024-04-29 17:07
Still awaiting a volunteer

**Comment by garrettmknight** [comment] 2024-05-09 18:58
Still awaiting a volunteer

**Comment by garrettmknight** [comment] 2024-05-13 16:45
Still awaiting a volunteer

**Comment by garrettmknight** [comment] 2024-05-22 19:26
Still awaiting a volunteer

**Comment by mvtglobally** [comment] 2024-05-30 01:29
Issue not reproducible during KI retests. (First week)

**Comment by garrettmknight** [comment] 2024-05-30 14:27
Moving to daily to test.

**Comment by garrettmknight** [comment] 2024-06-03 18:59
Will test tomo.

**Comment by garrettmknight** [comment] 2024-06-05 19:40
Didn't get to test today - tomorrow!

**Comment by garrettmknight** [comment] 2024-06-06 11:41
<img width="449" alt="Screenshot 2024-06-06 at 12 40 38 PM" src="https://github.com/Expensify/App/assets/1529980/d0dd8c8c-9908-4e9b-b399-757fb137a844">
Fixed!

**Closed by garrettmknight** 2024-06-06 11:41 UTC
Labels: Daily, Internal, Bug, Hot Pick
