### ISSUE TITLE
Mark down - Link is not underlined, heading text is not bold

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54301] opened 2024-12-18 15:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.77-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.0 / Chrome
**App Component:** Chat Report View

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Send a link (google.com).
4. Send a heading markdown.

## Expected Result:
Link will be underlined.
Heading text will be bold.

## Actual Result:
Link is not underlined.
Heading text is not bold.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7597f25b-2621-47d4-81ff-d08126a5a2dc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment] 2024-12-18 16:33
I'm suspicious of the changes to react-native-render-html or react-native-live-markdown but haven't done any testing yet, will undertake that now.

**Comment by amyevans** [comment] 2024-12-18 17:01
Alright confirmed it's the react-native-render-html change.

PR: https://github.com/Expensify/App/pull/52917

**With PR merged to `main`, testing locally:**
<img width="472" alt="Screenshot 2024-12-18 at 11 47 23 AM" src="https://github.com/user-attachments/assets/b0cc5fac-c3ad-4252-9d17-0ef8df73cff8" />

After stopping the dev server and reverting the PR I did:
```
rm -rf node_modules/
npm i
npm run web
```

**With PR reverted, testing locally:**

<img width="322" alt="Screenshot 2024-12-18 at 11 56 27 AM" src="https://github.com/user-attachments/assets/62a1875c-9e0a-46c5-95c9-4ba833bf01a0" />

So I'll open a revert PR, I think that's the best thing to do to unblock deploy.

**Comment by amyevans** [comment] 2024-12-18 17:14
Updated revert PR since we had 2 open: https://github.com/Expensify/App/pull/54309

Once it's on staging I'll double check the issue is gone and close this out

**Comment by amyevans** [comment] 2024-12-18 20:14
PR has been CP'ed, and I verified the result in staging:

![Screenshot 2024-12-18 at 3 13 45 PM](https://github.com/user-attachments/assets/3fa1e557-f55c-4682-bba5-4de2d0a7cce6)

Closing!

**Closed by amyevans** 2024-12-18 20:14 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug
