### ISSUE TITLE
[HOLD for payment 2024-10-14] [$250] Sign in–Magic code expired appears briefly if use Request one here link & login via magic link

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47883] opened 2024-08-22 20:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4886771
**Email or phone of affected tester (no customers):** applausetester+jp_322824@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. On the log in screen, enter a new account email
3. Repeat the previous step with the same email - This is to receive 2 validation links
4. Navigate to the account email inbox and open the first email of the 2
5. Copy the magic link and change it to staging
6. Navigate to the staging link
7. Verify Magic code expired page opens
8. Click on Request one here link
9. Navigate to the account email inbox and open the email
10. Copy the magic link, change it to staging and navigate to the staging link

## Expected Result:
Magic code expired not appears briefly

## Actual Result:
Magic code expired appears briefly

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f7ee22c3-e45b-494e-b98a-5849acb48bb9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ba582e21228c322</li>
        <li>Upwork Job ID: 1828311848767754708</li>
        <li>Last Price Increase: 2024-09-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by IuliiaHerets** [comment] 2024-08-22 20:38
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Amoralchik** [comment] 2024-08-23 01:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The user sees the `ValidateCodeModal` instead of a loading screen when accessing the magic link.

### What is the root cause of that problem?
Here in ValidateLoginPage:
https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/pages/ValidateLoginPage/index.website.tsx#L77
This condition returns `true` even when `shouldStartSignInWithValidateCode` is `true`. This caused the `ValidateCodeModal` to be shown to the user.

### What changes do you think we should make in order to solve the problem?
By changing the condition to 
`!shouldStartSignInWithValidateCode && autoAuthState === CONST.AUTO_AUTH_STATE.NOT_STARTED && !exitTo` 
By this we can prevent the display  `ValidateCodeModal`, and we can display the Loading Indicator instead of the `ValidateCodeModal` including it in the condition for `FullScreenLoadingIndicator`. 
I suggest making the changes as follows:
```js
    // If session.autoAuthState isn't available yet, we use shouldStartSignInWithValidateCode to conditionally render the component instead of local autoAuthState which contains a default value of NOT_STARTED
    const shouldValidateModal = !shouldStartSignInWithValidateCode && autoAuthState === CONST.AUTO_AUTH_STATE.NOT_STARTED && !exitTo;
    const isFailed = autoAuthState === CONST.AUTO_AUTH_STATE.FAILED;
    const isJustSignedIn2FA = autoAuthState === CONST.AUTO_AUTH_STATE.JUST_SIGNED_IN && is2FARequired && !isSignedIn && login;
    const isJustSignedIn = autoAuthState === CONST.AUTO_AUTH_STATE.JUST_SIGNED_IN && isSignedIn && !exitTo && login;

    return (
        <>
            {isFailed && <ExpiredValidateCodeModal />}
            {isJustSignedIn2FA && <JustSignedInModal is2FARequired />}
            {isJustSignedIn && <JustSignedInModal is2FARequired={false} />}
            {shouldValidateModal && (
                <ValidateCodeModal
                    accountID={Number(accountID)}
                    code={validateCode}
                />
            )}
            {!shouldValidateModal && !isJustSignedIn && !isJustSignedIn2FA && <FullScreenLoadingIndicator />}
        </>
    );
```

**Comment by greg-schroeder** [comment] 2024-08-27 06:01
Looks like we have one proposal to review when you get a chance, Rajat!

**Comment by bernhardoj** [comment] 2024-08-27 09:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The magic code expired is shown briefly when open the magic link for the 2nd time.

### What is the root cause of that problem?
When we open the expired magic link for the first time, the `session.autoAuthState` is FAILED. When we reopen the 2nd magic link, the state is still the same, FAILED, so the magic code expired view is shown briefly.
https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/pages/ValidateLoginPage/index.website.tsx#L73

### What changes do you think we should make in order to solve the problem?

I suggest that we clear the `autoAuthState` when pressing the request one here text,
https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/components/ValidateCode/ExpiredValidateCodeModal.tsx#L38-L45

```
function clearAutoAuthState() {
    Onyx.merge(ONYXKEYS.SESSION, {autoAuthState: null});
}
...
onPress={() => {
    Session.clearAutoAuthState();
    ...
})
```

**Comment by greg-schroeder** [comment] 2024-09-05 19:08
Let me know how you go @parasharrajat!

**Comment by greg-schroeder** [comment] 2024-09-06 18:21
go away melvin

**Comment by bernhardoj** [comment] 2024-09-07 15:23
Hmm, I don't really understand about that. The issue we have here is the expired code is shown briefly,
https://github.com/Expensify/App/blob/7ebfaa0daaa43a20083250e0f263964ed5b647b2/src/pages/ValidateLoginPage/index.website.tsx#L73

but the suggestion is to change the condition of ValidateCodeModal.
https://github.com/Expensify/App/blob/7ebfaa0daaa43a20083250e0f263964ed5b647b2/src/pages/ValidateLoginPage/index.website.tsx#L77-L82

**Comment by Amoralchik** [comment] 2024-09-07 16:48
@parasharrajat I just tried to reproduce the issue, and most of the links were directed to `email.expensify.com`, which caused me to confuse the appearance of shouldValidateModal with this problem. My apologies.

**Comment by greg-schroeder** [comment] 2024-09-09 06:31
Awaiting contributor assignment!

**Comment by MonilBhavsar** [comment] 2024-09-11 00:28
makes sense 👍

**Comment by MonilBhavsar** [comment] 2024-09-11 22:06
The automation didn't work somehow. 
@bernhardoj let us know when can you have PR ready.

---

@greg-schroeder we'll need to make offers manually

**Comment by bernhardoj** [comment] 2024-09-12 06:05
Preparing the PR..

**Comment by bernhardoj** [comment] 2024-09-12 06:39
PR is ready

cc: @parasharrajat

**Comment by greg-schroeder** [comment] 2024-09-17 00:56
Next up is @MonilBhavsar on PR review!

**Comment by greg-schroeder** [comment] 2024-09-19 01:14
Monil requested some changes, so work continues here

**Comment by greg-schroeder** [comment] 2024-09-23 03:05
PR is still in review

**Comment by greg-schroeder** [comment] 2024-10-01 01:47
PR still needs a re-review it appears!

**Comment by fabioh8010** [comment] 2024-10-02 06:28
The [Onyx Bump PR](https://github.com/Expensify/App/pull/49857) was merged 🚀

**Comment by greg-schroeder** [comment] 2024-10-03 01:22
Thanks for the update @fabioh8010!

**Comment by greg-schroeder** [comment] 2024-10-08 21:21
Payment summary:

Contributor: @bernhardoj - $250 - Can make a manual request via ND to be paid on 10/11
C+: @parasharrajat - $250 - Can make a manual request via ND to be paid on 10/11

**Comment by bernhardoj** [comment] 2024-10-09 03:57
Requested in ND.

**Comment by greg-schroeder** [comment] 2024-10-11 18:22
Oops - regression period is actually 10/14 because the 10/11 date is for the Onyx bump PR, not the PR that fixes this. Updated

**Comment by greg-schroeder** [comment] 2024-10-14 21:41
All right, these manual requests can be approved per https://github.com/Expensify/App/issues/47883#issuecomment-2400844493

**Comment by greg-schroeder** [comment] 2024-10-14 21:42
Adding regression test, closing!

**Closed by greg-schroeder** 2024-10-14 21:42 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-10-15 11:46
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment] 2024-12-16 10:16
$250 approved for @parasharrajat
