### ISSUE TITLE
[$500] Workspace - In WS, primary contact is shown but if searched not directed to primary contact

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34923] opened 2024-01-22 20:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4211164
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap Profile icon--- Workspaces ---- Workspace
3. Tap members ---- Invite
4. Paste Number +84387025654
5. Tap invite
6. Note message shown " Some user added with their primary logins"
7. Note primary contact email id get added in members page
8. Navigate to LHN
9. Tap search
10. Paste Number +84387025654 and select the contact
11. Note the user is not directed to primary contact page

## Expected Result:
Inviting a number to WS, shows secondary contact and primary contact added in WS. Same user if searched, must be directed to primary contact

## Actual Result:
Inviting a number to WS, shows secondary contact and primary contact added in WS. Same user if searched, not directed to primary contact

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/efe2d3e9-f8de-4524-937d-2c6128b62b4e

https://github.com/Expensify/App/assets/78819774/681d4de7-d458-4cfa-9961-6b28e98712b2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016503aac971db6644</li>
        <li>Upwork Job ID: 1749523829555523584</li>
        <li>Last Price Increase: 2024-01-29</li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2024-01-22 21:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

**Backend**

![Screenshot 2024-01-23 at 00 18 27](https://github.com/Expensify/App/assets/22982173/2c7a8d30-cce6-4031-a26a-5d5a65e429ff)

The image above is the `personalDetails` for the account (+84387025654).

It seems the backend does not include the phone number as part of the account's `personalDetails` 

**Frontend**

https://github.com/Expensify/App/blob/f3111a472b72c475a89703fce4cdde4fdd75d42f/src/libs/OptionsListUtils.js#L254-L267

We don't search or match by phone numbers.

Hence it does not push the realistic `personalDetails` retrieved from the `InviteToRoom` response.

Therefere, it optimistically creates `personalDetails` to display the default search result.


### What changes do you think we should make in order to solve the problem?

From the backend, we should return the phone number in the `personalDetails` data as part of the `InviteToRoom` response.

Then from the front end, we should add the phone number as part of [`getParticipantNames`](https://github.com/Expensify/App/blob/f3111a472b72c475a89703fce4cdde4fdd75d42f/src/libs/OptionsListUtils.js#L254-L267)

**Comment by rushatgabhane** [comment] 2024-01-30 01:39
🎀 👀 🎀 
we need to send secondary login details from backend

**Comment by youssef-lr** [comment] 2024-02-01 19:39
I'm focusing on a high priority issue, will get to this tomorrow.

**Comment by youssef-lr** [comment] 2024-02-14 15:05
Investigating today. @kevinksullivan I think this fits in #vip-vsb?

**Comment by youssef-lr** [comment] 2024-02-22 01:00
I think this belongs in `vip-vsb`, so adding it to the project with LOW priority.

**Comment by kevinksullivan** [comment] 2024-03-01 05:17
Sorry @youssef-lr missed this, but yes I agree with it being in VSB.

**Comment by tgolen** [comment] 2024-03-07 22:11
I wasn't really able to reproduce this. When I tested this out, I searched for the phone number in the LHN. It showed a contact with the phone number, and when I clicked on it, it opened the chat with that user. After a brief second, once the chat had loaded, the details of the user updated and showed the primary login now.

I think that's totally acceptable for a UX so I am going to close this out.

**Closed by tgolen** 2024-03-07 22:11 UTC
Labels: Engineering, Daily, Internal, Bug, Hot Pick
