### ISSUE TITLE
[$250] LHN - After creating split expense and switching to another chat, LHN displays it as unread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52194] opened 2024-11-07 15:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Y
**Email or phone of affected tester (no customers):** applausetester+bm203@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a workspace and go to the workspace chat
3. Split an expense
4. Observe that half of the split expense appears below it
5. Go to another chat

## Expected Result:
The chat report in the LHN should not appear in bold, as the split expense has already been viewed

## Actual Result:
The chat report in the LHN appears in bold, even though the split expense was seen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/2fde62c4-6fb1-45e5-801c-f2c032a89c7f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856693414198783158</li>
        <li>Upwork Job ID: 1856693414198783158</li>
        <li>Last Price Increase: 2024-12-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by JmillsExpensify** [comment] 2024-11-13 13:39
While this is not a common flow, we have lots of issues with reports you just created showing unread in the LHN, so I'm going to open this up to the community to see if we have any creative solutions.

**Comment by ugogiordano** [comment] 2024-11-21 23:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After creating a split expense and then switching to another chat, the chat in the LHN is displayed as unread.

### What is the root cause of that problem?
The issue arises because the report is flagged as requiring attention from the user.

This is due to the `requiresAttentionFromCurrentUser` function returning true—indicating that the report contains a child expense still awaiting action from the current user. 

https://github.com/Expensify/App/blob/e04d145b607f768b36fb90b57fe57f40b536813d/src/components/LHNOptionsList/OptionRowLHN.tsx#L118
https://github.com/Expensify/App/blob/e04d145b607f768b36fb90b57fe57f40b536813d/src/libs/ReportUtils.ts#L2822-L2824


Specifically, the `getReasonAndReportActionThatRequiresAttention` function returns a non-empty `ReasonAndReportActionThatRequiresAttention` object, which signals that there is an unresolved action (such as a pending expense) requiring the user's attention.

https://github.com/Expensify/App/blob/e04d145b607f768b36fb90b57fe57f40b536813d/src/libs/ReportUtils.ts#L2740-L2743


This happens because the report’s `hasOutstandingChildRequest` is true, meaning the report has a child expense that is still pending action from the user. As a result, the condition evaluates to true, triggering the attention-required status, which ultimately causes the report to appear as unread in the LHN.

https://github.com/Expensify/App/blob/e04d145b607f768b36fb90b57fe57f40b536813d/src/libs/ReportUtils.ts#L2782-L2788

### What changes do you think we should make in order to solve the problem?

To fix this, when the report has an `hasOutstandingChildRequest`, we can add a check to see if the `isUnread` flag is `false`, like in the following snippet:

```typescript
    // Has a child report that is awaiting action (e.g. approve, pay, add bank account) from current user
    if (optionOrReport.hasOutstandingChildRequest && !!('isUnread' in optionOrReport && optionOrReport.isUnread)) {
        return {
            reason: CONST.REQUIRES_ATTENTION_REASONS.HAS_CHILD_REPORT_AWAITING_ACTION,
            reportAction: IOU.getIOUReportActionToApproveOrPay(optionOrReport, optionOrReport.reportID),
        };
    }
```

This ensures that the unread icon is not displayed if the user has already read the chat, even when there’s an outstanding expense awaiting action.

### What alternative solutions did you explore? (Optional)

None

**Comment by ugogiordano** [comment] 2024-11-29 22:43
@rayane-djouah  I can no longer see the bold text, but the green dot is still present, even in your video. As I understand it, both the bold text and the green dot should disappear once the user has read the chat.

**Comment by ugogiordano** [comment] 2024-12-02 22:21
> > I can no longer see the bold text, but the green dot is still present, even in your video. From what I understand, both the bold text and the green dot should disappear once the chat has been read.
> 
> I believe the presence of the green dot is designed to indicate when there's a pending action required from the user, such as a payment action in this scenario.
> 

So, I don’t see this issue anymore if the green dot is designed to stay there even after you have read the message.

> > (along with the '1' on the tab indicating an unread message)
> 
> The '1' on the tab in my video indicates an unread message in the concierge chat rather than the workspace report.
> 

I don’t see the bold text for the concierge chat, it could be something else.

> It appears that the issue with the bold text has been fixed. cc @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2024-12-05 10:32
Agreed, closing.

**Closed by JmillsExpensify** 2024-12-05 10:32 UTC
Labels: External, Daily, Help Wanted, Bug
