### ISSUE TITLE
[$250] Composer - Composer is not in focused when switching chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#43369] opened 2024-06-10 13:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** exploratory
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause internal team
**Slack conversation:** 

## Action Performed:

1. Go to staging.new.expensify.com/
2. Switch between chats

## Expected Result:
The composer will be in focused when switching chat

## Actual Result:
The composer is not in focused when switching chat

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/5d6c5978-bcb5-49ab-af95-3af483a90301

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec9e11187ff9476c</li>
        <li>Upwork Job ID: 1800166392783128752</li>
        <li>Last Price Increase: 2024-06-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by arosiclair** [comment] 2024-06-10 19:07
I reproduced on staging **v1.4.81-4**

**Comment by aneequeahmad** [comment] 2024-06-10 20:10
Commit no #9f7ea101a3 has introduced this bug when `useOnyx` is used instead of  `withOnyx`

**Comment by arosiclair** [comment] 2024-06-10 21:02
> Commit no #9f7ea101a3 has introduced this bug when `useOnyx` is used instead of `withOnyx`

This seems to be just a commit to merge main. I reverted the associated PR and it did not fix the issue.

I looked into several PR's and couldn't find the culprit. I also looked through the Composer component tree and didn't spot anything obvious. Logging off now but I'll continue looking into it tomorrow if needed.

**Comment by luacmartins** [comment] 2024-06-10 21:27
Fixed on staging. Closing

**Closed** 2024-06-10 21:27 UTC
Labels: External, Engineering, Hourly, Help Wanted, Bug

**Comment by AndrewGable** [comment] 2024-06-10 21:28
Fixed by https://github.com/Expensify/App/pull/43431

Discussed here: https://expensify.slack.com/archives/C01GTK53T8Q/p1718054675083139?thread_ts=1718054237.611609&cid=C01GTK53T8Q
