### ISSUE TITLE
[HOLD for payment 2023-09-27] [$1000] Clicking back button takes user to LHN instead of previous page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23758] opened 2023-07-27 20:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Open announce room
3. Click on header
4. Click on workspace name to go to workspace settings
5. Click on three dots > Go to admin room
6. Click on back button at the top left corner
7. Click on three dots > Go to announce room
8. Click on back button
## Expected Result: 
App should take user back to workspace settings page just as it does on step 6
## Actual Result: 
The app takes users back to the LHN if the user went to the workspace settings page through a specific room (let's say the "Admin Room") and then click the back button, it takes them directly to the LHN. Similarly, if users navigate to the workspace settings page from "Announce Room" header then went back to the announce room through the three dots menu and then click the back button, they are also redirected to the LHN. But if user came from the announce room header to the workspace settings > clicked three dots > then went to the admin room and clicked the back button the app takes user back to the workspace settings page.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b13a317e-1e6d-48fc-a235-5167d6aab68c

https://github.com/Expensify/App/assets/43996225/f9fdd0ea-6e49-4907-806d-46539a9fa229

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690441099091969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b545eb8a3cbf0e4</li>
        <li>Upwork Job ID: 1688659311957544960</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26489581</li>
<li>nathan-mulugeta | Reporter | 26489582</li>
</ul></li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-07-28 05:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app's current navigation behavior takes the user to the **Left Hand Navigation (LHN)** when the back button is clicked, after moving to a specific room from the workspace settings page. The expected behavior is to navigate the user back to the previous page, the workspace settings in this case.

### What is the root cause of that problem?
The React Navigation library, which we use for handling navigation in the app, navigates back to an existing screen if it already exists in the stack when an action of type **NAVIGATE** is fired. This behavior is inconsistent with our app's user flow in this instance, causing the user to be directed to the **LHN** instead of the workspace settings page.

https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/libs/Navigation/linkTo.js#L62-L76

### What changes do you think we should make in order to solve the problem?
To align the navigation behavior with the expected user flow, we can adjust how we handle **NAVIGATE** actions in our navigation actions handler. If none of the existing conditions (e.g., navigating to the report screen, deep linking into one of the RHP flows, etc.) are met and the action type is still **NAVIGATE**, we can set the action type to **PUSH**. This will ensure a new instance of the screen is added to the navigation stack, maintaining the user's navigational context.

Here's the adjusted part of the code:
```
// If action type is different than NAVIGATE we can't change it to the PUSH safely
if (action.type === 'NAVIGATE') {
    // If this action is navigating to the report screen and the top most navigator is different from the one we want to navigate - PUSH
    if (action.payload.name === NAVIGATORS.CENTRAL_PANE_NAVIGATOR && getTopmostReportId(root.getState()) !== getTopmostReportId(state)) {
        action.type = 'PUSH';

        // If the type is UP, we deeplinked into one of the RHP flows and we want to replace the current screen with the previous one in the flow
        // and at the same time we want the back button to go to the page we were before the deeplink
    } else if (type === 'UP') {
        action.type = 'REPLACE';

        // If this action is navigating to the RightModalNavigator and the last route on the root navigator is not RightModalNavigator then push
    } else if (action.payload.name === NAVIGATORS.RIGHT_MODAL_NAVIGATOR && _.last(root.getState().routes).name !== NAVIGATORS.RIGHT_MODAL_NAVIGATOR) {
        action.type = 'PUSH';
    } else {
        action.type="PUSH"
    }
}
```

By doing so, if the user navigates to a specific room from the workspace settings, with this proposed change, they will be navigated to a new instance of that specific room even if an instance of that room already exists in the navigation stack. When they press the back button, they will return to the workspace settings page, aligning the behavior with user expectations.

**Comment by muttmuure** [comment] 2023-08-01 17:46
Will look at this tomorrow

**Comment by muttmuure** [comment] 2023-08-07 21:11
I was able to reproduce this

**Comment by anmurali** [comment] 2023-08-09 22:12
I don't know why this is assigned to me and @muttmuure in BZ. I am unassigning myself.

**Comment by robertKozik** [comment] 2023-08-22 14:25
Sorry! Will take a look today!

**Comment by muttmuure** [comment] 2023-08-29 08:53
@mananjadhav there are a couple of proposals to look into: 

https://github.com/Expensify/App/issues/23758#issuecomment-1655111684

and

https://github.com/Expensify/App/issues/23758#issuecomment-1655070277

**Comment by b4s36t4** [comment] 2023-08-29 08:55
@muttmuure maybe dupe of #25393

**Comment by Nathan-Mulugeta** [comment] 2023-08-29 09:14
Hey @b4s36t4 if they do actually have the same RCA, the dupe one is [#25393](https://github.com/Expensify/App/issues/25393). That issue was posted on slack 12 days ago, but the current issue is posted on Jul 27th on slack.

**Comment by mananjadhav** [comment] 2023-08-30 19:37
Between both the proposals, @bernhardoj's [proposal](https://github.com/Expensify/App/issues/23758#issuecomment-1655111684) looks good to me.

🎀 👀 🎀 C+ reviewed.

**Comment by danieldoglas** [comment] 2023-09-04 13:40
Added contirbutor.

**Comment by b4s36t4** [comment] 2023-09-04 13:49
Guys I think after recent patches with the `react-navigation` this might be solved. Can anyone able produce this on prod or staging??

**Comment by danieldoglas** [comment] 2023-09-04 13:53
@Nathan-Mulugeta please hold on the PR while we test this again. @muttmuure @mananjadhav can you please check?

**Comment by danieldoglas** [comment] 2023-09-12 07:53
@kavimuru can you please confirm this still happens?

**Comment by Nathan-Mulugeta** [comment] 2023-09-12 11:15
Hey @danI just retested this and this is still and issue. I am able to reproduce it.

**Comment by danieldoglas** [comment] 2023-09-13 06:16
yeah, let's move on

**Comment by muttmuure** [comment] 2023-09-27 02:43
Regression period ends today

**Comment by danieldoglas** [comment] 2023-10-02 02:33
just waiting for payment

**Comment by mananjadhav** [comment] 2023-10-02 14:11
Based on our fix, I think the Navigation was working as expected, but we changed the expected behavior. I don't think we have an offending PR, but we should add regression test for this one. The QA Steps from the PR look good to me here. What do you think @danieldoglas?

@muttmuure Also can you please post a payout summary and do the payout for the contributors? I will be raising my request on NewDot.

**Comment by danieldoglas** [comment] 2023-10-02 17:05
> The QA Steps from the PR look good to me here. 
agreed

**Comment by mananjadhav** [comment] 2023-10-04 18:57
@muttmuure quick bump on the payout summary here.

**Comment by muttmuure** [comment] 2023-10-05 10:27
C+ @mananjadhav - $1500
C - @bernhardoj - $1500
Reporter - @Nathan-Mulugeta - $250

**Comment by JmillsExpensify** [comment] 2023-10-05 20:55
$1,500 payment approved for @mananjadhav based on BZ summary.

**Comment by mananjadhav** [comment] 2023-10-06 03:46
@muttmuure did we do the payout for @bernhardoj and @Nathan-Mulugeta? If yes then we are good to close this one out.

**Comment by Nathan-Mulugeta** [comment] 2023-10-06 05:23
Payment has not been processed yet.

**Comment by muttmuure** [comment] 2023-10-06 17:18
Everyone has been paid

**Closed by muttmuure** 2023-10-06 17:18 UTC
Labels: External, Daily, Awaiting Payment, Bug
