### ISSUE TITLE
[HOLD for payment 2024-05-06] [$250] Can't update the custom time of the status to 00:59

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40495] opened 2024-04-18 19:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713463886729749

## Action Performed:
1. Create a new status
2. Set up a custom clear time for a status to 00:59

## Expected Result: 
We should update successfully
## Actual Result: 
Error: Please choose a time at least one minute ahead

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/16851cb1-c4dc-44db-b618-379fd5fc6a58

https://github.com/Expensify/App/assets/38435837/f608b851-b74d-4257-8afc-5a4212df019c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0187eaa0221ed74ecf</li>
        <li>Upwork Job ID: 1781292572093497344</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2024-04-18 19:16
@garrettmknight I investigated this bug while discovering it. Could I take over this one as C+ role?

**Comment by DylanDylann** [comment] 2024-04-19 00:42
@Krishna2323 PLEASE PRIORITIZING YOUR PR BEFORE POSTING NEW PROPOSAL

**Comment by nkdengineer** [comment] 2024-04-19 06:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error: Please choose a time at least one minute ahead

### What is the root cause of that problem?
We have 2 problems:
1. The value of the hour field is not accepted if it is `0`

https://github.com/Expensify/App/blob/68e69623a8bca0dce5f384fa351d5cbb2214aeb4/src/libs/DateUtils.ts#L672-L674

2. `parse` function of `date-fns` lib return `invalid date` if the hour is 0 because the range of this format in `date-fns` is `1->12`, they use 12 instead of 0

### What changes do you think we should make in order to solve the problem?
For the problem 1, I see this condition is redundant, we should remove it
https://github.com/Expensify/App/blob/68e69623a8bca0dce5f384fa351d5cbb2214aeb4/src/libs/DateUtils.ts#L672-L674

For the problem 2, I suggest we should update the hour to 12 if it is 0 to match the range of `date-fns`
### What alternative solutions did you explore? (Optional)
NA

**Comment by shawnborton** [comment] 2024-04-19 12:00
Given that we are clearing using AM/PM here, I would think we'd just throw an error saying that you can't enter "00" for the hour.

**Comment by shawnborton** [comment] 2024-04-19 12:01
So I think we just need a better error message.

**Comment by shmaxey** [comment] 2024-04-19 16:40
Maybe,

> Please enter a time using the 12-hour clock format (e.g., 2:30 PM).

**Comment by nkdengineer** [comment] 2024-04-21 15:47
@garrettmknight @shmaxey 

Let's see the current behavior when entering the hour


https://github.com/Expensify/App/assets/161821005/d3b05740-62db-43c4-9a8a-3cdf1bb3baff

If entering 13, It will turn into 01
If entering 14, It will turn into 02 

What do you think if entering 00, it will turn into 12 ?


cc @DylanDylann

**Comment by DylanDylann** [comment] 2024-04-22 09:34
One more option, If entering 00 we still display 00 but in our code, we will turn it into 12 to handle logic

**Comment by shawnborton** [comment] 2024-04-22 13:04
Yup, I agree with Garrett.

**Comment by arosiclair** [comment] 2024-04-23 17:40
@ShridharGoel there's no RCA in your proposal. @nkdengineer's proposal LGTM

**Comment by nkdengineer** [comment] 2024-04-24 09:53
@DylanDylann  we have open PR [here](https://github.com/Expensify/App/pull/40853)
Currently we have an error in en.ts like this
`invalidTimeRange: Please enter a time using the 12-hour clock format (e.g., 2:30 PM).`
and I have defined in es.ts like this:
`invalidTimeRange: 'Introduzca una hora utilizando el formato de reloj de 12 horas (por ejemplo, 2:30PM).',`
Please confirm again @arosiclair @garrettmknight

**Comment by arosiclair** [comment] 2024-04-24 14:16
@garrettmknight I can ask in `#espanol-translations` for a translation, but should we ask for english copy first?

**Comment by garrettmknight** [comment] 2024-04-24 14:40
Thanks! Here's [the english copy](https://github.com/Expensify/App/issues/40495#issuecomment-2066924619) from @shmaxey

**Comment by garrettmknight** [comment] 2024-05-09 18:51
All paid out - @DylanDylann can you complete the checklist when you get a chance?

**Comment by DylanDylann** [comment] 2024-05-10 02:59
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/24620
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/24620#discussion_r1596195724
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Create a new status
2. Set up a custom clear time for a status to 00:59
3. Verify that: error Please enter a time using the 12-hour clock format is displayed


Do we agree 👍 or 👎

**Comment by garrettmknight** [comment] 2024-05-10 17:35
All set

**Closed by garrettmknight** 2024-05-10 17:35 UTC
Labels: External, Daily, Awaiting Payment, Bug
