### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] `ping` and `ReconnectApp` are called back to back on a bad wifi network

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44269] opened 2024-06-24 15:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar
**Slack conversation:**  https://expensify.slack.com/archives/C05LX9D6E07/p1719023935665339

## Action Performed:
1. Be on a bad WiFi network
2. Open the app

## Expected Result:
Shouldn't call `ping` and `reconnectApp` several times

## Actual Result:
 on a really bad wifi network, where it concludes it's online but for some reason can't contact the server, it just hammers `Ping `and `ReconnectApp` back to back, filling the network queue with tons of parallel unfinished commands.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (16)](https://github.com/Expensify/App/assets/38435837/b4272aaf-df25-4860-8eca-8699e5dc6c11)

[bugd.txt](https://github.com/user-attachments/files/15957638/bugd.txt)

![image (17)](https://github.com/Expensify/App/assets/38435837/f9040300-cfe2-470b-9239-58d360b6fb02)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f591c76409c7f4d0</li>
        <li>Upwork Job ID: 1805714893198480172</li>
        <li>Last Price Increase: 2024-06-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by srikarparsi** [comment] 2024-06-25 21:29
Making this external to see if there's a reliable way to reproduce, the root cause, and proposals to fix.

**Comment by quinthar** [comment] 2024-06-26 22:49
This feels extremely easy to reproduce: just close your laptop lid for a few minutes, and reopen.

**Comment by srikarparsi** [comment] 2024-06-27 00:31
I just tried this (closing laptop and reopen) and this was my network tab:
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/48188732/06ebc445-f369-42c4-8205-ef34c0425279">

2 pings were called which isn't as many as your [screenshot here](https://expensify.slack.com/archives/C05LX9D6E07/p1719024212756699?thread_ts=1719023935.665339&cid=C05LX9D6E07) but it's still back to back pings which shouldn't happen.

We already have a [check](https://github.com/Expensify/App/blob/6ea15ed1b1515ddd832e8b1bae93bc86a7cb15e3/src/libs/NetworkConnection.ts#L194) to make sure that we don't send a Ping command when one is pending and this seems to be working because I don't see `[NetworkConnection] recheck NetInfo` in the console.

I have two theories:

1. The component is being re-rendered and the state of isOffline or hasPendingNetworkStatus is getting reset? So NetInfo is calling Ping again. I don't really think it's the cause but I think these should be wrapped in a useRef since it'll remain for the lifetime of the component?
2. We don't set or check for hasPendingNetworkCheck inside of NetInfo so there could be duplicate calls being made there. I think it's more likely this one where isOffline is being set to false so NetInfo checks again but so does [recheckNetworkConnection](https://github.com/Expensify/App/blob/050641a6451e75d13723e46062086e3db3c2ad35/src/libs/NetworkConnection.ts#L154) since hasPendingNetworkCheck isn't set by NetInfo.

I'm still looking into these but these are my initial thoughts based on the code. cc @roryabraham and @adhorodyski if you have any additional thoughts since you guys worked on these PRs to [introduce NetInfo](https://github.com/Expensify/App/pull/19133) and [periodic checks](https://github.com/Expensify/App/pull/43090).

**Comment by adhorodyski** [comment] 2024-06-27 09:28
@srikarparsi you're correct about the periodic check. 

The call itself feels solid, as it should bail out if only the function early return kicks in (which from the logs looks fine, no subsequent `recheck NetInfo`). 

If `hasPendingNetworkCheck` is reliable, this periodic check should cause us no harm (but that's an assumption).

**Comment by adhorodyski** [comment] 2024-06-27 09:31
On higher-level problem I see with this implementation is that's it's really, really imperative so it's easy to make a mistake and cause such a behaviour over time. Declarative APIs work better especially with React codebases and there are open source libraries to solve just that.

**Comment by srikarparsi** [comment] 2024-06-27 18:53
I created this [PR](https://github.com/Expensify/App/pull/44565) to check if a network check is pending before starting a new one. Still need to test but I think this would be a quick way to stop repetitive calls. @adhorodyski if you could take a look at it as well that would be appreciated.

I also agree that our current implementation might not be the best way of doing it. NetInfo has parameters that we seem to be implementing in a custom way. For example, NetInfo already has reachabilityShortTimeout and reachabilityLongTimeout which are defaulted to 5s and 60s. So when the internet is not detected, it should be rechecking for connection every 5s. And when it is detected, it should be rechecking every 60s. But we had to re-add the 60s check in this [PR](https://github.com/Expensify/App/pull/43090) so I think there might just be something wrong with our current implementation which we need to fix.

**Comment by OlimpiaZurek** [comment] 2024-06-28 10:43
I wasn’t able to reproduce this issue by closing and opening the laptop lid.  Every time I tried, the `Ping` and `ReconnectApp` methods were only called once. 
However, based on the code and description provided, it appears that the problem is related to the way the app handles network checks and reconnections. When an app determines that it is online but cannot connect to the server, it initiates multiple `Ping` and `ReconnectApp` requests simultaneously. This leads to high amounts of network traffic and unfinished commands.   Reconnect logic does not control or limit the number of reconnect attempts. This can be problematic in environments with poor network conditions, leading to a constant flood of network activity.

Given this, I think adding this additional [check](https://github.com/Expensify/App/pull/44565) makes sense as it ensures that a new network check only starts if there isn't already one in progress.

**Comment by OlimpiaZurek** [comment] 2024-07-02 14:49
The change from this [PR](https://github.com/Expensify/App/pull/44565) seems to cause regression.

Overall, I agree with Adam that we should adopt a more declarative approach to handling network connections. Currently, we are using an imperative approach, which seems error-prone.  For example, the `recheckNetworkConnection` function is used both as [middleware ](https://github.com/Expensify/App/blob/6ea15ed1b1515ddd832e8b1bae93bc86a7cb15e3/src/libs/Middleware/RecheckConnection.ts#L21)and in an[ interval](https://github.com/Expensify/App/blob/6ea15ed1b1515ddd832e8b1bae93bc86a7cb15e3/src/libs/NetworkConnection.ts#L154), leading to risk of potential errors and multiple calls. 

NetInfo provides built-in functions for re-checking the connection, such as `reachabilityShortTimeout`, which runs every 5 seconds if the Internet is not detected, and `reachabilityLongTimeout`, which runs every 60 seconds when the Internet is connected. These built-in mechanisms are designed to handle network rechecks reliably.

Given the complexity of our custom implementation, it's challenging to determine if the root cause of this issue is due to NetInfo or our custom logic. Therefore, maybe we should consider removing the custom `recheckNetworkConnection` solution and relying solely on NetInfo's built-in functionality?  This approach simplifies our codebase and leverages the library's tested and optimized features.

To ensure this change meets our needs, I’d suggest to double-check that it provides the required functionality.

Given the difficulty in reproducing the issue, I believe we should conduct thorough testing to ensure that NetInfo's built-in mechanisms handle all necessary scenarios and edge cases. 

To achieve this, we need to confirm which specific functionalities we want to test and verify.

Here are some examples: 

* Detection of online and offline states.
* Handling intermittent connectivity and redundant checks.
* Managing and processing sequential queues.

**Comment by srikarparsi** [comment] 2024-07-02 20:11
> Therefore, maybe we should consider removing the custom recheckNetworkConnection solution and relying solely on NetInfo's built-in functionality?

I agree with this. And if it doesn't work and we verify that it's not a problem with our implementation, then I think it's better to make the fix upstream in NetInfo.

I think this should be the first step so I'll close this [PR](https://github.com/Expensify/App/pull/44565). @OlimpiaZurek let me know if I can do anything to help you with this.

**Comment by OlimpiaZurek** [comment] 2024-07-05 13:40
I prepared a [PR](https://github.com/Expensify/App/pull/44901) to remove `hasPendingNetworkCheck` flag.

I also prepared [PR](https://github.com/react-native-netinfo/react-native-netinfo/pull/732) with the fix to the NetInfo library.

**Comment by muttmuure** [comment] 2024-07-05 15:13
Thanks for the update!

**Comment by rushatgabhane** [comment] 2024-07-23 01:10
1. The PR that introduced the bug has been identified. Link to the PR: N.A. This was always there

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N.A.

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. Yes!

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

                1. Go offline
                2. Go to network tab in browser
                3. Verify that `openApp` isn't repeatedly called

**Comment by kadiealexander** [comment] 2024-07-24 05:44
Payouts due:

- [ ] Contributor+: $250 @rushatgabhane via NewDot.

**Closed** 2024-07-24 05:44 UTC
Labels: External, Daily, Awaiting Payment, Bug, AutoAssignerNewDotQuality

**Comment by muttmuure** [comment] 2024-07-24 10:36
Woohoo! Great work

**Comment by JmillsExpensify** [comment] 2024-07-26 02:16
$250 approved for @rushatgabhane

**Comment by OlimpiaZurek** [comment] 2024-09-24 07:44
I have prepared a [PR](https://github.com/Expensify/App/pull/49631) with updated code from` react-native-netinfo`.

It is worth noting that this change has been approved and merged by the maintainer. But since we are patching this library instead of forking it, it needs to be updated as above.
