### ISSUE TITLE
[HOLD for payment 2023-09-27] [$1000] "Hm... it's not here" message displays for a moment when viewing deleted money request that has sub-thread

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#25698] opened 2023-08-22 15:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to Account A.
2. Send a money request to another account.
3. Open the "IOU preview" >>> then click to view details.
4. Edit the amount and click Save.
5. Return to the "IOU preview" >> a sub-thread will be created after step # 4.
6. Hover over the "IOU Preview" and select the "Delete request" option.
7. Click on the request to open the sub-thread >> Leave Thread.
8. On the LHN: reopen that thread.
9. Observer: A "Hm... it's not here" message displays for a moment.

## Expected Result:
We shouldn't allow the person who submitted the request to "leave thread" on their transactions, so that option shouldn't be available. 

## Actual Result:
"Hm... it's not here" message displays for a moment
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/068f7139-72d1-4519-acfc-ca44e9dde97f

https://github.com/Expensify/App/assets/38435837/f9a5c427-991f-45a0-af36-95c2d0a09db5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692707688922459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143a231695978749a</li>
        <li>Upwork Job ID: 1694426496996868096</li>
        <li>Last Price Increase: 2023-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26455595</li>
<li>b4s36t4 | Contributor | 26455597</li>
<li>tranvantoan-qn | Reporter | 26455598</li>
</ul></li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-08-22 18:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hm... it's not here" message displays for a moment when viewing deleted money request that has sub-thread
### What is the root cause of that problem?
THis bug introduced after #23394 this PR.

Before this PR we have a state `isReportRemoved` which makes the report to not render `FullPageNotFoundView`.

After we leave the thread API result `null` as the value for deleted reportID in which we have `{}` in onyxDB.

here https://github.com/Expensify/App/blob/aa98b6bcd1d71f47afee043673c7c18a337b8959/src/pages/home/ReportScreen.js#L295

in this line this snippet gets `!this.props.report.reportID && !this.props.report.isLoadingReportActions && !isLoading` to true because `this.props.report` is empty object `{}` which resulting `FullPageNotFoundView` to be `true`.

### What changes do you think we should make in order to solve the problem?

We add a can check for empty report means the we have removed the report from the our reports.

#### Updated

```jsx
!_.isEmpty(this.props.report) && !this.props.report.reportID && !this.props.report.isLoadingReportActions && !isLoading`
```

would render the loading screen.




### What alternative solutions did you explore? (Optional)
NA

https://github.com/Expensify/App/assets/59088937/9f47a1ce-b58d-4dc1-aebe-38b3a23e515c

**Comment by trjExpensify** [comment] 2023-08-22 23:47
Hm, I'm not sure why that option only appears when the request is in the `[Deleted request]` state to preserve the comment history only. Why don't we simply not allow the person who submitted the request to "leave thread"? CC: @luacmartins

**Comment by trjExpensify** [comment] 2023-08-22 23:47
FWIW, if this is the root cause it was deployed to production a week ago so this issue can't be a deploy blocker. 

>What is the root cause of that problem?
>THis bug introduced after https://github.com/Expensify/App/pull/23394 this PR.

**Comment by luacmartins** [comment] 2023-08-22 23:56
>Why don't we simply not allow the person who submitted the request to "leave thread"

I think this should be the correct behavior. Users shouldn't be able to leave the transaction thread.

**Comment by trjExpensify** [comment] 2023-08-23 00:05
Cool, let's fix it in that way then! 

I could reproduce this on staging, but not on prod, so that RCA above is likely not accurate. Either way, I don't think this should hold up the deploy. Would you agree with that?

**Comment by b4s36t4** [comment] 2023-08-23 01:12
@trjExpensify the issue happens with normal thread too. Not just transaction thread.

**Comment by b4s36t4** [comment] 2023-08-23 05:38
https://github.com/Expensify/App/assets/59088937/8e7b4a1e-fc27-40b5-9aec-9ffcc81f2f2c

Also I can reproduce this on prod too.

**Comment by trjExpensify** [comment] 2023-08-23 11:11
Oh interesting! I wasn't actually able to repro on prod, so yeah.. this is very likely not a deploy blocker. I'll wait for @puneetlath to chime in before removing the label though.

**Comment by puneetlath** [comment] 2023-08-23 15:04
I agree, not a blocker then. Removing the label and we can handle it like a normal bug.

**Comment by yassinedrissi87** [comment] 2023-08-23 21:20
Proposal
The solution should be implemented when we call the delete request function, once we click on confirm button we must give the value false to the canLeaveRoom function

**Comment by yassinedrissi87** [comment] 2023-08-23 21:22
Contributor details
Your Expensify account email: yassinedeveloper@gmail.com
Upwork Profile Link:  https://www.upwork.com/freelancers/~015c3130c154a47c8f

**Comment by trjExpensify** [comment] 2023-08-24 12:15
we shouldn't be seeing the "hmm.." page when leaving a normal message thread, no.

**Comment by mollfpr** [comment] 2023-08-24 15:01
> I see the problem even happens on normal thread. Is the expectation correct? Thanks


@tienifr Do you mean the user can leave the thread on a normal message?

**Comment by b4s36t4** [comment] 2023-08-24 15:09
@mollfpr The issue is that "Hm..." message is showing when ever we're try to open the thread which we left before. The expected behaviour is that this message shouldn't show either for normal threads or IOU threads. Restricting IOU threads can be enhancement I feel.

**Comment by mollfpr** [comment] 2023-08-25 12:54
I tried to reproduce it on `v1.3.57-3`, but the sub-thread is not created when updating the request amount and the IOU preview is just removed after deleting the request.


https://github.com/Expensify/App/assets/25520267/7a74bb23-6c78-4695-b427-69e3ad86df13

**Comment by luacmartins** [comment] 2023-08-28 15:10
I like how that makes both regular and transaction threads consistent, so we'd still allow users to leave the threads. What do you think @trjExpensify?

**Comment by trjExpensify** [comment] 2023-08-30 14:12
Sure, let's minimally solve the error page consistently across all threads. For transaction threads this issue only appears when you've deleted the transaction, but the thread is preserved when there are comments after all.

**Comment by mollfpr** [comment] 2023-08-30 17:17
@luacmartins @trjExpensify How about showing the loading screen on accessing the abandoned room until we get a response from the API? Proposed by @b4s36t4 [here](https://github.com/Expensify/App/issues/25698#issuecomment-1688699150)

**Comment by trjExpensify** [comment] 2023-08-30 17:18
The skeleton UI do you mean?

**Comment by b4s36t4** [comment] 2023-08-31 09:45
@mollfpr @trjExpensify #26341 these kind of bugs coming as new. Maybe we need to forward with this what should be the expected behaviour? I think Previously we show the loader if there is no report maybe this time too.

**Comment by mollfpr** [comment] 2023-08-31 11:59
> The skeleton UI do you mean?

Yes!

https://github.com/Expensify/App/issues/26341 I think it has the root cause.

**Comment by trjExpensify** [comment] 2023-09-01 11:13
>Yes!

Cool, I agree the skeleton UI is better and what we should display until the page loads versus a "Hmm...it's not here" error message.

**Comment by mollfpr** [comment] 2023-09-01 17:01
Thanks for the confirmation @trjExpensify 

Let's go with @b4s36t4 [proposal](https://github.com/Expensify/App/issues/25698#issuecomment-1688699150) to show the skeleton loader.

🎀 👀 🎀 C+ reviewed!

**Comment by luacmartins** [comment] 2023-09-01 17:13
LGTM! Assigning @b4s36t4 to the issue

**Comment by tranvantoan-qn** [comment] 2023-09-01 22:37
@trjExpensify @luacmartins 
I think the old reward scale should be applied for this issue.
Could you please check it again?

**Comment by b4s36t4** [comment] 2023-09-03 11:53
@mollfpr PR is UP #26602

**Comment by mollfpr** [comment] 2023-09-27 06:17
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

It's a bit tricky, but this issue arises after the revert on https://github.com/Expensify/App/pull/23394 for https://github.com/Expensify/App/pull/22787. So this should be expected.


> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Start a thread
2. Send some message
3. Leave the thread
4. Try opening the thread again from the main report
5. Verify it's showing skeleton loader instead of not found page
6. 👍 or 👎

**Comment by mollfpr** [comment] 2023-09-27 06:39
@b4s36t4 Any suggestion on the above checklist?

**Comment by b4s36t4** [comment] 2023-09-27 06:41
Hey, @mollfpr Sorry it was wrong emoji 😅😅. Also I'd suggest let's add tests for offline behavior as well? Sorry again 😅

**Comment by mollfpr** [comment] 2023-09-27 06:42
@b4s36t4 No worries! 🤣 

I was thinking the same about the offline case; I'll add one. Thanks!

**Comment by trjExpensify** [comment] 2023-09-27 07:26
>Open unexisting report, available test for Web/Desktop

Open **an existing** report? Also, why is this limited to web/desktop? Can you click a URL on mobile?

**Comment by trjExpensify** [comment] 2023-09-27 07:28
Confirming payments as follows:

- @tranvantoan-qn - $250 for the bug report
- @mollfpr - $1,000 for the C+ review
- @b4s36t4 - $1,000 for the bug fix 

#urgency bonus doesn't apply as per [here](https://github.com/Expensify/App/issues/25698#issuecomment-1722683169), and this issue was created before Aug 30th, so the old bounties apply. 

Sound correct?

**Comment by b4s36t4** [comment] 2023-09-27 07:28
I think it unexisting report only, means a report which we're not part of it anymore. Like to say Leaving a thread.

**Comment by b4s36t4** [comment] 2023-09-27 07:29
Yes the amount sounds correct to me.

**Comment by trjExpensify** [comment] 2023-09-27 07:47
P.S settled up with everyone!

**Comment by b4s36t4** [comment] 2023-09-27 08:00
Also, why web/desktop only?

Should be with all platforms, @mollfpr any issues?

**Comment by mollfpr** [comment] 2023-09-27 09:45
>Also, why web/desktop only?

Because the test is to change the URL. We can probably test it in all platforms with the deep link to a random report.

**Comment by trjExpensify** [comment] 2023-09-28 08:07
Yeah, I think we do that. Cool, so we're all done here. Closing!

**Closed by trjExpensify** 2023-09-28 08:07 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
