### ISSUE TITLE
[HOLD for payment 2024-12-03] [Search v1.2] - When paying via search, changes are not seen in LHN and expense preview

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52360] opened 2024-11-12 09:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5201400&group_by=cases:section_id&group_order=asc&group_id=296775
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Tap on "Search" on the bottom of the screen.
3. On any expense with pending payment, tap on "Pay" on the preview.
4. Tap on "Inbox"
5. Verify that the recent payment is reflected on LHN on the preview of the correct chat.
6. Open the chat that contains the expense.
7. Verify the expense preview reflects the payment.

## Expected Result:
When an expense is paid via search, changes should be automatically seen on LHN and on expense preview on chat.

## Actual Result:
When an expense is paid via expense preview on search, chat preview in LHN stil displays "User owes xxxx" and button to pay expense is still displayed on expense preview on chat.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/23d3d146-32f7-45ca-bc80-018dbd7a9bf2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856344566176088663</li>
        <li>Upwork Job ID: 1856344566176088663</li>
        <li>Last Price Increase: 2024-11-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala / @lschurr</details>

**Comment by Kicu** [comment] 2024-11-12 14:27
I have a problem reproducing the case where clicking on "Pay" automatically pays. For me clicking Pay opens RHP and I can correctly pay there which refreshes all the data.

I need some more info how to get an expense where the pay button would behave like on the video? Or perhaps is the problem that I don't have a card attached to my account, and thus I cannot pay directly?

@luacmartins could you please take a look at this?

**Comment by luacmartins** [comment] 2024-11-12 15:50
I think the reason why QA can reproduce is because we have two different behaviors here:

1. If you've never paid an expense on that workspace before, we open the RHP
2. If you've already paid something on that workspace before, we save that last payment method to `nvp_private_lastPaymentMethod` and then the pay action on search uses that payment method to do a "one-click pay".

I'll take a look at all of these Search action blockers and see if we need to revert the original PR or I can put up a quick fix.

**Comment by Gonals** [comment] 2024-11-12 15:51
I'm doing flow 2, though, and not seeing the bug

**Comment by luacmartins** [comment] 2024-11-12 16:37
I think this issue is expected for now, @lakchote and I are working on moving the PHP updates for ApproveMoneyRequest and PayMoneyRequest to Auth. See [this comment](https://github.com/Expensify/Expensify/issues/386310#issuecomment-2455225838). I'll demote this to NAB.

**Comment by luacmartins** [comment] 2024-11-15 22:28
Auth PR merged. Waiting on deploy.

**Comment by twisterdotcom** [comment] 2024-11-18 17:01
Relabelling as Lauren is OOO now.

**Comment by alitoshmatov** [comment] 2024-12-02 18:18
Completing the checklist in original issue https://github.com/Expensify/App/issues/51898#issuecomment-2512337832

**Comment by abekkala** [comment] 2024-12-03 16:37
@Gonals or @luacmartins can you confirm if there are two payments due to @alitoshmatov 
It looks like the checklist for this issue was completed via https://github.com/Expensify/App/issues/51898
Does this require one payment of $250 or does each issue pay out $250?

**Comment by luacmartins** [comment] 2024-12-03 19:34
@abekkala this issue was a regression from https://github.com/Expensify/App/issues/51898, so I think we can process payment in the original issue only.

**Comment by lschurr** [comment] 2024-12-04 18:32
Alright, so payment was handled over here: https://github.com/Expensify/App/issues/51898

I think that means we can close this one right?

**Closed by lschurr** 2024-12-04 18:32 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
