### ISSUE TITLE
Duplicates - Review duplicates button remains on employee side after admin resolves the dupes

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45582] opened 2024-07-17 10:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/45315
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Admin and employee are in the same workspace.
- Delayed submission in Workflows is enabled.

1. Go to staging.new.expensify.com
2. [Employee] Go to workspace chat.
3. [Employee] Submit two expenses with the same amount and merchant.
4. [Admin] Go to workspace chat with employee.
5. [Admin] Go to the transaction thread of any expense.
6. [Admin] Click Review duplicates.
7. [Admin] Click Keep all.

## Expected Result:
On Employee's side, "Review duplicates" button will disappear after admin resolves the duplicates.

## Actual Result:
On Employee's side, "Review duplicates" button remains after admin resolves the duplicates.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f4563160-ee35-4f1f-9faf-45a9f8313ab6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-07-17 10:05
We think this issue might be related to the #collect project.

**Comment by JmillsExpensify** [comment] 2024-07-29 17:17
Happy to chat in Slack/New Expensify as well. I mainly want to align on how we should prioritize the bugs from here on out.

**Comment by pecanoro** [comment] 2024-07-29 22:40
This should by design, it disappears only for whoever dismisses the violation

**Comment by JmillsExpensify** [comment] 2024-07-30 03:26
Ah I think I'm a little confused though given that we're talking about instant submit right? So in that case, why would we ask but the submitter and the approver to individually clear the violations on the same report in the same state. I don't think that's needed, right @trjExpensify?

**Comment by pecanoro** [comment] 2024-07-30 10:09
@JmillsExpensify Only the approver needs to dismiss it to approve the report. However, as oldDot, if you submit the report with the violation, it will still show unless it gets dismissed.

**Comment by trjExpensify** [comment] 2024-07-30 10:11
I'm not sure why submission frequency comes into it per se, but rather, do we still show duplicate violations on `processing` reports after the manager has resolved them and prior to taking the onward action (i.e approve). Historically, I think they've remained until approved. In practice, I kinda' question who will actually notice this timing wise.

**Comment by pecanoro** [comment] 2024-07-30 11:12
> do we still show duplicate violations on processing reports after the manager has resolved them and prior to taking the onward action (i.e approve). Historically, I think they've remained until approved

Yeah, we do unless the person looking at the report has dismissed them. Basically, one person dismissing one violation does not do it for all.

**Comment by JmillsExpensify** [comment] 2024-08-01 23:44
Interesting. So maybe we close this issue then and re-evaluate with more experience.

**Comment by pecanoro** [comment] 2024-08-05 22:04
Let's close for now

**Closed by pecanoro** 2024-08-05 22:04 UTC
Labels: Daily, Overdue, Bug
