### ISSUE TITLE
[$1000] IOU - IOU is displayed as Merchant in IOU details page when IOU is created without a Merchant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25694] opened 2023-08-22 15:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify,com
2. Create money request without selecting a merchant
3. Open the money request report
4. Click on the IOU preview

## Expected Result:
Merchant is not stated because money request is created without selecting a merchant

## Actual Result:
IOU (or sometimes, Request) is shown for Merchant when money request is created without selecting a merchant

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop
 
**Version Number:**1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4ec6929d-e591-4809-b2c2-e8e7a89b449f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d6df5b1911e3c11</li>
        <li>Upwork Job ID: 1694136380885807104</li>
        <li>Last Price Increase: 2023-08-22</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-08-22 16:04
@deetergp Looks like its coming from here
https://github.com/Expensify/App/blob/999ed938befa8910293cf349a4222314d5a73ccd/src/libs/TransactionUtils.js#L46

**Comment by shubham1206agra** [comment] 2023-08-22 16:05
Is it necessary to have merchant or we can leave it blank?

**Comment by shubham1206agra** [comment] 2023-08-22 16:30
Now its showing `Request` as merchant
Looks like its getting overridden from BE

**Comment by shubham1206agra** [comment] 2023-08-22 16:32
Confirmed it
IOU is coming due to optimistic transaction data
And now for blank merchant BE will pass Request as merchant

**Comment by shubham1206agra** [comment] 2023-08-22 19:07
## Proposal
### Please re-state the problem that we are trying to solve in this issue

IOU - IOU is displayed as Merchant in IOU details page when IOU is created without a Merchant

### What is the root cause of that problem?

This is due to during `requestMoney` call we are using `buildOptimisticTransaction` to create optimistic report data
And we use `CONST.REPORT.TYPE.IOU` as the default value for merchant in the places
https://github.com/Expensify/App/blob/999ed938befa8910293cf349a4222314d5a73ccd/src/libs/TransactionUtils.js#L46
and
https://github.com/Expensify/App/blob/999ed938befa8910293cf349a4222314d5a73ccd/src/libs/TransactionUtils.js#L69

### What changes do you think we should make in order to solve the problem?

Replace `CONST.REPORT.TYPE.IOU` with empty strings in `buildOptimisticTransaction`.

### What alternative solutions did you explore? (Optional)

**Comment by deetergp** [comment] 2023-08-22 23:57
I don't think this issue is big enough to consider it a blocker—it is pretty minor.

**Comment by shubham1206agra** [comment] 2023-08-23 03:57
@rushatgabhane Can you review my proposal?

**Comment by tewodrosGirmaA** [comment] 2023-08-23 13:19
Hey guys! I reported this bug in Slack before this issue was created. Could you please change the reporter's name? Thanks! Here's the link to the bug report: Bug Report Slack Link (https://expensify.slack.com/archives/C049HHMV9SM/p1692687129320969)

**Comment by luacmartins** [comment] 2023-08-23 18:46
This is not an issue, all requests should have a default merchant name. We're updating it to the correct merchant name in [this PR](https://github.com/Expensify/App/pull/25702)

**Comment by luacmartins** [comment] 2023-08-23 18:46
Gonna close this one.

**Closed by luacmartins** 2023-08-23 18:46 UTC
Labels: External, Engineering, Daily, Help Wanted
