### ISSUE TITLE
[$1000] Chronos message appears in LHN for a while only as html

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18737] opened 2023-05-10 19:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log out
2. Log in with any account
3. Go to / start a chat with chronos
4. Send the following test message:
```
10am
test [google.com](https://www.google.com/)
```

## Expected Result: 
After a little while the following response should come back and be reflected in the LHN
Thanks for your update!

Current top project: You haven't set a top project

## Actual Result: 
No response is shown in the chat for a while, but the LHN shows a new message with raw html. See screenshot.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/45c0c422-a676-4e84-9f14-9b9e2fb149fa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1682617139068579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b9239420091b5fd</li>
        <li>Upwork Job ID: 1657111444444622848</li>
        <li>Last Price Increase: 2023-05-12</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment] 2023-05-10 19:56
Following this so I can review the PR eventually

**Comment by slafortune** [comment] 2023-05-12 19:51
Looks good!

**Comment by alexxxwork** [comment] 2023-05-13 14:45
I don't see chronos chat, only concierge. How can I start a hat with chronos?

**Comment by PauloGasparSv** [comment] 2023-05-15 18:00
Tested this locally and staging multiple times but could not reproduce this!

@neil-marcellini can you still reproduce this? If so, locally too?

**Comment by PauloGasparSv** [comment] 2023-05-15 18:04
Removed the `external` and `help wanted` labels. @slafortune can you help me with the Upwork job, I think we have to close it right?

**Comment by PauloGasparSv** [comment] 2023-05-23 20:27
Could not focus on this issue yet but will start working on it ASAP

**Comment by PauloGasparSv** [comment] 2023-05-29 18:42
Still no updates but I plan to work on this tomorrow!

**Comment by PauloGasparSv** [comment] 2023-06-05 12:38
Focusing on Manual Requests first then working on this

**Comment by PauloGasparSv** [comment] 2023-06-07 22:11
> Focusing on Manual Requests first then working on this

I'm still not focusing on this but will get to it as soon as I can, I think I'll have time tomorrow. I'll prioritize this as soon as I'm done with Manual Requests

**Comment by PauloGasparSv** [comment] 2023-06-12 21:57
Don't have enough time to make progress here so I'll give an update on this tomorrow.

**Comment by PauloGasparSv** [comment] 2023-06-13 21:49
Reproduced locally and I think I've found a place that returns the wrong onyxData (with the previous message) back to newDot.

I also tested sending `10am` to Chronos in staging and could still replicate the issue.

**Comment by PauloGasparSv** [comment] 2023-06-13 21:51
All right, I think this is happening because we have 2 responses out of order in the same request:

1. Creating the 10am comment
2. Creating the 10am response comment, the real last message

**Comment by PauloGasparSv** [comment] 2023-06-23 21:04
> @PauloGasparSv Huh... This is 4 days overdue. Who can take care of this?

This is not overdue lol

**Comment by PauloGasparSv** [comment] 2023-06-30 23:39
This has been on production for a week (Was manually deployed) so closing it!

**Closed by PauloGasparSv** 2023-06-30 23:39 UTC
Labels: Reviewing, Daily, Internal, Bug
