### ISSUE TITLE
[HOLD for payment 2023-11-17] [$500] No space between description & show more option

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30039] opened 2023-10-20 00:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697621145743689

## Action Performed:
1. Open Request money & select manual tab
2. Enter amount  & select any user
3. Hover on description menu item and observer there is no gap between description & show more option
4. Go back to step one & select distance tab
5. Hover on finish point and observe the space between finish point & add stop option
## Expected Result: 
There should be some gap between description & show more option
## Actual Result: 
There is no gap between description & show more option

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/2f91fab2-f2db-4c2d-a532-1d1045021750

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/d3d40065-219a-48ab-bf30-9738ffef24c8

</details>

<details>
<summary>iOS: Native</summary>

</details>

https://github.com/Expensify/App/assets/38435837/bc4f4634-cce5-46cf-80a6-34ce5125de03

<details>
<summary>iOS: mWeb Safari</summary>

</details>

https://github.com/Expensify/App/assets/38435837/746346be-3588-448b-8543-c55059eb3bd1

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/f4ef5ba5-eb6f-4f69-8e06-ccf6ffb67b7f

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/cfd2dc04-e89b-46a6-b128-d56140bbd930

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e92101d63dc7fd51</li>
        <li>Upwork Job ID: 1715163936897327104</li>
        <li>Last Price Increase: 2023-10-20</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 27512429</li>
<li>krishna2323 | Reporter | 27512432</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @m-natarajan</details>

**Comment by m-natarajan** [comment] 2023-10-20 00:33
### Proposal by contributor reported the bug

### Please re-state the problem that we are trying to solve in this issue.
No space between description & show more option

### What is the root cause of that problem?
We don't apply any margin or padding to top of the show more container.

### What changes do you think we should make in order to solve the problem?
We can either apply margin/padding bottom to description menu item or margin/padding top to the show more container.
We are using `4px` padding for "Add Stop" option and I think it will be the best option but we can discuss about it and then apply.


### Result

**Comment by samilabud** [comment] 2023-10-20 02:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No space between the description & show more option

### What is the root cause of that problem?
The components MenuItemWithTopDescription inside of OptionsSelector (in MoneyRequestConfirmationList component in src/components/MoneyRequestConfirmationList.js) are all aligned using a flex-direction row with the same distance when the 'show more' option is displayed has no margins.

### What changes do you think we should make in order to solve the problem?
The best solution is adding the prop styles.mt2 in style as next, this going to add a margin-top of 2 and produce the space needed, this is the code needed (in file src/components/MoneyRequestConfirmationList.js line 619):
`<View style={[styles.flexRow, styles.justifyContentBetween, styles.mh3, styles.alignItemsCenter, styles.mb2, styles.mt2]}>`

These are the results:
Web:
<img width="454" alt="image" src="https://github.com/Expensify/App/assets/5216036/af1a2b04-030c-4291-bdb9-80abb0693128">
Mac Desktop:
<img width="1194" alt="Screenshot 2023-10-19 at 10 05 46 PM" src="https://github.com/Expensify/App/assets/5216036/4a75a956-2b9c-4b93-b776-4cc40a717259">
Android:
https://github.com/Expensify/App/assets/5216036/0d834be6-d1cb-4b77-a5b8-b306a9aea9bc
IPhone/IOS:
https://github.com/Expensify/App/assets/5216036/cc0bacf6-f2d5-466d-b389-4fcf05e824a6

**Comment by yh-0218** [comment] 2023-10-20 07:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No space between the description & show more option
### What is the root cause of that problem?
There is no `margin-top`
https://github.com/Expensify/App/blob/86e75ad6c95cd5927800bb62b848857716da52f6/src/components/MoneyRequestConfirmationList.js#L619
### What changes do you think we should make in order to solve the problem?
We need to add `margin-top`
```
<View style={[styles.flexRow, styles.justifyContentBetween, styles.mh3, styles.alignItemsCenter, styles.mv2]}>
```
https://github.com/Expensify/App/blob/86e75ad6c95cd5927800bb62b848857716da52f6/src/components/MoneyRequestConfirmationList.js#L619
### What alternative solutions did you explore? (Optional)

**Comment by narefyev91** [comment] 2023-10-20 09:07
@shawnborton Design help needed here!
Can you please check and suggestion - do we really need additional spacing between last button and Show More chip?
This is how we currently have it now:
<img width="440" alt="Screenshot 2023-10-20 at 12 03 35" src="https://github.com/Expensify/App/assets/28352309/196ea1a0-ffec-4c9c-965f-b321680ae761">
This is after any new padding coming in place (chip will take more space, and visually it show a bigger gap - when menu item is not in hover state):
<img width="298" alt="Screenshot 2023-10-20 at 12 03 59" src="https://github.com/Expensify/App/assets/28352309/1efcef20-d8f8-4249-95cd-a9d804133d47">
If we need to add margin - can you please tell how much it should be. Thanks!

**Comment by Pujan92** [comment] 2023-10-20 12:02
We had it earlier and I think mistakenly removed in this [PR](https://github.com/Expensify/App/pull/28110) https://github.com/Expensify/App/pull/28110/files#diff-dc0f934ad9e583b0f7ac049563a3dcacbfe314e9c16b5c6f8bba6e5a5225a86cL478
cc: @akinwale

**Comment by akinwale** [comment] 2023-10-20 12:07
> We had it earlier and I think mistakenly removed in this [PR](https://github.com/Expensify/App/pull/28110) https://github.com/Expensify/App/pull/28110/files#diff-dc0f934ad9e583b0f7ac049563a3dcacbfe314e9c16b5c6f8bba6e5a5225a86cL478 cc: @akinwale
> 
> We can use `styles.mv2` here instead of `styles.mb2`
> 
> https://github.com/Expensify/App/blob/69cf29e32950f915ea888fe294dfdea6a9fabbb5/src/components/MoneyRequestConfirmationList.js#L619

The idea from that PR was to remove the bottom margins from all push-to-page buttons. https://github.com/Expensify/App/issues/27052 for context.

**Comment by akinwale** [comment] 2023-10-20 12:12
> @akinwale, I think we didn't wanted to remove the spacing between "show more" button.

Yeah, I think the ideal solution here would be to add a top margin (or padding?) to the "show more" button. If there's another push-to-page button below "Description" (e.g. "Date" or "Merchant"), we don't want a bottom margin separating those.

**Comment by narefyev91** [comment] 2023-10-20 14:27
Proposal from @m-natarajan looks good to me https://github.com/Expensify/App/issues/30039#issuecomment-1771888313
All proposals are correct - in root case and area to apply a fix - just @m-natarajan was the faster one
🎀 👀 🎀 C+ reviewed

**Comment by akinwale** [comment] 2023-10-20 14:30
> Proposal from @m-natarajan looks good to me [#30039 (comment)](https://github.com/Expensify/App/issues/30039#issuecomment-1771888313) All proposals are correct - in root case and area to apply a fix - just @m-natarajan was the faster one 🎀 👀 🎀 C+ reviewed

@narefyev91 Small correction here. @m-natarajan is on the QA / Applause (I think?) team reposting the solution posted by the issue reporter, @Krishna2323.

**Comment by samilabud** [comment] 2023-10-20 22:46
@narefyev91 @roryabraham Is there any update related to who is assigned to resolve this bug?

**Comment by narefyev91** [comment] 2023-10-23 07:03
> @narefyev91 @roryabraham Is there any update related to who is assigned to resolve this bug?

Hey - i think we waiting final decision from @roryabraham

**Comment by adelekennedy** [comment] 2023-10-25 15:44
@roryabraham removing the overdue here

**Comment by adelekennedy** [comment] 2023-10-30 17:24
@roryabraham bump on [this](https://github.com/Expensify/App/issues/30039#issuecomment-1774553220)

**Comment by roryabraham** [comment] 2023-11-01 00:50
Assigned to @m-natarajan

**Comment by roryabraham** [comment] 2023-11-03 22:48
Done, sorry @Krishna2323.

**Comment by adelekennedy** [comment] 2023-11-07 18:57
waiting on the PR

**Comment by adelekennedy** [comment] 2023-11-20 23:47
Payouts due:

Issue Reporter: $50 @Krishna2323 (pre bounty change) 
Contributor: $500 @{handle}
Contributor+: NA

Eligible for 50% #urgency bonus? N

**Closed** 2023-11-27 17:19 UTC
Labels: External, Weekly, Awaiting Payment, Bug
