### ISSUE TITLE
[HOLD for payment 2024-06-03] [$250] mWeb  - Chat - In edit comment, changed skin tone is not applied

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42058] opened 2024-05-13 13:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4554707
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap in a report
3. Send a message
4. Tap emoji picker in compose box and change the skin tone
5. Enter :+1: and note changed skin tone is applied
6. Clear the text
7. In step 3, long press the message sent and tap edit comment
8. Tap enter key and move cursor to second line.
9. Enter :+1: and note changed skin tone is not applied

## Expected Result:
In edit comment, changed skin tone must be applied

## Actual Result:
In edit comment, changed skin tone is not applied

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2a8e53d4-d7a1-4bc6-8c23-a09e226e723f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013cd26a26b248adb5</li>
        <li>Upwork Job ID: 1790054359169802240</li>
        <li>Last Price Increase: 2024-05-13</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment] 2024-05-13 13:26
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-13 13:26
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment] 2024-05-13 13:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The preferred skin tone doesn't update in edit composer, but updates in main composer.

### What is the root cause of that problem?
The preferred skin tone value is passed from the ReportActionItem to the composer.
https://github.com/Expensify/App/blob/3bdb08d72381899aec31af4822849edb7d555a2f/src/pages/home/report/ReportActionItem.tsx#L1021-L1025
https://github.com/Expensify/App/blob/3bdb08d72381899aec31af4822849edb7d555a2f/src/pages/home/report/ReportActionItem.tsx#L675-L676

And ReportActionItem use a memo to optimize the rendering, but we haven't consider the case for the preferred skin tone, so even after it's updated, the component never re-renders.
https://github.com/Expensify/App/blob/3bdb08d72381899aec31af4822849edb7d555a2f/src/pages/home/report/ReportActionItem.tsx#L1053-L1087

### What changes do you think we should make in order to solve the problem?

Check for preferred skin tone in the memo.
`prevProps.preferredSkinTone === nextProps.preferredSkinTone &&`.

### What alternative solutions did you explore? (Optional)
Move the preferred skin tone onyx connection to edit composer component

**Comment by s77rt** [comment] 2024-05-14 09:29
@bernhardoj Thanks for the proposal. Your RCA is correct. The onyx bug technically is still reproducible as [the HOC can still return `null`](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/withOnyx.js#L316-L318). It's probably hard to reproduce now due to caching. But also the use of `initialValue` prevents the bug since we will have a value to render initially. We can now move the onyx subscription to `ReportActionItemMessageEdit` and to be extra safe we should use the `useOnyx` hook as it does not suffer from the problem in the HOC.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/42058#issuecomment-2107627115)

**Comment by bernhardoj** [comment] 2024-05-15 03:19
PR is ready

cc: @s77rt

**Comment by s77rt** [comment] 2024-05-29 08:12
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/18809
- The offending PR has been commented on: https://github.com/Expensify/App/pull/18809#discussion_r1618375790
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**
1. Go to any report
2. Send a message
3. Right click (or long press) on the message and select "Edit comment"
4. Type any emoji code e.g. `:+1:`
5. Change the skin tone from the emoji picker button
6. Type any emoji code e.g. `:+1:`
7. Verify that newly inserted emoji has the updated skin tone color

**Comment by garrettmknight** [comment] 2024-06-03 18:01
All paid up and QA'd, closing!

**Closed by garrettmknight** 2024-06-03 18:01 UTC
Labels: External, Daily, Awaiting Payment, Bug
