### ISSUE TITLE
User is unable to authenticate with magic link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25979] opened 2023-08-25 21:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to sig-up page
2. Enter email & click on 'Continue' button
3. Open email > copy magic link > open new tab
4. Paste to browser address bar & prefix the link with dev link in the following format: http://localhost:8082/v/15361796/136890
5. Press enter
6. Switch to the tab where user was trying to sign in
## Expected Result: 
User should be signed in
## Actual Result: 
User is not signed in until the user refreshes the page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692948638904319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2023-08-25 21:42
I know @tgolen is out for the rest of the day, grabbing this

**Comment by roryabraham** [comment] 2023-08-25 23:36
This is not reproducible on staging, so not a deploy blocker.

**Comment by NicMendonca** [comment] 2023-08-28 14:35
@kavimuru I am unable to reproduce this 👀

**Comment by Natnael-Guchima** [comment] 2023-08-28 14:38
Hello @NicMendonca did you try on development environment? I think the issue only exists on dev currently.

**Comment by tgolen** [comment] 2023-08-28 16:27
@Natnael-Guchima Does it work if you manually enter the code?

**Comment by Natnael-Guchima** [comment] 2023-08-28 16:28
@tgolen yes it works fine when you entered the magic code manually

**Comment by Natnael-Guchima** [comment] 2023-08-28 17:04
One user pastes the magic, they should be navigated into the app, rather the they are stuck at enter magic code page. The same flow works fine on staging.

**Comment by tgolen** [comment] 2023-08-28 17:07
> is it a frontend issue, or a backend issue?

**Comment by Natnael-Guchima** [comment] 2023-08-28 17:16
I am not sure. But I guess it is front-end issue that is related to navigation.

**Comment by tgolen** [comment] 2023-08-28 18:50
Could you please try some of the following and add the information to this issue?

- Look at JS console for any errors
- Look at the network requests to see if requests are successful
- For requests that are successful for validating the magic code, can you please include their `requestID` in case I need to look up the logs for those requests on the server?

**Comment by Natnael-Guchima** [comment] 2023-08-28 19:24
@tgolen

Response to the request: 
{
    "httpCode": 200,
    "jsonCode": 200,
    "authResponseMessage": "200 OK",
    "requestID": "7fdee47cc8ef11ac-MRS"
}

Console log: 

![Screenshot from 2023-08-28 22-20-42](https://github.com/Expensify/App/assets/57330233/d85e343f-ab69-4376-b87e-4a6773485c0c)

Now the issue is reproducible on staging: 

https://github.com/Expensify/App/assets/57330233/c683bf4a-7429-4c24-976d-6aad508e3049

And it works fine on prod: 

https://github.com/Expensify/App/assets/57330233/5d5bb161-30d9-4b24-8b15-cfe9d5c9ad89

**Comment by tgolen** [comment] 2023-08-28 19:38
OK, thank you! @johnmlee101 or @NikkiWines Do either of you might know what's going on here?

**Comment by johnmlee101** [comment] 2023-08-28 20:21
Has this always worked on staging? Some random part in the back of my subconscious thinks this flow only worked on prod but I can't for the life of me remember why. However the fact that the page just kind of sticks is very odd. Let me test and see

**Comment by johnmlee101** [comment] 2023-08-28 20:23
Okay I couldn't reproduce on staging but it was _realllllllly_ slow. Which honestly feels like a performance regression. It took like 10 seconds to load the page, and another 5 seconds after to actually update the original sign in page with the code

**Comment by Natnael-Guchima** [comment] 2023-08-30 03:38
@tgolen this issue is now reported by applause as a deploy blocker [here ](https://github.com/Expensify/App/issues/26190)

**Comment by tgolen** [comment] 2023-08-30 17:06
I'm going to close this issue as a duplicate.

**Closed by tgolen** 2023-08-30 17:06 UTC
Labels: Engineering, Weekly, Help Wanted, Bug

**Comment by Natnael-Guchima** [comment] 2023-08-30 17:08
@tgolen my report came first. The duplicate one is the one reported by applause. Can you please add my name on the other issue as a reporter?

**Comment by tgolen** [comment] 2023-08-30 17:16
Sure, updated 👍

**Comment by Natnael-Guchima** [comment] 2023-08-30 17:19
Thanks 👍
