### ISSUE TITLE
Log in - After pressing Go back button, the user's email remains in the log in field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12454] opened 2022-11-03 21:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Put your user name and click Continue
3. Click Go Back button

## Expected Result:
The log field should be empty after pressing the Go back button, 

## Actual Result:
After pressing Go back button, the user's email remains in the log in field

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.23.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/199840757-6bf896ba-c3f0-4310-82cf-7f5b646527fd.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2022-11-03 21:48
Issue is not reproduced in Production changing to Deploy Blocker

https://user-images.githubusercontent.com/93399543/199840930-ed81a941-1104-4477-ae44-5cb2de38111d.mp4

**Comment by thesahindia** [comment] 2022-11-03 21:51
Not a bug! It is intentional and was introduced by https://github.com/Expensify/App/pull/12062.

**Comment by mananjadhav** [comment] 2022-11-03 21:56
As @thesahindia pointed out, this is the intended behavior now @kbecciv

**Comment by sonialiap** [comment] 2022-11-03 22:13
Thanks @thesahindia and @mananjadhav! Closing since this is not a bug

**Closed by sonialiap** 2022-11-03 22:13 UTC
Labels: DeployBlockerCash, Engineering, Hourly

**Comment by roryabraham** [comment] 2022-11-03 23:12
@Expensify/applauseleads can we please update the regression suite if needed?

**Comment by isagoico** [comment] 2022-11-04 22:13
@roryabraham Steps have been added to cover the new expected behavior in the regression 
- [Log in to a newly created account and "Go Back" button](https://expensify.testrail.io/index.php?/cases/view/1970997)
![image](https://user-images.githubusercontent.com/44479856/200082550-c512717d-552c-432e-987a-a1a4595e31c7.png)

Let me know if these are good or if any correction is needed.
