### ISSUE TITLE
[$250] Log in - Empty onboarding modal shows up when redirected from OD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48656] opened 2024-09-05 15:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign in with a new account on staging.new.expensify.com
2. On a new tab navigate to OldDot
3. Sign up with the email used in step 1
4. After OldD redirects user to NewD open the first tab you signed in on NewD on step 1

## Expected Result:
Onboarding modal shows content

## Actual Result:
Empty onboarding modal shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/75ebe7e6-9b6f-40ab-a837-c81958cc29de

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832053842809458623</li>
        <li>Upwork Job ID: 1832053842809458623</li>
        <li>Last Price Increase: 2024-09-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by lanitochka17** [comment] 2024-09-05 15:29
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-09-05 15:31
We think that this bug might be related to #wave-collect - Release 1

**Comment by sonialiap** [comment] 2024-09-06 13:50
Pretty odd flow for a user to take, but I'll move it to external to see if we can polish this.

**Comment by ikevin127** [comment] 2024-09-09 21:36
💰 Looking for proposals (if the issue is reproducible).

**Comment by ikevin127** [comment] 2024-09-14 02:09
💰 Looking for proposals (if the issue is reproducible).

**Comment by rezkiy37** [comment] 2024-09-16 12:56
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by rezkiy37** [comment] 2024-09-16 12:57
I am familiar with the context of this feature because I worked on it.

**Comment by ikevin127** [comment] 2024-09-16 19:19
> Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.
> I am familiar with the context of this feature because I worked on it.

Sure, if this is still reproducible please go ahead.

🎀👀🎀 C+ reviewed

**Comment by rezkiy37** [comment] 2024-09-17 11:12
I could not reproduce the bug. I've tried 2 times with different accounts. Currently, it logs into OD successfully and does not redirect to ND. Meanwhile, ND logs out.

https://github.com/user-attachments/assets/7d70a8d0-a4a6-466d-a755-716cc209f9cd

**Comment by neil-marcellini** [comment] 2024-09-17 19:16
Sounds like it's not reproducible. I'm closing it.

**Closed by neil-marcellini** 2024-09-17 19:16 UTC
Labels: External, Daily, Help Wanted, Bug
