### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] Sign in – Onboarding modal is missing in new tab

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47054] opened 2024-08-08 10:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** ponikarchuks+98824@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. In Sign in page enter new Gmail account
3. When Onboarding modal appears open new tab and paste https://staging.new.expensify.com/

## Expected Result:
Onboarding modal is present in new tab

## Actual Result:
Onboarding modal is missing in new tab

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6395e2b1-0d6e-43a8-9ff1-5d09d2c76df5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f33db55519f8fc02</li>
        <li>Upwork Job ID: 1821535504288913507</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 103468942</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-08-08 10:26
We think that this bug might be related to #vip-vsb

**Comment by trjExpensify** [comment] 2024-08-08 13:14
So strange. Can't reproduce with private domain, can reproduce with public domain: 

https://github.com/user-attachments/assets/49aa21f4-5adc-4145-9ffb-cd32a89cfb94

**Comment by trjExpensify** [comment] 2024-08-08 13:14
Let's get some eyes on it.

**Comment by jayeshmangwani** [comment] 2024-08-08 14:50
> When we open a new tab, the isOnboardingFlowStatusKnownPromise promise reset after we call isOnboardingFlowCompleted [here](https://github.com/Expensify/App/blob/d7b0aba10b580b7b8adebb3cdb2a8026f119dafa/src/libs/actions/Welcome.ts#L48)

@dominictb I don't think this is the root cause. The issue is happening on staging and not in production, so any recent PR may have caused this problem.

**Comment by jayeshmangwani** [comment] 2024-08-08 15:23
@fedirjh I tested it after commenting out that code, and I'm still able to reproduce the issue. Have you tested to confirm that it's the cause of this bug?

**Comment by jayeshmangwani** [comment] 2024-08-08 15:31
> @jayeshmangwani The changes that @dominictb pointed out in his proposal are recently added in this PR, which is deployed to staging recently :


@fedirjh I've tested it a few times, but I'm not confident that those lines are the cause. Are you sure about this?

**Comment by tushar-a-b** [comment] 2024-08-08 15:46
Hello, I am the author of PR #46750. I removed my changes and tried to reproduce the bug, and I can still reproduce it even without the changes from my PR.

**Comment by jayeshmangwani** [comment] 2024-08-08 16:09
> @jayeshmangwani Did you disable the strict mode?

No, let me try it by disabling it

**Comment by jayeshmangwani** [comment] 2024-08-08 16:17
Thanks for the help, @dominictb and @fedirjh. Disabling the strict mode did the trick!

**Comment by jayeshmangwani** [comment] 2024-08-08 16:21
@dominictb's  [Proposal](https://github.com/Expensify/App/issues/47054#issuecomment-2275970044) will solve this issue. 

Issue comes from this PR https://github.com/Expensify/App/pull/46559, that was merged recently and it is now in the regression period. 

@NikkiWines What do you suggest? How should we proceed?

**Comment by trjExpensify** [comment] 2024-08-08 16:43
We should get this back to the C+ and PR author if they're here to fix it, or revert that PR. @DylanDylann @nkdengineer

**Comment by nkdengineer** [comment] 2024-08-08 16:47
I will raise a PR to fix this issue.

**Comment by nkdengineer** [comment] 2024-08-08 17:14
@DylanDylann The PR is [here](https://github.com/Expensify/App/pull/47097).

**Comment by NikkiWines** [comment] 2024-08-08 17:20
Yeah, ideally let's have this solved by the original PR author - though if we end up using the solution that was posted above, let's be sure to compensate @dominictb's accordingly

**Comment by marcaaron** [comment] 2024-08-08 20:07
Removing the `DeployBlocker` label as it looks like a frontend issue.

**Comment by jayeshmangwani** [comment] 2024-08-09 08:55
I’m unassigning myself from this issue. @DylanDylann will be handling it

**Comment by NikkiWines** [comment] 2024-08-09 20:58
@ishpaul777 reviewed, adding assingment

**Comment by marcaaron** [comment] 2024-08-09 22:12
Fixed with a CP

**Comment by NikkiWines** [comment] 2024-08-14 11:14
> @NikkiWines Should I eligible for compenstation since this https://github.com/Expensify/App/pull/47097 uses my proposal https://github.com/Expensify/App/issues/47054#issuecomment-2275970044?. The only difference is it creates a new function to resolve the onboarding promise.

Yes, since the core logic used in the fix is the same, I think compensation should be provided as the issue had been marked as `external` and `help wanted` at the time of your proposal being made. @trjExpensify what do you think?

**Comment by trjExpensify** [comment] 2024-08-14 11:37
I think we can do a partial payment agreed, so when this comes around, I'll be sure to send an offer for $125.

**Comment by trjExpensify** [comment] 2024-08-23 09:34
Yup, I've been OoO. Payment summary as follows: 

- $125 to @dominictb for contributing to the proposed fix
- $250 to @ishpaul777 for the C+ review 

@ishpaul777 paid, @dominictb I've reached out to you for your Upwork profile.

**Comment by trjExpensify** [comment] 2024-08-23 09:53
@dominictb offer now sent.

**Comment by trjExpensify** [comment] 2024-08-23 10:52
Paid, closing!

**Closed by trjExpensify** 2024-08-23 10:52 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
