### ISSUE TITLE
Web - App displays incorrect magic code even for right code after 5 tries

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22477] opened 2023-07-08 12:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. If logged in then log out
3. Enter any contact and click on Continue
4. Enter wrong magic code 5 times
5. Now enter right magic code and observe that app still gives incorrect magic code error

## Expected Result:
App should allow user to login if right magic code is entered

## Actual Result:
App provides incorrect magic code error and does not allow to login when right code is enter after 5 wrong code entry

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a83ae6ed-a2c0-4f3e-b38e-1874823bb1fa

https://github.com/Expensify/App/assets/93399543/58abaff5-5bd4-40df-a308-4a395a83be47

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688735229900869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment] 2023-07-08 17:15
# Proposed solution
### Please re-state the problem that we are trying to solve in this issue.
- Login code page shows incorrect magic code after writing true magic code after 5 tries.

### What is the root cause of that problem?
- Probably API is discarding the magic code session after 1st try.
- Thus on second try, it is not able to find the session's magic code after first try.

### What changes do you think we should make in order to solve the problem?
- We should not discard the magic code session after until the user has successfully logged in or should discard it after 3 tries. And ask user to re-send code again.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by mallenexpensify** [comment] 2023-07-11 02:23
Was able to reproduce, checking if we have a limit on retry attempts for magic codes
https://expensify.slack.com/archives/C049HHMV9SM/p1689042165897729?thread_ts=1688735229.900869&cid=C049HHMV9SM

**Comment by mallenexpensify** [comment] 2023-07-15 00:32
checking again for more detail https://expensify.slack.com/archives/C049HHMV9SM/p1689042165897729?thread_ts=1688735229.900869&cid=C049HHMV9SM

**Comment by mallenexpensify** [comment] 2023-07-17 20:47
Closing, this isn't a bug, there is a limit on the number of attempts for magic codes.

**Closed** 2023-07-17 20:47 UTC
Labels: Daily, Bug
