### ISSUE TITLE
[HOLD for payment 2023-06-19] [$2000] The password field loads infinitely on deleting the pdf file from the sender's account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18903] opened 2023-05-14 10:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to staging dot on mweb chrome and login with User A
2. Go to any chat with User B (Make sure to login with User B on android earlier)
3. From User A account, send two attachments in the order: First send the password protected file and then send any image
4. Very important step- On Android (User B), first select the last attachment (image) and click on left arrow key to navigate to the password-protected pdf (do not slide using fingers). Note:  Also, it's important to navigate from different attachments, as we're doing here , then only it will be reproducible
5. Enter any wrong password (please don't click on confirm yet)
6. From User's A account on mweb chrome, now delete the pdf file
7. Go to Android(User B) and now click on confirm
8. Notice that after clicking on the confirm field, it shows 'Unable to load pdf file' at top , while shows an infinite loading at the bottom. Thus, if the receiver is trying to type the password and if at the same time, sender deletes the file, in that case the password field goes into infinite loading. Also, it shows a weird display where loading pdf error is shown at the top and the infinite loading is seen at the bottom.

## Expected Result:
The password field should not load infinitely on deleting the pdf file from the sender's account if receiver has navigated to the Pdf from the other attachment.
## Actual Result:
The password field loads infinitely on deleting the pdf file from the sender's account if receiver has navigated to the Pdf from the other attachment using the arrow button

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4ad59a92-1ca0-4094-865f-157dbbc5989a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683961586794579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3ab5bde116ff8fd</li>
        <li>Upwork Job ID: 1659106012236103680</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-05-17 02:05
This feels like an extreme edge case issue. I asked in Slack if this is worth fixing: https://expensify.slack.com/archives/C02NK2DQWUX/p1684289126736739

**Comment by sakluger** [comment] 2023-05-18 07:57
We decided to fix this one, since it could affect other use cases in the future. Adding the external label.

**Comment by diegao15** [comment] 2023-05-18 13:12
Hi there, I would like to know if I can help you with these bugs?

**Comment by diegao15** [comment] 2023-05-18 13:22
Contributor details
Your Expensify account email: diegao15@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/diegosouza

**Comment by sakluger** [comment] 2023-05-18 18:56
Hi @diegao15, thanks for offering to help! If you'd like to contribute, please review our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) first to learn how Expensify works with contributors.

**Comment by diegao15** [comment] 2023-05-18 22:19
Hi there Sasha, could you invite me for these two groups?

  1.  #expensify-open-source<https://expensify.slack.com/archives/C01GTK53T8Q> -- used to ask general questions, facilitate discussions, and make feature requests.
  2.  #expensify-bugs<https://expensify.slack.com/archives/C049HHMV9SM> -- used to discuss or report bugs specifically.

best regards!


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Sasha Kluger ***@***.***>
Enviado: quinta-feira, 18 de maio de 2023 15:56
Para: Expensify/App ***@***.***>
Cc: diegao15 ***@***.***>; Mention ***@***.***>
Assunto: Re: [Expensify/App] [$1000] The password field loads infinitely on deleting the pdf file from the sender's account (Issue #18903)


Hi @diegao15<https://github.com/diegao15>, thanks for offering to help! If you'd like to contribute, please review our contributing guidelines<https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md> first to learn how Expensify works with contributors.

**Comment by payal-lathidadiya** [comment] 2023-05-19 16:33
Found challenging to reproduce. 
I tried multiple times with given steps but couldn't really reproduce.

**Comment by sakluger** [comment] 2023-05-21 19:54
Assigning to a different BugZero member since I will be working at a conference all next week.

**Comment by payal-lathidadiya** [comment] 2023-05-22 13:57
@priya-zha can you please help to reproduce this issue?

**Comment by priya-zha** [comment] 2023-05-22 14:32
@payal-lathidadiya I tried it again and it's reproducible. I've attached the recent video recorder for your reference. The best way to reproduce this bug is:

1. From sender's account on **mweb chrome** (User A) , send three attachments to User B (receiver) in order: **First** : Image , **Second** : password protected pdf , **Third** : image 
3. From the receiver account on **ANDROID** (User B),  click on the third attachment (Image) > Navigate to the password protected file using left arrow key on the screen > Click on enter password and enter any wrong password (please do not click on confirm)
4. Now go back to **senders** account and delete the password protected file 
5. If you go back to **receiver** account, still the password field is seen and if you click on confirm, it loads infinitely

https://github.com/Expensify/App/assets/34065075/fcadce88-8b56-4d7d-b8cc-fb27bbcd34af

**Comment by stitesExpensify** [comment] 2023-05-23 23:18
Getting a new bugzero member because Anu is OOO until the end of the month

**Comment by payal-lathidadiya** [comment] 2023-05-26 15:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The password field loads infinitely on deleting the pdf file from the sender's account. And the submit button shows loading indicator even after failure.

### What is the root cause of that problem?
When password is submitted, we update state field `shouldShowLoadingIndicator` as true [code here](https://github.com/Expensify/App/blob/main/src/components/PDFView/index.native.js#L104) while attempting PDF load with given password. On finish load, we set it to false as well [here](https://github.com/Expensify/App/blob/main/src/components/PDFView/index.native.js#L118)

In case of failure, we don't turn that flag off to hide the loading indicator. Hence, it shows loading indicator indefinitely on button.

### What changes do you think we should make in order to solve the problem?

When PDF load fails, we should update set `shouldShowLoadingIndicator` as false to turn off loading state. 
To achieve that, update below to `handleFailureToLoadPDF` function state section [here](https://github.com/Expensify/App/blob/main/src/components/PDFView/index.native.js#L62)
```js
this.setState({
    ...
    shouldRequestPassword: false,
    shouldShowLoadingIndicator: false,
});
```

In fact, when error occurs other than invalid password, it shouldn't show password form. So, it should also set `shouldRequestPassword: false`

### What alternative solutions did you explore? (Optional)
None

**Comment by stitesExpensify** [comment] 2023-05-29 18:15
@rushatgabhane can you please review the above proposals?

**Comment by payal-lathidadiya** [comment] 2023-06-01 08:56
[PR](https://github.com/Expensify/App/pull/19946) is ready for review

**Comment by payal-lathidadiya** [comment] 2023-06-02 14:06
@rushatgabhane @stitesExpensify Just a friendly remind in case you missed this!

Thank you in advance.

**Comment by payal-lathidadiya** [comment] 2023-06-09 04:48
@rushatgabhane This issue is not updated even after PR is merged and fix is deployed. I assume this happens automatically by bot, right?

**Comment by puneetlath** [comment] 2023-06-09 21:45
The issue will be updated once it gets deployed to production. That's when the 7 day clock starts for payment.

**Comment by puneetlath** [comment] 2023-06-23 16:21
@priya-zha @rushatgabhane I've sent you all Upwork contracts. 

@payal-lathidadiya could you please apply to the job? https://www.upwork.com/jobs/~01e3ab5bde116ff8fd

@rushatgabhane let me know when you're done with the checklist so that we can fully close this out.

**Comment by payal-lathidadiya** [comment] 2023-06-23 17:44
@puneetlath I applied to upwork job.

**Comment by puneetlath** [comment] 2023-07-05 14:08
Cool! Going to go ahead and close out then. Thanks everyone!

**Closed by puneetlath** 2023-07-05 14:08 UTC
Labels: External, Weekly, Awaiting Payment, Bug
