### ISSUE TITLE
[$500] Android - Rooms can be created when the user presses the Return key while typing in the description

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36624] opened 2024-02-15 19:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch the app
2. Log in with your account
3. Tap on Plus green button
4. Select Start Chat - Room
5. Enter room name
6. On description, use any text and hit Return key on Samsung device

## Expected Result:
Room should not be created

## Actual Result:
Rooms can be created when the user presses the Return key while typing in the description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b2646eb7-83c3-4fc6-b79e-4676de28c985

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe10c08e956825df</li>
        <li>Upwork Job ID: 1758204974898151424</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-15 19:02
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by agent3bood** [comment] 2024-02-18 19:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Android - Rooms can be created when the user presses the Return key while typing in the description

### What is the root cause of that problem?

The component tha listens for `Enter` keyboard shortcut is not able to detect the description field as multiline.
Look [here](https://github.com/Expensify/App/blob/a0574d54b166a88bf3cf43af2b750d850692213a/src/components/Button/index.tsx#L133)
while the web implementation for `validateSubmitShortcut` is skipping this event when `eventTarget.nodeName === 'TEXTAREA'
the native implementation does not have any information of the event or what type of element is focused.


### What changes do you think we should make in order to solve the problem?

Update [`KeyboardShortcutComponent`](https://github.com/Expensify/App/blob/a0574d54b166a88bf3cf43af2b750d850692213a/src/components/Button/index.tsx#L125) and add new arg `isMultiline`
and use that in the `validateSubmitShortcut` function.

Because the `keyboardShortcutComponent` is only used locally this change will not break other parts of the app, and it will be the expected behaviour to not submit the form when the user presses `Enter` while typing in a multiline field.

### What alternative solutions did you explore? (Optional)

- Check if `bindHandlerToKeydownEvent` emit any useful information when the enter key is pressed on native, the `event` was just `undefined`.
- Tyr to get the focused node and figure out if it is a multiline field, but native do not support focus.

**Comment by mananjadhav** [comment] 2024-02-19 18:55
@kbecciv I can see only `Android native` is marked as the platform. Can you please confirm about other platforms? If not, then none of the proposals highlight why it is only reproducicble in Android.

**Comment by kbecciv** [comment] 2024-02-22 14:53
@mananjadhav Let me double check with reproducible platforms.

**Comment by kbecciv** [comment] 2024-02-22 21:42
@mananjadhav Issue is reproducible only on Android app

**Comment by mananjadhav** [comment] 2024-02-27 16:45
Will review this by tomorrow.

**Comment by mananjadhav** [comment] 2024-02-28 16:57
I have asked for a clarifying question [here](https://github.com/Expensify/App/pull/34150#issuecomment-1969422855). Overall I am inclined to use `disablePressOnEnter`.

**Comment by mananjadhav** [comment] 2024-02-28 19:25
@kevinksullivan I am a little lost here on the expected behavior. Based on @ishpaul777's [comment](https://github.com/Expensify/App/pull/34150#issuecomment-1969453412) it was done intentionally? Are we looking to rollback the change or only fix for Android?

**Comment by mananjadhav** [comment] 2024-03-10 18:52
> @kevinksullivan I am a little lost here on the expected behavior. Based on @ishpaul777's [comment](https://github.com/Expensify/App/pull/34150#issuecomment-1969453412) it was done intentionally? Are we looking to rollback the change or only fix for Android?

@kevinksullivan Can you please confirm the expected behavior?

**Comment by kevinksullivan** [comment] 2024-03-15 22:09
Huh, closing out if this was by design. @kbecciv was there a particular test you ran where it suggested this was a bug?

**Closed by kevinksullivan** 2024-03-15 22:09 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug

**Comment by kbecciv** [comment] 2024-03-19 15:49
@kevinksullivan No particular test, exploratory issue!
