### ISSUE TITLE
[HOLD for payment 2022-09-26] [$250] User can't use , (comma) In spanish for decimals during IOU - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9497] opened 2022-06-20 17:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to setting > Workspace > Reimburse expenses page
2. Try using comma in the Rate input

## Expected Result:
User should be able to use comma, also the decimal should change to comma after changing the language to spanish.

## Actual Result:
User can't use comma

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screen Shot 2022-06-20 at 1 41 08 PM](https://user-images.githubusercontent.com/43995119/174654554-cd89dd26-c13d-4c92-bfe8-229e66ce21cf.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1655491691902889

**Job:** https://www.upwork.com/jobs/~0174a215853c604f4d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2022-06-21 18:21
@kevinksullivan reassigning you b/c I think @joelbettner unassigned you on accident 😅

**Comment by kevinksullivan** [comment] 2022-06-24 03:50
Just adding that we believe this already [exists for the send/request money flows](https://expensify.slack.com/archives/C01GTK53T8Q/p1655492009832279?thread_ts=1655491691.902889&cid=C01GTK53T8Q), so that code likely offers some guidance.

**Comment by kevinksullivan** [comment] 2022-06-24 03:52
@thesahindia please apply for reporting. Thanks!

**Comment by eVoloshchak** [comment] 2022-06-25 14:51
**Proposal:**
I'm not sure if this input is considered a Form input, but [FORMS.md](https://github.com/Expensify/App/blob/main/FORMS.md) states that
> User input that may include optional characters (e.g. (, ), - in a phone number) should never be restricted on input, nor be modified or formatted on blur. This type of input jacking is disconcerting and makes things feel broken.
Instead we will format and clean the user input internally before using the value (e.g. making an API request where the user will never see this transformation happen)

And I agree with that since I've also tried pressing `,` key instead of `.`, even though I'm not using Spanish (many countries use `,` instead of `.` as a separator)

I'm proposing we allow user to use both `,` and `.` and then just replace commas with periods when user presses `Next`

1. Replace https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/pages/iou/steps/IOUAmountPage.js#L122 with
```javascript
const decimalNumberRegex = new RegExp(/^\d+(,\d{0,2})*(\.\d{0,2})?$/, 'i');
```
2. Replace https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/pages/iou/steps/IOUAmountPage.js#L239 with
```javascript
onPress={() => this.props.onStepComplete(this.state.amount.replace(',', '.'))}
```
3. Remove all of the calls to `this.stripCommaFromAmount`

**Result:**

https://user-images.githubusercontent.com/9059945/175778816-fefa015d-f5e3-427c-bd31-1f92a3b83ebb.mp4

**Comment by eVoloshchak** [comment] 2022-06-25 16:30
> **Proposal:** I'm not sure if this input is considered a Form input, but [FORMS.md](https://github.com/Expensify/App/blob/main/FORMS.md) states that
> 
> > User input that may include optional characters (e.g. (, ), - in a phone number) should never be restricted on input, nor be modified or formatted on blur. This type of input jacking is disconcerting and makes things feel broken.
> > Instead we will format and clean the user input internally before using the value (e.g. making an API request where the user will never see this transformation happen)
> 
> And I agree with that since I've also tried pressing `,` key instead of `.`, even though I'm not using Spanish (many countries use `,` instead of `.` as a separator)
> 
> I'm proposing we allow user to use both `,` and `.` and then just replace comma with a period when user presses `Next`
> 
> 1. Replace https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/pages/iou/steps/IOUAmountPage.js#L122
>     with
> 
> ```js
> const decimalNumberRegex = new RegExp(/^\d+(,\d{0,2})*(\.\d{0,2})?$/, 'i');
> ```
> 
> 2. Replace https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/pages/iou/steps/IOUAmountPage.js#L239
>     with
> 
> ```js
> onPress={() => this.props.onStepComplete(this.state.amount.replace(',', '.'))}
> ```
> 
> 3. Remove all of the calls to `this.stripCommaFromAmount`
> 
> **Result:**
> 
>  cinnamon-20220625-1.mp4 
> **UPD** OK, i think i got confused, since the issue description is talking about the `Rate` input on Reimburce Expenses screen, while screenshot contains IOU Amount Page with an amount input. If the description is correct, we need to do the following:
> 
> 1. Replace https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/CONST.js#L668
>     with
> 
> ```js
> RATE_VALUE: /^\d{1,8}(\.\d*)*(\,\d*)?$/,
> ```
> 
> 2. Edit [updateRateValue](https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/pages/workspace/reimburse/WorkspaceReimburseView.js#L117) method in [WorkspaceReimburseView](https://github.com/Expensify/App/blob/main/src/pages/workspace/reimburse/WorkspaceReimburseView.js) so that it retains the separator the user has entered while sending a number with period to the server
> 
> ```js
>     updateRateValue(value) {
>         const numValue = parseFloat(value.replace(',', '.'));
> 
>         if (_.isNaN(numValue)) {
>             return;
>         }
> 
>         const rateToDisplay = value.includes(',') ? numValue.toFixed(3).replace('.', ',') : numValue.toFixed(3);
> 
>         this.setState({
>             rateValue: rateToDisplay,
>         });
> 
>         Policy.setCustomUnitRate(this.props.policyID, this.state.unitID, {
>             customUnitRateID: this.state.rateID,
>             name: this.state.rateName,
>             rate: numValue.toFixed(3) * 100,
>         }, null);
>     }
> ```
> 
> **Result:**
> 
>  cinnamon-20220625-2.mp4

On a side note, I personally think that updating input's value so that the number always has 3 digits after he separator looks suboptimal (notice that on the video). We could just delete `const rateToDisplay` and `setState` after that and the user's input will not be modified on the UI side. What do you think?

**Comment by eVoloshchak** [comment] 2022-06-25 16:31
> **Proposal:** I'm not sure if this input is considered a Form input, but [FORMS.md](https://github.com/Expensify/App/blob/main/FORMS.md) states that
> 
> > User input that may include optional characters (e.g. (, ), - in a phone number) should never be restricted on input, nor be modified or formatted on blur. This type of input jacking is disconcerting and makes things feel broken.
> > Instead we will format and clean the user input internally before using the value (e.g. making an API request where the user will never see this transformation happen)
> 
> And I agree with that since I've also tried pressing `,` key instead of `.`, even though I'm not using Spanish (many countries use `,` instead of `.` as a separator)
> 
> I'm proposing we allow user to use both `,` and `.` and then just replace comma with a period when user presses `Next`
> 
> 1. Replace https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/pages/iou/steps/IOUAmountPage.js#L122
>     with
> 
> ```js
> const decimalNumberRegex = new RegExp(/^\d+(,\d{0,2})*(\.\d{0,2})?$/, 'i');
> ```
> 
> 2. Replace https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/pages/iou/steps/IOUAmountPage.js#L239
>     with
> 
> ```js
> onPress={() => this.props.onStepComplete(this.state.amount.replace(',', '.'))}
> ```
> 
> 3. Remove all of the calls to `this.stripCommaFromAmount`
> 
> **Result:**
> 
>  cinnamon-20220625-1.mp4 
> **UPD** OK, i think i got confused, since the issue description is talking about the `Rate` input on Reimburce Expenses screen, while screenshot contains IOU Amount Page with an amount input. If the description is correct, we need to do the following:
> 
> 1. Replace https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/CONST.js#L668
>     with
> 
> ```js
> RATE_VALUE: /^\d{1,8}(\.\d*)*(\,\d*)?$/,
> ```
> 
> 2. Edit [updateRateValue](https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/pages/workspace/reimburse/WorkspaceReimburseView.js#L117) method in [WorkspaceReimburseView](https://github.com/Expensify/App/blob/main/src/pages/workspace/reimburse/WorkspaceReimburseView.js) so that it retains the separator the user has entered while sending a number with period to the server
> 
> ```js
>     updateRateValue(value) {
>         const numValue = parseFloat(value.replace(',', '.'));
> 
>         if (_.isNaN(numValue)) {
>             return;
>         }
> 
>         const rateToDisplay = value.includes(',') ? numValue.toFixed(3).replace('.', ',') : numValue.toFixed(3);
> 
>         this.setState({
>             rateValue: rateToDisplay,
>         });
> 
>         Policy.setCustomUnitRate(this.props.policyID, this.state.unitID, {
>             customUnitRateID: this.state.rateID,
>             name: this.state.rateName,
>             rate: numValue.toFixed(3) * 100,
>         }, null);
>     }
> ```
> 
> **Result:**
> 
>  cinnamon-20220625-2.mp4 
> On a side note, I personally think that updating input's value so that the number always has 3 digits after the separator looks suboptimal (notice that on the video). We could just delete `const rateToDisplay` and `setState` after that and the user's input will not be modified on the UI side. What do you think?

**Comment by eVoloshchak** [comment] 2022-06-27 19:03
> it needs to be more language dependent. Namely from the slack convo: `the decimal separator allowed should match the decimal separator of the selected language.` Meaning that the use of the separator should type should be dependent on the language currently selected.

We can do this in  [validateAmount](https://github.com/Expensify/App/blob/3f12c33f8a3e371c7f19ac6d0381932e8c46dc76/src/pages/iou/steps/IOUAmountPage.js#L121) method like this:
```diff 
validateAmount(amount) {
-   const decimalNumberRegex = new RegExp(/^\d+(,\d+)*(\.\d{0,2})?$/, 'i');
+   const decimalSeparator = this.props.fromLocaleDigit('.');
+   const decimalNumberRegex = RegExp(String.raw`^\d+([${decimalSeparator}]\d{0,2})?$`, 'i');
    return amount === '' || (decimalNumberRegex.test(amount) && this.calculateAmountLength(amount) <= CONST.IOU.AMOUNT_MAX_LENGTH);
}
```
And since we do not want to replace `,` with `.` on the UI side, change [updateAmount](https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/pages/iou/steps/IOUAmountPage.js#L165) method
```javascript
updateAmount(text) {
    this.setState((prevState) => {
        return this.validateAmount(text) ? {amount: text} : prevState;
    });
}
```
And [this](https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/pages/iou/steps/IOUAmountPage.js#L219) line
```diff
- formattedAmount={formattedAmount}
+ formattedAmount={this.state.amount}
```

And the same thing for [setRate](https://github.com/Expensify/App/blob/3f12c33f8a3e371c7f19ac6d0381932e8c46dc76/src/pages/workspace/reimburse/WorkspaceReimburseView.js#L88) method in `WorkspaceReimburseView.js`
```diff
setRate(value) {
-    const isInvalidRateValue = value !== '' && !CONST.REGEX.RATE_VALUE.test(value);
+    const decimalSeparator = this.props.fromLocaleDigit('.');
+    const rateValueRegex = RegExp(String.raw`^\d{1,8}([${decimalSeparator}]\d*)?$`, 'i');
+    const isInvalidRateValue = value !== '' && !rateValueRegex.test(value);
    this.setState(prevState => ({
        rateValue: !isInvalidRateValue ? value : prevState.rateValue,
    }), () => {
        // Set the corrected value with a delay and sync to the server
        this.updateRateValueDebounced(this.state.rateValue);
    });
}
```

I'm still not sure which one of the two screens needs to be fixed, so here's the video with both 

https://user-images.githubusercontent.com/9059945/176015992-ee82705f-6fe3-4f40-9cc6-5fe15c3fad79.mp4

**Comment by rushatgabhane** [comment] 2022-06-27 20:28
@eVoloshchak does you proposal also account the custom keyboard used on mobile?
We should display `,` instead of `.` over there right?

**Comment by eVoloshchak** [comment] 2022-06-27 21:12
> @eVoloshchak does you proposal also account the custom keyboard used on mobile? We should display `,` instead of `.` over there right?

It already displays `,` if you're on Spanish, but still appends `.` to the number. We need to change this line
https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/components/BigNumberPad.js#L66
```javascript
onPress={() => this.props.numberPressed(column === '<' ? column : this.props.toLocaleDigit(column))}
```

**Comment by sketchydroide** [comment] 2022-06-28 11:36
Yeah I think I'm happy with that solution @eVoloshchak 👍🏼

**Comment by Santhosh-Sellavel** [comment] 2022-06-28 17:34
> ##  Expected Result:
> User should be able to use comma, also the decimal should change to comma after changing the language to spanish.

Check the video [here](https://github.com/Expensify/App/issues/9497#issuecomment-1167763611)
In Spanish by default only `.` is shown. After modifying still `,` changes `.` in a second or two is this expected?

**Comment by eVoloshchak** [comment] 2022-06-28 20:05
> Check the video [here](https://github.com/Expensify/App/issues/9497#issuecomment-1167763611)
> On Reimburse expenses page. In Spanish by default only `.` is shown. After modifying still `,` changes `.` in a second or two is this expected?

That's how it works right now, I was talking about it [here](https://github.com/Expensify/App/issues/9497#issuecomment-1166304208)
> On a side note, I personally think that updating input's value so that the number always has 3 digits after the separator looks suboptimal (notice that on the video). We could just delete const rateToDisplay and setState after that and the user's input will not be modified on the UI side.

We can fix this if we delete [this](https://github.com/Expensify/App/blob/3f12c33f8a3e371c7f19ac6d0381932e8c46dc76/src/pages/workspace/reimburse/WorkspaceReimburseView.js#L124) line and limit number to 2 digits after the separator in regex
```diff
- `^\d{1,8}([${decimalSeparator}]\d*)?$`
+ `^\d{1,8}([${decimalSeparator}]\d{0,2}*)?$`
```

**Comment by sketchydroide** [comment] 2022-06-30 15:14
does that answer satisfy you @Santhosh-Sellavel?

**Comment by Santhosh-Sellavel** [comment] 2022-06-30 17:01
@sketchydroide 
Yeah looks good for me.

**Comment by sketchydroide** [comment] 2022-07-01 09:09
Ok I think we are happy with that then, I've assigned you to the GH @eVoloshchak

**Comment by kevinksullivan** [comment] 2022-07-06 22:27
Hired @eVoloshchak and @Santhosh-Sellavel on upwork.

**Comment by eVoloshchak** [comment] 2022-07-06 22:42
Will submit a PR tomorrow

**Comment by eVoloshchak** [comment] 2022-07-08 09:52
PR is up

**Comment by sketchydroide** [comment] 2022-07-18 13:27
this is being reviewed

**Comment by parasharrajat** [comment] 2022-07-20 18:17
Unfortunately, PR introduced many extra changes which were not required to fix this issue. These changes can further create confusion in the future. More https://github.com/Expensify/App/pull/9800#discussion_r925909157. 

@sketchydroide Could you please revert this PR and @eVoloshchak can send a new one with minimal required changes.

**Comment by Santhosh-Sellavel** [comment] 2022-07-20 19:16
@sketchydroide 

Yeah, @parasharrajat is correct!
Issue description introduced some unnecessary confusion.

Also retested PR once again. Found we are still missing handling entering `,` iOS & mWeb(iOS) in Reimburse page.
@eVoloshchak Need to handle this case also, in the upcoming PR.  

### Earlier tested without toggling software keyboard, it works fine. Check out the video from the PR #9800 description.

https://user-images.githubusercontent.com/85645967/180062973-a7c1b02e-c7c3-4f41-b8a0-c0d85b4143ab.mp4

### But with keyboard enabled, we are still unable to enter `,`:

![Simulator Screen Shot - iPhone 13 - 2022-07-21 at 00 25 13](https://user-images.githubusercontent.com/85645967/180063797-ece5a91f-39b3-4907-a3c8-1d3651ae798f.png)

**Comment by eVoloshchak** [comment] 2022-07-20 19:28
> Also retested PR once again. Found we are still missing handling entering `,` iOS & mWeb(iOS) in Reimburse page. @eVoloshchak Need to handle this case also, in the upcoming PR.

Will do, thank you. I think this will require changing `keyboardType` depending on the current decimal separator in [AmountTextInput](https://github.com/Expensify/App/blob/025dcf7c61f084da1f625b3aee66ef73b3e0060e/src/components/AmountTextInput.js#L40)

**Comment by eVoloshchak** [comment] 2022-07-25 04:10
@sketchydroide, could you please revert https://github.com/Expensify/App/pull/9800?

**Comment by parasharrajat** [comment] 2022-07-26 15:53
A regression was found https://github.com/Expensify/App/issues/9497 from this issue's PR so let's move to revert that PR and solve that issue as well.

**Comment by Santhosh-Sellavel** [comment] 2022-07-26 16:07
@parasharrajat  can you link the correct issue here.

**Comment by Santhosh-Sellavel** [comment] 2022-07-27 15:00
@eVoloshchak PR has been reverted.

**Comment by eVoloshchak** [comment] 2022-07-27 15:32
> @eVoloshchak PR has been reverted.

Started working on the PR.
I'm trying to tackle https://github.com/Expensify/App/issues/10108 and there [seems to be no keyboard type](https://betterprogramming.pub/12-shades-of-keyboard-types-in-ios-a413cf93bf4f) on iOS that features comma instead of period with numbers. We are using type `decimal-pad`. Instead, it is locale dependent. If user has their phone's language set to Spanish, decimal keyboard will have a comma instead of period
![Screenshot from 2022-07-27 18-21-28](https://user-images.githubusercontent.com/9059945/181287810-93a72da4-5b04-46c9-b79b-e5cafd205c2d.png)

However, if someone was to have a phone set to English with a New Expensify app set Spanish, that would create a problem. What should I do here?

**Comment by Santhosh-Sellavel** [comment] 2022-07-27 15:38
@eVoloshchak Let's get others thoughts on slack can you create a thread there.

**Comment by eVoloshchak** [comment] 2022-07-27 15:50
Created [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1658936908481629)

**Comment by Santhosh-Sellavel** [comment] 2022-08-05 17:58
@eVoloshchak How/which Spanish language did you set to get this keyboard with a comma, can you share the recording for the same?

![image](https://user-images.githubusercontent.com/85645967/183133926-9e7632fb-36de-4786-90cf-c5bbbf471b51.png)

**Comment by eVoloshchak** [comment] 2022-08-05 20:46
> @eVoloshchak How/which Spanish language did you set to get this keyboard with a comma, can you share the recording for the same?


https://user-images.githubusercontent.com/9059945/183159997-af76270b-ac0e-4b1f-80bf-0a2eb5918ca8.mp4

**Comment by Santhosh-Sellavel** [comment] 2022-08-08 17:03
But I'm not seeing a comma there,

https://user-images.githubusercontent.com/85645967/183473172-f4504ab1-9356-48ec-9217-4947e1affc1b.mp4

**Comment by Santhosh-Sellavel** [comment] 2022-08-11 21:25
@eVoloshchak Bump

**Comment by eVoloshchak** [comment] 2022-08-12 09:29
> Any update on this issue

It seems like a consensus has been [achieved](https://expensify.slack.com/archives/C01GTK53T8Q/p1659980975008289?thread_ts=1658936908.481629&cid=C01GTK53T8Q):

> Android can show both symbols, so there we can just treat each like the configured locale in the app would (ie: if you have english, it would treat . as decimal, if you have spanish it would treat, as decimal.
For iOS it always shows the phone's locale decimal symbol, so we know it will only have one symbol and whichever symbol that is, is the decimal separator and parse it accordingly.

So we accept both signs on IOS and only the correct one on Android. I'll submit a PR shortly

**Comment by eVoloshchak** [comment] 2022-08-20 17:04
PR is up

**Comment by kevinksullivan** [comment] 2022-09-13 19:35
PR in review.

**Comment by Santhosh-Sellavel** [comment] 2022-10-03 17:10
@kevinksullivan bump!

**Comment by thesahindia** [comment] 2022-10-06 08:06
> @thesahindia please accept this reposted job to get paid for reporting.

Applied to the job. Thanks.

**Comment by Santhosh-Sellavel** [comment] 2022-10-06 19:53
@kevinksullivan Can you close this issue and the other issue https://github.com/Expensify/App/issues/10108 as this same problem mentioned here https://github.com/Expensify/App/issues/9497#issuecomment-1190658490 and it is fixed now, thanks!

**Closed** 2022-10-07 14:42 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment
