### ISSUE TITLE
[LOW] [Splits] [$500] IOU - Error message not displaying when attempting to enable internet after requesting money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35009] opened 2024-01-23 21:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with 2 separate accounts in the main testing device and a secondary device
2. Disable the internet connection in the main testing device
3. From the main + menu, create a money request with the account logged in the secondary device
4. In the secondary device request money with same amount to the main testing device account
5. Enable the internet connection in in the main testing device, the money request request will be sent and will get a response an error.
6. Verify that the chat row in the LHN appears greyed out with a solid red dot icon

## Expected Result:
Error should be displayed and amount 0.00 should not displayed

## Actual Result:
Error message not displaying when attempting to enable internet after requesting money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/972afaad-4d5b-4178-8bb7-941bb0d298ef

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018701e9c338519f96</li>
        <li>Upwork Job ID: 1749909488235212800</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-23 21:39
We think that this bug might be related to #wave5. 
CC @DylanDylann

**Comment by shubham1206agra** [comment] 2024-01-30 04:26
No proposals to review yet.

**Comment by shubham1206agra** [comment] 2024-02-06 15:29
Still no proposal.

@sonialiap Can you please put this in some wave?

**Comment by rezkiy37** [comment] 2024-02-13 14:47
I can confirm that the bug is still replicable. Before, I want to clarify: _Expected Result: **Error** should be displayed..._. What's an error do you mean? What's a reason to have an error here? Two users want to request money from each other. 

I've investigated the behaviour. There is a bug that the backend returns a `total` value as "0" (_zero_) of a `report`. So, for the 1st user (_offline one_), the backend returns the value on a **RequestMoney** command. For the 2nd user, the backend sends the value via the **Pusher**. Looks like it is a root cause of the bug. 

https://github.com/Expensify/App/assets/57314631/b56f7145-78f0-4357-ab09-ef4f876f2211

**Comment by sonialiap** [comment] 2024-02-15 16:36
Thanks for the investigation @rezkiy37! Remind me, does Callstack work on the backend? If not, I'll see about getting an internal engineer to work on this

**Comment by rezkiy37** [comment] 2024-02-15 16:47
Callstack does not work on the backend.

**Comment by sonialiap** [comment] 2024-02-19 16:40
Waiting for issue to be picked up

**Comment by sonialiap** [comment] 2024-02-21 21:41
It's an internal issue, waiting for an engineer to have space to pick it up

**Comment by rezkiy37** [comment] 2024-02-26 10:31
No update. Still waiting.

**Comment by sonialiap** [comment] 2024-02-26 14:46
Still looking for an internal engineer

**Comment by sonialiap** [comment] 2024-02-29 10:45
I'm going to move this to weekly while we wait for engineering to pick this up

**Comment by sonialiap** [comment] 2024-03-11 12:34
Waiting for internal engineer

**Comment by rezkiy37** [comment] 2024-03-15 15:51
Hey!
I must inform you that I have a vacation next week. I will be back on Monday 25.03. During the vacation, someone from Callstack can take the issue to work. See you soon!

**Comment by mvtglobally** [comment] 2024-03-20 03:16
Issue not reproducible during KI retests. (First week)

**Comment by sonialiap** [comment] 2024-03-26 18:28
@rezkiy37 hope your OOO was good! Are you still able to work on this?

**Comment by rezkiy37** [comment] 2024-03-27 09:47
Hey!
Yes, I am still able to work on this. Just to clarify: I already posted my [summary](https://github.com/Expensify/App/issues/35009#issuecomment-1941679676). We were waiting for an internal developer to help.

**Comment by sonialiap** [comment] 2024-04-09 13:37
Waiting for internal engineer to join in

**Comment by sonialiap** [comment] 2024-04-18 11:38
Low priority, still waiting for an engineer

**Comment by rezkiy37** [comment] 2024-04-26 13:45
Hey!
I just wanted to let you know about my vacation for next week. I will be back on 06.05.2024. Meanwhile, I asked @waterim to take over this issue. 
See you soon!

**Comment by sonialiap** [comment] 2024-04-30 12:33
Still looking for internal engineer but priority is low

**Comment by mvtglobally** [comment] 2024-05-01 13:58
Issue not reproducible during KI retests. (Second week)

**Comment by sonialiap** [comment] 2024-05-14 22:29
I also cannot reproduce this. Closing

**Closed by sonialiap** 2024-05-14 22:29 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug, Hot Pick
