### ISSUE TITLE
[$500] Web- Split bill - Unable to split the money with new users in a group

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20964] opened 2023-06-17 12:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Create a group with non-existing users
3. Go to that group chat and click on + and click on split bill , enter the amount and click on split money button
4. Notice that the split button doesn't work

## Expected Result:
Able to split the money with new users in a group

## Actual Result:
Unable to split the money with new users in a group

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f2598c55-abe6-4d5d-bd8b-9ad31ff6adca

https://github.com/Expensify/App/assets/93399543/08d1eed4-4f7e-4967-910a-3eddc9364b58

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686993012583369
https://expensify.slack.com/archives/C049HHMV9SM/p1686991867243109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a34b44e2ad9be2a6</li>
        <li>Upwork Job ID: 1714382223552339968</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-06-19 19:10
Related [thread](https://expensify.slack.com/archives/C07J32337/p1687190132734579). We couldn't reproduce on staging. Closing.

**Comment by kbecciv** [comment] 2023-10-13 14:06
Issue is reproducible on build 1.3.83.10

Uploading Recording #4982.mp4…

**Comment by stitesExpensify** [comment] 2023-10-13 20:57
@kbecciv is this only on staging? If so I'll re-add the blocker label

**Comment by stitesExpensify** [comment] 2023-10-13 22:12
cc @mountiny since I know you were working on this

**Comment by mountiny** [comment] 2023-10-15 11:59
I have just retested on 1.3.84 and could not repro with non-existing expensifail first time and then with non-existing gmail accounts and it worked fine. 

Adding Needs Reproduction label

cc @luacmartins and @youssef-lr in case you would run into this

**Comment by youssef-lr** [comment] 2023-10-19 09:39
>We should add participant.text also in the above line similar to here

This won't work if the user has set a display name in their profile, as `text` will equal `John Doe` for example. I think we shouldn't allow adding a user to the split if their `login` is missing and their `text` prop is not a valid email. @c3024 have you tried your solution by having one of the participant set their display name?

**Comment by c3024** [comment] 2023-10-19 10:26
@youssef-lr 
You are right. i did not check with one of the participants setting their display name. It will fail.

Disallowing splitting a bill with a user without login may also be not a good idea in my opinion. We can create a group with unknown users and composer menu has one of the options as split bill. Disabling it when one of the members has their login hidden from the user appears wacky to me.

Fixing it from the backend is ideal. I think there is no need to pass email to the backend and at the least the backend should not validate the email.

**Comment by youssef-lr** [comment] 2023-10-19 10:29
I think we can do both:

1. For known users when we have `login` set, send the email
2. For unknown users with a display name, send the accountID
3. For unknown users without a display name, send the email from the text prop.

**Comment by c3024** [comment] 2023-10-19 10:49
As far as I understand, here
https://github.com/Expensify/App/blob/0d11e0b3b07488ff11ad69a78800a0995733f07a/src/libs/actions/IOU.js#L1179-L1181
we send both `email` and `accountID` and backend validates both and throws an error if either of them is not sent.
> For unknown users with a display name, send the accountID

So, I think we cannot do this (that is send `accountID` alone) unless we change the logic of backend to make email optional.

**Comment by youssef-lr** [comment] 2023-10-19 10:50
>So, I think we cannot do this (that is send accountID alone) unless we change the logic of backend to make email optional.

Yeah I can work on it.

**Comment by c3024** [comment] 2023-10-19 10:56
Then we can change this to send an empty string when `login` does not exist for a user with something like this
```
const email = isOwnPolicyExpenseChat || isPolicyExpenseChat || !participant.login ? '' : OptionsListUtils.addSMSDomainIfPhoneNumber(participant.login).toLowerCase();
```

**Comment by youssef-lr** [comment] 2023-10-21 13:41
Closing this one in favor of https://github.com/Expensify/App/issues/23470. Backend PR should be ready shortly, there's no changes required in App, but I'll create a small cleanup PR and add some comments.

**Closed by youssef-lr** 2023-10-21 13:41 UTC
Labels: External, Engineering, Weekly, Improvement, Needs Reproduction, Bug
