### ISSUE TITLE
[$500] [Awaiting payment]The formatting of the time is zero-prefixed

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#25650] opened 2023-08-22 03:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Navigate to any chat 
3. Check timezone display 

## Expected Result:
The formatting of the time should not be zero-prefixed

## Actual Result:
The formatting of the time is zero-prefixed

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**   1.3.56-2
**Reproducible in staging?:** Y  
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

![image - 2023-08-21T233446 040](https://github.com/Expensify/App/assets/43995119/e12b1459-50b5-4aba-8e86-c895fb9d4a39)
![Screen Shot 2023-08-21 at 11 39 48 PM](https://github.com/Expensify/App/assets/43995119/dee0758f-f438-466b-a771-bac2460047ea)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692671896444999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b09a40192967b0dd</li>
        <li>Upwork Job ID: 1699744670108016640</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-08-22 04:49
As https://github.com/Expensify/App/pull/24446 is within regression period, they will be handling this

**Comment by MonilBhavsar** [comment] 2023-08-22 07:57
@waterim since this was a regression, do you mind if I assign you to this issue and you can make a quick fix?

**Comment by waterim** [comment] 2023-08-22 09:23
@MonilBhavsar yes, sure, Im taking this one, thank you for the mention

**Comment by MonilBhavsar** [comment] 2023-08-22 09:25
Thank you! Happy to review the PR.

**Comment by waterim** [comment] 2023-08-22 09:25
@MonilBhavsar do I need to write a proposal here? Because this change is just removing one char from the time CONST

**Comment by MonilBhavsar** [comment] 2023-08-22 09:26
That's fine 👍

**Comment by mountiny** [comment] 2023-08-22 11:12
Assigning @allroundexperts coming from the original PR https://github.com/Expensify/App/pull/24446

**Comment by waterim** [comment] 2023-08-22 11:26
[PR](https://github.com/Expensify/App/pull/25665) is ready for a review :)

**Comment by MonilBhavsar** [comment] 2023-08-23 18:51
QA ✅ 

<img width="1727" alt="Screenshot 2023-08-24 at 12 21 13 AM" src="https://github.com/Expensify/App/assets/32012005/195635e9-4673-4986-851c-b5b5b9c037de">

**Comment by MonilBhavsar** [comment] 2023-09-01 11:36
The PR was deployed to production. We can issue the payment to C+ and close this issue

**Comment by laurenreidexpensify** [comment] 2023-09-07 11:22
Woops forgot @allroundexperts was on the C+ payment pilot

**Comment by laurenreidexpensify** [comment] 2023-09-07 11:23
@MonilBhavsar just to be clear - is there no C payment here, it's only $1000 for @allroundexperts is that corretc?

**Comment by MonilBhavsar** [comment] 2023-09-07 12:02
Correct, contributor - `@waterim` are from expert agency. Also just to note, this was a regression from https://github.com/Expensify/App/pull/24446

**Comment by MonilBhavsar** [comment] 2023-09-11 09:54
@laurenreidexpensify is partially ooo today

**Comment by laurenreidexpensify** [comment] 2023-09-12 09:45
Payment summary:

- bug report internal $0
- C fix - expert contributor $0
- C+ review - @allroundexperts pls request $1000 in newdot 

When @allroundexperts confirms payment has been requested we can close

**Closed** 2023-09-13 08:58 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
