### ISSUE TITLE
[HOLD for payment 2024-05-20]  iOS - Wallet - Missing up and down key and Done button in the header of account selection list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40126] opened 2024-04-11 15:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to Profile > Wallet
3. Add a personal bank account
4. After returning to ND from Plaid, note the header in account selection list

## Expected Result:
There will be up and down button and the word "Done" in the header in account selection list (screenshot from 1.4.61-8)

## Actual Result:
The header in account selection list is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e28ea7bb-2369-4dcd-a9f7-e5294e40f206

![Bug6445965_1712846010774!1 4 62-3](https://github.com/Expensify/App/assets/78819774/032f524a-2738-4828-a8f2-3ec6d1725127)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by lanitochka17** [comment] 2024-04-11 15:46
@luacmartins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-11 15:47
We think that this bug might be related to #wave-collect - Выпуск 1

**Comment by luacmartins** [comment] 2024-04-11 16:31
I think we can demote this to NAB and make it external, since the functionality is not broken.

**Comment by MrMuzyk** [comment] 2024-04-12 07:46
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

I see one effective alternative solution straight away here but we would need someone from UX team to speak on that. A while ago we've refactored BA flow and where we replaced this picker with a list of radio buttons. I can see in the codebase that we're already using this radio buttons list in [2 of 3 places](https://github.com/Expensify/App/blob/main/src/components/AddPlaidBankAccount.tsx#L262) if I'm not mistaken and Wallet is the only place left where we're using the old picker component. What could be done is we could drop the picker completely and move to this new design of list of radio buttons like on the screenshot - 

<img width="376" alt="image" src="https://github.com/Expensify/App/assets/23487612/d9b570e2-4df0-41a7-8d87-266acb35a8c0">

**Comment by luacmartins** [comment] 2024-04-15 14:34
@thesahindia did you get a chance to look at the proposals above?

**Comment by MrMuzyk** [comment] 2024-04-16 10:33
>I think we need to fix this bug anyway
>Because this problem is relevant for ALL pickers (Not only the account selection list)

If the issue exists for all picker then I agree - we should apply a fix for that too. Maybe it is also worth considering dropping usage of them completely - after all they have been dropped in other places. At the moment counting this one in wallet we have 3 usages of `<Picker/>`

**Comment by MrMuzyk** [comment] 2024-04-17 08:08
I've made a few screenshots to showcase the difference

| Before  | After |
| ------------- | ------------- |
|  <img width="1920" alt="wallet_before" src="https://github.com/Expensify/App/assets/23487612/5bd36068-ab6c-4151-8e60-fe5ea84aa7b8">  | <img width="1920" alt="wallet after" src="https://github.com/Expensify/App/assets/23487612/345a6cfc-cd33-4041-8d10-bc987fb47f3c">  |
| <img width="1920" alt="footer_before" src="https://github.com/Expensify/App/assets/23487612/fd576bbc-b378-4aa0-84c0-c92c08b8b506">  | <img width="1920" alt="footer_after" src="https://github.com/Expensify/App/assets/23487612/1eae5092-d7d5-415d-ab1e-e9446b8bff07">  |
| <img width="1920" alt="footer_before_2" src="https://github.com/Expensify/App/assets/23487612/e6ef1828-f7a0-4dac-b070-63bb803e28f3"> | same as above  |

Turns out that there are actually 2 usage and not 3. 3rd usage is here

https://github.com/Expensify/App/blob/21ee1a3772253538bba74b2bc655213dc7bdb68a/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.tsx#L142

but when I've tried to search for this spot in the actual app I've found out that this page (`WorkspaceRateAndUnitPage`) is not used anywhere in the code and can be removed alltogether

**Comment by luacmartins** [comment] 2024-04-17 15:39
@Expensify/design would love your thoughts on the Picker changes above. I think it's fine on the RHP, but the login page language selection looks odd to me.

**Comment by dannymcclain** [comment] 2024-04-17 16:07
I'm a big fan of moving to the radio options instead of the picker in the RHP for this. I honestly didn't even know we had any actual pickers in the product!

The login page/footer language select is pretty rough as radio buttons, so I think we should just leave that one alone for now.

Curious for the other designers' thoughts.

**Comment by shawnborton** [comment] 2024-04-17 16:16
Before we go too far with this, I think we're in the process of redoing this entire flow, check this out: https://github.com/Expensify/App/issues/36648

So perhaps we can just close this out as we're changing how we display accounts to be something more like this:
![image](https://github.com/Expensify/App/assets/2319350/b4ab8ff0-4577-483a-9397-03832641d72b)

**Comment by shawnborton** [comment] 2024-04-17 16:16
cc @mountiny @koko57

**Comment by dubielzyk-expensify** [comment] 2024-04-18 03:00
Agree that the radios are nice, but Shawns comment makes sense

**Comment by luacmartins** [comment] 2024-04-18 17:21
I'm not sure we're covering that in other issues. I agree that we should update the remaining pickers though.

**Comment by mountiny** [comment] 2024-04-20 19:16
I think I agree with @shawnborton that we could cover this in the wallet flow refactor, but also since there are other places where we should fix it, we might as well just fix it everywhere here.

**Comment by luacmartins** [comment] 2024-04-22 23:48
I think we can keep it in this issue since we have other places that need to be updated.

**Comment by luacmartins** [comment] 2024-04-26 16:54
Correct, except for the ones on the login page

**Comment by kevinksullivan** [comment] 2024-04-29 21:57
Adding to vip-split

**Comment by luacmartins** [comment] 2024-04-30 14:29
@MrMuzyk your proposal looks good.

**Comment by MrMuzyk** [comment] 2024-04-30 14:46
I will implement this once I'm back after long weekend I'm starting today (will be back 06.05)

**Comment by kevinksullivan** [comment] 2024-05-21 22:02
Confirmed summary is accurate. @thesahindia can you finish out the checklist above?

**Comment by JmillsExpensify** [comment] 2024-05-31 04:19
$250 approved for @thesahindia

**Comment by luacmartins** [comment] 2024-06-03 23:50
Are we good to close this one?

**Comment by luacmartins** [comment] 2024-06-04 14:41
Awesome! Thanks everyone!

**Closed by luacmartins** 2024-06-04 14:41 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
