### ISSUE TITLE
[$1000]  Title, Description, & Assignee fields are not dynamically disabled when an admin changes announce room's 'Who can post' setting to 'admins only'

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24335] opened 2023-08-09 17:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a tab where user A is signed in
2. Create a workspace & invite user B to the workspace
3. Navigate to announce room of the newly created workspace
4. Click on '+' icon > click on 'Assign task' > enter title & description > click on 'Next' >
5. Click on 'Confirm task'
6. Open a tab where user B is signed in
7. Open the announce room
8. Click on 'Task preview component'
9. Open a tab where user A is signed in
10. And change 'Who can post' setting of the announce room to 'Admins only'
11. Switch to the tab where user B is signed in

## Expected Result:
'Title', 'Description' & 'Assignee' fields should dynamically be disabled

## Actual Result:
 'Title', 'Description' & 'Assignee' fields are not dynamically disabled, but 'Mark as done' button is grayed out & three-dot icon has disappeared from the header dynamically

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/993ae0c7-5d2d-4c6a-9ae6-6a20100b4549

![Screenshot from 2023-08-02 22-08-29 (1)](https://github.com/Expensify/App/assets/43995119/eb17e434-d76a-4c36-8f73-fc1c283a38ef)

https://github.com/Expensify/App/assets/43995119/8276113b-e54f-4691-b40a-f97b456551a4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691003022572809 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128b84b09cbdee7d2</li>
        <li>Upwork Job ID: 1691099442708291584</li>
        <li>Last Price Increase: 2023-08-14</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2023-08-10 11:00
Reviewing today!

**Comment by dylanexpensify** [comment] 2023-08-11 10:15
[gut check](https://expensify.slack.com/archives/C01SKUP7QR0/p1691748884559589)

**Comment by dylanexpensify** [comment] 2023-08-11 17:02
not a bug because now the task report is separate from the announce room and they’re assigned to it which means they have responsibility over that task

**Comment by Natnael-Guchima** [comment] 2023-08-11 17:12
Also, the mark as done button on the header is dynamically updated to disabled state, creating inconsistency between the header and the body of the report.

**Comment by dylanexpensify** [comment] 2023-08-14 14:48
@thienlnam confirmed valid so reopening!

**Comment by dylanexpensify** [comment] 2023-08-16 13:42
@Ollyws to review proposals!

**Comment by dylanexpensify** [comment] 2023-08-17 09:38
@Ollyws mind if we get an update today? TY!

**Comment by dylanexpensify** [comment] 2023-08-21 08:42
reviewing today!

**Comment by dylanexpensify** [comment] 2023-08-21 10:23
Agree

**Closed by dylanexpensify** 2023-08-21 10:23 UTC
Labels: External, Daily, Help Wanted, Bug
