### ISSUE TITLE
[$1000] Do not update IOU total when IOU requests are submitted offline and the currency differs from the iouReport currency

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#12433] opened 2022-11-03 16:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money from a user in USD, `+ > Request money`
2. Go offline
3. Send another money request, but this time set a different currency, e.g. AED
4. Notice that the IOU preview just sums up the amount in USD and AED, without considering the exchange rate so the USD total displayed is incorrect
5. Go online and notice that the total is updated to the correct USD amount

https://user-images.githubusercontent.com/22219519/199781387-6e0356c0-7edc-49dc-8392-7a7cb2470403.mov

## Expected Result:
1. Coming from [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1667416017878019), we [decided](https://expensify.slack.com/archives/C01GTK53T8Q/p1667432246944119?thread_ts=1667416017.878019&cid=C01GTK53T8Q) that the total amount should not be updated if offline requests are submitted in a currency that is different than the currency on the iou report.
2. Additionally, if the iouReport has requests in different currencies and the user is offline, we should disable the Pay button cc @youssef-lr @sketchydroide since you are working on the Pay IOU flow refactors.

## Actual Result:
Amount is summed up without taking the exchange rate into consideration

## Workaround:
N/A

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01b90cfcf16c439e37
- Upwork Job ID: 1594935940044496896

**Comment by JmillsExpensify** [comment] 2022-11-04 21:35
Looks like the `Internal` issue doesn't randomly assign yet, so I've added the `Engineering` label in it's place.

**Comment by JmillsExpensify** [comment] 2022-11-04 21:37
For context, this is a high-value bug in conjunction with API Unchained.

**Comment by youssef-lr** [comment] 2022-11-04 23:17
@luacmartins just pushed a fix for this one, I'm curious if I missed anything as it was a relatively simple change.

**Comment by luacmartins** [comment] 2022-11-05 00:15
Nice! I'll review it on monday!

**Comment by JmillsExpensify** [comment] 2022-11-06 01:09
Thanks for the quick work @youssef-lr!

**Comment by JmillsExpensify** [comment] 2022-11-08 19:26
On-going review in the linked PR.

**Comment by NikkiWines** [comment] 2022-11-09 19:45
Unassigning myself since looks like @youssef-lr has a fix for this 👋

**Comment by youssef-lr** [comment] 2022-11-14 13:03
Waiting for @rushatgabhane's testing.

**Comment by JmillsExpensify** [comment] 2022-11-14 18:44
Nice work! @rushatgabhane now that you're unblocked on testing, will you be able to handle in the coming days?

**Comment by JmillsExpensify** [comment] 2022-11-17 05:05
Thanks @youssef-lr! I need to make time for the regression test, as I think we should add one for this case. I ran out of time today though.

**Comment by JmillsExpensify** [comment] 2022-11-22 06:07
Alright, time to circle back on the testing script. I posted a recommended update for our [TestRail IOU](https://expensify.testrail.io/index.php?/cases/view/1971032&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=229063) test [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1669097166394829).

**Comment by JmillsExpensify** [comment] 2022-11-22 06:09
In the meantime, @rushatgabhane it looks like you helped on the linked PR. I went ahead and temporarily added external so that we could get an Upwork job created. Posting is above!

**Comment by JmillsExpensify** [comment] 2022-11-27 05:44
Hired @rushatgabhane via Upwork. I'll circle back tomorrow to confirm he's been able to accept and issue payment.

**Comment by JmillsExpensify** [comment] 2022-11-27 20:29
Nice, paid via Upwork!

**Comment by JmillsExpensify** [comment] 2022-11-29 05:59
Ok the regression test has been added. @youssef-lr please comment in the linked PR in case I missed anything. Everything else is checked off, so I think we're done here! Closing.

**Closed by JmillsExpensify** 2022-11-29 05:59 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
