### ISSUE TITLE
Unable to login with non-existing account that owes money

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45252] opened 2024-07-11 11:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
User B has no account yet

Steps:
1. User A with gmail account go to FAB> Submit expense> Add User B email address> Complete the submit flow
2. Wait for a minute
3. Repeat step 1 to submit a second IOU to user B
4. As User B go to staging.new.expensify.com> Type email address and click Continue

## Expected Result:
User B should be able to login

## Actual Result:
Unable to login with non-existing account that owes money. "Cannot get account details, please try again or contact [concierge@expensify.com"](mailto:concierge@expensify.com%22)
error message is displayed on login page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/872b29f0-30b0-4b20-a74b-60a54ff87f14

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017518e8ff7a1d7f72</li>
        <li>Upwork Job ID: 1811408479840104416</li>
        <li>Last Price Increase: 2024-07-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by joekaufmanexpensify** [comment] 2024-07-11 14:33
I can reproduce this, but only specifically when submitting two IOUs to someone hasn't created an account yet. If I only submit one, I have no problem logging into the new account. 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/54866469/e3b23111-a674-4fd0-a00a-a2fa86111d59">

**Comment by joekaufmanexpensify** [comment] 2024-07-11 14:33
That said, this is a pretty bad bug for a core flow, so makes sense to me to fix now.

**Comment by kabeer95** [comment] 2024-07-11 21:22
okay

**Comment by kabeer95** [comment] 2024-07-11 21:30
Problem Statement: The problem we are trying to solve is that when a user attempts to log in with a non-existing account that owes money, the system does not handle the situation correctly, leading to a poor user experience.

Root Cause: The root cause of this problem is that the current login system does not have a mechanism to detect and handle cases where a user attempts to log in with a non-existing account that owes money. This lack of error handling and recovery flow leads to a poor user experience and potential frustration.

Proposed Solution: To solve this problem, I propose the following changes:

Implement robust error handling to detect when a user attempts to log in with a non-existing account that owes money.
Display clear and concise error messaging to the user, indicating that the account does not exist or that there is an outstanding balance.
Redirect the user to a recovery flow, where they can recover their account or resolve the outstanding balance.
Alternative Solutions Explored:

Soft Delete: Instead of completely removing the account, we could implement a soft delete mechanism that marks the account as inactive but still retains the account information. This would allow users to recover their account and resolve the outstanding balance.
Account Lookup: We could implement an account lookup feature that allows users to search for their account and recover it if it exists. This would provide an additional recovery path for users who have forgotten their login credentials.
Grace Period: We could introduce a grace period for accounts with outstanding balances, allowing users to log in and resolve the balance within a certain timeframe before the account is marked as non-existent.
These alternative solutions were explored, but the proposed solution was deemed the most effective and efficient way to solve the problem.
# Error handling mechanism
if user_account_exists and user_owes_money:
    # Display clear error message
    error_message = "Account does not exist or has an outstanding balance. Please recover your account or resolve the balance."
    # Redirect to recovery flow
    redirect_to_recovery_flow(error_message)
else:
    # Normal login flow
    login_user()

**Comment by kabeer95** [comment] 2024-07-11 21:34
Problem Statement: The problem we are trying to solve is that when a user attempts to log in with a non-existing account that owes money, the system does not handle the situation correctly, leading to a poor user experience.

Root Cause: The root cause of this problem is that the current login system does not have a mechanism to detect and handle cases where a user attempts to log in with a non-existing account that owes money. This lack of error handling and recovery flow leads to a poor user experience and potential frustration.

Proposed Solution: To solve this problem, I propose the following changes:

Implement robust error handling to detect when a user attempts to log in with a non-existing account that owes money.
Display clear and concise error messaging to the user, indicating that the account does not exist or that there is an outstanding balance.
Redirect the user to a recovery flow, where they can recover their account or resolve the outstanding balance.
Alternative Solutions Explored:

Soft Delete: Instead of completely removing the account, we could implement a soft delete mechanism that marks the account as inactive but still retains the account information. This would allow users to recover their account and resolve the outstanding balance.
Account Lookup: We could implement an account lookup feature that allows users to search for their account and recover it if it exists. This would provide an additional recovery path for users who have forgotten their login credentials.
Grace Period: We could introduce a grace period for accounts with outstanding balances, allowing users to log in and resolve the balance within a certain timeframe before the account is marked as non-existent.
These alternative solutions were explored, but the proposed solution was deemed the most effective and efficient way to solve the problem.

**Comment by joekaufmanexpensify** [comment] 2024-07-12 13:36
Still pending proposals

**Comment by jaydamani** [comment] 2024-07-12 17:24
The request for new account with IOU and without IOU looks same. So could this be a back-end issue?

Request for user with IOU (error):
```
email: xxxxx@proton.me
useNewBeginSignIn: true
apiRequestType: read
referer: ecash
platform: web
api_setCookie: false
isFromDevEnv: false
appversion: 9.0.6-2
clientUpdateID: -1
```
Response:
```json
{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Libs\\Error\\ExpError",
    "UUID": "9882CD0B-BC6B-46E8-951D-A633A1678314",
    "message": "Cannot get account details, please try again or contact concierge@expensify.com",
    "title": "",
    "data": {
        "onyxData": [
            {
                "onyxMethod": "merge",
                "key": "account",
                "value": {
                    "errors": {
                        "1720803445531455": "Cannot get account details, please try again or contact concierge@expensify.com"
                    }
                }
            }
        ]
    },
    "htmlMessage": "",
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "account",
            "value": {
                "errors": {
                    "1720803445531455": "Cannot get account details, please try again or contact concierge@expensify.com"
                }
            }
        }
    ],
    "requestID": "8a22927d3db1032e-AMD"
}
```

Request without IOU (no error):
```
email: xxxxxxx+aslfdk@proton.me
useNewBeginSignIn: true
apiRequestType: read
referer: ecash
platform: web
api_setCookie: false
isFromDevEnv: false
appversion: 9.0.6-2
clientUpdateID: -1
```
Response:
```json
{
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "credentials",
            "value": {
                "login": "xxxxxx+aslfdk@proton.me"
            }
        },
        {
            "onyxMethod": "merge",
            "key": "account",
            "value": {
                "validated": false,
                "primaryLogin": "",
                "accountExists": false,
                "domainControlled": false
            }
        }
    ],
    "jsonCode": 200,
    "requestID": "8a2292e37dd8032e-AMD"
}
```
Also noticed that the Pay button in the email send to user without account does not work, the sign-in request fails with error: "402 Invalid request, this command shouldn't get called for open accounts"

**Comment by jaydamani** [comment] 2024-07-12 17:36
Contributor details
Your Expensify account email: jaydamani567@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01334afe3f5f15353e?mp_source=share

**Comment by joekaufmanexpensify** [comment] 2024-07-15 15:06
@mkhutornyi, what do you think? Do you agree this could be a backend issue?

**Comment by joekaufmanexpensify** [comment] 2024-07-17 13:11
Hmm, okay. I will try and reproduce again today

**Comment by joekaufmanexpensify** [comment] 2024-07-17 14:31
@mkhutornyi did you specifically try and submit two IOUs to the account that did not exist? When I [did that](https://github.com/Expensify/App/issues/45252#issuecomment-2223099756) the other day, and again this morning I can still reproduce.

https://github.com/user-attachments/assets/abdeae76-7bb0-4aab-8043-26e2c145b35a

**Comment by joekaufmanexpensify** [comment] 2024-07-17 14:31
Updated repro steps to clarify you need yo submit two IOUs

**Comment by Julesssss** [comment] 2024-07-19 14:36
[Example](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228a5b263b5ea04ce9-BOS%22)+AND+timestamp:[2024-07-19T12:44:59.486Z+TO+2024-07-19T14:44:59.486Z]&index=logs_expensify-029452) query seems to show an invalid value of the `clientUpdateID` query param:

```
Malformed REQUEST: 'clientUpdateID' = '-1', ignoring (should match '\d{1,10}').
```

**Comment by roryabraham** [comment] 2024-07-19 22:37
@danieldoglas will probably know the most about this. It was originally added in the front-end with a default value of `0` in [this PR](https://github.com/Expensify/App/pull/43463/files).

Then it was changed to `-1` in [this PR](https://github.com/Expensify/App/pull/43654).

One thing I notice is that the intention of [this PR](https://github.com/Expensify/App/pull/43463/files) appears to have been to include `clientUpdateID` in write requests only (including `makeRequestWithSideEffects`, because that can act as a write). However, at the time that PR was added, `API.read` was just a wrapper around `API.makeRequestWithSideEffects`. So as soon as that PR was merged, `clientUpdateID` was being sent with every API request. In https://github.com/Expensify/App/pull/41962 I only refactored that to make it clearer and more DRY by moving it to `enhanceParameters`, which runs on every request.

**Comment by iwiznia** [comment] 2024-07-22 11:28
Oh wow... so yes, we should  change the `clientUpdateID` waf rule to allow -1.

**Comment by iwiznia** [comment] 2024-07-22 11:35
PR here https://github.com/Expensify/Web-Expensify/pull/42831

**Comment by iwiznia** [comment] 2024-07-22 11:36
BTW I think it's totally fine to send clientUpdateID in all requests, even if we only need it for writes.

**Comment by Julesssss** [comment] 2024-07-22 12:49
PR merged, thanks

**Comment by joekaufmanexpensify** [comment] 2024-07-22 12:53
Sweet, thank you both!

**Closed** 2024-07-30 08:04 UTC
Labels: Reviewing, Daily, Help Wanted, Bug
