### ISSUE TITLE
[$1000] #admins room - Other user is not referenced in a parenthetical (as copilot for XXXX)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21428] opened 2023-06-23 17:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20738
## Action Performed:
1. In [www.expensify.com,](http://www.expensify.com%2C/)
login as a copilot for a policy admin
2. Go to a policy disable and enable some categories on behalf of the admin as copilot while in copilot mode
3. Go to new.expensify.com
4. Go to the #admins chat room for that same policy
5. Verify that the actions taken by the copilot show as from them, with their avatar, and the other user is referenced in a parenthetical (as copilot for XXXX)

## Expected Result:
Other user is referenced in a parenthetical (as copilot for XXXX)

## Actual Result:
Other user is NOT referenced in a parenthetical (as copilot for XXXX)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/adac8190-2cbe-4ca3-87ae-54ba8fee44ef

![Bug6104231_OD](https://github.com/Expensify/App/assets/78819774/afb191ee-bbcf-4895-9b84-2cfbf60aebd8)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e08270f48a48293</li>
        <li>Upwork Job ID: 1673803073433559040</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by tjferriss** [comment] 2023-06-27 21:19
Reproduced. There is no indication the changes were made by a co-pilot.

<img width="995" alt="Screenshot 2023-06-27 at 14 18 24" src="https://github.com/Expensify/App/assets/8292562/a0390596-87a2-401b-a9a2-eb9efe7fb48f">

**Comment by tjferriss** [comment] 2023-06-28 05:24
Thank you for referencing the related PR and issue. It looks like we can close this as it has been previously reported.

**Closed by tjferriss** 2023-06-28 05:24 UTC
Labels: External, Daily, Help Wanted, Bug
