### ISSUE TITLE
[$250] Taxes - Edited tax is not grayed out in Tax list in submit manual flow

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#42918] opened 2024-05-31 12:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go offline.
4. Go to Categories > Edit a category name.
5. Go to Tags > Edit a tag name.
6. Go to Taxes > Edit a tax name and rate.
7. Go to workspace chat.
8. Go to + > Submit expense > Manual.
9. Proceed to confirmation page.
10. Look for the edited items in Category, Tag and Tax list.

## Expected Result:
All the edited items in Category, Tag and Tax list will be grayed out.

## Actual Result:
The edited items in Category and Tag list are grayed outm but the edited item in Tax list is not grayed out.
in production : None of the items are grayed out
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/a5e3ecde-e2b8-4187-a11c-5966ca546c15

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0132c9043b25b1d684</li>
        <li>Upwork Job ID: 1796662203817881600</li>
        <li>Last Price Increase: 2024-05-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by kavimuru** [comment] 2024-05-31 12:56
@sonialiap FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by MonilBhavsar** [comment] 2024-05-31 13:58
Commented on the offending PR https://github.com/Expensify/App/pull/42620#issuecomment-2142239882

**Comment by MonilBhavsar** [comment] 2024-05-31 13:58
Not worth blocking deploy

**Comment by iwiznia** [comment] 2024-05-31 21:57
@Krishna2323 introduced this here https://github.com/Expensify/App/issues/41066

**Comment by iwiznia** [comment] 2024-05-31 21:59
Actually reverted it here https://github.com/Expensify/App/pull/42953

**Comment by vishnu-karuppusamy** [comment] 2024-06-01 08:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The edited Tax rate items in the workspace are not grayed out in offline mode.

### What is the root cause of that problem?
The graying out is based on the property `pendingAction` which is missing in the tax rates data.

### What changes do you think we should make in order to solve the problem?
Add the `pendingAction` property to the `updatePolicyTaxValue`, `renamePolicyTax` and other setters of the tax rate data.
```typescript
                  taxRates: {
                      taxes: {
                          [taxID]: {
                              value: stringTaxValue,
                              pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE,
                              pendingFields: {value: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE},
                              errorFields: {value: null},
                          },
                      },
                  }
``` 

### What alternative solutions did you explore? (Optional)
None.

**Comment by vishnu-karuppusamy** [comment] 2024-06-01 08:49
Contributor details
Your Expensify account email: vishnu56666@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fded0233eaf38db6?mp_source=share

**Comment by vishnu-karuppusamy** [comment] 2024-06-01 08:50
> ⚠️ Invalid email. Please make sure to create an Expensify account with this email first [here](https://new.expensify.com/).

Update the email in the last reply.

**Comment by vishnu-karuppusamy** [comment] 2024-06-14 07:22
Please share if there's any update on the proposal.

**Comment by sonialiap** [comment] 2024-06-21 09:59
Closing issue since no payment is needed

**Closed by sonialiap** 2024-06-21 09:58 UTC
Labels: Reviewing, External, Engineering, Weekly, Help Wanted, Bug
