### ISSUE TITLE
Errors in ONYXKEYS.USER_WALLET getting cleared instantly without user interaction

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#12567] opened 2022-11-08 20:04 UTC
Regression coming from: https://github.com/Expensify/App/pull/10447/files#r1017060491

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

Have a user with 2 bank accounts

1. Go to `/settings/payments` in new dot
2. Click the bank account that is not your Default
![image](https://user-images.githubusercontent.com/87341702/200663261-8800604e-63e3-4dc3-a659-12e4c78222d4.png)
4. Click "Make default payment method"
5. Input a bad password

https://user-images.githubusercontent.com/87341702/200663920-ab6260ae-6260-4a2d-a6a7-df06eb1f0cb5.mov

## Expected Result:
There will be an error below the "Add payment method" button, the error should stay there until you click the `X`

## Actual Result:
The error appears below the "Add payment method" button, but gets immediately removed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2022-11-08 20:10
cc @Justicea83

**Comment by kavimuru** [comment] 2022-11-08 20:14
@aldo-expensify No we are not testing error in the regression.

**Comment by aldo-expensify** [comment] 2022-11-08 20:17
> @aldo-expensify No we are not testing error in the regression.

Sorry, not sure what this means. I mean, in the testrail tests, do we have a manual test that do these steps and look for this error? I'm guessing that we don't have and that's why this regression got to production

**Comment by kavimuru** [comment] 2022-11-08 20:22
@aldo-expensify 

> No we are not testing error in the regression.

Sorry, I meant there are no testrail steps to test the errors.

**Comment by aldo-expensify** [comment] 2022-11-08 20:25
ok!, thanks

**Comment by aldo-expensify** [comment] 2022-11-08 20:26
you don't mean errors in general, right? you are talking about errors in this page or particular button?

**Comment by lschurr** [comment] 2022-11-08 21:59
I was able to reproduce this. There is no error when entering the wrong password. Should this be `External` @aldo-expensify?

**Comment by aldo-expensify** [comment] 2022-11-08 22:02
@lschurr I'll take care of it internally, I know already where the bug is :)

**Comment by aldo-expensify** [comment] 2022-11-10 21:28
@lschurr added you back because I think we need to handle the C+ @thesahindia review in the [PR](https://github.com/Expensify/App/pull/12579)

**Comment by lschurr** [comment] 2022-11-10 22:36
Hm, so do we need a job posting for this in Upwork @aldo-expensify?

**Comment by aldo-expensify** [comment] 2022-11-10 23:47
hehe, I'm a bit lost too, but I think:

- @thesahindia should be assigned to this issue because he is the C+ that reviewed the PR
- An Upwork job posting should be created to pay @thesahindia 

@Beamanator is this correct?

**Comment by Beamanator** [comment] 2022-11-10 23:49
Kinda looks like a decent amount of people are still unclear how this works :D https://expensify.slack.com/archives/C01SKUP7QR0/p1668104342206089

**Comment by lschurr** [comment] 2022-11-14 15:39
Asked for more guidance [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1668187591130819).

**Comment by lschurr** [comment] 2022-11-14 18:24
Ok, I posted the job. 

https://www.upwork.com/ab/applicants/1592221542839255040/job-details
https://www.upwork.com/jobs/~01431277aec358749a

@thesahindia - can you apply in Upwork so that we can pay you for reviewing the PR?

**Comment by lschurr** [comment] 2022-11-14 18:25
Also @aldo-expensify - do you know if a regression test has been added to testrail for this one?

**Comment by aldo-expensify** [comment] 2022-11-15 01:16
@lschurr I requested a test to be added/updated for it here: https://github.com/Expensify/Expensify/issues/241841

**Comment by thesahindia** [comment] 2022-11-15 10:04
> @thesahindia - can you apply in Upwork so that we can pay you for reviewing the PR?

@lschurr, done!

**Comment by lschurr** [comment] 2022-11-15 17:20
Cool - the PR has been merged right @aldo-expensify? Can we consider this bug fixed?

**Comment by thesahindia** [comment] 2022-11-15 17:30
Yup, it's on staging.

**Comment by aldo-expensify** [comment] 2022-11-16 18:00
The update of the manual test to include this case is done (https://github.com/Expensify/Expensify/issues/241841).

**Comment by lschurr** [comment] 2022-11-16 18:17
@thesahindia has been paid in Upwork. I believe we can close!

**Closed by lschurr** 2022-11-16 18:17 UTC
Labels: Reviewing, Daily, Bug
