### ISSUE TITLE
Greenline line doesn't appear after the mark of a message as unread (iOS)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25737] opened 2023-08-22 23:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a thread conversation with several messages
2. Mark a message as unread

## Expected Result:
Green line "new" should be appeared. Verify the unread marked is displayed in the conversation history

## Actual Result:
Greenline line doesn't appear after the mark of a message as unread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-14

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5b574157-bfd3-4573-84e9-657805902c59

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2023-08-23 00:07
Could this be related? @MonilBhavsar @gedu https://github.com/Expensify/App/pull/18637

**Comment by marcaaron** [comment] 2023-08-23 00:09
Gonna check to see if relate.

**Comment by marcaaron** [comment] 2023-08-23 00:26
Hmm ... reverted that PR locally and it's still broken :suspect:

**Comment by marcaaron** [comment] 2023-08-23 00:30
Hmm this is not related to messages being threaded. It seems like the unread won't work with any message. Doesn't matter if it is a thread.

**Comment by marcaaron** [comment] 2023-08-23 02:35
Ok so after a somewhat lengthy investigation... I have discovered that when we mark a report as "unread" it sets the `lastReadTime` to be later than than the last visible created. But only on iOS. 

Basically, this logic is not working correctly:

https://github.com/Expensify/App/blob/79ea92345e48599d6663ef20213f8c64bb0568c1/src/libs/DateUtils.js#L270-L279

This is the offending PR -> https://github.com/Expensify/App/pull/24446 

I am guessing that date fns works differently in react-native or something, but not sure how.

Confirmed by rolling back `main` to right before it was merged.

**Comment by marcaaron** [comment] 2023-08-23 02:41
@allroundexperts @mountiny adding you guys in here in case you have ideas on how to fix this. I gotta jet.

**Comment by waterim** [comment] 2023-08-23 09:30
Hello, Im Artem from Callstack.
That was my PR which caused this issue, may I help with fixing this regression?

**Comment by mountiny** [comment] 2023-08-23 13:53
@waterim I believe you have found the root cause, can you create a PR with the fix?

**Comment by mountiny** [comment] 2023-08-23 17:35
Confirmed this works on ios in staging now, closing

**Closed by mountiny** 2023-08-23 17:35 UTC
Labels: Reviewing, Engineering, Weekly
