### ISSUE TITLE
[$1000] Android - Unable to access popup menu while "New message" marker is visible

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40108] opened 2024-04-11 13:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Not sure this is same root cause of #40048
**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Open a chat with multiple messages in history
2. Mark the last message as unread
3. Scroll up through the messages until "New message" marker shows up
4. Hold on any message to access the popup menu

## Expected Result:
Pop up menu should open up

## Actual Result:
Pop up menu doesn't show up, nothing happens when user holds on a single comment

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/acb9870d-5412-4b25-8832-357e7b4b227c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc3abc850cbdd73c</li>
        <li>Upwork Job ID: 1778840627568414720</li>
        <li>Last Price Increase: 2024-04-18</li>
    </ul>
</details>

**Comment by arosiclair** [comment] 2024-04-11 17:22
I reproduced on Android in **v1.4.62-3**

**Comment by arosiclair** [comment] 2024-04-11 17:55
No PR's are sticking out to me in the deploy checklist and I'm not currently able to build Android due to [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1712782954992479) so I'm a bit stuck here.

**Comment by arosiclair** [comment] 2024-04-11 19:03
_Not_ reproducible in **v1.4.61-8**

Android build is fixed on `main` now. In dev, what I'm seeing is that the long press only works on the last handful of report actions at the bottom. Scrolling up and trying earlier report actions does not work. The "New message" marker is not needed.

**Comment by arosiclair** [comment] 2024-04-11 19:10
I would guess this is related to https://github.com/Expensify/App/pull/13767 according to comments on similar issues [here](https://github.com/Expensify/App/issues/40048#issuecomment-2049738563).

@WoLewicki or @roryabraham either of you have an idea?

**Comment by arosiclair** [comment] 2024-04-12 00:20
I added logs to our showPopover function [here](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.tsx#L314) and executeSecondaryInteraction functions [here](https://github.com/Expensify/App/blob/fa2bfb29dbcdc84c369c77cfcadda0a8a7a577e7/src/components/PressableWithSecondaryInteraction/index.tsx#L61). Even when the context menu works, there is no log from `PressableWithSecondaryInteraction` so I'm deeply confused on what's going wrong here.

**Comment by isabelastisser** [comment] 2024-04-12 14:56
@arosiclair, is there anything I can do here to help?

Bump @WojtekBoman and @roryabraham on Andrew's message above.

**Comment by arosiclair** [comment] 2024-04-12 17:38
> @arosiclair, is there anything I can do here to help?

Thanks but I don't think so atm.

So at this point, I've burned an entire day trying to figure this out and haven't really made any progress. The information that I have is

- Long presses only work on the first screen of report actions. Our long press handler does not work on any actions above that.
- This is not reproducible on prod so this is definitely caused by the current deploy
- From the list of PR's, the [fabric PR](https://github.com/Expensify/App/pull/13767) is the only relevant change that I can see
  - I'm pretty confident this is the root cause, but I cannot successfully build Android after reverting to verify
  
I'll add `External` in case any contributors have better luck but also re-assign since @roryabraham was managing that PR. cc @WojtekBoman @j-piasecki @ishpaul777

**Comment by WoLewicki** [comment] 2024-04-12 20:31
@arosiclair Could you check if https://github.com/Expensify/App/pull/40191 solves the issue? I cannot reproduce it locally unfortunately.

**Comment by isabelastisser** [comment] 2024-04-15 14:12
@arosiclair, any updates here? Thanks!

**Comment by arosiclair** [comment] 2024-04-15 14:30
> @arosiclair Could you check if #40191 solves the issue? I cannot reproduce it locally unfortunately.

It should be very easy to reproduce unless it's already been fixed. Just open a convo, scroll up and long press any message on Android. I'm away from home and have other priorities so I can't reproduce atm.

**Comment by WoLewicki** [comment] 2024-04-15 15:42
> It should be very easy to reproduce unless it's already been fixed.

The problem is that I could not reproduce it even before I added a fix for it 😓 The steps worked just fine for me.

**Comment by j-piasecki** [comment] 2024-04-16 10:24
I cannot reproduce it on the `main` branch, nor https://github.com/Expensify/App/pull/40191:


https://github.com/Expensify/App/assets/21055725/54836b9c-7180-41d4-8772-e60a29872db9

**Comment by roryabraham** [comment] 2024-04-16 16:39
reopening this since we've had a number of inconsistently reproducible issues on staging

**Comment by roryabraham** [comment] 2024-04-16 23:19
I'm blocked from testing this by https://github.com/Expensify/App/issues/40048, but I'm optimistic that both might be fixed by https://github.com/Expensify/App/pull/40191, which should be deployed soon: https://github.com/Expensify/App/actions/runs/8713394572/job/23902301052

**Comment by roryabraham** [comment] 2024-04-16 23:31
I was able to reproduce this still in 1.4.62-13

**Comment by roryabraham** [comment] 2024-04-17 20:54
what I'm currently investigating is whether the `onLongPress` handler is somehow getting unset. To do that, I've given the `PressableWithSecondaryInteraction` in `ReportActionItem` a `testID`, and then in `BaseGenericPressable` I've added a conditional log line for a reportAction where the longPress is not working.

So far I've discovered that `isDisabled` appears to be `false` as expected.

**Comment by roryabraham** [comment] 2024-04-17 20:56
ok, so both `isDisabled` and `onLongPress` are truthy, so the handler being provided is not undefined.

**Comment by roryabraham** [comment] 2024-04-17 21:04
however, the unresponsive component does seem to be re-rendering whenever I tap it

**Comment by roryabraham** [comment] 2024-04-17 21:25
Debugging [this function](https://github.com/facebook/react-native/blob/fe9942a19d65d30c1127af207cf7777465cb257e/packages/react-native/Libraries/Pressability/Pressability.js#L706-L711), and in the normal case a long press looks like this:

```
 LOG  RORY_DEBUG performing transition side effects {"nextState": "RESPONDER_INACTIVE_PRESS_IN", "prevState": "NOT_RESPONDER", "signal": "RESPONDER_GRANT"}
 LOG  RORY_DEBUG performing transition side effects {"nextState": "RESPONDER_ACTIVE_PRESS_IN", "prevState": "RESPONDER_INACTIVE_PRESS_IN", "signal": "DELAY"}
 LOG  RORY_DEBUG performing transition side effects {"nextState": "RESPONDER_ACTIVE_LONG_PRESS_IN", "prevState": "RESPONDER_ACTIVE_PRESS_IN", "signal": "LONG_PRESS_DETECTED"}
 DEBUG  [info] [Onyx] merge called for key: modal properties: willAlertModalBecomeVisible,isPopover hasChanged: true - ""
 LOG  RORY_DEBUG performing transition side effects {"nextState": "NOT_RESPONDER", "prevState": "RESPONDER_ACTIVE_LONG_PRESS_IN", "signal": "RESPONDER_RELEASE"}
```

But in our error case, it looks like this:

```
 LOG  RORY_DEBUG performing transition side effects {"nextState": "RESPONDER_INACTIVE_PRESS_IN", "prevState": "NOT_RESPONDER", "signal": "RESPONDER_GRANT"}
 LOG  RORY_DEBUG performing transition side effects {"nextState": "RESPONDER_ACTIVE_PRESS_IN", "prevState": "RESPONDER_INACTIVE_PRESS_IN", "signal": "DELAY"}
 LOG  RORY_DEBUG the madman has done it {"isDisabled": false, "onLongPress": [Function executeSecondaryInteraction]}
 LOG  RORY_DEBUG usePressability config [Function anonymous]
 LOG  RORY_DEBUG performing transition side effects {"nextState": "RESPONDER_ACTIVE_PRESS_OUT", "prevState": "RESPONDER_ACTIVE_PRESS_IN", "signal": "LEAVE_PRESS_RECT"}
 LOG  RORY_DEBUG the madman has done it {"isDisabled": false, "onLongPress": [Function executeSecondaryInteraction]}
 LOG  RORY_DEBUG usePressability config [Function anonymous]
 LOG  RORY_DEBUG performing transition side effects {"nextState": "NOT_RESPONDER", "prevState": "RESPONDER_ACTIVE_PRESS_OUT", "signal": "RESPONDER_RELEASE"}
```

So it _looks_ like what's happening is the `BaseGenericPressable` is getting re-rendered mid-gesture, which causes a `LEAVE_PRESS_RECT` signal rather than a `LONG_PRESS_DETECTED` signal

**Comment by roryabraham** [comment] 2024-04-17 21:51
coming from [here](https://github.com/facebook/react-native/issues/36710#issuecomment-1586134344), I'm going to try disabling the native driver for animations. I tried converting the animation for the new messages pill to Reanimated and that didn't work

**Comment by roryabraham** [comment] 2024-04-17 21:54
`useNativeDriver: false` did not fix the problem

**Comment by roryabraham** [comment] 2024-04-17 22:01
<details>
<summary>More logs</summary>

```
 LOG  RORY_DEBUG pressable received signal: RESPONDER_GRANT
 LOG  RORY_DEBUG performing transition side effects {"nextState": "RESPONDER_INACTIVE_PRESS_IN", "prevState": "NOT_RESPONDER", "signal": "RESPONDER_GRANT"}
 LOG  RORY_DEBUG pressable received signal: DELAY
 LOG  RORY_DEBUG performing transition side effects {"nextState": "RESPONDER_ACTIVE_PRESS_IN", "prevState": "RESPONDER_INACTIVE_PRESS_IN", "signal": "DELAY"}
 LOG  RORY_DEBUG the madman has done it {"isDisabled": false, "onLongPress": [Function executeSecondaryInteraction]}
 LOG  RORY_DEBUG usePressability config [Function anonymous]
 LOG  RORY_DEBUG signalling LEAVE_PRESS_RECT because touch is outside responder region {"responderRegion": {"bottom": -551.6190795898438, "left": 0, "right": 411.4285583496094, "top": -609.1430053710938}, "touch": {"identifier": 0, "locationX": 186.6666717529297, "locationY": 7.61904764175415, "pageX": 258.6666564941406, "pageY": 289.1428527832031, "target": 2332, "targetSurface": 1, "timestamp": 159260347}}
 LOG  RORY_DEBUG pressable received signal: LEAVE_PRESS_RECT
 LOG  RORY_DEBUG performing transition side effects {"nextState": "RESPONDER_ACTIVE_PRESS_OUT", "prevState": "RESPONDER_ACTIVE_PRESS_IN", "signal": "LEAVE_PRESS_RECT"}
 LOG  RORY_DEBUG signalling LEAVE_PRESS_RECT because touch is outside responder region {"responderRegion": {"bottom": -551.6190795898438, "left": 0, "right": 411.4285583496094, "top": -609.1430053710938}, "touch": {"identifier": 0, "locationX": 186.6666717529297, "locationY": 7.61904764175415, "pageX": 258.6666564941406, "pageY": 289.1428527832031, "target": 2332, "targetSurface": 1, "timestamp": 159260514}}
 LOG  RORY_DEBUG pressable received signal: LEAVE_PRESS_RECT
 LOG  RORY_DEBUG the madman has done it {"isDisabled": false, "onLongPress": [Function executeSecondaryInteraction]}
 LOG  RORY_DEBUG usePressability config [Function anonymous]
 LOG  RORY_DEBUG signalling LEAVE_PRESS_RECT because touch is outside responder region {"responderRegion": {"bottom": -551.6190795898438, "left": 0, "right": 411.4285583496094, "top": -609.1430053710938}, "touch": {"identifier": 0, "locationX": 186.6666717529297, "locationY": 7.61904764175415, "pageX": 258.6666564941406, "pageY": 289.1428527832031, "target": 2332, "targetSurface": 1, "timestamp": 159260664}}
 LOG  RORY_DEBUG pressable received signal: LEAVE_PRESS_RECT
 LOG  RORY_DEBUG signalling LEAVE_PRESS_RECT because touch is outside responder region {"responderRegion": {"bottom": -551.6190795898438, "left": 0, "right": 411.4285583496094, "top": -609.1430053710938}, "touch": {"identifier": 0, "locationX": 186.6666717529297, "locationY": 7.61904764175415, "pageX": 258.6666564941406, "pageY": 289.1428527832031, "target": 2332, "targetSurface": 1, "timestamp": 159260681}}
 LOG  RORY_DEBUG pressable received signal: LEAVE_PRESS_RECT
 LOG  RORY_DEBUG signalling LEAVE_PRESS_RECT because touch is outside responder region {"responderRegion": {"bottom": -551.6190795898438, "left": 0, "right": 411.4285583496094, "top": -609.1430053710938}, "touch": {"identifier": 0, "locationX": 186.6666717529297, "locationY": 7.61904764175415, "pageX": 258.6666564941406, "pageY": 289.1428527832031, "target": 2332, "targetSurface": 1, "timestamp": 159260689}}
 LOG  RORY_DEBUG pressable received signal: LEAVE_PRESS_RECT
 LOG  RORY_DEBUG signalling LEAVE_PRESS_RECT because touch is outside responder region {"responderRegion": {"bottom": -551.6190795898438, "left": 0, "right": 411.4285583496094, "top": -609.1430053710938}, "touch": {"identifier": 0, "locationX": 186.6666717529297, "locationY": 7.61904764175415, "pageX": 258.6666564941406, "pageY": 289.1428527832031, "target": 2332, "targetSurface": 1, "timestamp": 159260764}}
 LOG  RORY_DEBUG pressable received signal: LEAVE_PRESS_RECT
 LOG  RORY_DEBUG signalling LEAVE_PRESS_RECT because touch is outside responder region {"responderRegion": {"bottom": -551.6190795898438, "left": 0, "right": 411.4285583496094, "top": -609.1430053710938}, "touch": {"identifier": 0, "locationX": 186.6666717529297, "locationY": 7.61904764175415, "pageX": 258.6666564941406, "pageY": 289.1428527832031, "target": 2332, "targetSurface": 1, "timestamp": 159260780}}
 LOG  RORY_DEBUG pressable received signal: LEAVE_PRESS_RECT
 LOG  RORY_DEBUG signalling LEAVE_PRESS_RECT because touch is outside responder region {"responderRegion": {"bottom": -551.6190795898438, "left": 0, "right": 411.4285583496094, "top": -609.1430053710938}, "touch": {"identifier": 0, "locationX": 186.6666717529297, "locationY": 7.61904764175415, "pageX": 258.6666564941406, "pageY": 289.1428527832031, "target": 2332, "targetSurface": 1, "timestamp": 159260797}}
 LOG  RORY_DEBUG pressable received signal: LEAVE_PRESS_RECT
 LOG  RORY_DEBUG signalling LEAVE_PRESS_RECT because touch is outside responder region {"responderRegion": {"bottom": -551.6190795898438, "left": 0, "right": 411.4285583496094, "top": -609.1430053710938}, "touch": {"identifier": 0, "locationX": 187.04762268066406, "locationY": 7.61904764175415, "pageX": 259.047607421875, "pageY": 289.1428527832031, "target": 2332, "targetSurface": 1, "timestamp": 159262399}}
 LOG  RORY_DEBUG pressable received signal: LEAVE_PRESS_RECT
 LOG  RORY_DEBUG signalling LEAVE_PRESS_RECT because touch is outside responder region {"responderRegion": {"bottom": -551.6190795898438, "left": 0, "right": 411.4285583496094, "top": -609.1430053710938}, "touch": {"identifier": 0, "locationX": 188.43377685546875, "locationY": 7.116443634033203, "pageX": 260.43377685546875, "pageY": 288.6402587890625, "target": 2332, "targetSurface": 1, "timestamp": 159262417}}
 LOG  RORY_DEBUG pressable received signal: LEAVE_PRESS_RECT
 LOG  RORY_DEBUG signalling LEAVE_PRESS_RECT because touch is outside responder region {"responderRegion": {"bottom": -551.6190795898438, "left": 0, "right": 411.4285583496094, "top": -609.1430053710938}, "touch": {"identifier": 0, "locationX": 188.95237731933594, "locationY": 6.857142925262451, "pageX": 260.952392578125, "pageY": 288.3809509277344, "target": 2332, "targetSurface": 1, "timestamp": 159262426}}
 LOG  RORY_DEBUG pressable received signal: LEAVE_PRESS_RECT
 LOG  RORY_DEBUG pressable received signal: RESPONDER_RELEASE
 LOG  RORY_DEBUG performing transition side effects {"nextState": "NOT_RESPONDER", "prevState": "RESPONDER_ACTIVE_PRESS_OUT", "signal": "RESPONDER_RELEASE"}
```

</details>

**Comment by roryabraham** [comment] 2024-04-17 22:21
my fledgling understanding of this issue is that the responderRegion for a touch event is sometimes getting measured incorrectly in scroll views. Consistent with https://github.com/Expensify/App/issues/40048 - touch events work finem, until you scroll up or down. Then the responderRegion is measured to be off-screen, and any touch event gets interrupted because even the slightest move of your thumb triggers an `onResponderMove` callback. Then the touch event appears to be outside the responderRegion, the phone thinks you moved your finger off the button, and the touch event is cancelled

**Comment by roryabraham** [comment] 2024-04-17 22:25
Also confirmed that this has nothing to do with the `New Message` marker - just scrolling up and long-pressing is enough for this 🐛 to occur

**Comment by roryabraham** [comment] 2024-04-17 22:26
success case:

```
RORY_DEBUG _measureCallback {"height": 134.09521484375, "left": 0, "pageX": 0, "pageY": 635.4285888671875, "top": 0, "width": 411.4285583496094}
```

error case:

```
RORY_DEBUG _measureCallback {"height": 57.52392578125, "left": 0, "pageX": 0, "pageY": -692.5715942382812, "top": 0, "width": 411.4285583496094}
```

**Comment by roryabraham** [comment] 2024-04-17 23:13
I'm wondering if this is a bug that has been fixed in a newer version of React Native...

**Comment by roryabraham** [comment] 2024-04-18 00:28
[this](https://github.com/facebook/react-native/issues/43500) also looks potentially related, I want to try 0.74 w/ react-native-screens >= 3.31

**Comment by WoLewicki** [comment] 2024-05-08 12:56
I think this issue should be resolved already by https://github.com/Expensify/App/pull/40560 or https://github.com/Expensify/App/pull/40905.

**Comment by c3024** [comment] 2024-05-22 16:58
@roryabraham this appears to be resolved. Could you please close this?

**Closed** 2024-05-30 00:22 UTC
Labels: Reviewing, External, Engineering, Monthly, Bug
