### ISSUE TITLE
[HOLD for payment 2022-12-15] [Image] Web - Profile - The white background in the image changes to black

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11063] opened 2022-09-16 15:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
and login with any account
2. Go to Settings->Profile->Upload photo
3. Select an image with a white background and click save

Attachment: 
![1f98b (2)](https://user-images.githubusercontent.com/93399543/190678088-d72da82b-a9b4-4f61-b275-b5198396c1fe.png)

## Expected Result:
The background on the avatar should remain white

## Actual Result:
The white background changes to black

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.1.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190678241-6ef6d543-ecf5-491c-87cd-ec57b6df3b86.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment] 2022-09-16 16:26
It's not an issue, it happens because the background is transparent. The result will be the same we try it on other platforms (e.g. Slack, Whatsapp)

**Comment by tgolen** [comment] 2022-09-16 17:37
Shouldn't the transparent background remain transparent though? Is this because it's being converted to a JPEG at some point (and transparency isn't supported)?

**Comment by varshamb** [comment] 2022-09-17 14:22
Yes, while saving, image is converting jpeg and jpeg doesn't support transparency.

**Comment by tgolen** [comment] 2022-09-19 14:56
All right, sounds like this would be an internal issue for us to fix then on the server. It would be nice to support images with transparent backgrounds.

**Comment by Beamanator** [comment] 2022-10-06 17:43
Putting this issue on HOLD and tracking in [Image-related feature request and improvements](https://github.com/Expensify/App/issues/10894#top)

**Comment by mvtglobally** [comment] 2022-10-18 11:21
Issue not reproducible during KI retests. (First week)

**Comment by MitchExpensify** [comment] 2022-10-19 21:26
I am unable to reproduce this

**Comment by Beamanator** [comment] 2022-10-20 10:11
@MitchExpensify I reproduced with the image provided in the OP:

![Transparent](https://user-images.githubusercontent.com/3885503/196921487-45bf3d63-7e42-4f4c-83d1-e8b40e519bf6.png)

I reproduced in web, production

**Comment by Beamanator** [comment] 2022-10-20 10:12
Assigning myself too & making `Weekly` since this is on hold for the image enhancements

**Comment by Beamanator** [comment] 2022-10-31 16:02
Will hopefully get to this later this week

**Comment by mallenexpensify** [comment] 2022-11-01 18:08
Off hold[ per this comment](https://github.com/Expensify/App/issues/10894#issuecomment-1297788096). 
Tis internal and assigned to Beaman so not much to do here meow

**Comment by mvtglobally** [comment] 2022-11-03 03:02
Issue not reproducible during KI retests. (Second week)

**Comment by Beamanator** [comment] 2022-11-04 13:40
Alright well I have some (maybe) interesting findings:
1. It looks like we hardcode the `jpg` file type in NewDot [here](https://github.com/Expensify/App/blob/e434efa1c455620c510441628b94081e0f8a564e/src/libs/cropOrRotateImage/index.js#L92) while for native devices we hardcode a `.jpg` at the end of the filename but set the "type" as `image/png` [here](https://github.com/Expensify/App/blob/e434efa1c455620c510441628b94081e0f8a564e/src/libs/cropOrRotateImage/index.native.js#L17)

**Comment by Beamanator** [comment] 2022-11-10 14:45
@JmillsExpensify good question! Currently it looks like we block `.svg` images from being uploaded as avatars here: https://github.com/Expensify/App/blob/0c65dbef1e97c6b811760b97e32a566e26b2e000/src/CONST.js#L30

I'm definitely willing to try to support `.svg` if we want though!

**Comment by JmillsExpensify** [comment] 2022-11-10 17:39
Ok yeah it's come up in a couple of contexts, in https://github.com/Expensify/App/issues/12264 most recently. It's fine if it's a separate project. I'm not clear why we block that file type in the first place.

**Comment by Beamanator** [comment] 2022-11-10 18:36
Aah interestingggg, I'm happy to make it another issue in my tracker, though maybe a bit lower priority

**Comment by JmillsExpensify** [comment] 2022-11-11 02:24
Added this project to WAQ - in progress

**Comment by Beamanator** [comment] 2022-11-11 23:17
Final PR for this (https://github.com/Expensify/App/pull/12549) is ready for review!

**Comment by mvtglobally** [comment] 2022-11-22 20:45
Issue not reproducible during KI retests. (Third week) Are we ok to close this one?

**Comment by trjExpensify** [comment] 2022-11-22 22:39
Oh, interesting. @Beamanator but your App PR from [this list](https://github.com/Expensify/App/issues/11063#issuecomment-1303554055) isn't merged yet? 😅

**Comment by Beamanator** [comment] 2022-11-25 08:38
Found some annoying issues on Mobile where Android & iOS Native Apps don't properly handle `bmp` & `gif` file uploads (with the help of @Santhosh-Sellavel 's very thorough tests 👍 ) 🤷 so I'm planning to make a follow-up issue that's external where others can help investigate possible solutions in the 3rd-party library we use, `@oguzhnatly/react-native-image-manipulator`

**Comment by JmillsExpensify** [comment] 2022-11-26 17:52
Great question. This is a bit of a grey area, since we recently added the ability to support all file types, which pre-dates WAQ. So based on that, given that we now support all file types and we have bugs related to that, I think we should solve them now as part of WAQ.

**Comment by Beamanator** [comment] 2022-11-28 11:55
That's fair, hopefully the PR to support all file types (for web / desktop / mobile web) will get merged soon, then I'll take the issue to fix `bmp` / `gif` images off HOLD, and we can get to work on it (probably from contractors since it seems like a big refactor that'll require updating at least 1 3rd-party lib)

**Comment by JmillsExpensify** [comment] 2022-11-29 20:35
Ok cool. That sounds like a plan to me. I think we should put this issue on HOLD in the meantime in any case.

**Comment by Beamanator** [comment] 2022-11-30 10:11
Wait wait taking this off hold b/c https://github.com/Expensify/App/pull/12549 is the PR to fix this issue :D (or am I missing something @JmillsExpensify )?

**Comment by JmillsExpensify** [comment] 2022-12-01 06:39
Ah, haha thanks. I'm with you now.

**Comment by Beamanator** [comment] 2022-12-01 10:43
Have one last thing to figure out before being able to merge (iOS mWeb, `.png` file format specifically) - calling in @jasperhuangg & @Santhosh-Sellavel to do this last test, being 100% sure we're uploading files of that format

**Comment by trjExpensify** [comment] 2022-12-01 22:19
Looks like we're merged here! 🎉 

On this follow-up https://github.com/Expensify/App/issues/13038, do we want to add it to the `Image` tracker?

**Comment by Beamanator** [comment] 2022-12-02 08:39
HECK ya we are.

And yes good idea I'll add that ^ follow-up to the tracker! Still won't take it off HOLD till the PR for this one gets to Production (to make sure there's no weird regressions)

**Comment by trjExpensify** [comment] 2022-12-02 13:54
Cool, makes sense!

**Comment by Santhosh-Sellavel** [comment] 2022-12-09 16:15
Please assign me this for tracking payment thanks!

**Comment by trjExpensify** [comment] 2022-12-16 12:40
Sent you a contract, @Santhosh-Sellavel.

**Comment by trjExpensify** [comment] 2022-12-16 15:58
Cool, settled!

**Closed by trjExpensify** 2022-12-16 15:58 UTC
Labels: Reviewing, Engineering, Daily, Improvement, Internal, Awaiting Payment, Bug
