### ISSUE TITLE
[HOLD for payment 2023-06-02] [$1000] Green icon on the left of share code is not turning white like others when hovered.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19067] opened 2023-05-16 20:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Open "Settings".
2.  Hover on share code option.

## Expected Result: 
Icon on the left of share code should turn white like others when hovered.

## Actual Result:
 Green icon on the left of share code is not turning white like others when hovered.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14-9
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/332cf318-6729-4b5d-81d3-c2f89b7d716f

<img width="960" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/03d911b5-18f9-46f3-80af-99d492afc160">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684166606971679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7e23eb0ca73f31d</li>
        <li>Upwork Job ID: 1659497347649708032</li>
        <li>Last Price Increase: 2023-05-19</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-05-16 23:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Green icon on the left of share code is not turning white like others when hovered.
### What is the root cause of that problem?
the svg code of icon qrcode.svg has inline fill color while other icons havn't.
If you browse the icons [here](https://github.com/Expensify/App/tree/main/assets/images) you will find all SVG icon hasn't inline fill color and show as blacked, but this icon color has filled color as show as green.
https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/assets/images/qrcode.svg#L4
### What changes do you think we should make in order to solve the problem?
remove `fill="#03D47C"` from the SVG code for this icon.

### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment] 2023-05-19 09:53
Able to repro, forgot to add the screenshot: 
<img width="395" alt="2023-05-19_10-53-18" src="https://github.com/Expensify/App/assets/56830058/a1763ab7-a926-4905-acc4-8bc2fa3c2d01">

**Comment by sobitneupane** [comment] 2023-05-19 10:39
Thanks for the proposal @ahmedGaber93.

[Proposal](https://github.com/Expensify/App/issues/19067#issuecomment-1550476151) from @ahmedGaber93 looks good to me.

🎀👀🎀 C+ reviewed
cc: @aldo-expensify

**Comment by zanyrenney** [comment] 2023-05-22 11:48
Awesome, thank you @sobitneupane 

@aldo-expensify - please give us the 👍🏼 when we can proceed.

**Comment by ahmedGaber93** [comment] 2023-05-24 00:04
@sobitneupane [PR](https://github.com/Expensify/App/pull/19505) is ready for review.

**Comment by zanyrenney** [comment] 2023-05-25 17:22
Going OOO and this is pretty active so needs management by bug0 team member, as per the [new process ](https://expensify.slack.com/archives/CK49UADB9/p1684182291511799)to stay assigned but assign another team member, please can you keep a watch of this. I am OOO until 8th June. Thanks!

**Comment by maddylewis** [comment] 2023-05-25 19:17
as a heads up, im OOO fri/mon

**Comment by maddylewis** [comment] 2023-06-01 16:44
moving to daily since payment is due tomorrow 👍

**Comment by maddylewis** [comment] 2023-06-01 17:04
### Payments
- @usmantariq96 (reporting bonus) - $250
- @sobitneupane (C+) - $1000
- @ahmedGaber93  - $1000

**Comment by ahmedGaber93** [comment] 2023-06-01 18:02
@maddylewis
This issue merged within 2 days, so I think it is eligible for a bonus.
Thanks!

**Comment by maddylewis** [comment] 2023-06-02 13:48
everyone is paid! @sobitneupane - will you confirm if we need a regression test for this one / review this checklist? thank you! https://github.com/Expensify/App/issues/19067#issuecomment-1563879712

**Comment by sobitneupane** [comment] 2023-06-06 08:17
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/18636
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/18636#issuecomment-1578153961
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I don't think any change in review checklist is required. It is one-off case. We don't usually change items in Settings Menu.

**Comment by maddylewis** [comment] 2023-06-07 14:00
update to regression test proposed - closing!

**Closed by maddylewis** 2023-06-07 14:00 UTC
Labels: External, Daily, Awaiting Payment, Bug
