### ISSUE TITLE
[$250] Admin Room - FAB task is assigned to the room/group of the previously created task

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51094] opened 2024-10-18 16:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5083391&group_by=cases:section_id&group_order=asc&group_id=291936
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions: Create a workspace. Add some messages in the #admin channel.
1. Click on FAB
2. Click on create task
3. Search for the #admin room of the created workspace

## Expected Result:
The user should be able to select the admin room inside 'Share'

## Actual Result:
When the user assigns a task from the FAB button, the “Share” option cannot be modified before the “Confirm task” screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/07aabf81-ba4f-428d-b8ab-2db29af4a9c9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849154853759257478</li>
        <li>Upwork Job ID: 1849154853759257478</li>
        <li>Last Price Increase: 2024-10-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by NJ-2020** [comment] 2024-10-18 23:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Admin Room - FAB task is assigned to the room/group of the previously created task
### What is the root cause of that problem?
When we create a task inside another room we set the `NVP_QUICK_ACTION_GLOBAL_CREATE` to task and set the parentReportID equal to current report id
https://github.com/Expensify/App/blob/f7d08e0941b9747bf266a11264bbf47f51bafda6/src/libs/actions/Task.ts#L248-L258
So when we go to another room and then go to FAB and quick actions for task and we set the `task.parentReportID` equal to `NVP_QUICK_ACTION_GLOBAL_CREATE.parentReportID`

And after filling all the info and clicking confirm button we got redirected to the confirm page
And for share input we're only enabling here if the task.parentReportID is not empty
https://github.com/Expensify/App/blob/f7d08e0941b9747bf266a11264bbf47f51bafda6/src/pages/tasks/NewTaskPage.tsx#L211-L212
And also every the share value input changed, we always check here if there's a task.parentReportID then we will revert it back to the parentReportID
https://github.com/Expensify/App/blob/f7d08e0941b9747bf266a11264bbf47f51bafda6/src/pages/tasks/NewTaskPage.tsx#L89-L94

### What changes do you think we should make in order to solve the problem?
We should remove this code
https://github.com/Expensify/App/blob/f7d08e0941b9747bf266a11264bbf47f51bafda6/src/pages/tasks/NewTaskPage.tsx#L211-L212
and this also
https://github.com/Expensify/App/blob/f7d08e0941b9747bf266a11264bbf47f51bafda6/src/pages/tasks/NewTaskPage.tsx#L89-L94
### What alternative solutions did you explore? (Optional)
When quick action for task instead of passing `NVP_QUICK_ACTION_GLOBAL_CREATE.parentReportID` we can pass the current reportID so it will match the current room

**Comment by truph01** [comment] 2024-10-19 03:16
> When the user assigns a task from the FAB button, the “Share” option cannot be modified before the “Confirm task” screen

@zanyrenney I believe this behavior is expected since we’re creating a new task through the quick action, which utilizes the data from the previously created task. Previously, there was an "Assign Task" option in the FAB that allowed users to modify the shared data, but it has been removed.

If we still want to enable _"The user should be able to select the admin room inside 'Share'"_, I believe a discussion is needed before moving forward.

**Comment by zanyrenney** [comment] 2024-10-22 10:09
Hey @truph01 thanks for your thoughts here.

**Comment by zanyrenney** [comment] 2024-10-22 10:09
Just checking into what the expected behavior should be.

**Comment by zanyrenney** [comment] 2024-10-23 18:24
adding external.

**Comment by jayeshmangwani** [comment] 2024-10-23 20:45
@zanyrenney Just wanted to confirm here, _The user should be able to select the admin room inside 'Share'_ is the the expected result, right?

**Comment by jayeshmangwani** [comment] 2024-10-28 13:20
@NJ-2020 Could you please add a video after applying your changes? I’m testing your proposal, and the first time I access assign task from the FAB, I’m not seeing the default assignee for the share.

**Comment by jayeshmangwani** [comment] 2024-10-28 13:23
@zanyrenney I’m seeking your consensus on this: we’ve currently disabled editing the task assignee when accessing from the quick action. Now, we’re considering changing the expected behavior so that the Share task assignee can be edited if accessed via the quick action. What are your thoughts?

**Comment by zanyrenney** [comment] 2024-10-30 15:47
I think we should close this seeing as Tasks are not a priority on the roadmap here.

Thank you for your thoughts everyone.

**Closed by zanyrenney** 2024-10-30 15:47 UTC
Labels: External, Daily, Help Wanted, Bug
