### ISSUE TITLE
Web - Creating new chat is lagging

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38818] opened 2024-03-22 17:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://applause-ts.slack.com/archives/G01CL838B8T/p1711126060917069
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to FAB> Start chat> Enter email address and select it

## Expected Result:
Chat should be open immediately and there should be no lagging for conversation history

## Actual Result:
When create new 1:1 or group chat chat conversation history is lagging

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/598229a6-3314-428e-a21d-2dc3c7646e26

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment] 2024-03-22 20:55
I don't seem to be able to reproduce this

**Comment by pecanoro** [comment] 2024-03-22 21:00
Hmm, it takes a bit longer than production but not too bad in my case as the video

**Comment by pecanoro** [comment] 2024-03-22 21:11
I am not sure which PR could have caused this, I am looking into https://github.com/Expensify/App/pull/37930 and https://github.com/Expensify/App/pull/30269

**Comment by pecanoro** [comment] 2024-03-25 15:10
It seems to be pretty fast now, we probably CPed some fixes or something related, so closing

**Closed by pecanoro** 2024-03-25 15:10 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Overdue
