### ISSUE TITLE
[HOLD 18101] onViewableItemsChanged gives false positive results

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#21811] opened 2023-06-28 15:25 UTC
While working on [this proposal](https://github.com/Expensify/App/issues/18101) @burczu encountered an issue with the onViewableItemsChanged event handler that occurs only on the web - it seems like it has a bug and provides incorrect list of visible items. This gives us false positive results while determining the index of the top element of the list. To fully implement this proposal, we will need to spend some additional time trying to fix this issue, and perhaps making some additional PR's to the react-native-web repository (original or our forked one).

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e5d1b0f907043de</li>
        <li>Upwork Job ID: 1674081456343396352</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by burczu** [comment] 2023-06-28 15:28
Hey! It's Bartek from Callstack - expert contributor group - I'll be working on this issue.

**Comment by burczu** [comment] 2023-06-29 12:42
Daily update: I think I found the solution and most likely I'll post some proposal tomorrow.

**Comment by burczu** [comment] 2023-07-03 06:32
Ok, I was a little bit hasty saying I found the solution - after some testing on Friday it seems like it was a dead end, so I need to dig deeper and will work on this today.

**Comment by burczu** [comment] 2023-07-05 13:18
Update: It looks like I may have a solution, hopefully this time for real :) I still need to tweak it a little bit but it's possible that I'll come back tomorrow with the proposal.

**Comment by burczu** [comment] 2023-07-10 11:14
Not overdue - I'll post the summary of what I've found today or tomorrow.

**Comment by puneetlath** [comment] 2023-07-11 17:57
@burczu @sobitneupane FYI, I'll be OOO for a week and a half starting Thursday. Feel free to collaborate on the proposal though and if you feel like it's ready for internal review, @sobitneupane you can ask in #contributor-plus for someone to help review it. Thanks!

**Comment by burczu** [comment] 2023-07-12 07:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In case of using `FlatList` that is inverted on the web, when utilizing the `onViewableItemsChanged` handler, it's `viewableItems` parameter contains incorrect results that are outside the viewport. 

### What is the root cause of that problem?

The issue lays in the `react-native-web` library, in the `VirtualizedList` component. During the first render, in the `_onCellLayout` handler, all the "frames" (offset and length of every item in the list) are collected.

The offset of the frame (single item of the list) is always calculated here in the context of the top of the parent element (the list component here). So, for **not inverted** list where, in the beginning, the content is scrolled top, the first element has offset 0px, the second offset equals the height of the first element and so on. This is correct.

For **inverted** list however, the content is scrolled bottom, and the first element is the one that is on the bottom of the viewport. But frame's offset is calculated, again, in the context of the top of the parent. So the first element on the list has offset, e.g. 2016px (it just takes the `y` coordinate of the `LayoutEvent.layout` object). This is incorrect because while scrolling the **inverted** list, the scroll offset is calculated as a difference between the bottom of the viewport and the bottom of the content.

### What changes do you think we should make in order to solve the problem?

To solve the issue we need to make some changes in the `react-native-web` fork we are using in the App. We need to re-calculate the offset of the frame for **inverted** lists in the `_onCellLayout` handler of the `VirtualizedList` component to show the offset of the frame in the context of the bottom of the parent. These changes will be applied in this part of the code:

```javascript
_onCellLayout(e, cellKey, index) {
    const layout = e.nativeEvent.layout;
    const next = {
      offset: this._selectOffset(layout),
      length: this._selectLength(layout),
      index,
      inLayout: true,
    };
```

In the above code, the `next.offset` value is just `LayoutEvent.layout.y` (for vertical lists). I suggest to change it like below:

```javascript
_onCellLayout(e, cellKey, index) {
    const layout = e.nativeEvent.layout;
    const target = e.nativeEvent.target;
    const next = {
        offset: this._selectOffset(layout),
        length: this._selectLength(layout),
        index,
        inLayout: true,
    };
    
    if (this.props.inverted) {
        next.offset = this._selectClientLength(target.parentNode) - next.offset - next.length;
    }
```

where `this._selectClientLength` returns the height or width of the parent and will be implemented like below:

```javascript
_selectClientLength(parentNode) {
  return !horizontalOrDefault(this.props.horizontal) ? parentNode.clientHeight : parentNode.clientWidth;
}
```

This way the very bottom element of the **inverted** list will have the offset 0px. The second, being above the first one will have the offset equals the height of the first one and so on. This will fix the calculation of `viewableItems` for inverted lists.

### What alternative solutions did you explore? (Optional)

n/a

**Comment by puneetlath** [comment] 2023-07-12 17:33
I haven't had a chance to review the proposal in detail, but one general thought: if we're going to do something in our fork, let's also try to get it merged upstream.

**Comment by burczu** [comment] 2023-07-13 06:31
Hey @puneetlath! I agree in general, but in this case I believe there is 99% of chances that this change will be rejected, because in upstream the `FlatList` and `VirtualizedList` components are copied straight from the `react-native` library and the maintainer of `react-native-web` is not interested to make any web customization in them.

**Comment by sobitneupane** [comment] 2023-07-14 04:45
[Proposal](https://github.com/Expensify/App/issues/21811#issuecomment-1632004895) looks good to me. I agree with @puneetlath. We should try to get it merged upstream.

🎀 👀 🎀 C+ reviewed

**Comment by MonilBhavsar** [comment] 2023-07-14 12:26
Makes sense
@burczu could you please link the code here 

> The offset of the frame (single item of the list) is always calculated here in the context of the top of the parent element (the list component here).

**Comment by burczu** [comment] 2023-07-14 12:37
> The offset of the frame (single item of the list) is always calculated here in the context of the top of the parent element (the list component here).

@MonilBhavsar it's done here in the `_selectOffset` method:

https://github.com/Expensify/react-native-web/blob/16921d7f68286381520ede1b561771335ca1e2cd/packages/react-native-web/src/vendor/react-native/VirtualizedList/index.js#L1643C3-L1651C4

So in case of vertical list it's just `e.nativeEvent.layout.y` coordinate.

**Comment by MonilBhavsar** [comment] 2023-07-14 13:08
Thanks! got it.
> This is incorrect because while scrolling the inverted list, the scroll offset is calculated as a difference between the bottom of the viewport and the bottom of the content.

Sorry, if it is a bad question. But I'm curious, why it is incorrect. Should the offset be calculated from single point of reference(top)?

**Comment by MonilBhavsar** [comment] 2023-07-14 13:40
Thanks for explanation! Makes sense to me 👍  I think that's a fact. that for inverted list, we consider bottom perspective.

As discussed above, let's try to propose to merge upstream first?

**Comment by burczu** [comment] 2023-07-14 13:44
> As discussed above, let's try to propose to merge upstream first?

Unfortunately I'll be OOO starting on Monday till July 25th, and some other Callstack developer will take it over from me on Monday. I guess she or he could try to do it, but personally I doubt we will succeed (for the reasons I've mentioned in t[his comment](https://github.com/Expensify/App/issues/21811#issuecomment-1633633581)).

**Comment by MonilBhavsar** [comment] 2023-07-14 13:54
Thanks for the update! No worries! Yes, fine making fix in forked repo. cc @puneetlath @sobitneupane

**Comment by MonilBhavsar** [comment] 2023-07-17 08:48
looks like PR will be raised soon here

**Comment by ArekChr** [comment] 2023-07-17 11:39
Hey there, I'm going to work on this issue as Bartek is OOO

**Comment by MonilBhavsar** [comment] 2023-07-17 11:53
Thank you @ArekChr! Assigning you to the issue

**Comment by MonilBhavsar** [comment] 2023-07-25 10:27
Merged the PR. I think we can close this out now?

**Comment by MonilBhavsar** [comment] 2023-07-28 13:07
I don't think so we are going to raise an upstream PR, as we know it is not according to standard. https://github.com/Expensify/App/issues/21811#issuecomment-1633633581

**Comment by puneetlath** [comment] 2023-07-31 19:36
Got it! Can we at least share with them what we did and confirm that they are not interested? I'd rather confirm that rather than assuming.

**Comment by MonilBhavsar** [comment] 2023-08-01 06:30
Good point! We didn't try. Can we please open a PR in upstream and confirm that cc @burczu @ArekChr

**Comment by burczu** [comment] 2023-08-03 06:24
Hey @MonilBhavsar @puneetlath! Regarding the PR in the upstream - I've made some tests and seems it is not necessary. 

The current version of the original `react-native-web` is `0.19`. The current version of `Expensify/react-native-web` is based on version `0.18` of the original `react-native-web`. 

I've checked, using @ArekChr's example component, that on the current version of the upstream the issue does not occur, so it seems like once we sync our fork with upstream (it looks like this is ongoing and @roryabraham is responsible), this fix won't be necessary anymore.

**Comment by puneetlath** [comment] 2023-08-03 21:27
Oh wow! In that case, we should revert the change right?

**Comment by burczu** [comment] 2023-08-04 06:34
No, no - it looks like the fork and the upstream are not in sync now, and our forked version is now affected, so the fix is necessary, but it probably won't be once we'll get in sync. I spoke to Rory, and he told me that the plan is to get rid of the forked version completely eventually.

**Comment by roryabraham** [comment] 2023-08-11 00:31
See my comment on the PR in the fork: https://github.com/Expensify/react-native-web/pull/20#issuecomment-1674085189 – I think we should put this on HOLD for https://github.com/Expensify/App/issues/16660

**Comment by MonilBhavsar** [comment] 2023-08-11 07:07
Putting this on HOLD and bumping it to Weekly

**Comment by MonilBhavsar** [comment] 2023-08-21 19:28
On HOLD

**Comment by MonilBhavsar** [comment] 2023-09-01 10:30
On HOLD

**Comment by MonilBhavsar** [comment] 2023-09-12 15:20
On HOLD

**Comment by MonilBhavsar** [comment] 2023-09-25 06:16
still on HOLD

**Comment by MonilBhavsar** [comment] 2023-10-04 14:25
still on HOLD

**Comment by MonilBhavsar** [comment] 2023-10-23 13:55
still on HOLD

**Comment by MonilBhavsar** [comment] 2023-11-03 07:25
Same, bumping to monthly

**Comment by roryabraham** [comment] 2023-12-23 00:33
Taking this off HOLD as #16660 is complete

**Comment by MonilBhavsar** [comment] 2024-01-10 10:21
Now this is off hold, I think we need to confirm if the issue is fixed as we have are directly using upstream repo.
And may be revert PR https://github.com/Expensify/react-native-web/pull/20 in the forked repo? Not sure if this is required.
cc @burczu @ArekChr

**Comment by burczu** [comment] 2024-01-10 10:25
@MonilBhavsar As we switched to use original `react-native-web` here https://github.com/Expensify/App/issues/16660 this issue probably won't be necessary anymore and would be just closed. But I would wait for https://github.com/Expensify/App/issues/18101 to bo finished to be sure.

**Comment by MonilBhavsar** [comment] 2024-01-10 10:27
Thanks! So I would put this issue on HOLD for https://github.com/Expensify/App/issues/18101

**Comment by MonilBhavsar** [comment] 2024-01-10 11:25
The issue is not reproducible anymore, so we can close this issue. Feel free to reopen if you see this issue again, thanks!

**Closed by MonilBhavsar** 2024-01-10 11:25 UTC
Labels: Monthly, Bug

**Comment by sobitneupane** [comment] 2024-01-16 05:43
@MonilBhavsar I can request payment on newDot once I get the payment summary.

https://github.com/Expensify/App/issues/21811#issuecomment-1650076743

cc: @puneetlath

**Comment by MonilBhavsar** [comment] 2024-01-16 05:52
Yes, @sobitneupane is eligible for payment as C+

**Comment by puneetlath** [comment] 2024-01-17 18:08
Payment summary: 
- $500 - @sobitneupane - C+

**Comment by JmillsExpensify** [comment] 2024-02-14 16:43
$500 approved for @sobitneupane based on comment above.
