### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Chat - Report in the background loads infinitely after refreshing group confirmation page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44442] opened 2024-06-26 10:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat.
3. Click Add to group next to a few users.
4. Click Next.
5. Refresh the confirmation page.
6. Dismiss the confirmation page.

## Expected Result:
In Step 5, after refreshing the confirmation page, the report in the background will load.

## Actual Result:
In Step 5, after refreshing the confirmation page, the report in the background shows infinite loading.
In Step 6, after dismissing the confirmation page, the link is https://staging.new.expensify.com/r

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/348585e4-2042-45b2-bdec-5ba4994ff8be

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by izarutskaya** [comment] 2024-06-26 10:37
@CortneyOfstad I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-06-26 10:37
We think this issue might be related to the #vip-vsb

**Comment by flodnv** [comment] 2024-06-26 12:40
@luacmartins @truph01 @akinwale I see that we modified the loading skeleton in this PR - https://github.com/Expensify/App/pull/43652 - could this DeployBlocker be related with that PR?

**Comment by flodnv** [comment] 2024-06-26 13:35
Actually, that's wrong. I tested reverting that PR on `main` and the bug is still there.

I used `git bisect` which tells me that the first bad commit is https://github.com/Expensify/App/commit/af02cb44e0adee190b878a4673a93d82d598bed5

Indeed, I tested reverting that PR on `main` and the bug is fixed.

@Kicu @mountiny @roryabraham @rayane-djouah

**Comment by Kicu** [comment] 2024-06-26 14:08
@flodnv interesting, this PR basically does 3 things:
 - remove shim for IE - highly unlikely to be a culprit
 - remove `forwardRef` that was not used by any component - same thing
 - rewrite ReportScreen from `withOnyx` to `useOnyx` - that one looks fishy

In favor of rolling forward instead of rolling back, I'd suggest we don't revert this PR but instead I will provide the revert just for the `ReportScreenIDSetter` file and we can test if that fixes it - sounds good?
Also @blazejkustra @roryabraham you might be interested to see if this turns out to be some kind of discrepancy between `withOnyx` and `useOnyx`

**Comment by flodnv** [comment] 2024-06-26 14:11
That sounds fine as long as it makes sense along that PR, and as long as reverting those changes fix the bug (I tested reverting the full PR only, not just these specific changes)

**Comment by Kicu** [comment] 2024-06-26 14:35
@flodnv this should fix it: https://github.com/Expensify/App/pull/44463

here is me trying to reproduce the bug on on my PR:
https://github.com/Expensify/App/assets/3929868/7f94f8b4-9dac-4a3a-b708-4a3be9ba2c64

**Comment by roryabraham** [comment] 2024-06-26 20:05
looking at the logs, it appears that the `ReportScreenWrapper` is not re-rendering when we call `navigation.setParams`:

<img width="1087" alt="image" src="https://github.com/Expensify/App/assets/47436092/4eb3ba84-c7d1-4ea6-97ad-86cb97db13f8">

**Comment by roryabraham** [comment] 2024-06-26 20:17
I figured out that adding _only_ the `reports` back with `withOnyx` instead of `useOnyx` solves this problem, but I'm not sure why yet.

**Comment by roryabraham** [comment] 2024-06-28 00:27
This is fixed and on prod, we just need to issue a C+ payment to @c3024 for the review

**Comment by roryabraham** [comment] 2024-06-28 00:29
Context for the fix: https://expensify.slack.com/archives/C01GTK53T8Q/p1719519717862329?thread_ts=1719427166.028799&cid=C01GTK53T8Q

**Comment by roryabraham** [comment] 2024-06-28 17:05
Just a standard $250 payout for the review here

**Comment by CortneyOfstad** [comment] 2024-06-28 17:30
@c3024 — sent you an offer [here](https://www.upwork.com/nx/wm/offer/102917450). Please let me know once you accept. Thank you!

**Comment by c3024** [comment] 2024-06-28 17:32
@CortneyOfstad accepted, thanks!

**Comment by CortneyOfstad** [comment] 2024-07-03 17:13
This has not deployed to production, as there is a deploy blocker. Going to adjust the title

**Comment by CortneyOfstad** [comment] 2024-07-09 16:36
@c3024 can you please complete the checklist above so there is no delay in issuing payment?

Also, i sent you an offer in Upwork (job post [here](https://www.upwork.com/jobs/~014e5bc715ee38d4f9)) Let me know once you accept and I'll get that paid ASAP tomorrow 👍

**Comment by c3024** [comment] 2024-07-10 15:59
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: No PR can be help responsible.
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: NA
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No. This could not have been identified earlier.
* [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression test proposal
1. Open any report
2. Press on FAB > Start Chat
3. Press on `Add to group` on some users
4. Press Next
5. Refresh the page.
6. Verify that the report opened in step 1 correctly loads in the background.

**Comment by c3024** [comment] 2024-07-10 16:01
@CortneyOfstad accepted, thanks!

**Comment by CortneyOfstad** [comment] 2024-07-10 17:45
## Payment Summary

@c3024 — paid $250 via Upwork

## Regression Test

Created [here](https://github.com/Expensify/Expensify/issues/411682)

**Closed by CortneyOfstad** 2024-07-10 17:45 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
