### ISSUE TITLE
Most recent chat from sender isn't showing in LHN 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11342] opened 2022-09-27 15:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. NewDot desktop open to chat with User A
2. Put computer to sleep
3. User A sends new chat/s
4. Awaken computer from sleep

## Expected Result:
To see newest chat in LHN

## Actual Result:
Old chat from before putting

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.2.7-2
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

[lhn not updating take two 9-27.txt](https://github.com/Expensify/App/files/9657769/lhn.not.updating.take.two.9-27.txt)
<img width="726" alt="image - 2022-09-27T115843 040" src="https://user-images.githubusercontent.com/43995119/192576381-3c6747ee-ca85-404d-bd4a-e9648c5b41c6.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664293510128719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-09-27 21:59
Waiting to see if this is reproducible, if so, I want to add `[HOLD Fetch]` to the title, since that _might_ be what fixes this

**Comment by tgolen** [comment] 2022-09-28 20:54
I'm going to take this and see if I can reproduce it locally or not.

**Comment by tgolen** [comment] 2022-09-29 16:29
I was not able to reproduce this on staging. I am seeing new messages just fine

**Comment by mallenexpensify** [comment] 2022-09-30 00:38
Weird, was able to reliably reproduce but not now.  On Version 1.2.10-0 . Tested in Sleep with lid open (where you see new notifications come in on screen) and with laptop lid closed.  I did find another bug though 🥇 
Will reopen if happens again and I can repro

**Comment by mallenexpensify** [comment] 2022-10-13 16:35
This just happened to me again, but it was when there was a weird glitch and NewDot Deskopt showed being offline for a few/handful of seconds.   
<img width="896" alt="image" src="https://user-images.githubusercontent.com/22508304/195654145-ed39c446-6b96-4bda-b62d-37a52f861cfd.png">


Gonna reopen, unassign you Tim and add needs reproduction steps.  Not seeing any errors in logs
[lhn not updating to show new chat.txt](https://github.com/Expensify/App/files/9778782/lhn.not.updating.to.show.new.chat.txt)

**Comment by mallenexpensify** [comment] 2022-10-17 16:36
Happened to me again this morn, posted to #expensify-open-source to see if others are experiencing the issue
https://expensify.slack.com/archives/C01GTK53T8Q/p1666023825454809?thread_ts=1664293510.128719&cid=C01GTK53T8Q

**Comment by Christinadobrzyn** [comment] 2022-10-19 06:23
If I understand, are you saying there's a delay in seeing the response after awakening from sleep? 

Testing the steps in the OP on the desktop app v.2.16-5 (1.2.16-5). 

### Action Performed

- NewDot desktop open to chat with User A
- Put computer to sleep
- User A sends new chat/s
- Awaken computer from sleep

I see the last message from the user but there is a delay. Here's a video. 

![2022-10-19_14-09-47 (1)](https://user-images.githubusercontent.com/51066321/196612139-3815a500-4013-4dd6-98a1-ed2b5ce5b3d4.gif)

**Comment by Christinadobrzyn** [comment] 2022-10-19 06:25
I'm not really sure what to search in the Expensify/App repo for other reports of this but I assume this is related to offline? sending to eng.

**Comment by Christinadobrzyn** [comment] 2022-10-19 06:27
Actually going to unassign eng until we know this is the issue.

**Comment by mallenexpensify** [comment] 2022-10-19 21:13
The issue is that LHN isn't updating.  I've also had it where chats take a while to load in LHN but lets keep that separate.  It happens to me regularly, surprised it doesn't for others. I'm going to trash NewDot and open a fresh version to see if that maybe helps

**Comment by Christinadobrzyn** [comment] 2022-10-20 05:04
Cool! Can you get a video of what is happening so I can try to replicate it @mallenexpensify?

**Comment by mallenexpensify** [comment] 2022-10-20 20:12
I'll get to it soon, i need to remember when reopening to start a vid.  I've found that quickly closing/opening doesn't reproduce as often as when I give it more time

**Comment by mallenexpensify** [comment] 2022-10-26 14:40
For sanity's sake I'm going to close, I did just try to reproduce with no luck
- Quit NewDot desktop
- Closed computer overnight
- opened computer
- started vid then started NewDot
- Chats loaded as expected

**Closed by mallenexpensify** 2022-10-26 14:40 UTC
Labels: Weekly, Needs Reproduction, Bug
