### ISSUE TITLE
[HOLD for payment 2023-10-16] [$500] [Distance] - Replace popup closes after image on ESC

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28088] opened 2023-09-24 15:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click request money
3. Click on distance and raise complete the request with any data
4. Open the request money page by clicking twice on request money message
5. Click on map
6. Click on 3 dots
7. Click ESC and observe that map image closes first and then replace popup

## Expected Result:
Replace popup should close first on ESC

## Actual Result:
Replace popup closes after map image on ESC

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d5b56028-f271-4a8c-b044-8ef423a5648e

https://github.com/Expensify/App/assets/93399543/ae186cb8-5512-482b-b5a0-85c657c3b923

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695375739034889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ef5e7fa3c9c06ba</li>
        <li>Upwork Job ID: 1705971108000849920</li>
        <li>Last Price Increase: 2023-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 26935834</li>
<li>dhanashree-sawant | Reporter | 26935835</li>
</ul></li>
    </ul>
</details>

**Comment by StraferDranzex** [comment] 2023-09-24 18:05
Prioritize Event Listeners:
We need to ensure that the "replace" popup's ESC key action is prioritized over the map's. This might involve adjusting the order in which event listeners are registered or checking the active state of these components.

Hierarchical Check:
When the ESC key is pressed, the app should first check if the "replace" popup is open. If it is, then it should close that first. If the "replace" popup is not open (or has just been closed with the current ESC press), then the app should proceed to check if the map is open and close it if necessary.

Prevent Event Propagation:
When the ESC key action is triggered for the "replace" popup, we should prevent the event from continuing to propagate. This way, once the "replace" popup has closed, the same ESC key action won't immediately close the map image as well.

**Comment by StraferDranzex** [comment] 2023-09-24 18:08
Contributor details
Your Expensify account email: umerayan6@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c127aa85a6bb50b9

**Comment by StraferDranzex** [comment] 2023-09-25 14:28
Re-stated Problem:
The issue we're trying to address is that when the ESC key is pressed, the AttachmentModal closes before the ThreeDotMenu modal, causing the user to see the "Replace" popup close after the image. The expected behavior is for the "Replace" popup to close first.

Root Cause:
The root cause of the problem is how modals are being handled currently. When the ESC key is pressed, the AttachmentModal, which encapsulates the ThreeDotMenu modal, is being dismissed first. This leads to an inconsistent user experience where the internal "Replace" popup (ThreeDotMenu) remains visible momentarily before the external modal (AttachmentModal) disappears.

Suggested Changes:
Your solution of utilizing React's useImperativeHandle hook and refs to manage the hiding order of the modals is clear and precise. By setting a reference to the ThreeDotMenu and exposing the hidePopoverMenu function, we can then programmatically hide the "Replace" popup before dismissing the AttachmentModal. This ensures that the internal modal is always dismissed first, leading to a more consistent user experience.

Alternative Solutions Explored:

Event Propagation Approach: One initial solution I considered was to manage the ESC key event propagation. By ensuring the "Replace" popup's ESC key action takes precedence over the map's, we could prioritize the order of event listeners. If the "Replace" popup was active, the event would stop at that level and not propagate further to the map's ESC event.

Modal Stacking Order: Another method could involve manipulating the stacking order (z-index) of the modals. If the "Replace" popup had a higher stacking order, pressing the ESC key would close it first. However, this method would be less reliable as z-index wouldn't always determine the order of event firing.

Parent-Child Event Management: We could also consider leveraging parent-child component relationships. Instead of checking two separate modals, the parent modal (AttachmentModal) could have a handler that checks the state of its child (ThreeDotMenu). If the child modal is active, the parent modal could trigger its closure before closing itself.

**Comment by laurenreidexpensify** [comment] 2023-09-26 04:37
@robertKozik how we feeling about the proposals above?

**Comment by laurenreidexpensify** [comment] 2023-09-28 03:15
bump @robertKozik

**Comment by robertKozik** [comment] 2023-09-28 09:01
Hi all @StraferDranzex @DylanDylann @ZhenjaHorbach ! Thank you all for your proposals 🙇🏼 
I'll suggest to choose [proposal](https://github.com/Expensify/App/issues/28088#issuecomment-1732626587) written by @ZhenjaHorbach as it consist of the clean way of fixing it. Stop rendering the `ThreeDotsMenu` effectively removes it along with the popup menu. I'm appreciate it more than @DylanDylann proposal as we should use `useImperativeHandle` when we have no other way of expressing the change by props (as it goes against declarative nature of React, you can read more [here](https://react.dev/reference/react/useImperativeHandle) in the PitFall section).

Selected Proposal: https://github.com/Expensify/App/issues/28088#issuecomment-1732626587

🎀 👀 🎀 C+ reviewed

**Comment by dangrous** [comment] 2023-09-29 04:55
Yep, this is simple enough and makes sense! Assigning now.

**Comment by robertKozik** [comment] 2023-10-10 07:51
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **Can't identify any particular PR which introduce it**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **In my opinion there is no need to create new regression test, it's visual bug which not interfere with any of the user flows**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test] **N/A** (https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

tldr; In my opinion there is no need to create new regression test, it's visual bug which not interfere with any of the user flows

**Comment by laurenreidexpensify** [comment] 2023-10-16 12:38
Payment Summary

- Bug report - @dhanashree-sawant $50 payment issued in Upwork 
- Contributor bug fix - @robertKozik does not require payment (Contractor)
- Contributor + Code review - @ZhenjaHorbach $500 payment issued in Upwork

**Closed** 2023-10-18 11:02 UTC
Labels: External, Daily, Awaiting Payment, Bug
