### ISSUE TITLE
[HOLD - #32109] [$500] Attachment – The corrupted PDF can be downloaded, but no download indication is displayed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32204] opened 2023-11-29 17:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account.
3. On a conversation, click on the + button in the compose box
4. Click on add attachment
5. Upload the following corrupted PDF
6. Verify that Failed to load PDF file. message appears when previewing a corrupt PDF file
7. Click on send.
8. Click on “Failed to load PDF file.”

## Expected Result:
The corrupted file should have the same preview component and download component as .mp4/docs.

## Actual Result:
The corrupted PDF can be downloaded by clicking on it, but no download indication is displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/dee95e1a-5a73-4526-b828-eafb04df47c0

[Corrupted PDF.pdf](https://github.com/Expensify/App/files/13503900/Corrupted.PDF.pdf)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a226f1589481a1b1</li>
        <li>Upwork Job ID: 1729917217011929088</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment] 2023-11-29 17:47
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

Attachment – The corrupted PDF can be downloaded, but no download indication is displayed 

## What is the root cause of that problem?

The main problem is that since we are using the onPress function by default

https://github.com/Expensify/App/blob/a0b219711080751d6826bb2330ddd85c1641d7bf/src/components/PDFView/index.js#L328-L337

## What changes do you think we should make in order to solve the problem?

Since we clearly have no information that our file is broken
We can obtain this information using a special method `onLoadError`

https://github.com/Expensify/App/blob/a0b219711080751d6826bb2330ddd85c1641d7bf/src/components/PDFView/index.js#L286-L297

## What alternative solutions did you explore? (Optional)
NA (edited)

**Comment by anup2230** [comment] 2023-11-29 18:39
**Please re-state the problem that we are trying to solve in this issue.**

The corrupted PDF can be downloaded, but no download indication is displayed

**What is the root cause of that problem?**

We are using PressableWithoutFeedback component even before PDF is loaded or failed to load in ~/PDFView/index.js.
```
render() {
        return this.props.onPress ? (
            <PressableWithoutFeedback
                onPress={this.props.onPress}


```

**What changes do you think we should make in order to solve the problem?**

We can use the available state 'failedToLoadPDF' as an additional condition before using the PassibleWithoutFeedback component. Currently, the 'faileToLoadPDF' state is being set to false given that the pdf failed to load. We can utilize this and make a minimal change to solve this issue.

```
render() {
        return this.props.onPress && !this.state.failedToLoadPDF ? (
            <PressableWithoutFeedback
                onPress={this.props.onPress}


```
This should only enable the download onClick when the PDF is loaded properly, utilizing the 'failedtoLoadPDF' state.

**Comment by anup2230** [comment] 2023-11-29 18:41
Contributor details
Your Expensify account email: anup2230@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0125eea53463402da3

**Comment by strepanier03** [comment] 2023-12-01 23:00
@akinwale - When you have some time we have some proposals.

**Comment by chiragsalian** [comment] 2023-12-05 20:18
@ishpaul777 yeah it looks like your proposal was made slightly earlier and sorta solves this issue too. I do like @tienifr proposal showing a cross with failed to load PDF file but i think that visual change might be a different issue. I like solving for displaying the corrupted PDT and having a download indication which you @ishpaul777 seem to solve too.

Thoughts on closing this issue in favor for https://github.com/Expensify/App/issues/32109 since it looks like the proposal there should solve this issue too right, @akinwale @parasharrajat, or am i missing something here?

**Comment by chiragsalian** [comment] 2023-12-12 19:07
@parasharrajat sure i dont mind keep the separate but can you explain why you think they are separate. Doesn't @ishpaul777 proposal solve the expected solution mentioned [here](https://github.com/Expensify/App/issues/32204#issue-2017097189),
> Expected Result:
The corrupted file should have the same preview component and download component as .mp4/docs.

**Comment by strepanier03** [comment] 2024-01-09 05:25
Updated title to reflect the Hold state.

**Comment by strepanier03** [comment] 2024-01-18 00:19
No update yet.

**Comment by strepanier03** [comment] 2024-01-18 00:45
Hmmm, all good here Melvin, on hold still.

**Comment by strepanier03** [comment] 2024-01-30 04:01
Hold GH is open, all good here Melvin.

**Comment by strepanier03** [comment] 2024-02-12 18:45
Still on Hold. All good for now.

**Comment by strepanier03** [comment] 2024-02-23 05:32
Still on hold.

**Comment by strepanier03** [comment] 2024-03-06 03:05
Hold GH is still open.

**Comment by strepanier03** [comment] 2024-03-11 04:20
HOLD GH still open.

**Comment by strepanier03** [comment] 2024-03-19 21:45
HOLD Gh still open.

**Comment by strepanier03** [comment] 2024-03-27 19:20
Hold GH looks like it's going to move forward soon as we've decided on the behavior.

**Comment by strepanier03** [comment] 2024-04-16 22:14
HOLD GH is still open, pausing here.

**Comment by strepanier03** [comment] 2024-05-03 23:15
still on hold

**Comment by strepanier03** [comment] 2024-05-22 00:04
HOLD GH is still open.

**Comment by chiragsalian** [comment] 2024-06-26 20:50
Looks like the linked GH issue is closed. @akinwale @parasharrajat @strepanier03, can someone test and confirm if this issue still exists. Also can someone confirm if this is an internal or external issue.

**Closed** 2024-07-05 17:57 UTC
Labels: Engineering, Monthly, Internal, Bug
