### ISSUE TITLE
[$1000] IOS : Some pages of the app gets blinks rapaidly ,when user goes to online from offine

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23375] opened 2023-07-21 21:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.login to app
2.turn off the  wifi/mobile data data
3.open app
4.again  turn on the wifi/mobile data
5.Observe that, chat composer, about page, main chat listing page gets blinks
rapidly
## Expected Result: 
chat composer, about page, main chat listing page shouldn't blink ,when moves back to online from offline
## Actual Result: 

chat composer, about page, main chat listing page gets blinks
rapidly user, when moves back to online from offline

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Needs reproduction (Applause not able to reproduce)
**Reproducible in production?:** Needs reproduction (Applause not able to reproduce)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e4f276c9-2d03-4ef8-b3d6-1c907ebab65e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lincolnb17
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689825356877209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196e53ee378460eae</li>
        <li>Upwork Job ID: 1684046777134739456</li>
        <li>Last Price Increase: 2023-09-06</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-07-26 03:23
What iPhone is this on? I can't reproduce it on iPhone 14 Pro.

**Comment by lincolnb17** [comment] 2023-07-26 03:37
@JmillsExpensify  i tested iPhone 12 Pro Max

**Comment by JmillsExpensify** [comment] 2023-07-26 03:43
Going to open this issue up for the community, though of questionable value given that it's visual and doesn't appear on all iOS devices.

**Comment by abdulrahuman5196** [comment] 2023-07-31 18:46
No proposals yet

**Comment by JmillsExpensify** [comment] 2023-08-02 20:41
Let's give this one another test and then close if not reproducible.

**Comment by lincolnb17** [comment] 2023-08-03 07:41
@JmillsExpensify @mvtglobally  i am still able to reproduce in my iphone 12 pro max

https://github.com/Expensify/App/assets/47911127/059266b3-e251-4f6f-ad4d-7bfacf4243dc

**Comment by JKobrynski** [comment] 2023-08-04 08:30
@lincolnb17 Can you share what version of iOS you are using?

**Comment by lincolnb17** [comment] 2023-08-04 08:31
@JKobrynski 16.5.1 (c)

**Comment by abdulrahuman5196** [comment] 2023-08-08 17:40
@JmillsExpensify I am also unable to repro the issue. And just to note we don't have any proposals yet.

**Comment by abdulrahuman5196** [comment] 2023-08-13 13:08
@JmillsExpensify Bump

**Comment by JmillsExpensify** [comment] 2023-08-13 13:12
Not sure if we have a good process for this one. Several aren't able to reproduce but one person can. Still no proposals in any case.

**Comment by abdulrahuman5196** [comment] 2023-08-13 13:13
If we don't want to close this, should we increase bounty since there is no proposal yet?

**Comment by abdulrahuman5196** [comment] 2023-08-18 15:47
@JmillsExpensify Bump

**Comment by abdulrahuman5196** [comment] 2023-08-28 12:09
Pinged @JmillsExpensify in slack. He mentioned to look into this tomorrow

**Comment by JmillsExpensify** [comment] 2023-08-29 03:22
Given that QA hasn't been able to reproduce, I'm inclined to close rather than increase the bounty.

**Comment by abdulrahuman5196** [comment] 2023-08-29 08:35
@JmillsExpensify  Fine by me as well. We can close this. Not able to reproduce

**Comment by abdulrahuman5196** [comment] 2023-09-04 10:11
Bump @JmillsExpensify We can close this out IMO

**Comment by JmillsExpensify** [comment] 2023-09-07 02:10
Agreed, closing.

**Closed by JmillsExpensify** 2023-09-07 02:10 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
