### ISSUE TITLE
HIGH: Room - User automatically joins public room when accessing from search list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36078] opened 2024-02-07 21:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Admin sign into OldDot, create a new workspace
- Invite a member to the workspace in OldDot
- Run script to make a Workspace chat

1. [Admin] set NewDot to the workspace in the LHN
2. [Admin] click FAB button > Chat > Room > create a public room
3. [Admin] Do not add the workspace member to the room
4. [Employee] Open search list in LHN
5. [Employee] Search for the workspace visibility room > Click on the room
6. Click on title of room and notice the employee automatically joins

## Expected Result:
The employee does not automatically join the public room

## Actual Result:
The employee joins the public room without consent

## Workaround:
Unknowm

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0d1009b5-530b-4f19-b3ff-1bdfaf203c07

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d79ffec2c5589c5</li>
        <li>Upwork Job ID: 1755337783452950528</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by Christinadobrzyn** [comment] 2024-02-07 23:50
I can't reproduce this either, I'm unable to find the public room when searching as the employee. 

Here's where I can get: 

1. Admin and member are in the same workspace
2. [Admin] Create a workspace and public room
3. [Admin] Do not add the workspace member to the room
4. [Employee] Open search list
5. [Employee] Search for the workspace visibility room > NO ROOM SHOWS

https://github.com/Expensify/App/assets/51066321/e92deb1a-aa05-47f8-96ed-365eea0c1dd9

@lanitochka17 can you help me understand what I might be doing wrong?

**Comment by lanitochka17** [comment] 2024-02-08 14:22
@Christinadobrzyn Hello
You are not testing with the same workspace. Admin, member and the room must be under the same workspace A. In your video, you using workspace A for admin and room, then workspace B for employee.

**Comment by lanitochka17** [comment] 2024-02-08 14:22
![Screenshot 2024-02-08 at 09 47 17](https://github.com/Expensify/App/assets/78819774/a884a226-a3e7-4f71-b6a7-086871441600)

**Comment by Christinadobrzyn** [comment] 2024-02-08 20:55
Oh perfect! I can reproduce and I think this can be part of VSB. I think this can be external - collecting proposals!

**Comment by Christinadobrzyn** [comment] 2024-02-12 18:33
Thank you for the review @barros001! 

@DylanDylann should we change this to an Internal job based on @barros001 review?

**Comment by DylanDylann** [comment] 2024-02-14 09:20
I will check today, sorry for delay

**Comment by DylanDylann** [comment] 2024-02-14 17:10
@Christinadobrzyn This is a BE bug, please help to add an internal label

**Comment by Christinadobrzyn** [comment] 2024-02-14 17:42
Okay, changed the labels - waiting for this one to get picked! thanks for the review @DylanDylann

**Comment by Christinadobrzyn** [comment] 2024-02-21 19:48
waiting for this to get picked up

**Comment by Christinadobrzyn** [comment] 2024-02-23 23:57
Testing again - this is happening. Asking the team if we want users to automatically join.

**Comment by quinthar** [comment] 2024-02-25 08:58
Let's try to fix this before the next earnings call, which is the next time we will invite a lot of people to a public room.

**Comment by Christinadobrzyn** [comment] 2024-02-26 21:50
Confirmed with the team that we do not want to auto-join someone into a public room. So this will remain open to be fixed by someone internal

**Comment by Christinadobrzyn** [comment] 2024-02-27 20:01
reached out in Slack to see if someone might be able to grab this - https://expensify.slack.com/archives/C066HJM2CAZ/p1709064090733229

**Comment by Christinadobrzyn** [comment] 2024-02-28 18:28
This is waiting to get picked up internally

**Comment by Christinadobrzyn** [comment] 2024-03-04 20:25
waiting to be picket up internally

**Comment by Christinadobrzyn** [comment] 2024-03-07 01:10
asking what to do with this expense - https://expensify.slack.com/archives/C01SKUP7QR0/p1709772958396869

**Comment by Christinadobrzyn** [comment] 2024-03-11 01:33
sounds like we keep this on daily based on this convo -https://expensify.slack.com/archives/C01SKUP7QR0/p1710119796569089?thread_ts=1709650818.238009&cid=C01SKUP7QR0

**Comment by Christinadobrzyn** [comment] 2024-03-12 00:40
waiting for this to get picked up

**Comment by Christinadobrzyn** [comment] 2024-03-13 02:46
trying to find someone in the vip-vsb room

**Comment by Christinadobrzyn** [comment] 2024-03-19 05:53
testing the steps in the OP to see if this is still happening. Yes, this is still happening... reaching out again to try and get an engineer.

**Comment by Christinadobrzyn** [comment] 2024-03-19 05:58
Maybe @youssef-lr would you be able to grab this?

**Comment by mvtglobally** [comment] 2024-03-20 03:38
Issue not reproducible during KI retests. (First week)

**Comment by Christinadobrzyn** [comment] 2024-03-20 04:35
Hum, I'm pretty sure this is still happening... I'll ask QA for another test

**Comment by Christinadobrzyn** [comment] 2024-03-21 02:30
Okay - we'll keep this open and hope for a engineer soon!

**Comment by Christinadobrzyn** [comment] 2024-03-22 03:10
posted here asking for a volunteer - https://expensify.slack.com/archives/C066HJM2CAZ/p1710899254355639

**Comment by jasperhuangg** [comment] 2024-03-22 17:11
@quinthar Isn't this the expected behavior for public rooms? Why would we not want the user to join the room after clicking on it? My assumption for public rooms was that users join the rooms as soon as they open them if they aren't members already.

**Comment by quinthar** [comment] 2024-03-23 00:28
Well.... this is a good question.  It *was* the original design -- we intentionally implemented it this way.  But I think maybe we got cold feet.  But I can imagine this being a special feature of public rooms, that you "join on click".  So maybe I'll just close this for now and we can reopen in the future if we really think it's important.

**Closed by quinthar** 2024-03-23 00:28 UTC
Labels: Engineering, Daily, Internal, Bug, Hot Pick
