### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] Details - Dropdown Menu Floats in Composer After Minimizing and Maximizing Website

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40944] opened 2024-04-24 21:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Click on FAB > Start chat > Add email
2.  Click on the header > Upload photo
3. Minimize the webpage > Click on the avatar to display the dropdown
4. Maximize the webpage. Notice that the dropdown menu floats in the composer

## Expected Result:
The dropdown should align with the edit photo button and should not float in the composer

## Actual Result:
The dropdown menu when editing the group photo floats in the composer after minimizing and maximizing the website

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/36c4706b-8228-437c-9ba9-5b778b35d6f0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01875ffa1608bd2090</li>
        <li>Upwork Job ID: 1783639833104637952</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by lanitochka17** [comment] 2024-04-24 21:51
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-24 21:52
We think that this bug might be related to #vip-vsp

**Comment by jliexpensify** [comment] 2024-04-25 23:30
I can repro this one, and I think it should be in #collect - #vsb is around chat functionality, and this is to do with settings.

**Comment by DylanDylann** [comment] 2024-04-30 09:00
Looking for proposals

**Comment by jliexpensify** [comment] 2024-05-03 04:33
@DylanDylann just to confirm, [this one](https://github.com/Expensify/App/issues/40944#issuecomment-2077168008) was no good?

**Comment by DylanDylann** [comment] 2024-05-03 08:13
@jliexpensify Yes
@dragnoir's [proposal](https://github.com/Expensify/App/issues/40944#issuecomment-2077168008) doesn't include the solution for this issue. It is invalid

**Comment by jliexpensify** [comment] 2024-05-03 10:02
Ah thank you for that context!

**Comment by jliexpensify** [comment] 2024-05-05 23:01
Hi @dragnoir - thanks for reaching back out. Unfortunately, I don't have any say in choosing a Contributor - I'm here to project manage and pay out. Choosing the proposal is solely up to the C+, which will then be reviewed by an assigned Engineer.

I'll leave it up to @DylanDylann here, but perhaps you can address this [comment](https://github.com/Expensify/App/issues/40944#issuecomment-2093815593) and elaborate further?

**Comment by DylanDylann** [comment] 2024-05-06 03:24
@dragnoir Your [proposal](https://github.com/Expensify/App/issues/40944#issuecomment-2077168008) caused confused to me, you don't write anything in the section "What changes do you think we should make in order to solve the problem?"

**Comment by DylanDylann** [comment] 2024-05-06 03:25
@dragnoir Your [proposal](https://github.com/Expensify/App/issues/40944#issuecomment-2077168008) confused me, you didn't write anything in the section "What changes do you think we should make in order to solve the problem?"

**Comment by mvtglobally** [comment] 2024-05-06 19:55
Issue not reproducible during KI retests. (First week)

**Comment by jliexpensify** [comment] 2024-05-09 02:12
Yep, I also can't reproduce this! Going to close it.

**Comment by jliexpensify** [comment] 2024-05-14 00:23
Oh interesting - I can't repro myself. @DylanDylann can you?

**Comment by DylanDylann** [comment] 2024-05-15 09:56
I still can reproduce

**Comment by jliexpensify** [comment] 2024-05-15 10:25
Thanks, ok lets keep this open for more proposals!

**Comment by DylanDylann** [comment] 2024-05-15 10:27
@dragnoir's [proposal](https://github.com/Expensify/App/issues/40944#issuecomment-2077168008) looks good to me 
We need to confirm with design team about the vertical and horizontal margin, for me this looks good
```
popoverMenuOffset: (windowWidth: number) =>
                ({
                    ...getPopOverVerticalOffset(180),
                    horizontal: windowWidth - 60,
                } satisfies AnchorPosition),
```
🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-05-15 10:28
One more thing, I see the same bug happen in other popovers. @dragnoir Could you also address it ?

**Comment by jliexpensify** [comment] 2024-05-15 10:34
cc @Expensify/design for this [comment](https://github.com/Expensify/App/issues/40944#issuecomment-2112143051)

**Comment by shawnborton** [comment] 2024-05-15 13:07
In terms of the margin/offset, whatever it is currently doing looks good to me so I think we want to maintain that. 

Also, while I agree that is a bug, the fact is it is an edge case bug - I would imagine most people aren't resizing their browsers after opening the menu up. So that being said, thoughts on reducing the price of this one down to $125?

**Comment by DylanDylann** [comment] 2024-05-15 14:50
@shawnborton Agree with you that this is a minor bug, but our PR will not only fix the original bug, we will need to find the same bug in other places and fix it as [this suggestion](https://github.com/Expensify/App/issues/40944#issuecomment-2112144685). Thus, I think 250$ make sense in this issue

cc @jliexpensify

**Comment by shawnborton** [comment] 2024-05-15 15:10
Cool, that works for me.

**Comment by DylanDylann** [comment] 2024-05-17 08:23
@dragnoir Any update here?

**Comment by jliexpensify** [comment] 2024-05-31 01:08
Payment Summary

- C: @dragnoir $250
- C+: @DylanDylann $250

[Upwork job](https://www.upwork.com/jobs/~01875ffa1608bd2090)

Just waiting on checklist!

**Comment by DylanDylann** [comment] 2024-06-05 04:36
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


**Regression Test Proposal**
1. Click on FAB > Start chat > Add email
2. Click on the header > Upload photo
3. Minimize the webpage > Click on the avatar to display the dropdown
4. Maximize the webpage.
5. Verify that the dropdown align with the edit photo button and doesn't float in the composer


Do we agree 👍 or 👎

**Comment by jliexpensify** [comment] 2024-06-06 10:06
All paid and job closed, thanks for your help!

**Closed by jliexpensify** 2024-06-06 10:06 UTC
Labels: External, Weekly, Awaiting Payment, Bug
