### ISSUE TITLE
[Regression test steps needed] Buttons on Payments page are getting too opaque (when pressing/holding) than the rest of the app 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13479] opened 2022-12-09 18:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Go to settings > go to Payments
3. Add paypal account
4. click on your created paypal account
5. press and hold Delete option
6. Button will become too opaque to see what's written

## Expected Result:
 It should behave like the rest of the buttons on the app

## Actual Result : 
Too opaque in comparison to the rest of the buttons

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.37-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206773560-366ca47b-d039-4acd-a986-531f0312c44c.mov
<img width="952" alt="button opacity" src="https://user-images.githubusercontent.com/43996225/206773658-4b152e32-250a-4ea0-abc7-bb4c6e759fce.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670571668126639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191203dd57c90f4c1</li>
        <li>Upwork Job ID: 1603126586766036992</li>
        <li>Last Price Increase: 2022-12-14</li>
    </ul>
</details>

**Comment by daraksha-dk** [comment] 2022-12-09 19:33
### Proposal 
This issue is because of using `TouchableOpacity` Replacing `TouchableOpacity` with `Button` component will fix this issue
 https://github.com/Expensify/App/blob/a75a01e710f4035ccd3e4ea0e6c9bc1be04d863f/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L383-L389
Use `Button` like suggested below
```js
                            <Button
                                onPress={() => {
                                    this.setState({
                                        shouldShowDefaultDeleteMenu: false,
                                    });

                                    // Wait for the previous modal to close, before opening a new one. A modal will be considered completely closed when closing animation is finished.
                                    // InteractionManager fires after the currently running animation is completed.
                                    // https://github.com/Expensify/App/issues/7768#issuecomment-1044879541
                                    InteractionManager.runAfterInteractions(() => {
                                        this.setState({
                                            shouldShowPasswordPrompt: true,
                                            passwordButtonText: this.props.translate('paymentsPage.setDefaultConfirmation'),
                                        });
                                    });
                                }}
                                text={this.props.translate('paymentsPage.setDefaultConfirmation')}
                            />
  
```
https://github.com/Expensify/App/blob/a75a01e710f4035ccd3e4ea0e6c9bc1be04d863f/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L406-L410

Use `Button` like suggested below
```js
                            <Button
                                onPress={() => {
                                    this.setState({
                                        showConfirmDeleteContent: true,
                                    });
                                }}
                                style={shouldShowMakeDefaultButton && styles.mt4}
                                danger
                                text={this.props.translate('common.delete')}

                            />
```


Make the changes suggested below at https://github.com/Expensify/App/blob/a75a01e710f4035ccd3e4ea0e6c9bc1be04d863f/src/components/PasswordPopover/BasePasswordPopover.js#L85
```diff
-                    <TouchableOpacity
+                    <Button
                         onPress={() => this.props.onSubmit(this.state.password)}
-                        style={[
-                            styles.button,
-                            styles.mt3,
-                            styles.w100,
-                        ]}
-                    >
-                        <Text style={[styles.buttonText]}>
-                            {this.props.submitButtonText}
-                        </Text>
-                    </TouchableOpacity>
+                        style={styles.mt3}
+                        text={this.props.submitButtonText}
+                    />
                 </View>
```

**Comment by michaelhaxhiu** [comment] 2022-12-13 20:59
Looking

**Comment by michaelhaxhiu** [comment] 2022-12-13 20:59
@shawnborton do you reckon this is a bug? It seems it's only when you press & hold?

**Comment by michaelhaxhiu** [comment] 2022-12-13 21:02
Screenshots of how other buttons look when you click and hold (e.g. don't click & release):

<img width="409" alt="image" src="https://user-images.githubusercontent.com/13206896/207442690-2d8fe768-9530-4d4a-8935-b0d0e0abfc78.png">


<img width="404" alt="image" src="https://user-images.githubusercontent.com/13206896/207442699-57353af1-1e4c-4c4d-9f4f-d6d18969075a.png">

**Comment by michaelhaxhiu** [comment] 2022-12-13 21:03
@daraksha-dk can you clarify why you think the behavior is inconsistent with other buttons? What other buttons in New Expensify are you looking at to be specific?

**Comment by francoisl** [comment] 2022-12-14 19:58
Hi @daraksha-dk, if I understand correctly, the issue same issue would also occur anywhere we use a `TouchableOpacity` as a "button", right? In that case, it sounds like we'd also benefit from updating IOUPreview [here](https://github.com/Expensify/App/blob/11cf5642823abe0656b8db63937718e0b04d0f87/src/components/ReportActionItem/IOUPreview.js#L194-L197) at the same time.

This is what it looks like when you click the Pay button on an IOU at the moment:
<img width="655" alt="image" src="https://user-images.githubusercontent.com/2229301/207701604-2c8d11ff-e773-41a5-b391-b1e8d024096a.png">

**Comment by daraksha-dk** [comment] 2022-12-14 20:17
@francoisl oh yeah, correct. I missed that place. I have updated my proposal to handle that as well.

**Comment by francoisl** [comment] 2022-12-14 20:35
Thanks for the update, the proposal sounds good.

I also forgot to mention, the issue didn't have the `External` label applied. In order to give every contributor a fair chance to submit a proposal, it's best not to submit a proposal until the label is applied (And we're actually in the process of [locking issues](https://github.com/Expensify/App/issues/13395) until the External label is applied).

I'm going to apply the label now to follow the process and will run a quick test locally with your proposal.

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-15 00:26
Proposal :- 

Instead of replacing `TouchableOpacity` with `Button` we can use default property of activeOpacity={0.5} in all `TouchableOpacity` Buttons to resolve this issue.

After Fix :-

<img width="1178" alt="Screenshot 2022-12-15 at 5 25 22 AM" src="https://user-images.githubusercontent.com/81307212/207743968-1c906b12-91b7-4f30-9630-71b747a2f3d6.png">

**Comment by francoisl** [comment] 2022-12-15 02:46
@syedsaroshfarrukhdot to clarify, are you suggesting that we use `activeOpacity` with **all** `TouchableOpacity` components, or just the ones that are currently used as buttons (i.e. have a `styles.button`, `styles.buttonMedium` etc. applied)?

Also out of curiosity, why `0.5` as a value and not something else?

**Comment by aneequeahmad** [comment] 2022-12-15 05:06
### PROPOSAL

Solution 01:

As `TouchableOpacity` is already used in many components and styled in a way that it can be used as `a link` or `a button on composer, for actionable icons like settings, search `

Here we should set the `activeOpacity={0.8}` as this value has already been set in components that already use `TouchableOpacity` like the component below(Its a row but the activeOpacity is almost same as of button

https://github.com/Expensify/App/blob/bb8a5dc6c2fbcedf7d01849000fcab02ee5f5226/src/components/OptionRow.js#L117-L127

**Comment by dhairyasenjaliya** [comment] 2022-12-15 10:08
@francoisl @shawnborton is the payment page getting refactored? as previously we closed issues related to payment pages based on this comment https://github.com/Expensify/App/issues/10493#issuecomment-1229930529 to push password popup to page


https://github.com/Expensify/App/issues/10509
https://github.com/Expensify/App/issues/10493

**Comment by mananjadhav** [comment] 2022-12-15 10:29
I am travelling today and I'll check the proposals in a few hours.

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-15 10:31
@dhairyasenjaliya As discussed above this isn't the issue with payment page. If you follow the issue discussion it is the issue with TouchableOpacity design not being consistent with Button design.

**Comment by michaelhaxhiu** [comment] 2022-12-15 15:28
>Thanks for the update, the proposal sounds good.


@francoisl are you saying [the proposal](https://github.com/Expensify/App/issues/13479#issuecomment-1344710243) from @daraksha-dk is the winning proposal thus far? I suppose we need @mananjadhav to give his C+ 👍 too before we know for sure?

**Comment by mananjadhav** [comment] 2022-12-15 17:48
I think we're fine to update the `TouchableOpacity` with a `Button`. I saw we add these buttons with TouchableOpacity, in this [PR](https://github.com/Expensify/App/pull/4437). Can't pinpoint any strong reason to stick to it.

Let's go ahead with @daraksha-dk's proposal.

@francoisl All yours.

**Comment by francoisl** [comment] 2022-12-15 18:30
> @francoisl are you saying https://github.com/Expensify/App/issues/13479#issuecomment-1344710243 from @daraksha-dk is the winning proposal thus far? 

I was curious if there was an alternative proposal that could also prevent this issue moving forward, because I guess nothing prevents someone from using a `<TouchableOpacity>` with a button style moving forward. But I agree @daraksha-dk's proposal makes the code more consistent in using `<Button>` for... buttons, so let's go with that!

**Comment by daraksha-dk** [comment] 2022-12-15 23:24
PR up for review

**Comment by mananjadhav** [comment] 2022-12-22 17:53
PR was deployed to production yesterday, but the payout date wasn't updated!

**Comment by mananjadhav** [comment] 2022-12-29 01:19
This is due for payment today (payment title isn't updated!)

**Comment by mallenexpensify** [comment] 2022-12-29 02:37
@mananjadhav and @daraksha-dk hired, final payments should be 
$1500 - @mananjadhav for C+ + plus timeliness bonus
$1750 for @daraksha-dk for contributor + reporting + timeliness bonus (I accidentally hired for $250, so bonus will be $1k)

can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0191203dd57c90f4c1

**Comment by mananjadhav** [comment] 2022-12-29 04:07
Accepted @mallenexpensify

**Comment by mallenexpensify** [comment] 2022-12-30 01:21
@mananjadhav paid $1500
@daraksha-dk paid $250 and bonused $1500 = $1750

Leaving open, think we need regression test steps added @michaelhaxhiu @francoisl 

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by francoisl** [comment] 2023-01-03 23:17
I don't think this is a regression, it looks like we were using `<TouchableOpacity>` from the start in these components. The issue became apparent when we started rolling out the new dark theme.

- `BasePasswordPopover` and `BasePaymentPage` used `TouchableOpacity` since https://github.com/Expensify/App/pull/4437
- `IOUPreview` used `TouchableOpacity` since https://github.com/Expensify/App/pull/2394/files#diff-3597ac886dade8ed106d403fad7c534b6a0fd9423bf6081877749b0295fb3bc8R110

**Comment by francoisl** [comment] 2023-01-11 01:56
I checked Testrail and there is no existing test flow where this could properly fit. This was also not a regression, so I'm going to close now that everybody got paid.

**Closed by francoisl** 2023-01-11 01:56 UTC
Labels: Reviewing, External, Daily, Bug
