### ISSUE TITLE
[HOLD for payment 2022-09-26] [$250] TextField(Composer) is not focused again when group chat participants Details drawer is closed - Reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10886] opened 2022-09-08 04:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any group chat or create a new group chat from + icon on LHN
2. Click on top header to open chat participants details.
3. Click on cross icon of Details.

## Expected Result:
TextInput should be focused

## Actual Result:
TextInput isn't focused

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.96-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
potentially related to https://github.com/Expensify/App/issues/10414

https://user-images.githubusercontent.com/43995119/189034190-22c26871-5599-4157-b8ab-97d3f99b6bf0.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661285952608309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment] 2022-09-08 09:48
Internal upwork job: https://www.upwork.com/ab/applicants/1567811708523073536/job-details
External upwork job: https://www.upwork.com/jobs/~01f274e1ebbcbe68a6

**Comment by sanjayradadiya** [comment] 2022-09-08 11:16
Need to fire text focus again when we close drawer on on drawer close event

**Comment by hashirafique** [comment] 2022-09-08 12:47
Hello, I just explored about your company Expensify and the work you people are doing is great. I visited this github link and watched the video and understand that you want this text field to stay focused even when we click on the details of a user. From my initial understanding, you are having some issues with your CSS Psuedo Classes such as focus and active. And if you require further edition in the website on ReactJS then I'll be right person to do so.

For editing, I would first of all trace down its component where this is written and then afterwards as I have mentioned above that as per my understanding there is an issue with the CSS Pseudo CLasses then I'll change that class to the right one. However I feel that there's the similar issue on every text field so I'll trace their components and edit them as per your requirement. Furthermore I'll edit this code as per your requirement which is mentioned below.


Looking forward to hearing from you.

Regards,
Hashir

https://www.upwork.com/ab/proposals/1567856788281503745?success This is my upwork proposal

**Comment by mollfpr** [comment] 2022-09-08 13:48
### Proposal

**Root cause**
To focus the composer it depends on `modal.isVisible`. But currently when open `ReportParticipantsPage`, the Onyx key of `modal.isVisible` is not set to `true` and instead has a `false` value even after the page is closed.
https://github.com/Expensify/App/blob/1718572434eafd9c3a816653c6eb8a95054e958c/src/pages/home/report/ReportActionCompose.js#L162-L174

There's a modal listener to set the `modal.isVisible` when the modal is focused or before closing, but the screen definition with not set the modal screen listener to the `ReportParticipantsPage` so that's why the `modal.isVisible` value will still to be a `false`.
https://github.com/Expensify/App/blob/1718572434eafd9c3a816653c6eb8a95054e958c/src/libs/Navigation/AppNavigator/AuthScreens.js#L260-L264

**Solution**
Adding the modal screen listeners to the screen option.
```diff
diff --git a/src/libs/Navigation/AppNavigator/AuthScreens.js b/src/libs/Navigation/AppNavigator/AuthScreens.js
index 3454a6847..335adbec4 100644
--- a/src/libs/Navigation/AppNavigator/AuthScreens.js
+++ b/src/libs/Navigation/AppNavigator/AuthScreens.js
@@ -261,6 +261,7 @@ class AuthScreens extends React.Component {
                     name="Participants"
                     options={modalScreenOptions}
                     component={ModalStackNavigators.ReportParticipantsModalStackNavigator}
+                    listeners={modalScreenListeners}
                 />
                 <RootStack.Screen
                     name="IOU_Request"
```


**Result**


https://user-images.githubusercontent.com/25520267/189139092-a19c9fd2-a982-4814-85e8-c9016c8cea45.mov

**Comment by puneetlath** [comment] 2022-09-12 13:27
@mollfpr very clear proposal thanks. Let's do it!

**Comment by mollfpr** [comment] 2022-09-12 15:15
Applied to Upwork and PR raised, thanks!

**Comment by puneetlath** [comment] 2022-09-13 12:59
Thanks! @aneequeahmad can you please also apply to the Upwork job?

**Comment by aneequeahmad** [comment] 2022-09-13 15:55
@puneetlath I have applied to the Upwork job. Thanks

**Comment by puneetlath** [comment] 2022-09-27 00:13
All paid. Thanks everyone!

**Closed by puneetlath** 2022-09-27 00:13 UTC
Labels: Exported, External, Engineering, Daily, Awaiting Payment
