### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] [TS Migration] Standartize between Boolean or !!

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39126] opened 2024-03-27 22:59 UTC
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Standartize between Boolean or !!

Lets pick the one which can be enforced with eslint

Any more details for this one cc @blazejkustra @fabioh8010
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01111a2979f5f2ac8c</li>
        <li>Upwork Job ID: 1780333266166345728</li>
        <li>Last Price Increase: 2024-04-16</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 0</li>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by blazejkustra** [comment] 2024-04-09 07:54
@ShridharGoel Not yet, let's wait until migration is fully finished

**Comment by fabioh8010** [comment] 2024-04-11 06:41
This is on hold Melvin..

**Comment by blazejkustra** [comment] 2024-04-15 09:06
**Details:**

We want to standardize with just one approach, !! and Boolean() are almost identical and we want to ensure just one is used in the codebase to avoid cases like this 😅
```ts
offline = Boolean(network.shouldForceOffline) || !!network.isOffline;
```

This includes writing a proposal on Slack, adjusting the code in the repository and perhaps adding an eslint rule that ensures only one approach is used. I myself believe !! is more readable more concise and faster in runtime.

**This issue requires a minimal understanding of how Expensify process works, before coding the contributor have to post a Problem/Solution on open-source channel**

**Comment by blazejkustra** [comment] 2024-04-15 11:21
The issue is still on hold, please wait until it's open for external contributors @ShridharGoel

**Comment by mountiny** [comment] 2024-04-16 20:32
In the proposal for this issue please write the slack problem/ solution statement to present in favour of the option you want to standardize on as Blazej mentioned:

> This includes writing a proposal on Slack, adjusting the code in the repository and perhaps adding an eslint rule that ensures only one approach is used. I myself believe !! is more readable more concise and faster in runtime.

**Comment by roryabraham** [comment] 2024-04-16 20:38
> I myself believe !! is ... faster in runtime

@blazejkustra what makes you say this?

**Comment by blazejkustra** [comment] 2024-04-16 22:14
Read some articles and benchmarks on the topic, sorry for not linking before:
- [Benchmark](https://www.measurethat.net/Benchmarks/Show/11127/0/boolean-vs)
- [Boolean() or !! (double bang, double negation)?](https://gist.github.com/arthurvi/66cb1e2bcfc92f99f465e0db04264367#performance)
 

Also some interesting posts here:
- [Boolean doesn't narrow down type the same way as !! does](https://stackoverflow.com/questions/66788887/react-typescript-why-does-boolean-behave-differently-than-double-not-op)
```ts
/* eslint-disable react/function-component-definition */
import React from 'react';

type Props = {
    myNumber: number | null;
};

const Test: React.FC<Props> = ({myNumber}) => (
    <>
        {/* Example 1 */}
        {!!myNumber && <span>{myNumber.toString()}</span>}

        {/* Example 2 */}
        {Boolean(myNumber) && <span>{myNumber.toString()}</span>} // error here
    </>
);

export default Test;
```
- [Some positive opinions on reddit in favor of `Boolean`](https://www.reddit.com/r/typescript/comments/oty3jl/opinions_on/)

**Comment by saifelance** [comment] 2024-04-17 03:09
> Triggered auto assignment to @CortneyOfstad (`NewFeature`), see https://stackoverflowteams.com/c/expensify/questions/14418#:~:text=BugZero%20process%20steps%20for%20feature%20requests for more details. Please add this Feature request to a GH project, as outlined in [the SO](https://stackoverflowteams.com/c/expensify/questions/14418#:~:text=Add%20the%20issue%20to%20a%20GH%20project).



> Triggered auto assignment to Contributor-plus team member for initial proposal review - @ntdiary (`External`)

@MelvinBot 

// ESLint rule for enforcing Boolean usage
module.exports = {
    create: function(context) {
        return {
            UnaryExpression: function(node) {
                if (node.operator === "!" && node.argument.type === "UnaryExpression" && node.argument.operator === "!") {
                    context.report({
                        node: node,
                        message: "Use Boolean instead of !!",
                        fix: function(fixer) {
                            const sourceCode = context.getSourceCode();
                            const start = node.range[0];
                            const end = node.argument.range[1];
                            const argumentText = sourceCode.getText(node.argument);
                            return fixer.replaceTextRange([start, end], `Boolean(${argumentText})`);
                        }
                    });
                }
            }
        };
    }
};


 if the decision is to standardize on !!, the ESLint rule should be adjusted accordingly:
 
 
 // ESLint rule for enforcing !! usage
module.exports = {
    create: function(context) {
        return {
            CallExpression: function(node) {
                if (node.callee.type === "Identifier" && node.callee.name === "Boolean" && node.arguments.length === 1) {
                    context.report({
                        node: node,
                        message: "Use !! instead of Boolean",
                        fix: function(fixer) {
                            const sourceCode = context.getSourceCode();
                            const argumentText = sourceCode.getText(node.arguments[0]);
                            return fixer.replaceText(node, `!!${argumentText}`);
                        }
                    });
                }
            }
        };
    }
};

**Comment by saifelance** [comment] 2024-04-17 03:12
https://www.upwork.com/freelancers/saifurrehman

**Comment by saifelance** [comment] 2024-04-17 03:21
***@***.***
https://www.upwork.com/freelancers/saifurrehman

**Comment by saifelance** [comment] 2024-04-17 10:10
> Started the discussion on this: https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1713329747825759

Unable to access, I think need to allow permission?

**Comment by saifelance** [comment] 2024-04-17 14:22
proposal sent

**Comment by CortneyOfstad** [comment] 2024-04-17 14:35
@ntdiary when you have a chance, can you review the proposal above and provide any feedback? Thank you!

**Comment by CortneyOfstad** [comment] 2024-04-17 14:41
No worries! Feel free to post and and we can get that adjusted!

**Comment by CortneyOfstad** [comment] 2024-04-17 14:59
I agree @ishpaul777 — and thanks for taking this on!

**Comment by saifelance** [comment] 2024-04-17 15:19
> I dont have strong opinions, but i like consizeness with `!!` over `Boolean()` if we put it up for vote i'd 👍 for`!!`

Yes. Another solution is to standardize the usage of !!. In this scenario, the ESLint check should ensure that !! is consistently used instead of Boolean.

Depending on the decision, appropriate changes should be made to the ESLint configuration and rules.

**Comment by saifelance** [comment] 2024-04-17 15:52
@MelvinBot @CortneyOfstad I sent above both solutions code updates, it was ignore or rejected work?

**Comment by saifelance** [comment] 2024-04-19 11:52
@MelvinBot I sent my proposal on Upwork job, did you check?

**Comment by saifelance** [comment] 2024-04-19 15:10
Kindly send Slack invite chanel : ***@***.***

**Comment by roryabraham** [comment] 2024-04-19 17:32
I'm not sure we had broad enough consensus yet, posted a proposal [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1713547892853379)

**Comment by mountiny** [comment] 2024-04-20 18:25
Seems like we are now good to move ahead with !!

**Comment by CortneyOfstad** [comment] 2024-04-22 14:30
@ishpaul777 can you provide a follow-up on the proposal that fits the clarification on `!!`? If we can get an assignment ready  to roll, that would be great 👍

**Comment by roryabraham** [comment] 2024-04-25 23:34
@ShridharGoel when do you estimate you'll have a PR ready for review?

**Comment by roryabraham** [comment] 2024-04-26 19:45
thanks for the update!

**Comment by CortneyOfstad** [comment] 2024-05-01 15:41
Any update @ishpaul777 on the PR review? Thanks!

**Comment by CortneyOfstad** [comment] 2024-05-06 14:38
Thanks @ishpaul777!

**Comment by fabioh8010** [comment] 2024-05-13 08:15
@aldo-expensify kindly bump 🙂

**Comment by CortneyOfstad** [comment] 2024-05-13 13:35
Not overdue — just waiting for @aldo-expensify to review PR [here](https://github.com/Expensify/eslint-config-expensify/pull/96) 👍

**Comment by aldo-expensify** [comment] 2024-05-13 18:13
There is a problem with the commits signing, left comment in the PR

**Comment by CortneyOfstad** [comment] 2024-05-15 17:47
@ShridharGoel it looks like there is some outstanding comments on the PR. Can you please have those addressed by EOD today? Thanks!

**Comment by CortneyOfstad** [comment] 2024-05-20 14:33
Freeze will be done on Wednesday evening, so will re-address then!

**Comment by CortneyOfstad** [comment] 2024-05-21 13:10
@ishpaul777 Unfortunately, the overdue label cannot be removed until @ShridharGoel comments as they have the star indicating action is waiting on them. 

@ShridharGoel can you please provide the PR by EOD?

**Comment by CortneyOfstad** [comment] 2024-05-22 13:47
@ShridharGoel bump on the update please

**Comment by CortneyOfstad** [comment] 2024-06-05 16:38
PR is being actively reviewed so no additional update at this stage!

**Comment by CortneyOfstad** [comment] 2024-06-19 13:04
@ishpaul777 can you confirm if this needs a regression test please before EOD to help avoid a delay in payment? Thank you!

**Comment by CortneyOfstad** [comment] 2024-06-20 18:22
Bump @ishpaul777 ^^^

**Comment by CortneyOfstad** [comment] 2024-06-20 18:27
@ShridharGoel I had to reinvite you to the job post because for some reason you were not listed in Upwork — let me know once you accept and I can get that paid ASAP!

**Comment by CortneyOfstad** [comment] 2024-06-24 19:35
@ShridharGoel let me know once you accept and I can get this paid ASAP. Thanks!

**Comment by CortneyOfstad** [comment] 2024-06-25 13:28
## Payment Summary

@ishpaul777 — paid $250 via Upwork
@ShridharGoel — paid $250 via Upwork

**Closed by CortneyOfstad** 2024-06-25 13:28 UTC
Labels: External, Daily, NewFeature, Task, Awaiting Payment, Typescript Migration
