### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] Request Money - Error Does not disappear when returning back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29774] opened 2023-10-17 14:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697510382480569

## Action Performed:
1. FAB > Request Money >Manual
2. Click next without entering a valid amount.
Notice an error will appear.
3. Switch or Go to 'Scan' or 'Distance' in the header.
4. Return to 'Manual'
Notice the error is still there

## Expected Result:
Error disappears when returning back

## Actual Result:
Error Does not disappear when returning back

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/9af11ed9-5396-40a6-a302-c2c36b2f1464

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/74c22739-1029-414d-93ff-6918e67a77af

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/fed9d92e-b03f-4a01-823c-6773b57be8bc

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/e3fdde92-dbbf-4ecc-a642-85ed0773bb48

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/c4900b11-98fb-483e-adff-48c2c9250c7d

https://github.com/Expensify/App/assets/93399543/62bda051-be19-4598-9c90-1bcb66a8f3bf

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/3904fd57-af9d-4880-bece-4eab601b3fbd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b128a1e4d22d1251</li>
        <li>Upwork Job ID: 1714280416375877632</li>
        <li>Last Price Increase: 2023-10-31</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27548886</li>
<li>daveSeife | Reporter | 27548887</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by DylanDylann** [comment] 2023-10-17 14:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error Does not disappear when returning back in request money
### What is the root cause of that problem?
Currently when user switches between tabs in request money iou, component [MoneyRequestAmountForm](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequestAmountForm.js) will not unmount and still has `formError` when user back to `Manual` tab

### What changes do you think we should make in order to solve the problem?
1. Pass `selectedTab` as a prop in https://github.com/Expensify/App/blob/91e2120e647aa9ee22171b6dbb772b4aebe64992/src/pages/iou/steps/NewRequestAmountPage.js#L153-L160
2. Every time A changes, we will reset `formError`
- We should add `useEffect` in [MoneyRequestAmountForm](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequestAmountForm.js) 
```
 useEffect(()=>{
        setFormError('')
    }, [selectedTab])
```
### What alternative solutions did you explore? (Optional)

**Comment by Nathan-Mulugeta** [comment] 2023-10-17 14:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error message doesn't clear when changing tabs and coming back. 

### What is the root cause of that problem?
The root cause of this problem is here in the `MoneyRequestAmountForm` page, we can see here that typing an amount clears the error: 
https://github.com/Expensify/App/blob/be44c93037fe165d6e3aec7445044c371bcbc921/src/pages/iou/steps/MoneyRequestAmountForm.js#L136-L138

But we are not clearing the error when the selected tab is changed. 

### What changes do you think we should make in order to solve the problem?
We can pass a prop `selectedTab`: 
https://github.com/Expensify/App/blob/be44c93037fe165d6e3aec7445044c371bcbc921/src/pages/iou/steps/NewRequestAmountPage.js#L153-L160
like this: 
```javascript
<MoneyRequestAmountForm
            isEditing={isEditing}
            currency={currency}
            amount={iou.amount}
            ref={(e) => (textInput.current = e)}
            onCurrencyButtonPress={navigateToCurrencySelectionPage}
            onSubmitButtonPress={navigateToNextPage}
            selectedTab={selectedTab} //Add this line
        />
```
and add a useEffect on `MoneyRequestAmountForm` page to clear the error whenever we change tabs: 
```javascript
 useEffect(() => {
        setFormError('');
    }, [selectedTab]);
```

### What alternative solutions did you explore? (Optional)
We can also follow the pattern we used on `DistanceRequest` component to remove the error
https://github.com/Expensify/App/blob/4c1ae82a1bb2fa0c087df6e9778bc2e45f8e7e1b/src/components/DistanceRequest/index.js#L99-L111
Instead of passing the selectedTab to `MoneyRequestAmountForm` we can pass the transactionID
```javascript
<MoneyRequestAmountForm
            isEditing={isEditing}
            currency={currency}
            amount={iou.amount}
            ref={(e) => (textInput.current = e)}
            onCurrencyButtonPress={navigateToCurrencySelectionPage}
            onSubmitButtonPress={navigateToNextPage}
            transactionID={iou.transactionID} //Add this line
        />
```
and add a useEffect on `MoneyRequestAmountForm` page to clear the error whenever the transactionID changes: 
```javascript
 useEffect(() => {
        setFormError('');
    }, [transactionID]);
```

**Comment by strepanier03** [comment] 2023-10-17 21:48
Easy to recreate:

<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/10925636/5c181329-a8fa-40dd-8300-4bc3c66a7334">
<img width="1901" alt="image" src="https://github.com/Expensify/App/assets/10925636/d0db3832-1f46-4489-9b80-f2d371cf6313">

error still visible

<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/10925636/973872f4-ce50-448f-a339-179b86b20d52">

**Comment by Santhosh-Sellavel** [comment] 2023-10-20 17:27
Will review proposal today

**Comment by Santhosh-Sellavel** [comment] 2023-10-20 22:26
@strepanier03  Yes easy to recreate but is that expected behavior can you check and confirm with the Product team, please?

**Comment by strepanier03** [comment] 2023-10-24 15:40
[Raised](https://expensify.slack.com/archives/C049HHMV9SM/p1698161994017699?thread_ts=1697510382.480569&cid=C049HHMV9SM) it @Santhosh-Sellavel - My recommendation is for closing it because the error is correct, the amount is still invalid.

**Comment by daveSeife** [comment] 2023-10-24 17:03
@strepanier03 if you do the same thing in 'distance' section, the error is dismissed when going back. 

Switch to distance > click next. Notice an error is shown 
Now switch to scan and switch back to Distance. The error is gone.

**Comment by strepanier03** [comment] 2023-10-27 21:45
I'll have to circle back to this next week.

**Comment by Santhosh-Sellavel** [comment] 2023-10-29 12:55
Any update @strepanier03?

**Comment by strepanier03** [comment] 2023-10-30 22:58
I didn't get any traction on the discussion raised. It makes sense to me we should be consistent in this behavior and in the example @daveSeife shared we do clear the error when switching. Let's move forward with being consistent with that.

**Comment by Santhosh-Sellavel** [comment] 2023-11-03 14:31
> I didn't get any traction on the discussion raised. It makes sense to me we should be consistent in this behavior and in the example @daveSeife shared we do clear the error when switching. Let's move forward with being consistent with that.

Okay then @DylanDylann [proposal](https://github.com/Expensify/App/issues/29774#issuecomment-1766483011) looks good.

C+ Reviewed
🎀 👀 🎀

**Comment by strepanier03** [comment] 2023-11-06 18:19
@dangrous - When you're online for the week can you review [this](https://github.com/Expensify/App/issues/29774#issuecomment-1792540853) and if you agree assign the contributor?

**Comment by dangrous** [comment] 2023-11-06 22:33
Yeah let's clear the error. That proposal works for me!

**Comment by DylanDylann** [comment] 2023-11-07 13:51
I am working on PR

**Comment by DylanDylann** [comment] 2023-11-08 03:40
@Santhosh-Sellavel PR https://github.com/Expensify/App/pull/31040 is ready for review

**Comment by Santhosh-Sellavel** [comment] 2023-11-27 14:13
_**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [ ]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR:
* [ ]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
* [ ]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
* [ ]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug.
* [ ]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@strepanier03] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:_

**Comment by strepanier03** [comment] 2023-11-27 19:08
My apologies for the delay here everyone! I was out most of last week for the US holiday but I'm working on this now and will have an update shortly.

**Comment by strepanier03** [comment] 2023-11-28 22:44
@Santhosh-Sellavel - Sorry I missed your comment right before mine yesterday with the checklist. It appears empty to me though, was that a bad copy paste?

**Comment by Santhosh-Sellavel** [comment] 2023-11-29 18:19
### Regression Test Steps

Bug: Request Money - Error Does not disappear when returning back

Steps
1. FAB > Request Money >Manual
2. Click next without entering a valid amount.
3. Notice an error will appear.
4. Switch or Go to 'Scan' or 'Distance' in the header.
5. Return to 'Manual'
6. Verify that the error disappeared

**Comment by strepanier03** [comment] 2023-11-29 23:26
Thanks @Santhosh-Sellavel - I'll work on the regression test now and then post the payment summary.

**Comment by strepanier03** [comment] 2023-11-29 23:29
## Payment summary

- [x] External issue reporter - @daveSeife - $50 via Upwork
- [x] Contributor that fixed the issue - @DylanDylann - $500 via Upwork
- [ ] Contributor+ that helped on the issue and/or PR - @Santhosh-Sellavel - $500 via Manual Requests

@JmillsExpensify @Santhosh-Sellavel - Please submit your Manual Request for payment.

**Comment by strepanier03** [comment] 2023-11-29 23:30
This can be closed once your request is paid. Let me know or close if you can.

**Comment by strepanier03** [comment] 2023-12-04 21:51
@Santhosh-Sellavel - Have you submitted your request for payment yet?

**Comment by Santhosh-Sellavel** [comment] 2023-12-05 02:41
Yes submitted last week

**Comment by strepanier03** [comment] 2023-12-05 22:39
@JmillsExpensify - Friendly bump on the payment for the C+. Santhosh says they submitted their request last week. Feel free to close this GH once you pay it or @mention me so I can do ti.

**Comment by strepanier03** [comment] 2023-12-06 20:40
Thank you @Santhosh-Sellavel for moving that and @JmillsExpensify for checking in and helping us wrap this up.

**Comment by dangrous** [comment] 2023-12-08 21:23
I think we're just waiting on payment of the (new) request, right? Anything else we need?

**Comment by JmillsExpensify** [comment] 2023-12-11 01:13
P.S. @strepanier03 In the future, no need to hold issues open for NewDot payments.

**Closed** 2023-12-11 01:12 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
