### ISSUE TITLE
[$500] Tag - No violation message for missing tag when tag is not selected

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36889] opened 2024-02-20 14:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition::
- User is an employee of Collect workspace.
- The Collect workspace has tags and Tag is set to "Required".
1. Navigate to staging.new.expensify.com
2. Go to workspace chat.
3. Create a manual request without tag.
4. Navigate to request details page.

## Expected Result:
There will be a violation message for missing tag.

## Actual Result:
There is no violation message for missing tag.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/59f134da-ba49-4548-9188-6e079fba4773

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01651062d96a32e6ea</li>
        <li>Upwork Job ID: 1759949751406247936</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-20 14:35
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by pecanoro** [comment] 2024-02-20 16:16
Found the PR and left a comment to see what we do next since we might have a PR in progress

**Comment by rezkiy37** [comment] 2024-02-20 16:25
I am an author of a broken PR. However, I see that there is already a work in progress. If you need any help from me, please let me know.

**Comment by kmbcook** [comment] 2024-02-20 21:58
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Tag - No violation message for missing tag when tag is not selected, for manual money request.

### What is the root cause of that problem?
Tag is not treated as a required field, in workspace money request when it should be.

### What changes do you think we should make in order to solve the problem?
Check policy to see if tag is required. If so, treat tag field as required in the same way that merchant field is required. Doing so will not permit user to create a manual money request without tag.

**Comment by cead22** [comment] 2024-02-21 16:55
Violations are in beta so this shouldn't be a blocker, and I'm working on the fix

**Comment by pecanoro** [comment] 2024-03-05 19:56
This is on prod already, closing!

**Closed by pecanoro** 2024-03-05 19:56 UTC
Labels: Reviewing, Engineering, Daily
