### ISSUE TITLE
[$500] Web - Wallet - BlockingViews component has grey background and another animation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33905] opened 2024-01-03 20:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32253

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Wallet -> Press Enable wallet

## Expected Result:
The BlockingViews component has a white background and same animation as in PR's video

## Actual Result:
The BlockingViews component has a grey background and another animation as in PR`s video and prod

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/38f3b09e-fc64-4abd-b44b-7ab759730605)

https://github.com/Expensify/App/assets/93399543/39c64274-e80e-42cf-a973-1ff7d010cc31

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2760f292f8f6de8</li>
        <li>Upwork Job ID: 1742949003985174528</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by Beamanator** [comment] 2024-01-03 21:58
@cdOut @0xmiroslav @joelbettner it looks like this could have been caused due to your typescript migration PR: https://github.com/Expensify/App/pull/32253

Anyone free to take a look? I'd prefer not to revert if possible

**Comment by marcaaron** [comment] 2024-01-03 22:26
This feels like it can be fixed as a follow up as it is a small UI issue.

**Comment by Beamanator** [comment] 2024-01-03 22:31
Hmm ya this doesn't seem like a blocker if it's just a style / animation diff... Also i don't see how that would have been changed by the linked typescript PR, may have another cause

**Comment by Beamanator** [comment] 2024-01-03 22:32
I did NOT mean to remove the bug label...

**Comment by Beamanator** [comment] 2024-01-03 22:32
I did NOT mean to remove the bug label...

**Comment by cdOut** [comment] 2024-01-04 12:27
> @cdOut it looks like this could have been caused due to your typescript migration PR: #32253

@Beamanator I will look into whether this is an issue caused by my PR and get back to you.

**Comment by cdOut** [comment] 2024-01-05 15:28
The lack of animation and a gray background is caused by the Plaid Link somehow being in the sandbox environment on staging, instead of a development/production one. This couldn't really be something caused by a TS migration issue, seems like there were changes to the API keys for staging / backend changes for the Plaid setup.

**Comment by cdOut** [comment] 2024-01-05 15:39
After reviewing it seems like this is the correct behaviour. When using the staging web version of the app we by default have the preferences option "Use Staging Server" enabled, causing the Plaid connections to use the sandbox version for testing, which has limited animations and a different background. If we switch the staging server option off, we get the production version.

In short, this isn't a bug and is the correct behavior for when you are using the staging server for Plaid connections. If you want the production version on the staging web app, you have to switch that option off in Preferences as shown in video.

https://github.com/Expensify/App/assets/88325488/a7ed3201-e79a-4179-9f5d-3e9e89f5c5c8

**Comment by cdOut** [comment] 2024-01-08 07:39
cc: @Beamanator @0xmiroslav

**Comment by MitchExpensify** [comment] 2024-01-08 23:54
> In short, this isn't a bug and is the correct behavior for when you are using the staging server for Plaid connections.

Do you think @cdOut is right about this being expected? @Beamanator @marcaaron 

The grey background certainly seems to be the case in OldDot on staging too

<img width="883" alt="image" src="https://github.com/Expensify/App/assets/36425901/58849c82-e928-48a7-be8d-d379f23d0d29">

**Comment by MitchExpensify** [comment] 2024-01-10 23:39
> can we make sure TestRail is updated so we don't create issues like this again in the future?

@kbecciv do you think we need to update anything in TestRrail to avoid Sandbox causing us to think this is a bug again?

**Comment by MitchExpensify** [comment] 2024-01-13 20:25
Friendly bump on the above @kbecciv

**Comment by MitchExpensify** [comment] 2024-01-22 01:12
Confirmed with @kbecciv that this wasn't caught via TestRail, its was caught in [this PR](https://github.com/Expensify/App/pull/32253), so we don't have to update anything - Closing

**Closed by MitchExpensify** 2024-01-22 01:12 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
