### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] No animation for Members and Invite Members page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25860] opened 2023-08-24 15:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on you avatar and open settings
2. Go to workspaces and open any workspace
2. Click on Members and Notice the RHP animation
3. Then Click on Invite and Notice the animation
## Expected Result: 
Opening Members and Invite members should be animated
## Actual Result: 
There is no animation for Members and Invite Members page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 24-08-23 09_25_07.webm](https://github.com/Expensify/App/assets/43996225/061b92fe-2331-4169-a413-db5c4ffc8197)

https://github.com/Expensify/App/assets/43996225/4c902ac2-0309-489e-8aa6-521de0443adf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692860888835619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd938c0400af0e16</li>
        <li>Upwork Job ID: 1694755918563115008</li>
        <li>Last Price Increase: 2023-08-24</li>
<li>Automatic offers: </li>
<ul>
<li>DrLoopFall | Contributor | 26308867</li>
<li>Ahmed-Abdella | Reporter | 26308869</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-08-24 15:36
Related to #22622

**Comment by DrLoopFall** [comment] 2023-08-24 15:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

No animation for Members and Invite Members page

### What is the root cause of that problem?

The Members page and Invite Members page have `TextInput` with autofocus, which breaks the animation.

### What changes do you think we should make in order to solve the problem?

Adding `ShouldDelayFocus` to `SelectionList`, would fix the animation.

### What alternative solutions did you explore? (Optional)

Use `onEntryTransitionEnd` to focus the `TextInput`, after the animation is completed.

**Comment by roryabraham** [comment] 2023-08-24 16:57
Not going to block deploy on this, but it's a valid bug we should fix

**Comment by shubham1206agra** [comment] 2023-08-24 16:59
@roryabraham If this is not a blocker then I think you should add this to the tracking https://github.com/Expensify/App/issues/11795

**Comment by roryabraham** [comment] 2023-08-24 17:01
> Use onEntryTransitionEnd to focus the TextInput, after the animation is completed.

@DrLoopFall I actually think that this is a more robust solution so we should use that instead of the `setTimeout` approach. I'm inclined to accept @DrLoopFall's proposal and not put this on HOLD needlessly, but I'll check with @mountiny first.

**Comment by roryabraham** [comment] 2023-08-24 17:12
@mountiny agrees, no need to put this on HOLD

**Comment by CortneyOfstad** [comment] 2023-08-24 17:15
Thanks @roryabraham!

**Comment by roryabraham** [comment] 2023-08-24 18:03
@DrLoopFall feel free to submit the PR as soon as it's ready. Thanks!

**Comment by DrLoopFall** [comment] 2023-08-24 18:05
@roryabraham Working on it, I'll submit the PR soon.

**Comment by b4s36t4** [comment] 2023-08-24 18:57
@roryabraham I believe there is no full explanation for the above proposal on how `onEntryTransitionEnd` would solve the issue. If there is a full proposal other people could weigh in and propose their solutions as well right? maybe the proposed solution might be having some flaws are so. Hope you understand thanks.

@DrLoopFall Hoping you'd update your proposal, also good proposals help others to learn a lot.

**Comment by DrLoopFall** [comment] 2023-08-24 22:23
@roryabraham @sobitneupane
The PR #25894 is ready for review.

**Comment by roryabraham** [comment] 2023-08-24 23:50
> I believe there is no full explanation for the above proposal on how onEntryTransitionEnd would solve the issue.

Fair call-out. The proposal could have used some more detail.

> If there is a full proposal other people could weigh in and propose their solutions as well right? maybe the proposed solution might be having some flaws are so. Hope you understand thanks.

Yep, thanks for the feedback! In this case I'm going to proceed with reviewing the pull request from @DrLoopFall

**Comment by roryabraham** [comment] 2023-08-25 00:28
@DrLoopFall I requested some changes on that PR. Thanks!

**Comment by thiagobrez** [comment] 2023-08-25 08:14
Just FYI: This has been previously seen here: https://github.com/Expensify/App/issues/24139

And discussed here: https://expensify.slack.com/archives/C01GTK53T8Q/p1692307751392999

**Comment by thiagobrez** [comment] 2023-08-25 11:47
PR being reviewed here: https://github.com/Expensify/App/pull/25921

**Comment by DrLoopFall** [comment] 2023-08-25 16:06
@roryabraham 
Looks like this issue has been fixed in #25921 now.
Since I've already made a PR will I be compensated for this?

**Comment by roryabraham** [comment] 2023-08-25 16:26
@DrLoopFall yes, you'll be compensated 👍🏼

**Comment by roryabraham** [comment] 2023-08-28 19:31
This will be handled separately as part of [this issue](https://github.com/Expensify/App/issues/11795#issuecomment-1694033011), but @CortneyOfstad  let's make sure to pay @DrLoopFall $1000 for the PR, even though it wasn't merged.

**Comment by Ahmed-Abdella** [comment] 2023-08-28 20:45
Hi, @roryabraham  what about reporting bonus in that case?

**Comment by roryabraham** [comment] 2023-09-03 18:02
@Ahmed-Abdella yes, I think we should pay the reporting bonus here as well 👍

**Comment by sakluger** [comment] 2023-09-05 18:13
@roryabraham - A [single PR](https://github.com/Expensify/App/pull/25921) fixed multiple issues including this one, and a different GH issue (https://github.com/Expensify/App/issues/25890) was reported first in expensify-bugs in Slack. Generally we only pay out for the first bug report, I'll let @CortneyOfstad make the final decision.

**Comment by Ahmed-Abdella** [comment] 2023-09-05 18:23
But they are two different issues and this wouldn't be fixed without this report.

**Comment by CortneyOfstad** [comment] 2023-09-06 14:45
Asking internally about this [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694011524128739).

**Comment by CortneyOfstad** [comment] 2023-09-08 15:25
Bumped the thread again. Will update as soon as I can 👍

**Comment by Ahmed-Abdella** [comment] 2023-09-08 15:55
Hey @CortneyOfstad , I would like to clarify one thing. How could this issue be resolved without this report? it will only be resolved after the report is made. If It was just the first issue that was reported, this issue would not be fixed. I believe that this report serves its purpose. Please do not misunderstand me, I am OK with whatever decision the team makes. I just want to comprehend the process.

**Comment by CortneyOfstad** [comment] 2023-09-11 14:43
@Ahmed-Abdella the team determined that we only pay a reporting bonus once per PR. If the PR fixes multiple bugs, that means they all had the same root cause and we only pay the initial report that caused the PR to be created/deployed. 

Because of that, the reporting bonus will not be applied here.

**Comment by CortneyOfstad** [comment] 2023-09-11 14:47
Payment has been made to @DrLoopFall and contract completed in Upwork 👍

**Comment by CortneyOfstad** [comment] 2023-09-11 14:48
@roryabraham update on the checklist above? ^^^

**Comment by roryabraham** [comment] 2023-09-14 03:10
@CortneyOfstad done!

**Comment by DrLoopFall** [comment] 2023-09-14 07:21
**BugZero Checklist:** 

* [x]  [@DrLoopFall] Determine if we should create a regression test for this bug: No, since it's not an impactful bug, I don't think we need a regression test.

* [x]  [@DrLoopFall] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md?rgh-link-date=2023-08-30T01%3A09%3A42Z) steps to ensure the same bug will not reach production again: N/A

**Comment by CortneyOfstad** [comment] 2023-09-14 18:07
Sounds good! Are we able to close this out?

**Comment by CortneyOfstad** [comment] 2023-09-18 19:49
Closing this out — feel free to reopen if needed 

CC @DrLoopFall @roryabraham

**Closed by CortneyOfstad** 2023-09-18 19:49 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
