### ISSUE TITLE
Preferences -  The description of Priority mode does not match the logic

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23903] opened 2023-07-30 21:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open setting
2. Preferences
3. Priority mode, Observe that explainer text does not match focus mode

## Expected Result:
The description of the focus mode must match the logic including: pined, unread and draft item

## Actual Result:
 Explainer text does not match logic focus mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-30 at 01 19 33](https://github.com/Expensify/App/assets/93399543/6a866079-852c-418a-8fe3-f1d738bb8ba1)

![image (12)](https://github.com/Expensify/App/assets/93399543/f75af13e-92c0-477a-bd4a-3095a9fdbe05)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690654739888759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-07-30 21:27
**Proposal by**: @namhihi237
**Slack conversation**: https://expensify.slack.com/archives/C049HHMV9SM/p1690654739888759


## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The description of the focus mode must match the logic including: pined, unread and draft item
### What is the root cause of that problem?
Currently, the logic of the show report on LHN of focus mode is unread, pined, and drafted but the description for focus is incomplete and confusing for users.
### What changes do you think we should make in order to solve the problem?
We need to update the description for focus mode here:
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/languages/en.js#L667
Can be like this:
`Choose whether to show all chats by default sorted with most recent with pinned items at the top, or #focus on unread, pinned, and draft items, sorted alphabetically.`
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/languages/en.js#L675
`Show unread, pined, and draft sorted alphabetically`
And Spanish translation
### What alternative solutions did you explore? (Optional)
N/A

**Comment by jeet-dhandha** [comment] 2023-07-31 05:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Explainer Text doesn't match Priority modes description.

### What is the root cause of that problem?
- The description was changed in the below commit.
    - PR: https://github.com/Expensify/App/pull/14591
    - Commit: https://github.com/jeet-dhandha/Expensify-App/commit/4384921f0e48bb382d72d1af8dbfc93ecc460b5b

### What changes do you think we should make in order to solve the problem?
- We can first update explainer text as below:
    - BEFORE: Choose whether to show all chats by default sorted with most recent with pinned items at the top, or #focus on unread pinned items, sorted alphabetically.
    - UPDATED: Choose whether to show all chats sorted with the most recent and pinned items at the top by default, or #focus on unread and pinned chats sorted alphabetically. (Fixed some writing issues using grammerly)
    - UPDATED SPANISH: Elige si mostrar todas las conversaciones ordenadas con las más recientes y los elementos anclados en la parte superior de manera predeterminada, o #enfocarse en las conversaciones no leídas y ancladas ordenadas alfabéticamente.

- Now we also need to update #focus mode's description:
    - BEFORE: Only show unread sorted alphabetically
    - UPDATED: Only show unread and pinned chats, sorted alphabetically.
    - Updated SPANISH: "Mostrar solo chats no leídos y anclados, ordenados alfabéticamente."

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by jeet-dhandha** [comment] 2023-07-31 05:34
Now i forgot about the draft items will update that shortly. 👍

**Comment by tjferriss** [comment] 2023-08-01 21:28
Determining whether we assign copy updates externally. Discussing [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1690925150461569).

**Comment by tjferriss** [comment] 2023-08-03 18:28
I'm going to close this out as it's more of an improvement suggestion rather than a bug preventing someone from using the app.

**Closed by tjferriss** 2023-08-03 18:28 UTC
Labels: Daily, Bug
