### ISSUE TITLE
[$500][MEDIUM] Categories: Search field is present in category list when there are fewer than 8 categories to choose from

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37329] opened 2024-02-27 17:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace
- The Collect workspace has less than 8 categories
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Open request money page
4. Create manual request and proceed to confirmation page
5. Click Show more > Category

## Expected Result:
There will be no search field because there are less than 8 categories

## Actual Result:
Search field is present when there are less than 8 categories

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3dc8e614-40ac-402a-844f-4443b64b497b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110ba1eec3b905bcd</li>
        <li>Upwork Job ID: 1762535661381767168</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-27 17:50
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by puneetlath** [comment] 2024-02-27 18:22
Definitely a bug, but doesn't need to block the deploy. Removing the label.

**Comment by jasperhuangg** [comment] 2024-03-01 18:55
Waiting for proposals

**Comment by akinwale** [comment] 2024-03-04 09:32
I am unable to reproduce this. Seems it has already been fixed on main.

https://github.com/Expensify/App/blob/4231ac90a8f6efa0249c925a06adbb9ef4d7a54a/src/components/CategoryPicker.tsx#L67

**Closed** 2024-03-04 18:40 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
