### ISSUE TITLE
[$500] [Not Implementing] Web - Chat - Clicking on unpin does not return cursor to conversation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18534] opened 2023-05-06 19:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with any account.
2. Open any conversation.
3. Click pin and unpin.

## Expected Result:
Cursor in conversation should be appear when unpin is clicked.

## Actual Result:
Clicking on unpin does not return cursor to conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/236643857-5df847ad-f937-4fad-a9fe-4f8aa39789f0.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb8588dfccface1a</li>
        <li>Upwork Job ID: 1655660886629089280</li>
        <li>Last Price Increase: 2023-05-23</li>
    </ul>
</details>

**Comment by PrashantMangukiya** [comment] 2023-05-07 07:58
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
Web - Chat - Clicking on unpin does not return cursor to conversation

### What is the root cause of that problem?
We are using `Pressable` for pin/unpin button as shown below:
https://github.com/Expensify/App/blob/d120f6a9aa13dc842e265202996f8fe32019faca/src/pages/home/HeaderView.js#L194-L199

So for onPress we are calling `Report.togglePinnedState(props.report)` at line 195 and there is not any code to set focus on composer, So upon button click it will toggle report state only and not do anything else. This is the root cause of the problem.

### What changes do you think we should make in order to solve the problem?
When we press pin/unpin button, first we have to call `Report.togglePinnedState()` and then we have to set focus on composer as shown in updated code below.
```javascript
 <Pressable
    onPress={() => {
        Report.togglePinnedState(props.report);
        ReportActionComposeFocusManager.focus();
    }}
    ....
>
   ...
</Pressable>
```
So this will solve the issue i.e. When pin/unpin button tap it will set focus to composer as shown in result video.

### What alternative solutions did you explore? (Optional)
None

<details>
<summary>Results</summary>

https://user-images.githubusercontent.com/7823358/236664674-f59e5a44-ae98-4f62-9a6b-4395a442d502.mov

</details>

**Comment by therealsujitk** [comment] 2023-05-07 08:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The composer input field doesn't get refocused after the pin/unpin button has been clicked. Behaviour should be similar to when modals are closed.

### What is the root cause of that problem?

The cause of this problem is that there's no case to handle this issue. To detect if modals are being closed across the app, we check for modal visibility before and after state updates here.

https://github.com/Expensify/App/blob/d120f6a9aa13dc842e265202996f8fe32019faca/src/pages/home/report/ReportActionCompose.js#L257-L263

### What changes do you think we should make in order to solve the problem?


To fix this similar to the way it is done for modals, I suggest checking for the current and previous values of `isPinned`.

```js
// We want to focus or refocus the input when the pin/unpin button has been clicked.
// We detect this click by checking if it was previously true/false
if (this.willBlurTextInputOnTapOutside && this.props.report.isPinned !== prevProps.report.isPinned) {
    this.focus();
}
```

> Note: This takes care of preventing the keyboard from being opened unnecessarily on native platforms as well.

[Screencast from 07-05-23 01:37:29 PM IST.webm](https://user-images.githubusercontent.com/60378235/236665639-327b42e4-b322-4ff1-bc3b-d56bc44f23c8.webm)

### What alternative solutions did you explore? (Optional)

- An alternative solution would be to use the `focus()` function in `ReportActionComposeFocusManager` as mentioned in a previous proposal.

**Comment by alitoshmatov** [comment] 2023-05-08 20:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking on unpin does not return cursor to conversation
### What is the root cause of that problem?
It is expected behavior of current code, since we don't have any code to handle focus when pin button is pressed. 
### What changes do you think we should make in order to solve the problem?
We should simply add 
```javascript
onMouseDown={e => e.preventDefault()}
``` to this pin button here
https://github.com/Expensify/App/blob/d120f6a9aa13dc842e265202996f8fe32019faca/src/pages/home/HeaderView.js#L194-L199
as we are doing all over the project to prevent losing focus. 
One thing to note, if we rather add focus method inside onpress, composer will actual lose focus and refocus again, thus resulting in flickering effect.
### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2023-05-08 22:44
@PrashantMangukiya Thanks for the proposal. Since this is more a feature request than a bug there can be many valid RCA. Your RCA is valid. However the suggested fix is not what we are looking for since the focus will be lost already.

**Comment by s77rt** [comment] 2023-05-08 22:53
@therealsujitk Thanks for the proposal. Although you linked a good piece of code in your RCA, I think we follow that pattern only on modals where the focus would be actually shifted (forcely). This case is a little different.

**Comment by s77rt** [comment] 2023-05-08 23:02
@alitoshmatov Thanks for the proposal. Your RCA is correct. The suggested fix looks good to me. That's indeed how we prevent elements from loosing focus (as seen on send button, expand & collapse buttons, etc.).

:ribbon: :eyes: :ribbon: C+ reviewed

cc @Beamanator

**Comment by alitoshmatov** [comment] 2023-05-09 09:52
Applied to the job, PR will be ready in couple of hours

**Comment by alitoshmatov** [comment] 2023-05-09 15:09
Pr is ready - https://github.com/Expensify/App/pull/18643

**Comment by situchan** [comment] 2023-05-09 16:56
Same [issue](https://github.com/Expensify/App/issues/17538) was closed as not a bug after discussion.
There was already same [solution](https://github.com/Expensify/App/issues/17538#issuecomment-1515169038) if that issue wasn't closed.

**Comment by s77rt** [comment] 2023-05-09 19:00
Thanks @situchan!

@roryabraham We are proceeding with a solution here (calling `preventDefault` on `mouseDown`) since this is a pattern that we follow to prevent losing focus e.g. [prevent losing focus on clicking the send button](https://github.com/Expensify/App/blob/f946eb63588e9cb70d4371517e3518f8d04a8f9f/src/pages/home/report/ReportActionCompose.js#L973-L974). Let us know if you think we should close this instead.

**Comment by s77rt** [comment] 2023-05-12 23:12
PR is ready. Will probably get merged on Monday.

Also @roryabraham for the above comment ^

**Comment by Beamanator** [comment] 2023-05-15 11:08
@s77rt In my opinion, the issue @situchan linked (https://github.com/Expensify/App/issues/17538) is **NOT** the same as this issue. Here's why:
1. In this issue, we're talking about maintaining focus in the compose box when clicking a button that doesn't have any modal popup opening / closing
2. In the other issue, one problem was that device defaults were getting in the away, and we didn't want to introduce any "hacks" just to keep platforms consistent.

In this case, just "keeping focus on the compose box when clicking the `Pin` button" doesn't seem like it will have any unintended consequences, so I'm for moving forward with the PR (https://github.com/Expensify/App/pull/18643).

Thoughts before we move forward?

**Comment by s77rt** [comment] 2023-05-16 10:44
Discussing on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1684233792150649).

**Comment by tjferriss** [comment] 2023-05-18 13:25
Closing after some discussion in Slack.

**Comment by Beamanator** [comment] 2023-05-23 08:47
@tjferriss Even though we decided to close this issue, I think we should consider compensating @alitoshmatov and @s77rt since:
1. @alitoshmatov created the PR: https://github.com/Expensify/App/pull/18643
2. @s77rt did all the tests (https://github.com/Expensify/App/pull/18643#issuecomment-1540672721) and review

I'd propose we compensate $500 each since this was quite a small change & small PR, and we ended up not implementing the solution. Thoughts?

**Comment by s77rt** [comment] 2023-05-26 18:14
@tjferriss Applied!

**Comment by s77rt** [comment] 2023-05-29 12:15
@tjferriss Can we close this?

**Comment by tjferriss** [comment] 2023-05-30 20:21
@s77rt I just sent you an offer. Once accepted, I can pay and close the issue.

**Comment by s77rt** [comment] 2023-05-30 20:24
@tjferriss Accepted!
We still need to pay @alitoshmatov

**Comment by tjferriss** [comment] 2023-05-30 20:59
Yes, you've both been paid now.

**Closed by tjferriss** 2023-05-30 20:59 UTC
Labels: External, Daily, Not a priority, Bug
