### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] Original message is displayed for few seconds after adding emoji reaction on edited message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21826] opened 2023-06-28 17:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open the app in another device and login with user B
3. From user B, send message to user A
4. From user A, open user B report, hover on latest sent message and click on Add reaction
5. From user B, edit the message
6. Observe in user A, the user B message is displayed edited, from the current open emoji picker for reaction, click on any emoji to add reaction
7. Observe that after adding the reaction, app displays older (message before edit) for few seconds

## Expected Result:
App should not display older message i.e. message before edit on adding reaction to edited message

## Actual Result:
App displays older message i.e. message before edit on adding reaction to edited message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9db1ed99-c6e8-445e-bfc8-93ad2fcde9c8

https://github.com/Expensify/App/assets/93399543/bc2d776e-8a2a-4066-9852-c7e949267100

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687870862782029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a60dfce3c07cce2</li>
        <li>Upwork Job ID: 1674267414000873472</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-06-28 20:56
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
- Problem is user is seeing old message for few seconds when someone edits the message, before the user add's emoji to the message.

### What is the root cause of that problem?
- The reportAction given to `Report.toggleEmojiReaction` function is not updated with the latest message.

### What changes do you think we should make in order to solve the problem?
- We can access the latest message using `reportID` and `reportActionID` and pass it to a function `ReportActionsUtils.getReportAction(reportID, reportActionID)` (which i had to create) and now use this `reportAction` for further code.

<details>

<summary> Code for `toggleEmojiReaction` </summary>

```js
function toggleEmojiReaction(reportID, reportAction, emoji, paramSkinTone = preferredSkinTone) {
    const latestReportAction = ReportActionsUtils.getReportAction(reportID, reportAction);
    const message = latestReportAction.message[0];
    const reactionObject = message.reactions && _.find(message.reactions, (reaction) => reaction.emoji === emoji.name);
    const skinTone = emoji.types === undefined ? null : paramSkinTone; // only use skin tone if emoji supports it
    if (reactionObject) {
        if (hasAccountIDReacted(currentUserAccountID, reactionObject.users, skinTone)) {
            return removeEmojiReaction(reportID, latestReportAction, emoji, skinTone);
        }
    }
    return addEmojiReaction(reportID, latestReportAction, emoji, skinTone);
}
```

</details>


### What alternative solutions did you explore? (Optional)
- N/A

**Comment by s-alves10** [comment] 2023-06-28 20:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

When user opens the emoji picker from the reaction bar, `openEmojiPicker` is called
https://github.com/Expensify/App/blob/d1a743c3d6ed9ff3767e6da93daf9a604c45a781/src/components/Reactions/MiniQuickEmojiReactions.js#L59-L71

The value of `props.onEmojiSelected` is defined when `openEmojiPicker` is called. So `reportAction` value of the `onEmojiSelected` function when emoji is selected would have the value of when user opens the emoji picker.

https://github.com/Expensify/App/blob/53e4154143052649ed7b2b8df302cd1744f31f67/src/pages/home/report/ContextMenu/ContextMenuActions.js#L60-L63
This is the root cause

### What changes do you think we should make in order to solve the problem?

We can get latest `reportAction` in `toggleEmojiReaction` function
https://github.com/Expensify/App/blob/53e4154143052649ed7b2b8df302cd1744f31f67/src/libs/actions/Report.js#L1641

```
    const action = _.get(allReportActions, [reportID, reportAction.reportActionID], reportAction);
```

The final function would look like
```
function toggleEmojiReaction(reportID, reportAction, emoji, paramSkinTone = preferredSkinTone) {
    const action = _.get(allReportActions, [reportID, reportAction.reportActionID], reportAction);
    const message = action.message[0];
    const reactionObject = message.reactions && _.find(message.reactions, (reaction) => reaction.emoji === emoji.name);
    const skinTone = emoji.types === undefined ? null : paramSkinTone; // only use skin tone if emoji supports it
    if (reactionObject) {
        if (hasAccountIDReacted(currentUserAccountID, reactionObject.users, skinTone)) {
            return removeEmojiReaction(reportID, action, emoji, skinTone);
        }
    }
    return addEmojiReaction(reportID, action, emoji, skinTone);
}
```

This works as expected.

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/2701b880-71c2-4c7a-a93e-2709e39a5dbf


</details>

### What alternative solutions did you explore? (Optional)

**Comment by jeet-dhandha** [comment] 2023-06-28 21:02
### Comment : https://github.com/Expensify/App/issues/21826#issuecomment-1612093829

Check below video for fix if necessary.

<details>
<summary> Fixed Video </summary>

https://github.com/Expensify/App/assets/78416198/1b524557-d81a-4d08-923f-35e1db961db8

</details>

**Comment by jliexpensify** [comment] 2023-06-28 21:53
Did some Android issues for Sophie, so doing an issue swap as I'm a bit swamped today and working 50%.

**Comment by sophiepintoraetz** [comment] 2023-06-29 04:03
Able to reproduce!
![2023-06-29_16-01-39 (1)](https://github.com/Expensify/App/assets/42940078/d77a4f87-7c2a-4747-995f-5d55d9044c4e)

**Comment by neil-marcellini** [comment] 2023-06-29 19:41
> @jeet-dhandha i agree with the root cause and the [solution](https://github.com/Expensify/App/issues/21826#issuecomment-1612093829).

Sounds good to me too thanks!

**Comment by jeet-dhandha** [comment] 2023-06-29 23:38
@neil-marcellini @rushatgabhane - Will create a PR and send here.

**Comment by sophiepintoraetz** [comment] 2023-06-29 23:41
@dhanashree - do you mind doing this please?
>The BZ member will need to manually hire dhanashree for this role Reporter. Please store your Upwork details and apply to our Upwork job so this process is automatic in the future!

**Comment by dhanashree-sawant** [comment] 2023-06-30 03:34
Hi @sophiepintoraetz, sorry I didn't get it, should I apply to the job?

**Comment by dhanashree-sawant** [comment] 2023-06-30 03:42
Melvin bot has marked wrong profile, my tag is @dhanashree-sawant

**Comment by jeet-dhandha** [comment] 2023-06-30 03:53
PR: https://github.com/Expensify/App/pull/21933.

Thanks 🙏 .

**Comment by jeet-dhandha** [comment] 2023-07-05 14:21
Regression: https://github.com/Expensify/App/issues/22235

**Comment by jeet-dhandha** [comment] 2023-07-07 04:12
@rushatgabhane Any updates on this one ?

**Comment by rushatgabhane** [comment] 2023-07-13 05:44
I think @aimane-chnaif is working on the review for regression https://github.com/Expensify/App/pull/22270

**Comment by sophiepintoraetz** [comment] 2023-07-14 14:58
Okay so @jeet-dhandha - can you confirm whether your PR introduced a regression? If so, it is correct that is a 50% deduction for you, @rushatgabhane? (So 1500/2 = $750)

Lastly, what is needed to close out this issue?

**Comment by jeet-dhandha** [comment] 2023-07-14 15:01
@sophiepintoraetz There’s a pr which needs to be merged before mine so waiting for that.

**Comment by sophiepintoraetz** [comment] 2023-07-14 15:03
Okay but to be clear, your PR did not introduce a regression?

**Comment by jeet-dhandha** [comment] 2023-07-14 15:06
It introduced on DEV env, basically someone was testing on main branch and had a issue in reacting with emoji in a thread chat’s first message. So i fixed it before it can go to Stagging. But my PR was not merged due to this https://github.com/Expensify/App/pull/17996 PR.

**Comment by jeet-dhandha** [comment] 2023-07-14 15:08
So you can somewhat count it as a regression on DEV end.

**Comment by jeet-dhandha** [comment] 2023-07-14 15:08
Any idea on when can we merge that PR ?

**Comment by sophiepintoraetz** [comment] 2023-07-14 15:11
Okay so we actually can't release payment until the 7 day window has passed. I think if a regression is introduced in production, that would have the penalty applied...so you're lucky! And Rushat will be best placed to say when we can merge.

**Comment by dhanashree-sawant** [comment] 2023-07-14 15:34
Hi @sophiepintoraetz, I have accepted the offer, you have also sent invite for that job so not accepting that as offer already accepted.

**Comment by jeet-dhandha** [comment] 2023-07-17 20:49
Waiting for @stitesExpensify to complete the requested changes on this PR : https://github.com/Expensify/App/pull/17996 and then i will have to make changes accordingly for my PR and then we will be able to complete this. @stitesExpensify if you need any help completing it quicker do tell me.

**Comment by dhanashree-sawant** [comment] 2023-07-19 03:49
Hi @sophiepintoraetz, I just got another offer for this issue from @trjExpensify and I understood that it was already paid after accepting it. Not sure what to do about it, kindly suggest.

**Comment by dhanashree-sawant** [comment] 2023-07-19 04:13
Most probably offer was for #20423 as @trjExpensify sent me offer with this issue title and had mentioned that offer was sent on that issue.

**Comment by trjExpensify** [comment] 2023-07-19 22:10
Yeah, I just fudged the contract title on #20243. My bad! Paid that one out anyhow!

**Comment by neil-marcellini** [comment] 2023-07-19 22:28
Not overdue

**Comment by jeet-dhandha** [comment] 2023-07-20 09:10
@aimane-chnaif should i take a pull from`main` branch on. My current branch or should i create a new branch and make changes there?

**Comment by jeet-dhandha** [comment] 2023-07-20 11:07
Thanks will do that.

**Comment by sophiepintoraetz** [comment] 2023-07-24 04:18
@jeet-dhandha @aimane-chnaif @rushatgabhane - can we confirm the PR for this issue has merged with no regressions in the last 7 days? I'm not sure why we're talking about creating/editing branches if the PR has merged?

**Comment by rushatgabhane** [comment] 2023-07-24 04:40
@sophiepintoraetz i think they're talking about a different issue.

But the bottom line is this -
@jeet-dhandha's PR caused a regression.
So no timeline bonus is applicable 

@jeet-dhandha - $1000 (or $500 not sure)
@rushatgabhane - $500

**Comment by sophiepintoraetz** [comment] 2023-07-24 04:48
Got it - thanks. @anmurali or @JmillsExpensify will pay you $500 in NewDot once you've completed the checklist [here](https://github.com/Expensify/App/issues/21826#issuecomment-1625182028)!

**Comment by sophiepintoraetz** [comment] 2023-07-24 04:51
Payment issue to Jeet and contract ended - closing.

**Closed by sophiepintoraetz** 2023-07-24 04:51 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by jeet-dhandha** [comment] 2023-07-24 05:12
@sophiepintoraetz wondering does the payment gets 1/3rd when received ?

**Comment by sophiepintoraetz** [comment] 2023-07-24 05:32
@jeet-dhandha - see the comment from the c+ [here](https://github.com/Expensify/App/issues/21826#issuecomment-1647196446)

**Comment by JmillsExpensify** [comment] 2023-07-27 04:39
Reviewed details for @rushatgabhane. This is accurate and approved for payment in NewDot.
