### ISSUE TITLE
[HOLD] [$500] Height of dropdown menu increases - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8719] opened 2022-04-21 04:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Click on actions > send money > add amount and click the next button
3. Now click on the dropdown arrow while the keyboard is open

## Expected Result:
Height of dropdown menu should remain same

## Actual Result:
Height of dropdown menu increases

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/164372506-2283370d-1ad8-4ddc-8c75-61116218a83e.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648882929562619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tylerkaraszewski** [comment] 2022-04-26 19:20
Seems legit and external.

**Comment by adelekennedy** [comment] 2022-04-26 22:16
[Internal](https://www.upwork.com/ab/applicants/1519077783430582272/job-details)
[External](https://www.upwork.com/jobs/~015eab27c03120d240)

**Comment by akhilesh-mourya** [comment] 2022-04-27 03:45
Hello @mvtglobally, the dropdown height issue seems to be happening due to improper handling of the dropdown open animation start time delay. UI usually shows this kind of issue where two animations are happening together at the same time. In our case, the keyboard is closing and the dropdown is opening at the same time. 

I can fix this issue.

**Comment by parasharrajat** [comment] 2022-04-27 15:41
Hi @akhilesh-mourya, Could you please share your proposal? Were you able to reproduce this issue?

**Comment by neil-marcellini** [comment] 2022-05-03 16:42
@parasharrajat I'm new to CME, is there anything we can do here to get more eyes on this, or another response, or do we keep waiting?

**Comment by parasharrajat** [comment] 2022-05-03 17:11
Waiting...😅

**Comment by neil-marcellini** [comment] 2022-05-09 16:09
@akhilesh-mourya any update?
> Hi @akhilesh-mourya, Could you please share your proposal? Were you able to reproduce this issue?

**Comment by adelekennedy** [comment] 2022-05-13 16:33
Still waiting - we're at the point where we typically double issues to attract more contributors @neil-marcellini

**Comment by neil-marcellini** [comment] 2022-05-13 16:59
Ok that sounds like a good idea.

**Comment by srikarparsi** [comment] 2022-05-16 21:56
I'm not able to reproduce this issue. I ran it on Safari on my iPhone

https://user-images.githubusercontent.com/48188732/168688872-3092c140-da9c-42ed-b410-d153f82ca999.MP4

.

**Comment by parasharrajat** [comment] 2022-05-17 11:05
This is not the dropdown height instead of the backdrop. When the keyboard is closed, dropdown reposition and the backdrop takes some to reposition itself. The backdrop has a dark background and the canvas behind it is white same as the dropdown. During repositioning the background behind the backdrop seems to be part of the dropdown. But we can see the distinction via observing the border radius of the dropdown. 
 
 
IMO, it's a very edge case.

**Comment by adelekennedy** [comment] 2022-05-17 20:14
Since this is a very edge case is it worth keeping the issue open to solve? @parasharrajat @neil-marcellini?

**Comment by neil-marcellini** [comment] 2022-05-17 20:49
I think it would be good to keep open, but it should be low priority and we shouldn't raise the price too much.

**Comment by adelekennedy** [comment] 2022-05-18 16:57
@neil-marcellini the process we have in place now is to double the issue every 7 days a contributor isn't assigned - we're around the doubling point now actually

**Comment by neil-marcellini** [comment] 2022-05-18 17:05
I think it would be fine to double this time. Let's make sure it doesn't become overly expensive in the future if it takes a long time until there is a good proposal.

**Comment by neil-marcellini** [comment] 2022-05-24 23:08
Still waiting for new proposals.

**Comment by imran-ranglerz** [comment] 2022-05-28 18:48
i will handle it by hight responsive or fixed hight

**Comment by neil-marcellini** [comment] 2022-06-10 21:52
This error only occurs on Android / Chrome. I was not able to reproduce it on iOS / Safari and neither was @srikarparsi. I might take a shot at fixing this later if we still don't have proposals.

Android / Chrome
https://user-images.githubusercontent.com/26260477/173155604-3cd9750e-84d7-408c-a53e-506532b6ca39.mov

**Comment by ntdiary** [comment] 2022-06-24 07:20
# Proposal
## cause
The opening and closing of the soft keyboard will change the height of html(only in android), which will lead to dropdown backdrop repositioning. input blur event and dropdown opened event are happening together. 

here is origin code video and image:

https://user-images.githubusercontent.com/8579651/175474103-a44e0c00-ac51-44f1-b72c-94c1a9751e1d.mp4

for debugging, change background from white to blue
<img width="500" alt="0" src="https://user-images.githubusercontent.com/8579651/175482977-4e8ec583-460f-4ac1-99d1-ceb75d26802a.png">
<img width="500" alt="1" src="https://user-images.githubusercontent.com/8579651/175482993-12345420-5149-446d-abb8-a34a1333c4ee.png">


this is just a simple html demo, also has this problem:
https://gist.github.com/ntdiary/97325b03da5ae71708502e849645e359

https://user-images.githubusercontent.com/8579651/175466499-8d5443d9-fd2a-45a8-9acd-d472a7910f70.mp4

## solution
1. for the event happening together problem, could we add setTimeout function here?
https://github.com/Expensify/App/blob/2595343f78d6d9866684b96f8ba96862b9d2165f/src/components/ButtonWithMenu.js#L65
1. for the backdrop repositioning problem, could we use 100% height instead of this.props.windowHeight? Or add a props to allow customize height.(if not, height is controlled by WithWindowDimensions.js and has debounce function)
https://github.com/Expensify/App/blob/2595343f78d6d9866684b96f8ba96862b9d2165f/src/components/Modal/BaseModal.js#L107

the result video:

https://user-images.githubusercontent.com/8579651/175474596-9c011b3f-c4ee-496e-8562-519fa50b48f4.mp4

**Comment by parasharrajat** [comment] 2022-06-24 15:56
> for the event happening together problem, could we add setTimeout function here?

Why do we need this? 

> for the backdrop repositioning problem, could we use 100% height instead of this.props.windowHeight? 

You tell us. What would be the effect of doing this? It should not break any platform. Do test your solution on All the platforms. 

Please also mention what is the effect of your proposed changes and how do they resolve the issue?

**Comment by ntdiary** [comment] 2022-06-25 15:03
> Why do we need this?

We need `setTimeout` to let the dropdown open animation run after the software keyboard close animation starts.
Otherwise, the height of the dropdown menu will be very high like this image in the first second of the video.
Of course, if this can not reproduce in your phone, maybe we don't need `setTimeout`.
<img width="200" alt="1" src="https://user-images.githubusercontent.com/8579651/175765118-0d33e119-57ab-469b-9b82-1ee237ec30c4.png">

> You tell us. What would be the effect of doing this?

I was hoping the height of dropdown menu can be recalculated in real time in that way.
Because this Issue root cause is this line, the height change was delayed by 100ms (in the second second of the video):
https://github.com/Expensify/App/blob/406040d1b208277e44580bb372323e934b112f37/src/components/withWindowDimensions.js#L35-L42
<img width="200" alt="2" src="https://user-images.githubusercontent.com/8579651/175766122-2e4a07a6-fccc-4a71-a660-57cb405f549c.png">

But I made a mistake.The parameter type of ReactNativeModal.deviceHeight is only number. and so
Either wait this issue https://github.com/Expensify/App/issues/2727 can be fixed and then above line may be updated to 
`this.onDimensionChange = this.onDimensionChange.bind(this);`,
or we need to calculate windowHeight in `BaseModal.js` like `withWindowDimensions.js` except debounce function.

commit: https://github.com/ntdiary/App/commit/dfe04bd56480ae893885960aa398db8ecd5f7614

# Result
### Mobile Web
android

https://user-images.githubusercontent.com/8579651/175779092-df0a10a4-855c-462f-ae02-2d1f4ab6fa84.mp4

ios safari

https://user-images.githubusercontent.com/8579651/175779112-4fc799be-7c8e-43d9-b410-91139970c90c.mp4

### IOS App
https://user-images.githubusercontent.com/8579651/175779194-a5adbcac-e3eb-4706-8150-7452161d44ba.mp4

### Android App
https://user-images.githubusercontent.com/8579651/175779256-50e3b177-220f-4ae5-a86a-680c51518f89.mp4

### Web
https://user-images.githubusercontent.com/8579651/175779291-f5ac7196-4bc7-4451-93e5-9d17f596d96f.mp4

### Desktop
https://user-images.githubusercontent.com/8579651/175779300-2d55b892-f709-4f5a-9e95-6eb90ed5c29c.mp4

**Comment by neil-marcellini** [comment] 2022-06-27 12:50
@ntdiary I'm still not sure if we need to or want to add a delay to the dropdown open animation. I don't like the result on Android / Chrome where the button takes a moment to drop down.

I tried setting the device height to 100% as you mentioned earlier and that yielded a good result. Maybe all we need to do is set that prop to 100% exclusively for Android / Chrome?


https://user-images.githubusercontent.com/26260477/175945676-cb5ae891-82f3-41ea-bcb1-5e42c6f8b22e.mov

**Comment by ntdiary** [comment] 2022-06-28 03:08
@parasharrajat 
I used this solution in my videos.(I can remove `setTimeout`)
https://github.com/ntdiary/App/commit/dfe04bd56480ae893885960aa398db8ecd5f7614
just calculated `deviceHeight` in the `BaseModal.js` like `WithWindowDimensions.js`(remove debounce)

If we cannot calculate height in real time because of performance, I'm afraid I haven't thought another solution yet.

**Comment by parasharrajat** [comment] 2022-06-28 19:19
Thanks for the clarification. As you are aware, we can't remove the denouncing from `WithWindowDimensions` hook due to some bug (until resolved). We can try to decouple the Modals from `WithWindowDimensions` but that is very likely to be accepted by the team. Creating two different sources of truth for dimensions will be confusing overall. But I will open a new discussion on the slack to hear others' thoughts. It could take some time before I do that due to other stuff. 

I suggest that you open a new discussion on `expensify-open-source` slack channel explaining the root cause of the issue and your solutions in a detailed manner. Share that link here. I will follow up.

Meanwhile, you can try to find other solutions.

State: **Open for proposals**

**Comment by neil-marcellini** [comment] 2022-06-30 14:53
# Proposal
Override the modal's `deviceHeight` prop for the `SettlementButton` only. If `deviceHeight` is set to something very large like `10000` then it works well because it always fills the whole screen when it is shown. See the diff below. A more simple option would be to always override the deviceHeight for the BaseModal, but that might break any modal we use.

```diff
diff --git a/src/components/ButtonWithMenu.js b/src/components/ButtonWithMenu.js
index e9fafa750..12b081a55 100644
--- a/src/components/ButtonWithMenu.js
+++ b/src/components/ButtonWithMenu.js
@@ -30,12 +30,16 @@ const propTypes = {
         iconHeight: PropTypes.number,
         iconDescription: PropTypes.string,
     })).isRequired,
+
+    /** Override the device height on the popover modal for a smooth animation when the keyboard collapses */
+    overrideDeviceHeight: PropTypes.bool,
 };
 
 const defaultProps = {
     isLoading: false,
     isDisabled: false,
     menuHeaderText: '',
+    overrideDeviceHeight: false,
 };
 
 class ButtonWithMenu extends PureComponent {
@@ -89,6 +93,7 @@ class ButtonWithMenu extends PureComponent {
                                 this.setState({selectedItem: item});
                             },
                         }))}
+                        overrideDeviceHeight={this.props.overrideDeviceHeight}
                     />
                 )}
             </View>
diff --git a/src/components/IOUConfirmationList.js b/src/components/IOUConfirmationList.js
index 96b26834f..4355a721e 100755
--- a/src/components/IOUConfirmationList.js
+++ b/src/components/IOUConfirmationList.js
@@ -375,6 +375,7 @@ class IOUConfirmationList extends Component {
                             addBankAccountRoute={ROUTES.IOU_SEND_ADD_BANK_ACCOUNT}
                             addDebitCardRoute={ROUTES.IOU_SEND_ADD_DEBIT_CARD}
                             currency={this.props.iou.selectedCurrencyCode}
+                            overrideDeviceHeight
                         />
                     ) : (
                         <ButtonWithMenu
@@ -382,6 +383,7 @@ class IOUConfirmationList extends Component {
                             isLoading={isLoading}
                             onPress={(_event, value) => this.confirm(value)}
                             options={this.splitOrRequestOptions}
+                            overrideDeviceHeight
                         />
                     )}
             />
diff --git a/src/components/Modal/BaseModal.js b/src/components/Modal/BaseModal.js
index 14662bc37..266344c32 100644
--- a/src/components/Modal/BaseModal.js
+++ b/src/components/Modal/BaseModal.js
@@ -104,7 +104,7 @@ class BaseModal extends PureComponent {
                 hasBackdrop={this.props.fullscreen}
                 coverScreen={this.props.fullscreen}
                 style={modalStyle}
-                deviceHeight={this.props.windowHeight}
+                deviceHeight={this.props.overrideDeviceHeight ? 10000 : this.props.windowHeight}
                 deviceWidth={this.props.windowWidth}
                 animationIn={this.props.animationIn || animationIn}
                 animationOut={this.props.animationOut || animationOut}
diff --git a/src/components/Modal/modalPropTypes.js b/src/components/Modal/modalPropTypes.js
index 8f09588e3..07e7da2d7 100644
--- a/src/components/Modal/modalPropTypes.js
+++ b/src/components/Modal/modalPropTypes.js
@@ -61,6 +61,9 @@ const propTypes = {
     /** Whether the modal should go under the system statusbar */
     statusBarTranslucent: PropTypes.bool,
 
+    /** Override the device height on the popover modal for a smooth animation when the keyboard collapses */
+    overrideDeviceHeight: PropTypes.bool,
+
     ...windowDimensionsPropTypes,
 };
 
@@ -77,6 +80,7 @@ const defaultProps = {
     popoverAnchorPosition: {},
     containerStyle: {},
     statusBarTranslucent: true,
+    overrideDeviceHeight: false,
 };
 
 export {propTypes, defaultProps};
diff --git a/src/components/PopoverMenu/BasePopoverMenu.js b/src/components/PopoverMenu/BasePopoverMenu.js
index 32551ba20..1eda531a1 100644
--- a/src/components/PopoverMenu/BasePopoverMenu.js
+++ b/src/components/PopoverMenu/BasePopoverMenu.js
@@ -16,6 +16,9 @@ const propTypes = {
     /** Callback fired when the menu is completely closed */
     onMenuHide: PropTypes.func,
 
+    /** Override the device height on the popover modal for a smooth animation when the keyboard collapses */
+    overrideDeviceHeight: PropTypes.bool,
+
     ...createMenuPropTypes,
     ...windowDimensionsPropTypes,
 };
@@ -23,6 +26,7 @@ const propTypes = {
 const defaultProps = {
     ...defaultCreateMenuPropTypes,
     onMenuHide: () => {},
+    overrideDeviceHeight: false,
 };
 
 class BasePopoverMenu extends PureComponent {
@@ -37,6 +41,7 @@ class BasePopoverMenu extends PureComponent {
                 animationOut={this.props.animationOut}
                 disableAnimation={this.props.disableAnimation}
                 fromSidebarMediumScreen={this.props.fromSidebarMediumScreen}
+                overrideDeviceHeight={this.props.overrideDeviceHeight}
             >
                 <View style={this.props.isSmallScreenWidth ? {} : styles.createMenuContainer}>
                     {!_.isEmpty(this.props.headerText) && (
diff --git a/src/components/SettlementButton.js b/src/components/SettlementButton.js
index 2997d2cad..626a040d7 100644
--- a/src/components/SettlementButton.js
+++ b/src/components/SettlementButton.js
@@ -27,6 +27,9 @@ const propTypes = {
     /** Associated phone login for the person we are sending money to */
     recipientPhoneNumber: PropTypes.string,
 
+    /** Override the device height on the popover modal for a smooth animation when the keyboard collapses */
+    overrideDeviceHeight: PropTypes.bool,
+
     ...withLocalizePropTypes,
 };
 
@@ -34,6 +37,7 @@ const defaultProps = {
     currency: CONST.CURRENCY.USD,
     recipientPhoneNumber: '',
     shouldShowPaypal: false,
+    overrideDeviceHeight: false,
 };
 
 class SettlementButton extends React.Component {
@@ -142,6 +146,7 @@ class SettlementButton extends React.Component {
                             this.props.onPress(iouPaymentType);
                         }}
                         options={this.state.buttonOptions}
+                        overrideDeviceHeight={this.props.overrideDeviceHeight}
                     />
                 )}
             </KYCWall>

```

Result:

https://user-images.githubusercontent.com/26260477/176708757-58f2f5eb-931d-4a19-be94-e750978fec00.mov

**Comment by parasharrajat** [comment] 2022-06-30 15:38
That seems like it will work because we can expect that a device with a 1000px viewport height is unrealistic. Checking for unintended side-effects.

**Comment by parasharrajat** [comment] 2022-06-30 16:15
Ok, a quick checkup and code review on `react-native-modal` tells me that it is safe to use arbitrary long values for `deviceHeight`. 
1. It is only used on the backdrop to calculate styles.
2. It is also used for swipe gestures which do not have any effect on our app as we have disabled all the swipe gestures for these menus. 

**But this is a hack, not a solution**. **Let's wait** for the `withWindowDimensions` fixes to be merged into our and then we can revisit this issue if it is still reproducible. Thankfully that is not far.

**Comment by neil-marcellini** [comment] 2022-07-01 08:18
Ok sounds good. I'll add [HOLD] to the title. Where can I follow along to tell when it's merged into our App?

**Comment by adelekennedy** [comment] 2022-07-04 15:55
on hold

**Comment by adelekennedy** [comment] 2022-07-06 18:59
On Hold

**Comment by adelekennedy** [comment] 2022-07-14 22:26
on hold

**Comment by neil-marcellini** [comment] 2022-08-16 00:46
@parasharrajat what's the status on the withWindowDimensions bug?

**Comment by adelekennedy** [comment] 2022-09-07 11:16
Still holding here!

**Comment by adelekennedy** [comment] 2022-10-10 16:16
Still on hold - @parasharrajat @neil-marcellini any updates I should make here?

**Comment by neil-marcellini** [comment] 2022-10-10 16:28
The withWindowDimensions work around has been removed here https://github.com/Expensify/App/pull/9143, so as I understand it this should be fixed now? I'll see if I can reproduce it.

**Comment by neil-marcellini** [comment] 2022-10-10 16:40
The PR I linked above hasn't been deployed to staging or prod yet, but from local testing it looks like it will fix this issue. It looks like there's another bug where the pay button isn't visible above the keyboard and when I scroll down I can scroll too far. I will report that issue unless I find an existing issue.

https://user-images.githubusercontent.com/26260477/194914536-aa182e74-6c8a-4162-9fe0-3f6203337e7d.mp4

**Comment by neil-marcellini** [comment] 2022-10-11 17:13
I'm making this weekly so I remember to test again and close the issue once the fix hits prod.

**Comment by neil-marcellini** [comment] 2022-10-28 16:06
This issue is fixed!

https://user-images.githubusercontent.com/26260477/198682262-0c81ff4a-6fe2-4400-a40d-ffb06e6109c3.MP4

Here is the issue I created for the other bug https://github.com/Expensify/App/issues/11722

**Closed by neil-marcellini** 2022-10-28 16:06 UTC
Labels: External, Engineering, Weekly, Help Wanted, Overdue, Bug

**Comment by thesahindia** [comment] 2022-11-03 15:57
I believe it's eligible for the reporting compensation.

cc: @adelekennedy @neil-marcellini

**Comment by thesahindia** [comment] 2022-11-08 06:33
bump @adelekennedy

**Comment by thesahindia** [comment] 2022-11-10 20:20
Bump @adelekennedy ^

**Comment by adelekennedy** [comment] 2022-11-10 20:40
@thesahindia whoops! Hired you fro the reporting bonus

**Comment by thesahindia** [comment] 2022-11-10 20:44
Thanks, accepted!

**Comment by thesahindia** [comment] 2022-11-15 17:53
Bump @adelekennedy
