### ISSUE TITLE
Chat - Family emojis are rendered as black and white emojis

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36679] opened 2024-02-16 12:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to any chat.
3. Open emoji picker.
4. Search for "Family".

## Expected Result:
Family emojis are rendered properly.

## Actual Result:
Family emojis are rendered as black and white emojis.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6381608_1708070280348!bandicam_2024-02-16_15-53-41-292](https://github.com/Expensify/App/assets/115492554/ba5cf1f8-cea5-4098-b239-6be1f5d2ab8f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-02-16 12:11
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

We think that this bug might be related to @quinthar

**Comment by dragnoir** [comment] 2024-02-16 13:35
This is not a bug.

We are now using new Emoji font for windows. We replaced Segoe UI Emoji by Nato Color Emoji. Bacause Segoe UI Emoji does not support flagsd and we need to display flags.

- Old font:
https://emojipedia.org/microsoft

![image](https://github.com/Expensify/App/assets/12425932/c28729ed-de5d-428e-9fe3-1efd4512eedd)

- New font:
https://fonts.google.com/noto/specimen/Noto+Color+Emoji/glyphs

![image](https://github.com/Expensify/App/assets/12425932/32708ea3-d853-4f00-9232-4fc403e0a800)

**Comment by jliexpensify** [comment] 2024-02-18 20:32
Thank you for weighing in @dragnoir! Closing.

**Closed by jliexpensify** 2024-02-18 20:32 UTC
Labels: Daily, Bug
