### ISSUE TITLE
[C+ Checklist Needs Completion] [$1000]  The State filled is not cleared after selecting another country

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23839] opened 2023-07-28 22:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go profile > Personal detail > Home Address Page
2. Click on State and choose any state
3. Now click on Country and select a country other than the United States.
Notice that the state filled shows an abbreviation of the previously selected State
## Expected Result:
 The State filled is cleared
## Actual Result: 
The State filled is not cleared. Shows abbreviation of previously selected State

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/906770f5-3db7-4e39-a605-fbc6666947ca

https://github.com/Expensify/App/assets/43996225/a8396236-3a43-400e-93ad-056da67d3fd3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690482380069389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0fbcbd5a20b5cfa</li>
        <li>Upwork Job ID: 1686035992494268416</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>daveSeife | Reporter | 25899761</li>
<li>dukenv0307 | Contributor | 25996636</li>
</ul></li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-07-29 00:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Currently we are selecting `State` first (when default `Country` is US) and then selecting other `Country` lets say India, then `State` is not getting empty.

### What is the root cause of that problem?
- We are not resetting the `state` input in form when we are changing the `country` input.
- Also even if we update the state component from Picker to TextInput the form's value won't get updated.
- Hence showing the previous selected state.

### What changes do you think we should make in order to solve the problem?
- We can implement a custom function-prop which acts like a callback with paramete as the below object and it changes values when `inputValues` or `inputRefs` changes in `Form` component:
```
{  resetField: (inputID) => {... reset the input field} }
```
- We can use this ref in `handleAddressChange` function of `AddressPage` component to reset the `State` input field.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by greg-schroeder** [comment] 2023-07-31 15:27
Reproduced. Agreed that the state field should just be cleared

**Comment by Santhosh-Sellavel** [comment] 2023-07-31 17:35
Left a comment [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1690824771304289) for volunteers to take over

**Comment by saalimzafar** [comment] 2023-08-01 23:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The problem we are trying to solve in this issue is that the "state" field is not clearing after selecting another country in the `AddressPage` component.

### What is the root cause of that problem?

The root cause of the problem lies in the `handleAddressChange` function within the `AddressPage` component. When the country is changed, the function updates the `currentCountry` state but does not reset the "state" field in the `privatePersonalDetails.address` object, leading to the "state" field retaining its previous value when a new country is selected.

### What changes do you think we should make in order to solve the problem?

To solve the problem, we need to modify the `handleAddressChange` function to reset the "state" field when a new country is selected. We'll also add the required state management hooks and define the `setPrivatePersonalDetails` function to manage the `privatePersonalDetails` state.

Here's the updated `AddressPage` component with the necessary modifications:

```jsx
import React, {useState} from 'react';
import lodashGet from 'lodash/get';
import {CONST} from 'expensify-common/lib/CONST';
import * as PersonalDetails from '../../../../libs/actions/PersonalDetails';
import styles from '../../../../styles/styles';
// (Add other necessary imports)

function AddressPage() {
    const [privatePersonalDetails, setPrivatePersonalDetails] = useState({
        address: {
            street: '',
            city: '',
            state: '',
            zip: '',
            country: '',
        },
    });

    const [currentCountry, setCurrentCountry] = useState(
        PersonalDetails.getCountryISO(
            lodashGet(privatePersonalDetails, 'address.country')
        ) || CONST.COUNTRY.US
    );

    // Rest of the component code...

    const handleAddressChange = (value, key) => {
        if (key === 'country') {
            setCurrentCountry(value);
            // Reset the "state" field to an empty string when a new country is selected
            setPrivatePersonalDetails({
                ...privatePersonalDetails,
                address: {...privatePersonalDetails.address, state: ''}
            });
        }
    };

    // Rest of the component code...
}
```

By adding the `useState` hook for `privatePersonalDetails` and `currentCountry`, we can manage the state and correctly update the "state" field when a new country is selected. This ensures that the "state" field is cleared whenever a different country is chosen.

### What alternative solutions did you explore? (Optional)

NA

**Comment by ares-dev05** [comment] 2023-08-02 07:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue at hand is that the "state" field fails to clear after selecting a different country on the Home Address page within the Personal Details section of the profile.
### What is the root cause of that problem?
In the AddressPage.js file, there is a code snippet that handles the UI/UX behavior based on the selected country. If the country is not the United States (US), the StatePicker component is replaced with a TextInput box. However, during this transition, the TextInput box displays the previous state value for the US. This happens because both the StatePicker and TextInput components use the same 'state' value.

To address this issue, we can create a separate 'state' hook variable specifically for the TextInput box when a non-US country is selected. We can then set this 'state' variable to the TextInput box. Consequently, when the user selects a country other than the US, we can reset the TextInput box for the non-US country. Subsequently, if the user selects the US again, the previous 'state' value will be restored.
### What changes do you think we should make in order to solve the problem?
To address this issue, we can implement a new 'state' hook variable by using the following code:

`const [currentState, setCurrentState] = useState('');`

To ensure the default value is set to an empty string, we need to initialize the 'currentState' variable accordingly.

In the `handleAddressChange` function, we should reset the `currentState` variable whenever a country is selected.

Finally, we need to establish a connection between the `currentState` variable and the `state` TextInput box for non-US countries.

```
import lodashGet from 'lodash/get';
import _ from 'underscore';
import React, {useState, useCallback} from 'react';
...

function AddressPage({privatePersonalDetails}) {
    usePrivatePersonalDetails();
    const {translate} = useLocalize();
    const [currentCountry, setCurrentCountry] = useState(PersonalDetails.getCountryISO(lodashGet(privatePersonalDetails, 'address.country')) || CONST.COUNTRY.US);
    const [currentState, setCurrentState] = useState('');

...

 const handleAddressChange = (value, key) => {
        if (key !== 'country') {
            return;
        }
        setCurrentCountry(value);
        setCurrentState('')
    };

...
return (
        <ScreenWrapper includeSafeAreaPaddingBottom={false}>
...
{isUSAForm ? (
                    <View style={styles.mhn5}>
                        <StatePicker
                            inputID="state"
                            defaultValue={address.state}
                        />
                    </View>
                ) : (
                    <TextInput
                        inputID="state"
                        label={translate('common.stateOrProvince')}
                        accessibilityLabel={translate('common.stateOrProvince')}
                        accessibilityRole={CONST.ACCESSIBILITY_ROLE.TEXT}
                        defaultValue={currentState || ''}
                        maxLength={CONST.FORM_CHARACTER_LIMIT}
                    />
                )}
...
  </ScreenWrapper>
    );
}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ares-dev05** [comment] 2023-08-02 07:20
Contributor details
Your Expensify account email: godknight122@gmail.com
Upwork Profile Link: https://www.upwork.com/en-gb/freelancers/~01afd03c01b66a1606

**Comment by ares-dev05** [comment] 2023-08-02 08:17
Contributor details
Your Expensify account email: godknight122@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01afd03c01b66a1606

**Comment by greg-schroeder** [comment] 2023-08-02 09:30
@allroundexperts assigned, thanks for your patience. Proposal review is g2g 👍

**Comment by jeet-dhandha** [comment] 2023-08-02 20:00
Updated Proposal for better code.

**Comment by saalimzafar** [comment] 2023-08-03 08:33
It's okay you can consider dukenv0307's proposal, but can you do me a favor?
I want to join the slack channel as I have to report a bug but I'm not getting response from the constributors. 
@allroundexperts

**Comment by roryabraham** [comment] 2023-08-07 20:40
Thanks, LGTM 👍🏼 

That said, I wonder if we should think about generalizing the address form a little bit. It looks like there's a lot of overlap between `src/pages/settings/Profile/PersonalDetails/AddressPage` and `src/pages/ReimbursementAccount/AddressForm`. Seems like they should be using a shared component.

**Comment by greg-schroeder** [comment] 2023-08-17 08:35
Issue Participants:

Issue reported by: @daveSeife
Contributor: @dukenv0307
C+: @allroundexperts 

Was this issue merged in time to be eligible for the speed bonus? [Yes](https://github.com/Expensify/App/issues/23839#issuecomment-1670448708)
Were their any regressions? ❌ 

Payment summary:

Reporter: $250
Contributor: $1,500 ($500 bonus)
C+: $1,500 ($500 bonus)

**Comment by greg-schroeder** [comment] 2023-08-17 08:35
Please request payment via NewDot @allroundexperts - all that's left here is taking care of the checklist!

**Comment by greg-schroeder** [comment] 2023-08-24 02:55
Filing regression test and closing!

**Closed by greg-schroeder** 2023-08-24 02:55 UTC
Labels: External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2023-08-24 05:12
Reviewed the details for @allroundexperts. $1,500 approved for payment in NewDot based on BZ summary above.
