### ISSUE TITLE
[HOLD] [$250] Connect Bank Account - App is crashed when adding a Verified Bank Account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12308] opened 2022-10-31 18:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Enable staging Web secure server in Account Preferences if disabled
4. Navigate to the add bank account modal (Workspace settings > Add bank account)
5. Verify the Add bank account modal is displayed with 2 options to add bank accounts (Log in and Manual)
6. Select the Connect with plaid method to add a bank account
7. On the bank account list select "Fidelity"
8. Enter the credentials "user_good / pass_good"
9. Select "Plaid Saving" account
10. Click Save and Continue
11. In the company information verify all fields are working as expected
12. Fill out the fields with the required test credentials
13. Verify you're able to continue to the personal information step.
14. In the Personal information verify all fields are working as expected
15. Fill out the fields with the required test credentials
16. Verify you're able to continue.
17. In the beneficial owners step toggle the last 2 checkboxes (terms and conditions and true information)
18. Confirm you're able to continue and reach the validate step.
19. Verify the bank account was added to the workspace

## Expected Result:
App is not crashed when adding Verified Bank Account

## Actual Result:
App is crashed when adding a Verified Bank Account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- mWeb/Safari
mWeb//Chrome

**Version Number:** 1.2.21.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/199078578-f5b865e3-1a3b-4db7-9c91-47d9fefea8ba.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team
 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2022-11-01 10:15
This was [unreproducible yesterday](https://expensify.slack.com/archives/C03TQ48KC/p1667237200981549?thread_ts=1667236200.518079&cid=C03TQ48KC), so there are possibly other required account configurations that cause this issue. 

Until we can reliably reproduce this I don't thin it should be made external yet.

**Comment by zanyrenney** [comment] 2022-11-01 12:19
Thanks @Julesssss

**Comment by Julesssss** [comment] 2022-11-01 12:22
@Expensify/applauseleads would you mind sending testing again and on other platforms so we can get an idea of how often this occurs? Thanks in advance

**Comment by kbecciv** [comment] 2022-11-01 17:00
@Julesssss Issue is reproduced on Web, mWeb/safari and mWeb/Chrome.
We are blocked to test on IOS and Android app due to KI

https://user-images.githubusercontent.com/93399543/199292290-366c3149-33a3-44b4-89dd-39176887f1c7.mp4


https://user-images.githubusercontent.com/93399543/199292298-51cd168d-ea3b-42bd-9e2d-5242a3714cdb.mp4


https://user-images.githubusercontent.com/93399543/199292310-1100dee0-ee39-4c57-a99e-f57933fc471f.mp4

**Comment by Julesssss** [comment] 2022-11-02 09:59
Hi, thanks for that. 

> We are blocked to test on IOS and Android app due to KI

What do you mean by KI? Sorry, but I don't remember what that stands for 😅

**Comment by Julesssss** [comment] 2022-11-02 10:07
@zanyrenney I'm on the fence about making this a deploy blocker. I'm blocked at test step 14 currently, are you able to reproduce? If you're also stuck I'll ask for help testing in Slack

**Comment by Julesssss** [comment] 2022-11-02 11:07
I asked for someone to help confirm this issue in Slack [here](https://expensify.slack.com/archives/C03SC9E09/p1667386623312289), but I have managed to reproduce the issue in web: 

<img width="1060" alt="Screenshot 2022-11-02 at 11 06 17" src="https://user-images.githubusercontent.com/10736861/199474492-a91a2ca2-0b72-4f86-b4a0-cdd8dcb29724.png">

**Comment by Julesssss** [comment] 2022-11-02 11:37
Marking internal as it seems to depend on the environment. I cannot reproduce in dev 😕 

Here's the [Logs ](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22763c8dc1ca61405e-LHR%22)+AND+timestamp:[2022-11-02T10:33:10.143Z+TO+2022-11-02T12:33:10.143Z]&index=logs_expensify-019315)for my attempt:

<img width="1713" alt="Screenshot 2022-11-02 at 11 36 42" src="https://user-images.githubusercontent.com/10736861/199480237-ab4313d6-cc21-4bb6-b6b7-43b915d4f153.png">

**Comment by Julesssss** [comment] 2022-11-02 11:53
Okay, so the bank account data is definitely being added to Onyx, but for some reason it's no contained when the check is made 😕  As the workaround is to simply refresh the page and it's already on prod, I'm not going to make this a major blocker. But it is still important. 

https://user-images.githubusercontent.com/10736861/199483290-55198dca-4f3b-489d-8fdb-a6696031c685.mov

**Comment by kbecciv** [comment] 2022-11-02 14:16
@Julesssss This is open KI https://github.com/Expensify/App/issues/11796 for IOS and Android app

**Comment by Julesssss** [comment] 2022-11-02 14:38
Opening this up for external contributors. My best guess right now is that the Component is not updated after the bank account data is persisted to Onyx.

**Comment by zanyrenney** [comment] 2022-11-07 10:00
No propsals yet.

**Comment by mvtglobally** [comment] 2022-11-09 03:43
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2022-11-10 04:53
Can someone on this issue re-test and see if they get the same result as Applause?

**Comment by Julesssss** [comment] 2022-11-10 11:18
I can't get to this today, will do at the next overdue ping

**Comment by JmillsExpensify** [comment] 2022-11-10 22:51
I just tried testing but I got an error trying to get past Onfido. 
![IMG_1818263A2EC5-1](https://user-images.githubusercontent.com/1127863/201222658-3880a049-1818-4774-96da-f9a0a174a42a.jpeg)

**Comment by Julesssss** [comment] 2022-11-14 10:30
Hey @mvtglobally would you mind retesting again, as we couldn't reproduce this last time and we are having trouble verifying ourselves.

**Comment by JmillsExpensify** [comment] 2022-11-14 19:22
Yes, thanks @mvtglobally! Let us know how testing goes.

**Comment by mvtglobally** [comment] 2022-11-16 02:23
Issue not reproducible during KI retests. (Second week)

**Comment by Julesssss** [comment] 2022-11-17 09:57
Holding this while the retesting is completed, it's possible this is no longer occuring 🤞

**Comment by zanyrenney** [comment] 2022-11-17 09:57
Could have been a tempoprary issue, but as we we close after 4 restests, We'll keep the issue open 2 more weeks for these retests.

**Comment by zanyrenney** [comment] 2022-11-21 15:38
Keeping open until retesting is complete.

**Comment by mvtglobally** [comment] 2022-11-22 21:16
Issue not reproducible during KI retests. (Third week) Can we close this ?

**Closed** 2022-11-23 10:47 UTC
Labels: External, Engineering, Daily, Needs Reproduction, Help Wanted, Bug
