### ISSUE TITLE
[$0] Report fields - No checkbox next to list value on web layout

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48724] opened 2024-09-06 15:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-10
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields
3. Click Add field
4. Select List from Type field
5. Click List values
6. Click Add value
7. Add some list values

## Expected Result:
There will be checkbox next to each list value (production behavior)

## Actual Result:
There is no checkbox next to each list value
The checkbox only appears when long clicking on the list value, which brings up the stretched pop-up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/698e4789-94e8-4b7f-b983-744942d04152

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832081817508149579</li>
        <li>Upwork Job ID: 1832081817508149579</li>
        <li>Last Price Increase: 2024-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 103848370</li>
<li>rayane-djouah | Contributor | 103848373</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by haris-aqeel** [comment] 2024-09-06 18:53
Hi, Is this task already completed? I recently saw a job post regarding this task on upwork but from here, it seems the matter is already resolved.

Here, is the job post link: https://www.upwork.com/jobs/~021832081817508149579

**Comment by Beamanator** [comment] 2024-09-06 18:55
Hi @haris-aqeel - yes sorry this job is already assigned out and being worked on in https://github.com/Expensify/App/pull/48723

Most available jobs in our Github repository will have the `Help Wanted` label assigned right now

**Comment by haris-aqeel** [comment] 2024-09-06 19:01
Contributor details
Your Expensify account email: harisaqeel.2001@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/harisaqeel34

**Comment by Beamanator** [comment] 2024-09-09 14:48
closing since fix was CP'd and was fixed as regression so no payment needed

**Closed by Beamanator** 2024-09-09 14:48 UTC
Labels: Reviewing, External, Engineering, Daily

**Comment by haris-aqeel** [comment] 2024-12-02 20:11
Can you invite me to slack?
