### ISSUE TITLE
[$500] IOU - Chat reloads when clicking Message <user> after returning from IOU thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39289] opened 2024-03-29 19:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Request money from any user
3. In 1:1 DM, click on the IOU preview
4. Click on the header subtitle to return to 1:1 DM
5. In 1:1 DM, click on the chat header
6. Click Message <user>

## Expected Result:
Chat will not reload when clicking Message <user> since it will lead to the same page

## Actual Result:
Chat reloads when clicking Message <user> after returning from thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/64160f60-0900-4cef-b5a5-5382b08d4601

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01350a160bfffaa30f</li>
        <li>Upwork Job ID: 1774830354063110144</li>
        <li>Last Price Increase: 2024-04-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-29 19:47
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-03-29 19:48
@luacmartins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment] 2024-04-01 16:04
I'll demote this to NAB, but it's something we need to fix. Making it external.

**Comment by abzokhattab** [comment] 2024-04-01 20:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
app reloads when clicking on message <user> while the user report being open in the background

### What is the root cause of that problem?
 
on clicking on `Message <user>` we navigate and open the report of that user without checking whether we are on the report page or not



### What changes do you think we should make in order to solve the problem?
here we should pass the current `reportID` to the `ReportActions.navigateToAndOpenReportWithAccountIDs`


https://github.com/Expensify/App/blob/78efe2f1887f0b211fbbb22d23e2b22c09e68621/src/pages/ProfilePage.tsx#L221


and then check if the reportID is the same or not before opening  the report in this line https://github.com/Expensify/App/blob/be315d6cf336a448e330ccc752e395ccf2695629/src/libs/actions/Report.ts#L852

**Comment by hungvu193** [comment] 2024-04-02 02:48
@abzokhattab Can you reproduce on latest main now?

https://github.com/Expensify/App/assets/16502320/c53176f9-6cf0-44f8-9df1-6808a34b7bb1

**Comment by abzokhattab** [comment] 2024-04-02 03:00
yes still reproducible


https://github.com/Expensify/App/assets/59809993/0794759b-7002-4691-88eb-35640a7f0f70

**Comment by hungvu193** [comment] 2024-04-02 03:05
> yes still reproducible
> 
> it doesnt reload but it keeps sending `OpenReport` request to the backend
> 
>  Screen.Recording.2024-04-02.at.4.56.03.AM.mov

Can you declare your test steps? It seems working fine on my end :/

**Comment by abzokhattab** [comment] 2024-04-02 03:21
Yes, it doesn't reload as shown in the video but it sends a redundant backend request `openReport` as observed in the network tap. 


To reproduce the previous behavior:
1. open a chat with any user.
2. send a message in case you don't have any previous chat with this user.
3. click on the report header
4. Then click on "Message XXXX"


This raises the question: Do we actually need to display the "Message XXX" item if the report is already opened in the background? I believe it's redundant in this case because it's already open.

**Comment by hungvu193** [comment] 2024-04-02 03:22
I'm observing the same behavior across dev, staging, and prod; it calls `OpenReport` when we click the `Message ...` button. Given that information, I think we can close this issue.

**Closed** 2024-04-02 14:02 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
