### ISSUE TITLE
Web - Chat - Selected part of the text does not transfer the to another place

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9403] opened 2022-06-11 00:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to link https://staging.new.expensify.com
2 Open the chat
3. Enter any text
4. Select part of the text
5 Move it to another place

## Expected Result:
Selected part of the text should transfer the to another place

## Actual Result:
Selected part of the text does not transfer the to another place

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.76.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/173166100-34a5fc8f-93d6-4692-ad1e-46ef2b370d4e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Exploratory 

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment] 2022-06-13 20:37
I noticed that other messaging apps have this functionality, and I think this feature could be a good minor UX improvement when a user is copying and pasting text in the chat box. Applying the `External` label.

**Comment by kevinksullivan** [comment] 2022-06-16 20:06
Hm can I see a video of this happening in other chat apps? I am not able to reproduce in slack and am unfamiliar with this.

**Comment by kevinksullivan** [comment] 2022-06-24 03:48
Closing unless someone can provide more context. Feel free to reopen if you have something!

**Closed by kevinksullivan** 2022-06-24 03:48 UTC
Labels: External, Engineering, Daily, Overdue
