### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] Web – 2FA - The copy icon placed in "copy code" button is clicked, the icon remains in a hovered state.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21673] opened 2023-06-27 11:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the "Settings" section.
2. Click on the "Security" option.
3. Select the "Two-factor authentication" feature.
4. Notice that when the copy icon placed in "copy code" button is clicked, the icon remains in a hovered position until the cursor is placed over it and then moved away.

## Expected Result:
The copy icon should not remain in a hovered position when the "copy code" button is clicked.

## Actual Result:
The copy icon should not remain in a hovered position when the "copy code" button is clicked until the cursor is placed over it and then moved away.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4f0e8cba-2c08-4bb3-ab41-79b29c1f4275

https://github.com/Expensify/App/assets/93399543/80c4d1e7-5574-4c17-b880-30f25c9aea40

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687498320311389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01827743d082c5b93a</li>
        <li>Upwork Job ID: 1674404614868873216</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-06-29 13:08
Was able to recreate this as well, so getting eyes on the proposal 👍

**Comment by CortneyOfstad** [comment] 2023-06-29 13:10
@abdulrahuman5196 Any thoughts on the proposal above?

**Comment by abdulrahuman5196** [comment] 2023-06-29 14:21
@Ollyws  I am not sure if i am understanding the proposal correctly.

>In [PressableWithDelayToggle](https://github.com/Expensify/App/blob/e5f00f86fb412702e9c212b5a88766a8ef7da611/src/components/Pressable/PressableWithDelayToggle.js#L98-L104), the text is rendered outside of the Pressable component which causes it to block the hoverout event when it is long enough.

How is text blocking the hover updates on the different child inside `PressableWithoutFeedback` ?

**Comment by abdulrahuman5196** [comment] 2023-06-30 15:43
>Essentially the pressable component is only wrapping the icon, which means it will only highlight when we hover over the icon specifically 

@Ollyws  I agree on this. it weird that while only hovering the icon it goes to hover state, it should be in hover state even if we go over the text. @CortneyOfstad  Kindly correct me if wrong, if the expectation is to show the hover state when only we go over the icon not the icon text.

But regardless, the current issue is that the hover state itself is not updated correctly leading to the copy icon being in hovered state. Could you mention why do you think both are related? Why does the hover provide wrong results when hovered over the icon(which is the root cause actually).

**Comment by CortneyOfstad** [comment] 2023-06-30 16:40
@abdulrahuman5196 I believe you are correct that the hover state should be when we go over all text 👍

**Comment by CortneyOfstad** [comment] 2023-06-30 19:32
Heading OoO for the week (back July 10) so re-assigning this in the meantime 👍

**Comment by maddylewis** [comment] 2023-07-05 13:28
this was assigned to me while i was out of office - reviewing today.

**Comment by maddylewis** [comment] 2023-07-05 13:30
@abdulrahuman5196 - when you have a chance, let me know what you think of @Ollyws comment here - https://github.com/Expensify/App/issues/21673#issuecomment-1614912366

**Comment by abdulrahuman5196** [comment] 2023-07-06 19:10
I think the comment makes sense.

Anyways the real issue i am thinking of is that `Why isn't the icon highlighted when we hover on its relevant text/button itself?`

So I think the right fix would be make the icon come to hover state when the mouse enters the button itself. AFAIK tested it seems to fix the hover state issue this GH was originally created for.

@Ollyws Could you update your original proposal with more information from comments discussed - https://github.com/Expensify/App/issues/21673#issuecomment-1609372663

**Comment by abdulrahuman5196** [comment] 2023-07-06 19:13
@Ollyws 's proposal here looks good and works well. We will be change the behaviour of hover style of icon to be activated when button itself is hovered.

🎀👀🎀
C+ Reviewed

cc: @maddylewis

**Comment by abdulrahuman5196** [comment] 2023-07-06 19:13
🎀 👀 🎀 C+ reviewed

**Comment by maddylewis** [comment] 2023-07-21 18:19
@abdulrahuman5196 - will you provide an update on this one? are we waiting for the fix to be deployed? https://github.com/Expensify/App/pull/22430#issuecomment-1645730374

once the fix is live, do we need to wait for the 7-day regression period before issuing payment? lmk - thanks!

**Comment by abdulrahuman5196** [comment] 2023-07-21 18:33
@maddylewis 

will you provide an update on this one? are we waiting for the fix to be deployed?

The fix was merged yesterday. And waiting for prod deployment 

once the fix is live, do we need to wait for the 7-day regression period before issuing payment?

Yes

**Comment by usmantariq96** [comment] 2023-07-21 19:09
@maddylewis offer accepted with thanks.

**Comment by maddylewis** [comment] 2023-07-29 14:02
moving to daily since payment date is coming up.

**Comment by abdulrahuman5196** [comment] 2023-08-01 18:37
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is not a regression. The component has been this way with PressableWithDelayToggle.js

>Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This is corner case. So regression test wouldn't be benificial here.

@maddylewis

**Comment by maddylewis** [comment] 2023-08-02 17:42
### Payments
 Outlined here - https://github.com/Expensify/App/issues/21673#issuecomment-1640394003

**Comment by abdulrahuman5196** [comment] 2023-08-02 18:53
@maddylewis Done

**Comment by maddylewis** [comment] 2023-08-04 21:17
thanks!

**Closed by maddylewis** 2023-08-04 21:17 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by maddylewis** [comment] 2023-08-04 21:33
thanks!
