### ISSUE TITLE
Sending text with codefence, followed by newline and a text makes both the lines appear in text preview LHN.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14719] opened 2023-01-31 22:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log in to ND.
2. Open up any chat.
3. Type this text in the composer and send it

```
```hello```
newline
```
4. You'll notice that instead of "hello" in text preview in LHN, "hellonewline" is shown.

## Expected Result:
Only the first line is shown in text preview

## Actual Result:
Both lines are shown in text preview

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/215900191-bc03e351-8e4c-47b4-9e3a-01b3bbbaeccd.mp4

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/215900227-6adf3f70-eb6e-413b-a2ac-2cb02307b9de.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Prince-Mendiratta 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1675186156366439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment] 2023-02-01 10:39
Dupe of https://github.com/Expensify/App/issues/14670, closing

**Closed by garrettmknight** 2023-02-01 10:39 UTC
Labels: Daily, Bug
