### ISSUE TITLE
Chat - Emojis used from 4 suggested are not displayed in frequently used

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21799] opened 2023-06-28 14:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap plus icon
3. Tap new chat
4. Select a user
5. Send a message
6. Long press the message
7. Pick emoticons from 4 listed
8. Long press the message
9. Tap emoticon plus
10. Search and select any emoticon

## Expected Result:
All used emoticons must be displayed in frequently used on opening emoticons plus section

## Actual Result:
Only emoticons used from emoticon plus section is displayed in frequently used but emoticons used from 4 suggested are not displayed in frequently used

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.33-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/15aba9de-ff9f-48b9-b16b-957904372016

![Bug6108153_Screenshot_2023-06-27-19-04-48-570-edit_com android chrome](https://github.com/Expensify/App/assets/78819774/2c2cdf03-5148-4e80-ad01-870da7ab1108)

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment] 2023-06-28 21:29
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
- User is not able to see frequently used emojis in the quick reactions list.

### What is the root cause of that problem?
- Currently there is no such logic to show frequently used emojis in the quick reactions list. Only constant emojis are shown.

### What changes do you think we should make in order to solve the problem?
- We can create a function in `EmojiUtils.js` to get frequently used emojis and show them in the quick reactions list. Also, we can show the constant emojis if there are no frequently used emojis.

```js
function getQuickReactions() {
    const frequent = getFrequentlyUsedEmojis([]).slice(0, 5);
    return frequent.length ? frequent : CONST.QUICK_REACTIONS;
}
```
- Use this in `MiniQuickEmojiReactions.js` and `BaseQuickEmojiReactions.js` instead of `CONST.QUICK_REACTIONS`.
<details>
<summary> Output after changes: </summary>

<img width="370" alt="Screenshot 2023-06-29 at 2 57 20 AM" src="https://github.com/Expensify/App/assets/78416198/50346b16-b664-483a-a882-9e30030a1791">
<img width="679" alt="Screenshot 2023-06-29 at 2 57 40 AM" src="https://github.com/Expensify/App/assets/78416198/9f092563-bd8b-4d37-a3f0-8f4c1c948ae2">


</details>


### What alternative solutions did you explore? (Optional)
- N/A

**Comment by jeet-dhandha** [comment] 2023-06-29 04:55
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
- User is not able to see suggested emojis in the frequently used emojis list, after using them.

### What is the root cause of that problem?
- Its because we are not updating frequently used emojis list when reacting with emoji to the message.

### What changes do you think we should make in order to solve the problem?
- We can add below code in `Report.js` file. This will update frequently used every time the user reacts with an emoji.

```diff
+ import * as User from './User';

...rest code

function addEmojiReaction(reportID, originalReportAction, emoji, skinTone = preferredSkinTone) {
+    const frequentEmojiList = EmojiUtils.getFrequentlyUsedEmojis(emoji);
+    User.updateFrequentlyUsedEmojis(frequentEmojiList);
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by alexpensify** [comment] 2023-06-30 23:33
Reassigning another `Bug` team member: I'm going OOO until Monday, July 10, and will take it back if it's still open by my return date.

Required action from the 🐛  team: I've run out of time and haven't tested this one yet. This needs testing to confirm if it's a bug, check if it's a dupe, and then assign the applicable labels. Thank you!

**Comment by mallenexpensify** [comment] 2023-07-04 18:04
@lanitochka17 are you proposing that we show the below in frequently used, along with other emoji there?
<img width="165" alt="image" src="https://github.com/Expensify/App/assets/22508304/acbdf4b6-ec5c-4b56-a550-f0c708ab6d90">

**Comment by jeet-dhandha** [comment] 2023-07-05 03:42
@mallenexpensify - From video what i understood is the emojis when used from quick reactions doesn't get added under Frequently used in Emoji Picker. 
Also frequently used emojis should show emoji even if they are:
- pasted in the composer
- used from quick reactions 
- Used using `:name:` syntax.

**Comment by alexpensify** [comment] 2023-07-10 21:21
@mallenexpensify -- I'm back online. Could you please share a summary of where we are at and I can run from there? Thank you!

**Comment by mallenexpensify** [comment] 2023-07-12 02:43
@alexpensify , my understanding is that we need to suss out if we want to show the default emoji as frequently used emojis

**Comment by alexpensify** [comment] 2023-07-14 18:57
Thanks @mallenexpensify for watching over. It looks like I need to start a discussion about how we want to handle this one then.

**Comment by mallenexpensify** [comment] 2023-07-15 00:05
I _think_ I think it's repetitive to have both, or unnecessary but, we might want them show for consistency ¯\_(ツ)_/¯

**Comment by alexpensify** [comment] 2023-07-16 17:20
Thank you for the feedback @mallenexpensify

**Comment by jeet-dhandha** [comment] 2023-07-18 20:49
- Updated Proposal - https://github.com/Expensify/App/issues/21799#issuecomment-1612431040 (All change logs for proposal is in the proposal it self)

**Comment by alexpensify** [comment] 2023-07-18 21:31
@shawnborton - Need design feedback if we should update the suggested emojis to be the frequently used ones 

https://github.com/Expensify/App/issues/21799#issuecomment-1636572769

Thanks!

**Comment by shawnborton** [comment] 2023-07-18 23:45
@stitesExpensify thoughts on this one? Was it intentional that we are not replacing the 4 default emojis with the most commonly used ones?

**Closed** 2023-07-19 13:45 UTC
Labels: Daily, Design, Bug

**Comment by alexpensify** [comment] 2023-07-19 15:18
Thank you for the update!
