### ISSUE TITLE
[HOLD on react-native-onyx#283] [$1000] Loading screen does not go away until a hard fresh when opening staging web

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22122] opened 2023-07-03 15:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com
## Expected Result:
Chat should be loaded after a brief seconds
## Actual Result:
Requires a hard refresh

NOTE: Bernhard Owen Josephus can reproduce in Dev 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-06-30 at 9 58 59 AM](https://github.com/Expensify/App/assets/43996225/763e0996-7244-4cfb-b1d1-24a35052372c)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688140800767229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec38f8400cec889b</li>
        <li>Upwork Job ID: 1676993803918155776</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-07-04 15:52
Not a lot to go off, I commented here [in thread](https://expensify.slack.com/archives/C049HHMV9SM/p1688485714787309?thread_ts=1688140800.767229&cid=C049HHMV9SM). A good place to start might be to figure out if there's something blocking the queue.

**Comment by trjExpensify** [comment] 2023-07-06 16:37
Seems to be still happening to @AndrewGable and @bernhardoj, I'll move this on to external for more eyes. A possible lead is [mentioned here](https://expensify.slack.com/archives/C049HHMV9SM/p1688623631917739?thread_ts=1688140800.767229&cid=C049HHMV9SM) in thread.

**Comment by waterim** [comment] 2023-07-09 22:39
Cant reproduce

**Comment by trjExpensify** [comment] 2023-07-10 10:29
Yeah, I think it's going to be a little tough. Did you check out the [slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1688485714787309?thread_ts=1688140800.767229&cid=C049HHMV9SM)?

**Comment by Julesssss** [comment] 2023-07-10 11:43
@waterim this likely won't be possible to reproduce, the cause is unknown at this point. But many of us have the issue so we should be able to verify any fix. I'll be looking into this today

**Comment by Julesssss** [comment] 2023-07-10 16:51
Hey, thanks @pasyukevich but for now I'm going to loo into this myself.

**Comment by Christinadobrzyn** [comment] 2023-07-10 21:01
Hey @sobitneupane We have this [comment](https://github.com/Expensify/App/issues/21881#issuecomment-1629013996) on another job- should we combine that job into this one? cc @aimane-chnaif

**Comment by Julesssss** [comment] 2023-07-11 08:43
@Christinadobrzyn in my opinion they should remain separate issues. If they are solved by the same fix that's a bonus.

**Comment by trjExpensify** [comment] 2023-07-26 11:53
@Julesssss, the linked PR has closed. Confirming we're moving to this one? https://github.com/Expensify/react-native-onyx/pull/283

**Comment by Julesssss** [comment] 2023-07-26 11:57
@trjExpensify yep, we had to fix this in the Onyx repo, so that's the PR to keep an eye on.

**Comment by trjExpensify** [comment] 2023-07-26 12:03
Cool, updated the title.

**Comment by trjExpensify** [comment] 2023-08-07 09:55
Seems like that PR has stalled in review.

**Comment by trjExpensify** [comment] 2023-08-21 11:20
Linked Onyx PR we're held on is still in review.

**Comment by JmillsExpensify** [comment] 2023-08-21 16:51
What's the latest on this one. It's one of the variables we're trying to remove that is slowing down my account to a crawl.

**Comment by Julesssss** [comment] 2023-08-29 13:03
Discussion occuring in the PR[ review](https://github.com/Expensify/react-native-onyx/pull/283)

**Comment by Julesssss** [comment] 2023-08-30 11:17
Just merged the Onyx PR and tested locally. Raised a PR for the Onyx lib bump here.

We never had reliable steps for reproducing this, so i think we'll need to merge with [NO QA] and ask people to test on staging.

**Comment by Julesssss** [comment] 2023-08-31 08:37
We closed our PR as a newer one was opened that bumped the Onyx lib to a higher version. 

> What's the latest on this one. It's one of the variables we're trying to remove that is slowing down my account to a crawl.

But we should be ready to test the fix now!

**Comment by trjExpensify** [comment] 2023-08-31 16:33
Perhaps! I never experienced it though, so I'm not sure. We could wait for a second opinion from @AndrewGable who was the other person experiencing it before we close it out officially.

**Closed** 2023-09-25 11:42 UTC
Labels: Reviewing, Monthly, Bug
