### ISSUE TITLE
Profile - The error message is not triggered right after entering an invalid symbol

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23743] opened 2023-07-27 15:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Tap the avatar icon
3. In settings, select Profile > Display name or Legal name
4. Enter an invalid symbol or word (e.g. semicolon or "Expensify" for Display name) in any of the fields

## Expected Result:
The error is displayed as soon as the invalid symbol or word is entered.

## Actual Result:
The error is triggered after the user starts entering info in the other field or hits "Save" if the invalid symbol is in the last name field. After emptying fields, the error is shown as soon as the invalid symbol is entered.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3219134b-bda9-418b-9f9d-10ff563d3b72

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause -  Internal Team
**Slack conversation:**

**Comment by ygshbht** [comment] 2023-07-27 16:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app doesn't instantly show an error when invalid input is entered in the Profile fields, but waits until the user interacts with another field or hits "Save".

### What is the root cause of that problem?
The form validation currently triggers onBlur or on form submission, not during input changes.

### What changes do you think we should make in order to solve the problem?
We should adjust the form component to validate the input onChange. This change would involve using a similar approach as the existing onBlur validation but triggered on input changes. Please note that this is a rough solution and the actual implementation may require additional adjustments.

```
if (props.validateOnInputChange) {
    setTimeout(() => {
        setTouchedInput(inputID);
        const shouldValidate = !_.isEqual(inputValues, lastValidatedValues.current);
        if (shouldValidate) {
            onValidate(inputValues);
        }
    }, 200);
}

```

**Comment by joh42** [comment] 2023-07-28 08:38
Working on a fix for this regression from issue https://github.com/Expensify/App/issues/21838

**Comment by joh42** [comment] 2023-07-28 11:11
FYI a [PR](https://github.com/Expensify/App/pull/23780) to fix this regression is awaiting review @alexpensify

**Comment by alexpensify** [comment] 2023-07-28 20:52
I ran out of time yesterday and am OOO today. I'll try to review it over the weekend.

**Comment by joh42** [comment] 2023-07-29 08:34
Seems like I was a bit unclear - I didn't mean that you should review that
PR, rather that this issue can be put on hold as a fix is on the way. Have
a nice weekend!

**Comment by alexpensify** [comment] 2023-07-31 22:55
Sorry @joh42 - I missed your comment. Please keep me posted if this bug is still around after the fix is live.

**Comment by alexpensify** [comment] 2023-08-02 17:20
@joh42 - it looks like the PR went to staging yesterday, can you confirm if we can close this one out? Thanks!

**Comment by joh42** [comment] 2023-08-02 17:44
Thanks for the ping, this can be closed now @alexpensify

https://github.com/Expensify/App/assets/138504087/a3648fb2-ec40-4403-98b4-34d9f9a3d4f0

**Comment by alexpensify** [comment] 2023-08-02 18:40
Perfect, thank you for that update!

**Closed by alexpensify** 2023-08-02 18:40 UTC
Labels: Daily, Bug
