### ISSUE TITLE
[Awaiting Payment 4th October] [$125] mWeb - Chat - While editing composer doesn't hide and the editing input doesn't get focused

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48161] opened 2024-08-28 11:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-10
**Reproducible in staging?:** Y
**Reproducible in production?:** N
Issue was found when executing this PR: https://github.com/Expensify/App/pull/45150
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1186@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open a chat and send a message
3. Hold on the sent message and tap on "Edit comment"

## Expected Result:
The compose box hides and the app focuses on the edit input field

## Actual Result:
The composer box doesn't hide and both the compose box and the edit input are visible. The app sometimes doesn't focus on the edit input field after clicking on "Edit comment". If the app focuses on the edit input field then the cursor jumps at the start of the text.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ad629516-ce94-4047-aaa5-68ceaf47a2b6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833542585900797797</li>
        <li>Upwork Job ID: 1833542585900797797</li>
        <li>Last Price Increase: 2024-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103900666</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-08-28 11:02
We think that this bug might be related to #wave-collect - Release 1

**Comment by youssef-lr** [comment] 2024-08-28 14:07
@Skalakid can you take a look at this issue please? Seems related to https://github.com/Expensify/App/pull/45150

**Comment by miljakljajic** [comment] 2024-09-04 09:17
Not overdue - Waiting for more feedback from @Skalakid

**Comment by Skalakid** [comment] 2024-09-04 16:28
I can't test it on the dev build, since I can't see `Edit message` option. However, it appears on staging and I was able to reproduce it also on iOS Safari:


https://github.com/user-attachments/assets/52ce3dc6-9fae-4a0c-b150-063eca076381

It's hard for me to say if it's connected to the Live Markdown refactor changes. We've changed only the markdown structure that is inside the Live Markdown input component. The outside structure wasn't touched. It can be easily checked by changing the version of the `react-native-live-markdown` library to `0.1.116` and verifying if it still occurs. Like I said the edit option bug block me in testing so I can't confirm it

**Comment by Skalakid** [comment] 2024-09-10 08:37
Finally, the bug with message editing has been fixed, and I could test it on the dev environment! I downgraded the version of the `react-native-live-markdown` to `0.1.116` (the one before the refactor) and the bug still occurs. So it's not connected to the live markdown changes.

Also, I tested @bernhardoj's proposal and it [fixes](https://github.com/Expensify/App/issues/48161#issuecomment-2315607224) the issue really well

**Comment by miljakljajic** [comment] 2024-09-10 10:34
@youssef-lr @Skalakid shall we move forward with @bernhardoj 's proposal then?

**Comment by bernhardoj** [comment] 2024-09-11 11:02
PR is ready

cc: @ikevin127 

@youssef-lr btw, is the price reduction intentional?

**Comment by miljakljajic** [comment] 2024-09-20 15:13
Going out on parental leave so I've reassigned to another BZ team member. Thank you @trjExpensify 

Next steps: PR is still being discussed [here](https://github.com/Expensify/App/pull/48973)

When payment is due:
Upwork Offer to be paid for @ikevin127 : https://www.upwork.com/nx/wm/offer/103900666
@bernhardoj is paid via ND manual requests (per this [SO](https://stackoverflowteams.com/c/expensify/questions/16949))

**Comment by ikevin127** [comment] 2024-09-21 00:26
**Update**: Awaiting for @youssef-lr to 🟢 **Approve** and merge PR - currently in talks with PR author to clear up some misunderstandings regarding the issue / implemented fix.

**Comment by trjExpensify** [comment] 2024-09-23 17:16
@youssef-lr thoughts on the PR?

**Comment by youssef-lr** [comment] 2024-09-23 20:57
Merging now!

**Comment by ikevin127** [comment] 2024-09-28 21:17
⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-10-04]** according to yesterday’s production deploy from https://github.com/Expensify/App/pull/48973#issuecomment-2379771842.

cc @trjExpensify

**Comment by trjExpensify** [comment] 2024-10-02 00:30
Sounds good! Updated.

**Comment by trjExpensify** [comment] 2024-10-04 18:04
Payment summary as follows: 

- $125 to @ikevin127 for the C+ review
- $125 to @bernhardoj for the fix 

Paid Kevin, Bernhard will request. Closing!

**Comment by trjExpensify** [comment] 2024-10-04 19:04
Hm.. but the contract has ended, and I don't have the option to pay it anymore. So wtf is that about?

**Comment by trjExpensify** [comment] 2024-10-04 19:05
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/76593bb9-5a21-4726-bf2c-219407e51698">

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/194356a2-3bde-4017-8cfd-bb2a03f1596c">

**Comment by trjExpensify** [comment] 2024-10-04 19:06
No idea what happened there. It doesn't show as being paid either. I'll send you another offer, but if you happen to get a rogue $125 show up - I'll trust your honesty to let me know. :)

**Comment by ikevin127** [comment] 2024-10-04 19:55
@trjExpensify Sure, I accepted the new contract and will let you know in case it comes twice 👍

**Comment by trjExpensify** [comment] 2024-10-04 20:28
Cool, paid!

**Comment by bernhardoj** [comment] 2024-10-05 03:39
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-10-05 06:06
$125 approved for @bernhardoj

**Comment by ikevin127** [comment] 2024-10-11 02:47
Not overdue, issue contributors were paid - waiting for issue closure.

**Comment by trjExpensify** [comment] 2024-10-11 15:03
Closing!

**Closed by trjExpensify** 2024-10-11 15:03 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
