### ISSUE TITLE
[$125] Task - Inconsistency in character limit count shown in mweb and Android.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45458] opened 2024-07-16 08:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4727550
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app in mweb and Android
2. Tap fab - assign task
3. Paste in description - is is your personal space. Use it for notes, tasks, drafts, and reminders.

You can also use the + button to track an expense, or assign a task!This is your personal space. Use it for notes, tasks, drafts, and reminders.

You can also use the + button to track an expense, or assign a task!This is your personal space. Use itL for notes, tasks, drafts, and reminders.

You can also use the + button to track an expense, or assign a task!This is your personal space. Use i
4.Enter title and tap next
5.Note the character limit count

## Expected Result:
There must not be inconsistency in character limit count shown in mweb and Android.

## Actual Result:
Inconsistency in character limit count shown in mweb and Android. In mweb, shown as 519 and in Android as 501.

In production mweb also it shows 501.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/95e98df0-4ca2-4510-92a1-5a93f27c0029

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f64b5d16f1171bcc</li>
        <li>Upwork Job ID: 1813225380361382299</li>
        <li>Last Price Increase: 2024-07-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by izarutskaya** [comment] 2024-07-16 08:48
We think this issue might be related to the #vip-vsb.

**Comment by youssef-lr** [comment] 2024-07-16 14:52
Demoting, I think this is a very minor issue and shouldn't be a blocker.

**Comment by brunovjk** [comment] 2024-07-17 14:50
Thank you for the proposal @Krishna2323, I tested your solution, and it indeed fixes the issue. However, I'm wondering about the root cause. Could you share more details about it? I'm concerned about this comment:

```
In mweb, shown as 519 and in Android as 501.

In production mweb also it shows 501.
```

Do you know what changed to cause the issue? Thank you very much for your time.

**Comment by brunovjk** [comment] 2024-07-18 10:43
Im sorry @Krishna2323, my mistake

**Comment by brunovjk** [comment] 2024-07-18 10:51
Im sorry @Krishna2323, my mistake, I shouldn't have posted this message. Please contact an intern.

**Comment by mallenexpensify** [comment] 2024-07-19 00:42
@Krishna2323 we were reviewing your assigned issues and requested to pause hiring while we did so. @brunovjk , please review @Krishna2323 's proposal as you normally would. Thx.

**Comment by brunovjk** [comment] 2024-07-22 11:16
Hi @Krishna2323, sorry again for the inconvenience, can you share more details about the _root cause_ here? From what I understood, you are suggesting remove `ReportUtils.getCommentLength` in the indicated places, however the same issue will not be observed in other places where we use `ReportUtils.getCommentLength`? Thank you.

**Comment by brunovjk** [comment] 2024-07-25 18:25
Waiting proposal

**Comment by johncschuster** [comment] 2024-07-29 14:47
This feels #vip-vsb related, which has been punted. @trjExpensify, do you want to fold this one into #wave-collect?

**Comment by johncschuster** [comment] 2024-07-29 16:38
I've brought this up in [#tasks](https://expensify.slack.com/archives/C05M6LM4TU0/p1722268939858979). Tasks is not on the roadmap at the moment, so I'll be closing this unless we have a compelling reason to keep it open.

**Closed** 2024-07-29 16:38 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
