### ISSUE TITLE
[Workspace Feeds] Android - Ecard -  Impossible to issue first card on a new account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51583] opened 2024-10-28 16:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3272217
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: new expensifail account. WS added (USD currency). Expensify card is enabled. VBA is added on Expensify card tab via ND application
1. Go to WS > Expensify card
2. Tap 'Issue card' > choose any card type
3. Proceed the flow to the end > tap 'Issue card'

## Expected Result:
Card is added for the WS admin

## Actual Result:
An error appears 'Oops... something went wrong and your request could not be completed. Please try again later.'
NOTE: admin can add Ecard via ND app (web. desk) first, delete it and then add via Hybrid app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/5cbb6dfa-86f7-4f5b-813d-e04bc17600cc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-28 16:31
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-10-28 16:31
We think that this bug might be related to #wave-collect - Release 2

**Comment by muttmuure** [comment] 2024-10-30 19:21
Looking tomorrow

**Comment by muttmuure** [comment] 2024-11-04 13:06
Asking about this here: https://expensify.slack.com/archives/C05LX9D6E07/p1730725586749509?thread_ts=1728966082.429659&cid=C05LX9D6E07

**Comment by mountiny** [comment] 2024-11-04 13:14
Asked QA for more details [here](https://expensify.slack.com/archives/C9YU7BX5M/p1730725877343599)

**Comment by trjExpensify** [comment] 2024-11-04 13:22
@mountiny: https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228d9b4061db4eca30-KBP%22)+AND+timestamp:[2024-10-28T12:25:23.029Z+TO+2024-10-28T14:25:23.029Z]&index=logs_expensify-030924

and right before that: https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228d9b3ff5581bca30-KBP%22)+AND+timestamp:[2024-10-28T12:25:07.108Z+TO+2024-10-28T14:25:07.108Z]&index=logs_expensify-030924

```
[ExpensifyCard] User_Utils - Failed to provision Expensify Card Company Expensify\Libs\Error\ExpError - e4d2bfc0-4573-4720-8062-6ac15323b185 ~~ domain: 'expensify-policy7a208df74deb1151.exfy' bankAccountID: '6348868' domainName: 'expensify-policy7a208df74deb1151.exfy' jsonCode: '401' message: '401 Missing balance verification' exceptionJsonCode: '666' exceptionUserMessage: 'Failed to provision domain' exceptionMessage: 'Failed to provision domain' exceptionFile: '/git/releases/expensify.com/15e3807/lib/BankAccountAPI.php' exceptionLine: '1712' exceptionCode: '666'
```

**Comment by trjExpensify** [comment] 2024-11-04 13:23
Given the below, I'm dropping the HybridApp distinction from the title. It's not exclusively a HybridApp bug, so the title is confusing. 

>If this was caught on HybridApp, is this reproducible on New Expensify Standalone?: Y

**Comment by mountiny** [comment] 2024-11-04 13:26
@koko57 we have been working on awaiting for a successful domain provisioning before we can issue a card. Those changes are not deployed yet, right? It should fix this case too as we would not let the user attempt issuing card without successfully provisioning

**Comment by koko57** [comment] 2024-11-04 13:44
yep, it was deployed to staging in 9.0.56-0 https://github.com/Expensify/App/pull/51407#issuecomment-2449649825 and here we have 9.0.54-2 in the description. So it needs to be retested

**Comment by mountiny** [comment] 2024-11-04 23:05
Asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1730761497246179)

**Comment by kavimuru** [comment] 2024-11-05 14:14
Now bug is not reproducible , but with a new account it is impossible to issue card without relogin. The flow leads  to Concierge chat. card issued after relogin to account.


https://github.com/user-attachments/assets/eb074270-69d5-4a14-b3ea-5c096f858a32


https://github.com/user-attachments/assets/6678ae41-b62a-47da-84d6-7e1590eb083c

**Comment by mountiny** [comment] 2024-11-05 21:08
Nice yeah that looks expected because the account got flagged so we had to manually review it.

Although I am not sure if its expected it would start working after simply re-logging in

**Comment by mountiny** [comment] 2024-11-05 22:58
I think we can close this one then because the verification page is expected

**Closed by mountiny** 2024-11-05 22:58 UTC
Labels: Daily, Bug
