### ISSUE TITLE
Chat - Pin icon flashes after switching back to online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14720] opened 2023-02-01 01:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/14608

## Action Performed:
1.Go offline
2.Pin a chat
3.Unpin a chat
4.Pin a chat again
5.Go online

## Expected Result:
Chat ends up in the correct state of "pinned" without any blinking

## Actual Result:
Pin icon flashes after switching back to online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.63.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/215926287-a53d8a94-21df-41fc-9cc0-ec557d59cc73.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019efbe2b8f3460e9e</li>
        <li>Upwork Job ID: 1620912782462525440</li>
        <li>Last Price Increase: 2023-02-01</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-02-01 11:02
I think this is to some extent expected because all the actions made offline are queued to be done when user comes back online. Hence if user will toggle the settings there and back while offline and comes back online, the requests will be sequentially made to the server resulting in this flickering behaviour. it does not look great, but I think this is not strictly a bug.

**Comment by greg-schroeder** [comment] 2023-02-01 20:55
Gotcha, thanks for that context @mountiny - do you think we should close this for now then to focus on other items?

**Comment by mountiny** [comment] 2023-02-01 22:31
@greg-schroeder Now I have noticed the issue is mentioning a PR https://github.com/Expensify/App/pull/14608 where this was noticed. It might not be related but it might be worth:
- check if engineer can repro locally on `main`
- reverting that change in the mentioned PR locally
- check if you can repro after the change

That would confirm this was caused by that PR.

If not, then I would probably close this.

**Comment by mountiny** [comment] 2023-02-01 22:33
@greg-schroeder can you also add Engineering so it picks someone internal, thanks!

**Comment by mountiny** [comment] 2023-02-01 23:13
Yep sorry, missed before this is coming form latest deploy https://github.com/Expensify/App/issues/14709#issuecomment-1412670582 so we should investigate if this is not a deploy blocker actually cc @thienlnam

**Comment by greg-schroeder** [comment] 2023-02-02 00:21
Sure, I assigned `Engineering` to help with https://github.com/Expensify/App/issues/14720#issuecomment-1412828802

**Comment by tgolen** [comment] 2023-02-03 16:03
I am closing this because it is expected behavior as Vit points out. We've discussed this several times, and we have always opted to just let the network queue play out naturally when someone comes back online.

**Closed by tgolen** 2023-02-03 16:03 UTC
Labels: Engineering, Daily, Internal, Bug
