### ISSUE TITLE
Workspace - "Find a workspace" text is missing from search bar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43220] opened 2024-06-06 20:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41158
## Action Performed:
1. Open New Expensify app
2. Sign into a valid account
3. Click on WS switcher and observe the search bar

## Expected Result:
According to the PR, there should be a search bar with the text "Find a workspace"

## Actual Result:
There is no text within the search bar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![WS_Search_](https://github.com/Expensify/App/assets/78819774/9ceabb98-1158-4b6d-960c-6c5631f7cd04)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-06 20:14
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CortneyOfstad** [comment] 2024-06-10 17:05
Going to check with the design team on this, as I am not sure if the text was not listed intentionally.

**Comment by CortneyOfstad** [comment] 2024-06-10 17:13
Confirmed with the design team [here](https://expensify.enterprise.slack.com/archives/C03TME82F/p1718039243283519), that this is **not a bug** as how it's displayed now is the same as if you're searching for a category (for example) when you submit an expense. 

Closing!

**Closed by CortneyOfstad** 2024-06-10 17:13 UTC
Labels: Daily, Bug
