### ISSUE TITLE
[$250] Removal from approval workflow whisper doesn't mark chat unread

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#50803] opened 2024-10-15 15:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1728690809841219

## Action Performed:
1. Create a workspace + enable approvals
2. Invite two approvers
3. Set Appprover 1 as the approver for everyone
4. Confirm Approver 1 has access to all user workspace chats
5. Set Apprvoer 2 as approver for everyone

## Expected Result:
Approver 1 should receive a whisper in their workspace chat that they've been removed from the approval workflow and workspace chat for submitters AND their workspace chat should be set to unread.

## Actual Result:
Approver 1 receives a whisper in their workspace chat that they've been removed from the approval workflow and workspace chat for submitters, but the chat was not set to unread so the approver missed the notification.

## Workaround:
Yeah, they'll just be confused.

## Platforms:
All

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846286835786031750</li>
        <li>Upwork Job ID: 1846286835786031750</li>
        <li>Last Price Increase: 2024-10-22</li>
    </ul>
</details>

**Comment by JKobrynski** [comment] 2024-10-16 07:32
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by Beamanator** [comment] 2024-10-16 09:16
Hmm I have a feeling it could be best to do this in the backend 🤔

**Comment by kadiealexander** [comment] 2024-10-17 03:55
@JKobrynski do you think this can be fixed from the front end?

**Comment by JKobrynski** [comment] 2024-10-17 08:58
@kadiealexander I am going to verify this today!

**Comment by JKobrynski** [comment] 2024-10-17 14:07
I just finished my small investigation and based on what I've found it would be difficult to fully fix it on the frontend. The report doesn't fulfill any of the if statements in `getReasonAndReportActionThatRequiresAttention` that would cause it to render as an unread report. What we could do is add a `pendingAction` field on the backend. What do you think? 

CC: @Beamanator @kadiealexander

**Comment by Beamanator** [comment] 2024-10-17 18:44
I agree it would be easier to fix in the backend - though I believe we have other ways of making a message unread, not just via `pendingAction` Onyx field

**Comment by JKobrynski** [comment] 2024-10-18 08:32
That's right! I was just suggesting one of the ways this could be handled 😄

**Comment by fabioh8010** [comment] 2024-10-22 20:33
Hey 👋 Just FYI that @JKobrynski is on sick leave since yesterday and is expected to return next week.

**Comment by situchan** [comment] 2024-10-22 20:35
Not overdue

**Comment by JKobrynski** [comment] 2024-10-24 10:32
Hey! FYI I'm back from the sick leave, I'll continue working on this issue

**Comment by JKobrynski** [comment] 2024-10-24 11:07
@situchan as discussed with @Beamanator it looks like this should be fixed on the backend, is there any update on that?

**Comment by kadiealexander** [comment] 2024-10-25 06:33
Not overdue.

**Comment by kadiealexander** [comment] 2024-10-25 06:34
Not overdue! Assigning someone to babysit this while I'm OOO for the next two weeks.

**Comment by situchan** [comment] 2024-10-28 06:00
@Beamanator you wanna work on this as you have context already?
Pulling up engineer otherwise 🎀👀🎀

**Comment by Beamanator** [comment] 2024-10-28 08:09
I'm happy to assist! But I'm deployer this week so probably won't have much time to take it myself

**Comment by dangrous** [comment] 2024-10-29 19:47
Still looking into this, I can replicate it on dev, interestingly at least in my testing the message IS marked as unread, but only when i click into the report itself, it's not marked as unread or updated in the LHN.

I think I've figured out why - we don't send onyxUpdates for reports for whispers, because we "don't want whispers to show in the LHN." (from a comment in the code). In this case I guess we DO want it to show - so should I make a specific exemption in the logic for this case, and no other? It feels a little strange but would work..

**Comment by dangrous** [comment] 2024-10-31 14:38
Continuing to discuss expected behavior. None of the potential fixes are that hard, but we need to figure out what direction we want to go in

**Comment by dangrous** [comment] 2024-10-31 14:59
https://github.com/Expensify/App/pull/51588 is very related, depending on how we fix this we can fix that one too

**Comment by dangrous** [comment] 2024-11-01 18:30
still discussing expected behavior in Slack

**Comment by situchan** [comment] 2024-11-04 20:05
I am going to be on parental leave. Please reassign C+

**Comment by dangrous** [comment] 2024-11-04 20:42
as above. bumped the convo for this week - https://expensify.slack.com/archives/C06ML6X0W9L/p1730752921770799?thread_ts=1728690809.841219&cid=C06ML6X0W9L - seems like we're not clear on a next step yet, though the actual fix will be pretty quick so that's good

**Comment by dangrous** [comment] 2024-11-05 16:35
Asking around for a new C+!

https://expensify.slack.com/archives/C02NK2DQWUX/p1730824497966189

**Comment by dangrous** [comment] 2024-11-07 19:24
k backend PR is in review! From testing, I think it actually does everything we need here (no frontend required), and we should be able to close after it's merged.

**Comment by dangrous** [comment] 2024-11-11 16:19
Hi all! Backend fix is deployed. Can we retest this and see if anything else is needed? Thanks!

**Comment by stephanieelliott** [comment] 2024-11-12 21:31
I'm unable to repro now, seems like this is fixed! 🎉

**Closed by stephanieelliott** 2024-11-12 21:31 UTC
Labels: Reviewing, Daily, Internal, Bug
