### ISSUE TITLE
[HOLD for payment 2023-10-25] [$500] LHN - New 1:1 DM appears briefly in LHN without avatar and username when IOU is received

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27878] opened 2023-09-20 18:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app as User A
2. Keep app in the foreground
3. As User B, who has no chat history with User A, send a money request to User A

## Expected Result:
The new 1:1 DM and IOU report show up on LHN without issue

## Actual Result:
The new 1:1 DM appears without avatar and username briefly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img width="364" alt="Bug6207763_Screenshot_2023-09-21_at_01 22 05" src="https://github.com/Expensify/App/assets/78819774/8342a220-81bf-4d91-abde-88bf871e820e">

https://github.com/Expensify/App/assets/78819774/9038986c-49fe-4e17-b553-db35ca8c3ddd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f7a7f916499f922b</li>
        <li>Upwork Job ID: 1704637836346048512</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27105842</li>
<li>rojiphil | Contributor | 27105844</li>
</ul></li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2023-09-20 22:08
Unable to reproduce so far

**Comment by MitchExpensify** [comment] 2023-09-20 23:25
Reproduced, labelling External in case someone can beat @chiragsalian to the punch here!

**Comment by chiragsalian** [comment] 2023-09-20 23:47
i can reproduce the issue as well. It also only occurs on staging and not production.

**Comment by chiragsalian** [comment] 2023-09-21 00:58
I'm unfortunately not able to solve this today. I'll post on slack if someone else can investigate. If not i can continue with it tomorrow.

**Comment by thienlnam** [comment] 2023-09-21 08:48
This looks pretty minor, so removing the deploy blocker label

**Comment by rojiphil** [comment] 2023-09-21 12:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For User B, the LHN for a Chat Report from User A displays briefly displays without an avatar and username when a Money Request was initiated by User A and there was no chat history between User A and User B.

### What is the root cause of that problem?
When User A initiates a chat with User B for the first time with a Money Request, User B will receive the request via pusher with bare minimum details. These initial details do not include an avatar and username and, hence, do not get displayed in LHN. 

Since the report is not completely visible, FE will immediately initiate a `ReconnectToReport` API to fetch the complete Chat Report as shown [here](https://github.com/Expensify/App/blob/b225b53829f8fa4ef5f7a75616469d1fc7d347b9/src/libs/actions/Report.js#L901C1-L905C6). Once the Chat Report arrives, the LHN displays the avatar and username. 

This causes a brief display without an avatar and username.

### What changes do you think we should make in order to solve the problem?

The decision to include a report in LHN is decided by function `shouldReportBeInOptionList` [here](https://github.com/Expensify/App/blob/b225b53829f8fa4ef5f7a75616469d1fc7d347b9/src/libs/OptionsListUtils.js#L984). The first thing we do in the function is to check if the report is ready for display. If not, we will not include it. In this case, we can additionally look for a valid `type` within the report to decide whether to include or not by making the following change [at this location](https://github.com/Expensify/App/blob/b225b53829f8fa4ef5f7a75616469d1fc7d347b9/src/libs/ReportUtils.js#L2888C1-L2902C1)

Once the complete report details arrive at FE, the LHN will display correctly.

```
    if (
        !report ||
        !report.reportID ||
+       !report.type ||
        report.isHidden ||
        (report.participantAccountIDs &&
            report.participantAccountIDs.length === 0 &&
            !isChatThread(report) &&
            !isPublicRoom(report) &&
            !isArchivedRoom(report) &&
            !isMoneyRequestReport(report) &&
            !isTaskReport(report))
    ) {
        return false;
    }  
```
### Test Video

https://github.com/Expensify/App/assets/3004659/e7309088-cd9e-4509-ac7e-9df082d7f106

### What alternative solutions did you explore? (Optional)

**Comment by MitchExpensify** [comment] 2023-09-26 04:37
@abdulrahuman5196 How does the proposal look to you?

**Comment by MitchExpensify** [comment] 2023-09-28 05:56
Bump @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2023-09-28 06:21
TAL now. Sorry for the delay

**Comment by abdulrahuman5196** [comment] 2023-09-29 11:10
@chiragsalian / @MitchExpensify The proposal by @rojiphil here https://github.com/Expensify/App/issues/27878#issuecomment-1729436030 mentions a behaviour of not showing the LHN item until we have full details.

But shouldn't we show placeholder avatar and name until the full LHN details loads?  Could we confirm on the behaviour.

**Comment by MitchExpensify** [comment] 2023-09-30 05:12
I think not showing the LHN item until we have full details sounds like better UX. What do you think @chiragsalian ?

**Comment by MitchExpensify** [comment] 2023-10-03 15:30
Lets run with this @abdulrahuman5196 "not showing the LHN item until we have full details"

**Comment by chiragsalian** [comment] 2023-10-03 18:30
Just catching up here., i'm okay with - "not showing the LHN item until we have full details"

But i am curious about this bit,
> When User A initiates a chat with User B for the first time with a Money Request, User B will receive the request via pusher with bare minimum details. These initial details do not include an avatar and username and, hence, do not get displayed in LHN.

Is this true, if so what API command is this? I would think it's `SplitBillAndOpenReport`, but from what i can tell that command does push avatar and username. Is it pushing incorrect values or were you thinking of a different API command?

**Comment by rojiphil** [comment] 2023-10-04 01:57
> Is it pushing incorrect values or were you thinking of a different API command?

@chiragsalian In my tests, the API command used was `RequestMoney`. If BE can send all the required details, that can also solve this problem. 
Nevertheless, it may also be a good idea to have this check of a valid `type` in FE as report `type` is a very basic requirement for sane operations in FE.

**Comment by chiragsalian** [comment] 2023-10-05 22:27
> it may also be a good idea to have this check of a valid type in FE as report type is a very basic requirement for sane operations in FE.

Yup i agree. It nice to have this fix in FE. Just trying to find out if its necessary. I just tested on dev and cannot reproduce the issue because there is a placeholder avatar and email is shown. Can you retest @rojiphil? 

 > In my tests, the API command used was RequestMoney

Ah `RequestMoney`, yeah i see the problem in the BE. It does not push onyx personal details.

**Comment by rojiphil** [comment] 2023-10-06 07:58
@chiragsalian 
ha ha 😆, some good soul has already fixed this.
If you notice, iou report shows up later.
Attaching test video from latest main.
I think, we can close this.

https://github.com/Expensify/App/assets/3004659/33bca2f8-73c9-4e66-bcc1-e81b229ff23d

**Comment by abdulrahuman5196** [comment] 2023-10-06 14:38
@rojiphil The issue is not fixed. Tested in latest main.
Even in you video the issue is present.
<img width="262" alt="Screenshot 2023-10-06 at 8 07 13 PM" src="https://github.com/Expensify/App/assets/46707890/d1cb0a1b-f5e1-4091-87be-045af81dc434">

**Comment by abdulrahuman5196** [comment] 2023-10-06 14:41
@chiragsalian I am still able to reproduce the issue in latest main.

Do you agree on both Frontend and backend fix, or should be just one side fix?

**Comment by rojiphil** [comment] 2023-10-06 14:46
> @rojiphil The issue is not fixed. Tested in latest main. Even in you video the issue is present.

@abdulrahuman5196 Oh! My bad. You sure have eagle eyes 🦅

**Comment by chiragsalian** [comment] 2023-10-06 18:12
oh interesting, I thought the issue was just for the person making the request (the left person in your video). Didnt realize the bug was for the person the request was made for (the person on the right).

I agree this should be a front and backend fix. I'm fine with @rojiphil [proposal](https://github.com/Expensify/App/issues/27878#issuecomment-1729436030) here. What are your thoughts on this @abdulrahuman5196?

**Comment by abdulrahuman5196** [comment] 2023-10-09 10:01
Yes. Tested @rojiphil 's proposal here https://github.com/Expensify/App/issues/27878#issuecomment-1729436030 and it is working fine.

🎀 👀 🎀
C+ Reviewed

@chiragsalian

**Comment by chiragsalian** [comment] 2023-10-09 18:19
Feel free to create the PR @rojiphil

**Comment by MitchExpensify** [comment] 2023-10-20 20:35
**Payment summary**:

- $500 @rojiphil requires payment [offer](https://www.upwork.com/nx/wm/offer/27105844) (Contributor) (Upwork)
- $500 @abdulrahuman5196 requires payment [offer](https://www.upwork.com/nx/wm/offer/27105842) (Reviewer) (Upwork)

**Comment by rojiphil** [comment] 2023-10-21 04:14
> **Payment summary**:
> 
> * $500 @rojiphil requires payment [offer](https://www.upwork.com/nx/wm/offer/27105844) (Contributor) (Upwork)
> * $500 @abdulrahuman5196 requires payment [offer](https://www.upwork.com/nx/wm/offer/27105842) (Reviewer) (Upwork)

@MitchExpensify @abdulrahuman5196 

Wanted to check if this qualifies for bonus payment as, I think, the issue got fixed before 3 days.
It was just that the final approval and merger from internal team member took some extra time. 
What are your thoughts?

Here are the timeline details that I could gather:
Assigned : Oct. 09, 11:49 PM, GMT+5:30 [link](https://github.com/Expensify/App/issues/27878#issuecomment-1753453587)
Completed: Oct. 12, 04:27 PM, GMT+5:30 [link](https://github.com/Expensify/App/pull/29155#pullrequestreview-1673873756)
Time Taken: Approximately 2 days 17 hours.

**Comment by MitchExpensify** [comment] 2023-10-22 19:16
**Assigned**:
<img width="509" alt="image" src="https://github.com/Expensify/App/assets/36425901/738a48e6-fcd9-4101-9797-d6d0f7fd7671">

**Merged**:
<img width="235" alt="image" src="https://github.com/Expensify/App/assets/36425901/f07ffa47-5c43-4e1e-920d-1c4b71181845">

**Comment by MitchExpensify** [comment] 2023-10-22 19:18
That looks over 3 days to me from assignment to merge but please let me know if I'm missing something!

**Comment by rojiphil** [comment] 2023-10-23 02:12
> That looks over 3 days to me from assignment to merge but please let me know if I'm missing something!

@MitchExpensify 

You are right that assignment to merge took more than 3 days.
What I was just trying to point out [here](https://github.com/Expensify/App/issues/27878#issuecomment-1773653243) was that the work got done by C and C+ team within 3 days (screenshot below).
It was just that the final approval and merger took some time.

But, I am also fine with the payment summary you mentioned [here](https://github.com/Expensify/App/issues/27878#issuecomment-1773361592) 

![Screenshot 2023-10-23 at 7 35 04 AM](https://github.com/Expensify/App/assets/3004659/731a5325-5295-49fb-901d-e107b2a7d9d4)

**Comment by abdulrahuman5196** [comment] 2023-10-23 13:06
This would be eligible for bonus IMO. We do consider the bonus for similar issues as well since the PR review/approval was completed in 3 days, but wasn't merged internally and the PR didn't have changes after C+ approval as well.

**Comment by MitchExpensify** [comment] 2023-10-25 17:17
Cool! I see what you are saying and I think that all sounds fair - Updating the payment summary

**Comment by rojiphil** [comment] 2023-10-25 17:22
Received the payment. Thanks @MitchExpensify.

**Comment by MitchExpensify** [comment] 2023-10-25 17:23
Paid and contracts ended 👍 

Do we need regression steps @abdulrahuman5196 ?

**Comment by abdulrahuman5196** [comment] 2023-10-25 19:46
>The PR that introduced the bug has been identified. Link to the PR:
 The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
 A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion

Not a regression 

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

No. regression tests wouldn't be beneficial here.

**Comment by MitchExpensify** [comment] 2023-10-28 21:25
Cool, closing! Thanks, everyone

**Comment by abdulrahuman5196** [comment] 2023-10-31 09:30
> Cool, closing! Thanks, everyone

@MitchExpensify This issue is not closed 🤔

**Closed** 2023-10-31 23:10 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
