### ISSUE TITLE
[HOLD] [$1000] Log in - Fast typing of login magic code omits digits

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26090] opened 2023-08-28 14:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to login page
2. Type an email and continue
3. Type the magic code quickly

## Expected Result:
All typed digits should be captured

## Actual Result:
Some digits are omitted (skipped).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/1e1b2ead-d1bd-4188-9fbb-6edcbb535d67

https://github.com/Expensify/App/assets/115492554/079896c5-677d-409a-b229-2cc90b1a71be

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tymatein

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692185514653689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f24f0f546442723</li>
        <li>Upwork Job ID: 1696319642103128064</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26456670</li>
<li>tymatein | Reporter | 26456673</li>
</ul></li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-08-29 00:26
Reproducible on Android 13, Pixel 6.

**Comment by marcaaron** [comment] 2023-09-01 18:14
What's the status on this bug? This seems kinda important given that every new user that signs up on Android will have an awful first experience trying to enter their magic code. I tried it just now and it is almost unusable.

**Comment by marcaaron** [comment] 2023-09-01 18:15
@Swor71 Thanks can you get started on this right away?

**Comment by strepanier03** [comment] 2023-09-01 23:27
Contributor assigned, I'll check in on Monday to bump if needed.

**Comment by Swor71** [comment] 2023-09-04 09:03
hey, yes, I'm currently looking into this issue

**Comment by strepanier03** [comment] 2023-09-05 23:29
Thanks @Swor71!

**Comment by strepanier03** [comment] 2023-09-11 12:26
Geeeeze Melvin, cool your jets!

Thanks for the update @Swor71, we'll keep an eye out for more from you Monday.

**Comment by Swor71** [comment] 2023-09-14 12:46
hey, I've had some issues reproducing this behaviour on an emulator but when testing on a real device (Galaxy S8, Android 9) it is rather obvious how it can be a problem, even though most people probably wouldn't type in the code that fast.

I wanted to ask, if this has been in such a state for a while or has it started recently, maybe after some refactor or pr merge in general? The reason I am asking is that, from what I could gather, nothing in particular stands out as an obvious problem, other than rather large amount of processing of the input that takes place when typing.

**Comment by strepanier03** [comment] 2023-09-14 20:25
Just based on my own experience, I feel like this has been an issue for some time (aka not recent), but either it's been hard to repro or it's felt like a problem that most people wouldn't run into because entering the code that fast is uncommon. 

Ideally, we'd want to improve the experience here so that no one is running into it, even if it would be rare to do so. 

As someone not as familiar with the coding side of things, this doesn't really sound like an easy fix or at least one that would require improvements in other areas of the app to allow for faster processing, is that correct? Is that feasible via this GH or would that be more like a feature request to make a wider improvement to something?

What would you recommend @Swor71 @aimane-chnaif?

**Comment by Swor71** [comment] 2023-09-15 12:34
Thank you for your insight @strepanier03 and yes, you got that absolutely right - it does not seem like an easy bug fix and most likely would require a further, more holistic, look as you've said. 

To my mind the amount of processing is extensive but on the other hand that probably is the requirement. At the same time I cannot guarantee that any slight refactor, simplifying the processing would solve the problem entirely but that might be a good place to start.

I might be missing some context on this issue and the requirements for that part of the app in general so suggesting any particular course of action at the moment wouldn't make much sense without the input and/or other opinions, which I'd love to hear.

**Comment by strepanier03** [comment] 2023-09-18 19:48
Thank you @Swor71 - I'll raise this in Slack for wider discussion and link back here.

**Comment by strepanier03** [comment] 2023-09-18 20:04
Raised [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1695067185379819).

**Comment by tymatein** [comment] 2023-09-18 20:34
I debugged it lightly when reporting the error. I did not find the handlers computationally intensive. But on Android, the entire page is re-rendered many times (~4 times) with each keystroke. Probably when focusing next input the soft-key is hidden and redisplayed, which causes the screen to resize and thus the whole page is redrawn.

**Comment by tymatein** [comment] 2023-09-18 20:58
I apologize for the inconvenience, but I declined the offer https://github.com/Expensify/App/issues/26090#issuecomment-1703154424 because it included a bug report reward of $50 instead of $250 under the old terms. If I'm not mistaken, I'd be glad if you'd look into it. Many thanks.

**Comment by strepanier03** [comment] 2023-09-21 01:10
@tymatein - I apply the additional $200 as a bonus when paying out. The automation creates a job at $50 now but I know to look at the bug report date to determine the final payment.

**Comment by strepanier03** [comment] 2023-09-27 22:04
Commented [here](https://expensify.slack.com/archives/C05LX9D6E07/p1695698961362069). Where it was raised again.

**Comment by strepanier03** [comment] 2023-10-02 19:08
In the thread, https://github.com/Expensify/App/pull/24012 was linked as a possible resolution but this is still happening to me if I type really fast.

**Comment by strepanier03** [comment] 2023-10-02 19:10
Aaah, that was reverted so we're holding until it is deployed again so we can test again.

**Comment by strepanier03** [comment] 2023-10-24 18:31
Still held on https://github.com/Expensify/App/pull/28711. Will check again.

**Comment by tymatein** [comment] 2023-11-13 13:50
Thank you @strepanier03 for the https://github.com/Expensify/App/issues/26090#issuecomment-1728618560 . I actually had turned down an offer on Upwork. If that's not a problem, I would need a new offer for bug reporting that I could accept. Sorry for the inconvenience.

**Comment by strepanier03** [comment] 2023-11-17 18:46
Sure thing @tymatein - I'll send that over when the PR is merged. This has already been on hold a long time and I don't want to make another job that is going to expire if we don't finish this soon. 

I'm following along and once this is off hold I'll make the job and hire you for it.

**Closed** 2024-03-15 19:16 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Bug
