### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] Onboarding - New user lands on workspace chat when 'Manage my team's expenses' selected in modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50578] opened 2024-10-10 14:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.47-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5070660
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify app
2. Log in with new gmail user
3. Select 'Manage my team's expenses' in onboarding modal
4. Enter workspace name, user name and submit modal

## Expected Result:
Either Concierge chat or LHN should be displayed

## Actual Result:
Workspace chat is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/3b43a8bd-38bd-4002-adf7-a3b09311f6fc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844427822228964480</li>
        <li>Upwork Job ID: 1844427822228964480</li>
        <li>Last Price Increase: 2024-10-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by MarioExpensify** [comment] 2024-10-10 14:42
Trying to track down which PR caused the issue right now

**Comment by mkzie2** [comment] 2024-10-10 17:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace chat is displayed

### What is the root cause of that problem?
This comes from https://github.com/Expensify/App/pull/50278

We always navigate to the last accessed report here. In this case when we select `Manage my team's expense`, the policy expense chat is created and it's the last access report


https://github.com/Expensify/App/blob/d93f29aac1c58a391baee08204a8f1acfbb66bc0/src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx#L85-L88

### What changes do you think we should make in order to solve the problem?


I checked and this logic is used when the user signs in with a public room. Then we can check if the `lastAccessedReport` is  the report from the `onboardingPolicyID` we will navigate to concierge chat otherwise navigate to the last access report 

```
const lastAccessedReport = ReportUtils.findLastAccessedReport(!canUseDefaultRooms, shouldOpenOnAdminRoom(), activeWorkspaceID);
const lastAccessedReportID = lastAccessedReport?.reportID
if (!lastAccessedReportID || lastAccessedReport?.policyID === onboardingPolicyID) {
    // We can return early or navigate to concierge here
    Report.navigateToConciergeChat();
    return;
}
const lastAccessedReportRoute = ROUTES.REPORT_WITH_ID.getRoute(lastAccessedReportID ?? '-1');
Navigation.navigate(lastAccessedReportRoute);
```
https://github.com/Expensify/App/blob/d93f29aac1c58a391baee08204a8f1acfbb66bc0/src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx#L85-L88

### What alternative solutions did you explore? (Optional)
NA

**Comment by ikevin127** [comment] 2024-10-10 18:40
Given that the offending PR was reverted, this issue should be fixed - not an issue anymore.

**Comment by mvtglobally** [comment] 2024-10-10 22:29
Seems resolved https://github.com/user-attachments/assets/2f6b51a4-ebca-436f-8780-92c0dec3e2e4

**Comment by wildan-m** [comment] 2024-10-11 03:27
Hi, does anyone know why I have different flow? 

I've overridden canUseAllBetas, but it remains different.

cc: @thesahindia, @lakchote 

https://github.com/user-attachments/assets/8d52ee10-fb78-425a-be51-8e8c988d9230

**Comment by lakchote** [comment] 2024-10-11 06:02
> Hi, does anyone know why I have different flow?
> 
> I've overridden canUseAllBetas, but it remains different.
> 
> cc: @thesahindia, @lakchote
> 

You didn't use a gmail account to sign up.

It's written in the issue's reproduction steps.

**Comment by wildan-m** [comment] 2024-10-11 08:26
@lakchote I've tried using gmail, but its flow still different compared to the reproduction steps above. And can't reproduce the issue even when my prev PR applied.


https://github.com/user-attachments/assets/b2daf712-f56e-459a-8749-fb8dcec5f9e6

**Comment by MarioExpensify** [comment] 2024-10-11 12:38
I'll close the issue, feel free to continue the discussion in it, it is just to clear up my K2.

**Comment by lakchote** [comment] 2024-10-11 15:48
> I'll close the issue, feel free to continue the discussion in it, it is just to clear up my K2.

@MarioExpensify  please do not close it, as we still have a discussion ongoing and the problem hasn't find resolution yet.

If it's to clear up your K2, just unassign yourself. Thanks!

**Comment by lakchote** [comment] 2024-10-11 16:11
@wildan-m yes I've been able to reproduce (on your original PR's branch):


https://github.com/user-attachments/assets/c3f95311-ec6c-4da1-8ac5-1ff393b02159

**Comment by adelekennedy** [comment] 2024-10-28 03:51
double check me here @lakchote 
Payouts due:

- [ ] Contributor: $250 @wildan-m Upwork (@wildan-m sent to you Upwork!)
- [ ] Reviewer: $250 @thesahindia NewDot

Upwork job is [here](https://www.upwork.com/ab/applicants/1844427822228964480/hired).

**Comment by wildan-m** [comment] 2024-10-28 04:35
I'm sad about the penalty on the original issue https://github.com/Expensify/App/issues/48715 but unsure if I qualify for payment in this one. Is resolving this part of the regression fix?

**Comment by lakchote** [comment] 2024-10-28 08:24
@adelekennedy no payment is due here as it was a regression caused by @wildan-m's PR in https://github.com/Expensify/App/issues/48715.

**Comment by adelekennedy** [comment] 2024-10-28 15:34
sorry about that! Then I think we are good to close this one?

**Closed** 2024-10-28 15:35 UTC
Labels: Engineering, Daily, Awaiting Payment
