### ISSUE TITLE
[$500] Distance: "Add a Stop" Functionality Overwrites "Finish" Location

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#27073] opened 2023-09-08 21:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Click on + > request money > distance
 (Eg: I want to go from Dallas to Houston but stop at Austin for 2 hours)
2 On start, choose start location (Eg Dallas)
3 On Finish, choose finish location (Eg Houston)
4 Click on Add a stop button
5 Verify that location on Finish is transferred to stop while my intention was to add another location (Eg Austin) as stop
## Expected Result:
 Clicking on "Add a Stop" should open a separate input field for specifying a stop location, allowing users to enter a different location without affecting the "Finish" location.
Actual Result: 
## Actual Result:
The location entered in the "Finish" field is automatically copied to the "Stop" field,
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/7b519a18-2435-4cf5-baaa-97e7c3e6e49b

https://github.com/Expensify/App/assets/38435837/43069f5f-3081-442b-b601-bd83b0b313eb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693877482555529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b3c43bd61f16cc5</li>
        <li>Upwork Job ID: 1700264309195997184</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-08 21:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

[Distance]: The finish address move to the stop waypoint when adding the stop
 
### What is the root cause of that problem?

https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/libs/actions/Transaction.js#L52-L57

Currently, in the beginning, waypoint1 will be the start point, waypoint2 will be the finish point. When creating a new stop point, start and finish point will remain. The stop point will be waypoint3.

https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/components/DistanceRequest.js#L187-L196

But while displaying, the finish point is the last point (in this context, last point is waypoint3). It caused this bug

### What changes do you think we should make in order to solve the problem?

When adding a new stop point we should change the index of the finish point to the last point. In this context, when adding new stop point, this stop point will be waypoint2 and the finish point will move to waypoint3.

https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/libs/actions/Transaction.js#L52-L57
```
[`waypoint${newLastIndex-1}`]: null,
[`waypoint${newLastIndex}`]: lodashGet(existingWaypoints, `waypoint${newLastIndex-1}`, {})
```
### Result

https://github.com/Expensify/App/assets/141406735/fa9f16c1-3996-4f78-b1b9-bd4eb8627f75

### What alternative solutions did you explore? (Optional)
 
In case, we want to remain the finish point always be waypoint 2.

https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/components/DistanceRequest.js#L187-L196

we can update here to display the finish point when index is 1

With this approach, the stop point will display below the finish point

<img width=“987” alt=“Screenshot 2023-09-05 at 12 04 20" src=“[https://github.com/Expensify/App/assets/141406735/34e5cc57-f28b-4bb6-9acf-52c1cd5af3be”](https://github.com/Expensify/App/assets/141406735/34e5cc57-f28b-4bb6-9acf-52c1cd5af3be%E2%80%9D)>

**Comment by RaheesAhmed** [comment] 2023-09-08 22:19
# Proposal for Distance: "Add a Stop" Functionality Overwrites "Finish" Location #27073


## Problem Statement
When a user clicks on "Add a Stop," the location entered in the "Finish" field is automatically copied to the "Stop" field. The expected behavior is that clicking on "Add a Stop" should open a separate input field for specifying a stop location, allowing users to enter a different location without affecting the "Finish" location.

## Root Cause
The root cause appears to be in the way the waypoints are managed in the code. Specifically, the code uses an index-based system to determine which waypoint is the start, finish, or a stop. When a new stop is added, it becomes the last waypoint, causing the finish point to shift.

## Proposed Solution 1: Update Finish Point Index

### Code Changes
In `Transaction.js`, modify the existing code block:

```javascript
Onyx.merge(`${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, { 
    comment: { 
        waypoints: { 
            [`waypoint${newLastIndex}`]: {}, 
        }, 
    }, 
});
```
to:

```
Onyx.merge(`${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, { 
    comment: { 
        waypoints: { 
            [`waypoint${newLastIndex-1}`]: null,
            [`waypoint${newLastIndex}`]: lodashGet(existingWaypoints, `waypoint${newLastIndex-1}`, {})
        }, 
    }, 
});

```
This ensures that the finish point's index is updated to be the last index, and the new stop takes the second last index.

###  Alternative Solution 2: Update Display Logic

Code Changes
In `DistanceRequest.js`, modify the existing code block:

```
if (index === 0) { 
    descriptionKey += 'start'; 
    waypointIcon = Expensicons.DotIndicatorUnfilled; 
} else if (index === lastWaypointIndex) { 
    descriptionKey += 'finish'; 
    waypointIcon = Expensicons.Location; 
} else { 
    descriptionKey += 'stop'; 
    waypointIcon = Expensicons.DotIndicator; 
}

```
to:

```
if (index === 0) { 
    descriptionKey += 'start'; 
    waypointIcon = Expensicons.DotIndicatorUnfilled; 
} else if (index === 1) { 
    descriptionKey += 'finish'; 
    waypointIcon = Expensicons.Location; 
} else { 
    descriptionKey += 'stop'; 
    waypointIcon = Expensicons.DotIndicator; 
}

```

This ensures that the finish point is always displayed when the index is 1, regardless of how many stops are added.

### Conclusion
Both solutions aim to resolve the issue of the "Add a Stop" functionality overwriting the "Finish" location.

**Comment by jeet-dhandha** [comment] 2023-09-09 03:17
@m-natarajan Please change the "Reported by" to me as i reported this first.

https://expensify.slack.com/archives/C049HHMV9SM/p1692939840341009

**Comment by jeet-dhandha** [comment] 2023-09-09 03:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- When you add a stop waypoint to a route, the 'Finish Waypoint' becomes the 'Stop' waypoint

### What is the root cause of that problem?
- The main reason for this problem is that when you add a stop waypoint, a new empty index is generated. As a result, this new waypoint, which is the last one in the list, is mistakenly shown as both the 'Finish Waypoint'.

### What changes do you think we should make in order to solve the problem?
- To resolve this we can create a function to handle the changes in the index of the waypoints.
```js
function generateStopWaypoint(waypoints) {
    const finishIndex = _.size(waypoints);
    const prevFinishIndex = finishIndex - 1;
    const newStopIndex = finishIndex - 1;

    const finish = lodashGet(waypoints, `waypoint${prevFinishIndex}`, null);

    return {
        [`waypoint${newStopIndex}`]: null,
        [`waypoint${finishIndex}`]: finish,
    };
}
```

- Then calling it in `addStop` function
```
function addStop(transactionID) {
    ...rest
    comment: {
        waypoints: generateStopWaypoint(existingWaypoints),
    },
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by laurenreidexpensify** [comment] 2023-09-12 10:26
@burczu bump for review on these proposals thanks

**Comment by burczu** [comment] 2023-09-12 10:50
@laurenreidexpensify I'll review it soon - I was ooo due to RNEU conference and now I'm kinda flooded by issues.

**Comment by burczu** [comment] 2023-09-12 11:10
Ok, proposals reviewed - all of them looks quite the same but @DylanDylann ([link](https://github.com/Expensify/App/issues/27073#issuecomment-1712259338)) was first and I think we should choose it because this solution looks correct (main one - the optional one seem to not working).

🎀 👀 🎀 C+ reviewed

**Comment by flodnv** [comment] 2023-09-13 03:35
@neil-marcellini looks like this is related to distance requests, so assigning to you

**Comment by DylanDylann** [comment] 2023-09-15 04:57
@neil-marcellini @burczu This is the [latest discussion](https://github.com/Expensify/App/issues/26888#issuecomment-1720655160) we still want to display the stop waypoint between the start point and finish point. So this issue should be fixed

**Comment by laurenreidexpensify** [comment] 2023-09-18 09:20
@neil-marcellini bump

**Comment by neil-marcellini** [comment] 2023-09-21 03:01
Sorry for the delay. This is going to be fixed by https://github.com/Expensify/App/issues/26888 so I think we should close it. I don't think we need to pay for the bug report because we were already aware of the behavior and it was the intended behavior before we decided to change the UX.

**Closed by neil-marcellini** 2023-09-21 03:01 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
