### ISSUE TITLE
[HOLD for payment 2023-10-02] [$1000] Split Bill - After splitting money, clicking on IOU detail takes the user to the Concierge chat.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22964] opened 2023-07-16 10:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Website
2. Split bill.
3. Click on You preview.

## Expected Result:
 It should navigates user to you detail page.

## Actual Result:
After splitting money, clicking on IOU detail takes the user to the Concierge chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-1
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8fbf82ef-bee1-4294-a27a-45d87fc9e65d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ad-eeb
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689369192363999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fccec540368136b1</li>
        <li>Upwork Job ID: 1681722206099353600</li>
        2023-07-19<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li> |  | 0</li>
</ul></li>
    </ul>
</details>

**Comment by daordonez11** [comment] 2023-07-17 23:03
Was analyzing to give a proposal but this is a regression of https://github.com/Expensify/App/pull/22787, which should be fixed as part of the original PR.

PS real steps, you need to get the issue of: There is a previously existing chat between these users, json code 666 in the command SplitBillAndOpenReport. 

Expected behavior: should show the optimistic report or hmmm not here page.

cc @allroundexperts  @wildan-m

**Comment by wildan-m** [comment] 2023-07-17 23:24
@daordonez11 @allroundexperts thanks for the report, checking...

**Comment by muttmuure** [comment] 2023-07-19 17:47
Reproduced, although I've just spotted that this is a regression so will double check if it should get a bounty

**Comment by robertKozik** [comment] 2023-07-21 17:51
@muttmuure could you assign this issue to @allroundexperts as he is responsible for checking the PR for this regression?

**Comment by muttmuure** [comment] 2023-07-26 06:57
Not overdue

**Comment by muttmuure** [comment] 2023-08-01 14:42
Bumped @allroundexperts in Slack

**Comment by muttmuure** [comment] 2023-08-01 15:11
being worked on over here: https://github.com/Expensify/App/issues/21518#issuecomment-1659525004

**Comment by muttmuure** [comment] 2023-08-09 20:45
Being discussed as an internal issue: https://github.com/Expensify/App/issues/21518#issuecomment-1670066169

**Comment by luacmartins** [comment] 2023-09-12 01:44
Assigning myself since [this PR](https://github.com/Expensify/App/pull/24407) might fix this issue.

**Comment by muttmuure** [comment] 2023-10-03 15:29
Looks like we don't think the other [issue is a regression](https://github.com/Expensify/App/issues/28522#issuecomment-1743763890) but I am going to keep an eye on it

**Comment by muttmuure** [comment] 2023-10-06 12:28
Ah, OK I miscalculated the dates and this can be paid out

**Comment by muttmuure** [comment] 2023-10-06 12:36
Is this really linked to a deploy blocker? @luacmartins, @allroundexperts  do you know?

**Comment by luacmartins** [comment] 2023-10-06 16:44
AFAIK this was a regression of https://github.com/Expensify/App/pull/22787 (within the regression period) and fixed in https://github.com/Expensify/App/pull/24407

**Comment by muttmuure** [comment] 2023-10-10 07:34
Clarifying here: https://expensify.slack.com/archives/C01SKUP7QR0/p1696923274741239

**Comment by muttmuure** [comment] 2023-10-10 13:55
You should be compensated

**Comment by luacmartins** [comment] 2023-10-13 18:45
Just pending payment

**Comment by luacmartins** [comment] 2023-10-16 17:07
Same as above. Still waiting on payment.

**Comment by muttmuure** [comment] 2023-10-19 18:34
invite sent

**Comment by muttmuure** [comment] 2023-10-20 09:42
Offer sent

**Comment by muttmuure** [comment] 2023-10-20 17:09
Paid

**Closed by muttmuure** 2023-10-20 17:09 UTC
Labels: External, Engineering, Daily, Needs Reproduction, Awaiting Payment, Bug
