### ISSUE TITLE
Update formatting for "info" box when it includes bullet points

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#42852] opened 2024-05-30 17:45 UTC
### Problem
When bullet points are included in an "information" text box, the `i` overlaps with one of the bullet points
<img width="795" alt="image" src="https://github.com/Expensify/App/assets/38016013/5b9e1c3b-2858-4a12-b87d-9e02a2f67a1a">
<img width="749" alt="image" src="https://github.com/Expensify/App/assets/38016013/f6750a7a-b0fd-4573-b557-2d2ad9d48eee">

### Solution
Update the formatting of that markdown so the `i` doesn't overlap with the bullet point

### Additional info
this is for sure happening on these two resources, but could be happening elsewhere:
- [Xero](https://github.com/Expensify/App/blob/main/docs/articles/new-expensify/connections/Set-up-Xero-connection.md)
- [Upgrade to new EC](https://github.com/Expensify/App/blob/main/docs/articles/new-expensify/expensify-card/Upgrade-to-the-new-Expensify-Card-from-Visa.md)

**Comment by rushatgabhane** [comment] 2024-06-10 18:44
duplicate of https://github.com/Expensify/App/issues/43044

**Comment by rushatgabhane** [comment] 2024-06-16 12:27
We can close this issue - Being tracked here - https://github.com/Expensify/App/issues/43044

And a PR has been raised

**Comment by francoisl** [comment] 2024-07-08 19:17
Closing as requested in https://expensify.slack.com/archives/C02NK2DQWUX/p1720465739511849

**Closed by francoisl** 2024-07-08 19:17 UTC
Labels: Weekly, Improvement
