### ISSUE TITLE
[HOLD for Regression Test] [$1000] Emoji button on hover background doesn't have proper padding (background touches the icon border) in the dark theme.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13160] opened 2022-11-29 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat
2. Hover on the emoji button on the composer,
3. Check the grey hover background

## Expected Result: 
Grey hover background should have proper padding

## Actual Result: 
Hover background doesn't have horizontal padding and it touches the icon.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.33-2
**Reproducible in staging?:** y
**Reproducible in production?:** new UI
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="960" alt="6" src="https://user-images.githubusercontent.com/43996225/204642522-38f70ac5-9f7d-49d1-b85d-3b1d736602b2.png">
<img width="201" alt="Screenshot 2022-11-29 at 5 17 36 PM" src="https://user-images.githubusercontent.com/43996225/204642544-232426f4-d8be-475c-8a64-98d5a80e0d46.png">
<img width="283" alt="Screenshot 2022-11-29 at 5 17 43 PM" src="https://user-images.githubusercontent.com/43996225/204642546-b9161dd8-071b-41c8-8f45-5eb3e3f42d52.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mananjadhav 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669722656145379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~0116174b9a06c6ad84
- Upwork Job ID: 1598772700294258688

**Comment by Puneet-here** [comment] 2022-11-29 20:41
### Proposal

Remove margin: 3
https://github.com/Expensify/App/blob/58c22bc44dc183e55c57c6a332a8790d46277840/src/styles/styles.js#L1503
instead pass 
```js
marginVertical: 3,
paddingHorizontal: 3,
```

**Comment by Pujan92** [comment] 2022-11-30 02:23
**Proposal**

Update the below style changes to highlight only the emoji icon.
https://github.com/Expensify/App/blob/58c22bc44dc183e55c57c6a332a8790d46277840/src/styles/styles.js#L1499-L1505

```
chatItemEmojiButton: {
      alignSelf: 'center',
      borderRadius: '50%',
      margin: 3,
},
```
<img width="1062" alt="Screenshot 2022-11-30 at 7 49 59 AM" src="https://user-images.githubusercontent.com/14358475/204692079-6bc6df34-39c2-4e5a-a24a-abe756a70ce4.png">

**Comment by mananjadhav** [comment] 2022-11-30 03:19
I reported this bug and it still needs to be triaged.

@Pujan92 I don't think we should be removing the hover background. This is added for all the icons I suppose.

Tagging @Expensify/design  as well.

**Comment by Pujan92** [comment] 2022-11-30 05:55
Ok, In that case I think the below properties work well.

```
    chatItemEmojiButton: {
        alignSelf: 'center',
        justifyContent: 'center',
        padding: 5,
        borderRadius: 6,
    },
```

<img width="1040" alt="Screenshot 2022-11-30 at 11 24 15 AM" src="https://user-images.githubusercontent.com/14358475/204718636-e6c71aed-aa40-4f8d-b72a-0d077a09948d.png">

**Comment by Puneet-here** [comment] 2022-11-30 16:07
@shawnborton, is this expected?
<img width="582" alt="Screenshot 2022-11-30 at 9 37 10 PM" src="https://user-images.githubusercontent.com/101883770/204848814-4174240f-8b17-4780-a9fa-efb395214c96.png">

**Comment by shawnborton** [comment] 2022-11-30 16:09
Ah apologies, once [this one](https://github.com/Expensify/App/pull/12965) is merged then let's test again

**Comment by mananjadhav** [comment] 2022-12-02 18:09
@shawnborton do you want to fix this one as a part of that PR? I reviewed the PR and I can confirm it is not fixed in that PR.?

<img width="366" alt="image" src="https://user-images.githubusercontent.com/3069065/205358073-1695864e-fc42-435c-84f2-ab42ab1165fc.png">

**Comment by shawnborton** [comment] 2022-12-02 19:53
Hmm I think that PR is about to be merged, so I'll let @grgia decide: either we can make a quick follow up issue, or we could squeeze this change into that PR before it gets merged.

**Comment by Puneet-here** [comment] 2022-12-02 20:00
Hey @shawnborton, we already have this issue for emoji button and I also have a [proposal](https://github.com/Expensify/App/issues/13160#issuecomment-1331273466).

Here's the result
<img width="582" alt="Screenshot 2022-11-30 at 9 37 10 PM" src="https://user-images.githubusercontent.com/101883770/204848814-4174240f-8b17-4780-a9fa-efb395214c96.png">

**Comment by shawnborton** [comment] 2022-12-02 20:02
Okay cool, that also works for me. cc @greg-schroeder so we can hire @Puneet-here for this one

**Comment by grgia** [comment] 2022-12-02 20:14
I'll go ahead and move this forward and assign @Puneet-here 

Just a heads up for the future,

Per the [Contribution Guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md)
"Issues that have not had the External label applied have not yet been approved for implementation. This means, if you propose a solution to an issue without the External label (which you are allowed to do) it is possible that the issue will be fixed internally. If the External label has not yet been applied, Expensify has the right to use your proposal to fix said issue, without providing compensation for your solution. This process covers the very rare instance where we need or want to fix an issue internally."

**Comment by Puneet-here** [comment] 2022-12-02 20:50
@grgia, PR is ready, thanks!

**Comment by shawnborton** [comment] 2022-12-13 18:36
This one has been merged!

**Comment by mallenexpensify** [comment] 2022-12-24 01:21
I think everyone's hired - @rushatgabhane , @Puneet-here , @mananjadhav Can y'all please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0116174b9a06c6ad84

**Comment by mananjadhav** [comment] 2022-12-24 02:50
Accepted @mallenexpensify

**Comment by mallenexpensify** [comment] 2022-12-26 23:18
All paid, bonus of 50% added for @rushatgabhane and @Puneet-here 
Hired Dec 2 
Merged Dec 6

Leaving open for the regression test steps, @grgia , can you check the above when you're back https://github.com/Expensify/App/issues/13160#issuecomment-1349848107

I'll try to do the BZ part before next week.

**Comment by grgia** [comment] 2022-12-28 20:58
Playing catch up, I'll get this steps done now

**Comment by grgia** [comment] 2022-12-28 22:11
After looking at blame, I don't think this was as much of a bug as a style improvement. I'm going to check off the checklist for now accordingly, but let's still add a regression test!

**Comment by JmillsExpensify** [comment] 2023-01-06 20:12
@greg-schroeder Can we get a regression test on this one? It's going on three weeks, so it'd be great to get that step crossed off. Let's close this issue out.

**Comment by JmillsExpensify** [comment] 2023-01-11 04:51
@greg-schroeder Do you need help getting the regression test done on this one? I'm also going to reach out to you via DM to make sure you don't have something wonky going on with notifications.

**Comment by mallenexpensify** [comment] 2023-01-19 02:25
@greg-schroeder , guessing you didn't see this cuz the `Reviewing` label was applied and it wasn't going/showing as overdue.  Check here for instructions for the regression test steps https://stackoverflow.com/c/expensify/questions/14574

**Comment by greg-schroeder** [comment] 2023-01-19 22:48
Okay working on regression steps today

**Comment by shawnborton** [comment] 2023-01-23 14:24
Not overdue

**Comment by greg-schroeder** [comment] 2023-01-24 04:02
Finishing this tonight

**Comment by grgia** [comment] 2023-01-27 20:40
Not overdue

**Comment by shawnborton** [comment] 2023-01-30 09:22
Not overdue

**Comment by greg-schroeder** [comment] 2023-01-30 12:37
Posted in slack re: regression here: https://expensify.slack.com/archives/C01SKUP7QR0/p1675082181227879

**Comment by greg-schroeder** [comment] 2023-01-30 18:19
Per slack, uniform padding/spacing covered by design guidelines: https://expensify.slack.com/archives/C01SKUP7QR0/p1675088862292759?thread_ts=1675082181.227879&cid=C01SKUP7QR0

**Closed by greg-schroeder** 2023-01-30 18:19 UTC
Labels: External, Daily, Bug
