### ISSUE TITLE
[PAID] [$250] Composer - Console error shows up when pasting the same text in the composer

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51466] opened 2024-10-25 12:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh2010001@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Type anything in the composer.
3. Highlight all the content.
4. Copy the content.
5. While the content is still highlighted, paste the same content.

## Expected Result:
No console error will show up.

## Actual Result:
Console error shows up when pasting the same text in the composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2951a5a3-55b3-4621-ad05-a41e6e42d001

[Bug6645374_1729849788357!staging.new.expensify.com-1729840230855.txt](https://github.com/user-attachments/files/17522348/Bug6645374_1729849788357.staging.new.expensify.com-1729840230855.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851405996383084182</li>
        <li>Upwork Job ID: 1851405996383084182</li>
        <li>Last Price Increase: 2024-10-29</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 104665940</li>
<li>nkdengineer | Contributor | 104665943</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by strepanier03** [comment] 2024-10-29 23:28
Reproduced without issue, 
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/6b07f80c-9228-4ed9-b059-c290fa351f13">

Figuring out project now.

**Comment by strepanier03** [comment] 2024-10-29 23:28
> cursorUtils.js:24 Uncaught IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 62 is larger than the node's length (0).
>     at A (cursorUtils.js:24:11)
>     at MarkdownTextInput.web.js:366:9
>     at Object.Te (react-dom.production.min.js:54:317)
>     at $e (react-dom.production.min.js:54:471)
>     at react-dom.production.min.js:55:35
>     at Fr (react-dom.production.min.js:105:68)
>     at Lr (react-dom.production.min.js:106:380)
>     at react-dom.production.min.js:117:104
>     at ll (react-dom.production.min.js:273:42)
>     at De (react-dom.production.min.js:52:375)

**Comment by nkdengineer** [comment] 2024-10-30 04:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error shows up when pasting the same text in the composer

### What is the root cause of that problem?
The problem is `inputType` can be `undefined` and in the case the current text and the past text is the same we go to this logic and the error appears because we use `includes` function with `undefined` value.

https://github.com/Expensify/react-native-live-markdown/blob/4e4f13d744dc05685c7a0907a086e5f9616906e2/src/web/utils/inputUtils.ts#L107


### What changes do you think we should make in order to solve the problem?
It's a bad type declear here since `inputType` can be `undefined`, we should change this to

```
interface MarkdownNativeEvent extends Event {
  inputType?: string;
}
```

https://github.com/Expensify/react-native-live-markdown/blob/4e4f13d744dc05685c7a0907a086e5f9616906e2/src/MarkdownTextInput.web.tsx#L39-L41

Then change the `inputType` to optional here

https://github.com/Expensify/react-native-live-markdown/blob/4e4f13d744dc05685c7a0907a086e5f9616906e2/src/web/utils/inputUtils.ts#L40

And add the safe check here

```
if (text === target.value && inputType?.includes('delete')) {
```

https://github.com/Expensify/react-native-live-markdown/blob/4e4f13d744dc05685c7a0907a086e5f9616906e2/src/web/utils/inputUtils.ts#L107

With this change, we can make sure there's not the same case can happen in the feature when we get the input type from `nativeEvent`

### What alternative solutions did you explore? (Optional)
NA

**Comment by jjcoffee** [comment] 2024-10-30 15:42
Two pretty similar proposals here, but @nkdengineer's [proposal](https://github.com/Expensify/App/issues/51466#issuecomment-2445832316) includes the important extra detail of fixing up `inputType`'s type declaration so I think we're going to go with theirs.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by nkdengineer** [comment] 2024-10-31 03:38
@jjcoffee this [PR](https://github.com/Expensify/react-native-live-markdown/pull/531) is ready for review

**Comment by tomekzaw** [comment] 2024-10-31 08:15
cc @Skalakid and @BartoszGrajdek

**Comment by tomekzaw** [comment] 2024-11-04 10:39
FYI https://github.com/Expensify/react-native-live-markdown/pull/531 has been merged and released in 0.1.180.

**Comment by jjcoffee** [comment] 2024-11-04 11:12
@nkdengineer Can you raise the App PR when you get a chance? :pray:

**Comment by nkdengineer** [comment] 2024-11-04 11:13
Will open the App PR tomorrow.

**Comment by jjcoffee** [comment] 2024-11-19 15:52
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by strepanier03** [comment] 2024-11-21 02:08
I've made the reg test, paid and closed both contracts and updated the title. 

Thanks again, everyone.

**Closed by strepanier03** 2024-11-21 02:08 UTC
Labels: External, Daily, Awaiting Payment, Bug
