### ISSUE TITLE
[Awaiting payment][$250] Action bar is missing in non-expanded mode for video attachments

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40652] opened 2024-04-20 23:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rojiphil 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713117417463329

## Action Performed:
1. Send a video attachment
2. Hover over the attachment preview in the report.
## Expected Result: 
The action bar must be displayed on hover within the video attachment preview
## Actual Result:
 The action bar is not displayed on hover within the video attachment preview

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
<img width="1440" alt="Screenshot 2024-04-20 at 7 41 12 PM" src="https://github.com/Expensify/App/assets/38435837/afbe1fb2-1a17-43cd-8b71-b398fe94d4ba">

https://github.com/Expensify/App/assets/38435837/4c5ad17c-c4a4-44c2-9887-71143a532a68

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e881973f1d097fbb</li>
        <li>Upwork Job ID: 1782953700596039680</li>
        <li>Last Price Increase: 2024-04-24</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by ikevin127** [comment] 2024-04-21 08:55
We were also discussing this first in:
- https://github.com/Expensify/App/issues/39598

Some discoveries regarding the bug:
- I can reproduce with the following steps:

1.Send a video attachment.
2.Play the video so that the preview is visible.
3.Hover over the attachment preview in the report.

Now the video does play, it doesn't freeze anymore on Safari but this is what's happening with regards to video controls not showing:
- when I manually resize the safari browser window vertically (making it less taller), after a certain height point the video controls do show up normally (as expected on hover), but resizing it back to fullscreen makes the controls not show up, again.


The bug is also discussed in this [Slack 🧵](https://expensify.slack.com/archives/C049HHMV9SM/p1713117417463329), I will also post my discoveries there.

> [!note]
> It does look like there might be something on our side, either some overlaying issue which causes the video controls to not be shown in Safari, or maybe even something new arch related (if this worked as expected in Safari before new arch merge).

**Comment by trjExpensify** [comment] 2024-04-23 01:12
Should we close this in favour of https://github.com/Expensify/App/issues/39598?

**Comment by ikevin127** [comment] 2024-04-23 02:02
@trjExpensify I think we should treat them separately!

**Reasoning:**
- this one is a **Safari** specific bug, it doesn't happen on any other WebKit engine based browsers on MacOS - I spent a few hours trying to figure out the root cause and I still have nothing as to why it's happening

- https://github.com/Expensify/App/issues/39598 is related to bad logic within the `BaseVideoPlayer` component, specifically the `VideoPopoverMenu`'s portal logic conflicting with the `Hoverable`'s component logic, as detailed in my [proposal](https://github.com/Expensify/App/issues/39598#issuecomment-2041187706)

Regarding this issue and why I think it should stay separated from the other one is because this one is definitely harder to debug compared to the other one for which there are 2 proposals already and for which we know the root cause.

Trying to solve both issues within https://github.com/Expensify/App/issues/39598 might significantly delay the completion of https://github.com/Expensify/App/issues/39598 issue since for this one we already have proposals ready to fix it whereas for  #40652 we don't have anything.

**Comment by rojiphil** [comment] 2024-04-23 02:59
> If [@rojiphil](https://github.com/rojiphil) cannot reproduce this one

@ikevin As mentioned [here](https://github.com/Expensify/App/issues/39598#issuecomment-2054137578), I could reproduce the flickering problem on Chrome. So reproducing the flickering problem is not the issue anymore. However, we did have a problem with reproduction of the issue of missing action bar on Safari which you were able to reproduce. Thanks for confirming on this.

**Comment by trjExpensify** [comment] 2024-04-24 02:04
Okay, moving it forward!

**Comment by mountiny** [comment] 2024-04-24 14:17
Adding @rojiphil as a C+ here as they have context from the linked issue

**Comment by ikevin127** [comment] 2024-04-24 19:14
Based on @rojiphil's https://github.com/Expensify/App/issues/39598#issuecomment-2073083790, it seems appropriate that @Skalakid could handle this issue given their original involvement with the `zIndex: 9000` code as this suggests a better understanding of the context based on https://github.com/Expensify/App/issues/39598#issuecomment-2074303236 where the `zIndex: 9000` code might have been implemented to address another edge case and removing this code without careful consideration could potentially lead to a regression.

If they don't have capacity to address this issue, I could write-up a formal proposal. Please let us know!

**Comment by Skalakid** [comment] 2024-04-25 14:11
Hi, I was investigating this issue today, and removing `zIndex: 9000` doesn't help on Safari browsers. The action bar is still hidden under the video component. Adding `WebkitTransform: 'translate3d(0, 0, 0)'` seems to fix the issue, however I will try to find other way for fixing it

**Comment by trjExpensify** [comment] 2024-04-27 12:41
What are the next steps here? Does anyone have a formal proposal for @rojiphil to review?

**Comment by rojiphil** [comment] 2024-04-27 13:05
> What are the next steps here? Does anyone have a formal proposal for @rojiphil to review?

@trjExpensify  No formal proposals are required here as @Skalakid is resolving this issue. Awaiting PR.

**Comment by mvtglobally** [comment] 2024-05-01 14:03
Issue not reproducible during KI retests. (First week)

**Comment by rojiphil** [comment] 2024-05-22 18:15
Looks like automation didn't work here. 
The PR has already been in production since 07 May  as mentioned [here](https://github.com/Expensify/App/pull/41218#issuecomment-2097207024)
This is pending payment for me as a C+ reviewer cc @trjExpensify

**Comment by trjExpensify** [comment] 2024-05-22 22:52
Payment summary as follows: 

- $250 to @rojiphil for the fix

Paid!

**Closed by trjExpensify** 2024-05-22 22:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
