### ISSUE TITLE
[HOLD for payment 2023-06-29]  Selecting/removing one user selects/removes all the user on split bill group page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21075] opened 2023-06-19 19:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Create a new group with multiple new users that you have not chatted before
3. Click on + in the group and select split bill
4. Enter amount and click on save/continue
5. On the split money page, notice there are multiple users in green checkmark selected.
6. Select the first user and notice all the other users are removed
7. Again, select any user and notice all the users are selected

## Expected Result:
Selecting/removing one user  should not selects/remove all the user on split bill group page

## Actual Result:
Selecting/removing one user selects/removes all the user on split bill group page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f94f1ad4-5253-40bb-bd4b-e88d6a95590b

https://github.com/Expensify/App/assets/93399543/fba375a5-8caf-4087-82c1-3901d4b8de87

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686991867243109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2023-06-20 02:06
Reproduced: 
<img width="374" alt="image" src="https://github.com/Expensify/App/assets/87341702/fae25d64-d332-473e-b1e0-69d14b7f2f6a">

**Comment by aldo-expensify** [comment] 2023-06-20 02:22
The `selectedParticipants` here:

https://github.com/Expensify/App/blob/a1611f9ec8f070faaf705ccc1579e2499f3beabc/src/components/MoneyRequestConfirmationList.js#L153

are missing the `login`:

<img width="545" alt="image" src="https://github.com/Expensify/App/assets/87341702/3fa083fb-6cc9-41f4-8fce-5e00b7011ce8">


@Beamanator do you know if that is expected? I see that the `text` contains the email. These accounts did not exist when I created the group with them.

**Comment by aldo-expensify** [comment] 2023-06-20 02:41
it seems like in Onyx `personalDetails` we have two entries for the accounts created with the group, for example:

<img width="634" alt="image" src="https://github.com/Expensify/App/assets/87341702/54fd71fa-e1dd-4c52-b033-ad8e123c6489">

The account appears under a real ID (11033541), missing the `login` key, and under a front end generated ID (4331464817836459) which does have the `login` information.

Debugging, I see that the participant is passed around with the real ID 11033541, so when we look in `personalDetails` for the login information, it is just not there.

**Comment by Beamanator** [comment] 2023-06-20 11:43
When I created a group w/ a user that didn't exist yet, I saw `__fake__` in the LHN (mentioned in linked issue ^). I also noticed I see this in Onyx:

<img width="797" alt="Screenshot 2023-06-20 at 2 43 03 PM" src="https://github.com/Expensify/App/assets/3885503/e53f36a6-9629-499e-9932-c449346ba6ef">

**Comment by Beamanator** [comment] 2023-06-20 11:44
And this too, due to optimistic accountIDs:

<img width="607" alt="Screenshot 2023-06-20 at 2 44 42 PM" src="https://github.com/Expensify/App/assets/3885503/525af047-2e71-4312-8eac-0d2acb9385ea">

**Comment by Beamanator** [comment] 2023-06-20 11:46
Which also leads to `Hidden` showing in the report participants page (I know this has been reported elsewhere, i just want to add for complete investigation):

<img width="378" alt="Screenshot 2023-06-20 at 2 45 22 PM" src="https://github.com/Expensify/App/assets/3885503/0c7e10ba-7205-4e6d-93b9-da341938ff33">

**Comment by Beamanator** [comment] 2023-06-20 12:49
PR up for this: https://github.com/Expensify/App/pull/21113

**Comment by aldo-expensify** [comment] 2023-07-01 00:19
@zanyrenney I think this just needs payment handling.

@s77rt reviewed the PR https://github.com/Expensify/App/pull/21113 which was fixing this deploy blocker

**Comment by aldo-expensify** [comment] 2023-07-01 01:03
I'll be out of office next week, I don't think you need any action from me 👋

**Comment by zanyrenney** [comment] 2023-07-03 10:14
Going to chat to @Beamanator to understand the latest here!

**Comment by zanyrenney** [comment] 2023-07-05 11:14
Hi there! After discussing internally, seeing as technically @s77rt s77rt & @narefyev91 both helped test & review that PR and you are both C+ we will be paying out $500 to each of you for your contributions as:

- s77rt tested, but not on all platforms and left some good reviews
- narefyev91 tested on all platforms but didn't really review as fully

**Comment by zanyrenney** [comment] 2023-07-05 14:23
Payment on upwork sent for reporting bonus and C+ work from @s77rt . Closing this one out!

**Closed by zanyrenney** 2023-07-05 14:23 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
