### ISSUE TITLE
[C+ Checklist Needs Completion] [$1000] DEV:Takes time to change topbar(manual to scan, scan to manual) selection in request money

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25428] opened 2023-08-17 19:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. click "+" button
2. select request money
3. try to slide right to left
## Expected Result: 
selection change should be immediately
## Actual Result: 
selection change takes some time

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e06b81a2-2165-4a53-a742-80a0555108f2

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691384151135339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c514d8b4722d88a</li>
        <li>Upwork Job ID: 1692452963606020096</li>
        <li>Last Price Increase: 2023-08-18</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-08-18 08:27
I can't repro DEV issues - I'm assuming since you made a proposal here @allroundexperts that you were able to?

**Comment by studentofcoding** [comment] 2023-08-18 10:05
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
Tab change animations are delayed when the screen is swiped when on MoneyRequestPage.

## What is the root cause of that problem?
The root cause of this problem is that by default, React Navigation lazy loads tab screens, which means that the screens are only rendered when accessed for the first time. This can cause a delay in rendering the new tab screen when swiping.

When the screen is swiped, the new tab screen needs to be rendered immediately to provide a smooth transition. However, because of lazy loading, there is a delay in rendering the new tab screen, resulting in delayed animation.

## What changes do you think we should make to solve the problem?
What we need to do is simply disable lazy loading by setting the `lazy` prop of the OnyxTabNavigator component to `false`. This ensures that all tab screens are rendered upfront, eliminating the delay in the tab change animation.
```
<OnyxTabNavigator
                                    lazy={false} // Add this line
                                    id={CONST.TAB.RECEIPT_TAB_ID}
                                    tabBar={({state, navigation}) => (
                                        <TabSelector
                                            state={state}
                                            navigation={navigation}
                                            onTabPress={resetMoneyRequestInfo}
                                        />
                                    )}
                                >
                                    <TopTab.Screen
                                        name={CONST.TAB.MANUAL}
                                        component={NewRequestAmountPage}
                                        initialParams={{reportID, iouType}}
                                    />
                                    {canUseScanReceipts && (
                                        <TopTab.Screen
                                            name={CONST.TAB.SCAN}
                                            component={ReceiptSelector}
                                            initialParams={{reportID, iouType}}
                                        />
                                    )}
                                    {canUseDistanceRequests && (
                                        <TopTab.Screen
                                            name={CONST.TAB.DISTANCE}
                                            component={DistanceRequestPage}
                                        />
                                    )}
                                </OnyxTabNavigator>
```

## What alternative solutions did you explore? (Optional)
None

cc @greg-schroeder

**Comment by shawnborton** [comment] 2023-08-18 12:28
This is not a bug, we can close. cc @AndrewGable

**Comment by shawnborton** [comment] 2023-08-18 13:04
It's really hard to tell because the mouse is moving like crazy in that video. Can we create a new video where the mouse is doing normal gestures?

**Comment by shawnborton** [comment] 2023-08-18 13:17
Cool, thanks for that. Curious for @AndrewGable's thoughts here.

**Comment by carlosalmonte04** [comment] 2023-08-18 17:12
## Proposal
Selection change between tab screens is not immediate due to not using realtime animation of tab active state.

## Please re-state the problem that we are trying to solve in this issue.
Make tabs active state have a faster feedback between screen changes.

## What is the root cause of that problem?
It takes about a second for `react-navigation/material-top-tabs` to update navigation state with the current active tab, this time is reflected in this UI lag.

## What changes do you think we should make in order to solve the problem?
Instead of changing states based on `isSelected` use the `position` property to determine active state.

https://github.com/Expensify/App/assets/25206487/1da37484-001f-433d-99b4-361625bda269

## What alternative solutions did you explore? (Optional)
I consider adding new animations a risk at the moment. [There is an android crash in react native related to animations](https://github.com/facebook/react-native/issues/37267). If it is not urgent, this should wait for that bug to be fixed in react native first, otherwise fixing this could introduce a different bug.

**Comment by greg-schroeder** [comment] 2023-08-19 01:16
going to wait on @AndrewGable's take before I take any action on this one like potentially closing or not

**Comment by greg-schroeder** [comment] 2023-08-21 17:43
bump @AndrewGable

**Comment by AndrewGable** [comment] 2023-08-21 17:46
Yes this is something that can be improved. I agree with it being a bug.

**Comment by burczu** [comment] 2023-08-22 09:51
@studentofcoding I've checked your proposed solution and it does not work...

@allroundexperts and @carlosalmonte04 - could you please be more specific of what exactly should be changed and how? I feel your proposals are similar (using `position` to make animation smooth).

**Comment by burczu** [comment] 2023-08-23 09:21
@carlosalmonte04 thanks for the explanation!

I agree we should choose [the proposal](https://github.com/Expensify/App/issues/25428#issuecomment-1683081653) from @allroundexperts - using the `position` property to change top bar button colors and background should do the trick

🎀 👀 🎀 C+ reviewed

**Comment by shawnborton** [comment] 2023-08-23 12:25
> we need some sort of animation like below

We don't actually need this. Let's just keep what we have by now and change the tab style once the new tab is fully into view.

**Comment by shawnborton** [comment] 2023-08-23 12:34
Okay cool, so let's just make sure the tab highlight changes as soon as the new tab is fully in view. No need to change anything with animation, etc. That's not what this issue is about.

**Comment by burczu** [comment] 2023-08-24 06:30
@allroundexperts I think what @shawnborton mean is to not add this additional animated bottom border etc. that is shown in the example you've posted [here](https://github.com/Expensify/App/issues/25428#issuecomment-1689866731) - I think fixing it with the `position` property to change button styles immediately instead waiting for the whole tab to be loaded is the correct way (please check the screen recording from @carlosalmonte04 [proposal](https://github.com/Expensify/App/issues/25428#issuecomment-1684205294)). Am I right @shawnborton?

**Comment by shawnborton** [comment] 2023-08-24 13:01
That is exactly correct. Let's fix the tab highlighting first before adding any new features like animation.

**Comment by thienlnam** [comment] 2023-08-24 17:24
@burczu Does the proposal from @allroundexperts fix the issue in the way Shawn is intending?

**Comment by thienlnam** [comment] 2023-08-24 17:58
Cool - will assign ya then!

**Comment by burczu** [comment] 2023-08-30 11:47
@thienlnam I've approved this [PR](https://github.com/Expensify/App/pull/26022), but Bot did not assign any internal engineer automatically - could you help with it?

**Comment by burczu** [comment] 2023-08-31 12:55
@allroundexperts - so shouldn't we accept numbers and objects instead of `any`? We will switch to TypeScript soon and I expect that `any` type will be forbidden anyway...

**Comment by burczu** [comment] 2023-08-31 13:03
Alright, let's go with `any` for now - I believe it will change, while doing migration to TS.

**Comment by greg-schroeder** [comment] 2023-09-08 22:35
Processing payments

**Comment by greg-schroeder** [comment] 2023-09-08 23:16
Was this issue merged in time to be eligible for the speed bonus? ❌ 
Were their any regressions? ❌ 

Payment summary:

Reporter: @niravkakadiya25 - $250
Contributor: @allroundexperts - $1000
C+: @burczu - $1000

**Comment by greg-schroeder** [comment] 2023-09-08 23:21
Offer sent to @niravkakadiya25. @allroundexperts you can make a manual request. All that's left is the checklist.

**Comment by JmillsExpensify** [comment] 2023-09-10 10:29
$1,000 payment approved via NewDot based on BZ summary.

**Comment by greg-schroeder** [comment] 2023-09-12 14:17
Bump on the [checklist](https://github.com/Expensify/App/issues/25428#issuecomment-1703425881) @burczu and then we can close this out!

**Comment by burczu** [comment] 2023-09-13 10:51
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu / @allroundexperts] The PR that introduced the bug has been identified. Link to the PR: this is not regression
* [x]  [@burczu / @allroundexperts] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: -
* [x]  [@burczu / @allroundexperts] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: -
* [x]  [@burczu / @allroundexperts] Determine if we should create a regression test for this bug.
* [x]  [@burczu / @allroundexperts] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@greg-schroeder] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Closed** 2023-09-18 10:51 UTC
Labels: Daily, Internal, Needs Reproduction, Overdue, Awaiting Payment, Bug
