### ISSUE TITLE
[HOLD for payment 2024-11-07] Unable to run storybook locally

### ISSUE THREAD

**Issue by chiragsalian** [Expensify/App#51108] opened 2024-10-18 18:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** https://expensify.slack.com/archives/C02NK2DQWUX/p1727459623902909

## Action Performed:
npm run storybook

## Expected Result:
storybook should have opened without any issues

## Actual Result:
Bunch of errors locally
![image](https://github.com/user-attachments/assets/03442d58-110e-49b9-b01f-6a5fb60ee84f)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

cc @ishpaul777 

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by Anaslancer** [comment] 2024-10-19 12:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to run storybook locally

### What is the root cause of that problem?
The “cannot access before initialization” error occurs when you try to use a variable before it has been initialized.

### What changes do you think we should make in order to solve the problem?
We should declare and initialize the variable before we use it.
The solution is to change this [part](https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/__mocks__/%40react-navigation/native/index.ts#L33-L43).
```
let Link, LinkingContext, NavigationContainer, ServerContainer, DarkTheme, DefaultTheme, ThemeProvider, useLinkBuilder, useLinkProps, useLinkTo, useScrollToTop;
Link = realReactNavigation.Link;
LinkingContext = realReactNavigation.LinkingContext;
NavigationContainer = realReactNavigation.NavigationContainer;
ServerContainer = realReactNavigation.ServerContainer;
DarkTheme = realReactNavigation.DarkTheme;
DefaultTheme = realReactNavigation.DefaultTheme;
ThemeProvider = realReactNavigation.ThemeProvider;
useLinkBuilder = realReactNavigation.useLinkBuilder;
useLinkProps = realReactNavigation.useLinkProps;
useLinkTo = realReactNavigation.useLinkTo;
useScrollToTop = realReactNavigation.useScrollToTop;
```


### What alternative solutions did you explore? (Optional)
N/A

### Contributor details
Expensify account email: anasup1995@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aff093c9a804b145

**Comment by Anaslancer** [comment] 2024-10-19 12:45
![Screenshot_4](https://github.com/user-attachments/assets/80c53afe-cab6-49df-8320-7c1b2be06164)

**Comment by Anaslancer** [comment] 2024-10-23 13:18
Thank you, @ishpaul777 
We are using `jest.requireActual` in this file when `isJestEnv` is true.
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/__mocks__/%40react-navigation/native/index.ts#L7
> > jest.requireActual(moduleName)
> Returns the actual module instead of a mock, bypassing all checks on whether the module should receive a mock implementation or not.
So at the moment there is no error, because `realReactNavigation` works like object.
But when `isJestEnv` is false, we are just using the declarations. So we are getting the above error I think.
@ishpaul777 Please let me know your idea. Thanks

**Comment by Anaslancer** [comment] 2024-10-23 14:34
@ishpaul777 I think it's best solution and it's similar like my above proposal.

**Comment by trjExpensify** [comment] 2024-10-24 17:26
Not really sure where to put this, but I guess being dev related we can put it in #quality.

**Comment by chiragsalian** [comment] 2024-10-24 19:58
LGTM, feel free to create the PR @Anaslancer.

**Comment by Anaslancer** [comment] 2024-10-25 16:14
@chiragsalian I can't not create a pull request from my forked repo's branch to the original repo's staging branch. Is it okay to create to the original repo's main branch?

**Comment by chiragsalian** [comment] 2024-10-25 17:37
Not sure i follow. Like yeah you should not create a PR from your repo to be merged to our repo's staging branch. And yes, creating a PR from your repo to be merged to our repo's main branch is the way to go 🙂 
If it helps - all PRs are merged to our main branch. Internal deployers move all the new main code to staging once a day so that QA can test it. Then once its QA's our internal deployers will move all the new staging code to production once a day.

**Comment by Anaslancer** [comment] 2024-10-25 21:47
@chiragsalian I've just created a [pull request](https://github.com/Expensify/App/pull/51502).
BTW, I have a question.
This ticket has not a upwork job link.
I don't have a chance to hire on upwork for this ticket?

**Comment by trjExpensify** [comment] 2024-10-29 02:35
Yep, PR has merged. Once it goes to prod, the 7-day regression period will start. Then payment will be made 👍

**Comment by trjExpensify** [comment] 2024-11-07 20:40
Checklist time!

**Comment by Anaslancer** [comment] 2024-11-09 10:07
@trjExpensify When can we get the offer?

**Comment by trjExpensify** [comment] 2024-11-12 00:27
Payment summary as follows: 

- $250 to @Anaslancer for the fix 
- $250 to @ishpaul777 for the c+ review

@Anaslancer can you link your Upwork profile, please? @ishpaul777, offer sent.

**Comment by Anaslancer** [comment] 2024-11-12 09:57
https://www.upwork.com/freelancers/~01aff093c9a804b145

**Comment by trjExpensify** [comment] 2024-11-12 14:14
Thanks, sent you an offer!

Separately, was this you testing in the #exfy-roadmap public room earlier today? 

<img width="325" alt="image" src="https://github.com/user-attachments/assets/78d2004d-63ea-4095-8e6b-62e9890ef3fe">

**Comment by Anaslancer** [comment] 2024-11-12 14:23
Yes, it was me and deleted all test message.

**Comment by Anaslancer** [comment] 2024-11-12 14:24
There is any way to test on public room?
I am using the staging database.

**Comment by Anaslancer** [comment] 2024-11-12 14:28
Thank you for your offer and accepted :)

**Comment by trjExpensify** [comment] 2024-11-12 14:49
>Thank you for your offer and accepted :)

Paid, @Anaslancer. @ishpaul777 waiting on you to accept your offer now as well.

**Comment by trjExpensify** [comment] 2024-11-15 15:37
@ishpaul777 bump!

**Comment by trjExpensify** [comment] 2024-11-18 12:09
Paid, closing!

**Closed by trjExpensify** 2024-11-18 12:09 UTC
Labels: External, Weekly, Awaiting Payment, Bug
