### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Concierge - User is not landed on Concierge chat via deeplink

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43727] opened 2024-06-13 20:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4630882&group_by=cases:section_id&group_order=asc&group_id=229066
**Email or phone of affected tester (no customers):** gocemate+a2533@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log out of NewDot
2. Navigate to https://staging.new.expensify.com/concierge
3. Sign-up with a new account

## Expected Result:
User should navigate to the concierge chat

## Actual Result:
User is not landed on Concierge chat via deeplink

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/09bfedd5-f5d8-4af5-98f9-2a5a1de57a45

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d4c5cf8f620e9130</li>
        <li>Upwork Job ID: 1801355071704746276</li>
        <li>Last Price Increase: 2024-06-13</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 102733790</li>
<li>bernhardoj | Contributor | 102797658</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by lanitochka17** [comment] 2024-06-13 20:02
@AndrewGable  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-13 20:02
We think that this bug might be related to #vip-vsp

**Comment by AndrewGable** [comment] 2024-06-13 20:11
I wonder if the new onboarding broke this, looking

**Comment by AndrewGable** [comment] 2024-06-13 20:20
Can't reproduce on web

**Comment by AndrewGable** [comment] 2024-06-13 20:29
Reproduced on staging Android


https://github.com/Expensify/App/assets/2838819/4a5061e8-9932-446d-9cc1-5c6088256b8a

**Comment by AndrewGable** [comment] 2024-06-13 20:36
This happens on Android production for me too (using version `1.4.82-4`)


Uploading screen-20240613-143449.mp4…

Going to remove the deploy blocker label, but keep it as a bug

**Comment by rvenky125** [comment] 2024-06-14 05:06
I want to work on this

**Comment by bernhardoj** [comment] 2024-06-14 08:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Concierge from deeplink doesn't open when sign up as a new user.

### What is the root cause of that problem?
When we sign up, an onboarding page shows up. After we complete the onboarding, close the onboarding page and we navigate to HOME (LHN).
https://github.com/Expensify/App/blob/43cd0f7bbb55b455a57f1996a3a11f66573c58d2/src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx#L69
https://github.com/Expensify/App/blob/43cd0f7bbb55b455a57f1996a3a11f66573c58d2/src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx#L71-L74

So the concierge page is actually in the nav stack,
[Home, Concierge, Onboarding]

but because we navigate to home, the LHN is shown instead of the concierge. I believe this happens to every deep link page.

### What changes do you think we should make in order to solve the problem?

If the expected is to show the deeplinked page after the onboarding, then we shouldn't navigate the user to home after completing the onboarding, but instead, just do nothing.
https://github.com/Expensify/App/blob/43cd0f7bbb55b455a57f1996a3a11f66573c58d2/src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx#L73-L79

```
if (!isSmallScreenWidth) {
    if (AccountUtils.isAccountIDOddNumber(accountID ?? 0)) {
        Report.navigateToSystemChat();
    } else {
        Report.navigateToConciergeChat();
    }
}
```

This way, if we have this nav stack,
[Home, Concierge, Onboarding]

and we complete the onboarding, we arrive at the concierge page.
[Home, Concierge]

**Comment by slafortune** [comment] 2024-06-14 11:46
Whoops!  Sorry about that - I was just fixing it!

**Comment by bernhardoj** [comment] 2024-06-17 09:06
I think this one is different because the user uses a deep link to /concierge.

**Comment by bernhardoj** [comment] 2024-06-19 12:21
<img width="895" alt="image" src="https://github.com/Expensify/App/assets/50919443/9a65c699-e4d3-418b-bee1-cb5dce9abd7b">

I mentioned it in the proposal that we already close the onboarding page when completing the process. So, no need to navigate anywhere after closing the onboarding page for a small screen.

**Comment by bernhardoj** [comment] 2024-06-20 04:12
PR is ready

cc: @allgandalf

**Comment by slafortune** [comment] 2024-07-08 18:28
@allgandalf can you please complete the checklist?

**Comment by bernhardoj** [comment] 2024-07-10 12:37
Requested payment in ND.

**Comment by slafortune** [comment] 2024-07-10 16:18
@allgandalf Role C+ - Owed $250 via Upworks - Paid ✅ 
@bernhardoj, ended contract via Upworks, eligible for NewDot payment as of 5/5. Role C - owed $250 via NewDot

**Closed by slafortune** 2024-07-10 16:18 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-10 16:19
$250 approved for @bernhardoj
