### ISSUE TITLE
[$500] Request - Request money page reopens when hitting ENTER twice quickly in description editor

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32290] opened 2023-11-30 18:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to 1:1 DM > + > Request money
3. Enter amount > Next
4. Click description
5. Enter a description
6. Hit ENTER key twice quickly
Note that request money page reopens

## Expected Result:
The request money page will not reopen

## Actual Result:
The request money page reopens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fc95db3e-9216-4c11-b857-31e524d6edea

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01959958dfbf2a4763</li>
        <li>Upwork Job ID: 1740328319111016448</li>
        <li>Last Price Increase: 2024-01-15</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-11-30 20:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request money page reopens when hitting ENTER twice quickly in description editor

### What is the root cause of that problem?
When we press enter twice the first enter will set description and close the description edit page but before the `MoneyRequestDescriptionPage` is unmounted the second enter will create the request and also reset the iou which will reset `iou.id` as empty and this `useEffect` line of code is called
https://github.com/Expensify/App/blob/a7460f7f81c9999cf20964e67b6f9029dc18a51f/src/pages/iou/MoneyRequestDescriptionPage.js#L91-L92
because `shouldReset` will be true as `iou.id` is empty but `iouType` is let's say request
https://github.com/Expensify/App/blob/a7460f7f81c9999cf20964e67b6f9029dc18a51f/src/pages/iou/MoneyRequestDescriptionPage.js#L85-L86
### What changes do you think we should make in order to solve the problem?

We should add additional logic checking `iou.id` is not empty before setting `shouldReset` to true 
https://github.com/Expensify/App/blob/a7460f7f81c9999cf20964e67b6f9029dc18a51f/src/pages/iou/MoneyRequestDescriptionPage.js#L85-L86
to
```
        const shouldReset = !isEmpty(iou.id) && iou.id !== moneyRequestId;

```
### What alternative solutions did you explore? (Optional)

**Comment by sukach318** [comment] 2023-12-04 02:17
### **Proposal**

### **Please re-state the problem that we are trying to solve in this issue.**
Request money page reopens when hitting ENTER twice quickly in description editor

What is the root cause of that problem?
The root cause is that when the user rapidly presses the submit button two or three times, the updateComment function is invoked two or three times consecutively in `src/pages/iou/MoneyRequestDescriptionPage.js`

### **What changes do you think we should make in order to solve the problem?**
In the context of the MoneyRequestDescriptionPage component, the utilization of `_.debounce` proves beneficial in preventing multiple submissions of the form in rapid succession. The `useCallback` hook serves to memoize a function, ensuring that the same function instance is returned for each render cycle. This memoization strategy helps mitigate performance issues stemming from the unnecessary recreation of functions during each render.

Through the synergistic application of `useDebounce` and `useCallback`, we adeptly address performance concerns arising from both swift, consecutive events and the avoidance of superfluous function recreations.

In `src/pages/iou/MoneyRequestDescriptionPage.js`, change to - 

```
<FormProvider
    ...
    onSubmit={_.debounce(
        useCallback((value) => updateComment(value), []),
        400,
    )}
    ...
>
```
### **What alternative solutions did you explore? (Optional)**

**Comment by adelekennedy** [comment] 2023-12-07 21:04
on hold!

**Comment by situchan** [comment] 2023-12-18 20:31
#26538 is done. I just retested and bug is still reproducible.
@adelekennedy we can remove hold

**Comment by adelekennedy** [comment] 2023-12-19 20:38
taken off hold

**Comment by adelekennedy** [comment] 2024-01-15 16:40
ah - realized this automatically went to internal. Updating.

**Comment by FitseTLT** [comment] 2024-01-15 16:57
@adelekennedy It's no longer reproducible after the request refactor U can close it 👍

**Closed** 2024-01-15 17:09 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
