### ISSUE TITLE
[HOLD for payment 2024-12-07] [$500]  Remove or update the “Chat with your account manager here” banner

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#51433] opened 2024-10-24 17:55 UTC
Problem: Chat with your account manager makes users think they are chatting with their account manager in Concierge.
- We have this green bar on the top of the Concierge DM that looks like notice, but it actually directs you to the #admins room. But from looking at the UX, I would never guess that is a linkable banner.

Solution: Update the banner to look like button that clearly links to somewhere. And in the process, include the email and also have the link direct to the AM DM rather than the #admins room.

`[Lightbulb] Need something specific? Chat with your account manager, [firstName] ([accountManagerEmail]).  [Chat now] X` 

Image 1 shows the old UI. Image 2 shows the proposed updated UI. Please weigh in before I take it to GH with a contributor!

![image](https://github.com/user-attachments/assets/01d10c10-7464-4ba7-a40c-bb6867f2c03b)
![image](https://github.com/user-attachments/assets/8172d49d-b3d2-4f09-a9ee-0165037e46ee)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853509960370506398</li>
        <li>Upwork Job ID: 1853509960370506398</li>
        <li>Last Price Increase: 2024-12-06</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 104908687</li>
<li>mkzie2 | Contributor | 104908688</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by dannymcclain** [comment] 2024-10-24 19:23
Figma file and easier to view updated mocks:

[Account manager banner (Figma)](https://www.figma.com/design/Krt6A2zfTFwlfe39HKbhjn/Account-Manager-Banner?node-id=1-2&node-type=canvas&t=Sk8KKRjHk4GmRYtc-11)

![image](https://github.com/user-attachments/assets/2465bda2-cfbb-4a30-8d55-b485dcabf54e)

![image](https://github.com/user-attachments/assets/57c2e4b6-d6e5-4b9f-8950-28c15fd9931a)

☝️ No difference between those mocks—just showing light and dark mode. Note that they mostly follow the banner style we use for when a chat is read only or archived and we replace the composer with a banner.

**Comment by flaviadefaria** [comment] 2024-10-28 15:53
@danielrvidal Since cohort 1 is for customers with less than 10 users, then effectively, they won't have AMs. I'll keep this in the project board under `Upcoming cohorts` but if you think this can be prioritized elsewhere or if you think this should be prioritized differently lmk!

**Comment by danielrvidal** [comment] 2024-10-28 22:49
That sounds good, I think this can be done purely by Contributors, so maybe I still open it up so they can work on it even if it's not going to be CRITICAL for this cohort.

**Comment by danielrvidal** [comment] 2024-10-31 19:29
Still working on this.

**Comment by flaviadefaria** [comment] 2024-10-31 20:50
>That sounds good, I think this can be done purely by Contributors, so maybe I still open it up so they can work on it even if it's not going to be CRITICAL for this cohort.

Oh absolutely! We should open everything that is possible, and on a project board, to contributors (regardless of priority).

**Comment by danielrvidal** [comment] 2024-11-04 18:50
Adding this now to get a contributor to help out! @allgandalf I think this should be ready for proposals. Can you please let me know if you have any questions and evaluate the proposals as they come in. Thank you!

**Comment by Anaslancer** [comment] 2024-11-04 23:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove or update the “Chat with your account manager here” banner

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?
- Add `ChatWithAccountManagerParams` in [here](https://github.com/Expensify/App/blob/main/src/languages/params.ts).
```
type ChatWithAccountManagerParams = {
    firstName: string;
    email: string;
};
```
- Add 2 translations in [en.ts](https://github.com/Expensify/App/blob/c99ca246dfaaf6726d0b8b99fd4eeda4d3ea2cbb/src/languages/en.ts#L663-L695) and [es.ts](https://github.com/Expensify/App/blob/c99ca246dfaaf6726d0b8b99fd4eeda4d3ea2cbb/src/languages/es.ts#L655-L689).
```
        chatWithAccountManager: ({firstName, email}: ChatWithAccountManagerParams) => `Need something specific? Chat with your account manager, ${firstName} (${email}).`,
        chatNow: "Chat now",
```
- Add some props in [BannerProps](https://github.com/Expensify/App/blob/c99ca246dfaaf6726d0b8b99fd4eeda4d3ea2cbb/src/components/Banner.tsx#L19-L49).
```
    buttonText?: string;
    shouldShowButton?: boolean;
    onButtonPress?: () => void;
```
- Add `Button` component in this [`View`](https://github.com/Expensify/App/blob/c99ca246dfaaf6726d0b8b99fd4eeda4d3ea2cbb/src/components/Banner.tsx#L85-L108).
```
                            {shouldShowButton && !!onButtonPress && (
                                <Button
                                    accessibilityLabel={buttonText}
                                    success
                                    text={buttonText}
                                    onPress={onButtonPress}
                                    style={[styles.mh3, shouldUseNarrowLayout && styles.mt3, shouldUseNarrowLayout && styles.flexGrow1]}
                                />
                            )}
```
- Add this style in above `View`.
`shouldUseNarrowLayout ? styles.flexColumn : styles.flexRow`
- Wrap 2 components(Icon and Text) in one View.
- Remove `onPress` and add these lines at [Banner](https://github.com/Expensify/App/blob/c99ca246dfaaf6726d0b8b99fd4eeda4d3ea2cbb/src/pages/home/ReportScreen.tsx#L770-L777) in [ReportScreen](https://github.com/Expensify/App/blob/main/src/pages/home/ReportScreen.tsx) component.
```
                                text={translate('reportActionsView.chatWithAccountManager', {firstName: accountManager.firstName, email: accountManager.email})}
                                buttonText={translate('reportActionsView.chatNow')}
                                onButtonPress={chatWithAccountManager}
                                shouldShowButton
```

### What alternative solutions did you explore? (Optional)
N/A

### Contributor details
Your Expensify account email: anasup1995@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aff093c9a804b145

**Comment by Anaslancer** [comment] 2024-11-04 23:31
![Screenshot_8](https://github.com/user-attachments/assets/0d3ba630-031e-443f-8b8d-730e0cc4ee0f)

**Comment by mkzie2** [comment] 2024-11-06 11:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Update the “Chat with your account manager here” banner

### What is the root cause of that problem?
New feature
### What changes do you think we should make in order to solve the problem?


1. Update the banner text:

In this section, I will ignore the change in en.ts and es.ts because it is very straighfoward and can be handled in PR. In [this file](https://github.com/Expensify/App/blob/c99ca246dfaaf6726d0b8b99fd4eeda4d3ea2cbb/src/pages/home/ReportScreen.tsx#L733), create a variable to store the banner text:

```
  const [personalDetails] = useOnyx(ONYXKEYS.PERSONAL_DETAILS_LIST);
    const chatWithAMText = useMemo(() => {
        if (!accountManagerReportID) {
            const accountManagerReport = ReportUtils.getReport(accountManagerReportID);
            const participants = ReportUtils.getParticipantsAccountIDsForDisplay(accountManagerReport, false, true);
            const participantPersonalDetails = OptionsListUtils.getPersonalDetailsForAccountIDs([participants?.at(0) ?? -1], personalDetails);
            const participantPersonalDetail = Object.values(participantPersonalDetails).at(0);
            const displayName = PersonalDetailsUtils.getDisplayNameOrDefault(participantPersonalDetail);
            const login = participantPersonalDetail?.login;
            if (displayName && login) {
                return `Need something specific? Chat with your account manager, ${displayName} (${login}).`;
            }
            return `Need something specific? Chat with your account manager.`;
        }
        return '';
    }, [accountManagerReportID, personalDetails]);
```

It will get the account manager based on the account manager report and personal details data.


2. Add the button "Chat now" to the banner.
In this place, introduce new param ```buttonComponent``` and use it in:

https://github.com/Expensify/App/blob/c99ca246dfaaf6726d0b8b99fd4eeda4d3ea2cbb/src/components/Banner.tsx#L109

```
                        {!!buttonComponent && buttonComponent}
                        {shouldShowCloseButton && !!onClose && (
```

So when using Banner in [there](https://github.com/Expensify/App/blob/c99ca246dfaaf6726d0b8b99fd4eeda4d3ea2cbb/src/pages/home/ReportScreen.tsx#L770), use:

```
                                buttonComponent={
                                    <Button
                                        success
                                        style={{paddingRight: 8}}
                                        text="Chat now"
                                        onPress={chatWithAccountManager}
                                    />
                                }
```


3. Update the banner style: Background color, border radius, add bulb icon:

We just need to update the banner to:

```
                            <Banner
                                containerStyles={[styles.mh4, styles.mt4, styles.p4, {borderRadius: 8}]}
                                text={chatWithAMText}
                                onClose={dismissBanner}
                                onPress={chatWithAccountManager}
                                shouldShowCloseButton
                                icon={Expensicons.Lightbulb}
                                shouldShowIcon
                                buttonComponent={
                                    <Button
                                        success
                                        style={{paddingRight: 8}}
                                        text="Chat now"
                                        onPress={chatWithAccountManager}
                                    />
                                }
                            />
```

### What alternative solutions did you explore? (Optional)

**Comment by mkzie2** [comment] 2024-11-06 11:08
[Proposal updated](https://github.com/Expensify/App/issues/51433#issuecomment-2459450163)

**Comment by danielrvidal** [comment] 2024-11-07 19:07
Awesome, let me know if you have any questions @allgandalf, this is a high priority project so let us know what you need!

**Comment by danielrvidal** [comment] 2024-11-08 17:20
Done, thanks @allgandalf

**Comment by danielrvidal** [comment] 2024-11-11 21:29
@allgandalf @mkzie2 any updates on this? Should we expect a PR to review any time soon?

**Comment by mkzie2** [comment] 2024-11-12 02:33
I’m not assigned to this issue, and we’re still waiting for the internal review.

**Comment by marcaaron** [comment] 2024-11-15 02:55
Huh weird. This one must have fallen off my radar somehow. Assigned!

**Comment by mkzie2** [comment] 2024-11-15 18:41
Will raise the PR on Monday.

**Comment by mkzie2** [comment] 2024-11-18 08:49
@allgandalf Currently I'm unable to access Expensify Slack channel, can you help ask for these translations? Thanks!

en: `Need something specific? Chat with your account manager`
es: `¿Necesitas algo específico? Habla con tu gerente de cuenta.`

**Comment by mkzie2** [comment] 2024-11-18 10:48
@marcaaron How can we display the banner? Currently I'm using mock data and I want to test the PR with real data.

**Comment by marcaaron** [comment] 2024-11-18 20:34
@mkzie2 Hmm this is just a UI change AFAICT so mocking or forcing this to show up seems fine. Let's use `git blame` to figure out when we added it and use the same manual QA steps?

**Comment by danielrvidal** [comment] 2024-11-26 21:10
Looks like we should be deploying PRs soon per this issue: https://github.com/Expensify/App/pull/52682

**Comment by greg-schroeder** [comment] 2024-12-06 16:23
Payments completed, new feature UI update, so no regression test/problematic PR required to identify

**Closed by greg-schroeder** 2024-12-06 16:23 UTC
Labels: External, Weekly, NewFeature, Awaiting Payment, High Priority
