### ISSUE TITLE
[$500]  welcome message not updating when inviting new members to workSpace's #announce room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26333] opened 2023-08-30 20:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create new workspace
2. Navigate to #announce room
3. Go to settings ->click to Welcome message
4. Navigate to Workspace model -> click "Members"
5. Invite users
## Expected Result: 
A welcome message appears when a new person is invited to the workspace
## Actual Result: 
The welcome message does not appear when a new person is invited to the workspace. Click another chat and click #announce room again, new welcome message is updated.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[welcome_message.webm](https://github.com/Expensify/App/assets/43996225/37bad635-9429-4c7e-bb07-3f870f511021)

https://github.com/Expensify/App/assets/43996225/66f4f719-db52-4ff2-a57f-7ae11288cda2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Le Thi Thu Thuy
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692616692151069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f748a675fddda96c</li>
        <li>Upwork Job ID: 1697005666951528448</li>
        <li>Last Price Increase: 2023-08-30</li>
    </ul>
</details>

**Comment by studentofcoding** [comment] 2023-08-31 08:23
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Welcome message not updating when inviting new members to workSpace's #announce room

## What is the root cause of that problem?

This is because the ReportWelcomeMessagePage component is only updating the welcome message on the server, but not in the local state.

## What changes do you think we should make in order to solve the problem?

To fix this, you need to update the local state after the welcome message is successfully updated on the server. You can do this by dispatching an action that updates the report object in Onyx (our state management library) with the new welcome message.

- In [src/pages/ReportWelcomeMessagePage.js](https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/pages/ReportWelcomeMessagePage.js#L4), update the submitForm function to dispatch an action that updates the local state:

```
const submitForm = useCallback(() => {
    Report.updateWelcomeMessage(props.report.reportID, props.report.welcomeMessage, welcomeMessage.trim(), () => {
        // Update the local state after the welcome message is updated on the server
        Report.updateReportObject(props.report.reportID, {welcomeMessage: welcomeMessage.trim()});
    });
}, [props.report.reportID, props.report.welcomeMessage, welcomeMessage]);
```

- In [src/libs/actions/Report.js](https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/libs/actions/Report.js#L4), add a new function updateReportObject:

```
/**
 * Updates the report object in Onyx
 *
 * @param {Number} reportID
 * @param {Object} updates
 */
function updateReportObject(reportID, updates) {
    Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT}${reportID}`, updates);
} 
```

## What alternative solutions did you explore? (Optional)

None

## Result

**Comment by pecanoro** [comment] 2023-08-31 17:52
Yes! it was done on purpose, automated whispers won't be shown to the owner now.

**Comment by pecanoro** [comment] 2023-08-31 17:53
I am going to close it since it was intended.

**Closed by pecanoro** 2023-08-31 17:53 UTC
Labels: External, Daily, Help Wanted, Bug
