### ISSUE TITLE
[HOLD for payment 2023-08-03] [HOLD for payment 2023-08-02] [$1000]  Dev: Web - User is unable to authenticate with magic link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23504] opened 2023-07-24 19:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to sign-in page
2. Enter email & click on 'Continue' button
3. Open email > copy magic link > paste it address bar > prefix the link with 'http://localhost:8080/' > press enter

## Expected Result:
User should be authenticated

## Actual Result:
 User is not signed in

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.44-0
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f534bf23-d3d2-4e41-901f-cf1999023cce

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690190001655879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117f832e71039be93</li>
        <li>Upwork Job ID: 1683881238506196992</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Contributor | 25745592</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-24 20:46
This seems to be a regression from [this PR](https://github.com/Expensify/App/pull/22461).
If remove the following code, user can be authenticated.
https://github.com/Expensify/App/blob/85d84b8d42f1b345fe0804592d1bab8b07875948/src/pages/ValidateLoginPage/index.website.js#L64-L68

**Comment by kadiealexander** [comment] 2023-07-25 06:19
@NikkiWines @srikarparsi @johnmlee101 could you please take a look and see if this is a regression from https://github.com/Expensify/App/pull/22461?

**Comment by Natnael-Guchima** [comment] 2023-07-25 06:48
This is reproducible on staging too on the latest release. 
https://github.com/Expensify/App/assets/57330233/761b92a7-5a98-478f-a746-d8516994780b

**Comment by NikkiWines** [comment] 2023-07-25 16:35
Hmm, this probably should've been marked as a deploy blocker since it was (previously) only on dev and is indeed a regression from https://github.com/Expensify/App/pull/22461 as @StevenKKC pointed out.

**Comment by danieldoglas** [comment] 2023-07-25 16:46
@jjcoffee proposal looks good, can you please prioritize and get a PR ready for this ASAP?

**Comment by NikkiWines** [comment] 2023-07-25 18:15
I'll push up a fix 👍

**Comment by danieldoglas** [comment] 2023-07-25 18:20
@NikkiWines assigning you since you're working on it.

**Comment by NikkiWines** [comment] 2023-07-25 18:51
@allroundexperts in this case no, since @danieldoglas and I agreed on the proposal and a C+ is auto-assigned to the corresponding PR

**Comment by NikkiWines** [comment] 2023-07-25 23:46
Confirmed this is fixed on staging now 

https://github.com/Expensify/App/assets/16747822/8c73b373-c533-4f96-875a-b9cbdebb32cd

**Comment by kadiealexander** [comment] 2023-08-04 04:21
Payouts due:

Issue Reporter: $250 @Natnael-Guchima
Contributor: n/a
Contributor+: n/a

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/nx/wm/offer/25938979).

**Comment by Natnael-Guchima** [comment] 2023-08-04 04:22
Accepted the offer. Thanks @kadiealexander

**Comment by kadiealexander** [comment] 2023-08-04 04:26
All paid! Please reopen if anything got missed.

**Comment by jjcoffee** [comment] 2023-08-04 10:29
@kadiealexander Would any compensation be due for me here, as [my proposal](https://github.com/Expensify/App/issues/23504#issuecomment-1649461644) was used for the fix? (I just couldn't implement it due to being in the "wrong" timezone and the fix was needed urgently!)

**Comment by pecanoro** [comment] 2023-08-04 10:46
@kadiealexander @NikkiWines Discussing the above message here: https://expensify.slack.com/archives/C01GTK53T8Q/p1691145123070889

**Comment by JmillsExpensify** [comment] 2023-08-08 03:05
Re-opening for confirmation on payment for @allroundexperts

**Comment by kadiealexander** [comment] 2023-08-08 03:16
Thanks Jason! I had this on my to-do for today. As discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1691145123070889) we agreed to compensate @jjcoffee 50% of the job price as we used their proposal. The following payouts are due:

- [ ] Issue Reporter: $250 @Natnael-Guchima
- [ ] Contributor: $500 @jjcoffee
- [ ] Contributor+: $1000 @allroundexperts (paid via Newdot)

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/nx/wm/offer/25938979).

**Comment by kadiealexander** [comment] 2023-08-08 03:20
@jjcoffee please let me know when you've accepted the Upwork contract.

**Comment by JmillsExpensify** [comment] 2023-08-08 04:13
No worries! Reviewed the details for @allroundexperts. This is approved for payment via NewDot.

**Comment by jjcoffee** [comment] 2023-08-08 16:55
@kadiealexander Accepted the offer, thanks!

**Closed** 2023-08-10 07:44 UTC
Labels: Engineering, Daily, Internal, Needs Reproduction, Overdue, Awaiting Payment, Bug
