### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Category & Tag - No scroll bar in Category and Tag list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34762] opened 2024-01-18 19:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-1
**Reproducible in staging?:** Y  
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User is an employee of Collect workspace that has categories and tags
1. Go to workspace chat
2. Open request money page
3. Enter amount > Next > Show more
4. Click Category
5. Scroll through the list
6. Click Tag
7. Scroll through the list

## Expected Result:
There will be scroll bar when the list is long

## Actual Result:
There is no scroll bar when the list is long

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7d713b74-7d8a-4972-a718-746977301530

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01085ff3847931e9ee</li>
        <li>Upwork Job ID: 1748069254741348352</li>
        <li>Last Price Increase: 2024-01-18</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 28117079</li>
<li>bernhardoj | Contributor | 28117080</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-18 19:46
[#wave6-collect-submitters](https://expensify.enterprise.slack.com/archives/C02MW39LT9N)

**Comment by FitseTLT** [comment] 2024-01-18 19:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Category & Tag - No scroll bar in Category and Tag list

### What is the root cause of that problem?
We are not passing `shouldAllowScrollingChildren` to options selector
### What changes do you think we should make in order to solve the problem?

We should be passing `shouldAllowScrollingChildren`  true to options selector in tagpicker and category picker

### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment] 2024-01-18 19:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Category & Tag - No scroll bar in Category and Tag list

### What is the root cause of that problem?

We do not use the  `ScrollView` component to wrapper to children in `IOURequestStepCategory` and `IOURequestStepTag`

### What changes do you think we should make in order to solve the problem?


Wrap the children components with `ScrollView` .

**Comment by bernhardoj** [comment] 2024-01-19 03:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No scrollbar for category and tag list.

### What is the root cause of that problem?
The list simply uses BaseOoptionsList that has a default value of false for `showsVerticalScrollIndicator` and we didn't pass it as true for both tag and category list, so the scroll is not visible.
https://github.com/Expensify/App/blob/e6b07616db3a818574d60acf1d9ebaf1cb26bf02/src/components/OptionsList/BaseOptionsList.js#L279

### What changes do you think we should make in order to solve the problem?

I don't know what is the rule to decide which page should show a scrollbar or not because this happens on many pages, but the solution is just to pass `showScrollIndicator` to the list component (OptionsSelector), or make it default to true if we want to show the scroll on all pages.

**Comment by akinwale** [comment] 2024-01-22 08:33
After reviewing all proposals, I recommend moving forward with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/34762#issuecomment-1899645970) which contains a simple and straightforward solution.

@bernhardoj Let's try to identify all the list views in the Request money flow and apply the changes there.

@FitseTLT When making significant edits to your proposal, please follow the guidelines and create an updated post in the thread, irrespective of whether there is already another proposal or not. This makes things easier to keep track of. There is also a lengthy code diff without a clear explanation of what the change does.

🎀👀🎀 C+ reviewed.

**Comment by dannymcclain** [comment] 2024-01-22 15:15
@shawnborton do we ever purposely hide scrollbars in the app? I guess I had just assumed we display them whenever they're present.

(I'm always on Mac and iOS where scrollbars are always invisible until you're using them—so it's totally possible I've missed some scrollbar-related details.)

**Comment by shawnborton** [comment] 2024-01-22 21:02
Hmm great question. I was under the same impression - we basically just follow platform conventions there, and indeed, on Mac I think they are basically hidden by default. 

So I would say this isn't a bug and we can just close this one out.

**Comment by akinwale** [comment] 2024-01-22 21:09
> So I would say this isn't a bug and we can just close this one out.

I believe the bug here is that the scrollbars are not displayed at all even when scrolling.

**Comment by shawnborton** [comment] 2024-01-22 21:13
Ah, got it, that makes sense. But that being said, whatever proposal we accept, we should make it so that the scroll behavior here matches the same scroll behavior elsewhere - we shouldn't just always show the scrollbar by default in this view, but rather, only when scrolling (if that's what the platform convention is of course).

**Comment by shawnborton** [comment] 2024-01-22 21:39
Can we confirm [that proposal](https://github.com/Expensify/App/issues/34762#issuecomment-1899824038) won't just force scrollbars to show on Mac even when scrolling is not happening?

**Comment by akinwale** [comment] 2024-01-23 05:39
@neonbhai A proposal has already been selected.

@bernhardoj When testing, please take the comments in 
https://github.com/Expensify/App/issues/34762#issuecomment-1904827362 especially regarding matching platform behaviour on macOS.

@MariaHCD I believe we can move forward here.

**Comment by bernhardoj** [comment] 2024-01-23 09:01
PR is ready

cc: @akinwale

**Comment by laurenreidexpensify** [comment] 2024-02-08 10:53
Payment Summary:

Contributor: $500 @bernhardoj paid in Upwork
C+ review: $500 @akinwale paid in Upwork

**Comment by laurenreidexpensify** [comment] 2024-02-08 10:53
remaining steps before closing: @akinwale to complete checklist and confirm re: regression testing

**Comment by akinwale** [comment] 2024-02-09 02:17
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Scrollbars for the list items were not being displayed previously.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
* Launch Expensify in a browser
* Click on the global create menu and select Request money
* Select the Manual tab if it is not already active
* Enter an amount and click Next
* Click Category
* Scroll through the list
* Verify that the scrollbar (matching platform behaviour) is displayed (for lists which can scroll offscreen)
* Select a Category or navigate back
* Click Tag
* Scroll through the list
* Verify that the scrollbar (matching platform behaviour) is displayed (for lists which can scroll offscreen)

Do we agree 👍 or 👎?

**Comment by akinwale** [comment] 2024-02-09 02:17
@laurenreidexpensify Payment received. Thanks.

I have completed the checklist.

**Closed** 2024-02-09 10:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
