### ISSUE TITLE
[$500] Web - Assign task - Tool tip starts to be inverted after clicking on edit and making a post unread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26650] opened 2023-09-04 11:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Assign a task to account B
2. While inside the task thread send a message
3. Hover over the avatar and the name and observe the position of the tooltip
4. Hover over the last sent message and click on the edit icon
5. Go to the LHN and right click on the open chat and click on Mark as unread
6. Go to the edit box and click on the close icon
7. Hover over the avatar and on the account name again and observe the position of the tooltip

## Expected Result:
The position of the tooltip should not change

## Actual Result:
The position of the tooltip inverts

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.62-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/97ece39c-ccb4-4494-a5b8-4eabf0506004

https://github.com/Expensify/App/assets/115492554/296e1595-0932-48c2-85a3-2a3411a18ad2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692947480477819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01acf203d863453a81</li>
        <li>Upwork Job ID: 1698691177926508544</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-09-04 13:34
We've now got multiple issues with the tooltip being "inverted" in certain cases:

https://github.com/Expensify/App/issues/26041
https://github.com/Expensify/App/issues/22222

I think someone should tackle them all, as I suspect there's a common RCA.

**Comment by WasilIslam** [comment] 2023-09-04 17:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tool tip starts to be inverted after clicking on edit and making a post unread
### What is the root cause of that problem?

The colors are not inverted, they are like this from the beginning. This is a css issue at src/styles/getTooltipStyles.js. It has been designed like this from the beginning. 

<img width="519" alt="Screenshot 2023-09-04 at 9 52 24 PM" src="https://github.com/Expensify/App/assets/74556190/f03484bc-9faf-4776-91c4-c4faacd0f90e">

There is no quick fix one liner fix, because the same tooltip is being used in other places where a bg color of white maybe required eg tooltip displaying more 
<img width="102" alt="Screenshot 2023-09-04 at 9 57 22 PM" src="https://github.com/Expensify/App/assets/74556190/73f046b7-ecab-4f9e-89a9-1cdabe7586a1">



### What changes do you think we should make in order to solve the problem?
We should create new styles for these tooltips which are separate from the tooltips where inverted colors are required. to match with the site colors. We can make use of the already predefined colors in colors.js within same folder.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by MuhammadSaboorIslam** [comment] 2023-09-04 17:25
I also propose @WasilIslam solution

**Comment by rakshitjain13** [comment] 2023-09-04 18:21
Contributor details
Your Expensify account email:  rakshitdhoka13@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c427caaa5ebf3b9c

**Comment by trjExpensify** [comment] 2023-09-08 16:23
@situchan can you review this one please? Thanks!

**Comment by trjExpensify** [comment] 2023-09-11 11:03
Bump, @situchan!

**Comment by situchan** [comment] 2023-09-18 09:53
reviewing today

**Comment by trjExpensify** [comment] 2023-09-20 11:30
@situchan did you review?

**Comment by situchan** [comment] 2023-09-20 11:37
I tested against latest main but not reproducible to me.


https://github.com/Expensify/App/assets/108292595/cfdd6a0a-eea0-4ffb-a400-a24ff68212b3



@Nathan-Mulugeta are you still able to reproduce?

**Comment by situchan** [comment] 2023-09-20 11:42
@rmm-fl I followed your repro step in https://github.com/Expensify/App/issues/26650#issuecomment-1705713958 but still not reproducible. Can you?

**Comment by situchan** [comment] 2023-09-20 12:04
It would be great if you can find PR which fixed this.

**Comment by Nathan-Mulugeta** [comment] 2023-09-20 12:12
I can't reproduce this anymore as well

**Comment by situchan** [comment] 2023-09-20 12:14
@Nathan-Mulugeta are you able to find the PR so you can claim bug reporting bonus?

<img width="1047" alt="Screenshot 2023-09-20 at 6 14 34 PM" src="https://github.com/Expensify/App/assets/108292595/18234dcd-7358-495c-9afc-156449a0582a">

**Comment by trjExpensify** [comment] 2023-09-21 11:59
Cool, I think we close this out then. @Nathan-Mulugeta if you find the PR, feel free to let me know here and I'll reopen!

**Closed by trjExpensify** 2023-09-21 11:59 UTC
Labels: External, Daily, Help Wanted, Bug
