### ISSUE TITLE
Android & iOS - Composer - Selected emoji is not shown in the composer after sending message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46024] opened 2024-07-23 14:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to DM
3. Tap on the emoji picker
4. Select an emoji and send it
5. Tap on the emoji picker
6. Select another emoji

## Expected Result:
The selected emoji will be shown in the composer

## Actual Result:
The selected emoji is not shown in the composer after sending message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/fca03310-7f27-426d-b846-a95007f21e86

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-23 14:49
We think that this bug might be related to #vip-vsp

**Comment by rlinoz** [comment] 2024-07-23 15:14
Removing the Web-E blocker label, since this is on the app composer.

**Comment by rlinoz** [comment] 2024-07-23 16:57
It looks like it is caused by https://github.com/Expensify/App/pull/45613

cc: @hannojg @Ollyws

**Comment by hannojg** [comment] 2024-07-23 18:42
Might have been caused by my PR, will take a look tmrw, feel free to assign me!

Interesting side note: you can still press send and the emojis will be send to chat, its just that the composer seem to be stuck

**Comment by rlinoz** [comment] 2024-07-23 19:17
We CP'd the revert and it fixed the issue.

**Comment by rlinoz** [comment] 2024-07-24 12:55
Let's close this one since the issue is fixed by the revert.

**Closed by rlinoz** 2024-07-24 12:55 UTC
Labels: Reviewing, Engineering, Weekly
