### ISSUE TITLE
[$1000] Open Electron popup is shown while opening the Expensify on web

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14479] opened 2023-01-23 19:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Setup our app locally
2. Open [staging.new.expensify.com](http://staging.new.expensify.com/)

## Expected Result:
Open in New Expensify shown if our desktop is installed. If not No popup

## Actual Result:
Open in Electron popup

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1116" alt="image (1)" src="https://user-images.githubusercontent.com/43996225/214132076-3f0d80a5-5608-4d68-8011-24eaf7ed0066.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1674481724781139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ddecff1624984752</li>
        <li>Upwork Job ID: 1620137032797765632</li>
        <li>Last Price Increase: 2023-01-30</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2023-01-26 02:19
Hey @kavimuru, can you please elaborate on the 1st step: Setup our app locally. I don't know how to reproduce it, can you clarify? Thanks!

**Comment by isabelastisser** [comment] 2023-01-28 01:19
bump @kavimuru and @Santhosh-Sellavel. Can you please provide more steps so I can reproduce the bug? Thanks!

**Comment by isabelastisser** [comment] 2023-01-30 18:48
No updates so I'm closing this.

**Comment by isabelastisser** [comment] 2023-01-30 19:07
I chatted with @Santhosh-Sellavel and he provided more context here:

Download app source https://github.com/Expensify/App 

Guide for local development setup https://github.com/Expensify/App#local-development

**Comment by Julesssss** [comment] 2023-01-31 17:43
I don't believe this is a bug. It is intentionally showing, though I agree it is annoying.

**Closed by Julesssss** 2023-01-31 17:43 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by situchan** [comment] 2023-01-31 20:28
I think the issue here is that popup shows even when not installed desktop app.

**Comment by eVoloshchak** [comment] 2023-01-31 20:44
Looking at the [Slack discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1674481724781139), this is happening only to developers. Everyone with a development setup will be affected on dev, on `new.expensify.com` and on staging. 
Tagging @Santhosh-Sellavel and @ckrodrigues since they were participating in the original slack discussion and have more context

**Comment by stitesExpensify** [comment] 2023-02-01 03:23
I have already pushed a fix here 😄 https://github.com/Expensify/App/pull/14723

LMK if you don't think it fixes the issue for developers
