### ISSUE TITLE
[$250] Connect Bank Account - Connect Manually - "Fix the error" has a pointer cursor but no functionality @varshamb

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11424] opened 2022-09-29 16:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2.  Navigate to settings > workspace > connect bank account
3. Connect manually
4. Enter wrong Routing number and other details
5. Check the error message "Please fix the errors in the form before continuing."

## Expected Result:
 "Fix the error" does not have a pointer cursor and something should happen when you cick on it

## Actual Result:
"Fix the error" has a pointer cursor but nothing happens when we click it.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193087196-2056a84f-8f93-4a53-ad8b-1b36ba9acb1f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @varshamb

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663725819169889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment] 2022-09-30 07:44
Sorry, I am OOO so reassgining.

**Comment by Puneet-here** [comment] 2022-09-30 08:06
Hi, We aren't using a function for this right now and this will be implemented after the Form refactors. So I don't think we need this issue.

cc: @luacmartins

**Comment by Christinadobrzyn** [comment] 2022-09-30 08:14
Thanks @Puneet-here, we'll close this issue for now

**Comment by Luke9389** [comment] 2022-10-12 20:59
I'm going to reopen this issue as it's still happening. We can set it to weekly and check in on reproducibility at that pace. @Puneet-here can you link to the form refactor issue/PR you're referring to?

**Comment by tgolen** [comment] 2022-10-12 22:47
I stumbled upon the problem here. Turns out these prop names do not match.

The code is trying to trigger the callback here: https://github.com/Expensify/App/blob/da9a8957bb8046fe7517b790a2e1241819215aeb/src/components/FormAlertWrapper.js#L72 (named `onFixTheErrorsPressed`) but all components are passing a prop named slightly different: `onFixTheErrorsLinkPressed`

**Comment by Luke9389** [comment] 2022-10-12 23:20
Looks like @aimane-chnaif had that one pegged. 

@aimane-chnaif are you currently working on a PR for an External issue? If not we can make this one external and assign it to you.

**Comment by Christinadobrzyn** [comment] 2022-10-13 02:15
Looks like this is missing the engineering label to determine if it should be external or internal - adding that now!

**Comment by Puneet-here** [comment] 2022-10-13 07:01
> I'm going to reopen this issue as it's still happening. We can set it to weekly and check in on reproducibility at that pace. @Puneet-here can you link to the form refactor issue/PR you're referring to?

@Luke9389, when this issue was reported this was known and was in development and it was reported many times before, @luacmartins had mentioned that it's known and this feature will be implemented after form refactor, which is true the issue would have resolved but because of this mistake of using `onFixTheErrorsPressed` and  `onFixTheErrorsLinkPressed` this wasn't fixed even after the refactor and IMO the report [here](https://github.com/Expensify/App/issues/11729) by @aimane-chnaif is the one that should stay open.

**Comment by parasharrajat** [comment] 2022-10-13 15:46
@aimane-chnaif 's [proposal](https://github.com/Expensify/App/issues/11424#issuecomment-1276749957) looks good to me. Let's fix all the instances of this prop name typo.

cc; @NikkiWines 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by varshamb** [comment] 2022-10-13 16:55
My github handle is `@varshamb` not `varsha`.

**Comment by kbecciv** [comment] 2022-10-13 17:01
Sorry @varshamb corrected

**Comment by joekaufmanexpensify** [comment] 2022-10-13 19:56
Clarifying a [question](https://expensify.slack.com/archives/C01SKUP7QR0/p1665690961480899) before creating upwork job.

**Comment by NikkiWines** [comment] 2022-10-14 14:22
Looks good! @joekaufmanexpensify can we hire @aimane-chnaif for this job, please? Thank you!

**Comment by NikkiWines** [comment] 2022-10-14 14:55
I'd say `onFixTheErrorsLinkPressed`

**Comment by joekaufmanexpensify** [comment] 2022-10-14 19:25
Sounds good! Going to:

- Create the upwork job. 
- Hire @varshamb for reporting the bug. 
- Hire @aimane-chnaif to fix the bug. 
- Hire @parasharrajat as C+

**Comment by joekaufmanexpensify** [comment] 2022-10-14 19:30
Job is [here](https://www.upwork.com/jobs/~016616e7640e850846).

**Comment by joekaufmanexpensify** [comment] 2022-10-14 19:43
@varshamb offer sent!

**Comment by joekaufmanexpensify** [comment] 2022-10-14 19:45
@parasharrajat offer sent!

**Comment by joekaufmanexpensify** [comment] 2022-10-14 19:48
@aimane-chnaif offer sent!

**Comment by joekaufmanexpensify** [comment] 2022-10-21 14:41
@parasharrajat Just bumping the offer for this one for whenever you have a sec. Could you accept in Upwork?

**Comment by joekaufmanexpensify** [comment] 2022-10-21 14:42
PR has been merged, QA is ongoing.

**Comment by parasharrajat** [comment] 2022-10-21 14:43
Will do. Thanks

**Comment by joekaufmanexpensify** [comment] 2022-11-02 20:19
We're at the 7 day window with no regressions, so issuing payment!

**Comment by joekaufmanexpensify** [comment] 2022-11-02 20:24
@aimane-chnaif payment was sent, and contract ended!

**Comment by joekaufmanexpensify** [comment] 2022-11-02 20:25
@parasharrajat payment sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2022-11-02 20:26
@varshamb payment sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2022-11-02 20:27
Job closed. This is all set!

**Closed by joekaufmanexpensify** 2022-11-02 20:27 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
