### ISSUE TITLE
[$500] Task-On opening user C chat page, task is duplicated and displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32937] opened 2023-12-12 17:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Open 1:1 chat of user A
3. Create a task entering title and description
4. Open created task and tap assignee
5. Assign to user C
6. Assign to yourself
7. Assign to user C
8. Open user C chat in LHN

## Expected Result:
On opening user C chat page, task must not be duplicated and displayed

## Actual Result:
On opening user C chat page, task is duplicated and displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f08d0419-f024-47e0-af00-5bfa81167a0b

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb0a8f1e8188db47</li>
        <li>Upwork Job ID: 1734621000263557120</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-12-13 01:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Task-On opening user C chat page, task is duplicated and displayed

### What is the root cause of that problem?
- Once we assign task to user C, the message is added. So in case of this bug, we assign the task to user C two times, so two messages are displayed.
### What changes do you think we should make in order to solve the problem?
 - Because clicking on the both message still navigate user to the same task report, so we just need to display the lastest message.
 - The general idea is that, we will filter all the reportActions that have the same ```reportAction.originalMessage.taskReportID``` Do it by update:
 https://github.com/Expensify/App/blob/9f00f67484d8da1ccf568d19b3b615f245671978/src/libs/ReportActionsUtils.ts#L484-L490



### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Santhosh-Sellavel** [comment] 2023-12-14 18:52
@getusha Please take over this one as C+, I missed this one on the post [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1702579265491999) as you volunteered for one, if not let me know, I'll ask for help in channel

cc: @abekkala

**Comment by abekkala** [comment] 2023-12-15 20:16
Tagged DB in #vip-vsb to confirm adding to the project.

**Comment by thienlnam** [comment] 2023-12-15 20:23
This is intended functionality and the test rail should be updated - it's re-links to the task report because in the typical scenario you may have other conversations in the DM between User A and User C so the task is resurfaced if the assignee is re-updated. It's not a typical scenario to immediately reassign to the same person multiple times

**Closed by thienlnam** 2023-12-15 20:23 UTC
Labels: External, Daily, Help Wanted, Bug
