### ISSUE TITLE
[$500] Split bill - The amount of money have been displayed consistently about currency in the IOU screen

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27185] opened 2023-09-11 18:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new split bill
2. Enter the amount of money
3. Choose users that you want to split the bill
4. Move to another user tab (the user that has been split bill before)

## Expected Result:
The money should be displayed in one currency.

## Actual Result:
The money is displayed in two different currencies.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.67-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/b14ee17e-53d3-41e1-b614-bd5f32152f31

https://github.com/Expensify/App/assets/115492554/b1db834b-2156-4dff-a6e9-70238c2d280e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @thuyle04

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693908742916009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124e2b8aade7d6d8b</li>
        <li>Upwork Job ID: 1701300073982619648</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-09-14 18:49
@JmillsExpensify we have a known issue (more info [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694513579526909)) with double-assignments happen, so going to unassign myself as the second assigner 👍

**Comment by narefyev91** [comment] 2023-09-20 09:01
Waiting for proposals

**Comment by mvtglobally** [comment] 2023-09-28 03:20
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2023-10-11 14:34
Can anyone else reproduce this issue still?

**Comment by JmillsExpensify** [comment] 2023-10-17 20:29
Closing since we can't seem to reproduce.

**Closed by JmillsExpensify** 2023-10-17 20:29 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
