### ISSUE TITLE
[Pay 4/30][$500] Workspaces - Unsynchronized transition of left and right page when deleting workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38922] opened 2024-03-25 10:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces.
3. Go to any workspace.
4. Delete the workspace.

## Expected Result:
Both left and right page will disappear at the same time.

## Actual Result:
The left page disappears first, then followed by the right page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/64bc7c7b-c327-43be-9a46-1b427f083333

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0173bde0810a3af269</li>
        <li>Upwork Job ID: 1772269977938833408</li>
        <li>Last Price Increase: 2024-04-01</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by izarutskaya** [comment] 2024-03-25 10:32
@mallenexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #vip-vsb.

**Comment by izarutskaya** [comment] 2024-03-25 10:32
Different behavior on production.


https://github.com/Expensify/App/assets/115492554/2276b714-9630-4d05-aa79-e3cc04708777

**Comment by ahmedGaber93** [comment] 2024-03-25 13:28
It seems a regression from #38321, I think we need to use back using `goBack` here
https://github.com/Expensify/App/blob/3d780639eb260c1165e884032f4a92aa7dbbb4ca/src/libs/PolicyUtils.ts#L276

**Comment by neil-marcellini** [comment] 2024-03-25 14:30
I think this behavior is actually better than what's on production, and it's not a big deal that one page disappears slightly before the other. I'm going to remove the blocker label and make this a low priority external issue.

**Comment by hayes102** [comment] 2024-03-25 15:08
i am not sure but maybe it's a regression from this PR https://github.com/Expensify/App/pull/38365

**Comment by cubuspl42** [comment] 2024-03-26 08:54
@GandalfGwaihir 

I don't get it.

```
// If the workspace being deleted is the active workspace, switch to the "All Workspaces" view 
```

As this comment states, this is intended to be executed only if the workspace being deleted is the active workspace. Have you tested your code when, for example, workspace A is active, and you delete the workspace B?

**Comment by godofoutcasts94** [comment] 2024-03-26 09:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspaces - Unsynchronized transition of left and right page when deleting workspace
### What is the root cause of that problem?
The main root cause here is, here :
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/workspace/WorkspaceProfilePage.tsx#L94-L108
inside, the `goBackFromInvalidPolicy()` function, we have defined it like this : 
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/PolicyUtils.ts#L275-L277
which is causing delay in left and right page when deleting a workspace.
### What changes do you think we should make in order to solve the problem?

We need to change it from `Navigation.navigate(ROUTES.SETTINGS_WORKSPACES);` to `Navigation.goBack(ROUTES.SETTINGS_WORKSPACES);` from both the pages going away simulatenously.
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by godofoutcasts94** [comment] 2024-03-26 09:28
updated [proposal](https://github.com/Expensify/App/issues/38922#issuecomment-2019914138) with working video. No other changes done

**Comment by cubuspl42** [comment] 2024-03-26 10:15
> Yes, here is the test with my suggested code:

No need for two windows. I just tested this by returning to the "Chats" view, and the behavior seemed to be a regression.

**Comment by cubuspl42** [comment] 2024-03-26 10:16
@godofoutcasts94 

Sounds good. Possibly we'll go with this one.

**Comment by cubuspl42** [comment] 2024-03-27 09:01
@ZhenjaHorbach

Sorry for not commenting on your proposal.

Would you also provide a video showing how your proposed solution works, including the path that leads to `FullPageNotFound` (I'm not sure if I understand this yet)?

**Comment by godofoutcasts94** [comment] 2024-03-27 09:36
> @godofoutcasts94 
> 
> 
> 
> Sounds good. Possibly we'll go with this one.

Will I get assigned on it @cubuspl42 ?

**Comment by cubuspl42** [comment] 2024-03-27 09:44
Come on, I said "possibly". I gave my feedback and shared my thoughts at the time of writing.

Since then, there were [some valid concerns raised](https://github.com/Expensify/App/issues/38922#issuecomment-2020106816) about your proposal in its current state.

**Comment by godofoutcasts94** [comment] 2024-03-27 09:51
> Come on, I said "possibly". I gave my feedback and shared my thoughts at the time of writing.
> 
> 
> 
> Since then, there were [some valid concerns raised](https://github.com/Expensify/App/issues/38922#issuecomment-2020106816) about your proposal in its current state.

Oh sorry I didn't follow the entire thread

**Comment by cubuspl42** [comment] 2024-03-28 09:39
@GandalfGwaihir

> The policy is already set as invalid, hence we never reach that state 

Do I understand correctly that you're suggesting that the condition of this `if` statement...

```ts
if (activeWorkspaceID === policy?.id) {
    // ...
}
```

...is never true in practice? Making its body dead code?

**Comment by cubuspl42** [comment] 2024-03-28 09:46
> Actually i misunderstood at first, 

When changing your proposal, please ensure to re-read it as a whole and ensure that it's up-to-date. Because now, you're just saying "nah, don't look at that part of the proposal, that's outdated!". It's not meant to be like this.

**Comment by cubuspl42** [comment] 2024-03-28 09:48
> So the regression that you pointed out won’t happen, shall i add a result video ?

Not necessarily, but please make your proposal consist of a clear, up-to-date root cause analysis and a clean, up-to-date solution proposal with rationale.

**Comment by cubuspl42** [comment] 2024-03-28 10:06
Hm, sorry, maybe I could have misunderstood your words. If you're sure that the RCA is synced with the proposal, then it's alright. Let's [continue this on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1711620247570789), as it's best not exchange too many messages on GitHub issues.

**Comment by cubuspl42** [comment] 2024-03-28 11:15
@tienifr Interesting, you focused on the 2-tab scenario strongly. I'm wondering if what you call a "regression" is actually a regression at all. If something got deleted, it can't be found; this UX might be good enough for a corner case.

**Comment by mallenexpensify** [comment] 2024-03-28 19:03
@dubielzyk-expensify , looping in design to see how y'all feel about the bug, view the vid in the OP. 

@cubuspl42 , @tienifr @GandalfGwaihir , @ZhenjaHorbach @godofoutcasts94 and others.... if we fix this small bug, are there other instances that would also be improved? This seems like a very small bug that almost no one would notice

**Comment by mallenexpensify** [comment] 2024-03-28 19:05
Tom, added this to #wave-collect because the bug occurs in when deleting a workspace and I feel like that would be first encountered as part of the wave.   Also, it'd be polish (assuming we end up fixing it)

**Comment by godofoutcasts94** [comment] 2024-03-28 19:06
@mallenexpensify I totally agree with you and I would say that my proposal will even make it better. Please have a look at [it](https://github.com/Expensify/App/issues/38922#issuecomment-2019914138) if possible

**Comment by cubuspl42** [comment] 2024-03-29 09:17
@mallenexpensify 

> @cubuspl42 [...] and others....

I believe the Contributors answered your question. Personally, I feel like you have doubts about the issue itself rather than the proposed solutions, so I don't have much to say.

**Comment by mallenexpensify** [comment] 2024-03-29 23:26
> Personally, I feel like you have doubts about the issue itself rather than the proposed solutions, 

Correct. I'm not providing feedback on the proposed solutions.  More curious if the issue is worth fixing or not (and.. apologies for not chiming in earlier).  @cubuspl42 , do you think it's worth fixing? If so, why?  Thx

**Comment by neil-marcellini** [comment] 2024-04-01 22:23
I'm going to un-assign for now to #focus. Please add me back after a proposal is approved.

**Comment by dubielzyk-expensify** [comment] 2024-04-01 23:04
Ideally they'd both be syncronized, but I don't view this as a massive deal and even if it's perfectly in tact I'm not sure the experience is that much better as a result. Happy to have @Expensify/design chime in here. (View the video and see that the LHN animates away quicker than the main area)

**Comment by cubuspl42** [comment] 2024-04-02 07:28
@mallenexpensify 

> do you think it's worth fixing? If so, why? Thx

The process is constructed this way so that the C+ team is not in a position to question the rationale for classifying the issue as worth fixing. I believe that this is a question to the BugZero team.

**Comment by trjExpensify** [comment] 2024-04-02 15:36
> I agree this is low priority, but can't hurt to fix it so that the exiting motion of deleting the workspace feels more smooth.

Agree with this. I think it's a low polish item for wave-collect, but worth fixing so the workspace editor feels like "one". I'd reduce the bounty to $250 personally as it's pretty minor. 👍

**Comment by mallenexpensify** [comment] 2024-04-03 00:31
The job has already been posted at $500 and has proposals above. If they're not excepted I'll reduce to $250. 

@cubuspl42 are any of the above proposals acceptable?

**Comment by cubuspl42** [comment] 2024-04-03 11:18
@tienifr 

> After the fix above, there'll be a regression described in RCA

This is the behavior tested on the `main` branch:

https://github.com/Expensify/App/assets/2590174/8dac74d1-9b8f-4459-b744-488a867470a0

So unless I'm missing something, the discussed behavior is not a regression.

**Comment by cubuspl42** [comment] 2024-04-03 11:20
@mallenexpensify 
> are any of the above proposals acceptable?

The proposal by @ZhenjaHorbach is simple and straight to the point.

It's suggested that it introduces a regression (in what I'd call a corner case), but as I discuss above, I can't see how it's a regression.

**Comment by cubuspl42** [comment] 2024-04-03 11:47
@mallenexpensify 

I'll let you handle this one.

- The proposal by @ZhenjaHorbach is acceptable and solves the issue as described
- The proposal by @tienifr builds on top of the former one, improving the experience in two more corner cases
  - From my perspective, any additional change brings a regression risk, while the no. 1 priority of the C+ team is to minimize regressions while solving the issue

**Comment by mallenexpensify** [comment] 2024-04-05 22:57
This is an edge case and one I haven't seen often. We don't have anything specifically documented in CONTRIBUTING.md or in our internal process doc for C+.  
 
Can you add 🎀 and request a review of both proposals from an engineer?  They'll have more context than I on which is best.

**Comment by cubuspl42** [comment] 2024-04-06 06:28
Sure, I thought you might want to focus on the user-observable scope of the proposals. I can go through the process without any problem.

I approve [the proposal](https://github.com/Expensify/App/issues/38922#issuecomment-2018330590) by @ZhenjaHorbach, as it solves the problem as described, with a minimal change.

C+ reviewed 🎀 👀 🎀

**Comment by mallenexpensify** [comment] 2024-04-10 00:16
👀 on the proposal above plz @dangrous

**Comment by dangrous** [comment] 2024-04-10 17:59
Hi! I'm still on parental leave - I'm not sure why @MelvinBot assigned me. I'll be back part time starting Friday but if you need someone before then might be good to see if another engineer can take it on - sorry for the trouble!

**Comment by mallenexpensify** [comment] 2024-04-12 18:06
@dangrous , since it's Friday now, please review when you have time (guessing it'll be next week)
Def weird you were assigned, unsure why

**Comment by dangrous** [comment] 2024-04-12 21:09
Looking today!

**Comment by mallenexpensify** [comment] 2024-04-12 22:40
I propose we hire @tienifr for the fix because it expands on the original proposal by @ZhenjaHorbach to cover additional cases. 
I propose we compensate @ZhenjaHorbach $250 because the they were the first to outline the core of the solution.   

Before moving forward. @tienifr and @ZhenjaHorbach can you 👍 here if you both agree? If so, I'll assign to both of you (so I don't forget to pay both) and @tienifr can raise the PR

Thx for the patience and the feedback from everyone.

**Comment by mallenexpensify** [comment] 2024-04-15 22:35
Assigned to @tienifr and @ZhenjaHorbach .  If you haven't been already been invited to the job, please apply
https://www.upwork.com/jobs/~0173bde0810a3af269

**Comment by mallenexpensify** [comment] 2024-04-24 00:29
Automation wasn't working so I updated.

**Comment by mallenexpensify** [comment] 2024-05-01 02:42
Contributor: @ZhenjaHorbach paid $250 via Upwork
Contributor: @tienifr owed $500 via Upwork
Contributor+: @cubuspl42 owed $500 via Upwork 

@tienifr and @cubuspl42 
can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0173bde0810a3af269

Testrail GH created
- https://github.com/Expensify/Expensify/issues/392231

**Comment by mallenexpensify** [comment] 2024-05-07 20:41
@tienifr paid, commented above. 
@cubuspl42 , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0173bde0810a3af269

**Comment by cubuspl42** [comment] 2024-05-09 15:22
I'm sorry for the delay, I accepted my pending offers

**Comment by mallenexpensify** [comment] 2024-05-09 18:41
@cubuspl42 paid, payment comment updated above. 
Thanks all!

**Closed by mallenexpensify** 2024-05-09 18:41 UTC
Labels: External, Engineering, Daily, Design, Awaiting Payment, Bug
