### ISSUE TITLE
[HOLD for payment 2024-05-03] Unable to load categories in the workspace settings

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#40875] opened 2024-04-24 12:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.65-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713951624767449

## Action Performed:
Break down in numbered steps

1. Have a collect policy on the beta
2. This policy should have categories set up
3. Sign into this account
4. Go to the workspace settings
5. Go to Categories page

## Expected Result:
Describe what you think should've happened

the categories list should load without issues

## Actual Result:
Describe what actually happened

Infinite spinner is showing

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/36083550/9c2ade1e-8795-48ef-ac10-081cca559e68)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-04-24 12:31
reverting https://github.com/Expensify/App/pull/40496/files fixes the issue

**Comment by s77rt** [comment] 2024-04-24 12:51
This is a known problem https://github.com/Expensify/App/pull/39132#discussion_r1571085835 It seems that https://github.com/Expensify/App/pull/40375 didn't fix it

**Comment by s77rt** [comment] 2024-04-24 12:52
cc @hayata-suenaga

**Comment by hayata-suenaga** [comment] 2024-04-24 14:57
PR was merged. requesting cherry pick -> https://expensify.slack.com/archives/C07J32337/p1713970530252449

**Comment by sonialiap** [comment] 2024-05-02 13:30
@abekkala I'm OOO 2024-05-03 to 2024-05-06 so adding a BZ buddy to issue payment if I'm out when it becomes due

**Comment by abekkala** [comment] 2024-05-02 19:56
@sonialiap - what is the payment summary? 

@mountiny it looks like you provided the fix and @s77rt did the PR review, correct? Was that a **$250** PR review or some other amount?

**Comment by s77rt** [comment] 2024-05-02 22:58
No payment is needed here since it was a regression

**Comment by abekkala** [comment] 2024-05-07 14:26
Handing this one back to you @sonialiap as you're back from ooo

**Comment by s77rt** [comment] 2024-05-07 15:37
This can be closed

**Closed** 2024-05-07 17:06 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
