### ISSUE TITLE
[$500] Chat - Three-dot menu is redundant for deleted root message with threads

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34992] opened 2024-01-23 19:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to any chat
2. Send a message and also reply in thread
3. Delete the parent message
4. Return to the main chat
5. Hover over the deleted parent message
6. Click 3-dot menu

## Expected Result:
3-dot menu should not appear when the 3-dot menu options are the same as the hover menu

## Actual Result:
3-dot menu is present when the 3-dot menu options are the same as the hover menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/38676533-c33f-4e64-a59f-bad33e4fa2ed

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f7369ff9642cdfd4</li>
        <li>Upwork Job ID: 1749877073496403968</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-23 19:31
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by paultsimura** [comment] 2024-01-23 19:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For deleted report actions, a 3-dot menu is visible

### What is the root cause of that problem?
We show the 3-dot menu for any report action on the mini context menu:

https://github.com/Expensify/App/blob/6b9cea1a70714aee48423a5fa997e0536259cc64/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L500-L504

### What changes do you think we should make in order to solve the problem?
We should update the shouldShow condition to hide it for deleted actions:

```js
        shouldShow: (type, reportAction, isArchivedRoom, betas, anchor, isChronosReport, reportID, isPinnedChat, isUnreadChat, isOffline, isMini) => {
            const isDeletedAction = ReportActionsUtils.isDeletedAction(reportAction);
            return isMini && !isDeletedAction;
        },
```



### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-23 20:05
## Proposal
Updated proposal https://github.com/Expensify/App/issues/34992#issuecomment-1906809330 – swapped main and alternative solutions.

**Comment by Bilal-Khursheed** [comment] 2024-01-23 22:35
@lanitochka17  I have reviewed your issue and confidently can say that i can fix it also saw other issues too and able to fix those too..
Per mentioned the solution we will replace 3 dots action with button shown separately and will remove or will hide 3 dots until we are done with what we are expecting 

Thanks do contact me on my email mailto:bilal.khursheed617@gmail.com

**Comment by paultsimura** [comment] 2024-01-25 11:47
> bump for review ^^

@laurenreidexpensify according to Slack status, @thesahindia is currently out sick.

**Comment by esh-g** [comment] 2024-01-25 14:01
Yes @paultsimura this should be fixed by that

**Comment by arosiclair** [comment] 2024-01-25 17:07
Alright I'll close this as a dupe for now. Be sure to include testing steps to verify this is also fixed @esh-g

**Closed by arosiclair** 2024-01-25 17:07 UTC
Labels: External, Daily, Help Wanted, Bug
