### ISSUE TITLE
[HOLD for payment 2024-06-20] [$125] [Invoice Rooms] Remove the option to allow users to update `Who can post` in invoice rooms

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#41476] opened 2024-05-02 04:14 UTC
Right now users can update who can post in invoice rooms from All members to Admins only. We do not restrict this to admins only ever in invoice rooms so we should not make it an option to change. We still do want to display the field Who can post but just make it so it says All members and remove the ability to change it. 

For reference, [we also just updated](https://github.com/Expensify/App/pull/41380) the invoice room settings to remove the Room name and Visibility altogether. Those will not be present at all. 

Please let me know if there are any other questions. Assigning this a low clean up as I don't think it is super urgent. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a363c4047d94da6</li>
        <li>Upwork Job ID: 1790255428707074048</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by Nodebrute** [comment] 2024-05-02 05:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
] [Invoice Rooms] Remove the option to allow users to update Who can post in invoice rooms
### What is the root cause of that problem?
Feature request
### What changes do you think we should make in order to solve the problem?

Add isInvoiceRoom = ReportUtils.isInvoiceRoom(report) to WriteCapabilityPage.tsx, then use this check to adjust the writeCapabilityOptions, so that only the 'all members' option is passed when it's a invoice room.
https://github.com/Expensify/App/blob/729c9ac733e721132b7b9792e6c3e146e8eac41c/src/pages/settings/Report/WriteCapabilityPage.tsx#L34-L39
### What alternative solutions did you explore? (Optional)

**Comment by neonbhai** [comment] 2024-05-02 05:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove the option to allow users to update Who can post in invoice rooms

### What is the root cause of that problem?
Feature Request

### What changes do you think we should make in order to solve the problem?
We will update the `shouldAllowWriteCapabilityEditing` here to also account for `!isInvoiceReport(report)`

https://github.com/Expensify/App/blob/729c9ac733e721132b7b9792e6c3e146e8eac41c/src/libs/ReportUtils.ts#L5720-L5722

**Comment by JmillsExpensify** [comment] 2024-05-14 05:39
Looks like the labels weren't added, so I just added them now.

**Comment by rushatgabhane** [comment] 2024-05-14 06:14
let's go with @neonbhai's [proposal](https://github.com/Expensify/App/issues/41476#issuecomment-2089619249) because they're first 🎀 👀 🎀

**Comment by neonbhai** [comment] 2024-05-15 02:01
[PR](https://github.com/Expensify/App/pull/42179) is ready for review!

**Comment by rushatgabhane** [comment] 2024-05-20 20:30
reviewing

**Comment by rushatgabhane** [comment] 2024-05-20 20:31
in review, will be merged after freeze is lifted

**Comment by jliexpensify** [comment] 2024-06-12 00:03
Payment Summary

- C: @neonbhai $125
- C+: @rushatgabhane $125 (ND payment) - waiting on checklist

[Upwork job](https://www.upwork.com/jobs/~014a363c4047d94da6)

**Comment by JmillsExpensify** [comment] 2024-06-13 03:23
$125 approved for @rushatgabhane

**Comment by rushatgabhane** [comment] 2024-06-16 13:23
1. Go to green `+` > Send invoice.
            3. Create an invoice with any detail.
            4. Go to the invoice room. Click the workspace chat header.
            5. Go to Setting.
            6. Verify "Who can post" is not clickable.

**Comment by jliexpensify** [comment] 2024-06-17 00:01
[Payment summary](https://github.com/Expensify/App/issues/41476#issuecomment-2161820286)

**Comment by jliexpensify** [comment] 2024-06-20 23:48
[stupid annoying upworks closed the job, here is a new one.](https://www.upwork.com/jobs/~017097bffcc6bea1ba)

@neonbhai have re-invited you.

**Comment by neonbhai** [comment] 2024-06-21 05:19
Thank you @jliexpensify, I've accepted the offer

**Comment by jliexpensify** [comment] 2024-06-21 08:49
Thanks! Paid and job closed.

@rushatgabhane here's the [Payment Summary](https://github.com/Expensify/App/issues/41476#issuecomment-2161820286) for your ND payment.

**Closed by jliexpensify** 2024-06-21 08:49 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
