### ISSUE TITLE
[$250] Workspace - Admin is unable to transfer ownership of a workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52697] opened 2024-11-18 12:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.63-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sing in to staging.new.expensify.com with a new gmail account
2. Create a workspace
3. Add a user to the workspace and set them as Admin
4. Login as the user that was set as admin
5. Navigate to the workspace settings > Members
6. Click over the owner of the workspace
7. Click on the button to transfer ownership
8. Enter valid payment card details - these can be found in 1Password under "Expensify Card - Applause Backup" or "Expensify Card - Applause" in the form
9. Click on " Accept terms and Payment card"

## Expected Result:
Workspace ownership is transferred and "Owner" label is displayed on the previous admin.

## Actual Result:
An error modal is opened with a message " Oops! Not so fast.. There was a problem transferring ownership of this workspace."

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6d377676-e583-44d5-8b1a-4125a580072f
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859674479318939830</li>
        <li>Upwork Job ID: 1859674479318939830</li>
        <li>Last Price Increase: 2024-12-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by me-ZaidAli** [comment] 2024-11-22 11:44
@IuliiaHerets How can I access card creds to test this? can you please mention card creds over here if you can so that I can debug the issue?.

**Comment by me-ZaidAli** [comment] 2024-11-22 12:24
I think the api is failing for this one please do look into logs to check if there's any API fail.

**Comment by ahmedGaber93** [comment] 2024-11-25 11:13
I will try to reproduce it today.

**Comment by ahmedGaber93** [comment] 2024-12-02 12:53
@garrettmknight I am not able to pass this [step](https://github.com/Expensify/App/issues/52697#issuecomment-2505948902) right now, but ant more this error is displaying based on data that comes from backend side `errorFields` and `isChangeOwnerFailed`, So I think this should be internal

https://github.com/Expensify/App/blob/f837a0cc662bb196eeaf8b8f79d101da55c6de97/src/pages/workspace/members/WorkspaceOwnerChangeWrapperPage.tsx#L42-L47

**Comment by ahmedGaber93** [comment] 2024-12-02 17:46
Update about reproducing, Now I can pass this step https://github.com/Expensify/App/issues/52697#issuecomment-2505948902, but the issue is not reproduced with me on the latest main on DEV

I trimmed the video to hide the card details

https://github.com/user-attachments/assets/dfbc7b8f-118e-4aac-8e0f-854c655c83b8

**Comment by garrettmknight** [comment] 2024-12-06 18:34
I'll test this out on Monday.

**Comment by garrettmknight** [comment] 2024-12-09 18:40
Just tested, worked perfectly for me now. Closing!

**Closed by garrettmknight** 2024-12-09 18:40 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
