### ISSUE TITLE
[HOLD for payment 2023-10-20] [$125]  Split bill - Date and merchant are not saved when splitting bill

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29458] opened 2023-10-12 15:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:**  Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Scan > Upload a receipt
3. Select Split on any user > Next
4. Enter description, date and merchant
5. Create the bill split
6. Click on the bill split preview

## Expected Result:
Date and merchant are saved

## Actual Result:
Date and merchant are not saved

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/0a1d263a-eaee-422b-8c6a-a1a9a041bd6e

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127c47ff7ea605892</li>
        <li>Upwork Job ID: 1712521065352839168</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 27165235</li>
<li>akinwale | Contributor | 27165585</li>
</ul></li>
    </ul>
</details>

**Comment by abekkala** [comment] 2023-10-12 15:47
@lanitochka17 can you please link the slack conversation and the video of recreating this bug?

**Comment by lanitochka17** [comment] 2023-10-12 15:52
@abekkala Hello You can see the video in the Screenshots/Videos tab
![image](https://github.com/Expensify/App/assets/78819774/7e14fca5-e79c-4477-84a0-b6029e4b813a)

**Comment by mountiny** [comment] 2023-10-12 17:35
Flat $125, this is a simple fix. When se call the StartSplitbill with the receipt, we do not pass the created or date, we only pass the description.

Lets hide those two fields in case of Split with receipt creation

**Comment by mountiny** [comment] 2023-10-12 18:05
@bernhardoj Can you please raise a pr with urgency

**Comment by mountiny** [comment] 2023-10-12 22:17
Fixed 
<img width="384" alt="image" src="https://github.com/Expensify/App/assets/36083550/898c5ebb-8c4c-4bcb-a558-df5f29488abb">

**Comment by akinwale** [comment] 2023-10-18 05:41
@abekkala Just noting that the PR for this issue was initially deployed to production on [2023-10-13](https://github.com/Expensify/App/issues/29458#issuecomment-1762361009) since it was a deploy blocker, so the payment due date should be 2023-10-20. There were some issues with deploys so Melvin's been a bit confused lately.

I will complete the BZ checklist on Friday, the 20th.

Thanks.

**Comment by abekkala** [comment] 2023-10-19 14:53
PAYMENTS TO BE MADE OCT 20

- Issue reported by: Applause - Internal Team [NO PAYMENT]
- @akinwale [$125] [offer](https://www.upwork.com/nx/wm/offer/27165585) (Contributor)
- @bernhardoj [$125] [offer](https://www.upwork.com/nx/wm/offer/27165235) (Contributor)

**Comment by akinwale** [comment] 2023-10-20 11:43
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Split bills with scan requests are handled differently in the backend, but the logic was not implemented in the app.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression test**
1. Launch Expensify
2. Open the global create menu, and select Request money
3. Select the Scan tab if it is not already active
4. Click Upload a receipt
5. Select Split on any user and click Next
6. Verify that only the Description field is visible

Do we agree 👍 or 👎?

**Comment by akinwale** [comment] 2023-10-20 11:49
> ### PAYMENTS TO BE MADE OCT 20
> * Issue reported by: Applause - Internal Team [NO PAYMENT]
> * @akinwale [$125] [offer](https://www.upwork.com/nx/wm/offer/27165585) (Contributor)
> * @bernhardoj [$125] [offer](https://www.upwork.com/nx/wm/offer/27165235) (Contributor)

I believe the issue is also eligible for the 50% bonus. Thanks.

**Comment by abekkala** [comment] 2023-10-20 14:01
@akinwale yes, you are correct! 

### PAYMENTS TO BE MADE OCT 20

- Issue reported by: Applause - Internal Team [NO PAYMENT]
- @akinwale [$125 + $62.50 bonus] [offer](https://www.upwork.com/nx/wm/offer/27165585) (Contributor)
- @bernhardoj [$125 +  $62.50 bonus] [offer](https://www.upwork.com/nx/wm/offer/27165235) (Contributor)

**Comment by abekkala** [comment] 2023-10-20 14:04
@akinwale [$125 + $62.50 bonus] payment made and contract ended - Thank you! 🎉 

@bernhardoj [$125 + $62.50 bonus] payment made and contract ended - Thank you! 🎉

**Comment by abekkala** [comment] 2023-10-20 14:06
All set!
Closing

**Closed by abekkala** 2023-10-20 14:06 UTC
Labels: External, Daily, Awaiting Payment, Bug
