### ISSUE TITLE
[hold for #11768] Clicking back button from a thread leads to LHN instead of chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19575] opened 2023-05-25 02:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat with a thread 
2. Open the thread
3. Click on the device back button and notice the behavior
4. Go back into the thread again
5. Click on the back button at the top left corner of the app

## Expected Result:
Clicking on the back button should take user back to the chat where the thread originated just like clicking on the device back button does.
 ## Actual Result:
The back button at the top left corner of the app takes user to LHN instead of taking user to the chat where the thread originated

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9b80423d-f5dc-4430-a044-59123f50442d

https://github.com/Expensify/App/assets/43996225/44a34f9b-6b90-458b-9c87-2e4b2371f67b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1684825878210559
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01584956baa0c6eefe</li>
        <li>Upwork Job ID: 1661841587393507328</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by payal-lathidadiya** [comment] 2023-05-25 13:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking back button from a thread opens LHN instead of parent chat report 

### What is the root cause of that problem?
Chat threads are created as child report.
From report screen, we're navigating to back using `Navigation.goBack` [code here](https://github.com/Expensify/App/blob/main/src/pages/home/ReportScreen.js#LL296) which redirects to previous route.

### What changes do you think we should make in order to solve the problem?

Change `onNavigationMenuButtonClicked` prop in `ReportScreen` component to Navigate to child report if current report is child report
```js
onNavigationMenuButtonClicked={
    () => 
        this.props.report.parentReportID 
            ? Navigation.navigate(ROUTES.getReportRoute(this.props.report.parentReportID)) 
            : Navigation.goBack()
}
```

### What alternative solutions did you explore? (Optional)
Alternatively, we could also modify `HeaderView` component instead [here](https://github.com/Expensify/App/blob/main/src/pages/home/HeaderView.js#L130) with logic to redirect to parentReport in case of navigation from child report
```js
onPress={
    ()=> props.report.parentReportID 
        ? Navigation.navigate(ROUTES.getReportRoute(props.report.parentReportID))
        : props.onNavigationMenuButtonClicked()
}
 ```

**Comment by joekaufmanexpensify** [comment] 2023-05-25 21:06
I can reproduce this, but not sure if it's a bug, or was a a feature we descoped to launch more quickly. Confirming [here. ](https://expensify.slack.com/archives/C01SKUP7QR0/p1685048738217459)

**Comment by joekaufmanexpensify** [comment] 2023-05-25 21:08
Confirmed this is a bug. We're going to keep this internal.

**Comment by joekaufmanexpensify** [comment] 2023-05-25 21:13
Turns out this is going to be fixed by the navigation reboot, so holding this until [that](https://github.com/Expensify/App/issues/11768) is complete. Then, we'll verify this is fixed, and close it out!

**Comment by joekaufmanexpensify** [comment] 2023-06-19 13:32
@stitesExpensify @Santhosh-Sellavel I think the navigation reboot is done now. So I should retest this to see if it's now fixed, right?

**Comment by stitesExpensify** [comment] 2023-06-19 15:23
Yep, that would be great!

**Comment by joekaufmanexpensify** [comment] 2023-06-26 12:53
Retested and this is working as expected now! Closing as this is all set. No reporting bonus is needed here as this was already a part of the navigation reboot before this was reported.

**Closed by joekaufmanexpensify** 2023-06-26 12:53 UTC
Labels: Monthly, Internal, Bug
