### ISSUE TITLE
[HOLD for payment 2024-01-09] [$500] Chat - Single line code blocks are not vertically centered

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31427] opened 2023-11-16 10:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Pre-requisite: user must be logged in.

1. Go to any chat.
2. Send a single line code block (like `test`)

## Expected Result:
The text inside the block should be centered.

## Actual Result:
The text is horizontally centered, but not vertically, is closer to the bottom.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6278669_1700114885241!IMG_E1595](https://github.com/Expensify/App/assets/115492554/1f9ab530-20b2-46d5-9ab3-3cb0d08d9029)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0173268787598947ed</li>
        <li>Upwork Job ID: 1725103891916292096</li>
        <li>Last Price Increase: 2023-12-01</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 28013519</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-11-16 17:16
This is dupe of https://github.com/Expensify/App/issues/8132

**Comment by trjExpensify** [comment] 2023-11-16 17:24
I agree. Closing!

**Comment by shubham1206agra** [comment] 2023-11-24 12:58
> @trjExpensify @shubham1206agra , this issue is about the text alignment inside the code block and the other one is for alignment of the whole code block alignment.

I see. Thanks for pointing out this, @Krishna2323.

**Comment by trjExpensify** [comment] 2023-11-29 17:28
@thesahindia thoughts?

**Comment by trjExpensify** [comment] 2023-12-04 11:38
Let's add the `Design` label to the PR for a review of this by the design team as well. (CC: @shawnborton).

**Comment by trjExpensify** [comment] 2023-12-08 11:41
@robertjchen over to you for a secondary proposal review please!

**Comment by trjExpensify** [comment] 2023-12-11 11:02
Cool, sounds good! @tienifr once you have the PR ready for review, don't forget to add the `Design` label :)

**Comment by trjExpensify** [comment] 2023-12-13 22:02
PR is still in draft, right?

**Comment by trjExpensify** [comment] 2023-12-14 23:34
Cool! Putting this back on external as the draftPR is up

**Comment by trjExpensify** [comment] 2023-12-18 12:16
@tienifr reckon you'll be able to get the PR into review in the next couple of days?

**Comment by NicMendonca** [comment] 2024-01-09 17:14
BZ Payment summary: 
- Contributor: @tienifr - paid through Upwork
- Contributor +: @thesahindia - paid through Expensify

**Comment by NicMendonca** [comment] 2024-01-09 17:15
@tienifr you've been paid! @thesahindia don't forget to request payment via Expensify and complete [the BZ checklist.](https://github.com/Expensify/App/issues/31427#issuecomment-1874681319)

**Comment by trjExpensify** [comment] 2024-01-12 00:42
Still awaiting the checklist!

**Comment by robertjchen** [comment] 2024-01-15 22:35
Awaiting completion of BZ checklist

**Comment by NicMendonca** [comment] 2024-01-17 17:59
fab ! thanks!

**Comment by JmillsExpensify** [comment] 2024-01-22 16:32
@NicMendonca Can you add specific payment amounts to [this summary](https://github.com/Expensify/App/issues/31427#issuecomment-1883462086)?

**Comment by NicMendonca** [comment] 2024-01-22 20:17
> BZ Payment summary: 
> - Contributor: @tienifr - $500 paid through Upwork
> - Contributor +: @thesahindia - $500  paid through Expensify

**Comment by JmillsExpensify** [comment] 2024-01-22 20:23
$500 approved for @thesahindia based on the comment above.

**Closed by JmillsExpensify** 2024-01-22 20:23 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
