### ISSUE TITLE
[$250] Workspace - Inbox briefly displayed when creating WS from selector and going back

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50850] opened 2024-10-16 07:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5088507&group_by=cases:section_id&group_order=asc&group_id=296775
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on the workspace selector on the top left corner.
3. Tap on the "+" icon to add a new workspace.
4. Once navigated to workspace menu, tap on the arrow on the top left corner.
5. Verify you are redirected to workspace selector again.

## Expected Result:
After the workspace is created and the user should be navigated to the new workspace menu, and when the back arrow is tapped, the app should return to workspace selector.

## Actual Result:
When the user lands on new workspace menu and tap the back arrow to return to workspace selector, the inbox is displayed for a second, before the user lands on selector again.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e09bb819-9eee-4cd6-a43e-52ce9faa4567

https://github.com/user-attachments/assets/323abdf3-e4d0-4fcf-b676-787d04336f0c
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849140571510923303</li>
        <li>Upwork Job ID: 1849140571510923303</li>
        <li>Last Price Increase: 2024-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>huult | Contributor | 104756734</li>
<li>dominictb | Contributor | 104771074</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by IuliiaHerets** [comment] 2024-10-16 07:38
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-10-16 07:39
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by skg0525** [comment] 2024-10-24 20:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the user lands on new workspace menu and tap the back arrow to return to workspace selector, the inbox is displayed for a second, before the user lands on selector again.

### What is the root cause of that problem?
We are reseting the navigation to home before we navigate to workspace-switcher. and hence for a second we see inbox for a second

https://github.com/Expensify/App/blob/a53705da129d1398725fa4464cb64e7f53168e2f/src/pages/workspace/WorkspaceInitialPage.tsx#L380-L381

### What changes do you think we should make in order to solve the problem?

We need to remove Navigation.resetToHome(); from WorkspaceInitialPage.tsx and

modify WorkspaceSwitcherPage to remove 
Navigation.goBack and add Navigation.resetToHome instead
https://github.com/Expensify/App/blob/a53705da129d1398725fa4464cb64e7f53168e2f/src/pages/WorkspaceSwitcherPage/index.tsx#L168


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by huult** [comment] 2024-10-28 08:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inbox briefly displayed when creating WS from selector and going back

### What is the root cause of that problem?

The reason we briefly see Inbox is that when we tap the back arrow, the function called includes `Navigation.resetToHome();`. As a result, Inbox appears for a short time before we proceed to call `Navigation.isNavigationReady().then(() => Navigation.navigate(route.params?.backTo as Route));` to navigate to the workspace switcher.
https://github.com/Expensify/App/blob/5103b4bd53ae74dcb301b8450f7046e82dc311d3/src/pages/workspace/WorkspaceInitialPage.tsx#L378-L382

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should navigate directly to the workspace switcher without calling `Navigation.resetToHome();` to avoid seeing the Inbox. After reaching the workspace switcher, when we go back, we can add `Navigation.resetToHome();` to return to the home screen. Something like this:
```diff
//.src/pages/workspace/WorkspaceInitialPage.tsx#L380
        onBackButtonPress={() => {
              if (route.params?.backTo) {
-                  Navigation.resetToHome();
-                  Navigation.isNavigationReady().then(() => Navigation.navigate(route.params?.backTo as Route));
+                  Navigation.isNavigationReady().then(() => Navigation.navigate(`${route.params?.backTo}?resetToHome=true` as Route));
              } else {
                  Navigation.dismissModal();
              }
          }}

//.src/pages/WorkspaceSwitcherPage/index.tsx#L38
-        function WorkspaceSwitcherPage() {
+        function WorkspaceSwitcherPage({route: {params}}) {

//.src/pages/WorkspaceSwitcherPage/index.tsx#L93
    const selectPolicy = useCallback(
        (option?: WorkspaceListItem) => {
            ...
+            if (params?.resetToHome === 'true') {
+                Navigation.resetToHome();
+            }
            ...
        },
        [activeWorkspaceID, setActiveWorkspaceID],
    );

//.src/pages/WorkspaceSwitcherPage/index.tsx#L168
-        onBackButtonPress={Navigation.goBack}
+        onBackButtonPress={() => {
+              if (params?.resetToHome === 'true') {
+                  Navigation.resetToHome();
+              }
+              Navigation.goBack();
+        }}      
```

<details><summary>POC</summary>

https://github.com/user-attachments/assets/2d22933a-6ad9-4051-a0fa-d0366807308a

</details>

**Comment by huult** [comment] 2024-10-29 01:26
@aimane-chnaif Yes, I will improve the next proposal.

**Comment by huult** [comment] 2024-10-30 00:07
@aimane-chnaif Yes, sure. I tested the case you mentioned, and my proposal worked.

**Comment by huult** [comment] 2024-11-01 00:05
> @huult are you able to find any regression with that solution?

@aimane-chnaif Yes, the other proposal has an issue: when we are on the search page, open the workspace switcher, and click the back arrow, it resets to the home page. That’s why, in my proposal, I use params to determine whether we need to reset to the home page or not

<details><summary>Video</summary>

https://github.com/user-attachments/assets/8c553b47-586b-405d-9074-7ab8022fea45

</details>

**Comment by huult** [comment] 2024-11-05 04:36
Waiting for @puneetlath

**Comment by mvtglobally** [comment] 2024-11-08 15:26
Issue not reproducible during KI retests. (First week)

**Comment by huult** [comment] 2024-11-19 09:05
@dominictb I think this ticket is still valid because we have the Get Started case where, if we don't have any workspace, we can create a workspace (click get started) in the same way as using the plus icon. Therefore, I believe the PR is still valid and ready to be merged. I will test that case once the server is back.

**Comment by huult** [comment] 2024-11-19 09:13
@dominictb I tested, and we have an issue when going back. Do you agree that we continue with this pull request?

https://github.com/user-attachments/assets/f01770d9-239b-40c8-9b08-638bb77d63a3

**Comment by huult** [comment] 2024-11-20 04:50
I made a mistake. This is not related to this ticket, so I will close this pull request. Thank you.

**Comment by huult** [comment] 2024-11-21 14:14
@puneetlath FYI

**Comment by puneetlath** [comment] 2024-11-25 21:54
Ah interesting ok.

**Comment by puneetlath** [comment] 2024-11-25 21:56
Ok, I've paid out the contracts. Closing. Thanks y'all!

**Closed by puneetlath** 2024-11-25 21:56 UTC
Labels: Reviewing, External, Weekly, Bug
