### ISSUE TITLE
[HOLD for payment 2024-07-02] Thread - App crashes after rejoining thread and opening thread header

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44196] opened 2024-06-22 12:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a message and also send a reply in thread
4. In thread, click 3-dot menu > Leave
5. Go to the thread again
6. Click Join
7. Immediately click on the chat header after rejoining the thread
8. Wait for the crash

## Expected Result:
App will not crash

## Actual Result:
App crashes after rejoining thread and opening thread header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d099334c-c766-4a7d-b6bd-189991d861b4

[logs (2).txt](https://github.com/user-attachments/files/15936576/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by lanitochka17** [comment] 2024-06-22 12:43
@iwiznia  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-22 12:43
We think that this bug might be related to #vip-vsp

**Comment by huult** [comment] 2024-06-22 16:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App crashes

### What is the root cause of that problem?

This issue occurred because `sortedAllReportActions` is `undefined`, and we are checking the condition `sortedAllReportActions.length`. Since `sortedAllReportActions` is `undefined`, there are pending merge operations for the key during the first connection, as shown in the image below:

<img width="1704" alt="Screenshot 2024-06-22 at 22 39 28" src="https://github.com/Expensify/App/assets/20178761/c2e6f98f-d87c-49b2-ae95-cd8512f4d032">
<img width="1100" alt="Screenshot 2024-06-22 at 22 39 47" src="https://github.com/Expensify/App/assets/20178761/a7ca51b6-a044-4b34-8110-3a2f2c727082">

To fix this issue, we need to validate if `sortedAllReportActions` is `undefined` before checking its length in [reportActions](https://github.com/Expensify/App/blob/main/src/pages/ReportDetailsPage.tsx#L89), as shown in the code below:

```diff
// src/pages/ReportDetailsPage.tsx#L89
const reportActions = useMemo(() => {
- if (!sortedAllReportActions.length) {
+ if (sortedAllReportActions === undefined || !sortedAllReportActions.length) {
  return [];
 }
 return ReportActionsUtils.getContinuousReportActionChain(sortedAllReportActions);
}, [sortedAllReportActions]);
```


<details>
<summary>POC</summary>


</details>

### What changes do you think we should make in order to solve the problem?

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2024-06-24 10:23
Asked @fabioh8010 to look into this as he has been working on the useOnyx changes

**Comment by iwiznia** [comment] 2024-06-24 12:52
@fabioh8010 any update here?	

Also, why didn't ts catch this earlier? Isn't this type of error exactly the ones TS should be catching before they are merged?

**Comment by mountiny** [comment] 2024-06-24 13:05
Here is the [thread btw](https://expensify.slack.com/archives/C0593T50UHG/p1719221492295069)

**Comment by fabioh8010** [comment] 2024-06-24 13:09
@iwiznia @mountiny My investigations so far:

- I was able to reproduce on Staging, **and on `main` only if I enable Staging server.**
- Yes TS is catching and actually showing that `sortedAllReportActions` is `ReportAction[]` because we defined a `selector` and we are always returning an an array inside it. From TS perspective everything is correct.
- Yet `sortedAllReportActions` is being `undefined` in this particular situation that shouldn't be possible, I'm still investigating why it's happening (now it will be easier because I was able to reproduce on `main`)

**Comment by fabioh8010** [comment] 2024-06-24 14:05
**Update:** The problem is inside `useOnyx`.. looking for a fix.

**Comment by bfitzexpensify** [comment] 2024-07-02 13:45
Payment summary:

@situchan due $250 for PR review to be paid via manual request

**Closed by bfitzexpensify** 2024-07-02 13:45 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug

**Comment by situchan** [comment] 2024-07-02 17:55
@bfitzexpensify I am still using upwork

**Comment by situchan** [comment] 2024-07-11 18:54
> @bfitzexpensify I am still using upwork

kind bump ^

**Comment by bfitzexpensify** [comment] 2024-07-12 09:48
Apologies @situchan! 

Offer sent via Upwork.
