### ISSUE TITLE
[HOLD for payment 2024-12-19] [HOLD for payment 2024-12-17] iOS - Expense - App returns to transaction thread when trying to replace receipt, then freezes

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53848] opened 2024-12-10 12:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch ND or hybrid app.
2. Go to workspace chat.
3. Submit an expense with receipt.
4. Go to transaction thread.
5. Tap on the receipt.
6. Tap 3-dot menu > Replace.

## Expected Result:
Replace receipt page will open.

## Actual Result:
App returns to transaction thread, then app freezes.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/605059b6-dc9e-4026-9612-58de008894a8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by mkzie2** [comment] 2024-12-10 15:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App returns to transaction thread, then app freezes.

### What is the root cause of that problem?
It comes from https://github.com/Expensify/App/pull/53108. On IOS, we call `onModalClose` with a delay then we navigate to the scan page first then we call `dismissModal` [here](https://github.com/Expensify/App/blob/c8e8517e872c6a9dd739d2745ddd302058ac64de/src/pages/TransactionReceiptPage.tsx#L56). That cause we go back to the `TransactionReceiptPage` and now the modal is hidden which is the freeze.

https://github.com/Expensify/App/blob/c8e8517e872c6a9dd739d2745ddd302058ac64de/src/components/AttachmentModal.tsx#L388


https://github.com/Expensify/App/blob/c8e8517e872c6a9dd739d2745ddd302058ac64de/src/libs/AttachmentModalHandler/index.ios.ts#L11-L15


### What changes do you think we should make in order to solve the problem?
We should only call `onModalClose` with a delay when it's not receipt attachment

```
if (!isEmptyObject(report) && !isReceiptAttachment) {
     attachmentModalHandler.handleModalClose(onModalClose); 
} else {
    onModalClose();
}
```
https://github.com/Expensify/App/blob/c8e8517e872c6a9dd739d2745ddd302058ac64de/src/components/AttachmentModal.tsx#L388
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)



**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by huult** [comment] 2024-12-10 16:02
@Beamanator Can we add InteractionManager.runAfterInteractions for each onClose event instead of using it within AttachmentModal?

**Comment by Beamanator** [comment] 2024-12-10 16:12
Mmmmm i mean yeah if that would be cleaner, that would work well! But using it within `AttachmentModal` like suggested above might make it so we don't have to remember to wrap `onClose` outside of `AttachmentModal` in the future, right?

**Comment by huult** [comment] 2024-12-10 16:15
@Beamanator Yes, you are correct

**Comment by luacmartins** [comment] 2024-12-10 19:06
Confirmed this is fixed in staging

**Comment by zanyrenney** [comment] 2024-12-16 10:08
@youssef-lr is anyone due for payment here? I'm not really sure!

**Comment by zanyrenney** [comment] 2024-12-19 17:24
Closing, as this is only Yousef and me as assignees, payment is not due. Thank you for your hard work, @youssef-lr!

**Closed by zanyrenney** 2024-12-19 17:24 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
