### ISSUE TITLE
[$250] Distance -Unable to edit distance rate as field missing for gmail users in submit expense pg

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41442] opened 2024-05-01 19:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** kiatest.78+mass@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition : Gmail account user has created WS, enabled distance rates & has added few more distance rates in settings
1. Log in with gmail account on ND site
2. Tap on + FAB >> select Submit Expense option
3. Select Distance request >> Enter Start & Stop waypoints >> tap Next button
4. Select any Workspace chat
5. User navigated to submit expense page (Note : Look for distance rate field to edit it)

## Expected Result:
Gmail users should be able to change distance rate in submit expense page for distance request as it similarly displayed for Expensifail account users

## Actual Result:
Unable to edit distance rate as field missing for gmail users in submit expense page
Note: Rate option is available for Expensifail accounts in submit page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/397ce5bc-55f5-47fb-923e-0603dd27d264

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be16b10f66e59bc6</li>
        <li>Upwork Job ID: 1787963260196671488</li>
        <li>Last Price Increase: 2024-05-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by lanitochka17** [comment] 2024-05-01 19:25
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-05-02 10:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance -Unable to edit distance rate as field missing for gmail users in submit expense pg

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?


We need to create new field in Distance rate page (Like we did in other pages)

<img width="677" alt="Screenshot 2024-05-02 at 17 10 13" src="https://github.com/Expensify/App/assets/161821005/55105f74-7ce8-416b-806d-dd71b52f48d9">




When click on Default distance Rate, we will navigate user to distanceRateSelector page (Like we did in other pages)

<img width="387" alt="Screenshot 2024-05-02 at 17 07 40" src="https://github.com/Expensify/App/assets/161821005/a5f5b000-b9bb-460c-a1a0-d0ed49c6d225">

When user click another distance rate we will update the distance rate of this policy. We also need to update how we get default distance rate. 

### What alternative solutions did you explore? (Optional)

**Comment by eh2077** [comment] 2024-05-08 11:48
@nkdengineer Do you mean add a rate editing option in this page?
<img width="311" alt="image" src="https://github.com/Expensify/App/assets/117511920/6c61877f-22a4-41e5-80b9-d81950f1c874">

**Comment by eh2077** [comment] 2024-05-09 04:23
I think this is **_not a bug_** as the feature is behind beta `p2pDistanceRequests`

<img width="600" alt="image" src="https://github.com/Expensify/App/assets/117511920/34189cc1-ed69-409f-9cab-1a7f478c1823">

cc @johncschuster @lanitochka17

**Comment by eh2077** [comment] 2024-05-14 20:25
@johncschuster @lanitochka17 Friendly bump on this https://github.com/Expensify/App/issues/41442#issuecomment-2101908682

**Comment by johncschuster** [comment] 2024-05-15 20:08
@lanitochka17 are you testing using an account that is on the beta? If not, can you give that a try to see if the outcome is different?

**Comment by lanitochka17** [comment] 2024-05-16 23:53
@johncschuster Hello

Checked in the staging 
Issue is still reproducible

https://github.com/Expensify/App/assets/78819774/943fd40f-f0be-4c95-b1d6-97c615a346d1

**Comment by johncschuster** [comment] 2024-05-17 14:46
@lanitochka17 Thanks for checking! And just to confirm, you are on the beta, right?

**Comment by lanitochka17** [comment] 2024-05-17 14:56
@johncschuster This is not a beta version.

**Comment by eh2077** [comment] 2024-05-18 01:08
@lanitochka17 Did you test this with an account has `p2pDistanceRequests` beta added?

**Comment by eh2077** [comment] 2024-05-21 16:03
> @lanitochka17 Did you test this with an account has `p2pDistanceRequests` beta added?

@lanitochka17 bump!

**Comment by johncschuster** [comment] 2024-05-21 22:03
Bumped in Slack

**Comment by mvtglobally** [comment] 2024-05-22 00:19
This is tested with Gmail account and without any BETAs. 
Do we need to retest with Expensifail account ?

**Comment by eh2077** [comment] 2024-05-23 15:17
@johncschuster Can you help to check if `p2pDistanceRequests` is behind betas?

**Comment by eh2077** [comment] 2024-05-28 16:02
Posted on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1716912107265609) to get more eyes.

**Comment by neil-marcellini** [comment] 2024-05-28 18:03
It’s a bit confusing because selecting a workspace rate doesn’t feel exactly like it’s part of P2P, but it is part of that project and is hidden behind the beta for now. This is not a bug so I'm closing it.

**Closed by neil-marcellini** 2024-05-28 18:03 UTC
Labels: External, Daily, Help Wanted, Bug
