### ISSUE TITLE
[HOLD for BZ checklist] [$2000] Android - Add Phone number UI not consistent - reported by @gadhiyamanan

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11087] opened 2022-09-19 04:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to setting > profile > Add phone number
2. click on password
3. check send validation button

## Expected Result:
Send validation button should not be hidden 

## Actual Result:
Send validation button is hidden

## Platform:

- Android

**Version Number:** 1.1.99-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**
https://user-images.githubusercontent.com/43995119/190951528-cf5f7ee0-d6e4-43f6-8f4f-3c38f89d6ab7.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661685271625409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment] 2022-09-20 16:13
I can't reproduce on mobile because I am running on iOS. The workflow looks like fine on iOS though. Either way, what's shown on Android should mirror what's shown in iOS
![IMG_BF83BBE593B2-1](https://user-images.githubusercontent.com/6643649/191310316-db53bfb5-912b-4edb-95b7-47ee4c51afbc.jpeg)

**Comment by cead22** [comment] 2022-09-26 22:08
This is by design. The button should be disabled because the password hasn't been entered

**Comment by cead22** [comment] 2022-09-26 22:09
@davidcardoza if you don't understand the issue or can't reproduce it, ask for clarification before assigning to engineering, or simply close the issue

**Comment by gadhiyamanan** [comment] 2022-09-28 05:03
@cead22 in android, when you click on a phone number user can see the button but when you click on the password keyboard will hidden

**Comment by cead22** [comment] 2022-09-28 20:06
@gadhiyamanan can you double check if when you click password and the button appears hidden, if you can scroll down and see the button? I think it's possible the button isn't hidden, but rather, the keyboard we show for the password is taller than the one we show for the phone number, and it's covering the button, but the button isn't really disappearing. 

If you can confirm the button is actually gone and you can't scroll down and see it, please reopen this issue

**Comment by gadhiyamanan** [comment] 2022-09-29 07:19
@cead22 not able to scroll down, first I need to close the keyboard  

the button disappears only for the password field and is reproducible only on android

**Comment by luacmartins** [comment] 2022-10-03 20:58
@cead22 I think an external contributor can work on fixing this bug. Would you be against removing the demolition label and making this external?

**Comment by cead22** [comment] 2022-10-04 00:49
Not at all, go for it

**Comment by Santhosh-Sellavel** [comment] 2022-10-05 15:50
This is related to keyboard hiding content, @tgolen this should be held right?

**Comment by tgolen** [comment] 2022-10-05 20:54
Yes! It is. I've tested this exact flow with some of my recent changes and I'm pretty certain I'll have it fixed.

**Comment by tgolen** [comment] 2022-10-10 17:07
Putting this on HOLD for now.

**Comment by tgolen** [comment] 2022-10-24 13:33
This is still on HOLD while I try to get https://github.com/Expensify/App/pull/11586 merged. That will then allow this to be opened up for proposals again.

**Comment by tgolen** [comment] 2022-10-31 16:46
This is no longer on hold and can have proposals created for it with the new code.

**Comment by abekkala** [comment] 2022-11-02 11:45
https://www.upwork.com/ab/applicants/1587772488630054912/job-details

https://www.upwork.com/jobs/~015814913e9779f5c9

**Comment by FilipRado** [comment] 2022-11-02 12:32
I will fix your layout to use only 'position:absolute'.
And then it will change by keyboardaware events.

**Comment by JmillsExpensify** [comment] 2022-11-02 19:54
@abekkala Given that we're still early and no proposals have been accepted, I'm assigning myself per the new BZ process: https://stackoverflow.com/c/expensify/questions/14597/14598#14598.

**Comment by Santhosh-Sellavel** [comment] 2022-11-02 20:00
@FilipRado Please go through our past [issues](https://github.com/Expensify/App/issues?q=is%3Aclosed+label%3A%22Awaiting+Payment%22) and learn how to write a proper proposal.

Also checkout out our [guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) to understand our process

**Comment by JmillsExpensify** [comment] 2022-11-06 20:20
Still waiting for proposals.

**Comment by JmillsExpensify** [comment] 2022-11-08 19:49
Still waiting for proposals. Increasing the price to $500.

**Comment by huzaifa-99** [comment] 2022-11-12 14:25
Not reproduceable in v1.2.27-3

**Comment by Julesssss** [comment] 2022-11-14 10:26
Hi @Expensify/applause, could we please retest this? Thanks

**Comment by kbecciv** [comment] 2022-11-14 14:17
@Julesssss Re-testing, update you shortly

**Comment by kbecciv** [comment] 2022-11-14 14:35
Issue is reproduced with device Realme 6 / Android 11 (build 1.2.27.1)

https://user-images.githubusercontent.com/93399543/201687018-0701c1aa-3bdb-4701-a0af-0cfcf2d52276.mp4

**Comment by Julesssss** [comment] 2022-11-14 14:41
I'm also seeing this on `1.2.27-1`. Leaving open for proposals, while we await the next deploy.

**Comment by JmillsExpensify** [comment] 2022-11-14 15:06
> Though I also wonder if the phone validation is incorrect 🤔

I'm not following what you mean here? I must have missed it in the video and screenshot.

**Comment by JmillsExpensify** [comment] 2022-11-14 15:06
Separately, we're still open for proposals and the price is now doubled to $1,000.

**Comment by Julesssss** [comment] 2022-11-14 16:32
@JmillsExpensify I meant that in my reproduction case, perhaps the button wasn't shown because of failing phone validation -- rather than because of a bug

**Comment by JmillsExpensify** [comment] 2022-11-14 17:18
Oh gotcha. I'm with you now. I'll have to circle back on that part, though the Applause video/reproduction gives me confident that we should resolve the erratic behavior with the keyboard / validate button.

**Comment by tgolen** [comment] 2022-11-16 21:53
still looking for proposals

**Comment by JmillsExpensify** [comment] 2022-11-17 05:41
This would be great for Margelo or an internal engineer at this point. We're still struggling to get proposals.

**Comment by Santhosh-Sellavel** [comment] 2022-11-21 14:54
Still looking for proposals!

**Comment by JmillsExpensify** [comment] 2022-11-21 17:29
Yep! It's Monday, and it's been exactly a week, so we're raising the price of this issue to $2,000 to help encourage a proposal.

**Comment by pecanoro** [comment] 2022-11-21 22:55
I am going to try and take a look, this is caused definitely because we are changing the keyboard type when jumping from the phone number field to the password one. I will check tomorrow if I can figure it out but maybe the intricacies of keyboard layouts is too much for me.

**Comment by JmillsExpensify** [comment] 2022-11-22 07:21
Thanks @pecanoro for jumping in!

**Comment by pecanoro** [comment] 2022-11-23 03:52
Ok, I figured out the cause, it's a actually [bug](https://github.com/facebook/react-native/issues/28004) with React Native and it does not seem to have a fix. However, I noticed that not passing the prop to the component fixes the issue on Android and does not break the others, so I am going to do that.

**Comment by JmillsExpensify** [comment] 2022-11-26 22:02
Nice work linking all the related issues in Slack. We can take the discussion there for now, as it's still on-going.

**Comment by pecanoro** [comment] 2022-11-28 16:29
After a discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1669197511103729), @0xmiroslav will be taking over with their proposal, I can take the CME role in this one instead.

**Comment by JmillsExpensify** [comment] 2022-11-28 18:36
Pulling from the Slack discussion, I wanted to clarify that the next steps are:

 - @tgolen has been added to this issue to help review the PR
 - @0xmiroslav has an approved proposal and is now assigned to this issue. 

Let's get that PR merged in 3 days! As a reminder that triggers a 50% bonus.

**Comment by JmillsExpensify** [comment] 2022-11-29 06:41
Agree with @0xmiroslav this isn't the regression.

**Comment by JmillsExpensify** [comment] 2022-12-01 06:18
Alright, PR is merged and already on production. This qualifies for 50% bonus. 

@tgolen @pecanoro Mind helping clarify what's going on there? We need to align on what the regression period officially started and ended. 

Coming back to the payouts, this is where we're at:

 - Contributor: @0xmiroslav $3,000 (incl. 50% bonus)
 - Contributor+: @Santhosh-Sellavel $3,000 (incl. 50% bonus)
 - Issue reporter: @gadhiyamanan $250

[Upwork job](https://www.upwork.com/jobs/~015814913e9779f5c9) is here. Can all individuals above please apply so you can be hired and paid out when the time comes?

**Comment by JmillsExpensify** [comment] 2022-12-01 06:18
Reminder for myself: Still need to come back to the regression test evaluation.

**Comment by pecanoro** [comment] 2022-12-01 15:38
@JmillsExpensify The PR its production [yesterday](https://github.com/Expensify/App/pull/13106#issuecomment-1331628851), so I am assuming the regression period starts from that moment.

**Comment by JmillsExpensify** [comment] 2022-12-05 13:12
@Santhosh-Sellavel @gadhiyamanan Can both of you please make sure to apply for the Upwork job. The correct amounts [are here](https://github.com/Expensify/App/issues/11087#issuecomment-1333268824). T

Separately, @Santhosh-Sellavel @pecanoro it would be good to get a head start on the checklist above. Can you check the boxes please and confirm we're good there. I'll separately get started on the regression tests. 

Thanks all!

**Comment by gadhiyamanan** [comment] 2022-12-05 13:16
Applied, thanks

**Comment by pecanoro** [comment] 2022-12-05 17:37
@Santhosh-Sellavel @tgolen We could link the PR when the KeyboardAvoidingView behavior for Android was introduced but I think we always had keyboard issues and this wasn't a new bug but inconsistent behavior of the keyboard itself, right? Unless I am missing something of course.

**Comment by Santhosh-Sellavel** [comment] 2022-12-05 18:35
Yeah this existed even before that PR #11586

**Comment by JmillsExpensify** [comment] 2022-12-10 02:01
Everyone is paid out at this point. Updating the title to clarity I need to create the regression test issue. Won't be able to get to that today.

**Comment by JmillsExpensify** [comment] 2022-12-12 12:43
@Santhosh-Sellavel @pecanoro @tgolen Regression test is a work in progress and linked to the larger set of keyboard tests we'll kick off as part of the KAV initiative. Accordingly, I've marked the regression test off above. I'm OOO this week, so can you all fill out your part of the BugZero checklist above and then close this issue out? Thank you!

**Comment by tgolen** [comment] 2022-12-12 15:37
BZ checklist is done so I will close this out.

**Closed by tgolen** 2022-12-12 15:37 UTC
Labels: External, Engineering, Weekly, Improvement, Awaiting Payment, Bug

**Comment by mallenexpensify** [comment] 2022-12-28 20:00
Coming from https://github.com/Expensify/App/issues/10483#issuecomment-1366885045
We've decided to issue @0xmiroslav a bonus of $1000 because their PR fixed many bugs.  I have made the payment on the job  https://www.upwork.com/jobs/~015814913e9779f5c9
