### ISSUE TITLE
[HOLD for payment 2024-04-25] [LOW] [Splits] [$500]  Split bill - Currency for split bill via Scan is USD instead of local currency

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29709] opened 2023-10-16 19:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-7
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29664
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to group chat > + > Split bill > Manual
3. Note that the currency is the local currency
4. Go to Scan > Upload a photo
5. Select Split with a few users and split the bill
6. Open the split preview and click Amount
7. Create a Scan request (1:1)
8. Go to Scan details page > Amount
9. Note that the currency is also local currency

## Expected Result:
In Step 6, when editing the amount for split bill, the currency should be in the local currency

## Actual Result:
In Step 6, when editing the amount for split bill, the currency is USD. While the currency in Manual split bill (Step 2) and 1:1 Scan request (Step 8) follows the local currency

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/8193c984-2317-4ba0-ba79-e8f1218dc1c8

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eec1820774133ef4</li>
        <li>Upwork Job ID: 1716906523802828800</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @marcochavezf</details>

**Comment by sicarius97** [comment] 2023-10-16 21:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
USD instead of local currency shown when starting a split on a receipt

### What is the root cause of that problem?
It looks to me like in the code below the currency is set to the constant USD rather than the local currency being passed down in the startSplitBill function:

https://github.com/Expensify/App/blob/22874c719767a23aa795ae09a4030c4890c542e7/src/libs/actions/IOU.js#L1294-L1336

### What changes do you think we should make in order to solve the problem?
Instead of setting the currency to be a constant we could add a variable to the startSplitBill function like so:
```
function startSplitBill(participants, currentUserLogin, currentUserAccountID, comment, receipt, existingSplitChatReportID = '', currency = CONST.CURRENCY.USD) {
```

And then on the money request confirmation page, pass down the users local currency like so:
```
IOU.startSplitBill(
                        selectedParticipants,
                        props.currentUserPersonalDetails.login,
                        props.currentUserPersonalDetails.accountID,
                        trimmedComment,
                        receipt,
                        existingSplitChatReportID,
                        props.iou.currency
                    );
```
So that it reflects the local currency like in other areas

**Comment by Victor-Nyagudi** [comment] 2023-10-17 12:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Split bill - Currency for split bill via Scan is USD instead of local currency

### What is the root cause of that problem?

When splitting a bill, the optimistic transaction's currency is set to USD (line 1310). 

https://github.com/Expensify/App/blob/be44c93037fe165d6e3aec7445044c371bcbc921/src/libs/actions/IOU.js#L1308-L1319

In addition, the back end also sends us the currency as USD.

<details>

<summary>Images of network request and split bill transaction</summary>

![expensify-RHP-split-bill-bug](https://github.com/Expensify/App/assets/79470910/d2cd7371-e646-455e-9704-33dc29d3163e)

![expensify-split-bill-bug-network-request](https://github.com/Expensify/App/assets/79470910/e12f02e5-94a9-4ee2-b81a-393fe8345fc8)

</details>

### What changes do you think we should make in order to solve the problem?

I propose two solutions. 

- Option 1

First, add a `currency` parameter at the end of the [`startSplitBill()`](https://github.com/Expensify/App/blob/be44c93037fe165d6e3aec7445044c371bcbc921/src/libs/actions/IOU.js#L1294) function.

```javascript
function startSplitBill(participants, currentUserLogin, currentUserAccountID, comment, receipt, existingSplitChatReportID = '', currency) {
```

Next, pass the `props.iou.currency` to [`startSplitBill()`](https://github.com/Expensify/App/blob/be44c93037fe165d6e3aec7445044c371bcbc921/src/pages/iou/steps/MoneyRequestConfirmPage.js#L201-L208) method call in `MoneyRequestConfirmPage`, similar to what happens in [a regular money request](https://github.com/Expensify/App/blob/be44c93037fe165d6e3aec7445044c371bcbc921/src/pages/iou/steps/MoneyRequestConfirmPage.js#L185).

```javascript
IOU.startSplitBill(
    selectedParticipants,
    props.currentUserPersonalDetails.login,
    props.currentUserPersonalDetails.accountID,
    trimmedComment,
    receipt,
    existingSplitChatReportID,
    props.iou.currency // <- Added
);
```

Finally, replace `CONST.CURRENCY.USD` with this currency in [`splitTransaction`](https://github.com/Expensify/App/blob/be44c93037fe165d6e3aec7445044c371bcbc921/src/libs/actions/IOU.js#L1310C9-L1310C27).

```javascript
const splitTransaction = TransactionUtils.buildOptimisticTransaction(
    0,
    currency, // <- currency replaced
    CONST.REPORT.SPLIT_REPORTID,
    comment,
    '',
    '',
    '',
    CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT,
    receiptObject,
    filename,
);
```

This solution improves consistency with what happens in a regular money request. 

- Option 2

Since we already have [the current user's personal details](https://github.com/Expensify/App/blob/be44c93037fe165d6e3aec7445044c371bcbc921/src/libs/actions/IOU.js#L104), we can leverage this and replace `CONST.CURRENCY.USD` with `currentUserPersonalDetails.localCurrencyCode`.

```javascript
const splitTransaction = TransactionUtils.buildOptimisticTransaction(
    0,
    currentUserPersonalDetails.localCurrencyCode, // <- currency replaced
    CONST.REPORT.SPLIT_REPORTID,
    comment,
    '',
    '',
    '',
    CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT,
    receiptObject,
    filename,
);
```

This second option has lesser changes. 

Either of these solutions addresses the front end issue, but as you can see from the following video, the back end changes the currency back to USD, so a change will need to happen over there too. 

<details>

<summary>Video of back end changing the currency back to USD</summary>

https://github.com/Expensify/App/assets/79470910/2238cbe7-a79a-475f-8612-b9c4a77ba3a2

</details>

Another indicator of a back end issue is if you test either of my proposed solutions offline, the currency stays at the local one.

<details>

<summary>Video of solution tested while offline</summary>

https://github.com/Expensify/App/assets/79470910/a18d2c6b-1f63-433e-a2e7-ba3a88052dcc

</details>

Once you go back online, the currency is reverted back to USD. 

<details>

<summary>Video of back end changing the currency back to USD when coming back online</summary>

https://github.com/Expensify/App/assets/79470910/91a3f68d-be1a-4640-8ba6-512adfc518e9

</details>

### What alternative solutions did you explore? (Optional)

I thought about making one of my two proposed solutions an alternative, but I figured I'd propose them together since the difference between them isn't that great.

**Comment by sourcecodedeveloper** [comment] 2023-10-19 16:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The currency for Splt bill scan option is set to USD rather than local currency.

### What is the root cause of that problem?
The transaction currency is set to USD instead of the local currency.

### What changes do you think we should make in order to solve the problem?
In IOU.js, when loading allTransactions from Onyxdb, check each transaction to ensure currency matches local currency. The local currency can be obtained from currentUserPersonalDetails.


```
if(currentUserPersonalDetails.localCurrencyCode !=undefined && currentUserPersonalDetails.localCurrencyCode != val.currency)
{
    val.currency = currentUserPersonalDetails.localCurrencyCode;
    Onyx.merge(`${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, val);     
}
```

Video attached

https://github.com/Expensify/App/assets/141340971/340c28cd-2cd4-4982-9e04-9076f73533fb


### What alternative solutions did you explore? (Optional)

**Comment by sourcecodedeveloper** [comment] 2023-10-19 17:01
@aimane-chnaif please review [proposal](https://github.com/Expensify/App/issues/29709#issuecomment-1771371887)

**Comment by anmurali** [comment] 2023-10-24 19:57
@aimane-chnaif can you review proposals and pick one so we can proceed?

**Comment by marcochavezf** [comment] 2023-11-02 18:59
Oops I've been swamped with some higher priorities.

**Comment by marcochavezf** [comment] 2023-11-06 20:19
No update

**Comment by marcochavezf** [comment] 2023-11-09 18:15
No update, focused on other higher priority items atm

**Comment by marcochavezf** [comment] 2023-11-13 20:28
No update

**Comment by marcochavezf** [comment] 2023-11-14 15:44
No update, still addressing other daily items

**Comment by marcochavezf** [comment] 2023-11-16 03:34
No update

**Comment by marcochavezf** [comment] 2023-11-20 19:57
No update

**Comment by marcochavezf** [comment] 2023-11-21 22:45
Moving this to weekly to focus on wave7

**Comment by marcochavezf** [comment] 2023-12-01 16:37
No update, still focused on critical items for wave7

**Comment by marcochavezf** [comment] 2023-12-11 19:36
No update

**Comment by marcochavezf** [comment] 2023-12-20 19:07
No update

**Comment by marcochavezf** [comment] 2023-12-29 19:11
No update

**Comment by marcochavezf** [comment] 2024-01-09 00:45
Focused on wave issues, no update

**Comment by marcochavezf** [comment] 2024-01-17 19:09
No update, probably this GH can probably be part of VIP project

**Comment by marcochavezf** [comment] 2024-01-29 17:30
No update, focused on wave work

**Comment by marcochavezf** [comment] 2024-02-07 16:49
No update

**Comment by anmurali** [comment] 2024-02-16 16:17
Adding BZ backup but this is still lower priority than waves so makes sense

**Comment by marcochavezf** [comment] 2024-02-19 18:17
Still focused on wave work. I'm going to move it to weekly meanwhile

**Comment by marcochavezf** [comment] 2024-02-28 17:01
No update, focused on critical and high-priority wave tasks

**Comment by marcochavezf** [comment] 2024-03-08 00:30
No update

**Comment by marcochavezf** [comment] 2024-03-18 18:14
No update, focused on higher priority tasks/bugs

**Comment by marcochavezf** [comment] 2024-04-01 19:19
I checked it out, and yes, we need a backend fix for this first. I created a few PRs to update the currency and quickly created a frontend PR to test the changes. The frontend PR includes part of the proposals from @sicarius97 and @Victor-Nyagudi, so we can split the compensation after the PR is deployed to production.

**Comment by Santhosh-Sellavel** [comment] 2024-04-13 18:20
@marcochavezf please Assign me this issue for tracking payment

**Comment by anmurali** [comment] 2024-04-23 10:58
@aimane-chnaif - offer is [here](https://www.upwork.com/nx/wm/offer/101988796).
Can you please also let us know if we need to add a regression test and if yes - lay out the steps.

**Comment by Santhosh-Sellavel** [comment] 2024-04-23 16:50
@anmurali I've reviewed this PR https://github.com/Expensify/App/pull/39373 Can you assign me issue the please?

**Comment by Victor-Nyagudi** [comment] 2024-04-25 08:43
@marcochavezf Is the payment going to be split 50/50?

**Comment by Victor-Nyagudi** [comment] 2024-05-02 11:19
Bump @anmurali for payment so we can close this out.

**Comment by anmurali** [comment] 2024-05-15 02:49
Not overdue

**Comment by Santhosh-Sellavel** [comment] 2024-05-22 18:12
Requested on ND

**Comment by anmurali** [comment] 2024-05-22 21:00
@aimane-chnaif is paid
@sicarius97 - I still need your Upwork profile to send you an offer.

**Comment by JmillsExpensify** [comment] 2024-05-31 04:32
$250 approved for @Santhosh-Sellavel

**Closed** 2024-06-04 01:43 UTC
Labels: Engineering, Daily, Internal, Overdue, Awaiting Payment, Bug
