### ISSUE TITLE
[HOLD for 0xmiroslav] [$1000] Web - Subscript avatar not showing in workspace chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21996] opened 2023-06-30 20:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login A account with policyExpenseChat beta enabled
2. Invite B to any workspace that has custom workspace avatar
3. On A, Go to B's policy expense chat
(custom workspace avatar (not default avatar) is key to reproduce)

## Expected Result:
Workspace avatar should show as subscript

## Actual Result:
 No subscript avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d8b1c084-b151-4362-af57-1a2bb70b78e1

https://github.com/Expensify/App/assets/93399543/55d9a706-c1b7-4d96-b003-d97358d23f06

**Expensify/Expensify Issue URL:**
**Issue reported by:** @0xmiroslav
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688056702660869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192a425ecc8391c30</li>
        <li>Upwork Job ID: 1679109827603726336</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-06-30 20:16
Heading OoO for the week (back July 10) so re-assigning this in the meantime 👍

**Comment by jeet-dhandha** [comment] 2023-07-01 06:23
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
- Subscript Avatar is not visible when an image is uploaded.

### What is the root cause of that problem?
- Root cause is that the `imageStyles` property is being passed as `null` to `Avatar` component in `SubscriptAvatar` component.

### What changes do you think we should make in order to solve the problem?
- Passing `imageStyles` as `[styles.avataravatarSmall]` property to `Avatar` component fixes the issue.
<details>
<summary>Code Changes:</summary>

```diff
function SubscriptAvatar(props) {
   ...rest code
    return (
        ...rest code
                    <Avatar
                        ...rest params
                    />
        ...rest code
                    <Avatar
-                       imageStyles={null}
+                       imageStyles={[styles.avatarSmall]}
                        ...rest params
                    />
        ...rest code
    );
}
```

</details>

After change:
<img width="301" alt="Screenshot 2023-07-01 at 11 50 17 AM" src="https://github.com/Expensify/App/assets/78416198/6eb92acd-2f23-4427-ae9a-4d0f640fad01">

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by JmillsExpensify** [comment] 2023-07-05 12:43
Slammed with bug reports. I'll close the loop on these today.

**Comment by Christinadobrzyn** [comment] 2023-07-05 17:52
@0xmiroslav would you be able to confirm if this GH is the same? https://github.com/Expensify/App/issues/22241

**Comment by JmillsExpensify** [comment] 2023-07-12 12:46
Re-assigning @0xmiroslav per the comment above.

**Comment by jeet-dhandha** [comment] 2023-07-13 05:50
@JmillsExpensify Might i be eligible for providing root cause and solution first.

**Comment by JmillsExpensify** [comment] 2023-07-24 22:10
Ok circling back on this. @0xmiroslav I consider that example you provided to be in line with review, so I'm going to issue $1k for now. Please raise in #contributor-plus in Slack if you disagree or would like a wider discussion.

**Comment by JmillsExpensify** [comment] 2023-08-02 04:28
Coming back to this issue, @0xmiroslav are you handling this payment via NewDot?

**Comment by JmillsExpensify** [comment] 2023-08-08 02:58
Not a problem. Please reach out to me directly via NewDot if you'd like me to act quickly on payment, happy to help.

**Comment by JmillsExpensify** [comment] 2023-08-16 13:51
Still holding

**Comment by JmillsExpensify** [comment] 2023-08-30 05:45
Still waiting for payment next steps.

**Comment by JmillsExpensify** [comment] 2023-09-07 01:47
Are we good to pay this one out yet?

**Comment by JmillsExpensify** [comment] 2023-09-13 07:50
Still holding.

**Comment by JmillsExpensify** [comment] 2023-09-25 22:34
@0xmiroslav should we still hold for payment?

**Comment by JmillsExpensify** [comment] 2023-10-10 20:23
Similar to other issues, I'm going to close this issue since I'm overwhelmed with GH assignments. Please reach out to us when you are ready for payment.

**Closed** 2023-10-10 20:23 UTC
Labels: Engineering, Daily, Monthly, Internal, Bug
