### ISSUE TITLE
[HOLD for payment 2023-12-08] [$500] Chat - Page scrolls to the middle conversation when collapse expended compose box

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31005] opened 2023-11-07 15:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to any chat
3. Enter 10 or more lines of text so the scroller is visible
4. Click on double-arrow button to expand the text
5. Click on double-arrow button to collapse the text

## Expected Result:
Last bottom lines should be visible and vertical scroller should be down to the latest message

## Actual Result:
Page scrolls to the middle conversation when collapse expended compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/57fe36f5-70f6-4bd5-8957-56f4727a5a39

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018067138b68673af0</li>
        <li>Upwork Job ID: 1721908499530989568</li>
        <li>Last Price Increase: 2023-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27651162</li>
</ul></li>
    </ul>
</details>

**Comment by NisargDeveloper** [comment] 2023-11-07 15:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Page scrolls in the middle of a conversation. It scroll should be in the end and shows the latest messages.

### What is the root cause of that problem?

It seems we don't have the css property.

```
.your-text-box {
  overflow-y: scroll;
  scroll-behavior: smooth;
}
```

Once we have overflow-y: scroll. It will stay in the end no matter how big the text-box is.

### What changes do you think we should make in order to solve the problem?


We have to add
```
 .your-text-box {
  overflow-y: scroll;
  scroll-behavior: smooth;
}
```
 in the css property.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by FitseTLT** [comment] 2023-11-07 15:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Page scrolls to the middle conversation when collapse expended compose box
### What is the root cause of that problem?
When collapse is pressed the scrollTop will stay to the value when it was expanded which is less than the scroll height
### What changes do you think we should make in order to solve the problem?

We need to manually scroll to bottom when user presses collapse
### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2023-11-07 16:50
I can reproduce - I think this can be external. I swear I've seen this issue reported already but I can't find it.

**Comment by Christinadobrzyn** [comment] 2023-11-08 21:33
@rushatgabhane we have a few proposals, would you be able to take a review?

**Comment by Christinadobrzyn** [comment] 2023-11-10 22:40
DMing @rushatgabhane for a review of the proposals

**Comment by rushatgabhane** [comment] 2023-11-13 01:28
I like @tienifr's [proposal](https://github.com/Expensify/App/issues/31005#issuecomment-1799116065) 
C+ reviewed 🎀 👀 🎀

**Comment by chiragsalian** [comment] 2023-11-13 19:19
Proposal LGTM, feel free to create the PR @tienifr.

**Comment by Christinadobrzyn** [comment] 2023-11-20 05:13
I'm going ooo until Monday Nov 27th so going to assign another BZ teammate to monitor this until I'm back. Thanks!

status: reviewing PR

**Comment by Christinadobrzyn** [comment] 2023-11-27 20:13
I'm back so I'll take this. Thanks Cortney! 

Looks like we're reviewing the [PR](https://github.com/Expensify/App/pull/31298) so this can be moved back to weekly.

**Comment by Christinadobrzyn** [comment] 2023-12-06 01:29
prepping for payment! 

Payouts due:

Issue Reporter: NA
Contributor: $500 @tienifr (in Upwork)
Contributor+: $500 @rushatgabhane (in NewExpensify)

Eligible for 50% #urgency bonus? N

Upwork job is [here](https://www.upwork.com/jobs/~018067138b68673af0)

@rushatgabhane do we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2023-12-09 14:59
No regressions so paying this out @tienifr I paid you based on this [payment summary](https://github.com/Expensify/App/issues/31005#issuecomment-1841928887). 

@rushatgabhane can you let us know about any regression tests? Thanks!

**Comment by Christinadobrzyn** [comment] 2023-12-12 22:07
nudge - @rushatgabhane can you let us know about any regression tests?

**Comment by Christinadobrzyn** [comment] 2023-12-14 23:09
nudge @rushatgabhane - do we need a regression test?

**Comment by rushatgabhane** [comment] 2023-12-18 13:24
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment] 2023-12-18 13:25
manual request here - https://staging.new.expensify.com/r/5195421093804697

**Comment by Christinadobrzyn** [comment] 2023-12-19 19:32
Awesome! thanks @rushatgabhane! I created the regression test GH - https://github.com/Expensify/Expensify/issues/352202

Closing this!

**Closed by Christinadobrzyn** 2023-12-19 19:32 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-12-26 21:58
$500 payment approved for @rushatgabhane based on [this comment](https://github.com/Expensify/App/issues/31005#issuecomment-1841928887).
