### ISSUE TITLE
[HOLD for payment 2023-08-24] [$2000] mWeb - Chat - emoji picker presents glitches while scrolling with the keyboard open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22939] opened 2023-07-15 14:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22680
## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Navigate to any chat.
3. Tap on Emoji button in composer
4. Enter a term that has no results
5. Scroll up and down slowly

## Expected Result:
The emoji picker should be stable when scrolling up and down

## Actual Result:
The emoji picker looks unstable and presents glitches while scrolling with the keyboard open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/271f759b-720d-437d-bc3b-eab39541a3ca

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Interanl Team

**Slack conversation:*
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bdc44dc552114d99</li>
        <li>Upwork Job ID: 1682463762946265088</li>
        <li>Last Price Increase: 2023-08-03</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 26030445</li>
</ul></li>
    </ul>
</details>

**Comment by maddylewis** [comment] 2023-07-18 15:57
asking about this here - https://expensify.slack.com/archives/C01GTK53T8Q/p1689695810701009

**Comment by maddylewis** [comment] 2023-07-21 18:53
added external label / added to Upwork

**Comment by maddylewis** [comment] 2023-07-24 17:15
there are no proposals on this one yet

**Comment by maddylewis** [comment] 2023-07-27 13:41
i'll double the bounty for this one!

**Comment by Piotrfj** [comment] 2023-07-28 09:07
Hi I'm Piotr from Callstack - expert contributor group - will start investigation in this area

**Comment by s-alves10** [comment] 2023-07-28 11:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Emoji Picker presents glitches while scrolling with the keyboard open

### What is the root cause of that problem?

As you can see, we calculate the menu height when windowHeight props changes. When scrolling, windowHeight may change several times and it shows glitches every time height is recalculated.
https://github.com/Expensify/App/blob/b2381f6c60acd4beca34b83c65a898eefb0594d6/src/components/EmojiPicker/EmojiPickerMenu/index.js#L529

This is the root cause.

### What changes do you think we should make in order to solve the problem?

I think preventing scrolling would be a perfect solution.
In order to do that, update the flatlist style as follows

```
        style={[
            StyleUtils.getEmojiPickerListHeight(isFiltered, this.props.windowHeight),
            {overscrollBehavior: 'contain', pointerEvents: 'box-none'},
            {overflow: this.state.filteredEmojis.length > 72 ? 'auto' : 'hidden'},
        ]}
```

This works fine.

**Note**
We use specific number 72(9 rows of emojis) here, but we might need to get exact number from the menu height

### What alternative solutions did you explore? (Optional)

**Comment by sobitneupane** [comment] 2023-08-02 17:14
Thanks for the proposal @s-alves10. The solution you are proposing looks interesting and might solve the issue. Can you please explain it in words as well. What are those variables you are proposing and what's the logic behind each calculation?

Please let me know once you update the proposal.

**Comment by s-alves10** [comment] 2023-08-02 22:28
## Proposal
[Updated](https://github.com/Expensify/App/issues/22939#issuecomment-1655555722)

@sobitneupane 
I've added some explanation to the proposal

**Comment by sobitneupane** [comment] 2023-08-04 14:36
@s-alves10 Thanks for the update.

> As you can see, we calculate the menu height when windowHeight props changes. When scrolling, windowHeight may change several times and it shows glitches every time height is recalculated.

@s-alves10 Oh yes. I did test it and windowHeight is changing abruptly. What's the reason behind that?

**Comment by s-alves10** [comment] 2023-08-04 15:19
@sobitneupane 

> I did test it and windowHeight is changing abruptly. What's the reason behind that?

This is because iOS Safari has a feature called "elastic scrolling" which causes the window height to change when scrolling. This is done to give the user a more natural and tactile feel when scrolling through a webpage or app.

**Comment by maddylewis** [comment] 2023-08-06 18:23
I am OOO until ~ August 20. 

- @sobitneupane let us know about this comment here - https://github.com/Expensify/App/issues/22939#issuecomment-1665776435
- and then, if you don't think @s-alves10's proposal will solve this one, want to start a convo in #expensify-open-source? https://github.com/Expensify/App/issues/22939#issuecomment-1666593979

thanks!

**Comment by sobitneupane** [comment] 2023-08-09 03:14
Sorry for the delay.

I will review the update by EOD.

**Comment by sobitneupane** [comment] 2023-08-09 11:16
Thanks for the update @s-alves10 

[Proposal](https://github.com/Expensify/App/issues/22939#issuecomment-1655555722) from @s-alves10 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by s-alves10** [comment] 2023-08-09 15:21
Thank you
I'll create a PR in a day

**Comment by s-alves10** [comment] 2023-08-09 15:56
@sobitneupane 
[PR](https://github.com/Expensify/App/pull/24324) is ready for review

**Comment by s-alves10** [comment] 2023-08-10 16:10
@sobitneupane 

Can you take a look at the https://github.com/Expensify/App/pull/24324?

**Comment by s-alves10** [comment] 2023-08-11 14:29
@amyevans 

Please take a look at the [PR](https://github.com/Expensify/App/pull/24324)

**Comment by amyevans** [comment] 2023-08-11 15:12
Review submitted

**Comment by maddylewis** [comment] 2023-08-21 15:06
moving to daily since payment is due this week

**Comment by maddylewis** [comment] 2023-08-24 18:33
### Payments
- [ ] Reporting bonus: N/A
- [ ] Contributor: @s-alves10 ($1500 paid via Upwork)
- [ ] C+: @sobitneupane ($1500 paid via NewDot)
______
- Contributor hired on August 9
- PR merged on August 11 - https://github.com/Expensify/App/pull/24324

**Comment by maddylewis** [comment] 2023-08-28 13:06
just waiting for @sobitneupane to confirm if any of these details need to be filled out before closing - https://github.com/Expensify/App/issues/22939#issuecomment-1681483982

**Comment by maddylewis** [comment] 2023-09-05 13:43
@sobitneupane - we're just waiting for you to confirm if anything on this checklist needs to be completed, and then we can close this out. https://github.com/Expensify/App/issues/22939#issuecomment-1681483982

**Comment by sobitneupane** [comment] 2023-09-05 16:48
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/18221
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/18221#issuecomment-1706965704
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is an edge case and was missed in the PR review.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-09-05 16:49
**Regression Test Proposal**

1. Navigate to any chat in IOS/safari.
2. Tap on Emoji button in composer
3. Enter a term that has no results
4. Scroll up and down slowly

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-09-05 17:59
Requested Payment on newDot.

https://github.com/Expensify/App/issues/22939#issuecomment-1692216835

**Closed** 2023-09-05 21:51 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-09-10 10:37
$3,000 payment approved via NewDot based on BZ summary.
