### ISSUE TITLE
[$500] "Reply Thread" Button Available in Archived Workspaces Despite User Inability to Reply

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37603] opened 2024-03-01 14:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.46-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to Settings > Create Workspace > Navigate to any room (admin, announcement, or workspace chat).
2. Comment something > Go to Settings > Delete the workspace > Return to the room and hover over the comment to observe that the "Reply Thread" button is available, even though the user cannot reply to the thread.

## Expected Result:
If users are not allowed to reply in the thread, the "Reply Thread" button should be removed to avoid confusion.

## Actual Result:
The "Reply Thread" button is available in archived workspaces, even though users cannot reply to the thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d98c2486-4c9d-4e8b-b63c-5a02b4b64eea

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014bb83c3bb20a6d51</li>
        <li>Upwork Job ID: 1764754146063355904</li>
        <li>Last Price Increase: 2024-03-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-01 14:29
@Christinadobrzyn I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment] 2024-03-01 14:31
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by Christinadobrzyn** [comment] 2024-03-04 20:45
Hum, I can reproduce based on the steps in the OP - I think this can be external.

**Comment by garrettmknight** [comment] 2024-03-05 19:52
Confirmed dupe, closing in favor of the earlier one.

**Closed by garrettmknight** 2024-03-05 19:52 UTC
Labels: External, Daily, Help Wanted, Bug
