### ISSUE TITLE
[$500] Web - SendMoney - Accessing the expense from the IOU report causes a Policy permission error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30518] opened 2023-10-27 14:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.91-8
**Reproducible in staging?:** n/a
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698362126625989

## Action Performed:
1. Send money to unvalidated account
2. Click on the report preview
3. Click on the expense preview

## Expected Result:
No error

## Actual Result:
Accessing an expense from an IOU report causes an error Policy does not exist or you do not have access

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/9dc8bf55-b5ac-435c-8553-0f9cccdca737

https://github.com/Expensify/App/assets/93399543/f342fd77-0f1e-4ba6-a420-297bfc6fb027

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148fdfcc75fba1bfe</li>
        <li>Upwork Job ID: 1717914114554114048</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by youssef-lr** [comment] 2023-10-27 17:32
Looks like this issue was mentioned by mistake in the PR above. I'm working on a fix.

**Comment by Christinadobrzyn** [comment] 2023-11-06 23:20
Fix is in the works!

**Comment by Christinadobrzyn** [comment] 2023-11-10 22:44
I think the PR is deployed to production right @youssef-lr? I'm not sure if this is a regression and there's no payment?

**Comment by youssef-lr** [comment] 2023-11-10 22:50
No payment here @Christinadobrzyn. and this is deployed already so I'll close!

**Closed** 2023-11-10 22:50 UTC
Labels: Daily, Internal, Bug
