### ISSUE TITLE
[$500] IOU – Red dot appears when create IOU with tag and category in Collect WS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35102] opened 2024-01-24 21:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4209391
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: In OldDot as the policy admin enable People must tag expenses
1. Go to https://staging.new.expensify.com/
2. Log in as Employee of a Collect workspace
3. Navigate to WS
4. Create a manual request, select a tag and category

## Expected Result:
There is no red dot on the parent IOU

## Actual Result:
Red dot appears on the parent IOU and disappears after IOU is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/0426dfa8-91cd-4ee2-9ec5-fc10f1ab76c6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e039fb442d9628ac</li>
        <li>Upwork Job ID: 1750262744576692224</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by wildan-m** [comment] 2024-01-25 09:42
@Ollyws  Do we need to request to activate it?, here is what my oldot WS page looks like

<img width="1440" alt="Screenshot 2024-01-19 at 14 36 29" src="https://github.com/Expensify/App/assets/11847279/d34c15b5-5fb6-428b-b931-e712069f585f">

**Comment by wildan-m** [comment] 2024-01-25 09:43
clicking the workspace will be redirected to newdot

**Comment by wildan-m** [comment] 2024-01-25 14:33
@Ollyws Thanks, after choosing to collect workspace I can only see #announce and #admin room, no Workspace room like we made in new dot, those two rooms don't have the option to request money. I've overridden `canUseAllBetas` to true, but nothing changed.

**Comment by zanyrenney** [comment] 2024-01-29 18:11
we can extend the trial for you no worries @wildan-m

**Comment by zanyrenney** [comment] 2024-01-29 18:11
/ clear any amount owed.

**Comment by zanyrenney** [comment] 2024-02-07 16:02
bumped here - https://expensify.slack.com/archives/C01GTK53T8Q/p1707321765663139

**Comment by zanyrenney** [comment] 2024-02-09 18:57
still waiting for proposal

**Comment by zanyrenney** [comment] 2024-02-14 16:10
awaiting proposals

**Comment by wildan-m** [comment] 2024-02-15 04:25
not reproducible

**Comment by zanyrenney** [comment] 2024-02-16 15:46
Also just tested and can't repro. I expect we have fixed this elsewhere with one of our many deploys 🎉 
 
closing!

**Closed by zanyrenney** 2024-02-16 15:46 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
