### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000]  Mask as unread doesn’t work with IOU report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22230] opened 2023-07-05 00:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account
2. Long press IOU report and choose Mark as unread
3. Notice that nothing happened

## Expected Result:
IOU report should be marked as unread

## Actual Result:
Nothing happened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/34eee16c-9d2b-4fa2-b46a-ef647e8a3c0f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688184504197159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b1761db5929fa57</li>
        <li>Upwork Job ID: 1677177064316227584</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-07-07 04:46
Hey @abdulrahuman5196 we have a proposal in the scrollback, can you review when you get a chance?

**Comment by stephanieelliott** [comment] 2023-07-11 01:28
Bump @abdulrahuman5196, can you review the proposal https://github.com/Expensify/App/issues/22230#issuecomment-1621341780

**Comment by stephanieelliott** [comment] 2023-07-13 07:21
@abdulrahuman5196 are you still planning to work on this? Planing to reassign to another C+ tomorrow if we've still not gotten a response.

**Comment by abdulrahuman5196** [comment] 2023-07-13 07:29
Sorry for the delay. Will complete the review today

**Comment by abdulrahuman5196** [comment] 2023-07-13 15:45
@honnamkuan I agree on the rootcause, but the suggested change doesn't work for me.

**Comment by abdulrahuman5196** [comment] 2023-07-15 07:13
@stephanieelliott / @honnamkuan  Why is this iOS specific bug? I have able to reproduce the same on web. If i mark as unread on web also i can reproduce the issue?

And @honnamkuan 's solution marks the LHN as unread, but the chat doesn't any message with 'New' line indicator.

**Comment by stephanieelliott** [comment] 2023-07-19 08:03
> Why is this iOS specific bug? I have able to reproduce the same on web. If i mark as unread on web also i can reproduce the issue?

The `Platforms` are selected by the creator of the issue, who is usually QA. I assume this was an oversight, have removed `IOS` from the title. . 

@abdulrahuman5196 can you please review the updated proposals? We have one [here ](https://github.com/Expensify/App/issues/22230#issuecomment-1639327999)and [here](https://github.com/Expensify/App/issues/22230#issuecomment-1636900676).

**Comment by abdulrahuman5196** [comment] 2023-07-20 07:17
Reviewing this now.

**Comment by abdulrahuman5196** [comment] 2023-07-20 08:45
From @Nodebrute 's proposal here https://github.com/Expensify/App/issues/22230#issuecomment-1636900676, it was the first to provide proper root cause, but the solution is not addressing the root cause. It actually fetches the report from ReportUtils which doesn't filter out IOU reports on storing.

**Comment by abdulrahuman5196** [comment] 2023-07-20 08:56
@honnamkuan 's updated root cause and solution is correct to address the root cause of IOU reports not present in the `allReports` variable. And added improvement of `DateUtils.getDBTime(new Date(0))` is also required.

@honnamkuan 's proposal here https://github.com/Expensify/App/issues/22230#issuecomment-1621341780 looks good and works well. 

🎀 👀 🎀
C+ Reviewed

**Comment by abdulrahuman5196** [comment] 2023-07-20 16:15
> @abdulrahuman5196 well @honnamkuan didn't even mentioned anything about changing allReports until I mentioned it. Also I did mentioned it in my alternate proposal that we can fix it. This issue was opened for 2 weeks. He was not even close to solving problem until I mentioned it.

@Nodebrute It is not wrong for a contributor to build a different solution from the root cause you had suggested. If he had copied your solution or build a similar solution on top of yours, I would have approved your proposal. But that's not the case, he provided a different solution, so it is considered as a different proposal.

>We can fix allReports data so we can retrieve value of lastVisibleActionCreated.

This is not valid fix information itself. It is just providing an understatement of what is required to fix. Maybe if this had provided some implementation information, this also would have considered. 


>He was not even close to solving problem until I mentioned it.

Thank you for your contributions. But kindly provide concerns in a civil manner.

**Comment by stephanieelliott** [comment] 2023-07-24 20:00
All reviews completed, PR undergoing QA.

**Comment by stephanieelliott** [comment] 2023-07-26 06:53
PR is on staging

**Comment by stephanieelliott** [comment] 2023-08-01 17:14
Hey @abdulrahuman5196 can you complete the BZ checklist above so we can issue payment tomorrow?

**Comment by abdulrahuman5196** [comment] 2023-08-01 18:47
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Seems to be the case since IOU report implementation.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1. Login with an account with IOU report
2. Long press or right click on an IOU report on LHN, choose "Mark as unread"
3. Verify that IOU report title is bold on LHN, indicating it has Unread report action
4. Click on the IOU report
5. Verify that green "New" line indicator is shown above the last report action

@stephanieelliott

**Comment by stephanieelliott** [comment] 2023-08-03 17:19
Issue for regression test: https://github.com/Expensify/Expensify/issues/305355

**Comment by stephanieelliott** [comment] 2023-08-03 17:20
Summarizing payment on this issue: 

 - Issue reporter: @hungvu193 $250, paid via Upwork
 - Contributor: @honnamkuan $1500 ($1000 + $500 bonus), paid via Upwork 
 - Contributor+: @abdulrahuman5196 $1500 ($1000 + $500 bonus), paid via Upwork 
 
 Upwork job is [here](https://www.upwork.com/jobs/~016b1761db5929fa57), 50% speed bonus is included on final payout

**Closed by stephanieelliott** 2023-08-03 17:20 UTC
Labels: External, Daily, Awaiting Payment, Bug
