### ISSUE TITLE
[HOLD for payment 2023-06-28] Workspace rooms no longer exist

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#20502] opened 2023-06-09 09:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Tap "+"
2. "New room"
3. Select any Workspace 
4. Name the room anything
5. Choose "Public" visibility
6. Create room

## Expected Result:
The room to exist after being created longer than a few days even if there is no activity, e.g. A comment, in the room 

## Actual Result:
The rooms exist upon creation but after some time (e.g. a day or two) no longer exist at all 

## Workaround:
Create more rooms 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.25-8
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** ladue@expensify.com, mitch@expensify.com: Nobody can access the rooms I created on the Scaling New Heights 2023 Workspace ([Internal Slack Thread on the matter](https://expensify.slack.com/archives/C04QEB4MJEQ/p1686300766445909?thread_ts=1686256871.864059&cid=C04QEB4MJEQ)):

https://new.expensify.com/r/2562430281976849
https://new.expensify.com/r/8773812781870040
https://new.expensify.com/r/3959586612649630
https://new.expensify.com/r/4987491735134437
https://new.expensify.com/r/3434009101472088
https://new.expensify.com/r/4254904726222870
https://new.expensify.com/r/1256989570917120
https://new.expensify.com/r/665161930913662
https://new.expensify.com/r/3032291257912066
https://new.expensify.com/r/3406315903006448
https://new.expensify.com/r/686547466607040
https://new.expensify.com/r/6952755378622259
https://new.expensify.com/r/32431901286090
https://new.expensify.com/r/2702250769049829
https://new.expensify.com/r/8947122985459714
https://new.expensify.com/r/7245222272791407
https://new.expensify.com/r/4184640799480230
https://new.expensify.com/r/4149332475254685
https://new.expensify.com/r/8025118228721561
https://new.expensify.com/r/270936148813137
https://new.expensify.com/r/8621841885382647
https://new.expensify.com/r/6132896515134410
https://new.expensify.com/r/7369111933652606
https://new.expensify.com/r/4965829983372246
https://new.expensify.com/r/4432534551888993
https://new.expensify.com/r/2284207808221553
https://new.expensify.com/r/5785123785605013
https://new.expensify.com/r/721879930552392
https://new.expensify.com/r/8517037426366828
https://new.expensify.com/r/7364970798928901
https://new.expensify.com/r/3062642324193697
https://new.expensify.com/r/7113865753115943
https://new.expensify.com/r/8731210460369161
https://new.expensify.com/r/1330157552549867
https://new.expensify.com/r/1785144468114039
https://new.expensify.com/r/3327202258816340
https://new.expensify.com/r/5606476194170807
https://new.expensify.com/r/4205184936451167
https://new.expensify.com/r/3480701359195144
https://new.expensify.com/r/8740827000781699
https://new.expensify.com/r/5190631253157040
https://new.expensify.com/r/862629261219042
https://new.expensify.com/r/3034504570884733
https://new.expensify.com/r/4824039698459455
https://new.expensify.com/r/3925882732955473
https://new.expensify.com/r/5387599258282327
https://new.expensify.com/r/8014015101103719
https://new.expensify.com/r/586356214623967
https://new.expensify.com/r/4497895780096251
https://new.expensify.com/r/725065348498926
https://new.expensify.com/r/5299947723499691
https://new.expensify.com/r/4449253575216744
https://new.expensify.com/r/3616897383310086
https://new.expensify.com/r/3781425557992207
https://new.expensify.com/r/1426003082940340
https://new.expensify.com/r/5384298421713252
https://new.expensify.com/r/6061593298110420
https://new.expensify.com/r/4393405170686928
https://new.expensify.com/r/48721475491292
https://new.expensify.com/r/8253212199051609
https://new.expensify.com/r/6839862476706193
 
**Notes/Photos/Videos:** 

https://new.expensify.com/r/8947122985459714:
<img width="912" alt="image" src="https://github.com/Expensify/App/assets/36425901/db212d26-ff4e-4875-af36-f0accda33979">

**Expensify/Expensify Issue URL:**
**Issue reported by:** mitch@expensify.com
**Slack conversation:** Internal: https://expensify.slack.com/archives/C04QEB4MJEQ/p1686300766445909?thread_ts=1686256871.864059&cid=C04QEB4MJEQ

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment] 2023-06-09 10:48
@MitchExpensify - Hi, it's my Saturday tomorrow, and I'm OOO on Monday for a public holiday. This seems urgent, if it's affecting Velocity Global, so I'll reassign this so it can be looked at by someone online.

**Comment by RobertLadue** [comment] 2023-06-09 12:24
Not sure what the tie in to Velocity Global is, might have missed it in the GH and apologies if I did, and the bigger issue is this is impacting Scaling New Heights 2023. Those were all rooms that Mitch created last week and somehow we lost them all 😭

**Comment by MitchExpensify** [comment] 2023-06-09 12:32
haha it is not tied to VG I think @jliexpensify is just mistaken with a separate urgent issue. This is equally urgent though as its tied to an external commit of SNH which happens soon

**Comment by francoisl** [comment] 2023-06-09 16:52
We just created a room with @RobertLadue together right now and we confirmed it exists in the backend (ID 5960908275900862). 

I don't see any logs of `AddWorkspaceRoom` being called with the report IDs mentioned above in the OP of this issue. One possible explanation could be that @MitchExpensify was offline when he created the rooms, so they were only created optimistically on his computer, and then he either signed out before coming back online, or there was an issue with sending the requests when he came back online.

Going to play around to try to reproduce the second theory, but so far it doesn't look like a major fire where we're not creating rooms.

**Comment by stephanieelliott** [comment] 2023-06-12 20:15
Thanks @francoisl! FWIW, I reported that this had also happened to me [here](https://github.com/Expensify/App/issues/20502#issuecomment-1584820909) but I'm not 100% confident on the details and it was definitely around the same time as the site outage on Wed. So let's ignore that second report that I had made.

**Comment by MitchExpensify** [comment] 2023-06-13 19:54
@francoisl does the theory about not leaving a comment seem at all likely as a factor based on your investigation?

**Comment by francoisl** [comment] 2023-06-13 22:42
> @francoisl does the theory about not leaving a comment seem at all likely as a factor based on your investigation?

Not really, it shouldn't be related.
I still can't explain the **original** issue where Mitch created the rooms and we don't have any `AddWorkspaceRoom` logs whatsoever, and since we don't have logs it's hard to pinpoint what happened. I tried creating rooms while offline and then coming back online, and couldn't see anything unexpected.

For Bob's **separate** issue during the site outage, I think I see a bug that could explain why the client didn't show an error message, and now looking to fix it.

**Comment by francoisl** [comment] 2023-06-30 18:17
Mostly done here, @stephanieelliott we'll just need to compensate @eVoloshchak for reviewing the [PR](https://github.com/Expensify/App/pull/20734).

**Comment by eVoloshchak** [comment] 2023-07-04 15:55
Not overdue, I'll request payment via NewDot in a couple of days

**Comment by stephanieelliott** [comment] 2023-07-07 04:30
Gonna consider this paid out, thanks everyone!

**Closed by stephanieelliott** 2023-07-07 04:30 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
