### ISSUE TITLE
[$500] In the "Invite Members" , cursor doesn't change to hand icon when hovering over checkbox.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36445] opened 2024-02-13 22:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1, Navigate to workspace settings > members.
2, Click on "Invite Members."
3, Search for email and hover over the checkboxes. The cursor should change to a hand since it is clickable.

## Expected Result:
The cursor changes to a hand when hovering over checkboxes.

## Actual Result:
The cursor doesn't change to a hand icon when hovering over checkboxes in the "Invite Members" section.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c8c53b20-25fb-473b-98ab-0918d6d1ffe5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e300650833fc613</li>
        <li>Upwork Job ID: 1757534906049933312</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-02-13 23:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The checkbox doesn't show a pointer cursor

### What is the root cause of that problem?
No styles applied to the checkbox, so it defaults to the default cursor

### What changes do you think we should make in order to solve the problem?
We can update the pointer styles for the checkbox!
We can add cursor:pointer here:
https://github.com/Expensify/App/blob/023d62cba900f4333f73c52eb735402a994cbc4b/src/styles/utils/index.ts#L921

### What alternative solutions did you explore? (Optional)

**Comment by aneequeahmad** [comment] 2024-02-14 02:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Cursor is not changed to hand icon when hovering over checkbox in invite members to workspace.

### What is the root cause of that problem?

The `role of button` for the `<View>` to select multiple items doesn't make sense. Checkbox are multiple or radio buttons maybe.

https://github.com/Expensify/App/blob/19a04519b9c3aad4147814b4cd02bcb79d2d0042/src/components/SelectionList/BaseListItem.tsx#L76-L78

### What changes do you think we should make in order to solve the problem?


The role should be `CHECKBOX` for the `<View>` since multiple checkboxes can be selected and this change doesn't effect anything else in app. it also increases the readability of the code.

   `role={CONST.ROLE.CHECKBOX}`

**Comment by jeremy-croff** [comment] 2024-02-14 02:29
We are not code golfing right :D 

## Proposal
Updating the checkbox component to use @components/checkbox 
### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We are using a duplication of @components/checkbox in BaseListItem, without the unified experience that sets the cursor, checkbox roles, and  aria labels, amongst other things.

### What changes do you think we should make in order to solve the problem?
Update the BaseList checkbox implementation to use @components/Checkbox to unify the experience

` ```
import Checkbox from '@components/Checkbox

{canSelectMultiple && (
      <Checkbox
          accessibilityLabel="item.text"
          disabled={item.isDisabled}
          isChecked={item.isSelected}
          style={[StyleUtils.getCheckboxContainerStyle(20), styles.mr3]}
          onPress={() => onSelectRow(item)}
      />
\)}```

This removes some lines of code as almost the exact same logic, styles, etc is in this component to be reused.

### What alternative solutions did you explore? (Optional)

**Comment by jeremy-croff** [comment] 2024-02-14 02:31
Implementation:
<img width="430" alt="Screenshot 2024-02-13 at 8 30 22 PM" src="https://github.com/Expensify/App/assets/157416545/cd341f3c-3650-49b3-a787-00208c367e77">

**Comment by askavyblr** [comment] 2024-02-14 11:43
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**


The checkbox fails to display a pointer cursor.

**What is the root cause of that problem?**

cursorPointer style is missing

What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/e6c321fe1681745b973f0e3861f734e5f21a596a/src/components/SelectionList/BaseListItem.tsx#L81-L85


                                    styles.mr3,
                                    **styles.cursorPointer,**

**What alternative solutions did you explore? (Optional)**

[checkbox pointer.webm](https://github.com/Expensify/App/assets/125897912/8f2591e9-bc20-47c4-a9e0-bfc16640a40d)

**Comment by lschurr** [comment] 2024-02-14 17:21
The other GH is closed. @rushatgabhane and @fedirjh (since you are on the issue) - can you take a look?

**Comment by Victor-Nyagudi** [comment] 2024-02-15 09:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The cursor doesn't change to a pointer when hovering over the checkbox next to a user while trying to invite them to a workspace. 

### What is the root cause of that problem?

The `View` housing the checkbox has an accessibility role of `button` which results in the cursor style being set to `default`. 

https://github.com/Expensify/App/blob/6914b1344ed1f8bd69037232a67e34ffea2581e4/src/components/SelectionList/BaseListItem.tsx#L78

You can see this if you inspect the checkbox on web and look through its styles. 

### What changes do you think we should make in order to solve the problem?

It looks like we're using two different kinds of checkboxes for tasks (the `Checkbox` component) and inviting workspace members (a `View` styled as a checkbox inside `BaseListItem`). 

For consistency's sake, I propose following [the pattern already in place in the tasks checkbox](https://github.com/Expensify/App/blob/6914b1344ed1f8bd69037232a67e34ffea2581e4/src/components/Checkbox.tsx#L96), and that is applying `role={CONST.ROLE.CHECKBOX}` to the `PressableWithFeedback` inside `BaseListItem`. 

https://github.com/Expensify/App/blob/6914b1344ed1f8bd69037232a67e34ffea2581e4/src/components/SelectionList/BaseListItem.tsx#L59

I'm getting a warning that `ACCESSIBILITY_ROLE` is deprecated, so we could potentially remove it from [the `View` styled as a checkbox](https://github.com/Expensify/App/blob/6914b1344ed1f8bd69037232a67e34ffea2581e4/src/components/SelectionList/BaseListItem.tsx#L78) in `BaseListItem` to mirror the `View` styled as a checkbox in the `Checkbox` component which doesn't have it. 

https://github.com/Expensify/App/blob/6914b1344ed1f8bd69037232a67e34ffea2581e4/src/components/Checkbox.tsx#L102-L112

However, if the role is meant to be kept, it would need to, in addition, be changed to `role={CONST.ACCESSIBILITY_ROLE.CHECKBOX}` in order for the cursor to show as a pointer. 

One could also argue adding this to the `View` in `Checkbox` for consistency.

### What alternative solutions did you explore? (Optional)

I explored the idea of adding a `styles.cursorPointer` to the `View` housing the checkbox in `BaseListItem` (before reading previous proposals - I'm aware it's already been proposed), which worked, but it felt like there were too many changes i.e. `PressableWithFeedback` sets the cursor to a pointer, `role={CONST.ACCESSIBILITY_ROLE.BUTTON` changes it to an arrow, and then I change it back to a pointer again. 

I also explored adding a `cursor: "pointer"` inside the `getCheckboxPressableStyle()` function (again, before reading proposals), but the `Checkbox` component also uses this function, and I preferred not to tamper with it. 

Finally, I thought about using `Checkbox` in both places, but after reading this [comment on the redesign](https://github.com/Expensify/App/issues/36445#issuecomment-1944489360), it's better to wait until that's finished.

**Comment by rushatgabhane** [comment] 2024-02-16 02:55
Agree with @fedirjh we should close this issue in favor of the refactor https://github.com/Expensify/App/issues/35712#issuecomment-1945851478

**Closed** 2024-02-16 16:25 UTC
Labels: External, Daily, Help Wanted, Bug
