### ISSUE TITLE
Attachment - Sometimes the taken picture is closed upon zooming out or moving the image

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47456] opened 2024-08-14 19:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4859369&group_by=cases:section_id&group_id=292107&group_order=asc
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app
2. Log in with any Gmail account
3. Open any 1:1 chat or self DM
4. Navigate to the Composers "+" button - Add attachment
5. Tap on "Take photo"
6. Take a photo and tap on the "OK" button
7. Zoom out on the image with the pinch method and move it up and down until the issue happens

## Expected Result:
I should be able to zoom without closing the image.

## Actual Result:
Sometimes the taken picture is closed upon zooming out or moving the image.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/dd4c0012-820b-4f3f-b88f-eff75878b5a1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-08-14 19:37
We think this issue might be related to the  #vip-vsb

**Comment by bernhardoj** [comment] 2024-08-15 05:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The attachment preview is closed when swiping down.

### What is the root cause of that problem?
We have a code that adds support to swipe down to close. This is available in the attachment modal and carousel.
https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/components/AttachmentModal.tsx#L457

### What changes do you think we should make in order to solve the problem?

If we don't want this feature anymore, we can first remove the `onSwipeDown`
https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/components/AttachmentModal.tsx#L457

But this isn't enough because when we swipe down the image, the image still becomes hidden as it's closed instead of going back to the boundary.

https://github.com/user-attachments/assets/ad29fc25-4f8d-4a4c-a074-1e0a69f9d044

It's because we have this code to hide the image and also calls `onSwipeDown` when we drag down the image (until the SNAP_POINT, 1/4 of screen height), but since we disable `onSwipeDown`, we don't want that behavior anymore, just like we aren't able to swipe left/right the image if not zoomed.
https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/components/MultiGestureCanvas/usePanGesture.ts#L145-L157

To fix this, we can add a check here to make sure the translate Y is happening if the `onSwipeDown` is enabled.
https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/components/MultiGestureCanvas/usePanGesture.ts#L219-L221
```
if (enableSwipeDownToClose.value || (isSwipingDownToClose.value && onSwipeDown)) {
```

(if we still want to allow drag the image down without calling the `onSwipeDown`, then we can just add the check [here](https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/components/MultiGestureCanvas/usePanGesture.ts#L145))

**Comment by puneetlath** [comment] 2024-08-15 14:46
Hmm, I don't really see this as a bug. I think the behavior is fine as is. I'm going to close but feel free to comment or reopen if you disagree.

**Closed by puneetlath** 2024-08-15 14:46 UTC
Labels: Daily, Bug
