### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500] Video - App returns to previous thread when scrubbing video in thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36906] opened 2024-02-20 15:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to chat.
3. Send a video.
4. Send a reply to the video in thread.
5. Send a reply to the video reply in Step 3.
6. Play the video in thread.
7. Click on the video player to adjust the playback.

## Expected Result:
App will stay in the same thread in Step 5.

## Actual Result:
App returns to thread in Step 4.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/33d26bb2-9fb7-4a02-9d22-bc075d75a202

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e97f0baf89a789a</li>
        <li>Upwork Job ID: 1759959992185339904</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by kbecciv** [comment] 2024-02-20 15:16
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by iwiznia** [comment] 2024-02-20 15:34
Posted here https://expensify.slack.com/archives/C01GTK53T8Q/p1708443084946829 we might revert https://github.com/Expensify/App/pull/30829

**Comment by kowczarz** [comment] 2024-02-20 15:43
Hey! I will take a look at it.

**Comment by puneetlath** [comment] 2024-02-26 15:59
Looks like the PR didn't totally fix it. But I'm removing the deploy blocker label based on discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1708962005483559).

**Comment by Skalakid** [comment] 2024-02-27 10:43
Hi, I prepared the [PR](https://github.com/Expensify/App/pull/37270) with the fix for this issue

**Comment by sobitneupane** [comment] 2024-03-20 05:54
Will work on the checklist asap.

**Comment by sobitneupane** [comment] 2024-03-20 15:20
The Video Player feature was added by https://github.com/Expensify/App/pull/30829 PR, which likely overlooked this particular case. Since it's an edge case that can only be reproduced by replying to a reply in a video message, it could have been easily missed.

**Closed** 2024-03-21 10:09 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment

**Comment by sobitneupane** [comment] 2024-03-21 13:04
Requested payment in newDot.

Payment Summary: https://github.com/Expensify/App/issues/36906#issuecomment-1995431921

**Comment by JmillsExpensify** [comment] 2024-03-22 21:20
$500 approved for @sobitneupane based on summary.
