### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Don't allow decimals in request amounts if the currency doesn't support decimals

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26551] opened 2023-09-02 11:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open anything that involves money. (Request money, split bill etc).
3. Write any amount in decimal in a currency that disallows decimals (i.e. ISK or MGA)
4. Click next

## Expected Result:
We should return an error stating that decimals are not supported in the selected currency.

## Actual Result:

No error is returned and the amount is rounded.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/faf670c6-a706-4534-92ea-136ac30b1b6e

https://github.com/Expensify/App/assets/93399543/c0c8f7af-8350-4be0-84ea-62aa2101610e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priyankrawat
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690213457772999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f0f0811f6fe308d</li>
        <li>Upwork Job ID: 1699169106621186048</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>esh-g | Contributor | 26858302</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-09-02 11:34
# Proposal

## Please re-state the problem we are trying to solve
Some currencies are automatically rounded off and decimals are removed while requesting money.

## What is the root cause of this problem?
Some currencies don't allow decimals places to be present in their denominations. We are already getting the decimals allowed by a currency in the `ONYXKEYS.CURRENCY_LIST`.
Example:
```js
VND: { 
  ISO4217: "704",
  decimals: 0,
  name: "Vietnam Dong",
  symbol: "₫"
}
```
So, if we select this currency the decimals are removed as `decimals : 0`.

## What changes should be made to fix this?
We should not allow the user to enter decimals places for currencies that don't allow it. This can be done by modifying the `MoneyRequestUtils.validateAmount()` method.

1. https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/iou/steps/MoneyRequestAmountForm.js#L64-L72
In the `MoneyRequestAccountForm` we should get the decimals allowed for the currency in the body of the component like this: 
```js
const decimals = CurrencyUtils.getCurrencyDecimals(currency);
```

2. https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/libs/MoneyRequestUtils.js#L59-L62
Modify the `MoneyRequestUtils.validateAmount()` to take two arguments instead of one: `amount` and `decimals`. Then, use a dynamic `regex` to validate the amount according to the decimals like this:
```js
function validateAmount(amount, decimals) {
    const regexString = decimals === 0
    ? `^\\d+(,\\d+)?$`                            // don't allow decimal point if decimals === 0
    : `^\\d+(,\\d+)*(\\.\\d{0,${decimals}})?$`;   // Allow the decimal point and the desired number of digits after the point
    const decimalNumberRegex = new RegExp(regexString, 'i');
    return amount === '' || (decimalNumberRegex.test(amount) && calculateAmountLength(amount) <= CONST.IOU.AMOUNT_MAX_LENGTH);
}
```
3. https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/iou/steps/MoneyRequestAmountForm.js#L126
Modify the use of the `validateAmount()` function and pass the `decimals` we got in step 1 to the function like this:
```js
if (!MoneyRequestUtils.validateAmount(newAmountWithoutSpaces, decimals)) {
```

4. We can also add a `useEffect` to `MoneyRequestAccountForm` to clear the `currentAmount` if it doesn't match the decimals when the currency is changed.
```js
useEffect(() => {
        if (!MoneyRequestUtils.validateAmount(currentAmount, decimals)) {
            setCurrentAmount('');
        }
    }, [currency]);
```

**Comment by esh-g** [comment] 2023-09-02 11:34
# Proposal

## Please re-state the problem we are trying to solve
Some currencies are automatically rounded off and decimals are removed while requesting money.

## What is the root cause of this problem?
Some currencies don't allow decimals places to be present in their denominations. We are already getting the decimals allowed by a currency in the `ONYXKEYS.CURRENCY_LIST`.
Example:
```js
VND: { 
  ISO4217: "704",
  decimals: 0,
  name: "Vietnam Dong",
  symbol: "₫"
}
```
So, if we select this currency the decimals are removed as `decimals : 0`.

## What changes should be made to fix this?
We should not allow the user to enter decimals places for currencies that don't allow it. This can be done by modifying the `MoneyRequestUtils.validateAmount()` method.

1. https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/iou/steps/MoneyRequestAmountForm.js#L64-L72
In the `MoneyRequestAccountForm` we should get the decimals allowed for the currency in the body of the component like this: 
```js
const decimals = CurrencyUtils.getCurrencyDecimals(currency);
```

2. https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/libs/MoneyRequestUtils.js#L59-L62
Modify the `MoneyRequestUtils.validateAmount()` to take two arguments instead of one: `amount` and `decimals`. Then, use a dynamic `regex` to validate the amount according to the decimals like this:
```js
function validateAmount(amount, decimals) {
    const regexString = decimals === 0
    ? `^\\d+(,\\d+)?$`                            // don't allow decimal point if decimals === 0
    : `^\\d+(,\\d+)*(\\.\\d{0,${decimals}})?$`;   // Allow the decimal point and the desired number of digits after the point
    const decimalNumberRegex = new RegExp(regexString, 'i');
    return amount === '' || (decimalNumberRegex.test(amount) && calculateAmountLength(amount) <= CONST.IOU.AMOUNT_MAX_LENGTH);
}
```
3. https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/iou/steps/MoneyRequestAmountForm.js#L126
Modify the use of the `validateAmount()` function and pass the `decimals` we got in step 1 to the function like this:
```js
if (!MoneyRequestUtils.validateAmount(newAmountWithoutSpaces, decimals)) {
```

4. We can also add a `useEffect` to `MoneyRequestAccountForm` to clear the `currentAmount` if it doesn't match the decimals when the currency is changed.
```js
useEffect(() => {
        if (!MoneyRequestUtils.validateAmount(currentAmount, decimals)) {
            setCurrentAmount('');
        }
    }, [currency]);
```

**Comment by sakluger** [comment] 2023-09-05 17:55
This is by design. Some currencies do not support decimals.

- ISK: This currency has been this way in our system for at least four years(I found a 4 year old [internal PR](https://github.com/Expensify/PHP-Libs/commit/11133efb5f40fcf090100ff33aab3001e6819e4e) where ISK had 0 decimal places)
- MGA: As of 2021 the unit is effectively obsolete, since one iraimbilanja is worth less than USD $0.005 and the coins have fallen into disuse. https://en.wikipedia.org/wiki/Malagasy_ariary

**Comment by sakluger** [comment] 2023-09-05 21:14
I think this has to be internal - in order to determine if a currency supports decimals, we need to access a private repo.

**Comment by sakluger** [comment] 2023-09-05 21:14
cc @aldo-expensify since we discussed in Slack: https://expensify.slack.com/archives/C049HHMV9SM/p1693939667624119?thread_ts=1690213457.772999&cid=C049HHMV9SM

**Comment by esh-g** [comment] 2023-09-06 01:06
Sure! @parasharrajat for that, we can use the `NumberUtils.format` function we are using right now to round off the value

**Comment by esh-g** [comment] 2023-09-06 16:28
@parasharrajat I have updated the [proposal](https://github.com/Expensify/App/issues/26551#issuecomment-1703807578) step 4 to reflect the changes you asked for. Please let me know if it looks good. I went with stripping the decimals without checking the decimal places allowed because I don't think we support currencies with denominations other than `1` or `0.01`. But still if we want to strip only the places with respect to the `decimals` provided we can use this function: 
```js
function stripDecimalsFromAmount(amount, decimals) {
    if (!decimals) {
        // If 'decimals' is not provided or equals 0, strip all decimals
        return amount.replace(/\.\d*/, '');
    } else {
        // If 'decimals' is provided, strip digits after the specified number of decimal places
        const decimalPattern = `\\.\\d{0,${decimals}}`;
        const regex = new RegExp(decimalPattern);
        return amount.replace(regex, '');
    }
}
```
Let me know if I should add this function instead

**Comment by esh-g** [comment] 2023-09-06 16:37
@parasharrajat I have tested for localzation as well. Here is a video of what I think is expected with the current proposal:
https://github.com/Expensify/App/assets/77237602/c1a7be55-0585-484f-9810-1973e6ce79cb

**Comment by esh-g** [comment] 2023-09-13 15:02
Bump @parasharrajat

**Comment by esh-g** [comment] 2023-09-14 17:17
Thanks @parasharrajat I have added a comment on slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1694711646490959?thread_ts=1667792460.122249&cid=C01GTK53T8Q) as you asked! 😇

**Comment by grgia** [comment] 2023-09-25 10:06
@aldo-expensify can you take over as the engineer for this Bug issue? I don't have the full context

**Comment by esh-g** [comment] 2023-09-25 15:09
Here is the PR: https://github.com/Expensify/App/pull/28137
@parasharrajat @aldo-expensify

**Comment by priyankrawat** [comment] 2023-09-25 15:40
Though I've already added my upwork details, I've also sent a proposal to the above link as mentioned by the bot.

**Comment by priyankrawat** [comment] 2023-09-27 00:41
> 📣 @priyankrawat We're missing your Upwork ID to automatically send you an offer for the Reporter role. Once you apply to the [Upwork job](https://www.upwork.com/jobs/~018f0f0811f6fe308d), your Upwork ID will be stored and you will be automatically hired for future jobs!

Hi guys, any updates? Thanks!

**Comment by sakluger** [comment] 2023-10-12 06:42
Hi @priyankrawat, sorry but we don't pay out a reporting bonus for New Features. You can see in the original Slack post where we discussed that this is a new feature rather than a bug. The Github automation incorrectly said you were eligible for the reporting bonus because the GH issue was originally labeled as bug. Sorry for the confusion 🙇.


For the other payments, I'm going to apply the speed bonus because the delay was due to BE, otherwise it would have been merged on time.

**Summarizing payouts for this issue:**

Contributor: @esh-g $750 (paid via Upwork)
Contributor+: @parasharrajat $750 (payable via Manual Request after BZ checklist is completed)

Above payments include efficiency bonus 🎉 
Upwork job: https://www.upwork.com/jobs/~018f0f0811f6fe308d

**Comment by sakluger** [comment] 2023-10-16 17:33
@parasharrajat could you please complete the BZ checklist and let me know when you've sent the request for payment? I'd love to close this one out. 🙇

**Comment by sakluger** [comment] 2023-10-17 16:17
Good call out, my bad! Closing this one out!

**Closed by sakluger** 2023-10-17 16:17 UTC
Labels: External, Engineering, Daily, NewFeature, Awaiting Payment
