### ISSUE TITLE
[$250] Room -Notify me about new messages is shown as "daily"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39077] opened 2024-03-27 15:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4458530
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap fab --- start chat -- room
3. Enter room name with
4. Make sure visibility is " Workspace "
5. Tap create room
6. Tap header
7. Tap settings

## Expected Result:
Notify me about new messages must be shown as "immediately" in room created with visibility " Workspace ".

## Actual Result:
Notify me about new messages is shown as "daily" by default instead of "immediately" in room created with visibility " Workspace ".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d2f87d8e-6b52-4aea-899e-4836615e2cc5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f2eeabf999360436</li>
        <li>Upwork Job ID: 1773032769246867456</li>
        <li>Last Price Increase: 2024-03-27</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-27 16:00
@kadiealexander I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-27 16:00
We think that this bug might be related to #vip-vsb.

**Comment by izarutskaya** [comment] 2024-03-27 16:01
Production 
![Screenshot_20240327_173113_Chrome](https://github.com/Expensify/App/assets/115492554/b453958b-ea79-4386-8e6f-c1c35d165f5d)

**Comment by blimpich** [comment] 2024-03-27 16:16
Not a blocker. Demoting. Looking into to see what could have caused this regression. Seems like a simple bug.

**Comment by blimpich** [comment] 2024-03-27 17:01
Hmmm, okay I spent some time looking at the PRs for this deploy and nothing really stands out to me. Lets open this up to contributors.

**Comment by FitseTLT** [comment] 2024-03-27 17:02
It is the BE that is returning notification preference daily and if u use staging server and if not it works well

**Comment by sobitneupane** [comment] 2024-03-28 09:02
The response received on creating a new room has "notificationPreference" set as "daily". So, I believe it's a backend issue.

<img width="402" alt="Screenshot 2024-03-28 at 14 42 19" src="https://github.com/Expensify/App/assets/25876548/5ce22f2a-da87-4228-989c-227b90b0cec3">

cc: @blimpich

**Comment by blimpich** [comment] 2024-03-28 16:30
@kadiealexander do you have a feeling as to what vip/wave we could put this under so that eventually an internal engineer will pick it up? I currently don't have the bandwidth to do it myself 😔. Maybe vip-vsb category "low"?

**Comment by kadiealexander** [comment] 2024-04-10 04:59
Updated the project and priority. I'm half-debating closing this, it doesn't seem to be a big deal.

**Comment by tgolen** [comment] 2024-04-16 18:49
@mountiny @aldo-expensify Are either of you aware of any changes that could have lead to this? I saw that you've both done some work on these notification preferences. From my investigation, it looks like it _might_ have coincided with [this change](https://github.com/Expensify/Auth/pull/10427) but it's not clear to me from looking at the code how the notification preferences get set in the `CreatePolicyRoom` flow. 

[This code](https://github.com/Expensify/Auth/blob/603ea5ae5b0c499702a79100efb3077b47fb4536/auth/lib/Report.cpp#L5788) is the closest thing I could find, but in the `CreatePolicyRoom` flow, `parentReportActionID` is null so that block would never execute.

This must have been something that recently changed as opposed to something that was never working (since the problem initially wasn't reproducible on production).

Is this something that needs to be added to `Report::getDefaultNotificationPreference()` for the `CHAT_TYPE_POLICY_ROOM`?

**Comment by aldo-expensify** [comment] 2024-04-16 19:27
> (since the problem initially wasn't reproducible on production).

If this was the case,  I think it may have been a change in Web-Expensify since there is no "staging Auth".

Maybe this PR: https://github.com/Expensify/Web-Expensify/pull/41437/files#diff-7a032f7284c8b42392fb9715c5196b05b34ebeb369ee31387f702a26980eb792L1299-R1303

It touches the onyx updates sent after creating the policy room.

It would be good to:

1. Reproduce the bug
2. Log out and log in
3. Check the notification preference

if in step 3. the notification preference is correct, then it is a problem of the pushed onyx updates

**Comment by mountiny** [comment] 2024-04-16 22:04
I am not aware of anything recent that I would work on or reviewed, but the PR Aldo linked looks suspicious and aligns timewise to when this bug was raised

**Comment by iwiznia** [comment] 2024-04-18 21:20
> Maybe this PR: [Expensify/Web-Expensify#41437 (files)](https://github.com/Expensify/Web-Expensify/pull/41437/files#diff-7a032f7284c8b42392fb9715c5196b05b34ebeb369ee31387f702a26980eb792L1299-R1303)


I thought so too, but this was open 6 hours before that [was deployed to staging](https://github.com/Expensify/Web-Expensify/pull/41437#issuecomment-2024037222)... 
Anyway, taking a look just in case.

**Comment by iwiznia** [comment] 2024-04-18 21:57
ok I am almost sure this has nothing to do with my changes, as that only changes what updates we queue and I just tested and this is wrongly saved in auth

**Comment by iwiznia** [comment] 2024-04-18 21:59
> Not a blocker. Demoting. Looking into to see what could have caused this regression. Seems like a simple bug.

I disagree with this. This was broken in staging and not prod, so it should've blocked as it is creating bad data in the DB that either willl remain bad forever or we need to fix manually.
It was probably a web-e blocker, not an App blocker (assuming that by the time we looked at it we had not deployed web). cc @blimpich

**Comment by blimpich** [comment] 2024-04-18 22:10
Fair, I wrongly assumed this wasn't a backend issue when I demoted it originally. The fact that we're creating bad data does make this worse than I thought. I can take a crack at this this afternoon and see if I can find the issue.

**Comment by blimpich** [comment] 2024-04-19 00:47
Hmm, I haven't been able to figure out which PR caused this. Trickier than it seems. I suspected [this PR](https://github.com/Expensify/Auth/pull/10226/files#diff-71e5dfb89f61488924fbd1778e402bfe798b419a31c368f1ca7dd3d2aa0a5387R6575) but actually on second look the timing is a little off. Merged after this was reported by less than a day. Also suspicious of [this PR](https://github.com/Expensify/Auth/pull/10128/files) but reverting it is rife with merge conflicts that I don't have the brain power to wade through.

Frustrating because the fix is actually pretty easy. I can put up a PR to fix this today. Though we should probably add a unit test to cover regressions as well.

**Comment by blimpich** [comment] 2024-04-19 21:26
I have a very hard time believing that this was ever a bug in Auth since we have a test that hasn't changed in 7 months that asserts that a newly created workspace visibility room should have a notification preference set to `Daily`. See [here](https://github.com/Expensify/Auth/blob/e5dfae40d1a5609f3c9a345e83c42f5de0d7209c/test/test/lib/ReportTest.cpp#L1370).

Additionally, the [test rail steps linked in the issue description](https://expensify.testrail.io/index.php?/tests/view/4458530) do not specify what the default notification setting should be.

All of this makes me think this is intended behavior.

**Comment by blimpich** [comment] 2024-04-19 21:33
Asking in #product about what we intended for this to be ([link](https://expensify.slack.com/archives/C03U7DCU4/p1713562248285709)). If we want it to be immediately I can do that, if we want it to stay the same we should update the test rail steps to say so.

**Comment by blimpich** [comment] 2024-04-22 17:53
There doesn't seem to be a consensus on whether we intentionally wanted the default notification preference set to daily or immediate, so I'll be airing on the side of doing as little as possible and just updating the QA steps to check for the notification preference being set to `Daily`. Best to "do nothing" in this case I think.

**Closed by blimpich** 2024-04-22 17:53 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
