### ISSUE TITLE
[HOLD for payment 2024-06-11] [Xero] mWeb - accounting - In accounting page, tapping enter your credentials does not trigger any action

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41795] opened 2024-05-07 18:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile --- workspaces -- workspace
3. Tap more features --- toggle on Accounting
4. Tap accounting and tap 3 dots in top
5. Tap enter your credentials

## Expected Result:
In accounting page, tapping enter your credentials must direct to respective page

## Actual Result:
In accounting page, tapping enter your credentials does not trigger any action

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4c1d3ec1-22d8-42c5-b9cb-ee01d45a0d07

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by lanitochka17** [comment] 2024-05-07 18:02
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MitchExpensify** [comment] 2024-05-14 16:08
I cannot get the staging to open on my virtual Android device 
<img width="594" alt="image" src="https://github.com/Expensify/App/assets/36425901/aafb6c1b-9b97-4365-b4ff-a586964927e0">

**Comment by MitchExpensify** [comment] 2024-05-14 16:12
Asking for help with reproduction here https://expensify.slack.com/archives/C01GTK53T8Q/p1715703126676229

**Comment by MitchExpensify** [comment] 2024-05-20 22:49
Asking again for help reporducing this here https://expensify.slack.com/archives/C02NK2DQWUX/p1716245342602619

**Comment by rushatgabhane** [comment] 2024-05-21 09:39
This is a WIP. @lakchote @trjExpensify this is not a bug right? is someone working on it?

**Comment by trjExpensify** [comment] 2024-05-21 10:23
Haha, whoops! I think we need to kill that three dot menu at the top of the accounting page - it does nothing. There should only be an overflow menu alongside the integration connected within the card itself. From the OP, it looks like one hasn't been connected yet - so they should only see the `Set up` button which on press navigates to QBO to initialise the connection. @rushatgabhane I can't find an issue for this, can you progress it here for Xero and QBO? 

CC: @hayata-suenaga @zanyrenney for vis.

**Comment by rushatgabhane** [comment] 2024-05-21 10:35
@trjExpensify i can raise a PR to remove it, should be quick.

**Comment by trjExpensify** [comment] 2024-05-21 10:36
Perf, thanks!

**Comment by rushatgabhane** [comment] 2024-05-22 07:51
not overdue

**Comment by hayata-suenaga** [comment] 2024-05-23 17:24
The PR was already reviewed. I don't know why Melvin assigned another engineer 🤔

**Comment by MitchExpensify** [comment] 2024-06-11 03:01
Do we need BZ steps here @rushatgabhane?

**Comment by rushatgabhane** [comment] 2024-06-11 07:46
hi, checklist isn't applicable because we just remove the three dot menu as it wasn't required

**Comment by rushatgabhane** [comment] 2024-06-11 07:46
we can close this issue. payment for all xero issues is already done.

**Closed** 2024-06-13 22:17 UTC
Labels: Daily, Overdue, Awaiting Payment, Bug
