### ISSUE TITLE
[HOLD for payment 2023-12-08] [$500] Connect Bank Account - first name not being validated on client side when adding a bank account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27390] opened 2023-09-13 20:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->bank account->connect manually
3. Fill in step 1 and 2 details and open step 3
4. Fill in correct details in step 3 and write numbers of symbols in first name field (used to trigger error)
5. Click on save and observe that app triggers error
6. Change first name field to proper name and save, it will move to next step and error is dismissed
7. Observe on workspace list or on profile avatar, there is no red dot currently
8. Reload on main page and observe that now red dot is displayed on profile avatar and on workspaces in workspace list even though error was fixed in step 6

## Expected Result:
App should display an error when entering invalid symbols in the first name field

## Actual Result:
App only shows a general "unexpected error" after hitting save and continue

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/69ceb58a-4ee0-4756-9756-d1aab0750156

https://github.com/Expensify/App/assets/93399543/78436571-a269-46b9-a99e-8330f88e1b7c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694445586380489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a5d35a91df14676</li>
        <li>Upwork Job ID: 1702051718946840576</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 27455937</li>
<li>tienifr | Contributor | 27455939</li>
<li>dhanashree-sawant | Reporter | 27455942</li>
</ul></li>
    </ul>
</details>

**Comment by peterdbarkerUK** [comment] 2023-09-14 15:14
<img width="370" alt="image" src="https://github.com/Expensify/App/assets/16888060/670e59d0-a4d9-463a-8e03-7d6b6d0ea8d1">


Kinda weird that it doesn't highlight the first name as an error either

(continuing to investigate, gotta step out for a sec)

**Comment by peterdbarkerUK** [comment] 2023-09-14 20:47
I was able to reproduce it. I also triggered this [issue](https://expensify.slack.com/archives/C049HHMV9SM/p1692808524671409).

**Comment by kevinksullivan** [comment] 2023-09-15 15:16
unassigning myself since we don't need duplicate BZ members

**Comment by peterdbarkerUK** [comment] 2023-09-19 10:21
Onyx [PR is merged](https://github.com/Expensify/react-native-onyx/pull/333)

@0xmiroslav - were you able to get clarification on the validation logic?

**Comment by peterdbarkerUK** [comment] 2023-09-25 14:20
Not overdue

**Comment by peterdbarkerUK** [comment] 2023-10-03 21:27
not overdue - @0xmiroslav could you point me towards where I can monitor the onyx version bump?

**Comment by mvtglobally** [comment] 2023-10-05 03:06
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2023-10-12 03:50
Issue not reproducible during KI retests. (Second week)

**Comment by peterdbarkerUK** [comment] 2023-10-17 10:26
@0xmiroslav could you update? :)

**Comment by stitesExpensify** [comment] 2023-10-20 17:24
Looks like the error is actually that you can't have an empty name. We strip the name field like this `preg_replace('/!|\d/', '', $name);`

**Comment by peterdbarkerUK** [comment] 2023-10-24 14:51
@tienifr would you mind updating your proposal in line with @stitesExpensify comment?

**Comment by peterdbarkerUK** [comment] 2023-12-11 20:12
@0xmiroslav could you take a swing through the checklist? This feels like something we should add to TR

Paid all three, though there's an error with ending contracts.

**Comment by peterdbarkerUK** [comment] 2023-12-19 09:28
Job closed all done!

**Closed by peterdbarkerUK** 2023-12-19 09:28 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
