### ISSUE TITLE
[$500] iOS - Room - Room name field in Room tab is not auto-focused when transitioning from Chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31414] opened 2023-11-16 02:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps1. Launch New Expensify app
2. Tap + > New chat
3. Tap Room

## Expected Result:
Room name field is auto-focused

## Actual Result:
Room name field is not auto-focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2b3a3790-040b-4386-83ed-f251f0292ffc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7206b7c5e42ad01</li>
        <li>Upwork Job ID: 1724981456441212928</li>
        <li>Last Price Increase: 2023-11-23</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 27955731</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-11-16 05:55
@bernhardoj Thanks for the proposal. Your RCA is right. However, the proposed solution might introduce a delay in the initial mounting of components. Kindly update your proposal to correct this.

**Comment by shubham1206agra** [comment] 2023-11-16 06:04
I mean focus in the initial mounting.

**Comment by manlaig** [comment] 2023-11-16 06:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Room name input is not auto-focused.

### What is the root cause of that problem?

For the `RoomNameInput` component, auto-focusing is decided by this condition:

https://github.com/Expensify/App/blob/47c7819244ccd1ec46e409c7f254791999f2637d/src/components/RoomNameInput/index.native.js#L45

But, the `autoFocus` property is not passed as part of `RoomNameInput` here:

https://github.com/Expensify/App/blob/47c7819244ccd1ec46e409c7f254791999f2637d/src/pages/settings/Report/RoomNamePage.js#L102-L107

### What changes do you think we should make in order to solve the problem?

Set the `autoFocus` field for `RoomNameInput` as follows:

```
<RoomNameInput
    ref={(ref) => (roomNameInputRef.current = ref)}
    inputID="roomName"
    defaultValue={report.reportName}
    isFocused={isFocused}
    autoFocus
/>
```


### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2023-11-17 15:04
> Ah, I see. IMO, that would bloat the `useAutoFocusInput` hook and I just feel it's weird to see that logic.
> 
> The new logic would probably look like this:
> 
> ```
> useAutoFocusInput(onMountDelay = CONST.ANIMATED_TRANSITION, onFocusDelay = CONST.ANIMATED_TRANSITION) {
>     const isFirstTimeRender = useRef(true);
>     const delay = isFirstTimeRender.current ? onMountDelay : onFocusDelay;
>     useEffect(() => {
>         isFirstTimeRender.current = false;
>     }, []);
> 
>     useFocusEffect(() => setTimeout(..., delay))
> }
> ```
> 
> I think it's fine to use 600ms for both cases as we don't have any issue with that when we are using it instead of trying to introduce something fancy that doesn't really add a value. Let me know your opinion.

@bernhardoj I don't think this will work exactly.

**Comment by shubham1206agra** [comment] 2023-11-20 15:17
> @shubham1206agra do you have any feedback on [my proposal](https://github.com/Expensify/App/issues/31414#issuecomment-1813863888)? Thanks!

@tienifr Your proposal looks the same as @bernhardoj proposal, and since @bernhardoj's proposal came first. I am going to prefer @bernhardoj on this.

**Comment by mallenexpensify** [comment] 2023-11-20 17:33
Is this a regression? Seems like it.

**Comment by shubham1206agra** [comment] 2023-11-27 06:48
I know @bernhardoj. Can you do this too? Check the lowest possible timing you can use.

**Comment by shubham1206agra** [comment] 2023-11-27 08:30
> I tried lowering the timeout and the lowest I found works reliably is 530ms. Other lower values won't work reliably especially when switching between tabs quickly.

Can you show us the video?

**Comment by shubham1206agra** [comment] 2023-11-27 12:58
@tienifr @bernhardoj I would favour the solution which can be fixed without changing the timing, i.e., fixing the problem inside `react-navigation` itself.

**Comment by shubham1206agra** [comment] 2023-11-29 06:19
@CortneyOfstad Is it possible to bump up the price to get more eyes on this?
Since no proposal now satisfies the requirement.

**Comment by situchan** [comment] 2023-11-29 06:27
Expert agency might help. Maybe SWM since this is related to navigation

**Comment by shubham1206agra** [comment] 2023-11-29 06:31
Adding 🎀 👀 🎀 for an engineer.

**Comment by shubham1206agra** [comment] 2023-11-29 06:31
@marcochavezf Can you drop this issue to SWM to see if anyone picks this up?

**Comment by CortneyOfstad** [comment] 2023-12-04 15:24
Not overdue!

**Comment by kowczarz** [comment] 2023-12-04 18:12
Hello! I'm an expert contributor from Software Mansion and I would like to work on this task.

**Comment by shubham1206agra** [comment] 2023-12-04 18:44
@marcochavezf Please assign @kowczarz

**Comment by kowczarz** [comment] 2023-12-07 09:39
Hello! After some research I'm confident to write that since [Material Top Tab Navigator](https://reactnavigation.org/docs/material-top-tab-navigator) under the food utilise [react-native-pager-view](https://github.com/callstack/react-native-pager-view) there is no simple way to overcome the issue with unfocusing the keyboard after the animation. Pager view wrapped in Material Top Tab Navigator doesn't expose any api that would notify us, that the screen is fully visible and the animation is finished. I could deep-dive into the pager view code and try to patch it to expose a callback, that would run on animation finished, but it's hard to estimate how long would it take since I don't know the code of that library. 

Other solution could be an addition of check if the `useAutoFocusInput` is being used in native navigator or the one that doesn't support `InteractionManager` and in the second case we can add some more time to `setTimeout`, because currently it the focus is called in almost the samem moment as the animation finish and that cause the race condition.

**Comment by kowczarz** [comment] 2023-12-07 09:40
Should I proceed with the native changes, or the solution with setTimeout is fine for now?

**Comment by shubham1206agra** [comment] 2023-12-07 14:39
@kowczarz Please proceed with the native one for now

**Comment by kowczarz** [comment] 2023-12-08 15:16
Ok, I will work on it next week

**Comment by CortneyOfstad** [comment] 2023-12-11 15:31
Thanks @kowczarz!

**Comment by CortneyOfstad** [comment] 2023-12-12 13:47
Hey! Sorry for the confusion here, but we just got an internal update. Per [this post](https://expensify.enterprise.slack.com/archives/C01SKUP7QR0/p1702341886807759), we can close any bugs that are not related to Waves, so closing this out 👍 We will re-address once the waves are completed.

**Closed by CortneyOfstad** 2023-12-12 13:47 UTC
Labels: External, Engineering, Daily, Bug

**Comment by situchan** [comment] 2023-12-12 13:48
> We will re-address once the waves are complete

Isn't it better to hold and move to Monthly? I believe closed issues won't be reopened again.

**Comment by CortneyOfstad** [comment] 2023-12-12 14:02
@situchan our plan is to manually reopen the GHs that were closed during this period, so no worries there 👍

**Comment by situchan** [comment] 2023-12-12 14:03
Ah ok. Thanks
