### ISSUE TITLE
[$500] IOU - Show more dropdown option not displayed and manual displayed for scan option

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30309] opened 2023-10-24 23:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click the FAB button > Request Money 
2. Select the "Scan" option
3. Upload a receipt
4. The Description, Date, Merchant details are displayed (not hidden under a "Show More" section)
5. Now, FAB button > Request Money > Manual > set an amount
6. Notice the Description, Date, Merchant are hidden under a "Show More" section

## Expected Result:
"Show more" drop down option is displayed when manually creating an expense and when scanning a receipt

## Actual Result:
"Show more" dropdown not displayed when Scanning a receipt but is displayed when manually creating an expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/c6130ce8-83c0-44a4-bffb-ab744b596579

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141550f3d1c8d39d8</li>
        <li>Upwork Job ID: 1716962535050149888</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by marktoman** [comment] 2023-10-25 00:46
### Proposal

Property `shouldShowSmartScanFields` is used incorrectly. It is [intended to show all fields](https://github.com/Expensify/App/blob/3651a16734ea70897ee7698af21519089422efaf/src/components/MoneyRequestConfirmationList.js#L158-L159) when it is true, but it is instead negated:

https://github.com/Expensify/App/blob/3651a16734ea70897ee7698af21519089422efaf/src/components/MoneyRequestConfirmationList.js#L235

Solution: 

1. Make it not negated, i.e. `props.shouldShowSmartScanFields` instead of `!props.shouldShowSmartScanFields`
2. Fix all calls to `MoneyRequestConfirmationList` so the flag is not present when the intent is to hide the properties.

**Comment by Christinadobrzyn** [comment] 2023-10-26 20:12
I can reproduce this - asking the team if we want to have "Show More" for scanned receipts - https://expensify.slack.com/archives/C01SKUP7QR0/p1698351093452399

**Comment by marktoman** [comment] 2023-10-27 13:30
Interestingly, the current behavior is unrelated to the intent of the flags. So, even if all fields should remain visible, the code needs to be fixed to make sense.

**Comment by Christinadobrzyn** [comment] 2023-10-27 18:10
Talking this over with the [team](https://expensify.slack.com/archives/C01SKUP7QR0/p1698393773345869?thread_ts=1698351093.452399&cid=C01SKUP7QR0) - it sounds like this is a regression. 

The date and merchant shouldn't show on a Scanned receipt. Not sure how to find the original job, I'll ask QA if they can help.

**Comment by isagoico** [comment] 2023-10-30 16:53
@Christinadobrzyn The issue that the show more option is not displayed for Scan and distance expenses is expected behavior. 
The show more button should only display in Manual expenses. I have added a note in this TC to remind the testers that this is expected. 

![image](https://github.com/Expensify/App/assets/44479856/9e8ab4d9-c2a2-42f3-9d3e-fbe25e3bb660)

**Comment by Christinadobrzyn** [comment] 2023-10-30 19:05
Thank you @isagoico! Okay so it sounds like this is expected - the "Show More" should only show for manually created expenses. Closing this without action.

**Comment by marktoman** [comment] 2023-10-30 19:08
@Christinadobrzyn There is more to fix, however, including what is in the report itself.

**Comment by marktoman** [comment] 2023-10-30 19:18
@Christinadobrzyn It looks like you recently removed the wrong header mention from the report. Is that not considered an error anymore?

```diff
- Show more drop down option displayed and scan displayed in header
+ "Show more" drop down option is displayed when manually creating an expense and when scanning a receipt
```

**Comment by Christinadobrzyn** [comment] 2023-10-30 21:00
Hi @marktoman, sorry I don't do code changes for the Bug Zero team so I'm not sure what that relates to. 

For your mention here - 

> It looks like you recently removed the wrong header mention from the report. Is that not considered an error anymore?

Is that in a PR? Or can you confirm where you are seeing that change? 

Also, can you send me a screenshot or video of what you mean by: 

> There is more to fix, however, including what is in the report itself.

**Comment by Christinadobrzyn** [comment] 2023-10-31 20:10
hey @marktoman Can you provide more information about what needs to be fixed, including videos or screenshots and the steps to reproduce so we can test?

**Comment by marktoman** [comment] 2023-10-31 22:53
@Christinadobrzyn Oh, there's actually been a recent [merge](https://github.com/Expensify/App/pull/29936) that fixes that part. The report is okay then, but it would be interesting if an engineer with enough authority could look at the code and say that it does not warrant the suggested refactoring. I don't believe that this would be the conclusion at all.

**Comment by Christinadobrzyn** [comment] 2023-11-06 20:34
I think if there's refactoring we'll address that at a later point. The point of this GH is to report bugs - we've concluded this isn't a bug and is working as expected. Any 'clean up' will happen at later date!

**Closed by Christinadobrzyn** 2023-11-06 20:34 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
