### ISSUE TITLE
[HOLD for payment 2023-01-16] [$1000] Zoom slider knob going out of boundary

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13817] opened 2022-12-23 12:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Settings.
2. Click on user avatar => click on camera icon.
3. Click on upload and select an image.
4. Press on left edge of knob.

## Expected Result:
Shouldn’t go out of boundary also shouldn’t show black border around image.

## Actual Result:
Going out of boundary and image going to zoom out in minus.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.43-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209337708-980c1630-2d2c-42bc-9168-fd3b10e9741a.mov

https://user-images.githubusercontent.com/43996225/209337730-9752c690-1e64-46d4-ae62-3d0a44912c9c.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jatinsonijs 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671696876380149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed7ab24ea289985f</li>
        <li>Upwork Job ID: 1610341468358815744</li>
        <li>Last Price Increase: 2023-01-03</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2022-12-27 20:50
cc @Expensify/design I'm curious to hear if you think this is a bug, or if we should allow users to zoom out on their avatar image a bit further.

**Comment by shawnborton** [comment] 2022-12-27 22:03
I commented in Slack but I don't think you should be able to zoom out. I'm curious if anything changed recently though to cause this, I feel like we built it so that you couldn't zoom out.

**Comment by sakluger** [comment] 2023-01-03 18:24
I was able to reproduce this, in fact I can continue zooming out pretty far by continuing to click on the left side of the knob.

Adding the `External` label, let's get this thing fixed!

**Comment by jatinsonijs** [comment] 2023-01-03 18:41
**Root Case**
It happening due to negative value of slider when we try to press edge. We can fix this by use min 0 (not less than 0).

**Proposal**

```diff
diff --git a/src/components/AvatarCropModal/AvatarCropModal.js b/src/components/AvatarCropModal/AvatarCropModal.js
index a42da9901c..0c4e07e8ea 100644
--- a/src/components/AvatarCropModal/AvatarCropModal.js
+++ b/src/components/AvatarCropModal/AvatarCropModal.js
@@ -293,8 +293,10 @@ const AvatarCropModal = (props) => {
         if (!isPressableEnabled.value) {
             return;
         }
-        const newScale = newScaleValue(locationX, sliderContainerSize);
-        translateSlider.value = locationX;
+
+        const x = Math.max(0, locationX);
+        const newScale = newScaleValue(x, sliderContainerSize);
+        translateSlider.value = x;
         const differential = newScale / scale.value;
         scale.value = newScale;
         const newX = translateX.value * differential;
```

**Comment by Prince-Mendiratta** [comment] 2023-01-03 18:50
# Proposal
## Cause
This issue happens because we have not set the maximum and minimum permissible value for the slider input. This allows the user to extend the value beyond the borders by clicking against the edge of the knob repeatedly.

## Solution
```diff
diff --git a/src/components/AvatarCropModal/AvatarCropModal.js b/src/components/AvatarCropModal/AvatarCropModal.js
index a42da9901c..f6da9786d7 100644
--- a/src/components/AvatarCropModal/AvatarCropModal.js
+++ b/src/components/AvatarCropModal/AvatarCropModal.js
@@ -293,8 +293,10 @@ const AvatarCropModal = (props) => {
         if (!isPressableEnabled.value) {
             return;
         }
-        const newScale = newScaleValue(locationX, sliderContainerSize);
-        translateSlider.value = locationX;
+        const minPossible = Math.max(0, locationX);
+        const idealValue = Math.min(minPossible, 100);
+        const newScale = newScaleValue(idealValue, sliderContainerSize);
+        translateSlider.value = idealValue;
         const differential = newScale / scale.value;
         scale.value = newScale;
         const newX = translateX.value * differential;
```

**Comment by jatinsonijs** [comment] 2023-01-03 19:03
**Proposal 2**
We can control both min and max 

```diff
diff --git a/src/components/AvatarCropModal/AvatarCropModal.js b/src/components/AvatarCropModal/AvatarCropModal.js
index a42da9901c..b95e0590d0 100644
--- a/src/components/AvatarCropModal/AvatarCropModal.js
+++ b/src/components/AvatarCropModal/AvatarCropModal.js
@@ -293,8 +293,10 @@ const AvatarCropModal = (props) => {
         if (!isPressableEnabled.value) {
             return;
         }
-        const newScale = newScaleValue(locationX, sliderContainerSize);
-        translateSlider.value = locationX;
+
+        const x = Math.min(Math.max(0, locationX), sliderContainerSize);
+        const newScale = newScaleValue(x, sliderContainerSize);
+        translateSlider.value = x;
         const differential = newScale / scale.value;
         scale.value = newScale;
         const newX = translateX.value * differential;
```

**Comment by Prince-Mendiratta** [comment] 2023-01-03 19:12
# Proposal 2
It would be better to use the inbuilt function for validating values. The output is same as my previous proposal.

```diff
diff --git a/src/components/AvatarCropModal/AvatarCropModal.js b/src/components/AvatarCropModal/AvatarCropModal.js
index a42da9901c..ae15654509 100644
--- a/src/components/AvatarCropModal/AvatarCropModal.js
+++ b/src/components/AvatarCropModal/AvatarCropModal.js
@@ -294,7 +294,7 @@ const AvatarCropModal = (props) => {
             return;
         }
         const newScale = newScaleValue(locationX, sliderContainerSize);
-        translateSlider.value = locationX;
+        translateSlider.value = clamp(locationX, [0, sliderContainerSize]);
         const differential = newScale / scale.value;
         scale.value = newScale;
         const newX = translateX.value * differential;
```

**Comment by jasperhuangg** [comment] 2023-01-04 07:31
Hey! Not the engineer assigned to review proposals for this issue, but I like the latest proposal from @Prince-Mendiratta using `clamp`. cc @cristipaval

**Comment by sobitneupane** [comment] 2023-01-04 08:00
@Prince-Mendiratta's [proposal](https://github.com/Expensify/App/issues/13817#issuecomment-1370132088) looks good to me as well.

🎀👀🎀 C+ reviewed

cc: @jasperhuangg @cristipaval

**Comment by Prince-Mendiratta** [comment] 2023-01-04 21:55
@cristipaval @sakluger I've got the PR ready, could you please assign the issue to me so I can send it in?

**Comment by cristipaval** [comment] 2023-01-05 10:20
> these type of things are discussion of PR review as per my understanding
Hey @jatinsonijs ! Thanks for your proposal, we really appreciate it! I agree with what you are saying, but I am going to approve @Prince-Mendiratta's [proposal](https://github.com/Expensify/App/issues/13817#issuecomment-1370132088) just because he is the first one who provided a complete solution from the first place. You initially proposed to adjust the `locationX` value to the left edge of the range only.

**Comment by jatinsonijs** [comment] 2023-01-05 10:21
@cristipaval I also have provided complete sol


> **Proposal 2** We can control both min and max by same way as in proposal 1. We can also use different variable to store min if we want to do
> 
> ```diff
> diff --git a/src/components/AvatarCropModal/AvatarCropModal.js b/src/components/AvatarCropModal/AvatarCropModal.js
> index a42da9901c..b95e0590d0 100644
> --- a/src/components/AvatarCropModal/AvatarCropModal.js
> +++ b/src/components/AvatarCropModal/AvatarCropModal.js
> @@ -293,8 +293,10 @@ const AvatarCropModal = (props) => {
>          if (!isPressableEnabled.value) {
>              return;
>          }
> -        const newScale = newScaleValue(locationX, sliderContainerSize);
> -        translateSlider.value = locationX;
> +
> +        const x = Math.min(Math.max(0, locationX), sliderContainerSize);
> +        const newScale = newScaleValue(x, sliderContainerSize);
> +        translateSlider.value = x;
>          const differential = newScale / scale.value;
>          scale.value = newScale;
>          const newX = translateX.value * differential;
> ```

**Comment by Prince-Mendiratta** [comment] 2023-01-05 10:28
> In @Prince-Mendiratta Proposal 1 he has used fixed width of "165" which Is not correct.

Hey @jatinsonijs, I was aware of the variable but used static values as a PoC for recording the solution videos, as suggested in my second proposal with the proper values. :)

**Comment by jatinsonijs** [comment] 2023-01-05 10:29
@Prince-Mendiratta I saw in your proposal you have added slider width is 165 right ?, but now it's edited and history version is deleted.

**Comment by jatinsonijs** [comment] 2023-01-05 10:32
If it's about first complete working solution then I think my proposal is the first one. We both was in hurry I guess 🙂

**Comment by Prince-Mendiratta** [comment] 2023-01-05 10:38
> @Prince-Mendiratta I saw in your proposal you have added slider width is 165 right ?, but now it's edited.

As I said, I used static values to test the extent to which the scale is dependent on the `locationX` value. That doesn't affect the fact that I proposed the solution first which had considerations about the maximum value of the slider. Besides, I had figured out the rootcause and gave a proposal which covered all cases first, even suggesting the correct function to use that adheres with the already implemented constraints, along with the demonstration video of the solution as well. Had I not been focused on providing a complete solution with the resultant output and testing all possible edge cases, I would've used the variable as well. 😄

**Comment by jatinsonijs** [comment] 2023-01-05 10:44
@Prince-Mendiratta I'm just saying if first complete working solution will consider first then according to order my solution is first one. and root case is also same for both side. even if I have added max condition in second proposal still according to time I gave first working solution.
Now it's on @cristipaval to decide.

**Comment by Prince-Mendiratta** [comment] 2023-01-05 10:50
@jatinsonijs In that case, let us consider the contribution each proposal had to providing a solution for the issue. My first proposal suggested the case to consider the maximum value of the slider, while my second proposal suggested the use of the correct function in the correct manner, along with demonstrations. 
Whilst your proposal just combined the function calls I made in my first proposal. 
Either way, I believe @cristipaval is the better judge here.

**Comment by cristipaval** [comment] 2023-01-05 12:37
Hey @Prince-Mendiratta ! Just go ahead with your solution.
@jatinsonijs I know he used a hardcoded value initially for the right edge, I picked up his solution because of his approach which handles both range margins. Thank you so much for your interest! I strongly recommend to continue proposing solutions for all the other open issues we have.

**Comment by sakluger** [comment] 2023-01-12 06:30
Whoops, @Prince-Mendiratta was never added as an assignee for this issue, I just assigned you now, so hopefully more of the GH automations will kick in now!

**Comment by sakluger** [comment] 2023-01-12 06:34
The linked PR was merged within 3 days. That means that if there are no regressions within 7 days after being deployed to production, then this issue is eligible for the efficiency bonus.

The PR was deployed to prod 2 days ago (on Jan 9), so payment is due on Jan 16. Updating the issue title accordingly.

**Comment by sakluger** [comment] 2023-01-17 18:18
All paid out in Upwork. Closing out, thanks everyone!

**Closed by sakluger** 2023-01-17 18:18 UTC
Labels: Reviewing, External, Daily, Bug
