### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] Tags & Categories - Name row in item RHP is not grayed out when edited offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39169] opened 2024-03-28 12:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is an admin of Collect workspace.

1. Go to staging.new.expensify.com.
2. Go to Collect workspace settings.
3. Go offline.
4. Go to Taxes.
5. Click on any tax and edit the name.
6. Note that the name row in RHP is grayed out.
7. Go to Tag > Settings > Custom tag name > Edit the name.
8. Note that the name row in RHP is grayed out.
9. Click on any tag > Edit tag name.
10. Repeat Step 9 with category.

## Expected Result:
In Step 9 and 10, when renaming tag and category offline, the name row in RHP should be grayed out, just like when tax name and custom tag name are edited offline.

## Actual Result:
In Step 9 and 10, when renaming tag and category offline, the name row in RHP is not grayed out.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/32d99617-b554-4236-8f13-567a4658075e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01656e560eca3f61c2</li>
        <li>Upwork Job ID: 1773756778962694144</li>
        <li>Last Price Increase: 2024-03-29</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-28 12:05
@garrettmknight I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-28 12:05
We think this issue might be related to the #wave-control.

**Comment by bernhardoj** [comment] 2024-03-28 12:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS category and tag name isn't grayed out in the setting page.

### What is the root cause of that problem?
The name menu item for category and tag isn't wrapped with OfflineWithFeedback, so even there is a pending action, they won't be grayed out.
https://github.com/Expensify/App/blob/469b11237c3079232d9bbf65899c3a4caa387b26/src/pages/workspace/categories/CategorySettingsPage.tsx#L119-L124

Compared to WS tax name field where we wrap it with OfflineWithFeedback.
https://github.com/Expensify/App/blob/469b11237c3079232d9bbf65899c3a4caa387b26/src/pages/workspace/taxes/WorkspaceEditTaxPage.tsx#L113-L127

### What changes do you think we should make in order to solve the problem?

Wrap both WS category and tag name menu item with offline with feedback and pass the correct pending action.
```
<OfflineWithFeedback ... pendingAction={currentPolicyTag.pendingAction}>

<OfflineWithFeedback ... pendingAction={policyCategory?.pendingAction}>
```

**Comment by nkdengineer** [comment] 2024-03-29 07:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 9 and 10, when renaming tag and category offline, the name row in RHP is not grayed out.

### What is the root cause of that problem?
We don't wrap `MenuItemWithTopDescription` of category/tag name into `OfflineWithFeedback` as we do for tax

https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/pages/workspace/categories/CategorySettingsPage.tsx#L119

https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/pages/workspace/tags/TagSettingsPage.tsx#L123

https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/pages/workspace/taxes/WorkspaceEditTaxPage.tsx#L113
### What changes do you think we should make in order to solve the problem?
We should wrap the menu item of tag and category name with `OfflineWithFeedback` and pass the pendingAction for this.
We should pass special pending action of name field via `pendingFields` since this is only updated when we edit the name. If we use `pendingAction`, the name is also grey out when we enable/disable the category/tag

```
<OfflineWithFeedback pendingAction={policyCategory.pendingFields?.name}>
    <MenuItemWithTopDescription
        title={policyCategory.name}
        description={translate(`workspace.categories.categoryName`)}
        onPress={navigateToEditCategory}
        shouldShowRightIcon
    />
</OfflineWithFeedback>
```

```
<OfflineWithFeedback pendingAction={currentPolicyTag.pendingFields?.name}>
    <MenuItemWithTopDescription
        title={currentPolicyTag.name}
        description={translate(`workspace.tags.tagName`)}
        onPress={navigateToEditTag}
        shouldShowRightIcon
    />
</OfflineWithFeedback>
```
### What alternative solutions did you explore? (Optional)
NA

**Comment by garrettmknight** [comment] 2024-03-29 16:59
Repro'd - opening up.

**Comment by garrettmknight** [comment] 2024-03-29 16:59
@ntdiary we've already got a couple proposals if you can check!

**Comment by garrettmknight** [comment] 2024-04-10 11:08
Moving to daily to check for deploy and test.

**Comment by garrettmknight** [comment] 2024-04-26 12:03
@ntdiary @nkdengineer please accept the offers.

**Comment by arosiclair** [comment] 2024-04-29 15:28
> @ntdiary @nkdengineer please accept the offers.

bump @nkdengineer

**Comment by garrettmknight** [comment] 2024-04-29 15:39
All paid out!

**Closed by garrettmknight** 2024-04-29 15:39 UTC
Labels: External, Daily, Awaiting Payment, Bug
