### ISSUE TITLE
Bank account - App crashes after connecting with plaid and selecting year of birth

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43550] opened 2024-06-12 11:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4621710
**Email or phone of affected tester (no customers):** applausetester+vd_mweb061124@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in with a completely new account.
2. Create a new Workspace.
3. Go to Settings > Workspaces > Workspace > More features and enable Workflows.
4. Go to Settings > Workspaces > Workspace > Workflows.
5. Tap on "Connect bank account".
6. Select "Connect online with Plaid".
7. Select Chase bank and use the testing credentials and test saving account.
8. Enter the testing routing number and account number and confirm.
9. Enter "Alberta" and "Charleson" on First name and Last name.
10. On the date of birth page, tap on the year number.
11. Scroll down and select a another year.

## Expected Result:
The app should continue to work normally, without crashing.

## Actual Result:
The app crashes after the user scrolls down and select a year.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fcae3ada-bb27-416b-b41f-074dec19b913

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2024-06-12 16:51
I cannot reproduce this on iOS staging.

**Comment by kavimuru** [comment] 2024-06-12 18:22
@luacmartins this is reproducible in iOS Safari

**Comment by luacmartins** [comment] 2024-06-12 20:37
This also happens in prod, so removing the label

**Comment by luacmartins** [comment] 2024-06-13 15:02
This is fixed. Closing.

**Closed by luacmartins** 2024-06-13 15:02 UTC
Labels: Reviewing, Engineering, Weekly, Bug
