### ISSUE TITLE
[HOLD for payment 2023-10-13] [HOLD for payment 2023-10-12] [$250] Assign Task - No margin New marker in Task report screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26015] opened 2023-08-26 22:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Assign task to user
3. Send a message in that Task -> Open context menu
4. Click Mark as unread
5. Try to click or hover Assignee button

## Expected Result:
There should be some spacing above New marker

## Actual Result:
No spacing above New marker

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4d99e29d-f011-47f3-b073-837397480e70

https://github.com/Expensify/App/assets/78819774/17fd4e02-7524-4105-82d4-c668b3e635f7

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @DinalJivani 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692313131187589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0147a58dd9511b7862</li>
        <li>Upwork Job ID: 1696445152355360768</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26752447</li>
<li>DinalJivani | Reporter | 26752448</li>
</ul></li>
    </ul>
</details>

**Comment by DinalJivani** [comment] 2023-08-27 20:48
@dylanexpensify @lanitochka17 
I think there is issue in **Issue reported by:**  in bug report.
I don't know how this happened but it tagged someone else. 😅

**Comment by dylanexpensify** [comment] 2023-08-29 08:48
Ah yes it does! We'll get you assigned @DinalJivani!

**Comment by DylanDylann** [comment] 2023-08-29 10:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No margin New marker in Task report screen

### What is the root cause of that problem?
Let's see the current behavior of new marker line and divider line in our App:
1. New marker line: There are no top and bottom padding/margin for every message

<img width="597" alt="Screenshot 2023-08-29 at 17 29 59" src="https://github.com/Expensify/App/assets/141406735/824040b8-c90a-4fca-8249-e90370bf6fcb">

2. Divider line: We have an inconsistency
- In thread chat, there are no top and bottom padding/margin for divider line
- In task/request money chat, marginVertical 8px is used for divider line

<img width="562" alt="Screenshot 2023-08-29 at 17 31 07" src="https://github.com/Expensify/App/assets/141406735/cb380a8d-b8ad-4a27-b003-8125c487974e">

This bug happened because **There are no top and bottom padding/margin for new marker line**
### What changes do you think we should make in order to solve the problem?
Solution 1: 
1. New marker line: We can consider adding margin top/bottom for the only first child message
2. Divider line: For consistency, we need to add marginVertical 8px to divider line of normal chat thread or remove marginVertical 8px in all places

Solution 2:
Add marginBottom 8px to below of parent message and only use marginBottom 8px for all Divider line for consistency
### What alternative solutions did you explore? (Optional)

**Comment by shawnborton** [comment] 2023-08-29 11:31
I think in this case, we should just add some margin on top of the unread message so that there doesn't appear to be a jump when the divider line gets replaced.

That being said, $1000 feels like a lot of money for such a small fix. @thienlnam what are your thoughts on just fixing this internally since you worked on a lot of the task changes?

**Comment by DylanDylann** [comment] 2023-08-29 11:45
@shawnborton what do you think about consistency in divider line
1. New marker line: There are no top and bottom padding/margin for every message
 
<img width="597" alt="Screenshot 2023-08-29 at 17 29 59" src="https://github.com/Expensify/App/assets/141406735/824040b8-c90a-4fca-8249-e90370bf6fcb">

2. Divider line: We have an inconsistency
- In thread chat, there are no top and bottom padding/margin for divider line
- In task/request money chat, marginVertical 8px is used for divider line

<img width="562" alt="Screenshot 2023-08-29 at 17 31 07" src="https://github.com/Expensify/App/assets/141406735/cb380a8d-b8ad-4a27-b003-8125c487974e">

**Comment by shawnborton** [comment] 2023-08-29 11:47
I think the extra vertical space is a nice separation from the top area to the bottom content, so I'm not sure that I would opt to change anything there. That being said, I can see where it's causing a slight inconsistency.

**Comment by DylanDylann** [comment] 2023-08-29 11:50
@shawnborton 
> I think the extra vertical space is a nice separation from the top area to the bottom content

I agree with your mind. So should we add extra vertical space to the divider line in the normal thread chat

**Comment by thienlnam** [comment] 2023-08-29 17:35
> That being said, $1000 feels like a lot of money for such a small fix. @thienlnam what are your thoughts on just fixing this internally since you worked on a lot of the task changes?

I agree, though I've been pretty focused on wave 5 items so I can't get to this now - we can always adjust the bounty so this feels less of a waste of money to complete. I'll go ahead and adjust the bounty

**Comment by dylanexpensify** [comment] 2023-08-31 08:58
Agree with that - thanks @thienlnam! @rushatgabhane can we get an update?

**Comment by dylanexpensify** [comment] 2023-09-04 10:16
Reviewing today while in the air! Currently taxi'd, will get to once I can hop on wifi! Sorry I didn't get to this last week, had head down on wave4 saastr - @rushatgabhane

**Comment by DinalJivani** [comment] 2023-09-06 12:03
> Bug not reproducible on staging
> 
> <img alt="image" height="500" src="https://user-images.githubusercontent.com/29673073/265909325-7969eda2-4e96-4c7c-830e-5a7dbe4303f2.png">

In this case it does not have bottom padding I see!! @rushatgabhane

**Comment by dylanexpensify** [comment] 2023-09-11 10:28
Coming back from conference last week - updating today!

**Comment by DylanDylann** [comment] 2023-09-11 11:13
Will update now

**Comment by dylanexpensify** [comment] 2023-09-19 08:30
@rushatgabhane can you give an update please 🙇‍♂️

**Comment by dylanexpensify** [comment] 2023-09-20 08:37
@rushatgabhane let's get a review today! 🙏

**Comment by yuwenmemon** [comment] 2023-09-29 05:49
I'm heading out on sabbatical so assigning another internal engineer for review when the time comes. @mountiny has graciously volunteered by virtue of sitting next to me.

**Comment by DinalJivani** [comment] 2023-09-29 11:04
@dylanexpensify 
I had received Upwork offer of $50 This is logged before 30th Aug. So it should be $250.

**Comment by dylanexpensify** [comment] 2023-10-02 14:08
@DinalJivani I'll payout 250!

**Comment by dylanexpensify** [comment] 2023-10-10 13:54
Payment summary:

- Reporter: @DinalJivani $250 
- Contributor: @dukenv0307 $125
- Contributor+: @rushatgabhane $125

**Comment by dylanexpensify** [comment] 2023-10-16 11:43
reviewing today!

**Comment by dylanexpensify** [comment] 2023-10-18 08:23
perfect! reviewing remaining steps today!

**Comment by JmillsExpensify** [comment] 2023-10-18 18:58
$125 payment approved for @rushatgabhane based on BZ summary.

**Comment by mountiny** [comment] 2023-10-23 14:53
@dylanexpensify I think we should be all set to pay or close

**Comment by mountiny** [comment] 2023-10-28 12:52
@DinalJivani @dukenv0307 have you been paid?

**Comment by dylanexpensify** [comment] 2023-10-30 09:53
everyone's been paid! Closing

**Comment by dylanexpensify** [comment] 2023-11-10 16:28
Sorry @aimane-chnaif - on it

**Comment by dylanexpensify** [comment] 2023-11-10 16:31
@aimane-chnaif sent offer

**Comment by dylanexpensify** [comment] 2023-11-10 16:59
done!

**Closed by dylanexpensify** 2023-11-10 16:59 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
