### ISSUE TITLE
[HOLD for payment 2024-05-08] [$250] Web - Thread - Adding a reaction on a highlighted message moves up and down strangely

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40572] opened 2024-04-19 14:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4494436
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open any chat
3. Send a message
4. Reply in the thread of the message
5. Click on header link to go back to originating chat
6. Scroll down to bottom and add a reaction using the "Add reaction" from the action menu and selecting from the emoji list
7. Observe the position of the highlighted message and do step 6 again multiple times without scrolling down manually until the message hides to the bottom

## Expected Result:
The highlighted message should not change positions when reaction is added to it

## Actual Result:
The highlighted message changes its position each time a reaction is added to it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dc7e2c6b-c52f-4706-8f3b-74070a247796

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0b14e1d5e66f327</li>
        <li>Upwork Job ID: 1781429732774735872</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment] 2024-04-19 14:49
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-19 14:49
We think that this bug might be related to #vip-vsp

**Comment by adelekennedy** [comment] 2024-04-19 21:08
yeah this is a weird one - making external, agree this is vip-vsb

**Comment by QichenZhu** [comment] 2024-04-20 12:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When adding a reaction to a partially visible message, the scroll position changes unexpectedly.

### What is the root cause of that problem?
The browser mistakenly selects the mini toolbar wrapper as an overflow anchor.

Although the browser's default scroll anchoring behavior is intended to minimize content shifts by adjusting scroll position, it causes issues here.

### What changes do you think we should make in order to solve the problem?
Adding a CSS property `overflowAnchor: 'none'` to the [`getMiniReportActionContextMenuWrapperStyle`](https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/styles/utils/index.ts#L1447-L1457) function to prevent the mini toolbar from being selected as an overflow anchor.

### What alternative solutions did you explore? (Optional)
Setting a fixed height for the mini toolbar wrapper, such as `36`, instead of using `auto`.

**Comment by ikevin127** [comment] 2024-04-21 22:31
I'm taking over as reviewer here as per @getusha's request, see [Slack 🧵](https://expensify.slack.com/archives/C02NK2DQWUX/p1713736340961419) for details.

**Comment by ikevin127** [comment] 2024-04-22 13:55
♻️ Proposal review in progress!

**Comment by ikevin127** [comment] 2024-04-22 15:31
@QichenZhu Thanks for your proposal. Your main solution works, it fixes the issue. The RCA is not entirely clear to me though so please help me understand it better in order to figure out how the solution comes into play.

As far as I understand from the current RCA and by looking at the code, the `MiniReportActionContextMenu` is being passed the `popoverAnchorRef` as anchor prop.

When you say:
> The browser selects the wrapper of the mini toolbar as an overflow anchor.

How does the browser do this exactly, are we making the browser do this programatically or how does this happen ?

> The wrapper's height changes when the mini toolbar disappears, and the browser's default scroll anchoring behavior adjusts the scroll position to keep the bottom of the wrapper in the same position on the screen.

Two questions here:
1. Which component's wrapper's height changes when the toolbar goes away ?
2. When you say `the browser's default scroll anchoring behavior adjusts the scroll position`, again, are we making the browser do this programatically or how does it adjust the scroll position ?

> [!tip]
> If for whatever reason it's difficult to explain in words, visuals like videos / screenshots could be helpful.

> [!note]
> The sooner these questions are answered and RCA becomes more clear, I think we can move on with this proposal.

**Comment by ikevin127** [comment] 2024-04-22 16:51
> I think this is not reproducible anymore!

@dragnoir I disagree, just reproduced it on latest main (develop) and it only happens on Web / Desktop.

<details>
<summary>MacOS: Chrome</summary>


https://github.com/Expensify/App/assets/56457735/27e25caf-d1d8-4d77-ad88-485ed62b5766



</details>

<details>
<summary>MacOS: Desktop</summary>


https://github.com/Expensify/App/assets/56457735/df44c1fd-6f25-4949-a9cb-967d57e0b506



</details>

> Also It's related to this issue: https://github.com/Expensify/App/issues/40644

I disagree for the following reasons:
- different `Action Performed` steps therefore different issue
- different RCA (allegedly, until the other issue gets some proposals)
- different scroll-related issue -> this one is related to the `MiniReportActionContextMenu` anchor and emoji selection

If you feel differently, feel free to expand on why you posted your comment and what do you suggest / would like to have happening based on your comment's observations.

**Comment by QichenZhu** [comment] 2024-04-22 22:07
@ikevin127 Thank you for your time!

> When you say:
> 
> > The browser selects the wrapper of the mini toolbar as an overflow anchor.
> 
> How does the browser do this exactly, are we making the browser do this programatically or how does this happen ?

The browser handles scroll anchoring automatically and we don't need to implement it programmatically. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor),  it is enabled by default in any browser that supports it.

> Which component's wrapper's height changes when the toolbar goes away ?

The `BaseReportActionContextMenu` component's wrapper's height changes.

The screenshots below illustrate the wrapper's height before and after `BaseReportActionContextMenu` goes away.

<img width="698" alt="toolbar" src="https://github.com/Expensify/App/assets/57348009/04e3fbde-efd9-4426-b601-c26d91fcbfac">


> When you say `the browser's default scroll anchoring behavior adjusts the scroll position`, again, are we making the browser do this programatically or how does it adjust the scroll position ?

Similar to the first question, it's not implemented programmatically on our end, the browser does it for us.

I also updated my [proposal](https://github.com/Expensify/App/issues/40572#issuecomment-2067657875) according to the question answers above. If you need further clarifications, please let me know.

**Comment by ikevin127** [comment] 2024-04-22 22:24
Thanks for the additional RCA clarifications!

@QichenZhu's [proposal](https://github.com/Expensify/App/issues/40572#issuecomment-2067657875) looks good to me and tests well. The RCA is clear **now** after https://github.com/Expensify/App/issues/40572#issuecomment-2071032728 clarifications and the proposed **main solution** fulfils the issue's **expected result** 🎉 

🎀👀🎀 C+ reviewed

**Comment by QichenZhu** [comment] 2024-04-22 22:43
@MelvinBot I've applied for the Upwork job. PR will be ready by tomorrow.

**Comment by QichenZhu** [comment] 2024-04-23 18:08
Just noticed I haven't been hired for the Upwork job yet. Would anyone be able to help me with this?

**Comment by ikevin127** [comment] 2024-04-24 21:41
@QichenZhu Don't worry about the Upwork contract as this is expected given this is the first job you were hired for. 

I'd encourage you to move on with the PR and open it so that I can review it and move along to get it merged. Once the PR is merged and deployed to **production** there will be a 7-day regression period at the end of which your payment will be issued based on the job you were told to applied to in https://github.com/Expensify/App/issues/40572#issuecomment-2071056959:

> Once you apply to this job, your Upwork ID will be stored and you will be automatically hired for future jobs!

As the bot mentioned, this flow only happens on your first contract. Subsequent contracts will send you the offer directly which you can accept and which will show up in your Upwork -> Reports -> Work in progress.

**Comment by QichenZhu** [comment] 2024-04-25 01:42
@ikevin127 Thank you for your assistance. The PR is ready for your review.

**Comment by ikevin127** [comment] 2024-05-01 03:49
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR:
- this issue was not caused by a regression introduced by any recent PRs but rather by the fact that we did not handle browser built-in scroll anchoring behaviour
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: (no need, see reasoning above)
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- based on the type of issue this is, there's no need for additional discussions regarding the addition of extra steps in order to catch this type of bug sooner because this was caused by the fact that we did not handle browser built-in scroll anchoring behaviour
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
- no need for a regression test here as this is a browser-related functionality issue caused by the fact that we did not handle browser built-in scroll anchoring behaviour
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- (no need, see reasoning above)

**Comment by ikevin127** [comment] 2024-05-08 22:51
@adelekennedy Please let me know if anything else is needed for the payment to be issued today!

**Comment by adelekennedy** [comment] 2024-05-09 00:37
@ikevin127 should be all set! @QichenZhu will you apply [here](https://www.upwork.com/jobs/~01d0b14e1d5e66f327)?

**Comment by QichenZhu** [comment] 2024-05-09 02:50
@adelekennedy Applied. Thanks! You can find my Upwork profile at https://www.upwork.com/freelancers/~0179e125e16ec756de

**Comment by adelekennedy** [comment] 2024-05-13 02:17
@QichenZhu hired you - I think you still need to accept and then I can pay you out

**Comment by QichenZhu** [comment] 2024-05-13 02:51
@adelekennedy Thanks! Accepted.

**Comment by adelekennedy** [comment] 2024-05-13 02:55
done! Sorry for the delay @QichenZhu!!

**Closed by adelekennedy** 2024-05-13 02:55 UTC
Labels: External, Daily, Awaiting Payment, Bug
