### ISSUE TITLE
[$250] mWeb/Safari - New Room - Welcome page of the new room is moving

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11406] opened 2022-09-29 00:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any expensify account
3. Click on FAB button/New Room
4. Enter the information to create the room and click Create Room

## Expected Result:
The welcome page of the new room opens smoothly

## Actual Result:
Welcome page of the new room is moving

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** v1.2.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/192909906-6b40d50f-8437-4d32-ba29-11cf6acd65f1.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PauloGasparSv** [comment] 2022-09-29 18:27
Reproduced locally on Web Mobile only too. This can be worked on by external contributors so I'm adding the External label!

**Comment by mollfpr** [comment] 2022-09-30 11:47
I think this has the same root cause as https://github.com/Expensify/App/issues/8292.

**Comment by adelekennedy** [comment] 2022-09-30 20:13
If we think this is the same root issue should we close this for now? @neil-marcellini @parasharrajat

**Comment by neil-marcellini** [comment] 2022-10-04 00:03
I'm fine with that, or we could make it weekly. Whenever the other issue gets fixed we should retest this one.

**Closed** 2022-10-04 18:42 UTC
Labels: External, Engineering, Daily, Help Wanted
