### ISSUE TITLE
Android - Captcha doesn't hide on back press - Reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11193] opened 2022-09-22 04:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Payments > Add payment method > Bank account
2. Select any bank
3. Tap on the captcha checkbox
4. When the captcha displays, press back button

## Expected Result:
The captcha hides when the back button is pressed

## Actual Result:
The captcha is still visible

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 
**Reproducible in staging?:** need repro (Not able to trigger CAPTCHA) 
**Reproducible in production?:** need repro
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/191659149-52e8abb1-4489-4009-87bf-b2f379a8752f.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661968966210629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment] 2022-09-23 06:01
I tried to replicate this but I don't get a captcha code. @adeel0202 could you please let me know how you triggered the captcha?

**Comment by adeel0202** [comment] 2022-09-23 06:09
@kadiealexander I don't think there are any specific steps to trigger the captcha. I too get to see the captcha sometimes, and the other times, it just bypasses the captcha. You can try to reproduce it with different accounts and also by connecting to a VPN.

**Comment by kadiealexander** [comment] 2022-09-26 23:32
Asking for help to replicate this issue [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1664235111906359).

**Comment by dhairyasenjaliya** [comment] 2022-09-28 04:59
hello @kadiealexander yes this issue exists on back click captcha doesn't hide, but I highly doubt to solve in our code base since this is inside plaid SDK


https://user-images.githubusercontent.com/47522946/192691144-1139f2d5-6db4-458c-b0c2-bf043541426b.mp4

**Comment by kadiealexander** [comment] 2022-09-29 03:28
Closing as this is an issue with Plaid as mentioned above.

**Closed by kadiealexander** 2022-09-29 03:28 UTC
Labels: Daily, Needs Reproduction
