### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] [$125] Workspace - Workspace chat reappears in LHN after leaving the chat and relogin

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44237] opened 2024-06-24 09:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is invited to a workspace.

1. Go to staging.new.expensify.com
2. Go to workspace chat as workspace member.
3. Click on the chat header.
4. Click Leave.
5. Go to Troubleshoot > Clear cache and restart > Reset and refresh (or relogin).

## Expected Result:

Users cannot leave  workspace chat. That is the chat where they are in the employee role

## Actual Result:
The workspace chat reappears in LHN after leaving the chat and relogin.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8c67be5c-bceb-4973-b603-0709780c4d5c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c734d656ba4811ea</li>
        <li>Upwork Job ID: 1805206172124171293</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 102854287</li>
<li>bernhardoj | Contributor | 102854288</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by izarutskaya** [comment] 2024-06-24 09:23
@JmillsExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-06-24 09:23
We think this issue might be related to the #collect project.

**Comment by mountiny** [comment] 2024-06-24 10:28
@izarutskaya in this case, is it the user leaving their own workspace chat? I dont think that should be possible

**Comment by mountiny** [comment] 2024-06-24 11:48
Marking as external. The expected behaviour is that the `Leave` button should not be available when its your workspace chat

**Comment by bernhardoj** [comment] 2024-06-24 12:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User can leave from their own workspace chat.

### What is the root cause of that problem?
In https://github.com/Expensify/App/pull/43251, we add the leave button for the workspace chat too if it's not the workspace admin.
https://github.com/Expensify/App/blob/d7db203cc8516492387a2a27b089f10bad7ab5ad/src/pages/ReportDetailsPage.tsx#L220

I believe this is because we are now able to invite users to the workspace chat, so it makes sense for the invited user to be able to leave, but not for the workspace chat owner.

### What changes do you think we should
Prevent the leave button from showing if it's an own workspace chat.
```
const shouldShowLeaveButton = !isThread && (... || (isPolicyExpenseChat && !report.isOwnPolicyExpenseChat && !isPolicyAdmin));
```

**Comment by bernhardoj** [comment] 2024-06-24 12:32
PR is ready

**Comment by mountiny** [comment] 2024-06-24 18:39
Its been CPed

**Comment by mountiny** [comment] 2024-06-24 18:40
<img width="487" alt="image" src="https://github.com/Expensify/App/assets/36083550/080d19b6-7067-45c2-b4d3-ff3e9a291ac3">
its gone

**Comment by lanitochka17** [comment] 2024-06-25 15:03
Hello. Issue still happens another way. Fail or new issue?
The steps are the same except that the user is now invited to workspace chat instead of workspace


https://github.com/Expensify/App/assets/78819774/41c127de-5e66-471d-a497-a9641f71c55f

**Comment by mountiny** [comment] 2024-06-26 11:33
@ishpaul777 you should not get the leave button in the report details, so then you should not be able to leave the chat. How come its still visible for the workspace chat you own?

**Comment by mountiny** [comment] 2024-06-26 11:47
Oh I see, i think that would be a new issue. @izarutskaya Can you please log this with the specific steps, ie its user that is invited and they are not able to leave the chat afterwards

I think we are calling wrong api command, it should call LeaveRoom or something like that

**Comment by lanitochka17** [comment] 2024-06-26 16:47
@mountiny I will leave a link when it is ready

**Comment by lanitochka17** [comment] 2024-06-26 17:05
@mountiny A new issue is ready https://github.com/Expensify/App/issues/44492

**Comment by mountiny** [comment] 2024-06-27 22:19
Cool thanks, I think that is ready for payment then

$125 to @bernhardoj and to @ishpaul777

**Comment by JmillsExpensify** [comment] 2024-07-11 04:30
Issuing payments based on Vit's [payment summary above](https://github.com/Expensify/App/issues/44237#issuecomment-2195760038). Do we need a regression test for this though?

**Comment by JmillsExpensify** [comment] 2024-07-11 04:31
Also @bernhardoj will you be requesting via NewDot?

**Comment by bernhardoj** [comment] 2024-07-11 04:33
@JmillsExpensify yes, requested in ND.

**Comment by JmillsExpensify** [comment] 2024-07-11 04:47
$125 approved for @bernhardoj

**Comment by JmillsExpensify** [comment] 2024-07-11 04:48
Closing this one out!

**Closed by JmillsExpensify** 2024-07-11 04:48 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
