### ISSUE TITLE
[Search v1.2] - Unsubmitted expense can be held without error in Search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46742] opened 2024-08-02 18:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:*Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4804456
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Delayed submission is enabled on Workflows
- Workspace has an approver (admin)
1. Go to staging.new.expensify.com
2. [Employee] Go to workspace chat
3. [Employee] Create two expenses and do not click Submit button
4. [Admin] Go to transaction thread of any submitted expense from employee
5. [Admin] Click on the report header > Hold
6. [Admin] Enter reason and save it
7. [Admin] Note that it shows "This request is being modified by another member." and the expense cannot be held
8. [Admin] Go to Search
9. [Admin] Select the expense from Step 4 via checkbox
10. [Admin] Click on the dropdown > Hold
11. [Admin] Enter reason and save it
12. [Admin] Note that admin can hold the request from Search and there is no error message

## Expected Result:
Admin should be prevented from holding expenses that are not submitted yet in Search

## Actual Result:
In Step 7, admin is not allowed to hold unsubmitted expense when holding via transaction thread
In Step 12, admin can hold unsubmitted expense via dropdown button in Search

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/0a07ac6e-19a1-43fa-980c-e423446af209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-02 18:13
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-02 18:14
We think that this bug might be related to #wave-collect - Release 1

**Comment by FitseTLT** [comment] 2024-08-02 18:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Unsubmitted expense can be held without error in Search

### What is the root cause of that problem?
We are missing the validate checks as in here
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/pages/iou/HoldReasonPage.tsx#L60-L74
here in search hold page
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/pages/Search/SearchHoldReasonPage.tsx#L40-L46
### What changes do you think we should make in order to solve the problem?

We need to use the validate logic here
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/pages/iou/HoldReasonPage.tsx#L60-L74
in the search hold page
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-08-02 18:57
BE

**Comment by trjExpensify** [comment] 2024-08-05 21:51
@cdOut is [your PR](https://github.com/Expensify/App/pull/45151) going to take care of this, actually?

**Comment by cdOut** [comment] 2024-08-06 08:10
@trjExpensify Hm, looking at the video it looks a little sketchy, it might be using different logic there. I can test it on the hold cleanup PR and if it doesn't fix it I can work on this one after.

**Comment by trjExpensify** [comment] 2024-08-06 09:40
Okay, sounds good. Let me know!

**Comment by trjExpensify** [comment] 2024-08-09 17:56
Any luck with testing that @cdOut?

**Comment by cdOut** [comment] 2024-08-09 18:15
@trjExpensify I've tested it on my hold cleanup PR and it did not help with this bug. I'll create a separate PR with a fix for this one early next week.

**Comment by trjExpensify** [comment] 2024-08-09 18:18
Okay, I'll assign you. :)

**Comment by cdOut** [comment] 2024-08-14 13:08
@trjExpensify I've raised a PR and moved to review, looks like someone missed a conditional for checking whether the selected requests have been submitted yet by the author.

I've also went and added a revised error message for this case, since the one used for singular requests wasn't fit for this one. So for singular request it's `This request is being modified by another member.` and for the search feature hold I've went with `'Some of the selected requests are being modified by another member.'` which is more descriptive. Let me know if that's okay.

**Comment by trjExpensify** [comment] 2024-08-14 22:52
Thanks, Tymo! I actually find these error messages pretty strange for the scenario they were introduced. I see the blame coming from this PR: https://github.com/Expensify/App/pull/37477

If I understand the `reportModified` one correctly, the case is: 

- Member submits an expense 
- Opens the hold modal to enter a reason
- during that time the approver approves/pays the report
- The submitter tries to hold the expense
- We display an error that says: "This request is being modified by another member." 

@jamesdeanexpensify I see you approved that copy, but I think it's incorrect, and we should change it to something like: "This expense can't be held because it is approved or paid."

Moving on to this case Tymo is addressing on the search page: 

- Member creates an expense, puts it on a draft open report
- Admin selects the expense (or multiple) on the open report
- They see the `Hold` action button in the bulk select dropdown
- Provide a holdReason > confirm
- We show an error, a discerning one would be: "You can't hold expenses that haven't been submitted yet."

But, I question why in step 3 we're even showing the Hold action button if the selected expenses can't be held, and then we'd avoid this error case altogether. CC: @JmillsExpensify @luacmartins as I'm sure we aren't showing other action buttons that aren't applicable in search (e.g `Delete` when an expense selected is approved or paid).

**Comment by cdOut** [comment] 2024-08-15 00:25
Ah, okay. I was missing some context on how the search flow handles such cases. Thanks for clearing that up. In that case, I do agree with hiding the option from the menu. The code I wrote is also applicable in that scenario.

This is definitely out of scope, but I do wonder if maybe always showing the possible options would be a better solution, and when one of the selected requests would block an option, we could then show a warning indicator next to the option in the menu. We could then also highlight which of the selected requests are causing the warning to appear.

**Comment by trjExpensify** [comment] 2024-08-15 00:35
>Ah, okay. I was missing some context on how the search flow handles such cases. Thanks for clearing that up. In that case, I do agree with hiding the option from the menu. The code I wrote is also applicable in that scenario.

Awesome, apols if that wasn't clear! 👍 

>This is definitely out of scope, but I do wonder if maybe always showing the possible options would be a better solution, and when one of the selected requests would block an option, we could then show a warning indicator next to the option in the menu. We could then also highlight which of the selected requests are causing the warning to appear.

Yeah, potentially, you could be right. I think we'll hear soon enough if the current approach is confusing via the support channels as we open the flood gates to NewDot with new sign-ups.

**Comment by luacmartins** [comment] 2024-08-15 15:53
I put up a PR to fix the hold option showing up in the Search page if the report is Open and the user is not the owner of the request.

**Comment by cdOut** [comment] 2024-08-15 22:59
@luacmartins could you share a link to that PR you've mentioned?

**Comment by luacmartins** [comment] 2024-08-15 23:08
Yea, [this is the PR](https://github.com/Expensify/Auth/pull/12070) but it's internal only

**Comment by luacmartins** [comment] 2024-08-15 23:08
It was deployed to production ~1h aho

**Comment by cdOut** [comment] 2024-08-21 16:22
@trjExpensify since we’ve settled on not showing the hold option if selected requests are unsubmitted I also wanted to clear out how we handle one of the cases for it.

What should happen when the user selects a few requests, some of which are submitted and the other are unsubmitted. Right now I also disable the hold option here from being displayed in the search menu. Is that the correct behavior here?

**Comment by trjExpensify** [comment] 2024-08-23 11:03
Sorry for the tardy response @cdOut, I've been OoO. 

>What should happen when the user selects a few requests, some of which are submitted and the other are unsubmitted. Right now I also disable the hold option here from being displayed in the search menu. Is that the correct behavior here?

Yep, that's the correct behaviour. 👍

**Comment by cdOut** [comment] 2024-08-23 11:34
Great, then the PR is ready and I'm just waiting for the C+ checklist 👍

**Comment by trjExpensify** [comment] 2024-08-26 09:11
Assigning @eh2077 for the PR review: https://github.com/Expensify/App/pull/47413

**Comment by luacmartins** [comment] 2024-08-30 14:34
We closed the App PR since the issue was fixed in the backend. However, given that a considerable amount of effort was put into it by @eh2077, I think we should still compensate them for the work.

**Comment by luacmartins** [comment] 2024-08-30 14:34
We can close this issue once payment is processed.

**Comment by trjExpensify** [comment] 2024-09-02 22:37
Sounds good! Payment summary as follows:

- $250 to @eh2077 for the PR

Offer sent!

**Comment by trjExpensify** [comment] 2024-09-05 01:18
Paid!

**Closed by trjExpensify** 2024-09-05 01:18 UTC
Labels: Weekly, Awaiting Payment, Bug
