### ISSUE TITLE
[HOLD for payment 2024-11-29] [GR Phase 2] Step 4 Beneficial owner screen (without API calls)

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#50900] opened 2024-10-16 13:54 UTC
Design doc section: https://docs.google.com/document/d/1Y4P7G9h0Easjcea7wyk52gKrNB9o1yTjpmJFYkrHDW4/edit?tab=t.0#bookmark=id.5pc093vnuj1r

**Comment by MrMuzyk** [comment] 2024-11-06 11:51
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by sonialiap** [comment] 2024-11-29 09:31
@hungvu193 do we need to add regression steps for this change?

Payment summary:
- @hungvu193 owed $250 via NewDot
- @MrMuzyk is from an agency-contributor and not due payment

**Comment by hungvu193** [comment] 2024-11-29 09:33
> @hungvu193 do we need to add regression steps for this change?

This is new feature, also it's not widely available to all the users (only available with debug mode), so I don't think we need regression test for this issue

**Comment by madmax330** [comment] 2024-12-02 10:43
Waiting for payment

**Comment by sonialiap** [comment] 2024-12-02 12:05
Thanks, since no regression test is needed, closing ✔️

**Closed by sonialiap** 2024-12-02 12:05 UTC
Labels: Daily, Awaiting Payment

**Comment by garrettmknight** [comment] 2024-12-12 11:22
$250 approved for @hungvu193
