### ISSUE TITLE
[HOLD for payment 2024-11-22] [$250] Pressing up arrow to edit the previous message, there is a bad overlap with the recipients local time.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51431] opened 2024-10-24 17:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729781934730029

## Action Performed:
1. Go to staging.new.expensify.com
2. DM any user and send multiple messages
3. Click the up arrow on keyboard to edit the last message sent
## Expected Result:
User able to edit last message sent and no visual issues
## Actual Result:
Selected message box overlaps with the recipients local time
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

![image (3)](https://github.com/user-attachments/assets/5092447f-dc44-421b-bcba-d87f83ca2b75)

  
![Google Chrome 2024-10-24 at 10 49 46](https://github.com/user-attachments/assets/d38d1d65-d120-4a0b-bf89-fc1a42377492)

![Snip - (55) New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/9c8fb52b-4973-4252-8614-1ae0281d7f9f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851399834739628625</li>
        <li>Upwork Job ID: 1851399834739628625</li>
        <li>Last Price Increase: 2024-11-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by shahinyan11** [comment] 2024-10-24 19:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing up arrow to edit the previous message, there is a bad overlap with the recipients local time.
### What is the root cause of that problem?
The message edit mode container is large and the scroll position remains the same after expanding the content.
### What changes do you think we should make in order to solve the problem?
Add following line `const reportScrollManager = useReportScrollManager()` in `ComposerWithSuggestions` component and add bellow code after [this](https://github.com/Expensify/App/blob/8807b2b178120cbe0613f3fb4b9b53cec9c0f4aa/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L502) line
```
InteractionManager.runAfterInteractions(()=>{
    reportScrollManager.scrollToBottom()
})
```
### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment] 2024-10-25 16:39
I think [this issue](https://github.com/Expensify/App/issues/51472#issuecomment-2437999128) may be a dupe (thank you @shahinyan11!) closing in favor if this one as it already has a proposal

**Comment by raza-ak** [comment] 2024-10-28 08:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing up arrow to edit the previous message, there is a bad overlap with the recipients local time.
### What is the root cause of that problem?
Enabling edit mode triggers a slight upward movement of the scrollbar, which shifts the layout and results in an overlap between the message editing area and the recipient's local time display.
### What changes do you think we should make in order to solve the problem?

A useEffect hook was implemented to automatically scroll to the bottom after the component finishes rendering in edit mode. This ensures that the edit section is fully visible and prevents any overlap with the recipient’s local time.
**Following changes will fix the issue:**
<img width="617" alt="image" src="https://github.com/user-attachments/assets/e714e235-32a4-4f40-b690-221d9b534be9">

**Video:**

https://github.com/user-attachments/assets/41995382-6b30-41f2-9dc3-c9e530241ed9

**Comment by strepanier03** [comment] 2024-10-29 23:06
Repro'd pretty easily. This is mostly just a polish project as it doesn't impact the customer's ability to use the product nor drive forward other projects. 

<img width="577" alt="image" src="https://github.com/user-attachments/assets/57d6275a-bf06-4cdc-aa77-51ce38fc2641">

**Comment by bernhardoj** [comment] 2024-11-06 04:51
PR is ready

cc: @Ollyws

**Comment by bernhardoj** [comment] 2024-11-22 11:21
Requested in ND.

**Comment by strepanier03** [comment] 2024-11-25 20:57
Thanks @bernhardoj!

Feel free to do the same @Ollyws - the payment summary is [here](https://github.com/Expensify/App/issues/51431#issuecomment-2493247776).

Per the SO I'm closing this since payments via ND don't require the GH to stay open.

**Closed by strepanier03** 2024-11-25 20:57 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-11-26 08:30
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment] 2024-11-26 13:48
$250 approved for @Ollyws
