### ISSUE TITLE
[$1000] Character limit error message appears for below 15k message with special characters

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18665] opened 2023-05-09 18:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat
2. copy character length of 149991
3. paste on send message
4. Observe Send message field

## Expected Result: 
App should not show character length error
## Actual Result: 
App show character length error of 15000. even pasted 149991 characters.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.12.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/87033cfc-32a7-4d03-9753-9216fc1f767b

<img width="949" alt="1" src="https://github.com/Expensify/App/assets/43996225/6045d2a0-1e00-4ce1-ab0e-019ec2323ae7">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683361183051679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0125dd8133e4fa58e1</li>
        <li>Upwork Job ID: 1656129697248456704</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-05-10 02:41
> copy character length of 149991

Please add sample text to the testing steps

**Comment by niravkakadiya25** [comment] 2023-05-10 02:43
@ja

**Comment by niravkakadiya25** [comment] 2023-05-10 02:44
@JmillsExpensify 
You can use samples text from below doc. I have 2-3 samples text with test case.

https://docs.google.com/document/d/1wayJlHDS86qkjtcsYKaX57Bjl7QWNxsHt75t3gC4IjY/edit?usp=sharing

**Comment by JmillsExpensify** [comment] 2023-05-10 02:50
Thanks! I confirmed that this is below the character count. I'm going to go ahead and open up to the community, though I vaguely remember us having this convo before about the exact length not being precisely the limit of 15k. Maybe someone else can remember or correct me!

**Comment by StevenKKC** [comment] 2023-05-10 07:09
There are two unicode characters in the sample text.
![1](https://github.com/Expensify/App/assets/131836113/4cc4a70e-91eb-464d-85fc-6e4965e6ab34)
![2](https://github.com/Expensify/App/assets/131836113/c83f7359-fee1-405c-bcb6-b8b00ba43c23)

A message's length is calculated by the getCommentLength function.
https://github.com/Expensify/App/blob/45c3212061983394e0919839248512874c2af83f/src/libs/ReportUtils.js#L1657-L1661

The above two unicode characters will be replaced by the string '\u????'
Due to this, the sample text's length will increase by 10 bytes, exceeding 15k.

I think this is not a bug.

**Comment by advaitasol9** [comment] 2023-05-10 07:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Character limit error message appears for below 15k message with special characters

### What is the root cause of that problem?
The comment's length is checked by this function
https://github.com/Expensify/App/blob/45c3212061983394e0919839248512874c2af83f/src/libs/ReportUtils.js#L1657-L1661
'getParsedComment' and 'replace(/[^ -~]/g, '\\u????')' increase the text's length if it has non-permissible characters and then returns the increased length. So the string user entered is less than 15k characters but they still see the error.

### What changes do you think we should make in order to solve the problem?
Now the solution depends on if we want to allow users to send such messages.

Solution 1 (not allowing user) :
In that case, we can keep everything as it is and show user some other error instead of character length error.
It will require the following changes:
from

https://github.com/Expensify/App/blob/45c3212061983394e0919839248512874c2af83f/src/components/ExceededCommentLength.js#L52-L56

to

<img width="925" alt="Screenshot 2023-05-10 at 1 04 03 PM" src="https://github.com/Expensify/App/assets/93445984/a7cf3052-4dae-4725-9304-2bdbb315be55">

Solution 1 (allowing user) :
In that case, we can change the 'getCommentLength' function to return the length of original text.
It will require the following changes:
from

https://github.com/Expensify/App/blob/45c3212061983394e0919839248512874c2af83f/src/libs/ReportUtils.js#L1657-L1661

to

<img width="336" alt="Screenshot 2023-05-10 at 1 08 34 PM" src="https://github.com/Expensify/App/assets/93445984/9ee4f658-b41d-43df-a86c-90df69bb63e0">

### What alternative solutions did you explore? (Optional)
None

**Comment by advaitasol9** [comment] 2023-05-10 07:42
Contributor details
Your Expensify account email: advaitasol9@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/tushar13

**Comment by mollfpr** [comment] 2023-05-15 04:51
I'm sorry for the delay.

@advaitasol9 I don't think changing the comment will be done much differently, and your second solution will lead us to this issue again https://github.com/Expensify/App/issues/13988

@wahaha999 I try your solution, and it's not working.

For context, this issue is related to https://github.com/Expensify/App/issues/13988, and the solution we move forward https://github.com/Expensify/App/issues/13988#issuecomment-1398990254


---

@JmillsExpensify @thienlnam I think this is expected and an edge-case, same as https://github.com/Expensify/App/issues/13988 but we solved it to prevent the API sent error.

**Comment by advaitasol9** [comment] 2023-05-17 13:31
Hi @mollfpr , i read through the issue thread you mentioned and while I agree that the solution there won't let the message (if longer than MAX_COMMENT_LENGTH) be sent to the backend. But thinking from a frontend user perspective, it might be confusing when they see something like 15003/15000 when only 4000 or 5000 emojis are typed.

Showing an error like 'Message too long!' might cover this edge case from frontend as well. What do you think?

**Comment by mollfpr** [comment] 2023-05-17 16:26
Thanks @advaitasol9, for your suggestion! 

Personally, I don't think sending 4000 emojis will be the case. For example, Twitter also didn't put any message on the exceeded length for the tweet and the emojis are only half of the limit characters.

![Screenshot 2023-05-17 at 23 21 45](https://github.com/Expensify/App/assets/25520267/4d23fa47-3c17-46d7-ab64-b7e0803c5108)

You always bring this to Slack and let others leave some thoughts regarding your suggestion.

cc @thienlnam @JmillsExpensify

**Comment by thienlnam** [comment] 2023-05-19 18:25
> @JmillsExpensify @thienlnam I think this is expected and an edge-case, same as https://github.com/Expensify/App/issues/13988 but we solved it to prevent the API sent error.

Yeah you're correct - this doesn't seem like a bug we need to solve 

Even if we updated the character count, you would still get an error from the back-end. Going to close this

**Closed by thienlnam** 2023-05-19 18:25 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by niravkakadiya25** [comment] 2023-05-26 02:47
@thienlnam  This is not the case for getting an error message. This is the case that I am not able to send messages even though I try to send less than 15K characters.
Thanks
