### ISSUE TITLE
Web - Connect bank account - Unchecked Checkbox and Unexpected Green Border When Hovering and Pressing Enter

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24327] opened 2023-08-09 16:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > workspace > Bank Account > Connect Manually.
2. Enter the incorrect Routing number and Account number.
3. Hover over the checkbox and press Enter.
4. Notice that instead of the checkbox getting checked as expected, a green border appears.

## Expected Result:
When hovering over the checkbox and pressing Enter, the checkbox should get checked, and no green border should appear.

## Actual Result:
When the checkbox is hovered over and Enter is pressed, the checkbox does not get checked. Instead, a green border appears, indicating an inconsistency with expected behavior.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.51-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/6fbaea57-ef15-4080-baf1-737a06de0206

https://github.com/Expensify/App/assets/115492554/4331ade2-1e26-4a8e-a7cd-45fc242a9504

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1690978271792559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tewodrosGirmaA** [comment] 2023-08-10 06:45
@bernhardoj let's explain, which one is not clear

**Comment by tewodrosGirmaA** [comment] 2023-08-10 07:49
I mean you press after hovering over the Cheack box

**Comment by Talha345** [comment] 2023-08-10 15:49
Not a bug, we are setting it here https://github.com/Expensify/App/blob/main/web/index.html#L57 for the entire web on focus-visible.

**Comment by sakluger** [comment] 2023-08-10 22:24
Enter will always submit the form, but if you tab to the checkbox and click space, it will select and unselect the checkbox. This is not a bug, so I'm going to close the issue.

**Closed by sakluger** 2023-08-10 22:24 UTC
Labels: Daily, Bug
