### ISSUE TITLE
Android - Go to Expensify Classic icon is black instead of green

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35468] opened 2024-01-31 12:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.34-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to Settings.

## Expected Result:
Go to Expensify Classic icon is green.

## Actual Result:
Go to Expensify Classic icon is black instead of green.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/bf785a00-8bd8-4df3-ae98-cb2b93eab3c6)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2024-01-31 13:04
Seems like regression from https://github.com/Expensify/App/pull/35097
cc: @barttom

**Comment by rlinoz** [comment] 2024-01-31 13:13
@barttom do you think you can raise a quick PR for this one?

**Comment by barttom** [comment] 2024-01-31 15:07
> @barttom do you think you can raise a quick PR for this one?

@rlinoz I’ll try later today, at least tomorrow

**Comment by francoisl** [comment] 2024-01-31 20:18
This is currently blocking the deploy, so if we can't get a fix before tomorrow, let's revert the offending PR @rlinoz?

**Comment by rlinoz** [comment] 2024-01-31 20:27
Yes, I will create the PR and request a CP, sorry for the delay.

**Comment by rlinoz** [comment] 2024-01-31 21:03
CP request: https://expensify.slack.com/archives/C07J32337/p1706734984165219

**Comment by rlinoz** [comment] 2024-01-31 21:11
Removing deploy blocker label since revert was CP'd

**Comment by rlinoz** [comment] 2024-02-26 16:29
Closing this one in favor of https://github.com/Expensify/App/issues/35018, as the fix proposal is in there and the PR is already in staging.

**Closed by rlinoz** 2024-02-26 16:29 UTC
Labels: Reviewing, Engineering, Monthly
