### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] Thread - Blue "Thread" above the parent message in thread is disable

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43190] opened 2024-06-06 16:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4601125&group_by=cases:section_id&group_order=asc&group_id=291937
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Send a message.
4. Right click on the message > Reply in thread.

## Expected Result:
The blue "Thread" above the parent message should be clickable (production behavior).

## Actual Result:
The blue "Thread" above the parent message is disable.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/f9dda743-828d-4215-8a17-e9c7783687b8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by m-natarajan** [comment] 2024-06-06 16:09
@marcochavezf FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-06 16:09
We think that this bug might be related to #vip-vsb

**Comment by neil-marcellini** [comment] 2024-06-06 18:07
Fixed by [[CP Staging] Revert "Fix get all ancestors in a thread"](https://github.com/Expensify/App/pull/43201#top)

https://github.com/Expensify/App/assets/26260477/de2722b3-2889-4d11-ad29-a84d77916130

**Comment by kmbcook** [comment] 2024-06-06 20:25
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Thread - Blue "Thread" above the parent message in thread is disable

### What is the root cause of that problem?
The root cause stems from https://github.com/Expensify/App/pull/34640 where ReportUtils.getAllAncestorReportActions was originally written. We now know this because fixing that root cause in https://github.com/Expensify/App/pull/42554 causes this regression. See https://github.com/Expensify/App/issues/41519#issuecomment-2093608757 for details.

### What changes do you think we should make in order to solve the problem?
Address the root cause by using the correct ancestor reportID, instead of leaving the root cause in place and reverting https://github.com/Expensify/App/pull/42554.

**Comment by twisterdotcom** [comment] 2024-06-20 11:02
Okay, looks like https://github.com/Expensify/App/pull/43518 is still open. @rushatgabhane's C+ review will be handled in https://github.com/Expensify/App/issues/41519.

Nothing else to do here.

**Closed by twisterdotcom** 2024-06-20 11:02 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
