### ISSUE TITLE
[$500] Download option not showing on web on "Share code"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33815] opened 2024-01-01 00:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @MitchExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704067710491769

## Action Performed:

1. Go to Settings
2. Share code

## Expected behavior:
Download option should exist

## Actual Result:
Download option does not exist

## Workaround:
Right click to download

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Snip - (1) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/5c31ba60-5b2c-40ea-8b9d-7b61a4bbef72)

![image (6)](https://github.com/Expensify/App/assets/38435837/c0e63cf1-7e0a-4e60-a039-2e87b6bd09cc)

![image (5)](https://github.com/Expensify/App/assets/38435837/2e3acd8f-f73c-4a6b-b070-9b6db8ef1aab)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145c04d294d320411</li>
        <li>Upwork Job ID: 1741623023415963648</li>
        <li>Last Price Increase: 2024-01-01</li>
    </ul>
</details>

**Comment by situchan** [comment] 2024-01-01 01:11
Dupe of https://github.com/Expensify/App/issues/19032

**Comment by Tony-MK** [comment] 2024-01-01 01:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Download option not showing on the web on "Share code"

### What is the root cause of that problem?

We only show the download option for only `iOS` and `Android` platforms.

https://github.com/Expensify/App/blob/af69ba7176d695d40e7c74cc2fe067348ea0ea20/src/pages/ShareCodePage.js#L77-L78

https://github.com/Expensify/App/blob/af69ba7176d695d40e7c74cc2fe067348ea0ea20/src/pages/ShareCodePage.js#L111-L119

### What changes do you think we should make in order to solve the problem?


Handle `macOS` platforms by opening a new tab to download the `macOS` application. This is almost similar to the `AppDownloadLinks` page in the `About` section.

```

{platform === CONST.PLATFORM.WEB && ( 
     <MenuItem 
         isAnonymousAction 
         title={this.props.translate('common.download')} 
         icon={Expensicons.Download} 
         // eslint-disable-next-line es/no-optional-chaining 
         onPress={() => Link.openExternalLink(CONST.APP_DOWNLOAD_LINKS.DESKTOP)} 
     /> 
 )} 

```

**Comment by njmulsqb** [comment] 2024-01-01 11:22
> This will be handled here: #19834

There's slight confusion. Is this going to be handled internally and there's no opportunity for external contributors?

**Comment by njmulsqb** [comment] 2024-01-01 11:23
Contributor details
Your Expensify account email: najum98@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0191785ee40bb1eec0

**Comment by dawoodtrumboo** [comment] 2024-01-01 22:13
After investigating the issue, I believe the problem stems from the isNative property , making changes to it fixes the problem. Its working on both chrome and safari/ MacOS
<img width="1438" alt="Screenshot 2024-01-02 at 3 40 40 AM" src="https://github.com/Expensify/App/assets/107537057/fdfc59d4-586f-4485-b134-5d96dd784b6c">

**Comment by wcardosodev** [comment] 2024-01-01 22:29
Contributor details
Your Expensify account email: wcardosodev@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013348315c098ddb1e

**Comment by dawoodtrumboo** [comment] 2024-01-01 23:09
The Download button is not showing up in MacOS (Chrome & Safari)

The problem is the isNative property which hasn't been assigned the WEB platform

Adding isaNative  == CONST.PLATFORM.WEB displays the download button.

I tested this solution on my system, but while looking at the code, I guess the button has only been created for mobile apps and not for web. The above solution did fix the problem but then another issue arises. Corrupted image is download.
That fix maybe for some other issue, so I'm proposing this solution for now and will look into that issue and if that issue is raised here, hopefully I would've found the solution by then for that.

**Comment by kaushiktd** [comment] 2024-01-02 06:19
### Please re-state the problem that we are trying to solve in this issue.

Download option not showing on web on "Share code"

### What is the root cause of that problem?

On `ShareCodePage.js`, there's a variable called `isNative`, and this variable is causing an issue because it satisfies a condition only for Android and iOS. [Check Here](https://github.com/Expensify/App/blob/main/src/pages/ShareCodePage.js#L78).

### What changes do you think we should make in order to solve the problem?

If you want to show download button on share code for the web platform. You'll need to adjust isNative condition accordingly.

```
const isNative = platform === CONST.PLATFORM.IOS || platform === CONST.PLATFORM.ANDROID || platform === CONST.PLATFORM.WEB;
```

### What alternative solutions did you explore? (Optional)

You can remove `isNative` condition from below line#
https://github.com/Expensify/App/blob/main/src/pages/ShareCodePage.js#L111

### Screenshot:
![Screenshot 2024-01-02 at 11 47 18 AM](https://github.com/Expensify/App/assets/43398804/337b5b96-f080-474c-b433-5e02fe77a3be)

**Comment by Christinadobrzyn** [comment] 2024-01-02 18:19
I agree this is going to be handled here - https://github.com/Expensify/App/issues/19834

to your question @njmulsqb 

> There's slight confusion. Is this going to be handled internally and there's no opportunity for external contributors?

Correct, `Interally` usually means an internal engineer and a member of contributor plus is going to work on this but feel free to reach out in https://github.com/Expensify/App/issues/19834 if you'd like to see if there's anything you can do to help! 

Closing this in favour of https://github.com/Expensify/App/issues/19834

**Closed by Christinadobrzyn** 2024-01-02 18:19 UTC
Labels: External, Daily, Help Wanted, Bug
