### ISSUE TITLE
[$250] [HOLD RHP navigation][Search v1] - Hold education modal is shaking

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42761] opened 2024-05-29 13:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** No, this is from testing preference section
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Submit a new expense.
2. Put it on hold.
3. Close the education modal by clicking outside it.
4. Go to the new search page.
5. Click "View" on the expense which has been held.

## Expected Result:
Hold education modal should be stable

## Actual Result:
Hold education modal is shaking when open via New search page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/9b5011b6-6d98-468b-9b5c-b6cc9948bf38

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01366c97749a0724f1</li>
        <li>Upwork Job ID: 1797620271220514816</li>
        <li>Last Price Increase: 2024-06-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by m-natarajan** [comment] 2024-05-29 13:24
@twisterdotcom FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by twisterdotcom** [comment] 2024-06-03 13:02
What do we mean by shaking here? Is it just that we load the expense and then quickly the hold modal?
<img width="438" alt="image" src="https://github.com/Expensify/App/assets/9133401/299026c4-bba4-4276-96b8-b805c0da45d6">

I can recreate and do think we should fix, but want to make sure I understand.

**Comment by twisterdotcom** [comment] 2024-06-03 13:23
Nice okay. Happy to make this External. I do disagree about creating a separate modal, ideally it's all in the right pane for consistency.

**Comment by Kicu** [comment] 2024-06-03 13:36
Please be advised that the logic of opening transactions/IOU/chats etc from `SearchPage` in right hand navigation is something that is still being actively discussed and worked on.
Some details this behaviour and how navigation works might change.

CC @adamgrzybowski @WojtekBoman @luacmartins

**Comment by ikevin127** [comment] 2024-06-03 19:25
@luacmartins I assume that I should be holding on reviewing the proposals until the RHP navigation is sorted out as per https://github.com/Expensify/App/issues/42761#issuecomment-2145226517 mentioned ?

**Comment by luacmartins** [comment] 2024-06-03 19:28
Yea, let's hold on that.

**Comment by ikevin127** [comment] 2024-06-06 18:35
Currently holding on reviewing the proposals until the RHP navigation is sorted out as per https://github.com/Expensify/App/issues/42761#issuecomment-2145226517.

**Comment by luacmartins** [comment] 2024-07-23 20:27
@m-natarajan could you retest this issue please? If we can't reproduce it anymore we can just close it

**Comment by luacmartins** [comment] 2024-07-29 22:31
This is no longer reproducible. Closing.

**Closed by luacmartins** 2024-07-29 22:31 UTC
Labels: External, Engineering, Monthly, Help Wanted, Bug
