### ISSUE TITLE
Web - "There was a problem removing that workspace member" when trying remove a member from a workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26334] opened 2023-08-30 20:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Add a member to a workspace
2. Go to the newly created room with that member
3. Leave the room
4. Go to the workspace and remove the member

## Expected Result:
The member should be removed

## Actual Result:
There was a problem removing that workspace member

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[bug-remove-member.webm](https://github.com/Expensify/App/assets/93399543/8fd1b9ca-c03d-49c9-bce3-6f95db0018d1)

https://github.com/Expensify/App/assets/93399543/3039ec96-ff4d-41e6-b2bd-5b71141b3fa2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692870821571869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jayeshmangwani** [comment] 2023-08-30 20:49
@trjExpensify This issue will be solved after this [PR](https://github.com/Expensify/App/pull/26298) hits the staging, on the main branch This issue can not be reproduced because we can not access the `Leave room` option now.

cc: @Beamanator

**Comment by Beamanator** [comment] 2023-08-31 13:04
Agreed, thanks @jayeshmangwani - the App PR is now on staging so feel free to retest, but i believe it should be good to close

**Comment by trjExpensify** [comment] 2023-08-31 15:22
Alrighty, looks like we're good here. Closing!

**Closed by trjExpensify** 2023-08-31 15:22 UTC
Labels: Daily, Bug
