### ISSUE TITLE
[$250] Can't go back in "Contact methods" if triggering "Back" button using Enter

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29132] opened 2023-10-09 22:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.79-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kosmydel 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696849230849869

## Action Performed:
1. Go to Settings -> Profile -> Contact method
2. Select the "Back" button using Tab.
3. Press Enter
## Expected Result:
Should go back to the previous screen
## Actual Result:
Opens the "New contact method" screen and immediately closes it.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/c08178af-b155-4a6b-9b62-7f8eab4a0f4d

https://github.com/Expensify/App/assets/38435837/7a0099aa-7884-4707-98e2-d5547afcded9

</details>

<details>
<summary>MacOS: Desktop</summary>

.

https://github.com/Expensify/App/assets/38435837/fe211360-781c-4877-9c71-99a6f29e1bbe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d24f78857b6fbc3</li>
        <li>Upwork Job ID: 1711509906241732608</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by cead22** [comment] 2023-10-10 00:20
This looks like a simple bug, and I imagine the solution will be simple as well, so I decreased the bounty

**Comment by Victor-Nyagudi** [comment] 2023-10-10 07:30
A [pull request](https://github.com/Expensify/App/pull/28374) affecting the <kbd>Enter</kbd> key's behavior got merged and recently deployed to production. 

It could provide some insight on why this issue occurred.

**Comment by FitseTLT** [comment] 2023-10-10 13:18
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
On Contact Methods page after focusing on the back button with the `Tab` key and pressing enter; it doesn't navigate back
### What is the root cause of that problem?
Because there is the new contact methods button with `pressOnEnter` enabled, in addition to the navigate back code the create new contact methods' code is also executed. So that's why the page will navigate to the new contact page and it will get back to the contact methods page(instead of navigating back to the profiles page).
### What changes do you think we should make in order to solve the problem?

This problem must exist everywhere there is a `Button` component with `pressOnEnter` enabled. So the fix should be applied to our `Button` component.
Changes to be applied:
Here,
https://github.com/Expensify/App/blob/a6d2f3e3564c19f32caba3837a81adc837f6c752/src/components/Button/index.js#L181-L185
we need additional logic to check if the focus is not on another element (it should be on the button element or on its parent) so it should be changed to
`
if(document.activeElement.contains(this.ref.current))
                this.props.onPress();
`
POC:
https://github.com/Expensify/App/assets/38649957/2a9e55d2-01be-4cdd-b2a0-faaf5000f46d
### What alternative solutions did you explore? (Optional)
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by cead22** [comment] 2023-10-10 18:49
Closing per https://github.com/Expensify/App/issues/29132#issuecomment-1754652679

**Closed by cead22** 2023-10-10 18:49 UTC
Labels: External, Daily, Help Wanted, Bug
