### ISSUE TITLE
[HOLD for payment 2023-07-28] [$1000] Web -Default avatar is changed when we select/unselect a member in Workspace invitation page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22085] opened 2023-07-02 22:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any Workspace
2. Click Invite button in top header
3. Invite an member that you haven't chatted before
4. Select member in search result list
5. Unselect above selecting member

## Expected Result:
The default avatar of member should be same every time we select/unselect

## Actual Result:
The default avatar of member is changed every time we select/unselect

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ad059425-9d0d-44a3-81cf-c3cff15fce64

https://github.com/Expensify/App/assets/93399543/46f5fd3e-4d11-41ea-8781-9ef956b2bdc7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hoangzinh
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688232507431689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018119c930be0fc798</li>
        <li>Upwork Job ID: 1676185302459514880</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by DrLoopFall** [comment] 2023-07-04 14:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The default avatar is changed whenever the member is unselected from the invitation page.

### What is the root cause of that problem?
We use `optimisticAccountID` to generate the avatar, but `optimisticAccountID` changes whenever the member is unselected, resulting in a different avatar.

### What changes do you think we should make in order to solve the problem?
Generate `optimisticAccountID` based on login/search which would result in the same avatar for that login.

```js
function generateAccountID(login) {
	// can't use hashText, it returns a 32bit integer
    return hash(login);
    
	// or
	const hash = hashText(login)
	return Number(`${hash}${hashText(login + hash)}`)
}
```

**Comment by DrLoopFall** [comment] 2023-07-06 08:06
Hi @allroundexperts,
Please read the proposals again, I [proposed](https://github.com/Expensify/App/issues/22085#issuecomment-1620332816) to generate **`optimisticAccountID` based on the search term**, whereas @dukenv0307 [proposed](https://github.com/Expensify/App/issues/22085#issuecomment-1620110078) to generate the default **avatar based on search term**, not to generate the `optimisticAccountID`.

**Comment by eh2077** [comment] 2023-07-06 09:28
@akinwale may also have a proposal for this from a previous issue.

**Comment by puneetlath** [comment] 2023-07-06 20:38
>I agree with @dukenv0307's https://github.com/Expensify/App/issues/22085#issuecomment-1620110078. I think we should generate optimistic account id based on the search term that the user entered. 

That seems reasonable to me.

**Comment by akinwale** [comment] 2023-07-07 09:50
This issue appears to be related to https://github.com/Expensify/App/issues/21543, as it's the same cause (using the optimistic ID to generate the avatar).

That was closed as [expected behaviour](https://github.com/Expensify/App/issues/21543#issuecomment-1614827152).

**Comment by dylanexpensify** [comment] 2023-07-11 18:18
Mind posting an update on this today @allroundexperts? 🙇‍♂️

**Comment by dylanexpensify** [comment] 2023-07-12 08:43
@allroundexperts mind giving us an update please? 🙏

**Comment by Julesssss** [comment] 2023-07-12 10:50
Happy to move forward here, but why not [hash the email](https://expensify.slack.com/archives/C01GTK53T8Q/p1688925076829199?thread_ts=1688915163.658279&cid=C01GTK53T8Q) instead of taking the first 4 digits?

**Comment by akinwale** [comment] 2023-07-12 10:59
> After discussion on Slack, we decided to fix this any ways. I'd agree that instead of generating avatars based on the login, we should generate optimistic ids based on the login. I think @dukenv0307 is correct in pointing out that his alternate solution proposed this earlier then anyone else. As such, lets go with there alternate [proposal](https://github.com/Expensify/App/issues/22085#issuecomment-1620110078) since they were the first.
> 
> @dukenv0307 I think the hashing you've suggested can be simplified so lets keep that in mind while creating the PR.
> 
> 🎀 👀 🎀 C+ reviewed

If the plan is to fix this, what happens to the earlier reported issue that was closed seeing as it's the same root cause and solution?

**Comment by DrLoopFall** [comment] 2023-07-13 05:45
> > Happy to move forward here, but why not [hash the email](https://expensify.slack.com/archives/C01GTK53T8Q/p1688925076829199?thread_ts=1688915163.658279&cid=C01GTK53T8Q) instead of taking the first 4 digits?
> 
> Yep. That's what I suggested as well. I think @dukenv0307 will handle that in his PR.

@allroundexperts and @Julesssss May I know how this is different from what I suggested in my [proposal](https://github.com/Expensify/App/issues/22085#issuecomment-1620332816)?

**Comment by akinwale** [comment] 2023-07-20 15:28
> I think you should get the reporting bonus. But the solution which you proposed was about generating avatars based on the emails instead of generating optimistic ids.

@allroundexperts I did not get an offer for the reporter role. Will this be corrected?

**Comment by dylanexpensify** [comment] 2023-08-03 11:19
Reviewing now!

**Comment by dylanexpensify** [comment] 2023-08-03 11:21
@akinwale mind applying [here](https://www.upwork.com/jobs/~018119c930be0fc798)?? 🙇‍♂️

**Comment by akinwale** [comment] 2023-08-03 11:25
> @akinwale mind applying [here](https://www.upwork.com/jobs/~018119c930be0fc798)?? 🙇‍♂️

Applied! Thanks.

**Comment by Julesssss** [comment] 2023-08-07 10:25
Bump for payment summary @dylanexpensify

**Comment by dylanexpensify** [comment] 2023-08-10 10:18
Payment Summary:

- Issue reporter: @akinwale $250
- Contributor +: @allroundexperts $1,000
- Contributor: @dukenv0307 $1,000

Upwork job [here](https://www.upwork.com/jobs/~018119c930be0fc798)

**Comment by dylanexpensify** [comment] 2023-08-10 10:22
reviewing!

**Comment by dylanexpensify** [comment] 2023-08-10 10:23
Correct! Updating prices!

**Comment by dylanexpensify** [comment] 2023-08-10 10:24
Updated! Thanks @allroundexperts!

**Comment by dylanexpensify** [comment] 2023-08-10 10:27
@akinwale sent offer!

**Comment by akinwale** [comment] 2023-08-10 10:29
> @akinwale sent offer!

Accepted, thanks!

**Comment by dylanexpensify** [comment] 2023-08-10 10:32
Everything done here - just pending C+ ND payout!

**Comment by dylanexpensify** [comment] 2023-08-10 11:09
That's fair, yes you can. Updated comment

**Comment by dylanexpensify** [comment] 2023-08-10 11:10
Paid @hoangzinh

**Comment by dylanexpensify** [comment] 2023-08-11 19:55
Waiting for @allroundexperts to be paid

**Comment by dylanexpensify** [comment] 2023-08-14 12:17
@allroundexperts you're paid in NewDot right?

**Comment by dylanexpensify** [comment] 2023-08-14 12:21
Ahh got it! Mind applying at the above job then? I'll get you sorted today!

**Comment by dylanexpensify** [comment] 2023-08-14 12:23
Ah I see, I thought you meant not yet as in not paid via new dot yet 😅 sounds good!

**Closed** 2023-08-15 20:10 UTC
Labels: External, Daily, Awaiting Payment, Bug
