### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Chat - A line break is resulted from pasting quote message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20725] opened 2023-06-13 22:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat with quote message
3. Copy the quote message
4. Paste the quote message in the composer

## Expected Result:
There is no extra space or line break from pasting the quote message

## Actual Result:
A line break is resulted from pasting the quote message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e89b0099-cae8-4f07-b479-5b7199c2d699

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018cc9d1380c77d6b3</li>
        <li>Upwork Job ID: 1668901682244857856</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by Nikhil-Vats** [comment] 2023-06-13 22:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A line break is resulted from pasting quote message.

### What is the root cause of that problem?
For pasting HTML, we use expensify-common -
https://github.com/Expensify/App/blob/d7c45a2e8e776f345f566f0cf1ae6d08f7c2e8a0/src/components/Composer/index.js#L280-L283

In expensify-common quote rule for `htmlToMarkdown`, we add new line at the beginning and end of the return value here -

https://github.com/Expensify/expensify-common/blob/9dfabe1de4213b0fd60ae3aa6a57012dd6545c72/lib/ExpensiMark.js#L289-L299
```javascript
return `\n${resultString}\n`;
```

### What changes do you think we should make in order to solve the problem?
Remove `\n` from beginning and end of return value to make line 299 in expensify-common -
```javascript
return `${resultString}`;
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by eh2077** [comment] 2023-06-14 02:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

A line break is resulted from pasting quote message.

### What is the root cause of that problem?

Copying a quote comment, like

```
> test
```

save following html

```html
<meta charset='utf-8'><div><div><comment><blockquote>test</blockquote></comment></div></div>
```

to clipboard, see

https://github.com/Expensify/App/blob/0a471b016d9b36c986a81680ef2518d2ae749937/src/components/CopySelectionHelper.js#L40

Pasting into composer converts the above html to following markdown

```
> test
```

See [quote-html-to-markdown rule](https://github.com/Expensify/expensify-common/blob/9dfabe1de4213b0fd60ae3aa6a57012dd6545c72/lib/ExpensiMark.js#L299) translates html piece

```html
<blockquote>test</blockquote>
```

to text

```
> test

```

And the ending line break is removed in method [replaceBlockElementWithNewLine](https://github.com/Expensify/expensify-common/blob/9dfabe1de4213b0fd60ae3aa6a57012dd6545c72/lib/ExpensiMark.js#L525-L531) when stripping `<div>` tags. That's in the composer we get

```
> test
```

Instead of 

```
> test

```

### What changes do you think we should make in order to solve the problem?

As changing the [quote-html-to-markdown rule](https://github.com/Expensify/expensify-common/blob/9dfabe1de4213b0fd60ae3aa6a57012dd6545c72/lib/ExpensiMark.js#L299) will break exiting unit test cases of Expensify-common, so I think we can fix this issue in App codebase.

To fix this issue, I think we can just trim the result of `parser.htmlToMarkdown(html)` in method `handlePastedHTML`

https://github.com/Expensify/App/blob/0a471b016d9b36c986a81680ef2518d2ae749937/src/components/Composer/index.js#L279-L284

### What alternative solutions did you explore? (Optional)

N/A

**Comment by conorpendergrast** [comment] 2023-06-14 08:38
Weird, I wonder if this is a regression. 

I see this happening and so it's reproducible: 

<img width="529" alt="image" src="https://github.com/Expensify/App/assets/5802477/ea51f5f0-d346-4143-981b-7c6d57f2304f">

After sending the message though, it doesn't show the line breaks:

<img width="544" alt="image" src="https://github.com/Expensify/App/assets/5802477/34c164b0-cb8f-4eca-b7e3-6d7651657755">

**Comment by Nikhil-Vats** [comment] 2023-06-14 09:09
@conorpendergrast I don't think it is a regression because the code I  have specified as root cause in my proposal is from 2 years ago but I am also skeptical as to why it went unnoticed for such a long time (if it really isn't a regression).

**Comment by narefyev91** [comment] 2023-06-14 14:26
@Nikhil-Vats @eh2077 Hey guys! The issue exists inside expensify-common and should be fixed inside it, we should avoid workarounds here. BTW i checked out some old branch and saw the same issue with empty line above and below. The last changes were done for quotes around 2 weeks ago. But it's not really influence on this bug - still see the same on old branches.

**Comment by Nikhil-Vats** [comment] 2023-06-14 14:28
@narefyev91 my change is only in Expensify commons not in this repo and it is not a workaround.

**Comment by narefyev91** [comment] 2023-06-14 14:31
@conorpendergrast let's assign @Nikhil-Vats to this ticket

**Comment by conorpendergrast** [comment] 2023-06-14 16:21
Nice! Assigned @Nikhil-Vats and sent contract in Upwork. 

@narefyev91 I haven't hired you through Upwork, as you're a Callstacker! If that's wrong, please let me know

**Comment by Nikhil-Vats** [comment] 2023-06-14 16:23
Thanks for assigning me this job. I will have the PR ready for review within 24 hours.

**Comment by iwiznia** [comment] 2023-06-14 16:59
Proposal looks good to me

**Comment by ristovkiril** [comment] 2023-06-14 17:17
### PROPOSAL

I solved this problem using the _onPaste_ event, so when this event is called I do _event.preventDefault()_ and then I take the pasted value and delete the first and last newline, so I solve the problem if it is copied from _quote_ and it is additionally solved if it is copied from another place.

`
onPaste={(event) => {
                            event.preventDefault();
                            const pastedText = event.clipboardData.getData('text').trim();
                            event.target.value += ` ${pastedText}`.trim();
                           }}
`

**Comment by ristovkiril** [comment] 2023-06-14 17:22
Contributor details
Your Expensify account email: ristov.kiril@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0192324f7a1802b375

**Comment by marlon-lozano** [comment] 2023-06-15 02:48
Contributor details
Your Expensify account email: marlon.lozano.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012d06c83909c7f4a9

**Comment by spcheema** [comment] 2023-06-15 03:22
@Nikhil-Vats I saw this one lie change as well. But when you posted the comment so I refrain to reiterate the same but doesn't mean I have to do everywhere.

**Comment by narefyev91** [comment] 2023-06-16 09:20
@Nikhil-Vats Hey! Any updates for initial PR?

**Comment by Nikhil-Vats** [comment] 2023-06-16 11:40
@narefyev91 It is taking more time than expected because the solution I proposed has regressions. Here's the detailed behaviour of what happens -

1. the extra line is added in composer **before** message only when message **starts** with a quote. eg -
```
> a quote message
a text message
_italics message_
> another quote
> empty line quote below
>
this doesn't end with a quote
```
2. the extra line is added in composer **after** message only when message **ends** with a quote. eg -
```
this starts with a text message
_italics message_
> another quote
> empty line quote below
>
> ends with a quote
```
3. So, when message starts and ends with a quote (or it is just a single line message which is a quote) then we have new lines in start and end. eg -
```
> start quote
you can also try this behaviour with just 1 line which is a quote
> end quote
```

My current solution has regressions because the new lines are needed when quotes are anywhere between the message like -
```
any message in any markdown like heading, etc. new line below

> quote

ending message after newline above
```
https://github.com/Expensify/expensify-common/blob/9dfabe1de4213b0fd60ae3aa6a57012dd6545c72/lib/ExpensiMark.js#L289-L299
```javascript
return `\n${resultString}\n`;
```

So, if we simply remove the `\n` in the beginning and end it is going to trim some new lines that are needed. I am trying an alternate solution without any regression now but you can unassign me for the moment to get other contributors' inputs if you want.

**Comment by narefyev91** [comment] 2023-06-16 12:23
> @narefyev91 It is taking more time than expected because the solution I proposed has regressions. Here's the detailed behaviour of what happens -
> 
> 1. the extra line is added in composer **before** message only when message **starts** with a quote. eg -
> 
> ```
> > a quote message
> a text message
> _italics message_
> > another quote
> > empty line quote below
> >
> this doesn't end with a quote
> ```
> 
> 2. the extra line is added in composer **after** message only when message **ends** with a quote. eg -
> 
> ```
> this starts with a text message
> _italics message_
> > another quote
> > empty line quote below
> >
> > ends with a quote
> ```
> 
> 3. So, when message starts and ends with a quote (or it is just a single line message which is a quote) then we have new lines in start and end. eg -
> 
> ```
> > start quote
> you can also try this behaviour with just 1 line which is a quote
> > end quote
> ```
> 
> My current solution has regressions because the new lines are needed when quotes are anywhere between the message like -
> 
> ```
> any message in any markdown like heading, etc. new line below
> 
> > quote
> 
> ending message after newline above
> ```
> 
> https://github.com/Expensify/expensify-common/blob/9dfabe1de4213b0fd60ae3aa6a57012dd6545c72/lib/ExpensiMark.js#L289-L299
> 
> ```js
> return `\n${resultString}\n`;
> ```
> 
> So, if we simply remove the `\n` in the beginning and end it is going to trim some new lines that are needed. I am trying an alternate solution without any regression now but you can unassign me for the moment to get other contributors' inputs if you want.

no worries - let's get it fix correctly and find solution which will work

**Comment by ristovkiril** [comment] 2023-06-16 12:23
Should it only be fixed if a **quote**  is copied?

**Comment by narefyev91** [comment] 2023-06-16 12:27
I think that it should work in the same way for any html which we may copy and paste - no new lines should be added above and below

**Comment by ristovkiril** [comment] 2023-06-16 12:42
This will work only on Input that have this event
<code>
onChangeText={(text) => {
                    let newValue = text.replace(term, '');
                    // If newValue is > 1 then its pasted value, then replace that value with trim()
                    if (newValue.length > 1) {
                        text = text.replace(newValue, newValue.trim());
                        console.log(text);
                    }
                    onChange(text);
                }}
</code>

**Comment by conorpendergrast** [comment] 2023-06-22 11:27
@Nikhil-Vats @narefyev91 Are we still making progress on the solution here? Can I help with anything?

**Comment by narefyev91** [comment] 2023-06-22 11:33
> @Nikhil-Vats @narefyev91 Are we still making progress on the solution here? Can I help with anything?

@conorpendergrast - we need to get some information from @Nikhil-Vats - are there any working fix, if not - we can open this again for proposals - but the root case was found correctly - only needs to get correct solution for this one

**Comment by Nikhil-Vats** [comment] 2023-06-22 12:59
@conorpendergrast @narefyev91 Apologies for the delay, I haven't been able to find a solution that fixes the root cause. I think you should open this for proposals again and meanwhile, I will continue to find a solution for this and put a new proposal if I do find one.

**Comment by eh2077** [comment] 2023-06-22 14:58
### Proposal

Updated [proposal](https://github.com/Expensify/App/issues/20725#issuecomment-1590344432) to let method [replaceBlockElementWithNewLine](https://github.com/Expensify/expensify-common/blob/f9985d572c772757885ff59ea5c82b1050c6b3f7/lib/ExpensiMark.js#L525) handle line break for `<blockquote>` tag, like what we do for `<h1>` tag, see [here](https://github.com/Expensify/expensify-common/blob/f9985d572c772757885ff59ea5c82b1050c6b3f7/lib/ExpensiMark.js#L270).

**Comment by conorpendergrast** [comment] 2023-06-22 19:50
Ok, two more proposals: https://github.com/Expensify/App/issues/20725#issuecomment-1602774224 and https://github.com/Expensify/App/issues/20725#issuecomment-1590344432

**Comment by narefyev91** [comment] 2023-06-23 06:43
@eh2077 can you please provide a video how it's working now with your changes?

**Comment by eh2077** [comment] 2023-06-23 06:56
@narefyev91 Sure! Here's the demo video FYI

https://github.com/Expensify/App/assets/117511920/eb881d21-e8f5-4bf3-8bb1-e6686e525c10

I verified that the solution to use method [replaceBlockElementWithNewLine](https://github.com/Expensify/expensify-common/blob/f9985d572c772757885ff59ea5c82b1050c6b3f7/lib/ExpensiMark.js#L525) won't break existing unit test cases of expensify-common repo. We only need to correct a few unit test cases by removing unwanted line breaks added by

```js
return `\n${resultString}\n`;
```

**Comment by narefyev91** [comment] 2023-06-23 10:21
> @narefyev91 Sure! Here's the demo video FYI
> 
>  Screen.Recording.2023-06-23.at.2.50.13.PM.mov 
> I verified that the solution to use method [replaceBlockElementWithNewLine](https://github.com/Expensify/expensify-common/blob/f9985d572c772757885ff59ea5c82b1050c6b3f7/lib/ExpensiMark.js#L525) won't break existing unit test cases of expensify-common repo. We only need to correct a few unit test cases by removing unwanted line breaks added by
> 
> ```js
> return `\n${resultString}\n`;
> ```

can you please make tests for all items listed here https://github.com/Expensify/App/issues/20725#issuecomment-1594542611 and post a video

**Comment by narefyev91** [comment] 2023-06-26 10:22
Proposal of @eh2077 https://github.com/Expensify/App/issues/20725#issuecomment-1590344432 looks good to me, it's fixed root case of the issue and based on the test - working as expected
🎀 👀 🎀 C+ reviewed

**Comment by narefyev91** [comment] 2023-06-26 10:55
> @narefyev91 Can I request you to review my alternate solution.
> 
> I know it's inspired from his solution but his solution isn't complete for all test cases.

Yes i saw that most of the changes is the same as proposed @eh2077 - the only difference that you change regExp - if you are saying that _his solution isn't complete for all test cases._ - can you maybe show on a video what do you mean, please.

**Comment by eh2077** [comment] 2023-06-26 11:28
I think the minor issue will be able to be solved in the PR preparing or reviewing stage.

**Comment by eh2077** [comment] 2023-06-26 11:47
> But I spent my time to find the issue and my solution does cover it.
> 
> The original issue itself minor then. If we consider line break removal as minor

I don't think it's your solution as it's literally same as my proposal. It'll be easy to fix the minor issue when preparing the PR as the issue is about copy and pasting quotes. Thanks for the discussion and I think you can have a look at other open issues.

**Comment by narefyev91** [comment] 2023-06-26 15:08
@deetergp please check this conversation for decision https://expensify.slack.com/archives/C02NK2DQWUX/p1687781331427029

**Comment by conorpendergrast** [comment] 2023-06-27 09:53
This was double-assigned to an engineer, so unassigning @deetergp in favour of @iwiznia (who was already assigned). Ionatan will also check in on the thread and we'll come back to this issue with a decision. Thanks for holding, all

**Comment by eh2077** [comment] 2023-06-27 18:22
PR will be ready by the end of today.

**Comment by iwiznia** [comment] 2023-06-27 23:40
No? We only pay to the contributor we hire.

**Comment by conorpendergrast** [comment] 2023-06-30 10:08
@eh2077 @narefyev91 Could you take a look at this somewhat similar issue and see if the fix here would resolve that too? 
 https://github.com/Expensify/App/issues/21903

**Comment by narefyev91** [comment] 2023-06-30 10:13
@conorpendergrast yes it's the same issue and should be fixed based on opened PR

**Comment by conorpendergrast** [comment] 2023-06-30 13:35
Thanks for confirming!

**Comment by conorpendergrast** [comment] 2023-07-03 14:54
Oh, the PR is under review. Marking as such!

**Comment by conorpendergrast** [comment] 2023-07-11 08:35
Ah, I withdrew the initial contract and re-sent to @eh2077

**Comment by conorpendergrast** [comment] 2023-07-18 16:45
Payment made to @eh2077. Final step is the checklist for @narefyev91 to complete, please!

**Comment by narefyev91** [comment] 2023-07-18 17:09
- The PR that introduced the bug has been identified - it was fully new requirements and fixes to make it working during pasting - i can say that those code changes fix any regression from someone - it was fully missed implementation
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - no comments
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - no discussions
- Determine if we should create a regression test for this bug - in case that it's not a regression - we are good to not have any steps here

**Closed** 2023-07-18 18:35 UTC
Labels: External, Daily, Awaiting Payment, Bug
