### ISSUE TITLE
[$500] Android-Chat-Tapping "Go back to home page", user directed to concierge page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32856] opened 2023-12-11 19:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.11
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Workspaces --- Workspace
4. Tap first Workspace " Vincenzoddragon+98's Workspace "
5. Tap question mark on top
6. Tap chat with concierge
7. Tap with " Enter the amount" link
8. Tap "Go back to home page"

## Expected Result:
When user taps on "Go back to home page", he must be directed to home page

## Actual Result:
When user taps on "Go back to home page", he is directed to concierge page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/aed5e74f-5296-4eac-ada9-90f08bf34d62

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae40b53cb7ec7aed</li>
        <li>Upwork Job ID: 1734300145091346432</li>
        <li>Last Price Increase: 2024-01-08</li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2023-12-11 20:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tapping "Go back to home page", user-directed to concierge page 

### What is the root cause of that problem?

here we use goback to redirect the user 
https://github.com/Expensify/App/blob/17a924f6594ff478af4f2a55ddf03a9dd15629f9/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L405



### What changes do you think we should make in order to solve the problem?
instead we should navigate to the home page 


```
                    onBackButtonPress={() => Navigation.navigate(ROUTES.HOME)}
```

**Comment by DylanDylann** [comment] 2023-12-13 15:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Android-Chat-Tapping "Go back to home page", user directed to concierge page

### What is the root cause of that problem?
- The  [FullPageNotFoundView](https://github.com/Expensify/App/blob/main/src/components/BlockingViews/FullPageNotFoundView.js) used in our app and also appeared in the evidence video.
- Clicking on  "Go back to home page" in this page will trigger the function ```onLinkPress```. By default, ```onLinkPress: () => Navigation.dismissModal()```:
https://github.com/Expensify/App/blob/d6755d68444d5d8e9e2c7593c7eb3f1228a20c67/src/components/BlockingViews/FullPageNotFoundView.js#L51 
- In the case of this bug, when user is in concierge report, the app's route stack is [Home, CentralPaneNavigator]. 
- Then, clicking on "Enter the amount" will navigate the user to [FullPageNotFoundView](https://github.com/Expensify/App/blob/main/src/components/BlockingViews/FullPageNotFoundView.js). Now, the app`s route stack is [Home, CentralPaneNavigator, RightModalNavigator]. 
- Then, if user clicks on "Go back to home page", it just pops the RightModalNavigator from the route stack, and user is redirected to concierge page.
### What changes do you think we should make in order to solve the problem?
- We need to check if the device is small screen or not. If true, ```onLinkPress: Navigation.navigate(ROUTES.HOME)```. If not, 
```onLinkPress: Navigation.dismissModal()```
- Do it by just update the bellow:
https://github.com/Expensify/App/blob/d6755d68444d5d8e9e2c7593c7eb3f1228a20c67/src/components/BlockingViews/FullPageNotFoundView.js#L73

### What alternative solutions did you explore? (Optional)
- NA

**Comment by muttmuure** [comment] 2023-12-18 16:10
@situchan a couple of proposals to review when you get chance

**Comment by muttmuure** [comment] 2024-01-02 18:53
@situchan when you get chance could you review the proposals above?

**Comment by muttmuure** [comment] 2024-01-08 14:05
Still waiting on C+ review

**Comment by situchan** [comment] 2024-01-08 14:06
Sorry missed this

**Comment by situchan** [comment] 2024-01-08 14:15
I don't think this is bug. We should go back to last page, not LHN skipping all previous pages.
If something should be fixed to avoid users get confused, `linkKey` can be updated like "Go back to Concierge", similar to https://github.com/Expensify/App/blob/3bd747dd59692a9144e38060302e45b3de5adc12/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L258, but not worth fixing imo.

**Comment by rushatgabhane** [comment] 2024-01-10 05:02
> as a user if I click a wrong click i'd prefer to goback to last screen instead of any other screen

> We should change the wording to "Go back to previous page"/"Go back" so we are not contradicting in terms of wording and functionality

@muttmuure i agree with @ishpaul777  https://github.com/Expensify/App/issues/32856#issuecomment-1850809658

But is this something worth doing?

**Comment by muttmuure** [comment] 2024-01-15 15:59
I'm not sure I think this is super important to fix right now.

**Closed by muttmuure** 2024-01-15 15:59 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
