### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] mWeb - Room - System message for room description with markdown is shown as html code

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44448] opened 2024-06-26 12:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4672130
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a room chat
3. Tap header-- room description
4. Enter _🦢💫😁🤡_
5. Save the description
6. In room conversation page, note the system message of room description saved

## Expected Result:
System message for room description with markdown must not be shown as html code

## Actual Result:
System message for room description with markdown is shown as html code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2a29b50e-794e-4968-b8ce-a23971f912ce

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c48ce1e75fd4d291</li>
        <li>Upwork Job ID: 1814416039583443889</li>
        <li>Last Price Increase: 2024-07-19</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 103199145</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by lanitochka17** [comment] 2024-06-26 12:23
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-26 12:24
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment] 2024-06-26 12:39
Caused by https://github.com/Expensify/App/pull/44300

**Comment by miljakljajic** [comment] 2024-07-03 10:46
@roryabraham @yuwenmemon is this a regression from https://github.com/Expensify/App/pull/44300?

**Comment by lanitochka17** [comment] 2024-07-18 19:59
Issue is still reproducible on the latest build 9.0.9-1

https://github.com/user-attachments/assets/f8b68165-e4cb-4e02-b65f-6c26c7deeccf

**Comment by bernhardoj** [comment] 2024-07-19 08:50
Because it's not fixed yet, I posted my proposal.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The system message of the room description update is shown with an HTML tag.

### What is the root cause of that problem?
If the action is an update room description, we use `ReportActionItemBasicMessage`.
https://github.com/Expensify/App/blob/9c5297efa452dd6c5f4939ce99e3af0756dc305d/src/pages/home/report/ReportActionItem.tsx#L652-L655

`ReportActionItemBasicMessage` only renders it as plain text. This happens after https://github.com/Expensify/App/pull/44300 which will also make the message translatable. Previously, we didn't check for the update room description action and let it be rendered by `ReportActionItemMessage` which uses `TextCommentFragment` that will render the HTML correctly. The fragment is constructed from the action message as shown below.

https://github.com/Expensify/App/blob/ffea2abc9b366b418291047b19dd20fdf6047a1b/src/pages/home/report/ReportActionItemMessage.tsx#L45-L51
https://github.com/Expensify/App/blob/9c5297efa452dd6c5f4939ce99e3af0756dc305d/src/pages/home/report/comment/TextCommentFragment.tsx#L55-L80

### What changes do you think we should make in order to solve the problem?

We need to use ReportActionItemMessage back by removing this code
https://github.com/Expensify/App/blob/9c5297efa452dd6c5f4939ce99e3af0756dc305d/src/pages/home/report/ReportActionItem.tsx#L652-L654

and to keep make it translatable, in `ReportActionItemMessage`, we need to construct a custom fragments array for the update room description action.
```
let fragments: Message[] = [];
if (action.actionName === CONST.REPORT.ACTIONS.TYPE.ROOM_CHANGE_LOG.UPDATE_ROOM_DESCRIPTION) {
    const message = `${translate('roomChangeLog.updateRoomDescription')} ${ReportActionsUtils.getOriginalMessage(action)?.description}`;
    fragments = [{text: message, html: `<muted-text>${message}</muted-text>`, type: 'COMMENT'}];
} else {
    if (Array.isArray(actionMessage)) {
        fragments = actionMessage.filter((item): item is Message => !!item);
    } else {
        fragments = actionMessage ? [actionMessage] : [];
    }
}
```

Last, we need to use Parser.htmlToText for the description here
https://github.com/Expensify/App/blob/ffea2abc9b366b418291047b19dd20fdf6047a1b/src/libs/SidebarUtils.ts#L429

**Comment by bernhardoj** [comment] 2024-07-20 05:25
PR is ready

**Comment by roryabraham** [comment] 2024-07-20 18:15
Didn't mean to unassign the original C+, but now that you're assigned to review the PR you can keep it. Thanks in advance for your review @allgandalf

**Comment by roryabraham** [comment] 2024-07-23 21:21
[PR](https://github.com/Expensify/App/pull/45818) is merge

**Comment by miljakljajic** [comment] 2024-08-05 08:32
@bernhardoj is owed 250 USD for their work reviewing this issue

**Comment by miljakljajic** [comment] 2024-08-05 08:34
@allgandalf paid you in upwork!

**Closed** 2024-08-05 08:35 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-08-05 09:38
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-08-05 12:14
$250 approved for @bernhardoj
