### ISSUE TITLE
Helpdot: The `Send an Invoice` article is missing a mention that a workspace is required to create an invoice

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44568] opened 2024-06-27 19:10 UTC
`If` you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Christinadobrzyn 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719503420839459

## Action Performed:
1. go to https://help.expensify.com/articles/new-expensify/expenses/Send-an-invoice
## Expected Result:
There is a note mentioning that a workspace is required to create an invoice
## Actual Result:
 there is no mention that a workspace is required before you can send an invoice
This is posted following SO - https://stackoverflowteams.com/c/expensify/questions/19321 (with next steps for the person assigned)
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/c05a6a62-3c29-47ec-8556-59d8504e2243

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neonbhai** [comment] 2024-06-28 00:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
FAB is missing Send an Invoice option for user with no active workspace

### What is the root cause of that problem?
We can now send invoices to individuals (and not just workspaces), but when adding the `Send Invoice` item to menu we still check for active policies:

https://github.com/Expensify/App/blob/27a8d0a6d88698e7d2cc6d42692abfbe7a8f6b76/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L185

https://github.com/Expensify/App/blob/27a8d0a6d88698e7d2cc6d42692abfbe7a8f6b76/src/libs/PolicyUtils.ts#L428-L430


### What changes do you think we should make in order to solve the problem?
We should remove the `canSendInvoice` variable and the checks from `FloatingActionButtonAndPopover.tsx`

https://github.com/Expensify/App/blob/27a8d0a6d88698e7d2cc6d42692abfbe7a8f6b76/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L185'

https://github.com/Expensify/App/blob/27a8d0a6d88698e7d2cc6d42692abfbe7a8f6b76/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L416-L417

**Comment by Christinadobrzyn** [comment] 2024-06-28 15:57
I'm kinda thinking this isn't needed and I can just go in a make the small change - for some reason I thought this would go to Ren for a review. 

I think we should make this internal and I'll work with our copy team to make an update.

**Comment by Christinadobrzyn** [comment] 2024-06-28 21:19
Actually, I just realised that I'm going to be updating this help article in the coming weeks anyway so I'm just going to bundle this into that job - https://github.com/Expensify/Expensify/issues/407226

@neonbhai thanks for taking the time to write up a proposal - sorry to change directions on this. 

Closing this as I'll move it into https://github.com/Expensify/Expensify/issues/407226

**Closed by Christinadobrzyn** 2024-06-28 21:19 UTC
Labels: Daily, Internal, Bug
