### ISSUE TITLE
[Hold for reporting bonus] Dev - Pay button text is cut off in Report.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12958] opened 2022-11-23 16:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. In LHN, choose any Report that has request money.
2. Notice that the Pay button is cut off text.

## Expected Result:
Pay button text should be fully visible.

## Actual Result:
Pay button text is cut off .

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.30-0
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/203604627-0e1d5baa-30ec-49ea-bc31-ef04ff474d24.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669173251556449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2022-11-23 16:59
``` js
    buttonSmall: {
        borderRadius: variables.buttonBorderRadius,
        height: variables.componentSizeSmall,
        paddingTop: 10,
        paddingHorizontal: 14,
        paddingBottom: 10,
        backgroundColor: themeColors.buttonDefaultBG,
    },

    buttonMedium: {
        borderRadius: variables.buttonBorderRadius,
        height: variables.componentSizeNormal,
        paddingTop: 6,
        paddingRight: 16,
        paddingBottom: 6,
        paddingLeft: 16,
        backgroundColor: themeColors.buttonDefaultBG,
    },

```

@shawnborton  here's our current small/medium button styles. Currently, this bug is only reproducible on mobile (at least IOS, have yet to test android)

**Comment by grgia** [comment] 2022-11-23 16:59
<img width="620" alt="image" src="https://user-images.githubusercontent.com/38015950/203605704-7d92efd2-0a2b-4a99-9486-eec77dd47bbd.png">

**Comment by shawnborton** [comment] 2022-11-23 17:02
I think we just have way too much top/bottom padding for the small buttons. What happens when we reduce it to something smaller, like 4?

**Comment by grgia** [comment] 2022-11-23 17:02
<img width="620" alt="image" src="https://user-images.githubusercontent.com/38015950/203606354-8fd3ea08-725c-474b-a695-19153fed9fd6.png">
Here's with 4

**Comment by shawnborton** [comment] 2022-11-23 17:05
Nice, that feels good to me for the gray buttons. I see in the green "Pay" button in the background, it looks weird. Any idea why that button would look different from the others?

**Comment by Puneet-here** [comment] 2022-11-23 17:12
paddingVertical should be 6px to keep the pay button correct

**Comment by shawnborton** [comment] 2022-11-23 17:14
I feel like the button text should always be vertically centered no matter what the padding is though. Are we able to do that?

**Comment by Puneet-here** [comment] 2022-11-23 17:16
Yes, we can. We have to use `styles.justifyContentCenter`

**Comment by mdneyazahmad** [comment] 2022-11-24 11:12
I was debugging the issue, not this one, and came to this issue via links. I see a PR is already merged. This can be used to add more context of the issue.

Button has a fixed height of 28, and padding top 10, padding bottom 10 and font size is 14.

The issue here is that the empty space for text (28 - 10 - 10) = 8 is left and the font size is 14. Therefore, the text is cut off.

This issue does not exist in web, because of the inconsistency between the devices. They behave differently. That can be observed from the attached video.

Changing padding top and bottom from 10 to 6 (seems fine), or we can remove this hard coded padding value completely. As the container has a display flex, and it has already set justifyContent to center, so the text will be always in the center provided the height is enough for the text.


https://user-images.githubusercontent.com/77761491/203769893-6682deb5-8383-440c-9407-a8b86a257920.mov


https://user-images.githubusercontent.com/77761491/203769945-cab20980-aa9e-4a11-9d76-d11b7399afb5.mov

**Comment by grgia** [comment] 2022-11-29 01:21
@mdneyazahmad That's a good point, and definitely something worth implementing if we run into this issue again! That said, I think for now we can close this issue as the padding changes in the fix fit the current branding in Figma.

**Comment by hungvu193** [comment] 2022-11-29 02:01
Can I have reporting bonus for this issue?

**Comment by Santhosh-Sellavel** [comment] 2022-11-29 14:35
@grgia Reporting bonus seems missed out for @hungvu193!

**Comment by hungvu193** [comment] 2022-12-07 03:33
Should we reopen this?

**Comment by grgia** [comment] 2022-12-07 06:31
Thanks for the bump, I'll reopen and see about payment

**Comment by grgia** [comment] 2022-12-07 17:55
@NicMendonca I must have accidentally unassigned you, do you mind helping me out with the reporting bonus for this issue?

**Comment by hungvu193** [comment] 2022-12-12 12:30
> @hungvu193 can you please apply to the job [here](https://www.upwork.com/jobs/~01720c3e572365836b)?

@NicMendonca it's showing as private job, can you please check again?

**Comment by NicMendonca** [comment] 2022-12-12 12:49
@hungvu193 paid! Thanks!

**Closed by NicMendonca** 2022-12-12 12:49 UTC
Labels: Daily, Internal, Needs Reproduction, Overdue, Bug
