### ISSUE TITLE
[HOLD FOR #40565][$250] Chat - Mention is not displayed in compose box when editing a message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41793] opened 2024-05-07 17:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4546634
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Send a message with user mention
4. Edit the message
5. If the mention is displayed cancel the edit and repeat step 4

## Expected Result:
Mentions should be displayed when editing messages

## Actual Result:
Mention is not displayed in edit compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/962e6932-c519-4aa5-82e0-b2dd8edb23ab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013489c9a79accb0a7</li>
        <li>Upwork Job ID: 1788009417512591360</li>
        <li>Last Price Increase: 2024-05-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by lanitochka17** [comment] 2024-05-07 17:16
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-07 17:17
We think that this bug might be related to #vip-vsp

**Comment by jliexpensify** [comment] 2024-05-08 00:52
Ah weird, yes - can repro this.

**Comment by c3024** [comment] 2024-05-08 07:09
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Mention is not displayed in edit compose box
### What is the root cause of that problem?
We return an empty string when there is no match for the account in the map here

https://github.com/Expensify/expensify-common/blob/182ef7f5824617b8893abaedee9855b5d66faf95/lib/ExpensiMark.js#L488

and we are not passing any `extras` here 

https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L241

so `extras` take the default `{}` here

https://github.com/Expensify/expensify-common/blob/182ef7f5824617b8893abaedee9855b5d66faf95/lib/ExpensiMark.js#L865

and `accountToNameMap` becomes `undefined` here

https://github.com/Expensify/expensify-common/blob/182ef7f5824617b8893abaedee9855b5d66faf95/lib/ExpensiMark.js#L486-L488
and the mention is replaced by `''`

### What changes do you think we should make in order to solve the problem?
We should create an `accountIdToName` map and pass it in `extras` to `parser.htmlToMarkdown` at all places. 
### What alternative solutions did you explore? (Optional)

**Comment by hungvu193** [comment] 2024-05-08 08:50
I think we have a PR to fix this already: https://github.com/Expensify/App/pull/40565

**Comment by robertKozik** [comment] 2024-05-08 09:06
Yes @hungvu193 #40565 should handle this case

@war-in CMIIW

**Comment by jliexpensify** [comment] 2024-05-08 10:36
Thanks gents, will drop a HOLD on this

**Comment by hungvu193** [comment] 2024-05-31 18:37
Still hold for https://github.com/Expensify/App/pull/40565

**Comment by lanitochka17** [comment] 2024-06-07 12:39
QA team faced similar problem: On editing mention message, hidden is displayed
Is it the same? or open new issue

![bandicam 2024-06-07 13-41-12-076](https://github.com/Expensify/App/assets/78819774/ea9a59cc-9455-47ab-8998-06327a0c8c29)

**Comment by war-in** [comment] 2024-06-07 13:52
Hi @lanitochka17 👋 

I'm currently working on this in my [Editing mentions](https://github.com/Expensify/App/pull/40565) PR.

To add more context. `expensify-common` was updated to handle the case of editing mentions but Expensify App is not yet updated so that's why `@hidden` is displayed. Everything will be fine when my PR is merged (hopefully early next week)

**Comment by hungvu193** [comment] 2024-07-09 09:29
Linked PR is merged and deployed, please verify this @lanitochka17. I think we can close this issue. cc @jliexpensify 

https://github.com/Expensify/App/assets/16502320/d3421e20-4196-4e6f-826b-12b836d09046

**Comment by jliexpensify** [comment] 2024-07-09 09:35
Nice, thanks @hungvu193

**Closed by jliexpensify** 2024-07-09 09:35 UTC
Labels: External, Monthly, Bug
