### ISSUE TITLE
[HOLD for payment 2024-06-05] [$125] Category - Clicking on a very long parent child category name scrolls the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41850] opened 2024-05-08 14:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-conditions:
- Create a workspace
- Create a category name with long parent child relationship (e.g: "A: Very: Long: Category: List: Done: A: Very: Long: Category: List: Done: A: Very: Long: Category: List: Done: A: Very: Long: Category: List: Done: A: Very: Long: Category: List: Done"
1. Navigate to staging.new.expensify.com
2. Open workspace chat
3. Click on Plus icon inside compose box > Submit expense > Manual > Enter amount > Click next
4. Open category list
5. Click somewhere down the long category list but do not use the mouse scroll wheel

## Expected Result:
Nothing should happen

## Actual Result:
The page scrolls down

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/52665374-9639-40fd-90a5-ca1a736cc5ae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d72668f5e4a79c3</li>
        <li>Upwork Job ID: 1789045147791183872</li>
        <li>Last Price Increase: 2024-05-17</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger / @muttmuure</details>

**Comment by lanitochka17** [comment] 2024-05-08 14:48
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-08 14:48
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment] 2024-05-09 05:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The page scrolls down

### What is the root cause of that problem?
We have the logic here to change the focusedIndex when a option is focused


https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/components/SelectionList/BaseSelectionList.tsx#L362

And then the page scrolls because of the logic here
https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/components/SelectionList/BaseSelectionList.tsx#L235-L237
### What changes do you think we should make in order to solve the problem?
We should check if the options is disabled we will do nothing instead of changing the `focusedIndex`

```
onFocus={() => {
    if (isDisabled) {
        return;
    }
    setFocusedIndex(normalizedIndex);
}}
```
https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/components/SelectionList/BaseSelectionList.tsx#L362

OPTIONAL: We can also do nothing if we can't select multiple option so the page will not scroll briefly when we select a option and navigate to another page.
### What alternative solutions did you explore? (Optional)
If we always want to not trigger `onFocus` function when the item is disabled, we can do this in `BaseListItem`

```
onFocus={() => {
    if (isDisabled && !item.isSelected) {
        return;
    }
    onFocus?.();
}}
```
https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/components/SelectionList/BaseListItem.tsx#L84


### Result



https://github.com/Expensify/App/assets/161821005/5e39e822-c725-4d83-baaf-6c102fe493de

**Comment by sakluger** [comment] 2024-05-10 21:30
This seems pretty low-impact and not to big of a fix, I'm going to change the price to $125. Let me know if you disagree.

**Comment by sobitneupane** [comment] 2024-05-14 10:01
Thanks for the proposal @nkdengineer 

But why is it being displayed in multiple lines like that? I tried adding some long paragraphs without `:`, it is being displayed only in two lines max with ellipsis.

**Comment by nkdengineer** [comment] 2024-05-14 10:25
@sobitneupane The category with `:` is  long parent child relationship and each category that is separated by `:` will be displayed in a line.

**Comment by sobitneupane** [comment] 2024-05-14 14:44
> The category with : is long parent child relationship and each category that is separated by : will be displayed in a line.

@nkdengineer Can you please link the code/issue that is responsible for this feature.

**Comment by robert-westenberger** [comment] 2024-05-14 14:45
Apologies if this is the wrong place to ask this, I am not overly familiar with the expensify ticketing process, but is there not another bug here? The category hierarchy is so large that the innermost child label is rendered off of the screen. Is that not an issue...? Or would that be handled in a different ticket?

**Comment by nkdengineer** [comment] 2024-05-15 09:54
@sobitneupane The option tree function is add from this PR https://github.com/Expensify/App/pull/25777

**Comment by sakluger** [comment] 2024-05-16 22:00
Reassigning while I'm OOO through May 31.

**Comment by sobitneupane** [comment] 2024-05-20 09:38
Thanks for the update @nkdengineer 

[Proposal](https://github.com/Expensify/App/issues/41850#issuecomment-2101972590) from @nkdengineer looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by nkdengineer** [comment] 2024-05-21 03:36
@sobitneupane this [PR](https://github.com/Expensify/App/pull/42405) is ready for preview.

**Comment by sakluger** [comment] 2024-06-05 00:41
@sobitneupane could you please complete the BZ checklist?

**Comment by sakluger** [comment] 2024-06-06 15:53
Bumped in Slack.

**Comment by sobitneupane** [comment] 2024-06-06 16:25
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

Option Tree was implemented by https://github.com/Expensify/App/pull/25777 PR to implement category tree.
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

Not Required.
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not Required.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2024-06-06 16:28
**Regression Test Proposal**

Pre-conditions:
- Create a workspace
- Create a category name with long parent child relationship (e.g: "A: Very: Long: Category: List: Done: A: Very: Long: Category: List: Done: A: Very: Long: Category: List: Done: A: Very: Long: Category: List: Done: A: Very: Long: Category: List: Done"

1. Open workspace chat
2. Click on Plus icon inside compose box > Submit expense > Manual > Enter amount > Click next
3. Open category list
4. Click somewhere down the long category list but do not use the mouse scroll wheel
5. Verify that the list is not scrolled on clicking the disabled category in category tree.

Do we agree :+1: or :thumbsdown:

**Comment by sakluger** [comment] 2024-06-06 20:01
Summarizing payment on this issue:

Contributor+: @sobitneupane $125, please request on Newdot

**Closed by sakluger** 2024-06-06 20:01 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-22 16:52
$125 approved for @sobitneupane

**Comment by nkdengineer** [comment] 2024-07-01 15:26
@sakluger @JmillsExpensify Hi, I'm the assigned contributor that raised the PR, and wasn't paid here.

Could you help reopen the issue to handle that?

Thanks

**Comment by sakluger** [comment] 2024-07-02 16:16
@nkdengineer I'm so sorry for missing your payment. I've completed the payment now, everything should be set here.
