### ISSUE TITLE
[$500] Web -  Context menu doesn't close when messages are marked as unread quickly

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26030] opened 2023-08-27 11:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a report
2. Mark messages unread quickly

## Expected Result:
The context menu should close when any message is marked unread

## Actual Result:
 The context menu doesn't close when any message is marked unread

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.5
**Reproducible in staging?:** yes
**Reproducible in production?:**yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0d8dd364-728b-44de-8f39-70b2932d7128

![image (15)](https://github.com/Expensify/App/assets/93399543/4bf60912-75cf-47d1-bf51-55b5a38e93ee)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692281382683649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4ddccc17dcb6355</li>
        <li>Upwork Job ID: 1697394566933270528</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-08-27 11:51
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Context menu doesn't close when messages are marked as unread quickly.
### What is the root cause of that problem?
There seems to be a synchronization issue between the time taken to process markCommentAsUnread and the UI updates (likely hover state changes). Specifically, when markCommentAsUnread is invoked, it triggers a state update which could interfere with the hover state of the UI component. This interference might be causing the onLeaveEvent to not be detected properly when moving the cursor rapidly.
### What changes do you think we should make in order to solve the problem?
To address this synchronization issue and ensure that the onLeaveEvent is detected reliably, we should defer the execution of markCommentAsUnread until all ongoing interactions and animations have been processed. We can achieve this by leveraging React Native's InteractionManager. The code implementation would look like this:
`
InteractionManager.runAfterInteractions(() => {
      Report.markCommentAsUnread(reportID, reportAction.created);
 });
`
By employing InteractionManager, we ensure that the marking action is queued and only processed once all other UI-related tasks are completed, thus reducing the chance of event overlap and state interference.

**Comment by alexpensify** [comment] 2023-08-30 01:26
I was assigned while OOO, I will test soon.

**Comment by alexpensify** [comment] 2023-08-31 23:43
Marking as External - @sobitneupane can we review the proposal to identify if it will correct this issue? Thanks!

**Comment by alexpensify** [comment] 2023-09-04 15:16
@Krishna2323 thanks for flagging. 

@rushatgabhane - when you get a chance, can you please review the proposal? Thanks!

**Comment by sobitneupane** [comment] 2023-09-05 10:27
@Krishna2323 Thanks for your proposal.

I have tested your proposal and it doesn't solve the [other issue](https://github.com/Expensify/App/issues/26011)

<img width="669" alt="Screenshot 2023-09-05 at 16 09 49" src="https://github.com/Expensify/App/assets/25876548/2efdd844-30b6-4144-9bc1-e2161b6eea5b">

**Comment by sobitneupane** [comment] 2023-09-06 07:05
@Krishna2323 The other issue is very similar to this one. Let's try to handle both the issues here

**Comment by alexpensify** [comment] 2023-09-11 22:17
@sobitneupane is there more feedback following @Krishna2323's latest reply? Thanks!

**Comment by sobitneupane** [comment] 2023-09-13 06:37
@Krishna2323 In that case we can wait for https://github.com/Expensify/App/pull/24482 to get merged. But Is this issue any longer reproducible? I cannot reproduce it on dev(main) and staging.

**Comment by alexpensify** [comment] 2023-09-15 00:31
Thanks! Based on this feedback, I'm closing this GH.

**Closed by alexpensify** 2023-09-15 00:31 UTC
Labels: External, Daily, Help Wanted, Bug
