### ISSUE TITLE
[HOLD for payment 2024-06-20] [$500] [Search v1] LHN shows `Not found` when navigated from global create menu

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#42995] opened 2024-06-03 14:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
There are two issues here:

**Issue 1**
1. From the Search page, click on a result
2. Click on the header link
3. Notice that the LHN shows `not found`

**Issue 2**
1. While viewing the Search page, click on the global create menu
2. Submit and expese
3. Notice that the LHN shows `not found`

## Expected Result:
Navigation should work

## Actual Result:
LHN shows `not found`

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015dea8a0a2e4109e9</li>
        <li>Upwork Job ID: 1797769446176616448</li>
        <li>Last Price Increase: 2024-06-04</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 102591587</li>
<li>bernhardoj | Contributor | 102591588</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by luacmartins** [comment] 2024-06-03 14:47
cc @adamgrzybowski can you take a look please?

**Comment by luacmartins** [comment] 2024-06-03 23:17
@c3024 @adamgrzybowski let me know what you think of the proposal above

**Comment by bernhardoj** [comment] 2024-06-04 07:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN shows not found when pressing the report parent navigation or submitting an expense from global create while on the search page.

### What is the root cause of that problem?
When pressing the parent navigation link, we use `goBack` with the parent report as the fallback to go to the parent report.
https://github.com/Expensify/App/blob/1d5f83d037b5635260c882047b0bfd4ead246d36/src/components/ParentNavigationSubtitle.tsx#L39-L48

Because the report screen is in RHP and it's the only screen, we navigate with the UP navigation type, which will replace the current screen with the report screen,
https://github.com/Expensify/App/blob/1d5f83d037b5635260c882047b0bfd4ead246d36/src/libs/Navigation/Navigation.ts#L219-L222
https://github.com/Expensify/App/blob/1d5f83d037b5635260c882047b0bfd4ead246d36/src/libs/Navigation/linkTo/index.ts#L85-L86

but the bottom tab navigator screen isn't changed. The bottom tab navigator screen should be updated if the navigation target is a central pane screen, which is true for our case, however, the UP type case is prioritized as you can see from the if condition below.

https://github.com/Expensify/App/blob/1d5f83d037b5635260c882047b0bfd4ead246d36/src/libs/Navigation/linkTo/index.ts#L85-L101

Previously, we had a FORCED_UP type which is always prioritized first and then the UP type will be checked after checking the central pane screen, 
```
if (type == FORCED_UP) ...
else if (target == CENTRAL_PANE_NAVIGATOR) ...
else if (type == UP)
```
but now, the FORCED_UP is removed and replaced with UP in https://github.com/Expensify/App/pull/42335.

For the second issue, after submitting an expense, we call `dismissModal`.
https://github.com/Expensify/App/blob/1d5f83d037b5635260c882047b0bfd4ead246d36/src/libs/actions/IOU.ts#L3498

What it will do is it will replace the current screen with a report screen and also update the bottom tab screen by `switchPolicyID`.
https://github.com/Expensify/App/blob/1d5f83d037b5635260c882047b0bfd4ead246d36/src/libs/Navigation/dismissModalWithReport.ts#L51-L63
https://github.com/Expensify/App/blob/1d5f83d037b5635260c882047b0bfd4ead246d36/src/libs/Navigation/switchPolicyID.ts#L85-L91

The bottom tab screen will be based on the `route` that we pass, in our case, it's HOME, so it should show the HOME LHN. If we don't pass `route`, then it will use the currently focused bottom tab screen (this is the `newPath` that will be explained below). However, there is a logic here that will always set the LHN to be the search bottom tab if we execute the navigation while on the search page, even if we pass a `route` to navigate to,
https://github.com/Expensify/App/blob/1d5f83d037b5635260c882047b0bfd4ead246d36/src/libs/Navigation/switchPolicyID.ts#L78-L81

Previously, we checked whether the `newPath` is the search bottom or not before setting the LHN to be the search bottom tab.
<img width="690" alt="image" src="https://github.com/Expensify/App/assets/50919443/863328b4-55ff-4b36-b9de-e3cbff50f399">

But it's changed in https://github.com/Expensify/App/pull/42335 too because the const is now removed.

### What changes do you think we should make in order to solve the problem?

To fix the 2nd issue, we can use the old approach by adding back the const,
```
const isOpeningSearchFromBottomTab = newPath.startsWith(CONST.SEARCH_BOTTOM_TAB_URL);
```

or update `isOpeningSearchFromBottomTab` condition so it's true only if we don't pass a `route`.
```
const isOpeningSearchFromBottomTab = !route && topmostCentralPaneRoute?.name === SCREENS.SEARCH.CENTRAL_PANE;
```

To fix the 1st issue, we can either:
1. Add back FORCED_UP and it's logic like before
2. Copy the bottom tab update logic from this if block,
https://github.com/Expensify/App/blob/1d5f83d037b5635260c882047b0bfd4ead246d36/src/libs/Navigation/linkTo/index.ts#L89-L101
to the type is UP logic if the target is the central pane screen
```
if (type === CONST.NAVIGATION.TYPE.UP) {
    if (action.payload.name === NAVIGATORS.CENTRAL_PANE_NAVIGATOR) // bottom tab screen update goes here
    action.type = CONST.NAVIGATION.ACTION_TYPE.REPLACE;
}
```
3. Rearrange the if such as the central pane screen condition is prioritized first,
```
if (target == CENTRAL_PANE_NAVIGATOR) ...
else if (type == UP)
```

and add another type check in the first if to change the action type.
https://github.com/Expensify/App/blob/1d5f83d037b5635260c882047b0bfd4ead246d36/src/libs/Navigation/linkTo/index.ts#L103

```
if (target == CENTRAL_PANE_NAVIGATOR) {
    ... (bottom tab screen update)

    if (type  === UP) {
        action.type = CONST.NAVIGATION.ACTION_TYPE.REPLACE
    } else {
        action.type = CONST.NAVIGATION.ACTION_TYPE.PUSH;
    }

   ...
} else if (type === UP) ...
```

**Comment by adamgrzybowski** [comment] 2024-06-04 10:29
@bernhardoj Thanks for this great proposal! 

For the issue with dismiss modal I personally prefer this solution: 
```const isOpeningSearchFromBottomTab = !route && topmostCentralPaneRoute?.name === SCREENS.SEARCH.CENTRAL_PANE;```. I like the fact that we don't operate on the url but rather on the state.

For the issue in the `linkTo` file I like the 3rd option. It looks simple and doesn't use FORCED_UP which may be confusing.

**Comment by luacmartins** [comment] 2024-06-04 15:03
I agree with @bernhardoj's proposal since it covers both nav issues. Let's implement @adamgrzybowski's suggestion though.

**Comment by JmillsExpensify** [comment] 2024-06-04 15:47
@bernhardoj Quick note for visibility: This PR is quite high value, so I'm going to double the value to reflect that. Can you make this your top priority? Thanks!

**Comment by bernhardoj** [comment] 2024-06-04 15:54
@JmillsExpensify hi, it's late for me now, this will be my first thing to work tomorrow.

**Comment by JmillsExpensify** [comment] 2024-06-04 17:45
Thank you for confirming! Sounds good

**Comment by bernhardoj** [comment] 2024-06-05 02:24
PR is ready

cc: @c3024

**Comment by alexpensify** [comment] 2024-06-05 22:41
Awesome, looks like this PR is moving forward. Thanks!

**Comment by luacmartins** [comment] 2024-06-05 23:31
PR is merged.

**Comment by alexpensify** [comment] 2024-06-11 23:04
Weekly Update: Waiting for this PR to go to prod

**Comment by awongCM** [comment] 2024-06-16 01:09
> If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
> 
> **Version Number:** **Reproducible in staging?:** **Reproducible in production?:** **If this was caught during regression testing, add the test name, ID and link from TestRail:** **Email or phone of affected tester (no customers):** **Logs:** https://stackoverflow.com/c/expensify/questions/4856 **Expensify/Expensify Issue URL:** **Issue reported by:** **Slack conversation:**
> 
> ## Action Performed:
> There are two issues here:
> 
> **Issue 1**
> 
> 1. From the Search page, click on a result
> 2. Click on the header link
> 3. Notice that the LHN shows `not found`
> 
> **Issue 2**
> 
> 1. While viewing the Search page, click on the global create menu
> 2. Submit and expese
> 3. Notice that the LHN shows `not found`
> 
> ## Expected Result:
> Navigation should work
> 
> ## Actual Result:
> LHN shows `not found`
> 
> ## Workaround:
> Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
> 
> ## Platforms:
> Which of our officially supported platforms is this issue occurring on?
> 
> * [ ]  Android: Native
> * [ ]  Android: mWeb Chrome
> * [ ]  iOS: Native
> * [ ]  iOS: mWeb Safari
> * [ ]  MacOS: Chrome / Safari
> * [ ]  MacOS: Desktop
> 
> ## Screenshots/Videos
> Add any screenshot/video evidence
> 
> [View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
> 
> Upwork Automation - Do Not Edit
> Issue Owner

Hi - is this issue going to remain open for a while?  I'm interested to contribute to the problem statement.

**Comment by c3024** [comment] 2024-06-16 06:54
@awongCM 

Issues with the `External` and `Help Wanted` labels are open to external contributors. So, this issue is no more open for contribution.

You can check the complete guidelines [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by awongCM** [comment] 2024-06-16 10:29
> here

Thanks.  I'll take a look in my own spare time.  Cheers.

**Comment by alexpensify** [comment] 2024-06-18 21:56
Flagging that the payment day is on June 20

**Comment by awongCM** [comment] 2024-06-19 13:08
Contributor details
Your Expensify account email: awong.cm@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01076ffa2e22c46ed8

**Comment by alexpensify** [comment] 2024-06-20 22:32
Payouts due: 2024-06-20

- [ ] Contributor: $500 @bernhardoj 
- [ ] Contributor+: $500 @c3024 

Upwork job is [here](https://www.upwork.com/jobs/~015dea8a0a2e4109e9). 

Closing, everyone here has been paid and I've closed the job in Expensify. I've also manually corrected the amount due in Upwork as a bonus.

**Closed by alexpensify** 2024-06-20 22:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
