### ISSUE TITLE
[HOLD for payment 2024-12-03] [$125] Share Code - Inconsistent profile pic shape in admin room when accessed via #Admin hyperlink

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52258] opened 2024-11-08 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** NA
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** biruknew45+2025@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create workspace
3. Go to the #admin room (if you couldn't find it in LHN go to account setting> workspace > click on the three dots then click on #admin room)
4. Click on the header > share code then see the shape of the profile picture
5. Go to workspace editor > profile > share code > click on #admins hyper link
6. click on the header > share code and see the shape of the profile picture.

## Expected Result:
The profile picture should consistently appear as a circle

## Actual Result:
When navigating to the admin room share code through the #admin hyperlink, the profile picture appears as a rectangle

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/b05f5cab-6736-47f6-a86d-bf7deef46a28

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854973788673857466</li>
        <li>Upwork Job ID: 1854973788673857466</li>
        <li>Last Price Increase: 2024-11-08</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 104896217</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by joekaufmanexpensify** [comment] 2024-11-08 19:46
Reproduced. 

https://github.com/user-attachments/assets/775d9473-5bed-41b6-984c-73cd68b3b07e

**Comment by joekaufmanexpensify** [comment] 2024-11-08 19:46
Seems like a pretty minor bug, so bumping down.

**Comment by Shahidullah-Muffakir** [comment] 2024-11-08 23:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The profile picture in QR code sharing displays as a circle when accessed from the admin room, but shows as a rectangle when accessed via the "#admin" hyperlink in workspace editor. 
### What is the root cause of that problem?
The logoBorderRadius in the QRCode component is incorrectly set to the full QR code size (size) instead of being calculated based on the logo size. To create a circle, border radius should be half of the logo's width/height

https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/components/QRCode.tsx#L86
### What changes do you think we should make in order to solve the problem?
Update the QRCode component to properly calculate the border radius:
size * logoRatio
          `logoBorderRadius={(size * logoRatio)/2}`

**Comment by Shahidullah-Muffakir** [comment] 2024-11-09 01:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When users view shared QR codes in the Expensify app, the profile picture shape is inconsistent depending on the navigation path taken. Specifically:

1. When accessing the share code through the normal admin room path, the profile picture appears as a circle (correct)
2. When accessing the share code through the "#admin" hyperlink in the workspace editor, the profile picture appears as a rectangle (incorrect)

### What is the root cause of that problem?
The issue occurs because when the user clicks on the hyperlink here:
[WorkspaceProfileSharePage.tsx#L89](https://github.com/Expensify/App/blob/c75b1bcc4c2a23a3c1d5ed84c844f82ed3996293/src/pages/workspace/WorkspaceProfileSharePage.tsx#L89),
the current QR code displayed in WorkspaceProfileSharePage is not being properly closed. As a result, when navigating to the new page where the QR code is shown again, two QRShare components are mounted simultaneously. You can verify this by checking the React dev tools for the two QRShare components. This is causing the SVG inside the QR code to lose the border-radius styling, making the profile picture appear as a rectangle.
### What changes do you think we should make in order to solve the problem?
When the user clicks on the hyperlink, close the current modal before navigating to the new page. This can be done using the Navigation.dismissModal() method.

```
Navigation.dismissModal();
Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(adminRoom.reportID ?? ''));
```

**Comment by ikevin127** [comment] 2024-11-09 11:28
Thanks @Shahidullah-Muffakir for the proposal, the RCA checks out and the proposed solution fixes the issue in accordance with the **Expected result**.

### **Suggestion**
In order to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) the code down to one line you might as well write it like this:

```ts
Navigation.dismissModal(adminRoom.reportID);
```

since `dismissModal` has support for `reportID` which if passed calls:

https://github.com/Expensify/App/blob/c75b1bcc4c2a23a3c1d5ed84c844f82ed3996293/src/libs/Navigation/dismissModalWithReport.ts#L24-L29

🎀👀🎀 C+ reviewed

**Comment by Shahidullah-Muffakir** [comment] 2024-11-09 14:36
> ### **Suggestion**
> In order to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) the code down to one line you might as well write it like this:
> 
> ```ts
> Navigation.dismissModal(adminRoom.reportID);
> ```
> 
> since `dismissModal` has support for `reportID` which if passed calls:
> 
> https://github.com/Expensify/App/blob/c75b1bcc4c2a23a3c1d5ed84c844f82ed3996293/src/libs/Navigation/dismissModalWithReport.ts#L24-L29
> 
> 🎀👀🎀 C+ reviewed

@ikevin127, Thank you for pointing that out! We’ll use that.

**Comment by ikevin127** [comment] 2024-11-12 19:27
CME doesn't seem to be OOO, not sure what's the hold up here.

cc @grgia @joekaufmanexpensify for visibility.

**Comment by joekaufmanexpensify** [comment] 2024-11-12 19:40
@grgia mind signing off on this one when you have a sec?

**Comment by ikevin127** [comment] 2024-11-13 22:48
@joekaufmanexpensify Do you think it's possible to re-assign CME for this issue ? Must be caught-up with some higher priority tasks and we wouldn't want deter from that. There's another issue reported on Slack with the same situation [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1731490291883769).

**Comment by joekaufmanexpensify** [comment] 2024-11-18 16:34
PR in review

**Comment by ikevin127** [comment] 2024-11-18 18:51
Awaiting final PR review from @grgia

**Comment by ikevin127** [comment] 2024-11-22 23:11
♻️ **Status updaate**: PR was merged & deployed to **staging** and is now awaiting **production** deploy.

**Comment by joekaufmanexpensify** [comment] 2024-11-25 16:30
Sounds good. TY!

**Comment by ikevin127** [comment] 2024-11-26 22:21
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by joekaufmanexpensify** [comment] 2024-12-02 15:51
Great. I will handle next steps!

**Comment by joekaufmanexpensify** [comment] 2024-12-02 15:52
@Shahidullah-Muffakir offer sent for $125!

**Comment by joekaufmanexpensify** [comment] 2024-12-03 15:55
This is a pretty niche bug, I don't think we need a regression test everytime here.

**Comment by joekaufmanexpensify** [comment] 2024-12-03 15:56
All set to pay: 

- @Shahidullah-Muffakir $125 for PR via Upwork. 
- @ikevin127 $125 for C+ via Upwork.

**Comment by joekaufmanexpensify** [comment] 2024-12-03 15:57
@ikevin127 $125 sent and contract ended

**Comment by joekaufmanexpensify** [comment] 2024-12-03 15:57
@Shahidullah-Muffakir $125 sent and contract ended

**Comment by joekaufmanexpensify** [comment] 2024-12-03 15:57
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-12-03 15:58
All set, thanks everyone!

**Closed by joekaufmanexpensify** 2024-12-03 15:58 UTC
Labels: External, Daily, Awaiting Payment, Bug
