### ISSUE TITLE
 Expense Report - System message does not appear in real time when updating report title

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41845] opened 2024-05-08 13:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Turn on workflow for the workspace and turn on approvals
4. Go to workspace chat and create two expenses and submit it
5. Open the expense report page and rename the report
6. Go back to the workspace chat and return back to expense report page
7. Do step 5 - 6 again

## Expected Result:
The system message stating the report has been renamed gets appears in real time as soon as the report gets renamed

## Actual Result:
The system message holds stale data, user has to go back to workspace chat and return to expense report to view the updated system message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7a53a6dc-e7e9-497c-81eb-066b1d01bf1b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-08 13:36
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-05-09 04:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The system message holds stale data, user has to go back to workspace chat and return to expense report to view the updated system message

### What is the root cause of that problem?
1. When we rename the report, we don't create optimistic data for rename action

https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/libs/actions/Report.ts#L1691

2. Backend doesn't return the data of rename action in `RenameReport` API

<img width="1510" alt="Screenshot 2024-05-09 at 11 43 11" src="https://github.com/Expensify/App/assets/161821005/eb991a4f-e9ce-4918-92e6-2b3dc0da9b5c">

### What changes do you think we should make in order to solve the problem?
1. We should create optimistic data for rename action, we can create a util like `buildOptimisticDataRenameReportAction` in `ReportUtil` and the data of rename action like this image. Also this will have `pendingAction` as `add` and we will generate the error for this action in `failureData`

<img width="1510" alt="Screenshot 2024-05-09 at 11 44 14" src="https://github.com/Expensify/App/assets/161821005/784e0cee-8e4c-4d6c-9a08-07a839ef30bc">


https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/libs/actions/Report.ts#L1691

2. For `RenameReport` API, We should accept an extra param like `renameReportActionID` that is the `reportActionID` of rename action that we generated in `buildOptimisticDataRenameReportAction` and use this to create the rename action in backend. We also need to return rename report action data in the response of this API

### What alternative solutions did you explore? (Optional)
NA

**Comment by joekaufmanexpensify** [comment] 2024-05-10 21:09
I can't reproduce this on my end. I'm thinking maybe this comes down to the timing of the API, and if it's slower, we don't load it in the frontend if we don't have the response from the backend in time?

Not sure this really feels like worth prioritizing right now, especially since I think we are doing a lot of work to make the site more performant. I am inclined to think we can close this for now, and see if any actual customers report this, or it becomes consistently reproducible. 

https://github.com/Expensify/App/assets/54866469/1eaa9e2b-07f7-496d-ade0-7ba67116c1e3

**Comment by joekaufmanexpensify** [comment] 2024-05-10 21:09
Going to close for now

**Closed by joekaufmanexpensify** 2024-05-10 21:09 UTC
Labels: Daily, Bug

**Comment by nkdengineer** [comment] 2024-05-24 08:15
@joekaufmanexpensify As the video above, you can't reproduce this bug because you go back to WS chat and open expense report again which makes `OpenReport` API is called again and rename action is returned. You can reproduce by keeping expense report and then you will never see the rename action is displayed.

**Comment by joekaufmanexpensify** [comment] 2024-05-24 13:28
Hm, the reproduction steps in OP of the issue say to go back to the workspace chat, and then to click back into the report. Are you saying that renaming the report in general is not working for you? 

It seems to be working for me, and in the tester's video (before they clicked out to WS chat and back into the report). But if it's not working for you at all, feel free to share a video, and happy to take a look.

**Comment by nkdengineer** [comment] 2024-05-27 04:56
@joekaufmanexpensify Here is the video, if we keep in the expense report we will never see the system message about rename report.

https://github.com/Expensify/App/assets/161821005/dd81003c-5c04-4bbf-9243-2701d920eedf

**Comment by joekaufmanexpensify** [comment] 2024-05-28 20:22
Got it. So you're saying the report can be successfully renamed, but if the user stays in the expense report, the system message itself will never show up (it shows up only after they leave the report and come back). Is that right?

**Comment by nkdengineer** [comment] 2024-05-29 02:48
> Got it. So you're saying the report can be successfully renamed, but if the user stays in the expense report, the system message itself will never show up (it shows up only after they leave the report and come back). Is that right?

@joekaufmanexpensify Yes, that's right.

**Comment by joekaufmanexpensify** [comment] 2024-05-29 12:45
Got it. I think in an ideal world the system message would show up right away. But since the renamed report appears right away, it doesn't feel like a big deal to me that the system message only appears after you leave the report and come back. Historically, we have not prioritized these kinds of "live update" issues, and I don't see why we'd change course now. 

I think we should focus on higher impact issues, and revisit this down the line if this ends up impacting actual customers.
