### ISSUE TITLE
[$500]  IOU - Endless loading when creating an IOU with user with no chat history

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36244] opened 2024-02-09 14:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click on FAB button > start chat with user with no history
2. Don't send any message > navigate to any other chat
3. Click on FAB button > create IOU with user from step 1

## Expected Result:
IOU should be successfully created. 1:1 chat between users should be loaded.

## Actual Result:
Chat history is stuck in endless loading on request creation. IOU is not created if user navigates to the 1:1 chat manually.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e719e0da-bdc1-43d6-8612-435effa79632

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d17196a2eaf1a88b</li>
        <li>Upwork Job ID: 1755968996312395776</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-09 14:57
We think that this bug might be related to #vip-split-p2p-chat-groups
CC @gabrielessner

**Comment by Christinadobrzyn** [comment] 2024-02-09 17:52
I am not able to reproduce this. here's what I'm doing: 

1. Click on FAB button > start chat with user with no history (tried on testingtesting+3@expensifail.com & bodzio.bodziak8+new5th@gmail.com)
2. Don't send any message > navigate to any other chat
3. Click on FAB button > create IOU with user from step 1

https://github.com/Expensify/App/assets/51066321/2828402f-2ad5-4572-9c70-38c46b0d96bb



@kbecciv can you take a peek at my steps and let me know what I need to do differently to reproduce this?

**Comment by isagoico** [comment] 2024-02-09 18:31
2 team members were able to reproduce this issue when it was reported (~5 hours ago) but we're unable to reproduce anymore. I'm not sure if this was like a blip or temporary issue.
We have the conversation ID where the infinite loading was visible, maybe the logs can reveal something?
These are the 2 conversations where this happened:
4110775099291402
5218769678771468

**Comment by Christinadobrzyn** [comment] 2024-02-09 19:55
Logs for [4110775099291402](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%224110775099291402%22%20AND%20timestamp%3A%5B2024-02-02T00%3A00%20TO%202024-02-10T23%3A59%5D)

Logs for [5218769678771468](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%225218769678771468%22%20AND%20timestamp%3A%5B2024-02-02T00%3A00%20TO%202024-02-10T23%3A59%5D)

Both show error: 

`Push_API - User attempted to subscribe to a private report channel they do not have access to. Blocking the subscription. ~~ reportID: 'X'`


<br class="Apple-interchange-newline">

<img width="1670" alt="image" src="https://github.com/Expensify/App/assets/51066321/85851429-d8eb-46eb-9bb6-1dcf376c9c9c">

Then it looks like we skipped the hold up with creating the IOU so a report was created so I think this is resolved. Going to close this but let me know if there's something else we should evaluate.

**Closed by Christinadobrzyn** 2024-02-09 19:55 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
