### ISSUE TITLE
[PAID][Regression in PR][$250] BUG: Able to check Select all checkbox of the manage members page when there is only me (workspace owner) on the list reported by @adeel0202 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12066] opened 2022-10-21 20:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Settings
2. Go to Profile
3. Delete profile pic if already exist
4. Click on avatar
5. Click on Upload photo
6. Choose a high resolution photo
7. Click Save
8. Go to any workspace
9. Click Manage members
10. Remove other members if exist by selecting all and then clicking on remove button
11. Click on Select all checkbox

## Expected Result:
Not able to check Select all checkbox when there is only me on the list

## Actual Result:
Able to check Select all checkbox when there is only me on the list

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/197283885-026876bb-5007-4d75-af04-e9866f0acd8a.mov

https://user-images.githubusercontent.com/43996225/197283936-19897b99-875a-4499-97aa-deba2dbc5ef3.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666371501103159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-10-21 23:39
@adeel0202 @kavimuru , you shouldn't be able to remove the admin of a workspace, right? So that box wouldn't/shouldn't be checked since it's not actionable... right?

https://user-images.githubusercontent.com/22508304/197305081-d7df3956-41fa-4db2-98d0-3ac3248fc00d.mp4

**Comment by kavimuru** [comment] 2022-10-21 23:51
@mallenexpensify Yes, shouldn't be able to select the admin to delete. But it allows to remove and then error message appears. This is only reproducible by following the same steps in the actions performed. Please change the profile image of size 3mb.

**Comment by mallenexpensify** [comment] 2022-10-24 14:55
Unable to reproduce on staging/Chrome with my test account. used a 4mb and 5mb test image. Works as expected.  

https://user-images.githubusercontent.com/22508304/197555942-8e91b089-8788-4f87-b5f2-748d0c574020.mp4

Tried other setups too - added two people then tried to select all, still no luck. 

Anything else I might be missing?  @kavimuru @adeel0202 are you both still able to repro?

**Comment by adeel0202** [comment] 2022-10-24 16:23
I'm also still able to reproduce.

> Also you should remove the member right after adding profile picture.

yup, you have to perform all the steps in a go and as quickly as possible.
upload a high res photo > go to any workspace > manage members page > select all > remove all selected members > select all

**Comment by mallenexpensify** [comment] 2022-10-24 18:04
Still not able to, tried multiple test accounts too, on staging and production, in chrome and firefox. 
Gonna dish to Engineering to see if they can.

**Comment by srikarparsi** [comment] 2022-10-28 01:01
yup checking now, was caught up with some other issues

**Comment by srikarparsi** [comment] 2022-10-28 01:14
hey, I'm also not able to reproduce. This was on staging and nothing of relevance came up in the console either. Anything else I could try to reproduce @kavimuru @adeel0202 ?

https://user-images.githubusercontent.com/48188732/198432539-c14571e7-5c29-4c07-b7af-e1ad7bfde768.mov

**Comment by adeel0202** [comment] 2022-10-28 06:26
@srikarparsi can you please try with a slower internet connection? I'm not sure but maybe you and @mallenexpensify are not able to reproduce because probably you guys have relatively faster internet connections.

Also, can you guys please try to reproduce [this one](https://expensify.slack.com/archives/C01GTK53T8Q/p1666372709197109) as well?

**Comment by srikarparsi** [comment] 2022-10-28 20:48
good idea @adeel0202, just tried it with slow connection and I'm able to reproduce the issue. 

https://user-images.githubusercontent.com/48188732/198729771-3b4c90f2-683e-49c3-bb4e-27599b72a575.mov

Will try reproducing the other one now.

**Comment by srikarparsi** [comment] 2022-10-28 21:03
I'm able to reproduce the second issue as well (manage members screen displaying an error after uploading high res profile picture with slow internet connection). I agree that the two issues are probably related. I'm a little busy with some other issues so will mark it external to get it looked at quicker.

https://user-images.githubusercontent.com/48188732/198732161-4bdb870e-35fc-43ec-a8f4-9b2484e1e61a.mov

**Comment by mallenexpensify** [comment] 2022-10-29 00:10
Job posted https://www.upwork.com/jobs/~015b8c264cc213a4cb

**Comment by mallenexpensify** [comment] 2022-10-31 16:25
Job's up, only been one biz day....

**Comment by tienifr** [comment] 2022-11-03 09:35
## Proposal

### Problem
When users have a slow connection and upload a high-resolution photo, then the user removes some members from the workspace, these policy members in Onyx aren't deleted immediately and just marked pendingAction is delete as this below image

<img width="1080" alt="Screen_Shot_2022-11-03_at_13 25 27" src="https://user-images.githubusercontent.com/113963320/199687694-8ed0cfef-341b-4ac4-a674-b74733711095.png">


### Solution
n Expensify/App/src/pages/workspace/WorkspaceMembersPage.js
we will add a filter to only pick out policy member who isn't marked pendingAction is delete

The sample PR: [tienifr/App: Pull Request 20](https://github.com/tienifr/App/pull/20)

Result: 

https://user-images.githubusercontent.com/113963320/199687822-36b01f4b-35f6-4f15-aa22-d69e8bb187c2.mp4

**Comment by mallenexpensify** [comment] 2022-11-03 15:40
@sobitneupane can you review @tienifr 's proposal above plz?

**Comment by michaelhaxhiu** [comment] 2022-11-03 21:40
Hey @mallenexpensify, just dropping a note as a reminder to [keep the pressure](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109) on to find a contributor and get this one closed out :)

Maybe consider doubling price tomorrow (7 day marker) as that could help surface a winning proposal and get us into the PR stage sooner! Will leave it to ya from here.

**Comment by sobitneupane** [comment] 2022-11-04 07:59
@tienifr Thanks for your proposal. I agree with your reason of this problem and your solution looks good.

@tienifr'a [Proposal](https://github.com/Expensify/App/issues/12066#issuecomment-1301842942) Looks good to me.

cc: @srikarparsi 

🎀👀🎀 C+ reviewed

**Comment by mallenexpensify** [comment] 2022-11-04 15:26
@srikarparsi , please review @tienifr 's proposal above 
https://github.com/Expensify/App/issues/12066#issuecomment-1301842942

**Comment by srikarparsi** [comment] 2022-11-07 11:13
This looks great to me as well. Thank you @tienifr, assigning you to the issue.

**Comment by tienifr** [comment] 2022-11-07 15:09
thanks @srikarparsi , I applied to the job, the PR will be ready by Nov 9

**Comment by mallenexpensify** [comment] 2022-11-07 23:23
Hired @tienifr . 
@adeel0202 and @sobitneupane , can you please apply? https://www.upwork.com/jobs/~015b8c264cc213a4cb

**Comment by tienifr** [comment] 2022-11-08 08:56
Hi @sobitneupane I just created a PR for this issue: https://github.com/Expensify/App/pull/12545
Could you help to review it? Thanks

**Comment by laurenreidexpensify** [comment] 2022-11-16 15:22
Updated BugZero Checklist: The PR fixing this issue has been merged! The following checklist (instructions) will need to be completed before the issue can be closed:

- [ ] [@srikarparsi @sobitneupane] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@srikarparsi @sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 
- [ ] [@srikarparsi @sobitneupane]  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@laurenreidexpensify] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:
- [ ] [@laurenreidexpensify] Applicable payments have been made. This potentially includes the issue reporter, the contributor that fixed the issue, and/or the contributor+ that helped on the issue.

**Comment by parasharrajat** [comment] 2022-11-17 10:42
There is a regression from this issue's PR https://github.com/Expensify/App/issues/12770 .

**Comment by laurenreidexpensify** [comment] 2022-12-01 11:04
@sobitneupane @srikarparsi can you confirm the status of the regression hold on this? Thanks

**Comment by sobitneupane** [comment] 2022-12-01 11:49
@laurenreidexpensify 

[PR](https://github.com/Expensify/App/pull/12878) was deployed to production 3 days back.

**Comment by laurenreidexpensify** [comment] 2022-12-05 14:35
All payments have been issued in Upwork.

@srikarparsi @sobitneupane can you please add any relevant links [here](https://github.com/Expensify/App/issues/12066#issuecomment-1317191255)

**Comment by laurenreidexpensify** [comment] 2022-12-05 14:40
Confirming Regression testing [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1670251206159689)

**Closed** 2022-12-07 13:55 UTC
Labels: Reviewing, External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by srikarparsi** [comment] 2022-12-08 21:34
hey @sobitneupane, do you have the bandwidth to work on the first three steps: https://github.com/Expensify/App/issues/12066#issuecomment-1317191255
