### ISSUE TITLE
[$1000] Inconsistent codeblock parsing that allowing codeblock to be styled

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18556] opened 2023-05-07 17:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Send this message to a chat : ~```Strikethrough codeblock```~
3. Send this message to a chat : _```Italic codeblock```_
4. Examine the difference of the parsing

## Expected Result : 
Either both message parsed appropriately (italic codeblock being italicized, strikethrough codeblock have strikethrough), or both message's styling shouldn't be parsed because codeblock shouldn't be styled
## Actual Result : 
The italic codeblock isn't italicized, but strikethrough codeblock have strikethrough

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="960" alt="1" src="https://user-images.githubusercontent.com/43996225/236694137-ca95f149-88ef-409a-ac34-228f86e22d38.png">

https://user-images.githubusercontent.com/43996225/236694146-44e73a68-76f4-4ce8-88df-dbcb39ee719f.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683378715811639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131f6c3fd981b25bb</li>
        <li>Upwork Job ID: 1655867220595605504</li>
        <li>Last Price Increase: 2023-05-09</li>
    </ul>
</details>

**Comment by dukenv0307** [comment] 2023-05-08 10:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent codeblock parsing that allowing codeblock to be styled
### What is the root cause of that problem?
Inconsistent rule replacement between italic and strikethrough

The rule replacement of italic is only wrapped inside with `em` tag if it doesn't `pre` tag
```
replacement: (match, g1) => (g1.includes('<pre>') ? match : `<em>${g1}</em>`),
```
While the rule replacement of strikethrough is always wrapped inside  with `del` tag
```
replacement: '<del>$1</del>',
```
### What changes do you think we should make in order to solve the problem?
Change the rule replacement of italic or strikethrough to be the same as the other.
### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment] 2023-05-09 09:27
Reproduced

**Comment by kerupuksambel** [comment] 2023-05-10 03:31
> @fedirjh you're correct. We didn't address that intentionally. Codeblock is always strikethrough when deleted offline. And no reason for preventing strikethrough inside strikethrough tag. So I think this is expected behavior.
> 
> There are some issues related to strikethrough codeblock, quote when deleted offline: #15571 #17365 #18042

If I may add, this issue is happened on online state, should it be treated like the offline state as well?

**Comment by bfitzexpensify** [comment] 2023-05-15 05:50
Cool, I agree. Closing this out.

**Closed by bfitzexpensify** 2023-05-15 05:50 UTC
Labels: External, Daily, Help Wanted, Bug
