### ISSUE TITLE
[$500] [MEDIUM] Web - IOU - "Category no longer valid" error message overlaps Category selection

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35203] opened 2024-01-25 22:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Employee creates manual request with category selected on collect workspace chat
2. Admin disable the selected category on Old Dot
3. Employee navigates to detailed IOU request

## Expected Result:
"Category no longer valid" error message should be under Category selection

## Actual Result:
"Category no longer valid" error message overlaps Category selection

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3be79c84-4c8f-4c9e-9554-196e2260f362

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01295a0277d76bca59</li>
        <li>Upwork Job ID: 1750645264825552896</li>
        <li>Last Price Increase: 2024-01-25</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-25 22:22
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by BhuvaneshPatil** [comment] 2024-01-25 22:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - IOU - "Category no longer valid" error message overlaps Category selection


### What is the root cause of that problem?
We have added negative top margin in `ViolationMessages` component.
https://github.com/Expensify/App/blob/ac94dc545a322de63375107e34e1ab31c26eaffe/src/components/ViolationMessages.tsx#L15

### What changes do you think we should make in order to solve the problem?
We shall remove that negative margin. Because this can happen in all places as well where we're using violation message.

### What alternative solutions did you explore? (Optional)
We shall pass a prop `styles` to `ViolationMessages`, so we can only change the component at places we want.
For example here -
https://github.com/Expensify/App/blob/ac94dc545a322de63375107e34e1ab31c26eaffe/src/components/ReportActionItem/MoneyRequestView.js#L346

This solution can handle the places we want, not global fix

**Comment by ikevin127** [comment] 2024-01-25 23:41
Dupes: https://github.com/Expensify/App/issues/35163 https://github.com/Expensify/App/issues/34539
Only diff is they are looking for different expected result than the current one.

**Comment by BhuvaneshPatil** [comment] 2024-01-25 23:57
@ikevin127 I don't think they are dupes.

**Comment by BhuvaneshPatil** [comment] 2024-01-26 00:05
sure @Krishna2323

**Comment by greg-schroeder** [comment] 2024-01-26 19:01
Awaiting proposal review

**Comment by BhuvaneshPatil** [comment] 2024-01-26 19:08
Just a heads up @Ollyws , this [Proposal](https://github.com/Expensify/App/issues/35203#issuecomment-1911105496) was updated after I posted mine. Before that it didn't mention about negative margin.

**Comment by amyevans** [comment] 2024-01-31 22:58
Thanks! Probably simplest to just close it

**Closed by amyevans** 2024-01-31 22:58 UTC
Labels: External, Daily, Help Wanted, Bug
