### ISSUE TITLE
[HOLD for payment 2024-11-21] [$250] Android - Compose Box - Composer not expanded when adding emojis until reaching second line

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51287] opened 2024-10-22 19:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/tests/view/5113856&group_by=cases:section_id&group_order=asc&group_id=306201
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the Expensify app
2. Open any chat
3. On compose box, add several emojis until reaching a second line
4. Verify the compose box is expanded and all the message is visible

## Expected Result:
When the message with emojis reaches a second line, the compose box should expand to make all the message visible

## Actual Result:
When adding several emojis and reaching a second line, the compose box is not expanded and only the second line is visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/58cde8f7-6a96-49a6-b213-eb6c74a2ce1c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851362613036850059</li>
        <li>Upwork Job ID: 1851362613036850059</li>
        <li>Last Price Increase: 2024-10-29</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 104755710</li>
<li>QichenZhu | Contributor | 104755712</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by lanitochka17** [comment] 2024-10-22 19:02
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shahinyan11** [comment] 2024-10-30 16:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Compose Box - Composer not expanded when adding emojis until reaching second line
### What is the root cause of that problem?
It is android behavior. We have set `height: 0` [here](https://github.com/Expensify/App/issues/51287#top) but currently the input height does not increase when adding emoji and reaching the second line
### What changes do you think we should make in order to solve the problem?
1.  Add new state in [Composer](https://github.com/Expensify/App/blob/431cadb53638082bc3e56c09eaca7ae52d117987/src/components/Composer/implementation/index.native.tsx#L52) component
```
const [inputContentHeight, setInputContentHeight] = useState<number | undefined>();
```
2. Update above state in [onContentSizeChange](https://github.com/Expensify/App/blob/431cadb53638082bc3e56c09eaca7ae52d117987/src/components/Composer/implementation/index.native.tsx#L121C13-L121C32)
```
onContentSizeChange={(e) => {
    setInputContentHeight(e?.nativeEvent?.contentSize?.height)
    ....
}
```
3. Update [composerStyle](https://github.com/Expensify/App/blob/431cadb53638082bc3e56c09eaca7ae52d117987/src/components/Composer/implementation/index.native.tsx#L111C11-L111C24) to bellow
```
const isAndroidNative = getPlatform() === CONST.PLATFORM.ANDROID
const composerStyle = useMemo(() => StyleSheet.flatten([
    style, textContainsOnlyEmojis ? styles.onlyEmojisTextLineHeight : {},
    isAndroidNative ? {height: inputContentHeight} : undefined
]), [style, textContainsOnlyEmojis, styles, inputContentHeight]);
```
### What alternative solutions did you explore? (Optional)

**Comment by QichenZhu** [comment] 2024-11-02 11:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The height of live markdown input doesn't fit its content on Android if it contains emojis.

### What is the root cause of that problem?
[`MarkdownEmojiSpan`](https://github.com/Expensify/react-native-live-markdown/blob/c282f64b11e8c8ea331add7a7d35d3cb57e450e0/android/src/main/java/com/expensify/livemarkdown/spans/MarkdownEmojiSpan.java#L6-L7) uses font size in DIP units.

<img width="748" alt="Screenshot 2024-11-02 at 11 52 28 PM" src="https://github.com/user-attachments/assets/b88b9755-4ea3-40ab-b2a7-55e0833784c0">

<p></p>

> [AbsoluteSizeSpan](https://developer.android.com/reference/android/text/style/AbsoluteSizeSpan#AbsoluteSizeSpan(int,%20boolean))(int size, boolean dip)
> Set the text size to size physical pixels, or to size device-independent pixels if dip is true.

However, the [text height measurement](https://github.com/Expensify/react-native-live-markdown/blob/c282f64b11e8c8ea331add7a7d35d3cb57e450e0/android/src/main/java/com/expensify/livemarkdown/CustomMountingManager.java#L52) treats the font size as if it’s in pixels, so the measured height doesn't match the actual height.

### What changes do you think we should make in order to solve the problem?
Use pixels in `MarkdownEmojiSpan`, just like in [`MarkdownFontSizeSpan`](https://github.com/Expensify/react-native-live-markdown/blob/c282f64b11e8c8ea331add7a7d35d3cb57e450e0/android/src/main/java/com/expensify/livemarkdown/spans/MarkdownFontSizeSpan.java#L9) below.

<img width="748" alt="Screenshot 2024-11-03 at 12 02 26 AM" src="https://github.com/user-attachments/assets/c01ebe0c-af4a-48e0-bffb-1a40d013648b">

### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment] 2024-11-03 09:40
Reviewing on Monday

**Comment by DylanDylann** [comment] 2024-11-04 09:38
@QichenZhu Your proposal doesn't work for me

<img width="344" alt="Screenshot 2024-11-04 at 16 37 39" src="https://github.com/user-attachments/assets/7ac1a0cf-4c96-4667-8676-2d6eb581e623">

**Comment by DylanDylann** [comment] 2024-11-04 09:38
@shahinyan11 Could you please provide a test branch?

**Comment by DylanDylann** [comment] 2024-11-04 10:34
@QichenZhu Thanks for your update

@QichenZhu's [proposal](https://github.com/Expensify/App/issues/51287#issuecomment-2452955435) looks good to me

🎀 👀 🎀 C+ Reviewed

**Comment by DylanDylann** [comment] 2024-11-07 03:53
@QichenZhu Let's create a PR on App repo to upgrade https://github.com/Expensify/react-native-live-markdown version

**Comment by QichenZhu** [comment] 2024-11-07 04:16
@DylanDylann The [PR](https://github.com/Expensify/App/pull/52017) to bump the library to an earlier version has already been reviewed, so how about waiting until it's merged as jumping versions tends to cause issues?

**Comment by mvtglobally** [comment] 2024-11-08 15:27
Issue not reproducible during KI retests. (First week)

**Comment by QichenZhu** [comment] 2024-11-09 00:27
Still reproducible. I'll open a PR in hours.

**Comment by anmurali** [comment] 2024-11-12 01:34
Rotating to get another BZ assigned while OOO

**Comment by DylanDylann** [comment] 2024-11-20 04:30
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by twisterdotcom** [comment] 2024-11-20 08:06
Payment Summary:

- @QichenZhu paid $250 [here](https://www.upwork.com/nx/wm/offer/104755712) (Contributor)
- @DylanDylann paid $250 [here](https://www.upwork.com/nx/wm/offer/104755710) (Reviewer)

**Closed** 2024-11-21 08:24 UTC
Labels: External, Daily, Awaiting Payment, Bug
