### ISSUE TITLE
[$500] Task - Reply in thread not present for complete and incomplete system messages

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30449] opened 2023-10-26 15:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-6

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Open the app
2. Navigate to any chat
3. Tap "+" and select " Assign task"
4. Enter title and assign a task to any user
5. Mark the task as "Complete", "Incomplete" and cancel the task
6. Log tap the system message "marked as complete", "marked as icomplete" and " deleted task"

## Expected Result:
The "Reply in thread" option is displayed for all system messages.

## Actual Result:
The "Reply in thread" option is shown only for the "deleted" message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/115492554/c7f2abd7-a7fc-486e-a5fc-5b70d5c93a18

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111143f6223d8f611</li>
        <li>Upwork Job ID: 1717569645460910080</li>
        <li>Last Price Increase: 2023-10-26</li>
    </ul>
</details>

**Comment by cooldev900** [comment] 2023-10-26 16:22
https://app.slack.com/client/T03SC9DTT/C049HHMV9SM/thread/C049HHMV9SM-1698127384.173859

## Proposal
from: @cooldev900
### Please re-state the problem that we are trying to solve in this issue.
Reply in thread not present for complete and incomplete system messages in task report page.
### What is the root cause of that problem?
The root cause is because we returns false in shouldShow function in 

https://github.com/Expensify/App/blob/cb5aeb14f6dfbdcd4b4e831d55fb17dc678e093f/src/pages/home/report/ContextMenu/ContextMenuActions.js#L124-L127

### What changes do you think we should make in order to solve the problem?
We can commet following code and should implement the 'reply in thread' functionality.
```
if (type !== CONTEXT_MENU_TYPES.REPORT_ACTION) {
      return false;
  }
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by thienlnam** [comment] 2023-10-26 23:50
This has already been fixed in https://github.com/Expensify/Auth/pull/9042, should be live now

**Comment by thienlnam** [comment] 2023-10-26 23:55
Verified this is fixed now
<img width="732" alt="Screenshot 2023-10-26 at 4 55 04 PM" src="https://github.com/Expensify/App/assets/30609178/84eac99d-f938-42bc-bc6d-2634e4c10a21">

**Closed by thienlnam** 2023-10-26 23:55 UTC
Labels: External, Daily, Help Wanted, Bug
