### ISSUE TITLE
[$500]  Bank Account - No character limit on Legal Business name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31874] opened 2023-11-26 00:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to settings > Workspace > choose a works space
2. Bank account > Connect Manually
3. Fill the details of step one and go to step 2
4. Go to Legal Business name and type a long long name.
Notice that the field allows you to enter any amount of characters. No End

## Expected Result:
There is a character limit for legal business names

## Actual Result:
No character limit

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b4f68c6b-24db-49eb-80d1-53a23d45469b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ab3357e3b21f462</li>
        <li>Upwork Job ID: 1728574837185871872</li>
        <li>Last Price Increase: 2023-11-26</li>
    </ul>
</details>

**Comment by giltron** [comment] 2023-11-26 01:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The input field for the business name can be of any length and is beyond reasonable.  
(over 1600 characters in the example which is beyond what a legal business name could be)

### What is the root cause of that problem?

InputWrapper in CompanyStep has no input character limit
(https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/pages/ReimbursementAccount/CompanyStep.js#L165)



### What changes do you think we should make in order to solve the problem

Set a reasonable maximum limit with the InputWrapper in CompanyStep.  This value should go in  CONST.ts with the explanation on the limit (ie. 40)

```
<InputWrapper
                    InputComponent={TextInput}
                    label={translate('companyStep.legalBusinessName')}
                    accessibilityLabel={translate('companyStep.legalBusinessName')}
                    role={CONST.ACCESSIBILITY_ROLE.TEXT}
                    inputID="companyName"
                    containerStyles={[styles.mt4]}
                    disabled={shouldDisableCompanyName}
                    maxLength={CONST.MAX_BUSINESS_NAME_LENGTH}
                    defaultValue={getDefaultStateForField('companyName')}
                    shouldSaveDraft
                    shouldUseDefaultValue={shouldDisableCompanyName}
                />
```



### What alternative solutions did you explore? (Optional)

**Comment by lukaspawlik** [comment] 2023-11-26 01:36
### Proposal

Please find attached patch as a solution for the problem. CompanyStep.js component on lines 165-176 should have `maxLength` prop with the value coming from `CONST.ts` and named `CONST.LEGAL_NAMES_CHARACTER_LIMIT`.

```
diff --git a/src/pages/ReimbursementAccount/CompanyStep.js b/src/pages/ReimbursementAccount/CompanyStep.js
index e31988fbb1..79a6467003 100644
--- a/src/pages/ReimbursementAccount/CompanyStep.js
+++ b/src/pages/ReimbursementAccount/CompanyStep.js
@@ -165,6 +165,7 @@ function CompanyStep({reimbursementAccount, reimbursementAccountDraft, getDefaul
                 <InputWrapper
                     InputComponent={TextInput}
                     label={translate('companyStep.legalBusinessName')}
+                    maxLength={CONST.LEGAL_NAMES_CHARACTER_LIMIT}
                     accessibilityLabel={translate('companyStep.legalBusinessName')}
                     role={CONST.ACCESSIBILITY_ROLE.TEXT}
                     inputID="companyName"
```

**Comment by lukaspawlik** [comment] 2023-11-26 01:38
Contributor details:
Your Expensify account email: lukasz.pawlik@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d0a5c201a9ae3e6a

**Comment by lukaspawlik** [comment] 2023-11-26 01:40
Contributor details
Your Expensify account email: lukasz.pawlik@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d0a5c201a9ae3e6a

**Comment by jaimishg2098** [comment] 2023-11-26 03:56
### How Can i Solve the max length issue?

I went thought the code and found issue in validate function, there is not max length condition and also max-length props is not there.

`<InputWrapper
                    InputComponent={TextInput}
                    label={translate('companyStep.legalBusinessName')}
                    accessibilityLabel={translate('companyStep.legalBusinessName')}
                    role={CONST.ACCESSIBILITY_ROLE.TEXT}
                    inputID="companyName"
                    containerStyles={[styles.mt4]}
                    disabled={shouldDisableCompanyName}
                    defaultValue={getDefaultStateForField('companyName')}
                    shouldSaveDraft
                    shouldUseDefaultValue={shouldDisableCompanyName}
                />`

**Comment by DylanDylann** [comment] 2023-11-26 03:57
This should be handled in [here](https://github.com/Expensify/App/issues/31874)

**Comment by ashishdevswami** [comment] 2023-11-26 12:23
Contributor details
Your Expensify account email: ashishdevswami@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011ad3126c906e7452

**Comment by ashishdevswami** [comment] 2023-11-26 12:47
I observed the code implemented here and found maxLength property is missing for the InputWrapper component object on line 165. Implementing this will solve the issue and this is as per the standard of code. 

https://github.com/Expensify/App/assets/2726330/e9bbf3fa-ad6b-4239-a8b6-000c2113c858

**Comment by kevinksullivan** [comment] 2023-12-12 02:12
Hi @mananjadhav , are you going to review these proposals? If not in the next day or two I'll have to reassign.

**Comment by mananjadhav** [comment] 2023-12-12 04:25
I think we should close this and handle it [here](https://github.com/Expensify/App/issues/18647)

**Comment by kevinksullivan** [comment] 2023-12-14 14:52
Got it, I am going to close then.

**Closed by kevinksullivan** 2023-12-14 14:52 UTC
Labels: Reviewing, External, Daily, Help Wanted, Bug
