### ISSUE TITLE
[HOLD for payment 2022-11-16] [$500] [BUG] - Url isn't fully visible in the tooltip reported by @thesahindia

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11486] opened 2022-09-30 23:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to any chat
2. Send a long url (e.g. https://www.expensify.com/inbox?policyID=D189E4B5582EAE8D&taskID=AddWorkEmail)
3. Hover

## Expected Result:
The whole Url should be visible

## Actual Result:
The Url isn't fully visible

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.10-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="960" alt="3" src="https://user-images.githubusercontent.com/43996225/193368347-ae12ea79-855a-4418-b95b-ea3ebbbdb5ba.png">
<img width="416" alt="Screenshot 2022-09-29 at 5 55 52 PM" src="https://user-images.githubusercontent.com/43996225/193368354-6fc84248-613a-446c-a6d5-96c4484736ef.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664484641135769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment] 2022-10-05 09:05
Hmm, this is because we have an intentional max-width restriction for tooltips. I'd assume we wouldn't want to have that dynamically sized based on the length of the link. That could look really weird if the link is super long...

<img width="756" alt="Screen Shot 2022-10-05 at 10 56 26" src="https://user-images.githubusercontent.com/16747822/194023074-462e395e-c131-4cd2-9d41-80fbeeb8df11.png">

Theoretically we could do something like a scrolling tooltip but I'm not sure it's really necessary or that it's a bug that it's cut off and doesn't scroll. cc: @shawnborton since you added the original maxWidth restriction [here](https://github.com/Expensify/App/blob/7ea5f78734d4e107433979777a554ba69c44676b/src/styles/variables.js#L14) (it's used [here](https://github.com/Expensify/App/blob/f0524e7b2789605cf9dd7bdc25c5c398b89873bf/src/components/Tooltip/tooltipPropTypes.js#L43)

**Comment by parasharrajat** [comment] 2022-10-05 09:37
This feels like a regression. Tooltip content should wrap in next lines after max width is reached.

**Comment by NikkiWines** [comment] 2022-10-05 10:18
Given that, marking this as external so we can get someone working on this.

**Comment by shawnborton** [comment] 2022-10-05 16:08
Personally I think it this is fine as it is with the max-width, but perhaps we should truncate via ellipsis instead of just a hard cut off.

**Comment by shawnborton** [comment] 2022-10-05 16:09
But actually, seeing your comment above:

> Ohh, yes, you're right @parasharrajat - looks like max lines should be 3 but it's not wrapping. That still feels (to me) like it would be bulky but I think you're right that it's a regression

I agree with that

**Comment by NikkiWines** [comment] 2022-10-05 17:05
@shawnborton, to be clear, you're suggesting we keep it to a single line but truncate with an elipsis?

**Comment by sobitneupane** [comment] 2022-10-09 05:43
@aimane-chnaif We would want this issue to be fixed without creating the other issue. So, Proposal that fixes this issue without affecting other would be ideal.

**Comment by bfitzexpensify** [comment] 2022-10-11 07:04
Upwork job [here](https://www.upwork.com/jobs/~014143204f1cdb68fd)

Reporting job [here](https://www.upwork.com/jobs/~01f7664133d31b114b) @thesahindia

**Comment by danishyasin33** [comment] 2022-10-11 07:48
Hi everyone, 

The issue seems to have something to do with how the width of the tooltip is calculated. If I remove the the width or set it to `fit-content` then the URL shows it's full length.
![image](https://user-images.githubusercontent.com/47951155/195027202-360c5fce-2306-4d82-9e77-46c9b828c7e5.png)

### The Fix:
To fix it, we can fix the width attribute of the tooltip for it to appear correctly. 

Or, if the team wants that the tooltip is wrapped after some fix width, say 400px, then we'll have to add a wrap attribute around the span of the tooltip.
Something like this: 
![image](https://user-images.githubusercontent.com/47951155/195029103-eb7738ed-0967-41d3-9825-d07788517348.png)

Whatever the team decides, I can make that fix and should be a quick process.

**Comment by sobitneupane** [comment] 2022-10-11 13:53
Hello @danishyasin33, Can you please point out the file where you proposing to make change and what are the changes you are proposing? Some codeblocks will be helpful. For example: https://github.com/Expensify/App/issues/11388#issuecomment-1262745992

If you haven’t already, check out [CONTRIBUTING GUIDELINES](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by fedirjh** [comment] 2022-10-11 14:16
hello there

This issue is related to white Space : it is set to nowrap which suppresses line breaks within the source text . to fix this you set `white-space:normal ;` and add `word-break: break-all;` to prevent overflow 

component to edit is [getTooltipStyles.js](https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/styles/getTooltipStyles.js#L161)


![Screenshot from 2022-10-11 15-11-11](https://user-images.githubusercontent.com/36869046/195115940-84593616-3bd1-4351-bc77-cf1007e7cf9f.jpg)

**Comment by danishyasin33** [comment] 2022-10-11 14:26
Hi @sobitneupane, 

So the file I would edit would be: 
https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/styles/getTooltipStyles.js#L160-L161

I would update it to: 
```diff
            overflow: 'hidden',
+          whiteSpace: 'break-spaces',
```

I believe this would fix the said issue if we are going for the line-break course of action.

**Comment by danishyasin33** [comment] 2022-10-12 13:23
@sobitneupane if my proposed fix is satisfactory, could I be assigned this job please. 😄

**Comment by sobitneupane** [comment] 2022-10-12 13:42
@danishyasin33 @fedirjh 
Thanks for the proposal.

Both the proposals have some issues. Changes suggested will recreate the issue fixed by:  https://github.com/Expensify/App/pull/10504

**Comment by fedirjh** [comment] 2022-10-12 19:53
@sobitneupane thanks for the update.

It looks like safari is still supporting the old alias of `overflow-wrap` which is `word-wrap` . here is an updated solution that works on safari and chrome . Tested on Safari and Chrome

changes made 

```diff
-          whiteSpace: 'nowrap', 
+          whiteSpace: 'normal',
+          wordWrap: 'normal', 
```
on 

https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/styles/getTooltipStyles.js#L161

**Comment by danishyasin33** [comment] 2022-10-12 21:22
Hi @sobitneupane, 

I tested it both Chrome and Safari after adding `white-space: break-spaces`, it does not recreate the issue fixed by #10504. 

Here's a demo on both safari and chrome. 

Chrome: 

https://user-images.githubusercontent.com/47951155/195449997-70e9a5ea-031f-4441-b4eb-cb03fa0d15b4.mov

Safari: 

https://user-images.githubusercontent.com/47951155/195450328-6cc63406-cc4c-4f27-a0ec-f85d69a57cc1.mov


As such, I don't see how it would cause regression and the original solution I proposed should be sufficient in the resolution of this error.

**Comment by sobitneupane** [comment] 2022-10-13 02:48
@fedirjh @danishyasin33 @aimane-chnaif 

The issue is existent not only on safari but also on other browsers.

https://user-images.githubusercontent.com/25876548/195486788-b029ef12-18c9-4ad2-94c2-fa9d62cb91d8.mov

**Comment by danishyasin33** [comment] 2022-10-13 08:39
@sobitneupane you're right about the unintended consequences. To fix this, we'll need to pass a prop down from the `BaseAnchorForCommentsOnly` file where we'll define the `TooltipType` as `commentLink`. 

This will be passed down all the way to `getTooltipStyles` and whitespace style will be determined by the following condition: 
`const tooltipWhiteSpace = tooltipType == 'commentLink' ? 'break-spaces' : 'nowrap'`

`BaseAnchorForCommentsOnly.js`:
```diff
<Tooltip 
+           tooltipType="commentLink" 
            text={Str.isValidEmail(props.displayName) ? '' : props.href}>
                <Text
                    ref={el => linkRef = el}
                    style={StyleSheet.flatten([props.style, defaultTextStyle])}
                    accessibilityRole="link"
                    hrefAttrs={{
                        rel: props.rel,
                        target: props.target,
                    }}
                    // eslint-disable-next-line react/jsx-props-no-spreading
                    {...linkProps}
                    // eslint-disable-next-line react/jsx-props-no-spreading
                    {...rest}
                >
                    {props.children}
                </Text>
            </Tooltip>
```

`getTooltipStyles.js`:
```diff
.
.
.
 *                                         A positive value shifts it to the right,
 *                                         and a negative value shifts it to the left.
 * @param {Number} [manualShiftVertical] - Any additional amount to manually shift the tooltip up or down.
 *                                       A positive value shifts it down, and a negative value shifts it up.
+ * @param {String} [tooltipType] - Defines the type of tool tip
 * @returns {Object}
 */

.
.
.

+    // We get the tooltip WhiteSpace style by determining which type of tooltip it is.
+    const tooltipWhiteSpace = tooltipType == 'commentLink' ? 'break-spaces' : 'nowrap'

.
.
.

        tooltipTextStyle: {
            color: themeColors.textReversed,
            fontFamily: fontFamily.GTA,
            fontSize: tooltipFontSize,
            overflowWrap: 'normal',
            overflow: 'hidden',
+          whiteSpace: tooltipWhiteSpace,
            left: '1px',
        },

```

This keeps the change limited to just the tooltips of the comments. Avoid any unnecessary regression. 

Demo (desktop):

https://user-images.githubusercontent.com/47951155/195546784-99e4bf20-2f03-4c6c-bc4b-06da70d1c5b2.mov

**Comment by fedirjh** [comment] 2022-10-13 11:01
@sobitneupane the problem with `white-space: nowrap;`  , it always suppresses line breaks always even when width is set , i have 2 solution 

## Solution 1

Since we have the both `tooltipTextWidth` and `maxWidth` . we can set dynamically the white-space to no-wrap if tooltipTextWidth < maxWidth else if tooltipTextWidth exceeds the max width we set white-space to normal (or  break-spaces)

https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/styles/getTooltipStyles.js#L155-L162

```diff
-whiteSpace: 'nowrap'
+whiteSpace: tooltipTextWidth && tooltipTextWidth > maxWidth ? 'normal' : 'nowrap'
```

## Solution 2

After we measure the tooltipTextWidth , we update the whitespace property. **white-space should be set to nowrap on getTooltipStyles.js** .

https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/components/Tooltip/TooltipRenderedOnPageBody.js#L83-L87

```diff
updateTooltipTextWidth() {
        this.setState({
            tooltipTextWidth: this.textRef.offsetWidth,
        });
+        this.textRef.style.whiteSpace = 'normal'
    }
```

**then we add a key to the tooltipText**

https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/components/Tooltip/TooltipRenderedOnPageBody.js#L128

```diff
-<Text style={tooltipTextStyle} ref={ref => this.textRef = ref}>{this.props.text}</Text>
+<Text style={tooltipTextStyle} key={this.props.text} ref={ref => this.textRef = ref}>{this.props.text}</Text>
```

**Comment by sobitneupane** [comment] 2022-10-14 14:33
@danishyasin33 @fedirjh 

Proposals above might fix the issue. But both of them look quite hacky to me.

I believe the best course of action will be to remove `whiteSpace: 'nowrap',` line which cause this issue(introduced in https://github.com/Expensify/App/pull/10504 PR to solve issue mentioned [here](https://github.com/Expensify/App/issues/11486#issuecomment-1276957645)) and find a way to resolve the [issue](https://github.com/Expensify/App/issues/11486#issuecomment-1276957645) the [PR](https://github.com/Expensify/App/pull/10504) was trying to solve.

cc: @thienlnam

**Comment by fedirjh** [comment] 2022-10-14 16:13
@sobitneupane may i ask a question here , what is the utility of setting the width of the `tooltipWrapper` to the tooltip width , we can just set `width:auto;` and add maxWidth

https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/styles/getTooltipStyles.js#L116-L124

```jsx
     zIndex: variables.tooltipzIndex, 
-    width: wrapperWidth,
+    width: 'auto',
+    maxWidth,
```

then we can remove the whiteSpace
https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/styles/getTooltipStyles.js#L161

```diff
-              whiteSpace: 'nowrap'
```

**Comment by thienlnam** [comment] 2022-10-17 02:15
Alright, looks like we have a couple conditions here.

- We need the tooltip to be long enough to show the 'Unpinned' copy in this [issue](https://github.com/Expensify/App/issues/9331)
- We want the tooltip to wrap into multiple lines when it becomes too long

With that being said, like @sobitneupane we will need to remove the `whiteSpace: 'nowrap'` line and figure out a different solution that resolves both cases. 

We have a prop [maxWidth](https://github.com/Expensify/App/blob/363d98fd3a3567c102c5359ba5257c67f95c60d0/src/components/Tooltip/index.js#L183-L183) that is passed down as a prop which is used to determine the wrapperWidth [here](https://github.com/Expensify/App/blob/363d98fd3a3567c102c5359ba5257c67f95c60d0/src/styles/getTooltipStyles.js#L100-L105).  I don't think we want to set a max-width because it will mess up the usage of tooltip in these other locations.  Though @sobitneupane can you please test these proposals?

**Comment by chauchausoup** [comment] 2022-10-18 07:00
Issue:

`whiteSpace: 'nowrap'` is creating a single line tooltip in Chat section especially for URLs. We can remove it but to my investigation we can see changes in two areas. 
1. pin/Unpin section in chat Report header section
2. Copy to Clipboard/ Copied in Reimburse expenses

Solution:
We can add numberOfLines ={1} in both of the above fields once we remove whiteSpave: 'nowrap' from getToolTipStyles.js file.

Proposal:

 tooltipTextStyle: { 
     color: themeColors.textReversed, 
     fontFamily: fontFamily.GTA, 
     fontSize: tooltipFontSize, 
     overflowWrap: 'normal', 
     overflow: 'hidden', 
  //   whiteSpace: 'nowrap', 
 }, 
 
<Tooltip numberOfLines={1} text={props.report.isPinned ? props.translate('common.unPin') : props.translate('common.pin')}>

<Tooltip numberOfLines={1} text={this.props.translate(`reportActionContextMenu.${this.state.showCheckmark ? 'copied' : 'copyToClipboard'}`)}>

**Comment by chauchausoup** [comment] 2022-10-18 07:04
**Issue**:

whiteSpace: 'nowrap' is creating a single line tooltip in Chat section especially for URLs. We can remove it but to my investigation we can see changes in two areas.

pin/Unpin section in chat Report header section
Copy to Clipboard/ Copied in Reimburse expenses

**Solution**:
We can add numberOfLines ={1} in both of the above fields once we remove whiteSpave: 'nowrap' from getToolTipStyles.js file.

**Proposal**:

getToolTipStyles.js 

tooltipTextStyle: {
color: themeColors.textReversed,
fontFamily: fontFamily.GTA,
fontSize: tooltipFontSize,
overflowWrap: 'normal',
overflow: 'hidden',
// whiteSpace: 'nowrap',
},

HeaderView.js
```
<Tooltip numberOfLines={1} text={props.report.isPinned ? props.translate('common.unPin') : props.translate('common.pin')}>
```

CopyTextToClipboard.js
```
<Tooltip numberOfLines={1} text={this.props.translate(reportActionContextMenu.${this.state.showCheckmark ? 'copied' : 'copyToClipboard'})}>
```

**Comment by sobitneupane** [comment] 2022-10-18 09:05
So, the problem lies in those `Tooltip` where the tooltip text is being changed with user interaction. As mentioned by @chauchausoup, pin/unpin and Copy to clipboard/copied are tooltips being changed with user interaction. (We should look for other such cases if any.)

The ideal solution would be to update [wrapperWidth](https://github.com/Expensify/App/blob/363d98fd3a3567c102c5359ba5257c67f95c60d0/src/styles/getTooltipStyles.js#L100-L105) when tooltip text changes which does not look like an easy task.

[Proposal](https://github.com/Expensify/App/issues/11486#issuecomment-1281906591) from @chauchausoup solves both issues. So, one option would be to go with his solution and the other to wait for the proposal which updates wrapperWidth with change in tooltip text.

cc: @thienlnam

**Comment by fedirjh** [comment] 2022-10-18 15:20
@sobitneupane any feedback here https://github.com/Expensify/App/issues/11486#issuecomment-1279204962 ? 
also there is an issue with https://github.com/Expensify/App/issues/11486#issuecomment-1281906591 , if we consider that tooltip text should wrap to max 3 lines , if url is longer it will only wrap to 2 lines

![Screenshot from 2022-10-18 16-07-29](https://user-images.githubusercontent.com/36869046/196472398-7b68e8e0-0419-465c-8a44-b861208b049f.png)

**Comment by sobitneupane** [comment] 2022-10-18 16:02
> @sobitneupane any feedback here https://github.com/Expensify/App/issues/11486#issuecomment-1279204962 ?

@fedirjh Your question is already answered here https://github.com/Expensify/App/issues/11486#issuecomment-1280178507 . There are many edge cases that should be considered.
With your proposed solution:
<img width="300" alt="Screen Shot 2022-10-18 at 21 38 01" src="https://user-images.githubusercontent.com/25876548/196481851-967e865b-6aeb-48f0-a3da-ecb56a70289e.png">
<img width="505" alt="Screen Shot 2022-10-18 at 21 29 55" src="https://user-images.githubusercontent.com/25876548/196481862-a0a7d165-d242-4e97-9ee3-e2cfa4fe4b4d.png">
<img width="505" alt="Screen Shot 2022-10-18 at 21 27 42" src="https://user-images.githubusercontent.com/25876548/196481884-b2c1b7c0-b33b-42a5-bafb-d6537725514d.png">


> also there is an issue with https://github.com/Expensify/App/issues/11486#issuecomment-1281906591 , if we consider that tooltip text should wrap to max 3 lines , if url is longer it will only wrap to 2 lines

Thats weird. It tested well in firefox and safari. But in Chrome tooltip wrap to 2 lines. Not sure if it was a known issue.

**Comment by chauchausoup** [comment] 2022-10-19 01:11
https://user-images.githubusercontent.com/34975245/196573868-62d3d7e3-53c9-4ffc-9b62-acf9e2a0ac54.mov

Working fine in here.

**Comment by thienlnam** [comment] 2022-10-21 08:48
For https://github.com/Expensify/App/issues/11486#issuecomment-1281906591, how come we're setting ` numberOfLines ={1}` in just those files? Doesn't that just limit the URL to a single line in those locations which is not the outcome we are looking for (we still want the URL to wrap).

So what it sounds like we need to do is get a proposal which updates wrapperWidth with change in tooltip text. It will be more complex, so we can double the job price but that's ideal over going with a temporary solution here so please look for those proposals @sobitneupane

**Comment by thienlnam** [comment] 2022-10-21 08:48
@bfitzexpensify Could we please get the job price doubled here?

**Comment by sobitneupane** [comment] 2022-10-21 09:08
> So what it sounds like we need to do is get a proposal which updates wrapperWidth with change in tooltip text. 

+1 

Waiting for proposal which updates wrapperWidth with change in tooltip text

**Comment by fedirjh** [comment] 2022-10-21 12:08
@sobitneupane actually setting a key for tooltip render will ensure toottip rerendering when text changes , this fix width recalculation 

https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/components/Tooltip/index.js#L173-L174
```diff
<TooltipRenderedOnPageBody
                        animation={this.animation}
+                       key={this.props.text}
```

we will need to remove the whiteSpace: 'nowrap'
https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/styles/getTooltipStyles.js#L161

```diff
-              whiteSpace: 'nowrap'
```

**Comment by fedirjh** [comment] 2022-10-21 19:31
i think the issue is when we componentDidUpdate , we use the old state value to calculate new one , which results a wrong value , i think to get the right value we should reset the value of `tooltipTextWidth` to the initiavaluel value `tooltipTextWidth: 0,` then recalculate the value . here is explanation , when the component is rendered the first time `getTooltipStyles()` uses initial values this will set tooltipWrapperStyle.width = 375 (max width) , then it will calculate the tooltipTextWidth based on that style . then `tooltipWrapperStyle.width = tooltipTextWidth + (spacing.ph2.paddingHorizontal * 2) + 1 || maxWidth` . so the issue will appear if the previous tooltipTextWidth < ( maxwidth && the actual tooltipTextWidth ) , and the style that will be used to recalculate will be the previous tooltipTextWidth . so i propose the rest to initial value when componentDidUpdate then recacuate . @sobitneupane your thoughts ?

https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/components/Tooltip/TooltipRenderedOnPageBody.js#L76-L81

```diff
-     this.updateTooltipTextWidth(); 
+     this.setState({tooltipTextWidth: 0}, () => this.updateTooltipTextWidth()); 
```

we will need to remove the whiteSpace: 'nowrap' , the overflowWrap: 'normal' will prevent the second line from wrapping
https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/styles/getTooltipStyles.js#L159-L161

```diff
-           overflowWrap: 'normal',
            overflow: 'hidden',
-           whiteSpace: 'nowrap',
```

**Comment by danishyasin33** [comment] 2022-10-23 13:46
Hi all, 

I've been following the conversation and I feel we're going in loops. I've tested the following solution thoroughly and it seems to be getting the job done. 

1. I don't see the need for updating the `wrapperWidth`. It won't resolve the issue we are discussion, the issue being: `wrap longer than x length tooltips`. The width already updates according to the text, you can check that via logging the widths of when tooltips update. cc: @thienlnam @sobitneupane 
2. The solution is pretty straightforward in my opinion, you simply need to set the `overflow-wrap` and `whiteSpace` CSS properties properly. You can determine that just by using the following piece of code: 

`src/styles/getTooltipStyles.js:`
```diff
     // We get the tooltip WhiteSpace and overflow wrap style by determining which type of tooltip it is.
+    const tooltipWhiteSpace = componentWidth && componentWidth < maxWidth ? 'nowrap' : 'normal'
+    const tooltipWrap = componentWidth && componentWidth < maxWidth ? 'normal' : 'break-word'
```

You can check the whole PR here: 
https://github.com/Expensify/App/pull/12079/files
Please note that it is a draft PR and I will prepare it properly if I am assigned the job. 

In the PR, I defined the maxToolTip width as 300px because I felt that's the appropriate maxWidth for showing URLs. 

## Demos: 
Chrome (Edge): 

https://user-images.githubusercontent.com/47951155/197395728-df275a4f-b5a1-4154-9941-100c3c346e43.mov

SafarI:

https://user-images.githubusercontent.com/47951155/197395801-ed7bb3da-9d46-4238-b759-0e08c656980d.mov

**Comment by sobitneupane** [comment] 2022-10-24 07:52
Thanks for the proposals. I won't be available today. I will review them tomorrow.

**Comment by sobitneupane** [comment] 2022-10-25 05:50
@fedirjh I tend to agree with your reasoning in [this proposal.](https://github.com/Expensify/App/issues/11486#issuecomment-1287358882) Few points:
-  You have pointed out that "previous value of `tooltipTextWidth` is being used." I can verify this happening.
- "We will need to remove the whiteSpace: 'nowrap'." I agree with you here.
- "overflowWrap: 'normal' will prevent the second line from wrapping". Can you explain, why? (as this is happening only in chrome)
- Any  shortcomings from removing `overflowWrap: 'normal'`?

**Comment by sobitneupane** [comment] 2022-10-25 05:57
@danishyasin33 Thanks for your proposal.

> The width already updates

It does. But it  does not update to a correct value. It's value is updated to `tooltipTextWidth + (spacing.ph2.paddingHorizontal * 2) + 1`, i.e, previous tooltipTextWidth +17.

I believe the better approach will be to find the reason for the issue rather than just getting the job done.

**Comment by bfitzexpensify** [comment] 2022-10-27 15:12
I've doubled the job to $500 - I know we have proposals being discussed, but let's make this a little more lucrative to get more action happening here

**Comment by sobitneupane** [comment] 2022-10-31 08:16
> @fedirjh I tend to agree with your reasoning in [this proposal.](https://github.com/Expensify/App/issues/11486#issuecomment-1287358882) Few points:
> 
> * You have pointed out that "previous value of `tooltipTextWidth` is being used." I can verify this happening.
> * "We will need to remove the whiteSpace: 'nowrap'." I agree with you here.
> * "overflowWrap: 'normal' will prevent the second line from wrapping". Can you explain, why? (as this is happening only in chrome)
> * Any  shortcomings from removing `overflowWrap: 'normal'`?

Waiting for @fedirjh response.

**Comment by fedirjh** [comment] 2022-11-01 20:03
hey there @sobitneupane 

> "overflowWrap: 'normal' will prevent the second line from wrapping". Can you explain, why? (as this is happening only in chrome)

it's on Firefox too , you can reproduce with this URL test : https://www.expensify.com/inbox?policyIDD189E4B5582EAE8DtaskIDAddWorkEmailpolicyIDD189E4B5582EAE8D&taskIDAddWorkEmailpolicyIDD189E4B5582EAE8DtaskIDAddWorkEmailpolicyID=D189E4B5582EAE8DtaskIDAddWorkEmailpolicyID189E4B5582EAE8DtaskIDAddWorkEmailpolicyIDD189E4B5582EAE8DtaskIDAddWorkEmailpolicyIDD189E4B5582EAE8DtaskIDAddWorkEmail

`overflowWrap: 'normal'` is actually overriding the default style which is  `overflow-wrap: break-word; ` , it's added in this commit https://github.com/Expensify/App/commit/6caff3ca9a49498cda995c14096f5202c1aa3bf3#diff-3c27ed5ef3408ae8e44446ed4eaddb058d5088dad2c9ae4022b318dbd0c986ae


![Screenshot from 2022-11-01 21-02-34](https://user-images.githubusercontent.com/36869046/199328463-5127060c-aeac-477a-9af9-740dc910c5d3.png)

**Comment by thienlnam** [comment] 2022-11-02 17:13
Let's give it a whirl 🟢

**Comment by bfitzexpensify** [comment] 2022-11-17 11:31
All paid out - thanks for the work here!

**Closed by bfitzexpensify** 2022-11-17 11:31 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
