### ISSUE TITLE
[HOLD for payment 2024-01-31] [$500] Web - Compose box - The compose box displays duplicate characters upon pressing a single key

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33710] opened 2023-12-28 14:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Open a conversation
2. Click anywhere outside the compose box
3. Press on any character on the keyboard (Only once)
4. Observe the number of characters displayed inside of the compose box

## Expected Result:
When a single key is pressed only a single character should be displayed inside the compose box

## Actual Result:
When pressing only a single key duplicate characters are displayed inside the compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/272a4186-f69a-41a3-91df-fb33b936b2a9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5ce38ee6504ce3e</li>
        <li>Upwork Job ID: 1740378947399057408</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28090824</li>
<li>bernhardoj | Contributor | 28090825</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-12-28 14:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The compose box displays duplicate characters upon pressing a single key

### What is the root cause of that problem?
We are subscirbing to two listeners on key press `ComposerWithSuggestions`
### What changes do you think we should make in order to solve the problem?

We should subscribe to one listener
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2023-12-28 14:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The text is doubled when pressing a key while the composer is not focused.

### What is the root cause of that problem?
We have a key-down listener that will:
1. Focus on the composer
2. Add the pressed key to the composer

https://github.com/Expensify/App/blob/88d837c2e88c8c4c22a4c80f93b622d634e67290/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L455-L472

The reason it added a duplicate character is, that the native input first receives the pressed key (because we focus on it) and we manually add the pressed key to the composer.

### What changes do you think we should make in order to solve the problem?

Remove `replaceSelectionWithText` after focusing the composer.

**Comment by strepanier03** [comment] 2024-01-04 00:14
I've been OoO, taking a look now.

**Comment by strepanier03** [comment] 2024-01-04 00:18
Weird, but reproducible. 

Chrome/Web

https://github.com/Expensify/App/assets/10925636/b0812f12-6f13-413e-8bc6-47722cce4f1f

**Comment by strepanier03** [comment] 2024-01-04 00:26
Checking internally, [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1704327947675299), to see if it's a good fit for Wave 5.

**Comment by aswin-s** [comment] 2024-01-04 00:29
This issue is already fixed in [this PR](https://github.com/Expensify/App/pull/30955). Sadly the review is blocked for quite some time now.

**Comment by situchan** [comment] 2024-01-08 16:28
Seems like https://github.com/Expensify/App/pull/30955 has been stale for long time.
I am not sure we should hold this for that. This issue is never related to emoji.

**Comment by situchan** [comment] 2024-01-08 16:33
The current behavior is weird and I think we should fix this as urgency

https://github.com/Expensify/App/assets/108292595/607578ee-e049-4a83-b637-2dfc22e84b40

**Comment by situchan** [comment] 2024-01-08 16:39
@bernhardoj please do regression test on these issues:
- https://github.com/Expensify/App/issues/30867
- https://github.com/Expensify/App/issues/32644
- https://github.com/Expensify/App/issues/32652

**Comment by strepanier03** [comment] 2024-01-08 21:47
Raised [again](https://expensify.slack.com/archives/C066HJM2CAZ/p1704750432817259) to try to tie to another project for priority purposes. Will update as soon as possible.

**Comment by bernhardoj** [comment] 2024-01-09 07:37
@situchan I tested all 3 issues reproduction steps and the solution here won't cause that issue again.

**Comment by situchan** [comment] 2024-01-09 07:45
> Remove `replaceSelectionWithText` after focusing on the composer.

@bernhardoj can you find the exact PR which added that line?

**Comment by bernhardoj** [comment] 2024-01-09 08:50
It was added since the first time of the feature https://github.com/Expensify/App/pull/21583.

Probably we need it before because the `focus` is delayed inside InteractionManager.

I think it has the same root cause as https://github.com/Expensify/App/issues/31210 https://github.com/Expensify/App/pull/24482/files#r1429943408.

**Comment by situchan** [comment] 2024-01-09 09:46
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/33710#issuecomment-1871243110) looks good to me
🎀 👀 🎀 C+ reviewed

**Comment by quinthar** [comment] 2024-01-22 01:49
What's the update on this?  Who is doing what, and when will it be done?  It looks like we have a 2-week old undeployed fix?

**Comment by bernhardoj** [comment] 2024-01-22 06:54
Currently waiting for review.
cc: @situchan

**Comment by situchan** [comment] 2024-01-22 07:17
Provided feedback. Was testing and finding any possible regressions

**Comment by strepanier03** [comment] 2024-01-30 21:59
Pay date is tomorrow so I'll handle @bernhardoj's then. 

@situchan - Feel free to @ mention me when you post the checklist. 

Be back to this tomorrow.

**Comment by situchan** [comment] 2024-01-30 22:03
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/21583
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/21583/files#r1472023437
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

We can skip regression test as this was discovered by QA team

**Comment by strepanier03** [comment] 2024-01-31 20:28
Awesome, thank you @situchan! Handling payment now for everyone.

**Comment by strepanier03** [comment] 2024-01-31 21:07
Both @bernhardoj and @situchan have been paid. Closing this out as complete. Thanks everyone!

**Closed by strepanier03** 2024-01-31 21:07 UTC
Labels: External, Daily, Awaiting Payment, Bug
