### ISSUE TITLE
[HOLD for payment 2024-11-21] [$250] mWweb - Chat - From search page, tapping on image doesn't show image

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51161] opened 2024-10-21 08:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a chat
3. Pate the text in compose box - *test* ![demo image](https://picsum.photos/id/1067/200/300)_test_
4. Send the message
5. Navigate to LHN
6. Tap bottom search icon
7. From the dropdown, navigate to the chat
8. Tap on the image

## Expected Result:
From search page, tapping on image must show image.

## Actual Result:
From search page, tapping on image doesn't show image.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4de7338d-6f69-44b9-812f-cc20654af9a2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848845902924647302</li>
        <li>Upwork Job ID: 1848845902924647302</li>
        <li>Last Price Increase: 2024-10-29</li>
<li>Automatic offers: </li>
<ul>
<li>huult | Contributor | 104681846</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott / @stephanieelliott</details>

**Comment by IuliiaHerets** [comment] 2024-10-21 08:43
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment] 2024-10-21 09:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
From search page, tapping on image doesn't show image.

### What is the root cause of that problem?
We don't pass `reportID` to `attachmentContextValue`

https://github.com/Expensify/App/blob/44f5c5c9ad416bab2914f77e270319b97afaf156/src/components/SelectionList/ChatListItem.tsx#L43

Then we navigate to the attachment page with `reportID` as `-1`. As the result, the image doesn't show
https://github.com/Expensify/App/blob/44f5c5c9ad416bab2914f77e270319b97afaf156/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L80-L93

### What changes do you think we should make in order to solve the problem?
Pass the `reportID` to `attachmentContextValue`

```
const attachmentContextValue = {type: CONST.ATTACHMENT_TYPE.SEARCH, reportID: item?.reportID ?? '-1'};
```
https://github.com/Expensify/App/blob/44f5c5c9ad416bab2914f77e270319b97afaf156/src/components/SelectionList/ChatListItem.tsx#L43

### What alternative solutions did you explore? (Optional)

**Comment by huult** [comment] 2024-10-23 16:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

From search page, tapping on image doesn't show image

### What is the root cause of that problem?

This is the case of HTML rendering.

We open this image from Search, and in this case, we use `AttachmentView` to render it. However, since the image doesn't have a `file name`, the condition check at [L224](https://github.com/Expensify/App/blob/main/src/components/Attachments/AttachmentView/index.tsx#L223) fails, resulting in the default attachment being loaded, as described in this issue.

https://github.com/Expensify/App/blob/48d6f84747d6fd8a9023029e4b2a4bd735d7ccfc/src/components/Attachments/AttachmentView/index.tsx#L219-L223

The reason we don't have a `file name` in this case is that we did not send the `file name` to the `AttachmentModal` when we opened the image.
https://github.com/Expensify/App/blob/48d6f84747d6fd8a9023029e4b2a4bd735d7ccfc/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L101

We can load this image from the `Home` page because when opened from there, it uses [`AttachmentCarousel`](https://github.com/Expensify/App/blob/main/src/components/AttachmentModal.tsx#L547), which contains the [`extractAttachments`](https://github.com/Expensify/App/blob/main/src/components/Attachments/AttachmentCarousel/index.tsx#L81) function to retrieve file information, allowing it to load successfully.

https://github.com/Expensify/App/blob/48d6f84747d6fd8a9023029e4b2a4bd735d7ccfc/src/components/Attachments/AttachmentCarousel/extractAttachments.ts#L69-L72

### What changes do you think we should make in order to solve the problem?

To resolve this issue, AttachmentView needs to have a fileName, so we must send the fileName to this component. In this case, we will handle something like this:

1. We get file name from `htmlAttribs.src` and send to `AttachmentModal`
```diff
//.src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L60
+   let fileName = htmlAttribs[CONST.ATTACHMENT_ORIGINAL_FILENAME_ATTRIBUTE] || FileUtils.getFileName(`${isAttachmentOrReceipt ? attachmentSourceAttribute : htmlAttribs.src}`);
+    const fileInfo = FileUtils.splitExtensionFromFileName(fileName);
+    if (!fileInfo.fileExtension) {
+        fileName = `${fileInfo.fileName || 'image'}.jpg`;
+    }
//.src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L101
-       const route = ROUTES.ATTACHMENTS?.getRoute(reportID ?? '-1', type, source, accountID, isAttachmentOrReceipt);
+       const route = ROUTES.ATTACHMENTS?.getRoute(reportID ?? '-1', type, source, accountID, isAttachmentOrReceipt, fileName);
```

2. Update routes to recive new param
```diff
//.src/ROUTES.ts#L312
-       getRoute: (reportID: string, type: ValueOf<typeof CONST.ATTACHMENT_TYPE>, url: string, accountID?: number, isAuthTokenRequired?: boolean) => {
+       getRoute: (reportID: string, type: ValueOf<typeof CONST.ATTACHMENT_TYPE>, url: string, accountID?: number, isAuthTokenRequired?: boolean, fileName?: string) => {
        ...
-        return `attachment?source=${encodeURIComponent(url)}&type=${type}${reportParam}${accountParam}${authTokenParam}` as const;
+        const fileNameParam = fileName ? `&fileName=${fileName}` : '';
+        return `attachment?source=${encodeURIComponent(url)}&type=${type}${reportParam}${accountParam}${authTokenParam}${fileNameParam}` as const;
}       ,
```
3. Set `fileName` for `AttachmentModal`
```diff
//.src/pages/home/report/ReportAttachments.tsx#L37
+       const fileName = route.params.fileName;
        <AttachmentModal
            ...
+            originalFileName={fileName ?? ''}
        />
```

### What alternative solutions did you explore? (Optional)
We reuse logic to file info from `extractAttachments`

**Comment by sobitneupane** [comment] 2024-10-25 13:46
Thanks for the proposal @mkzie2 

Could you please add more depth to your RCA? It seems like you're mainly validating your solution in the RCA section.

If we pass `reportID` in `attachmentContextValue`, we will end up calling `AttachmentCarousel` instead of `AttachmentView` from `AttachmentModal`, which will display all attachments in the report not just the one clicked. I doubt that’s what we want. @shubham1206agra, it seems like you implemented this feature—was it a intentional decision not to pass reportID?

>  const attachmentContextValue = {type: CONST.ATTACHMENT_TYPE.SEARCH};

**Comment by huult** [comment] 2024-10-26 02:46
@sobitneupane , They can't update the `reportId` in `attachmentContextValue` because it calls `AttachmentCarousel` instead of `AttachmentView`. However, when opening an attachment in `Search`, only one attachment is opened, so we use `AttachmentView` in the current flow.

**Comment by huult** [comment] 2024-10-26 06:36
## [Proposal Updated](https://github.com/Expensify/App/issues/51161#issuecomment-2432845073)

- Add more description to the described RCA and solution.

@sobitneupane can you review my proposal? 
The short RCA: The condition check [`isFileName`](https://github.com/Expensify/App/blob/main/src/components/Attachments/AttachmentView/index.tsx#L226) returned `false` in `AttachmentView`, so the default image is displayed. The reason it returned `false` is that this source name doesn’t have an extension (link below), and we did not send a file name for `AttachmentModal`.

 > https://camo.githubusercontent.com/4848d0f965f332077b77a1a0488c3e66b4769032104f4de6890bae218b4add8d/68747470733a2f2f70696373756d2e70686f746f732f69642f313036372f3230302f333030

**Comment by stephanieelliott** [comment] 2024-10-30 08:46
Hey @sobitneupane any thoughts considering the context provided [here](https://github.com/Expensify/App/issues/51161#issuecomment-2439392498)?

**Comment by sobitneupane** [comment] 2024-10-31 04:25
Thanks for the proposal @huult 

[Proposal](https://github.com/Expensify/App/issues/51161#issuecomment-2432845073) from @huult looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by huult** [comment] 2024-11-01 09:55
Thank you all. I will create the PR within 24 hours

**Comment by stephanieelliott** [comment] 2024-11-05 08:41
Hey @sobitneupane the PR is waiting for your review, can you take a look?

**Comment by stephanieelliott** [comment] 2024-11-12 21:32
PR has been merged to main

**Comment by garrettmknight** [comment] 2024-11-13 14:58
@puneetlath / @sobitneupane looks like your fix might be causing a crash here: https://github.com/Expensify/App/issues/52475

**Comment by huult** [comment] 2024-11-13 15:04
@garrettmknight I think [this bug](https://github.com/Expensify/App/issues/52475) is not related to this ticket because it occurs due to inputting a link with **long text** in the composer. I tried to reproduce it, and it's working well.

**Comment by huult** [comment] 2024-11-22 16:25
Hi @puneetlath @stephanieelliott , Sorry, I still have not received the payment. Can you help me check? Maybe we have an issue with Upwork?

**Comment by stephanieelliott** [comment] 2024-11-26 05:27
Summarizing payment on this issue: 

 - Contributor: @huult $250 via Upwork  - PAID! 
 - Contributor+: @sobitneupane $250 via ND - please request!
 
 Upwork job is here: https://www.upwork.com/jobs/~021848845902924647302

**Closed by stephanieelliott** 2024-11-26 05:27 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-12 10:53
$250 approved for @sobitneupane
