### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250] Task – Green dot disappears with a delay in LHN when task is completed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44087] opened 2024-06-20 14:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4647657
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Log in as user A
3. Create a task without assignee in a room, where user B is a member
4. Log in as user B
5. Open task and assign it to yourself
6. Find task in LHN and verify green dot appears
7. Mark task as complete

## Expected Result:
Green dot disappears without delay in LHN when task is completed

## Actual Result:
Green dot disappears with a delay in LHN when task is completed

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/245616ae-9983-439e-b92e-be59c8d99df5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd4e242d6ffc4ea6</li>
        <li>Upwork Job ID: 1804185858023926931</li>
        <li>Last Price Increase: 2024-06-21</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102916582</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by m-natarajan** [comment] 2024-06-20 14:57
@zanyrenney FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-20 14:57
We think that this bug might be related to  #vip-vsb

**Comment by neonbhai** [comment] 2024-06-20 15:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task – Green dot disappears with a delay in LHN when task is completed

### What is the root cause of that problem?
We wait for the server's reponse when updating the `pendingAction` on task completed in `successData`:

https://github.com/Expensify/App/blob/f618a94c486b80aebab584c52288a7013ffad64a/src/libs/actions/Task.ts#L324-L333


### What changes do you think we should make in order to solve the problem?
We will move the `pendingAction` update to `optimisticData` here:

https://github.com/Expensify/App/blob/f618a94c486b80aebab584c52288a7013ffad64a/src/libs/actions/Task.ts#L307-L309

```jsx
[completedTaskReportAction.reportActionID]: { 
   pendingAction: null, 
}, 
```

**Comment by bernhardoj** [comment] 2024-06-21 04:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The green dot in LHN doesn't immediately disappear when completing a task.

### What is the root cause of that problem?
There are multiple conditions for the green dot to show, but in our case, we just focus on these 2 conditions.
https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/libs/ReportUtils.ts#L2316-L2322

`isUnreadWithMention` will be true if the `lastReadTime` is smaller than the `lastMentionedTime`. A new task report doesn't have a `lastReadTime`. When we assign a task to ourselves, a new message is shown
`assigned to {mention}`
which adds a mention to ourselves. So, the `lastMentionedTime` returns from the EditTaskAssignee API.

Because the `lastReadTime` is empty and defaults to an empty string, it's smaller than the `lastMentionedTime`. This makes the LHN title bold too (unread).
https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/libs/ReportUtils.ts#L2288-L2290

When we complete the task, `isWaitingForAssigneeToCompleteTask` returns false, but `isUnreadWithMention` still returns true. After a few seconds, the CompleteTask API returns the up-to-date `lastReadTime` which hides the green dot.
<img width="604" alt="image" src="https://github.com/Expensify/App/assets/50919443/9d95bdce-b0ad-4332-a85c-962a9b7a06b6">

### What changes do you think we should make in order to solve the problem?

I think we have 2 issues here. The LHN becomes unread when assigning a task to ourselves and the green dot and unread don't immediately disappear after completing a task.

To fix the second issue, we can optimistically set a `lastReadTime` when completing the task.
https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/libs/actions/Task.ts#L302-L315

```
lastReadTime: DateUtils.getDBTime(),
```
(and revert it back when it fails)

For the first issue, I think it requires both FE and BE fix. On FE, we can optimistically update the `lastReadTime` just like above when editing the assignee (or other fields). However, this isn't enough because the `lastMentionedTime` from `EditTaskAssignee` will still be bigger than the optimistic `lastReadTime`. So, I think the `EditTaskAssignee` API should return both `lastReadTime` and `lastMentionedTime` and have them at least equal.

**Comment by zanyrenney** [comment] 2024-06-21 16:13
Yes this looks VSB related, lets get this fixed!

**Comment by zanyrenney** [comment] 2024-06-25 17:51
@allroundexperts please review the proposal from @bernhardoj

**Comment by allroundexperts** [comment] 2024-06-28 07:17
@bernhardoj The first issue doesn't seem to be related to the issue in the OP. Does it make sense to handle them separately?

**Comment by marcochavezf** [comment] 2024-06-28 16:27
Thanks @allroundexperts, assigning @bernhardoj 🚀 

Meanwhile I will work on this:

> `EditTaskAssignee` API should return both lastReadTime and lastMentionedTime and have them at least equal.

**Comment by bernhardoj** [comment] 2024-06-29 03:25
PR is ready

cc: @allroundexperts

**Comment by mvtglobally** [comment] 2024-07-03 14:38
Issue not reproducible during KI retests. (First week)

**Comment by bernhardoj** [comment] 2024-07-10 10:51
I'll request in ND once payment is due.

**Comment by bernhardoj** [comment] 2024-07-16 02:09
The payment should be due [tomorrow](https://github.com/Expensify/App/issues/44087#issuecomment-2220183671) (07-17)

**Comment by bernhardoj** [comment] 2024-07-17 02:54
Requested in ND

**Comment by zanyrenney** [comment] 2024-07-19 10:05
**payment summary**

@allroundexperts requires payment through NewDot Manual Requests - please request $250 via ND
@bernhardoj requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102916582) (Contributor) - please request $250 via ND

**Comment by JmillsExpensify** [comment] 2024-07-19 12:32
$250 approved for @bernhardoj

**Comment by allroundexperts** [comment] 2024-07-28 22:04
## Checklist

1. I was not able to pinpoint any specific PR which caused this. The logic for green dot is dependent on many conditions and it is highly likely that multiple changes lead up to this.
2. N/A
3. N/A
4. A regression test would be helpful here.

### Regression test

1. Open the app and login as user A
2. Create a room and add a user B to it
3. Create a task in the room and do not add any assignee to it
4. Login as user B
5. Open the task that was created in step 3 and assign it to yourself
6. Find task in LHN and verify green dot appears
7. Mark task as complete

Verify that the green dot disappears without delay in LHN when task is completed

Do we 👍 or 👎 ?

**Comment by JmillsExpensify** [comment] 2024-08-21 11:08
Opening this back up for the regression test.

**Comment by zanyrenney** [comment] 2024-08-22 13:21
My b, thanks @JmillsExpensify

**Closed by zanyrenney** 2024-08-22 13:21 UTC
Labels: External, Daily, Awaiting Payment, Bug
