### ISSUE TITLE
[$500] Red dot on Avatar and Workspace doesn't also show in RHP/settings

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32418] opened 2023-12-03 16:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction ( not able to trigger red dot)
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701294340182499

## Action Performed:
1. Notice red dot next to avatar
2. Click Avatar
3. Observe red dot next to `Workspaces` and click it
4. Observe red dot next to `Midtown Community` Workspace and click it.

## Expected Result: 
To see a red dot next to a menu item in the Workspace settings and to be able to remove the red dot.

## Actual Result: 
No red dot show, no idea how to get ride of the red dot.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/30d4f732-8fe9-4b38-bed6-10966da4b60d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee73d0b5375e2d9d</li>
        <li>Upwork Job ID: 1732472662864601088</li>
        <li>Last Price Increase: 2023-12-06</li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-12-06 18:55
I think this is dupe of #32513

**Comment by mallenexpensify** [comment] 2023-12-09 01:38
I'll take this one @sakluger , put on hold pending the below, which I reopened. 
https://github.com/Expensify/App/issues/32513#issuecomment-1848075022

**Comment by getusha** [comment] 2023-12-18 12:40
HELD for https://github.com/Expensify/App/issues/32513

**Comment by mallenexpensify** [comment] 2024-01-03 02:01
Not seeing the red dot anymore and can't reproduce so I'm closing.  Unsure if #32513 fixed it or not ¯\_(ツ)_/¯

**Closed by mallenexpensify** 2024-01-03 02:01 UTC
Labels: External, Weekly, Overdue, Bug
