### ISSUE TITLE
[$250] "Default" badge in Settings > Wallet > Bank Accounts does not use bold font

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#36696] opened 2024-02-16 13:49 UTC
It looks like when our badge component was updated, the badge is not using a bold font. This badge can be seen in Settings > Wallet > Bank Accounts

![image](https://github.com/Expensify/App/assets/2319350/e62df43d-221e-421c-8db9-06aebc2e3d71)

We also need to update the badge in the Wallet for from Settings:
![CleanShot 2024-02-16 at 08 51 06@2x](https://github.com/Expensify/App/assets/2319350/22d452a7-4460-498a-9737-29e8e88ba5d4)

This badge component should always use bold weight font. This is what the badge component looks like in [Figma](https://www.figma.com/file/qQIIaxVUdtggrh8eg8bI5B/Brand-Guidelines-%26-Product-UI?type=design&node-id=1%3A2&mode=design&t=coSPLhve2rwYBHM3-1):
![CleanShot 2024-02-16 at 08 49 22@2x](https://github.com/Expensify/App/assets/2319350/1722eba7-4a64-4660-b42a-5b5caf67cfe3)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165e6a9159ce348b3</li>
        <li>Upwork Job ID: 1758494072926507008</li>
        <li>Last Price Increase: 2024-02-16</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by shawnborton** [comment] 2024-02-16 13:52
cc @SzymczakJ  for assignment

**Comment by SzymczakJ** [comment] 2024-02-16 14:00
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by godofoutcasts94** [comment] 2024-02-16 14:11
Dibs

**Comment by shawnborton** [comment] 2024-02-16 14:18
@SzymczakJ when you work on this, can we try to make this a pretty DRY badge component so that it's reusable elsewhere in the future?

**Comment by shahinyan11** [comment] 2024-02-16 14:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Default" badge in Settings > Wallet > Bank Accounts does not use bold font
### What is the root cause of that problem?
Missing
### What changes do you think we should make in order to solve the problem?
Add bold style [here](https://github.com/Expensify/App/blob/28a1ccc40ad6345338de1951c02146304fb30cd5/src/components/Badge.tsx#L57C17-L57C72)

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-02-16 14:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Default" badge in Settings > Wallet > Bank Accounts does not use bold font
### What is the root cause of that problem?
A small font size is used for the `Badge` text.
### What changes do you think we should make in order to solve the problem?
Change the [variables.fontSizeSmall](https://github.com/Expensify/App/blob/28a1ccc40ad6345338de1951c02146304fb30cd5/src/styles/index.ts#L834C23-L834C46)  to  `variable.fontSizeLabel`

### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment] 2024-02-16 14:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Default" badge in Settings > Wallet > Bank Accounts does not use bold font

### What is the root cause of that problem?
We had add a new style flow to this badge https://github.com/Expensify/App/blob/28a1ccc40ad6345338de1951c02146304fb30cd5/src/styles/index.ts#L825-L830 in this commit: https://github.com/Expensify/App/commit/ce4c6008c6b1faaeb89e1e82ddfd57e78a10bc00 but we miss the `fontWeight`

### What changes do you think we should make in order to solve the problem?
We must add `fontWeight: FontUtils.fontWeight.bold,` to the [`badgeBordered style`](https://github.com/Expensify/App/blob/28a1ccc40ad6345338de1951c02146304fb30cd5/src/styles/index.ts#L825)
### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-02-16 14:29
Proposal
Please re-state the problem that we are trying to solve in this issue.
"Default" badge in Settings > Wallet > Bank Accounts does not use bold font

What is the root cause of that problem?
Missing style

What changes do you think we should make in order to solve the problem?
Add fontWeight: 'bold' [here](https://github.com/Expensify/App/blob/28a1ccc40ad6345338de1951c02146304fb30cd5/src/styles/index.ts#L832C6-L837C10)

What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-02-16 14:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Default" badge in Settings > Wallet > Bank Accounts does not use bold font
### What is the root cause of that problem?
Missing style
### What changes do you think we should make in order to solve the problem?
Add `fontWeight: 'bold'` [here](https://github.com/Expensify/App/blob/28a1ccc40ad6345338de1951c02146304fb30cd5/src/styles/index.ts#L832C6-L837C10)

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2024-02-16 14:50
Not open to proposals, handled by agency who worked on this before

**Comment by filip-solecki** [comment] 2024-02-19 10:35
Hi! I am Filip from SWM and I will take this one since @SzymczakJ is ooo this week

**Comment by JmillsExpensify** [comment] 2024-03-13 18:03
Payment summary: $500 to @getusha for PR review

**Comment by JmillsExpensify** [comment] 2024-03-13 18:12
@twisterdotcom I went ahead and paid C+ based on a Slack thread. Keeping this one open for you though.

**Comment by mountiny** [comment] 2024-03-15 13:11
Getusha was the only one to pay here so we can close this one, no specific regression test required for this

**Closed by mountiny** 2024-03-15 13:11 UTC
Labels: Reviewing, External, Monthly, Bug
