### ISSUE TITLE
[$1000] iOS/Android - Create A New Room - The welcome information is hidden when selecting an Emoji

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14085] opened 2023-01-06 22:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with the Expensify account
3. Tap on FAB button -> New Room
4. Enter room's name -> Create New Room
5. Open the Emoji selector
6. The welcome information is not visible

## Expected Result:
The welcome information should still show (the same as when you start typing a new message)

## Actual Result:
The welcome information is hidden when opening the Emoji selector

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / native
- [ ] Android / native

**Version Number:** 1.2.49.0 (iOS) / 1.2.50.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211107988-be72525c-6d25-490e-899f-5326020dca14.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a702234c48d75e9a</li>
        <li>Upwork Job ID: 1612253186229886976</li>
        <li>Last Price Increase: 2023-01-09</li>
    </ul>
</details>

**Comment by mvtglobally** [comment] 2023-01-06 22:07
@jliexpensify this is specific to the special run https://github.com/Expensify/App/pull/13967

**Comment by jliexpensify** [comment] 2023-01-09 00:49
Hmm so I can see this behaviour on v1.2.50-13 as well.

If you create a new room and begin to type something, the welcome message still occurs, so I'd imagine we'd want to mirror this for emoji's.

**Comment by jliexpensify** [comment] 2023-01-09 01:03
@thesahindia and @cead22 - I'm pretty sure this can be worked on externally, but @mvtglobally mentions that it's related to https://github.com/Expensify/App/pull/13967. Should we wait on that PR?

**Comment by allroundexperts** [comment] 2023-01-09 03:41
## Proposal

Just like how `KeyboardAvoidingView` works, we can translate the `ReportActionView` whenever emoji modal opens.

The following needs to be changed:

```diff
diff --git a/src/components/EmojiPicker/EmojiPicker.js b/src/components/EmojiPicker/EmojiPicker.js
index be621f368..2771374e1 100644
--- a/src/components/EmojiPicker/EmojiPicker.js
+++ b/src/components/EmojiPicker/EmojiPicker.js
@@ -71,6 +71,9 @@ class EmojiPicker extends React.Component {
     }
 
     hideEmojiPicker() {
+        if (this.props.onHideEmojiPicker) {
+            this.props.onHideEmojiPicker();
+        }
         this.emojiPopoverAnchor = null;
         this.setState({isEmojiPickerVisible: false});
     }
@@ -83,6 +86,9 @@ class EmojiPicker extends React.Component {
      * @param {Element} emojiPopoverAnchor - Element to which Popover is anchored
      */
     showEmojiPicker(onModalHide, onEmojiSelected, emojiPopoverAnchor) {
+        if (this.props.onShowEmojiPicker) {
+            this.props.onShowEmojiPicker();
+        }
         this.onModalHide = onModalHide;
         this.onEmojiSelected = onEmojiSelected;
         this.emojiPopoverAnchor = emojiPopoverAnchor;
diff --git a/src/pages/home/report/ReportActionsList.js b/src/pages/home/report/ReportActionsList.js
index 36638f521..c195a954b 100644
--- a/src/pages/home/report/ReportActionsList.js
+++ b/src/pages/home/report/ReportActionsList.js
@@ -148,7 +148,7 @@ class ReportActionsList extends React.Component {
         const extraData = (!this.props.isDrawerOpen && this.props.isSmallScreenWidth) ? this.props.newMarkerReportActionID : undefined;
         const shouldShowReportRecipientLocalTime = ReportUtils.canShowReportRecipientLocalTime(this.props.personalDetails, this.props.report);
         return (
-            <Animated.View style={[StyleUtils.fade(this.state.fadeInAnimation), styles.flex1]}>
+            <Animated.View style={[StyleUtils.fade(this.state.fadeInAnimation), styles.flex1, ...this.props.styles]}>
                 <InvertedFlatList
                     accessibilityLabel="List of chat messages"
                     ref={ReportScrollManager.flatListRef}
diff --git a/src/pages/home/report/ReportActionsView.js b/src/pages/home/report/ReportActionsView.js
index 25aba06a5..c9dc5c7c0 100755
--- a/src/pages/home/report/ReportActionsView.js
+++ b/src/pages/home/report/ReportActionsView.js
@@ -71,6 +71,7 @@ class ReportActionsView extends React.Component {
         this.state = {
             isFloatingMessageCounterVisible: false,
             newMarkerReportActionID: ReportUtils.getNewMarkerReportActionID(this.props.report, this.sortedAndFilteredReportActions),
+            emojiTransform: false,
         };
 
         this.currentScrollOffset = 0;
@@ -92,7 +93,7 @@ class ReportActionsView extends React.Component {
             // If the app user becomes active and they have no unread actions we clear the new marker to sync their device
             // e.g. they could have read these messages on another device and only just become active here
             this.openReportIfNecessary();
-            this.setState({newMarkerReportActionID: ''});
+            this.setState(s => ({...s, newMarkerReportActionID: ''}));
         });
 
         if (this.getIsReportFullyVisible()) {
@@ -110,21 +111,21 @@ class ReportActionsView extends React.Component {
                 ReportScrollManager.scrollToBottom();
 
                 // If the current user sends a new message in the chat we clear the new marker since they have "read" the report
-                this.setState({newMarkerReportActionID: ''});
+                this.setState(s => ({...s, newMarkerReportActionID: ''}));
             } else if (this.getIsReportFullyVisible()) {
                 // We use the scroll position to determine whether the report should be marked as read and the new line indicator reset.
                 // If the user is scrolled up and no new line marker is set we will set it otherwise we will do nothing so the new marker
                 // stays in it's previous position.
                 if (this.currentScrollOffset === 0) {
                     Report.readNewestAction(this.props.report.reportID);
-                    this.setState({newMarkerReportActionID: ''});
+                    this.setState(s => ({...s, newMarkerReportActionID: ''}));
                 } else if (!isNewMarkerReportActionIDSet) {
-                    this.setState({newMarkerReportActionID: newActionID});
+                    this.setState(s => ({...s, newMarkerReportActionID: newActionID}));
                 }
             } else if (!isNewMarkerReportActionIDSet) {
                 // The report is not in view and we received a comment from another user while the new marker is not set
                 // so we will set the new marker now.
-                this.setState({newMarkerReportActionID: newActionID});
+                this.setState(s => ({...s, newMarkerReportActionID: newActionID}));
             }
         });
     }
@@ -152,6 +153,10 @@ class ReportActionsView extends React.Component {
             return true;
         }
 
+        if (nextState.emojiTransform !== this.state.emojiTransform) {
+            return true;
+        }
+
         if (nextState.isFloatingMessageCounterVisible !== this.state.isFloatingMessageCounterVisible) {
             return true;
         }
@@ -200,11 +205,12 @@ class ReportActionsView extends React.Component {
         const didScreenSizeIncrease = prevProps.isSmallScreenWidth && !this.props.isSmallScreenWidth;
         const didReportBecomeVisible = isReportFullyVisible && (didSidebarClose || didScreenSizeIncrease);
         if (didReportBecomeVisible) {
-            this.setState({
+            this.setState(s => ({
+                ...s,
                 newMarkerReportActionID: ReportUtils.isUnread(this.props.report)
                     ? ReportUtils.getNewMarkerReportActionID(this.props.report, this.sortedAndFilteredReportActions)
                     : '',
-            });
+            }));
             this.openReportIfNecessary();
         }
 
@@ -213,7 +219,7 @@ class ReportActionsView extends React.Component {
         const didSidebarOpen = !prevProps.isDrawerOpen && this.props.isDrawerOpen;
         const didUserNavigateToSidebarAfterReadingReport = didSidebarOpen && !ReportUtils.isUnread(this.props.report);
         if (didUserNavigateToSidebarAfterReadingReport) {
-            this.setState({newMarkerReportActionID: ''});
+            this.setState(s => ({...s, newMarkerReportActionID: ''}));
         }
 
         // Checks to see if a report comment has been manually "marked as unread". All other times when the lastReadTime
@@ -221,7 +227,7 @@ class ReportActionsView extends React.Component {
         const didManuallyMarkReportAsUnread = (prevProps.report.lastReadTime !== this.props.report.lastReadTime)
             && ReportUtils.isUnread(this.props.report);
         if (didManuallyMarkReportAsUnread) {
-            this.setState({newMarkerReportActionID: ReportUtils.getNewMarkerReportActionID(this.props.report, this.sortedAndFilteredReportActions)});
+            this.setState(s => ({...s, newMarkerReportActionID: ReportUtils.getNewMarkerReportActionID(this.props.report, this.sortedAndFilteredReportActions)}));
         }
 
         // Ensures subscription event succeeds when the report/workspace room is created optimistically.
@@ -309,11 +315,11 @@ class ReportActionsView extends React.Component {
      */
     toggleFloatingMessageCounter() {
         if (this.currentScrollOffset < -200 && !this.state.isFloatingMessageCounterVisible) {
-            this.setState({isFloatingMessageCounterVisible: true});
+            this.setState(s => ({...s, isFloatingMessageCounterVisible: true}));
         }
 
         if (this.currentScrollOffset > -200 && this.state.isFloatingMessageCounterVisible) {
-            this.setState({isFloatingMessageCounterVisible: false});
+            this.setState(s => ({...s, isFloatingMessageCounterVisible: false}));
         }
     }
 
@@ -352,7 +358,6 @@ class ReportActionsView extends React.Component {
         if (!_.size(this.props.reportActions)) {
             return null;
         }
-
         return (
             <>
                 {!this.props.isComposerFullSize && (
@@ -370,6 +375,7 @@ class ReportActionsView extends React.Component {
                             isLoadingMoreReportActions={this.props.report.isLoadingMoreReportActions}
                             loadMoreChats={this.loadMoreChats}
                             newMarkerReportActionID={this.state.newMarkerReportActionID}
+                            styles={[{transform: [{translateY: this.state.emojiTransform ? -250 : 0}]}]}
                         />
                         <PopoverReportActionContextMenu
                             ref={ReportActionContextMenu.contextMenuRef}
@@ -378,7 +384,11 @@ class ReportActionsView extends React.Component {
                         />
                     </>
                 )}
-                <EmojiPicker ref={EmojiPickerAction.emojiPickerRef} />
+                <EmojiPicker
+                    ref={EmojiPickerAction.emojiPickerRef}
+                    onShowEmojiPicker={() => this.setState(s => ({...s, emojiTransform: true}))}
+                    onHideEmojiPicker={() => this.setState(s => ({...s, emojiTransform: false}))}
+                />
                 <CopySelectionHelper />
             </>
         );
```

### Result

https://user-images.githubusercontent.com/30054992/211237410-9b238141-a1e6-441f-8142-070264133104.mov

### Generic approach
We can also make this approach more generic by creating a context called `ModalAvoidingView`. Then whenever we need to move the content up, we can wrap that component inside the `ModalAvoidingView`. This will work similar to `KeyboardAvoidingView`.

**Comment by priyeshshah11** [comment] 2023-01-09 06:52
## Proposal

### Problem
This same problem exists for chats as well because the keyboard automatically closes when any modal is opened up thus the `KeyboardAvoidingView` moves the content back down to its original position (i.e. when keyboard is closed).

### Solution
Add padding to the main View when the emoji picker modal is opened to make it behave exactly like when the keyboard is opened which pushes the content up & is easily visible in both the chat & a room.

```diff
diff --git a/src/CONST.js b/src/CONST.js
index df6306afa..4dd75296d 100755
--- a/src/CONST.js
+++ b/src/CONST.js
@@ -503,6 +503,7 @@ const CONST = {
         WIDTH: 320,
         HEIGHT: 390,
     },
+    MOBILE_EMOJI_PICKER_HEIGHT: 360,
     NON_NATIVE_EMOJI_PICKER_LIST_HEIGHT: 288,
     EMOJI_PICKER_ITEM_HEIGHT: 32,
     EMOJI_PICKER_HEADER_HEIGHT: 32,

diff --git a/src/components/EmojiPicker/EmojiPicker.js b/src/components/EmojiPicker/EmojiPicker.js
index be621f368..8a098b2fa 100644
--- a/src/components/EmojiPicker/EmojiPicker.js
+++ b/src/components/EmojiPicker/EmojiPicker.js
@@ -4,6 +4,7 @@ import _ from 'underscore';
 import EmojiPickerMenu from './EmojiPickerMenu';
 import CONST from '../../CONST';
 import PopoverWithMeasuredContent from '../PopoverWithMeasuredContent';
+import { setEmojiPickerVisibility } from '../../libs/actions/Modal';
 
 class EmojiPicker extends React.Component {
     constructor(props) {
@@ -35,6 +36,9 @@ class EmojiPicker extends React.Component {
     }
 
     componentDidUpdate(prevProps, prevState) {
+        if (prevState.isEmojiPickerVisible !== this.state.isEmojiPickerVisible) {
+            setEmojiPickerVisibility(this.state.isEmojiPickerVisible);
+        }
         if (prevState.isEmojiPickerVisible === this.state.isEmojiPickerVisible || !this.state.isEmojiPickerVisible) {
             return;
         }

diff --git a/src/components/ScreenWrapper/index.js b/src/components/ScreenWrapper/index.js
index bed7167eb..3d9eb6d8e 100644
--- a/src/components/ScreenWrapper/index.js
+++ b/src/components/ScreenWrapper/index.js
@@ -1,4 +1,4 @@
-import {View} from 'react-native';
+import {Animated} from 'react-native';
 import React from 'react';
 import _ from 'underscore';
 import {withOnyx} from 'react-native-onyx';
@@ -24,6 +24,8 @@ class ScreenWrapper extends React.Component {
 
         this.state = {
             didScreenTransitionEnd: false,
+            paddingBottom: 0,
+            animatedPaddingBottom: new Animated.Value(0)
         };
     }
 
@@ -52,6 +54,7 @@ class ScreenWrapper extends React.Component {
      */
     shouldComponentUpdate(nextProps, nextState) {
         return !_.isEqual(this.state, nextState)
+            || !_.isEqual(this.props.modal.isEmojiPickerVisible, nextProps.modal.isEmojiPickerVisible)
             || !_.isEqual(_.omit(this.props, 'modal'), _.omit(nextProps, 'modal'));
     }
 
@@ -64,29 +67,47 @@ class ScreenWrapper extends React.Component {
         }
     }
 
+    componentDidUpdate(prevProps) {
+        if (prevProps.modal.isEmojiPickerVisible !== this.props.modal.isEmojiPickerVisible) {
+            Animated.timing(this.state.animatedPaddingBottom, {
+                toValue: this.props.modal.isEmojiPickerVisible
+                    ? CONST.MOBILE_EMOJI_PICKER_HEIGHT
+                    // We always need the safe area padding bottom if we're showing the offline indicator since it is bottom-docked.
+                    : this.props.includeSafeAreaPaddingBottom || this.props.network.isOffline ? this.state.paddingBottom: 0,
+                duration: 500,
+                useNativeDriver: false,
+              }).start();
+        }
+    };
+
     render() {
         return (
             <SafeAreaConsumer>
                 {({
                     insets, paddingTop, paddingBottom, safeAreaPaddingBottomStyle,
                 }) => {
+                    if (paddingBottom !== this.state.paddingBottom) {
+                        const updatePaddingBottom = paddingBottom;
+                            paddingBottom: updatePaddingBottom,
+                            animatedPaddingBottom: new Animated.Value(updatePaddingBottom)
+                        });
+                    }
                     const paddingStyle = {};
 
                     if (this.props.includePaddingTop) {
                         paddingStyle.paddingTop = paddingTop;
                     }
 
-                    // We always need the safe area padding bottom if we're showing the offline indicator since it is bottom-docked.
-                    if (this.props.includeSafeAreaPaddingBottom || this.props.network.isOffline) {
-                        paddingStyle.paddingBottom = paddingBottom;
-                    }
-
                     return (
-                        <View
+                        <Animated.View
                             style={[
                                 ...this.props.style,
                                 styles.flex1,
                                 paddingStyle,
+                                this.props.isSmallScreenWidth && {
+                                    paddingBottom: this.state.animatedPaddingBottom
+                                },
                             ]}
                         >
                             <KeyboardAvoidingView style={[styles.w100, styles.h100]} behavior={this.props.keyboardAvoidingViewBehavior}>
@@ -104,7 +125,7 @@ class ScreenWrapper extends React.Component {
                                     <OfflineIndicator />
                                 )}
                             </KeyboardAvoidingView>
-                        </View>
+                        </Animated.View>
                     );
                 }}
             </SafeAreaConsumer>

diff --git a/src/libs/actions/Modal.js b/src/libs/actions/Modal.js
index 37e54093d..0fda705f2 100644
--- a/src/libs/actions/Modal.js
+++ b/src/libs/actions/Modal.js
@@ -10,6 +10,15 @@ function setModalVisibility(isVisible) {
     Onyx.merge(ONYXKEYS.MODAL, {isVisible});
 }
 
+/**
+ * Allows other parts of the app to know when the emoji picker has been opened or closed
+ *
+ * @param {Boolean} isEmojiPickerVisible
+ */
+function setEmojiPickerVisibility(isEmojiPickerVisible) {
+    Onyx.merge(ONYXKEYS.MODAL, {isEmojiPickerVisible});
+}
+
 /**
  * Allows other parts of app to know that an alert modal is about to open.
  * This will trigger as soon as a modal is opened but not yet visible while animation is running.
@@ -23,4 +32,5 @@ function willAlertModalBecomeVisible(isVisible) {
 export {
     setModalVisibility,
     willAlertModalBecomeVisible,
+    setEmojiPickerVisibility,
 };
```

**Comment by thesahindia** [comment] 2023-01-09 07:09
> @mvtglobally mentions that it's related to https://github.com/Expensify/App/pull/13967. Should we wait on that PR?

@jliexpensify, I don't think it's related to #13967.

cc @mvtglobally for thoughts

**Comment by jliexpensify** [comment] 2023-01-09 22:44
@thesahindia cool, thanks for clarifying! I'm not an engineer, so I was wondering what this phrase meant: "this is specific to the special run [PR]"

**Comment by thesahindia** [comment] 2023-01-09 23:25
> I was wondering what this phrase meant: "this is specific to the special run [PR]"

I am also confused about the comment. Should we wait for @mvtglobally's reply ?

**Comment by twisterdotcom** [comment] 2023-01-10 23:39
@jliexpensify I'm confused why I'm assigned to this? You added the `External Label` but that shouldn't add _another_ BugZero team member should it?

**Comment by jliexpensify** [comment] 2023-01-10 23:59
@twisterdotcom hmm very odd. I don't think it should - since I'm also a member of the BugZero team.

**Comment by priyeshshah11** [comment] 2023-01-11 12:01
> @thesahindia and @cead22 - I'm pretty sure this can be worked on externally, but @mvtglobally mentions that it's related to #13967. Should we wait on that PR?
@thesahindia @jliexpensify The above mentioned PR has now been merged & seems unrelated, is it ok to proceed now?

**Comment by thesahindia** [comment] 2023-01-11 13:39
I just wanna make sure that it's not getting fixed somewhere else, the linked PR wasn't related to this. It's possible that @mvtglobally linked the wrong PR.

@mvtglobally, could you please help us understand this [comment](https://github.com/Expensify/App/issues/14085#issuecomment-1374190355)?

**Comment by jliexpensify** [comment] 2023-01-12 21:50
Bump @mvtglobally - I think your comment is blocking potential proposals. Can you please update us?

**Comment by mvtglobally** [comment] 2023-01-12 21:53
@jliexpensify 
Are you guys able to repro this in Staging? When this issue was originally reported, we use a special build which was NOT released to main staging branch.

**Comment by jliexpensify** [comment] 2023-01-12 22:14
@mvtglobally I could reproduce the behaviour on v1.2.50-13 on my Android phone. I now have v. 52-4 and am seeing the same behaviour.

On the web app (staging v1.2.53-0), I'm not seeing this behaviour - so it seems to be related to the mobile apps only.

@thesahindia is this what you're also seeing?

**Comment by jliexpensify** [comment] 2023-01-12 22:15
@mvtglobally - I'm not an engineer so I'm not aware of this information:

> When this issue was originally reported, we use a special build which was NOT released to main staging branch.

I think it would have been clear to provide this additional context initially, as both @thesahindia and myself didn't know what you meant by the phrase "special run".

**Comment by mvtglobally** [comment] 2023-01-12 22:28
@jliexpensify noted! This was the first time ever we got this request, so ourselves didn't know how best to proceed. 
We have a plan for future, so such misunderstanding doesn't happen again.

**Comment by priyeshshah11** [comment] 2023-01-13 17:12
@thesahindia any feedback on the [proposal here](https://github.com/Expensify/App/issues/14085#issuecomment-1375175553) ?

**Comment by thesahindia** [comment] 2023-01-14 17:23
We will soon be adding search input for native so the proposal should work fine in that case too. 

@jliexpensify, I think this is not actually a bug. I just checked the slack on mobile and it has the same behaviour.

**Comment by priyeshshah11** [comment] 2023-01-14 17:54
> We will soon be adding search input at emoji picker for native so the proposal should work fine in that case too.

@thesahindia I disagree that it needs to be handled by this issue/proposal as that feature doesn't even exist yet & we as contributors don't have any info on that feature so I don't feel it is reasonable to expect someone to handle/fix something that doesn't even exist yet. I believe it should be handled whenever that feature is built/enabled.

> I think this is not actually a bug. I just checked the slack app on mobile and it has the same behaviour.

Which platform did you check that on? as I cannot see the same behaviour on iOS Slack & not even on Whatsapp, Telegram, LinkedIn or Messenger. 

The message in the screenshot below is the last message in the chat.
![IMG_5612](https://user-images.githubusercontent.com/38547776/212487708-7c9a628f-7470-4065-8cfc-0e039ee00bbb.PNG)

@thesahindia @jliexpensify It would be good to include all the related information in the issue description before it is made External? Also can issues be discussed thoroughly internally first to decide the expected behaviour before getting externals involved? As significant time goes in finding solutions & making proposals (& obviously reviewing it too) and it is disappointing to later find out that all that effort's gone to waste 🙂

**Comment by jliexpensify** [comment] 2023-01-15 22:11
> I think this is not actually a bug. I just checked the slack app on mobile and it has the same behaviour.

@thesahindia this is what I see on Slack (Android, v. 23.01.20-90012094-12251):

![Screenshot_20230116-084533](https://user-images.githubusercontent.com/30815269/212568923-7ee4934e-ad2f-4c57-b76e-dd6316cd206b.png)

Compared to the initial video, the behaviour seems different - i.e. when I click on a channel, then select an emoji, I still see the last post in the background. Same with Whatsapp - which makes me think that this isn't the behaviour we want, if we're trying to model ourselves after these apps.

> It would be good to include all the related information in the issue description before it is made External? Also can issues be discussed thoroughly internally first to decide the expected behaviour before getting externals involved? As significant time goes in finding solutions & making proposals (& obviously reviewing it too) and it is disappointing to later find out that all that effort's gone to waste

@priyeshshah11 I appreciate your feedback here and definitely understand your point of view, but for this issue, I think that the process was followed properly.

This issue was reported by a QA tester, and I was able to reproduce it using their instructions, so I determined this behaviour as a bug and the "External" label was added. That assigned a C+ and an internal Expensify engineer - who are here to help determine which proposal is best, or whether or not a proposal is actually required as it might be handled internally. Having the "External" label applied is not a guarantee that a proposal will be chosen: the MD states this. Also, keep in mind that I'm not an Engineer - my role is to reproduce the issue and pay contributors via Upworks: I also don't have an ETA on when certain features will be built/rolled out.

If there's any confusion around the expected behaviour, you're also welcome to ask in a GH comment (or in Slack) to gain further clarity - I see other contributors do this, and sometimes, it helps us (i.e. the Expensify team) realise that we've overlooked something or are missing something.

I think that it might be good to wait for @thesahindia and @cead22's thoughts here - I'd be curious to hear if we need to take this to the wider team: my take is that this seems to be a bug, given every other app shows the background when the emoji picker is selected.

**Comment by thesahindia** [comment] 2023-01-16 03:03
In the screenshot I am seeing that the last message is not completely visible only a few initial lines can be seen. If there's a big message in our app and we open the emoji picker the same happens in our app.

Video comparison with slack
Our app -
https://user-images.githubusercontent.com/83179295/212588362-bed4ee3b-a88d-466b-bb23-bd37f394fc6b.mp4

Slack -
https://user-images.githubusercontent.com/83179295/212588475-627abb9c-dfab-4efe-98f5-e67f817de18c.mp4

Now let's see the welcome message case. The welcome message gets hidden on opening the emoji picker. It happens because the emoji picker is just a modal, when it opens it covers what's behind it that's why we aren't seeing the welcome message or last message when there are messages. Because this is how modal works I don't think we should do anything. 

Slack has the same behaviour -
https://user-images.githubusercontent.com/83179295/212589694-c0c9e2ef-d6dc-4735-99bc-0151f1275e7b.mp4

Our app- 
https://user-images.githubusercontent.com/83179295/212589727-d54ccd51-162d-4902-af1b-045b4fd1a138.mp4

**Comment by jliexpensify** [comment] 2023-01-16 03:20
Interesting, thanks for the analysis/write-up @thesahindia - my mistake here is assuming that when using the emoji picker, the welcome message must follow the same UI (is that the best term?) as a standard message, but you've shown that's not the case.

My other (incorrect) assumption would be that we'd want any behaviour with the welcome message to mirror a "standard" chat, but since this isn't the case with Slack, then perhaps we don't need to make any changes here. I'm all for closing this out then, since this isn't a bug cc @cead22

**Comment by priyeshshah11** [comment] 2023-01-16 03:25
@thesahindia @jliexpensify Did you guys check my screenshot from [here](https://github.com/Expensify/App/issues/14085#issuecomment-1382870960). Slack's behaviour is different on iOS, you can see till the end of the last message, in that case I wouldn't be referring to slack as they have inconsistent behaviour on different platforms.

**Comment by jliexpensify** [comment] 2023-01-16 04:00
[Given the desire to have cross-platform consistency](https://expensify.slack.com/archives/C01GTK53T8Q/p1673449676309319?thread_ts=1673363183.637219&cid=C01GTK53T8Q), this issue would fall under that umbrella, right? It seems like we're trying to determine what the correct "behaviours" are?

So I wonder if we should all pause on this issue until we determine how we want the emoji picker to appear with the welcome message - e.g. should it mirror a "standard" message and should we surface the welcome message in the background, or should it remain as it currently is - and then aim to replicate that across every platform? Because right now, on the mobile app, the welcome message doesn't show but on desktop, it does show.

**Comment by priyeshshah11** [comment] 2023-01-16 04:15
@jliexpensify I agree, and exactly my point [here](https://github.com/Expensify/App/issues/14085#issuecomment-1382870960). I feel the expected behaviour should be discussed prior to opening the issue up to external contributors/proposals or maybe start a slack discussion to get everyone's opinion on it. That way everyone's time is valued.

I am not saying this just for this issue or only to you, my point is in general as this has happened several times before too in other issues thus just trying to help to improve the process, hope it's taken constructively 🙂

In regards to my opinion on the expected behaviour, I think it's better to slide things up when the emoji picker is opened up as right now you cannot see the text input/message where you're adding the emoji so you kinda have to blindly select the emoji.

**Comment by jliexpensify** [comment] 2023-01-16 05:26
Thanks for sticking with me - in hindsight, it was probably best to clarify what we want to see instead of making assumptions. I've posted [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1673846322777199) - feel free to jump in with your suggestion @priyeshshah11 (i.e. _"I think it's better to slide things up when the emoji picker is opened up"_)

> I feel the expected behaviour should be discussed prior to opening the issue up to external contributors/proposals or maybe start a slack discussion to get everyone's opinion on it.

My understanding is that before last week, we may have leant towards considering each platform separately/differently, [but now it's looking like we are striving for 100% consistency between each platform](https://expensify.slack.com/archives/C01GTK53T8Q/p1673545548192569?thread_ts=1673363183.637219&cid=C01GTK53T8Q), so I imagine this will become a greater consideration moving forward. 

As I'm not an engineer and I'm not sure of this information, [I'm keen to see which platform we might use as the basis](https://expensify.slack.com/archives/C01GTK53T8Q/p1673846512496919).

> my point is in general as this has happened several times before too in other issues thus just trying to help to improve the process, hope it's taken constructively

I would encourage you to bring up any concerns or questions, especially regarding issues, in the #expensify-open-source channel: this will get some greater visibility and might start a larger discussion.

**Comment by jliexpensify** [comment] 2023-01-16 21:26
After some discussion on Slack, [we've landed on this being a "preference" rather than a bug](https://expensify.slack.com/archives/C01GTK53T8Q/p1673870729182309?thread_ts=1673846322.777199&cid=C01GTK53T8Q), so we're closing it out. Thanks everyone for your input!

**Closed by jliexpensify** 2023-01-16 21:26 UTC
Labels: External, Daily, Help Wanted, Bug
