### ISSUE TITLE
 Account name not updating on assignee contact list after renaming

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22481] opened 2023-07-08 16:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open two new accounts
2. Open account A and click on FAB > Assign a task
3. Give the task a title and on the assign account B for the task
4. Click on Settings > account name and rename it as "account A"
5. Go to account B and rename it as "account B" as well
6. Go back to account A and open the task thread
7. Click on assignee and observe the contact list
8. Change the assignee to be account B
9. Observe the assignee and observe the LHN
## Expected Result: 
After account B has been renamed that should be updated on the assignee contact list as well.
## Actual Result: 
Renamed account B name is not updated on assignee contact list and email is being shown. When user clicks on account B's email to assign the task you can see first the email show up and then the renamed name appears on the assignee place. Also this does not update on LHN as it says that account B's email has assigned a task to you.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/868fcafa-5dd9-40e6-a92a-3d84c034373a

https://github.com/Expensify/App/assets/43996225/73f48776-ac31-472f-b8fd-54c8c09ea9d8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688369587056979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/Expensify/App/assets/43996225/73f48776-ac31-472f-b8fd-54c8c09ea9d8

**Comment by sakluger** [comment] 2023-07-10 21:24
I think this is a duplicate of https://github.com/Expensify/App/issues/22293. I asked in the Slack thread how they are different.

**Comment by sakluger** [comment] 2023-07-10 21:38
Confirmed that this is a dupe. Closing in favor of https://github.com/Expensify/App/issues/22293.

**Closed** 2023-07-11 16:08 UTC
Labels: Daily, Bug
