### ISSUE TITLE
Chat - HotKey Search not working if receipt image open in preview modal

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40769] opened 2024-04-23 10:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open App
2. Open any chat with a receipt with image attached
3. Click the image to open the preview modal
4. Press CTRL+K or CMD+K to open the search page

## Expected Result:
The preview modal is exited and the search modal is opened, the search text box is focused.

## Actual Result:
The preview mode is exited. Serach modal is only opened after navigating to a different conversation or to the conversation name in the header.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d600bea6-d770-4896-9d89-056001740815

https://github.com/Expensify/App/assets/115492554/f421a479-d4a9-481f-819e-3c923156e893

https://github.com/Expensify/App/assets/115492554/2e56bc7a-3aee-4a94-b91b-bc42af29a45a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-23 10:51
We think this issue might be related to the #collect project.

**Comment by bernhardoj** [comment] 2024-04-23 11:31
Dupe of https://github.com/Expensify/App/issues/37634

**Closed** 2024-04-24 17:03 UTC
Labels: Daily, Bug
