### ISSUE TITLE
[HOLD for payment 2024-03-25] [$500] Chat - Unable to re-join thread after leaving thread and returning with back button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37612] opened 2024-03-01 16:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+uo110@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause  - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to any 1:1 chat conversation
2. Join a thread by replying to any sent message
3. Click on 3 dots in threaded message and leave conversation(User should return to original DM conversation)
4. Select back button(User should return to threaded message just left)
5. Select "Join" in header

## Expected Result:
User should be able to join conversation and "join: in header disappears

## Actual Result:
Tapping "join" button does nothing but flashes button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dd68524b-6cf7-48e4-88aa-f9d35d264b10

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d212626b2be400f</li>
        <li>Upwork Job ID: 1763728742263644160</li>
        <li>Last Price Increase: 2024-03-03</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-01 16:04
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment] 2024-03-01 16:05
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mallenexpensify** [comment] 2024-03-03 23:50
@jjcoffee think this can be External? I _feel_ like it can be. 
I was able to reproduce.

**Comment by badeggg** [comment] 2024-03-04 05:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not able to join the thread when coming back from a chat report page.

### What is the root cause of that problem?
The root cause is that we navigate to a new chat page then leave the thread,
which is coming from https://github.com/Expensify/App/pull/37355.
And I don't think the related issues's expected behaviour is reasonable.

### What changes do you think we should make in order to solve the problem?
We should revert the code change:
![image](https://github.com/Expensify/App/assets/10908996/b4e0ea08-6963-4b22-a0a1-f3d1d2672057)


### What alternative solutions did you explore? (Optional)
N/A

**Comment by badeggg** [comment] 2024-03-04 06:35
Why I think issue's https://github.com/Expensify/App/issues/35810 expected behavior is not reasonable. To brief #35810's expected behavior,  navigate to a new chat report page when leave a thread, navigate back to the thread when click the back button. I believe the intuition is navigate back to the previous chat report page rather than go to a new chat report page. Plus it will cause a route stack 'loop':

https://github.com/Expensify/App/assets/10908996/8992a775-cbd8-4239-b08d-2bab95c38976

**Comment by jjcoffee** [comment] 2024-03-04 10:00
Hmm yeah I agree with @badeggg that the expected behaviour in https://github.com/Expensify/App/issues/35810 seems a little off. I'd expect that explicitly choosing to leave the thread indicates the user doesn't want to go back there, and the following back button interaction should take you back to LHN (on mobile). It seems like they settled on this behaviour after a long discussion [on Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1705948892215059) though, so I think we can consider it "expected" :smile: 

@dukenv0307's proposal almost makes sense to me, I'm just missing a bit more clarity on the RCA. Why does the `Join` button not work until the report is reopened via `OpenReport`? It seems like it _probably_ should work and that that's the thing to fix. The proposed solution seems a bit like a workaround, but I'm not 100%!

**Comment by jjcoffee** [comment] 2024-03-04 16:28
@dukenv0307 Thanks for the extra details! One last missing piece - what exactly does opening the thread with `OpenReport` do in terms of making them a participant? Does the server then start sending notifications (silently)?

Under your proposal it sounds like there would be no way to fully leave a thread since if you use the back button to navigate away from the parent chat, you _always_ go to the thread you left first which (via `OpenReport`) would re-add you as a participant regardless of your intentions. So the server suddenly ends up sending (even silently) notifications for all threads where a user has left, for all eternity!

This is an "interesting" side-effect of implementing https://github.com/Expensify/App/issues/35810, so I'm not 100% on whether or not to consider this a regression that the PR author there should fix.

**Comment by badeggg** [comment] 2024-03-05 01:11
Question, if the final decision is to consider this as a regression of https://github.com/Expensify/App/issues/35810, will I get the bounty of this issue? @jjcoffee

**Comment by jjcoffee** [comment] 2024-03-05 11:01
> I also don't think "you use the back button to navigate away from the parent chat" would be a very common user action after leaving the thread, if they do anything other than that then they will not be re-added as a participant of the thread.

@dukenv0307 I don't think there's any other way to get back to LHN on mobile other than using the back button (which would always take you to the thread you just left)?

> Question, if the final decision is to consider this as a regression of https://github.com/Expensify/App/issues/35810, will I get the bounty of this issue?

@badeggg We usually don't reward bounties for pointing out regressions. Bounties only really apply where a proposal was selected to fix an issue and a PR raised + merged.

**Comment by badeggg** [comment] 2024-03-05 11:21
ok

**Comment by jjcoffee** [comment] 2024-03-05 14:23
Thanks for the back and forth @dukenv0307! I'm clarifying this [on Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1709647830524219?thread_ts=1705948892.215059&cid=C049HHMV9SM).

**Comment by mallenexpensify** [comment] 2024-03-05 23:26
> Question, if the final decision is to consider this as a regression of https://github.com/Expensify/App/issues/35810, will I get the bounty of this issue? @jjcoffee

@badeggg , good question!  Let's keep moving this issue forward to get it fixed then discuss after the PR's been merged for 7 days.

**Comment by jjcoffee** [comment] 2024-03-06 09:50
Looks like my concern with calling `OpenReport` on opening the thread isn't shared by others on Slack so we're good to go with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/37612#issuecomment-1975660450).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by mallenexpensify** [comment] 2024-03-07 15:52
Added to #vip-vsb, will hire in Upwork soon if automation doesn't magically start working.  @MariaHCD , can you review the recommended proposal above?  Thx

**Comment by mallenexpensify** [comment] 2024-03-10 21:54
@dukenv0307 @jjcoffee , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01932d25804c11bb6a

**Comment by jjcoffee** [comment] 2024-03-25 09:56
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37355
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37355#issuecomment-2017615153
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - just needed extra testing**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Navigate to any 1:1 chat conversation
2. Start a thread by replying to any message
3. Click on 3 dots in threaded message and leave conversation
4. Tap back button to navigate back to the thread
5. Tap "Join" in the header
6. Verify that the button disappears to indicate you have rejoined the thread successfully

Do we agree 👍 or 👎

**Comment by mallenexpensify** [comment] 2024-03-26 20:59
Contributor: @dukenv0307 paid $500 via Upwork
Contributor+: @jjcoffee paid $500 via Upwork

TR GH https://github.com/Expensify/Expensify/issues/382664

Thanks!

**Closed by mallenexpensify** 2024-03-26 20:59 UTC
Labels: External, Weekly, Awaiting Payment, Bug
