### ISSUE TITLE
[$500] After clicking `Add attachment` the keyboard toggles back for a split second

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10931] opened 2022-09-09 18:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Open any conversation
4. Tap on the compose box to make sure the keyboard is open
5. Click the `+` button.
6. Click `Add attachment`

## Expected Result:
Transition is smooth when clicking the Add Attachment button and doesn't toggle back.

## Actual Result:
After clicking `Add attachment` the keyboard toggles back for a split second

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Mobile Web/Chrome (Android)

**Version Number:** 1.1.99.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/189416600-4d187b70-5881-48e9-9e24-73d9c1b3ae3b.mp4

https://user-images.githubusercontent.com/93399543/189416602-8512c58f-c0a6-4261-8117-fc8eb0881194.mp4

**Upwork URL:** https://www.upwork.com/jobs/~01c3f1b04035ef88cf

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PauloGasparSv** [comment] 2022-09-12 18:35
It looks like a problem when the virtual keyboard is opened because it toggles back for a split second right?
Adding the External label for this.

**Comment by trjExpensify** [comment] 2022-09-13 17:45
@PauloGasparSv - marking the issue as `external` by design adds the `Daily` label. 

@kbecciv - The issue title says `iOS` but the `Platforms` section has all platforms listed. Can you confirm which platforms are impacted, please? Is it limited to iOS (incl. mobile web) or Android as well? 

>Transition is not smooth when clicking the Add Attachment button.

This description is a bit ambiguous to me. When reproducing this, I think I would more so describe it as a flicker. I agree with Paulo that we could make this clear by updating it to: 

>After clicking `Add attachment` the keyboard toggles back to the create menu for a split second

Thoughts on that?

**Comment by trjExpensify** [comment] 2022-09-13 18:23
Cool, I'll update that in the OP issue and title, then wait on @kbecciv to confirm the platforms before we proceed.

**Comment by kbecciv** [comment] 2022-09-14 14:15
@trjExpensify Checking with team, update here shortly.

**Comment by kbecciv** [comment] 2022-09-14 15:34
@trjExpensify Updated the impacted platforms. 
Adding mWeb/Chrome behavior as well

https://user-images.githubusercontent.com/93399543/190198758-05a11415-a20e-40e6-91b6-71dcc30fd6d5.mp4

**Comment by trjExpensify** [comment] 2022-09-14 18:17
Sweet! So just to confirm, we also need to add `Android` to the platform list right?

**Comment by kbecciv** [comment] 2022-09-15 18:01
Issue is reproduceable iOS app and mWeb (Android/Chrome)

**Comment by trjExpensify** [comment] 2022-09-15 21:53
Cool, thanks. On upwork here: https://www.upwork.com/jobs/~01c3f1b04035ef88cf

**Comment by mananjadhav** [comment] 2022-09-24 19:45
Waiting for proposals.

**Comment by trjExpensify** [comment] 2022-09-29 11:16
Job doubled to $500 on Upwork here: https://www.upwork.com/jobs/~01c3f1b04035ef88cf

**Comment by trjExpensify** [comment] 2022-10-06 13:43
Did this get fixed elsewhere? 🤔 I'm unable to reproduce on iOS 

https://user-images.githubusercontent.com/16232057/194327643-b810846b-53eb-498c-9f82-d25e1adf20f9.MP4

@mananjadhav @kbecciv can either of you retest on Android before I bump the price on this one?

**Comment by mananjadhav** [comment] 2022-10-07 05:35
I don't have an Android for the time being to test this one. @kbecciv Can you please help here?

**Comment by Julesssss** [comment] 2022-10-07 13:27
Unable to reproduce on Android. The keyboard no longer pops up like the original screencasts show. `Pixel 6A, Android 13 `


https://user-images.githubusercontent.com/10736861/194564695-3d4083f9-2b32-424c-a1e0-ce62788689fd.mp4

**Comment by kbecciv** [comment] 2022-10-07 15:57
Checking with team, will update you shortly

**Comment by kbecciv** [comment] 2022-10-07 16:05
QA team is still reproduced this issue with latest build 1.2.12.2

https://user-images.githubusercontent.com/93399543/194598426-014e835d-974f-4876-92a5-8a608711342e.mp4

**Comment by trjExpensify** [comment] 2022-10-07 17:01
Hm, is that iOS or Android?

**Comment by kbecciv** [comment] 2022-10-07 17:50
This is IOS app

**Comment by Julesssss** [comment] 2022-10-10 09:50
@kbecciv could you please share the iOS version, and device?

**Comment by kbecciv** [comment] 2022-10-10 19:09
Sure, checking with team

**Comment by kbecciv** [comment] 2022-10-10 19:10
@Julesssss Tester was using iPhone XS Max/IOS 16

**Comment by Julesssss** [comment] 2022-10-11 09:53
Okay. I think we should leave the issue open, but not increase the bounty. Verifying a fix will be tricky, but first, let's see if anyone finds a solution.

**Comment by trjExpensify** [comment] 2022-10-11 11:10
I'm a bit wary of leaving this open if both Jules nor I can reproduce it on either Android or iOS. What conditions are we missing, are the steps in the OP accurate? If the tester can consistently reproduce this, we must be missing something.

**Comment by Julesssss** [comment] 2022-10-11 11:30
My assumption is that it's just an inconsistent bug. Perhaps it's occurring on a specific device, but it's also possible for it to require additional steps to reproduce that we're not aware of. 

I'm also happy to just ignore it and close the issue, but we should first confirm whether we can reproduce on this device: `iPhone XS Max/IOS 16`. If yes, it's probably a device-specific (or device with certain hardware) issue. Else, it probably requires some additional step that we're unaware of and closing might be the best use of our time. 

I asked [here](https://expensify.slack.com/archives/C03TQ48KC/p1665487709858489) for someone with this specific device to try to reproduce.

**Comment by trjExpensify** [comment] 2022-10-12 17:21
Gotcha. The iPhone XS Max came out in 2018, it's pretty old at this point (latest in that product line is the iPhone 14 Max). I'm not surprised we're getting crickets from asking in a few places in Slack. 

>Else, it probably requires some additional step that we're unaware of and closing might be the best use of our time.

@kbecciv can you confirm the steps, and can you confirm on a couple of other iOS devices. Thanks!

**Comment by trjExpensify** [comment] 2022-10-13 10:43
Haha! All good - agree with that next step.

**Comment by kbecciv** [comment] 2022-10-17 12:39
@Julesssss Two testers are unable to reproduce the issue using latest build 1.2.16.4

https://user-images.githubusercontent.com/93399543/196179165-1c6d1bb2-eb39-4b68-b340-5a6712d4cf8a.mp4


https://user-images.githubusercontent.com/93399543/196179172-55aed4f2-1fff-4873-a7d3-a94d70ea27a0.MP4

**Comment by Julesssss** [comment] 2022-10-17 12:46
Hi @kbecciv, can you please include the device model and OS version?

**Comment by kbecciv** [comment] 2022-10-17 12:57
@Julesssss Added above to each video.

**Comment by Julesssss** [comment] 2022-10-17 13:00
> Two testers are unable to reproduce the issue using latest build 1.2.16.4

Thank you, seems like we're okay to close this issue for the moment then 👍

**Closed by Julesssss** 2022-10-17 13:00 UTC
Labels: External, Engineering, Weekly, Help Wanted
