### ISSUE TITLE
[$2000] mWeb/Chrome - Chat - The transition between chats is not smooth

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11502] opened 2022-10-01 14:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Switch between chats

## Expected Result:
The transition between chats should be smooth

## Actual Result:
The transition between chats is not smooth

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193413941-0b40194b-6480-4792-847e-8bab421b7715.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment] 2022-10-04 18:02
This would be a super tricky one, but would be nice to clean up quality

**Comment by mallenexpensify** [comment] 2022-10-04 23:40
@ctkochan22 if you think this will be tricky and involve a bit of work, do you think we should start it at more than $250?  (ie. if we know no one is likely to pick it up unless it's higher price, what should we start it at so that we don't have to wait weeks for it to climb in price before we get proposals)

**Comment by RafehWaqar** [comment] 2022-10-05 11:41
Proposal 
Hello Expensify team. I can't think of the problem until I see the code but I think the problem is in your animation libraries. Here see a screenshot in which the inspect window of google chrome in which we can clearly see a issue in animation libraries.

   
![Screenshot (1)](https://user-images.githubusercontent.com/115071033/194052245-ec4eb60d-9c09-467d-aa55-053b06372526.png)

**Comment by thesahindia** [comment] 2022-10-06 17:30
>Hello Expensify team. I can't think of the problem until I see the code but I think the problem is in your animation libraries.
 
You can see the code in this repo, you can checkout the [Readme](https://github.com/Expensify/App#readme) to setup local dev environment.

You can also check the [closed issues](https://github.com/Expensify/App/labels/Awaiting%20Payment) to understand the process of proposing a solution.

**Comment by thesahindia** [comment] 2022-10-10 07:18
Not overdue. Waiting for proposals.

**Comment by mallenexpensify** [comment] 2022-10-10 21:36
Realized I forgot to create the Upwork job.  It's here https://www.upwork.com/jobs/~0129cad70a1c139828
Raised to price to $500 too

**Comment by Itsoxama** [comment] 2022-10-10 23:26
Hello i hope you are fine!
I am a reactjs expert for last five years and i have figure out the issue in your application. Actually You application has a npm module usenativedriver installed.And  it clearly show that this module is deprecated means this is removed completely and you can see it in console log thats why navigation not working properly. so what i do?
I will install and setup the alternative of this module successfully.
And there will be no issue in this app.
I have done that already in my previous app
Thank You

**Comment by Itsoxama** [comment] 2022-10-10 23:27
> Realized I forgot to create the Upwork job. It's here https://www.upwork.com/jobs/~0129cad70a1c139828 Raised to price to $500 too

Hello i hope you are fine!
I am a reactjs expert for last five years and i have figure out the issue in your application. Actually You application has a npm module usenativedriver installed.And  it clearly show that this module is deprecated means this is removed completely and you can see it in console log thats why navigation not working properly. so what i do?
I will install and setup the alternative of this module successfully.
And there will be no issue in this app
Thank You

**Comment by mallenexpensify** [comment] 2022-10-11 01:18
@Itsoxama , please review https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md for details on how to submit a proposal for a job.  Thanks

**Comment by mallenexpensify** [comment] 2022-10-13 14:50
Checkin' on summin.....

**Comment by thesahindia** [comment] 2022-10-17 07:42
> Not overdue. Waiting for proposals.

Same

**Comment by mallenexpensify** [comment] 2022-10-17 17:23
Bumped my 'checkin' on something' internally https://expensify.slack.com/archives/C01SKUP7QR0/p1665702218396519

**Comment by mallenexpensify** [comment] 2022-10-20 21:53
Putting on hold for a minute, I think we're wanting to create a tracking issue for animation related issues.

**Comment by mallenexpensify** [comment] 2022-10-31 16:46
Checking in #expensify-open-source 
https://expensify.slack.com/archives/C01GTK53T8Q/p1667234779011239?thread_ts=1666110816.923929&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment] 2022-10-31 16:52
Gonna take off hold, Jason mentioned 
> That’s at the RN/native layer

Doubled price to $1000 too
https://www.upwork.com/jobs/~0129cad70a1c139828

**Comment by mallenexpensify** [comment] 2022-11-09 02:23
Price Doubled to $2000
https://www.upwork.com/jobs/~0129cad70a1c139828

@johncschuster Reassigning as I'm heading OOO for a month

**Comment by mvtglobally** [comment] 2022-11-09 03:34
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment] 2022-11-10 19:42
Thanks for the heads up, @mallenexpensify! I'll keep this one going strong.

**Comment by thesahindia** [comment] 2022-11-14 08:17
Not overdue.

**Comment by ctkochan22** [comment] 2022-11-17 00:12
Not overdue

**Comment by marcaaron** [comment] 2022-11-17 23:21
I think the reproductions steps here are not complete or something or our recent improvements in performance have made this less of an issue. Mobile web chat switching on Android looks pretty smooth to me under normal circumstances. On an account with many chats it's not going to look 100% smooth because the rendering performance of the LHN goes down a bit at scale.

I also think that these animations will be much smoother once we kill the drawer navigator and reimplement react navigation.

**Comment by marcaaron** [comment] 2022-11-18 00:38
Gonna just close this one. Don't think it's going to be much of problem for us and will get even better once we reimplement react nav.

**Closed by marcaaron** 2022-11-18 00:38 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
