### ISSUE TITLE
[$500] Distance - Empty description row is grayed out in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30378] opened 2023-10-25 18:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Go to a workspace distance request details page that has empty description
3. Disconnect network

## Expected Result:
The description row is not grayed out

## Actual Result:
The description row is grayed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/7712be63-c67f-4910-8c60-65154cd4495e

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013403512294192b83</li>
        <li>Upwork Job ID: 1717254370039369728</li>
        <li>Last Price Increase: 2023-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27597930</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-10-25 20:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We are not clearing `pendingFields` alongside `pendingActions` when request is successful here:
https://github.com/Expensify/App/blob/83fcaaa324d72996620c096a6185377e05cb16c8/src/libs/actions/IOU.js#L256
### What changes do you think we should make in order to solve the problem?
We should add following code to clear all pending fields:
```javascript
pendingFields: {
                    comment: null,
                    amount: null,
                    created: null,
                    currency: null,
                    merchant: null,
                    billable: null,
                    category: null,
                    tag: null,
                },
```


### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2023-10-25 20:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
When creating a Distance request, we populate the existing transaction with the `pendingFields: comment` here:

https://github.com/Expensify/App/blob/01016dcaf4da744fe554cc839b47b5780f01c637/src/libs/actions/Transaction.ts#L61-L63

Later on, when placing the request, this existing action is merged with the optimistic one:

https://github.com/Expensify/App/blob/f6a9dde37803302b3b1a1dd2b5c5f720ab309f6d/src/libs/actions/IOU.js#L509-L520

This results with a created optimistic action with `pendingFields: { comment: 'add' }`.

However, when building the success Onyx data, we clear only the `pendingAction`, but not `pendingFields`:

https://github.com/Expensify/App/blob/f6a9dde37803302b3b1a1dd2b5c5f720ab309f6d/src/libs/actions/IOU.js#L253-L257

### What changes do you think we should make in order to solve the problem?
Along with clearing `pendingAction`, we should clear the `pendingFields` as well:

```js
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.TRANSACTION}${transaction.transactionID}`,
            value: {
                pendingAction: null,
                pendingFields: {
                    comment: null,
                    amount: null,
                    created: null,
                    currency: null,
                    merchant: null,
                    billable: null,
                    category: null,
                    tag: null,
                },
            },
        },
```

We do the same while editing the request:

https://github.com/Expensify/App/blob/f6a9dde37803302b3b1a1dd2b5c5f720ab309f6d/src/libs/actions/IOU.js#L1863-L1878

### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment] 2023-10-25 21:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In a distance money request details page that has empty description, when going offline, the "Description" field  is greyed-out.

### What is the root cause of that problem?

When creating a Distance request, we populate the existing transaction with the `pendingFields: comment` here:
https://github.com/Expensify/App/blob/01016dcaf4da744fe554cc839b47b5780f01c637/src/libs/actions/Transaction.ts#L61-L63

This results with a created optimistic action with `pendingFields: { comment: 'add' }`.

Consequently, when we render the `OfflineWithFeedback` component for the "Description" field, the `props.pendingAction` is assigned the value `add`.
https://github.com/Expensify/App/blob/9f5e5e60fa8ad2a27839c343e4d1daa1b7c9a073/src/components/ReportActionItem/MoneyRequestView.js#L192

This setup leads to a situation where, during the transition from an Online to an Offline state, the variable `isOfflinePendingAction` evaluates to `true`.
https://github.com/Expensify/App/blob/0e660626beae07c3b8f8778000983596e0e391ba/src/components/OfflineWithFeedback.js#L108

Making `needsOpacity` goes to `true`:
https://github.com/Expensify/App/blob/0e660626beae07c3b8f8778000983596e0e391ba/src/components/OfflineWithFeedback.js#L111
Greying-out our "Description" field.

### What changes do you think we should make in order to solve the problem?
To solve the issue, we can adjust the logic of the `isOfflinePendingAction` variable. This variable should only evaluate to `true` if the action is either `update` or `delete`, as these are the scenarios where the greyed-out description is necessary. This can be implemented with the following code adjustment:

```
const isOfflinePendingAction = isOffline && props.pendingAction && (props.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || props.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE);
```

This adjustment will ensure that the "Description" field does not appear greyed out when transitioning from an Online to an Offline state unless the action is an update or delete operation.

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-10-26 03:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Empty description row is grayed out in offline mode

### What is the root cause of that problem?
Let's see
https://github.com/Expensify/App/blob/05ae4c4d7b150b9bd88569a84eee7e3ab7f3e5fd/src/libs/actions/Transaction.ts#L61-L63

I am not sure why we add pendingField. Normally, pendingField and pendingAction only be added in optimisticaData (apply before sending API) and It is re-set in successData and FailureData
One more thing, let's see the transaction.comment field.
<img width="321" alt="Screenshot 2023-10-26 at 10 48 22" src="https://github.com/Expensify/App/assets/141406735/250ad64a-8bb4-4640-be81-59b7e309c3a5">

description field is transaction.comment.comment. But currently we are setting pendingField.comment to description field

Another thing, I see while investigating: When creating distance request, we reset pendingActions field in successData 
https://github.com/Expensify/App/blob/05ae4c4d7b150b9bd88569a84eee7e3ab7f3e5fd/src/libs/actions/IOU.js#L253-L257
But we don't do that in the failureData
https://github.com/Expensify/App/blob/05ae4c4d7b150b9bd88569a84eee7e3ab7f3e5fd/src/libs/actions/IOU.js#L326-L330

### What changes do you think we should make in order to solve the problem?
Firstly, When creating distance request, reset pendingActions field in failureData
In here
https://github.com/Expensify/App/blob/05ae4c4d7b150b9bd88569a84eee7e3ab7f3e5fd/src/libs/actions/IOU.js#L326-L330
add `pendingActions: null`

Secondly, I have 2 options
1. I suggest we should remove
https://github.com/Expensify/App/blob/05ae4c4d7b150b9bd88569a84eee7e3ab7f3e5fd/src/libs/actions/Transaction.ts#L61-L63
Because savewaypoint is not an API 
2. We can create a new pendingField called description to distinguish description field and comment field. 
### What alternative solutions did you explore? (Optional)

**Comment by ArekChr** [comment] 2023-10-26 11:09
It looks like solutions with setting `pendingFields` to null do not solve this problem at all. After setting offline mode, descriptions are still being greyed out.

**Comment by DylanDylann** [comment] 2023-10-26 11:25
@ArekChr could you help to check my proposal https://github.com/Expensify/App/issues/30378#issuecomment-1780378035

**Comment by alitoshmatov** [comment] 2023-10-26 11:59
@ArekChr Can you share a video, It is working for me
https://github.com/Expensify/App/assets/59907218/9468c861-41e1-4adc-be32-2e7ff8332d8b

**Comment by ArekChr** [comment] 2023-10-27 10:46
After pulling the latest changes, I confirm that your proposal fixes the problem. I checked both creating and viewing distance requests, and it works well for both. Let's go ahead with @alitoshmatov's [proposal](https://github.com/Expensify/App/issues/30378#issuecomment-1779971045) since he was the first to understand the root cause and provided a working solution.

**Comment by DylanDylann** [comment] 2023-10-27 10:53
@ArekChr Could you help to check my proposal https://github.com/Expensify/App/issues/30378#issuecomment-1780378035

**Comment by DylanDylann** [comment] 2023-10-27 10:54
@ArekChr From my investigating, I see the RCA of @alitoshmatov's proposal is incorrect. The fix seems a workaround

**Comment by ArekChr** [comment] 2023-10-27 10:55
> @ArekChr From my investigating, I see the RCA of @alitoshmatov's proposal is incorrect. The fix seems a workaround

@DylanDylann could you elaborate?

**Comment by DylanDylann** [comment] 2023-10-27 10:56
@ArekChr Could you check my proposal for more detail? I am happy to elaborate more If you have any curious

**Comment by DylanDylann** [comment] 2023-10-28 09:40
@jasperhuangg Sorry If boring you. But I tag you here because you were author of [this PR](https://github.com/Expensify/App/pull/26141) where you add 

https://github.com/Expensify/App/blob/05ae4c4d7b150b9bd88569a84eee7e3ab7f3e5fd/src/libs/actions/Transaction.ts#L61-L63

I am not sure why we add pendingField in saveWaypoint function (this function only merge data to ONYX, not send API). Normally, pendingField and pendingAction only be added in optimisticaData (apply before sending API) and It is re-set in successData and FailureData

**Comment by mallenexpensify** [comment] 2023-10-30 23:16
> Let's go ahead with @alitoshmatov's https://github.com/Expensify/App/issues/30378#issuecomment-1779971045 since he was the first to understand the root cause and provided a working solution.

@ArekChr did you want/mean to add `🎀 👀 🎀 C+ reviewed` ?

**Comment by ArekChr** [comment] 2023-10-31 11:14
> @ArekChr did you want/mean to add 🎀 👀 🎀 C+ reviewed ?

Yes, I had overlooked that. Thanks for the reminder. I've updated the comment. Just note I will be out of the office from tomorrow until Monday. Upon my return, I will make sure to do the review.

**Comment by DylanDylann** [comment] 2023-10-31 12:07
@ArekChr Could you help to check [my comment](https://github.com/Expensify/App/issues/30378#issuecomment-1783761703)? I think we need to clear the problem here. @alitoshmatov's proposal said that 

> We are not clearing pendingFields alongside pendingActions when request is successful here:

So why do we need to set pendingField for the description field in saveWaypoint function? It is so weird. We are having a misunderstanding between transaction.comment field and transaction.comment.comment (description field)

cc @cead22

**Comment by mallenexpensify** [comment] 2023-11-03 23:06
Bumped the price to get more 👀 and/or proposals here.

**Comment by paultsimura** [comment] 2023-11-04 09:36
@mallenexpensify this issue is already C+ approved, are you sure it needs a bounty adjustment?

**Comment by cead22** [comment] 2023-11-06 19:09
@ArekChr can you check out and respond to this comment please? https://github.com/Expensify/App/issues/30378#issuecomment-1787092816

**Comment by mallenexpensify** [comment] 2023-11-07 00:03
Thanks @paultsimura , I dropped it back down to $500 since we're currently waiting on final approval from the internal engineer.

**Comment by ArekChr** [comment] 2023-11-07 12:23
@DylanDylann, I agree that removing saveWaypoionts from pendingFields makes sense. However, we should seek clarification to ensure no regression issues are tied to this implementation. Upon reviewing your solution, I've noticed that the issue is now non-reproducible on the latest main branch.

https://github.com/Expensify/App/assets/24796318/4a9cf8db-882d-40a5-93d2-e98a94f21f29

**Comment by DylanDylann** [comment] 2023-11-08 03:46
@ArekChr I still can reproduce this bug on the latest main follow by these steps:
1. Create a new Distance Request
2. Go to the transaction report 
3. Go offline 

https://github.com/Expensify/App/assets/141406735/c2a02653-f4d7-4b74-9f1b-86ed36b9f405

**Comment by DylanDylann** [comment] 2023-11-08 04:01
@ArekChr 
 
>  I agree that removing saveWaypoionts from pendingFields makes sense. However, we should seek clarification to ensure no regression issues are tied to this implementation.

Let's see
https://github.com/Expensify/App/blob/05ae4c4d7b150b9bd88569a84eee7e3ab7f3e5fd/src/libs/actions/Transaction.ts#L61-L63
I think `pendingFields.comment` is added here intended to mark waypoint changes not description changes.
Note that:
1. waypoint field: transaction.comment
2. description field: transaction.comment.comment

<img width="424" alt="Screenshot 2023-11-08 at 10 59 51" src="https://github.com/Expensify/App/assets/141406735/849f764a-580c-45a6-a5e4-0e731da85bec">

But we only have 1 pendingField `comment` and use it for both waypoint and description

So that in my proposal, I have a suggestion to distinguish description pendingfield and waypoint pendingfield
> We can create a new pendingField called description to distinguish description field and comment field.

**Comment by ArekChr** [comment] 2023-11-08 10:26
I confirm that after reproducing with your steps, the issue still exists. 

@DylanDylann, I’ve reviewed your [proposal](https://github.com/Expensify/App/issues/30378#issuecomment-1780378035) and agree it makes more sense. You've noticed that we're not resetting the pending fields on failure, which is missing in the code. This could indeed cause issues, especially in offline mode.

As for your point about the confusion between `transaction.comment` and `transaction.comment.comment` is valid. We need to clear this up to avoid errors in the app.

I think your proposal is a good way to fix these issues. Let’s go with your changes.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by cead22** [comment] 2023-11-08 17:30
- @ArekChr @DylanDylann will your proposal also fix the disappearing receipt image from your video? 
- Is there a way to add an automated test to prevent this moving forward? 
- If not, would it be worth it to add a regression test for this if we don't have one already?
- This is probably unrelated, but why do the chats on the left hand nav shift when going offline?

**Comment by DylanDylann** [comment] 2023-11-09 06:40
> will your proposal also fix the disappearing receipt image from https://github.com/Expensify/App/issues/30378#issuecomment-1800965818?

> This is probably unrelated, but why do the chats on the left hand nav shift when going offline?

@cead22 on the latest main (today), I can't reproduce 2 bugs that you mentioned. 



https://github.com/Expensify/App/assets/141406735/5cc5914c-3cdf-4ef1-b432-aec300e1f62a


@ArekChr Please help to confirm

**Comment by ArekChr** [comment] 2023-11-09 09:40
> Is there a way to add an automated test to prevent this moving forward?

This is possible. We can use RNTL and mock `@react-native-community/netinfo` for this test purposes.

> If not, would it be worth it to add a regression test for this if we don't have one already?

It is worth adding a regression test.

**Comment by cead22** [comment] 2023-11-09 18:16
Thanks for the clarifications

**Comment by bondydaa** [comment] 2023-11-21 22:46
Turns out this wasn't a deploy blocker but please make sure we update the regression steps with applause so that we don't create reports like this in the future https://github.com/Expensify/App/issues/31639

**Comment by DylanDylann** [comment] 2024-01-02 06:08
@mallenexpensify The PR is deployed to production a long time ago. COuld you help to move forward with this issue?

**Comment by mallenexpensify** [comment] 2024-01-03 01:24
Contributor: @DylanDylann paid $500 via Upwork. 

> [The PR](https://github.com/Expensify/App/pull/31172#issuecomment-1821919916) was deployed to production a long time ago. COuld you help to move forward with this issue?

You mean... over a month?!? 😿 
Sorry about that, the `Reviewing` label makes issues not go overdue so they get missed.

**Closed by mallenexpensify** 2024-01-03 01:24 UTC
Labels: External, Daily, Bug
