### ISSUE TITLE
Leave thread option not working- thread is restored a few seconds after displaying "Hmm its not here, this page can not be found"  message.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21185] opened 2023-06-21 11:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat and send a message
2. Long press on the message and click on reply in thread
3. Send another message in the new opened chat thread
4. Click on the thread name header at the top
5. Click on leave thread
6. Upon clicking leave thread user will be redirected to concierge
7. Click the back button at the top of the screen in the concierge chat
8. Observe the "Hmm its not here..." message
9. Wait a few seconds and observe thee user is redirected back to the thread

## Expected Result:
Once a thread is left the user should not see and access the thread

## Actual Result:
The thread is restored after a few second and can be accessed by the user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d4f40c70-080f-4b4f-91f4-c8c4f97050d7

https://github.com/Expensify/App/assets/93399543/b7619516-3e11-4c9a-aa57-e471d1465a1d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @sofoniasN

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686725421997199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2023-06-21 11:55
Dupe of https://github.com/Expensify/App/issues/20908

**Closed** 2023-06-21 13:45 UTC
Labels: Daily, Bug
