### ISSUE TITLE
[$1000] Console error when open new chat from search

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13224] opened 2022-12-01 04:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Search for a user to start a new chat
2. Report screen will be opened
3. Notice there is a console error

## Expected Result: 
No console error

## Actual Result: 
Console error appears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**  v1.2.33-1
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/204966855-e347c5da-28cb-4424-b96e-fbab43525147.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @bernhardoj 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669725582535429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01794f82db6afc0bd4
- Upwork Job ID: 1599875300598030336

**Comment by hungvu193** [comment] 2022-12-01 05:56
Sometimes I also got this issue too, but I can't reproduce it everytime.
https://expensify.slack.com/archives/C049HHMV9SM/p1669172780151489

**Comment by Pujan92** [comment] 2022-12-01 06:40
**Proposal**

<img width="959" alt="Screenshot 2022-12-01 at 12 05 38 PM" src="https://user-images.githubusercontent.com/14358475/204982951-539aa005-cd7c-4efd-ab77-8a7b3da4ef3f.png">

Initially, for the new chat it seems reportActionID is not generating instantly which causes the issue as `undefined` returned from the keyExtractor. To resolve we can use `index` as a fallback.

https://github.com/Expensify/App/blob/820e876d5e4a8cbffe272220c1182c8942ed93cf/src/pages/home/report/ReportActionsList.js#L110-L112

```
keyExtractor(item, index) {
    return item.action.reportActionID || index;
}
```

**Comment by situchan** [comment] 2022-12-01 12:56
### **Proposal**

https://github.com/Expensify/App/blob/820e876d5e4a8cbffe272220c1182c8942ed93cf/src/pages/home/report/ReportActionsList.js#L110-L112
We don't suggest index as key in FlatList

**Solution:**
```
 keyExtractor(item) { 
     return item.action.reportActionID || item.action.created
 } 
```

**Comment by Pujan92** [comment] 2022-12-01 13:11
> We don't suggest index as key in FlatList

I think for the fallback index should not be the issue.

**Comment by arosiclair** [comment] 2022-12-01 20:59
I'm not able reproduce this in dev 

https://user-images.githubusercontent.com/6833644/205158079-542ed609-d19d-4517-947e-b709a2277208.MP4

**Comment by Pujan92** [comment] 2022-12-01 23:21
> I'm not able reproduce this in dev

Can you plz check on the web once

**Comment by arosiclair** [comment] 2022-12-05 21:15
Thanks I'm able to reproduce in web. Marking this external to get a C+ on this

**Comment by arosiclair** [comment] 2022-12-05 21:18
Let's try to determine the root cause of the issue @Pujan92 @situchan. Your proposals only work around the issue. Why is the `reportActionId` undefined? Let's try to fix that instead of changing how the key works

**Comment by akshayasalvi** [comment] 2022-12-05 22:02
**Proposal**

We're creating an optimistic report action when creating a new chat here.

https://github.com/Expensify/App/blob/6380fe842ed363e7a90f4f799f418c7857614608/src/libs/actions/Report.js#L547-L551

But upon checking `ReportUtils.buildOptimisticReportAction`, you'll see we're not setting `reportActionID`

https://github.com/Expensify/App/blob/6380fe842ed363e7a90f4f799f418c7857614608/src/libs/ReportUtils.js#L639-L671

Hence, my proposal is to set a `reportActionID: NumberUtils.rand64()` in the above code block.

I can change the `NumberUtils.rand64` to whatever logic is required, as I don't know how that is created.

**Comment by Pujan92** [comment] 2022-12-05 23:15
**Proposal**

Yes, we are not setting the reportActionID for the new created report action. To solve we need to add `reportActionID` in the `buildOptimisticCreatedReportAction` function.

https://github.com/Expensify/App/blob/2e69dac1a41bd35c8b68e0c08f1da462cd7cc49a/src/libs/ReportUtils.js#L869-L901

Add `reportActionID: NumberUtils.rand64(),` to the above code.

**Comment by mananjadhav** [comment] 2022-12-06 04:14
Thanks for the proposals. @Pujan92's proposal looks good to me.

@akshayasalvi You mentioned the right function for the first part, but in the second part you picked `buildOptimisticReportAction` instead of `buildOptimisticCreatedReportAction`.  I am guessing it's an honest mistake, but because the next proposal mentions the correct function I've gone ahead with that.

@arosiclair All yours.

C+ Reviewed

**Comment by arosiclair** [comment] 2022-12-06 14:35
@Pujan92's new proposal looks good to me too. Thanks for the update!  @johncschuster can we hire them for the job?

**Comment by Pujan92** [comment] 2022-12-06 17:15
Oh, ok. I wasn't aware about it but anyways Thanks.

**Comment by marcaaron** [comment] 2022-12-07 22:08
Gonna remove the Help Wanted label from here as this does not seem actionable based on [this comment](https://github.com/Expensify/App/issues/13224#issuecomment-1339563702)

**Comment by mananjadhav** [comment] 2022-12-09 05:05
@johncschuster @arosiclair Do we need to keep this open when it is tracked by a separate PR? Should we close this one out?

**Comment by arosiclair** [comment] 2022-12-09 14:55
I am trying to find out when this issue was originally reported. If it was reported earlier than when we started tracking it internally, then I _think_ the reporter still gets a payment.

**Comment by bernhardoj** [comment] 2022-12-09 15:30
I reported it on 29th Nov.

@arosiclair

**Comment by arosiclair** [comment] 2022-12-09 15:58
Thanks. Since We started tracking this issue internally on Nov 28th, I do not think this is eligible for payment since the fix was already planned. Closing this out

**Closed by arosiclair** 2022-12-09 15:58 UTC
Labels: Daily, Bug

**Comment by Pujan92** [comment] 2022-12-09 16:29
@arosiclair isn't that [PR](https://github.com/Expensify/App/pull/13324/commits/030de8a3da44e3590450328ff05f5c623588da11) inspired from my proposal(I might be wrong but sharing my observation)?

**Comment by arosiclair** [comment] 2022-12-09 20:46
It wasn't. The change to add report IDs to CREATED report actions (and handle them in the backend) was already planned in our tracking issue on Nov 28th before this issue was reported. This was part of our ongoing effort for deprecating sequence numbers. Sorry I did not notice this sooner.
