### ISSUE TITLE
[$500] New chat - Composed box is displayed in the middle of page when open a user that don't have any messages with

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11858] opened 2022-10-14 17:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Log in with any account
3. Click on the green + button
4. Click on the "New Chat" option
5. Search for a user that you don't have any messages with and open the chat.

_Note: this seems to occur with other input fields. For example, this was reproducible for me after editing the first-name input field in Settings._ 

## Expected Result:
- There should not be padding beneath the input

## Actual Result:
- There is keyboard-sized vertical padding beneath the input

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android
- iOS

**Version Number:** 1.2.15.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195905893-5ce8fd8d-6379-4f7c-a3a4-031e9765715f.mp4

<img width="375" alt="Screenshot 2022-10-25 at 11 35 16" src="https://user-images.githubusercontent.com/10736861/197753801-52e37860-6fcf-4299-8121-d61d0d311b36.png">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PauloGasparSv** [comment] 2022-10-14 19:36
Could not reproduce the error locally or in my physical devices using the latest App version from TestFlight.
Closing this blocker for now!

cc @yuwenmemon

**Comment by thesahindia** [comment] 2022-10-17 13:55
@PauloGasparSv, can we reopen this as it's reproducible (it was also reported [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1665794603439699)) 
It is not consistent so hard to repro.

**Comment by PauloGasparSv** [comment] 2022-10-17 14:03
Hey @thesahindia! I think we should keep it closed till the P.R. https://github.com/Expensify/App/pull/10648 gets merged because it will also be tested against iOS if that's ok.

I'll link this issue to the P.R.

**Comment by kbecciv** [comment] 2022-10-17 14:22
@thesahindia @PauloGasparSv Issue is reproduced in latest build 1.2.16.4 

https://user-images.githubusercontent.com/93399543/196202163-428dc5b7-756e-4e5c-b1c1-8fd9add7ac4c.MP4

![IMG_5063](https://user-images.githubusercontent.com/93399543/196202276-f6d9c724-73f1-4a9a-bd80-5ca0aab53bb5.png)

**Comment by PauloGasparSv** [comment] 2022-10-17 15:14
Thanks @kbecciv!
As [mentioned here](https://expensify.slack.com/archives/C01GTK53T8Q/p1666012831265479) we are reopening this, despite of the similar issue https://github.com/Expensify/App/issues/10539 that happens on Android as the root cause may not be the same and the issue was reproduced again!

Marking this as external!

**Comment by sketchydroide** [comment] 2022-10-17 16:43
removing the blocker as this was reported on the currently prod version.

**Comment by ntrepanier** [comment] 2022-10-17 17:22
On hold until https://github.com/Expensify/App/pull/11586 is merged based on this [slack convo](https://expensify.slack.com/archives/C01GTK53T8Q/p1666012831265479).

**Comment by tgolen** [comment] 2022-10-18 15:22
Added to master tracking issue https://github.com/Expensify/App/issues/10273

**Comment by thesahindia** [comment] 2022-10-24 07:14
Not overdue.

**Comment by mvtglobally** [comment] 2022-10-24 18:39
Issue not reproducible during KI retests. (First week)

**Comment by tgolen** [comment] 2022-10-31 16:47
This is no longer on hold and can have proposals created for it with the new code.

**Comment by JmillsExpensify** [comment] 2022-11-02 19:59
@mvtglobally Are you able to reproduce this? If you aren't after a second round of tests, I vote we close the issue.

**Comment by mvtglobally** [comment] 2022-11-03 03:13
Issue not reproducible during KI retests. (Second week)

**Comment by JmillsExpensify** [comment] 2022-11-03 03:55
I was also to reproduce this issue just now using the testing steps above.

**Comment by Julesssss** [comment] 2022-11-03 14:46
I updated the description to include infor from [this](https://github.com/Expensify/App/issues/12114) duplicate issue.

**Comment by JmillsExpensify** [comment] 2022-11-06 20:07
Clarifying that this issue is open for proposals. Upwork job is here: https://www.upwork.com/jobs/~019a97b096e6136548.

**Comment by JmillsExpensify** [comment] 2022-11-08 19:37
Doubling the price to $500. We're still open for proposals.

**Comment by kbecciv** [comment] 2022-11-11 21:26
Issue is reproduced  today with build 1.2.27.0

https://user-images.githubusercontent.com/93399543/201433057-9ae6ec58-43a9-46bc-8d60-9e788cf5b8d4.mp4

**Comment by tgolen** [comment] 2022-11-16 21:55
Still looking for proposals

**Comment by JmillsExpensify** [comment] 2022-11-17 05:33
Ideally Margelo or an internal engineer will be taking this on soon!

**Comment by JmillsExpensify** [comment] 2022-11-18 22:50
Removed the iPad app testing steps since tablets are not an officially supported platform.

**Comment by madmax330** [comment] 2022-11-21 14:35
Picking this up

**Comment by JmillsExpensify** [comment] 2022-11-22 06:23
Thanks Maxence. Looks like we have a relatively fresh reproduction from Applause, though let us know if you have any questions.

**Comment by mvtglobally** [comment] 2022-11-22 21:11
Issue not reproducible during KI retests. (Third week) Can we close this?

**Comment by madmax330** [comment] 2022-11-23 06:39
I'm able to reproduce this 😄 

The repro steps are:

- Open the LHN
- Click on a chat
- Go back to the LHN
- Go to the search page
- Close the search page (without doing anything on it)
- Click on a chat
- 💥

**Comment by Julesssss** [comment] 2022-11-23 10:51
I can't find the issue, but those reproduction steps exactly match what I'm seeing occasionally on the related Android issue. Updating to show that this occurs on ANdroid and iOS

**Comment by madmax330** [comment] 2022-11-23 11:12
So I initially thought that this was introduced in this PR: https://github.com/Expensify/App/pull/12169/files
Where we set the height of the container here: https://github.com/Expensify/App/blob/6fc17930f4a306fbb862e2d501d68ffde0618b9d/src/pages/home/ReportScreen.js#L290

But that is just a post screen shrinking action, so I'm 90% sure the KAV still thinks the keyboard is open even though it isn't, which is weird because we call `Keyboard.dismiss()` when we navigate away from the search page

**Comment by madmax330** [comment] 2022-11-23 14:07
Ok so I did some further investigation and it seems to me like it's definitely the KAV that's causing this. 
I passed a `console.log` through the `onLayout` prop here: https://github.com/Expensify/App/blob/6fc17930f4a306fbb862e2d501d68ffde0618b9d/src/pages/home/ReportScreen.js#L233

Which is then called here when the KAV view changes: https://github.com/facebook/react-native/blob/3eb69f24ddc281f4bff2f250f88cb875d6d721d0/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L125

And I added a `console.log` here: https://github.com/Expensify/App/blob/6fc17930f4a306fbb862e2d501d68ffde0618b9d/src/pages/home/ReportScreen.js#L271

That will print out the height of the view. 

And I noticed that in the event caught by the KAV in `onLayout` the height is 769 (normal height), but in the component it is 392 (bug height)

So what that tell me is that the KAV added the padding when we re-opened the reports page, which means that this function is not returning early and the function is not returning 0 for the padding height: https://github.com/facebook/react-native/blob/3eb69f24ddc281f4bff2f250f88cb875d6d721d0/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L130

I'm not sure what to do from here though...

Thoughts @tgolen ??

I will post in #expensify-open-source as well

**Comment by madmax330** [comment] 2022-11-23 14:10
Posted here: https://expensify.slack.com/archives/C01GTK53T8Q/p1669212581514609

**Comment by marcaaron** [comment] 2022-11-23 17:51
Great summary @madmax330 and amazing job reproducing and debugging this issue. It seems like it will happen anytime we navigate to a chat while the LHN is open under a modal that triggers the KAV e.g. I was able to reproduce also by doing:

- New Room
- Dismiss
- Tap chat in LHN
- 💥 

So it seems like when we are using the KAV in a modal view that it somehow affects the initial state of the KAV on the ReportScreen. You can switch between various chats after that and it's still stuck open.

**Comment by marcaaron** [comment] 2022-11-23 19:12
Traced this one back to the `Freeze` component (which we will probably deprecate as part of the App Navigation Reboot). 

The `ScreenWrapper` being inside the `react-freeze` component prevents it from re-rendering and leaves it in a stuck state. This diff should fix it:

```diff
diff --git a/src/pages/home/ReportScreen.js b/src/pages/home/ReportScreen.js
index 972dc0210f2..744a6d4fc2f 100644
--- a/src/pages/home/ReportScreen.js
+++ b/src/pages/home/ReportScreen.js
@@ -217,19 +217,17 @@ class ReportScreen extends React.Component {
         // There are no reportActions at all to display and we are still in the process of loading the next set of actions.
         const isLoadingInitialReportActions = _.isEmpty(this.props.reportActions) && this.props.report.isLoadingReportActions;
         return (
-            <Freeze
-                freeze={this.props.isSmallScreenWidth && this.props.isDrawerOpen}
-                placeholder={(
-                    <ScreenWrapper
-                        style={screenWrapperStyle}
-                    >
-                        <ReportHeaderSkeletonView />
-                        <ReportActionsSkeletonView containerHeight={this.state.skeletonViewContainerHeight} />
-                    </ScreenWrapper>
-                )}
+            <ScreenWrapper
+                style={screenWrapperStyle}
             >
-                <ScreenWrapper
-                    style={screenWrapperStyle}
+                <Freeze
+                    freeze={this.props.isSmallScreenWidth && this.props.isDrawerOpen}
+                    placeholder={(
+                        <>
+                            <ReportHeaderSkeletonView />
+                            <ReportActionsSkeletonView containerHeight={this.state.skeletonViewContainerHeight} />
+                        </>
+                    )}
                 >
                     <FullPageNotFoundView
                         shouldShow={!this.props.report.reportID}
@@ -310,8 +308,8 @@ class ReportScreen extends React.Component {
                             )}
                         </View>
                     </FullPageNotFoundView>
-                </ScreenWrapper>
-            </Freeze>
+                </Freeze>
+            </ScreenWrapper>
         );
     }
 }
```

**Comment by JmillsExpensify** [comment] 2022-11-26 22:23
Awesome work guys! This is exactly the kind of digging into the codebase we need during WAQ.

**Comment by JmillsExpensify** [comment] 2022-12-01 05:44
@rushatgabhane Mind applying to the [Upwork job](https://www.upwork.com/jobs/~019a97b096e6136548) for C+ testing? Then we can close this one out as soon as the linked PR is deployed.

**Comment by JmillsExpensify** [comment] 2022-12-08 02:57
@rushatgabhane No worries, let's keep focused on squashing bugs. Your offer is appreciated though it's more work to rescind that it is to fight the fight against bugs. Thank you!

**Comment by JmillsExpensify** [comment] 2022-12-08 03:09
Rushat is paid out and the PR is already on production. I'm going to create a large keyboard behavior test following the completion of our KAV initiative, which I'm cataloguing in the linked regression test above. I'm closing this one out.

**Closed by JmillsExpensify** 2022-12-08 03:09 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
