### ISSUE TITLE
[HOLD for payment 2023-05-25] [$1000] Emoji gets added in between the text when selecting text and add new emoji by search and enter 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18515] opened 2023-05-05 23:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. Write multiple emojis (any emojis are fine) in compose box
4. **Select the emojis** and open emoji picker
5. Search for any emoji and **press enter** to insert the emoji (do not click to select)

## Expected Result: 
App should remove the emojis as it does normally when we select the emoji by clicking on it.

## Actual Result: 
App adds emoji in the middle of existing emojis

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236585877-e862b3e2-735d-4f98-bfb7-ab7e3d07c589.mp4

https://user-images.githubusercontent.com/43996225/236585888-23e8caa3-676a-4a95-899c-bb6d0a5e34bb.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683280230048149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf65aebce0e7ee33</li>
        <li>Upwork Job ID: 1655592568939524096</li>
        <li>Last Price Increase: 2023-05-08</li>
    </ul>
</details>

**Comment by dukenv0307** [comment] 2023-05-06 10:06
### Please re-state the problem that we are trying to solve in this issue.
## Proposal
Emoji gets added in between the text when selecting text and add new emoji by search and enter
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/d120f6a9aa13dc842e265202996f8fe32019faca/src/pages/home/report/ReportActionCompose.js#L534-L542

We are updating the selection state before inserting the emoji. 
### What changes do you think we should make in order to solve the problem?
We should insert emoji before updating the selection state like this
```
addEmojiToTextBox(emoji) {
        
        this.updateComment(ComposerUtils.insertText(this.comment, this.state.selection, emoji));
        this.setState(prevState => ({
            selection: {
                start: prevState.selection.start + emoji.length,
                end: prevState.selection.start + emoji.length,
            },
        }));
       
    }

```

### What alternative solutions did you explore? (Optional)
NA

**Comment by anmurali** [comment] 2023-05-08 14:12
Cannot reproduce

**Comment by dukenv0307** [comment] 2023-05-08 14:17
@anmurali Please try again with these steps:
1. Open the app
2. Open any report
3. Write 2 emojis (any emojis are fine) in compose box
4. Select all emojis
5. open emoji picker
6. Hover any emoji and click enter

My video
https://user-images.githubusercontent.com/129500732/236848003-48cca23f-e786-4072-84fd-21507dcba421.mov

**Comment by dukenv0307** [comment] 2023-05-11 03:35
@dangrous I posted a [proposal](https://github.com/Expensify/App/issues/18515#issuecomment-1537107813), please help to look at it
cc @mollfpr

**Comment by mollfpr** [comment] 2023-05-11 12:01
Thanks @dukenv0307, for the proposal!

Before the PR https://github.com/Expensify/App/pull/17346 we used the selection state before it's update in this [file](https://github.com/Expensify/App/pull/17346/files#diff-7fa482b2895f4e36a2a3ad8233496489c6de1256a8c992524e2fc072aaba43f8). So it makes sense that we move it early before the new `setState`.

@dangrous Let's go with @dukenv0307 proposal.

🎀 👀 🎀 C+ reviewed!

**Comment by dangrous** [comment] 2023-05-12 00:11
Ah yep, that makes sense to me! Assigning this now!

@dukenv0307 out of curiosity, do you know why does it fire immediately on `enter` and not on mouse click?

**Comment by dukenv0307** [comment] 2023-05-12 03:19
@dangrous As I said in my proposal

> The root cause is: React may batch multiple setState() calls into a single update for performance. ([ref](https://legacy.reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous))
> When clicking by mouse React doesn't execute immediately and waits to batch multiple setState() calls. But when hitting enter on the keyboard React execute setState immediately

cc @mollfpr

**Comment by dangrous** [comment] 2023-05-12 15:01
@dukenv0307 To clarify: why does React batch the calls on mouse click and not on enter press? I didn't see the answer in the docs, so just wondering. (Doesn't affect the PR at all.)

**Comment by dukenv0307** [comment] 2023-05-15 13:48
@dangrous I am not sure about that. I think it is built-in ReactJS but I haven't seen any article about it yet

**Comment by mollfpr** [comment] 2023-05-25 04:47
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/17346

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/17346#discussion_r1204981390

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1684989964993659

> [@mollfpr] Determine if we should create a regression test for this bug.

I think we should; it's easy to miss this kind of bug while testing/review.

>[@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

Propose regression step

1. Open the app
2. Open any report
3. Write 2 emojis (any emojis are fine) in compose box
4. Select the two above emojis and open emoji picker
5. Hover the mouse over any emoji and hit enter on the keyboard
6. **Verify** that the before emojis are removed and the new emoji is added
7. 👍 or 👎

**Comment by dangrous** [comment] 2023-05-25 15:31
Test looks good to me!

**Comment by mollfpr** [comment] 2023-05-30 13:30
Bump @anmurali to help with the payment

**Comment by anmurali** [comment] 2023-05-31 16:27
I can't find either of you on Upwork since I only have your GH and Slack profile handles. Asked [here](https://expensify.slack.com/archives/C049HHMV9SM/p1685550431586009)

**Comment by anmurali** [comment] 2023-06-01 14:08
Added regression test - https://github.com/Expensify/Expensify/issues/288154
Sent offers, waiting to accept to pay

**Comment by dhanashree-sawant** [comment] 2023-06-01 15:25
Thanks @anmurali, I have accepted the offer.

**Comment by dangrous** [comment] 2023-06-05 14:23
Are we still waiting on the accepted offers, or are we good to close?

**Comment by anmurali** [comment] 2023-06-05 17:34
Paid.

**Closed by anmurali** 2023-06-05 17:34 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by anmurali** [comment] 2023-08-03 16:09
Added bonus to @dukenv0307 and @mollfpr
