### ISSUE TITLE
[$250] Approver - Next step message for the approver is not displayed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49552] opened 2024-09-20 19:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4991111
**Email or phone of affected tester (no customers):** gibethlehem@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Create a workspace with an approver.
2. Make the approver the approver of the workspace

OD configuration
1. As the admin in OldDot - Navigate to members
2. Under "Workflow enforcement" enable "Prevent Self Approval"

NewDot - Admin Approver

1. Login as the Approver
2. Navigate to the workspace chat
3. Submit expense from the workspace
4. Click on the report that was created

## Expected Result:
There is a hour glass with a comment: "_Oops! Looks like you're submitting to yourself. Approving your own reports is forbidden by your policy. Please submit this report to someone else or contact your admin to change the person you submit to._" and label is "Next Steps"."

## Actual Result:
A message is not display to the approver that they're not allowed to submit reports to themselves if the Enable self Approval is enabled in the workspace.
Issue doesn't happen with the US tester.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b9b87162-6b79-47e1-9ac0-e0bbddfbf7ae

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839076781356799211</li>
        <li>Upwork Job ID: 1839076781356799211</li>
        <li>Last Price Increase: 2024-10-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by IuliiaHerets** [comment] 2024-09-20 19:04
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lschurr** [comment] 2024-09-20 21:49
I'm heading OOO from 9/23-10/4 so I need to reassign this one.

**Comment by CortneyOfstad** [comment] 2024-09-23 19:11
Will need a bit of time to test this!

**Comment by CortneyOfstad** [comment] 2024-09-25 22:56
I was not able to recreate this consistently, so going to see if we can have this retested!

**Comment by CortneyOfstad** [comment] 2024-10-01 18:39
Not overdue as we're still waiting for this to be retested!

**Comment by teneeto** [comment] 2024-10-02 09:34
Hey! I'm Eto Olei from Callstack. I will like to look into this issue. Please assign it to me. Thanks!

**Comment by CortneyOfstad** [comment] 2024-10-02 19:06
Sounds great @teneeto! Thanks!

**Comment by teneeto** [comment] 2024-10-04 07:52
Still investigating this one.

**Comment by teneeto** [comment] 2024-10-08 07:47
Hi @CortneyOfstad I'm still looking into this. Although i can see a similar behaviour, but I have not yet reproduced the exact issue as seen in description. Still some more time to dig in.

**Comment by teneeto** [comment] 2024-10-08 14:23
I'm not sure if I'm missing any steps, but I still can't reproduce this. Can we retest it?

**Comment by CortneyOfstad** [comment] 2024-10-08 15:02
Thanks @teneeto! I also am not able to consistently reproduce this — going to close!

**Closed by CortneyOfstad** 2024-10-08 15:02 UTC
Labels: External, Daily, Overdue, Bug, retest-weekly
