### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] Web - Login - "Incorrect magic code" error if click "Go back" in 2FA input page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19712] opened 2023-05-27 00:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition - User has setup a 2FA to log into account

1. Open https://staging.new.expensify.com/

2. Input email for account from the precondition
3. Click "Continue"
4.Input magic code
5. Click "Continue
6. Click "Go back"
## Expected Result:
User lands in login page with no errors

## Actual Result:
User lands in login page with an error about incorrect magic code displayed - "Incorrect magic code. Please try again or request a new code".

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/45718df5-6488-4ce2-bc77-867e8e742b43

<img width="1440" alt="Bug6069882_Screenshot_2023-05-27_at_04 01 15" src="https://github.com/Expensify/App/assets/43996225/fa9b692b-3734-456a-92b8-b84280ff3a07">

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117c06543ed99c789</li>
        <li>Upwork Job ID: 1663137767104331776</li>
        <li>Last Price Increase: 2023-05-29</li>
    </ul>
</details>

**Comment by Nathan-Mulugeta** [comment] 2023-05-28 04:14
Hello team I just wanted to let you know I originally reported this issue [here](https://expensify.slack.com/archives/C049HHMV9SM/p1684759841475729?thread_ts=1684759841.475729&cid=C049HHMV9SM) on slack.

**Comment by bfitzexpensify** [comment] 2023-05-29 10:58
Reproduced.

**Comment by JavSFDev** [comment] 2023-05-30 07:25
I can fix this bug. Let's discuss more detail.

**Comment by tgolen** [comment] 2023-05-31 03:58
I am reassigning this due to me going on extended leave.

**Comment by luacmartins** [comment] 2023-05-31 15:23
Thanks @rushatgabhane! I agree that the proposal looks good!

**Comment by avi-shek-jha** [comment] 2023-06-02 03:06
@luacmartins @rushatgabhane Seems [this](https://github.com/Expensify/App/issues/18310) issue is similar.

**Comment by bfitzexpensify** [comment] 2023-06-22 09:17
No problem @rushatgabhane - let's leave it a daily for the moment just so the priority is still correct, but noted that it won't be completed until next week

**Comment by bfitzexpensify** [comment] 2023-06-26 06:44
@rushatgabhane just a reminder to complete the checklist this week when you get a chance - thanks!

**Comment by bfitzexpensify** [comment] 2023-06-27 05:12
@rushatgabhane thanks for completing the checklist! 

Happy to switch this to a weekly. Just a note on that — that means I won't be checking this issue every day, so if you can ping here once the new payment method is ready to go, I'll get that payment processed ASAP.

**Comment by bfitzexpensify** [comment] 2023-07-05 13:09
Awesome — OK, we can close this out, thanks everyone!

**Closed by bfitzexpensify** 2023-07-05 13:09 UTC
Labels: External, Weekly, Awaiting Payment, Bug
