### ISSUE TITLE
Requests - Split bill preview shows all group members even if split bill does not apply to all

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#19170] opened 2023-05-18 04:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the + icon in a Group conversation
2. Open the DM create menu again and select Split Bill
3. Enter an amount into the BNP
4. Select part of the members of the group and tap "Split Bill"
5. Tap to IOU preview for this request

## Expected Result:
Showing only users who participate in this split bill as indicated in the IOU preview

## Actual Result:
All users in the group are shown

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.15-12
**Reproducible in staging?:** Y 
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/4c5d27ba-143b-47e5-b22d-31c62db6832b

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5e1057110ef40b6</li>
        <li>Upwork Job ID: 1659683355058298880</li>
        <li>Last Price Increase: 2023-05-19</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-05-18 08:10
@mvtglobally can you clarify what "BNP" stands for?

Also, I think the description of the issue isn't quite right.

For context, I created a Group between three users, and created a `Split Bill` between _two_ of the three users.

Next, I created another `Split Bill` between all three users in the DM.

When I click into either `Split Bill` requests, I only see the two members of the first `Split Bill` request, so I think this is more like, "Split bill preview only shows all members of the first `Split Bill` request in the group DM".

Can you test for that and see if that's true?

**Comment by luacmartins** [comment] 2023-05-18 16:01
@johncschuster this page is still under development. I have a draft PR [here](https://github.com/Expensify/App/pull/19196)

**Comment by luacmartins** [comment] 2023-05-19 22:11
PR in review - https://github.com/Expensify/App/pull/19196

**Comment by Nathan-Mulugeta** [comment] 2023-05-20 04:06
Hey team, I just want to let you know that I originally reported this issue [here](https://expensify.slack.com/archives/C049HHMV9SM/p1683617341708809?thread_ts=1683617341.708809&cid=C049HHMV9SM) in slack before this GH issue was created.

**Comment by luacmartins** [comment] 2023-05-23 15:01
@Nathan-Mulugeta thanks for letting us know, however we had plans to completely refactor this page as part of [this issue](https://github.com/Expensify/App/issues/18640) and in fact we can close this one.

**Closed by luacmartins** 2023-05-23 15:01 UTC
Labels: Reviewing, Daily, Internal, Bug
