### ISSUE TITLE
[$250] [CVP] New User who is submitted an IOU pays via BBA, then see’s `Approve'

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42322] opened 2024-05-16 20:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715816298574129

## Action Performed:

1. As user A send a IOU request to new user
2. Click "Pay" from the new user email
3. User is taken to the IOU report
4. Select the option "Pay with expensify"
5. Select option "Business bank account"
6. This will create a workspace and moves the IOU to a workspace chat
7. Cancel the VBBA set up and navigate to the workspace chat

## Expected Result:
The expense should see `pay `rather than `approve`. 

## Actual Result:
 There is an option to approve the expense, even though it’s a brand new workspace and thus shouldn’t have approval.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/75e30b41-82a9-4adc-aa72-0320aee34db4

https://github.com/Expensify/App/assets/38435837/98fc8878-c3e5-4d89-9ee5-a4fb07a0587b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc2fb178d0dea7a3</li>
        <li>Upwork Job ID: 1792680301683040256</li>
        <li>Last Price Increase: 2024-06-10</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 102721547</li>
<li>bernhardoj | Contributor | 102721548</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by bernhardoj** [comment] 2024-05-17 07:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The money request preview shows approve button even though it's a new workspace which has approval disabled by default.

### What is the root cause of that problem?
This has the same root cause as https://github.com/Expensify/App/issues/39171.

We already have a condition here to not show the approve button if the approval is disabled (isOnSubmitAndClosePolicy).

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/actions/IOU.ts#L5978-L5982

However, the auto-reporting frequency needs to be instant (isOnInstantSubmitPolicy) to not show the approval button. In our case, the frequency is set to WEEKLY, so the condition is never met.

### What changes do you think we should make in order to solve the problem?

Remove isOnInstantSubmitPolicy condition

Or change the condition to accept either isOnInstantSubmitPolicy or isOnSubmitAndClosePolicy.
`if (isOnInstantSubmitPolicy || isOnSubmitAndClosePolicy) {`

We need to fix on the BE too because the next step indicating for the admin to approve it first.

**Comment by kevinksullivan** [comment] 2024-05-20 22:13
This is bottom up case, so adding to collect project

**Comment by DylanDylann** [comment] 2024-05-22 04:35
This RCA and solution of this issue is similar to [this one](https://github.com/Expensify/App/issues/39171) that I approved 
@bernhardoj's proposal https://github.com/Expensify/App/issues/39171#issuecomment-2029805915.  @kevinksullivan Do you think we should close this one and reopen [the previous issue](https://github.com/Expensify/App/issues/39171)?

**Comment by kevinksullivan** [comment] 2024-06-04 21:10
I agree we should just keep up with the same issue. @hoangzinh if you want to pass to @DylanDylann you can, or you can stay on as C+.

**Comment by DylanDylann** [comment] 2024-06-11 04:49
Taking over as C+

**Comment by DylanDylann** [comment] 2024-06-11 11:06
Hi @bernhardoj Could you reproduce this issue any mỏe?

**Comment by bernhardoj** [comment] 2024-06-11 15:30
Yes, I can still repro it.

https://github.com/Expensify/App/assets/50919443/067abd54-949c-4721-b3a4-527ab3f19e1e

**Comment by DylanDylann** [comment] 2024-06-12 06:48
<img width="1512" alt="Screenshot 2024-06-12 at 13 46 14" src="https://github.com/Expensify/App/assets/141406735/de9936c2-6212-486d-93bf-b1e15794d26b">

@bernhardoj A bit curious, when I log in as a new user, I only see an option for payment "pay .. elsewhere"

**Comment by bernhardoj** [comment] 2024-06-12 06:55
Ah, the pay with expensify is for USD only, the currency is always converted to my local currency, so I manually update the code to always show the pay with expensify option.
https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/components/SettlementButton.tsx#L178

**Comment by DylanDylann** [comment] 2024-06-12 07:41
@bernhardoj Your alternative proposal looks good to me. Let's go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/42322#issuecomment-2116932048)

🎀👀🎀 C+ reviewed

**Comment by amyevans** [comment] 2024-06-13 14:38
Agreed we can set it optimistically to take care of this, assigning @bernhardoj and @DylanDylann

**Comment by bernhardoj** [comment] 2024-06-13 15:04
This [PR](https://github.com/Expensify/App/pull/43273) already set the `autoReportingFrequency` to instant, I guess nothing to do here then.

**Comment by amyevans** [comment] 2024-06-13 18:08
Okay got it, I think we should just close here then. Sorry this is the second time this has happened 😬

**Closed by amyevans** 2024-06-13 18:08 UTC
Labels: External, Daily, Bug
