### ISSUE TITLE
[HOLD for payment 2024-08-13] [$250] [Held requests] Partially approved expenses are not GBR'ed in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45902] opened 2024-07-22 12:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4747965
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite:
1. Create a workspace and add user A (as a member) and user B (as an admin).
2. More features > Enable workflows > Enable Add Approvals > Set user B as an approver
Steps
1. As user A submit two expenses to the workspace
2. As user B (the approver) navigate to the expense report and hold one of the expenses
3. As user B (the approver) click on the approve option
4. A modal is displayed to approve the full report amount or just the pending expense
5. Approve the pending expense (Submitted expense that is not on hold)
6. When the action is completed observe the LHN and workspace chat report.

## Expected Result:
A new report is created with the expense on hold and is GBR’ed in the LHN (green dot)

## Actual Result:
A new report is created with the expense on hold but is not GBR’ed in the LHN (green dot)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9ae19f52-d126-43a0-9686-38594d545360

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0130a7781bd6d708e1</li>
        <li>Upwork Job ID: 1816612436734076568</li>
        <li>Last Price Increase: 2024-07-25</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103312301</li>
<li>nkdengineer | Contributor | 103312306</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by lanitochka17** [comment] 2024-07-22 12:39
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment] 2024-07-25 23:12
Ok I've recreated the issue and agree it should be fixed:

![image](https://github.com/user-attachments/assets/e1944b73-0c7b-48e6-bee5-93d5c23a3aa6)

I think this is part of Wave Collect.

**Comment by nkdengineer** [comment] 2024-07-26 06:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A new report is created with the expense on hold but is not GBR’ed in the LHN (green dot)

### What is the root cause of that problem?
The Actual behavior in the OP is actually the correct behavior, as all outstanding requests are on HOLD, there's no action from the approver. The ball is on the request submitter to add more information/clarification so the request can be taken off HOLD.

That behavior is consistent with the back-end too.

The problem here is that it doesn't work now in offline mode because we're not setting optimistic data correctly. In https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/actions/IOU.ts#L6753, we don't set the IOU report ID to exclude in case of partial approval, this causes the `hasOutstandingChildRequest` to be `true` and GBR shows after approving partially, although there's no action for the approver, after approving that and held expenses moved to a new report.

### What changes do you think we should make in order to solve the problem?

Update https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/actions/IOU.ts#L6753
to 
```
hasOutstandingChildRequest: hasIOUToApproveOrPay(chatReport, expenseReport?.reportID ?? '-1'),
```

### What alternative solutions did you explore? (Optional)
This `hasIOUToApproveOrPay` could be missing in other optimistic cases too, such as when holding a request, paying, ... we need to check those places and add if needed (some adjustments could also be needed, eg. we need to pass the updated IOU report data/transaction data in `hasIOUToApproveOrPay` and merge it with the `iouReport` [here](https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/actions/IOU.ts#L6701), and do not use `excludedIOUReportID`). This will make the `hasOutstandingChildRequest` (GBR) behavior consistent with the back-end.

**Comment by ikevin127** [comment] 2024-07-27 00:08
I confirm that the issue **is reproducible** as per OP steps - but I'm not sure whether we want to fix this as per the OP **Expected result.**

**What happens currently:**
1. User A (Member - Submitter) submits 2 expenses.
2. User B (Admin - Approver) sets one of User A's expenses on Hold, adding a reason for Hold.
3. User B (Admin - Approver) will be shown a GBR because they can still **Approve** one of the expenses (the one which wasn't put on Hold).
4. User B (Admin - Approver) **approves** the other expense which which wasn't put on Hold -> no other indicator (RBR nor GBR) is shown for the (Admin - Approver) anymore.
5. User A (Member - Submitter) will see a RBR because one of the expenses was put on Hold by User B, giving a specific reason for the Hold.

**Notes:**
- User B should not see any indicator (RBR nor GBR) since on their side there's no pending action.
- User A will see a RBR because one of their expenses was put on Hold for a specific reason given by User B and they have to be notified of that - so RBR makes sense for User A in this case.

##

@nkdengineer's [proposal](https://github.com/Expensify/App/issues/45902#issuecomment-2252047214) makes sense to me as far as explaining the way in which the **Actual result** might be the correct behaviour in this case, this being backed by and consistent with the BE data as well. As far as the solution goes, I tested the **offline** behaviour and there's indeed an inconsistency compared to the **online** behaviour -> which can be fixed by the proposed **main solution**.

As for the proposed **alternative solution**: I think that proposition is out of scope for this issue.

This being said, I'll defer to the CME as to whether we should actually fix this issue as per the OP **Expected result** and change the current behaviour, **or** only fix the **offline** behaviour to have consistency with the current **online** behaviour (OP **Actual result**).

🎀👀🎀 C+ reviewed

cc @

**Comment by nkdengineer** [comment] 2024-07-29 14:28
Friendly bump @danieldoglas for [assignment](https://github.com/Expensify/App/issues/45902#issuecomment-2253664832), thank you

**Comment by ikevin127** [comment] 2024-07-29 16:43
@danieldoglas Not sure if you've read through https://github.com/Expensify/App/issues/45902#issuecomment-2253664832 before assignment - because assignment here without further discussion means we're not fixing the issue as the OP expects, but instead just aligning the offline behaviour with what we have online.

**Comment by danieldoglas** [comment] 2024-07-30 10:18
I agree that the actual solution is the correct one - there's nothing for the approver to work, so it doesn't make sense to create a GBR.

@VictoriaExpensify do you disagree?

**Comment by ikevin127** [comment] 2024-07-30 17:31
Thanks for the feedback! In this case I think @nkdengineer can move forward with opening the PR.

If **Victoria** disagrees, we can change course at any time.

**Comment by ikevin127** [comment] 2024-08-11 01:03
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42573.
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/42573#issuecomment-2282334519.
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Create a workspace and add user A (as a member) and user B (as an admin).
2. More features > Enable workflows > Enable Add Approvals > Set user B as an approver.
3. As user A submit two expenses to the workspace.
4. As user B (the approver) navigate to the expense report and hold one of the expenses.
5. 4. As user B, go **offline**.
6. As user B (the approver) click on the **Approve** option.
7. A modal is displayed to approve the full report amount or just the pending expense.
8. Approve the pending expense only (submitted expense that is not on hold).
9. When the action is completed observe the LHN and workspace chat report.
10. Verify that user B does not see any indicator (RBR nor GBR) since on their side there's no pending action.

Do we agree 👍 or 👎.

**Comment by VictoriaExpensify** [comment] 2024-08-12 07:26
lgtm. @danieldoglas - what do you think?

**Comment by ikevin127** [comment] 2024-08-13 14:54
cc @VictoriaExpensify For payment visibility (due today).

**Comment by ikevin127** [comment] 2024-08-14 07:43
cc @VictoriaExpensify For payment (due yesterday 13th).

**Comment by mallenexpensify** [comment] 2024-08-14 22:39
Contributor: @nkdengineer paid $250 via Upwork
Contributor+: @ikevin127 paid $250 via Upwork. 

Test case
-  https://github.com/Expensify/Expensify/issues/420497

Thx y'all 🎉

**Closed by mallenexpensify** 2024-08-14 22:39 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
