### ISSUE TITLE
[$500] Expense - LHN preview for submitted report shows "You" or user's email with no context

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33767] opened 2023-12-29 17:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.19-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee (not an admin) of a Collect workspace.
- User has a display name.
1. Go to workspace chat > + > Request money.
2. Create a manual expense.
3. Click on the expense preview.
4. Click Submit on the expense preview.
5. Note that expense report preview in LHN.
6. Return to the main chat.
7. Click on the expense preview.

## Expected Result:
In Step 5 and 7, the IOU report preview displays "You submitted this report to...".

## Actual Result:
In Step 5, the IOU report preview displays just "You".
In Step 7, the IOU report preview displays the user's email.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e32c5a9d-9bea-483f-9810-d78adb843282

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e710b7d92586ec2</li>
        <li>Upwork Job ID: 1740791347522711552</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2023-12-30 05:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The LHN last message preview shows "You" after submitting an expense and changes to an email after refresh.

### What is the root cause of that problem?
After we submit the expense, the BE will return the last message as "You"
<img width="423" alt="Screenshot 2023-12-30 at 13 46 32" src="https://github.com/Expensify/App/assets/50919443/2c6e2bc7-db26-49bb-961c-ab6d17c42059">

If you notice the report action message, it has 4 arrays and the first array message is "You". This is a similar case of https://github.com/Expensify/App/issues/32285.

After we refresh the web, the OpenReport API will be called and it will return a last message of our email.
<img width="381" alt="Screenshot 2023-12-30 at 13 47 04" src="https://github.com/Expensify/App/assets/50919443/0ccb8d9c-3891-4105-987b-35758c417a00">

### What changes do you think we should make in order to solve the problem?

For the first case, we can use the same approach as https://github.com/Expensify/App/issues/32285.

In OptionsListUtils.getLastMessageTextForReport, add a new case for submitted action.

```
if (ReportActionUtils.isSubmittedExpenseAction(lastReportAction)) {
    lastMessageTextFromReport = _.reduce(lastReportAction.message, (acc, curr) => `${acc}${curr.text}`, '');
}
```

For the second case, investigate on the BE why OpenReport returns our email as the last message.

**Comment by peterdbarkerUK** [comment] 2024-01-02 15:20
Checking internally on priority [here](https://expensify.slack.com/archives/C02MW39LT9N/p1704208837417809)

**Comment by sobitneupane** [comment] 2024-01-09 11:22
Thanks for the [proposal](https://github.com/Expensify/App/issues/33767#issuecomment-1872460956) @bernhardoj.

As stated by @bernhardoj, we may need some backend changes to resolve the issue completely. @peterdbarkerUK, could we please get an internal engineer assigned to investigate the backend for this issue??

**Comment by youssef-lr** [comment] 2024-01-16 21:35
Correct @peterdbarkerUK, I think we can close this.

**Closed** 2024-01-22 15:51 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
