### ISSUE TITLE
[Payment DUE] [$500] Login - svg background image appears late in login screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33916] opened 2024-01-04 00:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Go to Settings > Log out
3. Kill app
4. Relaunch app

## Expected Result:
On login page, the svg background image will not appear late

## Actual Result:
On login page, the svg background image appears late

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dc9cb3cd-e2bb-402d-a6d6-a8e09d5a7825

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165b8a813aeee9ac5</li>
        <li>Upwork Job ID: 1742711677066432512</li>
        <li>Last Price Increase: 2024-01-18</li>
<li>Automatic offers: </li>
<ul>
<li>wildan-m | Contributor | 28121989</li>
</ul></li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2024-01-09 01:07
@eVoloshchak when you get a chance, can you review this proposal? Thanks!

**Comment by alexpensify** [comment] 2024-01-10 18:38
Waiting for a review, no update yet.

**Comment by alexpensify** [comment] 2024-01-15 18:28
@eVoloshchak any update here? Thanks!

**Comment by eVoloshchak** [comment] 2024-01-16 14:13
@abzokhattab, is there a way to preload an image?
Would [prefetch](https://docs.expo.dev/versions/latest/sdk/image/#prefetchurls) do the trick?
Reducing the image size wouldn't fully solve it (there would still be a delay, especially on slower devices), but I think generally an interesting idea we could apply to all SVGs in the app

**Comment by abzokhattab** [comment] 2024-01-16 14:15
> @abzokhattab, is there a way to preload an image?
Would [prefetch](https://docs.expo.dev/versions/latest/sdk/image/#prefetchurls) do the trick?

Will investigate this today

**Comment by abzokhattab** [comment] 2024-01-17 01:47
tried the `prefetch` solution: 


```js
    useEffect(() => {
        Image.prefetch(src);
    }, [src]);
```

but makes no difference, I believe this happens because when we click on `sign out` the cache and all the data are cleared making it reload. so i believe this issue occurs only with the sign-in page because this is the first page the user goes to after the cache is cleared. so the app take few moments to load the image again 



https://github.com/Expensify/App/blob/82b76c1a36cf1a01b00c14510a5812a591e7f2fd/src/libs/actions/Session/index.ts#L90-L94

so i believe that minimizing the svg files size will be sufficient for this problem given that it only occurs with the login page. 


FYI: [image-expo](https://docs.expo.dev/versions/latest/sdk/svg/) recommends minimizing the SVG files using SVGOMG this is another tool, so now we have two tool to choose from them:
> Optimize your SVG with [SVGOMG](https://jakearchibald.github.io/svgomg/). This will make the code smaller and easier to work with. Be sure not to remove the viewbox for best results on Android.


let me know what you think @eVoloshchak

**Comment by alexpensify** [comment] 2024-01-17 18:30
Thanks for that update, we will wait for the next review here.

**Comment by wildan-m** [comment] 2024-01-18 02:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Login - svg background image appears late in login screen

### What is the root cause of that problem?

This is a performance issue caused by heavy Lottie animation on the initial launch. 

I've tried to:
- Perform background image pre-load / pre-fetch
- Change the image background to a [simple one](https://dummyimage.com/600x400/000/fff).
- Change the `expo-image` to our `ImageSVG` component
- Change .lottie file to .json

But I can still reproduce the issue with these attempts, then when I hide the lottie component (hero image) or change it with simpler animation, it works, but not always, I believe the device specs also affect this issue.

In my case, `Magician.lottie` works since it's lighter.

| Hands.lottie | Magician.lottie  |
|---|---|
|<img width="468" alt="Screenshot 2024-01-18 at 09 26 23" src="https://github.com/Expensify/App/assets/11847279/38bc687d-b0cb-47a1-97e6-69bb7dc787f2">|<img width="468" alt="2" src="https://github.com/Expensify/App/assets/11847279/ad24448f-6b48-4cdc-9539-45b508172d48">|   
|<img width="468" alt="Screenshot 2024-01-18 at 09 26 38" src="https://github.com/Expensify/App/assets/11847279/4b75365b-c428-4cce-bf32-697936a83857">|<img width="468" alt="6" src="https://github.com/Expensify/App/assets/11847279/c3fc6c24-9fa4-4f84-bc62-6664cf9ae814">| 
|<img width="468" alt="Screenshot 2024-01-18 at 09 26 50" src="https://github.com/Expensify/App/assets/11847279/4e039e5d-b1e1-4bcd-b1be-97b8910e41cb">|<img width="468" alt="4" src="https://github.com/Expensify/App/assets/11847279/e59c397e-c722-45d0-b73f-b36b91128fa3">|



### What changes do you think we should make in order to solve the problem?

We can perform code-splitting as suggested [here](https://github.com/mifi/react-lottie-player/issues/11#issuecomment-734262712).

I couldn't find a way to do the same using .lottie file but we can use .json instead.

Also, we have to use import and wait until the animation data is completely loaded.

Since import can't be called conditionally, we can't use `LottieAnimations.Hands` variable

```
    const [animationData, setAnimationData] = useState();

    useEffect(() => {
        import('../../../assets/animations/Hands.json').then((res) => setAnimationData(res.default));
    }, []);

    return (
        <Lottie
            source={{file: animationData, w: 375, h: 375}}
            loop
            autoPlay
            style={[styles.alignSelfCenter, imageSize]}
```

Allso we need to add `source.file` check in `Lottie` component
```
    const aspectRatioStyle = styles.aspectRatioLottie(source);

    // If the image fails to load, we'll just render an empty view
    if (isError || !source.file) {
        return <View style={aspectRatioStyle} />;
    }

```

[Branch to test](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/33916-delay-backgroun-code-splitting?expand=1).

### What alternative solutions did you explore? (Optional)
## Alternative 1 - Add transition to `BackgroundImage` component

We treat it as a bug because the background image shows suddenly, but if we intentionally add a transition, it doesn't look that bad.

For native, we can fill `transition` props
```
        <Image
            source={AndroidBackgroundImage}
            pointerEvents={props.pointerEvents}
            style={[styles.signInBackground, {width: props.width}]}
            transition={props.transitionDuration}
        />
```

And for web/desktop we can wrap background image with `Animatable` component

```
function BackgroundImage(props) {
    const styles = useThemeStyles();
    const fadeIn = {
        from: {
            opacity: 0,
        },
        to: {
            opacity: 1,
        },
    };

    return <Animatable.View
        style={styles.signInBackground}
        animation={fadeIn} duration={props.transitionDuration}>
        {props.isSmallScreen ? (
            <MobileBackgroundImage
                width={props.width}
                style={styles.signInBackground}

            />
        ) : (
            <DesktopBackgroundImage
                width={props.width}
                style={styles.signInBackground}
            />
        )}</Animatable.View>;
}
```
Adding fade-in/cross-dissolve animation with 1000 ms duration
https://github.com/Expensify/App/assets/11847279/bfe959d0-220a-4b32-9045-86d254e00ffd

[Branch to test](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/33916-delay-background-add-transition)

## Alternative 2 - Optimize / Minimize the lottie animation

We can try to optimize the lottie file e.g. using [this site](https://lottiefiles.com/), their optimized output requires a paid subscription, but I think it will not have a significant impact, since the device specs will also affect the result.

Maybe we can minimize the animation complexity to more simpler one.

**Comment by alexpensify** [comment] 2024-01-22 19:00
@eVoloshchak - any update?

**Comment by alexpensify** [comment] 2024-01-22 23:15
@eVoloshchak - any update?

**Comment by eVoloshchak** [comment] 2024-01-23 21:56
Thank you all for a great investigation!

I'm going to leave a couple of points first

- reducing/optimizing the SVG would resolve the issue somewhat, but I don't think that could be considered a fix. It depends on how powerful the device is (processes running in the background, etc.), so the issue would persist on slower devices. And in case we decide to change the SVG file to a different, "heavier" one, it would come back even for powerful devices
- Adding transition (as @wildan-m has proposed in their alternative solution) does look better, but that's also a workaround, not resolving the root cause
- Ideally, we'd want to resolve the root cause, which in this case SVG image taking a longer time to render. We know this is theoretically possible since the previous package we've used didn't have this problem. However, I believe optimizing how `expo-image` renders SVG would be non-trivial and time-consuming, and simply not worth it for such a minor bug

With all that, I think we should proceed with @wildan-m main [proposal](https://github.com/Expensify/App/issues/33916#issuecomment-1897695935)
Showing boot splash/loading indicator while SVG is rendered will resolve the issue, while not adding much complexity

🎀👀🎀 C+ reviewed!

**Comment by wildan-m** [comment] 2024-01-24 07:34
@eVoloshchak, in case we are ready, I have got [the PR ](https://github.com/Expensify/App/pull/35038) ready for review.
Android native video is pending, seems something is wrong with my machine environment after merging with main, but the error is not related to the change in this PR.

**Comment by arosiclair** [comment] 2024-01-24 16:55
I'm reaching out to the design team about this [here](https://expensify.slack.com/archives/C03TME82F/p1706114934338759). 

I'm currently leaning towards the @wildan-m's alternative for showing a transition since the main proposal adds a lot of complexity for a mostly harmless bug.

**Comment by arosiclair** [comment] 2024-01-25 17:37
Yup we agreed on using just the fade-in transition to keep things simple. Let's go with **Alternative 1** @wildan-m

**Comment by wildan-m** [comment] 2024-01-26 01:09
@arosiclair, @eVoloshchak thanks for the follow-up, I've created a new PR ready for review.

**Comment by alexpensify** [comment] 2024-01-26 18:37
Awesome, we are moving forward here.

**Comment by alexpensify** [comment] 2024-02-02 22:21
Weekly update: PR is going to staging soon.

**Comment by wildan-m** [comment] 2024-02-08 13:29
@alexpensify seems automation broken for this bug post. The PR deployed to production 3 days ago, but the title did not change

**Comment by alexpensify** [comment] 2024-02-08 15:34
@wildan-m - thanks for flagging, then I'll monitor this one until it hits the seven-day mark. I'll need to do so manually.

**Comment by alexpensify** [comment] 2024-02-12 15:44
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - $500 @wildan-m 
-  Contributor+ that helped on the issue and/or PR - $500 @eVoloshchak 

Upwork Job: https://www.upwork.com/jobs/~0165b8a813aeee9ac5

Extra Notes regarding payment: I have to apply the payment details manually, this PR was merged 7 days ago - https://github.com/Expensify/App/pull/35215.

**Comment by alexpensify** [comment] 2024-02-12 15:47
Actions taken: 

- @wildan-m has been paid via Upwork 
- @eVoloshchak please submit a request in Chat 
- Lastly, I closed the job in Upwork

--- 

## Closing

**Closed by alexpensify** 2024-02-12 15:47 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-02-21 00:03
$500 approved for @eVoloshchak based on summary above.
