### ISSUE TITLE
[$1000] Chat - Copy-pasting emoji names with keyboard shortcut doesn't paste the right emoji name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24399] opened 2023-08-11 00:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat with a user
2. Send message
3. Apply emoji reaction on the sent message
4. Right-click on the emjoi you applied on the message
5. Triple click on the emoji name
6. Press 'Ctrl + C' to copy the name
7. Open emoji picker & paste the content to the search field

## Expected Result:
The right emoji name should be pasted

## Actual Result:
Wrong, long emoji name is pasted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0384bf71-559d-4c5c-9cc1-3d291701b8d7

https://github.com/Expensify/App/assets/43996225/6ce8513a-e2f8-4d3e-805f-e7e2ba246a65

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-Guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691060569144289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01de88e41de20d9ce9</li>
        <li>Upwork Job ID: 1691744740321337344</li>
        <li>Last Price Increase: 2023-08-23</li>
    </ul>
</details>

**Comment by jfquevedol2198** [comment] 2023-08-11 01:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Copy-pasting emoji names with keyboard shortcut doesn't paste the right emoji name

### What is the root cause of that problem?
<details><summary>Triple click selects avatar's svg style of  nested reaction list</summary>
<img width="1668" alt="image" src="https://github.com/Expensify/App/assets/137529618/1500cd23-2df5-486d-8126-463a651a0779">
</details> 

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/c08d5887b18914d95e64e925bfed290fecfffc94/src/pages/home/report/ReactionList/BaseReactionList.js#L78
Add `styles.userSelectNone` in this line
```javascript
style={{maxWidth: variables.mobileResponsiveWidthBreakpoint, ...styles.userSelectNone}}
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by bfitzexpensify** [comment] 2023-08-16 09:32
Reproduced

**Comment by studentofcoding** [comment] 2023-08-22 14:56
# Proposal

## Please re-state the problem that we are trying to solve in this issue
Copy-pasting emoji names with keyboard shortcut doesn't paste the right emoji name

## What is the root cause of that problem?
The function attempts to get the selected text using `SelectionScraper.getCurrentSelection()` on `useCopySelectionHelper.js` hooks, but it does not handle the case when an emoji is selected. Instead, it assumes that the selected text is always a non-emoji text.

This leads to incorrect behavior when copying and pasting emoji names, as the function does not properly handle the case when an emoji is selected and tries to convert it to an emoji name.

## What changes do you think we should make in order to solve the problem?
In this solution, we are using the getEmojiNameByUnicode function from EmojiUtils to get the emoji name by its Unicode. If an emoji name is found, we wrap it with colons : (which is the standard way to represent emojis in text), otherwise, we use the selected text as it is. This ensures that when an emoji is selected and copied, its name is copied instead of the emoji itself.

```
import {useEffect} from 'react';
import ExpensiMark from 'expensify-common/lib/ExpensiMark';
import CONST from '../CONST';
import KeyboardShortcut from '../libs/KeyboardShortcut';
import Clipboard from '../libs/Clipboard';
import * as EmojiUtils from '../libs/EmojiUtils'; // Add EmojiUtils
import SelectionScraper from '../libs/SelectionScraper';

function copySelectionToClipboard() {
    const selection = SelectionScraper.getCurrentSelection();
    if (!selection) {
        return;
    }
    const parser = new ExpensiMark();
    const selectedEmojiName = EmojiUtils.getEmojiNameByUnicode(selection); //handleEmojiUnicode
    const textToCopy = selectedEmojiName ? `:${selectedEmojiName}:` : parser.htmlToMarkdown(selection); //copied text
    if (!Clipboard.canSetHtml()) {
        Clipboard.setString(textToCopy); //set textToCopy
        return;
    }
    Clipboard.setHtml(selection, parser.htmlToText(selection));
}

export default function useCopySelectionHelper() {
    useEffect(() => {
        const copyShortcutConfig = CONST.KEYBOARD_SHORTCUTS.COPY;
        const unsubscribeCopyShortcut = KeyboardShortcut.subscribe(
            copyShortcutConfig.shortcutKey,
            copySelectionToClipboard,
            copyShortcutConfig.descriptionKey,
            copyShortcutConfig.modifiers,
            false,
        );

        return unsubscribeCopyShortcut;
    }, []);
}

```

## What alternative solutions did you explore? (Optional)
None

## Demo

https://github.com/Expensify/App/assets/20473526/6b61f4e3-186f-4805-841a-44551085a7ac

cc: @eVoloshchak

**Comment by joh42** [comment] 2023-08-22 18:10
@studentofcoding you need to triple-click so that the colons on each side (and hidden text) are copied. Just copying the text is not broken

**Comment by studentofcoding** [comment] 2023-08-23 01:55
Okee @joh42, the triple-click (or copy of all the colons) is covered in my solution too ;)

**Comment by bfitzexpensify** [comment] 2023-08-23 11:35
Heading ooo for a week - @sakluger, we're still in the proposal review stage here, so no action required from you at the moment. I can take this back over next week when I return.

**Comment by sakluger** [comment] 2023-08-24 21:58
Assigning a new C+ to keep this moving forward. @sobitneupane could you please review the proposals we've received so far? Thanks!

**Comment by sobitneupane** [comment] 2023-08-28 10:50
I will review the proposals today.

**Comment by sakluger** [comment] 2023-08-29 02:04
@sobitneupane were you able to review proposals?

**Comment by sobitneupane** [comment] 2023-08-29 08:57
Thanks for the proposal everyone.

[Proposal](https://github.com/Expensify/App/issues/24399#issuecomment-1674374807) from @bernhardoj looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by studentofcoding** [comment] 2023-08-29 09:01
> Thanks for the proposal everyone.
> 
> 
> 
> [Proposal](https://github.com/Expensify/App/issues/24399#issuecomment-1674374807) from @bernhardoj looks good to me.
> 
> 
> 
> 🎀 👀 🎀 C+ reviewed

Can you share why we have to do such a complicated changes where we only needed to include getEmojiByUnicode function like I Proposed ? Thanks

**Comment by sobitneupane** [comment] 2023-08-29 12:24
@studentofcoding The issue is not confined to emoji only. Please go through the RCA section of [the proposal](https://github.com/Expensify/App/issues/24399#issuecomment-1674374807) for other instances of the issue.

**Comment by studentofcoding** [comment] 2023-08-29 16:14
As I recall, the expected behavior should be pasting the Emoji name with the : symbol

And for this could you share why we pursue A manual implementation of dom & nodes (that more like workaround) when we can simply use our EmojiUtils function instead?

Am I missing something @sobitneupane ?

**Comment by sobitneupane** [comment] 2023-08-31 16:46
> And for this could you share why we pursue A manual implementation of dom & nodes (that more like workaround) when we can simply use our EmojiUtils function instead?

@studentofcoding We always try to find the root cause and solve the issue there. Root Cause Analysis in this [proposal](https://github.com/Expensify/App/issues/24399#issuecomment-1674374807) looks promising. Please let us know if you find any issue with the solution.

**Comment by studentofcoding** [comment] 2023-08-31 17:37
The thing is

- The video demonstration is not on Emoji selection rather than a profile selection, when we only need to use `EmojiUtils.getEmojiUnicode` to handle the case, instead of changing (with my RCA reasoning below) as introducing changes into SelectionScraper file might introduce regression & as we might want to keep the behavior on another component

> The function attempts to get the selected text using SelectionScraper.getCurrentSelection() on useCopySelectionHelper.js hooks, but it does not handle the case when an emoji is selected. Instead, it assumes that the selected text is always a non-emoji text.` 

But it's just my concern, and whoever gets selected, it's serve the same result

**Comment by marcaaron** [comment] 2023-09-01 22:01
@sakluger @bfitzexpensify this bug feels like a waste of time to me.

**Comment by sakluger** [comment] 2023-09-01 23:14
@marcaaron I agree, I didn't look too closely at the issue when it was reassigned to me. I'm not sure if anyone actually would copy the emoji name from that menu in real life, and if they did, it would likely be someone who could figure out how to edit the name to work properly.

**Closed by sakluger** 2023-09-01 23:14 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by studentofcoding** [comment] 2023-09-02 03:10
Could you share more why this is a waste of time @marcaaron ? 

Also given mind that the user can and possibly do this, that behaviour itself its making this bug valid, no @sakluger ?

Im just want to ask and clarify things as its not clear why its abruptly being closed where this is a valid bug

Thanks

**Comment by marcaaron** [comment] 2023-09-05 22:06
I'd give the same reasoning as @sakluger. It's just not really something that a user seems like they would do.  I don't think anyone has said it's "invalid" though. The complexity in fixing it don't align with the value we would get by fixing it.

**Comment by studentofcoding** [comment] 2023-09-06 02:28
> I'd give the same reasoning as @sakluger. It's just not really something that a user seems like they would do.  I don't think anyone has said it's "invalid" though. The complexity in fixing it don't align with the value we would get by fixing it.

I beg to differ on the complexity in fixing it. In the end its just a simple fix, with using 'getEmojiNameByUnicode' from 'EmojiUtils' 

With this in mind, did it really wasting the effort here?

**Comment by studentofcoding** [comment] 2023-09-06 03:34
> Apologies in advance if I'm not aligned with anyone's opinion.
> 
> 
> I personally don't find this issue valuable to fix since it's not something a user will do in most cases. 
> 
> I'd say if we keep on fixing such bugs saying simple or small then we will end up with not utilising available resources (C++ & internal team time, then testing team time and of course money is another player in the game).
> 
> Since we already reduced bounty price to make open source sustainable for long run.

Thats totally ok, and I understand you POV, especially for Issue after the price reduction is announced

But in this case, 1. Its not a part of price reduction, and 2. Its a still a valid bug, and The solution is simple. Its just dont fair for external contributor, to close and change the procedure middle way dont you think?

On another aspect, I think I and @bernhardoj will understand if this issue are decreased to half ($500) as we also have a mechanism for low-priority bug

**Comment by studentofcoding** [comment] 2023-09-06 03:35
I'll wait for Internal Team to shed a light on this

**Comment by marcaaron** [comment] 2023-09-06 19:52
I'll defer to @sobitneupane as they should be managing this issue and selecting a proposal. The linked proposal has 3 different solutions. There is also various discussion happening and challenges to that proposal.

@sobitneupane Please be decisive, manage this conversation, and offer us a path forward. If the final proposal is clear and looks easy to implement then I will agree to reopen it and get it done.

**Comment by sobitneupane** [comment] 2023-09-07 16:12
I agree with @marcaaron and @sakluger. I don't think the issue carries much value. The reproduction step are very specific and rare. So, my vote is on closing the issue.
