### ISSUE TITLE
Web - Log in - The skeleton is displayed in the concierge chat after log in with a new account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20962] opened 2023-06-17 11:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com
2. Create new gmail account
3. Type Magic code

## Expected Result:
After logging in with a new account, the user enters the concierge chat. The chat has an avatar, name and other information.

## Actual Result:
The skeleton is displayed in the concierge chat after log in with a new account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1a9cfe65-f0fc-4e0a-be1a-11097802d995

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause- Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2023-06-19 14:46
Possibly related to: https://github.com/Expensify/Expensify/issues/291970

**Comment by cristipaval** [comment] 2023-06-19 15:17
I could reproduce this one by creating a new expensifail account and I did some investigation.
It seems to be indeed related to [the issue](https://github.com/Expensify/Expensify/issues/291970) posted by @Beamanator above. The issue occurs always when calling `OpenReport` command with the newly created account, even after signing out/in.
One possibly useful note is that this seems to occur with Concierge chat only. I know that @Beamanator and @puneetlath have plans to improve that query, but for now in order to get this deployed, I wonder if we could always make Concierge by default a known user for everyone 🤷

**Comment by cristipaval** [comment] 2023-06-19 15:30
Ah, here are [the logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227d9c0d4eeef2c31e-VIE%22)+AND+timestamp:[2023-06-19T12:22:15.636Z+TO+2023-06-19T14:22:15.636Z]&index=logs_expensify-022879) from my investigation.

**Comment by luacmartins** [comment] 2023-06-19 19:49
Changes are in Auth, so this is not an App blocker. Removing the labels and making it a daily.

**Comment by cristipaval** [comment] 2023-06-20 20:01
Retested with the [Auth](https://github.com/Expensify/Auth/pull/8141) and [Web-E](https://github.com/Expensify/Web-Expensify/pull/37876) fixes. Closing as it is not reproducible anymore.

**Closed by cristipaval** 2023-06-20 20:01 UTC
Labels: Engineering, Daily
