### ISSUE TITLE
[$500] Expense - Approver gets "Finished" instead of "Next step" after approving report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36419] opened 2024-02-13 15:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.40-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34450

## Action Performed:
Precondition:
- Admin and employee are part of Collect workspace on OD.
- Admin is also the approver in the workspace.
1. Go to staging.new.expensify.com
2. {Employee] Go to workspace chat.
3. [Employee] Create a manual request and submit it.
4. [Admin] Go to workspace chat with employee.
5. [Admin] Open expense report.
6. [Admin] Approve the report.

## Expected Result:
There is a "Next step" with "Waiting for you* to review these expenses." message.

## Actual Result:
It shows "Finished - No further action required!".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1d91533c-fe81-4faa-8d89-f43a1ffca574

![image](https://github.com/Expensify/App/assets/93399543/f8c2f070-bcbb-4d34-932a-b4343e447423)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152a9af1f27fd9d5e</li>
        <li>Upwork Job ID: 1757428613852938240</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2024-02-13 22:16
I don't think this is a bug. [Discussing.](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1707862581207419)

**Comment by joekaufmanexpensify** [comment] 2024-02-14 00:05
Discussed in Slack, and this is not a bug. Closing!

**Closed by joekaufmanexpensify** 2024-02-14 00:05 UTC
Labels: External, Daily, Help Wanted, Bug
