### ISSUE TITLE
[$250] mWeb/Safari - Payment - When tapping "Default Payment" the keyboard is overlapping the field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10533] opened 2022-08-24 15:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10162

## Action Performed:
Pre-Condition: User has a password saved on there device
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Tap on the Profile icon > Payments
4. Tap on a payment method
5. Tap "Make default payment method" > Tap on Password field (A popup about saved password will show)
6. Tap on the bottom "Keyboard" icon to dismiss the popup

## Expected Result:
When tapping "Default Payment" the keyboard is  not overlapping the field

## Actual Result:
When tapping "Default Payment" the keyboard is overlapping the field

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.89.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186455172-d7d1b08f-c9ed-4d70-af81-09968e5fb638.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment] 2022-08-25 13:29
Upwork job [here](https://www.upwork.com/jobs/~0170469f5f55c4df02)

**Comment by mvtglobally** [comment] 2022-08-30 15:26
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment] 2022-09-02 08:02
I also can't reproduce this — can anyone else? If not, I'll close this out.

**Comment by Santhosh-Sellavel** [comment] 2022-09-03 20:59
Unable to reproduce for my self also!

**Closed** 2022-09-09 10:12 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
