### ISSUE TITLE
[$250] mWeb -Error page when open #exfy-roadmap while #new-expensify-feedback is open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43580] opened 2024-06-12 14:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4622123&group_by=cases:section_id&group_id=229066&group_order=asc
**Email or phone of affected tester (no customers):** gocemate+a233@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Logout of New Expensify if logged in
2. Navigate to the following link - https://staging.new.expensify.com/r/6776919265133947
(#new-expensify-feedback)
3. While #new-expensify-feedback is open navigate to the following link - https://staging.new.expensify.com/r/868417741568295
(#exfy-roadmap)

## Expected Result:
#exfy-roadmap room should open and chat history should be visible

## Actual Result:
Error page appears when navigate to #exfy-roadmap link while #new-expensify-feedback is open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/27919dcd-cc46-4ef8-9a1d-bdd99c96eff4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e4f9542b1cde2bc</li>
        <li>Upwork Job ID: 1800937045717141030</li>
        <li>Last Price Increase: 2024-07-17</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-06-12 14:43
@youssef-lr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by tsa321** [comment] 2024-06-12 16:35
Possible offending PR: https://github.com/Expensify/App/pull/43090

**Comment by tsa321** [comment] 2024-06-12 16:37
or maybe https://github.com/Expensify/App/pull/43159

**Comment by youssef-lr** [comment] 2024-06-12 17:03
This is reproducible on production too, removing blocker

![image](https://github.com/Expensify/App/assets/9680864/0a326230-2e54-4cf2-99f8-bf732216efdc)

**Comment by TheGithubDev** [comment] 2024-06-12 20:27
### **Proposal**

### **Re-state the problem that we are trying to solve in this issue:**
When a user is logged out and navigates to the `#exfy-roadmap` public room from the `#new-expensify-feedback` room on the mobile web (mWeb) version of New Expensify, an error page appears instead of displaying the chat history of the `#exfy-roadmap` room.

### **What is the root cause of that problem?**
A state management issue where the application does not handle the transition between public rooms correctly while the user is logged out. This involves incorrect handling of session states or improper routing logic when switching from one public room to another.

### **What changes do you think we should make in order to solve the problem?**
To solve this problem, we need to make sure that the application correctly manages state transitions and routing between public rooms when the user is logged out. Specifically, we should:

1. **Ensure Proper Session Handling:**
- Verify that the session state is correctly managed when switching between public rooms while logged out.

   - - Ensure that the session state is correctly checked and maintained when navigating between rooms.
   ```javascript
   function navigateToRoom(roomId) {
       if (!isUserLoggedIn()) {
           // Ensure session state is correctly managed
           handleSessionStateForLoggedOutUser();
       }
       // Navigate to the room
       navigateTo(roomId);
   }

   function handleSessionStateForLoggedOutUser() {
       // Logic to manage session state for logged-out users
       // This might involve setting appropriate state flags or clearing unnecessary session data
   }
   ```

2. **Fix Routing Logic:**
-  Guarantee that the routing logic correctly handles navigation from one public room to another without causing an error.

   ```javascript
   function navigateTo(roomId) {
       try {
           // Ensure the room ID is valid and exists
           if (isValidRoomId(roomId)) {
               // Perform navigation
               window.location.href = `/r/${roomId}`;
           } else {
               throw new Error("Invalid room ID");
           }
       } catch (error) {
           console.error("Navigation error:", error);
           showErrorPage(); // Show error page if navigation fails
       }
   }

   function isValidRoomId(roomId) {
       // Logic to check if the room ID is valid
       return true; // Placeholder - replace with actual validation logic
   }
   ```

### **Any Alternative Solutions Explored?**(Optional)**
1. **Implement Room Preloading:**
- We can preload room data to ensure smooth transitions between rooms, especially when the user is logged out.
2. **Use Client-Side Routing:**
- Client-side routing to handle room transitions more smoothly and reduce the risk of encountering an error page.

**Comment by rushatgabhane** [comment] 2024-06-16 11:45
@TheGithubDev thank you for your proposal. 

> A state management issue where the application does not handle the transition between public rooms correctly while the user is logged out. This involves incorrect handling of session states or improper routing logic when switching from one public room to another.

I like what you're thinking but could you please explain the **root cause** in detail? Where exactly is the _incorrect_ session or routing logic? Can you please explain it in detail with the help of an example if needed. You can also link code where this problem is happening

**Comment by tsa321** [comment] 2024-06-16 14:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Public room Error page when open url to #exfy-roadmap report, while #new-expensify-feedback is open

### What is the root cause of that problem?

When Opening `#exfy-roadmap` report page, the request took long time to complete the request. When user open it by url, the pusher already authenticated and already subscribe to user channel even though the open report for that room isn't completed yet. then there is Pusher event received with lastUpdateID, this pusher data is just an update so it is really small data, then when OpenReport Completed the lastUpdateID is the same as the pusher event. this will make onyxUpdate won't run because lastUpdateID is same:

https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/actions/OnyxUpdates.ts#L85-L86

But the complete data is stored in `OpenReport` server response and it is not updated by onyxupdatemanager.
Here is some ss from log:

### What changes do you think we should make in order to solve the problem?

We need to make the `authenticatePusher` http request queue on `SequentialQueue`. So it will authenticate only when OpenReport is completed. The pusher authenticate is in here:

https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/actions/Session/index.ts#L751-L752

In `makeRequestWithSideEffects`:

https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/API/index.ts#L159-L160

we add  parameter `shouldBeSequential`, then adjust the return value:
```javascript
...
if (shouldBeSequential) {
    return SequentialQueue.waitForIdle().then(() => Request.processWithMiddleware(request));
}

return Request.processWithMiddleware(request);    
```

**Comment by rushatgabhane** [comment] 2024-06-16 14:52
@tsa321 could you please attach the log screenshot that you've mentioned

**Comment by tsa321** [comment] 2024-06-16 15:01
@rushatgabhane 

Here is some ss from log:

![full_box](https://github.com/Expensify/App/assets/114975543/c48ba0f3-cd6a-4945-88fc-a8ab077f4541)

Onyx data:

![onyxofreport](https://github.com/Expensify/App/assets/114975543/d413a5f6-0752-447f-8479-002d349ee35b)

**Comment by rushatgabhane** [comment] 2024-06-19 16:26
@tsa321 i like your analysis. One Q: how do you think waiting for SequentialQueue to be idle before we authenticate pusher will impact a user that's signed in?

**Comment by tsa321** [comment] 2024-06-21 13:23
@rushatgabhane After further investigation:

1. The pusher event is triggered by `User.subscribeToUserEvents()` (multiple event pusher).
2. The bug also occurs for signed-in users, so we cannot delay `subscribeToUserEvents` or `Pusher.authenticate`.
3. I believe the bug is caused by the following sequence:
   - After user authenticated (second visit to a public room will make user authenticated / an Auth token is present in Onyx)
   - OpenReport is requested to the server.
   - The server adds the user's account ID to the participant list of the report.
   - This change in the participant list triggers a pusher event from the server .
   - The pusher event is received by the user before the OpenReport response.
   - Onyx updates based on the pusher data, setting `lastUpdateID` to the latest value.
   - When the OpenReport request completes, it has the same `lastUpdateID` as the pusher data, causing the OnyxData from the OpenReport to be ignored.


The solutions for this issue could be:
1. Store the previous Onyx update, and if the lastUpdateID is the same, compare the newest received Onyx update with the last stored update. Then, apply the Onyx update to the differences.

2. Make sequential Onyx updates between API write requests and pusher data. If an API write request is loading and pusher data arrives, we must first finish the Onyx updates of the API request, then continue with the pusher update.

3. Handle the logic in Report Screen: if the OpenReport completed and there is no error response from server, retry the OpenReport request.

**Comment by tsa321** [comment] 2024-06-22 01:32
@rushatgabhane delaying authenticatePusher cannot fix this issue, because:

https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L208-L214

`User.subscribeToUserEvents()` is executed first, before OpenReport.

I believe a good solution is to wait for OpenApp to complete before calling `subscribeToUserEvents()`. What do you think?

**Comment by tsa321** [comment] 2024-06-22 06:22
If we want to handle it in report screen, the code could be:

```javascript
useEffect(() => {
    if (!reportMetadata.isLoadingInitialReportActions && !report.reportID && reportActions.length > 0 && retryCount.current < maxOpenReportRetries) {
        retryCount.current += 1;
        fetchReportIfNeeded()
    }
}, [reportMetadata.isLoadingInitialReportActions]);
```

then in:

https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/pages/home/ReportScreen.tsx#L398-L403

we change the first condition into :
```javascript
(!wasReportAccessibleRef.current && !firstRenderRef.current && !report.reportID && !isOptimisticDelete && !reportMetadata?.isLoadingInitialReportActions && !userLeavingStatus && retryCount.current < maxOpenReportRetries)

```

**Comment by johncschuster** [comment] 2024-06-24 16:27
@rushatgabhane, can we get an update on this one? Thank you!

**Comment by rushatgabhane** [comment] 2024-06-26 00:42
@tsa321 thanks again. My main concern with delaying the subscription to pusher events is that an authenticated user would have to wait for OpenApp API call to complete before receiving new messages. This will make the app feel really slow

**Comment by tsa321** [comment] 2024-06-26 17:16
@rushatgabhane

> Wait for OpenApp() to complete before calling User.subscribeToUserEvents(), but do this only if the user is anonymous.

Yes, this could work for an anonymous user. However, this bug also occurs with authenticated users if they haven't visited the room before. (The bug happens on the first visit by entering a URL in the URL bar; if the user clicks a link in chat, the bug doesn't occur.)

**Comment by rushatgabhane** [comment] 2024-06-27 19:42
okayy, in that case we should go for the retry solution

**Comment by rushatgabhane** [comment] 2024-06-27 19:43
@tsa321 what is the value of maxOpenReportRetries and how will we decide that?

**Comment by tsa321** [comment] 2024-06-27 22:20
@rushatgabhane for this issue, 1 retry is fine

**Comment by johncschuster** [comment] 2024-07-01 21:11
@rushatgabhane did you see [this response](https://github.com/Expensify/App/issues/43580#issuecomment-2195761084)? Do you need anything else?

**Comment by rushatgabhane** [comment] 2024-07-01 21:13
@johncschuster the proposed fix will negativity impact performance of opening the app. So I'm not comfortable with going with it

@tsa321

**Comment by rushatgabhane** [comment] 2024-07-01 21:14
@tsa321 has a solution that involves retrying but that looks like a hack to me

**Comment by mvtglobally** [comment] 2024-07-03 14:37
Issue not reproducible during KI retests. (First week)

**Comment by tsa321** [comment] 2024-07-04 01:26
@rushatgabhane I think the simple solution is to change the comparison in here:

https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/actions/OnyxUpdates.ts#L85-L86

from `<= lastUpdateIDAppliedToClient` to `< lastUpdateIDAppliedToClient`

**Comment by rushatgabhane** [comment] 2024-07-08 19:41
@tsa321 in the existing code, do you know why an onyx update is applied even if updateID is same? Because I'm concered about any regression that might arise

**Comment by tsa321** [comment] 2024-07-09 00:08
@rushatgabhane Since the Onyx update for HTTPS occurs within `applyHTTPSOnyxUpdates` and considering the WRITE API operates sequentially, I believe changing the comparison from `<=` to `<` will not cause any regression.

**Comment by johncschuster** [comment] 2024-07-12 20:14
@rushatgabhane / @youssef-lr do you believe this is still an issue? I noticed @mvtglobally was unable to reproduce the behavior [here](https://github.com/Expensify/App/issues/43580#issuecomment-2206332933). How about we retest this one more time, and if it doesn't persist, we close it?

**Comment by johncschuster** [comment] 2024-07-15 22:00
Waiting on a retest. I'll ping the QA room for that.

**Comment by mvtglobally** [comment] 2024-07-16 14:26
Error page appears when navigate to #exfy-roadmap link while #new-expensify-feedback is open 

https://github.com/user-attachments/assets/722c6c74-47e4-4c14-a3de-a9fc0769ac2a

**Comment by johncschuster** [comment] 2024-07-18 21:30
Getting a sense check on the priority of this issue [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1721338104794599)

**Comment by johncschuster** [comment] 2024-07-22 21:22
We're going to close this for now.

**Closed by johncschuster** 2024-07-22 21:22 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug, retest-weekly
