### ISSUE TITLE
[$500] Web - Public room - @hidden mention reveals user name once the mention is clicked on anonymously 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31117] opened 2023-11-09 12:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out if logged in.
2. Navigate to https://staging.new.expensify.com/r/2376199970894587
which has user mentions in the chat.
3. Click on @hidden.
4. Close user profile.

## Expected Result:
@hidden mention will stay hidden.

## Actual Result:
@hidden mention reveals the user name once it is clicked on.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e61d9cbd-05a3-4eb8-9722-37095aa933e5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012db5d33ec09672ef</li>
        <li>Upwork Job ID: 1722597145489809408</li>
        <li>Last Price Increase: 2023-11-09</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-11-09 13:16
Doesn't seem to be reproducible on latest dev

**Comment by s-alves10** [comment] 2023-11-09 13:31
This looks like a backend issue. `OpenPublicProfilePage` API returns a personal detail data for anonymous user

**Comment by s77rt** [comment] 2023-11-09 21:22
I'm not sure what should be the expected behavior here. I have asked on Slack https://expensify.slack.com/archives/C01GTK53T8Q/p1699564909001019

**Comment by s77rt** [comment] 2023-11-10 00:55
Per the above slack discussion this is not a bug. We can close this one. cc @laurenreidexpensify

**Closed** 2023-11-10 09:16 UTC
Labels: External, Daily, Help Wanted, Bug
