### ISSUE TITLE
[$1000] Web - Chat - Second workspace created under Price is displayed in OldDot after refresh the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13798] opened 2022-12-22 20:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing the PR** https://github.com/Expensify/App/pull/13675

## Action Performed:
1. Log into an account on oldDot and create a new Free policy
2. Confirm you're automatically logged into newDot as that user
3. Log out of the account on NewDot
4. Back in OldDot, click on the name of the free policy you created in step 1
5. Confirm you're logged back into newDot and that you land on the workspace page
6. Navigate to the /pricing page on oldDot and selected Free
7. Confirm you're logged back into newDot and that you land on the workspace page of a new workspace
8. Back to OldDot

## Expected Result:
Second WORKSPACE created under Price is displayed in OldDot without refresh the page

## Actual Result:
Second WORKSPACE created under Price is displayed in OldDot after refresh the page/
Also create a new Free policy in OldDot - the chat with users is not loaded.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Web / Chrome 

**Version Number:** 1.2.43.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209223525-ccb13f5c-26e8-4cf5-acdf-104cc664d2b5.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015b79072ab719e49a</li>
        <li>Upwork Job ID: 1606226819550310400</li>
        <li>Last Price Increase: 2022-12-23</li>
    </ul>
</details>

**Comment by Prince-Mendiratta** [comment] 2022-12-23 10:40
# Proposal
I was able to reproduce the issue. The steps involving singing out on newDot are unnecessary, any new workspace created by using the button on the `/pricing` will cause the oldDot to not render the latest changes without a refresh.

If the new workspace is instead created by using the New Policy button on the `/admin_policies` page, a new tab opens with the newDot and the oldDot page automatically refreshes itself after a few seconds. This leads to the latest workspace being displayed in the Policy page.

## Cause
The buttons on the `/pricing` page do not trigger the automatic refresh unlike their counterparts on the `/admin_policies` page.

I'm a first time contributor so still figuring out my way around the code. I'm not sure how I can get access to the code for the oldDot but a solution I can hypothesize is -

## Solution
Any WS created using the buttons on the `/pricing` should trigger the automatic refresh on the oldDot.
Some pointers on dealing with the oldDot repository and I can send a PR with the fix. I've already sent a mail for the invite to Slack channels, awaiting a reply.

**Comment by marcaaron** [comment] 2022-12-23 18:09
Please do not use abbreviations like "WS" to refer to things like "workspace".

I think this must be internal since contributors do not have access to OldDot.

**Comment by MonilBhavsar** [comment] 2022-12-27 06:43
Looking

**Comment by MonilBhavsar** [comment] 2023-01-04 05:00
The linked PR was deployed last week, we can close this issue.
The issue was handled internally, so no payment is required

**Closed by MonilBhavsar** 2023-01-04 05:00 UTC
Labels: Reviewing, Daily, Internal, Bug
