### ISSUE TITLE
[HOLD for payment 2023-12-13] [$1000] Deeplink -  FAB menu briefly shown when navigate to concierge deeplink with new account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30021] opened 2023-10-19 20:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out of the ND app
2. Go to https://staging.new.expensify.com/concierge
3. Log in with a new account

## Expected Result:
Concierge chat is opened, and the FAB menu is not displayed

## Actual Result:
The FAB menu is briefly displayed when navigating to the concierge chat. The FAB icon is displayed as "x" instead of "+"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/48f7aa04-93a2-413d-bee7-8336d13d24e3

https://github.com/Expensify/App/assets/78819774/587ea9f8-a44d-477a-a619-2b91458f5943

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01277cf9c667bd137d</li>
        <li>Upwork Job ID: 1715096447474085888</li>
        <li>Last Price Increase: 2023-11-20</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27768526</li>
<li>dukenv0307 | Contributor | 27768530</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lakchote</details>

**Comment by abzokhattab** [comment] 2023-10-20 00:52
not able to reproduce on ios-mweb  ![image](https://github.com/Expensify/App/assets/59809993/8cf6dc57-c7d1-48db-ad5b-97a0434c937c)

**Comment by jjcoffee** [comment] 2023-10-20 08:47
@abzokhattab The FAB is displaying open in your screenshot, which it shouldn't be.

**Comment by kadiealexander** [comment] 2023-10-24 04:26
@jjcoffee any thoughts on the proposals above?

**Comment by jjcoffee** [comment] 2023-10-26 13:36
Neither of the proposals explain why the FAB only shows briefly. Also why is this only happening for the concierge chat (if that's actually the case)?

**Comment by kadiealexander** [comment] 2023-10-30 04:54
Not overdue, get your proposals in!

**Comment by jjcoffee** [comment] 2023-11-01 15:30
@ishpaul777 
> as a new user there is no chats a user a can deeplink to

Not technically true, as you could start a chat with a new user, then login as that user and there'd be a chat there.

Look forward to your update @dukenv0307!

**Comment by rojiphil** [comment] 2023-11-02 08:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The FAB menu either keeps showing up or is shown briefly when a new account signs-in via deep-link to concierge view. This is the problem we are trying to solve here. 

### What is the root cause of that problem?

When the concierge page is focused after successful sign-in, we navigate back to `Home` screen [here](https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/pages/ConciergePage.js#L36) before loading the concierge report. This was done to pop the concierge utility page before loading the concierge report. However, as a consequence of this, the FAB welcome popover also get displayed for a new account. 

### What changes do you think we should make in order to solve the problem?

To solve the problem, we can prevent going back to `Home` screen during navigation to the concierge page. However, this would mean that we still need to pop the concierge utility page. This can be done as follows:

1) Prevent going back to `Home` screen by removing the following line [here](https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/pages/ConciergePage.js#L36) 

`Navigation.goBack(ROUTES.HOME);`

2) Since we call `navigateToConciergeChat` [here](https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/pages/ConciergePage.js#L37), we can replace the `concierge` screen if the current active route is referring to the concierge route.  
We can do like this [here](https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/libs/actions/Report.js#L1527)

        Navigation.getActiveRoute() === `/${ROUTES.CONCIERGE}`
            ? Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(conciergeChatReportID), CONST.NAVIGATION.TYPE.FORCED_UP)
            : Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(conciergeChatReportID));

3) Further, we open report from deep link by calling `openReportFromDeepLink` [here](https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/Expensify.js#L171) and [here](https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/Expensify.js#L177). This will trigger `navigateToConciergeChat` [here](https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/libs/actions/Report.js#L2000). Since `ignoreConciergeReportID` is set to true, this will trigger opening the concierge using concierge email [here](https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/libs/actions/Report.js#L1524C13-L1524C36) even when the current route is not concierge. This is redundant and can be removed as the Concierge page will handle navigation due to `/concierge` path . This will also prevent the concierge root to be unnecessarily added to the navigation history. 
i.e. we can remove the following line [here](https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/libs/actions/Report.js#L2000) 

                navigateToConciergeChat(true);


### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2023-11-02 10:24
## Proposal

[Updated](https://github.com/Expensify/App/issues/30021#issuecomment-1790259789)

@jjcoffee 
Updated the solution step 2 as I had missed some information to add.
Do let me know your thoughts on the proposal.

**Comment by jjcoffee** [comment] 2023-11-06 16:04
Reviewing tomorrow!

**Comment by jjcoffee** [comment] 2023-11-07 15:47
Sorry will have to push the review to tomorrow.

**Comment by jjcoffee** [comment] 2023-11-08 15:55
Hmm can't reproduce on staging anymore, can you guys still reproduce? @rojiphil @dukenv0307

**Comment by rojiphil** [comment] 2023-11-09 04:58
> Hmm can't reproduce on staging anymore, can you guys still reproduce?

@jjcoffee Yes. I can reproduce this on the latest main. 

https://github.com/Expensify/App/assets/3004659/50cb5a4f-9ac9-4713-8b03-00b9958d5dd1

**Comment by rojiphil** [comment] 2023-11-10 12:05
> Yes. I can reproduce this on the latest main.

@jjcoffee 
Did you get a chance to reproduce this? 
Also, curious to know your thoughts on the [proposal here](https://github.com/Expensify/App/issues/30021#issuecomment-1790259789)

**Comment by jjcoffee** [comment] 2023-11-10 16:32
I'm curious why this appears to only be happening on small screens (if that's definitely the case). Can either of you address that in your proposals?

**Comment by rojiphil** [comment] 2023-11-13 10:50
> I'm curious why this appears to only be happening on small screens (if that's definitely the case). Can either of you address that in your proposals?

@jjcoffee Am looking into this. Will share the updates in a few hours.

**Comment by jjcoffee** [comment] 2023-11-13 16:38
@dukenv0307 Oh yes, that makes sense thanks! 

One thing I'm wondering here is what we actually expect once we navigate back from the concierge chat. Should the create menu show as open? Or does it make sense to keep it hidden since we've already navigated directly to a chat? As far as I can tell your [proposal](https://github.com/Expensify/App/issues/30021#issuecomment-1773112414) @dukenv0307 will still show the create menu after navigating back. Unsure about @ishpaul777 and @rojiphil's proposals.

**Comment by wildan-m** [comment] 2023-11-16 04:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

FAB menu briefly shown when navigate to concierge deeplink

### What is the root cause of that problem?

`Welcome.show` triggerred inside sidebar, sidebar is loaded in ROUTEs.HOME and initialRoute (ROUTES.HOME) will always loaded even when we deeplinked to other screens

### What changes do you think we should make in order to solve the problem?

We can wait at least until the concierge report successfully created. If we need to show the FAB when user getback to home screen, then we can also check `props.isFocused` we can add this check to `FloatingActionButtonAndPopover` useEffect: 

```
        if (_.isEmpty(props.chatReports) || !props.isFocused)
        {
            return;
        }
```

change dependency to 

```
}, [props.isLoading, props.isFocused]);
```

`chatReports` contain `ONYXKEYS.COLLECTION.REPORT` data.

What is the advantage of this implementation?

we are not immediately set `ONYXKEYS.NVP_IS_FIRST_TIME_NEW_EXPENSIFY_USER` to true, so if the user closed the apps when loaded the concierge screen, it will still get the welcome behaviour when user re-opened the app

Branch to test [here](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/30021-deeplink-welcome?expand=1).

### What alternative solutions did you explore? (Optional)

**Comment by kadiealexander** [comment] 2023-11-16 06:51
Not overdue, @jjcoffee please take a look at the proposal and comment above :)

**Comment by rojiphil** [comment] 2023-11-16 07:50
## Proposal

[Updated](https://github.com/Expensify/App/issues/30021#issuecomment-1790259789)

@jjcoffee
Also, please have a look at my revised proposal. Thanks.

**Comment by jjcoffee** [comment] 2023-11-16 17:00
Just wanting to clarify the expected behaviour, so opening up for a broader consensus on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1700153847406089). Feel free to chime in/vote there!

**Comment by jjcoffee** [comment] 2023-11-17 16:39
I'll just see if we get any more feedback (it's currently tied) over the weekend and come back to this Monday.

**Comment by jjcoffee** [comment] 2023-11-20 15:04
Haha well, looks like we're still on a 50:50 split on Slack about this, but I think we can just go ahead with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/30021#issuecomment-1773112414) here. The RCA is correct and sufficiently detailed, and the solution is nice and straight forward. In comparison @rojiphil's [proposal](https://github.com/Expensify/App/issues/30021#issuecomment-1790259789) feels a bit over-engineered when we can have a much simpler fix.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment] 2023-11-20 15:05
@lakchote We were trying to settle on the right behaviour once we navigate back from the concierge chat, i.e. should the create menu show as open, or does it make sense to keep it hidden since we've already navigated directly to a chat. Let me know if you have any thoughts, otherwise I think we can just go with what @dukenv0307 has in their proposal (open once navigating back from the chat).

**Comment by lakchote** [comment] 2023-11-21 13:36
@jjcoffee In my opinion, we shoud show the FAB but _only_ once?

It's important to clearly communicate the value of the app, and I think by showing it once to the user is a good idea to convert them to paid down the line.

If we did it more than once, it could be frustrating.

@dukenv0307's proposal LGTM 👍

**Comment by mvtglobally** [comment] 2023-11-23 05:25
Issue not reproducible during KI retests. (First week)

**Comment by jjcoffee** [comment] 2023-12-07 16:17
Deployed to production Dec 6, not sure what happened to the automation! @kadiealexander Can you update the title and add the `Awaiting Payment` label?

**Comment by sonialiap** [comment] 2023-12-07 16:36
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@jjcoffee] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@jjcoffee] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@jjcoffee] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@jjcoffee] Determine if we should create a regression test for this bug.
- [ ] [@jjcoffee] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment] 2023-12-15 04:53
Everyone is paid!

**Closed by kadiealexander** 2023-12-15 04:53 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
