### ISSUE TITLE
[$1000] Task long assignee name will push the caret to the edge of the view

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#20012] opened 2023-06-01 21:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Assign Task
2. Assign a user that has a really long name
3. Verify in the 'Share somewhere' section the caret is pushed to the edge of the view 

## Expected Result:
Describe what you think should've happened
The caret should not have been pushed to the edge
The assignee and share somewhere should be bolded

## Actual Result:
<img width="376" alt="Screenshot 2023-06-01 at 2 29 17 PM" src="https://github.com/Expensify/App/assets/30609178/727711e0-15bf-4111-b728-f9e5e15617ec">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df5c7345faa9fded</li>
        <li>Upwork Job ID: 1664388453539151872</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2023-06-01 21:49
We should also be bolding the assignee name in the selector but will update when I get more details from https://expensify.slack.com/archives/C04QEB4MJEQ/p1685378889159569

**Comment by sethraj14** [comment] 2023-06-01 22:14
@thienlnam Unable to reproduce the issue, can you explain the steps once again and give the details of the platform too.

**Comment by sethraj14** [comment] 2023-06-01 22:33
@thienlnam 
Could not reproduce the long assignee name issue on Chrome. Proposing for this - The assignee and share somewhere should be bold

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The assignee and share somewhere should be bold

### What is the root cause of that problem?

Not Passing correct styles

### What changes do you think we should make in order to solve the problem?
Passing this style to for share somewhere title will make it bold in this [file](https://github.com/Expensify/App/blob/f4f89a0cac5b07265e82c85e69e48720997ba84b/src/components/TaskSelectorLink.js#L55) - 

`   const displayNameStyle = StyleUtils.combineStyles(styles.optionDisplayName, styles.pre, props.isShareDestination ? styles.textStrong : styles.textNormal);`

Passing `styles.textStrong` will make the assignee name bold - 

`<Text style={[styles.label, styles.textLabelSupporting,props.isShareDestination ?  styles.textStrong: styles.textNormal]}>{props.translate(props.label)}</Text>`

![Screenshot 2023-06-02 at 4 01 33 AM](https://github.com/Expensify/App/assets/14844259/b24ee2e8-84ef-4d50-956d-80220ac1bcec)

### What alternative solutions did you explore? (Optional)

**Comment by thienlnam** [comment] 2023-06-01 23:27
Good question, asking in the original thread about the device as I cannot reproduce it now either

**Comment by laurenreidexpensify** [comment] 2023-06-02 11:32
oh rad, nice spot @dhairyasenjaliya. I'm gonna close this - @thienlnam pls reopen if you think it's a different issue that still needs to be addressed 👍

**Closed by laurenreidexpensify** 2023-06-02 11:32 UTC
Labels: External, Daily, Help Wanted, Bug
