### ISSUE TITLE
Hyperlinks are not clickable on IOS and android platforms - Reported by @chauchausoup

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11276] opened 2022-09-26 05:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to IOS/Android app
2. Enter any suitable hyperlink (eg: [google.com](http://google.com/))
3. Tap on just entered hyperlink

## Expected Result:
Hyperlink should have opened a popup to respective website

## Actual Result:
Hyperlink is not clickable

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/192198294-73196d58-7a43-4621-9d17-f0aaf20ce431.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @chauchausoup
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662428762050009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chauchausoup** [comment] 2022-09-26 05:19
Now I am testing the issue and I can see that production IOS app is showing the issue as above screen record but the emulator version on both app are not replicating the issue.

**Comment by Christinadobrzyn** [comment] 2022-10-19 04:21
I can't replicate this on the desktop app (Version 1.2.11-4 (1.2.11-4) or iOS mobile app (v1.2.15). I don't know if this is still an issue. Going to send to eng to get their take. 

Example of what I see on mobile app: 

<img src="https://user-images.githubusercontent.com/51066321/196596549-0bff453c-a4f6-4a5c-a8c8-05d5fb9dbea5.gif" width="250" height="450" />

**Comment by cristipaval** [comment] 2022-10-21 13:12
I can't reproduce it. Tested on we, desktop, chrome on Android, Android native, safari on iOS, iOS native.

**Comment by cristipaval** [comment] 2022-10-21 13:13
I think we can close the issue since the last reproduction happened 25 days ago.

**Comment by chauchausoup** [comment] 2022-10-21 14:09
I agree. Its not reproducible now.

**Closed** 2022-10-24 09:37 UTC
Labels: Engineering, Daily, Needs Reproduction, Overdue, Bug
