### ISSUE TITLE
[$250] The intro text on More Features stays fixed when it should scroll with the page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49075] opened 2024-09-12 12:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dubielzyk-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726115971343019

## Action Performed:
1. Go to Profile -> Workspace
2. Click a workspace -> More features
3. Observe the intro text
## Expected Result:
The intro text that says: "use the toggles below to enable..."
is fixed when you scroll the page
## Actual Result:
Intro text should be attached to the content of the page and scroll with the rest of the cards. Also the padding on the right of the text missing. The text is too close to the edge:
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b1e78d00-750c-4742-849c-45f0a5bb78ad

![CleanShot 2024-09-12 at 14 41 24@2x](https://github.com/user-attachments/assets/f96fe7d1-25bf-45c8-9dd3-418e70d33207)

https://github.com/user-attachments/assets/c84e130f-baf1-4dd0-a176-e88bf11e413a

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837165152252710251</li>
        <li>Upwork Job ID: 1837165152252710251</li>
        <li>Last Price Increase: 2024-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104114387</li>
<li>truph01 | Contributor | 104114389</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>

**Comment by ChavdaSachin** [comment] 2024-09-12 12:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The intro text on More Features stays fixed when it should scroll with the page

### What is the root cause of that problem?
- intro is not included in scroll view https://github.com/Expensify/App/blob/9240b03a5224b01e71365898f82960586cfec497/src/pages/workspace/WorkspaceMoreFeaturesPage.tsx#L412-L417
### What changes do you think we should make in order to solve the problem?

- Include intro in scroll view
```js
                <ScrollView contentContainerStyle={styles.pb2}>{sections.map(renderSection)}</ScrollView>

                <Text style={[styles.ph5, styles.mb4, styles.mt3, styles.textSupporting, shouldUseNarrowLayout ? styles.workspaceSectionMobile : styles.workspaceSection]}>
                    {translate('workspace.moreFeatures.subtitle')}
                </Text>
                
```
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ChavdaSachin** [comment] 2024-09-13 08:22
## Proposal
[Updated](https://github.com/Expensify/App/issues/49075#issuecomment-2346177564) added additional changes we should make for more consistent user experience. 

Reference images for proposal
Notice Larger gap between sections on MoreFeaturesPage
|  MoreFeaturesPage  | WorkflowPage |
| ------------- | ------------- |
| <img width="434" alt="Screenshot 2024-09-13 at 1 47 22 PM" src="https://github.com/user-attachments/assets/05687555-7373-4343-a704-f2bec7485bbb">   | <img width="450" alt="Screenshot 2024-09-13 at 1 48 17 PM" src="https://github.com/user-attachments/assets/155ec754-f316-44cb-bdf0-7d3e7677fe00">|

**Comment by abekkala** [comment] 2024-09-16 18:54
@Expensify/design 
I want to confirm that the "expected" above is true: 


> Intro text should be attached to the content of the page and scroll with the rest of the cards. Also the padding on the right of the text missing. The text is too close to the edge.

Should `More Features` scroll with the page or remain fixed at the top?

**Comment by shawnborton** [comment] 2024-09-16 18:56
The More features part should stay fixed.

**Comment by abekkala** [comment] 2024-09-18 19:55
That's what I was assuming
Closing

**Comment by dubielzyk-expensify** [comment] 2024-09-19 03:26
Why are we closing this? Sorry if I missed something, but this issue isn't fixed is it? To clarify the top header shouldn't scroll, but the text below should:

![image](https://github.com/user-attachments/assets/5cf507ac-580d-4153-88b0-e721a3aa898e)

Sorry if I'm missing something though 😅

**Comment by shawnborton** [comment] 2024-09-19 04:13
Agree with Jon, I think this is something we need to fix.

**Comment by abekkala** [comment] 2024-09-20 16:21
OH! I did misunderstand. I thought you meant the **whole** "More Features" part stays fixed!

**Comment by truph01** [comment] 2024-09-21 01:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Intro text should be attached to the content of the page and scroll with the rest of the cards. Also the padding on the right of the text missing. The text is too close to the edge:

### What is the root cause of that problem?
- The intro text is not added to ScrollView:

https://github.com/Expensify/App/blob/04762acb53f446708d6f649cbb6b527abbf72889/src/pages/workspace/WorkspaceMoreFeaturesPage.tsx#L412-L414

### What changes do you think we should make in order to solve the problem?
- We should move the intro text to the ScrollView:

```
                <ScrollView contentContainerStyle={[styles.pb2]}>
                    <Text style={[styles.ph5, styles.mb4, styles.mt3, styles.textSupporting, shouldUseNarrowLayout ? styles.workspaceSectionMobile : styles.workspaceSection]}>
                        {translate('workspace.moreFeatures.subtitle')}
                    </Text>
                    {sections.map(renderSection)}
                </ScrollView>
```

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-09-21 01:14
@dubielzyk-expensify Can you help confirm that: This issue need to be resolved on all platforms, right?

**Comment by suneox** [comment] 2024-09-21 05:36
> @dubielzyk-expensify Can you help confirm that: This issue need to be resolved on all platforms, right?

I think it should be resolved on all platforms, but we should wait for confirmation.

**Comment by dubielzyk-expensify** [comment] 2024-09-23 06:46
Yep. All platforms please

**Comment by suneox** [comment] 2024-09-23 08:13
> Yep. All platforms please

Based on the confirmation @truph01 [proposal](https://github.com/Expensify/App/issues/49075#issuecomment-2364797178)  LGTM. and I believe the issue `The text is too close to the edge` has been fixed in #48565.

🎀 👀 🎀 C+ reviewed

**Comment by suneox** [comment] 2024-09-23 13:52
> @suneox With the selected proposal, the text will scroll in all cases. We only scroll the header text when we're in narrow layouts.

@Nodebrute The expected behavior has been confirmed in [this comment](https://github.com/Expensify/App/issues/49075#issuecomment-2367350911)

**Comment by dubielzyk-expensify** [comment] 2024-09-24 00:36
In the wider layout example is it possible to have the intro text scroll, but not the table header?

**Comment by truph01** [comment] 2024-09-24 00:41
> In the wider layout example is it possible to have the intro text scroll, but not the table header?

@dubielzyk-expensify Could you provide more details? I don't fully understand what you're referring to.

**Comment by dubielzyk-expensify** [comment] 2024-09-24 03:03
My bad. Can we do this?

![CleanShot 2024-09-24 at 13 03 23@2x](https://github.com/user-attachments/assets/ce40dde4-c44c-4c6f-a070-76ff54e77f5b)

**Comment by truph01** [comment] 2024-09-24 03:23
I can fix the 'Name-Status' header, but I’m unable to make the 'Get a better overview ...' text scrollable:

https://github.com/user-attachments/assets/ba3e4547-5917-4b80-93dd-492282d93770

**Comment by truph01** [comment] 2024-09-24 03:32
@dubielzyk-expensify I don't see any similarity between the workspace 'More Features' page and other pages like workspace categories, tags, or taxes. Therefore, there’s no reason to require us to apply the same behavior on the 'More Features' page as on those other pages. 

So I think we just need to apply the changes to all platforms as you mentioned above:

> All platforms please

**Comment by dubielzyk-expensify** [comment] 2024-09-24 03:43
Yeah, I think for the pages with tables, let's just leave them as is for now and proceed with the original bug in this issue.

It's still solvable by making a sticky header table when scrolling, but it requires more work

**Comment by truph01** [comment] 2024-09-24 03:47
@srikarparsi C+ has reviewed [the proposal](https://github.com/Expensify/App/issues/49075#issuecomment-2367510018). All yours!

**Comment by dannymcclain** [comment] 2024-09-24 13:34
>I don't see any similarity between the workspace 'More Features' page and other pages like workspace categories, tags, or taxes. Therefore, there’s no reason to require us to apply the same behavior on the 'More Features' page as on those other pages.

Definitely agree with this so I agree with where you all landed. Make `More features` work how we want it to work and leave the table pages alone for now.

**Comment by srikarparsi** [comment] 2024-09-24 21:55
Cool, sounds good. If we want the intro text to scroll up with the page on all platforms then @truph01's [proposal](https://github.com/Expensify/App/issues/49075#issuecomment-2364797178) looks good to me too

**Comment by truph01** [comment] 2024-09-25 02:34
@suneox [PR](https://github.com/Expensify/App/pull/49679) is ready.

**Comment by suneox** [comment] 2024-10-07 18:56
### Checklist

- [X] [@suneox] The PR that introduced the bug has been identified. Link to the PR: *I don’t think there’s a PR responsible for this issue, as the implementation documents seem to be missing a proper description about scroll behavior for the header*
- [X] [@suneox] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: *N/A*
- [X] [@suneox] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: *N/A*
- [X] [@suneox] Determine if we should create a regression test for this bug. *N/A*

**Comment by abekkala** [comment] 2024-10-11 14:32
### PAYMENT SUMMARY: 

- Fix: @truph01 [OFFER](https://www.upwork.com/nx/wm/offer/104114389)
- PR Review: @suneox [OFFER](https://www.upwork.com/nx/wm/offer/104114387)

**Comment by abekkala** [comment] 2024-10-11 14:33
@truph01 and @suneox payments sent and contracts ended - thank you! 🎉

**Closed by abekkala** 2024-10-11 14:33 UTC
Labels: Reviewing, External, Weekly, Bug
