### ISSUE TITLE
[$250] Workspace - Make workspace name input push to page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29455] opened 2023-10-12 14:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap Workspaces
4. Tap on any Workspace
5. Tap on Workspace name
6. Change Workspace name
7. Select any other currency and without tapping save option, tap app's back button
8. Tap Workspace name

## Expected Result:
As user never tapped save option, on revisit, the changed Workspace name and selected currency should not be displayed

## Actual Result:
On revisit, the changed Workspace name is not shown but selected currency is displayed although user never tapped save option

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/72f0421c-ad37-46cb-a629-a39dd1d7dc5e

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ec5b209f3445160</li>
        <li>Upwork Job ID: 1712522664628527104</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-10-12 18:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Selected currency is shown on revisit without tapping save button
### What is the root cause of that problem?

We recently migrated the currency selection from a `Select` component to push to page method where we have to select a currency from a new page.

In that page we're automatically saving the currency when ever we click on any item here https://github.com/Expensify/App/blob/5bd71f03d1a72416c622c7e6568f1e038ec3043d/src/pages/workspace/WorkspaceSettingsCurrencyPage.js#L71

### What changes do you think we should make in order to solve the problem?

We can use Query Params (navigation params) method to read currency from currency page.

Whenever user clicks on any currency we need to navigate the user to the settings page with the user selected currency then update with the menu option when user clicks on save read from the params.

> We're kind of doing same method with different pages like dob pages etc (mainly modals)



### What alternative solutions did you explore? (Optional)
NA

cc: @mountiny

**Comment by mountiny** [comment] 2023-10-12 21:16
yeah its certainly weird with the Save button there, but I agree, I was also suspicious seeing the report, I will remove the blocker and we can discuss next steps

**Comment by puneetlath** [comment] 2023-10-13 16:33
Hm, @mountiny so do you think we should do anything here? Or just close the issue?

**Comment by mountiny** [comment] 2023-10-15 12:36
I think we should make sure there is a follow up to change the workspace name as push to page as now you have to different types of the form where one requirs you to click  Save and the other one does not.

Then once the Workspace name is push to page we can remove the Save button. If there is an issue for it, we can close it I guess, if not we could use this to track it.

**Comment by puneetlath** [comment] 2023-10-18 00:38
Ok I updated this issue to implement push to page for the workspace name. @b4s36t4 feel free to update your proposal.

**Comment by b4s36t4** [comment] 2023-10-18 07:29
Updated my proposal, thanks :)

**Comment by b4s36t4** [comment] 2023-10-26 14:25
@aimane-chnaif I'm not available for till tmrw. Available from Sat (IST) I'm available. Been sick for few days.

**Comment by puneetlath** [comment] 2023-10-27 14:09
I think $250 is fair here.

**Comment by puneetlath** [comment] 2023-10-31 16:19
@b4s36t4 how's this going?

**Comment by b4s36t4** [comment] 2023-10-31 16:25
@puneetlath I have completed writing the changes, it's just  to take screen recordings. Will do it in sometime night.

**Comment by b4s36t4** [comment] 2023-11-01 19:22
@puneetlath @aimane-chnaif #30733 PR is here. Thanks!!

**Comment by puneetlath** [comment] 2024-02-02 22:25
@b4s36t4 bump! If we don't hear back by Monday, we'll go ahead and re-assign.

**Comment by b4s36t4** [comment] 2024-02-06 04:42
Hey, guys. Sorry been away because of health issues for many days. Been back now will take it up and complete it ASAP. 

Thanks for holding it up🙂.

**Comment by puneetlath** [comment] 2024-02-12 17:53
I'm sorry to hear about your health issues @b4s36t4!

However, it seems like this issue is no longer relevant right? This page has been totally changed and the issue no longer seems to be happening. 

Given that the PR seems to have been abandoned, I'm going to go ahead and close this issue out. Let me know if that's wrong and I've misunderstood anything.

**Closed by puneetlath** 2024-02-12 17:53 UTC
Labels: Reviewing, External, Monthly, Not a priority, Bug
