### ISSUE TITLE
[HOLD for payment 2024-05-02] [VIP-VSB] Thumbnail - Thumbnail of a markdown image flickers

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38819] opened 2024-03-22 17:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Send a markdown image to a user you don’t have a chat history with
2. Navigate to another chat
3. Navigate back to the report

## Expected Result:
Thumbnail of a markdown image shouldn’t flicker

## Actual Result:
Thumbnail of a markdown image flickers

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bd858471-6879-48a9-b7a7-54f4222ae9f3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by kbecciv** [comment] 2024-03-22 17:47
We think that this bug might be related to #vip-vsb

**Comment by situchan** [comment] 2024-03-22 17:49
cc: @kidroca

**Comment by arosiclair** [comment] 2024-03-22 20:42
Looks like a new feature (https://github.com/Expensify/App/pull/37566) so probably doesn't need to be a blocker. cc @kidroca @marcaaron

**Comment by kidroca** [comment] 2024-03-25 11:24
I'm investigating

**Comment by kidroca** [comment] 2024-03-25 20:25
I've traced the bug using git bisect down to 3fbbb19 and https://github.com/Expensify/App/pull/30269

**Comment by strepanier03** [comment] 2024-03-26 22:22
Thank you, @kidroca. 

Should I assign this to you? Based on what I've found in Slack, I'm going to tie this to VIP-VSB.

**Comment by kidroca** [comment] 2024-03-27 07:48
> Thank you, @kidroca. 
> 
> Should I assign this to you?

No, this should be addressed by the pull request that introduced the regression.

**Comment by strepanier03** [comment] 2024-04-12 20:41
Been OoO since last week but catching up on this now.

**Comment by roryabraham** [comment] 2024-04-12 20:49
yeah, on the surface it looks like we're immediately calling `GetOlderActions` when joining the chat, which is causing some loading state to be true, and effectively flashing the whole chat list. I've seen the same thing joining any new chat on dev.

This does seem worth fixing as soon as we can, but without spending more time on it I don't have a good suggestion. Asked for support here: https://expensify.slack.com/archives/C035J5C9FAP/p1712954888419339

**Comment by janicduplessis** [comment] 2024-04-13 16:39
Looking at this!

**Comment by janicduplessis** [comment] 2024-04-13 21:27
I investigated the issue and I’m starting to have a good understanding of what is going on.

The main cause of this is that the list is being remounted because this [listId](https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/pages/home/report/ReportActionsView.tsx#L126) changes. The change happens because the `isLoadingInitialReportActions` dependency changes from false to true then again to false.

When listID changes the whole list is remounted and the ThumbnailImage component has to load the image size asynchronously again which causes the flicker of size. ThumbnailImage defaults to a square image initially when it doesn’t have the real size. Images uploaded via expensify have the real size already available when loaded, but when using a markdown image with some random image url the initial size is not available synchronously and will be loaded when image has done loading.

This is not the root cause of the issue, but it could be good to save a memory cache of url to size so once we loaded an image once it will not flicker when loaded the next time. This would also partially mitigate this issue and also improve the ux when switching between 2 different chats since currently there is always at least 1 flicker independently of fixing the `isLoadingInitialReportActions` bug.

This is where I am currently in my investigation, basically I need to figure out why `isLoadingInitialReportActions` starts as false and then is updated to true, then false again when opening a chat. If that behaviour is correct then we could look to see if it is possible to remove that state from the dependency array of listID. I will post again when I have more progress on this.

**Comment by strepanier03** [comment] 2024-04-15 23:27
Thanks @janicduplessis - I'll continue to follow along.

**Comment by janicduplessis** [comment] 2024-04-19 19:18
Will pickup work on this tomorrow!

**Comment by janicduplessis** [comment] 2024-04-20 19:52
I was not able to reproduce as much flickering, for me it only happens once on chat load, compared with the video where it happens 2+ times. @kbecciv would you be able to test with latest main see if you still get 2+ flickers or maybe something has been improved since then. If you can still repro 2+ flickers I will try to have a look at this too.

We can still reduce flickering significantly by caching the dimensions so the flicker only happens the first time an image is loaded. I implemented this in https://github.com/Expensify/App/pull/40643.

**Comment by jose-valentin-git** [comment] 2024-05-02 04:32
I have checked this issue on Video recording.
My technical apporach: 
  - Implement enhanced caching strategies for image thumbnails to reduce load times and prevent re-rendering flickers. Utilize React Native's built-in caching mechanisms more effectively or integrate a more robust custom caching solution.
  - Modify the lifecycle methods of the image display component to prevent unnecessary re-renders. Employ shouldComponentUpdate or React's PureComponent to ensure components only update when new props affecting the image are received.
  - Ensure state transitions related to chat navigation are handled smoothly, possibly by implementing a global state management solution like Redux or Context API to keep track of image loading states across components.

**Comment by strepanier03** [comment] 2024-05-02 18:02
@janicduplessis @situchan - Can one of you complete the checklist steps below so I can wrap this up?

- [ ] [@janicduplessis / @situchan] Determine if we should create a regression test for this bug.
- [ ] [@janicduplessis / @situchan] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2024-05-07 09:39
I reviewed https://github.com/Expensify/App/pull/40643 PR @strepanier03 Can you please assign me the issue.

**Comment by strepanier03** [comment] 2024-05-08 01:43
Did @situchan also work on this? Do you know @sobitneupane?

**Comment by strepanier03** [comment] 2024-05-09 23:27
@sobitneupane - Can you complete the two @situchan originally?

- [ ] [@janicduplessis / @situchan] Determine if we should create a regression test for this bug.
- [ ]  [@janicduplessis / @situchan] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

Thanks!

**Comment by strepanier03** [comment] 2024-05-09 23:30
I also sent you an offer @sobitneupane, let me know if I need to cancel that if you use Manual Requests normally.

**Comment by marcaaron** [comment] 2024-05-13 19:10
bump @sobitneupane

**Comment by sobitneupane** [comment] 2024-05-14 07:14
**Regression Test Proposal**

1.  Add an image using markdown `![https://hatrabbits.com/wp-content/uploads/2017/01/random.jpg](https://hatrabbits.com/wp-content/uploads/2017/01/random.jpg)`
2.  Reload the page and switch between chats, 
3. Verify that thumbnail of the markdown image doesn't flicker (with an exception of first load/time)

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2024-05-14 07:14
> I also sent you an offer @sobitneupane, let me know if I need to cancel that if you use Manual Requests normally.

@strepanier03 I will request the payment in newDot.

**Comment by strepanier03** [comment] 2024-05-14 22:40
Thanks @sobitneupane - I'll cancel the job in Upwork, finish the reg test, and post the payment summary for your ND request.

**Comment by strepanier03** [comment] 2024-05-14 22:42
Reg test done, job closed in Upwork.

**Comment by strepanier03** [comment] 2024-05-14 22:43
### Payment Summary

- @sobitneupane - $500 via Manual Requests

_Heads up @JmillsExpensify - Request incoming for payment!_

**Closed by strepanier03** 2024-05-14 22:43 UTC
Labels: Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-22 16:51
$500 approved for @sobitneupane
