### ISSUE TITLE
[$500]  IOU - Composer is hidden when opening Distance IOU reports details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36174] opened 2024-02-08 19:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a distance request
2. Open IOU details reports page before map finishes generating or loading

## Expected Result:
Composer shouldn't be hidden and there should be no RBR on LHN

## Actual Result:
Composer is hidden and there is RBR on LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/827a7b44-0284-4a9d-91ac-3c08c77379fe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf8912dca09f5a2e</li>
        <li>Upwork Job ID: 1755689568621125632</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-08 19:59
We think that this bug might be related to [#vip-bills](https://expensify.enterprise.slack.com/archives/CSL3XBCCR)
CC @davidcardoza

**Comment by situchan** [comment] 2024-02-08 20:06
This is known bug and the fix is in progress.

Reproducible on production:

https://github.com/Expensify/App/assets/108292595/2933fd07-d3d9-4cff-a429-fed30f716014

**Comment by dangrous** [comment] 2024-02-08 20:21
@situchan do you have the issue / PR handy for that bug? Thanks!

**Comment by situchan** [comment] 2024-02-08 20:27
> @situchan do you have the issue / PR handy for that bug? Thanks!

@dangrous dupe of https://github.com/Expensify/App/issues/33114

**Comment by situchan** [comment] 2024-02-08 20:28
This is the tip to reproduce:
`go quickly to the transaction thread`

**Comment by situchan** [comment] 2024-02-08 20:29
PR: https://github.com/Expensify/App/pull/35449

**Comment by lanitochka17** [comment] 2024-02-08 20:32
sorry for confusion. Issue is reproducible on Production

![image](https://github.com/Expensify/App/assets/78819774/161c2ec7-5413-4f5a-bb07-50706c92bfa8)

**Comment by dangrous** [comment] 2024-02-08 20:37
Nice! I'll close this then, unless anyone disagrees. Thanks for your quick help @situchan !

**Closed by dangrous** 2024-02-08 20:37 UTC
Labels: External, Engineering, Hourly, Help Wanted, Bug
