### ISSUE TITLE
mweb -  "Unexpected error..." Is thrown when trying to split bill with an account that has a task chat history

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22158] opened 2023-07-04 10:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging new dot
2. Click on + icon and select split bill
3. Enter amount and click next
4. Enter an account where the user had previously assigned a task to and also had a chat history and click on split bill
5. Observe an "Unexpected error is thrown.."

## Expected Result:
 No error should be thrown

## Actual Result:
 "Unexpected error.." is thrown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b95adad0-6187-443c-8f9b-8e9e37c64a50

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688317432530109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f07b9a46fa6b68b</li>
        <li>Upwork Job ID: 1680962948949823488</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2023-07-11 18:25
Running behind, getting to this tomorrow

**Comment by muttmuure** [comment] 2023-07-14 14:06
Still not had time

**Comment by muttmuure** [comment] 2023-07-17 15:24
Wow this seems super broken

**Comment by Julesssss** [comment] 2023-07-19 11:55
Yeah nice find, looks like a dupe of https://github.com/Expensify/App/issues/22031

**Comment by muttmuure** [comment] 2023-07-19 12:16
Closing in favour of https://github.com/Expensify/App/issues/22031

**Closed by muttmuure** 2023-07-19 12:16 UTC
Labels: Daily, Internal, Needs Reproduction, Bug
