### ISSUE TITLE
[Paid] Android - IOU - App crashes when adding a receipt from gallery in confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32865] opened 2023-12-11 21:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Go to 1:1 DM > + > Request money
3. Enter amount and proceed to confirmation page
4. Tap 3-dot menu > Add receipt
5. Upload a receipt from gallery

## Expected Result:
App does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/422a8b6d-5124-4062-9d34-2e1b124242f7

[logs.txt](https://github.com/Expensify/App/files/13641022/logs.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by luacmartins** [comment] 2023-12-12 00:26
@mkhutornyi are you able to work on a PR within the next hour?

**Comment by luacmartins** [comment] 2023-12-12 00:30
Cool, assigned you to the issue. Let me know when the PR is ready

**Comment by luacmartins** [comment] 2023-12-12 22:30
Tested in staging. This is a pass.

**Comment by strepanier03** [comment] 2024-01-04 03:42
Been OoO but back in now. Working on payments.

**Comment by strepanier03** [comment] 2024-01-04 03:50
Regression test made and bug checklist is done. 

I've sent offers to both @parasharrajat and @mkhutornyi. I'll check back in tomorrow.

**Comment by strepanier03** [comment] 2024-01-05 00:52
Waiting for offers to be accepted and then I'll pay out. I'll check again tomorrow.

**Comment by strepanier03** [comment] 2024-01-09 04:37
Got it, will do that shortly @parasharrajat.

**Comment by strepanier03** [comment] 2024-01-09 04:57
@mkhutornyi - I've paid you in Upwork and closed the contract.

**Comment by strepanier03** [comment] 2024-01-09 04:57
### Payment Summary

- Contributor - @mkhutornyi paid via Upwork
- C+ - @parasharrajat via Manual Request

@JmillsExpensify  - head's up, a request is incoming from Rajat.

**Comment by JmillsExpensify** [comment] 2024-05-19 16:38
Re-opening so that I can get payment summaries with an amount.

**Comment by strepanier03** [comment] 2024-05-20 21:46
Oops, sorry about that, don't know how I managed to forget that 🤦‍♀️. Updated the payment summary [above](https://github.com/Expensify/App/issues/32865#issuecomment-1882414361) with amounts.

**Comment by luacmartins** [comment] 2024-05-27 15:33
Seems like we can close this again since the payment summary was updated. Please reopen if we're still missing something.

**Closed by luacmartins** 2024-05-27 15:33 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-31 03:37
$500 approved for @parasharrajat
