### ISSUE TITLE
[Awaiting checklist] [$250] Distance Request -"Distance" option does not appear in QAB for a gmail account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40790] opened 2024-04-23 13:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/39413
## Action Performed:
1. Open the testing app and login with a gmail account
2. Submit an expense request using Distance request
3. Click on FAB menu and select "Record distance" from the QAB

## Expected Result:
User should be navigated to the Distance tab

## Actual Result:
No Distance tab / user is directed to the Manual request tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2cfd3253-d0a3-4062-9456-d75c602447b8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f4eac573fdf1cb2</li>
        <li>Upwork Job ID: 1783176218489765888</li>
        <li>Last Price Increase: 2024-05-01</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by lanitochka17** [comment] 2024-04-23 13:00
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-23 13:01
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment] 2024-04-24 17:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user is able to do P2P distance request even though they're not in `P2PDistanceRequests` beta.

### What is the root cause of that problem?
The problem here is not that "Distance" does not show, it's expected that it will not show if the user is not in `P2PDistanceRequests` beta (the logic is [here](https://github.com/Expensify/App/blob/c90b46ec8d3e81c374163f774b32f874d18ba707/src/pages/iou/request/IOURequestStartPage.tsx#L100)).

The issue is the user's able to do P2P distance request in the first place, even though they're not in `P2PDistanceRequests` beta. Once they did the P2P distance request, of course the "Distance" tab will not show when they attempt again, because the user indeed is not in the `P2PDistanceRequests` beta.

> The issue is the user's able to do P2P distance request in the first place

The root cause of this is the user can still see the `personalDetails` options that contain individual users, because we don't have any restriction [here](https://github.com/Expensify/App/blob/5b1c240f69098f07fbbd7459235edcfc8f936111/src/libs/OptionsListUtils.ts#L1732) if the `includeP2P` is `false`. As we can see, we have such restriction [here](https://github.com/Expensify/App/blob/5b1c240f69098f07fbbd7459235edcfc8f936111/src/libs/OptionsListUtils.ts#L1699), that's why we don't see any 1-1 chat when trying to do "Distance" request.

### What changes do you think we should make in order to solve the problem?

Update [this](https://github.com/Expensify/App/blob/5b1c240f69098f07fbbd7459235edcfc8f936111/src/libs/OptionsListUtils.ts#L1731) to 
```
const havingLoginPersonalDetails = includeP2P ? options.personalDetails.filter((detail) => !!detail?.login && !!detail.accountID && !detail?.isOptimisticPersonalDetail) : [];
```

So it will not show any option in `Contacts`, if `includeP2P` is false (aka the user is not in `P2PDistanceRequests` beta)

### What alternative solutions did you explore? (Optional)
NA

**Comment by neil-marcellini** [comment] 2024-04-29 16:47
I'll take a peek in a bit

**Comment by neil-marcellini** [comment] 2024-04-29 17:19
Here's what's happening.
1. P2P distance requests are still under beta
2. It's a front end only beta
3. There's a bug which allows users not on the beta to select individuals for distance requests
4. The p2p distance request is successfully created
5. The QAB is successfully updated, but it also properly prevents the user from submitting a distance request to the individual since they aren't on the beta


The solution should be to fix the bug in point 3. I will see if I can find the issue for that. I can't find any other issue like that. Please lmk if you find something, but otherwise let's fix it here.

https://github.com/Expensify/App/assets/26260477/69525fe8-8f75-41b9-ab15-4e2d56236858

**Comment by nkdengineer** [comment] 2024-04-29 19:31
> The solution should be to fix the bug in point 3.

@neil-marcellini I agree with this, [my proposal](https://github.com/Expensify/App/issues/40790#issuecomment-2075464550) is doing just that.

**Comment by twisterdotcom** [comment] 2024-04-29 20:06
Alright, shall we assign @nkdengineer?

**Comment by twisterdotcom** [comment] 2024-04-30 08:27
Okay, this is with you then @getusha.

**Comment by getusha** [comment] 2024-05-01 17:17
@GandalfGwaihir's [proposal](https://github.com/Expensify/App/issues/40790#issuecomment-2073366271) looks good to me.
🎀 👀 🎀 C+ Reviewed!

**Comment by nkdengineer** [comment] 2024-05-02 02:13
@getusha I believe [my proposal](https://github.com/Expensify/App/issues/40790#issuecomment-2075464550) is the first to have the correct RCA and solution (which was later confirmed by @neil-marcellini [here](https://github.com/Expensify/App/issues/40790#issuecomment-2083258171)), while everyone else was going in the wrong direction and only [updated the proposal later](https://github.com/Expensify/App/issues/40790#issuecomment-2083617303).

@GandalfGwaihir's proposal is basically the same as mine, the only difference is that they use another equivalent variable `includePersonalDetails` (as opposed to `includeP2P` in my proposal). Actually the rendering performance of that suggestion is much worse, because even though we don't need the personal detaills, we're still running [all these logic](https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.ts#L1739-L1761) to get, filter, order the `allPersonalDetailsOptions`. And that solution will also still return the `currentUserOption` [here](https://github.com/Expensify/App/blob/8b3def3121a5de9e28245382a5e0503da26733a8/src/libs/OptionsListUtils.ts#L1842), while the personal details should not be included.

Meanwhile, my proposal will not do any logic with the `personalDetails` list from the start.

Since the meaning of `includeP2P` and `includePersonalDetails` are the same, I think we should consolidate them instead of having both, and still make the `allPersonalDetailsOptions` empty from the start (if `includeP2P` is true) so that we don't run any unnecessary logic there.

@getusha Could you kindly take a second look at this? Thanks 🙏 

cc @neil-marcellini

**Comment by getusha** [comment] 2024-05-07 12:50
>Since the meaning of includeP2P and includePersonalDetails are the same, I think we should consolidate them instead of having both, and still make the allPersonalDetailsOptions empty from the start (if includeP2P is true) so that we don't run any unnecessary logic there.

@nkdengineer i doubt they have the same purpose, can you expand on that more?

**Comment by nkdengineer** [comment] 2024-05-07 13:04
> @nkdengineer i doubt they have the same purpose, can you expand on that more?

Yes they're the same purpose, let me update you in a bit.

@neil-marcellini We're re-discussing the solution (details [here](https://github.com/Expensify/App/issues/40790#issuecomment-2089412920)), please hold the assignment until it's clear which path we'll go with 🙇

**Comment by nkdengineer** [comment] 2024-05-07 13:55
> @nkdengineer i doubt they have the same purpose, can you expand on that more

@getusha The `includeP2P`'s meaning is "include peer to peer" sharing, which means no options of P2P chat or personal details should show. The `includePersonalDetails` is also for including/not including the personal details.

There's never a case where `includeP2P` is `false`, but the personal details is included. So we need to make sure the `includeP2P` works correctly by itself instead of depending on another variable to do part of its job. Also my solution is much more performant as already explained, we won't run operations on the `personalDetailsList` unnecessarily

> I also don't see any possible case where my solution will cause a regression :)

@GandalfGwaihir so is mine, mine is the first to work without regressions, and also more performant than your solution.

**Comment by neil-marcellini** [comment] 2024-05-13 21:04
Oh wow sorry for the delay on this one. I'll review proposals soon, hopefully today.

**Comment by neil-marcellini** [comment] 2024-05-13 22:01
There seems to be some disagreement about who had the first valid proposal. I started by examining the first proposal by @GandalfGwaihir in its earliest version. The RCA in that version is incorrect, so I moved on to view the earliest version of the next proposal, which is by @nkdengineer. It also has an incorrect RCA, however the next edit has a correct RCA and it looks like a good solution. It was posted at `2024-04-24T17:23:40Z` relative to my timezone. @GandalfGwaihir's next proposal edit was made at `2024-04-29T20:35:38Z`. Therefore we should go with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/40790#issuecomment-2075464550) @getusha

**Comment by nkdengineer** [comment] 2024-05-14 09:45
@getusha The PR is [here](https://github.com/Expensify/App/pull/42142).

**Comment by neil-marcellini** [comment] 2024-05-21 19:31
PR is under review, commenting so this doesn't got overdue.

**Comment by twisterdotcom** [comment] 2024-06-20 11:41
Payment Summary:

- @getusha requires paid $250 [here](https://www.upwork.com/nx/wm/offer/102808948) (Reviewer)
- @nkdengineer paid $250 [here](https://www.upwork.com/nx/wm/offer/102293893) (Contributor)

**Comment by twisterdotcom** [comment] 2024-06-25 17:05
Bump on this checklist @getusha.

**Comment by twisterdotcom** [comment] 2024-06-26 10:06
Bump @getusha.

**Comment by getusha** [comment] 2024-07-02 19:32
This fell through the cracks, will complete the checklist.

**Comment by getusha** [comment] 2024-07-04 10:21
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@getusha] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40748
 [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/2e21c24fed25b43d109d4ae7e269459b8a85cc35#r143839908
 [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/a**
 [@getusha] Determine if we should create a regression test for this bug. **Yes**
 [@getusha] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Login with an account that doesn't have `P2PDistanceRequests` enabled
2. Go FAB > Submit expense > Distance
3. Select any waypoint and go to participants page
4. Verify that contact option/p2p accounts doesn't appear in the list

Do we agree 👍 or 👎

**Closed** 2024-07-04 11:48 UTC
Labels: External, Daily, Bug

**Comment by getusha** [comment] 2024-07-04 12:09
@twisterdotcom accepted the offer, could you end it? ty!

**Comment by twisterdotcom** [comment] 2024-07-04 14:51
Done
