### ISSUE TITLE
[HOLD for payment 2022-10-03] [$500] mWeb/safari - When we try to download App from ‘App download links’ drawer page for safari mobile it opens a blank page instead of opening in app store @dhairyasenjaliya

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10329] opened 2022-08-09 20:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Open Drawer setting -> Go to about
3. Go to App download links
4. Press on iOS
Notes: It will open an blank page in new tab instead of app store
But when you go back to web app (tab) again it will show popup “open this app in app store”

## Expected Result:
pp should open in App store or direct popup of “open this app in app store” should be displayed without opening new blank tab

## Actual Result:
Currently it open empty page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/183755978-d956ab3c-2fba-4493-accd-9abb0baf1cac.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @dhairyasenjaliya

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657624682950209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment] 2022-08-10 16:46
Posted [here](https://expensify.slack.com/archives/C03TE33PG/p1660149829184639) looking for another triager. I can't access m/web safari and I tried to recreate on my mac and android without any luck.

**Comment by lschurr** [comment] 2022-08-10 16:49
Confirmed. Same thing happens for me. @johncschuster also reproduced this.

**Comment by dhairyasenjaliya** [comment] 2022-08-10 17:00
This issue only affect mobile safari

**Comment by TomatoToaster** [comment] 2022-08-10 20:46
So it seems like a blank page is opening up in a new tab, but if you navigate back to the original tab, it still shows you an open to open the app store link:

![image](https://user-images.githubusercontent.com/19364431/184016352-5ff0b171-6ae6-4941-8429-54170702a673.png)

Since that still works I feel like this is not worth fixing. This also seems more like an issue with safari, but we have some different link handling for safari and @luacmartins you worked on specific for that here: https://github.com/Expensify/App/blob/75b398f513eca2141f974ecb932459600aaba2d6/src/libs/asyncOpenURL/index.website.js#L18

Do you think we can fix this/ this is worth fixing?

**Comment by luacmartins** [comment] 2022-08-10 20:53
I think we should fix this since we open the blank page and it's confusing. Maybe we should not use the custom Safari link handler for that link since it opens the link in the App store and not Safari.

**Comment by luacmartins** [comment] 2022-08-11 16:20
I think this can be external!

**Comment by kevinksullivan** [comment] 2022-08-16 05:11
https://www.upwork.com/jobs/~01ebeba569e03425e7

**Comment by kevinksullivan** [comment] 2022-08-24 12:12
Going OOO for a bit so I'm going to reassign. Thanks @mallenexpensify !

**Comment by MadPharaoh** [comment] 2022-08-25 23:05
Proposal### 

```
if (!isSafari) { 
     promise.then((params) => { 
         Linking.openURL(typeof url === 'string' ? url : url(params)); 
     }); 
 } else { 
     const windowRef = window.open(); 
     promise 
         .then((params) => { 
             windowRef.location = typeof url === 'string' ? url : url(params); 
             windowRef.close();
         }) 
         .catch(() => windowRef.close()); 
 } 
```
 it will just trigger a redirect to the App store via the client side on the onload page event of the blank window then close it  and this will just show “open this app in app store” , better to use branch Links if u want it to directly open in page store

**Comment by Santhosh-Sellavel** [comment] 2022-08-26 18:49
@MadPharaoh 
Your suggesstion is to add `windowRef.close();`  here? 

https://github.com/Expensify/App/blob/d5b1c8249bd3538051abe7d7bc728eaa1e64fd3c/src/libs/asyncOpenURL/index.website.js#L23-L25

It breaks everything and does not open any links

It would be helpful if write proposals more clearly, look at these past [jobs](https://github.com/Expensify/App/issues?q=is%3Aissue+is%3Aclosed+label%3A%22Awaiting+Payment%22) for reference.

**Comment by songlang1994** [comment] 2022-09-04 03:34
### Proposal

`openExternalLink` in `src/libs/actions/Link.js` was changed in [PR#8788](https://github.com/Expensify/App/pull/8788/files) to make sure open links in a new tab in Safari. The root cause for that issue is react-native-web uses the `noopener` feature to open new windows [(source code)](https://github.com/necolas/react-native-web/blob/dee258ae02188befca4192ea502d4fbebc478341/packages/react-native-web/src/exports/Linking/index.js#L112), it causes Safari to use a new window to open instead of a new tab.

So we have two problems:
- `Linking.openURL` of react-native-web is not suitable for Safari.
- `asyncOpenURL` workaround for Safari opens a blank page when open AppStore link. (this issue)

By passing a `null` value into the first argument, we can make `asyncOpenUrl` support synchronously open URLs. This should resolve this issue.

```diff
  // File: src/libs/asyncOpenURL/index.website.js

- import {Linking} from 'react-native';

+ // We don't directly use `Linking.openURL` of react-native-web since it adds `noopener` feature to open
+ // new windows which causes Safari to use a new window to open instead of a new tab.
+ // Basically copied from `Linking.js` of react-native-web but removing the `noopener` feature.
+ function open(url, target = '_blank') {
+     const urlToOpen = new URL(url, window.location).toString();
+     if (urlToOpen.indexOf('tel:') === 0) {
+       window.location = urlToOpen;
+     } else {
+       window.open(urlToOpen, target);
+     }
+ }
  
  export default function asyncOpenURL(promise, url) {
      if (!url) {
          return;
      }
  
+     if (!promise) {
+         open(url);
+         return;
+     }
  
      const isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
  
      if (!isSafari) {
          promise.then((params) => {
-             Linking.openURL(typeof url === 'string' ? url : url(params));
+             open(typeof url === 'string' ? url : url(params));
          });
      } else {
          const windowRef = window.open();
          promise
              .then((params) => {
                  windowRef.location = typeof url === 'string' ? url : url(params);
              })
              .catch(() => windowRef.close());
      }
  }
```

```diff
  // File: src/libs/actions/Link.js
  
  function openExternalLink(url) {
      if (showGrowlIfOffline()) {
          return;
      }
  
-     asyncOpenURL(Promise.resolve(), url);
+     asyncOpenURL(null, url);
  }
```

**Comment by rawalyogendra** [comment] 2022-09-04 09:47
# Proposal

## Problem
The Menu item has this action handler associated with it.
https://github.com/Expensify/App/blob/847e0af9f05756f49756cc374d0aa5aed02118a0/src/pages/settings/AppDownloadLinks.js#L43-L45
Which opens external links using our `asyncOpenURL` handler.
https://github.com/Expensify/App/blob/847e0af9f05756f49756cc374d0aa5aed02118a0/src/libs/asyncOpenURL/index.website.js#L16-L27
this is a workaround for opening links in Safari from inside an async call. This opens the new tab in Safari with our app link, but the popup to open the App Store is displayed on the web app tab instead of the new tab, which is causing the blank tab issue.

## Solution
Since we are trying to open the app link in App Store itself, we should use `Linking.openURL()` from `react-native` for this purpose, which will redirect the user straight to our app in App Store without opening a new tab. I have two approaches to fix this issue using `Linking`.

### First Approach
> I think we should fix this since we open the blank page and it's confusing. Maybe we should not use the custom Safari link handler for that link since it opens the link in the App store and not Safari.
_Originally posted by @luacmartins in https://github.com/Expensify/App/issues/10329#issuecomment-1211259143_

We can update our action in [App/src/pages/settings/AppDownloadLinks.js](https://github.com/Expensify/App/blob/847e0af9f05756f49756cc374d0aa5aed02118a0/src/pages/settings/AppDownloadLinks.js#L43-L45)
```js
 action: () => { 
    // import {Linking} from 'react-native';
     Linking.openURL(CONST.APP_DOWNLOAD_LINKS.IOS); 
 },
```

### Second Approach
We can update our workaround on [App/src/libs/asyncOpenURL/index.website.js](https://github.com/Expensify/App/blob/847e0af9f05756f49756cc374d0aa5aed02118a0/src/libs/asyncOpenURL/index.website.js#L16-L27) to include a check fo any apps.apple.com URL and use `Linking.openURL()` to open those URLs.
```js
// just an example 
// could be anything to check for this domain
 const isAppStoreURL = /apps.apple.com/i.test(url); 

  if (!isSafari || isAppStoreURL) {
      promise.then((params) => {
          Linking.openURL(typeof url === 'string' ? url : url(params));
      });
  } else {
```

**Comment by flodnv** [comment] 2022-09-06 15:55
@Santhosh-Sellavel what are your thoughts on these latest proposals?

**Comment by Santhosh-Sellavel** [comment] 2022-09-07 21:13
@flodnv 
The first approach in @rawalyogendra's Proposal looks good to me!

> I think we should fix this since we open the blank page and it's confusing. Maybe we should not use the custom Safari link handler for that link since it opens the link in the App store and not Safari.
> Originally posted by @luacmartins in https://github.com/Expensify/App/issues/10329#issuecomment-1211259143

C+ Reviewed
🎀 👀 🎀 

Thanks!

cc: @mallenexpensify

**Comment by Santhosh-Sellavel** [comment] 2022-09-07 21:31
@flodnv 
The first approach in @rawalyogendra's Proposal sounds good to me!
> I think we should fix this since we open the blank page and it's confusing. Maybe we should not use the custom Safari link handler for that link since it opens the link in the App store and not Safari.
> Originally posted by @luacmartins in https://github.com/Expensify/App/issues/10329#issuecomment-1211259143

But there is the problem here we will not show a growl for offline and we might miss out on that.

So we could use the second approach which is simpler.
I find it a little odd to test the URL against `apps.apple.com`, if we are okay with it then let's proceed with this.

Else instead we can add a param `useLinking` with default `false` to the methods. For the IOS link alone let's pass it `true` for skipping the `!isSafari` check

Any thoughts @flodnv ?

C+ Reviewed
🎀 👀 🎀 

Thanks!

cc: @mallenexpensify

**Comment by mallenexpensify** [comment] 2022-09-13 17:14
Bumping back to weekly but... @flodnv can you _sign off_ on @Santhosh-Sellavel 's recommendation above https://github.com/Expensify/App/issues/10329#issuecomment-1239912579

**Comment by flodnv** [comment] 2022-09-15 11:59
👋 I was ooo

>The first approach in @rawalyogendra's Proposal sounds good to me!

Hm, I agree, however I got a bit lost in all the other chatter. Is the proposal to simply change one line and be done with this @rawalyogendra ?

**Comment by rawalyogendra** [comment] 2022-09-15 12:06
For this particular scenario, yes, changing that one line will do the trick.

But if we want to handle cases like this in future @Santhosh-Sellavel's suggestion is better. Adding a second parameter in ` Link.openExternalLink` which skips the `isSafari` check.

**Comment by flodnv** [comment] 2022-09-15 13:05
Let's make the change we need to make for what we need _now_, and revisit later in the future if we ever need something else (although I am not convinced it is better). Let's also add a comment in the change explaining why we use this method over another.

@mallenexpensify go ahead and hire @rawalyogendra

**Comment by Santhosh-Sellavel** [comment] 2022-09-15 13:12
Only problem with the first approach is
> we will not show a growl for offline and we might miss out on that.

**Comment by flodnv** [comment] 2022-09-15 13:14
Right, I did not understand what this means, can you clarify please?

**Comment by Santhosh-Sellavel** [comment] 2022-09-15 13:30
Offline check is handled in `Link.openExternalLink` method, replacing with `Linking.openURL` will cause a regression

**Comment by flodnv** [comment] 2022-09-15 13:32
Ah, I see... Not sure how I feel about this, but anyways, I guess let's not cause a regression, and add that new parameter.

**Comment by mallenexpensify** [comment] 2022-09-16 00:34
@rawalyogendra , please apply for the job https://www.upwork.com/jobs/~01ebeba569e03425e7 and confirm here once you have. Thx

**Comment by rawalyogendra** [comment] 2022-09-16 13:36
@mallenexpensify I have applied for the job on Upwork.

I will be fixing this issue as suggested by @Santhosh-Sellavel and approved by @flodnv.

Ah, I see... Not sure how I feel about this, but anyways, I guess let's not cause a regression, and add that new parameter.

_Originally posted by @flodnv in https://github.com/Expensify/App/issues/10329#issuecomment-1248108258_

I will raise a PR for this fix by 19th September 2022.

**Comment by mallenexpensify** [comment] 2022-09-16 19:42
Hired @rawalyogendra and @Santhosh-Sellavel .  @dhairyasenjaliya , please apply so I can pay for reporting the bug, once the issue is fixed

**Comment by dhairyasenjaliya** [comment] 2022-10-05 03:29
> Hired @rawalyogendra and @Santhosh-Sellavel . @dhairyasenjaliya , please apply so I can pay for reporting the bug, once the issue is fixed

hello @mallenexpensify sent the proposal in Upwork, I think this one is ready to close out

**Comment by Santhosh-Sellavel** [comment] 2022-10-05 13:40
Not overdue, waiting for payment!

**Comment by mallenexpensify** [comment] 2022-10-05 20:22
Thanks for the pings, Paid @rawalyogendra and @Santhosh-Sellavel $500 each. 
@dhairyasenjaliya , please accept the job and I'll pay you $250 for reporting
https://www.upwork.com/jobs/~01ebeba569e03425e7

**Comment by dhairyasenjaliya** [comment] 2022-10-06 02:39
done @mallenexpensify :)

**Comment by mallenexpensify** [comment] 2022-10-06 22:03
Thanks, @dhairyasenjaliya is paid, closing

**Closed by mallenexpensify** 2022-10-06 22:03 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment
