### ISSUE TITLE
Previous message appears after a chat response

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10485] opened 2022-08-23 04:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Send a message

## Expected Result:
Receive a response

## Actual Result:
Receive a response and a previous message is shown after it

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88-14
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image - 2022-08-23T005612 891](https://user-images.githubusercontent.com/43995119/186073238-59437a02-652b-4b82-b118-881247a852f7.png)
![image](https://user-images.githubusercontent.com/26260477/186114174-7341aaf2-2b96-4067-aba8-42155f6f4054.png)
![image](https://user-images.githubusercontent.com/26260477/186114251-82530225-2ec4-49bb-b27b-47db7f0410bc.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661161062238409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment] 2022-08-24 05:06
@neil-marcellini The original issue was specific to 10am post. Now it seems just a general message?

Are there reproduction steps here?

**Comment by ctkochan22** [comment] 2022-08-24 05:06
Labeling it monthly until we have some actionable steps here

**Comment by neil-marcellini** [comment] 2022-08-24 08:11
Yes it happened for messages to Flo for a bit, but now it's working fine. It still happens with Chronos, so that might be the best place to focus. Are you not able to re-produce?

**Comment by ctkochan22** [comment] 2022-08-24 14:48
No :/. So I'm just messaging back and forth right? Waiting for a response to come with a previous response? 

If there are no other steps I'm missing, I'm unable to reproduce

**Comment by neil-marcellini** [comment] 2022-08-24 15:37
I'll close this because it's not easy to re-produce and was probably just a fluke.

**Comment by srikarparsi** [comment] 2022-09-16 17:15
I think this issue is still occurring: 

<img width="1135" alt="Screen Shot 2022-09-16 at 1 13 18 PM" src="https://user-images.githubusercontent.com/48188732/190693387-32a9237b-edc7-498c-ac16-5bcd0f0a11d9.png">

I'm going to reopen it but was unable to reproduce it with a different chat.

**Comment by johncschuster** [comment] 2022-10-24 20:35
It looks like this issue has already been triaged to Engi. @srikarparsi, do you have a sense of the repro steps for this behavior? If we can reproduce, we can figure out how to route this to solve it.

**Comment by johncschuster** [comment] 2022-10-24 20:38
@neil-marcellini, have you been able to reproduce this recently? If not, I may close this again until we can get crisp on the reproduction steps.

**Comment by neil-marcellini** [comment] 2022-10-25 18:47
No I haven't seen this issue in a while. We also have the [Deprecate Sequence Numbers design doc](https://docs.google.com/document/d/1xYZfYX3HoNRF9iZOQJH4Tt7GvPgdS4eTMSRX27tQpl4/edit#heading=h.ns12dr1f35rx) which aims to solve this issue for good. I think it's ok to close this.

**Comment by johncschuster** [comment] 2022-10-27 14:28
Thanks! I'll go ahead and close it 👍

**Closed by johncschuster** 2022-10-27 14:28 UTC
Labels: Engineering, Daily, Improvement, Overdue, Bug
