### ISSUE TITLE
[HOLD for payment 2023-12-26] [$500] No error message when editing a chat to go past character limit

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30921] opened 2023-11-06 17:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @grgia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699281873727459

## Action Performed:
1. Open app
2. Go to a report and enter > 10K characters
3. Observe the error message
4. Edit a message and enter >10k characters

## Expected Result:
Error message should appear

## Actual Result:
No error message and could not send the message

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/1dd18f5f-0598-4c9f-b7af-4873d2c191d7

![image (3)](https://github.com/Expensify/App/assets/38435837/d13d0193-f4d4-4cc3-ada9-40c5ab793587)

![image (2)](https://github.com/Expensify/App/assets/38435837/75b48161-b610-4401-86e6-21366f7897e7)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019dbff50a5a453b18</li>
        <li>Upwork Job ID: 1721581708178677760</li>
        <li>Last Price Increase: 2023-11-13</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27770738</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @burczu</details>

**Comment by mpiniarski** [comment] 2023-11-06 17:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When editing a message, length validation does not work.

### What is the root cause of that problem?
Passing `reportId` to `ExceededCommentLength.js` in `ReportActionItemMessageEdit.js`
<img width="944" alt="image" src="https://github.com/Expensify/App/assets/11861292/683f2b6e-cc7c-4033-94f2-11e6b00ecb3c">
causes it to be incorrectly initialised with empty value in`ExceededCommentLength.js`:
<img width="792" alt="image" src="https://github.com/Expensify/App/assets/11861292/a3da27e7-da23-43d1-b197-3a2274934425">


### What changes do you think we should make in order to solve the problem?
We don't need to pass `reportId`.
<img width="948" alt="image" src="https://github.com/Expensify/App/assets/11861292/63d04031-a8dc-4ca7-9bba-f405268f0ac4">


### What alternative solutions did you explore? (Optional)

**Comment by erquhart** [comment] 2023-11-06 18:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The 10,000 character max error message does not show when editing an existing message.

### What is the root cause of that problem?
The `ExceededCommentLength` component checks the onyx store directly for the comment value. It is currently set up to check for the draft of a new comment, but not for the draft of an existing comment, which uses a different Onyx key.

### What changes do you think we should make in order to solve the problem?

`ExceededCommentLength` should not be tied to the Onyx store. It is only used in two places, and it's simple to pass the draft directly to the component, rather than add logic to `ExceededCommentLength` to fetch the right draft from the store.

We should remove the `withOnyx()` HOC from this component and allow it to receive the comment direct through the `comment` prop that is currently populated through Onyx.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by erquhart** [comment] 2023-11-06 18:23
## Proposal
[Updated](https://github.com/Expensify/App/issues/30921#issuecomment-1795769911)

- Recognized that the `ExceededCommentLength` component was connected to Onyx for performance reasons
- Changed recommendation to have consumers pass in the onyx key for the comment draft rather than hardcoding the key
- Allows minimal change, no new components need to be created
- Allows flexibility as new consumers can specify the key without needing to update logic in `ExceededCommentLength`.

**Comment by abekkala** [comment] 2023-11-08 21:34
@burczu can you review the proposals?

**Comment by burczu** [comment] 2023-11-13 12:02
@abekkala I'm sorry, I've missed that one - I'll review proposals soon.

**Comment by burczu** [comment] 2023-11-14 09:36
@erquhart Could you please be more specific how the `ExceedCommentLength` component should be changed? How do you want to use this new `draftKey` property in case on composing and editing?

**Comment by burczu** [comment] 2023-11-14 09:38
@tienifr I've tried your solution but it does not work for me. Could you be more specific how do you pass `reportActionID` to the component and where?

**Comment by DylanDylann** [comment] 2023-11-14 10:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- No error message when editing a chat to go past character limit

### What is the root cause of that problem?
- [ExceededCommentLength](https://github.com/Expensify/App/blob/main/src/components/ExceededCommentLength.js) uses the ```comment``` prop to decide if it will display error or not (when ```comment.length``` > 10K, it will display error). This ```comment``` is from ```ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT```
- And [ExceededCommentLength](https://github.com/Expensify/App/blob/main/src/components/ExceededCommentLength.js) uses in [ReportActionItemMessageEdit](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItemMessageEdit.js) as well, so when the main composer has < 10K characters, edit composer has > 10K characters, the edit composer will have no error. 
### What changes do you think we should make in order to solve the problem?
- Rather than getting the ```comment``` from ```ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT```, we can just pass the ```comment``` param to ```ExceededCommentLength``` from its parent component. This can fix this issue, also reducing the delay time in updating max length error (currently, when user types more than 10K, it will delay 1500ms before displaying error).
- We can do it by these below steps:
1. Remove subscribing ```ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT```
https://github.com/Expensify/App/blob/2c7062b917a2d31b709691166633f171dd1fce8c/src/components/ExceededCommentLength.js#L63-L68
2. With ```ReportActionItemMessageEdit```, we do not need do anything because we have already had the below logic:
https://github.com/Expensify/App/blob/2c7062b917a2d31b709691166633f171dd1fce8c/src/pages/home/report/ReportActionItemMessageEdit.js#L468
3. With ```ReportActionComposer```, updating
https://github.com/Expensify/App/blob/358c3bf4fd161c51cf4ea00110576af3afe03ce9/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L454
to
```
<ExceededCommentLength comment={value} ... />                 
```

### What alternative solutions did you explore? (Optional)
- Also, we rather than passing the ```comment``` param to ```ExceededCommentLength``` from its parent component like the above solution, we can just pass the param called ```isExceedMaxLength``` to ```ExceededCommentLength``` from its parent component.

**Comment by erquhart** [comment] 2023-11-14 17:24
@burczu `ExceededCommentLength` has a hardcoded key in the `withOnyx` config object, which is the norm, but we can pass it through props so any key can be used and the consumer can specify.

Before:
```
export default withOnyx({
    comment: {
        key: ({reportID}) => `${ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT}${reportID}`,
        initialValue: '',
    },
})(ExceededCommentLength);
```

After:
```
export default withOnyx({
    comment: {
        key: ({draftKey, reportID}) => `${draftKey}${reportID}`,
        initialValue: '',
    },
})(ExceededCommentLength);
```

**Comment by burczu** [comment] 2023-11-15 11:57
Thanks for your updates @erquhart and @tienifr, I'll get back to your proposals soon.

@DylanDylann So, your solution actually rolls back the changes introduced in this performance PR: https://github.com/Expensify/App/pull/25758 - are you sure it actually improves the performance?

**Comment by DylanDylann** [comment] 2023-11-15 14:11
@burczu Before, we need to display exactly the current input length, for example 12000/10000, so we need to get the comment from Onyx - that will be updated with 1000ms delay to increase the performance. But now, we just need to know whether the input is greater than the MAX_COMMENT_LENGTH or not, so my proposal suggestd that, we just need to pass the ```isExceedMaxLength``` to ```ExceededCommentLength``` from its parent. Besides fixing this bug, it also reduce the delay time when updating the error (Currently, updating error has 1500ms delay)

**Comment by erquhart** [comment] 2023-11-15 15:03
The 1500ms delay is an intentional debounce, the current setup avoids the component fetching the comment directly to keep evaluation out of the render. Sidestepping this will decrease performance unless you move the debounce into each consumer of `ExceededCommentLength`, which is why #25758 centralized the comment length check.

**Comment by burczu** [comment] 2023-11-16 10:26
@DylanDylann Thanks for explanation, but I agree with @erquhart's [comment](https://github.com/Expensify/App/issues/30921#issuecomment-1812703393) here.

That being said, after I've reviewed all the proposals I tend to like the most [the one](https://github.com/Expensify/App/issues/30921#issuecomment-1795769911) from @erquhart, but with additional change - what if instead passing the `draftKey` to the `ExceededCommentLength` we could pass some boolean flag, like `isEditMode` and let the component decide which Onyx key to use based on that? This way, the component would be easier to use. What do you think?

[The solution](https://github.com/Expensify/App/issues/30921#issuecomment-1795956682) proposed by @tienifr is somehow similar but it is based on more complicated condition, so in my opinion is less preferable, but we could also consider it.

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2023-11-16 10:28
@burczu as I mentioned above, I think debounce 1500ms is unnecessary

> Now, we just need to know whether the input is greater than the MAX_COMMENT_LENGTH or not, so my proposal suggested that, we just need to pass the isExceedMaxLength to ExceededCommentLength from its parent. So the ExceededCommentLength just re-render once the isExceedMaxLength update from "true" to "false" or vice versa.

**Comment by DylanDylann** [comment] 2023-11-16 10:57
@burczu Also please note that, the solution that I mentioned is my **[alternative solutions](https://github.com/Expensify/App/issues/30921#issuecomment-1809962677)**

**Comment by burczu** [comment] 2023-11-16 11:47
@tienifr Ahh, you are right - I've slightly mixed both solutions while testing... Re-tested everything again and indeed passing additional `reportActionID` prop is necessary because we need it to retrieve the comment from the object if we are in edit mode. I'll change my proposal recommendation. Sorry for my mistake.

**Comment by burczu** [comment] 2023-11-16 11:52
@DylanDylann By agreeing with @erquhart I meant that just passing `isExceedMaxLength` to the `ExceededCommentLength` component will force us to move debouncing to the parent components for keep the performance, so I don't think it's best solution here.

**Comment by burczu** [comment] 2023-11-16 12:04
@bernhardoj Ah, yes - it looks like some kind of workaround for me - I think taking the comment from correct Onyx key for creating and editing comments seems to be more consistent than taking it from Onyx in one case and from props in another.

**Comment by burczu** [comment] 2023-11-16 12:05
Let's now wait for @tgolen opinion because I'm curious what he thinks.

**Comment by erquhart** [comment] 2023-11-16 13:10
@burczu needing to also pass the report action id with my proposal is an implementation detail, I'm hoping code in my proposal is treated as pseudo code. The approach in my proposal still works, and is still the best to maintain existing performance improvements for the `ExceededCommentLength` component.

**Comment by tgolen** [comment] 2023-11-16 15:29
All right, coming in with fresh eyes, I see we have multiple proposals here. Every time I've come across a similar problem (one component needing a piece of data that could exist in two different collections like a draft collection and a regular collection), the best solution I've always found is to lift up the onyx connection to the parents. I think this is the most simple, cleanest, most straightforward solution.

The only argument I hear against that is that it would undo a change that was made for performance. That's good to know, but it doesn't need to be a blocker for the solution. As long as the solution does not degrade performance, then that's really all that matters.

I think the RCA from @DylanDylann was the most comprehensive and easiest for me to understand and I think both the main solution (only pass down `comment`) or the alternate solution (have a prop for `isExceedMaxLength`) is acceptable as long as you are able to prove that there is no performance decrease. I am leaning more toward `isExceedMaxLength` or maybe call it something like `shouldDisplayError`. Also, I'd love to get rid of the debounce. As I understand, the performance problem isn't in checking the length of the comment, but rather in the re-rendering of the component.

@DylanDylann can you please show evidence that your solution won't lead to a performance regression, and then I think the job is yours.

**Comment by DylanDylann** [comment] 2023-11-18 04:35
@tgolen Here is the evidence that my solution won`t lead to performance regression:

1. The current main branch (The ExceedCommentLength re-reder once the input changes)

2. My solution https://github.com/DylanDylann/App/tree/fix/30921-no-error-message-when-editing-a-chat  (The ExceedCommentLength only re-render once the isExceedCommentLength changes)

[Screencast from 18-11-2023 11:28:09.webm](https://github.com/Expensify/App/assets/141406735/7f3ddb44-ecc7-4c01-96ac-c9cc03af98f6)

**Comment by tgolen** [comment] 2023-11-20 15:14
Thank you @DylanDylann. @burczu are you OK with [this proposal](https://github.com/Expensify/App/issues/30921#issuecomment-1809962677) then? I know it's not the one that you originally approved, but it's the one I prefer.

**Comment by burczu** [comment] 2023-11-21 11:43
@tgolen Sure, let's got with the proposal you prefer the most.

**Comment by tgolen** [comment] 2023-11-21 15:50
OK, thanks! @DylanDylann it's all yours.

**Comment by abekkala** [comment] 2023-11-22 21:37
I'm heading out for the Thanksgiving holiday and will be back bright and early Monday morning. 

@DylanDylann can you note when you expect a PR to be ready?

**Comment by DylanDylann** [comment] 2023-11-23 03:20
@abekkala I am working on it and will open PR today

**Comment by DylanDylann** [comment] 2023-11-23 12:57
@burczu PR https://github.com/Expensify/App/pull/31769 is ready to reivew

**Comment by abekkala** [comment] 2023-12-18 14:37
note: deployed to staging Dec 14

**Comment by abekkala** [comment] 2023-12-19 20:51
@laurenreidexpensify 
### STATUS:

I'm going ooo but this one is at the finish line and waiting payment on **Dec 26.**
Then, if regression test is needed a GH will need to be created for that.

- Issue reported by: @grgia (no payment 😉)
- Fix: @DylanDylann [$500, if no regressions] [Offer link](https://www.upwork.com/nx/wm/offer/27770738)
- PR Review: @burczu  [$500, if no regressions] please complete checklist.

**Comment by laurenreidexpensify** [comment] 2023-12-20 10:18
Just a heads up I am OOO until 28 Dec, @DylanDylann @burczu so this will only be paid then, we have a skeleton team working next week so a few payments may be a little bit late

**Comment by laurenreidexpensify** [comment] 2023-12-29 09:13
Payment Summary: 

Fix: @DylanDylann $500 paid in Upwork
PR Review: @burczu N/A - expert contributor (callstack)

@burczu please complete checklist steps thanks

**Comment by laurenreidexpensify** [comment] 2024-01-02 12:36
@burczu bump to complete checklist thanks

**Comment by abekkala** [comment] 2024-01-03 14:54
@burczu can you please complete the checklist so this issue can be closed. thanks!

**Comment by abekkala** [comment] 2024-01-03 17:44
LAST TASK: waiting on @burczu to complete checklist, then this issue can be closed.

**Comment by burczu** [comment] 2024-01-08 08:29
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR:

**https://github.com/Expensify/App/pull/25758**

* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

**https://github.com/Expensify/App/pull/25758#issuecomment-1880557320**

* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

**Not found any.**

* [x]  [@burczu] Determine if we should create a regression test for this bug.

**I think it may be worth checking if we have such test for creating the report message and update it with the check for editing report message as well.**

* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**I'll post the regression test proposal in a separate message.**

* [ ]  [@abekkala] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by burczu** [comment] 2024-01-08 08:33
**Regression test proposal**

1. Open the app.
2. Go to a report and enter > 10K characters in the message box.
3. Check if the error message appears.
4. Update the message to have less than 10k characters and post it.
5. Edit this message and again enter >10k characters.
6. Check if the error message appears.

Do we agree 👍 or 👎

**Closed** 2024-01-08 18:47 UTC
Labels: External, Daily, Awaiting Payment, Bug
