### ISSUE TITLE
[$1000] Attachments - Unable to upload attachments in certain rooms

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#35006] opened 2024-01-23 21:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705433392285439

## Action Performed:
1. Log in with a Expensifail account
2. Navigate to the room #applause.expensifail.com (https://staging.new.expensify.com/r/5324367938904284)
3. Send an image to the chat 
4. Login to another Expensifail account
5. Navigate to the room #applause.expensifail.com (https://staging.new.expensify.com/r/5324367938904284
6. Verify if you can see the uploaded image

## Expected Result:
Image is uploaded and displayed in the conversation history. 

## Actual Result:
The image uploads for a while then an error is displayed in chat and in JS console

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/44479856/5224dbb3-c62e-493c-a345-4b0aebc0da58)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a3eadd41d507135</li>
        <li>Upwork Job ID: 1749905365297426432</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2024-01-23 23:37
This might be related to 
https://github.com/Expensify/App/issues/35017
Since comes first in the process (you have to upload before seeing multiple images, I'm going to put the other on hold pending this one).

**Comment by peterdbarkerUK** [comment] 2024-01-24 10:48
I'm experiencing this, but the attachment does seem to actually upload: other people are reacting to it, at least

<img width="682" alt="image" src="https://github.com/Expensify/App/assets/16888060/2570be70-1bd6-4627-ace0-0e0f0781bc6e">
![image](https://github.com/Expensify/App/assets/16888060/e6fbade6-7337-4ca2-b509-b5116d95bc6d)

I've updated OP for repro steps to check if others can see it.

**Comment by Santhosh-Sellavel** [comment] 2024-01-24 19:32
@NicMendonca need a Expensifail account to test this C+/contributors  don't have one so can you make this internal please, thanks!

**Comment by mallenexpensify** [comment] 2024-01-25 18:43
Happened to me last night then tested again this morn to reproduce

- Open #social room
- Type some text
- Drag drop an image file to the compose box
- Click button to upload
- Leave chat at #social for a while, hoping that it uploads (never left #social for this test)
- Observe receiving error and that image didn't upload
<img width="602" alt="image" src="https://github.com/Expensify/App/assets/22508304/b9d9437e-34c7-4bb1-8725-0aa7f88b582b">

What I see in the console
<img width="529" alt="image" src="https://github.com/Expensify/App/assets/22508304/c3bff613-c6c9-4f8a-a983-764dab8d0adb">

<img width="545" alt="image" src="https://github.com/Expensify/App/assets/22508304/e2932736-7649-4f5e-afd0-d34d1805a483">

@NicMendonca can you try to reproduce in #social? If you can't, will you please swap me out with you as assignees? Thx

**Comment by mallenexpensify** [comment] 2024-01-25 19:42
Both the pic and the text posted, although they still shows as not on my end. 
<img width="618" alt="image" src="https://github.com/Expensify/App/assets/22508304/2f7fb04c-d0c8-4436-87c7-aa699f0b53b5">

<img width="636" alt="image" src="https://github.com/Expensify/App/assets/22508304/a503a0d8-27d7-4740-9894-b0c2f30fb3a5">

What's weird is that, on mobile, it's showing correctly, without the erros

![IMG_1042](https://github.com/Expensify/App/assets/22508304/7aeaf978-a2b7-40f8-9bbf-dc1cafd05878)

**Comment by mallenexpensify** [comment] 2024-01-25 19:58
Experiencing the same bug on iOS when I try to upload a photo.  The photo at text both post though. (for some reason I thought it might be platform specific)
![IMG_1045](https://github.com/Expensify/App/assets/22508304/fe38e82e-0a9b-4dc0-87de-bfaa75e260cf)

**Comment by NicMendonca** [comment] 2024-01-26 21:16
@mallenexpensify I can repro! But I am going to assign this back to you since I start mat leave next week and won't be able to see this one through!

**Comment by Santhosh-Sellavel** [comment] 2024-01-27 16:58
I'm unavailable next week, Please assign a new C+ Issue here if required while I am away, thanks!

cc: @mallenexpensify

**Comment by mallenexpensify** [comment] 2024-01-30 00:52
Raised to $1k to try to get more 👀 on this.  Reassigned C+ @Santhosh-Sellavel since I'm hoping we can get this fixed soon.  @situchan any thoughts on what might be going on?

**Comment by situchan** [comment] 2024-01-30 05:26
Can I get room invited to reproduce? Seems like not reproducible on normal report

**Comment by mallenexpensify** [comment] 2024-01-30 22:51
@situchan do you have access to the 'high traffic' workspace?  If so, are there any rooms in there? I'm checking with QA too

**Comment by situchan** [comment] 2024-01-31 03:30
@mallenexpensify I don't have access. Can I get invited?

**Comment by mallenexpensify** [comment] 2024-02-02 01:35
I invited you @situchan , using your email that's associated with your Slack instance.  DM me if that's not the best one. Can you confirm here once you've been granted access? I'm unsure of the process after requesting access

**Comment by mallenexpensify** [comment] 2024-02-06 23:28
@situchan can you invite me to a room in `Crowded Policy` and comment here once you have done so? Plz use mallen@expensifail.com  Thanks

**Comment by situchan** [comment] 2024-02-07 03:26
@mallenexpensify as an invitee, I don't have permission to invite someone

<img width="944" alt="Screenshot 2024-02-07 at 9 25 43 AM" src="https://github.com/Expensify/App/assets/108292595/60ae00d1-2d99-4c3f-a88c-0eeb93c53f42">

**Comment by mallenexpensify** [comment] 2024-02-07 16:45
I created a room on that policy and invited you https://staging.new.expensify.com/r/1369282750079587
<img width="353" alt="image" src="https://github.com/Expensify/App/assets/22508304/ec0236ea-8eea-467a-9a11-e01a10a460bd">

Know of any _easy_ way to auto-populate that room with a bunch of chats/files.  or.. a way to regularly populate it, ie. have a few test accounts post 10 messages in there a day?

**Comment by situchan** [comment] 2024-02-13 16:11
No idea how to proceed since contributors (including me) are not able to reproduce

**Comment by mallenexpensify** [comment] 2024-02-13 23:14
Added `Needs Reproduction` and bumping to weekly since I'm also unsure of currently reproduction status.

**Comment by mallenexpensify** [comment] 2024-02-21 01:11
Gonna close this until someone else runs into the bug and posts deets.

**Closed by mallenexpensify** 2024-02-21 01:11 UTC
Labels: External, Engineering, Daily, Needs Reproduction, Help Wanted, Bug
