### ISSUE TITLE
[$250] Workspace switcher - Expensify and workspace are highlighted when navigating by keyboard

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43296] opened 2024-06-07 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-9
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User has at least one workspace.
- Workspace switcher is set to "Expensify".

1. Go to staging.new.expensify.com
2. Open workspace switcher.
3. Navigate through the workspace list via keyboard.

## Expected Result:
"Expensify" filter will not be highlighted when navigating through the workspace list via keyboard.

## Actual Result:
Both "Expensify" and the selected workspace are highlighted when navigating through the workspace list via keyboard.
User is also unable to move the selection from workspace list to Expensify and vice versa.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/6d652a4f-0152-4ed6-b470-11c132975670

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0120bd99e26c1b69ef</li>
        <li>Upwork Job ID: 1799087109849632061</li>
        <li>Last Price Increase: 2024-06-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by m-natarajan** [comment] 2024-06-07 14:19
@tgolen FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-07 14:19
We think that this bug might be related to #vip-vsb

**Comment by getusha** [comment] 2024-06-07 15:16
>We separated Expensify option and selection list, before that Expensify option was in the list so it was only highlighted when focused. This is expected behaviour IMO.

I agree, wdyt @blimpich?

**Comment by blimpich** [comment] 2024-06-07 15:34
Yeah seems like intended behavior to me. And even if it isn't we shouldn't block the deploy over this.

**Comment by blimpich** [comment] 2024-06-07 15:38
[Asked internally](https://expensify.slack.com/archives/C03TQ48KC/p1717774669713619) to double check if this is intended behavior. If people agree lets close this.

**Closed** 2024-06-10 19:12 UTC
Labels: External, Engineering, Hourly, Help Wanted, Bug
