### ISSUE TITLE
[HOLD for payment 2023-08-28] [$2000] Web- Chat - Pressing Copy to clipboard, Copy link, or Mark as unread from the Mini context menu does not refocus the Composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20079] opened 2023-06-02 17:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App
2. Go to any chat
3. Send a message and click anywhere on the page to lose composer focus
4. Hover over the message and click any of these three Copy to clipboard, Copy link, Mark as unread

## Expected Result:
Pressing any of these three options Copy to clipboard, Copy link, Mark as unread should have to refocus the composer like we do when using the Context menu

## Actual Result:
Pressing any of these three options, Copy to clipboard, Copy link, or Mark as unread is, not refocusing the composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/17878553-d3bc-4891-9525-ed47bd10fceb

https://github.com/Expensify/App/assets/93399543/e4ae86d4-d71d-4d31-8a1c-b0eb4942501b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @jayeshmangwani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684759049611809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01517d6a9b05f42ab8</li>
        <li>Upwork Job ID: 1666174440708157440</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment] 2023-06-02 18:05
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Pressing Copy to clipboard, Copy link, Download, or Mark as unread from the Mini context menu does not refocus the Composer, but Composer is refocused when pressed from the context menu opened from a long press
### What is the root cause of that problem?
We are focusing the composer on the above actions if we press from the Context menu and we are doing nothing if we press from the mini menu
here is the condition for checking if the press is from the popover or not and if the press is from the context menu then call the `ReportActionComposeFocusManager.focus`
https://github.com/Expensify/App/blob/c917c447f225fe3b194a5e03f568cca0de9e5e71/src/pages/home/report/ContextMenu/ContextMenuActions.js#L102-L104
### What changes do you think we should make in order to solve the problem?
We need to add an `else` condition to Copy to clipboard, Copy link, Download, and Mark as unread(or any other actions) press, where we will call `ReportActionComposeFocusManager.focus()` if it is not the from Popover, it means mini context menu
https://github.com/Expensify/App/blob/c917c447f225fe3b194a5e03f568cca0de9e5e71/src/pages/home/report/ContextMenu/ContextMenuActions.js#L45
here need to add else and all other presses like Copy to clipboard, Copy link, and Mark as unread
https://github.com/Expensify/App/blob/c917c447f225fe3b194a5e03f568cca0de9e5e71/src/pages/home/report/ContextMenu/ContextMenuActions.js#L102-L104
```
  } else {
    ReportActionComposeFocusManager.focus()
  }
```
### What alternative solutions did you explore? (Optional)
none

**Comment by will0225** [comment] 2023-06-06 20:18
I want to have this issue.

**Comment by youssef-lr** [comment] 2023-06-07 04:59
@0xmiroslav what do you think of the proposal above?

**Comment by youssef-lr** [comment] 2023-06-09 21:48
Waiting for more proposal.

**Comment by petromoldovan** [comment] 2023-06-10 20:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Composer field must be focused, when user clicks on one of three actions(copy clipboard, copy link and mark message as new) in the popup element(`MiniReportActionContextMenu` component) that appears in the top right corner when a message is hovered.

### What is the root cause of that problem?
All three actions do NOT implement methods for focusing the composer when actions are called from the `MiniReportActionContextMenu` component. 
In their onPress handlers, there is a method called `hideContextMenu` but it is not used in case of the `MiniReportActionContextMenu` which is our case. `hideContextMenu` is functional only for the `ReportActionContextMenu`(the popup that appears with the right click on an action).
https://github.com/Expensify/App/blob/035783a7984e0214677b5364d9351c968887bf58/src/pages/home/report/ContextMenu/ContextMenuActions.js#L192

### What changes do you think we should make in order to solve the problem?

The first step is easy: we need to focus the composer manually when actions are triggered from the `MiniReportActionContextMenu` component. I will implement such function:
```
function hideAllContextMenus(isMini) {
    if (isMini) {
        ReportActionComposeFocusManager.focus();
        return;
    }

    hideContextMenu(true, ReportActionComposeFocusManager.focus);
}
```
and I will call it in `onPress` methods for all three actions, like so:
```
onPress: (closePopover, {reportAction, selection}) => {
	//...
	hideAllContextMenus(!closePopover);
}
``` 

But then I start getting such effect: compose field is focused but the click animation is broken:

https://github.com/Expensify/App/assets/15109844/cca15590-5cd5-44eb-a909-25ecff0a6f6c

Each action in the view is wrapped in a `Hoverable` HOC component. 
https://github.com/Expensify/App/blob/035783a7984e0214677b5364d9351c968887bf58/src/pages/home/report/ReportActionItem.js#L427-L428

I noticed that when I call the `ReportActionComposeFocusManager.focus()` method, the `onBlur` method in the `Hoverable` is triggered and the hover state is set to false for a moment. This triggers rerender in few elements and that is why the click animation in actions menu is broken. The `ContextMenuItem` is rerendered again and animation seems to be broken.

I propose to ignore state changes in `Hoverable` component in `onBlur` method if the the composer element is clicked. 

The current `onBlur` in `Hoverable` component looks like this:
https://github.com/Expensify/App/blob/035783a7984e0214677b5364d9351c968887bf58/src/components/Hoverable/index.js#L109-L117

This is the new `onBlur`method. Here I check if I am allowed to ignore hover state change for the element if `this.props.ignoreBlurForElement` prop allows it:
```
onBlur: (el) => {
    if (!this.wrapperView.contains(el.relatedTarget)) {
        if (!this.props.ignoreBlurForElement || !this.props.ignoreBlurForElement(el.relatedTarget)) {
            this.setIsHovered(false);
        }
    }

    if (_.isFunction(child.props.onBlur)) {
        child.props.onBlur(el);
    }
}
```

And this is how the prop is passed in the `Hoverable` component in the file `ReportActionitem.js`. 
The `ignoreBlurForElement` returns true if the element that user clicked on is the composer. Therefore, there is not rerender happening when we do `ReportActionComposeFocusManager.focus()` and focus the composer element.
```
<Hoverable
  ...
  ignoreBlurForElement={(el) => el === lodashGet(ReportActionComposeFocusManager, 'composerRef.current')}>
...
```

This is the end result. Notice that completion animation goes till the end and composer field is focused immediately after the click.
https://github.com/Expensify/App/assets/15109844/82f9ad15-99fb-4b90-93ad-5a60a92233a6

### What alternative solutions did you explore? (Optional)
In `ContextMenuActions.js` I could call `ReportActionComposeFocusManager.focus()` for `MiniReportActionContextMenu` component WITH a certain delay. I could make a setTimeout and wait for 1800ms(duration of the completion state animation) and only then shoot the `ReportActionComposeFocusManager.focus()` action. In this way the composer will be focused only after 1800ms. 
The initial solution is a bit harder but much cleaner.

**Comment by youssef-lr** [comment] 2023-06-12 12:29
@0xmiroslav ^

**Comment by petromoldovan** [comment] 2023-06-12 21:54
@0xmiroslav I also do not recommend to set the `setTimeout`. It was just an alternative to emphasise how much better the main proposal is. What do you think about my main proposal?

**Comment by adelekennedy** [comment] 2023-06-16 03:44
Still pending more proposals!

**Comment by aliammar1995** [comment] 2023-06-17 14:35
**Please re-state the problem that we are trying to solve in this issue.**

      Pressing Copy to clipboard, Copy link, or Mark as unread from the Mini 
      context menu does not refocus the Composer

**What is the root cause of that problem? **
      In MiniReportActionContextMenu component, when clicking menu items 
     (Copy to clipboard, copy link, Mark as unread), It  does not call
     ReportActionComposeFocusManager.focus method while calling 
      hideContextMenu.


 **What changes do you think we should make in order to solve the problem?**
   
   I found a solution.
   In hideContextMenu function, we can call 
   ReportActionComposeFocusManager.composerRef.current.focus() directly.
   `function hideContextMenu(shouldDelay, onHideCallback = () => {}) {
   
    if (!contextMenuRef.current) {
        return;
    }
    if (!shouldDelay) {
        contextMenuRef.current.hideContextMenu(onHideCallback);

        return;
    }

    // Save the active instanceID for which hide action was called.
    // If menu is being closed with a delay, check that whether the same instance exists or a new was created.
    // If instance is not same, cancel the hide action
    const instanceID = contextMenuRef.current.instanceID;
    setTimeout(() => {
        if (contextMenuRef.current.instanceID !== instanceID) {
            return;
        }

        contextMenuRef.current.hideContextMenu(onHideCallback);
        ReportActionComposeFocusManager.composerRef.current.focus()
    }, 800);
}`

It worked on my local.


https://github.com/Expensify/App/assets/136129373/57e19a9f-2c62-40a9-a913-20af079ca2cc

**Comment by adelekennedy** [comment] 2023-06-19 18:43
pending proposal review

**Comment by youssef-lr** [comment] 2023-06-21 20:14
@0xmiroslav what do you think of the proposal above?

**Comment by aliammar1995** [comment] 2023-06-22 06:58
Exactly, hideContextMenu function is for hide context menu, not Mini context menu.
so we have to add ReportActionComposeFocusManager.focus() in onPress method in contextMenuActions.js file.


`onPress: (closePopover, {reportAction, selection}) => {
            const message = _.last(lodashGet(reportAction, 'message', [{}]));
            const messageHtml = lodashGet(message, 'html', '');

            const isAttachment = _.has(reportAction, 'isAttachment') ? reportAction.isAttachment : ReportUtils.isReportMessageAttachment(message);
            if (!isAttachment) {
                const content = selection || messageHtml;
                if (content) {
                    const parser = new ExpensiMark();
                    if (!Clipboard.canSetHtml()) {
                        Clipboard.setString(parser.htmlToMarkdown(content));
                    } else {
                        const plainText = parser.htmlToText(content);
                        Clipboard.setHtml(content, plainText);
                    }
                }
            } else {
                Clipboard.setString(messageHtml);
            }
            if (closePopover) {
                hideContextMenu(true, ReportActionComposeFocusManager.focus);
            }
            ReportActionComposeFocusManager.focus()
        },`

**Comment by ShogunFire** [comment] 2023-06-25 21:22
@0xmiroslav Can you explicit what type of regressions you had with this [proposal](https://github.com/Expensify/App/issues/20079#issuecomment-1574120279) . @petromoldovan speaks about a problem with animation but I don't have it, was it also a problem with animation that you had ?

This is what I have with the first proposal:


https://github.com/Expensify/App/assets/19537677/40f79aef-e520-45d8-9c0a-9cc41612e7fd

**Comment by adelekennedy** [comment] 2023-06-26 15:07
still pending proposal updates

**Comment by aliammar1995** [comment] 2023-06-27 16:15
I think the bounty is needed. we have to redesign structure about Mini context menu.

**Comment by aliammar1995** [comment] 2023-06-27 16:17
https://github.com/Expensify/App/issues/20079#issuecomment-1602108187
Above proposal works well if we don't want to redesign structure.

**Comment by aliammar1995** [comment] 2023-06-27 16:21
sorry, I am about to respond to everyone :)

**Comment by adelekennedy** [comment] 2023-06-29 19:51
doubling - we're still open to better proposals

**Comment by aliammar1995** [comment] 2023-06-30 11:23
### Proposal

### **Please re-state the problem that we are trying to solve in this issue.**

Pressing Copy to clipboard, Copy link, or Mark as unread inside the Mini context menu does not refocus the Composer

### **### What is the root cause of that problem?**

The method that let the composer refocus is ReportActionComposeFocusManager.focus in onPress method in ContextMenuActions.js

` hideContextMenu(true, ReportActionComposeFocusManager.focus);`

We have two context menu component, one is PopoverReportActionContextMenu and MiniContextMenu.

When the user click one of actions on context menu, it call above hideContextMenu function in  onPress method and also calls 
hideContextMenu function in PopoverReportActionContextMenu component.

`contextMenuRef.current.hideContextMenu(onHideCallback);`

```
    hideContextMenu(onHideActionCallback) {
        if (_.isFunction(onHideActionCallback)) {
            this.onPopoverHideActionCallback = onHideActionCallback;
        }
        this.setState({
            reportID: 0,
            reportAction: {},
            selection: '',
            reportActionDraftMessage: '',
            isPopoverVisible: false,
        });
    }
```
this hideContextMenu function store onHideActionCallback which is ReportActionComposeFocusManager.focus and set IsPopoverVisible state variable as false, which let Popover close.

In that case ContextMenu is open,  IsPopoverVisible set as true, if hideContextMenu is called (when the user click action), IsPopoverVisible set as false. so ContextMenu is closed. At that time onModalHide prop function is called
This function calls  above stored ReportActionComposeFocusManager.focus. so composer is refocused.

`onModalHide={this.runAndResetOnPopoverHide}`

  ```
  runAndResetOnPopoverHide() {
        this.setState({reportID: '0', reportAction: {}}, () => {
            this.onPopoverHide = this.runAndResetCallback(this.onPopoverHide);
            this.onPopoverHideActionCallback = this.runAndResetCallback(this.onPopoverHideActionCallback);
        });
    }
```

```
    runAndResetCallback(callback) {
        callback();
        return () => {};
    }
```

In MiniContextMenu that we are considering now, when the user click action, it calls hideContextMenu in PopoverReportActionContextMenu component  like above.

But as you know, IsPopoverVisible variable is already set as false because ContextMenu ( which is not MiniContextMenu) is not open. so it can not call onModalHide props function which is called when Modal is closed.

As a result, In MiniContextMenu, ReportActionComposeFocusManager.focus can not be called, thus, composer is not refocused.

### **What changes do you think we should make in order to solve the problem?**

I think we have to make another method else that does not call hideContextMenu function for MiniContextMenu.
For example,  In case MiniContextMenu, It should call onPressMini, otherwise, calls onPress.
```
onPressMini: (closePopover, {reportAction}) => {
            const message = _.last(lodashGet(reportAction, 'message', [{}]));
            const html = lodashGet(message, 'html', '');
            const attachmentDetails = getAttachmentDetails(html);
            const {originalFileName, sourceURL} = attachmentDetails;
            const sourceURLWithAuth = addEncryptedAuthTokenToURL(sourceURL);
            const sourceID = (sourceURL.match(CONST.REGEX.ATTACHMENT_ID) || [])[1];
            Download.setDownload(sourceID, true);
            fileDownload(sourceURLWithAuth, originalFileName).then(() => Download.setDownload(sourceID, false));
            ReportActionComposeFocusManager.focus();
        },
```

or we can modify hideContextMenu function in PopoverReportActionContextMenu.js

```
hideContextMenu(onHideActionCallback, isMini = false) {
        if (_.isFunction(onHideActionCallback)) {
            this.onPopoverHideActionCallback = onHideActionCallback;
        }
        this.setState({
            selection: '',
            reportActionDraftMessage: '',
            isPopoverVisible: false,
        });

        if(isMini) {
            this.runAndResetOnPopoverHide()
        }
    }
```

It is working on my end.

**### What alternative solutions did you explore? (Optional)**

**Comment by Skalakid** [comment] 2023-07-03 14:28
Hey, I’m Michał from Software Mansion, an expert agency, and I will help close this issue out.

**Comment by aliammar1995** [comment] 2023-07-03 19:44
@Skalakid How do you think [this proposal ](https://github.com/Expensify/App/issues/20079#issuecomment-1614515180)

**Comment by Skalakid** [comment] 2023-07-04 09:53
Hi @aliammar1995, the first solution that you described will have a lot of repetitive code. `onPress` and `onPressMini` are very similar. I the second solution I don't like that we are doing something connected with MiniContextMenu in the PopoverContextMenu file

**Comment by Skalakid** [comment] 2023-07-04 09:56
@0xmiroslav how should the ideal solution look like? Should TextInput be focused instantly after the MiniContextMenu item is clicked? Or should it be focused after 1800ms when the item is ending to be in the `success ✔️` state?

**Comment by aliammar1995** [comment] 2023-07-04 09:57
@Skalakid it should work like in PopoverMenu

**Comment by aliammar1995** [comment] 2023-07-04 10:00
As I describe above, onPress method is designed and needed for PopoverMenu, Exactly, not designed for MiniContextMenu.
so we have to make other method for MiniContentMenu.

**Comment by Skalakid** [comment] 2023-07-04 10:04
@dayana7204 Thanks for the proposal but I think it is basically the same as the [previous one](https://github.com/Expensify/App/issues/20079#issuecomment-1574120279)

**Comment by Skalakid** [comment] 2023-07-04 10:08
@dragoilic I really like the fact that you created a separate function `closeContextMenu ` to manage hiding menu and focusing TextInput. However in the end it is the same situation as I described in my previous comment, we already got similar proposal

**Comment by aliammar1995** [comment] 2023-07-05 00:36
@Skalakid I don't like to use setTimeout.

**Comment by adelekennedy** [comment] 2023-07-05 02:24
not overdue - still discussing above

**Comment by Skalakid** [comment] 2023-07-05 06:25
@aliammar1995 I'm using the existing one, I'm not adding the new one like I wrote in my proposal

**Comment by Skalakid** [comment] 2023-07-05 09:11
@0xmiroslav what do think about my proposal?

**Comment by Skalakid** [comment] 2023-07-06 15:52
@0xmiroslav yes

**Comment by adelekennedy** [comment] 2023-07-10 20:14
@0xmiroslav coming back to this one, can we assign this job to @Skalakid or do we need more discussion here?

**Comment by youssef-lr** [comment] 2023-07-12 20:22
bump @0xmiroslav! :)

**Comment by youssef-lr** [comment] 2023-07-14 22:38
@Skalakid Your proposal is using `setTimeout` which we consider a workaround. Please try to submit a proposal that does not use `setTimeout` and other similar methods.

**Comment by Skalakid** [comment] 2023-07-17 09:34
@youssef-lr Yes, my proposal is using **existing** `setTimeout` logic and adding a callback that will launch after the state comes back from `success` to `normal`. I think this change can be beneficial in the future, in case of launching function after the success state ends. Using `isDelayButtonStateComplete` doesn't work, because it is changed to `true` just after the button click.
If we want to have a delay between the press action and the refocus we have to somehow use this logic.§

**Comment by Skalakid** [comment] 2023-07-17 09:38
@youssef-lr please confirm if we want to wait for the button state change before the refocus. The described [Expected result](https://github.com/Expensify/App/issues/20079#issue-1738534710) suggests that it should have a delay to work similarly to the normal context menu

**Comment by adelekennedy** [comment] 2023-07-17 20:05
@youssef-lr pending the above

**Comment by youssef-lr** [comment] 2023-07-17 21:31
@0xmiroslav can you please check the [proposal](https://github.com/Expensify/App/issues/20079#issuecomment-1636776460) above?

**Comment by Skalakid** [comment] 2023-07-21 09:38
@0xmiroslav I updated my proposal

**Comment by situchan** [comment] 2023-07-24 05:54
Coming from https://expensify.slack.com/archives/C02NK2DQWUX/p1690178033848139?thread_ts=1690177499.108059&cid=C02NK2DQWUX, I'd like to take this as C+

**Comment by situchan** [comment] 2023-07-25 18:27
I am inclined to preventDefault approach. I don't see any side effect from preventing blur of focused composer (either main or edit)
All other proposals are similar and they refocus after blur is already made.
I will still be testing this solution but no issues found so far.
Also it's good UX to keep focusing on composer while typing message and give reaction to any previous message. (No one proposed about quick emoji reactions)

There's significant difference between 2 approaches.

composer border glitch

https://github.com/Expensify/App/assets/108292595/f5e141f7-ceea-438e-85c6-11d33ad98607



no glitch

https://github.com/Expensify/App/assets/108292595/8693c4d9-85db-4035-af3a-1a6e3140a691



@youssef-lr @Skalakid what are your thoughts?

**Comment by situchan** [comment] 2023-07-26 07:36
> But on opening a popover and closing the popover the focus returns.

I checked slack and this even doesn't refocus. Btw, I believe it's not intentional to lose focus on any other chat platforms. They just didn't go beyond the default behavior.

> why do we need to refocus?

First of all, for consistency I think. This issue was reported from inconsistency between context menu and mini menu.

**Comment by Skalakid** [comment] 2023-07-26 08:35
@situchan I like the preventDefault approach, it looks much better when there is no refocus glitch. In my proposal, I focused on making both menus consistent, with similar refocus logic. But this different approach is interesting and I think we should give it a try. The question is if we want to make manus consistent or change the logic of the mini-context menu. @youssef-lr what you thought about that?

**Comment by adelekennedy** [comment] 2023-07-30 19:59
not overdue - pending response from @youssef-lr above

**Comment by adelekennedy** [comment] 2023-08-01 23:24
Bump for [this](https://github.com/Expensify/App/issues/20079#issuecomment-1650331220) @youssef-lr

**Comment by mountiny** [comment] 2023-08-02 14:44
@situchan @Skalakid @youssef-lr Lets go with whatever is more robust from code perspective but in the end lets pull  in Shawn from design team to check this out and let him decide which is better. 

Lets start on the PR

**Comment by situchan** [comment] 2023-08-03 15:56
> @situchan which solution has no glitch? That seems to be better UX, what person should I assign?

@mkhutornyi's [proposal](https://github.com/Expensify/App/issues/20079#issuecomment-1650047485)

**Comment by mountiny** [comment] 2023-08-06 18:36
@mkhutornyi go ahead with the PR please!

**Comment by adelekennedy** [comment] 2023-08-06 23:18
Not overdue! C has been assigned!

**Comment by adelekennedy** [comment] 2023-08-30 21:59
It looks like @mkhutornyi was assigned Aug 6th, PR was ready to be merged by the 8th but was actually merged on the 15th after @mountiny was back from ooo

**Comment by mountiny** [comment] 2023-08-31 00:31
Sounds fair thanks

**Comment by adelekennedy** [comment] 2023-08-31 18:34
### Payouts due:

Issue Reporter: $250 @jayeshmangwani 
Contributor: $2000 @mkhutornyi (Upwork)
Contributor+: $2000 @situchan (Upwork)

Eligible for 50% #urgency bonus? **Y**

Upwork job is [here](https://www.upwork.com/jobs/~01517d6a9b05f42ab8).

**Comment by adelekennedy** [comment] 2023-09-01 23:02
@mkhutornyi [here](https://www.upwork.com/jobs/~01f89b7d1f45d807b6)

**Comment by adelekennedy** [comment] 2023-09-04 23:02
pending final payment

**Closed** 2023-09-06 21:38 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
