### ISSUE TITLE
[HOLD for payment 2024-07-22] [Performance] Slow load of one-transaction reports

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#44162] opened 2024-06-21 14:19 UTC
One transaction reports seem to load slower than regular reports or regular transactions. And they have a weird UI while they are loading where the report looks like a one-transaction report, but there is also that same expense attached to the report as a comment. 

Let's fix this by fixing the weird UI while loading and making loading faster. 

Context here: https://expensify.slack.com/archives/C05LX9D6E07/p1718718047425429?thread_ts=1718652645.370349&cid=C05LX9D6E07

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify / @VictoriaExpensify</details>

**Comment by rinej** [comment] 2024-06-21 15:38
Hello it's Tomek from Callstack, I would like to work on that

**Comment by rinej** [comment] 2024-06-24 13:43
It looks like there's an error when displaying the ReportAction in ReportActionItem.tsx. Essentially, the app initially renders the previous report and then updates it after it has already been rendered. This issue might be caused by Onyx's optimistic approach, but it seems it could be fixed with a simple condition check. I'm currently investigating this further.

**Comment by puneetlath** [comment] 2024-06-24 13:58
Ok sounds good!

**Comment by rinej** [comment] 2024-06-26 15:24
I noticed two causes of that issue:

The first was that the `MoneyReportView` was being displayed even when there were no transactions in the current state (optimistic approach). This led to the view covering the screen unnecessarily, and once the transactions were fetched, it disappeared, causing a flickering effect. To address this, I adjusted the logic to ensure that the `MoneyReportView` is only displayed when there are transactions to show.

The second issue was with the `IOU` message action in the one-view transaction screen. By default, the `IOU` action was displayed, even though it was not supposed to be shown. It would only be removed after several re-renders, which caused the flickering effect. To fix this, I implemented filtering logic to remove the `IOU` action before the view is rendered. 

I am preparing a draft PR for these changes and will proceed with some testing to ensure that these adjustments do not break other flows

**Comment by puneetlath** [comment] 2024-06-26 15:35
Ok awesome. We can also make a test build and I can see if it solves the issue in my account.

**Comment by rinej** [comment] 2024-06-27 10:40
That would be great! Here is the PR -> https://github.com/Expensify/App/pull/44529

I am using not very heavy account, but still I could see the flickering, so at your account the fix would be more visible, please let me know :)

**Comment by puneetlath** [comment] 2024-07-24 20:26
@mkhutornyi can you do the checklist? And @VictoriaExpensify can you handle payment?

**Comment by VictoriaExpensify** [comment] 2024-07-29 12:05
@mkhutornyi - I have invited you to accept the [Upwork Job](https://www.upwork.com/ab/applicants/1817890356879032590/job-details). Please let me know once you have accepted it and I'll fix up your payment.

**Comment by VictoriaExpensify** [comment] 2024-08-01 21:59
@mkhutornyi - let me know once you've accepted the[ offer](https://www.upwork.com/nx/wm/offer/103363159) in Upwork :)

**Comment by VictoriaExpensify** [comment] 2024-08-05 21:11
Contributor: @rinej is from an agency-contributor and not due payment
ROLE: @mkhutornyi paid $250 via [Upwork]([Upwork Job](https://github.com/Expensify/App/issues/44162))

**Closed** 2024-08-07 00:58 UTC
Labels: Daily, Awaiting Payment, Bug
