### ISSUE TITLE
[$500] Web - Chat - Console error "Uncaught TypeError" shows up when sending a message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30935] opened 2023-11-07 00:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29561

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to any chat.
3. Send a text.

## Expected Result:
No console error shows up.

## Actual Result:
Console error "Uncaught TypeError" shows up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/eca1c98b-74bf-4fe0-b095-bc49d3aa8286

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0189b4f1ab639c484e</li>
        <li>Upwork Job ID: 1721795764122386432</li>
        <li>Last Price Increase: 2023-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 27553747</li>
<li>Ollyws | Contributor | 27880003</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-11-07 01:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Console error shows when sending a message

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/d5725c52bead4baa02ecec38915fc7c8c4316a4a/src/components/InvertedFlatList/index.js#L27
We should not use `React.createRef` in a function component because it recreates a new ref every time it is rendered

This is the root cause

### What changes do you think we should make in order to solve the problem?

Simply updating the above code to
```
    const listRef = useRef();
```

would solve the issue

Or we can remove the `listRef` from the component because it is not needed

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/46634214-aada-4a0d-8f22-a1fe09c05881


</details>

### What alternative solutions did you explore? (Optional)

**Comment by robertjchen** [comment] 2023-11-07 04:47
Hm, looks like that change went in 3 months ago. Any idea why it would be erroring now and not earlier? 🤔

**Comment by robertjchen** [comment] 2023-11-07 07:44
Perfect, thanks for the explanation- let's move forward with your proposal.

**Comment by s-alves10** [comment] 2023-11-28 17:22
@robertjchen @Ollyws 

The PR was merged into production 2 weeks ago. It looks like something went wrong here

**Comment by robertjchen** [comment] 2023-11-29 12:39
Hm, I'm confused- what's the expected behavior here?

**Comment by s-alves10** [comment] 2023-12-13 11:51
@robertjchen Pay day for this issue would be 22 Nov.

**Comment by robertjchen** [comment] 2023-12-13 14:15
Ah, I see it now- https://github.com/Expensify/App/pull/30962 was the fix but this issue was not properly automated for compensation. Will handle this, apologies for the delay.

**Comment by robertjchen** [comment] 2023-12-13 14:18
Is the original offer on Upwork still valid? 🤔

**Comment by s-alves10** [comment] 2023-12-13 22:55
@robertjchen Yes. I accepted the original offer. Thanks

**Comment by puneetlath** [comment] 2023-12-14 17:58
@s-alves10 has been paid. 

@Ollyws new offer is [here](https://www.upwork.com/nx/wm/offer/28061287). Please ping me here when you've accepted it.

**Comment by puneetlath** [comment] 2023-12-15 15:55
All paid. Thanks y'all!

**Closed by puneetlath** 2023-12-15 15:55 UTC
Labels: External, Engineering, Daily, Bug
