### ISSUE TITLE
[HOLD for payment] [$500] Android - Composer is hidden by native emoji picker - Reported by @rushatgabhane 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10483] opened 2022-08-23 04:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login
2. Go to a chat with any user
3. Tap on compose box to open the virtual keyboard
4. Select the emoji picker from the native virtual keyboard

## Expected Result:
composer is not hidden by native emoji picker

## Actual Result:
composer is hidden by native emoji picker

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.88-14
**Reproducible in staging?:** Y
**Reproducible in production?:**  N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/186072279-359e4caf-923a-4f2b-a82d-12ea6a49bffb.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rushatgabhane 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661203695542579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment] 2022-08-23 14:35
This doesn't seem like deploy blocker to me.

**Comment by jboniface** [comment] 2022-09-01 19:56
This was assigned to me while I was on leave (and signing out for the day), so I'm  reassigning it

**Comment by dylanexpensify** [comment] 2022-09-05 09:45
will get on this today

**Comment by dylanexpensify** [comment] 2022-09-05 13:34
Internal: https://www.upwork.com/ab/applicants/1566781835066662912/job-details
External: https://www.upwork.com/jobs/~0130daa37148ce0b9e

**Comment by dylanexpensify** [comment] 2022-09-13 08:14
Doubled price.

**Comment by mvtglobally** [comment] 2022-09-20 05:10
Issue not reproducible during KI retests. (First week)

**Comment by dylanexpensify** [comment] 2022-09-20 08:24
Holding on doubling

**Comment by Puneet-here** [comment] 2022-09-24 19:57
I think it's not reproducible anymore.

**Comment by mvtglobally** [comment] 2022-09-27 05:15
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2022-10-03 20:18
Issue not reproducible during KI retests. (Third week) @chiragsalian @dylanexpensify Are we ok to close this?

**Comment by chiragsalian** [comment] 2022-10-03 21:42
Yup if its not reproducible lets close this out. Feel free to reopen or create a new issue if it resurfaces.

**Comment by chiragsalian** [comment] 2022-10-07 18:22
I'll reopen so @dylanexpensify, sees it on his github tasks, but I'll unassign myself since there is nothing actionable here for me.

**Comment by mvtglobally** [comment] 2022-10-11 13:01
Issue not reproducible during KI retests. (Fourth week)

**Comment by mallenexpensify** [comment] 2022-10-11 22:01
@rushatgabhane , per the [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=If%20it%27s%20a%20valid%20job%20proposal%20that%20we%20choose%20to%20implement%20by%20deploying%20it%20to%20production%20%E2%80%94%20either%20internally%20or%20via%20an%20external%20contributor%20%E2%80%94%20then%20we%20will%20compensate%20you%20%24250%20for%20identifying%20and%20proposing%20the%20improvement.) I don't think you're eligible for the reporting bonus
> If it's a valid job proposal that we **choose to implement by deploying it to production — either internally or via an external contributor** — then we will compensate you $250 for identifying and proposing the improvement.

If there is a PR that fixed it we can review that PR, issue and bug report to see if you're eligible

**Comment by JmillsExpensify** [comment] 2022-10-12 14:45
@rushatgabhane closing based on @mallenexpensify's link to the guidelines, though please feel free to keep the discussion going.

**Comment by mallenexpensify** [comment] 2022-10-13 23:36
Thanks for the comment @rushatgabhane, we're[ updating CONTRIBUTING.md](https://github.com/Expensify/App/pull/11826) to clarify this  (bold below is new)
>  
If it's a valid job proposal that we choose to implement by deploying it to production — either internally or via an external contributor — then we will compensate you $250 for identifying and proposing the improvement. **If the bug is fixed by a PR that is not associated with your bug report, the contributor is not eligible for compensation unless they can find the PR that fixed the bug then show their bug report preceded the one associated with the PR.**

If you're able to find the PR the fixed this bug, please post in this issue, there isn't a timeline associated with potential payment

**Comment by JmillsExpensify** [comment] 2022-11-26 22:03
Re-opening based on the linked discussion.

**Comment by JmillsExpensify** [comment] 2022-11-26 22:10
Whoops, disregard the above.

**Comment by dylanexpensify** [comment] 2022-12-05 09:51
@JmillsExpensify shall we close this again? cc @rushatgabhane

**Comment by dylanexpensify** [comment] 2022-12-15 11:39
@0xmiroslav would you mind summarizing what you think would be a fair amount and why

**Comment by JmillsExpensify** [comment] 2022-12-23 17:40
Looks like this wasn't resolved while I was out, so I'll jump in now that I'm back. I think doubling the price of this issue is fair. That comes out to $1,000. @dylanexpensify is out for the holidays, and I think we still need to retest to ensure this is no longer a live issue. @mallenexpensify this might be a good one to take over since you're around over the holidays.

**Comment by mallenexpensify** [comment] 2022-12-23 23:51
I co-assigned.  I'll get to it _over the holidays_, maybe today but I got a lil bit to do before logging off in an ~hour.  Bumped to `Daily`.  Thanks for the patience @0xmiroslav

**Comment by mallenexpensify** [comment] 2022-12-27 20:13
Working on this @0xmiroslav , hoping to have an update tomorrow.

**Comment by mallenexpensify** [comment] 2022-12-28 19:57
Thanks @0xmiroslav for helping us fix the android keyboard issues.  I def saw multiple bug reports and GH issues for 'em.  

For https://github.com/Expensify/App/issues/11087 you were paid $3000, but $1000 was a bonus so, if we are discussing what compensation should be for a situation like this, we **shouldn't** take into account any bonuses for doing quick work.  I don't think you were compensated for other related issues but I might have missed that.  Generally speaking, for deciding on bonuses and partial payments, we've found it's best practice to use a percentage vs a dollar amount.  **So, for this issue, I think a 50% bonus is fair, and that'd be on the job price before the bonus, so $1000.**

It's hard to standardize on a process for payment for a PR that fixes multiple bugs (and... similarly, multiple bug reports that are fixed by a single PR).  I think it's safe to assume that _we_ weren't sure what was going on, by creating the multiple issues it helped us figure it out and also provided a level of urgency since your PR would fix the bugs.  

The bonus should be applied to https://github.com/Expensify/App/issues/11087 since that's the main issue.  I'll post over there and issue payment.

**Comment by mallenexpensify** [comment] 2022-12-28 20:05
I believe this issue can be closed now since there isn't an associated/linked PR for this. Comment/reopen if ya want.

**Closed by mallenexpensify** 2022-12-28 20:05 UTC
Labels: External, Engineering, Daily
