### ISSUE TITLE
[$1000] Home Address- “This field is required” error inconsistency

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#24450] opened 2023-08-11 18:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > profiles > personal details > home address
2. Click into any field (ex: "Address line 1")
3. Click into another field (ex: "Address line 2")
4. Click into a third field (ex: "City")
5. Exit Home address
6. Enter back into Home address
7. Click into a different first field and then into any other two fields (ex: "City", "Zip/Postcode", and "Address line 1")

## Expected Result:
Error when any of the following are clicked into and then left blank, at any time, in any combination

- Address line 1
- State / Province
- City
- Zip / Postcode

## Actual Result:
Only the first of the clicked required lines throws an error if left blank

Direction of the cursor dictates the missing field error. There is no error if we move the cursor from bottom to top but there is error if we move the cursor from top to bottom.

Also, the first required field where we put our cursor gives a missing field error but second one fails to give error as verified in step 3 and step 8
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/b714e525-80f7-4ca1-b407-8f84cccfb95d

https://github.com/Expensify/App/assets/38435837/5f58400e-f770-447a-8e2d-1e492f8efa74

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691089774442969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0119a7addc648210c5</li>
        <li>Upwork Job ID: 1691190540092907520</li>
        <li>Last Price Increase: 2023-08-14</li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-08-12 12:58
i am not able to reproduce a error message is shown everytime if a required field is blurred without a value.

**Comment by alphaboss1104** [comment] 2023-08-14 06:39
I can't reproduce this error.

**Comment by sonialiap** [comment] 2023-08-14 20:50
I can reproduce

**Reproduction steps:**
1. Go to settings > profiles > personal details > home address
2. Click into any field
3. Click into another field
4. Click into a third field

**Expected behavior:**
Error when any of the following are left blank, at any time, in any combination
- Address line 1
- State / Province
- City
- Zip / Postcode 

**Actual behavior:**
Only the first of the clicked required lines throws an error if left blank

https://github.com/Expensify/App/assets/17131195/a799179c-9f14-4d17-9c9c-319c5f5b0dc5

**Comment by sonialiap** [comment] 2023-08-14 20:56
Oh whoops, I was able to reproduce on new.expensify.com. But I'm not able to reproduce on staging.new.expensify.com so looks like this got fixed in the last few days. Closing

<img width="389" alt="image" src="https://github.com/Expensify/App/assets/17131195/2cbbbd83-649d-4bda-bf9f-dd52fa2b3a0e">

**Closed by sonialiap** 2023-08-14 20:56 UTC
Labels: External, Daily, Help Wanted, Bug
