### ISSUE TITLE
[$250] Android - On scrolling up and tapping plus icon, page scrolled down & can't scroll up page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51034] opened 2024-10-17 15:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5096105
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Open chat with long conversation
3. Scroll up and send the message
4. Note page scrolled down to new message
5. Again scroll up and tap plus icon and note user scrolled down now
6. Note scroll up and note user can't fully scroll up the page
7. Send a message
8. Now again scroll up and note user can scroll up fully now

## Expected Result:
On scrolling up and tapping plus icon, page must not scrolled down & must able to scroll up page fully after that

## Actual Result:
On scrolling up and tapping plus icon, page scrolled down & can't scroll up page fully after that

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/c9e98fdf-440a-4043-901c-ecce2ff0dc6d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847327594039972213</li>
        <li>Upwork Job ID: 1847327594039972213</li>
        <li>Last Price Increase: 2024-11-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by mvtglobally** [comment] 2024-10-30 09:44
Issue not reproducible during KI retests. (First week)

**Comment by lschurr** [comment] 2024-10-30 15:50
@ishpaul777 are you able to reproduce this?

**Comment by lschurr** [comment] 2024-11-05 20:08
Closing since we can't reproduce.

**Closed by lschurr** 2024-11-05 20:08 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
