### ISSUE TITLE
[HOLD for payment 2024-08-29] [$250] Voice recognition doesn't work on mobile web on Android in the message compose input

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44394] opened 2024-06-25 14:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-17
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1719169189159419

## Action Performed:
1. Go to staging.new.expensify.com
2. Initiate a DM to any user
3. Tap mic icon on keyboard and say a message to be composed

## Expected Result:
Message composed without any issues
## Actual Result:
Voice recognition does not work if you begin it in an empty field, lose focus and it stops 
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [X] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f063fe0495eff4ac</li>
        <li>Upwork Job ID: 1805694285589168826</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103185927</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by deetergp** [comment] 2024-06-25 20:07
This one seems like it could be done by an External contributor.

**Comment by diegohosilver** [comment] 2024-06-27 12:55
I was able to reproduce it in dev and stage

https://github.com/Expensify/App/assets/20136219/8c8490dd-5f2d-461b-b345-f31c20799195

**Comment by MitchExpensify** [comment] 2024-06-27 22:24
@diegohosilver It looks like its working in your video, am I missing something?

**Comment by diegohosilver** [comment] 2024-06-28 01:30
@MitchExpensify the focus is interrupted when the input is empty. I had to press the mic button again to continue with the dictation.

I narrowed down the problem to the `RNMarkdownTextInput` component. The usage of MarkdownTextInput from '@expensify/react-native-live-markdown' is what introduced this behavior. I will continue my testing tomorrow

**Comment by diegohosilver** [comment] 2024-06-30 03:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Android dictation cuts off in Chrome web

### What is the root cause of that problem?

The package `@expensify/react-native-live-markdown` is causing this behavior. The code below is causing the dictation to cut off when setting `targetElement.innerHTML = ''`

```
 if (!rootSpan || rootSpan.innerHTML !== dom.innerHTML) {
      targetElement.innerHTML = '';
      targetElement.innerText = '';
      target.appendChild(dom);

      if (BrowserUtils.isChromium) {
        moveCursor(isFocused, alwaysMoveCursorToTheEnd, cursorPosition, target);
      }
 }
```

### What changes do you think we should make in order to solve the problem?

1. Check if the current text is different from the parsed ranges to HTML nodes
2. Clear the `targetElement` innerHTML by removing child nodes
3. Append the HTML nodes to the `targetElement` by cloning them

### What alternative solutions did you explore? (Optional)

N/A

**Comment by eh2077** [comment] 2024-06-30 14:23
@diegohosilver Thanks for your proposal! Can you elaborate on why this issue happens on mobile Chrome only?

**Comment by diegohosilver** [comment] 2024-06-30 15:55
@eh2077 no problem!

I'm not 100% sure. I would say it has to do with Android's WebView implementation:
- It might handle contentEditable elements differently than other platforms.
- It might be more sensitive to DOM updates during ongoing input events, causing the dictation to cut off when the DOM is modified.

I'd like to provide an answer on **why** this is happening, but this is where the rabbit hole led me.

**Comment by eh2077** [comment] 2024-07-01 00:11
@diegohosilver Thanks for the comment. But the root cause is still not clear to me. 

Looking for better proposals

**Comment by eh2077** [comment] 2024-07-04 15:10
@MitchExpensify Should we consider increasing the bounty to get proposals to dig into the root cause of this issue?

**Comment by MitchExpensify** [comment] 2024-07-04 19:26
Early days for a bump, lets give it another week

**Comment by jacobkim9881** [comment] 2024-07-05 13:51
It's not reproducible.

**Comment by eh2077** [comment] 2024-07-10 01:45
Still waiting for proposals

**Comment by mvtglobally** [comment] 2024-07-11 03:46
Issue not reproducible during KI retests. (First week)

**Comment by muttmuure** [comment] 2024-07-11 11:35
Sounds like this might be fixed

**Comment by muttmuure** [comment] 2024-07-11 11:36
Let's ask David to retest it in the thread

**Comment by muttmuure** [comment] 2024-07-11 11:37
Asking here: https://expensify.slack.com/archives/C05LX9D6E07/p1719169189159419

**Comment by muttmuure** [comment] 2024-07-15 09:58
David is still experiencing this

**Comment by eh2077** [comment] 2024-07-15 10:08
Still waiting for proposals

**Comment by MitchExpensify** [comment] 2024-07-16 19:04
Asking CT for help with this here https://expensify.slack.com/archives/C03UK30EA1Z/p1721150619478589

**Comment by puneetlath** [comment] 2024-07-18 18:09
CT said they'll assign someone tomorrow.

**Comment by mvtglobally** [comment] 2024-07-19 03:14
Issue not reproducible during KI retests. (Second week)

**Comment by MitchExpensify** [comment] 2024-07-19 18:50
I don't _think_ we need another Bug Zero team assignee here as I head out on paternity seeing as @puneetlath is on the team. As such unassigning myself without tracking down a leave buddy

**Comment by eh2077** [comment] 2024-07-22 23:50
@JKobrynski Do you have any updates on this?

**Comment by muttmuure** [comment] 2024-07-24 09:15
Pinged @JKobrynski in Slack

**Comment by JKobrynski** [comment] 2024-07-25 13:25
I've spent some time investigating this issue today and I've narrowed it down to `@react-native-live-markdown`. I forked the repo and was able to reproduce this exact bug in the example web app. I'm going to dig deeper into the package itself to try to understand why that's happening. If necessary, I'm going to create an issue in the package's repo and also contact SWM devs who were working on it to speed things up.

**Comment by JKobrynski** [comment] 2024-07-25 13:58
Another update! I was able to pinpoint the exact function that is causing this bug, will try to fix it

**Comment by JKobrynski** [comment] 2024-07-26 12:13
Today's investigation led me to a conclusion that the exact thing that causes this bug is this line 

```tsx
ref={setRef}
```

in **MarkdownTextInput.web.tsx**. If removed, everything works fine. 

I'm going to continue my work on it, and try to make this ref work.

**Comment by JKobrynski** [comment] 2024-07-29 14:39
Today's further investigation led me from `setRef` function to `parseText` method of **parserUtils.ts**, more specifically the following three lines:

```tsx
  targetElement.innerHTML = '';
  targetElement.innerText = '';
  target.appendChild(dom);
```

that seem to be causing the issue. The `dom` value comes from `parseRangesToHTMLNodes` method from the same file, and I suspect that this where the things get mixed up. I will continue my investigation there.

**Comment by diegohosilver** [comment] 2024-07-29 15:01
@JKobrynski check my [proposal](https://github.com/Expensify/App/issues/44394#issuecomment-2198416755) from a month ago. I discovered that too and proposed a fix. It might help you a bit

**Comment by BartoszGrajdek** [comment] 2024-08-02 12:45
Hi! Tried debugging this issue a little bit yesterday/today to help out, but didn't manage to find anything yet due to the lack of time. 

Unfortunately, I'm OOO till 11.08, but once I'm back I'll try helping you here if this doesn't get fixed.

Something I also told Julian is that if I remember correctly we used to have the `parseText` method without `targetElement.innerHTML = '';` (something like @diegohosilver proposal) but the problem was that in some cases it added additional line breaks, or broke cursor positioning, keep that in mind if you go that route and make sure it doesn't introduce any similar regressions.

**Comment by puneetlath** [comment] 2024-08-07 19:40
This is not overdue. It's actively being worked on.

**Comment by puneetlath** [comment] 2024-09-03 21:33
In the Slack [thread](https://expensify.slack.com/archives/C05LX9D6E07/p1724780390782329?thread_ts=1719169189.159419&cid=C05LX9D6E07) it sounds like @quinthar is still experiencing the issue. So going to hold off on paying/closing this just yet.

**Comment by Skalakid** [comment] 2024-09-04 13:31
Hello, I'm Michał from SWM. I also reproduced this issue when using Live Markdown. Here I prepared a [fix](https://github.com/Expensify/react-native-live-markdown/pull/468) inside the library

**Comment by puneetlath** [comment] 2024-09-10 17:35
@Skalakid we're just waiting to upgrade the rn-live-markdown version in the app, is that right?

**Comment by Skalakid** [comment] 2024-09-11 07:26
@puneetlath Hi, yes that's the last thing that we have to do. However, I see that there is already https://github.com/Expensify/App/pull/48626#issuecomment-2342856145 that is bumping the LM version and it will contain my fixes for this issue. So I wrote the comment under the PR to include test steps for QAs

**Comment by puneetlath** [comment] 2024-09-16 19:06
This is on prod. Messaged @quinthar in the [Slack thread](https://expensify.slack.com/archives/C05LX9D6E07/p1726513570133709?thread_ts=1719169189.159419&cid=C05LX9D6E07) to have him confirm it's working for him now.

**Comment by puneetlath** [comment] 2024-09-16 19:14
Ok looks like we're good to go here. @eh2077 were you involved in this one at all? Or am I good to close this?

**Comment by eh2077** [comment] 2024-09-17 00:34
@puneetlath I helped review earlier proposals. After it's picked up by agency team, I helped review the first PR here https://github.com/Expensify/App/pull/47407#issuecomment-2291125673 but it doesn't fix the issue when the update hits production. Though it was working fine when testing the PR. I haven't checked what caused the back and forth in the live markdown repo.

Given that, should I be eligible for payment on this task? Hmm, whatever the team think is best works for me, thanks!

**Comment by puneetlath** [comment] 2024-09-17 15:30
Ok, I think it's fair to pay then. 

Payment summary: 
- C+ - $250 - @eh2077 - to be paid via NewDot

Thanks everyone!

**Closed by puneetlath** 2024-09-17 15:30 UTC
Labels: External, Daily, Awaiting Payment, Bug, AutoAssignerNewDotQuality

**Comment by eh2077** [comment] 2024-10-10 16:07
Requested in NewDot

**Comment by JmillsExpensify** [comment] 2024-10-11 09:33
$250 approved for @eh2077
