### ISSUE TITLE
[$250] LHN - After submitting expense to WS, GBR is displayed briefly, then is replaced by pin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42526] opened 2024-05-23 14:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4548968
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: User has created a WS in ND.
1. Navigate to the WS chat
2. Create and Submit an expense
3. Submit the expense
4. Navigate to the LHN

## Expected Result:
Expected result depends on workspace settings, but should be: 

- Closed reports: No GBR in LHN (unless the workspace has payments enabled). 
- Submitted report pending action: GBR for admin that is supposed to action it, rather than the GBR appearing momentarily, and then disappearing in favor of the pinned icon.

## Actual Result:
The GBR is displayed briefly, it disappears in a couple seconds and is replaced by the pin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cfda55f6-369a-4b8a-86e0-dbc555c0f90a

https://github.com/Expensify/App/assets/78819774/ed6ee51a-9fe2-47b2-975e-c96196fc3134

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01348e2facc5ff13b2</li>
        <li>Upwork Job ID: 1795829696805433344</li>
        <li>Last Price Increase: 2024-06-05</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reviewer | 102670060</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-05-23 14:29
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by slafortune** [comment] 2024-05-23 21:07
I will be on vacation until June 4th - I have not yet looked at this so I'll simply reassign. TIA!!

**Comment by joekaufmanexpensify** [comment] 2024-05-23 21:38
Hey @slafortune , as an fyi for OOO re-assignments, you're supposed to add an additional assignee, but stay assigned so you can take the issue back over once you're back from OOO (assuming it's still open). Here's the [relevant SO](https://stackoverflowteams.com/c/expensify/questions/8836) where the process is outlined. 

I'm going to re-add you to the issue, but happy to tackle it while you're OOO!

**Comment by joekaufmanexpensify** [comment] 2024-05-23 21:38
Going to work on triaging this today

**Comment by slafortune** [comment] 2024-05-23 22:08
Oh!  I have on ones I've had a minute to look at, just not the other few.  Thanks!

**Comment by joekaufmanexpensify** [comment] 2024-05-24 14:34
>A GBR is displayed next to the WS chat, indicating action is needed

@lanitochka17 why would the expected behavior be that we would show a GBR for a report that is submitted when there are no approvals enabled? I would think the report would be submitted, and then is all set.

**Comment by joekaufmanexpensify** [comment] 2024-05-30 15:21
Waiting for proposals

**Comment by joekaufmanexpensify** [comment] 2024-06-03 13:29
Same

**Comment by joekaufmanexpensify** [comment] 2024-06-03 13:38
@Pujan92 do you agree this is external?

**Comment by slafortune** [comment] 2024-06-07 20:01
Checking here - https://expensify.slack.com/archives/C03UK30EA1Z/p1717790478531449

**Comment by VickyStash** [comment] 2024-06-10 11:28
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment] 2024-06-10 15:33
I've investigated the issue, and it looks like the main reason why the GBR indicator appears momentarily and then disappears in favor of the pinned icon after submitting an expense is that the user tries to Submit expenses using an account with out of date billing information.

When a user Submits expenses in this case, the API returns an error `Policy billing is out of date. Please visit your settings page on Expensify.com and update your billing information.` No error indication appears and it makes GBR disappear. See the video:

https://github.com/Expensify/App/assets/23176449/7c60738f-e841-4dca-822b-3d6c288b2134

It's a known issue, there was [an open ticket](https://github.com/Expensify/App/issues/42081) for that. However, no solutions were applied because the problem should be resolved with [paywall functionality](https://github.com/Expensify/App/issues/42081#issuecomment-2113564482).

**Comment by slafortune** [comment] 2024-06-10 18:54
Thanks for the details @VickyStash !  I'll close this 👍

**Closed by slafortune** 2024-06-10 18:54 UTC
Labels: External, Daily, Bug
