### ISSUE TITLE
[$500] Web - Send money - Save and continue button infinitely loading after entering additional details

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29380] opened 2023-10-11 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-6

**Reproducible in staging?:** Y

**Reproducible in production?:** No. The "Send money" option is not present in production

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Navigate to OldDot, log in, and add a personal bank account (Fidelity)
2. Go to ND and log in to the same account
3. Navigate to any conversation
4. Click on "+" button > Send money
5. Enter the amount and select "Next"
6. On the final review screen, select "Pay with Expensify"
7. On the "Additional details, fill out the fields
8. Click on the "Save&Continue" button

## Expected Result:
User is able to proceed to the Onfido privacy page

## Actual Result:
The "Save&Continue" button is infinitely loading, user is unable to proceed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/7e7b3f25-75e1-45a1-a976-94164ea686d3

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b05455d41ac4f2b6</li>
        <li>Upwork Job ID: 1712201478765879296</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by jasperhuangg** [comment] 2023-10-11 22:36
cc @techievivek since this seems related to your recent Send Money PR

**Comment by sakluger** [comment] 2023-10-11 23:17
I'm headed out for the next few hours, I'll help tomorrow if needed.

**Comment by luacmartins** [comment] 2023-10-11 23:21
I don't think this is an issue with NewDot. On staging, the `UpdatePersonalDetailsForWallet` request is returning `Please review your account number and routing number one more time before continuing. Reimbursements are not reversible.`. That seems like an issue with the bank account we're using for test, so not an issue. That being said we should be displaying an error to the user, which is the real issue here.

Gonna remove the blocker label and keep this open to address the error message issue.

**Comment by luacmartins** [comment] 2023-10-11 23:46
PR [here](https://github.com/Expensify/Web-Expensify/pull/39189)

**Comment by sakluger** [comment] 2023-10-18 16:09
@luacmartins will https://github.com/Expensify/Web-Expensify/pull/39205 fix this issue? Or are you working on some other PR? Either way, it sounds entirely backend, so we can remove @eVoloshchak's assignment, right?

**Comment by luacmartins** [comment] 2023-10-19 03:44
Yes, it should have been fixed in that PR. We can retest this now that the PR made it to production.

**Comment by sakluger** [comment] 2023-10-23 20:22
@izarutskaya could you please retest this when you haev a chance and let us know if it's fixed or still reproduceable in the latest build? Thanks!

**Comment by sakluger** [comment] 2023-11-03 05:52
Bump @izarutskaya, could you please retest this?

**Comment by luacmartins** [comment] 2023-11-28 00:35
Closing this issue since it doesn't seem to be reproducible anymore. Please reopen if needed.

**Closed by luacmartins** 2023-11-28 00:35 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Bug
