### ISSUE TITLE
[HOLD for payment 2024-06-05] [$500] Android - Chat - Edited url is not shown & Url is changed as URL name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40564] opened 2024-04-19 13:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4498682
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Enter an url and send
4. Long press the url message and edit url and save it
5. Copy to clipboard and paste in compose
6. Note correct edited url displayed
8. Launch Android app and open a report
9. Paste the same copy to clipboard message and send it
10. Long press and tap edit comment
11. Note edited url is not displayed
12. Go to mweb report
13. Clear the compose message
14. Long press the url message and select edit comment
15. Change url name and save it
16. Copy to clipboard and paste in compose
17. Note pasted message is correct
18. Paste the same clipboard message in Android compose and send it
19. Long press the message and select edit comment
20. Note url is changed same as url name

## Expected Result:
Altering url name and url, then copy to clipboard and pasting must show correctly in Android. Edited url must be shown. Url must not be changed as url name

## Actual Result:
Altering url name and url, then copy to clipboard and pasting shows correctly in mweb but displayed incorrectly in Android. Edited url is not shown. Url is changed as url name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/62fbe8c4-d9aa-44f5-888e-d524dfea8ce9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0160742901ec92ef7d</li>
        <li>Upwork Job ID: 1783248511413014528</li>
        <li>Last Price Increase: 2024-05-09</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>samilabud | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by lanitochka17** [comment] 2024-04-19 13:10
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-19 13:10
We think that this bug might be related to #vip-vsp

**Comment by johncschuster** [comment] 2024-04-24 21:35
I've added this to the #vip-vsb project and triaged it out

**Comment by DylanDylann** [comment] 2024-04-29 16:41
Looking for proposals

**Comment by johncschuster** [comment] 2024-05-01 21:18
Still looking for proposals. Let's raise this in Slack if we don't get anything in a day or so.

**Comment by DylanDylann** [comment] 2024-05-07 07:42
@johncschuster Should we double price to get more eyes?

**Comment by johncschuster** [comment] 2024-05-09 21:28
Thanks for the suggestion, @DylanDylann! I've bumped the price.

**Comment by samilabud** [comment] 2024-05-10 16:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android chat copy URLs in plain markdown format and other platforms use the HTML format

### What is the root cause of that problem?
We are using navigator.clipboard to handle the copy in web client that supports it, but Android Native do not support it and we use Clipboard library (@react-native-clipboard/clipboard) to handle the copy functionality in the composer. That said we are using the next function to decide if we going to set the copy as plain markdown text or as html:

https://github.com/Expensify/App/blob/94c0bae3ec5fd718156d08df26ea0c83709febdb/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L43-L51

When we copy from android we can paste the result in any composer (web, native, ios, desktop) and going to work because is a markdown format (in plain text).

When we copy the content as HTML we are using `Clipboard.setHtml(content, plainText) ` this means the first option is HTML and second the plain text (not markdown format), if the platform/software do not support HTML going to use the plain text and this is the why of this issue.

### What changes do you think we should make in order to solve the problem?
Inside the [setClipboardMessage](https://github.com/Expensify/App/blob/94c0bae3ec5fd718156d08df26ea0c83709febdb/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L43) we should validate if the content is only an URL, if that we should use the markdown format `Clipboard.setString(parser.htmlToMarkdown(content));`, with this we going to have a standard copy of any link when using the composer.

**Comment by johncschuster** [comment] 2024-05-13 20:46
[Bumped in Slack!](https://expensify.slack.com/archives/C02NK2DQWUX/p1715633158718909)

**Comment by DylanDylann** [comment] 2024-05-14 04:17
On my list today

**Comment by DylanDylann** [comment] 2024-05-14 10:50
@samilabud I tested your solution but It doesn't work for me. Could you provide a draft branch?

**Comment by samilabud** [comment] 2024-05-14 11:33
> @samilabud I tested your solution but It doesn't work for me. Could you provide a draft branch?

Of course, let me know if this work for you: https://github.com/Expensify/App/pull/42147

**Comment by DylanDylann** [comment] 2024-05-15 09:45
@samilabud Thanks. Your proposal looks great to me. But there is a small problem with your regex

https://github.com/Expensify/App/assets/141406735/db908d92-c976-44fb-bf9a-9044409ad0fe

I think in this case isAnchorTag should be false

**Comment by DylanDylann** [comment] 2024-05-15 09:47
@samilabud Thanks. Your proposal looks great to me. But there is a small problem with your regex
 
https://github.com/Expensify/App/assets/141406735/db908d92-c976-44fb-bf9a-9044409ad0fe

But I am not sure if it is a bug, It also be minor and we can discuss it in the PR phrase

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-05-16 04:16
@samilabud Please note that only create PR after you are assigned officially

**Comment by johncschuster** [comment] 2024-05-29 14:30
I'll be issuing payment for this one next Wednesday. @DylanDylann, can you complete the BZ Checklist above before then? Thank you!

**Comment by DylanDylann** [comment] 2024-06-05 04:35
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


**Regression Test Proposal**
1. Go to expensify url or open the native app (IOS or Android or Desktop)
2. Tap on a report
3. Enter an url and send
4. Long press the url message
5. Select copy to clipboard and paste in compose
6. Note the markdown format
7. This could be pasted in other/same platform with the same format
8. Note the url name and url could be different and works (optional)


Do we agree 👍 or 👎

**Comment by johncschuster** [comment] 2024-06-05 13:32
Payment has been issued and the QA issue has been linked. Let's close this up!

**Closed by johncschuster** 2024-06-05 13:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
