### ISSUE TITLE
Web – Chat - The font is changed in the compose box upon completing a code block markdown

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39273] opened 2024-03-29 17:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58.0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Open any chat
2. Write "```text``" in the compose box
3. Add "`" to the end of it
4. Remove the last "`"
## Expected Result:
The font shouldn't change

## Actual Result:
The font is changed in the compose box upon completing a code block markdown. It reverts to the original one if you remove the last "`

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/eca7c223-3c1b-4245-8cc8-19647e246fb0

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-03-29 17:55
We think this bug might be related to #vip-vsb

**Comment by m-natarajan** [comment] 2024-03-29 17:55
@AndrewGable  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by AndrewGable** [comment] 2024-03-29 17:57
Agree this feels like intended behavior, but doing a quick confirmation before closing out

**Comment by AndrewGable** [comment] 2024-03-29 18:02
Confirmed, closing!

**Closed by AndrewGable** 2024-03-29 18:02 UTC
Labels: DeployBlockerCash, Engineering, Daily, Bug
