### ISSUE TITLE
[$1000] Web -  After request money, user is not seeing who sent the message in group conversation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26031] opened 2023-08-27 12:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account
2. Create a group with 3 people
3.  Request money from Account A
4. Send message from Account B or C to the group conversation

## Expected Result:
User can see who sent the message

## Actual Result:
After request money, user is not seeing who sent the message in group conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (14) (1)](https://github.com/Expensify/App/assets/93399543/256b931f-5f89-4e93-845b-3c47462c2fb8)

![12345](https://github.com/Expensify/App/assets/93399543/b5de0702-eae0-4ee6-a9c2-cb42a6c8ee0f)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @vitHoracek 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692307206737309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c73976e93aabc959</li>
        <li>Upwork Job ID: 1697342081334173696</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-08-27 13:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For immediate messages after requesting money, we do not show user details of who sent the message

### What is the root cause of that problem?
We do not show the user details and it will be considered as `displayAsGroup` bcoz it is sent within the set time interval. For specific this scenario where the previous action is `REPORTPREVIEW` we don't have any specific condition to allow it to show the user details.

### What changes do you think we should make in order to solve the problem?
We need to add a new condition where we won't consider the current action as `displayAsGroup` when the previous action is `REPORTPREVIEW`. With that, it won't show this in a group and considered as a separate message by showing user details.

https://github.com/Expensify/App/blob/c029dc509d03fd13ece058ba89ab25c4318a9050/src/libs/ReportActionsUtils.js#L263-L269

```
   // Comment is grouped if the previous action isn't REPORTPREVIEW
    if(isReportPreviewAction(previousAction)) {
        return false;
    }
```

**Comment by puneetlath** [comment] 2023-08-31 20:15
Opening up for proposals. @aimane-chnaif just FYI @Pujan92 has already made a proposal above.

**Comment by puneetlath** [comment] 2023-09-04 15:41
@aimane-chnaif friendly bump for your thoughts on Pujan's proposal above.

**Comment by Pujan92** [comment] 2023-09-11 13:05
> > we won't consider the current action as displayAsGroup when the previous action is `REPORTPREVIEW`
> 
> @Pujan92 what about adjacent `REPORTPREVIEW`s?

@aimane-chnaif I think we are showing a single updated ReportPreview for the report, so there might be no adjacent REPORTPREVIEW from the same user.

<img width="1440" alt="Screenshot 2023-09-11 at 18 31 26" src="https://github.com/Expensify/App/assets/14358475/90bd288d-7a7b-4228-ac60-30b2a76844a3">

**Comment by puneetlath** [comment] 2023-09-13 02:59
@aimane-chnaif thoughts?

**Comment by puneetlath** [comment] 2023-09-14 16:34
Even if there aren't now. There will be scenarios in the near future where you can have multiple reports in different states in the chat.

**Comment by Pujan92** [comment] 2023-09-15 12:28
Yes @aimane-chnaif , that will not show as `displayAsGroup` for the adjacent previews. 

**Current**

<img width="1440" alt="Screenshot 2023-09-14 at 21 55 41" src="https://github.com/Expensify/App/assets/14358475/b5d3e814-934c-45b8-8a62-3575905edc12">
<img width="1440" alt="Screenshot 2023-09-14 at 21 55 51" src="https://github.com/Expensify/App/assets/14358475/4e686996-8694-43d3-b53b-54fdb938236a">

**After Suggested Fix**

<img width="1440" alt="Screenshot 2023-09-14 at 21 57 42" src="https://github.com/Expensify/App/assets/14358475/e04332ce-1ff2-490f-a32d-a5badb835825">
<img width="1440" alt="Screenshot 2023-09-14 at 21 57 53" src="https://github.com/Expensify/App/assets/14358475/f33b4f35-498d-46ec-a0ff-e2ad8ea24492">

----------

In that case, we can't only rely on previous `REPORTPREVIEW ` action. We need to consider current action type and if it is `REPORTPREVIEW` then needs to compare `actorAccountID`.

**Comment by puneetlath** [comment] 2023-09-19 07:20
That makes sense to me, yes.

**Comment by puneetlath** [comment] 2023-09-22 05:20
Updating the bounty to try and get some proposals.

**Comment by Pujan92** [comment] 2023-09-22 13:30
@aimane-chnaif I have updated my [proposal](https://github.com/Expensify/App/issues/26031#issuecomment-1694672956). Plz consider reviewing it.

**Comment by puneetlath** [comment] 2023-09-25 10:36
@aimane-chnaif mind taking a look at the updated proposal?

**Comment by puneetlath** [comment] 2023-10-12 16:25
@aimane-chnaif bump!

**Comment by puneetlath** [comment] 2023-10-19 16:42
Any update @aimane-chnaif?

**Comment by trjExpensify** [comment] 2023-10-20 15:45
Oh wait, did I just log the same bug then?

**Comment by trjExpensify** [comment] 2023-10-20 15:53
The bug I logged is with regards to the avatar and title of the ReportPreview not showing when there's a message before it, yes.

**Comment by Pujan92** [comment] 2023-10-20 16:18
@aimane-chnaif We were focused more here when the chat messages were sent after REPORTPREVIEW, I have updated the [proposal](https://github.com/Expensify/App/issues/26031#issuecomment-1694672956) a bit to consider the condition where REPORTPREVIEW comes after chat message.

**Comment by abdel-h66** [comment] 2023-10-20 17:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report preview and Messages are displayed as group when they should not. 

### What is the root cause of that problem?
The logic that handles the grouping only checks for `actorAccountID` to make the decision of grouping. So when the following cases happen 


### Scenario 1 
1. User B sends a message (actor is user B)
2. User A requests money from User B (actor is B)
Then the action will be grouped 

### Scenario 2 
1. User A sends message to user B (actor = user A)
2. User B sends a request to user A (actor = user A)
The action will be grouped 

### Scenario 3
1. User B sends a request to user A (actor = user A)
2. User A sends a message to user B (actor = user A)
The action will be grouped

### Scenario 4
1. User A sends a request to user B (actor = user B)
2. User B sends a message to user A (actor = user B)
The action will be grouped

### Scenario 5
1. User A sends a request to user B (actor = user B)
2. User B sends a request to user A (actor = user A)
The action group will display both actions, which is what we want. 


### What changes do you think we should make in order to solve the problem?

It appears that we only need to check if one of the actions are a report preview. and if the actor is the same, then we don't group 

```js
    function oneOfActionsIsPreview(actionOne, actionTwo) {
        return isReportPreviewAction(actionOne) || isReportPreviewAction(actionTwo);
    }

    if (currentAction.actorAccountID === previousAction.actorAccountID && oneOfActionsIsPreview(currentAction, previousAction)) {
        return false;
    }
```

### Scenario 1 
1. User B sends a message (actor is user B)
2. User A requests money from User B (actor is B)
Then the action will be not be grouped 

### Scenario 2 
1. User A sends message to user B (actor = user A)
2. User B sends a request to user A (actor = user A)
Then the action will be not be grouped 

### Scenario 3
1. User B sends a request to user A (actor = user A)
2. User A sends a message to user B (actor = user A)
Then the action will be not be grouped 

### Scenario 4
1. User A sends a request to user B (actor = user B)
2. User B sends a message to user A (actor = user B)
Then the action will be not be grouped 

### Scenario 5
1. User A sends a request to user B (actor = user B)
2. User B sends a request to user A (actor = user A)
The action group will display both actions, which is what we want. 

### What alternative solutions did you explore? (Optional)

N/A

**Comment by trjExpensify** [comment] 2023-10-20 17:39
Can we please prioritise reviewing these and moving it forward @aimane-chnaif? This has come up as being confusing in the money2020 activation flow and this issue has been around now for a couple of months. Thanks!

**Comment by trjExpensify** [comment] 2023-10-20 18:02
Thank you!

**Comment by trjExpensify** [comment] 2023-10-23 14:58
@aimane-chnaif how'd the reviews go?

**Comment by puneetlath** [comment] 2023-10-27 13:55
Sounds good to me.

**Comment by puneetlath** [comment] 2023-11-20 16:32
Oh yes, right you are. Not sure why the automation didn't run.

**Comment by puneetlath** [comment] 2023-11-20 16:42
Can you please apply to this upwork job @tsa321? And then please comment here when you have. https://www.upwork.com/jobs/~01b2834eb1b18efbfe

**Comment by puneetlath** [comment] 2023-11-21 18:28
All paid, thanks y'all!

**Closed by puneetlath** 2023-11-21 18:28 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
