### ISSUE TITLE
Web - Timezone - Console errors when changing Timezone offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13532] opened 2022-12-12 21:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12201

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login
2. Change URL to ".....staging.new.expensify.com/settings/profile/timezone"
3. Go offline
4. Change Timezone

## Expected Result:
No console errors expected

## Actual Result:
Console errors are displayed

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.38.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/207157081-ccd502a7-239c-466a-a27a-042612ea9442.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-12-12 22:54
Is this a dupe issue of https://github.com/Expensify/App/issues/13311

**Comment by marcaaron** [comment] 2022-12-12 22:56
Can't reproduce this. Seems possibly related to Windows? What device / OS / etc?

**Comment by dylanexpensify** [comment] 2022-12-13 18:15
This looks like a dupe to me

**Comment by dylanexpensify** [comment] 2022-12-16 09:45
closing for dupe

**Closed by dylanexpensify** 2022-12-16 09:45 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
