### ISSUE TITLE
 iOS - Chat - Clown face emoji can't be selected if you type ":clown_face"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42439] opened 2024-05-21 16:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with any account
2. Open any chat or room
3. Tap inside the composer
4. Type ":clown_face"
5. Tap on the emoji

## Expected Result:
I should be able to select it

## Actual Result:
Clown face emoji can't be selected if you type ":clown_face". I have tested a few different ones and it seems to only affect this one emoji. It can be selected if you use the emoji picker and search for this emoji

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4e027aa7-4e98-4c2d-84e5-e0d14cceedc8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-21 16:34
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-21 16:34
We think that this bug might be related to #vip-vsp

**Comment by joekaufmanexpensify** [comment] 2024-05-21 19:51
IMO, this is not a bug we should be prioritizing right now. We have many more important fish to fry. Closing this for now.

**Closed by joekaufmanexpensify** 2024-05-21 19:51 UTC
Labels: Daily, Bug
