### ISSUE TITLE
New contacts are not shown as Recents/contacts

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25647] opened 2023-08-22 02:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a New Chat with a new user.
2. Send a Message
3. Go out of the chat and Click on the PLUS button.
Click on New Group.
4. Notice that The new User that we previously created a chat with is not shown on Recent.
## Expected Result: 
Users we had chats with are shown in recent contact lists.
## Actual Result: 
Users we had chats with are not shown in recent contact lists.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/af581309-d483-47bd-a34c-d749656a9d4e

https://github.com/Expensify/App/assets/43996225/35d010be-2719-41c1-847a-73e61cc4c069

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692670914060579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by techievivek** [comment] 2023-08-22 08:39
This one looks tricky. But seems to be a result of some recent changes.

**Comment by s-alves10** [comment] 2023-08-22 08:51
This is a regression of [this PR](https://github.com/Expensify/App/pull/24355)
Reverting this works fine

We need to find another solution for the https://github.com/Expensify/App/issues/21706

**Comment by s-alves10** [comment] 2023-08-22 08:56
yes. that's because the account info from the server has not login info
If this issue is an expected behavior, we need to fix the solution. Simply removing optimistic data can't solve this issue

**Comment by s-alves10** [comment] 2023-08-22 08:58
@aimane-chnaif 

I think we need to set clear expectation about this issue.
If new user shouldn't be shown in contact list before he replies, this issue is wrong. But if should be shown, [this PR](https://github.com/Expensify/App/pull/24355) is wrong

cc @techievivek

**Comment by s-alves10** [comment] 2023-08-22 09:05
@aimane-chnaif 

Yes, optimistic data should be removed once correct data is returned from the server. But as you can see, login data wasn't returned from the server. Do you think that is a correct data?

I'm not judging. I am sharing my thought

**Comment by techievivek** [comment] 2023-08-22 09:22
@aimane-chnaif 

> There was recent discussion that unknown contacts should not be displayed in search list.

Could you please provide a link to the discussion? Also, what does "unknown contact" mean in this context? Should we consider a user as an "unknown contact" if they haven't replied to our message?

**Comment by techievivek** [comment] 2023-08-22 09:43
Okay, I agree that this is not a bug, but rather a feature. I will close this now. Thanks.

**Closed** 2023-08-22 09:43 UTC
Labels: Engineering, Hourly, Bug
