### ISSUE TITLE
[HOLD for payment 2024-10-08] Clean up Reanimated warnings

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#48361] opened 2024-08-30 18:54 UTC
### Problem

Somewhere between react-native-reanimated 3.8 and 3.13 a new dev warning was added to make worklet closures more strict and prevent common developer errors. These are just warnings and not errors for now, but there are many of them across the app.

This is distracting for developers and may be a sign that we are mis-using the library, which may in turn lead to other unintended consequences.

### Solution

For now, let's [suppress the warnings](https://github.com/Expensify/App/pull/48330), since we aren't aware of any real problems being caused by this. Then let's (with lower priority) go through and clean them up and eventually un-suppress the warning to make sure we're using Reanimated correctly.

cc @WoLewicki

**Comment by BartoszGrajdek** [comment] 2024-09-02 13:43
Hi! I’m Bartosz from SWM and I’m going to work on this issue 😄

**Comment by BartoszGrajdek** [comment] 2024-09-11 20:02
I made some progress on this issue last week, but was delayed due to a higher-priority issue and a brief sick leave. I'm back now and will be making this my primary focus 👀

**Comment by BartoszGrajdek** [comment] 2024-09-23 13:51
It got delayed longer than anticipated due to some other tasks at hand, but I believe there are no other warnings, than the ones I've noticed. I've tested it on all platforms and found 3 places where this warning was thrown:
1. Any screen using composer (Solved by https://github.com/Expensify/App/pull/48329)
2. Empty chat (Stopped happening on main, not sure which exact PR fixed this, but it doesn't happen anymore)
3. IOU Request Screen (PR with a fix is available [here](https://github.com/Expensify/App/pull/49587))

**Comment by stephanieelliott** [comment] 2024-10-03 22:58
Queuing this for payment after the regression period!

**Comment by stephanieelliott** [comment] 2024-10-08 23:59
Summarizing payment on this issue: 

 - Contributor: @BartoszGrajdek no payment due (external)
 - Contributor+: @hoangzinh $250 via Upwork -- offer extended, please accept: https://www.upwork.com/nx/wm/offer/104330959
 
 Upwork job is here: https://www.upwork.com/jobs/~021843802551890560225

**Comment by mallenexpensify** [comment] 2024-10-09 18:49
I paid @hoangzinh via Upwork because I needed to test the 'end contract' bug we're experiencing and grab a vid of it.  Will _let_ @stephanieelliott close this (I don't _think_ it needs a regression test but def not certain)

**Comment by stephanieelliott** [comment] 2024-10-11 04:12
Thanks @mallenexpensify! Yep this one is good to close.

**Closed by stephanieelliott** 2024-10-11 04:12 UTC
Labels: Reviewing, Engineering, Daily, Awaiting Payment, Bug
