### ISSUE TITLE
[HOLD for payment 2024-05-22]  Tax - Missing tax amount change in system message and incorrect new tax amount in the message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42045] opened 2024-05-13 11:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Workspace has enabled tax rate.
- Workspace currency default is tax exempt (0%).
- Foreign currency default have different tax rate (non-zero rate).

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense in local currency.
4. Go to transaction thread.
5. Click Amount and change it to a foreign currency.
6. Note that the system message does not include tax amount change system message.
7. Click Amount.
8. Change it back to local currency.
9. Note that the system message includes tax amount change system message.

## Expected Result:
In Step 6, when tax rate changes as a result of switching currency, the system message will include tax amount change, just like Step 9.
In Step 9. the system message will show the new tax amount.

## Actual Result:
In Step 6, when tax rate changes as a result of switching currency from local to foreign currency, the system message does not include tax amount change.
It only shows when changing currency from foreign to local currency (Step 9).
In Step 9, the system message shows the old tax amount.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/56531c25-652d-45a0-95fa-1d3e9fad9851

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by izarutskaya** [comment] 2024-05-13 11:07
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-13 11:07
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-05-13 11:07
Production


https://github.com/Expensify/App/assets/115492554/83b99fe8-38a5-4cd7-887d-1edbe429dbb8

**Comment by Julesssss** [comment] 2024-05-13 11:14
[This](https://github.com/Expensify/App/pull/40443) seems the most likely candidate IMO. If confirmed we'll seek a quick PR or revert to unblock the deploy. 

@madmax330 I haven't seen this new process where web and mobile deployers are assigned. I assume you'll remain assigned and won't remove the blocker label until it is confirmed to be front end?

**Comment by MonilBhavsar** [comment] 2024-05-13 11:33
Found the issue. Working on a fix.
We have previously discussed that we won't be displaying a system message for an indirect change.
In this case, taxAmount changes as expense amount is updated. We won't display a system message for tax amount update, and only display system message for amount/currency change.

I also confirmed this is optimistic by signing out and signing in and confirming the system message is no longer displayed.

**Comment by MonilBhavsar** [comment] 2024-05-13 12:34
PR is ready for review

**Comment by Julesssss** [comment] 2024-05-13 13:32
Merged, about to CP

**Comment by Julesssss** [comment] 2024-05-13 14:24
[Fix](https://github.com/Expensify/App/pull/42051) was just CP'd to staging. Checking it off the checklist.

**Comment by sakluger** [comment] 2024-05-16 18:56
@johncschuster could you please help with payment while I'm OOO?

@Julesssss does this issue require payment, and if so, how much? It looks like it may be a regression, and in that case I think no payment would be due.

**Comment by Julesssss** [comment] 2024-05-17 08:46
Monil submitted the PR so no payment is necessary for that. But @rushatgabhane was a C+ reviewer

**Comment by johncschuster** [comment] 2024-05-17 14:25
## Payment Summary:
Contributor+: @rushatgabhane - $250 via Manual Request

**Comment by rushatgabhane** [comment] 2024-05-20 16:43
1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by johncschuster** [comment] 2024-05-21 14:17
Thank you! 🎉 The payment summary is [above](https://github.com/Expensify/App/issues/42045#issuecomment-2117729923), and payment is due tomorrow. Please send your manual request 👍

**Closed by johncschuster** 2024-05-21 14:18 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-31 03:51
$250 approved for @rushatgabhane
