### ISSUE TITLE
Hybrid App - Duplicated Push Notifications on iOS

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46842] opened 2024-08-05 23:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-5
**Reproducible in staging?:** Y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dangrous 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722873417960569

## Action Performed:
1. Get a notification for something (chat, report approval, etc.)
## Expected Result:
Get a single notification for each action
## Actual Result:
Multiple notifications - all from hybrid app, it's not doubling between newDot and hybrid.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [X] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/46fd00ef-5276-4425-9329-b022672bc216" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/af08c263-0633-44a1-9124-66d3d343b119" width="40%" height="40%">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment] 2024-08-06 19:22
Dupe of https://github.com/Expensify/App/issues/46837

**Closed by AndrewGable** 2024-08-06 19:22 UTC
Labels: Daily, Bug
