### ISSUE TITLE
[$250] Chat - The number 1 in the name is lost and is not displayed in another user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11848] opened 2022-10-14 16:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Use123 numbers for your account Name under Settings
1. Open URL https://staging.new.expensify.com/
2. Login with any account which you sets up the account Name as 123
3.  Create a group and send message (you need to have access to it)
4. Login with any user and check Group message
5. Check the header with participants 

## Expected Result:
The name of the other user must be displayed in full

## Actual Result:
The number 1 in the name is lost and is not displayed in another user

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.15.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![image (8)](https://user-images.githubusercontent.com/93399543/195890460-a512d89b-fd41-4154-bc0c-024c4c75c17f.png)
![123 -1410](https://user-images.githubusercontent.com/93399543/195890464-d5d9cd4c-b57c-45ff-98fc-8b5cd8c99907.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2022-10-15 00:44
This happens in the function [ReportUtils::getDisplayNameForParticipant](https://github.com/Expensify/App/blob/069424538ad9ac0e03ec2af4f73c3b6c02e32e26/src/libs/ReportUtils.js#L472-L485) because it gets detected as phone number by `Str.isSMSLogin`.

The regex `E164_REGEX: /^\+?[1-9]\d{1,14}$/` accepts numbers with or without the `+` at the start.

The number `1` at the start gets interpreted as the US country code and then removed:

![image](https://user-images.githubusercontent.com/87341702/195961283-e328f6e3-e11f-40e7-abf3-a1dd641529ca.png)

**Comment by aldo-expensify** [comment] 2022-10-15 00:46
humm maybe I rushed into exporting as `External`... it is not 100% clear to me what is the solution we want here:

1. Don't consider as phone number if it didn't start with a `+`?
2. Why are we cutting the `+` and the `country code`? maybe we should leave everything there.
3. Maybe the logic is fine as it is, but don't apply the phone number cutting logic if the value is coming from the person name and not the email

**Comment by mananjadhav** [comment] 2022-10-16 09:42
@aldo-expensify I am not sure if what you mean in point three is same as what I am suggesting. But I guess we don't need to apply the check to `participate.displayName` and only apply it to `participate.login.`


```diff
     const loginWithoutSMSDomain = Str.removeSMSDomain(participant.login);
-   let longName = participant.displayName || loginWithoutSMSDomain;
-   if (Str.isSMSLogin(longName)) {
-        longName = LocalePhoneNumber.toLocalPhone(preferredLocale, longName);
-    }
      
+   let longName = participant.displayName || ( Str.isSMSLogin(participant.login) ?  LocalePhoneNumber.toLocalPhone(preferredLocale, participant.login) : participant.login );
    const shortName = participant.firstName || longName;
    return shouldUseShortForm ? shortName : longName;
}

```

**Comment by tienifr** [comment] 2022-10-16 11:06
@mananjadhav I see your suggestion is good. But are you missing `loginWithoutSMSDomain`? I think we should change the function `LocalePhoneNumber.toLocalPhone(preferredLocale, participant.login)` to `LocalePhoneNumber.toLocalPhone(preferredLocale, loginWithoutSMSDomain)`

**Comment by mananjadhav** [comment] 2022-10-16 11:18
Yes you're right @tienifr, I meant to write `loginWithoutSMSDomain`.

**Comment by aldo-expensify** [comment] 2022-10-17 18:16
Thanks @mananjadhav 

> @aldo-expensify I am not sure if what you mean in point three is same as what I am suggesting. But I guess we don't need to apply the check to participate.displayName and only apply it to participate.login.

yes, that would be point 3

> This can go wrong if displayName is set as login by default without processing the phone number logic during assignment,

yes, would be good to test if that is the case. If it is the case, maybe we would want to add do something like:

```js
let longName = participant.displayName;
if (!participant.displayName || participant.displayName === participant.login) {
    longName = Str.isSMSLogin(participant.login)
        ? LocalePhoneNumber.toLocalPhone(preferredLocale, participant.login)
        : participant.login;
}
```

**Comment by aldo-expensify** [comment] 2022-10-17 18:16
I'll ask in slack to confirm what is the path we want to take

**Comment by mananjadhav** [comment] 2022-10-18 18:58
> yes, would be good to test if that is the case. If it is the case, maybe we would want to add do something like:

Good idea @aldo-expensify

**Comment by aldo-expensify** [comment] 2022-10-22 00:18
Awaiting proposal . @mananjadhav are you going to do a formal proposal?

**Comment by aldo-expensify** [comment] 2022-10-24 18:31
No updates since comment above^

**Comment by ntrepanier** [comment] 2022-10-27 17:19
Waiting for proposal review @mananjadhav. Not overdue

**Comment by mananjadhav** [comment] 2022-10-27 18:19
Okay I did post one solution but didn't pursue it. I think @0xmiroslav's proposal is better.

🎀 👀 🎀 
C+ reviewed


@aldo-expensify What do you think?

**Comment by mananjadhav** [comment] 2022-10-31 07:37
Waiting on @aldo-expensify's review for the proposal.

**Comment by aldo-expensify** [comment] 2022-10-31 17:24
Yes, the proposal works for me. I tested and `participant.displayName` is the same as `loginWithoutSMSDomain` when the user has not specified a First and Last name, for phone number logins and emails.

**Comment by aldo-expensify** [comment] 2022-10-31 17:26
Assigned to @0xmiroslav

**Comment by mvtglobally** [comment] 2022-11-03 03:12
Issue not reproducible during KI retests. (First week)

**Comment by mananjadhav** [comment] 2022-11-05 18:56
@ntrepanier @aldo-expensify This was deployed to production but it's payment date wasn't updated

**Comment by mvtglobally** [comment] 2022-11-09 03:38
Issue not reproducible during KI retests. (Second week)

**Comment by aldo-expensify** [comment] 2022-11-10 19:37
@abekkala can you help me with this question: https://github.com/Expensify/App/issues/11848#issuecomment-1304611366 🙏

**Comment by abekkala** [comment] 2022-11-11 14:40
@aldo-expensify hmm - it looks like Nicole didn't create an Upwork job for this? Is that correct? I'm not seeing any Upwork links in here.
Before I can hire and then pay there should have been an Upwork job posting for this, no? 

Having just been thrown into this I want to make sure I understand where, in the process, this is right now. 

Do I have it correct that this was confirmed to be an `External` job > we accepted a proposal (but without an Upwork job posting)

**Comment by mananjadhav** [comment] 2022-11-11 15:10
@abekkala You're right. I guess the Upwork wasn't created. will you be able to create one and help here? The contributor was assigned the job [here](https://github.com/Expensify/App/issues/11848#issuecomment-1297425663), but we missed to take actions on Upwork.

**Comment by abekkala** [comment] 2022-11-11 16:54
ok, I'll create the Upwork job and then hire yourself and @0xmiroslav

**Comment by abekkala** [comment] 2022-11-11 17:00
https://www.upwork.com/ab/applicants/1591112720305827840/job-details
https://www.upwork.com/jobs/~0130f6fcd09160c648

Posted and hiring done

**Comment by abekkala** [comment] 2022-11-11 17:10
oh no - one should have been you and another for mananjadhav

**Comment by mananjadhav** [comment] 2022-11-11 17:12
@abekkala No worries, I've applied for the Upwork job.

**Comment by abekkala** [comment] 2022-11-11 17:12
Fixed! Sorry about that!

**Comment by mananjadhav** [comment] 2022-11-11 17:47
No worries. @abekkala, accepted the offer on Upwork.

**Comment by aldo-expensify** [comment] 2022-11-11 17:57
Thanks for sorting it out :)

**Comment by mananjadhav** [comment] 2022-11-14 03:55
@abekkala Quick bump on the payment for this one.

**Comment by abekkala** [comment] 2022-11-14 13:15
@aldo-expensify I feel that there is something missing here. 
Why did it GH auto-populate with the payment date for this one?

**Closed** 2022-11-14 15:15 UTC
Labels: External, Engineering, Daily, Bug

**Comment by aldo-expensify** [comment] 2022-11-14 18:00
> Why did it GH auto-populate with the payment date for this one?

I don't find any "payment date" in this GH issue, where should I look for it? I also don't know how this gets populated 🤷

**Comment by mananjadhav** [comment] 2022-11-14 18:37
@mountiny might have some idea on this?
