### ISSUE TITLE
Scan-Uploading specific pdf in workspace chat scan expense shows error

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49590] opened 2024-09-23 09:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Open workspace chat
3. Tap plus icon -- submit expense -- scan
4. Upload below given attachment
5. Tap submit expense
6. View the expense in report and details page
7. Tap on receipt and scroll the receipt

## Expected Result:
Uploading specific pdf in workspace chat scan expense must not show error.

## Actual Result:
Uploading specific pdf in workspace chat scan expense shows the error " The receipt didn't upload. Download the file or dismiss this error and lose it."

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/d8181f2d-75ba-432f-aa37-b6d0c53fd4e8

[Bug6610114_1726850778578!Biology_12th.pdf](https://github.com/user-attachments/files/17095572/Bug6610114_1726850778578.Biology_12th.pdf)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-23 09:56
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment] 2024-09-24 18:19
It looks like this is uploading a PDF through Android - I can't upload through Browserstack. Asking for a buddy to take this.

**Comment by mallenexpensify** [comment] 2024-09-28 00:13
d'oh, forgot I volunteered for this, will test week when in the office

**Comment by mallenexpensify** [comment] 2024-10-01 23:57
@Julesssss , why did you self-assign?  I was unable to reproduce, I got a different error ¯\_(ツ)_/¯

My error. 
![IMG_2284](https://github.com/user-attachments/assets/1eb1be3e-b77a-4543-b3ab-09dbcd222b8f)


Error from vid in OP
<img width="658" alt="image" src="https://github.com/user-attachments/assets/edebb703-e513-4d80-9aec-6a6485b567f8">

**Comment by Julesssss** [comment] 2024-10-02 13:22
Hey @mallenexpensify I assigned myself early as I was interested in this specific issue. 

I can also successfully scan the receipt now. I get the same error you see, which seems unrelated. Possible failure during parsing?

**Comment by mallenexpensify** [comment] 2024-10-03 22:24
uggggh, I hate when one bug becomes another :/ 
Should I just update the OP to change the actual behaviour to the "this receipt didn't upload" error? I looked in E/App and Slack and didn't see other bugs that containted "this receipt didn't upload".

**Comment by mallenexpensify** [comment] 2024-10-07 23:44
@Julesssss 👀 above when you have a min

**Comment by Julesssss** [comment] 2024-10-08 11:08
Lets close this in case other cases exist in the future and this can be used as a reference.

**Closed by Julesssss** 2024-10-08 11:08 UTC
Labels: Daily, Bug
