### ISSUE TITLE
[$500] IOS - Decimal and currency goes out of the screen when currency with 3 digits selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35212] opened 2024-01-25 23:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: Large text enabled on iPhone settings (Settings > Display & Brightness > Display Zoom > Large Text)
1. Open app
2. Tap on FAB
3. Tap on Request Money
4. Select UAH currency
5. Write 8 numbers and 2 decimals

## Expected Result:
Decimal and currency should be displayed properly

## Actual Result:
Decimal and currency goes out of the screen when currency with 3 digits selected and Large Text enabled on iPhone settings

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9057c5da-ee16-430b-9146-da66c26d2f22

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177fc294299afae8c</li>
        <li>Upwork Job ID: 1750656599886901248</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-01-26 01:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On IOS when having font zoom on, it overflows the amount field in the send money flow.

### What is the root cause of that problem?
We don't have allowFontScaling={false} on the AmountTextInput to prevent it from scaling with display zoom.
We use this pattern on some other inputs as well: https://github.com/Expensify/App/blob/071046f635e3ff46697d3bd7c10f68f5e57ffab0/src/components/Text.tsx#L47

### What changes do you think we should make in order to solve the problem?
pass allowFontScaling={false}  in the AmountTextInput to TextInput
https://github.com/Expensify/App/blob/071046f635e3ff46697d3bd7c10f68f5e57ffab0/src/components/AmountTextInput.tsx#L42


### What alternative solutions did you explore? (Optional)
Adding line-break css to wrap the number to a new line

**Comment by allroundexperts** [comment] 2024-01-29 20:30
Reviewing now!

**Comment by allroundexperts** [comment] 2024-01-29 20:41
Thanks for your proposal @jeremy-croff. I think your RCA is correct but I was not able to test your solution on a simulator. Can you post a screen recording of your solution in action on a real device? Thanks!

**Comment by allroundexperts** [comment] 2024-01-29 20:51
I could only reproduce this on a real device. If you can reproduce on a simulator, do let me know the steps and I can give it a shot.

**Comment by jeremy-croff** [comment] 2024-01-30 00:43
> I could only reproduce this on a real device. If you can reproduce on a simulator, do let me know the steps and I can give it a shot.

To reproduce this on the emulator,
You go into the developer settings, and set display Zoom to larger text. 
![Screenshot 2024-01-29 at 6 42 50 PM](https://github.com/Expensify/App/assets/157416545/b9bdc846-c79a-493d-b5e9-bbaf893f07e1)

My proposed solution does not fix this, as it actually is zoom related not font scaling.

**Comment by jeremy-croff** [comment] 2024-01-30 00:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When using a zoomed IOS experience, the amount text input overflows the screen as it scales beyond the screen size.

### What is the root cause of that problem?
We have not way in react-native to prevent display zoom from effecting font-size.
Only fontScaling is disable-able.

Android allows a way to not zoom https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#scalespagetofit 
But this is not supported for IOS.

### What changes do you think we should make in order to solve the problem?
We can introduce a new styling utility to remove zoom:
```
function getValueDisablingZoom(defaultValue: number): number {
    return defaultValue/PixelRatio.getFontScale();
}
```
We can use that to fix the font-size to 40 for this component:
https://github.com/Expensify/App/blob/480ae8d9615000c965ec7f7ec34adcb4c4a5551c/src/styles/variables.ts#L82

### What alternative solutions did you explore? (Optional)

**Comment by NicMendonca** [comment] 2024-01-31 19:42
Starting leave so re-assigning!

**Comment by trjExpensify** [comment] 2024-02-01 11:45
The chances of somebody requesting the equivalent of £1.8m for reimbursement are about the same as me winning the lottery! I'd love to be proved wrong though and see a customer report this bug. 

@allroundexperts, I'm inclined to close this.

**Comment by allroundexperts** [comment] 2024-02-02 20:57
> The chances of somebody requesting the equivalent of £1.8m for reimbursement are about the same as me winning the lottery! I'd love to be proved wrong though and see a customer report this bug.
> 
> @allroundexperts, I'm inclined to close this. What do you think?

Yep, I agree. The solution is sort of a work around as well. Not worth the time IMO.

**Comment by trjExpensify** [comment] 2024-02-05 12:16
Cool, thanks for the sense check. Closing!

**Closed by trjExpensify** 2024-02-05 12:16 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
