### ISSUE TITLE
[$500] Web - Emoji - cursor is lost in animals & nature section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10223] opened 2022-08-03 00:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/9954

## Action Performed:
1.  Go to staging.new.expensify.com
2. Navigate to any chat
3. Open an emoji picker
4. Press down arrow key 
5. Navigate with arrow key to Animals and Nature section
6.  Press up arrow key

## Expected Result:
When scroll up from the point the focus is not lost cursor

## Actual Result:
When scroll up from the point the focus is lost cursor

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.87.8

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/182496845-46e34690-e00a-4739-9942-271922dbf118.mp4

https://user-images.githubusercontent.com/93399543/182496846-9a9bcb5e-6cc8-4972-9459-5fad337066df.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment] 2022-08-09 20:27
Thanks @rushatgabhane. I've gone ahead and created an Upwork job to fix it. 

External upwork post: https://www.upwork.com/jobs/~01dfc05e7b0586aa7f
Internal upwork post: https://www.upwork.com/ab/applicants/1557101140060336128/job-details

**Comment by puneetlath** [comment] 2022-08-17 19:07
Doubled to $500.

**Comment by mdneyazahmad** [comment] 2022-08-22 08:13
Looks like a duplicate of https://github.com/Expensify/App/issues/8459

**Comment by puneetlath** [comment] 2022-08-22 17:08
Ah, looks like you're right! Thanks @mdneyazahmad.

**Closed by puneetlath** 2022-08-22 17:08 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
