### ISSUE TITLE
QBO – Unable to change preferred exporter in QBO connection

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#49797] opened 2024-09-26 15:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.40-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5006859 
**Email or phone of affected tester (no customers):**  applausetester+shsb22145@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause Internal Team 

**Slack conversation:**

## Action Performed:
Prerequisite
Workspace is connected to QBO
Another Admin is added to the workspace

1. Navigate to Accounting
2. Click on Export
3. Click Preferred Exporter
4. Select the unchecked workspace admin
5. Wait for the connection to sync and check the preferred exporter

## Expected Result:
The newly selected exporter is displayed with a checkmark

## Actual Result:
The selected exporter does not stay selected and the exporter is reverted back to the previous one

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [X] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/911fb40a-2e72-4343-8ba7-626426b95336

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by mvtglobally** [comment] 2024-09-26 15:43
We think this is related to #wave-collect - Release 2

**Comment by mananjadhav** [comment] 2024-09-26 16:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Unable to update the QBO Preferred exporter

### What is the root cause of that problem?

- In `QuickbooksPreferredExporterConfigurationPage` we are using `qboConfig?.export.exporter` as the fallback value for optimistic update. But  `qboConfig.export` can be undefined when we first sync.

### What changes do you think we should make in order to solve the problem?

- In `QuickbooksPreferredExporterConfigurationPage` update code to `qboConfig?.export?.exporter`.


### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment] 2024-09-26 16:31
Proposal updated.

**Comment by Beamanator** [comment] 2024-09-26 19:40
Oh dang, thanks for the proposals so far! Anyone know which PR the bug may have come from??

**Comment by mananjadhav** [comment] 2024-09-26 19:44
@Beamanator Likely https://github.com/Expensify/App/pull/48080/files#diff-afb3647e9a1c6b4d00a7047f997bffa23c873bbd6807e726807f48ebef608bcaR57

**Comment by Beamanator** [comment] 2024-09-26 20:06
Yaaa i was kinda thinking that too ^

**Comment by Beamanator** [comment] 2024-09-26 20:06
@shubham1206agra  @dangrous  @rushatgabhane @aldo-expensify can y'all look at this?

**Comment by aldo-expensify** [comment] 2024-09-26 20:48
Investigating...

**Comment by dangrous** [comment] 2024-09-26 20:49
I think this is probably due to https://github.com/Expensify/Expensify/issues/431392#issuecomment-2377490529 which I just noticed today - basically I think we're ending up trying to update the export object to `{exporter: {exporter: [actual value]}}` but not 100% sure

**Comment by aldo-expensify** [comment] 2024-09-26 20:58
The exporter is getting encoded and nested in a weird way:

<img width="579" alt="image" src="https://github.com/user-attachments/assets/499c9882-e725-4a82-b647-e6b2f24f098f">

This is a duplicate of https://github.com/Expensify/Expensify/issues/431392#issuecomment-2377490529.

**Comment by aldo-expensify** [comment] 2024-09-26 21:02
This seems to fix it: https://github.com/Expensify/App/pull/49818

cc @dangrous

**Comment by mananjadhav** [comment] 2024-09-26 21:06
@aldo-expensify This might fix the API call but when I did a fresh connection, I could see the JS error for `qboConfig?.export.exporter` as `qboConfig.export` was undefined. May be we'll need to fix both?

**Comment by aldo-expensify** [comment] 2024-09-26 21:09
> @aldo-expensify This might fix the API call but when I did a fresh connection, I could see the JS error for `qboConfig?.export.exporter` as `qboConfig.export` was undefined. May be we'll need to fix both?

That sounds unrelated. Can you reproduce it in production?

**Comment by aldo-expensify** [comment] 2024-09-26 21:14
About that second bug, I'm not sure what is proposed here is the "right" way to fix it: https://github.com/Expensify/App/issues/49797#issuecomment-2377460969

If the request to update the exporter fails, the "current value" we revert to could be wrong. The real value may have just been delayed.

**Comment by mananjadhav** [comment] 2024-09-26 21:16
Here's a recording, and it looks like reproducible on Prod too.

https://github.com/user-attachments/assets/354d87a6-32eb-4c77-8e90-eea6aa133a57

**Comment by aldo-expensify** [comment] 2024-09-26 21:17
> Here's a recording, and it looks like reproducible on Prod too.

nice, I think we should work on the right solution with more time, so I would avoid putting it together with the deploy blocker

**Comment by mananjadhav** [comment] 2024-09-26 21:19
Is the API being called in your solution? If you see the recording the API wasn't called at all. Adding optional chaining works as mentioned in my [proposal](https://github.com/Expensify/App/issues/49797#issuecomment-2377428671).

https://github.com/user-attachments/assets/87b7d7b1-87a0-4711-9ee7-526d778d61cd

On a side note, I can help you review the DeployBlocker PR.

**Comment by aldo-expensify** [comment] 2024-09-26 22:02
> Adding optional chaining works as mentioned in my https://github.com/Expensify/App/issues/49797#issuecomment-2377428671.

I want to avoid adding optional chaining just to go around an issue that may require a better solution

**Comment by aldo-expensify** [comment] 2024-09-26 22:04
> Is the API being called in your solution?

yes, you can see it in the video I attached to the PR

<img width="780" alt="image" src="https://github.com/user-attachments/assets/5e3b0d47-4366-4871-87ae-b1c135900c18">

**Comment by mananjadhav** [comment] 2024-09-26 22:32
Yeah I can see that. Thanks for clarifying.

**Comment by Beamanator** [comment] 2024-09-27 15:04
Thanks so much for taking care of this since i had to peace out early yesterday @aldo-expensify 🙏

**Comment by johncschuster** [comment] 2024-10-07 21:39
How's this one going, @aldo-expensify?

**Comment by mananjadhav** [comment] 2024-10-08 16:47
@johncschuster I believe the PR was deployed to fix the Deploy blocker. I had helped with the PR review, and there would be a payout for me. Can you please update the payment summary for this one?

Also @aldo-expensify do you think it's worth solving the FE [error](https://github.com/Expensify/App/issues/49797#issuecomment-2377958255) in this issue?

**Comment by aldo-expensify** [comment] 2024-10-09 06:10
> How's this one going, @aldo-expensify?

The deploy blocker (this issue) was solved by this PR: https://github.com/Expensify/App/pull/49818

@mananjadhav reviewed so we should pay

While we worked on that, another bug was found: https://github.com/Expensify/App/issues/49797#issuecomment-2377938528, but I would recommend creating a new clean issue for that with reproduction steps.

> Also @aldo-expensify do you think it's worth solving the FE https://github.com/Expensify/App/issues/49797#issuecomment-2377958255 in this issue?

Yes, but I think we should open a new issue to avoid confusions. I'm not really sure about what kind of solution are we looking for... it sounds like we should maybe lock the inputs until we have received the data or something like that.

**Comment by mananjadhav** [comment] 2024-10-09 17:29
Could be related. I can check that one if you'd like.

**Comment by aldo-expensify** [comment] 2024-10-11 20:15
@johncschuster [the PR](https://github.com/Expensify/App/pull/49818#issuecomment-2379775132) was deployed 2 weeks ago, we need to process @mananjadhav 's C+ payment.

**Comment by johncschuster** [comment] 2024-10-14 15:04
Sorry folks! I action all my payment issues every day by filtering my assignments by `HOLD for payment` in the title and I missed this. Thank you for the pings!

**Comment by mananjadhav** [comment] 2024-10-14 15:06
Thanks @johncschuster for the help here.

**Comment by garrettmknight** [comment] 2024-10-15 01:14
$250 approved for @mananjadhav

**Comment by johncschuster** [comment] 2024-10-16 22:08
@aldo-expensify / @mananjadhav can you provide a regression test step list if we need one?

**Comment by aldo-expensify** [comment] 2024-10-21 20:18
> @aldo-expensify / @mananjadhav can you provide a regression test step list if we need one?

I don't think we need a new one. This bug was caught while running the existing test: https://expensify.testrail.io/index.php?/tests/view/5006859

**Closed by aldo-expensify** 2024-10-21 20:18 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
