### ISSUE TITLE
[Waiting on BugZero Checklist] [$1000]  Inconsistency bug: 'Go back to home screen' link is not present on 'Hmm its not here' page of archived workspace settings

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24391] opened 2023-08-10 20:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces
4. Create new workspace or open existing workspace
5. Click on settings and copy link, send to any report
6. Click on bank account and copy link, send to any report
7. Delete the workspace used in step 5 and 6
8. Open link copied in step 6 and observe that it has 'Go back to home screen' link
9. Open link copied in step 5 and observe that it does nor have 'Go back to home screen' link

## Expected Result:
 App should display 'Go back to home screen' link in 'Hmm its not here' page for all workspace pages after being archived

## Actual Result:
App does not display 'Go back to home screen' link  in 'Hmm its not here' page for settings page of workspace after being archived

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.52.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a4577eb8-4a16-4abc-a94d-ad171e8c2b8e

https://github.com/Expensify/App/assets/43996225/5b6142f7-f30b-4331-8d75-62b9943f5fa9

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691054147355909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d12ba5fc6e912485</li>
        <li>Upwork Job ID: 1690985977143230464</li>
        <li>Last Price Increase: 2023-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>GItGudRatio | Contributor | 26164949</li>
<li>Dhanashree-Sawant | Reporter | 26164953</li>
</ul></li>
    </ul>
</details>

**Comment by DanutGavrus** [comment] 2023-08-10 20:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency bug: 'Go back to home screen' link is not present on 'Hmm its not here' page of archived workspace settings

### What is the root cause of that problem?
For the Workspace Setting Page, we do not pass the prop `shouldShowLink`, so we don't see the button.

### What changes do you think we should make in order to solve the problem?
1. If we want to show the link in the Settings Page, then, the `WorkspaceSettingPage` returns the `WorkspacePageWithSections` which is wrapped in the `FullPageNotFoundView` component. We should pass the **shouldShowLink** prop here.
2. If we want to remove the link from the bank account page, then we should remove the **shouldShowLink** prop from the `ReimbursementAccountPage` component.

**Comment by kadiealexander** [comment] 2023-08-14 07:17
Not overdue.

**Comment by narefyev91** [comment] 2023-08-14 07:40
@kadiealexander current issue is a duplication of https://github.com/Expensify/App/issues/24368 - both issues should be fixed at once

**Comment by DanutGavrus** [comment] 2023-08-14 07:44
This one was reported on Slack on *Aug 03*, and https://github.com/Expensify/App/issues/24368 was created on *Aug 10* and has no Slack link. Should we close that and keep this then?

**Comment by narefyev91** [comment] 2023-08-16 06:44
Well in issue https://github.com/Expensify/App/issues/24368 - they are changing the wrapper from BlockingView to FullPageNotFoundView  - which is not really the same as we have in our bug
Not see any issue to not fix this one - in any case - @GItGudRatio was the first one with correct root case and steps to solve https://github.com/Expensify/App/issues/24391#issuecomment-1673903904 - I will also suggest to reach consistency between all pages adding Go back to home screen
🎀 👀 🎀 C+ reviewed

**Comment by DanutGavrus** [comment] 2023-08-16 07:01
Hi, @narefyev91!
> I will also suggest to reach consistency between all pages adding Go back to home screen 

That wouldn't be my [alternate Proposal](https://github.com/Expensify/App/issues/24391#issuecomment-1673903943) then? Thanks!

**Comment by DanutGavrus** [comment] 2023-08-17 10:14
@narefyev91 has said that `I will also suggest to reach consistency between all pages adding Go back to home screen`.
@marcaaron Could you please confirm that it's not my [alternative Proposal](https://github.com/Expensify/App/issues/24391#issuecomment-1673903943) which is going to be implemented? Maybe it was missed during the review as it was the alternative, not the main one. Thank you!

**Comment by DanutGavrus** [comment] 2023-08-17 11:03
@narefyev91 @marcaaron Looking into the [PR changes](https://github.com/Expensify/App/pull/25164/files) & [my alternative proposal](https://github.com/Expensify/App/issues/24391#issuecomment-1673903943):
> I would say, instead of fixing only 1, or some of them in this issue, to default shouldShowLink prop to true in order to prevent future bugs like this one  

they are the same thing, while @GItGudRatio's [Proposal](https://github.com/Expensify/App/issues/24391#issuecomment-1673903904) states to just add **shouldShowLink** prop into `WorkspacePageWithSections` component.

**Comment by narefyev91** [comment] 2023-08-17 13:34
> @narefyev91 @marcaaron Looking into the [PR changes](https://github.com/Expensify/App/pull/25164/files) & [my alternative proposal](https://github.com/Expensify/App/issues/24391#issuecomment-1673903943):
> 
> > I would say, instead of fixing only 1, or some of them in this issue, to default shouldShowLink prop to true in order to prevent future bugs like this one
> 
> they are the same thing, while @GItGudRatio's [Proposal](https://github.com/Expensify/App/issues/24391#issuecomment-1673903904) states to just add **shouldShowLink** prop into `WorkspacePageWithSections` component.

@DanutGavrus Hey! Thanks for flagging - btw - the root case of the issue was identified by @GItGudRatio firstly - and changes which potentially fix the issue were correct - any other additional logic which should be implemented is discussed during PR review

**Comment by DanutGavrus** [comment] 2023-08-17 20:02
Hey, @narefyev91!
> the root case of the issue was identified by @GItGudRatio firstly  

As per *my understanding of the guideline*, in the reviewing process, the Proposal which has ***both** the correct root cause + solution* should be chosen. For example, in [this issue](https://github.com/Expensify/App/issues/22658), we went with my *alternative* Proposal after **clarifications**, even if I didn't have the **first** correct root cause. There, while the previous Proposals were *similar*, those were *not targeting the specific required components by the issue*, a situation pretty similar with this one. Different resolutions seem to create inconsistency in the reviewing process, at least for me.

> any other additional logic which should be implemented is discussed during PR review  

In my opinion, *only adding **1** prop to component A* seems different enough from *changing the default behavior of component B that is used in the whole application* as to be considered **different** solutions, and not just *some additional implementation logic*.

Any second opinion would help me very much in better understanding the situation. @marcaaron Could you please consider sharing your thoughts here? cc: @Gonals You've recently helped in a similar situation(in the Issue I've previously mentioned), could you please eventually help with this one too? Thank you!

**Comment by marcaaron** [comment] 2023-08-17 22:14
Apologies, I can't prioritize settling this dispute with urgency. Would you kindly raise it in Slack or via email and someone will look into it for you as soon as possible?

**Comment by narefyev91** [comment] 2023-08-18 07:02
@DanutGavrus you are right that we should choose correct proposal with both root case and fix - for the current issue correct proposal was done from @GItGudRatio. It was not 100% decision to move with changing a prop globally, and such cases should be discussed in PR - with internal dev. I only posted my comment for person who makes final decision to agree or disagree with this.
Based on your linked issue - it's really different from current one - and here your alternative solution will be based on main solution.
Finally if for some reason here should be changed a picked person - based on alternative solutions - it should be @namhihi237 - because we proposed those global changes.
I'm personally open for any change/not change here @marcaaron

**Comment by DanutGavrus** [comment] 2023-08-18 07:10
@narefyev91 
> it should be @namhihi237 - because we proposed those global changes.

I agree that he proposed those global changes, but I still consider that:
> We should look for places where FullPageNotFoundView is used in the workspace and add the shouldShowLink prop.  

> default shouldShowLink prop to true in order to prevent future bugs like this one, and pass it as false only where we really don't want to show it(if any)

Are different solutions/Proposals. They provide very different approaches, and work on different components. In my opinion, if we decide to go with him, in the PR, we should add the **shouldShowLink** prop to the missing **FullPageNotFoundView** components as he stated.

**Comment by narefyev91** [comment] 2023-08-18 07:59
I asked some clarification in slack - and will come back shortly

**Comment by narefyev91** [comment] 2023-08-18 08:56
@marcaaron get agreement with @Gonals to continue with @GItGudRatio proposal and continue in the same direction https://expensify.slack.com/archives/C02NK2DQWUX/p1692346863575419 for reference
@DanutGavrus @namhihi237 thanks for your contribution - hope we will see your proposal on next issues

**Comment by mountiny** [comment] 2023-08-18 10:31
@GItGudRatio whats you slack handle?

**Comment by mountiny** [comment] 2023-08-18 10:55
From the Slack thread, lets do fixed $250 to @DanutGavrus for contribution here and @GItGudRatio should be getting urgency bonus as PR is ready to be merged under 3 days. that will be $1250 to @GItGudRatio Thanks

**Comment by DanutGavrus** [comment] 2023-08-24 09:29
@mountiny 
> From the Slack thread, lets do fixed $250 to @DanutGavrus for contribution here and @GItGudRatio should be getting urgency bonus as PR is ready to be merged under 3 days. that will be $1250 to @GItGudRatio Thanks

Unfortunately, the PR did not get merged under 3 days. I'd suggest to give the whole $1000 to @GItGudRatio and $0 to me. To be honest, I cared more about the fairness of the situation than the financial one. I may have also added some delay for @GItGudRatio which took the bonus out from him, so I feel it's fair that I don't take 25% from him now. Thank you very much again!

**Comment by kadiealexander** [comment] 2023-09-05 03:00
Payouts due:

Issue Reporter: $250 @dhanashree-sawant 
Contributor: $1000 @GItGudRatio
Contributor+: $0 @narefyev91 (contractor)

Eligible for 50% #urgency bonus? [No](https://github.com/Expensify/App/issues/24391#issuecomment-1687380908)

Upwork job is [here](https://www.upwork.com/jobs/~01d12ba5fc6e912485).

**Comment by kadiealexander** [comment] 2023-09-05 03:01
Just waiting on the BugZero checklist! Gentle reminder @narefyev91  :)

**Comment by narefyev91** [comment] 2023-09-05 06:00
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/25516
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - https://github.com/Expensify/App/pull/25164#issuecomment-1684442556
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - discussion was raised during regression inside github.
- Determine if we should create a regression test for this bug - yes we should
- if we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again:

**Regression Test**
1. Login to ND.
2. Go to settings > Workspaces > choose any workspace > settings.
3. Copy the URL.
4. Go back and delete the workspace.
5. Go the URL you copied in step 3.
6. Ensure that you see the "go back to home screen" lin

**Comment by ayazhussain79** [comment] 2023-09-06 20:36
@kadiealexander @narefyev91 I've reported a regression bug in this [PR](https://github.com/Expensify/App/pull/25164) and this [PR](https://github.com/Expensify/App/pull/23060) created to fix it . You can review the details on the following link: https://github.com/Expensify/App/pull/25164

**Comment by marcaaron** [comment] 2023-09-12 02:43
I think we are good to close this one now. Feel free to reopen if I missed something.

**Closed by marcaaron** 2023-09-12 02:43 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by ayazhussain79** [comment] 2023-09-17 19:21
@marcaaron can you please check this one https://github.com/Expensify/App/issues/24391#issuecomment-1709071988 I reported regression

**Comment by marcaaron** [comment] 2023-09-18 04:35
@ayazhussain79 please advise whether you are suggesting there is some further action to take. It's not clear from your comment. Thanks.

**Comment by ayazhussain79** [comment] 2023-09-18 04:58
@marcaaron I have reported a regression [bug](https://github.com/Expensify/App/pull/25164#issuecomment-1684442556) When PR merged, am i eligible for reporting bonus?
