### ISSUE TITLE
[HOLD for payment 2024-04-15] [Violations][$500] Scan - Category row shows violation briefly after the scan request is created

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38131] opened 2024-03-12 12:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** applause internal team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has toggled on "People must categorize expenses" for Categories on Old Dot.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a scan request without category.
4. Go to request details page right after it is created.

## Expected Result:
Category row will not show violation until after smartscanning is complete.

## Actual Result:
Category row shows "missing category" violation briefly after the scan request is created.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/0e631a0e-f9f7-41bd-bfcd-33ec07452ca6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e13a4e6b1d86de89</li>
        <li>Upwork Job ID: 1770584960942833664</li>
        <li>Last Price Increase: 2024-03-20</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2024-03-12 12:08
We think this bug might be related to #wave-collect - RELEASE 1

cc @trjExpensify

**Comment by trjExpensify** [comment] 2024-03-12 14:11
Hm, why wouldn't we show the category violation right away if categories are required on the workspace? 🤔 CC: @JmillsExpensify @cead22

**Comment by bfitzexpensify** [comment] 2024-03-15 10:54
Yes, I think the bug here is that the violation disappears, not that it appears in the first place.

**Comment by bfitzexpensify** [comment] 2024-03-18 17:18
@trjExpensify do you agree with [this comment](https://github.com/Expensify/App/issues/38131#issuecomment-1999407240)?

If so, I'll update the OP and send external

**Comment by trjExpensify** [comment] 2024-03-19 14:44
Yeah, I agree with it insofar as I don't know why it's disappearing. This is violations related though, so one for #wave-control.  :)

**Comment by cead22** [comment] 2024-03-20 22:54
It looks like this is happening because we compute missingTag/missingCategory/tagOutOfPolicy/categoryOutOfPolicy/someTagLevelsRequired violations on the client, and when the request to OpenReport comes back, it clears the violations in Onyx which makes them disappear.

The reason violations are cleared is because we don't compute those violations when a transaction is a "partial transaction", meaning it's merchant is set to `(none)` and its amount is 0.

Let's make this issue external, have the contributors confirm that ^ is the root cause in their proposal, and see if adding a check for partial transactions in `getViolationsOnyxData`, or something along those lines fixes the issue

**Comment by bernhardoj** [comment] 2024-03-21 03:32
_I don't see the violation disappears anymore, but here is the proposal to not add the violation optimistically when it's a partial transaction_

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The violation data is added optimistically when it's a partial transaction.

### What is the root cause of that problem?
When we create a new money request, we just push the violation data that we found on the request,
https://github.com/Expensify/App/blob/47bba81007ae9a4a5dfd6008c626efecb895153d/src/libs/actions/IOU.ts#L797-L806

in this case, the category is missing. We never check whether the transaction is a partial transaction or not.

### What changes do you think we should make in order to solve the problem?

As pointed out by @cead22, we don't want to add it optimistically when it's a partial transaction, so we can add a new check and only add it when it's not a partial transaction.
```
const isPartialTransaction = TransactionUtils.isPartialMerchant(transaction.merchant) && transaction.amount === 0;
if (violationsOnyxData && !isPartialTransaction) {
    optimisticData.push(violationsOnyxData);
    failureData.push({
        onyxMethod: Onyx.METHOD.SET,
        key: `${ONYXKEYS.COLLECTION.TRANSACTION_VIOLATIONS}${transaction.transactionID}`,
        value: [],
    });
}
```

### What alternative solutions did you explore? (Optional)
Or we can check whether we are creating a scan request or not by checking the `receipt.state` value is SCANREADY or any other way if available.

**Comment by eh2077** [comment] 2024-03-21 06:42
Reviewing proposals.

**Comment by eh2077** [comment] 2024-03-21 15:16
The category violation is no longer being shown. Tested in dev and staging.

I think I also agree with @trjExpensify that the violation should be shown as long as it's required by the workspace, regardless of whether it's scanning or not. @cead22 Do you agree with this?

I think @abzokhattab 's proposal makes sense to me.

**Comment by trjExpensify** [comment] 2024-03-21 18:21
>I think I also agree with @trjExpensify that the violation should be shown as long as it's required by the workspace, regardless of whether it's scanning or not. @cead22 Do you agree with this?

I caught up with Carlos, and you can ignore me =D. We don't show the violation(s) while the transaction is partial because we don't have all the info yet. So it's right to proceed with a solution that doesn't show them in that state.

**Comment by eh2077** [comment] 2024-03-25 02:42
@trjExpensify Thanks for the update! Reviewing proposals.

**Comment by eh2077** [comment] 2024-03-25 15:11
@trjExpensify I want to confirm I understand the expected flow. Let's say we have following preconditions as described in this issue

- User is an employee of Collect workspace.
- The Collect workspace has toggled on "People must categorize expenses" for Categories on Old Dot.

For a scan request without category
1. Should we display the red dot when the receipt is scanning?
    Currently, there's a red dot shown
    <img width="456" alt="Screenshot 2024-03-25 at 10 26 10 PM" src="https://github.com/Expensify/App/assets/117511920/5b575eeb-86d8-4e12-9b11-11fbb959309d">

    
2. Should we show category violation when scanning is completed? 
    Currently, the category violation is not shown when scanning is failed.
    
    <img width="1060" alt="Screenshot 2024-03-25 at 10 30 20 PM" src="https://github.com/Expensify/App/assets/117511920/4af4b0ac-43ac-4e11-b01c-8f67e11a53db">

3. What's the expected result after manual editing the failed request?
    Currently, the category violation is not shown after editing the amount or both amount and merchant
    
    <img width="1058" alt="image" src="https://github.com/Expensify/App/assets/117511920/60165d66-d81e-4c42-8893-57b783ee66cd">
    <img width="1096" alt="image" src="https://github.com/Expensify/App/assets/117511920/844bda2b-65d3-446f-8aae-039b6ecb94d8">

**Comment by cead22** [comment] 2024-03-26 03:12
> 2\. Currently, the category violation is not shown when scanning is failed.

I think this makes sense since in this case the transaction is still partial because we don't have all merchant and amount for it

> 3\. What's the expected result after manual editing the failed request?
>     Currently, the category violation is not shown after editing the amount or both amount and merchant

If/when the transaction isn't partial, we should show the category violation, probably by triggering a call to `getViolationsOnyxData`

**Comment by JmillsExpensify** [comment] 2024-03-26 03:27
Building on that last point from Carlos

> Should we display the red dot when the receipt is scanning?

We shouldn't show the red dot on a scanning receipt, as that's a partial transaction.

**Comment by bernhardoj** [comment] 2024-03-26 03:51
> What's the expected result after manual editing the failed request?
> Currently, the category violation is not shown after editing the amount or both amount and merchant

I tested this and the violation shows as we already added the violation when editing the transaction.
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/IOU.ts#L1701-L1718

I have updated my proposal to make sure the violation is added when editing only when it's not a partial transaction.

**Comment by eh2077** [comment] 2024-03-26 04:32
> > What's the expected result after manual editing the failed request?
> > Currently, the category violation is not shown after editing the amount or both amount and merchant
> 
> I tested this and the violation shows as we already added the violation when editing the transaction.
> 

@bernhardoj Thanks for your comment. I'm not following you about this. I just tested it in staging and didn't see category violation after updating amount and merchant.
<img width="400" alt="image" src="https://github.com/Expensify/App/assets/117511920/9147267b-4cc0-48ae-8571-ded61de90c83"><img width="400" alt="image" src="https://github.com/Expensify/App/assets/117511920/bd760270-0597-4591-9b98-adda70f70e21">

**Comment by bernhardoj** [comment] 2024-03-26 05:59
That's weird. Is the account has access to the beta and is it a collect policy?

Actually, if both is satisfied, won't you get the violation right away after creating the request? From my testing:
1. Create a new scan request. Violation shows
2. Scan failed. Violation still shows
<img width="781" alt="image" src="https://github.com/Expensify/App/assets/50919443/8ecc7f83-c263-48ae-ac25-c57bc22d4df1">

If I fixed the optimistic violation:
1. Create a new scan request. No violation
2. Scan failed. No violation
3. Edit the amount. Violation shows.

https://github.com/Expensify/App/assets/50919443/5adf8aee-72c2-4ad0-8de3-0b3c058a0817

**Comment by eh2077** [comment] 2024-03-26 09:27
@bernhardoj It's a collective policy but my account hasn't been added to the `violations` beta. I can reproduce what you shared if I overwrite `Permissions.canUseAllBetas` locally to return true.

**Comment by eh2077** [comment] 2024-03-26 09:58
Thank you all for your proposals. 

@GandalfGwaihir Your idea to display violation according to `isScanning` has limitation when receipt scanning is failed, see https://github.com/Expensify/App/issues/38131#issuecomment-2019305656

@abzokhattab I believe you would be able to provide a better proposal if you know that there's a `violations` beta to access the feature. I also overlooked this before @bernhardoj 's clarification. You can apply it like [link](https://expensify.slack.com/archives/C01GTK53T8Q/p1708715225455659) or just overwrite it locally.

I think we can go with @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/38131#issuecomment-2011156976) as their solution follows the expected flow as discussed https://github.com/Expensify/App/issues/38131#issuecomment-2010830030 and https://github.com/Expensify/App/issues/38131#issuecomment-2018233259.

@cead22 All yours.

🎀👀🎀 C+ reviewed

**Comment by eh2077** [comment] 2024-03-26 10:07
> > Currently, the category violation is not shown when scanning is failed.
> 
> A little clarification please, this was not showing on your side because beta was not enabled for your account right 🤔

Yes.

**Comment by bernhardoj** [comment] 2024-03-27 06:23
PR is ready

cc: @eh2077

**Comment by mvtglobally** [comment] 2024-03-28 04:27
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2024-03-29 14:19
Looks like we're close on the PR.

**Comment by eh2077** [comment] 2024-04-02 13:49
The PR just hit staging.

**Comment by cead22** [comment] 2024-04-12 21:13
> * The offending PR has been commented on, pointing out the bug it caused and why,

@eh2077 can you explain why that PR caused this regression?

**Comment by eh2077** [comment] 2024-04-12 23:18
> > * The offending PR has been commented on, pointing out the bug it caused and why,
> 
> @eh2077 can you explain why that PR caused this regression?

Oh, my bad. Updated [comment](https://github.com/Expensify/App/pull/32528/files#r1556996670).

**Comment by cead22** [comment] 2024-04-12 23:29
Thanks. I think that change actually happened before we were showing RBRs on partial transactions (I haven't confirmed). The linked PR was merged in early Jan

**Comment by bfitzexpensify** [comment] 2024-04-16 13:48
Payments complete - regression steps proposed in https://github.com/Expensify/Expensify/issues/388131. We're all done here, thanks everyone!

**Closed by bfitzexpensify** 2024-04-16 13:48 UTC
Labels: External, Daily, Awaiting Payment, Bug
