### ISSUE TITLE
[HOLD for payment 2023-01-30] [$1000] Loader is not center aligned on transactions detail page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14321] opened 2023-01-16 16:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Action Performed:

1. Open any chat room.
2. Send/Request money if not have any IOU-Preview.
3. Press on IOU-Preview.
4. Observer detail page loading (showing on top instead of center).

## Expected Result:
Transactions detail loader should be center aligned.

## Actual Result:
Transactions detail loader display at top.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.54-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212723057-ed7f9e53-c676-4cf3-9a70-72d6c0fd8169.mov

https://user-images.githubusercontent.com/43996225/212723079-94a25753-354e-416f-8082-cfa8092f0134.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jatinsonijs 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673695348615179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016967a20343f40aef</li>
        <li>Upwork Job ID: 1615021086958297088</li>
        <li>Last Price Increase: 2023-01-16</li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment] 2023-01-16 16:21
### Proposal

We should wrap the ActivityIndicator in parent View with flex 1, alignItemsCenter, and justifyContentCenter

https://github.com/Expensify/App/blob/7ca2979f550c812171017e7b20b4ba659be17800/src/pages/iou/IOUDetailsModal.js#L168

```diff
-                    {this.props.iou.loading ? <ActivityIndicator color={themeColors.text} />
+                    {this.props.iou.loading ? (
+                        <View style={[styles.flex1, styles.alignItemsCenter, styles.justifyContentCenter]}>
+                            <ActivityIndicator color={themeColors.text} />
+                        </View>
+                    ): (

**Comment by jatinsonijs** [comment] 2023-01-16 16:22
Root case
We are not using centre align on loader

Proposal
We can use 
 {this.props.iou.loading ? <FullScreenLoadingIndicator /> : (
 
 Or 
 <View style={[styles.flex1, styles.alignItemsCenter, styles.justifyContentCenter]}>
                            <ActivityIndicator color={themeColors.spinner} size="large" />
                        </View>

**Comment by hungvu193** [comment] 2023-01-16 16:26
<b>Proposal</b>
For now the loading indicator didn't have the style for AcitivtyIndicator inside IOUDetailsModal.
To make it center we should add the styles into it.
```diff
+          {this.props.iou.loading ? <ActivityIndicator style={[styles.flex1, styles.justifyContentCenter]} color={themeColors.text} /> : (
```

Result:

https://user-images.githubusercontent.com/16502320/212725516-3455da5a-e33c-49c6-a06e-a1ed565fb8e2.mov

**Comment by Pujan92** [comment] 2023-01-16 16:34
**Proposal**

We require only `flex: 1` to take available height which we can add with `styles.flex1` class.

```diff
diff --git a/src/pages/iou/IOUDetailsModal.js b/src/pages/iou/IOUDetailsModal.js
index ab600cfb5..4405f78ca 100644
--- a/src/pages/iou/IOUDetailsModal.js
+++ b/src/pages/iou/IOUDetailsModal.js
@@ -165,7 +165,7 @@ class IOUDetailsModal extends Component {
                         title={this.props.translate('common.details')}
                         onCloseButtonPress={Navigation.dismissModal}
                     />
-                    {this.props.iou.loading ? <ActivityIndicator color={themeColors.text} /> : (
+                    {!this.props.iou.loading ? <ActivityIndicator color={themeColors.text} style={styles.flex1} /> : (
                         <View style={[styles.flex1, styles.justifyContentBetween]}>
                             <ScrollView contentContainerStyle={styles.iouDetailsContainer}>
                                 <IOUPreview
```

<img width="388" alt="Screenshot 2023-01-16 at 10 02 54 PM" src="https://user-images.githubusercontent.com/14358475/212727009-1adf78c9-3d88-4761-b62e-65aa9f7972ff.png">

**Comment by Santhosh-Sellavel** [comment] 2023-01-17 16:33
This looks like a regression, has anyone found the offending PR?

**Comment by jatinsonijs** [comment] 2023-01-17 16:45
@Santhosh-Sellavel I think its not a regression, earlier loader was not showing

https://github.com/Expensify/App/commit/ad13a227fce0c0412e0a84900e157407c89cd790

**Comment by Santhosh-Sellavel** [comment] 2023-01-17 19:42
@mountiny @Expensify/design which of the following loading is expected here?

#### FullScreenLoading
https://user-images.githubusercontent.com/85645967/212996153-8e18fdc8-2a62-4126-8b06-adcab811a4e5.mov

#### ActivityIndicator large
https://user-images.githubusercontent.com/85645967/212996137-926b66b9-77d8-4044-a0bd-fbe9aef065e4.mov

#### ActivityIndicator small
https://user-images.githubusercontent.com/85645967/212996148-81dbafd2-d4fe-4e30-91e4-ffa47ce8a6d7.mov

**Comment by shawnborton** [comment] 2023-01-18 08:44
I would think `FullScreenLoading`? But curious for your thoughts @mountiny

**Comment by Pujan92** [comment] 2023-01-18 09:14
I think the same needs to apply to `IOUParticipantsPage` too, bcoz it is also not in the center currently.

<img width="379" alt="Screenshot 2023-01-18 at 2 39 56 PM" src="https://user-images.githubusercontent.com/14358475/213130867-9893c821-5d5a-4ef7-b147-388344c5d647.png">

**Comment by jatinsonijs** [comment] 2023-01-18 09:19
@Pujan92 in which case its displayed ? I also saw it is not center aligned when I did search for all ActivityIndicator.

**Comment by Pujan92** [comment] 2023-01-18 09:23
@jatinsonijs In the current app we usually not seeing the loader for the participants page but I just reversed the condition to check the loader place and found it.

**Comment by Pujan92** [comment] 2023-01-18 14:47
**Updated Proposal for FullScreenLoadingIndicator**

Used `FullScreenLoadingIndicator` for `IOUDetailsModal` & `IOUParticipantsPage`(due to the reason of the same issue) too.
In `IOUDetailsModal` wrapped with the `View` to not overlay with the header part due to `absolute` position of `FullScreenLoadingIndicator`.

```diff
diff --git a/src/pages/iou/IOUDetailsModal.js b/src/pages/iou/IOUDetailsModal.js
index ab600cfb5..5571ab57a 100644
--- a/src/pages/iou/IOUDetailsModal.js
+++ b/src/pages/iou/IOUDetailsModal.js
@@ -24,6 +24,7 @@ import FixedFooter from '../../components/FixedFooter';
 import networkPropTypes from '../../components/networkPropTypes';
 import reportActionPropTypes from '../home/report/reportActionPropTypes';
 import FullPageNotFoundView from '../../components/BlockingViews/FullPageNotFoundView';
+import FullScreenLoadingIndicator from '../../components/FullscreenLoadingIndicator';
 
 const propTypes = {
     /** URL Route params */
@@ -165,7 +166,11 @@ class IOUDetailsModal extends Component {
                         title={this.props.translate('common.details')}
                         onCloseButtonPress={Navigation.dismissModal}
                     />
-                    {this.props.iou.loading ? <ActivityIndicator color={themeColors.text} /> : (
+                    {!this.props.iou.loading ? (
+                        <View style={[styles.flex1]}>
+                            <FullScreenLoadingIndicator />
+                        </View>
+                    ) : (
                         <View style={[styles.flex1, styles.justifyContentBetween]}>
                             <ScrollView contentContainerStyle={styles.iouDetailsContainer}>
                                 <IOUPreview
diff --git a/src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsPage.js b/src/pages/iou/steps/IOUParticipantsPage/IOUPartic
ipantsPage.js
index e87c4ac98..42d418621 100644
--- a/src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsPage.js
+++ b/src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsPage.js
@@ -7,6 +7,7 @@ import IOUParticipantsSplit from './IOUParticipantsSplit';
 import IOUParticipantsRequest from './IOUParticipantsRequest';
 import themeColors from '../../../../styles/themes/default';
 import styles from '../../../../styles/styles';
+import FullScreenLoadingIndicator from '../../../../components/FullscreenLoadingIndicator';
 
 const propTypes = {
     /** Callback to inform parent modal of success */
@@ -51,8 +52,8 @@ const defaultProps = {
 const IOUParticipantsPage = (props) => {
     if (props.iou.loading) {
         return (
-            <View style={styles.pageWrapper}>
-                <ActivityIndicator color={themeColors.text} />
+            <View style={[styles.flex1, styles.pageWrapper]}>
+                <FullScreenLoadingIndicator color={themeColors.text} />
             </View>
         );
```

<img width="378" alt="Screenshot 2023-01-18 at 8 14 42 PM" src="https://user-images.githubusercontent.com/14358475/213201931-5dc3a384-8ea1-4b46-8491-15617023a6fa.png">

**Comment by mountiny** [comment] 2023-01-18 14:54
@Santhosh-Sellavel Agreed with Shawn, `FullScreenLoading` seems like what's the best in this case.

**Comment by jatinsonijs** [comment] 2023-01-18 14:59
@Santhosh-Sellavel I think we you have same screenshot for FullScreenLoading and ActivityIndicator large

FulScreenLoading with already exist component look like this

![](https://user-images.githubusercontent.com/114683042/212727323-f94f5f94-910e-4355-8479-a1eda875670d.png)

And with large indicator 

![](https://user-images.githubusercontent.com/114683042/212727208-017adb14-9e9f-405e-9dd6-c076bc26ed18.png)

**Comment by jayeshmangwani** [comment] 2023-01-18 15:03
> FullScreenLoading

wanted to confirm if I can update my [proposal](https://github.com/Expensify/App/issues/14321#issuecomment-1384284245) based on FullScreenLoading component requirement or not ? as I have first proposed for the LoadingIndicator only, when i proposed my solution at that time we were talking about LoadingIndicator

cc: @Santhosh-Sellavel @vitHoracek

**Comment by mountiny** [comment] 2023-01-18 15:22
Hmm I dont like the header and the X button is dimmed in that screenshot.

Can we confirm whats used in similar pages for Workspace set up etc? I think there should be just one loading indicator for all of these right hand side modals

**Comment by jatinsonijs** [comment] 2023-01-18 15:40
@mountiny on other pages loader not cover header and cross button. FullScreenLoadingIndicator loader inside other views so its not cover header.

**Comment by jayeshmangwani** [comment] 2023-01-18 15:45
https://github.com/Expensify/App/blob/8e76903ff364e4c9b8d63f3aecff0a23e02d0ae9/src/pages/workspace/reimburse/WorkspaceReimburseSection.js#L79-L84

@mountiny I think we should go with the alignItemsCenter and justifyContentCenter as we are doing in WorkspaceReimburseSection

**Comment by Pujan92** [comment] 2023-01-18 15:55
> @mountiny I think we should go with the alignItemsCenter and justifyContentCenter as we are doing in WorkspaceReimburseSection

We do not require those properties with the `View`  bcoz `ActivityIndicator` already has those styles which I mentioned [here](https://github.com/Expensify/App/issues/14321#issuecomment-1384299641)

**Comment by mountiny** [comment] 2023-01-18 16:06
@Santhosh-Sellavel I think the best solution will be the one which does not cover the header. Not sure who presented the best proposal here right now.

**Comment by mountiny** [comment] 2023-01-18 17:27
Thanks @Santhosh-Sellavel and everyone for their proposals, its really great to see so many people ready to help!

@jatinsonijs Can you please get a PR ready? thankyou!

**Comment by jatinsonijs** [comment] 2023-01-18 17:28
Thanks @mountiny and @Santhosh-Sellavel, sure will raise PR by Today

**Comment by jatinsonijs** [comment] 2023-01-18 18:47
[PR](https://github.com/Expensify/App/pull/14391) is ready for review

cc @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2023-01-18 18:52
Thanks, but seems the issue is not linked properly the first time so it missed assigning the correct reviewers.

**Comment by jatinsonijs** [comment] 2023-01-18 18:56
I have linked correct issue @Santhosh-Sellavel, this is known issue happened with other PR also.

**Comment by mountiny** [comment] 2023-01-18 19:15
@jatinsonijs 
<img width="383" alt="image" src="https://user-images.githubusercontent.com/36083550/213273338-e4099a58-15fc-4f43-a4d3-48913d8fadb9.png">
it seems like that when it was created there was not space between the link and the `$` symbol which will break the linking.

What is the other instance of this being broken? I worked on this integration so I am curious 😄

**Comment by sakluger** [comment] 2023-01-19 00:35
I've sent offers in Upwork to @jatinsonijs ($1250 for the $1000 Contributor payment and $250 reporting bonus) and @Santhosh-Sellavel ($1000 for the Contributor+ payment).

**Comment by jatinsonijs** [comment] 2023-01-19 01:55
> What is the other instance of this being broken? I worked on this integration so I am curious 😄

https://github.com/Expensify/App/pull/14156#issuecomment-1377028598

**Comment by mountiny** [comment] 2023-01-19 07:23
@jatinsonijs As mentioned by Rajat [here](https://github.com/Expensify/App/pull/14156#issuecomment-1377036042), for their PRs it was expected at the time. I think it should work for his PRs as well now

Thanks for having 🦅 👀 though!

**Comment by mountiny** [comment] 2023-01-19 07:23
@sakluger Just merged the PR, I think there will be speed bonus to be paid here as well 🎉

**Comment by mountiny** [comment] 2023-01-23 18:30
@Santhosh-Sellavel would you be bale to help with the checklist?

**Comment by Santhosh-Sellavel** [comment] 2023-01-23 18:43
This exists right from the start, not introduced by any changes. @mountiny

**Comment by mountiny** [comment] 2023-01-23 18:57
Thanks @Santhosh-Sellavel!

@sakluger thinking how to catch this in a regression test, I think there is many pages which have such spinner, all of them should have it vertically centered

**Comment by sakluger** [comment] 2023-02-01 02:28
Sorry folks, I missed the payment day because I was looking in my daily assignments, but it stayed in Weekly. I just paid out @Santhosh-Sellavel and @jatinsonijs including the efficiency bonus, thanks for the quick work everyone!

**Comment by sakluger** [comment] 2023-02-01 18:36
@mountiny brought up a good point in Slack that we'll be redoing this page soon for the Manual Requests project, so no need to add new regression tests now.

**Closed by sakluger** 2023-02-01 18:36 UTC
Labels: Reviewing, External, Engineering, Weekly, Awaiting Payment, Bug
