### ISSUE TITLE
[$500] No page with “Set up my company for free” after signing up with an account with a WS

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34211] opened 2024-01-10 06:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to OD and sign in with an account that has a Workspace or sign up for a new account

## Expected Result:
A page with the CTA "Set up my company for free" can be seen. User can tap on it to go to ND

## Actual Result:
There's no such page. User is redirected to OD similar to how desktop web works if it's a new email or is redirected to OD's home page if it's a sign in

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/61595794-6f7d-4b43-b504-34f57efffa65

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017855f59ae1dca841</li>
        <li>Upwork Job ID: 1744972959784497152</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

**Comment by hkopser99** [comment] 2024-01-10 10:01
Contributor details:
Expensify account email: [hkopser@me.com](mailto:hkopser@me.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0141fe061cf82b5462

Hello, I'd like to resolve this. While I don't see code referenced, assuming there is a component or multiple components in existence that would make up the 'set up my company for free' UI, this is likely either a Routing issue or a matter of failing to check if that UI or a button/link to it should be rendered for particular users. It may also be a matter of CSS not rendering for the iOS Mobile Safari. Regardless of the cause, once reviewing the related components, I see this as an easy fix.

**Comment by ikevin127** [comment] 2024-01-10 11:04
If I understand correctly the expected result requires modifications to the OD codebase, therefore this issue should be handled internally.

**Comment by sobitneupane** [comment] 2024-01-16 06:14
@NicMendonca As it is related to OD, I believe this should be handled internally.

**Comment by NicMendonca** [comment] 2024-01-16 13:27
Not prioritising OD right now so closing this for now

**Closed by NicMendonca** 2024-01-16 13:27 UTC
Labels: External, Daily, Help Wanted, Bug
