### ISSUE TITLE
Android – Sign in Hibrid app – Wellcome modal appears if transition from HybridApp to NewDot

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50053] opened 2024-10-02 11:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ponikarchuks+1311024@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/issues/49960
## Action Performed:
1. Go to staging NewDot app
2. Log in with a new Gmail account and finish the onboarding
3. Login on HybridApp with the same account
4. Click on Try New Expensify in LHN for transition from OldDot to NewDot

## Expected Result:
Wellcome to Expensify modal is not shown

## Actual Result:
Wellcome to Expensify modal appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6dc34d7a-cff4-4ff3-a97e-71e00831eded

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @srikarparsi</details>

**Comment by lanitochka17** [comment] 2024-10-02 11:41
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by isogit123** [comment] 2024-10-06 16:07
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The welcome modal appears when transitioning from HybridApp to NewDot.

### What is the root cause of that problem?
The onboarding flow is explicitly set to be shown when transitioning to NewDot if the OldDot onboarding is completed but the NewDot onboarding is not here:
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/hooks/useOnboardingFlow.ts#L35-L39

### What changes do you think we should make in order to solve the problem?
Remove the code mentioned above to disable this behavior.

### What alternative solutions did you explore? (Optional)

**Comment by dylanexpensify** [comment] 2024-10-07 12:22
TY @ishpaul777!

**Comment by dylanexpensify** [comment] 2024-10-17 20:32
Hey @kadiealexander! I'm heading out on parental leave so reassigning this! TY!

**Comment by srikarparsi** [comment] 2024-10-22 01:47
Yes agreed @ishpaul777, the onboarding flow was not completed in the video and that's why the onboarding flow re-opened as you [explained](https://github.com/Expensify/App/issues/50053#issuecomment-2417721582). Going to close this one out.

**Closed by srikarparsi** 2024-10-22 01:47 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
