### ISSUE TITLE
[HOLD for C+ newdot payment] [$500] Web - App crashes when currency in url is changed to invalid currency code

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26619] opened 2023-09-03 19:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go to any chat
2. Open request money
3. Change currency in currency list
4. Notice there is a currency code in url indicating selected currency
5.  (a). Now change that currency code in url to invalid currency code for example `ABCD`
Another case:
5.  (b). Change currency code in url to not invalid currency code but keep it 3 letters like `ABC`

## Expected Result:
 In both cases invalid currency should be ignored and default currency should be selected

## Actual Result:
 a) App crashes.
b) You can request money with invalid currency code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Case A**

https://github.com/Expensify/App/assets/93399543/22a93902-cd73-4c31-a848-a2bd908999ce

https://github.com/Expensify/App/assets/93399543/cd1b7aa4-f1c1-4988-ac95-307304242511

**Case B**

https://github.com/Expensify/App/assets/93399543/bbd5f249-63ad-4fe2-830c-4336681c8a82

https://github.com/Expensify/App/assets/93399543/df23d3e7-967e-4f9d-82cf-a2afe0b7a70f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @alitoshmatov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693385994296529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140a8a0afc8dbbe3d</li>
        <li>Upwork Job ID: 1698528155580948480</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-03 19:42
Proposal by: @alitoshmatov
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1693385994296529

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
App crashes when currency in url is changed to invalid currency code
### What is the root cause of that problem?
The issue is happening because we are not checking if currency from route params is valid or not.
https://github.com/Expensify/App/blob/28065b44e3b856ec644accd79366b06ca95e4c53/src/pages/iou/steps/NewRequestAmountPage.js#L85
### What changes do you think we should make in order to solve the problem?
We should introduce a process to check if currency from route param is valid or not, then accept it only if it is a valid currency if not we should fallback to default currency.
We can achieve it by introducing a new function to validate currency code when we get it from route, something like this:
```javascript
function validateCurrency(route) {
  const currencyCode = lodashGet(route, 'params.currency', '');
  const currency = lodashGet(currencyList, currencyCode);
  return currency ? currencyCode : '';
}
```
By returning empty string, we let it fallback to default currency which
https://github.com/Expensify/App/blob/28065b44e3b856ec644accd79366b06ca95e4c53/src/pages/iou/steps/NewRequestAmountPage.js#L85
### What alternative solutions did you explore? (Optional)

**Comment by kadiealexander** [comment] 2023-09-04 02:47
Reproduced:

![image](https://github.com/Expensify/App/assets/59587260/94c6037e-c25a-457d-8db9-a81a1ba3585b)

**Comment by napster125** [comment] 2023-09-04 03:34
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The app crashes when the currency in the URL is changed to an invalid currency code.
### What is the root cause of that problem?
We currently don't perform a check to verify whether the currency from the route parameters is valid or not.
This issue is not limited to the new money request page; it also affects the edit and confirmation money request pages.
### What changes do you think we should make in order to solve the problem?
We can find the relevant code here: https://github.com/Expensify/App/blob/4676492705a96d766fd1f0f1d2e2401cfd5bc566/src/pages/iou/steps/MoneyRequestAmountForm.js#L252
https://github.com/Expensify/App/blob/44721d2035642266b43d1bad36b30d7a3c5e239d/src/libs/CurrencyUtils.js#L65-L67
Fortunately, we already have a function for obtaining the currency symbol. If the currency symbol is `undefined`, it signifies that the currency is invalid. While we could create a custom validation function for currency, I believe it would be more consistent and simpler to add the validation logic for currency to the submit button in the `MoneyRequestAmountForm`.
```
isDisabled={!currentAmount.length || parseFloat(currentAmount) < 0.01 || !CurrencyUtils.getCurrencySymbol(currency)}
```
### What alternative solutions did you explore? (Optional)
Alternatively, we can include form helper text in our money request form to display the error using the proposed validation logic.

### Result:
![image](https://github.com/Expensify/App/assets/136437976/705ad956-933c-4a21-b100-83eb45821053)

**Comment by sobitneupane** [comment] 2023-09-11 08:51
Thanks for the proposal @alitoshmatov and @napster125 .

I believe it's better idea to show default currency instead of disabling the button.

So, [proposal](https://github.com/Expensify/App/issues/26619#issuecomment-1704385505) from @alitoshmatov looks good to me. @alitoshmatov Let's make sure to handle the case in edit and confirmation money request page as well if it exists.

🎀 👀 🎀 C+ reviewed

**Comment by MonilBhavsar** [comment] 2023-09-13 08:50
> I believe it's better idea to show default currency instead of disabling the button.

👍 

Proposal looks good, though I think validateCurrency should only return boolean if currency is valid. We can address that in a PR.

**Comment by MonilBhavsar** [comment] 2023-09-13 08:51
@alitoshmatov needs to comment on this issue, so I can assign them.

**Comment by alitoshmatov** [comment] 2023-09-13 09:08
@MonilBhavsar 👋

**Comment by MonilBhavsar** [comment] 2023-09-15 11:35
Melvin, I assigned contributor!

**Comment by alitoshmatov** [comment] 2023-09-15 16:12
@MonilBhavsar Can we hold this issue, there is a new bug with request money flow where after currency selection tab is changed back to scan. So far no issue is created but It looks like it is already reported in slack - https://expensify.slack.com/archives/C049HHMV9SM/p1694766009988229

**Comment by alitoshmatov** [comment] 2023-09-15 17:41
Found a way to test it without that another bug getting in the way, but since that bug is likely a deploy blocker we can hold this one till the solution for that bug is merged

PR - https://github.com/Expensify/App/pull/27550

**Comment by MonilBhavsar** [comment] 2023-10-02 15:44
Awaiting payment and need to complete checklist here

**Comment by alitoshmatov** [comment] 2023-10-02 16:48
Applied to the upwork job since automation didn't work

**Comment by kadiealexander** [comment] 2023-10-05 06:06
Payouts due:

- [ ] Issue Reporter: $50 @alitoshmatov
- [ ] Contributor: $500 @alitoshmatov
- [ ] Contributor+: $500 @sobitneupane

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/jobs/~0140a8a0afc8dbbe3d).

**Comment by kadiealexander** [comment] 2023-10-05 06:12
@alitoshmatov could you please apply here? https://www.upwork.com/jobs/~0196e99f5c78661337

**Comment by alitoshmatov** [comment] 2023-10-05 08:04
@kadiealexander Applied

**Comment by kadiealexander** [comment] 2023-10-06 04:05
@alitoshmatov sent you a contract!

**Comment by alitoshmatov** [comment] 2023-10-06 05:04
@kadiealexander Accepted contract

**Comment by sobitneupane** [comment] 2023-10-09 07:15
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/23979
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/23979#issuecomment-1752457582
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is an edge case and could have easily missed in PR review.

> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-10-09 07:17
**Regression Test Proposal**

1. Go to any chat
2. Open request money
3. Change currency code
4. Notice there is a currency code in url indicating selected currency
5. Now change that currency code in url to invalid currency code (for example: ABCD and ABC)
6. Make sure this invalid currency code is not applied and default currency code is selected

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-10-09 08:50
https://github.com/Expensify/App/issues/26619#issuecomment-1748141483

Requested payment on newDot

**Comment by JmillsExpensify** [comment] 2023-10-09 17:53
$500 payment approved for @sobitneupane based on BZ summary.

**Closed** 2023-10-09 20:44 UTC
Labels: External, Weekly, Awaiting Payment, Bug
