### ISSUE TITLE
[$250] DEV - Console error on clicking "fix the errors" on Company information page - iOS - reported by @0xmiroslav 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12508] opened 2022-11-07 13:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login and go to Settings -> Workspaces -> workspace -> Connect bank account page
2. Select Connect manually
3. Enter valid routing number and account number
4. Click Save & continue
5. Click "fix the errors" shown above Save & continue button

## Expected Result: 
Nothing happens on native (Checkbox highlighted on web/desktop)

## Actual Result: 
Shows console error on iOS (other platforms work as expected)

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS Only (Happens only in Dev, Not in staging / production)

**Version Number:** 1.2.24-0

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200325166-136178a7-da62-4fa0-8417-d2df7401d54f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @0xmiroslav 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667741154056619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment] 2022-11-08 00:04
@deetergp - Any chance you can help me test this for recreation? I don't have a dev environment to do it. 🙏

**Comment by strepanier03** [comment] 2022-11-08 01:13
Nevermind Scott, I'm all good. I read "dev console" and my brain went "dev environment" 🤦‍♀️ . Unassigning you now.

**Comment by strepanier03** [comment] 2022-11-08 01:14
@kavimuru @0xmiroslav - I am unable to recreate the error that you're showing. 

Nothing happens when I click the "Fix the error" text but I also don't have any error in my dev console. 

Can you still both recreate?

**Comment by Luke9389** [comment] 2022-11-08 01:15
I mislead @strepanier03 here, this problem is on iOS so needs to be tested by an engineer. Sorry!

**Comment by strepanier03** [comment] 2022-11-08 01:20
No worries at all Luke, I'm learning and appreciate all of these no matter what the outcome.

**Comment by Gonals** [comment] 2022-11-08 14:44
Hmmm. I seem to be able to reproduce this in the iOS simulator. I don't have a real iOS device to test, though

**Comment by strepanier03** [comment] 2022-11-08 23:45
@Gonals - Should I find someone with a real iOS device to test it (I don't have one either) or do you think we have sufficient evidence to put the External label on it and get it worked on? 

Also, what sort of behavior are we expecting to happen here when clicking the "fix the errors" link? Is the behavior on the page correct?

**Comment by Gonals** [comment] 2022-11-09 09:59
I think we are good to make this external 👍 

The expected behavior, in general, is to scroll up to where the errors are. In this specific page? We don't really need to do anything, since there is no scrolling involved 😅

**Comment by strepanier03** [comment] 2022-11-10 00:05
That's what I was thinking @Gonals, the behavior on the page seem appropriate considering no scroll is needed. 

I will toss external on this and get the job made. Thank you for helping me here!

**Comment by strepanier03** [comment] 2022-11-10 00:10
Internal Upwork job: https://www.upwork.com/ab/applicants/1590496858216435712/suggested

----

Public job posting: https://www.upwork.com/jobs/~0145c9a4f39844c843

**Comment by parasharrajat** [comment] 2022-11-10 00:15
No proposals.

**Comment by strepanier03** [comment] 2022-11-11 01:33
I am out of the office tomorrow. If there is an urgent need on this GH from a BugZero team member, please post in #expensify-open-source for assistance.

**Comment by smrutiparida** [comment] 2022-11-11 11:09
The below issue looks similar to the one disccused 
https://github.com/facebook/react-native/issues/32145
https://github.com/software-mansion/react-native-reanimated/issues/2370
https://github.com/software-mansion/react-native-reanimated/issues/2364

They were resolved as fixed in PR https://github.com/software-mansion/react-native-reanimated/pull/2404

As we are in the RN version > 0.65 and react-native-reanimated > 3.0.0-rc.3 the issue should not have occured. I am debugging more to find the cause

**Comment by huzaifa-99** [comment] 2022-11-11 23:02
I think a similar issue https://github.com/Expensify/App/issues/12400 also exists for the same page. The focus there is not set to the first field when the label (fix the errors) is clicked. The root cause might be related and maybe something to look into.

Anyways if this is not a duplicate and we are only concerned with removing the console error.
### Proposal
We can refactor the callback fired about `Fix the label` is clicked
https://github.com/Expensify/App/blob/0d244e4338f5b258096880bf592f6e73b25fac7e/src/components/Form.js#L230-L232 to 
```js
onFixTheErrorsLinkPressed={() => {
    const firstInputRef = this.inputRefs[_.first(_.keys(this.state.errors))]
    if(firstInputRef) firstInputRef.focus();
}}
```
### Demo

https://user-images.githubusercontent.com/68777211/201441816-b7998c10-c384-45f7-b85a-b4f3ff470d7c.mp4

**Comment by parasharrajat** [comment] 2022-11-12 18:53
Looks like a tough one. There is no direct solution available. I don't consider this RN fault either. We calling `focus` on Pressable which we shouldn't and there is direct way to prevent that from Form. Let me know if I am wrong. 


@aldo-expensify  Because, this is only happening on dev,  we can ignore this issue. RN ignores focus call on Android but it iOS code is still behind.

**Comment by huzaifa-99** [comment] 2022-11-13 22:01
> @huzaifa-99 you missed reproducing step: 3. Enter valid routing number and account number

oops, my bad. Apologies if I caused confusion.

**Comment by aldo-expensify** [comment] 2022-11-15 00:05
Yep, I agree, we can wait for the fix to reach IOS as this doesn't really block our development and the bug doesn't happen in production/staging. I looked a bit into trying to avoid the crash, but I failed find a way.

**Closed by aldo-expensify** 2022-11-15 00:05 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by cubuspl42** [comment] 2023-03-19 16:33
@aldo-expensify

I encountered this error when working on another issue.

Isn't the solution as easy as... not calling that method?

`Checkbox.js`:
```js
class Checkbox extends React.Component {
    // ...

    focus() {
        this.onFocus();
    }

    blur() {
        this.leaveFocus();
    }

    measureLayout(...args) {
        return this.root.measureLayout(...args);
    }

    render() {
        return (
            <Pressable
                // ...
                ref={el => this.root = el}
                // ...
            >
              // ...
            </Pressable>
        );
    }
}
```

`CheckboxWithLabel.js`:
```js
                    <Checkbox
                        // ...
                        ref={this.props.forwardedRef}
                    />
```

**Comment by cubuspl42** [comment] 2023-03-20 22:42
@aldo-expensify, I'm saying not to call `Pressable.focus`, the one throwing exceptions. Instead we could provide a best-effort `focus` method in the `Checkbox` class, like in the code snippet in the post above.

**Comment by cubuspl42** [comment] 2023-03-20 22:44
Because as I understand it, `Pressable` doesn't have a _functional_ `focus` on any platform, right? Does it do anything on Web?
