### ISSUE TITLE
[HOLD for payment 2023-07-17] [HOLD for payment 2023-07-14] Not able to split money on back button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22302] opened 2023-07-05 19:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On chrome staging website > FAB icon > Split Bill > Enter amount > Click Next >Select any user > Click Next to open up the split bill page ( Do NOT click split button)
2. Now click on the user > Click back and see that the split money page is gone
## Expected Result: 
Back button should not end the split bill page
## Actual Result: 
Back button ends the split bill page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cd9f3625-1c70-45c6-8537-3de2dcf6c409

https://github.com/Expensify/App/assets/43996225/935b3d9e-6c1d-4a24-a505-aa8d819dc245

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Santhosh-Sellavel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688586118022729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-07-06 09:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Back button ends the split bill page after open user detail page. 

### What is the root cause of that problem?
The following code is called if clicks the user on the split bill confirmation page.
https://github.com/Expensify/App/blob/a2a521d9ac1f22ccf50cd973d7704d82337522da/src/components/MoneyRequestConfirmationList.js#L199-L204

The Money Request page and the Profile page are separate screens, seperate RHP flows.
As a result, the following code will replace navigation routes. and the money request flow will be removed after navigating to the user profile page.
https://github.com/Expensify/App/blob/a2a521d9ac1f22ccf50cd973d7704d82337522da/src/libs/Navigation/linkTo.js#L80-L90

Therefore clicking back will close the modal and end the split bill process.
### What changes do you think we should make in order to solve the problem?
According to the above code comments, replacing routes when changing flow is intended.
However, I think navigating from split bill or money request to user detail page should follow the same flow and not replace routes.
We can change [this line](https://github.com/Expensify/App/blob/a2a521d9ac1f22ccf50cd973d7704d82337522da/src/libs/Navigation/linkTo.js#L84) as below.
```js
-   if (targetName === NAVIGATORS.RIGHT_MODAL_NAVIGATOR) {
+   if (targetName === NAVIGATORS.RIGHT_MODAL_NAVIGATOR && minimalAction.payload.name !== 'Profile') {
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by Julesssss** [comment] 2023-07-06 12:55
Same underlying cause as [this issue](https://github.com/Expensify/App/issues/22289). I'm going to close this and add this additional case to the issue description

**Comment by Santhosh-Sellavel** [comment] 2023-07-06 15:01
@Julesssss But I reported this issue before the other one please check https://expensify.slack.com/archives/C049HHMV9SM/p1688507121082889

**Comment by Julesssss** [comment] 2023-07-06 16:21
@Santhosh-Sellavel I documented this [here](https://github.com/Expensify/App/issues/22289#issuecomment-1623855949) on the other issue

**Comment by Julesssss** [comment] 2023-07-06 16:29
My mistake. This is still occurring 😖

**Comment by Julesssss** [comment] 2023-07-06 16:34
Hi @StevenKKC, thanks for your proposal. Checking for a specific profile page doesn't seem like it solves the underlying issue though.

**Comment by mountiny** [comment] 2023-07-06 19:25
PR is up

**Comment by Julesssss** [comment] 2023-07-07 07:37
Thank you @mountiny!

**Comment by Santhosh-Sellavel** [comment] 2023-07-09 19:48
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/21067
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/21067/files#r1257532582
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: [Here](https://expensify.slack.com/archives/C049HHMV9SM/p1688932059028169)
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. Yes
> * [ ]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [ ]  [] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

cc: @mountiny Let me know if you differ on any of the above.

**Comment by Santhosh-Sellavel** [comment] 2023-07-09 19:49
### Regression Steps

From PR looks good

1. From Global create, select Split Bill
2. Go through the flow until the confirmation page
3. click on the user details (do not create the split)
4. Click Back (UP action) in left top corner of RHP
5. Verify the screen navigated back to the confirmation page

👍  or 👎

**Comment by mountiny** [comment] 2023-07-17 10:49
Reassinging the Bug label to get someone to pay this out

@Santhosh-Sellavel should get $1250 for the review and reporting the bug

**Comment by Santhosh-Sellavel** [comment] 2023-07-17 17:33
Requested payment on ND

**Comment by tjferriss** [comment] 2023-07-19 05:16
@Santhosh-Sellavel have you been paid via NewDot?

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 18:40
Yeah got paid! Good to close this!

**Closed** 2023-07-20 19:59 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
