### ISSUE TITLE
Profile - When opening profile, in settings, "Private" section loads infinitely.

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49461] opened 2024-09-19 12:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Navigate to settings.
3. Tap on "Profile"
4. Scroll down to "Private"
5. Verifiy the section loads smoothly and the user can access all the fields in the category.

## Expected Result:
All the sections in profile, should load properly and the user should be able to access to all the available fields.

## Actual Result:
The "Private" section in profile settings, loads infinitely and the user is not able to see any of the fields in the section. Despite refreshing the page or logging out and in again, the infinite loading keeps displaying.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ef0cf47b-166f-4444-80dd-ca968702f91e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-19 12:19
We think that this bug might be related to #wave-collect - Release 1

**Comment by grgia** [comment] 2024-09-19 12:31
Likely caused by https://github.com/Expensify/App/pull/48517 @rushatgabhane

**Comment by NJ-2020** [comment] 2024-09-19 12:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Profile - When opening profile, in settings, "Private" section loads infinitely. 
### What is the root cause of that problem?
The `isLoadingApp` returning array value instead of boolean
![Screenshot 2024-09-19 at 05 34 09](https://github.com/user-attachments/assets/d62dd0cd-f234-4198-b922-73f0d6027e0a)
So when we check here it will return true because an array value return true
https://github.com/Expensify/App/blob/37bf6b2fef128786dfcd83257a56f56c0cd1eb3d/src/pages/settings/Profile/ProfilePage.tsx#L192-L202
### What changes do you think we should make in order to solve the problem?
We can change to something look like this `isLoadingApp[0] || (!Array.isArray(isLoading) && isLoading)]`


### What alternative solutions did you explore? (Optional)

**Comment by dangrous** [comment] 2024-09-20 16:22
I think we can close this one out, no payment necessary.

**Closed by dangrous** 2024-09-20 16:22 UTC
Labels: Reviewing, Engineering, Weekly, Bug
