### ISSUE TITLE
[$1000] Web - Workspace- Date is not clickable under Personal information page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20972] opened 2023-06-17 19:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Go to settings > workspace >Bank account > connect manually
3. Fill the form until step 3
4. Select todays date - (in my case 2005-06-10) for the date of birth 
5. Change the date to 2005-06-25

## Expected Result:
Date is clickable under Personal information page

## Actual Result:
Date is not clickable under Personal information page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cd8fa269-b7a1-4c35-a8e4-b85a5ec0ccbb

**Expensify/Expensify Issue URL:**

**Issue reported by:** @narzullome

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686396762249499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0173f8064c5dc2674d</li>
        <li>Upwork Job ID: 1671080425393836032</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2023-06-19 09:19
Got this sorted, btw @kbecciv for issues like this that are already in production, no need to add `Dev` to the title! 🙇‍♂️

**Comment by dylanexpensify** [comment] 2023-06-19 09:33
Unable to reproduce - @kbecciv can you confirm if still reproducible on your side?

**Comment by narzullome** [comment] 2023-06-19 23:43
@dylanexpensify Pls select todays date - for a year select 2005 
For ex - 2005 -06-20 with this dates and year - just now I was able to reproduce

**Comment by dylanexpensify** [comment] 2023-06-20 08:59
Reproduced

**Comment by alitoshmatov** [comment] 2023-06-20 09:31
I think it is expected behavoir since user must be 18 years old, and any date of birth younger than this is disabled. 
Maybe the problem is that datepicker in safari is not showing disabled these dates where in chrome it does
<img width="383" alt="Screenshot 2023-06-20 at 2 30 54 PM" src="https://github.com/Expensify/App/assets/59907218/73b809a0-b59b-4548-8b3a-2dc1ffaf2aec">

**Comment by Ali-ch88** [comment] 2023-06-20 10:37
Hi, It's working fine on Chrome and Safari as well.
https://github.com/Expensify/App/assets/61835503/4e6a9bde-590e-4010-9184-d6f23d34d724

**Comment by s77rt** [comment] 2023-06-20 11:19
@dylanexpensify We can close this one. All date pickers will soon be replaced by our custom push to page date picker.

**Comment by s77rt** [comment] 2023-06-22 21:18
Not overdue. @dylanexpensify ^

**Comment by dylanexpensify** [comment] 2023-06-26 17:47
Ahh nice! Thanks @s77rt !

**Closed by dylanexpensify** 2023-06-26 17:47 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
