### ISSUE TITLE
[$500] Android - Scan - Camera preview in Scan becomes blank after returning from Distance

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27879] opened 2023-09-20 18:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app.
2. Go to + > Request money.
3. Go to Scan and enable camera access if not allowed yet.
4. Go to Distance.
5. Go back to Scan.

## Expected Result:
Camera preview works without issue

## Actual Result:
Camera preview is now blank

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/bd797a03-8a91-4fb3-870f-30c7cafcaf3a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018be32f891c61fb2c</li>
        <li>Upwork Job ID: 1707637360214872064</li>
        <li>Last Price Increase: 2023-09-29</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27009429</li>
</ul></li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-09-29 06:04
Agree this should probably be fixed, adding relevant labels.

**Comment by stephanieelliott** [comment] 2023-10-04 01:25
Thanks @thesahindia! Assigned @dukenv0307

**Comment by stephanieelliott** [comment] 2023-10-11 05:10
PR is under review

**Comment by stephanieelliott** [comment] 2023-10-17 01:24
Still under review

**Comment by sonialiap** [comment] 2023-10-30 14:15
A possible regression https://github.com/Expensify/App/issues/30280

**Comment by dangrous** [comment] 2023-11-01 17:40
We're closing #30280 as an individual but please handle the solution here

Action Performed:
Go to + > Request money
Go to Scan and enable camera access if not allowed yet
Go to Distance, then Manual a few times
Go back to Scan
Expected Result:
The camera should not blink when switching between tabs

Actual Result:
Camera blinks when switching between tabs

**Comment by mananjadhav** [comment] 2023-11-01 18:04
@dukenv0307 quick bump regarding the regression PR.

**Comment by mananjadhav** [comment] 2023-11-03 18:10
> Can you help build ad-hoc for ios so I can test the ios camera here

@dukenv0307 I didn't understand.  What do we mean by adho build for iOS? The issue is reproducible on App Store build.

**Comment by mananjadhav** [comment] 2023-11-07 12:33
@dukenv0307 can you ask on the slack? Even I don't know if external contributors can build on iOS.

**Comment by bondydaa** [comment] 2023-11-08 16:53
discussing in that slack thread (https://expensify.slack.com/archives/C01GTK53T8Q/p1699410931837159) what next steps are, i'm so confused here.

**Comment by bondydaa** [comment] 2023-11-09 18:32
okay threw these idea out in the thread:
1. If @dukenv0307 has an idea of how to fix create a PR and we'll create an ad-hoc build to test
2. Or @mananjadhav could take over writing the PR since you have a physical ios device it seems to test while you go? Then @dukenv0307 can help review the PR (sort of swapping roles).

Either of those seem like a good path forward to unblock this?

**Comment by mananjadhav** [comment] 2023-11-10 21:46
@bondydaa I think the iOS development will blocked for me too. I'll check this over the weekend.

**Comment by stephanieelliott** [comment] 2023-11-20 11:50
Hey @mananjadhav did you have a chance to check this?

**Comment by mananjadhav** [comment] 2023-11-26 17:39
Nope I am unable to debug this on physical iOS device.

**Comment by stephanieelliott** [comment] 2023-11-28 03:11
Hey @lanitochka17 can you confirm whether this is still reproducible?

**Comment by stephanieelliott** [comment] 2023-11-28 18:20
Ok, gonna consider the regression fixed so let's pay out on the original issue. Summarizing payment: 

 - Issue reporter: N/A
 - Contributor: @dukenv0307 $500, pay via Upwork 
 - Contributor+: @mananjadhav $250 ($500 - 50% penalty for regression), request via Newdot 
 
 Upwork job is [here](https://www.upwork.com/jobs/~018be32f891c61fb2c)

**Comment by mananjadhav** [comment] 2023-11-29 17:15
@stephanieelliott @bondya  Wanted to raise this if we can payout the full amount on this one? The regression (which was fixed via some PR), couldn't be tested by me because we don't have physical build access. Hence it wasn't possible to identify the regression at all. 

Also tagging @mountiny as they helped with the iOS QA.

**Comment by mountiny** [comment] 2023-11-30 14:05
I think it makes sense to not give penalty if C+ could not catch this.

Can you not build even from XCode with the automatic certificate?

**Comment by mananjadhav** [comment] 2023-11-30 14:13
> Can you not build even from XCode with the automatic certificate?

No. and I tried multiple attempts for the adhoc build.

**Closed** 2023-12-04 17:38 UTC
Labels: External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2023-12-11 01:33
$500 payment approved for @mananjadhav based on summary above.
