### ISSUE TITLE
Accounting - User need no sync Xero integration after connection

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42992] opened 2024-06-03 13:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check 
**Found when executing PR :** https://github.com/Expensify/App/pull/42360
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite:
Workspace with Xero account with no previous data sync attempt. In case the sync is done, disconnect and setup agai.
Steps

1. Login with a user who already has the Xero account setup.
2. Go to Workspace having Xero connection -> Accounting -> Export.
3. Verify in Xero bank account, the first option is shown in the Menu Item. For the Demo company it's Business Bank Account.
Clicking the item should also show the first option selected.
4. Go to Workspace having Xero connection -> Accounting -> Advanced.
Repeat the steps 4 and 5, for Xero Bill Payment Account and Xero Invoice Collections Account.

## Expected Result:
In Xero bank account, the first option is shown in the Menu Item.
In Xero Bill Payment Account and Xero Invoice Collections Account, the first option is shown in the Menu Item.

## Actual Result:
No options in Xero bank account, Xero Bill Payment Account and Xero Invoice Collections Account.
User has to 'Sync now' Xero integration (opposite to pre-requisite) to be able see options.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4e4530af-a886-48b0-8806-8c524c94d633

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-06-03 13:47
We think this issue might be related to the #collect project.

**Comment by puneetlath** [comment] 2024-06-03 14:03
Discussed here: https://expensify.slack.com/archives/C036QM0SLJK/p1717422872999129

Not a blocker. Potentially a back-end issue.

**Comment by neil-marcellini** [comment] 2024-06-03 17:42
Tom [said](https://expensify.slack.com/archives/C036QM0SLJK/p1717436410083009?thread_ts=1717422872.999129&cid=C036QM0SLJK) this, so removing the backend blocker label too.

> It shouldn’t be blocking the deploy, Accounting is behind a beta so nobody will run into this.

**Comment by trjExpensify** [comment] 2024-06-05 01:30
@izarutskaya we think this might be an issue with pusher. Can you help us confirm that? 

1. Experience the problem (i.e the default config is missing when connecting to Xero/QBO)
2. Log out and log back in
3. Check if the policy connection data is there or not (i.e are all the expected default accounts selected?)

If the answer is yes, we suspect this happened because you missed all pusher events. CC: @aldo-expensify

**Comment by hayata-suenaga** [comment] 2024-06-06 16:46
[Asking the QA team for retest with additional instructions](https://expensify.slack.com/archives/C9YU7BX5M/p1717692237722309)

**Comment by kbecciv** [comment] 2024-06-08 10:51
Issue is still reproducible, re login did not help. And tester needed to make another manual sync to import needed fields

https://github.com/Expensify/App/assets/93399543/6a4a286d-4128-46f1-88e5-946557fc585b

**Comment by trjExpensify** [comment] 2024-06-11 16:45
@aldo-expensify has fixed this in Web-E & IS. The crux of the problem was disabling onyxUpdates from OldDot because of the fires. So we've reenabled them for IS jobs created from NewDot. 

Feel free to retest on staging, but this should be good.

**Comment by kavimuru** [comment] 2024-06-11 18:57
Bug is still reproducible. 

https://github.com/Expensify/App/assets/43996225/769b9b47-e709-4680-bfc3-f00dd3587699

**Comment by aldo-expensify** [comment] 2024-06-11 19:13
Yep, that doesn't look like a pusher problem, since they logged out and back in and the problem is still there.

**Comment by aldo-expensify** [comment] 2024-06-11 19:33
I couldn't reproduce this in dev. I wonder if there is some race condition here:

https://github.com/Expensify/Web-Expensify/blob/c976bff01d5bd36a9962a1ee963af34a7198c416/partners/xero/oauth_callback.php#L123-L131

If the `Xero::import($authToken, $targetPolicyID);` call finishes fast enough (before the 1s timeout), then the call `PolicyStore::save($authToken, $policy);` could overwrite the values pulled by the integration because these values are not in the policy stored in the cache. I think we should revert the order of these calls.

**Comment by aldo-expensify** [comment] 2024-06-11 19:38
I think I reproduced it in dev by adding a `sleep(10);` between those lines.

**Comment by aldo-expensify** [comment] 2024-06-11 19:47
Testing and preparing a PR...

**Comment by aldo-expensify** [comment] 2024-06-11 20:17
PR up: https://github.com/Expensify/Web-Expensify/pull/42336

**Comment by puneetlath** [comment] 2024-06-13 18:31
Looks like this has been merged and is a purely back-end fix, so gonna close this out.

**Closed by puneetlath** 2024-06-13 18:31 UTC
Labels: Reviewing, Engineering, Daily, Bug, retest-weekly
