### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250] Generate Workspace Avatar Color based on PolicyID instead of Workspace Name

### ISSUE THREAD

**Issue by grgia** [Expensify/App#39478] opened 2024-04-03 08:41 UTC
See https://expensify.slack.com/archives/C03TME82F/p1712094385071259

![image](https://github.com/Expensify/App/assets/38015950/c29c9ae4-bb74-4c93-ab57-81e963db2aa5)

Right now the workspace icon changes based on the name, but that means that the icon and colors will change every time you modify the name of your workspace, even slightly. For example `Expensify UK` versus `Expensify - UK`

Let's hash the policyID instead so the workspace avatar will always remain the same color and the SVG will only change if the first character is modified. For example `Expensify UK` (E) versus `New Expensify - UK` (N)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d4085169c8260375</li>
        <li>Upwork Job ID: 1775449679811973120</li>
        <li>Last Price Increase: 2024-04-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by nkdengineer** [comment] 2024-04-03 09:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In [here](https://github.com/Expensify/App/blob/398636a109452a6442d5e9fd0774f928ceaddee0/src/styles/utils/index.ts#L274), we're using the full workspace name, not just the first character

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/App/blob/398636a109452a6442d5e9fd0774f928ceaddee0/src/styles/utils/index.ts#L274), use just the first character of `workspaceName`

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-04-03 09:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want the workspace avatar color to be consistent based on first character of workspace name

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/398636a109452a6442d5e9fd0774f928ceaddee0/src/styles/utils/index.ts#L274), we're using the full workspace name, not just the first character

### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/App/blob/398636a109452a6442d5e9fd0774f928ceaddee0/src/styles/utils/index.ts#L274), use just the first character of `workspaceName` (similar to what we did with the `getDefaultWorkspaceAvatar` [here](https://github.com/Expensify/App/blob/398636a109452a6442d5e9fd0774f928ceaddee0/src/libs/ReportUtils.ts#L1558))
```
const colorHash = UserUtils.hashText(workspaceName[0].trim(), workspaceColorOptions.length);
```

We might want to normalize the `workspaceName` first (like [here](https://github.com/Expensify/App/blob/398636a109452a6442d5e9fd0774f928ceaddee0/src/libs/ReportUtils.ts#L1553)) before getting the first character

### What alternative solutions did you explore? (Optional)
We can use `PolicyID` for the hash, but it will not ensure changing workspace color when first character of workspace name is changed. To do this, we need to:
- Modify `getDefaultWorkspaceAvatarColor` [here](https://github.com/Expensify/App/blob/398636a109452a6442d5e9fd0774f928ceaddee0/src/styles/utils/index.ts#L274) to accept `workspaceID` instead of `workspaceName`, and use `workspaceID` for the hash
- In places that uses `getDefaultWorkspaceAvatarColor`, pass in `workspaceID` instead
If we go with this, we can optionally do the same for `getDefaultWorkspaceAvatar` too

**Comment by grgia** [comment] 2024-04-03 09:33
> We want the workspace avatar color to be consistent based on first character of workspace name
@nkdengineer 

The only change is that the workspace color will be based off the policyID. The Workspace SVG will still be based on the name

**Comment by grgia** [comment] 2024-04-03 09:35
I accidentally added a label and all of ^ was me trying to battle the autoassigner adding more labels 😂

**Comment by godofoutcasts94** [comment] 2024-04-03 09:56
updated [proposal](https://github.com/Expensify/App/issues/39478#issuecomment-2034081004) RCA

**Comment by nkdengineer** [comment] 2024-04-03 10:01
[Proposal updated](https://github.com/Expensify/App/issues/39478#issuecomment-2034020967) to add some minor explanations, solutions remained unchanged.

> The only change is that the workspace color will be based off the policyID. The Workspace SVG will still be based on the name

@grgia I had this in the alternative solution of [the proposal](https://github.com/Expensify/App/issues/39478#issuecomment-2034020967), I think we're good to go here 👍

**Comment by grgia** [comment] 2024-04-03 10:06
> but it will not ensure changing workspace color when first character of workspace name is changed. To do this, we need to:

@nkdengineer my bad, I've updated the description to be more specific

Let's hash the policyID instead so the workspace avatar will always remain the same color and **the SVG** will only change if the first character is modified. For example Expensify UK (E) versus New Expensify - UK (N)

The color will be consistent no matter what the name is

**Comment by rushatgabhane** [comment] 2024-04-03 10:25
@grgia 🎀👀🎀

https://github.com/Expensify/App/issues/39478#issuecomment-2034081004 @godofoutcasts94's proposal looks good.

**Comment by nkdengineer** [comment] 2024-04-03 10:50
@rushatgabhane The proposal from @godofoutcasts94 is a dupe of [my alternative solution](https://github.com/Expensify/App/issues/39478#issuecomment-2034020967), just checking if you've read my proposal?

Thank you!

cc @grgia

**Comment by rushatgabhane** [comment] 2024-04-03 11:46
> The selected proposal seems incomplete, so that's why I'm asking

@ShridharGoel i think that it's understood that we'll pass policyId instead of policy name to the function. Your proposal is good but I prefer @godofoutcasts94's proposal because they were first.

**Comment by nkdengineer** [comment] 2024-04-03 11:51
> We can use PolicyID for the hash, but it will not ensure changing workspace color when first character of workspace name is changed. To do this

@rushatgabhane This part is meant to say that the policyID approach will not ensure changing workspace color when first character of workspace name is changed. Which means the workspace color will remain constant as @grgia later confirmed [here](https://github.com/Expensify/App/issues/39478#issuecomment-2034142341).

That's because the OP at the time I posted my proposal is as follows
> Let's hash the policyID instead so the workspace avatar will always remain the same color and will only change if the first character is modified.

Which sounds like it's suggesting the color should change "if the first character is modified", that's why I add that sentence to highlight that the policyID approach will not have that behavior.

I think it's just a small misunderstanding between us. Based on the merits of the solution, do you agree @godofoutcasts94 's solution is identical to my alternative proposal?

**Comment by nkdengineer** [comment] 2024-04-03 11:57
@rushatgabhane  To put side-by-side

@godofoutcasts94 's solution:
> Instead of workspaceName we need to pass workspaceId for generating workspace avatar color based on policy id. Also, taken reference from this https://github.com/Expensify/App/issues/39478#issuecomment-2034046805

My alternative solution
> Modify getDefaultWorkspaceAvatarColor [here](https://github.com/Expensify/App/blob/398636a109452a6442d5e9fd0774f928ceaddee0/src/styles/utils/index.ts#L274) to accept workspaceID instead of workspaceName, and use workspaceID for the hash

(and some extra details on how to pass `workspaceID`)

**Comment by grgia** [comment] 2024-04-03 15:22
@nkdengineer in the future, please update your proposal to remove outdated suggestions. I noted what was incorrect with your proposal [here](https://github.com/Expensify/App/issues/39478#issuecomment-2034046805) and updated the issue description as it was confusing [here](https://github.com/Expensify/App/issues/39478#issuecomment-2034142341). 

That said, I pretty much wrote the solution design in the description as this isn't a bug but a modification to the feature. So I'm fine going with the first posted proposal. WDYT @rushatgabhane.

**Comment by nkdengineer** [comment] 2024-04-03 16:21
> @nkdengineer in the future, please update your proposal to remove outdated suggestions.

@grgia Noted on this, normally I saw proposal's alternative solution is also evaluated independently from the main solution, so I didn't update immediately after you updated the issue OP. 

[Proposal updated](https://github.com/Expensify/App/issues/39478#issuecomment-2034020967) to move alternative solution to main solution, and removed outdated suggestions

> So I'm fine going with the first posted proposal. WDYT @rushatgabhane.

@rushatgabhane Let us know what you think and we can move forward here 👍

**Comment by rushatgabhane** [comment] 2024-04-03 18:13
> So I'm fine going with the first posted proposal
@grgia sounds good

**Comment by godofoutcasts94** [comment] 2024-04-03 18:34
Since after your comment @grgia ! My proposal was the first after your comment, then why my proposal is not selected?

**Comment by nkdengineer** [comment] 2024-04-04 04:49
@godofoutcasts94 Your proposal is a dupe of [my proposal](https://github.com/Expensify/App/issues/39478#issuecomment-2034020967) (it's the alternative solution in my initial proposal)

**Comment by isabelastisser** [comment] 2024-05-08 21:54
@rushatgabhane, please complete the BZ list, and I will process the payments tomorrow. Thanks!

**Comment by isabelastisser** [comment] 2024-05-10 17:55
Bump @rushatgabhane for an update, thanks!

**Comment by rushatgabhane** [comment] 2024-05-13 09:23
This is a new feature, so we should add regression steps.

**Comment by shawnborton** [comment] 2024-05-13 18:57
I thought this PR introduced a bunch of regressions? Should we be paying out the bounty, or wait until all of the regressions are fixed? 

@grgia can you confirm please?

**Comment by shawnborton** [comment] 2024-05-13 19:09
Here's the link to the PR that should fix some of the regressions: https://github.com/Expensify/App/pull/41485

**Comment by grgia** [comment] 2024-05-17 11:49
@rushatgabhane @isabelastisser yes, it did introduce a handful of regressions. Would you please calculate payment with the regression penalty

**Comment by isabelastisser** [comment] 2024-05-17 19:14
Thanks, @grgia! Discussion[ here.](https://expensify.slack.com/archives/C01SKUP7QR0/p1715973163101069)

**Closed** 2024-05-20 15:24 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-31 03:50
$100 approved for @rushatgabhane
