### ISSUE TITLE
[HOLD for payment 2023-09-11] [$1000]  Request money - Address field shows error when saved again and it becomes empty after refresh

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25686] opened 2023-08-22 14:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify,com
2. Go to + > Request money > Distance
3. Click Start
4. Enter an address and save
5. Click on Start again
6. Click Save
7. Refresh the page

## Expected Result:
In Step 6, since the address is populated, user is able to save the selection
In Step 7. the address field remains populated

## Actual Result:
In Step 6, user is unable to save the selection and error 'Please select a suggested address' shows up
In Step 7. the address field is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5eae689d-8f67-4bea-af34-a8e154ae8e6e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012df4e765e5dc30c6</li>
        <li>Upwork Job ID: 1694412987696316416</li>
        <li>Last Price Increase: 2023-08-23</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Contributor | 26396416</li>
</ul></li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-08-22 15:27
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Request money - Address field shows error when saved again and it becomes empty after refresh(https://github.com/Expensify/App/issues/25686#top)### What is the root cause of that problem?

https://github.com/Expensify/App/blob/c053381c06587d2569247c6d546cf9bd69ceba97/src/pages/iou/WaypointEditor.js?#L87
change to  because when online waypointValue is empty only we need to throw the error
` if (!network.isOffline && waypointValue !== '') {`

for a refreshing time before update the defaultValue AddressSearch component is mounted so that the value is not updated we can use the state for update the value and  instead of `defaultValue` we can use value

**Comment by pradeepmdk** [comment] 2023-08-23 04:20
@hungvu193  I tried `shouldSaveDraft` but I think it  will create a regression 

https://github.com/Expensify/App/assets/16595846/5e34d659-add4-48ae-a96c-7a288b8f5479

**Comment by thienlnam** [comment] 2023-08-23 18:00
I authored this regression so I'll take it

**Comment by thienlnam** [comment] 2023-08-23 18:02
Oh, looking at the video this doesn't look like a blocker

**Comment by thienlnam** [comment] 2023-08-23 18:14
The current proposals won't fix the issue in a way that doesn't add another regression but yeah we can make this external

**Comment by Pujan92** [comment] 2023-08-23 19:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the waypoint editor address field shows error when saved without change and empties after refresh

### What is the root cause of that problem?

1) Currently, we are not allowing the same string to be saved if there isn't any change. We only can clear out the input and save but for non-empty string needs to be selected from the autocomplete options.

2) Seems the default value for iou `transactionID` in `WaypointEditorPage` makes the extra render which causes the waypointAddress defaultValue to be empty on the first render.

### What changes do you think we should make in order to solve the problem?

1) We need to allow user to save same string which they have chosen earlier via autocomplete option. For that we need to add 1 more condition here.
` && waypointAddress !== waypointValue`
https://github.com/Expensify/App/blob/8d5ae3a22a952677f8c48ce8a9c288f51a5eb8d0/src/pages/iou/WaypointEditor.js#L70

2) Seems the default value is not needed here for iou `transactionID` in `WaypointEditorPage` as that needs to be available when we create transaction in `DistanceRequestPage`. (Also we can redirect to the distance page when user tries to access waypoint screen directly if `transactionID` not available)
https://github.com/Expensify/App/blob/7bf9db50ef5968ed95a46988a43478c8226d0235/src/pages/iou/WaypointEditorPage.js#L50
`selector: (iou) => (iou && iou.transactionID)}`

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/14358475/da6e9b95-c1f0-42f8-b874-ebfba5ee3797

</details>

**Comment by napster125** [comment] 2023-08-28 06:59
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Request money - Address field shows error when saved again and it becomes empty after refresh.

### What is the root cause of that problem?
The problem has a couple of underlying causes.

First, there's an incorrect condition in place that triggers an error message when `waypointValue` isn't empty. This leads to the error being displayed upon saving again.

https://github.com/Expensify/App/blob/394860028c68d10727e4e829ffd0c3ff455ed97f/src/pages/iou/WaypointEditor.js#L70

Second, in the provided code snippet, if the `transactionID` is an empty string, the `WaypointEditor` component renders with an empty `transactionID`. Furthermore, the `WaypointEditor` renders the `AddressSearch` component with a `defaultValue` of an empty string.

https://github.com/Expensify/App/blob/394860028c68d10727e4e829ffd0c3ff455ed97f/src/pages/iou/WaypointEditorPage.js#L35-L51

However, when the Onyx store is fully loaded, the `transactionID` is not an empty string. As a result, the `WaypointEditor` and `AddressSearch` components are re-rendered, causing the `defaultValue` prop in `AddressSearch` to change. Unfortunately, this change doesn't update the value of `AddressSearch` because `defaultValue` doesn't affect the value.

![Screenshot 2023-08-28 010525](https://github.com/Expensify/App/assets/136437976/58c45db6-1c27-4bd0-8740-b7aa85cb38bc)

### What changes do you think we should make in order to solve the problem?
To address this issue, I suggest modifying the following code:

https://github.com/Expensify/App/blob/394860028c68d10727e4e829ffd0c3ff455ed97f/src/pages/iou/WaypointEditor.js#L70

We need to change the condition to one of the following:
```
if (!network.isOffline && _.isEmpty(waypointValue)) {
```
or
```
if (!network.isOffline && waypointValue === '') {
```

https://github.com/Expensify/App/blob/394860028c68d10727e4e829ffd0c3ff455ed97f/src/pages/iou/WaypointEditorPage.js#L36-L41

Also we should modify the code as follows:
```
return !_.isEmpty(transactionID) ? (
  <WaypointEditor
    transactionID={transactionID}
    route={route}
  />
) : null;
```
#### Result:
https://github.com/Expensify/App/assets/136437976/ea854dd8-26f1-4ab6-8a2c-7689faa9f1c6



### What alternative solutions did you explore? (Optional)
Another approach we could consider involves using the `value` and `onValueChange` props in the `AddressSearch` component.

**Comment by napster125** [comment] 2023-08-28 07:16
@allroundexperts, @thienlnam 
Could you kindly review my proposal? I believe we can resolve this issue by utilizing the `value` and `onValueChange` attributes. However, in my opinion, my proposed solution offers greater consistency and requires fewer modifications.
Your feedback on this matter would be greatly appreciated.

**Comment by thienlnam** [comment] 2023-08-29 18:11
Assigning @Pujan92 - they addressed the requirements first

**Comment by Pujan92** [comment] 2023-08-31 08:58
@allroundexperts [PR](https://github.com/Expensify/App/pull/26371) is ready for review!

**Comment by zanyrenney** [comment] 2023-09-13 09:58
**Payment summary**

 External issue reporter - N/A (reported by Applause internal team)
 Contributor that fixed the issue (paid @Pujan92 $1500 for work + urgency bonus)
 Contributor+ that helped on the issue and/or PR (paid with manual requests) @allroundexperts please request payment outside this! Thanks!

**Comment by zanyrenney** [comment] 2023-09-13 09:58
Closing now upwork payment is complete!

**Closed by zanyrenney** 2023-09-13 09:58 UTC
Labels: External, Engineering, Daily, Awaiting Payment
