### ISSUE TITLE
mWeb - chat - On starting conversation with phone contact, +91 is added as seperate contact

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47790] opened 2024-08-21 13:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4879523
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login with new account
3. Tap fab -- start chat
4. Scroll and check +91 contact not in contact list
5. Enter a photo number eg:+919878675687
6. Start chat with that user and send a message
7. Navigate to LHN
8. Tap fab - start chat
9. Now note in recents you can see number eg: 09878675687 and scroll the user list and note +91 is added as seperate contact.

## Expected Result:
On starting conversation with phone contact, +91 must not be added as seperate contact

## Actual Result:
On starting conversation with phone contact, +91 is added as seperate contact.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d69a60c8-abea-4941-b90a-d45efabe5053

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-21 13:45
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-21 13:45
We think that this bug might be related to #vip-vsp

**Comment by NJ-2020** [comment] 2024-08-22 07:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On starting conversation with phone contact, +91 is added as seperate contact
### What is the root cause of that problem?
When we type +91 we request search to the BE and the BE response and return a contact personal detail info with +91 only
![Screenshot 2024-08-21 at 22 59 11](https://github.com/user-attachments/assets/864ea0cc-729c-490f-93a9-728f36360e59)
And the response from the BE will apply the Onyx changes which will create a new +91 contact number 
### What changes do you think we should make in order to solve the problem?
in the contact section we can exclude if the contact response is from BE, we can use the `isFromServerSearch` property to determine if the personal detail is from BE 

And we will show only if we click the contact meaning we start conversation with the contact, because the new personal detail contact info is not from server search
### What alternative solutions did you explore? (Optional)

**Comment by kavimuru** [comment] 2024-08-27 15:05
Bug is fixed. 

https://github.com/user-attachments/assets/20ca3138-bc31-4de5-b6f7-61056df04d2c

**Comment by miljakljajic** [comment] 2024-08-27 15:06
Closing!

**Closed by miljakljajic** 2024-08-27 15:06 UTC
Labels: Daily, Bug
