### ISSUE TITLE
[$500] Web - Settings - Unable to log out after being redirected to ND from OD by clicking on workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33731] opened 2023-12-29 00:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out of ND
2. Log into OD with an account that has an existing workspace without a bank account
3. Click on "Continue setup" in the inbox task or Settings> Workspace > User's workspace
4. After being redirected to ND, click on the avatar and sign out

## Expected Result:
User is logged out and the home screen is displayed

## Actual Result:
The page refreshes and the user is still logged in

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e5cde966-c16e-4e16-8e2b-c61991efbe8f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152728ca06936b7d2</li>
        <li>Upwork Job ID: 1740527564973801472</li>
        <li>Last Price Increase: 2024-01-19</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 28119678</li>
<li>aswin-s | Contributor | 28119680</li>
</ul></li>
    </ul>
</details>

**Comment by aswin-s** [comment] 2023-12-29 08:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

User is not getting signed out after being redirected to ND from OD

### What is the root cause of that problem?

We are using a transition url with shortLivedAuthToken to redirect from oldDot to newDot. We are using `exitTo` param for navigating to a screen immediately after signIn. The transition url route is mapped to `loadLogOutPreviousUserPage`. 

https://github.com/Expensify/App/blob/5c5c862a10b75214899da32333a7f3a694e38be3/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L268-L272

The`LogOutPreviousUserPage` has an effect which handles the `exitTo` param in transition url. Note that we are directly navigating to exitTo route from transition route.

https://github.com/Expensify/App/blob/5c5c862a10b75214899da32333a7f3a694e38be3/src/pages/LogOutPreviousUserPage.js#L57-L65

When user closes the `Connect Bank Account` modal, screen goes back to the transition URL. So if user tries to signout at this point, the page reloads with transition url which will again invoke `signInWithShortLived` access token which inturn will sign the user back in. 


### What changes do you think we should make in order to solve the problem?

We should reset the transition route before navigating to exitTo route in `LogOutPreviousUserPage` . This prevents the screen from going back to transition route on closing the modal.

```tsx
if (exitTo && exitTo !== ROUTES.WORKSPACE_NEW && !props.account.isLoading && !isLoggingInAsNewUser) {
    Navigation.isNavigationReady().then(() => {
      Navigation.goBack(ROUTES.HOME);
      Navigation.navigate(exitTo);
  });
}
```

### What alternative solutions did you explore? (Optional)
None (edited)

**Comment by MitchExpensify** [comment] 2023-12-31 01:00
Expected right now

**Comment by aswin-s** [comment] 2024-01-02 07:20
@MitchExpensify As explained in the proposal above this seems to be a bug on client side which re-authenticates the user using the short lived auth token just because we are not clearing the used transition url. This bug will also cause below screen to be shown when user tries to signout when the short lived token has expired. Both of these results are not as per expectation.

![image](https://github.com/Expensify/App/assets/6880914/83c2bb2e-ccc9-4c77-a340-f5cd9b2de0e0)

Could you please shed some light on why this is the expected behaviour at the moment or point to a discussion where this is discussed in detail?

**Comment by MitchExpensify** [comment] 2024-01-04 21:03
I initially misunderstood the issue, I think this fits into Wave 9 because its related to the redirect introduced in that wave

**Comment by MitchExpensify** [comment] 2024-01-08 23:41
@abdulrahuman5196 Do you think this looks like it will need to be handled internally?

**Comment by abdulrahuman5196** [comment] 2024-01-11 15:53
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-01-11 16:05
@aswin-s I am unable to fully understand your proposal. I assume you are saying we using the same exitTo url during transition and during logout as well, which is causing the user to re-signin. 
And in the change mentioned, you are just routing to home before navigating to exitTo which seems to be a workaround IMO.

**Comment by aswin-s** [comment] 2024-01-11 16:46
Let me elaborate the series of events once again

1. User logs into old dot, taps on the "Continue setup" for bank account button
2. Gets redirected to Newdot with a url of the pattern

https://staging.new.expensify.com/transition?accountId=123&email&user%40gmail.com&shortLivedAccessToken=1234&exitTo=bank-account%2Fnew%3FpolicyID%3D72D1

3. Note that the route being used is /transition
4. On NewDot '/transion' route is being handled by `LogInWithShortLivedAuthTokenPage` & `loadLogOutPreviousUserPage` components. It logsOut previous user and signins in again using the short lived token in the Url. This is a regular GET url and could pasted any time within the validity of shortAuthToken to signOut current user and login again.
5. After signin there is an effect in `loadLogOutPreviousUserPage` which basically redirects the user to the exitRoute. In this case it is `/bank-account/new`. This is a drawer page that opens on top of ReportActionScreen.
6. So navigation route changes from /transition to /bank-account
7. At this point user cancels the action and signs out 
8. SignOut action closes the drawer and goes back in history, which takes user back to transition url
9. Page gets reloaded using the transition url which triggers a re-login

If you see above steps it is quite evident that the transition should have been from /transition -> /r/reportId (Home) -> /bank-account. The reason user goes back to transition url is because the home route is not set before navigating directly to a drawer screen. Thats the reason why user needs to navigate to ROUTES.HOME before navigating to an exitRoute. This could further be verified by simply closing the modal and checking the url in address bar.


https://github.com/Expensify/App/assets/6880914/7d8648f4-c228-4005-a339-a92aec23a466



Let me know if you have any further questions.

**Comment by MitchExpensify** [comment] 2024-01-13 21:02
Next step here is for @abdulrahuman5196 to review @aswin-s 's resopnse

**Comment by aswin-s** [comment] 2024-01-18 22:50
@abdulrahuman5196 Any feedback on [above comment](https://github.com/Expensify/App/issues/33731#issuecomment-1887559200)?

**Comment by abdulrahuman5196** [comment] 2024-01-19 14:30
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-01-22 10:39
REviewing now. thanks for the detailed explanation.

**Comment by abdulrahuman5196** [comment] 2024-01-22 11:09
The proposal here https://github.com/Expensify/App/issues/33731#issuecomment-1871852199 and extended explanation here https://github.com/Expensify/App/issues/33731#issuecomment-1887559200 seems reasonable. But still wondering about routing to home and then routing to bank page.

@MitchExpensify  Could you kindly involve internal engineer worked on Authentication and Session to double confirm, `If the the thought process of the proposal is fine or is the transition url expected to behave someway different in this case requiring a different fix?`

**Comment by MitchExpensify** [comment] 2024-01-23 02:10
> Could you kindly involve internal engineer worked on Authentication and Session to double confirm, If the the thought process of the proposal is fine or is the transition url expected to behave someway different in this case requiring a different fix?

This seems like a good question for @marcaaron or @cead22

**Comment by cead22** [comment] 2024-01-23 15:27
The proposal looks good to me, and it's the only one we have for now that makes this work the way it should. 

I understand navigating to home feels like a workaround, and if we have a way to set the home route or to remove the transition page from the navigation stack without navigating to home, those could be good fixes too. If we don't have a way to do either or no other way to accomplish this, then navigating to home is better than the bug, so I think we can go with the proposal and add a comment above `Navigation.goBack(ROUTES.HOME);` to explain why we're doing that

**Comment by abdulrahuman5196** [comment] 2024-01-23 18:35
Thank you for the confirmation @cead22 .

@aswin-s 's proposal here https://github.com/Expensify/App/issues/33731#issuecomment-1871852199 looks good and works well. @aswin-s Kindly update your proposal as well on the new discussions. Would be helpful for future reference.

🎀 👀 🎀
C+ Reviewed

**Comment by aswin-s** [comment] 2024-01-24 11:40
@abdulrahuman5196 [Updated my proposal](https://github.com/Expensify/App/issues/33731#issuecomment-1871852199) with additional details

**Comment by aswin-s** [comment] 2024-01-26 03:54
@MariaHCD @abdulrahuman5196 I'm unable to reproduce this issue anymore. Looks like it got [fixed over here](https://github.com/Expensify/App/pull/34305).

**Comment by MitchExpensify** [comment] 2024-01-28 02:08
Oh nice catch, I'll defer to @MariaHCD or @abdulrahuman5196 to confirm before closing or not

**Comment by abdulrahuman5196** [comment] 2024-01-28 18:20
Yes. I don't see this issue anymore.

**Comment by MariaHCD** [comment] 2024-01-29 07:43
Nice, since this is no longer reproducible, I'd agree with closing this out.

**Closed** 2024-01-30 19:53 UTC
Labels: External, Engineering, Daily, Bug
