### ISSUE TITLE
[HOLD for payment 2024-06-05] [$250] iOS - Expense - Chat header appears after delay when opening expense report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41523] opened 2024-05-02 17:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Submit two expenses to a user with no chat history
3. In 1:1 DM, tap on the expense preview

## Expected Result:
Expense report header will appear instantly

## Actual Result:
The report content is displayed first, then followed by the chat header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/eef5e978-b8ae-48af-a5a9-0dcda4f7cd32

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011fdda098a71985a0</li>
        <li>Upwork Job ID: 1786406953110065152</li>
        <li>Last Price Increase: 2024-05-10</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by lanitochka17** [comment] 2024-05-02 17:58
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-02 17:58
We think that this bug might be related to #vip-vsp

**Comment by puneetlath** [comment] 2024-05-02 20:33
I'm not able to reproduce this on my iOS app.

**Comment by francoisl** [comment] 2024-05-03 05:01
Can't repro either with Browserstack. I get a "Review required" violation on each expense, but that's unrelated, and violations are still in beta.

**Comment by puneetlath** [comment] 2024-05-07 16:42
@DylanDylann thoughts on the proposal above?

**Comment by DylanDylann** [comment] 2024-05-08 10:19
@bernhardoj Your proposal looks promising. Could you provide a draft branch?

**Comment by bernhardoj** [comment] 2024-05-10 06:00
@DylanDylann here is the [test branch](https://github.com/bernhardoj/Expensify/tree/fix/41523-chat-header-show-with-delay)

**Comment by bernhardoj** [comment] 2024-05-13 12:33
Correct, so I used the useOnyx hook which doesn't have that bug.

**Comment by mvtglobally** [comment] 2024-05-13 14:19
Issue not reproducible during KI retests. (First week)

**Comment by DylanDylann** [comment] 2024-05-14 10:30
@bernhardoj Could your reproduce this issue anymore?

**Comment by DylanDylann** [comment] 2024-05-15 07:58
@bernhardoj Yeah, a bit delay in MoneyReportHeader. But I don't see delay in MoneyRequestHeader. Could you help to confirm that?

**Comment by bernhardoj** [comment] 2024-05-15 08:00
You can see the MoneyRequestHeader delay in 0:09 after the header skeleton disappears

**Comment by DylanDylann** [comment] 2024-05-15 08:02
Oh see, a very small delay

**Comment by DylanDylann** [comment] 2024-05-15 08:06
Your proposal works well but gives me a time to dive deep into useOnyx to understand why it resolves this problem

**Comment by bernhardoj** [comment] 2024-05-15 12:16
> and if the data is not available yet, withOnyx will return null. 

The important point of the issue is this. [code ref](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/withOnyx.js#L316-L319)

if we move from withOnyx HOC to useOnyx hook, then we won't have this problem.

**Comment by DylanDylann** [comment] 2024-05-16 04:15
@bernhardoj I have a bit curious
1. If the data is not available, what does useOnyx return?

2. why the header is delayed when the data is not available?

**Comment by bernhardoj** [comment] 2024-05-16 04:38
> If the data is not available, what does useOnyx return?

It's null from my testing

> why the header is delayed when the data is not available?

> and if the data is not available yet, withOnyx will return null.

**Comment by DylanDylann** [comment] 2024-05-16 04:46
You mean if data isn't available both withOnyx and useOnyx return null ????

**Comment by bernhardoj** [comment] 2024-05-16 04:47
Yes

**Comment by DylanDylann** [comment] 2024-05-16 04:47
> why the header is delayed when the data is not available?

I want to ask why when the data is null, the header is delay

**Comment by DylanDylann** [comment] 2024-05-16 04:49
> if we move from withOnyx HOC to useOnyx hook, then we won't have this problem.

Could you help to detail your point? Why useOnyx will resolve this bug?

**Comment by bernhardoj** [comment] 2024-05-16 04:49
When you render null, you see nothing. Please check the ref I put in my comment [here](https://github.com/Expensify/App/issues/41523#issuecomment-2112371236)

**Comment by DylanDylann** [comment] 2024-05-16 08:20
> When you render null

which null? You mean the nextStep?

**Comment by bernhardoj** [comment] 2024-05-16 08:23
This null 🙂 

<img width="758" alt="image" src="https://github.com/Expensify/App/assets/50919443/07b38220-a7de-4fd3-ae3d-5f5cbca27403">

**Comment by DylanDylann** [comment] 2024-05-16 08:37
Oh see, I got misunderstand your mean

**Comment by DylanDylann** [comment] 2024-05-16 08:37
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/41523#issuecomment-2092814191) looks good. I agree with using useOnyx instead of withOnyx 
🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-05-17 05:39
PR is ready

cc: @DylanDylann

**Comment by puneetlath** [comment] 2024-06-05 13:56
@DylanDylann bump on the checklist!

**Comment by DylanDylann** [comment] 2024-06-05 17:39
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal

1. (Web/Desktop/mWeb) Refresh the app (iOS/Android) Close the app and reopen the app
2. Verify the header/top bar of the home page/LHN is shown immediately


Do we agree 👍 or 👎

**Comment by DylanDylann** [comment] 2024-06-05 17:40
@puneetlath thanks for your reminder

**Comment by puneetlath** [comment] 2024-06-10 16:15
All paid. Thanks everyone!

**Closed by puneetlath** 2024-06-10 16:15 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment
