### ISSUE TITLE
MEDIUM: [$500] After leaving a workspace room, the room is still in the chat view after closing the Concierge chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33521] opened 2023-12-22 19:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcochavezf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703192168381059

## Action Performed:
1. Log in as account A and create a workspace
2. Create a room in the workspace with welcome message and visibility as "Workspace"
3. Invite account B as a member of the workspace created in step 1
4. Invite the same email/phone number to the workspace room by either mentioning them in the room or in the member list
5. In a mobile device log in with the invited account
6. Open the workspace room
7. Click/tap on the three dots menu
8. Select the option Leave
and the workspace room will be still there

## Expected Result:
You will see the Concierge chat and when you close it, you should not see the workspace room

## Actual Result:
 If you close it and the workspace room will be still there

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/fcf249f1-6217-41cb-9948-9d070eb3d5a8

https://github.com/Expensify/App/assets/38435837/810fb46b-d71b-4cb7-bf2e-4393b4192e5a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ad515ee3bf6c0e8</li>
        <li>Upwork Job ID: 1738283285298159616</li>
        <li>Last Price Increase: 2023-12-22</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28071460</li>
<li>dukenv0307 | Contributor | 28071461</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-12-22 19:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After leaving a workspace room, the room is still in the chat view after closing the Concierge chat

### What is the root cause of that problem?
Currently we are navigating to concierge chat when we leave room here 
https://github.com/Expensify/App/blob/862b0eac87e969e3c15d2ccde165600a6e40e8fb/src/libs/actions/Report.ts#L2110-L2115
but the route for the room is still in navigation state so when we navigate back it will navigate to it
### What changes do you think we should make in order to solve the problem?

We need to delete the room route from the navigation state route 
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2023-12-25 11:59
BTW did u guys **reproduce** the issue? I Couldn't!!

**Comment by isabelastisser** [comment] 2024-01-19 15:36
@dukenv0307 @hoangzinh any updates here?

**Comment by quinthar** [comment] 2024-01-22 00:41
Has this been paid?  Can we close this issue?

**Comment by isabelastisser** [comment] 2024-01-22 00:56
Payment summary:

@dukenv0307 Contributor $500 paid in Upwork.
@hoangzinh C+ $500 offer sent in Upwork. Please accept it, and I will process the payment. Thanks!

**Closed by isabelastisser** 2024-01-22 00:56 UTC
Labels: Reviewing, External, Weekly, Bug
