### ISSUE TITLE
[$250] Web - Deleting a message/comment in report shows New messages floating indicator even if no new message in the report - Reported by @aneequeahmad 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#12710] opened 2022-11-14 16:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch web app.
2. Click on any report having list of comments/messages in LHN
3. Hover on any comment/message and click on delete comment/message icon.
4. Click on delete in Delete comment modal.
5. Scroll to top.

## Expected Result:
Shouldn't see New message floating indicator.

## Actual Result:
New message floating indicator is shown

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.22-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/201708226-2f4bfc97-f091-428e-ba8e-43b543dfb116.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668232657153179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment] 2022-11-14 16:18
I am able to reproduce. I am assigning out to an external contributor.

**Comment by Santhosh-Sellavel** [comment] 2022-11-14 16:21
Definitely Looks like a regression!

**Comment by davidcardoza** [comment] 2022-11-14 17:32
I was able to reproduce. Job posted - https://www.upwork.com/jobs/~015eb0ac1a09b42c84

**Comment by Santhosh-Sellavel** [comment] 2022-11-15 00:57
@marcaaron this might be related to the New Indicator PR can you confirm, thanks!

**Comment by marcaaron** [comment] 2022-11-15 01:01
@Santhosh-Sellavel Sorry, I can't determine if it's related. But if you see a clear link I will try to assist however I can.

**Comment by marcaaron** [comment] 2022-11-15 01:04
I want to say this is a known issue and has never really worked correctly. There are a lot of small edge cases related to deleting chat messages that proved to be difficult to solve when we moved to the new style API.

**Comment by Santhosh-Sellavel** [comment] 2022-11-17 14:19
Not overdue, looking for proposals!

**Comment by davidcardoza** [comment] 2022-11-18 01:08
@marcaaron should I raise the pay to $500?

**Comment by Santhosh-Sellavel** [comment] 2022-11-21 14:44
Not overdue, still looking for proposals!

**Comment by alex-mechler** [comment] 2022-11-21 19:04
I'm no longer able to reproduce this on dev or staging.  @mvtglobally or @davidcardoza are you able to reproduce this? 

https://user-images.githubusercontent.com/22447860/203138212-0cc9036a-99ab-440c-8ffd-9e57ae973ddf.mp4

**Comment by davidcardoza** [comment] 2022-11-21 20:58
Ya, I can't seem to reproduce either after several attempts. Should I close this issue?

**Comment by alex-mechler** [comment] 2022-11-21 23:33
Lets close this out. If QA can reproduce, we can reopen it then

**Closed by alex-mechler** 2022-11-21 23:33 UTC
Labels: External, Daily, Help Wanted, Bug
