### ISSUE TITLE
Web - Connect Bank Account - When disconnecting the bank account - it directed to Plaid option instead of Connect bank account page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11109] opened 2022-09-19 16:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go Setting - Workspace - Connect Bank Account
4. Use Plaid option
5 Select "Fidelity" bank option
6. Use all information to connect bank account
7. Tap Disconnect button
8. Select Delete

## Expected Result:
When disconnecting the bank account - it directed to Connect bank account page

## Actual Result:
When disconnecting the bank account - it directed to Plaid option instead of Connect bank account page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.2.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191062148-b0fdcb72-aaa7-4fd4-a0ca-d3fd7c7fac11.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment] 2022-09-22 19:48
I was able to reproduce this. Working on figuring out what causes this.

**Comment by mvtglobally** [comment] 2022-10-03 20:22
Issue not reproducible during KI retests. (First week)

**Comment by youssef-lr** [comment] 2022-10-04 09:00
Will test this again today.

**Comment by strepanier03** [comment] 2022-10-14 18:42
@youssef-lr - Just checking in on this, what are the next steps here to help move this forward? Are you at the testing phase still? Or is this something that can be closed because we can't reproduce?

**Comment by youssef-lr** [comment] 2022-10-17 22:47
I could not reproduce this one again. Will close this out.

**Closed by youssef-lr** 2022-10-17 22:47 UTC
Labels: Engineering, Weekly, Overdue
