### ISSUE TITLE
[HOLD for payment 2024-04-05] [Wave Collect] [Ideal Nav] Issues with the bold (unread) status on Workspace Item

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35682] opened 2024-02-02 17:33 UTC
## Action Performed:

The workspace item on the Workspace Switcher should be bold when there are any unread chat/report in that workspace. This indicator, however, isn't working consistently.

Sometimes, the workspace item is bold even when there is no unread chat in that workspace. And sometimes, it's not bold when there is a unread chat/report.

The following is the reproduction step for the latter issue.

1. Create a workspace if you don't have one yet.
2. Go to a workspace (not Expensify one).
3. Right click (or long press) a chat and click `Mark as unread` on the popover that appears
4. Click the Workspace Switcher.
5. Look for the current workspace name. Confirm that the workspace name is bold.
6. Go back to the workspace.
7. Right click the same chat and click `Mark as read`
8. Go back to Workspace Switcher
9. Confirm the current workspace is not bold

https://github.com/Expensify/App/assets/98560306/bb189b08-1d8a-4e97-9215-f7ad861808a8

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Vides are attached above.

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183bc22eb2779a4b0</li>
        <li>Upwork Job ID: 1763580448153239552</li>
        <li>Last Price Increase: 2024-03-01</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment] 2024-02-02 17:41
@mateuuszzzzz I believe you're working on this regression? can you comment on this GH issue so that I can assign you?

**Comment by Christinadobrzyn** [comment] 2024-02-02 22:39
Ah good catch! I can reproduce this - we'll see if @mateuuszzzzz is working on this!

**Comment by cdOut** [comment] 2024-02-05 10:40
Hello, I'll be working on this one.

**Comment by trjExpensify** [comment] 2024-02-05 10:42
Nice, assigned you @cdOut!

**Comment by ikevin127** [comment] 2024-02-05 14:24
While debugging a similar issue (https://github.com/Expensify/App/issues/35766) which was closed as a dupe of this one I noticed the following:
- within the `ReportUtils.isUnread` function we're checking the `lastReadTime` which if undefined will fallback to empty string
- in WorkspacesSettingsUtils we're using Onyx.connect to get `allReports`
- sometimes for certain workspaces -> reports within that workspace will initially have the `lastReadTime` as undefined
- undefined lastReadTime defaults to empty string which when compared to an existing `lastVisibleActionCreated` date string, isUnread always returns true

Considering these, I tend to think that the RC here might come from the Onyx.connect -> allReports data which might first initialize some report variables as undefined - while shortly after to become defined but the function doesn't register the data change and remains with initial isUnread status.

Hope this helps w/ debugging ✌️

**Comment by cdOut** [comment] 2024-02-05 14:37
Interesting, thanks for sharing the info @ikevin127!

**Comment by Christinadobrzyn** [comment] 2024-02-06 19:09
update - we're working on debugging/PR for this!

**Comment by situchan** [comment] 2024-02-06 19:23
I am interested in reviewing this since I was C+ in [dupe issue](https://github.com/Expensify/App/issues/35766)

**Comment by Christinadobrzyn** [comment] 2024-02-06 20:47
hey just a quick question here... testing this again and talking over this issue with @cdOut... I'm not sure if the steps in the OP are correct or are the issue we're trying to fix. 

What I see when testing: 

1. Create a workspace if you don't have one yet.
2. Go to a workspace (not Expensify one).
3. Right click (or long press) a chat and click `Mark as unread` on the popover that appears
4. Click the Workspace Switcher.
5. **Verify** that the workspace is bold and there is no green dot next to it
6. Go back to the workspace and right click (or long press) to `mark as read`
7. **Verify** that the workspace is not bold and there is no green dot next to it


https://github.com/Expensify/App/assets/51066321/3aa046e6-0c70-4f70-bc09-86898a924bbb


I don't think the checkmark matters here, the checkmark is the default workspace, yeah?

So isn't this behaviour correct? @hayata-suenaga @trjExpensify @situchan

**Comment by hayata-suenaga** [comment] 2024-02-06 21:29
@Christinadobrzyn I'm sorry. I mistyped the step #6. You're correct. We want to check if the workspace name is bold or not.

There is another issue that is handling RBR and GBR.

**Comment by Christinadobrzyn** [comment] 2024-02-06 21:41
Ah okay, thanks @hayata-suenaga so if that's the case, I think this might be fixed? Could you test again and let me know if the bold isn't working? TY! Or I can ask QA to test again if needed!

**Comment by trjExpensify** [comment] 2024-02-06 23:06
I still seem to have a phantom unread workspace on `v1.4.37-2`: 

<img width="1195" alt="image" src="https://github.com/Expensify/App/assets/16232057/10ddf42c-2deb-403c-8f09-7c5d7c744cf8">

I've clicked into all of the chats on that workspace and can't seem to clear it.

**Comment by cdOut** [comment] 2024-02-07 01:04
> I still seem to have a phantom unread workspace on `v1.4.37-2`:
> <img alt="image" width="1195" src="https://private-user-images.githubusercontent.com/16232057/302801674-10ddf42c-2deb-403c-8f09-7c5d7c744cf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNjgwOTgsIm5iZiI6MTcwNzI2Nzc5OCwicGF0aCI6Ii8xNjIzMjA1Ny8zMDI4MDE2NzQtMTBkZGY0MmMtMmRlYi00MDNjLThmMDktN2M1ZDdjNzQ0Y2Y4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDAxMDMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NWI1NTBiOWY1NGZjZjIyN2JiNWQzMjJkYWE5OTQ2NWM3ZjI2YTg5M2IwZjNiNDRjODMyYzM0YzNmNjgyMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qndt2QLDxHk96Hrtx0csDBoIU60pu4nb-bvO7p8Y5hQ">
> 
> I've clicked into all of the chats on that workspace and can't seem to clear it.

That's exactly the problem that I was also able to replicate and was working on a fix on this, just wanted to clarify that that's the only issue appearing currently with bold.
Thanks for retesting and specifying the issue!

**Comment by trjExpensify** [comment] 2024-02-07 01:12
Dopeeee! Any idea what it is? 🕵️

**Comment by cdOut** [comment] 2024-02-08 12:21
The issue appears to be occuring on old accounts which already had different reports created but due to updates to different flows they were hidden from the users view without ever gaining the `lastReadTime` property, which we use to determine whether we should use bold for the workspaces in the switcher.

I do have an old account that has a hidden report in the `Everything` section of the switcher, but I'd appreciate if I could log into the account you used for the video @trjExpensify with a hidden report in a user created workspace so I can test that case also. I've messaged you on slack about it.

**Comment by trjExpensify** [comment] 2024-02-08 17:46
Chatted about this earlier. I can't provide access to my real Expensify account where this is shown in the vid. I'll test an adhoc build though when ready!

**Comment by cdOut** [comment] 2024-02-12 13:19
As an update I will be creating a PR for this today.

**Comment by trjExpensify** [comment] 2024-02-12 15:35
Wahoo, nice! 👍

**Comment by Christinadobrzyn** [comment] 2024-02-14 00:10
Awesome! Thanks @cdOut! Let us know if you need anything for the PR

**Comment by hayata-suenaga** [comment] 2024-02-14 16:39
@cdOut let us know once you open a PR 🙇

**Comment by cdOut** [comment] 2024-02-15 19:15
I am still working on fixing this issue, I'm currently revising what reports are shown to the user on the LHP so I can properly display the unread reports, which after testing different scenarios I found out are still available reports that the user can manually go to but they do not appear properly on the list.

**Comment by hayata-suenaga** [comment] 2024-02-16 16:45
> which after testing different scenarios I found out are still available reports that the user can manually go to but they do not appear properly on the list.

hi @cdOut, I'm having a bit of trouble understanding the sentence above. Would you mind clarifying it for me? Thanks!

**Comment by hayata-suenaga** [comment] 2024-02-19 18:11
@cdOut, could you report on the progress of this when you have time? 🙇

**Comment by cdOut** [comment] 2024-02-22 08:42
I was OOO due to a fever these past days, I'll get back on this issue today and write up a follow up with progress for you later today.

**Comment by hayata-suenaga** [comment] 2024-02-22 15:36
thank you for the update and I hope you recovered fully 🍀

**Comment by hayata-suenaga** [comment] 2024-02-23 15:15
melvin, @cdOut is going to provide an update later once they recover.

**Comment by Christinadobrzyn** [comment] 2024-02-28 01:29
Thanks for the update @cdOut!

**Comment by cdOut** [comment] 2024-03-01 18:21
As an update, I've worked out a fix and will be testing it on different accounts, draft PR will be up today or tomorrow and we'll prioritize pushing it on main asap.

**Comment by hayata-suenaga** [comment] 2024-03-01 18:22
thank you for the update @cdOut

**Comment by cdOut** [comment] 2024-03-04 11:42
@trjExpensify I've created a PR for it with a fix that is fairly simple and works for all of my accounts, could you please also check it on the one you have with the phantom unread workspace?

**Comment by trjExpensify** [comment] 2024-03-04 12:18
Nice, do you have an adhoc build PR for me to look at?

**Comment by cdOut** [comment] 2024-03-04 12:32
@trjExpensify you could use the branch mentioned in the [pinned PR](https://github.com/Expensify/App/pull/37672) for this thread.

**Comment by hayata-suenaga** [comment] 2024-03-04 19:01
@trjExpensify -> https://github.com/Expensify/App/pull/37672#issuecomment-1977260384

**Comment by trjExpensify** [comment] 2024-03-04 22:40
Commented in the PR, but wahoo! The workspace isn't bold anymore: 

<img width="372" alt="image" src="https://github.com/Expensify/App/assets/16232057/34f992d8-61b5-4861-9925-539ca57b3367">

(See [here](https://github.com/Expensify/App/issues/35682#issuecomment-1930919335) for when it was).

**Comment by cdOut** [comment] 2024-03-04 22:44
Awesome! Thank you for testing it with your account.

**Comment by Christinadobrzyn** [comment] 2024-03-07 06:18
Just checking @cdOut are we adjusting something based on Tom's testing?

**Comment by cdOut** [comment] 2024-03-07 06:58
No, I just asked Tom to test this fix on his account since I knew he was affected with this very specific issue. I don't have to make any more adjustments, we're currently just waiting for a PR review to merge this one.

**Comment by hayata-suenaga** [comment] 2024-03-07 17:23
we're waiting for @situchan's review

**Comment by Christinadobrzyn** [comment] 2024-03-25 08:45
Just checking on an update @situchan. thanks!

**Comment by situchan** [comment] 2024-03-25 08:47
I approved PR. I raised a few unrelated concerns which can be out of scope.
We can merge as is if @hayata-suenaga agrees.

**Comment by cdOut** [comment] 2024-03-25 10:09
@situchan I've added a comment in the PR, could you please take a look at it?

**Comment by situchan** [comment] 2024-03-25 14:54
> @situchan I've added a comment in the PR, could you please take a look at it?

yes, checked already

**Comment by hayata-suenaga** [comment] 2024-03-25 20:27
approved 🎉 thank you for the work cdOut and situchan!

**Comment by Christinadobrzyn** [comment] 2024-04-04 08:20
Payouts due:

- [ ] Contributor+: $500 @situchan - are you paid through Upwork? or NewDot? 

Looks like the upwork job is closed so I can create a new one if needed. 

Do we need a regression test for this?

**Comment by hayata-suenaga** [comment] 2024-04-04 17:43
@situchan, I feel like we need a regression test for this one. What do you think?

**Comment by Christinadobrzyn** [comment] 2024-04-08 04:00
I think @situchan might be ooo based on Slack. 

@situchan can you accept this Upwork offer - https://www.upwork.com/nx/wm/offer/101773908

Can you also provide a regression test for us? Thanks!

**Comment by Christinadobrzyn** [comment] 2024-04-11 02:50
nudging @situchan in slack about [the offer](https://github.com/Expensify/App/issues/35682#issuecomment-2041818610)

**Comment by hayata-suenaga** [comment] 2024-04-11 17:09
@Christinadobrzyn I heard that @situchan is OOO for a while. I think we might have to wait a little bit until they come back 😄

**Comment by Christinadobrzyn** [comment] 2024-04-12 03:06
Ah okay! I'll move this to weekly since payment due is all that's left.

**Comment by Christinadobrzyn** [comment] 2024-04-24 07:54
holding for @situchan to accept this Upwork offer - https://www.upwork.com/nx/wm/offer/101773908

**Comment by Christinadobrzyn** [comment] 2024-05-03 03:48
Dmd @situchan to see if they are back and can accept the offer

**Comment by Christinadobrzyn** [comment] 2024-05-08 09:04
moving this to monthly since payment is all that's needed. @situchan let me know when you're back b/c I'll need to make a new offer

**Comment by situchan** [comment] 2024-05-17 00:42
Sorry for late. I am back. Can you please send new offer?

**Comment by Christinadobrzyn** [comment] 2024-05-17 04:11
@situchan here's the new offer - https://www.upwork.com/nx/wm/offer/102347085

Thanks!

**Comment by Christinadobrzyn** [comment] 2024-06-13 01:32
Paid @situchan in upwork based on this payment summary - https://github.com/Expensify/App/issues/35682#issuecomment-2040358104

Closing!

**Closed by Christinadobrzyn** 2024-06-13 01:32 UTC
Labels: Engineering, Monthly, Internal, Awaiting Payment, Bug
