### ISSUE TITLE
Not applying bold style to the selected pronouns

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14154] opened 2023-01-09 19:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Expensify.
2. Click on profile icon.
3. Choose profile option.
4. Choose pronouns.

## Expected Result: 
Selected pronouns are checked with a green checkmark and the text is bold.

## Actual Result: 
Selected pronouns are checked with a green checkmark and the text is not bold.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.51
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="347" alt="boldstyle2" src="https://user-images.githubusercontent.com/43996225/211388724-51cbf422-ba6b-46a6-8cd0-ea4409fb74b0.png">
<img width="662" alt="boldstyle" src="https://user-images.githubusercontent.com/43996225/211388725-f7af690f-a9c3-4bf5-848a-1fc245a0e0a6.png">
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/211388755-c9ed7ae4-a9f1-4c78-8297-96dcca84f918.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @oesayan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673253083720439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf7952f73a42104b</li>
        <li>Upwork Job ID: 1612804597019262976</li>
        <li>Last Price Increase: 2023-01-10</li>
    </ul>
</details>

**Comment by anmurali** [comment] 2023-01-09 22:50
Looks bold to me!

Chrome browser
<img width="354" alt="image" src="https://user-images.githubusercontent.com/14225673/211416180-14e55486-7227-44db-91f3-f33699be26b2.png">

iOS/ native
<img width="328" alt="image" src="https://user-images.githubusercontent.com/14225673/211421846-11572868-d903-456b-a796-6b74e39a1ce4.png">

iOS/chrome
<img width="316" alt="image" src="https://user-images.githubusercontent.com/14225673/211423334-f2c8dff9-ba80-4930-bd87-4e9ee94152ec.png">

**Comment by anmurali** [comment] 2023-01-09 22:51
@kavimuru can you try to reproduce in production again and include screenshots if you're able to reproduce?

**Comment by Beamanator** [comment] 2023-01-10 07:28
@anmurali I believe the reported bug was on the page where you select a pronoun / timezone, not on the Profile page 🤔 

I'm seeing this:

| Pronouns | Timezone |
|---|---|
| <img width="350" alt="Screenshot 2023-01-10 at 9 27 08 AM" src="https://user-images.githubusercontent.com/3885503/211488261-2f54085d-6f8f-441b-b18a-3cc08146f3b2.png"> | <img width="350" alt="Screenshot 2023-01-10 at 9 27 25 AM" src="https://user-images.githubusercontent.com/3885503/211488287-1d0b6bc5-ae9a-48d4-906c-13e40b014e0f.png"> |

**Comment by flaviadefaria** [comment] 2023-01-10 10:49
@Beamanator are you going to handle this? Should I add an internal label?

**Comment by Beamanator** [comment] 2023-01-10 13:32
@flaviadefaria yep sorry for notifying you, I have a PR ready to fix this 👍

**Comment by Beamanator** [comment] 2023-01-17 19:25
This was deployed to production (https://github.com/Expensify/App/pull/14176#issuecomment-1381720685) 4 days ago :D

@flaviadefaria do you mind paying out @sobitneupane for reviewing the PR?

**Comment by oesayan** [comment] 2023-01-17 19:47
Sorry to hijack the thread, but the issue is soon to be closed and the Upwork job is still private so I can not apply. Is there something I should do so I can apply?

**Comment by Beamanator** [comment] 2023-01-18 09:20
Don't worry, you're not hijacking @oesayan 👍 It looks like Flavia is actually out till next week so I'm going to ask for another #bug-zero person to take over here and they can answer your question

**Comment by dylanexpensify** [comment] 2023-01-18 09:34
Hello! I can help!

**Comment by dylanexpensify** [comment] 2023-01-18 09:46
@oesayan I can't seem to find your Upwork profile - mind linking it here?

**Comment by dylanexpensify** [comment] 2023-01-18 09:46
@sobitneupane invited you to the job!

**Comment by oesayan** [comment] 2023-01-18 09:47
@dylanexpensify Hello! Sure, it is https://www.upwork.com/freelancers/~017637da0274c11b53
Thank you!
Guess the profile got lost somewhere since I can't apply for any other issues I reported.

**Comment by sobitneupane** [comment] 2023-01-18 10:35
> @sobitneupane invited you to the job!

Thanks @dylanexpensify. Applied for the job.

**Comment by dylanexpensify** [comment] 2023-01-18 11:01
@sobitneupane offer sent!

@oesayan nice!! Sent you the invite! Also - see you're based in Tampa! I grew up just south of there in Sarasota! Small world!

**Comment by oesayan** [comment] 2023-01-18 11:02
> @sobitneupane offer sent!
> 
> 
> 
> @oesayan nice!! Sent you the invite! Also - see you're based in Tampa! I grew up just south of there in Sarasota! Small world!

thank you! I am frequently visiting Sarasota and also Longboat Key haha. Truly a small world!

**Comment by dylanexpensify** [comment] 2023-01-18 11:05
>I am frequently visiting Sarasota and also Longboat Key haha. Truly a small world!
hahaha amazing! Siesta Key is definitely a great spot to visit!

**Comment by dylanexpensify** [comment] 2023-01-18 13:38
Offer sent @oesayan !

**Comment by dylanexpensify** [comment] 2023-01-18 15:30
Payment sent, contract ended @oesayan

**Comment by Beamanator** [comment] 2023-01-19 09:00
Great so @dylanexpensify i think we're good to close this, right?

**Comment by dylanexpensify** [comment] 2023-01-20 10:17
Just gotta do a RT then yes! Will do today and close out 😄

**Comment by dylanexpensify** [comment] 2023-01-20 10:27
https://expensify.slack.com/archives/C01SKUP7QR0/p1674210426920129

**Comment by dylanexpensify** [comment] 2023-01-20 10:45
QA addition: https://github.com/Expensify/Expensify/issues/256249

**Closed by dylanexpensify** 2023-01-20 10:45 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
