### ISSUE TITLE
[$250] mWeb/Chrome - Account Management page - Required section name is not visible

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12210] opened 2022-10-27 19:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12147 

## Action Performed:
1. Go to https://help.expensify.com/articles/other/Account-Management#how-do-i-contact-my-account-manager

## Expected Result:
"How do I contact my account manager?" section of "Account Management" page should be displayed with section name visible.

## Actual Result:
"How do I contact my account manager?" section name is not visible once user is landed on the page. Only Android / Chrome. Not repro with iOS / Safari nor Windows / Chrome

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web - Android/Chrome

**Version Number:** 1.2.19.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/198381143-67badcb1-16ef-4681-86bf-1d55cb56c583.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment] 2022-10-28 02:12
Hmm, I'm not sure if this needs to go to engineering or if we can close as a part of the Deploy list above - but swinging over in case.

**Comment by sophiepintoraetz** [comment] 2022-10-30 23:12
Actually, cc @marcochavezf and @johncschuster from https://github.com/Expensify/Expensify/issues/188579

**Comment by michaelhaxhiu** [comment] 2022-11-03 23:28
Switching back to `daily` per the standard bugzero process. Also just a friendly reminder to [keep the pressure](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109) on to find a contributor and get this one closed out!

A few questions to help move this forward.
1. Is this `external` or `internal`?
2. If it's `external` let's post it to upwork. If it's `internal` and reproducible, let's label as `demolition` to get movement.

**Comment by sophiepintoraetz** [comment] 2022-11-04 00:26
I'd love to hear from @marcochavezf and @johncschuster to confirm that it's a quick fix from https://github.com/Expensify/Expensify/issues/188579

**Comment by marcochavezf** [comment] 2022-11-04 02:48
Oh I missed the previous ping, I think it can be external. Contributors can follow [these instructions](https://github.com/Expensify/App/blob/main/docs/README.md) to run the site locally. I tried to update some of the 
 tocbot [settings](https://tscanlin.github.io/tocbot/), but I have no luck. Probably it's a CSS style issue.

**Comment by sophiepintoraetz** [comment] 2022-11-07 00:05
Bumping @roryabraham 🙏

**Comment by roryabraham** [comment] 2022-11-07 21:05
Sorry for the delay, marking this as external

**Comment by sophiepintoraetz** [comment] 2022-11-08 04:28
[Job posted!](https://www.upwork.com/jobs/~013080b056ebfbb6c0)

**Comment by kzhein** [comment] 2022-11-08 07:48
### Proposal

Expensify help website has a fixed navigation menu for small screens that usually remains fixed at the top of the page. When you use the URL anchor, the browser window will scroll itself (instantly) to bring anchor at the top of the page, leaving the content behind the fixed navigation menu.

### Solution:

https://user-images.githubusercontent.com/58266349/200504507-c1610a89-3b43-472a-a50b-0c6667669f00.mp4


For small screens, we can use :before pseudo element and giving it a height, which pushes up the size of the header, then use negative margin to yank it back up into place

```css
#content-area {
  h1::before, h2::before {
    @include maxBreakpoint($breakpoint-tablet) {
            display: block;
            content: ' ';
            height: 80px; 
            margin-top: -80px;
            visibility: hidden;
    }
  }
}
```

**Comment by sobitneupane** [comment] 2022-11-09 10:52
[Workaround](https://github.com/Expensify/App/issues/12210#issuecomment-1306767308) proposed by @kzhein looks good and test well. 

As I am not very much familiar with "help.expensify.com", I am not sure if there is any other direct ways to achieve the result. 

cc: @Julesssss 

🎀👀🎀 C+ reviewed

**Comment by kzhein** [comment] 2022-11-09 16:25
Thanks! I have sent a [pull request](https://github.com/Expensify/App/pull/12601) and applied the job in Upwork.

**Comment by sophiepintoraetz** [comment] 2022-11-21 04:15
@Julesssss - are we waiting on a review from @Gonals for this issue to close it out?

**Comment by Julesssss** [comment] 2022-11-22 14:55
Ah, the automated message didn't appear but we are still 2 days away from payment. Then we can close the issue.

**Comment by mvtglobally** [comment] 2022-11-22 21:13
Issue not reproducible during KI retests. (First week)

**Comment by kzhein** [comment] 2022-11-24 12:52
@sophiepintoraetz May I know when can I expect the payment?

**Comment by sophiepintoraetz** [comment] 2022-11-24 23:26
Hey @kzhein - typically we need 7 days from the PR being merged but you're all set! Just processed payment through Upwork now 👍 @sobitneupane - I've hired you for the job if you want to accept the contract!

**Comment by sobitneupane** [comment] 2022-11-25 05:04
@sophiepintoraetz Accepted offer. This issue is also eligible for 50% bonus since the PR was merged within 3 days.

**Comment by roryabraham** [comment] 2022-11-28 20:30
Dropping this since @Julesssss has been acting as the CME for this issue.

**Comment by kzhein** [comment] 2022-11-29 00:25
@sophiepintoraetz Received the payment but I think you forgot the eligible 50% bonus.

**Comment by sophiepintoraetz** [comment] 2022-11-29 00:30
Sorry @kzhein - I was out yesterday - I'll look into this once I have a chance!

**Comment by mvtglobally** [comment] 2022-11-30 05:00
Issue not reproducible during KI retests. (Second week)

**Comment by sophiepintoraetz** [comment] 2022-11-30 05:27
@kzhein - thanks for your patience! I created a separate job I hired you for with the bonus of $125 - [see here](https://www.upwork.com/jobs/~01125cbcff03070522)!

**Comment by sophiepintoraetz** [comment] 2022-11-30 06:58
All paid!

**Closed by sophiepintoraetz** 2022-11-30 06:58 UTC
Labels: Reviewing, External, Engineering, Daily, Bug

**Comment by sobitneupane** [comment] 2022-11-30 07:50
> @sophiepintoraetz Accepted offer. This issue is also eligible for 50% bonus since the PR was merged within 3 days.

@sophiepintoraetz I am not paid yet. I have accepted the offer.

**Comment by sophiepintoraetz** [comment] 2022-12-01 00:35
Hired you for the job @sobitneupane - [here's the link!](https://www.upwork.com/jobs/~010f05e19c2baabe06)

**Comment by sobitneupane** [comment] 2022-12-01 02:09
@sophiepintoraetz Thanks. (250$+125$) is due.

**Comment by sophiepintoraetz** [comment] 2022-12-01 02:39
All set @sobitneupane
