### ISSUE TITLE
 Inconsistency when responded via email

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20428] opened 2023-06-08 00:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to web chrome and login with User A (the primary email account) and request money from multiple test accounts (Eg. User B, User C)
2. Now, login from those Users (test accounts) and you will have received a money request. Click on 'I will settle up elsewhere'
This will generate an IOU email to User A from those test accounts with a message "has sent $x elsewhere"
3. Go to Gmail and you will receive an email saying ""has sent $x elsewhere. To respond, head over to Expensify or reply directly to this message."
4. Reply to the message as User A directly from the email saying "Thank you for paying"
5. Login with test account and verify the message
## Expected Result: 
All reply messages should go to their respective chats (User Inbox)
## Actual Result: 
Some reply messages goes to the 'Concierge chat' while others goes to User chat/Inbox

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.23-6
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7ed4c79d-1f74-46af-9b77-78d14ded26a1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685921319932199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment] 2023-06-10 11:18
I'm also not able to reproduce this. Need to check what to do as next steps.

**Comment by flaviadefaria** [comment] 2023-06-15 16:52
I also wasn't able to reproduce this so closing it for now.

**Closed by flaviadefaria** 2023-06-15 16:52 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
