### ISSUE TITLE
[HOLD for payment 2022-12-22] DEV - Loading indicator is not  in center on Add Bank Account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13401] opened 2022-12-07 16:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to new
2. go to Settings - payments - Add Payment method - Bank Account
3. observe the loading indicator

## Expected Result: 
The loading indicator should be in the center.

## Actual Result: 
The loading indicator isn't in center

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.36-2
**Reproducible in staging?:** Needs preproduction (Seems happening only in DEV)
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206236316-1ad5c227-7d66-4c22-a73b-07f5a8e58b83.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @varshamb 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670352022190369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2022-12-07 17:52
I'm unable to reproduce this on `v1.2.36-2` web chrome, so I’m going to close this issue in the absence of clearer reproduction steps to reliably reproduce it. 
![navhcDw8DI](https://user-images.githubusercontent.com/16232057/206257767-a14da668-c0d6-4822-b099-e97124f70a94.gif)

**Comment by aldo-expensify** [comment] 2022-12-07 18:38
I can reproduce in all of them, but in DEV, not staging.. so I guess that explains why you can't reproduce :P. Looks like a regression that is going to be deployed at some point

**Comment by aldo-expensify** [comment] 2022-12-07 18:38
Ahh, yeah, it is in the description `Reproducible in staging?: Needs preproduction (Seems happening only in DEV)` 🤦

**Comment by aldo-expensify** [comment] 2022-12-07 18:49
The regression seems to be coming from this PR: https://github.com/Expensify/App/pull/12954

**Comment by trjExpensify** [comment] 2022-12-09 02:01
@aldo-expensify are we making this a deploy blocker then?

**Comment by aldo-expensify** [comment] 2022-12-09 02:02
Well, I think it becomes a deploy blocker when it reaches staging. I don't know if we can use the label before that.

**Comment by trjExpensify** [comment] 2022-12-09 02:19
Oh sorry, I saw it on the [deploy checklist here](https://github.com/Expensify/App/issues/13431#issue-1483420455) when I was going through - should have checked in the PR for the state. Cool, makes sense. Want to add the `Internal` label in the interim though?

**Comment by aldo-expensify** [comment] 2022-12-10 01:38
Draft PR up: https://github.com/Expensify/App/pull/13499

**Comment by trjExpensify** [comment] 2022-12-21 18:17
👋 I'm going to be out from tomorrow when this payment is due. 

@varshamb I've sent you an offer for $250 for reporting the issue, and @thesahindia $1k for the PR review. Can you please accept the[ job offers on this](https://www.upwork.com/jobs/~0143cd1b2bb2f5a458). Once you have, do confirm here in the issue. @JmillsExpensify I'm co-assigning you to settle those contracts if you wouldn't mind! 

As for the rest of the checklist..

> [@aldo-expensify] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

@aldo-expensify what do you think about this one? I think that will inform whether we should add a regression test for this, as it's largely a cosmetic UI placement issue.

**Comment by aldo-expensify** [comment] 2022-12-21 18:22
> @aldo-expensify what do you think about this one? I think that will inform whether we should add a regression test for this, as it's largely a cosmetic UI placement issue.

@mvtglobally do you know if this is already part of a test? (Verifying that the loading spinner is in the middle of the panel and not at the top)

**Comment by trjExpensify** [comment] 2022-12-21 18:23
Settled up with @thesahindia. 👍

**Comment by trjExpensify** [comment] 2022-12-21 18:26
@aldo-expensify it would likely be here if so: https://expensify.testrail.io/index.php?/cases/view/1971065&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=229065

**Comment by aldo-expensify** [comment] 2022-12-21 19:06
Thanks @trjExpensify. I modified the step 4. to be 

`4. Verify the loading spinner appears vertically centred and then the plaid modal is displayed.`

Does that sound good?

**Comment by JmillsExpensify** [comment] 2022-12-22 17:44
> @varshamb I've sent you an offer for $250 for reporting the issue, and @thesahindia $1k for the PR review. Can you please accept the[ job offers on this](https://www.upwork.com/jobs/~0143cd1b2bb2f5a458). Once you have, do confirm here in the issue. @JmillsExpensify I'm co-assigning you to settle those contracts if you wouldn't mind!

Circling back on this. I'm still waiting for @varshamb to accept the offer before I can finalize the contract and settle up the reporting bonus.

**Comment by JmillsExpensify** [comment] 2022-12-27 19:37
@varshamb Quick reminder that you have an offer outstanding in Upwork for [this job](https://www.upwork.com/jobs/~0143cd1b2bb2f5a458). Please accept the offer so we can make sure you're paid.

**Comment by JmillsExpensify** [comment] 2022-12-31 18:03
@varshamb Reminding you again that you have an outstanding offer you need to accept in Upwork, thanks!

**Comment by trjExpensify** [comment] 2023-01-03 02:51
Awesome, thanks for accepting @varshamb. I've settled up!

@aldo-expensify that edit looks good, so closing this out now. Thanks ya'll!

**Closed by trjExpensify** 2023-01-03 02:51 UTC
Labels: Reviewing, Daily, Internal, Awaiting Payment, Bug
