### ISSUE TITLE
[$500] Web - Bank Account - Blue box focus appears when clicking enter

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31891] opened 2023-11-26 22:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.3-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
1. Go to settings > Workspace > choose a workspace (currency should be USD)
2. Bank account > Connect Manually
3. Fill in the details of steps 1 - 3. Then proceed to the next part of Step 3(Choose your documents step)
4. Click with your mouse on an empty field near the passport and driving license buttons.
5. Press on Enter from the Keyboard.

## Expected Result:
No blue box is shown when clicking enter

## Actual Result:
blue box is shown when clicking enter

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d96cb4d1-7652-426f-a13d-a5ae8c7d9b75

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01140847c130c78965</li>
        <li>Upwork Job ID: 1728906192050343936</li>
        <li>Last Price Increase: 2023-11-26</li>
    </ul>
</details>

**Comment by zukilover** [comment] 2023-11-26 23:47
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Document area shows blue box on clicking enter.

### What is the root cause of that problem?
The blue box comes from onFido UI, specifically at `restrictedDocumentSelection` where it has a tabIndex of 0.
This results in the scrollable content (`onfido-sdk-ui-Theme-scrollableContent`) to focus when hitting Enter.

### What changes do you think we should make in order to solve the problem?
Override the tabIndex manually from this line https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/components/Onfido/index.website.js#L9-L10:

```javascript
          let overrideTabIndex = null
            if (baseOnfidoRef.current) {
                overrideTabIndex = setTimeout(() => {
                    const documentSelection = baseOnfidoRef.current.querySelector('[data-page-id="restrictedDocumentSelection"]')
                    documentSelection.tabIndex = -1
                }, 3000)
            }
```

### What alternative solutions did you explore? (Optional)
Raise a feature request on the library: https://github.com/onfido/onfido-sdk-ui so that it accepts a tabIndex option.

**Comment by allroundexperts** [comment] 2023-11-26 23:50
@zukilover Can't you apply the styles directly in `src/components/Onfido/index.css`?

**Comment by zukilover** [comment] 2023-11-26 23:58
@allroundexperts we can of course apply an `outline: none` in the css, but it does not override the tabIndex. And this tabIndex is currently doing nothing other than focusing on the scrollable content of onFido.

**Comment by allroundexperts** [comment] 2023-11-27 00:00
I think its better to use `outline` as it does not involve the usage of setTimeouts which we highly discourage. Also, we've done that in past as well (https://github.com/allroundexperts/Expensify/blob/b0b1ff344f5b1523d46083781e0fbc8253a29f91/src/components/Onfido/index.css#L31).

**Comment by zukilover** [comment] 2023-11-27 00:12
@allroundexperts in that case, I have updated my proposal:

### Proposal
[Updated](https://github.com/Expensify/App/issues/31891#issuecomment-1826942495)

**Comment by allroundexperts** [comment] 2023-11-27 00:13
@zukilover's [proposal](https://github.com/Expensify/App/issues/31891#issuecomment-1826942495) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by roryabraham** [comment] 2023-11-29 18:59
Sorry, I'm going to close this as not worth fixing.

**Closed by roryabraham** 2023-11-29 18:59 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
