### ISSUE TITLE
[$500] Chat - Red dot of failed scan request still remains on admin chat after deleted from employee

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33534] opened 2023-12-23 02:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must log in with the admin and an employee of a workspace
1. From employee side, create a scan request that will fail (missing details)
2. Wait for the scan to fail
3. Verify there is a red dot on the admin side
4. Go to employee account and delete the request

## Expected Result:
The red dot of failed scan request should disappear on both sides, employee and admin

## Actual Result:
The red dot still remains on admin chat and LHN after the request is removed from the employee side

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3a47eb22-39e4-4b09-bfc7-61fb08e8cc70

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010109c98b8e7fa3de</li>
        <li>Upwork Job ID: 1738392249100804096</li>
        <li>Last Price Increase: 2023-12-23</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment] 2023-12-23 12:38
This seem to be by design, the BE isn't clearing transactions on the admin side, probably because it's intended for the admin to see transactions even if the employee deletes them. since the transaction will be accessible to the admin, red dot will appear because the following code will return true: 

`function hasMissingSmartscanFields(transaction: OnyxEntry<Transaction>): boolean {
    return Boolean(transaction && hasReceipt(transaction) && !isDistanceRequest(transaction) && !isReceiptBeingScanned(transaction) && areRequiredFieldsEmpty(transaction));
}`

**Comment by bfitzexpensify** [comment] 2023-12-25 20:29
Thanks @AmjedNazzal, in that case, let's close this out.

**Closed by bfitzexpensify** 2023-12-25 20:29 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
