### ISSUE TITLE
[HOLD for payment 2024-07-10] [$500] [One expense reports] The expense details are shown at the top, and then a report preview in the comments

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43034] opened 2024-06-04 14:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717176771231389

## Action Performed:

1. Have a HT account as admin
2. Create a policy with some violation (category required) and leave the submission frequency as instantly
3. Invite a member A
4. As a member A create a report with only one expense
5. Log in as HT admin
6. Open the report

## Expected Result:
Expense report preview should not appear in the expense details page

## Actual Result:
Expense details showing at the top, and then a report preview of the same in the comments

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-05-31 at 11 31 43@2x (1)](https://github.com/Expensify/App/assets/38435837/ca4c9d19-ed0c-4336-82ef-c12ebfd4ac02)

https://github.com/Expensify/App/assets/38435837/16c6fda0-4465-4b28-93b5-252601935d89

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016087f922551bb586</li>
        <li>Upwork Job ID: 1798510897494771226</li>
        <li>Last Price Increase: 2024-06-18</li>
<li>Automatic offers: </li>
<ul>
<li>wildan-m | Contributor | 102862232</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment] 2024-06-06 00:22
I'm struggling to reproduce this myself, but given that Jason runs into it a lot and QA have reproduced. I'm going to move it forward.

Sounds like a perfect storm of HT account and slow internet connection are in play.

**Comment by marcuscook2169** [comment] 2024-06-06 05:21
I do have a feeling this has something to do with the JS. I would need access to recreate the issue and inspect elements on said page to really dial in exactly what is going on. Inspecting your main page, This is the only possible thing I could think of.

**Comment by trjExpensify** [comment] 2024-06-11 18:18
>I do have a feeling this has something to do with the JS. I would need access to recreate the issue and inspect elements on said page to really dial in exactly what is going on. Inspecting your main page, This is the only possible thing I could think of.

Any luck @marcuscook2169?

**Comment by trjExpensify** [comment] 2024-06-13 09:02
Still awaiting proposals.

**Comment by trjExpensify** [comment] 2024-06-18 11:47
Still awaiting proposals. @Pujan92 don't suppose you fancy just taking this issue if we don't get any bites?

**Comment by wildan-m** [comment] 2024-06-22 01:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

[One expense reports] The expense details are shown at the top, and then a report preview in the comments

### What is the root cause of that problem?

[transactionThreadReportActions](https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/libs/ReportActionsUtils.ts#L376C66-L376C96) can be empty when the report is not opened yet, [this check](https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/libs/ReportActionsUtils.ts#L377-L379) directly return all reportActions when transactionThreadReportActions empty or not yet loaded.

### What changes do you think we should make in order to solve the problem?

Remove this check:

https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/libs/ReportActionsUtils.ts#L377-L379

 and it will keep using logic to filter expected reportActions here:

https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/libs/ReportActionsUtils.ts#L387-L398

### What alternative solutions did you explore? (Optional)

**Comment by wildan-m** [comment] 2024-06-22 01:37
Proposal [updated](https://github.com/Expensify/App/issues/43034#issuecomment-2183633570).

Add nullish coalescing  ?? [] to filteredTransactionThreadReportActions

**Comment by Pujan92** [comment] 2024-06-23 19:20
Thanks for the proposal @wildan-m. I agree with the RCA but with a proposed solution I think it will create the below problem.

> Remove this check:
- If we remove that check then for the reports where there are multiple IOU's are also filtered out with the remaining logic. With that, it won't render any IOU in the report actions.
https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/libs/ReportActionsUtils.ts#L386-L390

**Comment by wildan-m** [comment] 2024-06-23 20:24
@Pujan92 Thanks for the feedback, proposal [updated](https://github.com/Expensify/App/issues/43034#issuecomment-2183633570)


We only apply the logic when we only have one undeleted IOU

**Comment by Pujan92** [comment] 2024-06-24 05:25
> `const nonDeletedReportActions = reportActions?.filter((action) => !isDeletedAction(action));`

@wildan-m This also won't work because you are suggesting to consider any generic type not deleted message, so for a case when there is only 1 IOU but also some chat messages then its length will be more than 2(`nonDeletedReportActions.length > 2`) and it returns all actions which will still render the IOU preview for one transaction reports.

**Comment by wildan-m** [comment] 2024-06-24 05:28
@Pujan92 please also check the alternative one

**Comment by Pujan92** [comment] 2024-06-24 05:38
> @Pujan92 please also check the alternative one

Ah, Sorry I missed that. The alternative solution from @wildan-m's [proposal](https://github.com/Expensify/App/issues/43034#issuecomment-2183633570) makes sense to consider IOU count too for deciding one expense report.

🎀👀🎀 C+ reviewed

**Comment by wildan-m** [comment] 2024-06-24 20:09
@deetergp Any other feedback before we move on to the next step?

**Comment by deetergp** [comment] 2024-06-24 21:29
Okay, let's go with @wildan-m's alternative solution.

**Comment by wildan-m** [comment] 2024-06-25 04:03
@Pujan92 The PR is ready for review. [link](https://github.com/Expensify/App/pull/44366)

**Comment by trjExpensify** [comment] 2024-07-10 17:51
👋 checklist time!

**Comment by Pujan92** [comment] 2024-07-10 19:36
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [X] [@Pujan92] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/36934
- [X] [@Pujan92] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/36934/files#r1672831481
 - [X] [@Pujan92] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: NA
 - [X] [@Pujan92] Determine if we should create a regression test for this bug. Yes
 - [X] [@Pujan92] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
 
### Regression Test Steps

1. Create a collect policy
2. Invite a member A
3. Login as a member A and submit an expense within that policy
4. Log in as admin
5. Open that report
6. Verify that the IOU preview does not appear on that one expense report

**Comment by JmillsExpensify** [comment] 2024-07-11 03:24
Ready to pay this once I get a payment summary.

**Comment by trjExpensify** [comment] 2024-07-11 14:18
Thanks, Pujan! Payment summary as follows:

- $500 to @Pujan92 for the C+ review (go ahead and request)
- $500 to @wildan-m for the fix (paid!)

Closing!

**Closed by trjExpensify** 2024-07-11 14:18 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-11 16:28
$500 approved for @Pujan92
