### ISSUE TITLE
Chat - Chat history disappears after creating a task

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25676] opened 2023-08-22 13:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any chat
3. Tap "+" button and select "Assign a task"
4. Enter the Title and assign it to yourself
5. Navigate to the chat

## Expected Result:
Chat history is displayed

## Actual Result:
Chat history disappears, only the task is shown after scrolling up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/53545482-42bc-435b-8d17-fb9e821a57f5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by daordonez11** [comment] 2023-08-22 14:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
edited message is overlapping with the next message in the chat if a quote is used

### What is the root cause of that problem?
Due to this [PR](https://github.com/Expensify/App/pull/24235/files) in `BaseHTMLEngineProvider` `defaultViewProps` now have `styles.w100, styles.h100` which are causing the issue of the `blockquote` element specifically height 100%

### What changes do you think we should make in order to solve the problem?
I think there might be more issues since this is used by the `RenderHTMLSource` but this is the first visible so there are two ways of solving it:
1. remove from defaultViewProps h100 and w100 and include it in the specific element required using `webViewStyles.tagStyles`
2. In the `webViewStyles.tagStyles.blockquote` element we can override height to avoid the issue.
I'm inclined to using solution #1 but it would require help from the author of the display receipts in chat to avoid any side effect in the implementation.

### What alternative solutions did you explore? (Optional)

**Comment by arosiclair** [comment] 2023-08-22 20:03
Prioritizing another distance request deploy blocker over this. This is free to take by anyone

**Comment by roryabraham** [comment] 2023-08-23 00:17
Not able to reproduce this on web

**Comment by roryabraham** [comment] 2023-08-23 00:17
Trying Android next

**Comment by roryabraham** [comment] 2023-08-23 00:26
Not able to reproduce this on Android v `1.3.56-16`:

![Screenshot_20230822-172435](https://github.com/Expensify/App/assets/47436092/1da86ac6-f499-4a22-993b-1811bdefbaee)

**Comment by roryabraham** [comment] 2023-08-23 00:28
Going to close this one as fixed

**Closed by roryabraham** 2023-08-23 00:28 UTC
Labels: Engineering, Hourly
