### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Web - Chat - Empty space is added after adding an emoji by typing in web platform

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21584] opened 2023-06-26 16:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Login to expensify web
2.  Go to any chat and type ":smiley":" and notice that the position marker is right next to the smiley emoji 
3. Go to the expensify app and open any chat
 4. Type ":smiley":" and notice that there is a spaces between the position marker and the smiley emoji

## Expected Result:
There should always be a space added after an emoji.

## Actual Result:
Inconsistent spacing after a smiley (or any emoji) on different platforms. A space is added in the Android mobile app, but no space is added next to the emoji in web, the desktop app, or in the iOS app.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8f57dc19-6039-4b71-ad56-1b678ca590ef

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687428313003479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ef8342a4645c7a1</li>
        <li>Upwork Job ID: 1673543813405294592</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-06-27 04:08
I was able to reproduce this in the Android mobile app - that's the only platform that has the extra space in front of the emoji. All other platforms have no space after the emoji.

I'm not sure if it's possible, but ideally when we fix this, we can check to see if there are similar spacing issues in other places (like maybe we use the same component in different places).

**Comment by bernhardoj** [comment] 2023-06-27 04:41
Here is a previous [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1668009281985659?thread_ts=1667208968.300839&cid=C01GTK53T8Q) that discuss the expected behavior on adding emojis.

**Comment by liondancing** [comment] 2023-06-27 07:22
hello, 
this is my chat site.
afc-three.vercel.app/chat
please consider...

**Comment by liondancing** [comment] 2023-06-27 07:25
***@***.***
upwork: kennyth stewart

**Comment by narefyev91** [comment] 2023-06-27 11:42
Proposal from @getusha looks good to me https://github.com/Expensify/App/issues/21584#issuecomment-1608765208
🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2023-06-27 11:51
@getusha proposal removes the space when adding an emoji from the suggestion, but this issue mentions the space from typing the complete emoji code, i.e. `:smile:`.

_I'm not posting any proposal because based on the thread I posted [here](https://github.com/Expensify/App/issues/21584#issuecomment-1608787826), the behavior is already working as expected, except we decide to change it_

**Comment by bernhardoj** [comment] 2023-06-27 12:19
Typing the complete emoji code will be handled by EmojiUtils.replaceEmojis
https://github.com/Expensify/App/blob/e5f00f86fb412702e9c212b5a88766a8ef7da611/src/libs/EmojiUtils.js#L245-L249

That's why the space is there only on mobile screens.

**Comment by sakluger** [comment] 2023-06-27 23:08
Hey @getusha @narefyev91 @luacmartins - I just noticed that we discussed this [previously in Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1682386879390169), and the space is added intentionally after an emoji. I just updated the GH issue description - could you please update your proposal and PR to make sure that we add a space in all platforms? Thanks!

**Comment by sakluger** [comment] 2023-06-29 23:14
Nice work everyone! I sent out offers through upwork to @SofoniasN and @getusha. @narefyev91 works for Callstack so we pay outside of Upwork.

**Comment by SofoniasN** [comment] 2023-06-30 04:30
Hey @chiragxarora your bug report mention space after emoji inconsistencies with in a platform but the issue i reported and @getusha fixed is the inconsistencies across platforms. 

@sakluger couldnt tell if the upwork offer was pulled back due to this issue if it was i hope this clarifies it, Thanks in advance.

**Comment by SofoniasN** [comment] 2023-07-01 04:43
Hey guys, any new updates on the issue @sakluger? Thanks in advance

**Comment by sakluger** [comment] 2023-07-04 00:28
Hey @chiragxarora  - This same question/issue has come up 4 or 5 times over the past 8 months, and it was reported by someone different every time. Originally, it was raised [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667208968300839), then [here](https://expensify.slack.com/archives/C049HHMV9SM/p1682386879390169), and I think one or two other times.

I'm still going to award the reporting bonus to @SofoniasN because their report got us talking about this behavior again, so I think it's fair to reward them. It's definitely a tricky situation, but I think that's the most fair decision in this case.

**Comment by SofoniasN** [comment] 2023-07-04 03:20
@sakluger Thank you for the thoughtful consideration!

**Comment by sakluger** [comment] 2023-07-07 22:39
@SofoniasN sorry, I'm not sure what happened, I didn't take back the offer. I just tried resending, let me know if you didn't receive it.

**Comment by SofoniasN** [comment] 2023-07-08 03:54
@sakluger No worries. I have accepted the offer, I am waiting on your approval!

Thanks

**Comment by sakluger** [comment] 2023-07-10 18:35
Hey @narefyev91 could you please complete the BZ checklist? Thanks!

**Comment by sakluger** [comment] 2023-07-10 18:40
I sent payments to @SofoniasN and @getusha (with efficiency bonus). Just waiting for the BZ checklist before closing out this issue. Given that this issue has come up a few times now, I think it would be helpful to document the correct behavior by adding a regression test.

**Comment by narefyev91** [comment] 2023-07-11 07:23
- The PR that introduced the bug has been identified. Link to the PR - https://github.com/Expensify/App/pull/21749
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - no important code changes were define
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - no discussion
- Determine if we should create a regression test for this bug - we are good with existing QA steps in PR

**Closed** 2023-07-11 15:54 UTC
Labels: External, Daily, Awaiting Payment, Bug
