### ISSUE TITLE
BUG:Pay with debit card - Doesn't auto-complete the zip and state correctly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11654] opened 2022-10-06 22:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to ND and login
2. Go to settings > payment > Debit card

## Expected Result:
Zip code and password should not auto filled in correctly

## Actual Result:
Zipcode auto filled with some portion of the email and password of that email

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.12-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="960" alt="STAGING" src="https://user-images.githubusercontent.com/43996225/194431039-36cdbeb7-aaa9-4492-94c2-68c9ba7f034a.png">
<img width="345" alt="image (2)" src="https://user-images.githubusercontent.com/43996225/194431056-52bd4314-3795-4190-9611-51d5b5a0d605.png">

https://user-images.githubusercontent.com/43996225/194431077-0349df27-0441-45de-b041-fdc1a8994873.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:**  @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665001946509239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment] 2022-10-06 23:04
Sorry, it is reproducible in production too

**Comment by joekaufmanexpensify** [comment] 2022-10-07 13:54
Having trouble reproducing in web, discussing [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1665150847778259?thread_ts=1665001946.509239&cid=C01GTK53T8Q).

**Comment by joekaufmanexpensify** [comment] 2022-10-10 12:03
Looking into this further today.

**Comment by joekaufmanexpensify** [comment] 2022-10-10 18:48
Clarifying a few questions about this [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1665427724197339).

**Comment by joekaufmanexpensify** [comment] 2022-10-10 20:32
@alex-mechler unassigning you as the bug that caused this is reported as being fixed by the above PR.

**Comment by joekaufmanexpensify** [comment] 2022-10-10 20:45
Asking clarifying question [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1665434664215229) to understand a bit better the relationship between this bug and the above linked PR.

**Comment by joekaufmanexpensify** [comment] 2022-10-11 20:48
Still discussing in Slack thread.

**Comment by joekaufmanexpensify** [comment] 2022-10-11 20:52
Discussed with @rushatgabhane [in Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1665434664215229) to understand a bit more about how the above linked PR fixed this bug. 

Since this bug is being fixed by a PR that's already merged, we're all set to close here. Payment will be handled in the original issue that led to the above linked PR.

**Closed by joekaufmanexpensify** 2022-10-11 20:52 UTC
Labels: AutoAssignerTriage, Daily
