### ISSUE TITLE
[HOLD for payment 2023-08-17] [$1000] Create Onyx migration for previousReportActionID

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#23221] opened 2023-07-19 23:47 UTC
# Part of the Comment Linking project
Main issue: https://github.com/Expensify/App/issues/20282
Doc section: https://docs.google.com/document/d/1v-ZaIRTZL5LIsyPWB0IopBNNgCajf5WC1OA8cVKtd8I/edit#bookmark=id.bry74gx446k1
Project: [Comment Linking](https://github.com/orgs/Expensify/projects/62/views/1)

# <Feature Description>
Create an Onyx migration called `CheckForPreviousReportActionID` that:

- Looks at a single reportAction from Onyx
- If that reportAction has the previousReportActionID field, resolve the migration.
- If the reportAction _does not_ have the previousReportActionID field, delete all reportActions from Onyx

This migration should be created and tested, but not yet added to [migrateOnyx](https://github.com/Expensify/App/blob/218920473e5753234408554cfd86517e4923ad84/src/libs/migrateOnyx.js#L19-L26) until we are ready.

# Manual Test Steps
Manually test this by locally adding the migration to `migrateOnyx` but do not commit that change.

# Automated Tests
We should update [MigrationTest](https://github.com/Expensify/App/blob/6bca6026f4b78b6751a4486c4543e084bb05f8cb/tests/unit/MigrationTest.js) to include tests for the new migration.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01382a606158d56e43</li>
        <li>Upwork Job ID: 1681813151297843200</li>
        2023-07-19<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 25687360</li>
<li>neonbhai | Contributor | 25687361</li>
</ul></li>
    </ul>
</details>

**Comment by roryabraham** [comment] 2023-07-19 23:48
No UI changes so I unassigned @shawnborton, but didn't mean to unassign @abdulrahuman5196

**Comment by roryabraham** [comment] 2023-07-19 23:49
Sorry for any confusion, @abdulrahuman5196 is the C+ for this issue

**Comment by neonbhai** [comment] 2023-07-20 00:08
Can contributors work on this feature? I am interested in working on this!

**Comment by roryabraham** [comment] 2023-07-20 00:09
Yep this is open to contributors. Please make a proposal 🙇🏼

**Comment by neonbhai** [comment] 2023-07-20 01:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Create Onyx migration for previousReportActionID

### What is the root cause of that problem?
New Feature

### What changes do you think we should make in order to solve the problem?


We are creating an Onyx migration called `CheckForPreviousReportActionID` which will:

1. Look at a single reportAction from Onyx
2. If `reportAction` has the `previousReportActionID field`, i.e., `if(lodashHas(reportAction, ['previousReportActionID'])` returns true, we `resolve()` the migration
3. If it returns false, we will delete all `reportActions` from Onyx

### What alternative solutions did you explore? (Optional)
xx

**Comment by neonbhai** [comment] 2023-07-20 01:20
@allroundexperts looks like it! This is probably because reportActions now always have to have a previousReportActionID, that represents (as the name says) to the reportAction immediately preceding it. If its not present, we delete reportActions as I'm guessing this implies some other task failed to complete.
@roryabraham please confirm!
I am also curious how this migration is useful for implementing the comment deeplinking feature, Is there any way I as a contributor can get to read the design doc, as it would help better understanding on how this feature is being implemented!

**Comment by perunt** [comment] 2023-07-20 11:13
### **Proposal**

### **Please re-state the problem that we are trying to solve in this issue.**
Create a new onyx migration

### **What is the root cause of that problem?**
Implementing support comment linking feature 

### **What changes do you think we should make in order to solve the problem?**
In the migrations folder, create a file called PreviousReportActionID with the following code:
```
/**
 * @returns {Promise<Object>}
 */
function getReportActionsFromOnyx() {
    return new Promise((resolve) => {
        const connectionID = Onyx.connect({
            key: ONYXKEYS.COLLECTION.REPORT_ACTIONS,
            waitForCollectionCallback: true,
            callback: (allReportActions) => {
                Onyx.disconnect(connectionID);
                return resolve(allReportActions);
            },
        });
    });
}

/**
 * Migrate Onyx data for reportActions. If the first reportAction of a reportActionsForReport
 * does not contain a 'previousReportActionID', all reportActions for that report are removed from Onyx.
 *
 * @returns {Promise<void>}
 */
export default function () {
    return getReportActionsFromOnyx().then(
        (oldReportActions) => {
            const onyxData = {};

            _.each(oldReportActions, (reportActionsForReport, onyxKey) => {
              if (_.isEmpty(reportActionsForReport)) {
                Log.info(`[Migrate Onyx] Skipped migration for ${onyxKey} because there were no reportActions`);
                return;
              }
              
              const firstReportActionID = Object.keys(reportActionsForReport)[0];
              const firstReportAction = reportActionsForReport[firstReportActionID];
              
              if (!firstReportAction || !firstReportAction.previousReportActionID) {
                Log.info(`[Migrate Onyx] Migration: removing all reportActions for ${onyxKey} because previousReportActionID not found in the first reportAction`);
                onyxData[onyxKey] = {};
              }
            });

            return Onyx.multiSet(onyxData);
        },
    );
}
```

test cases could look next:
```describe('Migration', () => {
    describe('CheckPreviousReportActionID', () => {
        it("Should wipe reportActions if 'previousReportActionID' is missing", () =>
            Onyx.multiSet({
                [`${ONYXKEYS.COLLECTION.REPORT}1`]: {
                    reportActions: {
                        'action1': {
                            reportActionID: 'action1',
                            previousReportActionID: null,
                        },
                        'action2': {
                            reportActionID: 'action2',
                            previousReportActionID: 'action1',
                        },
                    },
                },
                [`${ONYXKEYS.COLLECTION.REPORT}2`]: {
                    reportActions: {
                        'action3': {
                            reportActionID: 'action3',
                            previousReportActionID: 'action2',
                        },
                        'action4': {
                            reportActionID: 'action4',
                            previousReportActionID: 'action3',
                        },
                    },
                },
            })
                .then(CheckPreviousReportActionID)
                .then(() => {
                    const connectionID = Onyx.connect({
                        key: ONYXKEYS.COLLECTION.REPORT,
                        waitForCollectionCallback: true,
                        callback: (allReports) => {
                            Onyx.disconnect(connectionID);
                            expect(_.keys(allReports).length).toBe(2);
                            expect(allReports.report_1.reportActions).toBeNull();
                            expect(allReports.report_2.reportActions).not.toBeNull();
                        },
                    });
                }));
    });
});
```

**Comment by perunt** [comment] 2023-07-20 11:19
@allroundexperts @neonbhai, we are removing all **reportActions** from the current **Report** if the **previousReportActionID** is absent. We are implementing this change to support a feature that enables comment linking, allowing users to navigate through a Report using links instead of scrolling. However, to make this feature work smoothly, we need to eliminate any inconsistency in the saved data.

**Comment by joekaufmanexpensify** [comment] 2023-07-20 18:20
Proposals pending review.

**Comment by joekaufmanexpensify** [comment] 2023-07-21 13:14
@abdulrahuman5196 could you take a look at the proposals here when you have a sec?

**Comment by abdulrahuman5196** [comment] 2023-07-21 13:15
Yes will review today.

**Comment by abdulrahuman5196** [comment] 2023-07-21 15:44
@roryabraham 
I have a doubt in the requirement?

>If the reportAction does not have the previousReportActionID field, delete all reportActions from Onyx

Do we check all the reportAction for a particular report? Or just first reportAction or something else?

And assuming we find a reportAction with the previousReportActionID, we delete all the reportActions of that particular report right? Or just reportActions preceding the current reportAction?

**Comment by perunt** [comment] 2023-07-21 16:03
Just realized that we should immediately remove all non-compliant data at once (to prevent inconsistencies when interacting with Pusher). This way, we can get the migration done even faster.
```
/**
 * @returns {Promise<Object>}
 */
function getReportActionsFromOnyx() {
    return new Promise((resolve) => {
        const connectionID = Onyx.connect({
            key: ONYXKEYS.COLLECTION.REPORT_ACTIONS,
            waitForCollectionCallback: true,
            callback: (allReportActions) => {
                Onyx.disconnect(connectionID);
                return resolve(allReportActions);
            },
        });
    });
}

/**
 * Migrate Onyx data for reportActions. If any reportAction of a reportActionsForReport
 * does not contain a 'previousReportActionID', all reportActions for that report are removed from Onyx.
 *
 * @returns {Promise<void>}
 */
export default function () {
    return getReportActionsFromOnyx().then(
        (oldReportActions) => {
            const onyxData = {};

            _.each(oldReportActions, (reportActionsForReport, onyxKey) => {
              if (_.isEmpty(reportActionsForReport)) {
                Log.info(`[Migrate Onyx] Skipped migration for ${onyxKey} because there were no reportActions`);
                return;
              }
              
              let shouldRemoveReportActions = false;
              _.each(reportActionsForReport, (reportAction) => {
                if (!reportAction.previousReportActionID) {
                  shouldRemoveReportActions = true;
                  return false; // break the loop
                }
              });

              if (shouldRemoveReportActions) {
                Log.info(`[Migrate Onyx] Migration: removing all reportActions for ${onyxKey} because at least one previousReportActionID was not found`);
                onyxData[onyxKey] = {};
              }
            });

            return Onyx.multiSet(onyxData);
        },
    );
}
```

**Comment by roryabraham** [comment] 2023-07-22 08:00
Sorry for the delayed responses here...

> @roryabraham do you mean to delete ALL the report actions?

Yes, all reportActions for all reports.

> This is probably because reportActions now always have to have a previousReportActionID, that represents (as the name says) to the reportAction immediately preceding it. If its not present, we delete reportActions as I'm guessing this implies some other task failed to complete.
@roryabraham please confirm!

Yep, that's correct. In this case, the "other task" would be a change in our API to update the Onyx schema.

> Do we check all the reportAction for a particular report? Or just first reportAction or something else? ... And assuming we find a reportAction with the previousReportActionID, we delete all the reportActions of that particular report right? Or just reportActions preceding the current reportAction?

We should look at one reportAction from any report. It does not matter which report or reportAction. If that one reportAction has a `previousReportActionID` field, then great the migration is done. If not, then we will delete all reportActions from all reports in Onyx.

**Comment by roryabraham** [comment] 2023-07-22 08:03
@perunt even though you're heavily involved in this project I'm going to give this issue to @neonbhai for [this proposal](https://github.com/Expensify/App/issues/23221#issuecomment-1642956270) since it seems like they understand the task and know where to make the change. That gives you more time to focus on other tasks 🙂

**Comment by neonbhai** [comment] 2023-07-22 08:46
Thank you for assigning @roryabraham! 
Will raise PR in 24 hours :)

**Comment by neonbhai** [comment] 2023-07-24 06:01
@roryabraham @abdulrahuman5196 The [PR](https://github.com/Expensify/App/pull/23457) is ready for review!

**Comment by joekaufmanexpensify** [comment] 2023-08-10 22:09
Not overdue. Payment due next week!

**Comment by abdulrahuman5196** [comment] 2023-08-12 19:06
No BZ checklist, since this is a migration feature request.

**Comment by joekaufmanexpensify** [comment] 2023-08-18 21:11
Okay, all set to issue payment here. Based on the [guidelines for payment](https://github.com/Expensify/App/issues/23221#issuecomment-1673834473), this one would qualify for 50% speed penalty, since it took more than 9 business days to merge ([11 specifically](https://github.com/Expensify/App/issues/23221#issuecomment-1670149021)). This means we need to pay: 

- @neonbhai $500 for PR. 
- @abdulrahuman5196 $500 for C+ review. 

LMK if you have any questions on this, and if not, I'll issue payment on Monday!

**Comment by neonbhai** [comment] 2023-08-20 18:50
Hi @joekaufmanexpensify just wanted to say that the PR started reviewing about 3 days after raising the PR as I'm presuming @abdulrahuman5196 sir could not give enough time. As this was my first feature contribution, and since the migration is on the backend and the check could be running on every user signin, me and @abdulrahuman5196 tried to perfect and minimize the PR code. I hope the penalty can be forgiven 🙇

**Comment by joekaufmanexpensify** [comment] 2023-08-21 13:51
@neonbhai Thanks for the context! The purpose of the speed bonus/penalty is to incentivize the contributor and C+ to collaborate to get the PR merged quickly. It doesn't look like there were any internal delays here, so we'd still need to apply the penalty. 

But this doesn't impact your ability to contribute to future issues, or anything like that! LMK if you have any other questions.

**Comment by joekaufmanexpensify** [comment] 2023-08-21 13:56
@abdulrahuman5196 I see you were hired twice on this Upwork job, but I'm not sure why. As an fyi, I'm going to pay you $500 on one of the contracts, and then close out the other one with no payment. 

LMK if you have any questions on this!

**Comment by joekaufmanexpensify** [comment] 2023-08-21 13:57
@abdulrahuman5196 $500 sent and first contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-08-21 13:58
@abdulrahuman5196 second contract ended with no payment.

**Comment by joekaufmanexpensify** [comment] 2023-08-21 13:59
Closing as this is all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-08-21 13:59 UTC
Labels: External, Weekly, NewFeature, Awaiting Payment
