### ISSUE TITLE
[Awaiting Payment][$250] Migrate SwipeableView/index.native.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16203] opened 2023-03-20 08:44 UTC
### Filenames
- [ ] [src/components/SwipeableView/index.native.js](https://github.com/Expensify/App/blob/main/src/components/SwipeableView/index.native.js)
    - **type:** `React.PureComponent`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01acfdc7006f9d7166</li>
        <li>Upwork Job ID: 1685092599321219072</li>
        2023-07-29<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 25857041</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-06-06 11:06
I'd love to work on this.

**Comment by dayana7204** [comment] 2023-06-27 19:29
I am ready to work on this ticket. :)

**Comment by vdem0115** [comment] 2023-07-07 14:43
I would like to work on this issue.

**Comment by olexyt** [comment] 2023-07-07 14:52
I can work on this issue.

**Comment by mejed-alkoutaini** [comment] 2023-07-11 19:12
I'm able to work on this if needed!

**Comment by ojasjadhav2** [comment] 2023-07-29 03:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate `SwipeableView/index.native.js` to function component

### What is the root cause of that problem?
need to change class based component to functional

### What changes do you think we should make in order to solve the problem?
- component state and props from class to function syntax
- render method from class to function syntax
- lifecycle methods to hooks(if any)
- update callbacks from class to function syntax (possibly with useCallback hook)
- update refs from class to function syntax
- any other class component logic to function component
- and ensure no regressions occur.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by alexxxwork** [comment] 2023-07-29 04:19
I would love to work on this issue

**Comment by reinesarchisorte** [comment] 2023-07-29 04:27
Can I work this one?

**Comment by priyankrawat** [comment] 2023-07-29 04:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migration of [src/components/SwipeableView/index.native.js](https://github.com/Expensify/App/blob/main/src/components/SwipeableView/index.native.js) to the function component.

### What is the root cause of that problem?
No root cause, just need to migrate class component to function component.

### What changes do you think we should make in order to solve the problem?
We can perform the following steps-
1. Remove the class declaration and constructor as function components don't have constructors.
2. Use the useRef hook to create the oldYRef and replace the this.oldY usage.
3. Replace any instance methods with regular functions within the function component.
4. Utilize the PanResponder.create() function directly in the function component to create the panResponder.
5. Update the prop access to use direct variable references.
6. Finally make sure there is no regression.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Shampinon** [comment] 2023-07-29 05:03
Proposal

```

const minimumPixelDistance = CONST.COMPOSER_MAX_HEIGHT;

export const SwipeableView = (props) => {

   const oldYRef = useRef(0);
  
   const panResponder = useMemo(() => {
     return PanResponder.create({
            // The PanResponder gets focus only when the y-axis movement is over minimumPixelDistance
            // & swip direction is downwards
            onMoveShouldSetPanResponderCapture: (_event, gestureState) => {                
                if (gestureState.dy -  oldYRef.current> 0 && gestureState.dy > minimumPixelDistance) {
                    return true;
                }
                oldYRef.current= gestureState.dy;
            },

            // Calls the callback when the swipe down is released; after the completion of the gesture
            onPanResponderRelease: this.props.onSwipeDown,
        })
   })
   return (<View {...panResponder.panHandlers}>{props.children</View>);
}
```

**Comment by abdulrahuman5196** [comment] 2023-07-31 11:46
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-07-31 13:18
Looking at dibs after Help Wanted label applied. @rayane-djouah and @huzaifa-99  both already have migration PR in works. So approving @ojasjadhav2 proposal here https://github.com/Expensify/App/issues/16203#issuecomment-1656532781

🎀 👀 🎀
C+ Reviewed

cc: @tjferriss

**Comment by ojasjadhav2** [comment] 2023-07-31 13:28
@abdulrahuman5196 thanks for the review, the PR will be ready within few hours.

**Comment by tjferriss** [comment] 2023-08-09 05:08
PR is awaiting @abdulrahuman5196 review

**Comment by tjferriss** [comment] 2023-08-15 22:45
PR review is ongoing

**Comment by abdulrahuman5196** [comment] 2023-08-28 09:20
@tjferriss 
Melvin didn't auto-update this issue for payment - Change deployed to prod on 24 Aug. This should be eligible for payment on 31 Aug

**Comment by MonilBhavsar** [comment] 2023-09-01 11:13
@tjferriss 👋 can we please issue payment here

**Comment by abdulrahuman5196** [comment] 2023-09-11 20:14
Pinged @tjferriss in slack

**Comment by tjferriss** [comment] 2023-09-12 16:37
I'm sorry for the delay. I'll move this to Daily.

@abdulrahuman5196 I just processed your payment in Upworks. 

@ojasjadhav2 can you please apply to the job here: https://www.upwork.com/jobs/~01f07496805b01d288

**Comment by MonilBhavsar** [comment] 2023-09-15 11:35
Payment in progress

**Comment by tjferriss** [comment] 2023-09-16 22:05
The offer has been sent. Once accepted I can process payment and we can close this out.

**Comment by tjferriss** [comment] 2023-09-18 03:39
@ojasjadhav2 payment has been made.

**Closed by tjferriss** 2023-09-18 03:39 UTC
Labels: External, Engineering, Daily, NewFeature, Awaiting Payment
