### ISSUE TITLE
[HOLD App PR#12181] [$1000] [BUG] Pay with Expensify is NOT selecting ACH automatically 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#12004] opened 2022-10-19 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login 
2. Set your default payment method in Settings > Payment
3. Get IOU from another user
4. Click Pay in chat 
5. Note the 

## Expected Result:
If user has Bank account setup, we should not be asking again for the new payment 

## Actual Result:
Pay with Expensify is NOT selecting ACH automatically 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="369" alt="image - 2022-10-19T155743 782" src="https://user-images.githubusercontent.com/43995119/196791707-d5a884cd-74a0-4046-96c4-a7f2d1f73de9.png">

<img width="363" alt="image - 2022-10-19T155919 500" src="https://user-images.githubusercontent.com/43995119/196791790-c4433c48-c9c4-450a-81ed-c16f57f653a1.png">

https://user-images.githubusercontent.com/43995119/196793186-54354593-f56f-420b-8862-82cfb85261f0.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664998800299199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment] 2022-10-19 20:12
@ntrepanier can you please prioritize this one, as it was initially missed by mistake (in our bug reporting flow)? Refer to the slack thread above for context.

**Comment by michaelhaxhiu** [comment] 2022-10-19 22:15
Note for the C+ that gets assigned, this GH should include a Root Cause Analysis (RCA) investigation since it's clearly a regression.

**Comment by ntrepanier** [comment] 2022-10-25 22:38
Sorry. It assigned while I was OOO. On it.

**Comment by ntrepanier** [comment] 2022-10-25 22:55
@johnmlee101 Can you help me determine if this would be external or internal?

**Comment by johnmlee101** [comment] 2022-10-26 13:30
```
{triggerKYCFlow => (
```
seems to be self-referencial https://github.com/Expensify/App/blob/62394cca18424fafe09c046fa63199d98696cc49/src/components/SettlementButton.js#L89

I'm a bit confused, but I'm pretty sure this is external so marking it

**Comment by smrutiparida** [comment] 2022-10-27 05:08
@mvtglobally  The bank account added is still not a default account as I can see from the screenshot attached. Underlined below.

<img width="217" alt="Screen Shot 2022-10-27 at 10 33 00" src="https://user-images.githubusercontent.com/5945400/198196500-a781c8ad-7c04-445b-9a05-b0b791120b5b.png">

As an external developer though I have not reproduced the steps but from the code it seems evident that though bank account is found, the isDefaultCredit() is returning false as the account is not a default account to receive payment. 

<img width="667" alt="Screen Shot 2022-10-27 at 10 36 35" src="https://user-images.githubusercontent.com/5945400/198196739-bfa4b837-6e8e-46fa-8e1c-7450c29a8a5a.png">

May I hence suggest to make the account default and see one more. I hope that is what is the expected result.

**Comment by puneetlath** [comment] 2022-10-28 17:14
@smrutiparida the issue exists even when a default payment method is set. Here's an example from my account: 
<img width="362" alt="Screen Shot 2022-10-28 at 1 12 45 PM" src="https://user-images.githubusercontent.com/1371996/19869458

<img width="355" alt="Screen Shot 2022-10-28 at 1 12 54 PM" src="https://user-images.githubusercontent.com/1371996/198694604-75246e6b-a7a5-4502-aef3-f3e46f5cd321.png">
2-1c17b754-6842-4bfb-8a74-e3b054c3832e.png">

I have a default payment method set, but it's still asking me how I want to pay when I click "pay with Expensify". If I choose bank account, it takes me to the add a bank account page. So in some way, this page is not registering that I already have a bank account set.

**Comment by puneetlath** [comment] 2022-10-31 19:20
@ntrepanier let's go ahead and double this one.

**Comment by smrutiparida** [comment] 2022-11-02 08:47
@puneetlath @mvtglobally can you help me with an expensify account or are there any dummy savings account you can share me with to reproduce these steps

**Comment by puneetlath** [comment] 2022-11-02 22:00
@smrutiparida you should be able to follow these steps to set up a bank account: https://github.com/Expensify/App/issues/11512#issuecomment-1300561586

**Comment by puneetlath** [comment] 2022-11-03 15:27
Doubled to $1000. 

Job post is here: https://www.upwork.com/jobs/~01744f6f4e5bb3bfe4

**Comment by thomas-coldwell** [comment] 2022-11-07 13:23
Trying to reproduce this issue, but unable to add a bank account as the default payment method - getting the following 404 output in console when I attempt it:
`Finished API request - {"command":"MakeDefaultPaymentMethod","jsonCode":404,"requestID":"76665b147b9f7505-SJC"}`

**Comment by MariaHCD** [comment] 2022-11-08 12:16
Just a heads up here, I actually have the fix for this included in this PR: https://github.com/Expensify/App/pull/12181

[bankAccount.isDefaultCredit()](https://github.com/Expensify/App/blob/91acada3b65af8c465febe6853bcc7d37995f0f4/src/libs/models/BankAccount.js#L149-L156) is currently returning false because the `this.json.defaultCredit` property has now moved to ` this.json.accountData.defaultCredit` as part of https://github.com/Expensify/App/pull/10447

**Comment by mountiny** [comment] 2022-11-08 13:18
Updated this issue to reflect it is internal. Sorry for the confusion. It is easy to overlook that some issue overlap and miss this. Hopefully this issue will be resolved. with the aforementioned PR.

**Comment by puneetlath** [comment] 2022-11-08 19:08
Ok cool, good to know. Thanks @mountiny and @MariaHCD!

**Comment by puneetlath** [comment] 2022-11-09 21:15
@MariaHCD would you be able to help me out with figuring out which PR caused the bug?

**Comment by MariaHCD** [comment] 2022-11-10 06:41
@puneetlath It was due to this backend change: https://github.com/Expensify/Web-Expensify/pull/34592

The format of the bank account data in Onyx changed but the corresponding [model](https://github.com/Expensify/App/blob/main/src/libs/models/BankAccount.js) in the App was not. cc: @Justicea83 

There was also a RCA [here](https://github.com/Expensify/Expensify/issues/234321) but we didn't catch this particular bug because features related to the Expensify wallet are not being QA'd right now. That's going to change with the completion of https://github.com/Expensify/Expensify/issues/232687

**Comment by puneetlath** [comment] 2022-11-14 16:14
Ok awesome, thanks for the info @MariaHCD. 

And just checking, this is still on hold, is that right? If so, mind linking what we are holding for? Thanks!

**Comment by mountiny** [comment] 2022-11-14 16:25
I think Maria is ooo til Friday so stepping in, from the previous comments this is on hold for https://github.com/Expensify/App/pull/12181

It is in staging now so we should be bale to retest there, but we can wait for another deploy I assume

**Comment by mountiny** [comment] 2022-11-14 16:25
I have read and reviewed this Project Manager Application!

**Comment by puneetlath** [comment] 2022-11-14 20:56
Just tested on staging and looks like it's working so I think we're good to go here. Thanks @MariaHCD!

**Closed by puneetlath** 2022-11-14 20:56 UTC
Labels: Engineering, Daily, Bug

**Comment by mountiny** [comment] 2022-11-14 21:56
> I have read and reviewed this Manager Application!

Oops, luckily i dont have that chore. Wondering if it created some bugbot issue 🤔
