### ISSUE TITLE
[$500] Request money - Distance request money is not deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32075] opened 2023-11-27 23:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap request money---Distance
4. Enter start and finish waypoints
5. Tap next
6. Select a Workspace
7. Tap request
8. Tap distance request created to open distance request detail page
9. Tap receipt
10. Tap 3 dots on top right
11. Tap delete receipt

## Expected Result:
When user taps delete receipt, the receipt must be deleted

## Actual Result:
In distance request, user taps delete receipt but the receipt reappears again and not deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/32adf2d8-9629-4ea0-af5c-afa1602beb82

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01968e0702cd968607</li>
        <li>Upwork Job ID: 1729283943547236352</li>
        <li>Last Price Increase: 2023-11-27</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2023-11-27 23:46
This is a dupe of https://github.com/Expensify/App/issues/29684

**Closed by thienlnam** 2023-11-27 23:46 UTC
Labels: External, Daily, Help Wanted, Bug
