### ISSUE TITLE
[HOLD for payment 2023-12-29] Android - Distance - Location permission prompt reappears after declining it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32121] opened 2023-11-28 13:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**
**Issue found when executing PR** https://github.com/Expensify/App/pull/30506

## Action Performed:
Precondition:
- The device used is a Samsung device with Android 12.
- App location permission is reset.

1. Launch New Expensify app.
2. Tap + > Request money > Distance.
3. Don't allow location access.
4. Wait for a while.

## Expected Result:
Location permission prompt will not reappear.

## Actual Result:
Location permission prompt appears again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f95abfca-e88e-4c0c-a000-5379d9f22893

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment] 2023-11-28 14:36
Pinged @neil-marcellini [here in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1701182180979399?thread_ts=1701179900.197909&cid=C01GTK53T8Q) since he added this feature

**Comment by flodnv** [comment] 2023-11-28 17:38
Reassigning to @thienlnam as per the Slack discussion

**Comment by thienlnam** [comment] 2023-11-28 18:49
@MaciejSWM is going to be looking into this - likely will get around to it tommorow

**Comment by MaciejSWM** [comment] 2023-11-28 19:03
@thienlnam a draft PR created.

It’s a draft so far. Let me highlight that I didn’t try to replicate the real issue, I only presented a possible solution to what I think might be the issue. Feel free to continue exploring based on my PR and present the final solution if this bug is urgent, or let me know if I should investigate and present the final fix tomorrow

**Comment by thienlnam** [comment] 2023-12-05 18:01
@MaciejSWM Have you had a chance to get back to this yet?

**Comment by thienlnam** [comment] 2023-12-08 23:16
Bump @MaciejSWM

**Comment by thienlnam** [comment] 2023-12-12 00:35
Pinged in https://expensify.slack.com/archives/C04878MDF34/p1702331990995889

**Comment by MaciejSWM** [comment] 2023-12-15 12:01
Reproduced on physical Android. The exact issue presented above is not reproducible, only after some minor changes in the code. What is reproducible though is that when I land on `Distance` tab and deny access, then go to other tab and then back to `Distance`, then I get asked for the second time. Fixing both those issues with one change. PR soon.

**Comment by MaciejSWM** [comment] 2023-12-15 14:36
@thienlnam PR is ready for review

**Comment by thienlnam** [comment] 2024-01-02 19:47
Assigning s77rt for C+ review payment

**Comment by thienlnam** [comment] 2024-01-02 19:48
Here's the PR https://github.com/Expensify/App/pull/33157

We just need a payment to C+ s77rt for reviewing
The contributor that handled the changes is from SWM

**Comment by isabelastisser** [comment] 2024-01-03 17:17
@s77rt I sent you an offer in Upwork.

All set!

**Closed by isabelastisser** 2024-01-03 17:17 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug

**Comment by s77rt** [comment] 2024-01-03 18:38
@isabelastisser Accepted! I think the payment due here is $500
