### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Chat does not scroll to the last message when a new message received

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43600] opened 2024-06-12 18:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:**

## Action Performed:
1. Go to a report with lots of messages
2. Send a message to user B

## Expected Result:
For user B the chat scrolls to the last message received
## Actual Result:
Does not scroll 
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/f07a9a7a-c575-4992-b10a-864156649506

https://github.com/Expensify/App/assets/38435837/90731ab5-19e0-45d5-ae82-221e6d29640f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0178751bd086a2062a</li>
        <li>Upwork Job ID: 1802672136974977044</li>
        <li>Last Price Increase: 2024-06-17</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 102816257</li>
<li>tsa321 | Contributor | 102816260</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by tsa321** [comment] 2024-06-16 06:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat does not scroll to the last message when a new message received

### What is the root cause of that problem?

When user receive new message, the pushJSON data contains onyx update for report and the new reportAction.
The report onyx data will update `lastVisibleAcitonCreated` and reportAction will add new latest reportAction.
In here:

https://github.com/Expensify/App/blob/a5d0c4df41c72a56f316c2d8eac7616e2e4224a1/src/pages/home/report/ReportActionsView.js#L215

when onyx update on report data the `hasNewestReportAction` will be false because the reportActions isn't updated yet, then the onyx update reportActions

### What changes do you think we should make in order to solve the problem?

We could use `useMemo` to avoid unnecessary value changes on `hasNewestReportAction` when the onyx pushJSON data isn't fully merged yet.

In [here](https://github.com/Expensify/App/blob/a5d0c4df41c72a56f316c2d8eac7616e2e4224a1/src/pages/home/report/ReportActionsView.js#L215), the code could be:

```javascript
const hasNewestReportAction = useMemo(() => lodashGet(reportActions[0], 'created') === props.report.lastVisibleActionCreated, [allReportActions.length]);
```
So when new report action is updated, the `shouldEnableAutoScroll` that depend on `hasNewestReportAction` will be correct and the List will scroll.

**Comment by s77rt** [comment] 2024-06-17 22:56
I'm not able to reproduce the bug. @tsa321 Is this still reproducible for you?


https://github.com/Expensify/App/assets/16493223/92fc0371-9a7b-4961-b40c-a811dfec323c

**Comment by tsa321** [comment] 2024-06-17 23:08
@s77rt yes, I can still reprdouce it. You must scroll up to 1 or 2 message above before receiving new message.


https://github.com/Expensify/App/assets/114975543/46ac8201-3a64-41b1-8884-3aaac202af79

**Comment by s77rt** [comment] 2024-06-19 00:10
@tsa321 I'm able to reproduce now. Regarding your RCA:

> the mvcpAutoscrollToTopThreshold value used in here isn't the latest mvcpAutoscrollToTopThreshold. the value is still undefined because of the update from report onyx data and hasn't updated after reportAction onyx merged. So it won't scroll

After testing the latest rendered value is 250 but this is still not scrolling. Can you please investigate this more?


https://github.com/Expensify/App/assets/16493223/19d32dd2-9d73-45c9-badd-27ac3e01709d

**Comment by tsa321** [comment] 2024-06-19 02:54
@s77rt you must log above this line:

https://github.com/Expensify/App/blob/f8387958061623d2a3d0f7fe03597306458f0c1c/src/components/FlatList/index.tsx#L104

using `console.log({delta, mvcpAutoscrollToTopThreshold})`. And notice when the delta value is above 0, the mvcpAutoscrollToTopThreshold is undefined:


https://github.com/Expensify/App/assets/114975543/7ad9bf09-a739-43cd-afa4-7a7223a49497


I have [updated](https://github.com/Expensify/App/issues/43600#issuecomment-2171084196) my proposal on last paragraph of RCA .

**Comment by s77rt** [comment] 2024-06-19 20:40
@tsa321 `hasNewestReportAction` and `mvcpAutoscrollToTopThreshold` are being updated at the same time. The bug is that the value that we end up using in `adjustForMaintainVisibleContentPosition` is outdated even though `mvcpAutoscrollToTopThreshold` is added as a dependency.

<img width="617" alt="Screenshot 2024-06-19 at 9 30 45 PM" src="https://github.com/Expensify/App/assets/16493223/f72d9d89-bc3e-4499-98f8-b66f9e8c4aea">

https://github.com/Expensify/App/assets/16493223/e7f35389-04b5-4fcb-815e-0b1b006efeec

**Comment by s77rt** [comment] 2024-06-19 20:45
Adding to ^ I'm seeing that `setupMutationObserver` is getting called unexpectedly (or too early)

<img width="623" alt="Screenshot 2024-06-19 at 9 45 21 PM" src="https://github.com/Expensify/App/assets/16493223/70835b3a-db36-4767-865a-271b50feefea">

https://github.com/Expensify/App/assets/16493223/f347b498-47d0-4452-a99b-f3e737cca805

**Comment by tsa321** [comment] 2024-06-20 02:50
@s77rt in here:

https://github.com/Expensify/App/blob/a4a1b2001232d993cdb8a20456aa16b324565ad0/src/components/FlatList/index.tsx#L148-L156

When `mvcpAutoscrollToTopThreshold` changes, the `setupMutationObserver` will changes and will be executed by this useEffect.
This is because: `setupMutationObserver` depend on `adjustForMaintainVisibleContentPosition` which is depend on `mvcpAutoscrollToTopThreshold`. (you can confirm this by removing `mvcpAutoscrollToTopThreshold` dependency in `adjustForMaintainVisibleContentPosition`, the `setupMutationObserver` won't be triggered when new message coming/mvcpAutoscrollToTopThreshold changes). 

So what you say about setupMutationObserver on:

> I'm seeing that setupMutationObserver is getting called unexpectedly (or too early)

It is not too early, it is because of first value change of `mvcpAutoscrollToTopThreshold` from 250 to undefined,  setupMutationObserver will be triggered and will create new MutationObserver.

When new reportAction merged by onyx, (mvcpAutoscrollToTopThreshold changes from undefined to 250) the `setupMutationObserver` will be executed again because value mvcpAutoscrollToTopThreshold changes from undefined to 250. The creation and disconnection of MutationObserver because of mvcpAutoscrollToTopThreshold value changes will disturb the detection of content change in the list.

So the simplest fix in this issue is to prevent creating new subscriber when  mvcpAutoscrollToTopThreshold value changes.
In here:

https://github.com/Expensify/App/blob/a4a1b2001232d993cdb8a20456aa16b324565ad0/src/components/FlatList/index.tsx#L112

We remove `adjustForMaintainVisibleContentPosition` dependency on `mvcpAutoscrollToTopThreshold`. Then use ref of the `mvcpAutoscrollToTopThreshold` inside adjustForMaintainVisibleContentPosition.

**Comment by s77rt** [comment] 2024-06-20 17:25
@tsa321 Makes sense! The solution looks good to me

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/43600#issuecomment-2171084196)

**Comment by tsa321** [comment] 2024-06-21 07:24
@s77rt PR is ready...

**Comment by mountiny** [comment] 2024-06-27 17:44
Can we retest again in a it to verify this is fixed everywhere based on https://github.com/Expensify/App/pull/44132#issuecomment-2191884485 thanks!

**Comment by s77rt** [comment] 2024-06-27 22:11
@tsa321 This actually seems broken on `main`. Can you check from your side?

**Comment by tsa321** [comment] 2024-06-27 23:00
@s77rt you are right. it is broken in main. I am investigating it

**Comment by tsa321** [comment] 2024-06-27 23:33
@s77rt Early investigation: after `setupMutationObserver` is called (creating the `mutationObserver`), the `mutationObserver` eventually gets disconnected here:

https://github.com/Expensify/App/blob/27a8d0a6d88698e7d2cc6d42692abfbe7a8f6b76/src/components/FlatList/index.tsx#L176-L181

I will further investigate why it is currently behaving that way.

**Comment by s77rt** [comment] 2024-06-28 15:46
@tsa321 Any idea on which PR broke this? It's seems to be a deploy blocker as this works on staging

**Comment by tsa321** [comment] 2024-06-28 16:22
@s77rt Currently, I am not with my computer, but I am guessing that the PR causing the issue is https://github.com/Expensify/App/pull/42592 
For the comment linking should also check on https://github.com/Expensify/App/pull/44412

**Comment by s77rt** [comment] 2024-06-29 21:27
@tsa321 I see, this is related to `React.StrictMode` which makes the bug dev only. This is a regression from that PR then.

**Comment by s77rt** [comment] 2024-07-07 13:59
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/32098
- The offending PR has been commented on: https://github.com/Expensify/App/pull/32098#discussion_r1667696235
- A discussion in #expensify-bugs has been started: Not needed. Unique bug
- Determine if we should create a regression test for this bug: I don't think this requires a test, it could cause false positives as the auto scroll is supposed to happen only if the scroll position is below a certain threshold

**Comment by bfitzexpensify** [comment] 2024-07-10 18:55
Payments complete. Closing this one out.

**Closed by bfitzexpensify** 2024-07-10 18:55 UTC
Labels: External, Daily, Awaiting Payment, Bug
