### ISSUE TITLE
[$500] Room-Scrolled up members list scrolled down in admins account everytime message received

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31110] opened 2023-11-09 11:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on a room with many members
3. Tap on header
4. Tap members
5. Scroll up the page and note last contact
6. Go to https://staging.new.expensify.com/
in other device
7. Login in as member who is shown in last in room members list while scrolled up
8. Tap on room
9. Send a message
10. Note - Admin room members list page scrolled down everytime user sends a message
11. Navigate back to Room and note new message received
12. Again tap header--Members
13. Scroll up the page
14. From members account, as mentioned in step 9 again send a message
15. Note - Admin room members list page now got scrolled down
16. Navigate back to room and verify new message received

## Expected Result:
Scrolled up members list must not scrolled down in admins account when message is sent from invited user account.

## Actual Result:
Scrolled up members list scrolled down in admins account everytime message is sent from invited user account.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/ce9310fd-f628-4f0f-a0b0-4728d0bd2cd0

https://github.com/Expensify/App/assets/115492554/d25249a5-e98e-42bb-a67f-22cc7cb547be

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01198909fcc1f7f42d</li>
        <li>Upwork Job ID: 1722573758151155712</li>
        <li>Last Price Increase: 2024-03-28</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-11-09 12:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Scrolled up members list is scrolled down every time message received

### What is the root cause of that problem?

When a message is received, [RoomMembersPage](https://github.com/Expensify/App/blob/main/src/pages/RoomMembersPage.js) is re-rendered, and the data is recalculated as you can see below
https://github.com/Expensify/App/blob/9862a3e65393b26184369d312a02e1f7de88b64b/src/pages/RoomMembersPage.js#L243

When section data is changed, we set focus to the first item and scroll to it
https://github.com/Expensify/App/blob/9862a3e65393b26184369d312a02e1f7de88b64b/src/components/SelectionList/BaseSelectionList.js#L340-L351

This is the root cause

### What changes do you think we should make in order to solve the problem?

As mentioned above, we set focus to the first item and scroll to it when section data is changed. This isn't an intended behavior. This was added to focus and scroll to the first item when search(PR https://github.com/Expensify/App/pull/30438 for issue https://github.com/Expensify/App/issues/29080)

This isn't correct. This fix causes the selection list focus and scroll to the first item every time section data changes. We only need to focus and scroll to the first item when sections data is changed by changing search value.

Update the dependency to `[textInputValue]` would fix this issue

<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)

**Comment by sourcecodedeveloper** [comment] 2023-11-09 18:22
Please review [proposal](https://github.com/Expensify/App/issues/31087#issuecomment-1803506915) as the issues 
https://github.com/Expensify/App/issues/31087 and https://github.com/Expensify/App/issues/31110 are related.

**Comment by abdulrahuman5196** [comment] 2023-11-13 08:54
Hi, Will review again today, just back from weekend

**Comment by abdulrahuman5196** [comment] 2023-11-13 18:44
@zanyrenney Multiple contributors pointed this issue as an regression from https://github.com/Expensify/App/issues/29080.

can we put this issue on hold for the same?

**Comment by s-alves10** [comment] 2023-11-15 08:34
@abdulrahuman5196 

This is a general issue of `SelectionList`, not specific to timezone list. I think we can solve the issue here
My solution solves both https://github.com/Expensify/App/issues/29080 and this issue

**Comment by zanyrenney** [comment] 2023-12-22 13:37
Is this still meant to be on hold?

**Comment by abdulrahuman5196** [comment] 2023-12-25 12:04
The linked issue is still being reviewed for proposals

**Comment by zanyrenney** [comment] 2024-01-25 16:23
ON HOLD.

**Comment by zanyrenney** [comment] 2024-02-27 14:22
ON HOLD.

**Comment by zanyrenney** [comment] 2024-04-02 14:29
ON HOLD>

**Comment by zanyrenney** [comment] 2024-04-04 09:56
The related issue is now closed, so I think we are good to take this off hold.

**Comment by zanyrenney** [comment] 2024-04-04 09:57
retesting!

**Comment by zanyrenney** [comment] 2024-04-04 10:33
I cannot reproduce this anymore - good news! 🎉  I will close it out.

**Closed by zanyrenney** 2024-04-04 10:33 UTC
Labels: External, Daily, Help Wanted, Bug
