### ISSUE TITLE
[$1000] The last message is automatically set as unread after sending the money

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13075] opened 2022-11-28 04:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

On hold for https://github.com/Expensify/App/pull/12739

## Action Performed:

1. Go to any chat
2. Click on + icon
3. Click Send money
4. Enter any amount
5. Click Next
6. Click I'll settle up somewhere else

## Expected Result:
The last message is not set as unread

## Actual Result:
The last message is set as unread

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.32-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/204194839-8e901f15-52d6-470f-b7e0-0ebfe7bc7c2f.mov

https://user-images.githubusercontent.com/43996225/204194990-efaea69c-2446-4577-b5d3-073446ca5fab.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669270590893699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~0173d3ffce0cf4db8c
- Upwork Job ID: 1597301252406939648

**Comment by s77rt** [comment] 2022-11-28 11:07
### Proposal
```diff
diff --git a/src/libs/actions/IOU.js b/src/libs/actions/IOU.js
index 9fb462f64b..5cd49f11ff 100644
--- a/src/libs/actions/IOU.js
+++ b/src/libs/actions/IOU.js
@@ -711,6 +711,15 @@ function payIOUReport({
                 return;
             }
 
+            // If reportID is not passed, e.g. we are creating a new iouReport
+            // try to extract the reportID from the server response
+            if (reportID === "0") {
+                const otherReportsIDs = _.keys(_.omit(response.reports, chatReportID));
+                if (otherReportsIDs.length === 1) {
+                    reportID = otherReportsIDs[0];
+                }
+            }
+
             const chatReportStuff = response.reports[chatReportID];
             const iouReportStuff = response.reports[reportID];
             Report.syncChatAndIOUReports(chatReportStuff, iouReportStuff);
```

### Details
1.  **sendMoney**: The passed reportID is `"0"`
https://github.com/Expensify/App/blob/b4f1be977bb4d628ab4b55e4732b2158488dbc82/src/pages/iou/IOUModal.js#L285-L311

2. **payIOUReport**: `iouReportStuff` is `undefined`
https://github.com/Expensify/App/blob/b4f1be977bb4d628ab4b55e4732b2158488dbc82/src/libs/actions/IOU.js#L714-L716

3. **syncChatAndIOUReports**: returns early, and this is exactly the part that is supposed to be executed.
https://github.com/Expensify/App/blob/b4f1be977bb4d628ab4b55e4732b2158488dbc82/src/libs/actions/Report.js#L991-L995

In my proposal, I implemented a `reportID` "extractor" based on the returned server response, so we can carry on normally

**Comment by parasharrajat** [comment] 2022-11-28 19:02
@s77rt Do you mind adding some details and explanations to your proposal?

**Comment by s77rt** [comment] 2022-11-28 19:10
@parasharrajat Sorry, I thought it was clear.

When you send money, the function `sendMoney` is called, and this calls `payIOUReport` which calls `syncChatAndIOUReports`.
`syncChatAndIOUReports` is supposed to (as stated in the name) sync the local stored data in onyx, but it's returning early due to `iouReport` being `undefined`. `iouReport` is `undefined` because `response.reports[reportID]` does not exist where `reportID` is equal `'0'`.

So, the root issue is due to the `reportID` being unknown (set to '0'). In my proposal we extract the reportID from the server response, since the server returns two reports, one of them is the chatID and the other must be the reportID

**Comment by s77rt** [comment] 2022-11-28 19:14
Maybe the title is not clear or misleading.
The last message (before sending the money) is untouched, it will stay marked as read.
The new message (the sent payment report) is marked as unread
You can confirm by locating the NEW marker in the video, what's below it is the unread part.

**Comment by parasharrajat** [comment] 2022-11-28 19:16
Thanks for the details. 

We are doing [some API refactors](https://expensify.slack.com/archives/C01GTK53T8Q/p1669652735069499) for IOUs. I am not sure what is being changed. If we are getting away from the Deprecated API on IOU, it might be affected. @mountiny Do you think that refactor will affect this issue?

**Comment by parasharrajat** [comment] 2022-11-29 11:45
@mountiny Any thoughts?

**Comment by mountiny** [comment] 2022-11-29 11:56
@parasharrajat @s77rt Sorry for this but yeah I agree this should be on hold for the refactor, we have PRs actively being worked on this behaviour should be update there as we move to optimistic actions https://github.com/Expensify/App/pull/12739

I will put this on hold for that

**Comment by NikkiWines** [comment] 2022-12-01 20:57
on hold, not overdue. Dropping to weekly until this is back off hold.

**Comment by JmillsExpensify** [comment] 2022-12-08 04:03
As a heads up, PayIOU should be merged and hit staging by early next week at the latest.

**Comment by NikkiWines** [comment] 2022-12-12 23:33
still on hold for the moment

**Comment by abekkala** [comment] 2022-12-20 13:07
I'm assigning myself as I'm ooo until Jan.
@NikkiWines if you want reapply a BZ when this is off hold you can re-apply the `Bug` label.
Otherwise if this happens to be on hold until the new year I can just take it back!

**Comment by NikkiWines** [comment] 2022-12-20 17:42
With https://github.com/Expensify/App/pull/12739 on prod, I actually think this can go off hold now. Thoughts @vitHoracek @JmillsExpensify?

**Comment by JmillsExpensify** [comment] 2022-12-22 22:59
Agree with Vit. With that in mind, update the hold accordingly.

**Comment by JmillsExpensify** [comment] 2022-12-22 23:00
Also I went ahead and added myself as BZ on this one.

**Comment by JmillsExpensify** [comment] 2022-12-27 19:46
Giving the on-going implementation for sequence numbers, I'm switching out the weekly for monthly. We'll circle back to the outstanding bugs when everything is finished.

**Comment by JmillsExpensify** [comment] 2023-01-11 05:30
Still on hold for sequence numbers. We're getting closer though.

**Comment by JmillsExpensify** [comment] 2023-02-02 15:54
Removing the hold now that sequence numbers are deprecated. I'll run through the testing steps now.

**Comment by JmillsExpensify** [comment] 2023-02-02 16:03
Unable to reproduce this bug now. @adeel0202 can you apply to this Upwork job for reporting? https://www.upwork.com/jobs/~0191216749091fc728

**Comment by JmillsExpensify** [comment] 2023-02-02 16:04
Closing the issue in any case, though we'll still make sure contributor is paid out for reporting an issue we've since fixed.

**Closed by JmillsExpensify** 2023-02-02 16:04 UTC
Labels: External, Monthly, Needs Reproduction, Bug

**Comment by JmillsExpensify** [comment] 2023-02-02 20:51
Sorry I disagree. We did a ton of work to fix this. We just an entire refactor of unreads.

**Comment by JmillsExpensify** [comment] 2023-02-02 20:52
> For example, if there is some issue with a feature, which we deprecated or removed from the app. It does not mean that issue was resolved. Instead issue should be marked invalid.

So building on that, this isn't a case of reported with no action and closed. This is a case of refactoring the core underlying flows that this issue described. And now that we fixed them (approximately two weeks ago), I retested and confirm that those refactors have resolved the issue.

**Comment by JmillsExpensify** [comment] 2023-02-02 20:53
@adeel0202 Fixed.

**Comment by JmillsExpensify** [comment] 2023-02-02 21:03
@parasharrajat That's fair, though if that's the case we should have closed it in the triage stage. Instead if stayed open for months, presumably because we weren't sure if it would be fixed or not. Given that, I still think for this kind of case where we held instead of closed the issue and confirmed the fix, we should pay. Or at the very least, I think that's the case for this specific issue. We can look at everyone individually.

**Comment by JmillsExpensify** [comment] 2023-02-02 21:04
@adeel0202 That's so odd, looks like a bug on the Upwork side, as I can't successfully change the posting now. It says saved but then I go back to confirm and nothing is saved.

**Comment by JmillsExpensify** [comment] 2023-02-02 21:05
Here's a new one: https://www.upwork.com/jobs/~01bd52874afbcf7444

**Comment by JmillsExpensify** [comment] 2023-02-03 04:37
Cool, thanks. Sent you an offer just now.

**Comment by JmillsExpensify** [comment] 2023-02-08 03:01
Oh yeah this is pretty messy. So does this mean the earlier Upwork link worked? I just clicked the most recent link but perhaps that's not the right? Let me check quickly to see if I can hunt down the existing one.

**Comment by JmillsExpensify** [comment] 2023-02-08 03:38
You should be all set now!
