### ISSUE TITLE
[$250] Task - Infinite flickering skeleton loader if the task is marked complete by both users

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41126] opened 2024-04-27 00:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66.5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Account A: Create assign and share a task with account b from the FAB
2. Account B: Open the chat with the task but don't open the task
3. Mark the task complete with both accounts at the same time
4. Account A: Navigate to the task details

## Expected Result:
There shouldn't be any flickering or long skeleton loaders

## Actual Result:
Infinite flickering skeleton loader if the task is marked complete by both users at the same time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/de95ecd5-940d-414b-a35b-6ebae8e8a380

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01158a0b28cee4eefc</li>
        <li>Upwork Job ID: 1785175961792782336</li>
        <li>Last Price Increase: 2024-05-14</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-27 00:57
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-27 00:57
We think that this bug might be related to #vip-vsp

**Comment by jacobkim9881** [comment] 2024-05-02 15:15
Not reproducible for now.

**Comment by kadiealexander** [comment] 2024-05-03 05:58
Asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1714715876390389).

**Comment by kavimuru** [comment] 2024-05-03 13:36
Issue is still reproducible. 

https://github.com/Expensify/App/assets/43996225/6a962a30-7722-4275-9fae-a2ca35e240b0

**Comment by kadiealexander** [comment] 2024-05-06 23:25
Still looking for volunteers!

**Comment by kadiealexander** [comment] 2024-05-10 06:16
Still looking for proposals! I don't think this is high enough priority right now to increase the bounty on.

**Comment by jacobkim9881** [comment] 2024-05-12 13:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When 2 users complete same task at once, skeleton loading loops while the task details on account A.
### What is the root cause of that problem?

<details>
  <summary>One of report actions in task details hasn't been finished and doesn't have `previousReportActionID` because the task is finished already from B user.</summary>

```json
/// This one doesn't have `previousReportActionID`
{"actionName":"TASKCOMPLETED","actorAccountID":16514892,"automatic":false,"avatar":"https://d1wpcgnaa73g0y.cloudfront.net/5827744ff2d088c7b757e1caf1f44133520163d4_128.jpeg","isAttachment":false,"originalMessage":
{"taskReportID":"6534500894507005","type":"TASKCOMPLETED","text":"marked as complete"},"person":[{"style":"strong","text":"Jacob Kim","type":"TEXT"}],
"reportActionID":"6847493605933731035","shouldShow":true,"created":"2024-04-27 16:58:52.591","isFirstItem":false},

/// This one has
{"person":[{"style":"strong","text":"Jacob Kim","type":"TEXT"}],"actorAccountID":16504294,"message":[{"style":"normal","text":"marked as complete","type":"TEXT"}],"originalMessage":{"html":"marked as complete","lastModified":"2024-04-27 16:58:47.914",
"taskReportID":6534500894507005,"title":"Jgj"},"avatar":"https://d1wpcgnaa73g0y.cloudfront.net/40736a868ca6f766573306a0e78e9a4af05a6266_128.jpeg","created":"2024-04-27 16:58:47.914","timestamp":1714237127,"reportActionTimestamp":1714237127914,"automatic":false,
"actionName":"TASKCOMPLETED","shouldShow":true,
"reportActionID":"6209206495004934451","previousReportActionID":"2454485976387404289","lastModified":"2024-04-27 16:58:47.914","actorEmail":"jacobkim9881+15@gmail.com","whisperedToAccountIDs":[],"isAttachment":false,"sequenceNumber":3},

```

</details> The ID is used as a flag here below.

https://github.com/Expensify/App/blob/2a6d63d7f17b1e4fba94f26103f13c6afe294b91/src/libs/ReportActionsUtils.ts#L356

`getContinuousReportActionChain` have the condition. The report action didn't meet conditions for `previousReportActionID` of the task and then other report actions are not added except itself. To reload missed report actions `getOlderActions` API requests are repeated. As a result skeleton loading is repeated. If any unidentified condition isn't meet and then adding indexes is finished too soon without the function's purpose, which returns shorted report action list and which issues skeleton loading.  

> [!NOTE]  
> Currently this function doesn't act properly since `previousReportActionID` doesn't have value `0` to `ReportActionID` from BE. 

### What changes do you think we should make in order to solve the problem?
Since activity of tasks could make report actions without `previousReportActionID`, we should add `isOptimisticAction` in such report actions for conditions working here to `getContinuousReportActionChain` below,

https://github.com/Expensify/App/blob/2a6d63d7f17b1e4fba94f26103f13c6afe294b91/src/libs/ReportActionsUtils.ts#L293-L299

of

https://github.com/Expensify/App/blob/2a6d63d7f17b1e4fba94f26103f13c6afe294b91/src/libs/ReportActionsUtils.ts#L357

For `completeTask` API, `isOptimisticAction` should be added here below,

https://github.com/Expensify/App/blob/2a6d63d7f17b1e4fba94f26103f13c6afe294b91/src/libs/ReportUtils.ts#L4252-L4270

Then report actions not having `previousReportActionID` can be passed in `getContinuousReportActionChain`'s condition, so report actions didn't get cut. As a result `getOlderActions` API  didn't get executed for less report actions.

### What alternative solutions did you explore? (Optional)
Whenever conditions are not meet then this function makes skeleton loading. We shouldn't use `getContinuousReportActionChain`.

**Comment by kadiealexander** [comment] 2024-05-13 06:25
@sobitneupane please review the above!

**Comment by sobitneupane** [comment] 2024-05-15 08:09
Thanks for the proposal @jacobkim9881 

Your proposal looks very convincing. I am yet to test the proposal though, looks like there is some issue in database connection. Were you able to reproduce the issue on Web?
<img width="361" alt="Screenshot 2024-05-15 at 13 53 09" src="https://github.com/Expensify/App/assets/25876548/55cf1626-d825-4845-99dd-66176fdf9e3b">

**Comment by mvtglobally** [comment] 2024-05-16 04:04
Issue is reproducible during KI retests.

https://github.com/Expensify/App/assets/43995119/b9453c8f-4798-4fa3-8ffd-74e35da8b789

**Comment by jacobkim9881** [comment] 2024-05-16 05:38
@sobitneupane Seems there were issues from BE which we couldn't handle! I understood you were yet to test, let me share the proposal on my branch below. 

https://github.com/jacobkim9881/Expensify-App/tree/41126

**Comment by sobitneupane** [comment] 2024-05-19 10:29
Thanks for the patience @jacobkim9881 

Overall, your proposal looks good to me. I have one question, though: should we set isOptimisticAction to null once the action is successful?

**Comment by jacobkim9881** [comment] 2024-05-19 17:33
Thanks for the question @sobitneupane 

 As I expected it revoke skeleton loading because it remains with OptimisticAction to null. But as I tested, the report action was deleted which was successful with isOptimisticAction to null. It also shouldn't have isOptimisticAction to true after it got responded from BE.

**Comment by jacobkim9881** [comment] 2024-05-20 12:26
## Proposal
[Updated](link to proposal)

**Comment by sobitneupane** [comment] 2024-05-21 08:11
Thanks for the update @jacobkim9881 

[Proposal](https://github.com/Expensify/App/issues/41126#issuecomment-2106249359) from @jacobkim9881 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by jacobkim9881** [comment] 2024-05-22 04:05
@sobitneupane Thanks for choosing my proposal.

While testing, my proposal doesn't work now. From BE the redundant optimistic data isn't deleted but responded as successful data without `previousReportActionID` or `isOptimisticAction`. From BE the data should be deleted but responses from BE have been changed.

**Comment by sobitneupane** [comment] 2024-05-22 09:37
@jacobkim9881 I don't think we can expect isOptimisticAction to be returned from BE. It can be handled within the app. I can see `previousReportActionID` in the response. @jacobkim9881 Can you please explain in detail about the issue you are facing?

**Comment by jacobkim9881** [comment] 2024-05-22 13:17
@sobitneupane  We can search to solve the problem in the app. 
The one which has `previousReportActionID` is the one from user B. B clicked to complete the task at first. From user B's screen I also checked there is no A's message to complete the task. It works well.

**Comment by jacobkim9881** [comment] 2024-05-22 14:23
In the user A's screen, there was skeleton loading with my PR. There were 2 responses from 1 completed task. One has `previousReportActionID` from user B but the other doesn't have from user A which should be deleted.

**Comment by sobitneupane** [comment] 2024-05-23 08:46
@jacobkim9881 Can you please share screenshots of the responses?

**Comment by jacobkim9881** [comment] 2024-05-23 09:16
@sobitneupane It was `console.log(sortedReportActions)` from here 

https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/libs/ReportActionsUtils.ts#L334

<img width="1440" alt="스크린샷 2024-05-23 오후 6 06 11" src="https://github.com/Expensify/App/assets/46774300/ac8716c6-35d9-4e5d-b7c5-d33273252901">

**Comment by jacobkim9881** [comment] 2024-05-24 10:28
@sobitneupane Could I add other details for below?

> Overall, your proposal looks good to me. I have one question, though: should we set isOptimisticAction to null once the action is successful?

If we didn't add `isOptimisticAction: null` to successful data, the task completed message is remained in report actions, which will not be shown because it is sorted out by here below,

https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/pages/home/report/ReportActionsList.tsx#L208

for it doesn't have `message` array, 

https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/libs/ReportActionsUtils.ts#L106-L113

<img width="1046" alt="스크린샷 2024-05-24 오후 7 18 48" src="https://github.com/Expensify/App/assets/46774300/0105fd40-7d63-4d22-8ad0-619a2495d109">

**Comment by jacobkim9881** [comment] 2024-05-26 17:30
@sobitneupane 
> @jacobkim9881 Can you please share screenshots of the responses?

Seems my explains needed more details. [Please to check.](https://github.com/Expensify/App/issues/41126#issuecomment-2126625406)

**Comment by sobitneupane** [comment] 2024-05-28 09:39
@jacobkim9881 Thanks for the update.

But I don't fully understand what you are trying to suggest. I assume you are trying to say that we will have issue if we add `isOptimisticAction: null` in successData.

In this [comment](https://github.com/Expensify/App/issues/41126#issuecomment-2126625406), 0th report action is the optimistic action taken by UserA which is blocking other report actions(no previousReportActionID in optimistic action) to go through. If we add `isOptimisticAction: true`, it will pass following condition and will be returned by `getContinuousReportActionChain`

https://github.com/Expensify/App/blob/2a6d63d7f17b1e4fba94f26103f13c6afe294b91/src/libs/ReportActionsUtils.ts#L352-L360

But if we add `isOptimisticAction: null` in `successData`, it will again block the report actions to go through above conditions, right?

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/actions/Task.ts#L325-L335

But, the `completeTask` action taken by User A should fail and should not be successful as the task is already marked complete by User B. But it is returned as successful action by the server. @aldo-expensify Is this the expected behavior?

<img width="302" alt="Screenshot 2024-05-28 at 15 21 12" src="https://github.com/Expensify/App/assets/25876548/ed309466-33f0-47c6-bfd0-a2392472851a">

**Comment by jacobkim9881** [comment] 2024-05-29 19:48
@sobitneupane
> I assume you are trying to say that we will have issue if we add isOptimisticAction: null in successData.

I want to say putting `isOptimisticAction: null` in successData would work well to complete tasks. And it should be added for the report action becomes successData already and added `isOptimisticAction: true` as optimistic report action.

> But if we add isOptimisticAction: null in successData, it will again block the report actions to go through above conditions, right?

In this issue, it'll be blocked because the redundant report action doesn't have `previousReportActionID` from BE or doesn't have `isOptimisticAction`, `pendingAction: add` for as responded as successData.

**Comment by jacobkim9881** [comment] 2024-06-03 09:04
If we only fix the issue from FE only, we can fix the issue with alternative way. Since `completeTask` get the report action with `message: null` which can be official status, we can pass such report action on here below,

https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/libs/ReportActionsUtils.ts#L294-L305

We can add code below,

```js
  if (!currentReportAction.message || !nextReportAction.message) {
       return true;
  }
```

Then report actions w `message: null` will be passed.

**Comment by sobitneupane** [comment] 2024-06-05 09:31
@aldo-expensify Whenever you have a moment, could you please take a look at [this](https://github.com/Expensify/App/issues/41126#issuecomment-2134777101)?

> But, the completeTask action taken by User A should fail and should not be successful as the task is already marked complete by User B. But it is returned as successful action by the server.

**Comment by kadiealexander** [comment] 2024-06-10 00:54
@aldo-expensify bump on this!

**Comment by jacobkim9881** [comment] 2024-06-11 11:45
The issue will be solved [when it gets merged](https://github.com/Expensify/App/pull/41962).

**Comment by aldo-expensify** [comment] 2024-06-11 17:13
It does sounds related, lets  HOLD on that?

**Comment by aldo-expensify** [comment] 2024-06-19 20:01
No overdue, holding.

**Comment by aldo-expensify** [comment] 2024-06-28 21:32
Still on HOLD. I'll be OOO starting from next week for 2 weeks.

**Comment by kadiealexander** [comment] 2024-07-09 05:36
Still on hold.

**Comment by aldo-expensify** [comment] 2024-07-18 01:11
Removing HOLD, https://github.com/Expensify/App/pull/41962 reached production

**Comment by aldo-expensify** [comment] 2024-07-18 01:15
Failed to reproduce:


https://github.com/user-attachments/assets/8b48de35-cf29-40e9-b1fa-38c768492296

Can someone else give it a try?

**Comment by jacobkim9881** [comment] 2024-07-22 05:34
Not reproducible

**Comment by aldo-expensify** [comment] 2024-07-22 19:22
I guess we can close now, thanks @jacobkim9881 for testing and investigating

**Closed by aldo-expensify** 2024-07-22 19:22 UTC
Labels: External, Weekly, Bug
