### ISSUE TITLE
[HOLD for payment 2022-10-20] [$500] Mac/Safari - request money flow: user display list is blank or cut off reported by @thesahindia

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10608] opened 2022-08-26 20:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging.new.expensify.com via Mac/Safari
2. Press green + icon and click on `Request money`
3. Enter money amount and click on the next button
4. Observe users list, see it is blank or the image is cut off 
5. Repeat 2-3 with different browsers Zoom levels (cmd + / cmd -)

## Expected Result:
The user should be able to use money request flow without any display  issues

## Actual Result:
Users list in money request flow do not fit correctly or is blank in some zoom levels

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.92.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186982733-92ff0624-0700-4687-b457-3dfa60b6ed79.mp4

https://user-images.githubusercontent.com/31225194/190689162-09fce78a-8be5-456e-99f3-511cda12ac30.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment] 2022-09-01 08:50
Was able to repro on Safari, this is buggy and should be fixed. Posted to Upwork: https://www.upwork.com/jobs/~013abb27ed5da559c8

**Comment by wildan-m** [comment] 2022-09-08 08:56
I see a blank page when clicking Next after filling in the money amount.

Someone also experiences the same:

https://expensify.slack.com/archives/C01GTK53T8Q/p1661708190183589

This bug will be dependent on the above bug.

**Comment by thesahindia** [comment] 2022-09-08 09:15
Yeah the page is blank at safari, I have tested this on iPad and mac

**Comment by oogushikun** [comment] 2022-09-12 11:57
Proposal

Root cause
The issue here is Safari ignores element that have overflow: hidden when said element is transitioning. In this case, it's the sectionList that's being rendered inside the IOUParticipantsPage:

https://github.com/Expensify/App/blob/0825a4e001df6ac5b19ac89ca3ab216ee4450400/src/pages/iou/IOUModal.js#L422-L433

Solution

Adding the following styles to the component.

```diff
    <AnimatedStep
-      style={[styles.flex1]}
+      style={[styles.flex1,{position: 'fixed', width:"100%"}]}
       direction={this.getDirection()}
    >
```

No breaking changes observed with said change.

https://user-images.githubusercontent.com/23414844/189647138-79582391-eb24-48fc-9070-3229e2c55402.mov


https://user-images.githubusercontent.com/23414844/189647231-7cafbb50-506f-4ade-ae70-7cf8cbdadce6.mov


https://user-images.githubusercontent.com/23414844/189647289-b991482d-cfc9-4c10-8002-0c865792e38a.mov

**Comment by mvtglobally** [comment] 2022-09-13 04:34
Issue not reproducible during KI retests. (First week)

**Comment by stephanieelliott** [comment] 2022-09-13 18:54
I'm still able to produce this in Safari on prod. I'm not able to repro the blank page described in the linked Slack post though 🤔, I'm using Mac/Safari 

@wildan-m, are you suggesting that this issue and the blank screen issue probably have the same cause? Or are you just saying that the blank screen issue will need to be solved first?


<img width="430" alt="image" src="https://user-images.githubusercontent.com/31225194/189986335-36ec4da8-7a3c-4e91-922d-ab61d2725113.png">

**Comment by mananjadhav** [comment] 2022-09-13 19:04
I feel the blank page and the zoom levels are related. Here's a screencast from my Mac Safari browser on staging.


https://user-images.githubusercontent.com/3069065/189988051-e12fbc41-a927-4c98-bf0e-8014a9be1468.mp4

**Comment by wildan-m** [comment] 2022-09-13 22:06
@stephanieelliott 
Have you tried it in Staging? I think we have to resolve the blank page issue first.

**Comment by stephanieelliott** [comment] 2022-09-16 16:53
Weird, I'm still not able to repro the blank screen behavior -- tried both Chrome and Safari on staging and prod, multiple zoom levels. Either way, I agree these are very likely related! I updated this issue to include both the blank screen and the distorted display and raised it to $500.

**Comment by oogushikun** [comment] 2022-09-17 16:19
PROPOSAL

Root Cause
In the AnimatedStep component, the component being animated does not stay in view in Safari if said components children is a sectionList. In this case it happens during the participants selection step. Not sure why exactly it's failing but I found a similar issue on the react-animated repo https://github.com/oblador/react-native-animatable/issues/262. 

Solution
Applying the animation directly rather than passing the animation type i.e "slideInright" fixes the issue. You can also notice that the animation looks smoother(videos attached to show the comparison) which I suggest fixes this issue too https://github.com/Expensify/App/issues/10610

Changes made are in the AnimatedStep component that is currently only being used in the IOUModal page.

```diff
diff --git a/src/components/AnimatedStep.js b/src/components/AnimatedStep.js
index b876f9c26..9cae58af6 100644
--- a/src/components/AnimatedStep.js
+++ b/src/components/AnimatedStep.js
@@ -21,13 +21,25 @@ const defaultProps = {
 };
 
 const AnimatedStep = (props) => {
+    function makeSlideInTranslation(translationType, fromValue) {
+        return {
+          from: {
+            [translationType]: fromValue,
+          },
+          to: {
+            [translationType]: 0,
+          },
+        };
+    }
     function getAnimationStyle(direction) {
         let animationStyle;
+        const slideInLeft = makeSlideInTranslation('translateX', -100); //100 is the default value used by react-animatable
+        const slideInRight = makeSlideInTranslation('translateX', 100);
 
         if (direction === 'in') {
-            animationStyle = 'slideInRight';
+            animationStyle = slideInRight;
         } else if (direction === 'out') {
-            animationStyle = 'slideInLeft';
+            animationStyle = slideInLeft;
         }
         return animationStyle;
     }
```

Test

https://user-images.githubusercontent.com/23414844/190865816-6b4da369-44d6-4276-8c1f-860c45b8dfc8.mov


https://user-images.githubusercontent.com/23414844/190865860-f698e3f3-1f25-4c7d-872e-bdab3d012bef.mov


https://user-images.githubusercontent.com/23414844/190865924-2c701d75-6da2-460a-b840-66b09306eeb8.mov


https://user-images.githubusercontent.com/23414844/190866227-81f225f8-0206-4d84-844e-f0712f3cbb55.mp4

**Comment by mananjadhav** [comment] 2022-09-20 04:14
Missed the proposal here from @oogushikun. Please allow me a day to confirm. I am trying to check if this is a regression because this should've been working earlier!

**Comment by mvtglobally** [comment] 2022-09-20 05:06
Issue not reproducible during KI retests. (Second week)

**Comment by stephanieelliott** [comment] 2022-09-22 17:33
Hey @mananjadhav have you had a chance to review this one?

**Comment by mananjadhav** [comment] 2022-09-24 23:31
I couldn't find any regression. @oogushikun  I did check your proposal and this is exactly what `react-native-animatable` uses underneath for `sliderInRight` and `sliderInLeft`. Could you explain why is it not working in the library and why the same function works when used in `AnimatedStep` component?

**Comment by mvtglobally** [comment] 2022-09-27 05:12
Issue not reproducible during KI retests. (Third week)

**Comment by mananjadhav** [comment] 2022-09-27 05:15
@mvtglobally I am not sure when you say its not reproducible. Screenshots I took from staging few mins back.


<img width="300" alt="Screenshot 2022-09-27 at 10 43 59 AM" src="https://user-images.githubusercontent.com/3069065/192437839-2d5fd4b7-0364-4b88-a131-5a2c6748d756.png">

<img width="400" alt="Screenshot 2022-09-27 at 10 44 13 AM" src="https://user-images.githubusercontent.com/3069065/192437830-6299ce51-8baa-4d63-afd2-fefcffbc983a.png">

**Comment by oogushikun** [comment] 2022-10-02 13:04
Apologies @mananjadhav for the late reply. As you've mentioned the values I passed in my previous comment are defined by react-native-animatable. The reason it's not working is because currently when passing the animation type as a string i.e 'slideInRight', the transition value is **1920** instead of **100**.

https://user-images.githubusercontent.com/23414844/193454744-5b3d3ff1-3514-4511-b82e-edd83fddd871.mov

This is being caused by react-native-modal which also uses react-native-animatable as a depedency. React-native-modal declares it's own [custom animations](https://github.com/oblador/react-native-animatable#custom-animations) like this:
![image](https://user-images.githubusercontent.com/23414844/193455114-bdfbc6c6-3635-4634-9b4c-c9f457d95e96.png)
As you can see the transition value being passed is using the devices window width, hence why we're getting 1920 i.e the window width on my monitor. Hope that clarifies things 😅

**Comment by mananjadhav** [comment] 2022-10-03 11:07
Thanks for the clarification @oogushikun. Yes you're right that the transitions are getting overwritten with `react-native-modal`.

@oogushikun's proposal here https://github.com/Expensify/App/issues/10608#issuecomment-1250098928 looks fine to be. Just that I would want to move `100` to `CONST.js`

🎀 👀 🎀 
C+ reviewed

@AndrewGable Up for your review.

**Comment by oogushikun** [comment] 2022-10-04 14:43
Applied on upwork. It'll take me a day(after being approved) to create the PR.
Thanks 😃

**Comment by mananjadhav** [comment] 2022-10-10 16:39
@oogushikun Do you have an update for us on the PR?

**Comment by oogushikun** [comment] 2022-10-10 16:47
Hi @mananjadhav. I'm still waiting to be approved for the job on upwork.

**Comment by mananjadhav** [comment] 2022-10-10 16:52
Ohh okay, @stephanieelliott Can you please approve the hire on Upwork?

fyi, @oogushikun it is okay for you to wait for the Upwork hire, but if you're assigned a job here on Github like [this](https://github.com/Expensify/App/issues/10608#issuecomment-1266339780), it is as goo as being hired on Upwork.

**Comment by oogushikun** [comment] 2022-10-10 17:01
my bad on my part then, I figured I'm only supposed to create the PR once you've been approved. Let me create it and I'll be update you shortly.

**Comment by stephanieelliott** [comment] 2022-10-10 20:29
Oops sorry @oogushikun, I didn’t realize that was you on Upwork! You’ve been hired there. 

@mananjadhav please also grab the job for C+ when you get a chance! 😀

**Comment by oogushikun** [comment] 2022-10-10 23:10
Thanks @stephanieelliott 😄

**Comment by oogushikun** [comment] 2022-10-12 12:25
Hi @stephanieelliott Is it possible to get a reevaluation of the budget for this task? Taking into consideration the effort put into debugging the issue and also the effects of the bug being more than what was reported, i.e., transitons weren't working correctly on all platforms, not just on Safari.

**Comment by stephanieelliott** [comment] 2022-10-14 21:55
@oogushikun I agree that the scope of the issue may have extended a little bit beyond what was described in the issue body. I can see increasing this to $750 total -- does that sound fair to you?

**Comment by oogushikun** [comment] 2022-10-17 07:23
works for me @stephanieelliott, thanks a lot 😃.

**Comment by mvtglobally** [comment] 2022-10-18 11:16
Issue not reproducible during KI retests. (First week)

**Comment by stephanieelliott** [comment] 2022-10-21 15:19
All paid up!

**Closed by stephanieelliott** 2022-10-21 15:19 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by thesahindia** [comment] 2022-10-21 15:27
@stephanieelliott, I think reporting compensation is pending on this one. Can you please look into it?

**Comment by stephanieelliott** [comment] 2022-10-26 14:17
Oop, thanks @thesahindia! I invited you to the job on Upwork to pay out the reporting bonus https://www.upwork.com/jobs/~013abb27ed5da559c8

**Comment by thesahindia** [comment] 2022-10-26 14:20
I have already submitted the proposal.

**Comment by stephanieelliott** [comment] 2022-10-26 18:23
Thanks, all paid now!
