### ISSUE TITLE
[$1000] On task view page clicking three dot menu hides the pin icon and mark as done button as well on header

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22505] opened 2023-07-09 02:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Click on FAB button -> Click Assign task
3. Enter title -> Click Next -> Select Share somewhere -> Click confirm task
4. This will navigate to created task -> Click three dot on right side -> Notice the position of menu hides all three option
## Expected Result: 
Menu should not hide the three option on top left same on other pages
## Actual Result: 
Opening the menu hides the 3 option on header
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-07-08 at 7 59 19 PM](https://github.com/Expensify/App/assets/43996225/f03e8c29-65ae-49f9-b258-a4c4c7a3a629)
![Snip - New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/43bd47f2-9954-463d-aeca-ca7eff978ac6)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688826550912059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018cd8bba8d8d66974</li>
        <li>Upwork Job ID: 1686022998067138560</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-09 02:02
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
On task view page clicking three dot menu hides the pin icon and mark as done button as well on header
### What is the root cause of that problem?
The root cause is we have not added `anchorAlignment` prop to `<ThreeDotsMenu>` on `HeaderView.js` that basically responsible to set position horizontal/vertical for menu here we are missing that’s the causes of this issue
### What changes do you think we should make in order to solve the problem?
We just need to `anchorAlignment` prop to `<ThreeDotsMenu>` such a way that I doesn’t hide header option
We need to define default props of `anchorAlignment` to `HeaderView.js` and pass on `<ThreeDotsMenu>`
We need to set value like below as this can be found to other places that we have used `<ThreeDotsMenu>` which is consistent with other page
Optionally we can add custom values as desired
```js
threeDotsAnchorAlignment:{
	horizontal: CONST.MODAL.ANCHOR_ORIGIN_HORIZONTAL.LEFT,
	vertical: CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.TOP,
}
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by jasperhuangg** [comment] 2023-07-10 21:03
Yup, not a bug, closing. Thanks for clarifying @dhairyasenjaliya

**Comment by thienlnam** [comment] 2023-07-28 18:28
This bug still exists

**Comment by greg-schroeder** [comment] 2023-07-31 14:36
Okay this has been reopened, applying `External` and will have C+ review proposals

**Comment by situchan** [comment] 2023-07-31 14:48
This has the same root cause as https://github.com/Expensify/App/issues/23140. Just happening in a different place.
@Julesssss should we cover this fix as well in https://github.com/Expensify/App/issues/23140?
cc: @Nikhil-Vats 

I see that both issues are reported by same contributor - @dhairyasenjaliya and I think we can combine these into one.

**Comment by greg-schroeder** [comment] 2023-07-31 14:59
@Julesssss @Ollyws can you confirm the above?

**Comment by Julesssss** [comment] 2023-08-01 09:11
Yeah agree. Let's close this issue as a dupe

**Comment by greg-schroeder** [comment] 2023-08-01 14:39
Got it. I will port this discussion over to the other issue.

**Closed by greg-schroeder** 2023-08-01 14:39 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
