### ISSUE TITLE
HOLD for payment 2024-04-03 [$500] Workspace - 3 dot menu in WS listing/WS chat stops working after viewing WS avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37609] opened 2024-03-01 15:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** kiatest.78+mass@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click Settings icon at bottom >> Workspaces
3. Tap on 3 dot menu for any WS
4. Select admin or announce room
5. Tap on header
6. Tap on WS avatar to view larger preview
7. Tap on 3 dot menu in WS chat (Note : 3 dot not working)
8. Go back to WS listing page
9. Tap on 3 dot menu for any WS

## Expected Result:
3 dot menu in WS listing page (to access delete, admin & announce rooms) & in WS chat (to select unpin/pin option) should work after viewing WS avatar

## Actual Result:
3 dot menu in WS listing/WS chat stops working after viewing WS avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/99be7269-fea2-4b4f-8003-9057c9d76444

https://github.com/Expensify/App/assets/78819774/4aea41a0-b0aa-4786-8bca-a945a58ccf95

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9482d637d6fa5bd</li>
        <li>Upwork Job ID: 1765134061012324352</li>
        <li>Last Price Increase: 2024-03-05</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-01 15:44
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by bernhardoj** [comment] 2024-03-02 11:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't open the three-dot menu after opening a workspace avatar.

### What is the root cause of that problem?
The three-dot menu won't show when it's behind a modal.
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/components/ThreeDotsMenu/index.tsx#L86

The condition that always fails is `modal?.willAlertModalBecomeVisible`. When we open the WS avatar page, `modal?.willAlertModalBecomeVisible` will be true, 
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/components/Modal/BaseModal.tsx#L79-L83

but when we close the WS avatar page, `modal?.willAlertModalBecomeVisible` is never updated to false because `hideModal` is never called.
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/components/Modal/BaseModal.tsx#L62-L64

`hideModal` will either be called when the avatar modal unmounts,
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/components/Modal/BaseModal.tsx#L96-L106

but at the time the modal is unmounted, the visible state is already updated to false,

or when `onModalHide` is called.
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/components/Modal/BaseModal.tsx#L187

The first one already works as expected, but the second one is the issue. The reason it didn't get called is that when we press the close button of the WS avatar modal, it will update the visible state to false and call `onModalClose`,
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/components/AttachmentModal.tsx#L388-L396

and in `onModalClose`, we close the WS avatar page.
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/pages/ReportAvatar.tsx#L33-L35

So, the `onModalHide` didn't get a chance to be called because we closed the page too early.

### What changes do you think we should make in order to solve the problem?

We should close the page in `onModalHide` instead, just like we did in ReportAttachments.
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/pages/home/report/ReportAttachments.tsx#L36-L40

_we should fix this in ReportAvatar, ProfileAvatar, and WorkspaceAvatar_

**Comment by abekkala** [comment] 2024-03-05 21:55
@lanitochka17 hmm, yeah, I feel that the 3 dot menu should always work

**Comment by kmbcook** [comment] 2024-03-06 19:48
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Workspace - 3 dot menu in WS listing/WS chat stops working after viewing WS avatar

### What is the root cause of that problem?
BaseModal sets willAlertModalBecomeVisible to true, but fails to set it back to false after the modal is closed. 
https://github.com/Expensify/App/blob/44fc9e1121cc5e214ba1fa24c5d3aad97216666b/src/components/Modal/BaseModal.tsx#L79-L94

### What changes do you think we should make in order to solve the problem?
Set willAlertModalBecomeVisible to false when BaseModal closes. Do this by calling Modal.willAlertModalBecomeVisible(false) in the clean-up function which is called when the modal closes, this function.
https://github.com/Expensify/App/blob/44fc9e1121cc5e214ba1fa24c5d3aad97216666b/src/components/Modal/BaseModal.tsx#L88-L93

**Comment by abekkala** [comment] 2024-03-06 21:36
@allroundexperts when you have a moment can you review the proposals that have come in so far?

**Comment by sarahRosannaBusch** [comment] 2024-03-06 23:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Three Dots Menu stops working after viewing WS Avatar in a preview modal.

### What is the root cause of that problem?
After viewing the avatar in the modal then clicking the ThreeDotsMenu, its `hidePopoverMenu()` is called immediately after `showPopoverMenu()` so the popover is never visible. This is happening because the modal used to view the avatar is not tracking it's state properly, and the Three Dot Menu is being automatically closed when it thinks the modal is open. 

### What changes do you think we should make in order to solve the problem?
The Three Dots Menu should not be dependent on the state of the modal. 

In `src/components/ThreeDotsMenu/index.tsx` the `isBehindModal` variable and `useEffect()` function should be removed entirely as they are not needed. Without them, the onPress event is the only thing determining when to show/hide the popover menu, so it is always correct. (I've tested on all platforms to confirm this is true.)

### What alternative solutions did you explore? (Optional)
The modal state bug, as others have already proposed, should also be fixed - but maybe as a separate issue?

**Comment by allroundexperts** [comment] 2024-03-07 16:59
> In `src/components/ThreeDotsMenu/index.tsx` the `isBehindModal` variable and `useEffect()` function should be removed entirely as they are not needed. Without them, the onPress event is the only thing determining when to show/hide the popover menu, so it is always correct. (I've tested on all platforms to confirm this is true.)

We occasionally open the modals by keyboard shortcuts as well. This would fail in that case.

**Comment by sarahRosannaBusch** [comment] 2024-03-07 17:38
> We occasionally open the modals by keyboard shortcuts as well. This would fail in that case.

My solution still works for this case, because the popover menu is closed on blur (not by a close button). So anytime the user does anything it is already closing properly. I've tried this using the shortcuts to open the RHP and LHP, but I'm not actually seeing a shortcut to open a modal. Am I missing something?

**Comment by allroundexperts** [comment] 2024-03-07 21:14
> My solution still works for this case, because the popover menu is closed on blur (not by a close button). So anytime the user does anything it is already closing properly. I've tried this using the shortcuts to open the RHP and LHP, but I'm not actually seeing a shortcut to open a modal. Am I missing something?

No, I just tested it and it seems to work. However, can you verify if applying your fix won't bring back https://github.com/Expensify/App/issues/33541?

**Comment by allroundexperts** [comment] 2024-03-07 21:22
Thanks for your proposal @kmbcook. I see that your solution is similar to what @rayane-djouah proposed earlier. You're suggesting to apply the same fix at a different place. Is there any reason for it? How is it any better from applying it at the screen level?

**Comment by allroundexperts** [comment] 2024-03-07 21:40
I'm leaning towards @rayane-djouah's [proposal](https://github.com/Expensify/App/issues/37609#issuecomment-1975228336) since it fixes the problem at its root. The other proposals seem to be more of a patch work on the original problem. That being said, I'm open to a discussion if anyone disagrees.

**Comment by allroundexperts** [comment] 2024-03-07 21:41
I'm leaning towards @rayane-djouah's [proposal](https://github.com/Expensify/App/issues/37609#issuecomment-1975228336) since it fixes the problem at its root. The other proposals seem to be more of a patch work on the original problem. That being said, I'm open to a discussion if anyone disagrees.

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-03-08 03:10
@allroundexperts the issue we have here is that the `hideModal` of BaseModal isn't called at all, not just the `Modal.willAlertModalBecomeVisible`. If it fixes the root cause, it should also solve this [issue](https://github.com/Expensify/App/issues/37634) which has the same root cause.

`willAlertModalBecomeVisible` also doesn't seem related to RHP.

**Comment by sarahRosannaBusch** [comment] 2024-03-08 04:38
> > My solution still works for this case, because the popover menu is closed on blur (not by a close button). So anytime the user does anything it is already closing properly. I've tried this using the shortcuts to open the RHP and LHP, but I'm not actually seeing a shortcut to open a modal. Am I missing something?
> 
> No, I just tested it and it seems to work. However, can you verify if applying your fix won't bring back #33541?

Oh, yes I was able to reproduce that issue on Android with my "fix". Sorry, I should have looked for that.

**Comment by abekkala** [comment] 2024-03-08 17:36
@Gonals do you agree with @allroundexperts chosen proposal?

**Comment by bernhardoj** [comment] 2024-03-11 14:04
@allroundexperts any thoughts on my disagreement [here](https://github.com/Expensify/App/issues/37609#issuecomment-1984967711)?

**Comment by bernhardoj** [comment] 2024-03-12 13:05
@allroundexperts bump

**Comment by kmbcook** [comment] 2024-03-12 21:27
> Thanks for your proposal @kmbcook. I see that your solution is similar to what @rayane-djouah proposed earlier. You're suggesting to apply the same fix at a different place. Is there any reason for it? How is it any better from applying it at the screen level?

I actually didn't read that earlier proposal carefully. Looks like it is better.

**Comment by allroundexperts** [comment] 2024-03-18 00:35
@bernhardoj I went through your proposal again and I still think that @rayane-djouah's proposal is better. In my opinion, we should not rely on `hideModal` to be called in order to fully close the modal. If someone dismisses the modal by navigation, `willAlertModalBecomeVisible` should become `false` automatically. With your approach, we would have to call `onModalHide` explicitly in other pages as well just like you mentioned in your proposal. Even if we fix those pages now, I am pretty sure that this issue would return as new modals are added. A better way to do this in my opinion would be to detach this dependency on `onModalHide` call. 

I hope that clarified the reasoning for selecting @rayane-djouah's proposal.

**Comment by bernhardoj** [comment] 2024-03-18 06:55
@allroundexperts I'm still unconvinced about setting the `willAlertModalBecomeVisible` when a page is removed from navigation. Even if we do it, we will still need to replace onModalClose with onModalHide to fix this issue https://github.com/Expensify/App/issues/37634 as they have the same root cause.

I think it's just about the attachment modal lifecycle. The `onModalClose` is called when the user request to close the modal. If we immediately do a navigation, then `onModalHide` will never be called. Calling `Modal.willAlertModalBecomeVisible` when a page is removed doesn't solve the root cause of the issue. 

> Even if we fix those pages now, I am pretty sure that this issue would return as new modals are added.

We can just remove the `onModalClose` if that's confusing as it's only being used in report, WS, profile avatar, and transaction receipt page to navigate away. 

Or if we still want to keep the `onModalClose`, then we need to change the ref here to `isHideModalCalled.current` and call `hideModal` when it's not yet called in case the animation is still ongoing.
https://github.com/Expensify/App/blob/c915e7f026eddc710dd01a38abc3afc9334002ae/src/components/Modal/BaseModal.tsx#L96-L103

**Comment by allroundexperts** [comment] 2024-03-18 10:52
> We can just remove the `onModalClose` if that's confusing as it's only being used in report, WS, profile avatar, and transaction receipt page to navigate away.

@bernhardoj Are you sure that removing this will not cause any regressions?

**Comment by bernhardoj** [comment] 2024-03-18 11:51
@allroundexperts after some testing, I found that replacing `onModalClose` with `onModalHide` caused a regression.
1. Open profile avatar
2. Press the browser/device back button
3. There will be 2 navigation back happen, one from the browser/native, one from `onModalHide`

Now I know why we use `onModalClose` because it will never be called when we navigate using the browser/device back button.

So, we can't use the solution of replacing `onModalClose` with `onModalHide`, but we still need a solution that makes sure `hideModal` is called instead of only `Modal.willAlertModalBecomeVisible`.

**Comment by allroundexperts** [comment] 2024-03-19 22:04
> So, we can't use the solution of replacing `onModalClose` with `onModalHide`, but we still need a solution that makes sure `hideModal` is called instead of only `Modal.willAlertModalBecomeVisible`.

For now, I still feel like the chosen proposal is the best one.

**Comment by bernhardoj** [comment] 2024-03-20 02:29
@allroundexperts I have updated my proposal's main solution to make sure `hideModal` is called. If it still doesn't convince you, can you ask to reopen https://github.com/Expensify/App/issues/37634 and I can move my proposal there?

**Comment by abekkala** [comment] 2024-03-22 19:00
@isabelastisser I'm ooo until April 08 - I'll be taking back any issues still Open once I return

___

### CURRENT STATUS:
@allroundexperts has chosen a proposal by @rayane-djouah. A PR has already been merged: https://github.com/Expensify/App/pull/38098 which was just deployed to staging. Once it has deployed to prod this issue should update with a payment date. 

- Fix: @rayane-djouah [$500, pending no regressions] 
- PR: Review @allroundexperts [$500, pending no regressions]

**Comment by isabelastisser** [comment] 2024-03-28 19:28
No updates.

**Comment by isabelastisser** [comment] 2024-04-05 02:41
Payment summary:

`PENDING`:

PR: Review @allroundexperts $500 - pending payment in newdot.

**Closed by isabelastisser** 2024-04-05 02:41 UTC
Labels: Reviewing, External, Daily, Bug
