### ISSUE TITLE
[Internal:292669] Users LHN not loading after sign-in

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23557] opened 2023-07-25 14:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Download the  NewDot app
2. Sign in as `jules@expensify.com` or `sonia@expensify.com`

## Expected Result:
User is able to sign - in

## Actual Result:
For certain users, the app won't load after sign-in

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.45.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![IMG_9585 (1)](https://github.com/Expensify/App/assets/93399543/5a963cb9-8028-434c-9f7d-9dbcc12836fd)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690204559608079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b851a413dd654c19</li>
        <li>Upwork Job ID: 1686302515143319552</li>
        <li>Last Price Increase: 2023-08-01</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-07-25 20:07
@kbecciv @sophiepintoraetz , let me know if either of you can reproduce.

**Comment by sophiepintoraetz** [comment] 2023-07-25 22:11
Sorry @mallenexpensify - I cannot reproduce 

https://github.com/Expensify/App/assets/42940078/527ab907-10ac-4e43-8541-961ae61f375b

**Comment by rushatgabhane** [comment] 2023-07-25 22:15
@sophiepintoraetz maybe we can add `Needs Reproduction` label and keep it open for a while?

**Comment by sophiepintoraetz** [comment] 2023-07-26 01:35
i'll add the label but leave it closed - if someone else is able to reproduce this, then they can re-open the issue!

**Comment by mallenexpensify** [comment] 2023-07-26 20:29
@flodnv is it possible to check my logs for the iOS app?  It won't load for me.  I've tried to close/reopen, sign out/in, waited for app the update to a new version - none of it makes a difference, I still only see the loading screen from the OP.  I can click a few things but nothing 'loads', outside of settings which allowed me to sign out

**Comment by flodnv** [comment] 2023-07-27 08:58
Did you uninstall and reinstall it?

**Comment by sophiepintoraetz** [comment] 2023-07-28 02:30
@mallenexpensify - can you take a video recording like I did to get the result you're getting?

**Comment by flodnv** [comment] 2023-07-31 10:57
Bump @mallenexpensify

**Comment by mallenexpensify** [comment] 2023-08-01 04:04
The vid is the same as the screenshot, with the chats blank and loading. 
Going to chat with @danieldoglas tomorrow to see if we can debug in person.  I've un/reinstalled many times with the same bug. My only thought is that I deleted an IOU report in Classic and that might have 'set things off', when I log into [www.expensify.com](http://www.expensify.com/) now I get an error each time (GH for that _somewhere_) 

https://github.com/Expensify/App/assets/22508304/6d1fc268-1102-41bb-87e8-6400093fb443

**Comment by flodnv** [comment] 2023-08-01 08:12
>when I log into [www.expensify.com](http://www.expensify.com/) now I get an error each time

On OldDot?? So you can't use Expensify at all anymore, Old nor New?? Then yes, we need you to launch OldDot whilst tailing your logs

**Comment by Julesssss** [comment] 2023-08-01 09:02
This is reproducible on my account and Sonia's

**Comment by flodnv** [comment] 2023-08-01 09:04
You can't close a BugBot, it will get reopened as long as it happens 😄

**Comment by Julesssss** [comment] 2023-08-01 09:05
Good point. Let's leave both open then, as the app issue prevents more dupes from being reported.

**Comment by Julesssss** [comment] 2023-08-01 09:07
God damn it.

**Comment by Julesssss** [comment] 2023-08-01 09:36
Next Auth deploy will contain a Log that should help us to track down the troublesome reportID for me and Sonia. Then we can take a close look at the report data

**Comment by Julesssss** [comment] 2023-08-01 13:59
Timestamp for my login attempts: 
- 1st Aug - 13:58 UTC

@sonialiap could you please try to sign in and make a note of the time so I can review our logs later today? Thanks

**Comment by flodnv** [comment] 2023-08-02 08:57
So @Julesssss what is the log telling you??

**Comment by Julesssss** [comment] 2023-08-02 09:02
Currently investigating, will write up notes soon

**Comment by Julesssss** [comment] 2023-08-02 10:29
Okay, I located the troublesome reportID: `28501663496784` for me, and `1591164149233781` for Sonia. 

- Both reports were created within three days of each other, and are chat reports without any comments
- In my case, I believe it's a chat report with one of my test users for which I lost access due to passwordless
- ^ for that use, I see :`Our email provider has temporarily suspended emails to salvorhardin585@gmail.com due to delivery issues.` when logging into NewDot
- Navigating directly to the report fails as expected with the same 500 error (requestID: `7f0542012fee887d-LHR`)

It's better if my account remains bricked, so I asked @sonialiap to try manually adding a comment in OldDot to see if that resolves the bug. In the meantime I will continue looking into the specific data of the bad reports.

**Comment by flodnv** [comment] 2023-08-02 11:12
```
flo@db1.lax:~$ sudo readdb.sh  "select * from reports where reportID IN ('28501663496784', '1591164149233781', '1740055458673635');"
created              submitted  approved  reportID          accountID  managerID  reportName   state  total  currency  cachedData                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status
-------------------  ---------  --------  ----------------  ---------  ---------  -----------  -----  -----  --------  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  ------
2023-06-21 11:08:15                       28501663496784    0                     Chat Report  0      0      USD       {"submitted":"","submittedTo":"","approved":"","unapproved":"","reimbursed":"","shared":"","type":"chat","retracted":"","expensify_policyID":"F8B4A7879EDA483B","policyLastModified":1681915927035045,"isSmartReport":false,"cacheComputedBy":8572718,"inbox":{"violations":[],"policyType":"personal","firstSubmittedDate":"","wasComputedInReportCache":true},"reimburserEmail":"__fake__","queuedForAutoExport":{"queued":false,"connections":[],"exportFailed":false,"failedConnections":[]},"hasBeenExportedToIntegration":false,"wasReimbursedViaACH":false,"statementCardID":null,"statementBank":null,"statementPeriodEndDay":null,"isWaitingOnBankAccount":false,"isABAReimbursed":false,"expectedReimbursementDate":null,"canMarkReimbursementReceived":true,"hasReimbursableTotal":false,"hasTransactions":false,"hasBillableTransactions":false,"reportOwners":[],"managerOnVacation":"","isSmartReportOnFile":false,"invoiceID":0,"billID":0}  0     
2023-05-18 19:42:35                       1591164149233781  0                     Chat Report  0      0      USD       {"submitted":"","submittedTo":"","approved":"","unapproved":"","reimbursed":"","shared":"","type":"chat","retracted":"","expensify_policyID":"F38EA6C07CC57AC2","policyLastModified":1689843167331370,"isSmartReport":false,"cacheComputedBy":3472167,"inbox":{"violations":[],"policyType":"personal","firstSubmittedDate":"","wasComputedInReportCache":true},"reimburserEmail":"__fake__","queuedForAutoExport":{"queued":false,"connections":[],"exportFailed":false,"failedConnections":[]},"hasBeenExportedToIntegration":false,"wasReimbursedViaACH":false,"statementCardID":null,"statementBank":null,"statementPeriodEndDay":null,"isWaitingOnBankAccount":false,"isABAReimbursed":false,"expectedReimbursementDate":null,"canMarkReimbursementReceived":true,"hasReimbursableTotal":false,"hasTransactions":false,"hasBillableTransactions":false,"reportOwners":[],"managerOnVacation":"","isSmartReportOnFile":false,"invoiceID":0,"billID":0}  0     
2023-08-02 10:31:03                       1740055458673635  0                     Chat Report  0      0      USD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   0     
flo@db1.lax:~$ 
```

**Comment by Julesssss** [comment] 2023-08-02 13:29
We need more data, so I am requesting the [full query results](https://github.com/Expensify/Expensify/issues/304905) here. If this works, I'll do the same for sonia's report, and for my 'good' report.

**Comment by Julesssss** [comment] 2023-08-02 16:05
I will be OOO from today, but will return to this on Monday.

**Comment by mallenexpensify** [comment] 2023-08-02 19:03
I just updated NewDot via TestFlight and to log in at 12:02pm PST and it's not loading, in case that's helpful.  Also, mostly, OOO til later on Monday.

**Comment by Julesssss** [comment] 2023-08-07 10:49
Rafe retrieved the db data I need, so the next step is to look for discrepencies in the good/bad report data. 

Also @RachCHopkins is now seeing the same issue, so I might locate her troublesome reportID and request that data too.

**Comment by Julesssss** [comment] 2023-08-08 13:08
I decrypted and compared the report data, here are the comparisons: 

**lastReportAction**
![Screenshot 2023-08-08 at 13 58 39](https://github.com/Expensify/App/assets/10736861/dc605545-96c9-4d75-bcac-46ad1b61e0f5)

**Shared**
![Screenshot 2023-08-08 at 13 58 49](https://github.com/Expensify/App/assets/10736861/5bcc53b1-354d-4e2e-8569-94044b685f23)

**RNVPs**
![Screenshot 2023-08-08 at 13 58 43](https://github.com/Expensify/App/assets/10736861/a6194e8d-0b6e-491a-ba9f-8b46e6499aa8)

______________

Most of the report data structure is identical, but here are some things I am currently investigating further: 
- Only the bad reports have a `parentReportActionID` field
- Only the bad reports have an `expensify_policyID` value

**Comment by Julesssss** [comment] 2023-08-08 13:41
1. `expensify_policyID`: we cast accountIDs to int [here](https://github.com/Expensify/Auth/blob/c24fe9a7caa3a0e3445ea95bf223f4f8270b6bec/auth/lib/Report.cpp#L4385-L4386) when building participants, but they seem to be correct looking at the `shared` data
2. `parentReportActionID`: [here](https://github.com/Expensify/Auth/blob/629676c5a167da938085f4b93bed54fdbd98e0ee/auth/lib/Report.cpp#L4293-L4294) we are adding participants from the shared user array, though `account` is a valid int and `email` is a valid String according to the queried data 
3. [This logic](https://github.com/Expensify/Auth/blob/629676c5a167da938085f4b93bed54fdbd98e0ee/auth/lib/Report.cpp#L4321-L4329) is only invoked if the report has a `parentReportActionID`(!)  This was also flagged by Rocio as a potential cause for the exception (!!)

3 seems the most likely, so I plan to do the following: 
- Create a query that removes `parentReportActionID` from Sonia's bad report to test the theory
- If that resolves her issue, I'll attempt to solve the bug in code using mine and Rach's bad reports

**Comment by Julesssss** [comment] 2023-08-08 15:06
### Successfully reproduced locally!

After manually inserting a reportNVP for `parentReportActionID` of a **report with NO reportActions** to match the production db data, I can reproduce the same bug locally: 

NewDot dev build:
![Screenshot 2023-08-08 at 15 57 44](https://github.com/Expensify/App/assets/10736861/610f7641-7b0e-40c0-aac8-3bc2b9dfe358)

Logs:
![Screenshot 2023-08-08 at 15 59 42](https://github.com/Expensify/App/assets/10736861/ff0bd201-17ff-4468-9347-25ef9581ab68)

### Solution

My first thought is to manually remove the `parentReportActionID` rNVP. 

The theory is that the malformed reports were created during a short window where we were implementing threaded reports and we shouldn't see new malformed reports.  We can try the above fix for Sonia, then after I have verified the reports are completely useless, we can delete them entirely.

**Comment by Julesssss** [comment] 2023-08-08 15:13
Testing the fix locally before I create the query request: 

1. Account is [screwed](https://github.com/Expensify/App/issues/23557#issuecomment-1669800550) due to malformed report
2. Removed the `parentReportActionID` rnvp with:
    `delete from reportNameValuePairs where reportID=336189714734429 AND name='parentReportActionID';`
4. Refresh the page and the bug is resolved: 

https://github.com/Expensify/App/assets/10736861/18a8270d-bd1c-4b16-8ab3-ff0230bdd569

**Comment by Julesssss** [comment] 2023-08-09 08:01
Just noting that it appears @RachCHopkins has a different issue to myself and Sonia, I can find no trace of the same exception that occurs every time we attempt to sign in...

<img width="1192" alt="Screenshot 2023-08-09 at 08 59 21" src="https://github.com/Expensify/App/assets/10736861/45f05ef9-3838-4777-8011-d6d7302356d6">
<img width="1203" alt="Screenshot 2023-08-09 at 08 59 12" src="https://github.com/Expensify/App/assets/10736861/f7a0c1b6-524e-4ed5-9227-8aff0cb2aaca">
<img width="1203" alt="Screenshot 2023-08-09 at 08 59 02" src="https://github.com/Expensify/App/assets/10736861/e90478a9-faca-4c18-93ac-1a5d5df93ce6">

**Comment by Julesssss** [comment] 2023-08-09 10:33
Sadly the query didn't resolve the issue for Sonia. I'll continue to investigate this, there might be additional places that the exception occurs, or a second problematic report... 

In better news, I believe I located the actual cause of the null exception, and I have an [Auth PR](https://github.com/Expensify/Auth/pull/8478) that is now in review 🤞

**Comment by Julesssss** [comment] 2023-08-09 12:56
Auth PR merged. After tomorrow's deploy we'll test the fix 🤞

**Comment by Julesssss** [comment] 2023-08-10 08:13
Auth PR was deployed and the GetChats exception no longer occurs. However, this unsurfaced a new issue where `OpenApp` & `RecconectApp` fail. Investigating further.

**Comment by Julesssss** [comment] 2023-08-10 09:28
The new crash occurs [here](https://github.com/Expensify/Web-Expensify/blob/196dbf62dc89d2f01298ce6022c83040b3d78a2c/lib/ReportStore.php#L507) as the report does not exist. Example [logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%221756694260998440%22%20AND%20email%3A%22jules%40expensify.com%22%20AND%20timestamp%3A%5B2023-08-10T07%3A30%20TO%202023-08-11T23%3A59%5D).

I believe the fix is to not throw an exception for newDot as that code was meant for the old app (`isMobileApp` > `isOldMobileApp`), here's how I was able to reproduce locally:

- Locate a reportID where the most recent report action is a `reportpreview` action
- get the linkedReportID: 
    `SELECT * from reportActions where reportActionID=1887718498688973431;`
    <img width="1014" alt="Screenshot 2023-08-10 at 10 25 17" src="https://github.com/Expensify/App/assets/10736861/04e95fde-188b-454d-82e8-340992e6c672">
- Delete or corrupt the `linkedReportID` value
    `UPDATE reportActions SET message="{""linkedReportID"":6666666666666}" WHERE reportActionID=1887718498688973431;`

**Comment by Julesssss** [comment] 2023-08-10 09:31
In the meantime... here's confirmation the Auth PR resolved the issue for Sonia and hopefully @mallenexpensify:

<img width="471" alt="Screenshot 2023-08-10 at 10 30 07" src="https://github.com/Expensify/App/assets/10736861/3d401b77-7fb4-4013-b0c8-236729a0586b">

**Comment by Julesssss** [comment] 2023-08-10 13:20
PR for the second fix: https://github.com/Expensify/Web-Expensify/pull/38450

**Comment by Julesssss** [comment] 2023-08-11 08:09
Resolved for me on staging, I can finally message people again 🤩

**Comment by flodnv** [comment] 2023-08-24 09:59
Isn't this done? 😄

**Comment by Julesssss** [comment] 2023-08-29 09:55
I was OOO. But yes it's done :shipit:

**Closed by Julesssss** 2023-08-29 09:55 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
