### ISSUE TITLE
[$1000] Annonymous User can open title/description edit task modal but not able to edit it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25482] opened 2023-08-18 13:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Create a public room, and assign the task
- Copy the room link and open it in incognito window
- Open the task, and add `/title` to link. link will be -
`http://localhost:8082/r/6576534725992156/title`
- Hit enter, the title edit dialogue will open
- Try editing the task, and saving it. No effect.
## Expected Result: 
Navigates to the sign in page
## Actual Result: 
Title change page can be opened
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b05443f8-d83d-4dcb-93ca-24266bc8ae09

**Expensify/Expensify Issue URL:**
**Issue reported by:** @BhuvaneshPatil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691484016766219
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01474a89838f9e93ae</li>
        <li>Upwork Job ID: 1694002267803222016</li>
        <li>Last Price Increase: 2024-01-02</li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-08-18 13:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
We are not checking if user is anonymous in -`TaskTitlePage` and `TaskDescriptionPage` .

### What changes do you think we should make in order to solve the problem?
There are two approaches for this -
1. Redirecting user to sign in page
- We can check if user is anonymous using `Session.isAnonymousUser` and redirect to sign in page
2. Wrapping the component with `FullPageNotFoundView`
- `shouldShow` condition should be passed so that `FullPageNotFoundView` will be displayed.

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2023-08-21 13:36
When you click on such action you should be navigated to the sign in page>  `Navigates to the sign in page`

updated the expected results section

**Comment by slafortune** [comment] 2023-08-22 15:02
looks good

**Comment by sobitneupane** [comment] 2023-08-23 07:21
@BhuvaneshPatil Would you like to update your proposal with more details? Please include permalink to refer where the issue exists and which are the files where you are proposing to make the change.

**Comment by BhuvaneshPatil** [comment] 2023-08-23 07:43
Sure @sobitneupane .
I will update the proposal shortly.

**Comment by sobitneupane** [comment] 2023-08-24 09:01
@BhuvaneshPatil I am having some issue while trying to open task report as an anonymous user. So, It is difficult for me to reproduce the issue.

https://github.com/Expensify/App/assets/25876548/b1698c3e-c9e1-4c99-a8a3-57d8494285a1

**Comment by BhuvaneshPatil** [comment] 2023-08-24 10:19
@sobitneupane I also face same issue many times, What I do is create a new task and open it. There is an issue created for the same. 
PS - Finding that issue

**Comment by BhuvaneshPatil** [comment] 2023-08-24 10:20
Link to issue - https://github.com/Expensify/App/issues/23491

**Comment by sobitneupane** [comment] 2023-08-25 05:22
@BhuvaneshPatil Thanks for the update.

Let's hold this issue for now. We will come back to it after https://github.com/Expensify/App/issues/23491 gets fixed.

cc; @slafortune

**Comment by slafortune** [comment] 2023-08-28 19:34
Putting on hold and changing priority to monthly as well.

**Comment by slafortune** [comment] 2023-09-08 20:00
reassigning a BZ member, I am out on sabbatical.

**Comment by johncschuster** [comment] 2023-09-27 00:07
Still on hold

**Comment by johncschuster** [comment] 2023-10-04 21:21
Still on hold

**Comment by johncschuster** [comment] 2023-10-10 21:19
No need to adjust the bounty. This is still on hold.

**Comment by johncschuster** [comment] 2023-10-13 20:35
Still on hold.

**Comment by johncschuster** [comment] 2023-10-17 20:52
Still on hold

**Comment by johncschuster** [comment] 2023-10-20 10:40
This is still on hold. I'm going to decrease the priority to Weekly while we wait.

**Comment by johncschuster** [comment] 2023-10-31 21:16
Still on hold

**Comment by johncschuster** [comment] 2023-11-14 22:47
Still on hold

**Comment by johncschuster** [comment] 2023-11-29 04:02
Still holding

**Comment by johncschuster** [comment] 2023-12-08 21:45
Looks like https://github.com/Expensify/App/issues/23491 is now off hold! @kavimuru, can you please see if you can still reproduce this behavior? If so, can you let us know if the reproduction steps have changed at all?

**Comment by johncschuster** [comment] 2023-12-18 15:48
@kavimuru bump!

**Comment by kavimuru** [comment] 2023-12-18 22:17
@johncschuster Issue is fixed now.

https://github.com/Expensify/App/assets/43996225/3b691fa1-d1ef-497e-87fe-b9f212ae6edc

**Comment by DylanDylann** [comment] 2023-12-20 10:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Annonymous User can open title/description edit task modal but not able to edit it
### What is the root cause of that problem?
- Still can reproduce this issue if we click on the title/description link.
- The RCA is that, when user clicks on the internal link that is in the public report, it will navigate user to the correct screen without checking if the user is anonymous user or not.
https://github.com/Expensify/App/blob/c09a3fead81512a4b01ccafff4c736301e0dbe89/src/libs/actions/Link.ts#L102-L105

### What changes do you think we should make in order to solve the problem?
- Just need to update the above to:


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by DylanDylann** [comment] 2023-12-20 10:16
@kavimuru  I still can reproduce this bug when clicking on the link in the report

**Comment by johncschuster** [comment] 2024-01-02 22:32
@DylanDylann did you follow the exact reproduction steps above to reproduce the behavior, or did you need to modify the repro steps in any way?

**Comment by DylanDylann** [comment] 2024-01-03 01:48
@johncschuster I need to modify the repro steps

**Comment by sobitneupane** [comment] 2024-01-09 08:06
Sorry for the delay @DylanDylann.

Yup. I can still reproduce [the issue](https://github.com/Expensify/App/issues/25482#issuecomment-1864210665).

[Proposal](https://github.com/Expensify/App/issues/25482#issuecomment-1864208261) from @DylanDylann looks good to me.

🎀 👀 🎀 C+ reivewed

**Comment by DylanDylann** [comment] 2024-01-11 17:00
@youssef-lr What do you think about my proposal [here](https://github.com/Expensify/App/issues/25482#issuecomment-1864208261) ?

**Comment by DylanDylann** [comment] 2024-01-12 17:42
@youssef-lr This bug will apply to not only the title/description, but also all the flow that we do not want the anonymous user can access

**Comment by johncschuster** [comment] 2024-01-12 21:55
@DylanDylann, can you elaborate on this comment?:

> but also all the flow that we do not want the anonymous user can access

I'm having a hard time understanding what you mean.

**Comment by DylanDylann** [comment] 2024-01-12 22:01
@johncschuster I mean that:

- This bug happened when the anonymous user clicked on the link ```/r/:reportId/title``` or ```/r/:reportId/description``` 
- Also It happened when the anonymous user clicked on ```/settings/profile``` or whatever link that we do not want anonymous users to access

**Comment by youssef-lr** [comment] 2024-01-12 23:45
@DylanDylann I don't think this is reproducible, modifying the URL still takes me to the sign in page. The inputs show up for a split second, but again I don't think we need to worry about this bug at the moment, as long as clicking on the fields takes us immediately to the sign in page, I think it's fine.


https://github.com/Expensify/App/assets/9680864/a0ba6a1f-043b-401d-a022-b255df8e62f1

Thanks for you input here!

**Closed by youssef-lr** 2024-01-12 23:45 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by DylanDylann** [comment] 2024-01-12 23:48
@youssef-lr No. You need to paste the link to the report then click on that

**Comment by DylanDylann** [comment] 2024-01-12 23:59
@youssef-lr Here is the evidence video. You can follow its reproduce steps

[Screencast from 13-01-2024 06:58:00.webm](https://github.com/Expensify/App/assets/141406735/bbc47204-fc21-401a-8c83-970b72b457c8)

**Comment by youssef-lr** [comment] 2024-01-13 00:01
Right @DylanDylann, but I don't think this is affecting real world users currently, we can definitely revisit it once it does.

**Comment by DylanDylann** [comment] 2024-01-13 00:08
@youssef-lr Thanks. Just to note, in the past, we already had PR to fix this issue

**Comment by DylanDylann** [comment] 2024-01-13 00:26
@johncschuster Clicking on the "internal link" action is a frequent action and we already have a lot of issues related to it, so I think this bug will be reported in the future

**Comment by DylanDylann** [comment] 2024-02-28 07:44
This bug still can be reproduced. User can go to the protected route through internal link 

[Screencast from 28-02-2024 14:42:21.webm](https://github.com/Expensify/App/assets/141406735/8c8640fc-3457-44b3-adea-f2ec8168b69e)
