### ISSUE TITLE
DEV: Not able to run storybook

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14338] opened 2023-01-16 22:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to the app folder on terminal
2. Run npm run storybook

## Expected Result:
 It should launch storybook

## Actual Result:
It failed

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:**  v1.2.54-2 dev
**Reproducible in staging?:** occurring in dev
**Reproducible in production?:** occurring in dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** https://user-images.githubusercontent.com/43996225/212771482-af0df354-2457-4c80-9af1-2aa855b1eff7.mov
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mdneyazahmad 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673848718223189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment] 2023-01-17 04:50
Asking about this [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1673930978157359).

**Comment by Luke9389** [comment] 2023-01-17 22:32
👋 Hey y'all! 
There is already a PR to fix this problem here: https://github.com/Expensify/App/pull/13916#issuecomment-1370471303

**Comment by kadiealexander** [comment] 2023-01-17 22:34
Thanks Luke! Closing as a dupe of the above.

**Closed by kadiealexander** 2023-01-17 22:34 UTC
Labels: Daily, Needs Reproduction, Bug
