### ISSUE TITLE
[$500] Search result does not display group chats in focus mode

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38413] opened 2024-03-15 17:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710425577862209

## Action Performed:
1. create a group chat between three people (i.e tom, puneet, bob). Send a message
2. create a DM between two people (i.e tom and puneet). Send a message
3. Switch to #focus mode
4. Make sure both chats are read and not showing up in your LHN
5. Sign out and back in
6. Neither chat should be in your LHN
7. Search for one of the participants (i.e "puneet")
8. You will see the DM in the search results but not the group chat

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/ae65e3e7-fbc4-42f5-b041-1c8e71f25a3e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177cf2eb9537a666d</li>
        <li>Upwork Job ID: 1769687165157543936</li>
        <li>Last Price Increase: 2024-03-18</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2024-03-15 19:06
Asking in thread, can't reproduce following the steps: https://expensify.slack.com/archives/C049HHMV9SM/p1710529504585739?thread_ts=1710425577.862209&cid=C049HHMV9SM

**Comment by trjExpensify** [comment] 2024-03-18 11:27
New steps below, updating the OP: 

1. create a group chat between tom, puneet, bob. Send a message
2. create a DM between tom and puneet. Send a message
3. Switch to focus mode
4. Make sure both chats are read and not showing up in your LHN
5. Sign out and back in
6. Neither chat should be in your LHN
7. Search "puneet"
8. You will see the DM in the search results but not the group chat

Can reproduce: 

<img width="373" alt="image" src="https://github.com/Expensify/App/assets/16232057/ab4f2864-a55e-4cea-98a1-73341e8026ae">

**Comment by kishanio** [comment] 2024-03-18 19:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Group Chats should be visible whilst searching in focus mode. Assuming the focus mode gets rid of all the read conversations in Left Hand Navigation.

### What is the root cause of that problem?

The backend doesn't seem to respond search reports in focus mode.

### What changes do you think we should make in order to solve the problem?

1. Witness backend filtering search reports based on priority mode filter. Maybe this filter is applied globally? 
2. Priority mode filter should not be applied to SearchForReports command.

### What alternative solutions did you explore? (Optional)

**Reminder:** I was thinking to dig deeper to find cause for a related issue where the usernames were not visible upon switching to most recent priority mode. 

![no-usernames-mostrecent-mode](https://github.com/Expensify/App/assets/1800156/ee903328-83d7-4307-991c-0efd785071dc)

**Comment by kishanio** [comment] 2024-03-18 19:44
Contributor details
Your Expensify account email: thobhanikishan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011c7c70c853485d83

**Comment by Pranav2612000** [comment] 2024-03-19 05:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Group chats should be visible during search in focus mode.

### What is the root cause of that problem?

The underlying issues is much more complicated than the scenario mentioned here. Group chats
not being shown in focus mode is just one part of it, but the issue can also be reproduced on shifting to "Most Recent Mode". 

The root cause of the issue is that `personalDetails` for the appropriate accounts have not been populated. So, even though the `SearchForReports` api returns the right response, ( IMG )
<img width="380" alt="image" src="https://github.com/Expensify/App/assets/20909078/d864d3d1-79f0-4914-b19c-693daa387db7">
the search fails because the `personalDetails` store for the users is empty. We can verify the personal details store is empty because we also do not see the names of the users, even if we see the report ( IMGs below )

*Here we see that even after the report has been populated ( I had searched for the user before which populated the `reports` with this entry ), we still don't see the user names*
<img width="375" alt="image" src="https://github.com/Expensify/App/assets/20909078/01fb620f-d159-4f98-a859-071987f41bb1">

Due to the `personalDetails` being entry, this `report` is not added to the `recentReportOptions` that we return in `getSearchOptions` ( https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/libs/OptionsListUtils.ts#L1737 )

This check is being done here - 
https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/libs/OptionsListUtils.ts#L1610
where `participantNames` is an empty Set generated by https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/libs/OptionsListUtils.ts#L380


Also note that it may seem that the search result show a DM chat with another user, but it's actually showing the result as `UsersToInvite`. Refer to the images for the difference – the second one is a `recentReport` where we see the older messages and the correct user icon. In the first image, even though the actual report was in Onyx, we didn't see it because the `personalDetails` were empty.
<img width="378" alt="image" src="https://github.com/Expensify/App/assets/20909078/569b684a-dfd1-474d-9195-917c7fc791d0">
<img width="375" alt="image" src="https://github.com/Expensify/App/assets/20909078/7cea5187-61e7-441a-9823-f928dd247103">

### What changes do you think we should make in order to solve the problem?
The best solution would be for the backend to also include the `personalDetails` of the users who are participants in the reports returned by the `SearchForReports` api. This way all personalDetails info would already be populated and we should start seeing the results. 
The drawback of this solution is that for common generic searches the payload size can be huge, so
a workaround can be to include the `personalDetails` of the users matching the searchString ( because the frontend would also be doing the same check anyway ). But, with this solution, you only see the name of the current user in the report list ( because other users have not yet loaded ) which can feel confusing. 


### What alternative solutions did you explore? (Optional)
If the reviewers and @paultsimura feel appropriate, we can have temporary workarounds in the UI by explicitly making the calls to populate the `personalDetails` whenever required.

**Comment by Pranav2612000** [comment] 2024-03-19 14:13
Thank you @paultsimura .
@francoisl Let me know if there's any way I can help

**Comment by francoisl** [comment] 2024-03-20 21:56
Makes sense to fix this in the backend 👍

**Comment by trjExpensify** [comment] 2024-04-10 18:44
👋 @paultsimura confirming we didn't have any frontend issues here, so we can close it out?

**Comment by trjExpensify** [comment] 2024-04-10 21:33
All for of those PRs linked to this issue are on prod, so I'm going to close it out.

**Closed by trjExpensify** 2024-04-10 21:33 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Bug
