### ISSUE TITLE
[$1000] Chat - Keyboard is hidden when editing the message and selecting the emoji

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18448] opened 2023-05-04 21:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Go to any chat
4. Type and send any message
5. Open context menu (long-hold on the message)
6. Select Edit option
7. Tap on any emoji

## Expected Result:
After selecting an emoji (or dismissing the emoji menu), the keyboard should reappear so that you can continue editing the message

## Actual Result:
After selecting an emoji (or dismissing the emoji menu), the keyboard is hidden and you have to tap back into the compose field to edit the message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.10.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/236333501-804c5ecd-3f69-41e3-99f6-fbec366123c6.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9bdec3cd07f91a5</li>
        <li>Upwork Job ID: 1654576988630274048</li>
        <li>Last Price Increase: 2023-05-05</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-05-05 16:32
@conorpendergrast - am unsure on the repro steps here as I can't repro and don't understand the phrase being use, and I am OOO on mon as are you (why did you, me an @zanyrenney all get assigned this at Fri 5:30pm when all our calendars say 0% Monday I do not know) and then afk with Accountex stuff from Tues - Thurs, so to move this one along when we get confirmation on what this repro step means an reassigning.

**Comment by conorpendergrast** [comment] 2023-05-05 19:57
@laurenreidexpensify Ah, it's the context menu - long press on the sent message! I have it replicated now

**Comment by akinwale** [comment] 2023-05-05 20:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When editing a message in the report, after selecting an emoji from the emoji menu, the edit input does not regain focus.

### What is the root cause of that problem?
The composer does not regain focus because the emoji menu still has focus during its hide animation. Calling the focus() method during this animation will not have any effect. 

### What changes do you think we should make in order to solve the problem?
Implement a delayed `focus()` method similar to the one in `ReportActionsCompose`.

https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose.js#L544-L567

Call this `focus` method with the delay set to `true` in the `onModalHide` event handler for `EmojiPickerButton` in the `ReportActionItemMessageEdit` component.

### What alternative solutions did you explore? (Optional)
None.

**Comment by rojiphil** [comment] 2023-05-08 10:39
@parasharrajat I think, you are referring to this [tracking issue](https://github.com/Expensify/App/issues/15992#top)

**Comment by conorpendergrast** [comment] 2023-05-09 07:44
Sounds good to me. @marcochavezf if you disagree, please reopen!

**Closed by conorpendergrast** 2023-05-09 07:44 UTC
Labels: External, Daily, Help Wanted, Bug
