### ISSUE TITLE
IOU - Clicking on the badge shows cancel button after cancelling the badge amount remains the same

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12969] opened 2022-11-23 19:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensofy.com
2. Log in with HT account (applausetester+0901abb@applause.expensifail.com)
3. Select user (5082211196) and click on the badge
4. Cancel the remaining balance

## Expected Result:
Clicking on the badge shows cancel button after cancelling the badge amount should be changed

## Actual Result:
Clicking on the badge shows cancel button after cancelling the badge amount remains the same

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.30.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203635501-25356723-f222-4a69-a52c-58582b3514dd.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-11-23 21:01
Gonna take this one

**Comment by luacmartins** [comment] 2022-11-28 21:03
I'm getting a `Transaction not found` error, which indicates that the transaction had already been cancelled. 
![Screenshot 2022-11-28 at 1 58 46 PM](https://user-images.githubusercontent.com/22219519/204379683-a6b6a39c-89e1-4931-83e0-400e76c61ca2.png)

I'll look into why those transactions still show as cancellable tomorrow!

**Comment by luacmartins** [comment] 2022-12-01 21:53
Gonna try to get to this tomorrow!

**Comment by luacmartins** [comment] 2022-12-05 21:14
Those transactions had already been cancelled, so the error is correct. Not sure why those showed up as cancellable though, but it's likely that the App got into a weird state. I'll close the issue since I can't reproduce this anymore and the transaction that resulted in the error was already cancelled.

**Closed by luacmartins** 2022-12-05 21:14 UTC
Labels: Engineering, Daily, Overdue, Bug
