### ISSUE TITLE
[$500] Report is not auto submitted with non violation expenses if some of the expenses have violations

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33381] opened 2023-12-20 21:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702933011305779

PolicyID 0CFE78B25EBE2A0A
ReportID: 3961426678972217
Email: puneet@expensify.com

## Action Performed:
1. Create a report with some expenses (say 5) has violations
2.  Set up auto submission to be everyday

## Expected Result:
Expenses which does not have any violations should get submitted 

## Actual Result:
The expenses which does not have any violations is not submitted in the NewDot

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2023-12-15 at 4 20 51 PM](https://github.com/Expensify/App/assets/38435837/a7250082-dfbb-4d9c-9296-de3fd528bf63)

![image (10)](https://github.com/Expensify/App/assets/38435837/2bffb22d-b21f-485d-922b-d87c9e11da58)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018282d51d26aadafc</li>
        <li>Upwork Job ID: 1746854134947237888</li>
        <li>Last Price Increase: 2024-01-15</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2024-01-04 12:21
Asked clarifying questions in slack

**Comment by sonialiap** [comment] 2024-01-10 09:06
Puneet said he'd let me know if this happens again. I haven't had a chance to test it myself.

**Comment by puneetlath** [comment] 2024-01-10 15:53
It happens to me consistently. Report 3961426678972217 is an example of a current open report of mine that is in this state. 

<img width="1026" alt="image" src="https://github.com/Expensify/App/assets/1371996/c0356671-7c24-4b82-b823-f5ef3b884818">

**Comment by sonialiap** [comment] 2024-01-15 11:17
Thanks Puneet!

**Comment by okhot** [comment] 2024-01-15 14:29
@MelvinBot I sent and email requesting to join the slack channel a couple months ago but haven't received any response, Is there anything I can do to speed the process up?

**Comment by puneetlath** [comment] 2024-01-15 16:25
@sonialiap I think this'll actually need to be Internal and should be a part of wave6. Harvesting is a back-end thing.

**Comment by puneetlath** [comment] 2024-01-17 17:20
@sonialiap can we get some movement on this?

**Comment by sonialiap** [comment] 2024-01-18 15:29
@puneetlath I'm not sure what the next step is if it's internal and has been added to a wave. Should I be looking for a volunteer?

**Comment by okhot** [comment] 2024-01-18 20:19
> @okhot what is your email address? I can check the status for you 

It's arreyette1jnr@gmail.com

**Comment by sonialiap** [comment] 2024-01-22 11:50
@okhot I do not see any emails from arreyetta1jnr@gmail.com in our inbox. I'm guessing maybe your email wasn't sent to the right address. I've invited you to the slack channel (you should be added as soon as my invite is approved) and sent an email to confirm the invite

**Comment by greg-schroeder** [comment] 2024-01-24 13:19
Yeah let's make it a Hot Pick and see if someone can grab it

**Comment by iwiznia** [comment] 2024-01-24 20:20
Looked into this. I am not sure what happened since the report is old and was already submitted, but I am seeing that the job (5404634338406566623 ) for that user and policy is stuck:
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/521248/c8f7f6b4-af3a-40ad-835c-d041ac3deffb">
Logs for it are here https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22kuHHSN%22)+AND+timestamp:[2024-01-24T07:03:11.671Z+TO+2024-01-24T09:03:11.671Z]&index=logs_expensify-026430

Error is:
````
kuHHSN	db1.sjc	2024-01-24 08:03:14 118	we@dont.know	{SQLITE} Code: 2067, Message: abort at 39 in [INSERT INTO reportNameValuePairs ( reportID, name, value ) VALUES ( 6700778327476777, 'parentReportActionID', '3963606325532086405') ON CONFLICT(reportID, name) DO UPDATE SET value = excluded.v
kuHHSN	db1.sjc	2024-01-24 08:03:14 118	we@dont.know	'read/write transaction', query failed with error #19 (UNIQUE constraint failed: reportNameValuePairs.name, reportNameValuePairs.value): INSERT INTO reportNameValuePairs ( reportID, name, value ) VALUES ( 6700778327476777, 'parentReportActionID', '3963606325532086405') ON CONFLICT(reportID, name) DO UPDATE SET value = excluded.value ON CONFLICT(name, value) WHERE name = 'parentReportActionID' DO UPDATE SET reportID = excluded.reportID;
kuHHSN	db1.sjc	2024-01-24 08:03:14 118	we@dont.know	Unique Constraints Violation, command: SetReportNameValuePairs
```
That means this is probably a dupe of all these issues:
https://github.com/Expensify/Expensify/issues/360258
https://github.com/Expensify/Expensify/issues/354848
https://github.com/Expensify/Expensify/issues/351255

I am going to close this one for now so we can focus on the others and leave a note on the others so we don't duplicate the effort.

**Closed by iwiznia** 2024-01-24 20:20 UTC
Labels: Engineering, Daily, Internal, Bug, Hot Pick
