### ISSUE TITLE
[HOLD for payment 2023-05-23] [$1000] [HOLD for payment 2023-05-22] Unable to drag and drop an attachment after trying to upload a non-supported attachment.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18888] opened 2023-05-13 15:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. On [staging.new.expensify.com](http://staging.new.expensify.com/), upload a non supported file.
2. Close the error message.
3. Drag and drop a supported file to the chat.

## Expected result:
Attachment preview modal shows up.
## Actual result:
Nothing happens.

## Workaround:
Upload the supported file using the ‘Add attachment’ button
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0c627497-4cc9-4274-a835-091943a5f220

https://github.com/Expensify/App/assets/43996225/1a570685-821e-4af5-8eb7-6bcc27bfa31a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683918518994549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e02c3225827dbfe9</li>
        <li>Upwork Job ID: 1658541353564557312</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by abdulrahuman5196** [comment] 2023-05-13 15:45
Potential PR caused this regression - https://github.com/Expensify/App/pull/18624

**Comment by akinwale** [comment] 2023-05-13 15:50
This is due to changes in this PR: https://github.com/Expensify/App/pull/18624

The `isAttachmentPreviewActive` state is not getting properly reset back to `false` because the `onModalHide` event handler never gets called. To fix this, `onModalHide` should be called in the `closeConfirmModal` method for the `AttachmentModal` component.

https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/components/AttachmentModal.js#L156-L158

```
closeConfirmModal() {
    this.setState({isAttachmentInvalid: false});
    if (_.isFunction(this.props.onModalHide)) {
        this.props.onModalHide();
    }
}
```

**Comment by mountiny** [comment] 2023-05-14 14:47
This is fixed, I think the only payment here is $1000 to @rushatgabhane for doing C+ review but its a regression so that should decrease the price paid out on the original issue

**Comment by mountiny** [comment] 2023-05-15 10:56
I think we should just pay $1000 to @rushatgabhane  here cc @michaelhaxhiu

**Comment by michaelhaxhiu** [comment] 2023-05-16 18:36
Offer sent to Satish G (on behalf of Rushat). Please DM me when you accept and I'll pay it out, close this!

https://www.upwork.com/jobs/~01e02c3225827dbfe9

**Comment by michaelhaxhiu** [comment] 2023-05-17 19:59
paid.

**Closed by michaelhaxhiu** 2023-05-17 19:59 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
