### ISSUE TITLE
[$250] mweb/safari - Signout - The screen slides up when user tries to sign out

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10760] opened 2022-09-01 18:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: User has the iOS banner at the top of the screen (Not sure if this is a deal breaker)
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Tap Profile > Workspace > Back button
4. Scroll down and attempt to sign out

## Expected Result:
User expects the screen to scroll down normally

## Actual Result:
The users screen keeps sliding back up when scrolling down, this makes it very difficult for the user to access the "sign out" button on mweb iOS

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web/safari

**Version Number:** 1.1.96.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187987954-9166955d-781d-4db5-8b51-abab5feb2724.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2022-09-02 14:53
[Upwork Job](https://www.upwork.com/jobs/~0100af7c505d1f9e74)

**Comment by liyamahendra** [comment] 2022-09-03 13:23
The root cause of this issue is the Smart Banner which is visible on staging and production website, when accessed on an iOS device. 

The issue won't occur when the Smart banner is not displayed, which should be evident if you try reproducing through the steps mentioned on localhost - on which the Smart Banner won't show up.

There was already an [issue for the Smart Banner](https://github.com/Expensify/App/issues/8791), under which we might completely remove the Smart Banner or have it displayed on all pages. (Currently, the Smart Banner isn't visible on the Workspace Page - which is evident from the video shared in the issue description).

Are we still looking to get this fixed?

**Comment by liyamahendra** [comment] 2022-09-03 17:15
@parasharrajat you rightly shared that banners hides on the Workspace page and causes a weird pacing issue under the Modal. When the user comes back from the Workspace page, the height isn't recalculated / adjusted which causes issue in subsequent navigation. My analysis in my previous comment comes from having spent time on the referenced issue. 

As seen locally:

https://user-images.githubusercontent.com/911879/188281403-caaac0c1-ffb2-4c98-ba31-61364159ad9e.mp4



@kbecciv  @parasharrajat Are you able to reproduce this locally? If not, how do you suggest to reproduce this locally and test a fix?

**Comment by MitchExpensify** [comment] 2022-09-13 08:27
Have you had a chance to try and reproduce this @liyamahendra ?

**Comment by liyamahendra** [comment] 2022-09-13 08:35
I don't have the steps to reproduce this locally. @MitchExpensify

**Comment by zanyrenney** [comment] 2022-09-13 11:25
Hmm, no, I cannot reproduce this, the sign out button is not hidden on Safari. 

Steps taken:
- Log in to new.expensify.com on staging. 
- Scroll down on home page
- Row for Sign out is visible
- Able to click Sign out and sign out successfully

iOS version: 16.6.1 
iPhone 11

https://user-images.githubusercontent.com/56830058/189889058-4a313575-5ef0-45b6-b7a3-be637dc4b674.MP4

**Comment by MonilBhavsar** [comment] 2022-09-13 11:34
Thank you for testing!
I'm also not able to reproduce on simulator and my old iOS device. So going to close this issue.
@kbecciv feel free to reopen if you still see this issue. I think it could be version specific issue. So could you please mention iOS/Safari version. Thank you!

**Closed by MonilBhavsar** 2022-09-13 11:34 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
