### ISSUE TITLE
[HOLD for payment 2024-10-30] A newly added card under the Members section does not appear in the Assigned Cards section.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50441] opened 2024-10-08 17:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728308001803959

## Action Performed:
1. Navigate to Settings > Workspaces > Select any workspace that has Expensify Cards enabled and where you have permissions to add a card.
2. Go to Members > Select any member > New Card.
3. Fill in the card details and complete the issue card flow.
4. Check the Assigned Cards section under the member's details.
## Expected Result:
The card should be added to the Assigned Cards section immediately.

## Actual Result:
The card does not appear until you navigate away to Workspaces and then return to the Member details page.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b0bc02a0-61e9-41ca-affc-81f815138de2

https://github.com/user-attachments/assets/9fadb56c-08df-4eb6-b7fc-9703a3137786

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by mountiny** [comment] 2024-10-08 20:56
@koko57 We need to add the card optimistically to the cards_ collection to show there, I believe you already working on that elsewhere, if so, can you comment so I can assign you? thanks!

**Comment by koko57** [comment] 2024-10-09 02:40
yes, I can work on that with https://github.com/Expensify/App/issues/50248 and https://github.com/Expensify/App/issues/50467 - they are related so I will fix them all in one PR

**Comment by stephanieelliott** [comment] 2024-10-11 04:26
@koko57 can you link the PR when you have it?

**Comment by koko57** [comment] 2024-10-11 04:32
@stephanieelliott yes! I'm still working on it. Sorry for not posting updates here, I left some in these two other issues I mentioned. We also had a discussion yesterday on how to solve this problem on Slack

**Comment by koko57** [comment] 2024-10-11 13:10
it looks like it's rather the same root cause as https://github.com/Expensify/App/issues/50467, here we don't have the info for which type of card it happened. If for both it could be due to some error - the error handling is applied here: https://github.com/Expensify/App/pull/50644

cc @mountiny

**Comment by koko57** [comment] 2024-10-11 13:51
I'll be ooo Monday - Tuesday (14-15 Oct) if there will be some changes required to my PR and you'd like to merge it asap - please ping Callstack team, someone might be able to take it over. Thanks!

**Comment by mountiny** [comment] 2024-10-14 10:18
Thanks, yeah I think we are nicely streamlining the process now

**Comment by stephanieelliott** [comment] 2024-10-23 02:39
Hey @koko57 any update on this one?

**Comment by DylanDylann** [comment] 2024-10-23 03:22
the PR is merged and deployed to staging

**Comment by koko57** [comment] 2024-10-23 03:52
yes, it's merged and can be retested. Sorry for no update!

**Comment by mountiny** [comment] 2024-10-23 11:01
Asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1729681305609559?thread_ts=1729680154.144859&cid=C9YU7BX5M)

**Comment by m-natarajan** [comment] 2024-10-23 13:51
Still able to reproduce, card not appears even after refresh

https://github.com/user-attachments/assets/2de41078-f8a1-47cb-89c2-b49da96b4dec

**Comment by koko57** [comment] 2024-10-23 15:04
this one is definitely strange, maybe some other changes broke it in the meantime, I will look at this tomorrow

**Comment by mountiny** [comment] 2024-10-24 04:30
I think the create card call failed and that is why its not showing

**Comment by mountiny** [comment] 2024-10-24 04:51
I have asked for another retest, @koko57 have you been able to reproduce it?

**Comment by koko57** [comment] 2024-10-24 04:52
Looking into it in a minute

**Comment by koko57** [comment] 2024-10-24 05:48
Ok, I was able to reproduce - I'm digging into the code now

**Comment by koko57** [comment] 2024-10-24 06:07
When I was issuing a card for myself I could not reproduce. The cards were added properly. But when I invited a new member any card that I've added haven't appeared in the list. 

<img width="579" alt="Screenshot 2024-10-24 at 13 02 45" src="https://github.com/user-attachments/assets/5092f993-53ed-4162-ba8f-8d6122a5e185">


It's because we're using a wrong(?) Onyx key for querying cards

<img width="834" alt="Screenshot 2024-10-24 at 13 01 29" src="https://github.com/user-attachments/assets/0073b418-e873-458c-8f06-522fae440aa3">

and that's why we don't get the newly created card - observe that for the cards_ collection we have a new card.
<img width="834" alt="Screenshot 2024-10-24 at 13 01 29" src="https://github.com/user-attachments/assets/5ff6074b-8540-4348-aca2-68d2e31a1008">

I need to look at why we use this key, why it only stores the current user's (not an invitee's) card and if the key is used for company cards.

**Comment by koko57** [comment] 2024-10-24 06:59
@mountiny - this was an intentional change, Vicky left a comment why it was necessary. Now I need to figure out a solution, maybe query for both cards_ and cardList? And then filter out the ones already in the  cards_ object?

**Comment by VickyStash** [comment] 2024-10-24 06:59
I've answered about the reason of `cards_` -> `cardList_` update here: https://github.com/Expensify/App/pull/49928#discussion_r1814374460

But does the `cardList_` key store only current user cards?
If so, to show all user related cards from different feeds we need to:
1. Do multiple calls to get cards for every feed
2. Have an API call to get all of the cards for all of the feeds

**Comment by koko57** [comment] 2024-10-24 07:01
But can't we query cards_ for expensify cards and feeds separately? If I understand it correctly cardList contains Expensify Cards and Feeds?

**Comment by koko57** [comment] 2024-10-24 07:02
And the question is why the cards for another member doesn't appear in the cardList? Is it because for the current user (admin) only there is an additional logic on the backend that adds any card (Expensify or 3rd party) to the cardList object?

**Comment by VickyStash** [comment] 2024-10-24 07:05
> But can't we query cards_ for expensify cards and feeds separately? If I understand it correctly cardList contains Expensify Cards and Feeds?

The thing is that `cardList_` key populated by `OpenApp` command. So it has the data right away.
To populate `cards_` key we need to do API calls to get the data.
It can be 6+ calls, for example, if we need to get Expensify cards + 5 feeds cards.

**Comment by mountiny** [comment] 2024-10-25 08:25
Ok yeah i was wondering if thsi is the issue. The two onyx keys hold different values


cardList is all **your** cards those that you as the currently assigned user own

cards_ collection is only for the domain admins where you can see all the cards on particular feed.

So i think what we need to do is update the member details page to look at cardList if its your own page (the signed in user) and the cards_ if not.

**Comment by koko57** [comment] 2024-10-25 13:09
@mountiny I opened a draft PR for fixing the Expensify Card issues, I haven't got an idea yet how to solve the problem for the 3rd party feeds. 

I wonder if we can proceed with this fix only and then fix company cards in another PR, or should we work on it here

**Comment by koko57** [comment] 2024-10-25 13:55
PR opened for review https://github.com/Expensify/App/issues/50441

**Comment by DylanDylann** [comment] 2024-10-30 06:44
[Asking](https://expensify.slack.com/archives/C05LX9D6E07/p1730219754826249?thread_ts=1728966082.429659&cid=C05LX9D6E07) for the next step

**Comment by stephanieelliott** [comment] 2024-10-31 08:39
Summarizing payment on this issue: 

 - Contributor: N/A (agency)
 - Contributor+: @DylanDylann $250 via Upwork - offer extended, please accept!
 
 Upwork job is here: https://www.upwork.com/jobs/~021851906318833506897

**Comment by DylanDylann** [comment] 2024-10-31 11:40
@stephanieelliott Done

**Comment by stephanieelliott** [comment] 2024-11-05 08:22
All paid!

**Closed by stephanieelliott** 2024-11-05 08:22 UTC
Labels: Reviewing, Daily, Awaiting Payment, Bug
