### ISSUE TITLE
[$2000] Android- PDF Scrolling Issue: Difficulty in Navigating Through Pages

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23417] opened 2023-07-23 14:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Initiate a chat with another user
2 Go to + > add attachment >choose document > upload a multipage pdf file
3 Open the pdf file and scroll down and up
4 Verify if its smooth
5 Now, upload an image
6 Go back to the pdf file and try to scroll up-down
7 Verify if the image opens (Next image is selected when swiping the screen up and down)
## Expected Result: 
Smooth interaction with pdf. No difficulty in scrolling pdf pages
## Actual Result: 
Difficulty in scrolling through pdf. Sometimes another document opens instead of scrolling

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/319bec3f-9bdd-4090-a0a5-f4b038e23d5e

https://github.com/Expensify/App/assets/43996225/90582094-35e4-448d-8293-f2cd77bd6710

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690006696574999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef34bf6d94d34d3b</li>
        <li>Upwork Job ID: 1686884315196669952</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>HezekielT | Contributor | 27284015</li>
<li>avi-shek-jha | Reporter | 27284018</li>
</ul></li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-07-26 19:59
Thanks for the callout, @ShogunFire!

**Comment by johncschuster** [comment] 2023-08-01 22:35
@kavimuru the above-linked issue and PR has been closed. Can you please try reproducing the reported behavior in this issue to see if it persists?

**Comment by avi-shek-jha** [comment] 2023-08-02 01:59
@johncschuster Hi, I reported this one and since, I was free today so I took the time to retest it. The problem still persists. I tested it on the latest build of Android v1.3.48-5. 


https://github.com/Expensify/App/assets/123831727/1df94ead-f8f5-4d66-9fbe-193764fe27b3

**Comment by johncschuster** [comment] 2023-08-02 23:38
Ok cool. Thanks for confirming!

**Comment by jaylalakiya** [comment] 2023-08-03 11:05
This is happening because of scrolling conflict between FlatList and Document component by react-pdf package.
We have horizontal FlatList of attachments and if particular attachment is pdf, we are rendering it using Document component by react-pdf package. When user tries to scroll pdf, scroll event of parent FlatList also gets triggered.

We should disable horizontal FlatList scrolling when pdf is being scrolled vertically. But according to my research, there is no default way of getting scroll related events from react-pdf package ([https://github.com/wojtekmaj/react-pdf]). 

Waiting for senior's reply to move further.

**Comment by mollfpr** [comment] 2023-08-07 17:07
> This is happening because of scrolling conflict between FlatList and Pdf component by react-native-pdf package.

@jaylalakiya That might be correct, but I don't have much context since I can't test sending attachments in the latest `main`. If you have another solution, please submit a proposal, and I'll gladly review it. Thanks!

**Comment by johncschuster** [comment] 2023-08-09 20:36
@mollfpr what do you think? It seems like we should raise the bounty.

**Comment by thealmikey** [comment] 2023-08-09 20:50
Hey, I think I have a workaround, it's my first contribution too :)

### Proposal

#### Problem Statement:

In the carousel, when users attempt to scroll through a PDF, they face a conflict between the horizontal scrolling of the FlatList carousel and the vertical scrolling of the PDF component. This makes the page unscrollable in the carousel when transitioning between an image and a PDF.

#### Root Cause:

Matches what @jaylalakiya mentioned above ->

The primary cause of this issue is a scrolling conflict between the FlatList component and the Pdf component from the `react-native-pdf` package. Specifically, on Android, when a user tries to scroll the PDF vertically, the horizontal scroll event of the parent FlatList is also triggered. This behavior has been identified in multiple issues within the `react-native-pdf` package's repository.

#### Proposed Solution:

- **Utilize PanGestureHandler in AttachmentViewPdf:** Implement the `PanGestureHandler` from the `react-native-gesture-handler` library within the `AttachmentViewPdf` component. This will allow us to differentiate between vertical and horizontal swipes and control the scrolling behavior of the PDF.

##### Code Snippets and File Names:

In `AttachmentViewPdf.js`:

```javascript
import { PanGestureHandler, State } from 'react-native-gesture-handler';

function AttachmentViewPdf({ /* ...props... */ }) {
    // ... existing code ...

    const onGestureEvent = ({ nativeEvent }) => {
        if (nativeEvent.state === State.END) {
            if (Math.abs(nativeEvent.translationY) > Math.abs(nativeEvent.translationX)) {
                // This is a vertical swipe, allow the PDF to scroll
            } else {
                // This is a horizontal swipe, handle carousel navigation
                if (nativeEvent.translationX > SWIPE_THRESHOLD) {
                    attachmentCarouselPagerContext.goToPrevious();
                } else if (nativeEvent.translationX < -SWIPE_THRESHOLD) {
                    attachmentCarouselPagerContext.goToNext();
                }
            }
        }
    };

    return (
        <PanGestureHandler
            onGestureEvent={onGestureEvent}
            onHandlerStateChange={onGestureEvent}
        >
            <PDFView
                // ... existing props ...
            />
        </PanGestureHandler>
    );
}```

#### Rationale:


By implementing the `PanGestureHandler` within the `AttachmentViewPdf` component, we can differentiate between vertical and horizontal swipes. This allows us to handle the PDF's vertical scrolling and the carousel's horizontal navigation separately, addressing the core issue of the scrolling conflict between the two components.

**Comment by thealmikey** [comment] 2023-08-09 20:53
Contributor details
Your Expensify account email: thealmikey@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019966dd8999703d47

**Comment by thealmikey** [comment] 2023-08-09 23:01
https://github.com/Expensify/App/assets/3298815/fb6e6b30-81e8-4ddd-9900-3f0405f21379

Tested on my emulator

**Comment by mollfpr** [comment] 2023-08-14 17:58
Sorry for the delay, I got sick a few days ago 🙏

Checking the proposals now.

**Comment by thealmikey** [comment] 2023-08-14 18:17
Really sorry, hope it's nothing seruiys and you're feeling better... @mollfpr 🧑🏾‍⚕️
Take your time, was just taking my shot on the issue 🙂

**Comment by mollfpr** [comment] 2023-08-22 11:52
I'm back! Apologies for the wait 🙏

Thanks, @thealmikey, for the proposal. Could you update your proposal following the [template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md)?

> The primary cause of this issue is a scrolling conflict between the FlatList component and the Pdf component from the react-native-pdf package.

@jaylalakiya @thealmikey I don't see that our native `AttachmentCarousel` uses `FlatList` to render the attachments. Am I missing something?

**Comment by thealmikey** [comment] 2023-08-22 19:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When users view a multi-page PDF in the AttachmentCarousel and attempt to scroll through it, they experience difficulty in scrolling. In some instances, while trying to scroll within the PDF, the carousel unexpectedly navigates to the next attachment instead of scrolling the PDF.

### What is the root cause of that problem?
The root cause is a scrolling conflict between the FlatList's horizontal swipe gesture used in the AttachmentCarousel and the PDF's vertical scroll gesture. When a user tries to scroll vertically within the multi-page PDF, the horizontal swipe gesture of the FlatList sometimes takes precedence, causing the carousel to navigate to the next attachment instead of scrolling the PDF.

### What changes do you think we should make in order to solve the problem?
I propose implementing the PanGestureHandler from the react-native-gesture-handler library within the AttachmentViewPdf component. This will allow us to differentiate between vertical and horizontal swipes, giving us more control over the scrolling behavior of the multi-page PDF within the carousel. When a vertical swipe is detected, we'll allow the PDF to scroll. When a horizontal swipe is detected, we'll trigger the carousel's navigation. This ensures that the user's intention to scroll within the PDF or navigate to the next attachment is accurately captured and executed.

### What alternative solutions did you explore?
An alternative solution could be to adjust the sensitivity or threshold of the swipe gestures, but this might not provide a consistent user experience across different devices and screen sizes. Another option could be to implement custom gesture handlers, but using a well-maintained library like react-native-gesture-handler is more efficient and reliable.

**Comment by thealmikey** [comment] 2023-08-22 19:31
@mollfpr Did the correction, here's the link where the Flatlist mentioned above can be found https://github.com/Expensify/App/blob/af7b05755b1d42aa7dfa5b47105da504b14dff76/src/components/Attachments/AttachmentCarousel/index.js#L193

**Comment by mollfpr** [comment] 2023-08-25 02:26
@thealmikey That's for web/desktop, and for native, we not using FlatList right?
https://github.com/Expensify/App/blob/af7b05755b1d42aa7dfa5b47105da504b14dff76/src/components/Attachments/AttachmentCarousel/index.native.js#L134

**Comment by thealmikey** [comment] 2023-08-25 14:50
@mollfpr I think there's some shared components in the system, my changes seem to change behavior.
Thought I was in the right place from the import.
https://github.com/Expensify/App/blob/af7b05755b1d42aa7dfa5b47105da504b14dff76/src/components/Attachments/AttachmentCarousel/index.native.js#L2
Think this might require more tracing

**Comment by mollfpr** [comment] 2023-08-28 17:27
We are still waiting for a proposal that can address the root cause of the Android.

**Comment by johncschuster** [comment] 2023-08-29 19:38
Thanks for the update, @mollfpr!

**Comment by mollfpr** [comment] 2023-09-01 17:02
No new proposals

**Comment by mollfpr** [comment] 2023-09-04 17:42
Not overdue

**Comment by johncschuster** [comment] 2023-09-05 20:13
@mollfpr do you feel we need to increase the bounty to get more proposals?

**Comment by mollfpr** [comment] 2023-09-06 04:48
@johncschuster Yes, please!

**Comment by mollfpr** [comment] 2023-09-11 16:53
No new proposals.

**Comment by mollfpr** [comment] 2023-09-14 14:20
No new proposals.

**Comment by mollfpr** [comment] 2023-09-18 10:17
No new proposals.

**Comment by johncschuster** [comment] 2023-09-19 20:47
Posted in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1695156432593879) to get more eyes on this one.

**Comment by studentofcoding** [comment] 2023-09-20 04:50
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Android- PDF Scrolling Issue: Difficulty in Navigating Through Pages

## What is the root cause of that problem?

The issue arises possibly from the handling of the pan gesture in the `ImageTransformer.js` file. The pan gesture, responsible for scrolling, is activated when the zoom scale is greater than 1. This can lead to unexpected scrolling behavior as the pan gesture might be activated unintentionally.

Additionally, the swipe gesture, responsible for switching between attachments, might be too sensitive and could be activated when the user is trying to scroll.

## What changes do you think we should make in order to solve the problem?

Change `panGesture` details on `ImageTransformer.js` to include the condition of
- if the user is currently zooming in on the PDF, and
- Increase the velocity thresholds here to adjust the sensitivity of the swipe gesture to 500

```
const panGesture = Gesture.Pan()
    .manualActivation(true)
    .averageTouches(true)
    .onTouchesMove((evt, state) => {
        // Add additional conditions here to ensure the pan gesture is only activated when intended
        if (zoomScale.value > 1 && !userIsCurrentlyZooming) {
            state.activate();
        }
    })
    //... Other Code
    .onEnd((evt) => {
        previousTouch.value = null;

        if (isScrolling.value) {
            return;
        }

        offsetX.value += translateX.value;
        offsetY.value += translateY.value;
        translateX.value = 0;
        translateY.value = 0;

        if (isSwiping.value) {
            // Increase the velocity thresholds here to adjust the sensitivity of the swipe gesture
            const enoughVelocity = Math.abs(evt.velocityY) > 500 && Math.abs(evt.velocityX) < Math.abs(evt.velocityY);
            const rightDirection = (evt.translationY > 0 && evt.velocityY > 0) || (evt.translationY < 0 && evt.velocityY < 0);

            if (enoughVelocity && rightDirection) {
                // Rest of the code...
            }
        }

        afterPanGesture();

        panVelocityX.value = 0;
        panVelocityY.value = 0;
    })
    .withRef(panGestureRef);
    
```

## What alternative solutions did you explore? (Optional)

None

cc: @johncschuster @mollfpr

**Comment by mollfpr** [comment] 2023-09-25 16:51
Not overdue, will review the latest proposal in the morning.

**Comment by mollfpr** [comment] 2023-09-28 11:26
Sorry for the delay!

@studentofcoding I tried your solution but didn't find it working. Also, the issue in upstream you attached has a different problem with this.

>Upon checking and add <ScrollView contentContainerStyle={{ flex: 1 }}> for wrapping PDFView it fixed, the problem

You should have specified the reason why this can fix the problem.

**Comment by mollfpr** [comment] 2023-10-02 15:26
Not overdue, still waiting for other proposals.

**Comment by johncschuster** [comment] 2023-10-04 21:19
What are your thoughts on this one, @mollfpr?

**Comment by mollfpr** [comment] 2023-10-10 17:32
Still looking for a better solution here.

**Comment by johncschuster** [comment] 2023-10-13 20:38
Posted in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1697229467692369) to get more proposals

**Comment by johncschuster** [comment] 2023-10-16 20:54
@mollfpr what do you think of the above proposal?

**Comment by mollfpr** [comment] 2023-10-17 05:09
@HezekielT I just tested your proposal on an Android physical device, and it's working well, but on the iOS simulator, I can swipe left/right on the PDF to navigate to other attachments.


https://github.com/Expensify/App/assets/25520267/a6537a34-9a07-4d6c-9b62-ef9d1e121e99

**Comment by mollfpr** [comment] 2023-10-18 11:01
@HezekielT Can we move the current `index.native.js` to a new base component so we don't need to do the same twice for `index.ios.js` and `index.android.js`?

**Comment by mollfpr** [comment] 2023-10-19 11:04
Okay, the proposal looks good, and we can improve the code while reviewing the PR so it will be easier. Let's go with @HezekielT [proposal](https://github.com/Expensify/App/issues/23417#issuecomment-1762822130), then.

🎀 👀 🎀 C+ reviewed!

@johncschuster Could you help add the `Engineering` label? Thanks!

**Comment by avi-shek-jha** [comment] 2023-10-19 21:04
Hello, This issue was reported on July 23 before the new changes took place. Can someone please send me the corrected offer as I received the one for 50 dollars instead of 250 for older issues?

**Comment by mollfpr** [comment] 2023-10-20 03:22
@HezekielT Let me know when the PR is ready because Melvin will not request my review. Thank you!

@avi-shek-jha I think @johncschuster will take care of that.

**Comment by johncschuster** [comment] 2023-10-20 11:14
@avi-shek-jha, I've adjusted your offer to account for the previous Bug Reporter amount. Thanks for calling that out!

**Comment by avi-shek-jha** [comment] 2023-10-20 17:37
> @avi-shek-jha, I've adjusted your offer to account for the previous Bug Reporter amount. Thanks for calling that out!

Thank you John. Accepted.

**Comment by mollfpr** [comment] 2023-11-06 16:43
Not overdue. The PR is merged.

**Comment by johncschuster** [comment] 2023-11-07 21:00
Oh boy, I literally just paid this out too 😅.

@Gonals, I'll follow your lead on this one.

**Comment by mollfpr** [comment] 2023-12-05 11:01
@johncschuster I think this was ready for payment. Could you give the payment summary to make a manual request? Thanks!

**Comment by mollfpr** [comment] 2023-12-20 11:35
> The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. This difference in behavior between Android and iOS is causing the issue.

>A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good.

>Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open any report
2. Click on + of the composer.
3. Select Add attachment > Choose document > upload a multi-page pdf file.
4. Open the pdf file and scroll up and down.
5. Verify the scroll is smooth.
6. Close the attachment and Click on + of the composer again.
7. Upload an image.
8. Open the image and swipe to the left.
9. Verify the previously sent pdf is opened.
10. Scroll through the pdf up and down.
11. Verify the scroll is smooth.

---

Friendly bump @johncschuster

**Comment by mollfpr** [comment] 2024-01-08 16:50
Friendly bump @johncschuster

**Comment by mollfpr** [comment] 2024-01-29 18:14
Friendly bump @johncschuster

**Comment by JmillsExpensify** [comment] 2024-01-30 19:28
$2,000 payment approved for @mollfpr based on summary above.

**Closed** 2024-01-31 15:37 UTC
Labels: Reviewing, External, Engineering, Monthly, Bug
