### ISSUE TITLE
mWeb - Tags - On creating scan expense, billable option is toggled off

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53443] opened 2024-12-03 11:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5292403
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-condition:As admin, rebill expenses to clients set default to billable
1. Go to https://staging.new.expensify.com/home
2. Login as employee
3. Open employee workspace chat
4. Try to create manual and distance expense
5. Note billable option is toggled on
6. Try to create scan expense
7. Note billable option is toggled off

## Expected Result:
On creating scan expense, billable option is toggled must be on.

## Actual Result:
On creating scan expense, billable option is toggled off.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/03edbbeb-031b-4b22-abce-80d051107c16

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-12-03 11:13
Production 

https://github.com/user-attachments/assets/17bfa4e1-1bed-4748-abc7-fa4bce249fd8

**Comment by jasperhuangg** [comment] 2024-12-03 18:25
Haven't been able to test this yet but I'm not confident that it isn't coming from the back-end so I'm adding the label in the meantime.

**Comment by jasperhuangg** [comment] 2024-12-03 19:24
Can't reproduce this, closing


https://github.com/user-attachments/assets/c497ab2c-81eb-4c8f-8334-4cc6c5f3dd85

**Closed** 2024-12-03 19:25 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug, DeployBlocker
