### ISSUE TITLE
Reports-In report page, deleted expense is shown.

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#54365] opened 2024-12-19 14:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.77-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team
**Device used:** Redmi note 10s android 13
**App Component:** Search

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login with new gmail account
3. Tap fab - new workspace
4. Navigate to reports
5. Tap plus icon and create a expense using new workspace
6. Long press the expense shown and delete it

## Expected Result:
In report page, deleted expense must not be shown.

## Actual Result:
In report page, deleted expense is shown.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1ee1cb3a-a159-4b56-88a5-d962b0fe3bc6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mitarachim** [comment] 2024-12-19 14:28
Issue not reproduce when we disabled `Use Staging Server`

https://github.com/user-attachments/assets/3e1a4a18-7c08-4ec3-91d3-f1185e0bd290

**Comment by arosiclair** [comment] 2024-12-19 16:18
Confirmed that this is not reproducible with **Use Staging Server** disabled. This should be a web blocker.

**Comment by arosiclair** [comment] 2024-12-19 16:38
It doesn't look like there's anything wrong with `DeleteMoneyRequestOnSearch` on staging. The responses look similar on staging and prod. 

Instead I think there's something broken with creating the expense in `RequestMoney`. If I create the expense with prod and delete it with staging, it works fine. Only creating the expense on staging causes the issue.

**Comment by arosiclair** [comment] 2024-12-19 17:29
I'm more confused now.

- I looked at the diff between staging and prod for `RequestMoney` and `DeleteMoneyRequestOnSearch` responses and didn't notice any important differences
- In `DeleteMoneyRequestOnSearch` response, there's an update to clear the report and transaction from the snapshot but from logs and the values in IndexedDB, this is NOT being merged:

<img width="656" alt="Screenshot 2024-12-19 at 12 19 37 PM" src="https://github.com/user-attachments/assets/6f0f750f-71f4-4172-be2e-3d4b631270ca" />

So I think the root of this problem lies more in the way we're processing Onyx updates. Which means this might actually need to be an App blocker.

**Comment by arosiclair** [comment] 2024-12-19 17:56
I don't see any relevant App changes in the current deploy 😕. I'll try reproducing this in dev and finding the root cause.

**Comment by arosiclair** [comment] 2024-12-19 20:58
Unfortunately, I'm having trouble reproducing in dev. And now even on staging I'm having trouble reproducing 🙃. 

I think there's probably a subtle bug with the way Onyx updates are handled here, but I don't think any of the changes in the current deploy are causing it. I'm going to demote this and revisit next week to see if it's still reproducible.

**Comment by arosiclair** [comment] 2024-12-23 17:44
No updates. Waiting until the next deploy.

**Comment by arosiclair** [comment] 2024-12-26 16:18
Still not reproducible in **v9.0.78-2**:

https://github.com/user-attachments/assets/1930350d-4865-4f16-b2c6-0e896380c7a3

Closing this out

**Closed by arosiclair** 2024-12-26 16:18 UTC
Labels: Daily, Overdue, Bug

**Comment by IuliiaHerets** [comment] 2025-01-21 15:36
QA team can repro this issue in the latest build - v9.0.88-4

https://github.com/user-attachments/assets/f5f6acd0-49df-4b42-b635-cf2fbc82b239
