### ISSUE TITLE
[Pay meow][$250] Web - Composer - Cursor positioned at the start if pasting text which contains a new line

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#42216] opened 2024-05-15 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open a chat and type a one line text and create an empty new line
3. Select all using keyboard ctrl + A and cut the text
4. Paste it inside the compose box

## Expected Result:
The cursor gets positioned at the end of the pasted text, no console error

## Actual Result:
The cursor gets positioned at the start of the pasted text if the pasted text contains a new empty line, console error is showing

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/776b5c51-77c3-4fdd-94bc-9f33b61804ff

<img width="1639" alt="image" src="https://github.com/Expensify/App/assets/51066321/cf37f25c-7f48-4d56-a344-42de2eb5aac7">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc45b59ee9c4ae02</li>
        <li>Upwork Job ID: 1792451156946927616</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-05-15 20:29
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment] 2024-05-15 20:49
@Christinadobrzyn FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Christinadobrzyn** [comment] 2024-05-16 05:29
Very similar to https://github.com/Expensify/App/issues/42112 - asking if the fix will be the same

**Comment by moonstar-95515** [comment] 2024-05-16 12:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Composer - Cursor positioned at the start if pasting text which contains a new line

### What is the root cause of that problem?
We are setting cursor position in below part when pasting.
https://github.com/Expensify/App/blob/fb14d5a4970374a2377483e70eb5f974354570b5/src/hooks/useHtmlPaste/index.ts#L19-L20

When pasted text contains empty line, the value of `node.length` is greater than it's actually length because the length of line break at the end(`\n\n`) will be caculated as 2.
So console error occurs and cursor is not set because we are trying to set cursor to non-exist position.

### What changes do you think we should make in order to solve the problem?
We have to set range with `node.length - 1` when it contains empty line at the end.

### What alternative solutions did you explore? (Optional)

**Comment by jscoder21321** [comment] 2024-05-16 16:36
Contributor details
Your Expensify account email: jscoder21321@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by jscoder21321** [comment] 2024-05-16 16:38
Contributor details
Your Expensify account email: jscoder21321@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by Christinadobrzyn** [comment] 2024-05-20 07:03
Doesn't seem to be related to https://github.com/Expensify/App/issues/42112 as that is resolved. I can still reproduce this - adding external

**Comment by rakhaxor** [comment] 2024-05-20 10:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Composer - Cursor positioned at the start if pasting text which contains a new line

### What is the root cause of that problem?
In the `text` param, newline character(s) at the end (if present) are wrongly interpreted by the cursorUtils library because `node.length` is calculated including the \n but \n is not inserted in the document node which makes the range go out of bounds.
https://github.com/Expensify/App/blob/e6c9f06a0952434f3f8ff9ace267c0e3ca026e8e/src/hooks/useHtmlPaste/index.ts#L10

### What changes do you think we should make in order to solve the problem?
const plainText = text.replace(/\n+$/, '');
And use this in all the places we are using text:
`const node = document.createTextNode(text);`
`insertByCommand(text);`

### What alternative solutions did you explore? (Optional)
None

**Comment by RickDeb2004** [comment] 2024-05-20 11:20
### **Proposal**

### **Please re-state the problem that we are trying to solve in this issue.**
when pasting text containing a new empty line into the chat compose box, the cursor incorrectly positions itself at the start of the text instead of the end and a console error occurs.

### **What is the root cause of that problem?**
The root cause of the problem is that the cursor positioning logic in the [**insertAtCaret**](https://github.com/Expensify/App/blob/e6c9f06a0952434f3f8ff9ace267c0e3ca026e8e/src/hooks/useHtmlPaste/index.ts#L10) function incorrectly handles the insertion of text containing new lines. Specifically, the cursor is not being moved to the correct position (the end of the newly inserted text) when the text includes empty new lines, which causes the cursor to appear at the start of the text. Additionally, there is no proper error handling to catch and log any potential issues during the paste operation, leading to console errors.

### **What changes do you think we should make in order to solve the problem?**

a) 
**original code :**
   
 ```
 range.setStart(node, node.length);
        range.setEnd(node, node.length);
        selection.removeAllRanges();
        selection.addRange(range);
```
  **modified code:**
```
 range.setStartAfter(node);
        range.setEndAfter(node);
        selection.removeAllRanges();
        selection.addRange(range);
 
```
b) 
**original code :**
   
 ```
 target.dispatchEvent(new Event('paste', {bubbles: true}));
        // Dispatch input event to trigger Markdown Input to parse the new text
        target.dispatchEvent(new Event('input', {bubbles: true}));
    } else {
        insertByCommand(text);
    };

```
  **modified code:**
```
 target.dispatchEvent(new Event('input', {bubbles: true}));
    } else {
        insertByCommand(text);
    }
 
```
c) 
**original code :**
   
 ```
const paste = useCallback((text: string) => {
        try {
            const textInputHTMLElement = textInputRef.current as HTMLElement;
            if (textInputHTMLElement?.hasAttribute('contenteditable')) {
                insertAtCaret(textInputHTMLElement, text);
            } else {
                insertByCommand(text);
            }

            // Pointer will go out of sight when a large paragraph is pasted on the web. Refocusing the input keeps the cursor in view.
            textInputRef.current?.blur();
            textInputRef.current?.focus();
            // eslint-disable-next-line no-empty
        } catch (e) {}
        // We only need to set the callback once.
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);
```
  **modified code:**
```
 const paste = useCallback((text: string) => {
        try {
            const textInputHTMLElement = textInputRef.current as HTMLElement;
            if (textInputHTMLElement?.hasAttribute('contenteditable')) {
                insertAtCaret(textInputHTMLElement, text);
            } else {
                insertByCommand(text);
            }

            // Pointer will go out of sight when a large paragraph is pasted on the web. Refocusing the input keeps the cursor in view.
            textInputRef.current?.blur();
            textInputRef.current?.focus();
        } catch (e) {
            // ** Added console error log here **
            console.error('Error during paste handling:', e);
        }
    }, []);

 
```

### **Summary of Changes**
**1.Cursor Positioning Fix:**

Updated the insertAtCaret function to use range.setStartAfter(node) and range.setEndAfter(node) to correctly position the cursor at the end of the newly inserted text, especially when new lines are involved.

**2.Error Handling:**

Added console.error logging within the paste function to handle and log any exceptions that occur during the paste operation, making it easier to debug issues.
These changes ensure that the cursor is positioned correctly after pasting text with new lines and improve error visibility during paste operations.

**Comment by Christinadobrzyn** [comment] 2024-05-21 05:13
hi @eVoloshchak can you take a peek at these proposals when you have a moment? TY!

**Comment by eVoloshchak** [comment] 2024-05-21 17:27
> We have to set range with node.length - 1 when it contains empty line at the end.
@moonstar-95515, that works for this specific case of testing steps, but wouldn't work if pasted text end with 3 (or more) new lines

I think we should proceed with @rakhaxor's [proposal](https://github.com/Expensify/App/issues/42216#issuecomment-2120118241), it's clean and straightforward. It does cut off all of the new lines at the end of the pasted text, but that's what the backend does when you send the message, so this can be considered a small improvement

🎀👀🎀 C+ reviewed!

**Comment by moonstar-95515** [comment] 2024-05-21 21:28
@eVoloshchak 

> @moonstar-95515, that works for this specific case of testing steps, but wouldn't work if pasted text end with 3 (or more) new lines

My proposal works when it has 3 or more new lines at the end, as the text will  be `hello 111\n\n\n\n` when it has 3 new lines.

**Comment by moonstar-95515** [comment] 2024-05-21 21:58
@eVoloshchak 

> It does cut off all of the new lines at the end of the pasted text, but that's what the backend does when you send the message, so this can be considered a small improvement

I can't sure if I understood correctly, but I think only new lines at the end of the text will be cut.
If we copy text with new lines in the middle of the compose box and paste it again, new lines will be deleted. I think this is not what we want.



https://github.com/Expensify/App/assets/170007025/067a681e-9ce0-4747-bc4d-34b17bfaceee

**Comment by moonstar-95515** [comment] 2024-05-21 22:01
@eVoloshchak  cc: @Christinadobrzyn  @AndrewGable 

> It does cut off all of the new lines at the end of the pasted text, but that's what the backend does when you send the message, so this can be considered a small improvement

I can't sure if I understood correctly, but I think only new lines at the end of the text will be cut.
If we copy text with new lines in the middle of the compose box and paste it again, new lines will be deleted. I think this is not what we want.



https://github.com/Expensify/App/assets/170007025/067a681e-9ce0-4747-bc4d-34b17bfaceee

**Comment by rakhaxor** [comment] 2024-05-22 13:18
@eVoloshchak Thank you for accepting my proposal! This is my first time contributing and I just applied to the Upwork job like 3-4 hours ago. Do I need to do some further action before my upwork proposal is accepted and do I need to wait for it to be accepted before I could raise my PR?

**Comment by moonstar-95515** [comment] 2024-05-23 08:40
@eVoloshchak

**Comment by Christinadobrzyn** [comment] 2024-05-27 06:42
Dmd @eVoloshchak to see if he can take a peek at the recent comments. Thanks!

**Comment by eVoloshchak** [comment] 2024-05-27 12:40
@moonstar-95515, thank you for https://github.com/Expensify/App/issues/42216#issuecomment-2123510932, good catch, this is a case I've missed and it's definitely not the desired behavior.

I think we should proceed with @moonstar-95515's [proposal](https://github.com/Expensify/App/issues/42216#issuecomment-2115186516)
It's simpler and more efficient (since we don't need to iterate over the whole string with `replace`, we just need to check if the line ends with a line break)

Apologies for the confusion folks
cc: @AndrewGable

**Comment by rakhaxor** [comment] 2024-05-27 12:46
> @moonstar-95515, thank you for [#42216 (comment)](https://github.com/Expensify/App/issues/42216#issuecomment-2123510932), good catch, this is a case I've missed and it's definitely not the desired behavior.
> 
> I think we should proceed with @moonstar-95515's [proposal](https://github.com/Expensify/App/issues/42216#issuecomment-2115186516) It's simpler and more efficient (since we don't need to iterate over the whole string with `replace`, we just need to check if the line ends with a line break)
> 
> Apologies for the confusion folks cc: @AndrewGable

Hello @eVoloshchak! I have already sent proposal on Upwork and about to raise a PR. I think this is not a good way since I have put a lot of my time on it setting up everything. And my solution works as needed. Also for the moonstar's proposal, I believe he posted a video where he got "hi" text below the text he is writing, so it is working but I am not sure it would work with multiple lines in case there are newlines after the last character.

**Comment by moonstar-95515** [comment] 2024-05-27 12:49
@rakhaxor 

> Also for the moonstar's proposal, I believe he posted a video where he got "hi" text below the text he is writing, so it is working but I am not sure it would work with multiple lines in case there are newlines after the last character.

I've tested my proposal with multiple lines at the end and it's working properly.

**Comment by moonstar-95515** [comment] 2024-05-29 17:28
Hi, @AndrewGable 
Could you please assign me so that I can raise PR? Thanks.

**Comment by Christinadobrzyn** [comment] 2024-05-30 04:43
Double-checking with @AndrewGable that we're good with https://github.com/Expensify/App/issues/42216#issuecomment-2133401204

**Comment by moonstar-95515** [comment] 2024-05-31 06:31
Hi, @eVoloshchak 
PR is ready for review. I will upload videos asap.

**Comment by Christinadobrzyn** [comment] 2024-06-05 08:17
Melvbot update - watching PR - https://github.com/Expensify/App/pull/42892

**Comment by Christinadobrzyn** [comment] 2024-06-12 09:06
watching - https://github.com/Expensify/App/pull/42892

Just a heads up - I'm going to be ooo until June 24th. I'm not going to assign anyone new but if you need a new BZ teammate for any reason please feel free to ask for one to be assigned here.

**Comment by Christinadobrzyn** [comment] 2024-06-24 23:20
watching - https://github.com/Expensify/App/pull/42892

**Comment by mallenexpensify** [comment] 2024-06-25 00:04
@eVoloshchak @AndrewGable should we look at having another contributor, or internal engineer, get this over the finish line? It's been ~25 days since the contributor was assigned.  Thx

**Comment by kpadmanabhan** [comment] 2024-06-25 02:12
@mallenexpensify / @AndrewGable / @eVoloshchak : 

this is completely unprofessional and unacceptable to have multiple people working on the same issue and keeping one wait from proceeding with original issue for this long. expensify must bring in some sort of sanitization of process in recognizing duplicate issues before C+ reviewing and assigning these to multiple people. at the moment, I monitor issues and blow whistle in each of them like [this](https://github.com/Expensify/App/issues/42216#issuecomment-2140491997) for instance.

in fact, [this is the very first instance](https://github.com/Expensify/App/issues/39971) of reporting of this bug and the [related PR](https://github.com/Expensify/App/pull/41265) for the issue. 

if acceptable, i am ready to proceed with my PR fixing all related issues and regressions that I have kept track of, but with an increased bug bounty.

CC: @jayeshmangwani (C+ for original issue)

**Comment by mallenexpensify** [comment] 2024-06-25 16:41
@kpadmanabhan[ from CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=Daily%20updates%20on,original%20contract%20terminated.) 
> Daily updates on weekdays are highly recommended. If you know you won’t be able to provide updates within 48 hours, please comment on the PR or issue stating how long you plan to be out so that we may plan accordingly. We understand everyone needs a little vacation here and there. Any issue that doesn't receive an update for 5 days (including weekend days) may be considered abandoned and the original contract terminated.

I see almost no updates on the issue and only one comment on the PR over a 10 day period.  
<img width="932" alt="image" src="https://github.com/Expensify/App/assets/22508304/f5d99be7-2322-4c0c-82b4-c03556a8c931">

@moonstar-95515 our interest is fixing bugs quickly.  When do you foresee the PR being ready to be reviewed by @eVoloshchak ?

**Comment by moonstar-95515** [comment] 2024-06-25 17:04
@mallenexpensify 
Sorry for delay.
I've completed everything but test video for android.
Now I'm trying to build android version but I have some problems.
I will complete PR asap.

**Comment by Christinadobrzyn** [comment] 2024-07-02 21:25
Hi @moonstar-95515 checking on the PR - can you provide an update for the team? Thank you!

**Comment by moonstar-95515** [comment] 2024-07-05 06:49
PR completed for review.

**Comment by Christinadobrzyn** [comment] 2024-07-08 23:24
Watching PR - https://github.com/Expensify/App/pull/42892

**Comment by mallenexpensify** [comment] 2024-07-12 00:42
Reported a bug I found while testing this
https://expensify.slack.com/archives/C049HHMV9SM/p1720744680218859

**Comment by Christinadobrzyn** [comment] 2024-07-16 23:28
Watching PR - https://github.com/Expensify/App/pull/42892

**Comment by mallenexpensify** [comment] 2024-07-22 21:26
I have another 'cursor position isn't in right place issue`.  If it's related to this or, or if this might fix it, plz comment on the issue
- https://github.com/Expensify/App/issues/45885

**Comment by Christinadobrzyn** [comment] 2024-07-23 23:57
@eVoloshchak can you check on this question when you have a moment? https://github.com/Expensify/App/issues/42216#issuecomment-2243843021

**Comment by eVoloshchak** [comment] 2024-07-25 14:33
@Christinadobrzyn, @mallenexpensify, I doesn't look like https://github.com/Expensify/App/issues/45885 is related to this issue

I cannot reproduce this issue on staging (or when building latest `main`), what should be our next steps here before closing?

**Comment by Christinadobrzyn** [comment] 2024-07-30 17:08
Sorry for the delay @eVoloshchak - I'm not actually sure where we are with this one. Did we decide not to continue this [PR](https://github.com/Expensify/App/pull/42892)? Is there anyone one?

**Comment by kpadmanabhan** [comment] 2024-07-30 18:46
@Christinadobrzyn / @mallenexpensify / @eVoloshchak : #45885 is not related to this issue and PR. It has a different root cause of not using `useHtmlPaste`.

@Christinadobrzyn : This issue, for the Composer field, is already fixed in `main/HEAD` through other PRs.
Also, I do not see any decisions made w.r.t this in PR or in public channel in Slack.
In fact @eVoloshchak is asking [here](https://github.com/Expensify/App/issues/42216#issuecomment-2250481082) on how to proceed with a closure to this issue.
May be @mallenexpensify might be able to guide.

**Comment by mallenexpensify** [comment] 2024-07-31 22:17
oooof, this one is a bit confusing. 

Are the next steps

1. Plan to close the issue since it isn't reproducible. 
2. Before closing, allow contributors to comment if they think they're due compensation?

**Comment by moonstar-95515** [comment] 2024-08-01 11:10
Hi @mallenexpensify,

I’d like to provide an overview of the PR for this issue:

PR Created: May 30
PR Completed (excluding Android video): June 12
Video Uploaded: July 4
I completed everything except for the Android screen recordings by June 12. I acknowledge that the delay in uploading the test video was my responsibility due to various challenges. However, I want to assure you that I did my best; in fact, I even purchased a new Mac to facilitate this work.

Could you please let me know if I could receive payment in this situation?

Thank you for your consideration.
Best regards.

**Comment by mallenexpensify** [comment] 2024-08-06 23:00
Thanks @moonstar-95515 for the breakdown! 

This is a lil complex because... generally, our process is
> If a contributor has been hired for a job and we decide to close the job before it is successfully completed, full payment is due for C+ and the contributor. One caveat here might be if the hired contributor wasn't working on their PR with urgency. 

What makes this complex is **One caveat here might be if the hired contributor wasn't working on their PR with urgency.** 

I propose we compensate 50% here.

**Comment by moonstar-95515** [comment] 2024-08-07 00:10
@mallenexpensify 
I agree with your suggestion.
Thank you for your consideration.

**Comment by mallenexpensify** [comment] 2024-08-07 22:02
@moonstar-95515 , can you please apply to the job and reply here once you have? 
https://www.upwork.com/jobs/~019ed12c117911de2f

**Comment by moonstar-95515** [comment] 2024-08-08 01:09
@mallenexpensify 

Contributor details
Your Expensify account email: moonstar95515@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0199a1c5ba303082c7

**Comment by mallenexpensify** [comment] 2024-08-09 00:24
@moonstar-95515 can you apply plz? It's MUCH easier for me to hire then pay you that way.  thx
https://www.upwork.com/jobs/~019ed12c117911de2f

**Comment by moonstar-95515** [comment] 2024-08-09 00:43
@mallenexpensify 
I'm really sorry but I have some problem with applying the job.
Could you please send me offer?
Sorry for inconvenience. Thank you for your effort.

**Comment by Christinadobrzyn** [comment] 2024-08-13 19:21
Hi @moonstar-95515 sorry for the delay here - I just created a new offer in this Upwork job post - https://www.upwork.com/nx/wm/offer/103512886

Can you see if you can accept that for payment? Thank you!

**Comment by moonstar-95515** [comment] 2024-08-14 03:14
@Christinadobrzyn 
Thank you.
I've accepted offer.

**Comment by Christinadobrzyn** [comment] 2024-08-15 20:38
Thanks @moonstar-95515! 

I'm a little lost on the payments due for this. I think this is the summary, can we get a review. 

Payouts due:

- [ ] Contributor: $125 @moonstar-95515 (in upwork -  https://www.upwork.com/nx/wm/workroom/38089229/overview)
- [ ] Contributor: $125 @rakhaxor (can you please send your Upwork profile)
- [ ] Contributor+: $250 @eVoloshchak (upwork offer - https://www.upwork.com/nx/wm/offer/103544327)

**Comment by moonstar-95515** [comment] 2024-08-15 23:47
@Christinadobrzyn 
Thank you for your summary.
@ rakhaxor was mis-assigned at the first time and not unassigned yet.

**Comment by mallenexpensify** [comment] 2024-08-16 00:46
@rakhaxor had an accepted proposal and was initially assigned/hired so $125 seems fair, even with @moonstar-95515 working on the PR/issue later.

**Comment by moonstar-95515** [comment] 2024-08-16 02:21
@mallenexpensify 
Thank you for your explanation.

Of course, I know that I have no face to say anything because my solution has not been reflected in production.
But I still have some unclear points.
Can contributors be compensated even if it is due to a misjudgement of C+ as long as they are assigned to an issue?

**Comment by rakhaxor** [comment] 2024-08-16 04:35
Hello @Christinadobrzyn, Thank you for the offer. Here’s my upwork: https://www.upwork.com/freelancers/~01f94219e6101472c1

**Comment by moonstar-95515** [comment] 2024-08-16 05:40
@mallenexpensify , @Christinadobrzyn 
Sorry for bothering again.
Of course, I've already agreed 50% of compensation here.
But I think it's not fair considering my work and @rakhaxor's work in this issue.

Here's summary:
- My proposal was the first one and perfect.
- But then @rakhaxor 's proposal was selected due to misjudgment. He worked on this issue until it was assigned to me.
- Anyway, my proposal was selected [here](https://github.com/Expensify/App/issues/42216#issuecomment-2133401204).
- Then, I've created PR and I worked on the PR for over a month.

I think I put much more effort in this issue and the same compensation is not fair.
Could you please reconsider about compensation?

**Comment by rakhaxor** [comment] 2024-08-16 07:00
@moonstar-95515 What’s your problem with me man? I have done all the tests and made screen recordings. You were assigned later on, I did all the work there and was asking to submit PR. I didn’t even comment even after doing all the work and not being able to submit it until now when I was asked to submit my profile link. Anyways, I just need you to not talk about me anymore. Thank you

**Comment by moonstar-95515** [comment] 2024-08-16 07:55
@rakhaxor 
I don't have any problem with you. I'm just talking about my rights.
Do you really think you have right to be compensated?
I've commented just after you were assigned and you may know that your proposal was wrong. I can't understand why you kept working.
But I'm not saying you shouldn't be compensated, I'm just saying that I put more effort and there must be difference in compensation.
That's all. Thank you.

**Comment by mallenexpensify** [comment] 2024-08-19 18:00
The decision to compensate @rakhaxor is an edge case, based on the fact they were assigned to the issue and hired.  It was the responsibility of Expensify to hire/assign. Since this action is considered a source-of-truth and gives the green light for the contributor to invest more time into the issue (assuming compensation), we feel it's fair to compensate.  Since their proposal was initially accepted, we decided on 50%. 

@moonstar-95515 , your compensation on this issue, and the value associated with it, is completely unrelated to the compensation for @rakhaxor.  Please keep in mind our [documented code of conduct ](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md)when communicating with others, both internal and with fellow contributors. 
> We pride ourselves as a company and as individual employees on our core qualities: Talent, Ambition, & Humility. The environment we have developed uses these qualities to adhere to our two golden rules of Expensify:
>
> 1. Get Shit Done
> 2. Don’t Ruin it for Everyone Else

Thanks

**Comment by Christinadobrzyn** [comment] 2024-08-19 20:11
Quick follow up - based on a review (as Matt outlined) we are going to continue with this [payment summary](https://github.com/Expensify/App/issues/42216#issuecomment-2292195800). 

@eVoloshchak can you accept this Upwork offer - https://www.upwork.com/nx/wm/offer/103544327
@rakhaxor can you accept this Upwork offer - https://www.upwork.com/nx/wm/offer/103593092

TY!

**Comment by rakhaxor** [comment] 2024-08-20 06:57
Hello @Christinadobrzyn! I have accepted the offer on Upwork. Thank you

**Comment by eVoloshchak** [comment] 2024-08-20 16:19
@Christinadobrzyn, declined the Upwork offer, requested the payment on NewDot
Thanks!

**Comment by JmillsExpensify** [comment] 2024-08-20 17:21
$250 approved for @eVoloshchak

**Comment by Christinadobrzyn** [comment] 2024-08-20 22:37
@eVoloshchak can you let us know about a regression test? Then I think this is good to close!

**Comment by eVoloshchak** [comment] 2024-08-21 17:17
Yes, a regression test would be useful and easy to perform

**Regression Test Proposal**

1. Navigate to staging.new.expensify.com
2. Open a chat and type a one-line text and create a few empty lines 
```
test



```
3. Select all using keyboard ctrl + A and cut the text
4. Paste it inside the composer
5. Verify the cursor is positioned at the end of the pasted text

**Do we agree 👍 or 👎**

**Comment by Christinadobrzyn** [comment] 2024-08-21 17:31
Regression test is created - https://github.com/Expensify/Expensify/issues/422290

Closing!

**Closed by Christinadobrzyn** 2024-08-21 17:31 UTC
Labels: External, Daily, Awaiting Payment, Bug
