### ISSUE TITLE
Chat - Clicking Reply in thread results in continuous loading in offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20393] opened 2023-06-07 16:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR ** https://github.com/Expensify/App/pull/20258

## Action Performed:
1. Login with any account
2. If doesn't have any workspace, create a new workspace
3. Go to announce or admin chat of any workspace
4. Send any message
5. Clicking on reply in thread in offline

## Expected Result:
Thread loads without any issue

## Actual Result:
Clicking Reply in thread results in continuous loading in offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.2

**Reproducible in staging?:** Yes 

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/77e23f56-c61e-445b-a456-0dd91d85fb67

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by eh2077** [comment] 2023-06-08 10:02
This is not reproducible on latest main branch

**Comment by johncschuster** [comment] 2023-06-08 13:59
I just attempted to follow the repro steps as well, and couldn't reproduce it on staging either.

https://github.com/Expensify/App/assets/5579997/51270167-cac7-47b4-9345-07aea72cffa0

@lanitochka17, can you please clarify the reproduction steps?

**Comment by johncschuster** [comment] 2023-06-09 17:14
@lanitochka17 bump. Can you please clarify the reproduction steps?

**Comment by lanitochka17** [comment] 2023-06-09 17:37
@johncschuster I can not reproduce with build 1.3.26.1

https://github.com/Expensify/App/assets/78819774/a18ac639-7f8a-4535-9948-03ab83a8b3a7

**Comment by lanitochka17** [comment] 2023-06-09 17:40
@johncschuster I can not reproduce with build 1.3.26.1

https://github.com/Expensify/App/assets/78819774/b1cf8702-24dd-45e1-9d70-e3f1990cdd0d

**Comment by johncschuster** [comment] 2023-06-10 12:16
Great! In that case, let's close the issue.

**Closed by johncschuster** 2023-06-10 12:16 UTC
Labels: Daily, Needs Reproduction, Bug
