### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Web - Tooltip is not displayed if hovered the users which are down the list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21099] opened 2023-06-20 10:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go to staging dot on web chrome
2. Go to search
3. Hover over the first few profile avatar of the users and notice that tooltipis displayed
4. Scroll down the list up to bottom and try to hover on the profile avatar (not on the display name/email) and notice that tooltip is not displayed

## Expected Result:
Tooltip should be displayed if hovered the users which are down the list

## Actual Result:
Tooltip is not displayed if hovered the users which are down the list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f02808d3-8316-410e-bcbc-9452863b05cd

https://github.com/Expensify/App/assets/93399543/9649a7b5-754a-4e37-bc6e-3ee7626060ba

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686629969783219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ca8b2c30604ca26</li>
        <li>Upwork Job ID: 1671246480159539200</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2023-06-20 19:59
I can reproduce this!

**Comment by daordonez11** [comment] 2023-06-21 00:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For some elements in the search (personalDetails) the tooltip is not displayed if hovering the image
### What is the root cause of that problem?
The searchPage has a list of OptionRows, each element uses a component called MultipleAvatars to render de image, even tho the prop of shouldOptionShowTooltip this line calculates the tooltip content:
`const tooltipTexts = props.shouldShowTooltip ? _.pluck(props.icons, 'name') : [];`

For the section of [personalDetails ](https://github.com/Expensify/App/blob/9fde2718fa923c0da9e0ab58a6fc435877b22207/src/pages/SearchPage.js#L60) in the searchPage the icons are calculated using the method [getIcons](https://github.com/Expensify/App/blob/9fde2718fa923c0da9e0ab58a6fc435877b22207/src/libs/ReportUtils.js#L715) in ReportUtils.js

Since there are no reports the method only returns the source of the image.

### What changes do you think we should make in order to solve the problem?
Update [getIcons](https://github.com/Expensify/App/blob/9fde2718fa923c0da9e0ab58a6fc435877b22207/src/libs/ReportUtils.js#L715) and include a new parameter called defaultName
```javascript
function getIcons(report, personalDetails, defaultIcon = null, isPayer = false, defaultName = '') {
    const result = {
        source: '',
        type: CONST.ICON_TYPE_AVATAR,
        name: '',
    };

    if (_.isEmpty(report)) {
        result.source = defaultIcon || Expensicons.FallbackAvatar;
        result.name = defaultName || '';
        return [result];
    }
```
So it can be sent in this [line](https://github.com/Expensify/App/blob/9fde2718fa923c0da9e0ab58a6fc435877b22207/src/libs/OptionsListUtils.js#L517)
```javascript
result.icons = ReportUtils.getIcons(report, personalDetails, UserUtils.getAvatar(personalDetail.avatar, personalDetail.login),false,personalDetail.login);
```
Image of solution working in personalDetails section:

![image](https://github.com/Expensify/App/assets/13544910/740bb3c3-61cf-424b-950c-56d78a89407d)


### What alternative solutions did you explore? (Optional)
At the beginning I thought this was a backend issue but after seeing Onyx I found that it was about handling the data stored.

**Comment by BhuvaneshPatil** [comment] 2023-06-21 14:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Tooltip is not displayed if hovered the users which are down the list

### What is the root cause of that problem?
Easy step to reproduce this bug is - Create a workspace invite non-existent user, after that try creating the group ( the new user will appear) and it will not have tooltip.
The root cause of this problem is that some rows doesn't have `UserDetailTooltip` wrapped around them.
This mainly happens because when we send `option` prop to `OptionRow` it has `icons` field, and in that - `name` is empty.
While calculating the icons - 
https://github.com/Expensify/App/blob/0b7455fa832b53eccb99ca23c70e131b3464fb1d/src/libs/OptionsListUtils.js#L514-L521

We call `getIcons()` method - And if the user hasn't take a part in any conversation the report is null or probably `policyExpenseChart`
https://github.com/Expensify/App/blob/0b7455fa832b53eccb99ca23c70e131b3464fb1d/src/libs/ReportUtils.js#L715-L815

We return - 
https://github.com/Expensify/App/blob/0b7455fa832b53eccb99ca23c70e131b3464fb1d/src/libs/ReportUtils.js#L716-L720

as it never reaches the -
https://github.com/Expensify/App/blob/0b7455fa832b53eccb99ca23c70e131b3464fb1d/src/libs/ReportUtils.js#L814

That's why `name` for icon being empty - we don't wrap it with `UserDetailTooltip`.



### What changes do you think we should make in order to solve the problem?
We need to handle the case for getting the icons when the report is empty, using `result.participantsList`, we have a method `getIconsForParticipants()` we can pass `result.participantList` (it will be array of `accountID`) and `personalDetails` and get the icons.
This will ensure that all the users have the correct set of icons.

### What alternative solutions did you explore? (Optional)

**Comment by isabelastisser** [comment] 2023-06-22 20:39
@sobitneupane did you have the chance to review the proposals above? Thanks!

**Comment by sobitneupane** [comment] 2023-06-23 17:45
[Proposal](https://github.com/Expensify/App/issues/21099#issuecomment-1599809305) from @daordonez11 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by daordonez11** [comment] 2023-06-23 18:12
Oh my bad. 😂 thanks for the explanation @sobitneupane I thought you were already doing the assignation.

**Comment by daordonez11** [comment] 2023-06-23 18:25
@0xmiroslav  mi proposal is about the first if when no report arrives, which hasn't been touched in the PR. 
![image](https://github.com/Expensify/App/assets/13544910/fbb3634b-db76-4469-97ab-3cc57b3ac48f)
This is more like a minor improvement  rather than a bugfix:

**Comment by daordonez11** [comment] 2023-06-23 18:41
I mean @grgia since you are already focused on this topic you could just implement the solution proposed it seems it is just a border case for personalDetailsSeciton in searchpage but might fix the issue in other points

**Comment by isabelastisser** [comment] 2023-06-23 19:49
I will be OOO until July 5, so assigning another team member. [SO](https://stackoverflowteams.com/c/expensify/questions/883) for reference.

**Comment by sobitneupane** [comment] 2023-06-24 03:16
@0xmiroslav I don't think the PR will affect the behavior being discussed here. So, we should be good to create PR based on https://github.com/Expensify/App/issues/21099#issuecomment-1599809305 proposal

**Comment by BhuvaneshPatil** [comment] 2023-06-25 06:35
I have reported a bug related to avatars, and I tried understanding the root cause. That is same as of this one.
As mentioned in the contributing guidelines, I should mention the PR that has fixed the bug which I reported. Shall I wait till that gets merged or mention the bug(slack convo link) here?

**Comment by muttmuure** [comment] 2023-06-26 11:37
@luacmartins just needs to assign [daordonez11](https://github.com/daordonez11)

**Comment by muttmuure** [comment] 2023-06-26 11:39
> As mentioned in the contributing guidelines, I should mention the PR that has fixed the bug which I reported. Shall I wait till that gets merged or mention the bug(slack convo link) here?

@BhuvaneshPatil if you think you caught this bug earlier, please tag the PR and bug report here so we can check timestamps. We'll see the PR get merged if it is tagged

**Comment by BhuvaneshPatil** [comment] 2023-06-26 11:47
@muttmuure The bug is not the same. But when this PR will get merged, the bug will be resolved
This is slack convo link - https://expensify.slack.com/archives/C049HHMV9SM/p1687628052221969

**Comment by daordonez11** [comment] 2023-06-26 16:26
Thanks for the assignation @luacmartins, just applied in Upwork, I expect to have the PR ready by tomorrow June 27th @sobitneupane

**Comment by daordonez11** [comment] 2023-06-27 16:21
PR Ready https://github.com/Expensify/App/pull/21696 @sobitneupane  only waiting for high traffic account to test but still, the PR doesn't change anything in terms of performance

**Comment by daordonez11** [comment] 2023-06-27 16:37
NVM already tested high traffic everything working fine!

**Comment by daordonez11** [comment] 2023-07-05 00:32
Hey @sobitneupane @luacmartins  is the rule of the #urgency bonus specifically 72 hours? This PR was closed on the 3rd business day after assignation so I want to know if the bonus does apply on this issue. And it was due to a variable name change 😅

**Comment by daordonez11** [comment] 2023-07-05 15:14
Noted thanks for the info! @luacmartins

**Comment by sobitneupane** [comment] 2023-07-10 08:28
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

Probably [this PR](https://github.com/Expensify/App/pull/8499) or might have caused by some PR involving accountID migration.

> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1688977644296659
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-07-10 08:29
**Regression Test Proposal:**

1. Login with a high traffic account
2. Go to search
3. Hover over the profile picture of the user without previous chat history in the search list
4. Verify that the tooltip is displayed.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-07-10 09:15
Payment Requested on Expensify.

**Comment by isabelastisser** [comment] 2023-07-10 09:16
@sobitneupane I will review and process the payment by EOD.

**Comment by priyeshshah11** [comment] 2023-07-11 12:28
> @daordonez11 - what's your profile in Upwork? I can't find you there.
> 
> @priyeshshah11 - what's your profile in Upwork? I can't find you there.
> 
> @sobitneupane - I sent you an offer in Upwork!
> 
> 

I think you might have wrongly tagged me instead of @priya-zha

**Comment by sobitneupane** [comment] 2023-07-11 12:44
@isabelastisser I have requested payment and will be paid through Expensify App.

**Comment by isabelastisser** [comment] 2023-07-11 13:49
@priya-zha, I sent you an offer in Upwork.

@sobitneupane, I don't see a payment request from you in Upwork, please accept the offer I sent you today, and I will process the payment thorough Upwork.

**Comment by isabelastisser** [comment] 2023-07-11 14:04
>  [@isabelastisser] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:



https://github.com/Expensify/Expensify/issues/299030

**Comment by daordonez11** [comment] 2023-07-11 14:28
@isabelastisser https://www.upwork.com/freelancers/~01e96b8da58232f028 here is my link! thanks

**Comment by anmurali** [comment] 2023-07-11 15:19
Paid @sobitneupane

**Closed** 2023-07-11 15:57 UTC
Labels: External, Daily, Awaiting Payment, Bug
