### ISSUE TITLE
[$500] [Wave Collect] [Ideal Nav] Workspace switcher - "Expensify" and workspace are ticked when returning from workspace [Payment due March 6]

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35680] opened 2024-02-02 17:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-36.0
**Reproducible in staging?:**  Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4264387
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open workspace switcher
2. Click +
3. Click browser back button

## Expected Result:
Only "Expensify" will be selected

## Actual Result:
"Expensify" and the previous workspace are ticked at the same time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/89434aab-aec5-4dc9-a799-a0a2205225fc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e52e8d993f5ba021</li>
        <li>Upwork Job ID: 1753506244878921728</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28149266</li>
<li>esh-g | Contributor | 28149267</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-02 17:29
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by esh-g** [comment] 2024-02-02 17:53
# Proposal

## Please re-state the problem we are trying to fix
"Expensify" and workspace are ticked when returning from workspace

## Root cause
The root cause of this issue is that at first when we don't have an active workspace set, and open workspace switcher, we are on route: `https://dev.new.expensify.com:8082/workspace-switcher`. At this point `ActiveWorkspaceID` is `undefined` so the `expensify` icon is ticked.
The `activeWorkspaceID` is always based on `route` and navigation state.
When we create new workspace, the route becomes `https://dev.new.expensify.com:8082/workspace/32DF7AB51CD026CA/overview` which means the `activeWorkspaceID` gets set to `32DF7AB51CD026CA` (based on navigation state), and when we click back once again, we go to the original route: `https://dev.new.expensify.com:8082/workspace-switcher`, at this point the `activeWorkspaceID` becomes `undefined` again as there is no `ID` in the route.

But the code for selecting the workspace icon doesn't update if the `activeWorkspacecID` is `undefined` here:
https://github.com/Expensify/App/blob/e6ea03b9278029acacb424856b58dee2d1134d9d/src/pages/WorkspaceSwitcherPage.tsx#L281-L286

## What changes should be made to fix this?
We should modify this code:
https://github.com/Expensify/App/blob/e6ea03b9278029acacb424856b58dee2d1134d9d/src/pages/WorkspaceSwitcherPage.tsx#L281-L286
And remove the `if condition` and `early return`, thus allowing the `activeWorkspaceID` to be set to `undefined` which it should be as we are going back to the point where there was not an `activeWorkspace`.

**Comment by amyevans** [comment] 2024-02-02 19:48
This is a regression from Ideal Nav, but it's pretty minor so doesn't need to block deploy. Confirmed it's not a dupe of any issues listed in https://github.com/orgs/Expensify/projects/94/views/2.

**Comment by isabelastisser** [comment] 2024-02-05 14:40
@situchan, can you please review the proposal above? Thanks!

**Comment by isabelastisser** [comment] 2024-02-07 18:58
Bump @situchan. Please let me know if you would like me to reassign this. Thanks!

**Comment by situchan** [comment] 2024-02-07 19:02
sorry reviewing now

**Comment by situchan** [comment] 2024-02-07 19:31
@esh-g's [alternative solution](https://github.com/Expensify/App/issues/35680#issuecomment-1924408425) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by isabelastisser** [comment] 2024-03-01 18:34
@esh-g @situchan let's priorizite this! Can you please share an update? Thanks!

**Comment by situchan** [comment] 2024-03-01 18:35
@isabelastisser automation failed here.
PR was deployed to production already. Mar 6 is payment date

**Comment by isabelastisser** [comment] 2024-03-01 18:59
@situchan, great, thanks for the heads up!

**Comment by isabelastisser** [comment] 2024-03-06 03:17
The payments were processed in Upwork.

- @esh-g Reviewer $500
- @situchan Contributor $500

All set!

**Closed by isabelastisser** 2024-03-06 03:17 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
