### ISSUE TITLE
[$1000] Log in - User unable to proceed after re-enter last digit of magic code number

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21958] opened 2023-06-30 15:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Login Page
2. Input email => Continue
3. input wrong magic: example:  111111
4. Click last input
5. Input again 1
6. input any number

## Expected Result:
User able to proceed after re-enter last digit of magic code number

## Actual Result:
User unable to proceed after re-enter last digit of magic code number

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/56b17ede-ed41-4739-aa3d-0017108ef367

https://github.com/Expensify/App/assets/93399543/96ffccb2-c5a6-41e4-96c5-304d47d85a8e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688039417283349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01306ade9d70001f15</li>
        <li>Upwork Job ID: 1674835066467475456</li>
        2023-07-28<li>Automatic offers: </li>
<ul>
<li>samh-nl | Contributor | 25862341</li>
<li>namhihi237 | Reporter | 25862342</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by CortneyOfstad** [comment] 2023-06-30 19:27
I am heading OoO for the week (back July 10) so re-assigning this in the meantime 👍

**Comment by ugur-akin** [comment] 2023-07-01 11:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When clicked/touched on the last digit of a magic code input that is previously non-empty, upon re-inputting the same digit as previously entered (i.e. the last digit was previously 6, user presses 6 again after clicking the last digit), the code will not auto submit and nor will any further digit inputs will update the last digit. 

### What is the root cause of that problem?
The handling of the underlying text input in magic code input component is implemented incorrectly to handle the case when the user re-types the same last digit as the previously entered one.

https://github.com/Expensify/App/blob/0bbf3fccfce0994ddf4fd9e95fb33dd9edbd1868/src/components/MagicCodeInput.js#L214-L217

### What changes do you think we should make in order to solve the problem?
#### Recommended Approach:
I think there's a good opportunity to improve MagicCodeInput component and the magic code UX for Expensify (see [altermative solutions explored](#what-alternative-solutions-did-you-explore?)). 

#### Fixing the existing implementation:
Split up the underlying text input to: `[...digitsUpToLastDigit, lastDigit]` .

```javascript
const  valueAsNumbers  =  value.trim().split('');

const  numDigitsToTakeIfValueIsPastMaxLength  =  props.maxLength  -  editIndex  -  1;
const  numDigitsToTakeIfValueIsShorterThanMaxLength  =  value.length -  1;
const  numDigitsToTake  =  Math.min(numDigitsToTakeIfValueIsPastMaxLength, numDigitsToTakeIfValueIsShorterThanMaxLength);
const  valueUpToLastDigit  =  value.slice(0, numDigitsToTake);  

const  lastDigitInValue  =  valueAsNumbers[valueAsNumbers.length -  1];

const  effectiveValueAsNumbers  = [...valueUpToLastDigit, lastDigitInValue];

const  updatedFocusedIndex  =  Math.min(editIndex  + (effectiveValueAsNumbers.length -  1) +  1, props.maxLength  -  1);

let  numbers  =  decomposeString(props.value, props.maxLength);
numbers  = [...numbers.slice(0, editIndex), ...effectiveValueAsNumbers, ...numbers.slice(effectiveValueAsNumbers.length +  editIndex, props.maxLength)];
```

### What alternative solutions did you explore?
**Opinionated Statement:** The complexity of the magic code input can be reduced drastically if we opt for better UX choices.
**Claim:** Often re-typing the entire code is easier for the user than correcting digits. Fixing a digit requires identifying the incorrect digit, focusing it (either by clicking/touching the right digit or through arrow keys navigation) and entering the right digit. 

#### Clear on incorrect submission
Maintain focus on the magic input and clear it upon an unsuccessful code entry. Users are pretty effective with the keyboard (especially on mobile). Don't make them re-focus the input, let them re-type without hassle. A bonus of this is a second opportunity to leverage pasting a value or automatic text fills such as [iOS' SMS Passcode feature](https://support.apple.com/en-gb/guide/iphone/iphc89a3a3af/ios). This method is also used widely in the industry and is Tinder's choice of UX for one-time password inputs.

#### Don't let users enter past the first empty index
**Claim:** Allowing users to enter digits past the first empty digit is practically useless - arguably nobody fills starting from mid-way through and if it happens, it's probably a mistake. If the user loses focus on the text input, let them click anywhere on the magic code and automatically register the input for the first empty digit. Along with [clear on incorrect submission](#clear-on-incorrect-submission), this will entirely remove the need for complicated input-index/focus-index state management. If we don't like to clear input, this would still be an low-cost improvement for the magic code input.

**Comment by ugur-akin** [comment] 2023-07-01 11:50
Contributor details
Your Expensify account email: ugurakinsoftware@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0161bd395d1f6814a7

**Comment by lazar-stamenkovic** [comment] 2023-07-02 15:58
### Please re-state the problem that we are trying to solve in this issue.

When clicked/touched on the last digit of a magic code input that is previously non-empty, upon re-inputting the same digit as previously entered (i.e. the last digit was previously 6, user presses 6 again after clicking the last digit), the code will not auto submit and nor will any further digit inputs will update the last digit.

### What is the root cause of that problem?
This issue is caused by following reason
 - The MagicCode input doesn't clear input value when the user inputs last digit of a magic code.
 - Whenever typing the text, OnChangeText is called even if code text isn't changed.

### What changes do you think we should make in order to solve the problem?
- Text Input value has to be cleared if current focused input is last input.
-  OnChangeText is called only if code text is changed.

![Screenshot 2023-07-02 at 10 53 09](https://github.com/Expensify/App/assets/114150992/f54e68b2-426b-472c-a2e6-bfe471d7b104)

**Comment by lazar-stamenkovic** [comment] 2023-07-03 20:49
@eVoloshchak, @mallenexpensify please take a look my proposal. https://github.com/Expensify/App/issues/21958#issuecomment-1616711090

**Comment by eVoloshchak** [comment] 2023-07-05 21:08
@namhihi237's [proposal](https://github.com/Expensify/App/issues/21958#issuecomment-1614874888) was the first to correctly identify the root cause. This is indeed the cause, the issue is happening only when you enter the same number
> This issue occurs when after entering last input same as current number in that cell,




I agree with @ugur-akin, [UX seems to be a bit off.](https://github.com/Expensify/App/issues/21958#issuecomment-1615866011). Currently, if you've entered an incorrect code, you can edit only a single digit, after which the API call is made and input is blurred. 

> I think there's a good opportunity to improve MagicCodeInput component and the magic code UX for Expensify (see alterative solutions explored section).
> Maintain focus on the magic input and clear it upon an unsuccessful code entry.



@mallenexpensify, what are your thoughts on @ugur-akin's [alternative solution](https://github.com/Expensify/App/issues/21958#issuecomment-1615866011)? I could also create a bigger discussion on Slack

**Comment by lazar-stamenkovic** [comment] 2023-07-05 21:28
@eVoloshchak would you please take a look my proposal? 
https://github.com/Expensify/App/issues/21958#issuecomment-1616711090
believe I have resolved the issue by updating the code with minimal changes.
I also agree with @ugur-akin. think it's a new feature that will require minor updates on the MagicCodeInput component. Specifically, it needs to include an action, such as a button click, to trigger the code submission within the component using MagicCodeInput

**Comment by eVoloshchak** [comment] 2023-07-06 14:50
@lazar-stamenkovic, I did review your proposal, but would like to clarify the expected behavior first. I think simplifying the logic is the way to go, but would like to hear what others think

**Comment by lazar-stamenkovic** [comment] 2023-07-06 14:59
> @lazar-stamenkovic, I did review your proposal, but would like to clarify the expected behavior first. I think simplifying the logic is the way to go, but would like to hear what others think

Got it.  Please let me know if you decide considering my solution again.  Thanks for reviewing my proposal.

**Comment by mallenexpensify** [comment] 2023-07-11 03:53
Sorry for the delay, I was out for a couple days last week. 
> what are your thoughts on @ugur-akin's https://github.com/Expensify/App/issues/21958#issuecomment-1615866011? I could also create a bigger discussion on Slack

Can you please raise a discussion in Slack please @eVoloshchak?  I _feel_ like we could _maybe_ improve aspects of how we're managing magic codes (not an engineer!).    If we decide to make larger changes, we should discuss potential compensation for @namhihi237 for being the first to identify the root cause here, since that'd fix the specific bug here

**Comment by eVoloshchak** [comment] 2023-07-13 16:50
Will raise a discussion shortly

**Comment by eVoloshchak** [comment] 2023-07-17 18:16
Not overdue, started a discussion in https://expensify.slack.com/archives/C01GTK53T8Q/p1689617742443109

**Comment by eVoloshchak** [comment] 2023-07-25 17:06
Original discussion didn't get any traction, [bumping](https://expensify.slack.com/archives/C01GTK53T8Q/p1690304754371609?thread_ts=1689617742.443109&cid=C01GTK53T8Q) on Slack

**Comment by eVoloshchak** [comment] 2023-07-31 15:54
As per the discussion
> Also I believe we've had discussion in the past about clearing the input on failure, and we came to the conclusion that correcting 6 digits isn't really much of a barrier to retyping so it wasn't seen as necessary to have
> We should keep focused input on the field if incorrect

Which is exactly what @samh-nl's has proposed [here](https://github.com/Expensify/App/issues/21958#issuecomment-1614810638). I think we can proceed with the proposal

🎀👀🎀 C+ reviewed!

**Comment by Pujan92** [comment] 2023-08-01 07:06
@eVoloshchak I think the selected proposal won't work as we blur the MagicCodeInput once it is fulfilled. 
https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/components/MagicCodeInput.js#L122-L129

**Comment by Pujan92** [comment] 2023-08-01 07:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Last input text is not focused when we get an error from the server

### What is the root cause of that problem?
Currently, we are blurring the focusedIndex once the user fulfills the magic code and we are not focusing back on the last input once we receive an error from the server.
https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/components/MagicCodeInput.js#L129


### What changes do you think we should make in order to solve the problem?
As per the requirement, we do need to focus on the last input box once we get the incorrect magic code error from the server for user convenience.

1. In the MagicCodeInput component we need to check for the previous `hasError` value.
`const prevHasError = usePrevious(props.hasError);`

2. We can create `useEffect` block where we consider `prevHasError` and `hasError` to decide whether to focus or not on the last index input.
``` 
    useEffect(() => {
        if(prevHasError || !props.hasError) {
            return;
        }
        inputRefs.current[props.maxLength - 1].focus();
    }, [prevHasError, props.hasError, props.maxLength])
```

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/14358475/760ff53a-b1fd-4cef-a491-5314bc4deaf0


</details>

**Comment by Pujan92** [comment] 2023-08-01 13:27
@samh-nl I don't think so otherwise keeping focus will make the api calls on each input change even though the previous call is in process, as per the slack discussion what I understood is that only for the failure/error case we need to make the focus.

**Comment by Pujan92** [comment] 2023-08-01 13:33
cc: @johnmlee101 to weigh in here.

**Comment by Pujan92** [comment] 2023-08-04 09:53
@eVoloshchak @johnmlee101 can you plz share the expected behaviour here?

**Comment by johnmlee101** [comment] 2023-08-04 16:23
Refocusing the magic code input if its incorrect seems like the expected behavior

**Comment by Pujan92** [comment] 2023-08-05 02:39
> Refocusing the magic code input if its incorrect seems like the expected behavior

Thanks @johnmlee101 , in that case I don't think selected proposal is achieving that.

**Comment by Pujan92** [comment] 2023-08-10 12:31
@eVoloshchak @amyevans  isn't my proposal needs to be considered if it is meet the expected outcome in case the wrong proposal gets selected?

**Comment by amyevans** [comment] 2023-08-11 15:36
@eVoloshchak can you provide a recommendation for the best path forward please? I have not reviewed the PR in detail but from a glance it does seem to have deviated from the original selected proposal. Thanks!

**Comment by eVoloshchak** [comment] 2023-08-14 13:45
> @eVoloshchak can you provide a recommendation for the best path forward please? 

@amyevans, yeah, I agree with @samh-nl comment, we kind of got off track with the expected behavior (but made the UX better) and the PR for this ended up consisting of two separate fixes:

- Refocus the magic code input if it's incorrect (this was [proposed](https://github.com/Expensify/App/issues/21958#issuecomment-1614810638) by @samh-nl)
- Still make a network request if user has re-entered the same magic code (the same last digit). The fix for this was [proposed](https://github.com/Expensify/App/issues/21958#issuecomment-1659711099) by @Pujan92



Current [PR](https://github.com/Expensify/App/pull/23995) achieves the desired behavior and works fine, but it clearly uses both @samh-nl and @Pujan92's proposals combined. 
I think a fair way forward would be to split the bounty between @Pujan92 and @samh-nl, since both of them have contributed to fixing this.
@Pujan92, @samh-nl, would you be fine with that? @amyevans, is that something we could do?

**Comment by amyevans** [comment] 2023-08-14 22:56
Okay got it, thanks for the additional detail!

> I think a fair way forward would be to split the bounty between @Pujan92 and @samh-nl, since both of them have contributed to fixing this.
@Pujan92, @samh-nl, would you be fine with that? @amyevans, is that something we could do?

Yes, that's definitely something we can do. Does $750 @samh-nl / $250 @Pujan92 sound acceptable? (Favoring the PR implementor in the split, since that's where the bulk of iteration and testing took place)

**Comment by Pujan92** [comment] 2023-08-15 12:01
@amyevans @eVoloshchak Thanks for acknowledging the point! I am ok with the split.

**Comment by Pujan92** [comment] 2023-08-22 17:24
@amyevans @eVoloshchak to inform, we have a [regression](https://github.com/Expensify/App/pull/23995#issuecomment-1682631957) from this PR which we are trying but haven't actually solved yet.
Issue: On pasting the same code twice and pressing back crashes the app.

**Comment by amyevans** [comment] 2023-08-23 16:17
Regression: https://github.com/Expensify/App/issues/25728

We've reverted the PR in https://github.com/Expensify/App/pull/25781

@samh-nl let us know once a new PR is set to go, thank you!

**Comment by amyevans** [comment] 2023-08-31 14:41
Not overdue

**Comment by amyevans** [comment] 2023-09-01 16:16
I don't think we need to rush this PR. As long as you don't object, let's HOLD until that bug is fixed and also until after the merge freeze, whichever comes last.

**Comment by mallenexpensify** [comment] 2023-09-05 02:45
Do we know the issue number that we're holding for this? I'd like to update the title if so

**Comment by amyevans** [comment] 2023-09-05 13:51
The bug hasn't been added to GH yet but I'm subscribed to the Slack thread for when it does and can update the title then

**Comment by amyevans** [comment] 2023-09-06 17:29
Updated the title to reflect we're holding on https://github.com/Expensify/App/issues/26190

**Comment by mallenexpensify** [comment] 2023-09-11 07:14
Still on hold
- https://github.com/Expensify/App/issues/26190

**Comment by amyevans** [comment] 2023-09-20 01:55
Same

**Comment by amyevans** [comment] 2023-09-29 02:21
Still holding

**Comment by amyevans** [comment] 2023-10-10 21:18
Looks like https://github.com/Expensify/App/issues/26190 has been solved so we can remove the hold, @samh-nl any concerns regarding proceeding?

**Comment by amyevans** [comment] 2023-10-23 15:43
Still on hold for https://github.com/Expensify/App/pull/28711

**Comment by mallenexpensify** [comment] 2023-11-03 23:27
- https://github.com/Expensify/App/pull/28711

Actively being worked on

**Comment by amyevans** [comment] 2023-11-14 23:01
Still on hold, there's movement on the PR

**Comment by amyevans** [comment] 2023-11-27 23:03
Linked PR is still open

**Comment by amyevans** [comment] 2023-12-06 02:10
#28711 is merged, are we ready to roll on this one @samh-nl?

**Comment by amyevans** [comment] 2023-12-14 20:15
Discussing [in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1702582276597049)

**Comment by mallenexpensify** [comment] 2023-12-14 23:19
@samh-nl do you want to work on this?

**Comment by amyevans** [comment] 2023-12-15 18:51
Agreed, and thanks for the links @mkhutornyi.

Let's close this then - @mallenexpensify can you handle any payments that may be due for work completed to date?

Thanks!

**Comment by mallenexpensify** [comment] 2023-12-18 21:19
Thanks all!
Compensation shouldn't be due because we didn't move forward with a fix. If you disagree, please post!

**Closed** 2023-12-18 21:19 UTC
Labels: External, Engineering, Daily, Bug
