### ISSUE TITLE
 The text quoted with backticks is showing smaller than it should, making it look weird

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52223] opened 2024-11-07 22:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_bugs](https://expensify-ts.slack.com/archives/C049HHMV9SM/p1730993593571369)

## Action Performed:
Prerequisite: Set the font size to bigger in device settings

1. Open a DM with anyone
2. Enter a message with quoted backticks as  Hello `Test  Test` Hello

## Expected Result:
Message displayed without any visual issues

## Actual Result:
The quoted test is showing smaller, space in the quoted message is interrupted, and not showing in the same line (Higher than the rest of the text)
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

<img src="https://github.com/user-attachments/assets/09f8c9dd-dbe4-4fdf-8940-d040d17f117a" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/d0512910-1d7a-4c95-b48f-e253570dd31b" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/9f40b249-e445-4ac8-90fb-8f721aa5b0a1" width="40%" height="40%">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkzie2** [comment] 2024-11-08 05:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The quoted test is showing smaller, space in the quoted message is interrupted, and not showing in the same line (Higher than the rest of the text)

### What is the root cause of that problem?

The `lineHeight` of normal text is `20`:

https://github.com/Expensify/App/blob/08e571ca195023f63160076d560f92de96d0fe49/src/styles/index.ts#L240

https://github.com/Expensify/App/blob/2c561aee7b9e92f086a02b088c9f66934d93ca93/src/styles/variables.ts#L66

while the `lineHeight` of the code text and `height` of the code wrapper on Android is much smaller compared to `20`:

https://github.com/Expensify/App/blob/82b76c1a36cf1a01b00c14510a5812a591e7f2fd/src/styles/utils/codeStyles/index.android.ts#L3-L14

### What changes do you think we should make in order to solve the problem?


My experiment proved that we can reuse [iOS's `codeStyles`](https://github.com/Expensify/App/blob/82b76c1a36cf1a01b00c14510a5812a591e7f2fd/src/styles/utils/codeStyles/index.ios.ts) for Android. So we can remove the Android specific file and rename iOS file to `.native.ts` to apply to both platforms.

**Comment by OfstadC** [comment] 2024-11-11 19:37
Back and looking at this now. Can't reproduce on Mac or IOS - trying android now

**Comment by OfstadC** [comment] 2024-11-12 22:18
Didn't get a chance to try this on an android device today - but will first thing tomorrow

**Comment by OfstadC** [comment] 2024-11-14 22:11
Was able to reproduce on Android, but I don't think this is likely a [priority](https://expensify.slack.com/archives/C049HHMV9SM/p1731017638508959?thread_ts=1730993593.571369&cid=C049HHMV9SM) 

Mine also wasn't as drastic as the image in the OP - It was nearly inline with the other text. So I think we'll likely close this but i'll get some more eyes on it tomorrow to confirm

**Comment by OfstadC** [comment] 2024-11-15 19:51
Going to close

**Closed by OfstadC** 2024-11-15 19:51 UTC
Labels: Daily, Bug
