### ISSUE TITLE
Thread - Join button in thread is not responsive

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35562] opened 2024-02-01 14:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Send a message in any chat
2. Right click on the message > Leave thread
3. Right click on the message > Reply in thread
4. Click Join

## Expected Result:
Join button is responsive

## Actual Result:
Join button is not responsive. The same issue also occurs when clicking Join from 3-dot menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/09ad3c70-7809-4cd5-a97b-87111f604bc7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-01 15:00
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by paultsimura** [comment] 2024-02-01 15:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
This is happening because we memoize the `ReportScreen` incorrectly: we do not compare the `report.notificationPreference`:

https://github.com/Expensify/App/blob/9ab4fe92dcbac8252998febf6fa24a080a196a70/src/pages/home/ReportScreen.js#L645-L662

### What changes do you think we should make in order to solve the problem?
We should add this check as well:

```js
prevProps.report.notificationPreference === nextProps.report.notificationPreference &&
```



### What alternative solutions did you explore? (Optional)

**Comment by AndrewGable** [comment] 2024-02-01 21:27
Looks like the fix for this is CP-ed to web already: https://github.com/Expensify/App/actions/runs/7746962730 and https://github.com/Expensify/App/actions/runs/7747613218 so going to test a fix

**Comment by AndrewGable** [comment] 2024-02-01 21:29
The join button now works on staging 👍 

Great job @rlinoz

**Closed by AndrewGable** 2024-02-01 21:29 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Hourly
