### ISSUE TITLE
Unable to see 'Review Duplicates' button while offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52210] opened 2024-11-07 18:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48958
**Email or phone of affected tester (no customers):** applausetester+bm211@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Workspace A has tax rates, categories, and tags.
2. Workspace B does not have taxes, categories, and tags feature enabled.
3. Open the chat for Workspace A.
4. Submit an expense in Workspace A with a tax rate, category, and tag (us5. e the same amount and merchant).
5. Submit another expense in Workspace A with all fields left empty (defaults).
6. Open the chat for Workspace B.
7. Submit an expense in Workspace B with the same amount and merchant as the previous entries.
8. Open the transaction thread for the expense submitted in Workspace B.

## Expected Result:
Review Duplicates should appear

## Actual Result:
Review Duplicates doesn't appear.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/643a2336-1ec0-45eb-b0ef-2d9f330d58f1

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by brunovjk** [comment] 2024-11-07 19:03
I can review my expenses without any problems, both in the latest `main` and in production, the button is always there:

https://github.com/user-attachments/assets/f4926ae7-5d0c-4892-820b-2499b43c749b


@IuliiaHerets  Could it be that the account has no "beta" permissions? The same steps for an account without beta permissions, the button really doesn't appear:

https://github.com/user-attachments/assets/b08fa25e-5126-4812-a962-3aef21756715

**Comment by brunovjk** [comment] 2024-11-07 19:10
I can **Review Duplicate** without any problems, both in the latest `main` and in production, the button is always there:

<details>
<summary>latest `main` </summary>



https://github.com/user-attachments/assets/f4926ae7-5d0c-4892-820b-2499b43c749b

</details>

@IuliiaHerets  Could it be that the account has no "beta" permissions? The same steps for a new account, the button really doesn't appear:

<details>
<summary>New account, without permissions</summary>



https://github.com/user-attachments/assets/b08fa25e-5126-4812-a962-3aef21756715

</details>

cc: @pecanoro

**Comment by IuliiaHerets** [comment] 2024-11-07 19:11
@brunovjk Can you check in offline mode? Issue happens only in offline

**Comment by brunovjk** [comment] 2024-11-07 19:37
Thank you for pointing that out, @Iuliia. Indeed, I retested and confirmed that when following all steps while offline, the "Review Duplicates" alert does not appear as expected. 

<details>
<summary>latest `main`</summary>



https://github.com/user-attachments/assets/f36ac70b-dd69-4dc7-9eb0-80b200561f7e

</details>

I think this is because **the server is required to check for duplicate expenses**. It seems our original [PR](https://github.com/Expensify/App/pull/48958) tests should either not have included offline steps or should have outlined them differently. @Kristina2323 @pecanoro Thoughts?

**Comment by pecanoro** [comment] 2024-11-07 23:49
@brunovjk The button didn't show before the changes either way, right? It seems this has never been an option so let's just skip offline tests since they don't apply

**Comment by brunovjk** [comment] 2024-11-08 12:41
> The button didn't show before the changes either way, right? It seems this has never been an option so let's just skip offline tests since they don't apply

Yes. Great then.
>> https://github.com/Expensify/App/pull/48958 - Failing with https://github.com/Expensify/App/issues/52210

> Minor, not a blocker. Checking off.

 @pecanoro do you think we need to change the Steps for Testing the [PR](https://github.com/Expensify/App/pull/48958) (remove offline)? I wonder if the "Online QA Steps" passed successfully. Thank you.

**Comment by pecanoro** [comment] 2024-11-08 15:36
Yeah, we need to do so, @Krishna2323 could you update the offline steps?

**Comment by pecanoro** [comment] 2024-11-11 16:00
Perfect, closing this one then

**Closed by pecanoro** 2024-11-11 16:00 UTC
Labels: Daily, Overdue, Bug
