### ISSUE TITLE
mWeb / Safari - Search - Modal doesn't completely cover the screen 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13548] opened 2022-12-13 03:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to the prod website [staging.new.expensify.com](http://staging.new.expensify.com/) 
2. Click on new Chat
3. Notice the previous screen is slightly visible and can be scrolled

## Expected Result:
The new chat screen should cover the screen completely

## Actual Result:
The previous screen is slightly visible and can be scrolled at the bottom

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web (Safari)

**Version Number:** 1.2.38-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/207216526-5cf6ab3e-3bbe-474b-a516-0ef99dfd04fd.mov
<img src="https://user-images.githubusercontent.com/43996225/207216619-8624a518-e303-4b6d-abba-aeadcecb854b.PNG" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @someone-here
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670748885345139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sketchydroide** [comment] 2022-12-13 13:29
this seems like a regression, maybe, maybe it's just another one of those `flex` that has been changed

**Comment by laurenreidexpensify** [comment] 2022-12-13 14:10
@sketchydroide do you have any idea where the regression might have stemmed from in more detail?

**Comment by marcaaron** [comment] 2022-12-13 17:12
Seems related to the banner at the top of the screen? We have definitely had an issue like this before... 👀

**Comment by marcaaron** [comment] 2022-12-13 17:20
Feels like a dupe of this which we put on HOLD (but I think should not have) -> https://github.com/Expensify/App/issues/13219

**Comment by laurenreidexpensify** [comment] 2022-12-15 13:53
I'm closing in favour of https://github.com/Expensify/App/issues/13219, pls reopen if anyone disagrees

**Closed by laurenreidexpensify** 2022-12-15 13:53 UTC
Labels: Daily, Bug
