### ISSUE TITLE
Invoices - Unable to update company name and website

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51871] opened 2024-11-01 15:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh2410006@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace
3. Go to workspace settings
4. Enable Invoices
5. Go to Invoices
6. Add company name and company website
7. Click on the company name
8. Edit the existing company name and save it
9. Repeat Step 7 and 8 for company website

## Expected Result:
User should be able to update company name and website

## Actual Result:
User is unable to update company name and website
The company name and website cannot be updated once the initial info is entered

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/5ae43f3e-14cf-4e8d-87ad-3a974f38fbc8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-11-01 15:53
We think that this bug might be related to #vip-bills

**Comment by tgolen** [comment] 2024-11-01 16:26
It sounds like this is directly related to https://github.com/Expensify/App/pull/50571. @rezkiy37 Could you please look into this ASAP?

**Comment by Beamanator** [comment] 2024-11-04 10:34
Bumped in the blocker slack thread

**Comment by Julesssss** [comment] 2024-11-04 11:31
Downgrading this from being a blocker. This API was just added as a new feature and only breaks on the second use.

**Comment by tgolen** [comment] 2024-11-04 16:12
Sounds like @madmax330 will be looking into this more with a backend fix ([Slack ref](https://expensify.slack.com/archives/C01GTK53T8Q/p1730736336177649?thread_ts=1730476397.837949&cid=C01GTK53T8Q))

**Comment by rezkiy37** [comment] 2024-11-05 11:41
That's definitely a backend bug. Moreover, I could not reproduce it with legacy workspaces but only with newly created ones.

Error: `"400 invoice attribute is missing or malformed"`

<details><summary>Details</summary>
<p>


https://github.com/user-attachments/assets/e4ee7473-e166-4d9d-9e9b-6c67b6cc0c07



</p>
</details>

**Comment by madmax330** [comment] 2024-11-11 18:06
Pr is up

**Comment by madmax330** [comment] 2024-11-19 17:57
This should be fixed now

**Comment by madmax330** [comment] 2024-11-19 17:58
@rezkiy37 can you double check?

**Comment by rezkiy37** [comment] 2024-11-20 11:39
The bug has been fixed. It works properly with legacy and newly created workspaces.

<details><summary>Video</summary>
<p>

https://github.com/user-attachments/assets/e2cdbaad-7436-4850-8566-fc89818aa2d5

</p>
</details> 

cc @madmax330

**Comment by madmax330** [comment] 2024-11-20 12:02
Cool, let's close this then

**Closed by madmax330** 2024-11-20 12:02 UTC
Labels: Reviewing, Engineering, Daily
