### ISSUE TITLE
Web - Green highlight appears below user clicked

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26556] opened 2023-09-02 14:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go any workspace
2. Click "Members" -> click "Invite"
3. Invite some users -> click "Next" to confirm
4. Choose any 1 person

## Expected Result:
Only highlight the selected person

## Actual Result:
Green highlight appears below user clicked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[bug#4.webm](https://github.com/Expensify/App/assets/93399543/0d423b5a-6a57-4470-8c87-8bb86663f76c)

https://github.com/Expensify/App/assets/93399543/00b2f358-6c64-481b-9022-96a2ab402c93

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Le Thi Thu Thuy
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693212099393909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ishpaul777** [comment] 2023-09-02 17:27
Dupe of https://github.com/Expensify/App/issues/25884#issuecomment-1695507001

**Closed** 2023-09-04 08:30 UTC
Labels: Daily, Bug
