### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] [Payment card / Subscription] When clicking "Change payment", past data still shows on new form

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44886] opened 2024-07-05 09:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**Found when executing PR :** https://github.com/Expensify/App/pull/44361
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account (Beta enabled)
3. Access https://staging.new.expensify.com/settings/subscription/add-payment-card
4. Input valid card data
5. Click on "Change Payment" after the card data has been set

## Expected Result:
User expects that if the fields are cleared, then all fields should be cleared.

## Actual Result:
The expiration date still shows from the previous card (And is in the correct format, missing a digit) and the Zip code is still showing as well.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4c7b43bb-3b0f-4e17-ae62-521fae36a05b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f36eea0f55c219c3</li>
        <li>Upwork Job ID: 1809282474389988839</li>
        <li>Last Price Increase: 2024-07-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by izarutskaya** [comment] 2024-07-05 09:34
@mallenexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-07-05 09:35
We think this issue might be related to the #collect project.

**Comment by mountiny** [comment] 2024-07-05 09:40
This is minor and subscriptions in ND is still hidden for new users so we can demote

**Comment by Pujan92** [comment] 2024-07-05 21:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Past data shows in the form when we try to change payment card or opening the add payment card page directly

### What is the root cause of that problem?
In the `PaymentCard` component, we are setting the payment card form with the previously added card details. Due to that some of the fields are populated with the existing card data.

https://github.com/Expensify/App/blob/c5eafd33463b2ba4c0ce2eb0c48261f66b085dc7/src/pages/settings/Subscription/PaymentCard/index.tsx#L48-L55

### What changes do you think we should make in order to solve the problem?

I don't think we need this(`setPaymentCardForm`) method or don't need to set payment card form details. We can get rid of that useEffect block. Also we need to remove the prop `shouldShowPaymentCardForm` bcoz it should be always true for web.
Reason - We don't have any edit card functionality for which we need to populate the existing details and for currency updation we use `fundList` to derive default card currency.

https://github.com/Expensify/App/blob/c5eafd33463b2ba4c0ce2eb0c48261f66b085dc7/src/pages/settings/Subscription/PaymentCard/ChangeBillingCurrency/index.tsx#L36

**Comment by trjExpensify** [comment] 2024-07-08 10:41
@fedirjh what do you think?

**Comment by blimpich** [comment] 2024-07-09 16:33
The entire form should be emptied when the user clicks on "change payment card." We originally decided to have edit functionality but changed our minds and decided that when the user clicks "change payment card" the entire form should be emptied.

No real root cause, its a new feature and we are still figuring out how exactly we want it. Less of a bug and more a new feature.

**Comment by trjExpensify** [comment] 2024-07-10 11:37
@fedirjh @Pujan92 how we looking here? Are we aligned, can we move forward?

**Comment by trjExpensify** [comment] 2024-07-10 16:25
>should we consider validating the edited card number on the front end? For instance, if someone tries to add the same card number again, should we show an error message?

I don't really see the value in erroring out here. If someone did that, it doesn't cause any harm, they just have the same card details on file as they did before.

**Comment by blimpich** [comment] 2024-07-10 17:03
Yeah we don't care about them putting in the same card number. Lets keep it simple 👍

**Comment by blimpich** [comment] 2024-07-10 20:04
Looks like automation didn't work for automatically assigning the contract. @Pujan92 please feel free to raise a PR. @mallenexpensify will make sure you get paid.

**Comment by Pujan92** [comment] 2024-07-11 08:53
@blimpich I will raise PR soon, the contract isn't assigned bcoz now I am about to get payments via Newdot.

**Comment by mallenexpensify** [comment] 2024-07-12 00:27
Noting that assign date is after eligible date, so @Pujan92 will be paid via NewDot

**Comment by mallenexpensify** [comment] 2024-07-22 21:18
> @Pujan92 does not require payment (Contractor)

@Pujan92 this should be fixed now to denote you're paid via NewDot. Comment here if you see any assigned issues from today forward where it's not. 

@fedirjh , thanks for test case steps
- https://github.com/Expensify/Expensify/issues/414485

**Comment by JmillsExpensify** [comment] 2024-07-25 02:15
@mallenexpensify can you confirm the checklist above so I can approve payments?

**Comment by mallenexpensify** [comment] 2024-07-26 22:44
Contributor: @Pujan92 due $250 via NewDot   
Contributor+: @fedirjh due $250 via NewDot 

 Thanks!

**Closed by mallenexpensify** 2024-07-26 22:44 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-05 11:55
$250 approved for @fedirjh
