### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] Track expense - Tracking report does not appear in LHN when the tracking is created offlne

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41284] opened 2024-04-30 02:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40988
## Action Performed:
Precondition:
- User has not opened the selfDM previously (this can also be done by a re-logging in or simply resetting the app from the Troubleshoot menu).
- ~selfDM must be in skeleton in offline mode.~ didn't matter for me
- ~Use a new expensifail account~ didn't matter for me

1. Go to staging.new.expensify.com
2. Go offline
3. Go to FAB > Track expense
4. Track a manual expense
5. Click on the preview to open the tracked expense

## Expected Result:
The tracked expense should appear in the LHN and be highlighted as the "active" chat.

## Actual Result:
The tracked expense does not appear in the LHN when created offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/86ead60b-a73e-486c-9ae6-1192f08ad6e4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b8a455d33344f1fa</li>
        <li>Upwork Job ID: 1785823144724504576</li>
        <li>Last Price Increase: 2024-05-09</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by lanitochka17** [comment] 2024-04-30 02:12
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-30 02:13
We think that this bug might be related to #vip-vsp

**Comment by trjExpensify** [comment] 2024-05-02 00:06
I can repro this under the first pre-condition in the OP: 

<img width="1052" alt="image" src="https://github.com/Expensify/App/assets/16232057/280909fe-8ffd-42a0-8230-d1ab425355a7">

CC: @thienlnam

**Comment by jayeshmangwani** [comment] 2024-05-06 13:16
Waiting for proposals

**Comment by rezkiy37** [comment] 2024-05-07 13:46
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2024-05-08 15:52
Actively working on the issue. Seems like the problem with **Onyx** is that a component does not get the latest **Onyx** updates.

**Comment by rezkiy37** [comment] 2024-05-09 15:39
The problem is associated with the `withOnyx` HOC, it does not get the latest updates from `Onyx.connect`. I am deeply investigating `react-native-onyx` codebase to find something helpful. However, I already know a way how we can fix the bug. I tested the `useOnyx` hook and it works properly. The hook returns the most recent reports. So probably it is a case where we can replace `withOnyx` with `useOnyx`.

**Comment by trjExpensify** [comment] 2024-05-10 13:08
Assigning you @rezkiy37!

**Comment by rezkiy37** [comment] 2024-05-10 13:15
I've sent a proposal for an internal review. I will post it here today or on Monday.

**Comment by rezkiy37** [comment] 2024-05-13 08:24
Hey, @dominictb!
I am already working on the issue. Thank you for your [proposal](https://github.com/Expensify/App/issues/41284#issuecomment-2105341099), but I [took](https://github.com/Expensify/App/issues/41284#issuecomment-2098449706) the issue last week and going to finish it by myself. 
cc @trjExpensify

**Comment by rezkiy37** [comment] 2024-05-13 14:26
Actively working on the issue. Finding and discussing solutions to fix without using `useOnyx`.

**Comment by rezkiy37** [comment] 2024-05-14 15:35
Actively working on the issue. I've found a better solution to fix the bug directly inside `react-native-onyx` to fix `withOnyx` updates. I am sending a proposal for the internal review.

**Comment by jayeshmangwani** [comment] 2024-05-14 19:00
Not overdue, we are close to the [Proposal](https://github.com/Expensify/App/issues/41284#issuecomment-2110548826)

**Comment by rezkiy37** [comment] 2024-05-15 10:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tracking reports do not appear in **LHN** when created offline.

### What is the root cause of that problem?

I was investigating deeply how **Onyx** and **OnyxUtils** send updates to `withOnyx`. I can confirm that [OnyxUtils.getCollectionDataAndSendAsObject()](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/OnyxUtils.ts#L813) does not send latest updates to `withOnyx`. This function is being called before [OnyxCache.set()](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/OnyxCache.ts#L86) has been called. It means the function uses out-of-date values for further checks and to send updates.

### What changes do you think we should make in order to solve the problem?

I think that the function (_[OnyxUtils.getCollectionDataAndSendAsObject()](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/OnyxUtils.ts#L813)_) should check if there is no difference between data it wants to send and stored cache. So before [sending updates](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/OnyxUtils.ts#L881) to `withOnyx`, I am adding a new `then` right before `finally` to check if there is the difference. When there is a data leak, the function has to get a specific missed value and append it to the sending data. This fix prevents these kinds of leaks for all other keys, not only for `reports`. Therefore it confirms that it sends the really latest data to components.

```typescript
.then(() => {
    const allCacheKeys = cache.getAllKeys();
    const cacheKeys = Array.from(allCacheKeys).filter((k) => k.startsWith(mapping.key));
    const diff = lodashDifference(cacheKeys, Object.keys(data || {}));

    if (diff.length === 0) {
        return Promise.resolve();
    }

    diff.forEach((key) => {
        const cachedValue = cache.getValue(key);

        data[key] = cachedValue as OnyxValue<TKey>;
    });

    return Promise.resolve();
})
```

### What alternative solutions did you explore? (Optional)

1.  “Fetch” data in [Onyx.connect()](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/Onyx.ts#L96) via [OnyxUtils.tryGetCachedValue()](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/OnyxUtils.ts#L302) for the case when it was called for `withOnyx`.
2. Replace `withOnyx` by `useOnyx` in the app for [LHNOptionsList](https://github.com/Expensify/App/blob/main/src/components/LHNOptionsList/LHNOptionsList.tsx). This migration to useOnyx solves the problem. However, the hook is still under performance improvements and maybe we can have a perf hit if we use it in such critical components.

**Comment by jayeshmangwani** [comment] 2024-05-15 17:33
@rezkiy37 [Plan](https://github.com/Expensify/App/issues/41284#issuecomment-2112166628) looks good to me
🎀 👀 🎀 C+ reviewed

**Comment by thienlnam** [comment] 2024-05-15 18:25
I'm not entirely sure about the impact of a change in onyx like this,  @tgolen / @marcaaron do you mind taking a look and seeing what you think about this [proposal](https://github.com/Expensify/App/issues/41284#issuecomment-2112166628) please?

**Comment by marcaaron** [comment] 2024-05-15 19:48
>This function is being called before [OnyxCache.set()](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/OnyxCache.ts#L86) has been called

I'm not seeing where this happens. Could you maybe break it down step by step?

**Comment by marcaaron** [comment] 2024-05-15 19:49
>I think that the function ([OnyxUtils.getCollectionDataAndSendAsObject()](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/OnyxUtils.ts#L813)) should check if there is no difference between data it wants to send and stored cache.

Not sure if I understood this part. Wouldn't it be better to call it in the correct place vs. building in a check to see if there is a cache diff.

**Comment by rezkiy37** [comment] 2024-05-16 09:27
> > I think that the function ([OnyxUtils.getCollectionDataAndSendAsObject()](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/OnyxUtils.ts#L813)) should check if there is no difference between data it wants to send and stored cache.
> 
> Not sure if I understood this part. Wouldn't it be better to call it in the correct place vs. building in a check to see if there is a cache diff.

The **Onyx** call `OnyxUtils.getCollectionDataAndSendAsObject()` right in `Onyx.connect()`. It is not the incorrect place. The problem is that this function is called and starts to use some values. Then the app updates these values and `OnyxUtils.keyChanged()` updates `withOnyx` HOCs. Meanwhile, `OnyxUtils.getCollectionDataAndSendAsObject()` is still ongoing, but the initial values can be out-of-date. At the end the function updates `withOnyx` HOCs with those out-of-date values. So my idea is to avoid these wrong rewrites and verify that the function has the latest changes before sending updates.

**Comment by rezkiy37** [comment] 2024-05-16 12:12
> > This function is being called before [OnyxCache.set()](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/OnyxCache.ts#L86) has been called
> 
> I'm not seeing where this happens. Could you maybe break it down step by step?

For our case `OnyxCache.set()` is called when the app tries to send a request and does update optimistic data:

https://github.com/Expensify/App/blob/1faad15adcc79d796a8e065cc586615b755e8473/src/libs/API/index.ts#L61-L63

**Comment by marcaaron** [comment] 2024-05-17 00:40
Yah sorry I'm just not really connecting how the Onyx bug is linked to the proposal. 

Could we maybe go a bit more in depth WRT the problem itself and walk through how it happens? 

Can we start with the expectation that the optimistic "expense report" will show in the LHN? I'm hearing there's a problem in Onyx, but not making the connection between that problem and the bug we are trying to fix here.

**Comment by jayeshmangwani** [comment] 2024-05-17 09:12
let me try to break few things down: why it seems the issue is related to withOnyx and how it will lead to solving the existing problem of offline blank LHN optionslist

1. The main issue we are trying to solve is that we are getting a blank list in LHN, and the root cause is that we are getting the `itemFullReport` value null here:

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/LHNOptionsList/LHNOptionsList.tsx#L107-L109



2. On the LHNOptionsList we are using the withOnyx, And reports we are getting from it are the Outdated, and it looks like under the withOnyx we are sending the outdated data:

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/LHNOptionsList/LHNOptionsList.tsx#L249-L251

3. When we used withOnyx() HOC, the data we are sending back from the `getCollectionDataAndSendAsObject`, and here on the `getCollectionDataAndSendAsObject` function when we are sending the data using the `sendDataToConnection` method, the report is missing for the newly created offline expense. So before sending back the data, we add a check if the value is available in the cache and not on the data object, then append the missing values.

and below lines of code for checking the differnce between cache values and data will be placed before sending data to [sendDataToConnection](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/OnyxUtils.ts#L881) in the  [getCollectionDataAndSendAsObject](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/OnyxUtils.ts#L813) method

```js
.then(() => {
    const allCacheKeys = cache.getAllKeys();
    const cacheKeys = Array.from(allCacheKeys).filter((k) => k.startsWith(mapping.key));
    const diff = lodashDifference(cacheKeys, Object.keys(data || {}));

    if (diff.length === 0) {
        return Promise.resolve();
    }

    diff.forEach((key) => {
        const cachedValue = cache.getValue(key);

        data[key] = cachedValue as OnyxValue<TKey>;
    });

    return Promise.resolve();
})
```

**Comment by rezkiy37** [comment] 2024-05-17 09:45
@jayeshmangwani, your [explanations](https://github.com/Expensify/App/issues/41284#issuecomment-2117103786) is very good! Thank you!

Let me add more context for the 3rd point. The `withOnyx()` HOC reconnects to **Onyx** on the mount and updates. So we are interested in the case of the updates. 

The app sends a list of updates to **Onyx** for example via the optimistic data. During these updates, the `withOnyx()` HOC can reconnect a few times. As we remember `Onyx.connect()` calls `OnyxUtils.getCollectionDataAndSendAsObject()`. This, in its turn, [gets](https://github.com/Expensify/react-native-onyx/blob/b6a108d98f010462fae42aad2dbbf9baa509959d/lib/OnyxUtils.ts#L833) values from the cache. 

Right after that, **Onyx** updates reports that come from the optimistic data. These reports are set to the cache. However, `OnyxUtils.getCollectionDataAndSendAsObject()` is ongoing, because this function executes promises under the hood. At this point, we have the bug. The function continues to work with out-of-date data because it does not check for new values.

> So before sending back the data, we add a check if the value is available in the cache and not on the data object, then append the missing values.

**Comment by rezkiy37** [comment] 2024-05-21 08:52
@marcaaron @jayeshmangwani, guys can I go ahead and open a PR?

**Comment by jayeshmangwani** [comment] 2024-05-21 09:46
> @jayeshmangwani, guys can I go ahead and open a PR?

We need a green light from @marcaaron / @tgolen

**Comment by marcaaron** [comment] 2024-05-21 20:48
Let's bring it to Slack please. I am reluctant to greenlight changes to Onyx for a minor bug without multiple engineers agreeing to the changes.

**Comment by jayeshmangwani** [comment] 2024-05-23 13:22
Opened a discussion on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1716470445010589)

**Comment by jayeshmangwani** [comment] 2024-05-28 09:41
[Discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1716470445010589) has still not reached a conclusion

**Comment by rezkiy37** [comment] 2024-05-29 15:28
Work in progress. Looking for a way to reliably capture this race condition with an automated test. Also, chatting internally about other solutions.

**Comment by trjExpensify** [comment] 2024-06-03 20:19
Any luck, @rezkiy37?

**Comment by rezkiy37** [comment] 2024-06-04 08:10
I’ve pushed a [commit](https://github.com/Expensify/react-native-onyx/pull/549/commits/4dfa59c5bd83617b713c95e26fe18619f00eac35) with raw tests.

**Comment by rezkiy37** [comment] 2024-06-05 12:37
Trying to catch this bug with tests.

**Comment by rezkiy37** [comment] 2024-06-07 12:29
The hook useOnyx has been confirmed as a new approach for getting data. 

Based on my [proposal](https://github.com/Expensify/App/issues/41284#issuecomment-2112166628) there was a 2nd alternative solution to use the hook. Looks like it can be a main solution now. WDYT?

cc @jayeshmangwani @marcaaron @trjExpensify

**Comment by jayeshmangwani** [comment] 2024-06-07 12:36
I have don't have access to [slack link](https://callstack-hq.slack.com/archives/C01GTK53T8Q/p1717695182186119),But I am :+1: for the replacing withOnyx by useOnyx as withOnyx is officially [deprecated](https://expensify.slack.com/archives/C01GTK53T8Q/p1717695182186119) now.

**Comment by jayeshmangwani** [comment] 2024-06-07 12:53
Marc is OOO till June 16th, let's wait for others opinion

**Comment by tgolen** [comment] 2024-06-07 15:02
I don't know anything about this issue, but I'm 👍 for `useOnyx`

**Comment by rezkiy37** [comment] 2024-06-07 16:04
I've opened a PR (https://github.com/Expensify/App/pull/43294) for review 🙂

**Comment by trjExpensify** [comment] 2024-06-20 14:06
Yeah, totally. Go ahead and request on NewDot, and decline the offer on Upwork. 👍 

Payment summary as follows:

- $250 to @jayeshmangwani for the C+ review 

Regression test issue created here: https://github.com/Expensify/Expensify/issues/406236

Closing!

**Closed by trjExpensify** 2024-06-20 14:06 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by jayeshmangwani** [comment] 2024-06-22 17:45
Requested on NewDot

**Comment by JmillsExpensify** [comment] 2024-06-24 13:44
$250 approved for @jayeshmangwani
