### ISSUE TITLE
Admin also appears in the "invite new members list in workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21037] opened 2023-06-19 14:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. create new account
2. create new workspace
3. go to Settings > Workspace > Members
4. you can find yourself as member in list
5. click on invite button
## Expected Result: 
user should not appears in invite list ifr part of workspace
## Actual Result: 
user itself appears in invite list

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9e8fb9bf-c1a3-4af1-9a4a-b9a9f67e7354

<img width="956" alt="Screenshot (370)" src="https://github.com/Expensify/App/assets/43996225/4a29bcfd-6db6-49d7-9d3e-73c6b625e225">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686990342042729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2023-06-19 14:32
@kavimuru is this only occurring on web, or was that the only platform tested?

**Comment by Julesssss** [comment] 2023-06-19 14:40
I'm not able to reproduce this... Can you @zanyrenney?

**My user is not showing in search...**
![Screenshot 2023-06-19 at 15 38 39](https://github.com/Expensify/App/assets/10736861/9fd42f8c-5c98-48c3-bfdc-761cc4a92575)

**Comment by Julesssss** [comment] 2023-06-19 14:40
Reducing priority

**Comment by gadhiyamanan** [comment] 2023-06-19 14:41
@Julesssss please try with new account

**Comment by Julesssss** [comment] 2023-06-19 14:42
THis is a new account. I created the user, created the workspace, and immediately opened the member page

**Comment by gadhiyamanan** [comment] 2023-06-19 14:47
> THis is a new account. I created the user, created the workspace, and immediately opened the member page. Anyway, I'll leave the issue open while we attempt to reproduce. 

@Julesssss if it is new account why it shows number of users in list

**Comment by Pujan92** [comment] 2023-06-19 14:48
I am not able to reproduce in dev.

**Comment by kavimuru** [comment] 2023-06-19 15:02
@Julesssss I tested in public account.

**Comment by Julesssss** [comment] 2023-06-19 15:07
Sorry, I meant did Applause test all of the platforms? Or just web? Also, was this tested on production or just staging? I'm asking because it helps us to determine whether it should be a blocker.

**Comment by kavimuru** [comment] 2023-06-19 15:20
@Julesssss It is not reproducible in production. It is reproducible in all platforms in staging.

**Comment by Julesssss** [comment] 2023-06-19 15:24
Ah thanks. We should update the checkboxes in that case

**Comment by Julesssss** [comment] 2023-06-20 10:12
@zanyrenney are you able to reproduce this? So far only Applause can, so maybe this was fixed elsewhere?

**Comment by zanyrenney** [comment] 2023-06-20 17:02
No, I am not able to reproduce either: 
<img width="491" alt="2023-06-20_18-01-40" src="https://github.com/Expensify/App/assets/56830058/500d60b4-fb26-42f8-b836-aa869a88f85d">

I am on staging v1.3.29-8 so this isn't correct: 
> It is reproducible in all platforms in staging.

**Comment by zanyrenney** [comment] 2023-06-21 08:12
chatted with @Julesssss in DM to confirm, we should close this as its not happening anymore.

**Closed by zanyrenney** 2023-06-21 08:12 UTC
Labels: Engineering, Daily, Bug
