### ISSUE TITLE
Dev: Delay in removing 'New' marker After deleting newly sent message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25606] opened 2023-08-21 17:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat  
2. Send a message
3.  Click on “Mark as unread”
4. Now delete the message 
5. Notice new marker not removed with message
## Expected Result: 
New marker should be removed when deleting new sent message
## Actual Result: 
New marker not removed when deleting new sent message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** Dev
**Reproducible in production?:** Dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b1c81dce-2ca6-45d7-a2be-a02c4b36e230

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692306828126859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hayata-suenaga** [comment] 2023-08-21 18:07
on it now

**Comment by hayata-suenaga** [comment] 2023-08-21 18:25
okay I cannot re-produce this on production. If this issue is present on staging, then this is a deploy blocker.

https://github.com/Expensify/App/assets/98560306/5df20aad-96ba-4adb-b1b6-532619003165

**Comment by ayazhussain79** [comment] 2023-08-21 18:44
you can reproduce it on DEV

**Comment by hayata-suenaga** [comment] 2023-08-21 18:53
my dev env is not working well, but I gonna ask in #expensify-open-source channel to see if anyone made changes recently that might have caused this regression.

**Comment by hayata-suenaga** [comment] 2023-08-21 18:55
asked [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1692644143886639)

**Comment by hayata-suenaga** [comment] 2023-08-21 19:35
[This PR](https://github.com/Expensify/App/pull/18637) might be related. Asked in that PR.

**Comment by roryabraham** [comment] 2023-08-21 21:35
not reproducible on staging, so not a deploy blocker. Will be a deploy blocker tomorrow though, so leaving this as an hourly issue @hayata-suenaga

**Comment by hayata-suenaga** [comment] 2023-08-21 21:40
yea that's only on dev. I was wondering if the issue should be deploy blocker if it only exists on dev (main). Thank you for letting me know

**Comment by getusha** [comment] 2023-08-21 22:20
this can be fixed by adding aditiional check `reportAction.pendingActions !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE)` inside `ReportActionList` while passing shouldDisplayNewMarker or inside `ReportActionItem` alongside `props.shouldDisplayNewMarker &&` but it's hard to tell why it was working previously since it's a refactor which changed the logic entirely with new approach.

**Comment by tgolen** [comment] 2023-08-22 00:47
I'm decreasing the priority here

**Comment by stephanieelliott** [comment] 2023-08-22 16:57
Thanks @gedu! I'm going to put a `Weekly` label on this in that case, anyone looking for more frequent updates can look to the master issue https://github.com/Expensify/App/issues/23171

**Comment by stephanieelliott** [comment] 2023-09-21 18:21
Still working in https://github.com/Expensify/App/issues/23171

**Comment by stephanieelliott** [comment] 2023-09-29 05:17
https://github.com/Expensify/App/issues/23171 still open

**Comment by stephanieelliott** [comment] 2023-10-04 00:47
Still working in https://github.com/Expensify/App/issues/23171

**Comment by stephanieelliott** [comment] 2023-10-11 04:48
https://github.com/Expensify/App/issues/23171 still ongoing

**Comment by stephanieelliott** [comment] 2023-10-17 01:11
Still working in https://github.com/Expensify/App/issues/23171

**Comment by stephanieelliott** [comment] 2023-10-30 16:07
https://github.com/Expensify/App/issues/23171 still ongoing

**Comment by stephanieelliott** [comment] 2023-11-06 21:38
Still working in https://github.com/Expensify/App/issues/23171

**Comment by stephanieelliott** [comment] 2023-11-13 15:44
Still working in https://github.com/Expensify/App/issues/23171

**Comment by gedu** [comment] 2023-11-27 06:17
I will review it too

**Comment by gedu** [comment] 2023-11-27 10:03
Can not reproduce it.
I'm seeing just an small delay but correspond with the re-render and the list sorting.

https://github.com/Expensify/App/assets/1676818/ca6a73b9-8e3a-4a49-ac04-68ed60ab2d79

**Comment by hayata-suenaga** [comment] 2023-11-27 16:39
compared with the video in the original issue, the problem seems to have been fixed. We can close this. Do we need any payment @stephanieelliott ?

**Comment by stephanieelliott** [comment] 2023-11-28 03:09
Great! No payment due here as work was done by a Callstack expert contrib.

**Closed by stephanieelliott** 2023-11-28 03:09 UTC
Labels: Reviewing, Engineering, Weekly, Needs Reproduction, Bug
