### ISSUE TITLE
[HOLD for payment 2023-09-29] [HOLD for payment 2023-09-27] Web - Money request preview box doesn't have any space with user title

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27684] opened 2023-09-18 14:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money from any user
2. Click on that report preview to navigate IOU report
3. Observe the space between user name and request preview box

## Expected Result:
There should be space between the box and title

## Actual Result:
 There isn't any space between the box and title

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e8cc2178-7d08-4804-bbe0-658bae86e4ac

https://github.com/Expensify/App/assets/93399543/cb9ccac6-8f8a-48ae-a5d5-b31ab13dee3d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695048533117929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-09-18 15:01
@getusha Seems regression from your [PR](https://github.com/Expensify/App/pull/27465) where `styles.moneyRequestPreviewBox` applied before margin top.

**Comment by Pujan92** [comment] 2023-09-18 15:24
Sharing a proposal in case it is needed and considered.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Money request preview box space inconsistency before and after hover

### What is the root cause of that problem?
We are providing the `styles.moneyRequestPreviewBox` in this PR https://github.com/Expensify/App/pull/27465/files#diff-d8e6b69ad4461bebf91e940a67ddc07adf36a3f7c156d6066363c3bde06a0f8aR346 which has the background color property and in nested View we have margin top of 8px. So in marginal area also it shows that background color which causing this.

### What changes do you think we should make in order to solve the problem?
We can shift [this](https://github.com/Expensify/App/blob/d848eabee0042afd53007bafe3f2406d9c44b210/src/components/ReportActionItem/MoneyRequestPreview.js#L238) entire styles to the parent `PressableWithFeedback` styles [here](https://github.com/Expensify/App/blob/d848eabee0042afd53007bafe3f2406d9c44b210/src/components/ReportActionItem/MoneyRequestPreview.js#L345).
https://github.com/Expensify/App/blob/d848eabee0042afd53007bafe3f2406d9c44b210/src/components/ReportActionItem/MoneyRequestPreview.js#L238

https://github.com/Expensify/App/blob/d848eabee0042afd53007bafe3f2406d9c44b210/src/components/ReportActionItem/MoneyRequestPreview.js#L345

**Comment by bondydaa** [comment] 2023-09-18 17:07
looks like a fix is in the works already right? https://github.com/Expensify/App/pull/27692

**Comment by getusha** [comment] 2023-09-18 17:10
@bondydaa yes raised the PR since it was a regression from https://github.com/Expensify/App/pull/27465

**Comment by bondydaa** [comment] 2023-09-19 15:10
looks PR was merged https://github.com/Expensify/App/pull/27465. and deployed to staging

can we confirm on staging this is fixed and closed if so @kbecciv ?

**Comment by getusha** [comment] 2023-09-19 16:16
>@getusha I guess you meant https://github.com/Expensify/App/pull/27692

Oh yes! apologies 😄

**Comment by bondydaa** [comment] 2023-09-19 17:50
Oh doh 🤦 thank you, reviewing the fix PR https://github.com/Expensify/App/pull/27692/ now

**Comment by bondydaa** [comment] 2023-09-19 17:52
requested CP here https://expensify.slack.com/archives/C07J32337/p1695145933456359

**Comment by mountiny** [comment] 2023-09-20 02:21
Thanks for a quick progress here https://expensify.slack.com/archives/C07J32337/p1695145933456359 we decided not to CP right now as we already got bunch of CPs we need for the deploy and this seems like an issue which can go through the normal process

**Comment by bondydaa** [comment] 2023-10-04 22:40
closing as this was a fix to a regression so no payment needed

**Closed by bondydaa** 2023-10-04 22:40 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
