### ISSUE TITLE
[$500] iOS - Profile - Photo upload options are missing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32307] opened 2023-11-30 21:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in
3. Tap on your profile picture
4. Tap on your profile picture again
5. Tap on the "Upload photo" button

## Expected Result:
"Browse" option should be added so I can choose a photo from iCloud drive or from the iPhone internal storage

## Actual Result:
Profile photo upload options are missing. Currently I can take a photo or choose one from the gallery

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9bde98b8-5fef-404a-99c1-ddfe09b8c12b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb01e156c8ab43dd</li>
        <li>Upwork Job ID: 1730337464884461568</li>
        <li>Last Price Increase: 2023-12-21</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28118868</li>
<li>DylanDylann | Contributor | 28128145</li>
</ul></li>
    </ul>
</details>

**Comment by Santhosh-Sellavel** [comment] 2023-12-01 17:53
@alexpensify  This is a improvement not a bug, Can you confirm this internally, whether this is something we should fix or not, thanks!

**Comment by alexpensify** [comment] 2023-12-01 18:10
Thanks! I'll start a discussion on Monday.

**Comment by alexpensify** [comment] 2023-12-06 18:38
I've bumped the 🧵 and there is feedback that it might be a dupe.

**Comment by alexpensify** [comment] 2023-12-08 17:31
I've asked for some more feedback in another Slack channel.

**Comment by alexpensify** [comment] 2023-12-11 18:41
Still waiting for more feedback

**Comment by alexpensify** [comment] 2023-12-13 21:56
No update, I've asked again for more feedback.

**Comment by alexpensify** [comment] 2023-12-18 23:47
No update yet.

**Comment by alexpensify** [comment] 2023-12-20 23:57
Based on the feedback so far, I need to identify if this fits into a wave. TBD.

**Comment by alexpensify** [comment] 2023-12-23 18:25
I'm moving to Weekly. Due to other urgent GHs, I couldn't associate this one with a Wave before the holidays. 

## I will be offline from Friday, December 22, to Thursday, January 4, 2024. I will not be actively watching over this GitHub during this period. We can continue the review process in the new year-- thanks!

**Comment by alexpensify** [comment] 2024-01-04 19:09
I'm back online again and will start working on the next steps.

**Comment by alexpensify** [comment] 2024-01-09 01:09
No update yet

**Comment by alexpensify** [comment] 2024-01-10 18:38
No update, working on more urgent GHs and will review this one soon.

**Comment by alexpensify** [comment] 2024-01-17 19:16
Pitched it to this VIP group: 

https://expensify.slack.com/archives/C066HJM2CAZ/p1705518924933779

Waiting for confirmation on the next steps.

**Comment by alexpensify** [comment] 2024-01-19 19:39
@Santhosh-Sellavel - alright, this one has been associated with a VIP. Can we review the proposals again to see if one will work? Thanks!

**Comment by alexpensify** [comment] 2024-01-22 18:34
@Santhosh-Sellavel - any update here or let me know if you are unable to review this one? Thanks!

**Comment by Santhosh-Sellavel** [comment] 2024-01-22 18:58
Sorry missed this one, I think we should have a proposal here already above, I'll update soon!

**Comment by Santhosh-Sellavel** [comment] 2024-01-27 17:20
@alexpensify 
[PR](https://github.com/Expensify/App/pull/35164) is ready for review

I'm unavailable next week, so unassigning here please assign a new C+ here to move this forward

**Comment by DylanDylann** [comment] 2024-01-27 17:22
I can review PR as C+

**Comment by srikarparsi** [comment] 2024-01-28 18:47
Sounds good, assigning you to this and the PR @DylanDylann

**Comment by DylanDylann** [comment] 2024-01-29 07:26
@srikarparsi Could you help to assign me to this issue again ?

**Comment by alexpensify** [comment] 2024-02-12 15:35
@dukenv0307 any update to address the PR feedback? Thanks!

**Comment by alexpensify** [comment] 2024-02-27 22:54
Thanks for flagging, it looks like the PR was handled in the other GH.

**Comment by alexpensify** [comment] 2024-03-05 23:05
Automation didn't kick in here, I think the 7-day mark is tomorrow.

**Comment by alexpensify** [comment] 2024-03-06 22:18
Here is the payment summary: 

-  External issue reporter - n/a
-  Contributor that fixed the issue - @dukenv0307 $500 
-  Contributor+ that helped on the issue and/or PR - @DylanDylann - $250 

Upwork Job: https://www.upwork.com/jobs/~01cb01e156c8ab43dd

Extra Notes regarding payment: @DylanDylann - there is regression here but I mixed up the payments. I still input the $500 amount, instead of $250. This was my mistake and we will leave the amount paid as is. 

Everyone has been paid via Upwork, so I'm closing.

**Closed by alexpensify** 2024-03-06 22:18 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
