### ISSUE TITLE
Sign In - "STG" label displayed on the right side against "Expensify" label on Sign In page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33283] opened 2023-12-19 12:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31303

## Action Performed:
Precondition: User should be Signed Out
1. Open app
2. Observe the "STG" label position against "Expensify" label
3. Sign In to the app
4. Repeat step 2

## Expected Result:
The "STG" label position against "Expensify" label should be the same on Sign In and LHN pages

## Actual Result:
The "STG" label displays on the right side against "Expensify" label on Sign In page and "STG" label moved to the right against "Expensify" on the LHN page (it looks like a new design/feature on LHN page)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/97d9166e-9136-4701-a82d-59a93fb373ec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment] 2023-12-19 13:09
According to this PR, this is expected: https://github.com/Expensify/App/pull/32221

@shawnborton @mountiny could you please confirm/reject?

**Comment by shawnborton** [comment] 2023-12-19 13:47
Hmm but that being said, I'm not a huge fan of the placement of this label. I bet we can tuck it into the negative space by the y's tail somewhere? cc @Expensify/design

**Comment by shawnborton** [comment] 2023-12-19 13:47
Not a deploy blocker but I think we should make some updates to this one.

**Comment by Pujan92** [comment] 2023-12-19 13:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Header badge isn't in the correct place

### What is the root cause of that problem?
Badge isn't set with the title View and absolute values aren't correct.

### What changes do you think we should make in order to solve the problem?
We can move badge inside the adjacent View of the title so it will take the correct width to set its absolute position and make changes to bottom and right property values.

```
                : subtitle}
                {shouldShowEnvironmentBadge && <EnvironmentBadge />}
        </View>
```

https://github.com/Expensify/App/blob/aa1d87caddb6831061f3750bd78f77b42603e5e3/src/components/Header.tsx#L46-L48

```
bottom: 0,
right: -20,
```

https://github.com/Expensify/App/blob/aa1d87caddb6831061f3750bd78f77b42603e5e3/src/styles/index.ts#L3598-L3599

<img width="1439" alt="Screenshot 2023-12-19 at 18 52 31" src="https://github.com/Expensify/App/assets/14358475/5a638d13-ab2e-4a7e-9928-ad8978a0cd58">

**Comment by mountiny** [comment] 2023-12-20 09:02
@shawnborton I think we should wait for the full ideal nav to be implemented. and I agreee that this is not up for proposals @MaciejSWM will handle this once we decide.

Why I think its not that important is that this badge exists only in staging or dev so no real customers will ever face this so we can take our time

**Comment by Julesssss** [comment] 2023-12-21 15:44
Closing based on [this comment](https://github.com/Expensify/App/issues/33283#issuecomment-1864100614). please reopen if anyone disagrees

**Closed by Julesssss** 2023-12-21 15:44 UTC
Labels: Engineering, Daily, Design
