### ISSUE TITLE
[$250] Chat - No "Edit" option on comment with video attachment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44098] opened 2024-06-20 16:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** emilio.utest@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42463
## Action Performed:
1. Access the New Expensify Beta app
2. Sign into a valid account
3. Send a comment with a video attachment to any chat.
4. Click the 3 dot menu on the comment

## Expected Result:
User expects to see an Edit comment option as on Web

## Actual Result:
No Edit comment option is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ec3f7b6f-f2ed-4dfa-adbc-c0bd7bad28c4

<img width="1440" alt="On_Web_" src="https://github.com/Expensify/App/assets/78819774/a3e6507f-52ee-4871-bfe4-32da949dccd5">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138b8d7dfb7321ad9</li>
        <li>Upwork Job ID: 1803878166972059685</li>
        <li>Last Price Increase: 2024-06-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by lanitochka17** [comment] 2024-06-20 16:27
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-20 16:27
We think that this bug might be related to #vip-vsp

**Comment by jantznick** [comment] 2024-06-20 21:00
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
User expects to see an Edit comment option as on Web

### What is the root cause of that problem?
Currently editing a report is not available if the report is not an attachment per src>libs>ReportUtils.ts
```
/**
 * Can only edit if:
 *
 * - It was written by the current user
 * - It's an ADD_COMMENT that is not an attachment
 * - It's an expense where conditions for editability are defined in canEditMoneyRequest method
 * - It's not pending deletion
 */
```

### What changes do you think we should make in order to solve the problem?
Modify the canEditReportAction function to not check if the report is an attachment or, possibly check if it is a video attachment depending on desired functionality across different attachment types.

### What alternative solutions did you explore? (Optional)
Can modify the check to only allow editing video attachments but not for other attachments.

Also noticed an additional issue with the above fix.
When the above change is made it breaks the rendering of chat messages that include text and a video attachment to not render the video properly. This is due to the report action item single component rendering it as text, not an attachment comment fragment. This is an additional fix that will be required as part of the same PR.

**Comment by jantznick** [comment] 2024-06-20 21:04
Contributor details
Your Expensify account email: thenickjantz@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019d41aaa9beb952fe

**Comment by jantznick** [comment] 2024-06-24 02:09
@rayane-djouah This appears to be fixed, can you please test?

**Comment by jantznick** [comment] 2024-06-25 22:13
@rayane-djouah The original bug seems to be fixed on desktop and web. This bug you're mentioning now seems to be related to not being able to edit the comment due to it not having a response from the server yet after coming back online. Will that be fixed as part of this issue or a new one?

<img width="1840" alt="Screenshot 2024-06-25 at 5 09 07 PM" src="https://github.com/Expensify/App/assets/18474500/7833824e-1264-4008-b5ba-e425ac718675">
<img width="1312" alt="Screenshot 2024-06-25 at 5 10 56 PM" src="https://github.com/Expensify/App/assets/18474500/f65ba0da-d771-4934-b5aa-a031a1d489c4">

**Comment by jantznick** [comment] 2024-06-26 17:09
Just so we're clear, the proposal you're looking for is completely unrelated to the original. The new issue is that while the request is being made to the server there is no edit button, correct?

**Comment by slafortune** [comment] 2024-07-01 15:54
It seems that updating would have been easy enough since @jantznick already has the base work done and just needs to make some updates, though it really doesn't matter since there is only one proposal - no one will be paid on this one if it's just closed.

**Closed by slafortune** 2024-07-01 15:54 UTC
Labels: External, Daily, Help Wanted, Bug
