### ISSUE TITLE
 report screen does not scroll to bottom on send new messages

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22860] opened 2023-07-14 02:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat which has few messages
2. send any message
3. click on that message qnd select Reply in thread option
4. go to thread and send any message
5. go back to main report screen
6. scroll to top and send any message

## Expected Result: 
user should scroll to bottom on send new messages
## Actual Result: 
user does not scroll to bottom on send new messages

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c5ebff86-5e8a-44b9-b6cb-fb3ad025064e

https://github.com/Expensify/App/assets/43996225/c14d136d-a517-46f2-8356-999c0e6aba0f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689260262084409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment] 2023-07-14 04:38
Seems like dupe of https://github.com/Expensify/App/issues/21603

**Comment by alexpensify** [comment] 2023-07-14 18:56
Thanks for flagging, I agree and will close this GH.

**Closed by alexpensify** 2023-07-14 18:56 UTC
Labels: Daily, Bug
