### ISSUE TITLE
[HOLD for payment 2023-10-27] [$500] Android - Keyboard stays open when getting back to amount input page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27543] opened 2023-09-15 16:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Request money
3. Click on the currency sign & try to select any currency asap
4. Try few times
5. Observe the keyboard stays open few times.

## Expected Result:
The keyboard should be closed on the amount input page.

## Actual Result:
The keyboard is not closed on the amount input page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d282c81f-10a0-4ada-bb68-0d30a383a08e

https://github.com/Expensify/App/assets/93399543/17b2fbc1-ed02-481c-a4b7-598caee3c0fb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694209564341799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8a396e607bd78b9</li>
        <li>Upwork Job ID: 1702718401323413504</li>
        <li>Last Price Increase: 2023-10-06</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 27221285</li>
<li>Krishna2323 | Reporter | 27221287</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-15 16:18
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Android - Keyboard stays open when getting back to amount input page
### What is the root cause of that problem?
The root cause is the use of keyboardShouldPersistTaps="always" on SectionList used in the BaseOptionsList. This property essentially dictates that the keyboard should remain open even after a tap on the screen (like selecting an any result).
https://github.com/Expensify/App/blob/bbc23423c7ddbffe96bc399a198df767db7f4857/src/components/OptionsList/BaseOptionsList.js#L225-L248
### What changes do you think we should make in order to solve the problem?
We need to dismiss keyboard by using Keyboard.dismiss() before navigating with back button or navigating using confirmCurrencySelection function.
https://github.com/Expensify/App/blob/bbc23423c7ddbffe96bc399a198df767db7f4857/src/pages/iou/IOUCurrencySelection.js#L79-L92
I also tried to dismiss the keyboard using cleanup function but it didn't worked.
useEffect(() => () => Keyboard.dismiss(), []);
### Result

**Comment by PiyushChandra17** [comment] 2023-09-15 19:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The keyboard is not closed on the amount input page.

### What is the root cause of that problem?
We are using `keyboardShouldPersistTaps="always"` in BaseOptionsList. This basically means that Keyboard should stay visible after a tap, and "always" means it will not dismiss automatically. This is the root cause.

### What changes do you think we should make in order to solve the problem?
We need to add `Keyboard.dismiss()` right AFTER navigating with back button AND navigating using confirmCurrencySelection function.

https://github.com/Expensify/App/blob/191bda19b9acd42e83c5f87a870a483c30da7cc5/src/pages/iou/IOUCurrencySelection.js#L79-L92

### What alternative solutions did you explore? (Optional)
NA

**Comment by strepanier03** [comment] 2023-09-15 21:16
While testing this the behavior I run into is that the keyboard is momentarily kept open but then closes after a second or two. I haven't been able to successfully get the keyboard to stay open.

**Comment by ArekChr** [comment] 2023-09-18 07:47
I was unable to reproduce the issue on macOS using Chrome, and I don't have access to a Windows machine for testing. Could @strepanier03 please reassign me, as I won't be able to complete the review for this checklist?

**Comment by sophiepintoraetz** [comment] 2023-09-18 08:44
@strepanier03 - FYI, if the Applause team have applied the `External` label, you do not need to replicate it (as Applause already have). We just need to check it's a) not a feature and b) not a duplicate.

**Comment by ArekChr** [comment] 2023-09-18 13:28
While the keyboardShouldPersistTaps="always" setting does keep the keyboard open, I believe the root issue may be with React Native's input handling itself.

The input component should programmatically blur and dismiss the keyboard when removing the screen. This would be a more robust solution, ensuring the keyboard doesn't remain open across different parts of the application.

**Comment by sophiepintoraetz** [comment] 2023-09-22 05:26
@ArekChr - are you saying that this is more of a feature request rather than a bug fix or you saying that the proposals don't encompass programatically blur and dismiss the keyboard?

**Comment by ArekChr** [comment] 2023-09-22 08:04
@sophiepintoraetz, I believe the root cause lies in the react-native repo. The proposal from @PiyushChandra17 looks good as a workaround. However, I'm still waiting for more proposals.

**Comment by mvtglobally** [comment] 2023-09-28 03:21
Issue not reproducible during KI retests. (First week)

**Comment by sophiepintoraetz** [comment] 2023-09-28 03:28
Hmm, looks like this bug might have been resolved.

**Comment by sophiepintoraetz** [comment] 2023-10-02 09:26
Waiting for confirmation bug has been resolved.

**Comment by sophiepintoraetz** [comment] 2023-10-05 04:37
@mvtglobally - can you confirm whether this bug is still reproducible?

**Comment by lanitochka17** [comment] 2023-10-11 12:56
Issue reproducible on  Build 1.3.81-4

https://github.com/Expensify/App/assets/78819774/ad9cac72-2c15-4e3b-adf6-317e11e99a6c

![Screenshot_2023-10-11-15-13-58-74_4f9154176b47c00da84e32064abf1c48](https://github.com/Expensify/App/assets/78819774/39c8fab7-9503-4bd9-82e9-78f22d98bc55)

**Comment by ArekChr** [comment] 2023-10-12 11:43
@Krishna2323 What is the root cause of this issue? I believe this happens only on the split bill. I didn't see this behavior before on different screens with text input. We have set `keyboardShouldPersistTaps="always"` in BaseOptionList, which is used in many places in NewDot

**Comment by ArekChr** [comment] 2023-10-16 10:13
@Krishna2323 agree we are using a similar approach in different places. Let's fix that in this way, [proposal](https://github.com/Expensify/App/issues/27543#issuecomment-1721536014) approved.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by Beamanator** [comment] 2023-10-16 14:25
Seems like we reproduced this, right @ArekChr ? If so, I'll remove the `Needs Reproduction` label

**Comment by ArekChr** [comment] 2023-10-23 12:32
- [x] Link to the PR: No bug identified, this is react-native issue.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I don’t think we need to add a regression test here.

**Comment by sophiepintoraetz** [comment] 2023-10-26 23:43
Paid!

**Closed by sophiepintoraetz** 2023-10-26 23:43 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
