### ISSUE TITLE
[$1000] Details page for secondary login doesn't display avatar and 'Local time' info

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21054] opened 2023-06-19 17:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: account A has a secondary login account B
1. From a tab where account C is signed in start a chat with account A
2. Mention primary login account A, and secondary login account B
3. Click on the primary login account A mention & observe the details sidebar
4. Click on the secondary login account B mention & observe the details sidebar
## Expected Result: 
Details page should display an avatar and 'Local time' info for secondary login account B
## Actual Result: 
Details page doesn't display an avatar and 'Local time' info for secondary login account B

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2b3c03e0-44cb-4425-99b7-ed67694a2bf3

https://github.com/Expensify/App/assets/43996225/59796984-759d-40dd-830e-8019781d96d7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686952562376199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0157924ae1c89d3495</li>
        <li>Upwork Job ID: 1671077404255952896</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-06-20 08:47
I managed to reproduce this, thanks. Couldn't find an existing issue for it, but I did stumble across [this bug](https://github.com/Expensify/App/issues/15511) while reproducing

**Comment by alitoshmatov** [comment] 2023-06-20 10:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Details page for secondary login doesn't display avatar and 'Local time' info 
### What is the root cause of that problem?
When we click mentioned user it goes to `DetailsPage` which gets login from route and using login looks for user details from `personalDetailsList`. If mentioned user is not here, it will return undefined. This occurs in many places, when we mention user which we have not interacted with, or when we mention secondary login of user.
### What changes do you think we should make in order to solve the problem?
We have new `ProfilePage` component which is doing exactly the same, but this component recieves an `accountID` and retrieves user details from backend.
https://github.com/Expensify/App/blob/e6c2704eb43d4d31a55eff5d5d1b3e89c5292bc3/src/pages/ProfilePage.js#L96-L100

We should migrate to `ProfilePage` when opening user details from mentions. Also we should add functionality to retrieve user details with login too. Also it requires some backend changes.

### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2023-06-20 11:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Details page for secondary login doesn't display avatar and 'Local time' info

### What is the root cause of that problem?
The `DetailsPage` takes `login`(email/phone) for finding the user, and there is no info about the id for that record about `accountID` and if we search by using `login`, we won't find any user until it's default contact method.
That's why the email and local time is not being showed.

### What changes do you think we should make in order to solve the problem?
We can use `ProfilePage` to display the content for user.
The `accountID` that will be passed is the current user's accountID as all contact method belong to the particular user.

### What alternative solutions did you explore? (Optional)
We can modify `DetailsPage` component to display the user details according to `accountID`

**Comment by sobitneupane** [comment] 2023-06-22 03:15
Started a discussion to know if we have any way of getting accountID from login.

https://expensify.slack.com/archives/C02NK2DQWUX/p1687403669803389

**Comment by conorpendergrast** [comment] 2023-06-23 09:32
From that discussion, we're going to close this out. When we migrate mentions to be accountID-based, we'll no longer have this bug so it's not worth fixing today. I've removed the Help Wanted label to reflect that.

I'll pay @Natnael-Guchima as the bug reporter, and then will close this.

**Comment by conorpendergrast** [comment] 2023-06-23 09:33
Contract sent

**Comment by Natnael-Guchima** [comment] 2023-06-23 09:51
> Contract sent

I have accepted the offer. Thanks @conorpendergrast

**Comment by conorpendergrast** [comment] 2023-06-23 19:58
Paid now! Closing this out as it will be handled in this internal project: https://github.com/Expensify/Expensify/issues/290083

Thank you!

**Closed by conorpendergrast** 2023-06-23 19:58 UTC
Labels: External, Daily, Bug
