### ISSUE TITLE
#new-expensify-feedback room shows a flickering skeleton when accessed from link

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37697] opened 2024-03-04 19:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709570318571869
 
## Action Performed:
1. Open Expensify feedback public room

## Expected Result:
Should open without any skeleton

## Actual Result:
Skeleton appears in the chat page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screen Shot 2024-03-04 at 2 38 01 PM](https://github.com/Expensify/App/assets/38435837/d704c0b4-01fc-43db-b675-b6d5f418881f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e6901ec82d29559</li>
        <li>Upwork Job ID: 1765099040783011840</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

**Comment by garrettmknight** [comment] 2024-03-05 19:43
Ooops - dupe of https://github.com/Expensify/App/issues/37661

**Closed by garrettmknight** 2024-03-05 19:43 UTC
Labels: Daily, Internal, Bug
