### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500]  Workspace - Error page appears for a second after deleting a Workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30100] opened 2023-10-20 18:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-10
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with any account
2. Open the workspace #admins or #announce cha
3. Press the chat header to open the details
4. Press the workspace name below the chat name. You will be navigated to the workspace page
5. Delete the workspace

## Expected Result:
You will be navigated back to the chat details

## Actual Result:
Error page appears for a second and then navigated back to the chat details

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 
![Bug6244780_1697826660078!Error](https://github.com/Expensify/App/assets/78819774/ad9d5673-8743-425a-8ee6-106ca1d8d42a)

https://github.com/Expensify/App/assets/78819774/a16b6196-47fb-4ef2-9651-cc0b4542770d

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by samilabud** [comment] 2023-10-21 04:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error page appears for a second after deleting a Workspace
### What is the root cause of that problem?
When the prop `shouldShow` accepts any change of policy, like PolicyUtils.isPendingDeletePolicy(policy), the component renders each time the policy change, in this case when pressing the delete workspace button the policy value trigger 3 times.
### What changes do you think we should make in order to solve the problem?
The best option should be to use the react hook to wait for the policy value change to send a true/false to the component below:
https://github.com/Expensify/App/blob/4a1e2b3e8a1f73992173264276fef2ded1fd5918/src/pages/workspace/WorkspaceInitialPage.js#L204

**Comment by samilabud** [comment] 2023-10-25 21:00
## Proposal
[Updated](https://github.com/Expensify/App/issues/30100#issuecomment-1773652524)

@hoangzinh  this was what I meant, please verify again

**Comment by stephanieelliott** [comment] 2023-10-30 16:37
Hey @hoangzinh can you review this updated proposal when you get a chance: https://github.com/Expensify/App/issues/30100#issuecomment-1773652524

**Comment by samilabud** [comment] 2023-10-31 14:39
## Proposal
[Updated](https://github.com/Expensify/App/issues/30100#issuecomment-1773652524)

@hoangzinh you are right, I have changed the proposal for update when policy/workspace has a change, see how it looks:
https://github.com/Expensify/App/assets/5216036/da6e9d0a-8afb-48a8-8e28-a425e7b171bc

On the other hand, currently, I can't reproduce the bug in the main branch, could you or someone else?

**Comment by samilabud** [comment] 2023-11-01 18:01
I think I'm missing something 😅, I have tried in android, iphone15 and currently in the same version you have shared (iPhone 14 IOS 16.2), but I can't reproduce it. 

https://github.com/Expensify/App/assets/5216036/5ec375b9-d9ad-4778-b51d-5eb2e603470d

Other tests:

https://github.com/Expensify/App/assets/5216036/d796478b-0152-4621-8fc7-4088dd96e72f


https://github.com/Expensify/App/assets/5216036/452553d3-6092-45cf-ae8c-b7af161ae6d5



Please if you see anything I'm doing wrong let me know.

**Comment by lanitochka17** [comment] 2023-11-02 14:05
@hoangzinh @stephanieelliott 
Issue reproducible on IOS 17


https://github.com/Expensify/App/assets/78819774/e58443dd-d8b1-4010-9c92-11a2d837929a

**Comment by stephanieelliott** [comment] 2023-11-06 21:07
Still collecting proposals

**Comment by stephanieelliott** [comment] 2023-11-08 07:03
Reapplying the `Bug` label to get another BZ member on this while I am OOO til Nov 13. Thanks @trjExpensify,  I'll grab this back from you when I return!

**Comment by trjExpensify** [comment] 2023-11-09 00:33
@hoangzinh can you address this question please? https://github.com/Expensify/App/issues/30100#issuecomment-1794358571

**Comment by mvtglobally** [comment] 2023-11-18 04:30
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment] 2023-11-22 18:03
👋 checklist time, @hoangzinh!

**Comment by trjExpensify** [comment] 2023-11-23 19:24
Yep, agree this was caught by Applause when executing the "core" steps of deleting a workspace. 

Okay, payments are as follows by my calculations: 

- $500 to @hoangzinh for the C+ review
- $500 to @dukenv0307 for the fix 

No urgency bonuses apply as the PR was created after the Oct 24th cutoff. 

Sent you both offers!

**Comment by trjExpensify** [comment] 2023-11-24 14:21
@dukenv0307 - paid! 

@hoangzinh hm, interesting. Let me check.

**Comment by trjExpensify** [comment] 2023-11-24 14:24
Okay, how about now? :)

**Comment by trjExpensify** [comment] 2023-11-24 15:39
Nice one, paid. Closing!

**Closed by trjExpensify** 2023-11-24 15:39 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
