### ISSUE TITLE
Room - 'No workspace found' page is not displayed when user navigates to room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34253] opened 2024-01-10 16:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Sign up with a new account & verify that you are not a member of any workspace
2. Click on 'FAB' menu > click on 'Start Chat'
3. Click on 'Room'

## Expected Result:
'No workspace found' page should be displayed

## Actual Result:
User is navigated to 'Create room' page but is unable to create. a room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/32774215-8fd9-44d2-a64c-ad8c7c5e79ea

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment] 2024-01-10 16:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
The default "{user}'s Expenses" workspace is now present in Onyx for the newly created users.

### What changes do you think we should make in order to solve the problem?
If we don't want to allow to create rooms in it, we should filter out the default "{user}'s Expenses" workspace here:

https://github.com/Expensify/App/blob/38cf1b6d7c3a5abc1fb5c5652e99018e87794a1d/src/pages/workspace/WorkspaceNewRoomPage.js#L188-L196


### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-10 16:24
BTW, this is a regression from https://github.com/Expensify/App/pull/34046
cc: @iwiznia

**Comment by iwiznia** [comment] 2024-01-10 16:33
Huh? Why/how? Ohhhhh, is it because we are not creating the chats for the admin? Basically what @Julesssss pointed out [here](https://github.com/Expensify/Web-Expensify/pull/40411#discussion_r1447315172)?

**Comment by paultsimura** [comment] 2024-01-10 16:36
Yes. We should have kept the `policy.isPolicyExpenseChatEnabled` check here:

<img width="1150" alt="image" src="https://github.com/Expensify/App/assets/12595293/1bfe7413-d64e-4fd0-bc90-bd4767d8b74e">

**Comment by Julesssss** [comment] 2024-01-10 16:39
I think you mean @mountiny.

Just noting that the UI issue reminds me of [this bug](https://github.com/Expensify/App/issues/30618).

**Comment by iwiznia** [comment] 2024-01-10 16:41
Damnit! Sorry about that. I swear it's your avatars, they look too similar for my shitty ill working eyes 😂

**Comment by cead22** [comment] 2024-01-11 01:28
Looks like we're waiting on Vit to confirm, and this might need a backend fix. @iwiznia I assigned you since you'll be on before me tomorrow, and you seem to be familiar with this issue

**Comment by thienlnam** [comment] 2024-01-11 04:23
Should we revert that PR for the meantime so we can continue with deploy?

**Comment by thienlnam** [comment] 2024-01-11 07:59
Ended up reverting it https://github.com/Expensify/App/pull/34311 - which actually ended up overlapping with another TS change that was merged to main that I fixed [here](https://github.com/Expensify/App/pull/34315)

**Comment by iwiznia** [comment] 2024-01-11 18:11
So can we close this now that it was reverted?

**Comment by thienlnam** [comment] 2024-01-12 01:29
Yeah, we can close this since this bug no longer exists and then move the convo to the original issue

**Closed by thienlnam** 2024-01-12 01:29 UTC
Labels: Engineering, Daily
