### ISSUE TITLE
[$1000] Fix navigating to workspace chat when a new invited user logs in

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#12041] opened 2022-10-20 14:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace from an account that's on the policyExpenseChat beta (e.g @expensifail.com)
2. Add a new member to the workspace via Manage Members > Invite
3. CMD+F and search the member's name to navigate to their workspace chat
4. Write a couple of messages in the member's workspace chat, then log-out of the admin account
5. Validate the member account and log-in to NewDot
6. Observe that you land in the Concierge DM and not the member's workspace chat

## Expected Result:
User should be navigated to the correct chat

## Actual Result:
User is not navigated to the correct chat

## Workaround:
Manually navigate to the chat

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012abff40d9e607123</li>
        <li>Upwork Job ID: 1688926809469202432</li>
        <li>Last Price Increase: 2023-08-22</li>
    </ul>
</details>

**Comment by techievivek** [comment] 2022-10-31 08:09
Will look into it this week.

**Comment by techievivek** [comment] 2022-10-31 15:31
Not overdue.

**Comment by techievivek** [comment] 2022-11-09 08:32
I think this might get fixed [here](https://github.com/Expensify/App/issues/11948)

**Comment by techievivek** [comment] 2022-11-09 08:34
I will follow the conversation there and see if that would also fix the navigation issue for this case or not.

**Comment by techievivek** [comment] 2022-11-23 07:23
I was ooo so looking into it today.

**Comment by techievivek** [comment] 2022-12-01 09:11
Seems like the drawer is open and maybe that's sometimes users are not navigated to the workspace chat.

I just tested this and though the drawer state is `open` it did navigate me to the workspace chat.

![Screenshot 2022-12-01 at 2 38 24 PM](https://user-images.githubusercontent.com/35863227/205012372-ec3c024c-ec49-4389-8ff9-86217aeae88d.png)

I will test it a few more just to be sure and then I will add this issue on HOLD because with navigation refactor this will be automatically fixed as we are switching to stack-based navigation.

**Comment by techievivek** [comment] 2022-12-01 09:45
Tested this couple of times and every time it navigated to workspace chat on Android though the drawer state was `open`.

![Screenshot 2022-12-01 at 3 07 19 PM](https://user-images.githubusercontent.com/35863227/205020067-ca3d5e53-21cf-4875-a3c6-92afada95a74.png)
![Screenshot 2022-12-01 at 3 13 22 PM](https://user-images.githubusercontent.com/35863227/205020086-b3227bd5-0f09-402c-8b72-3608aecfa66a.png)

@luacmartins Do you mind giving it a try just to see if this still happens? Thanks

**Comment by luacmartins** [comment] 2022-12-01 16:38
I just tested and it seems like this doesn't work at all anymore on any platform 😢 Looking at the logs, it seems like we are never setting `ONYXKEYS.IS_LOADING_REPORT_DATA` to `false` [here](https://github.com/Expensify/App/blob/92d09f7ba88f389f7fa24aed0d1cf2da597f59a2/src/libs/actions/App.js#L128-L141). Am I missing something?

**Comment by techievivek** [comment] 2022-12-01 17:48
This is weird, it worked perfectly for me. This is what I did.
1. Invited a new user to a workspace which created a chat between admin and newly invited user.
2. Added some messages for the invited user in the workspace chat.
3. Logged out from the admin account.
4. Validated the invited user account and logged in to newDot.
5. It right away took me to workspace chat.

I will a screen share recording tomorrow.

**Comment by techievivek** [comment] 2022-12-02 16:28
Sorry, I couldn't get time to look into it today. I will share a recording tomorrow for sure.

**Comment by techievivek** [comment] 2022-12-05 07:50
Here is a video of it.

https://user-images.githubusercontent.com/35863227/205582148-0fdc51b0-f22a-45e9-b713-52918b65fa23.mov

**Comment by luacmartins** [comment] 2022-12-07 16:09
@techievivek it seems to be working for me now 😕  

https://user-images.githubusercontent.com/22219519/206230741-2e66a430-170c-41c6-9771-27e1e8f3e689.mov

**Comment by techievivek** [comment] 2022-12-08 06:00
🤣 Yeah, it seems inconsistent. I will add this issue under Navigation reboot and will tackle this once the navigation reboot is implemented.

**Comment by techievivek** [comment] 2022-12-19 09:02
Not overdue, we are holding this for App navigation reboot.

**Comment by techievivek** [comment] 2022-12-28 10:17
It's on hold for the navigation reboot project.

**Comment by trjExpensify** [comment] 2023-01-13 14:06
I ran some end-to-end retests on workspace chats today and this worked fine for me as well. I think there are a few instances just broadly with inconsistent navigation on sign-in, agree with this call to hold on the nav reboot.

**Comment by techievivek** [comment] 2023-01-30 08:58
On hold for navigation reboot project.

**Comment by techievivek** [comment] 2023-03-03 09:50
On hold for navigation reboot project.

**Comment by techievivek** [comment] 2023-04-03 13:51
On hold for navigation reboot.

**Comment by techievivek** [comment] 2023-05-05 06:38
On hold for navigation reboot. We are making good progress on the project, so hoping to test and close this soon.

**Comment by techievivek** [comment] 2023-06-06 12:22
On hold for navigation refactor.

**Comment by JmillsExpensify** [comment] 2023-06-26 21:02
Adding myself on this one now that the navigation refactor is complete and I need to re-test.

**Comment by JmillsExpensify** [comment] 2023-06-27 04:24
Alright, I just re-tested this one and I successfully landed in the workspace chat. Now I do land in the Concierge chat if I'm not on the beta, policyExpenseChat beta, but otherwise it works like a charm now. I'm going to close this issue, though please re-open if anyone disagrees.

**Comment by trjExpensify** [comment] 2023-07-07 12:17
Didn't seem to work for me as a new member:

<img width="1505" alt="image" src="https://github.com/Expensify/App/assets/16232057/94e3ffd9-52c6-430f-ace8-e661ced8fbe8">

**Comment by techievivek** [comment] 2023-08-08 14:54
We can send it back to the contributors, I am pretty sure they should be able to fix this up.

**Comment by Talha345** [comment] 2023-08-11 19:37
How can I get an policyExpenseChat beta (e.g @expensifail.com) account to reproduce this issue?

**Comment by techievivek** [comment] 2023-08-14 13:05
@Talha345 Please have a look at the working on beta features section here: https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#working-on-beta-features

**Comment by Talha345** [comment] 2023-08-14 13:07
Thanks, will check and revert

**Comment by luacmartins** [comment] 2023-08-14 14:37
>On Dev you should have access to all betas.
@trjExpensify I think that works for internal engineers only, since external contributors use the staging/production API.

**Comment by trjExpensify** [comment] 2023-08-14 14:41
Oh, hm.. it's in the contributing.md file though as @techievivek pointed out!

**Comment by luacmartins** [comment] 2023-08-14 16:14
Yea, that works to see the UI in the frontend or things that don't depend on the API, but in this case the API won't return the `policyExpenseChat` so the user won't be able to actually see them.

**Comment by Talha345** [comment] 2023-08-14 17:43
> Yea, that works to see the UI in the frontend or things that don't depend on the API, but in this case the API won't return the `policyExpenseChat` so the user won't be able to actually see them.

@luacmartins How can I reproduce this issue then?

**Comment by luacmartins** [comment] 2023-08-14 18:10
We'd need to add your email to the beta.

**Comment by Talha345** [comment] 2023-08-14 18:24
@luacmartins Can you please add talha.97.mahmood+55@gmail.com?

**Comment by luacmartins** [comment] 2023-08-14 18:58
Done! Changes should be live in ~1h.

**Comment by Talha345** [comment] 2023-08-14 19:00
Thanks a lot!

**Comment by Talha345** [comment] 2023-08-14 21:01
@techievivek @luacmartins When I login using the member account, Concierge chat opens but I also cannot see the chat where the user who invited me sent messages.I can only see the default announce channel of the workspace.Also the drawer opens automatically.

![image](https://github.com/Expensify/App/assets/36226639/a262d6e9-6e51-42dd-80d8-143efd2dbd5a)

What should be the expected behaviour in this case? Can you please clarify!

**Comment by techievivek** [comment] 2023-08-22 13:05
I tried reproducing this but it seems to work just fine for me.

https://github.com/Expensify/App/assets/35863227/2967b172-3534-4a46-a29b-81abee1469d4


https://github.com/Expensify/App/assets/35863227/d3529de0-7353-4d5f-af6f-a8f5eb27e26e



I saw an another bug tho where the "request money" option appeared without interaction. Isn't that unexpected?

<img width="859" alt="Screenshot 2023-08-22 at 6 31 38 PM" src="https://github.com/Expensify/App/assets/35863227/aa10109f-17ea-490b-875a-29794400c0ba">

**Comment by techievivek** [comment] 2023-08-22 13:20
Maybe the order in which these things matter? Let me try with admin inviting the user to the workspace first, and only then the user validates their account.

**Comment by techievivek** [comment] 2023-08-22 13:29
Seems to work the other way around as well.

https://github.com/Expensify/App/assets/35863227/4b0e6071-ca69-4eb9-b07c-ed40452e1c99

@trjExpensify I am unable to reproduce this on my end. 😕

**Comment by trjExpensify** [comment] 2023-08-22 13:40
Maybe the nav reboot fixed it then? The drawer should be open btw, so that's expected. I'm happy to close this out, we can circle back if we come across it again. Will leave that call to you and @JmillsExpensify assigned on the issue though!

**Comment by techievivek** [comment] 2023-08-24 10:04
> Maybe the nav reboot fixed it then?

Jaons did point that out here https://github.com/Expensify/App/issues/12041#issuecomment-1608774465, going to close this. Feel free to re-open if this persists.

**Closed by techievivek** 2023-08-24 10:04 UTC
Labels: External, Engineering, Daily, Help Wanted
