### ISSUE TITLE
 IOU - User B can't request money to user A inside the IOU report user A created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28816] opened 2023-10-04 13:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/28542
## Action Performed:
Pre-requisite: user must be logged in with 2 different accounts
1. As user A, go to user B chat
2. Request money to user B
3. Go to the IOU report that got created
4. Make another money request in the IOU report
5. As user B, got to the IOU report that user A created
6. Click on "+" button

## Expected Result:
There should be and option to request money

## Actual Result:
As user B, there is no "Request money" option in the IOU report that user A created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b0d260ff-91b7-487c-a1c4-6fe82f80d3a5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by c3024** [comment] 2023-10-04 15:40
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
User B is not shown "Request Money" option in an IOU report of User A's request for money from B
### What is the root cause of that problem?
Here we remove the current user from the participants
https://github.com/Expensify/App/blob/ab821e5a62121123752440fc2faf31bf0403b487/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L147-L150
For an IOU report created, the `ownerAccountID` is the requestor and the `participantID`s are the requested people.
In this case, for User B, they are the only participant and removing the current user that is user B leaves no participants and this here
https://github.com/Expensify/App/blob/ab821e5a62121123752440fc2faf31bf0403b487/src/libs/ReportUtils.js#L3380-L3386
does not return "Request Money" option
### What changes do you think we should make in order to solve the problem?
We should change this here
https://github.com/Expensify/App/blob/ab821e5a62121123752440fc2faf31bf0403b487/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L148
to something like this
```js
() => _.without([...lodashGet(report, 'participantAccountIDs', []), report?.ownerAccountID], currentUserPersonalDetails.accountID),
```
### What alternative solutions did you explore? (Optional)
<details>
<summary>Result</summary>



</details>

**Comment by mountiny** [comment] 2023-10-04 19:13
This is waiting for backend PR to be deployed https://github.com/Expensify/Auth/pull/8827

**Comment by sophiepintoraetz** [comment] 2023-10-05 04:28
@mountiny - I'm headed OOO from today - I checked the PR and it looks like no reviewer payment is due here. Neither was it reported so I believe there is no BZ action to be taken here? If so, then please can you close or unassign me from this issue?

**Comment by mountiny** [comment] 2023-10-05 15:50
This is now fixed in staging, closing

**Closed by mountiny** 2023-10-05 15:50 UTC
Labels: Reviewing, Daily, Bug
