### ISSUE TITLE
[$250] Distance rates - No error when go online with a new rate set on a secondary device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41911] opened 2024-05-09 13:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/1971179
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: user is logged in on two devices with the same account.
1. On the main testing device, navigate to Workspace settings > More features
2. Enable "Distance rates"
3. Navigate to the Distance rates tab
4. Turn off the internet connection on the device
5. Change the Distance rate to any number
6. Secondary device - navigate to Workspace settings > More features
7. Secondary device - Navigate to the Distance rates tab
8. Change the distance rate
9. On the main testing device - Enable the internet connection

## Expected Result:
There's a message indicating something went wrong and to reload the page and try again.
The changes made on the secondary device are now visible

## Actual Result:
There's no message indicating something went wrong and to reload the page and try again.
The changes made on the main device are sync to secondary device

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2d7e810b-df41-4120-8300-ce4204b0c1d1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bacf55f8fe7777b9</li>
        <li>Upwork Job ID: 1800244868393259428</li>
        <li>Last Price Increase: 2024-07-15</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103153053</li>
<li>dominictb | Contributor | 103153055</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by lanitochka17** [comment] 2024-05-09 13:25
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-09 13:26
We think that this bug might be related to #wave-collect - Release 1

**Comment by slafortune** [comment] 2024-05-15 12:29
Because of the multiple changes, It makes sense that they are not all recognized, and an error is showing.

**Comment by izarutskaya** [comment] 2024-06-05 09:50
This issue is still reproducible 
Build v1.4.79-3
According the steps from TR (https://expensify.testrail.io/index.php?/tests/view/4592925) we expected that there's a message indicating something went wrong and to reload the page and try again.
The changes made on the secondary device now will be visible
TR steps
![Screenshot 2024-06-05 124014](https://github.com/Expensify/App/assets/115492554/650741cf-699e-4812-b4f8-8617de78ae3e)

Actual result
https://github.com/Expensify/App/assets/115492554/20221706-6c89-4b82-8b60-e4851cf89475

**Comment by slafortune** [comment] 2024-06-10 19:13
Thanks for the details @izarutskaya

**Comment by cyberstar9091** [comment] 2024-06-11 00:01
Hi, email me here: cyberstar9091@gmail.com
I want to discuss with you.

**Comment by NJ-2020** [comment] 2024-06-13 00:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No error when go online with a new rate set on a secondary device

### What is the root cause of that problem?
An error message was not added when we reconnected to the internet
https://github.com/Expensify/App/blob/a451de460c45611f64bcd06961afb78b4e2f3c9b/src/pages/workspace/distanceRates/PolicyDistanceRatesPage.tsx#L86
### 

### What changes do you think we should make in order to solve the problem?
We should add an error message when we reconnect it again to the internet either in this function or in a new function
https://github.com/Expensify/App/blob/a451de460c45611f64bcd06961afb78b4e2f3c9b/src/pages/workspace/distanceRates/PolicyDistanceRatesPage.tsx#L70-L72

### What alternative solutions did you explore? (Optional)
N/A

**Comment by eh2077** [comment] 2024-06-13 01:23
Reviewing proposals

**Comment by eh2077** [comment] 2024-06-13 04:23
I agree with @dominictb 's diagnosis. This shouldn't be a bug as it follows our offline-ux design [B - Optimistic WITH Feedback Pattern
](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#b---optimistic-with-feedback-pattern).

If we want to extend the offline-ux design, then I think we can consider @dominictb ‘s suggestion to cooperate client request created timestamp in backend and return reasonable error message to front end. 

🎀👀🎀 C+ reviewed

**Comment by eh2077** [comment] 2024-06-14 17:17
@roryabraham Kindly take a look here https://github.com/Expensify/App/issues/41911#issuecomment-2164342273 when you get a chance, it's most likely not a bug IMO.

**Comment by eh2077** [comment] 2024-06-19 13:32
> @roryabraham Kindly take a look here [#41911 (comment)](https://github.com/Expensify/App/issues/41911#issuecomment-2164342273) when you get a chance, it's most likely not a bug IMO.

Not overdue, same

**Comment by roryabraham** [comment] 2024-06-20 17:22
Sorry for the delay, was OOO for a few days. Overall I agree that this is not a bug - the main device comes back online and the change made offline takes effect, overwriting the earlier change.

This is how the design currently works, and changing it would need to be a broader conversation. It also would be tricky and sometimes lead to unexpected behavior.

In general, you can take many actions offline. However, those actions don't actually "occur" until the client comes back online and the action is processed by the server. For example, if I send a message offline at 9:00am, and come online at 10:00am, the timestamp for that message is expected to be 10:00am,  not 9:00am.

We could potentially change this, but not without a P/S posted in WhatsNext. For now this is expected behavior

**Comment by roryabraham** [comment] 2024-06-20 17:24
hmmm actually I just read the TR - maybe I'm missing something.

**Comment by roryabraham** [comment] 2024-06-20 17:42
I stand [corrected](https://expensify.slack.com/archives/C01GTK53T8Q/p1718904630778779?thread_ts=1718892211.283609&cid=C01GTK53T8Q), this is a legitimate bug. Policy settings changed offline are not expected to supersede changes made by the same (or other) users online.

**Comment by roryabraham** [comment] 2024-06-20 17:43
However, this is a regression. We need to figure out how it _used_ to work, so that we can figure out the simplest way to fix it.

**Comment by roryabraham** [comment] 2024-06-20 17:51
It looks like the front-end is set up to [handle failures](https://github.com/Expensify/App/blob/61255a34a2bd13d0dbecf64d46c87f3d91310154/src/libs/actions/Policy/DistanceRate.ts#L319-L323), so my next step is to figure out where in the back-end we need to throw an error, and how the back-end is supposed to know whether or not an action was taken offline or not

**Comment by roryabraham** [comment] 2024-06-20 17:56
It looks like the back-end logic relies on the `lastModified` field: https://github.com/Expensify/App/blob/b07ed293d1499b82e2b3d7a6a328eb57803c75cd/src/libs/API/parameters/UpdateWorkspaceCustomUnitAndRateParams.ts#L3

**Comment by roryabraham** [comment] 2024-06-20 18:01
Next step - waiting for a proposal using the `lastModified` field for other API commands for changing policy settings beyond just `updateWorkspaceCustomUnitAndRate`. All the `UpdatePolicy$XYZ` API commands should provide this field.

**Comment by eh2077** [comment] 2024-06-21 01:04
@roryabraham Thank you so much for bringing clarity 🫡

@dominictb Can you update your proposal based on @roryabraham 's comment above ^

**Comment by eh2077** [comment] 2024-06-25 09:11
@dominictb Friendly bump

**Comment by eh2077** [comment] 2024-06-30 14:24
@dominictb Friendly bump. Can you update the proposal?

**Comment by eh2077** [comment] 2024-07-01 13:42
@dominictb Are you still keen on updating your proposal based on https://github.com/Expensify/App/issues/41911#issuecomment-2181246408?

**Comment by eh2077** [comment] 2024-07-05 00:08
@dominictb Friendly bump!

**Comment by slafortune** [comment] 2024-07-08 18:21
@dominictb can you please give an update?

**Comment by eh2077** [comment] 2024-07-09 13:58
Waiting for the update from @dominictb !

**Comment by eh2077** [comment] 2024-07-14 13:44
@dominictb Thanks for the update! 

@dominictb 's [proposal](https://github.com/Expensify/App/issues/41911#issuecomment-2162911970) looks good to me!

I think we should skip cases of `delete` operations because deleting a non-existing resource should return a different error message. 

@roryabraham What do you think?

🎀👀🎀 C+ reviewed

**Comment by roryabraham** [comment] 2024-07-17 09:28
> I think we should skip cases of delete operations because deleting a non-existing resource should return a different error message.

agreed, we should skip delete if someone else changed the resource while you were offline

**Comment by roryabraham** [comment] 2024-07-25 19:57
responded in the PR. Hopefully we can push it forward

**Comment by slafortune** [comment] 2024-08-13 20:06
This is waiting on @roryabraham so I don't feel the need to add another BZ person to this.
I'll be out until 8/21 and will check in on this then.

**Comment by slafortune** [comment] 2024-08-23 16:26
@roryabraham can you add some clarity to this question - https://github.com/Expensify/App/pull/45612#issuecomment-2284211883
It sounds like the issue is how quickly the updates were made to the rate on different devices if an error happens or not.

**Comment by slafortune** [comment] 2024-09-18 16:32
a slack discussion was started [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1725311480441339)

**Comment by roryabraham** [comment] 2024-10-04 23:27
Going on parental leave, reassigning to @neil-marcellini as someone who knows a good bit about distance requests. Thanks in advance @neil-marcellini!

**Comment by slafortune** [comment] 2024-10-14 17:01
Retested and have confirmed the issue still stands

**Comment by neil-marcellini** [comment] 2024-10-30 18:34
Going back to the original bug report, I don't think this is a valid bug. I mentioned that [in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1730313210719269?thread_ts=1725311480.441339&cid=C01GTK53T8Q), so let's discuss there.

**Comment by neil-marcellini** [comment] 2024-10-30 18:43
We decided this is not a real problem, it's working as intended, so closing it out. I'm sorry we didn't catch it sooner. Please let me know if there's some other valid bug related to this.

**Closed by neil-marcellini** 2024-10-30 18:43 UTC
Labels: External, Weekly, Bug

**Comment by eh2077** [comment] 2024-10-31 02:23
@neil-marcellini Thanks for looking into this issue and making the decision! 

@slafortune May I know if we are eligible for any payment, given that we have done some work in the closed PR? https://github.com/Expensify/App/pull/45612

**Comment by eh2077** [comment] 2025-02-04 15:08
Hi @slafortune, may I know if @dominictb and I are eligible for some compensation, given that we have done some work in the closed PR https://github.com/Expensify/App/pull/45612? Thank you!

cc @roryabraham as you have followed this issue before your leave 🙏

**Comment by slafortune** [comment] 2025-02-20 15:38
Thank you so much for the bumps and links!!!  I really do appreciate it - sorry for the delay

@dominictb offer sent here - https://www.upwork.com/nx/wm/offer/106208037
@eh2077 offer sent here - https://www.upwork.com/nx/wm/offer/106208061

**Comment by slafortune** [comment] 2025-02-20 16:00
@eh2077 since you were assigned prior to 8/24/24 this should be paid via Upworks, is that correct?

**Comment by eh2077** [comment] 2025-02-20 16:04
> [@eh2077](https://github.com/eh2077) since you were assigned prior to 8/24/24 this should be paid via Upworks, is that correct?

Oh, I see that makes sense! Upwork offer accepted, thank you

**Comment by slafortune** [comment] 2025-02-21 19:23
Paid 🎉
