### ISSUE TITLE
[$1000] Deeplink - No prompt to open in app when navigating to deep link as logged-out web user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25790] opened 2023-08-23 16:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/24638
## Action Performed:
1. Go to staging.new.expensify.com
2. As signed in user on web, copy code to room and paste it on web browser and navigate to the link
3. As signed out user on web, repeat Step 2

## Expected Result:
Whether user is signed in or signed out on web browser, navigate to new expensify deeplink on web should show a prompt to open ND in app

## Actual Result:
When user is signed out on web and navigates to deep link, there is no prompt to open in desktop app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.56-18

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f2ea9918-aaf4-40d1-a544-8d3e756f44bd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f534d2e9aa904030</li>
        <li>Upwork Job ID: 1694458731220623360</li>
        <li>Last Price Increase: 2023-08-30</li>
    </ul>
</details>

**Comment by yuwenmemon** [comment] 2023-08-23 18:58
I QA'd https://github.com/Expensify/App/pull/24638 - it worked fine and I don't believe what we're seeing here is a deploy blocker. I'm going to reassign this to the bug zero team for triage.

**Comment by joekaufmanexpensify** [comment] 2023-08-23 21:16
Confirmed this works right now on production when signed in or out. It's only on staging that we don't prompt to open the desktop app when deeplinking while signed out.

**Comment by ArekChr** [comment] 2023-08-24 10:10
@joekaufmanexpensify @yuwenmemon Can we close this issue then?

**Comment by joekaufmanexpensify** [comment] 2023-08-24 18:04
@ArekChr I would think we wouldn't want to close this, no? It seems like a bug that we're not triggering the desktop prompt when logged out on staging.

**Comment by ArekChr** [comment] 2023-08-25 06:53
Sure, I thought that was intentional.

**Comment by napster125** [comment] 2023-08-25 09:54
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When a user is signed out on the web and attempts to navigate to a deep link, there is no prompt to open the link in the desktop app.

### What is the root cause of that problem?
The root cause of this problem is that we are not handling deep links when users are logged out.
You can find the relevant code snippet here:
https://github.com/Expensify/App/blob/34d4e54055c3fee2a04e2fc11af82fe454197ff9/src/components/DeeplinkWrapper/index.website.js#L78-L94

### What changes do you think we should make in order to solve the problem?
To address this issue, I recommend the following changes:

- Update Conditional Expression
We need to modify the code by removing the conditional expression that checks for `isAuthenticated === false`. Since the existing `else` statement implies that `isAuthenticated` is `false`, the conditional is unnecessary.

https://github.com/Expensify/App/blob/34d4e54055c3fee2a04e2fc11af82fe454197ff9/src/components/DeeplinkWrapper/index.website.js#L83

- Adjust Denylist for Opening Desktop App
We need to modify the code by either removing `HOME` from the `DEEPLINK_PROMPT_DENYLIST`, or by incorporating the condition `navigationRef.current.getState().routes.length === 1`. This indicates that these changes are specifically related to the `DEEPLINK` and do not affect `HOME`. This condition establishes that if the route length is greater than 1, it signifies a deep link; otherwise, it is not a deep link. These changes are aimed at enabling the desktop app to show a prompt for opening when a user, logged out on the web, navigates to a deep link.

https://github.com/Expensify/App/blob/34d4e54055c3fee2a04e2fc11af82fe454197ff9/src/components/DeeplinkWrapper/index.website.js#L87-L88

https://github.com/Expensify/App/blob/34d4e54055c3fee2a04e2fc11af82fe454197ff9/src/CONST.js#L444

- Modification of Conditional Code Block Adjust the code as follows:
```
if (currentScreen === undefined) {
  return;
}

const preventPrompt = shouldPreventDeeplinkPrompt(currentScreen);

// navigationRef.current is not null as currentScreen is not undefined. Therefore, we can utilize navigationRef.current.
if (preventPrompt === true && navigationRef.current.getState().routes.length === 1) {
  return;
}
```
This modification ensures proper handling of the prompt prevention based on the conditions mentioned.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by pradeepmdk** [comment] 2023-08-25 11:59
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
No prompt to open in app when navigating to deep link as logged-out web user

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/34d4e54055c3fee2a04e2fc11af82fe454197ff9/src/components/DeeplinkWrapper/index.website.js#L83
https://github.com/Expensify/App/blob/34d4e54055c3fee2a04e2fc11af82fe454197ff9/src/components/DeeplinkWrapper/index.website.js#L52
Both places we are blocking for non-auth people

### What changes do you think we should make in order to solve the problem?

we should remove `isAuthenticated === false` both places and 
we should remove ` SCREENS.HOME` as well because  SCREENS.HOME is a root path for  this allow the path
```
 const preventPrompt = shouldPreventDeeplinkPrompt(currentScreen); 
``` 
and 
we should update 
https://github.com/Expensify/App/blob/34d4e54055c3fee2a04e2fc11af82fe454197ff9/src/components/DeeplinkWrapper/index.website.js#L52 
```javascript
    + if (!hasShownPrompt) { // update this one
   - setHasShownPrompt(false); and remove this
            Navigation.isNavigationReady().then(() => {
                // Get initial route
                const initialRoute = navigationRef.current.getCurrentRoute();
                setCurrentScreen(initialRoute.name);

                removeListener.current = navigationRef.current.addListener('state', (event) => {
                    setCurrentScreen(Navigation.getRouteNameFromStateEvent(event));
                });
            });
        }
``` 
https://github.com/Expensify/App/blob/34d4e54055c3fee2a04e2fc11af82fe454197ff9/src/components/DeeplinkWrapper/index.website.js#L64
because when ever `hasShownPrompt` changes and `isAuthenticated === false` means it will update again `hasShownPrompt` as false and again it will ask the popup to open desktop so it will  goes to loop.

**Comment by joekaufmanexpensify** [comment] 2023-08-25 20:51
>Sure, I thought that was intentional.

@ArekChr did you see discussion that said this somewhere? The reason I thought this was not intentional is that when [I was testing it](https://github.com/Expensify/App/issues/25790#issuecomment-1690651270) the other day, we were not showing the "switch to desktop" prompt to non-authenticated users on staging, but we were on production. 

That inconsistency made me think this was likely a regression introduced at recently (unless we made the active decision to change this somewhere).

**Comment by joekaufmanexpensify** [comment] 2023-08-29 20:24
@ArekChr mind sharing your thoughts [on this](https://github.com/Expensify/App/issues/25790#issuecomment-1693916234) when you have a sec?

**Comment by ArekChr** [comment] 2023-08-31 07:32
@joekaufmanexpensify It Looks like this functionality is intended. There were discussions about not prompting redirects when users are logged out on the web app, a related thread [here](https://github.com/Expensify/App/pull/23673#discussion_r1310591279)
cc: @cdanwards

**Comment by joekaufmanexpensify** [comment] 2023-08-31 20:28
Ah cool. Yep, confirmed [here. ](https://expensify.slack.com/archives/C01GTK53T8Q/p1683074274469839?thread_ts=1683070404.415199&cid=C01GTK53T8Q) Closing as this is intended!

**Closed by joekaufmanexpensify** 2023-08-31 20:28 UTC
Labels: External, Daily, Help Wanted, Bug
