### ISSUE TITLE
The loading screen uses a dark icon mark against a dark background

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35279] opened 2024-01-27 07:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @grgia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705601141119089

## Action Performed:
1. log in to an account
2. Observe the dark icon mark in the dark background
## Expected Result:
Icon should not display in black
## Actual Result:
The loading screen uses a dark icon mark against a dark background
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2024-01-18 at 8 54 06 AM](https://github.com/Expensify/App/assets/43996225/957b5681-ab6d-41f9-ba59-2b8b74b9d90c)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment] 2024-01-27 11:22
Dupe of this one [here](https://github.com/Expensify/App/issues/35018), so closing!

**Closed by shawnborton** 2024-01-27 11:22 UTC
Labels: Daily, Bug
