### ISSUE TITLE
[$1000] Web -  'Notify me' option doesn't update on Unavailable workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21859] opened 2023-06-29 11:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A
2. Create a new workspace and invite User B and click on the announce channel
3. Login with User B on another web chrome and go to the announce channel
4. Important step- Now close the browser for User B
5. From User A, remove the User B from the workspace (members > remove User B)
6. On user B, open the browser again so that User B is able to see 'Unavailable Workspace' on announce.
7. From user B, go to 'Unavailable workspace' header and click on 'Notify me about messages' and try to select different options from there.
8. Notice that even if you select other options, it switches back to the default option - Daily

## Expected Result:
 If settings can't be changed for unavailable workspace, we can either not show settings OR if we decide to show settings, then it should be updated if the user selects different options

## Actual Result:
'Notify me' option doesn't update on the Unavailable workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e44743c1-2984-4794-bc61-7c4cddadcf59

https://github.com/Expensify/App/assets/93399543/18c0e1d2-d32c-44d8-8f81-646506d1319f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687932409885299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0766bb586cb325f</li>
        <li>Upwork Job ID: 1677141743908093952</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-06-29 13:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
'Notify me' option doesn't update on Unavailable workspace.

### What is the root cause of that problem?
If user is removed from workspace, he can't update workspace notification setting, and server will response "Report no longer exists".
There is no checking whether workspace is available for user or not, and UI doesn't reflect the server response.

### What changes do you think we should make in order to solve the problem?
We can prevent the user from going to workspace details page.
For this, we can add a utility function `isAvailableWorkspace` function in `ReportUtils.js`.

And when user click workspace header, we can check workspace is available using this function in this line.
https://github.com/Expensify/App/blob/f9acca952d03bc8b07be31a49e1e025c574ee4b8/src/pages/home/HeaderView.js#L161
### What alternative solutions did you explore? (Optional)
None.

**Comment by adelekennedy** [comment] 2023-07-07 02:25
moving this along

**Comment by jeet-dhandha** [comment] 2023-07-07 04:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- User still able to see Workspace even when they were removed from the workspace.

### What is the root cause of that problem?
- The user didn't receive the Pusher's event as mentioned by @hungvu193. But still the `shouldReportBeInOptionList` should have handled this case.

### What changes do you think we should make in order to solve the problem?
- First we need to change `canSeeDefaultRoom` and check if Policy for the report is still available or not. If not then we should remove the report (in this case it's room) from the list.
- Second we need to add a check in `canAccessReport` to remove the user created rooms under that workspace too. As currently only the default room is removed.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by sobitneupane** [comment] 2023-07-10 11:12
I agree with @tienifr. It looks like something that should be fixed in backend. @adelekennedy Can we add an internal engineer to see if it can be fixed in backend as suggested [here](https://github.com/Expensify/App/issues/21859#issuecomment-1626858324).

**Comment by adelekennedy** [comment] 2023-07-10 20:27
@NikkiWines question [above](https://github.com/Expensify/App/issues/21859#issuecomment-1628734072) - can thi be fixed on the backend as suggested [here](https://github.com/Expensify/App/issues/21859#issuecomment-1626858324)?

**Comment by adelekennedy** [comment] 2023-07-11 16:43
Let's refocus this - after reproducing I don't think this is a true bug, when we remove someone from the workspace it doesn't matter that they can't update settings. I also wasn't able to reproduce the bug for re-added members 🤷‍♀️ 

I think we should actually close this as we're getting into backend fixes for something pretty insubstantial @NikkiWines @sobitneupane for thoughts

**Comment by NikkiWines** [comment] 2023-07-12 01:21
Yep, agreed - not saving user notification preferences for a workspace they don't have access to any longer sounds like expected behavior to me

**Comment by sobitneupane** [comment] 2023-07-12 04:22
IMO, those rooms from where user is removed should not be shown at all. It was the behavior previously and even now if user is removed when he/she is online, those rooms are not visible to the removed user. 

According to @tienifr (https://github.com/Expensify/App/issues/21859#issuecomment-1626858324)

>This problem doesn't happen before, that's because earlier the OpenApp API is called whenever we load the page again. This will populate all the policies and reports data, and will not show stale data.
>
>However, after https://github.com/Expensify/App/pull/18807, we no longer call OpenApp on page load for performance reason (because OpenApp fetches all the data so it's slow), we only call ReconnectApp if the user was already logged in before.
>
>After the user is removed from the workspace and the user loads the page, the ReconnectApp only sends back "set workspace to null", not "set reports and reportActions related to this workspace to null" (as the Pusher will send if the user opens the app at the time).

**Comment by NikkiWines** [comment] 2023-07-12 23:32
If it's a regression from previous behavior (i.e. we used to not show the rooms but now we do) that sounds like an issue, and should be reported separately if it hasn't been already. But I don't think this issue as it was [reported](https://expensify.slack.com/archives/C049HHMV9SM/p1687932409885299) is a real bug

**Comment by adelekennedy** [comment] 2023-07-13 17:41
Agree - I think we should open a separate issue and deal with the regression!

**Comment by NikkiWines** [comment] 2023-07-13 21:54
Cool, in that case, I'm going to close this out. Thanks everyone 🙇

**Closed by NikkiWines** 2023-07-13 21:54 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by NikkiWines** [comment] 2023-07-14 23:13
@tienifr I personally think it should be a separately reported issue
