### ISSUE TITLE
[$250] Sign in – Account settings page open when login with a new account using magic code

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47055] opened 2024-08-08 10:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4834070
**Email or phone of affected tester (no customers):** applausetester+jp_78824category@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. In Sign in page enter new Expensify email
3. Open email and copy Magic code
4. In Sign in page paste Magic code

## Expected Result:
Inbox page opens

## Actual Result:
Account settings page open

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/295259d1-6598-49b4-bf01-c6bc7983a38b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112e69610b7f6b0df</li>
        <li>Upwork Job ID: 1821565963664006644</li>
        <li>Last Price Increase: 2024-08-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by IuliiaHerets** [comment] 2024-08-08 10:30
We think that this bug might be related to #vip-vsb

**Comment by nkuoch** [comment] 2024-08-08 14:47
Tried with a gmail account and didn't have the bug. Reproduced the bug with an expensifail.com one, so linked to a beta

**Comment by nkuoch** [comment] 2024-08-08 15:09
So, removing DeployBlocker, but this should be worked on!

**Comment by hungvu193** [comment] 2024-08-13 02:12
Seems it was fixed here: https://github.com/Expensify/App/pull/47099

**Comment by hungvu193** [comment] 2024-08-16 03:36
Not overdue, asking for retest cc @JmillsExpensify

**Comment by hungvu193** [comment] 2024-08-20 01:58
Not overdue

**Comment by JmillsExpensify** [comment] 2024-08-20 14:31
Asked for a retest.

**Comment by JmillsExpensify** [comment] 2024-08-20 14:32
Also filing this one in #wave-control since that is where the homepage is being worked on.

**Comment by m-natarajan** [comment] 2024-08-20 15:05
Unable to reproduce now. 

https://github.com/user-attachments/assets/ec2cdcbd-2fae-4932-b6ed-7ab50059b8b3

**Comment by JmillsExpensify** [comment] 2024-08-20 16:47
Closing based on the above.

**Closed by JmillsExpensify** 2024-08-20 16:47 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
