### ISSUE TITLE
[HOLD on 43397][$250] Android - QBO - Other integrations section blinks

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44264] opened 2024-06-24 14:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4666345&group_by=cases:section_id&group_order=asc&group_id=309135
**Email or phone of affected tester (no customers):** applausetester+qbo@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. User should have connected QBO
2. Login with [applausetester+qbo@applause.expensifail.com](mailto:applausetester+qbo@applause.expensifail.com)
3. Go to Workspace> Accounting
4. Tap on Other integrations

## Expected Result:
Other integrations section should be stable and should not blink

## Actual Result:
Other integrations section blinks

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fcc0792b-1a39-4f69-8a4a-57dc64ff652a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016262988a225be2e3</li>
        <li>Upwork Job ID: 1808166912556054758</li>
        <li>Last Price Increase: 2024-07-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment] 2024-06-24 14:23
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by huult** [comment] 2024-07-06 17:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Other integrations section blinks

### What is the root cause of that problem?

This issue is from [react-native-collapsible](https://github.com/oblador/react-native-collapsible), and some users have reported it in [this issue](https://github.com/oblador/react-native-collapsible/issues/473).

### What changes do you think we should make in order to solve the problem?

This issue has the same root cause analysis (RCA) as [this issue](https://github.com/Expensify/App/issues/43397). A contributor has [proposed a solution](https://github.com/Expensify/App/issues/43397#issuecomment-2159823409) for it, and I saw they have created a [pull request](https://github.com/oblador/react-native-collapsible/pull/475) for react-native-collapsible to fix it. So please wait for the new version of react-native-collapsible to upgrade the package, or use the alternative solution provided by [truph01](https://github.com/Expensify/App/issues/43397#issuecomment-2159823409).

### What alternative solutions did you explore? (Optional)

**Comment by miljakljajic** [comment] 2024-09-20 12:50
I am heading out on parental leave so assigning another BZ team member to manage this when it comes off hold

**Comment by lschurr** [comment] 2024-09-20 21:55
Shoot, sorry - I am actually out from 9/23-10/4 so I need to reassign this one again.

**Comment by slafortune** [comment] 2024-09-23 15:43
Adding the retest tag

**Comment by slafortune** [comment] 2024-10-09 16:37
no longer able to recreate - closing

**Closed by slafortune** 2024-10-09 16:37 UTC
Labels: External, Weekly, Help Wanted, Bug, retest-weekly
