### ISSUE TITLE
Room - Unnecessary "Are you sure?" Modal for Public Rooms

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46900] opened 2024-08-06 15:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open chat via FAB
2. Switch to a room and add a room name
3. Set room visibility to public
4. Go to the room, click the header, then Settings > Visibility
5. Notice public is selected, then click on it again

## Expected Result:
The modal should not appear when re-selecting public visibility

## Actual Result:
The "Are you sure? Anyone can find this room" modal appears even though public visibility is already selected. This modal should only appear when changing from a different visibility setting

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8d5c3e51-2ff4-473d-a3ac-23f4baf0c8fd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-06 15:43
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-06 15:44
We think that this bug might be related to #vip-vsp

**Comment by etCoderDysto** [comment] 2024-08-06 15:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unnecessary "Are you sure?" Modal for Public Rooms
### What is the root cause of that problem?
We are only checking if the selection option has a public room value
https://github.com/Expensify/App/blob/69476a124a8609f451a44ed173c20135c9e3dd4b/src/pages/settings/Report/VisibilityPage.tsx#L72-L73
### What changes do you think we should make in order to solve the problem?
We should also check if the selected option is already selected, and display the modal when it is not selected 
```
 if (option.value === CONST.REPORT.VISIBILITY.PUBLIC && !option.isSelected)
 ```
### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-08-06 22:00
The project this is associated with (#vip-vsb), which [is paused](https://expensify.slack.com/archives/C066HJM2CAZ/p1721684527960509?thread_ts=1721683272.509669&cid=C066HJM2CAZ). 

Further, I don't think this is really an issue/bug. In an ideal world, maybe this wouldn't be there, but we generally allow selecting the current selected option in a menu, and in this case that option comes with a warning modal, so I think it's fine that we show that if you select it again. 

Going to close this for now, LMK if anyone disagrees.

**Closed by joekaufmanexpensify** 2024-08-06 22:00 UTC
Labels: Daily, Bug
