### ISSUE TITLE
[$250][P2P Distance] - Disabled rate is not listed in the Rate list when it is still selected

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46884] opened 2024-08-06 13:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.17-0
**Reproducible in staging?:** y
**Reproducible in production?:** no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):** applausetester+kh050801@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace has some distance rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a distance expense with Distance rate A.
4. Go to workspace settings > Distance rates.
5. Disable Distance rate A used in Step 3.
6. Go back to transaction thread of the distance expense.
7. Click Rate.
## Expected Result:
The disabled rate will appear selected in the Rate list but grayed out (like Category and Tag when selected and disabled afterward).

## Actual Result:
The disabled rate is not listed in the Rate list when it is still selected.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7a2b9e90-faa2-460a-abfb-0f5ce5ef5f00

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01113b3b52e50f7f4e</li>
        <li>Upwork Job ID: 1821117740687763365</li>
        <li>Last Price Increase: 2024-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103608790</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by BhuvaneshPatil** [comment] 2024-08-06 13:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance rate which is selected but after disabling, not shown.

### What is the root cause of that problem?
We are filtering the disabled rates when showing the rates list in selector.
https://github.com/Expensify/App/blob/627ef1a982350287aaf79e5c08c5f25a7033187a/src/libs/DistanceRequestUtils.ts#L47-L50

https://github.com/Expensify/App/blob/627ef1a982350287aaf79e5c08c5f25a7033187a/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L141-L144

### What changes do you think we should make in order to solve the problem?

We shall pass true as second argument that will give us disabled rates as well and we will also pass enabled value.
https://github.com/Expensify/App/blob/627ef1a982350287aaf79e5c08c5f25a7033187a/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L141-L144

Once that is done - 
we can filter the disabled rate in `IOURequestStepDistanceRate` as following. and pass isDisabled value so it will show selected but style will be different for selected but disabled value.

```ts
    const sections = Object.values(rates).filter(rate => {
        const isSelected = currentRateID ? currentRateID === rate.customUnitRateID : rate.name === CONST.CUSTOM_UNITS.DEFAULT_RATE
        return isSelected || rate?.enabled
    }).map((rate) => {
        const rateForDisplay = DistanceRequestUtils.getRateForDisplay(rate.unit, rate.rate, rate.currency, translate, toLocaleDigit);
        return {
            text: rate.name ?? rateForDisplay,
            alternateText: rate.name ? rateForDisplay : '',
            keyForList: rate.customUnitRateID,
            value: rate.customUnitRateID,
            isSelected: currentRateID ? currentRateID === rate.customUnitRateID : rate.name === CONST.CUSTOM_UNITS.DEFAULT_RATE,
            isDisabled: !rate.enabled
        };
    });
```

### What alternative solutions did you explore? (Optional)

**Comment by neil-marcellini** [comment] 2024-08-06 17:50
Not a blocker, the rate field is still behind the beta.

![image](https://github.com/user-attachments/assets/9a2ea040-8bc7-45b7-a713-8b4bd53126f2)

**Comment by BhuvaneshPatil** [comment] 2024-08-06 18:21
@neil-marcellini Are we planning to make it external?

**Comment by dylanexpensify** [comment] 2024-08-07 09:35
made external

**Comment by mananjadhav** [comment] 2024-08-14 17:22
I'll review the proposals by tomorrow. I was OOO.

**Comment by iwiznia** [comment] 2024-08-20 12:29
@mananjadhav are you available or should we reassign this issue?

**Comment by mananjadhav** [comment] 2024-08-20 12:30
I'll have this reviewed today.

**Comment by mananjadhav** [comment] 2024-08-20 17:48
I was a little confused with the `selectedRateID` in this [proposal](https://github.com/Expensify/App/issues/46884#issuecomment-2272043244). But after reviewing it thoroughly I understand now. Both the proposals identify the correct root cause, but I think it's best to use [this proposal ](https://github.com/Expensify/App/issues/46884#issuecomment-2272043244) by @dominictb. It involves cleaning up the existing code as well.

**Comment by mananjadhav** [comment] 2024-08-20 17:48
I was a little confused with the `selectedRateID` in this [proposal](https://github.com/Expensify/App/issues/46884#issuecomment-2272043244). But after reviewing it thoroughly I understand now. Both the proposals identify the correct root cause, but I think it's best to use [this proposal ](https://github.com/Expensify/App/issues/46884#issuecomment-2272043244) by @dominictb. It involves cleaning up the existing code as well.


🎀 👀 🎀

**Comment by iwiznia** [comment] 2024-08-20 18:34
@dominictb a couple questions:

> Remove this: ... because it is redundant and use:

Don't we need that there? Otherwise this component will not update if onyx data changes, no?

> Finally, return additional prop isDisabled: !rate.enabled in:

Why are we transforming `enabled` to `isDisabled`? Why not keep `enabled`?

**Comment by BhuvaneshPatil** [comment] 2024-08-20 18:45
Yes, I agree with @iwiznia points here.

1. I am not sure if we should modify `getMileageRates()` method, because it's being used at multiple places.
2. For unit, we use what is being used in workspace not individual rate. Can you please confirm that.

https://github.com/Expensify/App/blob/72c8cf7679f2ce80e39e8fd14c55bc48b5f80937/src/libs/DistanceRequestUtils.ts#L42-L61

3. And for `calculateTaxAmount()` we use particular tax rate.

**Comment by BhuvaneshPatil** [comment] 2024-08-20 19:06
Also in selected proposal, root cause is not correct. 

We are not passing disabled values to component and the RCA mentions about the logic for creating list items.

**Comment by iwiznia** [comment] 2024-08-20 19:11
> I think we already had the policy data is always up-to-date here:

Ohhhhh, ok yeah, looking at those now I agree it is not needed

> We only have a logic to gray out the option if it has isDisabled is true. So if need to convert enabled to isDisabled.

Got it, makes sense

**Comment by iwiznia** [comment] 2024-08-20 19:13
> I am not sure if we should modify getMileageRates() method, because it's being used at multiple places.

Like where? I'd think most places it is being used needs this logic and the ones that do not, can just not pass a selected value and the behavior would stay the same as now, no?

> or unit, we use what is being used in workspace not individual rate
> And for calculateTaxAmount() we use particular tax rate. Meaning when we click on option then only that's triggered.

Not sure what you mean here

**Comment by mananjadhav** [comment] 2024-08-20 19:19
Checking recent comments.

**Comment by mananjadhav** [comment] 2024-08-20 19:28
I don't think any of the existing calls should break. We can even set that as optional param. I don't think we're modifying anything for `calculateTaxAmount` or unit. We're only ensuring it works as before. Still feel we should go with the shortlisted proposal.

**Comment by BhuvaneshPatil** [comment] 2024-08-20 19:28
about RCA?

**Comment by dylanexpensify** [comment] 2024-09-10 19:59
pending regression period

**Comment by iwiznia** [comment] 2024-09-25 17:55
FYI you can check yourself by looking at the production branch. I think it was since I see your changes [here](https://github.com/Expensify/App/blob/production/src/libs/DistanceRequestUtils.ts#L49)

**Comment by mananjadhav** [comment] 2024-09-25 18:17
Okay I should've clarified. I did see the changes in the production branch, I am not sure what would be the payout date.

**Comment by iwiznia** [comment] 2024-09-25 18:24
hmmm yeah, I am not sure. Maybe you can find the merge commit in the production branch?

**Comment by mananjadhav** [comment] 2024-09-26 16:09
Correct me if I am wrong but we can use this release link to confirm this was deployed 2 weeks ago - https://github.com/Expensify/App/releases/tag/9.0.31-26 

@dylanexpensify as for the checklist I think this was more of an edge case and hence I don't have a PR that I can pinpoint to.

But I do feel we should add a regression test for this one. 

**Regression Test Proposal**

1. Precondition: Workspace has some distance rates. 
2. Go to NewDot app 
3. Go to workspace chat. 
4. Submit a distance expense with Distance rate A. 
5. Go to workspace settings > Distance rates. 
6. Disable Distance rate A used in Step 3. 
7. Go back to transaction thread of the distance expense. 
8. Click Rate.
9. Verify that: The disabled rate will appear selected in the rate list but grayed out.

**Comment by dylanexpensify** [comment] 2024-09-26 17:34
Payment summary:

Contributor: @dominictb $250 via Upwork
Contributor+: @mananjadhav $250 via NewDot

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-09-26 17:37
payment sent in upwork @dominictb!

**Closed** 2024-09-26 17:37 UTC
Labels: Reviewing, External, Engineering, Monthly, Bug

**Comment by garrettmknight** [comment] 2024-10-02 16:53
$250 approved for @mananjadhav
