### ISSUE TITLE
[$500] #focus mode - Subscribing to thread from the same message 30 times trigger #focus modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32720] opened 2023-12-08 14:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account
3. Initiate a chat and send a message
4. Right click on the message > Unsubscribe from thread
5. Right click on the message > Subscribe from thread
6. Repeat Step 4 30 times

## Expected Result:
No focus mode modal will pop up because there is less than 30 chats

## Actual Result:
Focus mode modal pops up when there is less than 30 chats
This issue seems to happen when Subscribe to thread button does not change to Unsubscribe from thread after subscribing the thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows : Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/00593134-cd78-446e-acfe-5f9852cb3566

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01999a522faa910e6b</li>
        <li>Upwork Job ID: 1733134040015462400</li>
        <li>Last Price Increase: 2023-12-08</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-12-08 14:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Subscribing to thread from the same message 30 times trigger #focus modal

### What is the root cause of that problem?
It is caused because report record is created and added to `allReports` every time we subscribe (after unsubscribe) the same message. so the code here will trigger the notification
https://github.com/Expensify/App/blob/269e8668c3ced74b6e7fc32b74e4c133fad1df78/src/libs/actions/PriorityMode.ts#L122-L134

### What changes do you think we should make in order to solve the problem?

We should delete the report when the user unsubscribes from the message
### What alternative solutions did you explore? (Optional)

**Comment by burczu** [comment] 2023-12-11 09:47
@isabelastisser It looks like this is BE issue.

**Comment by isabelastisser** [comment] 2023-12-11 18:03
@bernhardoj @burczu, can you please clarify? What is a BE issue? What's recommended as a next step here?

**Comment by burczu** [comment] 2023-12-12 09:04
@isabelastisser I think it's well explained in the @FitseTLT's proposal.

**Comment by Beamanator** [comment] 2023-12-13 13:01
Reading the bug report again, this seems like a super low value bug, what do you think @isabelastisser ? If this is only reproducible when clicking subscribe / unsubscribe 30 times 🤷 I think we should make this a monthly

**Comment by isabelastisser** [comment] 2023-12-14 19:23
@Beamanator based on the comment above, it seems like this will be fixed with https://github.com/Expensify/App/issues/32519. So I think we should close this.

**Closed by isabelastisser** 2023-12-14 19:23 UTC
Labels: Engineering, Daily, Internal, Bug
