### ISSUE TITLE
Expense - Leave option doesn't appear on invitee to a IOU thread

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49529] opened 2024-09-20 11:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4986423
**Email or phone of affected tester (no customers):** gatantm+166@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. In a 1:1 conversation between 2 users - Send 2 IOUs
2. In the report conversation mention a external user (invitee)
3. In the actionable whisper, select to invite the user
4. Copy the report URL and send it to the Invitee
5. Login as the invitee
6. Navigate to the report URL and open the header

## Expected Result:
The options to share, pin/unpin, and leave are displayed in the conversation details

## Actual Result:
The option to leave is only displayed after leaving a message to one of the threads and only on the IOU

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b9119bf2-40ae-4606-8c94-e32e24859dcf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-20 11:55
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CyberAndrii** [comment] 2024-09-20 12:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Leave option doesn't appear on invitee to a IOU thread

### What is the root cause of that problem?

BE sets notification preference to `CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN`. This causes the `ReportUtils.canLeaveChat` function to return false.

https://github.com/Expensify/App/blob/d009d8ed4830c7d0562c524c991b8a688e2b4869/src/pages/ReportDetailsPage.tsx#L249

https://github.com/Expensify/App/blob/d009d8ed4830c7d0562c524c991b8a688e2b4869/src/libs/ReportUtils.ts#L7547-L7549

### What changes do you think we should make in order to solve the problem?

Add `true` as an argument to the `getReportNotificationPreference` function. It will use `CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS` as a default value
 
https://github.com/Expensify/App/blob/d009d8ed4830c7d0562c524c991b8a688e2b4869/src/libs/ReportUtils.ts#L7547-L7549

```diff
-    if (getReportNotificationPreference(report) === CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN) {
+    if (getReportNotificationPreference(report, true) === CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN) {
```

**Comment by CyberAndrii** [comment] 2024-09-20 12:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Leave option doesn't appear on invitee to a IOU thread

### What is the root cause of that problem?

BE sets notification preference to `CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN`. This causes the `ReportUtils.canLeaveChat` function to return false.

https://github.com/Expensify/App/blob/d009d8ed4830c7d0562c524c991b8a688e2b4869/src/pages/ReportDetailsPage.tsx#L249

https://github.com/Expensify/App/blob/d009d8ed4830c7d0562c524c991b8a688e2b4869/src/libs/ReportUtils.ts#L7547-L7549

### What changes do you think we should make in order to solve the problem?

Pass `false` to the `shouldDefaltToHidden` parameter in the `getReportNotificationPreference` function. It will use `CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS` as a default value
 
https://github.com/Expensify/App/blob/d009d8ed4830c7d0562c524c991b8a688e2b4869/src/libs/ReportUtils.ts#L7547-L7549

```diff
-    if (getReportNotificationPreference(report) === CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN) {
+    if (getReportNotificationPreference(report, false) === CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN) {
```

https://github.com/Expensify/App/blob/d009d8ed4830c7d0562c524c991b8a688e2b4869/src/libs/ReportUtils.ts#L1172-L1177

**Comment by CyberAndrii** [comment] 2024-09-20 13:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Leave option doesn't appear on invitee to a IOU thread

### What is the root cause of that problem?

The BE sets the notification preference to `CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN`, which causes the `ReportUtils.canLeaveChat` function to return false.

https://github.com/Expensify/App/blob/d009d8ed4830c7d0562c524c991b8a688e2b4869/src/pages/ReportDetailsPage.tsx#L249

https://github.com/Expensify/App/blob/d009d8ed4830c7d0562c524c991b8a688e2b4869/src/libs/ReportUtils.ts#L7547-L7549

This check was accidentally added in https://github.com/Expensify/App/pull/40529. Prior to this PR, the notification preference was not being checked: https://github.com/Expensify/App/pull/40529/files#diff-a85e40561837eb28d893b4b0087cb33a3f772ff4b3e082036ac882d74c545452L160-L162

After: https://github.com/Expensify/App/pull/40529/files#diff-577fcc5f3a5e4930916ff310e61c38edfa093792fe3ab55b9a30d2aecd8811dbR6480-R6482

### What changes do you think we should make in order to solve the problem?

Remove the following lines
 
https://github.com/Expensify/App/blob/d009d8ed4830c7d0562c524c991b8a688e2b4869/src/libs/ReportUtils.ts#L7547-L7549

**Comment by joekaufmanexpensify** [comment] 2024-09-20 20:25
@IuliiaHerets could you share why you think this is a bug? It doesn't seem like one to me. Before you send a reply on the IOU thread, it's just a message in the parent chat room (rather than a thread in its own right that you can join/leave). So it makes sense to me that we add the leave button once the IOU message has a reply, as that's when it becomes a thread of it's own.

**Comment by joekaufmanexpensify** [comment] 2024-09-20 20:26
Closing for now as I think this is expected behavior.

**Closed by joekaufmanexpensify** 2024-09-20 20:26 UTC
Labels: Daily, Bug
