### ISSUE TITLE
[$250] Chat - Size of text cursor is smaller when returning to any chat via browser back button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39303] opened 2024-03-29 21:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Create a group chat
4. Split bill in the group chat
5. Click on the split preview > Click any split member > Click Message <user>
6. In 1:1 DM, click on the IOU preview
7. Click on the header subtitle to return to 1:1 DM
8. Click browser back button until app returns to the group chat in Step 3

## Expected Result:
The size of text cursor will remain the same when returning to group chat via browser back button

## Actual Result:
The size of text cursor is smaller when returning to group chat via browser back button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/04307fb8-cb63-4e23-b779-80bf212633d1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e868dd4a424eb130</li>
        <li>Upwork Job ID: 1776300146755960832</li>
        <li>Last Price Increase: 2024-04-05</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-29 21:59
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-03-29 21:59
@marcaaron  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcaaron** [comment] 2024-03-29 22:36
Seems possibly more related to markdown changes.

**Comment by marcaaron** [comment] 2024-03-29 22:37
@thienlnam I asked for a re-test to see. It kinda feels like this would be broken everywhere (sorry if I end up wrong on that hunch).

**Comment by thienlnam** [comment] 2024-03-29 22:43
Definitely possible - I'll add it to the main tracking list. But seems pretty harmless and I don't think needs to be a blocker

**Comment by marcaaron** [comment] 2024-03-29 22:44
Cool. If you are not passionate about it. Then I'm gonna pop the label off.

**Comment by marcaaron** [comment] 2024-04-01 17:25
p.s. confirmed with QA that this is not limited to Group Chats.

**Comment by thienlnam** [comment] 2024-04-05 17:25
Opening this to external contributors!

**Comment by nkdengineer** [comment] 2024-04-06 10:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The size of text cursor is smaller when returning to group chat via browser back button

### What is the root cause of that problem?
In [here](https://github.com/Expensify/react-native-live-markdown/blob/c7595572ff4f2a4b8c95a6110a05de62b2d8dbe4/src/MarkdownTextInput.web.tsx#L120), we didn't check if the height is positive before returning the value. The `height` could be 0 if the parent element was not fully rendered in the DOM yet.

So on layout change, when we use the method to get the element height [here](https://github.com/Expensify/react-native-live-markdown/blob/c7595572ff4f2a4b8c95a6110a05de62b2d8dbe4/src/MarkdownTextInput.web.tsx#L524) to use as `maxHeight`, we're getting `0` as the height when returning to the chat via browser back button (and the composer container was not fully rendered in DOM yet), leading to the input height becomes very small and the cursor size is small.

### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/react-native-live-markdown/blob/c7595572ff4f2a4b8c95a6110a05de62b2d8dbe4/src/MarkdownTextInput.web.tsx#L120), if the height is 0, we should return `auto` as the height. So in the next layout effect trigger, when the composer container has been rendered in DOM, it will have positive `height` and will show in the UI correctly.
```
if (!height) {
  return 'auto';
}
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by BartoszGrajdek** [comment] 2024-04-09 07:40
I'll take a look at it later today! 👀

**Comment by BartoszGrajdek** [comment] 2024-04-09 12:35
Makes sense to me! 🙌🏻

**Comment by BartoszGrajdek** [comment] 2024-04-09 12:37
If @paultsimura decides to go with your proposal @nkdengineer you can make a PR directly to `react-native-live-markdown` and we'll try pushing it forward 👀

**Comment by nkdengineer** [comment] 2024-04-11 08:53
@BartoszGrajdek  @paultsimura this [PR](https://github.com/Expensify/react-native-live-markdown/pull/283) is ready for preview.

**Comment by dylanexpensify** [comment] 2024-04-12 19:38
PR is merged Mel! Waiting for payment day

**Comment by dylanexpensify** [comment] 2024-04-15 10:34
Ah nice, thanks @paultsimura! 👍

**Comment by nkdengineer** [comment] 2024-04-15 10:44
@paultsimura this [PR](https://github.com/Expensify/App/pull/40228) is ready for preview.

**Comment by dylanexpensify** [comment] 2024-04-29 10:54
Payment summary:
- Contributor: @nkdengineer $250
- Contributor+: @paultsimura $250

Please apply or request!

**Comment by thienlnam** [comment] 2024-05-13 19:04
We don't close issues until we get them paid out - but we can remove this from the tracking issue

**Comment by dylanexpensify** [comment] 2024-05-14 09:46
bump @nkdengineer!

**Comment by nkdengineer** [comment] 2024-05-14 09:59
Hi @dylanexpensify, sorry for the delay, I've applied to the job https://www.upwork.com/jobs/~01e868dd4a424eb130

**Comment by dylanexpensify** [comment] 2024-05-21 18:21
offer sent!

**Comment by dylanexpensify** [comment] 2024-05-27 17:11
Ah, thanks for the catch, agree. Updated offer, and will pay out $500 in Upwork

**Comment by dylanexpensify** [comment] 2024-06-05 09:42
@paultsimura paid last week! But just sent bonus along!

**Comment by dylanexpensify** [comment] 2024-06-05 09:43
@nkdengineer waiting for you to accept offer!

**Comment by nkdengineer** [comment] 2024-06-05 10:14
@dylanexpensify I accepted the offer. But the offer was for $250 so I guess a bonus of $250 will be sent too.

Thanks 🙇

**Comment by dylanexpensify** [comment] 2024-06-17 18:14
Correct! all done btw

**Closed by dylanexpensify** 2024-06-17 18:14 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
