### ISSUE TITLE
[$1000] Inconsistent autolink parsing on parameter with styling characters (underscores and tildes)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18564] opened 2023-05-07 19:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Send this message to a chat : https://example.com/?_parameter_
3. Send this message to a chat : https://example.com/?~parameter~
4. Examine the difference of the parsing

## Expected Result : 
Since tilde is a valid URL character and treated as unreserved characters, just like underscore (https://datatracker.ietf.org/doc/html/rfc3986#section-2.3), parameters with tildes should be treated the same as parameter with underscores, hence tilde should be included in the URL
## Actual Result : 
While URL parameter with underscore parsed correctly and included in the autolink, URL parameter with tildes parsed separatedly and the parameter isn't included in the autolink

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236699999-aa66f5a5-de96-47d0-840e-61ad7541523a.mp4

<img width="955" alt="5" src="https://user-images.githubusercontent.com/43996225/236700007-3f232fae-1d13-4656-a4ba-b08c1a0faf91.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683422758747299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb4a801e2a4e7612</li>
        <li>Upwork Job ID: 1655598377906573312</li>
        <li>Last Price Increase: 2023-05-08</li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2023-05-08 15:26
> Since tilde is a valid URL character and treated as unreserved characters, just like underscore

Wow, TIL

**Comment by s-alves10** [comment] 2023-05-09 10:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Underscores and tildes are parsed differently though they are valid URI characters.

### What is the root cause of that problem?

The main cause of this issue is in its query regex below.

```
const URL_PARAM_REGEX = `(?:\\?${addEscapedChar('[-\\w$@.+!*()\\/,=%{}:;\\[\\]\\|_]')}*)?`;
```

### What changes do you think we should make in order to solve the problem?

We need to update the param regex. Also `\w` includes `_` and there is no needs to include it at the end.
```
const URL_PARAM_REGEX = `(?:\\?${addEscapedChar('[-\\w$@.+!*()\\/,=%{}:;\\[\\]\\|~]')}*)?`;
```

<details>
    <summary>Result</summary>
    
![image](https://github.com/Expensify/App/assets/126839717/a976a5b1-a9fc-438f-a413-69389c0978b1)

https://github.com/Expensify/App/assets/126839717/8ac40eae-1971-4e8b-83fe-2a4ebba7cf6b


</details>

### What alternative solutions did you explore? (Optional)
`{}|` are valid URI characters? I can see that this is the only difference between fragment and query regex. I'ven't found any documents these are valid URI characters. If I was wrong, please kindly include those links here. If not, we should remove them from path query.

**Comment by PauloGasparSv** [comment] 2023-05-10 21:20
LGTM to me too so I've assigned @huzaifa-99 here.

Btw, I think we should implement those optional changes + test to see if they cause any regressions.

**Comment by PauloGasparSv** [comment] 2023-05-16 13:31
The [P.R.](https://github.com/Expensify/expensify-common/pull/533) was merged succesfully. Since these changes were done to [Expensify-common](https://github.com/Expensify/expensify-common/) we still have to update that lib version in NewDot.

Someone else already created [this P.R.](https://github.com/Expensify/App/pull/18994) which includes our changes. I'll ask them to add our Test and QA steps there

**Comment by PauloGasparSv** [comment] 2023-05-19 18:29
[Changes](https://github.com/Expensify/App/pull/18994) are in production! I think we are good to **close** this.

<img width="298" alt="image" src="https://github.com/Expensify/App/assets/6564265/d480e63f-627e-47cf-a5b2-04ac4cc5375d">

@NicMendonca can you help with payment and closing this issue?

**Comment by NicMendonca** [comment] 2023-05-23 08:36
@PauloGasparSv weird, I am not sure why the `hold for payment` title didn't populate

**Comment by NicMendonca** [comment] 2023-05-23 08:37
Going OOO until June 5th so assigning a buddy to issue payment

**Comment by PauloGasparSv** [comment] 2023-05-23 12:40
> @PauloGasparSv Is this eligible for a quick merge bonus?
> 
> Asking since I only created the https://github.com/Expensify/expensify-common/pull/533 but the https://github.com/Expensify/App/pull/18994 that introduced those changes in Expensify/App was done by someone else, tho their work was unrelated but it pulled the latest changes from expensify-common.

I think the compensation will only be based on when https://github.com/Expensify/expensify-common/pull/533 was merged and not https://github.com/Expensify/App/pull/18994 since that comes from another contributor : )
cc @kevinksullivan so you are aware of that too

**Comment by kevinksullivan** [comment] 2023-05-23 19:56
@kerupuksambel @huzaifa-99 @sobitneupane offers sent. Let me know when you accept. Thanks!

**Comment by kevinksullivan** [comment] 2023-05-25 00:31
Correct @huzaifa-99

**Comment by kevinksullivan** [comment] 2023-05-25 00:33
Paid out!

**Comment by kevinksullivan** [comment] 2023-05-25 00:33
@huzaifa-99 upwork is being buggy and not letting my close the contract. Stay tuned on that.

**Closed by kevinksullivan** 2023-05-25 00:33 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by kevinksullivan** [comment] 2023-05-25 21:24
All set @huzaifa-99 !
