### ISSUE TITLE
[$500] Home - Workspace page appears on the right instead of chat view after returning from settings

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36900] opened 2024-02-20 15:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open workspace settings from the bottom.
3. Open profile settings from the top.
4. Go to About > Troubleshoot.
5. Click outside Troubleshoot RHP.
6. Click on the back button on the top left.

## Expected Result:
When returning to home page, the right side will be populated with currently opened chat history.

## Actual Result:
Workspace page appears on the right instead of chat view.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/56448d78-6274-4dc8-a189-199968664503

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018670fb693224f232</li>
        <li>Upwork Job ID: 1759956696756723712</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by situchan** [comment] 2024-02-20 15:06
Another regression from https://github.com/Expensify/App/pull/36309

**Comment by mvtglobally** [comment] 2024-03-05 04:50
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment] 2024-03-05 13:51
Gonna close this issue since it's no longer reproducible.

**Closed by luacmartins** 2024-03-05 13:51 UTC
Labels: Reviewing, External, Engineering, Weekly, Help Wanted
