### ISSUE TITLE
[$500] iOS - Log out - App crashes after creating workspace offline and logging out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28524] opened 2023-09-29 19:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Log in
3. Turn off the internet connection
4. Create a new workspace
5. Log out

## Expected Result:
User is landed on the log in screen

## Actual Result:
The app crashes, the "Uh-oh, something went wrong" screen is dsiplayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/438f6480-8b44-475c-a074-b665173b8cdc

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01358d3bf53e81f6f1</li>
        <li>Upwork Job ID: 1709260403967778816</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-10-01 04:21
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
App crashes after creating workspace offline and logging out

### What is the root cause of that problem?
some time
https://github.com/Expensify/App/blob/main/src/components/LHNOptionsList/OptionRowLHNData.js#L202 
`fullReport` is undefined/null so that `parentReportID` is not accessable.


### What changes do you think we should make in order to solve the problem?

we need to null check here 
https://github.com/Expensify/App/blob/7c86d09a34c4104c8b4885899f29d5ec92d199c3/src/components/LHNOptionsList/OptionRowLHNData.js#L202
https://github.com/Expensify/App/blob/7c86d09a34c4104c8b4885899f29d5ec92d199c3/src/components/LHNOptionsList/OptionRowLHNData.js#L206
https://github.com/Expensify/App/blob/7c86d09a34c4104c8b4885899f29d5ec92d199c3/src/components/LHNOptionsList/OptionRowLHNData.js#L218

**Comment by bfitzexpensify** [comment] 2023-10-03 17:33
Reproduced.

**Comment by bfitzexpensify** [comment] 2023-10-06 18:50
Looks like we have a proposal in https://github.com/Expensify/App/issues/28524#issuecomment-1741952320 ready for review when you get a chance @thesahindia - thank you!

**Comment by bfitzexpensify** [comment] 2023-10-09 23:02
Bump on a review of https://github.com/Expensify/App/issues/28524#issuecomment-1741952320 @thesahindia, thank you!

**Comment by bfitzexpensify** [comment] 2023-10-10 21:35
@lanitochka17 can you still reproduce? We might be able to just close this one out if not

**Comment by bfitzexpensify** [comment] 2023-10-13 00:28
Since I also can't reproduce, I'm going to close this out.

**Closed by bfitzexpensify** 2023-10-13 00:28 UTC
Labels: External, Daily, Help Wanted, Bug
