### ISSUE TITLE
[HOLD for payment 2024-09-26] [$250] [Dupe Detection] Review duplicates - Tag in X: Y format is displayed in X\: Y format in review flow

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47615] opened 2024-08-18 21:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has a tag in X: Y format.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense without tag.
4. Submit another same expense as the previous one, but with tag in X: Y format.
5. Go to transaction thread.
6. Click Review duplicates.
7. Select Keep this one (any).
8. Proceed to tag selection page.

## Expected Result:
Tag in X: Y format will be displayed in X: Y format in review flow.

## Actual Result:
Tag in X: Y format is displayed in X\: Y format in review flow.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3be21d19-b66b-4b37-a877-0a84f7596dd5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176ca0a6294fa423b</li>
        <li>Upwork Job ID: 1826096228342537444</li>
        <li>Last Price Increase: 2024-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>etCoderDysto | Contributor | 103689450</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by IuliiaHerets** [comment] 2024-08-18 21:05
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment] 2024-08-18 21:05
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment] 2024-08-18 21:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag in X: Y format is displayed in X\: Y format in review flow
### What is the root cause of that problem?
We are passing a tag that is formatted in `X\: Y` without removing the `\` here to `text` prop of `options` object here
https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/pages/TransactionDuplicate/ReviewTag.tsx#L23-L30
Then `ReviewFields` will use the `text` prop to render the `X\: Y` formatted tag
https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/pages/TransactionDuplicate/ReviewTag.tsx#L45-L48
### What changes do you think we should make in order to solve the problem?
 Using `PolicyUtils.getCleanedTagName()`, we should remove `\` from `X\: Y` tag before passing it to `ReviewFields`  [here](https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/pages/TransactionDuplicate/ReviewTag.tsx#L23-L29)

```
 {
      text: PolicyUtils.getCleanedTagName(tag),
      value: tag,
},

```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-08-18 21:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag in X: Y format is displayed in X\: Y format in review flow
### What is the root cause of that problem?
We are passing a tag that is formatted in `X\: Y` without removing the `\` here to `text` prop of `options` object here
https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/pages/TransactionDuplicate/ReviewTag.tsx#L23-L30
Then `ReviewFields` will use the `text` prop to render the `X\: Y` formatted tag
https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/pages/TransactionDuplicate/ReviewTag.tsx#L45-L48
### What changes do you think we should make in order to solve the problem?
 Using `PolicyUtils.getCleanedTagName()`, we should remove `\` from `X\: Y` tag before passing it to `ReviewFields`  [here](https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/pages/TransactionDuplicate/ReviewTag.tsx#L23-L29)

```javascript
 {
      text: PolicyUtils.getCleanedTagName(tag),
      value: tag,
},

```

### What alternative solutions did you explore? (Optional)

**Comment by raza-ak** [comment] 2024-08-23 11:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag in X: Y format is displayed in X\: Y format in review flow
### What is the root cause of that problem?
There are two issues.

1. [Frontend] When users create a tag then `escapeTagName` function is appending `//` before colon in the tag name before sending request to server.
[-1-New-Expensify.webm](https://github.com/user-attachments/assets/ad6c7b91-aded-4f94-8121-aae440853f25)
<img width="522" alt="image" src="https://github.com/user-attachments/assets/e158a0cd-0d5f-4b05-9841-26b9ec5d03d4">

2. [Backend] I tested by removing the // from the tag name but // is still appending to the tab name. 

### What changes do you think we should make in order to solve the problem?


1. We don’t need to call escapeTagName and send the user provided tag name to server. 
2. - I tested by removing the // from the tag name but // is still appending to the tab name. So we need to fix this issue from backend as well.

**Comment by getusha** [comment] 2024-08-23 11:21
cc @bernhardoj this looks related to https://github.com/Expensify/App/pull/46556

**Comment by bernhardoj** [comment] 2024-08-23 14:52
It's not. We're not cleaning the tag name as @etCoderDysto suggested.

**Comment by getusha** [comment] 2024-08-24 08:46
@etCoderDysto's [proposal](https://github.com/Expensify/App/issues/47615#issuecomment-2295400652) looks good to me.
🎀 👀 🎀 C+ Reviewed!

**Comment by etCoderDysto** [comment] 2024-08-26 18:05
PR will be ready for review soon

**Comment by puneetlath** [comment] 2024-08-29 18:27
@etCoderDysto how's the PR coming?

**Comment by etCoderDysto** [comment] 2024-08-30 07:47
Hi @puneetlath. Sorry, I am OOO until the coming Monday. PR will be ready for review on Monday.

**Comment by etCoderDysto** [comment] 2024-09-01 18:01
PR will be ready for review by tomorrow

**Comment by stephanieelliott** [comment] 2024-09-11 02:49
PR is still under active review

**Comment by stephanieelliott** [comment] 2024-09-17 02:36
PR was merged to main

**Comment by stephanieelliott** [comment] 2024-09-27 08:49
Summarizing payment on this issue: 

 - Contributor: @etCoderDysto $250 via Upwork -- PAID 
 - Contributor+: @getusha $250 via NewDot -- please request 
 
 Upwork job is here: https://www.upwork.com/jobs/~0176ca0a6294fa423b

**Closed by stephanieelliott** 2024-09-27 08:49 UTC
Labels: Reviewing, External, Monthly, Awaiting Payment, Bug
