### ISSUE TITLE
[$1000] Web - New group & Split - Hitting Enter on Add to group and split button does not work

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27997] opened 2023-09-22 08:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to + > Send message.
3. Navigate to Add to group button using tab key.
4. Press Enter.
5. Repeat Step 1 to 3 in Request money menu.

## Expected Result:
When pressing Enter on Add to group and Split button, the button will work as expected.

## Actual Result:
Pressing Enter on Add to group button closes the RHP, while Split button redirects user to Request monet confirmation screen.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.72-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/dbb9d0b8-c779-4f43-b7eb-6629bb1c66df

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01892c0a3b7b6fdf32</li>
        <li>Upwork Job ID: 1705748647468806144</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by ayazalavi** [comment] 2023-09-25 04:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tab key not working for send message and request money buttons i.e **Add to group** and **split**.

### What is the root cause of that problem?
Buttons doesn't have onFocus and OnBlur handlers in https://github.com/Expensify/App/blob/bcc2ddbbeaa6b0c2bc7e6c9d73b1112b52c09e34/src/components/Button/index.js

### What changes do you think we should make in order to solve the problem?
Add OnFocus and OnBlur keeping state in ONYX about button focus/blur and call [onAddtoSelection](https://github.com/Expensify/App/blob/e6a621adf939e3a09cf5ac28ca904fd0769688e3/src/pages/NewChatPage.js#L193)

Result:

https://github.com/Expensify/App/assets/767439/44039691-3380-4df7-9574-73ed62560e43

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ayazalavi** [comment] 2023-09-26 04:15
@abdulrahuman5196 any updates?

**Comment by DylanDylann** [comment] 2023-09-27 09:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
-  Web - New group & Split - Hitting Enter on Add to group and split button does not work

### What is the root cause of that problem?
- Currently, we have the logic that allows the user to choose an option by using the ARROW key and ENTER key: ARROW key is used to change the focused option, and ENTER is used to select this option. 
- When we change the focused component by using tab key, for example focus to "Split" button in option A, and using ARROW key to change the focused component to option B, then pressing ENTER, it will call both the onClickSplit function for option A and onSelectRow for option B. In case select participants in request money, the onSelectRow(B) will navigate user to confirm request money screen, that lead to the bug. Similar to the create new chat logic
 - Here is the logic when pressing ENTER key:
https://github.com/Expensify/App/blob/41ddd7428340fd8d347e8160980809e76a93899b/src/components/OptionsSelector/BaseOptionsSelector.js#L168-L178
https://github.com/Expensify/App/blob/41ddd7428340fd8d347e8160980809e76a93899b/src/components/OptionsSelector/BaseOptionsSelector.js#L211-L235
### What changes do you think we should make in order to solve the problem?
- We can make sure that when the current active component is the "Split" button or "Add to group" button, just call the onClickSplit or OnClickAddToGroup, and skip the onSelectRow function. Like below:
Update https://github.com/Expensify/App/blob/41ddd7428340fd8d347e8160980809e76a93899b/src/components/OptionsSelector/BaseOptionsSelector.js#L211-L235 to:
```
  selectFocusedOption() {
        const currentActive = DomUtils.getActiveElement();
        if (currentActive?.textContent === 'Split') {
            return;
        }
        ...

```

### What alternative solutions did you explore? (Optional)
- NA

### Result

[Screencast from 27-09-2023 16:10:23.webm](https://github.com/Expensify/App/assets/141406735/1223cddf-166b-4a7d-8488-d27c07d7bbfe)

**Comment by abdulrahuman5196** [comment] 2023-09-27 11:18
Rewiewing now

**Comment by ayazalavi** [comment] 2023-09-27 13:07
### Proposal
[Updated](https://github.com/Expensify/App/issues/27997#issuecomment-1732876327)

**Comment by abdulrahuman5196** [comment] 2023-09-28 14:05
We don't expect code diffs in proposal actually

**Comment by abdulrahuman5196** [comment] 2023-09-29 10:23
Re-checking again

**Comment by abdulrahuman5196** [comment] 2023-09-29 10:28
I am not aligned with a proposal of added onyx state for focus on the proposal here https://github.com/Expensify/App/issues/27997#issuecomment-1732876327

**Comment by abdulrahuman5196** [comment] 2023-09-29 10:29
@laurenreidexpensify Could you kindly check internal if we will work on this issue? 
I remember sometime back we mentioned to not to look at keyboard or accessibility kind of issues?

**Comment by ayazalavi** [comment] 2023-10-01 16:05
> I am not aligned with a proposal of added onyx state for focus on the proposal here https://github.com/Expensify/App/issues/27997#issuecomment-1732876327

We can pass on focus and blur callbacks alternatively and handle key press event as per requirement. Should I update proposal to show you this solution?

**Comment by laurenreidexpensify** [comment] 2023-10-03 12:18
@mountiny can you buddy check this comment https://github.com/Expensify/App/issues/27997#issuecomment-1740666791 for me? thanks

**Comment by mountiny** [comment] 2023-10-03 15:18
I believe we can proceed with this one, I am not sure if we still continue with this hold or not

**Comment by abdulrahuman5196** [comment] 2023-10-06 12:40
For @DylanDylann 's proposal here https://github.com/Expensify/App/issues/27997#issuecomment-1737014971 , it seems more like a workaround solution to check for elements text. This won't work out if in future the text changes or translation happens. And I am not aligned to checking which child element got clicked on the parent component.

**Comment by abdulrahuman5196** [comment] 2023-10-06 12:41
@laurenreidexpensify Currently we don't have any proposals to approve.

**Comment by ayazalavi** [comment] 2023-10-06 12:42
> > > I am not aligned with a proposal of added onyx state for focus on the proposal here [#27997 (comment)](https://github.com/Expensify/App/issues/27997#issuecomment-1732876327)
> > 
> > 
> > We can pass on focus and blur callbacks alternatively and handle key press event as per requirement. Should I update proposal to show you this solution?
> 
> I am not sure on what this means. If you have a different proposal, do add the same as an alternative solution in your original proposal.

@abdulrahuman5196 if we don't use onyx then we need to pass handler deep down hierarchy. sure let me update proposal to reflect that as well.

**Comment by ayazalavi** [comment] 2023-10-09 12:14
### Proposal 

[Updated](https://github.com/Expensify/App/issues/27997#issuecomment-1732876327)

**Comment by abdulrahuman5196** [comment] 2023-10-09 16:49
Will review the updated proposals tomorrow

**Comment by abdulrahuman5196** [comment] 2023-10-10 16:23
Re-checking now

**Comment by abdulrahuman5196** [comment] 2023-10-10 16:30
@DylanDylann @ayazalavi I am not aligned on added focus mechanisms to keep track if a button is focused during moving with TAB key.
I was expecting something like the button itself should know the press, like For eg:, how a normal button would call onpress for click events and the parent row should process the event.
I am just saying the above as example, but any other good approaches is also fine.

**Comment by abdulrahuman5196** [comment] 2023-10-10 16:31
@laurenreidexpensify Can we bump the price given the issue is already 3 weeks old? And we can search for more proposals?

**Comment by abdulrahuman5196** [comment] 2023-10-14 08:21
@ayazalavi You don't have to wait on our confirmations to update the proposals. If you think you have a better solution do update and intimate in the GH.

**Comment by abdulrahuman5196** [comment] 2023-10-14 08:23
> This is accessibility issue and not supposed to fix at the moment with the same reasoning as [#29132 (comment)](https://github.com/Expensify/App/issues/29132#issuecomment-1754652679)

We did confirm with @mountiny  before here https://github.com/Expensify/App/issues/27997#issuecomment-1745197079. Maybe he could re-confirm as well if required.

**Comment by abdulrahuman5196** [comment] 2023-10-14 08:24
Currently we don't have better proposals to review.

**Comment by mountiny** [comment] 2023-10-15 19:20
Actually we have recently discussed this design will be changed as the buttons in a row are confusing. 

Since this will change i think we can close this issue now

**Comment by mountiny** [comment] 2023-10-15 19:20
Given it was also reported internally nothing to pay here, thanks for your time

**Closed** 2023-10-15 19:20 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
