### ISSUE TITLE
[HOLD for payment 2024-02-19] [$500] Create Automation for when main fails in `/App`

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#34110] opened 2024-01-08 19:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
We have a Github Action defined in `App/.github/workflows/preDeploy.yml` that can fail without being noticed. It runs every time a PR is merged into our main branch. When it fails there is no process for notifying engineers of its failure other than an email to the person who merged the PR, which can easily get lost or ignored. Previous examples of this happening and being handled manually are [here](https://github.com/Expensify/App/issues/33719) and [here](https://github.com/Expensify/App/issues/34108).

Allowing this test suite to break and go unnoticed can make it difficult to diagnose what caused the issue in the first place, and opens us up to performance regressions that could negatively impact the user experience.

## Solution:

Create an automation that produces a new Github issue when main fails. It should only create an issue if there isn't already an open issue for the associated breakage already. The issue should be labelled as daily and should automatically assign both the the author of the PR that contains the commit that kicked off the failed workflow run and the person who merged the PR into main. The issue should also link to the PR that is associated with the failed run.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b564dd37aa88e42</li>
        <li>Upwork Job ID: 1744445606630244352</li>
        <li>Last Price Increase: 2024-01-08</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28091182</li>
<li>rayane-djouah | Contributor | 28091183</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by jjcoffee** [comment] 2024-01-09 15:46
@rayane-djouah's proposal LGTM! I'm guessing we'll dig into the details on the PR.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by pecanoro** [comment] 2024-01-09 18:03
The solution is pretty vague, but I am hoping you guys will handle it in the PR. Assigning @rayane-djouah

**Comment by pecanoro** [comment] 2024-01-09 18:05
I added the bug label so we can get someone from the Bug Zero team to handle payments later

**Comment by jjcoffee** [comment] 2024-01-12 14:58
@blimpich Sorry, I should've clarified this earlier but I realised I'm not 100% on the expected result. Should a new issue be created for _any_ job that's part of the `Process new code merged to main` workflow failing? I see that we already have a Slack notification for the build job, for example:

https://github.com/Expensify/App/blob/964548a2adb3ed9e2572ad33456759176a01b76c/.github/workflows/preDeploy.yml#L26-L27

But no notification for the E2E tests, which seems to be the main issue here from the examples you've linked to.

**Comment by blimpich** [comment] 2024-01-12 20:34
> Should a new issue be created for any job that's part of the Process new code merged to main workflow failing?

@jjcoffee I think so, yes, though that slack notification does add some extra noise. I didn't realize we posted to slack when that happened. Still though, I'd like this to be a more general solution instead of a automation that only concerns the E2E performance tests, even though the issues that I link to are about the the E2E tests. The spirit of the issue is that when `main` breaks, for whatever reason, we should be creating an issue for that breakage.

**Comment by blimpich** [comment] 2024-01-12 20:34
@rayane-djouah for [this workflow run](https://github.com/Expensify/App/actions/runs/7506827805), would your current solution create a single issue?

**Comment by blimpich** [comment] 2024-01-13 02:17
No I like the way it currently works, just confirming 🙂👍

**Comment by muttmuure** [comment] 2024-02-09 15:01
I think we're just waiting for the above PR to pass the regression period? Or is there more to do here? @blimpich

**Comment by pecanoro** [comment] 2024-02-09 16:20
The issue will get updated when the PR gets deployed to prod, it's still on staging

**Comment by jjcoffee** [comment] 2024-02-20 11:17
@muttmuure Friendly bump for payment :bow:

**Comment by blimpich** [comment] 2024-02-21 22:46
Just wanted to say I say this working for the first time in the wild today ([link](https://github.com/Expensify/App/issues/37042)). Nice job!! 🙂

**Comment by muttmuure** [comment] 2024-02-23 15:59
Everyone is paid up

**Closed** 2024-02-23 16:00 UTC
Labels: External, Daily, Improvement, Awaiting Payment
