### ISSUE TITLE
[HOLD for payment 2023-10-10] [HOLD for payment 2023-10-09] [$500] Android-IOU-Distance IOU amount is auto-filled and displayed in manual request money page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26945] opened 2023-09-07 11:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap fab
3. Tap request money
4. Tap distance
5. Tap Start and select an address
6. Tap Finish and select an address
7. Tap next
8. Select a workspace
9. Note the Request money amount
10. Navigate back to Request money page
11. Tap Manual

## Expected Result:
The Distance IOU amount should not be displayed in manual request money page.

## Actual Result:
The Distance IOU amount is auto-filled and displayed in manual request money page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/b59d3cb8-065b-4c2d-aa1b-19d00909db20

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693999827026719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01baf90b8cc8571594</li>
        <li>Upwork Job ID: 1702484361858043904</li>
        <li>Last Price Increase: 2023-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26852371</li>
<li>tienifr | Contributor | 26852372</li>
<li>ashimsharma10 | Reporter | 26852374</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-07 11:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU amount is autofilled and displayed in manual request page when editing Distance request.

### What is the root cause of that problem?
The NewRequestAmountPage sets the default value to iou.amount which retrieves the saved amount from Onyx.

### What changes do you think we should make in order to solve the problem?
Do not set the iou.amount value if the request page is not in focus.

### What alternative solutions did you explore? (Optional)
None.

**Comment by joh42** [comment] 2023-09-07 11:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we go to the manual money request tab after starting a distance request, the amount from the distance request remains.
### What is the root cause of that problem?
We already reset the data when the tab changes:

https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/pages/iou/MoneyRequestSelectorPage.js#L64-L67

The problem is that when the manual data tab renders, the new amount value has not yet been reset in Onyx. When it is reset, we do not change the amount since there is a condition returning early if `!amount`:

https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/pages/iou/steps/MoneyRequestAmountForm.js#L103-L105

### What changes do you think we should make in order to solve the problem?


I suggest we update the aforementioned condition so that we still set the amount if it is 0:
```
    if (!currency || (!amount && amount !== 0)) {
        return;
    }
```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by joh42** [comment] 2023-09-07 12:02
Demo of my proposed solution:

https://github.com/Expensify/App/assets/138504087/9b1f465e-6792-4291-906b-0431e73e1202

**Comment by joh42** [comment] 2023-09-07 12:04
Also as per this comment we want to clear the data when we switch between request types: https://github.com/Expensify/App/issues/26579#issuecomment-1703948897
> We still want to reset the money request information because we are sharing the data for a draft money request. If we don't clear the data when a different tab/request type is selected, draft data from the previous type might be included in the new money request.

**Comment by alexpensify** [comment] 2023-09-08 23:38
I've run out of time today and will test soon.

**Comment by alexpensify** [comment] 2023-09-11 22:21
Still on my testing list

**Comment by alexpensify** [comment] 2023-09-15 00:55
@cubuspl42 - when you get a chance, can you please review if the proposals will address this issue? Thanks!

**Comment by cubuspl42** [comment] 2023-09-15 11:51
@izarutskaya @alexpensify 

I think that the "expected result" should not be just the "actual result", but negated. What amount should actually be displayed? 0?

**Comment by alexpensify** [comment] 2023-09-18 19:09
Yeah, I think 0 makes sense.

**Comment by cubuspl42** [comment] 2023-09-19 12:03
I like the approach taken by @joh42 and @tienifr, which focuses on improving the already existing logic for `resetMoneyRequestInfo`, which seems to have the intention to prevent exactly what we're observing in this issue.

@joh42 was first here, but I think that the hook-based solution by @tienifr is the better one.

So I say we go with @tienifr here.

C+ reviewed 🎀 👀 🎀

**Comment by alexpensify** [comment] 2023-09-21 18:18
@marcochavezf - we need a review here, please. Thanks!

**Comment by alexpensify** [comment] 2023-09-25 08:30
I've bumped @marcochavezf in Chat.

**Comment by marcochavezf** [comment] 2023-09-25 08:52
Thanks for the review @cubuspl42, also @tienifr's proposal looks good to me 🚀

**Comment by cubuspl42** [comment] 2023-09-29 10:14
This is being taken care of

**Comment by alexpensify** [comment] 2023-10-05 23:41
@cubuspl42 - to prepare for the payment date, can you please complete the checklist? Thanks!

**Comment by cubuspl42** [comment] 2023-10-06 11:58
- The PR that introduced the bug has been identified. Link to the PR:
    - https://github.com/Expensify/App/pull/25707/files#r1348624232
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - [N/A](https://github.com/Expensify/App/pull/25707
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - Launch the app.
    - Tap the Floating Action Button (FAB).
    - Select the 'Request Money' option.
    - Access the 'Distance' feature.
    - Click on 'Start' and choose a specific address.
    - Click on 'Finish' and designate a different address.
    - Proceed by tapping 'Next'.
    - Choose your preferred workspace.
    - Take note of the 'Request Money' amount displayed.
    - Navigate back to the 'Request Money' page.
    - Select the 'Manual' option.
    - Confirm that no amount is set (you should see a slightly greyed-out 0)

**Comment by cubuspl42** [comment] 2023-10-06 11:58
- The PR that introduced the bug has been identified. Link to the PR:
    - https://github.com/Expensify/App/pull/25707/files#r1348624232
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - https://github.com/Expensify/App/pull/25707
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - Launch the app.
    - Tap the Floating Action Button (FAB).
    - Select the 'Request Money' option.
    - Access the 'Distance' feature.
    - Click on 'Start' and choose a specific address.
    - Click on 'Finish' and designate a different address.
    - Proceed by tapping 'Next'.
    - Choose your preferred workspace.
    - Take note of the 'Request Money' amount displayed.
    - Navigate back to the 'Request Money' page.
    - Select the 'Manual' option.
    - Confirm that no amount is set (you should see a slightly greyed-out 0)

**Comment by alexpensify** [comment] 2023-10-10 23:41
My mistake, I missed that there was a regression here but was addressed quickly. I need another day to review and confirm the payment amounts. For now, I've paid the reporter.

**Comment by alexpensify** [comment] 2023-10-12 22:15
Here is the payment summary: 

-  External issue reporter @ashimsharma10 $50 
-  Contributor that fixed the issue @cubuspl42 $500
-  Contributor+ that helped on the issue and/or PR @tienifr $500 

Upwork Job: https://www.upwork.com/jobs/~01baf90b8cc8571594

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: This GH would fall under an urgency bonus but due to regression there won't be one. We did fix the issue quickly, so I'll be keeping the base pay as is for the contributors.

**Comment by alexpensify** [comment] 2023-10-12 22:20
Everyone has been paid in Upwork. I need to create the regression test and will close it.

**Comment by alexpensify** [comment] 2023-10-16 23:10
Not overdue, I need to create the regression test.

**Comment by cubuspl42** [comment] 2023-10-17 09:06
> * Contributor that fixed the issue @cubuspl42 $500
> 
> * Contributor+ that helped on the issue and/or PR @tienifr $500

It's the opposite, but doesn't matter much I guess

**Comment by alexpensify** [comment] 2023-10-18 00:34
Alright, I updated the summary based on the @cubuspl42 feedback Also, I created the regression test, so I'm going to close this out.

**Closed by alexpensify** 2023-10-18 00:34 UTC
Labels: External, Daily, Awaiting Payment, Bug
