### ISSUE TITLE
[HOLD for payment 2024-04-05] [$100] Remove the closeFullScreen() method from code since it is no longer used

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36509] opened 2024-02-14 15:14 UTC
The back button was removed from the modals and so now the `closeFullScreen()` method is no longer used in the code, but it was never removed. Let's remove it!

<details>
<summary>Old Issue Description</summary>
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal 
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace filter is set to "Expensify".
1. Go to staging.new.expensify.com
2. Go to any chat and send a message.
3. Open workspace switcher.
4. Select any workspace.
5. Click Profile settings.
6. Click back button on the top left.

## Expected Result:
App closes profile settings and reopens the chat that shows up after switching workspace in Step 4.

## Actual Result:
App reopens the chat that is opened in Step 2, which is before workspace filter is applied, while the workspace filter is still applied.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/32828cc3-8d1c-4347-a25d-f7b624a03ccc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124a682d645bc91de</li>
        <li>Upwork Job ID: 1757785433393643520</li>
        <li>Last Price Increase: 2024-03-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by kbecciv** [comment] 2024-02-14 15:16
We think that this bug might be related #wave8-collect-admins
CC @zanyrenney

**Comment by rushatgabhane** [comment] 2024-02-16 02:31
Let's fix the issue then instead of reverting

**Comment by rushatgabhane** [comment] 2024-02-20 03:55
looking for proposals

**Comment by bi-kash** [comment] 2024-02-22 13:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The current issue pertains to the functionality of the back button in profile settings, which erroneously navigates to the conversation before workspace switching.

### What is the root cause of that problem?
Upon pressing the back button in profile settings, the closeFullScreen() function is triggered, utilizing StackActions.poptotop() to jump to the first screen in the stack. However, the desired behavior is to navigate only one step back.
``` javascript
/**
 * Close the full screen modal.
 */
function closeFullScreen() {
    const rootState = navigationRef.getRootState();
    navigationRef.dispatch({...StackActions.popToTop(), target: rootState.key});
}
```


### What changes do you think we should make in order to solve the problem?
We can use StackAction.pop(1) instead of StackActions.poptotop()
```javascript
/**
 * Close the full screen modal.
 */
function closeFullScreen() {
    const rootState = navigationRef.getRootState();
    navigationRef.dispatch({...StackActions.pop(1), target: rootState.key});
}
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by garatkarr** [comment] 2024-02-25 19:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After navigation around various chats and workspaces and then the user brings up the Profile page, when user click the Left Chevron at the top left it does not go back to the last chat page viewed. The user expectation is it should go back to the chat page immediately before opening the Profile page.

### What is the root cause of that problem?
The root cause of the problem is the wrong action is called when the Left Chevron is clicked. `StackActions.popToTop()` is the wrong action introduced in [404b0b6](https://github.com/Expensify/App/commit/404b0b65ec58bbe3b072d366d78f266f8de832bd)

### What changes do you think we should make in order to solve the problem?
We should revert [404b0b6](https://github.com/Expensify/App/commit/404b0b65ec58bbe3b072d366d78f266f8de832bd) to restore correct functionality of the Left Chevron. 

[404b0b6](https://github.com/Expensify/App/commit/404b0b65ec58bbe3b072d366d78f266f8de832bd) was supposed to fix "Clicking back from the Account Settings back in top left corner takes noticeably longer to open the chats then other back buttons" but I have not been able to reproduce this slower performance on Web. We should fix this issue (#36509) now because it's broken functionality which is more important than performance. Separately, another issue should be opened to properly investigate and address the slower performance. It's possible this performance issue no longer exists.

### What alternative solutions did you explore? (Optional)

**Comment by rushatgabhane** [comment] 2024-02-28 15:09
on my plate

**Comment by bi-kash** [comment] 2024-02-29 15:33
## Proposal
[Updated](https://github.com/Expensify/App/issues/36509#issuecomment-1959508184)

**Comment by rushatgabhane** [comment] 2024-02-29 17:13
I like @bi-kash's proposal https://github.com/Expensify/App/issues/36509#issuecomment-1959508184

🎀 👀 🎀

**Comment by rushatgabhane** [comment] 2024-02-29 17:41
@tgolen I'm suggesting another C+ to review proposals here.

**Comment by rushatgabhane** [comment] 2024-02-29 17:52
@barros001 the [commit](https://github.com/react-navigation/react-navigation/commit/b1f13774295465942aafa1b0ff611b9eebccbd77#) you're referring to in react navigation is 4 years old. I can't find it in `main` branch. Maybe they removed the delay?

**Comment by tgolen** [comment] 2024-02-29 19:20
OK, I read through most of this issue and I hope I caught everything. I understand the focus on `pop` and `popToTop` but I am concerned that it could have far-reaching effects across the app. Are we sure we want to affect the entire app?

If so, then I think this problem is not really related to the workspace selector only, and that's just one way the problem is manifesting. I agree with Rushat's [plan](https://github.com/Expensify/App/issues/36509#issuecomment-1971641735) to fix that.

If we don't want to affect the entire app, then @bi-kash's proposal is the correct one I think.

**Comment by rushatgabhane** [comment] 2024-03-01 15:19
No worries, it's all good :)

**Comment by tgolen** [comment] 2024-03-04 15:44
@rushatgabhane How do you want to move forward on this one? Is the root problem happening elsewhere in the app and this should be a holistic solution for the entire app? OR does this problem only affect this single flow and a more simple fix is in order?

**Comment by mvtglobally** [comment] 2024-03-05 04:48
Issue not reproducible during KI retests. (First week)

**Comment by bi-kash** [comment] 2024-03-05 05:54
> Issue not reproducible during KI retests. (First week)

Issue is still reproducible in staging and production

**Comment by rushatgabhane** [comment] 2024-03-06 17:31
Yeah sure! Let me deep dive what to do here

**Comment by rushatgabhane** [comment] 2024-03-07 21:21
@tgolen I think we should measure the delay using `StackActions.pop` vs `StackActions. popToTop`. 

If the delay is measureable and user can feel the lag, then we could go with @bi-kash's [proposal](https://github.com/Expensify/App/issues/36509#issuecomment-1959508184) because I can't find this issue happening anywhere else in the app.

**Comment by rushatgabhane** [comment] 2024-03-07 21:23
If there are no posts, I'll find a way to measure the delay over the weekend.

**Comment by s77rt** [comment] 2024-03-10 10:51
Besides the delay issue there is also this issue https://github.com/Expensify/App/issues/36900

**Comment by adelekennedy** [comment] 2024-03-11 22:11
clearing the overdue here - @rushatgabhane were you able to measure the delay over the weekend?

**Comment by adelekennedy** [comment] 2024-03-13 18:43
I've added this to wave collect as I think it belongs there and under the Release 1 status

**Comment by rushatgabhane** [comment] 2024-03-15 15:52
Hey, now that we've removed back button from the full screen modal, do we really need to fix this bug?
It can't be reproduced after click browser back. The function `closeFullScreen` where the root cause is isn't being used.

<img width="1257" alt="image" src="https://github.com/Expensify/App/assets/29673073/57be5dc5-c42d-401c-b79b-28320ac414f5">

**Comment by tgolen** [comment] 2024-03-15 16:43
That's a good point. It's a shame that `closeFullScreen` has been abandoned. It should be cleaned up now. I'm going to reduce the bounty of this issue to $100 and change the scope to just be a simple cleanup.

**Comment by adelekennedy** [comment] 2024-03-15 16:45
@trjExpensify with the change above should this be under polish vs release 1?

**Comment by rushatgabhane** [comment] 2024-03-15 17:04
Let's hire @barros001 because they were first to mention the root cause?
https://github.com/Expensify/App/issues/36509#issuecomment-1961909146

@tgolen 🎀👀🎀

**Comment by trjExpensify** [comment] 2024-03-15 19:11
yep, polish makes sense.

**Comment by rushatgabhane** [comment] 2024-03-30 08:48
Not a bug. This is a cleanup issue

**Comment by rushatgabhane** [comment] 2024-03-30 08:49
@adelekennedy could you please attach payment summary 🙇

**Comment by adelekennedy** [comment] 2024-04-01 22:57
Is payment due today or on the 5th? Happy to pay out today but want to check if the retitling automation is correct!

**Comment by adelekennedy** [comment] 2024-04-02 16:02
ah Upwork, always reliably unreliable

**Comment by adelekennedy** [comment] 2024-04-02 16:45
payment made!

**Closed by adelekennedy** 2024-04-02 16:45 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-04-03 03:01
$100 approved for @rushatgabhane
