### ISSUE TITLE
[$1000] Web - Console Error appears when Request money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22737] opened 2023-07-12 11:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
First Open the console in inspect
1. Click plus sign
2. Open Request money
3. Write an number and click button Next
4. Select an email or number phone
5. Click button Request

## Expected Result:
Shouldn't show error in the console

## Actual Result:
Console Error appears when Request money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8917370f-a657-449e-890e-9e330525149e

![image (21)](https://github.com/Expensify/App/assets/93399543/793857c7-a004-4074-add0-1221f9e773dd)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Mauri-salazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689103367965409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0172a557c830f6c2cd</li>
        <li>Upwork Job ID: 1679181860611170304</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-12 11:34
@puneetlath Also seen the console error when clicking on the profile picture.

https://github.com/Expensify/App/assets/93399543/1d41183b-a212-4222-a812-d8686d35a5da

**Comment by DiaRar** [comment] 2023-07-12 18:01
Contributor details
Your Expensify account email: diaconescurares2@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01282f1dd802d54185

**Comment by DiaRar** [comment] 2023-07-12 18:01
Contributor details
Your Expensify account email: diaconescurares2@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01282f1dd802d54185

**Comment by kbecciv** [comment] 2023-07-12 18:37
@puneetlath Another console error when uploading zip file.

https://github.com/Expensify/App/assets/93399543/ee737b83-c0d2-4e7c-9120-80bef7b738c2

**Comment by situchan** [comment] 2023-07-14 13:39
Dupe of https://github.com/Expensify/App/issues/22853

**Comment by abdulrahuman5196** [comment] 2023-07-14 13:53
Yes. I think its a dupe. We can retest this.

**Comment by abdulrahuman5196** [comment] 2023-07-21 16:10
@puneetlath  is OOO. Once he is back we can retest and close this if not reproducible

**Comment by puneetlath** [comment] 2023-07-24 17:03
Unable to reproduce so closing.

**Closed by puneetlath** 2023-07-24 17:03 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
