### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] The font for unread messages is not bolded in Android

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25967] opened 2023-08-25 18:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open reports sidebar
2. Observe any report that has unread message
## Expected Result: 
The font should be bolded

## Actual Result: 
The font is not bolded

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/25eeb6fb-3aaa-45ad-9a71-e474325ca744

**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692053748619759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014cfdb7c2eb889c72</li>
        <li>Upwork Job ID: 1699723695123820544</li>
        <li>Last Price Increase: 2023-09-21</li>
<li>Automatic offers: </li>
<ul>
<li>krishna2323 | Reporter | 26624529</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-08-25 18:40
### Proposal by @Krishna2323
### Please re-state the problem that we are trying to solve in this issue.
The font for unread messages is not bolded in Android
### What is the root cause of that problem?
React native has a bug in which fonts are not bolded on android until we add a bold fontFamily file. We are using the right bold fontFamily file & font weight variable  in HeaderView, thats why it's bolded in android correctly.
https://github.com/Expensify/App/blob/00efce42977caf147dddf7763f06758bf39bb6f1/src/styles/styles.js#L820-L825
But not in the DisplayNames in OptionRowLNH.
https://github.com/Expensify/App/blob/00efce42977caf147dddf7763f06758bf39bb6f1/src/components/LHNOptionsList/OptionRowLHN.js#L77-L78
### Style:
https://github.com/Expensify/App/blob/00efce42977caf147dddf7763f06758bf39bb6f1/src/styles/styles.js#L1467-L1472
https://github.com/Expensify/App/blob/00efce42977caf147dddf7763f06758bf39bb6f1/src/styles/styles.js#L1445-L1448
### What changes do you think we should make in order to solve the problem?
We need to change fontFamily & fontWeight according to the unread status and use it just like it is used in HeaderView. File below also confirms the root cause.
https://github.com/Expensify/App/blob/main/src/styles/fontWeight/bold/index.android.js

**Comment by laurenreidexpensify** [comment] 2023-09-04 14:34
@Expensify/design curious for your take on this one

**Comment by shawnborton** [comment] 2023-09-05 13:48
That does seem like a bug and even beyond that, it looks like not only is the font not bold, but a totally incorrect font is being applied. Notice how the number "6" changes shape when it goes from unread to read? So yeah, this is definitely a bug but I would say this is most likely a regression as this would have been working fine at some point. Cc @grgia who implemented the fonts here. 

If this is a regression (which I think it must be), then let's track it down and have the offending PR author fix it.

**Comment by shawnborton** [comment] 2023-09-05 22:30
Hmm I feel like we have touched the sidebar stuff way more recently than 2020. Either way, let's get this fixed but curious for @grgia's take too. 

Do we know why only a few Android devices experience this?

**Comment by shawnborton** [comment] 2023-09-06 15:39
Sounds good, @laurenreidexpensify can we get this issue into motion? 

The Android thing seems like a bit of a hack. We should be using font-weight 700 as it maps to Expensify Neue Bold.

**Comment by laurenreidexpensify** [comment] 2023-09-07 09:58
Thanks for the review @shawnborton - @grgia am assigning you in case you want to take this for now / add any additional details

**Comment by Santhosh-Sellavel** [comment] 2023-09-07 18:23
Unassigned myself due to low bandwidth assign new C+ if required by adding external/internal label again, thanks!

cc: @laurenreidexpensify

**Comment by grgia** [comment] 2023-09-12 06:02
assigned @allroundexperts

**Comment by grgia** [comment] 2023-09-12 06:04
I agree with @shawnborton that it doesn't look like a regression, but we should avoid any hacky solutions

**Comment by situchan** [comment] 2023-09-12 06:04
I am not able to reproduce in android. Is this device specific?

**Comment by situchan** [comment] 2023-09-12 06:08
@Krishna2323 what device are you using? It's not stated in repro step

**Comment by laurenreidexpensify** [comment] 2023-09-18 09:32
@allroundexperts are we good to move forward with the proposal above?

**Comment by laurenreidexpensify** [comment] 2023-09-24 23:53
@allroundexperts any luck on the Realme device?

**Comment by laurenreidexpensify** [comment] 2023-09-26 05:08
I think as long as there are no negative knock on effects of this then we should fix it. If you're happy with the proposals above @allroundexperts let's do it

**Comment by laurenreidexpensify** [comment] 2023-10-13 10:51
Payment Summary: 

-  External issue reporter - @Krishna2323  - $50 paid in Upwork 
-  Contributor that fixed the issue - @Krishna2323  - $500 + $250 urgency bonus - paid in Upwork
-  Contributor+ that helped on the issue and/or PR - @allroundexperts - $500 + $250 bonus - please request in Newdot 

@allroundexperts please complete checklist above thanks

**Comment by laurenreidexpensify** [comment] 2023-10-18 17:32
waiting on @allroundexperts for checklist!

**Comment by laurenreidexpensify** [comment] 2023-10-23 09:50
@allroundexperts thanks for the update. I think in this instance we're honouring the issue creation date, so the payments stand. Thanks for checking tho. I am closing as we have no further action here now.

**Closed by laurenreidexpensify** 2023-10-23 09:50 UTC
Labels: External, Engineering, Daily, Needs Reproduction, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-23 16:34
$1,500 payment approved for @allroundexperts based on summary above.
