### ISSUE TITLE
[HOLD for payment 2023-08-21] [$1000] Dev: Web - Whole Magic code screen is lagging on Safari Mac when the countdown is ticking

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22798] opened 2023-07-13 11:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Log out
2.  Enter Email
3. Go to magic code screen

## Expected Result:
No lags

## Actual Result:
Lags when resend code clock is ticking (After it's over it's all good)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.39-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1395e70f-a911-4cea-8898-e46925a068dd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @wojtus7
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689161375102319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b1b4261926709eab</li>
        <li>Upwork Job ID: 1679761308203876353</li>
        <li>Last Price Increase: 2023-08-04</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-07-14 07:53
I reproduced this in Safari. Weird.

**Comment by shubham1206agra** [comment] 2023-07-14 11:10
Its related to `Lottie` mp. Tried to write Custom Component for countdown. Looks like Animation frame has some issue that is being used by `Lottie`

**Comment by closedspace** [comment] 2023-07-14 15:56
Setting the little svg city background thing to be relatively positioned as opposed to static seems to do the trick - 

Uploading CleanShot 2023-07-14 at 18.50.08.mp4…

**Comment by closedspace** [comment] 2023-07-14 16:01
Setting the little svg city background thing to be relatively positioned as opposed to static seems to do the trick - 

https://github.com/Expensify/App/assets/36342328/bf74a2de-051c-4229-af2d-4652f24a787e

Commenting again since I couldn't upload the video for some reason 😅

**Comment by shubham1206agra** [comment] 2023-07-14 16:20
> Setting the little svg city background thing to be relatively positioned as opposed to static seems to do the trick - 
> 
> https://github.com/Expensify/App/assets/36342328/bf74a2de-051c-4229-af2d-4652f24a787e
> 
> Commenting again since I couldn't upload the video for some reason 😅
> 
> 

Can you check the same for resized windows?

**Comment by closedspace** [comment] 2023-07-14 16:40
It works on just about any size I've tried. Basically the reason why the issue isn't prelevant on mobile screen widths is because in that case we have these styles attached to the background image -
``` signInBackgroundMobile: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        minHeight: 700,
    },```

Keeping this in mind and taking out the background from whatever problematic stacking context it is in helps improve how that animation renders and gives us the buttery smooth motion on higher screen sizes.

https://github.com/Expensify/App/assets/36342328/570b21ae-8f8a-4955-9acb-cc9152bcb90c

**Comment by greg-schroeder** [comment] 2023-07-17 16:18
@closedspace did you want to put together a proposal?

**Comment by closedspace** [comment] 2023-07-17 16:36
@greg-schroeder A proposal for a solution? I kinda just bumped into this project the other day so I'm not sure what a formal proposal would be. My above comments suggest a solution for this bug, if that counts for anything

**Comment by eVoloshchak** [comment] 2023-07-17 16:49
> probably should read those big guidelines 😅

THIS😄
To post a proposal the only thing you need is [CONTRIBUTING.md] (https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) I think
Welcome, by the way, it's awesome to see new contributors! 
I'll circle back to your [proposal](https://github.com/Expensify/App/issues/22798#issuecomment-1636109154) later today, could you please update it according to [PROPOSAL_TEMPLATE.md](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md)

**Comment by closedspace** [comment] 2023-07-17 17:50
### Please re-state the problem that we are trying to solve in this issue.
On widescreen safari, the little animation which plays while the user is in send-me-my-magic-code timeout seems to stutter with each tick of the timeout counter.

### What is the root cause of that problem?
The root cause is tricky to pindown as it is related to how Webkit handles rendering. My hypothesis is that the city background svg and the animated svg are stuck on the same composite layer, thus causing an inefficient repaint of both svgs every time the counter triggers a re-render.

### What changes do you think we should make in order to solve the problem?
Setting the city background svg to be non statically positioned resolves this animation stutter by potentially forcing the browser to handle both svgs on separate composite layers. Relative positioning is preferred so as to not cause any change in positioning of the background on the page

### What alternative solutions did you explore? (Optional)
I have looked into any possible component rendering issues and found none. I also looked into whether any other element aside from the city background svg could interact inappropriately with the animation and found nothing else.

**Comment by eVoloshchak** [comment] 2023-07-17 23:12
@closedspace, thanks for the proposal, this is an interesting issue
I can confirm the fix resolving stuttering for me (even though it's not 100% reliable, I was still able to make it stutter by resizing the window multiple times, but it's not 100% reproducible)

I wonder what's truly causing the issue, but suspect it's going to be near impossible to find the true root cause for this.

I think we should wait a bit before implementing the workaround for this, perhaps we find an issue/bug for Webkit, or there are different proposals
If that fails, we can implement the @closedspace's proposal, since the problem is pretty severe (I think it has performance implications also, I personally had my laptop's battery drain because Safari with login page was open in the background)
Is there a way we could profile that somehow?

**Comment by ShogunFire** [comment] 2023-07-18 04:02
Can you still reproduce ? I don't have the issue

**Comment by closedspace** [comment] 2023-07-18 05:36
@eVoloshchak I investigated the resizing and can confirm what you see. I looked more deeply into the background city svg structure and I discovered there's a <mask/> which, when removed, seems to resolve this issue. I have not noticed any visual changes to the svg from removing the mask yet

https://github.com/Expensify/App/assets/36342328/c67a0bef-7402-4d0a-9651-97260d1b1e3e

**Comment by greg-schroeder** [comment] 2023-07-21 09:52
I'm not familiar with the mask concept - are you @eVoloshchak?

**Comment by eVoloshchak** [comment] 2023-07-26 19:08
> I looked more deeply into the background city svg structure and I discovered there's a mask which, when it or its reference is removed, seems to resolve this issue.

@closedspace, thanks for investigating this further!
Could you elaborate on how you would disable this mask in code?
Ideally, we need to find out **why** is this happening, not just work around it. If it's a bug with displaying svg in Safari, in perfect scenario we would report in and apply e temporary fix while it's being worked on

**Comment by closedspace** [comment] 2023-07-27 12:15
@eVoloshchak removing the mask reference can be done by removing this line:
https://github.com/Expensify/App/blob/f8bc30500acaed95d4668657cf18558deee79194/assets/images/home-background--desktop.svg#L10
The CSS class is used in only one place so this is sufficient to make the mask unused.

I will look to reproduce the issue within a sandboxed environment and I'll post an update if that ends going somewhere.

**Comment by closedspace** [comment] 2023-07-27 15:22
Nothing down some other things I have explored without much success in improving performance:
- optimizing with [https://jakearchibald.github.io/svgomg/](SVGOMG)
- removing 7000 lines worth of `path` elements barely makes a dent 

Codesandbox - https://codesandbox.io/s/beautiful-boyd-8t2sdn?file=/src/App.js

I am not sure what else can be said other than the mask causing significant repainting costs. Any deeper explanation than that I'd imagine would entail digging into WebKit source code, which I am not brave enough to do.

Some threads I've found in my investigation incase anyone's interested on reading more about Safari and SVGs or contributing:
- https://twitter.com/destroytoday/status/1563716595402285057
- https://stackoverflow.com/questions/75950100/masking-with-black-and-white-images-svg-alternatives-safari-performace-issues
- https://codepen.io/tigt/post/improving-svg-rendering-performance

**Comment by greg-schroeder** [comment] 2023-07-31 14:48
@eVoloshchak how do you feel about @closedspace's update? Is that enough to go on or are we saying it's still a workaround?

**Comment by greg-schroeder** [comment] 2023-08-02 20:28
bump on the above!

**Comment by eVoloshchak** [comment] 2023-08-03 16:18
Yeah, I think we should proceed with @closedspace's [solution](https://github.com/Expensify/App/issues/22798#issuecomment-1638604346) (and removing the [mask](https://github.com/Expensify/App/issues/22798#issuecomment-1653497984))

This is a workaround, since we aren't fixing the root cause, however, I think we should implement it for the following reasons:
1. If this is a bug in WebKit/Safari, we won't be able to fix it
2. If we manage to find what the actual issue is and report in to Apple, it would still take a lot of time for fix tto be implemented
3. This is pretty severe. It's visibly laggy and energy impact (according to macOS's activity monitor) is huge 

🎀👀🎀 C+ reviewed!

**Comment by conorpendergrast** [comment] 2023-08-04 14:28
Flo is OoO until August 21st, so reassigning. @bondydaa [proposal to review](https://github.com/Expensify/App/issues/22798#issuecomment-1664272430) above

**Comment by bondydaa** [comment] 2023-08-04 21:03
proposal sounds good, let's just make sure this mask doesn't cause regressions of the SVG in other browsers as well.

**Comment by closedspace** [comment] 2023-08-04 21:33
I'll have the PR ready in the next couple of hours

**Comment by closedspace** [comment] 2023-08-04 21:34
Contributor details
Your Expensify account email: emil@pernik.org
Upwork Profile Link: https://www.upwork.com/freelancers/emilmomchilov

**Comment by closedspace** [comment] 2023-08-05 13:40
I'm not sure if its redundant to mention, but PR is ready for review https://github.com/Expensify/App/pull/24176
@eVoloshchak @bondydaa

**Comment by greg-schroeder** [comment] 2023-08-21 11:30
Issue Participants:

Issue reported by: @wojtus7
Contributor: @closedspace 
C+: @eVoloshchak 

Was this issue merged in time to be eligible for the speed bonus? ✅ 
Were their any regressions? ❌ 

Payment summary:

Reporter: $250
Contributor: $1,500 ($500) bonus
C+: $1,500 ($500) bonus

**Comment by greg-schroeder** [comment] 2023-08-21 11:36
@wojtus7 what are you Upwork details?

**Comment by eVoloshchak** [comment] 2023-08-22 12:40
- The PR that introduced the bug has been identified. Link to the PR: not applicable, this is a problem with how Safari renders specific SVG files
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: We already have automated performance checks for every PR. This one is a visual lag, that couldn't be caught by those tests. I don't think an additional discussion is needed, this is a visual bug
- Determine if we should create a regression test for this bug.
I don't think we need a regression test here, this was not a problem with the code, but rather a bug in Safari.

**Comment by wojtus7** [comment] 2023-08-22 13:27
Hi @greg-schroeder!

I am from Software Mansion expert agency so I think it's dealt differently and you don't need my Upwork details 🫡

**Comment by greg-schroeder** [comment] 2023-08-22 15:49
Oh got it, duh! Thanks @wojtus7

**Comment by greg-schroeder** [comment] 2023-08-23 06:40
@eVoloshchak please request payment via NewDot! Closing this out.

**Closed by greg-schroeder** 2023-08-23 06:40 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-24 05:41
Reviewed the details for @eVoloshchak. $1,500 approved for payment via NewDot based on BZ summary.
