### ISSUE TITLE
[$250] IOS - Attachment-Choose from gallery - Gallery does not open on second time for applause account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10032] opened 2022-07-20 12:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Tap on any user
4. Tap on Plus button - Add attachment
5. Select Choose from gallery
6. Select any picture and send
7. Repeat step 4-6 a couple times

## Expected Result:
Gallery  opens on second time for applause account

## Actual Result:
Gallery does not open on second time for applause account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.85.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any applause account

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/179978961-58e73a98-5a7c-4538-886f-989a82d9ef8c.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment] 2022-07-21 15:17
Can't reproduce this in dev on the simulator, but I think this is something worth looking into maybe with a physical device. Marking as external as well

**Comment by arosiclair** [comment] 2022-07-21 18:29
@NicMendonca unassigned you by accident!

**Comment by NicMendonca** [comment] 2022-07-21 22:07
job post: https://www.upwork.com/jobs/~0143d439bd04f56f83

**Comment by great111lancer** [comment] 2022-07-21 22:44
Hello @NicMendonca 

I am illia,  React-native developer from upwork,

I just checked the video.

I think on the first open gallery, it is still opened on the background.

I didn't check the app on my emulator, But if you could invite me, I will fix the issue.

Best regards.

Illia

**Comment by ayanmurad987** [comment] 2022-07-21 22:57
Got It 👍
same issue i was already fixed in my previous app I’ll create a PR Buy tomorrow 

ref Upwork

**Comment by marcaaron** [comment] 2022-07-22 00:38
Hey everyone, If you're new to the repo please take a look at our [Contributing Guidelines](https://github.com/Expensify/App/blob/574e19de9ea6689c4e311b6b57a4a18f26d3b040/contributingGuides/CONTRIBUTING.md).

**Comment by ahmdshrif** [comment] 2022-07-23 03:53
> Can't reproduce this in dev on the simulator, but I think this is something worth looking into maybe with a physical device. Marking as external as well

I also can't reproduce it on a real device and simulator. 

we want to know if this is related to a specific OS version. or a specific scenario.

**Comment by mananjadhav** [comment] 2022-07-25 17:06
I can't reproduce this on the physical device on prod and the simulator.  @kbecciv Can you probably retest this or help with better reproduction steps?

**Comment by kbecciv** [comment] 2022-07-27 18:41
@mananjadhav 
Here is reproduction steps:
Precondition: Use expensifail account
1. Launch the app
2. Log in with expensifail account
3. Tap on any user
4. Tap on Plus button - Add attachment
5. Select Choose from gallery 
6. Select any picture and tap Send button
7. Tap on Plus button again - Add attachment
8. Select Choose from gallery 
Tester device: iPhone 8/ 14.2
Attached video with latest build 1.1.86.4

https://user-images.githubusercontent.com/93399543/181347849-4ebfc4ee-8532-4789-b40c-7ce81523afff.MP4

Please et me know if you have any ather request for this issue.

**Comment by mvtglobally** [comment] 2022-08-02 04:05
Issue not reproducible during KI retests. (First week)

**Comment by marcaaron** [comment] 2022-08-03 18:57
Let's close this issue as it is not reproducible.

**Closed by marcaaron** 2022-08-03 18:57 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted, Overdue
