### ISSUE TITLE
[$500] Chat - Text in the composer is also sent when sending a file via drag & drop

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32488] opened 2023-12-05 15:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Type anything in the composer
4. Drag and drop a file
5. Send the file
Note that the text in the composer is also sent

## Expected Result:
Only the file is sent. The text in the composer is not sent

## Actual Result:
The text in the composer is also sent along with the file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4bcf8e13-7a7e-4f2b-8fdb-c3d817e18fa8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131d55976c3ede439</li>
        <li>Upwork Job ID: 1732060394171572224</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-12-05 15:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Text in the composer is also sent when sending a file via drag & drop

### What is the root cause of that problem?
We are sending the comment with the file attachement here
https://github.com/Expensify/App/blob/e0d34b803aed6316fb9804a51ad5caf24f415cbf/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L232-L233
### What changes do you think we should make in order to solve the problem?

We should only send the file to `Report.addAttachement` here
https://github.com/Expensify/App/blob/e0d34b803aed6316fb9804a51ad5caf24f415cbf/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L232-L233

### What alternative solutions did you explore? (Optional)

**Comment by ZhenjaHorbach** [comment] 2023-12-05 15:40
Agree
Based on the code, it looks like expected behavior

https://github.com/Expensify/App/blob/e0d34b803aed6316fb9804a51ad5caf24f415cbf/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L231-L233

**Comment by strepanier03** [comment] 2023-12-07 17:57
I'm going to raise this internally because I'm pretty sure this is intentional behavior. It's worked this way for as long as I can remember and I believe that's by design. 

I'll update this when I have confirmation.

**Comment by strepanier03** [comment] 2023-12-07 18:16
All right, this behavior is by design and is the same behavior Slack has so we're not going to make any changes. 

Closing this.

**Closed by strepanier03** 2023-12-07 18:16 UTC
Labels: External, Daily, Help Wanted, Bug
