### ISSUE TITLE
Selecting same Pronoun removing the pronoun/Calls API again.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24370] opened 2023-08-10 13:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to profile section.
2. Select the same timezone already selected & see API is getting called again.
3. Repeat the same for Pronoun
## Expected Result: 
We're not calling the API's if the data is same, so we should do same here.
## Actual Result: 
Calling API even if the data is same.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.52-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c96b175e-f71b-4f3e-a55f-841bd921815e

https://github.com/Expensify/App/assets/43996225/5020c355-075f-493b-975a-5e1a59b2dc1c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @b4s36t4
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690927044823149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e3816742efa304d</li>
        <li>Upwork Job ID: 1691233224162840576</li>
        <li>Last Price Increase: 2023-08-14</li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2023-08-14 23:40
Discussed `internal` here: https://expensify.slack.com/archives/C01SKUP7QR0/p1691777833317799

**Comment by b4s36t4** [comment] 2023-08-15 02:47
@NicMendonca this issue contains two different issues which both are irrelevant... 
1. Pronoun removes if we select same pronoun. 
2. Time zone saving saving same calls api again. 

Are you aligned here about having only 1 issues for these both?

**Comment by b4s36t4** [comment] 2023-08-15 09:04
https://github.com/Expensify/App/issues/24370#issuecomment-1673246864 Proposal for the timezone issue.

Also @danieldoglas @NicMendonca This is not internal. As I said there are two issue here out of 1 Selecting the same pronoun is removing is frontend issue.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selecting same Pronoun removing the pronoun.
### What is the root cause of that problem?

RCA for this issue lies here https://github.com/Expensify/App/blob/9294e9eacd53ba2ba805c6e33f18c796ccc3306d/src/pages/settings/Profile/PronounsPage.js#L74.

If we see the function and API call we're sending empty string if the selected option is same as saved option which shouldn't be the case.

Instead of returning we're setting empty here causing reset of the pronoun.
### What changes do you think we should make in order to solve the problem?
Instead of setting empty string here we should return without doing the api call and go to back profile screen.

```jsx
if(selectedPronouns.keyForList === initiallyFocusedOption.keyForList){
            Navigation.goBack(ROUTES.SETTINGS_PROFILE)
            return
        }
```
like the above change is required inside the function.



### What alternative solutions did you explore? (Optional)
NA

> This proposal is for pronoun issue.

**Comment by b4s36t4** [comment] 2023-08-15 09:06
I hope this clears the confusion... two bugs... two different RCA's. Sorry for the mess up.

**Comment by danieldoglas** [comment] 2023-08-17 20:19
For item 1, that is the expected behavior.

For item 2: I agree this is an external item, but I don't really think it's a problem. The user effectively did the action of going to the page and clicking on the timezone. If we were automatically changing the timezone in a loop without user interaction, this issue would be a problem for me.

I'm not sure if we do this kind of check in any other place, so I'm mostly thinking we should just close this issue. What do you think @NicMendonca @fedirjh ?

**Comment by b4s36t4** [comment] 2023-08-17 20:21
For item 2 I think we're considering these kind of issues as Bugs. Like these for instance -> https://github.com/Expensify/App/issues/23113

**Comment by NicMendonca** [comment] 2023-08-21 12:06
sure! @danieldoglas that works with me

**Closed by NicMendonca** 2023-08-21 12:06 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug

**Comment by b4s36t4** [comment] 2023-08-21 12:27
@NicMendonca can you please see this issue -> https://github.com/Expensify/App/issues/23113 it's same still we've moved forward to it.
