### ISSUE TITLE
[$500]  Chat - Deleting an IOU makes the chat unread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32907] opened 2023-12-12 10:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to https://staging.new.expensify.com/

2. Open a chat
3. Do a manual IOU
4. Do another manual IOU
5. Go back to the LHN
6. Open the chat again
7. Tap on the IOU
8. Delete the first IOU
9. Go back
10. Go back to the LHN
11. Open the chat again

## Expected Result:
Deleting the IOU shouldn't make the chat unread.

## Actual Result:
Deleting an IOU makes the chat unread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/92fb306a-c6e3-45ca-82bf-1f8aa7ce525c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f653d2e302e6dee1</li>
        <li>Upwork Job ID: 1734519635947929600</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by RAnis2017** [comment] 2023-12-12 19:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The issue is related to the behavior of the Expensify app chat page when performing actions within a chat. 
Specifically, the issue is that creating two manual IOUs and then going back and deleting the first IOU within the chat is currently causing the chat to be marked as unread when back on LHN, contrary to the expected behavior where deleting an IOU should not affect the unread status of the chat.

### What is the root cause of that problem?

The root cause that I found is related to the stale data for reports inside the `ReportScreen.js`.

It is part of withOnyx configurations. It can be adjusted to resolve this issue.

Also, we need to modify some logic inside `ReportActionsList.js` needs to change. 
Since the data is not stale anymore and there's a problem check between `reportID` and `prevReportID`
that needs to be removed.

### What changes do you think we should make in order to solve the problem?


By having stale data not allowed for the withOnyx inside the `ReportScreen.js`

```
    ...
    report: {
         key: ({route}) => `${ONYXKEYS.COLLECTION.REPORT}${getReportID(route)}`,
         allowStaleData: true, // should be false or removed
         selector: reportWithoutHasDraftSelector,
     },
     ...
 ```
And also the code inside the file `ReportActionsList.js` is unnecessary when the data is not stale. This condition prevents the marking of read items. This check of prevReportID is unnecessary. 

`userActiveSince.current` should still be kept.

```
if (!userActiveSince.current || report.reportID !== prevReportID) { // This condition needs to change.
      return;
}
```

By making these two changes we can easily fix the issue. I've checked on the `staging branch`.

Please also check the attached demo.

### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment] 2023-12-12 21:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The UnreadMarker in Expensify's chat system is triggering unexpectedly during both manual IOU creation and deletion.

### What is the root cause of that problem?
While the UnreadMarker's behavior is anticipated for report creation or deletion, the issue lies in its application to the user who initiated these actions, causing them to receive an unnecessary Unread Message notification.

### What changes do you think we should make in order to solve the problem?
In the `src/pages/home/report/ReportActionsList.js` file, specifically within the `shouldDisplayNewMarker` function, introduce a condition to display the unread marker only if the user is not the report creator/editor.
The code adjustment could resemble the following:

```
        if (!currentUnreadMarker) {
            ...

            // Proposed condition to display unread marker only for non-creators/editors
            shouldDisplay = shouldDisplay && (reportAction.actorAccountID !== Report.getCurrentUserAccountID());

            ...
        } else {
```

### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment] 2023-12-17 15:12
Hm, I think this behaviour is reasonable - there's been a change to the IOU amount, so marking it as unread (I.e. 'something has updated') makes sense to me. Going to close this out.

**Closed by bfitzexpensify** 2023-12-17 15:12 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
