### ISSUE TITLE
[HOLD #11321] Bug: Website become choppy while dealing with large text reported by @Tushu17 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11954] opened 2022-10-18 02:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Website/App
2. Go to chat
3. Send a message of 60000 characters
4. Try to edit & save that message.

## Expected Result:
It shouldn't become choppy.

## Actual Result:
It become choppy and sometimes show errors in console.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196324316-02cbf513-fad1-4e14-acfd-90581e3831b5.mov

https://user-images.githubusercontent.com/43996225/196324329-9288c014-0ec0-4328-b12b-b260664e2563.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665756926532669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-10-18 17:08
Checking in the Slack thread to see if there's another issue similar to this, I couldn't find while searching issues in E/App though https://expensify.slack.com/archives/C01GTK53T8Q/p1666112879921489?thread_ts=1665756926.532669&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment] 2022-10-24 16:33
Holding pending
https://github.com/Expensify/App/issues/11321#
which might be holding pending this PR
https://github.com/Expensify/App/pull/11684

**Comment by mallenexpensify** [comment] 2022-11-02 16:21
Nudged the issue that this might be be held on https://github.com/Expensify/App/issues/11321#issuecomment-1300817683

**Comment by mallenexpensify** [comment] 2022-11-09 02:17
Reassigning as I'm heading OOO for a month .

**Comment by strepanier03** [comment] 2022-11-11 01:46
Still held for now. Will check in Monday when I'm back online. 

I am out of the office tomorrow. If there is an urgent need on this GH from a BugZero team member, please post in #expensify-open-source for assistance.

**Comment by strepanier03** [comment] 2022-11-14 23:19
Following along [here](https://github.com/Expensify/App/issues/11321) for updates and a fix.

**Comment by strepanier03** [comment] 2022-11-16 03:13
Update expected by end fo the week.

**Comment by strepanier03** [comment] 2022-11-22 04:26
We're getting close, will check tomorrow, and then I'm out of the office Wednesday-Sunday.

**Comment by strepanier03** [comment] 2022-11-28 23:33
Looks like a fix is on staging, following along for the close of this [GH](https://github.com/Expensify/App/issues/11321#issuecomment-1328156491).

**Comment by strepanier03** [comment] 2022-12-02 01:43
The GH is closed. 

Going to attempt to recreate so I can confirm this issue is fixed.

**Comment by strepanier03** [comment] 2022-12-02 01:51
Hmmm the issue is still occurring for me. There is a 15k character limit for a message now.


Steps when testing:

Created a message of 15k characters,
Send it in desktop app,
Attempt to edit message,
The screen started jumping around my chat thread and I wasn't able to edit anything,
I attempted to delete the message and try again but when I did it resent the same message dozens of times,
I can't edit or delete any of the messages now,

I will try again next time I'm online. 

---- 

I am OoO for jury duty tomorrow. If immediate action is needed on this GH please post in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) for another BugZero's assistance, thank you.

**Comment by strepanier03** [comment] 2022-12-09 03:31
I didn't get back to this but will prioritize tomorrow.

**Comment by strepanier03** [comment] 2022-12-11 22:30
Tested this again today and it all worked out very well. I was able to paste 15k character message, edit it, and do so without experiencing issues.

**Comment by strepanier03** [comment] 2022-12-11 22:32
This is resolved now. I am closing as completed because it was reported before this GH was opened and fixed elsewhere.

**Closed by strepanier03** 2022-12-11 22:33 UTC
Labels: Weekly, Bug
