### ISSUE TITLE
[$250]  Mweb/Chrome - Scan receipt camera access permission reset

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53276] opened 2024-11-28 18:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.66-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/52880
**Email or phone of affected tester (no customers):** testpayment935+60@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com
2. Go to FAB > Submit expense > Scan
3. Allow the camera access
4. Navigate to manual  then back to Scan ( do this multiple times)

## Expected Result:
Scan receipt camera access permitted and open camera without an issue

## Actual Result:
Scan receipt camera access permission reset

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d221bf02-e4c1-45ee-94a6-5c69d6d7371b

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863571751448877888</li>
        <li>Upwork Job ID: 1863571751448877888</li>
        <li>Last Price Increase: 2024-12-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by mountiny** [comment] 2024-11-29 17:23
cc @rezkiy37 this seems to be related to your pr, can you please have a look?

**Comment by rezkiy37** [comment] 2024-11-29 19:09
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by twisterdotcom** [comment] 2024-12-02 14:20
@Julesssss is this expected? I think I've seen this in mobile browsers before that we ask consistently.

**Comment by Julesssss** [comment] 2024-12-02 14:43
@twisterdotcom not expected, we shouldn't be resetting the permission over and over. Once granted user should always see camera view.

**Comment by mountiny** [comment] 2024-12-03 12:58
Asked for a [retest](https://expensify.slack.com/archives/C9YU7BX5M/p1733230700776999?thread_ts=1733229205.242329&cid=C9YU7BX5M)

**Comment by izarutskaya** [comment] 2024-12-04 22:11
There is no access permission request ( https://github.com/Expensify/App/issues/51142) But after granted access switching tabs between Manual and Scan works fine. Issue not reproducible.

https://github.com/user-attachments/assets/b11b246e-122b-4155-b022-abbdeebf1fe6

**Comment by rezkiy37** [comment] 2024-12-05 09:59
So the issue is not replicable. Can we close it?

**Comment by Julesssss** [comment] 2024-12-05 10:00
> There is no access permission request ( https://github.com/Expensify/App/issues/51142)

I'm not sure this is the same issue. The permission flow is complex with many scenarios but you should be prompted for permission 1 time on iOS and two times on Android (assuming you have not done this previously). The tests should be ran on fresh installs I think to be completely accurate. 

However, it seems like this is no longer occurring, which is good. Lets close

**Closed** 2024-12-05 10:00 UTC
Labels: External, Daily, Overdue, Bug
