### ISSUE TITLE
[HOLD for payment 2022-06-15] [$250] Nothing happens when the google meet option is pressed on android - reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8851] opened 2022-05-02 06:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Press Start a call icon
3. Select Google Meet option

## Expected Result:
It should redirect to google meet

## Actual Result:
Nothing happens

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.57-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/166194330-820efc1d-6c9e-4107-9d5d-31eaefc88f26.mp4

**Upwork job URL:** https://www.upwork.com/jobs/~0141cfd04877737242
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649958629253299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2022-05-02 13:27
I don't have an Android device to test this. I asked @peterdbarkerUK to confirm the reproduction steps on his Pixel 6 and it redirects to Google Meet. 😕 

@adeel0202, did you try this with the Google Meet app installed to see if there's a different result?

**Comment by adeel0202** [comment] 2022-05-02 14:28
Just installed the Google Meet app and still, nothing happens when I tap the Google Meet option.

https://user-images.githubusercontent.com/13783842/166251384-492d7c3d-d5c0-4eba-a43b-2e070fd3b9e6.mp4

**Comment by trjExpensify** [comment] 2022-05-03 12:24
Alright, going to pass this over to `engineering` triage!

**Comment by tgolen** [comment] 2022-05-03 20:18
hm, works for me (ish) in the simulator. It should open up a browser and go to https://meet.google.com/new. I think it's not fully working in the simulator because I don't have the google meet app installed.

**Comment by AndrewGable** [comment] 2022-05-06 17:13
@Expensify/applauseleads - Can you reproduce this?

**Comment by isagoico** [comment] 2022-05-06 17:26
@AndrewGable Able to reproduce the issue in my device, Android 10 / Build 1.1.57-7

https://user-images.githubusercontent.com/44479856/167182005-bf347212-83f6-4ccc-854a-65d0890c4d78.mp4

**Comment by AndrewGable** [comment] 2022-05-06 19:51
@trjExpensify - Do you know if I applied the correct labels here? 🤔 - It seems like we are missing a C+.

**Comment by eVoloshchak** [comment] 2022-05-07 16:28
When you try to reproduce this in dev, it gives you the following warning:

![image](https://user-images.githubusercontent.com/9059945/167263041-ce2f89ac-288e-476e-b2c8-700108af3981.png)

**Proposal:**

1. Add
```xml
<uses-permission android:name="android.permission.CALL_PHONE"/>
```
to the list of permissions in [AndroidManifest.xml](https://github.com/Expensify/App/blob/main/android/app/src/main/AndroidManifest.xml)

2. Request permission on [this](https://github.com/Expensify/App/blob/724ccb46ca4b2f48f6052592cbacc7ffe9528c5c/src/components/VideoChatButtonAndMenu.js#L55) line in [VideoChatButtonAndMenu.js](https://github.com/Expensify/App/blob/main/src/components/VideoChatButtonAndMenu.js)
```javascript
  onPress: async () => {
      this.toggleVideoChatMenu();
      await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CALL_PHONE)
      Linking.openURL(CONST.NEW_GOOGLE_MEET_MEETING_URL);
  },
```

https://user-images.githubusercontent.com/9059945/167263004-eb4bab86-ca71-4cd6-89ac-17b4cb6e03c0.mp4

**Note:**
This is probably a good idea to show some kind of alert if user has denied the permission, what is the desired behaviour in this case?

**Comment by trjExpensify** [comment] 2022-05-09 11:46
>@trjExpensify - Do you know if I applied the correct labels here? 🤔 - It seems like we are missing a C+.

You're good. I hadn't taken this to Upwork yet to add the `Exported` label (which will assign C+ and `Help wanted`), but let me do that now that it has been reproduced.

**Comment by rushatgabhane** [comment] 2022-05-16 15:54
Sorry for getting to this so late, [I was OOO](https://expensify.slack.com/archives/C02NK2DQWUX/p1652282380139939?thread_ts=1652277963.845719&cid=C02NK2DQWUX).

Issue is not reproducible on v1.1.57-17, Android 12.

**Comment by eVoloshchak** [comment] 2022-05-16 16:27
@rushatgabhane 
> I can't repro this issue on v1.1.57-17, Android 12. Is this bug only for Android 11 and below??

Tested again with v1.1.57-17, here are the results

OnePlus6, Android 11 - reproducible
LG G7,  Android 10 - reproducible
Pixel 3a XL, Android 12 * - not reproducible
OnePlus 8T, Android 11 * - not reproducible
Pixel 6 Pro, Android 12 * - not reproducible
Pixel 3, Android 9 * - not reproducible

But, all of the devices marked with an asterisk are the devices I tested on Amazon's Device Farm. So i'm guessing this could be not about the OS version, but about the region, but this is only a guess

**Comment by rushatgabhane** [comment] 2022-05-17 18:44
@eVoloshchak I really appreciate the results you've posted! 
I'm still investigating and trying to find a source of truth (like official documentation).

**Comment by rushatgabhane** [comment] 2022-05-18 10:47
> https://meet.google.com/new and https://meet.google.com are just opening Google Meet application (see my previous video), and don't create a new meeting

@eVoloshchak A new meeting is created on web.

**Comment by eVoloshchak** [comment] 2022-05-18 10:54
> @eVoloshchak A new meeting is created on web.

Yup, I also observed that. When you were testing, was new meeting created on Android or did it just open google meet app?

**Comment by rushatgabhane** [comment] 2022-05-18 10:54
It just opened the meet app.

**Comment by rushatgabhane** [comment] 2022-05-18 10:55
I can't repro the issue at all. I tested on the following physical devices.
Pixel 6, Android 12
Pixel 3, Android 10, 11 and 12 (i sideloaded the firmware)
Samsung S8, Android 9 

@AndrewGable what do we do here? How about we wait for more proposals that point to the exact root cause?

**Comment by eVoloshchak** [comment] 2022-05-18 10:57
> It just opened the meet app.

In that case we can just change `https://meet.google.com/new` to `https://meet.google.com` for Android, the behaviur will stay the same but the permission isn't required.
But I argee, finding some proof of **why** it is that way is required

**Comment by AndrewGable** [comment] 2022-05-18 18:23
Kinda seems just like it's a quirk of Google's app, which we probably won't ever get to the bottom of. I think the high level solution sounds solid, but let's update the proposal to include all the changes required.

**Comment by eVoloshchak** [comment] 2022-05-18 18:36
**Updated proposal:**
1. Add `GOOGLE_MEET_APP_URL: 'https://meet.google.com'` to [CONST.js](https://github.com/Expensify/App/blob/main/src/CONST.js)
2. In `src/components` create a folder called `VideoChatButtonAndMenu`, move [VideoChatButtonAndMenu.js](https://github.com/Expensify/App/blob/main/src/components/VideoChatButtonAndMenu.js) into it and rename it to `index.js`
3. In that same folder create a file called `getGoogleMeetUrl.js` with the following contents:
```javascript
export default function getGoogleMeetUrl() {
    return CONST.NEW_GOOGLE_MEET_MEETING_URL;
}
```
4. Create a file called `getGoogleMeetUrl.android.js`
```javascript
export default function getGoogleMeetUrl() {
    return CONST.GOOGLE_MEET_APP_URL;
}
```
5. Replace [this](https://github.com/Expensify/App/blob/5096dea4e6bbeb6203df3ae8c896f282bf570e66/src/components/VideoChatButtonAndMenu.js#L56) line with `Linking.openURL(getGoogleMeetUrl());`

**Comment by rushatgabhane** [comment] 2022-05-18 19:09
@eVoloshchak I believe we don't follow that pattern for components. It should look something more like this
- BaseComponent
- index.js
- index.android.js

eg: [Modal component](https://github.com/Expensify/App/tree/main/src/components/Modal)

**Comment by rushatgabhane** [comment] 2022-05-18 19:10
🎀 👀 🎀 C+ reviewed

We're gonna be using https://meet.google.com for android and https://meet.google.com/new for all other platforms.
I can't repro the bug on any of my devices, but @eVoloshchak has tested it out. Let's do this!

cc: @AndrewGable

**Comment by AndrewGable** [comment] 2022-05-18 19:14
Let's do it!

**Comment by eVoloshchak** [comment] 2022-05-18 19:18
> @eVoloshchak I believe we don't follow that pattern for components. It should look something more like this
> 
> * BaseComponent
> * index.js
> * index.android.js

Got it, thanks
>Please make sure to add a comment for Android and add a link to your investigation.

Will do
>Also, `GOOGLE_MEET_URL_ANDROID` seems like a better name. What do you think?

Yes, I agree, will use that instead

I applied for the job on Upwork, will submit a PR in ~2 days

**Comment by trjExpensify** [comment] 2022-05-18 20:00
Sent the offer! 👍

**Comment by trjExpensify** [comment] 2022-05-23 09:39
👋 @eVoloshchak any luck with submitting that PR?

**Comment by eVoloshchak** [comment] 2022-05-26 19:56
Sorry for the delay, [PR](https://github.com/Expensify/App/pull/9193) is up

**Comment by rushatgabhane** [comment] 2022-06-05 18:25
Hello, #9193 caused some [console errors](https://github.com/Expensify/App/pull/9193#issuecomment-1146778920).

I've raised PR #9315 to fix them.
@trjExpensify please note that this is a regression.

**Comment by trjExpensify** [comment] 2022-06-06 12:09
Cool, thanks @rushatgabhane. 👍

**Comment by trjExpensify** [comment] 2022-06-15 15:55
@eVoloshchak, I've paid you for this. 

@rushatgabhane & @adeel0202 I need you both to accept the offers to settle up here.

**Comment by trjExpensify** [comment] 2022-06-15 15:58
Okay, @adeel0202 done! I'll close it out once @rushatgabhane accepts the C+ offer.

**Comment by trjExpensify** [comment] 2022-06-15 15:59
All set here, closing!

**Closed by trjExpensify** 2022-06-15 15:59 UTC
Labels: Exported, External, Engineering, Daily, Improvement, Awaiting Payment
