### ISSUE TITLE
Tooltip doesn't resize itself after copying Email/Phone No - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9409] opened 2022-06-13 03:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Desktop Website/App
2. Chat > Details
3. Copy Email/Phone no.

## Expected Result:
There shouldn't be extra space.

## Actual Result:
Tooltip doesn't resize itself after copying Email/Phone No.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.75-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/173275765-1a9c3a56-5476-4a24-b98e-8eaff438eadc.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652971168939839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment] 2022-06-13 05:35
Dupe of https://github.com/Expensify/App/issues/9331

**Comment by mananjadhav** [comment] 2022-06-15 06:01
> Dupe of https://github.com/Expensify/App/issues/9331

@mvtglobally @muttmuure We're good to close this one as its a duplicate and being tracked there.

**Closed** 2022-06-15 14:10 UTC
Labels: Daily, Overdue
