### ISSUE TITLE
[HOLD for payment 2023-07-17] [HOLD for payment 2023-07-14] [$1000]  Task thread gets hidden when clicking on other chats

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22300] opened 2023-07-05 19:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB > Assign task > Give title > Click next > Click on Assignee > select a user > Click Confirm task
2. While task thread is open click on other chats
## Expected Result: 
Task thread should not disappear
## Actual Result: 
Task thread disappears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.37-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4c3f6a49-0afc-43b7-bedb-173dfe464d06

https://github.com/Expensify/App/assets/43996225/0ecd1f21-19f5-40a5-8854-1e6328650e11

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1688585231083709
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0172c3507dab16a468</li>
        <li>Upwork Job ID: 1677064497764429824</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-06 10:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task thread gets hidden when clicking on other chats.

### What is the root cause of that problem?
The root cause is that task thread have a empty `lastMessageText`, so `ReportUtils.shouldReportBeInOptionList` returns false, and then gets hidden in LHN.
https://github.com/Expensify/App/blob/197cf7dd27431bf665e2c0b9aa0dabbb3d5465f8/src/libs/ReportUtils.js#L2021-L2024

### What changes do you think we should make in order to solve the problem?
We can change above code as below.
```js
-   if (isThread(report) && !report.lastMessageText) {
+   if (isThread(report) && !isTaskReport(report) && !report.lastMessageText) {
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by Li357** [comment] 2023-07-06 14:32
Thanks @StevenKKC -- I don't we should hide any actionable items either, such as IOUs, expenses, etc. So we should only hide 1:1s, group chats, and threads that haven't been commented on. Since this is also a deploy blocker, can you get a PR in by EoD? If not, I'll pick this up.

**Comment by Li357** [comment] 2023-07-06 15:10
Seems like @jeet-dhandha did propose first. Since this is a deploy blocker I'm going to go ahead and do the fix myself.

**Comment by Julesssss** [comment] 2023-07-06 15:16
The proposal makes sense to me, but I'm curious why this was only a recent regression. Nothing from [yesterday's checklist ](https://github.com/Expensify/App/issues/22282)seems like an obvious cause for this issue 😕

**Comment by jeet-dhandha** [comment] 2023-07-06 15:22
@Li357 should i do anything ?

**Comment by Li357** [comment] 2023-07-06 15:27
No, we'll handle this internally since it involves fixing this not just for tasks

**Comment by jeet-dhandha** [comment] 2023-07-06 15:31
Sure 👌

**Comment by kevinksullivan** [comment] 2023-07-06 21:18
Adding external label for upwork automation

**Comment by kevinksullivan** [comment] 2023-07-06 21:23
Sent offers to @allroundexperts for PR review and @Nathan-Mulugeta for reporting

**Comment by jeet-dhandha** [comment] 2023-07-07 02:47
@kevinksullivan If this was external shouldn't we get a compensation for proposing first ?

https://github.com/Expensify/App/issues/22294

**Comment by conorpendergrast** [comment] 2023-07-07 09:17
Not sure why I got assigned here too, unassigning myself!

**Comment by anmurali** [comment] 2023-07-11 15:22
@allroundexperts - paid

**Comment by Nathan-Mulugeta** [comment] 2023-07-11 19:25
Hey @anmurali are payments being processed early?

**Comment by Nathan-Mulugeta** [comment] 2023-07-13 10:54
Hey guys when is this report's Payment going to be processed? I am seeing two hold for payments on the title. @kevinksullivan

**Comment by kevinksullivan** [comment] 2023-07-17 15:37
Paid @Nathan-Mulugeta

**Comment by kevinksullivan** [comment] 2023-07-17 15:37
>should i be issuing a reporting bonus on my issue? is a second reporting bonus, the Contributor and C+ payments being processed via this issue?

That seems to be a duplicate of this GH @maddylewis . Does the problem still exist now that this has deployed?

**Closed by kevinksullivan** 2023-07-17 15:37 UTC
Labels: Engineering, Daily, Help Wanted, Awaiting Payment, Bug

**Comment by esh-g** [comment] 2023-07-17 17:33
@kevinksullivan @maddylewis Sorry for the late reply but that issue was opened 44 mins before this issue. I think this would be the dupe. I'm sorry I didn't notice it before

**Comment by maddylewis** [comment] 2023-07-17 18:59
ok ok word - ty for clarifying, all 👍
