### ISSUE TITLE
[Payment due][$1000] Room - Side panel does not close when clicking outside of panel

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34394] opened 2024-01-11 21:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click on FAB > Start chat > room > workspace
2. Click outside of the side panel

## Expected Result:
Side panel should close as it does when clicking on outside of the panel anywhere in the app

## Actual Result:
Side panel stays open but navigates one step back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5a12ad18-b438-4b90-92c0-a1153b5391bb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ab450f9ef4bcadd</li>
        <li>Upwork Job ID: 1745558199758635008</li>
        <li>Last Price Increase: 2024-02-21</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28104675</li>
<li>neonbhai | Contributor | 28104676</li>
<li>Krishna2323 | Contributor | 28142924</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by yuetong3yu** [comment] 2024-01-11 23:58
Feel like it's expected instead a bug.

**Comment by yuetong3yu** [comment] 2024-01-12 00:10
Contributor details
Your Expensify account email: yuetong3yu@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019f5d35fda67374fb

**Comment by kadiealexander** [comment] 2024-01-16 05:30
@danieldoglas bump!

**Comment by danieldoglas** [comment] 2024-01-16 19:33
Thanks for the discussion here.

Though I agree @Krishna2323 proposals would also solve the issue, I think that @neonbhai's proposal follows the practices we've implemented in other places already.

**Comment by danieldoglas** [comment] 2024-01-16 19:47
@neonbhai let's wait for @mountiny opinions since he was the one that participated the most in that implementation.

But I think we should implement the route to be consistent with what we did in other selectors.

**Comment by mountiny** [comment] 2024-01-16 23:53
Sorry for the tagging game but i was merely re reverting a pr which had to be reverted there i think it was @dangrous who worked on that one, so i am not sure about the discussions about this design

I would personally expect that this will have its own route because thats how we implement almost everything except could exceptions

That change would however not have to be in scope of this pr

**Comment by mountiny** [comment] 2024-01-16 23:54
Like this is same as picking an assignee for a task for example, do we have a route there? I think we do

**Comment by dangrous** [comment] 2024-01-17 16:41
Hi! So the component definitely wasn't planned to have its own route BUT I don't think we really discussed it - the conception of it came out of discussion with Shawn, so we were mostly thinking about the (visual) design of the picker rather than route or not route. For internal folks - [here's](https://expensify.slack.com/archives/C05RECHFBEW/p1695176727382349?thread_ts=1695081351.878289&cid=C05RECHFBEW) the Slack discussion. So, I think if adding a route to it would match our patterns better, I think we can probably do that?

**Comment by mountiny** [comment] 2024-01-18 02:36
Yep I think we should do it, although not sure about the complexity given this needs to be reusable component.

**Comment by danieldoglas** [comment] 2024-01-22 20:26
bump @neonbhai

**Comment by danieldoglas** [comment] 2024-02-01 15:35
Ok, if we don't have any feedbacks from @neonbhai until next Monday, let's make this issue available again.

**Comment by danieldoglas** [comment] 2024-02-05 15:56
I'm sorry for your loss @neonbhai.

**Comment by danieldoglas** [comment] 2024-02-05 15:56
Assigning @Krishna2323, let's follow the proposal that was discussed here before. Thanks!

**Comment by danieldoglas** [comment] 2024-02-21 21:42
Hi @Krishna2323 . OK, I think it's fair considering we increased the scope.

**Comment by danieldoglas** [comment] 2024-02-27 13:12
@dangrous is now OOO, let's also ask @roryabraham since he decided to close the issue mentioned. @roryabraham do you think we should not implement routes as we're doing in other places?

**Comment by danieldoglas** [comment] 2024-02-29 12:48
@hoangzinh between the 3 options on the original proposal from @Krishna2323 , which one do you think would be the best going forward?

**Comment by danieldoglas** [comment] 2024-03-06 13:03
@Krishna2323 let's move on with your proposal, option 1.

**Comment by CortneyOfstad** [comment] 2024-03-20 15:38
@kadiealexander There is a regression for this issue [here](https://github.com/Expensify/App/issues/38665) — just giving you a heads up 👍

**Comment by danieldoglas** [comment] 2024-04-01 16:34
Reached production last week, soon it will be ready for payment.

**Comment by kadiealexander** [comment] 2024-05-15 21:47
Since there was a regression, reducing the payment by 50% as per [the contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). 

Payouts due:

- [ ] Contributor: $500 @Krishna2323
- [ ] Contributor+: $500 @hoangzinh

Upwork job is [here]().

**Comment by kadiealexander** [comment] 2024-05-15 22:29
@danieldoglas I'll let you decide if the regression penalty should apply here, as I don't have the technical understanding to know if the regression was true.

**Comment by danieldoglas** [comment] 2024-05-17 11:32
I agree we can't skip the reduction because of the effort applied.

**Comment by kadiealexander** [comment] 2024-05-20 05:37
Thanks Daniel!

**Closed by kadiealexander** 2024-05-20 05:37 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
