### ISSUE TITLE
[PAID] [$1000] Bug: Tooltip gets stuck on the page reported by @Puneet-here

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12025] opened 2022-10-20 00:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Decrease the screen size
2. Hover over any contact at chat navigator
3. When the tooltip appears open the chat
4. Hover at back button until the tooltip shows up then press back

## Expected Result:
The tooltip should go away

## Actual Result:
The tooltip should doesn't go away

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/196830711-438ca9f7-1bbd-44df-80a2-3bf7e0b9ff01.mp4
https://user-images.githubusercontent.com/43996225/196830700-9a924829-e70f-4121-bd50-80e148d1fc91.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666210802145239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment] 2022-10-20 14:14
looks like a solid external @chiragsalian ? can you do the honours pls :)

**Comment by chiragsalian** [comment] 2022-10-20 18:20
Yup, adding label.

**Comment by laurenreidexpensify** [comment] 2022-10-21 13:37
https://www.upwork.com/jobs/~01a51c9760a2d3a8c8

**Comment by laurenreidexpensify** [comment] 2022-10-26 10:05
not overdue, still looking for proposals

**Comment by laurenreidexpensify** [comment] 2022-10-31 11:00
Price increased to $500

**Comment by mmarceau** [comment] 2022-11-04 21:13
@rushatgabhane Let me first explain that I'm new here and I'm learning so I apologize ahead of time if I'm wrong. I looked at @Ollyws code and tested it locally. It does work for me. I'm not sure exactly how it could lead to a race condition like you suggested. Since `setState` is always called now and not wrapped in a conditional, it seems like a solid solution so I'm wondering what I am missing here. Thanks!

**Comment by laurenreidexpensify** [comment] 2022-11-07 13:13
Bumped in Slack https://expensify.slack.com/archives/C01GTK53T8Q/p1667826775048499?thread_ts=1666210802.145239&cid=C01GTK53T8Q and set price to $1000

**Comment by laurenreidexpensify** [comment] 2022-11-07 13:14
@mmarceau @Ollyws any further ideas yet?

**Comment by getusha** [comment] 2022-11-07 14:41
It is quite interesting to see this detailed comment
https://github.com/Expensify/App/blob/c02031489b46200f95d19bfda1e0c048cb99bb45/src/components/Hoverable/index.js#L62-L67
What do we miss?
https://github.com/Expensify/App/blob/c02031489b46200f95d19bfda1e0c048cb99bb45/src/components/Tooltip/index.js#L187-L192
```diff
+ resetsOnClickOutside={true}
```

https://github.com/Expensify/App/blob/c02031489b46200f95d19bfda1e0c048cb99bb45/src/components/Hoverable/index.js#L71-L78

```diff
-     if (this.wrapperView && !this.wrapperView.contains(event.target) && this.props.resetsOnClickOutside) { 
-         this.setIsHovered(false); 
-     } 
+        if ((this.wrapperView && !this.wrapperView.contains(event.target)) || this.props.resetsOnClickOutside) {
+           this.setIsHovered(false);
+       }
```

Result

https://user-images.githubusercontent.com/75031127/200337163-1ef1fbc0-f5ff-4986-807a-d22cadc27c75.mp4

**Comment by chiragsalian** [comment] 2022-11-08 19:15
Nice proposal, LGTM as well. Feel free to create the PR @getusha.

**Comment by getusha** [comment] 2022-11-08 19:26
Thank you @chiragsalian @rushatgabhane for assigning me.
I will apply for the job on upwork now. the price is not up to date on UW hope it will get updated soon.

**Comment by getusha** [comment] 2022-11-08 20:25
Applied.
Will submit the PR in short.

**Comment by laurenreidexpensify** [comment] 2022-11-09 13:37
Offers out in Upwork for everyone with correct pricing

**Comment by getusha** [comment] 2022-11-09 13:42
@laurenreidexpensify Thanks Accepted.

**Comment by JmillsExpensify** [comment] 2022-11-11 18:27
@laurenreidexpensify Wanted to make sure you have visibility on the regression in the linked PR. Let's wait for that to play out until the BZ checklist is filled out.

**Comment by parasharrajat** [comment] 2022-11-11 21:36
Caused this regression https://github.com/Expensify/App/issues/12685.

**Comment by laurenreidexpensify** [comment] 2022-11-16 15:20
Updated BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@chiragsalian @rushatgabhane] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@chiragsalian @rushatgabhane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@chiragsalian @rushatgabhane]  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@laurenreidexpensify] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:
- [ ] [@laurenreidexpensify] Applicable payments have been made. This potentially includes the issue reporter, the contributor that fixed the issue, and/or the contributor+ that helped on the issue.

**Comment by laurenreidexpensify** [comment] 2022-11-23 16:13
@chiragsalian @rushatgabhane can you link the PR you think caused the regression in the comment above? Thanks

**Comment by laurenreidexpensify** [comment] 2022-11-23 16:20
Regression test buddy check here https://expensify.slack.com/archives/C01SKUP7QR0/p1669220417075829

**Comment by chiragsalian** [comment] 2022-11-23 22:12
Updated the first two. Not sure what to do about the third. It was discussed on slack and not in expensify-bugs. So should we start a discussion in #expensify-bugs?

**Comment by laurenreidexpensify** [comment] 2022-11-24 11:11
@Puneet-here @rushatgabhane @getusha payment has been issued in Upwork 👍

**Comment by getusha** [comment] 2022-11-24 11:14
PR merged within 3 business days. so we're eligible for the 50% bonus?

**Comment by laurenreidexpensify** [comment] 2022-11-25 11:12
@getusha @rushatgabhane bonus sent 👍🏽

**Closed** 2022-11-25 11:18 UTC
Labels: Reviewing, External, Engineering, Daily, Bug

**Comment by situchan** [comment] 2023-01-20 16:45
It doesn't seem that #12572 fixed the issue completely. Issue reported again https://github.com/Expensify/App/issues/13947

**Comment by getusha** [comment] 2023-01-20 16:50
@situchan this approach was overwritten here https://github.com/Expensify/App/issues/13146
