### ISSUE TITLE
Task - Unassigned user can mark a task as incomplete

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49301] opened 2024-09-16 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/47519
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. [User A] Go to a DM with user B
2. [User A] Assign task to yourself
3. [User A] Mark it as complete
4. [User B] Open the task detail report
5. [User B] Click on header
6. [User B] Click Mark as incomplete button

## Expected Result:
There shouldn't be 'Mark as complete button'

## Actual Result:
Task is marked as uncompleted

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0b35dd29-e6c3-41d3-bf51-115f0be170ee

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-16 20:59
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment] 2024-09-16 21:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - Unassigned user can mark a task as incomplete
### What is the root cause of that problem?
In ReportDetails page, we are not checking if the current user is assignee or task owner before we are adding mark as incomplete action to menuItems
https://github.com/Expensify/App/blob/6eb93964edb5e0013a4ee26331a0f619aba59f3f/src/pages/ReportDetailsPage.tsx#L369-L374
### What changes do you think we should make in order to solve the problem?
We should check if the user is task assignee or task owner using `Task.canActionTask`
```
const canActionTask = Task.canActionTask(report, session?.accountID ?? -1);
```
```
 if (ReportUtils.isCompletedTaskReport(report) && canModifyTask && canActionTask)
```
### What alternative solutions did you explore? (Optional)

**Comment by CortneyOfstad** [comment] 2024-09-18 15:27
We need to have a fall back in case a task is marked as complete by accident, giving someone the ability undo that (i.e. mark as incomplete). 

The second person should have this option (especially if they are an admin on the default workspace), which these instructions are missing as a pre-requisite or not. 

Closing!

**Closed by CortneyOfstad** 2024-09-18 15:27 UTC
Labels: Daily, Bug
