### ISSUE TITLE
IOS - App crashes while tapping on start over option for connecting bank account - @aswin-s

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10621] opened 2022-08-29 02:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to workspace settings and select connect to bank account.
2.  Tap on start over option

## Expected Result:
App doesn’t crash

## Actual Result:
IOS -  App closes abruptly.
On Desktop - Nothing happens 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Desktop App

**Version Number:** 1.1.91-0
**Reproducible in staging?:** Y
**Reproducible in production?: ** Need repro due to PROD KYC
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/187700907-910ad4d9-7194-473f-b55b-0e5b81b6d104.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aswin-s
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660073873432529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment] 2022-08-29 12:34
Hey @mvtglobally I don't understand the reproduction steps - they aren't clear enough for me to test. Please can you add a video recording to your issue and more detail on the exact steps taken?

**Comment by zanyrenney** [comment] 2022-08-30 12:25
bump @mvtglobally thanks!

**Comment by zanyrenney** [comment] 2022-08-31 14:06
bumping @mvtglobally

**Comment by mvtglobally** [comment] 2022-08-31 14:16
@zanyrenney 
Start adding bank account, don't finish setup and navigate away 

Later come back to the bank setup flow again, you'll see "start over" button. Click on it

**Comment by zanyrenney** [comment] 2022-08-31 14:16
Can you add screenshots or a video recording please?

**Comment by zanyrenney** [comment] 2022-08-31 14:16
Let's reopen when they are added.

**Comment by mvtglobally** [comment] 2022-08-31 14:19
Slack conversation: https://expensify.slack.com/archives/C01GTK53T8Q/p1660073873432529

**Comment by mvtglobally** [comment] 2022-08-31 14:20
This is on Desktop.. 
![Screen Shot 2022-08-31 at 10 20 26 AM](https://user-images.githubusercontent.com/43995119/187701757-fa1eb2c1-977c-4bb9-b226-7d84a825afa4.png)

**Comment by puneetlath** [comment] 2022-09-06 15:19
Hm, I'm not able to reproduce this. Are you @zanyrenney?

**Comment by zanyrenney** [comment] 2022-09-08 10:40
Replied in Slack, my newdot being funky.

**Comment by puneetlath** [comment] 2022-09-20 21:05
Looks like this is a dupe of https://github.com/Expensify/App/issues/10233 so closing.

**Closed by puneetlath** 2022-09-20 21:05 UTC
Labels: Engineering, Daily, Overdue
