### ISSUE TITLE
[$250] Key Navigation - Pressing CTRL+K in attachment and closing search, leads to different chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48113] opened 2024-08-27 18:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4891152&group_by=cases:section_id&group_order=asc&group_id=229066
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the staging.new.expensify website
2. Open any chat in which an attachment was sent
3. Click the attachment to open preview modal
4. Press CTRL+K to open search page
5. Dismiss the opened search page
6. Verify if you are redirected to the correct chat

## Expected Result:
When the user opens the preview modal of an attachment in any chat, presses CTRL+K and closes the search page, the website should return to the same chat where the user was in

## Actual Result:
After the user opens the preview modal of an attachment in any chat, presses CTRL+K and closes the search page, is redirected to a different chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3db4ac96-4a3d-4e9d-8e90-f5180e3f55b7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01212d967034d02032</li>
        <li>Upwork Job ID: 1829648537564304374</li>
        <li>Last Price Increase: 2024-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 104123548</li>
<li>FitseTLT | Contributor | 104123550</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by lanitochka17** [comment] 2024-08-27 18:54
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-08-27 20:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Key Navigation - Pressing CTRL+K in attachment and closing search, leads to different chat

### What is the root cause of that problem?
When press the shortcut key Modal.close will be called here
https://github.com/Expensify/App/blob/e32430cf15b3fcdf35e8d43f82c027fea50c20d3/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L308
This will call the modal onClose here
https://github.com/Expensify/App/blob/e32430cf15b3fcdf35e8d43f82c027fea50c20d3/src/libs/actions/Modal.ts#L29-L37
the onModalClose in this case is this
https://github.com/Expensify/App/blob/e32430cf15b3fcdf35e8d43f82c027fea50c20d3/src/pages/home/report/ReportAttachments.tsx#L41-L44
Which `dismissModal` and it will pop the report attachment modal route but this `onModalClose` will be called again via `onModalDidClose` (because the modal itself calls the `onModalDidClose` on its `onModalHide`) here 
https://github.com/Expensify/App/blob/e32430cf15b3fcdf35e8d43f82c027fea50c20d3/src/libs/actions/Modal.ts#L52-L57
so another pop on the route will navigate the user to another report
### What changes do you think we should make in order to solve the problem?

In `closeTop` here, we need to pop the last `closeModals` becasue there is no need we will call the onClose of the topmost modal again after it is called  here
https://github.com/Expensify/App/blob/e32430cf15b3fcdf35e8d43f82c027fea50c20d3/src/libs/actions/Modal.ts#L28-L37
```
    if (onModalClose) {
        closeModals[closeModals.length - 1](isNavigate);
        closeModals.pop();
        return;
    }
    closeModals[closeModals.length - 1]();
    closeModals.pop();
```
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2024-09-04 05:42
@FitseTLT Could you reproduce this issue anymore?

**Comment by FitseTLT** [comment] 2024-09-04 11:45
@DylanDylann The reason you are not reproducing it for report attachment is because of this [pr](https://github.com/Expensify/App/pull/47622) which tried to solve the same problem with wrong RCA and wrong solution. So instead of solving the issue from the root cause they applied a partial fix to report attachment so the problem still exists for other modals such as receipt attachment (Transaction Receipt), here is a video:
the page navigates back from transaction details page to the iou report page when CTRL+K, so I suggest we revert that fix and apply the right fix that [solves](https://github.com/Expensify/App/issues/48113#issuecomment-2313485082) problem from the root cause.


https://github.com/user-attachments/assets/7f9def89-e53c-4394-bbef-4f3e5dd326ca

**Comment by DylanDylann** [comment] 2024-09-10 01:33
On my list today

**Comment by DylanDylann** [comment] 2024-09-10 07:40
@kevinksullivan I think this should be handled in https://github.com/Expensify/App/issues/46388 I added a [comment](https://github.com/Expensify/App/issues/46388#issuecomment-2339902916) to the original issue. We can close this one

**Comment by FitseTLT** [comment] 2024-09-10 09:32
@DylanDylann the [issue](https://github.com/Expensify/App/issues/46388) is payedout/closed and way past its regression period, how is that suppose to be handled there while I have found the correct root cause and solution here.

CC @kevinksullivan

**Comment by thienlnam** [comment] 2024-09-11 18:12
@dominictb / @allgandalf Can you comment on the proposal? Ideally, if this can resolve all cases - we should undo the fix and have this fixed universally

**Comment by kevinksullivan** [comment] 2024-09-11 21:56
Agree with @thienlnam that it's worth addressing the broader issue if we can.

**Comment by kevinksullivan** [comment] 2024-09-11 21:56
Also going OOO so I'm looping in another BZ

**Comment by CortneyOfstad** [comment] 2024-09-17 17:41
Sorry, was OoO myself when this was assigned!

**Comment by CortneyOfstad** [comment] 2024-09-17 17:43
@DylanDylann where are we at with this?

**Comment by DylanDylann** [comment] 2024-09-18 07:07
@dominictb @allgandalf Bump on this comment: https://github.com/Expensify/App/issues/48113#issuecomment-2344360516

**Comment by DylanDylann** [comment] 2024-09-18 09:21
@allgandalf Here: https://github.com/Expensify/App/issues/48113#issuecomment-2328734043 Please help to check

**Comment by DylanDylann** [comment] 2024-09-20 08:08
@allgandalf @dominictb Thanks for your response. Hmm, I think we will handle the new bug that @FitseTLT mentioned separately in this issue. It is hard to say this is a regression from the previous PR because this bug is in another place and isn't known at that time. The previous issue also be closed 2 weeks ago.

I will review @FitseTLT's proposal and handle this as a new issue

**Comment by DylanDylann** [comment] 2024-09-24 05:15
@dominictb Would you like to post your proposal to fix this bug globally on this issue? It looks promising

**Comment by DylanDylann** [comment] 2024-09-24 09:41
@FitseTLT The same bug still happen when reloading page

https://github.com/user-attachments/assets/1ecc4e7a-3ab8-4678-a27f-ad2b0690d81f

**Comment by FitseTLT** [comment] 2024-09-24 12:30
> @FitseTLT The same bug still happen when reloading page
> 
>  Screen.Recording.2024-09-24.at.16.40.04.mov

@DylanDylann What you found here is a totally different bug that is not occuring because onMOdalHide is being called twice as the main bug here but it is caused by `Navigation.goBack` being called without fallbackRoute because we haven't passed `shouldEnforceFallback` true. We have options to solve this 
1. We can use dismissModal with report id here
https://github.com/Expensify/App/blob/a99cf941a355a412e7498c41a69a99b01e35431c/src/pages/TransactionReceiptPage.tsx#L68
```
                Navigation.dismissModal(report?.reportID ?? '-1');

```
Because dismissModal correctly handles the case of transaction receipt page here ( and also dismissModal is the most appropriate as we are dismissing a modal)
https://github.com/Expensify/App/blob/a99cf941a355a412e7498c41a69a99b01e35431c/src/libs/Navigation/dismissModalWithReport.ts#L42
2. We can also pass shouldEnforceFallback to goBack
```
                Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(report?.reportID ?? '-1'), true);

```

**Comment by DylanDylann** [comment] 2024-09-25 04:47
Let's go with @FitseTLT's [proposal](https://github.com/Expensify/App/issues/48113#issuecomment-2313485082). Please include the change to address [this bug](https://github.com/Expensify/App/issues/48113#issuecomment-2370785961) 

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-10-08 08:36
@CortneyOfstad This is ready for payment. The PR is deployed to production on 1/10

**Comment by CortneyOfstad** [comment] 2024-10-09 13:56
## Payment Summary

@DylanDylann — paid $250 via Upwork
@FitseTLT — pid $250 via Upwork

**Closed by CortneyOfstad** 2024-10-09 13:56 UTC
Labels: Reviewing, External, Weekly, Bug
