### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Web - 'Find a member' doesn't update dynamically on the placeholder

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21061] opened 2023-06-19 17:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go to staging dot on web chrome
2. Go to any workspace
3. Go to invite members and notice that when the search field is not focused, the 'Find a member' is shown on the placeholder
4. But if you click on the search field, the 'Find a member' goes on top allowing users to input the text on the search field
5. Now invite some members
6. Now,  search the member using the initials of one invited member
7. Click on select all and now remove the user
8. Next click on invite button on top and then click on go back to return to the list of users
9. Notice that now, even when the search field is not focused , the 'Find a member' is shown at the top (In previous cases -step 3 and 4, 'Find a member' was shown on top only when the search field was focused). If you refresh the page you can notice that the 'Find a member' is updated in the placeholder of the search field now.

## Expected Result:
'Find a member' should be update dynamically on the placeholder

## Actual Result:
 'Find a member' doesn't update dynamically on the placeholder

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yrs

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/03f6a718-c58c-4822-93e3-c14b20cd3e5c

https://github.com/Expensify/App/assets/93399543/d5a34fc6-f59f-4988-92df-e6b195d036d6

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686466494275769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2b58955cd2caa4f</li>
        <li>Upwork Job ID: 1671383734343749632</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2023-06-20 07:26
I have posted my proposal here https://github.com/Expensify/App/issues/19231#issuecomment-1555898904, so copying it here

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Text input label does not deactivate (move back as the placeholder) when we clear the input value. To reproduce it, make sure type something first.

### What is the root cause of that problem?
Actually, we already have the code that SHOULD deactivate the label when we clear the input value here:
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/TextInput/BaseTextInput.js#L71-L89

As you can see, we update the `value` state with `inputValue` and call `deactivateLabel` if `inputValue` is empty. Then, inside `deactivateLabel`, we check if the state of `value` is empty or not. 
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/TextInput/BaseTextInput.js#L164-L171

If it's empty, then we proceed to deactivate the label. The problem is, the `value` state is not updated yet inside `deactivateLabel`, which is basically a race condition.

### What changes do you think we should make in order to solve the problem?

Call the `deactivateLabel` inside the `setState` callback.

More specific, move this code to be inside the `setState` callback.
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/TextInput/BaseTextInput.js#L85-L89

I guess we also can change `inputValue` to `this.state.value` instead.

**Result**

https://github.com/Expensify/App/assets/50919443/1ddc61e5-9f65-465c-a202-9fe608ea0f3e

**Comment by JmillsExpensify** [comment] 2023-06-21 05:05
While we expect to overhaul this entire flow soon, I'm going to go ahead and triage. I also wasn't able to reproduce on either Safari or desktop.

**Comment by teguhkurnia** [comment] 2023-06-26 04:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
'Find a member' doesn't update dynamically on the placeholder

### What is the root cause of that problem?
The root of this problem is that the `setState` function doesn't update the state immediately, because the setState is Asynchronous

In your code, you called the `deactivateLabel()` function immediately after the setState function, but inside the `deactivateLabel()` function you have an if statement that has checked the `this.state.value.length !== 0`.

As I said before value state is not changed yet in this case. So if you check the value immediately after the `setState` is called the value is the same as before.


### What changes do you think we should make in order to solve the problem?
`setState` function has a callback argument, that callback argument is called if the state has already changed, so we can call the `deactivateLabel()` function inside the callback argument.


### What alternative solutions did you explore? (Optional)
Or, we can add an argument to the `deactivateLabel()` function that is the changed input value in your case is `inputValue` variable, so`deactivateLabel(inputValue)`. 
and on the `deactivateLabel()` function we can check the input value not from the state, but from the argument

**Comment by teguhkurnia** [comment] 2023-06-26 04:16
Contributor details
Your Expensify account email: vayim63018@byorby.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016b08cfd1ddef1a1a

**Comment by sobitneupane** [comment] 2023-06-26 08:49
Discussion: https://expensify.slack.com/archives/C02NK2DQWUX/p1687769287412449

**Comment by sobitneupane** [comment] 2023-06-27 04:59
This issue is almost same as [this issue](https://github.com/Expensify/App/issues/19231) where @bernhardoj had proposed https://github.com/Expensify/App/issues/19231#issuecomment-1555898904 solution. It solves the issue. But for consistency we decided to change the requirement of that issue. So, considering this issue just the extension of https://github.com/Expensify/App/issues/19231. We have decided to go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/21061#issuecomment-1598258415).

🎀 👀 🎀 C+ reviewed

**Comment by johnmlee101** [comment] 2023-06-27 19:22
Makes sense to me.

**Comment by bernhardoj** [comment] 2023-06-28 05:24
PR is ready.

cc: @sobitneupane

**Comment by sobitneupane** [comment] 2023-07-10 08:38
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/9056
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/9056/files#r1257910704
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1688978277278329
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-07-10 08:40
**Regression Test Proposal**

1. Go to Settings > Workspaces > Select any workspace > Members
2. In the "Find a member" input, type something
3. Verify the "Find a member" label moves up
4. Press the Invite button
5. Go back by pressing back button
6. Verify the input is cleared and "Find a member" label moves back to its original position

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-07-10 09:13
Payment Requested on Expensify

**Comment by JmillsExpensify** [comment] 2023-07-24 22:33
Circling back on this now.

**Comment by JmillsExpensify** [comment] 2023-07-24 22:36
@bernhardoj I sent you an offer via Upwork. I'll pay the bonus when closing out the contract. Thanks!

**Comment by JmillsExpensify** [comment] 2023-07-25 04:43
All paid out, including the bonus. Still need to create the issue for TestRail, so I'll do that before closing this one out.

**Comment by JmillsExpensify** [comment] 2023-07-26 04:01
Test created. Closing this one.

**Closed by JmillsExpensify** 2023-07-26 04:01 UTC
Labels: External, Daily, Awaiting Payment, Bug
