### ISSUE TITLE
[HOLD for payment 2024-03-19] [$500] [MEDIUM] IOU - Unable to delete a receipt that has been replaced in a failed scan flow

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34427] opened 2024-01-12 10:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.24-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Log in as the employee
2. Navigate to the workspace chat
3. Select "Request Money" > "Scan"
4. Upload a dummy image or a blurry receipt
5. Complete the money request
6. When the scan finally fails, open the receipt thumbnail
7. Tap on the three-dot menu on the top right > "Replace"
8. Replace the receipt with a new image
9. Tap on the three-dot menu on the top right again > "Delete Receip."
10. Confirm the action

Simplified Version (You don't need to replace, the root problem is detaching a receipt from a partial transaction):
1. Log in as the employee
2. Navigate to the workspace chat
3. Select "Request Money" > "Scan"
4. Upload a dummy image or a blurry receipt
5. Complete the money request
6. When the scan finally fails, open the receipt thumbnail
7. Tap on the three-dot menu on the top right  > "Delete Receipt."
8. Confirm the action

## Expected Result:
User should be able to delete a receipt that has incomplete details.

## Actual Result:
Unable to delete a receipt that has incomplete details.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/eaf1eeae-796f-4b0e-b91e-5ca400ff476a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4c657675402f03a</li>
        <li>Upwork Job ID: 1745749079699476480</li>
        <li>Last Price Increase: 2024-03-06</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2024-01-12 13:31
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Unable to delete a receipt that has been replaced in a failed scan flow.

## What is the root cause of that problem?

This is caused by a back-end `DetachReceipt` failed API call, in which the failureData persists the previous transaction's data which will always keep the last replaced receipt in onyx without the possibility to delete it.

Current `DetachReceipt` API failed call json response:

```json
{
    "jsonCode": 405,
    "message": "405 Cannot detach receipt from partial transaction",
    "onyxData": [],
    "requestID": "8445a7fbbba4052f-OTP"
}
```

## What changes do you think we should make in order to solve the problem?

If the expected behaviour here is to be able to upload another receipt then a front-end only fix that will allow that would be:

- in `IOU.detachReceipt()` function, replace the failureData's value to `newTransaction` instead of `transaction`, same as for the optimisticData. This will clear the receipt even if the detachReceipt call fails which will allow the user to upload another receipt.

**Caveat**: if detachReceipt call fails and the user doesn't add another receipt, when the IOU report is opened again they will see the last saved receipt since that's the real data that comes from the BE, as the above-mentioned fix is strictly front-end based (onyx).

## What alternative solutions did you explore? (Optional)

A back-end fix that will allow receipt deletion even when the `DetachReceipt` API call fails due to the transaction being partial (incomplete / missing data).

## Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/56457735/4425a3ff-e167-4278-a121-039423dde108

</details>

**Comment by CortneyOfstad** [comment] 2024-01-17 14:52
Any update @Ollyws? Thanks!

**Comment by ikevin127** [comment] 2024-01-17 19:24
@Ollyws I can still reproduce it on both latest staging and w/ latest main on local dev.

It happens for both 1:1 and workspace IOU scan requests, here are the steps:
1. Request Money > Scan > Add a random image (not an actual receipt)
2. Wait for the receipt scan to fail
3. Go to the IOU's view then lick on uploaded receipt > Tap on the three-dot menu on the top right > "Replace"
4. Once replaced > Tap on the three-dot menu on the top right > "Delete"

You will notice that the latest uploaded receipt is the same because the request fails.

**Comment by ikevin127** [comment] 2024-01-21 14:02
No idea. It only fails when both amount and merchant are incomplete as a result of a failed receipt scan.

If only the amount or only the merchant is missing - the DetachReceipt call succeeds.

**Comment by CortneyOfstad** [comment] 2024-01-22 15:26
Sounds good @Ollyws — I'll add `engineering` to confirm 👍

**Comment by CortneyOfstad** [comment] 2024-01-22 15:27
@srikarparsi can you confirm if this would be an internal issue? In the meantime, I've removed the `external` and `help wanted` tags 👍 TIA!

**Comment by srikarparsi** [comment] 2024-01-24 04:30
Yup! I can take a look at this :)

**Comment by CortneyOfstad** [comment] 2024-01-29 14:52
Awesome — thank you @srikarparsi!

**Comment by CortneyOfstad** [comment] 2024-01-31 16:06
@srikarparsi any updates? Thanks!

**Comment by srikarparsi** [comment] 2024-02-01 04:31
Hey! Sorry I wasn't able to look at this yet, I will try to get to this by the end of the week

**Comment by CortneyOfstad** [comment] 2024-02-02 14:12
No worries — thanks @srikarparsi!

**Comment by srikarparsi** [comment] 2024-02-09 07:51
Hey! Sorry for not getting to this yet. I believe this is related to wave 5 but I'm not completely sure. I should be able to work on this on Monday.

**Comment by CortneyOfstad** [comment] 2024-02-12 14:01
Sounds good and thanks @srikarparsi!

**Comment by CortneyOfstad** [comment] 2024-02-12 14:37
Dylan confirmed this is actually Wave 6 👍

**Comment by srikarparsi** [comment] 2024-02-14 08:00
Looks like it's a problem with the detach receipt call. Will try to get a PR out by the end of this week.

**Comment by CortneyOfstad** [comment] 2024-02-14 14:27
Sounds good @srikarparsi — thank you!

**Comment by srikarparsi** [comment] 2024-02-16 07:51
Created a WIP PR above, will try to test more tomorrow.

**Comment by CortneyOfstad** [comment] 2024-02-16 15:29
Awesome — thanks @srikarparsi!

**Comment by srikarparsi** [comment] 2024-02-20 04:51
Did some preliminary testing, looks good, I'll test one more thing tomorrow and should be good to mark it ready for review.

**Comment by CortneyOfstad** [comment] 2024-02-22 19:03
@srikarparsi just checking to see how the review is going! Do you think that is something that can be completed by EOD? Thanks!

**Comment by CortneyOfstad** [comment] 2024-02-23 18:23
Bump @srikarparsi ^^^ thank you!

**Comment by srikarparsi** [comment] 2024-02-26 09:00
Hey @CortneyOfstad! Sorry, I was working on this other wave issue and haven't checked up on this one. I'll review this tomorrow and it should get merged by Wednesday

**Comment by srikarparsi** [comment] 2024-02-27 11:27
Wasn't able to get to this either today but will make it a top priority tomorrow.

**Comment by srikarparsi** [comment] 2024-02-28 10:33
It seems to be working, I left a comment here about a [question](https://expensify.slack.com/archives/C03TQ48KC/p1709116368258469) I had. Should be able to get this merged by the end of the week.

**Comment by CortneyOfstad** [comment] 2024-02-28 14:58
Thanks for the context @srikarparsi!

**Comment by CortneyOfstad** [comment] 2024-02-29 19:37
@srikarparsi I am going to be heading OoO until March 11th, so going to be reassigning BZ. Once you have an update on the merge, let us know. Thanks!

**Comment by CortneyOfstad** [comment] 2024-02-29 19:39
@lschurr I'll be back on March 11th and in the meantime, @srikarparsi is waiting on a question (more details [here](https://github.com/Expensify/App/issues/34427#issuecomment-1968691179)) to get the PR merged and will post an update when he can. Thanks!

**Comment by srikarparsi** [comment] 2024-03-04 08:12
Looking at Old Dot behavior to see expected behavior.

**Comment by lschurr** [comment] 2024-03-04 16:15
Any update here @srikarparsi?

**Comment by srikarparsi** [comment] 2024-03-05 21:20
Hey @lschurr, do you know if theres a way to detach a receipt from an expense in Old Dot? I tried scanning in a receipt and then detaching the receipt but couldn't find a way to do it. I saw this help doc [here](https://community.expensify.com/discussion/3559/delete-unwanted-documents-receipts#:~:text=Yes%2C%20you%20can%20detach%20a,down%20to%20the%20Documents%20section.) but couldn't find the same button on our current product.

**Comment by lschurr** [comment] 2024-03-05 21:43
Hey @srikarparsi - I checked in a random customer's account and I see the Detach option only on Unreported expenses:

<img width="912" alt="image" src="https://github.com/Expensify/App/assets/33293730/573436c2-eb81-4644-8992-38325cec392f">

It doesn't look like it exists if the expense is added to a report.

**Comment by lschurr** [comment] 2024-03-05 21:44
Hey @srikarparsi - I checked in a random customer's account and I see the Detach option only on Unreported expenses:

<img width="241" alt="image" src="https://github.com/Expensify/App/assets/33293730/d990e885-e275-419e-9338-4104a71b250f">

It doesn't look like it exists if the expense is added to a report.

**Comment by srikarparsi** [comment] 2024-03-06 08:18
Got it! That makes sense actually. Based on this [discussion](https://expensify.slack.com/archives/C03TQ48KC/p1709116368258469) as well, it sounds like we don't want to allow users to detach receipts from partial expenses.

In other words, the "Delete Receipt" option should not exist for partial transactions.

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/48188732/a8e3bc90-14b9-4e5e-80dc-d6f897781be9">

Instead, users can get rid of the receipt by deleting the expense or filling out the rest of the expense and then deleting the receipt.

I think we can use the [hasMissingSmartscanFields](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.ts#L2289) method to check this and conditionally render the button. Opening it back to the pool since it can be taken care of in the frontend. I can also start on this on Friday if it doesn't get picked up by then.

**Comment by srikarparsi** [comment] 2024-03-06 22:01
This looks good to me, @Ollyws what do you think?

**Comment by CortneyOfstad** [comment] 2024-03-13 16:36
Thanks @Ollyws!

**Comment by CortneyOfstad** [comment] 2024-03-14 15:16
Regression test created [here](https://github.com/Expensify/Expensify/issues/378882)

Payment is set for the 19th!

**Comment by CortneyOfstad** [comment] 2024-03-19 16:43
@Ollyws @dukenv0307 — sent you both an offer in Upwork. Let me know once you both accept and we can get this paid asap. Thank you!

**Comment by CortneyOfstad** [comment] 2024-03-20 15:24
Payments have been completed! Thanks!

**Closed by CortneyOfstad** 2024-03-20 15:24 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
