### ISSUE TITLE
[Backwards Compatibility] [HIGH] Allow submitting reports which have smartscanning expenses on them

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#35240] opened 2024-01-26 13:03 UTC
### Problem

Coming from [here](https://expensify.slack.com/archives/C049HHMV9SM/p1706229968104059) cc @yuwenmemon 

In OldDot world, we did not allow to submit a report which had an expense/ receipt still being smartscanned. This error is thrown [here](https://github.com/Expensify/Auth/blob/1ba8cfb714f42c3a4576cf4a70588d17edc216fb/auth/command/SubmitReport.cpp#L60-L62).

In NewDot, we are taking different approach for such expenses. For example in PayMoneyRequest, we [move such transactions over to a new report](https://github.com/Expensify/Auth/blob/1ba8cfb714f42c3a4576cf4a70588d17edc216fb/auth/command/PayMoneyRequest.cpp#L206-L233). We would like to do the same when report is submitted.

### Solution

Similarly to the PayMoneyRequest, if there are smartscanning receipts, move those expenses to a new Open/Processing report (depending on the policy settings), move over the report actions and push updates to the client.

These updates should provide:
- new report
- updated transactions
- updated report actions 
- new report preview for the new report

In OldDot, per [this comment](https://expensify.slack.com/archives/C049HHMV9SM/p1706273505540099?thread_ts=1706229968.104059&cid=C049HHMV9SM) from @trjExpensify, we should detect if any expenses are smartscanning in Web and show a confirmation modal if the user wants to wait with submission or proceed while creating a new report. [Here's the suggested changes](https://github.com/Expensify/App/issues/35240#issuecomment-1912088150) for that OldDot portion.

**Comment by trjExpensify** [comment] 2024-01-26 13:41
So it looks like we hit the user with modal inception when they try to take this action: 

<img width="679" alt="image" src="https://github.com/Expensify/App/assets/16232057/727cf191-fffd-4df0-82c1-5f054a7ae829">

Dismissing that reveals this: 

<img width="600" alt="image" src="https://github.com/Expensify/App/assets/16232057/645d3835-ffe7-4edb-8b80-0aaefa16fb8a">

So I'd vote we don't show the first one, and tweak that copy of the second one: 

**Not so fast! SmartScan still in progress.** 
            [Illustration]

The receipt will be moved to a different open report if you proceed with this action. You can otherwise wait for it finish, or manually edit the receipt by clicking on "Fill out the details".

[Tip: SmartScan your receipts at the register using [our mobile app](https://community.expensify.com/discussion/4712/how-to-receipt-uploading-on-mobile/p1?new=1) and they'll be done before you submit your report!]

[Submit] [Cancel]

**Comment by jasperhuangg** [comment] 2024-02-02 01:18
Interested in looking into this! @mountiny do you think this still needs to be a `Weekly` issue?

**Comment by jasperhuangg** [comment] 2024-02-02 01:18
cc ^ @greg-schroeder

**Comment by mountiny** [comment] 2024-02-02 01:20
I think it could be a Daily!

**Comment by greg-schroeder** [comment] 2024-02-02 05:19
Updated

**Comment by blimpich** [comment] 2024-02-02 22:57
@jasperhuangg you're working on this correct? If so can we remove the hot pick label?

**Comment by trjExpensify** [comment] 2024-02-08 02:01
@jasperhuangg, confirming you're on this one?

**Comment by jasperhuangg** [comment] 2024-02-09 02:10
@trjExpensify yes! sorry, I've been prioritizing another `HIGH` priority issue I have and have also been looking into a fire. Looking to get started on this next week.

**Comment by trjExpensify** [comment] 2024-02-09 11:04
Okay, sounds good!

**Comment by jasperhuangg** [comment] 2024-02-12 18:06
Looking into this today.

**Comment by jasperhuangg** [comment] 2024-02-12 20:07
I looked into the code and design docs a bit and sent [this](https://github.com/Expensify/App/issues/35240#issuecomment-1912088150) in Slack asking for some clarification on the issue.

**Comment by jasperhuangg** [comment] 2024-02-13 00:12
Have some local changes, the changes are proving to be a bit more complex than I had imagined because we have to take into account updating the `previousReportActionIDs` of all the money request actions that are moved to the newly created expense report.

**Comment by jasperhuangg** [comment] 2024-02-14 04:28
It's been clarified here that the Auth changes aren't necessary anymore. We only need to make the Web-E changes outlined [here](https://github.com/Expensify/App/issues/35240#issuecomment-1912088150)

**Comment by jasperhuangg** [comment] 2024-02-23 20:53
Same ^

**Comment by jasperhuangg** [comment] 2024-02-27 04:15
Same ^^, it looks like the PR is almost ready for review

**Comment by jasperhuangg** [comment] 2024-03-01 18:56
^ Same

**Comment by jasperhuangg** [comment] 2024-03-04 18:12
Same ^

**Comment by jasperhuangg** [comment] 2024-03-06 21:05
Same ^

**Comment by jasperhuangg** [comment] 2024-03-12 17:18
Same ^, still on HOLD

**Comment by jasperhuangg** [comment] 2024-03-15 19:06
Still on HOLD ^

**Comment by jasperhuangg** [comment] 2024-03-18 19:08
Still on HOLD

**Comment by jasperhuangg** [comment] 2024-03-18 19:38
Still on HOLD

**Comment by jasperhuangg** [comment] 2024-03-25 18:47
@youssef-lr Do you mind taking a look at this issue (specifically [these](https://github.com/Expensify/App/issues/35240#issuecomment-1912088150) front-end changes) and letting me know if it still needs to be on HOLD for your changes in https://github.com/Expensify/Expensify/issues/359760?

**Comment by jasperhuangg** [comment] 2024-04-03 22:27
cc @youssef-lr ^ friendly bump

**Comment by youssef-lr** [comment] 2024-04-04 23:30
@jasperhuangg @garrettmknight I don't think this issue needs to be held on https://github.com/Expensify/Expensify/issues/359760, it seems unrelated and we can work on it independently

**Comment by garrettmknight** [comment] 2024-04-05 07:32
Great to hear, @jasperhuangg you're up!

**Comment by jasperhuangg** [comment] 2024-04-08 19:03
@mountiny @JmillsExpensify just to clarify, are [these front-end changes](https://github.com/Expensify/App/issues/35240#issuecomment-1912088150) all that needs to happen for this issue?

I remember we had a conversation a while back saying that the back-end changes weren't necessary. I just wanted to clarify that this was still the case before I got started on updating the front-end.

**Comment by mountiny** [comment] 2024-04-08 20:55
@trjExpensify I believe that is it

Because the rest should have been handled by updates from @youssef-lr so people are able to edit processing reports

**Comment by jasperhuangg** [comment] 2024-04-08 21:13
Got it, thanks for clarifying! I'll get started on the front-end changes for this this week.

**Comment by jasperhuangg** [comment] 2024-04-09 19:07
Running into some issues with uploading receipts locally so I reached out for some help [here](https://expensify.slack.com/archives/C03TQ48KC/p1712687415213459?thread_ts=1692206624.105019&cid=C03TQ48KC) where people have ran into the issue previously.

**Comment by jasperhuangg** [comment] 2024-04-12 01:44
Made more progress today with https://github.com/Expensify/Web-Expensify/pull/41606. I also opened https://github.com/Expensify/Auth/pull/10503 yesterday since there were some Auth changes that are necessary to get this to work as expected.

Not gonna mark https://github.com/Expensify/Auth/pull/10503 as ready for review until I've fully tested it with the changes from https://github.com/Expensify/Web-Expensify/pull/41606 in case there are other changes I need to make.

**Comment by jasperhuangg** [comment] 2024-04-15 19:11
Have a new understanding of the issue after asking some clarifying questions [here](https://expensify.slack.com/archives/C036QM0SLJK/p1712888121286259), gonna use that new understanding to keep pushing forward that Web PR

**Comment by jasperhuangg** [comment] 2024-04-15 20:06
Made a bt more progress with the PR today

**Comment by jasperhuangg** [comment] 2024-04-16 18:47
@mountiny @trjExpensify Opened a thread [here](https://expensify.slack.com/archives/C036QM0SLJK/p1713292446017259) for some more clarifying questions I have–it seems some back-end changes could be missing that we assumed existed or didn't need to be done.

**Comment by jasperhuangg** [comment] 2024-04-18 19:07
Still working on the Auth PR, the back-end changes that needed to be added were pretty extensive since they involve porting over an entire ReportAction class to Auth.

**Comment by jasperhuangg** [comment] 2024-04-18 22:51
Lol melvin marked this as overdue right after I commented an update 🤔

**Comment by jasperhuangg** [comment] 2024-04-19 23:57
Made good progress with the tests, and I think it should almost be ready for review. The only issue is that the Onyx update for report preview action relies on the `Currency::format` function, which still needs to be updated to support all currency types. Flo mentioned he would look into that on Monday, so I'll keep this posted with what's gonna happen next week.

I also asked @mountiny for additional clarification on why we need to update the report preview action [here](https://expensify.slack.com/archives/C036QM0SLJK/p1713569502698799).

**Comment by jasperhuangg** [comment] 2024-04-22 22:19
Made more progress with the tests, but there are still a few failing that I need to fix.

**Comment by jasperhuangg** [comment] 2024-04-23 14:20
I've fixed the automated tests, going to start figuring out manual testing steps. This could be pretty complicated since the Auth changes touch quite a few flows both in NewDot and OldDot.

**Comment by jasperhuangg** [comment] 2024-04-24 01:21
Vit gave the Auth PR a review, I'm resolving some merge conflicts and looking to get his review addressed before he comes online again.

**Comment by jasperhuangg** [comment] 2024-04-25 21:03
Making good progress with the Auth PR, there were some conflicts that created some problems since so much code has been merged lately.

I started testing it with the Web-E PR and the changes seem to be working as expected. Gonna fix the issues with the conflicts and request Vit for another review.

@mountiny Do you have any tips on the flows in NewDot that I should test with this PR? I've only tested it manually with OldDot so far. Some specific testing steps would be really helpful since I'm not super familiar with all the flows that this change touches in NewDot.

**Comment by jasperhuangg** [comment] 2024-04-26 00:32
I've marked both the Auth and Web-E PRs as ready for review.

Tested the new submission flow with smartscanning expenses in NewDot and Olddot and it seems to be working as expected.

Requested @mountiny for review on both PRs. Would love a second look at my testing steps to see if there are any other flows that I need to test. Thanks!

**Comment by jasperhuangg** [comment] 2024-04-29 20:00
Tests are passing again and I've addressed all the review comments. Just submitted both PRs for re-review!

**Comment by jasperhuangg** [comment] 2024-05-06 19:38
Was sick Thursday/Friday last week so wasn't able to push forward the broken tests and reviews.

I am aware of the pending reviews on my Auth PR. I need to fix the broken automated tests first before addressing those reviews. Looking to submit the Auth PR for re-review by EOD.

**Comment by jasperhuangg** [comment] 2024-05-07 22:05
I've finally fixed all the automated tests! Just gonna rerun the manual tests to double-check that I didn't break anything as I was fixing the tests and addressing all the review comments.

Nonetheless it should be ready for review again.

**Comment by jasperhuangg** [comment] 2024-05-09 20:12
Looks like Vit got another review up for the Auth PR, so I'm addressing that now

**Comment by jasperhuangg** [comment] 2024-05-23 19:09
Auth PR is held on the merge slush since it has a ton of lines and touches quite a few flows.

Gonna work on resolving the merge conflicts today, a lot came up when I was OOO.

**Comment by jasperhuangg** [comment] 2024-05-28 21:25
Finally took the merge freeze/slush hold off, and fixed some failing automated tests after merging main. I also ran through all the manual tests again since it's been a while and they seem to be working as expected (save for 1 small bug that I addressed).

I think the Auth PR should be ready to merge now.

**Comment by jasperhuangg** [comment] 2024-06-05 18:45
Requested to merge the Auth PR [here](https://expensify.slack.com/archives/C0714QF3A1Z/p1717610597353359), not overdue

**Comment by jasperhuangg** [comment] 2024-06-14 17:11
@trjExpensify Yep! Thanks for checking. I applied the changes to the PR already.

**Comment by jasperhuangg** [comment] 2024-06-14 17:18
We just merged the Web-E PR 🥳 Next step deployment/QA and verifying nothing explodes 🤞

**Comment by trjExpensify** [comment] 2024-06-19 18:31
... we good here?

**Comment by jasperhuangg** [comment] 2024-06-20 17:28
The Web PR was reverted slowly after being deployed. It seems the new value I added to the cache isn't being set correctly for some types of reports. I'm going to look into a fix today and hopefully get it remerged. cc @mountiny thank you for the investigation while I was out 🙇

**Comment by jasperhuangg** [comment] 2024-06-20 18:11
Was able to reproduce the error. It was difficult to catch during the review because the report needs to be created on a version of Web-Expensify that doesn't have the cache updates. If you then switch to using the new cache changes and access the report, the new cache value isn't set yet, leading to the Submit button to be greyed out. Here are some detailed steps to reproduce:
1. Pull latest version of `main`. Sign into any account in OldDot. Create a new report with 1 complete expense on it. See that the Submit button is clickable.
2. Apply changes from `jasper-updateSmartscanningReportSubmit` (check it out locally).
3. Reload the page. The Submit button is now unclickable.

The fix is to add `hasNonSmartscanningTransactions` to the required cache keys [here](https://github.com/Expensify/Web-Expensify/blob/8cc2bc9a68d20fc090b0a29444c3cd46da8d0b71/lib/Report.php#L837-L869) so trigger the cache to be loaded again if we see that `hasNonSmartscanningTransactions` isn't set yet.

**Comment by jasperhuangg** [comment] 2024-06-20 18:43
Just re-merged the Web-E PR

**Comment by trjExpensify** [comment] 2024-06-24 18:30
Nice! Is it just the Web-E PR we need here?

**Comment by jasperhuangg** [comment] 2024-06-24 19:03
Yep, once that's on prod we should be good to close this out!

https://github.com/Expensify/Web-Expensify/pull/42448

**Comment by jasperhuangg** [comment] 2024-06-25 16:36
PR was deployed to staging last night!

**Comment by jasperhuangg** [comment] 2024-06-26 18:03
PR is on prod about 20 hours ago. I'm monitoring for API issues, but it seems like things are going smoothly, gonna close this out for now 👍

**Closed by jasperhuangg** 2024-06-26 18:03 UTC
Labels: Reviewing, Daily, NewFeature
