### ISSUE TITLE
[$250] Wrong error message displayed when a self assigned task not shared

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46676] opened 2024-08-01 17:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @srikarparsi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722527807659089

## Action Performed:

1. Click FAB
2. Click Assign Task
3. Enter in a title and description
4. Click next
5. Select an assignee (Self assigned)
6. Click confirm task

## Expected Result:
Error message as  “Please select where you want to share”
## Actual Result:
Error message is displayed as  “Please select with whom you want to share”,
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/0a60b1e4-a7ea-4daa-928c-57cb682e9695" width="40%" height="40%">

![Snip - (1) New Expensify - Google Chrome](https://github.com/user-attachments/assets/553335bf-d966-4c32-b1ac-79575e47a1f9)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143d34debb4b1dce5</li>
        <li>Upwork Job ID: 1820524672136368978</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by srikarparsi** [comment] 2024-08-05 18:19
Actually, I'll take this one internally because the main part of this is confirming behavior. Sorry for the noise.

**Comment by srikarparsi** [comment] 2024-08-06 05:01
Checking [here](https://expensify.slack.com/archives/C049HHMV9SM/p1722527807659089) about behavior to confirm.

**Comment by srikarparsi** [comment] 2024-08-09 05:25
PR above just waiting on confirmation for [translation](https://expensify.slack.com/archives/C21FRDWCV/p1723180793685769?thread_ts=1723098495.510839&cid=C21FRDWCV)

**Comment by mvtglobally** [comment] 2024-08-23 12:00
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment] 2024-08-30 11:11
@srikarparsi sounds like based on this not being reproducible, we can potentially go ahead and close this out?

**Closed** 2024-09-06 15:19 UTC
Labels: Reviewing, Weekly, Internal, Help Wanted, Bug

**Comment by srikarparsi** [comment] 2024-09-10 21:00
Oh yup, we fixed it in this [PR](https://github.com/Expensify/App/pull/47032)
