### ISSUE TITLE
FEATURE REQUEST: add the ability to set custom avatars for rooms/groups

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34369] opened 2024-01-11 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704927923611429

## Action Performed:
1. Open any group chat or room
## Expected Result:
Should be able to set custom avatar
## Actual Result:
Not able set to custom avatar

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/d83bfa5f-7b97-499d-a817-64a16e6bafbd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018c02eb6140cd415f</li>
        <li>Upwork Job ID: 1749467340661170176</li>
        <li>Last Price Increase: 2024-01-22</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2024-01-11 16:21
I can handle this issue if it is opened for Contributor
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- FEATURE REQUEST: add the ability to set custom avatars for rooms/groups
### What is the root cause of that problem?
- NA
### What changes do you think we should make in order to solve the problem?
- We can use the AvatarWithImagePicker component that were used in ProfilePage and WorkspaceSettingPage

### What alternative solutions did you explore? (Optional)
- NA

**Comment by michaelhaxhiu** [comment] 2024-01-19 22:40
@iwiznia did you envision this should be handled by someone **internal** or **external**?

I believe we typically assign new features to **internal** staff only?

**Comment by iwiznia** [comment] 2024-01-22 16:20
I assume this needs both, since it will need a backend change as well as a frontend change.

**Comment by michaelhaxhiu** [comment] 2024-01-22 16:22
Cool! Let's start with `internal` and then recruit from `external`

**Comment by iwiznia** [comment] 2024-01-22 17:54
Going to unassign to give room for engineers with time to work on it to self assign

**Comment by CortneyOfstad** [comment] 2024-02-05 14:11
Reached out about priority on this [here](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ/p1707142286718789).

**Comment by quinthar** [comment] 2024-02-05 19:25
It's on the list, but let's not worry about it right now.

**Comment by CortneyOfstad** [comment] 2024-02-22 19:02
This is pretty low priority, so no update at this time 👍

**Comment by CortneyOfstad** [comment] 2024-02-28 14:57
No update yet as this is a "Future" upgrade. Put the hotpick on it, in case anyone has a brief moment to take it on, but otherwise **Low** priority. 

Going to adjust this to **Monthly** in the meantime 👍

**Comment by CortneyOfstad** [comment] 2024-04-01 13:07
Still a pretty low priority/future upgrade, so no updates at this time 👍

**Comment by CortneyOfstad** [comment] 2024-05-01 15:16
Still pretty low on the list, but should expect some traction after the May 1 release 👍

**Comment by CortneyOfstad** [comment] 2024-06-03 13:28
Still no takers

**Comment by CortneyOfstad** [comment] 2024-07-11 16:55
With VIP VSB being paused, this will be in the backseat for a while.

**Comment by mvtglobally** [comment] 2024-07-19 03:12
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment] 2024-08-12 14:41
Still a backseat item — not overdue!

**Comment by CortneyOfstad** [comment] 2024-09-16 17:42
This is pretty low priority and with VIP VSB remaining paused, going to close this. We can always re-address if there are any issues associated with it  👍

**Closed by CortneyOfstad** 2024-09-16 17:42 UTC
Labels: Engineering, Monthly, Internal, NewFeature, Overdue, Hot Pick
