### ISSUE TITLE
Console error when spliting bills among new users with no chat history

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24243] opened 2023-08-08 00:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. click + icon from LHN
3. create a group for new users
4. split a bill for the group
## Expected Result: 
there shouldn't be a console log error
## Actual Result: 
Uncaught TypeError: Iterable yielded undefined which is not a string

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/824645ed-c56a-48f4-87ea-419d506e741e

https://github.com/Expensify/App/assets/43996225/ca73853e-cebf-484f-996b-90520edad95b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690936933055849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ygshbht** [comment] 2023-08-08 01:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The console logs an error when splitting bills among new users with whom you have no chat history.

### What is the root cause of that problem?
The error stems from attempting to split a bill with users whose data is unavailable, likely because of privacy constraints linked to the lack of prior chat interactions. This issue becomes evident when formatting participants and finding the 'login' is undefined.
https://github.com/Expensify/App/blob/2ce4328401ec71f9ec0dc1304e0c5be261ae5628/src/libs/actions/IOU.js#L475
### What changes do you think we should make in order to solve the problem?
When invoking `Localize.arrayToString([currentUserLogin, ..._.map(participants, (participant) => participant.login)])`, if login is undefined, use the user's email or phone as an alternative by finding it in the participant object or asking the requesting user, if the server permits. If not possible, introduce a UI component to display an error to the user.

**Comment by pbkompasz** [comment] 2023-08-09 12:44
Dupe of #23470

**Comment by slafortune** [comment] 2023-08-09 20:17
Closing

**Closed by slafortune** 2023-08-09 20:17 UTC
Labels: Daily, Bug
