### ISSUE TITLE
iOS - Notifications - New message is not displayed in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8963] opened 2022-05-12 13:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the test app and log in with a HIGH TRAFFIC account as user A
2. Sign into as user B on another device
3. As user A, navigate to another conversation (not user B) and lock the device.
4. Wait for ~5 minutes.
5. Send a message from B to A. Push notification should appear.
6. After about 10 seconds, put the device on airplane mode.
7. Tap the notification.

## Expected Result:
After tapping the notification, It should open the test app to the correct chat, and the new message should be available.

## Actual Result:
After tapping the notification, It opens the test app to the correct chat, but the new message isn't available.
The new message appeared after back online.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.57.15

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/168092579-77e34eea-5e5f-4fed-a110-4cb1a75a1421.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-05-12 17:38
>After tapping the notification, It should open the test app to the correct chat, and the new message should be available.

@kbecciv is this the current behavior on staging/production?

**Comment by mvtglobally** [comment] 2022-05-12 18:18
@luacmartins It is not repro on PROD. Only on Staging

**Comment by luacmartins** [comment] 2022-05-12 18:48
Having issues to reproduce this on the simulators. Asked in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1652379435924739).

**Comment by luacmartins** [comment] 2022-05-12 19:46
The behavior is also inconsistent on production, so I'm removing the deploy blocker label and moving this to a daily.

**Comment by mvtglobally** [comment] 2022-07-05 04:38
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment] 2022-08-15 23:38
Seems like the issue is not reproducible anymore. Closing!

**Closed by luacmartins** 2022-08-15 23:38 UTC
Labels: Engineering, Monthly, Improvement, Overdue
