### ISSUE TITLE
[HOLD for payment 2024-07-10] [$500] Task – Task is bold in LHN when reassign task to another user and @ appears before user name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42068] opened 2024-05-13 14:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4553777
**Email or phone of affected tester (no customers):** applausetester+jpcategory@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Log in
3. Open any chat and select Assign task
4. Create a task and assign to another user
5. Find task in the LHN
6. Open task details and reassign task to another user
7. Observe the task in LHN

## Expected Result:
Task details is not bold in LHN when reassign task to another user, as this page is open

## Actual Result:
Task details is bold in LHN when reassign task to another user and wait until @ appears before user name in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4ad06f15-abe2-46db-b186-1eaddb44c5a2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ad0a78be0f06131</li>
        <li>Upwork Job ID: 1791203935959134208</li>
        <li>Last Price Increase: 2024-05-31</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 102709353</li>
<li>suneox | Contributor | 102709356</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment] 2024-05-13 14:04
@AndrewGable  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bondydaa** [comment] 2024-05-13 15:55
@AndrewGable can you determine if this is something from the API or not? if not can you remove the DeployBlocker label?

**Comment by AndrewGable** [comment] 2024-05-13 16:42
Yes, looking into it

**Comment by AndrewGable** [comment] 2024-05-13 20:52
Seems like yes, that was the diff, which should not have caused this, so seems fine to not block on API deploy.

**Comment by AndrewGable** [comment] 2024-05-13 23:07
Ok can't reproduce bug on production or staging, can we retest this @lanitochka17 ?

Screen Recording 2024-05-13 at 5.05.52 PM.mov

**Comment by lanitochka17** [comment] 2024-05-15 18:02
Issue is still reproducible 

https://github.com/Expensify/App/assets/78819774/76816a72-6a6c-4329-9dea-932506adda0b

**Comment by tsa321** [comment] 2024-05-20 00:00
Maybe internal?

**Comment by laurenreidexpensify** [comment] 2024-05-20 12:10
Waiting for proposals

**Comment by getusha** [comment] 2024-05-20 14:47
Not able to reliably reproduce this issue, trying to figure out if it is an issue from the FE

**Comment by laurenreidexpensify** [comment] 2024-05-22 10:46
@AndrewGable do you have a steer on whether this is FE or BE?

**Comment by AndrewGable** [comment] 2024-05-23 22:22
I would assume it's front end, bolding and marking as unread seems to usually come from the front end

**Comment by laurenreidexpensify** [comment] 2024-05-24 11:25
Still waiting on proposals

**Comment by laurenreidexpensify** [comment] 2024-05-28 08:53
Still waiting on proposals

**Comment by laurenreidexpensify** [comment] 2024-05-31 12:04
bounty increased

**Comment by getusha** [comment] 2024-06-04 06:36
Reviewing proposals

**Comment by getusha** [comment] 2024-06-04 07:53
>// Or change a comparison by Date instead of string

@suneox the RCA makes sense, ^ solution sounds interesting could you expand on that? thanks

**Comment by laurenreidexpensify** [comment] 2024-06-04 11:14
Still working through proposals

**Comment by getusha** [comment] 2024-06-05 11:57
@suneox's [proposal](https://github.com/Expensify/App/issues/42068#issuecomment-2143922620) looks good to me, the root cause is well explained and make sense.
We can convert the string to date before comparing.

🎀 👀 🎀 C+ Reviewed

**Comment by laurenreidexpensify** [comment] 2024-06-12 18:37
@AndrewGable bump if you have a mo to review thanks. Also can you confirm what project this falls under - is this VSB cos tasks?

**Comment by AndrewGable** [comment] 2024-06-12 18:40
Yes, VSB sounds right

**Comment by laurenreidexpensify** [comment] 2024-06-18 11:17
@adelekennedy  adding you here for parental leave sub. no action required this BZ this week, PR is still in review, but adding you for payment in coming weeks when the fix makes it to prod. Thanks

**Comment by adelekennedy** [comment] 2024-07-12 16:52
Just took care of it! @getusha it looks like your offer is still pending - will yo accept it today? Otherwise it expires!

**Comment by getusha** [comment] 2024-07-12 17:24
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@suneox / @getusha] The PR that introduced the bug has been identified. Link to the PR: N/a i think this is an edge case left unhandled
 [@suneox / @getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/a**
 [@suneox / @getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/a**
 [@suneox / @getusha] Determine if we should create a regression test for this bug. **I don't think the bug is impactful enough to create a regression test**
 [@suneox / @getusha] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/a**

**Comment by getusha** [comment] 2024-07-12 17:25
Accepted, @adelekennedy, thanks!

**Closed** 2024-07-12 17:35 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
