### ISSUE TITLE
iOS  -  App crashes when re-inviting the member

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13907] opened 2022-12-30 15:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions Performed:

1. Open expensify app in member iOS device keep it open.
2. Open expensify app in admin device(any device) and remove the member from the workspace
3. Invite the member again to the same workspace

## Expected Result:
Member should be able to use the app properly and interact with workspace

## Actual Result:
iOS app is crashing on member device. Crashes every time i try to open the app again. only fix seems to be re-install.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / native

**Version Number:** 1.2.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210087275-6fd1d1ee-72bb-43e4-b585-e963b1a15786.mov

https://user-images.githubusercontent.com/43996225/210087296-8f5db2d9-567f-4bab-a06b-4671241dae70.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @abdulrahuman5196
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672258474181849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b62be585203ffd9</li>
        <li>Upwork Job ID: 1609769898823237632</li>
        <li>Last Price Increase: 2023-01-02</li>
    </ul>
</details>

**Comment by jasperhuangg** [comment] 2023-01-02 04:34
Gonna check this one out!

**Comment by jasperhuangg** [comment] 2023-01-02 04:43
<img width="940" alt="Screen Shot 2023-01-02 at 12 42 43 PM" src="https://user-images.githubusercontent.com/31285285/210195702-0da205bc-5c8e-47cd-91b4-f5dfa13087f2.png">

was able to reproduce on iOS dev, something is happening when we try to save the Onyx response.

**Comment by jasperhuangg** [comment] 2023-01-02 09:27
The contributor who originally pointed out this issue and made this proposal DMd me with a solution, and it mostly makes sense to me, I'm going to open up this issue to `External` so that they can post their proposal here for further review. At first glance the proposal makes sense to me.

Based on what they told me, here's an outline of what's going on with Onyx:
1. Onyx's `mergeCollection` relies on `AsyncStorage.multiMerge`.
2. When we delete a member from a workspace, we call `Onyx.mergeCollection`, merging `null` values for each workspace member to effectively delete them. However, even though the values have been cleared, the keys are still present.
3. Later on, when we add deleted members back to the workspace, the key still exists, so we try to merge an object into `null`.
4. In AsyncStorage, this action is handled gracefully on all other platforms (`null` is overwritten by the object), but for whatever reason on iOS it throws an exception.

The solution is when we call `mergeCollection` with `null` values, we should also delete the keys from storage as well. This shouldn't cause any problems because the behavior of getting a non-existent keys is also to return `null`.

**Comment by abdulrahuman5196** [comment] 2023-01-02 09:35
**Proposal**

I have already add the Root cause and solution as part of the original bug statement in slack here - https://expensify.slack.com/archives/C049HHMV9SM/p1672258474181849

**Comment by abdulrahuman5196** [comment] 2023-01-02 09:35
**Proposal**
**Background:**
Whenever we receive a pusher event to delete data, it has data like for eg.

```
key = 'keyToDelete'
value = null
```
1. In Onyx, what we do is call set() function with key('keyToDelete') and value 'null'. Now we call AsyncStorage(backbone of Onyx) and OnyxCache with the same key and value through set() function.
2. When a member is added to the workspace, we get 'mergeCollection' event which ultimately ends up here https://github.com/Expensify/react-native-onyx/blob/main/lib/Onyx.js#L1123

**Rootcause:**
Now we assume as the value is set to 'null' during 1st action, the data is deleted in OnyxCache and AsyncStorage. But no, the key is still present in AsyncStorage with value as null. And OnyxCache also has the key in its cache.  This key should have been ideally deleted from AsyncStorage and OnyxCache as per pusher event/standard practice.Now when a mergeCollection(as part of any pusher event in this context  workspace case) request comes to Onyx, we try to find if we already have keys present in cache/storage to understand if we need to call multiMerge(called for existing keys) or multiSet(called for new keys)
https://github.com/Expensify/react-native-onyx/blob/main/lib/Onyx.js#L1141
https://github.com/Expensify/react-native-onyx/blob/main/lib/Onyx.js#L1156

Here even though the values are null for the keys from previous pusher notifications, when we call getKeys() we would still get the key(which should have been ideally not present). So we call multiMerge of AsyncStorage instead of multiSet as we think AsyncStorage already has some value for the key. AsyncStorage now tries to merge a value of 'null' and new object from request which results in crash.This would also be the root cause related to these inconsistent iOS crash bugs - https://github.com/Expensify/App/issues/10975, https://github.com/Expensify/App/issues/12330


**Why is this happening only for iOS?**
This might be a difference in AsyncStorage itself on how it handles exceptions. On other platforms even though multiMerge is called with wrong data AsyncStorage handles gracefully but not with iOS. But expensify should be responsible in this case as we are sending invalid data to multiMerge.

**Solution 1 (Best Long term fix IMO):**
Instead of setting the key value as null, call AsyncStorage.removeItem(key)  and remove the key from OnyxCache as well. This will remove the keys from AsyncStorage and OnyxCache. This way when you call mergeCollection it will properly find if the the key is new or existing with proper value. This will also remove any inconsistencies we have with keys present in Onyx cache and AsyncStorgage.We can also extend the same fix to multiSet as well as similar to set().
I have added short sample solution code for contributors to test if my analysis is correct. I can work on
full code with proper standard formats and provide the changes required if my proposal gets approved.

**Solution 2(Not Preferred IMO):**
Reach out to AsyncStorage package to handle this exception gracefully. This might not fix our issues with OnyxCache and won't fix underlying issue in expensify app.

**Solution 3(Not best just proposing IMO):**
Before merge check if the key has actual value in the storage instead of null value. (edited)


**Code diff for fix**

```
diff --git a/lib/Onyx.js b/lib/Onyx.js
index 4a4196d..1e33923 100644
--- a/lib/Onyx.js
+++ b/lib/Onyx.js
@@ -799,8 +799,7 @@ function notifyCollectionSubscribersOnNextTick(key, value) {
  * @return {Promise}
  */
 function remove(key) {
-    // Cache the fact that the value was removed
-    cache.set(key, null);
+    cache.drop(key)
     notifySubscribersOnNextTick(key, null);
     return Storage.removeItem(key);
 }
@@ -847,6 +846,9 @@ function evictStorageAndRetry(error, onyxMethod, ...args) {
  * @returns {Promise}
  */
 function set(key, value) {
+    if (!value) {
+        return remove(key)
+    }
     // Logging properties only since values could be sensitive things we don't want to log
     Logger.logInfo(`set() called for key: ${key}${_.isObject(value) ? ` properties: ${_.keys(value).join(',')}` : ''}`);
 
diff --git a/lib/OnyxCache.js b/lib/OnyxCache.js
index 4ac4222..1500e47 100644
--- a/lib/OnyxCache.js
+++ b/lib/OnyxCache.js
@@ -104,6 +104,8 @@ class OnyxCache {
      */
     drop(key) {
         delete this.storageMap[key];
+        this.storageKeys.delete(key);
+        this.recentKeys.delete(key);
     }
 
     /**

```
Working video after fix


https://user-images.githubusercontent.com/46707890/210214334-60a648a6-413c-4e68-8d23-7dbbb665452a.mov

**Comment by jasperhuangg** [comment] 2023-01-02 09:39
@abdulrahuman5196 awesome write-up! definitely a lot more clear here than the first one you provided on Slack 👍 

Everything sounds pretty good to me, but I'm gonna drop another note in #engineering-chat to get more pairs of eyes on this proposal just in case, since I'm sure there are a few more engineers who have opinions on any changes to the actual Onyx library.

**Comment by abdulrahuman5196** [comment] 2023-01-02 10:25
Thank you @jasperhuangg for hearing me out. Hope this information is sufficient. If not kindly do let me know and I would be able to provide any information requested.

**Comment by fedirjh** [comment] 2023-01-02 14:47
@jasperhuangg, @abdulrahuman5196 , I think `AsyncStorage` will be deprecated on next `Onyx` release , It will be replaced with `quick-sqlite` , check https://github.com/Expensify/react-native-onyx/pull/211 , hence I think it's wise to hold this issue until sqllite deployed to production

**Comment by jasperhuangg** [comment] 2023-01-03 04:34
Thanks for the ping @fedirjh!

@abdulrahuman5196 Let's wait for [the linked PR](https://github.com/Expensify/react-native-onyx/pull/211) to go out and see if we still run into the same problems. Thank you for your patience.

**Comment by tgolen** [comment] 2023-01-03 16:24
Yeah, I agree that with AsyncStorage going away, this is less of a problem. Unfortunately, with the SQLite change already merged, we are stuck with fixing any bugs in Onyx until we are ready to release the SQLite version. This is one of the projects I will be working on this week with @marcaaron. 

I do think that it would probably be a good idea to clean this up anyway (a key with a `null` value doesn't feel quite right), but I do have a question about what will happen to Onyx subscribers (both `withOnyx` as well as `Onyx.connect()`). What will their behavior be when a key is deleted (assuming we go with `solution 1` above)?

**Comment by tgolen** [comment] 2023-01-03 22:33
OK, got it. Thanks for the links! I think that should work OK then.

It sounds like we are going to move forward with the SQLite migration (the update PR is being written right now), so this bug will automatically be going away since AsyncStorage is no longer used. That solves the crash and the bug, so the proposal from @abdulrahuman5196 is really more just a code quality and cleanup issue with low priority. I just wanted to point that out as we move forward with this.

Is everyone OK with that path?

**Comment by abdulrahuman5196** [comment] 2023-01-04 15:51
Thank you @tgolen for notifying. I agree on the assessment if we are moving to SQLite sooner and proposal will be a cleanup action item. 

So what is the process now for this cleanup action item which can be achieved with my proposal. 

Are we going to keep the change aside for it to be taken on a future date or should we do a PR as the code change is already available?

**Comment by tgolen** [comment] 2023-01-05 00:07
I think it would be OK to work on it as long as you don't have any bugs that you're currently working on, and under the assumption that people reviewing your PR will review at a lower priority than any bugs.

**Comment by jasperhuangg** [comment] 2023-01-05 03:43
@tgolen Understood! 

@abdulrahuman5196 please confirm that you don't have anything else on your plate at the moment, and I'll be happy to assign you to this issue and review your PR.

Otherwise, please let me know when you have more time to deal with this low-priority issue.

**Comment by abdulrahuman5196** [comment] 2023-01-05 04:09
Thank you. @jasperhuangg Currently I am not working on any other bugs. I can take this task up.

**Comment by jasperhuangg** [comment] 2023-01-05 04:58
Taking the HOLD off based on Tim's comments [here](https://github.com/Expensify/App/issues/13907#issuecomment-1371565370)

**Comment by marcaaron** [comment] 2023-01-10 20:38
I skipped a lot of this conversation, but I think we can just do a retest to see if `react-native-quick-sqlite` still has this problem and then close this issue? AFAIK there should be no issues with calling `multiMerge()` with objects that have `null` properties for SQLite.

Not to be a stickler. But I think I am **not really OK** with the path of this issue. I would prefer to have Onyx changes discussed publicly. Let's talk about what problem we are solving, what doesn't feel right about it, and then find some clear solution. Again, I didn't read through this issue (I might 100% agree with the proposal) so that is just a high level comment on converting an issue about a "crash" into a "code cleanup".

**Comment by jasperhuangg** [comment] 2023-01-10 21:52
Hey @marcaaron I agree with what you're saying.. no reason to have this issue lying around if it was fixed by the `react-native-quick-sqlite` stuff.

We demoted the priority of this because it became a code-cleanup, but I get what you're saying–nothing is actually broken here. The PR is more there to make us feel "better safe than sorry".

I also feel that it's strange that the key for an item still exists even after it's been removed. 

cc @tgolen what are your thoughts?

**Comment by tgolen** [comment] 2023-01-10 22:59
Yes, this issue is fixed by the release of SQLite and it can be closed now since it should no longer be reproducible.

**Comment by abdulrahuman5196** [comment] 2023-01-12 20:30
Hi, 
given this issue is closed. 
Melvi bot commented to apply for a upwork job, but didn't have a upwork link. 
I was the initial reporter of this issue as well and the null check PR is pending in review. 
What is the compensation process for this issue?

**Comment by abdulrahuman5196** [comment] 2023-01-18 12:32
The onyx version was updated 5 days back itself part of this commit - https://github.com/Expensify/App/commit/e7651685ba1f8b9e4ee54d023a3c917de5179b2b
I don't think we need to merge a separate PR
@jasperhuangg

**Comment by jasperhuangg** [comment] 2023-01-18 16:59
Hey @Christinadobrzyn do we know if there is an Upwork job up for this issue? @abdulrahuman5196 needs to be compensated for discovering the issue and fixing it as well.

**Comment by abdulrahuman5196** [comment] 2023-01-20 12:23
Gentle bump @Christinadobrzyn

**Comment by mallenexpensify** [comment] 2023-01-20 17:20
@abdulrahuman5196 apologies for the delay.  @jasperhuangg @eVoloshchak is total compensation due to @abdulrahuman5196 $1250? $1000 for fix and $250 for reporting? @eVoloshchak are you also due C+ compensation? 

Job is https://www.upwork.com/jobs/~016b62be585203ffd9
It's private but both y'all should be able to see.

**Comment by abdulrahuman5196** [comment] 2023-01-20 17:29
@mallenexpensify 
I am asking this question because I am not sure on the process of this case. The original PR raised was code complete and got all the required approvals within 2 days. But it was put on hold due to sqlite merging. Other the hold time the PR only took **2 days to complete and get all the required approvals**. I think this should be eligible for 50% bonus as the PR was on hold due to different change. Kindly let me know otherwise.
Hold reference: https://github.com/Expensify/react-native-onyx/pull/223#issuecomment-1374196239

**Comment by mallenexpensify** [comment] 2023-01-20 18:29
Ah... an edge case!  Let's see... 

1. In general, if you were hired for a job, were actively working on it (or finished it) then we put the job on hold or closed it, you would be compensated. So.. That should be $1000 (I think)
2. If your PR was merged within 3 business days and it was **before** the issue was put on hold, you'd be eligible for the bonus too. 

I'm going to wait for feedback from @eVoloshchak and/or @jasperhuangg as they're more familiar.  Thanks for the patience here @abdulrahuman5196 and for providing the details above.  We'll get this sorted soon (might not be til Monday cuz it's Friday though)

**Comment by abdulrahuman5196** [comment] 2023-01-20 18:35
Thank you @mallenexpensify. I am fine with either though. Just wanted to check on eligibility. I have accepted the offer in upwork.

**Comment by eVoloshchak** [comment] 2023-01-23 13:49
> @abdulrahuman5196 apologies for the delay. @jasperhuangg @eVoloshchak is total compensation due to @abdulrahuman5196 $1250? $1000 for fix and $250 for reporting? @eVoloshchak are you also due C+ compensation?

@mallenexpensify, I wasn't C+ for this, so not eligible for any payment

**Comment by mallenexpensify** [comment] 2023-01-23 16:59
Thanks @eVoloshchak. 
@jasperhuangg , please review when you have a min

**Comment by jasperhuangg** [comment] 2023-01-24 17:43
Hi guys, since this wasn't really a high priority fix (the bug itself was fixed by the sqlite migration) there was a good reason to hold the review for this for other, higher priority items. The PRs themselves were just code cleanup.

With that being said, I don't think it'd be fair to @abdulrahuman5196 if we didn't pay out the 50% bonus because they were able to get the PRs done quickly–it wasn't their fault that we weren't able to merge the PRs. 

So I think we should still pay out the 50% bonus.

cc @mallenexpensify

**Comment by mallenexpensify** [comment] 2023-01-24 19:07
Thanks @jasperhuangg , I agree.  I just paid @abdulrahuman5196  $1750 - $1000 for the job, 50% for the bonus and $250 for reporting.  Since this was fixed by sqlite, regression test steps shouldn't be needed so I'm closing.

**Closed by mallenexpensify** 2023-01-24 19:07 UTC
Labels: External, Daily, Bug

**Comment by abdulrahuman5196** [comment] 2023-01-24 19:08
Thank you @jasperhuangg and @mallenexpensify
