### ISSUE TITLE
[HOLD for payment 2022-12-20] [$250] Closing split bill doesn't refocus on text-input(composer) if already focused - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10888] opened 2022-09-08 04:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login in web app.
2. Click on any report in LHN (text-input will be focused).
3. Click on + icon on left end of text-input.
4. Click on split bill.
5. Click cross icon on split bill page.

## Expected Result:
Text-input should be focused.

## Actual Result:
Text-input is not focused

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.96-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/189036621-c4249a5f-7eb8-4083-916c-d18854c4e601.mov

**Expensify/Expensify Issue URL:**  
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661325304904489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment] 2022-09-08 09:33
This could definitely be fixed. Putting this in the engineering pool.

**Comment by Luke9389** [comment] 2022-09-12 19:48
Odd, this one doesn't show up on my K2 at all... 🤔

**Comment by Luke9389** [comment] 2022-09-12 19:50
@arielgreen is OOO today (she's heading back to the States). We can export this tomorrow.

**Comment by Luke9389** [comment] 2022-09-13 16:54
Hmm. I wonder why this issue didn't get a C+ assigned

**Comment by thesahindia** [comment] 2022-09-13 17:06
> Hmm. I wonder why this issue didn't get a C+ assigned

Exported label is missing.

**Comment by Luke9389** [comment] 2022-09-13 17:35
Ah right, we need to wait for it to be Exported by @arielgreen

**Comment by arielgreen** [comment] 2022-09-13 23:39
https://www.upwork.com/jobs/~011227dc49a4e5b8d2

**Comment by aneequeahmad** [comment] 2022-09-14 19:31
PROPOSAL### 

**Problem:** 

- When + icon is pressed and `PopoverMenu` is opened. Modal.isVisible is set to `True` and when any of the `MenuItem` is clicked a new `Modal` opens for example `Split bill` and Modal.isVisible is set to `false` and when this modal is closed the value of `prevProps.modal.isVisible` is false and `this.props.modal.isVisible` is also false and in that case `this.focus()` in `componentDidUpdate` is never invoked since  `prevProps.modal.isVisible is false`.


**Solution:**

- We need to stop setting `Modal.isVisible to false when any of the MenuItem in PopoverMenu is clicked since this modal is closed and the other modal is opened so it will retain the value `true` for `prevProps.modal.isVisible` which will cause the condition https://github.com/Expensify/App/blob/44e258cf9e7568629104055bf774fdad92f67448/src/pages/home/report/ReportActionCompose.js#L169-L175

to run and composer will be focused.

**Comment by aneequeahmad** [comment] 2022-09-27 21:10
### PROPOSAL:

- @Santhosh-Sellavel This is my [proposal](https://github.com/Expensify/App/issues/10888#issuecomment-1247213815) where i identified the root cause and proposed the solution that is `to stop the Modal.isVisible` value set to `false`.

I liked this [idea](https://github.com/Expensify/App/issues/10888#:~:text=Maybe%20we%20could%20do%20something%20like%20this%20%2D) to introduce `Modal.state` and setting the `Modal.state` which can have 3 states `open, closed, openingAnotherModel`.

-  On closing of popoverMenu we will set the `Modal.state` value to `openingAnotherModal` and add additional check that Modal.isVisible is false and Modal.state is closed then set `Modal.isVisible to false which will cause this check to run and focus the composer https://github.com/Expensify/App/blob/44e258cf9e7568629104055bf774fdad92f67448/src/pages/home/report/ReportActionCompose.js#L169-L175

**Comment by Santhosh-Sellavel** [comment] 2022-09-28 02:07
@arielgreen 
I'm afraid will not be able to look into this any sooner Busy with existing work items, also limited availability for the next couple of weeks So unassigning this one. Can you reassign this to another C+ by reapplying the external label?

Also, the above [proposal](https://github.com/Expensify/App/issues/10888#issuecomment-1260058143) is yet to be reviewed

**Comment by arielgreen** [comment] 2022-09-29 01:44
Crowdsourcing [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1664415846832409) because autoassigner keeps adding Rushat.

**Comment by arielgreen** [comment] 2022-09-30 01:33
@mananjadhav can you please review the above proposal?

**Comment by mananjadhav** [comment] 2022-10-06 08:28
Sorry it took a bit longer. I reviewed the proposals from @aneequeahmad and @aimane-chnaif. But I am a little lost and confused in what both the proposals are suggesting. 

- I don't like the idea of putting `null`, which means a lot different than true/false
- @aneequeahmad You've mentioned three states, but nowhere I can see which pieces of code will you change to support three states.

I haven't put deep effort in working out the solution, but  I am also wondering if we could somehow use `willAlertModalBecomeVisible` flag instead of changing it to three states.

**Comment by mananjadhav** [comment] 2022-10-07 05:34
Thanks for the update @aimane-chnaif. 

@aneequeahmad While your proposal was still up before I got assigned, are you willing to share an updated proposal? 

I'll review both of them together.

**Comment by aneequeahmad** [comment] 2022-10-07 20:20
@mananjadhav, I'll share the updated proposal over the weekend. Thanks for mentioning.

**Comment by mananjadhav** [comment] 2022-10-10 19:40
Thanks for the patience here everyone. I checked @aimane-chnaif's proposal here https://github.com/Expensify/App/issues/10888#issuecomment-1269798509 and it looks good to me.

cc - @Luke9389 

🎀 👀 🎀 
C+ reviewed

**Comment by aneequeahmad** [comment] 2022-10-11 00:42
@mananjadhav Apologies couldn't find time to post an update to proposal. 
I would like to just mention that i figured out the `root cause` of the issue [here](https://github.com/Expensify/App/issues/10888#:~:text=When%20%2B%20icon%20is,is%20false.) 

Also i posted updated proposal which is non different than the comment that you just mentioned. We can introduce another state in modal that  indicates that another modal is opening so don't set the `Modal.isVisible` to `false` [here](https://github.com/Expensify/App/issues/10888#:~:text=On%20closing%20of%20popoverMenu%20we%20will%20set%20the%20Modal.state%20value%20to%20openingAnotherModal%20and%20add%20additional%20check%20that%20Modal.isVisible%20is%20false%20and%20Modal.state%20is%20closed%20then%20set%20%60Modal.isVisible%20to%20false%20which%20will%20cause%20this%20check%20to%20run%20and%20focus%20the%20composer). Did i miss something ?

**Comment by mananjadhav** [comment] 2022-10-11 00:56
Not sure I understand @aneequeahmad. I didn't agree with any of the proposals when I took over as C+. And to be fair, I waited 3 days to avoid any confusion. Not sure what you mean by non different proposal.

**Comment by aneequeahmad** [comment] 2022-10-11 01:01
Ahhh yes i agree my mistake i'm a bit late couldn't post updates on proposal on time. Totally your decision. Proceed with what you feel is right. 

Thanks

**Comment by Luke9389** [comment] 2022-10-11 21:48
@mananjadhav it looks like there are a few solutions in the comment you linked to. Which one are you endorsing?

**Comment by mananjadhav** [comment] 2022-10-12 18:31
@Luke9389 *Solution 4* is what I endorsed from the comment.

**Comment by Luke9389** [comment] 2022-10-12 21:45
Huh, what's the rationale for not choosing Solution 1 [here](https://github.com/Expensify/App/issues/10888#issuecomment-1245652236)? It seems like it adds consistency between web and mobile. Would it break something?

**Comment by Luke9389** [comment] 2022-10-17 21:48
What do you think @mananjadhav?

**Comment by mananjadhav** [comment] 2022-10-18 18:23
We can work with Solution 1. I was also a bit concerned with the note that was mentioned in the component. Should we go ahead with Solution 1 then?

**Comment by Luke9389** [comment] 2022-10-18 21:23
Lets try it and see if it breaks :)

**Comment by Luke9389** [comment] 2022-10-19 23:57
Yup! Go ahead @aimane-chnaif

**Comment by arielgreen** [comment] 2022-10-20 19:34
Offers sent in Upwork

**Comment by arielgreen** [comment] 2022-10-21 16:45
PR in progress

**Comment by mananjadhav** [comment] 2022-10-21 17:22
PR is raised, but I can't get to this until tomorrow.

**Comment by arielgreen** [comment] 2022-10-24 21:23
Awaiting review, but possibly delayed due to Diwali this week.

**Comment by mananjadhav** [comment] 2022-10-27 17:30
I reviewed the PR, I am in process of testing this.

**Comment by arielgreen** [comment] 2022-11-01 15:58
[Awaiting changes](https://github.com/Expensify/App/pull/12031#issuecomment-1298593885)

**Comment by mananjadhav** [comment] 2022-11-08 04:44
C+ Review is done on this one. Once @Luke9389  is done, we can merge this.

**Comment by arielgreen** [comment] 2022-11-11 02:30
@Luke9389 update please

**Comment by davidcardoza** [comment] 2022-11-14 19:05
@Luke9389 bump

**Comment by Luke9389** [comment] 2022-11-16 19:37
Thanks, was OOO yesterday

**Comment by arielgreen** [comment] 2022-11-16 19:38
bumped Luke again [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1668627449739289)

**Comment by Luke9389** [comment] 2022-11-16 19:47
We're still in the review process on that PR. You can see the conversation has been happening over the past few days (I was OOO yesterday). I think the problem with this issue was that we didn't use the Reviewing label once the PR was up, so the overdue messages got annoying.

**Comment by mananjadhav** [comment] 2022-11-23 06:29
I've tested the PR again. All yours @Luke9389

**Comment by davidcardoza** [comment] 2022-11-30 23:16
@Luke9389 Anything I can help with here?

**Comment by mananjadhav** [comment] 2022-12-05 18:47
@Luke9389 This is waiting on you. Can you help it move forward?

**Comment by Luke9389** [comment] 2022-12-07 00:37
Hey sorry y'all. I've been stacked this week. 👀

**Comment by Luke9389** [comment] 2022-12-07 00:40
Done!

**Comment by mananjadhav** [comment] 2022-12-20 10:50
@arielgreen this is due for payment. Also note for C+ payment that it had a regression.

**Comment by arielgreen** [comment] 2022-12-23 16:48
Timeline:
10/20: Contributor [assigned to issue](https://github.com/Expensify/App/issues/10888#event-7634322003)
12/6: PR [merged](https://github.com/Expensify/App/pull/12031#event-7972455921) - 31 business days ([calculation](https://www.timeanddate.com/date/workdays.html?d1=20&m1=10&y1=2022&d2=06&m2=12&y2=2022&ti=on&)) - -50%
12/13: [Regression](https://github.com/Expensify/App/pull/12031#issuecomment-1349910802) -50% C+

So:
Reporting bonus: $250 to @aneequeahmad 
Contributor pay - $250*.5 = $125 to @aimane-chnaif 
C+ = $250*.5*.5 = $62.50 to @mananjadhav 

Issuing payment now.

**Comment by arielgreen** [comment] 2022-12-23 16:58
Oh! Good catch @aimane-chnaif -- my apologies. [You are correct.](https://expensify.slack.com/archives/C01GTK53T8Q/p1667607226305649) I'll go ahead and bonus you and @mananjadhav the difference. Apologies and thanks for letting me know.

**Comment by mananjadhav** [comment] 2022-12-23 17:26
Thanks for pointing out @aimane-chnaif. @arielgreen did you process the bonus? My upwork page for the contract looks a bit confusing and I can't make out if the difference was applied.

**Closed** 2022-12-23 18:44 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
