### ISSUE TITLE
[$1000] reply text appears as strikethrough on delete parent message in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22810] opened 2023-07-13 13:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. send any message
3. hover on that message and select reply in thread option
4. go to that thread report screen
5. send message in thread
6. go back to parent report screen
7. go offline
8. delete original message
## Expected Result: 
only message should be show as strikethrough text not the reply and counter text
## Actual Result: 
reply text appears as strikethrough on delete parent message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.40-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ee1164c1-66eb-435d-81c5-ef74a896f268

https://github.com/Expensify/App/assets/43996225/9f889048-0c8f-4a5b-902c-8b40c8a5604a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689249243007879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01783ca3e14a37fff1</li>
        <li>Upwork Job ID: 1680963716129968128</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by Victor-Nyagudi** [comment] 2023-07-14 12:50
I'm a little confused on the expected behavior here. 

If the message is deleted, the reply below it shouldn't be struck through?

Shouldn't deleting the parent message also delete the replies?

**Comment by gadhiyamanan** [comment] 2023-07-14 12:53
>Shouldn't deleting the parent message also delete the replies?

no, it will not delete replies. you can check slack as well

**Comment by kevinksullivan** [comment] 2023-07-17 15:33
Reproduced ad sending to the pool

**Comment by muhammadkashaf** [comment] 2023-07-17 20:29
Proposal

Problem Statement:
The issue at hand is that in OfflineWithFeedback, when a parent message is deleted in offline mode, the reply text appears as strikethrough, even though the reply itself should not be affected by the deletion.

Root Cause:
The root cause of the problem lies in the way strikethrough is applied to all children in OfflineWithFeedback. In this specific case, the reply text is getting the strikethrough formatting because it is considered a child, although it should remain unaffected by the deletion of the parent message.

Proposed Solution:
To solve the problem, we can make the following changes in the OfflineWithFeedback component, specifically at Line 77 in the file "App/src/components/OfflineWithFeedback.js."


function applyStrikeThrough(children) {
    // Check if the child has a childReportID prop, if yes, then skip applying strikethrough
    if (children.props.children?.props?.childReportID) {
        return children;
    }
    // Apply strikethrough to all other children
    return <strike>{children}</strike>;
}

This proposed solution ensures that strikethrough will not be applied to any child that has the "childReportID" prop, which includes the reply text in this case. Only the other children will receive the strikethrough formatting, representing the deleted parent message.

Alternative Solution (Optional):
Another way to achieve the same result is as follows:

function applyStrikeThrough(children) {
    // Check if the child has a childReportID prop, if yes, then skip applying strikethrough
    if (children.props.children && children.props.children.props && children.props.children.props.childReportID) {
        return children;
    }
    // Apply strikethrough to all other children
    return <strike>{children}</strike>;
}

Both proposed solutions work effectively to prevent the strikethrough formatting from being applied to the reply text, resolving the issue in OfflineWithFeedback. The choice between the two solutions can be made based on code readability and any specific coding conventions followed in the project.

**Comment by ShogunFire** [comment] 2023-07-18 11:36
So what happen if we delete the replies offline ? Should the line with "x replies" be striked through ? I think we should pass a new parameter to applyStrikeThrough that dictate the type of child we want to strike through, otherwise it's going to be hard to handle every cases (I think I saw other issues with this method)

**Comment by kevinksullivan** [comment] 2023-07-24 15:22
Hi @fedirjh did you get a chance to review this last week?

**Comment by kevinksullivan** [comment] 2023-08-04 22:29
Hi @laurenreidexpensify I am going OOO for the week so tapping you in the interim. Thanks!

**Comment by laurenreidexpensify** [comment] 2023-08-07 12:31
@fedirjh bump on proposal review above pls! thanks

**Comment by sophiepintoraetz** [comment] 2023-08-09 22:25
Bumped @fedirjh in [slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1691619921206879)

**Comment by sophiepintoraetz** [comment] 2023-08-14 17:01
Just need a review from @fedirjh! And @kevinksullivan - I think you're back now so gracefully bowing out 👍

**Comment by ShogunFire** [comment] 2023-08-15 11:10
@fedirjh You are right that this is strange but looking directly at child.props.stopOfflineWithFeedbackStyle doesn't work because the opacity of the parent div is applied to all his children.
If we have:

```
<div1 opacity = 0.5>
    <div2 opcaity = 1>
    </div>
</div>
```
Div2 will appear with 0.5 opacity :/ 

If it's a problem, we can try to use rgba background instead of opacity, I will try

**Comment by ShogunFire** [comment] 2023-08-15 12:20
## Proposal
[Updated](https://github.com/Expensify/App/issues/22810#issuecomment-1660339902)

I put in an alternative proposal that is better I think, we can play with OfflineWithFeedback and NoOfflineStyleForChild to handle every cases. For example we could have another nested OfflineWithFeedback in ReportActionItemThread and another NoOfflineStyleForChild in it

**Comment by kevinksullivan** [comment] 2023-08-21 22:02
@fedirjh when will you be able to get to these reviews?

**Comment by ShogunFire** [comment] 2023-08-24 13:42
Yes that's a better solution since it allow us to declare NoOfflineStyleForChild wherever we want and not only as a children of OfflineWityhFeedback, the challenge will be to make this method efficient because if we have a depth of 10 and the child that is the more deep has stopOfflineWithFeedbackStyle it means at each depth we will have to go through the whole children tree

**Comment by ShogunFire** [comment] 2023-08-24 15:02
Ah you are right, I though we had to go through the tree multiple time but I think we can find a solution without doing that.

>  I am not sure if it can be a direct child of OfflineWithFeedback.

Again you are right, my proposal was kind of a general idea but was tricky to put in place, we would have had to add some OfflineWithFeedbackI think but if we apply your suggestion it should be good.

**Comment by ShogunFire** [comment] 2023-08-24 18:05
@fedirjh So far I have this, it's almost working but the opacity is applied multiple times so I will find a way later to apply the style only to the highest possible parent

```

function applyOfflineStyle(children, needsOpacity, needsStrikeThrough) {
    var shouldParentApplyOfflineStyle = true;
    return [React.Children.map(children, (child) => {
        if (!React.isValidElement(child)) {
            return child;
        }
        
        if(child.props.stopOfflineWithFeedBackStyle){
            shouldParentApplyOfflineStyle = false;
            return child;
        }
        var props = {style: child.props.style};
        var shouldApplyStyle = true;
        if(child.props.children){
            [props.children, shouldApplyStyle] = applyOfflineStyle(child.props.children, needsOpacity, needsStrikeThrough);
        }
        
        if(!shouldApplyStyle){
            shouldParentApplyOfflineStyle = false;
            return React.cloneElement(child, props);
        }
       
        if(needsStrikeThrough){
            props.style = StyleUtils.combineStyles(props.style, styles.offlineFeedback.deleted, styles.userSelectNone);
        }
        if(needsOpacity){
            props.style = StyleUtils.combineStyles(props.style, styles.offlineFeedback.pending);
        }
        return React.cloneElement(child, props);
    }), shouldParentApplyOfflineStyle];
}

```

**Comment by ShogunFire** [comment] 2023-08-29 00:36
I spent a lot of time on this and at some point it stopped applying the style, I found out that it was working in theory but the highest parent, the one we apply the opacity to was ShowContextMenuContext.Provider which is never displayed, so I added a wrapperView to which I apply the style. It is working well. Here is the code:

```
function applyStyleToComponent(component, needsOpacity, needsStrikeThrough){
    var styleOffline = {};
    if(needsStrikeThrough){
        styleOffline = StyleUtils.combineStyles(styles.offlineFeedback.deleted, styles.userSelectNone);
    }
    if(needsOpacity){
        styleOffline = StyleUtils.combineStyles(styleOffline, styles.offlineFeedback.pending);
    }
    return <View style={styleOffline}>{component}</View>;

}
 
function applyOfflineStyleRecursively(component, needsOpacity, needsStrikeThrough, depth = 0) {

    // Not a valid element, no descendant
    if (!React.isValidElement(component)) {
        return [component, false];
    }

    // stopOfflineWithFeedBackStyle so we do nothing and return true
    if(component.props.stopOfflineWithFeedBackStyle){
        return [component, true];
    }
    
    // We go through the descendants tree and apply the style to children that don't have descendant with the stopStyle prop
    var newChildren = null;
    var foundChildWithProps = false;
    if(component.props.children){
        newChildren = React.Children.map(component.props.children, (child) => {
            const [resultChild, hasDescendantWithStopOfflineStyle] = applyOfflineStyleRecursively(child, needsOpacity, needsStrikeThrough, depth + 1);
            if(hasDescendantWithStopOfflineStyle){
                foundChildWithProps = true;
                return resultChild;
            }
            else{
                return applyStyleToComponent(resultChild, needsOpacity, needsStrikeThrough);
            }
        });
    }

    if(!foundChildWithProps){
        //We don't actually apply the changes that we made because an ancester will apply them
        if(depth != 0)
            return [component, false];
        else {
            // We are at the root, we need to apply the style to the root
            return [applyStyleToComponent(component, needsOpacity, needsStrikeThrough), false];
        }
    }
    return [React.cloneElement(component, {children: newChildren}), true];
}


```

**Comment by kevinksullivan** [comment] 2023-09-13 03:10
Hi @fedirjh can you provide an update here?

**Comment by ShogunFire** [comment] 2023-09-14 16:52
## Proposal
[Updated](https://github.com/Expensify/App/issues/22810#issuecomment-1660339902)

I updated my proposal with the current solution and made it more clear because it was all over the place. Can you check this @fedirjh ?

**Comment by kevinksullivan** [comment] 2023-09-27 04:23
What's the latest here @fedirjh ? I will need to reassign this as it's been a while if we can't get a review in the next day.

**Comment by kevinksullivan** [comment] 2023-10-03 22:09
Reassigning

**Comment by kevinksullivan** [comment] 2023-10-09 16:20
@rushatgabhane will you be able to review this?

**Comment by mvtglobally** [comment] 2023-10-12 03:51
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2023-10-17 15:15
Issue not reproducible during KI retests. (Second week)

**Closed** 2023-10-17 16:27 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug

**Comment by ShogunFire** [comment] 2023-10-17 17:08
Ok so for some reason the strike through is not applied anymore on "x replies" BUT the opacity is still applied and you can't click on "x replies" I think this was part of the bug.


https://github.com/Expensify/App/assets/19537677/6ebd4efb-9bf6-4d42-b0ca-86847174fbf9

**Comment by ShogunFire** [comment] 2023-10-17 18:46
I disagree, the replies haven3t changed so they should not be grey

**Comment by ShogunFire** [comment] 2023-10-26 16:54
No answer on the slack thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1697569221310029
