### ISSUE TITLE
[$500]  LHN - A group conversation disappears from LHN after creating a duplicate Split Bill

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29635] opened 2023-10-14 22:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with the same gmail account on the primary and secondary devices
3. Disconnect the internet connection on the primary device
4. On the secondary device, split the account with 2 gmail users
5. On the primary test device (it should be offline), create the same split account with the same 2 users
6. Turn on the internet connection on the primary test device

## Expected Result:
A group conversation should not disappear from LHN after creating a duplicate Split Bill offline and then going online when using gmail accounts

## Actual Result:
Group conversation disappears from LHN after creating a duplicate Split Bill offline and then going online when using gmail accounts

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/ed661193-6284-47fa-857d-173aa9cb5342

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a00f7b57314a338</li>
        <li>Upwork Job ID: 1713759725680902144</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2023-10-16 04:07
I believe this is a duplicate of https://github.com/Expensify/App/issues/28491

**Comment by lschurr** [comment] 2023-10-16 19:17
@situchan could you double check? Should we close this one?

**Closed** 2023-10-19 15:52 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
