### ISSUE TITLE
Assignee- Console error displayed on adding a assignee

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19462] opened 2023-05-23 16:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19335

## Action Performed:
1. Login with any Expensifail account
2. Verify that this account has at least one contact that is an account created by phone number
3. Go to FAB -> Assign Task -> Enter a title and description and navigate to next page
4. Click on the "Assignee" and enter the correct phone number

## Expected Result:
Verify that the account with phone number is added as assignee and no error appears

## Actual Result:
404 error message displayed in console

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/b9ed2458a443d3607bd6fcb109575bf4cd4f9708f5d0ff8936ce2070cd0d2b93

https://platform.applause.com/services/links/v1/external/500cd644c040b711df9e9026817add6933095d0b5e513790cd6eadb028ed9ad2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b8fec9274038ed9</li>
        <li>Upwork Job ID: 1676739867017773056</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-05-24 01:21
@kbecciv do you have a phone number account I can use to test with? I'm getting an error when trying to use my google phone number "The provided phone number belongs to a landline or VoIP, please use your email address instead.
" 
and... when using my other number I get
> Unexpected error while posting the comment, please try again later
Report no longer exists

**Comment by situchan** [comment] 2023-05-24 04:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error shows after selecting assignee on task assignee selector page

### What is the root cause of that problem?
This came from lack knowledge of lifecycle in functional component.
In `TaskAssigneeSelectorModal`, there's `search_render` measurement.
Timer should start on component mount and should end only on OptionsSelector onLayout callback or component unmount.
In current logic, there are more cases of start/end timer: whenever props or search value are changed because of **`[updateOptions]` dependency**.
https://github.com/Expensify/App/blob/d70b7462cd698a50aa121310f69b815e9f7cc9fa/src/pages/tasks/TaskAssigneeSelectorModal.js#L110-L114
So finally these are call orders in Timing.js:
- end
- start
- end
- start
- getEnvironment promise return
- getEnvironment promise return (error happens here because key is removed by [this line](https://github.com/Expensify/App/blob/d70b7462cd698a50aa121310f69b815e9f7cc9fa/src/libs/actions/Timing.js#L47))
- start
- end
- getEnvironment promise return

### What changes do you think we should make in order to solve the problem?
call Timing.start only on component mount, Timing.end only on component unmount or OptionsSelector onLayout callback.
To do this, define new useEffect hook with **empty array dependency**:
```
    useEffect(() => {
        Timing.start(CONST.TIMING.SEARCH_RENDER);
        Performance.markStart(CONST.TIMING.SEARCH_RENDER);

        return () => {
            Timing.end(CONST.TIMING.SEARCH_RENDER);
            Performance.markEnd(CONST.TIMING.SEARCH_RENDER);
        };
    }, []);
```

### What alternative solutions did you explore? (Optional)
Early return if key [doesn't](https://github.com/Expensify/App/blob/d70b7462cd698a50aa121310f69b815e9f7cc9fa/src/libs/actions/Timing.js#LL31C4-L31C10) exist [here](https://github.com/Expensify/App/blob/d70b7462cd698a50aa121310f69b815e9f7cc9fa/src/libs/actions/Timing.js#L36)

**Comment by kbecciv** [comment] 2023-05-26 14:06
@mallenexpensify Sorry, I don't have any extra phone account for testing, only my personal.

**Comment by situchan** [comment] 2023-05-26 14:27
@mallenexpensify this bug is not specific to phone account. Reproducible even for emails

**Comment by mallenexpensify** [comment] 2023-05-26 21:39
Confirmed bug, was only able to get an error when used a phone number though, not email.  
@yuwenmemon internal or external? 

<img width="449" alt="image" src="https://github.com/Expensify/App/assets/22508304/31a1cbe9-c23f-480f-a3e4-c989e89c74ff">

**Comment by situchan** [comment] 2023-05-26 21:43
@mallenexpensify The error in your screenshot is different issue - https://github.com/Expensify/App/issues/19203

**Comment by mallenexpensify** [comment] 2023-05-31 02:33
- https://github.com/Expensify/App/issues/19203#issuecomment-1569408379
Checking on the above as folks are hired for that issue and the fix for that might affect this (or.. that's my thinking/hoping)

**Comment by situchan** [comment] 2023-05-31 03:04
@mallenexpensify this is duplicated with https://github.com/Expensify/App/issues/19772. We can close either one.

**Comment by sobitneupane** [comment] 2023-05-31 04:35
@mallenexpensify I don't think fix of the issue https://github.com/Expensify/App/issues/19203 will fix this issue. Looks like a different issue.

**Comment by mallenexpensify** [comment] 2023-06-01 03:40
Thanks @situchan , I put this on hold pending
- https://github.com/Expensify/App/issues/19772

**Comment by yuwenmemon** [comment] 2023-06-12 17:17
On HOLD

**Comment by mallenexpensify** [comment] 2023-06-21 17:12
Help PR is on staging as of 14 hours ago
https://github.com/Expensify/App/pull/20840#issuecomment-1599976955

**Comment by mallenexpensify** [comment] 2023-06-30 16:37
Taking off hold the PR associated with #19772 hit production
https://github.com/Expensify/App/pull/20840

Bumping back to Daily, will test again again soon

**Comment by mallenexpensify** [comment] 2023-07-05 23:48
@mananjadhav and @yuwenmemon , do you think this can be External?

**Comment by mananjadhav** [comment] 2023-07-06 20:20
I tried from 2-3 accounts I am unable to reproduce this. @kbecciv can you confirm if we're missing any steps? and what do we mean by correct number?

@mallenexpensify did you do anything different from the steps mentioned in the GH issue?

<img width="1512" alt="Screenshot 2023-07-07 at 1 49 07 AM" src="https://github.com/Expensify/App/assets/3069065/2f01b2d2-a263-43dc-9634-8fc9d3625a1e">

**Comment by mallenexpensify** [comment] 2023-07-11 04:49
@kbecciv , can you see if you can still reproduce please? Thx

**Comment by kbecciv** [comment] 2023-07-12 11:16
Hello @mallenexpensify Checking, update you shortly

**Comment by kbecciv** [comment] 2023-07-12 12:11
App is crash after create a task on build 1.3.39.5

https://github.com/Expensify/App/assets/93399543/b5ad82f3-088e-494e-9c63-dee14c021f1b

**Comment by mallenexpensify** [comment] 2023-07-14 21:42
I tried to reproduce and wasn't able to, it worked as expected when I used 6309177596, the one you used above @kbecciv .  I ran into issues when I tried to use my personal number, I think it's because it used to be a secondary login for my main account.

**Comment by mallenexpensify** [comment] 2023-07-17 20:21
Checking on what the current process is for issues that can't be reproduced https://stackoverflowteams.com/c/expensify/questions/16989

**Comment by yuwenmemon** [comment] 2023-07-20 23:41
I can't reproduce either - I'm just going to close this out.

**Closed by yuwenmemon** 2023-07-20 23:41 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
