### ISSUE TITLE
[$250] Profile - Timezones listing page displayed empty in Safari

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42274] opened 2024-05-16 11:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+omq233@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Click on Profile icon
3. Select Profile > Timezone
4. Click on Timezone

## Expected Result:
Timezones listing page should be displayed with timezones

## Actual Result:
Timezones listing page is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/66889583-1acb-4e14-8258-7dd5222f39a6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2c71e8eb905ea6d</li>
        <li>Upwork Job ID: 1793075625564327936</li>
        <li>Last Price Increase: 2024-05-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by greg-schroeder** [comment] 2024-05-22 00:25
Sending through to `external`

**Comment by nkdengineer** [comment] 2024-05-22 03:41
Dupe of https://github.com/Expensify/App/issues/40483, we should reopen the original issue

**Comment by Christinadobrzyn** [comment] 2024-05-22 03:50
I think we need to determine if this issue and this [issue](https://github.com/Expensify/App/issues/40483#issuecomment-2123810738) have the same root. if we're not sure, I think we should fix this and put https://github.com/Expensify/App/issues/40483#issuecomment-2123810738 on Hold since it's affecting only RP currency whereas this seems to be affecting a larger group of users.

**Comment by nkdengineer** [comment] 2024-05-22 03:54
Reposting my proposal here from https://github.com/Expensify/App/issues/40483, in case we want to fix it in this GH.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Timezones listing page should be displayed with timezones

### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/components/SelectionList/BaseSelectionList.tsx#L234), we have the logic to `scrollToIndex` if the focused index changes in `useArrowKeyFocusManager`.

In `useArrowKeyFocusManager` [here](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/hooks/useArrowKeyFocusManager.ts#L71), we call `onFocusedIndexChange` in an `useEffect`, so it will be called in first render, even if the `focusedIndex` did not change.

This first render of `useArrowKeyFocusManager` (and scrolling) happens even before the `SectionList` [here](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/components/SelectionList/BaseSelectionList.tsx#L595) finishes rendering (and `onLayout` called), so the scrolling will interfere with the SectionList rendering, causing the blank page to show.

This is a known issue and avoided that by only `scrolling` to the focused index after the `onLayout` was already called [here](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/components/SelectionList/BaseSelectionList.tsx#L386). But due to the first rendering in `useArrowKeyFocusManager`, scrolling is still called before `onLayout`.

### What changes do you think we should make in order to solve the problem?

In `useArrowKeyFocusManager` [here](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/hooks/useArrowKeyFocusManager.ts#L71), we need to call `onFocusedIndexChange` when the focused index actually changes (not on first render). We can use `usePrevious` or `firstRenderRef` (like [here](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/libs/Navigation/NavigationRoot.tsx#L63)) for this.
```
const prevIsFocusedIndex = usePrevious(focusedIndex);

useEffect(() => {
    if (prevIsFocusedIndex === focusedIndex) {
        return;
    }
    onFocusedIndexChange(focusedIndex)
}, [focusedIndex, prevIsFocusedIndex]);
```

### What alternative solutions did you explore? (Optional)
In [scrollToIndex](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/components/SelectionList/BaseSelectionList.tsx#L210), early return if `onLayout` of `SectionList` wasn't called yet. To do this, we need to store `isInitialSectionListRender` in a `ref` like `isInitialSectionListRenderRef` too and use it, also we need to make sure to set `isInitialSectionListRenderRef` to `false` before [this line](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/components/SelectionList/BaseSelectionList.tsx#L377) to make sure the initial scroll still works fine.

An alternative is to still reuse `isInitialSectionListRender` state, but we should use `animated: false` (or add a new param) to distinguish [the first scroll](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/components/SelectionList/BaseSelectionList.tsx#L377). So we always allow the first scroll, if it's not the first scroll, `isInitialSectionListRender` is `true`, then we early return and don't scroll.

**Comment by nkdengineer** [comment] 2024-05-22 03:55
> I think we need to determine if this issue and this https://github.com/Expensify/App/issues/40483#issuecomment-2123810738 have the same root.

Yes it has the same RCA.

**Comment by s77rt** [comment] 2024-05-22 20:59
@Christinadobrzyn Indeed we can close this one as a dupe.

**Comment by Christinadobrzyn** [comment] 2024-05-23 06:04
okay closing this in favour of https://github.com/Expensify/App/issues/40483

**Closed by Christinadobrzyn** 2024-05-23 06:04 UTC
Labels: External, Daily, Help Wanted, Bug
