### ISSUE TITLE
[HOLD for C+ newdot payment] [$1000] Burger menu overlaps with "Expensify" logo in top left corner of the page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25646] opened 2023-08-22 02:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Login and then open Settings.
2.open help.
## Expected Result: 
Drawer button should not overlay on Expensify logo.
## Actual Result: 
Drawer button is overlaying on Expensify logo.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/000f1391-24e0-49fb-9d38-75b0eee62dc7

<img src="https://github.com/Expensify/App/assets/43996225/d5c55862-f726-4ab5-86fe-af6aeed30acb" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Harshizonnet
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691834089242369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5ada1183af69b00</li>
        <li>Upwork Job ID: 1693866584422825984</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Contributor | 26399647</li>
</ul></li>
    </ul>
</details>

**Comment by getusha** [comment] 2023-08-22 07:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN toggle icon overlaps with 'expensify' logo
### What is the root cause of that problem?
The header button is positioned absolute which makes it overlap with any other element if the viewport is resized to it's break point.

https://github.com/Expensify/App/blob/660930886e10b909e0c774a2d0b7354a4685324b/docs/_sass/_main.scss#L270
### What changes do you think we should make in order to solve the problem?


We should remove the position absolute from here:
https://github.com/Expensify/App/blob/660930886e10b909e0c774a2d0b7354a4685324b/docs/_sass/_main.scss#L270
and add `padding-right: 24px` which seems the standard in our case (used on the header padding)

then we will move the header button to the element below inside "flex"

https://github.com/Expensify/App/blob/660930886e10b909e0c774a2d0b7354a4685324b/docs/_layouts/default.html#L25-L28

move this to inside

https://github.com/Expensify/App/blob/660930886e10b909e0c774a2d0b7354a4685324b/docs/_layouts/default.html#L29-L37

<img width="500" alt="Screenshot 2023-08-22 at 10 04 04 AM" src="https://github.com/Expensify/App/assets/75031127/2f0f293c-5114-445b-bac1-3395325ba98f">

### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2023-08-22 07:07
I think it is regression of https://github.com/Expensify/App/pull/24299

**Comment by studentofcoding** [comment] 2023-08-22 10:46
Nope, It's already like that before the PR of https://github.com/Expensify/App/pull/24299

**Comment by neonbhai** [comment] 2023-08-22 12:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Burger menu overlaps with "Expensify" logo in top left corner of the page

### What is the root cause of that problem?
The logo element is not padded for the burger icon that appears for small screen devices.

### What changes do you think we should make in order to solve the problem?
We should add `padding-left: 44px` to the logo when it is rendered in a small screen device to compensate for the burger icon's presence.


### What alternative solutions did you explore? (Optional)
xx

**Comment by studentofcoding** [comment] 2023-08-22 13:41
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
Burger menu overlaps with "Expensify" logo in top left corner of the page

## What is the root cause of that problem?
The Mobile Menu, Logo, and Search Toggle still do not have an exact structure on Mobile.

## What changes do you think we should make in order to solve the problem?
The Mobile Menu, Logo, and Search Toggle should have different wrappers instead so we can use `justify-content: space-between;` and make them in one Flex wrapper.

1. Make Mobile Menu, Logo, and Search Toggle have separate wrapper On `default.html`
```
<div class="lhn-header">
            <div id="header-button">
                <img id="angle-up-icon" src="/assets/images/arrow-up.svg" class="base-icon hide"></img>
                <img id="bars-icon" src="/assets/images/menu.svg" class="base-icon"></img>
            </div>
            <div class="flex">
                <div>
                    <a href="/">
                        <img src="/assets/images/expensify-help.svg" class="logo" />
                    </a>
                </div>
            </div>
            <div class="flex search-icon-wrapper">
                <!-- Search icons that'll open the Sidebar Search sections -->
                {% include search-toggle.html %}
            </div>
        </div>
```

2. Add `display: flex;` & `justify-content: space-between;` on `.lhn-header` `_main.scss`

3. Add `search-icon-wrapper` class into `_search-bar.scss`
```
.search-icon-wrapper {
    margin: auto 0;
}
```

## What alternative solutions did you explore? (Optional)
None

## Result
https://github.com/Expensify/App/assets/20473526/8ab0140c-0e93-4656-a89c-594471e4cd34

**Comment by yoodule-dev** [comment] 2023-08-22 17:08
### Please re-state the problem that we are trying to solve in this issue.
Fix burger menu overlapping with "Expensify" logo in top left corner of the page. Also search icon is requires some padding/margin.

### What is the root cause of that problem?
The header button is positioned absolute which makes it overlap with any other element if the view-port is resized to it's break point.

### What changes do you think we should make in order to solve the problem?
A good design approach will be to reduce the number of items displayed in the header
We can update the header to only have an hamburger icon and show a search box in the Burger menu

### What alternative solutions did you explore? (Optional)
Giving a margin left to the logo on smaller screen.
But the issue is that we will have much item there which might still be an issue when a screen is much smaller

Attached is a sample of what the solution should look like
https://www.loom.com/share/0af59e8066c74e3db45c1b3b6e0183be?sid=952a2ece-2066-486e-92eb-b0694804e9ba

**Comment by yoodule-dev** [comment] 2023-08-22 17:14
Contributor details
Your Expensify account email: dev@yoodule.com
Upwork Profile Link: https://www.upwork.com/ag/yoodule/

**Comment by yoodule-dev** [comment] 2023-08-22 17:14
Contributor details
Your Expensify account email: [dev@yoodule.com](mailto:dev@yoodule.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~019fb991cf334b5944

**Comment by yoodule-dev** [comment] 2023-08-22 17:17
Contributor details
Your Expensify account email: dev@yoodule.com
Upwork Profile Link: https://www.upwork.com/ag/yoodule/

**Comment by yoodule-dev** [comment] 2023-08-22 17:18
Contributor details
Your Expensify account email: dev@yoodule.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019fb991cf334b5944

**Comment by yoodule-dev** [comment] 2023-08-22 17:19
Contributor details
Your Expensify account email: dev@yoodule.com
Upwork Profile Link: https://www.upwork.com/ag/yoodule/

**Comment by Hanawa02** [comment] 2023-08-24 20:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The burger menu overlaps with the Expensify logo, which makes it difficult for users to be able to see that a burger menu actually exists.

### What is the root cause of that problem?
The root cause is an absolute positioning applied to the burger menu.

### What changes do you think we should make in order to solve the problem?
- I would simplify the header structure, currently, there are some unnecessary divs that do not provide any benefit, the `flex` class applied to one of the divs can be transferred to the div with `lhn-header` class.
- I would remove the absolute positioning from the burger menu, and add an adequate, responsive margin-right to the burger menu.

- For accessibility purposes, I would also suggest changing the burger menu from a div to a button, but that is not related to the issue.

**Comment by Hanawa02** [comment] 2023-08-24 20:54
Contributor details
Your Expensify account email: laura@laura-melo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0197ce8d101b2bec80

**Comment by studentofcoding** [comment] 2023-08-27 13:33
> Thanks for the proposals everyone. I think that `position: absolute` is really not needed here and we can fix this by removing the absolute positioning and adding appropriate padding. I also think that we should fix the search icon's positioning (which looks like broken on tablet). 
> 
> 
> 
> @getusha's [proposal](https://github.com/Expensify/App/issues/25646#issuecomment-1687594198) was the first one to cover all of these points. Let's go with them.
> 
> 
> 
> 🎀 👀 🎀 C+ reviewed
> 
> 

Have you seen my proposal @allroundexperts, based on the needs we need to cover the tables also, and i believe its better to cover it via adding flex and wrap the menu button, logo, and search icon vs add manual padding

**Comment by francoisl** [comment] 2023-08-29 21:07
Makes sense to me, let's go with @getusha's solution.

**Comment by getusha** [comment] 2023-08-30 13:39
@allroundexperts [PR](https://github.com/Expensify/App/pull/26284) is ready!

**Comment by Harshizonnet** [comment] 2023-09-01 11:24
> 📣 @Harshizonnet! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```

Contributor details
Your Expensify account email: harshvardhan@izonnet.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019236ecd910ad150f

**Comment by Harshizonnet** [comment] 2023-09-02 09:24
> 



> The BZ member will need to manually hire Harshizonnet for the Reporter role. Please store your Upwork details and apply to our Upwork job so this process is automatic in the future!

I have applied for the Upwork job.

**Comment by kadiealexander** [comment] 2023-09-12 03:53
Payouts due:

- [ ] Issue Reporter: $250 @Harshizonnet
- [ ] Contributor: $1000 @getusha
- [ ] Contributor+: $1000 @allroundexperts

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/25646#issuecomment-1701903845)

Upwork job is [here](https://www.upwork.com/jobs/~01a5ada1183af69b00).

**Comment by kadiealexander** [comment] 2023-09-20 05:02
This can be closed after @allroundexperts is paid via NewDot. Payment summary is [here](https://github.com/Expensify/App/issues/25646#issuecomment-1714921859).

**Comment by kadiealexander** [comment] 2023-10-03 21:45
Not overdue.

**Comment by JmillsExpensify** [comment] 2023-10-05 12:49
$1,500 payment for @allroundexperts approved based on BZ summary.

**Closed** 2023-10-13 04:50 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug
