### ISSUE TITLE
mWeb Android/Chrome - Compose box is hidden when we delete edited message

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24016] opened 2023-08-01 17:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app in android chrome
2. Open any report
3. Send any text
4. Write some text in compose box and long press message sent in step 3 and edit the message
5. Remove all the text and click send, in delete popup, click on delete
6. Observe that composer is now not visible

## Expected Result:
App should display the composer after we delete edited message

## Actual Result:
App does not display the composer after we delete edited message in android chrome

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48-3
**Reproducible in staging?:** Y 
**Reproducible in production?:** Needs repro
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/077a2e60-4a14-41de-8b26-84a3f97b16e0 

https://github.com/Expensify/App/assets/43995119/05da3129-20d3-4b0b-862c-916e1af8a8e0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690903191529089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment] 2023-08-01 17:07
@bfitzexpensify We are near closure of the checklist. Contributor is not able to repro on PROD, i need a bit more time to validate PROD. If you can check on your side as well to confirm if its a blocker or no, would be great

**Comment by marcochavezf** [comment] 2023-08-01 19:16
I'm also not able to reproduce it on prod, investigating what caused the issue

**Comment by s-alves10** [comment] 2023-08-01 20:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Compose box is hidden when we delete message by saving empty draft

### What is the root cause of that problem?

When we save the empty draft, delete confirmation modal appears and the input gets blurred. On select delete, deleteDraft is called, but isFocusedRef.current is false and the main composer doesn't show
https://github.com/Expensify/App/blob/5034433c46088208bea475476d2be98f623ac0af/src/pages/home/report/ReportActionItemMessageEdit.js#L203-L206

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to check if deletion is from confirm modal
Change the above code to
```
        if (isFocusedRef.current || ReportActionContextMenu.isActiveReportAction(props.action.reportActionID)) {
            ComposerActions.setShouldShowComposeInput(true);
            ReportActionComposeFocusManager.focus();
        }
```

Removes the `isFocused` state. We can use `isFocusedRef` instead.

This works fine


### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2023-08-01 20:25
We will handle this as a part of https://github.com/Expensify/App/pull/23618 since it's a regression

**Comment by s-alves10** [comment] 2023-08-01 20:26
@s77rt 

Do you agree with the solution I proposed?

**Comment by marcochavezf** [comment] 2023-08-01 20:30
Hi @s-alves10, I tested the proposed change but the compose input is still not shown after following the reproduction steps:

https://github.com/Expensify/App/assets/6829422/b9826036-d80b-4c4e-8134-1178fc463b78

**Comment by s77rt** [comment] 2023-08-01 20:33
@s-alves10 Yes.

We should show the Main Composer only if we are deleting the active report action.

A report action is considered active if it's focused, have the context menu open or have the emoji picker open - we need to be sure we are not missing any other cases.

**Comment by s-alves10** [comment] 2023-08-01 20:34
Yes. We've missed the deletion by saving empty draft

**Comment by marcochavezf** [comment] 2023-08-01 20:47
> We will handle this as a part of https://github.com/Expensify/App/pull/23618 since it's a regression

Ok, I'm going to revert the PR that introduced the regression to unblock the deployment

**Comment by s-alves10** [comment] 2023-08-01 20:48
Follow up PR will be created in an hour

@marcochavezf

**Comment by marcochavezf** [comment] 2023-08-01 20:50
Ok sounds good, let me know when it's ready, otherwise we'd need to revert

**Comment by s-alves10** [comment] 2023-08-01 20:53
@s77rt 
Can you test with the branch https://github.com/s-alves10/App/tree/fix/issue-24016?

**Comment by s77rt** [comment] 2023-08-01 21:14
@s-alves10 Please raise a PR, I will test asap. You need to test that as well.

**Comment by s77rt** [comment] 2023-08-01 23:14
@s-alves10 Let's continue proposal discussion here.

**Comment by marcochavezf** [comment] 2023-08-02 00:14
The PR that caused the regression was [reverted](https://github.com/Expensify/App/pull/24025), so I'm going to close this issue since it's no longer happening on staging

**Comment by dhanashree-sawant** [comment] 2023-08-02 02:57
Hi @marcochavezf, @s77rt, it seems like issue was useful to trigger the solution, will it be eligible for reporting bonus?

**Comment by marcochavezf** [comment] 2023-08-02 21:35
Oh sorry @dhanashree-sawant, I think yes since it was a deploy blocker and fixed with the revert. Reopening for payment cc @bfitzexpensify

**Comment by bfitzexpensify** [comment] 2023-08-03 17:13
Cool, this has been paid out.

**Closed by bfitzexpensify** 2023-08-03 17:13 UTC
Labels: Engineering, Daily, Bug

**Comment by s77rt** [comment] 2023-08-24 22:07
I think this is reproducible again

**Comment by s77rt** [comment] 2023-08-30 22:22
This actually got reported again https://expensify.slack.com/archives/C049HHMV9SM/p1692747837798019

**Comment by s-alves10** [comment] 2023-08-31 00:12
I think this should be fixed in https://github.com/Expensify/App/issues/23908
