### ISSUE TITLE
[$250] Request Money - App crashed for specific account when requesting the money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10272] opened 2022-08-05 19:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with applausetester+0901abb@applause.expensifail.com/Feya86Katya
3. Select any chat
4. Click on plus button - Request Money

## Expected Result:
App is not crash for specific account when requesting the money

## Actual Result:
App crashed for specific account when requesting the money

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com/Feya86Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![Screen Shot 2022-08-05 at 3 22 11 PM](https://user-images.githubusercontent.com/93399543/183145819-b623884b-9a1e-4d9b-b772-53651f27136b.png)

https://user-images.githubusercontent.com/93399543/183145823-395e1606-bc95-4589-a68b-c6a821a37851.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-08-09 22:53
Posted! https://www.upwork.com/jobs/~01a99564082042bf31

**Comment by aimane-chnaif** [comment] 2022-08-10 06:38
### **Proposal**
This issue happens when `ONYXKEYS.IOU` value removed from storage unexpectedly. (I think when out of storage because the reporter's account (applausetester+0901abb@applause.expensifail.com) has lots of data)
And app crashes on this line:
https://github.com/Expensify/App/blob/f5f076a13bb4a991dbeaf32a8f7a7b0625e8a3cc/src/pages/iou/IOUModal.js#L156
because of `prevProps.iou` = undefined
<img width="1367" alt="crash" src="https://user-images.githubusercontent.com/96077027/183832234-9adcfdfb-739c-4b37-8b67-5da7902c4b55.png">

**Solution:**
add null safe condition to avoid crash
```
        if (!prevProps.iou || !this.props.iou) {
            return;
        }
```
updated code:
<img width="839" alt="IOU" src="https://user-images.githubusercontent.com/96077027/183830860-d838996c-255e-40a5-99bf-f3270a81947c.png">

**Comment by aimane-chnaif** [comment] 2022-08-11 01:51
@rushatgabhane this is called in `componentDidMount`, which means `props.iou` is set immediately as `{selectedCurrencyCode: xxx}` after IOUModal component is rendered first time.
https://github.com/Expensify/App/blob/c5b3ba87542f10b1303121c1131230d31bd9771a/src/pages/iou/IOUModal.js#L147
So IOUModal is still functional after setting value.
The crash happens only because `componentDidUpdate` is called after updating this value, with these props: (`prevProps.iou: undefined, this.props.iou: {selectedCurrencyCode: xxx}`)

These calls are not needed on first render of IOUModal so it's safe to `return` if `!prevProps.iou || !this.props.iou`
<img width="854" alt="componentDidUpdate" src="https://user-images.githubusercontent.com/96077027/184051727-5251ca1c-44d6-4241-8495-365944cdfffe.png">

**Comment by aimane-chnaif** [comment] 2022-08-11 17:30
@rushatgabhane @AndrewGable I just noticed this crash already fixed by @marcaaron in internal team
https://github.com/Expensify/App/issues/10275
https://github.com/Expensify/App/pull/10340

@marcaaron I think `iou` value is removed from storage and becomes `undefined` when out of storage. Only happening to the account with lots of data (workspaces, chats, etc)

**Comment by marcaaron** [comment] 2022-08-11 18:51
>@marcaaron I think iou value is removed from storage and becomes undefined when out of storage. Only happening to the account with tons of data (workspaces, chats, etc)

Ah hmm why would it be _removed_ from storage? My first thought was that it was not removed, but just hasn't loaded yet. Did we observe somewhere in the code where it's possible for that to happen or just a guess?

**Comment by aimane-chnaif** [comment] 2022-08-11 19:35
> > @marcaaron I think iou value is removed from storage and becomes undefined when out of storage. Only happening to the account with tons of data (workspaces, chats, etc)
> 
> Ah hmm why would it be _removed_ from storage? My first thought was that it was not removed, but just hasn't loaded yet. Did we observe somewhere in the code where it's possible for that to happen or just a guess?

Theoretically, `iou` cannot be `undefined`. It's always set https://github.com/Expensify/App/blob/main/src/setup/index.js#L33 when app starts. Other than that, no code of setting or removing this value. Always do `merge`.
please check this video:
https://drive.google.com/file/d/1wtm19M_Lp-VDN66aoxOhe3mcrvo3sarH/view?usp=sharing
You will see that `iou` set to `undefined` unexpectedly
Also, app is too slow to load

**Comment by marcaaron** [comment] 2022-08-11 20:24
> Theoretically, iou cannot be undefined. It's always set https://github.com/Expensify/App/blob/main/src/setup/index.js#L33 when app starts. 

Maybe there is some bug related to how that initial data is getting set or possibly a race condition related to the sign outs. Have we tried debugging?

I don't quite understand the conclusion that the data is somehow related to running out of storage space. My suggestion would be to find some evidence that this happening and otherwise stay open to the possibility that the issue could be related to something else.

**Comment by marcaaron** [comment] 2022-08-11 20:26
I think we can close this issue though since it's a duplicate and should be fixed on my other branch. Feel free to reopen if we disagree.

**Comment by kbecciv** [comment] 2022-09-20 23:33
@marcaaron Issue was reproduced with 2 testers using build 1.2.3.0.
Testers accounts:
1. applausetester+0901abb@applause.expensifail.com/Feya86Katya
2. applausetester+ihchat1@applause.expensifail.com/Yulia1986Gerets

https://user-images.githubusercontent.com/93399543/191382693-a3735738-820d-466a-8292-775719b11089.MP4


https://user-images.githubusercontent.com/93399543/191382686-eae62f9a-2293-4746-b435-c950a350a6d2.MP4

**Comment by mallenexpensify** [comment] 2022-09-21 18:04
@marcaaron what do you recommend we do with this issue since the bug is reproducible?

**Comment by mallenexpensify** [comment] 2022-09-27 17:50
@rushatgabhane and @marcaaron , can you help here plz? The issue is reproducible so I'm hesitant to close
> I think we can close this issue though since it's a duplicate and should be fixed on my other branch

What's link to other branch? Is it on staging yet?

**Comment by marcaaron** [comment] 2022-09-27 18:06
>@marcaaron what do you recommend we do with this issue since the bug is reproducible?

I would recommend that someone log into these tester accounts provided while debugging.

>What's link to other branch? Is it on staging yet?

This one -> https://github.com/Expensify/App/pull/10340

I think it should be on production by now... not sure how to figure that out for sure.

**Comment by mallenexpensify** [comment] 2022-09-30 20:30
@adelekennedy auto-assigned to you, I'm going to be OOO for a month. Thx

**Comment by mallenexpensify** [comment] 2022-10-04 18:25
@adelekennedy assigned myself and unassigned you cuz I'm NOT going to be OOO the next month ¯\_(ツ)_/¯

**Closed** 2022-10-13 14:50 UTC
Labels: External, Engineering, Weekly, Help Wanted, Overdue

**Comment by mvtglobally** [comment] 2022-10-14 18:39
@mallenexpensify @AndrewGable Looks like @adeel0202 is still able to repro this issue. We are not able to reproduce. Asked the team to double check as well. 
Should we reopen this issue? 
https://expensify.slack.com/archives/C01GTK53T8Q/p1662020087722169

**Comment by mallenexpensify** [comment] 2022-10-15 00:02
@adeel0202 is there anything different that you're doing to reproduce, vs using the steps in the OP?

**Comment by adeel0202** [comment] 2022-10-17 09:50
Update: Just check again today and I'm not able to reproduce the bug I reported. I was able to reproduce when this ticket was closed and I commented on slack. But now looks like it got fixed somehow.
