### ISSUE TITLE
[HOLD https://github.com/Expensify/App/pull/20821] [$1000] DEV: Requesting money after getting paid in a workspace stops working

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23334] opened 2023-07-21 04:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create 2 accounts. In the video, [6050@expensifail.com](mailto:6050@expensifail.com) is the workspace owner and [6051@expensifail.com](mailto:6051@expensifail.com) is an invited member
2. [6051@expensifail.com](mailto:6051@expensifail.com) requests money in their workspace chat
3. [6050@expensifail.com](mailto:6050@expensifail.com) adds a VBBA and pays the money requests
4. [6051@expensifail.com](mailto:6051@expensifail.com) tries to request money again

## Expected result: 
The money request should work and a new expense report should be created
## Actual result: 
The money request amount is added to the previous expense report that is already payed. The backend threw an error and no error is reported in the UI.

it shows a second bug where [6051@expensifail.com](mailto:6051@expensifail.com) can't create a DM chat with [6050@expensifail.com](mailto:6050@expensifail.com) anymore. The search shows only the last expense report and the workspace chat, but it is not possible to create a DM chat outside of the existing workspaces chats

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/177ed8ce-620d-4034-9ae4-be67cd125ced

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aldo-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689791415511559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d897bad012991ac0</li>
        <li>Upwork Job ID: 1682243955987083264</li>
        <li>Last Price Increase: 2023-07-21</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-07-21 04:19
Aldo reported this so it'll be reproducible.

**Comment by jigartankhupp** [comment] 2023-07-21 06:03
Hello I am unable to replicate this issue but getting this error:
```
{
    "jsonCode": 404,
    "message": "404 payerAccountID and policyID not found",
    "onyxData": [],
    "requestID": "7ea13bcbcb572e96-HYD"
}
```

**Comment by aldo-expensify** [comment] 2023-07-21 17:02
Heads up, I was told that there is a PR being worked on that will fix it. I don't have the link of the PR yet, but I'll remove `Help Wanted` and putting on HOLD for now.

**Comment by jliexpensify** [comment] 2023-08-14 01:25
On hold

**Comment by Santhosh-Sellavel** [comment] 2023-08-14 16:57
@aldo-expensify @jliexpensify Seems this PR #20821 is merged, can you confirm whether this is reproducible for you if not we can close this!

**Comment by jliexpensify** [comment] 2023-08-16 03:01
@aldo-expensify is this in DEV only? If so, could you test this one?

**Comment by aldo-expensify** [comment] 2023-08-16 17:33
Can't reproduce anymore, it works 🎉

**Closed by aldo-expensify** 2023-08-16 17:33 UTC
Labels: Weekly, Bug
