### ISSUE TITLE
Dev: Scroll issue at end of page in login page while keyboard is open

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23943] opened 2023-07-31 17:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to log in page
2. focus on the email field
3. try to scroll bottom of the page
## Expected Result: 
Scroll to be flexible and it should be the scrolling end of the page.
## Actual Result: 
The scroll is not flexible. Not able to scroll the end of the page.
Some views are not visible while the keyboard is open and try to scroll the end of the page.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** DEV
**Reproducible in production?:** DEV
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0c5d652b-a9c3-4a2f-bfa9-515e9d6eae2a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690720498181789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2023-07-31 19:14
I'm not able to reproduce this, looks like the app is scrolling all the way to the bottom of the page while the keyboard is open. Asking for more information in the slack chat https://expensify.slack.com/archives/C049HHMV9SM/p1690830753091699?thread_ts=1690720498.181789&cid=C049HHMV9SM

**Comment by niravkakadiya25** [comment] 2023-08-01 03:24
Issue able to reproduce in IOS Native as well
@Christinadobrzyn 
https://github.com/Expensify/App/assets/100456857/cad5b359-8336-4e8a-b8a8-d8e62d3ad801

**Comment by gadhiyamanan** [comment] 2023-08-01 04:55
@Christinadobrzyn this is dupe https://github.com/Expensify/App/issues/15754, we can close as per this https://github.com/Expensify/App/issues/15754#issuecomment-1520796403

**Comment by Christinadobrzyn** [comment] 2023-08-01 18:39
Ah thanks @gadhiyamanan! It does look like we should just close this and do nothing at this time based on https://github.com/Expensify/App/issues/15754#issuecomment-1520796403

**Closed by Christinadobrzyn** 2023-08-01 18:39 UTC
Labels: Daily, Needs Reproduction, Bug
