### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250]  Profile - Missing Save & continue button on 'Choose your bank account' selector

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44640] opened 2024-06-28 18:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** albertodege+2420@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisite: The user is logged in to the website.
1. Navigate to Account settings > Wallet
2. Click on Add Bank account> Personal Bank Account
3. On the Plaid modal, search and select Chase bank
4. Submit the credentials "user_good / pass_good"
5. Click on Continue until Plaid modal closes
6. Observe the 'Choose your bank account' selector

## Expected Result:
The user sees a Selector and a 'Save & continue' button

## Actual Result:
The 'Save & continue' button is not visible. When the user selects an account from the list, the 'Save & continue' button shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ecd96224-18c9-4797-a822-f436d9c30377

![Save___continue_button](https://github.com/Expensify/App/assets/78819774/e3159420-8156-43a8-8bfb-7718a08e1ba1)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0178ffe584bcdf528c</li>
        <li>Upwork Job ID: 1809027782286803187</li>
        <li>Last Price Increase: 2024-07-05</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 103036601</li>
<li>nkdengineer | Contributor | 103036605</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by lanitochka17** [comment] 2024-06-28 18:52
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment] 2024-06-28 21:24
I don't think this is really a "bug". It makes sense that you can't proceed here until you select an account. Once you select an account, we show `Save and continue` immediately, allowing you to proceed.

I could see an argument that this is not ideal UX, since it is a bit odd that we don't assume your selection when there is only one account on the list. But this form 100% works as designed now, so I don't think it really makes sense to spend resources changing this before we really have many customers in the product. 

https://github.com/Expensify/App/assets/54866469/32beaf5c-631c-4678-9dcf-4b3a4214c53b

**Comment by joekaufmanexpensify** [comment] 2024-06-28 21:24
Closing this until we get feedback from actual customers that this should work differently than as designed now.

**Comment by shawnborton** [comment] 2024-06-29 15:31
Hmm I think technically we don't hide or disable our form submit buttons. We would make it so that the button is visible, but if it's submitted with no bank account selected, we'd throw a form error. cc @mountiny @koko57 in case we might have missed this one during some of the bank account flow refactoring.

**Comment by mountiny** [comment] 2024-07-05 00:54
I agree this should be visible. Very odd that this would be missed in the original PR, maybe something caused this regression after. Opening it to the community

**Comment by nkdengineer** [comment] 2024-07-05 01:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The 'Save & continue' button is not visible. When the user selects an account from the list, the 'Save & continue' button shows up

### What is the root cause of that problem?
We're making submit button visibility dependent on the bank account selection https://github.com/Expensify/App/blob/74a6dbba2105ceba086f0387f50dcad573d4569f/src/pages/AddPersonalBankAccountPage.tsx#L83

### What changes do you think we should make in order to solve the problem?

Simply remove that line, or set it always to `true`

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-07-05 01:56
[Proposal updated](https://github.com/Expensify/App/issues/44640#issuecomment-2209846945) to add more details

**Comment by mountiny** [comment] 2024-07-05 09:28
@jayeshmangwani can you please review the proposals? thanks

**Comment by jayeshmangwani** [comment] 2024-07-05 09:30
@mountiny Yes I can but here @abdulrahuman5196 is C+ 😃

**Comment by mountiny** [comment] 2024-07-05 09:35
Yep sorry, @abdulrahuman5196 can you please review?

**Comment by nkdengineer** [comment] 2024-07-08 07:53
[Proposal updated](https://github.com/Expensify/App/issues/44640#issuecomment-2209846945) to add a small detail

**Comment by mountiny** [comment] 2024-07-08 09:38
@abdulrahuman5196 What is your ETA on this one? thanks!

**Comment by abdulrahuman5196** [comment] 2024-07-08 09:41
Hi @mountiny  will check on this before EOD

**Comment by abdulrahuman5196** [comment] 2024-07-08 18:32
Checking now

**Comment by abdulrahuman5196** [comment] 2024-07-08 19:27
@nkdengineer 's proposal here https://github.com/Expensify/App/issues/44640#issuecomment-2209846945 looks good and works well. The other proposals are almost similar with minor variations.

🎀 👀 🎀
C+ Reviewed
@mountiny

**Comment by nkdengineer** [comment] 2024-07-09 03:26
@abdulrahuman5196 this [PR](https://github.com/Expensify/App/pull/45040) is ready for review

**Comment by joekaufmanexpensify** [comment] 2024-07-15 14:54
PR in review

**Comment by joekaufmanexpensify** [comment] 2024-07-22 14:12
Same

**Comment by joekaufmanexpensify** [comment] 2024-07-31 18:16
[Bumped in Slack ](https://expensify.slack.com/archives/C02NK2DQWUX/p1722449761234279)

**Comment by joekaufmanexpensify** [comment] 2024-07-31 18:16
Payment here is: 

- $250 to @nkdengineer for PR via Upwork.

**Comment by abdulrahuman5196** [comment] 2024-07-31 18:53
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be a regression.

>Determine if we should create a regression test for this bug.

Yes.

> If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Navigate to Account settings > Wallet
2) Click on Add Bank account> Personal Bank Account
3) On the Plaid modal, search and select Chase bank
4) Submit the credentials "user_good / pass_good"
5) Click on Continue until Plaid modal closes
6) Observe the 'Choose your bank account' selector
7) Verify that: sees a Selector and a 'Save & continue' button


Hi @joekaufmanexpensify, I have moved to newdot payments.

**Comment by joekaufmanexpensify** [comment] 2024-07-31 19:11
@abdulrahuman5196 thanks for confirming on payments. I have updated the checklist and closed your upwork contract for this issue.

**Comment by joekaufmanexpensify** [comment] 2024-07-31 19:12
@nkdengineer $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-07-31 19:12
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-07-31 19:13
Closing as all that's left here is for @abdulrahuman5196 to request payment via NewDot.

**Closed by joekaufmanexpensify** 2024-07-31 19:13 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-01 20:18
$250 approved for @abdulrahuman5196
