### ISSUE TITLE
[HOLD for payment 2024-04-15] [$250] Remove deprecated `ReportUtils.getPolicy()` method

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#38959] opened 2024-03-25 20:32 UTC
This is coming from https://github.com/Expensify/App/issues/27262. You can read the issue description there to get context behind the problem being solved and the mess being cleaned up.

# Problem
`ReportUtils.getPolicy()` is called from a view component and other action files which is an anti-pattern.

## Why this is important to fix
It maintains a more pure and exact flow of data through the react application. If the view is using policy data, then it needs to subscribe to the policy in Onyx so that it's garaunteed that the data will never be stale or out-of-date.

# Solution
- Use `withOnyx()` to load the data in view components
- Use `Onyx.connect()` to load the data in other action files
- Remove the usage of `ReportUtils.getPolicy()` or at least prevent it from being exported by adding a test to https://github.com/Expensify/App/blob/main/tests/actions/EnforceActionExportRestrictions.ts
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ae8bb081ab888f1</li>
        <li>Upwork Job ID: 1772360821776945152</li>
        <li>Last Price Increase: 2024-03-25</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by godofoutcasts94** [comment] 2024-03-25 20:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove deprecated ReportUtils.getPolicy() method
### What is the root cause of that problem?
Identify the usage of `ReportUtils.getPolicy()` method.
### What changes do you think we should make in order to solve the problem?

After that we need to : 
- Use withOnyx() to load the data in view components
- Use Onyx.connect() to load the data in other action files
### What alternative solutions did you explore? (Optional)
N/A

**Comment by nayabatir1** [comment] 2024-03-25 20:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove deprecated `ReportUtils.getPolicy()`.

### What is the root cause of that problem?
Since `ReportUtils.getPolicy()` is deprecated need to replace it with `withOnyx` or `Onyx.connect()` to get data

### What changes do you think we should make in order to solve the problem?
- List of files for implementing this change
  - `SettlementButton.tsx`
  - `NextStepUtils.ts`
  - `ReportUtils.ts`
  - `Policy.ts`
  - `WorkspaceJoinUserPage.tsx`
- add test case to check `getPolicy` is not exported from `ReportUtils`

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-03-26 03:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Remove deprecated ReportUtils.getPolicy() method


### What is the root cause of that problem?


### What changes do you think we should make in order to solve the problem?
1. For component we should get `policy` via `withOnyx` of if the component already subscribe the policy collection, we will get the `policy` from this

```
policy: {
    key: ({policyID}) =>  `${ONYXKEYS.COLLECTION.POLICY}${policyID}`
}
```
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/components/SettlementButton.tsx#L262

```
const policy = policies?.[`${ONYXKEYS.COLLECTION.POLICY}${policyID}`]
```
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/workspace/WorkspaceJoinUserPage.tsx#L32

2. For the libs action, in we should use `Onyx.connect` to get `allPolicies` and then use this to get the policy

```
let allPolicies: OnyxCollection<Policy>;
Onyx.connect({
    key: ONYXKEYS.COLLECTION.POLICY,
    waitForCollectionCallback: true,
    callback: (value) => (allPolicies = value),
});
```

OPTION: We can create a local function in action file to get the policy with `policyID` and use this in other place of this file that we want.

3. Add a test here to verify that we do not export `getPolicy` function in `ReportUtils`

```
it('does not export getPolicy', () => {
    // @ts-expect-error the test is asserting that it's undefined, so the TS error is normal
    expect(ReportUtils.getPolicy).toBeUndefined();
});
```
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/tests/actions/EnforceActionExportRestrictions.ts#L8
### What alternative solutions did you explore? (Optional)
NA

**Comment by samilabud** [comment] 2024-03-26 03:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove deprecated ReportUtils.getPolicy() method

### What is the root cause of that problem?
ReportUtils.getPolicy() is called from a view component and other action files which is an anti-pattern.

### What changes do you think we should make in order to solve the problem?
We should do the next changes in [SettlementButton](https://github.com/Expensify/App/blob/main/src/components/SettlementButton.tsx) component:

Add the prop policy like:
```
type SettlementButtonOnyxProps = {
    /** The last payment method used per policy */
    nvpLastPaymentMethod?: OnyxEntry<LastPaymentMethod>;
    /** Policy to which the report belongs to */
    policy: OnyxEntry<Policy>;
};
```
Receive as a param the policy like:
```
function SettlementButton({
    .
    .
    .
    policy,
}: SettlementButtonProps) {

```
Remove the line:
https://github.com/Expensify/App/blob/0047ad2cc9005042b064bfd2fb5b8c6d21055d66/src/components/SettlementButton.tsx#L142

Also we should remove the export of the function '[getPolicy](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.ts#L5662)' of [ReportUtils.ts](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.ts)

Additionally we should reuse the function [getPolicity](https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/ReportUtils.ts#L573) in [Policy.ts](https://github.com/Expensify/App/blob/main/src/libs/actions/Policy.ts) and replace all the lines with 'ReportUtils.getPolicy(policyID)' by 'getPolicy(policyID)'.

Later we should make the next changes in [WorkspaceJoinUserPage](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceJoinUserPage.tsx):

Add policy prop:
```
type WorkspaceJoinUserPageOnyxProps = {
    /** The list of this user's policies */
    policies: OnyxCollection<Policy>;
    /** Policy to which the report belongs to */
    policy: OnyxEntry<Policy>;
};
```
Add the policy param to the function:
`function WorkspaceJoinUserPage({route, policies, policy}: WorkspaceJoinUserPageProps) {`

Add the policy prop inside withOnyx:
```
export default withOnyx<WorkspaceJoinUserPageProps, WorkspaceJoinUserPageOnyxProps>({
    policies: {
        key: ONYXKEYS.COLLECTION.POLICY,
    },
    policy: {
        key: ({route}) => `${ONYXKEYS.COLLECTION.POLICY}${route.params.policyID}`,
    },
})(WorkspaceJoinUserPage);
```
Add this to [EnforceActionExportRestrictions](https://github.com/Expensify/App/blob/main/tests/actions/EnforceActionExportRestrictions.ts) inside of ReportUtils section:
```
it('does not export getPolicty', () => {
        // @ts-expect-error the test is asserting that it's undefined, so the TS error is normal
        expect(ReportUtils.getPolicty).toBeUndefined();
    });
```

**Comment by CortneyOfstad** [comment] 2024-03-26 15:22
@eVoloshchak — we have quite a few proposals above. Can you provide feedback by EOD? Thanks!

**Comment by CortneyOfstad** [comment] 2024-03-26 15:25
@tgolen I reviewed all of the linked PRs in the main issue you linked (https://github.com/Expensify/App/issues/27262) and I wasn't able to find a connection to any Waves or VIPs. Can you provide some context into whether or not this falls into one of those classifications? Thanks!

**Comment by tgolen** [comment] 2024-03-26 16:08
It doesn't neatly fit into any waves or VIP. This task is cleaning up some
deprecated code in order to maintain code quality.

**Comment by CortneyOfstad** [comment] 2024-03-27 13:13
Sounds good, thanks @tgolen!

**Comment by tgolen** [comment] 2024-03-27 15:12
@eVoloshchak are you able to take a look at the proposals? If not today, I will reassign this tomorrow.

**Comment by DylanDylann** [comment] 2024-03-28 02:49
I am happy to take over this issue if he isn't available

**Comment by tgolen** [comment] 2024-03-28 16:05
@DylanDylann Can you please take this one? Thank you! I will reassign it.

**Comment by DylanDylann** [comment] 2024-03-28 16:39
@nkdengineer Why do you think this point is necessary here?

> Add a test here to verify that we do not export getPolicy function in ReportUtils

**Comment by nkdengineer** [comment] 2024-03-28 16:47
> Remove the usage of ReportUtils.getPolicy() or at least prevent it from being exported by adding a test to https://github.com/Expensify/App/blob/main/tests/actions/EnforceActionExportRestrictions.ts

@DylanDylann This is a requirement here.

**Comment by DylanDylann** [comment] 2024-03-28 16:54
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/38959#issuecomment-2019324591) looks good to me. We should keep `getPolicy` in ReportUtils file to use in other places in that file

**Comment by DylanDylann** [comment] 2024-03-28 16:56
🎀 👀 🎀 C+ reviewed

**Comment by abzokhattab** [comment] 2024-03-28 17:03
@DylanDylann Hi Dylan can you please let me know what you think about my proposal, looking forward to your feedback ... I believe my proposal is pretty similar.

**Comment by DylanDylann** [comment] 2024-03-28 17:11
I also hesitate when making a decision here. Your proposal is first but @nkdengineer mentioned updating the test file that I think is a good point. @tgolen The final decision is up to you

**Comment by abzokhattab** [comment] 2024-03-28 17:15
I thank you for the feedback. I believe that mentioning tests in the proposal is optional and shouldn't be the core focus, but I understand your point.

Let's see what @tgolen thinks as well. I am happy with whatever decision is made.

**Comment by tgolen** [comment] 2024-03-28 18:01
Both proposals are very similar, but I will go with the one that included the mention of the tests as that is a very important point to keep this pattern from being repeated.

**Comment by DylanDylann** [comment] 2024-04-01 08:51
Waiting for @nkdengineer's PR to be ready for review

**Comment by nkdengineer** [comment] 2024-04-10 08:09
@DylanDylann Create a follow up PR here https://github.com/Expensify/App/pull/39991 to fix the bug that is mentioned by @Pujan92 above https://github.com/Expensify/App/issues/38959#issuecomment-2039913163.

**Comment by CortneyOfstad** [comment] 2024-04-15 13:36
So there was a regression, so this will result in a price of $250 instead of $500 for both @DylanDylann and @nkdengineer. 

@DylanDylann can you handle the checklist [here](https://github.com/Expensify/App/issues/38959#issuecomment-2042451727) by EOD? 

@nkdengineer I sent you a manual offer in Upwork. Please let me know once you accept 👍

**Comment by DylanDylann** [comment] 2024-04-15 13:44
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **No**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by DylanDylann** [comment] 2024-04-15 13:45
This is clean up issue, so I think we don't need regression test step

**Comment by CortneyOfstad** [comment] 2024-04-15 16:43
Sounds good @DylanDylann!

**Comment by CortneyOfstad** [comment] 2024-04-15 16:43
## Payment Summary

@DylanDylann — paid $250 via Upwork
@nkdengineer — paid $250 via Upwork

**Closed by CortneyOfstad** 2024-04-15 16:43 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
