### ISSUE TITLE
[HOLD for payment 2023-10-05] [$500] Web – Request Money – “Show more” button is not highlighted on hover or when the cursor is moved

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#25687] opened 2023-08-22 14:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Click FAB (Plus sign).
2.	Click " Request Money ".
3.	Enter amount and click “Next”.
4.	Select the user to proceed
5.	Notice the “Show more” button is not highlighted on hover or when the cursor is moved 
## Expected Result:
Down arrow (chevron) should highlighted on hover
## Actual Result:
Down arrow (chevron) does not highlighted on hover
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/8a93c65c-289e-44c9-a3b0-31807982f134

https://github.com/Expensify/App/assets/38435837/a45e9712-3760-442a-aeba-2f0368e511fd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691225374193429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01152fc4f180cf9e07</li>
        <li>Upwork Job ID: 1699608422610767872</li>
        <li>Last Price Increase: 2023-09-07</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 26734890</li>
<li>suneox | Contributor | 26734891</li>
</ul></li>
    </ul>
</details>

**Comment by alphaboss1104** [comment] 2023-08-22 18:06
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Web – Request Money – Down arrow (chevron) is not highlighted on hover or when the cursor is moved on the “Show more” button.

### What is the root cause of that problem?

We didn't set the prop in `Button` component so that the down arrow (chevron) should be highlighted on the hover.

https://github.com/Expensify/App/blob/999ed938befa8910293cf349a4222314d5a73ccd/src/components/MoneyRequestConfirmationList.js#L364-L372

Also, even if we set the prop on the `Button` component, there is no code to update the color of the down arrow (chevron), so only the `Show more` button is highlighted, but not the down arrow (chevron).

https://github.com/Expensify/App/blob/999ed938befa8910293cf349a4222314d5a73ccd/src/components/Button/index.js#L241-L249

This is the root cause of this issue.

### What changes do you think we should make in order to solve the problem?

To solve this problem we should add a prop to the `Button` component and then add the code to update the down arrow (chevron)'s color on hover.

We can do it like this:

1. Add a prop to the `Button` component.

```js
              <Button
                  small
                  onPress={toggleShowAllFields}
                  text={translate('common.showMore')}
                  shouldShowRightIcon
                  iconRight={Expensicons.DownArrow}
-                 iconFill={themeColors.icon}
                  style={styles.mh0}
+                 shouldUseDefaultHover
              />
```
2. Add a new state variable [here](https://github.com/Expensify/App/blob/main/src/components/Button/index.js):

```js
              constructor(props) {
                  super(props);

+                 this.state = {
+                     isHovered: false,
+                 };

                  this.renderContent = this.renderContent.bind(this);
+                 this.handleHoverIn = this.handleHoverIn.bind(this);
+                 this.handleHoverOut = this.handleHoverOut.bind(this);
              }
```

3. Create `handleHoverIn` and `handleHoverOut` functions to manage the hover state:

```js
              handleHoverIn() {
                  this.setState({isHovered: true});
              }
              
              handleHoverOut() {
                  this.setState({isHovered: false});
              }
```

4. Pass these functions to the `PressableWithFeedback` component in [here](https://github.com/Expensify/App/blob/main/src/components/Button/index.js):

```js
              <PressableWithFeedback
                  ref={this.props.forwardedRef}
                  onPress={(e) => {
                      // existing code...
                  }}
+                 onHoverIn={this.handleHoverIn}
+                 onHoverOut={this.handleHoverOut}
                  // other props...
              >
```

5. Finally, change the fill color of the `IconRight` based on the `isHovered` state in the `renderContent` function:

```js
            {this.props.shouldShowRightIcon && (
                <View style={[styles.justifyContentCenter, styles.ml1, ...this.props.iconRightStyles]}>
                    <Icon
                        src={this.props.iconRight}
                        fill={this.state.isHovered ? themeColors.iconHovered : this.props.iconFill}
                        small={this.props.small}
                    />
                </View>
            )}
```
### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2023-08-30 05:55
Hmm, I don't think this is a bug. We don't highlight the chevron on hoover for a pill. Right @shawnborton @trjExpensify? I think we should close though getting a second opinion.

**Comment by trjExpensify** [comment] 2023-08-30 14:37
Hm yeah, if anything, the button should probably be highlighted on hover like the confirmation button does. Not super passionate though, @JmillsExpensify.

**Comment by shawnborton** [comment] 2023-08-30 15:06
I don't know that the chevron needs to change color in this instance. We're showing it as a button and not as an option row. However, that "Show more" button should behave exactly like our standard "Default" buttons which means it would get a slight color change on hover and on press. cc @dannymcclain 

So I would say this bug report is incorrect (well, not even a bug report but rather a design inconsistency request) so no payouts here, but we could spin up an issue to make sure it has the hover state or ask whoever implemented it to go back and make the change?

**Comment by dannymcclain** [comment] 2023-08-30 16:56
Yeah I agree with Shawn—that should just work like a standard button (with the same static/hover/active/etc states).

**Comment by JmillsExpensify** [comment] 2023-09-07 02:19
Cool, now that that's cleared up, let's focus this issue on the "show more." Opening up for solutions.

**Comment by shawnborton** [comment] 2023-09-07 14:33
Yeah, ideally this just uses the same exact hover style as other default buttons.

**Comment by alphaboss1104** [comment] 2023-09-07 15:51
If we add only `shouldUseDefaultHover`,  `Show more` button is highlighted but Down arrow (chevron) isn't highlighted on hover.
If we can compare the icon, we can notice that`Show more` button's icon is different with this with `Description`'s on hover.

[screen-capture.webm](https://github.com/Expensify/App/assets/137152763/98d18105-c5f3-49e6-92fc-fb741baca3a3)

**Comment by shawnborton** [comment] 2023-09-11 14:55
Yup, that works for me.

**Comment by JmillsExpensify** [comment] 2023-10-07 21:06
@ntdiary Do you mind kicking off the BZ checklist?

**Comment by JmillsExpensify** [comment] 2023-10-07 21:09
In the meantime, here's the payment summary:

 - Issue reporter: @usmantariq96 $250 (reported before Aug. 25)
 - Contributor: @suneox $500 (no bonus)
 - Contributor+: @ntdiary $500

**Comment by usmantariq96** [comment] 2023-10-07 21:35
@JmillsExpensify as per Shawn comment I don't think I'm eligible for bounty.

**Comment by JmillsExpensify** [comment] 2023-10-08 13:17
Thanks @ntdiary! Everyone has been paid based on the payment summary. I'm closing this one out.

**Closed by JmillsExpensify** 2023-10-08 13:17 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
