### ISSUE TITLE
[HOLD for #35174] [$500] Chat - The task does not display in LHN that it is archived

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35183] opened 2024-01-25 20:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31900
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a new workspace
4. Open the workspace/policy expense chat
5. Create a task
6. Turn off the internet connection
7. Delete the workspace
8. Verify that task is archived
9. Go back Online

## Expected Result:
The task is archived

## Actual Result:
The task becomes unarchived

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/de385d7f-b029-4e11-9eeb-4194ba3c2a2b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b75849bf0303bf35</li>
        <li>Upwork Job ID: 1750612664757682176</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2024-01-25 20:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - The task does not display in LHN that it is archived

### What is the root cause of that problem?

The `leaveRoom` function is only setting `statusNum: CONST.REPORT.STATUS_NUM.CLOSED` in `optimisticData`. 

However, the backend erases this.
### What changes do you think we should make in order to solve the problem?


Put `statusNum` and `stateNum` in the `successData` as well.

**Comment by Tony-MK** [comment] 2024-01-25 20:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?


We checked if the report is a `ReportUtils.isThread(report)` and removed it from the list of reports which need to be set `statusNum` and `stateNum` in `optimisticData`. 

https://github.com/Expensify/App/blob/889051cf6c155c225a9c602c17d95ec40d740839/src/pages/workspace/WorkspaceInitialPage.js#L103-L105

### What changes do you think we should make in order to solve the problem?


Instead, use the condition `ReportUtils.isThread(report) && !ReportUtils.isTask(report)` for this case.

**Comment by Tony-MK** [comment] 2024-01-25 20:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - The task does not display in LHN that it is archived

### What is the root cause of that problem?


We checked if the report is a `ReportUtils.isThread(report)` and removed it from the list of reports which need to be set `statusNum` and `stateNum` in `optimisticData`. 

https://github.com/Expensify/App/blob/889051cf6c155c225a9c602c17d95ec40d740839/src/pages/workspace/WorkspaceInitialPage.js#L103-L105

### What changes do you think we should make in order to solve the problem?


Instead, use the condition `ReportUtils.isThread(report) && !ReportUtils.isTask(report)` for this case.

**Comment by Tony-MK** [comment] 2024-01-25 20:48
I think the root cause is caused by https://github.com/Expensify/App/issues/35174.

**Comment by getusha** [comment] 2024-01-26 19:30
@Tony-MK I see you posted the same proposal on both issues.

@michaelhaxhiu We should hold this for https://github.com/Expensify/App/issues/35174

**Comment by Tony-MK** [comment] 2024-01-26 19:43
Yeah, I presume both have the identical root cause.

**Comment by getusha** [comment] 2024-02-01 18:49
Should be held for https://github.com/Expensify/App/issues/35174

**Comment by CortneyOfstad** [comment] 2024-02-02 15:05
Sounds good @getusha!

**Comment by CortneyOfstad** [comment] 2024-02-05 15:24
Not overdue 👍

**Comment by CortneyOfstad** [comment] 2024-02-07 16:36
Not overdue — going to change the frequency 👍

**Comment by CortneyOfstad** [comment] 2024-02-22 19:09
No PR has been created yet on the other GH. Going to keep this set to weekly and will continue to watch both.

**Comment by CortneyOfstad** [comment] 2024-02-28 15:25
Issue is still in reviewing stage. Going to continue keeping an eye on this.

**Comment by CortneyOfstad** [comment] 2024-02-29 19:48
Hey @johncschuster ! I am heading OoO and will be back March 11th, so reassigned to have someone keep this moving until I am back. At this stage, we're on-hold for your other GH (https://github.com/Expensify/App/issues/35174), so it made sense to have you review this one as well in tandem. Thanks!

**Comment by CortneyOfstad** [comment] 2024-03-11 17:08
Back from OoO — thanks for keeping an eye on things @johncschuster!

**Comment by CortneyOfstad** [comment] 2024-03-11 17:10
PR has been closed for a while — apparently the automation was broken, so this can be closed!

PR here — https://github.com/Expensify/App/pull/36225#issuecomment-1945393959
More details here — https://github.com/Expensify/App/issues/35174#issuecomment-1971851703

**Closed by CortneyOfstad** 2024-03-11 17:10 UTC
Labels: Weekly, Bug
