### ISSUE TITLE
The message link does not work

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21287] opened 2023-06-21 23:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message in any chat
2. Hover over the message and copy link
3. Open the link the same or new tab
4. App throws a "its not there" page

## Expected Result: 
The user should be able to use the message link or the copy link button should not be there, in staging we don't have the option to copy link on a text message
## Actual Result: 
Message link doesn't work, throws a "its not there" page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b0a1b508-a501-48b2-a820-815130912ee7

https://github.com/Expensify/App/assets/43996225/d2aa4d11-c0eb-4cbe-b63c-305c5fb17048

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686832980883059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2023-06-22 09:50
Dupe of https://github.com/Expensify/App/issues/20766 and closed because it's a beta feature

**Comment by sonialiap** [comment] 2023-06-22 21:23
Thanks @bernhardoj , closing this one as dupe

**Closed by sonialiap** 2023-06-22 21:23 UTC
Labels: Daily, Bug
