### ISSUE TITLE
[HOLD for payment 2023-08-14] [$1000] Tasks assigned disappears from LHN when leaving the chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23309] opened 2023-07-20 20:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login and create a task
2. Assign to account B
3. Login to account B
4. Open the task
5. Switch to other chat
## Expected Result:
Task is available in LHN
## Actual Result:
Task gets disappeared. Tasks that are assigned to me should be pinned in LHN in #focus mode
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (1)](https://github.com/Expensify/App/assets/43996225/1b1dbcd1-ef87-438f-92bb-de8119901292)
![image](https://github.com/Expensify/App/assets/43996225/cb4eb3db-1875-41ab-ba69-f7585fa2ec45)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689746543712129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0120f92e247a863177</li>
        <li>Upwork Job ID: 1684316072626675712</li>
        2023-07-26<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 25855965</li>
</ul></li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-07-21 01:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The task assigned to a user disappears from the left-hand navigation (LHN) when the user navigates away from the task chat in focus mode. 

### What is the root cause of that problem?
The issue stems from the `shouldReportBeInOptionList `function which decides whether a report should show in 'focus' mode. Currently, there is no check to retain the report in the list if the user is the assignee of the task.

https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/libs/ReportUtils.js#L2125-L2183

### What changes do you think we should make in order to solve the problem?
To address this issue, we could include a check within the `shouldReportBeInOptionList `function to determine if the user is the assignee for the task. The implementation could look like this

```
if (report.type === 'task') {
    if (isTaskAssignee(report)) {
        return true;
    }
}
```

**Comment by anmurali** [comment] 2023-07-24 15:07
Rotating the assignment as I am OOO for 10 days

**Comment by johncschuster** [comment] 2023-07-26 23:58
Not overdue, Melvin

**Comment by ArekChr** [comment] 2023-07-27 13:29
Trying to reproduce this error but with no results. Could anyone send a video with the repro steps? Screens from the description are not enough

**Comment by ygshbht** [comment] 2023-07-27 13:34
Sure

https://github.com/Expensify/App/assets/65986357/58f4f164-8b0d-4400-8351-0ec50675e672

**Comment by ArekChr** [comment] 2023-07-31 10:17
Thanks for the repro steps! 
@ygshbht in your proposal, when opening not completed tasks and leaving the chat, it still disappears from LHN

**Comment by ArekChr** [comment] 2023-07-31 10:25
>I think the condition to show Task in focus mode is not only Task is assigned to current user, but also this Task must not be completed or cancelled yet. It's same condition when we show Green dot indicator for a task in LHN

@hoangzinh, your proposal implements proper logic for that solution, LGTM
:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by ygshbht** [comment] 2023-07-31 10:45
Thanks for the question @ArekChr 

Can you please let me know the steps you followed as I don't see the issue when you are explicty assigned the task? It'd be best if you could also share a video of that. You may not see the task if you are only a participant. If you want to show even if you are only a participant, it can be implemented too by checking the `participants `or `participantAccountIds` fields of report. 

I'm tackling the main issue here which is showing the task when it is assigned to you. If it is preferred to not show the task if it cancelled or completed, you can further make use of the `isCompletedTaskReport` and `isCanceledTaskReport` functions.

**Comment by ygshbht** [comment] 2023-07-31 10:51
https://github.com/Expensify/App/assets/65986357/85613efd-22b3-4bfa-98ca-b2d7a631ed91

**Comment by ygshbht** [comment] 2023-07-31 10:53
https://github.com/Expensify/App/assets/65986357/5c3f20af-482d-4a54-a9d5-f6e2d5e993f7

**Comment by ArekChr** [comment] 2023-07-31 10:54
> New.Expensify.-.Google.Chrome.2023-07-31.16-21-11.mp4

Is focus mode enabled? I tested your condition from the proposal and performed actions like in the description: 

Login to account A and create a task
Assign to account B
Login to account B
Open the task
Switch to another chat

Expected Result:

The task is available in LHN

**Comment by ygshbht** [comment] 2023-07-31 11:03
> > New.Expensify.-.Google.Chrome.2023-07-31.16-21-11.mp4
> 
> Is focus mode enabled? I tested your condition from the proposal and performed actions like in the description:
> 
> Login to account A and create a task Assign to account B Login to account B Open the task Switch to another chat
> 
> Expected Result:
> 
> The task is available in LHN

Thanks. You can see from the LHN that focus mode is enabled

**Comment by ygshbht** [comment] 2023-07-31 11:04
Here i show it more explicitly. I have also added the compltion and cancelled checks if you prefer that. 

https://github.com/Expensify/App/assets/65986357/a1817203-c3bd-4edc-9073-1a3b1170c929

To test better, i have place the condition around the code at top 

```
function shouldReportBeInOptionList(report, currentReportId, isInGSDMode, iouReports, betas, policies, allReportActions) {
    const isInDefaultMode = !isInGSDMode;

    // Exclude reports that have no data because there wouldn't be anything to show in the option item.
    // This can happen if data is currently loading from the server or a report is in various stages of being created.
    // This can also happen for anyone accessing a public room or archived room for which they don't have access to the underlying policy.
    if (
        !report ||
        !report.reportID ||
        (_.isEmpty(report.participantAccountIDs) && !isChatThread(report) && !isPublicRoom(report) && !isArchivedRoom(report) && !isMoneyRequestReport(report) && !isTaskReport(report))
    ) {
        return false;
    }

    if (!canAccessReport(report, policies, betas, allReportActions)) {
        return false;
    }

    if (isTaskReport(report)) {
        if (isTaskAssignee(report) && !isCanceledTaskReport(report) && !isCompletedTaskReport(report)) {
            return true;
        }
    }
```

**Comment by ygshbht** [comment] 2023-07-31 11:11
> I think there is confusion here. Let me verify it again. We have 2 proposal so far:
> 
> * @ygshbht proposed a solution that we show assigned tasks in the LHN for all cases including opening/completed/cancelled if user changes to focus mode.
> * I proposed a solution that we should only show assigned tasks in the LHN only if it's opening in focus mode. Because in focus mode, completed/cancelled Tasks are not really need to be focused anymore.

It seems clear that everyone agrees with the points @honagzinh made in the above comment. He emphasized that tasks should not be shown if they are in focus mode and completed/ cancelled.

I did not initially mention this point, as it was not the primary concern, and the issue description did not include it. However, such features can always be implemented when they are identified as preferred enhancements.

**Comment by ArekChr** [comment] 2023-07-31 11:12
@ygshbht 

https://github.com/Expensify/App/assets/24796318/0caf2f86-9d5e-410c-a813-ce5f2de6670a

**Comment by ygshbht** [comment] 2023-07-31 11:23
> @ygshbht
> 
>  Nagranie.z.ekranu.2023-07-31.o.13.10.16.mov

This can be the case when the report has not been fetched and is not present in the LHN either in focus mode or Most recent mode. For such cases, you can decide to always fetch the report even if it not present but is a Task report using `Report.openReport()` util

**Comment by cristipaval** [comment] 2023-07-31 12:05
> > I think the condition to show Task in focus mode is not only Task is assigned to current user, but also this Task must not be completed or cancelled yet. It's same condition when we show Green dot indicator for a task in LHN
> 
> @hoangzinh, your proposal implements proper logic for that solution, LGTM 🎀 👀 🎀 C+ reviewed

Thanks @ArekChr! 🙇 
Could you also link the accepted proposal when you approve, from now on?

**Comment by ArekChr** [comment] 2023-08-08 13:26
@puneetlath Re-tested on staging, and no longer expecting this bug.

https://github.com/Expensify/App/assets/24796318/81395da6-beed-45ab-8e68-12af332ba2a5

**Comment by johncschuster** [comment] 2023-08-14 21:23
Payment to @hoangzinh has been issued!

**Comment by johncschuster** [comment] 2023-08-14 21:25
@puneetlath do we need to wait on the above checklist to close this out, or are we good to close the issue?

**Comment by puneetlath** [comment] 2023-08-14 23:21
Given that it was a bug that we fixed, I think we should complete the checklist as we always do.

**Comment by ArekChr** [comment] 2023-08-16 11:37
- [x]: The PR that introduced the bug has been identified. Link to the PR: No bug has been identified
- [x]: The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: n/a
- [x]: A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: n/a
- [x]: Determine if we should create a regression test for this bug: We can create a regression test

Regression test proposal:

1. Log in to account A and create a task.
2. Assign the task to account B.
3. Log in to account B and switch to focus mode.
4. Open the task.
5. Switch to another chat.
6. Verify that the task is visible on `LHN`.

Do we agree 👍 or 👎

**Comment by cristipaval** [comment] 2023-08-21 15:13
I think the only payment is for @hoangzinh. I think we can close the issue, can't we?

**Closed** 2023-08-24 20:16 UTC
Labels: External, Daily, Weekly, Needs Reproduction, Overdue, Awaiting Payment, Bug

**Comment by lanitochka17** [comment] 2023-09-18 22:46
We have a similar issue. Should we open this one or create a new one?
Steps:
1. Navigate to a Group Chat
2. Log out and log in as another participant of the group
3. Navigate to the group conversation 
4. Create the task Do not assign
5. Click on the task to navigate to the task "conversation"
6. Click on Assignee
7. Assign the task to yourself
8. Verify the task report shows a green dot on the LHN
9. Open another chat – Green dot disappears.

https://github.com/Expensify/App/assets/78819774/920c3cd3-f2c8-470e-bf8a-e623643a67dd
