### ISSUE TITLE
Emoji picker keyboard is covering compose box reported by @aneequeahmad 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12557] opened 2022-11-08 16:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. open web app on browser of phone(or android/IOS app).
2. Open any report and focus on composer to open soft keyboard.
3. Press emoji picker option/icon on keyboard.

## Expected Result:
Composer should be above the keyboard emoji picker and shouldn't hide behind the keyboard as if keyboard is closed

## Actual Result:
Composer is hiding behind the keyboard

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.2.21-4

**Reproducible in staging?:** Need reproduction

**Reproducible in production?:** Need reproduction

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200624951-88c91689-2997-446a-ad21-d4c0e34ec69a.mp4

https://user-images.githubusercontent.com/43996225/200624967-c24ce5ea-c287-4479-9dc0-e57d57757096.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @aneequeahmad 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667091893014729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sketchydroide** [comment] 2022-11-09 14:09
I was not able to replicate this on version 1.2.25-0, not sure if this was fixed in the mean time, or if it was just on this ocasion.
CCing @tgolen as this might be related to the Keyboard Avoidance features, this would definetly be something to look for on regular iOS developement and a typical issue with keyboard and fields, not sure how that translates to RN.

**Comment by tgolen** [comment] 2022-11-09 15:56
I think this is a duplicate of https://github.com/Expensify/App/issues/10609 which was closed because it was no longer reproducable. I think if we can consistently reproduce this in some fashion, then we should reopen the original issue.

**Comment by sketchydroide** [comment] 2022-11-14 11:29
will close this one, next time we reopen the original one

**Closed by sketchydroide** 2022-11-14 11:29 UTC
Labels: Engineering, Daily, Needs Reproduction, Overdue, Bug
