### ISSUE TITLE
[CHECKLIST - ISHPAUL] [$250] Mac Safari - Tasks/Chat - Second right hand menu pane RHP shown severely cut compared to prod

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44765] opened 2024-07-03 08:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** gatantm+82@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to any chat
2. Click on the plus icon > Assign task
3. Add any Title > next
4. Second flow click on the chat header > Share

## Expected Result:
The second page of the opened RHP is shown without issues

## Actual Result:
The second page of the opened RHP either when assigning a task or Sharing a channel is shown cut. Sometimes the button back is hard to reach as well

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7163f8c9-558e-42ed-9d9b-8b7d896140f4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c408a04e30a45b7f</li>
        <li>Upwork Job ID: 1808446874734237891</li>
        <li>Last Price Increase: 2024-07-03</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 102994015</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by izarutskaya** [comment] 2024-07-03 08:13
We think this issue might be related to the  #vip-vsb

**Comment by izarutskaya** [comment] 2024-07-03 08:14
Production

![Screenshot 2024-07-03 at 08 00 22](https://github.com/Expensify/App/assets/115492554/6797fa6f-1fd5-4f43-ac93-fd3362e28077)

**Comment by techievivek** [comment] 2024-07-03 09:39
oops, it's badly broken. Removing the `DeployBlocker` since this is not concerned with backend.

**Comment by jliexpensify** [comment] 2024-07-03 09:46
@techievivek keep it `Internal` or can we make it `External`?

**Comment by mountiny** [comment] 2024-07-03 10:25
Lets make this external

**Comment by jnowakow** [comment] 2024-07-03 10:27
Hello, I'm from Software Mansion, an expert agency, and I'll work on this

**Comment by jliexpensify** [comment] 2024-07-03 10:31
Assigned you @jnowakow

**Comment by jnowakow** [comment] 2024-07-03 10:47
As per [this message](https://swmansion.slack.com/archives/C01GTK53T8Q/p1720002550104879?thread_ts=1720002337.271509&cid=C01GTK53T8Q) more people can look at this issue - it's only reproducible on Safari, on other browsers it works fine

**Comment by mountiny** [comment] 2024-07-03 11:22
I could only reproduce in Safari, not in chrome

**Comment by jasperhuangg** [comment] 2024-07-03 18:29
Demoting since the issue only happens on Safari, on a very specific flow, and isn't consistently reproducible.

**Comment by mountiny** [comment] 2024-07-03 21:48
@Kicu can you please check that out?

**Comment by mountiny** [comment] 2024-07-03 21:51
I am not 100% if just disabling the mode is the right path forwards, can we help fix this issue in safari with some patch and try to fix it upstream? I worry that if we would not care, we might leave the safari disabled for a long time

**Comment by s77rt** [comment] 2024-07-03 21:54
Not able to reproduce


https://github.com/Expensify/App/assets/16493223/525f5513-8271-4b42-8906-ad6c0b8dff4c

**Comment by mountiny** [comment] 2024-07-03 21:55
@s77rt I believe it was not super reliable, have you tried couple of times?

**Comment by s77rt** [comment] 2024-07-03 22:12
@mountiny Tested on staging and I'm able to reproduce (all the time) but not on `main`


https://github.com/Expensify/App/assets/16493223/60990a61-17ee-4c38-b653-93adb5b677d8

The bug is probably not fixed yet. But it does seem harder to reproduce locally

**Comment by s77rt** [comment] 2024-07-03 22:52
@ShridharGoel Were you able to reproduce this locally?

**Comment by Kicu** [comment] 2024-07-04 08:14
I also tested, and:
- initiall I was able to reproduce on Assign Task, but then after I got the correct behavior once I cannot reproduce anymore. Tried refreshing the page multiple times and it looks good every time
- however when doing a similar pattern from Search, that is: click on row, see the report in RHP and click on its header to get another RHP open I get this:

![Screenshot 2024-07-04 at 10 10 46](https://github.com/Expensify/App/assets/3929868/f79876f8-595e-4241-a771-b0daf640a8e6)

Do we also treat this as part of this bug? seems closely related.

**Comment by mountiny** [comment] 2024-07-04 13:12
@Kicu seems like the RCA will be similar so I would say yes

**Comment by Kicu** [comment] 2024-07-04 13:24
Both the original bug with `Task` RHP page and also my screenshot ☝️ where ReportDetails looks bad seem to have the same source.
The source is using specific interpolators from base `Animated` from `react-native` or writing our own interpolators.

If we take a look where the RHP Navigator is defined: https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx#L40
we see that there are options passed to it, and within them the specific interpolator to be used, defined here: https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/ModalNavigatorScreenOptions.ts#L16
If I either **comment out this interpolator to some other animation** the bug does not happen.

This is the direct link to the interpolator in question: https://github.com/react-navigation/react-navigation/blob/main/packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx#L14

I tried to do some logging from inside `react-navigation` and `Animated` but found nothing. What I also found is that sometimes if we trigger the bug, then moving the browser window or changing focus fixes it.
This leads me to believe that perhaps there is some problem in Safari related to painting, updating screen etc. Perhaps the internal Animated/progress.interpolate implementation has a bug that did not surface before 🤷 

I guess the only 2 things to do that I can come up right now is to:
A. disable.remove concurrent mode
B. somehow disable this specific animation (see video 1)


### vid1: interpolate animation disabled for RHP transition

https://github.com/Expensify/App/assets/3929868/5f991e73-6eba-420b-b7af-31863d07b313

**Comment by Kicu** [comment] 2024-07-04 15:05
I pushed a somewhat dirty hotfix here: https://github.com/Expensify/App/pull/44840

We could probably write the same code in a nicer way, but for now we can at least test since this is a deploy blocker

**Comment by s77rt** [comment] 2024-07-04 18:16
Passing the torch to @ishpaul777 as he can reproduce the bug and can better test the solution ([Slack thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1720116272747949)).

**Comment by Kicu** [comment] 2024-07-05 07:25
@mountiny I left some comments on my PR about what to do next since I cannot reproduce anymore, also asked a few folks in SWM to test how this behaves for them.
I leave the decisions what to do next to you.

**Comment by BrtqKr** [comment] 2024-07-10 15:14
Hey, we've noticed that this issue happens only on the most recent versions of safari (17.x.x). I've created a react-navigation issue. We'll try to research it at the library level, so this might help to resolve this, but atm I'd suggest keeping the workaround @Kicu applied. 

https://github.com/react-navigation/react-navigation/issues/12058

**Comment by jliexpensify** [comment] 2024-07-18 03:31
Bump @ishpaul777 for the checklist!

Payment Summary

- C+: @ishpaul777 $250

[Upwork job](https://www.upwork.com/jobs/~01c408a04e30a45b7f)

**Comment by jliexpensify** [comment] 2024-07-19 00:27
Paid and job closed. Bump @ishpaul777 for the checklist.

**Comment by jliexpensify** [comment] 2024-07-20 03:18
Thanks, closing!

**Closed by jliexpensify** 2024-07-20 03:18 UTC
Labels: External, Engineering, Daily, Bug
