### ISSUE TITLE
[$500] Chat - Some messages are not shown for other user if sent in quick succession

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34748] opened 2024-01-18 17:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log into New Expensify with Expensifail account on Device A
2. Log into New Expensify with Gmail account od Device B
3. Navigate to the conversation between both users on both devices
4. Send a few messages in quick succession from Device A

## Expected Result:
All messages should be displayed on Device B

## Actual Result:
Some messages are skipped and not displayed on Device B
User is forced to refresh the page to view all messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2e55fd4d-6fa7-46c8-b996-a314b82d06f5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-01-18 17:35
[#vip-vsb](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ)

**Comment by jeremy-croff** [comment] 2024-01-23 06:02
## Proposal

This is a tough one

### Please re-state the problem that we are trying to solve in this issue.
Users are not receiving all the messages when they are rapidly submitted, will have to refresh to see them

### What is the root cause of that problem?
The UI becomes out of sync, and skips older messages when it has already processed newer ones thinking it has already seen the older messages.

GetMissingOnyxMessages pauses the message queue, and by the time it resumes it can be ahead of the messages that are yet to be processed. There's a gap in the message's being processed and the onyx state.

### What changes do you think we should make in order to solve the problem?
(https://github.com/Expensify/App/blame/82fb44bdfd00d84ddc4abcb1e19ba686c7ed9fed/src/libs/actions/OnyxUpdates.ts#L74) This is where the logic resides for checking the last updated id.

We can choose to apply the data here even if it's not the most current updated ID.
I don't see any reason not to process the message from pubsub if we are receiving it. 

### What alternative solutions did you explore? (Optional)
Trying to dig deeper into finding why the state becomes out of sync

**Comment by sakluger** [comment] 2024-01-23 23:34
Added to #vip-vsb, asking how best to categorize it within that project.

**Comment by quinthar** [comment] 2024-01-24 00:20
Looks like a good one to fix!  @iwiznia do you agree with the problem description?

**Comment by sakluger** [comment] 2024-01-29 18:54
@iwiznia what are your thoughts here?

**Comment by iwiznia** [comment] 2024-01-29 18:58
> The UI becomes out of sync, and skips older messages when it has already processed newer ones thinking it has already seen the older messages.
> GetMissingOnyxMessages pauses the message queue, and by the time it resumes it can be ahead of the messages that are yet to be processed. There's a gap in the message's being processed and the onyx state.

Huh? Why? This should not happen because:
- Whenever we receive an update, we receive the previousUpdateID
- If the previousUpdateID is not the same as the last updateID the app has, it calls GetMissingOnyxMessages to get the updates between the last updateID the app has and the previousUpdateID of the update we got, then applies those updates
- Given that we are ensured to have all updates in this step, we apply the update we already got

@jeremy-croff can you delve further into the issue to figure out what exactly of this flow is broken?

> We can choose to apply the data here even if it's not the most current updated ID.
> I don't see any reason not to process the message from pubsub if we are receiving it. I don't believe messaging can guarantee order so the logic on the client side to expect order might not be a good fit.

We can't do this, as applying an old update can make the app be in a wrong state.

**Comment by jeremy-croff** [comment] 2024-01-30 01:29
> > The UI becomes out of sync, and skips older messages when it has already processed newer ones thinking it has already seen the older messages.
> > GetMissingOnyxMessages pauses the message queue, and by the time it resumes it can be ahead of the messages that are yet to be processed. There's a gap in the message's being processed and the onyx state.
> 
> Huh? Why? This should not happen because:
> 
> * Whenever we receive an update, we receive the previousUpdateID
> * If the previousUpdateID is not the same as the last updateID the app has, it calls GetMissingOnyxMessages to get the updates between the last updateID the app has and the previousUpdateID of the update we got, then applies those updates
> * Given that we are ensured to have all updates in this step, we apply the update we already got
> 
> @jeremy-croff can you delve further into the issue to figure out what exactly of this flow is broken?
> 
> > We can choose to apply the data here even if it's not the most current updated ID.
> > I don't see any reason not to process the message from pubsub if we are receiving it. I don't believe messaging can guarantee order so the logic on the client side to expect order might not be a good fit.
> 
> We can't do this, as applying an old update can make the app be in a wrong state.



> > The UI becomes out of sync, and skips older messages when it has already processed newer ones thinking it has already seen the older messages.
> > GetMissingOnyxMessages pauses the message queue, and by the time it resumes it can be ahead of the messages that are yet to be processed. There's a gap in the message's being processed and the onyx state.
> 
> Huh? Why? This should not happen because:
> 
> * Whenever we receive an update, we receive the previousUpdateID
> * If the previousUpdateID is not the same as the last updateID the app has, it calls GetMissingOnyxMessages to get the updates between the last updateID the app has and the previousUpdateID of the update we got, then applies those updates
> * Given that we are ensured to have all updates in this step, we apply the update we already got
> 
> @jeremy-croff can you delve further into the issue to figure out what exactly of this flow is broken?
> 
> > We can choose to apply the data here even if it's not the most current updated ID.
> > I don't see any reason not to process the message from pubsub if we are receiving it. I don't believe messaging can guarantee order so the logic on the client side to expect order might not be a good fit.
> 
> We can't do this, as applying an old update can make the app be in a wrong state.

I seem unable to reproduce this right now

**Comment by mvtglobally** [comment] 2024-01-30 04:58
Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment] 2024-02-01 19:28
I also couldn't reproduce. Closing for now! We can reopen if it becomes reproducible again.

**Closed by sakluger** 2024-02-01 19:28 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
