### ISSUE TITLE
[$500] [3rd Party Feeds] Company cards page

### ISSUE THREAD

**Issue by robertjchen** [Expensify/App#47376] opened 2024-08-14 04:48 UTC
# Part of the Third Party Workspace Feeds project
Main issue: https://github.com/Expensify/Expensify/issues/394008
Doc section: [Doc Link](https://docs.google.com/document/d/1PXx506PM7-sGW3Zones8mWieZgnqRJ5qYXzTOZ3dnlg/edit?pli=1#bookmark=id.mm6t04y0mb0d)
Project: [<Project Link>](https://github.com/orgs/Expensify/projects/130/views/11)

# Feature Description
- [x] Company cards empty state (@waterim)
- [x] Add Card Feed Flow (@waterim)
- [ ] Pending State with No Other Feeds (@waterim)
- [x] Feed Added Empty State (@narefyev91)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f14c3cdaeae82c2</li>
        <li>Upwork Job ID: 1823734726079087014</li>
        <li>Last Price Increase: 2024-10-01</li>
    </ul>
</details>

**Comment by robertjchen** [comment] 2024-08-14 05:42
@waterim

**Comment by joekaufmanexpensify** [comment] 2024-08-14 13:35
I'm working with this Robert on this project, but I don't need to be assigned to every frontend new feature issue, as the work here is just regular BZ management. Going to revert back to the chosen auto-assignee!

**Comment by joekaufmanexpensify** [comment] 2024-08-14 13:36
@alexpensify , as an fyi @narefyev91 and @waterim are working on this, and as soon as they comment, you'll be able to assign them! Setting to daily as this is deliverable by September 9th, 2024

**Comment by narefyev91** [comment] 2024-08-14 14:47
Hey! I'm Nicolay from Callstack - will work on this issue

**Comment by alexpensify** [comment] 2024-08-16 20:11
Everyone has been assigned here, just waiting for the PR to continue with the next steps.

**Comment by waterim** [comment] 2024-08-19 11:42
Hello, Im Artem from Callstack and would like to work on these features!

**Comment by waterim** [comment] 2024-08-19 11:43
Will start from empty state

**Comment by alexpensify** [comment] 2024-08-26 15:26
## Next Steps

This PR is going through the review process. 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment] 2024-09-03 23:17
Catching up from being OOO, I see the PR is moving along.

**Comment by alexpensify** [comment] 2024-09-11 23:03
I believe that we are waiting for one more PR here.

**Comment by alexpensify** [comment] 2024-09-18 19:33
Weekly Update: Waiting for this one to go to production

**Comment by alexpensify** [comment] 2024-09-20 22:25
Now we wait for this one to go through automation. It went into production yesterday.

**Comment by alexpensify** [comment] 2024-09-27 18:06
Automation didn't kick in, so I'll need to manually work on the payment process.

**Comment by alexpensify** [comment] 2024-09-30 20:06
Payouts due: 09-27-2024

- [ ] Contributor: @waterim - payment will be handled via the vendor 
- [ ] Contributor+: $250 @Pujan92 - please submit a request in Chat 

Upwork job is N/A. Closing, @Pujan92 will submit a request.

**Comment by Pujan92** [comment] 2024-09-30 20:13
@alexpensify as this issue is divided in multiple PR's, just wanted to confirm isn't the compensation should be more?

**Comment by alexpensify** [comment] 2024-09-30 21:26
@joekaufmanexpensify and @robertjchen, since this is a larger project you've been working on, can I get your feedback on whether there was an amount that was discussed previously for the reviews? Thanks!

**Comment by Pujan92** [comment] 2024-10-01 16:15
Better if we keep it open until it gets confirmed for the price, so it won't missed by me and stay in my K2 list.

**Comment by joekaufmanexpensify** [comment] 2024-10-01 19:31
[Discussing ](https://expensify.slack.com/archives/C01SKUP7QR0/p1727811077412969)

**Comment by alexpensify** [comment] 2024-10-01 23:24
Based on the internal discussion, the summary has been updated here: https://github.com/Expensify/App/issues/47376#issuecomment-2384053548

**Comment by alexpensify** [comment] 2024-10-01 23:25
@Pujan92 - please submit a request in chat for this new amount. Thanks!

**Closed by alexpensify** 2024-10-01 23:25 UTC
Labels: Reviewing, External, Weekly, NewFeature

**Comment by garrettmknight** [comment] 2024-10-02 15:07
$500 approved for @Pujan92
