### ISSUE TITLE
[$500]  Workspace - Tooltip 'Get assistance from our team"' Displays Before Hovering Over Icon

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31724] opened 2023-11-22 16:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to Settings > Workspaces > New Workspace
2. Hover over the question mark icon
3. Notice that the tooltip "Get assistance from our team" is displayed before hovering over the icon

## Expected Result:
The "Get assistance from our team" tooltip should be displayed only when the user hovers over the icon

## Actual Result:
The "Get assistance from our team" tooltip is displayed before hovering over the question mark icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
 
 
<img width="436" alt="Bug6286960_1700650046267!Screenshot_2023-11-22_at_3 46 34_PM" src="https://github.com/Expensify/App/assets/78819774/5f2fd5b6-f746-49d1-8e3c-0a8c82babf3a">

https://github.com/Expensify/App/assets/78819774/4a4325e1-3045-4329-8986-79600a8a7537

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e278b6512dd70f3</li>
        <li>Upwork Job ID: 1727370031987064832</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by erquhart** [comment] 2023-11-22 16:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tooltip shows before info icon is hovered.

### What is the root cause of that problem?

The pressable container has a static width and height of 40px.

### What changes do you think we should make in order to solve the problem?

Remove the static width and make only the icon clickable.

**Comment by DylanDylann** [comment] 2023-11-22 17:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Tooltip 'Get assistance from our team"' Displays Before Hovering Over Icon
### What is the root cause of that problem?
The Tooltip Component is wrapping PressableWithoutFeedback
### What changes do you think we should make in order to solve the problem?
In HeaderWithBackButton we should update like this
```
<Tooltip text={translate('getAssistancePage.questionMarkButtonTooltip')}>
                                <Icon
                                    src={Expensicons.QuestionMark}
                                    fill={iconFill}
                                />
                        </Tooltip>
```

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-11-22 17:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tooltip `Get assistance from our team` appears before hovering over the question icon in workspace page

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/b30b55574bd3453c7c8d012aa39d62fe9de569f6/src/components/HeaderWithBackButton/index.js#L134-L147
As you can see above, `tooltip` is wrapping the `Pressable`, not the `icon`. Icon size is 20 and `Pressable` size is 40.

This is the root cause

### What changes do you think we should make in order to solve the problem?

Of course, we can wrap the icon with tooltip, but I don't think this is a solution because button area and icon area looks different. That is, the cursor will be changed before hovering the icon

I think the ideal solution is to make the style of the `Pressable` same as icon

<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment] 2023-11-23 23:39
Few proposals ready for review @sobitneupane

**Comment by sobitneupane** [comment] 2023-11-28 08:25
Sorry for the delay. I will review the proposals today.

**Comment by sobitneupane** [comment] 2023-11-29 08:33
@bfitzexpensify This doesn't look like a bug to me. I believe it's an intended design decision. We show tooltip for icons (throughout the app) when we hover over the pressable area. The same is the case for search icon, back icon, etc.

**Comment by bfitzexpensify** [comment] 2023-11-29 14:44
@sobitneupane ah yes, you're right, just confirmed myself with a few other tooltips. OK, let's close this one out.

**Closed by bfitzexpensify** 2023-11-29 14:44 UTC
Labels: External, Daily, Help Wanted, Bug
