### ISSUE TITLE
[HOLD for payment 2023-10-09] [$1000] Quoting macOS Download Link with text will result in unexpected behaviour

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23672] opened 2023-07-26 17:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app in Android native app (this issue only occurs in Android native)
2. Go to any chat
3. Type a message:` > https://new.expensify.com/NewExpensify.dmg test`
4. Send it

## Expected Result: 
All characters should be visible

## Actual Result: 
The end characters will not be visible

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7330f977-7909-4029-be8c-4e1f14569fe1
![Screenshot_20230726-134920_New Expensify](https://github.com/Expensify/App/assets/43996225/232fd215-e95b-4810-9a39-65f2ecb2f88c)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690296200318199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4f40b6933ecb982</li>
        <li>Upwork Job ID: 1686407694784102400</li>
        <li>Last Price Increase: 2023-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26853127</li>
<li>pradeepmdk | Contributor | 26853130</li>
<li>daraksha-dk | Reporter | 26853132</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-07-27 23:46
Asked a few clarifying questions in the Slack thread

**Comment by sakluger** [comment] 2023-08-05 01:13
Huh, no proposals at all! Let's give it another week and see if we get any proposals at this price.

**Comment by sakluger** [comment] 2023-08-07 20:09
Still waiting for proposals.

**Comment by sakluger** [comment] 2023-08-09 21:01
> this issue also occurs on other links and it also occurs without blockquote.

@Krishna2323 thanks, that's helpful! Were you able to determine why it happens for some links but not others?

@abdulrahuman5196, mind taking a look at the two proposals we received?

**Comment by pradeepmdk** [comment] 2023-08-10 15:50
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
A message with a button gets cut off early for a certain length of emails

### What is the root cause of that problem?

dude to  android  textbreakstrategy  its breaking
ex: [here](https://reactnative.dev/docs/text#textbreakstrategy-android) and [here](https://stackoverflow.com/a/53237068/7965547)
![Screenshot 2023-08-01 at 8 17 50 AM](https://github.com/Expensify/App/assets/16595846/3a6e82b4-864b-403b-af67-215336016092)

### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/d6a14d797753e8b7886b3c85a4450ff9cdd6e6be/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js#L60

```javascript
    const defaultTextProps = useMemo(() => ({selectable: props.textSelectable, allowFontScaling: false, textBreakStrategy: "simple", }), [props.textSelectable]);

``` 
pass `textBreakStrategy: "simple",`

Result: 
<img width="348" alt="Screenshot 2023-08-10 at 9 17 50 PM" src="https://github.com/Expensify/App/assets/16595846/89034a2c-9cd9-4a01-a4ce-f568ee74dab9">

**Comment by pradeepmdk** [comment] 2023-08-10 15:52
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
Quoting macOS Download Link with text will result in unexpected behaviour

### What is the root cause of that problem?

dude to  android  textbreakstrategy  its breaking
ex: [here](https://reactnative.dev/docs/text#textbreakstrategy-android) and [here](https://stackoverflow.com/a/53237068/7965547)
![Screenshot 2023-08-01 at 8 17 50 AM](https://github.com/Expensify/App/assets/16595846/3a6e82b4-864b-403b-af67-215336016092)

### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/d6a14d797753e8b7886b3c85a4450ff9cdd6e6be/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js#L60

```javascript
    const defaultTextProps = useMemo(() => ({selectable: props.textSelectable, allowFontScaling: false, textBreakStrategy: "simple", }), [props.textSelectable]);

``` 
pass `textBreakStrategy: "simple",`

Result: 
<img width="348" alt="Screenshot 2023-08-10 at 9 17 50 PM" src="https://github.com/Expensify/App/assets/16595846/89034a2c-9cd9-4a01-a4ce-f568ee74dab9">

**Comment by sakluger** [comment] 2023-08-10 22:29
@abdulrahuman5196 can you take a look at the proposals we've received so far? If you already have a full plate, I'm happy to reassign.

**Comment by abdulrahuman5196** [comment] 2023-08-12 18:47
I am reviewing all my pending items this weekend. Will close review on this as well

**Comment by abdulrahuman5196** [comment] 2023-08-13 11:36
I am not sure what is the issue here, for me it seems to be working fine. Anything I am missing here. @sakluger 


https://github.com/Expensify/App/assets/46707890/e6d786d6-24e5-4efa-b9fc-44483a8359a9

**Comment by mvtglobally** [comment] 2023-08-16 20:42
Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment] 2023-08-17 04:51
Looks like this is not longer reproduceable, I'm going to close the issue. Feel free to comment on the original thread if you're able to reproduce on the latest build.

**Comment by sakluger** [comment] 2023-08-24 21:09
Opening this back up because several contributors were able to reproduce on the latest build.

**Comment by pradeepmdk** [comment] 2023-08-25 01:35
@sakluger can you review my proposal https://github.com/Expensify/App/issues/23672#issuecomment-1673491181 and here i am attaching the reference ticket
https://github.com/meliorence/react-native-render-html/issues/360#issuecomment-761612982

**Comment by abdulrahuman5196** [comment] 2023-08-28 12:10
I will try to repro the issue again and update here

**Comment by sakluger** [comment] 2023-08-28 18:44
@pradeepmdk I cannot review proposals as I am not an engineer. I'm mainly here to make sure the issue keeps moving forward :)

**Comment by sakluger** [comment] 2023-08-31 22:44
@abdulrahuman5196 any luck reproducing?

**Comment by sakluger** [comment] 2023-09-01 23:08
@Krishna2323 can you write out the reproduction steps? Especially if they're different than the original steps, I want to make sure that @abdulrahuman5196 can also reproduce.

**Comment by abdulrahuman5196** [comment] 2023-09-04 15:32
Oh ok got it. I was able to reproduce by following this https://github.com/Expensify/App/issues/23672#issuecomment-1672307199.

It is a very strange issue. Could you kindly add this information to the OP description @sakluger

**Comment by abdulrahuman5196** [comment] 2023-09-04 15:35
And @Krishna2323 Kindly add all the information in your original proposal https://github.com/Expensify/App/issues/23672#issuecomment-1668714244 and mentioning UPDATED proposal in comment as per our guidelines should be enough. It will be easier to manage and to make sure we don't miss anything.

**Comment by abdulrahuman5196** [comment] 2023-09-04 15:55
@Krishna2323 's proposal (solution 1) here https://github.com/Expensify/App/issues/23672#issuecomment-1668714244 and @pradeepmdk 's proposal here https://github.com/Expensify/App/issues/23672#issuecomment-1673491181 is both working well.

But I not convinced on the root cause provided. @Krishna2323 , @pradeepmdk Could you kindly add more information or references on why this issue is coming? Is it due to bug in `react-native-render-html` or some other bug? Do we have any open GH against the repo or the RN repo?

**Comment by pradeepmdk** [comment] 2023-09-05 10:25
@abdulrahuman5196 I already mentioned in the proposal this will be due to reacting native textBreakStrategys  by default  its settings high_quality  https://github.com/Expensify/App/issues/23672#issuecomment-1673491181
I am adding a ref ticket from react native HTML
https://github.com/meliorence/react-native-render-html/issues/360#issuecomment-761612982 This given solution by [jsamr](https://github.com/jsamr) from react-native-render-HTML  

**I am using One Plus only it's working well.**

**Comment by sakluger** [comment] 2023-09-05 18:28
@abdulrahuman5196 I updated the OP to clarify that this only occurs on Android native.

**Comment by pradeepmdk** [comment] 2023-09-12 00:18
@abdulrahuman5196 
https://github.com/Expensify/App/assets/16595846/41f1e640-29cb-4eb9-b98f-2be67a9f63b1

**Comment by pradeepmdk** [comment] 2023-09-13 06:14
![Screenshot 2023-09-13 at 11 12 52 AM](https://github.com/Expensify/App/assets/16595846/d988fc08-663b-4fb4-9459-58e005fb82c4)
By default, `alignItemsStretch` is applied. for overriding the stretch only we are applying the `alignItemsStart`.
now this update @abdulrahuman5196 decision now.
both solutions work well for this issue. 

`alignItemsStretch` will take full space that why it's working for you when removing `alignItemsStart`
https://developer.mozilla.org/en-US/docs/Web/CSS/align-items

 Root cause is  `textbreakstrategy` only  https://github.com/Expensify/App/issues/23672#issuecomment-1673491181

**Comment by sakluger** [comment] 2023-09-14 17:28
@abdulrahuman5196 could you please check the latest responses here?

**Comment by abdulrahuman5196** [comment] 2023-09-14 18:56
Both @Krishna2323 's proposal here https://github.com/Expensify/App/issues/23672#issuecomment-1668714244 and @pradeepmdk 's proposal here https://github.com/Expensify/App/issues/23672#issuecomment-1673491181 is working fine.

Now looking at both proposals, I find @pradeepmdk 's proposal more reasonable change. Given this issue is happening in the html component and the bug travels upstream. @pradeepmdk has referenced the `react-native-render-html` issue here https://github.com/Expensify/App/issues/23672#issuecomment-1706353574 which suggests the fix.

So I am going ahead with approving @pradeepmdk 's proposal of textBreakStrategy here https://github.com/Expensify/App/issues/23672#issuecomment-1673491181

🎀 👀 🎀
C+ Reviewed

**Comment by sakluger** [comment] 2023-09-18 07:41
@abdulrahuman5196 @grgia what do you think about @Krishna2323's comment?

**Comment by pradeepmdk** [comment] 2023-09-18 08:17
we are facing this issue inside the `react-native-render-html` they also agree bug from react-native so they are giving the solution here. so we need to update the `react-native-render-html` props.

>So this bug has reportedly appeared with React Native on Android Q (https://github.com/facebook/react-native/issues/25258). Since v5 release, you can use defaultTextProps and set textBreakStrategy to highQuality simple in order to circumvent this bug. I'm closing this thread now as there is an easy workaround and the bug is upstream.

https://github.com/meliorence/react-native-render-html/issues/360#issuecomment-761612982

also, I verified the one plus devices there is no issue with that. (as mentioned by StackOverflow)
https://github.com/Expensify/App/issues/23672#issuecomment-1714783263

and  https://github.com/Expensify/App/issues/23672#issuecomment-1720037494 compared to this links comments this is  the updated one https://github.com/meliorence/react-native-render-html/issues/360

**Comment by pradeepmdk** [comment] 2023-09-19 09:36
@grgia  bump

**Comment by grgia** [comment] 2023-09-20 06:14
@abdulrahuman5196 do you still stand by your C+ recommendation given the above comments?

**Comment by abdulrahuman5196** [comment] 2023-09-20 06:22
@grgia yes IMO. There isn't any strong recommendation from react native team on the RN issue. Since we use react-native-render-html  directly and they have provided a simple fix as a suggestion, I am recommending to go with the suggestion from react-native-render-html team. And the issue is not worth a upstream fix as well.

**Comment by pradeepmdk** [comment] 2023-09-23 01:08
@grgia bump

**Comment by grgia** [comment] 2023-09-25 09:56
Thanks you, assigned!

**Comment by mvtglobally** [comment] 2023-09-28 03:12
Issue not reproducible during KI retests. (First week)

**Comment by abdulrahuman5196** [comment] 2023-10-09 18:00
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. But its a behavioral miss from start.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Minor issue which unable to reproduce always. Not beneficial to add a regression test.

**Comment by sakluger** [comment] 2023-10-09 18:28
Thanks! @pradeepmdk and @abdulrahuman5196, you've paid via Upwork (with the efficiency bonus 🚀 ).

@daraksha-dk could you please accept the offer in Upwork so I can complete payment? Thanks!

**Comment by sakluger** [comment] 2023-10-12 05:54
@daraksha-dk Thanks for letting me know! I've completed payment for $250.

**Closed by sakluger** 2023-10-12 05:54 UTC
Labels: External, Daily, Awaiting Payment, Bug
