### ISSUE TITLE
[HOLD for payment 2024-02-26] [$500] [MEDIUM] Smartscan: Thread - You can go to the notifications@expensify.com profile and send a private message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32500] opened 2023-12-05 18:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Navigate to any conversation
3. Request money from another account by uploading a non-legible receipt (a random pic).
4. Wait for smartscan to finish. It should fail.
5. Navigate to the IOU details
6. Create a thread with a system message about a receipt scanning failure
7. In the thread header, click on the "Expensify" avatar
8. In the RHP that appears, click on "Members"
9. In "Members," click on "Expensify."
10. In "Profile" click on "Message Expensify"

## Expected Result:
[notifications@expensify.com](mailto:notifications@expensify.com)
account should be hidden from user interaction

## Actual Result:
Through thread, you can go to the [notifications@expensify.com](mailto:notifications@expensify.com)
profile and send a private message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f69a58b3-d991-4af7-81c5-de9961946e7e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013bd0e1cccedfb977</li>
        <li>Upwork Job ID: 1732097741987237888</li>
        <li>Last Price Increase: 2024-01-02</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28124783</li>
<li>mkhutornyi | Contributor | 28124784</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-12-05 18:09
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Thread - You can go to the notifications@expensify.com profile and send a private message

### What is the root cause of that problem?

This is due to missing restrictions on email chat in `navigateToAndOpenReportWithAccountIDs`.

### What changes do you think we should make in order to solve the problem?

Add restrictions in the function as well as disable showing message icon at all (Maybe disable reply as well)

### What alternative solutions did you explore? (Optional)

**Comment by chiItepin** [comment] 2023-12-05 18:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user is able to send a private message to an official Expensify user that is meant to behave such a bot

### What is the root cause of that problem?
In `ProfilePage` we are only not showing up the "message" button to current user and anonymous users

### What changes do you think we should make in order to solve the problem?


We should expand and consolidate the condition to not include certain known bot accounts so that the `MenuItem` is not rendered

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by yh-0218** [comment] 2023-12-05 19:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
You can reply to message came from [notifications@expensify.com](mailto:notifications@expensify.com) profile
### What is the root cause of that problem?
We didn't consider about  notification account [here](https://github.com/Expensify/App/blob/52a6383349ef705b04e2d26233ab68c0a1c91124/src/pages/ReportParticipantsPage.js#L91)
### What changes do you think we should make in order to solve the problem?
We need to update like this to disable notification account profile.
```
isDisabled: ReportUtils.isOptimisticPersonalDetail(participant.accountID) || participant.accountID === CONST.ACCOUNT_ID.NOTIFICATIONS
```
### What alternative solutions did you explore? (Optional)

https://github.com/Expensify/App/assets/65789015/cfef2510-c036-444c-9573-70cb65656556

**Comment by puneetlath** [comment] 2023-12-14 18:06
Posted in #wave5 about what the ideal behavior should be here: https://expensify.slack.com/archives/C05DWUDHVK7/p1702577149414069

**Comment by puneetlath** [comment] 2023-12-14 18:16
Going to assign to @dylanexpensify to figure out ideal behavior and distribute as part of wave5.

**Comment by dylanexpensify** [comment] 2023-12-20 09:31
Need to confirm behavior this week

**Comment by dylanexpensify** [comment] 2023-12-21 15:07
Behavior: 
- you can thread any message, including those from notifications@
- you cannot view the profile or message notifications@

@0xmiroslav can we review proposals?

**Comment by dylanexpensify** [comment] 2024-01-09 12:18
nice, any updates @0xmiroslav

**Comment by dylanexpensify** [comment] 2024-01-10 15:56
bump @0xmiroslav

**Comment by dylanexpensify** [comment] 2024-01-15 13:40
bump @0xmiroslav

**Comment by dylanexpensify** [comment] 2024-01-17 09:28
Bump @0xmiroslav

**Comment by dylanexpensify** [comment] 2024-01-23 13:31
calling out for volunteer today

**Comment by mallenexpensify** [comment] 2024-01-24 03:43
@fedirjh reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by blimpich** [comment] 2024-01-24 21:47
@fedirjh Can you look over the most recent comments and tell me if @yh-0218's proposal is still your preferred solution? I haven't had the time to look over this issue in depth today and want to make sure your opinion is unchanged before I read through all the comments here and assign.

**Comment by blimpich** [comment] 2024-01-27 00:58
Okay I read through everything here and also our Expensify internal chats about expected behavior. I like @mkhutornyi's proposal best. I agree that we should try to keep it simple like @fedirjh said but blocking the profile is a good simple addition to this issue's solution, and I also like the suggestion of creating a utility function for when we add more accounts like this to the list. The list of bots like the notifications bot is only going to increase as the app matures, so lets get a head start on abstracting out that logic and making this part of the codebase clean and maintainable.

@dukenv0307 you make great points, but after talking internally we do want it to be in the members list, even though its a bot. This is more a design decision than a engineering decision so its fairly subjective, but we've decided that that is what we want.

The empty list case is interesting. I consider it out of scope for this issue, especially since I'm honestly not sure how that should be handled. I'll bring this up internally and see what we want to do with this empty list scenario. I think what will happen is we will come to a decision internally on how to handle this and then I'll create the issue in GH. When that happens I'll tag you.

**Comment by dylanexpensify** [comment] 2024-01-29 12:04
@mkhutornyi when can we expect PR?

**Comment by dylanexpensify** [comment] 2024-02-13 20:20
@fedirjh mind giving an update

**Comment by dylanexpensify** [comment] 2024-02-21 10:45
payment coming up!

**Comment by dylanexpensify** [comment] 2024-02-28 09:06
payment today!

**Comment by dylanexpensify** [comment] 2024-02-28 10:31
Payment summary:
- Contributor: @mkhutornyi $500
- Contributor+: @fedirjh $500

Please apply

**Comment by dylanexpensify** [comment] 2024-02-28 10:31
paid!

**Closed by dylanexpensify** 2024-02-28 10:31 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug, SmartScan
