### ISSUE TITLE
[$500] [Distance] - Incorrect Amount after updating distance rate

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27051] opened 2023-09-08 18:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Request money
2. Select distance
3. Fill start and finish points and click next
4. In a new tab change the rate of the workspace

## Expected Result:
The amount should be recalculated after updating the distance rate

## Actual Result:
Incorrect Amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/76ee146f-f9ba-41a4-827a-4fd2c305630b

https://github.com/Expensify/App/assets/93399543/73f288a3-b24d-4fd3-8dec-1d58159963a6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693858446228419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f2b0dfe92fa39b6</li>
        <li>Upwork Job ID: 1700221326639685632</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-09-08 19:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Updating distance rate in other tab isn't update the earlier calculated amount

### What is the root cause of that problem?
Currently, we are only calculating the amount when the current iou amount is 0 which kind of gets calculated the first time only. 
https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/components/MoneyRequestConfirmationList.js#L173

### What changes do you think we should make in order to solve the problem?
We need to consider the recalculation for 2 cases 
1) when the mileage gets updated in other tab (we are rerendering the component on mileage change)
https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/components/MoneyRequestConfirmationList.js#L173
2) When we update the waypoint by going back and come to this page again

To recalculate we need to take out the iou amount condition and keep only `props.isDistanceRequest`.

**Note**: I actually provided the solution recalculation in one of the other issue [here](https://github.com/Expensify/App/issues/26583#issuecomment-1703996357)(I am not sure whether it considers or not) regarding the waypoint but posting here again with the explanation of the mileage part too.

**Comment by DylanDylann** [comment] 2023-09-09 06:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect Amount after updating distance rate

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/components/MoneyRequestConfirmationList.js#L173
We only calculate the amount if the props.iouAmount === 0. So when the rate is changed, we don't re-calculate the amount
### What changes do you think we should make in order to solve the problem?
I think props.iouAmount === 0 condition is added to reduce the redundant computation.
In here
https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/components/MoneyRequestConfirmationList.js#L173-L188
we should remove the shouldCalculateDistanceAmount variable and to avoid redundant re-calculate we can create a new variable called amount in a useMemo and use it instead of calling getDistanceRequestAmount function

this is demo code change

```
const amount = useMemo(() => DistanceRequestUtils.getDistanceRequestAmount(distance, unit, rate), [distance, unit, rate]) 
const formattedAmount = CurrencyUtils.convertToDisplayString(
        props.isDistanceRequest ? amount : props.iouAmount,
        props.isDistanceRequest ? currency : props.iouCurrencyCode,
);

useEffect(() => {
        if (!props.isDistanceRequest) {
            return;
        }
        IOU.setMoneyRequestAmount(amount);
}, [props.isDistanceRequest, distance, rate, unit, amount]);

```

### What alternative solutions did you explore? (Optional)

**Comment by anmurali** [comment] 2023-09-26 23:29
Closing this as a dupe of https://github.com/Expensify/App/issues/26946

**Closed by anmurali** 2023-09-26 23:29 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by hichamcc** [comment] 2023-09-27 01:38
@anmurali I reported it first

**Comment by DylanDylann** [comment] 2023-10-03 04:07
@anmurali @Ollyws Currently, we can'r reproduce https://github.com/Expensify/App/issues/26946 But we still reproduce this bug. It's not a dupe, Let's re-open it

**Comment by DylanDylann** [comment] 2023-10-12 10:13
@anmurali Bump on this one
