### ISSUE TITLE
[HOLD for payment 2023-12-12] [$500] Chat - No skeleton loading when scrolling up the chat history offline until the chat is reopened

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31367] opened 2023-11-15 13:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Log in to HT account.
3. Open a chat that has long chat history.
4. Go offline.
5. Scroll to the top.
6. Return to LHN.
7. Reopen the chat in Step 2 and scroll to the top.

## Expected Result:
In Step 5, skeleton placeholder will appear.

## Actual Result:
In Step 5, skeleton placeholder does not appear. It only appears when the chat is revisited in Step 7.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/05c4f8c8-1320-49d7-bbe6-3b31cf508638

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01073572ec47fdb07b</li>
        <li>Upwork Job ID: 1724786009891438592</li>
        <li>Last Price Increase: 2023-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 28015843</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-11-15 15:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The top report skeleton is not visible when offline.

### What is the root cause of that problem?


### What changes do you think we should make in order to solve the problem?

In `ReportActionsView`:

**First,** Move (and slightly modify) this code outside of `loadOlderChats`:

```js
    const oldestReportAction = _.last(props.reportActions);
    const isLoadedTillBeginning = lodashGet(oldestReportAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.CREATED;
```

https://github.com/Expensify/App/blob/772715011ce1431884bb499164faa36dcc8006e6/src/pages/home/report/ReportActionsView.js#L185-L190

**Second,** modify the logic for displaying the top skeleton:
```js
isLoadingOlderReportActions={props.isLoadingOlderReportActions || (props.network.isOffline && !isLoadedTillBeginning)}
```

https://github.com/Expensify/App/blob/772715011ce1431884bb499164faa36dcc8006e6/src/pages/home/report/ReportActionsView.js#L262



### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2023-11-15 20:18
@paultsimura Thanks for the proposal. Your RCA makes sense but the solution does not look good to me. `props.network.isOffline && !isLoadedTillBeginning` will make `isLoadingOlderReportActions` evaluates to `true` even if we are not loading any report action.

**Comment by s77rt** [comment] 2023-11-15 20:20
I see this is a regression from https://github.com/Expensify/App/pull/30658 and it's still within the regression period. In this case this should be fixed by the Contributor/Contributor+ @paultsimura / @getusha

**Comment by getusha** [comment] 2023-11-16 14:43
I agree this looks like a regression from https://github.com/Expensify/App/pull/30658
@paultsimura could you address @s77rt's [comment](https://github.com/Expensify/App/issues/31367#issuecomment-1813201178) and raising a PR if possible?

**Comment by paultsimura** [comment] 2023-11-16 14:47
Yes, I'm on it. However, @s77rt could you please elaborate a little on why is this bad?

> props.network.isOffline && !isLoadedTillBeginning will make isLoadingOlderReportActions evaluates to true even if we are not loading any report action

If we are offline and not at the beginning of the conversation yet – this means we will eventually load the newer actions when online, doesn't it?
We're not loading the older actions when offline anyway, so in my understanding, the skeleton here is used only to show the user that there are some more actions to load.

**Comment by s77rt** [comment] 2023-11-16 18:18
@paultsimura The logic makes sense but just the way we are modifying the `isLoadingOlderReportActions` prop is counterintuitive. If `isLoadingOlderReportActions` is true then we must be indeed loading older report actions otherwise this prop won't be a reliable source of truth.

A slight adjustment is to move the logic to `ListBoundaryLoader`. This would keep the prop untouched and achieve same results.

**Comment by paultsimura** [comment] 2023-11-17 10:34
Thanks @s77rt, this makes sense.

I would like to clarify the expected UI in the offline case: should we show the long skeleton, similar to when loading the older events, or the shorter one – like when loading the initial report actions? 

<details><summary>Short</summary>


https://github.com/Expensify/App/assets/12595293/cb8a23b7-051c-48ec-90a2-1171712fc7a9


</details> 

<details><summary>Long</summary>



https://github.com/Expensify/App/assets/12595293/2062a237-2575-4dd9-a9b4-d5674794f571





</details> 

Also, I suppose it should be not animated when offline, similar to the `LoadingInitialActions` skeleton:

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/pages/home/report/ListBoundaryLoader/ListBoundaryLoader.js#L48-L51

@shawnborton could you please share your upinion here?

**Comment by shawnborton** [comment] 2023-11-17 13:34
Hmm shorter seems to make more sense to me, but cc @Expensify/design for thoughts in case they disagree.

Also, it looks like we are missing the animation on the skeleton lines above the preview cards. Any idea why those skeleton lines are not using the pulse/fade/gradient animation?

**Comment by paultsimura** [comment] 2023-11-17 13:43
@shawnborton looks like it was made on purpose: we're disabling the animation when offline:

https://github.com/Expensify/App/blob/d521dd6783c382297e06a429701ae1936f808041/src/pages/home/report/ListBoundaryLoader/ListBoundaryLoader.js#L51

I believe this was made so that the user won't expect something new to be loaded while offline (the animation implies that something's happening).

If that's not the expected behaviour, I can remove this condition and the result will look like this:


https://github.com/Expensify/App/assets/12595293/a0e0bcfc-6dbc-448b-b3eb-c58ae1e3fde8

**Comment by dannymcclain** [comment] 2023-11-17 13:49
Oh that's interesting about the animation—it makes total sense after you explain it, but I'm not sure anyone will connect those dots on their own. I don't have strong feelings about it though so I'll leave it to @shawnborton.

I'm also a fan of the short skeleton in this situation—it does it's job communicating the state so I don't think we need any more than that.

**Comment by shawnborton** [comment] 2023-11-17 13:56
Hmm yeah, I see the point too. I think I'd rather just always have the subtle animation though, otherwise we get into a weird situation where we try to determine if the loading state should be animated or not based on connectivity, which might not be truly offline but could be flakey and cause some weird start/stop of the animation? So I lean towards just always having it.

**Comment by paultsimura** [comment] 2023-11-17 17:03
Thanks y'all. The PR is ready: https://github.com/Expensify/App/pull/31492

**Comment by s77rt** [comment] 2023-12-05 20:44
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/30658
- The offending PR has been commented on: https://github.com/Expensify/App/pull/30658#discussion_r1416251002
- A discussion in #expensify-bugs has been started: I don't think we need this here
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

1. Open a chat that has a many messages
2. Go offline
3. Scroll to the top
4. Verify that the skeleton loader is displayed

**Comment by s77rt** [comment] 2023-12-05 20:46
@mallenexpensify Please assign @getusha and @paultsimura here since this is a part of https://github.com/Expensify/App/issues/30503

**Comment by getusha** [comment] 2023-12-13 12:23
@mallenexpensify we can close this as it was handled as a regression.

**Closed** 2023-12-18 17:30 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
