### ISSUE TITLE
mWEB/Safari - Nothing happens when tap "Set up my company for free"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11245] opened 2022-09-23 17:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #10949
## Action Performed:
1. Navigate to the URL https://staging.expensify.com/
2. Tap email > Enter email > Next > Join
3. Tap "Set up my company for free"

## Expected Result:
User should be redirected to new created workspace.

## Actual Result:
Nothing happens when tap "Set up my company for free".

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web Safari

**Version Number:** 1.1.21-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):**
 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/192021263-b60d1023-3de5-48d9-9d57-e8198bb20d52.mp4

<img src="https://user-images.githubusercontent.com/43996225/192021664-92cc93b3-0633-493c-9458-53e26b80f06a.png" width="40%" height="40%">
**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2022-09-26 16:05
I'm able to reproduce on iOS.

**Comment by Christinadobrzyn** [comment] 2022-10-19 02:45
I think this was assigned the wrong way, should have gone to triage and then eng. Asking [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1666147427523899) to make sure I'm not missing a workflow change. Sending to eng to determine if we can close or make external.

**Comment by pecanoro** [comment] 2022-10-19 14:50
@Julesssss I was going to add External but I see you added FirstPick, do you want to leave it internal?

**Comment by Julesssss** [comment] 2022-10-19 15:09
I think it needs to be internal right? As the change would occur in OldDot?

**Comment by pecanoro** [comment] 2022-10-19 15:16
Omg, you are right, I guess I am not fully awake yet lol

**Comment by dangrous** [comment] 2022-10-19 19:02
Grabbing this, it looks like the function to open new dot can't find `App` [here](https://github.com/Expensify/Web-Expensify/blob/fd2b4022de5962267f2fdf410c20824216ca248c/homepage/js/signin.jsx#L1290) and so that's why it's not doing anything. That's [added as a global variable](https://github.com/Expensify/Web-Expensify/blob/fd2b4022de5962267f2fdf410c20824216ca248c/homepage/js/signin.jsx#L1), though... Any thoughts on why this might not be working?

**Comment by Julesssss** [comment] 2022-10-20 09:18
Afraid not @dangrous, but I think your initial guess is on the right track.

**Comment by dangrous** [comment] 2022-10-29 00:38
Haven't had time to dig into this further but will hopefully do so soon! I think we just need to figure out how to get App to be accessible from this page. I *think* it's because it's in the `homepage` directory rather than `site` - and `site` is where the global gets created - so it hasn't actually done so yet. Just a hunch though, haven't confirmed so could be wrong.

**Comment by dangrous** [comment] 2022-11-04 00:35
Should be able to dig into this again tomorrow. TBD on whether or not I can find a solution.

One potential thing to do would just be to duplicate all the logic in https://github.com/Expensify/Web-Expensify/blob/3c2dbb8e310109f8a7fb01e019deb794fd3734d7/site/app/global/app.js#L1182-L1213 into `signin.jsx`. It wouldn't be very clean, but would solve this problem, if we can't figure out the global importing stuff.

**Comment by mvtglobally** [comment] 2022-11-22 20:48
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-11-30 04:57
Issue not reproducible during KI retests. (Second week)

**Comment by dangrous** [comment] 2022-12-01 14:45
I think we can go ahead and close this since it hasn't been reproducible for 2 weeks. Also, working on some modifications in https://github.com/Expensify/Expensify/issues/242600 - so this is mostly irrelevant.

**Closed by dangrous** 2022-12-01 14:45 UTC
Labels: Reviewing, Engineering, FirstPick, Monthly, Improvement, Bug
