### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] Close account offline - Close account is enabled by ENTER and no close account text

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21951] opened 2023-06-30 13:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/19328
## Action Performed:
1. Go to staging.new..expensify.com
2. Go offline
3. Go toSettings > Security > Close account
4. Enter email address
5. Press ENTER on keyboard
5. Reconnect network

## Expected Result:
In Step 5, Close account CTA is disabled and cannot be accessed by keyboard
In Step 6, after reconnecting network, close account message shows up in login screen

## Actual Result:
In Step 5, Close account CTA is disabled but it can be accessed by keyboard
In Step 6, after reconnecting network, close account message does not show up in login screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0e4e2dbd-4eb9-4985-a3ef-05fe5bf30d0c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137e6674165abf18a</li>
        <li>Upwork Job ID: 1676655158891503616</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2023-07-03 12:55
Possibly introduced by [this PR](https://github.com/Expensify/App/pull/19328)?

**Comment by sakluger** [comment] 2023-07-03 19:15
> Possibly introduced by https://github.com/Expensify/App/pull/19328?

Yes, possibly! Otherwise, here is the original issue where we refactored the Close Account page to use a form: https://github.com/Expensify/App/issues/11341.

I'll comment on the recent PR to see if it's a regression.

**Comment by sakluger** [comment] 2023-07-05 18:11
Alright, sounds like there's consensus that we need to audit the behavior across all pages and fix the root cause. Adding the external label.

**Comment by sakluger** [comment] 2023-07-07 21:54
Waiting for proposals.

**Comment by sakluger** [comment] 2023-07-10 20:56
Hey @eVoloshchak - since we haven't gotten any other proposals yet, could you please review the proposal from @hoangzinh to see if that will work here? Thanks!

**Comment by sakluger** [comment] 2023-07-10 20:57
Hey @eVoloshchak - have you had a chance to review the proposals we've gotten so far?

**Comment by sakluger** [comment] 2023-07-12 16:02
@eVoloshchak can you please take a look at the proposals we've gotten so far?

**Comment by eVoloshchak** [comment] 2023-07-13 16:49
I agree with @samh-nl on root cause for this one
> The `FormSubmit` component does not evaluate the prop `enabledWhenOffline` and the current online/offline status when submitting forms

However, I think we should proceed with @hoangzinh's [proposal](https://github.com/Expensify/App/issues/21951#issuecomment-1623883445). All of the other proposals will disable form validation (local front-end validation) when `enabledWhenOffline=false` and you're offline

🎀👀🎀 C+ reviewed!
cc: @sakluger

**Comment by sakluger** [comment] 2023-07-24 23:54
PR was merged and deployed to staging last week, should deploy to prod today or tomorrow.

**Comment by sakluger** [comment] 2023-08-01 05:40
**Summarizing payouts for this issue:**

Contributor: @hoangzinh $1500
Contributor+: @eVoloshchak $1500 (payable after BZ checklist is completed)

Above payments include efficiency bonus 🎉 
Upwork job: https://www.upwork.com/jobs/~0137e6674165abf18a

**Comment by sakluger** [comment] 2023-08-01 16:26
Oh yeah - @eVoloshchak could you please finish the BZ checklist so that your payment can be approved? Thanks!

**Comment by JmillsExpensify** [comment] 2023-08-02 04:33
Not seeing a request for this one yet in NewDot. Let me know if I'm missing something.

**Comment by eVoloshchak** [comment] 2023-08-03 14:42
- The PR that introduced the bug has been identified. Link to the PR: I can't pinpoint the exact PR that caused this. The first PR to use `enabledWhenOffline` prop was https://github.com/Expensify/App/pull/10395, but it's completely unrelated to this and was adding this prop to use in a single specific case. I'd say this is something that wasn't implemented initially, not a regression per se
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think this is necessary, in general, keyboard navigation is out of scope, with the exception of this specific case (confirming something by pressing space/enter)
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No_
While this specific case isn't impactful, the bug was present on all forms throughout the app, so we might want to add a regression test

**Comment by eVoloshchak** [comment] 2023-08-03 14:46
**Regression Test Proposal**

- Go to Settings > Security > Close account
- Disconnect from network
- Enter your default contact method
- While contact method input is still focused, press `ENTER` on keyboard
- Verify that there is no `close account` confirmation modal shown
- Connect back to the network
- While contact method input is focused, press `ENTER` on keyboard
- Verify that `close account` confirmation modal is shown

**Do we agree 👍 or 👎**

**Comment by eVoloshchak** [comment] 2023-08-03 14:48
Requested the payment via NewDot

**Comment by JmillsExpensify** [comment] 2023-08-03 22:08
Reviewed details for @eVoloshchak. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by sakluger** [comment] 2023-08-04 00:11
Created the regression test issue: https://github.com/Expensify/Expensify/issues/305598. We're all set here, thanks everyone!

**Closed by sakluger** 2023-08-04 00:11 UTC
Labels: External, Daily, Monthly, Awaiting Payment, Bug
