### ISSUE TITLE
[$500] DEV: Web - Console error on change Merchant

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26382] opened 2023-08-31 10:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to an chat
2. Click on request money
3. Enter money and request money
3. Go to transaction thread
4. Change the merchant

## Expected Result:
Should not show any console error

## Actual Result:
Console error appears (Failed prop type: Invalid prop `transaction.comment` of type `string` supplied to `MoneyRequestView`, expected `object`.)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.60.1
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/56205b95-58f2-49ec-9f04-df8bd2a3c74e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692851970325269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fa47045940012689</li>
        <li>Upwork Job ID: 1699602545467158528</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-08-31 11:34
Dupe of https://github.com/Expensify/App/issues/24608#issuecomment-1688742711 https://expensify.slack.com/archives/C049HHMV9SM/p1692729074593069

**Comment by JmillsExpensify** [comment] 2023-09-07 01:56
Don't have my dev environment up to date, but agree we should resolve this if it's still happening.

**Comment by JmillsExpensify** [comment] 2023-09-07 01:57
Also removed the `needs reproduction` label to avoid confusion and other contributors can comment if they're seeing the same thing.

**Comment by JmillsExpensify** [comment] 2023-10-16 17:42
Removing the `reviewing` label, given that the associated PR/proposal was never approved.

**Comment by MrMuzyk** [comment] 2023-10-18 11:46
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by MrMuzyk** [comment] 2023-10-19 09:30
@JmillsExpensify 

Hi, I've investigated this issue and I think this issue is on the BE side. Here is my detailed explanation:

After digging a bit more deeper I've discovered that the issue may lead to greater errors than just a warning in a console. It can also lead to app crash in a certain scenario. Here is a bit more complex scenario:
* request money
* click on request to get into it's details
* change description to a number, ie: 1 and then save it
* change merchant and save it
* try to change description again

On web app crashes and on native we won't be able to edit description value as it will be empty when we will try to edit it. See the recordings

https://github.com/Expensify/App/assets/23487612/961e3601-53ef-4ed5-92af-7b7be90b9a4a


https://github.com/Expensify/App/assets/23487612/855c40cb-dc55-4ac0-910a-4aebacd9e803

What I believe is happening is that BE is incorrectly parsing the description to a number because it only consists of numbers. Web is crashing because it is trying to invoke a method available only for strings on a number variable. I haven't confirmed what exactly is happening on native that we get an empty input but my guess is that it is set to type `text` and we're trying to set a number in there so in the end it is just empty. 

To back up my findings I've made a recording showing what is happening and why I suspect that it is a BE issue.

https://github.com/Expensify/App/assets/23487612/0f3ad31e-f149-40f9-8ffd-9890f7be92f3

I've tracked the data sent/received from BE and it seems to me that when we're changing merchant and description has only numbers it somehow gets parsed to a number and then saved to Onyx. It looks like its causing extra re-render as well. I've made a few console logs with comments attached to them so it's clear what is what. The optimistic data we want to set when updating Onyx is correct (comment is a string), data send to API is correct (comment is a string), props changes inside component as optimistic data is set; props is correct (comment is a string), then actual update from BE side happens and its incorrect (comment is a number). Up till the actual request the data is correct on the FE side but once request is processed then Onyx gets updated with incorrect value. 

I think something similar is happening when description is empty and we're changing merchant - when comment is empty it is not being nested properly. It's being set to `comment: ''` instead of `comment: { comment: ''}` . Adding a few screenshots  to showcase this

<img width="1920" alt="Screenshot 2023-10-19 at 11 03 29" src="https://github.com/Expensify/App/assets/23487612/6489a560-5268-41b9-8c34-1d75b73905a0">
<img width="1920" alt="Screenshot 2023-10-19 at 11 03 39" src="https://github.com/Expensify/App/assets/23487612/d87ecbe4-1c57-4b2e-803b-d8e8d81a7afa">
<img width="1920" alt="Screenshot 2023-10-19 at 11 04 14" src="https://github.com/Expensify/App/assets/23487612/9b826a6c-9023-4a47-8d92-1076ce4879c7">

**Comment by JmillsExpensify** [comment] 2023-10-19 15:22
@burczu thoughts on those findings? I'll add an `internal` label if you agree it's BE.

**Comment by burczu** [comment] 2023-10-23 12:45
@JmillsExpensify I agree with what @MrMuzyk wrote - let's add `Internal` label to get confirmation from someone from the BE side.

**Comment by MrMuzyk** [comment] 2023-10-25 10:16
Hey, I’ve started work on some wave6 features that are high-priority and someone else from Callstack will take over this issue

**Comment by barttom** [comment] 2023-10-27 06:11
Hi! I'm Bartek from Callstack and I want to take over this issue, please assign me :)

**Comment by burczu** [comment] 2023-10-31 13:01
Just to inform, I'll be ooo for the next few days and we'll be back on Monday, November 6th.

**Comment by cristipaval** [comment] 2023-11-20 10:46
bump @barttom

**Comment by barttom** [comment] 2023-11-20 12:57
@cristipaval Still waiting from internal developer insights, please check this comment
https://github.com/Expensify/App/issues/26382#issuecomment-1770426023

**Comment by cristipaval** [comment] 2023-11-20 13:00
Ugh! I see. I'll closely look into this one to see what to do on the BE side.

**Comment by JmillsExpensify** [comment] 2023-11-24 17:11
Pending BE

**Comment by JmillsExpensify** [comment] 2023-12-06 04:45
Same as above

**Comment by JmillsExpensify** [comment] 2023-12-13 05:13
Same

**Comment by burczu** [comment] 2023-12-22 13:44
Hey @JmillsExpensify! I'll be OOO till January 6th, and right after that I'm leaving the C+ role and joining Waves. Could you please assign another C+ engineer to handle this issue from now on? Thanks.

**Comment by situchan** [comment] 2023-12-22 15:05
Seems like this is still on hold for backend update.
Btw, I can take over in case C+ is needed

**Comment by cristipaval** [comment] 2024-01-24 23:03
This isn't reproducible anymore.

**Closed by cristipaval** 2024-01-24 23:03 UTC
Labels: Engineering, Monthly, Internal, Overdue, Bug

**Comment by situchan** [comment] 2024-01-25 01:55
Actually, I fixed this in https://github.com/Expensify/App/pull/31872 😄

**Comment by cristipaval** [comment] 2024-01-25 11:30
great, thanks @situchan!

**Comment by situchan** [comment] 2024-01-25 11:35
I volunteered fix without knowing that GH existed already but just based on this [discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1699455885756469?thread_ts=1699358032.439529&cid=C01GTK53T8Q).
If I am eligible for any compensation, much appreciated.

**Comment by cristipaval** [comment] 2024-01-25 11:42
cc'ing @JmillsExpensify as the BZ assigned here for this matter

**Comment by JmillsExpensify** [comment] 2024-03-22 20:44
Payment summary: @situchan $500 for PR review and testing.

**Comment by JmillsExpensify** [comment] 2024-03-22 20:51
Upwork contract sent and paid out.
