### ISSUE TITLE
[$50] "Your data is protected" link is broken

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48031] opened 2024-08-26 20:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.24-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hannojg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724679642375049

## Action Performed:

1. Go to staging.new.expensify.com
2. Initiate Add Business Account flow
3. Click `Your Data Is Secure` link

## Expected Result:
https://community.expensify.com/discussion/5677/deep-dive-how-expensify-protects-your-information/ opens without any issue
## Actual Result:
Link broken and Error 1014 displayed
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c6cd3cee-348f-40d3-985b-85f246a70ea1

![Snip - CNAME Cross-User Banned Cloudflare - Google Chrome](https://github.com/user-attachments/assets/543478a7-e81d-4247-a452-95fb713cbf8f)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194501906e3889a0d</li>
        <li>Upwork Job ID: 1828335152483406949</li>
        <li>Last Price Increase: 2024-08-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by ijmalik** [comment] 2024-08-27 09:46
**_Proposal_**

**Please re-state the problem that we are trying to solve in this issue.**
"Your data is protected" link is not working.


**What is the root cause of that problem?**

Users experience "Error 1014" when attempting to access the "Your data is protected" link https://community.expensify.com/discussion/5677/deep-dive-how-expensify-protects-your-information on "Connect bank account" page.

https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/pages/ReimbursementAccount/BankAccountStep.tsx#L168-L173

 The error persists even when the link is manually pasted into a new browser tab, indicating a problem outside of the our Expensify application.
 
The root cause of "Error 1014" is likely related to a CNAME Cross-User Banned issue on Cloudflare. This error typically occurs when one domain points to another via a CNAME record, and the domains are managed under different Cloudflare accounts. The issue seems to originate from the configuration of the community.expensify.com domain or its Cloudflare settings.

**What changes do you think we should make in order to solve the problem?**

If accessible, check the DNS settings for community.expensify.com within its Cloudflare account. Ensure that the CNAME records are correctly configured and that there are no conflicts with other domains.

If DNS settings cannot be directly modified, contact the administrators responsible for community.expensify.com. Inform them of the "Error 1014" and request that they review the CNAME configurations within their Cloudflare account.

**What alternative solutions did you explore?**

If the issue cannot be resolved on the target domain, consider providing an alternative link for users to access the content.

**Comment by NJ-2020** [comment] 2024-08-27 09:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[$50] "Your data is protected" link is broken
### What is the root cause of that problem?
I think we already migrated from `https://community.expensify.com/discussion/5677/deep-dive-how-expensify-protects-your-information/` to `https://help.expensify.com/`

Because when we open the `https://community.expensify.com` we got redirected to `https://help.expensify.com/`
So we need to update the link from `https://community.expensify.com` to `https://help.expensify.com/`
### What changes do you think we should make in order to solve the problem?
We need to ask Expensify internal for the right article inside the `https://help.expensify.com`

And update the below code:
https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/pages/ReimbursementAccount/BankAccountStep.tsx#L168-L172
### What alternative solutions did you explore? (Optional)

**Comment by NJ-2020** [comment] 2024-08-27 13:36
@fedirjh Ijmalik update the alternative solution like my solution, can you please look at the timestamps
Which he update the alternative solution like my solution after my proposal has been send

**Comment by NJ-2020** [comment] 2024-08-27 13:46
Ok, do you aggree with alternative solution or main changes?

**Comment by NJ-2020** [comment] 2024-08-27 13:52
@fedirjh But as you can see the alternative solution it's almost exact same, the only difference he provide the link:
https://help.expensify.com/articles/new-expensify/settings/Encryption-and-Data-Security

**Comment by NJ-2020** [comment] 2024-08-27 14:08
@fedirjh Yes I've read, but he didn't mention about that earlier

**Comment by NJ-2020** [comment] 2024-08-27 14:18
Ok, Thanks

**Comment by NJ-2020** [comment] 2024-08-27 14:22
Just to make it clear

@ijmalik Add the alternative solution after my proposal has been send, which is almost exactly like me, but he add the link to the article in the proposal

My proposal i do not include the link to the article but i said that we need to ask to Expensify internal team for the article link inside my proposal:
> We need to ask Expensify internal for the right article inside the https://help.expensify.com

cc: @blimpich

**Comment by trjExpensify** [comment] 2024-08-28 00:39
@adelekennedy the community site is being/has been deprecated. For the OP and the expected results, we should include and update in the triage the correct link we expect it to have been replaced by. If you're unsure what that replacement link is, #expensifyhelp would be a good place to ask. 👍

**Comment by blimpich** [comment] 2024-08-29 20:49
@adelekennedy do you know if this would be the correct link to replace this with? https://help.expensify.com/articles/new-expensify/settings/Encryption-and-Data-Security

**Comment by adelekennedy** [comment] 2024-09-03 04:02
That's the correct one @blimpich

**Comment by blimpich** [comment] 2024-09-03 16:39
I agree with @fedirjh. Lets go with @ijmalik's proposal 🙂

**Comment by blimpich** [comment] 2024-09-06 20:52
@ijmalik are you able to raise a PR soon?

**Comment by ijmalik** [comment] 2024-09-07 00:03
< @ijmalik are you able to raise a PR soon?
yes

**Comment by ijmalik** [comment] 2024-09-11 11:44
> 📣 @ijmalik You have been assigned to this job! Please apply to the [Upwork job](https://www.upwork.com/jobs/~0194501906e3889a0d) and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻 Once you apply to this job, your Upwork ID will be stored and you will be automatically hired for future jobs! Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖

Hi @blimpich ,

I have applied for the [Upwork job](https://www.upwork.com/jobs/~0194501906e3889a0d), but it seems my status hasn’t been updated here yet. Please let me know if any further action is required from my side.

**Comment by blimpich** [comment] 2024-09-11 16:14
I don't think you need to do anything else. @adelekennedy are you able to double check that @ijmalik has done all the steps they need to do in order to get paid via Upwork? I believe they have.

**Comment by adelekennedy** [comment] 2024-09-25 16:52
sorry! This totally slipped off my radar - I've hired you in Upwork @ijmalik

**Comment by blimpich** [comment] 2024-09-25 17:03
This was also deployed to production, so @adelekennedy we should be ready to pay out I believe.

**Comment by blimpich** [comment] 2024-09-25 17:05
I'm sorry about this @ijmalik, it looks like some of our automations failed so the payment process for this didn't work as smoothly as it should've. We will make sure to pay you and the C+ who reviewed your work.

**Comment by adelekennedy** [comment] 2024-09-25 17:07
Payouts due:

- [ ] Contributor: $50 @ijmalik (Upwork) offer pending, once you accept I will pay you out!
- [ ] Contributor+: $50 @fedirjh (NewDot)

Upwork job is [here](https://www.upwork.com/ab/applicants/1828335152483406949/offers).

**Comment by ijmalik** [comment] 2024-09-25 19:18
@adelekennedy @blimpich 

Thank you very much for the update. I completely understand, and there's no issue with the delay. I appreciate your efforts in resolving this.

**Closed** 2024-09-26 13:24 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-10-23 10:21
$50 approved for @fedirjh
