### ISSUE TITLE
Workspace - App crashed when creating New room in offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11246] opened 2022-09-23 17:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #10863 
## Action Performed:
1. Log in to any account
2. Create a workspace by clicking the green plus, New workspace (if needed)
3. Go offline
4. Click the green plus then click New room
5. Fill out the new room form as a restricted workspace and click save

## Expected Result:
Verify that you are navigated to the newly created room and you see the "Collaboration starts here" message and everything is grayed out

## Actual Result:
App crashed when try to save new room offline.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Mobile Web - Safari

**Version Number:** 1.2.5.0.

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** applausetester+31622@applause.expensifail.com / Qwerty123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/192025941-f59255c7-8627-491a-95c5-1cf9c5527f5e.mp4
[Bug5746025_New_Expensify-2022-09-23-102958.txt](https://github.com/Expensify/App/files/9636081/Bug5746025_New_Expensify-2022-09-23-102958.txt)

<img src="https://user-images.githubusercontent.com/43996225/192026157-d9cf0294-92f1-4d4c-8aeb-018f1366f217.png" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-09-23 17:57
FWIW I could not repro this on staging.

**Comment by johnmlee101** [comment] 2022-09-23 17:58
I could reproduce this on iOS

**Comment by johnmlee101** [comment] 2022-09-23 17:58
v1.25-0

**Comment by luacmartins** [comment] 2022-09-23 18:03
Oh interesting! I tried the same platform and version and didn't have an issue. 
From the issue description it seems like it's also on prod so I won't block the deploy on it, but please keep investigating!

**Comment by johnmlee101** [comment] 2022-10-04 16:41
Can't reproduce in the latest update, so I think this might be good to close out

**Comment by johnmlee101** [comment] 2022-10-04 17:48
Can you retest to see if this is happening on your side?

**Comment by mvtglobally** [comment] 2022-10-11 13:03
Issue not reproducible during KI retests. (First week)

**Comment by johnmlee101** [comment] 2022-10-11 21:57
Unassigning in the meantime since I don't believe this is happening anymore

**Comment by mvtglobally** [comment] 2022-10-18 11:24
Issue not reproducible during KI retests. (Second week)

**Comment by Christinadobrzyn** [comment] 2022-10-19 02:18
going to send this to eng to see if we need to keep it open. Sounds like it hasn't happened for a few weeks so maybe closing for now?

**Comment by NikkiWines** [comment] 2022-10-20 20:54
The reproduction steps on the OP don't work for the most recent version of NewDot (staging) for me. 

https://user-images.githubusercontent.com/16747822/197055161-29f0f1e4-80d8-42b2-9cac-dc2d7801caf4.MP4

@kavimuru is this still a valid flow? If so, it looks like there would be more steps necessary to reproduce this issue - could you list those out please? If not, doesn't look like this is an issue anymore.

**Comment by kavimuru** [comment] 2022-10-21 00:56
@NikkiWines Is this gmail account? For public domains "New room" option is not available.

**Comment by NikkiWines** [comment] 2022-10-21 11:39
Oh, yes I was using a gmail account. Let me try on a private domain

**Comment by NikkiWines** [comment] 2022-10-21 12:13
I'm unable to reproduce this on iOS staging v1.2.18-4. Closing since QA is also unable to reproduce this. 

https://user-images.githubusercontent.com/16747822/197192951-97342445-4e09-4d86-aae1-5fc671531bad.MP4

**Closed by NikkiWines** 2022-10-21 12:13 UTC
Labels: Engineering, Daily, Bug
