### ISSUE TITLE
[$1000] Web - Send money - Replies are not displayed on send money message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20099] opened 2023-06-02 20:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open the app in another device and login with user B
3. From user B, request money to user A
4. Observe in user A, request money message of user B has 'Replies' and its count displayed
5. From user A, send money to user B
6. From user A, click on send money message, send new message and it and again observe that send money message does not have 'Replies' displayed

## Expected Result:
App should displays 'Replies' on send money messages too as it does on request money messages

## Actual Result:
App does not display 'Replies' on send money messages.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cca730bc-8208-45bc-81dd-0bdf6e799730

https://github.com/Expensify/App/assets/93399543/e9a91b12-0ca9-4dbf-b541-1338aecd34e2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685207535140439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ad41131bcfa9808</li>
        <li>Upwork Job ID: 1666298796414373888</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2023-06-06 06:41
Came in before the long weekend - will catch up on this tomorrow.

**Comment by sophiepintoraetz** [comment] 2023-06-07 04:19
I believe I've been able to reproduce this - I get a notification for the reply, as well as it appearing in the LHN but it does not appear in the sent money request.
![image](https://github.com/Expensify/App/assets/42940078/c4208960-75db-428b-801c-9e8983d115f4)

https://github.com/Expensify/App/assets/42940078/69515c6b-d36a-4221-9867-05b02232ac3c

**Comment by sophiepintoraetz** [comment] 2023-06-08 21:27
Waiting for some proposals! As a heads up - I will be OOO for a week from next Tuesday, so will reassign the Bug label for a co-conspirator. If we have no proposals in the next few days, let's hand over to the external agencies for some eyes!

**Comment by AmjedNazzal** [comment] 2023-06-09 10:41
This seem to be a backend issue, when the api request has a command of "RequestMoney" the response contains childVisibleActionCount which is used to show replies, but when the command is "SendMoneyElsewhere" the response does not contain that.

<img width="1280" alt="requestMoney" src="https://github.com/Expensify/App/assets/74202751/bc4f6825-c2bd-4845-9e12-0d062eafe124">

<img width="1280" alt="sendMoney" src="https://github.com/Expensify/App/assets/74202751/4d22e02d-8ecd-4398-843b-94e4b8e63403">

**Comment by sophiepintoraetz** [comment] 2023-06-12 09:51
@yuwenmemon - can you confirm @AmjedNazzal's backend theory? If so, then this needs to be an internal issue, right?

**Comment by sophiepintoraetz** [comment] 2023-06-12 09:54
@michaelhaxhiu - thank you 🙏 I'm headed OOO until 20 June, we're just waiting on Yuwen to confirm whether this issue is going to be internal or not. If it is, likely the only payment needed is for the reporter (upwork job is still [open](https://github.com/Expensify/App/issues/20099)).

**Comment by yuwenmemon** [comment] 2023-06-12 17:07
Looks to be the case that this is internal.. Thanks @AmjedNazzal!

**Comment by michaelhaxhiu** [comment] 2023-06-15 00:36
Just affirmed it's internal, let's give yuwen a few days to get into this.

**Comment by sophiepintoraetz** [comment] 2023-06-21 05:24
@yuwenmemon - when are you able to take a look into this? (thanks Hax for babysitting!)

**Comment by yuwenmemon** [comment] 2023-06-21 16:33
It's on my to-do list for today!

**Comment by sophiepintoraetz** [comment] 2023-06-25 22:40
@yuwenmemon - I think this is on you here - let me know if there's something else I can take off your plate so you can get to this?

**Comment by yuwenmemon** [comment] 2023-06-27 05:09
Okay @luacmartins or @cristipaval I'm not sure how to best proceed here but after digging in a bit it seems like we're not sending a `reportPreviewReportActionID` with our sendMoney API calls - is that on purpose?

https://github.com/Expensify/App/blob/217059fab24b3d2d8c748211198e266c635f72a4/src/libs/actions/IOU.js#L1074-L1082

Should we be sending that, similar to what we do for [RequestMoney](https://github.com/Expensify/App/blob/217059fab24b3d2d8c748211198e266c635f72a4/src/libs/actions/IOU.js#L425) and [SplitBill](https://github.com/Expensify/App/blob/217059fab24b3d2d8c748211198e266c635f72a4/src/libs/actions/IOU.js#L683)?

**Comment by cristipaval** [comment] 2023-06-27 14:21
Hey @yuwenmemon! This is because report previews are not optimistically created for send/pay flows. This is the [GH issue](https://github.com/Expensify/App/issues/19119) for it, I'm making [this PR](https://github.com/Expensify/App/pull/21578) ready soon and it will fix this issue.

FYI: I think we're not accepting the bug reports related to sending money anyway. See [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1687388507073569) Slack announcement.

**Comment by yuwenmemon** [comment] 2023-06-27 23:00
Cool! Will close this in favor of that issue then. Thanks @cristipaval!

**Closed by yuwenmemon** 2023-06-27 23:00 UTC
Labels: Engineering, Daily, Internal, Bug
