### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] Add deep links for CTA links

### ISSUE THREAD

**Issue by marcochavezf** [Expensify/App#45350] opened 2024-07-12 17:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

We want to add a couple of deep links for the following actions, where each link will open the corresponding views:

| Action          | Link                | View |
|-----------------|---------------------|------|
| Track Expense   | `/track-expense`    | <img width="830" alt="Screenshot 2024-07-12 at 11 30 51 a m" src="https://github.com/user-attachments/assets/2f1439c2-ec88-43c2-84f2-919cab5ce37c"> |
| Submit Expense  | `/submit-expense`   | <img width="830" alt="Screenshot 2024-07-12 at 11 31 51 a m" src="https://github.com/user-attachments/assets/88e6f520-7635-48cd-81fa-ada28dd99a61"> |

Potentially, we'd want to create something like a `/concierge` deep link, where we create a component that navigates to the Concierge chat. In this case, we would start the corresponding money request action using `IOU.startMoneyRequest`.

- 

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01967a3704af99de82</li>
        <li>Upwork Job ID: 1811816585616897261</li>
        <li>Last Price Increase: 2024-07-12</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103142789</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by marcochavezf** [comment] 2024-07-12 17:37
This issue is frontend implementation for Harpoons for NewDot, specifically for this [internal issue](https://github.com/Expensify/Expensify/issues/402919).

**Comment by dannymcclain** [comment] 2024-07-12 17:48
Looks like nothing in the UI is actually changing for this right? I probably don't need to be assigned since this "new feature" basically has nothing to do with design—but I will wait for confirmation!

**Comment by nkdengineer** [comment] 2024-07-12 17:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add deep links for CTA links

### What is the root cause of that problem?
This is a new feature

### What changes do you think we should make in order to solve the problem?
We can use the same implementation as we do on the concierge page. For each track-expense and submit expense create a navigation page with the corresponding route
 . This page will be a RHP and we can display a loading page while waiting for the navigation or something like this (this can be confirmed by design team)


And then on this page create a `useEffect` to navigate to the money request flow by using `IOU.startMoneyRequest`

Here is an example for track-expense page

```
function TrackExpensePage({session}: TrackExpenseProps) {
    const styles = useThemeStyles();
    const isUnmounted = useRef(false);

    useFocusEffect(() => {
        if (session && 'authToken' in session) {
            App.confirmReadyToOpenApp();
            Navigation.isNavigationReady().then(() => {
                if (isUnmounted.current) {
                    return;
                }
                IOU.startMoneyRequest(CONST.IOU.TYPE.TRACK, ReportUtils.generateReportID())
            });
        } else {
            Navigation.navigate();
        }
    });

    useEffect(
        () => () => {
            isUnmounted.current = true;
        },
        [],
    );

    return (
        <FullScreenLoadingIndicator />;
    );
}
```
### What alternative solutions did you explore? (Optional)

**Comment by kabeer95** [comment] 2024-07-12 19:03
Proposal: Add Deep Links for CTA Links on Expensify

Problem Statement:

Currently, the Call-to-Action (CTA) links on Expensify do not utilize deep linking, which can lead to a poor user experience and decreased conversion rates. Deep linking allows users to be directed to a specific page or section within the app, rather than the app's homepage, providing a more seamless and efficient experience.

Goals:

Improve the user experience by directing users to the intended page or section within the app.
Increase conversion rates by reducing the number of steps required to complete a task.
Enhance the overall usability of Expensify's CTAs.
Proposed Solution:

To resolve this issue, we recommend implementing deep linking for CTA links on Expensify. This can be achieved by:

Updating the link structure: Modify the CTA links to include a unique identifier or parameter that specifies the intended page or section within the app.
Implementing a deep linking framework: Utilize a deep linking framework such as React Navigation and Expo Linking to handle the routing and navigation within the app.
Configuring the app's routing: Update the app's routing configuration to recognize and handle the deep links, directing users to the intended page or section.
Code Implementation:

To implement deep linking, we will use Expo Linking and React Navigation. Here is an example of how the code can be implemented:


{
  "expo": {
   ...
    "linking": {
      "scheme": "expensify",
      "config": {
        "screens": {
          "SubmitExpense": "submit-expense"
        }
      }
    }
  }
}
DeepLinking.ts

typescript


import { Linking } from 'expo';
import { NavigationContainer } from '@react-navigation/native';

const linking = {
  prefixes: ['expensify://'],
  config: {
    screens: {
      SubmitExpense: {
        path: 'submit-expense',
      },
    },
  },
};

const DeepLinking = () => {
  const navigation = useNavigation();

  const handleDeepLink = (event: Linking.EventType) => {
    const url = event.nativeEvent.url;
    const route = linking.config.screens[url.split('/').pop()];

    if (route) {
      navigation.navigate(route);
    }
  };

  useEffect(() => {
    Linking.addEventListener('url', handleDeepLink);
    return () => {
      Linking.removeEventListener('url', handleDeepLink);
    };
  }, []);

  return null;
};

export default DeepLinking;
App.tsx

typescript

import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import DeepLinking from './DeepLinking';

const Stack = createStackNavigator();

const App = () => {
  return (
    <NavigationContainer>
      <DeepLinking />
      <Stack.Navigator>
        <Stack.Screen name="SubmitExpense" component={SubmitExpenseScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

export default App;
CTA Link Update

jsx

<a href="expensify://submit-expense">Submit Expense</a>
GitHub Issue:

We propose creating a new issue on Expensify's GitHub repository to track the progress of this feature. The issue can be titled "Add Deep Links for CTA Links on Expensify" and include the following labels: feature, ux, and deep-linking.


Alternative Solutions:

We also considered the following alternative solutions:

Using URL schemes: Utilize URL schemes such as expensify:// to direct users to the app, rather than the app's homepage.
Implementing a custom routing solution: Develop a custom routing solution using React Router or a similar library to handle the deep linking.
Please let us know if you would like to discuss this proposal further or proceed with implementation.

**Comment by kabeer95** [comment] 2024-07-12 19:30
Proposal: Add Deep Links for CTA Links on Expensify

Problem Statement:

The current implementation of CTA links on Expensify does not provide deep links, resulting in a poor user experience. Users are not able to navigate directly to the relevant section of the report.

Root Cause:

The lack of deep links in the CTA links is due to the absence of a proper linking mechanism.

Proposed Solution:

To resolve this issue, we recommend adding deep links to the CTA links on Expensify. This can be achieved by:

Modifying the CTA link generation: Update the CTA link generation logic to include deep links that point to the relevant section of the report.
Using anchor tags: Utilize anchor tags (<a href="#section-id">) to create deep links that navigate to the desired section of the report.

 Code:
 import React from 'react';

interface CTALinkProps {
  reportId: string;
  sectionId: string;
  children: React.ReactNode;
}

const CTALink: React.FC<CTALinkProps> = ({ reportId, sectionId, children }) => {
  const href = `#${sectionId}`;

  return (
    <a href={href} onClick={() => console.log(`Navigate to ${sectionId} section`)}>
      {children}
    </a>
  );
};

export default CTALink;

const Report = () => {
  return (
    <div>
      <h2>Report</h2>
      <CTALink reportId="report-1" sectionId="expenses">View Expenses</CTALink>
      <CTALink reportId="report-1" sectionId="income">View Income</CTALink>
      
    </div>
  );
};

export default Report;


export default CtaLink;
Alternative Solutions:

We explored the following alternative solutions:

Using a URL parameter: Pass the section ID as a URL parameter, allowing the report to navigate to the desired section.
Implementing a custom linking mechanism: Develop a custom linking mechanism that uses a unique identifier to navigate to the relevant section of the report.

**Comment by ikevin127** [comment] 2024-07-13 19:07
@nkdengineer Thanks for your proposal.

I implementing the solution you proposed locally for testing purposes and while the redirect part works, when submitting the track expense -> the API call fails (responding with `Auth TrackExpense returned an error`), and the track expense is not created, an empty avatar report appears in LHN which goes away after dismissing the errors.

Additionally, your `TrackExpensePage` provided code would keep the central pane loading indefinitely, so I had to remove the following block:

```ts
if (isUnmounted.current) {
    return;
}
```
in order to get the redirect working and open the routed RHP.

##

In order for me to move on with assignment here I need proof of **at least one** of the deep link routes working as expected, functionality wise as well - meaning the whole track expense flow working as it would when triggered from the FAB button.

**Comment by ikevin127** [comment] 2024-07-13 19:09
@kabeer95 Thanks for your proposal. To be reviewed by Contributor+, please update your proposal comment using the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md).

**Comment by nkdengineer** [comment] 2024-07-14 03:27
@ikevin127 I created a test branch [here](https://github.com/nkdengineer/App/tree/fix/45350).

**Comment by nkdengineer** [comment] 2024-07-14 03:30
> I implementing the solution you proposed locally for testing purposes and while the redirect part works, when submitting the track expense -> the API call fails (responding with Auth TrackExpense returned an error), and the track expense is not created, an empty avatar report appears in LHN which goes away after dismissing the errors.


For track-expense we should find the self DM instead of generating a new reportID because only selft can create track-expense. I updated proposal https://github.com/Expensify/App/issues/45350#issuecomment-2226093175.

**Comment by marcochavezf** [comment] 2024-07-15 16:08
> Looks like nothing in the UI is actually changing for this right? I probably don't need to be assigned since this "new feature" basically has nothing to do with design—but I will wait for confirmation!

Yup, no UI changes are needed for this one, I will unassign you :)

**Comment by ikevin127** [comment] 2024-07-15 20:59
@nkdengineer Thanks for the proposal update. Unfortunately the test branch implementation still does not work as expected, what I mean by this is that while submitting the track expense works now, there's a weird flicker when the RHP opens and the central pane report seems to load indefinitely.

<details>
<summary>Video</summary>

https://github.com/user-attachments/assets/ed9c9249-274e-48b6-b326-23ac78ada0e9

</details>

**Note:** I tested your branch with both `CONFIG.USE_REACT_STRICT_MODE` true and false and got the same behaviour.

**Comment by ikevin127** [comment] 2024-07-15 20:59
@nyomanjyotisa's updated [proposal](https://github.com/Expensify/App/issues/45350#issuecomment-2227161967) looks good enough to me in order to move on with assignment, given that this is a `NewFeature` I think the details can be worked on during PR. The proposed solution addresses the issue accordingly and I appreciate the attention to detail like:
- displaying `track-training` when the `track-expense` deep link route is accessed and the conditions are met
- considering the anonymous user behaviour

<details>
<summary>Video</summary>

https://github.com/user-attachments/assets/9aa917f5-e9d2-4961-b9e2-95ef0d3732c5

</details>

**One issue I found with the solution**: on `/submit-expense`, the submission flow fails with error message `There is a previously existing chat between these users.` (see video above).

**Regarding solution code**:
- no need to create `getSelfDMReportID`, just use existing `findSelfDMReportID` like [here](https://github.com/Expensify/App/blob/26541aca06c3e96a3618e758fe3c990b5ece850c/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L374-L382) (same for `/submit-expense`, model after existing code)
- ^ similarly to the referenced code above, you can use `interceptAnonymousUser` to handle flow for non-logged-in users
- when you create the pages, instead of using [deprecated](https://github.com/Expensify/react-native-onyx?tab=readme-ov-file#deprecated-note) `withOnyx`HOC, use `useOnyx` hook instead as shown [here](https://github.com/nkdengineer/App/blob/0784160bf792367bdbfac4d913bce37f2040876a/src/pages/TrackExpensePage.tsx)

**Note:** Because of `CONFIG.USE_REACT_STRICT_MODE` being true, [this](https://github.com/nyomanjyotisa/Expensify/blob/ab17e03926be3d77f0c3538e65a76c79ff982927/src/pages/TrackExpensePage.tsx#L54-L59) block of code will always have `isUnmounted` as true because of the double rendering `StrictMode` does, so for local development while working on the feature you can set `CONFIG.USE_REACT_STRICT_MODE` to false (just make sure to set it back before pushing the code to PR).


🎀👀🎀 C+ reviewed

**Comment by marcochavezf** [comment] 2024-07-16 16:16
Nice, thanks for the review @ikevin127! Assigning @nyomanjyotisa 🚀

**Comment by trjExpensify** [comment] 2024-07-19 11:18
This is harpoon project related, right? Moving to #vip-vsb

**Comment by marcochavezf** [comment] 2024-07-19 17:11
Not overdue, moved to #vip-vsb

**Comment by marcochavezf** [comment] 2024-07-22 16:13
Hi @nyomanjyotisa, is the still happening?

**Comment by ikevin127** [comment] 2024-07-23 07:19
@nyomanjyotisa That's fine - you can safely open the PR  if that's the only issue - as it's expected to get the Not Found page when using ngrok and this happens regardless of your changes, happens to everybody that uses tunneling - including on adhoc build since we're not using the dev / staging / prod domains when we tunnel.

To test this without ngrok (on iOS only) you can setup the iPhone Simulator by running `npm run setupNewDotWebForEmulators` and once this is successful on iOS you will be able to connect to web on Simulator using `https://dev.new.expensify.com:8082` directly in the simulator.

**Comment by dylanexpensify** [comment] 2024-07-23 14:18
Ongoing

**Comment by dylanexpensify** [comment] 2024-07-24 08:16
@marcochavezf mind giving us a quick update when you have a free moment 🙇‍♂️ ❤️

**Comment by ikevin127** [comment] 2024-07-24 19:38
@marcochavezf I think it's safe to move forward with the PR review despite [this](https://github.com/Expensify/App/issues/45350#:~:text=One%20issue%20I%20found%20with%20the%20solution%3A%20on%20/submit%2Dexpense%2C%20the%20submission%20flow%20fails%20with%20error%20message%20There%20is%20a%20previously%20existing%20chat%20between%20these%20users.%20(see%20video%20above).,-Regarding%20solution%20code) issue mentioned in https://github.com/Expensify/App/issues/45350#issuecomment-2247282205 (above) as to me this seems like a BE issue as the error message details - issue which is already happening currently via the FAB submit expense flow, therefore I think it's out of scope for this issue and should be fixed for both FAB / deep link flows once addressed in another issue.

**What do you think ?**

**Comment by marcochavezf** [comment] 2024-07-29 15:52
> @marcochavezf mind giving us a quick update when you have a free moment 🙇‍♂️ ❤️

Apologies for the delay here. The PR has been merged!

**Comment by ikevin127** [comment] 2024-08-01 02:49
# Regression Test Proposal

**A. Track expense deep link**

1. Once logged-in, append `/track-expense` after the expensify domain (e.g. `https://staging.new.expensify.com`).
2. Verify that the **Track Training** is displayed if the conditions match (first time Tracking an expense / never clicked **Don't show me this again** on Track Training before).
3. Click **Got It**.
4. Verify that the Track Expense page is displayed.
5. Enter amount on manual track expense.
6. Click **Next**.
7. Click **Track Expense**.
8. Verify that the Track Expense request is created successfully and the Track Expense related Concierge whisper is displayed.

**B. Submit expense deep link**

1. Once logged-in, append `/submit-expense` after the expensify domain (e.g. `https://staging.new.expensify.com`).
4. Verify that the Submit Expense page is displayed.
5. Enter amount on manual submit expense.
6. Click **Next**.
7. Select any user or workspace.
8. (Optional) Enter Merchant (for workspace).
8. Click **Submit**.
9. Verify that the Submit Expense request is created successfully.


Do we agree 👍 or 👎.

**Comment by dylanexpensify** [comment] 2024-08-05 12:27
Payment coming up!

**Comment by ikevin127** [comment] 2024-08-07 19:39
cc @dylanexpensify

**Comment by dylanexpensify** [comment] 2024-08-08 08:57
Payment summary:
- Contributor: @nyomanjyotisa $250
- Contributor+: @ikevin127 $250

Please apply or request!

**Comment by dylanexpensify** [comment] 2024-08-08 09:00
@ikevin127 payment sent, @nyomanjyotisa offer sent!

**Comment by dylanexpensify** [comment] 2024-08-08 09:07
Done!

**Closed by dylanexpensify** 2024-08-08 09:07 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
