### ISSUE TITLE
[HOLD for payment 2023-09-15] [$1000] Android - Request money - Different app behavior when asking for camera permission in Scan receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24160] opened 2023-08-04 13:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Tap + button > Add attachments > Take photo
4. Return to LHN
5. Click + button > Request Money > Scan
6. Tap on the capture button

## Expected Result:
The app should ask for camera permission the same way it asks for permission when adding attachments by taking photo

## Actual Result:
In Step 3, the app asks for camera permission via pop-up
In Step 6, the app shows error message when tapping on the capture button. User is required to go to app settings to manually allow camera permission via Give permission CTA

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c736b9ac-a2bc-42f9-8739-633a970fe60d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142d61bc15de5a06b</li>
        <li>Upwork Job ID: 1687482269732622336</li>
        <li>Last Price Increase: 2023-08-24</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26331513</li>
</ul></li>
    </ul>
</details>

**Comment by mananjadhav** [comment] 2023-08-10 04:15
@AndrewGable Been more than a few days since we've added an update. But curious, any specific reason we didn't set this External?

**Comment by AndrewGable** [comment] 2023-08-10 15:29
It's a weekly issue so you can expect an update once a week. I introduced the bug so I want to fix it.

**Comment by mananjadhav** [comment] 2023-08-10 16:54
thanks for the comment.

**Comment by AndrewGable** [comment] 2023-08-21 20:58
Looking into if we can handle this via vision camera or not.

**Comment by AndrewGable** [comment] 2023-08-24 19:52
Apologies, I am going to go on OOO this next week so I will make this external. @hungvu193's proposal looks on track, but I would also double check we cannot do this directly with vision camera. Feel free to re-assign if we need to move this forward once we get a proposal @tjferriss!

**Comment by b4s36t4** [comment] 2023-08-24 20:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Request money - Different app behavior when asking for camera permission in Scan receipt
### What is the root cause of that problem?
We already have the flow where we request the user to allow permission for camera but it's not showing because of the the following reason.

If we observe the flow carefully, first we've tried to open the camera in which we've declined the request.

> If the user has previously blocked the app from using the camera, the alert will not be shown and "denied" will be returned.

As per the above comment (from react-native-vision-camera) we're getting the permissionStatus for the camera as `denied` but the flow we're checking is only for `not-determined`
https://github.com/Expensify/App/blob/74be5f627511410373f926c76e50f98c459e93e5/src/pages/iou/ReceiptSelector/index.native.js#L154

### What changes do you think we should make in order to solve the problem?

We need to add a check for `denied` status as well which will trigger the `requestCameraPermission` and the flow would be normal.
### What alternative solutions did you explore? (Optional)
NA

**Comment by b4s36t4** [comment] 2023-08-24 21:06
@AndrewGable can you review my proposal??

**Comment by AndrewGable** [comment] 2023-08-24 21:23
@mananjadhav will be reviewing the proposals 👍

**Comment by mananjadhav** [comment] 2023-08-25 18:43
Thanks for the detailed proposals. I agree if we don't handle the permissions properly it could crash the app or make it unresponsive. 

I liked @tienifr's proposal. I just want to ensure we don't break any Camera flow. I also checked for `react-native-vision-camera`'s issues and there are 1-2 I could find for camera permissions, but none of them been address for more than a year.

I think using `react-native-permissions` is a better choice.

cc - @AndrewGable 

🎀 👀 🎀 C+ reviewed.

**Comment by tgolen** [comment] 2023-08-25 18:57
I also like that proposal, including the change to copy for scenario 2

**Comment by tgolen** [comment] 2023-08-28 15:31
This has been assigned and is waiting for a PR.

**Comment by mananjadhav** [comment] 2023-08-29 04:58
@tienifr Quick bump on the PR for this one.

**Comment by mananjadhav** [comment] 2023-09-04 16:25
@AndrewGable This has been waiting on quite a few days. Considering this is related to Scan receipt and permissions, I think we should prioritize this one?

**Comment by tjferriss** [comment] 2023-09-11 22:46
I'm not sure why the checklist didn't show up here. @mananjadhav can you please get started on this?

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] @mananjadhav The PR that introduced the bug has been identified. Link to the PR:
- [ ] @mananjadhav The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] @mananjadhav A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] @mananjadhav Determine if we should create a regression test for this bug.
- [ ] @mananjadhav If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
- [ ] @mananjadhav Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by tjferriss** [comment] 2023-09-16 22:20
@tienifr has been paid via Upworks. @mananjadhav can you please get started on the checklist?

**Comment by mananjadhav** [comment] 2023-09-17 17:10
@tjferriss Can you please post a payment summary so that I can raise the payment request?

This was introduced when we added the component in this [PR](https://github.com/Expensify/App/pull/23046). This was a large PR and I think it was easy to miss the permissions. 

I don't think we need any regression test here.

**Comment by tgolen** [comment] 2023-09-21 02:23
Bump @tjferriss

**Comment by mananjadhav** [comment] 2023-09-21 04:08
I also believe this is eligible for the timeline bonus? This was waiting for merge freeze but the C+ checklist was completed within the timeline.

**Comment by tjferriss** [comment] 2023-09-25 05:57
I'm not sure it fits the timeline bonus, even with the feature freeze consideration. I see @tienifr was assigned on 8/26 and then I see your [reviewer checklist comment](https://github.com/Expensify/App/pull/26231#issuecomment-1701531128) on 9/1. 

**Payment Summary:**

Reporter: NA
Contributor: @tienifr $1000
Contributor+: @mananjadhav $1000

**Comment by mananjadhav** [comment] 2023-09-25 16:56
You're right @tjferriss. I don't know why I thought this was eligible. I just verified the assignment was on 8/26. Thanks for clarifying.

**Comment by tjferriss** [comment] 2023-09-26 07:27
@mananjadhav have you raised the payment request?

**Comment by mananjadhav** [comment] 2023-09-26 07:29
Yes @tjferriss I've done that.

**Comment by JmillsExpensify** [comment] 2023-09-28 00:29
$1,000 payment approved for @mananjadhav based on BZ summary.

**Comment by tgolen** [comment] 2023-09-29 04:14
Just waiting for payouts it looks like

**Comment by mananjadhav** [comment] 2023-10-02 14:16
@tjferriss @tienifr can you confirm if the payout is done here?

**Comment by mananjadhav** [comment] 2023-10-02 16:20
@tjferriss @AndrewGable @tgolen I think we can close this one.

**Comment by tgolen** [comment] 2023-10-02 16:31
OK, I'll go ahead and close it out.

**Closed by tgolen** 2023-10-02 16:31 UTC
Labels: External, Engineering, Daily, Awaiting Payment
