### ISSUE TITLE
[HOLD for payment 2024-04-03] [PAY MARCH 27][$500] mweb - Distance - App opens Scan tab when dragging map to the right

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36508] opened 2024-02-14 15:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4312540
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com on mweb.
2. Go to FAB > Request money > Distance.
3. Drag the map to the right.
4. Repeat Step 2 and 3 on Android app.

## Expected Result:
Mag is dragged and app will not open Scan tab.

## Actual Result:
App opens Scan tab when attempting to drag map to the right.
On Android app, app does not open Scan tab when dragging map to the right.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3b9cbefa-0b2f-423e-be38-9a2ca6a5fbb2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c070998a0d47da2</li>
        <li>Upwork Job ID: 1757783384527659008</li>
        <li>Last Price Increase: 2024-02-21</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
<li>aswin-s | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-14 15:07
We think that this bug might be related #wave5-free-submitters
CC @dylanexpensify

**Comment by aswin-s** [comment] 2024-02-15 00:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Swiping to the right on the map view on  the Distance tab switches the tab on Android mobile web browser.

### What is the root cause of that problem?

This seems to be a regression from https://github.com/Expensify/App/pull/27491. In the PR we switched from `onStartShouldSetPanResponder` to `onMoveShouldSetPanResponder` for intercepting swipe events inside MapView.

But on Android mWeb just responding to onMove gesture doesn't seem to be preventing the event from bubbling up and activating the Tab Navigator.

### What changes do you think we should make in order to solve the problem?

Revert to `onStartShouldSetPanResponder` event for handling gesture. This change doesn't seem to cause the original issue https://github.com/Expensify/App/issues/26761 where the attribution icon is not tappable. So the root cause might have been something different. 

https://github.com/Expensify/App/blob/0381d57ab7a127371cdea766e118ce0290be1eaf/src/components/SwipeInterceptPanResponder.tsx#L4

```tsx
const SwipeInterceptPanResponder = PanResponder.create({
    // Revert to onStart event
    onStartShouldSetPanResponderCapture: () => true,
    onPanResponderTerminationRequest: () => false,
});
```
This ensures that TouchMove doesn't trigger Tab change on Android mWeb

### What alternative solutions did you explore? (Optional)

None

**Comment by situchan** [comment] 2024-02-19 15:38
@aswin-s thanks or the proposal.

> This seems to be a regression from https://github.com/Expensify/App/pull/27491

You mean that this won't be reproducible if that PR is reverted?

**Comment by aswin-s** [comment] 2024-02-19 15:55
@situchan Earlier behaviour was that permission request will not be triggered until user taps on the 'Continue' button on permission message. With above PR we are triggering the permission request on screen lod itself.

**Comment by aswin-s** [comment] 2024-02-19 16:03
Also this behaviour was chosen because it aligned with the experience on Web. More details on the links below.

https://github.com/Expensify/App/issues/34750#issuecomment-1910964516
https://expensify.slack.com/archives/C01GTK53T8Q/p1706132155733569

**Comment by aswin-s** [comment] 2024-02-21 16:04
@situchan Yes, the bug should be resolved if we revert the PR. However there seems to be some refactor around handlers after the original PR

**Comment by slafortune** [comment] 2024-02-21 16:25
@situchan do you have a suggestion on the best option to move this forward?

**Comment by situchan** [comment] 2024-02-26 16:47
checking

**Comment by situchan** [comment] 2024-02-28 13:41
Confirmed reverting logic on https://github.com/Expensify/App/pull/27491 fix this issue and not re-introduce https://github.com/Expensify/App/issues/26761.
@aswin-s's [proposal](https://github.com/Expensify/App/issues/36508#issuecomment-1945099030) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by slafortune** [comment] 2024-03-13 15:09
Looks like PR is still in need of review @situchan

**Comment by slafortune** [comment] 2024-04-02 17:51
@situchan @hayata-suenaga will this need a regression test?

@situchan can you complete the checklist when you get a chance?  TIA!

**Comment by hayata-suenaga** [comment] 2024-04-03 16:14
I don't think we need a permanent regression test for this. @situchan, what do you think?

**Comment by slafortune** [comment] 2024-04-04 14:40
@aswin-s requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor) - PAID
@situchan requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Reviewer) - please complete the checklist when you get a chance.

**Comment by slafortune** [comment] 2024-04-15 14:35
I'll be out of office until 4/22 and will check on this once I'm back - moving to weekly.

**Comment by slafortune** [comment] 2024-04-24 13:31
Paid @situchan 
I'm going to lean on @hayata-suenaga [suggestion](https://github.com/Expensify/App/issues/36508#issuecomment-2035030781) and assume no regression test is needed.

**Closed by slafortune** 2024-04-24 13:31 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug
