### ISSUE TITLE
[HOLD for payment 2023-11-17] Login - Chat loads infinitely after logging in unless user opens another chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30934] opened 2023-11-07 00:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Log in with an existing account with chats.

## Expected Result:
Chat loads without issue after login.

## Actual Result:
Chat loads infinitely until user opens another chat.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/dea88529-11b9-4f68-88ea-2e985d37793f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment] 2023-11-07 22:19
I'm taking a look into this one

**Comment by tgolen** [comment] 2023-11-07 23:09
This is being discussed here: https://expensify.slack.com/archives/C035J5C9FAP/p1699374131021109

**Comment by tgolen** [comment] 2023-11-08 00:10
I've confirmed that https://github.com/Expensify/react-native-onyx/pull/412 is the cause of the problems. I'd like to see if I can find a fix for it without needing to revert, though I know that's going to delay the deploy.

**Comment by tgolen** [comment] 2023-11-08 16:05
Getting this reviewed and merged today. Once the Onyx PR is merged, I need to create an App PR to bump the Onyx version. I think I'll create a draft PR for that now so that it'll be ready.

**Comment by getusha** [comment] 2023-11-28 12:54
@tgolen could you please add the `Bug` label to assign BZ for C+ payment?

**Comment by tgolen** [comment] 2023-11-28 15:40
@laurenreidexpensify Could you please help with payments on this one? @getusha needs to be paid for a [C+ review on the PR](https://github.com/Expensify/App/pull/31066#issuecomment-1802381018).

**Comment by laurenreidexpensify** [comment] 2023-11-30 10:17
Payment Summary:

- C+ Review @getusha $500, offer sent in Upwork

**Comment by getusha** [comment] 2023-11-30 10:53
@laurenreidexpensify accepted!

**Comment by laurenreidexpensify** [comment] 2023-11-30 11:12
Payment Summary:

C+ Review @getusha $500, payment issued in Upwork

**Closed by laurenreidexpensify** 2023-11-30 11:12 UTC
Labels: Reviewing, Engineering, Daily, Awaiting Payment, Bug
