### ISSUE TITLE
[$250] Changing "Purchase bill date" clears "Purchase bill status" Authorised value

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#42317] opened 2024-05-16 19:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #[41583](https://github.com/Expensify/App/pull/41583)
**Version Number:** 1.4.74-2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace
3. Enable accounting from the Workspace settings
4. Connect to Xero
5. Navigate to Workspace settings - Accounting - Export - Purchase bill date
6. Change it to a different value
7. Log out
8. Log in with the same account
9. Navigate to Workspace settings - Accounting - Expor

## Expected Result:
The value shouldn't clear.

## Actual Result:
Changing "Purchase bill date" clears "Purchase bill status" Authorised value. I'm unable to set any value for the field.
NOTE : We are not sure it is intended
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/a0532805-e02d-41cd-9469-d71e430afd2f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011cccc97f51a7d2bb</li>
        <li>Upwork Job ID: 1793075720142639104</li>
        <li>Last Price Increase: 2024-05-22</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2024-05-22 00:25
Adding to #wave-collect as this is a Xero bug

**Comment by getusha** [comment] 2024-05-24 10:22
Trying to reproduce the issue

**Comment by getusha** [comment] 2024-05-24 16:01
🎀 👀 🎀

**Comment by getusha** [comment] 2024-05-24 16:02
@luacmartins could you please check if this is something we can fix on the BE? thanks! https://github.com/Expensify/App/issues/42317#issuecomment-2123740638

**Comment by luacmartins** [comment] 2024-05-27 16:04
Yea, this seems like internal work cc @lakchote

**Comment by greg-schroeder** [comment] 2024-05-28 19:18
This is internal, no update just yet - @lakchote are you across this?

**Comment by greg-schroeder** [comment] 2024-05-28 19:22
Go away Melvin

**Comment by lakchote** [comment] 2024-05-29 11:38
@greg-schroeder @luacmartins @kavimuru @getusha not a bug, and no BE fix needed.

Testing needed to be done on the ad hoc build, since there was the merge freeze.

You can test it out here: https://42340.pr-testing.expensify.com/ ([PR](https://github.com/Expensify/App/pull/42340))

I've tested it there, and the value for `Purchase bill status` doesn't clear out, and we can choose different values for it.

**Comment by luacmartins** [comment] 2024-05-29 14:00
Nice, so can we just close this issue then?

**Comment by lakchote** [comment] 2024-05-30 07:29
> Nice, so can we just close this issue then?

Yes, I'm closing it

**Closed by lakchote** 2024-05-30 07:29 UTC
Labels: Daily, Internal, Bug
