### ISSUE TITLE
Error doesn't appear in unheld action

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46551] opened 2024-07-31 01:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722240179636459

## Action Performed:
1. As submitter, create 2 expenses in WS chat and submit the report
2. As approver, hold an expense
3. As submitter, open the held expense and unhold this expense
4. Notice the error appears
## Expected Result:
Error appears in unheld action
## Actual Result:
Error appears at the receipt section
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/47486df5-eefe-4b8a-a8e5-bd7678c51666

![Full Screen #7](https://github.com/user-attachments/assets/5dd6b412-1c0e-43a4-a55e-2619555186e2)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2024-07-31 02:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error for unhold appears below the receipt title instead of the unhold message.

### What is the root cause of that problem?
When the unhold request fails, we set the error to the transaction data.
https://github.com/Expensify/App/blob/eced1703e3b2ca1d7374b583fbc0a82b68381f85/src/libs/actions/IOU.ts#L7565-L7573

And that will show the error below the receipt title. It's the same with hold too.

### What changes do you think we should make in order to solve the problem?

Set the error to the optimistic unhold action instead.
```
{
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`,
    value: {
        [createdReportAction.reportActionID]: {
            errors: ErrorUtils.getMicroSecondOnyxErrorWithTranslationKey('iou.error.genericUnholdExpenseFailureMessage'),
        },
    },
},
```

Do the same for hold too, but we will set it for 2 action, hold request and hold reason action.

**Comment by anmurali** [comment] 2024-08-06 02:04
Seems fixed.

**Comment by mallenexpensify** [comment] 2024-08-07 22:48
@robertjchen 👀 plz to see if this will be fixed via the below. I'm commenting cuz I'm BZ on[ this similar issue](https://github.com/Expensify/App/issues/46946#issuecomment-2273759604)
- [[Held requests] Clean up the hold/unhold logic](https://github.com/Expensify/App/issues/44573#top)

**Comment by anmurali** [comment] 2024-08-14 02:28
Waiting on @robertjchen to check if that PR fixed this issue before closing it.

**Comment by robertjchen** [comment] 2024-08-14 05:46
Yep, this is addressed by that PR!

**Closed by robertjchen** 2024-08-14 05:46 UTC
Labels: Daily, Bug
