### ISSUE TITLE
[$500] mWeb- Blank page is displayed when tapped on Concierge or Send a message options

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11892] opened 2022-10-16 02:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/11857

## Action Performed:
1. Open the site https://help.expensify.com/main
2. Click on Concierge button and verify it opens the Concierge chat in NewDot if the user is logged in.
3. Click on the Send message button and verify it opens the Concierge chat in NewDot too.

## Expected Result:
By clicking on the Send message button and verify it opens the Concierge chat in NewDot too.

## Actual Result:
Blank page is displayed when tapped on Concierge or Send a message options

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.16.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196014717-570a6458-0e7c-45e9-9e9a-693a550cec66.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment] 2022-10-17 13:04
@kbecciv can you confirm this only happens on Mobile Web? I have tested on Desktop and also on Android with the native app and it works. 

cc @marcochavezf as you are the author of https://github.com/Expensify/App/pull/11857. Can this be external? 🤔

**Comment by kbecciv** [comment] 2022-10-17 14:29
@flodnv
Correct, it happens only on mobile Web. Windows/Chrome  is Pass for QA team.

https://user-images.githubusercontent.com/93399543/196203915-ad9af389-2887-4c23-92e2-45ffadbbb672.mp4

**Comment by marcochavezf** [comment] 2022-10-18 16:59
Oh interesting it only happens in mWeb (no native app installed). Yeah it can be external. FWIW this issue is not related to the help.expensify.com site, the problem is that for some reason https://new.expensify.com/concierge is not opening the Concierge report correctly only on mWeb (only if the user is logged in).

**Comment by lschurr** [comment] 2022-10-18 20:14
Posted job.

https://www.upwork.com/ab/applicants/1582465027628163072/job-details
https://www.upwork.com/jobs/~0175ba72296e865638

**Comment by lschurr** [comment] 2022-10-31 15:56
Hi @rushatgabhane - could you review the added proposal?

**Comment by mvtglobally** [comment] 2022-11-03 03:16
Issue not reproducible during KI retests. (First week)

**Comment by lschurr** [comment] 2022-11-03 15:40
I can reproduce this if I use mobile web and go to new.expensify.com/concierge. Should that link work to find your conversation with Concierge?

@flodnv are you able to reproduce?

@rushatgabhane can you review the proposal?

**Comment by flodnv** [comment] 2022-11-07 11:23
@Ollyws your proposal looks good to me, but,

>One solution to this is to subscribe to ONYXKEYS.IS_SIDEBAR_LOADED in SidebarLinks and only enable Freeze after it has been set to true, however this causes an unnecessary re-render.

For my own understanding can you clarify why "this causes an unnecessary re-render"?

**Comment by flodnv** [comment] 2022-11-07 11:59
Thanks, 👍 to your proposal!

**Comment by lschurr** [comment] 2022-11-07 20:59
Awesome. @Ollyws will you please apply for [the job in Upwork](https://www.upwork.com/jobs/~0175ba72296e865638)? Additionally, when do you expect to have a PR ready for review?

**Comment by lschurr** [comment] 2022-11-08 17:38
Offer sent in Upwork.

**Comment by mvtglobally** [comment] 2022-11-09 03:39
Issue not reproducible during KI retests. (Second week)

**Comment by flodnv** [comment] 2022-11-09 10:22
Go for it @Ollyws !

**Comment by flodnv** [comment] 2022-11-11 07:50
@rushatgabhane can you review the PR please?

**Comment by flodnv** [comment] 2022-11-14 09:45
@lschurr next steps are on you^

**Comment by lschurr** [comment] 2022-11-14 15:36
Asked for help here since I'm unsure about which test should be added. https://expensify.slack.com/archives/C01SKUP7QR0/p1668439426176659

**Comment by flodnv** [comment] 2022-11-14 16:34
We should add these, from mWeb : 
<img width="739" alt="image" src="https://user-images.githubusercontent.com/4164921/201714645-33e38176-27fd-4ef6-8ceb-dbf827f5ccf1.png">

**Comment by lschurr** [comment] 2022-11-14 18:02
Ok, I made this GH to request the test be added. @flodnv would you look at that and confirm I've done it correctly? (sorry first time doing all of this)

**Comment by flodnv** [comment] 2022-11-15 10:13
LGTM, thanks 👍

**Comment by lschurr** [comment] 2022-11-15 17:23
@rushatgabhane - I've invited you to apply for the job in Upwork. Can you accept the offer?

**Comment by mvtglobally** [comment] 2022-11-16 02:18
Issue not reproducible during KI retests. (Third week)

**Comment by lschurr** [comment] 2022-11-16 15:27
@Ollyws and @rushatgabhane have been paid! Closing.

**Closed by lschurr** 2022-11-16 15:27 UTC
Labels: External, Engineering, Daily, Bug
