### ISSUE TITLE
Split - Empty merchant field can't be saved when expense can be split in room without merchant

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42275] opened 2024-05-16 11:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to #announce room that has members.
3. Split an expense without merchant.
4. Note that expense can be split in #room without merchant.
5. Start another split expense flow.
6. On confirmation page, click Merchant.
7. Without entering Merchant, hit Save.

## Expected Result:
Empty merchant field can be saved because merchant is not a requirement in room expense (Step 4).

## Actual Result:
Empty merchant field cannot be saved when expense can be split in room without merchant.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/acb7cea9-87f7-412a-9447-1b84f8f5cee2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-05-16 11:41
We think this issue might be related to the #vip-split.

**Comment by bernhardoj** [comment] 2024-05-16 14:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't save empty string as the merchant when splitting bills in an announce room.

### What is the root cause of that problem?
The merchant is required if the transaction contains a participant with `isPolicyExpenseChat` property or if the report is in group policy.
https://github.com/Expensify/App/blob/a03fecc80e5326a24644254f682441aa50585347/src/pages/iou/request/step/IOURequestStepMerchant.tsx#L66

In case of announce room, the report is in group policy, so the merchant is required, but the merchant is only required if it's a policy expense chat, so the condition is not 100% correct.

### What changes do you think we should make in order to solve the problem?

We can use ReportUtils.isPolicyExpenseChat and ReportUtils.getRootParentReport to check whether the root report is a policy expense chat or not.
```
const isMerchantRequired = ReportUtils.isPolicyExpenseChat(ReportUtils.getRootParentReport(report)) || transaction?.participants?.some((participant) => Boolean(participant.isPolicyExpenseChat));
```

We can apply the fix for other pages if it has the same issue.

**Comment by garrettmknight** [comment] 2024-05-17 16:37
Splits shouldn't be allowed in Announce. Closing this one, will open another issue to correct that problem once we have consensus.

**Closed by garrettmknight** 2024-05-17 16:37 UTC
Labels: Daily, Bug
