### ISSUE TITLE
[$1000] iOS - 2FA - Error "Incorrect 2FA" if login via magic link into 2FA enabled account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19921] opened 2023-05-31 23:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition - User enabled 2FA in account (either via OD or ND).
1. Open iOS app
2. Input email for account from the precondition
3. Tap "Continue"
4. Open the sign in link email
5. Copy magic link
6. Modify link to staging
7. Pasted the modified link into other app (e.g. notes)
8. Tap on the modified link

## Expected Result:
User lands in 2FA input screen in the app

## Actual Result:
User lands in magic code input screen in the app with an error displayed - "incorrect two factor authentication code. Please try again". User is able to proceed to 2FA screen by using the code from the same email.
Issue reproduces both for expensifail HT and non-expensifail accounts.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5d2b17e5-34dd-43fb-b230-569794d212a8

https://platform.applause.com/services/links/v1/external/c3f263f86bb7329eb3ca7cd2c01becc7149602cf390c681a21cc420fdd632468

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef887a0ae9abb1bc</li>
        <li>Upwork Job ID: 1664166777529278464</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-06-01 00:14
ios <> Android issue swap

**Comment by kadiealexander** [comment] 2023-06-01 07:07
Reproduced on iOS:

![IMG_0989](https://github.com/Expensify/App/assets/59587260/18a3e9dd-de69-448b-9caa-9ea48edf3828)

**Comment by Natnael-Guchima** [comment] 2023-06-01 07:17
I think this issue is being addressed here https://github.com/Expensify/App/issues/19636

**Comment by kadiealexander** [comment] 2023-06-01 07:48
Agreed, thanks for flaggin @Natnael-Guchima! Closing as a dupe.

**Closed by kadiealexander** 2023-06-01 07:48 UTC
Labels: External, Daily, Help Wanted, Bug
