### ISSUE TITLE
Tax - Inconsistency in auto changing tax rate on confirmation page and transaction thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44179] opened 2024-06-21 19:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.0.0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4652180
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Taxes feature is enabled
- Tax A is assigned to Workspace currency default
- Tax B is assigned to Foreign currency default
- There is unassigned Tax C
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go to + > Submit expense > Manual
4. Enter amount > Next
5. Click Tax rate
6. Select Tax C (very important)
7. Click Amount and change to a foreign currency
8. Note that the Tax rate is still Tax C and it does not auto change to Tax B (Foreign currency default)
9. Submit an expense in Workspace currency default (Tax A)
10. Go to transaction thread
11. Click Tax rate
12. Select Tax 
13. Click Amount and change to a foreign currency
14. Note that the Tax rate is auto changed to Tax B (Foreign currency default)

## Expected Result:
There should be consistency in converting tax rate to Foreign currency default when changing currency to a foreign currency on confirmation page and transaction thread

## Actual Result:
When manually changing to an unassigned tax rate (Tax C) and then switching to foreign currency, inconsistency is seen
- On confirmation page, the tax rate does not auto convert to follow Foreign currency default (Tax B)
- On transaction thread, the tax rate auto converts to follow Foreign currency default (Tax B)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/68a86532-06d0-4468-b1b2-6c24a878e6a0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-21 19:38
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-21 19:38
We think that this bug might be related to #wave-collect - Release 1

**Comment by sonialiap** [comment] 2024-06-26 10:31
Looks like a dupe of https://github.com/Expensify/App/issues/42586

**Closed by sonialiap** 2024-06-26 10:31 UTC
Labels: Daily, Overdue, Bug
