### ISSUE TITLE
HIGH: Email notification for expense thread message appears with empty brackets

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37568] opened 2024-02-29 20:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709146689688659

## Action Performed:
1. Create a expense report in a workspace
2. Submit the report to the approver
3. Approve the report and start a thread messge inside the expense report
4. Wait for the email notification

## Expected Result:
Should not have empty brackets in the subject line

## Actual Result:
Email subject appears with empty brackets

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (1)](https://github.com/Expensify/App/assets/38435837/a1940308-c950-46a7-b4d7-726a416dc1d4)

![image (2)](https://github.com/Expensify/App/assets/38435837/1847ca54-080b-460d-9e4d-043627b65aa9)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01224f69e939bd789a</li>
        <li>Upwork Job ID: 1763307587005255680</li>
        <li>Last Price Increase: 2024-02-29</li>
    </ul>
</details>

**Comment by rlinoz** [comment] 2024-02-29 20:58
This is internal, so no need for a C+

**Comment by jliexpensify** [comment] 2024-03-01 02:57
Upeorks job removed

**Comment by jliexpensify** [comment] 2024-03-04 00:51
@rlinoz assigned this a `HIGH` priority and assigned you, based off the other PR. Feel free to change!

**Comment by rlinoz** [comment] 2024-03-04 21:36
I am unsure on how we want to fix this.

The problem here is that for threads inside an Expense Report and threads inside an Expense we are showing empty brackets, so a thread has this subject: `[] bug`.

For Expense Reports our current subject is `Bob requests $3.00`, we could just add that same subject inside the brackets and the subject for a thread would be `[Bob requests $3.00] why?`, the problem is for each new request this subject changes, because the total amount changes, so a new answer to this thread could come up as  `[Bob requests $10.00] follow up`, are we ok with that?

An option would be to use the expense report name in the brackets.

For expenses it is a little easier, our current subject is `Bob: $3.00 request`, so we could just put this in brackets and move on, getting `[Bob: $3.00 request] Nice`. The only problem I see with this is that it might be too generic.

@quinthar any thoughts?

**Comment by quinthar** [comment] 2024-03-05 03:09
I think it's ok if the subject changes, and that we should match the email to whatever report/thread name is being shown in the UI.

**Comment by rlinoz** [comment] 2024-03-13 21:14
PR is in production https://github.com/Expensify/Web-Expensify/pull/41161#issuecomment-1994978149, closing this one.

**Closed by rlinoz** 2024-03-13 21:14 UTC
Labels: Reviewing, Daily, Internal, Needs Reproduction, Bug
