### ISSUE TITLE
[$2000] iOS - Profile - Bottom home bar on iOS does not have transparent background

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12963] opened 2022-11-23 18:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login
2. Go to profile page

## Expected Result:
Bottom home bar should have transparent background

## Actual Result:
Have white background

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.30-0
**Reproducible in staging?:** y
**Reproducible in production?:**y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/203618068-85213643-2e7f-475a-ae46-3e98023af0bf.png" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/203618113-4776a4e0-5d5d-4426-8d24-3f799354977a.PNG" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669215534845239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d769c08d05e2ed49</li>
        <li>Upwork Job ID: 1595628342549524480</li>
        <li>Last Price Increase: 2022-12-13</li>
    </ul>
</details>

**Comment by hungvu193** [comment] 2022-11-24 02:35
This come from this piece of code:
https://github.com/Expensify/App/blob/0274c4ab700ea483272315c27e3299883356ed30/src/components/ScreenWrapper/BaseScreenWrapper.js#L78-L81
This also happen in every screens that used ScreenWrapper, I tested on Setting, About...
So I think the prop: `includePaddingBottom` should be false by default.
```diff
const defaultProps = {
    style: [],
-    includePaddingBottom: true,
+   includePaddingBottom: false,
    includePaddingTop: true,
    onTransitionEnd: () => {},
    modal: {},
    keyboardAvoidingViewBehavior: 'padding',
};
```

**Comment by kadiealexander** [comment] 2022-11-24 04:00
From this SO: https://stackoverflow.com/c/expensify/questions/14418
- [x] **The "bug" is actually a bug**: 
- [x] **The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)**: 
- [x] **The bug is reproducible, following the reproduction steps:**

![28696830-FCDC-47D8-B9A3-79F37EE3668E](https://user-images.githubusercontent.com/59587260/203690934-5bfe84e3-d888-49f2-a498-a9436c4c98b4.png)

- [x] **If you’re unable to reproduce the bug, add the _Needs reproduction_ label. Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.**: 
- [x] **The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?):** 
- [x] **The GH was created by an Expensify employee or a QA tester:** 
- [x] **If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification:** 
- [x] **If there's a link to Slack, check the discussion to see if we decided not to fix it:** 
- [x] **Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label:**

**Comment by Pujan92** [comment] 2022-11-24 08:43
**Proposal**

As @hungvu193 mentioned either we can update `includePaddingBottom: false` in the default or we can only add bottom padding when we want to show the network error message(for showing the message better).

https://github.com/Expensify/App/blob/0f1d7e2c9dc005fe467ad5f9891b8d4f1005c7ca/src/components/ScreenWrapper/BaseScreenWrapper.js#L79-L81
```
if (this.props.network.isOffline) {
   paddingStyle.paddingBottom = paddingBottom;
}
```

Online Case
![Simulator Screen Shot - iPhone 14 - 2022-11-24 at 14 03 52](https://user-images.githubusercontent.com/14358475/203734277-8d4b9505-b109-4ab7-a6c3-3ad982de3ea1.png)

Offline Case without Bottom Padding
![Simulator Screen Shot - iPhone 14 - 2022-11-24 at 14 08 35](https://user-images.githubusercontent.com/14358475/203734439-43b599ea-2381-4699-9ffb-402f52f7a703.png)

Offline Case with Bottom Padding
![Simulator Screen Shot - iPhone 14 - 2022-11-24 at 14 04 40](https://user-images.githubusercontent.com/14358475/203734492-3ee7bf0d-ad0e-4c17-a748-96a205e0e2dc.png)

**Comment by vladamx** [comment] 2022-11-24 18:25
I think the real issue here is that we can not add bottom spacing in ScreenWrapper without having the white background behind a notch. See related issue in the safe area context repo https://github.com/th3rdwave/react-native-safe-area-context/issues/197

**Comment by fedirjh** [comment] 2022-11-24 18:56
Since this is related to iOS only we can set the `defaultProps.includePaddingBottom = false;` 

Changes : new file `index.ios.js`

```jsx
import React from 'react';
import BaseScreenWrapper from './BaseScreenWrapper';
import {defaultProps, propTypes} from './propTypes';

const ScreenWrapper = props => (
    <BaseScreenWrapper
        // eslint-disable-next-line react/jsx-props-no-spreading
        {...props}
    >
        {props.children}
    </BaseScreenWrapper>
);

defaultProps.includePaddingBottom = false;

ScreenWrapper.propTypes = propTypes;
ScreenWrapper.defaultProps = defaultProps;
ScreenWrapper.displayName = 'ScreenWrapper';

export default ScreenWrapper;
```

**Comment by mananjadhav** [comment] 2022-11-27 16:46
I agree with @vladamx's comment here.

All the proposals are about either adding/removing the padding, but the title says it doesn't have transparent background.

@shawnborton Can you confirm if that we still need a background image? Is that something which worked earlier and now it doesn't?

**Comment by shawnborton** [comment] 2022-11-28 20:40
I'm not sure what caused it to work before and not work anymore. But yeah, I think we want to make sure there is transparency and not a background color around the home bar.

**Comment by kadiealexander** [comment] 2022-11-30 21:02
📢 Price doubled! Please get those proposals in.

**Comment by hungvu193** [comment] 2022-12-01 05:29
Here's my original proposal https://github.com/Expensify/App/issues/12963#issuecomment-1325872151
<b>Updated Proposal</b>
Since our parent is `View` and has paddingBottom, our children view is ScrollView, so the content of ScrollView is only inside space it has. See the attachment bellow, the orange color is the backgroundColor of ScrollView inside.
![simulator_screenshot_4AEFCD5E-0501-47D1-B74C-52C7A655F5B4](https://user-images.githubusercontent.com/16502320/204972525-5315d975-b572-4934-bfcf-b7f1f725f042.png)
<b>Solution</b>
Move the padding inside the children it will solve the problem.

```diff
diff --git a/src/components/ScreenWrapper/index.js b/src/components/ScreenWrapper/index.js
index 52d9aa5e6..ee4728b2e 100644
--- a/src/components/ScreenWrapper/index.js
+++ b/src/components/ScreenWrapper/index.js
@@ -77,7 +77,7 @@ class ScreenWrapper extends React.Component {
                     }
 
                     // We always need the safe area padding bottom if we're showing the offline indicator since it is bottom-docked.
-                    if (this.props.includePaddingBottom || this.props.network.isOffline) {
+                    if (this.props.network.isOffline) {
                         paddingStyle.paddingBottom = paddingBottom;
                     }
 
diff --git a/src/pages/settings/Profile/ProfilePage.js b/src/pages/settings/Profile/ProfilePage.js
index 6c805ade9..d7efa38af 100755
--- a/src/pages/settings/Profile/ProfilePage.js
+++ b/src/pages/settings/Profile/ProfilePage.js
@@ -28,6 +28,7 @@ import * as ValidationUtils from '../../../libs/ValidationUtils';
 import * as ReportUtils from '../../../libs/ReportUtils';
 import Form from '../../../components/Form';
 import OfflineWithFeedback from '../../../components/OfflineWithFeedback';
+import { withSafeAreaInsets } from 'react-native-safe-area-context';
 
 const propTypes = {
     /* Onyx Props */
@@ -219,6 +220,9 @@ class ProfilePage extends Component {
         }));
         const currentUserDetails = this.props.currentUserPersonalDetails || {};
         const pronounsPickerValue = this.state.hasSelfSelectedPronouns ? CONST.PRONOUNS.SELF_SELECT : this.pronouns;
+        const paddingStyle = {
+            paddingBottom: this.props.insets.bottom,
+        };
 
         return (
             <ScreenWrapper>
@@ -229,7 +233,7 @@ class ProfilePage extends Component {
                     onCloseButtonPress={() => Navigation.dismissModal(true)}
                 />
                 <Form
-                    style={[styles.flexGrow1, styles.ph5]}
+                    style={[styles.flexGrow1, styles.ph5, paddingStyle]}
                     formID={ONYXKEYS.FORMS.PROFILE_SETTINGS_FORM}
                     validate={this.validate}
                     onSubmit={this.updatePersonalDetails}
@@ -342,4 +346,5 @@ export default compose(
             key: ONYXKEYS.LOGIN_LIST,
         },
     }),
+    withSafeAreaInsets,
 )(ProfilePage);

```

Result:


https://user-images.githubusercontent.com/16502320/204973162-2c4ed44f-96e6-4a89-af6d-b2c395b56dfe.mov

**Comment by mananjadhav** [comment] 2022-12-01 08:00
Thanks for the updated proposal @hungvu193, can you confirm if your change works fine with the `offline` mode as we show the offline text below the button?

**Comment by hungvu193** [comment] 2022-12-01 08:01
@mananjadhav yes, I didn't remove the paddingStyle inside ScreenWrapper, so it still worked with offline mode.

**Comment by shawnborton** [comment] 2022-12-01 14:59
Nice, that looks pretty good to me!

**Comment by mananjadhav** [comment] 2022-12-01 18:47
Okay great. Thanks for the update @hungvu193. Your proposal looks good to me.

@Gonals @shawnborton All yours.

🎀 👀 🎀 
C+ reviewed

**Comment by shawnborton** [comment] 2022-12-01 19:15
I completely agree with that ^^

**Comment by mananjadhav** [comment] 2022-12-01 19:18
@hungvu193 Are you willing to revise your proposal to take care of this across the App?

**Comment by hungvu193** [comment] 2022-12-02 00:34
@mananjadhav yes sure 😀

**Comment by hungvu193** [comment] 2022-12-02 01:05
We can create Common Component for the content view of these screen. As I remembered we have 3,4 screens like that

**Comment by vladamx** [comment] 2022-12-02 19:07
**Proposal**

In order to handle this in a reusable way i would do the next steps:

1. I would not change BaseScreenWrapper since its doing many things already and is not really a good fit for this kind of screens
2. I would have HeaderComponent handle top inset - Header is already reusable which is good
3. I would make a new reusable container component which will be a ScrollView with a bottom inset - I would wrap the contents of the necessary screens with this component. By doing this we don't need Form component to be a scroll view. Form will just do form things.

**Comment by mananjadhav** [comment] 2022-12-05 22:43
Checking through the comments now.

@orkunkarakus We don't recommend `getPlatform() === CONST.PLATFORM.IOS`. We need these to be split into their respective platform specific files. Please check the [contributing guidelines](https://github.com/Expensify/App#platform-specific-file-extensions). Also are you sure by just updating `ScreenWrapper`, we would cover all the screens?

> We can create Common Component for the content view of these screen. As I remembered we have 3,4 screens like that

@hungvu193 Can you elaborate on this? I am not sure what you mean by Content View. Can you list the screens in your proposal.

**Comment by hungvu193** [comment] 2022-12-06 03:20
@mananjadhav It will happen in screen that has button at the bottom inside the scrollview has `flexGrow: 1`.
They are: ProfileScreen, CloseAccountScreen, SearchScreen (OptionsSelector).
With few other screens, you can see that if you try to scroll the content to bottom, with these screens we can simply pass the `isIncludePaddingBottom: false` to ScreenWrapper of these screens.
I was planning to build a ContentView for these screens (similar to what we have in BaseModal.js), but since it only 3 screens I don't think it's necessary.
In case to reuse the logic we can create a HOC to get the calculated padding inset:

```javascript
import React from 'react';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import PropTypes from 'prop-types';
import getComponentDisplayName from '../libs/getComponentDisplayName';
import * as StyleUtil from '../styles/StyleUtils';

const withSafeAreaInsetsPropTypes = {
    insets: PropTypes.any,
};

export default function withSafeAreaInsets(WrappedComponent) {
    const WithSafeAreaInsets = (props) => {
        const insets = useSafeAreaInsets();
        const localInsets = StyleUtil.getSafeAreaPadding(insets);

        return (
            <WrappedComponent
        // eslint-disable-next-line react/jsx-props-no-spreading
                {...props}
                ref={props.forwardedRef}
                insets={localInsets}
            />
        );
    };

    WithSafeAreaInsets.displayName = `withDrawerState(${getComponentDisplayName(
        WrappedComponent,
    )})`;
    WithSafeAreaInsets.propTypes = {
        forwardedRef: PropTypes.oneOfType([
            PropTypes.func,
            PropTypes.shape({current: PropTypes.instanceOf(React.Component)}),
        ]),
    };
    WithSafeAreaInsets.defaultProps = {
        forwardedRef: undefined,
    };
    return React.forwardRef((props, ref) => (
        // eslint-disable-next-line react/jsx-props-no-spreading
        <WithSafeAreaInsets {...props} forwardedRef={ref} />
    ));
}

export {withSafeAreaInsetsPropTypes};

```

**Comment by kadiealexander** [comment] 2022-12-09 03:05
@mananjadhav any thoughts on the above?

**Comment by mananjadhav** [comment] 2022-12-09 05:04
thanks for the ping @kadiealexander. I didn't get the notification for the previous comment.

@hungvu193 I think we're making it more complex by introducing the HoC and we haven't adopted the React hooks usage in our codebase. Please checkout the [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md). I would recommend only fixing the padding to the relevant screens and call it off. If you're updating the ScreenWrapper, then does it cover all the screens that you've mentioned? Can you send in the revised proposal with the requested changes?

thank you for the patience here.

**Comment by hungvu193** [comment] 2022-12-09 05:29
@mananjadhav
Sure here's the screen that need to update padding inside:
- Profile Screen.
- Search Screen.
Here's the screen that need to set `includePaddingBottom: false` to their screen wrapper.
- Company Information (Step 2 to 5)
- Manage Members
- Settings
- About
- Workspace

We can consider update these screens, since we only saw the `not transparent background` only when we tried to scroll so hard to the bottom.
- Close Account
- Pay Bill
- Send Invoice

**Comment by fedirjh** [comment] 2022-12-10 22:13
@orkunkarakus we proposed those changes before :smiling_face_with_tear:  , you have to read other proposals before posting new one , https://github.com/Expensify/App/issues/12963#issuecomment-1326775070 

and @mananjadhav stated this
> All the proposals are about either adding/removing the padding, but the title says it doesn't have transparent background.

**Comment by shawnborton** [comment] 2022-12-12 22:23
Not overdue, still looking at proposals

**Comment by mananjadhav** [comment] 2022-12-13 04:01
should we have doubled here @kadiealexander ? We are reviewing the proposals and I think we might go with one of them. I'll have an update on this by tomorrow.

**Comment by kadiealexander** [comment] 2022-12-13 04:05
Apologies, I was going off Shawn's comment above.

**Comment by marcaaron** [comment] 2022-12-14 01:51
I thought the whole point of something like a "safe area" to render content inside a "safe area". And by removing the content from here aren't we _basically_ just saying something like.. "we don't care about safe areas" in these places?

Seems like it would be better to look at the places where a "safe area" is required (e.g. wherever there is a button at the bottom of the screen that may get rendered in the "unsafe area") important and explicitly add one there?

**Comment by marcaaron** [comment] 2022-12-14 02:26
>here's the screens that need to update padding inside:

Doesn't moving the safe area padding into the screen itself means that extra padding will exist now on all platforms besides iOS?

**Comment by hungvu193** [comment] 2022-12-14 02:46
> > here's the screens that need to update padding inside:
> 
> Doesn't moving the safe area padding into the screen itself means that extra padding will exist now on all platforms besides iOS? **Edit:** I guess not because the insets should return 0.
Yes, other platforms that didn't have safe area insets will return 0.

**Comment by marcaaron** [comment] 2022-12-14 02:53
Getting something started over here -> https://github.com/Expensify/App/pull/13580

I could use some help with testing and making sure all the screens are good if @mananjadhav and @hungvu193 are interested in helping find any remaining things that need to be fixed.

**Comment by marcaaron** [comment] 2022-12-14 18:55
Oh, was there not any announcement about this? As far as I know, we have been encouraged to take things "internal" at our discretion to help expedite as our roadmap is blocked on these bugs and unblocking it is our highest priority atm. It does not affect compensation if you have contributed to the solution then you will get paid. So, it's less work for you and the same benefit 😄

**Comment by hungvu193** [comment] 2022-12-15 00:47
> Oh, was there not any announcement about this? As far as I know, we have been encouraged to take things "internal" at our discretion to help expedite as our roadmap is blocked on these bugs and unblocking it is our highest priority atm. It does not affect compensation if you have contributed to the solution then you will get paid. So, it's less work for you and the same benefit 😄

Thank you @marcaaron

**Comment by kadiealexander** [comment] 2022-12-20 04:17
I'm going OOO for a family emergency, if this needs action while I'm away please re-add the `bug` label to assign someone.

**Comment by mananjadhav** [comment] 2023-01-02 06:14
PR is raised and I am going to review this by today-tomorrow.

**Comment by mananjadhav** [comment] 2023-01-10 06:48
PR is merged and deployed to production 3 days ago.

**Comment by mananjadhav** [comment] 2023-01-13 15:56
@kadiealexander This is ready for payout today. Can you please help me with the same?

**Comment by kadiealexander** [comment] 2023-01-16 03:01
Yes! The Upwork job closed, but please apply here @hungvu193 and @mananjadhav and I'll get the payment issued. 

https://www.upwork.com/jobs/~0135d50f36c1f175ac

**Comment by hungvu193** [comment] 2023-01-16 03:02
Thanks @kadiealexander, I've just applied.

**Comment by kadiealexander** [comment] 2023-01-16 03:07
Thanks @hungvu193, I've just issued that payment now :)

**Comment by mananjadhav** [comment] 2023-01-16 03:11
Applied @kadiealexander :)

**Comment by kadiealexander** [comment] 2023-01-16 04:38
Everyone is paid 🎉

**Closed by kadiealexander** 2023-01-16 04:38 UTC
Labels: Reviewing, Daily, Internal, Bug
