### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] [HIGH] When mentioning a user the "actionable whisper" message shows the full display name 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38079] opened 2024-03-11 18:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710108211692399

## Action Performed:
1. Open any room
2. mention someone in the compose box and send
3. Look at the "actionable whisper" message `Heads up, @B B isn't a member of this room.`

## Expected Result:
This shouldn't show full display name

## Actual Result:
Shows full display name

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/c4281c93-c84d-475b-b81c-ef3f1957d7a1

![Screen Shot 2024-03-11 at 2 49 51 PM](https://github.com/Expensify/App/assets/38435837/f55532bd-2043-4cae-be45-c6707054a995)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8171385c92b3a6a</li>
        <li>Upwork Job ID: 1767266276761448448</li>
        <li>Last Price Increase: 2024-03-18</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2024-03-11 19:21
> Expected Result:
This shouldn't show full display name


what is the correct result then?

**Comment by whitestar613910** [comment] 2024-03-11 19:30
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> When mentioning a user the "actionable whisper" message shows the full display name.
> 
> ### What is the root cause of that problem?
> `displayName` is used here, which leads to the full display name being shown.
> 
> https://github.com/Expensify/App/blob/944793736f38189dd8b37b56473b40c5adf552fd/src/libs/PersonalDetailsUtils.ts#L205-L211
> 
> ### What changes do you think we should make in order to solve the problem?
> `firstName` should be used.
> 
> ```
> function getEffectiveDisplayName(personalDetail?: PersonalDetails): string | undefined {
>     if (personalDetail) {
>         return LocalePhoneNumber.formatPhoneNumber(personalDetail?.login ?? '') || personalDetail.firstName;
>     }
> 
>     return undefined;
> }
> ```

The problem at hand involves the "actionable whisper" message displaying the full user's display name when mentioning them. 

The root cause of this issue lies in the use of the `displayName` attribute in the `getEffectiveDisplayName` function, which results in the presentation of the complete display name instead of the intended behavior. The function relies on `LocalePhoneNumber.formatPhoneNumber` for formatting or defaults to the `firstName` of the personal details if available.

**Comment by godofoutcasts94** [comment] 2024-03-11 19:36
@sobitneupane what is the expected result ? `firstName`, `lastName` or `email`. What is it?  Can you please mention that ?

**Comment by whitestar613910** [comment] 2024-03-11 19:41
Contributor details
your Expensify account email: techcollabo147@gmail.com
Upwork profile Link: https://www.upwork.com/freelancers/~010bbce3c00ea08221?s




> The problem at hand involves the "actionable whisper" message displaying the full user's display name when mentioning them.
> 
> The root cause of this issue lies in the use of the `displayName` attribute in the `getEffectiveDisplayName` function, which results in the presentation of the complete display name instead of the intended behavior. The function relies on `LocalePhoneNumber.formatPhoneNumber` for formatting or defaults to the `firstName` of the personal details if available.

The problem at hand involves the "actionable whisper" message displaying the full user's display name when mentioning them.

The root cause of this issue lies in the use of the displayName attribute in the getEffectiveDisplayName function, which results in the presentation of the complete display name instead of the intended behavior. The function relies on LocalePhoneNumber.formatPhoneNumber for formatting or defaults to the firstName of the personal details if available.

**Comment by nkdengineer** [comment] 2024-03-12 02:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Shows full display name

### What is the root cause of that problem?
We use the `displayName` or `phoneNumber` here that show the full display name

https://github.com/Expensify/App/blob/b8590c966c7a7f7df8b6a1c8d8566cbab0fd572b/src/libs/PersonalDetailsUtils.ts#L207
### What changes do you think we should make in order to solve the problem?
We can use `getDisplayNameForParticipant` here and pass the param `shouldUseShortForm` as `true` which we return the sort name of the user and cover all cases like phone number, `hidden`, ....

https://github.com/Expensify/App/blob/b8590c966c7a7f7df8b6a1c8d8566cbab0fd572b/src/libs/PersonalDetailsUtils.ts#L207

### What alternative solutions did you explore? (Optional)
NA

**Comment by whitestar613910** [comment] 2024-03-12 03:12
Hello

I think you've pasted the same TypeScript module again, along with a
proposal for solving a specific problem related to displaying full names.
I suggest using `getDisplayNameForParticipant` and passing
`shouldUseShortForm` as true to display the short name of the user.

Also I think the issue you're addressing is related to displaying the full
display name in a specific context, and the proposed solution involves
using a function that provides a short form of the name based on certain
conditions.

best,
kingsley

**Comment by ahmedGaber93** [comment] 2024-03-12 03:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When mentioning a user (not member in the room) the "actionable whisper" message **Heads up, [full name] isn't a member of this room.** with full name not first name.

Note: all mention should display the full name else this issue case when user is not member in the room.
### What is the root cause of that problem?
the component responsable for rendering mentioned user view is [MentionUserRenderer](https://github.com/Expensify/App/blob/main/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx) which display `displayName` with fallback `user.login` not `firstName`
https://github.com/Expensify/App/blob/b8590c966c7a7f7df8b6a1c8d8566cbab0fd572b/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx#L62
### What changes do you think we should make in order to solve the problem?
conditionaly display `firstName` if user is not member in the room, to do that we need this steps:
1. pass `currentReportID` to `MentionUserRenderer` by `withCurrentReportID` or `withOnyx`
2. use `currentReportID` and to check if `htmlAttributeAccountID` is member on this room and conditionaly display `firstName` [here](https://github.com/Expensify/App/blob/b8590c966c7a7f7df8b6a1c8d8566cbab0fd572b/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx#L62)
```javascript
// we can also check `isChatRoom`
if (!ReportUtils.getReport(currentReportID)?.visibleChatMemberAccountIDs?.includes(Number(htmlAttributeAccountID))){
  // we will create this method like exist one `getDisplayNameOrDefault`
  return getFirstNameOrDefault(....)
}else{
  // exist code
  return getDisplayNameOrDefault(....)
}
```

if this "actionable whisper" message **Heads up, [full name] isn't a member of this room.** appare in other places we need also to fix it.
### What alternative solutions did you explore? (Optional)
we can display `user.login` instead of `displayName`

**Comment by whitestar613910** [comment] 2024-03-12 05:03
Hello

Are you trying to address an issue related to displaying user names in a
chat application?
The problem is that when mentioning a user who is not a member of the room,
the full name is displayed, and you want to conditionally display the first
name in this specific case.
The root cause is identified as the MentionUserRenderer component, which
currently displays the full name without considering whether the user is a
member of the room.

To solve the problem, you propose passing the currentReportID to
MentionUserRenderer and using it to check whether the user is a member of
the room. If not, you suggest creating a new method (ex:
getFirstNameOrDefault) to conditionally display the first name.

The alternative solution mentioned is to display user.login instead of
displayName.
It seems like a reasonable proposal, and your plan to conditionally display
the first name based on the user's membership status in the room makes
sense. Implementing this logic in MentionUserRenderer should address the
issue you've identified.😅😅😅

Best,
Kingsley

**Comment by whitestar613910** [comment] 2024-03-12 05:42
Restated Problem:
The issue arises when using a shortened mention in a chat application.
Specifically, when mentioning a user who is not a member of the chat room,
the full display name is shown in the actionable whisper message. This
behavior deviates from the intended functionality, where the login should
be displayed instead.

Root Cause:
The root cause of the problem is that, in the context of a shortened
mention and an actionable whisper message, the display name is being shown
even when the user isn't present in the chat room. In this scenario, the
correct behavior should be to display the user's login.

Proposed Changes:
To address this issue, the following changes are proposed:

1. Include context of the current report using withOnyx.

2. Update the PersonalDetailsUtils.getDisplayNameOrDefault function to make
it more flexible and easier to use.

interface GetDisplayNameOrDefaultProps {
  personalDetails?: Partial<PersonalDetails> | null;
  defaultValue?: string;
  shouldFallbackToHidden?: boolean;
  shouldAddCurrentUserPostfix?: boolean;
  defaultToLogin?: boolean;
}

function getDisplayNameOrDefault({
  personalDetails,
  defaultValue = '',
  shouldFallbackToHidden = true,
  shouldAddCurrentUserPostfix = false,
  defaultToLogin = false,
}: GetDisplayNameOrDefaultProps): string {
  if (defaultToLogin && personalDetails?.login) {
    return personalDetails.login;
  }

  let displayName = personalDetails?.displayName ?
personalDetails.displayName.replace(CONST.REGEX.MERGED_ACCOUNT_PREFIX, '')
: '';
  if (shouldAddCurrentUserPostfix && !!displayName) {
    displayName = `${displayName}
(${Localize.translateLocal('common.you').toLowerCase()})`;
  }

  const fallbackValue = shouldFallbackToHidden ?
Localize.translateLocal('common.hidden') : '';

  return displayName || defaultValue || fallbackValue;
}

3. Example usage in MentionUserRenderer:

const displayNameOrLogin = PersonalDetailsUtils.getDisplayNameOrDefault({
  personalDetails: user,
  defaultValue: LocalePhoneNumber.formatPhoneNumber(user?.login ?? ''),
  defaultToLogin:
!ReportUtils.getReport(currentReportID)?.participantAccountIDs?.includes(Number(htmlAttributeAccountID)),
});

These changes aim to provide a more flexible and context-aware solution for
handling display names, especially in scenarios where the user is not a
member of the chat room. The `defaultToLogin` option allows for a more
explicit control over whether to display the login or the full display name.
I think this answer gave you sufficient results.😅😅😅
Best,
Kingsley

**Comment by whitestar613910** [comment] 2024-03-12 12:43
Hi there,

Are there any additional solutions? Please inform me if you require
assistance.

**Comment by puneetlath** [comment] 2024-03-12 14:55
Just to clarify the behavior, all mentions, whether they are login-based or accountID-based should follow what is described here: https://github.com/Expensify/App/issues/32534#issuecomment-1843288493

**Comment by whitestar613910** [comment] 2024-03-12 15:32
I think you want to update the PersonalDetailsUtils.getDisplayNameOrDefault function to handle mentions more flexibly. The proposed changes include adding a new property defaultToLogin to the function's input object, and modifying the function to return the login if defaultToLogin is true and the login property exists in the personalDetails object. The rest of the function remains the same, handling the display name logic based on the other properties.

const displayNameOrLogin = PersonalDetailsUtils.getDisplayNameOrDefault({
  personalDetails: user,
  defaultValue: LocalePhoneNumber.formatPhoneNumber(user?.login ?? ''),
  defaultToLogin: !ReportUtils.getReport(currentReportID)?.participantAccountIDs?.includes(Number(htmlAttributeAccountID)),
});

This change will allow you to specify exactly when you want a shortened/hidden display name or if you want to only use the login as the display name.

**Comment by ahmedGaber93** [comment] 2024-03-12 15:40
my proposal work fine in both.
the "actionable whisper" message come from backend with accountID-based mentions - `<mention-user accountID=1234></mention-here>` and my proposal fix it without any affect on email based mentions, so both work fine with me.

**Comment by adelekennedy** [comment] 2024-03-13 18:48
@sobitneupane just a few proposals to review above

**Comment by sobitneupane** [comment] 2024-03-14 04:41
>If we have a personalDetail with display name, but no login, render as @Display Name
if we have a personalDetail with login, render the same way as email-based mentions

@puneetlath Just to clarify, we want to show `@login` if both login and displayName(firstName or LastName) is present, right?

For example, in the following case,
Login: john@gmail.com
First Name: John
Last Name: ABC

Mention should be @john@gmail.com

**Comment by nkdengineer** [comment] 2024-03-14 08:14
Updated [proposal](https://github.com/Expensify/App/issues/38079#issuecomment-1989932744).

**Comment by puneetlath** [comment] 2024-03-14 15:14
@brandonhenry I don't quite understand your question. 

>Though, re-reading your comment @puneetlath, i wonder if how it working right now is intended? If the user is on the same domain and has personalDetail with login, it renders like email-based mentions, which ultimately leads to rendering If it's on the same private domain as mine, render as @person. Otherwise render as @person@domain.com.

I don't think this is how it's currently working. At least not in the case of the whisper message. It's rendering with their display name, even though they are on the same domain and I have their email address locally. 
<img width="484" alt="image" src="https://github.com/Expensify/App/assets/1371996/54a4a534-fda1-4d56-b114-6ac1aa7e433e">

**Comment by ahmedGaber93** [comment] 2024-03-14 15:53
## Proposal
[Updated](https://github.com/Expensify/App/issues/38079#issuecomment-1990120462)

**Comment by sobitneupane** [comment] 2024-03-18 12:07
Changes suggested by @puneetlath [here](https://github.com/Expensify/App/issues/32534#issuecomment-1843288493) was made by https://github.com/Expensify/App/pull/34013 PR. Everything was working fine back then. This should be a regression.

This is probably regression from https://github.com/Expensify/App/pull/36998 PR. The PR made change to prioritize displayName over login. The change was made to show display name instead of login while assigning task.

We should consider https://github.com/Expensify/App/issues/36443 and https://github.com/Expensify/App/issues/34052 issues as well while solving this issue.

**Comment by ahmedGaber93** [comment] 2024-03-18 13:08
## Proposal
[Updated](https://github.com/Expensify/App/issues/38079#issuecomment-1990120462)

**Comment by sobitneupane** [comment] 2024-03-20 09:37
@ahmedGaber93 I am not sure your proposal will solve the issue. I didn't understand how your proposal will solve the issue. Even if user has set display name, if login is present, we would like to prioritize the login.

**Comment by sobitneupane** [comment] 2024-03-20 09:40
@brandonhenry Wouldn't your proposal recreate https://github.com/Expensify/App/issues/36443 issue? If it doesn't, can you please explain how it handles the issue. I might not have understand your proposal clearly.

**Comment by sobitneupane** [comment] 2024-03-20 09:43
@puneetlath We would want the task assignment message to show custom display name instead of login, right? We created [this](https://github.com/Expensify/App/issues/38079) regression while solving [this issue](https://github.com/Expensify/App/issues/36443). 

Culprit PR:https://github.com/Expensify/App/pull/36998

**Comment by sobitneupane** [comment] 2024-03-20 16:06
@brandonhenry Aren't we using `MentionUserRenderer` in task preview as well? After we make the changes you suggested, if I assign a task to a user with custom displayName, will the task preview show custom displayName or login?

> The primary issue on this ticket, is that whenever a user is mentioned inside a chat, if the user is on the same domain (example both users on @google.com) then the actionable whipser system message will show "@Full name is not in the room".

We want to remove the domain only for the case of private domain not public.

**Comment by nkdengineer** [comment] 2024-03-20 16:39
@sobitneupane what about my proposal https://github.com/Expensify/App/issues/38079#issuecomment-1989932744?

**Comment by puneetlath** [comment] 2024-03-20 21:07
>@puneetlath We would want the task assignment message (task preview) to show custom display name instead of login, right? https://github.com/Expensify/App/issues/38079 was caused while solving https://github.com/Expensify/App/issues/36443.

Yes, I think we'd want all mentions to work the same.

**Comment by ahmedGaber93** [comment] 2024-03-20 21:12
@sobitneupane 

> Even if user has set display name, if login is present, we would like to prioritize the login.

I think this approach would conflict with https://github.com/Expensify/App/issues/36443, we need to set the priority to displayName

This GitHub issue have two issues:
1. show full name rather than email in wishper messages(see the video in issue description), fixing this will conflict with issue#36443, so I think this is the expected behavior.
2.  shortened mentions not handled in wishper messages (see the screenshot in issue description) and this what i try to fix in my proposal.

```javascript
// here we handle shortened mentions
if (!isUserSetItsDisplayName && user?.login && LoginUtils.areEmailsFromSamePrivateDomain(user?.login, currentUserPersonalDetails.login ?? '')) {
    displayNameOrLogin = user?.login.split('@')[0];
}else{
    // here we handle displayName || login || hidden
    displayNameOrLogin = PersonalDetailsUtils.getDisplayNameOrDefault(user, LocalePhoneNumber.formatPhoneNumber(user?.login ?? ''));
}
```

If we will fix 2 issues and set the priority to login, we can do that

```javascript
if (user?.login) {
  if (Str.isSMSLogin(user?.login)){
    displayNameOrLogin = LocalePhoneNumber.formatPhoneNumber(user?.login ?? '');
  }else if(LoginUtils.areEmailsFromSamePrivateDomain(user?.login, currentUserPersonalDetails.login ?? '')) {
    displayNameOrLogin = user?.login.split('@')[0];
  }else{
    displayNameOrLogin = user?.login;
  }
}else{
  displayNameOrLogin = PersonalDetailsUtils.getDisplayNameOrDefault(user);
}
```

**Comment by ahmedGaber93** [comment] 2024-03-20 21:15
@puneetlath 
> Yes, I think we'd want all mentions to work the same.
Just to clarify, the same mean prioritize displayName over login or login over displayName.

**Comment by sobitneupane** [comment] 2024-03-21 05:59
Started discussion for clarification on the expected output.

https://expensify.slack.com/archives/C02NK2DQWUX/p1711000340700859

**Comment by sobitneupane** [comment] 2024-03-22 08:43
It was decided to prioritize login over display name for all the mentions in the app including task preview. We also should consider https://github.com/Expensify/App/issues/32534#issuecomment-1843288493 requirements in the proposal.

cc: @brandonhenry @ahmedGaber93 @nkdengineer

**Comment by sobitneupane** [comment] 2024-03-22 08:48
@brandonhenry `getMentionDisplayText` should probably handle the logic you are proposing in `getDisplayNameFromAccountID`. Can we make use of `getMentionDisplayText`? We would only want to remove domain if both users are in same private domain.

> We want to remove the domain only for the case of private domain not public. If [username@domain.com](mailto:username@domain.com) is on the same private domain, we should show the @username in whisper. If domain.com is public domain, we should always show @[username@domani.com](mailto:username@domani.com). It is already handled by getMentionDisplayText in MentionUserRenderer.

**Comment by sobitneupane** [comment] 2024-03-22 08:52
@ahmedGaber93 Would you like to update [your proposal](https://github.com/Expensify/App/issues/38079#issuecomment-2014623920) keeping this expected output in consideration?

**Comment by ahmedGaber93** [comment] 2024-03-22 10:10
## Proposal
[Updated](https://github.com/Expensify/App/issues/38079#issuecomment-1990120462)

**Comment by ahmedGaber93** [comment] 2024-03-22 10:34
@sobitneupane 
I think `getDisplayNameOrDefault` in not the good place to do this changes because it use in many ather places rather than `MentionUserRenderer` 

also, `getMentionDisplayText` logic work as `get short mention` and called only in one place on [email-based mention](https://github.com/Expensify/App/blob/0aa0ffa8301d4d8bdb43f4a6985098b437428f47/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx#L69) 
so this lines always false because no `userAccountID` will pass
https://github.com/Expensify/App/blob/0aa0ffa8301d4d8bdb43f4a6985098b437428f47/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx#L46-L48

I propose to clean it by rename it to `returnShortMentionIfFound` and remove parameter `userAccountID`

```javascript
const returnShortMentionIfFound = (userLogin) => {
    // If the emails are not in the same private domain, we also return the displayText
    if (!LoginUtils.areEmailsFromSamePrivateDomain(displayText, currentUserPersonalDetails.login ?? '')) {
        return displayText;
    }

    // Otherwise, the emails must be of the same private domain, so we should remove the domain part
    return displayText.split('@')[0];
};
 ```   
 

 I think its good if we keep based-email and based-account handle its displayText alone because every one of them have diffrend data , `based accountID depend on accountID, and based email depend on html node data, and just share `returnShortMentionIfFound` between them`

**Comment by sobitneupane** [comment] 2024-03-25 08:44
@ahmedGaber93 Thanks for the update.

Instead of adding the logic you suggested, can't we reuse `getMentionDisplayText` as done initially by [this PR](https://github.com/Expensify/App/pull/34013/)

**Comment by nkdengineer** [comment] 2024-03-25 10:09
@sobitneupane I updated proposal https://github.com/Expensify/App/issues/38079#issuecomment-1989932744 to reuse `getMentionDisplayText` just need a bit change in `getDisplayNameOrDefault` function.

**Comment by sobitneupane** [comment] 2024-03-25 10:33
@ahmedGaber93 We won't be using `getMentionDisplayText ` for prioritization.

I believe following code will do the job.
```diff
-    displayNameOrLogin = PersonalDetailsUtils.getDisplayNameOrDefault(user, LocalePhoneNumber.formatPhoneNumber(user?.login ?? ''));
+    displayNameOrLogin = LocalePhoneNumber.formatPhoneNumber(lodashGet(user, 'login', '')) || lodashGet(user, 'displayName', '') || translate('common.hidden');
+    displayNameOrLogin = Str.removeSMSDomain(getMentionDisplayText(displayNameOrLogin, htmlAttributeAccountID, lodashGet(user, 'login', '')));
```

**Comment by nkdengineer** [comment] 2024-03-25 11:00
@sobitneupane I think we can use `getDisplayNameOrDefault` with adding `shouldPriozitizeLogin` param before calling `getMentionDisplayText` and every thing will work well because if `userLogin !== displayText` that mean `getDisplayNameOrDefault` return the displayName of user (the case personal detail doesn't have login) otherwise everything logic below is already correct.

**Comment by ahmedGaber93** [comment] 2024-03-25 11:35
@sobitneupane 
> I believe following code will do the job.

Yes, I think this shorthand format is better 👍.
`LocalePhoneNumber.formatPhoneNumber(lodashGet(user, 'login', ''))` will work as `formatedPhoneNumber || login`.

We can also use [getDisplayNameOrDefault](https://github.com/Expensify/App/blob/a35ccc68b4b889a182501d406b8dc0dfca525f32/src/libs/PersonalDetailsUtils.ts#L28) instead of `lodashGet(user, 'displayName', '') || translate('common.hidden');` to clean displayName
```javascript
displayNameOrLogin = LocalePhoneNumber.formatPhoneNumber(lodashGet(user, 'login', '')) || PersonalDetailsUtils.getDisplayNameOrDefault(user);
displayNameOrLogin = Str.removeSMSDomain(getMentionDisplayText(displayNameOrLogin, htmlAttributeAccountID, lodashGet(user, 'login', '')));

```

**Comment by sobitneupane** [comment] 2024-03-25 11:41
@ahmedGaber93 Can you please update your proposal accordingly.

**Comment by sobitneupane** [comment] 2024-03-25 11:43
@nkdengineer I don't think we will need to add `shouldPriozitizeLogin` for now as we will always prioritize login as discussed [here](https://github.com/Expensify/App/issues/38079#issuecomment-2014623920)

**Comment by ahmedGaber93** [comment] 2024-03-25 11:44
## Proposal
[Updated](https://github.com/Expensify/App/issues/38079#issuecomment-1990120462)

**Comment by nkdengineer** [comment] 2024-03-25 14:20
@sobitneupane `getDisplayNameOrDefault` is not only used for mention but also used for many other places in the app so we shouldn't always prioritize login in this function, for example in `ProfileAvatar` page, we should display the display name as title of `AttachmentModal` or in suggestion mention, the text and alternateText will be duplicated if we do this and it can occur many other cases since it's used in many places of the app.


https://github.com/Expensify/App/blob/3d780639eb260c1165e884032f4a92aa7dbbb4ca/src/pages/home/report/ReportActionCompose/SuggestionMention.tsx#L197-L198

<img width="302" alt="Screenshot 2024-03-25 at 21 20 22" src="https://github.com/Expensify/App/assets/161821005/ce2d0d4f-f31f-451b-922b-92f18beb3180">

**Comment by sobitneupane** [comment] 2024-03-25 14:34
> `getDisplayNameOrDefault` is not only used for mention but also used for many other places in the app so we shouldn't always prioritize login in this function,

Yup. Change is not required in `getDisplayNameOrDefault` at all.

**Comment by puneetlath** [comment] 2024-03-25 15:30
When can you have a PR up @ahmedGaber93?

**Comment by ahmedGaber93** [comment] 2024-03-25 15:34
@puneetlath PR will be ready in few hours.

**Comment by ahmedGaber93** [comment] 2024-03-25 19:51
@sobitneupane PR https://github.com/Expensify/App/pull/38957 is ready for review.

**Comment by adelekennedy** [comment] 2024-04-15 16:17
**Payouts due:**

- [ ] Contributor: $500 @ahmedGaber93 (Upwork)
- [ ] Contributor+: $500 @sobitneupane (NewDot)

Upwork job is [here](https://www.upwork.com/jobs/~01c8171385c92b3a6a).

**Comment by adelekennedy** [comment] 2024-04-15 16:17
Payment summary above - just pending checklist if relevant!

**Comment by puneetlath** [comment] 2024-04-17 20:48
@sobitneupane bump on the checklist.

**Comment by adelekennedy** [comment] 2024-04-22 14:58
@sobitneupane will you complete the checklist today so we can close?

**Comment by sobitneupane** [comment] 2024-04-24 07:50
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/36998
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/36998#issuecomment-2074303542
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2024-04-24 07:53
**Regression Test Proposal:**

1. Open any room
2. Mention someone who is not the room
3. Notice the "actionable whisper" message
4. Verify that login is displayed both in mention and actionable whisper.

**Comment by adelekennedy** [comment] 2024-04-24 19:50
@sobitneupane Thank you!

https://github.com/Expensify/Expensify/issues/390576

**Closed by adelekennedy** 2024-04-24 19:50 UTC
Labels: External, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-05-12 19:13
$500 approved for @sobitneupane
