### ISSUE TITLE
[$250] [Simplified Collect][More features] Unable to toggle on a feature when second tab is open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38897] opened 2024-03-24 19:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/37902
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is admin of Collect workspace.
- The Collect workspace has at least one feature that is disabled in More features.
1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to More features.
4. Open the same page in Step 3 in a second tab and refresh the second tab.
5. In the first tab, toggle on a disabled feature.
6. Note that it is toggled back off and it shows not here page in the first tab.
7. Close the second tab.
8. Refresh the first tab.
9. Toggle on the disabled feature.
10. Note that now the feature can be toggled on without issue.

## Expected Result:
In Step 5, app should successfully toggle on a disabled feature in the first tab when the second tab of the same page is open.

## Actual Result:
In Step 5, when the second tab of the same page is open. app prevents from toggling on a disabled feature from the first tab.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4d2030e4-e06f-4940-9561-f5d8a4474d41

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ac2f7c8241fff900</li>
        <li>Upwork Job ID: 1772285151075995648</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-24 19:44
We think that this bug might be related to #wave-control

**Comment by kbecciv** [comment] 2024-03-24 19:51
We think that this bug might be related to #wave-control

**Comment by luacmartins** [comment] 2024-03-25 15:31
I can take over since this is related to Simplified Collect. I'll demote this to NAB though since customers don't have access to this yet.

**Comment by trjExpensify** [comment] 2024-03-25 22:09
Open for proposals from the community here!

**Comment by luacmartins** [comment] 2024-03-27 17:31
Still looking for a volunteer. Tagging @allroundexperts @DylanDylann @rezkiy37 @shubham1206agra since you all worked on `More features` issues and might have some context.

**Comment by rezkiy37** [comment] 2024-03-27 17:35
Sorry, I don't have the capacity to take the issue now. Can you confirm that the app used the staging server? I assume the production server is not ready to manipulate these toggles.
cc @waterim

**Comment by waterim** [comment] 2024-03-28 08:46
I can take this!

**Comment by ArekChr** [comment] 2024-03-28 09:24
It seems this bug appears to be no longer reproducible

**Comment by luacmartins** [comment] 2024-03-28 17:38
Agree! I couldn't reproduce in dev anymore. Staging is still not updating in real time, but I think that'll be fixed with the next deploy. Gonna close this one. Thanks for the help everyone!

https://github.com/Expensify/App/assets/22219519/20f465e0-bf94-45dc-80b5-af44e269afb0

**Closed by luacmartins** 2024-03-28 17:38 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
