### ISSUE TITLE
[HOLD for payment 2023-11-17] [$125] [Form Provider Refactor] KnowATeacherPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30308] opened 2023-10-24 23:38 UTC
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/TeachersUnite/KnowATeacherPage.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b8e43ae5ee47bc1</li>
        <li>Upwork Job ID: 1716962423981568000</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by cdOut** [comment] 2023-10-25 11:07
Hello, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I would like to work on this task.

**Comment by Samueljh1** [comment] 2023-10-25 21:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We need to refactor Form inputs based on the new `FORMS.md` specification.

### What is the root cause of that problem?
The current component is outdated and needs to be refactored.

### What changes do you think we should make in order to solve the problem?
(From FORMS.md): All form inputs need to be wrapped in [InputWrapper](https://github.com/Expensify/App/blob/029d009731dcd3c44cd1321672b9672ef0d3d7d9/src/components/Form/InputWrapper.js) and passed as `InputComponent` property additionally it's necessary po pass an unique `inputID`. All other props of the input can be passed as `InputWrapper` props.
```jsx
<InputWrapper
    // `InputWrapper` required props
    InputComponent={TextInput}
    inputID="uniqueTextInputID"
    // `TextInput` specific props
    placeholder="Text input placeholder"
    label="Text input label"
    shouldSaveDraft
/>
```

**Comment by luacmartins** [comment] 2023-10-25 21:56
@Samueljh1 thanks for the proposal. We already have @cdOut working on it though.

**Comment by Samueljh1** [comment] 2023-10-25 22:06
> @Samueljh1 thanks for the proposal. We already have @cdOut working on it though.

My bad, didn't see the usual proposal stuff here so missed it.

**Comment by stephanieelliott** [comment] 2023-11-06 21:55
PR is undergoing QA

**Comment by stephanieelliott** [comment] 2023-11-13 15:54
PR was merged to production on 11/10, updating title to reflect 7 day hold

**Comment by stephanieelliott** [comment] 2023-11-20 12:12
Summarizing payment on this issue: 

 - Issue reporter: N/A
 - Contributor: @cdOut no payment due (expert contrib)
 - Contributor+: @aimane-chnaif $125 via Upwork -- contract was extended to you, can you please accept when you get a chance?
 
 Upwork job is [here](https://www.upwork.com/jobs/~017b8e43ae5ee47bc1)

**Comment by stephanieelliott** [comment] 2023-11-28 03:21
All paid!

**Closed by stephanieelliott** 2023-11-28 03:21 UTC
Labels: Reviewing, External, Weekly, Bug
