### ISSUE TITLE
[HOLD for payment 2023-07-06] [$250] Migrate ImageWithSizeCalculation.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16167] opened 2023-03-20 08:38 UTC
### Filenames
- [ ] [src/components/ImageWithSizeCalculation.js](https://github.com/Expensify/App/blob/main/src/components/ImageWithSizeCalculation.js)
    - **type:** `React.PureComponent`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019290e3ea81f50f59</li>
        <li>Upwork Job ID: 1664694167941718016</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-04-25 22:48
Gonna take this one off hold since worked through the other issue you were assigned and looks like there is a draft PR already for this.

**Comment by thienlnam** [comment] 2023-04-27 22:22
Went back to this, there seems to be an underlying problem with refactoring this to use hooks unless I am missing something completely.

onLoadStart keeps getting called on state change, I wonder if I need to update the Image component as well

**Comment by thienlnam** [comment] 2023-06-02 17:46
Dropping this so someone else can work on it as I focus on task cleanup

**Comment by marcaaron** [comment] 2023-06-02 18:04
Making this one External as per https://expensify.slack.com/archives/C01GTK53T8Q/p1685727842949549

**Comment by Uzayn** [comment] 2023-06-02 18:31
## Proposal: Migrate `ImageWithSizeCalculation` to a Function Component

### Problem Statement
The current codebase includes a class component called `ImageWithSizeCalculation` that needs to be migrated to a function component. However, during the migration process, an issue arises where the `onLoadStart` event is triggered on state changes, leading to unexpected behavior. 

### Root Cause of the Problem
The issue is caused by the nature of function components and how they handle event callbacks. Unlike class components, function components create new instances of event callbacks on every render. This can lead to unintended behavior, such as triggering events multiple times on state changes.

### Proposed Solution

1. In the function component, wrap the event callback functions (`imageLoadingStart`, `imageLoadingEnd`, `onError`, `imageLoadedSuccessfully`) with the `useCallback` hook. This hook memoizes the event callbacks and ensures they remain the same across renders unless their dependencies change.

2. Update the usage of event callbacks in the JSX to use the memoized versions returned by the `useCallback` hook.

3. If the issue persists after applying `useCallback`, I'll consider updating the `Image` component or its related code to ensure proper handling of event callbacks and state changes. Analyze the `Image` component and its dependencies to identify any potential issues that could cause the `onLoadStart` event to be triggered on state changes.

### Alternative Solutions (Optional)
None

**Comment by Vishrut19** [comment] 2023-06-02 18:47
Here is my proposal

## Proposal : Migrate `ImageWithSizeCalculation.js` to function component #16167

### Please re-state the problem that we are trying to solve in this issue.

Problem : Migrate `ImageWithSizeCalculation.js` to function component #16167

### What is the root cause of that problem?

The root cause of the problem is that most of the things written are in class based which needs to be converted into function based as the updated ReactJS syntax.

### What changes do you think we should make in order to solve the problem?

Before This is class based code:

```
class ImageWithSizeCalculation extends PureComponent {
    constructor(props) {
        super(props);

        this.state = {
            isLoading: false,
        };

        this.imageLoadingStart = this.imageLoadingStart.bind(this);
        this.imageLoadingEnd = this.imageLoadingEnd.bind(this);
        this.onError = this.onError.bind(this);
        this.imageLoadedSuccessfully = this.imageLoadedSuccessfully.bind(this);
    }

    onError() {
        Log.hmmm('Unable to fetch image to calculate size', {url: this.props.url});
    }

    imageLoadingStart() {
        // Return early if the image has already loaded (this can happen when uploading the same image twice on Android)
        if (this.isLoaded) {
            return;
        }
        this.setState({isLoading: true});
    }

    imageLoadingEnd() {
        this.setState({isLoading: false});
    }

    imageLoadedSuccessfully(event) {
        this.isLoaded = true;
        this.props.onMeasure({
            width: event.nativeEvent.width,
            height: event.nativeEvent.height,
        });
    }

    render() {
        return (
            <View style={[styles.w100, styles.h100, this.props.style]}>
                <Image
                    style={[styles.w100, styles.h100]}
                    source={{uri: this.props.url}}
                    isAuthTokenRequired={this.props.isAuthTokenRequired}
                    resizeMode={Image.resizeMode.cover}
                    onLoadStart={this.imageLoadingStart}
                    onLoadEnd={this.imageLoadingEnd}
                    onError={this.onError}
                    onLoad={this.imageLoadedSuccessfully}
                />
                {this.state.isLoading && <FullscreenLoadingIndicator style={[styles.opacity1, styles.bgTransparent]} />}
            </View>
        );
    }
}

```

After (new function based code):

```
import React, { useState, useRef } from 'react';
import { View, Image } from 'react-native';

const ImageWithSizeCalculation = (props) => {
  const [isLoading, setIsLoading] = useState(false);
  const isLoaded = useRef(false);

  const onError = () => {
    Log.hmmm('Unable to fetch image to calculate size', { url: props.url });
  };

  const imageLoadingStart = () => {
    // Return early if the image has already loaded (this can happen when uploading the same image twice on Android)
    if (isLoaded.current) {
      return;
    }
    setIsLoading(true);
  };

  const imageLoadingEnd = () => {
    setIsLoading(false);
  };

  const imageLoadedSuccessfully = (event) => {
    isLoaded.current = true;
    props.onMeasure({
      width: event.nativeEvent.width,
      height: event.nativeEvent.height,
    });
  };

  return (
    <View style={[styles.w100, styles.h100, props.style]}>
      <Image
        style={[styles.w100, styles.h100]}
        source={{ uri: props.url }}
        isAuthTokenRequired={props.isAuthTokenRequired}
        resizeMode={Image.resizeMode.cover}
        onLoadStart={imageLoadingStart}
        onLoadEnd={imageLoadingEnd}
        onError={onError}
        onLoad={imageLoadedSuccessfully}
      />
      {isLoading && <FullscreenLoadingIndicator style={[styles.opacity1, styles.bgTransparent]} />}
    </View>
  );
};

export default ImageWithSizeCalculation;



```



### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by nhminhduc** [comment] 2023-06-02 18:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Refactor class base component [ImageWithSizeCalculation.js](https://github.com/Expensify/App/blob/main/src/components/ImageWithSizeCalculation.js) to functional component
### What is the root cause of that problem?
It seems like the previous PR function trigger everytime the state change, this is because functional component react run from top to bottom everytime state change, unless there is something tell React not to initiate the function. That is when useCallback hooks come into play.
### What changes do you think we should make in order to solve the problem?
New code
```
import React, { useState, useCallback, useEffect } from 'react';
import { View } from 'react-native';
import PropTypes from 'prop-types';
import Log from '../libs/Log';
import styles from '../styles/styles';
import FullscreenLoadingIndicator from './FullscreenLoadingIndicator';
import Image from './Image';

const ImageWithSizeCalculation = ({ url, style = {}, onMeasure = () => { }, isAuthTokenRequired = false }) => {
    const [isLoading, setIsLoading] = useState(false);
    const [isLoaded, setIsLoaded] = useState(false);

    const onError = useCallback(() => {
        Log.hmmm('Unable to fetch image to calculate size', { url: url });
    }, [url]);

    const imageLoadingStart = useCallback(() => {
        if (isLoaded) {
            return;
        }
        setIsLoading(true);
    }, [isLoaded]);

    const imageLoadingEnd = useCallback(() => {
        setIsLoading(false);
    }, []);

    const imageLoadedSuccessfully = useCallback((event) => {
        setIsLoaded(true);
        onMeasure({
            width: event.nativeEvent.width,
            height: event.nativeEvent.height,
        });
    }, [onMeasure]);

    return (
        <View style={[styles.w100, styles.h100, style]}>
            <Image
                style={[styles.w100, styles.h100]}
                source={{ uri: url }}
                isAuthTokenRequired={isAuthTokenRequired}
                resizeMode={Image.resizeMode.cover}
                onLoadStart={imageLoadingStart}
                onLoadEnd={imageLoadingEnd}
                onError={onError}
                onLoad={imageLoadedSuccessfully}
            />
            {isLoading && <FullscreenLoadingIndicator style={[styles.opacity1, styles.bgTransparent]} />}
        </View>
    );
}

ImageWithSizeCalculation.propTypes = {
    url: PropTypes.string.isRequired,
    style: PropTypes.any,
    onMeasure: PropTypes.func,
    isAuthTokenRequired: PropTypes.bool,
};

ImageWithSizeCalculation.defaultProps = {
    style: {},
    onMeasure: () => { },
    isAuthTokenRequired: false,
};

export default ImageWithSizeCalculation;
```
### What alternative solutions did you explore? (Optional)

**Comment by Vishrut19** [comment] 2023-06-02 19:47
Hey!I have applied on Upwork for this issue.

**Comment by Vishrut19** [comment] 2023-06-02 19:48
> @Vishrut19 please check this comment [#16167 (comment)](https://github.com/Expensify/App/issues/16167#issuecomment-1574152338)

okay! So that means i cannot be assigned on this issue?

**Comment by Vishrut19** [comment] 2023-06-02 19:53
cannot see this thread
<img width="1303" alt="Screenshot 2023-06-03 at 1 22 38 AM" src="https://github.com/Expensify/App/assets/53470896/05c4e90d-e64a-4a04-9613-7b6b476406e0">

**Comment by Vishrut19** [comment] 2023-06-02 20:00
> @Vishrut19 this is a great thread to understand the process
> 
> https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119

@getusha Thanks great thread!

**Comment by NikkiWines** [comment] 2023-06-05 15:08
Sorry for the delay here! @getusha assigning this one to you 🚀

**Comment by conorpendergrast** [comment] 2023-06-09 18:49
Looks like PR is still waiting for review here

**Comment by conorpendergrast** [comment] 2023-06-14 12:48
PR is still waiting for @0xmiroslav and @NikkiWines to review. 

I've sent offers [via Upwork](https://www.upwork.com/ab/applicants/1664694167941718016/offers)!

**Comment by conorpendergrast** [comment] 2023-06-16 14:20
PR still waiting for review

**Comment by conorpendergrast** [comment] 2023-06-22 12:29
New PR is up and waiting for review now

**Comment by conorpendergrast** [comment] 2023-07-06 10:04
Paid @getusha and @0xmiroslav. And we're done! Closing

**Closed by conorpendergrast** 2023-07-06 10:04 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment
