### ISSUE TITLE
Settings - Crash when trying to navigate to settings/preferences

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23073] opened 2023-07-18 12:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Login with any account
3. On home tab, select profile icon to open settings page
4. Tap on ''Preferences''

## Expected Result:
The app should not crash when accessing settings/preferences

## Actual Result:
When attempting to access preferences under settings, the web app crashes every time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/154a27fc-97d7-44c9-903e-d3446f73092c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Interanal Team

**Slack conversation:**

**Comment by mountiny** [comment] 2023-07-18 15:00
Seems like this is also related to this PR https://github.com/Expensify/App/pull/21852/files and there is one more blocker tied to it https://github.com/Expensify/App/pull/21852/files

Since there are 2 blockers maybe it would be worth reverting

**Comment by pac-guerreiro** [comment] 2023-07-18 15:06
I'm unable to reproduce this on my iPhone 14 Plus, using Safari

**Comment by roryabraham** [comment] 2023-07-18 17:41
I am just starting today but would love the opportunity to try to fix the blockers rather than reverting https://github.com/Expensify/App/pull/21852/files

**Comment by roryabraham** [comment] 2023-07-18 18:48
What device was this on?

**Comment by jasperhuangg** [comment] 2023-07-18 20:34
@roryabraham it looks like it's on mWeb Safari on an actual iOS device

**Comment by roryabraham** [comment] 2023-07-19 00:05
I haven't observed this before on my iPhone 14 Pro or any simulators. However, in [this PR](https://github.com/Expensify/App/pull/23145) I discovered that sometimes Lottie was not cleaning up after itself and would leave an invisible animation running in the background forever, which inhibited basic browser APIs such as `requestIdleCallback` from running as expected.

I'm cautiously optimistic that after we deploy the fix for that this crash may no longer be reproducible

**Comment by jasperhuangg** [comment] 2023-07-19 02:08
We are CPing a fix for this, I'll retest this once the CP is on staging

**Comment by jasperhuangg** [comment] 2023-07-19 02:52
Retested on staging and this looks like it isn't happening anymore, closing!

**Closed by jasperhuangg** 2023-07-19 02:52 UTC
Labels: DeployBlockerCash, Engineering, Hourly
