### ISSUE TITLE
[$500] when adding amount details to a failed smartscan, default currency isn’t local

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33258] opened 2023-12-18 22:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dylanexpensify 
**Slack conversation:**

## Action Performed:

1. Head to any chat
2. Create request money
3. Choose Scan with faulty picture (e.g. a book)
4. Wait till scan fails
5. Click on the Amount details required

## Expected Result:
the amount to input would default to your local currency

## Actual Result:
the amount to input defaults to USD$

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/12b42847-8b4e-4bef-bf42-19c9f8bbfd08

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01afd06e1036c5deb0</li>
        <li>Upwork Job ID: 1736882015099211776</li>
        <li>Last Price Increase: 2023-12-25</li>
<li>Automatic offers: </li>
<ul>
<li>wlegolas | Contributor | 28076000</li>
</ul></li>
    </ul>
</details>

**Comment by wlegolas** [comment] 2023-12-19 01:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

when adding amount details to a failed smartscan, default currency isn’t local

### What is the root cause of that problem?

The component `CurrencySymbolButton` receives the property `currencySymbol` to show the currency symbol, this information comes from the `EditRequestPage` component. The `EditRequestPage` component uses the method `ReportUtils.getTransactionDetails` to retrieve the transaction details and one of the information is `currency`. 

https://github.com/Expensify/App/blob/19ca74491ec7dc60bf8e3103058add651964533c/src/pages/EditRequestPage.js#L78-L85

To retrieve the currency, is used the methods from `ReportUtils` file: `getTransactionDetails` -> `getCurrency`, in the `getCurrency` there is a logic to retrieve the currency from the transaction object, and the value returned from the method `getCurrency` will be the information from the transaction property `modifiedCurrency` that has the default currency when the scanning fails.

https://github.com/Expensify/App/blob/19ca74491ec7dc60bf8e3103058add651964533c/src/libs/TransactionUtils.ts#L280-L286


### What changes do you think we should make in order to solve the problem?

We should change the `getCurrency` to verify if the transaction has an error, if so, we need to get the currency from the `currency` property in the transaction object.

For example:

```js
function getCurrency(transaction: OnyxEntry<Transaction>): string {
    const currency = transaction?.modifiedCurrency ?? '';
    const hasFieldErrors = hasMissingSmartscanFields(transaction);

    if (hasFieldErrors || _.isEmpty(currency)) {
        return transaction?.currency ?? CONST.CURRENCY.USD;
    }

    return currency;
}
```

### What alternative solutions did you explore? (Optional)

N/A

**POC**

https://dev.new.expensify.com:8082/r/5473945671459503

**Comment by Tony-MK** [comment] 2023-12-19 01:21
This just needs a simple backend fix because once the scan fails, it sets the `transaction.modifiedCurrency` from `''` to `USD` by the server. Also, the `transaction.currency` remains unchanged. 

Check whether the backend is setting the `transaction.modifiedCurrency` to `USD`. 

@rushatgabhane, could you confirm this?

**Comment by Victor-Nyagudi** [comment] 2023-12-21 05:41
Not exactly the same, but the currency is changed from the local one to USD here too, so I thought it good to mention the issue for reference sake. 

- https://github.com/Expensify/App/issues/29709

**Comment by lschurr** [comment] 2023-12-22 19:36
Bump on this one @rushatgabhane

**Comment by lschurr** [comment] 2023-12-26 20:52
@rushatgabhane - any update here?

**Comment by lschurr** [comment] 2023-12-29 17:45
Bumped in Slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1703871901016549

**Comment by rushatgabhane** [comment] 2023-12-29 17:51
@wlegolas 's proposal LGTM https://github.com/Expensify/App/issues/33258#issuecomment-1861932910
🎀 👀 🎀

**Comment by aldo-expensify** [comment] 2024-01-02 14:53
hmm, @Tony-MK that is a good point, but I think that change would affect also the Old website leaving the currency empty, and that may break things there.

**Comment by Tony-MK** [comment] 2024-01-02 19:01
Sorry, I didn't know that. 
Good job @wlegolas. You deserve it. 
Thanks @aldo-expensify 😄

**Comment by wlegolas** [comment] 2024-01-02 22:28
Hi everyone, I created the PR with the changes https://github.com/Expensify/App/pull/33853

If you have any questions or suggestions, please let me know.

**Comment by aldo-expensify** [comment] 2024-01-29 18:15
This still stuck on me, I have done some progress in reproducing the original problem in dev. The Expensiwork/smartscan was a bit tricky to get to work.

I need to do more testing to decide where is the best place to fix this (backend/frontend).

**Comment by wlegolas** [comment] 2024-02-06 23:36
Hi @aldo-expensify did you have time to execute your tests to check the better place to fix this issue?

If there is something that I can help, please let me know.

**Comment by aldo-expensify** [comment] 2024-02-07 00:15
I found the code in the backend where we are setting the `modifiedCurrency` when smartscan fails and it is new code that was introduced for the new app. I don't think this behaviour existed for the Old app and it seems like a bug introduced by mistake. So I still think the right fix would be to stop setting the `modifiedCurrency` incorrectly instead of ignoring the bad currency in the frontend.


This issue is kind of low priority, so I have been getting pulled to other higher priority issues.

I think what we should do is:

- I finds the right fix in the backend, and we close your PR
- Pay you something (half?) because you still spent some time investigating, coding and testing your solution.

These don't have to necessarily happen in that order.

**Comment by wlegolas** [comment] 2024-02-16 11:48
> I found the code in the backend where we are setting the `modifiedCurrency` when smartscan fails and it is new code that was introduced for the new app. I don't think this behaviour existed for the Old app and it seems like a bug introduced by mistake. So I still think the right fix would be to stop setting the `modifiedCurrency` incorrectly instead of ignoring the bad currency in the frontend.
> 
> This issue is kind of low priority, so I have been getting pulled to other higher priority issues.
> 
> I think what we should do is:
> 
> * I finds the right fix in the backend, and we close your PR
> * Pay you something (half?) because you still spent some time investigating, coding and testing your solution.
> 
> These don't have to necessarily happen in that order.

Hi @aldo-expensify thank you for sharing your results. 

If the fix should be done by the backend, for me doesn't have a problem, I don't know how it's the process (just close the PR or pay something for my time), so I leave it open to you to understand the best way to close this issue.

**Comment by aldo-expensify** [comment] 2024-04-16 18:19
Not resolved yet!

**Comment by aldo-expensify** [comment] 2024-06-26 19:40
Reopening for handling some payment for @wlegolas for the work done in the PR: https://github.com/Expensify/App/pull/33853 (even if it wasn't merged because we preferred a backend solution in the end)

**Comment by lschurr** [comment] 2024-06-26 19:50
Payment summary:

We agreed to pay half of the original job price since the PR wasn't merged but the job was assigned and @wlegolas put work into it.

- Contributor: $250 @wlegolas ([Offer sent in Upwork](https://www.upwork.com/nx/wm/offer/102891256))

**Comment by rushatgabhane** [comment] 2024-06-26 19:55
@lschurr me too please, i had reviewed the issue and PR

**Comment by lschurr** [comment] 2024-06-26 20:01
Ah, thanks @rushatgabhane. I'll add you to the payment summary

**Comment by lschurr** [comment] 2024-06-27 00:18
All set.

**Closed by lschurr** 2024-06-27 00:18 UTC
Labels: Reviewing, Daily, Internal, Not a priority, Bug

**Comment by JmillsExpensify** [comment] 2024-06-28 17:55
$250 approved for @rushatgabhane

**Comment by wlegolas** [comment] 2024-06-28 21:46
Hi folks.

Thank you so much for giving me this payment ❤️
