### ISSUE TITLE
[$500] Web - Login - Error page is displayed after changing the long URL to staging and go to it

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29849] opened 2023-10-18 09:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR:** https://github.com/Expensify/App/pull/28984

**Version Number:** 1.3.86-1

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
Pre-requisite: user must be logged in with account A on expensify.com and account B on new.expensify.com

1. With account B on expensify.com go to Support and select Concierge.
2. A new tab will open with a long URL, copy it.
3. Change the URL to staging.new.expensify.com and go to it.

## Expected Result:
User A should be successfully logged in to ND with no error pages displayed.

## Actual Result:
User A is logged in but there is an error page displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/8519be39-4268-4103-99e1-f9026b9b0edf

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b109095a56a932b9</li>
        <li>Upwork Job ID: 1714580146381455361</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27258677</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-18 09:52
Not reproducible in production

https://github.com/Expensify/App/assets/115492554/63fb98a7-b6e9-49bb-9217-af4db9fb317f

**Comment by koko57** [comment] 2023-10-18 12:09
yes, it's also reproducible locally. Not sure why the id for Concierge chat changes to the id for Concierge chat from the previously log out account 
![Screenshot 2023-10-18 at 14 05 02](https://github.com/Expensify/App/assets/28020445/cea3481f-8175-4f11-8428-6f55653577c1)
![Screenshot 2023-10-18 at 14 03 48](https://github.com/Expensify/App/assets/28020445/9fa14d80-2c91-41ae-bb71-68267faaa000)
![Screenshot 2023-10-18 at 14 03 33](https://github.com/Expensify/App/assets/28020445/551caadf-1dee-4bce-8faf-bb0244b16376)
![Screenshot 2023-10-18 at 14 03 39](https://github.com/Expensify/App/assets/28020445/fac30365-6ad1-4b0f-a3e0-3dc3fcafc25d)

it tested well before merging [my PR](https://github.com/Expensify/App/pull/28984), so maybe some other changes were introduced that caused the issue with mine

I'll investigate it

**Comment by mountiny** [comment] 2023-10-18 12:48
Thanks for investigating, maybe we can also confirm if revert fixes this, there could be some other change

**Comment by mountiny** [comment] 2023-10-18 12:49
I think the steps should say `With account A on expensify.com go to Support and select Concierge.` right?

**Comment by koko57** [comment] 2023-10-18 13:04
reverting my changes gives me totally black screen - not like in the issue I tried to fix (an empty sidebar and green background)
![Screenshot 2023-10-18 at 15 03 45](https://github.com/Expensify/App/assets/28020445/d99a8d41-f352-4a54-a7f5-a05b0b1b6260)

**Comment by Beamanator** [comment] 2023-10-18 17:41
Hey @koko57 - has there been any more investigation in the last 4 hours? 😅 I didn't see that I am assigned to look into this as well 😳

**Comment by koko57** [comment] 2023-10-18 17:49
When I removed demoInfo key from withOnyx in AuthScreens (with my changes reverted) I got the same outcome as in the issue I was fixing (green background, empty sidebar). Then I restored the changes and noticed that at first the user is redirected to the correct chat (the one with id from the transition url) but right afterwards there's redirection to this improper chat. I haven't found the reason why this happens. I'll continue investigating it tomorrow

**Comment by francoisl** [comment] 2023-10-18 18:44
Discussed in Slack [in this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1697623266522859), this is an edge case so we'll not block the deploy for this. 
I also got a crash on production when I tried to reproduce this, so there might be an issue there anyway.

**Comment by koko57** [comment] 2023-10-19 10:54
Reverting this empty string to null in this line fixes the issue 😃 
https://github.com/Expensify/App/blob/eb5fec2c258e74a69bbed9d93100db4b30b265ec/src/pages/home/ReportScreen.js#L130
and seems that it doesn't introduce any regression.
However, it only unveiled some other problems with the transition. Starting working on my proposal

**Comment by koko57** [comment] 2023-10-20 12:47
Still working on it. I will continue on Monday.

**Comment by koko57** [comment] 2023-10-20 16:04
I've merged with the latest main and '' in this line https://github.com/Expensify/App/blob/b20766bc58a49c86d0f55cff1096e8c01636a2c1/src/pages/home/ReportScreen.js#L130-L131 was changed back to null so locally there's no problem with the transtition. 

https://github.com/Expensify/App/assets/28020445/1f4ca1c8-87cd-4684-8489-52ff3ab1ee5a

for the transition to staging there's still a problem, but it's because this [PR](https://github.com/Expensify/App/pull/29893) hasn't been deployed to staging yet.

**Comment by mountiny** [comment] 2023-10-20 16:48
@koko57 thank you! would you be able to make a new PR?

**Comment by koko57** [comment] 2023-10-20 17:06
@mountiny do we need a new PR here? This [PR](https://github.com/Expensify/App/pull/29893) fixes this

**Comment by mountiny** [comment] 2023-10-20 17:46
ah yes sorry I forgot we did not end up reverting your PR, so then we are all good

**Comment by Beamanator** [comment] 2023-10-23 08:08
Ok so we can close this one out, yeah?

**Closed by Beamanator** 2023-10-23 08:08 UTC
Labels: External, Engineering, Daily, Bug
