### ISSUE TITLE
[HOLD for payment 2023-10-05] [$500] Web - Focus Border is not disappearing on Click

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26431] opened 2023-08-31 20:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat, hover over a chat to get popup with menu items.
2. Use Tab/f11 to navigate to that element.
3. Once it's on Focus click on it, Click multiple times, Click on neighbouring elements,

## Expected Result:
Border should be disappeared after clicking

## Actual Result:
Border is not disappeared even clicking

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/17c795e5-51cc-4b22-836b-467bc69169c2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Charan-hs
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693035839221489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165692f1106821d38</li>
        <li>Upwork Job ID: 1699153497359552512</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 26739286</li>
<li>Charan-hs | Reporter | 26739289</li>
</ul></li>
    </ul>
</details>

**Comment by AJV009** [comment] 2023-08-31 21:03
I am not sure if this is an error because you see as soon as you move the mouse out of the message the circle goes away, right?

**Comment by johncschuster** [comment] 2023-09-05 20:34
Not overdue. This was just triaged, Melv.

**Comment by ArekChr** [comment] 2023-09-06 08:10
@DylanDylann I think `document.activeElement` can be used only in `index.website.js` files, so this should be a separate function or maybe is another way to blur the active element?

**Comment by DylanDylann** [comment] 2023-09-06 08:39
> * e.preventDefault()
As my first solution, we can remove the e.preventDefault()

**Comment by DylanDylann** [comment] 2023-09-06 09:39
@ArekChr 
I just tested on the Desktop and saw that document.activeElement.blur(); work well as below video
https://github.com/Expensify/App/assets/141406735/0d1c3bc2-3912-4b0f-9456-c254d6093f52

So that, If we come up with  this solution we need to define a new function for native and web/desktop separately

**Comment by getusha** [comment] 2023-09-06 12:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Focused outline is not dismissed on click
### What is the root cause of that problem?
In

https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/components/BaseMiniContextMenuItem.js#L56

We have `e.preventDefault()` which prevents the default behavior of blurring and transferring the focus to the clicked target element, which makes it preserve the previously focused element.

In first place the `e.preventDefault()` was added to avoid the composer being blurred when we click on the emoji inside mini context menu. which was introduced here https://github.com/Expensify/App/pull/24252 aiming to solve https://github.com/Expensify/App/issues/20079
### What changes do you think we should make in order to solve the problem?

 we should call `e.preventDefault()` only if the focused element is not an input. this will make sure we fix this issue without re-introducing https://github.com/Expensify/App/issues/20079

It will be something like this.
```js
onMouseDown={(e) => {
     if (!['TEXTAREA', 'INPUT'].includes(DomUtils.getActiveElement())) { return; }
     e.preventDefault()
}}
```

Since we are using DomUtils.getActiveElement it won't be necessary to separate the files.
https://github.com/Expensify/App/blob/57b76067cd3d7b59e84c4a387d11ad33e6a97d05/src/libs/DomUtils/index.js#L5-L7

We can also utilize `blurActiveElement` if we decided to manually blur the focus.

<details>
<summary>
Result
</summary>

https://github.com/Expensify/App/assets/75031127/4edcf683-fbd4-4014-8b5a-e49d2f84bcde
</details>


### What alternative solutions did you explore? (Optional)
N/A

cc @ArekChr

**Comment by DylanDylann** [comment] 2023-09-06 14:36
@ArekChr Updated proposal https://github.com/Expensify/App/issues/26431#issuecomment-1706236926. Please help review again. Thanks!

**Comment by getusha** [comment] 2023-09-06 14:50
@DylanDylann you updated your proposal after mine and your solution is also based on my approach.

**Comment by DylanDylann** [comment] 2023-09-06 15:54
@getusha your proposal will check if the current active element is [input, textarea] or not, If not, we will blur the current active elements. My proposal will check if the current active element is exactly the main composer/edit composer or not, if not, we will blur the current active. I want the blur action will affect all the elements except exactly the main composer and the edit composer because we cannot guarantee that there will be other input elements in the future or not

**Comment by getusha** [comment] 2023-09-06 15:56
> @getusha your proposal will check if the current active element is [input, textarea] or not, If not, we will blur the current active elements. My proposal will check if the current active element is exactly the main composer/edit composer or not, if not, we will blur the current active. I want the blur action will affect all the elements except exactly the main composer and the edit composer because we cannot guarantee that there will be other input elements in the future or not


the only difference is that you're using Focus manager which can be suggested by c+, the main proposal is we are triggering e.preventDefault when the composer is not focused, which you updated to it after my proposal.

**Comment by DylanDylann** [comment] 2023-09-06 16:01
@getusha yeah. The GitHub will store the edit history. I just want to make sure this issue is fixed as best as possible.

**Comment by ArekChr** [comment] 2023-09-12 09:26
Hi @DylanDylann, @getusha, please send a new message if you're making significant edits to your original posts. This will help keep everyone on the same page and avoid confusion. Thanks!

**Comment by ArekChr** [comment] 2023-09-12 09:41
@DylanDylann Since we have `DomUtils` with the `getActiveElement` function, we can use that as you suggested in your first proposal. Also, a solution that prevents default behaviour on events works for me. Let's go with your [proposal](https://github.com/Expensify/App/issues/26431#issuecomment-1706236926). as you understood the root cause first and provided a working solution.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by getusha** [comment] 2023-09-12 09:47
@ArekChr
@DylanDylann's proposal was blurring activeElement on click, but after my proposal of adding a condition to the e.preventDefault or blurring depending on the composer focus status, i also mentioned why preventDefault was needed in the first place, that's when he modified his, can you take a look? I am also open for collaboration for a fair decision, Thanks!

**Comment by DylanDylann** [comment] 2023-09-12 09:49
@ArekChr I had updatedd my proposal: My proposal will check if the current active element is exactly the main composer/edit composer or not, if not, we will blur the current active. I want the blur action will affect all the elements except exactly the main composer and the edit composer, because we cannot guarantee that there will be other input elements in the future or not

**Comment by getusha** [comment] 2023-09-12 09:58
@ArekChr 
I mentioned why we need the `e.preventDefault` needed and why we need to preserve it when the composer is focused. the differences between proposals should be significant and not a simple change using the focus manager or checking the active element. please check the times when the proposals were edited.

>Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable.

**Comment by ArekChr** [comment] 2023-09-12 10:30
> after my proposal of adding a condition to the e.preventDefault or blurring depending on the composer focus status

@getusha You are right. I checked that, and there is a regression with composer focus without the conditional blur, which was fixed in the PR you mentioned. Thanks for mentioning that.

@DylanDylann You added that condition after @getusha proposed this in his proposal first.

We should proceed with the @getusha approach.

**Comment by DylanDylann** [comment] 2023-09-12 10:32
@ArekChr yeb. But my proposal  will check if the current active element is exactly the main composer/edit composer or not. @getusha `s proposal just check if the current active element is [input, textarea] or not

**Comment by getusha** [comment] 2023-09-12 10:40
@DylanDylann as i mentioned before, i don't think the difference is important, meaningful or considerable other than change in code snippet, it's the idea of the proposal and the root cause and why we need to preserve the code you suggested to be removed.

I have similar experience before here is a comment about our situation.

>If we get into the nitty gritty, we’ll keep doing a back and forth in the issue which isn’t really effective.
Doing a back and forth in a PR is faster because we can test and reference code.
We stopped code diffs as proposals because of this reason only. To avoid back and forth of small tweaks to a proposal until it’s perfect.

**Comment by ArekChr** [comment] 2023-09-12 10:44
@DylanDylann Yes, although we can't guarantee the presence of other input elements in the future, @getusha's insight was crucial. Without it, @DylanDylann, you might not have modified your original proposal, and we could have ended up with a regression.

@johncschuster Do you think should split payment here?

**Comment by jasperhuangg** [comment] 2023-09-18 19:51
@ArekChr I agree with your opinion on splitting the bounty. Going to wait on @johncschuster's input here.

**Comment by DylanDylann** [comment] 2023-09-26 06:36
We request a review from the internal engineer 2.5 days after being assigned. There are also no changes after that. The timeline lasts because the internal engineer @jasperhuangg forgot to merge PR. So are we eligible for a bonus in this issue?

**Comment by getusha** [comment] 2023-10-13 11:32
@johncschuster this is 1 week overdue, could you also consider [this](https://github.com/Expensify/App/issues/26431?notification_referrer_id=NT_kwDOBHjiV7M3NTcxNDg1OTcxOjc1MDMxMTI3&notifications_after=Y3Vyc29yOjI1#issuecomment-1724273581) before processing the payment?

**Comment by johncschuster** [comment] 2023-10-16 18:30
Discussing in Slack. I'll be back to this shortly!

**Comment by johncschuster** [comment] 2023-10-20 10:34
Ok, I'm back! Thanks for your patience, everyone. I needed to discuss two items:

Should we split the payment?
Is the issue eligible for the bonus?

For the first, I confirmed with @DylanDylann (the assignee) that they are okay with splitting the payment, as I wouldn't feel comfortable with that without their express consent, which I didn't see in the above threads. We spoke in Slack, and they have agreed.

For the second, I spoke with Jasper, and confirmed the timeline mentioned in [this comment](https://github.com/Expensify/App/issues/26431#issuecomment-1734915389). Yes, this issue is eligible for the bonus.

With that in mind, I will be issuing the following payments:
C+ Reviewer: @ArekChr - does not require payment (Contractor)
Contributor that wrote the code/fixed the issue: @DylanDylann - $500 (half of $1000) - paid via Upwork
Contributor that gave crucial insight to help fix the issue: @getusha - $500 (half of $1000) - paid via Upwork
Bug Reporter: @Charan-hs - $50 - paid via Upwork

@getusha, I've invited you to the job directly on Upwork, can you please accept that and ping me when you've done that? Thank you!

**Comment by DylanDylann** [comment] 2023-10-20 10:42
@johncschuster I created PR and updated PR totally and tried to catch up with the timeline. So I think I should receive 100% bonus timeline in this case. (@getusha doesn't take part in PR phrase)

**Comment by getusha** [comment] 2023-10-20 10:43
>@getusha, I've invited you to the job directly on Upwork, can you please accept that and ping me when you've done that? Thank you!

@johncschuster Accepted!

hank you, everyone, for your involvement in this fair decision 🙏

**Comment by johncschuster** [comment] 2023-10-20 11:08
Oh wow, good catch on the math, @DylanDylann! I agree and will adjust.

**Comment by johncschuster** [comment] 2023-10-24 13:03
Ok! I've issued payment to @DylanDylann and @Charan-hs. @getusha, can you accept the proposal in Upwork? I'll issue payment to you as soon as that's done.

Thanks, everyone!

**Comment by getusha** [comment] 2023-10-24 14:14
@johncschuster accepted.

**Comment by johncschuster** [comment] 2023-10-26 19:11
Awesome. Thank you! I'll get payment issued now.

**Comment by johncschuster** [comment] 2023-10-26 19:13
Payment has been issued to @getusha! Thanks for your patience while I worked this out, everyone!

**Comment by johncschuster** [comment] 2023-11-01 14:23
Oh, whoops. I think I forgot to close this one.

@ArekChr, do you think we need regression test steps?

**Comment by ArekChr** [comment] 2023-11-06 10:51
Yes, we can add regression steps here.

**Regression test proposal.**

1. Open chat and hover over a chat to get a popup with menu items.
2. Use Tab/f11 to navigate to that element.
3. Once it's on Focus, click on one of the emojis multiple times.
4. Click another emoji and verify if the hover border from the previous one disappears.

Do we agree :+1: or :-1:

**Comment by johncschuster** [comment] 2023-11-07 21:24
Thanks, @ArekChr! I'll get that regression test issue created shortly.

**Comment by johncschuster** [comment] 2023-11-14 22:47
This is on me. I need to get the regression issue going. Will do that shortly.

**Comment by johncschuster** [comment] 2023-11-22 22:19
Everything is done except the regression test issue. Doing that now.

**Closed** 2023-11-22 22:24 UTC
Labels: External, Daily, Awaiting Payment, Bug
