### ISSUE TITLE
[$500] [Wave 6: Workspace Chats] Category IOU- When deleting IOU request in WS chat, error is shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28966] opened 2023-10-05 22:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Tap on Workspace chat
3. Tap plus icon and select request money
4. Enter an amount
5. Tap next
6. Tap request amount
7. Tap IOU
8. Long tap IOU again to select delete request
9. Tap delete

## Expected Result:
When user tap "delete" request, IOU must be deleted

## Actual Result:
When user tap "delete" request, IOU is not deleted and error message shown under IOU "unexpected error deleting the money request, please try again later"
"Unexpected error deleting the money request, please try again later"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6de3a02a-7ab6-4906-9c14-60ac426b4ccd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015cf957f0fdc69b9a</li>
        <li>Upwork Job ID: 1719032129095122944</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lanitochka17</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lanitochka17</details>

**Comment by mallenexpensify** [comment] 2023-10-06 00:07
@lanitochka17 can you elaborate on 
> Tap on Workspace chat

Is is a room, a 1:1 chat with a member on a workspace?  Thx

**Comment by lanitochka17** [comment] 2023-10-06 13:11
@mallenexpensify You are right, this happens in a Workspace with one member

**Comment by mallenexpensify** [comment] 2023-10-09 16:37
@lanitochka17 I still don't understand how to access the report.  
Also.. it's possible to have an IOU request in a workspace chat room with only 1 person?  You'd just be requesting money from yourself, right?

**Comment by mallenexpensify** [comment] 2023-10-13 22:08
@lanitochka17 when you get a minute can you address the above plz
https://github.com/Expensify/App/issues/28966#issuecomment-1753331187

**Comment by mallenexpensify** [comment] 2023-10-20 00:53
@lanitochka17 👀 above plz

**Comment by lanitochka17** [comment] 2023-10-20 13:36
@mallenexpensify 
First, create a workspace, then make a request for money in this workspace.
Then open the IOU and delete it.

Issue is not reproducible on latest build 1.3.87-8
Samsung Galaxy A50/Android11

https://github.com/Expensify/App/assets/78819774/ef541bd0-4061-47ae-b788-d879f1ca3890

**Comment by mallenexpensify** [comment] 2023-10-23 15:51
Thanks @lanitochka17 
Can't test, I broke my expensifail.com account :/

**Comment by mallenexpensify** [comment] 2023-10-30 16:44
I'm stumped here, I don't understand some aspects of how workspaces work, I posted about in #expensify-open-source to try to get some help.  https://expensify.slack.com/archives/C01GTK53T8Q/p1698683807624869

@akinwale , added a C+ to to see if you can review/help here, since I'm so confused here

**Comment by mallenexpensify** [comment] 2023-11-03 21:45
Well.. I've learned quite a bit the past week (but I'm sure there's a lot I still don't know).  
Current understanding
- Everyone on a workspace can 1:1 chat with the workspace, that's who they'd submit expenses too
- Users can create a workspace, not invite anyone, then create a room and invite people to that (which i did this week for #midtown-community). Apparently this is better than inviting them to a workspace cuz it's easier and, if people aren't going to be submitting expenses, they don't need to be a member of the workspace. (maybe that's kinda how we'll manage Admins > Employees (both on workspace) > guests (in rooms but not part of workspace). 

So.. if the above is (mostly true), that means we're allowing guests to chat with admins of the parent workspace and to also submit expenses to them.   And, if so, then we'd need/want to fix this issue with that in mind. (sorry if I'm sidetracking here while trying to understand the process/flow and use cases)

**Comment by mallenexpensify** [comment] 2023-11-08 01:09
@lanitochka17 can you retest this please to see if it's still happening? 
I just follow the steps on Desktop and wasn't able to reproduce.

**Comment by mallenexpensify** [comment] 2023-11-10 23:18
@akinwale can you test to see if you can reproduce? Thx

**Comment by akinwale** [comment] 2023-11-11 02:17
> @akinwale can you test to see if you can reproduce? Thx

I'll look into this.

**Comment by mallenexpensify** [comment] 2023-11-14 01:45
@akinwale , were you able to reproduce? Thx

**Comment by mallenexpensify** [comment] 2023-11-21 23:36
@akinwale and @lanitochka17 can you please try to reproduce?

**Comment by lanitochka17** [comment] 2023-11-22 14:15
Issue is not reproducible on the latest build 1.4.2-0

https://github.com/Expensify/App/assets/78819774/e1cdf60e-2c29-4e9a-b7f7-bba5cfbea393

**Comment by mallenexpensify** [comment] 2023-11-27 17:53
Thanks @lanitochka17 , can you do me one more favor, can you update the reproduction steps in the OP, to denote the steps needed to take in OldDot before moving over to NewDot?

**Comment by lanitochka17** [comment] 2023-12-03 16:22
@mallenexpensify Hello

![image](https://github.com/Expensify/App/assets/78819774/4d5babab-9f8b-4b7a-aad8-bba3b0ef5eb1)

![image](https://github.com/Expensify/App/assets/78819774/b5d24748-80b2-4d08-84c6-0386bf71322e)

**Comment by mallenexpensify** [comment] 2023-12-05 01:48
Thanks @lanitochka17 couple things. 
When outlining reproduction steps, can you do so in text in a post vs a screenshot, it makes it easier to copy/paste and to update any steps.
ie. 
> p = Policy.getCurrent()
> p.policy.isPolicyExpenisfyChatEnabled = "true";
> p.save();

I got through the OldDot steps but I'm unsure how to "Navigate to the workspace chat on the collect workspace".  The only report I see in LHN related to "NewDot Category" is the #admins one.  How do I access the workspace report?

**Comment by mallenexpensify** [comment] 2023-12-05 04:00
I think the issue is that I don't see Collect workspaces in the workspace I created with my mallen@expensifail.com
Anyone know why?!?!
It shows here
<img width="422" alt="image" src="https://github.com/Expensify/App/assets/22508304/bb1802ee-ecde-4a16-8f0d-aa4d8f541775">

But not when searching for it

<img width="409" alt="image" src="https://github.com/Expensify/App/assets/22508304/4c717e60-11ad-40b5-b873-91fe3bd9fa1d">

<img width="363" alt="image" src="https://github.com/Expensify/App/assets/22508304/461909b9-90c8-4e1b-bce4-5e0fa22f59a0">

<img width="428" alt="image" src="https://github.com/Expensify/App/assets/22508304/09bb58eb-211d-401b-994c-26e553baf493">

**Comment by mallenexpensify** [comment] 2023-12-05 04:06
Posted about in #expensify-open-source too
https://expensify.slack.com/archives/C01GTK53T8Q/p1701749018911429

**Comment by mallenexpensify** [comment] 2023-12-12 23:07
checking to see if we can add this to wave6 
https://expensify.slack.com/archives/C02MW39LT9N/p1702422435569189

**Comment by mallenexpensify** [comment] 2023-12-18 19:18
Checking again
https://expensify.slack.com/archives/C02MW39LT9N/p1702927081071739?thread_ts=1702422435.569189&cid=C02MW39LT9N

**Comment by mallenexpensify** [comment] 2023-12-23 18:31
Added to Wave 6 and the project board!

**Comment by mallenexpensify** [comment] 2024-01-03 01:55
Posted in #engineering to see about getting help
https://expensify.slack.com/archives/C03SSAQ7P/p1704246905372709

**Comment by aldo-expensify** [comment] 2024-01-03 14:31
I'll give it a try!

**Comment by aldo-expensify** [comment] 2024-01-03 14:39
Tried to reproduce by:

1. Create `collect` workspace with policy expense chats enabled
2. Invited employee
3. Created expense (which automatically created report) in OldDot using employee account
4. Logged in on NewDot using employee account and deleted the transaction

No error seen. Can we have more clear reproduction steps?

**Comment by mallenexpensify** [comment] 2024-01-05 00:34
@lanitochka17 can you please retest and, if you're able to reproduce, can you please share new reproduction steps that you use?  Thx

**Comment by mallenexpensify** [comment] 2024-01-10 01:57
Unable to reproduce on Android/chrome (Which looked like the vid in the OP) and Aldo wasn't able to either, so closing this 😌

**Closed by mallenexpensify** 2024-01-10 01:57 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug, Hot Pick
