### ISSUE TITLE
[HOLD for payment 2023-10-18] [$500] Two "Flag as offensive" list opens

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#28863] opened 2023-10-04 20:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. hover on message and right click
3. select  Flag as offensive
4. click on back button
## Expected Result: 
should hide  Flag as offensive list
## Actual Result: 
Flag as offensive list appears

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/0225b340-fb6c-413a-81aa-f1ff1011eb2f

https://github.com/Expensify/App/assets/38435837/1f31dfd6-8810-4875-9386-6341dd57fb7f

https://github.com/Expensify/App/assets/38435837/acba27b6-6d3c-495b-883a-afd268b48cad

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696409294638669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bfd52163177c5b7e</li>
        <li>Upwork Job ID: 1709673665006915584</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>gadhiyamanan | Contributor | 27048435</li>
<li>gadhiyamanan | Reporter | 27048436</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2023-10-04 20:56
## Proposal by @gadhiyamanan 
### Please re-state the problem that we are trying to solve in this issue.
two Flag as offensive list open
### What is the root cause of that problem?
We are navigate to flag comment two times [here](https://github.com/Expensify/App/blob/56eda28adc69f0a851d29f70427cf38c4bebfc89/src/pages/home/report/ContextMenu/ContextMenuActions.js#L375) and [here](https://github.com/Expensify/App/blob/56eda28adc69f0a851d29f70427cf38c4bebfc89/src/pages/home/report/ContextMenu/ContextMenuActions.js#L378)
### What changes do you think we should make in order to solve the problem?
add return after hideContextMenu and navigate to flag comment
https://github.com/Expensify/App/blob/56eda28adc69f0a851d29f70427cf38c4bebfc89/src/pages/home/report/ContextMenu/ContextMenuActions.js#L374-L376

**Comment by ayazalavi** [comment] 2023-10-05 03:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking on context menu item Flag as offensive opens a popover but it is not getting closed.

### What is the root cause of that problem?
There is redundant call to navigate method in onPress event of the menu item

https://github.com/Expensify/App/blob/6d86d5aecc47096bffdfbf59dcaefcb5dd0a0509/src/pages/home/report/ContextMenu/ContextMenuActions.js#L373-L379

### What changes do you think we should make in order to solve the problem?
We need to confirm why 2 times above callback is being called and if second callback is not necessary then remove it 
https://github.com/Expensify/App/blob/6d86d5aecc47096bffdfbf59dcaefcb5dd0a0509/src/pages/home/report/ContextMenu/ContextMenuActions.js#L378

### What alternative solutions did you explore? (Optional)
N/A

**Comment by maxconnectAbhi** [comment] 2023-10-05 10:02
# Proposal

## Please re-state the problem that we are trying to solve in this issue
"Flag as offensive" list modal opens two times

## What is the root cause of that problem?
Following callback is the root cause 
```
onPress: (closePopover, {reportID, reportAction}) => { 
     if (closePopover) { 
         hideContextMenu(false, () => Navigation.navigate(ROUTES.FLAG_COMMENT.getRoute(reportID, reportAction.reportActionID))); 
     } 
  
     Navigation.navigate(ROUTES.FLAG_COMMENT.getRoute(reportID, reportAction.reportActionID)); 
 }, 
 ```

## What changes do you think we should make in order to solve the problem?
In above callback we need to remove one Navigation call

## What alternative solutions did you explore? (Optional)
NA

**Comment by burczu** [comment] 2023-10-05 11:16
I've reviewed all the proposals and all of them define the root cause correctly but I think [the best solution](https://github.com/Expensify/App/issues/28863#issuecomment-1747628608) (and the first one) is the one from @m-natarajan - I believe here the `return` statement is just missing in the `if` block - we can compare it with similar  implementations of `onPress` method for other context menu item in the `ContextMenuActions.js` - they are similar so I believe calling `navigate` twice is intended.

🎀 👀 🎀 C+ reviewed

**Comment by gadhiyamanan** [comment] 2023-10-05 11:24
@m-natarajan is from QA team and he posted solution from [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1696413365210689?thread_ts=1696409294.638669&cid=C049HHMV9SM) 

cc: @burczu @francoisl

**Comment by burczu** [comment] 2023-10-05 11:28
@gadhiyamanan Ahh... sorry, I didn't notice it! Updated!

**Comment by ayazalavi** [comment] 2023-10-05 12:48
@burczu i think the person who posted issue should not be putting proposal. Otherwise there will be no margin for others.

**Comment by maxconnectAbhi** [comment] 2023-10-05 13:05
They Both seems to be friends 😀

**Comment by francoisl** [comment] 2023-10-06 00:12
Works for me, @gadhiyamanan let's go with your solution.

**Comment by gadhiyamanan** [comment] 2023-10-06 05:24
@burczu [PR](https://github.com/Expensify/App/pull/28978) is ready for review

**Comment by burczu** [comment] 2023-10-06 09:35
> @burczu i think the person who posted issue should not be putting proposal. Otherwise there will be no margin for others.

@ayazalavi This is quite common situation when some contributor posts they proposal directly in the Slack thread and then when QA engineer creates an issue on GH they just add the proposal along.

**Comment by burczu** [comment] 2023-10-17 06:39
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: No regression - it was just done this way from the beginning.
* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: n/a
* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: n/a
* [x]  [@burczu] Determine if we should create a regression test for this bug.
* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@bfitzexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by bfitzexpensify** [comment] 2023-10-18 20:31
Payments complete and BZ checklist done, we're all done here, thanks everyone.

**Closed by bfitzexpensify** 2023-10-18 20:31 UTC
Labels: External, Daily, Awaiting Payment, Bug
