### ISSUE TITLE
[HOLD for payment 2024-06-03]  Send invoice - Each workspace avatar in sender list has the same avatar

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41385] opened 2024-05-01 07:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User has a few workspaces with default and custom workspace name.

1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Enter amount and select a participant.
4. Click on the workspace.

## Expected Result:
Each workspace avatar is displayed correctly.

## Actual Result:
Each workspace avatar in sender list has the same avatar.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/2062df31-95e8-4e66-ae0b-5c76d4284be5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by izarutskaya** [comment] 2024-05-01 07:14
@adelekennedy I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-01 07:14
We think this issue might be related to the #vip-bills

**Comment by izarutskaya** [comment] 2024-05-01 07:15
Production 

![image (12)](https://github.com/Expensify/App/assets/115492554/ecfba886-acd9-440e-89a0-8be0c146f1e9)

**Comment by MonilBhavsar** [comment] 2024-05-01 11:01
A minor UI issue not worth a blocker.
Have commented in the offending PR https://github.com/Expensify/App/pull/39637#issuecomment-2088291461

**Comment by grgia** [comment] 2024-05-01 11:14
@nkdengineer

**Comment by grgia** [comment] 2024-05-01 11:15
@rushatgabhane this is a regression from https://github.com/Expensify/App/pull/39637#issuecomment-2088291461

**Comment by rushatgabhane** [comment] 2024-05-01 11:20
Send invoice wasn't a thing back then 😭 
Anyway, @nkdengineer could you please raise a PR

**Comment by MonilBhavsar** [comment] 2024-05-01 11:29
> Send invoice wasn't a thing back then 😭

Hmm, Send Invoice PR is on production and this is on staging. So i wonder if it is the case 🤔

**Comment by nkdengineer** [comment] 2024-05-02 02:42
@MonilBhavsar @grgia I will raise the PR to fix this today. It's hard to keep track this bug because it's merged while my PR is in review.

**Comment by adelekennedy** [comment] 2024-06-04 15:23
@MonilBhavsar @grgia I don't think any payment is due here, have I missed something?

**Closed** 2024-06-05 15:49 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
