### ISSUE TITLE
[HOLD for payment 2023-11-13] [$500] Room - Message starting with “<<“ not displayed in the welcome message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29612] opened 2023-10-14 16:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697214320531079

## Action Performed:
1. Navigate to Send message > Room
2. Enter a room name and enter a welcome message starting with “<<message”
3. Select a workspace and create the room
4. Go to the room detail page > Settings > Welcome message

## Expected Result:
Message starting with “<<“ should be displayed in the welcome message

## Actual Result:
Message starting with “<<“ not showing in the welcome message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details> crashed, not able to check 

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/cd457bb4-7fb5-45c7-be4e-d6cccdacd8f7

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/995b0e05-8028-4079-9bdd-a649f083e5e3

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/28510b43-8ef8-4a05-9c82-d7c67350f0c4

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/069e0920-ccec-4c04-bc04-b52f430af180

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/569ea6c1-4531-4f2e-b7c9-e8b786491aef

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aaeb78bffb57b09f</li>
        <li>Upwork Job ID: 1713225046807224320</li>
        <li>Last Price Increase: 2023-10-28</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27443023</li>
<li>abzokhattab | Contributor | 27443025</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2023-10-14 16:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Message starting with “<<“ is not shown in the welcome message

### What is the root cause of that problem?

we dont parse the the input message before its send to the backend and apprently the backend deals with is as empty line

### What changes do you think we should make in order to solve the problem?

like we do in the update welcome message here:

https://github.com/Expensify/App/blob/eabe4f4e40ca391ddc7d5eb0921ce91f5b7f0d9e/src/libs/actions/Report.js#L1355

we should also parse the message when creating the room:

so we need to add the prev line in the `addPolicyReport` as well:

```js
const parsedWelcomeMessage = ReportUtils.getParsedComment(welcomeMessage);
```

and use it here:

```js
const policyReport = ReportUtils.buildOptimisticChatReport(
  participants,
  reportName,
  CONST.REPORT.CHAT_TYPE.POLICY_ROOM,
  policyID,
  CONST.REPORT.OWNER_ACCOUNT_ID_FAKE,
  false,
  "",
  visibility,
  writeCapability,

  // The room might contain all policy members so notifying always should be opt-in only.
  CONST.REPORT.NOTIFICATION_PREFERENCE.DAILY,
  "",
  "",
  parsedWelcomeMessage
);
```

and finally in the api.write:

```js
API.write(
  "AddWorkspaceRoom",
  {
    policyID: policyReport.policyID,
    reportName,
    visibility,
    reportID: policyReport.reportID,
    createdReportActionID: createdReportAction.reportActionID,
    writeCapability,
    parsedWelcomeMessage,
  },
  { optimisticData, successData, failureData }
);
```

**Comment by AmjedNazzal** [comment] 2023-10-14 17:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Room - Message starting with “<<“ not displayed in the welcome message

### What is the root cause of that problem?

The reason for this is that we are parsing the welcome message using htmlToMarkdown which doesn't accept "<>"

https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/ReportWelcomeMessagePage.js#L49

### What changes do you think we should make in order to solve the problem?

Instead of using parser.htmlToMarkdown we can use parser.htmlToText since the welcome message is just text or we can just use report.welcomeMessage as it is

### Result

https://github.com/Expensify/App/assets/74202751/85c0c745-4230-4b56-94a6-a3ca126f6f4b

**Comment by peterdbarkerUK** [comment] 2023-10-16 20:35
Hmm, I couldn't reproduce this - where am I going wrong?


https://github.com/Expensify/App/assets/16888060/081e1c8f-4d44-41a2-ba07-c71fd944dd74

**Comment by abzokhattab** [comment] 2023-10-16 20:37
I think you attached a wrong video, Peter, Right?

**Comment by AmjedNazzal** [comment] 2023-10-16 20:52
@peterdbarkerUK Can you please tell us what you are getting on your end?

**Comment by ayazhussain79** [comment] 2023-10-18 11:23
@peterdbarkerUK could you please try again it is still reproducible

Steps:
1. Navigate to Send message > Room
2. Enter a room name and enter a welcome message starting with “<<message”
3. Select a workspace and create the room
4. Go to the room detail page > Settings > Welcome message

**Comment by peterdbarkerUK** [comment] 2023-10-24 13:43
Apologies, I'd updated the video above but my comment here was not saved.

I'm now able to reproduce.

**Comment by cubuspl42** [comment] 2023-10-30 08:24
In my opinion, the clearest solution was suggested by @abzokhattab. I verified that indeed there's an asymmetry between updating the welcome message and creating a room with a welcome message. Attacking the issue from this angle seems the most correct.

C+ reviewed 🎀 👀 🎀

**Comment by AmjedNazzal** [comment] 2023-10-30 09:03
@cubuspl42 That RC is incorrect though, it states that the backend displays an empty line, this has nothing to do with backend, check the backend response to room creation and you'll find that the message is indeed there, also try logging report.welcomeMessage and you'll see that it's there just fine.

**Comment by cubuspl42** [comment] 2023-10-30 10:06
@AmjedNazzal

> the backend displays it as an empty line

...is indeed an unfortunate statement, as backend can't really "display" anything directly in a React app.

I should have asked for improvement of the RCA.

My understanding is that the backend stores (or _wants to_ store) the welcome message as HTML, analogically to the comments. You seem to agree with this perspective, as you suggest replacing one `htmlTo...` operator with another `htmlTo...` operator.

As we seem to agree that the backend message format is HTML, than we should observe that `<< whatever` text is not HTML as the `<` characters require escaping. This is what is done when we update the welcome message, but is committed when we create a new room **with** a welcome message.

The root cause analysis in the proposal by @abzokhattab should be clarified. Would you do that, @abzokhattab?

Still, the general idea and the solution is valid and more appropriate in my opinion than switching to `htmlToText` **because** it seems to accept invalid HTML. We might consider switching to `htmlToText` as an unrelated change, though.

@neil-marcellini Would you confirm this reasoning with the backend?

**Comment by abzokhattab** [comment] 2023-10-30 10:40
> The root cause analysis in the proposal by @abzokhattab should be clarified. Would you do that, @abzokhattab?

 Thanks @AmjedNazzal  and @cubuspl42  for pointing that out .. updated the RCA.

**Comment by neil-marcellini** [comment] 2023-10-30 19:04
I like @abzokhattab's [proposal](https://github.com/Expensify/App/issues/29612#issuecomment-1763035319) too. Yes we expect to store the message as html. It doesn't have to be valid html, it can also be plain text. The point is that markdown is converted into html which then renders it with the appropriate styles. If it's just plain text then it parses to plaint text.

**Comment by peterdbarkerUK** [comment] 2023-11-14 15:52
@abzokhattab @ayazhussain79 could you accept the [offer in Upwork?](https://www.upwork.com/nx/wm/offer/27443025)

Thanks! 

@cubuspl42 - paid $500 for review. 

@cubuspl42 I think this is an edge case that needn't be added to testrail, would you agree? Could you also complete the rest of [the checklist?](https://github.com/Expensify/App/issues/29612#issuecomment-1796785510)

**Comment by abzokhattab** [comment] 2023-11-14 17:20
Thank you @peterdbarkerUK .. I have just accepted the offer.. please notice that this issue was opened before announcement, and the PR was merged within three days thus it should be eligible for the bonus.

**Comment by peterdbarkerUK** [comment] 2023-11-15 09:37
@abzokhattab thanks! 

As per [Greg's post](https://expensify.slack.com/archives/C01GTK53T8Q/p1698191269281379), PRs created after the announcement on October 25th would not be eligible for the urgency bonus. The PR for this issue was [created on October 30th](https://github.com/Expensify/App/pull/30609). Please let me know if I've misunderstood something, or if you disagree! 

Payment summary:
- $50 Reporter to @ayazhussain79
- $500 contributor to @abzokhattab 

Job closed, issue will close once @cubuspl42 and I have resolved the checklist

**Comment by abzokhattab** [comment] 2023-11-15 09:59
I thought it is based on the issue’s creation date not the PR creation date

Thanks

**Comment by cubuspl42** [comment] 2023-11-15 10:18
- The PR that introduced the bug has been identified. Link to the PR:
    -  https://github.com/Expensify/App/pull/29541
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - https://github.com/Expensify/App/pull/29541/files#r1393976540
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No need for a regression test
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by peterdbarkerUK** [comment] 2023-11-15 10:44
All good @abzokhattab I had to check it over as well!

**Comment by peterdbarkerUK** [comment] 2023-11-15 10:45
Thanks Jakub!

**Closed by peterdbarkerUK** 2023-11-15 10:45 UTC
Labels: External, Daily, Awaiting Payment, Bug
