### ISSUE TITLE
[$500] Expense - Expense preview shows incorrect amount briefly when WS default currency is different

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31638] opened 2023-11-21 15:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com.
2. Go to Settings > Workspaces > any workspace.
3. Click Settings > Default currency.
4. Select a different currency.
5. Go to workspace chat > + > Request money.
6. Enter amount (MYR1234) while remaining the local currency > Next.
7. Click Request in confirmation page.
Note that the amount in the confirmation shows the incorrect amount ($1234) briefly before the conversion.

## Expected Result:
The amount in the expense preview will show the correct amount (MYR1234) briefly before the conversion.

## Actual Result:
The amount in the expense preview shows the incorrect amount ($1234) briefly before the conversion.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0c409f71-eaf2-49e6-b492-ce1410a94431

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015cbb737be93fbffb</li>
        <li>Upwork Job ID: 1726990587939540992</li>
        <li>Last Price Increase: 2023-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28042435</li>
<li>esh-g | Contributor | 28042437</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-11-21 16:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Expense preview shows incorrect amount briefly when WS default currency is different

### What is the root cause of that problem?
Our optimistic data is set to incorrect currency 
### What changes do you think we should make in order to solve the problem?

We should set the currency of the optimistic data to the default currency 
### What alternative solutions did you explore? (Optional)

**Comment by esh-g** [comment] 2023-11-21 16:59
# Proposal

## Please re-state the problem we are trying to solve?
Expense - Expense preview shows incorrect amount briefly when WS default currency is different

## What is the root cause?
Two cases:
1. If there is a `iouReport` already created, we don't consider the currency may be different and just subtract here:
https://github.com/Expensify/App/blob/65076218fea470476c0f165a282d9a085523f09d/src/libs/actions/IOU.js#L463-L467
2. When creating a new `iouReport`, we create it in the workspace currency but don't change the amount here:
https://github.com/Expensify/App/blob/65076218fea470476c0f165a282d9a085523f09d/src/libs/ReportUtils.js#L2489-L2496

## What changes should be made to fix this?
**Case 1**
We should add a condition to check if the currency is same and subtract only if it is like this:
```js
if (policy.outputCurrency === currency) {
    iouReport.total -= amount;
}
```
**Note:** `policy` can be passed as a parameter from the money request page like this: `MoneyRequestConfirmPage(props.policy)` -> `IOU.requestMoney` -> `getMoneyRequestInformation`

Also, this is what we do for distance requests as well. We don't update `iouReport` optimistically for distance request, we rely on the backend. Moreover, it wouldn't make sense to update the `iouReport` optimistically because we don't have the converted amount on front-end anyways.

**Case 2**
We should stop using `outputCurrent` in `reportUtils.buildOptimisticExpenseReport()` and just use the original currency the request was in because we don't have the ability to change the amount to the desired currency on the front-end, so we can rely on the backend to update that

**Comment by Tony-MK** [comment] 2023-11-22 03:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Expense preview shows incorrect amount briefly when WS default currency is different

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/85f372c4e35c30119e72c7689959282a298bad1b/src/components/ReportActionItem/ReportPreview.js#L230

https://github.com/Expensify/App/blob/85f372c4e35c30119e72c7689959282a298bad1b/src/components/ReportActionItem/ReportPreview.js#L148-L153

The root cause of the problem comes from the frontend not having any way to convert different currencies, and there are no checks to determine and handle whether the currency of the money request's `transaction` and `iouReport` are different. We can only convert the amount into workspace currency at the backend. Due to this reason, the frontend sets the requested amount in the `ReportPreview` component using the default workspace currency, even if both currencies are different.

https://github.com/Expensify/App/blob/85f372c4e35c30119e72c7689959282a298bad1b/src/components/ReportActionItem/ReportPreview.js#L153

This is the line where `props.iouReportID.currency`, which is set by the policy, is used to produce a string with the workspace's right currency but the wrong amount value, `totalDisplaySpend` from the function `ReportUtils.getMoneyRequestSpendBreakdown`.

Here is a similar issue (https://github.com/Expensify/App/issues/27060#issuecomment-1813133832) to help gain a better understanding of the process. However, the issue is created at the backend.


### What changes do you think we should make in order to solve the problem?

Since we do not have the correct amount from the server, every possible figure we can show will eventually change. Unless the currencies are the same, therefore, the most appropriate solution in this situation is to display `TBD`. Then, the correct IOU amount will be displayed once the server pushes it. The reason why I believe this is the most appropriate solution is because, not only will it improve the user's offline experience, we already have implemented this method with distance requests. When a user's distance request changes waypoints and before the server returns the distance request's `amount`, if not manually set, and `distance`, the `ReportPreview` component will display `TBD`. To gain further understanding of why `TBD` is used for distance requests, here is a recent [PR] (https://github.com/Expensify/App/pull/30232) and [issue] (https://github.com/Expensify/App/issues/29899) to utilize.

Hence, we create a strict condition that is only `true` in this specific case, so we don't create regressions with other reports. The condition below is capable of determining whether the amount to be displayed on the `ReportPreview` is incorrect and is going to be updated soon.

```
const isWaitingOnAmount = isPolicyExpenseChat && numberOfRequests == 1 && lodashGet(props.iouReport, 'pendingFields.createChat') === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD && props.iouReport !== TransactionUtils.getAllReportTransactions(props.iouReportID)[0].currency

```

https://github.com/Expensify/App/blob/85f372c4e35c30119e72c7689959282a298bad1b/src/components/ReportActionItem/ReportPreview.js#L150-152

Using `isWaitingOnAmount` to change the condition above to look something similar to the one below should show `TBD` for incorrect amount values.

```

https://github.com/Expensify/App/assets/22982173/37146a5d-c7b3-4520-8cba-ad1f8436a963

if (hasPendingWaypoints || isWaitingOnAmount) {
    return props.translate('common.tbd');
}
```

https://github.com/Expensify/App/assets/22982173/671b22bb-f4d8-4b0d-a71b-5928d355b5d4

### What alternative solutions did you explore? (Optional)

This solution is like the previous one, but we use the amount in the very first money request currency, `TransactionUtils.getAllReportTransactions(props.iouReportID)[0]` instead of the default WS currency.

https://github.com/Expensify/App/blob/85f372c4e35c30119e72c7689959282a298bad1b/src/components/ReportActionItem/ReportPreview.js#L153

We will use the same condition as before and change the line above to look something similar to the one below. This will return a formatted string with the amount using the very first money request's currency.

```
return CurrencyUtils.convertToDisplayString(
   totalDisplaySpend, 
   isWaitingOnAmount ? TransactionUtils.getAllReportTransactions(props.iouReportID)[0].currency : props.iouReport.currency
);

```


https://github.com/Expensify/App/assets/22982173/9bc5c50a-3582-45d8-8553-fb866294bdc7

**Comment by DylanDylann** [comment] 2023-11-22 09:22
I think we should do no thing here, because we can't convert currency from FE side 
cc @danieldoglas Tag you here, because we have this context in the previous issue

**Comment by esh-g** [comment] 2023-11-22 14:24
I think the current behaviour should be changed because if the user has already requested for example $12 and another request of ₹10 is made, it shows for a moment that the request is $22 which is obviously wrong and should not be done

**Comment by DylanDylann** [comment] 2023-11-22 16:37
@c3024 Please check this discussion https://github.com/Expensify/App/issues/26309#issuecomment-1742647241

**Comment by c3024** [comment] 2023-11-23 02:04
Thanks @DylanDylann 

The existing optimistic update behaviour for the report preview in the workspace chat is weird.

But in the linked discussion you clearly laid out these cases and @danieldoglas and @dylanexpensify decided to do nothing here.

So let's do nothing here.

cc @NicMendonca

**Comment by esh-g** [comment] 2023-12-06 18:22
bump @c3024 on the [updated proposal](https://github.com/Expensify/App/issues/31638#issuecomment-1821310344)

**Comment by DylanDylann** [comment] 2023-12-07 04:03
@esh-g Could you check [this thread](https://github.com/Expensify/App/issues/26309#issuecomment-1742647241), too? Your proposal will fix it, right?

**Comment by DylanDylann** [comment] 2023-12-07 04:05
@c3024 @esh-g  
Turn offline. In workspace chat, the first request money I request 23000Đ, in the second time I request 1$. What we should display in this case ????

Note that: we can't convert currency on FE

**Comment by esh-g** [comment] 2023-12-07 04:07
@DylanDylann Yes, that is what my proposal covers. You can check the slack discussion here: https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1701181431339359
It aligns with the expectations here

**Comment by DylanDylann** [comment] 2023-12-07 04:14
<img width="744" alt="Screenshot 2023-12-07 at 11 13 27" src="https://github.com/Expensify/App/assets/141406735/c254faaf-ec1b-42e1-90fb-2ff712c91989">
 
A bit curious, in offline, we only update the amount if the currency is the same. Do you guys think it will make confusion for users because of inconsistency

**Comment by esh-g** [comment] 2023-12-07 06:43
@DylanDylann That is why it was decided to grey out the report preview to indicate a pending action. Moreover, we also do the same for offline distance requests. The preview doesn't get updated until you go online for distance requests as well.

**Comment by c3024** [comment] 2023-12-12 11:05
[Awaiting assignment](https://github.com/Expensify/App/issues/31638#issuecomment-1844195771)

**Comment by esh-g** [comment] 2023-12-15 18:06
PR is here: https://github.com/Expensify/App/pull/33171

**Comment by c3024** [comment] 2024-01-17 13:26
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

[x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: No specific PR caused this. The case of optimistic update for requesting money with a currency different from existing iou report currency was missed.
[x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: NA
[x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This is a difficult-to-catch case and a discussion is not beneficial.
[x]  [@c3024] Determine if we should create a regression test for this bug. Yes
[x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by c3024** [comment] 2024-01-17 13:42
### Regression test proposal

#### Test 1
1. Create a new workspace.
2. Set the workspace default currency to USD
3. Go to the expense chat of the workspace
4. Go offline
5. Make a request in a currency that is not USD
6. Verify that the preview shows the amount and currency used in step 5
7. Go online
8. Verify that the amount and currency in preview are updated to USD

#### Test 2
1. Create a new workspace
2. Set the workspace default currency to USD
3. Go to the expense chat of the workspace
4. Make a request of any amount in any currency from the 'Request Money' option in the composer
5. Wait till the preview gets updated to amount and currency to USD
6. Go offline
7. Make another request in a currency that is different from USD
8. Verify that the preview is greyed out and the total amount is not updated
9. Go online
10. Verify that the preview is not greyed out and the total amount gets updated

👍 or 👎

**Comment by c3024** [comment] 2024-01-17 13:46
@NicMendonca 

Automation failed to update the title here and labels for the issue are not updated. PR #33171 referred in this issue was deployed to production more than a week ago. 

PS: [This](https://github.com/Expensify/App/issues/31638#issuecomment-1878100733) was not a deploy blocker for this issue

Thanks

**Comment by NicMendonca** [comment] 2024-01-29 17:17
both have been paid!

**Closed by NicMendonca** 2024-01-29 17:17 UTC
Labels: Reviewing, External, Engineering, Monthly, Awaiting Payment, Bug
