### ISSUE TITLE
[$500] Workspace - Keyboard is flickering when entering magic code at bank account flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43425] opened 2024-06-10 19:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/38726
## Action Performed:
1. Log in with a new Gmail account
2. Create a workspace
3. Enable "Workflows"
4. Navigate to Workflows - Connect bank account
5. Tap on "verify your account here"
6. Enter magic code

## Expected Result:
The keyboard shouldn't flicker

## Actual Result:
Keyboard is flickering when entering or deleting magic code at bank account flow for an unverified account. The text under is becomes visible for a very short time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/750e57f4-7e3b-4038-8c8a-f3a5e115f86c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bfdc76c99fb63dcf</li>
        <li>Upwork Job ID: 1800283124607224669</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-06-10 19:28
@roryabraham  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-10 19:28
We think that this bug might be related to #wave-collect - Release 1

**Comment by roryabraham** [comment] 2024-06-10 20:25
I've been seeing this one for a while, so I'm pretty sure it's not a deploy blocker. It is really annoying though.

**Comment by roryabraham** [comment] 2024-06-10 20:27
I think there are some other preconditions we're missing that makes this happen, because I wasn't able to reproduce this on staging with my rory@expensify.com account

**Comment by roryabraham** [comment] 2024-06-10 20:32
It happens with some other TextInputs too... 🤔

**Comment by roryabraham** [comment] 2024-06-10 20:33
It looks similar to [this Flutter issue](https://github.com/flutter/flutter/issues/134723)

**Comment by roryabraham** [comment] 2024-06-10 20:36
It sounds like the consensus in the community is that this is an [iOS 17 issue](https://github.com/facebook/react-native/issues/39411#issuecomment-1744962420), which is out of our hands.

**Comment by roryabraham** [comment] 2024-06-10 20:41
We may be able to disable auto suggestions for the MagicCode input, by [setting it to a oneTimePassword](https://github.com/facebook/react-native/issues/39411#issuecomment-1746484565) input, which seems appropriate. But I'm not sure if that will disable this autocompletion behavior (shows up after opening the email with the magic code)

![IMG_AF5C771688F4-1](https://github.com/Expensify/App/assets/47436092/37e65c80-e23d-4458-884d-ee707b6e1688)

**Comment by roryabraham** [comment] 2024-06-10 21:42
Since I'm pretty certain I've seen this in production, and I'm not consistently seeing it in staging, I'm going to demote it.

I'll make it external just in case I'm being too hasty in thinking that it's most likely an iOS bug, and someone has a simple idea to fix this.

**Comment by roryabraham** [comment] 2024-06-10 21:46
On this issue I want to be particularly wary of hacks or workarounds. We don't need to make our code super complex to try and work around an iOS bug. Ideally that is fixed by Apple at some point soon

**Comment by TheGithubDev** [comment] 2024-06-11 10:55
### **Proposal**

### **Please re-state the problem that we are trying to solve in this issue:**
The problem is that the keyboard flickers when entering or deleting the magic code in the bank account verification flow for an unverified account. This flickering causes the text underneath to become visible momentarily, disrupting the user experience.

### **What is the root cause of that problem?**
The root cause of this problem is likely due to the input field losing and gaining focus repeatedly, causing the keyboard to appear and disappear. This could be caused by:
1. **Focus Handling:** Improper handling of the input field focus events, potentially due to state changes or re-renders triggered by the input actions.
2. **Animation or Transition:** Unintended animations or transitions that affect the input field or the keyboard.

**What changes do you think we should make in order to solve the problem?**
To address this issue without resorting to hacks or workarounds, we should focus on simplifying and stabilizing the code handling the input field:

1. **Stabilize Focus Handling:**
- Ensure that the input field retains focus correctly during input actions by preventing unnecessary state changes and re-renders.

2. **Optimize State Management:**
- Use a straightforward state management approach to avoid triggering re-renders that could cause the flickering.

3. **Review and Adjust Animations:**
- Ensure there are no unintended animations or transitions affecting the input field.

### **Example of changes:**

### **1. Stabilize Focus Handling:**
   ```javascript
   const handleFocus = () => {
       inputRef.current.focus();
   };

   return (
       <TextInput
           ref={inputRef}
           onFocus={handleFocus}
           onChangeText={handleInputChange}
           // Ensure other necessary props are included
       />
   );
   ```

### **2. Optimize State Management:**
   ```javascript
   const [magicCode, setMagicCode] = useState('');

   const handleInputChange = (text) => {
       setMagicCode(text);
   };

   return (
       <TextInput
           value={magicCode}
           onChangeText={handleInputChange}
           // Ensure other necessary props are included
       />
   );
   ```

### **3. Review and Adjust Animations:**
   ```javascript
   return (
       <View style={styles.inputContainer}>
           <TextInput
               value={magicCode}
               onChangeText={handleInputChange}
               // Ensure other necessary props are included
           />
       </View>
   );
   ```

### **What alternative solutions did you explore? (OPTIONAL)**
We could implement a debounce mechanism for input changes to reduce the frequency of state updates and re-renders.

Please note that the above explanation outlines only the technical approach I plan to take. After my proposal is accepted, I will submit the finalized solution or code promptly.

Regards.
Mohammed

**Comment by kevinksullivan** [comment] 2024-06-17 17:59
@abdulrahuman5196 thoughts on the proposal above?

**Comment by kevinksullivan** [comment] 2024-06-17 18:02
@MitchExpensify just looping in another BZ member while I am OOO Tuesday - Friday. Will keep it up once I return!

**Comment by MitchExpensify** [comment] 2024-06-19 22:56
@abdulrahuman5196, friendly bump here on a proposal review

**Comment by abdulrahuman5196** [comment] 2024-06-20 16:09
@TheGithubDev The proposal seems to be like a generalized good practice kind of information, I am not seeing solid Root cause analysis or solution. Can you update your proposal with solid RCA and solution? Or elaborate if I missed something.

**Comment by TheGithubDev** [comment] 2024-06-21 16:59
Will definitely edit and reply.
Thanks for the feedback.

**Comment by abdulrahuman5196** [comment] 2024-06-24 18:51
No new proposal to review

**Comment by kevinksullivan** [comment] 2024-06-26 15:35
increasing price and still waiting on proposals.

**Comment by abzokhattab** [comment] 2024-06-26 16:12
the issue is not reproducible on my side, am i missing any step? 


https://github.com/Expensify/App/assets/59809993/1625bbe9-839b-4ad4-870c-bf28466689cb

**Comment by kevinksullivan** [comment] 2024-07-03 20:57
closing for now unless we can get reliable steps

**Comment by lanitochka17** [comment] 2024-07-05 18:20
Issue is still reproducible on the latest build 9.0.4-7
Iphone 14 Pro Max/IOS17
The same steps
https://github.com/Expensify/App/assets/78819774/efb496d6-f216-4309-9a22-cdaed030fb86

**Comment by kevinksullivan** [comment] 2024-07-15 18:10
adding to collect since this is VBBA related

**Comment by roryabraham** [comment] 2024-07-16 20:59
Ok, adding the retest-weekly label to keep an eye on this. We can accept other proposals here, but I'm not going to double this and instead we'll kind of wait-and-see if Apple fixes this.

**Comment by roryabraham** [comment] 2024-07-17 08:44
I've noticed this across many different websites on my phone. Noticed it at least twice today on other sites.

**Comment by mvtglobally** [comment] 2024-09-09 04:08
Issue not reproducible during KI retests. (First week)

**Comment by kevinksullivan** [comment] 2024-09-12 19:34
Looping in a BZ member to handle payment as I'm going OOO in case this does get picked up

**Comment by mvtglobally** [comment] 2024-09-13 16:35
Issue not reproducible during KI retests. (Second week)

**Comment by slafortune** [comment] 2024-09-13 19:42
[SO](https://stackoverflowteams.com/c/expensify/questions/18717) If KI restest are not reproducible for more than 3 weeks it's safe to close the GH - one more week of testing 👍

**Comment by abdulrahuman5196** [comment] 2024-09-17 15:07
> [SO](https://stackoverflowteams.com/c/expensify/questions/18717) If KI restest are not reproducible for more than 3 weeks it's safe to close the GH - one more week of testing 👍

Same

**Comment by slafortune** [comment] 2024-09-23 15:34
Unassigning myself now that your back @kevinksullivan - just needs to be tested once more.

**Comment by roryabraham** [comment] 2024-10-01 00:35
not overdue, awaiting retest

**Comment by izarutskaya** [comment] 2024-10-17 09:08
Not reproducible anymore.
Build v 9.0.50-0

https://github.com/user-attachments/assets/a2aceba7-9dc1-49da-890b-2f9d4bb589f2

**Closed** 2024-10-17 11:19 UTC
Labels: External, Engineering, Weekly, Bug, retest-weekly
