### ISSUE TITLE
[HOLD for payment 2024-07-10] [$500] critical: Chat is not marked as read when receiving a message being in the chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40152] opened 2024-04-11 20:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711638025134599

## Action Performed:
1. Go to any chat
2. Open another tab or not having the window on focus
3. Receive a notification for a new message in the chat
4. Click on the notification and land on the chat
5. Chat should be marked since message is read
6. Go to another chat 
7. Again open the chat where the message is received

## Expected Result:
In step 4 or in step 6 LHN should be unbold as the message is read

## Actual Result:
Still showing as unread, user has to click back to the chat as in step 7 to show as "read"

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/cc01a991-50f0-4fee-b112-477bb33c3c4e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e5ebea78782ee33</li>
        <li>Upwork Job ID: 1778874424236658688</li>
        <li>Last Price Increase: 2024-07-03</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 102764320</li>
<li>allgandalf | Contributor | 102884646</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by dylanexpensify** [comment] 2024-04-12 19:54
Yep, could repro, though low value

**Comment by iwiznia** [comment] 2024-04-12 20:15
> though low value

I disagree, this is happening to me every day, many times a day. It makes the app look broken as it makes you have to click out and back in to mark as read.

**Comment by giorgi17** [comment] 2024-04-14 16:29
Doesn't show notifications for me like in the video, do I need to activate something? trying to replicate the issue.

**Comment by dylanexpensify** [comment] 2024-04-15 09:31
>I disagree, this is happening to me every day, many times a day. It makes the app look broken as it makes you have to click out and back in to mark as read.

happy to move this higher then @iwiznia!

**Comment by dylanexpensify** [comment] 2024-04-15 09:40
> What is the expected behaviour? Should we quickly mark it as read when the user switches to the tab? Then the user wouldn't be able to know that there are some new messages, and where the new messages start from. Maybe we can have some interval, like mark it as read after 4 seconds (just as an example).

@ShridharGoel simple - just if the user clicks on the notification and reads the chat, it's marked as read then and there (aka unbolds instantly when opening the chat).

**Comment by dylanexpensify** [comment] 2024-04-15 09:53
@ShridharGoel that should disappear at the same rate it does for any new message! cc @Expensify/design not sure if we have a limit distinguished for this

**Comment by shawnborton** [comment] 2024-04-15 11:24
I would think the New marker would stay in the chat as long as you are looking at the chat. This way if you do scroll up and down in the chat, you at least have a marker that shows you where the new messages start. If you navigate away and come back, then the new marker would disappear. Is that what you are asking Dylan?

**Comment by giorgi17** [comment] 2024-04-15 12:05
> > Doesn't show notifications for me like in the video, do I need to activate something? trying to replicate the issue. @dylanexpensify
> 
> @giorgi17 ah make sure your preferences allow for notifications from New Expensify!

I did, but still couldn't see notifications, perhaps it's not reproducible on local. However, I've found similar issue, where receiving the message and opening It doesn't unbold the text, it's still seen as "unread". It only works after 1 minute or so. [See the footage ](https://nimb.ws/10BMyrI)
My diagnosis is that from frontend, the message creation time is sent correctly, but then the response has the time 1.5 minutes later, because of this, the logic is flawed. Read time is always 1.5 minute earlier if you quickly try to view the new message upon receiving it, you basically need to wait 2 minutes so you can then open the chat and it'll then pick that it's now read, so, for the first 2 minutes, this logic doesn't work. This is why I was trying to find the backend code, it's a huge project, could you tell me where I could see the backend code, or Is there one at all in this project. Maybe i could find the reason there for this time difference. 

The same reason could be in the case of notification. Fixing this requires figuring out, why after sending the right message creation time, i receive the time from the database that is 1.5 minutes older.

**Comment by giorgi17** [comment] 2024-04-22 20:07
> 📣 It's been a week! Do we have any satisfactory proposals yet? Do we need to adjust the bounty for this issue? 💸

Yes, my proposal is satisfactory - https://github.com/Expensify/App/issues/40152#issuecomment-2056672875

**Comment by abdulrahuman5196** [comment] 2024-04-23 12:38
Checking now

**Comment by abdulrahuman5196** [comment] 2024-04-23 12:41
@FitseTLT I think we fixed this sometime back right? Or is it different?

**Comment by robert-westenberger** [comment] 2024-04-27 18:47
I'm seeing something different than what giorgi is seeing. When following the steps to reproduce, when i console log the optimisticReport from src/libs/actions/Report.ts:477 , and compare it's lastVisibleActionCreatedTime to that from the lastVisibleActionCreatedTime value inside the addComment POST response body, i see a difference in the order of milliseconds (2024-04-27 18:27:57.093 from the response body and 2024-04-27 18:27:56.685 from the optimistic report object for example ). 

One thing I've noticed is that components that are getting report data from the onyx store via withOnyx are rendering with stale data when landing on a report from a browser notification. 

The components DO have a render where they are rendering with the most up to date lastReadTime, but then they rerender with the previous/stale lastReadTime. 

You can see this when you view the lastReadTime for a report in local storage, and then compare it to a value for a report the withOnyx HOC is returning. 

Just for an arbitrary example, in localStorage I happen to have 2024-04-27 18:28:05.186 for the report i'm testing, but when i inspect the props LHNOptionsList is getting with react devtools I see 2024-04-27 18:27:04.873 , which is the previous / stale value for lastReadTime. 


This is the first expensify issue I have looked at and I don't know enough about onyx or the report flow to diagnose a root cause.

**Comment by robert-westenberger** [comment] 2024-04-27 18:51
Contributor details
Your Expensify account email: robert.michael.westenberger@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0121200855c9004c83

**Comment by dylanexpensify** [comment] 2024-04-29 10:06
@abdulrahuman5196 can we get an update and next steps please?

**Comment by dylanexpensify** [comment] 2024-05-01 07:36
Bump @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2024-05-01 15:05
Sorry for delay. Checking now

**Comment by abdulrahuman5196** [comment] 2024-05-01 15:19
@giorgi17 @robert-westenberger Kindly propose solution as per the contributing template

https://raw.githubusercontent.com/Expensify/App/main/contributingGuides/PROPOSAL_TEMPLATE.md

The suggestions provided above is more of a hypothesis and I am not sure if that the hypothesis is correct.
And kindly provide code path on where you think the issue is happening and code path for your solution to fix the same.

To note the backend code is not open-source, only front-end code is open-source.

If you still have doubts on how to provide a proposal, kindly check other issues as well in the Repo which could provide better idea.

**Comment by abdulrahuman5196** [comment] 2024-05-01 15:19
@dylanexpensify We don't have any proposals to approve yet.

**Comment by dylanexpensify** [comment] 2024-05-07 11:18
Pending proposals

**Comment by gedu** [comment] 2024-05-07 13:54
Hey Edu from Callstack, I can take a look at this

**Comment by gedu** [comment] 2024-05-08 10:16
I'm not able to get a notification, do I need any special setup? I'm getting emails from the messages sent but no notifications

**Comment by gedu** [comment] 2024-05-08 15:38
@dylanexpensify what I found is, in this [PR](https://github.com/Expensify/App/pull/31762/files) a change into the ReportActionsList was introduced the `Visibility.isVisible`
```
    if (ReportUtils.isUnread(report)) {
            if (Visibility.isVisible() && scrollingVerticalOffset.current < MSG_VISIBLE_THRESHOLD) {
                Report.readNewestAction(report.reportID);
            } else {
                readActionSkipped.current = true;
            }
        }
 ```
 Seems that code is getting executed before the document is visible. When the component runs the code `document.visibilityState` is `hidden` so it skip the read action.
I want to understand why that check was added in first place

**Comment by gedu** [comment] 2024-05-09 10:08
@abdulrahuman5196 do you have more knowledge about my previous comment?

**Comment by gedu** [comment] 2024-05-13 09:29
@abdulrahuman5196 I would need a bit more of context to fix this issue, now the `Visibility.isVisible()` causing problems, so I would like to have more information to know if we can remove it or I look into something else

**Comment by abdulrahuman5196** [comment] 2024-05-13 09:35
Checking now

**Comment by abdulrahuman5196** [comment] 2024-05-13 16:01
> @dylanexpensify what I found is, in this [PR](https://github.com/Expensify/App/pull/31762/files) a change into the ReportActionsList was introduced the `Visibility.isVisible`
> 
> ```
>     if (ReportUtils.isUnread(report)) {
>             if (Visibility.isVisible() && scrollingVerticalOffset.current < MSG_VISIBLE_THRESHOLD) {
>                 Report.readNewestAction(report.reportID);
>             } else {
>                 readActionSkipped.current = true;
>             }
>         }
> ```
> 
> Seems that code is getting executed before the document is visible. When the component runs the code `document.visibilityState` is `hidden` so it skip the read action. I want to understand why that check was added in first place

@gedu I am sure of the reason it was added. Tagging @arosiclair who originally added the change. Could you kindly check on this?

**Comment by arosiclair** [comment] 2024-05-13 20:17
> > @dylanexpensify what I found is, in this [PR](https://github.com/Expensify/App/pull/31762/files) a change into the ReportActionsList was introduced the `Visibility.isVisible`
> > Seems that code is getting executed before the document is visible. When the component runs the code `document.visibilityState` is `hidden` so it skip the read action. I want to understand why that check was added in first place
> 
> @gedu I am sure of the reason it was added. Tagging @arosiclair who originally added the change. Could you kindly check on this?

IIRC, we were automatically marking new report actions as read even when the window was minimized/unfocused. This was preventing push notifications from displaying because they are hidden if the message is already read. I added the visibility check to fix that.

I don't have all of the context on this issue, but we probably need to continue checking that the window is visible before marking any report as read.

**Comment by gedu** [comment] 2024-05-14 05:24
> > > @dylanexpensify what I found is, in this [PR](https://github.com/Expensify/App/pull/31762/files) a change into the ReportActionsList was introduced the `Visibility.isVisible`
> > > Seems that code is getting executed before the document is visible. When the component runs the code `document.visibilityState` is `hidden` so it skip the read action. I want to understand why that check was added in first place
> > 
> > 
> > @gedu I am sure of the reason it was added. Tagging @arosiclair who originally added the change. Could you kindly check on this?
> 
> IIRC, we were automatically marking new report actions as read even when the window was minimized/unfocused. This was preventing push notifications from displaying because they are hidden if the message is already read. I added the visibility check to fix that.
> 
> I don't have all of the context on this issue, but we probably need to continue checking that the window is visible before marking any report as read.

Awesome, that good information, I will try a couple of things then, thanks

**Comment by gedu** [comment] 2024-05-14 05:51
@abdulrahuman5196 Seems with the last code in `main` this bug is fixed, I saw this [PR](https://github.com/Expensify/App/pull/41484) was merged. Can we double check?

**Comment by dylanexpensify** [comment] 2024-05-14 09:40
@abdulrahuman5196 can we confirm this today?

**Comment by dylanexpensify** [comment] 2024-05-15 20:27
confirmed

**Comment by m-natarajan** [comment] 2024-05-22 20:32
Still able to reproduce.
**Issue reported by:** @iwiznia
**Slack conversation :** https://expensify.slack.com/archives/C049HHMV9SM/p1716385350752519 

https://github.com/Expensify/App/assets/38435837/89bfaec3-4484-4ca8-8a79-3971a9c9e874

**Comment by dylanexpensify** [comment] 2024-05-29 06:37
Ah hmm, darn. Ok, let's bring it on. @gedu want to dig more?

**Comment by abdulrahuman5196** [comment] 2024-06-04 19:45
> Ah hmm, darn. Ok, let's bring it on. @gedu want to dig more?

Seems we are waiting on @gedu , can you check on this?

**Comment by dylanexpensify** [comment] 2024-06-05 09:19
@gedu bump!

**Comment by gedu** [comment] 2024-06-10 18:16
Sorry for the late response, I though it was closed, and missed some pings, I can take another look

**Comment by dylanexpensify** [comment] 2024-06-11 10:50
thank you @gedu!

**Comment by gedu** [comment] 2024-06-13 08:33
I will try to investigate a bit more why is this happening

**Comment by gedu** [comment] 2024-06-13 13:44
@dylanexpensify hey seems that this commit: https://github.com/Expensify/App/commit/cd7ba79935aed99bfbf998e0567bbf8cfa1a868f [PR](https://github.com/Expensify/App/pull/32548)

Produce the regression here, we can create a new file using the `.website` or my change above

**Comment by gedu** [comment] 2024-06-14 09:06
Proposal
Please re-state the problem that we are trying to solve in this issue.
When the User opens the report from a notification, at LHN is showing the title as unread, after switching reports, it still showing as unread

What is the root cause of that problem?
Seems that config changes here:
commit: https://github.com/Expensify/App/commit/cd7ba79935aed99bfbf998e0567bbf8cfa1a868f 
PR: https://github.com/Expensify/App/pull/32548
Made chrome handle different the files.

What changes do you think we should make in order to solve the problem?
I would rename the files, so the proper logic can be handle by the specific ones:
`index.ts` was intended only for native so -> `index.native.ts`
`index.desktop.ts` was intended for desktop and web -> `index.ts`

**Comment by gedu** [comment] 2024-06-14 15:02
@MonilBhavsar friendly ping

**Comment by gedu** [comment] 2024-06-17 13:20
Ping on Slack

**Comment by mountiny** [comment] 2024-06-17 13:29
@gedu feel free to raise the PR please

**Comment by dylanexpensify** [comment] 2024-06-17 19:34
+1 @gedu

**Comment by dylanexpensify** [comment] 2024-06-18 09:09
Gedu is working on PR

**Comment by gedu** [comment] 2024-06-18 15:09
@mountiny @dylanexpensify  I'm trying to get notifications on Safari or desktop but I'm not getting it

**Comment by gedu** [comment] 2024-06-19 16:26
PR created

**Comment by dylanexpensify** [comment] 2024-07-03 08:34
Correct, thanks @allgandalf!

**Comment by dylanexpensify** [comment] 2024-07-10 08:13
payment coming up!

**Comment by dylanexpensify** [comment] 2024-07-12 13:12
Payment summary:
- Contributor: @gedu $500
- Contributor+: @allgandalf $500

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-07-12 13:19
Done!

**Closed by dylanexpensify** 2024-07-12 13:19 UTC
Labels: External, Daily, Awaiting Payment, Bug, High Priority
