### ISSUE TITLE
[$1000] Web - Clicking on Avatar in Header of Task Detail page takes to wrong user details

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23579] opened 2023-07-25 19:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a task with assignee
2. Go to task page
3. Wait till the time in the bottom shows up
4. Click on User in Header of Task details page

## Expected Result:
There are two possibilities:
It should show the details of the task creator

## Actual Result:
Wrong user in Header and User Details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c7712ad5-7d18-4693-ab88-e8648864f21a

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @BhuvaneshPatil
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1689928645869329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ccc9b0b61fc1bf49</li>
        <li>Upwork Job ID: 1684047964217954304</li>
        <li>Last Price Increase: 2023-07-26</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-25 19:01
**Proposal by**: @BhuvaneshPatil
**Slack conversation**: https://expensify.slack.com/archives/C049HHMV9SM/p1689928645869329

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking on header of task report opens assignee page instead of members/details page

### What is the root cause of that problem?
When we click on header - `navigateToDetailsPage` function is called.
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/home/HeaderView.js#L164-L170

And this function - 
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/libs/ReportUtils.js#L1269-L1281

For task which has assignee, there is only one `accountID` in `participantAccountIDs` (which is task assignee), that's why we are opening the `assignee` profile page.

### What changes do you think we should make in order to solve the problem?
The solution depends on what page do we want to open
1. If we want to open details page
Then we shall add the condition here - 

    if (isChatRoom(report) || isPolicyExpenseChat(report) || isChatThread(report) || isTaskReport(report)) {
        Navigation.navigate(ROUTES.getReportDetailsRoute(report.reportID));
        return;
    }

2. If we want to open the members page - 
Then there are two approaches for this -
    - Add the following condition that check if current report is task report or not and based on that navigates to required page
    
      if(isTaskReport(report)){
        Navigation.navigate(ROUTES.getReportParticipantsRoute(report.reportID));
        return;
    }
    
    - Add condition while we are redirecting to user details page to check if the report is task report or not
    
        if (participantAccountIDs.length === 1 && !isTaskReport(report)) {
        Navigation.navigate(ROUTES.getProfileRoute(participantAccountIDs[0]));
        return;
    }
    

### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2023-07-25 19:08
Expanding on - https://github.com/Expensify/App/issues/23579#issuecomment-1650376240

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Clicking on Avatar in Header of Task Detail page takes to wrong user details

### What is the root cause of that problem?
When we click on header - `navigateToDetailsPage` function is called. And in case of task that is assigned to someone.
`participantAccountIDs` has only one id. and we are take to profile details of task assignee profile details page.


### What changes do you think we should make in order to solve the problem?
as mentioned by @thienlnam here - https://expensify.slack.com/archives/C049HHMV9SM/p1690311552613889?thread_ts=1689928645.869329&cid=C049HHMV9SM

Clicking on task header should take us to profile details of creator. To adjust for this behaviour - 
we can modify this method as following - 
- We add the check if current report is task or not. and based on that redirect user to creator's profile page.
We can get the creatorID using `ownerAccountID` field.
```
    if(isTaskReport(report)){
        Navigation.navigate(ROUTES.getProfileRoute(report.ownerAccountID));
        return;
    }
```


### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2023-07-26 03:48
Able to reproduce this one. Given that the task creator is the avatar that appears in the header, I think that's the one we should be showing.

**Comment by JmillsExpensify** [comment] 2023-07-26 04:16
I think that second one is a closer replica. Thanks for flagging. I'll close though Jasper, please re-open if you disagree.

**Comment by JmillsExpensify** [comment] 2023-07-26 04:16
Further for clarity, since this is a duplicate report, no payout is issued for reporting.

**Closed by JmillsExpensify** 2023-07-26 04:16 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by BhuvaneshPatil** [comment] 2023-07-26 04:28
@Nodebrute. I have mentioned the root cause for #23296 in slack conversation. So they are not dupes.

The PR that was going to fix - https://github.com/Expensify/App/issues/23579, has been merged and it's still reproducible.

**Comment by BhuvaneshPatil** [comment] 2023-08-07 18:02
Updated proposal - 

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
It must show the detail of the user's profile that assigns the task

### What is the root cause of that problem?
As decided here in slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1691426870537099?thread_ts=1691334974.136469&cid=C01GTK53T8Q

We should show the task title (the one that appears in header below the avatar, and avatar will be of task creator)

### What changes do you think we should make in order to solve the problem?
We are disabling showing `shouldUseFullTitle` here - 
https://github.com/Expensify/App/blob/09f6b6b00ecbee279f8988b92dd81abeb56416d1/src/pages/ReportDetailsPage.js#L153-L160

For that value we use - 
https://github.com/Expensify/App/blob/09f6b6b00ecbee279f8988b92dd81abeb56416d1/src/pages/ReportDetailsPage.js#L63-L64

We shall change - `shouldUseFullTitle` to something like below - 

```js
const shouldUseFullTitle = !shouldDisableSettings || ReportUtils.isTaskReport(props.report);
```

It will allow to show full title in case we are opening a task report.

### What alternative solutions did you explore? (Optional)
