### ISSUE TITLE
[$1000]  Dev - Clicking on the browser back button either reloads the same page or doesn't take the user to the immediate previous page.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21121] opened 2023-06-20 14:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB and assign task
2. Input title and click next
3. Click on Assignee and select a user
4. Click on Share somewhere 
5. Click on the browser back button
6. Click on Share somewhere again and select a workspace
7. Click on Share somewhere and click on the browser back button

Same behavior occurs if you select a report to "Share somewhere" then click into Assignee and hit the back button - you're taken to the "Share Somewhere" instead of the Confirm Task page.

## Expected Result:
App should take user back to the Confirm Task page

## Actual Result:
App reloads the same page / takes to Assignee page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.27-6

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4651be3c-0dc9-4a0c-b020-30d75452f2e0

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686731805543929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ac6ff52966f5604</li>
        <li>Upwork Job ID: 1671528400032681984</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-06-21 14:39
Reproducible, triaging to External

**Comment by rain2o** [comment] 2023-06-21 18:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The browser back button creates unexpected behavior while navigating through some of the views in the `/new/task` modal.

### What is the root cause of that problem?

The [TaskShareDestinationSelectorModal](https://github.com/Expensify/App/blob/main/src/pages/tasks/TaskShareDestinationSelectorModal.js) and [TaskAssigneeSelectorModal](https://github.com/Expensify/App/blob/main/src/pages/tasks/TaskAssigneeSelectorModal.js) pages utilize `Navigation.goBack()` after selecting a value. When you use the browser's back button it seems to be reloading the last navigation state in that stack which was created from the `navigate` action. In this case it loads a state that was previously _popped_ by using `goBack`.

I believe this is due to the nature of how `goBack` and `navigate` work within react-navigation. As [this comment](https://github.com/Expensify/App/issues/21121#issuecomment-1600966505) explains, this behavior can be reproduced on other pages in this modal. If you select a report in the "Share somewhere" view, clicking on Title, Description, or Assignee and then using the browser's back button will reproduce the described issue. This problem seems to be boiled down to the use of `Navigation.goBack()`.

### What changes do you think we should make in order to solve the problem?


We should make the navigation behavior consistent with the other pages in this modal. Looking at [NewTaskDescriptionPage](https://github.com/Expensify/App/blob/main/src/pages/tasks/NewTaskDescriptionPage.js#L56) for inspiration I see that `Navigation.navigate(ROUTES.NEW_TASK);` is used instead of `Navigation.goBack()`. Similarly, [NewTaskTitlePage](https://github.com/Expensify/App/blob/main/src/pages/tasks/NewTaskTitlePage.js#L61) uses `Navigation.navigate(ROUTES.getNewTaskRoute());`.

To keep the code and behavior consistent, we should use `Navigation.navigate(ROUTES.NEW_TASK);` in both `TaskShareDestinationSelectorModal` and `TaskAssigneeSelectorModal`. I have tested this solution and the described behavior in this bug no longer occurs.

### What alternative solutions did you explore? (Optional)

A less-than-ideal solution could be to add support for `PUSH` in [navigate](https://github.com/Expensify/App/blob/main/src/libs/Navigation/Navigation.js#LL67C14-L67C14)'s `type` param, and update [linkTo](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkTo.js#LL8C31-L8C31) accordingly, adding a condition for `type === 'PUSH'`. We could then use `onPress={() => Navigation.navigate(ROUTES.NEW_TASK_ASSIGNEE, 'PUSH')}` in [NewTaskPage](https://github.com/Expensify/App/blob/main/src/pages/tasks/NewTaskPage.js)'s MenuItems. This seems to solve the issue, though is not as clean of a solution.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by rain2o** [comment] 2023-06-21 18:19
Contributor details
Your Expensify account email: joel.rain2o@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0179b5219c771c991d

**Comment by abdulrahuman5196** [comment] 2023-06-24 16:00
This issue could be solved by this PR navigation refractor PR - https://github.com/Expensify/App/pull/21067

I tested with the PR locally and this issue is not happening

**Comment by abdulrahuman5196** [comment] 2023-06-27 10:14
Not overdue. Ref https://github.com/Expensify/App/issues/21121#issuecomment-1605607974

**Comment by sonialiap** [comment] 2023-06-30 12:33
Holding for https://github.com/Expensify/App/pull/21067

**Comment by abdulrahuman5196** [comment] 2023-07-05 15:45
The issue is on hold melvin

**Comment by sonialiap** [comment] 2023-07-11 11:35
https://github.com/Expensify/App/pull/21067 has been merged

I tested and can't reproduce the error any more. Looks like it was resolved by the refactor

**Closed by sonialiap** 2023-07-11 11:35 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
