### ISSUE TITLE
[HOLD for payment 2024-01-09][$250] Mentions - @ Here icon is black

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33589] opened 2023-12-26 13:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to any chat.
2. Type @ here.

## Expected Result:
Here icon is green.

## Actual Result:
Here icon is black.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Bug6326135_1703592270063!Screenshot_2023-12-26_163901](https://github.com/Expensify/App/assets/115492554/0d6b4ae6-833f-451e-bd20-fb29b771d3d3)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f2330f066b567e3</li>
        <li>Upwork Job ID: 1739644027587080192</li>
        <li>Last Price Increase: 2023-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 28070446</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by Pujan92** [comment] 2023-12-26 14:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In mention list for here the icon is black

### What is the root cause of that problem?
In this [PR](https://github.com/Expensify/App/pull/30905) we have removed the fill property for the avatar.
https://github.com/Expensify/App/pull/30905/files#diff-3e66159ec7e545cdb519881ff0194d3e2151d3d3c9a963bf2b82e46b3119a92cL75

### What changes do you think we should make in order to solve the problem?
We can add the fill property with `fill={theme.success}` again here to make it a green icon.

https://github.com/Expensify/App/blob/de5a9435f97ca5fee0ead16fd38bdfc71da6582a/src/components/MentionSuggestions.tsx#L68-L74

**Comment by paultsimura** [comment] 2023-12-26 14:23
This was missed and should be fixed as a follow-up of the https://github.com/Expensify/App/issues/29067

**Comment by mountiny** [comment] 2023-12-26 22:26
Decreasing the price as this should be very simple fix from the regression PR.

@Pujan92 can you raise the PR quickly?

**Comment by paultsimura** [comment] 2023-12-26 22:30
If @Pujan92 is unavailable, I can make the quick PR.
Didn't bother posting a full-scale [proposal](https://github.com/Expensify/App/issues/33589#issuecomment-1869579464) because I thought it would be handled by the original PR author.

**Comment by mountiny** [comment] 2023-12-26 22:33
Yeah they are ooo though so I have decreased the reward. 

I think that given this is a deploy blocker and you are available, I am going to assign you. This is not common so sorry to @Pujan92 that this was not handled earlier when they were on but we need to treat this with urgency

**Comment by mountiny** [comment] 2023-12-26 22:33
@paultsimura Can you raise the PR quickly please?

**Comment by paultsimura** [comment] 2023-12-26 22:34
Yes, I'm on it

**Comment by paultsimura** [comment] 2023-12-26 22:40
The PR is ready, adding the screenshots now: https://github.com/Expensify/App/pull/33634

**Comment by Pujan92** [comment] 2023-12-27 01:40
> Yeah they are ooo though so I have decreased the reward.
> 
> I think that given this is a deploy blocker and you are available, I am going to assign you. This is not common so sorry to @Pujan92 that this was not handled earlier when they were on but we need to treat this with urgency

No issues.. :)

**Comment by paultsimura** [comment] 2023-12-27 21:02
This caused a regression: https://github.com/Expensify/App/issues/33657
Creating a follow-up PR now.

**Comment by mountiny** [comment] 2024-01-09 22:27
This was a deploy blocker caused by a big change in how we handle images, using expo-image package. I think that has been stated already and there was bunch of other small issues so no need to dig more into that, the checklist can be omitted in this case

**Comment by Pujan92** [comment] 2024-01-10 14:23
@mountiny Am I eligible for partial compensation here for providing the proposal which is used?

**Comment by Pujan92** [comment] 2024-01-10 14:35
Agree, my bad. Sorry for the ask.

**Comment by mountiny** [comment] 2024-01-10 14:40
no problem, one has to try

**Comment by mountiny** [comment] 2024-01-18 19:57
@bfitzexpensify this should be $250 to @paultsimura  please

**Comment by michaelhaxhiu** [comment] 2024-01-18 21:09
I can step in for Ben!

**Comment by michaelhaxhiu** [comment] 2024-01-18 21:16
paid.

**Comment by michaelhaxhiu** [comment] 2024-01-18 21:16
Good to close?

**Comment by mountiny** [comment] 2024-01-19 15:42
I think so thanks!

**Closed by mountiny** 2024-01-19 15:43 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
