### ISSUE TITLE
[HOLD for payment 2023-01-05] [HOLD #13392] [$1000] Android - Avatar is not displayed on push notification

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12967] opened 2022-11-23 19:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12540

## Action Performed:
1. Sign into the Android app
2. Sign into another account on web and upload a custom profile picture for that account
3. Background the Android app
4. Send a message from the account signed in on web to the account signed in on Android
5. Verify that a push notification appears and that the notification appears a message style notification, including the avatar image of the web user.

## Expected Result:
Avatar image of the web user is displayed after received a push notification in Android app

## Actual Result:
Avatar image of the web user isn't displayed after received a push notification in Android app

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.30.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203633324-ac7e4d46-4d31-45c2-a62e-338725caa2ff.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~0171d7d835c1969527
- Upwork Job ID: 1598107016845291520

**Comment by arielgreen** [comment] 2022-11-30 16:57
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [ ] The "bug" is actually a bug 
- [ ] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [ ] The bug is reproducible, following the reproduction steps.
  - [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [ ] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  - [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [ ] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [ ] The GH was created by an Expensify employee or a QA tester 
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [ ] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by arielgreen** [comment] 2022-12-01 00:10
Reproduced following the steps in OP:
![image](https://user-images.githubusercontent.com/37308300/204934863-e3d763a2-39e8-4fb1-8aab-d11e08c8b261.png)

**Comment by StefanNemeth** [comment] 2022-12-01 16:39
I could reproduce the issue as well on the debug build and started to debug the issue.

The following error occurred when fetching the icon and appears to occur on Android O (onwards):

```
12-01 17:21:31.539 24579 24622 E NotificationProvider: Failed to fetch icon
12-01 17:21:31.539 24579 24622 E NotificationProvider: java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:706)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:81)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:139)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at android.graphics.Canvas.drawBitmap(Canvas.java:1604)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at com.expensify.chat.customairshipextender.CustomNotificationProvider.getCroppedBitmap(CustomNotificationProvider.java:110)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at com.expensify.chat.customairshipextender.CustomNotificationProvider.fetchIcon(CustomNotificationProvider.java:265)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at com.expensify.chat.customairshipextender.CustomNotificationProvider.applyMessageStyle(CustomNotificationProvider.java:151)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at com.expensify.chat.customairshipextender.CustomNotificationProvider.onExtendBuilder(CustomNotificationProvider.java:76)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at com.urbanairship.push.notifications.AirshipNotificationProvider.onCreateNotification(AirshipNotificationProvider.java:210)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at com.urbanairship.push.IncomingPushRunnable.postProcessPush(IncomingPushRunnable.java:196)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at com.urbanairship.push.IncomingPushRunnable.processPush(IncomingPushRunnable.java:144)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at com.urbanairship.push.IncomingPushRunnable.run(IncomingPushRunnable.java:97)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:50)
12-01 17:21:31.539 24579 24622 E NotificationProvider: 	at java.lang.Thread.run(Thread.java:1012)
```

To resolve the issue, we could convert the avatar to the desired bitmap (as used by the canvas we create in getCroppedBitmap)

```java
// android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationProvider.java
public Bitmap getCroppedBitmap(Bitmap bitmap) {
        bitmap = bitmap.copy(Config.ARGB_8888, true);
        // ...
}
```

Thats would resolve the bug as seen here.

![Screenshot_1669912402](https://user-images.githubusercontent.com/5003405/205109298-2312ed69-c3ac-4781-b20e-d77de224265e.png)

**Comment by robertjchen** [comment] 2022-12-06 06:33
Thanks for the proposal, it looks like this is indeed the source of the issue! Just out of curiosity, is there a reason why we don't use `PixelCopy`? https://bumptech.github.io/glide/doc/hardwarebitmaps.html

**Comment by StefanNemeth** [comment] 2022-12-06 11:02
> @StefanNemeth Thanks for the proposal, it looks like this is indeed the source of the issue! Just out of curiosity, is there a reason why we don't use `PixelCopy`? https://bumptech.github.io/glide/doc/hardwarebitmaps.html

According to the documentation PixelCopy allows for copy operations from [Surface](https://developer.android.com/reference/android/view/Surface) to [Bitmap](https://developer.android.com/reference/android/graphics/Bitmap) (e.g. for screenshots). We are dealing with bitmaps here so bitmap.copy is the proper way to do it afaik.

**Comment by robertjchen** [comment] 2022-12-06 11:14
Got it, that makes sense. @parasharrajat What are your thoughts on the above proposal? 🙏

**Comment by parasharrajat** [comment] 2022-12-06 20:17
I am not an Android native guy but can we just use `bitmap.setConfig(Config.ARGB_8888)` before drawing? it seems that it will have the same effect. 
https://github.com/Expensify/App/blame/main/android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationProvider.java#L107

I don't see where we create the Bitmap with `Hardware` config. It may be coming directly from AirShip.

**Comment by parasharrajat** [comment] 2022-12-06 20:47
Ok, Thanks for the explanation. I am good with both. I have asked internally to review it before we proceed.

**Comment by parasharrajat** [comment] 2022-12-06 21:21
Ok @StefanNemeth 's proposal looks good to me.

Cc: @robertjchen 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by cristipaval** [comment] 2022-12-06 21:37
Hey @robertjchen ! Just wanted to add here the reasoning why I internally confirmed that the solution is good:
The avatar is downloaded as a hardware bitmap (a new optimised bitmap added in Android O) but we crop it to make it circular. Crop operation uses software Canvas which doesn't support hardware bitmap rendering. @StefanNemeth solution basically converts the hardware bitmap into a software bitmap (`bitmap.copy(Config.ARGB_8888, true)`) which is successfully rendered by the Canvas.

**Comment by robertjchen** [comment] 2022-12-07 02:16
Thanks for the confirmation @cristipaval ! 

@dylanexpensify Let's move forward with hiring @StefanNemeth for this 👍

**Comment by StefanNemeth** [comment] 2022-12-07 04:28
Created the PR

**Comment by dylanexpensify** [comment] 2022-12-07 10:49
@StefanNemeth offer sent! @parasharrajat please apply when you get a moment 😄

**Comment by dylanexpensify** [comment] 2022-12-07 10:50
ah, @robertjchen looks like @arielgreen is the BZ member for this 😂

**Comment by StefanNemeth** [comment] 2022-12-29 19:27
Am I eligible for the 50% bonus as the PR created within a few hours after assignment was held?

**Comment by arielgreen** [comment] 2023-01-10 17:19
@StefanNemeth yes, I think that is fair. Paid. @parasharrajat sending offer now.

**Comment by Julesssss** [comment] 2023-01-11 10:53
> [@parasharrajat / @robertjchen] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

it's not clear to me what exactly caused the regression in the linked PR. I recall that notification profile images have been broken for weeks/months now.

**Comment by Julesssss** [comment] 2023-01-11 10:57
Ahhh, I see. That PR was January 2022, not 2023 😄

**Comment by arielgreen** [comment] 2023-01-12 23:40
All payments have been issued.

**Comment by Julesssss** [comment] 2023-01-16 10:48
Hey @arielgreen I think this should be added as a new regression test, as it ensures we test for custom profile pics as well as the default icons: 

**Ensure rounded profile images are displayed for notifications**
- _Android and iOS only_
- Sign in as a new account (userA) on the test platform (iOS/Android)
- Sign in as userB on a different device/browser/platformfor that account
- Background the app as userA
- Send a message from userB to userA
- Verify that a push notification appears for userA and that the notification includes a rounded default avatar
- As userB upload a custom profile picture for that account
- Send a message from userB to userA
- Verify that a push notification appears for userA and that the notification includes a rounded version of the custom profile image

**Comment by arielgreen** [comment] 2023-01-19 01:03
Discussing regression test [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1674090219501939).

**Comment by arielgreen** [comment] 2023-01-19 20:31
https://github.com/Expensify/Expensify/issues/256144

**Closed by arielgreen** 2023-01-19 20:31 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
