### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] [MEDIUM] Expensify Cards: Wrong report header for the money spent

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36186] opened 2024-02-08 22:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction (card expense)
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @coleaeason 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707427890816659

## Action Performed:
1. User A spends using the card
2. Submits the bill to B
3. Check the report header as user A
## Expected Result:
User A spent $x.xx should appear
## Actual Result:
User B spent $x.xx appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot 2024-02-08 at 1 30 54 PM](https://github.com/Expensify/App/assets/38435837/35fb989b-0b23-432e-acc6-64e7d2ab86d7)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016517b2a5bd47bbcb</li>
        <li>Upwork Job ID: 1762448288159342592</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 0</li>
<li>mollfpr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2024-02-09 13:56
Clarifying which wave [here](https://expensify.enterprise.slack.com/archives/C02NZ2HGJAZ/p1707486964101629)

**Comment by grgia** [comment] 2024-02-09 17:24
Wave 6 @CortneyOfstad !

**Comment by grgia** [comment] 2024-02-09 17:25
maybe related to https://github.com/Expensify/App/pull/35529 cc @mollfpr

**Comment by mollfpr** [comment] 2024-02-09 17:29
Looking 👀

**Comment by CortneyOfstad** [comment] 2024-02-09 18:30
Wahoo! Thanks @grgia!

**Comment by grgia** [comment] 2024-02-09 19:36
cc @abzokhattab

**Comment by CortneyOfstad** [comment] 2024-02-12 15:30
Not overdue 👍

**Comment by CortneyOfstad** [comment] 2024-02-14 15:53
Not overdue

**Comment by mollfpr** [comment] 2024-02-15 13:02
Sorry for the delay! I have checked and the PR https://github.com/Expensify/App/pull/35529 doesn't make this issue. We don't have a check or utils function showing the spender's name on the money spent. It's default to use the manager name instead.

Here's are another place that using the display name wrong.

![Screenshot 2024-02-15 at 20 01 07](https://github.com/Expensify/App/assets/25520267/98b1f5e6-c05a-4792-84de-f01aed87f885)
![Screenshot 2024-02-15 at 20 00 53](https://github.com/Expensify/App/assets/25520267/4e01da34-0c68-4df4-a964-2deb77de8a4b)
 
![Screenshot 2024-02-15 at 20 01 23](https://github.com/Expensify/App/assets/25520267/030ac81e-ee92-437b-aa1e-9500f2ea7fca)

**Comment by CortneyOfstad** [comment] 2024-02-15 19:25
Thanks for the update @mollfpr! Any thoughts on the above @grgia?

**Comment by grgia** [comment] 2024-02-21 01:35
Looks like we mistakenly only use the manager name, but it should be the spender in some cases. I think unless we make this change as an update from the linked PR, we can make this internal. It seems more like this is a forgotten case that we should have covered in that PR @mollfpr

**Comment by CortneyOfstad** [comment] 2024-02-22 15:14
@mollfpr in regards to @grgia's comment above, do you think a change is feasible from the [PR here](https://github.com/Expensify/App/pull/35529), or do you think it is better to just move this internally? I am not sure how much extra time/work a change/fix would be so looking for any insight you can provide. Thanks!

**Comment by CortneyOfstad** [comment] 2024-02-23 17:42
@mollfpr bump on the comment above ^^ Thanks!

**Comment by mollfpr** [comment] 2024-02-23 18:21
Sorry, I forgot to reply here.

---

The changes to cover this issue might be similar to the https://github.com/Expensify/App/pull/35529. We just need to add another check `hasNonReimbursableTransactions` and `isCardTransaction` to use the requestor name.

To create the case for non-reimbursable transactions spent and eCard is a bit tricky. Som I'm not sure if that's all the step we need, if yes then we can make it external.

**Comment by CortneyOfstad** [comment] 2024-02-26 14:28
Thanks @mollfpr! I am going to bring this up to the team and see where we get. Thank you!

**Comment by grgia** [comment] 2024-02-27 12:04
I made this external, I'm not sure if you'd like to take C+ since you have context here @mollfpr, other wise autoassigner assigned @aimane-chnaif

**Comment by mollfpr** [comment] 2024-02-27 12:05
@grgia Sounds good to me!

**Comment by godofoutcasts94** [comment] 2024-02-27 12:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Expensify Cards: Wrong report header for the money spent
### What is the root cause of that problem?
The root cause of the problem is here 
https://github.com/godofoutcasts94/App/blob/4816890a1c63b64f7c3278fbd39c92a8db0b2759/src/languages/en.ts#L626
we are showing `payer spent amount`
### What changes do you think we should make in order to solve the problem?

We need to change it to something like `spender spent amount`
### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment] 2024-02-27 12:12
I don't why my `permalink` is not working.

**Comment by grgia** [comment] 2024-02-27 12:15
To be clear, the `spender spent amount` pattern should be used for nonreimbursable transactions, i.e `transaction.reimbursable` === false

**Comment by godofoutcasts94** [comment] 2024-02-27 12:17
Yes yes

**Comment by godofoutcasts94** [comment] 2024-02-27 12:25
> > I don't why my `permalink` is not working.
> 
> you meant
> 
> https://github.com/Expensify/App/blob/cfa0ae37156208ebecdc6b2126464ec462271b76/src/languages/en.ts#L627
> 
> ?

Yes, correct that is not working @aimane-chnaif

**Comment by mollfpr** [comment] 2024-02-27 12:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The manager's name is shown instead of the spender on the report preview and the report header.

### What is the root cause of that problem?

Currently, we using the `managerID` to get the payer name, not just for the non-reimbursable transaction but also the card transaction.

https://github.com/Expensify/App/blob/cfa0ae37156208ebecdc6b2126464ec462271b76/src/components/ReportActionItem/ReportPreview.tsx#L201-L202

When the transaction is a non-reimbursable transaction/card transaction it should use the `ownerAccountID` for the payer name.

We also have the same place that uses the `managerID`.

https://github.com/Expensify/App/blob/cfa0ae37156208ebecdc6b2126464ec462271b76/src/libs/ReportUtils.ts#L2023-L2024

https://github.com/Expensify/App/blob/cfa0ae37156208ebecdc6b2126464ec462271b76/src/libs/ReportUtils.ts#L2325


### What changes do you think we should make in order to solve the problem?


We should add a check for non-reimbursable transactions and card transactions to use the correct spender name which is the `ownerAccountID` from the IOU report instead the `managerID`.

To align the update on the above three places, we can create a new utils function to return the manager or spender name with a parameter from the IOU report and transaction.


### What alternative solutions did you explore? (Optional)

**Comment by CortneyOfstad** [comment] 2024-02-28 15:46
@aimane-chnaif – looks like we have a few more proposals — can you please provide feedback by EOD today? Thanks!

**Comment by CortneyOfstad** [comment] 2024-02-29 20:06
Hi @joekaufmanexpensify! I am heading OoO and will be back March 11th, so reassigned to have someone keep this moving until I am back. At this stage, @aimane-chnaif is reviewing the proposals and should be providing feedback soon. Thanks!

**Comment by grgia** [comment] 2024-03-04 17:46
all yours @mollfpr !

**Comment by joekaufmanexpensify** [comment] 2024-03-05 15:04
@mollfpr is there an ETA for a PR here?

**Comment by joekaufmanexpensify** [comment] 2024-03-11 15:06
@CortneyOfstad I see you're back, so going to let you keep this one. LMK if there's anything else I can help with!

**Comment by mollfpr** [comment] 2024-03-12 12:27
Checking 👀

**Comment by CortneyOfstad** [comment] 2024-03-15 14:59
@grgia it shows that @mollfpr is waiting for confirmation on the PR [here](https://github.com/Expensify/App/pull/37773/files/e043a782537b345d840caef8737a76c8262ca9c1#r1521380559). Can you provide an update? Thanks!

**Comment by CortneyOfstad** [comment] 2024-03-22 13:52
@grgia bump on the above ^^^

**Comment by mollfpr** [comment] 2024-03-22 13:54
@CortneyOfstad The PR is approved https://github.com/Expensify/App/pull/37773#pullrequestreview-1954553540 but needs more internal testing.

**Comment by CortneyOfstad** [comment] 2024-04-03 15:03
@mollfpr Can you complete the checklist before EOD tomorrow? Thanks!

**Comment by CortneyOfstad** [comment] 2024-04-05 14:02
@mollfpr bump on the checklist 👍

**Comment by CortneyOfstad** [comment] 2024-04-05 14:02
## Payment Summary

@mollfpr to be paid $500 via NewDot
@aimane-chnaif paid $500 via Upwork

**Comment by mollfpr** [comment] 2024-04-05 19:57
Sorry for the delay @CortneyOfstad 

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

Not fully regression from https://github.com/Expensify/App/pull/35529 but we do some improvement and cover another case to show correct verb.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Log in to your account with the Expensify Card transaction ([tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com))
2. Go to the workspace chat with the transaction (https://staging.new.expensify.com/r/4612388815642526. If the transaction is settled, please create another Expensify Card transaction)
3. Verify the text on 3 places below correctly showing <requestor's name> spent
   - Alternate text on LHN
   - Report preview
   - Money report preview header
4. 👍 or 👎

**Comment by mollfpr** [comment] 2024-04-05 20:06
@CortneyOfstad The PR I worked for this issue has a [regression](https://github.com/Expensify/App/issues/39158) but I have fixed it https://github.com/Expensify/App/pull/39208

**Comment by CortneyOfstad** [comment] 2024-04-05 20:13
@mollfpr I don't see a regression listed. Only that it was merged without testing, which @Gonals handled. We should be good 👍 

I think the regression test looks good — @grgia any changes you would like to see made (if any)?

**Comment by JmillsExpensify** [comment] 2024-04-08 02:57
$500 approved for @mollfpr

**Comment by CortneyOfstad** [comment] 2024-04-08 13:23
Regression test created here — https://github.com/Expensify/Expensify/issues/386030

Thanks!

**Closed by CortneyOfstad** 2024-04-08 13:23 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
