### ISSUE TITLE
CRITICAL: [$500] No email received to the members invited to a room even sending custom message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30919] opened 2023-11-06 17:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699256664640499

## Action Performed:
1. Open app and login
2. Create a room and set up a custom welcome message
3. Invite a member to the room

## Expected Result:
Member will receive an email for joining the room
## Actual Result:
No email is received

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (4)](https://github.com/Expensify/App/assets/38435837/053d9cd8-0cb5-49d3-8b48-e3e947470b79)

![11](https://github.com/Expensify/App/assets/38435837/0049435c-335a-494d-989c-d52e944dbe2a)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139cc5970497422cf</li>
        <li>Upwork Job ID: 1721579344839163904</li>
        <li>Last Price Increase: 2023-11-13</li>
    </ul>
</details>

**Comment by marcochavezf** [comment] 2023-11-06 17:51
Coming from [here](https://expensify.slack.com/archives/C036QM0SLJK/p1699167324995859), I will assign myself to this issue to check it out today, probably it's a backend issue.

**Comment by NisargDeveloper** [comment] 2023-11-07 02:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Members are not receiving an email after joining


### What is the root cause of that problem?

It actually depends on what are you using to trigger an email. The issue relies in library/api itself. 

### What changes do you think we should make in order to solve the problem?

I gotta check the library/API service that we are using. If we are using external API then we gotta change or fix the we way are using.


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by dylanexpensify** [comment] 2023-11-07 09:36
Sounds good, thanks @marcochavezf!!

**Comment by marcochavezf** [comment] 2023-11-09 02:15
No update, I can check it out this tomorrow

**Comment by marcochavezf** [comment] 2023-11-11 02:22
No update, I will check it out this on Monday

**Comment by marcochavezf** [comment] 2023-11-14 00:12
Working on it

**Comment by dylanexpensify** [comment] 2023-11-14 09:43
Nice! Thanks @marcochavezf!

**Comment by marcochavezf** [comment] 2023-11-16 03:34
No update, focused on wave7 issues. I hope to continue with the PRs tomorrow

**Comment by marcochavezf** [comment] 2023-11-20 04:03
No update

**Comment by marcochavezf** [comment] 2023-11-21 22:46
Moving this to weekly, focused on wave7, I will continue with it in spare cycles

**Comment by quinthar** [comment] 2023-11-21 22:51
If you can't work on it now, can you unassign yourself so someone else can pick it up?

**Comment by dylanexpensify** [comment] 2023-11-22 09:35
agree ^, thanks @marcochavezf !

**Comment by marcochavezf** [comment] 2023-11-27 04:53
I missed these messages, apologies. Unassign myself in case someone wants to take this one, I started some implementation in a couple of linked PRs. Also, I'm almost done with the critical items for wave7 (maybe tomorrow the pending PRs will be done for review), if no one takes it I can continue with those PRs after wrapping up the other PRs.

**Comment by bondydaa** [comment] 2023-11-28 00:25
not really, I have another project I am trying to complete. 

I see there are open WIP PRs already, is this more important than the things that Marco is working on? If so then it should be reprioritized accordingly.

**Comment by marcochavezf** [comment] 2023-12-05 03:08
I already completed a critical item I was working on and I'm just waiting for review, so I can continue with this one tomorrow morning

**Comment by dylanexpensify** [comment] 2023-12-05 20:02
Nice, thanks @marcochavezf!

**Comment by marcochavezf** [comment] 2023-12-06 00:25
PRs are ready for review, we'd just need to corroborate if the copy is good to go

**Comment by marcochavezf** [comment] 2023-12-08 00:38
Created a new [PR](https://github.com/Expensify/Web-Expensify/pull/39984) (ready for review) to send the unread summary when a user is invited to a room either via member list or mentioned in the room.

**Comment by dylanexpensify** [comment] 2023-12-11 09:24
Nice! What's left here besides hat hitting prod, @marcochavezf ?

**Comment by marcochavezf** [comment] 2023-12-12 04:33
Ah the automated tests. I already added them, but Travis is failing because of bedrock connection issues again.

**Comment by marcochavezf** [comment] 2023-12-12 04:34
Also we have this weird error reported [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1702331995121639?thread_ts=1702002822.245799&cid=C066HJM2CAZ), where the subsequent messages in the public room are not sent to the invited accounts in the daily digest summary but can be considered as another bug.

**Comment by marcochavezf** [comment] 2023-12-12 22:30
- [Fixed](https://github.com/Expensify/Web-Expensify/pull/39984#issuecomment-1852906931) the automated tests, and Travis is passing now.
- Related to the subsequent messages not sent in the daily summary email, I got yesterday the emails:

![IMG_7648](https://github.com/Expensify/App/assets/6829422/37137660-e30e-4365-a50d-aba9c6af25e6)

 But when I was testing locally, I remember the daily summary was throwing an error because of the auth token type. We can retest on staging after the PR to fix this issue is deployed.

**Comment by dylanexpensify** [comment] 2023-12-13 08:47
Nice digging and work here! What's our expected ETA?

**Comment by mallenexpensify** [comment] 2023-12-18 21:49
> Hey @mallenexpensify, can you check the following copy for the email invitation?
 
Totally missed this, sorry @marcochavezf .  Do you know if we're sending emails when people are added to new workspaces and, if so, what the copy is for those?   I imagine we'll want to keep things consistent.

**Comment by quinthar** [comment] 2023-12-19 02:40
Let's close this issue, and create a new issue for sending UnreadMessageSummaries to unvalidated accounts, as that seems fundamentally different.

**Closed** 2023-12-19 02:40 UTC
Labels: Reviewing, Engineering, Daily, Internal, Waiting for copy, Bug

**Comment by mallenexpensify** [comment] 2023-12-19 05:04
> sending UnreadMessageSummaries to unvalidated accounts

I'm unfamiliar with this would the new issue just be
Expected - unvalidated accounts get email from message in room
Actual - No email being received when post in a room if account isn't validated? 

Also.. any idea what wave/VIP that'd be a part of? I'm unsure if want to create a new issue if it's just going to get closed cuz it's not directly associated with our roadmap
