### ISSUE TITLE
[HOLD for payment SEPT 23][$250] iOS - 2FA code input is hidden by keyboard when disabling 2FA

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48461] opened 2024-09-03 11:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validation PR** https://github.com/Expensify/App/pull/48030
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to Account settings > Security,
3. Tap Disable 2FA.

## Expected Result:
2FA code input will not be hidden by keyboard when disabling 2FA

## Actual Result:
2FA code input is hidden by keyboard when disabling 2FA

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bb4e0e29-4a4f-497c-a57e-ab88c4b532fd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831813205395072237</li>
        <li>Upwork Job ID: 1831813205395072237</li>
        <li>Last Price Increase: 2024-09-05</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103915601</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by Julesssss** [comment] 2024-09-03 12:10
This is a new step in the process and shouldn't block deployment, as users can still enter the code (without visible confirmation).

**Comment by bernhardoj** [comment] 2024-09-03 12:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
2FA code is behind the keyboard.

### What is the root cause of that problem?
In the code page, we disable the keyboard avoiding view which is required for iOS to push up the button.
https://github.com/Expensify/App/blob/aa693719e19c468983a090e0c8a7bb2cec8ee76c/src/pages/settings/Security/TwoFactorAuth/Steps/GetCode.tsx#L29-L31

### What changes do you think we should make in order to solve the problem?

Enable the keyboard avoiding view by removing the `shouldEnableKeyboardAvoidingView` prop.

**Comment by ItxAltaf** [comment] 2024-09-06 03:43
try like that

<KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : null}
      >
...
<TextInput>
</KeyboardAvoidingView>

**Comment by Julesssss** [comment] 2024-09-10 16:26
Awiating proposals and review

**Comment by alitoshmatov** [comment] 2024-09-11 14:56
Looks straightforward fix, we can go with @bernhardoj 's proposal [here](https://github.com/Expensify/App/issues/48461#issuecomment-2326369448)

C+ reviewed 🎀 👀 🎀

**Comment by bernhardoj** [comment] 2024-09-11 15:58
PR is ready

cc: @alitoshmatov

**Comment by alitoshmatov** [comment] 2024-09-17 18:54
Deployed to [production](https://github.com/Expensify/App/pull/48993#issuecomment-2353604925) on 16th

**Comment by abekkala** [comment] 2024-09-20 16:17
### PAYMENT SUMMARY FOR SEPT 23

- Fix: @bernhardoj [$250, if no regresssions] payment via NewDot
- PR Review: @alitoshmatov [$250, if no regresssions] [Offer](https://www.upwork.com/nx/wm/workroom/38355198/overview)

**Comment by abekkala** [comment] 2024-09-23 20:37
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@alitoshmatov] The PR that introduced the bug has been identified. Link to the PR: 
- [ ] [@alitoshmatov] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 
- [ ] [@alitoshmatov] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.
- [ ] [@alitoshmatov] Determine if we should create a regression test for this bug.
- [ ] [@alitoshmatov] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@abekkala] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

___

@alitoshmatov can you complete checklist so I can issue payment - thank you!

**Comment by abekkala** [comment] 2024-09-26 12:24
@alitoshmatov, can you complete the checklist above, please?

**Comment by abekkala** [comment] 2024-10-02 17:43
@alitoshmatov just a friendly bump here. Please complete the checklist above and I can issue payment. (before the offer expires in Upwork)

**Comment by alitoshmatov** [comment] 2024-10-06 08:23
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/48030
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/48030/files#r1788965261
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. I think no need since it wasn't regression but rather incomplete feature

**Comment by alitoshmatov** [comment] 2024-10-06 08:23
@abekkala Sorry for late response

**Comment by abekkala** [comment] 2024-10-07 14:24
@alitoshmatov payment sent and contract ended - thank you! 🎉

**Closed by abekkala** 2024-10-07 14:24 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by bernhardoj** [comment] 2024-10-07 14:26
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-10-07 19:50
$250 approved for @bernhardoj
