### ISSUE TITLE
[Hold on #19076] Details page opened on scanning share QR does not display '+' in email and user profile and user name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19062] opened 2023-05-16 19:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app in mac safari/mac chrome/ windows chrome
2. Open settings
3. Open share code
4. On android device, scan the QR code and open the URL
5. Observe that details page opened does not display '+' in email and displays default profile even though profile is set

## Expected Result: 
App should display email with all characters, it should display profile name if present and also display proper profile if set on scanning of share QR
## Actual Result: 
App does not display set user name, displays default profile and does not display characters like '+' in email on details page opened on scanning QR

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14-9
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/200a51f9-39c9-4eed-832b-5328e75d99a6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684164092067469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190dc680faf2b76f3</li>
        <li>Upwork Job ID: 1660675291499335680</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by hungvu193** [comment] 2023-05-17 03:48
I believe this issue has same root cause with this one (https://github.com/Expensify/App/issues/19062)

**Comment by michaelhaxhiu** [comment] 2023-05-19 20:41
Looking :)

**Comment by michaelhaxhiu** [comment] 2023-05-19 20:44
@robertjchen do you agree with @hungvu193? Basically can we fix this issue and https://github.com/Expensify/App/issues/19076 with the same PR?

**Comment by michaelhaxhiu** [comment] 2023-05-22 13:46
Figure it's easier to manually assign Robert since he's already assigned to the https://github.com/Expensify/App/issues/19076 and the fix that Hungvu is assigned will address the problems.

**Comment by robertjchen** [comment] 2023-05-22 15:50
Yep, that is correct, the PR should address this error case 👍

**Comment by michaelhaxhiu** [comment] 2023-05-22 15:53
Kewl so I will...:
- Mark this `External`
- Remove `Help wanted` label
- Add `Hold on #19076` to the title. 
- Once that #19076 deploys, I will re-test this one.
- After it's all resolved, I will pay the bug reporter.
- Let's figure out how to fairly Compensate HungVu for fixing 3 issues with 1 PR.

**Comment by michaelhaxhiu** [comment] 2023-05-22 15:56
https://github.com/Expensify/App/issues/19076#issuecomment-1557416627

PR was submitted here

**Comment by robertjchen** [comment] 2023-05-24 08:46
That makes sense to me, in that case I think we can close this out for now.

**Comment by dhanashree-sawant** [comment] 2023-05-25 04:01
Hi @robertjchen, @parasharrajat had pointed out that it should be provided reporting bonus, can you keep it open until then?

**Comment by robertjchen** [comment] 2023-05-25 04:10
Yes, re-opening for now for followup on the above cc: @michaelhaxhiu ^

**Comment by robertjchen** [comment] 2023-05-29 17:25
Pending reporting bonus

**Comment by robertjchen** [comment] 2023-05-31 09:51
Pending reporting bonus payout cc: @michaelhaxhiu

**Comment by michaelhaxhiu** [comment] 2023-05-31 14:50
Apologies, looking :)

**Comment by michaelhaxhiu** [comment] 2023-05-31 16:13
Paid!

**Closed by michaelhaxhiu** 2023-05-31 16:13 UTC
Labels: External, Daily, Bug
