### ISSUE TITLE
[HOLD for payment 2023-09-21] [$1000] Add avatar details to the Lounge Access Page

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#24381] opened 2023-08-10 17:23 UTC
To help identify customers and address #nocreeps violations, we're going to add the avatar to the lounge access page for when users check in.

1. Update the lounge access page to include the avatar, display name, and login like this mockup

![image](https://github.com/Expensify/App/assets/30609178/5ed67820-be30-4e0a-b195-6a36e7719636)

[Internal issue](https://github.com/Expensify/Expensify/issues/300972)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb19c0e49400d07e</li>
        <li>Upwork Job ID: 1689690079128702976</li>
        <li>Last Price Increase: 2023-08-31</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Contributor | 26439127</li>
</ul></li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2023-08-10 17:33
Accidentally added the 'External' label twice, removed the second C+ assignee

**Comment by Pujan92** [comment] 2023-08-10 17:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add avatar details in the lounge access page

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?
We need to use `withCurrentUserPersonalDetails` for getting the current user personal details and create the `View` which will have the avatar, display name and login with negative margin to overlap with the above svg animation. For opacity change, we need to create an extra `View` with absolute position to match with the mockup.

**Comment by jeet-dhandha** [comment] 2023-08-10 17:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- New Feature Request: To show Profile Details in Lounge Access Page as well.

### What is the root cause of that problem?
- Its a new feature request.

### What changes do you think we should make in order to solve the problem?
- We will use `withCurrentUserPersonalDetails` to get the user's details and also the code we have in `InitialSettingsPage.js`.
- InitialSettingsPage.js code also handles skeleten view so we will use that code to show the skeleten view until we get the user's details. ( We can remove navigation to profile screen if needed)
- Finally we need to blur the bottom part of the illustration. (Currently don't have any idea but will find a way)/

<details>
<summary> Initial Settings page code </summary>

https://github.com/Expensify/App/blob/ed0e54667ae19c8ad4e73c18ae2bfbc5a0b9d13d/src/pages/settings/InitialSettingsPage.js#L338-L383

</details>


### What alternative solutions did you explore? (Optional)
- N/A

**Comment by puneetlath** [comment] 2023-08-10 17:53
@thienlnam do you want to be the CME for this since you're proposing the feature?

**Comment by thienlnam** [comment] 2023-08-10 17:54
Sure I can take it

**Comment by pradeepmdk** [comment] 2023-08-10 19:01
can i work this as this an feature request so i think no need formal proposal.

**Comment by puneetlath** [comment] 2023-08-10 19:09
@pradeepmdk you should still make a proposal for how you'll implement it if you'd like the job.

**Comment by pradeepmdk** [comment] 2023-08-10 19:20
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add avatar details to the Lounge Access Page
### What is the root cause of that problem?

new feature request


### What changes do you think we should make in order to solve the problem?

- we can use withCurrentUserPersonalDetails from onyx wrapped component
- for Illustrated we can reuse IllustratedHeaderPageLayout.js form workspace list
-  for Layout we can use `View` and `Text` Component

**Comment by Santhosh-Sellavel** [comment] 2023-08-10 21:11
All the proposals have a general outline, But I would like more details specifically on how we are planning to add the user details above the illustration.

Thanks!

**Comment by pradeepmdk** [comment] 2023-08-11 02:44
@Santhosh-Sellavel proposal updated https://github.com/Expensify/App/issues/24381#issuecomment-1673780098

**Comment by jeet-dhandha** [comment] 2023-08-11 04:21
@Santhosh-Sellavel Updated Proposal with:

- Output Screenshots
- Extra points on how to handle Fade View and Positioning of Profile.
- Compare Changes Link on what code needs to be added. 

Please give suggestions if needed.

**Comment by Pujan92** [comment] 2023-08-11 14:17
@Santhosh-Sellavel proposal updated https://github.com/Expensify/App/issues/24381#issuecomment-1673650212.

**Comment by tjferriss** [comment] 2023-08-15 05:19
Un-assigning myself as @puneetlath is handling BugZero role.

**Comment by Santhosh-Sellavel** [comment] 2023-08-15 20:20
Sorry for the delay here. 

After checking the proposals all proposals should do the job, @pradeepmdk [proposal](https://github.com/Expensify/App/issues/24381#issuecomment-1673780098) has it all required. And I like the idea of overlayComponent for rendering the Avatar and username. Over negative margin idea from other proposals. 

cc: @thienlnam Let me know your thoughts

**Comment by jeet-dhandha** [comment] 2023-08-15 21:54
@Santhosh-Sellavel Just a small request for you, can you review all other proposals and point out the disadvantage they have over the selected proposal

**Comment by pradeepmdk** [comment] 2023-08-16 13:51
![Screenshot 2023-08-16 at 7 20 12 PM](https://github.com/Expensify/App/assets/16595846/3f712858-0115-4f23-a057-b9350ebfffca)
@Pujan92  we can  do without negative margin

**Comment by Pujan92** [comment] 2023-08-16 14:20
@pradeepmdk I assume you have increased the top margin/padding of the content which starts with "You qualify...". If this is the case then it is the other way around only. So this leads to if we increase more content for the user details you need to adjust or increase more margin/padding as the content is set with the absolute position. Whereas this won't be the situation when we set relative position for the user details content. does this makes sense?

**Comment by pradeepmdk** [comment] 2023-08-16 15:21
@Pujan92 I am not using margin/padding for content  only using flex for rendering the content

**Comment by shawnborton** [comment] 2023-08-16 15:22
Looks like the avatar needs to be a bit bigger too.

**Comment by pradeepmdk** [comment] 2023-08-16 15:27
@shawnborton this is bigger image in our app  same size in the profile screen
 `avatarSizeLarge: 80,`
```javascript

 avatarLarge: {
        width: variables.avatarSizeLarge,
        height: variables.avatarSizeLarge,
    },

```

**Comment by shawnborton** [comment] 2023-08-16 15:32
Fair point, what if we update those to be 100x100 everywhere?

**Comment by pradeepmdk** [comment] 2023-08-16 15:38
let me list where our this changes reflacted

**Comment by Pujan92** [comment] 2023-08-16 15:45
@pradeepmdk can you plz explain when you use absolute View for the user details part, how the below content goes down with flex without setting any margin/padding between Lottie and content?

<img width="269" alt="Screenshot 2023-08-16 at 4 17 40 PM" src="https://github.com/Expensify/App/assets/14358475/c7249990-2e4e-4996-af33-9d20f284dc7c">

**Comment by pradeepmdk** [comment] 2023-08-16 15:58
@Pujan92 
you don't need to move the content to the bottom 
you can use `locations`
```javascript
<LinearGradient
                    locations={[0, 0.73]}
                    colors={['transparent', themeColors.appBG, ]}
                    style={[styles.flex1, styles.justifyContentEnd, styles.alignItemsCenter]}
                >
                   {profile()}
                </LinearGradient>
```

**Comment by Pujan92** [comment] 2023-08-16 16:19
> @Pujan92 you don't need to move the content to the bottom you can use `locations`
>                     locations={[0, 0.73]}
>                             <View style={[styles.alignItemsCenter, styles.pRelative, styles.pb8, styles.justifyContentEnd, 

Exactly, my point here is that we need to adjust `locations` and `styles.pb8`(which you applied for the space I am mentioning) whenever we have a change in the content size of the user details part. Due to this, I am not considering it as a preferable solution. 
In contrast to above, I am suggesting the overlay only on the Lottie animation part and negative margin for the relative user details View. With that, we don't need to use/adjust locations or extra paddings.

I am not sure whether @Santhosh-Sellavel @thienlnam are following what I am trying to highlight.

**Comment by Santhosh-Sellavel** [comment] 2023-08-16 17:09
Thanks, everyone for the active discussion.

Sorry @jeet-dhandha. 

I don't see a disadvantage in any of the proposals. We have two similar proposals yours & @Pujan92 only difference is the difference in linear background. I liked the overlay idea In @pradeepmdk's proposal as it comes in handy for other pages too.

Regarding @Pujan92's [thoughts](https://github.com/Expensify/App/issues/24381#issuecomment-1680908774) 

I don't see any negative in using locations. 

But setting up the bottom padding seems off to me, 
Where would this go @pradeepmdk ?

                          `  <View style={[styles.alignItemsCenter, styles.pRelative, styles.pb8, styles.justifyContentEnd, StyleUtils.getBackgroundColorStyle(backgroundColor)]}>

`

**Comment by Pujan92** [comment] 2023-08-16 17:24
I think the fade-out needs to be applied on only Lottie, otherwise it seems to be like a workaround to me as need to adjust as per the content height. For eg. if in the user details we add some more content then location 0.73 may be starts after the animation, so no effect can be seen on Lottie.

**Comment by pradeepmdk** [comment] 2023-08-16 20:33
@Santhosh-Sellavel 
without `styles.pb8` still working
<img width="383" alt="Screenshot 2023-08-17 at 2 01 58 AM" src="https://github.com/Expensify/App/assets/16595846/594c4db9-5f29-4924-9ac3-90aaa98a8631">

**Comment by shawnborton** [comment] 2023-08-16 20:36
That feels like it doesn't quite match the mockup though - the header area with the lounge illustration feels too short.

**Comment by pradeepmdk** [comment] 2023-08-16 21:21
@shawnborton Yes that's why I added `styles.pb8`

**Comment by Santhosh-Sellavel** [comment] 2023-08-16 21:26
@pradeepmdk where `overlayComponentStyle` is used?

**Comment by pradeepmdk** [comment] 2023-08-16 21:28
@Santhosh-Sellavel here 
```javascript
                            <View style={[styles.alignItemsCenter, styles.pRelative, styles.justifyContentEnd, StyleUtils.getBackgroundColorStyle(backgroundColor), ...overlayComponentStyle]}>

```

**Comment by Santhosh-Sellavel** [comment] 2023-08-16 21:43
Thank you @pradeepmdk!

**Comment by shawnborton** [comment] 2023-08-16 23:05
Can you share the latest screenshot of this?

**Comment by pradeepmdk** [comment] 2023-08-16 23:16
![Screenshot 2023-08-17 at 4 40 39 AM](https://github.com/Expensify/App/assets/16595846/ff6c8cdc-b912-45c4-93d0-7bbab9d97ade)

if we need more space we can increase the  padding-bottom

and `avatarLarge` used those places
https://github.com/Expensify/App/blob/b07cbefe04ab2f7d4d815ffa2cb1a082c6ea4950/src/components/AvatarWithImagePicker.js?#L236
https://github.com/Expensify/App/blob/b07cbefe04ab2f7d4d815ffa2cb1a082c6ea4950/src/components/RoomHeaderAvatars.js?#L47

https://github.com/Expensify/App/blob/b07cbefe04ab2f7d4d815ffa2cb1a082c6ea4950/src/pages/DetailsPage.js?#L158

https://github.com/Expensify/App/blob/b07cbefe04ab2f7d4d815ffa2cb1a082c6ea4950/src/pages/ProfilePage.js?#L169

https://github.com/Expensify/App/blob/b07cbefe04ab2f7d4d815ffa2cb1a082c6ea4950/src/pages/settings/InitialSettingsPage.js?#L352
https://github.com/Expensify/App/blob/b07cbefe04ab2f7d4d815ffa2cb1a082c6ea4950/src/pages/workspace/WorkspaceInitialPage.js?#L210

https://github.com/Expensify/App/blob/b07cbefe04ab2f7d4d815ffa2cb1a082c6ea4950/src/pages/workspace/WorkspaceSettingsPage.js

**Comment by shawnborton** [comment] 2023-08-16 23:18
Yeah, that doesn't match up with the mockup. Can you take another look please?

**Comment by pradeepmdk** [comment] 2023-08-16 23:24
![Screenshot 2023-08-17 at 4 53 43 AM](https://github.com/Expensify/App/assets/16595846/86424e04-d860-4ec2-ab0d-c183eb3c0349)

**Comment by shawnborton** [comment] 2023-08-16 23:26
Nice, that feels better!

**Comment by pradeepmdk** [comment] 2023-08-16 23:30
can I create the PR?

**Comment by puneetlath** [comment] 2023-08-16 23:36
@thienlnam you good with @pradeepmdk moving forward? As @Santhosh-Sellavel recommended [here](https://github.com/Expensify/App/issues/24381#issuecomment-1679552891).

**Comment by Santhosh-Sellavel** [comment] 2023-08-17 05:28
On hold please

**Comment by pradeepmdk** [comment] 2023-08-17 05:36
@Santhosh-Sellavel  updated https://github.com/Expensify/App/issues/24381#issuecomment-1681294421 checked all the platforms as well.

paddingBottom is used for just increase the illustration height

**Comment by Pujan92** [comment] 2023-08-17 13:34
Sorry if I am stretching a bit but just to make the last point, @Santhosh-Sellavel they are using the bottom padding/margin to fulfill the content of the user details instead allow taking the required height by the content. So in the future whenever we reduce/increase the content for the user details we do need to adjust that padding/margin to fulfill the content again.

<img width="280" alt="Screenshot 2023-08-17 at 7 03 16 PM" src="https://github.com/Expensify/App/assets/14358475/debb7772-b8df-4e15-abe1-bddecfeb3fc8">

**Comment by Santhosh-Sellavel** [comment] 2023-08-17 20:14
No worries @Pujan92
Won't we need to change the Negative offset if the UserDetails content changes?

@pradeepmdk 
it's really off seeing props `overlayComponent` and a style. And I agree we might need to change the location when the content size is. I see this is a bit overengineering, maybe a negative offset is better here.

**Comment by Santhosh-Sellavel** [comment] 2023-08-17 20:16
@shawnborton To confirm the overlay user details component's background should have a gradient style right?

**Comment by shawnborton** [comment] 2023-08-17 21:31
Yup, please refer to the mock.

**Comment by Pujan92** [comment] 2023-08-18 06:46
> @Pujan92 Won't we need to change the Negative offset if the UserDetails content changes?

No @Santhosh-Sellavel , content initial position remains the same most probably so we don't need to change the offset. 
I think the main idea is to give an aesthetic feeling to the user by placing some content on the animation with the fading. So the gradient might be applied to the animation part but not to the user details bg. @shawnborton correct me if I am wrong.

**Comment by jeet-dhandha** [comment] 2023-08-18 06:53
@Santhosh-Sellavel Would you mind taking a peek at my proposal?https://github.com/Expensify/App/issues/24381#issuecomment-1673650589

**Comment by Santhosh-Sellavel** [comment] 2023-08-18 17:07
> @Santhosh-Sellavel Would you mind taking a peek at my proposal?[#24381 (comment)](https://github.com/Expensify/App/issues/24381#issuecomment-1673650589)

@jeet-dhandha Did I miss something I've already reviewed yours

> We have two similar proposals yours & @Pujan92 only difference is the difference in linear background.

**Comment by Santhosh-Sellavel** [comment] 2023-08-18 17:15
@shawnborton I've checked the mark, just to be sure asked. 
After checking again I infer 
- Only part of the user details i.e only the avatar is shown above the Lottie
- Comparing the mock with the existing one, we added a gradient to the Lottie

Right?

**Comment by shawnborton** [comment] 2023-08-18 17:24
We added a gradient as a separate box that sits on top of the lottie animation, but aligned to the bottom of it.

**Comment by shawnborton** [comment] 2023-08-21 17:16
Figma file is [here](https://www.figma.com/file/vwDE2f4cboyl1d9TkOV913/Lounge-Access?type=design&node-id=4%3A788&mode=design&t=V23JLOzbSpG7yToD-1) if that helps.

Maybe this is helpful too:
<img width="664" alt="image" src="https://github.com/Expensify/App/assets/2319350/484b3cae-60b4-426a-8a76-7b3dd25d2035">

<img width="547" alt="image" src="https://github.com/Expensify/App/assets/2319350/0c97d385-cd8c-4ed8-b225-bb4d839d7e7e">


The gradient just covers the entire animation. The 100x100 avatar is centered and anchored to the bottom of the wrapper that has the animation and gradient. cc @Expensify/design

**Comment by jeet-dhandha** [comment] 2023-08-22 05:16
> Thanks, everyone for the active discussion.
> 
> Sorry @jeet-dhandha.
> 
> I don't see a disadvantage in any of the proposals. We have two similar proposals yours & @Pujan92 only difference is the difference in linear background. I liked the overlay idea In @pradeepmdk's proposal as it comes in handy for other pages too.
> 
> Regarding @Pujan92's [thoughts](https://github.com/Expensify/App/issues/24381#issuecomment-1680908774)
> 
> I don't see any negative in using locations.
> 
> But setting up the bottom padding seems off to me, Where would this go @pradeepmdk ?
> 
> ```js
> <View style={[styles.alignItemsCenter, styles.pRelative, styles.pb8, styles.justifyContentEnd, StyleUtils.getBackgroundColorStyle(backgroundColor)]}>
> ```

As you wish 👍

**Comment by Santhosh-Sellavel** [comment] 2023-08-22 18:38
Looking at all proposals again.  We can get the idea for implementation from @Pujan92's [proposal](https://github.com/Expensify/App/issues/24381#issuecomment-1673650212) or @jeet-dhandha's [proposal](https://github.com/Expensify/App/issues/24381#issuecomment-1673650589) 

Regarding the Gradient approach, I prefer a component over the static SVG file as suggested by @jeet-dhandha. As when the theme changes gradient should be on par with the new theme. So we can go with @Pujan92 here.

Now coming to the gradient part as a component. We have two suggestions from @Pujan92 & @pradeepmdk  one from using
-  library react-native-linear-gradient recently added
- https://medium.com/@ibrahimozdogan/adding-gradient-in-react-native-f75ddd02aea4 which uses react-native-svg

If we can come up with a component to add a gradient using react-native-svg. We can remove `react-native-linear-gradient` for good, thoughts @Pujan92  @thienlnam?

**Comment by shawnborton** [comment] 2023-08-22 18:44
We might want to pause on accepting proposals right now, as we might change up the overall structure of this page. cc @dannymcclain

**Comment by puneetlath** [comment] 2023-08-27 17:52
I added the hold to the title. Should we assign this issue to @dannymcclain in the meantime?

**Comment by shawnborton** [comment] 2023-08-28 10:49
That makes sense to me. This is what we landed on in the other issue:
<img width="1075" alt="image" src="https://github.com/Expensify/App/assets/2319350/d7a20bc4-0324-42ae-91ba-9f1b3bd872dd">


So we are probably good to go ahead with the changes, just notice that we slightly changed the gradient/illustration style on the top so that we aren't fading out to dark.

**Comment by pradeepmdk** [comment] 2023-08-28 11:02
@Santhosh-Sellavel  can you check my proposal https://github.com/Expensify/App/issues/24381#issuecomment-1681233321 and without out padding I can able to do it now

**Comment by Santhosh-Sellavel** [comment] 2023-08-28 19:17
@pradeepmdk Can you please submit an updated proposal in a new comment, thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-08-28 19:22
@shawnborton What's the other issue mentioned [here](https://github.com/Expensify/App/issues/24381#issuecomment-1695477376)

> Just notice that we slightly changed the gradient/illustration style on the top so that we aren't fading out to dark.

What's the new style now, can you throw some clarity on that, thanks!

**Comment by shawnborton** [comment] 2023-08-28 19:27
Yes, please see mockups [here](https://github.com/Expensify/App/issues/24381#issuecomment-1695477376)

**Comment by Santhosh-Sellavel** [comment] 2023-08-28 19:40
@shawnborton Yes I've seen that, but what's the new change in `gradient/illustration style`?

**Comment by shawnborton** [comment] 2023-08-28 19:41
Here is a side-by-side:
<img width="1028" alt="image" src="https://github.com/Expensify/App/assets/2319350/4e0a2be8-2295-4944-88ca-ceec8cb615d1">

**Comment by shawnborton** [comment] 2023-08-28 19:54
The gradient isn't in production, so I guess a more correct comparison would be this: 
<img width="681" alt="image" src="https://github.com/Expensify/App/assets/2319350/f99d6f3e-10b4-4667-a6f5-93c42334ec9d">


Then in the other issue, we're going to add the ability to check in, which looks like this: 
<img width="659" alt="image" src="https://github.com/Expensify/App/assets/2319350/e107746a-2282-4bd7-8713-8e25c1cd3384">

So again, this issue is only about adding the avatar + name + login on top of the animated illustration. Figma is [here](https://www.figma.com/file/vwDE2f4cboyl1d9TkOV913/Lounge-Access?type=design&node-id=42%3A209683&mode=design&t=35ewijAUTzgpXluJ-1).

**Comment by Santhosh-Sellavel** [comment] 2023-08-28 20:08
Thanks, all good!

**Comment by Pujan92** [comment] 2023-08-28 21:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add avatar details in the lounge access page

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?
1. Use `withCurrentUserPersonalDetails` for getting the current user personal details and add `session` in `withOnyx` to fetch from Onyx if required to show the email as we do the same for `InitialSettingsPage`.
https://github.com/Expensify/App/blob/cceb862e4566b10cc5afecf1d016af45f87177d6/src/pages/settings/InitialSettingsPage.js#L379

2. To make the overlay content on the Illustration we need to use linear-gradient with colors(#00214000, # 002140 -- provided in the figma) And absolute `View` aligned/justified centered  which contains the user details. Assign these to the function called `overlayContent` in the `LoungeAccessPage` and pass it to the `IllustratedHeaderPageLayout`.

3. In the `IllustratedHeaderPageLayout`, After `Lottie` conditionally render the passed `overlayContent`.
```
{overlayContent && overlayContent()}
```
https://github.com/Expensify/App/blob/cceb862e4566b10cc5afecf1d016af45f87177d6/src/components/IllustratedHeaderPageLayout.js#L59-L66

<img width="376" alt="Screenshot 2023-08-29 at 02 35 39" src="https://github.com/Expensify/App/assets/14358475/8c830702-d324-42cd-ae6e-4cc8a6cc08e2">

**Comment by pradeepmdk** [comment] 2023-08-28 22:46
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add avatar details to the Lounge Access Page
### What is the root cause of that problem?

new feature request


### What changes do you think we should make in order to solve the problem?

- we can use withCurrentUserPersonalDetails from onyx wrapped component
- for Illustrated we can reuse `IllustratedHeaderPageLayout.js` from the workspace list
-  for Layout we can use `View` and `Text` Component
- for linear gradient on opacity gradient we can use `react-native-svg `https://medium.com/@ibrahimozdogan/adding-gradient-in-react-native-f75ddd02aea4
  or we can `react-native-linear-gradient` recently added to our project.

https://github.com/Expensify/App/blob/8d84c23ae3a21130a540794104313b2f7e7e6b6a/src/pages/settings/Profile/LoungeAccessPage.js
for adding user details in the Illustrated we need to set the parent view should to` position: relative` and the user view should be `position: absolute ` 
in the `IllustratedHeaderPageLayout.js` we add overlayComponent with `position: absolute `  like footer


```javascript
  <View style={styles.overscrollSpacer(backgroundColor, windowHeight)} />
                            <View style={[styles.alignItemsCenter, styles.pRelative, styles.justifyContentEnd, StyleUtils.getBackgroundColorStyle(backgroundColor)]}>
                                <Lottie
                                    source={illustration}
                                    style={styles.w100}
                                    autoPlay
                                    loop
                                />
                                {!_.isNull(overlayComponent) && <View style={[styles.loungeAccess]}>
                                    {overlayComponent}
                                </View>}
                            </View>
                            <View style={[styles.pt5]}>{children}</View>
                        </ScrollView>
                        {!_.isNull(footer) && <FixedFooter>{footer}</FixedFooter>}
``` 
and we need to create an overlay component with user Details that will pass from https://github.com/Expensify/App/blob/8d84c23ae3a21130a540794104313b2f7e7e6b6a/src/pages/settings/Profile/LoungeAccessPage.js

```javascript
 <IllustratedHeaderPageLayout
            title={translate('loungeAccessPage.loungeAccess')}
            onBackButtonPress={() => Navigation.goBack(ROUTES.SETTINGS)}
            illustration={LottieAnimations.ExpensifyLounge}
            overlayComponent={<LinearGradient
                    colors={['#00214000', '#002140' ]}
                    style={[styles.flex1, styles.justifyContentEnd, styles.alignItemsCenter]}
                >
                   {profile()}
                </LinearGradient>}
        >
```

**Comment by Santhosh-Sellavel** [comment] 2023-08-29 22:18
@thienlnam 

Both @Pujan92's [proposal](https://github.com/Expensify/App/issues/24381#issuecomment-1696418777) & @pradeepmdk 's [proposal](https://github.com/Expensify/App/issues/24381#issuecomment-1696528517) are valid ones here!

**Comment by Santhosh-Sellavel** [comment] 2023-08-30 18:29
Bump @pradeepmdk @Pujan92

**Comment by Pujan92** [comment] 2023-08-31 13:04
> > Now coming to the gradient part as a component. We have two suggestions from @Pujan92 & @pradeepmdk one from using
> > library react-native-linear-gradient recently added
> > https://medium.com/@ibrahimozdogan/adding-gradient-in-react-native-f75ddd02aea4 which uses react-native-svg
> > If we can come up with a component to add a gradient using react-native-svg as suggested in second option above.
> > We can remove react-native-linear-gradient for good, thoughts @Pujan92
> 
> @Pujan92 @pradeepmdk thoughts?

@Santhosh-Sellavel I think react-native-linear-gradient will be easy to use here as it provides the handy props here, we can think of creating a separate component with `react-native-svg` but to me making it more customizable may take time. For eg. one point is in the mentioned example the component is created with 2 colors only, so to make it dynamic we need to iterate through and make these Stop elements.

**Comment by Santhosh-Sellavel** [comment] 2023-08-31 16:57
The positive is one less library,  react-native-linear-gradient has some weird [issue](https://github.com/Expensify/App/pull/23698#issuecomment-1670554048) color mismatch in iOS or mWeb iOS. As we have just started using this library if we could just replace it here then it would be great!

**Comment by Santhosh-Sellavel** [comment] 2023-08-31 17:03
> Both @Pujan92's https://github.com/Expensify/App/issues/24381#issuecomment-1696418777 & @pradeepmdk's https://github.com/Expensify/App/issues/24381#issuecomment-1696528517 are valid ones here!

@thienlnam Other than [this](https://github.com/Expensify/App/issues/24381#issuecomment-1701002353) we have valid proposals to get started here. I think we should go with @Pujan92 here as they submitted the first updated proposal after the mockup change and my last [pick](https://github.com/Expensify/App/issues/24381#issuecomment-1688722737) was @Pujan too before hold, Let me know your pick as both are valid thanks!

**Comment by thienlnam** [comment] 2023-08-31 19:33
I agree with your choice - thanks! As for the color mismatch, we can address separately - we also have this issue to handle it so it should be okay https://github.com/Expensify/App/issues/24447

**Comment by Santhosh-Sellavel** [comment] 2023-09-04 14:14
@Pujan92 Any update?

**Comment by Pujan92** [comment] 2023-09-04 14:49
@Santhosh-Sellavel Yes, I will raise a PR in an hour.

**Comment by Pujan92** [comment] 2023-09-04 16:26
@Santhosh-Sellavel [PR](https://github.com/Expensify/App/pull/26687) is ready for review!

**Comment by puneetlath** [comment] 2023-09-22 04:59
@Pujan92 has been paid. @Santhosh-Sellavel please open a NewDot request and let me know when you have so that I can close out this issue. 

Thanks everyone!

**Comment by Pujan92** [comment] 2023-09-22 13:44
@puneetlath just to make a point for the urgency bonus, @roryabraham approved the PR within 3 working days and later it was delayed due to merge freeze. I know @Santhosh-Sellavel approved it a bit late without any additional change, which might be due to unavailability. So don't know whether it falls in the urgency bonus criteria or not.

**Comment by puneetlath** [comment] 2023-09-25 09:38
@Santhosh-Sellavel bump on creating the NewDot request! 

@Pujan92 I think based on what we had previously announced, this would not qualify for the urgency bonus in that case.

**Comment by Santhosh-Sellavel** [comment] 2023-09-25 19:08
@puneetlath Can you add a payment summary here, so I can proceed with the request!

**Comment by Santhosh-Sellavel** [comment] 2023-09-25 20:02
@puneetlath  Requested $1000 On ND, please leave a summary when you get a chance thanks!

**Comment by puneetlath** [comment] 2023-09-26 01:50
Payment summary: 
- Contributor - @Pujan92 - $1000 - paid via Upwork
- C+ - @Santhosh-Sellavel - $1000 - to be paid via NewDot

Closing!

**Closed by puneetlath** 2023-09-26 01:50 UTC
Labels: External, Daily, NewFeature, Awaiting Payment

**Comment by shawnborton** [comment] 2023-09-27 01:05
I guess the avatar size is just using the standard 80x80 size we have elsewhere. I would have liked to have updated the global "big avatar" size everywhere, to something more like 100x100 to fill the space a bit better - not just here, but when viewing someone's profile, viewing room details, etc. 

I think we can just do a separate issue for that as a different project. cc @Expensify/design for visibility.

**Comment by JmillsExpensify** [comment] 2023-09-28 01:12
$1,000 payment approved for @Santhosh-Sellavel based on BZ summary.
