### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Web - Disable cursor is shown on completed task details

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27243] opened 2023-09-12 12:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a task report
2. Complete it if it is not
3. Hover on title, description, amount
4. Observe the disable cursor

## Expected Result:
It should not show the disabled cursor.

## Actual Result:
 It shows the disabled cursor.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/16c2d109-13dd-4d1f-ae36-48a3799621dd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694080698301029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01116fd25511df4aba</li>
        <li>Upwork Job ID: 1701566603636944896</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 26726635</li>
<li>Krishna2323 | Reporter | 26726636</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-12 12:01
Proposal by: @Krishna2323
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694080698301029

### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Disable cursor is shown on completed task details.
### What is the root cause of that problem?
We are passing the prop disable to PressableWithSecondaryInteraction, MenuItemWithTopDescription & MenuItem which shows the disabled cursor if the disabledState is true.
https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/components/ReportActionItem/TaskView.js#L55-L161
### What changes do you think we should make in order to solve the problem?
We need to make few changes to PressableWithSecondaryInteraction, MenuItemWithTopDescription & MenuItem to remove the disabled cursor and show it same as completed IOU report:
Remove disable prop from PressableWithSecondaryInteraction(Title) to remove the disable cursor style.
Add disableState && styles.cursorDefault  to style prop of PressableWithSecondaryInteraction for removing the pointer cursor if disabledState is true.
Add a if check to return from onPress event of PressableWithSecondaryInteraction if disabledState is true.
From MenuItemWithTopDescription & MenuItem remove disabled & shouldGreyOutWhenDisabled prop and add interactive={!disableState} prop.
We can also pass focusable={!disableState} to disable focus on task view elements if disabledState is true.

**Comment by mananjadhav** [comment] 2023-09-17 18:21
@DylanDylann's proposal [here](https://github.com/Expensify/App/issues/27243#issuecomment-1715591493) is good and a simple fix.

A note for future proposals. for the first point `Please re-state the problem`, avoid copying the title of the issue. You need to explain in your own words of what the problem is or why is it a problem.

🎀 👀 🎀 C+ reviewed.

**Comment by DylanDylann** [comment] 2023-09-18 03:16
@Krishna2323 My proposal gives an idea to resolve this problem, It's not completed code changed, It will be done in the PR stage. The pseudo-code is mentioned in my proposal to make it easily understandable. I don't agree that you use the same idea for your updated proposal with a bit change

**Comment by DylanDylann** [comment] 2023-09-18 03:42
>  it looks like you have used most of my solution with a few minor

My proposal was totally different from your first proposal. Let's see [this issue](https://github.com/Expensify/App/issues/27464), the selected proposal doesn't need to cover all code changes, It will be done in the PR stage.
We don't need redundant discussion, let's wait for @yuwenmemon to give his decision.

**Comment by DylanDylann** [comment] 2023-09-18 07:04
@mananjadhav The PR is ready for review

**Comment by DylanDylann** [comment] 2023-09-18 12:02
> the disabled cursor even if the task is canceled.

If it is correct, I think It is a new improvement, not related to this issue

**Comment by thienlnam** [comment] 2023-09-22 03:00
Yes that's correct - we should never be showing a disabled cursor. I'm not sure about the proposals issues but the assigned CME / C+ can sort that out

**Comment by DylanDylann** [comment] 2023-09-22 03:16
The new requirement is confirmed after the PR is merged. It is not mentioned in this issue at the beginning. So I think we should create a new issue for it

**Comment by mananjadhav** [comment] 2023-09-24 15:14
I don't think we need a new issue here. I think we should create another PR to fix this @DylanDylann . @yuwenmemon  wdyt?

**Comment by DylanDylann** [comment] 2023-09-24 16:58
@mananjadhav ok. The PR will be ready soon

**Comment by DylanDylann** [comment] 2023-09-26 03:13
> I don't think we need a new issue here. I think we should create another PR to fix this @DylanDylann . @yuwenmemon wdyt?

Please help check the latest main, the new design is applied so I think we do not need to create another PR 

![image](https://github.com/Expensify/App/assets/141406735/f6f14933-449c-4004-90c1-b01384f3737a)

**Comment by yuwenmemon** [comment] 2023-09-29 02:34
Unassigning as this is complete and I'm heading out on sabbatical.

**Comment by mananjadhav** [comment] 2023-10-02 15:32
@Krishna2323 Apologies I was OOO. I think the confusion arised because the GH issue didn't mention the correct behavior for all the scenarios. Based on that I will still stick to the proposal I shortlisted. Thanks for your patience here.


@CortneyOfstad I think this was added in the PR [here](https://github.com/Expensify/App/pull/22851) and I've posted the comment [here](https://github.com/Expensify/App/pull/22851#issuecomment-1743238726). I don't think we need a regression test here.

Can you please paste the payout summary here? So that I can raise the request.

**Comment by mananjadhav** [comment] 2023-10-04 20:00
@CortneyOfstad I've raised my request so I think we can close this one out.

**Closed** 2023-10-04 20:03 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 21:03
$750 payment approved for @mananjadhav based on BZ summary.
