### ISSUE TITLE
[HOLD for payment 2023-09-18] [$500] Dev: console error if we open RHN page directly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26561] opened 2023-09-02 16:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Try to open direct link of RHN(for eg, http://localhost:8082/settings)
2. Observe the console error
## Expected Result: 
Should not occur console error
Actual Result: 
Error `Failed prop type: The prop `isBlockedFromConcierge` is marked as required in `AttachmentPickerWithMenuItems`, but its value is `undefined`.` occurs
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** DEV
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9ff55e9e-0e2f-4662-a396-a6e5487bf0b2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692985306887049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c4503a94278a1ad</li>
        <li>Upwork Job ID: 1699435322866675712</li>
        <li>Last Price Increase: 2023-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26527992</li>
<li>Pujan92 | Contributor | 26527994</li>
<li>Pujan92 | Reporter | 26527998</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-09-02 16:45
## Proposal from @Pujan92 
### Please re-state the problem that we are trying to solve in this issue.
Console error for `isBlockedFromConcierge` passed undefined but it’s required prop
### What is the root cause of that problem?
In [PR](https://github.com/Expensify/App/pull/25758) we added prop `isBlockedFromConcierge` required in `AttachmentPickerWithMenuItems` & `ComposerWithSuggestions` components. But from `ReportActionCompose` it gets passed undefined when we directly open the RHN screen.
https://github.com/Expensify/App/blob/7217a18a78ec2b01a45267f476fd95ed0cde0fb0/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L158
Bcoz by the time the report gets loaded it has a default value `{reportID: ‘0’}`, so condition `ReportUtils.chatIncludesConcierge(report)` returns undefined, with that `undefined && false` returns undefined and issue persist.
### What changes do you think we should make in order to solve the problem?
We need to update the condition to make sure it will return a boolean value instead of undefined.
https://github.com/Expensify/App/blob/57603a08d0e018c5a428a5839ddb48a0b66115cd/src/libs/ReportUtils.js#L809-L811
```
!_.isEmpty(report.participantAccountIDs)
```
OR
We can use double negate or Boolean constructor to make `ReportUtils.chatIncludesConcierge` a boolean value.
https://github.com/Expensify/App/blob/7217a18a78ec2b01a45267f476fd95ed0cde0fb0/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L158

**Comment by situchan** [comment] 2023-09-06 10:02
Just doing an expedited review as this is annoying. When refresh app every time, hard to see other console errors caused by test branch as this one shows always.

@Pujan92's [proposal](https://github.com/Expensify/App/issues/26561#issuecomment-1703885699) looks good - `!_.isEmpty(report.participantAccountIDs)`

@sonialiap as this is dev-only issue, I am going to pull up engineer directly - 🎀 👀 🎀 C+ reviewed

**Comment by nkuoch** [comment] 2023-09-06 14:36
@Pujan92 's proposal looks good, but seems like I can't assign them to the issue, maybe because they didn't post the proposal to this issue by themselves?

**Comment by Pujan92** [comment] 2023-09-06 14:37
Commenting to get assigned.

**Comment by situchan** [comment] 2023-09-06 14:41
@nkuoch can you please do actions in this order?
- unassign @Pujan92 
- assign @situchan 
- add External label
- after a few seconds, assign @Pujan92

**Comment by situchan** [comment] 2023-09-07 16:42
@Pujan92 please let me know when PR is ready

**Comment by Pujan92** [comment] 2023-09-07 19:13
> @Pujan92 please let me know when PR is ready

@situchan [PR](https://github.com/Expensify/App/pull/26980) is ready for review!

**Comment by sonialiap** [comment] 2023-09-19 07:10
Payments - sent ✔️ 
@Pujan92 report + fix + bonus = $50 + $500 + $250 = $800
@situchan review + bonus = $500 + $250 = $750

**Comment by sonialiap** [comment] 2023-09-19 07:11
@situchan please fill out [the checklist ](https://github.com/Expensify/App/issues/26561#issuecomment-1714738003)so that we can close this issue :)

**Comment by situchan** [comment] 2023-09-19 07:15
This doesn't require BZ checklist.
Console error check is already in PR checklist and it's just dev error, not affecting production app.

**Comment by Pujan92** [comment] 2023-09-19 07:26
@sonialiap Can you plz check this slack thread https://expensify.slack.com/archives/C01GTK53T8Q/p1694444733848299 and confirm whether this should be eligible for old payment price or not as this issue gets reported on 25th aug before new pay price(31st aug) applied.

**Comment by sonialiap** [comment] 2023-09-22 05:53
@Pujan92 Thanks for bringing this up! I went by the date the gh issue was opened and didn't check the reporting date. 

The reporting date was Aug 26 so you are eligible for the old reporting bonus of $250. I have already issued a payment of $50 so you're owed $200. I just sent an offer for $200. 

<img width="1001" alt="image" src="https://github.com/Expensify/App/assets/17131195/099c86ea-c7cb-44bc-a897-1804921fa049">

**Comment by Pujan92** [comment] 2023-09-22 06:11
Thanks @sonialiap for reconsidering but I believe contributor price also needs to be updated by considering it($1000+$500 for urgency bonus)

**Comment by sonialiap** [comment] 2023-09-26 06:20
@Pujan92 The GH issue was created and became available after the pricing change so the fix and review are both $500

**Comment by Pujan92** [comment] 2023-09-26 09:43
Oh, ok @sonialiap. I thought all payments needs to be with old price. Thanks for clearing.

**Comment by sonialiap** [comment] 2023-10-02 04:43
I believe all payments have been processed, please reopen if I missed anything in the discussion

**Closed by sonialiap** 2023-10-02 04:43 UTC
Labels: External, Daily, Needs Reproduction, Overdue, Awaiting Payment, Bug

**Comment by Pujan92** [comment] 2023-10-03 16:58
> I believe all payments have been processed, please reopen if I missed anything in the discussion

@sonialiap payment is pending [here](https://www.upwork.com/nx/wm/offer/26810739), could you plz check.

**Comment by Pujan92** [comment] 2023-10-05 13:49
Bump @sonialiap

**Comment by Pujan92** [comment] 2023-10-13 13:14
Bump @sonialiap for remaining payment

**Comment by sonialiap** [comment] 2023-10-31 09:36
@Pujan92 my apologies! Payment completed!

**Comment by Pujan92** [comment] 2023-10-31 11:46
No issues, Thanks!
