### ISSUE TITLE
[HOLD for payment 2024-06-13] [$500] Login with edit description does not open edit description page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29115] opened 2023-10-09 18:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.79-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696834330715939

## Action Performed:
1. Open the app
2. Open request money report or raise one and open it
3. Click on description and copy the URL
4. Logout and paste the URL
5. Login and observe that app does not open description edit on after login
## Expected Result:
After we login, app should open URL which we use before login
## Actual Result:
After we login, app does not open edit description URL that we used before login
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/aed8bdda-894a-4f8c-9064-2405edc429af

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/66f0d2d3-8113-40cb-8d79-485db7fa25d9

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/4f4c0cda-1c30-4f4a-a214-90f647cdecfb

https://github.com/Expensify/App/assets/38435837/5c79eaac-ffd5-407b-8497-9a0fc67076d2

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017838f4eb8f52a1be</li>
        <li>Upwork Job ID: 1711448302691934208</li>
        <li>Last Price Increase: 2023-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27743863</li>
<li>dukenv0307 | Contributor | 27743865</li>
<li>dhanashree-sawant | Reporter | 27743868</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by abdulrahuman5196** [comment] 2023-10-09 18:32
@m-natarajan can you add `Bug` label so that a BZ is assigned here?

**Comment by abzokhattab** [comment] 2023-10-09 18:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Logging with the edit description/merchant page does open these pages 
### What is the root cause of that problem?
in this use effect we check if the `canEdit` value is false then dismiss the modal, in our case initially the report and the parent report are empty so the canEdit value resolves to false, which closes the modal 
https://github.com/Expensify/App/blob/main/src/pages/EditRequestPage.js#L133-L140

### What changes do you think we should make in order to solve the problem?
to check also if the report and the parent-report in the useeffect

```js
    useEffect(() => {
        if (canEdit || _.isEmpty(parentReport)) {
            return;
        }
        Navigation.isNavigationReady().then(() => {
            Navigation.dismissModal();
        });
    }, [canEdit]);
```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by abzokhattab** [comment] 2023-10-09 19:02
POC was added [here](https://github.com/Expensify/App/issues/29115#issuecomment-1753482255)

**Comment by b4s36t4** [comment] 2023-10-09 22:06
#28645 this PR got merged today which does have some issues which is a blocker for re-producing this issue. We can put this on-hold for till that completed.

**Comment by abdulrahuman5196** [comment] 2023-10-13 07:42
@abzokhattab @saranshbalyan-1234 @b4s36t4 @dukenv0307 
I think all the above solutions are only partial fixes for the issue. If we do any of the above, it will open the description page but could have issues if data isn't loaded (@dukenv0307's proposal mentioned to show after loading data but still incomplete IMO)

We should fix this how TasK description works. Like it shows loading indicator until data is loaded then proceeds with showing the screen.


https://github.com/Expensify/App/assets/46707890/267e7b86-5450-4c3b-b115-71e990cb8f46

**Comment by b4s36t4** [comment] 2023-10-13 08:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Login with edit description does not open edit description page
### What is the root cause of that problem?

There's no report data available after login, causing the modal's rendering condition to be falsy which makes modal to close automatically.

### What changes do you think we should make in order to solve the problem?

> As per @abdulrahuman5196 suggestion following the same methodologies would prevent such issues further.

We have a wrapper called `withReportOrNotFound` that handles the loading/notfound logic for report which does the work. which we cannot use because of the way we written the code.

Possible solutions:

1. We access report using the following prop https://github.com/Expensify/App/blob/a2f483d91982f10cf7e2cc1098221e7dbd29ea78/src/pages/EditRequestPage.js#L310. We can update the `withReportOrNotFound` component to support custom parameter (reportId) instead of just relying on `props.report.reportID` https://github.com/Expensify/App/blob/0cbee2247e48c17eec428b989afead3dc6f196d4/src/pages/home/report/withReportOrNotFound.js#L53

2. We can create a new HOC maybe called `withTransactionOrNotFound` that works same as `withReportOrNotFound` but with somemore detailing about the report or transaction.



### What alternative solutions did you explore? (Optional)
NA

**Comment by abzokhattab** [comment] 2023-10-13 08:47
Proposal is [updated](https://github.com/Expensify/App/issues/29115#issuecomment-1753482255) @abdulrahuman5196 .. now the loading indactor is shown while the page is loading , please check the POC

**Comment by abdulrahuman5196** [comment] 2023-10-16 14:25
@b4s36t4 I tried your 3 rd option 

>We can make the param threadReportID as reportID just like we do with other reports 

It shows loading and proper open. But it doesn't show the existing description always shows up empty?

I assume it should be the case for other options as well. We should fix that as well IMO .

**Comment by b4s36t4** [comment] 2023-10-16 14:28
Yes, there are some other changes might require to complete things correctly. Would you want me to update my proposal to cover all things using the third Option?

**Comment by abdulrahuman5196** [comment] 2023-10-19 17:08
@b4s36t4 
>Yes, there are some other changes might require to complete things correctly. Would you want me to update my proposal to cover all things using the third Option?

Yes.

**Comment by abdulrahuman5196** [comment] 2023-10-19 17:10
@dukenv0307 

If you already set up a description, it doesn't show up in the edit description page after login. Even after applying the fixes, it would fix that as well

**Comment by abdulrahuman5196** [comment] 2023-10-23 11:51
Waiting for contributors to update proposals on this.

**Comment by b4s36t4** [comment] 2023-10-23 15:21
@abdulrahuman5196 Updated my proposal https://github.com/Expensify/App/issues/29115#issuecomment-1761091225

**Comment by abdulrahuman5196** [comment] 2023-10-26 16:18
REviewing now

**Comment by abdulrahuman5196** [comment] 2023-10-30 12:54
We complete the updated review today.

**Comment by abdulrahuman5196** [comment] 2023-11-01 11:38
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-11-06 14:09
I will take care of this today. Seems we have updated proposals as well.

**Comment by abdulrahuman5196** [comment] 2023-11-13 06:27
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-11-13 06:31
Pending proposals to review:
https://github.com/Expensify/App/issues/29115#issuecomment-1761091225
https://github.com/Expensify/App/issues/29115#issuecomment-1754801666

**Comment by abdulrahuman5196** [comment] 2023-11-13 08:20
@dukenv0307 's proposal here https://github.com/Expensify/App/issues/29115#issuecomment-1754801666 looks good and works well. Other proposal is also similar, so choosing the first proposal which suggested to use indicator.

🎀 👀 🎀
C+ Reviewed

**Comment by b4s36t4** [comment] 2023-11-13 08:43
@abdulrahuman5196 I request you to check edit history of the proposal. Since you mentioned proposals are similar, this is a humble request from my side. As you requested I gave you the first proposal with loading, but due the simple issues I took some time to update the proposal (which I did first).

**Comment by abdulrahuman5196** [comment] 2023-11-17 11:57
> @abdulrahuman5196 is right that the first proposal that suggested to use data loading state is mine, since Oct 10. @abdulrahuman5196 can double check that if necessary, thanks!

Agree on this. Solving the loading problem was the core problem of this issue and it first came from @dukenv0307

**Comment by abdulrahuman5196** [comment] 2023-11-17 11:58
@robertjchen Gentle ping on review https://github.com/Expensify/App/issues/29115#issuecomment-1807655874

**Comment by robertjchen** [comment] 2023-11-20 02:09
Thanks for the discussion here, I would agree that @dukenv0307 is the first one to suggest the proper approach. Let's move forward!

**Comment by b4s36t4** [comment] 2023-11-20 11:30
@robertjchen But he just gave the proposal to show the editor view only, but it doesn't contain the fix/root cause to show loader while transaction is loading. I was the first to find the both root causes (loader for report & loading state for transaction). I request you to re-consider.

cc: @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2023-11-20 18:08
Hi @b4s36t4, Thank you for raising the concern.
But @dukenv0307 proposed with solution to the have the description page in loading state on Oct 10 https://github.com/Expensify/App/issues/29115#issuecomment-1754801666. The fix to have the transaction loading is a fix on top of the core fix of making the edit description with loading state IMO. So I took the timeline of the core issue fix and suggested the proposal which was the first.

**Comment by abdulrahuman5196** [comment] 2023-12-14 12:51
Its in PR state. Seems we hit a blocker. Will check and update on that soon.

**Comment by kevinksullivan** [comment] 2024-06-17 18:32
@abdulrahuman5196 @dukenv0307 can you please finish the steps above?

**Comment by kevinksullivan** [comment] 2024-06-17 20:11
Created a new job since the previous one expired, and sent offers to @dukenv0307 and @abdulrahuman5196 

https://www.upwork.com/jobs/~017a3e1b0beac19165

**Comment by kevinksullivan** [comment] 2024-06-17 20:13
hey @slafortune ! I am assigning another BZ member here to wrap this up as I am OOO the rest of the week. Waiting on:
1. The checklist to be complete
2. @dukenv0307 and @abdulrahuman5196 to accept the [upwork job](https://www.upwork.com/jobs/~017a3e1b0beac19165), and then we can pay it

Thanks!

**Comment by kevinksullivan** [comment] 2024-06-26 15:52
@abdulrahuman5196 @dukenv0307 can you complete the checklist please?

**Comment by kevinksullivan** [comment] 2024-06-26 15:54
Payments made, just waiting on the checklist.

**Comment by dhanashree-sawant** [comment] 2024-06-27 03:12
Hi @kevinksullivan, am I eligible for reporting bonus?

**Comment by kevinksullivan** [comment] 2024-07-03 14:25
Bump @abdulrahuman5196

**Comment by kevinksullivan** [comment] 2024-07-03 14:30
@dhanashree-sawant since this was prior to [this announcement](https://expensify.slack.com/archives/C01GTK53T8Q/p1698191269281379) I will pay out reporting bonus. Please let me know when you accept this job

https://www.upwork.com/jobs/~0190db0218ebfa737d

**Comment by dhanashree-sawant** [comment] 2024-07-03 14:32
Thanks @kevinksullivan, I have accepted the offer.

**Comment by kevinksullivan** [comment] 2024-07-03 14:34
Paid @dhanashree-sawant

**Comment by robertjchen** [comment] 2024-07-07 08:04
Looks like we're just waiting on the checklist here?

**Comment by abdulrahuman5196** [comment] 2024-07-08 20:31
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be a regression

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Open a request money report or raise one and open it
2) Click on the description or merchant and copy the URL
3) Logout and paste the URL
4) Login and observe that the app opens the correct description or merchant modal

@kevinksullivan

**Comment by robertjchen** [comment] 2024-08-01 21:55
I think we can close this one out?

**Closed by robertjchen** 2024-08-01 21:55 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Not a priority, Bug
