### ISSUE TITLE
[HOLD for payment 2023-10-16] [$250] Regression: prop 'value' of type 'string' supplied to 'CheckboxWithLabel', expected 'boolean`

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#23909] opened 2023-07-31 07:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

In this PR a change was added to fix several regressions, however it created a new regression with checkboxes in forms:

https://github.com/Expensify/App/pull/22589

## Expected Result:

There should be no console error

## Actual Result:

A console error is showing when interacting with a checkbox wrapped in a Form:

<img width="1440" alt="256987402-a85e0060-abf7-44f2-8066-7fd1062f232b" src="https://github.com/Expensify/App/assets/16821682/f8fd8046-4804-4bb3-acf6-c5464b7a6d2b">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

It's an error only devs will see + it doesn't have any impact on the functionality of the app.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:1.3.47-5**
**Reproducible in staging?:no (not deployed yet)**
**Reproducible in production?:no**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** See in **Actual result**
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690578654439359?thread_ts=1690578654.439359&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140a93db1203e631c</li>
        <li>Upwork Job ID: 1709884954347847680</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by hannojg** [comment] 2023-07-31 07:27
PR for fixing it is up:

- https://github.com/Expensify/App/pull/23910

**Comment by sobitneupane** [comment] 2023-08-02 11:31
Thanks @Pujan92 and @dhairyasenjaliya.

**Comment by mountiny** [comment] 2023-10-05 10:56
Updating the price as this is quite minor

**Comment by mountiny** [comment] 2023-10-05 12:11
$250 to @sobitneupane for review and testing

**Comment by mountiny** [comment] 2023-10-05 12:42
$50 to @dhairyasenjaliya for reporting, $50 because this is just a console log warning

**Comment by trjExpensify** [comment] 2023-10-05 13:20
Can someone clarify where the PR is and/or is this ready to be paid?

**Comment by mountiny** [comment] 2023-10-05 17:26
This PR https://github.com/Expensify/App/pull/23910

Not ready to be paid, just merged it

**Comment by trjExpensify** [comment] 2023-10-06 00:15
Thanks!

**Comment by trjExpensify** [comment] 2023-10-17 23:39
👋 @sobitneupane checklist time, thanks!

**Comment by trjExpensify** [comment] 2023-10-23 13:12
Same, awaiting checklist.

**Comment by sobitneupane** [comment] 2023-10-27 12:25
@trjExpensify Sorry for the delay. I was OOO. I will try to get it done in the weekend.

**Comment by trjExpensify** [comment] 2023-10-30 10:28
Thanks, @sobitneupane. Did you get to it? 

In the meantime, confirming payments we'll issue as follows: 

- @dhairyasenjaliya $50 for the bug report
- @sobitneupane $250 for the C+ review

**Comment by sobitneupane** [comment] 2023-10-30 11:16
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/22589
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

Not Required.
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It should have been caught in PR review.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

The issue is reproducible only in Dev. So, regression test is not required.

**Comment by trjExpensify** [comment] 2023-10-30 11:59
Thanks, @sobitneupane! 

>It should have been caught in PR review.

If that's the case, is there something in the reviewer checklist that could be improved such that it is caught?

**Comment by sobitneupane** [comment] 2023-10-30 13:20
The change was made in Form component which affects all the components using `Form`. And we already have a point in reviewer checklist to verify it.

> If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App

**Comment by sobitneupane** [comment] 2023-10-30 14:04
https://github.com/Expensify/App/issues/23909#issuecomment-1784896294

Requested payment on newDot.

**Comment by trjExpensify** [comment] 2023-10-30 15:33
@dhairyasenjaliya an offer has been sent to you.

**Comment by trjExpensify** [comment] 2023-10-30 15:38
Cool, paid. Closing!

**Closed by trjExpensify** 2023-10-30 15:38 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-03 22:24
$250 payment approved for @sobitneupane based on [this comment](https://github.com/Expensify/App/issues/23909#issuecomment-1784896294).
