### ISSUE TITLE
[WAITING ON SLACK] [$1000] ANDROID CHROME - Missing focus when going from LHN to the conversation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23382] opened 2023-07-21 21:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to http://staging.new.expensify.com/
2. Tap on any conversation from LHN
Another scenario
1. Go to http://staging.new.expensify.com/
2. Tap on any conversation from LHN
3. Type a letter in compose box
4. Navigate to LHN
5. Return to compose box

## Expected Result:
While navigating from LHN to chat page, focus on compose box, with cursor and keypad must be shown

## Actual Result:
While navigating from LHN to chat page, no focus on compose box, no cursor and no keypad displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a742d4dd-7b16-43bb-842f-789b03e4232d

https://github.com/Expensify/App/assets/78819774/9988e9cd-4163-4008-8bcf-70bab319cd32

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01256fc687c8baf62f</li>
        <li>Upwork Job ID: 1682564295686647808</li>
        <li>Last Price Increase: 2023-07-29</li>
    </ul>
</details>

**Comment by makiour** [comment] 2023-07-22 00:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When clicking on a chat in the sidebar, the focus is not anymore shown. 

### What is the root cause of that problem?

This is actually the normal behavior of ReactDOM. The focus event listener is triggered automatically when clicking anywhere in the 'document'. This causes the focus to clear itself from the composer and tries to focus where we have the mouse clicked event. 
Basically, the issue is that we are not handling manually to keep the focus when clicking on the sidebar. 

The lines of code that trigger the click event on the OptionRowLHN or Chat is in the SidebarLinks file where we navigate to the report and open it when we click:
https://github.com/Expensify/App/blob/f235a45e3043a09c89869477691b0a85bbb05aed/src/pages/home/sidebar/SidebarLinks.js#L148-L157

Dealing with the composer in independent of openingReport request and Report rendering component. We can't pass something to let the composer present here that it needs to be focused. 
https://github.com/Expensify/App/blob/f235a45e3043a09c89869477691b0a85bbb05aed/src/pages/home/report/ReportActionCompose.js#L1138-L1162

Thus, the solution here is that we can work it out through the ReportActionComposeFocusManager that keeps track of the focusCallback. When navigating to the selected report, we can add the focus listener to the compose which will keep it on!



### What changes do you think we should make in order to solve the problem?
In this part of the SidebarLinks:
https://github.com/Expensify/App/blob/f235a45e3043a09c89869477691b0a85bbb05aed/src/pages/home/sidebar/SidebarLinks.js#L148-L157

We need to add:
`ReportActionComposeFocusManager.focus();` which will trigger the composer to focus each time we click on the OptionRowLHN

I hope I made it as clear as possible for you!

# Result
[bugFocus.webm](https://github.com/Expensify/App/assets/60530038/14aca581-41cb-420b-b58a-f2980f1d23f5)


### What alternative solutions did you explore? (Optional)
N/A

**Comment by jliexpensify** [comment] 2023-07-22 01:31
Yep, I can replicate it on 1.3.44.0 (Android Chrome, Pixel 3a). The behaviour on Mac OS is that the cursor re-appears when you navigate back into the same compose field in the same chat.

**Comment by Nathan-Mulugeta** [comment] 2023-07-22 07:05
Hey guys I think I have reported this issue long ago [here](https://expensify.slack.com/archives/C049HHMV9SM/p1681887877764439?thread_ts=1681887877.764439&cid=C049HHMV9SM)

**Comment by jliexpensify** [comment] 2023-07-23 22:20
@Nathan-Mulugeta - thanks for letting me know! @situchan - let me bring this one up internally. I reviewed Nathan's [bug report](https://expensify.slack.com/archives/C049HHMV9SM/p1681887877764439) and Matt closed it as not being a bug, but my understanding is our behaviours should be the same across all platforms.

I think this is a bug since we can see the behaviour on Mac OS, but I'll circle back with a final response.

**Comment by jliexpensify** [comment] 2023-07-23 23:36
Asked here - https://expensify.slack.com/archives/C01SKUP7QR0/p1690155370218789

**Comment by jliexpensify** [comment] 2023-07-26 23:37
Still awaiting consensus

**Comment by jliexpensify** [comment] 2023-07-31 00:28
Sorry, not overdue - we're discussing auto-focusing in Slack. Catching up on the threads today.

**Comment by jliexpensify** [comment] 2023-07-31 01:03
@situchan just curious: does Android support auto-focusing in this particular instance (i.e. the chat composer)?

**Comment by situchan** [comment] 2023-07-31 02:06
> @situchan just curious: does Android support auto-focusing in this particular instance (i.e. the chat composer)?

yes, it should be auto-focused when open new (no chat history yet) report

**Comment by jliexpensify** [comment] 2023-07-31 02:12
@situchan as an FYI, I've posted publicly here - https://expensify.slack.com/archives/C01GTK53T8Q/p1690436065927919

It looks like we never really defined the rules around auto-focus so I was trying to get consensus around it. Feel free to review!

**Comment by jliexpensify** [comment] 2023-08-01 22:34
@Nathan-Mulugeta @situchan - sorry for the delay: we're going to close this one as both iOS and Android don't intentionally auto-focus on the chat composer, and we want to keep it this way.

**Closed by jliexpensify** 2023-08-01 22:34 UTC
Labels: External, Daily, Help Wanted, Bug
