### ISSUE TITLE
Chat - Group chat - Large spacing between last message and compose box

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9282] opened 2022-06-01 21:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in any account
2. Open group chat
3. Click in compos box

## Expected Result:
Distance between the last message and compose box should be uniform

## Actual Result:
Large distance between the last message and compos box.

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**  1.1.70-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** applausetester+0604lsn@applause.expensifail.com / w323052760We
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5593550_Web_31 05](https://user-images.githubusercontent.com/43996225/171505226-413d915b-b3fe-4a75-b5bf-3141066c080e.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2022-06-02 02:00
This first needs to go through AutoAssigner triage before going to an engineer. I'll take the triage since I'm on that team and working on this.

**Comment by Christinadobrzyn** [comment] 2022-06-02 03:42
- I'm not able to reproduce this issue
- and I think it might be associated with this [job](https://github.com/Expensify/App/issues/8731). 

So going to ask Eng for a buddy check Eng. I don't think this needs to be posted as a job until this is [fixed](https://github.com/Expensify/App/issues/8731) to see if it's resolved.

**Comment by mountiny** [comment] 2022-06-02 11:11
This is a dupe of https://github.com/Expensify/App/issues/9251 and the solution for it should revolve this problem as well so I am closing this.

**Closed by mountiny** 2022-06-02 11:11 UTC
Labels: External, Engineering, Daily, Improvement
