### ISSUE TITLE
[$1000] User avatar and name not displayed under assign to me

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21338] opened 2023-06-22 18:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From account A, send a money request to account B
2. From account B, open the request and click on the IOU
3. Click on + in the composer.
4. Click on assign task
5. Enter any title
6. Click on Assignee

## Expected Result:
Under assign to me, there should be the user avatar instead of the IOU avatar and the user name should be there.

## Actual Result:
Actual result, it has the current IOU avatar and the IOU report name.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**

**Reproducible in staging?:**

**Reproducible in production?:**

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/50e847b7-9b69-43dd-b179-f6c7acc7698a

https://github.com/Expensify/App/assets/93399543/e36c9498-2239-4871-807e-1bd99189d992

**Expensify/Expensify Issue URL:**

**Issue reported by:** @esh-g

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686903102584029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01750f9f952f7f10ef</li>
        <li>Upwork Job ID: 1673485733203546112</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-06-22 21:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User avatar and name not displayed under assign to me in some cases

### What is the root cause of that problem?

Assignee page gets the available assignee options with `OptionsListUtils.getNewChatOptions`. This function retrieves all reports and personal lists and get relevant information(i.e. report title as main text).
https://github.com/Expensify/App/blob/2669f79733f57aba08ff8b7b086720d37eb54072/src/libs/OptionsListUtils.js#L681-L686

This is incorrect for the current user option. Current user option should have its own display name and email as its text and alternativeText. This is the main reason

### What changes do you think we should make in order to solve the problem?

Now we get current user option here
https://github.com/Expensify/App/blob/2669f79733f57aba08ff8b7b086720d37eb54072/src/libs/OptionsListUtils.js#L753

We can get the `currentUserOption` without report as follows.
```
    let currentUserOption = createOption([currentUserAccountID], personalDetails, null, {}, {});
```

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/45fc593a-5493-403f-bcb6-1ce123de3b79


</details>

### What alternative solutions did you explore? (Optional)

**Comment by slafortune** [comment] 2023-06-27 00:17
looks good

**Comment by eVoloshchak** [comment] 2023-06-29 19:07
I can't reproduce

https://github.com/Expensify/App/assets/9059945/4c3e4b83-5d6a-4bb0-95d9-8cc8d73141b6

@slafortune, could you check if this is still reproducible please?

**Comment by eVoloshchak** [comment] 2023-07-04 15:58
@esh-g, @s-alves10, can you still reproduce this issue?

**Comment by esh-g** [comment] 2023-07-04 19:58
@eVoloshchak This doesn't seem to be reproducible anymore..

**Closed** 2023-07-10 13:10 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
