### ISSUE TITLE
[Hold, Testing][$500] Theme - Theme is always reset to "Use Device Settings" after relogin

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33160] opened 2023-12-15 13:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Precondition: App theme is set to Light mode.

1. Launch New Expensify app.
2. Log out.
3. Log in to the same account.
4. Go to Settings > Preferences > Theme.

## Expected Result:
The theme preference before logout is preserved.

## Actual Result:
The theme is reset to "Use Device Settings" after relogin.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0c1dc7d0-23a6-4f1b-b44e-52e4de131924

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0146344d6185cdc37b</li>
        <li>Upwork Job ID: 1735649568056549376</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2023-12-15 13:34
# Proposal

## Please re-state the problem that we are trying to solve in this issue

The theme is reset to "Use Device Settings" after relogin.

## What is the root cause of that problem?

We are not setting `ONYXKEYS.PREFERRED_THEME` to the value of the theme when we call `updateTheme` endpoint, we only pass `optimisticData`.

## What changes do you think we should make in order to solve the problem?

We should pass `successData` to `updateTheme` where we set the `ONYXKEYS.PREFERRED_THEME` to the value of the theme.

**Comment by ikevin127** [comment] 2023-12-15 14:36
# Proposal

## Please re-state the problem that we are trying to solve in this issue

The theme is reset to "Use Device Settings" after relogin.

## What is the root cause of that problem?

The theme onyx data is cleared when logout is performed.

## What changes do you think we should make in order to solve the problem?

We should pass `successData` to `LogOut` where we set the `ONYXKEYS.PREFERRED_THEME` to the value of the theme.

### Changed code:

```diff
...src/libs/actions/Session/index.ts

+    let preferredTheme: ValueOf<typeof CONST.THEME> | null = null;
+    Onyx.connect({
+        key: ONYXKEYS.PREFERRED_THEME,
+        callback: (val) => (preferredTheme = val),
+    });

/**
 * Clears the Onyx store and redirects user to the sign in page
 */
function signOut() {
    ...
+    const successData = [
+        {
+            onyxMethod: Onyx.METHOD.SET,
+            key: ONYXKEYS.PREFERRED_THEME,
+            value: preferredTheme,
+        },
+    ];

+    API.write('LogOut', params, {successData});
    ...

```

## Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/56457735/902fb6c0-da57-40f2-8aa7-6311b6ae3f0f

<details>

**Comment by shubham1206agra** [comment] 2023-12-15 14:36
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Theme - Theme is always reset to "Use Device Settings" after relogin

### What is the root cause of that problem?

We are not preserving `ONYXKEYS.PREFERRED_THEME` on logout.

### What changes do you think we should make in order to solve the problem?

We should preserve the `ONYXKEYS.PREFERRED_THEME` key in `clearStorageAndRedirect` function.

**Comment by Julesssss** [comment] 2023-12-15 15:18
This shouldn't block deploy, removing the label

**Comment by danieldoglas** [comment] 2023-12-18 14:26
@situchan please review the proposals

**Comment by danieldoglas** [comment] 2023-12-18 14:27
Also, I think it makes sense to assign @grgia to this issue since she's the person with the most knowledge on our side

**Comment by grgia** [comment] 2023-12-20 21:30
I am fixing this internally in https://github.com/Expensify/Web-Expensify/pull/40078

**Comment by grgia** [comment] 2023-12-20 21:31
Although @situchan maybe we should go with one of these proposals on App side. Do you have thoughts on this?

**Comment by grgia** [comment] 2024-01-03 17:38
Otherwise I believe this will be fixed by https://github.com/Expensify/Web-Expensify/pull/40078 (internal)

**Comment by grgia** [comment] 2024-01-05 18:49
We've merged internal auth PR, will retest after changes are deployed

**Closed** 2024-01-11 01:24 UTC
Labels: External, Engineering, Weekly, Internal, Help Wanted, Bug
