### ISSUE TITLE
[Awaiting Contributor Response for Payment - Payment 27th June] [$250] Incorrect video is paused after turning on and off full screen mode

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42427] opened 2024-05-21 15:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @blimpich / @KMichel1030
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716239323512349

## Action Performed:
1. Upload two videos (Video1, Video2)
2. Play Video1
3. Play Video2
4. Click full screen mode button of Video1 while Video2 is playing
5. Exit full screen mode by pressing Esc key
6. Click play button of Video1

## Expected Result:
Video1 should be played

## Actual Result:
Video2 is played

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/5e217ce9-e450-4d19-86d7-7604f0abb5dd

https://github.com/Expensify/App/assets/38435837/fb5ae120-7a38-4117-8bb2-853a19eb7404

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153a7421c659e1e1b</li>
        <li>Upwork Job ID: 1793023328329351168</li>
        <li>Last Price Increase: 2024-05-28</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 102587027</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment] 2024-05-21 20:57
@KMichel1030 are you interesting in proposing a solution for this?

**Comment by jacobnguyen0000** [comment] 2024-05-21 21:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect video is paused after turning on and off full screen mode

### What is the root cause of that problem?
When entering full screen mode, `currentlyPlayingURL` is updated, but `currentVideoPlayerRef` is not updated because we have `isFullScreenRef` check [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/VideoPlayer/BaseVideoPlayer.tsx#L245).
Since we use `currentVideoPlayerRef` when play and pause video, incorrect video is paused.

### What changes do you think we should make in order to solve the problem?
We should remove `isFullScreenRef` check [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/VideoPlayer/BaseVideoPlayer.tsx#L245).
We also need to modify last parameter of  [this line](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/VideoPlayer/BaseVideoPlayer.tsx#L248) to prevent auto play when entering full screen mode.

### What alternative solutions did you explore? (Optional)

**Comment by jacobnguyen0000** [comment] 2024-05-24 06:37
@hoangzinh 
Thank you for your review.

> @jacobnguyen0000 Thanks for proposal https://github.com/Expensify/App/issues/42427#issuecomment-2123474008. I don't think we can remove isFullScreenRef.current from [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/VideoPlayer/BaseVideoPlayer.tsx#L245). Thanks to @tienifr, he already confirmed reason with author of that line https://github.com/Expensify/App/pull/38407#discussion_r1609386669

I've tested on my end but it seems removing `isFullScreenRef.current` doesn't any problem.

**Comment by mstindia-com** [comment] 2024-05-24 08:50
## Proposal
[Updated](https://github.com/Expensify/App/issues/42427#issuecomment-2124941131)

**Comment by mstindia-com** [comment] 2024-05-24 08:52
@hoangzinh Thanks for your reply. I managed to find a solution. updated my proposal.

**Comment by jacobnguyen0000** [comment] 2024-05-28 00:15
@hoangzinh 

> @jacobnguyen0000 solution could lead to the unknown bug here https://github.com/Expensify/App/issues/42427#issuecomment-2128356588

Thank you for your check.

> isFullScreenRef is responsible for locking the video player when screen orientation changes in full-screen mode. It prevents video players from changing their state because of device rotation or window size changes. Changing state causes the full screen to dismiss. We need it here to block updating currently shared video element

I've tested above cases and confirmed it's working properly with my proposal.

**Comment by mstindia-com** [comment] 2024-05-28 10:39
## Proposal
[Updated](https://github.com/Expensify/App/issues/42427#issuecomment-2124941131)

**Comment by jacobnguyen0000** [comment] 2024-05-28 12:08
Hi, @hoangzinh 
I've tested on my end and discussed with author.
Could you please check if it's working for you. Thanks.

**Comment by jacobnguyen0000** [comment] 2024-06-03 16:00
Hi, @grgia 
Could you please assign me so that I can raise PR?

**Comment by grgia** [comment] 2024-06-04 09:14
@jacobnguyen0000 all yours!

**Comment by jacobnguyen0000** [comment] 2024-06-04 09:37
Hi, @hoangzinh 
I've created PR.

**Comment by trjExpensify** [comment] 2024-06-27 22:38
Hm, not sure what happened there. The automation didn't run. Payments are due here! 

Payment summary as follows:

- $250 to @hoangzinh for the C+ review (paid!)
- $250 to @jacobnguyen0000 for the fix. 

@jacobnguyen0000 I'll need your Upwork profile link to send you an offer. Thanks!

**Comment by trjExpensify** [comment] 2024-07-01 09:46
Bump @jacobnguyen0000 on providing your Upwork profile for payment.

**Comment by grgia** [comment] 2024-07-01 13:13
awaiting payment details, not overdue

**Comment by trjExpensify** [comment] 2024-07-01 17:15
Melvin, stop it.

**Comment by trjExpensify** [comment] 2024-07-04 17:44
@jacobnguyen0000 bump here!

**Comment by trjExpensify** [comment] 2024-07-08 18:55
Cool, dropped to weekly. I'll likely just close this after a couple of weeks, and @jacobnguyen0000 can let me know when he's back if he wants to get paid.

**Comment by trjExpensify** [comment] 2024-07-19 01:09
Closing.

**Comment by jacobnguyen0000** [comment] 2024-08-06 00:52
Hi, @trjExpensify 
Sorry for late response. Can I get payment now?

Contributor details
Your Expensify account email: jacobnguyen0000@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014cac515a92876fc5

**Comment by jacobnguyen0000** [comment] 2024-08-07 00:12
@mallenexpensify 
It seems @trjExpensify is not here.
Could you please complete payment here?

**Comment by trjExpensify** [comment] 2024-08-07 16:31
Sent an offer.

**Comment by jacobnguyen0000** [comment] 2024-08-07 17:58
Thank you, @trjExpensify.
I've accepted offer.

**Comment by trjExpensify** [comment] 2024-08-07 19:04
Paid!

**Closed by trjExpensify** 2024-08-07 19:04 UTC
Labels: External, Weekly, Awaiting Payment, Bug
