### ISSUE TITLE
[HOLD for payment 2023-11-06][$500] Web - Split bill - Enter key in Edit amount page directly creates split bill

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29051] opened 2023-10-07 09:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to any group chat.
3. Go to + > Split amount > Enter amount > Next.
4. Click on the amount.
5. Enter new amount.
6. Hit Enter on keyboard.
Note that the new amount is not saved and the split bill with the old amount is created instantly.

## Expected Result:
The new amount is saved and user lands in confirmation page.

## Actual Result:
The new amount is not saved and Enter key triggers the creation of split bill with the previous amount.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.79-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/b5d35db4-cf5c-47ce-8190-87fc10ea83e3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4cfb0b4e5279620</li>
        <li>Upwork Job ID: 1710595541472288768</li>
        <li>Last Price Increase: 2023-10-07</li>
    </ul>
</details>

**Comment by zzarcon** [comment] 2023-10-07 10:32
I'm trying to reproduce the issue but I can't, it seems like when I get to the split bill action we have an exception in where we try to parse the participant login but is undefined


https://github.com/Expensify/App/assets/1194982/d77c86f6-ceed-46d4-beda-f6d2e6d1ccbe

I believe we need to first fix this issue?

**Comment by paultsimura** [comment] 2023-10-07 10:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When editing the request amount on the request confirmation page, hitting "Enter" submits the request instead of just updating the amount.

### What is the root cause of that problem?
The reason for this is that when we are editing the amount, we have 2 buttons with `pressOnEnter`, and their effect is bubbling, meaning both buttons are pressed on hitting "Enter"

### What changes do you think we should make in order to solve the problem?
We need to disable the "Confirm Request" button when we are in the editing mode:

```diff
+        const isEditingRequest = lodashGet(props.route, 'path', '').includes('amount');
+        const shouldDisableButton = selectedParticipants.length === 0 || isEditingRequest;
-        const shouldDisableButton = selectedParticipants.length === 0;
```

https://github.com/Expensify/App/blob/dd46584f26699ab2683cc7d14770457264e294b5/src/components/MoneyRequestConfirmationList.js#L417




### What alternative solutions did you explore? (Optional)

**Comment by zzarcon** [comment] 2023-10-07 11:33
# Proposal

## Please re-state the problem that we are trying to solve in this issue.

Pressing enter on the edit amount view when focused on the amount text field creates the split bills instead of going back to the confirmation page

## What is the root cause of that problem?

The footer button on `<MoneyRequestAmountForm>` bubbles the enter event, causing a double action enter action, subsequently creating the bill when landing on the confirmation view.

By removing the `allowBubble` from the button we will prevent the event to happen twice

<img width="952" alt="image" src="https://github.com/Expensify/App/assets/1194982/03742c1c-971d-4680-826c-11aac2ec3437">

**Comment by maxconnectAbhi** [comment] 2023-10-07 14:28
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing enter on the edit amount view when focused on the amount text field creates the split bills instead of going back to the confirmation page

### What is the root cause of that problem?
The footer button on `<MoneyRequestAmountForm>` bubbles the enter event, causing a double action on enter action.
https://github.com/Expensify/App/blob/e448a7e912231ee47fd384ec73e9f3396c596871/src/pages/iou/steps/MoneyRequestAmountForm.js#L284-L292

## What changes do you think we should make in order to solve the problem?
We need to remove the allowBubble from the button.
```
                 <Button
                    success
                    pressOnEnter
                    medium={isExtraSmallScreenHeight}
                    style={[styles.w100, canUseTouchScreen ? styles.mt5 : styles.mt2]}
                    onPress={submitAndNavigateToNextPage}
                    text={buttonText}
                />
```
     

## What alternative solutions did you explore? (Optional)
NA

**Comment by mallenexpensify** [comment] 2023-10-10 00:35
@eVoloshchak can you please review the proposals above?

**Comment by mallenexpensify** [comment] 2023-10-11 02:03
Thanks @mkhutornyi , put on hold.

**Comment by mallenexpensify** [comment] 2023-10-13 22:07
@parasharrajat do you agree that this is a regression from https://github.com/Expensify/App/issues/28022 that you worked on? Trying to figure out what the next step is here

**Comment by mallenexpensify** [comment] 2023-10-18 00:55
@parasharrajat can you provide an update when you have a minute? Thx

**Comment by tylerkaraszewski** [comment] 2023-10-25 21:25
Fix is merged.

**Comment by mallenexpensify** [comment] 2023-11-08 01:00
Is compensation due here?  Wasn't sure because it looks like this was related to a regression.

**Comment by mallenexpensify** [comment] 2023-11-08 21:18
And... lastly(?) @eVoloshchak, are you owed any compensation?

**Comment by eVoloshchak** [comment] 2023-11-08 21:32
No compensation for me either, this issue is just a regression from another PR

**Comment by mallenexpensify** [comment] 2023-11-09 00:32
K, thanks!  Closing (since I'm assuming, since this is a regression, any regression tests would be created as part of the original issue, comment if ya disagree).

**Closed by mallenexpensify** 2023-11-09 00:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
