### ISSUE TITLE
  Inline code block overlap when it extends on multiple lines

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13161] opened 2022-11-29 20:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Goto https://staging.new.expensify.com/
2. Select a report
3. Send he online encyclopedia project, _Wikipedia_, is the most popular _wiki_-based website, and is one of the most widely viewed sites in the world, having been ranked

## Expected Result: 
Border is not overlapping

## Actual Result: 
Border is overlapping

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.33-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
<img width="1077" alt="issue" src="https://user-images.githubusercontent.com/43996225/204644749-354002ad-12ae-4bf0-aa4a-3fa42c121fa3.png">
<img width="960" alt="5" src="https://user-images.githubusercontent.com/43996225/204644774-f30f69e7-0d73-4f1b-b447-86948a374ea0.png">

**Issue reported by:** @mdneyazahmad 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669728664026649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by markarmanus** [comment] 2022-11-29 21:45
Proposal 

Issue: 

Its a simple styling issue when trasnalting the native components to HTML. This is done through the https://meliorence.github.io/react-native-render-html/ package. 

Fix:
To simply fix the issue we need to add line height to the styling. 
![image](https://user-images.githubusercontent.com/33489215/204654587-54ac7d8f-1558-4693-afb5-0ca9a9cb8074.png)

Before:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/33489215/204654676-3b31064a-84b9-4c0b-b992-7cd060b41a16.png">

After :

<img width="630" alt="image" src="https://user-images.githubusercontent.com/33489215/204654659-d786521f-69f6-46c8-a6e7-94afed3b6457.png">

**Comment by markarmanus** [comment] 2022-11-30 02:29
After running some tests the lineHeight:22 added would break it on android and ios. So instead we should modify the InlineCodeBlock/index.js to exten the style to include the lineHeight: 23

**Comment by mdneyazahmad** [comment] 2022-11-30 07:17
@markarmanus that is a duplicate proposal of mine posted in issue thread https://expensify.slack.com/archives/C049HHMV9SM/p1669728872475079?thread_ts=1669728664.026649&cid=C049HHMV9SM. I did not tested there on all platform, but I have noted to change the line height to best fix the issue.

**Comment by amyevans** [comment] 2022-12-02 14:26
A couple quick thoughts:
1. Line height should be expressed as a unitless value when used
2. The fix is not as straightforward as it initially seems, due to the use of the `<WrappedText />` component for iOS/Android
3. Since it's not super straightforward to fix (at least without a hacky solution), and the issue is quite minor IMO, I wonder if we should just close it as Won't Fix

Will wait for @slafortune to weigh in though

**Comment by slafortune** [comment] 2022-12-06 20:45
I agree that this is super minor and am not opposed to closing - do you agree @amyevans in your engineering opinion 😂😬

**Comment by amyevans** [comment] 2022-12-06 22:44
Agreed!

**Closed by amyevans** 2022-12-06 22:44 UTC
Labels: Daily, Bug
