### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500] Back button in SAML page doesn't work to go back to log in page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36673] opened 2024-02-16 11:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when validating PR:** https://github.com/Expensify/App/pull/35294

**Version Number:** 1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team
**Slack conversation:**

## Action Performed:
1. Log in to OD with [applausetester@applause.expensifail.com](mailto:applausetester@applause.expensifail.com)
account
2. Enable SAML required to sign in
3. Go to ND and enter [applausetester@applause.expensifail.com](mailto:applausetester@applause.expensifail.com)
in login field
4. Press Continue
5. Confirm you're automatically redirected to your SSO providers login page (with the interstitial page being briefly shown)
6. Disable SAML toggle in OD
7. Try to go back to login page in ND

## Expected Result:
Back button should work & user able to go back to login screen

## Actual Result:
Back button in SAML page doesn't work to go back to log in page. Even killing the app does not work. User has to uninstall & reinstall app to get the login screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/39dd7da0-935e-4c51-914f-b81c658e1763

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f786b4a5d463af8</li>
        <li>Upwork Job ID: 1758563440991674368</li>
        <li>Last Price Increase: 2024-02-23</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-16 11:39
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by joekaufmanexpensify** [comment] 2024-02-16 15:18
I can reproduce this. The back button doesn't work. However, the swiping-back gesture does work for me. The back button should work if it's there though. 


https://github.com/Expensify/App/assets/54866469/d6c0eea0-3a02-4e62-b046-8e8e11b50b75

**Comment by NikkiWines** [comment] 2024-02-16 18:37
Should be fine to be external! No back end code should need to change for this to be fixed.

**Comment by joekaufmanexpensify** [comment] 2024-02-16 18:46
Cool cool. TY!

**Comment by allroundexperts** [comment] 2024-02-19 02:50
@rayane-djouah Why does navigation `home` does not work?

**Comment by brandonhenry** [comment] 2024-02-19 07:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users are unable to navigate back to the login screen from the SAML SSO page. This issue persists even after restarting the app, requiring a complete reinstallation to reset the login state.

### What is the root cause of that problem?
Took a lot of setup in order to reproduce the error. Managed to do so on real iPhone XS as well. 

The root issue, is caused by the fact that SAML isn't properly configured to work correctly. When a user logs in via SAML, they are taken to the `SAMLSignInPage` component. 

**This page is incorrectly receiving props which results in the webview having the incorrect url structure and broken SAML page**

![image](https://github.com/Expensify/App/assets/15656774/d95415fe-1267-4fb8-8e91-6406fd883283)

The reason you cannot go back to the sign in page and you are stuck even after an app reload, is because no matter what, anytime you come back to the app, it will always be set to this URL:
https://github.com/Expensify/App/blob/b7418b909338d9b5c1583b6a42cc72fe46f0512a/src/pages/signin/SAMLSignInPage/index.native.tsx#L19

Which, I am seeing turn out as `https://www.expensify.com/authentication/saml/login?email=undefined&referer=ecash&platform=android`

That must mean that `credentials` is being lost or reset at some point between clicking "Sign In via SAML" and reaching the SAML page. That said, once we are on the SAML page, assuming `credentials` is now corrupt / not what we are expecting, we can't expect the navigate back to home button to work becuase the `Session.clearSignInData` is likely not clearing the right data we need to produce any re-render.

```
<HeaderWithBackButton
      title=""
      onBackButtonPress={() => {
          Session.clearSignInData();
          Navigation.navigate(ROUTES.HOME);
      }}
  />

```

### What changes do you think we should make in order to solve the problem?

**Potential Backend Issue**
So I think this is both a frontend and backend issue. Seeing as the actual SAML integration is probably handled backend?

Main question on this is, should the backend be returning `undefined` for the email if it messes up? Why is it returning undefined?

**To fix on the frontend:**

update `handleNavigationStateChange` to check for `email` to be `undefined`. If so, kick us back to the login page immediately

```
 const handleNavigationStateChange = useCallback(
        ({url}: WebViewNativeEvent) => {
            // ... other code
            // If the login attempt is unsuccessful OR email from backend is undefined, set the error message for the account and redirect to sign in page
            if (searchParams.has('error') || searchParams.get('email') === 'undefined') {
                Session.clearSignInData();
                Session.setAccountError(searchParams.get('error') ?? 'Domain Not Setup for SAML');
                Navigation.navigate(ROUTES.HOME);
            }
        },
        [credentials?.login, shouldShowNavigation, account?.isLoading],
    );

```

Original: 

https://github.com/Expensify/App/blob/b7418b909338d9b5c1583b6a42cc72fe46f0512a/src/pages/signin/SAMLSignInPage/index.native.tsx#L25

**Comment by allroundexperts** [comment] 2024-02-20 15:29
> That must mean that credentials is being lost or reset at some point between clicking "Use single sign-on" and reaching the SAML page

Why is it being lost?

> assuming `credentials` is now corrupt / not what we are expecting, we can't expect the navigate back to home button to work becuase the `Session.clearSignInData` is likely not clearing the right data we need to produce any re-render

@brandonhenry Can you elaborate on this point? How is the corrupt session data linked with the re-render needed for showing the home page?

**Comment by joekaufmanexpensify** [comment] 2024-02-21 15:16
Proposals still in review

**Comment by brandonhenry** [comment] 2024-02-21 20:37
Finally got android and ios builds running locally. Digging deeper here

**Comment by brandonhenry** [comment] 2024-02-22 00:00
So found the culprit @allroundexperts - its definitely that we need to do:

```javascript
Navigation.goBack(ROUTES.SAML_SIGN_IN);
```
https://github.com/Expensify/App/assets/15656774/167a1003-5cb5-404b-9efe-87fbdacdd985


I did notice that the `SAMLSignInPage` is still broken though - based on the logs in pic at bottom, here are my findings:

The log indicates that the credentials are being cleared at some point during the SAML sign-in process. Here are a few key points from the log that might help explain why the credentials and login information are being lost:

1. **BeginSignIn API Call**: The `BeginSignIn` API is called with an email, and the request is completed successfully (`jsonCode: 200`) meaning the initial sign-in process starts correctly.

2. **Navigating to SAML Sign-in**: The app navigates to the SAML sign-in route (`"/sign-in-with-saml"`), which indicates that the SAML sign-in process is being initiated.

3. **Clearing Sign-in Data**: The log shows multiple instances of "Clearing sign in data" immediately following the "Handling SAML navigation change" messages. This suggests that some part of the SAML sign-in process or navigation logic is triggering the clearing of sign-in data, including credentials.

4. **Empty Credentials**: After the sign-in data is cleared, the log shows "Credentials: - """, indicating that the credentials are indeed empty at this point.

<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/15656774/2698c3eb-8367-4d8e-a1ff-d589a288f618">

**Comment by brandonhenry** [comment] 2024-02-22 06:18
Took a fair amount of digging, but finally figured this one out. We don't need to use `.goBack`

@allroundexperts 

## Updated Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users are unable to navigate back to the login screen from the SAML SSO page. This issue persists even after restarting the app, requiring a complete reinstallation to reset the login state.

### What is the root cause of that problem?
The issue is caused by the Navigation setup of the `PublicScreens` stack navigator. Specifically, this line
https://github.com/Expensify/App/blob/c425c3412856c07d6126da4147a8af4b49cc8db1/src/libs/Navigation/linkTo.ts#L206

When you press the back button, `actionForBottomTabNavigator` is calculated and returned as an empty object. This causes the navigation to early return and never actually do anything

### What changes do you think we should make in order to solve the problem?
Instead of early returning there, and breaking navigation - we should instead check if the `actionForBottomTabNavigator` variable is there and send the dispatch and keep running the rest of the code below

```
if (actionForBottomTabNavigator) root.dispatch(actionForBottomTabNavigator);
```

This fixes navigation. The main reason I think navigation is setup like this is because it needs to work the same for PublicScreens and AuthScreens so the navigate function works the same for both. However, I don't think we have any actionForBottomTabNavigator to calculate when not signed in (going from SAML back to the homepage). This was causing some properties to not be available in the navigation route, thus resulting in `actionForBottomTabNavigator` being `null`

**Comment by joekaufmanexpensify** [comment] 2024-02-22 20:34
Proposals still in review

**Comment by allroundexperts** [comment] 2024-02-23 16:00
Thanks for the updated proposal @brandonhenry. I still don't understand why the action has a payload of `NAVIGATORS.BOTTOM_TAB_NAVIGATOR` in the first place? Shouldn't we just have an action of type `CONST.NAVIGATION.ACTION_TYPE.NAVIGATE`?

**Comment by allroundexperts** [comment] 2024-02-23 16:01
@joekaufmanexpensify I think it would be good if we can maybe raise the bounty to get more proposals.

**Comment by joekaufmanexpensify** [comment] 2024-02-26 15:28
Not overdue

**Comment by joekaufmanexpensify** [comment] 2024-02-27 15:23
Floated it in Slack [here. ](https://expensify.slack.com/archives/C01GTK53T8Q/p1709047383995199) Let's see if that generates more interest before doing anything else.

**Comment by joekaufmanexpensify** [comment] 2024-02-27 15:23
@allroundexperts is there not a path where you could see us using one of the two existing proposals on the issue?

**Comment by allroundexperts** [comment] 2024-02-27 15:27
Hm... the RCA isn't fully clear to me here so not sure if we can go along with any of these proposals. @brandonhenry Did you manage to find an answer for my above question?

**Comment by joekaufmanexpensify** [comment] 2024-02-27 15:30
Someone flagged that this may actually be a dupe of [this one](https://github.com/Expensify/App/issues/29825). Thoughts?

**Comment by allroundexperts** [comment] 2024-02-27 15:34
@joekaufmanexpensify The issue you linked is specifically for Desktop only. The accepted proposal there manipulates the window object which won't work on native applications.

**Comment by situchan** [comment] 2024-02-27 15:50
@alitoshmatov can confirm if the solution is supposed to fix this as well

**Comment by allroundexperts** [comment] 2024-02-27 15:59
@joekaufmanexpensify I saw the accepted [proposal](https://github.com/Expensify/App/issues/29825#issuecomment-1925459656) actually. In it, its proposed to use the `window` object. This object does not exist on native platforms but we can hold this one on #29825 as I might be wrong.

**Comment by alitoshmatov** [comment] 2024-02-27 17:48
This issue does look similar to https://github.com/Expensify/App/issues/29825 since both working with the SAML flow. But I think this issue is addressing different bug. I would suggesting holding this one

**Comment by alitoshmatov** [comment] 2024-02-28 16:50
No https://github.com/Expensify/App/issues/29825 won't fix this issue, but I thought this two might effect each other's progress since they both addressing the same functionality.

**Comment by ikevin127** [comment] 2024-02-29 15:24
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Back button in SAML page doesn't work to go back to log in page, esentially locking the user on the SAML page.
Even killing the app does not work, the user has to uninstall & reinstall app to get to the login screen.

### What is the root cause of that problem?

> [!NOTE]
> `Navigation.navigate()` === `Navigation.navigate(ROUTES.HOME)` since if no route is passed, navigate's default is HOME -> see code [here](https://github.com/Expensify/App/blob/104565b99a82751af0dd397c910f38958b6cb39a/src/libs/Navigation/Navigation.ts#L169).

The reason why calling navigate to home doesn't reset the navigation anymore while unauthenticated (public screens) which broke the SAML page `onBackButtonPress` functionality comes from the recent navigation refactoring.

More context can be found on this [issue](https://github.com/Expensify/App/issues/34177), where I detailed the root cause:

> Since the new navigation was implemented (bottom tab navigator), `Navigation.navigate()` does not work anymore in calling navigate to the home route like it did before and I suspect this has to do with the new navigation logic -> which I cannot fully understand the inner workings of.

<details>
<summary>Here is the involved code (before / after)</summary>

| Before | After |
| ------------- | ------------- |
| https://github.com/Expensify/App/blob/76e5b1cbd80e7dc55c52f47c5572b2984a7f7ed6/src/libs/Navigation/linkingConfig.ts#L33-L36 | https://github.com/Expensify/App/blob/9bfe961622d03de5ac8e18652bbb56dda5ed9f60/src/libs/Navigation/linkingConfig/config.ts#L26-L38 |

| Before | After |
| ------------- | ------------- |
| https://github.com/Expensify/App/blob/76e5b1cbd80e7dc55c52f47c5572b2984a7f7ed6/src/libs/Navigation/AppNavigator/PublicScreens.tsx#L19-L23 | https://github.com/Expensify/App/blob/9bfe961622d03de5ac8e18652bbb56dda5ed9f60/src/libs/Navigation/AppNavigator/PublicScreens.tsx#L20-L25 |

</details>

> Besides these important changes in routing structure, we also had some important changes to the `linkTo` function which actually calls navigate when `Navigation.navigate()` is called.

### What changes do you think we should make in order to solve the problem?

We should replace `Navigation.navigate()` with `Navigation.goBack()` just like other PR's did (https://github.com/Expensify/App/pull/35850) in order to fix similar issues after the new navigation logic was implemented.

Simply replace this line:
https://github.com/Expensify/App/blob/807ce54e7b045f4e19c0a5b2876f401d23869d8f/src/pages/signin/SAMLSignInPage/index.native.tsx#L61
with:

```ts
Navigation.isNavigationReady().then(() => {
    Navigation.goBack();
});
```
and we're good to go!

**Comment by allroundexperts** [comment] 2024-02-29 16:00
@ikevin127's [proposal](https://github.com/Expensify/App/issues/36673#issuecomment-1971375831) looks good to me. It has a clear RCA and proposes a simple fix.

🎀 👀 🎀 C+ reviewed

**Comment by ikevin127** [comment] 2024-03-01 10:26
PR will be ready in 2-3 hours!

**Comment by ikevin127** [comment] 2024-03-01 17:10
PR https://github.com/Expensify/App/pull/37618 ready for review!

**Comment by joekaufmanexpensify** [comment] 2024-03-11 15:02
@allroundexperts can you complete BZ so we can prep to issue payment?

**Comment by joekaufmanexpensify** [comment] 2024-03-13 21:24
[Bumped in slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1710365032483619)

**Comment by allroundexperts** [comment] 2024-03-13 21:36
## Reviewer checklist

1. https://github.com/Expensify/App/pull/33280
2. The above PR changed the structure of navigation stacks which caused this. There isn't any single line I was able to point to.
3. N/A
4. Regression test would be useful here. The test steps given in the OP should be clear enough.

**Comment by ikevin127** [comment] 2024-03-14 20:56
@joekaufmanexpensify 👋 Any blockers from completing the payment here ?

**Comment by joekaufmanexpensify** [comment] 2024-03-14 21:03
Nope. I will complete it today.

**Comment by joekaufmanexpensify** [comment] 2024-03-14 21:10
Checklist is complete. All set to issue payment. We need to pay: 

- @ikevin127 $500 for PR via upwork. 
- @allroundexperts $500 for C+ review via NewDot.

**Comment by joekaufmanexpensify** [comment] 2024-03-14 21:11
@ikevin127 $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-03-14 21:12
@allroundexperts could you please request $500 via NewDot and confirm here once complete?

**Comment by allroundexperts** [comment] 2024-03-17 23:00
All done. Feel free to close!

**Closed** 2024-03-18 08:45 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by joekaufmanexpensify** [comment] 2024-03-18 12:21
TY!

**Comment by JmillsExpensify** [comment] 2024-03-22 21:29
$500 approved for @allroundexperts based on summary.
