### ISSUE TITLE
[$1000] Setting - Old values in WS `general setting are remain after Saved and reopen again

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14840] opened 2023-02-05 03:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate staging.new.expensify.com and log in
2. Open WS general setting
3. Change name/currency and save
4. Close WS general setting and open again

## Expected Result:
Saved values should remain after General settings reopened

## Actual Result:
after WS name and currency are changed --> old values will visible if General settings closed and opened again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.65.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/216799400-9ea0a409-f961-4a70-a720-dc5cf79dd088.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128665dc5e4e8d6b4</li>
        <li>Upwork Job ID: 1622587433874833408</li>
        <li>Last Price Increase: 2023-02-06</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-02-06 13:23
Can reproduce - 

https://user-images.githubusercontent.com/62073721/216982526-9069e189-f85c-4524-81c0-da292b81e09f.mp4

**Comment by laurenreidexpensify** [comment] 2023-02-06 13:25
Seems similar to https://github.com/Expensify/App/issues/14784

**Comment by bernhardoj** [comment] 2023-02-06 13:36
Yeah, I think it has the same root cause https://github.com/Expensify/App/issues/14784#issuecomment-1415229212.

**Comment by anupp-11** [comment] 2023-02-07 10:35
As mentioned, the Issue is similar to #14784 

It is working after updating the Form.js file.

https://user-images.githubusercontent.com/21983426/217221300-38f240cc-32f1-4af1-857c-7b88e483e151.mov

**Comment by mollfpr** [comment] 2023-02-07 10:51
Thanks guys! @Gonals @laurenreidexpensify, we can close this.

**Closed** 2023-02-09 22:02 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
