### ISSUE TITLE
[HOLD for payment 2023-09-21] [HOLD for payment 2023-09-20] web - Pronouns - Unable to deselect pronouns once it is selected

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27235] opened 2023-09-12 11:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Profile > Pronouns.
3. Select a pronouns.
4. Click on the pronouns again.
5. Click on the selected pronouns to deselect it.

## Expected Result:
The pronouns is now deselected.

## Actual Result:
The pronouns remain selected.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.68-12

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/392b5f22-5ff8-4a18-b75c-a27e6bcbd805

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694495687512659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-09-12 11:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not able to remove the pronoun

### What is the root cause of that problem?
It is a regression from https://github.com/Expensify/App/pull/26192 where `currentPronouns` is a string and we are trying to access `keyForList` on it. With that even though we click on the already selected pronoun it will again pass that value for the api call instead of empty string.
https://github.com/Expensify/App/blob/662af46c49bbe9690de71ecfe9ad98a9481f0f24/src/pages/settings/Profile/PronounsPage.js#L64
Earlier we were creating the object `initiallyFocusedOption` with the fields `text` & `keyForList` [here](https://github.com/Expensify/App/pull/26192/files#diff-2becc643119bc669cba2992bd64114fa69691d2a7d3fe265026322b57f4c75fdL74).

### What changes do you think we should make in order to solve the problem?
We need to correct the condition with `selectedPronouns.value === currentPronouns`
https://github.com/Expensify/App/blob/662af46c49bbe9690de71ecfe9ad98a9481f0f24/src/pages/settings/Profile/PronounsPage.js#L64

**Comment by Pluto0104** [comment] 2023-09-12 11:52
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
We're currently unable to remove pronouns from the user profile.
### What is the root cause of that problem?
This is a regression of https://github.com/Expensify/App/pull/26192. It's crucial to treat this as a deploy blocker since it doesn't occur on NewDot.
The problem lies in how we're using conditions to update pronouns incorrectly.
In this code snippet, currentPronouns.keyForList is undefined because we have made significant changes in this component. Therefore, we need to use the correct currentPronounsKey.
https://github.com/Expensify/App/blob/5f668c669a501a94caebbb434a656580e3bcfb24/src/pages/settings/Profile/PronounsPage.js#L64
### What changes do you think we should make in order to solve the problem?
We need to ensure that we use the correct current pronouns key.
PersonalDetails.updatePronouns(selectedPronouns.keyForList === currentPronounsKey ? '' : lodashGet(selectedPronouns, 'value', ''));
### What alternative solutions did you explore? (Optional)
N/A

**Comment by situchan** [comment] 2023-09-12 12:00
@Pluto0104's [proposal](https://github.com/Expensify/App/issues/27235#issuecomment-1715579677) looks good.
Since this is deploy blocker, I did quick review on this one as Santhosh (C+ on offending PR) is OOO for now.
cc: @joelbettner

**Comment by Pujan92** [comment] 2023-09-12 12:01
@situchan have you checked my [proposal](https://github.com/Expensify/App/issues/27235#issuecomment-1715554263) too?

**Comment by Pluto0104** [comment] 2023-09-12 12:03
@Pujan92 your solution won't work because `currentPronouns` is not the same as `selectedPronouns.keyForList`.

**Comment by situchan** [comment] 2023-09-12 12:03
> @situchan have you checked my [proposal](https://github.com/Expensify/App/issues/27235#issuecomment-1715554263) too?

yes, it's not correct solution. It was original logic to use key instead of value.

**Comment by Pujan92** [comment] 2023-09-12 12:10
> @Pujan92 your solution won't work because `currentPronouns` is not the same as `selectedPronouns.keyForList`.

actually, I am suggested to use `selectedPronouns.value` with currentPronouns so it will work.

> yes, it's not correct solution. It was original logic to use key instead of value.

Ok, but I still believe the value is also unique so we can use that also here. Thoughts @thiagobrez ?

**Comment by thiagobrez** [comment] 2023-09-12 13:29
Both solutions work the same way, just use different keys, I have no preference

@joelbettner @situchan I'm the original PR author, should I take this as a regression?

**Comment by thiagobrez** [comment] 2023-09-12 15:04
PR is ready to review here: https://github.com/Expensify/App/pull/27256

**Comment by abekkala** [comment] 2023-09-14 19:54
### PAYMENTS FOR SEPT 21
* Issue reported by: @gadhiyamanan [$50]

@joelbettner I don't see any other assignees on here - were there other contributors in need of Upwork payment here?

**Comment by joelbettner** [comment] 2023-09-14 20:10
> were there other contributors in need of Upwork payment here?

@abekkala I don't think so.

**Comment by situchan** [comment] 2023-09-14 20:22
I reviewed [PR](https://github.com/Expensify/App/pull/27256) - https://github.com/Expensify/App/issues/27235#issuecomment-1715940302

**Comment by joelbettner** [comment] 2023-09-14 20:28
My bad...yes, @situchan reviewed it, @abekkala.

**Comment by abekkala** [comment] 2023-09-18 18:23
PAYMENTS FOR SEPT 21
Issue reported by: @gadhiyamanan [$50]
PR Review: @situchan [$500]

**Comment by abekkala** [comment] 2023-09-25 08:00
I'm unable to get Upwork to save a job posting so I can issue payment. 
working on it!

**Comment by abekkala** [comment] 2023-09-26 05:57
@gadhiyamanan and @situchan 
Upwork is back in action and I sent you both payment offers. Once accepted I'll process the payments!

**Comment by gadhiyamanan** [comment] 2023-09-26 05:57
@abekkala offer accepted, thanks!

**Comment by abekkala** [comment] 2023-09-26 05:59
@gadhiyamanan payment made and contract ended. Thank you! 🎉

**Comment by abekkala** [comment] 2023-09-29 05:08
@situchan can you please accept the payment offer in Upwork so I can process payment to you. 

Thanks!

**Comment by abekkala** [comment] 2023-10-02 15:38
payments made - closing

**Closed by abekkala** 2023-10-02 15:38 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
