### ISSUE TITLE
[$500] Creating an optimistic action with a default avatar (SVG component) causes a failed write to Onyx storage

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#28885] opened 2023-10-05 01:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

Coming from: https://github.com/Expensify/Expensify/issues/313434#issuecomment-1747916128 an investigation into why storing data to Onyx can fail...

- I am not sure exactly. But there are several code flows where we might default to an SVG avatar in `ReportUtils.js`.

https://github.com/Expensify/App/blob/0d55bc9ced437a38f521e01322019c719651ec0b/src/libs/ReportUtils.js#L2660-L2661
https://github.com/Expensify/App/blob/0d55bc9ced437a38f521e01322019c719651ec0b/src/libs/ReportUtils.js#L2641-L2642
https://github.com/Expensify/App/blob/0d55bc9ced437a38f521e01322019c719651ec0b/src/libs/ReportUtils.js#L2602-L2603
https://github.com/Expensify/App/blob/0d55bc9ced437a38f521e01322019c719651ec0b/src/libs/ReportUtils.js#L2485-L2486
https://github.com/Expensify/App/blob/0d55bc9ced437a38f521e01322019c719651ec0b/src/libs/ReportUtils.js#L2411-L2412
https://github.com/Expensify/App/blob/0d55bc9ced437a38f521e01322019c719651ec0b/src/libs/ReportUtils.js#L2337-L2338
https://github.com/Expensify/App/blob/0d55bc9ced437a38f521e01322019c719651ec0b/src/libs/ReportUtils.js#L2298-L2299
https://github.com/Expensify/App/blob/0d55bc9ced437a38f521e01322019c719651ec0b/src/libs/ReportUtils.js#L1970-L1971
https://github.com/Expensify/App/blob/0d55bc9ced437a38f521e01322019c719651ec0b/src/libs/actions/Task.js#L626-L627

- IndexedDB cannot save this to storage and throws an error.
- This error is confirmed throwing in the logs.

## Expected Result:

1. The optimistic report action is saved correctly

## Actual Result:

1. The user cannot persist the action in the device storage and an error is thrown

![2023-10-04_15-47-42](https://github.com/Expensify/App/assets/32969087/4756aa1b-11d0-410b-8967-a60527a79172)

## Workaround:

Yes - it will largely not be felt by many people. 
However if they create the action while offline, then kill the app, then reopen then it could lead to some data loss or unexpected behavior

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** `main`
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f221fc1261af7d28</li>
        <li>Upwork Job ID: 1710091720770150400</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-10-05 06:45
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
svg component not able store the onyx.

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/1eae8007bb79e7913b039182224c1ac3efc04e8c/src/libs/UserUtils.ts#L73 
 `getDefaultAvatar` will return the local reference so that not able to be stored in the onyx.

in react when we import .svg file its as function we can use as a component also like `<SVG/>`
### What changes do you think we should make in order to solve the problem?

we need change `getDefaultAvatarURL` it will as a url string. and url image will be cached in the Image tag by default.

https://github.com/Expensify/App/blob/1eae8007bb79e7913b039182224c1ac3efc04e8c/src/libs/UserUtils.ts#L91

**Comment by twisterdotcom** [comment] 2023-10-05 16:37
@marcaaron can I just slap `External` on this?

**Comment by marcaaron** [comment] 2023-10-05 22:28
yes. But I'm curious to understand whether we ever supported saving SVG to IndexedDB. 

Maybe @thienlnam or @Beamanator remember the answer to this one. I think both of y'all have investigated some things related to Onyx and image storage IIRC.

**Comment by talent-dev610** [comment] 2023-10-06 02:50
My proposal
I think Onyx only accepts javascript code.
So traditionally you can't store SVG file to the Onyx.
In this case , you have to convert SVG to the base64 encoded code.

**Comment by thienlnam** [comment] 2023-10-06 10:11
> But I'm curious to understand whether we ever supported saving SVG to IndexedDB.

**Comment by thienlnam** [comment] 2023-10-06 10:25
> But I'm curious to understand whether we ever supported saving SVG to IndexedDB.

This was the [PR](https://github.com/Expensify/react-native-onyx/pull/102) where we added file handling in Onyx - I haven't been following along with the changes that we've made since then but there's perhaps a chance that indexdb doesn't support storing SVGs or maybe we need to do something to the SVG to be able to store it as a blob

**Comment by Beamanator** [comment] 2023-10-06 10:31
I think I've seen this issue before when we tried to store default avatars in Onyx & from what i've seen, there's always errors when we try to store SVGs in Onyx - cc @grgia who also worked on avatars a lot in the past

**Comment by s77rt** [comment] 2023-10-06 16:24
@talent-dev610 Thanks for the proposal. Encoding will work but it will add more space and computation. Regardless your proposal is not complete as it's not clear when to encode / decode. Is this supposed to be done in `react-native-onyx`?

**Comment by pradeepmdk** [comment] 2023-10-06 16:46
@s77rt we are using https://www.npmjs.com/package/@svgr/webpack plugin for loading the svg file. 
![Screenshot 2023-10-06 at 10 14 22 PM](https://github.com/Expensify/App/assets/16595846/9f2b96e7-9ef6-4f01-b4c0-61bb85e9fa97)

we can change this to 
any one of them 
 use: ['@svgr/webpack', 'file-loader'], if we use file loader we will get like this /f69bf6542f9d0b403b9b1e3ec5679fa8.svg
`url-loader` we will get an base64
'raw-loader' we will get original svg string

this three we can able to store in the onyx.

**Comment by pradeepmdk** [comment] 2023-10-07 00:54
@s77rt Proposal updated https://github.com/Expensify/App/issues/28885#issuecomment-1748189633

**Comment by s77rt** [comment] 2023-10-07 18:46
@pradeepmdk Thanks for the update. I think option 1 will do it but we will have a lot of code to update / test. Ideally we would want functions to be supported in Onyx store but we will have serialize / deserialize data internally.

e.g.:


```js
// Insert phase
myFun = getDefaultAvatar(1);
if (typeof myFun === 'function') {
    myFun = myFun.toString();
}
```
 
```js
// Retrieval phase
myFun = eval('(' + myFun + ')');
```


But eval is evil

**Comment by pradeepmdk** [comment] 2023-10-07 23:51
>  Ideally we would want functions to be supported in Onyx store but we will have serialize / deserialize data internally.

serialize / deserialize we are going to do in App/react-native-onyx ?

**Comment by pradeepmdk** [comment] 2023-10-08 00:06
> if we use file-loader we will get like this /f69bf6542f9d0b403b9b1e3ec5679fa8.svg (like other file import .png, .jpeg)

@s77rt 
we can use this as well 

but we have an issue on offline in web(on native it will work fine). because offline on the web it will fail to load to this reference. 
so we need to implement the service worker to cache those files.

**Comment by s77rt** [comment] 2023-10-08 19:18
@pradeepmdk 

> serialize / deserialize we are going to do in App/react-native-onyx ?

If we are going with the serialize / deserialize path then it must be done within react-native-onyx.


I'm not sure about the file loader as we currently use the imported svg files as components.

**Comment by s77rt** [comment] 2023-10-11 00:56
Not overdue. Still looking for proposals

**Comment by s77rt** [comment] 2023-10-13 17:13
Still looking for proposals

**Comment by twisterdotcom** [comment] 2023-10-16 11:43
Only overdue because of the weekend.

**Comment by twisterdotcom** [comment] 2023-10-16 11:44
@pradeepmdk seems like we're making progress with your possible solution though. Any more ideas?

**Comment by pradeepmdk** [comment] 2023-10-17 01:20
sorry missed the notification 
@s77rt 
> I'm not sure about the file loader as we currently use the imported svg files as components.

as we are now using it as a component because the file loader does not load the image offline. 

we can convert svg to json but we need raw svg so we can use `raw-loader`
https://github.com/elrumordelaluz/svgson
like Lottie https://lottiefiles.com/svg-to-lottie

**Comment by s77rt** [comment] 2023-10-17 18:21
@pradeepmdk Can you please clarify the following:
- If we are going to use file-loader. How are we going to migrate from the current structure where we use svg as components?
- Isn't the file-loader unsupported on native? i.e. we can't use `<Image src={loadedSvg} />`

**Comment by pradeepmdk** [comment] 2023-10-20 16:39
> @pradeepmdk Can you please clarify the following:
> 
> * If we are going to use file-loader. How are we going to migrate from the current structure where we use svg as components?

if we choose file loader we can use like this <Image src={loadedSvg} /> instead of <LodedSvg/> and as i said it fail on offline, we need implement service worker 

> * Isn't the file-loader unsupported on native? i.e. we can't use `<Image src={loadedSvg} />`

file-loader is web. for react-native in metro we are using `react-native-svg-transformer` this will convert as a functional component once we removed we will get as a file loader like .png import 

i have one more idea instead of we can directly store the svg string in onyx and create a functional component on that.

like what svgr doing https://react-svgr.com/docs/what-is-svgr/ svgr doing on build time we can rewrite as function 

or
we can try json format as well svg to json and store it in onyx and retrive the json and json -> svg component

**Comment by s77rt** [comment] 2023-10-21 01:41
@pradeepmdk The use of file-loaders seems to be a breaking change that would required a lot of changes.

If I understood you correctly, you are saying that for native svg will be imported as components and can be used directly and for web they will be imported as files and have to be used with `<Image />` component. Is that accurate?

**Comment by twisterdotcom** [comment] 2023-10-23 16:16
Waiting on a response from @pradeepmdk. Not overdue, discussion ongoing.

**Comment by pradeepmdk** [comment] 2023-10-23 16:36
>If I understood you correctly, you are saying that for native svg will be imported as components and can be used directly and for web they will be imported as files and have to be used with <Image /> component. Is that accurate? 

no we should use <Image /> components both native and web.

@s77rt Yes this is breaking changes. 
so I am trying to avoid this ...
can we try like this https://github.com/dev-javascript/string-to-react-component. they are using `Function`
or
https://www.npmjs.com/package/react-native-jsx-parser
https://github.com/TroyAlford/react-jsx-parser
https://www.npmjs.com/package/acorn

**Comment by s77rt** [comment] 2023-10-23 21:19
@pradeepmdk Thanks for the update. Given that the proposal is a breaking change, it may be better to explore other options. Can we fix this at `react-native-onyx` level instead?

**Comment by pradeepmdk** [comment] 2023-10-24 15:57
sure @s77rt I am checking these options now 
https://www.npmjs.com/package/react-native-jsx-parser
https://github.com/TroyAlford/react-jsx-parser
https://www.npmjs.com/package/acorn

**Comment by twisterdotcom** [comment] 2023-10-26 13:28
Any update today @pradeepmdk?

**Comment by pradeepmdk** [comment] 2023-10-26 15:57
yes, @twisterdotcom I working on the solution I will update the working solution this weekend.

**Comment by s77rt** [comment] 2023-10-30 09:01
Not overdue. Looking for more proposals

**Comment by s77rt** [comment] 2023-11-01 16:33
Still looking for proposals

**Comment by twisterdotcom** [comment] 2023-11-02 13:50
Still waiting for proposals. @pradeepmdk have you made any progress on your ideas here?

@marcaaron should we take this internal, or leave it external indefinitely? How important is it to get done soon?

**Comment by s77rt** [comment] 2023-11-08 17:18
Same ^

**Comment by s77rt** [comment] 2023-11-13 09:02
Not overdue. Still looking for more proposals

**Comment by pradeepmdk** [comment] 2023-11-13 09:07
sorry for the delay my system is broken I ordered a new system so waiting for that. I will update you on the coming 16

**Comment by twisterdotcom** [comment] 2023-11-13 11:53
Okay, let's downgrade for now then.

**Comment by twisterdotcom** [comment] 2023-11-16 22:07
How you doing here @pradeepmdk?

**Comment by pradeepmdk** [comment] 2023-11-16 23:38
yes, @twisterdotcom working on that only. I will update here today end of the day.

**Comment by pradeepmdk** [comment] 2023-11-17 22:23
@s77rt for current update now i am convert the svg component into [Ast](https://github.com/estree/estree) format and stored in the onyx.
<img width="833" alt="Screenshot 2023-11-18 at 3 51 57 AM" src="https://github.com/Expensify/App/assets/16595846/dfda399d-e8b7-4ab8-b765-dd1529374ce8">
now i am working on the again convert into svg component on run time. using this https://babeljs.io/docs/babel-core#transformfromastsync 
i will update you here once this done.

**Comment by s77rt** [comment] 2023-11-18 13:34
@twisterdotcom Can you please add `External` and `Help Wanted` labels back

**Comment by pradeepmdk** [comment] 2023-11-21 03:01
@s77rt  https://babeljs.io/docs/babel-core#transformfromastsync not working on run time even if we fixed we will get the result as string only.  so in the end, we need to use either `eval` or `Function` to execute the javascript code 
<img width="319" alt="Screenshot 2023-11-21 at 8 30 35 AM" src="https://github.com/Expensify/App/assets/16595846/92a769b3-70c8-4b9f-bfa7-8f8d389f70c3">

**Comment by s77rt** [comment] 2023-11-21 12:33
@pradeepmdk If this is still going to be done in `react-native-onyx` then it may be okay. Although for final decision we will probably have to go through a slack thread to get multiple confirmation on this change.

**Comment by s77rt** [comment] 2023-11-21 17:19
@pradeepmdk I think just a string is enough if there is no benefit in using the Ast format.

**Comment by pradeepmdk** [comment] 2023-11-23 11:09
@s77rt so what is next progress here ?

**Comment by s77rt** [comment] 2023-11-23 12:47
@pradeepmdk Can you please explain how you will achieve the encode/decode functionality in `react-native-onyx`?

**Comment by talent-dev610** [comment] 2023-12-01 15:23
My proposal
I think Onyx only accepts javascript code.
So traditionally you can't store SVG file to the Onyx.
In this case , you have to convert SVG to the base64 encoded code for saving SVG to Onyx.

import { SvgXml } from 'react-native-svg';
import { encode } from 'base-64';

const svgXml = '';
const svgBase64 = encode(svgXml);

import Onyx from 'react-native-onyx';

Onyx.set('svgImage', svgBase64);

**Comment by s77rt** [comment] 2023-12-07 12:55
Still waiting for proposals

**Comment by s77rt** [comment] 2023-12-11 10:37
Same ^

**Comment by s77rt** [comment] 2023-12-13 16:00
Still looking for proposals

**Comment by twisterdotcom** [comment] 2023-12-14 09:39
Okay, I will allow @marcaaron to reopen if he thinks differently, but given we are moving towards a world where [only real world reported bugs will be fixed](https://expensify.slack.com/archives/C01GTK53T8Q/p1702496349813859), I'm going to close this.

**Closed by twisterdotcom** 2023-12-14 09:39 UTC
Labels: External, Engineering, Daily, Internal, Help Wanted, Bug
