### ISSUE TITLE
Not able to scroll all the way to bottom in the LHN as the footer is covering the bottom chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37362] opened 2024-02-27 22:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708906501419769

## Action Performed:
1. Open app with lots of chat
2. Scroll down the LHN to reach the bottom chat

## Expected Result:
Able to reach the bottom chat 

## Actual Result:
Bottom chat is covered by the footer

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![IMG_0611](https://github.com/Expensify/App/assets/38435837/d322f807-c0c0-4068-9441-f9ce05984b4b)

https://github.com/Expensify/App/assets/38435837/3c8cdffd-42f2-4c93-9825-ea60ed530658

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment] 2024-02-28 20:39
I'm having trouble getting anything to work on the iOS app currently. Going to keep trying to reproduce.

**Comment by lschurr** [comment] 2024-02-28 20:41
Hm, I also have an iPhone 15 pro, but I can't reproduce this one.

**Comment by lschurr** [comment] 2024-02-28 21:28
Closing since it seems this is no longer happening.

**Closed by lschurr** 2024-02-28 21:28 UTC
Labels: Daily, Bug
