### ISSUE TITLE
Thread - Parent message is missing when navigating to it via deep link for the first time

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#37575] opened 2024-02-29 23:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** https://expensify.slack.com/archives/C9YU7BX5M/p1709147975751119?thread_ts=1709147904.723589&cid=C9YU7BX5M

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Create a room under workspace where User B is not a member.
3. [User A] Send a message and create several nested threads to the parent message.
4. [User A] Invite User B to the deep thread via mention.
5. Copy the link to the deep thread.
6. [User B] Navigate to the deep link to the thread.

## Expected Result:
Parent message will show up on the thread.

## Actual Result:
Parent message does not show up on the thread when navigating to the thread via deep link for the first time. it only reveals after the thread is revisited.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/ba72614e-e143-4e7e-85a6-5af55f2be577

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016244dfc27632f1f4</li>
        <li>Upwork Job ID: 1764727000160501760</li>
        <li>Last Price Increase: 2024-03-04</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2024-02-29 23:05
@marcaaron tagging you as per this [conversation](https://expensify.slack.com/archives/C9YU7BX5M/p1709147975751119?thread_ts=1709147904.723589&cid=C9YU7BX5M)

**Comment by isabelastisser** [comment] 2024-03-04 17:30
Bump @marcaaron. Thanks!

**Comment by marcaaron** [comment] 2024-03-04 18:59
Thanks! I'll look into this internally, but it will be at a somewhat lower priority (probably won't get around to it until next week or later).

**Comment by marcaaron** [comment] 2024-03-13 02:17
I will try looking at this one tomorrow.

**Comment by marcaaron** [comment] 2024-03-18 22:23
Not yet, sorry. Competing priorities at the moment.

**Comment by isabelastisser** [comment] 2024-04-02 01:28
It was added to collect - Due May 1st.

**Comment by trjExpensify** [comment] 2024-04-05 12:23
Why wave-collect? It looks like it's related to rooms/threads, which is more #vip-vsb territory.

**Comment by isabelastisser** [comment] 2024-04-05 13:31
Thanks for the feedback, Tom! I moved it to #vip-vsb now.

**Comment by marcaaron** [comment] 2024-04-24 22:07
Still haven't had a chance to look at this one. Staying assigned as it's related to a feature I added in the backend. But happy to pass it off if someone is looking for something to work on.

**Comment by isabelastisser** [comment] 2024-05-07 01:14
Added the hot pick label for the engineering assignment.

**Comment by mvtglobally** [comment] 2024-05-13 14:19
Issue not reproducible during KI retests. (First week)

**Comment by marcaaron** [comment] 2024-05-15 21:33
Interesting. Did we fix it somehow? I'm leaning more towards closing and reopening if we can reproduce it soon.

**Closed by marcaaron** 2024-05-15 21:33 UTC
Labels: Weekly, Internal, Overdue, Bug, Hot Pick
