### ISSUE TITLE
When blurring the emoji picker search field, it wobbles if it is not empty

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26436] opened 2023-08-31 21:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report
2. Open the reaction menu on a message
3. Write something in the emoji search field
4. Blur the search field by clicking elsewhere

## Expected Result:
The emoji search field should behave like other input fields - it should not wobbl

## Actual Result:
The emoji search field wobbles

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.60-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ecd379dc-8939-4337-b69c-6f6b4128bd7b

https://github.com/Expensify/App/assets/115492554/d1fe74b0-1970-4a37-8e67-9a9c193b653e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @joh42

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692728174404989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-08-31 21:27
Proposal from @joh42
# Proposal

### Please re-state the problem that we are trying to solve in this issue.

When blurring the emoji picker search field, it wobbles if it is not empty.

### What is the root cause of that problem?

The root cause of the issue is that the [BaseTextInput](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js) component checks the length of the `value` prop before animating the label:

https://github.com/Expensify/App/blob/44eb88a7b6643b6b75978927adc83715e6c06824/src/components/TextInput/BaseTextInput.js#L112-L117

But the [EmojiPickerMenu](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.js) does not pass any value prop:

https://github.com/Expensify/App/blob/44eb88a7b6643b6b75978927adc83715e6c06824/src/components/EmojiPicker/EmojiPickerMenu/index.js#L536-L549

This means that even if the text input is not empty, label deactivation will begin, leading to the buggy animation.

Previously, the value of the input was stored inside of the [BaseTextInput](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js) component, but there was a conscious decision made to remove that in [this PR](https://github.com/Expensify/App/pull/20186). Since then the `value` prop has been used to determine if the label should animate back or not.

### What changes do you think we should make in order to solve the problem?

There is already a ref, called `hasValueRef` inside the [BaseTextInput](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js) component that keeps track of whether or not the input has a value:

https://github.com/Expensify/App/blob/44eb88a7b6643b6b75978927adc83715e6c06824/src/components/TextInput/BaseTextInput.js#L184-L186

I suggest we check that ref as well in the `deactivateLabel` function's early return:

https://github.com/Expensify/App/blob/44eb88a7b6643b6b75978927adc83715e6c06824/src/components/TextInput/BaseTextInput.js#L112-L117

Which would look something like this:
```
if (props.forceActiveLabel || props.prefixCharacter || hasValueRef.current) {
    return;
}
```

If the input has a value, we do not want the deactivation animation of the label to start. We could likely remove the check of the length of the value prop entirely in that conditional, since checking `hasValueRef` accomplishes the same thing.

This approach makes the most sense IMO. I think hinging the animation logic on the length of a prop that isn't required is suboptimal when the [BaseTextInput](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js) component already stores whether or not the text input is empty.

### What alternative solutions did you explore? (Optional)

#### Alternative solution 1

Alternatively we could pass the `value` prop from the [EmojiPickerMenu](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.js) component to the [BaseTextInput](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js) component. I do not think this approach is the best one, as the [EmojiPickerMenu](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.js) currently does not actually store the search term. Rather, it is used right away to filter emojis:

https://github.com/Expensify/App/blob/44eb88a7b6643b6b75978927adc83715e6c06824/src/components/EmojiPicker/EmojiPickerMenu/index.js#L540

https://github.com/Expensify/App/blob/fc9378eef3691017366dbc98348f583d7f36b8ee/src/components/EmojiPicker/EmojiPickerMenu/index.js#L419-L420

As such we would have to start storing the search term in both the regular [EmojiPickerMenu](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.js) and the [native EmojiPickerMenu](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.native.js) just so that the [BaseTextInput](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js) label can animate correctly.

If we choose this approach, I think we should consider making the `value` prop required to make it clear that the [BaseTextInput](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js) component does not function 100% correctly without it.

#### Alternative solution 2

Another alternative would be to start storing the current input value in the [BaseTextInput](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js) component again. I do not really think this is worth considering, given that a [decision has been made](https://github.com/Expensify/App/pull/20186) to not store the current input value in the  [BaseTextInput](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js) component, but it is an option. It is also not really required, since we are only interested in whether or not the input is empty, not the actual value of the input.

**Comment by laurenreidexpensify** [comment] 2023-09-04 10:04
Closing for https://github.com/Expensify/App/pull/26399

**Closed by laurenreidexpensify** 2023-09-04 10:04 UTC
Labels: Daily, Overdue, Bug
