### ISSUE TITLE
[HOLD for payment 2023-06-28] [$1000] New member as Hidden shows while create new room in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20967] opened 2023-06-17 16:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. create a workspace
2. go to offline
3. click on + icon and choose new room option
4. fill details and click on new room button
5. go to room and click on header
6. go to Members
## Expected Result: 
should show only one member
## Actual Result: 
shows two member (one with Hidden name)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b6efe871-fced-4b0a-b33a-02bb2cec02b3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686909294977579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<img width="960" alt="a1" src="https://github.com/Expensify/App/assets/43996225/dc31dd8b-2ba6-45ad-8cd3-b9f656a3d3e9">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0bb944a66007f1c</li>
        <li>Upwork Job ID: 1670734312369778688</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-06-19 10:05
Great: not reproducible on Production, just on Staging (making this a deploy blocker)

**Comment by conorpendergrast** [comment] 2023-06-19 14:28
Ok, I wonder if this is going to be resolved via https://github.com/Expensify/App/issues/19007

@bondydaa @Beamanator what do you think?

**Comment by bondydaa** [comment] 2023-06-19 16:19
I think this issue though has 2 different pieces to it.

Since part of it is dealing with "offline" updates it's not solely a backend/api thing. 

Looks like the line linked in the proposal https://github.com/Expensify/App/blob/b997868d39d758edbbbc9eb799bf18fab471e2f4/src/libs/actions/Report.js#L1158 was changed last week https://github.com/Expensify/App/commit/92394a8ed93f591d5c89c12ffb17c6e04e879aae

I think it's in part b/c we are transitioning between the `PERSONAL_DETAILS` and `PERSONAL_DETAILS_LIST`. 

so maybe we need to support both `email` and `accountID` for now in the app until the back end is updated?

**Comment by luacmartins** [comment] 2023-06-19 22:45
Removing the blocker label since the [fix](https://github.com/Expensify/App/pull/21072) is merged and being CPed. Thanks for the help everyone!

**Comment by conorpendergrast** [comment] 2023-06-20 07:56
Thanks! Looking at this issue and [the PR](https://github.com/Expensify/App/pull/21072), it seems like we have: 
* bug reporter @gadhiyamanan 
* Fixed by: @fedirjh 
* C+ PR review: @aimane-chnaif 

I'll get people hired and paid on the usual timeline. Let me know if any of that is wrong, thanks!

**Comment by conorpendergrast** [comment] 2023-06-28 10:59
Going to hire these people https://github.com/Expensify/App/issues/20967#issuecomment-1598296734

**Comment by conorpendergrast** [comment] 2023-06-28 12:48
Looks like the urgency bonus applies here too, so I'll factor that in as well

**Comment by conorpendergrast** [comment] 2023-06-28 12:49
Offers sent 👍

**Comment by conorpendergrast** [comment] 2023-06-28 19:21
Paid:
bug reporter @gadhiyamanan
Fixed by: @fedirjh

Waiting for contract to be accepted:
C+ PR review: @aimane-chnaif

**Comment by conorpendergrast** [comment] 2023-06-29 12:00
Waiting for the contract to be accepted to pay @aimane-chnaif (with urgency bonus), and for [the C+ checklist](https://github.com/Expensify/App/issues/20967#issuecomment-1602992085)

**Comment by conorpendergrast** [comment] 2023-06-30 15:25
@aimane-chnaif FYI: I'm waiting to pay you! Please accept [this contract](https://www.upwork.com/nx/wm/offer/25265467) and complete the C+ checklist

**Closed** 2023-07-03 15:08 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
