### ISSUE TITLE
[$500] Web -  LHN Subtitle Changed to "Not Active" Instead of "Delete" After Deleting Assigned Tasks and Attachment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28015] opened 2023-09-22 13:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB and select "Assign Tasks"
2. Add a title and share it somewhere
3. Complete the tasks and reopen them, then delete them
4. Observe that the LHN subtitle is changed to "Deleted", which is correct
5. Add an attachment and observe that the subtitle changes to "Attachment", which is correct
6. Delete the attachment and observe that the LHN subtitle should change back to "Deleted", but instead it changes to "Not Active"

## Expected Result:
After deleting assigned tasks, adding an attachment, and then deleting the attachment, the LHN subtitle should change back to "Deleted"

## Actual Result:
 After following the above steps, the LHN subtitle changes to "Not Active" instead of "Deleted"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-09-20T045952.964.webm](https://github.com/Expensify/App/assets/93399543/f2edc8cc-ab71-4480-9691-b7523a6d00ee)

https://github.com/Expensify/App/assets/93399543/8b65c1fa-b76d-4c54-b694-dbec9d788455

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695210969594049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dcaedc710fed40e3</li>
        <li>Upwork Job ID: 1705218203708387328</li>
        <li>Last Price Increase: 2023-09-29</li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2023-09-22 16:29
Dupe of #26679. Different problem but same RCA. That will solve this problem too.

**Comment by mananjadhav** [comment] 2023-09-24 15:24
@isabelastisser @maddylewis We should put this on hold for 26679.

Thanks @rojiphil.

**Comment by isabelastisser** [comment] 2023-09-25 13:52
Thanks @rojiphil!

Hey @mananjadhav, will this issue be solved once [26679](https://github.com/Expensify/App/issues/26679) is fixed? If yes, should we close this one instead of putting it on Hold?

**Comment by isabelastisser** [comment] 2023-09-27 19:08
@mananjadhav please follow up on my comment above, thanks!

**Comment by mananjadhav** [comment] 2023-10-02 16:04
@isabelastisser Apologies I was OOO. Are you , @kbecciv, @rojiphil able to reproduce? I don't have the bandwidth to get to this soon. If still needs a C+ (which I don't think it needs), can you please reassign?

**Comment by kbecciv** [comment] 2023-10-03 14:18
Unable to reproduce on build 1.3.76.4

https://github.com/Expensify/App/assets/93399543/19513242-4cbf-4042-860d-d4eae639842f

**Comment by isabelastisser** [comment] 2023-10-03 16:49
Thanks @rojiphil and @kbecciv! Closing!

**Closed by isabelastisser** 2023-10-03 16:49 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by tewodrosGirmaA** [comment] 2023-10-03 21:32
@isabelastisser  am I eligible for payment?
