### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] mWeb - Chat - smaller file preview when opening PDF attachment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#42566] opened 2024-05-23 23:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.75-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4569525
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Upload a PDF attachment
4. Open the PDF attachment

## Expected Result:
Attachment preview should be of the usual height.

## Actual Result:
Preview of the opened attachment is much smaller in height in comparison to the other PDFs in conversation.
Issue is reproducible 8 out of 10 times.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/95d47d0a-406c-4681-a30f-61243fafe49e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011542ccd37628748a</li>
        <li>Upwork Job ID: 1800587084111022941</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 102885617</li>
<li>bernhardoj | Contributor | 102885619</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by kbecciv** [comment] 2024-05-23 23:47
@muttmuure FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment] 2024-05-23 23:48
We think that this bug might be related to #vip-vsb

**Comment by bernhardoj** [comment] 2024-05-24 05:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The PDF has a smaller height. This happens when we open the PDF while a keyboard is shown.

### What is the root cause of that problem?
The PDF container height is set based on the div height as can be seen in [this code](https://github.com/Expensify/react-fast-pdf/blob/1abc4ed9164aa668b7cbcb17a2393f6e8ddae338/src/PDFPreviewer.tsx#L233-L236).

It's set in a useLayoutEffect and only happens once. When a keyboard is shown, the whole page height is reduced and if the calculation is happening while the keyboard isn't fully closed yet, the height it will receive is the reduced height, thus the PDF has a smaller height.

### What changes do you think we should make in order to solve the problem?

Instead of getting the height once, we should get the height whenever the div height is updated. We can use ResizeObserver for that.
```
const resizeObserver = new ResizeObserver(() => {
    if (!containerRef.current) {
        return;
    }
    setContainerWidth(containerRef.current.clientWidth);
    setContainerHeight(containerRef.current.clientHeight);
});
resizeObserver.observe(containerRef.current);

return () => {
    resizeObserver.disconnect();
}
```

_We can optionally debounce it to optimize if we want._

**Comment by muttmuure** [comment] 2024-06-05 14:10
Catching up from OOO

**Comment by bernhardoj** [comment] 2024-06-14 03:58
I use this PDF but any PDF should work

[dummy.pdf](https://github.com/user-attachments/files/15831346/dummy.pdf)

**Comment by bernhardoj** [comment] 2024-06-18 04:42
Here you go

https://github.com/Expensify/App/assets/50919443/2c7b3943-5226-4f08-b1b2-d5a9f3f8f67b

**Comment by bernhardoj** [comment] 2024-06-21 03:10
@mkhutornyi yes.

**Comment by bernhardoj** [comment] 2024-06-26 15:35
The mWeb on my emulator feels laggy, I can't open a report. Will re-check it tomorrow!

**Comment by mountiny** [comment] 2024-06-27 22:00
Have you been able to resolve these issues?

**Comment by bernhardoj** [comment] 2024-06-28 03:39
Thanks to this [comment](https://expensify.slack.com/archives/C01GTK53T8Q/p1719497873778469), I can resolve it by disabling the strict mode.

**Comment by bernhardoj** [comment] 2024-06-28 04:19
The react-fast-pdf PR is [here](https://github.com/Expensify/react-fast-pdf/pull/30)

**Comment by mountiny** [comment] 2024-07-03 22:23
@bernhardoj @mkhutornyi on https://github.com/Expensify/react-fast-pdf/pull/30 lint is failing

**Comment by bernhardoj** [comment] 2024-07-05 04:55
App PR is ready

cc: @mkhutornyi

**Comment by mountiny** [comment] 2024-07-29 20:27
I believe this is ready to be paid $250 to @bernhardoj and to @mkhutornyi

**Comment by bernhardoj** [comment] 2024-07-30 02:08
I've requested in ND.

**Comment by JmillsExpensify** [comment] 2024-07-30 17:00
$250 approved for @bernhardoj

**Comment by mountiny** [comment] 2024-08-08 23:45
$250 to @mkhutornyi still pending and we can close this I think

**Comment by mountiny** [comment] 2024-08-14 20:48
Matt is ooo so going to ask someone else for help paying out the $250 to @mkhutornyi, @bernhardoj has already been handled.

@greg-schroeder can you please help? Thanks!

**Comment by greg-schroeder** [comment] 2024-08-15 14:46
Yeah sure, doing

**Comment by greg-schroeder** [comment] 2024-08-15 15:07
@mkhutornyi paid via Upwork

**Closed** 2024-08-15 15:07 UTC
Labels: External, Daily, Awaiting Payment, Bug
