### ISSUE TITLE
[HOLD for payment 2023-09-21] [$500] Request Money/Scan: Validation messages are not translated to Spanish

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25865] opened 2023-08-24 15:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click plus button, choose Request Money.
2. Click scan tab, drag an invalid file to the scan tab (too big > 25MB or too small < 240KB), a validation modal will show.
3. Open a new tab, change the current language to Spanish.
4. Notice that validation messages are not translated to Spanish.

## Expected Result:
Validation messages should be translated to Spanish

## Actual Result:
Validation messages are not translated to Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/3cd692cd-2c3d-4701-82dc-6b26d4d0681e

https://github.com/Expensify/App/assets/115492554/01010763-a69f-4bcd-83f4-0c2cccb0ec30

**Expensify/Expensify Issue URL:**

**Issue reported by:** @hungvu193

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691900667713019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fbfb6ee98fe603c3</li>
        <li>Upwork Job ID: 1696537225664692224</li>
        <li>Last Price Increase: 2023-09-01</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26568326</li>
<li>hungvu193 | Contributor | 26568328</li>
<li>hungvu193 | Reporter | 26568330</li>
</ul></li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-08-29 14:55
Similar to https://github.com/Expensify/App/issues/25704#issuecomment-1696384768, seeing as this is low-priority and not necessarily an upgrade to the app's functionality, I am reducing the payscale for this issue to the following: 

- **Bug reporting bonus: $50
- Contributor fix: $250
- C+ proposal/PR review: $250**

Just noting this before I add the labels to accept proposals.

**Comment by stephanieelliott** [comment] 2023-08-29 14:59
Hey @AnshuAgarwal24 @himanshuragi456 this is not a "dibs" situation, if you would like to work on this issue please post a proposal per [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md)

**Comment by stephanieelliott** [comment] 2023-09-01 20:11
Updating price to match https://github.com/Expensify/App/issues/25704#issuecomment-1698009062. Moving to Weekly since this is low priority.

**Comment by sourcecodedeveloper** [comment] 2023-09-05 22:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Under Request Money -> scan tab, Attachment modal is not translating messages to spanish when the language is switched from english.
### What is the root cause of that problem?

The root cause is that validateReceipt function is storing the localized version of the validation message in onyx db. When switching from
spanish to english, the actual validation message is still in english and not spanish and therefore the validation message 
shown is in english. 

```
function validateReceipt(file) {
    const {fileExtension} = FileUtils.splitExtensionFromFileName(lodashGet(file, 'name', ''));
    if (_.contains(CONST.API_ATTACHMENT_VALIDATIONS.UNALLOWED_EXTENSIONS, fileExtension.toLowerCase())) {
        Receipt.setUploadReceiptError(true, Localize.translateLocal('attachmentPicker.wrongFileType'), Localize.translateLocal('attachmentPicker.notAllowedExtension'));
        return false;
    }

    if (lodashGet(file, 'size', 0) > CONST.API_ATTACHMENT_VALIDATIONS.MAX_SIZE) {
        Receipt.setUploadReceiptError(true, Localize.translateLocal('attachmentPicker.attachmentTooLarge'), Localize.translateLocal('attachmentPicker.sizeExceeded'));
        return false;
    }

    if (lodashGet(file, 'size', 0) < CONST.API_ATTACHMENT_VALIDATIONS.MIN_SIZE) {
        Receipt.setUploadReceiptError(true, Localize.translateLocal('attachmentPicker.attachmentTooSmall'), Localize.translateLocal('attachmentPicker.sizeNotMet'));
        return false;
    }

    return true;
}

```
### What changes do you think we should make in order to solve the problem?
The validateReceipt function can be refactored so it is only storing the validation message key rather than the actual message.

`Receipt.setUploadReceiptError(true, 'attachmentPicker.attachmentTooLarge', 'attachmentPicker.sizeExceeded');
`
Then in ReceiptSelector function where the validation message is loaded, get the key from onyx db and then fetch the localized version
of the validation message.
 
```
let attachmentInvalidReasonTitle = lodashGet(props.receiptModal, 'attachmentInvalidReasonTitle', '');
attachmentInvalidReasonTitle = attachmentInvalidReasonTitle === '' ? '' : Localize.translateLocal(attachmentInvalidReasonTitle);

```
video attached

### What alternative solutions did you explore? (Optional)

[bug_solution.webm](https://github.com/Expensify/App/assets/141340971/d9a45423-341e-4f45-91fb-e2f5c00b5d94)

**Comment by sourcecodedeveloper** [comment] 2023-09-05 23:16
@aimane-chnaif @stephanieelliott please review [proposal](https://github.com/Expensify/App/issues/25865#issuecomment-1707414385)

**Comment by sourcecodedeveloper** [comment] 2023-09-08 12:40
> @hungvu193's [proposal](https://github.com/Expensify/App/issues/25865#issuecomment-1691958421) looks good to me. @sourcecodedeveloper your proposal is same as @hungvu193's. @hungvu193 please comment here to be assigned. 🎀 👀 🎀 C+ reviewed

@aimane-chnaif it is not the same as @hungvu193. I have mentioned where the validation messages are being stored in  onyx db, there is no mention of  onyx db in @hungvu193 proposal. 
@hungvu193 has suggested 
`We should use translateKey only, so we need to remove all the Localize.translateLocal from our validateReceipt function.`
 
The Localize.translateLocal does not have to be removed and the proposal is incorrect. The root problem is not using Localize.translateLocal or translate key as suggested in @hungvu193 proposal but that the validation messages are being stored in onyx db and not being localized. 
@aimane-chnaif please review carefully again as @hungvu193 proposal will cause regression and does not address the root cause.

**Comment by sakluger** [comment] 2023-09-14 17:44
Hey team, I was assigned [Android - IOU - Validation message not shown when file above 25mb for Smart Recipe was selected #27389](https://github.com/Expensify/App/issues/27389#top) which Applause created after testing this issue's [linked PR](https://github.com/Expensify/App/pull/27089). Basically, we're not showing any validation when scanning a receipt file over 25MB.

According to the PR description, the >25MB validation should have been included in the PR. Can anyone help explain why we still deployed that PR to staging and Prod even after QA found an issue?

**Comment by sakluger** [comment] 2023-09-18 07:38
I see, so we never had this validation on mobile, thanks for clarifying. I assume we want to prevent attachments >25mb on all platforms, even if we didn't implement it before.

**Comment by stitesExpensify** [comment] 2023-09-26 02:47
Are we all done here?

**Comment by stephanieelliott** [comment] 2023-09-29 05:22
OK, issued remaining payments to match the [updated the payment summary](https://github.com/Expensify/App/issues/25865#issuecomment-1730565861): 
 - $750 to @aimane-chnaif via Upwork 
 - $200 to @hungvu193 for remaining bounty payment (so $250 paid total)

**Closed by stephanieelliott** 2023-09-29 05:22 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by stephanieelliott** [comment] 2023-10-10 18:35
Sorry for leaving ya hanging on this, @hungvu193! 

OK so let's try this one more time: 
- Reporting bonus: $250 [already paid] 
- Contributor: $500 job + $250 bonus  - $500 already paid = **$250 till owed.** 

Does this make sense? LMK and I'll issue the remaining payment as a bonus in the existing job.

**Comment by stephanieelliott** [comment] 2023-10-25 21:34
Issued $250 bonus to you @hungvu193! We should be squared up now!
