### ISSUE TITLE
DEv: Web - When flagging  message: flag sidebar stuck on loading

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22794] opened 2023-07-13 11:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a chat you have with user B
2. Hover on a chat from user B
3. Click on the flag

## Expected Result:
Flag sidebar option opens

## Actual Result:
When flagging  message: flag sidebar stuck on loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.39-8
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/447154de-d022-44a7-bed6-ab31bfa9ad1c

**Expensify/Expensify Issue URL:**
**Issue reported by:** requested 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689154429821869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment] 2023-07-17 09:46
Looks like this only happens in dev (it works as expected in prod and staging). Adding engineering tag for reproduction - @pecanoro, can you reproduce?

**Comment by pecanoro** [comment] 2023-07-17 20:47
I can't reproduce either in any environment so I am going to close it

**Closed by pecanoro** 2023-07-17 20:47 UTC
Labels: Engineering, Daily, Needs Reproduction, Bug
