### ISSUE TITLE
[HOLD for payment 2023-12-04] [CRITICAL] Migrate the LHNOptionsList to Flashlist

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#30910] opened 2023-11-06 13:15 UTC
HOLD on https://github.com/Expensify/App/pull/30242

Part of https://github.com/Expensify/App/issues/28902

Let's migrate [LHNOptionsList](https://github.com/Expensify/App/blob/bce37385dbc60a4dcade3b357fd346ac683d5547/src/components/LHNOptionsList/LHNOptionsList.js#L76-L89) to use Flashlist component instead of FlatList

Callstack is working on the migration right now.

Lets use this issue for daily updates on this migration

**Comment by TMisiukiewicz** [comment] 2023-11-06 14:05
Hi, I'm Tomasz from Callstack, I'd like to work on that issue

**Comment by TMisiukiewicz** [comment] 2023-11-06 15:09
Waiting for #30242 to be reviewed and merged, once it's done I'll create a proper PR

**Comment by roryabraham** [comment] 2023-11-06 15:33
Ok, then let's put this one HOLD for that

**Comment by TMisiukiewicz** [comment] 2023-11-06 15:47
#30242 is merged now, we can remove hold status

**Comment by garrettmknight** [comment] 2023-11-06 21:02
Hold status removed.

**Comment by garrettmknight** [comment] 2023-11-10 19:24
Looks like @TMisiukiewicz was off for a few days - we'll get back to this on Monday.

**Comment by TMisiukiewicz** [comment] 2023-11-13 17:05
Still working on fixing the tests, [described details in a comment under a PR](https://github.com/Expensify/App/pull/31052#issuecomment-1808559578)

**Comment by TMisiukiewicz** [comment] 2023-11-21 15:12
Trying to figure out if the regression #31610 comes from this PR, but I can't reproduce it. The logic for displaying the skeleton remains the same, the only thing that changed were styles. Left the more detailed comment  [here](https://github.com/Expensify/App/issues/31610#issuecomment-1821107051)

**Comment by garrettmknight** [comment] 2023-12-04 19:22
@TMisiukiewicz Good to close?

**Comment by garrettmknight** [comment] 2023-12-07 11:35
Not overdue, confirming which issue to pay on.

**Comment by situchan** [comment] 2023-12-07 11:36
https://github.com/Expensify/App/issues/31610 is for https://github.com/Expensify/App/pull/31642 (I was PR author)
https://github.com/Expensify/App/issues/30910 is for https://github.com/Expensify/App/pull/31711 (I was PR reviewer)

**Comment by garrettmknight** [comment] 2023-12-07 11:52
And paid! Closing

**Closed by garrettmknight** 2023-12-07 11:52 UTC
Labels: Daily, Awaiting Payment, Bug
