### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500] Split - "Enter a merchant name" error message appears while scanning is in process

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34916] opened 2024-01-22 19:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4211017
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have created a workspace and invited a member as employee
1. As the employee, go to the Workspace chat
2. Tap on the "+" button and select "Split bill"
3. On "Scan" option, upload any image and create the Split
4. On the Workspace chat, tap on the split preview while it is still scanning
5. Scroll down to "Merchant" field

## Expected Result:
Error message for missing merchant should not appear while the scanning is in process

## Actual Result:
Error message for missing merchant appears while scanning is in process

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dea203c4-61c9-42ce-9cd6-55a2f0f8af2a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e28b0f9e8a41bb6e</li>
        <li>Upwork Job ID: 1749515793504890880</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28146340</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-22 19:35
We think that this bug might be related to [#vip-split-p2p-chat-groups](https://expensify.enterprise.slack.com/archives/C05RECHFBEW)

**Comment by jeremy-croff** [comment] 2024-01-23 04:14
I'm actually unable to reproduce.
Is it specific to some receipts?

**Comment by bernhardoj** [comment] 2024-01-23 04:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The merchant field shows an error on a split bill details page while the receipt is still scanning.

### What is the root cause of that problem?
Currently, we show the error if `shouldDisplayMerchantError` or `shouldDisplayFieldError` is true.
https://github.com/Expensify/App/blob/9c552abbc1b29f243493eaf3f5d8874ed6d9f3c8/src/components/MoneyRequestConfirmationList.js#L715

`shouldDisplayFieldError` will be false when the receipt is still scanning.
https://github.com/Expensify/App/blob/9c552abbc1b29f243493eaf3f5d8874ed6d9f3c8/src/components/MoneyRequestConfirmationList.js#L276-L281

But `shouldDisplayMerchantError` is always true because `isScanRequest` is always false.
https://github.com/Expensify/App/blob/9c552abbc1b29f243493eaf3f5d8874ed6d9f3c8/src/components/MoneyRequestConfirmationList.js#L285

The `shouldDisplayMerchantError` was added in https://github.com/Expensify/App/pull/32486. The condition was added in both `MoneyRequestConfirmationList` and `MoneyTemporaryForRefactorRequestConfirmationList` (with a different name). I'm pretty sure they just copied it from `MoneyTemporaryForRefactorRequestConfirmationList` to `MoneyRequetConfirmationList` without testing the existence of `isScanRequest` (it's not available on both pages).

The `isScanRequest` is added in https://github.com/Expensify/App/pull/29473 where it was added for the money request create page only, and not for the split bill details page intentionally.

The reason for the condition is to not show a merchant field if we are going to create a new scan request (just like other field, such as amount), but this condition is not applicable for the split bill details page (which still uses `MoneyRequestConfirmationList`). On `MoneyRequestConfirmationList`, we use this condition to decide whether to show an error or not which is not correct.

If we look at MoneyRequestView, we can see the condition to decide whether to show the merchant error or not.
https://github.com/Expensify/App/blob/9c552abbc1b29f243493eaf3f5d8874ed6d9f3c8/src/components/ReportActionItem/MoneyRequestView.js#L225
https://github.com/Expensify/App/blob/9c552abbc1b29f243493eaf3f5d8874ed6d9f3c8/src/components/ReportActionItem/MoneyRequestView.js#L317

And that's the one that we should follow.

### What changes do you think we should make in order to solve the problem?

We can update `shouldDisplayMerchantError` to:
```
const shouldDisplayMerchantError = props.isPolicyExpenseChat && shouldDisplayFieldError && isMerchantEmpty;
```

Then we can remove the `shouldDisplayFieldError` here
https://github.com/Expensify/App/blob/9c552abbc1b29f243493eaf3f5d8874ed6d9f3c8/src/components/MoneyRequestConfirmationList.js#L715

If we later migrate to `MoneyTemporaryForRefactorRequestConfirmationList`, then we need to pass `isEditingSplitBill` as false from `IOURequestStepConfirmation`

**Comment by situchan** [comment] 2024-01-24 20:32
Even BZ member not assigned here 🤔

I can take this as C+

**Comment by anmurali** [comment] 2024-02-06 16:38
I will rotate the external label and see if that kicks off the Upwork process. I will assign you @situchan

**Comment by situchan** [comment] 2024-02-09 18:51
proposals are in review

**Comment by situchan** [comment] 2024-02-12 15:16
Based on https://github.com/Expensify/App/issues/29107#issuecomment-1924216766, `MoneyRequestConfirmationList` deprecation is held on other remaining migrations. So not sure if we should wait for this.
@anmurali based on how this bug impacts users, we can hold or continue.

**Comment by anmurali** [comment] 2024-02-16 15:31
I think we should continue @situchan

**Comment by anmurali** [comment] 2024-02-16 15:32
I am rotating the label since I am OOO till 29th but will take it back when I return.

**Comment by johncschuster** [comment] 2024-02-21 00:28
@situchan I'm catching up on this now. Do any of the available proposals fit here?

**Comment by situchan** [comment] 2024-02-23 20:40
still validating. I will provide update on Monday

**Comment by johncschuster** [comment] 2024-02-26 22:11
@situchan how's it going? Are you still able to provide an update today?

**Comment by situchan** [comment] 2024-02-27 12:52
Is `Merchant` field required when edit split bill? I don't think so as it's optional when create split bill.

**Comment by situchan** [comment] 2024-02-27 12:56
I'd like to approve proposal depending on https://github.com/Expensify/App/issues/34916#issuecomment-1966481671
🎀 👀 🎀

**Comment by bernhardoj** [comment] 2024-02-28 05:46
PR is ready

cc: @situchan

**Comment by anmurali** [comment] 2024-03-13 14:13
@bernhardoj and @situchan are paid.

@situchan can you complete the BZ checklist?

**Comment by anmurali** [comment] 2024-03-18 23:44
@situchan - this is waiting on you to complete the checklist. Can you please handle?

**Comment by situchan** [comment] 2024-03-19 04:40
yes, I was looking for culprit PR but not found. The issue existed for a while.

We already have regression test here:
https://expensify.testrail.io/index.php?/tests/view/4211017

**Comment by srikarparsi** [comment] 2024-03-26 23:49
Cool, in that case do you want to check off the boxes @situchan or is there something pending before payment?

**Comment by srikarparsi** [comment] 2024-04-02 02:47
@situchan, do you think you can complete the checklist whenever you get a chance?

**Comment by anmurali** [comment] 2024-04-09 16:33
@situchan - bump on the checklist.

**Comment by anmurali** [comment] 2024-04-17 01:57
Since the regression test exists [here](https://expensify.testrail.io/index.php?/tests/view/4211017), and everyone's been paid, I will close this issue

**Closed by anmurali** 2024-04-17 01:57 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
