### ISSUE TITLE
[$500] Chat - Flag emoji appears broken after adding a dash emoji next to it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26879] opened 2023-09-06 14:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app
2. Go to composer
3. Add any flag emoji via the emoji picker
4. Add a second emoji via the emoji picker

## Expected Result:
The emojis are not broken

## Actual Result:
The flag emoji is broken

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/43e3862d-0c89-40cb-9c49-7ff6eeac6941

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148516b71f9640bc4</li>
        <li>Upwork Job ID: 1706590721181237248</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-09-06 14:58
Same, this is working fine for me! 

https://github.com/Expensify/App/assets/54866469/ec167c83-1ce1-4be6-a66d-7d0911cce976

**Comment by joekaufmanexpensify** [comment] 2023-09-06 14:58
Closing as this isn't reproducible!

**Comment by kavimuru** [comment] 2023-09-22 14:51
Issue is still reproducible by the tester from applause and By contributor @dhanashree-sawant. https://expensify.slack.com/archives/C049HHMV9SM/p1695035857569269

Reopening the issue

**Comment by dhanashree-sawant** [comment] 2023-09-22 15:42
Key to reproduction is there shouldn't be space after flag emoji

**Comment by joekaufmanexpensify** [comment] 2023-09-25 02:50
Going to re-triage today.

**Comment by joekaufmanexpensify** [comment] 2023-09-25 10:24
I still can't reproduce this on my end using a Pixel 6, and when making sure to delete any space between the two emojis: 


https://github.com/Expensify/App/assets/54866469/9cf7a635-8889-4960-8642-1ceab8075271

**Comment by joekaufmanexpensify** [comment] 2023-09-26 08:44
Discussed [here](https://expensify.slack.com/archives/C049HHMV9SM/p1695717751933289?thread_ts=1695035857.569269&cid=C049HHMV9SM), and narrowed down that this only happens if you select the flag emoji and another one via the emoji picker. If you select the emojis with colons, then this doesn't occur. I can reproduce this via the emoji picker!

**Comment by joekaufmanexpensify** [comment] 2023-09-27 06:34
@Krishna2323 ah, is this just a duplicate of that issue?

**Comment by joekaufmanexpensify** [comment] 2023-09-27 06:36
Got it. If this is dupe of that issue, then IMO we'd just close this one. I don't think we need to leave it open personally.

**Comment by joekaufmanexpensify** [comment] 2023-09-27 06:57
Cool cool, closing as this is being fixed in the above linked issue!

**Closed by joekaufmanexpensify** 2023-09-27 06:57 UTC
Labels: External, Daily, Help Wanted, Bug
