### ISSUE TITLE
[$250] The input doesn't scroll back to bottom after adding an emoji to last line in expanded state - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10350] opened 2022-08-11 17:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open :expensify: at mobile browser
2. Go to any chat
3. Paste the text given in the thread)
4. Tap on expand button (top left at composer)
5. Go to the last line and add an emoji

## Expected Result:
User should be seeing the last line where he added the emoji

## Actual Result:
After adding the emoji you will see the text at middle

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.85-8
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/184205473-b958b783-f1b7-43f2-b3fa-8ce2538eba9b.mov

**Upwork job URL:** https://www.upwork.com/jobs/~0106d661f53cf28d49
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658154907835679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2022-08-24 15:36
Putting this on a monthly since it's pretty minor - only seems to happen if the text input is expanded beyond the visible text

**Comment by mvtglobally** [comment] 2022-08-30 15:24
Issue not reproducible during KI retests. (First week)

**Comment by michaelhaxhiu** [comment] 2022-09-02 15:12
Sweet, maybe we close this job down since it's not reproducible.

**Comment by michaelhaxhiu** [comment] 2022-09-02 15:12
@mvtglobally let's test again next week and then make a call :)

**Comment by mvtglobally** [comment] 2022-09-06 03:39
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2022-09-13 04:32
Issue not reproducible during KI retests. (Third week) @michaelhaxhiu  Ok to close?

**Comment by thienlnam** [comment] 2022-09-19 18:31
Yeah this is good to close

**Closed by thienlnam** 2022-09-19 18:31 UTC
Labels: Exported, External, Engineering, Monthly, Help Wanted
