### ISSUE TITLE
[$500] mentioning a user in a thread displays a system message "Heads up, <person> isn't a member of this room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35278] opened 2024-01-27 06:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @justinpersaud 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706210054373999

## Action Performed:
1. Create a room with few members
2. Send a message in the room
3. Reply in thread mentioning a user in the room

## Expected Result:
Should there be no message mentioning the person is not a member of this room
## Actual Result:

mentioning a user in a thread displays a system message "Heads up, <person> isn't a member of this room" even though they're in the room.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Snip - (6) New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/43996225/dd9a9bd6-6a86-4070-90a3-b4ea0bfe5bfe)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01772d0d0d506ebfc0</li>
        <li>Upwork Job ID: 1751136469650223104</li>
        <li>Last Price Increase: 2024-01-27</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2024-01-29 11:15
@c3024 do you agree this should be internal?

**Comment by c3024** [comment] 2024-01-29 12:44
@kavimuru 

Not able to reproduce the bug.

Uploading Screen Recording 2024-01-29 at 6.13.06 PM.mov…

Could you post a video showing instructions step by step?

**Comment by blimpich** [comment] 2024-01-31 00:53
This will need to be an internal issue because we send these messages from the backend.

**Comment by blimpich** [comment] 2024-02-02 17:57
This could probably be brought under #vip-vsb

**Comment by laurenreidexpensify** [comment] 2024-02-09 11:26
@blimpich will this be solved by https://github.com/Expensify/Web-Expensify/pull/40775?

**Comment by blimpich** [comment] 2024-02-09 17:08
Nope, that won't fix it 😔. I'll add this to vip-vsb and hopefully someone will pick it up eventually. I unfortunately can't right now.

**Comment by laurenreidexpensify** [comment] 2024-02-13 12:07
Still waiting for internal eng to pick up

**Comment by laurenreidexpensify** [comment] 2024-02-16 18:33
Will try find a taker next week

**Comment by laurenreidexpensify** [comment] 2024-02-19 17:45
Will add this to the whatsnext threads tomorrow (Tues)

**Comment by laurenreidexpensify** [comment] 2024-02-21 15:17
Resync hasn't been posted yet, will pop in thread later or tomorrow

**Comment by laurenreidexpensify** [comment] 2024-02-22 12:24
asked here https://expensify.slack.com/archives/CC7NECV4L/p1708604649349309?thread_ts=1708548663.630439&cid=CC7NECV4L to see if someone can pick up

**Comment by quinthar** [comment] 2024-02-25 09:03
Can you reproduce this?  I can't.


![Image](https://github.com/Expensify/App/assets/575186/da196337-e720-46bd-8430-fbcc45a14742)

**Comment by blimpich** [comment] 2024-02-26 17:42
I can reproduce this on staging, so still an issue

https://github.com/Expensify/App/assets/17171674/dd25fe45-e92d-44a0-b7c3-6e88478a6415

**Comment by laurenreidexpensify** [comment] 2024-02-27 06:19
Still waiting for internal eng to pick up

**Comment by laurenreidexpensify** [comment] 2024-03-04 05:32
Still waiting for a volunteer to pick up

**Comment by laurenreidexpensify** [comment] 2024-03-21 16:36
Going to leave this on the low list for a few more weeks

**Comment by mvtglobally** [comment] 2024-03-28 04:19
Issue not reproducible during KI retests. (First week)

**Closed** 2024-04-02 11:56 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug, Hot Pick
