### ISSUE TITLE
Xero - The connection isn't syncing when enabling tax import

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48090] opened 2024-08-27 14:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/47905
## Action Performed:
1. Open the app
2. Log in with a new Gmail account and validate it
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to Xero and enable 2FA when asked
7. Navigate to Import - Taxes
8. Enable "Import"

## Expected Result:
The connection should auto sync to enable "Taxes" in the workspace settings

## Actual Result:
The connection isn't syncing when enabling tax import. I have to sync it manually

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4cbd8850-d05a-4d5b-b739-d48d7c941091

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-27 14:14
We think that this bug might be related to#wave-collect - Release 2

**Comment by hungvu193** [comment] 2024-08-28 02:38
The api was called successfully, can you take a look at the BE @dangrous ? 😄

**Comment by dangrous** [comment] 2024-08-28 13:55
ha yeah I had this up in a tab but hadn't reviewed yet. It's definitely not because of your PR, @hungvu193 since it's on production as well. I took a very brief look yesterday and didn't see anything different between the tax import setting and the other ones? I'll see if I can do so today

**Comment by dangrous** [comment] 2024-08-28 17:46
oh we do have special handling for tax import. I thinkkkk I know how to fix this on the backend. Stay tuned!

**Comment by dangrous** [comment] 2024-08-28 18:31
oh wait. In testing, I think this is happening for ALL integrations and all settings. Is that correct @lanitochka17? I just tested a couple QBO settings as well as a few Xero ones.

If so, it's a different issue. Maybe @aldo-expensify can let us know since you worked on the first connection syncing stuff - is this expected behavior? It seems like the sync eventually happens, and we have optimistic data beforehand, so maybe it's fine?

**Comment by aldo-expensify** [comment] 2024-08-29 13:54
It may be because of this: https://github.com/Expensify/Web-Expensify/pull/43173, I added a debounce of 1 min for syncing when you modify a setting. If the person doing the test would have waited longer, they would have seen it syncing,... but I can see how this can be confusing for the user.

I'm not sure what to do, some ideas:

- When we modify a setting, we could optimistically show like the sync is happening, even if the backend will really start syncing one minute later.
- We could decrease the 1 minute debounce to something shorter... 30s, 20s...

both? other?

**Comment by CortneyOfstad** [comment] 2024-08-29 20:22
Thanks @aldo-expensify! Maybe both? Interested to hear what @dangrous thinks!

**Comment by dangrous** [comment] 2024-08-29 21:09
Hm interesting. So let's try 30s to start...

As for pretending it's loading? I'm not sure - I almost feel like users would be more annoyed with "hey it seems like this sync is taking a long time" vs. "oh it just hasn't synced yet" but I don't know. @CortneyOfstad do you think it's worth bringing up in Slack somewhere to see what we think?

**Comment by aldo-expensify** [comment] 2024-08-30 16:27
> "oh it just hasn't synced yet"

I feel like this is more confusing / annoying than `"hey it seems like this sync is taking a long time"`

>  @CortneyOfstad do you think it's worth bringing up in Slack somewhere to see what we think?

That sounds like a good idea to get more consensus. Or maybe we can ask a designer?

**Comment by dangrous** [comment] 2024-08-30 17:59
yeah let's bring it up in.... #product? @CortneyOfstad do you have time to tackle that?

**Comment by CortneyOfstad** [comment] 2024-09-04 20:31
So I'm reviewing this with fresh eyes, and I think part of the problem is we don't import tax for US-based entities in integrations. The tester used the US Xero company details, so we don't import those in, which is why the sync wasn't triggered. 

However, I think we need to display **something** when this happens. In classic, we don't even let them select the option (either it isn't there, or it is grayed out). I wonder if we need to do the same thing here.

**Comment by CortneyOfstad** [comment] 2024-09-10 17:33
@dangrous @aldo-expensify interested to hear your thoughts on the above ^^^

**Comment by aldo-expensify** [comment] 2024-09-10 19:47
> So I'm reviewing this with fresh eyes, and I think part of the problem is we don't import tax for US-based entities in integrations. The tester used the US Xero company details, so we don't import those in, which is why the sync wasn't triggered.

I tried to verify this with the account `applausetester+xero@applause.expensifail.com` the tester used, but seems like the password stored is wrong 🤷 

> However, I think we need to display something when this happens. In classic, we don't even let them select the option (either it isn't there, or it is grayed out). I wonder if we need to do the same thing here.

This sounds like something we may need to improve.

@lanitochka17 can you retry what the tester did, but now giving it at least a minute after changing the "Import tax' setting to see if the sync starts later or it never does? 🙏  Where can I get the right password for `applausetester+xero@applause.expensifail.com`?

**Comment by trjExpensify** [comment] 2024-09-11 00:48
Seems like a regression if `Taxes` is available for import on a connection to a US-based entity, as we weren't showing the option at all when initially built. 

>@lanitochka17 can you retry what the tester did, but now giving it at least a minute after changing the "Import tax' setting to see if the sync starts later or it never does? 🙏 Where can I get t

@CortneyOfstad might be worth escalating this to #qa for faster resolution. 👍

**Comment by CortneyOfstad** [comment] 2024-09-11 18:19
Poste in` #QA` [here](https://expensify.enterprise.slack.com/archives/C9YU7BX5M/p1726078753867429)

**Comment by kavimuru** [comment] 2024-09-12 00:46
It only syncs if 

Uploading bandicam 2024-09-11 21-53-02-883.mp4…

 waiting a minute after enabling the setting.

**Comment by aldo-expensify** [comment] 2024-09-12 01:03
Thanks @kavimuru , then in this case the problem is because of the 1 minute delay of the sync job after any setting is changed. I think we should just decide if we prefer:

a. Shortening the time to sync to 30s (or less), and / or
b. Optimistically show like we are syncing as soon as a setting is changed, even if the real syncing starts later

I'm still on the side of doing both or just `.b`, and I find `.a` insufficient by itself.

**Comment by dangrous** [comment] 2024-09-12 16:15
I think I've changed my mind and would vote for "do both" as well, so there's immediate feedback for the user. 30s seems like a good limit.

My only remaining concern - would users think they can't continue to make changes while the syncing is happening? I feel like it would be fine, but just wanted to bring it up.

**Comment by aldo-expensify** [comment] 2024-09-12 16:31
> would users think they can't continue to make changes while the syncing is happening?

🤷 , but this is a concern that also applies now.

**Comment by dangrous** [comment] 2024-09-12 19:54
haha fair. Okay maybe we move forward with both those solutions then. Do you have time to tackle the PRs? Sounds like one BE and one FE, right?

**Comment by aldo-expensify** [comment] 2024-09-12 22:10
Yes, I can work on it.

**Comment by trjExpensify** [comment] 2024-09-13 14:18
Dang, [this seems like](https://github.com/Expensify/App/issues/48090#issuecomment-2317731872) a step back in the UX. Waiting a minute or even 30s for the sync to start is confusing and makes it seem super slow - because it will be shown as syncing for a much longer time than necessary. The lack of feedback as well. 

Did we discuss this anywhere in Slack? I'd be curious for the input of @Expensify/design @JmillsExpensify. Like, maybe there's a better way that can allow it to start right away, but while the sync is in progress not let you change the same value again until it's done.

Just looking at what we were trying to solve for in the [parent issue](https://github.com/Expensify/App/issues/45201) of [the PR](https://github.com/Expensify/App/issues/45201) that introduced this 1m delay.

**Comment by dannymcclain** [comment] 2024-09-13 15:49
Hmm yeah, I agree with Tom. This doesn't really seem ideal.

>Like, maybe there's a better way that can allow it to start right away, but while the sync is in progress not let you change the same value again until it's done.

Would it be possible to just use something similar to offline pattern? Where if you change a setting it becomes reduced opacity and not-interact-with-able until the sync finishes?

**Comment by trjExpensify** [comment] 2024-09-13 15:58
Yeah, I guess it is "pending update" in that regard.

**Comment by aldo-expensify** [comment] 2024-09-13 17:16
It is not the input that you just changed that would need to be locked, you would need to lock all settings.

**Comment by CortneyOfstad** [comment] 2024-09-17 17:33
> you would need to lock all settings (any setting that triggers a sync)

Is that something we can do @aldo-expensify?

**Comment by aldo-expensify** [comment] 2024-09-17 17:53
>> you would need to lock all settings (any setting that triggers a sync)

> Is that something we can do @aldo-expensify?

I think so, but when would we block it and for how long?

If we do this only when the user is offline, then the user can at most change only one setting offline and then will be blocked, this UX is worse IMO. Also, we come back to having the problem of creating multiple IS jobs that push many policy updates that may arrive in the wrong order when changing settings while being online.

If we do the locking when online and offline, for online we would have to introduce an artificial amount of time to lock the settings to give time to the IS job to finish... this also sound like a worse UX to me.

I think we could do a better solution if there was a way to know if the IS job is running or not. If this is not possible for the moment, then we could try to implement something for knowing that? If we can know if the IS job is running, we could do this in the backend:

- If IS is not running, then immediately queue a new IS job to sync
- If IS is running, then create the bedrock job we are creating now that will queue the IS job in the future (when it is not running)

**Comment by aldo-expensify** [comment] 2024-09-17 17:54
Actually, I think when we create the IS job from the bedrock job, we could wait for it to finish instead of fire and forget. Maybe that could help with "knowing" that the IS job is running because the bedrock job would also be "running" until the IS job finishes.

**Comment by aldo-expensify** [comment] 2024-09-17 20:28
I think something like this will work: https://github.com/Expensify/Web-Expensify/pull/43574

- The sync should start immediately like it used to
- Config changes while the sync is running should be held until the sync finishes (two syncs should not happen at the same time).

**Comment by dangrous** [comment] 2024-09-17 22:23
I think that could work!

**Comment by aldo-expensify** [comment] 2024-09-18 01:45
Made PR ready for review: https://github.com/Expensify/Web-Expensify/pull/43574

**Comment by trjExpensify** [comment] 2024-09-18 13:37
Thanks, Aldo!

**Comment by dangrous** [comment] 2024-09-18 19:24
So I have https://github.com/Expensify/Web-Expensify/pull/43483/files up for the backend - if there is a reimburser explicitly set for the policy, it will use their info, if not it will just say "an admin". I'll put up a front end PR momentarily (it's quick so doesn't need a contributor really)

**Comment by CortneyOfstad** [comment] 2024-09-23 15:20
PR — https://github.com/Expensify/Web-Expensify/pull/43574 — is on staging, so will keep an eye until it is released to production 👍

**Comment by trjExpensify** [comment] 2024-09-30 17:53
That's on prod now.

**Comment by aldo-expensify** [comment] 2024-10-02 18:08
I'll try to reproduce this, I'm expecting this to be fixed now.

**Comment by aldo-expensify** [comment] 2024-10-02 18:12
Same problem as https://github.com/Expensify/App/issues/48090#issuecomment-2341885599, the password stored in 1Password doesn't work. I'll ask in `#QA` for a retest from applause.

**Comment by aldo-expensify** [comment] 2024-10-02 18:16
> Same problem as [#48090 (comment)](https://github.com/Expensify/App/issues/48090#issuecomment-2341885599), the password stored in 1Password doesn't work. I'll ask in `#QA` for a retest from applause.

Oh, there is a second entry for xero / applausetester+xero@applause.expensifail.com in 1Password and that one worked.

This works now:


https://github.com/user-attachments/assets/b231bd22-d677-40e3-bc4d-16fb16ceaa33

**Closed by aldo-expensify** 2024-10-02 18:16 UTC
Labels: Reviewing, Daily, Internal, Bug
