### ISSUE TITLE
Emojis displayed are cut off in top in composer

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39274] opened 2024-03-29 18:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58.0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to any chat and add some text on the first like
2. Add a second like and type/add a hand emoji (e.g. :hand:)
## Expected Result:
The emojis do not overlap other lines of text

## Actual Result:
The hand emojis overlap the previous line in a multiline message

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [X] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/78a660ee-fe1e-456b-bd04-655be14c1cb4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-03-29 18:04
We think this bug might be related to #vip-vsb

**Comment by m-natarajan** [comment] 2024-03-29 18:04
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by thienlnam** [comment] 2024-03-29 18:35
Not a blocker - added to the main tracking issue, looks maybe related to https://github.com/Expensify/App/issues/39270

**Comment by BartoszGrajdek** [comment] 2024-04-02 10:25
Hi! I'm Bartosz from SWM / `react-native-live-markdown` team - I'll be taking a look into what's happening here later today! 👀

**Comment by adelekennedy** [comment] 2024-04-02 17:21
@thienlnam should we close this in favor of the other GH? It seems like a very small part of a larger problem

**Comment by thienlnam** [comment] 2024-04-03 02:04
Are you referencing the tracking issue? I think we should try to keep this open since these are all different fixes

**Comment by adelekennedy** [comment] 2024-04-03 04:43
Not the tracking issue - #39270

**Comment by thienlnam** [comment] 2024-04-03 15:56
Oh yeah, I am not entirely sure - they might be from different causes. @BartoszGrajdek will have a better idea once he starts investigating

**Comment by adelekennedy** [comment] 2024-04-08 15:35
any updates here @BartoszGrajdek?

**Comment by BartoszGrajdek** [comment] 2024-04-09 12:31
Working on it! 👀 Last week we prioritized critical-level issues 😅

**Comment by thienlnam** [comment] 2024-04-09 16:40
Going to update the priority for these lower level issues

**Comment by BartoszGrajdek** [comment] 2024-04-11 13:05
[This PR](https://github.com/Expensify/App/pull/39597) should fix this problem 👀

**Comment by thienlnam** [comment] 2024-04-16 19:41
This is resolved! I can no longer reproduce

**Closed by thienlnam** 2024-04-16 19:41 UTC
Labels: Engineering, Weekly, Bug
