### ISSUE TITLE
[$500] Clicking on "New Workspace" in WS list closes the RHP for a brief moment and then opens the new workspace settings

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29649] opened 2023-10-16 00:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697303051407209

## Action Performed:
1. Navigate for workspace list page.
2. Click on "New Workspace".
## Expected Result: 
New Workspace settings page opens without closing of RHP,
## Actual Result: 
Clicking on "New Workspace" in WS list closes the RHP for a brief moment and then opens the new workspace settings

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/98005a75-072b-4144-8271-78ef30ffeea1

 

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/11cd9163-dbf3-43cc-8a03-d7431dd7fa72

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/126f8811-ac1f-4664-bdf5-b78d911a5245

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/2a9ef133-ba06-477a-932e-e19f47d6cf84

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/1aebd26a-2721-441c-8f24-82e9b09a49de

 
https://github.com/Expensify/App/assets/38435837/4af46d10-c6b7-4598-8fbe-4ba899cfe422

</details>

https://github.com/Expensify/App/assets/38435837/c740c543-e71f-4de4-b358-7ae725dac1a0

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/5ff1fb42-1b09-450f-9738-91ed66aa6300

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f9d8b34b9a97b7b2</li>
        <li>Upwork Job ID: 1713715148645781504</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-10-16 07:28
FYI: https://github.com/Expensify/App/pull/28573#discussion_r1349059739

**Comment by strepanier03** [comment] 2023-10-20 20:11
@ArekChr - Friendly bump on the proposal and comments above.

**Comment by ArekChr** [comment] 2023-10-24 10:43
I attempted to reproduce the problem, but it appears to have been resolved in a different PR. The issue is no longer present.

**Comment by strepanier03** [comment] 2023-10-24 15:20
Thank you @ArekChr - I'm closing for now and if we need to reopen in the future we can.

**Closed by strepanier03** 2023-10-24 15:20 UTC
Labels: External, Daily, Help Wanted, Bug
