### ISSUE TITLE
[HOLD for payment 2023-08-02][$1000] Workspace chat displays 'send money' when there are no option to send the money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19828] opened 2023-05-30 16:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to dev on web chrome
2. Create a new workspace
3. Go to the newly created 'Workspace chat' that has square logo
4. Notice that on the message , it displays 'You can also use the + button below to send or request money!'
5. But now , click on + icon and notice that it doesn't have options for send money and has only request money and attachment

## Expected Result:
The message should not display 'Send Money' since there is no functionality to send money in the + icon

## Actual Result:
Workspace chat displays 'send money  even when there is no option to send the money on the + icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20.1

**Reproducible in staging?:** yes

**Reproducible in production?:**yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (46)](https://github.com/Expensify/App/assets/93399543/b6a7172f-9105-49cd-9d7c-e0bfaf0f95ae)

https://github.com/Expensify/App/assets/93399543/cca524a2-513d-442d-ab77-433fad023ab5

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zya

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685176461755199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1e5de861745b07c</li>
        <li>Upwork Job ID: 1673785766553649152</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-05-31 02:09
You shouldn't be able to `Send Money` on the workspace chat so I think this is as simple as a wording change and we're done here. @luacmartins What do you think about keeping this internal and me handling the wording change?

**Comment by luacmartins** [comment] 2023-06-05 15:37
@JmillsExpensify any updates here?

**Comment by JmillsExpensify** [comment] 2023-06-07 04:57
Sorry haha I commented and now need to actually get back to this in the coming days. Will circle back!

**Comment by JmillsExpensify** [comment] 2023-06-14 06:04
Chatted with Carlos about this earlier today. Going to circle back later this week.

**Comment by JmillsExpensify** [comment] 2023-06-21 05:16
Still haven't gotten to this, though it'll be a quick change. On my list!

**Comment by JmillsExpensify** [comment] 2023-06-26 21:01
Sorry, still very minor and something I'd like to get to now that we are deprecating Send in the front-end.

**Comment by JmillsExpensify** [comment] 2023-07-05 12:53
On my list and not a high priority.

**Comment by JmillsExpensify** [comment] 2023-07-12 13:16
I haven't gotten to this yet, and I just don't have time right now. I'll open up to the community.

**Comment by JmillsExpensify** [comment] 2023-07-12 16:00
Noting that we should still do this issue, especially in light of deprecating `send money` recently.

**Comment by ishpaul777** [comment] 2023-07-12 17:58
# Proposal
## Problem
Workspace chat displays 'send money' when there are no option to send the money

## Root cause
As send money is now depreciated the condition is still (here)[https://github.com/Expensify/App/blob/HEAD/src/components/ReportWelcomeText.js#L122C17-L124C19]. 
```
moneyRequestOptions.includes(CONST.IOU.MONEY_REQUEST_TYPE.SEND)
```
## Changes
remove the condition and change wording to exclude the word Send

**Comment by amyevans** [comment] 2023-07-13 15:15
Sorry I'm not up on the latest, @JmillsExpensify @luacmartins are we deprecating `Send money` across the board, or only for certain scenarios (e.g. sending money to a workspace)? Do we have an internal cleanup issue?

I see other instances of `CONST.IOU.MONEY_REQUEST_TYPE.SEND` and think we should ideally handle this more holistically.
![Screenshot 2023-07-13 at 11 15 23 AM](https://github.com/Expensify/App/assets/7277067/cca75792-2b24-4e88-928e-273ec1ec5409)

Regarding copy for the new text, would we want to highlight the `Assign task` option in place of `send money`? Maybe `You can also use the + button below to request money or assign a task!` Or should it just be `You can also use the + button below to request money!`

**Comment by luacmartins** [comment] 2023-07-13 15:48
I'm not sure what the plan is for Send money. @JmillsExpensify might be better suited to answer your question.

**Comment by ishpaul777** [comment] 2023-07-17 11:35
Bump @JmillsExpensify can you please confirm about the correct wording of text and when can I expect to be assigned to the issue

**Comment by JmillsExpensify** [comment] 2023-07-19 13:49
Send money is deprecated. I like Amy's suggestion here:

> You can also use the + button below to request money or assign a task!

**Comment by amyevans** [comment] 2023-07-19 20:38
Requested translation internally

**Comment by amyevans** [comment] 2023-07-19 20:41
Spanish translation is
> ¡También puedes usar el botón + de abajo para pedir dinero o asignar una tarea!

**Comment by ishpaul777** [comment] 2023-07-19 23:53
Applied!! PR will be ready to review within a few hours.

**Comment by ishpaul777** [comment] 2023-07-20 05:34
@thesahindia @amyevans Should I wait to hired on upwork before creating PR ?

**Comment by ishpaul777** [comment] 2023-07-20 09:56
@thesahindia  PR is up for review -
https://github.com/Expensify/App/pull/23248

**Comment by amyevans** [comment] 2023-07-28 20:14
Hmm it looks like the automation failed here and didn't update the GH. The PR was deployed to production 7/26 so is due for payment 8/2.

**Comment by JmillsExpensify** [comment] 2023-08-02 04:41
@amyevans Thanks for updating, I'll circle back on this tomorrow.

**Comment by ishpaul777** [comment] 2023-08-02 06:26
@JmillsExpensify @amyevans I am still not hired on upwork, is this automation failure

**Comment by rushatgabhane** [comment] 2023-08-02 13:15
manual request here - https://staging.new.expensify.com/r/3851271757956553

**Comment by ishpaul777** [comment] 2023-08-03 06:04
@JmillsExpensify bump for pay reminder.

**Comment by JmillsExpensify** [comment] 2023-08-04 04:27
Summarizing the payouts: 
 - Issue reporter: @priya-zya $250
 - Contributor: @ishpaul777 $1,500
 - Contributo+: @rushatgabhane $1,500

Upwork job is here: https://www.upwork.com/jobs/~01a1e5de861745b07c. Still waiting for contributor to apply and we'll get this paid out.

**Comment by JmillsExpensify** [comment] 2023-08-04 04:28
Reviewed details for @rushatgabhane. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by ishpaul777** [comment] 2023-08-04 04:36
@JmillsExpensify Applied to the job on upwork. Thanks!

**Comment by priya-zha** [comment] 2023-08-04 04:58
Applied. thanks.

**Comment by ishpaul777** [comment] 2023-08-07 05:01
@JmillsExpensify Bumping for reminder thanks!

**Comment by JmillsExpensify** [comment] 2023-08-08 01:58
Contracts sent. Any bonuses will be paid when issuing final payment.

**Comment by ishpaul777** [comment] 2023-08-08 02:17
Accepted offer

**Comment by JmillsExpensify** [comment] 2023-08-08 02:26
Paid out.

**Comment by JmillsExpensify** [comment] 2023-08-08 04:19
Everyone is approved and/or paid out and not regression tests applicable. I'm closing this one out.

**Closed by JmillsExpensify** 2023-08-08 04:19 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
