### ISSUE TITLE
[$500] Chat - Start chat opens not smoothly

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34141] opened 2024-01-09 14:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Click on + (FAB) in LHN
4. Click on Start chat

## Expected Result:
Start chat opens smoothly

## Actual Result:
Start chat opens not smoothly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f313a037-4f63-4e77-95eb-03553dc51c33

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017aeb95424fe5c1b2</li>
        <li>Upwork Job ID: 1744721747500904448</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2024-01-09 15:03
Hm, I'm on staging mac chrome and can't repro this - it's fast and smooth for me. @lanitochka17, confirming this is reproducible on both staging and production? Is it Windows only?

**Comment by samilabud** [comment] 2024-01-09 16:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Start chat opens not smoothly

### What is the root cause of that problem?
Every time we open the start chat navigation modal we are calling two times the getFilteredOptions from OptionsListUtils in:
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/pages/NewChatPage.js#L185
This makes the animation of the navigation modal make this strange behavior, more because when use set the personal details using `setFilteredPersonalDetails(newChatPersonalDetails)`.

### What changes do you think we should make in order to solve the problem?
We should use useMemo to store the value of that function and use it every time the start chat navigation modal is called/toggle in these two lines:
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/pages/NewChatPage.js#L133
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/pages/NewChatPage.js#L185

The useMemo code could be something like:
```
const filteredOptions = useMemo(
        () =>
            OptionsListUtils.getFilteredOptions(
                reports,
                personalDetails,
                betas,
                searchTerm,
                selectedOptions,
                isGroupChat ? excludedGroupEmails : [],
                false,
                true,
                false,
                {},
                [],
                false,
                {},
                [],
                true,
                true,
            ),
        [searchTerm],
    );
```

Result:
Before changes:

https://github.com/Expensify/App/assets/5216036/eea98119-f9c2-484d-9dd3-cc281bb016dc


After changes:


https://github.com/Expensify/App/assets/5216036/b310d10d-cfce-4415-a680-1475464e9078

**Comment by MelnykDmitro** [comment] 2024-01-09 16:29
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Chat - Start chat opens not smoothly
> 
> ### What is the root cause of that problem?
> Every time we open the start chat navigation modal we are calling two times the getFilteredOptions from OptionsListUtils in:
> 
> https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/pages/NewChatPage.js#L185
> 
> 
> This makes the animation of the navigation modal make this strange behavior, more because when use set the personal details using `setFilteredPersonalDetails(newChatPersonalDetails)`.
> ### What changes do you think we should make in order to solve the problem?
> We should use useMemo to store the value of that function and use it every time the start chat navigation modal is called/toggle in these two lines:
> 
> https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/pages/NewChatPage.js#L133
> 
> 
> https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/pages/NewChatPage.js#L185
> 
> The useMemo code could be something like:
> 
> ```
> const filteredOptions = useMemo(
>         () =>
>             OptionsListUtils.getFilteredOptions(
>                 reports,
>                 personalDetails,
>                 betas,
>                 searchTerm,
>                 selectedOptions,
>                 isGroupChat ? excludedGroupEmails : [],
>                 false,
>                 true,
>                 false,
>                 {},
>                 [],
>                 false,
>                 {},
>                 [],
>                 true,
>                 true,
>             ),
>         [searchTerm],
>     );
> ```
> 
> **Result:** **Before changes:**
> 
>  Before.changes.-.start.chat.not.smoothly1.mp4 
> 
> With rendering painting enabled (notice the component is rendered two times while open):
> 
>  Screen.Recording.2024-01-09.at.12.07.50.PM.mov 
> 
> **After changes:**
> 
>  After.changes.-.start.chat.not.smoothly.mp4 
> 
> With rendering painting enabled (notice the component open smoothly):
> 
>  Screen.Recording.2024-01-09.at.12.06.48.PM.mov

Good one, however it still doesn't fix the performance issue.

**Comment by MelnykDmitro** [comment] 2024-01-09 16:34
Contributor details
Your Expensify account email: melnyk.dmitro@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/dmytrom100

**Comment by MelnykDmitro** [comment] 2024-01-10 20:41
@lanitochka17 I've noticed this issue occurs only when the Developer Tools panel in Chrome is open. In my case, if I close it, the chat starts smoothly. Once it's opened, it consumes a lot of resources to render the DOM efficiently.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - Start chat opens not smoothly

### What is the root cause of that problem?

I have investigated the way animation is provided for the modal and have found it already uses the most efficient way to animate using `transform` style property. My presumption is that issue affected by opened dev panel and insufficient machine resources to render it smoothly.

### What changes do you think we should make in order to solve the problem?

We can use `will-change` property together with `transform` to hint to the browser that an element will be animated, which can optimize rendering. 

### What alternative solutions did you explore? (Optional)

1. Use smoother animations.
2. **Velocity.js** or **GreenSock Animation Platform (GSAP)** instead of regular animations provided by **React Navigation**.

**Comment by jjcoffee** [comment] 2024-01-11 09:03
I imagine this is related/a dupe of https://github.com/Expensify/App/issues/33459.

**Comment by MelnykDmitro** [comment] 2024-01-11 10:55
> I imagine this is related/a dupe of #33459.

My be caused by the same problem.

**Comment by jjcoffee** [comment] 2024-01-11 16:06
@trjExpensify Let's close this in favour of https://github.com/Expensify/App/issues/33459.

**Comment by trjExpensify** [comment] 2024-01-11 17:09
Works for me!

**Closed by trjExpensify** 2024-01-11 17:09 UTC
Labels: External, Daily, Help Wanted, Bug
