### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] Split - User is redirected to LHN instead of group chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32853] opened 2023-12-11 19:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Go offline
3. Tap + > Request money > Manual
4. Enter amount and select a few users to split bill with
5. Create the bill split

## Expected Result:
User is redirected to group chat

## Actual Result:
User is redirected to LHN instead of group chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/05ec916f-26a4-486d-bf96-487a6213807d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107713523a204644e</li>
        <li>Upwork Job ID: 1734345734978011136</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28045529</li>
<li>shubham1206agra | Contributor | 28045530</li>
</ul></li>
    </ul>
</details>

**Comment by tgolen** [comment] 2023-12-11 20:05
I'll take this. It is related to my recent refactoring

**Comment by tgolen** [comment] 2023-12-11 20:07
It looks like this is reproducible in production @lanitochka17? If so, then it shouldn't be a deploy blocker.

**Comment by tgolen** [comment] 2023-12-11 20:09
It also appears that this is reproducible regardless of the offline setting so I've updated the title of the issue.

**Comment by lanitochka17** [comment] 2023-12-11 20:21
Issue is not reproducible in Production:

https://github.com/Expensify/App/assets/78819774/c6993c6a-ee21-493f-b896-87bc740169fb

**Comment by tgolen** [comment] 2023-12-11 20:22
OK, thank you!

**Comment by tgolen** [comment] 2023-12-11 22:55
I haven't had any luck figuring out what the issue is with this one. I know it has something to do with [these two calls here](https://github.com/Expensify/App/blob/298d9d2db15db35dd49206151d9301e60ffb10a4/src/pages/iou/request/step/IOURequestStepConfirmation.js#L202-L228). I am opening this up to contributors to see if someone else can find the problem before I am able to.

**Comment by tgolen** [comment] 2023-12-11 23:01
I have this [draft PR](https://github.com/Expensify/App/pull/32878) which refactors the code slightly to conform to how the APIs expect to be used. I don't know if it's the real fix that we want though. It seems to work well.

**Comment by shubham1206agra** [comment] 2023-12-12 15:56
Please assign me here as I reviewed this PR

**Comment by kevinksullivan** [comment] 2023-12-14 15:10
Hi @shubham1206agra please complete the checklist above when you get a chance. Thanks!

**Comment by shubham1206agra** [comment] 2023-12-20 14:51
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28618
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28618#issuecomment-1864606149
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No as we already have caught this in deploy testing
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@kevinksullivan] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kevinksullivan** [comment] 2023-12-22 17:56
Hi @shubham1206agra can you accept the job offer so I can pay this out?

**Comment by shubham1206agra** [comment] 2023-12-22 18:13
Accepted

**Comment by kevinksullivan** [comment] 2023-12-22 18:14
All set, thanks!

**Comment by kevinksullivan** [comment] 2023-12-22 18:15
Upwork isn't letting me end the contract 🙄 , so I'll have to come back to taking this step later 

<img width="1020" alt="image" src="https://github.com/Expensify/App/assets/22508290/6f7829f7-91c9-4471-97eb-96cec0b7ad8b">

**Closed by kevinksullivan** 2023-12-22 18:14 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by shubham1206agra** [comment] 2023-12-22 18:20
I have ended the contract here
