### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] [Held requests] Not here page for held expense when partially pay the report

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49274] opened 2024-09-16 14:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** gocemate+a2160@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. User A goes to chat with User B
2. User A submits two expenses
3. User B put on hold first expense
4. User B partially pay the report
5. User B navigates to unpaid expense that is put on hold

## Expected Result:
Held expense should open and show the transaction details

## Actual Result:
Not here page appear when open unpaid held expense. On LHN this chat is displayed as Unavailable workspace owes - currency, -1 amount

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/103917e2-dd34-4f56-9029-1991d74bc567

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838873865299371336</li>
        <li>Upwork Job ID: 1838873865299371336</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 104402955</li>
<li>mkzie2 | Contributor | 104920263</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by IuliiaHerets** [comment] 2024-09-16 14:29
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-09-16 14:29
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by garrettmknight** [comment] 2024-09-16 18:18
@robertjchen are you aware of this behavior?

**Comment by mkzie2** [comment] 2024-09-17 09:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not here page appear when open unpaid held expense. On LHN this chat is displayed as Unavailable workspace owes - currency, -1 amount

### What is the root cause of that problem?
If we pay the report partially, we build the hold report Onyx data by using `getReportFromHoldRequestsOnyxData` function

https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/libs/actions/IOU.ts#L6857

Let's see `optimisticExpenseReport` here, we always build an expense report even if we're paying in an iou report. That causes LHN to display the wrong message

https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/libs/actions/IOU.ts#L6443

About the not found page bug, it's an BE bug because `OpenReport` API returns this report as not found.
### What changes do you think we should make in order to solve the problem?
If the `iouReport` is an iou report we should use `buildOptimisticIOUReport` function to create an optimistic iou report and we also need to introduce new param in `buildOptimisticIOUReport` to update the `parentReportActionID` if the new iou report as we do for `buildOptimisticExpenseReport`

```
const optimisticExpenseReport = ReportUtils.isExpenseReport(iouReport)
    ? ReportUtils.buildOptimisticExpenseReport(
          chatReport.reportID,
          chatReport.policyID ?? iouReport.policyID ?? '',
          recipient.accountID ?? 1,
          (firstHoldTransaction?.amount ?? 0) * -1,
          getCurrency(firstHoldTransaction),
          false,
          newParentReportActionID,
      )
    : ReportUtils.buildOptimisticIOUReport(
          iouReport.ownerAccountID ?? -1,
          iouReport.managerID ?? -1,
          firstHoldTransaction?.amount ?? 0,
          chatReport.reportID,
          getCurrency(firstHoldTransaction),
          false,
          newParentReportActionID,
      );
```
https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/libs/actions/IOU.ts#L6443

For the not found page issue, BE should store the new iou report when we pay the report partially and return the correct data in `OpenReport` API
### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment] 2024-09-17 18:06
@robertjchen assigning you to confirm whether we're aware and fixing this somewhere else before adding `External`.

**Comment by robertjchen** [comment] 2024-09-17 19:24
Thanks, let me evaluate!

**Comment by robertjchen** [comment] 2024-09-18 09:13
Ok, yes- we're already working on the fix for this here: https://github.com/Expensify/App/issues/46370 Consolidating there

**Comment by mkzie2** [comment] 2024-09-18 10:14
> On LHN this chat is displayed as Unavailable workspace owes - currency, -1 amount

@robertjchen We also have another bug here.

**Comment by robertjchen** [comment] 2024-09-18 11:29
We can revisit this issue after the other fix goes out- it's only happening because the backend is handling the whole process incorrectly.

**Comment by mkzie2** [comment] 2024-09-25 08:48
@robertjchen Look like https://github.com/Expensify/App/issues/46370 is closed but we still can reproduce the LHN bug. it still displays `Unavailabe workspace owes`

https://github.com/user-attachments/assets/5096648c-b9e6-4590-9165-7d1cb724b76f

**Comment by robertjchen** [comment] 2024-09-25 08:58
Is this test being performed offline? Is the BE now returning the correct data?

If you can confirm that the BE is fixed, then we can re-open to address what appears to be an issue with the FE optimistic logic.

**Comment by mkzie2** [comment] 2024-09-25 09:23
@robertjchen Yes, the BE is fixed, the only problem here is the FE optimistic logic.

**Comment by robertjchen** [comment] 2024-09-25 09:30
sounds good, reopening and tagging `External` for review of proposal 👍

**Comment by robertjchen** [comment] 2024-10-02 11:27
awaiting proposal review

**Comment by mkzie2** [comment] 2024-10-07 09:50
@eVoloshchak Can you look at my [proposal](https://github.com/Expensify/App/issues/49274#issuecomment-2355007694)?

**Comment by garrettmknight** [comment] 2024-10-08 18:40
@eVoloshchak can you take a look at that proposal when you get a chance?

**Comment by garrettmknight** [comment] 2024-10-11 00:20
Reassigning for review - @hoangzinh mind giving that proposal a look? Thanks!

**Comment by mkzie2** [comment] 2024-10-11 14:05
@hoangzinh I updated my [proposal](https://github.com/Expensify/App/issues/49274#issuecomment-2355007694).

**Comment by mkzie2** [comment] 2024-10-11 15:24
@hoangzinh 

Here is the logic we used to get the message text of the report preview action. We get the iou report of the report preview and use `getReportPreviewMessage` to get the message

https://github.com/Expensify/App/blob/12e41b177cc0a3dc1c4b26beceb28d337e69a37d/src/libs/OptionsListUtils.ts#L676-L688

And the `payerName` is wrong in this case. It displays as `policyName` because `iouReport` is an expense report as my RCA mentioned
https://github.com/Expensify/App/blob/12e41b177cc0a3dc1c4b26beceb28d337e69a37d/src/libs/ReportUtils.ts#L3449

**Comment by robertjchen** [comment] 2024-10-14 02:33
Thanks for the updated proposal, let's proceed with this solution!

**Comment by garrettmknight** [comment] 2024-11-15 18:50
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by garrettmknight** [comment] 2024-11-15 18:50
@hoangzinh can you finish the checklist when you get a chance?

**Comment by garrettmknight** [comment] 2024-11-15 18:56
@mkzie2 offer out to you!

**Comment by garrettmknight** [comment] 2024-11-18 15:27
@JmillsExpensify can a I get a confirmation on [this payment summary ](https://github.com/Expensify/App/issues/49274#issuecomment-2462140527)so I can pay out the C+?

**Comment by JmillsExpensify** [comment] 2024-11-20 12:56
Payment summary:

 - Contributor: @mkzie2 $250 via Upwork
 - Reviewer: @hoangzinh $250 via Upwork

**Comment by garrettmknight** [comment] 2024-11-20 13:07
$250 approved for @hoangzinh

**Comment by garrettmknight** [comment] 2024-11-20 13:12
All paid out

**Closed by garrettmknight** 2024-11-20 13:12 UTC
Labels: External, Daily, Awaiting Payment, Bug
