### ISSUE TITLE
[HOLD for payment 2023-06-23] [$1000] Email field is not cleared when the new contact method page is opened

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20496] opened 2023-06-09 02:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/settings/profile/contact-methods/new
2. Enter some email address
3. Click on Add button
4. Click on the New contact method button
## Expected Result: 
The email field is cleared and empty when the new contact method page is opened
## Actual Result: 
The email field is not cleared and the last entered email is still there

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
NOTE : Also, sometimes adding a contact method after opening the page direct through URL doesn't allow me to open the newly added contact method. Not sure how to reproduce this since this happens randomly.

https://github.com/Expensify/App/assets/43996225/9bc46c47-dd83-4ab9-a343-a593ecbb476d

https://github.com/Expensify/App/assets/43996225/3e896126-0cae-4e19-8b72-09426eba0272

https://github.com/Expensify/App/assets/43996225/9cace447-1079-4a31-bb46-6bcb6d390973

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685971374351349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4247ce2f81e2730</li>
        <li>Upwork Job ID: 1667285214162128896</li>
        <li>Last Price Increase: 2023-06-09</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2023-06-09 21:40
@kadiealexander sorry, I need to hand this off since I'll be OOO next week. Thanks for taking over!

**Comment by kadiealexander** [comment] 2023-06-12 02:16
Not overdue! Please don't forget to check the proposal above @abdulrahuman5196.

**Comment by kadiealexander** [comment] 2023-06-19 07:02
@JmillsExpensify I'm going OOO so I've reassigned this to ensure everyone gets paid on time. I've sent out all the offers which you can find [here](https://www.upwork.com/ab/applicants/1667285214162128896/hired), and @abdulrahuman5196 and @tienifr are due an #urgency bonus for their quick work ([here](https://github.com/Expensify/App/issues/20496#issuecomment-1591990213)). Thanks so much for your help!

**Comment by JmillsExpensify** [comment] 2023-06-27 04:35
Circling back to issue payouts now.

**Comment by JmillsExpensify** [comment] 2023-06-27 04:43
Alright, summarizing payouts:

 - Issue reporter: @adeel0202 $250
 - Contributor: @tienifr $1,500
 - Contributor+: @abdulrahuman5196 $1,500

I've added the [regression test here](https://github.com/Expensify/Expensify/issues/295219).

**Comment by JmillsExpensify** [comment] 2023-06-27 04:44
I think we're good here, so closing this one out!

**Closed by JmillsExpensify** 2023-06-27 04:44 UTC
Labels: External, Daily, Awaiting Payment, Bug
