### ISSUE TITLE
[$500] Public room - Flickering skeleton animation displayed when navigating to  public room "#exfy-roadmap"

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#37862] opened 2024-03-07 02:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.48-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:

1. Log in
2. Go to `#exfy-roadmap` public room: https://new.expensify.com/r/868417741568295

Note: If you fail to reproduce (room loads fine), log out and log in, then try again to open the room
Note2: If I open the link to the room without being logged in (anonymous account), it opens fine

## Expected Result:

The room should have loaded just fine

## Actual Result:

The skeleton animation stays flickering for ever and we start spamming the server with `OpenReport` requests

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/87341702/f5290b99-f996-42a5-8f04-abf499237610

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0f2346e21fd5507</li>
        <li>Upwork Job ID: 1769836029946839040</li>
        <li>Last Price Increase: 2024-03-18</li>
    </ul>
</details>

**Comment by aldo-expensify** [comment] 2024-03-07 02:04
This may be related to https://github.com/Expensify/App/issues/37661 or not (similar symptom at least)

**Comment by johncschuster** [comment] 2024-03-11 21:04
I'm applying the `retest-weekly` label so we can check to see if this issue persists now that the linked issue is closed.

**Comment by johncschuster** [comment] 2024-03-14 20:55
This should be retested tomorrow.

**Comment by johncschuster** [comment] 2024-03-15 20:56
Bumped to have it retested. If it still exists, I will need to figure out which project it fits into.

**Comment by johncschuster** [comment] 2024-03-15 20:59
Coming from the[ Road Map doc](https://docs.google.com/document/d/1pghDdrUVhINJH4jFWNbT2w-ecFqYwTvoGxx4EoYA1U8/edit#heading=h.8h6w5k8u12fm), it looks like it fits into #vip-vsb

**Comment by aldo-expensify** [comment] 2024-03-15 22:37
This still happens for me in staging. I logged out and logged in before testing to make sure I didn't have bad data in the client:


https://github.com/Expensify/App/assets/87341702/ff17f435-3b32-4cdc-b898-0edcc536e06a

The client keeps sending `OpenReport` requests in a loop even after leaving the room that didn't load.

**Comment by justinpersaud** [comment] 2024-03-15 22:58
Commenting because I have the same issue

**Comment by roryabraham** [comment] 2024-03-19 22:46
This appears to be a duplicate of https://github.com/Expensify/App/issues/35620, and we're addressing it in #fireroom-2024-03-19-spam-openreport. Going to close this

**Closed by roryabraham** 2024-03-19 22:46 UTC
Labels: External, Daily, Help Wanted, Bug
