### ISSUE TITLE
[$1000] Web - Unexpected error displayed after adding a comment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35107] opened 2024-01-24 21:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31.0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706069427229519

## Action Performed:
1. Login in NewDot
2. Select the Workspace chat
3. Add a comment

## Expected Result:
User is able to add comment without any error

## Actual Result:
Unexpected error displayed after adding a comment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (3)](https://github.com/Expensify/App/assets/93399543/8ba8c087-7191-471a-962b-b4960f5901b0)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186123ce8bf2e2147</li>
        <li>Upwork Job ID: 1752713142580895744</li>
        <li>Last Price Increase: 2024-02-19</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2024-02-02 18:10
I can't reproduce. No proposal yet

**Comment by johncschuster** [comment] 2024-02-02 22:20
I'll buzz #expensify-open-source on Monday to drum up proposals.

**Comment by johncschuster** [comment] 2024-02-05 23:51
Increased the bounty

**Comment by mvtglobally** [comment] 2024-02-13 04:51
Issue not reproducible during KI retests. (First week)

**Comment by jeremy-croff** [comment] 2024-02-13 05:36
Could it be related to the Category? I do not have that option. Maybe the Service doesn't like it?

Additionally,  I'm clueless how to set up this reimbursement report as well as get the Department options.

**Comment by DylanDylann** [comment] 2024-02-13 19:08
I can't reproduce this issue with test step on the OP. @jliexpensify Could you help to detail the previous step? how we create that report and what did we do before?

**Comment by jliexpensify** [comment] 2024-02-14 00:15
I would say that we should close this - honestly, these `Unexpected Error` GH's are really frustrating as they happen once and generally only to a single user and are near-impossible to reproduce. I also can't reproduce anymore.

cc @johncschuster

**Comment by DylanDylann** [comment] 2024-02-16 04:09
Let's close this one

**Comment by DylanDylann** [comment] 2024-02-19 11:06
not overdue. Wait to close

**Comment by johncschuster** [comment] 2024-02-20 22:31
Just caught up on this! Yeah, I agree we can close the issue. Thanks!

**Closed by johncschuster** 2024-02-20 22:31 UTC
Labels: External, Engineering, Daily, Needs Reproduction, Help Wanted, Bug, retest-weekly
