### ISSUE TITLE
Extra padding around vertical line in single backtick code block

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24143] opened 2023-08-04 02:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send multiple vertical lines in single backtick code block eg: `|||||`
4. Observe that it has padding around each line, try sending other symbols like @ in similar manner eg: `@@@@@` and observe that it does not have extra padding around
5. Try multiple vertical lines in 3 backtick codeblock and observe that it does not have any padding around each symbol eg: ```|||||```

## Expected Result:
App should not have extra padding around symbols in code block

## Actual Result:
App displays padding around vertical line in single backtick code block, other symbols does not have extra padding

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [X] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** Y 
**Reproducible in production?:**  Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/fca1645a-f5c0-4a21-a9b2-e4df71e3c5ef

https://github.com/Expensify/App/assets/43995119/db917c35-0fff-43a5-9153-bb82f4eeae76

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690797080473699
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhanashree-sawant** [comment] 2023-08-04 03:03
Yes I too had that doubt that it could be styling but currently we only have padding for one symbol i.e. '|', that seemed to me as odd and raised it as issue
![image](https://github.com/Expensify/App/assets/87513216/1c970031-481b-4541-93da-03019633b29c)

**Comment by laurenreidexpensify** [comment] 2023-08-04 09:21
Agree not a bug and expected. Am closing.

**Closed by laurenreidexpensify** 2023-08-04 09:21 UTC
Labels: Daily, Bug
