### ISSUE TITLE
[$500] Chat - Loading wheel for large image is not completely visible

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38687] opened 2024-03-20 16:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/tests/view/4441489
**Email or phone of affected tester (no customers):**  vdargentotest+ios032024@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: the user must be logged in
1. Go to any chat
2. Upload the attached large image
3. When the image finally uploads, verify that when it loads, the loading wheel is not completely visible

## Expected Result:
The loading wheel should be fully visible

## Actual Result:
The loading wheel is almost completely hidden

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6420675_1710950197283!IMG_E3498](https://github.com/Expensify/App/assets/78819774/54466fd9-fe08-4ca9-a5b7-d46800bd7c77)

![Bug6420675_1710950197332!bigggg](https://github.com/Expensify/App/assets/78819774/acca20e0-48da-4279-8ba9-8e5bda266459)

https://github.com/Expensify/App/assets/78819774/4969a3bc-2716-4eaa-bb05-17019585ff4f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010fa06a3d83b43db6</li>
        <li>Upwork Job ID: 1770603734538096640</li>
        <li>Last Price Increase: 2024-03-28</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-20 16:57
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-20 16:57
We think that this bug might be related to #vip-vsp

**Comment by johncschuster** [comment] 2024-03-20 20:48
Yeah, this feels like a pretty extreme case to me. I think we can probably close this.

**Comment by johncschuster** [comment] 2024-03-21 00:09
Welp! After discussing, we feel it's worth fixing. I've added it to `#vip-vsb`

**Comment by jsdev2547** [comment] 2024-03-22 01:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Loading wheel for large image does not fit inside image dimensions.
### What is the root cause of that problem?
The root cause of the issue is the loader is displayed inside the image. If the loader dimensions are greater than the image dimensions, the loader does not fit inside the image.
https://github.com/Expensify/App/blob/e6f64324c8efa20b32420901b083a063f4a4ceb6/src/components/ImageWithSizeCalculation.tsx#L105

### What changes do you think we should make in order to solve the problem?

The loader should not be displayed inside the image. Add state variable in ThumbnailImage component
https://github.com/Expensify/App/blob/e6f64324c8efa20b32420901b083a063f4a4ceb6/src/components/ThumbnailImage.tsx#L57
```
const [isLoaded, setIsLoaded] = useState(false);
```

In updateImageSize callback, setIsLoaded to true
https://github.com/Expensify/App/blob/e6f64324c8efa20b32420901b083a063f4a4ceb6/src/components/ThumbnailImage.tsx#L75
```
setIsLoaded(true);
```

The sizeStyles can be conditional, if isLoaded is false then use styles.invisibleImage. Using styles.invisibleImage provides placeholder image with width and height of 200.
https://github.com/Expensify/App/blob/e6f64324c8efa20b32420901b083a063f4a4ceb6/src/components/ThumbnailImage.tsx#L80

```
const sizeStyles = isLoaded ? (shouldDynamicallyResize ? [thumbnailDimensionsStyles] : [styles.w100, styles.h100]) : [styles.invisibleImage];
```

Then add FullscreenLoadingIndicator and check for isLoaded.
https://github.com/Expensify/App/blob/e6f64324c8efa20b32420901b083a063f4a4ceb6/src/components/ThumbnailImage.tsx#L106
```
{
    !isLoaded && (
        <FullscreenLoadingIndicator style={[styles.opacity1, styles.bgTransparent]} />
    )
}
```

### What alternative solutions did you explore? (Optional)

**Comment by jsdev2547** [comment] 2024-03-22 11:10
@dukenv0307 Please provide some video or screenshot so I can understand the issue.

**Comment by jsdev2547** [comment] 2024-03-22 11:28
@dukenv0307 Please check for images with lesser width than the width of the loader. The aspect ratio would stretch the image should the minimum be lesser than the width of the loader.
I tested using, 
const aspectRatio = (height && Math.max(width / height, 0.15)) || 1;

![blur](https://github.com/Expensify/App/assets/161593779/d83d4b87-77a4-4f63-9082-8052c866ad17)

**Comment by jsdev2547** [comment] 2024-03-22 16:53
@dukenv0307 I tested on main and on staging using thin width image(90px) and the blur image is introduced by using,
const aspectRatio = (height && Math.max(width / height, 0.15)) || 1;

I am not able to reproduce the bug on main branch.

For reference,
main branch

![main](https://github.com/Expensify/App/assets/161593779/53cdb9e2-6d24-4354-9fb6-12c24c9a7f2f)

main branch using
const aspectRatio = (height && Math.max(width / height, 0.15)) || 1;

![after](https://github.com/Expensify/App/assets/161593779/583c597b-9c40-4fee-a949-597f40a37e68)

**Comment by jsdev2547** [comment] 2024-03-22 17:27
> Pls check 2 images below. The first one is loading state and the second one is loaded state. The width changes after the image is loaded -> flicker

@dukenv0307 The invisible image in loading state has width height of 200px. I have revised [proposal](https://github.com/Expensify/App/issues/38687#issuecomment-2014148219) instead of using invisibleImage, use styles.invisible. The loader displays the actual thumbnail image and no shift in width.

[poc-loader.webm](https://github.com/Expensify/App/assets/161593779/c73718df-6935-4229-9105-a53848f70a43)

**Comment by jsdev2547** [comment] 2024-03-22 18:03
@dukenv0307 I am not getting blurred image on main branch though, the image might be thin but not blurred. The blur is caused by using, 
const aspectRatio = (height && Math.max(width / height, 0.15)) || 1;
I am not convinced the bug is different because when I get latest and run the app the image is not blurred but when I use 
const aspectRatio = (height && Math.max(width / height, 0.15)) || 1;
the image is stretched to match the width of the loader and gets blurred.

**Comment by jsdev2547** [comment] 2024-03-25 10:17
@dukenv0307 Please check revised [proposal](https://github.com/Expensify/App/issues/38687#issuecomment-2014148219) using styles.invisible. 

The issue with the current proposal is the magic number (0.15 or 0.30). The blur is caused by using magic numbers. For example, the image in OP has wide enough width and the blurring is not noticeably visible but set the width to 2% of the height and try loading the image and the thumbnail would be blurred.

const aspectRatio = (height && Math.max(width / height, 0.15)) || 1;

Please test the following image with current proposal on main branch. Remove the magic number 0.15 and the thumbnail is not blurred, add the 0.15 and the thumbnail is stretched. The blurring is due to the use of magic number 0.15. I suggest not to put loader inside image but allow the image to load and then show the thumbnail.
https://github.com/Expensify/App/assets/161593779/b9ed8c00-f03d-47ef-be54-450d47403e8c

**Comment by johncschuster** [comment] 2024-04-01 21:46
@youssef-lr, can you take a look at @dukenv0307's recent comment above?

**Comment by johncschuster** [comment] 2024-04-02 20:43
Bump!

**Comment by youssef-lr** [comment] 2024-04-02 21:55
Agreed with your decision @dukenv0307

**Comment by mvtglobally** [comment] 2024-04-04 03:25
Issue not reproducible during KI retests. (First week)

**Comment by youssef-lr** [comment] 2024-07-02 05:19
Replied in the thread @dukenv0307, I'm still facing issues locally that deal with attachments, hoping we can resolve them today

**Comment by johncschuster** [comment] 2024-08-21 14:24
Sure thing, @tienifr!

I reviewed the issue with @youssef-lr, and it looks like the PR was closed and the fix was not implemented. However, we feel you both deserve payment for putting in the work. I'm going to issue 50% of the payment for the work you've done here.

**Comment by johncschuster** [comment] 2024-08-21 14:29
# Payment Summary:

Contributor: @tienifr paid $250 via Upwork
Contributor+: @dukenv0307 owed $250 via NewDot

**Comment by johncschuster** [comment] 2024-10-08 15:20
Thanks for raising that, @dukenv0307! I'm happy to issue full payment if this was discussed. Let me change the comment above and also issue the remaining payment to @tienifr.

**Comment by johncschuster** [comment] 2024-10-08 15:23
Got it! I'll update that comment above and will pay you now via Upwork.

**Comment by johncschuster** [comment] 2024-10-08 16:01
@tienifr, I previously paid you $250 for this job, but I need to issue the remaining $250 given the conversation that @dukenv0307 linked above. Can you please accept the invite to this job? 

https://www.upwork.com/nx/wm/offer/104323370

**Comment by johncschuster** [comment] 2024-10-09 13:14
Paid! Thank you!

**Comment by johncschuster** [comment] 2024-10-10 12:34
@tienifr / @dukenv0307 / @youssef-lr do we require a regression test for this? If so, can you provide that? If not, we can close this up.

**Comment by johncschuster** [comment] 2024-10-11 14:31
Oh duh. I forgot that 🤦 😂 

Closin!

**Closed** 2024-10-11 14:31 UTC
Labels: Reviewing, External, Weekly, Not a priority, Bug
