### ISSUE TITLE
[Search v2.2] Update Trips empty state on Search to avoid double empty state

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#47937] opened 2024-08-23 17:26 UTC
Right now when you access the Trips empty state via search, you press a big green button that leads to an RHP view with virtually the same information. 

https://github.com/user-attachments/assets/647d89ea-d4a0-4dbd-b781-67032df732aa

Let's just combine everything into the Trips empty state view so that it looks like this:
![CleanShot 2024-08-23 at 13 23 58@2x](https://github.com/user-attachments/assets/79f5f9b2-814e-4b2c-80fb-1e10528e178e)

Rather than adding two buttons into the empty state like the RHP does, I'm suggesting we just change the "Book a demo" button to be a link in the text above. 

cc @filip-solecki in case this might be interesting to you.

cc @dylanexpensify & @luacmartins to file this one under #44038 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01042577ade1f53d6d</li>
        <li>Upwork Job ID: 1827040366251521288</li>
        <li>Last Price Increase: 2024-08-23</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103693340</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by DylanDylann** [comment] 2024-08-26 10:07
@daledah's [proposal](https://github.com/Expensify/App/issues/47937#issuecomment-2308369284) looks good to me. Please remember to use translation instead of hard-code string

🎀 👀 🎀 C+ reviewed

**Comment by shawnborton** [comment] 2024-08-26 15:52
Also I want to add to the solution here: let's update the empty state to use a Lottie animation.

File for that is here: [TripsEmptyState-082324-1.json.zip](https://github.com/user-attachments/files/16750820/TripsEmptyState-082324-1.json.zip)

cc @roryabraham just to double check again, do I need to supply a .lottie file or are the .json files okay?

**Comment by roryabraham** [comment] 2024-08-26 19:04
We want `.lottie` files, which we just get by uploading the json ones to https://app.lottiefiles.com/: https://stackoverflowteams.com/c/expensify/questions/17073

**Comment by roryabraham** [comment] 2024-08-26 19:08
[OptimizedAnimations.zip](https://github.com/user-attachments/files/16752703/OptimizedAnimations.zip)

**Comment by luacmartins** [comment] 2024-08-26 22:09
Thanks! Proposal LGTM. Let's do this!

**Comment by DylanDylann** [comment] 2024-08-27 08:44
Waiting for a confirmation [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1724748217484429?thread_ts=1724746631.932369&cid=C01GTK53T8Q)

**Comment by luacmartins** [comment] 2024-08-27 19:39
```
“Book a demo” = “Reserva una demo”
“to learn more” = “para obtener más información”
```

**Comment by shawnborton** [comment] 2024-08-28 11:21
I think that's fine, but the modal shouldn't be cut off - we should be able to see the whole thing there. 

cc @filip-solecki - I'm not sure how you implemented the height there, but is there some kind of fixed minimum or something? I would think that it would have a min-height but it would also always be tall enough to show all of the inner modal content.

**Comment by lschurr** [comment] 2024-09-02 21:24
What's the latest on this one @DylanDylann @daledah?

**Comment by lschurr** [comment] 2024-09-03 16:01
Ok, thanks! It seems we're waiting on confirmation from @filip-solecki in that comment

**Comment by filip-solecki** [comment] 2024-09-04 07:41
Hi! I think there isn't any max or min height defined for the empty state modal. But looks like there are some styles to change, I guess it might be flex but I'm not sure. Right now I am not able to take a look at this so feel free to find some solutions and ping me, otherwise I can take a look on Friday

**Comment by lschurr** [comment] 2024-09-05 19:09
Thoughts @shawnborton @daledah?

**Comment by shawnborton** [comment] 2024-09-05 19:52
Let's discuss on the PR? We need to find some kind of solution to the min-height problem.

**Comment by DylanDylann** [comment] 2024-09-11 08:37
@filip-solecki Kindly bump https://github.com/Expensify/App/issues/47937#issuecomment-2328144008

On the other hand, @daledah Could you jump into the above problem to unblock the PR? If this is complicated we can raise a bounty later

cc @luacmartins

**Comment by luacmartins** [comment] 2024-09-26 02:11
PR is merged

**Comment by lschurr** [comment] 2024-10-07 13:54
Thanks @daledah - Could you point me to the PR that fixed the bug?

**Comment by lschurr** [comment] 2024-10-07 14:06
Great, ok! So was there a regression or should this be paid in full? @luacmartins @DylanDylann @daledah

**Comment by lschurr** [comment] 2024-10-09 16:56
Payment summary:

- Contributor: $125 @daledah (Offer sent in [Upwork](https://www.upwork.com/nx/wm/offer/104342695))
- Reviewer: $125 @DylanDylann (Paid in Upwork)

**Comment by lschurr** [comment] 2024-10-09 18:42
All set!

**Closed by lschurr** 2024-10-09 18:42 UTC
Labels: External, Monthly, NewFeature, Awaiting Payment
