### ISSUE TITLE
[$500]  Conversation - Strikethrough does not work if the "_" italic is not completely closed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35789] opened 2024-02-04 20:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4281168
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in under your HT account
3. Navigate to any conversation or create one
4. Type "_~Text~" without quotation marks and send it to

## Expected Result:
Strikethrough should work if the " ~ " sign is in front of and behind the phrase

## Actual Result:
Strikethrough does not work if " _~text~ " italics are not fully closed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d39fd613-6f14-4e8d-af1c-837472c10f90

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0178511d0743874f58</li>
        <li>Upwork Job ID: 1754245274546057216</li>
        <li>Last Price Increase: 2024-02-04</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-04 20:49
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by BryceAltman** [comment] 2024-02-05 01:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Strikethrough does not work as expected when preceded by an underscore (_) 

### What is the root cause of that problem?
In the library linked below the regex for strikethrough begins with `\B` which means it expects a non word character at the beginning. An underscore (_) is one of the few characters which is included as a word character, which is what causes the regex to fail when the underscore is present, but not for other characters such as *

https://github.com/Expensify/expensify-common/blob/6ae333c38ca5909245c6310db1dc66728d62d0ed/lib/ExpensiMark.js#L282

### What changes do you think we should make in order to solve the problem?
Removing the \B from the regex would fix this issue, but would also enable matches in the middle of words, so part of a word could be struckthrough e.g. strike~through~.  I think this behaviour does have a use case so I don't see an issue.

### What alternative solutions did you explore? (Optional)
If it is preferred to not match in the middle of words, the regex can instead be altered to include underscores at the beginning as well as non word characters with `\B`. E.g `(\B|_)` this would match for ~test~ and _~test~ but not test\~test~

**Comment by getusha** [comment] 2024-02-06 19:31
I agree this is expected same happens with `#~Text~`
we can close this, @laurenreidexpensify

**Closed** 2024-02-08 10:57 UTC
Labels: External, Daily, Help Wanted, Bug
