### ISSUE TITLE
[HOLD #368997] [$500]  Web - New Dot tab reloads every time user switches to another tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36343] opened 2024-02-12 15:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in
3. After login, switch to a different tab

## Expected Result:
The New Dot tab will not reload

## Actual Result:
The New Dot tab reloads every time user switches to another tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/119161f5-f8a7-4fae-8fae-df07951b4ba4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e30f67ef5530e985</li>
        <li>Upwork Job ID: 1757447213211623424</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-12 15:25
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by flodnv** [comment] 2024-02-12 16:25
Why do we think this @lanitochka17 ? Where was it discussed?

**Comment by Beamanator** [comment] 2024-02-13 09:05
It's poooossible this has been fixed, I am having trouble reproducing in v1.4.40-2

**Comment by Beamanator** [comment] 2024-02-13 09:10
Marking NAB b/c can't reproduce in latest staging 👍

**Comment by flodnv** [comment] 2024-02-13 13:26
Discussing here: https://expensify.slack.com/archives/C9YU7BX5M/p1707830123344949?thread_ts=1707772795.526639&cid=C9YU7BX5M

**Comment by flodnv** [comment] 2024-02-13 16:50
@Beamanator and myself can't reproduce. @kavimuru indicates:

confirmed with the tester

1. Login to ND (in-congnito)
2. Wait for a build update
3. Refresh ND.
4. Go to different tab.
5. See tab 1 getting refreshed

Then to confirm the reproducibility he did:

1. Restarted incognito mode (to clear cache)
2. Login to ND
3. Refresh ND.
4. Switch to other tab

Is anyone able to reproduce this?

**Comment by aldo-expensify** [comment] 2024-02-14 18:55
I think this should be a deploy blocker because I can reproduce in `staging` and not in `production`

The problem seems to be coming from the request to get `version.json`. 

Production:
<img width="695" alt="image" src="https://github.com/Expensify/App/assets/87341702/fe6dcc3f-ee2d-43a1-9a9f-dd200196288e">


Staging:

<img width="1365" alt="image" src="https://github.com/Expensify/App/assets/87341702/94315a39-e5dd-4eb0-b575-a9a2a4f33800">

**Comment by aldo-expensify** [comment] 2024-02-14 18:57
Asking in slack: https://expensify.slack.com/archives/C03TQ48KC/p1707937015961739

**Comment by aldo-expensify** [comment] 2024-02-14 19:10
Removing deploy blocker label because:

- Seems to be related to Clouldflare cache
- Got fixed on my end and can't reproduce anymore with any account

**Comment by roryabraham** [comment] 2024-02-14 19:21
Throwing this on HOLD because we think the root cause is https://github.com/Expensify/Expensify/issues/368997

**Comment by roryabraham** [comment] 2024-02-17 10:40
confirmed, I can no longer reproduce. This wasn't consistently reproducible anyways, but I'm pretty confident that was the root cause and it has been fixed

**Closed by roryabraham** 2024-02-17 10:40 UTC
Labels: External, Engineering, Weekly, Needs Reproduction
