### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500] Chat - Hover menu is not dismissed after opening emoji picker

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34833] opened 2024-01-19 19:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to any chat
2. Hover over any message
3. Click Add reaction icon
4. Hover away from the message

## Expected Result:
Hover menu is dismissed after opening emoji picker

## Actual Result:
Hover menu is not dismissed after opening emoji picker

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b74ca732-3467-43c8-a4df-0ed846f1ad10

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c51a081dafada031</li>
        <li>Upwork Job ID: 1758506887343419392</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2024-01-19 19:19
BTW, This is not a regression from the overflow menu PR as the hover menu was not dismissed even before the PR

https://github.com/Expensify/App/assets/77237602/d7bce24a-0f57-4965-96c5-eb79fe44b096

**Comment by abzokhattab** [comment] 2024-01-19 19:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hover menu is not missed after opening emoji picker 
### What is the root cause of that problem?


in the `onPressOpenPicker` we dont close the context menu 

https://github.com/Expensify/App/blob/c884245e7204abad57e01752ec54e4011c1e43e9/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L139 


### What changes do you think we should make in order to solve the problem?

define a new function `openPickerAndCloseMenu`

```js

            const openPickerAndCloseMenu = () => {
                openContextMenu();
                closeContextMenu();
            };
```


then inside then change `onPressOpenPicker` to  

```js
                        onPressOpenPicker={openPickerAndCloseMenu}
```

**Comment by JeremyCroff** [comment] 2024-01-19 22:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The message context menu does not close when leaving the focus area of the message, after you have selected the Add emoji reaction button. This is inconsistent with other buttons such as the Menu button from the context menu, hence an inconsistent experience.

### What is the root cause of that problem?
The root cause is that each context button is responsible for it's own calling of the closePopover callback. And is left out in the emoji reaction button. Causing an inconsistent behavior within the app.

### What changes do you think we should make in order to solve the problem?
In order to solve this problem I looked at both Slack and Discord to see how they handle this. They both will keep the hover context menu open, if you are in an unfinished interaction such as having selected the emoji button but not having chosen one yet. Even after leaving focus of the message that triggered the context menu.
This means that the current behavior for the Emoji reaction button is a standard one, and we should actually change the behavior of how the Menu button behaves ( last one in the hover context menu ), for consistency within the app, and across other popular messaging apps for the best customer experience.


### What alternative solutions did you explore? (Optional)
I explored hiding the context menu, by calling closePopover. Simple, but will deviate us from industry standards.

**Comment by mollfpr** [comment] 2024-01-22 15:16
Thanks guys!

> This means that the current behavior for the Emoji reaction button is a standard one, and we should actually change the behavior of how the Menu button behaves ( last one in the hover context menu ), for consistency within the app, and across other popular messaging apps for the best customer experience.

I agree with @JeremyCroff that we have an inconsistency on the context menu popup open from the hover context menu.

https://github.com/Expensify/App/assets/25520267/95d3b999-c283-4fa2-8e7a-2a9287ddadf4

@JmillsExpensify I'm not sure if it's a bug.

**Comment by jeremy-croff** [comment] 2024-01-23 03:29
> Thanks guys!
> 
> > This means that the current behavior for the Emoji reaction button is a standard one, and we should actually change the behavior of how the Menu button behaves ( last one in the hover context menu ), for consistency within the app, and across other popular messaging apps for the best customer experience.
> 
> I agree with @JeremyCroff that we have an inconsistency on the context menu popup open from the hover context menu.
> 
>  Screen.Recording.2024-01-22.at.22.06.27.mp4 
> @JmillsExpensify I'm not sure if it's a bug.

My proposal is temporarily hidden - while I am recovering my github account it's in a suspended state.

My summary of the proposal was that after reviewing Discord and Slack, we should keep the toolbar open like it currently is. And introduce a clicked state for the icon. Further more, we should make the three dots for the Menu button behave the same, as currently it dismissed the toolbar when clicking on it.

I can write up another formal proposal if necessary, but maybe some one has the logs for it.

**Comment by mollfpr** [comment] 2024-01-23 14:42
Yeah, I agree that both of you have inconsistency, and the behavior should be similar to what Slack does.

But I don't know if we want to fix it here or create a new issue since the OP is expected.

@JmillsExpensify Can we fix the inconsistency and update this issue's title and description?

**Comment by mollfpr** [comment] 2024-01-29 15:52
Friendly bump @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2024-01-31 17:31
>My summary of the proposal was that after reviewing Discord and Slack, we should keep the toolbar open like it currently is. And introduce a clicked state for the icon.

I agree with this though I'd also like to confirm with @Expensify/design on the clicked state for the icon. Thoughts?

**Comment by dannymcclain** [comment] 2024-01-31 18:07
I personally don't think we need a clicked/active state for the icon, but I 100% agree that the menu should stay open (and just for clarity, I'm saying the way the "add reaction" option behaves right now is the correct behavior imo).

**Comment by shawnborton** [comment] 2024-01-31 18:36
Got it, I'm down with that approach, so sounds like we can close this?

**Comment by dannymcclain** [comment] 2024-01-31 19:29
> Got it, I'm down with that approach, so sounds like we can close this?

Is the plan to close this and open a different ticket for the three-dot menu (which currently does not follow this behavior)?

**Comment by shawnborton** [comment] 2024-01-31 19:31
Ah, I missed that part. I think we could just update this ticket with the correct report then.

**Comment by dannymcclain** [comment] 2024-02-01 14:05
Good point—I personally don't think it's a HUGE deal, but yes, it would be ideal if it stayed "focused/hovered" like when you have the context menu open.

**Comment by esh-g** [comment] 2024-02-01 17:40
> Good point—I personally don't think it's a HUGE deal, but yes, it would be ideal if it stayed "focused/hovered" like when you have the context menu open.

Let me know if we end up going ahead with this as I worked on the original implementation of the overflow menu

**Comment by mollfpr** [comment] 2024-02-05 17:15
I'll re-reviewing the proposal in the morning!

**Comment by mollfpr** [comment] 2024-02-12 15:08
To clarify we will fix a few issues here.

1. Add a hovered/focused background on the report action while the emoji picker opens from the context menu or mini context menu
2. Retain the mini context menu while opening the menu

@JmillsExpensify @dannymcclain Is this correct?

**Comment by mollfpr** [comment] 2024-02-12 16:19
Thanks @dannymcclain for the confirmation!

@JmillsExpensify I think we need to update the issue title and description to match up with the new expectation.

**Comment by mollfpr** [comment] 2024-02-16 19:57
@JmillsExpensify Could you update the issue title and description for the [summary](https://github.com/Expensify/App/issues/34833#issuecomment-1938858064)? Thank you!

**Comment by mollfpr** [comment] 2024-02-20 18:48
Friendly bump @JmillsExpensify

**Comment by mollfpr** [comment] 2024-02-26 09:33
I'll make this move forward! Meanwhile we still need to update the title and issue description.

The [proposal](https://github.com/Expensify/App/issues/34833#issuecomment-1901846497) from @tienifr has what the issue we will solve and I think it's on the correct path.

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment] 2024-02-27 04:49
I think Melvin doesn't notice the assignment because we missing the `External` label 👀

@tienifr Let me know when the PR ready? Thank you!

**Comment by mollfpr** [comment] 2024-03-14 13:54
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR was found. The issue expanded to be improved and aligned on highlighting the report action and keeping the context menu open.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression test should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

We have a good place [here](https://expensify.testrail.io/index.php?/suites/view/7722&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=229067) on the test rail to add more step.

1. Hover over any message (right-click on the action or add any reaction)
2. Click the Add reaction icon to open the emoji picker
3. Hover away from the message
4. Verify that the background is retained
5. Verify that the mini context menu is open if users open the emoji picker from the mini context menu
6. Select any emoji or click outside to close the emoji picker
7. Verify that the background has disappeared and the mini context menu is close
8. Click three dot/ menu icons to open the popover
9. Hover away from the message
10. Verify that the background is retained and the mini context menu is open
11. Click outside to close the popover
12. Verify that the background has disappeared and the mini context menu is close

**Comment by mollfpr** [comment] 2024-03-14 13:54
@JmillsExpensify Could you create the payment summary? Thank you!

**Comment by JmillsExpensify** [comment] 2024-03-18 15:04
Looks like we don't have an automatic Upwork issue. Created one just now and sent an offer to @tienifr. @trjExpensify Another one, can you please confirm the summary above?

**Comment by JmillsExpensify** [comment] 2024-03-18 15:12
Payment released via Upwork.

**Comment by trjExpensify** [comment] 2024-03-18 15:14
Payment summary [here](https://github.com/Expensify/App/issues/34833#issuecomment-1998184314) looks good!

**Comment by JmillsExpensify** [comment] 2024-03-18 15:34
$500 approved for @mollfpr based on summary.

**Comment by JmillsExpensify** [comment] 2024-03-18 15:36
Regression test request created. Closing.

**Closed by JmillsExpensify** 2024-03-18 15:36 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
