### ISSUE TITLE
App crashes when Ctrl/Cmd + D is pressed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43897] opened 2024-06-18 12:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating https://github.com/Expensify/App/pull/43543
**Version Number:** 1.4.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Sign in to Expensify.
2. Press Ctrl/Cmd + D.

## Expected Result:
Pressing Ctrl/Cmd + D should not cause the app to crash instead it should open the troubleshooting model

## Actual Result:
The app crashes when pressing Ctrl/Cmd + D

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/7714b4fc-16cd-4703-9963-01eca61f1dc3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-06-18 12:48
@greg-schroeder FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dangrous** [comment] 2024-06-18 15:43
And it's definitely (by default) related to https://github.com/Expensify/App/pull/43543 since that created the shortcut

Side note, this is not listed in our in-app keyboard shortcuts list

**Comment by dangrous** [comment] 2024-06-18 15:57
I think it's maybe not the shortcut but something to do with opening the separate modal for the options instead of going to the troubleshoot page.

There's nothing in the console, weirdly.

Also after clicking "Refresh" the modal DOES show up, but the slider doesn't work. Again, nothing in the console.

**Comment by dangrous** [comment] 2024-06-18 16:08
oh huh, i wonder why that isn't showing up for me!

I've pinged the folks that worked on the focus trap, hopefully they have some ideas!

**Comment by dangrous** [comment] 2024-06-18 20:28
OMG I had my console filtered and I didn't realize. I see the error now, hopefully that will help me diagnose.

**Comment by dangrous** [comment] 2024-06-18 21:08
Okay! So. I know why it doesn't happen on dev - it's because of https://github.com/Expensify/App/blob/c64c55f6721b84c08288eb89e5d16cc743a508ed/src/components/TestToolsModal.tsx#L47 - if that TestToolMenu isn't there, then it breaks the focus trap, with the error @dominictb noted. Going to ping @adamgrzybowski and @jnowakow here because they might be able to figure out how to fix.

Technically I think this is a regression, as it _could_ have been discovered during testing of #43543, though it is unlikely since it's because of a dev only feature that it works fine. Not sure about official responsibility here but will keep trying to figure it out - all other opinions welcome!

**Comment by dangrous** [comment] 2024-06-19 00:10
Another update, I found this [online](https://github.com/ndimatteo/HULL/issues/88):

```
This can happen if there isn't a link/button within the <FocusTrap /> component and there is animations happening that could cause it to not be focusable when the focus trap component mounts.

There's a few solutions here:

1. Default the FocusTrap's active prop to false until the animation is complete
2. Set a fallbackFocus ref via the focusTrapOptions prop

I hope that helps, but let me know if you run into any specific issues with the core HULL components using FocusTrap!
```

I think it's because the modal is animating in and so there's nothing focusable - it seems like that first option makes the most sense

**Comment by Beamanator** [comment] 2024-06-19 07:30
FYI @jnowakow is looking into fixing this one 🙏 - [slack thread](https://expensify.slack.com/archives/C04878MDF34/p1718781971997089?thread_ts=1718346278.994659&cid=C04878MDF34)

**Comment by jnowakow** [comment] 2024-06-19 07:42
Yeah, I've found the root cause - it's described [here](https://github.com/focus-trap/focus-trap?tab=readme-ov-file#error-your-focus-trap-must-have-at-least-one-container-with-at-least-one-tabbable-node-in-it-at-all-times). Focus trap is created before the elements are mounted in dom and this causes the error. The solution is to add `fallbackFocus` for example to `document.body` and it prevents the error. I'll open PR in a minute

**Comment by Beamanator** [comment] 2024-06-19 08:21
Merged & CPing PR

**Comment by Beamanator** [comment] 2024-06-19 09:02
Removing deploy blocker b/c this was fixed in staging! I think we can close too, but i'll let @dangrous do that haha

**Comment by dangrous** [comment] 2024-06-20 16:31
Okay great! Thanks for the assist @Beamanator. Closing now.

**Closed by dangrous** 2024-06-20 16:31 UTC
Labels: Reviewing, Engineering, Weekly, Bug
