### ISSUE TITLE
[$500] Android - Chat - Attachment - Preview of a multi-page PDF cannot be scrolled

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30979] opened 2023-11-07 11:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR:* https://github.com/Expensify/App/pull/28469

**Version Number:** 1.3.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open Android Expensify App
2. Login with any account
3. Go to any chat
4. Tap "+" > "Add Attachment > Choose document
5. Select any multi-page PDF
6. Scroll preview of this multi-page PDF

## Expected Result:
Preview of a multi-page PDF can be scrolled before uploading

## Actual Result:
Preview of a multi-page PDF cannot be scrolled before uploading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/6d0ac297-448d-4eaa-8b46-8061c2e9c37f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018554c178eebee2b3</li>
        <li>Upwork Job ID: 1721852555493412864</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by Beamanator** [comment] 2023-11-07 13:36
Looks like this was caused by PR: https://github.com/Expensify/App/pull/30050

Author supposedly has a fix incoming ([source](https://github.com/Expensify/App/pull/30050#issuecomment-1798469976))

**Comment by Beamanator** [comment] 2023-11-08 08:10
Fixed in latest staging, due to https://github.com/Expensify/App/pull/30995 👍

**Comment by trjExpensify** [comment] 2023-11-09 00:35
Cool, so to confirm, can this be closed?

**Comment by Beamanator** [comment] 2023-11-09 07:53
Mmmm well it looks like the fix isn't on prod yet, am i crazy? Also I'm not sure if @mollfpr is being paid for his efforts reviewing that PR elsewhere?

**Comment by trjExpensify** [comment] 2023-11-09 17:31
Yes, he should be paid on the issue where we hired the contributor and also take into account regressions. Came from here you see: https://github.com/Expensify/App/pull/30050

Closing!

**Closed by trjExpensify** 2023-11-09 17:31 UTC
Labels: External, Engineering, Weekly, Bug
