### ISSUE TITLE
mWeb - Chat - When opening a request and going back, the requests list is displayed empty

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39609] opened 2024-04-04 14:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v 1.4.60-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** bellicoignacio@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the https://staging.new.expensify.com
2. Open any chat that contains requests.
3. Tap on the requests preview.
4. Open any request from the list displayed.
5. Tap on the arrow on the top left corner.
6. Check the requests list behaviour.

* Sometimes you need to relog-in to see the issue

## Expected Result:
The requests list, should remain visible when opening one and returning to previous page.

## Actual Result:
After opening one request and tapping on the arrow to go back to previous page, the requests list is displayed empty.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/81bdf6f3-7451-454d-8c00-ac0b17ada5b2

![Bug6437555_1712204086303!Requests](https://github.com/Expensify/App/assets/115492554/930c1990-cf1b-40e0-91bc-5baa765b12bf)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-04 14:25
We think this issue might be related to the #vip-vsb.

**Comment by mountiny** [comment] 2024-04-04 15:56
cc @NikkiWines as it might be still related to the one transaction view

Noting that the production deploy did not work this morning so the current production is actually 2 releases back from current staging (hence the one transaction PR is not in production yet)

**Comment by NikkiWines** [comment] 2024-04-04 16:56
Pretty sure this is a dupe of https://github.com/Expensify/App/issues/39461 which we determined was not due to a front-end change

**Comment by luacmartins** [comment] 2024-04-04 18:32
Cool, so it seems like we can close this in favor of https://github.com/Expensify/App/issues/39461?

**Comment by NikkiWines** [comment] 2024-04-04 18:46
At the very least it's not a blocker, buuuuuttttt... I'd love your help on https://github.com/Expensify/App/issues/39461 if you have the bandwidth 🙇 

Rory summarized our findings from yesterday [here](https://expensify.slack.com/archives/C07J32337/p1712193854585489?thread_ts=1712184224.944899&cid=C07J32337). I'm not very familiar with our pusher logic and why we're not passing the correct `previousReportActionID` even though `OpenReport` is returning the right value.

**Comment by luacmartins** [comment] 2024-04-08 16:25
PR is in review.

**Comment by luacmartins** [comment] 2024-06-27 15:53
This was fixed a while ago, but the automation didn't close the issue. Closing!

**Closed by luacmartins** 2024-06-27 15:53 UTC
Labels: Reviewing, Engineering, Monthly, Bug
