### ISSUE TITLE
[HOLD for payment 2024-01-24] Settings - 'Go to Expensify Classic' options redirect to prod, not STG version

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33284] opened 2023-12-19 13:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.14-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/r/88085227
2. Login with any account
3. Go to Settings -> Go to Expensify Classic

## Expected Result:
The system redirects to the staging version of OldDot

## Actual Result:
The system redirects to the production version of OldDot

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d10b4379-4bfe-4cc0-ae41-2a9a9e02f707

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment] 2023-12-19 13:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
We are using the hard-coded prod URL in the menu item:

https://github.com/Expensify/App/blob/aa1d87caddb6831061f3750bd78f77b42603e5e3/src/pages/settings/InitialSettingsPage.js#L267-L272

### What changes do you think we should make in order to solve the problem?
We shouldn't use the constant URL, but instead use the `Link.buildOldDotURL('inbox')`

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2023-12-19 13:18
This is not deploy blocker as new feature and should work fine on production.
cc: @barttom as coming from https://github.com/Expensify/App/pull/32947

**Comment by srikarparsi** [comment] 2023-12-26 23:57
I believe @barttom is [fixing](https://github.com/Expensify/App/issues/32875#issuecomment-1868014118) this. Will take a look back towards the beginning of next week if there's no update

**Comment by srikarparsi** [comment] 2023-12-31 23:53
^

**Comment by srikarparsi** [comment] 2024-02-01 04:13
oh hold for payment

**Comment by srikarparsi** [comment] 2024-02-12 08:05
on hold

**Comment by srikarparsi** [comment] 2024-02-21 07:17
Was fixed [here](https://github.com/Expensify/App/pull/33863) and I made sure that this is no longer reproducible. Closing this out since it was handled by an external agency which I don't believe requires payment. But if it does, please reopen this issue or tag me.

**Closed by srikarparsi** 2024-02-21 07:17 UTC
Labels: Engineering, Weekly, Overdue, Awaiting Payment
