### ISSUE TITLE
[$500] Chat - When navigating to chat via URL, user has to tap on back arrow twice to return to LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40743] opened 2024-04-23 02:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4501393
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat and copy its URL
3. Return to LHN and navigate to the chat via URL
4. Tap on back arrow

## Expected Result:
User should redirected back to the LHN.

## Actual Result:
User remains in the chat, has to tap on back arrow once again to return to the LHN.
Also reproducible when logging in via conversation direct URL.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/ebe02ab7-4a95-42cf-bca4-ee229b085dcd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01178464ec2ad2a33e</li>
        <li>Upwork Job ID: 1782696560950165504</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2024-04-23 02:53
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment] 2024-04-23 02:53
We think this bug might be related to #vip-vsb

**Comment by mountiny** [comment] 2024-04-23 20:42
We are getting close to deploying, I am going to demote this issue because:
- only related to deeplinking to report in narrow view which is rare flow for a user in itself
- it seems to only be relevant to mWeb
- while annoying ux its not blocking the user from using the app
- its one off as once they are in the lhn and use the app it will work properly

**Comment by nkdengineer** [comment] 2024-04-24 08:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User remains in the chat, has to tap on back arrow once again to return to the LHN.
Also reproducible when logging in via conversation direct URL.

### What is the root cause of that problem?
When we open a report by deep link, we will navigate to the report here and it will call `linkTo` function.

https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/libs/actions/Report.ts#L2437

Let see this condition here. We're comparing the params object of `topmostCentralPaneRoute` and `action.payload.params?`. It's `true` when we open the report by deep link because `topmostCentralPaneRoute` has another param is `OpenOnAdminRoom` that is initialized [here](https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.tsx#L42) 

 
<img width="558" alt="Screenshot 2024-04-24 at 15 20 41" src="https://github.com/Expensify/App/assets/161821005/af59bcfd-1bdb-484e-a334-7ec245fc3baf">


https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/libs/Navigation/linkTo.ts#L156


That makes we move to this [case](https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/libs/Navigation/linkTo.ts#L163
) and then another report screen is opened because the `action.type` is `push` here. 


https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/libs/Navigation/linkTo.ts#L176
### What changes do you think we should make in order to solve the problem?
We should only compare the reportID param as we did in the past instead of comparing the value of `params` field and we can change this variable name to `areReportIDParamsDifferent`



```
const areReportIDParamsDifferent = getTopmostReportId(rootState) !== getTopmostReportId(stateFromPath);
```

or 

```
const areReportIDParamsDifferent = topmostCentralPaneRoute?.params?.reportID !== action.payload.params?.params?.reportID;

```
https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/libs/Navigation/linkTo.ts#L156


### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-04-24 08:35
Updated proposal to add alternative solution.

**Comment by eh2077** [comment] 2024-04-24 09:40
@nkdengineer Thanks for your proposal!

I agree with your RCA but I have concerns about your main solution - the `shallowCompare` function may also compare other properties of params like `filter`. I think the alternative solution you proposed fixes the root cause. Although this issue is uncovered by a recent [new feature](https://github.com/Expensify/App/pull/40280), the [root cause](https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.tsx#L41-L42) has been there for a while. 

That said, I think we can go with @nkdengineer 's [proposal](https://github.com/Expensify/App/issues/40743#issuecomment-2074389711).

🎀👀🎀 C+ reviewed

**Comment by abzokhattab** [comment] 2024-04-24 09:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report is opened twice when the user is logged in and navigates to it using deep-linking 
### What is the root cause of that problem?
 
when the user is already signed in and navigates to a report using deep linking, the [openReportFromDeepLink](https://github.com/Expensify/App/blob/91d22c1207b18562e138937119e92ae847446a2a/src/libs/actions/Report.ts#L2399-L2441) is executed. 


in this function we always navigate to the report ([here](https://github.com/Expensify/App/blob/91d22c1207b18562e138937119e92ae847446a2a/src/libs/actions/Report.ts#L2437)) even if the report is already opened 


### What changes do you think we should make in order to solve the problem?

we need to check if the report is already opened before calling a redundant navigation call, to do that we should use the `Navigation.getTopmostReportId`  [here](https://github.com/Expensify/App/blob/91d22c1207b18562e138937119e92ae847446a2a/src/libs/actions/Report.ts#L2436)  and check if its equal to the current `reportID` 

```JS
       const topmostReportId = Navigation.getTopmostReportId();
                if (topmostReportId === reportID) {
                    return;
                }
```

**Comment by abzokhattab** [comment] 2024-04-24 09:48
Hi @eh2077  would love to hear your feedback about my proposal as I think we shouldn't navigate to the report if its is already opened

**Comment by eh2077** [comment] 2024-04-24 10:05
@abzokhattab At the first glance, I'm not convinced your RCA and I have concerns about your solution - will it just avoid opening RHP screens? I could be wrong and I'll take a deeper look later. Sorry, I'll be offline in following hours.

**Comment by abzokhattab** [comment] 2024-04-24 10:38
> I'm not convinced your RCA 

i will clarify it more. thanks 


>  will it just avoid opening RHP screens?




The part inside the [InteractionManager.runAfterInteractions](https://github.com/Expensify/App/blob/91d22c1207b18562e138937119e92ae847446a2a/src/libs/actions/Report.ts#L2416-L2438) is intended for scenarios where an unauthenticated user accesses a private report using deeplinking (as mentioned in [this](https://github.com/Expensify/App/blob/91d22c1207b18562e138937119e92ae847446a2a/src/libs/actions/Report.ts#L2415) comment).  in this case, the user will be directed to the sign-in page and then be redirected to the report afterward 

However, this code does not account for situations where the user is already signed in or the report is public, in those cases the user won't be redirected to the sign-in page and the report will be already opened causing unnecessary navigation and thus opening the report twice.

Does that answer your question? please let me know

**Comment by nkdengineer** [comment] 2024-04-24 11:42
> Just a note here

The solution here https://github.com/Expensify/App/issues/40743#issuecomment-2074548351 will cause the regression if we open the sub page of report i.e. report detail page by deep link.

Actually, in `linkTo` function, we had the logic to replace or add a new screen when we navigate to a page that why this bug doesn't happen in the past with navigation logic in `openReportFromDeeplink` function . So we should fix the current wrong logic in this function.

**Comment by eh2077** [comment] 2024-04-25 16:33
@abzokhattab Thanks for your comment. I partially agreed with your RCA and I tested your solution. It fixes the issue and also avoids my concerns about opening RHP screens - the `reportID` is empty string `""` and `topmostReportId` is `undefined` when opening a RHP like report details page. But I still think it's not the best way to fix this issue in method `openReportFromDeeplink`.

**Comment by eh2077** [comment] 2024-04-25 16:44
@nkdengineer Thanks for sharing your thoughts!

> Actually, in linkTo function, we had the logic to replace or add a new screen when we navigate to a page that why this bug doesn't happen in the past with navigation logic in openReportFromDeeplink function . So we should fix the current wrong logic in this function.

Yes, I agreed with you. This issue is ideal to be fixed in the `linkTo` function. Just want to extend discussion about your solutions, can we fix this issue by improving the `shallowCompare` method? For example, let it omit parameter key with `undefined` value. Maybe this can be discussed in PR.

**Comment by eh2077** [comment] 2024-04-29 06:00
According to the discussions above^, I tend to stick to the original review decision https://github.com/Expensify/App/issues/40743#issuecomment-2074534777

@robertjchen All yours.

🎀👀🎀 C+ reviewed

**Comment by robertjchen** [comment] 2024-04-29 16:28
Appreciate the proposals and discussions here! 🙇 After reviewing, I think we will go with @nkdengineer 's proposal

**Comment by alexpensify** [comment] 2024-05-03 17:07
Weekly Update: Waiting for this one to go to Production

**Comment by alexpensify** [comment] 2024-05-07 19:04
Waiting for automation here

**Comment by alexpensify** [comment] 2024-05-13 21:56
@eh2077 - can you please confirm if there is any more action here? It looks like the automation didn't kick in, and I believe that the 7-day mark is today. I need to move forward with the payment process, but I want to double-check. Thanks!

**Comment by alexpensify** [comment] 2024-05-14 22:31
@nkdengineer - can you update me if there is any other action here? Thanks!

**Comment by eh2077** [comment] 2024-05-14 23:01
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40280
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40280/files#r1600762277
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
 [@eh2077] Determine if we should create a regression test for this bug. _**I don't think we need to add a regression for it**_


cc @alexpensify

**Comment by alexpensify** [comment] 2024-05-15 23:07
Payouts due: 2024-05-13 - delayed due to automation failure

- [ ] Contributor: $500 @nkdengineer 
- [ ] Contributor+: $500 @eh2077 

Upwork job is [here](https://www.upwork.com/jobs/~01178464ec2ad2a33e). This was treated as a High and is the reason for the payment amount. I've closed the job and paid everyone via Upwork.

**Closed by alexpensify** 2024-05-15 23:07 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
