### ISSUE TITLE
[HOLD for payment 2024-11-11] [Workspace Feeds] Create a loading state for creating card and provisioning a policy for cards

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50699] opened 2024-10-14 04:31 UTC
### Problems

Both - creating cards and provisioning a policy for Expensify cards - are tasks in the backend that rely on third-party services, and we cannot optimistically take these actions in the App. Right now, we do not wait for a successful response from the server, which in some cases (especially if the card program provisioning fails), leads to bad UX. 

Coming from [this thread](https://expensify.slack.com/archives/C036QM0SLJK/p1728591368825789?thread_ts=1728549946.385929&cid=C036QM0SLJK)

### Solution

Let's add a loading/ waiting/ spinner state for the user once they create a card or when they choose a VBBA bank account as a settlement bank account. We will wait for 200 successful API response before proceeding and if the call fails, we will show them the error message straight away and we won't lead them to failure on other commands. 

Can you please mock how these should look like? In case of provisioning the policy for cards, I think its such a rare moment its also work a celebration in the product so maybe some fireworks would be worth it there

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by mountiny** [comment] 2024-10-14 04:32
Sorry no need for b0 person

**Comment by dubielzyk-expensify** [comment] 2024-10-15 04:59
We should use the button + spinner combo for all places where we need to wait for the response:
![image](https://github.com/user-attachments/assets/8ff9343a-5d52-4644-81d9-9732d590d3ac)

As for the bank account selection flow we can either do the same and add a success screen:
![image](https://github.com/user-attachments/assets/cd40036a-6d09-4458-8029-5122bc0448df)

Or we could use the bank account illustration as a loading state:
![image](https://github.com/user-attachments/assets/bfd21a55-ab51-44ff-932d-a6197b57fd1d)

I think if the loading time is likely to be multiple seconds, then maybe use the bank account illustration. If it's relatively short, then use the loading button.

cc @Expensify/design for thoughts too

**Comment by shawnborton** [comment] 2024-10-15 06:47
Totally agree with that Jon. If we know it's typically at least a few seconds, let's use the animation instead of the loading spinner.

**Comment by dannymcclain** [comment] 2024-10-15 13:45
Also totally agree with Shawn and Jon above!

**Comment by mountiny** [comment] 2024-10-15 13:55
Agreed with Jon, Shawn and Danny.

@koko57 Would you want to take this one on?

**Comment by mountiny** [comment] 2024-10-15 13:56
Added the copy label here just so we can confirm the copy in the mocks above is what we are happy with

**Comment by jamesdeanexpensify** [comment] 2024-10-15 16:28
Also, is the `Verifying bank account...` screen meant to sit for a few seconds, **OR** is there a chance it will take a longer time via manual checks so they'll need a way out of that screen + a way to get notified whether or not their bank account was approved later on?

**Comment by koko57** [comment] 2024-10-16 03:41
@mountiny yep, of course! Happy to work on this one 🙂

**Comment by mountiny** [comment] 2024-10-16 04:03
The screens titled as bank account verified and verifying - that's where to confirm the copy please.

Yes there is a chance of manual verification needed, @koko57  that is the waitlist nvp btw

In that case the screen should lead them to concierge page. Then the card page will already have a modal pointing them to concierge

**Comment by mountiny** [comment] 2024-10-16 06:17
<img width="533" alt="image" src="https://github.com/user-attachments/assets/5a1b0cb5-cd33-466e-997f-10cc2f04a713">

These screens.

@dubielzyk-expensify I wonder then if we should have a special screen as the final one in case the bank account was put on a waitlist and we need to verify that manually. We should be able to check that by looking for the waitlist nvp and tell the user they have to go to concierge where there should already be a message with instructions

**Comment by koko57** [comment] 2024-10-16 09:00
@mountiny @jamesdeanexpensify I'm wondering - will we ever have the case that the account that is not verified (on the waitlist) will appear on the bank account list? ([comment](https://github.com/Expensify/App/issues/49472#issuecomment-2367678616)) Do we need any other validation? And for bank accounts we additionally filter out eligible bank accounts.

**Comment by mountiny** [comment] 2024-10-16 10:16
The waitlist is before you are provisioned for the expensify cards when you choose that bank account @madmax330 so I would say its possible

**Comment by dubielzyk-expensify** [comment] 2024-10-16 11:12
Can you explain what the waitlist means in simple terms? 😇 

But that being said, I think something like what we did for VBA could work:
![image](https://github.com/user-attachments/assets/f8b011f6-949b-46fb-8bf0-9ee044816d1e)

Just need confirm I've understood it correctly and likely @jamesdeanexpensify will have to fix my copy 😅

**Comment by shawnborton** [comment] 2024-10-16 12:59
Mock looks good to me though, nice one Jon!

**Comment by jamesdeanexpensify** [comment] 2024-10-16 15:52
Oh! Actually for the **One more step** screen - I remembered we discussed a similar screen [here](https://www.figma.com/design/9J4v6CzMVLQbzXMnXC5Izq/%23wave-collect%3A-Workspace-Card-Feeds?node-id=5926-18080&node-type=frame&t=r9tt8POxvKcZZhjH-0) @dubielzyk-expensify but I'm not sure which one we landed on. Could we just use whatever we used there, instead, to make things more consistent?

**Comment by dubielzyk-expensify** [comment] 2024-10-17 04:02
We could use similar language, but it sounds like this is one where they actually have to go to Concierge for next step? If there is a wait, then I agree, but from the wording above I interpreted it as next steps immediately available.

**Comment by koko57** [comment] 2024-10-17 09:12
ok, so for success screen I should use this image and this copy?
<img width="228" alt="Screenshot 2024-10-17 at 16 11 14" src="https://github.com/user-attachments/assets/9f60fc0f-2973-40cc-8062-ad3d1dc1958b">

and for the Veryfing step? Which design should I use?

**Comment by mountiny** [comment] 2024-10-17 09:39
@dubielzyk-expensify For waitlist, I think you got it right; we basically need more details from them about the business and the bank account before we can offer them the line of credit/ decide what the limit will be, and they need to talk to the concierge to provide those details. When they are put on this waitlist, they should get an automatic message in the concierge. We also already have a special view on the cards page when this happens so that will also guide them to concierge

Seems like we are sorted for this one right? @koko57

**Comment by mountiny** [comment] 2024-10-17 09:40
I think this one on the left for verifying 
![image](https://github.com/user-attachments/assets/5a975f02-7172-4a4e-91bf-846fb5b316b6) and then if the waitlist is added we show this one 
![image](https://github.com/user-attachments/assets/768ec7a5-88f4-4716-9058-ca8a20eba96b)

**Comment by koko57** [comment] 2024-10-17 12:06
May I ask for the puzzle illustration exported as SVG? I cannot find it in the project

**Comment by shawnborton** [comment] 2024-10-17 12:47
I think Jon might have signed off for the day, so here you go: [emptystate__puzzlepieces.svg.zip](https://github.com/user-attachments/files/17412633/emptystate__puzzlepieces.svg.zip)

It should be displayed at 148x154

**Comment by koko57** [comment] 2024-10-17 13:03
@shawnborton thanks a lot! 😊

**Comment by jamesdeanexpensify** [comment] 2024-10-17 15:55
Just making sure we're incorporating [these edits](https://github.com/Expensify/App/issues/50699#issuecomment-2417210145) to the copy. Is that right? Thanks!

**Comment by dubielzyk-expensify** [comment] 2024-10-18 04:08
Thank you Shawn!

**Comment by dubielzyk-expensify** [comment] 2024-10-21 08:25
Not overdue

**Comment by koko57** [comment] 2024-10-21 09:54
Sorry for the delay - still working on it, I had some other responsibilities that I needed to take care of in the meantime. Will do my best to open the PR for this issue today/tomorrow.

**Comment by mountiny** [comment] 2024-10-22 02:51
Thanks for the update

**Comment by shawnborton** [comment] 2024-10-22 10:46
[It's a Lottie animation ](https://github.com/Expensify/App/blob/main/assets/animations/Fireworks.lottie)

**Comment by koko57** [comment] 2024-10-22 12:44
ok, thanks for confirmation! I've already used that one 🙂 I still have to polish the logic and do some code clean-up, so unfortunately I won't be able to open the PR today, but it should be ready tomorrow.

**Comment by koko57** [comment] 2024-10-23 05:34
and another question - now we get 200 when the domain is properly provisioned and 200 with cardOnWaitlist otherwise - is there a possibility that we get an error? In such case should I also show the screen with the puzzle?

**Comment by koko57** [comment] 2024-10-23 07:58
I'm almost ready to open the PR but I have one problem. I'm getting this:
<img width="504" alt="Screenshot 2024-10-23 at 14 44 11" src="https://github.com/user-attachments/assets/3a5ec81f-7a47-41a5-9420-a3f99e77417e">
as a response from OpenPolicyExpensifyCardsPage when I open Expensify Card on a new workspace.

After I choose an account that was added to another workspace I get 
<img width="599" alt="Screenshot 2024-10-23 at 14 50 29" src="https://github.com/user-attachments/assets/2d24bfde-d6f4-485e-90c4-7aa19b865630"> the same response.

And the problem is - how can I differentiate between the state of verification to show either the bank account list to choose and the verification screen with the puzzle?

cc @mountiny

**Comment by mountiny** [comment] 2024-10-23 09:59
@koko57 I see where the issue is so I updated the waitlist nvp and Max will review https://github.com/Expensify/Auth/pull/12873

we will add the underscore too. 

There is a structure problem with the nvp though, essentially it only hold one waitlist information at a time for the particular user, so as you set up another domain that might get on the waitlist, the previous values are just overwritten by the new one. Its not a map per domain which is what we would need in this case

So for now it might wokr well for that one workspace which is a mainline case and we will look into how to make it scale better

**Comment by koko57** [comment] 2024-10-23 10:00
ok, I understand. So it's better to hold on opening PR here?

**Comment by mountiny** [comment] 2024-10-23 10:21
Nono, lets just go ahead, I think that what you ran into is very edge casey for normal user, they would set up the cards on one workspace and be done, most likely they would not try to set up the cards on multiple ones at the same time (being on a waitlist for multiple workspaces

**Comment by koko57** [comment] 2024-10-23 11:07
ok, so I will test it for a new user and a new workspace and will open the PR if everything is ok

**Comment by mountiny** [comment] 2024-10-23 11:51
Yes, but even for the existing user, the NVP would be correctly set after you try to setup the policy. 

I have made updated to the backend so we will return the nvp to the client only if the nvp is specific for the policy settings page you are seeing

**Comment by koko57** [comment] 2024-10-23 13:31
I was about to open the PR but I'm having a strange problem with the animation - it's not changing although it should. I also need to do some style improvements to make the content on the same height.  

https://github.com/user-attachments/assets/2cad5d5b-c93f-4920-9dfe-fa59d91c68a5

**Comment by koko57** [comment] 2024-10-23 14:08
BTW, maybe as a follow-up we could make this loader from VBBA flow similar to the one used here - I mean with centered content and a title text (but we would need a new copy)
<img width="366" alt="Screenshot 2024-10-23 at 21 03 20" src="https://github.com/user-attachments/assets/cec703e8-cfaf-4a1b-a871-578885d11616"><img width="309" alt="Screenshot 2024-10-23 at 21 07 04" src="https://github.com/user-attachments/assets/fcd9fd14-5996-4476-8f1f-f12a2e49ff32">

wdyt? @shawnborton @dubielzyk-expensify

**Comment by dannymcclain** [comment] 2024-10-23 14:46
Yes we definitely need to make it match the `Verifying` one in terms of styles/text layout/etc.

It also looks like the illustration and page title are knocked back or have an opacity set or something, which they shouldn't.

**Comment by shawnborton** [comment] 2024-10-23 18:29
Totally agree with both of you.

**Comment by koko57** [comment] 2024-10-24 11:34
I fixed the problem with Lottie animation not changing, although it's very strange that it didn't work properly when extracted to a separate component. I need to fix the styles and test it, and I'm opening PR shortly.

**Comment by bfitzexpensify** [comment] 2024-11-11 15:41
@mountiny is payment required here? I saw your [comment](https://github.com/Expensify/App/issues/50699#issuecomment-2409923789):

>Sorry no need for b0 person

**Comment by DylanDylann** [comment] 2024-11-11 15:49
@mountiny The PR was created after we handled the payment for the project

**Comment by DylanDylann** [comment] 2024-11-11 15:52
In this time (after settling payment for the project), there is only me working as C+ on all issues. So that, could we handle this issue separately?

**Comment by DylanDylann** [comment] 2024-11-12 11:18
@mountiny What do you think about my above comment?

**Comment by bfitzexpensify** [comment] 2024-11-13 17:26
Offer sent @DylanDylann

**Comment by DylanDylann** [comment] 2024-11-13 17:35
@bfitzexpensify Accepted, TY!

**Comment by bfitzexpensify** [comment] 2024-11-13 17:41
Paid out!

**Closed by bfitzexpensify** 2024-11-13 17:41 UTC
Labels: Daily, Design, Waiting for copy, Awaiting Payment
