### ISSUE TITLE
HOLD #12650 [$250] [mWeb/Android] keyboard hides when long press on keyboard reported by @gadhiyamanan 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12324] opened 2022-10-31 23:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Write something
3. Long press on send button

## Expected Result:
Keyboard should not hide

## Actual Result:
Keyboard hides

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web (Android) 

**Version Number:** 1.2.22-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** https://user-images.githubusercontent.com/43996225/199126158-ac5b1d67-ce20-4f38-8747-f0c3e1427f08.mp4

https://user-images.githubusercontent.com/43996225/199126178-d52889ae-fa2a-410a-b343-5ffbf6c5a5d8.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667223139479689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment] 2022-11-01 14:44
Hmm what do we expect out of long-pressing the send button? I'm guessing we should send like it was a press?

**Comment by gadhiyamanan** [comment] 2022-11-01 17:08
I think on long press we should send message as we are doing that in Android and iOS native https://user-images.githubusercontent.com/54790231/199293654-71111e46-05bf-4d1e-90db-31aeb387af25.mp4

**Comment by mallenexpensify** [comment] 2022-11-05 15:20
Bumped back to daily per our new BugZero process, [internal Slack thread with deets](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109)

**Comment by sophiepintoraetz** [comment] 2022-11-07 00:28
@johnmlee101 -bumping for your thoughts here so that we can get this assigned `External` or `Internal`

**Comment by johnmlee101** [comment] 2022-11-08 23:28
Seems good let's mark it!

**Comment by sophiepintoraetz** [comment] 2022-11-08 23:48
[Job posted](https://www.upwork.com/jobs/~0160642490e8b87d90)

**Comment by sophiepintoraetz** [comment] 2022-11-11 02:17
@gadhiyamanan - did you have a proposal for how we can fix this?

**Comment by Emz27** [comment] 2022-11-15 18:28
https://github.com/Expensify/App/issues/12650#issuecomment-1315699265

**Comment by parasharrajat** [comment] 2022-11-15 20:52
Reviewing the proposals. What about we just prevent the longPress on the button?

**Comment by sophiepintoraetz** [comment] 2022-11-15 21:04
I think we can put this issue on hold and see if it's resolved by #12650, given that still has the momentum. @gadhiyamanan will still receive the reporting bonus in that case given that it was reported by them first.

**Comment by sophiepintoraetz** [comment] 2022-11-17 03:23
Going to close this one out as a dupe of https://github.com/Expensify/App/issues/12650

**Closed by sophiepintoraetz** 2022-11-17 03:23 UTC
Labels: External, Engineering, Weekly, Bug
