### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Extra spaces are not trimmed in the next page for the routing number and Account number

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43135] opened 2024-06-05 17:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allgandalf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717537508312169

## Action Performed:

1. Go to a workspace
2. Enable workflows
3. Click on connect bank account
4. Select manual and enter the account details as : 011401533 and account number 1111222233331111 give some space before both these numbers and press next

## Expected Result:
Spaces are trimmed in the confirmation page
## Actual Result:
Spaces are present on the confirmation page, we should trim them while saving as a account number cannot have spaces before or after.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/a49126cb-5c86-4581-9bb4-f01981c4cd23

https://github.com/Expensify/App/assets/38435837/8c4919cb-0a0f-4397-81c2-f246536db5e7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134151ac2072ab6de</li>
        <li>Upwork Job ID: 1798588655835680495</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 102633932</li>
<li>Krishna2323 | Contributor | 102704572</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify / @Christinadobrzyn</details>

**Comment by Christinadobrzyn** [comment] 2024-06-06 05:32
@allgandalf I'm going to add the lable so it's fair share but we can ask the assigned C+ if you can take it.

**Comment by Christinadobrzyn** [comment] 2024-06-06 05:33
Hey @ahmedGaber93 - would you mind if @allgandalf took over as C+ since they reported this issue and have some more context?

**Comment by ahmedGaber93** [comment] 2024-06-06 05:41
> Hey @ahmedGaber93 - would you mind if @allgandalf took over as C+ since they reported this issue and have some more context?

@Christinadobrzyn Yeah, that's fair. Please unassign me and assign @allgandalf.

**Comment by iwiznia** [comment] 2024-06-11 14:13
> useStepFormSubmit saves the trimmed value (that is passed by FormProvider onSubmit) as the new draft.

I don't see this component trimming the values, @Krishna2323 can you point out where that component would trim the value?

**Comment by Christinadobrzyn** [comment] 2024-06-12 07:12
Just a heads up - I'm going to be ooo until June 24th so going to assign a teammate to watch this while I'm away. 

@MitchExpensify we are discussing the proposals - https://github.com/Expensify/App/issues/43135#issuecomment-2160876506

**Comment by iwiznia** [comment] 2024-06-12 14:07
Got it.

**Comment by MitchExpensify** [comment] 2024-06-24 00:36
*Payment summary*:

- $250 @Krishna2323 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102704572) (Contributor)
- $250 @allgandalf requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102633932) (Contributor)

**Comment by Christinadobrzyn** [comment] 2024-06-28 20:48
There are no regressions, so I'm paying this out based on this payment summary  - https://github.com/Expensify/App/issues/43135#issuecomment-2185388708

@allgandalf can you let us know about a regression test?

**Comment by Christinadobrzyn** [comment] 2024-07-01 18:03
Regression test here - https://github.com/Expensify/Expensify/issues/409420

Payment summary here - https://github.com/Expensify/App/issues/43135#issuecomment-2185388708

Closing as complete!

**Closed by Christinadobrzyn** 2024-07-01 18:03 UTC
Labels: External, Daily, Bug
