### ISSUE TITLE
[HOLD for payment 2024-06-03] [$500] IOU - Creating IOU Distance offline with incomplete addresses results in incorrect error message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38213] opened 2024-03-13 11:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4418303
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Preconditions:
Set up an OldDot admin account, invite the employee to the policy https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?authuser=0

Steps:
1. Open https://staging.new.expensify.com/
2. Log in with the account of the employee added to the policy
3. Navigate to the WS room
4. Compose Box > Request Money
5. Select Distance option
6. Disable the internet connection
7. Enter a vague start location like "Fake"
8. Enter a vague finish location like "Blah blah"
9. Finish the request creation flow

## Expected Result:
The error "No route found through the waypoints. Please edit the waypoints and try again." Should be shown in the UI.

## Actual Result:
The error "Unexpected error requesting money, please try again later" is shown in the UI.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9f020cb7-bcd0-416e-a283-f52e109c5a45

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df4bc3e1ba142b9b</li>
        <li>Upwork Job ID: 1767941481061400576</li>
        <li>Last Price Increase: 2024-04-24</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by izarutskaya** [comment] 2024-03-13 11:12
@lakchote I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-13 11:13
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by izarutskaya** [comment] 2024-03-13 11:14
Production video 


https://github.com/Expensify/App/assets/115492554/ba0d8027-7b5a-4085-b3c2-e1bbd037b337

**Comment by trjExpensify** [comment] 2024-03-13 14:32
Looks like a deploy blocker to me!

**Comment by lakchote** [comment] 2024-03-13 15:30
I can't reproduce on dev.

Might be related to [these](https://github.com/Expensify/App/pull/36407/files#diff-15c9e14f2042c455d3b1cb7f96b4b08be83df4e3590ea8d7a2b52794ad02cd30L155) changes

**Comment by lakchote** [comment] 2024-03-13 15:50
> @lakchote I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

It's a frontend issue, and as such I'm opening it to external contributions.

**Comment by luacmartins** [comment] 2024-03-13 15:52
@lakchote this is a deploy blocker. Since this is the end of your day, can we find an internal engineer to keep pushing this forward?

**Comment by tgolen** [comment] 2024-03-13 17:28
I don't think this is a deploy blocker or a backend issue.

If I use the addresses "SF" and "LA", then the backend is able to come up with a route that goes from San Francisco to Lousiana (which is feasible). So, I think those are valid addresses.

When I use the addresses "fake" and "blah blah", the server returns an error `No route found through the waypoints. Please edit the waypoints and try again.`

<details>
<summary>Full API response</summary>

```
{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Libs\\Error\\ExpError",
    "UUID": "5C7EDD2F-FAC9-4795-AA2D-383D7E053F9D",
    "message": "No route found through the waypoints. Please edit the waypoints and try again.",
    "title": "",
    "data": {
        "onyxData": [
            {
                "onyxMethod": "merge",
                "key": "transactions_1747048417427960048",
                "value": {
                    "errorFields": {
                        "route": {
                            "1710350682438627": "No route found through the waypoints. Please edit the waypoints and try again."
                        }
                    }
                }
            }
        ]
    },
    "htmlMessage": "",
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "transactions_1747048417427960048",
            "value": {
                "errorFields": {
                    "route": {
                        "1710350682438627": "No route found through the waypoints. Please edit the waypoints and try again."
                    }
                }
            }
        }
    ],
    "requestID": "Zxpu95"
}
```

</details>


![image](https://github.com/Expensify/App/assets/1228807/af4409aa-6d41-426a-a62e-701c6cc6395a)

What I think needs to be fixed here is that the UI is not displaying the error that is returned from the server, and instead, it's displaying some generic error.

I'm going to remove the deploy blocker label, and update the description of the issue.

**Comment by bernhardoj** [comment] 2024-03-14 05:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The distance route error shows a generic message instead of the message that is returned from the BE.

### What is the root cause of that problem?
When the distance request fails, we set a generic error message to the report action.
https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/libs/actions/IOU.ts#L759-L763

The BE returns an error message that is set to the transaction instead of the report action, and we don't use this error from transaction as the error of the report action.
https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/pages/home/report/ReportActionItem.tsx#L821-L828

### What changes do you think we should make in order to solve the problem?

Subscribe to the transaction of the report action and add the transaction error to the OfflineWithFeedback error.
```
errors={linkedTransaction?.errorFields?.route ?? ErrorUtils.getLatestErrorMessageField(action as ErrorUtils.OnyxDataWithErrors)}
...
linkedTransaction: {
    key: ({action}) => `${ONYXKEYS.COLLECTION.TRANSACTION}${action.originalMessage?.IOUTransactionID ?? 0}`,
},
```
<img width="496" alt="image" src="https://github.com/Expensify/App/assets/50919443/bef3542c-947e-4737-aac9-bacf30199911">

_This will show the BE error for individual money request action, but the report preview will still show the generic error message. If we want to show the error for report preview too, we need to subscribe to the transaction collection which degrades the performance of the app because we are subscribing each action to a transaction collection._

**Comment by lakchote** [comment] 2024-03-18 07:49
@abdulrahuman5196 can you please review proposals?

**Comment by abdulrahuman5196** [comment] 2024-03-18 07:52
Hi will review today

**Comment by abdulrahuman5196** [comment] 2024-03-20 14:18
REviewing now

**Comment by laurenreidexpensify** [comment] 2024-03-21 10:24
bump @abdulrahuman5196 did you complete review? Thanks

**Comment by abdulrahuman5196** [comment] 2024-03-21 12:15
Not yet. I was having trouble checking the API response. 
I will complete within a day.

**Comment by laurenreidexpensify** [comment] 2024-03-21 14:19
@trjExpensify adding to wave-collect as a distance bug

**Comment by abdulrahuman5196** [comment] 2024-03-26 13:23
Reviewing now. Will provide update soon.

**Comment by abdulrahuman5196** [comment] 2024-03-26 17:52
@usman-ghani564 @bernhardoj @tienifr 
I am not sure on the root cause. I tested the flow and was able to reproduce the issue.

But I was checking the network tab, but couldn't see the `CreateDistanceRequest` itself. Tried couple of times as well.
Who is sending the error in this? I assume somewhere from mapbox. Do let me know if I am missing something here.

<img width="1135" alt="Screenshot 2024-03-26 at 9 41 01 PM" src="https://github.com/Expensify/App/assets/46707890/a40a808e-dc9a-4f74-837d-a966e5148246">

**Comment by bernhardoj** [comment] 2024-03-27 03:20
It's from CreateDistanceRequest.
<img width="563" alt="image" src="https://github.com/Expensify/App/assets/50919443/406126de-9786-48ea-9db3-0726d83c21c8">

**Comment by abdulrahuman5196** [comment] 2024-04-01 08:32
Looking into this again based on the above input

**Comment by abdulrahuman5196** [comment] 2024-04-03 16:24
Sorry for the delay checking now

**Comment by abdulrahuman5196** [comment] 2024-04-03 17:34
At @nexarvo 's proposal here https://github.com/Expensify/App/issues/38213#issuecomment-1996076076, it seems you are setting the waypoint error if the request is simply distance request. But the server could have different errors right, for the distance request? How would you handle that case?

**Comment by abdulrahuman5196** [comment] 2024-04-03 17:54
On @tienifr 's solution here https://github.com/Expensify/App/issues/38213#issuecomment-1997308997, I am not sure if checking the errors and adding it to different objects is the good path. I would like to see if we get any better approaches than this.

**Comment by abdulrahuman5196** [comment] 2024-04-07 19:46
We don't have proposals to approve yet.

**Comment by abdulrahuman5196** [comment] 2024-04-10 16:34
Checking now.

**Comment by abdulrahuman5196** [comment] 2024-04-10 16:47
> > I am not sure if checking the errors and adding it to different objects is the good path. I would like to see if we get any better approaches than this.
> 
> @abdulrahuman5196 I don't think there's any better approach than this.
> 
> Why do you think my approach might not be a good path to solve the issue? I think it's quite clean and straight forward.

I don't think it is not a good path, it is a good solution, Just seeing if we get any better solutions. I was not inclined totally towards setting up listener changes. But anyways seeing we don't have any different solutions. We should go with the best we have now.


Could you share any pseudo code to test on your solution?

**Comment by lakchote** [comment] 2024-04-11 06:20
> @bernhardoj In you proposal as you have pointed out,
> 
> `If we want to show the error for report preview too, we need to subscribe to the transaction collection which degrades the performance of the app because we are subscribing each action to a transaction collection.`
> 
> We would need this fixed at both report preview and request page also. Do you think of any optimised way for this?

cc @bernhardoj

**Comment by abdulrahuman5196** [comment] 2024-04-12 16:33
> > > I am not sure if checking the errors and adding it to different objects is the good path. I would like to see if we get any better approaches than this.
> > 
> > 
> > @abdulrahuman5196 I don't think there's any better approach than this.
> > Why do you think my approach might not be a good path to solve the issue? I think it's quite clean and straight forward.
> 
> I don't think it is not a good path, it is a good solution, Just seeing if we get any better solutions. I was not inclined totally towards setting up listener changes. But anyways seeing we don't have any different solutions. We should go with the best we have now.
> 
> Could you share any pseudo code to test on your solution?

@tienifr ?

**Comment by lakchote** [comment] 2024-04-15 08:41
Please let's get this moving, cc @abdulrahuman5196 @tienifr (see question from @abdulrahuman5196  [here](https://github.com/Expensify/App/issues/38213#issuecomment-2052092236))

**Comment by bernhardoj** [comment] 2024-04-16 04:30
As we're not showing the error message anymore on the report preview, I updated my [proposal](https://github.com/Expensify/App/issues/38213#issuecomment-1996546186) to remove my comment about report preview and include showing the error on the transaction thread.

**Comment by lakchote** [comment] 2024-04-17 12:36
Thank you contributors for your reactiveness.

cc @abdulrahuman5196 could you please review them again?

**Comment by lakchote** [comment] 2024-04-18 15:13
> Thank you contributors for your reactiveness.
> 
> cc @abdulrahuman5196 could you please review them again?

friendly bump @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2024-04-23 11:34
Checking now

**Comment by laurenreidexpensify** [comment] 2024-04-25 11:45
@abdulrahuman5196 any conclusions? thanks

**Comment by abdulrahuman5196** [comment] 2024-04-29 12:24
Checking again. Not conclusions yet. Will close out today

**Comment by abdulrahuman5196** [comment] 2024-05-01 14:16
@bernhardoj 's proposal here https://github.com/Expensify/App/issues/38213#issuecomment-1996546186 looks good and works well as per the new expectation here https://github.com/Expensify/App/issues/38213#issuecomment-2056079350 and https://github.com/Expensify/App/issues/38213#issuecomment-1995092834

🎀 👀 🎀
C+ Reviewed

**Comment by tgolen** [comment] 2024-05-01 15:30
That proposal looks fine to me. @bernhardoj Can you please be sure to use a selector when connecting to that transaction so that it's only subscribing to the `transaction.error` property? I think that's the only one you need.

**Comment by bernhardoj** [comment] 2024-05-02 05:55
PR is ready

cc: @abdulrahuman5196

**Comment by laurenreidexpensify** [comment] 2024-05-07 10:20
@abdulrahuman5196 do you still have capacity for C+ on this one or can I reassign?

**Comment by abdulrahuman5196** [comment] 2024-05-07 12:24
> @abdulrahuman5196 Could you give some feedback on [my proposal](https://github.com/Expensify/App/issues/38213#issuecomment-1997308997)?
> 
> > Without the proper error clearing (in report action, IOU report createChat) here, when clearing the route error in the transaction thread, the user will see an undismissable RBR error in the report preview.
> 
> bernhardoj's solution will have the above problem (mentioned and solved in my proposal)

Given the expectation change, your proposal seemed to be an extended fix of Bernhardoj's solution. That why went with the solution which came first.

Regarding the error clearing issue, it is an extended fix of the core issue(showing proper error in this case) which would be mostly handled in PR state.

**Comment by tgolen** [comment] 2024-05-08 16:41
I can understand and agree with both sides. Ultimately, I'd like to see the most complete fix (the right error message AND being able to clear it) and I'm less interested about who does it or how it gets done :D 

@tienifr If you'd like to open a new bug report for not being able to clear the error, I'd support just assigning it to you and have you fix it. Would that work?

**Comment by abdulrahuman5196** [comment] 2024-05-08 17:39
Hi, to mention we are clearing the error in the PR raised. In the PR, the error is shown properly and cleared properly AFAIK.

But basically the fix to clear the error is considered as an extended solution or improvement to the core fix which is showing the proper error(as per OP). Afaik we select the original proposal which suggested the core fix if the improvements could/would have handled in the PR state. Because multiple improvements can be made on any selected proposal on any issue. In this case, clearing of error would have been mostly handled in the PR state.

**Comment by tgolen** [comment] 2024-05-08 18:01
Yeah, I agree with that too. It's not always a given that stuff like that gets caught in the PR which is why I can see both sides to it. If it is caught and addressed in this PR, then let's just move forward with the single PR like it is.

**Comment by laurenreidexpensify** [comment] 2024-05-20 12:20
@abdulrahuman5196 can you give an update of status of this issue? thank you

**Comment by laurenreidexpensify** [comment] 2024-06-04 11:25
Payment Summary: 

C+ @abdulrahuman5196 $500 paid in upwork 
Contributor @bernhardoj $500 paid in upwork

**Comment by laurenreidexpensify** [comment] 2024-06-04 11:26
@abdulrahuman5196 please confirm checklist above so we can close this out thanks

**Comment by abdulrahuman5196** [comment] 2024-06-04 19:53
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Open a workspace chat
2) Have at least 1 request
3) Go offline
4) Create a new distance request with invalid waypoints
5) Go online
6) Open the expense report
7) Verify there is an invalid waypoint error message below the money request preview
8) Open the transaction thread
9) Verify there is an invalid waypoint error message below the distance map image

@laurenreidexpensify

**Closed** 2024-06-05 09:56 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
