### ISSUE TITLE
[$250] [HOLD for payment 2024-07-10] Split bill - New group is created when splitting bill with the same users

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40579] opened 2024-04-19 15:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4496719
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Issue reported by:** Applause - Internal Team
 

## Action Performed:
1. Click on FAB > and create a split bill with two new users
2. Click on FAB > and create another split bill the same two users you have created with on step one

## Expected Result:
New group shouldn't be created, and the split bill should be added to the existing group

## Actual Result:
A second, new group is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b4527362-dcdf-4103-b3f0-a566fba97660

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9e84f7fad619cd5</li>
        <li>Upwork Job ID: 1811859168529416327</li>
        <li>Last Price Increase: 2024-07-12</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-19 15:22
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-04-19 15:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split bill - New group is created when splitting bill with the same users

### What is the root cause of that problem?
We are not checking if the group chat exists or not before creating here
https://github.com/Expensify/App/blob/9b2c5187e2203d83bba50bfa66936691788cbd18/src/libs/actions/IOU.ts#L3104-L3119
### What changes do you think we should make in order to solve the problem?

We should check if it already exists in onyx
```
   if (participants.length > 1) {
        const existing = ReportUtils.getChatByParticipants(allParticipantsAccountIDs, true) ?? null;
        const splitChatReport =
            !existing &&
            ReportUtils.buildOptimisticChatReport(
                allParticipantsAccountIDs,
                '',
                CONST.REPORT.CHAT_TYPE.GROUP,
                undefined,
                undefined,
                undefined,
                undefined,
                undefined,
                undefined,
                CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN,
            );
        return {existingSplitChatReport: existing, splitChatReport: existing ?? splitChatReport};
    }
```
### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-04-19 16:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split bill - New group is created when splitting bill with the same users
### What is the root cause of that problem?
New feature
### What changes do you think we should make in order to solve the problem?
Update [this](https://github.com/Expensify/App/blob/09ad46816dcd944cafd041e6626c15bb6dbc1527/src/libs/actions/IOU.ts#L3582) line as follows `getChatByParticipants(participants) || ''` 

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-04-19 16:22
[Updated](https://github.com/Expensify/App/issues/40579#issuecomment-2066862070) Only to add a refactored code for same solution

**Comment by joekaufmanexpensify** [comment] 2024-04-19 19:55
I think this report is going to be obviated by a feature refactor we're working on. [Discussing. ](https://expensify.slack.com/archives/C05RECHFBEW/p1713556484718769)

**Comment by joekaufmanexpensify** [comment] 2024-04-22 13:32
Not overdue

**Comment by joekaufmanexpensify** [comment] 2024-04-24 13:32
Bumped 1:1

**Comment by joekaufmanexpensify** [comment] 2024-04-25 14:17
[Flagged again](https://expensify.slack.com/archives/C05RECHFBEW/p1714054599762549?thread_ts=1713556484.718769&cid=C05RECHFBEW) in Slack. This is definitely #vip-split related. But don't want to make external just yet since I feel like there is a solid chance we will close this.

**Comment by youssef-lr** [comment] 2024-04-25 18:43
@joekaufmanexpensify I'll take a look at the proposals tomorrow.

**Comment by joekaufmanexpensify** [comment] 2024-04-26 13:58
Great. TY!

**Comment by joekaufmanexpensify** [comment] 2024-04-30 14:24
Still pending

**Comment by youssef-lr** [comment] 2024-05-01 00:13
I will get to this this week

**Comment by joekaufmanexpensify** [comment] 2024-05-02 13:11
Great. TY!

**Comment by joekaufmanexpensify** [comment] 2024-05-06 13:06
@youssef-lr will you have a chance to circle back to this soon? If you think we should definitely change this behavior, also happy to assign a C+ so they do preliminary review for you

**Comment by joekaufmanexpensify** [comment] 2024-05-07 14:08
@youssef-lr making this external for now so we can start to look at the proposals. When you have a sec, could you confirm if the solution in OP of the issue is what you wanted from the design doc?

**Comment by joekaufmanexpensify** [comment] 2024-05-08 13:51
@Ollyws yeah the split button did move to FAB, but I still get the same result when I try and reproduce. Splitting two expenses with the same two people creates a new group each time. Is that what you did to get that error?

**Comment by tsa321** [comment] 2024-05-09 10:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Split bill always making new report despite existing group chat with same paritcipants.

### What is the root cause of that problem?

In here:

https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/libs/actions/IOU.ts#L3604-L3606

the `ReportUtils.getChatByParticipants` won't be called because `shouldGetOrCreateOneOneDM` will be false if number of participant of splited bill more than 2 (including user that make split bills). So `shouldGetOrCreateOneOneDM` will only be true if we split bills with exactly one other user.
Then `ReportUtils.getChatByParticipants` won't be called and existingSplitChatReport will be undefined or null, then create new report in here:

https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/libs/actions/IOU.ts#L3620

-----------
and another problem if we disable shouldGetOrCreateOneOneDM check, and do `getChatByParticipants`, the call to the function isn't including self/current account id. so it just pass other participant without ownself/current user (user that create split bill):

https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/libs/actions/IOU.ts#L3606

------------
and another problem in `getChatByParticipants` function: 

https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/libs/ReportUtils.ts#L5151 

it won't check on group report.

### What changes do you think we should make in order to solve the problem?

I think we need to add parameter `currentUserAccountID` if we use `ReportUtils.getChatByParticipants` and we need to investigate why the function won't check on groupChat:

https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/libs/ReportUtils.ts#L5151 

if we can disable this check then we can use this function. 
If we cannot disable this check (because of regression if we disable it) then we can create new function  `getGroupChatByParticipants` and use it in `getOrCreateOptimisticSplitChatReport` function instead of ReportUtils.getChatByParticipants.

Also we need to investigate why:

https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/libs/actions/IOU.ts#L3605

`shouldGetOrCreateOneOneDM` condition will be false if number split bill participant is more than 1. 
I think we can disable this check but, further investigation on git blame will give some information .

**Comment by joekaufmanexpensify** [comment] 2024-05-09 14:19
Still discussing behavior here

**Comment by tsa321** [comment] 2024-05-10 12:39
@Ollyws the error is because the app create new report every time when splitting bills from `+ FAB button -> spliting bills`.
The server will returns error, because we must use existing group report with same split bill participant and don't create new report.

If you can check [my proposal](https://github.com/Expensify/App/issues/40579#issuecomment-2102407450).
And here is the result:

<details> <summary> Result: </summary>

https://github.com/Expensify/App/assets/114975543/018d4364-e29d-4e57-b629-3cd2d69536ec

</details>

**Comment by joekaufmanexpensify** [comment] 2024-05-13 13:52
Still pending further discussion

**Comment by joekaufmanexpensify** [comment] 2024-05-14 15:23
TY!

**Comment by joekaufmanexpensify** [comment] 2024-05-15 14:28
@Ollyws any update on this?

**Comment by ShaheFS** [comment] 2024-05-17 10:51
@Ollyws Could you please give a feedback about my proposal ?

**Comment by shahinyan11** [comment] 2024-05-17 10:52
@Ollyws Could you please give a feedback about my proposal ?

**Comment by joekaufmanexpensify** [comment] 2024-05-17 13:54
Pending sign off from @youssef-lr

**Comment by joekaufmanexpensify** [comment] 2024-05-20 13:54
@FitseTLT please share ETA for a PR

**Comment by joekaufmanexpensify** [comment] 2024-05-21 15:13
@FitseTLT is there an ETA for a PR here?

**Comment by FitseTLT** [comment] 2024-05-21 20:22
PR is ready

**Comment by joekaufmanexpensify** [comment] 2024-06-03 13:41
PR awaiting review from @youssef-lr

**Comment by youssef-lr** [comment] 2024-06-06 17:17
on it today @FitseTLT

**Comment by joekaufmanexpensify** [comment] 2024-06-10 13:52
Still pending review from @youssef-lr

**Comment by joekaufmanexpensify** [comment] 2024-06-14 20:50
@youssef-lr Is this issue on hold now because of the change in project status?

**Comment by joekaufmanexpensify** [comment] 2024-07-08 13:44
@Ollyws mind tackling the checklist here so we can prep to issue payment?

**Comment by marcaaron** [comment] 2024-07-09 19:13
@joekaufmanexpensify Hmm sorry, this is actually the expected behavior and not a bug. This issue seems like a miscommunication. 

@youssef-lr I think we should revert the PRs that "fixed" this? 

Where was it decided that we would change this behavior?

I think it's going to be quite weird since if you happen to have the chat locally it would use the "existing group", but if you don't (e.g. in focus mode or soon pagination) then we will create a "new" group. Basically, all FAB flows create a new group always. If you want to split with the same people then you split via the `+` in the composer on the chat itself.

**Comment by joekaufmanexpensify** [comment] 2024-07-10 13:13
Hey @marcaaron, the slack thread where it was discussed is a bit higher up in the issue, also [here](https://expensify.slack.com/archives/C05RECHFBEW/p1713556484718769). The consensus from those working on the uneven splits project at the time was that we should change this behavior. If we no longer agree with that and want to revert it, no issues with me. 

>but if you don't (e.g. in focus mode or soon pagination) then we will create a "new" group. Basically, all FAB flows create a new group always. If you want to split with the same people then you split via the + in the composer on the chat itself.

I don't think this piece was considered at the time. My 2c is if I have an existing chat with the exact same group, I would personally expect a split from FAB to go in that chat, whether or not you happen to have the chat locally. But if the standard for FAB actions is to consistently create a new group always, then makes sense to me that we'd keep the actions consistent.

**Comment by marcaaron** [comment] 2024-07-10 18:37
Ok thanks, sorry, I missed that discussion and those links.

>I would personally expect a split from FAB to go in that chat, whether or not you happen to have the chat locally. But if the standard for FAB actions is to consistently create a new group always, then makes sense to me that we'd keep the actions consistent.

Yeah, I think this is the part that is confusing for me? If we are OK with having that inconsistency then that's fine. I think we fundamentally changed (or maybe "broke") our previous design with Group Chats. My 2 cents, if we want to give users the ability to split with an _existing group_ then we should return Groups in the list of available options to split with and not auto select or create a new group depending on whether that group exists locally (which may not exist due to varying factors outside of the control of the user).

**Comment by joekaufmanexpensify** [comment] 2024-07-10 21:26
That's fair! I see the argument of doing as you suggest, as it does seem a bit odd to have this one option with groups behave differently from every other option on FAB. I think that kinda matches my initial thoughts on this in [OP of that slack thread](https://expensify.slack.com/archives/C05RECHFBEW/p1713556484718769) too. But I am not super close to this project, so deferred to those working on the project. 

@arielgreen / @youssef-lr what do you both think?

**Comment by joekaufmanexpensify** [comment] 2024-07-12 20:20
We landed on leaving this as is in Slack. We may change this again in the future, but this project is paused now, so no need to do that now.

**Comment by joekaufmanexpensify** [comment] 2024-07-12 20:23
Checklist is all set. Good to issue payment. We need to pay: 

- @FitseTLT - $250 for PR via Upwork. 
- @Ollyws - $250 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment] 2024-07-12 20:25
@FitseTLT offer sent for $250!

**Comment by joekaufmanexpensify** [comment] 2024-07-12 20:25
@Ollyws please request $250 via NewDot whenever you're ready!

**Comment by FitseTLT** [comment] 2024-07-12 20:49
> @FitseTLT offer sent for $250!

Accepted

**Comment by joekaufmanexpensify** [comment] 2024-07-12 20:55
@FitseTLT $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-07-12 20:55
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-07-12 20:56
Closing for now, as only thing left here is for @Ollyws to request their payment. Payment summary is [here](https://github.com/Expensify/App/issues/40579#issuecomment-2226302456) as FYI.

**Comment by joekaufmanexpensify** [comment] 2024-07-12 20:56
Thanks everyone!

**Closed by joekaufmanexpensify** 2024-07-12 20:56 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-16 00:14
$250 approved for @Ollyws
