### ISSUE TITLE
[$250]  Xero - Unable to change Xero bank account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46347] opened 2024-07-27 01:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app
2. Log in with a new account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to Xero
7. Navigate to Accounting - Export - Xero bank account
8. Select any of the accounts

## Expected Result:
I should be able to change Xero bank account

## Actual Result:
I'm unable to change Xero bank account. After choosing a new one, the input clears and a few seconds later the default one appears again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/cb547d5b-63f2-49e2-b691-9a0e86fd67b4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01280db714da683fda</li>
        <li>Upwork Job ID: 1817974646767184922</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>

**Comment by lanitochka17** [comment] 2024-07-27 01:45
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-27 01:45
We think that this bug might be related to #wave-collect - Release 2

**Comment by hungvu193** [comment] 2024-07-30 03:25
Posted an update on Slack, this looks like a BE issue (https://expensify.slack.com/archives/C036QM0SLJK/p1722307989215409?thread_ts=1722273937.109659&cid=C036QM0SLJK)

**Comment by m-natarajan** [comment] 2024-08-05 13:01
Issue is still reproducible by the original tester.

https://github.com/user-attachments/assets/12e3cd3b-5f4d-42b0-9029-f49fc7273034

**Comment by puneetlath** [comment] 2024-08-05 17:00
Ok, so it looks like this is an issue with the pusher event that gets sent after the action is taken. Not the API response itself. So I'm making it an internal issue and hot-pick in #wave-collect.

**Comment by yuwenmemon** [comment] 2024-08-19 15:46
I think this might be a similar problem to https://github.com/Expensify/App/issues/45201 since this reset is coming from the integration server.

If I comment out the sync in `updatePolicyConnectionConfiguration` then this does not happen.

**Comment by yuwenmemon** [comment] 2024-08-19 15:55
Oh, hmmm, but even after running a sync 5 min later, it still resets... that's not good 😬

**Comment by yuwenmemon** [comment] 2024-08-19 16:37
Looks like these are the lines that are throwing an Invalid Connection Format and then we go to the defaults: 
https://github.com/Expensify/Integration-Server/blob/f2f3c959c4fbbae22e0a78d2ea450825b31429e9/src/expensify/beans/expensify/policy/integration/xero/XeroConfiguration.java#L368-L370

**Comment by yuwenmemon** [comment] 2024-08-19 16:40
Oh hm looks like we're completely overwriting the config object when we update the bank account for some reason:
<img width="873" alt="Screenshot 2024-08-19 at 12 36 19 PM" src="https://github.com/user-attachments/assets/cdfd6178-4faa-403a-bfda-c9e407212ae1">

**Comment by yuwenmemon** [comment] 2024-08-19 16:46
Oh yeah, it's because we use `UpdatePolicyConnectionConfiguration`, which performs a `SET` instead of a `PATCH` like `UpdateManyPolicyConnectionConfigurations` does.

**Comment by yuwenmemon** [comment] 2024-08-19 16:56
I think I can at least move all sync updates to use individual commands, which will help with: https://github.com/Expensify/Expensify/issues/398342

cc @aldo-expensify

**Comment by yuwenmemon** [comment] 2024-08-19 20:15
Actually I'll just make this easier and have Auth use JSONB_PATCH in both cases.

**Comment by mvtglobally** [comment] 2024-08-23 12:05
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment] 2024-08-26 12:48
Auth PR is on prod, can we close this?

**Comment by yuwenmemon** [comment] 2024-08-26 17:05
Yes

**Closed by yuwenmemon** 2024-08-26 17:05 UTC
Labels: Reviewing, Daily, Internal, Bug, Hot Pick
