### ISSUE TITLE
[$250] Android – Workspace settings – Workspace avatar is not play video when add a gif image

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47681] opened 2024-08-20 06:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4873281
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with Gmail account
3. Create a new workspace
4. Tap on Profile
5. Tap on Avatar to edit photo
6. Select GIF file

## Expected Result:
Video is playing

## Actual Result:
Video is not playing, only image is visible

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d6f7deff-8b90-42b9-943d-b4171e0eff42

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f0ccdca10a92e9b</li>
        <li>Upwork Job ID: 1826018430208557144</li>
        <li>Last Price Increase: 2024-08-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by IuliiaHerets** [comment] 2024-08-20 06:11
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment] 2024-08-20 06:12
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by wildan-m** [comment] 2024-08-20 07:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Android workspace settings: Workspace avatar doesn't play video when a gif image is added.

### What is the root cause of that problem?

New feature

### What changes do you think we should make in order to solve the problem?

By default the Gif images are not supported in android react native app. We need to set use [Fresco](http://frescolib.org/docs/index.html) to display the gif images

build.gradle

```
implementation 'com.facebook.fresco:fresco:2.0.0'
implementation 'com.facebook.fresco:animated-gif:2.6.0'
```


### What alternative solutions did you explore? (Optional)
N/A

**Comment by Christinadobrzyn** [comment] 2024-08-20 22:08
It does look like gifs are allowed with other platforms so let's fix this for Android. I assume this can be external.

**Comment by AlfredoAlc** [comment] 2024-08-21 01:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace avatar is not playing video when selecting a gif image.

### What is the root cause of that problem?
For that screen we are using `Animated.Image` component from `react-native-reanimated` which internally uses the `Image` component from `react-native`. That `Image` component doesn't render gifs correctly specifically for Android devices.

https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/components/AvatarCropModal/ImageCropView.tsx#L79-L83


### What changes do you think we should make in order to solve the problem?
I recommend using the `createAnimatedComponent()` function from `react-native-reanimated` and create an `AnimatedImage` component from our custom [`Image`](https://github.com/Expensify/App/blob/main/src/components/Image/index.tsx) component. That component uses internally the `Image` component from `expo-image` which handles correctly gifs for all platforms.

And use that new `AnimatedImage` component instead of the `Animated.Image` component.

**Comment by Christinadobrzyn** [comment] 2024-08-23 19:33
@thesahindia can you please review the proposal when you have a moment? TY!

**Comment by Christinadobrzyn** [comment] 2024-08-25 18:06
Good call - asking here - https://expensify.slack.com/archives/C066HJM2CAZ/p1724609178246019

**Comment by Christinadobrzyn** [comment] 2024-08-26 15:37
discussing with the team - https://expensify.slack.com/archives/C066HJM2CAZ/p1724609178246019

**Comment by Christinadobrzyn** [comment] 2024-08-27 15:21
[Discussing with the team](https://expensify.slack.com/archives/C066HJM2CAZ/p1724771792962969?thread_ts=1724609178.246019&cid=C066HJM2CAZ) - gifs don't play once they are saved as a profile image on all devices. So closing this without action.

**Closed by Christinadobrzyn** 2024-08-27 15:21 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
