### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] [MEDIUM] Scan - Merchant message disappears after deleting receipt and reappears after adding receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34997] opened 2024-01-23 19:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat
2. Create a scan request
3. While the scanning is ongoing, navigate to the request details page and manually enter amount
4. Click on the receipt and delete it
5. Add a receipt

## Expected Result:
Since merchant is a requirement for workspace request, the merchant requirement message will remain until a merchant is entered

## Actual Result:
After deleting the receipt while merchant is empty, the merchant message disappears. After adding a receipt, the message reappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ad6fafb4-1173-420b-ac56-17f665fcc76f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f34025c8418af8d7</li>
        <li>Upwork Job ID: 1749884467102949376</li>
        <li>Last Price Increase: 2024-01-23</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28142586</li>
<li>dukenv0307 | Contributor | 28142587</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-23 19:59
We think that this bug might be related to #wave6. 
CC @greg-schroeder

**Comment by c3024** [comment] 2024-01-26 16:05
I'll update in a few hours. Thanks for the bump.

**Comment by c3024** [comment] 2024-01-27 15:16
We don't show RBR and error for the required fields when they are empty only while the receipt is scanned. The empty field check is already being done so checking whether the receipt is scanned as suggested by @Nodebrute is I think the correct way to fix this. However, this change should be done for all required fields as well as the brick indicator field.

In cases when there is no receipt, setting `hasErrors` to `true` purely based on `canEdit` as suggested by @dukenv0307 gives the meaning of having errors just because the request is editable which is inconsistent with the variable name `hasErrors`. Further, with violations enabled setting `hasErrors` to `true` causes a regression showing a danger border for the `ReceiptEmptyState` for simple manual money requests.

So, [the proposal here](https://github.com/Expensify/App/issues/34997#issuecomment-1906909180) by @Nodebrute looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by kadiealexander** [comment] 2024-01-30 01:26
@Julesssss bump!

**Comment by Julesssss** [comment] 2024-01-30 10:07
I was sick, but it looks like we should now discuss @dukenv0307's points before committing to the proposal. 

@c3024:

> So my suggestion is that we need to add a variable to check this in BE as we `ve proposed [here](https://github.com/Expensify/App/pull/28618/files#r1385473157), then use it as I mentioned in my https://github.com/Expensify/App/issues/34997#issuecomment-1907046052. What do you think?

**Comment by c3024** [comment] 2024-02-01 17:52
1. There is no scope of the mandatory fields (amount, merchant and created) missing errors in case of manual requests (with receipt added). Because, in manual request flow the user cannot make a request unless they fill all these mandatory fields.

2. Where as in case of a scan request flow, the user uploads a picture and till the smartscan is complete or till the user overrides it with filling fields, there are no errors for missing mandatory fields. Only when the user fills a field (either amount or merchant) before the scanning is complete does the error appear. 

3. My understanding is that the request type is fixed based on the tab (either scan or manual). It does not matter if a receipt is added later to a manual request or the receipt is deleted for a scan request. Whatever the request type is fixed at the time of selection of tab at the making of request remains.

4. So, while I agree that `hasReceipt` does not convey the correct meaning, the case where one of the mandatory fields missing for a manual request (with a receipt added later) does not arise for the reason specified in (1). 

This updating value of `hasErrors` here
https://github.com/Expensify/App/blob/49fbaa035150260033424bf284343a05c3213fb5/src/components/ReportActionItem/MoneyRequestView.js#L226
need not be in `hasReceipt` check (no harm in being there as well) because the `hasMissingSmartScanFields` checks if the transaction has receipt here. 
https://github.com/Expensify/App/blob/49fbaa035150260033424bf284343a05c3213fb5/src/libs/TransactionUtils.ts#L439

So, while I agree that `hasReceipt` does not clearly convey whether the request is a scan or a manual request (with receipt added), I think that differentiation is not required right now.

Also, I don't think the suggested change by @Nodebrute causes [this regression](https://github.com/Expensify/App/issues/34997#issuecomment-1916316629) as suggested.

So, I think we can go with the proposal by @Nodebrute 

cc: @dukenv0307 @Julesssss

**Comment by c3024** [comment] 2024-02-05 05:53
> * Why do you think that it does not cause a regression? We `hasErrors` need to meet the condition `canEdit`, right?

[This proposal](https://github.com/Expensify/App/issues/34997#issuecomment-1906909180) replaces the `hasErrors` with `!TransactionUtils.isReceiptBeingScanned(transaction)` so displaying the error is not dependent on the `hasErrors` field anymore and they are displayed only based on the empty field conditions ((after scanning is complete or the request is overridden by entering amount or other details) like `isEmptyMerchant` here.

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/components/ReportActionItem/MoneyRequestView.tsx#L298

I checked the test steps in the potential regression #34195 suggested and I see it working fine with this change.

> * Also, the `hasErrors` need a condition `!isDistanceRequest`. if we do like the selected solution, it also misses this condition

That is a good catch. I think we should check for `!isDistanceRequest` as well along with `!TransactionUtils.isReceiptBeingScanned(transaction)` for these mandatory fields to fix this without disturbing existing behaviours in distance requests.

So either we should move the `hasErrors` update to outside the `hasReceipt` or change the `hasErrors` to `!isDistanceRequest &&  !TransactionUtils.isReceiptBeingScanned(transaction)`. I think the former looks appropriate. [This is proposed here](https://github.com/Expensify/App/issues/34997#issuecomment-1907046052) in @dukenv0307 's alternative solution and this solution looks good to me.

Over to you @Julesssss for final call

**Comment by Julesssss** [comment] 2024-02-05 10:05
Thanks for all the discussion. 

> We need to have a way to differentiate manual requests with an attached receipt from a smartscan request once the server returns the response.

I agree this would be ideal, but don't have the time to make the backend `` change right now. 

I'm struggling to verify whether @dukenv0307's alternative works without the backend change though. Can you please verify?

**Comment by Julesssss** [comment] 2024-02-05 11:37
Got it, thanks. Then let's go with your alternative solution where `hasErrors` is outside of the condition 👍 

I'll check back in a few hours in case there are any final dissagreements.

**Comment by c3024** [comment] 2024-03-01 15:46
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
 
 * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #26155 
 * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/26155/files#r1509172991
 * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This happens only when the user enters amount before the scan is complete and then removes the receipt. This is an uncommon case and this is difficult to be identified. So, no discussion has been started.
 * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
 * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Go to workspace chat
2. Create a scan request
3. While the scanning is ongoing, navigate to the request details page and manually enter amount leaving `Merchant` field empty
4. Verify that there is an error and RBR at the `Merchant` field
5. Click on the receipt and delete it
6. Verify that the error and RBR stay at the 'Merchant' field
7. Add a receipt
8. Verify that the error and RBR stay at the 'Merchant' field

👍 or 👎

**Comment by s77rt** [comment] 2024-03-04 16:48
Ignore ^

**Comment by kadiealexander** [comment] 2024-03-07 05:21
Payouts due:

Contributor: $500 @dukenv0307
Contributor+: $500 @c3024

Upwork job is [here](https://www.upwork.com/nx/wm/offer/28142587).

**Comment by kadiealexander** [comment] 2024-03-08 00:31
Issue for adding steps to Testrail: https://github.com/Expensify/Expensify/issues/376654

**Closed** 2024-03-08 00:35 UTC
Labels: External, Daily, Awaiting Payment, Bug
