### ISSUE TITLE
[HOLD] [$250] iOS -Chat - When using extension in compose box the focus disappears

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11867] opened 2022-10-14 19:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Log in with any account
3. Navigate to any conversation
4. Focus on the compose box and start typing in a quick manner
5. When the arrows appear to enlarge the compose box - tap on them

## Expected Result:
User can continue typing.

## Actual Result:
Focus disappears from compose box.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** v1.2.15-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/195930916-7e012d5d-6bff-4dd6-a1c5-4694d84f18d7.mp4
<img src="https://user-images.githubusercontent.com/43996225/195930910-0894a9bc-8112-4d99-ba96-21e9fdd2bcc8.jpg" width="40%" height="40%">
<img src="https://user-images.githubusercontent.com/43996225/195930913-8f161f3d-0a6d-44ac-a9cd-80f13bb92aaf.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment] 2022-10-17 07:18
<b>Proposal</b>
We didn't focus the text input again after expand or collapse so this issue happened.

<b>Solution</b>
Add the input focus after press expand or collapse in this file:
https://github.com/Expensify/App/blob/363d98fd3a3567c102c5359ba5257c67f95c60d0/src/pages/home/report/ReportActionCompose.js#L560-L586
For collapse:
```diff
          <Tooltip text={this.props.translate('reportActionCompose.collapse')}>
              <TouchableOpacity
                  onPress={(e) => {
                      e.preventDefault();
                      Report.setIsComposerFullSize(this.props.reportID, false);
+                    this.textInput.focus();
                  }}
                  style={styles.composerSizeButton}
                  underlayColor={themeColors.componentBG}
                  disabled={isBlockedFromConcierge}
              >
                  <Icon src={Expensicons.Collapse} />
              </TouchableOpacity>
          </Tooltip>

      )}
                                                              
```

For expand:

```diff
                           <Tooltip text={this.props.translate('reportActionCompose.expand')}>
                                <TouchableOpacity
                                    onPress={(e) => {
                                        e.preventDefault();
                                        Report.setIsComposerFullSize(this.props.reportID, true);
+                                      this.textInput.focus();
                                    }}
                                    style={styles.composerSizeButton}
                                    underlayColor={themeColors.componentBG}
                                    disabled={isBlockedFromConcierge}
                                >
                                    <Icon src={Expensicons.Expand} />
                                </TouchableOpacity>
                            </Tooltip>                                                             
```

**Comment by mountiny** [comment] 2022-10-17 14:57
Please see discussion in [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1665991322162069). This is related to the the react-drawer  update but we would like to fix it without downgrading its version.

**Comment by roryabraham** [comment] 2022-10-17 17:43
I'm going to put this issue on HOLD for https://github.com/Expensify/App/issues/11915 since we should have a fix ready-to-go in the upstream react-navigation repo.

**Comment by roryabraham** [comment] 2022-10-18 00:12
Taking this over because I have a [fix](https://github.com/Expensify/App/pull/11944) ready for review.

**Comment by kbecciv** [comment] 2022-10-21 18:31
Issue is reproducible with build 1.2.18.5, re-opening

https://user-images.githubusercontent.com/93399543/197265339-975a7a7b-06c3-4d41-b7a2-c826eaf3136f.mp4

**Comment by mountiny** [comment] 2022-10-21 20:55
I think this has been reported much before the react-drawer change, cant find the link right now :(

**Comment by mountiny** [comment] 2022-10-21 21:11
Oh, there we go, thanks!

**Comment by techievivek** [comment] 2022-10-24 07:31
So I think for the scope of this issue we have already implemented a fix, right?

**Comment by roryabraham** [comment] 2022-10-24 09:44
Closing this out, it's fixed

**Closed by roryabraham** 2022-10-24 09:44 UTC
Labels: Reviewing, Engineering, Daily, Improvement, Bug
