### ISSUE TITLE
[HOLD for payment 2024-01-26] [$500] Settings - Red dot remains after error is cleared

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33021] opened 2023-12-13 21:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31713
## Action Performed:
Pre-requisite: user must be logged in
1. On staging, enable "Simulate failing network requests" in Settings > Preferences
2. Go to Settings > Profile > Contact method
3. Add a phone number as a new contact method
4. Wait for the pending add operation to fail
5. Once you see the red dot, click on the contact method and clear the error

## Expected Result:
The red dot should disappear after the error is cleared

## Actual Result:
The red dot remains on user avatar on the home screen and in settings

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/12fb6405-23e2-4fe2-99ac-b11d63ce21b5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ec660a67cb6d223</li>
        <li>Upwork Job ID: 1735053356937179136</li>
        <li>Last Price Increase: 2024-01-03</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 28089273</li>
<li>tienifr | Contributor | 28089274</li>
</ul></li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment] 2023-12-13 23:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

All - Settings - Red dot remains after error is cleared

### What is the root cause of that problem?

In `deleteContactMethod`, we are clearing `errorFields.deletedLogin` but we aren't clearing `errorFields.addedLogin` which is a part of the `failureData` of `addNewContactMethodAndNavigate`.

When we delete a contact method, we expect a green dot to show up while the deletion is being processed, this is added intentionally by using `pendingFields.deletedLogin: CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE` as shown below in the code, however this green dot is override by red dot because of `errorFields.addedLogin`

https://github.com/Expensify/App/blob/fe2d0d1ca481a05ad281e4bea85f31b11b88a817/src/libs/actions/User.js#L186-L200

### What changes do you think we should make in order to solve the problem?

We should clear that errorField on contact method deletion so the red dot doesn't show up during the deletion process

```javascript
function deleteContactMethod(contactMethod, loginList) {
    ....
    value: {
        [contactMethod]: {
            ....
            errorFields: {
                deletedLogin: null,
                addedLogin: null,
            },
```

### Result

https://github.com/Expensify/App/assets/74202751/b09cd38c-32d3-45e9-97a6-e33bbed29a1f

**Comment by sfurqan2** [comment] 2023-12-14 00:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Red dot remains after error is cleared when network connection is simulating slow network requests
### What is the root cause of that problem?
The root cause of the problem is that in Contact Page there is an additional check which hides new contact requests with pendingAction "delete". 

```js
const hideChildren = shouldHideOnDelete && !isOffline && pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE && !hasErrors;
```

However, this check is missing from userUtils "hasLoginListError" function. 
```js
function hasLoginListError(loginList: Record<string, Login>): boolean {
    return Object.values(loginList).some((loginData) => Object.values(loginData.errorFields ?? {}).some((field) => Object.keys(field ?? {}).length > 0));
}
```
### What changes do you think we should make in order to solve the problem?
Logic on both ends should be kept consistent so I would suggest we implement the same checks in userUtils and call it. This will maintain the DRY principle as well as is easier to maintain.


### What alternative solutions did you explore? (Optional)

N/A

**Comment by sfurqan2** [comment] 2023-12-14 00:19
Contributor details
Your Expensify account email: sfurqan1999@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0163c31a5a31c72f3f

**Comment by AmjedNazzal** [comment] 2023-12-22 08:07
@ntdiary Any feedback on my proposal?

**Comment by AmjedNazzal** [comment] 2024-01-02 07:56
@ntdiary My solution to begin with has been adding `addedLogin: null` in the `optimisticData`, sure alternatively we could make it `errorFields: null`, with that being said though, essentially `addedLogin` is probably the only error field here that will be affecting the behaviour in the context of this component. is the suggestion to update proposal to `errorFields: null` exclusive to @tienifr?

**Comment by michaelhaxhiu** [comment] 2024-01-03 14:48
🚀

**Comment by michaelhaxhiu** [comment] 2024-01-05 21:59
@ntdiary do we feel good about the [latest proposal](https://github.com/Expensify/App/issues/33021#issuecomment-1854965474) from @tienifr ?

**Comment by michaelhaxhiu** [comment] 2024-01-05 21:59
Let's get this moving forward if so, as it's blocked

**Comment by danieldoglas** [comment] 2024-01-18 20:51
@tienifr @ntdiary can you please take a look into https://github.com/Expensify/App/issues/34758 and check if it's related ? cc @dangrous

**Comment by dangrous** [comment] 2024-01-29 15:41
Hi! I just wanted to call it out here - I'm closing out https://github.com/Expensify/App/issues/34758 as not a bug, but I'm pretty sure it means that QA was never able to successfully QA this issue. It would be great if y'all could make sure this works as expected on this issue!

**Comment by danieldoglas** [comment] 2024-01-31 20:27
@ntdiary let's do the bugzero checklist here

**Comment by michaelhaxhiu** [comment] 2024-01-31 23:50
Next step is with @ntdiary to do the regression steps

**Comment by danieldoglas** [comment] 2024-02-01 19:43
cc @miljakljajic can you please proceed with the payment on this issue? Thanks!

**Comment by miljakljajic** [comment] 2024-02-02 09:15
Paid and paid!

**Closed by miljakljajic** 2024-02-02 09:15 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
