### ISSUE TITLE
[HOLD for payment 2023-08-03] [$1000] Web - The tooltip shows multiple/all the selected users when hovering over the overlayed avatar

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22951] opened 2023-07-15 18:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Settings > Workspace > Members
2. Click on Invite and select 9 users.
3. Click on next
4. Hover over the Overlayed avatar and notice the tooltip shows multiple/all the selected users.

## Expected Result:
The tooltip should only show users missing from the initial 2 lines

## Actual Result:
The tooltip shows multiple/all the selected users.
 
## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e9621fb0-8147-471d-9efd-d7c43d30c6dd

https://github.com/Expensify/App/assets/93399543/51e449e5-1524-44dc-880c-8b778e696a11

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689364011034509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117cec49274e7cba8</li>
        <li>Upwork Job ID: 1680798574892285952</li>
        2023-07-17<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 25671578</li>
<li>ahmedGaber93 | Contributor | 25671580</li>
<li>daveSeife | Reporter | 25671581</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-07-15 19:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tooltip shows number of users max than the reminding when Hovering over the Overlayed avatar.
### What is the root cause of that problem?
Wrong calculate for tooltip text in  `MultipleAvatars`, after enable multi rows in PR #21402 we missed changing it base on the new way.

https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/components/MultipleAvatars.js#L195-L198

we now use rows so `tooltipTexts.slice(3, 10)` is not correct because rows show 8 avatars.
### What changes do you think we should make in order to solve the problem?
The tooltip text should be

```javascript
// text={tooltipTexts.slice(3, 10).join(', ')}
text={tooltipTexts.slice((avatarRows.length * props.maxAvatarsInRow) - 1, 10).join(', ')}
```
1. .slice with size 10 is optional to show tooltip for only 10 users since some reports have hundreds of users.
The number 10 in the current code is the whole user in rows and tooltip if we need to keep it for whole user we can calculate it 10 - (props.maxAvatarsInRow * avatarRows.length) we can discuss it.

2. -1 above to show the user number 8.
### What alternative solutions did you explore? (Optional)
we can calculate it out of tooltipTexts
```javascript
text={props.shouldShowTooltip ? _.pluck(avatars.slice(props.maxAvatarsInRow - 1), 'name').slice(0, 10).join(', ') : ''}
```

**Comment by jliexpensify** [comment] 2023-07-17 00:42
Hmm, very odd - I invited 9 users and here's what I see:

![image](https://github.com/Expensify/App/assets/30815269/48ad80ec-8e9d-4021-b018-13220336f584)

So I think that hovering over the +1 should only accurately reflect who isn't currently on those 2 lines.

**Comment by jliexpensify** [comment] 2023-07-17 00:46
Oh, this is a dupe of https://github.com/Expensify/App/issues/22685

**Comment by daveSeife** [comment] 2023-07-17 02:48
Hi @jliexpensify I think they are different issues. The one you mentioned is about the Avatars moving to the left when adding more than 8 users(this issue can also be seen in the IOU report of more than 7 user splitting a bill and also in "workspace" in the settings). 

The issue I posted is about the tooltip not showing the correct users. 

Can you please comment on this so I can have a better understanding on how they are the same

**Comment by jliexpensify** [comment] 2023-07-17 04:31
@daveSeife I'm going off the Slack link, but it looks like it might be the [incorrect one](https://expensify.slack.com/archives/C049HHMV9SM/p1689364011034509) associated with this GH?

**Comment by jliexpensify** [comment] 2023-07-17 04:37
Hi @aimane-chnaif - based off Ahmed's comment [here](https://github.com/Expensify/App/issues/22951#issuecomment-1636858205), this isn't considered a regression right? It's just something that we didn't account for in the other PR?

**Comment by niteshletxsoft** [comment] 2023-07-17 08:40
### **Proposal**

### **Please re-state the problem that we are trying to solve in this issue.**
The tooltip shows number of users max than the reminding when Hovering over the Overlayed avatar.

### **What is the root cause of that problem?**
The cause of this issue is wrong calculation of the number of remaing avatars to be shown in the tooltip.
 https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/components/MultipleAvatars.js#L195-L198

This is the part of the code, which is causing the current issue.

### **What changes do you think we should make in order to solve the problem?**
To fix this issue, We will define two states as follows along with a const value to show the number of emails in the tooltip
```javascript
const maxAvatarsInTooltip = 9; //10 - 1 in order to point to the indexes of the array;
const maxAvatarsRows = 2;

// This value will have a value of max 10 depending on the number of user's avatar in the list.
// we are limiting it to 10 or so as some reports have hundreds of users, causing performance to degrade.
const [remainingAvatars, setRemainingAvatars] = useState(0);
// We are counting the remaining number of the users which are not included in the avatars and the tooltip
// to show the count in the tooltip
const [notListedAvatarsCount, setNotListedAvatarsCount] = useState(0);
```

then we will update the values of the states defined above in calculateAvatarRows function with this code.

https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/components/MultipleAvatars.js#L81C1-L97

```javascript
// We are going to have only two rows as per the code here above. So we will exclude the Avatars in the rows from the list and 
// Show only 10 more users in the tooltip. If there are more users, We will add a string in the tooltip
// With remaining numbers which are not included in the tooltip.
if (props.icons.length > props.maxAvatarsInRow * maxAvatarsRows) {
    const avatarsCountInTooltip = props.maxAvatarsInRow * maxAvatarsRows + maxAvatarsInTooltip;
    setRemainingAvatars(avatarsCountInTooltip);

    if (props.icons.length > avatarsCountInTooltip) {
        setNotListedAvatarsCount(props.icons.length - avatarsCountInTooltip);
    }
}
```

Then we will use the states to show the max 10 emails in the tooltip and add the remaining numbers in the tooltip with "...+ N More"

```javascript
<Tooltip
    // We only want to cap tooltips to only the first 10 users or so since some reports have hundreds of users, causing performance to degrade.
    text={`${tooltipTexts.slice((avatarRows.length * props.maxAvatarsInRow) - 1, remainingAvatars).join(', ')}
${notListedAvatarsCount > 0 ? ` ...+ ${notListedAvatarsCount} More`: "" }`}
>
```

**Comment by niteshletxsoft** [comment] 2023-07-17 08:43
Contributor details
Your Expensify account email: niteshsharma@letxsoft.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018f40cdf5cfc3c570

**Comment by niteshletxsoft** [comment] 2023-07-17 20:21
Hi @aimane-chnaif 
Would you please share your thoughts, why do you think the proposal shared by AhmedGabar93 looks good but not mine?

I have proposed a better solution to the tooltip issue and an enhancement to handle the large number of members in a Workspace.
As i shared in the solution that We will show only 10 member's name (Email), which are not visible in the avatar rows and the remaining members count will be shown in the tooltip like "...+12 More". Which will give the idea to the user that there are more members, which are not included in the tooltip.

We can also include the below two points with this task as well.

- swap 1st row and 2nd row so that +x is at the end of 2nd row
- center align horizontally avatars group container

Looking forward for your reply.

**Comment by niteshletxsoft** [comment] 2023-07-17 21:40
@aimane-chnaif Actually it's the solution to the problem we are having.
We are having an issue, which shows incorrect names of the members which are not visible in the avatar rows.
To give the user proper information about all the members, We have to use this approach. 
It should not be a optional thing. Representation of the Information in a correct way should the approach of the solution.

Let's take a case, where someone have 35 members and he/she moved to this page, which just show 8 Avatars + 10 or 15 in the tooltip. He/she might think this as a bug. We are not showing all the members name, atleast show the numbers which are not included in the tooltip.

**Comment by niteshletxsoft** [comment] 2023-07-18 07:07
Yes, I tested with 10 members and the count is also wrong.
The current code counts the 8th Avatar (With the count of remaining members on it) as a avatar, but it's actually a tooltip button to show the remaining members emails / Name. This should not be counted as an 8th Avatar because it does not the email of the 8th member when we hover over it.

In the 10 Members case, The 8Th Avatar with tooltip will show 3 emails/name (Including 8th memeber's email along with 9th and 10th members email/name) but the count on the 8th avatar shows +2.

Here is the screenshot to explain you better. The 8th avatar will also come in the tooltip, as this is the place where the user can see it's name/email.

<img width="377" alt="Screenshot 2023-07-18 at 12 35 28 PM" src="https://github.com/Expensify/App/assets/53343579/ee6ceed4-d807-4f86-bd0a-0485c4125fcf">

**Comment by jliexpensify** [comment] 2023-07-21 05:33
@madmax330 you've been assigned this issue, [based on this comment](https://github.com/Expensify/App/issues/22951#issuecomment-1637658309) - can you review please?

**Comment by madmax330** [comment] 2023-07-21 09:55
I agree with @aimane-chnaif's recommendation

**Comment by ahmedGaber93** [comment] 2023-07-22 13:20
@aimane-chnaif [PR](https://github.com/Expensify/App/pull/23396) is now ready for review.

**Comment by jliexpensify** [comment] 2023-07-28 00:50
Payment Summary:

- Issue Reporter: @daveSeife $250
- Contributor: @ahmedGaber93 $1000
- C+: @aimane-chnaif $1000

Is this correct? Upworks Job [here](https://www.upwork.com/jobs/~0117cec49274e7cba8).

Friendly bump @aimane-chnaif to complete the checklist

**Comment by jliexpensify** [comment] 2023-07-28 02:39
@aimane-chnaif can you share the timeline please, for documentation purposes?

**Comment by jliexpensify** [comment] 2023-07-28 05:13
Thank you, updated above!

**Comment by jliexpensify** [comment] 2023-08-03 02:32
Bump @aimane-chnaif to complete the checklist before payment. Thanks!

**Comment by jliexpensify** [comment] 2023-08-04 02:32
Everyone paid, job closed, Thanks!

**Closed by jliexpensify** 2023-08-04 02:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
