### ISSUE TITLE
[HOLD App#19095] [$1000] Web - When deleting the last message after a money request, the email address is shown instead of the username

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22796] opened 2023-07-13 11:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Navigate to the "Request money"
3. Enter the amount and request it
4. Send a message in the chat
5. Delete the last sent message
6. Notice before deleting message it was username but after deleting email address displayed

## Expected Result:
The deletion of the last message after a money request should not display the email address of the other user

## Actual Result:
Deleting the last message after a money request shows the email address instead of the username

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8a6e677b-b027-43c6-a874-bb3c9643c630

https://github.com/Expensify/App/assets/93399543/010cc961-72dc-44e8-8ff4-962ab51c40f1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689159664071419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c84d77abf4550b41</li>
        <li>Upwork Job ID: 1679473347809771520</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-07-13 12:50
Reproduced. Agreed this feels like a bug. 

https://github.com/Expensify/App/assets/54866469/a082feec-4f85-4613-9ba4-3c5974b46c0e

**Comment by Victor-Nyagudi** [comment] 2023-07-13 14:51
I believe you're right, @allroundexperts. 

This is what I got from the backend after deleting the most recent message, as shown in the steps. 

![expensify-backend-response-after-delete](https://github.com/Expensify/App/assets/79470910/24f0fe86-76df-43ea-89a1-82992afd524a)

We'll need some insight from the backend engineers on this one.

**Comment by multijump** [comment] 2023-07-13 16:59
In this case, `lastMessageTextFromReport` was node made from `lastReportAction`.
It was made from `report.lastMessageText` and this report.lastMessageText` was from backend.
So I think it is backend issue.

**Comment by joekaufmanexpensify** [comment] 2023-07-13 18:23
Adding engineering label, as it looks like this needs to be handled internally!

**Comment by Gilbertelnino** [comment] 2023-07-14 10:16
### Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - When deleting the last message after a money request, the email address is shown instead of the username

### What is the root cause of that problem?

The problem is in this file src/libs/OptionsListUtils.js we don't have the proper logic to get the latest action report

### What changes do you think we should make in order to solve the problem?

In order to solve this we need to add a logical condition to check if the message is deleted and get the latest report

**Comment by Gilbertelnino** [comment] 2023-07-14 10:22
Contributor details
Your Expensify account email: ndatimanagilbert250@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0172bd4a777b771bd4

**Comment by joekaufmanexpensify** [comment] 2023-07-14 18:52
Pending internal review from Vit

**Comment by mountiny** [comment] 2023-07-14 20:39
Havent go around to this once. Maybe this one will help with it https://github.com/Expensify/App/pull/19095

**Comment by joekaufmanexpensify** [comment] 2023-07-24 13:40
On hold

**Comment by joekaufmanexpensify** [comment] 2023-07-31 13:31
PR is out on staging. So should be able to test this later this week.

**Comment by joekaufmanexpensify** [comment] 2023-08-07 13:40
Other PR is out on production. Re-tested and the other issue fixed this bug, so this is all set. Closing as no action is needed here!

**Closed by joekaufmanexpensify** 2023-08-07 13:40 UTC
Labels: Engineering, Weekly, Internal, Bug

**Comment by ayazhussain79** [comment] 2023-08-07 14:07
@joekaufmanexpensify Am I eligible to report a bonus? PR that also fixed this issue, may have created after this bug.

**Comment by ayazhussain79** [comment] 2023-08-07 14:08
@joekaufmanexpensify can you please check that again ?

**Comment by joekaufmanexpensify** [comment] 2023-08-07 14:19
Hm I'd think probably not. As the PR that fixed this was opened in May, 2023 . And this bug reported on July, 2023. If the bug was already going to be fixed by that PR, IDT we'd pay a reporting bonus here.
