### ISSUE TITLE
[HOLD money request modal refactor] [$1000] Split/Request/Send - Click on back button of device navigates to LHN instead of previous screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20588] opened 2023-06-12 14:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on + button
2. Select Request money , send money or split bill
3. Enter amount
4. Click on. Next button
5. Press Android native back button (not caret) to go to the previous screen

## Expected Result:
Should navigate to previous screen

## Actual Result:
Navigates to LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native - can not reproduced
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0cf500e9-aaff-44c1-834e-22dd0557e2cf

https://github.com/Expensify/App/assets/93399543/51b02b5a-068d-4db2-adf0-c17680938bc7

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686202903642119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d8522b2a2f1c4c5f</li>
        <li>Upwork Job ID: 1668326458886987776</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-06-12 18:22
I can't reproduce this on android native v1.3.26-3. 


https://github.com/Expensify/App/assets/54866469/bfe4add5-8325-4f35-911b-4d2a4d2012a0

**Comment by joekaufmanexpensify** [comment] 2023-06-12 18:34
Reproduced using native android back button: 

https://github.com/Expensify/App/assets/54866469/e0c08cec-cd48-4495-a9a5-c2a38e935d5f

**Comment by roryabraham** [comment] 2023-06-13 02:13
@cubuspl42 While your proposal looks reasonable, we just completed a large refactor of all our react-navigation code and I think we need to be very careful when introducing new patterns. For example, we have several multi-step form flows where the steps are stored in state, so a generalized solution for this pattern in the navigation layer would be appropriate, rather than a screen-by-screen solution that doesn't use react-navigation.

**Comment by cubuspl42** [comment] 2023-06-13 06:05
@roryabraham Thanks for this explanation. Do you mean that in the scope of this issue, we should refactor all such flows so they don't keep steps in React state?

**Comment by mountiny** [comment] 2023-06-13 07:44
This is because the money request modal right now is one screen so going back pops it.

I believe @s77rt and @bernhardoj work on refactoring this to its on screens which will resolve this issue.

I will close this for now, thanks for raising

**Comment by mountiny** [comment] 2023-06-13 07:44
No reporting bonus either as this refactoring has been planned and ongoing for a while

**Comment by roryabraham** [comment] 2023-06-17 00:26
@mountiny Should we reopen this and put it on HOLD for that refactoring so we can retest after?

**Comment by mountiny** [comment] 2023-06-19 14:32
sure, this should be fixed 99% as its the core logic of the navigation changes, but we can keep it open for the retest. making it weekly too

**Comment by mountiny** [comment] 2023-06-19 14:33
@bernhardoj @s77rt could you link the issue for the refactor, I could not find it quickly

**Comment by s77rt** [comment] 2023-06-19 14:35
Issue: https://github.com/Expensify/App/issues/17662
PR: https://github.com/Expensify/App/pull/17964

**Comment by joekaufmanexpensify** [comment] 2023-06-26 12:47
Thanks! I see the refactoring issue is out on prod now. I just retested this and it's working now, so closing!

**Closed by joekaufmanexpensify** 2023-06-26 12:47 UTC
Labels: External, Weekly, Bug
