### ISSUE TITLE
[$2000] Unnecessary new lines created when user mentions a contact

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21615] opened 2023-06-26 19:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open ND on Android
2. Open any chat and type @
3. Select any one contact from the list which has a long email
4. Observe the mentioned contact email in the composer

## Expected Result:
Extra new lines should not be created since there is enough space inside the composer
## Actual Result:
Extra new lines are created and app is not using the white space after the email.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e93a3335-2fd8-4c88-bfd2-536121375649

https://github.com/Expensify/App/assets/43996225/a11a96ec-c014-401b-bc5d-94fc65e70141

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687353655609189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c301c436377b47aa</li>
        <li>Upwork Job ID: 1673794132243972096</li>
        <li>Last Price Increase: 2023-07-19</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27161424</li>
<li>aswin-s | Contributor | 27161425</li>
<li>nathan-mulugeta | Reporter | 27161427</li>
</ul></li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-06-26 20:35
I can reproduce this, but am not 100% convinced this is a bug. The mention does break into multiple lines with extra space. But then if you type on one of the middle lines, it fills out the extra space. 

https://github.com/Expensify/App/assets/54866469/50b0a6fc-979d-4ead-a99e-ef4d7bc34e12

**Comment by joekaufmanexpensify** [comment] 2023-06-26 20:41
Discussing [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1687812057722109)

**Comment by joekaufmanexpensify** [comment] 2023-06-27 20:43
Discussed [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1687814356209099?thread_ts=1687812057.722109&cid=C01SKUP7QR0), and this is a bug, since it only happens with mentions.

**Comment by joekaufmanexpensify** [comment] 2023-06-28 19:15
Waiting for proposals

**Comment by joekaufmanexpensify** [comment] 2023-06-29 18:38
Same

**Comment by joekaufmanexpensify** [comment] 2023-06-30 17:38
Still waiting for proposals.

**Comment by joekaufmanexpensify** [comment] 2023-07-03 13:05
Same

**Comment by joekaufmanexpensify** [comment] 2023-07-06 17:50
Still pending proposals.

**Comment by aswin-s** [comment] 2023-07-07 06:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Text in composer wraps early even when there is enough white space available towards right

### What is the root cause of that problem?

Native TextInput component on Android uses 'highQuality' [line break strategy](https://developer.android.com/reference/kotlin/androidx/compose/ui/text/style/LineBreak.Strategy#HighQuality()). This strategy scans the entire paragraph and wraps the multi line text for better readability. That's the reason it breaks the email 'applausetester+0709izv2604@applause.expensify.com' early when it encounters a series of number after the text. This behaviour is also annoying when user tries to delete characters from the end of the long string as the text wrapping keeps on changing with each character being removed.

### What changes do you think we should make in order to solve the problem?

For Composer component, pass the attribute `textBreakStrategy: 'simple'`. This is an [Android only prop](https://developer.android.com/reference/kotlin/androidx/compose/ui/text/style/LineBreak.Strategy#HighQuality()) which maps to the native lineBreakStrategy prop on Android. 

https://github.com/Expensify/App/blob/main/src/components/Composer/index.android.js#L98C12-L98C12

```
<RNTextInput
  autoComplete="off"
  textBreakStrategy="simple"
  ...
/>
```


### What alternative solutions did you explore? (Optional)

None

**Comment by s77rt** [comment] 2023-07-07 15:03
@aswin-s Thanks for the proposal. Although your RCA makes sense I'm not sure we are at the very root cause yet. `textBreakStrategy` default value should already be `simple`[^1], how come it's not the case?

[^1]: https://github.com/Expensify/react-native/blob/9837731f7bbf93949344c3cc74fdc304764085e4/Libraries/Components/TextInput/AndroidTextInputNativeComponent.js#L196-L199

**Comment by aswin-s** [comment] 2023-07-07 16:54
@s77rt My bad. I was referring to textBreakStrategy of `Text` component while checking the default value which is highQuality by default. As per Android documentation for EditText line break strategy is purposefully set as `simple` to prevent the text dancing around while user typing. Surprisingly we are observing this dancing behaviour in the Composer component of Expensify. Which means the default value of breakStrategy at native level is not 'simple'.

[**setBreakStrategy**](https://developer.android.com/reference/android/widget/TextView#setBreakStrategy(int))

`
Sets the break strategy for breaking paragraphs into lines. The default value for TextView is [Layout#BREAK_STRATEGY_HIGH_QUALITY](https://developer.android.com/reference/android/text/Layout#BREAK_STRATEGY_HIGH_QUALITY), and the default value for EditText is [Layout#BREAK_STRATEGY_SIMPLE](https://developer.android.com/reference/android/text/Layout#BREAK_STRATEGY_SIMPLE), the latter to avoid the text "dancing" when being edited.
`


I'm checking a [recent commit to react native](https://github.com/facebook/react-native/commit/3b2d5419899363d84aea4f5cc3a4c75253dd6406) which sets default textBreakStrategy to highQuality. I'll keep you posted.

**Comment by aswin-s** [comment] 2023-07-07 19:53
This issue is present even in a new react-native project. TextInput is using `highQuality` as the default `textBreakStrategy` on Android devices. Only fix seems to be explicitly setting the props value to 'simple'. 

Here is a snack to quickly verify the issue.
https://snack.expo.dev/EXM6N4Rkm

I've [raised an issue ](https://github.com/facebook/react-native/issues/38244)at react-native repo as well.

**Comment by s77rt** [comment] 2023-07-07 22:42
@aswin-s Thanks! At least we identified the real issue :smile: Now I think we are open for upstream proposals.

**Comment by ShogunFire** [comment] 2023-07-08 18:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

On android composer the lines sometimes appears wrapped to the left

### What is the root cause of that problem?

As @aswin-s said [here](https://github.com/Expensify/App/issues/21615#issuecomment-1624796844) 

> Native TextInput component on Android uses 'highQuality' [line break strategy](https://developer.android.com/reference/kotlin/androidx/compose/ui/text/style/LineBreak.Strategy#HighQuality()). This strategy scans the entire paragraph and wraps the multi line text for better readability. That's the reason it breaks the email

We can use pass the prop textBreakStrategy: 'simple' to the textinput to make it work but it's supposed to be the default value so we shouldn't have to.

I haven't managed to prove it but maybe the prop that is actually used is not this one:
https://github.com/Expensify/react-native/blob/9837731f7bbf93949344c3cc74fdc304764085e4/Libraries/Components/TextInput/AndroidTextInputNativeComponent.js#L196-L199

[Here](https://github.com/Expensify/react-native/blob/9837731f7bbf93949344c3cc74fdc304764085e4/ReactCommon/react/renderer/components/textinput/androidtextinput/react/renderer/components/androidtextinput/AndroidTextInputProps.cpp#L63C7-L66)  we have another props who convert rawProps into a string , from the name I deduce that rawProps is the props as we passed them so without default value so in our case rawProps for textBreakStrategy would be null.

The problem is that during the conversion here:

https://github.com/Expensify/react-native/blob/9837731f7bbf93949344c3cc74fdc304764085e4/ReactCommon/react/renderer/attributedstring/conversions.h#L87-L100

If textBreakStrategy is not set or wrong they return "highQuality" instead of simple

### What changes do you think we should make in order to solve the problem?

I think we should return 'simple' there too since this is the default value elsewhere

### What alternative solutions did you explore? (Optional)

**Comment by ShogunFire** [comment] 2023-07-08 18:41
Hello @s77rt , I know my proposal is full of assumptions but it is a possible cause so I still put it. If you think we are going in the right direction I can research more

**Comment by s77rt** [comment] 2023-07-08 18:57
@ShogunFire Thanks for the proposal. @aswin-s already linked to a potential offending commit that also makes changes to the code you linked. I think it would be a good call to investigate that.

**Comment by ShogunFire** [comment] 2023-07-08 20:21
Oups, I had missed that. So I guess we know the problem now, they changed the default value to HighQuality because the doc says that it should be the default value for TextView but their changes also set the default value for EditText which is wrong.

**Comment by aswin-s** [comment] 2023-07-09 02:17
Found the offending piece of code.

https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputShadowNode.java#L56


```java
mTextBreakStrategy =
  (Build.VERSION.SDK_INT < Build.VERSION_CODES.M)
  ? Layout.BREAK_STRATEGY_SIMPLE
  : Layout.BREAK_STRATEGY_HIGH_QUALITY;

```

Here TextInput is getting initialised with breakStrategy as high quality for API versions above 22. However TextInput should alway be initialised with 'Layout.BREAK_STRATEGY_SIMPLE' as any other strategy would cause text wrapping to change while user is typing. And the Android documentation also sets this expectation. 

I've confirmed the fix on my local setup And will be raising a PR upstream soon.

**Comment by s77rt** [comment] 2023-07-09 17:08
Cool! This seems to be the offending PR https://github.com/facebook/react-native/pull/23333 and that change looks a misunderstanding/unintended https://github.com/facebook/react-native/pull/23333#discussion_r255322749.

**Comment by aswin-s** [comment] 2023-07-10 05:59
**Update:** Above fix works only for current architecture. To raise a PR for the fix, I guess it needs to be fixed for new architecture as well.

For new architecture the default value seems to be read from [ParagraphAttributes](https://github.com/facebook/react-native/blob/50f620a1ad8e925a46d2aa8e6439d5ce6f4f2ce4/packages/react-native/ReactCommon/react/renderer/attributedstring/ParagraphAttributes.h#L45-L47). It is also shared by other TextComponents. So we cannot reset the value to 'Simple' directly within ParagraphAttributes. 

Other places where the prop is getting initialised are 

https://github.com/facebook/react-native/blob/50f620a1ad8e925a46d2aa8e6439d5ce6f4f2ce4/packages/react-native/ReactCommon/react/renderer/components/textinput/androidtextinput/react/renderer/components/androidtextinput/AndroidTextInputProps.h#L87

https://github.com/facebook/react-native/blob/50f620a1ad8e925a46d2aa8e6439d5ce6f4f2ce4/packages/react-native/ReactCommon/react/renderer/components/textinput/androidtextinput/react/renderer/components/androidtextinput/AndroidTextInputProps.cpp#L63-L66

Setting a default value at above lines doesn't seem to be working.

**Comment by ShogunFire** [comment] 2023-07-10 12:37
The first offending [Pr](https://github.com/facebook/react-native/commit/3b2d5419899363d84aea4f5cc3a4c75253dd6406)  that you had found was changing values in conversion file to change the default value and they looked happy about the result.

I think we could pass a default value as the last argument here https://github.com/facebook/react-native/blob/50f620a1ad8e925a46d2aa8e6439d5ce6f4f2ce4/packages/react-native/ReactCommon/react/renderer/components/textinput/androidtextinput/react/renderer/components/androidtextinput/AndroidTextInputProps.cpp#L63-L66 and use it in conversions

**Comment by s77rt** [comment] 2023-07-10 20:13
We are working on it, Melvin

**Comment by joekaufmanexpensify** [comment] 2023-07-11 20:04
Agreed! @s77rt Curious if you think we're close to being able to accept any of the existing proposals on the issue?

**Comment by s77rt** [comment] 2023-07-11 22:03
@joekaufmanexpensify We are close. It seems we found a solution for the current react-native arch (paper) but not for the new one (fabric). @aswin-s Can you confirm the same?

**Comment by aswin-s** [comment] 2023-07-12 16:58
> @joekaufmanexpensify We are close. It seems we found a solution for the current react-native arch (paper) but not for the new one (fabric). @aswin-s Can you confirm the same?

Yes @s77rt that's correct. I don't have a fix for new architecture yet.

**Comment by joekaufmanexpensify** [comment] 2023-07-12 19:25
Got it. @aswin-s Curious if you think you'll have identified a fix for this one soon?

**Comment by joekaufmanexpensify** [comment] 2023-07-13 18:11
Pending response.

**Comment by aswin-s** [comment] 2023-07-14 11:07
Fixing it for new architecture seems beyond me. No one from upstream repo has responded on the issue yet. So I've raised a PR for fixing it on old architecture. 

https://github.com/facebook/react-native/pull/38347

**Comment by joekaufmanexpensify** [comment] 2023-07-14 18:53
@s77rt Are you cool with fixing this only on the old architecture?

**Comment by s77rt** [comment] 2023-07-14 19:25
@joekaufmanexpensify This will create an inconsistency between the two archs. I'm not sure the PR will be merged. Although that would be enough to fix this issue.

**Comment by joekaufmanexpensify** [comment] 2023-07-17 19:41
Got it. Is there a way to fix this without the upstream PR?

**Comment by ShogunFire** [comment] 2023-07-17 19:46
Pass textBreakStrategy, this is @aswin-s [Proposal](https://github.com/Expensify/App/issues/21615#issuecomment-1624796844)   I think he deserves it. And I saw that we used textBreakStrategy at another place in the app

**Comment by s77rt** [comment] 2023-07-17 21:01
@joekaufmanexpensify Yes, we could simply pass `textBreakStrategy="simple"` to `TextInput`. The thing is that textBreakStrategy default value should already be "simple", the fact that it's not is the bug (upstream bug).

**Comment by aswin-s** [comment] 2023-07-18 17:24
@s77rt Reviewer is concerned that this change might break existing apps which are using `highQuality` strategy by default. So I guess this change might only be made available through a major release. 

https://github.com/facebook/react-native/pull/38347#discussion_r1265964612

**Comment by joekaufmanexpensify** [comment] 2023-07-18 18:25
Interesting. Does that mean we'd consider changing this just in our app, rather than upstream?

**Comment by s77rt** [comment] 2023-07-18 19:09
@joekaufmanexpensify  Hmm maybe, but I think only if RN updates their docs to have the default as `highQuality`? cc @aswin-s 

Let's see how the PR discussion ends first.

**Comment by joekaufmanexpensify** [comment] 2023-07-19 12:59
Got it, sounds good!

**Comment by ShogunFire** [comment] 2023-07-19 13:10
In the meantime is it worth it trying to solve the problem on the new architecture or is it better to wait for that too ?

**Comment by s77rt** [comment] 2023-07-19 14:57
@ShogunFire Solving this for the new arch (and old arch) is best in my opinion as this will reflect the default values in Android. The default value for `TextView` is `Layout#BREAK_STRATEGY_HIGH_QUALITY`, and the default value for `EditText` is `Layout#BREAK_STRATEGY_SIMPLE` [^1].

[^1]: https://developer.android.com/reference/android/widget/TextView#setBreakStrategy(int)

**Comment by joekaufmanexpensify** [comment] 2023-07-20 18:18
@s77rt If proceeding here is held on the discussion in the upstream PR, should this be on hold then until we know for sure whether we can fix this in the new architecture?

**Comment by s77rt** [comment] 2023-07-20 18:24
@joekaufmanexpensify Yes let's put this on hold. Thanks!

**Comment by joekaufmanexpensify** [comment] 2023-07-21 13:10
Sounds good, thanks!

**Comment by joekaufmanexpensify** [comment] 2023-07-24 13:41
On hold

**Comment by s77rt** [comment] 2023-07-24 19:01
@aswin-s Can you please help push the PR forward, whether i( should be merged or update the docs

**Comment by aswin-s** [comment] 2023-07-25 05:34
I've asked the reviewer for his recommendation.

**Comment by joekaufmanexpensify** [comment] 2023-07-31 13:32
Still on hold

**Comment by joekaufmanexpensify** [comment] 2023-08-07 13:15
Same

**Comment by aswin-s** [comment] 2023-08-11 03:49
No feedback from reviewer yet. My recommendation is to override the `textBreakStrategy` in TextInput component under `Library/Components`. This would solve the issue for Expensify App and have all inputs behave in expected way. We are pretty sure that this PR wouldn't land in any of the minor versions as it is a breaking change for majority of users.

**Comment by joekaufmanexpensify** [comment] 2023-08-14 13:19
@s77rt thoughts on this?

**Comment by s77rt** [comment] 2023-08-14 15:09
@aswin-s We no longer use the forked repo. This has to either be fixed on RN level or our App level

**Comment by s77rt** [comment] 2023-08-14 15:18
@joekaufmanexpensify I think we can wait a little more for RN response on this since it's not a priority AFAIK.

**Comment by joekaufmanexpensify** [comment] 2023-08-21 13:31
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2023-08-28 13:44
Held

**Comment by joekaufmanexpensify** [comment] 2023-09-04 17:55
Same

**Comment by joekaufmanexpensify** [comment] 2023-09-11 13:42
Still held

**Comment by joekaufmanexpensify** [comment] 2023-09-17 08:38
Same

**Comment by joekaufmanexpensify** [comment] 2023-09-25 03:04
Same.

**Comment by joekaufmanexpensify** [comment] 2023-10-02 21:14
Still held

**Comment by aswin-s** [comment] 2023-10-10 04:48
@s77rt Just doing a rain check here. It's been almost 3 months and we are yet to get any feed back from upstream repo. 

A check in our codebase shows that all the text inputs extends from the `RNTextInput` (App/src/components/RNTextInput.js) component, as we need AnimatedTextInput. All we need to do is to set `textBreakStrategy` as `simple` in this component. This will properly fix the issue across the Expensify codebase. Fix in upstream repo seems to be a lost cause at this point.

**Comment by s77rt** [comment] 2023-10-10 13:33
I have also asked in Slack for visibility https://expensify.slack.com/archives/C01GTK53T8Q/p1696944794805369

**Comment by aswin-s** [comment] 2023-10-11 12:21
Raised a PR to fix the documentation.

https://github.com/facebook/react-native-website/pull/3881

**Comment by aswin-s** [comment] 2023-10-11 14:59
@s77rt The documentation update [PR got merged ](https://github.com/facebook/react-native-website/pull/3881#pullrequestreview-1671468478) 🎉.  Looks like we can make the required change in our code base now.

**Comment by s77rt** [comment] 2023-10-11 16:44
@aswin-s That's great! Can you please update your proposal to have the change affect our wrapperd TextInput

**Comment by aswin-s** [comment] 2023-10-11 16:55
@s77rt Updated [my proposal](https://github.com/Expensify/App/issues/21615#issuecomment-1624796844) above.

**Comment by s77rt** [comment] 2023-10-11 19:27
@aswin-s Thanks for the update! Let's get this fixed!

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/21615#issuecomment-1624796844)

**Comment by joekaufmanexpensify** [comment] 2023-10-16 14:56
Sounds good!

**Comment by aswin-s** [comment] 2023-10-18 00:41
PR is deployed to production. Melvin doesn't seem to care.

**Comment by aswin-s** [comment] 2023-10-23 14:20
@joekaufmanexpensify  All good from my side.

**Comment by s77rt** [comment] 2023-10-23 20:28
- The PR that introduced the bug has been identified: n/a. The bug is in RN (and its outdated documents)
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: Not needed for this case as we already have a [lint rule](https://github.com/Expensify/eslint-config-expensify/blob/49f110377c597defdf11fea76a1772f3539dae90/rules/expensify.js#L20-L25) to force the use of our custom TextInput (which includes the fix) instead of RN's TextInput
- Determine if we should create a regression test for this bug: I don't think this is needed for the same reason above

**Comment by s77rt** [comment] 2023-10-23 20:28
@joekaufmanexpensify All is good. Checklist provided above ^

**Comment by aswin-s** [comment] 2023-10-23 21:32
@joekaufmanexpensify PR was merged within 3 days of assignment. Is speed bonus applicable here?

**Comment by joekaufmanexpensify** [comment] 2023-10-30 21:30
Switching to this to daily so I can organize the payment next steps. I will look into the applicability of urgency bonus here as well.

**Comment by joekaufmanexpensify** [comment] 2023-10-31 22:01
[Discussing speed bonus.](https://expensify.slack.com/archives/C01SKUP7QR0/p1698789659021309)

**Comment by joekaufmanexpensify** [comment] 2023-11-01 21:01
Okay, we discussed in the above thread and confirmed this is eligible for a speed bonus. So we need to make the following payments: 

- @aswin-s - $3000 ($2000 for bounty + $1000 speed bonus). Paid via Upwork. 
- @s77rt - $3000 ($2000 for C+ review + $1000 speed bonus). Paid via Upwork. 
- @Nathan-Mulugeta - $50 for reporting. Paid via Upwork.

**Comment by joekaufmanexpensify** [comment] 2023-11-01 21:02
@aswin-s $3000 sent and contract ended!

**Comment by Nathan-Mulugeta** [comment] 2023-11-01 21:03
Hey @joekaufmanexpensify The reporting bonus for this one is based on the previous bounty since this issue was opened before the adjustment

**Comment by joekaufmanexpensify** [comment] 2023-11-01 21:03
@s77rt $3000 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-11-01 21:03
>Hey @joekaufmanexpensify The reporting bonus for this one is based on the previous bounty since this issue was opened before the adjustment

Ah, good call. Let me double check the timing on that!

**Comment by joekaufmanexpensify** [comment] 2023-11-01 21:06
Okay, yep. Reporting will be $250, since [this was reported before August, 24th](https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649).

**Comment by Nathan-Mulugeta** [comment] 2023-11-01 21:08
Great thanks

**Comment by joekaufmanexpensify** [comment] 2023-11-01 21:08
@Nathan-Mulugeta $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-11-01 21:09
Bug is fixed, and all payment issued. Closing as this is all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-11-01 21:09 UTC
Labels: External, Engineering, Daily, Bug
