### ISSUE TITLE
[Awaiting C+ for payment][$500] Profile - Private notes doesn't appear on profile when navigate via Share code link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#35654] opened 2024-02-02 11:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
User A have a existing conversation with User B

1. While logged out User A navigate to conversation with User B via Share code link
2. Take a note of the Profile modal

## Expected Result:
Since there is a existing conversation between users - on the Profile modal Private notes should be present

## Actual Result:
Private notes does not appear on existing conversation when navigate logged out via Share code link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7e6eaf67-e1e9-4f53-aa44-c2aa2ca5cdbe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145bd5b64b244e0b6</li>
        <li>Upwork Job ID: 1753374296548478976</li>
        <li>Last Price Increase: 2024-02-23</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by izarutskaya** [comment] 2024-02-02 11:08
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by FitseTLT** [comment] 2024-02-02 11:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Private notes doesn't appear on profile when navigate via Share code link

### What is the root cause of that problem?
The problem lies in how we are getting the reportID for the 1to1 chat report here as it depends on the reports list in onyx
https://github.com/Expensify/App/blob/9d4c634a87890ccbdcc2efe353ae9d929aa5530b/src/pages/ProfilePage.js#L281-L287
So if the reports is not fetched to the onyx from BE when the profile page is rendered it will result in null reportID and privates notes not fetched
### What changes do you think we should make in order to solve the problem?

We need to subscribe to the reports list and recalculate `getChatByParticipants` to get report when the reports list is successfully fetched from BE in Profile Page.
### What alternative solutions did you explore? (Optional)

**Comment by miljakljajic** [comment] 2024-02-06 11:57
reviewing proposals still

**Comment by shubham1206agra** [comment] 2024-02-06 13:23
@miljakljajic I am waiting for a better proposal. The current proposals add listeners to all reports, which I think is not a good approach.

**Comment by FitseTLT** [comment] 2024-02-06 15:09
@shubham1206agra The data the page gets from the route is accountID and it needs to get the DM report linked to that participant and if reports data is not ready we will definitely need to recalculate the `getChatByParticipants` when the data `reports` is ready. So what I am proposing is just a `useEffect` that will be run once on render and will only subscribe to the report collection if report is not ready at that time (what is needed in the case of this current issue) and early return for the case the report is ready and once the reports collection is ready we will populate the report and will disconnect inside the callback. I don't see an inefficiency in it.

**Comment by shubham1206agra** [comment] 2024-02-06 15:25
Can you give me a test branch for this?

**Comment by FitseTLT** [comment] 2024-02-06 15:26
> Can you give me a test branch for this?

Will do shortly

**Comment by shubham1206agra** [comment] 2024-02-06 15:28
I think I have same feedback as https://github.com/Expensify/App/issues/35654#issuecomment-1929585780. I just don't need to necessarily listen to all reports after initial rendering.

**Comment by FitseTLT** [comment] 2024-02-06 16:28
@shubham1206agra be notified that made changes on the test branch 👍

**Comment by shubham1206agra** [comment] 2024-02-07 02:26
@FitseTLT I still don't like this solution.

@dukenv0307 We cannot update the Onyx logic. Maybe design a selector for all reports (Not sure if it prevents re-rendering on any change in the collection).

**Comment by shubham1206agra** [comment] 2024-02-07 02:45
Maybe see the SidebarLinkData component.

**Comment by FitseTLT** [comment] 2024-02-08 13:05
@shubham1206agra 
1. Don't forget my alternative solution that's to incorporate the `reportID` inside the route
2. We can also optionally subscribe to the report collection and pass it to the `key` callback to solve this specific issue and to deal with the performance degradation we can memoize `ProfilePage` in such a way that it won't re-render in response to changes in report collection.

**Comment by miljakljajic** [comment] 2024-02-13 15:20
Still reviewing proposals

**Comment by miljakljajic** [comment] 2024-02-20 17:04
@shubham1206agra what are your thoughts

**Comment by mvtglobally** [comment] 2024-02-27 15:39
Issue not reproducible during KI retests. (First week)

**Comment by miljakljajic** [comment] 2024-03-01 16:50
sorry @trjExpensify - would you mind issuing payment ([offer links here](https://github.com/Expensify/App/issues/35654#issuecomment-1972141841)) on the 7th of March? I'll be OOO next week.

Cheers!

**Comment by trjExpensify** [comment] 2024-03-04 09:06
Sure! Awaiting the regression period to run down melv, chill.

**Comment by jasperhuangg** [comment] 2024-03-06 21:04
^ Same

**Comment by trjExpensify** [comment] 2024-03-07 12:01
👋 Checklist time please!

**Comment by trjExpensify** [comment] 2024-03-11 11:06
Yep! Payment summary as follows: 

- $500 to @shubham1206agra for C+ review.
- $500 to @dukenv0307 for the fix.

@dukenv0307 I've paid you. @shubham1206agra doesn't look like you've accepted [the offer](https://www.upwork.com/nx/wm/offer/101051704) yet.

**Comment by trjExpensify** [comment] 2024-03-11 11:32
Yep, please comment here when your ready. Dropping to `Weekly` and updating the title.

**Comment by trjExpensify** [comment] 2024-04-02 14:00
Sounds good, closing!

**Closed** 2024-04-18 15:06 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
