### ISSUE TITLE
Desktop - Sign in - The app freezes after logging in via the "Sign in with Google" function

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25679] opened 2023-08-22 13:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open New Expensify app
2. Click on "Sign in with Google"
3. Sign in with your account in the browser
4. Click on "Open New Expensify" in the pop-up window
5. Attempt to do any action in the app

## Expected Result:
After logging in via the "Sign in with Google" feature, the user should be able to fully use the app under their account

## Actual Result:
The app freezes and you can't perform any action until you restart the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/af365ea8-2d97-425d-a7d9-25c8345c8c4a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cdanwards** [comment] 2023-08-22 14:51
@danieldoglas hey! 👋🏼 I'm one of the external contributors who worked on this feature. I've been able to identify the issue and working up a solution. Would it be best for you to reassign this issue and submit the PR myself or is it better to provide the solution here and you do the PR? I'm happy with whatever is easiest for you! 🙂

**Comment by danieldoglas** [comment] 2023-08-22 15:12
@cdanwards you can put up a PR, I'll assign you to the issue!

**Comment by amyevans** [comment] 2023-08-23 15:30
I tested on staging following the CP of https://github.com/Expensify/App/pull/25706 and could not reproduce the error, so I think we can close this.

**Closed by amyevans** 2023-08-23 15:30 UTC
Labels: DeployBlockerCash, Engineering, Hourly
