### ISSUE TITLE
[HOLD for payment 2023-09-21] Web - Input field not focused on click of back button from Get assistance page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25893] opened 2023-08-24 20:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings > Workspaces >members
2. click on invite button
3. click on ? button to go Get assistance page
4. click on back button

## Expected Result:
input field not focused on click of back button

## Actual Result:
 input field should be focused on click of back button from Get assistance page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-2

**Reproducible in staging?:** Y

**Reproducible in production?:** N 

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/f191e187-badf-4c56-923b-4e513d091ab3

https://github.com/Expensify/App/assets/115492554/84d79220-98cb-46f8-af49-2ba53bbbd9d6

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692778407152369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by b4s36t4** [comment] 2023-08-24 21:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
This is happening after #22622 this PR, we don't do any focus on the input when navigating back.
### What is the root cause of that problem?

After getting merged of #25894 which will allow us to manually focus the input, we can use the updated ref and would be focusing depends on route focus in Screen `WorkSpaceInvitePage`

```jsx

const isFocused = props.navigation.isFocused()

useEffect(() => {
    if(selectionListRef.current && isFocused){
        selectListRef.current.focusTextInput()
    }
},[isFocused, selectionListRef])
```

Would be giving the focus to the input whenever we navigate back.

### What changes do you think we should make in order to solve the problem?
NA

**Comment by situchan** [comment] 2023-08-25 19:57
@b4s36t4 we should implement "focus input on navigation focus" in BaseSelectionList which is base component, similar to BaseOptionsSelector here:
https://github.com/Expensify/App/blob/0b7ae7f58e3a98ba49cf9fc2812921964d9d8895/src/components/OptionsSelector/BaseOptionsSelector.js#L101-L108

**Comment by b4s36t4** [comment] 2023-08-25 20:09
@situchan gotcha. I think the same approach would do the work, except in context of functional component and the way we use the propos.

**Comment by roryabraham** [comment] 2023-08-25 22:31
This is still reproducible in 1.3.57-5

**Comment by roryabraham** [comment] 2023-08-25 22:51
@situchan I tried that actually for a related issue – `InteractionsManager.runAfterInteractions` uses `requestAnimationFrame` on web and so will interrupt a transition in progress. I know that's what react-navigation recommends in their docs, but it doesn't really work on web.

I tried [this solution](https://github.com/Expensify/App/issues/11795#issuecomment-1693981399) and it works great for pushing new routes onto the stack, but doesn't work for popping routes off the stack because, as Satya explains [here](https://github.com/react-navigation/react-navigation/pull/9915#pullrequestreview-751263137), `transitionStart` and `transitionEnd` only run for the top card on the stack.

In this case we want to run an effect on the _new_ top card on the stack only after `transitionEnd` finishes for the _old_ top card on the stack.

**Comment by roryabraham** [comment] 2023-08-25 23:01
This solution seems to work well for pushing new cards onto the stack as well as popping them:

```diff
diff --git a/src/components/SelectionList/BaseSelectionList.js b/src/components/SelectionList/BaseSelectionList.js
index 046b64e9e5..74083c4ad8 100644
--- a/src/components/SelectionList/BaseSelectionList.js
+++ b/src/components/SelectionList/BaseSelectionList.js
@@ -1,7 +1,8 @@
-import React, {useEffect, useMemo, useRef, useState} from 'react';
+import React, {useMemo, useRef, useState, useCallback} from 'react';
 import {View} from 'react-native';
 import _ from 'underscore';
 import lodashGet from 'lodash/get';
+import {useFocusEffect} from '@react-navigation/native';
 import SectionList from '../SectionList';
 import Text from '../Text';
 import styles from '../../styles/styles';
@@ -266,23 +267,20 @@ function BaseSelectionList({
         );
     };
 
-    /** Focuses the text input when the component mounts. If `props.shouldDelayFocus` is true, we wait for the animation to finish */
-    useEffect(() => {
-        if (shouldShowTextInput) {
-            if (shouldDelayFocus) {
+    /** Focuses the text input when the screen this component is included in comes into focus and any transitions to open that screen are completed. */
+    useFocusEffect(
+        useCallback(() => {
+            if (shouldShowTextInput) {
                 focusTimeoutRef.current = setTimeout(() => textInputRef.current.focus(), CONST.ANIMATED_TRANSITION);
-            } else {
-                textInputRef.current.focus();
-            }
-        }
-
-        return () => {
-            if (!focusTimeoutRef.current) {
-                return;
             }
-            clearTimeout(focusTimeoutRef.current);
-        };
-    }, [shouldDelayFocus, shouldShowTextInput]);
+            return () => {
+                if (!focusTimeoutRef.current) {
+                    return;
+                }
+                clearTimeout(focusTimeoutRef.current);
+            };
+        }, [shouldShowTextInput]),
+    );
 
     /** Selects row when pressing Enter */
     useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.ENTER, selectFocusedOption, {

```

`useFocusEffect` runs whenever a card comes into focus, whether it was just pushed or the one on top was just popped, so that's great 👍🏼

The only downside (and it's pretty minor...) is that we're still using `setTimeout`, and that just feels a bit brittle. In reality it might be the best option though.

**Comment by roryabraham** [comment] 2023-08-25 23:28
Started a draft PR with this implementation: https://github.com/Expensify/App/pull/25983

That said, I don't think this needs to be a deploy blocker. Demoting this.

**Comment by roryabraham** [comment] 2023-08-25 23:34
Don't want to make this external because this was a regression related to [this project](https://github.com/Expensify/App/issues/11795). So I've asked [that project team](https://github.com/Expensify/App/issues/11795#issuecomment-1694033011) to fix it with the solution I provided

**Comment by roryabraham** [comment] 2023-08-28 19:27
@thiagobrez can I assign this issue to you?

**Comment by kadiealexander** [comment] 2023-08-29 07:11
@roryabraham do you think it makes sense for @Santhosh-Sellavel to also be C+ on this, as he was on the original PR?

**Comment by thiagobrez** [comment] 2023-08-29 07:11
Hey @roryabraham, yep! I'll take a look soon

**Comment by thiagobrez** [comment] 2023-08-30 11:43
Update: will start on this tomorrow

**Comment by thiagobrez** [comment] 2023-09-01 09:56
PR is ready to review here: https://github.com/Expensify/App/pull/26415

**Comment by roryabraham** [comment] 2023-09-14 03:01
PR is on staging

**Comment by kadiealexander** [comment] 2023-09-25 04:57
@roryabraham seems like no one is due payments based on [this](https://github.com/Expensify/App/issues/25893#issuecomment-1694033662) comment from you, can you please confirm if that's still correct?

**Comment by roryabraham** [comment] 2023-09-26 05:15
Correct, no payments due. Going to close this out.

**Comment by gadhiyamanan** [comment] 2023-09-26 05:20
@roryabraham this is eligible for reporting bonus

**Comment by roryabraham** [comment] 2023-09-26 07:56
Sorry about that. Looks like reporting bonus should apply here

**Comment by kadiealexander** [comment] 2023-09-27 05:02
Sent you a contract @gadhiyamanan!

**Comment by gadhiyamanan** [comment] 2023-09-27 05:03
@kadiealexander offer accepted, thanks!

**Comment by kadiealexander** [comment] 2023-09-27 05:14
Nice! All paid :)

**Closed by kadiealexander** 2023-09-27 05:14 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
