### ISSUE TITLE
[$250] IOU - RBR appears then disappears from IOU preview component & LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39174] opened 2024-03-28 12:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/37875
**Issue reported by:** Applause - Internal team

## Action Performed:
1. On the main device, create an IOU with secondary device user
2. On the secondary device, settle the payment
3. On the main device, make a second request right after secondary device settles the request

## Expected Result:
RBR should remain on IOU preview component, and LHN of the main report until it is cleared

## Actual Result:
RBR fades away from IOU preview component, and LHN after few seconds

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0840c8a9-8991-45f9-8067-02c6fa8ffb93

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162848aad35917395</li>
        <li>Upwork Job ID: 1776390018885652480</li>
        <li>Last Price Increase: 2024-09-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-28 12:44
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment] 2024-03-28 12:44
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kevinksullivan** [comment] 2024-04-05 23:22
This wold go in split, so I'll add it to that project and push forward.

**Comment by VickyStash** [comment] 2024-04-09 06:54
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment] 2024-04-09 10:28
I did some investigations, and that's what I've found out. The reason for RBR disappearing with the described flow is that the money request is turned into settled and the app doesn't show RBR for settled money requests.
https://github.com/Expensify/App/blob/4f673576491af54296014b7595e6ad5017fdb60e/src/components/ReportActionItem/ReportPreview.tsx#L216
This logic was implemented as a requirement for this [issue](https://github.com/Expensify/App/pull/31897) in the [related PR](https://github.com/Expensify/App/pull/31897/files).

Overall it looks like expected behavior, but if we want to define more specific cases when we want to show RBR indicators for settled money requests we need to know the requirements.

**Comment by kevinksullivan** [comment] 2024-04-11 21:17
@getusha since you are working on another project should we reassign this?

**Comment by kevinksullivan** [comment] 2024-04-19 17:41
asking about this bug in slack

https://expensify.slack.com/archives/C05RECHFBEW/p1713548212648119

**Comment by kevinksullivan** [comment] 2024-04-30 22:35
following up in slack

https://expensify.slack.com/archives/C05RECHFBEW/p1714516535693249?thread_ts=1713548212.648119&cid=C05RECHFBEW

**Comment by luacmartins** [comment] 2024-07-10 19:09
Maybe we can increase the bounty on this one since we don't have proposals?

**Comment by mvtglobally** [comment] 2024-07-11 03:52
Issue not reproducible during KI retests. (First week)

**Comment by kevinksullivan** [comment] 2024-07-26 15:39
closing as not reproducible.

**Comment by m-natarajan** [comment] 2024-07-26 19:28
@kevinksullivan Tester is still reproducible. 
On main parent report RBR is not appearing on IOU preview component and main report LHN. The RBR persist only in combined report and thread report.

https://github.com/user-attachments/assets/c52d13a5-b0c0-4c68-baab-392559a8946e

**Comment by kevinksullivan** [comment] 2024-08-09 23:35
Awaiting proposals

**Comment by kevinksullivan** [comment] 2024-09-04 17:51
asking for re-test as it's been a while

https://expensify.slack.com/archives/C9YU7BX5M/p1725472285004789

**Comment by mvtglobally** [comment] 2024-09-09 04:08
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment] 2024-09-09 14:52
I think we can close this one since it's not reproducible anymore.

**Closed by luacmartins** 2024-09-09 14:52 UTC
Labels: External, Weekly, Help Wanted, Bug
