### ISSUE TITLE
[$500] Emojis not saved and not displayed in task description

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36454] opened 2024-02-14 02:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Navigate to any chat
3. Tap the “+” button > Assign task
4. Enter title
5. Enter emojis in the description field
6. Finish creating the task
7. Open the created task
## Expected Result:
Emojis are displayed in the description field

## Actual Result:
Emojis are not displayed in the description. They can be seen when opening the description field to edit

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/5058af6e-f4b3-4e13-b4fe-d6b4123649fd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a49592038f35c91e</li>
        <li>Upwork Job ID: 1757587009008824320</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-02-14 02:07
We think this might be related to #vip-vsb
cc @quinthar

**Comment by jeremy-croff** [comment] 2024-02-14 02:45
#
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want to save Emojis in the task description

### What is the root cause of that problem?
The MenuitemWithTopDescription is setup to parse the text, so that emojis get stripped.

### What changes do you think we should make in order to solve the problem?
We can remove that flag, and allow it to render emojis.
https://github.com/Expensify/App/blob/023d62cba900f4333f73c52eb735402a994cbc4b/src/pages/tasks/NewTaskPage.js#L179
We would remove "shouldParseTitle" prop from the description MenuItemWithTopDescription, so that it can is in parity with the task.title.

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2024-02-14 05:57
regression from https://github.com/Expensify/expensify-common/pull/640 which tries to fix https://github.com/Expensify/App/issues/34307
Especially this change:
```diff
        this.rules = [
+           {
+               name: 'emoji',
+               regex: CONST.REG_EXP.EMOJIS,
+               replacement: match => `<emoji>${match}</emoji>`
+           },
```

**Comment by abdulrahuman5196** [comment] 2024-02-14 07:54
> regression from [Expensify/expensify-common#640](https://github.com/Expensify/expensify-common/pull/640) which tries to fix #34307 Especially this change:
> 
> ```diff
>         this.rules = [
> +           {
> +               name: 'emoji',
> +               regex: CONST.REG_EXP.EMOJIS,
> +               replacement: match => `<emoji>${match}</emoji>`
> +           },
> ```

@dukenv0307 / @fedirjh Could you kindly check on this regression? I was able to fix the issue by locally reverting the mentioned PR.

**Comment by situchan** [comment] 2024-02-14 09:27
@dukenv0307 can that PR be CP'ed? This is deploy blocker.
expensify-common version was accidentally bumped. It should have been bumped along with app PR.

**Comment by situchan** [comment] 2024-02-14 09:34
> The App's PR of my issue is still reviewing. Maybe another PR bumped expensify-common version.

yeah it's not your fault.
In version bump [PR](https://github.com/Expensify/App/pull/36310), they should have tested all recent changes since previous version.

**Comment by amyevans** [comment] 2024-02-14 19:04
Retested on staging after the CP and it looks good! Closing.

**Closed by amyevans** 2024-02-14 19:04 UTC
Labels: Reviewing, DeployBlockerCash, External, Engineering, Weekly, Help Wanted, Bug
