### ISSUE TITLE
Web - App crashes on click of priority mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27326] opened 2023-09-13 11:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->Preferences
3. Click on Priority mode

## Expected Result:
App should open priority mode page on click of priority mode

## Actual Result:
App crashes on click of priority mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dbfcdc32-a6da-4799-b4be-a1765b0aafb2

https://github.com/Expensify/App/assets/93399543/0001f22d-d212-4513-9967-ae0971c4c237

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694597540315309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by getusha** [comment] 2023-09-13 12:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when navigating to priority mode page
### What is the root cause of that problem?
This is a regression from https://github.com/Expensify/App/pull/25846 which flattens translation objects `en.js` & `es.js`

https://github.com/Expensify/App/blob/1baf33af3ba8e603b9cdae7ae8a99cfb5ffb2e63/src/languages/translations.ts#L46-L47

eg:

```js
    languagePage: {
        language: 'Language',
        languages: {
            en: {
                label: 'English',
            },
            es: {
                label: 'Spanish',
            },
        },
    },

```

before the change we can easily access the above value using `props.translate('languagePage.languages') and get the `languages` object value.  but when it is flat we only have access to single keys for example 'languagePage.languages.en.label', because the above object will become like the following after flattening:

```js
{
    languagePage.language: 'Language',
    llanguagePage.languages.en.label: 'English',
    ....
}

```

### What changes do you think we should make in order to solve the problem?


Since the translation object is flattened we cannot access any key to get it's child object value, we should access the required value directly.

https://github.com/Expensify/App/blob/1baf33af3ba8e603b9cdae7ae8a99cfb5ffb2e63/src/pages/settings/Preferences/PriorityModePage.js#L29-L35


```js
    const priorityModes = _.map(['default', 'gsd'], (type) => ({
        value: type,
        text: props.translate(`priorityModePage.priorityModes${type}.label`),
        alternateText: props.translate(`priorityModePage.priorityModes.${type}.description`),
        keyForList: type,
        isSelected: props.priorityMode === type,
    }));
```

We also need to update other parts of the code where direct access to object values is being attempted, for example:"

https://github.com/Expensify/App/blob/1baf33af3ba8e603b9cdae7ae8a99cfb5ffb2e63/src/pages/settings/Report/NotificationPreferencePage.js#L29
### What alternative solutions did you explore? (Optional)

**Comment by MrJithil** [comment] 2023-09-13 14:31
https://github.com/Expensify/App/issues/27326#issuecomment-1717661985

Along with this there are changes needed in 
* Company Picker for `INCORPORATION_TYPES`
* Theme change in `ThemePage` 

Can be added in the same PR.

**Comment by AndrewGable** [comment] 2023-09-13 16:57
Looks like this is going to be fixed by https://github.com/Expensify/App/pull/27358

**Closed** 2023-09-26 07:52 UTC
Labels: Reviewing, Engineering, Weekly

**Comment by MrJithil** [comment] 2023-09-26 14:54
The issue is still occurring.
