### ISSUE TITLE
[HOLD for payment 2024-09-02] [$250] Workflows - Error message for Additional approver remains when reopening the setup

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47460] opened 2024-08-14 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Workspace is under Control plan.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Workflows.
3. Click on the "This default workspace applies.." modal.
4. Click Approver.
5. Unselect the approver and save it.
6. Click Save button.
7. Close the RHP.
8. Click on the "This default workspace applies.." modal.

## Expected Result:
The error message under Additional approver and above Save button will not appear when reopening Edit approval workflow RHP.

## Actual Result:
The error message under Additional approver and above Save button remains when reopening Edit approval workflow RHP.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/db2ffef3-9ddb-4db7-8a9d-6ffb854b678d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da030f1d78849d4e</li>
        <li>Upwork Job ID: 1828862879903358180</li>
        <li>Last Price Increase: 2024-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103723711</li>
<li>cretadn22 | Contributor | 103723713</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by izarutskaya** [comment] 2024-08-14 20:21
Production 
![image](https://github.com/user-attachments/assets/aed2de3b-1825-4d89-a22e-d8cce576d735)

**Comment by tgolen** [comment] 2024-08-14 20:38
This feature is behind a beta so I am removing the deploy blocker label. cc @blazejkustra @DylanDylann

**Comment by bernhardoj** [comment] 2024-08-15 03:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error message for approval edit workflow is persisted.

### What is the root cause of that problem?
When we are editing the approval and validating it, the errors will be saved to the workflow Onyx data which means the data is persisted on the storage.
https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/libs/actions/Workflow.ts#L361

We are not clearing the error when closing/opening the page, so the previous error is shown and also, the error is shared between approval workflows.

### What changes do you think we should make in order to solve the problem?

Clears the error when the edit workflow page is mounted (or unmounted, but mounted is better).
```
function clearApprovalWorkflowErrors() {
    Onyx.merge(ONYXKEYS.APPROVAL_WORKFLOW, {errors: null});
}

useEffect(() => {
    Workflow.clearApprovalWorkflowErrors();
}, []);
```

OR

We can take out the error from the Onyx data and convert it to a local state.

**Comment by garrettmknight** [comment] 2024-08-15 22:24
@blazejkustra @DylanDylann is this getting fixed elsewhere or should we leave this open?

**Comment by DylanDylann** [comment] 2024-08-16 02:35
@blazejkustra is OOO, Could you please assign me to this issue? I will review proposals today if it is external

**Comment by DylanDylann** [comment] 2024-08-16 02:42
@garrettmknight no PR fix yet

**Comment by tgolen** [comment] 2024-08-16 16:08
There you go @DylanDylann. Got you assigned to look over proposals

**Comment by DylanDylann** [comment] 2024-08-16 17:42
Both proposals work well but I prefer @cretadn22's proposal because it will be cleaner and they also point out a good RCA

> We already reset the approvalWorkflow when navigating to the edit page (WorkspaceWorkflowsApprovalsEditPage), but we haven't passed error: null

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-08-19 09:28
@cretadn22 Could you give an ETA for the PR?

**Comment by garrettmknight** [comment] 2024-08-28 18:32
@tgolen is payment for any of this being handled in the project?

**Comment by tgolen** [comment] 2024-08-30 15:26
Not that I know of. This should just be paid out and treated like any normal contributor issue.

**Comment by garrettmknight** [comment] 2024-09-02 16:46
**Payment summary:**
- Contributor: @cretadn22 $250 paid via Upwrok
- Reviewer: @DylanDylann $250

**Comment by garrettmknight** [comment] 2024-09-02 16:46
@DylanDylann please accept the offer when you get a chance.

**Comment by DylanDylann** [comment] 2024-09-03 08:19
@garrettmknight Sure I accepted it

**Comment by garrettmknight** [comment] 2024-09-03 17:26
Cool, all paid out! @DylanDylann please complete the checklist when you get a chance.

**Comment by DylanDylann** [comment] 2024-09-04 04:21
@JmillsExpensify Hi, this issue belongs to the approval workflow feature. Do you know if we need to fill checklist?

**Comment by DylanDylann** [comment] 2024-09-06 07:43
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **No**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Closed** 2024-09-10 10:16 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
