### ISSUE TITLE
[HOLD for payment 2024-05-03] [HOLD for payment 2024-05-02] Web - "Error: FullStory is not loaded" console error shows up

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40860] opened 2024-04-24 10:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in.

## Expected Result:
No console error will show up.

## Actual Result:
"Error: FullStory is not loaded" console error shows up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img width="1440" alt="Bug6459941_1713948779812!Screenshot_2024-04-24_at_09 53 30" src="https://github.com/Expensify/App/assets/115492554/abf18fb0-ff64-48dd-bbe2-066a6aa26ede">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-24 10:10
@laurenreidexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-24 10:11
Production 


https://github.com/Expensify/App/assets/115492554/88327483-5b87-41ea-b676-0b1380dac80d

**Comment by hungvu193** [comment] 2024-04-24 10:25
Regression from this one: 
https://github.com/Expensify/App/pull/40294

Seems this one should be:
https://github.com/Expensify/App/blob/c9cf7676da863302b3dddea61976933ca9d8f33a/src/libs/fullstory/index.ts#L31-L33

```javascript
 if (!isInitialized()) { 
     init({orgId: ''}, resolve); 
 } 
```

**Comment by danieldoglas** [comment] 2024-04-28 23:36
Closing this since error doesn't exist anymore

**Closed by danieldoglas** 2024-04-28 23:36 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
