### ISSUE TITLE
[$500] [Wave Collect] [Ideal Nav] Navigating back to Workspace List doesn't work

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35610] opened 2024-02-01 23:23 UTC
## Action Performed:
1. If you’re testing this on desktop browser, shrink the window size
2. Workspace List → choose a workspace → click the back button on browser or Android
3. Confirm that you're taken back to the Workspace Settings page of the previous workspace when you should be taken back to the Workspace List page

_There was additional issue reported that is related to this isssue_
### Wrong animation when selecting a workspace
1. Make sure you're on a mobile phone or on a browser with a smaller width
2. Make sure that the test account has at least one workspace
4. Click on the Settings icon 🔧 on the bottom tab > Workspaces > Select a workspace
5. Confirm that the Workspace List page closes to the right when the new page should appear from the right.

video -> https://github.com/Expensify/App/pull/33280#issuecomment-1921860615

## Expected Result:
It should take you back to Workspace List page

## Actual Result:
You're taken back to Workspace Settings page instead of the Workspace List page

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

video → https://github.com/Expensify/App/pull/33280#issuecomment-1877829079

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154caf623797588b3</li>
        <li>Upwork Job ID: 1753227077608316928</li>
        <li>Last Price Increase: 2024-02-29</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-02-02 04:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are not able to navigate back from the workspace settings page.

### What is the root cause of that problem?
In this flow we are deeplinking to the workspace Initial route from the all-settings screen. In order for the back navigation to work we have to provide a deeplink back.

### What changes do you think we should make in order to solve the problem?
`To provide a deeplink back we can use the <HeaderWithBackButton /> `component inside of https://github.com/Expensify/App/blob/d9fd412e85be642e7b4115cd8c15ceda8424740e/src/pages/workspace/WorkspaceInitialPage.js#L175 with the prop:  `onBackButtonPress={() => Navigation.goBack(ROUTES.SETTINGS_WORKSPACES)}`

A nuance to consider is that we also have a back button being rendered on the not found state for this screen, so we'd have to only show the HeaderWithBackButton component  if the existing local variable shouldShowNotFoundPage condition is false in this component.

### What alternative solutions did you explore? (Optional)

**Comment by hayata-suenaga** [comment] 2024-02-02 06:07
I apologize 🙇 An expert agency (SWM), who worked on the original PR that caused this regression, will work on this issue.

**Comment by hayata-suenaga** [comment] 2024-02-02 06:39
We can keep @getusha as C+ for this issue. We need a C+ when the PR is ready 😄

**Comment by WojtekBoman** [comment] 2024-02-05 07:18
Hi! I'm going to work on it!

**Comment by WojtekBoman** [comment] 2024-02-05 11:29
Hi! Working on it :)

**Comment by getusha** [comment] 2024-02-05 15:53
@WojtekBoman will raise the PR.

**Comment by WojtekBoman** [comment] 2024-02-06 11:30
This issue turned out to be a bit complicated to fix and it requires from us introducing bigger changes to the part of the navigation logic responsible for BottomTabNavigator so before I start fixing it, I'd like to ask you about the priority of this issue, because it may take some time and to fix it we need to handle storing multiple bottom tab navigators in the navigation state. I suggest to focus on other issues until we make a decision how to fix it :)

**Comment by hayata-suenaga** [comment] 2024-02-06 17:40
@WojtekBoman thank you for letting us know the estimate 🙇 

so this won't be handled in [[Wave 8] [Ideal Nav] Back navigation issues](https://github.com/Expensify/App/issues/35626) that Adam is working on?

**Comment by hayata-suenaga** [comment] 2024-02-06 18:00
@WojtekBoman also, I added another related issue to this OP (`Wrong animation when selecting a workspace`). Please check the added issue description to ensure that the added issue can be handled together with the original issue.

**Comment by hayata-suenaga** [comment] 2024-02-15 17:56
@WojtekBoman is going to handle this issue when they have time

**Comment by hayata-suenaga** [comment] 2024-02-22 16:32
Melvin, @WojtekBoman is going to handle this issue when they have time

**Comment by hayata-suenaga** [comment] 2024-02-26 15:47
I'm changing the priority to weekly until Wojciech is back

**Comment by hayata-suenaga** [comment] 2024-02-29 17:38
@WojtekBoman is going to work on this when they have time

**Comment by WojtekBoman** [comment] 2024-03-01 08:39
I think this issue will be resolved when we merge [the PR with ideal-nav-v2](https://github.com/Expensify/App/pull/37421). It modifies the logic responsible for navigating between these screens

**Comment by hayata-suenaga** [comment] 2024-03-01 19:18
ah niceeee 👍 in that case, I'll add the `reviewing` label to this issue

**Comment by hayata-suenaga** [comment] 2024-03-01 19:18
let's come back to this issue after the PR is merged to see if it fixes the problem

**Comment by jliexpensify** [comment] 2024-03-19 07:59
OOO from 21st to 31st March, but will keep this assigned to me (should be nothing for B0 to do in this period).

**Comment by trjExpensify** [comment] 2024-04-08 21:39
Ideal Nav v2 merged ages ago. We good to close here or what are the next steps?

**Closed** 2024-04-09 00:00 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug
