### ISSUE TITLE
[$250] Android - When cancelling payment, "Done" message displayed instead of "Pay" button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52403] opened 2024-11-12 14:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on the FAB and select "Submit Expense"
3. Complete the expense creation flow and send the expense to any workspace.
4. Tap on "Search" on the bottom of the screen.
5. Tap on "Pay" on the preview of the just created expense.
6. Once the payment is complete, tap on the expense to open the report.
7. Tap on the header and select "Cancel Payment"
8. Tap on the arrow on the top left corner to return to expense preview on search.
9. Verify that the "Pay" button is displayed again on expense preview.

## Expected Result:
"Pay" button should appear again on the expense preview on search, after the payment is cancelled

## Actual Result:
After cancelling expense payment, a "Done" message can be seen on the expense preview instead of the "Pay" button. The user has to leave search section and return to see the "Pay" button again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/85903ebc-fc90-436f-bddd-bb55cd9628e8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856449395622318059</li>
        <li>Upwork Job ID: 1856449395622318059</li>
        <li>Last Price Increase: 2024-11-19</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Contributor | 104870015</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by mountiny** [comment] 2024-11-12 19:35
I dont think this is BE blocker based on the video

**Comment by dangrous** [comment] 2024-11-12 21:02
oh hai, not sure why i was double assigned? @puneetlath are you okay to take this one? I think you were here first.

**Comment by puneetlath** [comment] 2024-11-12 21:29
I think it assigned me and you because I'm on the BZ team as well as engineering. So I got assigned as the BZ. You got assigned as the engineer. 

Given that this Pay button in search is a new feature that isn't even on prod yet, I don't think this needs to be a deploy blocker. We can clean it up as a follow up. cc @luacmartins

**Comment by luacmartins** [comment] 2024-11-12 22:08
I'll handle this since I'm the author of the offending PR.

**Comment by luacmartins** [comment] 2024-11-12 22:38
Ah nice! I'll make it external again then!

**Comment by puneetlath** [comment] 2024-11-14 16:13
Correct!

**Comment by suneox** [comment] 2024-11-15 06:03
It looks like the current behavior on the latest staging is that the expense list does not update after a pay or cancel action. Util user change the filter to trigger reload expense

https://github.com/user-attachments/assets/11bff709-74b3-4aab-9fc8-fa118460e1d9


https://github.com/user-attachments/assets/395c6e88-c928-4892-8e70-3bacdb64bfa8


@Nodebrute Your proposal is out of date with the latest main branch. Could you please verify your proposal again?

**Comment by suneox** [comment] 2024-11-21 15:22
We're still looking for proposal, I’ve posted on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1732202409608679) to get more eyes

**Comment by suneox** [comment] 2024-11-24 16:16
> I can't reproduce this bug

@cretadn22 Thank for your feedback. [This issue](https://github.com/Expensify/App/issues/52403#issuecomment-2478027149) can not reproduce on latest staging

https://github.com/user-attachments/assets/cbf7db44-9e3d-4740-8440-98c8f6dbac66

**Comment by puneetlath** [comment] 2024-11-25 16:12
Ah good to know. In that case, I think we can just close this out. Let me know if I've missed anything!

**Closed by puneetlath** 2024-11-25 16:12 UTC
Labels: External, Engineering, Daily, Help Wanted
