### ISSUE TITLE
[HOLD for payment 2024-03-20] [HOLD for payment 2024-03-19] [$500] Chat - New messages button is not shown after marking message as unread and scrolling up

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38062] opened 2024-03-11 16:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4412893
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat with existing chat history
3. Mark any message as unread
4. Scroll up chat history

## Expected Result:
New messages button below chat header should be displayed

## Actual Result:
New messages button is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/75844e21-396a-4bf5-b279-86b056594bb2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc5aa44b04fa24d0</li>
        <li>Upwork Job ID: 1767281088113135616</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-11 16:34
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment] 2024-03-11 16:34
@marcochavezf  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcochavezf** [comment] 2024-03-11 20:56
The regression was introduced [here](https://github.com/Expensify/App/pull/32336), and it was reverted, but some changes for `ReportActionList` were not reverted at all, maybe because the file was migrated to ts in another PR.

Creating a new PR to remove the introduced changes that causing the regression.

**Comment by marcochavezf** [comment] 2024-03-11 21:02
[PR](https://github.com/Expensify/App/pull/38091) up

**Comment by marcochavezf** [comment] 2024-03-12 00:03
Fixed on staging, removing the deploy blocker label

<img width="1433" alt="Screenshot 2024-03-11 at 6 03 28 p m" src="https://github.com/Expensify/App/assets/6829422/03226eba-7550-4775-8691-c080c5dcd932">

**Comment by mallenexpensify** [comment] 2024-03-13 01:31
Thanks for the help here @marcochavezf !  Can we close this since the PR was CPd to production?
- https://github.com/Expensify/App/pull/38091

**Comment by marcochavezf** [comment] 2024-03-13 17:52
Yup, closing it out

**Comment by jayeshmangwani** [comment] 2024-03-20 20:33
This issue was closed without the C+ compensation , reviewed this [PR](https://github.com/Expensify/App/pull/38091) , can you please help with this @mallenexpensify

**Comment by mallenexpensify** [comment] 2024-03-22 21:15
eeeeps, forgot to pay @jayeshmangwani , sorry about that. 
can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01dc5aa44b04fa24d0

**Comment by jayeshmangwani** [comment] 2024-03-22 21:18
Thanks @mallenexpensify , job accepted

**Comment by mallenexpensify** [comment] 2024-03-22 22:10
Contributor+: @jayeshmangwani paid $500 via Upwork.

**Closed by mallenexpensify** 2024-03-22 22:10 UTC
Labels: External, Engineering, Weekly, Help Wanted, Awaiting Payment, Bug
