### ISSUE TITLE
[HOLD for payment 2024-10-14] [$250] [Dupe detection] Use new ResolveDuplicates when approver is resolving duplicates

### ISSUE THREAD

**Issue by pecanoro** [Expensify/App#48416] opened 2024-09-02 15:10 UTC
# Part of the Duplicate Detection project
Main issue: https://github.com/Expensify/Expensify/issues/411008
Project: [Dupe detection](https://github.com/Expensify/Expensify/issues/307591)

# Feature Description

![image](https://github.com/user-attachments/assets/3e11e9ca-7d6d-4aae-96b9-c2b2f1d180ed)

Right now, we always call [MergeTransactions](https://github.com/Expensify/App/blob/12c86200b3724d8f2a8c069bbb696b3dd31060d6/src/libs/actions/IOU.ts#L7821) when resolving duplicates and click `Confirm` at the last page of resolving duplicates. However, we need to call a new command called `ResolveDuplicates` when an approver or admin (basically anyone but the submitter) is the person resolving the duplicates. The behaviour (so we can create the proper optimistic actions) should be as follows:

- ResolveDuplicates API endpoint needs the following parameters:
```
            'authToken' => $authToken,
            'transactionIDToKeep' => $transactionIDToKeep,
            'transactionIDList' => $transactionIDList,
            'created' => $created,
            'merchant' => $merchant,
            'amount' => $amount,
            'currency' => $currency,
            'category' => $category,
            'comment' => $comment,
            'billable' => $billable,
            'reimbursable' => $reimbursable,
            'tag' => $tag,
            'optimisticReportActionID' => $optimisticReportActionID,
            'reportActionIDList' => $reportActionIDList,
```
This command will update the transaction to match the fields we chose during the flow. It should already be doing this.
- It won't delete the rest of the transactions in transactionIDList but it will HOLD them by adding the hold NVP to it and will add the corresponding HOLD actions to each of them.
- It will add a DISMISSEDVIOLATION action to the transactionIDToKeep
- It will dismiss the violation by adding the corresponding transaction NVP for all transactions. 

Main issue: https://github.com/Expensify/Expensify/issues/411008

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011781060ec2a6c428</li>
        <li>Upwork Job ID: 1830626997874011636</li>
        <li>Last Price Increase: 2024-09-02</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103792699</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by pecanoro** [comment] 2024-09-02 15:20
@parasharrajat I am assigning you as the C+ in this issue since you reviewed the main ones.

**Comment by nkdengineer** [comment] 2024-09-02 15:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add a new command for admin/approver when resolving the duplicate transaction from submitter

### What is the root cause of that problem?
We're always calling `mergeDuplicates` function without checking the current user is admin/approver or not


https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/pages/TransactionDuplicate/Confirmation.tsx#L45-L48



### What changes do you think we should make in order to solve the problem?
1. To check the user is admin/approver we can use the same way we do here.

https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/libs/ReportUtils.ts#L3074-L3079

2. Create a new function `resolveDuplicates` that will call `ResolveDuplicates` comman with the param as described [here](https://github.com/Expensify/App/issues/48416#issue-2501192175). It will be almost the same with `mergeDuplicates`, the only difference with `mergeDuplicates` is 

> It won't delete the rest of the transactions in transactionIDList but it will HOLD them by adding the hold NVP to it and will add the corresponding HOLD actions to each of them.

- We will not delete the transaction in `transactionIDList`. Instead, we will add a hold action for these transaction thread reports in optimistic data and reset in failure data and also add `hold` violation for these transaction

> It will add a DISMISSEDVIOLATION action to the transactionIDToKeep

- Add a DISMISSEDVIOLATION action with `reason` in `originalMessage` is `duplicatedTransaction` for the transaction thread report of `transactionIDToKeep` list

> It will dismiss the violation by adding the corresponding transaction NVP for all transactions.

- Remove violation of  all transactions in `transactionIDToKeep` 


### What alternative solutions did you explore? (Optional)

**Comment by pecanoro** [comment] 2024-09-03 08:59
Assigning @nkdengineer!

**Comment by nkdengineer** [comment] 2024-09-04 05:11
@pecanoro In the `ResolveDuplicates` API, what is the structure of `reportActionIDList` params?

**Comment by pecanoro** [comment] 2024-09-04 11:21
> In the ResolveDuplicates API, what is the structure of reportActionIDList params?

A comma-separated list of report actions

**Comment by pecanoro** [comment] 2024-09-05 12:06
> @pecanoro Can you give an example?

Imagine we have 3 duplicates with transactionIDs 111, 222 and 333. We want to keep 111 and hold the other two. Then:

```
'transactionIDToKeep' => '111',
'transactionIDList' => '222,333',
```

> Do we need to add reportID in data?

Nope, no reportID since they are not changing reports

**Comment by pecanoro** [comment] 2024-09-05 13:24
Ahh, the same, another comma-separated list, same as DismissViolations. The reportActionIDList contains the optimistic report actions for the HOLD actions. Then optimisticReportActionID should be for the dismissViolation action.

**Comment by nkdengineer** [comment] 2024-09-05 13:31
Got it, So the `reportActionIDList` is the same order with the `transactionIDList` right (example the first reportActionID is the hold action of the first transaction in `transactionIDList`)?


actually for the normal hold reason flow it will have two report actions, one is the hold message, one is the reason. Should we do the same in this case or we will add only the first action or add both actions?

**Comment by pecanoro** [comment] 2024-09-05 13:34
> Got it, So the reportActionIDList is the same order with the transactionIDList right (example the first reportActionID is the hold action of the first transaction in transactionIDList)?

Yes!

> actually for the normal hold reason flow it will have two report actions, one is the hold message, one is the reason. Should we do the same in this case or we will add only the first action or add both actions?

No need to add a reason for this one, it will only show that is was held.

**Comment by dylanexpensify** [comment] 2024-09-06 13:06
@nkdengineer when can we expect the PR raised? ty!

**Comment by nkdengineer** [comment] 2024-09-06 13:08
Will open this today

**Comment by dylanexpensify** [comment] 2024-09-06 13:17
amazing, ty!

**Comment by nkdengineer** [comment] 2024-09-09 04:37
@pecanoro When I call `ResolveDuplicates`, BE returns the error like this video. Here is the parameter that I called this API. Am I missing something?

```
{
    "amount": -200,
    "currency": "VND",
    "created": "2024-09-09",
    "transactionIDList": [
        "4002616464040896678"
    ],
    "billable": false,
    "reimbursable": true,
    "category": "",
    "tag": "",
    "merchant": "ssd",
    "comment": "",
    "transactionIDToKeep": "5332969134080823220",
    "reportActionIDList": [
        "637476526581947356"
    ],
    "optimisticReportActionID": "3766068727586466325"
}
```


https://github.com/user-attachments/assets/d9ca09c3-9441-41c9-9465-145f28816be9

**Comment by pecanoro** [comment] 2024-09-09 11:05
Oh, it's a BE problem, I j just checked the logs. Let me create a PR to fix it

**Comment by pecanoro** [comment] 2024-09-09 12:58
The PR is merged, we are waiting for a deploy and then you will be able to use the endpoint in staging again. I renamed transactionIDToKeep for just transactionID

**Comment by dylanexpensify** [comment] 2024-09-10 20:50
@nkdengineer PR is deployed to prod now!

**Comment by nkdengineer** [comment] 2024-09-11 15:21
@parasharrajat The PR is [here](https://github.com/Expensify/App/pull/48522).

**Comment by nkdengineer** [comment] 2024-09-12 03:20
@pecanoro While testing I found another BE bug, the dismiss violation action isn't stored from BE side.

**Comment by pecanoro** [comment] 2024-09-12 14:45
> What do you mean by NVP @pecanoro?

Ah sorry, when the transaction is put on HOLD, we add a value to the transaction namevaluepairs in the comment.

**Comment by nkdengineer** [comment] 2024-09-12 14:59
Yes, I tested and after reset cache this action is removed since BE doesn't return this action. Also the resolve duplicate API doesn't return dismiss violation action data.

**Comment by pecanoro** [comment] 2024-09-12 15:50
Let me double-check manually, but it's pretty odd since I even wrote automated tests for this and they are passing

**Comment by pecanoro** [comment] 2024-09-12 15:51
@nkdengineer Can you paste here what the BE is returning for you?

**Comment by nkdengineer** [comment] 2024-09-12 17:25
{
    "accountID": 18311825,
    "accounts": {
        "18311825": {
            "lastUpdateID": 1775760902,
            "previousUpdateID": 1775614249,
            "updateIDs": [
                1775760897,
                1775760898,
                1775760899,
                1775760900,
                1775760901,
                1775760902
            ]
        }
    },
    "authToken": "ED538D6882FC6B872FD1E38C8B75EC3ED4799DAF2809D40258D5A38DF3F448972D57954AF21C6EF04D9DBA533734CD6FC5B8908331F9904CF87AF73E8B286E9DDC523F8C2153DB499A0D6E433B2BD2E21CB71155B10A7F6D64826D4ACD1CA0443ECF354E9006107CD6DAC056448043E0FBDE3C32367A157108E87CBB53EDBFFD03E891BCEB5DA77E8EBEF24B5AF0D7E9FD9A757BDA391A6568E463678C8EF1BF1E55E96771BEEE6228EF37F1B8FF3BE280B9E5C6B2235E5FAD8E30F652EAA244C06EFE2E8B18BFB3CB8DA94286CC32C74D0B5F03C003CD78D2BB8A9D02A9478C89F64E9674B229779DDC5DEA5EED7B3DF5A513373D224C022CE70012AEAEA03F4BF4CF18ED5EBE8DF44F7A53F64C623731EF5689A91E9FB3E061CDF663B373ED10CECB4758B6D759E25715BB2EF0BE6C729E7A3928CF1F89005D8434D3BD4556A86E95D218CB4353E3B6E6A20E66F7775725A89AEB459453192F36B84EA2742A",
    "email": "nkdengineer+s102@outlook.com",
    "fetchableOnyxUpdates": [
        "1775760897",
        "1775760898",
        "1775760899",
        "1775760900",
        "1775760901",
        "1775760902"
    ],
    "onyxUpdates": {
        "1775760897": [
            {
                "key": "transactions_398480206897163307",
                "onyxMethod": "merge",
                "value": {
                    "comment": {
                        "dismissedViolations": {
                            "duplicatedTransaction": {
                                "nkdengineer+s102@outlook.com": 1726161878570510
                            }
                        }
                    }
                }
            }
        ],
        "1775760898": [
            {
                "key": "transactions_1367302367436179941",
                "onyxMethod": "merge",
                "value": {
                    "comment": {
                        "comment": "",
                        "dismissedViolations": {
                            "duplicatedTransaction": {
                                "nkdengineer+s102@outlook.com": 1726161878570610
                            }
                        }
                    }
                }
            }
        ],
        "1775760899": [
            {
                "key": "report_1113086820473870",
                "onyxMethod": "merge",
                "value": {
                    "participants": {
                        "18301280": {
                            "hidden": true,
                            "notificationPreference": "hidden"
                        },
                        "18308128": {
                            "hidden": true,
                            "notificationPreference": "hidden"
                        },
                        "18311825": {
                            "hidden": true,
                            "notificationPreference": "hidden"
                        }
                    }
                }
            }
        ],
        "1775760900": [
            {
                "key": "report_1113086820473870",
                "onyxMethod": "merge",
                "value": {
                    "chatType": "",
                    "description": "",
                    "lastActorAccountID": 18311825,
                    "lastMessageText": "held this expense with the comment: ",
                    "lastVisibleActionCreated": "2024-09-12 17:24:38.571",
                    "managerID": null,
                    "ownerAccountID": 0,
                    "parentReportActionID": "2951370456346266262",
                    "parentReportID": "8755324512976856",
                    "policyID": "2D62A4DBCE91AD7E",
                    "reportID": "1113086820473870",
                    "reportName": "Chat Report",
                    "state": "OPEN",
                    "stateNum": 0,
                    "statusNum": 0,
                    "type": "chat",
                    "visibility": null
                }
            },
            {
                "key": "reportActions_1113086820473870",
                "onyxMethod": "merge",
                "value": {
                    "2272851721205218606": {
                        "actionName": "HOLD",
                        "actorAccountID": 18311825,
                        "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_18.png",
                        "created": "2024-09-12 17:24:38.571",
                        "lastModified": "2024-09-12 17:24:38.571",
                        "message": [
                            {
                                "html": "",
                                "text": "",
                                "type": "COMMENT",
                                "whisperedTo": []
                            }
                        ],
                        "originalMessage": {
                            "accountID": 18311825,
                            "date": "2024-09-12 17:24:38",
                            "isDuplicate": "true",
                            "lastModified": "2024-09-12 17:24:38.571",
                            "message": ""
                        },
                        "person": [
                            {
                                "style": "strong",
                                "text": "nkd102",
                                "type": "TEXT"
                            }
                        ],
                        "reportActionID": "2272851721205218606",
                        "shouldShow": true
                    }
                }
            }
        ],
        "1775760901": [
            {
                "key": "personalDetailsList",
                "onyxMethod": "merge",
                "value": {
                    "18311825": {
                        "accountID": 18311825,
                        "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_18.png",
                        "displayName": "nkd102",
                        "firstName": "nkd102",
                        "lastName": "",
                        "login": "nkdengineer+s102@outlook.com",
                        "phoneNumber": "",
                        "pronouns": "",
                        "status": null,
                        "timezone": {
                            "automatic": true,
                            "selected": "Asia/Ho_Chi_Minh"
                        },
                        "validated": true
                    }
                }
            }
        ],
        "1775760902": [
            {
                "key": "transactions_1367302367436179941",
                "onyxMethod": "merge",
                "value": {
                    "comment": {
                        "hold": "2272851721205218606"
                    }
                }
            }
        ]
    },
    "httpCode": 200,
    "jsonCode": 200,
    "authResponseMessage": "200 OK",
    "requestID": "8c21979b5e5e1fbc-HKG",
    "onyxData": [
        {
            "key": "transactions_398480206897163307",
            "onyxMethod": "merge",
            "value": {
                "comment": {
                    "dismissedViolations": {
                        "duplicatedTransaction": {
                            "nkdengineer+s102@outlook.com": 1726161878570510
                        }
                    }
                }
            }
        },
        {
            "key": "transactions_1367302367436179941",
            "onyxMethod": "merge",
            "value": {
                "comment": {
                    "comment": "",
                    "dismissedViolations": {
                        "duplicatedTransaction": {
                            "nkdengineer+s102@outlook.com": 1726161878570610
                        }
                    }
                }
            }
        },
        {
            "key": "report_1113086820473870",
            "onyxMethod": "merge",
            "value": {
                "participants": {
                    "18301280": {
                        "hidden": true,
                        "notificationPreference": "hidden"
                    },
                    "18308128": {
                        "hidden": true,
                        "notificationPreference": "hidden"
                    },
                    "18311825": {
                        "hidden": true,
                        "notificationPreference": "hidden"
                    }
                }
            }
        },
        {
            "key": "report_1113086820473870",
            "onyxMethod": "merge",
            "value": {
                "chatType": "",
                "description": "",
                "lastActorAccountID": 18311825,
                "lastMessageText": "held this expense with the comment: ",
                "lastVisibleActionCreated": "2024-09-12 17:24:38.571",
                "managerID": null,
                "ownerAccountID": 0,
                "parentReportActionID": "2951370456346266262",
                "parentReportID": "8755324512976856",
                "policyID": "2D62A4DBCE91AD7E",
                "reportID": "1113086820473870",
                "reportName": "Chat Report",
                "state": "OPEN",
                "stateNum": 0,
                "statusNum": 0,
                "type": "chat",
                "visibility": null
            }
        },
        {
            "key": "reportActions_1113086820473870",
            "onyxMethod": "merge",
            "value": {
                "2272851721205218606": {
                    "actionName": "HOLD",
                    "actorAccountID": 18311825,
                    "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_18.png",
                    "created": "2024-09-12 17:24:38.571",
                    "lastModified": "2024-09-12 17:24:38.571",
                    "message": [
                        {
                            "html": "",
                            "text": "",
                            "type": "COMMENT",
                            "whisperedTo": []
                        }
                    ],
                    "originalMessage": {
                        "accountID": 18311825,
                        "date": "2024-09-12 17:24:38",
                        "isDuplicate": "true",
                        "lastModified": "2024-09-12 17:24:38.571",
                        "message": ""
                    },
                    "person": [
                        {
                            "style": "strong",
                            "text": "nkd102",
                            "type": "TEXT"
                        }
                    ],
                    "reportActionID": "2272851721205218606",
                    "shouldShow": true
                }
            }
        },
        {
            "key": "personalDetailsList",
            "onyxMethod": "merge",
            "value": {
                "18311825": {
                    "accountID": 18311825,
                    "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_18.png",
                    "displayName": "nkd102",
                    "firstName": "nkd102",
                    "lastName": "",
                    "login": "nkdengineer+s102@outlook.com",
                    "phoneNumber": "",
                    "pronouns": "",
                    "status": null,
                    "timezone": {
                        "automatic": true,
                        "selected": "Asia/Ho_Chi_Minh"
                    },
                    "validated": true
                }
            }
        },
        {
            "key": "transactions_1367302367436179941",
            "onyxMethod": "merge",
            "value": {
                "comment": {
                    "hold": "2272851721205218606"
                }
            }
        }
    ],
    "previousUpdateID": 1775614249,
    "lastUpdateID": 1775760902
}

**Comment by nkdengineer** [comment] 2024-09-12 17:26
@pecanoro The response here.

**Comment by nkdengineer** [comment] 2024-09-12 17:26
The payload here.

<img width="1512" alt="Screenshot 2024-09-13 at 00 26 11" src="https://github.com/user-attachments/assets/a9dfa7ca-0f11-43d6-ac51-4e12bb76ba95">

**Comment by pecanoro** [comment] 2024-09-12 17:50
There is something off, also because both hold actions are returned for the same report

**Comment by pecanoro** [comment] 2024-09-12 17:54
Ah nv, forget my previous comment, you were resolving duplicates with only two transactions. I am going to check the database

**Comment by pecanoro** [comment] 2024-09-12 18:12
Ah I found the problem, another parameter name that got cleared because of sanitization. I am going to rename it to something better either way. I will create a PR in the back-end

**Comment by pecanoro** [comment] 2024-09-19 17:18
@parasharrajat No, it should not change it

**Comment by nkdengineer** [comment] 2024-10-02 08:01
@parasharrajat The original PR was reverted so I created a new one [here](https://github.com/Expensify/App/pull/50035) to fix another bug https://github.com/Expensify/App/issues/49900

**Comment by sonialiap** [comment] 2024-10-14 09:59
Payment summary:
- @parasharrajat $250 please request in ND and complete the [checklist](https://github.com/Expensify/App/issues/48416#issuecomment-2398046770)
- @nkdengineer $250 paid in upwork ✔️

**Closed** 2024-10-15 09:28 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-12-16 10:16
$250 approved for @parasharrajat
