### ISSUE TITLE
[HOLD for payment 2023-10-25] [$1000] The search result still shows emoji for wrong texts

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21055] opened 2023-06-19 17:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On staging web chrome, navigate to a chat and click the emoji on the chat
2. Type in any emoji name (example search) and after you enter the last character ('h' in my case for search), do not release your fingers and continuous type any other letters. You'll see still the emojis are shown. But now release your fingers and see , it displays 'Not found'
3. Repeat the above steps on Slack and you'll see after entering the last character of the emoji, if you type any other letters even without releasing your fingers, it will still show 'Not found'
## Expected Result: 
The search result should show 'Not found' if the text doesn't match with emoji
## Actual Result: 
The search result still shows emoji for wrong texts

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4dec122c-daa2-439d-bc4d-6f7ce7e8a677

https://github.com/Expensify/App/assets/43996225/f9648f71-a471-4766-a82b-764f0f6f9e1c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686306616768299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d07f1517b1b1cba9</li>
        <li>Upwork Job ID: 1671998870894948352</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by DanutGavrus** [comment] 2023-06-19 17:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The search result still shows emoji for wrong texts.

### What is the root cause of that problem?
Right now, in `EmojiPickerMenu` we have this:
https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/components/EmojiPicker/EmojiPickerMenu/index.js#L73  
The `debounce` method makes the emoji picker seem _slow_(as seen in a video in the next section).

The filter was initially added in this [commit](https://github.com/Expensify/App/blob/c17f51a6c7ea09724d780a52e4e8286b08ca23ac/src/pages/home/report/EmojiPickerMenu.js#L24) with no debounce at all. The `debounce` was later added in this [commit](https://github.com/Expensify/App/blob/0f8454fac554699f3e831d88d246f6a70e3ff73b/src/pages/home/report/EmojiPickerMenu.js#L25) with a value of `500`, which was then reduced to `300` and remained unchanged from _April 2021_.

### What changes do you think we should make in order to solve the problem?
The `filter` method makes no network call and it executes very fast, so I would suggest to remove the `debounce` at all. If, for some reason, we need to keep the `debounce`, I would suggest to lower the value to the smallest one possible in order to make the picker as _fast_ as we can.  

We also need to keep both `index` and `index.native.js` in sync, so we need to make the same change in both files.  

I've made 2 videos for comparison:  
<details>
<summary>Picker with 300 debounce:</summary>
<video src="https://github.com/Expensify/App/assets/56603839/db6330d0-7ba8-489d-bae1-00ca11497156" />
</details>  

*NOTE: if you keep typing forever in the previous video, you will still see the emojis forever. It's when you stop typing that you see the "No results found." message eventually.  

<details>
<summary>Picker with no debounce:</summary>
<video src="https://github.com/Expensify/App/assets/56603839/c61d1776-e337-45b7-b727-1d1f662a91eb" />
</details>

I've also played with small values for the debounce, up to 50 I could not reproduce the bug, no matter how fast I was typing. At 100 it's reproducible, but not as easy as it's now. We may discuss if we want to remove it completely, or to just lower it to 50(or other value).

**Comment by sophiepintoraetz** [comment] 2023-06-22 04:15
Reassigning because Kadie is OOO and this should have hit her K2 (timezone takes a while to catch up with 0%!)

**Comment by mallenexpensify** [comment] 2023-06-22 21:51
@aimane-chnaif can you please review the proposals above, thx

**Comment by kadiealexander** [comment] 2023-06-26 03:27
Thanks for keeping this warm, Matt!

**Comment by kadiealexander** [comment] 2023-06-28 05:47
Bumped @aimane-chnaif [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1687931233823259).

**Comment by perunt** [comment] 2023-06-28 08:31
I originally implemented it for mobile. The debounce I used is the same as the one on the web. I wouldn't consider it a bug. Using debounce is a common practice to prevent excessive load on the JavaScript thread. Instead, we can focus on improving performance. Specifically, I would love to propose replacing the FlatList here and optimizing it.
@stitesExpensify we can make it much faster and decrease this delay. Perhaps it would make sense to incorporate this improvement within the scope of performance refactoring for the Emoji Picker.

**Comment by stitesExpensify** [comment] 2023-06-28 18:20
@perunt how much work do you think a refactor like that would take?

**Comment by perunt** [comment] 2023-06-29 11:40
If we only focus on switching the list, it would take a couple of hours. However, if we refactor the entire picker, it will take a few days. Also I noticed that this component is being migrated to a functional component, it makes sense to perform this task after the migration is complete

**Comment by DanutGavrus** [comment] 2023-06-30 13:01
@aimane-chnaif @stitesExpensify @perunt 
Sorry for the delay, I basically had to hack my own J3 phone because of some Google protection & a very old and forgotten Google account 😂 Unfortunately, the application was barely usable on this particular device, so it had no means to test the emojis.  

> Instead, we can focus on improving performance. Specifically, I would love to propose replacing the FlatList here and optimizing it.  

I also have a *Huawey P40 Lite*(mid-range phone from 2020) and I conducted the tests on it and the FlatList is indeed very slow depending on the nr of emojis it has to render. It's *very slow* when inserting 1 letter, *faster* when inserting the second letter, and *fast* from the 3rd and up as there are less resulted emojis to render.

What we may do for now:
1. Remove the `debounce` from the `filter` which is called at `onChangeText`;
2. Add `filterShortText` method with a `300 debounce`;
3. From the `filter` method, call the new `debounced filterShortText` method when the search's text length is maybe 0-1-2 characters long, or continue filtering here from the 3rd letter and up. I think this would also make sense in practice.

> If we only focus on switching the list, it would take a couple of hours. However, if we refactor the entire picker, it will take a few days. Also I noticed that this component is being migrated to a functional component, it makes sense to perform this task after the migration is complete  

As it may take quite some time until the component is migrated & then refactored to have improved performance(which also depends on the priority this component will have), this would be a small change for the time being(maybe it will also be worth keeping afterwards). Let me know your opinions about this 😁.

**Comment by avi-shek-jha** [comment] 2023-06-30 15:41
@stitesExpensify Still reproducible.

https://github.com/Expensify/App/assets/123831727/cc92f9b8-b8a9-4d7f-9a4d-d3cafefa19e0

**Comment by stitesExpensify** [comment] 2023-06-30 18:07
Ah I see, I misread the instructions. Honestly, with the amount of work it sounds like it would take to fix this properly, I don't think that it is worth it. It is _technically_ a bug, but IMO we should do nothing for now.

I think that waiting to search until you are done typing is a common pattern and makes sense. Additionally, we will be updating both our searching and our picker when we do custom emojis, so I don't want to waste time by doubling up the work doing this twice. I think that we should close. 

Thoughts @kadiealexander ?

**Comment by DanutGavrus** [comment] 2023-06-30 18:13
@stitesExpensify [This comment](https://github.com/Expensify/App/issues/21055#issuecomment-1614620142) would fix this bug and may also be kept after refactoring.  

Or would you say it's not worth it?

**Comment by stitesExpensify** [comment] 2023-06-30 18:37
@DanutGavrus can you give me a code example of what your proposal would look like? I'm having difficulty imagining it based on your discription

**Comment by DanutGavrus** [comment] 2023-06-30 18:52
@stitesExpensify Of course! I'm not at home right now, I'll create a testing branch tomorrow.

**Comment by stitesExpensify** [comment] 2023-06-30 19:55
No worries, I won't be back until Monday at the earliest (Tuesday is 4th of July Holiday in the US)

**Comment by kadiealexander** [comment] 2023-07-03 04:08
Not overdue.

**Comment by DanutGavrus** [comment] 2023-07-03 12:01
Started working on the testing branch, I'll add it here soon.

**Comment by DanutGavrus** [comment] 2023-07-03 14:17
@stitesExpensify The commit is [here](https://github.com/DanutGavrus/App/commit/a08c1bbdf1c4f692e659e8418fde699b9e80eda3).  

We use `debounced filter` when search text is short which requires *rendering many emojis and produces lag*;
We use `non-debounced filter` when search text length becomes longer which requires *rendering less emojis and does not produce lag*;  

This fixes this issue. In this demo I've called the `non-debounced filter` method when search text got to **3** characters and up, and let the `300 debounce filter` for <= **2** characters in search. Both may be adjusted if needed. You may play with it on web & mobile for a little. I've also made this short video for comparison:  

<video src="https://github.com/Expensify/App/assets/56603839/7c2ea676-8c1d-4614-85e8-25f91a31fdaa" />

**Comment by stitesExpensify** [comment] 2023-07-03 18:31
@perunt would you mind taking a look at that code and giving your opinion? While I like the idea, it feels a little "hacky" to me to only debounce sometimes and not others, but I'm curious if you disagree

**Comment by perunt** [comment] 2023-07-04 19:08
> @perunt would you mind taking a look at that code and giving your opinion? While I like the idea, it feels a little "hacky" to me to only debounce sometimes and not others, but I'm curious if you disagree

Yeah, I agree with you that the current solution feels a bit hacky, it's not an ideal approach. Although it partially solves the issue of showing wrong emojis during fast typing (I still have a blinking because, after the 3rd character, we fire it immediately)

https://github.com/Expensify/App/assets/48593211/338d0d34-21e9-4bd1-86ce-668f92266f62

if you are good to stay with that approach, I can suggest a shorter one(and less hacky). Change debounce to throttle  and put a timer to 150(it will still have this delay, but it would call each 150ms)
from 
` this.filterEmojisDebounced = _.debounce(this.filterEmojisDebounced.bind(this), 300);`
to 
` this.filterEmojisDebounced = _.throttle(this.filterEmojisDebounced.bind(this), 150);`
result:

https://github.com/Expensify/App/assets/48593211/4a6e19a3-07ab-43aa-b375-2fe6baee6b3e



If we have a bit more time we can do next:
1. use FlashList (it should be plug and play change)
2. reduce the debounce time to around 50-100 milliseconds. This will update the search results quickly as the user types, without noticeable delays.
3. if the rendering time is still noticeable or causing blinking issues, split the rendering process into 'initial' and 'rest.' Display the first dozen emojis instantly, and then the rest.

**Comment by DanutGavrus** [comment] 2023-07-04 20:06
@perunt Here are my thoughts:

> Change debounce to throttle and put a timer to 150(it will still have this delay, but it would call each 150ms)  

I've also played with `throttle`, but won't we encounter a new bug? If we have 3 characters in the search(**sez**), delete last and replace(**sea**) in under `150ms` to correct our mistake, I think that the `throttled filter` will fire only the first time showing a very long list of emojis, *the results of se instead of sea*? Or, if we input 2 characters in *<150ms*, won't we only see the resulting emojis for the first character only?

> reduce the debounce time to around 50-100 milliseconds. This will update the search results quickly as the user types, without noticeable delays.  

I've tried this too, works great on a flagship, but on a *P40 Lite*(2020 phone with decent hardware), the rendering of all emojis sometimes takes *>1000ms*, rendering for 1 letter *>500ms*, and keeps decreasing. On **50ms** we may be on the same bench as `no debounce` as I think it takes *>50ms* between each letter, specially on **native**.

> I still have a blinking because, after the 3rd character, we fire it immediately  

I also have a blinking while rapidly typing on my native messenger app(*mountain* for example) on my phone because they are also replaced immediately.  

> if the rendering time is still noticeable or causing blinking issues, split the rendering process into 'initial' and 'rest.' Display the first dozen emojis instantly, and then the rest.

This sounds interesting, I'm curious how will the scroll behave then.

> Yeah, I agree with you that the current solution feels a bit hacky  

I also agree, but for now it seems to make sense in practice regarding performance and typing bugs.

**Comment by perunt** [comment] 2023-07-05 08:20
I tried to play with sez -> sea and it uses the last changes for generating the filtered array. Am I doing it correctly? For reference, I tested it on pixel 2(2017) as well

https://github.com/Expensify/App/assets/48593211/f7b2af41-754e-46d6-ac41-aadc93bd4047


That's why I'm on the side of refactoring to make it better on the low-level device.
Also, we can consider creating a separate list for searching with absolute positions. It should decrease the time when you type first later erase it and type again

**Comment by DanutGavrus** [comment] 2023-07-05 11:26
> I tried to play with sez -> sea and it uses the last changes for generating the filtered array. Am I doing it correctly?

Yes, my bad, I tried to imagine before testing. As I see from testing now, with `150 throttle` it's almost the same as `no throttle`/`no debounce` at all as I'm getting re-renders for each change in search:  

https://github.com/Expensify/App/assets/56603839/d5b6daad-c3e1-4d11-816c-9efec3e670ad  
  
  
> For reference, I tested it on pixel 2(2017) as well

This is from my P40 Lite(2020) with current `300 debounce`:

https://github.com/Expensify/App/assets/56603839/f2e242a1-1012-4463-af32-47552879e0f7  
  
  
As it's already so laggy, I have concerns for having more re-renders by *removing debounce/replacing with throttle/reducing debounce time*.  

> That's why I'm on the side of refactoring to make it better on the low-level device.

I really do agree with you on this one!  

Also, as we may see from the P40 Lite video, it works *pretty fast from the 2rd character(exclusive) and up* and that's why I proposed that. *Refactoring to make it better on the low-level devices* is of course the way to go in the end.

**Comment by stitesExpensify** [comment] 2023-07-05 15:16
Wow that search is _very_ slow. If search is like that for a lot of old phones, then the solution might be to try using flashList like @perunt mentioned. I'm surprised that we haven't heard about that before... it seems pretty unusable on that device

**Comment by perunt** [comment] 2023-07-05 15:35
By the way, I also want to note that older devices slow down over time. So, in this case, we need to see how performance-intensive apps work on such devices. For instance, my Pixel 2 has become laggy and considerably slower, performing at about half its original speed or less.

My main point here is that we need to test these apps on older, but still functioning phones. It's a well-known fact that these devices slow down over time due to hardware deterioration.

**Comment by kadiealexander** [comment] 2023-07-06 04:48
Not overdue.

**Comment by perunt** [comment] 2023-07-06 08:20
@stitesExpensify would you like Margello to take care of it?

**Comment by stitesExpensify** [comment] 2023-07-06 16:12
@perunt Yes, I think that we should start 1/2 [here](https://github.com/Expensify/App/issues/21055#issuecomment-1620633044) and see where we end up.

**Comment by DanutGavrus** [comment] 2023-07-06 16:29
@perunt
> I also want to note that older devices slow down over time. So, in this case, we need to see how performance-intensive apps work on such devices. For instance, my Pixel 2 has become laggy and considerably slower, performing at about half its original speed or less. [...] we need to test these apps on older, but still functioning phones.

If it helps, I could re-test the search functionality, starting from opening the app, on the P40 Lite(with the app installed from the apk directly) and any other app(s) which you would like too see in comparison when the changes here are done.

**Comment by kadiealexander** [comment] 2023-07-11 06:49
@stitesExpensify @perunt should I assign you both here so that we can move forward with [this](https://github.com/Expensify/App/issues/21055#issuecomment-1623946316)?

**Comment by stitesExpensify** [comment] 2023-07-17 20:12
Bump @perunt

**Comment by perunt** [comment] 2023-07-18 15:42
I apologize for the delay. I've been occupied with migrating to `Composer` for `Inline Autosuggestion`. I need to continue focusing on `Inline Autosuggestion` for now. Would it be okay if I work on this task later this week? If that doesn't work for you, I can delegate it to another team member. Does that sound okay to you?

**Comment by stitesExpensify** [comment] 2023-07-19 12:58
No worries, I think this can wait. In the future if you can just keep us updated on when you'll get around to issues a little more proactively so that it doesn't go overdue that would be great!

**Comment by perunt** [comment] 2023-07-19 14:34
Okay, got you. I'll make sure to provide frequent updates and keep you in the loop

**Comment by kadiealexander** [comment] 2023-07-24 02:37
Not overdue.

**Comment by kadiealexander** [comment] 2023-07-26 21:58
Still not overdue! @perunt any updates so far?

**Comment by perunt** [comment] 2023-07-28 09:55
Yesterday, I tested it again. The main issue lies in the render time of the search list (i.e., the first letter). Even with FlashList, we can't significantly decrease this render time. We could consider using WishList, but it would first need to be adapted for Reports. Therefore, it's unlikely that this picker will see improvements anytime soon(from WishList).

I recorded a video that shows the general performance (which is quite poor) and another with the minor changes I've described before.
As @stitesExpensify mentioned, we aim to solve the issue without getting interrupted by performance regression out of scope (as we have some queues for perf updates).

So, here's what I propose next:
- If it's web and not mobile, we decrease the throttle time to 50-100 ms. This should search appear much faster.
- If it's the mobile web, we set the throttle time to 150-200 ms.

Ultimately, this solution should improve the issue on the web, resulting in a faster laptop experience and slightly less delay on the mobile web. I will provide four videos to demonstrate the difference, and you can decide what to do next, use this quick fix or think about refactoring. I want to be sure that we spend time in proper places 😃 
 I've conducted this comparison before, but now I have access to a HUAWEI P Smart 2019, which is a low-performance device that uses the Kirin 710 processor under the hood
**Before**

https://github.com/Expensify/App/assets/48593211/7852e78d-1e7d-46c8-a15f-d7c8f34c3f9e

https://github.com/Expensify/App/assets/48593211/224b4792-0aa5-4d5b-97bb-889cb15bbdb5


**After**

https://github.com/Expensify/App/assets/48593211/14bc0f85-123c-4b03-99df-f364678dff3b

https://github.com/Expensify/App/assets/48593211/5e99c666-a460-4b5a-8fa3-4f51dd0b5fb9

**Comment by stitesExpensify** [comment] 2023-07-28 18:21
I think we should just do the quick fix. IMO this is not worth spending a lot of time on given that we have much more important features that need to be built.

**Comment by perunt** [comment] 2023-07-29 11:00
If this fix above is good for you, then I can release [PR](https://github.com/Expensify/App/pull/23846) with it

**Comment by kadiealexander** [comment] 2023-08-01 01:40
@stitesExpensify are you happy to proceed here?

**Comment by stitesExpensify** [comment] 2023-08-01 16:21
Yep let's proceed. That PR looks good to me.

**Comment by kadiealexander** [comment] 2023-10-26 07:08
Payouts due:

Issue Reporter: $50 @avi-shek-jha
Contributor+: $500 @aimane-chnaif

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/jobs/~0163fda4e34b241b3a).

**Comment by kadiealexander** [comment] 2023-10-26 07:12
@aimane-chnaif I cannot access that contract anymore could you please link it here? Could you also please complete the BugZero checklist?

**Comment by kadiealexander** [comment] 2023-10-27 02:55
@aimane-chnaif please don't forget to link your offer!

**Comment by kadiealexander** [comment] 2023-10-31 04:26
Sent!

**Comment by kadiealexander** [comment] 2023-11-01 05:23
@aimane-chnaif bump to accept the Upwork contract.

**Closed** 2023-11-02 03:03 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
