### ISSUE TITLE
[Guides] Chats that are already read show up as unread in LHN

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#22603] opened 2023-07-11 01:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Select focus mode
2. Click into an unread chat
3. Navigate elsewhere

## Expected Result:
The chat that is already read shouldn't show in LHN as unread

## Actual Result:
The chat is shown as unread several seconds later

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.34-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** izaiah.rivera@team.expensify.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://github.com/Expensify/App/assets/22508290/6f69c066-f9c5-4d79-b029-f73fd00a1e2d

**Slack conversation:** https://expensify.slack.com/archives/C036S0BVAHH/p1688135931190779

**Comment by MariaHCD** [comment] 2023-07-12 09:53
Not able to 100% reproduce the issue in dev. But I managed to see it with:

1. A (non-high-traffic) account on an IOU report:

https://github.com/Expensify/App/assets/12268372/bb66f8b5-a84a-48b0-a618-7c89932baee9

2. A moderately high-traffic account (1000 chat reports with 5 report actions each):

https://github.com/Expensify/App/assets/12268372/5ff6a260-cf75-43f9-b06e-7925cfb04695

**Comment by MariaHCD** [comment] 2023-07-17 10:02
Update: 
- The guide that original reported the bug doesn't seem to be facing the issue anymore: https://expensify.slack.com/archives/C036S0BVAHH/p1689268396379479?thread_ts=1688135931.190779&cid=C036S0BVAHH. I looked in the deploy checklist for 2023-07-13 [here](https://github.com/Expensify/App/issues/22783), but couldn't see anything that might've touched on unread messages.
- The issue is being reproduced consistently for contributors@ because this email is intentionally being filtered out when updating the lastRead timestamp: https://expensify.slack.com/archives/C04JD99283A/p1689344967205299?thread_ts=1689202761.085489&cid=C04JD99283A
- We also see this happen (very inconsistently) for IOU reports: https://expensify.slack.com/archives/C04JD99283A/p1689345667761529?thread_ts=1689202761.085489&cid=C04JD99283A

Next steps:
1. Investigate how to fix the issue for contributors@
2. Investigate if this issue affects IOU reports, this issue doesn't seem to be 100% reproducible for IOU reports.
3. Keep an eye out if any guides report the issue again and have them follow [these instructions](https://expensify.slack.com/archives/C036S0BVAHH/p1689258622275319?thread_ts=1688135931.190779&cid=C036S0BVAHH)

Co-assigning you @MonilBhavsar! Let me know if I missed anything above.

**Comment by MonilBhavsar** [comment] 2023-07-17 12:09
> Investigate how to fix the issue for contributors@
Looks like we'll be using a new account to get ignore that condition in code

Sounds good 👍 

David thinks this issue is reproducible when using same account on different devices, pointing to unreliable pusher delivery - https://expensify.slack.com/archives/C04JD99283A/p1689375389197839

**Comment by sakluger** [comment] 2023-07-17 22:46
@MariaHCD @MonilBhavsar - The Guide savannah.expensify@instantteams.com says that this is still happening for her ([Slack thread](https://expensify.slack.com/archives/C036S0BVAHH/p1689604947813549?thread_ts=1689603182.450439&cid=C036S0BVAHH)). Maybe you could use the new V0 Supportal tool to try reproducing in her account? Instructions on using the supportal tool are here: https://stackoverflowteams.com/c/expensify/questions/16975/16976

**Comment by MariaHCD** [comment] 2023-07-20 09:02
Latest here: https://expensify.slack.com/archives/C04JD99283A/p1689785584377169?thread_ts=1689724796.767359&cid=C04JD99283A

**Comment by MonilBhavsar** [comment] 2023-07-24 10:10
Discussed in slack. Guides are actually facing this issue https://github.com/Expensify/App/issues/17316

**Comment by MonilBhavsar** [comment] 2023-07-25 10:05
I think we can bump the priority of this issue, as no one is experiencing it at the moment. As I mentioned above, guides are experiencing the other similar issue related to unread messages https://github.com/Expensify/App/issues/17316

**Comment by zanyrenney** [comment] 2023-07-28 11:07
sorry what do you mean bump? do you mean punt or reduce the urgency to weekly?

**Comment by MonilBhavsar** [comment] 2023-07-28 11:16
Yes, I did and Melvin updated to daily again. I think we can close this GH and this issue is no longer faced by anyone. Thoughts @kevinksullivan @sakluger

**Comment by zanyrenney** [comment] 2023-07-28 14:45
Closing in that case, we can reopen if we get more live cases of this!

**Closed by zanyrenney** 2023-07-28 14:45 UTC
Labels: Engineering, Daily, Internal, Needs Reproduction, Bug
