### ISSUE TITLE
[$1000]  On the first message of a thread the added reactions appear only after page refresh

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19238] opened 2023-05-18 23:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any message
2. Start a thread
3. Add a reaction

## Expected Result:
Reaction should appear immediately

## Actual Result:
Reaction appears only after a refresh of the page
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fcf41766-46ff-4e7b-a508-9da3c7de312f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684264413560439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f93ea0ecd14b3161</li>
        <li>Upwork Job ID: 1659537329240760320</li>
        <li>Last Price Increase: 2023-05-19</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-05-19 12:30
Reproduced on web: 


https://github.com/Expensify/App/assets/54866469/25d80b7c-6b86-483d-a7d0-f5be802607d2

**Comment by danieldoglas** [comment] 2023-05-19 15:28
@stitesExpensify I think this will be internal right?

**Comment by stitesExpensify** [comment] 2023-05-19 17:45
Yes it will be internal cc @chiragsalian

**Comment by YousefKhawaga** [comment] 2023-05-19 17:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 On the first message of a thread the added reactions appear only after page refresh
### What is the root cause of that problem?
the first message of a thread data comes from the parent action 
https://github.com/Expensify/App/blob/2182d0cb6eee479fa1c4d6f3fd9dd9cc9e97adbf/src/pages/home/report/ReportActionItemParentAction.js#L44
when we toggle the reaction Item we use the current reportID which won't update the parentID
https://github.com/Expensify/App/blob/2182d0cb6eee479fa1c4d6f3fd9dd9cc9e97adbf/src/pages/home/report/ReportActionItem.js#L179
### What changes do you think we should make in order to solve the problem?
we can check if the ReactionItem Rendered through ReportActionItemParentAction we use the parentID else we use the current reportID
https://github.com/Expensify/App/blob/2182d0cb6eee479fa1c4d6f3fd9dd9cc9e97adbf/src/pages/home/report/ReportActionItem.js#L179

### What alternative solutions did you explore? (Optional)
merging the parentAction with the current report action
https://github.com/Expensify/App/blob/2182d0cb6eee479fa1c4d6f3fd9dd9cc9e97adbf/src/pages/home/report/ReportActionItemParentAction.js#L44

**Comment by s77rt** [comment] 2023-05-19 21:44
@YousefKhawaga Thanks for the proposal. But this is going to be handled internally.

**Comment by joekaufmanexpensify** [comment] 2023-05-22 13:06
Next step here is for @danieldoglas to begin a PR!

**Comment by danieldoglas** [comment] 2023-05-23 02:28
Working on this soon, probably tomorrow or wed

**Comment by joekaufmanexpensify** [comment] 2023-05-23 20:21
Great, ty!

**Comment by joekaufmanexpensify** [comment] 2023-05-24 19:44
PR is pending here.

**Comment by danieldoglas** [comment] 2023-05-24 22:38
Pull requests are ready, awaiting for reviews/deploy.

**Comment by joekaufmanexpensify** [comment] 2023-05-26 18:23
Adding an additional BZ assignee as I'm OOO next week (and will be returning on June 5th). Both PRs for this issue are in review, so the next step here is to just watch the issue in case anything comes up until I'm back.

**Comment by joekaufmanexpensify** [comment] 2023-05-26 18:23
Adding an additional BZ assignee as I'm OOO next week (and will be returning on June 5th). Both PRs for this issue are in review, so the next step here is to just watch the issue in case anything comes up until I'm back.

**Comment by danieldoglas** [comment] 2023-05-29 10:14
Update:

We found another bug in threads that blocks this. Both PRs are ready, once that bug is fixed we can just merge main into my branches and review.

**Comment by joekaufmanexpensify** [comment] 2023-06-04 16:14
I'm back from vacation, so removing your assignment @isabelastisser , thanks for covering!

**Comment by joekaufmanexpensify** [comment] 2023-06-08 18:25
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2023-06-14 19:11
@danieldoglas I saw both internal PRs are now out on production. Is anything else still needed here?

**Comment by danieldoglas** [comment] 2023-06-15 00:22
No, this is done!

**Closed by danieldoglas** 2023-06-15 00:22 UTC
Labels: Reviewing, Daily, Internal, Bug
