### ISSUE TITLE
[HOLD for payment 2022-11-22] [$250]  Routing number field doesn't get auto focused after opening the page reported by @Puneet-here

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11423] opened 2022-09-29 16:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to settings > workspace > connect bank account
2. Connect manually

## Expected Result:
Routing number field should get focused

## Actual Result:
 It doesn't get focused

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/193083990-640a22f3-a01b-44f2-93be-303bcda6cd3b.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663687968571139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment] 2022-09-29 16:19
### Proposal

We can use autoFocus here https://github.com/Expensify/App/blob/7c29d89afe94b8e2f178e55b8f0137c91b1283c8/src/pages/ReimbursementAccount/BankAccountManualStep.js#L116

**Comment by zanyrenney** [comment] 2022-09-29 16:53
I can't repro this, but from the video, it looks good for eng.

**Comment by MitchExpensify** [comment] 2022-09-29 22:02
[Upwork Job](https://www.upwork.com/jobs/~0131bb47d4ef5fcfdd)

**Comment by 16NTU116** [comment] 2022-09-29 22:26
### Proposal
It can be solved by the following:
1. Using autoFocus prop. [Reference](https://reactnative.dev/docs/textinput#autofocus) 
2. Use ref prop by setting it in componentDidMount or in useeffect

**Comment by MonilBhavsar** [comment] 2022-10-03 09:32
@Santhosh-Sellavel could you please take a look at the proposals when you get chance

**Comment by Santhosh-Sellavel** [comment] 2022-10-03 17:04
@Puneet-here Can you add behavior to all platforms here, thanks!

**Comment by Santhosh-Sellavel** [comment] 2022-10-03 19:41
Also @MonilBhavsar Please confirm if the autofocus is expected here with the design/product team.  Autofocus creates weird keyboard issues in native I believe intentionally we don't set `autofocus`, thanks!

**Comment by Santhosh-Sellavel** [comment] 2022-10-03 19:43
@MitchExpensify or @MonilBhavsar 
Due to Limited Availability unassigning this one. Can you reapply the external label to get another C+ assigned thanks!

**Comment by MonilBhavsar** [comment] 2022-10-04 13:36
> Please confirm if the autofocus is expected here with the design/product team. Autofocus creates weird keyboard issues in native I believe intentionally we don't set autofocus, thanks!

We discussed internally and in this particular case we want to set the autoFocus, so we're open to proposals!

**Comment by Puneet-here** [comment] 2022-10-04 14:22
Safari macOS:

https://user-images.githubusercontent.com/101883770/193843212-4d171439-493c-44d9-b1ef-0f85db8fb700.mov

Safari Ios:

https://user-images.githubusercontent.com/101883770/193843223-c8f41a38-7535-4513-9a63-41c494c23630.mov

We can also use `shouldDelayFocus` to be on the safer side.

**Comment by MonilBhavsar** [comment] 2022-10-04 14:45
Sorry, forgot to mention. In this particular case, we also want keyboard to open on Mobile devices when the field is auto focussed.

**Comment by Puneet-here** [comment] 2022-10-07 20:36
Yeah the keyboard opens, it was on simulator and I hadn't turned on the soft keyboard. I have checked it and it's working.

**Comment by syedsaroshfarrukhdot** [comment] 2022-10-12 06:35
**Proposal**

The issue on android is due to transitions so we should wait for transitions to complete before focusing the input so we could to pass autoFocus and shouldDelayFocus props to TextInput and it fixes the of keyboard opening issue on android and ios.

<img width="779" alt="Screen Shot 2022-10-12 at 11 25 26 AM" src="https://user-images.githubusercontent.com/81307212/195267126-94541f22-0913-4fcc-a8a3-013e3a9c4f72.png">

**After Fixing:-**

https://user-images.githubusercontent.com/81307212/195267473-2a4d8430-66eb-4782-9d08-fb0fc8033fa6.mov

**Comment by syedsaroshfarrukhdot** [comment] 2022-10-12 14:26
@rushatgabhane  We can handle shouldDelayFocus on only on android Platform  by introducing Platform.OS === 'android' just like below

<img width="851" alt="Screen Shot 2022-10-12 at 7 24 33 PM" src="https://user-images.githubusercontent.com/81307212/195369523-db9cd8f4-e262-4fd1-81fd-b16c0cedfd69.png">

**Comment by Puneet-here** [comment] 2022-10-12 17:35
Can we use two files index.ios.js and index.android.js instead of https://github.com/Expensify/App/blob/main/src/libs/ComponentUtils/index.native.js and add a variable for this which will be only true at android and we can use it whenever we use `shouldDelayFocus` like we do for other props or we can also use two platform specific files for TextInput instead of https://github.com/Expensify/App/blob/main/src/components/TextInput/index.native.js
for android.js we can pass `shouldDelayFocus`

**Comment by MitchExpensify** [comment] 2022-10-19 22:56
Any update here?

**Comment by MitchExpensify** [comment] 2022-10-25 00:04
> @MonilBhavsar maybe you could buddy check my comment https://github.com/Expensify/App/issues/11423#issuecomment-1281134156

lil bump @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2022-10-27 12:10
Sorry, looking.
Since we already have that _hack_ in other components, I'm fine moving with that and create a new issue to investigate and get rid of that hack. Thoughts?

**Comment by Puneet-here** [comment] 2022-10-27 15:49
I don't like the idea of choosing a duplicate proposal just because it explained `shouldDelayFocus`.  I didn't explain the use because we are already using it at many pages so I was expecting its use will be known.

**Comment by MonilBhavsar** [comment] 2022-10-28 06:14
> Alright, delay focus is needed on android only when there is a page transition.

👍 After briefly looking, it seems like the input element is not referenced immediately and this hack as a solution was suggested in some SO's. But yes, I feel like there should be some workaround. So we can open an issue and investigate.

**Comment by MonilBhavsar** [comment] 2022-10-29 10:36
As @Puneet-here posted the proposal first and `shouldDelayFocus` was mentioned in it. Let's hire Puneet.

**Comment by syedsaroshfarrukhdot** [comment] 2022-10-29 12:44
@MonilBhavsar I know the proposal had mentioned `shouldDelayFocus` but I posted a proposal on the first place was that the last proposal didn't explain the `shouldDelayFocus` and why it is needed it just mentioned that it is needed to be on safer side on @rushatgabhane comment that autoFocus is not opening keyboard on android I figured out that only on android to open keyboard we need to provide s`shouldDelayFocus`. So I believe my proposal was better than the previous one where it wasn't explained as I specified its need only on android.

As, according to contributing guidelines I believe my proposal was the proposal addressing the problem on android and solving that issue as mentioned below in contributing guidelines.

<img width="1080" alt="Screen Shot 2022-10-29 at 5 31 20 PM" src="https://user-images.githubusercontent.com/81307212/198831676-d190d3bb-e686-401b-90f0-89053965de41.png">

**Comment by MonilBhavsar** [comment] 2022-11-07 12:09
Since, shouldDelayFocus is already used in our codebase in platform specific files. For example [here](https://github.com/Expensify/App/blob/main/src/components/PasswordPopover/index.android.js). It was understandable why shouldDelayFocus was required.
Thanks for proposing a solution though.

**Comment by MonilBhavsar** [comment] 2022-11-10 12:52
> The PR that introduced the bug has been identified. Link to the PR:

I think this was missed and not a regression by any PR. @rushatgabhane thoughts?

**Comment by MitchExpensify** [comment] 2022-11-13 16:18
Seeing as this wasn't a regression, I'm thinking that this step can be skipped in this case:

> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I'm undecided if this still makes sense for the same reason:

>. A discussion in #contributor-plus has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Curious what you think @puneetlath ?

**Comment by puneetlath** [comment] 2022-11-14 20:51
In that case, I think the offending PR would be the one that created this feature.

**Comment by MitchExpensify** [comment] 2022-11-16 18:41
> I think the offending PR would be the one that created this feature.

Thats fair. @MonilBhavsar / @rushatgabhane mind tracking that down and [linking here](https://github.com/Expensify/App/issues/11423#issuecomment-1310214192)?

**Comment by MitchExpensify** [comment] 2022-11-16 18:42
Made a note on my cal to pay on 11/22

**Comment by MitchExpensify** [comment] 2022-11-22 21:16
Paid @Puneet-here for reporting bonus and fix 

@rushatgabhane sent you an invite for C+ payment

**Comment by MitchExpensify** [comment] 2022-11-23 17:02
@rushatgabhane All good! It is accepted. Payment made > Contract ended

**Comment by MonilBhavsar** [comment] 2022-11-25 05:34
Are we good to close this now?

**Comment by MonilBhavsar** [comment] 2022-11-25 05:58
Thanks! I see the the checklist needs still needs to be completed https://github.com/Expensify/App/issues/11423#issuecomment-1310214192

**Comment by MonilBhavsar** [comment] 2022-11-25 07:12
> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

Not a bug. May be It is like this since it was introduced.

> A discussion in #contributor-plus has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I think when we add a form component, PR author can start a discussion in slack if we want to autofocus field when we open the form. In this way we can prevent these kind of bugs.

cc @MitchExpensify

**Comment by MitchExpensify** [comment] 2022-12-01 00:51
Sorry I've been sick the last few days! Started the discussion about how to avoid this going forward here

**Closed by MitchExpensify** 2022-12-01 00:51 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
