### ISSUE TITLE
[Regression #12066] Manage members - When removing a user offline from workspace, user is not crossed out

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12770] opened 2022-11-16 14:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Tap on Profile > Workspace > Manage Members
4. Invite any user to the workspace
5. Turn off internet connection and remove the user

## Expected Result:
User expects that when removing a user offline that the user is crossed out and slightly greyed out

## Actual Result:
When removing a user offline from workspace, user is not crossed out

# Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.28.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/202212172-389285f4-a720-4d3b-afc2-bb1522b580bb.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arielgreen** [comment] 2022-11-16 21:58
https://www.upwork.com/jobs/~01dfbfdaac1037594e

**Comment by thesahindia** [comment] 2022-11-17 10:01
Not completely sure but this might be a regression from https://github.com/Expensify/App/pull/12545

cc: @sobitneupane @tienifr

**Comment by sobitneupane** [comment] 2022-11-17 10:22
> Not completely sure but this might be a regression from https://github.com/Expensify/App/pull/12545

Yeah. I think https://github.com/Expensify/App/pull/12545 is the culprit. 

@tienifr Can you raise a PR to fix this issue? I believe this should be pretty simple.

**Comment by parasharrajat** [comment] 2022-11-17 10:35
We can take down the job @arielgreen and assign @sobitneupane as C+ for handling the Regression.

**Comment by Julesssss** [comment] 2022-11-17 10:47
Thanks all, I can 100% confirm the linked issue caused the regression. Just tested the PR and the final commit prior to it being merged.

**Comment by Julesssss** [comment] 2022-11-17 10:47
I don't think this is critical enough to be a deploy blocker.

**Comment by tienifr** [comment] 2022-11-19 06:36
Hi @sobitneupane I just created a PR for fixing this issue, please help to pre-check, if you agree with my fixing I will complete the PR later. Thanks 
https://github.com/Expensify/App/pull/12878

**Comment by arielgreen** [comment] 2022-11-21 21:37
Thanks, removed job from Upwork.

**Comment by mvtglobally** [comment] 2022-11-22 21:20
Issue not reproducible during KI retests. (First week)

**Comment by arielgreen** [comment] 2022-11-24 15:49
Not overdue, this is being handled in #10266

**Comment by Julesssss** [comment] 2022-11-28 11:09
PR merged, awaiting deployment to prod

**Comment by mvtglobally** [comment] 2022-11-30 05:03
Issue not reproducible during KI retests. (Second week)

**Comment by parasharrajat** [comment] 2022-12-01 11:06
No payment's here it was a regression.

**Comment by arielgreen** [comment] 2022-12-08 21:25
@parasharrajat @sobitneupane @Julesssss please be sure to complete your steps in the [checklist](https://github.com/Expensify/App/issues/12770#issuecomment-1329711135).

**Comment by sobitneupane** [comment] 2022-12-09 03:51
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed: 
* [x]  [@parasharrajat / @sobitneupane / @Julesssss] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/12545

* [x]  [@parasharrajat / @sobitneupane / @Julesssss] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/12545#issuecomment-1318439149
* [x]  [@parasharrajat / @sobitneupane / @Julesssss] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression was caused because I was unaware of the feature that the user is crossed out when removing offline.

**Closed** 2022-12-09 20:04 UTC
Labels: Reviewing, External, Engineering, Daily, Improvement, Awaiting Payment, Bug
