### ISSUE TITLE
Web - Payment - An error when trying to mark the withdrawal account as the default

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12075] opened 2022-10-22 01:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go URL https://staging.new.expensify.com/
2. Login with Expensifail account
3. Go to Settings->Workspace->Connect Bank account->Connect with Plaid
4. Choose Fidelity bank
5. Enter your credentials and company information
6. After added new bank account go to Settings->Payment
7. Try to mark the withdrawal account as the default

## Expected Result:
The payment method should be marked as the default

## Actual Result:
An error when trying to mark the withdrawal account as the default

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** N/A

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/197309667-c22aad82-d57a-4c56-8f51-34cf4554f3fb.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-10-24 17:18
Error messages come from the API so I think this should be Internal

**Comment by JmillsExpensify** [comment] 2022-10-25 10:13
Given that this is a bug, I think we should have a BZ team member assigned. Adding the auto-assigner.

**Comment by JmillsExpensify** [comment] 2022-10-25 10:17
Looks like that didn't work. Going with triage instead.

**Comment by miljakljajic** [comment] 2022-10-26 17:10
Looks good - adding the engineering label since we're handling internally.

**Comment by miljakljajic** [comment] 2022-10-26 17:11
Ah, apologies - it's been added!

**Comment by miljakljajic** [comment] 2022-10-31 16:48
To be clear then @JmillsExpensify, given t[his discussion](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064935349459), should I add the `demolition` label?

**Comment by JmillsExpensify** [comment] 2022-11-01 23:32
Yes, exactly!

**Comment by michaelhaxhiu** [comment] 2022-11-03 21:43
This one was just assigned to Monil and so I'm sure he'll be able to get some movement in coming days! Will leave this to @miljakljajic @MonilBhavsar to help drive forward 👍

**Comment by MonilBhavsar** [comment] 2022-11-04 08:07
I'll take a look

**Comment by miljakljajic** [comment] 2022-11-08 18:38
@MonilBhavsar did you find anything?

**Comment by MonilBhavsar** [comment] 2022-11-09 09:41
Was able to reproduce the issue
The error for this particular use case is thrown from [here](https://github.com/Expensify/Auth/blob/f3e3da4def086ccc05ce0e533bfeed82ae596f3d/auth/command/SetWalletLinkedAccount.cpp#L56). [Logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id%3A%2275dbe1dc9d8e22fb-LAX%22)
This error is thrown when we account is not in OPEN state or of type PERSONAL. In this case it is an OPEN account, but is of type BUSINESS. 
Chatting with @MariaHCD to figure it out since she has more context about Bank accounts and wallet.

**Comment by MonilBhavsar** [comment] 2022-11-10 08:29
When user adds VBBA by going to Workspace > Connect Bank account.
We display that bank account in Payments Page (Profile > Payments) and on tapping that account, an option to make it a default payment method. But we have a backend validation where we can't set business bank account as default method.
We can fix this by not displaying "Make default payment method" in Payments page for Business Bank account. Thoughts?

**Comment by MonilBhavsar** [comment] 2022-11-15 13:20
^ Worth a discussion in #product?

**Comment by JmillsExpensify** [comment] 2022-11-15 17:32
Yes, I think that's a good discussion for #product. I also like the solution, but let's get more conversation going to confirm we all agree that's the best page. For instance, we also might think about adding "badges" to the bank accounts so that it's more clear why some bank accounts (e.g. biz) are treated differently than others (e.g. personal).

**Comment by michaelhaxhiu** [comment] 2022-11-15 18:04
>For instance, we also might think about adding "badges" to the bank accounts so that it's more clear why some bank accounts (e.g. biz) are treated differently than others (e.g. personal).

Oooh nice idea! I'll stay tuned for that #product discussion 🤓

**Comment by MonilBhavsar** [comment] 2022-11-16 11:05
@michaelhaxhiu Please join https://expensify.slack.com/archives/C03U7DCU4/p1668596349084729

**Comment by MonilBhavsar** [comment] 2022-11-28 10:39
PR is merged!

**Comment by MonilBhavsar** [comment] 2022-11-28 10:42
I think we can close this, or we have to complete the checklist?

**Closed** 2022-11-28 12:36 UTC
Labels: Engineering, Daily, Demolition, Internal, Bug
