### ISSUE TITLE
[$250] Android - Search - Paid & Approved status is not tappable after opening expense in All status

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47684] opened 2024-08-20 07:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh05081@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
PPrecondition:
- Physical (real) device is required to reproduce this issue.

1. Launch New Expensify app.
2. Go to Search.
3. Go to Paid.
4. Note that Paid tab is tappable.
5. Go to All.
6. Open any expense.
7. Tap app back button to return to All.
8. Scroll the status bar.
9. Tap on Paid and Approved status.

## Expected Result:
Paid and Approved status should be tappable after opening an expense in All tab.

## Actual Result:
Paid and Approved status is no longer tappable after opening an expense in All tab.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a5354fdc-7700-4e15-9a92-dc76c2787ba7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0182def85840821943</li>
        <li>Upwork Job ID: 1825893542863089341</li>
        <li>Last Price Increase: 2024-08-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by IuliiaHerets** [comment] 2024-08-20 07:46
We think that this bug might be related to  #wave-collect - Release 1

**Comment by flodnv** [comment] 2024-08-20 08:19
Well for me I can't even tap `Paid` to start with 😕 How about you @joekaufmanexpensify? 

This does seem like a blocker.

**Comment by flodnv** [comment] 2024-08-20 08:22
Probably caused by https://github.com/Expensify/App/pull/47181 @luacmartins @arosiclair @rayane-djouah ? I'll let you decide whether this should be a blocker.

**Comment by joekaufmanexpensify** [comment] 2024-08-20 13:31
@flodnv I don't have a physical android device. I tried to reproduce via browserstack, but scrolling to the paid tab doesn't work (I assume hence the precondition in the reproduction steps). But I agree if you can't tap the paid tab at all, that does indeed feel like a blocker.

**Comment by luacmartins** [comment] 2024-08-20 13:52
Yea, that looks like a blocker to me. Adding the external label to get more eyes on it

**Comment by luacmartins** [comment] 2024-08-20 13:53
I'll take this over since my PR is introducing this feature

**Comment by luacmartins** [comment] 2024-08-20 21:04
We reverted the offending PR. Closing.

**Closed by luacmartins** 2024-08-20 21:04 UTC
Labels: Reviewing, DeployBlockerCash, External, Engineering, Weekly, Help Wanted, Bug
