### ISSUE TITLE
DEV: Web - Console error when clicked on Reimbursements

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23849] opened 2023-07-29 11:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open settings > Workspaces >
2. Select a workspace from the list
3. Click Reimbursements

## Expected Result:
There shouldn't be a console error

## Actual Result:
onsole error: `Warning: Failed prop type: The prop `innerRef` is marked as required in `PressableWithDelayToggle`, but its value is `null`.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/27b3d467-2995-4cf8-b5dd-968b435dafb4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690619039709079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment] 2023-07-31 11:09
Adding engineering to confirm reproduction.

**Comment by joh42** [comment] 2023-08-01 13:42
The same error is also present on the 2FA page (Settings > Security > Two-factor authentication)

**Comment by gadhiyamanan** [comment] 2023-08-01 13:56
this is dupe of https://github.com/Expensify/App/issues/23093

**Closed** 2023-08-01 14:33 UTC
Labels: Engineering, Daily, Needs Reproduction, Bug
