### ISSUE TITLE
[$250] Scan split - Group chat with scanning split expense disappers from LHN when navigating away

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41185] opened 2024-04-29 00:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Split expense.
3. Create a manual split expense with a few users.
4. Go to a different chat.
5. Note that the group chat remains in LHN.
6. Go to FAB > Split expense.
7. Create a scan split expense with a few users.
8. Go to a different chat.

## Expected Result:
The group chat with scanning split expense will remain in LHN when navigating away from it.

## Actual Result:
The group chat with scanning split expense disappers from LHN when navigating away from it.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/abbac58f-d2a7-40d6-a4f8-5b4fc67d86fc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef7f9695267557e2</li>
        <li>Upwork Job ID: 1784885067934978048</li>
        <li>Last Price Increase: 2024-04-29</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-04-29 00:13
@garrettmknight FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors. 

We think this bug might be related to #vip-split

**Comment by m-natarajan** [comment] 2024-04-29 00:13
We think this bug might be related to #vip-split

**Comment by marcaaron** [comment] 2024-04-30 21:59
This is a duplicate of https://github.com/Expensify/App/issues/40314

**Closed by marcaaron** 2024-04-30 21:59 UTC
Labels: External, Daily, Help Wanted, Bug
