### ISSUE TITLE
[$250] Admin's name is showing as blank after Editing anything on profile page - Reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10891] opened 2022-09-08 05:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website.
2. Go to settings > profile > edit anything and save
3. Then go to workspace manage member page and see admin's name.

## Expected Result:
Name shouldn't be showing as blank

## Actual Result:
It's showing blank until user refreshes the website.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.1.96-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/189038101-228df7d0-eab0-42ba-abcc-0cc36b44fb58.mp4

https://user-images.githubusercontent.com/43995119/189038104-6e37003a-4479-4e7c-91a1-ef172b8b166c.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661322811349869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by varshamb** [comment] 2022-09-08 18:57
### Proposal

User profile has First Name and Last Name already updated

![image](https://user-images.githubusercontent.com/111683206/189201377-a103079c-1a56-4340-b016-07c3d17a5cfb.png)


Workspace Manage member page then

![image](https://user-images.githubusercontent.com/111683206/189201434-be11b0fd-563f-468e-9f6d-45d54856c008.png)

First Name and Last Name removed (made blank) from User profile and Saved.

![image](https://user-images.githubusercontent.com/111683206/189201514-7a03c85f-7aa9-4c08-a40b-51da44ffaadd.png)

Workspace Manage member page then

![image](https://user-images.githubusercontent.com/111683206/189201580-bdeeb63f-4003-4c91-a980-643a69e473fa.png)

Again User profile page opened and saved without changing anything and visited Workspace Manage member page.

![image](https://user-images.githubusercontent.com/111683206/189201660-c495b653-444c-4289-b6d3-a51fb13dcb92.png)

Will it be okay if we only display LoginID only once.

![image](https://user-images.githubusercontent.com/111683206/189202514-ab662b41-621f-4c98-b08a-3e0aa1c573ac.png)

**Comment by danieldoglas** [comment] 2022-09-13 11:50
will look at this tomorrow

**Comment by danieldoglas** [comment] 2022-09-16 11:24
We can export this one.

**Comment by stephanieelliott** [comment] 2022-09-20 02:11
Posted to Upwork: https://www.upwork.com/jobs/~013fb8003f81392003

As the reporter, @Tushu17 has right of first refusal on this one.

**Comment by Tushu17** [comment] 2022-09-20 09:18
Hey @stephanieelliott, the policy has changed now the reporter doesn't get dibs on an issue. Anyone can post a solution.

**Comment by stephanieelliott** [comment] 2022-09-21 03:45
Oh cool, thanks @Tushu17!

**Comment by stephanieelliott** [comment] 2022-09-21 03:50
Re-applied the `External` label, it didn't apply the assignments correctly the first time. @rushatgabhane we have a proposal [here](https://github.com/Expensify/App/issues/10891#issuecomment-1250913836) when you get a chance!

**Comment by iwiznia** [comment] 2022-09-23 13:55
Almost sure this is a dupe of https://github.com/Expensify/App/issues/11134 and we can close this

**Comment by Tushu17** [comment] 2022-09-23 15:48
> Almost sure this is a dupe of #11134 and we can close this

Hey @iwiznia, This issue was reported and created before #11134. So I think we should close the other issue.

**Comment by iwiznia** [comment] 2022-09-23 16:43
Sounds good to me

**Comment by stephanieelliott** [comment] 2022-09-27 13:05
Cool! Ok, removing the `Help Wanted` label since we have a fix for this already.

**Comment by iwiznia** [comment] 2022-10-05 15:14
Oh, BTW, this is already fixed too. @stephanieelliott reporting payment is needed, please check if you agree with my message above.

**Comment by iwiznia** [comment] 2022-10-06 13:01
@rushatgabhane is technically correct, but in this case, there were a few mishaps in the issue, like there were 2 issues created (but only one was needed) and they were marked as external when they were really internal. Due to that and the fact that you did spend time debugging it and helped @parasharrajat, I think we should pay out $250 (same as reporting bonus) in good faith. 

One minor note: if the issue is in the backend, we should not attempt to fix it in the frontend. so saying  for next time if there's a similar issue, it's better to not add frontend proposals and instead commenting something like:
> This issue is coming from the backend, data in the property X of the onyx key Y, that gets set after calling the API command Z is sending bad data: it should not return & symbols html escaped.

Thanks for your help and look forward to working with you again!

@stephanieelliott can you pay @aimane-chnaif $250 please?

**Comment by parasharrajat** [comment] 2022-10-06 13:19
Thanks, @iwiznia for following up. There is something I want to add. 

We strictly follow our documented guidelines. There can be exceptions but no one should expect those. If someone feels that something is not done as per the guidelines, we will be happy to help you understand or fix our mistake. 

For this issue, 
- As per guidelines, no solution was accepted thus technically none of those proposals is eligible for payment. The same can be seen in my comment. I explained the reasons why solution 1 and solution 2 were not the best things to do. 

At last, I agree with @iwiznia's decision and look forward to more contributions from you and I am sure there won't be many such cases. 
Thank you.

**Comment by stephanieelliott** [comment] 2022-10-10 20:34
Hey @aimane-chnaif, can you please grab the job on Upwork? We’ll use that to pay you https://www.upwork.com/jobs/~013fb8003f81392003

**Comment by stephanieelliott** [comment] 2022-10-14 22:05
All paid up!

**Closed by stephanieelliott** 2022-10-14 22:05 UTC
Labels: Reviewing, Engineering, Daily, Improvement
