### ISSUE TITLE
Workspace - The added bank account isn't visible in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33908] opened 2024-01-03 21:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21.1
**Reproducible in staging?:** y
**Reproducible in production?:** can not check production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Add a workspace
4. Finish adding a Chase Plaid bank account (You're all set! message is visible)
5. Click away to close the side page
6. Go offline
7. Navigate to workspace - Bank account

## Expected Result:
It should be visible.

## Actual Result:
The added bank account isn't visible in offline mode.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/28029600-4a83-43b8-b94e-f2cfb702ede7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2024-01-04 00:42
this seems to be a dupe of https://github.com/Expensify/App/issues/33890

**Closed** 2024-01-04 00:49 UTC
Labels: Engineering, Hourly
