### ISSUE TITLE
[$500] Workspace request thread shows the AM's timezone, not the request sender's timezone

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27474] opened 2023-09-14 21:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Decide a private domain that you want to use for testing
2. Ask a member of the Concierge team to set a that domain as having an account manager (any account manager will do, so they can set themselves as the account manager)
3. Sign in to account A from that private domain, and create a workspace
4. Invite account B (from the save private domain) to that workspace
5. Sign in to account B, and go to the workspace chat for that new workspace
6. As account B, send a request in that workspace chat
7. Sign in to Account A, go to the workspace chat with account B, and click on the request thread for account B (ie: "WorkspaceName owes $x"
8. Observe the name and timezone at the bottom of the list of requests
9. Click on an individual request (ie: "Cash")
10. Observe the name and timezone at the bottom of the individual request
## Expected Result: 
At step 8, I expected to see the request sender's first name and timezone (which should match step 10)
## Actual Result: 
At step 8, I incorrectly saw the account manager's first name and timezone. At step 10, I correctly saw the request sender's first name and timezone.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/50395473-0421-4e23-a30a-ae1415100be7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @conorpendergrast 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693994843908319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137af0b4532497312</li>
        <li>Upwork Job ID: 1702755706356289536</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by mollfpr** [comment] 2023-09-18 10:16
No proposals.

**Comment by isabelastisser** [comment] 2023-09-20 20:40
Still waiting for proposals!

**Comment by isabelastisser** [comment] 2023-09-27 19:07
Bump @mollfpr

**Comment by mvtglobally** [comment] 2023-09-28 03:20
Issue not reproducible during KI retests. (First week)

**Comment by mollfpr** [comment] 2023-09-28 14:41
Sorry for the delay. I couldn't reproduce the issue.

**Comment by isabelastisser** [comment] 2023-09-29 15:41
Thanks @mollfpr ! Closing.

**Closed by isabelastisser** 2023-09-29 15:41 UTC
Labels: External, Daily, Help Wanted, Bug
