### ISSUE TITLE
[HOLD for payment 2022-10-31] [$250] After Creating group, email address of only one user is used in alternate Text reported by @sobitneupane

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11300] opened 2022-09-26 21:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. New Group > Create Group
2. Scroll down to newly created group in LHN.

## Expected Result:
Comma separated emails of group members as alternateText

## Actual Result:
Email of only one user is shown

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.2.7-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/192380802-709e5c68-d010-4ee0-b82e-e921f07717d5.mp4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @sobitneupane 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment] 2022-09-26 21:20
I am not sure if the way we present the alternateText in the LHN is by design or is an actual bug. I am going to assign out to engineering to get a second pair of eyes.

**Comment by Justicea83** [comment] 2022-09-28 14:28
Looking into the code to see if something might be wrong here

**Comment by Justicea83** [comment] 2022-09-28 15:20
Wanted to clarify something before I assign the internal label, you can follow [the thread here](https://expensify.slack.com/archives/C03TQ48KC/p1664378389551639).

**Comment by Justicea83** [comment] 2022-09-29 11:16
We want to replace the alternate text with `This is the beginning of your chat history with Person, Person, and Person`

**Comment by puneetlath** [comment] 2022-10-03 21:50
@eVoloshchak what do you think of the proposal?

**Comment by eVoloshchak** [comment] 2022-10-03 21:56
> @eVoloshchak what do you think of the proposal?

I wasn't able to fully test it yet, experiencing some weird problems (`createOption` is called multiple times, which breaks the proposed solution), still trying to figure out if it's the problem with the code or my environment. 

Expect an answer in 14 hours

**Comment by eVoloshchak** [comment] 2022-10-04 15:02
@Ollyws, your proposal doesn't work for me, but you've correctly identified the root cause of the problem

1. Correct me if I'm wrong, but [createOption](https://github.com/Expensify/App/blob/1ff9206ec817a44a368125fec9910bfd75ce0157/src/libs/OptionsListUtils.js#L239) function is not the one responsible for `alternateText` for LNH. [getOptionData](https://github.com/Expensify/App/blob/1ff9206ec817a44a368125fec9910bfd75ce0157/src/libs/SidebarUtils.js#L225) is the correct function, we need to change the  `alternateText` there
2. We need to match the logic implemented [here](https://github.com/Expensify/App/blob/1ff9206ec817a44a368125fec9910bfd75ce0157/src/components/ReportWelcomeText.js#L101), i.e. 

- separate emails with commas, add "and" before the last email, add a dot after the last email (one@mail.com, two@mail.com and three@mail.com.) not (one@mail.com, two@mail.com, three@mail.com)
- display pronouns for users if there are any

Essentially we need to make sure the text is identical in LHN and in the chat window itself when you select it

**Comment by puneetlath** [comment] 2022-10-11 13:18
@eVoloshchak what do you think?

**Comment by puneetlath** [comment] 2022-10-11 17:53
Ah, right you are. 

Internal upwork job: https://www.upwork.com/ab/applicants/1579892682555052032/job-details
External upwork job: https://www.upwork.com/jobs/~01d614951b96cdb960

@Ollyws @sobitneupane @eVoloshchak can you all apply there? Thanks!

**Comment by eVoloshchak** [comment] 2022-10-12 14:35
@Ollyws, looks readable to me, let's proceed with the PR

**Comment by puneetlath** [comment] 2022-10-21 17:28
PR has been merged. Just waiting for deploy and then regression period.

**Comment by puneetlath** [comment] 2022-10-31 18:06
@Ollyws @sobitneupane @eVoloshchak sent [hiring offers](https://www.upwork.com/ab/applicants/1579892682555052032/hired) to all three of you via Upwork.

**Comment by puneetlath** [comment] 2022-11-01 12:39
All paid. Thanks everyone!

**Closed by puneetlath** 2022-11-01 12:39 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
