### ISSUE TITLE
[HOLD for payment 2023-10-23][$500] Edit box and compose box slides over a bit when editing an existing comment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28663] opened 2023-10-02 22:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Click edit comment

## Expected Result:
Edit box should match the compose box as nearly as possible

## Actual Result:
The compose box against the static text - the text inside the compose box  is perfectly aligned between the two lines
The compose box against the edit text -- notice that the text of the edit box is a few pixels in. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.76-1 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Snip - (115) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/b29a36cd-7f97-47cf-b825-febc869ac8c1)
![image (2)](https://github.com/Expensify/App/assets/43996225/e984548c-1642-427b-a613-6dd34d46d5f5)
![image (1)](https://github.com/Expensify/App/assets/43996225/576f57c1-4d13-4992-912f-9fe623972187)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696218478121089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0130f9aae9385c3c6f</li>
        <li>Upwork Job ID: 1709203467909345280</li>
        <li>Last Price Increase: 2023-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 27062550</li>
</ul></li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2023-10-05 21:07
@ArekChr proposals for you here ^^

**Comment by ArekChr** [comment] 2023-10-06 09:05
[Proposed](https://github.com/Expensify/App/issues/28663#issuecomment-1743969726) solution from @neonbhai looks good to me

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by Pujan92** [comment] 2023-10-06 13:15
@ArekChr Could you plz consider my proposal for review?

**Comment by Pujan92** [comment] 2023-10-06 18:19
@luacmartins requesting you to check my proposal once as I have clarified some [doubts](https://expensify.slack.com/archives/C049HHMV9SM/p1696594375481669?thread_ts=1696218478.121089&cid=C049HHMV9SM)  regarding the requirements and made a proposal based on that which is quite different from the selected one.

**Comment by luacmartins** [comment] 2023-10-10 16:47
@NicMendonca fyi I think the urgency bonus should be applied here since the PR was ready to be merged yesterday but I was ooo and only merged it today.

**Comment by ArekChr** [comment] 2023-10-16 12:01
- [x] Link to the PR: No bug identified.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I don’t think we need to add a regression test here.

**Comment by luacmartins** [comment] 2023-10-20 17:45
Just missing BZ checklist and payment

**Comment by NicMendonca** [comment] 2023-10-20 20:26
@ArekChr bump on [BZ checklist](https://github.com/Expensify/App/issues/28663#issuecomment-1765319129) please!

**Comment by NicMendonca** [comment] 2023-10-24 15:34
@ArekChr thank you!

@neonbhai - you've been paid via Upwork 🎉

**Closed by NicMendonca** 2023-10-24 15:34 UTC
Labels: External, Daily, Awaiting Payment, Bug
