### ISSUE TITLE
[HOLD for payment 2023-10-28] [$500] Chat - Focus is lost after deleting a message from edit mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28420] opened 2023-09-28 22:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Desktop app or go to staging.new.expensify.com
2. Login with any account
3. Open any chat
4. Send message
5. Press UpArrow
6. Last message in the chat enters edit mode
7. Delete all the text while editing the comment and save
8. Confirm the message deletion

## Expected Result:
Message deleted, focus on composer

## Actual Result:
Message deleted, focus is lost

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/416d8733-ee08-4162-a2e3-1b2331235efd

https://github.com/Expensify/App/assets/78819774/ce412d0b-df58-43b3-9deb-0c491dba5883

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f46de8f434791af5</li>
        <li>Upwork Job ID: 1707684884701130752</li>
        <li>Last Price Increase: 2023-09-29</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Contributor | 26963532</li>
</ul></li>
    </ul>
</details>

**Comment by ospfranco** [comment] 2023-09-29 09:34
Seems this issue is caused by wrapping this function in a useCallback, since isFocused flag is not part of the dependencies it never gets updated.


![Oscar Franco Screen 000022](https://github.com/Expensify/App/assets/1634213/b6882df7-4623-4587-87b8-9811848a6e03)

Part of this PR https://github.com/Expensify/App/pull/27190.

**Comment by s-alves10** [comment] 2023-09-29 09:52
@ospfranco 

Please don't create a PR before approved

**Comment by mountiny** [comment] 2023-09-29 10:00
@s-alves10 Oscar is an expert agency engineer and I have asked them to investigate, going to assign him now https://expensify.slack.com/archives/C01GTK53T8Q/p1695940729318099

**Comment by s-alves10** [comment] 2023-09-29 10:06
This issue looks like a regression of [this PR](https://github.com/Expensify/App/pull/27221)

**Comment by kbecciv** [comment] 2023-09-29 18:05
Not reproduced on  build 1.3.73-3

https://github.com/Expensify/App/assets/93399543/4f34e22a-62ea-4c91-a024-b658d9956aa9

**Comment by mountiny** [comment] 2023-10-01 06:44
@aimane-chnaif should be paid for PR review. Given the original issue from which this regression came was $250, it makes sense to me to PR review payment here equal max to that original issue, otherwise we pay more fo the hotfix than for the feature itself. Does that work for you @aimane-chnaif ?

**Comment by mountiny** [comment] 2023-10-01 06:45
Taking this over as I have reviewed the PR too

**Comment by mountiny** [comment] 2023-10-28 13:23
@trjExpensify this should be ready for payment the automations seems to not have worked properly here

**Comment by trjExpensify** [comment] 2023-10-30 11:35
Sorry for the delay, I've been out. I see the payment due from [this comment](https://github.com/Expensify/App/issues/28420#issuecomment-1743514602) is $250, so I've settled up with you. Closing!

**Closed by trjExpensify** 2023-10-30 11:35 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
