### ISSUE TITLE
[$250] Tags - Tags no longer valid error doesn't appear unless user selects a category

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42145] opened 2024-05-14 10:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace and invite user B as a member
3. Enable tags and add some tags as an admin
4. As user B go to workspace chat and create an expense with a tag selected
5. As the admin delete the tag user B selected while creating the expense
6. As user B go to transaction detail page of the expense and open the tag RHP
7. Wait until the selected tag turns from bold to greyed as it has been deleted
8. Observe no inline error appears under the tag field
9. Click on the category field and select a category

## Expected Result:
Tags no longer valid error appears as soon as the tag becomes greyed out

## Actual Result:
Tags no longer valid error does not appear right away but appears when user selects a category

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/bcc120c0-f47e-4bcb-90f1-07c2a3cd76dd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01963726193b7ed49f</li>
        <li>Upwork Job ID: 1793040699834540032</li>
        <li>Last Price Increase: 2024-06-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @marcochavezf</details>

**Comment by izarutskaya** [comment] 2024-05-14 10:58
We think this issue might be related to the #collect project.

**Comment by kevinksullivan** [comment] 2024-05-21 22:06
Agree this is a collect issue. Not super critical, but definitely worth addressing as it's a weird hidden error message.

**Comment by situchan** [comment] 2024-05-22 20:06
@nexarvo thanks for the proposal. Can you please explain the root cause in more detail? And it's not ideal to call OpenReport in MoneyRequestView.

**Comment by situchan** [comment] 2024-05-23 04:21
Waiting for proposals

**Comment by situchan** [comment] 2024-05-27 15:37
Thanks. Reviewing

**Comment by situchan** [comment] 2024-05-27 19:46
Thanks. The root cause is correct but still I don't think it's good to call openReport only to get updated transactionViolations.

**Comment by situchan** [comment] 2024-05-28 19:29
Pulling up engineer since I think this requires backend collaboration.
🎀👀🎀

**Comment by marcochavezf** [comment] 2024-05-30 01:40
Just to confirm, we'd need to send the updated policyTagList from backend when the tag is removed, right?

**Comment by marcochavezf** [comment] 2024-05-31 16:47
No update

**Comment by situchan** [comment] 2024-06-03 08:28
checking

**Comment by marcochavezf** [comment] 2024-06-03 19:27
I will continue with it today

**Comment by marcochavezf** [comment] 2024-06-04 02:41
I noticed the policy tags are updated to the workspace members when they are deleted from the workspace. I will be evaluating if we need to re-compute the violation for all the expenses related to the workspace in this case

**Comment by marcochavezf** [comment] 2024-06-05 18:56
Re-evaluating the solution, [posting](https://expensify.slack.com/archives/C036QM0SLJK/p1717613737057669) possible solutions internally

**Comment by marcochavezf** [comment] 2024-06-06 19:17
Coming from the internal discussion, I'm leaning toward closing it out because it's an edge case. The behavior is similar to the "older than X days" violation, where we don't send the update in real-time for old expense reports, but you see the error when you open the report. Feel free to comment/re-open if you disagree

**Closed by marcochavezf** 2024-06-06 19:17 UTC
Labels: External, Daily, Help Wanted, Bug
