### ISSUE TITLE
[$500] Distance-In forced offline, selecting add stop, map box scrolls up

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30332] opened 2023-10-25 09:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile----Preferences
3. Toffle on forced offline
4. Navigate back to LHN
5. Tap fab
6. Tap request money----distance
7. Tap add stop and select a waypoint and note the map box

## Expected Result:
In forced offline, selecting add stop, map box must not scrolls up.

## Actual Result:
In forced offline, selecting add stop, map box scrolls up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/115492554/87acbbc6-908e-4e9e-b502-803392bb7632

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ea1a276eaddb7601</li>
        <li>Upwork Job ID: 1717116200862494720</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

**Comment by hungvu193** [comment] 2023-10-25 11:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
selecting add stop, map box scrolls up (both offline and online) for mWeb.
### What is the root cause of that problem?
Unlike other platforms, in mWeb, keyboard already take its spaces. In this issue while keyboard is dismissing and take a its space in our view, we also scroll to bottom because this useEffect will be triggered:
https://github.com/Expensify/App/blob/a8482e20e92916af993bf3198036dbd0f412f9dd/src/components/DistanceRequest/index.js#L120-L125

This is the RCA.
### What changes do you think we should make in order to solve the problem?
To avoid bad user experience in this case, we should add an early return for the useEffect above that will return when current platform is mobile web:
```javascript
     if (numberOfWaypoints <= numberOfPreviousWaypoints || Browser.isMobile()) { 
         return; 
     } 
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by s77rt** [comment] 2023-10-25 15:20
@hungvu193 Thanks for the proposal. Your RCA makes sense but I don't think disabling a feature to solve a bug is best here. As for the alternative solution, I'm not sure we can do that, on web there is no keyboard event listener.

**Comment by mpiniarski** [comment] 2023-10-25 19:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In request money----distance, when selecting add stop, map box jumps (scrolls up)
### What is the root cause of that problem?
In the add stop view, the native Keyboard is open, taking up space. Selecting an address redirects back to the distance view, where the following effect scrolls to the bottom:

https://github.com/Expensify/App/blob/a8482e20e92916af993bf3198036dbd0f412f9dd/src/components/DistanceRequest/index.js#L120-L125

The native Keyboard still takes up space for a moment so after redirection:
- scroll to the bottom happens
- keyboard gets hidden
- the view (and map) jumps 

### What changes do you think we should make in order to solve the problem?
As stated in the comments above, we cannot use a Keyboard event listener on the web.
My proposition is to, on mWeb, wait an arbitrary time before performing the scroll.

```js
    useEffect(() => {
        if (numberOfWaypoints <= numberOfPreviousWaypoints) {
            return;
        }
        
        if (Browser.isMobile()) {
            setTimeout(() => {
                scrollViewRef.current.scrollToEnd({animated: true});
             }, 1000);
        }
        else {
            scrollViewRef.current.scrollToEnd({animated: true});
        }
    }, [numberOfPreviousWaypoints, numberOfWaypoints]);

```

With such a small delay, the user will not experience the view jumping, because the Keyboard will already be hidden.
I would experiment with the value of the timeout.
Because scrolling already happens with animation, the user flow feels good.

**Comment by s77rt** [comment] 2023-10-25 19:15
@mpiniarski Thanks for the proposal. I'm afraid the solution may not be valid as the use of `setTimeout` is strictly discouraged and considered a workaround.

**Comment by mpiniarski** [comment] 2023-10-25 21:06
Thanks for the feedback @s77rt . I'll create another proposal.

**Comment by mpiniarski** [comment] 2023-10-25 21:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In request money----distance, when selecting add stop, map box jumps (scrolls up)
### What is the root cause of that problem?
**As in previous proposal:**
In the add stop view, the native Keyboard is open, taking up space. Selecting an address redirects back to the distance view, where the following effect scrolls to the bottom:

https://github.com/Expensify/App/blob/a8482e20e92916af993bf3198036dbd0f412f9dd/src/components/DistanceRequest/index.js#L120-L125

The native Keyboard still takes up space for a moment so after redirection following happens:
- scroll to the bottom in the smaller view (limited by keyboard)
<img width="278" alt="image" src="https://github.com/Expensify/App/assets/11861292/68d930c8-9742-4185-a248-4a0c08ff7733">

- keyboard gets hidden
- the view turns full-height again, the map jumps 

### What changes do you think we should make in order to solve the problem?
Without Keyboard event listener on the web and arbitrary `setTimeout` off the table, what we can do is:
- on the initial view load save the height an element (initial height, without Keyboard interfering). we can use `scrollViewRef` for that purpose,

```js
    const scrollViewHeight = useRef(null);
    useEffect(() => {
        scrollViewHeight.current = scrollViewRef.current.offsetHeight;
    }, []);

```

- in `useEffect` calling `scrollViewRef.current.scrollToEnd({animated: true});`, when on mWeb, we set up a `ResizeObserver` waiting for an element to come back to an initial height, only then start scrolling

```js
    useEffect(() => {
        if (numberOfWaypoints <= numberOfPreviousWaypoints) {
            return;
        }
        
        if (Browser.isMobile()) {
            const resizeObserver = new ResizeObserver(() => {
                if (scrollViewRef.current.offsetHeight === scrollViewHeight.current) {
                    scrollViewRef.current.scrollToEnd({animated: true});
                    resizeObserver.unobserve(scrollViewRef.current)
                }
            })
            resizeObserver.observe(scrollViewRef.current)
        }
        else {
            scrollViewRef.current.scrollToEnd({animated: true});
        }
    }, [numberOfPreviousWaypoints, numberOfWaypoints]);

```

Thanks to this approach, we avoid using `setTimeout` with a guessed timeout, we will perform the scroll on the exact moment the Keyboard gets hidden.

**Comment by s77rt** [comment] 2023-10-26 11:28
@mpiniarski Thanks for the update. I think the use of element height to determine keyboard visibility is a little workaround-ish. Because on height change we only **assume** that the change was due to keyboard open/close gesture but it may not. e.g. If we go offline the height would change which would break the logic (initial height will never be met again).


https://github.com/Expensify/App/assets/16493223/60b048f1-3b2c-4952-af87-6f49f28f3bff



For further proposals please just update the previous comment instead of writing a new one.

**Comment by mpiniarski** [comment] 2023-10-26 12:18
@s77rt Thanks for the comment. You're right, using such an arbitrary element as a reference is error prone as it's assuming too much. 
I would switch to use `document.documentElement` instead. It's height will not be affected by such event.

It can be affected by native events e.g. switching device orientation. If we want to ensure proper scrolling behaviour in such cases as well, we can observe document resizes as well to adjust the reference height.

I'll update the proposal with that option.

**Comment by s77rt** [comment] 2023-10-27 17:18
@mpiniarski I still think the solution is a workaround. We are still assuming the change in height is due to keyboard visibility change.

**Comment by s77rt** [comment] 2023-10-27 17:20
@mpiniarski Also please for tags you'd need to write a new comment otherwise I wouldn't get notified.

**Comment by mpiniarski** [comment] 2023-10-27 18:48
@s77rt Thanks for the feedback.

I agree this is a workaround, but the web standards do not give us tools to deal with this issue without a workaround. That's why [VirtualKeyboard API](https://www.w3.org/TR/virtual-keyboard/#introduction) draft was introduced. Unfortunatelly it's not well supported: \
<img width="347" alt="image" src="https://github.com/Expensify/App/assets/11861292/ce823c2d-d4c9-4a52-b9ea-629b868923e6">

Both [the draft](https://www.w3.org/TR/virtual-keyboard/#introduction) and [mdn docs](https://developer.mozilla.org/en-US/docs/Web/API/VirtualKeyboard_API#browser_compatibility) say that browsers deal with virtual keyboards on their own, by adjusting the viewport height.

That's why I think observing the viewport height changes together with `focus` and `blur` events of inputs is the best option be have for the issue.

That's true there are edge cases when a change in viewport height is not due to a keyboard visibility change, but some external events (not resulting from application state). Easiest way to handle them might be to force keyboard dismiss (input's unfocus) when viewport changes unexpeced (after `keyboardDidShow` and before `keyboardWillHide`).

Hope this convinces you.

**Comment by s77rt** [comment] 2023-10-28 10:09
Asked on Slack https://expensify.slack.com/archives/C01GTK53T8Q/p1698487723587479 to get some 👀 here

**Comment by s77rt** [comment] 2023-10-30 17:40
Not overdue. Gonna wait a little more for slack 👀

**Comment by NicMendonca** [comment] 2023-11-03 18:35
closing!

**Closed by NicMendonca** 2023-11-03 18:35 UTC
Labels: External, Daily, Help Wanted, Bug
