### ISSUE TITLE
Wallet - Loading spinner for Expensify wallet amount when changing default payment method

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31149] opened 2023-11-09 18:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: account has 2 or more payment method
1. Open the App
2. Login with any Expensifail account
3. Go to Settings -> Wallet -> Change default payment method

## Expected Result:
Expensify wallet amount not changes

## Actual Result:
Expensify wallet amount refreshing with loading spinner

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/786ca82d-5c59-4749-b481-9a9751cc7d7a

Production

https://github.com/Expensify/App/assets/78819774/8efc3230-e026-45dc-9c02-d95b49b3c0f3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment] 2023-11-09 18:06
Taking a look 👀

**Comment by neil-marcellini** [comment] 2023-11-09 18:14
The regression came from this PR [Fix: Wallet page does not update instantly when bank account is added or deleted](https://github.com/Expensify/App/pull/30700#top).

I agree that the wallet amount shouldn't refresh or have to load when you change the default payment method. However, I think this "bug" is arguable more minor than the one fixed by that PR, which is that the wallet page doesn't update when adding or removing a bank account. I think we should put up a quick fix, and if we start holding up the deploy we can remove the blocker label.

@Pujan92 do you want to put up a quick fix? I'll start investigating too.

**Comment by neil-marcellini** [comment] 2023-11-09 18:19
Ok so the `OpenPaymentsPage` API command returns bank accounts, funds, user wallet, paypal, and card list. The user wallet is where the balance comes from and that's why we show a loader when it's updating. That makes sense, but again, we shouldn't need to update the balance when adding or removing bank accounts.

So why did we decide to call this API command again when a bank account is added or deleted? The APIs which do that should return the updated list of bank accounts.

**Comment by situchan** [comment] 2023-11-09 18:21
The issue is that api doesn't return wallet info, either from pusher or from response

**Comment by neil-marcellini** [comment] 2023-11-09 18:42
Ok I took a second look at the issue that was supposed to be solved. It looks like when the user doesn't have a bank account we don't show the wallet, so when one is added we need to send an update for the wallet key, which we currently [don't do](https://github.com/Expensify/Web-Expensify/blob/e3019a9ca3573f402ac24f40e0d8a6e82dce7f3c/lib/BankAccountAPI.php#L879) for the API `AddPersonalBankAccount`.

Since we need backend changes, and the original issue isn't really that bad, I now think that we should revert the PR causing the regression. It's not the right approach anyways.

**Closed** 2023-11-09 19:23 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug

**Comment by neil-marcellini** [comment] 2023-11-09 19:28
CP requested [here](https://expensify.slack.com/archives/C07J32337/p1699558060641739)
