### ISSUE TITLE
[$1000] Contact method - Error message about existing account disappears after refreshing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22688] opened 2023-07-11 20:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Profile > Contact methods > New contact method
3. Add an existing account
4. Save it
5. Refresh the page

## Expected Result:
The error message that the existing account cannot be used will not disappear after refreshing the page

## Actual Result:
The error message that the existing account cannot be used disappears after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4672e7a1-7445-4dd7-b919-6a6ca9a32f75

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018dd619d053797a3c</li>
        <li>Upwork Job ID: 1679219149348700160</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-12 08:46
This should be fixed in the backend. `ReconnectApp` API returns loginList and it doesn't include failed contacts.

**Comment by joekaufmanexpensify** [comment] 2023-07-12 19:59
This feels like a bug to me. If you navigate away from the this error message, we continue to show it if you then go back to the page. It feels odd that we'd then remove the error entirely (without the user acknowledging it) if you refresh the page. The behavior should be consistent. 


https://github.com/Expensify/App/assets/54866469/682fe74e-e0e4-4260-99b0-49ff924aac80

**Comment by joekaufmanexpensify** [comment] 2023-07-12 20:00
@Santhosh-Sellavel I think this one might be fixed by https://github.com/Expensify/App/issues/17827 , curious if you agree?

**Comment by Santhosh-Sellavel** [comment] 2023-07-12 20:03
Yes seems like a duplicate

**Comment by joekaufmanexpensify** [comment] 2023-07-12 20:04
Cool, thanks! Going to close, as this is a dupe of the above issue.

**Closed by joekaufmanexpensify** 2023-07-12 20:04 UTC
Labels: External, Daily, Help Wanted, Bug
