### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Don't show "We might have a problem. Check out "

### ISSUE THREAD

**Issue by srikarparsi** [Expensify/App#43536] opened 2024-06-12 06:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:https://expensify.slack.com/archives/C05LX9D6E07/p1717834594513299

## Action Performed:

1. In Network devtools, verify that Ping command is called every 60 seconds (see Network Devtools)
2. Block https://dev.new.expensify.com:8082/api request to make backend unreachable (see Block network request)
3. Verify that after a while, 'You appear to be offline.' message appears.

## Expected Result:

We should only ever see the 'You appear to be offline.' message

## Actual Result:

Sometimes, we see the 'We might have a problem. Check out status.expensify.com.' message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img width="811" alt="image" src="https://github.com/Expensify/App/assets/48188732/2bfd93c7-ee42-466b-80ea-24462df08be9">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01557bbba5e2f56091</li>
        <li>Upwork Job ID: 1800772528715909319</li>
        <li>Last Price Increase: 2024-06-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by srikarparsi** [comment] 2024-06-12 06:11
Essentially, we need to revert this [PR](https://github.com/Expensify/App/pull/38377) without altering future changes made to networking like this [PR](https://github.com/Expensify/App/pull/43090). @tienifr @DylanDylann @cubuspl42 if you could take a look at this, that would be great since you worked on the original PR to add in this functionality.

**Comment by DylanDylann** [comment] 2024-06-12 08:31
@tienifr Please ping me when the PR is ready

**Comment by srikarparsi** [comment] 2024-06-12 16:49
Cool thanks, @mananjadhav reassigning to @DylanDylann since he reviewed the initial PR.

**Comment by srikarparsi** [comment] 2024-06-12 21:15
Not sure why the automation is failing. @tienifr do you think you can give an ETA for when the PR will be ready?

**Comment by srikarparsi** [comment] 2024-06-14 06:11
friendly bump @tienifr

**Comment by muttmuure** [comment] 2024-06-17 16:28
@tienifr did you open the PR on Friday? Could you link it here?

**Comment by srikarparsi** [comment] 2024-06-18 05:11
I believe @tienifr is [opening](https://expensify.slack.com/archives/C05R2V5GM1S/p1718678788145759?thread_ts=1718226581.480929&cid=C05R2V5GM1S) a PR today

**Comment by trjExpensify** [comment] 2024-06-28 19:17
👋 checklist time!

**Comment by trjExpensify** [comment] 2024-07-01 09:45
Bump on the checklist, @DylanDylann!

**Comment by DylanDylann** [comment] 2024-07-01 13:17
This is a reverted PR. We don't need the checklist.

**Comment by DylanDylann** [comment] 2024-07-03 03:11
This is a reverted PR. We don't need the checklist.

cc @srikarparsi

**Comment by trjExpensify** [comment] 2024-07-04 17:43
Oh cool, so no payment is due as it was a regression revert?

**Comment by DylanDylann** [comment] 2024-07-08 12:29
@trjExpensify The payment should be handled here because this is not a regression. we intended to implement this feature previously but it seems this is unnecessary so the internal team created this issue as a task to revert the previous PR

cc @srikarparsi

**Comment by DylanDylann** [comment] 2024-07-09 09:50
@trjExpensify I accepted the Upwork offer 🙏

**Comment by trjExpensify** [comment] 2024-07-09 15:47
Paid, @DylanDylann. Closing!

**Closed by trjExpensify** 2024-07-09 15:47 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-09 17:21
$250 approved for @tienifr
