### ISSUE TITLE
[$500] Unable to mute all sounds on App

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36455] opened 2024-02-14 02:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41.1
**Reproducible in staging?:** Y
**Reproducible in production?:** No (New feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open app on two devices
2. Go to Preferences > On "Mute all sounds from Expensify".
3. Send message from one device to another

## Expected Result:
There is no audio actually played.

## Actual Result:
Done sound. Unable to mute all sounds on App. "Mute all sounds from Expensify" button doesn't function.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e45836f1-a474-4a02-be08-28de8f2786c5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ce6ba6ef040e21d</li>
        <li>Upwork Job ID: 1757587986193575936</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2024-02-14 02:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unable to mute all sounds -> "Mute all sounds from Expensify" button doesn't seem to work as expected.

### What is the root cause of that problem?

Offending PR https://github.com/Expensify/App/pull/31055.

When a user on device A toggles on the "Mute all sounds from Expensify" this sets the isMutedAllSounds to true locally only via:

https://github.com/Expensify/App/blob/023d62cba900f4333f73c52eb735402a994cbc4b/src/libs/actions/User.ts#L715-L717

When the same user account on device B receives a message, the sounds are still enabled since different device means the local data from device A is not synced with that on device B in real-time -> therefore isMutedAllSounds is false on device B.

This is happening since we're not saving this data on BE in order to sync on all devices via pusher in real-time.

### What changes do you think we should make in order to solve the problem?

Implement saving of isMutedAllSounds on BE via endpoint and sync the data in real-time using pusher event.

**Comment by jeremy-croff** [comment] 2024-02-14 02:46
Similar to https://github.com/Expensify/App/issues/35422

**Comment by ikevin127** [comment] 2024-02-14 03:55
@jeremy-croff  Not that similar with the switch toggle based settings for which there's no overall solution because if we take a look at the current logic of other switch toggle based settings from Preferences they seem to have their own update endpoint.

Take for example the "Receive relevant feature updates and Expensify news" setting and it's toggle function:

https://github.com/Expensify/App/blob/023d62cba900f4333f73c52eb735402a994cbc4b/src/libs/actions/User.ts#L175

using its own unique `WRITE_COMMANDS.‎UPDATE_NEWSLETTER_SUBSCRIPTION` update endpoint:

https://github.com/Expensify/App/blob/023d62cba900f4333f73c52eb735402a994cbc4b/src/libs/actions/User.ts#L193-L196

**Comment by jeremy-croff** [comment] 2024-02-14 04:28
So there are 2 sounds.
1. native sounds like this bug is showing
2. app sounds, like we are playing through react-native-sounds library using playSound
They both fire off when a notification gets received.
When we mute all sounds, it just silences the app sounds 

The notification send to target devices still has a sound in the payload and it allows the device to honor it's own settings.
If the phone is on silence it won't play, otherwise it would.
The BE needs to stop sending a sound file in the notification for this to also stop making a sound there.

**Comment by Beamanator** [comment] 2024-02-14 13:47
I'm going to at least mark this as NAB for now, but we're discussing a bit in slack about how to fix / who should fix

**Comment by kirillzyusko** [comment] 2024-02-14 14:39
Basically @ikevin127 and @aimane-chnaif are right, now this feature is device-level only (so the preference for this setting will not be synchronized across devices).

Also want to point out this comment https://github.com/Expensify/App/pull/31055#issuecomment-1938590551 where we agreed that for now it should be device-level feature.

So @Beamanator please decide what should we do next 👀 Thank you!

**Comment by abekkala** [comment] 2024-02-15 18:07
I'll await confirmation from @m-natarajan irt TR. 

If there are no updates needed, I'll close out

**Comment by Beamanator** [comment] 2024-02-19 17:35
Hmm Maybe we should post in the #qa slack channel to get more 👀 on this @abekkala ? What you think? :D

**Comment by abekkala** [comment] 2024-02-19 19:07
@Beamanator yeah, good call. https://expensify.slack.com/archives/C9YU7BX5M/p1708369604811349

**Comment by Julesssss** [comment] 2024-02-20 10:57
Let's close this, and we'll add creating testrail cases to the [tracking issue](https://github.com/Expensify/App/issues/36846)

**Closed by Julesssss** 2024-02-20 10:57 UTC
Labels: Engineering, Daily
