### ISSUE TITLE
[$500] Workspace - #admin room with messages shows skeleton loading after workspace is deleted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38839] opened 2024-03-22 21:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Create a new workspace.
3. Go to #admin room.
4. Send a message.
5. Delete the workspace.
6. Go to #admin room.

## Expected Result:
#admin room will not show skeleton loading after the workspace is deleted.

## Actual Result:
#admin room shows skeleton loading after the workspace is deleted.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7435ef39-86ee-4cf3-9698-2f59dddf58d0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190baa2ce2890e3e7</li>
        <li>Upwork Job ID: 1772371688906227712</li>
        <li>Last Price Increase: 2024-03-25</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by kbecciv** [comment] 2024-03-22 21:04
We think that this bug might be related to #vip-vsb

**Comment by aldo-expensify** [comment] 2024-03-22 21:33
The `GetOlderActions` command is erroring out, sample logs: [86894ae17a5e2d72-YVR
](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2286894ae17a5e2d72-YVR%22)+AND+timestamp:[2024-03-22T20:32:07.340Z+TO+2024-03-22T22:32:07.340Z]&index=logs_expensify-027440)
![image](https://github.com/Expensify/App/assets/87341702/f6032a51-5aac-48a7-8502-8b99d8db69d8)

**Comment by aldo-expensify** [comment] 2024-03-22 21:48
Seems like the functions [loadOlderChats](https://github.com/Expensify/App/blob/81787f5ffe943ce46ef810e1892fe4bb2055f7ff/src/pages/home/report/ReportActionsView.tsx#L298) and [loadNewerChats](https://github.com/Expensify/App/blob/81787f5ffe943ce46ef810e1892fe4bb2055f7ff/src/pages/home/report/ReportActionsView.tsx#L312-L326) gets called in a infinite loop:

<img width="477" alt="image" src="https://github.com/Expensify/App/assets/87341702/6a8bf97b-f29c-46aa-8cbc-ec658207be24">

**Comment by aldo-expensify** [comment] 2024-03-25 21:15
Adding `external` and `bug` to see if we can get a contributor to help here

**Comment by mallenexpensify** [comment] 2024-03-25 21:22
@aldo-expensify , does this need to be a deploy blocker? I have a feeling it might be related to comment linking, multiple bugs have been reported, like here https://expensify.slack.com/archives/C049HHMV9SM/p1711147499521539

cc @roryabraham , you likely have a better idea if it's related.

**Comment by aldo-expensify** [comment] 2024-03-25 22:25
> @aldo-expensify , does this need to be a deploy blocker?

I think so, it is causing a regression that doesn't allow opening the admin room.

**Comment by abzokhattab** [comment] 2024-03-26 04:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app keeps calling the loading skeleton after a workspace is deleted
### What is the root cause of that problem?
 
the reportActions returned from the [getContinuousReportActionChain](https://github.com/Expensify/App/blob/51c38fd4709b641f8b5b859d09aff3328d18239d/src/libs/ReportActionsUtils.ts#L262) always have fewer actions after deleting the workspace 

this happens because the optimistic value of the [delete workspace action](https://github.com/Expensify/App/blob/964ef6ddd862c3c23779b11cae52d2e281e17c14/src/libs/ReportUtils.ts#L3956) doesn't have a `previousReportActionID` so the conditions [here](https://github.com/Expensify/App/blob/51c38fd4709b641f8b5b859d09aff3328d18239d/src/libs/ReportActionsUtils.ts#L284-L293) fails after one iteration 

<img width="1461" alt="image" src="https://github.com/Expensify/App/assets/59809993/6f7e0afd-da34-4d34-930c-a88e7c169bf9">

### What changes do you think we should make in order to solve the problem?


we can modify the [endIndex loop](https://github.com/Expensify/App/blob/51c38fd4709b641f8b5b859d09aff3328d18239d/src/libs/ReportActionsUtils.ts#L283-L290) so that it skips if the current action is `close`

```js
    while (
        (endIndex < sortedReportActions.length - 1 && sortedReportActions[endIndex].previousReportActionID === sortedReportActions[endIndex + 1].reportActionID) ||
        !!sortedReportActions[endIndex + 1]?.whisperedToAccountIDs?.length ||
        !!sortedReportActions[endIndex]?.whisperedToAccountIDs?.length ||
        sortedReportActions[endIndex]?.actionName === CONST.REPORT.ACTIONS.TYPE.ROOMCHANGELOG.INVITE_TO_ROOM ||
        sortedReportActions[endIndex]?.actionName === CONST.REPORT.ACTIONS.TYPE.CLOSED ||
        sortedReportActions[endIndex + 1]?.actionName === CONST.REPORT.ACTIONS.TYPE.CLOSED ||
        sortedReportActions[endIndex + 1]?.actionName === CONST.REPORT.ACTIONS.TYPE.CREATED
    ) {
```


#### POC:




https://github.com/Expensify/App/assets/59809993/bbbfc15f-9d78-4102-9190-49100ed15d86







### alternatively:

or we can pass a `previousReportActionID` to the [buildOptimisticClosedReportAction](https://github.com/Expensify/App/blob/51c38fd4709b641f8b5b859d09aff3328d18239d/src/libs/ReportActionsUtils.ts#L284-L293) and set it to the last action id so that the first condition passes for the optimistic action.

**Comment by sobitneupane** [comment] 2024-03-26 09:39
Thanks for the proposal @abzokhattab 

There are two Closed action which looks like the reason for the issue. Why do we have two Closed Actions in the first place? One of them don't have `previousReportActionID` which probably is the one optimistically added.
<img width="465" alt="Screenshot 2024-03-26 at 15 13 45" src="https://github.com/Expensify/App/assets/25876548/dd2d09b3-bc35-44b5-9bf4-eab891f1e78b">

[This PR ](https://github.com/Expensify/App/pull/36225/files) might have caused the regression.

**Comment by abzokhattab** [comment] 2024-03-26 11:23
> Does reverting the [PR](https://github.com/Expensify/App/pull/36225/files) and adding previousReportActionID optimistically solves both this issue and https://github.com/Expensify/App/issues/35174 issue?

I reverted the PR and yes indeed the current issue is not there anymore, however, the task and the admin room will not be set as archived in offline mode and I can still send new messages in the deleted rooms:

https://github.com/Expensify/App/assets/59809993/0fef1b1a-b888-4058-88a0-9a5b00d99874

Reverting the pr makes the reports list as empty `[]` thus it will not entered into this loop and the optimistic values will not be added:
https://github.com/Expensify/App/blob/d3ada5bfc09dde810411c46f71bf93caf4156fef/src/libs/actions/Policy.ts#L331-L368

 I think that we still need to optimistic action to prevent [this issue 
](https://github.com/Expensify/App/issues/35174)

**Comment by perunt** [comment] 2024-03-26 13:12
I guess it's also a backend issue. When we close the report, we do not reuse reportAction from optimistic data. Check it https://github.com/Expensify/App/issues/35952
Also https://github.com/Expensify/App/pull/30269/files#diff-cd0dfd9f8af5bc7cd33ff4f0337ef70574d42424ceecd7692b193348d3d8ecd4R869-R876

**Comment by aldo-expensify** [comment] 2024-03-26 17:51
> I guess it's also a backend issue. When we close the report, we do not reuse reportAction from optimistic data

That makes sense, the problem is gone if we log out and log back in.

**Comment by aldo-expensify** [comment] 2024-03-26 17:58
Looking at the `DeleteWorkspace` payload, we are not sending any client side reportActionID.

**Comment by aldo-expensify** [comment] 2024-03-26 18:01
hmm, but sending an optimistic reportActionID for the CLOSED action is not really possible I think because there could be thousands of reports getting closed because of the workspace deletion.

**Comment by aldo-expensify** [comment] 2024-03-26 18:05
Shouldn't we remove the optimistic CLOSED  reportAction using the success data? I see that in `DeleteWorkspace` response we have the real CLOSED reportActions coming.

**Comment by aldo-expensify** [comment] 2024-03-26 18:13
I created a PR here https://github.com/Expensify/App/pull/39008 that removes the optimistic CLOSED action on success and it seems to fix the problem:


https://github.com/Expensify/App/assets/87341702/8c95b790-64f1-4dc4-b9f1-e682371fdc1f

I'm not sure if it could cause another problem or if it is fine. I'm also not sure if we should do the same on failure too.

**Comment by aldo-expensify** [comment] 2024-03-26 19:22
@roryabraham @perunt when you have some time, can you check if [this solution](https://github.com/Expensify/App/issues/38839#issuecomment-2021159213) makes sense to you? 🙏

**Comment by roryabraham** [comment] 2024-03-27 00:10
PR is being CP'd presently

**Comment by mallenexpensify** [comment] 2024-03-28 23:21
This hit production two days ago 🎉 
Gonna close this, doesn't look like @sobitneupane reviewed the PR.  If I'm wrong, please comment, reopen.

**Comment by aldo-expensify** [comment] 2024-03-28 23:38
https://github.com/Expensify/Expensify/issues/383435

**Comment by aldo-expensify** [comment] 2024-03-28 23:39
@mallenexpensify : @ishpaul777 ended up reviewing

**Comment by aldo-expensify** [comment] 2024-03-28 23:43
ohh thanks for clearing that up!

**Closed by aldo-expensify** 2024-03-28 23:43 UTC
Labels: Engineering, Daily, Bug
