### ISSUE TITLE
[HOLD for Payment 2024-10-08][$250] [Search v2.2] - Report name is bold when report is unread or select, and unbold when not unselected

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49100] opened 2024-09-12 16:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search > Chats.
3. Click Filters.
4. Click In.
5. Select some reports.

## Expected Result:
There should be consistency whether the report name should be bold.

## Actual Result:
The report name is bold when the report is unread or selected, and unbold when not selected.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d3b29422-e05e-401c-9588-298f55ccc983

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834272973003292308</li>
        <li>Upwork Job ID: 1834272973003292308</li>
        <li>Last Price Increase: 2024-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 104115265</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by luacmartins** [comment] 2024-09-12 17:03
I can take this one since it's part of Search. cc @Kicu @289Adam289

**Comment by ikevin127** [comment] 2024-09-12 22:02
@luacmartins Are we accepting proposals for this one or will somebody from agencies work on it ?

**Comment by luacmartins** [comment] 2024-09-12 22:45
Sure, we can take contributors too

**Comment by bernhardoj** [comment] 2024-09-13 16:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The title bold is inconsistent in chat search filter In list.

### What is the root cause of that problem?
In `In` chat filters, we use getSearchOptions which has `shouldBoldTitleByDefault` as `false`.
https://github.com/Expensify/App/blob/16415328f9462eb4e9a8cd0099833d29948f1544/src/libs/OptionsListUtils.ts#L2067

So, the title will be bold based on the unread status.
https://github.com/Expensify/App/blob/16415328f9462eb4e9a8cd0099833d29948f1544/src/libs/OptionsListUtils.ts#L1973
https://github.com/Expensify/App/blob/16415328f9462eb4e9a8cd0099833d29948f1544/src/libs/OptionsListUtils.ts#L2502-L2504

Then, for the selected options, the item doesn't have `isBold` property,
https://github.com/Expensify/App/blob/0f2de40b73400455f4de33f1579783feae9e655d/src/components/Search/SearchFiltersChatsSelector.tsx#L85-L94

and it will be bold if `isBold` is not false.
https://github.com/Expensify/App/blob/49b00516a135ae9a4c96c885eef7f534b3a709cb/src/components/SelectionList/InviteMemberListItem.tsx#L101

### What changes do you think we should make in order to solve the problem?

The solution is to always bold the title. To do that, add a new param to `getSearchOptions` for `shouldBoldTitleByDefault` and use that instead of always setting it to false.
https://github.com/Expensify/App/blob/49b00516a135ae9a4c96c885eef7f534b3a709cb/src/libs/OptionsListUtils.ts#L2067

```
function getSearchOptions(options: OptionList, searchValue = '', betas: Beta[] = [], shouldBoldTitleByDefault = false): Options {
...
const optionList = getOptions(options, {
    ...
    shouldBoldTitleByDefault,
});
```

https://github.com/Expensify/App/blob/49b00516a135ae9a4c96c885eef7f534b3a709cb/src/components/Search/SearchFiltersChatsSelector.tsx#L68

```
return OptionsListUtils.getSearchOptions(options, undefined, undefined, true);
```

**Comment by ikevin127** [comment] 2024-09-14 02:47
> Sure, we can take contributors too

In this case, thanks everyone for the proposals!

##

I think @dominictb's [proposal](https://github.com/Expensify/App/issues/49100#issuecomment-2346875983) makes sense as the RCA is straight-forward and the main solution solves the issue as per the **Expected result**, without affecting other parts of the app other than the `SearchFiltersChatsSelector`, specifically the `In` filter.

- @luacmartins Before we actually attempt to address this issue, given my recent review of PR  [#49186](https://github.com/Expensify/App/pull/49186) from issue https://github.com/Expensify/App/issues/48823 - is this issue even worth being fixed given that the `In` and `Has` filters will be deprecated ?

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment] 2024-09-14 02:49
@bernhardoj Feel free to let us know if you think the selected proposal's main solution has some pitfalls which would create regressions whereas your solution won't - I'd be happy to re-assign!

**Comment by bernhardoj** [comment] 2024-09-14 06:04
@ikevin127 I don't think there will be a regression, but both solutions actually have different results. My solution will bold all the title instead of depends on the unread status.

**Comment by luacmartins** [comment] 2024-09-15 22:06
@Expensify/design what's the expected behavior for the `In` filter? Should report names be always bold, regular, or bold depending on unread status?

**Comment by dubielzyk-expensify** [comment] 2024-09-16 00:04
My assumption here is that they should _always_ be bold like we you submit a regular expense. Keen to hear what rest of @Expensify/design thinks though

**Comment by dubielzyk-expensify** [comment] 2024-09-16 00:47
Yeah, I see what you're saying, but I don't think this is an instance where we need to tell the user which are unread/read. I think of this more as a picker-style which we tend to keep all bold. Happy for @Expensify/design to tell me otherwise though 😄

**Comment by luacmartins** [comment] 2024-09-16 01:02
I agree! 👍 for going with all bold

**Comment by shawnborton** [comment] 2024-09-16 05:17
I think if we're displaying these rows the same way that we display the finder page, where we have the report title above and a preview of the latest message below, then it should follow the same behavior as the chat finder where unreads are bold and reads are not. 

If this follows the same behavior as the participant selector page, then they all should be bold.

**Comment by trjExpensify** [comment] 2024-09-16 09:23
>I think if we're displaying these rows the same way that we display the finder page, where we have the report title above and a preview of the latest message below

Interestingly on this, the defaultRooms (i.e #admins and announce) use the workspaceName as the second line in the chat switcher, whereas the user created rooms seem to use the lastMessage text. I know we did the former for ease of reference and discovery when looking for the room for a particular workspace. Was it intentional not to follow suit with the user created rooms in the chat switcher, or is that just an oversight?

**Comment by shawnborton** [comment] 2024-09-16 11:26
Hmm no idea, but I would think we should standardize on message preview in the chat finder, and then just use the Workspace label in the Submit flow/participant selector.

**Comment by ikevin127** [comment] 2024-09-16 19:18
Not overdue, still discussing about the right solution based on which we will assign one of the two existing proposals.

**Comment by trjExpensify** [comment] 2024-09-16 22:52
>but I would think we should standardize on message preview in the chat finder, and then just use the Workspace label in the Submit flow/participant selector.

Why not standardise on the workspaceName as the second line for all workspace rooms and chats in both the switcher and the participant selector? 

If you're trying to find say the #admins room and we don't include the workspace name it's going to be much harder to figure out which workspace its for. We can't rely on avatar being the sole distinction, really.

**Comment by shawnborton** [comment] 2024-09-17 05:28
That's fair, though there is a conversation happening about adding the workspace name right before the report name - so that would solve that issue and then make sure we have 100% consistency between LHN and Find. Thoughts on something like that?

**Comment by trjExpensify** [comment] 2024-09-17 15:07
Ah, that would solve it if it's searchable by workspace name still. Do we have an issue for it? I would think we need to do that first before changing the defaultRooms to drop the workspace name, because I think that would break the guides' ability to find the admins rooms of deals they're working with if we do it before.

**Comment by shawnborton** [comment] 2024-09-17 16:41
[Here's the thread](https://expensify.slack.com/archives/C07HPDRELLD/p1726090155295889) where it was being discussed. 

I am fine doing nothing for now with the preview line until something like the above is in place.

**Comment by trjExpensify** [comment] 2024-09-18 14:30
Yep, sounds good! 👍

**Comment by ikevin127** [comment] 2024-09-18 18:47
Can we have a **summary** of the discussions and an update on the expected result (if changed) ? We need to know whether or not we go with the assigned proposal 👍

**Comment by ikevin127** [comment] 2024-09-24 21:44
Given there was no response to my https://github.com/Expensify/App/issues/49100#issuecomment-2359178076 from above, I'm getting the sense that prople are leaning towards **all bold** instead of depending on read / unread status then my review from https://github.com/Expensify/App/issues/49100#issuecomment-2350799488 is not valid anymore and we should assign @bernhardoj based on their [proposal](https://github.com/Expensify/App/issues/49100#issuecomment-2349422915) and explanation from https://github.com/Expensify/App/issues/49100#issuecomment-2350863847.

cc @luacmartins

**Comment by luacmartins** [comment] 2024-09-24 23:30
>I'm getting the sense that prople are leaning towards all bold instead of depending on read / unread status

Yes, I think this is where we landed.

**Comment by trjExpensify** [comment] 2024-09-24 23:49
Hm, you sure? From Shawn: 

>I think if we're displaying these rows the same way that we display the finder page, where we have the report title above and a preview of the latest message below, then it should follow the same behavior as the chat finder where unreads are bold and reads are not.
>
>If this follows the same behavior as the participant selector page, then they all should be bold.

What's the "In" filter using? The chat-finder list or the participant selector list?

<img width="377" alt="image" src="https://github.com/user-attachments/assets/fe985ec0-52b1-4ae8-b31a-ca449bf1525c">

<img width="374" alt="image" src="https://github.com/user-attachments/assets/d5a0df3d-78b5-4200-aa93-ee0245f506dc">

Looks like the former to me, and thus would be bold/unbold if that's the case:

<img width="969" alt="image" src="https://github.com/user-attachments/assets/58d9333d-3e5e-43ce-869d-364dcde772c6">

**Comment by luacmartins** [comment] 2024-09-25 00:36
>What's the "In" filter using? The chat-finder list or the participant selector list?

It's closer to the chat finder, but not quite since the data rendered is still different. If that's the case, isn't the current behavior what we want then and we can close this issue, i.e. unread chats are bold and read chats are unbold?

<img width="1512" alt="Screenshot 2024-09-25 at 9 35 42 AM" src="https://github.com/user-attachments/assets/11caf0d7-996c-428e-91a6-f84c88b385a2">

**Comment by trjExpensify** [comment] 2024-09-25 00:57
>It's closer to the chat finder, but not quite since the data rendered is still different.

Different in what way? (Mainly for my understanding). 

>If that's the case, isn't the current behavior what we want then and we can close this issue, i.e. unread chats are bold and read chats are regular?

Yes, unless we think aligning with the participant selector is better for the `In` filter list? Personally, I think it is probably better for what you want to look up here. In which case, we should be rendering the `In` list more like we do the participant selector format which does not use the lastMessage previews or the bold/unbold unread indicator.

**Comment by luacmartins** [comment] 2024-09-25 01:55
>Different in what way? (Mainly for my understanding).

The main differences are that the `In` filter:
- Allows multi-select
- Renders `InviteMemberListItem` row component instead of `UserListItem` row, which allows the multi-select above. This component is used in other lists with multi-select e.g. Workspace member invite, Room invite page, New chat confirm page, etc
-  We only show reports vs reports + users (since you can create chats from the ChatFinder page)

**Comment by luacmartins** [comment] 2024-09-25 01:55
>Yes, unless we think aligning with the participant selector is better for the In filter list? Personally, I think it is probably better for what you want to look up here. In which case, we should be rendering the In list more like we do the participant selector format which does not use the lastMessage previews or the bold/unbold unread indicator.

Right, that's my preference too since I don't think we need to add the read/unread context to the user when selecting these.

**Comment by bernhardoj** [comment] 2024-09-25 06:59
> Right, that's my preference too since I don't think we need to add the read/unread context to the user when selecting these.

So, is the final decision is to bold all?

**Comment by trjExpensify** [comment] 2024-09-25 12:03
>Right, that's my preference too since I don't think we need to add the read/unread context to the user when selecting these.

Cool, so then we need to stop showing the lastMessage as the preview line and bold all to bring it in-line.

**Comment by dylanexpensify** [comment] 2024-09-26 12:54
> So, is the final decision is to bold all?

@bernhardoj correct!

**Comment by dannymcclain** [comment] 2024-09-26 13:14
Totally agree with where you all landed! **Bold 'em 🚀**

**Comment by bernhardoj** [comment] 2024-09-26 14:22
> so then we need to stop showing the lastMessage as the preview line

Hmm, what should we show then? On pages like money request participants, there is only DM and policy expense chat report, but in the "In" filter page, there are all kinds of reports, thread, money request/report, etc.

For a bit of context, we have this logic to decide what to show for each type of report. We can prevent showing the last message of the report by setting `showChatPreviewLine` as false.
https://github.com/Expensify/App/blob/da37289fe24c8d92cdf63da9de7320b7c3f08bca/src/libs/OptionsListUtils.ts#L536-L554

If we set `showChatPreviewLine` as false:

1. If it's a chat room or policy expense chat, it will show the report subtitle, which is the workspace name
2. If it's a task report, it will show "No activity yet" even if there is a message in the report
3. If it's a thread or IOU/expense report, it will still show the last message
4. Other types will show the first participants login

I believe 2 and 3 is not expected, in that case, what should we show?

**Comment by trjExpensify** [comment] 2024-09-26 23:33
Right, we need to consider an appropriate sub-line for each report type returned in the results of the `In: filter, but I think that's fine, and suggest something that communicates the data type a bit. So for the missing ones, that would be the below I think:

>taskName
>Task

>expense report/IOU report/transaction thread report name
>Expense

>threadName (for "normal" message threads)
>Thread

>groupName
>Group

CC: @JmillsExpensify

**Comment by bernhardoj** [comment] 2024-09-27 09:18
Thanks! PR is ready

cc: @ikevin127

**Comment by ikevin127** [comment] 2024-09-30 22:59
♻️ **Status update**: The PR was deployed to staging (https://github.com/Expensify/App/pull/49835#issuecomment-2384318473).

**Comment by ikevin127** [comment] 2024-10-02 21:49
⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-10-08]** according to yesterday’s production deploy from https://github.com/Expensify/App/pull/49835#issuecomment-2387307791.

cc @OfstadC

**Comment by OfstadC** [comment] 2024-10-08 14:07
## Payment Summary
- @ikevin127 paid $250 via Upwork
- @bernhardoj due $250 via manual New Expensify request

**Closed** 2024-10-08 14:07 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by bernhardoj** [comment] 2024-10-08 14:56
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-10-15 11:45
$250 approved for @bernhardoj
