### ISSUE TITLE
[HOLD for payment 2024-07-02] Expense - Same results appear twice when search email on submit expense modal

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44200] opened 2024-06-22 13:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #[40235](https://github.com/Expensify/App/pull/40235)
**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to FAB> Submit Expense
2. Enter amount> Next
3. Type email address that can be seen on the suggested list of emails
4. Check searched results
## Expected Result:
Only one mail address in list results should be present

## Actual Result:
Same results appear twice when search email on submit expense modal

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/726a69d2-c785-4ddc-92a7-7e682335c5b6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by m-natarajan** [comment] 2024-06-22 13:15
@srikarparsi FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

We think that this bug might be related to  #vip-vsb

**Comment by Pujan92** [comment] 2024-06-22 13:57
@TMisiukiewicz @rinej Regression from our [PR](https://github.com/Expensify/App/pull/40235). Could you plz check this

**Comment by srikarparsi** [comment] 2024-06-22 20:45
Thank you @Pujan92

**Comment by TMisiukiewicz** [comment] 2024-06-24 08:14
@Pujan92 @srikarparsi I'm gonna take a look on this today

**Comment by TMisiukiewicz** [comment] 2024-06-24 13:03
PR #44253 opened

**Comment by srikarparsi** [comment] 2024-06-24 15:26
Thanks @TMisiukiewicz, merged the PR, going to request a CP since it's a blocker

**Comment by roryabraham** [comment] 2024-06-24 21:20
[PR was CP'd](https://github.com/Expensify/App/pull/44253#issuecomment-2187032849). I see the blocker label was removed, but did we confirm this is fixed?

**Comment by srikarparsi** [comment] 2024-06-25 01:58
We did, answered [here](https://expensify.slack.com/archives/C9YU7BX5M/p1719266867620219?thread_ts=1719264053.246139&cid=C9YU7BX5M)

**Comment by srikarparsi** [comment] 2024-06-25 02:12
I think we just need to pay @Pujan92 here for reviewing the PR right?

**Comment by Pujan92** [comment] 2024-06-25 02:41
No payment for me @srikarparsi, it's regression from the PR I reviewed.

**Comment by kbecciv** [comment] 2024-06-25 11:40
Issue is fixed!

https://github.com/Expensify/App/assets/93399543/8a136dbf-d7d1-40d9-b73e-94344892ecb1

**Comment by MitchExpensify** [comment] 2024-06-26 23:33
No payment necessary

**Closed by MitchExpensify** 2024-06-26 23:33 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
