### ISSUE TITLE
[HOLD for payment 2024-03-14] [HOLD for payment #36814] [$500] [Collect approvers] `Pay` button appears for the approved report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34951] opened 2024-01-23 08:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705978407170839

## Action Performed:
1. submit a expense report to approver 
2. Approve the expense report

## Expected Result:
"pay" button should disappear
## Actual Result:
"pay" button still appears
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/Expensify/App/assets/43996225/af51f3f5-94b4-4b76-8e50-00b93f50f3e4" width="40%" height="40%">
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01649969eb5b52cb20</li>
        <li>Upwork Job ID: 1750230674366476288</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2024-01-25 03:02
Still seeing this daily

**Comment by bernhardoj** [comment] 2024-01-25 03:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pay option is still appears after approving the expense.

### What is the root cause of that problem?
It's simply because we don't hide the pay button when the expense is approved.
https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/components/MoneyReportHeader.tsx#L68-L71

### What changes do you think we should make in order to solve the problem?

Hide the button when the expense is approved by adding `!isApproved` condition to `shouldShowPayButton`.

(we need to do this in ReportPreview too)

_but how will the expense get paid if the pay button is hidden and it's not automatically reimbursed?_

**Comment by marcochavezf** [comment] 2024-01-25 16:45
Thanks for the proposal @bernhardoj, but this GH will be internal since it will require BE changes.

**Comment by marcochavezf** [comment] 2024-01-29 15:52
Working on it

**Comment by marcochavezf** [comment] 2024-01-30 02:17
PRs up 
- https://github.com/Expensify/Web-Expensify/pull/40709
- https://github.com/Expensify/App/pull/35347

**Comment by NicMendonca** [comment] 2024-01-31 19:37
Starting leave so re-assigning!

**Comment by marcochavezf** [comment] 2024-02-06 00:38
Updated the [App PR](https://github.com/Expensify/App/pull/35347) from latest main and mark it ready for review

**Comment by twisterdotcom** [comment] 2024-02-13 15:27
Is it? What do we need to do here?

**Comment by marcochavezf** [comment] 2024-02-13 17:46
Seems there's an edge case for `indirect reimbursement`, discussing [here](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1707846328342689?thread_ts=1707822000.587969&cid=C02NZ2HGJAZ)

**Comment by marcochavezf** [comment] 2024-02-13 22:40
Coming from this [convo](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1707858648454169?thread_ts=1707822000.587969&cid=C02NZ2HGJAZ), we'd need to update the `Pay` button logic based   on the reimbursement settings:

```
None - No pay button at all. The final report destination is either closed or approved based on “Submit & Close” or “Submit & Approve” mode.
Direct - Pay using Expensify shown to the admin that is configured for payment in the workspace (i.e the “assigned reimburser”)
Indirect - Pay elsewhere show to all admins
```

**Comment by twisterdotcom** [comment] 2024-02-14 11:48
@c3024 want to handle this as well please?

**Comment by c3024** [comment] 2024-02-14 12:19
Yes @twisterdotcom . Thanks

**Comment by marcochavezf** [comment] 2024-02-15 21:45
Also coming from the same convo, we want to simplify this [condition](https://github.com/Expensify/App/blob/b0043b5627d77c5076a34ef25ed83732606108ca/src/components/MoneyReportHeader.tsx#L60-L63) in favor of the group policies (we will remove the free plan soon) cc @c3024

**Comment by marcochavezf** [comment] 2024-02-15 21:46
Also we'd need to update this [condition](https://github.com/Expensify/App/blob/b0043b5627d77c5076a34ef25ed83732606108ca/src/components/ReportActionItem/ReportPreview.tsx#L213-L216) for the report preview.

**Comment by trjExpensify** [comment] 2024-02-19 10:35
@marcochavezf you're working on a PR for this, correct?

**Comment by marcochavezf** [comment] 2024-02-19 16:57
Hi @c3024, I was wondering if you've had a chance to work on this? If not, no worries at all, I'm more than happy to take care of the pending changes by creating a PR today.

**Comment by c3024** [comment] 2024-02-19 17:29
My bad, I misunderstood that I'd take this as C+. 😄  I will make the PR right away.

Could you confirm these?

```
REIMBURSEMENT_YES: 'reimburseYes', = Direct
            REIMBURSEMENT_NO: 'reimburseNo', = None
            REIMBURSEMENT_MANUAL: 'reimburseManual', = Indirect
```

>Also coming from the same convo, we want to simplify this [condition](https://github.com/Expensify/App/blob/b0043b5627d77c5076a34ef25ed83732606108ca/src/components/MoneyReportHeader.tsx#L60-L63) in favor of the group policies (we will remove the free plan soon).

This means `isPaidGroupPolicy` is always true henceforth, right?

@marcochavezf

**Comment by marcochavezf** [comment] 2024-02-19 17:33
Thanks @c3024, yeah the meaning of the reimbursement values is correct and also yes, the `isPaidGroupPolicy` will be always true

**Comment by twisterdotcom** [comment] 2024-02-20 21:38
I think we are going to wait for the follow up PR. @c3024 can you share your Upwork profile link for me?

**Comment by marcochavezf** [comment] 2024-02-21 01:59
Yup, it was an edge case that required more discussion and was reverted to unblock the deployment at that moment

**Comment by twisterdotcom** [comment] 2024-02-21 10:28
Hmm okay, so we'll just do one payment of $500, because this is a fix for something that required reverting. The original solution didn't consider the edge cases.

**Comment by marcochavezf** [comment] 2024-02-27 17:33
Waiting for this [PR](https://github.com/Expensify/App/pull/36814) to be merged.

**Closed** 2024-03-14 21:56 UTC
Labels: Weekly, Internal, Awaiting Payment, Bug
