### ISSUE TITLE
[HOLD for payment 2024-04-05] [$250] Chats - Expensify / Chats is not aligned on the same line

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38298] opened 2024-03-14 12:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/37421
## Action Performed:
1. Go to staging.new.expensify.com
2. Make sure the workspace filter is Expensify

## Expected Result:
Expensify / Chats is aligned on the same line

## Actual Result:
Expensify / Chats is not aligned on the same line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6413173_1710400313627!bandicam_2024-03-14_15-08-37-869](https://github.com/Expensify/App/assets/78819774/9d1c8206-9c81-484b-b2df-50c39b88fe4b)

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8acccc3eea77881</li>
        <li>Upwork Job ID: 1768272521223192576</li>
        <li>Last Price Increase: 2024-03-14</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-14 12:11
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by mountiny** [comment] 2024-03-14 12:44
I think this might have started after the update to breadcrumbs scaling https://github.com/Expensify/App/pull/36655 cc @dukenv0307 

@Expensify/design

**Comment by shawnborton** [comment] 2024-03-14 12:47
Hmm that is definitely possible, and if so, let's treat it like a regression and have @dukenv0307 follow up with a fix.

**Comment by mountiny** [comment] 2024-03-14 13:47
for whatever proposal @MahmudjonToraqulov Could you please identify what PR caused this regression, I agree this cannot be more than couple releases old

**Comment by MahmudjonToraqulov** [comment] 2024-03-14 14:11
[UPDATED](https://github.com/Expensify/App/issues/38298#issuecomment-1997373601) with offending PR

**Comment by shawnborton** [comment] 2024-03-14 14:11
That looks pretty good, just make sure it covers the case where the logo doesn't have the environment label as well.

**Comment by MahmudjonToraqulov** [comment] 2024-03-14 14:15
> managing assignees handle the proposal process

Ah sorry. I didn't check the assigners for the issue yet :).

**Comment by aneequeahmad** [comment] 2024-03-14 14:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expensify / Chats text is not aligned

### What is the root cause of that problem?
setting the height to `height: variables.lineHeightSizeh1` is causing the issue here
https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/styles/index.ts#L1539-L1542

### What changes do you think we should make in order to solve the problem?

`height: variables.lineHeightSizeh1` removed from `breadcrumbLogo` styles fixes the issue. 
Note: we cannot remove `top` since there is a comment which says top is added for pixel perfect alignment

### What alternative solutions did you explore? (Optional)

N/A

**Comment by godofoutcasts94** [comment] 2024-03-14 14:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chats - Expensify / Chats is not aligned on the same line
### What is the root cause of that problem?
This is happing also because of this line - 
https://github.com/Expensify/App/blob/0a512c9f3cf1b207668ab93f3d79866c80345f88/src/components/Breadcrumbs.tsx#L43
And also related to stylings here - 
https://github.com/Expensify/App/blob/0a512c9f3cf1b207668ab93f3d79866c80345f88/src/components/Breadcrumbs.tsx#L68
and here - 
https://github.com/Expensify/App/blob/0a512c9f3cf1b207668ab93f3d79866c80345f88/src/components/Breadcrumbs.tsx#L69-L74
as well.
### What changes do you think we should make in order to solve the problem?

We need to remove the `style={styles.breadcrumbLogo}` from here - 
https://github.com/Expensify/App/blob/0a512c9f3cf1b207668ab93f3d79866c80345f88/src/components/Breadcrumbs.tsx#L43
and also we need to add `mb1` here - 
https://github.com/Expensify/App/blob/0a512c9f3cf1b207668ab93f3d79866c80345f88/src/components/Breadcrumbs.tsx#L68
and here 
https://github.com/Expensify/App/blob/0a512c9f3cf1b207668ab93f3d79866c80345f88/src/components/Breadcrumbs.tsx#L71
as well 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment] 2024-03-14 16:56
Updated [Proposal](https://github.com/Expensify/App/issues/38298#issuecomment-1997584459)

**Comment by cubuspl42** [comment] 2024-03-15 11:37
@MahmudjonToraqulov 

>  And it works well even without environment label as well.

Would you include the relevant screenshots in the proposal, in such a case?

**Comment by cubuspl42** [comment] 2024-03-15 11:38
@aneequeahmad @godofoutcasts94 

Thanks for your proposals. Unless they cover any case @MahmudjonToraqulov missed, I don't think that they are superior in any way, so I would go with the first on posted in this case.

**Comment by MahmudjonToraqulov** [comment] 2024-03-15 12:34
> @aneequeahmad @godofoutcasts94
> 
> Thanks for your proposals. Unless they cover any case @MahmudjonToraqulov missed, I don't think that they are superior in any way, so I would go with the first on posted in this case.

Of course @cubuspl42. Updated my [PROPOSAL](https://github.com/Expensify/App/issues/38298#issuecomment-1997373601) with new screenshot img.

**Comment by aneequeahmad** [comment] 2024-03-15 13:00
@cubuspl42 If we `Remove style={styles.breadcrumbLogo} here` as said [here](https://github.com/Expensify/App/issues/38298#:~:text=Remove%20style%3D%7Bstyles.breadcrumbLogo%7D%20here%3A) it isn't aligned on the same line. if you look closely you can se 1-2 pixel difference in alignment(1.66px to be exact). There is also a comment for this style https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/styles/index.ts#L1539-L1540

Screenshot of the case when whole style is removed is here(not aligned perfectly).
<img width="690" alt="Screenshot 2024-03-15 at 5 44 09 PM" src="https://github.com/Expensify/App/assets/36359331/4833a815-8a06-46ed-a64b-0e8c35f39e4e">

That why i said we need to only have  style `top: 1.66` and no need to have fixed height `height: variables.lineHeightSizeh1,` and its generally not a good practice to give height to the boxes containing elements(margin and padding attributes given right values should set the perfect height). 

Screenshot of my proposal is here 
<img width="676" alt="Screenshot 2024-03-15 at 5 47 26 PM" src="https://github.com/Expensify/App/assets/36359331/17fc0eca-6798-44d2-921b-fe7f9ef27bc8">

**Comment by MahmudjonToraqulov** [comment] 2024-03-15 13:15
Hey @aneequeahmad. As the main solution to the issue was removing `style={styles.breadcrumbLogo}` in my first solution  I haven't added positioning yet.

Let me ask friendly have u checked my second solution? 
When it comes to screenshots, have you checked my screenshots?  
Thanks.

**Comment by godofoutcasts94** [comment] 2024-03-15 14:41
Updated [Proposal](https://github.com/Expensify/App/issues/38298#issuecomment-1997584459) @cubuspl42

**Comment by aneequeahmad** [comment] 2024-03-15 22:30
@MahmudjonToraqulov if you haven't added the positioning yet then how can alignment issue be fixed by your solution ? 
Also i have checked your second solution it doesn't fix the alignment as well please look at the screenshot below closely from your 2nd solution `Expensify / Chats` is not aligned(not pixel perfect).
<img width="1249" alt="Screenshot 2024-03-16 at 3 20 41 AM" src="https://github.com/Expensify/App/assets/36359331/9e073d81-97f5-4975-8365-ee36627964bd">

@suneox Your video shows the alignment isn't correct. Please see the screenshot below

<img width="679" alt="Screenshot 2024-03-16 at 3 15 21 AM" src="https://github.com/Expensify/App/assets/36359331/9b7bda50-c933-4909-8692-0da4fe2c376c">

**Comment by aneequeahmad** [comment] 2024-03-16 12:18
> @aneequeahmad your screenshot also have a little space bellow text

@suneox The screenshot you are referring to is the screenshot from your video please look closely.

The screenshot from my proposal is [here](https://github.com/Expensify/App/issues/38298#:~:text=Screenshot%20of%20my%20proposal%20is%20here)

**Comment by cubuspl42** [comment] 2024-03-18 12:22
@suneox 

> we need to check the condition Browser.isMobile() before applying the style change from PR

I checked the diff from #36655 and I can't see any mobile-dependent code. You'd need to elaborate why your solution **is** mobile/desktop Web specific.

Also, this issue is said to be occurring [on all platforms](https://github.com/Expensify/App/issues/38298#issue-2186188067).

> Which of our officially supported platforms is this issue occurring on?
> (all)

...and you mention mentions Web-specific mobile check. This is all unclear.

**Comment by MahmudjonToraqulov** [comment] 2024-03-18 15:59
> Please update the proposal to describe your actual proposed solution.

Hey @cubuspl42. You were gonna go with my solution if I'm not mistaken. LMK Have u changed your decision?

**Comment by cubuspl42** [comment] 2024-03-19 10:58
@MahmudjonToraqulov

I said,"Unless they cover any case you missed".

So far, we have three proposals:

- @MahmudjonToraqulov suggests to just drop the `style={styles.breadcrumbLogo}`
  - It's simple but removes the "pixel-perfect alignment"
- @aneequeahmad suggests to remove `height: variables.lineHeightSizeh1` from 
  - Also simple, keeps the "pixel-perfect alignment"
- @suneox suggests that we should go platform-specific. It makes me wonder if the other proposals weren't tested only on the desktop Web.

If the simpler approach works on all platforms, I'd prefer it. If not, other proposals might be just invalid and then we'll re-evaluate.

Ping @aneequeahmad about testing on all platforms.

**Comment by godofoutcasts94** [comment] 2024-03-19 11:13
Hey @cubuspl42 why is my proposal not even considered ??

**Comment by MahmudjonToraqulov** [comment] 2024-03-19 11:17
> @MahmudjonToraqulov
> 
> I said "Unless they cover any case you missed".
> 
> So far, we have three proposals:
> 
> * @MahmudjonToraqulov suggests to just drop the `style={styles.breadcrumbLogo}`
>   
>   * It's simple but removes the "pixel-perfect alignment"
> * @aneequeahmad suggests to remove `height: variables.lineHeightSizeh1` from
>   
>   * Also simple, keeps the "pixel-perfect alignment"
> * @suneox suggests that we should go platform-specific. It makes me wonder if the other proposals weren't tested only on the desktop Web.
> 
> If the simpler approach works on all platforms, I'd prefer it. If not, other proposals might be just invalid and then we'll re-evaluate.
> 
> Ping @aneequeahmad about testing on all platforms.

What about my alternative solution?

**Comment by cubuspl42** [comment] 2024-03-19 11:20
@godofoutcasts94 

I keep forgetting about it. Sorry.

> style={styles.breadcrumbLogo}

From my perspective, it has the same qualities as the first proposal, i.e. it looses the "pixel-perfect alignment". Also, it's last in the submitting order, so it would have to be measurably better than the one by @aneequeahmad to be selected.

But you're right that it should be included in the commentary.

**Comment by cubuspl42** [comment] 2024-03-19 11:28
@MahmudjonToraqulov 

> What about my alternative solution?

I don't interpret the "What alternative solutions did you explore?" section like some other people do. For me, it's an _optional_ section that's best suited for describing rejected solutions.

If you actually want to suggest two different solutions, which you both fully tested and are ready to sign under both, I think you should describe them as "Option A" / "Option B" in the "What changes do you think we should make in order to solve the problem?" section.

In the case of a visual issue like this one, you should provide screenshots for both "Option A" and "Option B".

Since this issue is "suspected" to be platform-specific, I think that screenshots for all platforms should be provided. You can use  the`<details>` tag like in the [template](https://github.com/Expensify/App/blob/main/.github/PULL_REQUEST_TEMPLATE.md?plain=1).

**Comment by aneequeahmad** [comment] 2024-03-19 11:53
@cubuspl42 here are screenshot of my proposal on different platforms.

**iOS Native:**

![IOS_native](https://github.com/Expensify/App/assets/36359331/d53c6948-b683-41ba-bc4f-75903683ab07)

**Android native:**

![Screenshot_20240319-032421](https://github.com/Expensify/App/assets/36359331/4f18dbf5-aff9-4446-bfed-09c2d7b2af24)

**mobile Web (Safari):**

![mWeb](https://github.com/Expensify/App/assets/36359331/d43ddde8-4370-4ecf-986a-1dd8de6e0a7e)

**desktop Web(Mac Os/Chrome):**

![Screenshot_20240319-165139](https://github.com/Expensify/App/assets/36359331/3a9a0260-2189-46c5-9774-b8272afacca6)

**Comment by cubuspl42** [comment] 2024-03-19 17:16
It looks good, as far as I can tell!

I approve the proposal by @aneequeahmad 

I base my decision on a mix of simplicity, effectiveness, and the order of submission.

Thanks, everyone!

C+ reviewed 🎀 👀 🎀

**Comment by aneequeahmad** [comment] 2024-03-24 00:18
@cubuspl42 PR is ready for review

**Comment by puneetlath** [comment] 2024-04-04 18:08
@cubuspl42 friendly reminder on the checklist so that we can pay tomorrow.

**Comment by cubuspl42** [comment] 2024-04-05 09:21
- The PR that introduced the bug has been identified. Link to the PR:
    -  https://github.com/Expensify/App/pull/32221
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - https://github.com/Expensify/App/pull/32221#issuecomment-2039306743
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
  - N/A

**Comment by puneetlath** [comment] 2024-04-05 16:07
@cubuspl42 has been paid. 

@aneequeahmad I sent you an offer [here](https://www.upwork.com/nx/wm/offer/101749286). Ping me on this issue when you've accepted.

**Comment by aneequeahmad** [comment] 2024-04-05 20:39
@puneetlath Friendly reminder

**Comment by puneetlath** [comment] 2024-04-05 20:40
Everyone has been paid. Thanks y'all!

**Closed by puneetlath** 2024-04-05 20:40 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
