### ISSUE TITLE
Web - incorrect label for contact methods option in profile

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21710] opened 2023-06-27 17:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Open profile
3. See the label for contact methods
4. Click that and now see the header

## Expected Result:
Label should be "Contact methods"

## Actual Result:
Label is "Contact method"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/48997371-2b34-4fa7-9345-3ddafbe5c4af

https://github.com/Expensify/App/assets/93399543/4f4b456e-8e5e-4dce-87a5-8363aaf1bd0b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687542345661389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-06-27 17:29
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
incorrect label for contact methods option in profile
### What is the root cause of that problem?
Root cause is the wrong language key passed in description field of contact option in `ProfilePage`
https://github.com/Expensify/App/blob/5200aafaf16c7e9ad896096de0bfcd467555ee63/src/pages/settings/Profile/ProfilePage.js#L69-L74
### What changes do you think we should make in order to solve the problem?
We need to pass `contactMethods` key in the description which is also defined in the language file like shown below
```js
{
    description: props.translate('contacts.contactMethods'),
    title: props.formatPhoneNumber(lodashGet(currentUserDetails, 'login', '')),
    pageRoute: ROUTES.SETTINGS_CONTACT_METHODS,
    brickRoadIndicator: contactMethodBrickRoadIndicator,
 },
```
https://github.com/Expensify/App/blob/5200aafaf16c7e9ad896096de0bfcd467555ee63/src/languages/en.js#L425-L427
<details>
  <summary>Results</summary>
</details>
### What alternative solutions did you explore? (Optional)
None

**Comment by JmillsExpensify** [comment] 2023-07-05 12:44
Slammed with bug reports. I'll close the loop on these today.

**Comment by Nikhil-Vats** [comment] 2023-07-11 20:58
This is intentional since we only see 1 contact method in profile page so the label is singular. It can be closed.

**Comment by JmillsExpensify** [comment] 2023-07-12 13:02
Agreed. This is by design. Closing.

**Closed by JmillsExpensify** 2023-07-12 13:02 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
