### ISSUE TITLE
[$2000] Test Issue - Testing automation

### ISSUE THREAD

**Issue by MonilBhavsar** [Expensify/App#13812] opened 2022-12-23 05:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012bdd36bd0e9cc3b9</li>
        <li>Upwork Job ID: 1606159894333325312</li>
        <li>Last Price Increase: 2022-12-30</li>
    </ul>
</details>

**Comment by MonilBhavsar** [comment] 2022-12-23 05:30
This is test issue for testing automation.
No action is required here @aimane-chnaif 
@mallenexpensify could you please confirm that after 7 days, no slack DM is received to double the price of the issue manually.

**Comment by mallenexpensify** [comment] 2022-12-23 18:10
Yup, @MonilBhavsar , will do.  I bumped it to weekly to get the reminder

**Comment by sandipanghos** [comment] 2022-12-24 18:48
@MonilBhavsar Can you provide screenshot? 
I will try to check the testing script in repo and understand the issue.
Please confirm is it 

```test("Describe what actually happened", () => {

    expect(g...).toBe("result");

});
it needs to be 

test("Describe what should be  happened", () => {

    expect(g...).toBe("result");

});
```
The requirement will be clear after checking the code. I am new to this Expensify

**Comment by abdulrahuman5196** [comment] 2022-12-31 17:44
**Proposal**

I have already add the Root cause and solution as part of the original bug statement in slack here - https://expensify.slack.com/archives/C049HHMV9SM/p1672258474181849

**Comment by mallenexpensify** [comment] 2023-01-02 16:47
Can confirm I have **not** received a botify message in Slackbot channel to double message.  Closing.  Thanks @MonilBhavsar . 

@sandipanghos sorry about the confusion, most issues labeled `Help Wanted` are jobs that are open to proposals, unfortunately this test issue is not.  You can check the rest at https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22

**Closed by mallenexpensify** 2023-01-02 16:47 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by MonilBhavsar** [comment] 2023-01-03 05:51
Thanks!
