### ISSUE TITLE
[HOLD for payment 2023-08-24] [CHECKLIST TO BE COMPLETED] [$1000] Workspace +N overlay has a smaller border radius than the workspace icon

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23426] opened 2023-07-23 17:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Requirement: has >= 5 workspaces
1. Open Settings
2. Hover or long-press the Workspaces menu
3. Notice carefully the +N overlay border radius
To spot it easier, please zoom it
## Expected Result: 
The overlay border radius is the same as the workspace icon border radius
## Actual Result: 
The overlay border radius is smaller than the workspace icon border radius
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-22 at 21 10 34](https://github.com/Expensify/App/assets/43996225/a086fa92-38b9-407a-b304-b6659befa517)

![Snip - New Expensify - Google Chrome (4)](https://github.com/Expensify/App/assets/43996225/b7b1939a-5e30-49ea-a90d-79a55146f7b0)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690036975314749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb51d18c394675da</li>
        <li>Upwork Job ID: 1683274383107907584</li>
        2023-07-24<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 25777355</li>
<li>bernhardoj | Reporter | 25777356</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-23 17:49
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The workspace +N overlay has a smaller border-radius than the workspace icon.
### What is the root cause of that problem?
In the code, the workspace icon and the +N overlay have the same border radius, which is 6. They also have the same size, which is 24, but somehow the overlay border radius appears smaller. Here is why:
The workspace icon is a nested view that has 2 border-radius styles with the same value (6). The first border-radius is in MultipleAvatars. This View has a border width of 2.
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/components/MultipleAvatars.js#L170-L183
The second border radius is in Avatar.
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/components/Avatar.js#L93-L104
On the other hand, the overlay only has 1 border radius style. This View also has a border width of 2.
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/components/MultipleAvatars.js#L199-L215
The bigger the value, the bigger the radius. But as we also know, border radius is also affected by the element size. For the workspace icon, the first View has a border width of 2, which means the total width of the element is
24 + 2 (border left) + 2 (border right) = 28.
while the second View width is still 24. This makes the first View radius smaller than the 2nd View.
<img width="431" alt="Screenshot 2023-07-22 at 23 02 42" src="https://github.com/Expensify/App/assets/50919443/ab357819-62c5-443c-86f4-623bf60116c0">
The image above shows the radius difference between the parent View and the child View.
In the case of the overlay, the width is also 28 (24 + 2 + 2).
<img width="728" alt="Screenshot 2023-07-22 at 21 10 34" src="https://github.com/Expensify/App/assets/50919443/c4cac96b-5db1-4950-bd95-c532c963d31a">
The image above also shows the radius difference between the overlay and the workspace icon. Because the radius is different, we can notice the overlay background color.
### What changes do you think we should make in order to solve the problem?

_Avatar code has a lot of responsibilities and I think the most ideal solution is to refactor the Avatar and MultipleAvatar code so we don't have the nested View with multiple border radius, but I also think that requires a lot of effort._
So, I would like to propose this simple idea (the idea is to mimic the structure of the workspace icon):
1. Add the border radius style to the overlay child View.
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/components/MultipleAvatars.js#L216-L223
2. Move the overlay background color to the overlay child View
<details>
<summary>View diff</summary>
```diff
diff --git a/src/components/MultipleAvatars.js b/src/components/MultipleAvatars.js
index 3b20d99fa2..6e4ce933ca 100644
--- a/src/components/MultipleAvatars.js
+++ b/src/components/MultipleAvatars.js
@@ -206,9 +206,7 @@ function MultipleAvatars(props) {
                                             isInReportAction: props.isInReportAction,
                                             shouldUseCardBackground: props.shouldUseCardBackground,
                                         }),
-
-                                        // Set overlay background color with RGBA value so that the text will not inherit opacity
-                                        StyleUtils.getBackgroundColorWithOpacityStyle(themeColors.overlay, variables.overlayOpacity),
+                                        styles.bgTransparent, <- we need to set it to transparent to override the bg from getHorizontalStackedAvatarBorderStyle
                                         StyleUtils.getHorizontalStackedOverlayAvatarStyle(oneAvatarSize, oneAvatarBorderWidth),
                                         props.icons[3].type === CONST.ICON_TYPE_WORKSPACE ? StyleUtils.getAvatarBorderRadius(props.size, props.icons[3].type) : {},
                                     ]}
@@ -219,6 +217,9 @@ function MultipleAvatars(props) {
                                             styles.alignItemsCenter,
                                             StyleUtils.getHeight(oneAvatarSize.height),
                                             StyleUtils.getWidthStyle(oneAvatarSize.width),
+                                            // Set overlay background color with RGBA value so that the text will not inherit opacity
+                                            StyleUtils.getBackgroundColorWithOpacityStyle(themeColors.overlay, variables.overlayOpacity),
+                                            StyleUtils.getAvatarBorderStyle(props.size, props.icons[3].type),
                                         ]}
                                     >
                                         <Text
```
</details>
### What alternative solutions did you explore? (Optional)
**Alternative 1**
To have the same radius between the icon parent and the icon itself, we should adjust the parent border radius by taking into account the border width. For example, the workspace icon border width is 2, so we add the current border radius, which is 6, with the border width (6 + 2 = 8). The parent (container) border radius will be 8.
1. Create a new StyleUtils called `getAvatarContainerBorderRadius(size, type, borderWidth)`. It will simply call `getAvatarBorderRadius` and add `borderWidth` to the result.
2. Replace the usage of `getAvatarBorderRadius` (on the icon and overlay) with `getAvatarContainerBorderRadius`
<img width="463" alt="image" src="https://github.com/Expensify/App/assets/50919443/e54e53df-9766-44f6-8676-9836dbbd64b3">
**Alternative 2**
I think this alternative solution is cleaner but requires more changes, but there is a catch.
The idea is to completely remove the border from the overlay. We want just a simple View that sits on top of the workspace icon with the same size and border radius.
1. Remove the overlay child View and move the height and width style to the parent.
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/components/MultipleAvatars.js#L216-L223
2. Remove the border style of the overlay parent View. This will remove the border color and "unused" bg color.
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/components/MultipleAvatars.js#L203-L208
3. Remove the second border style of the overlay parent View. (remove the borderWidth and borderStyle)
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/styles/StyleUtils.js#L920-L928
4. Because we are removing the border from the overlay, we need to adjust the `left` positioning.
Before: `left: -(oneAvatarSize.width * 2 + oneAvatarBorderWidth * 2)`
After: `left: -(oneAvatarSize.width * 2 + oneAvatarBorderWidth)`
`oneAvatarBorderWidth` is the 4th workspace icon's right border width.
5. We need to somehow disable the tooltip of the icon behind the overlay because now the user can hover over the icon border.
<img width="379" alt="Screenshot 2023-07-23 at 00 13 57" src="https://github.com/Expensify/App/assets/50919443/0f309008-9b85-4de2-9bd5-ec903ea5091c">, OR if we want, we can also do a change so that user can't hover over the icon border, which I prefer.

**Comment by jliexpensify** [comment] 2023-07-24 00:31
Yep, I can repro:

![image](https://github.com/Expensify/App/assets/30815269/20c129c1-d9ec-46aa-b90a-24b2b290b1ca)

**Comment by bondydaa** [comment] 2023-08-02 21:20
looks like the PR caused this regression https://github.com/Expensify/App/issues/24069, i goofed initially on the labels but should be ready for @bernhardoj to take over when you're online.

**Comment by jliexpensify** [comment] 2023-08-02 22:52
Ok, since this caused a regression - here's a Payments summary:

- Bug Reporter: @bernhardoj $250
- Contributor: @bernhardoj $500 (penalty due to regression)
- C+: @thesahindia $500  (penalty due to regression) - request via New.Dot

[Upwork job](https://www.upwork.com/jobs/~01fb51d18c394675da)

Let me know if this isn't correct!

**Comment by danieldoglas** [comment] 2023-08-11 01:13
@jliexpensify , as @bernhardoj explained [here](https://github.com/Expensify/App/pull/24088#issuecomment-1664962948) this bug was not generated by the code changes he did. The problem is that the fix for this issue was supposed to be a 2 part fix, and we fixed just one. So I think we should **not** apply the regression penalty in this situation.

**Comment by jliexpensify** [comment] 2023-08-11 01:26
@danieldoglas no worries, I can adjust the Payment for @bernhardoj . What about for @thesahindia ?

**Comment by jliexpensify** [comment] 2023-08-11 04:20
Paid in Upworks, job removed. @thesahindia - is a checklist needed? Also, please request $1000 in New.Dot.

**Comment by jliexpensify** [comment] 2023-08-14 01:32
@thesahindia bump on checklist  + ND payment request

**Comment by jliexpensify** [comment] 2023-08-16 01:32
Bump @thesahindia - do we need a checklist?

**Comment by JmillsExpensify** [comment] 2023-08-24 05:30
Reviewed the details for @thesahindia. $1,000 approved for payment based on the [BZ summary](https://github.com/Expensify/App/issues/23426#issuecomment-1674194459) above.

**Comment by jliexpensify** [comment] 2023-08-27 00:14
Closing this, I think everytihng is sorted!

**Closed by jliexpensify** 2023-08-27 00:14 UTC
Labels: External, Weekly, Awaiting Payment, Bug
