### ISSUE TITLE
[HOLD for payment 2024-01-26] [$600] CRITICAL: Updates to Comment Action menu

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#33573] opened 2023-12-25 23:15 UTC
## Problem
As we increasingly build out our chat-focused features, the amount of available comment actions has increased pretty dramatically from a couple to ten and counting. It's pretty daunting to say the least. The comment action menu has become bloated and inconsistent over time. 

## Solution
- [ ] Rename `Subscribe to thread` to `Join thread`
- [ ] Rename `Unsubscribe to thread` to `Leave thread`
- [ ] Rework the actions to only show 3 emojis, emoji reaction button, two actions, then overflow icon:
![image](https://github.com/Expensify/App/assets/145416827/66f8ae0b-926b-4bdb-8121-dffb16379020)

- [ ] Change `Reply in thread` icon to new `comment_bubble_add` icon
- [ ] Change `Mark as unread` icon to new `comment_bubble_unread` icon
- [ ] Adjust to new sizing removing the spacing between icons and sizing of them (see details below):
![image](https://github.com/Expensify/App/assets/145416827/a722074b-499c-4431-b9e9-d0aece44fdea)

- Implement overflow menu for actions #3 and beyond

Details about sizing
- [ ] Button still `28x28px`
- [ ] Icons should be `18x18px`
- [ ] Emoji size should be `18x18px` (or visually so)
- [ ] Spacing between buttons should be `0px`
- [ ] Height of menu should be `36px`
- [ ] Menu padding should remain `4px`

## That should give us:
![image](https://github.com/Expensify/App/assets/145416827/2e1dd45e-041e-4cee-a2a3-ccaf673a0567)
![image](https://github.com/Expensify/App/assets/145416827/2459abce-ad6b-4a57-a8ba-801bf64ee120)
![image](https://github.com/Expensify/App/assets/145416827/7c301817-3c7c-4f08-ad00-a25fac7b62ea)
![image](https://github.com/Expensify/App/assets/145416827/cf8e825d-2755-480e-b694-2ffa301748ff)
![image](https://github.com/Expensify/App/assets/145416827/191522d4-f0c7-4a07-9a20-738695575fd7)

Realtime discussion in Slack here: https://expensify.slack.com/archives/C0671JDRKQW/p1703546061230429?thread_ts=1703546004.757449&cid=C0671JDRKQW

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017316d0730ce02286</li>
        <li>Upwork Job ID: 1742747999864901632</li>
        <li>Last Price Increase: 2024-01-26</li>
<li>Automatic offers: </li>
<ul>
<li>esh-g | Contributor | 28080976</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by quinthar** [comment] 2024-01-03 03:28
I don't think @NikkiWines is needed; @dubielzyk-expensify can you update the original post of this to outline how you want to update the hover menu, and then tag with `external + task + daily` to get an external contributor assigned to it?

**Comment by esh-g** [comment] 2024-01-03 11:30
# Proposal

## Please re-state the problem
Rename "Subscribe" in action menu to "Join"

## What is the root cause?
N/A (New feature)

## What changes should be made to fix this?
The solution suggests three options. Here are possible implementations for all of them:
1. Remove the 'subscribe to thread' and 'unsubscribe to thread' options entirely by removing them from the `ContextMenuActions` here:
https://github.com/Expensify/App/blob/2fe11741539c96dadd2ce109b8538b01d02a60cb/src/pages/home/report/ContextMenu/ContextMenuActions.js#L152-L155
https://github.com/Expensify/App/blob/2fe11741539c96dadd2ce109b8538b01d02a60cb/src/pages/home/report/ContextMenu/ContextMenuActions.js#L190-L193

2. Re-name the action to 'join thread'. This can be done by adding translation keys for `reportActionContextMenu.joinThread` and `reportActionContextMenu.leaveThread` and then using them in the places mentioned in point 1. We can also change the icon from `Expensicons.Bell` to `Expensicons.ChatBubbles` to mirror the room behaviour even more consistently.

3. Re-name the action to 'follow thread'. This is similar to point 2 and can be done with the same process.

### Additional change proposals

**Option 1**
<img width="549" alt="Screenshot 2024-01-03 at 4 48 37 PM" src="https://github.com/Expensify/App/assets/77237602/ee64b418-8cd6-46eb-a3e6-47a82eaa8530">

The language slack uses is 'Get notified about new replies' which is very clear cut but very lengthy unfortunately for the Expensify app.
<img width="302" alt="Screenshot 2024-01-03 at 4 49 46 PM" src="https://github.com/Expensify/App/assets/77237602/b8ecfe32-20e0-4075-aff2-844a136dbd9b">

**Option 2**
What can be done also is use the `getDescription` property on the context menu action to have a description that explains the property so that there is no confusion for the user.
https://github.com/Expensify/App/blob/2fe11741539c96dadd2ce109b8538b01d02a60cb/src/pages/home/report/ContextMenu/ContextMenuActions.js#L187-L189
<img width="302" alt="Screenshot 2024-01-03 at 4 58 43 PM" src="https://github.com/Expensify/App/assets/77237602/75f2b3ec-f3c6-4de5-8e06-75d638275669">

**Comment by dubielzyk-expensify** [comment] 2024-01-04 03:22
Description updated to reflect latest changes, @quinthar

**Comment by rushatgabhane** [comment] 2024-01-04 03:58
This is a straightforward implementation. Let's hire @esh-g for their [proposal](https://github.com/Expensify/App/issues/33573#issuecomment-1875222992)
🎀 👀 🎀

**Comment by rushatgabhane** [comment] 2024-01-04 04:01
> Additional change proposals

> <img width="329" alt="image" src="https://github.com/Expensify/App/assets/29673073/786b7372-686d-4e85-9523-77ad86a5a3ad">

@esh-g this is smart but it kinda looks cluttered. Since this is a CRITICAL issue, let's raise a PR as soon as possible after assignment.

Meanwhile, @dubielzyk-expensify what do you think about adding description as proposed by @esh-g ?

**Comment by dubielzyk-expensify** [comment] 2024-01-04 04:21
Does this proposal include the new changes? I updated this from the original proposal. It's not just about changing the wording anymore

I like the idea, but because we don't do it anywhere else we'll skip on doing the description for now :)

**Comment by rushatgabhane** [comment] 2024-01-04 05:18
@esh-g could you please update your proposal to include the sizing changes too?

**Comment by esh-g** [comment] 2024-01-04 12:20
@rushatgabhane Included all the changes in the [updated proposal](https://github.com/Expensify/App/issues/33573#issuecomment-1875222992)!

**Comment by mountiny** [comment] 2024-01-04 14:14
Thanks, lets go, @esh-g  feel free to bring any question to Slack where Jon, me or Rushat can answer faster :)

**Comment by quinthar** [comment] 2024-01-08 01:24
What your ETA for getting this done?  Thanks!

**Comment by rushatgabhane** [comment] 2024-01-08 02:47
@dubielzyk-expensify could you please help us with the icon svgs for
- comment_bubble_add
- comment_bubble_unread

**Comment by dubielzyk-expensify** [comment] 2024-01-08 03:02
Here you go. Renamed based on naming in [repo](https://github.com/Expensify/App/tree/main/assets/images):
[chatbubble.zip](https://github.com/Expensify/App/files/13855898/chatbubble.zip)

**Comment by quinthar** [comment] 2024-01-09 01:19
Is this something we expect to get done this week?

**Comment by esh-g** [comment] 2024-01-09 16:00
Yes @quinthar I think it should be done before this weekend. [PR](https://github.com/Expensify/App/pull/34031) is up to date just waiting for @rushatgabhane to review again

**Comment by quinthar** [comment] 2024-01-12 23:57
Still on track for today?

**Comment by esh-g** [comment] 2024-01-13 09:44
@quinthar Yes, if anything unexpected doesn't come up, we should be able to merge today 
cc @rushatgabhane

**Comment by dubielzyk-expensify** [comment] 2024-01-14 23:08
I made a comment on [the PR](https://github.com/Expensify/App/pull/34031#issuecomment-1891103980) with one outstanding issue

**Comment by esh-g** [comment] 2024-01-15 02:36
Here is the thread where we discussed that change. Please weigh in: https://expensify.slack.com/archives/C01GTK53T8Q/p1704887111830419

**Comment by mountiny** [comment] 2024-01-15 15:04
Merged

**Comment by dubielzyk-expensify** [comment] 2024-01-21 23:29
Just realized that the unread icon isn't implemented:
![CleanShot 2024-01-22 at 09 28 48@2x](https://github.com/Expensify/App/assets/145416827/2e6eca16-c513-44f2-8bb5-7a7e5abfaa7b)

The mail icon should be the new unread icon as outlined the description:
![image](https://github.com/Expensify/App/assets/145416827/7aa2ca2d-992a-4a30-814f-5baa1005e9db)

**Comment by dubielzyk-expensify** [comment] 2024-01-22 23:57
Thanks!

**Comment by mountiny** [comment] 2024-01-26 11:57
Payment is $600 for @esh-g @rushatgabhane  see reasoning [here](https://github.com/Expensify/App/issues/34739#issuecomment-1911580124)

**Comment by mountiny** [comment] 2024-01-31 16:22
@muttmuure this is ready for payment now

**Comment by esh-g** [comment] 2024-02-03 17:30
gentle bump @muttmuure

**Comment by rushatgabhane** [comment] 2024-02-03 18:36
$ requested here https://staging.new.expensify.com/r/2143839370405563

**Comment by JmillsExpensify** [comment] 2024-02-03 18:38
$600 approved for @rushatgabhane based on comment above.

**Comment by mountiny** [comment] 2024-02-05 10:39
Ready for payment @muttmuure

**Comment by muttmuure** [comment] 2024-02-05 11:06
Handling

**Comment by muttmuure** [comment] 2024-02-05 11:08
@esh-g paid $600 on Upwork

**Closed** 2024-02-05 11:08 UTC
Labels: External, Engineering, Daily, NewFeature, Awaiting Payment
