### ISSUE TITLE
[HOLD for payment 2023-09-04] [$1000] Reimburse - 0.5 is allowed, but .5 is not allowed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25514] opened 2023-08-18 21:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to reimbursement
2. Track distance
3. Go inside rate per mile
4. Change rate to 0.5 click save, it’s accepted
5. Change rate to .5 click save, it throws validation error

## Expected Result:
.5 is valid rate, should not throw error

## Actual Result:
Throws error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Chrome
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1831f09e-cd8a-4967-886e-bc88558f35b0

https://github.com/Expensify/App/assets/78819774/c26edd7e-1e10-4e3a-9f37-128b80af3649

**Expensify/Expensify Issue URL:**
 
 **Issue reported by:** @premsjce
 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691592935896589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01db7922b3ba7a8491</li>
        <li>Upwork Job ID: 1693978352051523584</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26272077</li>
<li>GItGudRatio | Contributor | 26272078</li>
</ul></li>
    </ul>
</details>

**Comment by ShogunFire** [comment] 2023-08-21 13:21
Is that really a bug, it's a bit different but when we did that page they said saving `1.` was an issue

**Comment by bfitzexpensify** [comment] 2023-08-22 13:27
>Is that really a bug, it's a bit different but when we did that page they said saving 1. was an issue

To me, `1.` is an invalid number, since I couldn't say reliably what it was meant to be. It's reasonable to type `.5` since it's reasonably obvious that it means `0.5`

**Comment by cubuspl42** [comment] 2023-08-22 15:07
The proposal by @GItGudRatio seems to solve the problem cleanly and his bot was the fastest. Other proposals look similar.

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment] 2023-08-22 15:17
@dukenv0307 I decided to postpone the heavy regex testing, including the corner cases, to the implementation phase. I definitely agree that handling corner cases is important.

**Comment by Premsjce** [comment] 2023-08-22 23:59
@MelvinBot 
Contributor details
Your Expensify account email: premsjce@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0182bbbcf31ac0306f

**Comment by cubuspl42** [comment] 2023-08-29 20:19
- The PR that introduced the bug has been identified. Link to the PR:
    - N/A (the desired behavior was always missing in the component)
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No need for a new regression test
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by trjExpensify** [comment] 2023-08-31 15:23
👋 @bfitzexpensify @conorpendergrast, can you reduce the payment for @cubuspl42 by 50% when you pay this please? 

We missed a regression [here](https://github.com/Expensify/App/issues/24216#issuecomment-1699465126) and I already settled up. Thanks!

**Comment by conorpendergrast** [comment] 2023-08-31 15:58
Sure Tom, thanks for that. Added into this comment https://github.com/Expensify/App/issues/25514#issuecomment-1696127816

**Comment by Premsjce** [comment] 2023-09-03 02:06
@bfitzexpensify @conorpendergrast :
I’m the submitter of the issue, but didn’t get any upwork job offer yet, is this expected?
I’ve submitted proposal for the job posted ad well.
Please do let me know, whats the usual process?
Thanks

**Comment by cubuspl42** [comment] 2023-09-03 09:35
@trjExpensify @conorpendergrast Actually, technically speaking, that should be "minus $500", not "minus 50%", as this is a financial correction, not something related to this issue

**Comment by conorpendergrast** [comment] 2023-09-04 08:32
@cubuspl42 Ah, I believe the deduction should be $1000. Here's my maths: 

* Price for the original issue was $1000, plus urgency bonus of $500. That's a total of $1500 paid you to
* With regressions, we ignore urgency bonus and deduct 50% from the price, which makes $500 (1000 * 50%)
* So that issue was overpaid by $1000, and that will be applied here

**Comment by conorpendergrast** [comment] 2023-09-04 08:33
@Premsjce offer sent now, thanks for applying on the job!

**Comment by Premsjce** [comment] 2023-09-04 08:48
@conorpendergrast : thank you.. accepted the offer in upwork, now the status is contract started.
When this issue is closed here only then i can submit work for payment right?

**Comment by conorpendergrast** [comment] 2023-09-04 08:49
I'll pay today and then close out the contract, you don't need to do anything else here!

**Comment by conorpendergrast** [comment] 2023-09-04 19:44
Payouts due:

- [x] Issue Reporter: $250 @Premsjce 
- [x] Contributor: $1500 @GItGudRatio 
- [x] Contributor+: $500 @cubuspl42 ($1000 + 50% urgency bonus = $1500, [minus regression penalty for previous issue](https://github.com/Expensify/App/issues/25514#issuecomment-1704841443) of $1000

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/25514#issuecomment-1690089349)

Upwork job is [here](https://www.upwork.com/jobs/~01db7922b3ba7a8491).

All done, thanks everyone. Closing out!

**Closed by conorpendergrast** 2023-09-04 19:44 UTC
Labels: External, Daily, Awaiting Payment, Bug
