### ISSUE TITLE
Expense - LHN for expense report shows user email instead of detach receipt message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38532] opened 2024-03-18 22:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Create a manual request with receipt
4. Go to request details page
5. Click on the receipt > 3-dot menu > Delete receipt
6. Delete the receipt
7. Return to expense report

## Expected Result:
LHN for expense report will show the message "You detached a receipt from expense"

## Actual Result:
LHN for expense report briefly shows the message "You detached a receipt from expense", then changes to user email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4b434c53-e79b-48ac-83b7-b748cb30ebb2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0132cf050c37cb1c78</li>
        <li>Upwork Job ID: 1770147132270587904</li>
        <li>Last Price Increase: 2024-03-19</li>
    </ul>
</details>

**Comment by aldo-expensify** [comment] 2024-03-18 22:33
Doesn't look like a bug to me, I think the email is just part of the LHN message for "xxx@yyy.com detached a receipt from expense 'a'", but the email is so long that we don't see anything else.

**Comment by aldo-expensify** [comment] 2024-03-18 22:51
I'm wrong, if the email is short, only the email is there:

<img width="850" alt="image" src="https://github.com/Expensify/App/assets/87341702/261e3540-e504-4984-b240-1e8c735c17d1">

**Comment by aldo-expensify** [comment] 2024-03-19 00:19
I'm seeing that the front end is receiving `lastMessageHTML` and `lastMessageHtml`:

<img width="427" alt="image" src="https://github.com/Expensify/App/assets/87341702/e633195a-6957-46e4-9e5a-0ed0ceaff045">

Asking if this looks like a bug or was intended. The message in `lastMessageHTML` seems to contain the right information

**Comment by aldo-expensify** [comment] 2024-03-19 00:20
I don't think this is important enough to block deploys on it.

**Comment by aldo-expensify** [comment] 2024-03-19 02:26
Chatting with @jasperhuangg  here: https://expensify.slack.com/archives/C03TQ48KC/p1710807445236389

@jasperhuangg is preparing a backend fix 🎉

**Comment by jasperhuangg** [comment] 2024-03-19 02:57
This doesn't need to be a blocker since the fix is in the back-end.

**Comment by jasperhuangg** [comment] 2024-03-19 02:58
Gonna keep @aldo-expensify since he did the initial investigation on this

**Closed** 2024-03-26 23:31 UTC
Labels: Reviewing, Engineering, Daily, Internal
