### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] App keeps the  hover state when returning back from the opened links

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18675] opened 2023-05-09 20:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app in mac chrome/mac safari
2. Open settings
3. Click on help link
4. Revisit the expensify tab and observe that link still has background hover color

## Expected Result: 
App should remove the hover effect from link background when clicked (when visiting external link) - like it does on Windows Chrome

## Actual Result: 
App keeps the hover effect on external link even when we click and visit the link

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1edf7370-895b-483b-b695-4d0780ef4cb0

https://github.com/Expensify/App/assets/43996225/0bffd13a-c062-4c0c-ab25-19197e833728

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683626608112949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016746e1721b3e89aa</li>
        <li>Upwork Job ID: 1656133072671420416</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-05-10 02:54
Yep, can repro this one!

**Comment by jliexpensify** [comment] 2023-05-10 03:05
@jasperhuangg @aimane-chnaif - curious to get your thoughts: will @allroundexperts proposal in https://github.com/Expensify/App/issues/16923 resolve this issue as well?

**Comment by mostfa29** [comment] 2023-05-11 09:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem we are trying to solve in this issue is that the App's hover effect on a link's background is not being removed when the link is clicked and visited externally. 

### What is the root cause of that problem?
The root cause of the problem is that when a user clicks on an external link, the focus is shifted away from the component, but the onBlur event is not triggered. As a result, the onPressOut event is not triggered either.

### What changes do you think we should make in order to solve the problem?
In order to solve the problem, we can add an event listener to the external link and manually trigger the onBlur event for the component when the external link is clicked. This will ensure that the onPressOut event is triggered even when the focus is shifted away from the component.

### What alternative solutions did you explore? (Optional)
I explored several alternative solutions, including using the onFocus event instead of onBlur, and using a different event handler for external links. However, I found that manually triggering the onBlur event was the most effective solution.

**Comment by mostfa29** [comment] 2023-05-11 09:20
```
Contributor details
Your Expensify account email: amin29199@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011bc7e925bdaf6efe
```

**Comment by jasperhuangg** [comment] 2023-05-17 20:40
still on HOLD

**Comment by jasperhuangg** [comment] 2023-05-17 20:50
@allroundexperts If your proposal isn't able to fix all instances of this issue in one-fell swoop, then I think this particular instance of the issue isn't worth fixing, since when the user navigates back to the page the issue disappears.

**Comment by jasperhuangg** [comment] 2023-05-22 22:41
Got it, I think I just wanted to clarify that we should use a proposal that fixes this issue on all levels, as opposed to proposing some band-aid fix only for this once instance.

This is not a major problem and honestly isn't worth fixing unless the solution fixes other, more important instances (e.g. https://github.com/Expensify/App/issues/16923) of this issue as well.

**Comment by jliexpensify** [comment] 2023-05-26 05:31
Not overdue!

**Comment by jasperhuangg** [comment] 2023-05-29 14:11
Not overdue

**Comment by jasperhuangg** [comment] 2023-06-01 06:56
@aimane-chnaif I'm gonna be going OOO next week, so if you receive proposals and I'm not around to help review/approve them feel free to ask another internal engineer to help push this forward, thanks!

**Comment by jasperhuangg** [comment] 2023-06-12 13:28
Looks like there's a proposal [here](https://github.com/Expensify/App/issues/18555#issuecomment-1561722967) that was recently updated which should solve this issue at its root. 

cc @aimane-chnaif @parasharrajat do you mind giving it a second/third set of eyes? I've read through it and it looks good to me. If so we should be able to knock this and https://github.com/Expensify/App/issues/18555#issuecomment-1561722967 out in one fell swoop.

**Comment by jasperhuangg** [comment] 2023-06-14 17:32
awesome!

**Comment by jliexpensify** [comment] 2023-06-14 23:08
Just confirming: do we take this off HOLD?

**Comment by jasperhuangg** [comment] 2023-06-22 17:22
We are still discussing in Slack, but it sounds like the context approach works but is considered another workaround.

**Comment by cubuspl42** [comment] 2023-06-27 10:07
@jasperhuangg 

I [submitted a proposal](https://github.com/Expensify/App/issues/21605#issuecomment-1608193347) for a duplicate of this issue (as I didn't know it was a dupe). I think that it can be considered an acceptable approach for this issue, and not merely a workaround.

**Comment by jasperhuangg** [comment] 2023-06-27 17:04
@cubuspl42 It doesn't seem like your proposal would fix the issue as described in https://github.com/Expensify/App/issues/18555, as the visibility of the element never becomes hidden. Can you confirm?

**Comment by cubuspl42** [comment] 2023-06-27 18:03
@jasperhuangg I do confirm. But at the same time, I have doubts about whether [the proposal you mentioned](https://github.com/Expensify/App/issues/18555#issuecomment-1561722967) will actually solve our issue. It relies on tracking the mouse position, and after the link is pressed and the browser opens the new tab, we can't track the mouse position until our tab gets focused again. At least I understand things this way.

**Comment by cubuspl42** [comment] 2023-06-28 11:05
@aimane-chnaif

You're right, a fix on the `Hoverable` level won't solve this issue. It does solve #21605, though, as that issue is about a tooltip, and `Tooltip` does depend on `Hoverable`.

Do you know when/why `MenuItem` stopped using `Hoverable`?

**Comment by jliexpensify** [comment] 2023-07-03 05:11
Hi, got an overdue ping here. @cubuspl42 any additional changes to your proposal? @aimane-chnaif should we take this off hold?

**Comment by cubuspl42** [comment] 2023-07-03 10:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When a `MenuItem` directing to an external URL is pressed, it remains in the hovered state when the Expensify tab is selected again.

### What is the root cause of that problem?

At least in some browsers, `Pressable` (and our internal wrappers around it) is not updating the `hovered` state when the browser tab is switched.

### What changes do you think we should make in order to solve the problem?

First, let's update `Hoverable` to unhover when the `Document` visibility becomes `'hidden'`.

Then let's use `Hoverable` in `MenuItem`.

### What alternative solutions did you explore?

I explored the possibility of adjusting the `BasePressable` implementation, but in the end, I considered it an inferior solution.

**Comment by jliexpensify** [comment] 2023-07-04 04:31
@mallenexpensify Hello, I am headed OOO this week. Have assigned you to keep an eye on hiring, but atm we are still sourcing proposals. Will unassign you when I get back!

**Comment by jasperhuangg** [comment] 2023-07-06 19:01
@cubuspl42 Thanks for the proposal! I think it makes sense to me, given that the requirements have changed. Thanks for clarifying how we're using Hoverable.

@aimane-chnaif what are your thoughts on this proposal?

**Comment by cubuspl42** [comment] 2023-07-07 11:25
@aimane-chnaif 

> > but in the end, I considered it an inferior solution.
> 
> @cubuspl42 can you elaborate more detail?

From my perspective, these are the reasons:

1. `Pressable` / `hovered` is not a "core" React Native API. It's [not mentioned in the docs](https://reactnative.dev/docs/pressable). Although the relevant classes are imported from React Native import paths, this functionality is mixed-in via React Native for Web.
    - In consequence, this API [is not present in the official TypeScript typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/57b1cd2e7aef45d6ca5cb8e0fad99e445bd581c6/types/react-native/Libraries/Components/Pressable/Pressable.d.ts#L16). This will not make Expensify's TypeScript migration easier.
2. Using `Pressable` hover state can be problematic in some cases (when [nesting is involved](https://github.com/Expensify/App/blob/0ee7dfa0dadb6ba11ca4cf08085df9003b0fb452/src/components/Hoverable/index.js#L5-L9)) and is exactly the reason why `Hoverable` was introduced in the first place.
3. Last, but not least, implementing this functionality on the `Pressable` level seemed to be problematic. I gave it a try and I couldn't make it work. It probably wasn't something unsolvable, but during my attempt I discovered the facts that I summed up above, which made me feel that this isn't the path I'm willing to investigate further.

**Comment by jasperhuangg** [comment] 2023-07-07 20:17
@cubuspl42 That makes sense to me, thanks for explaining.

**Comment by jliexpensify** [comment] 2023-07-09 22:26
Back now, unassigning Matt.

**Comment by jasperhuangg** [comment] 2023-07-11 18:58
Thanks for the discussion and patience with this one, I'm gonna be assigning @cubuspl42, looking forward to working with ya!

**Comment by jliexpensify** [comment] 2023-07-11 23:09
Hmm @aimane-chnaif it says the Upworks job is closed. Did you get an actual invite?

**Comment by jliexpensify** [comment] 2023-07-12 02:45
Weird ok, I guess the following is happening:

1. Upworks jobs longer than 1 month are being auto-closed (?)
2. When an Engineer assigns a contributor, since the job is closed, they don't get the invite

I'll create a manual job, this is pretty annoying!

**Comment by jliexpensify** [comment] 2023-07-12 02:55
https://www.upwork.com/jobs/~01ae392bba5fe121b4

Invites sent!

**Comment by dhanashree-sawant** [comment] 2023-07-12 04:59
@jliexpensify, Thanks! Offer accepted.

**Comment by cubuspl42** [comment] 2023-07-15 08:50
@MelvinBot Well, you're technically right, but it nearly made it, the PR was submitted 4 hours after the assignment and the review comments were minor. What took the time was waiting for review. But you're a good bot anyway.

**Comment by jliexpensify** [comment] 2023-07-17 00:56
Yeah, that's fine - we'll pay put a bonus since you just missed out on the timeframe @cubuspl42 . Btw, you invoice us separately, correct?

**Comment by jliexpensify** [comment] 2023-07-25 05:33
@aimane-chnaif bump to please complete the checklist

Looks like this qualifies for a [bonus](https://github.com/Expensify/App/issues/18675#issuecomment-1636506943)

@cubuspl42 - just confirming, do you invoice us separately?

**Comment by cubuspl42** [comment] 2023-07-25 07:14
@jliexpensify I'm sorry but I don't understand the question 🙁 Is it related to something on Upwork?

**Comment by jliexpensify** [comment] 2023-07-25 07:39
Yes @cubuspl42 - I'm just wondering if you're from an external agency and invoicing us separately, or if you've got an Upworks profile? :)

**Comment by cubuspl42** [comment] 2023-07-25 07:42
@jliexpensify Via Upwork: https://www.upwork.com/freelancers/jakubt

**Comment by jliexpensify** [comment] 2023-07-25 07:45
Great, thanks - I'll pay out in a couple of days: https://www.upwork.com/jobs/~01ae392bba5fe121b4

Jakub / Aimane - $1500
Dhanashree - $250

**Comment by jliexpensify** [comment] 2023-07-27 05:28
Everyone is paid and job is closed!

**Closed by jliexpensify** 2023-07-27 05:28 UTC
Labels: External, Daily, Awaiting Payment, Bug
