### ISSUE TITLE
[$500] Fix style regressions caused by new Global Nav component

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29057] opened 2023-10-07 20:23 UTC
This issue handles all regressions stemmed from the addition if the new Global Nav component in [this PR](https://github.com/Expensify/App/pull/28277). Any proposals should handle all these regressions. Please refer to the screenshots attached for the new design requirements to solve these issues.

cc: @allroundexperts

- Sign in button on Global Nav is cropped (the original issue)
  <img width="400" alt="Screenshot 2023-10-11 at 2 34 12 PM" src="https://github.com/Expensify/App/assets/98560306/b4308b05-a602-48c4-bfb8-fa0dfb4524d3">

- [Avatar on Global Nav is cropped](https://github.com/Expensify/App/issues/29133)
<img width="200" alt="Screenshot 2023-10-11 at 2 35 05 PM" src="https://github.com/Expensify/App/assets/98560306/947cfb85-9be7-4093-bf31-d2ddc044988f">

- [Avatar on Global Nav is very close to the native icons on desktop](https://github.com/Expensify/App/issues/29162)

- [Settings Background for profile details Header is changed unintentionally while refactoring LHN](https://github.com/Expensify/App/issues/29085)

- [Sign in banner for anonymous user don't have a highlighted green background color](https://github.com/Expensify/App/issues/29058)

**Comment by ashishBajracharyaFrostidi** [comment] 2023-10-08 04:18
the sidebar has a fixed width which is causing this issue, giving a variable width to the sidebar relative to the button width will solve this issue, even in the future if the button text changes or the font size increases, it won't cause a problem. #simpleCSSHacks

**Comment by ashishBajracharyaFrostidi** [comment] 2023-10-08 04:26
Contributor details
Your Expensify account email: ashish.bajracharya.frostdigi.ai@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0135bbe272a370da40

**Comment by maxconnectAbhi** [comment] 2023-10-08 04:31
# Proposal

## Please re-state the problem that we are trying to solve in this issue
Login - Sign in button for anonymous user on New LHN Nav is not fitting

## What is the root cause of that problem?
Sign in Button has a width of **82** px while the globalNavigation container has width of **70** px so the sign in button does not fit in container


## What changes do you think we should make in order to solve the problem?
We should make the width for sign in button **95**% of the container here
`width: '95%'
`https://github.com/Expensify/App/blob/389d7b0c4b96c6f2a2295055c685791d35b65252/src/styles/styles.js#L2296-L2298


## What alternative solutions did you explore? (Optional)
NA

**Comment by hayata-suenaga** [comment] 2023-10-10 00:01
## 🚨 Can you combine this issue with [this issue](https://github.com/Expensify/App/issues/29133)?

**Comment by hayata-suenaga** [comment] 2023-10-10 00:02
melvin, please remove the `overdue` label.

**Comment by hayata-suenaga** [comment] 2023-10-10 00:35
assigning myself as this is a regression from a wave 8 issue

**Comment by hayata-suenaga** [comment] 2023-10-10 05:02
# Design discussion is happening in [this App issue](https://github.com/Expensify/App/issues/29136)

**Comment by hayata-suenaga** [comment] 2023-10-10 05:10
# Please see the OP. This issue combined [this issue](https://github.com/Expensify/App/issues/29133).

# Please hold your proposals until the design decision is made ⬆️

**Comment by hayata-suenaga** [comment] 2023-10-11 05:38
# OP was changed. Please update your proposals to reflect the new requirements 🙇

**Comment by b4s36t4** [comment] 2023-10-11 05:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Fix style regressions caused by new Global Nav component
### What is the root cause of that problem?

1. Sign in button on Global Nav is cropped

Previously we have the Signin button at the top, now we need to replace it with the expensify logo. https://github.com/Expensify/App/blob/0cbee2247e48c17eec428b989afead3dc6f196d4/src/pages/home/sidebar/SignInOrAvatarWithOptionalStatus.js#L40 in this file we need to make changes and remove Signin Button also remove the component as at this only file.

2. Avatar on Global Nav is cropped

Avatar on glbal nav is only cropped because of the width issue which only happens if we have custom status. 

3. Avatar on Global Nav is very close to the native icons on desktop

Previously we used to have same bg color on the header so it won't be visible. After added the new bg over the global we have different bg colors.

### What changes do you think we should make in order to solve the problem?

1. Update `SignInButton` https://github.com/Expensify/App/blob/0cbee2247e48c17eec428b989afead3dc6f196d4/src/pages/home/sidebar/SignInOrAvatarWithOptionalStatus.js in this file to use Expensify logo.

2. Use `position` property to update the styling of the custom status.

3. Update https://github.com/Expensify/App/blob/d916effd3ffb2f29adcd3cfad1e314f210a23efa/src/CONST.ts#L885 this line with the height (26) is tested. more on here https://github.com/Expensify/App/issues/29162#issuecomment-1754788318


### What alternative solutions did you explore? (Optional)
NA

**Comment by hayata-suenaga** [comment] 2023-10-11 12:50
@shawnborton this is the follow up issue for the PR that added the new Global Nav component

**Comment by hayata-suenaga** [comment] 2023-10-11 13:02
We decided that an engineer from an expert agency is going to work on this issue.

Thank you for all contributors who shared detailed proposals here. We really appreciate the time you took to write these 🙇

**Comment by hayata-suenaga** [comment] 2023-10-11 13:14
@0xmiroslav you don't have to review proposals as an expert agency is going to work on it. We gonna keep you assigned to this issue so that you can review the PR when it's open 🙇

**Comment by hayata-suenaga** [comment] 2023-10-11 14:09
Added [this issue](https://github.com/Expensify/App/issues/29058) to the OP.

**Comment by stitesExpensify** [comment] 2023-10-11 22:15
@kosmydel @robertKozik I heard you guys are interested in fixing these issues?

**Comment by hayata-suenaga** [comment] 2023-10-16 00:01
@kosmydel @robertKozik could you also take a look at [this issue](https://github.com/Expensify/App/issues/29079)?

**Comment by hayata-suenaga** [comment] 2023-10-16 12:09
omg the style system of App is just too intertwined...

@kosmydel @robertKozik ⬆️

**Comment by hayata-suenaga** [comment] 2023-10-23 01:52
@kosmydel @robertKozik could you check if your fix will handle [this regression, too](https://github.com/Expensify/App/issues/29870)?

**Comment by robertKozik** [comment] 2023-10-23 09:17
@hayata-suenaga, I believe we didn't include this regression because we didn't notice it before. However, we can easily add it to the PR to keep all the fixes in the same place.

**Comment by hayata-suenaga** [comment] 2023-10-24 01:44
> Should we proceed with the fix inside our PR as in my opinion it would be better to keep all related fixes inside one PR?

Yes let's handle in your PR 👍 

We can close this issue if no payment is necessary (@robertKozik is a SWM engineeer)

**Comment by hayata-suenaga** [comment] 2023-11-02 17:27
The PR was closed with implementation

Payment summary

C+ Review payment for @situchan

**Comment by hayata-suenaga** [comment] 2023-11-03 22:52
@situchan could you check the above comment ⬆️ ?

**Comment by situchan** [comment] 2023-11-04 02:47
Maybe we can pay @ishpaul777 one-time bonus ($50) for all these kinds of reports as they are regressions from one PR, if closed issues also apply bonus.
@zanyrenney will decide.

**Comment by hayata-suenaga** [comment] 2023-11-27 16:43
@zanyrenney could you handle the payment according to [this suggestion](https://github.com/Expensify/App/issues/29057#issuecomment-1793313762)?

**Comment by hayata-suenaga** [comment] 2023-12-05 16:53
if the payment has been completed, we can close this issue 🙇

**Comment by situchan** [comment] 2023-12-05 17:44
@hayata-suenaga can you please remove `Reviewing` which prevents adding `Overdue`? This way, @zanyrenney will be bumped every few days

**Comment by hayata-suenaga** [comment] 2023-12-11 20:41
I'm closing this issue. Please comment here if we need payments for this issue.

**Comment by situchan** [comment] 2023-12-11 21:01
I noticed that @zanyrenney's slack status indicates OOO until Wed

**Comment by zanyrenney** [comment] 2023-12-13 19:05
![2023-12-13_19-03-52](https://github.com/Expensify/App/assets/56830058/4c41ee36-5721-4de6-bfce-a6ee02cdca91)

payment summary - @ishpaul777 $50 for regression reports.

As per this [comment](https://github.com/Expensify/App/issues/29057#issuecomment-1841221554), closing.

**Comment by zanyrenney** [comment] 2023-12-14 16:12
Paid @situchan through bonus due to problem with hourly contract.

**Closed by zanyrenney** 2023-12-14 16:12 UTC
Labels: Daily, Bug

**Comment by zanyrenney** [comment] 2023-12-14 16:25
Paid @situchan via a bonus as I messed up the orignal offer and made it hourly. Closing!

**Comment by zanyrenney** [comment] 2023-12-14 16:25
![2023-12-14_16-20-46](https://github.com/Expensify/App/assets/56830058/c8ce5ee8-6542-4339-8573-9e9a56ac4e11)
