### ISSUE TITLE
 IOU - Details modal is dismissed after editing title

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44963] opened 2024-07-08 13:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** New feature
**Email or phone of affected tester (no customers):** natnael.expensify+0a89fdndafadf@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to a workspace chat
2. Submit a manual expense
3. Click on the IOU preview component
4. Click on report header > Title
5. Edit title & click Save

## Expected Result:
User should be returned to Details RHP

## Actual Result:
Details RHP modal is dismissed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9eb6d15a-0c5f-4fc3-bbcc-9039415340dd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-07-08 13:43
@adelekennedy I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-07-08 13:43
We think this issue might be related to the #collect project.

**Comment by etCoderDysto** [comment] 2024-07-08 13:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Details modal is dismissed after editing title
### What is the root cause of that problem?
We are dismissing the modal and navigating to the previous report here
https://github.com/Expensify/App/blob/51dd814bf6a142fbaf590b69f90932dec2fe6507/src/pages/EditReportFieldPage.tsx#L84
### What changes do you think we should make in order to solve the problem?
We should change  `Navigation.dismissModal(report?.reportID)` with Navigation.goBack()`

### What alternative solutions did you explore? (Optional)

**Comment by iwiznia** [comment] 2024-07-08 14:01
That makes sense @etCoderDysto but wouldn't that break the feature for the other places where we call this (that existed before we added the possibility of editing the title like this)?

**Comment by etCoderDysto** [comment] 2024-07-08 14:04
I have been trying to check other pages after applying. I found that different component is used other pages as room's details page. But to make things sure. I will check other places that use the same component.

**Comment by etCoderDysto** [comment] 2024-07-08 14:10
@iwiznia The component seems to be used only in `ModalStackNavigator`. 
![Screenshot 2024-07-08 at 5 07 23 in the afternoon](https://github.com/Expensify/App/assets/171434916/bf73f829-caf4-4833-a25c-dc1283bc0e22)

**Comment by Julesssss** [comment] 2024-07-08 14:15
Solution seems good 👍

**Comment by etCoderDysto** [comment] 2024-07-08 14:15
Should I raise a quick PR?

**Comment by etCoderDysto** [comment] 2024-07-08 14:27
I am raising a pr asap. And investigating what component was used before.

**Comment by etCoderDysto** [comment] 2024-07-08 17:15
@iwiznia  I have found a flow where we use [EditReportsFieldPage](https://github.com/Expensify/App/blob/51dd814bf6a142fbaf590b69f90932dec2fe6507/src/pages/EditReportFieldPage.tsx#L84). We use it in `MoneyReportView` to display editable report fields when the user has enabled 'Report Fields' in more features. 
https://github.com/Expensify/App/blob/c5c4ea8fcec6c03ebee5483b6bcacacdfbed9ebf/src/components/ReportActionItem/MoneyReportView.tsx#L83-L86

I have changed the logic to address that we don't change exiting behaviour in `MoneyReportView` as below. We navigate back only when user is changing report title.
```javascript
 if (isReportFieldTitle) {
            ReportActions.updateReportName(report.reportID, value, report.reportName ?? '');
            Navigation.goBack();
        } else {
            ReportActions.updateReportField(report.reportID, {...reportField, value: value === '' ? null : value}, reportField);
            Navigation.dismissModal(report?.reportID);
        }
        
```

**Comment by etCoderDysto** [comment] 2024-07-08 17:16
The [PR](https://github.com/Expensify/App/pull/44988) is ready for review.

**Comment by iwiznia** [comment] 2024-07-09 11:09
Ah nice, I knew that code must've been there for a reason 😄

**Comment by Julesssss** [comment] 2024-07-09 12:42
CPd. thanks

**Comment by jayeshmangwani** [comment] 2024-07-10 22:06
@adelekennedy Please assign me to the issue for tracking the payment (reviewed [PR](https://github.com/Expensify/App/pull/44988))

**Comment by adelekennedy** [comment] 2024-07-10 23:44
done @jayeshmangwani !

**Comment by etCoderDysto** [comment] 2024-07-18 13:50
@adelekennedy the pr was [deployed to production 8 days ago](https://github.com/Expensify/App/pull/44988#issuecomment-2220226090).

**Comment by adelekennedy** [comment] 2024-07-18 16:29
Thank you @etCoderDysto - the automatic update failed here.

**Comment by etCoderDysto** [comment] 2024-07-18 17:19
Yes, mevlin is not adding lables.

**Comment by adelekennedy** [comment] 2024-07-18 23:11
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by adelekennedy** [comment] 2024-07-18 23:16
Payouts due:

- [ ] Contributor: $250 @etCoderDysto (Upwork)
- [ ] Contributor+: $250 @jayeshmangwani (NewDot)

**Comment by adelekennedy** [comment] 2024-07-18 23:17
@etCoderDysto will you link your upwork profile here?

**Comment by etCoderDysto** [comment] 2024-07-18 23:19
https://www.upwork.com/freelancers/~01ea78e0164390eb79
Here is a link to my profile.
Thank you!

**Comment by jayeshmangwani** [comment] 2024-07-21 08:23
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/44671
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/44671#discussion_r1685680379
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **Yes**
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


## Regression Test Proposal

1. Go to a workspace chat.
2. Submit a manual expense.
3. Click on the IOU preview component.
4. Click on the report header -> Title.
5. Edit the title and click Save.
6. Verify that you are navigated back to the Details page.

Do we agree 👍 or 👎

**Comment by adelekennedy** [comment] 2024-07-22 19:41
offer sent @etCoderDysto

**Comment by etCoderDysto** [comment] 2024-07-22 19:44
> offer sent @etCoderDysto 

I have accepted the offer. Thank you!

**Closed** 2024-07-22 19:45 UTC
Labels: Reviewing, Engineering, Weekly, Awaiting Payment, Bug

**Comment by jayeshmangwani** [comment] 2024-07-25 04:57
Requested $250
