### ISSUE TITLE
[HOLD for payment 2024-10-30] Copilot - Nothing happens when clicking on the grayed out user when magic code is incorrect

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51266] opened 2024-10-22 16:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Security.
3. Click Add copilot.
4. Select a user > Next.
5. Select an access level > Next.
6. Click Add copilot.
7. Enter wrong magic code.
8. Click outside the RHP twice to dismiss it.
9. Click on the grayed out user under Copilot: Delegated access section.

## Expected Result:
Clicking on the grayed out user will open up magic code RHP (production behavior).

## Actual Result:
Nothing happens when clicking on the grayed out user when magic code is incorrect.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0432636e-2667-4974-98eb-7b30d99ec25b
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by bondydaa** [comment] 2024-10-22 16:11
testing reverting this locally as i'm suspicious of it https://github.com/Expensify/App/pull/49445

**Comment by bondydaa** [comment] 2024-10-22 16:29
yep testing locally I'm fairly certain https://github.com/Expensify/App/pull/49445 is the problem

cc @mountiny @getusha @hungvu193

**Comment by luacmartins** [comment] 2024-10-22 16:50
We might add a fix for this in [this PR ](https://github.com/Expensify/App/pull/51267)

**Comment by kavimuru** [comment] 2024-10-23 01:00
It's a pass

https://github.com/user-attachments/assets/4464f26d-28dc-4049-b88c-15d531676f21

**Comment by tgolen** [comment] 2024-10-23 21:27
Reopening for @bondydaa and @sakluger to finish the checklist

**Comment by bondydaa** [comment] 2024-10-24 17:35
i think we followed those steps properly, i don't think we need a regression test or rather we already have one since this was caught during testing so i think we're good here?

**Closed by bondydaa** 2024-10-24 17:35 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
