### ISSUE TITLE
[$500] Group Chat - The radio button for "Paid by" user in Split bill is not disabled when hovering over it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28331] opened 2023-09-27 16:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a group chat.
2. Navigate to the "Split bill" feature.
3. Enter the amount and click on "Next"
4. Observe the radio button for "Paid by"

## Expected Result:
 The radio button for "Paid by" should also be disabled when hovering over it

## Actual Result:
The pointer is not disabled when hovering over the "Paid by" radio button in the Split bill

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] Windows / Chrome
- [x] MacOS / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.74-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6a483367-5641-4c70-88fb-90b0a7ecec1f

https://github.com/Expensify/App/assets/78819774/d961d85e-a287-4482-aba4-2f3c5b57555f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695711981329049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0171908e7bd858377f</li>
        <li>Upwork Job ID: 1707075579287011328</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27027591</li>
</ul></li>
    </ul>
</details>

**Comment by astrohunter62** [comment] 2023-09-27 18:08
Looks like a dupe of https://github.com/Expensify/App/issues/28064#issue-1909885736

**Comment by DylanDylann** [comment] 2023-09-27 18:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web - The radio button for "Paid by" user in Split bill is not disabled when hovering over it

### What is the root cause of that problem?
- Currently, we do not add the styles.cursorDisabled to the radio button in case the "Paid by" user

### What changes do you think we should make in order to solve the problem?
- We can add the styles.cursorDisabled to the radio button if the optionRow has isDisabled: true like below:
Update https://github.com/Expensify/App/blob/cf9ad20a4545ec01b16f88f9c1a53a7488ca1b44/src/components/OptionRow.js#L283-L287 to 
```
  <PressableWithFeedback
                                                    onPress={() => this.props.onSelectedStatePressed(this.props.option)}
                                                    accessibilityRole={CONST.ACCESSIBILITY_ROLE.CHECKBOX}
                                                    accessibilityLabel={CONST.ACCESSIBILITY_ROLE.CHECKBOX}
                                                    style={this.state.isDisabled && styles.cursorDisabled}
                                                >
```
- ```style={this.state.isDisabled && styles.cursorDisabled}``` is added
### What alternative solutions did you explore? (Optional)
- NA

**Comment by PiyushChandra17** [comment] 2023-09-27 19:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - The radio button for "Paid by" user in Split bill is not disabled when hovering over it

### What is the root cause of that problem?
We are missing one prop in  `PressableWithFeedback` component of radio button ie. `disabled`

### What changes do you think we should make in order to solve the problem?
We need to add:
`disabled={this.state.isDisabled && cursor.cursorDisabled}`

Here:

https://github.com/Expensify/App/blob/e74b4d2e2922cf9fb6e3f410e9871c91a4114919/src/components/OptionRow.js#L283-L287

### What alternative solutions did you explore? (Optional)
NA

**Comment by sonialiap** [comment] 2023-10-04 05:26
@sobitneupane what do you think of the above proposals?

**Comment by sobitneupane** [comment] 2023-10-04 08:13
[Proposal](https://github.com/Expensify/App/issues/28331#issuecomment-1737787088) from @dukenv0307 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by marcaaron** [comment] 2023-10-04 22:37
I will approve this because the solution is very simple. But this "bug" is very low value IMO.

**Comment by sobitneupane** [comment] 2023-10-30 14:48
This issue is fixed by some other PR. So, [the PR](https://github.com/Expensify/App/pull/28889) created by @dukenv0307 is no longer required. Thanks @dukenv0307 for the effort.

**Closed** 2023-11-29 21:28 UTC
Labels: Reviewing, External, Monthly, Bug
