### ISSUE TITLE
[$500] [MEDIUM] Scan - No thumbnail is shown for the corrupted file in receipt preview

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37435] opened 2024-02-28 15:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Go to + > Request money > Scan.
4. Upload a corrupted file (attached below).
5. Proceed to confirmation page.

## Expected Result:
The confirmation page will show thumbnail for the corrupted file.

## Actual Result:
The confirmation page shows blank area for the corrupted file.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Bug6395765_1709133702609!Screenshot_2024-02-27_at_22 59 30](https://github.com/Expensify/App/assets/115492554/fb797a70-634d-4fc8-a1b8-d97161327f18)
![Corrupted file (1)](https://github.com/Expensify/App/assets/115492554/8d1ef8f7-70a3-4353-954e-4fe52a41ecb1)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ddfcfb2a8a486a23</li>
        <li>Upwork Job ID: 1763726750178574336</li>
        <li>Last Price Increase: 2024-04-06</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-28 15:30
@greg-schroeder I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-02-28 15:32
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by kmbcook** [comment] 2024-03-02 19:28
The corrupted file used to create this issue seems to be a very small image, only 16 x 16 pixels. A thumbnail of this image might appear blank, possibly. The corrupted file I am using works as expected. I see a thumbnail of it.

**Comment by situchan** [comment] 2024-03-04 14:54
proposals are in review

**Comment by situchan** [comment] 2024-03-08 19:37
eta Monday

**Comment by greg-schroeder** [comment] 2024-03-13 10:53
Proposal review

**Comment by situchan** [comment] 2024-03-13 19:37
<img width="650" alt="Screenshot 2024-03-14 at 1 36 42 AM" src="https://github.com/Expensify/App/assets/108292595/47fc5485-8ec8-4c83-b9d3-be25a7f01aa3">


@Expensify/design do we agree to show thumbnail when attached receipt is not previewable (i.e. corrupted image/pdf)?

**Comment by dannymcclain** [comment] 2024-03-13 19:54
I think showing a fallback image makes sense—but I'm not sure I would show that type of thumbnail. I feel like it kinda makes more sense to show our little fallback image thingy:

![CleanShot 2024-03-13 at 14 52 29@2x](https://github.com/Expensify/App/assets/7516624/2f8b03cd-4e82-4828-9beb-638c1e501fb2)

What do the other designers think?

**Comment by dubielzyk-expensify** [comment] 2024-03-13 23:37
Agree with Shawn who agrees with Danny

**Comment by situchan** [comment] 2024-03-15 21:01
Thanks for feedback.
Please update proposals.

**Comment by situchan** [comment] 2024-03-15 21:33
@Krishna2323 the expected behavior should be discussed with design team.
Why don't we just use this GH if we don't allow corrupted images? I see the the linked issue created just today with no context.

**Comment by situchan** [comment] 2024-03-22 09:03
We're going to prevent uploading corrupted PDF as scan receipt in #34032.
So to be consistent, we should not allow corrupted images.
cc: @Expensify/design to confirm the expected behavior.

**Comment by situchan** [comment] 2024-03-22 09:07
^ is only when we're able to detect if file is corrupted or not.
For no-preview files we cannot detect if corrupted or not, I think it still makes sense to show fallback image like [this](https://github.com/Expensify/App/issues/37435#issuecomment-1995579903).

**Comment by dannymcclain** [comment] 2024-03-22 13:35
>We're going to prevent uploading corrupted PDF as scan receipt in https://github.com/Expensify/App/issues/34032.
So to be consistent, we should not allow corrupted images.

@situchan that makes sense to me.

>For no-preview files we cannot detect if corrupted or not, I think it still makes sense to show fallback image like https://github.com/Expensify/App/issues/37435#issuecomment-1995579903.

Agree with this as well!

**Comment by greg-schroeder** [comment] 2024-03-25 11:24
Okay so based on above comments, can you give me a quick update on where this one stands @situchan? Are we still waiting for proposals or something else?

**Comment by situchan** [comment] 2024-03-25 15:09
We're still waiting for proposals.

**Comment by mallenexpensify** [comment] 2024-04-01 16:33
@situchan is out OOO, reassigning a C+ via the auto-assigner for fairness.

**Comment by dannymcclain** [comment] 2024-04-02 13:28
>Show the fallback thumbnail for files that do not support preview (@dannymcclain do you have any ideas what file types might fit into this category?)

😬 I honestly do not. Going to tag @shawnborton and @trjExpensify to see if they have any ideas or might know who would know.

**Comment by shawnborton** [comment] 2024-04-02 16:09
I think [this comment](https://github.com/Expensify/App/pull/34843#issuecomment-1981252770) is helpful for that question

![CleanShot 2024-04-02 at 18 08 49@2x](https://github.com/Expensify/App/assets/2319350/54e10b6c-8dd4-4570-8886-43945ed040ef)

**Comment by jsdev2547** [comment] 2024-04-03 00:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In scan request upload corrupted image file, the user is allowed to upload corrupted and no thumbnail preview is displayed on confirmation page.
### What is the root cause of that problem?
In the IOURequestStepScan step after user selects file, need to add step to handle image loading errors. The image can be checked using RNImage.prefetch api.
https://github.com/Expensify/App/blob/8300ae40dd1f882167162fa7c86d0f5152000a87/src/pages/iou/request/step/IOURequestStepScan/index.js#L178

### What changes do you think we should make in order to solve the problem?
The validateReceipt function needs to be converted to callback. Add useState variable isReceiptValid
```
const [isReceiptValid, setIsReceiptValid] = useState(false);
```

The validateReceipt function after conversion to useCallback and using RNImage.prefetch api to determine if the image is valid.
```
    const validateReceipt = useCallback((file) => {
        const {fileExtension} = FileUtils.splitExtensionFromFileName(lodashGet(file, 'name', ''));
        
        if (!CONST.API_ATTACHMENT_VALIDATIONS.ALLOWED_RECEIPT_EXTENSIONS.includes(fileExtension.toLowerCase())) {
            setUploadReceiptError(true, 'attachmentPicker.wrongFileType', 'attachmentPicker.notAllowedExtension');
            setIsReceiptValid(false);
        }

        if (lodashGet(file, 'size', 0) > CONST.API_ATTACHMENT_VALIDATIONS.MAX_SIZE) {
            setUploadReceiptError(true, 'attachmentPicker.attachmentTooLarge', 'attachmentPicker.sizeExceeded');
            setIsReceiptValid(false);
        }

        if (lodashGet(file, 'size', 0) < CONST.API_ATTACHMENT_VALIDATIONS.MIN_SIZE) {
            setUploadReceiptError(true, 'attachmentPicker.attachmentTooSmall', 'attachmentPicker.sizeNotMet');
            setIsReceiptValid(false);
        }
        RNImage.prefetch(file.uri).then(()=>{{
            fileRef.current = file;
            setIsReceiptValid(true);
        }}).catch((error) => {
            setUploadReceiptError(true, 'attachmentPicker.errorLoadingAttachment', 'attachmentPicker.invalidAttachment');
            setIsReceiptValid(false);
        })
    },[isReceiptValid])
```

The setReceiptAndNavigate function is called after the user picks the file and also needs to be converted to useCallback. The callback would only call the validateReceipt and the remaning steps to go to confirmation step can be shifted in useEffect.
https://github.com/Expensify/App/blob/8300ae40dd1f882167162fa7c86d0f5152000a87/src/pages/iou/request/step/IOURequestStepScan/index.js#L232

```
    const setReceiptAndNavigate = useCallback((file) => {
        validateReceipt(file);
    },[isReceiptValid]);
```

The useEffect has dependancy on isReceiptValid and proceeds to confirmation step if the image is valid.
```
    useEffect(()=>{
        if (isReceiptValid) {
            // Store the receipt on the transaction object in Onyx
            const source = fileRef.current.uri;
            IOU.setMoneyRequestReceipt(transactionID, source, fileRef.current.name, action !== CONST.IOU.ACTION.EDIT);

            if (action === CONST.IOU.ACTION.EDIT) {
                updateScanAndNavigate(fileRef.current, source);
                return;
            }

            navigateToConfirmationStep();
        }
    },[isReceiptValid])
```
### What alternative solutions did you explore? (Optional)

**Comment by jsdev2547** [comment] 2024-04-03 02:41
> Prevent from using corrupted images for Scan requests;
> Show the fallback thumbnail for files that do not support preview

@paultsimura I have covered pt 1, for pt 2 if going by https://github.com/Expensify/App/issues/37435#issuecomment-2032468860. I checked on staging and the fallback thumbnail is already displayed.

**Comment by shawnborton** [comment] 2024-04-03 06:43
Do you think we need an explicit icon that looks like a broken image? Like something like this? 
![image](https://github.com/Expensify/App/assets/2319350/c99d77e8-97fb-4765-9c51-a9d133814ab4)


Or maybe I am not quite understanding what you are thinking here.

**Comment by shawnborton** [comment] 2024-04-03 10:13
That also works for me. Wasn't sure what you meant by "FYI, we still don't have any fallback thumbnail for corrupted images."

**Comment by jsdev2547** [comment] 2024-04-03 10:55
> FYI, we still don't have any fallback thumbnail for corrupted images.

@paultsimura @shawnborton Please confirm, the corrupted images would be prevented from uploading in scan requests and the fallback thumbnails would only be for files which do not support previews e.g. doc, html, xml etc. Please confirm if corrupted images are also to show fallback thumbnails or if fallback thumbnails are only for files which do not support previews.

**Comment by shawnborton** [comment] 2024-04-03 10:57
Sorry I haven't been following along too closely to the original issue - but I guess now that you spell it out that way, should we even let you continue with a corrupted image? What even is a "corrupted" image? Basically if we detect upon upload that the image is corrupted, I would think we'd throw an error.

**Comment by shawnborton** [comment] 2024-04-03 10:57
cc @Expensify/design for other thoughts here too

**Comment by dubielzyk-expensify** [comment] 2024-04-03 11:04
Yeah good point. Can we detect if an image is corrupt? If so, I also think we should throw an error as early as possible instead of getting to a state where it tries to scan.

**Comment by jsdev2547** [comment] 2024-04-03 11:06
> Prevent from using corrupted images for Scan requests;
> Show the fallback thumbnail for files that do not support preview
@shawnborton @dubielzyk-expensify I understood, the user should be prevented from continuing with corrupted images, makes sense to prevent user from continuing when image is corrupted and use fallback thumbnails for files which do not support previews (doc, html , xml etc)
In the proposal, I am preventing the user from continuing if the image is corrupt.

**Comment by dannymcclain** [comment] 2024-04-03 13:27
>@Expensify/design please just confirm what would we prefer for the corrupted images:
>
>Show an alerting modal that says "The attachment upload failed" (this doesn't look like a common approach to work with errors in the App)
>Show the error on the initial page of the receipt upload (if so – please specify the placement of the error)
>Proceed to the confirmation screen, but show the thumbnail and error on it
>Any other options?

I don't think we should wait until the confirmation screen—then you'd have to basically start the entire flow over to fix it. I think it's best to do it on the actual scan step. Like Jon said, as early as possible. Here are two options for that:

- Bottom RBR error that seems fairly in line with other errors in the app
- Center modal - this doesn't quite seem like our normal pattern, but it does get the job done

Keen for @Expensify/design thoughts.

![image](https://github.com/Expensify/App/assets/7516624/17f5ae25-87b8-4f47-b128-6c603a8f7534)

> [!NOTE]
> We'll probably want some help with the actual error text. I just made something up.

**Comment by shawnborton** [comment] 2024-04-03 13:32
Yup, big fan of Danny's suggestions. When you upload an invalid file type, we use the centered modal error pattern so perhaps we could stay consistent and use that here as well.

**Comment by dannymcclain** [comment] 2024-04-03 13:35
> Yup, big fan of Danny's suggestions. When you upload an invalid file type, we use the centered modal error pattern so perhaps we could stay consistent and use that here as well.

Oh I didn't realize that but you're totally right. Agree let's just stick with that!

So based on the invalid file type flow:
![CleanShot 2024-04-03 at 08 34 31@2x](https://github.com/Expensify/App/assets/7516624/ef349b9b-39d4-47e7-9d26-80b89671a5c9)

We should probably do something like this:
![image](https://github.com/Expensify/App/assets/7516624/19b6d965-c226-48c4-ba96-024b2825279a)

**Comment by jsdev2547** [comment] 2024-04-03 13:37
@paultsimura @shawnborton @dannymcclain The centered modal error pattern is also used when the file size is too small or too large. I have used the centered pattern.

**Comment by shawnborton** [comment] 2024-04-03 13:37
Dope, I like it!

**Comment by jsdev2547** [comment] 2024-04-03 14:57
> Show the fallback thumbnail for files that do not support preview;

@dannymcclain @shawnborton 
Also please confirm if going with https://github.com/Expensify/App/issues/37435#issuecomment-1995579903, the fallback thumbnails for files which do not support previews can either use app theme background or use color codes based on file extension (https://github.com/Expensify/App/issues/37435#issuecomment-2032468860)

I have poc to demonstrate use of app theme bg and color coded file extension.

fallback thumbnails using color codes

[poc01.webm](https://github.com/Expensify/App/assets/161593779/cc9b04bf-f74a-4707-8b2a-51c6a2e1e5fb)

fallback thumbnails without color codes

[poc02.webm](https://github.com/Expensify/App/assets/161593779/0cdff764-a423-4992-9982-d5938ad3708f)

**Comment by dannymcclain** [comment] 2024-04-03 15:05
Hmm, I'm torn a bit. Curious what Shawn thinks. I kinda like the color codes? But I'm wondering if it makes sense to use them or not. Using the color codes makes it feel more "filled" which is kinda nice, but it also makes it feel a lot more like an eReceipt (for card transactions) and I don't know if that's a good thing or not.

**Comment by shawnborton** [comment] 2024-04-03 15:52
I'd say no colors but I don't think this issue is about fallback icons anymore is it? That is being handled in a different issue. It seems like now we agree that the crux of this issue is just making sure the user knows the attachment is corrupt and they need to choose a different one.

**Comment by jsdev2547** [comment] 2024-04-03 16:32
@shawnborton Thanks. 

> Prevent from using corrupted images for Scan requests;

@paultsimura I have [proposal](https://github.com/Expensify/App/issues/37435#issuecomment-2033328935) for handling corrupted images for scan requests. The fallback thumbnails are to be handled in different issue.

**Comment by dubielzyk-expensify** [comment] 2024-04-04 02:42
This is great. Definitely like the modal as an error and I also prefer no color codes.

**Comment by jsdev2547** [comment] 2024-04-04 13:42
> Also, it doesn't fix the issue on native platforms

@paultsimura @shawnborton I understood the current issue is only to prevent the user from uploading corrupted attachment and not resolve any other issues. Please elaborate which other issue is supposed to be addressed in the current issue.

**Comment by shawnborton** [comment] 2024-04-04 13:46
> and not resolve any other issues

What other issues are you referring to?

**Comment by jsdev2547** [comment] 2024-04-04 13:47
@shawnborton I am also trying to find out which other issue @paultsimura is referring to.

**Comment by dannymcclain** [comment] 2024-04-04 13:47
>I saw your suggestion for the copy:
>However, we already have a copy for the corrupted attachment modal (not sure how to trigger the current one though). Would you be ok with it, or should we alter the copy?

If we already have something let's absolutely stick with what's already there!

**Comment by jsdev2547** [comment] 2024-04-04 13:50
@paultsimura RNImage.getSize should not be used on android native. The android native uses expo-image library and the RNImage is used for react web component.

**Comment by jsdev2547** [comment] 2024-04-04 13:51
@paultsimura The concerned members need to tagged and @shawnborton explained in the https://github.com/Expensify/App/issues/37435#issuecomment-2034986390 that the only issue to be addressed was to prevent the user from uploading corrupt image.

**Comment by jsdev2547** [comment] 2024-04-04 14:30
@paultsimura The ImageSize.getsize would only be for android native and not the web. Please check. The expo-image for android exposes prefetch and the react image component for web also has prefetch. I was also first to use the centered error model which fits with the requirements.

**Comment by jsdev2547** [comment] 2024-04-04 14:49
@paultsimura The proposal for getSize is incomplete the pseudo-code " /// Block users and show message." is already done in the validateReceipt function call of validateReceipt. I have provide much more complete solution and does not leave any room for pseudo-code expanding to lot more extra effort.

**Comment by jsdev2547** [comment] 2024-04-04 14:52
@paultsimura please do point out the overhead, the state variable for isAttachmentInvalid can be utilized but the error message handling is already done in the IOURequestStepScan validateReceipt function call doing the validation in attachment picker would actually adding extra overhead. Please review final time.

**Comment by jsdev2547** [comment] 2024-04-04 15:33
@paultsimura Please review, something is not correct with the implementation of ImageSize.getsize as suggested in the accepted proposal.

According to AvatarCropModel.tsx
https://github.com/Expensify/App/blob/8300ae40dd1f882167162fa7c86d0f5152000a87/src/components/AvatarCropModal/AvatarCropModal.tsx#L122

The ImageSize.getSize the success callback is handled in then()
```
   ImageSize.getSize(imageUri).then(({width, height}) => {
            // We need to have image sizes in shared values to properly calculate position/size/animation
            originalImageHeight.value = height;
            originalImageWidth.value = width;
            setIsImageInitialized(true);

            // Because the reanimated library has some internal optimizations,
            // sometimes when the modal is hidden styles of the image and slider might not be updated.
            // To trigger the update we need to slightly change the following values:
            translateSlider.value += 0.01;
            rotation.value += 360;
        });
```
but the accepted proposal has suggested without using then.
```
ImageSize.getSize(
   fileData.fileCopyUri || fileData.uri,
   (width, height) => {
       fileData.width = width;
       fileData.height = height;
       return validateAndCompleteAttachmentSelection(fileData);
   },
   (error) => {
       if (error.message === 'unknown image format') {
           showImageCorruptionAlert();
       } else {
           showGeneralAlert();
       }
   },
);
```

I tried using ImageSize.getSize without 'then' and the method is not returning success or fail callback

```
    ImageSize.getSize(file.uri, function (width, height) {
        setFile(file);
        isAttachmentInvalid(true);
      }, function (error) {
        setUploadReceiptError(true, 'attachmentPicker.errorLoadingAttachment', 'attachmentPicker.invalidAttachment');
        isAttachmentInvalid(false);
      });
```
Ideally the call to getSize should have returned success for valid image and failed for corrupt image.

Also please reconsider the accepted proposal. The react-native-image-size designed only for (ios+android) according to npm package. Even if the avatarcropmodel is using react-native-image-size in the web, does not mean the approach is correct.
I suggest to go with prefetch because the android + ios is using expo-image and the web is using react image component and both have prefetch method.

**Comment by jsdev2547** [comment] 2024-04-04 16:00
@paultsimura besides the concern of ios+android, I am finding difficulty using ImageSize.getsize to actually catch corrupt images. The AvatarCropModal is only passing valid images to ImageSize.getSize, the invalid or corrupt images are caught in the call to getImageResolution.

**Comment by jsdev2547** [comment] 2024-04-04 16:09
> @jsdev2547 Did you try using `.catch`?
> 
> ```js
> ImageSize.getSize(file.uri)
>             .then(({width, height}) => {
>                 ...
>             })
>             .catch(() => {
>                 setUploadReceiptError(true, 'attachmentPicker.attachmentError', 'attachmentPicker.errorWhileSelectingCorruptedImage');
>             });
> ```

@paultsimura I literally pasted the code block and for valid files, the getsize returns success but then also calls the catch block. Try uploading corrupt image in profile avatar and notice the console error, the ImageSize.getsize atleast for the web currently is only used for valid images and not corrupt.

**Comment by jsdev2547** [comment] 2024-04-04 16:27
@paultsimura I do not mean to cause delay but the ImageSize.GetSize seems to lack catch and also is designed for ios+android. Also considering the AvatarCropModal.tsx is only getting valid images, the corrupt images are getting handledin call to getImageResolution. I urge to reconsider and use prefetch api for web and android+ios(expo-image).

**Comment by jsdev2547** [comment] 2024-04-04 16:30
@paultsimura The internal engineers can also make suggestions on proposals if needed so as final call, no harm in getting final go ahead from the internal engineer.

**Comment by greg-schroeder** [comment] 2024-04-05 21:33
Agree with the above statement by @paultsimura - I think we should go with his choice and have @arosiclair validate that choice and then just proceed getting this fixed.

**Comment by greg-schroeder** [comment] 2024-04-15 02:44
Hold removed, moved back to `Daily`

**Comment by greg-schroeder** [comment] 2024-05-09 05:13
Hmm. Sorry, the automation seems to have failed this one. We generally search for payments by issue title + label. I'll get this taken care of now.

**Comment by greg-schroeder** [comment] 2024-05-09 05:15
Done, apologies.

**Closed by greg-schroeder** 2024-05-09 05:15 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
