### ISSUE TITLE
[$250] Scan Receipt - Scan of receipt in pdf does not finish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41819] opened 2024-05-08 00:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/21004&group_by=cases:section_id&group_id=294998&group_order=asc
**Email or phone of affected tester (no customers):** applausetester+az2070524@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Select the option to Submit expense and Scan receipt
2. Select the option to upload a receipt
3. Upload a PDF receipt file
4. Verify a preview of the file is displayed in the final review page
5. Click on Submit expense
6. Wait to finish the scan

## Expected Result:
Receipt ends scanning and displays value and Merchant data

## Actual Result:
Receipt does not finish scanning for more than two hours and continues to present message "in progress"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6474133_1715107140606!bug_scanning](https://github.com/Expensify/App/assets/78819774/3a8c73d4-cb2a-48bb-b720-7a6745935bf0)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d46c70d4cfe8580a</li>
        <li>Upwork Job ID: 1790583629216169984</li>
        <li>Last Price Increase: 2024-05-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by lanitochka17** [comment] 2024-05-08 00:20
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment] 2024-05-15 03:22
Hmm, not sure what's going on here. I'll add the external label to get some thoughts from the community.

**Comment by jscoder2151** [comment] 2024-05-16 16:18
Contributor details
Your Expensify account email: jscoder126@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by jscoder2151** [comment] 2024-05-16 16:18
Contributor details
Your Expensify account email: jscoder126@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by jscoder2151** [comment] 2024-05-16 16:49
Contributor details
Your Expensify account email: jscoder126@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by jscoder21321** [comment] 2024-05-16 16:51
Contributor details
Your Expensify account email: jscoder21321@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by jscoder21321** [comment] 2024-05-16 17:27
Contributor details
Your Expensify account email: jscoder21321@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by jscoder21321** [comment] 2024-05-16 17:27
Contributor details
Your Expensify account email: jscoder21321@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by mvtglobally** [comment] 2024-05-22 04:42
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2024-05-29 22:51
Closing since we can't reproduce.

**Closed by JmillsExpensify** 2024-05-29 22:51 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
