### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] Room - In offline, changing room name, in room chat changed message is not displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34364] opened 2024-01-11 14:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Turn off mobile data
3. Tap fab--- Start chat --- Room
4. Enter all fields
5. Tap create room
6. Tap header
7. Tap settings
8. Tao room name
9. Change room name
10. Tap save
11. Navite back to room chat page

## Expected Result:
In offline, changing room name, in room chat changed message must be displayed

## Actual Result:
In offline, changing room name, in room chat changed message is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7870616e-de53-4fd6-b270-e25a193688ee

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc0589030a9cc719</li>
        <li>Upwork Job ID: 1745458564459560960</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28142459</li>
<li>paultsimura | Contributor | 28142460</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-01-11 15:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In offline, changing room name, in room chat changed message is not displayed

### What is the root cause of that problem?
We are only setting the update of the room name in optimistic data
https://github.com/Expensify/App/blob/55746c78a6ef59d9ad636eda8c610023c3cd62ac/src/libs/actions/Report.ts#L1719-L1733
### What changes do you think we should make in order to solve the problem?

We should also add the changed name message in optimistic data
### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-11 15:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
When renaming a room, we do not add an optimistic `RENAME` report action to the room report, only update the report name:

https://github.com/Expensify/App/blob/c0c4d64f67d263472a713f5c1aa4b0ec8b0080f9/src/libs/actions/Report.ts#L1706-L1764

### What changes do you think we should make in order to solve the problem?
**First**, we should build an optimistic report action with type="RENAME" and add it to the `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}` onyx key in the optimisticData (the report action should be build to match the one we receive from BE, it's a rather trivial task):

```js
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`,
            value: {
                [optimisticRenamedAction.reportActionID]: optimisticRenamedAction,
            },
        },
```

**Second**, equally important: we should also remove this optimistic action on API call success or failure. This is needed to avoid duplicates when the BE response comes and adds another `RENAMED` action with a different ID:

```js
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`,
            value: {
                [optimisticRenamedAction.reportActionID]: null,
            },
        },
```

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-11 15:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
When renaming a room, we do not add an optimistic `RENAME` report action to the room report, only update the report name:

https://github.com/Expensify/App/blob/c0c4d64f67d263472a713f5c1aa4b0ec8b0080f9/src/libs/actions/Report.ts#L1706-L1764

### What changes do you think we should make in order to solve the problem?
**First**, we should build an optimistic report action with type="RENAME" and add it to the `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}` onyx key in the optimisticData (the report action should be build to match the one we receive from BE, it's a rather trivial task):

```js
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`,
            value: {
                [optimisticRenamedAction.reportActionID]: optimisticRenamedAction,
            },
        },
```

**Second**, equally important: we should modify the `UpdatePolicyRoomName` API route to accept the `renamedActionID` parameter, so it will be used as the ID of the action received from BE.

We do similar with the task updates:

https://github.com/Expensify/App/blob/382a09642aab4580bd14955d828544d892ac1188/src/libs/actions/Task.js#L434-L443

This is needed to avoid duplicates when the BE response comes and adds another `RENAMED` action with a different ID.

### What alternative solutions did you explore? (Optional)
To avoid BE changes, we could also remove this optimistic action on API call success or failure:

```js
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`,
            value: {
                [optimisticRenamedAction.reportActionID]: null,
            },
        },
```

**Comment by FitseTLT** [comment] 2024-01-11 16:30
[Updated](https://github.com/Expensify/App/issues/34364#issuecomment-1887365384) to add detailed implementation

**Comment by jjcoffee** [comment] 2024-01-16 12:41
After an in-depth analysis of timestamps ( :sweat_smile: ), I think we can go with @tienifr's [proposal](https://github.com/Expensify/App/issues/34364#issuecomment-1887396696). All three proposals are similar, but @tienifr got the most fully fleshed out proposal first, including an important detail of needing to translate the message text.

I do appreciate @paultsimura's proposal _also_ included an extra detail to avoid duplicate report actions that @tienifr later included, but IMO it would've been handled in the PR anyway.

I'm not sure how long it would take to add BE support for an extra `renamedActionID` parameter, but if we agree to go down that route we should probably HOLD this issue until the BE changes are made.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by neil-marcellini** [comment] 2024-01-22 21:47
> @neil-marcellini looks like you implemented this 5 months ago, can you check please? The proposal sounds reasonable to me, and I do think we should update the backend, as well as do this:
> 
> > Because buildOptimisticRenamedReportAction is quite same as buildOptimisticCreatedReportAction, we can consider to generic this function to support renamed action.

The proposal sounds good to me. I'm not sure what part I implemented 5 months ago. Let me know via DM if you need anything else from me.

**Comment by anmurali** [comment] 2024-01-22 23:04
Not overdue. @flodnv and @neil-marcellini are working through what needs to change.

**Comment by anmurali** [comment] 2024-01-25 18:39
@jjcoffee - based on https://github.com/Expensify/App/issues/34364#issuecomment-1893664724 - do you want to hire @tienifr for this job?

**Comment by jjcoffee** [comment] 2024-01-26 09:35
@anmurali Yes, still happy to go with @tienifr's proposal!

**Comment by jjcoffee** [comment] 2024-02-02 14:31
Maybe if I do this again an engineer will get assigned? See my original review [here](https://github.com/Expensify/App/issues/34364#issuecomment-1893664724).

🎀👀🎀 C+ reviewed

**Comment by MonilBhavsar** [comment] 2024-02-05 11:45
I do like the idea of passing optimistic reportActionID to server. 

> I do appreciate @paultsimura's proposal also included an extra detail to avoid duplicate report actions that @tienifr later included, but IMO it would've been handled in the PR anyway.


@jjcoffee this is not correct no? Once we would have moved to App PR we would have only implemented client side change?
If @paultsimura made a complete proposal first that mentioned about server side change, then I think we should assign them to the issue

**Comment by MonilBhavsar** [comment] 2024-02-05 12:36
Thanks @tienifr and everyone for the proposals. As @paultsimura posted complete proposal first mentioning backend fix. We would like to assign them to this issue.

**Comment by MonilBhavsar** [comment] 2024-02-05 12:37
I'll handle the backend fix and update here. Meanwhile feel free to open a PR

**Comment by MonilBhavsar** [comment] 2024-02-05 13:04
I have started implementing server side change that accepts `renamedRoomReportActionID` parameter. I would like to test it with App PR once before getting it ready.

**Comment by paultsimura** [comment] 2024-02-05 13:39
> I would like to test it with App PR once before getting it ready.

Great, the draft PR will be ready today. I'll tag you in it @MonilBhavsar

**Comment by paultsimura** [comment] 2024-02-07 21:00
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/35826

**Comment by jjcoffee** [comment] 2024-02-08 15:55
Thanks, will review tomorrow!

**Comment by anmurali** [comment] 2024-02-16 15:41
Due in 4 days to be paid but I am OOO so I am reassigning. @jjcoffee meanwhile, if applicable, can you add regression tests and complete the BZ checklist?

**Comment by strepanier03** [comment] 2024-02-20 17:52
Reg test created, everyone paid, closing out. 

Thanks again @jjcoffee and @paultsimura for your help getting this one finished up 🙌

**Closed by strepanier03** 2024-02-20 17:52 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
