### ISSUE TITLE
[Paid] [$250] Selecting yourself as the assignee should default Share somewhere to your self-DM

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46918] opened 2024-08-06 19:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @srikarparsi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722970867440899

## Action Performed:

1. Click FAB
2. Click Assign Task
3. Enter in a title and click next
4. Select yourself as the assignee

## Expected Result:
Your self DM should be selected under Share somewhere
## Actual Result:
Nothing happens to  Share somewhere
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6b9a5fb3-f7c8-46ee-abee-005fa267c738

![image (10)](https://github.com/user-attachments/assets/6ef16f26-d643-4449-aad7-46a7318fec3c)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee964f440e728109</li>
        <li>Upwork Job ID: 1820902098430288377</li>
        <li>Last Price Increase: 2024-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103489021</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by nkdengineer** [comment] 2024-08-06 19:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Nothing happens to  Share somewhere

### What is the root cause of that problem?

We only set the share destination if the selection assignee is not the current user here.


https://github.com/Expensify/App/blob/fb0043ad97b023b7eb7ad7f57f91711d47213f3f/src/libs/actions/Task.ts#L777
https://github.com/Expensify/App/blob/fb0043ad97b023b7eb7ad7f57f91711d47213f3f/src/libs/actions/Task.ts#L798


### What changes do you think we should make in order to solve the problem?
If the selected assignee is the current user, we should add the share somewhere as the self-chat. We can add a else condition for this case like this. 

OPTIONAL: We can also call `setAssigneeChatReport` inside the case the current user is the assignee. If we want to do that, we can move the logic set assign chat report and share somewhere to outside the if condition [here](https://github.com/Expensify/App/blob/fb0043ad97b023b7eb7ad7f57f91711d47213f3f/src/libs/actions/Task.ts#L777) and add a else condition to assign the `report` as the selfDM.

```
else {
    const selfDMReportID = ReportUtils.findSelfDMReportID();
    // If there is no share destination set, automatically set it to the assignee chat report
    // This allows for a much quicker process when creating a new task and is likely the desired share destination most times
    if (!shareToReportID && !skipShareDestination) {
        setShareDestinationValue(selfDMReportID ?? '-1');
    }
}
```
https://github.com/Expensify/App/blob/fb0043ad97b023b7eb7ad7f57f91711d47213f3f/src/libs/actions/Task.ts#L777

### What alternative solutions did you explore? (Optional)

**Comment by kpadmanabhan** [comment] 2024-08-06 20:45
I was trying to reproduce the issue. However it works as expected as in test steps in staging.new.expensify.com
@m-natarajan : am i missing any steps? isnt this what the expected behaviour is?

https://github.com/user-attachments/assets/8a910f06-a54d-4c88-9275-deb8f553057d

**Comment by srikarparsi** [comment] 2024-08-08 06:18
Hi @kpadmanabhan, the expected behavior is if you select yourself in the Assignee field, then your self DM should automatically populate in the Share somewhere field.

**Comment by srikarparsi** [comment] 2024-08-08 06:18
@Pujan92 have you had a chance to review proposals?

**Comment by Pujan92** [comment] 2024-08-08 17:43
@Krishna2323's RCA is incorrect, we aren't passing `skipShareDestination` in the function call. 

@nkdengineer's RCA and [solution](https://github.com/Expensify/App/issues/46918#issuecomment-2271996646) looks good to me where they suggested to use else condition for the isCurrentUser part.

🎀👀🎀 C+ reviewed

**Comment by alexpensify** [comment] 2024-08-13 04:31
Easy Melvin, the PR is being worked on.

**Comment by nkdengineer** [comment] 2024-08-13 09:46
@Pujan92 this [PR](https://github.com/Expensify/App/pull/47291) is ready for review

**Comment by alexpensify** [comment] 2024-08-22 13:15
This was merged 3 days ago, so waiting for automation to kick in here.

**Comment by alexpensify** [comment] 2024-08-26 15:32
## Next Steps

@OfstadC, it looks like automation hasn't kicked in here, and I'm not sure if it will. If automation fails, then the payment date will be tomorrow. Here's the summary: 

Payouts due: 2024-08-27

- [ ] Contributor: $250 @nkdengineer https://www.upwork.com/ab/applicants/1820902098430288377/hired
- [ ] Contributor+: $250 @Pujan92 handled via Chat 

Upwork job is [here](https://www.upwork.com/ab/applicants/1820902098430288377/hired).

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by OfstadC** [comment] 2024-08-27 18:10
## Payment Summary

- @nkdengineer paid $250 via Upwork
- @Pujan92 due $250 via manual New Expensify request

**Comment by OfstadC** [comment] 2024-08-27 18:10
@Pujan92 any regression testing to propose here?

**Comment by Pujan92** [comment] 2024-08-27 19:40
### Regression Test Steps

1. Click FAB -> Assign Task
2. Provide a title and click next
3. Select yourself as the assignee
4. Verify that your self-DM should be selected in Share somewhere

**Comment by OfstadC** [comment] 2024-08-27 20:00
Thanks @Pujan92 

https://github.com/Expensify/Expensify/issues/423739

**Closed by OfstadC** 2024-08-27 20:00 UTC
Labels: Reviewing, External, Daily, Bug
