### ISSUE TITLE
[$250] Tabbing to number pad and pressing enter in Send Money screen submits the form reported by @huzaifa-99

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12431] opened 2022-11-03 15:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click the 'New' button
2. Select 'Send money'
3. Press tab to focus to first number and enter to select (works correctly and the focus stays at the first number)
4. Press enter again while focus is on the first number
5. The form gets submitted and the user is redirected to next step

## Expected Result:
Repeated enter key presses should work on the number pad when focused via tab

## Actual Result:
Only the first enter key press works on number pad when focused via tab

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web **(touch screen)**

**Version Number:** 1.2.21-4
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/199765272-d2055848-09b9-402d-96b0-f46bb0b98edd.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667174885945259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by huzaifa-99** [comment] 2022-11-07 11:05
If it helps for reproduction in non-touch screens.

Changing `canUseTouchScreen()` to `true` in 
https://github.com/Expensify/App/blob/0724337138a4d80f6603074cc9af5c186cb524ec/src/pages/iou/steps/IOUAmountPage.js#L274-L280

would show the big number pad that is having issues on touch screens.

**Comment by arielgreen** [comment] 2022-11-09 20:27
https://www.upwork.com/jobs/~01b26e7b27740b8448

**Comment by alexandermendes** [comment] 2022-11-09 21:41
# Proposal

The issue is that the `Button` below uses the `pressOnEnter` prop, which calls the `onPress` callback when the enter key is pressed. The reason it doesn't fire the first time is because the button is disabled until an amount has been entered.

https://github.com/Expensify/App/blob/ed864876a097a9cfd382330ac99d3c2b1b88dae1/src/pages/iou/steps/IOUAmountPage.js#L282-L289

The issue can also be replicated by entering a number without tabbing, then tabbing any number and hitting enter.

One way to solve this would be to add a hook to listen for tab key presses and, if we detect that the user is using the keyboard, disable the `pressOnEnter` behaviour. 

I have used a hook like this in the past:

```js
export const useWasKeyboardTabPressed = () => {
  const [wasTabPressed, setWasTabPressed] = useState(false);

  useEffect(() => {
    const checkForTabPress = (evt) => {
      const isTab = evt.key === 'Tab' || evt.keyCode === 9;

      if (isTab) {
        setWasTabPressed(true);

        window.removeEventListener('keydown', checkForTabPress);
      }
    };

    window.addEventListener('keydown', checkForTabPress);

    return () => {
      window.removeEventListener('keydown', checkForTabPress);
    };
  }, []);

  return wasTabPressed;
};
```

And then in the `IOUAmountPage` something like:

```js
const wasKeyboardTabPressed = useWasKeyboardTabPressed();

// ...

<Button
  pressOnEnter={!wasKeyboardTabPressed}
  // ...
/>
```

**Comment by Pujan92** [comment] 2022-11-10 18:15
### **Proposal**

We can use prop `onSubmitEditing` on `TextInput` to determine whether enter is pressed from the text input or not, in the case when it is pressed when the user is focused within the text input we can take the button ref and execute `onPress` of it.

In the `BaseTextInput.js` file, we can add prop assignment and with the prop chain we can get notify in the caller component.
`onSubmitEditing={this.props.onSubmitEditing}`

**Comment by Santhosh-Sellavel** [comment] 2022-11-11 00:50
@arielgreen I can't get to this sooner, so unassigning! Please other C+, thanks!

**Comment by thesahindia** [comment] 2022-11-11 14:06
Thanks for the proposals everyone but I don't think we are focusing on accessibility right now. I will start a discussion on this.

**Comment by alexandermendes** [comment] 2022-11-11 14:26
Fair enough, although if that does end up being the case it might be worth questioning why the issue was created 8 days ago and the external label added 2 days ago. Takes up people's time obviously to dig in and come up with solutions, might indicate a tweak in processes being needed!

**Comment by thesahindia** [comment] 2022-11-11 20:24
@arielgreen, I think we can close this issue. I have started the discussion [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1668177379952499?thread_ts=1668177379.952499&cid=C02NK2DQWUX)

**Closed** 2022-11-14 23:11 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
