### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] Composer defocuses when editing parent message in thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38878] opened 2024-03-23 14:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/37566
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to any chat.
3. Send a message containing inline image markdown. Example:
An inline image and some text ![off](https://images.unsplash.com/photo-1709983723739-d72ea88434dd?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)
4. Right click on the message > Edit comment.
5. Focus the cursor anywhere in the editor.
6. Note that the composer will not defocus.
7. Right click on the message > Reply in thread.
8. Right click on the parent message > Edit comment.
9. Focus the cursor anywhere in the editor.

## Expected Result:
The composer will not defocus.

## Actual Result:
The composer defocuses when editing message with inline image mark down in thread.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0fcd8066-c7e0-4bc0-aff4-17488bfd31b3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012dd2062cbe841507</li>
        <li>Upwork Job ID: 1772340169085984768</li>
        <li>Last Price Increase: 2024-03-25</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-23 14:37
We think that this bug might be related to #vip-bills

**Comment by amyevans** [comment] 2024-03-25 15:26
This is related to a new feature and also pretty minor so not worth considering a blocker.

@kidroca do you have bandwidth to take this on and fix as polish? If not I can open it up to external proposals. cc @situchan @marcaaron

**Comment by amyevans** [comment] 2024-03-25 15:45
Hmm actually I'm going to walk back my comment that it's related to the Image Markdown PR, I think it was just incidental that it was discovered during QA there. I can reproduce the bug on `main` with that PR reverted, and I can also reproduce on a comment that does not include image markdown.

Will continue to investigate...

**Comment by situchan** [comment] 2024-03-25 15:47
Agree, I am not convinced why composer focus behavior is related to image MD.

**Comment by bernhardoj** [comment] 2024-03-26 04:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The edit composer of a parent thread message lose focuses when clicking on it.

### What is the root cause of that problem?
For the parent thread message, we set an on-press event that will navigate the user to the thread report.
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionItemParentAction.tsx#L85-L86

In the video, the thread is 1 level deep, so pressing it will navigate to itself, so the composer loses the focus.

### What changes do you think we should make in order to solve the problem?

Don't trigger the on-press when the message is in draft mode.
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionItem.tsx#L798-L800

```
onPress={!draftMessage ? onPress : undefined}
```

**Comment by bernhardoj** [comment] 2024-03-26 06:25
It's related to the comment linking PR. The navigation triggers this memo to recalculate the ID which is passed to the chat list `FlatList` key, so the list re-renders every time a navigation happens.
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionsView.tsx#L135-L141

We still need to apply my fix, otherwise we can't edit a thread ancestor message.

https://github.com/Expensify/App/assets/50919443/5873b394-86ad-4fb2-9992-c8bd298430e9

**Comment by shahinyan11** [comment] 2024-03-26 07:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Image MD - Composer defocuses when editing message with inline image mark down in thread
### What is the root cause of that problem?
When we press anywhere in input, the event will bubble up the tree and call the `onPress` of the parent element [here](https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionItemParentAction.tsx#L86C34-L86C117) 
### What changes do you think we should make in order to solve the problem?
Add `onClick={(e)=>{e.stopPropagation()}}` to this [View](https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionItemMessageEdit.tsx#L377C13-L377C68)

### What alternative solutions did you explore? (Optional)
Replace this [View](https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionItemMessageEdit.tsx#L377C13-L377C68) with `PressableWithoutFeedback` component

**Comment by jjcoffee** [comment] 2024-03-26 10:14
Looks to be caused by the comment linking PR https://github.com/Expensify/App/pull/30269. @bernhardoj's [proposal](https://github.com/Expensify/App/issues/38878#issuecomment-2019341555) LGTM to get this fixed quickly!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by shahinyan11** [comment] 2024-03-26 10:25
@jjcoffee What about my proposal ?

**Comment by amyevans** [comment] 2024-03-26 15:31
> @amyevans I think this should block deployment here as it breaks crucial feature of editing messages.

The user isn't blocked from editing the comment. They can edit it from the original conversation - the bug only applies to the editing of the parent comment from within the thread. So while I definitely appreciate the urgency here and agree it's better to get a fix in sooner than later, I don't agree that it needs to block deployment given there's a workaround 😄

**Comment by amyevans** [comment] 2024-03-26 15:32
Proposal looks good @bernhardoj, thanks! Let us know when we can expect a PR

**Comment by amyevans** [comment] 2024-03-26 15:34
Also cc @perunt @roryabraham (nothing y'all need to do here, just a tag for visibility since this came from comment linking)

**Comment by bernhardoj** [comment] 2024-03-26 15:51
PR is ready

cc: @jjcoffee

**Comment by isabelastisser** [comment] 2024-04-09 20:46
@jjcoffee please complete the list above. Thanks!

**Comment by isabelastisser** [comment] 2024-04-09 20:49
The payments were processed in Upwork.

Waiting for @jjcoffee to completed the BZ list before this can be closed.

**Comment by jjcoffee** [comment] 2024-04-10 07:48
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30269
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30269#issuecomment-2046774297
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - big PR so regressions were inevitable!**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Send a message to any chat
2. Right-click and reply in thread to the message
3. Right-click and edit the thread parent message
4. Tap anywhere in the message
5. Verify that the focus on the composer isn't lost

Do we agree 👍 or 👎

**Comment by isabelastisser** [comment] 2024-04-10 13:26
Hi @amyevans, do you agree that we should create the regression test with the steps above? Thanks!

**Comment by amyevans** [comment] 2024-04-10 15:58
@isabelastisser I think since the bug was caught during normal regression testing by Applause, it means that adding an explicit test case for this would be unnecessary. However if you want to be safe you can always open a GH for it and let Isabella make that call!

**Comment by isabelastisser** [comment] 2024-04-10 16:57
Thanks for the context, Amy! I agree and will close it then.

**Closed by isabelastisser** 2024-04-10 16:57 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
