### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000] mWeb - Chat - 'Hmm... it's not here' page is displayed when we go back from concierge after we open invalid user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19996] opened 2023-06-01 19:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Go to search and search for any invalid phone or email
	An invalid phone number meaning a non-mobile phone line. (Landline)
3. Click on result
4. Close the error
5. On concierge page, click on back of phone or swipe back

## Expected Result:
App should not display its not here page after getting back from concierge after opening invalid user

## Actual Result:
App displays 'Hmm... it's not here' page when we get back from concierge after opening invalid user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/61f55905-ceec-4805-8a19-1ced747f39d3

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685645535899559?thread_ts=1685385849.445229&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148400a911dd6cf26</li>
        <li>Upwork Job ID: 1666097434807554048</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-06-05 16:08
I've asked in Slack for clarity about what qualifies as an invalid phone number/email address so we can update the repro steps.

**Comment by johncschuster** [comment] 2023-06-06 14:56
From Slack:

> I used landline numbers (eg: [+916541237890](tel:+916541237890)) as we can't start chat with them. Not sure landline number format in US though.

**Comment by ShogunFire** [comment] 2023-06-08 00:19
Is it just me that can't arrive on the error page ? This is what I have for mweb:

https://github.com/Expensify/App/assets/19537677/06dc51cb-4461-4177-ad30-aa91a5532aca

I also tried on prod and same result...

On Android native I have the error page

**Comment by dhanashree-sawant** [comment] 2023-06-08 16:00
Hi @parasharrajat, it should get us back to main report from which we clicked on 'Reply in thread' or generally when we go back from concierge, we go back to main home page i.e. reports archive page. Whatever seems right. From users perspective, if we already have closed the error and are taken to concierge page, I won't expect it to show 'Hmm... its not there' page. That would be confusing.

**Comment by bernhardoj** [comment] 2023-06-10 13:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we start a chat with an invalid user, it will show a create chat error and show a close button. The close button will delete the invalid chat and navigate to concierge chat. 
https://github.com/Expensify/App/blob/9f1c0e08eb40f5703d12c9a62770509c70f78dff/src/libs/actions/Report.js#L1267-L1270
When going back, it will show the deleted invalid chat.

### What is the root cause of that problem?
When we navigate to concierge chat, the deleted invalid chat is still in the stack ([LHN, Deleted Invalid Chat, Concierge]). So, when we go back, we will land on deleted invalid chat.

### What changes do you think we should make in order to solve the problem?

When we navigate to concierge, we should pop the deleted invalid chat from stack.
https://github.com/Expensify/App/blob/9f1c0e08eb40f5703d12c9a62770509c70f78dff/src/libs/actions/Report.js#L1267-L1270
(add Navigation.goBack() before navigateToConciergeChat)

### What alternative solutions did you explore? (Optional)
Add a way to replace the navigation instead of push. So, the deleted invalid chat will be replaced with concierge chat.
(I prefer the main solution as it's much simpler)

**Comment by johncschuster** [comment] 2023-06-14 14:49
@parasharrajat what do you think? Do you think the proposals here are sufficient?

**Comment by bernhardoj** [comment] 2023-06-21 04:22
Unfortunately, we can't do that.
https://github.com/Expensify/App/blob/342d4fd84f3dda933c44a71b9e4d666d26b270c9/src/libs/Navigation/linkTo.js#L27-L36

When we navigate to a different report screen even using 'UP' type, it will always enter the first if block.

**Comment by johncschuster** [comment] 2023-06-26 17:33
@parasharrajat what do you think about the response from @bernhardoj above?

**Comment by marcaaron** [comment] 2023-06-28 20:27
Noting that I got assigned to this, but I think @robertjchen is the CME here so the assignment feels like a glitch to me. That said, if we need some assistance here I am happy to review this proposal - please just let me know.

**Comment by robertjchen** [comment] 2023-06-30 06:37
Reviewing this now 👀

**Comment by robertjchen** [comment] 2023-06-30 17:24
Thanks for the discussion! Since it looks like we're doing the replace manually elsewhere, it is also an acceptable approach here as well. Let's move forward with @bernhardoj 's proposal 👍

**Comment by johncschuster** [comment] 2023-07-05 15:29
Waiting on the deploy to prod 👍

**Comment by robertjchen** [comment] 2023-07-17 03:54
I believe we're waiting on the BZ checklist for this one? https://github.com/Expensify/App/issues/19996#issuecomment-1622149044

**Comment by johncschuster** [comment] 2023-07-19 19:29
The job has been closed on Upwork. I'll get a new one going.

**Comment by robertjchen** [comment] 2023-07-24 11:58
@johncschuster Got it, should we close this one out then?

**Comment by johncschuster** [comment] 2023-07-24 18:27
I'm having trouble with Upwork (no surprises there) with creating the new job. I'm going to keep this issue open while I work on that so I don't miss paying everyone.

**Comment by johncschuster** [comment] 2023-07-26 21:20
@dhanashree-sawant and @bernhardoj I have sent contracts to both of you. Can you please comment here when you've accepted so I can issue payment? Thank you!

**Comment by dhanashree-sawant** [comment] 2023-07-27 02:07
Thanks @johncschuster, Offer accepted.

**Comment by JmillsExpensify** [comment] 2023-07-27 05:10
Reviewed details for @parasharrajat. This is accurate based on summary from the thumbs up from the Business Reviewer and approved for payment in NewDot.

**Comment by johncschuster** [comment] 2023-07-27 11:01
### Summary of payment:
External issue reporter - @dhanashree-sawant - $250
Contributor that fixed the issue - @bernhardoj - $1500
Contributor+ that helped on the issue and/or PR - @parasharrajat - $1500

**Comment by johncschuster** [comment] 2023-07-30 17:40
@JmillsExpensify, I've issued payment on Upwork for @dhanashree-sawant and @bernhardoj and it looks like payment should be issued to @parasharrajat via NewDot. Do we need to keep this issue open until that payment is issued or are we good to close this out?

**Comment by JmillsExpensify** [comment] 2023-08-01 05:49
You can close it. I've approved payments.

**Comment by johncschuster** [comment] 2023-08-01 23:33
Sweet! Thank you!

**Closed** 2023-08-01 23:33 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
