### ISSUE TITLE
[HOLD PR #39343][$250] Thread-Cursor is hand cursor instead of text cursor when hovering over edit composer in thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39301] opened 2024-03-29 21:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Send a message in chat.
3. Right click on the message > Reply in thread.
4. Right click on the parent message in thread > Edit comment.
5. Hover over the text in the edit composer.

## Expected Result:
The cursor should be text cursor when hovering over edit composer in thread (production behavior).

## Actual Result:
The cursor is a hand cursor when hovering over edit composer in thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8c7e5b62-1322-471e-96f8-1b941f5f8a5d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae2c268d361e853b</li>
        <li>Upwork Job ID: 1774503212793540608</li>
        <li>Last Price Increase: 2024-03-31</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-29 21:56
@mallenexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-29 21:56
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-03-29 21:57
Production 


https://github.com/Expensify/App/assets/115492554/bd0dfa7c-7202-496c-9701-d51977996348

**Comment by thienlnam** [comment] 2024-03-29 22:46
Not a blocker - added it to the main tracking issue https://github.com/Expensify/App/issues/36071

**Comment by ahmedGaber93** [comment] 2024-03-30 03:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread-Cursor is hand cursor instead of text cursor when hovering over edit composer in thread
### What is the root cause of that problem?
This issue related with PR #38722
[here](https://github.com/Expensify/App/pull/38722/files#diff-f0bdc7ab41060e24e6bcdc847f25185b372c5f9a072251fe5d3cae2a27887920) we added new parameter `isClickable = !!onPress` to  `getReportActionItemStyle` to add style `styles.cursorPointer` when hover.
The issue here is we not exclude edit message case.

### What changes do you think we should make in order to solve the problem?
We need to exclude edit message case from when we pass `isClickable` [here](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/pages/home/report/ReportActionItem.tsx#L863) to be 
```javascript
// !!onPress
draftMessage === undefined && !!onPress
``` 

### What alternative solutions did you explore? (Optional)

**Comment by ahmedGaber93** [comment] 2024-03-30 03:55
@thienlnam this issue not related with Live Markdown, as I described in my [proposal](https://github.com/Expensify/App/issues/39301#issuecomment-2027900623) root cause.

**Comment by mallenexpensify** [comment] 2024-03-31 18:26
Pretty sure this can be External. Set price at $250 and added to #vip-vsb because the bug doesn't involve money.

@thienlnam let me know if anything above needs updating. 
@hungvu193 , do you think this can be External? If so, can you review the proposal above? thx

**Comment by TafreedAhmad** [comment] 2024-03-31 21:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When trying to edit the parent thread, the cursor is a hand and not a pointer as it should be while editing.

### What is the root cause of that problem?

The root cause is the `isclickable` parameter which is set to `!!onPress`.

### What changes do you think we should make in order to solve the problem?

We should change the parameters it receives so that we can get our pointer cursor while hovering it.

### What alternative solutions did you explore? (Optional)

I made it work on my local machine using different parameters there.

**Comment by hungvu193** [comment] 2024-04-01 02:51
@mallenexpensify Feel like this [PR](https://github.com/Expensify/App/pull/39343) will fix this issue as well.
I think we can put it on hold.

**Comment by mallenexpensify** [comment] 2024-04-03 00:07
Thanks @hungvu193 , I put this on hold and removed `External` and `Help Wanted`

**Comment by hungvu193** [comment] 2024-05-21 07:46
The linked PR is merged, I think we can close this one 😄

**Comment by mallenexpensify** [comment] 2024-05-22 01:07
Thanks @hungvu193 , we should be all good, closing
<img width="227" alt="image" src="https://github.com/Expensify/App/assets/22508304/7bf6746c-16ac-4e24-9079-6d27c5bd83df">

**Closed by mallenexpensify** 2024-05-22 01:07 UTC
Labels: Reviewing, Engineering, Monthly, Bug
