### ISSUE TITLE
[$500] mWeb - Settings - Transitions not smooth in settings navigation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33628] opened 2023-12-26 21:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32267

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Go to Settings
3. Navigate to some pages

## Expected Result:
Transaction should be smooth 

## Actual Result:
Transitions not smooth in settings navigation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c04c4e62-7657-4d23-8036-055aab993a7b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d4616de7bef61fc</li>
        <li>Upwork Job ID: 1739766508742758400</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-12-29 17:16
Couple of proposals ready for review @thesahindia

**Comment by bfitzexpensify** [comment] 2024-01-01 21:23
Likewise - things are fine when I've tried to reproduce. Let's close this out

**Comment by kbecciv** [comment] 2024-01-09 14:29
Issue is reproducible on Android/Chrome, build 1.4.23.0

https://github.com/Expensify/App/assets/93399543/9fed9a16-9c90-4e7d-8248-8dc2e72e3b79

**Comment by bfitzexpensify** [comment] 2024-01-11 17:22
I still wasn't able to reproduce this on either 1.4.23.0 or 1.4.24.0:


https://github.com/Expensify/App/assets/38236554/04b82b9c-c536-4e40-a5f6-52315b623fab

@kbecciv is it happening on the latest build? 

I'm going to be mostly ooo until Jan 29, assigning a second BZ team member to keep an eye on this.
- this is recently reopened after being closed as non-reproducible, still figuring out if this is an issue we need to address

**Comment by kbecciv** [comment] 2024-01-12 22:34
Issue is reproducible in Android mWeb version 1.4.24-7.

https://github.com/Expensify/App/assets/93399543/5e626184-e3e9-4247-8d9a-b4984b99f3c1

**Comment by bfitzexpensify** [comment] 2024-01-17 22:54
Hm, looks like my label adding didn't work last week. Re-adding a second BZ team member from my comment in https://github.com/Expensify/App/issues/33628#issuecomment-1887620203.

**Comment by bfitzexpensify** [comment] 2024-01-18 23:35
@CortneyOfstad and @thesahindia - are either of you able to reproduce this?

**Comment by CortneyOfstad** [comment] 2024-01-22 14:37
Sorry for the delay here – no, I am unable to reproduce. @thesahindia are you able to?

**Comment by CortneyOfstad** [comment] 2024-01-22 17:21
Okay, let's close this 👍

**Closed by CortneyOfstad** 2024-01-22 17:21 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
