### ISSUE TITLE
Can still receive incoming messages while offline via the Network tab on chrome reported by @grgia 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11783] opened 2022-10-12 22:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195461868-911ef319-783f-4f5a-906f-91eb5921b477.mov

https://user-images.githubusercontent.com/43996225/195461876-b66c2bdc-508e-438b-adc1-924b1e31b4f1.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @grgia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665593954083459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2022-10-13 11:18
I'm seeing the same issue, and I feel like it used to work correctly 😕 The profile icon is turning grey, so some component seems to be correctly noticing the network change:

<img width="1116" alt="Screenshot 2022-10-13 at 12 05 22" src="https://user-images.githubusercontent.com/10736861/195582028-c1459834-2b4a-4d93-91d9-ffc67b072e5e.png">

Additionally, I have the same issue when disconnecting my WiFi. Does anyone else see this, or just me? 😭

**Comment by grgia** [comment] 2022-10-13 16:30
I'm also seeing that isOffline is not updating correctly and that the offline indicator/messages greyed out are still reacting to network change

**Comment by amyevans** [comment] 2022-10-13 21:58
Hmm I'm not able to reproduce 🤔
![Screen Shot 2022-10-13 at 5 56 47 PM](https://user-images.githubusercontent.com/7277067/195718445-6b7c95ad-9611-4858-b5e0-8255b73d4cd4.png)

**Comment by amyevans** [comment] 2022-10-13 22:00
Going to unassign myself for now to stay focused on some other tasks, but feel free to ping me to take another stab at reproduction if something changes!

**Comment by grgia** [comment] 2022-10-13 22:40
I found that it will update the first time, but trying to toggle back on or back off doesn't reliably update the network boolean

**Comment by amyevans** [comment] 2022-10-14 15:52
Toggling back and forth and still working okay for me:

https://user-images.githubusercontent.com/7277067/195888631-e1406471-a5c4-4964-9a22-deb8423f6689.mov

Maybe chrome version? I'm on `Version 106.0.5249.119 (Official Build) (arm64)`.

I'm really not sure...

**Comment by grgia** [comment] 2022-10-14 20:17
I'm on `Version 106.0.5249.119 (Official Build) (arm64)` as well. I'm still able to reproduce, and I also notice that I'm getting the "is typing..." on my phone despite being offline on chrome. I'm assuming that the pusher websockets aren't being disabled, but that seems to be an issue with chrome? Or somehow our implementation is getting around chrome's [disabling of websockets ](https://developer.chrome.com/docs/devtools/network/reference/#throttle-websocket)

**Comment by grgia** [comment] 2022-10-14 20:19
@roryabraham I know you've worked on the offline projects, do you have any ideas for why/what could be happening?

**Comment by grgia** [comment] 2022-10-17 17:17
I can still replicate this, it most likely seems to be an issue with chrome dev tools not actually disabling WebSockets as pusher is still working

**Comment by roryabraham** [comment] 2022-10-19 06:44
> it most likely seems to be an issue with chrome dev tools not actually disabling WebSockets as pusher is still working

This seems plausible. Can you replicate the issue if you actually turn off your WiFi instead of using the chrome dev tools?

**Comment by grgia** [comment] 2022-10-19 20:17
I sent an issue report to google, closing for now.

**Closed by grgia** 2022-10-19 20:17 UTC
Labels: Engineering, Daily
