### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] MEDIUM: Show full thread ancestry (front end, 1/2)

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#32618] opened 2023-12-07 03:59 UTC
**Strategy:**
To capture a billion users requires captures billions of conversations, and organizing them in an intuitive fashion.  One method of allowing many users to talk at the same time is to use "threads", which capture a conversation's many branches and side-branches in an organized fashion.  One major differentiation we have from Slack is our ability to "infinite thread": every conversation can branch and re-branch as many times as it needs to.

**Problem:**
Our testing with NewDot #social has already revealed that once you get a level or two away from the original conversation, it's easy to lose the context of the current thread.  We do show the "parent comment", but if that parent is itself a thread a level or two under the "root", it's easy to get lost.

**Solution:**
At the top of the thread show not just the immediate parent, but its parent, and so on back to the "root" of the conversation.  This provides a form of "breadcrumbs" such that if you ever get lost in the conversation, you can look at the top of the thread to remind yourself how you got to this particular conversational branch.  This can be done with the following changes:

* **Back-end:** (See https://github.com/Expensify/App/issues/34085) The back end will ensure that ancestor data is added when deep linking specifically to a thread.  However, this feature can be implemented on the front end without this back-end feature, by just navigating naturally down a thread hierarchy, which will populate Onyx with the correct data organically.

* **Front-end:** (To be done by a contributor.)  Render the ancestor comments at the top of the chat as follows:
    * Each thread already renders its immediate parent comment at the start of the chat, followed by a simple line separator.  This already figures out how to render that using the Onyx stored in a totally standard fashion, with no redundant storage, such that any changes to the parent comment are automatically reflected within the thread.  So the bulk of the complexity is already worked out for a single level of ancestry.
    * Propose how to extend that existing code in the simplest and most obvious way to support multiple levels of ancestry that look and work exactly the same.  Make sure the result looks like the mockup below.
    * And then add the ability to press (click or tap) on an ancestor chat in order to directly navigate to that specific chat on the parent report.
        * Note: We currently support the ability to get a direct link to a specific comment, and it will open the right report, but doesn't currently scroll to the right comment.  Use that link, and don't worry about the fact that it doesn't scroll correctly.

![image](https://github.com/Expensify/App/assets/575186/230cca5c-b6ad-4ed0-be4a-29aeb37461cc)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192639c03063bdc61</li>
        <li>Upwork Job ID: 1744243475279429632</li>
        <li>Last Price Increase: 2024-01-08</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 28104781</li>
<li>dukenv0307 | Contributor | 28104782</li>
</ul></li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2024-01-08 07:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In a thread report, along with the immediate parent, we want to show its parent, and so on back to the "root" of the conversation

### What is the root cause of that problem?

This is a new feature.

### What changes do you think we should make in order to solve the problem?

The following changes can be done:

1) [Here](https://github.com/Expensify/App/blob/bbfa54184346c4db8d0d848037e67e99155bc270/src/pages/home/ReportScreen.js#L184), we get the list of actions that should be shown for a report. In additional to these actions, we can iteratively fetch the parent Report Action if the Report itself has a `parentReportID` and `parentReportActionID` until its root. The ancestor Report Actions can be prepended to the existing Thread Report Actions which can be used for rendering.
2) When displayed as an ancestor of a chat, we should disable display of thread replies [here](https://github.com/Expensify/App/blob/bbfa54184346c4db8d0d848037e67e99155bc270/src/pages/home/report/ReportActionItem.js#L488C15-L488C41) by checking if the parent action is displayed as an ancestor in thread report. Also, a divider line can be displayed in the similar manner.
3) Since we can identify the Report ID to which an ancestor Report Action belongs to, we can easily navigate to the parent chat using this.
 
### What alternative solutions did you explore? (Optional)

**Comment by esh-g** [comment] 2024-01-08 10:20
# Proposal

## Please re-state the problem
At the top of the thread show not just the immediate parent, but its parent, and so on back to the "root" of the conversation. This provides a form of "breadcrumbs" such that if you ever get lost in the conversation, you can look at the top of the thread to remind yourself how you got to this particular conversational branch.

## What is root cause
N/A (new feature)

## What changes should be made?
1. We should first implement a method called `ReportActionUtils.getReportActionAncestry` that returns a `ReportAction[]` with all parent report actions.
Which can be implemented like this:
```js
function getReportActionAncestry(report: OnyxEntry<Report>): ReportAction[] {
    const reportActionAncestry = [];
    let currentReport = report;
    while (currentReport?.parentReportID && currentReport?.parentReportActionID) {
        const parentReport = allReports?.[currentReport.parentReportID];
        if (!parentReport) {
            break;
        }
        const parentReportAction = allReportActions?.[currentReport.parentReportID]?.[currentReport.parentReportActionID];
        if (!parentReportAction) {
            break;
        }
        reportActionAncestry.push(parentReportAction);
        currentReport = parentReport;
    }
    return reportActionAncestry.reverse();
}
```
2. We should use the list in `ReportActionItemParentAction` here:
https://github.com/Expensify/App/blob/bbfa54184346c4db8d0d848037e67e99155bc270/src/pages/home/report/ReportActionItemParentAction.js#L48
```js
const ancestery = ReportActionsUtils.getReportActionAncestry(props.report);
...
{ancestery.map((reportAction, index) => (
    <>
        <ReportActionItem
            report={props.report}
            action={reportAction}
            displayAsGroup={false}
            isMostRecentIOUReportAction={false}
            shouldDisplayNewMarker={props.shouldDisplayNewMarker}
             onPress={() => Report.navigateToAndOpenChildReport(reportAction.childReportID)}
            index={index}
            key={reportAction.reportActionID}
        />
        {!props.shouldHideThreadDividerLine && <View style={[styles.threadDividerLine]} />}
    </>
))}
```
**Result**
<img width="735" alt="Screenshot 2024-01-08 at 12 49 15 PM" src="https://github.com/Expensify/App/assets/77237602/3e096135-0b53-4e77-a948-a4d4e070d7f8">


3. To match the mockup, we also need to remove the reply counter for ancestor threads, this can be done by modifying the `isFirstThreadChat` function and possibly renaming it to `isAncestorChat`. (Optionally, a prop can be passed from point 2 which can disable reply count.)
https://github.com/Expensify/App/blob/bbfa54184346c4db8d0d848037e67e99155bc270/src/libs/ReportUtils.ts#L1012-L1014
```js
function isThreadFirstChat(reportAction: OnyxEntry<ReportAction>, report: OnyxEntry<Report>): boolean {
    const childReport = allReports?.[`${ONYXKEYS.COLLECTION.REPORT}${reportAction?.childReportID}`] ?? null;
    return ReportActionsUtils.getReportActionAncestry(childReport).length <= ReportActionsUtils.getReportActionAncestry(report).length;
}
```

4. Now we need to add logic to navigate to child report when pressed which can be done by modifying `ReportActionItem` to accept an `onPress` prop that can be passed in `ReportActionItemParentAction` as shown in point 2.
https://github.com/Expensify/App/blob/bbfa54184346c4db8d0d848037e67e99155bc270/src/pages/home/report/ReportActionItem.js#L666-L667
(Or alternatively, we can add a pressable in `ReportActionItemParentAction` itself and surround the `ReportActionItem` in a `View` with pointer events blocked.

**Resullt**

https://github.com/Expensify/App/assets/77237602/f2850701-661b-4dd6-b58e-ffe135339325

**Comment by abekkala** [comment] 2024-01-08 14:43
@mollfpr 🎉 looks like we received a few proposals already can you give them a review?

**Comment by mollfpr** [comment] 2024-01-08 17:08
> Propose how to extend that existing code in the simplest and most obvious way to support multiple levels of ancestry that look and work exactly the same.

@dukenv0307 @rojiphil Since the steps from all the proposals are similar, and it's pretty clear what should have been done, could you put the code changes for your proposal?

**Comment by esh-g** [comment] 2024-01-08 17:26
@mollfpr My proposal already has the code implementation laid out... Could you please review that because I believe for things like hiding the comment count, the exact implementation matters as well as the handling of the click event...

**Comment by mollfpr** [comment] 2024-01-08 17:29
@esh-g Let's wait for others to show their code so it can be reviewed fairly since they post their proposal before you.

**Comment by rojiphil** [comment] 2024-01-09 01:54
> could you put the code changes for your proposal?

@mollfpr Thanks for the feedback. I will share the code today.

**Comment by rojiphil** [comment] 2024-01-09 05:38
## Proposal

@mollfpr 
[Updated proposal](https://github.com/Expensify/App/issues/32618#issuecomment-1880494569) with code changes + test branch

**Comment by mollfpr** [comment] 2024-01-10 15:19
I don't feel well and will sleep early. I'll finish the review in the morning.

**Comment by quinthar** [comment] 2024-01-10 23:55
Ah feel better!  Am I correct that we have a working PR for this and it just needs review?  That's great!

**Comment by mollfpr** [comment] 2024-01-11 17:14
Thank you guys for the proposal. I think the [proposal](https://github.com/Expensify/App/issues/32618#issuecomment-1880723969) from @esh-g is more suitable for the case, and it's a pretty clear implementation.

🎀 👀 🎀 C+ reviewed!

**Comment by esh-g** [comment] 2024-01-11 17:47
@dukenv0307 That was the demo for the navigation only, editing context menu options can be done in the PR. You shared the whole branch but I only shared some code snippets for the general gist for the solution. Moreover, my proposal was the first one with complete implementations of functions like `getReportActionAncestry` and your proposal does not include logic to remove the number of replies for ancestor thread (by editing `isThreadFirstChat`)

**Comment by rojiphil** [comment] 2024-01-11 17:59
> I think the [proposal](https://github.com/Expensify/App/issues/32618#issuecomment-1880723969) from @esh-g is more suitable for the case, and it's a pretty clear implementation.

@mollfpr 
Also would love to have your feedback on my proposal.
My test branch is almost a working PR and it leverages the existing `ReportActionItemParentAction`.  From the implementation front, the [proposal](https://github.com/Expensify/App/issues/32618#issuecomment-1880494569) seems clear too. Or am I missing something here.
Also, if you could point out why the approved proposal is more suitable than others, that would help us understand better.

**Comment by mollfpr** [comment] 2024-01-12 16:42
@rojiphil I don't think getting all parent report actions in the `ReportScreen` is ideal, and I think it's better to get the ancestor when we know in the thread.

---

>Please see the video from esh-g proposal, the context menu of the parent isn't correct

Sorry, I didn't realize we show the regular context menu for the parent action.

After testing the proposals again, I agree with the point from @dukenv0307 mentioned for proposal @esh-g. Since everyone has already put in their code changes, I expect a few changes we will do in the PR work.

I decided to change my initial choice and suggest going with the @dukenv0307 proposal.

Sorry for @esh-g @dukenv0307 for this inconvenience 🙏

**Comment by abekkala** [comment] 2024-01-15 20:48
@marcaaron do you want to review the above after @mollfpr suggested accepted proposal?

**Comment by marcaaron** [comment] 2024-01-16 20:48
LGTM. @dukenv0307 let's get this into review!

**Comment by quinthar** [comment] 2024-01-21 23:40
Very cool!  When you click an ancestor comment, does it deep link you back to that comment on the ancestor room?  (Recognizing that deep-links don't yet auto-scroll to the right comment when the room is opened, but they should super soon.)

**Comment by quinthar** [comment] 2024-01-21 23:40
@mollfpr It's been 5 days; can you please review this immediately?  Thanks!

**Comment by mollfpr** [comment] 2024-01-22 02:31
@quinthar Yup! I left a comment in the PR, and we still have some issues that must be resolved.

**Comment by abekkala** [comment] 2024-01-25 21:47
@mollfpr have the issues in the PR from @dukenv0307 been resolved?

**Comment by mollfpr** [comment] 2024-01-26 03:08
@quinthar @abekkala We are getting close, the changes look good on showing the ancestor, but we still have an issue with the mark unread on the parent message.

**Comment by quinthar** [comment] 2024-02-01 04:02
Hey all, what's the latest here?  This has sat for a week with no updates.  We need to accelerate the turnaround here.  What are the exact next steps, who is doing them, and when will they be done?

**Comment by abekkala** [comment] 2024-02-08 18:39
### PAYMENTS FOR FEB 14


- Fix: @dukenv0307 [$500 - if no regressions] [Offer](https://www.upwork.com/nx/wm/offer/28104782) 
- PR Review: @mollfpr [$500 - if no regressions] [Offer](https://www.upwork.com/nx/wm/offer/28104781)

**Comment by abekkala** [comment] 2024-02-15 17:18
1. Open any report
2. Send a message
3. Reply in the thread of this message
4. Report steps 2-3 serval times
5. Verify that in each thread, all ancestors of this thread are displayed
6. Click on any ancestor action
7. Verify that we go to the current thread of this action

**Comment by abekkala** [comment] 2024-02-15 17:20
@dukenv0307 payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment] 2024-02-15 17:20
@mollfpr can you accept the offer in Upwork so I can send payment to you? It expires today

**Comment by mollfpr** [comment] 2024-02-15 17:21
@abekkala I'll do a manual request in NewDot 🚀

**Comment by abekkala** [comment] 2024-02-15 17:22
> I'll do a manual request in NewDot 🚀

oh that is correct - thanks for the reminder! I'll post a payment summary for the person who is paying you in NewDot!

**Comment by abekkala** [comment] 2024-02-19 17:38
closing - payment is in NewDot - payment summary above.

**Closed by abekkala** 2024-02-19 17:38 UTC
Labels: External, Daily, NewFeature, Overdue, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-02-29 22:52
$500 approved for @mollfpr based on [this comment](https://github.com/Expensify/App/issues/32618#issuecomment-1946667607).
