### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] The workspace logo disappears if changed the workspace picture on combined user/workspace chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19905] opened 2023-05-31 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to dev on web chrome
2. Create a new workspace and invite a user
3. Notice that on LHN, a combined workspace and user chat is created with both the user picture and the workspace picture
4. Now try to change the workspace picture and notice that as soon as you change the workspace picture, the logo of the workspace that was present below in the LHN chat disappears. And if you remove the workspace picture, it reappears again
5. Thus, it should have shown the updated picture on the LHN , instead of making it disappear

## Expected Result:
 The workspace logo should have been updated to the picture set on the LHN in the combined user/workspace chat instead of making it go disappear
## Actual Result:
 The workspace logo disappears if changed the workspace picture on combined user/workspace chat

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f60e50ac-3321-42a7-b67e-ef47be8ce963

https://github.com/Expensify/App/assets/43996225/4755d1f4-7c1c-410d-b8b9-5a08ee826033

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685339400060349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e5f5da305633aff</li>
        <li>Upwork Job ID: 1669420216317644800</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-06-01 23:35
This should be fixed with https://github.com/Expensify/App/pull/19750 so I'm going to put it on hold until that is merged so we can test again to be sure.

**Comment by strepanier03** [comment] 2023-06-13 00:22
PR has been deployed to Prod so I'm going to test again and action as necessary.

**Comment by strepanier03** [comment] 2023-06-13 00:24
I don't have a dev environment so I asked [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1686615857497259) if someone could test for me.

**Comment by strepanier03** [comment] 2023-06-13 00:24
Switching to Daily for now so I can remember to revisit this tomorrow.

**Comment by priya-zha** [comment] 2023-06-14 11:49
#19750 was fixed, but this issue still exists. I just tested it today again.

https://github.com/Expensify/App/assets/34065075/c8542218-7342-45de-aa45-0a227d32ffb0

**Comment by strepanier03** [comment] 2023-06-15 19:01
This is still happening on DEV so I'm going to remove the hold and push through the BZ process so we can get a re-evaluation of it.

**Comment by strepanier03** [comment] 2023-06-15 19:04
@tjferriss - I am going out for sabbatical starting this evening and will not be able to move this forward before I leave. 

This was on hold for another PR that was supposed to fix this. The PR is closed so I asked in #expensify-open-source for help testing since this is on DEV. Priya confirmed it's still happening so I removed the hold so it could go through the BZ process.

**Comment by developerdavi** [comment] 2023-06-15 20:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The workspace logo/avatar disappears when the workspace logo is a valid URL. It only appears when the workspace does not contain a logo, so it displays the initials of the workspace instead.

### What is the root cause of that problem?
The root cause is that the `<Avatar/>` component is receiving the `imageStyles` prop with `null` value, and that is not valid when having a valid image as `source`. The `<Avatar/>` component checks the value of `imageStyles` on a ternary condition. `!![] -> true`, but `!!null -> false` and that results in `undefined` values being passed to `<Image/>` `style` prop.

### What changes do you think we should make in order to solve the problem?
There are two reasonable options:
- Changing the `imageStyles` prop to `[]` or remove it instead of setting as null (SubscriptAvatar.js:71).
- Properly handle `null` values from the `imageStyles` prop (Avatar.js:76).


https://github.com/Expensify/App/assets/31714350/3aabbcb4-6924-470b-b99d-bacd659c8140

**Comment by tjferriss** [comment] 2023-06-19 18:32
I'm just catching up here. @rushatgabhane what do you think of the above proposal?

**Comment by developerdavi** [comment] 2023-06-21 01:16
Hey @rushatgabhane please review my proposal above. I'm not sure if the first proposal is still valid. The issue is related to the props passed to the `Avatar` component, as I showed in the video.

**Comment by NikkiWines** [comment] 2023-06-21 18:32
Hmm, it does look like some of the suggestions in @allroundexperts's [proposal](https://github.com/Expensify/App/issues/19905#issuecomment-1571009268) have already been implemented. 

> Firstly, we need to pass policyID prop into ReportActionItemCreated component [here](https://github.com/allroundexperts/Expensify/blob/f0078298dbc9546cab847ff420eb375b07601c46/src/pages/home/report/ReportActionItem.js#L344-L345).

> Next, we'll need to load the policy into the ReportActionItemCreated component as a prop. We need to add following [here](https://github.com/allroundexperts/Expensify/blob/f0078298dbc9546cab847ff420eb375b07601c46/src/pages/home/report/ReportActionItemCreated.js#L100).

Both of these changes already exist on main now, so we are already re-rendering and calling `const icons = ReportUtils.getIcons(props.report, props.personalDetails);` whenever the policy changes. 

Given that I don't think we can proceed with @allroundexperts's proposal if the issue still exists. @rushatgabhane, thoughts? Can you review @developerdavi's proposal? @allroundexperts can you provide an updated proposal since your suggests are already implemented?

**Comment by thienlnam** [comment] 2023-06-21 18:34
Not sure how I got autoassigned here, but removing myself since Nikki is already on the case!

**Comment by developerdavi** [comment] 2023-06-26 14:41
Thanks @rushatgabhane!

The issue with the distorted fallback icon when the `imageStyles` props is not `null` is due to the fact that the icon dimensions are actually 24x24px, while the image icon has 20x20px dimensions:

![Screenshot 2023-06-26 at 11 11 14](https://github.com/Expensify/App/assets/31714350/424cd75e-47e5-498f-8037-f625d928edb4)
![image](https://github.com/Expensify/App/assets/31714350/0d2b79b0-bb99-46c0-94fe-91b3158f8b1b)

One possible solution is to properly let the fallback icon have 24x24px dimensions when it's a workspace icon:

```js
const iconStyle = props.imageStyles && !isWorkspace ? [StyleUtils.getAvatarStyle(props.size), styles.bgTransparent, ...props.imageStyles] : undefined;
```

---

About handling `null` value passed to `imageStyles` prop, a possible solution, if we really want to consider `null` as a valid value, would be adjusting the ternary condition in the `<Avatar/>` component to generate a valid value for the `style` prop of the `<Image/>` component in the case of the checked condition is falsy:

```js
const imageStyle = props.imageStyles ? [StyleUtils.getAvatarStyle(props.size), ...props.imageStyles, StyleUtils.getAvatarBorderRadius(props.size, props.type)] : [StyleUtils.getAvatarStyle(props.size), StyleUtils.getAvatarBorderRadius(props.size, props.type)];
```

**Comment by developerdavi** [comment] 2023-06-26 16:13
@rushatgabhane as I said, the different dimensions are because of the 2px border, not the SVG size. The workspace avatar does not have a border when the image is valid. In my opinion, the best is to add a border to the workspace avatar image as well, and that's probably the expected UI.

**Comment by developerdavi** [comment] 2023-06-26 16:20
@rushatgabhane

> (2) Avatar.js is a generic component. I'm not sure how we'll handle null values such that the styles work everywhere. Because props.size isn't required

The only place where this prop is being passed as `null` is by the `<SubscriptAvatar/>`.

I think that the solution is a mix of the two as we discussed here because not setting as null also causes some issues in the current codebase (e.g the distorted icon). The component should work as expected in both ways.

**Comment by developerdavi** [comment] 2023-06-26 17:44
Applied to the job on Upwork. I can deliver the PR later today (Brazilian time), probably tomorrow for you guys.

**Comment by developerdavi** [comment] 2023-06-27 01:33
@NikkiWines @rushatgabhane created a PR (https://github.com/Expensify/App/pull/21657). Looking forward for your feedback. Thank you!

**Comment by tjferriss** [comment] 2023-06-28 05:13
@rushatgabhane are you able to review the PR tomorrow?

**Comment by developerdavi** [comment] 2023-07-03 18:34
Bot calculations seem correct. What's the next step? I already submitted a proposal to the job on Upwork.

**Comment by developerdavi** [comment] 2023-07-03 19:56
> @developerdavi you'll get paid after the regression period. (PR is in production for 7 days without any regression)

Gotcha! Thank you guys. I'm looking forward to contribute more to the project :)

**Comment by tjferriss** [comment] 2023-07-11 22:02
I've sent offers to everyone via Upworks. @rushatgabhane can you get started on the checklist?

**Comment by NikkiWines** [comment] 2023-07-17 19:54
@rushatgabhane friendly bump here 🙇

**Comment by tjferriss** [comment] 2023-07-18 16:39
Payments sent to @developerdavi and @priya-zha

**Comment by tjferriss** [comment] 2023-07-19 05:28
@rushatgabhane can you accept the offer in Upworks?

**Comment by rushatgabhane** [comment] 2023-07-23 15:11
1. The PR that introduced the bug has been identified. Link to the PR: 

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again
    1. Click on any chat-based report in LHN to view the report screen.
    2. Click on the actions button on the footer to show the actions menu.
    3. Click 'Add Attachment' and select the corrupted file as attached in the issue.
    4. Click on the 'Send` button in the Attachment modal to send the attachment.
    5. Note that the sidebar screen in LHN for this chat report will show '[Attachment]'. Further, the 'Uploading Attachment' chat comes up in the chat report screen.
    6. Once the attachment upload fails due to the corrupt file, we will observe a failure comment with "Unexpected error..."
    7. At this time, verify that the sidebar screen in LHN for this chat report displays the last successful message instead of '[Attachment]'.

**Comment by rushatgabhane** [comment] 2023-07-23 15:15
Hi @tjferriss I'll be requesting payment on new dot and Anu will handle it for now. Thanks :)

**Comment by rushatgabhane** [comment] 2023-07-23 15:29
Made a manual request on new dot https://staging.new.expensify.com/r/4385861037826843

**Comment by tjferriss** [comment] 2023-07-25 23:11
Easy, Melvin. We're just wrapping up payment.

**Comment by JmillsExpensify** [comment] 2023-07-27 04:38
@tjferriss Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @rushatgabhane's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869). This may also be affected based on the possible regression above.

**Comment by tjferriss** [comment] 2023-07-27 05:23
The payment comment has been updated: https://github.com/Expensify/App/issues/19905#issuecomment-1625182299

**Comment by JmillsExpensify** [comment] 2023-07-27 22:51
Reviewed details for @rushatgabhane. This is accurate based on summary from Business Reviewer and approved for payment in NewDot.

**Comment by tjferriss** [comment] 2023-08-01 22:09
@rushatgabhane bumping this comment once more https://github.com/Expensify/App/issues/19905#issuecomment-1652336978

**Comment by rushatgabhane** [comment] 2023-08-01 22:57
@tjferriss i responded to the in the PR

**Closed** 2023-08-02 03:37 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
