### ISSUE TITLE
[$250] mWeb - LHN - Chat started while offline, disappears from LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51025] opened 2024-10-17 14:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website
2. Turn of internet connection
3. Tap on the FAB
4. Tap on "Start Chat"
5. Search for a user without any conversation in common and select it
6. Tap on the arrow on the top left corner
7. Once in LHN, turn on internet connection again
8. Verify the new chat now appears without any reduced opacity and loads correctly

## Expected Result:
The user should be able to start a new chat while offline and this chat should remain visible and accessible after recovering internet connection

## Actual Result:
New chat, created while offline, disappears from LHN when internet connection is recovered

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>  

https://github.com/user-attachments/assets/7cb62dee-a095-4315-b67a-8d8865e8ec52

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848489150153382951</li>
        <li>Upwork Job ID: 1848489150153382951</li>
        <li>Last Price Increase: 2024-10-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by lanitochka17** [comment] 2024-10-17 14:22
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VickyStash** [comment] 2024-10-22 10:45
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment] 2024-10-22 14:35
I'm not able to reproduce the issue. It works as expected for me:

https://github.com/user-attachments/assets/9c3baab4-5e7a-41cf-9787-22b674ea9024

**Comment by lanitochka17** [comment] 2024-10-24 13:26
@mkhutornyi Issue is not reproducible now

https://github.com/user-attachments/assets/c5f0e2e1-f1a2-446a-b5f1-e1828551168e

**Comment by greg-schroeder** [comment] 2024-10-24 23:01
I also can't reproduce. Closing accordingly. Please reopen if you disagree.

**Closed by greg-schroeder** 2024-10-24 23:01 UTC
Labels: External, Daily, Help Wanted, Bug
