### ISSUE TITLE
[$250]  [Search v2.1] - (you) disappears after selecting own user name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47712] opened 2024-08-20 13:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh05081@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com/search/filters
2. Click From or To
3. Select your user name

## Expected Result:
(you) will not disappear after selecting own user name

## Actual Result:
(you) disappears after selecting own user name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/0d3a4fab-3206-40fa-937f-3c09d3fc5858

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc33a0aabc7f4ab9</li>
        <li>Upwork Job ID: 1826026505817504872</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 103781419</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @FitseTLT</details>

**Comment by lanitochka17** [comment] 2024-08-20 13:20
We think that this bug might be related to #wave-collect - Release 1

**Comment by FitseTLT** [comment] 2024-08-20 13:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search filters - (you) disappears after selecting own user name

### What is the root cause of that problem?
We are not getting the text from getDisplayName when current user is selected here
https://github.com/Expensify/App/blob/a32da40e1017d2136389f05735bace7bc307e098/src/components/Search/SearchFiltersParticipantsSelector.tsx#L111
### What changes do you think we should make in order to solve the problem?

Remove the condition `!isCurrentUserSelected`
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-08-20 13:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search filters - (you) disappears after selecting own user name

### What is the root cause of that problem?
We are not getting the text from getDisplayName when current user is selected here
https://github.com/Expensify/App/blob/a32da40e1017d2136389f05735bace7bc307e098/src/components/Search/SearchFiltersParticipantsSelector.tsx#L111
### What changes do you think we should make in order to solve the problem?

We need to get the text from get `getDisplayNameForParticipant` when current user is selected
### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-08-20 13:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
(you) disappears after selecting own user name
### What is the root cause of that problem?
When the user selects their account, In `getParticipantsOption`, we assign assign `displayName` which is the users name without `(you)` to `text`
https://github.com/Expensify/App/blob/d519981587b065ce96f73ab341d84f9eb17a864c/src/libs/OptionsListUtils.ts#L447-L457
And the `text` prop will be used to render the users display name in `InviteMemberListItem` component 
### What changes do you think we should make in order to solve the problem?
Since `participant.text` has the display name that includes `(you)` we should assign `participant.text` to `text` prop and fallback to `displayName` if  `participant.text` is undefiend 
```javascript
text: participant?.text ?? displayName,
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-08-20 14:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search filters - (you) disappears after selecting own user name

### What is the root cause of that problem?
We are properly setting (you) to current user here
https://github.com/Expensify/App/blob/a32da40e1017d2136389f05735bace7bc307e098/src/components/Search/SearchFiltersParticipantsSelector.tsx#L111-L113
but only doing it when current user is not selected 
### What changes do you think we should make in order to solve the problem?

We should do the same update of `text` we did [here](https://github.com/Expensify/App/blob/a32da40e1017d2136389f05735bace7bc307e098/src/components/Search/SearchFiltersParticipantsSelector.tsx#L111-L113
) for selected current user too
```
   const currentUserSelected = formattedResults.section.data.find((option) => option.accountID === chatOptions.currentUserOption?.accountID);

        if (chatOptions.currentUserOption) {
            const formattedName = ReportUtils.getDisplayNameForParticipant(chatOptions.currentUserOption.accountID, false, true, true, personalDetails);
            if (!currentUserSelected) {
                newSections.push({
                    title: '',
                    data: [{...chatOptions.currentUserOption, text: formattedName}],
                    shouldShow: true,
                });
            } else {
                currentUserSelected.text = formattedName;
            }
        }
        newSections.push(formattedResults.section);
```
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-08-20 14:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The (you) text disappears from the current user option after selecting it.

### What is the root cause of that problem?
When the current user is not selected yet, we format the name using `getDisplayNameForParticipant` and pass `shouldAddCurrentUserPostfix` as true which adds the (you) suffix.
https://github.com/Expensify/App/blob/c6d81c82fc88d52622c41a958844b2fcc9b1bb33/src/components/Search/SearchFiltersParticipantsSelector.tsx#L111-L115

When the user is selected, the selected options is formatted with `OptionsListUtils.formatSectionsFromSearchTerm` > `getParticipantsOption`.
https://github.com/Expensify/App/blob/c6d81c82fc88d52622c41a958844b2fcc9b1bb33/src/components/Search/SearchFiltersParticipantsSelector.tsx#L98-L100
https://github.com/Expensify/App/blob/c6d81c82fc88d52622c41a958844b2fcc9b1bb33/src/libs/OptionsListUtils.ts#L2378

In `getParticipantsOption`, the text is from `PersonalDetailsUtils.getDisplayNameOrDefault` whcih doesn't contains the (you) suffix because we don't pass `shouldAddCurrentUserPostfix` to it.
https://github.com/Expensify/App/blob/c6d81c82fc88d52622c41a958844b2fcc9b1bb33/src/libs/OptionsListUtils.ts#L451

### What changes do you think we should make in order to solve the problem?

Pass as true for `shouldAddCurrentUserPostfix` to `getDisplayNameOrDefault`.
```
const displayName = PersonalDetailsUtils.getDisplayNameOrDefault(detail, LocalePhoneNumber.formatPhoneNumber(login), undefined, shouldAddCurrentUserPostfix);
```
This will require us to pass down the value as true from SearchFiltersParticipantsSelector > formatSectionsFromSearchTerm > getParticipantsOption.

**Comment by abdulrahuman5196** [comment] 2024-08-26 18:31
Hi, came back from weekend. Will check in the morning.

**Comment by abdulrahuman5196** [comment] 2024-08-29 16:12
@FitseTLT 's proposal here https://github.com/Expensify/App/issues/47712#issuecomment-2299001034 looks good and works well. It aims to fix the issue in the SearchFiltersParticipantsSelector similar to existing approach of showing (you).

🎀 👀 🎀
C+ Reviewed

**Comment by bernhardoj** [comment] 2024-08-29 17:36
@abdulrahuman5196 any opinion with my proposal?

I think the selected proposal doesn't follow a similar approach. The approach is mutating the item returned from the array below.
https://github.com/Expensify/App/blob/a32da40e1017d2136389f05735bace7bc307e098/src/components/Search/SearchFiltersParticipantsSelector.tsx#L107

The current approach is, selected options are formatted by `OptionsListUtils.formatSectionsFromSearchTerm` and then pushed to the list. If the current user isn't selected, we push the current user with (you) suffix to the list. If the user is selected, then it will be handled by `OptionsListUtils.formatSectionsFromSearchTerm`, just like the other selected items.

Also, the selected proposal will cause the current user to always be at the top even though there are selected items.
<img width="379" alt="image" src="https://github.com/user-attachments/assets/a365525d-fe6f-4bc6-be2c-8d178d653866">

**Comment by FitseTLT** [comment] 2024-08-29 17:53
> Also, the selected proposal will cause the current user to always be at the top even though there are selected items.

@abdulrahuman5196  It's because I moved down the `newSections.push(formattedResults.section);` below the `if` block I have [updated](https://github.com/Expensify/App/issues/47712#issuecomment-2299001034) It works fine now.
We alreay have a code that concatenates `(you)` the only problem we forgot to do the same for selected list so my approach is indeed using the same as existing approach.
https://github.com/user-attachments/assets/9db1d9d7-e907-4aad-a96b-d03bb69bec33

**Comment by abdulrahuman5196** [comment] 2024-08-29 18:02
@bernhardoj 

>I think the selected proposal doesn't follow a similar approach. The approach is mutating the item returned from the array below.

I noticed that during approval, but its more like a PR code fix. 
for the issue you mentioned, we can fix that during PR since we don't consider the proposal code to be the expect PR code.

>any opinion with my proposal?
>Pass as true for shouldAddCurrentUserPostfix to getDisplayNameOrDefault

I was not aligned in passing shouldAddCurrentUserPostfix as true in the common helper method usecase. Since the default value of shouldAddCurrentUserPostfix in getDisplayNameOrDefault is false and I have also noticed we are not passing it as true in multiple common places.

**Comment by bernhardoj** [comment] 2024-08-29 18:34
> I was not aligned in passing shouldAddCurrentUserPostfix as true in the common helper method usecase. Since the default value of shouldAddCurrentUserPostfix in getDisplayNameOrDefault is false and I have also noticed we are not passing it as true in multiple common places.

I don't see why this is a problem since we only pass it as true in the filter page just like we did with the non-selected current user section.

> I think the selected proposal doesn't follow a similar approach. The approach is mutating the item returned from the array below.

> I noticed that during approval, but its more like a PR code fix.

I believe the root issue is that we are not formatting it inside `OptionsListUtils.formatSectionsFromSearchTerm` (assuming you agree with this), but the selected proposal explanation is revolving around mutating the array and lacks the explanation that we already did some formatting inside `OptionsListUtils.formatSectionsFromSearchTerm` which is why I posted my proposal because I think the approach is very different.

^ just an explain why I posted my proposal 😄, i'll accept any decision

**Comment by twisterdotcom** [comment] 2024-09-02 14:55
We have an assignee @MelvinBot

**Comment by twisterdotcom** [comment] 2024-09-02 14:56
We have an assignee @MelvinBot

**Comment by FitseTLT** [comment] 2024-09-03 20:57
PR will be up tomorrow

**Comment by FitseTLT** [comment] 2024-09-17 14:45
bump for a review @abdulrahuman5196

**Comment by luacmartins** [comment] 2024-09-23 23:37
It seems like we can close this issue then?

**Closed** 2024-09-24 12:19 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by FitseTLT** [comment] 2024-09-24 12:24
@twisterdotcom [PR](https://github.com/Expensify/App/pull/48600) was raised and was on review; I think Payment is due here.

**Comment by abdulrahuman5196** [comment] 2024-09-26 17:31
> @twisterdotcom [PR](https://github.com/Expensify/App/pull/48600) was raised and was on review; I think Payment is due here.

Yeah. Same is mentioned in [C+ doc](https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit?pli=1#bookmark=id.by6zfdtawcqn) as well

**Comment by twisterdotcom** [comment] 2024-09-27 10:24
Aha, I see. 

>If a contributor has been hired for a job and we decide to close the job before it is successfully completed, full payment is due for the hired contributor. If the C+ only reviewed proposals and not a PR, they are eligible for 50%. If they started reviewing a PR it's 100%. One caveat here might be if the hired contributor wasn't working on their PR with urgency.

Okay, cool, @abdulrahuman5196 was actively reviewing, so let's do both $250.

Payment Summary:
- @FitseTLT paid $250 via Upwork [here](https://www.upwork.com/nx/wm/workroom/38258325/) (Contributor)
- @abdulrahuman5196 paid $250 via Newdot requests (C+)

**Comment by JmillsExpensify** [comment] 2024-09-30 08:07
$250 approved for @abdulrahuman5196
