### ISSUE TITLE
[$500] IOS - Request - Camera blinks when switching between tabs 

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30280] opened 2023-10-24 17:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/28792
## Action Performed:
1. Go to + > Request money
2. Go to Scan and enable camera access if not allowed yet
3. Go to Distance, then Manual a few times
4. Go back to Scan

## Expected Result:
The camera should not blink when switching between tabs

## Actual Result:
Camera blinks when switching between tabs

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

Staging:

https://github.com/Expensify/App/assets/78819774/a1e719fd-a44c-4363-9c67-f9724eaf9f12

Production:

https://github.com/Expensify/App/assets/78819774/8789ba6d-21bc-49c1-87f0-70ce45214b75

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e1abb1d81693a85</li>
        <li>Upwork Job ID: 1717191476381212672</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2023-10-24 18:24
@isabelastisser You are right. Issue was found when executing PR https://github.com/Expensify/App/pull/28792

**Comment by dangrous** [comment] 2023-10-24 19:18
So you're right on the cause, I'm wondering if it's a bug or just how phone cameras work - it's not actually blinking, it's just - for a second - showing the last image it saw before you navigated away. Like, point it at one thing, switch away, point it at another thing, and then switch back to the camera - you'll see the first thing for a second. I think it might just be the camera initializing again?

But maybe we could send it selectedTab just a second earlier, it looks like it might not be triggered until the tab is fully visible, rather than on press. If we could activate it earlier then maybe it could work.

Also cc @dukenv0307 @mountiny @mananjadhav who worked on that PR because I know very little about cameras.

@ishpaul777 I think you can build for a physical device via XCode? I'm not sure if that requires any special access or anything

**Comment by mananjadhav** [comment] 2023-10-24 19:21
This is bit of a bummer because I couldn’t this on iOS physical device myself.

I can see the issue right now, but I am afk and I am not sure if I can confirm the exact behavior as of now.

**Comment by dangrous** [comment] 2023-10-24 21:51
Confirmed not a blocker, we should still look into this though! It looks like the new code activates the camera later than it used to - so only when the camera is fully in view, rather than as soon as the button is pressed, or as soon as the scroll begins. So we should figure out a way to get that activated earlier, without undoing the fix made in #28792

**Comment by sonialiap** [comment] 2023-10-25 14:48
Sounds like an external issue, adding label

**Comment by mountiny** [comment] 2023-10-25 20:24
I agree this is not a blocker, I have seen the blink but I have seen that in previous versions too @dukenv0307 I think this should be handled as a regression from your PR though as it introduced it cc @sonialiap

**Comment by sonialiap** [comment] 2023-10-30 14:16
@mountiny we'll want to fix this in https://github.com/Expensify/App/issues/27879 and then pay the reporter, is that correct?

**Comment by dangrous** [comment] 2023-10-31 18:32
Yeah I think ideally @dukenv0307 and @mananjadhav would take care of this as a regression (or at least an improvement) from #27879 - let me know if you think differently @mountiny

**Comment by mananjadhav** [comment] 2023-10-31 20:04
I agree we can take this as an improvement from the previous PR. But we would still need help to test it on IOS.

@dukenv0307 can we please work on the follow up PR?

**Comment by situchan** [comment] 2023-10-31 20:07
I can help testing. I can install app on iOS physical device

**Comment by mountiny** [comment] 2023-11-01 11:11
I agree this should be treated as a regression and so we could also close this issue, pay the reporter first but handle this in the original issue

**Comment by dangrous** [comment] 2023-11-01 17:41
Okay cool, that works for me. Closing! I just commented on the main issue with these details.

**Closed by dangrous** 2023-11-01 17:41 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
