### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Web - The green line appear immediately only after comments are added to a task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23004] opened 2023-07-17 12:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.exensify.com](https://staging.new.expensify.com/)
2. log in with your account
3. Create a task
4. Send a message 

## Expected Result:
The green line should appear immediately after creating the task

## Actual Result:
The green line appear immediately only after comments are added to a task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (33)](https://github.com/Expensify/App/assets/93399543/c77aca43-fb5c-40b5-aa89-a562fc99d75f)

![image (32)](https://github.com/Expensify/App/assets/93399543/6949290d-8421-4103-a403-2eb1fe6c0507)

https://github.com/Expensify/App/assets/93399543/a50526cd-dca9-4846-a4a5-c6e5640677a7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689466341316849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01179280ad6cadbb04</li>
        <li>Upwork Job ID: 1681076844552364032</li>
        2023-07-17<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 25783892</li>
</ul></li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-07-17 13:22
Not sure if this is a bug.

The line separates the details with the conversation. Let's take opinion expensify team.

**Comment by Pujan92** [comment] 2023-07-17 13:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Green line does not appear immediately for the task report and only appears if it has any comment

### What is the root cause of that problem?
We are showing the line here conditionally where it only shows when we it is not only a ReportAction.
https://github.com/Expensify/App/blob/f638162c899795821e8d6fa68735aa47fa6e2aa1/src/pages/home/report/ReportActionItem.js#L421-L423

### What changes do you think we should make in order to solve the problem?
Remove `shouldShowHorizontalRule` prop from the `TaskView` component and remove the pass from the `ReportActionItem` as it is not required considering this change.

**Comment by makiour** [comment] 2023-07-17 23:37
Hello @anmurali 

I am Mohammed, an experienced full-stack developer and worked as SWE engineer intern at Google and Meta and currently working remotely as an SWE intern at a Fintech company in Dubai.

As I see you marked this task as external, I would like to know if it is still open for proposals as I managed to find the root cause and I can solve it as well quickly for you in the same business day in the next hours.

Will be more than happy to help! Let me know if it is still open.

**Comment by avinayk** [comment] 2023-07-18 02:05
Interested for this job post

**Comment by avinayk** [comment] 2023-07-18 05:43
I have done this last time also but didnt get any further message

**Comment by avinayk** [comment] 2023-07-18 05:48
Contributor details
Your Expensify account email: <avinaykumar.web@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/avinayk>

**Comment by avinayk** [comment] 2023-07-18 05:49
Contributor details
Your Expensify account email: avinaykumar.web@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/avinayk

**Comment by avinayk** [comment] 2023-07-18 05:59
![Screenshot 2023-07-18 at 11 28 10 AM](https://github.com/Expensify/App/assets/19589263/622b578a-403d-4f21-8a58-8bdd576d582e)

when I click on assign task and it open title on right side then suddenly green line appear without doing anything is this BUG are you refer ?

**Comment by narefyev91** [comment] 2023-07-18 06:46
@shawnborton can you please check this issue? For me as I see it's not a bug in case we separating task information with additional message

**Comment by narefyev91** [comment] 2023-07-18 10:35
Proposal from @dukenv0307 looks good to me https://github.com/Expensify/App/issues/23004#issuecomment-1639409767
🎀 👀 🎀 C+ reviewed

**Comment by MonilBhavsar** [comment] 2023-07-21 09:52
> Not sure if this is a bug.
> 
> The line separates the details with the conversation. Let's take opinion expensify team.



> @shawnborton can you please check this issue? For me as I see it's not a bug in case we separating task information with additional message

I agree with these two comments. This doesn't seem like a bug to me. Looks like green line differentiates between task details and messages in the task. If there are no messages, then I think we should not display green line. cc @shawnborton curious for your thoughts

**Comment by MonilBhavsar** [comment] 2023-07-21 10:17
Good point!
I see that for tasks, current behavior is different.
For MoneyRequest, I think it is fine, since we have ReportPreview as a content after the green line
<img width="1726" alt="Screenshot 2023-07-21 at 3 45 13 PM" src="https://github.com/Expensify/App/assets/32012005/fa1b0eee-3927-4b0e-a973-40093bffb62c">


Still, I would wait for thoughts from design team, as displaying separator without content looks odd to me.

**Comment by shawnborton** [comment] 2023-07-21 12:29
Cc @trjExpensify as we've talked about this before.

My thoughts are that we should treat every single kind of thread (report, expense, task, thread message, etc) the same. I'm not sure if I prefer having the line always or not, but either way we should pick one and stay consistent.

**Comment by trjExpensify** [comment] 2023-07-21 14:42
I agree with being consistent. It's an unnecessary complexity to add code to determine which report types should or should not have this separator. My vote is to having it be present on all report types. 👍

**Comment by shawnborton** [comment] 2023-07-21 15:26
Works for me!

**Comment by MonilBhavsar** [comment] 2023-07-24 10:11
Thank you for the thoughts!

> My vote is to having it be present on all report types. 👍
> Works for me!

Considering the issue and these comments. I'm fine 👍

**Comment by MonilBhavsar** [comment] 2023-07-24 10:24
> If we don't want to create new props in ReportActionItem. We can consider moving TaskView and MoneyReportView to ReportActionItemParentAction instead of ReportActionItem


@dukenv0307 could you please share more thoughts on how you're thinking to accomplish it without introducing additional prop. I'm little bit sideways for providing same prop with same condition and logic to two different components. cc @narefyev91

**Comment by anmurali** [comment] 2023-07-24 15:20
I am un-assigning myself as I am out for 10 days.

**Comment by MonilBhavsar** [comment] 2023-07-27 07:01
> I don't think this is problem. If we decide to move TaskView and MoneyReportView to ReportActionItemParentAction, we also pass the isOnlyReportAction prop to both MoneyReportView to ReportActionItemParentAction

Thanks! just wanted to know how we were planning to approach. We can pass a new prop, no worries. And I think, let's use use either of `shouldShowHorizontalRule={!props.isOnlyReportAction}` or `shouldShowHorizontalRule={!props.shouldHideThreadDividerLine}` for all components - Task, Thread, MoneyRequest, and to have consistency?

**Comment by MonilBhavsar** [comment] 2023-07-27 07:02
@narefyev91 any though on [this](https://github.com/Expensify/App/issues/23004#issuecomment-1638099731) fisrt proposal to completely remove the condition, as we decided to display line in all cases

**Comment by MonilBhavsar** [comment] 2023-07-27 09:26
@dukenv0307 thanks for clarifying!
I was looking at this draft PR https://github.com/Expensify/App/pull/23055/files and the prop value for `shouldShowHorizontalRule` was passed differently only for TaskView. I believe we can pass the same for all different types of report views.

**Comment by zanyrenney** [comment] 2023-08-21 10:05
Payment summary: 

reporting bonus $0 - reported by internal Expensify employee
C+ payout: @narefyev91 (expert agency paid outside upwork)
C payout: $1000 no urgency bonus 

@dukenv0307 you've been paid so closing this one out!

**Closed by zanyrenney** 2023-08-21 10:05 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug
