### ISSUE TITLE
[$250] Invoice - Export buttons are available for invoice but disabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46979] opened 2024-08-07 15:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace is connected to QBO
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice
3. Enter amount and select a participant
4. Select the workspace connected to QBO as the sender
5. Send the invoice
6. Invoice receiver pays the invoice
7. As invoice sender, go to invoice chat
8. Click on the export button

## Expected Result:
Admin should be able to export the invoice since export buttons are present, or the export buttons should not appear for invoice if the feature is not available

## Actual Result:
Export buttons are available for invoice but disabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b13867b9-8035-47e5-8204-6e99ab491dd8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f7f1d9faff4b2165</li>
        <li>Upwork Job ID: 1821629335578332276</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103636950</li>
<li>FitseTLT | Contributor | 103636955</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by lanitochka17** [comment] 2024-08-07 15:21
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-08-07 19:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Export buttons are available for invoice but disabled

### What is the root cause of that problem?
We are not checking for `canExport` when displaying the export dropdown button
https://github.com/Expensify/App/blob/b806725c60547ac3e71470670cf34a0de107000b/src/components/ReportActionItem/ReportPreview.tsx#L478-L479
### What changes do you think we should make in order to solve the problem?

We need to check if it `canExport` before displaying it using the logic we are using to disable it
https://github.com/Expensify/App/blob/b806725c60547ac3e71470670cf34a0de107000b/src/components/ReportActionItem/ExportWithDropdownMenu.tsx#L49-L50

```
    const canBeExported = ReportUtils.canBeExported(iouReport);
...

{shouldShowExportIntegrationButton && !shouldShowSettlementButton && canBeExported &&(
                                    <ExportWithDropdownMenu
```
### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment] 2024-08-12 10:12
@alitoshmatov can you give this proposal a look when you get a chance?

**Comment by garrettmknight** [comment] 2024-08-13 16:42
@alitoshmatov bump when you a get chance

**Comment by alitoshmatov** [comment] 2024-08-13 17:34
Looks fairly simple task. I don't think this is a bug, the original implementation considered disabling buttons when export feature is unavailable.
If we want to change this logic then we can go with @FitseTLT 's [proposal](https://github.com/Expensify/App/issues/46979#issuecomment-2274158141)

C+ reviewed 🎀 👀 🎀

**Comment by neil-marcellini** [comment] 2024-08-20 18:09
I asked for some consensus about how this is supposed to work in Slack here.

> Looks fairly simple task. I don't think this is a bug, the original implementation considered disabling buttons when export feature is unavailable. If we want to change this logic then we can go with @FitseTLT 's [proposal](https://github.com/Expensify/App/issues/46979#issuecomment-2274158141)
> 
> C+ reviewed 🎀 👀 🎀

If we agree we want to hide the buttons in this case then I like this proposal too.

**Comment by garrettmknight** [comment] 2024-08-20 20:00
@neil-marcellini good to assign @FitseTLT ?

**Comment by neil-marcellini** [comment] 2024-08-21 18:09
Let's wait to assign until we figure out how it should work

**Comment by neil-marcellini** [comment] 2024-08-22 14:52
At least one other person agrees with me that we should [hide the buttons](https://expensify.slack.com/archives/CSL3XBCCR/p1724262176469559?thread_ts=1724177147.344969&cid=CSL3XBCCR) when the report can't be exported, so I'll hire @FitseTLT now.

**Comment by FitseTLT** [comment] 2024-08-23 20:58
The intended change has already been made on latest main. We can close this.

**Comment by alitoshmatov** [comment] 2024-08-26 17:58
Let's close this issue then

**Closed** 2024-08-26 20:51 UTC
Labels: External, Daily, Overdue, Bug
