### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] Android - User can't open context menu by long press on code block if keyboard is open.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27187] opened 2023-09-11 18:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Send a code block
3. Focus on composer to open keyboard
4. Try to open context menu by long pressing on the code block

## Expected Result:
Context menu should be opened.

## Actual Result:
Keyboard is closed but the context menu doesn't open.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6ac11dc7-56c1-4c6a-b8a4-2654325fbbb9

https://github.com/Expensify/App/assets/93399543/e47ceaae-d426-4640-9538-39b988d760c0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693936202424889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010167bb18a0e7f6fd</li>
        <li>Upwork Job ID: 1707105690912485376</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 26991374</li>
<li>Krishna2323 | Reporter | 26991377</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-11 18:46
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Android: Can't open context menu by long press on code block if keyboard is open.
### What is the root cause of that problem?
Upon investigation, it appears that the presence of the ScrollView component interferes with the propagation of the onLongPress event, especially when the keyboard is visible. This behavior is likely due to the ScrollView capturing the tap event, which results in the onLongPress event not being triggered for the nested component.
https://github.com/Expensify/App/blob/1400608f7cc6537fd03fe7987d6d59bc6c7da56d/src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/BasePreRenderer.js#L34-L56
### What changes do you think we should make in order to solve the problem?
Implement the keyboardShouldPersistTaps property on the ScrollView and set it to either "always" (preferred) or "handled". This ensures that taps are correctly propagated to child components even when the keyboard is active.
'always' : the keyboard will not dismiss automatically, and the scroll view will not catch taps, but children of the scroll view can catch taps.
'handled' : the keyboard will not dismiss automatically when the tap was handled by children of the scroll view (or captured by an ancestor).

**Comment by garrettmknight** [comment] 2023-09-14 11:26
@abdulrahuman5196 what do you think about that proposal?

**Comment by garrettmknight** [comment] 2023-09-19 03:37
@isabelastisser looks like you were assigned first so I'm gonna drop off.

@abdulrahuman5196 can we get a review?

**Comment by isabelastisser** [comment] 2023-09-20 20:38
Bump @abdulrahuman5196

**Comment by isabelastisser** [comment] 2023-09-25 15:11
@abdulrahuman5196, please review the proposal above. Thanks!

**Comment by isabelastisser** [comment] 2023-09-27 18:52
Hey @robertKozik, you're assigned this issue now, can you please review the proposal above so we can move forward asap? Thanks!!

**Comment by robertKozik** [comment] 2023-09-27 19:24
Hi @isabelastisser @Krishna2323 ! I've checked briefly the proposal and it looks very promising. I want to test it a little more though, before the selection - will come back soon(ish)

**Comment by mvtglobally** [comment] 2023-09-28 03:20
Issue not reproducible during KI retests. (First week)

**Comment by robertKozik** [comment] 2023-09-28 08:46
Issue is reproducible on TestFlight New Expensify. To repro this make sure to tap the code block itself

**Comment by robertKozik** [comment] 2023-10-02 11:33
Hi again! After further investigation, I think the solution proposed by @Krishna2323 should be sufficient to fix this bug.

**Comment by robertKozik** [comment] 2023-10-02 11:35
Hi again! After further investigation, I think the solution proposed by @Krishna2323 should be sufficient to fix this bug.

Selected Proposal: https://github.com/Expensify/App/issues/27187#issuecomment-1714404242

🎀 👀 🎀 C+ reviewed

**Comment by isabelastisser** [comment] 2023-10-02 18:12
Waiting for @srikarparsi to review it before I can assign the contributor. Thanks!

**Comment by srikarparsi** [comment] 2023-10-03 02:31
Looks good! Thanks @robertKozik and @Krishna2323

**Comment by isabelastisser** [comment] 2023-10-18 16:30
Sorry for the delay, I was OOO. I will take care of this soon!

**Comment by isabelastisser** [comment] 2023-10-19 16:10
The payments were made in Upwork, all set!

**Closed by isabelastisser** 2023-10-19 16:10 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
