### ISSUE TITLE
Bug: Endless spinner appears when Sign out and sign in back again 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12055] opened 2022-10-21 14:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. signed out of  test account on chrome, [staging.new.expensify.com](http://staging.new.expensify.com/)
2. signed back into test account

## Expected Result:
Able to sign in

## Actual Result:
Endless spinner appears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web - Chrome

**Version Number:** 1.2.18-4
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:**
[blank page.txt](https://github.com/Expensify/App/files/9839756/blank.page.txt)

**Notes/Photos/Videos:** 
<img width="742" alt="image (1)" src="https://user-images.githubusercontent.com/43996225/197216020-8e897a32-d6ff-4fa8-a17a-d6e419657f37.png">
<img width="738" alt="image" src="https://user-images.githubusercontent.com/43996225/197216023-f681fe53-14b5-4f83-99e6-f3aff967b249.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666285536654439?thread_ts=1666215056.542569&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2022-10-21 18:43
@mallenexpensify is this what you mean?
https://user-images.githubusercontent.com/38015950/197267369-819922ae-85f7-41f8-8fe7-837dac296608.mov

**Comment by mallenexpensify** [comment] 2022-10-21 20:05
@maddylewis  new BZ chore SO is [here](https://stackoverflow.com/c/expensify/questions/14418), we want to ensure BZ stays assigned to all issues so we can get to BugZero,

**Comment by maddylewis** [comment] 2022-10-21 20:09
@mallenexpensify - im confused by your comment. are you saying a member of the BZ team should stay assigned to any BUG issues they're assigned until the bug is resolved?

**Comment by mallenexpensify** [comment] 2022-10-21 21:26
Yes @maddylewis  but... I have a feeling you nor QA will be able to reproduce so you'll end up closing this issue if no one can.

**Comment by maddylewis** [comment] 2022-10-23 19:13
will attempt to reproduce on monday.

**Comment by maddylewis** [comment] 2022-10-24 14:22
im not able to reproduce this. 

1. i logged into my account on https://staging.new.expensify.com/ on web
2. logged in successfully
3. signed out
4. logged back in again 
5. no spinners / log in successful

**Comment by mallenexpensify** [comment] 2022-10-24 17:48
Thanks @maddylewis , I'm gonna close this cuz, even though I did experience the bug, I don't think others will be able to reliably reproduce.  We can reopen if it happens to someone else and they provide repro steps.

**Closed by mallenexpensify** 2022-10-24 17:48 UTC
Labels: Daily, Needs Reproduction, Bug
