### ISSUE TITLE
[HOLD for payment 2023-09-04] [$1000] Web - Refreshing in the profile section while requesting money will stop the requesting money process

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22802] opened 2023-07-13 12:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to FAB> Request money
2. Enter the amount you want to request
3. Select any user
4. Click the avatar to open the profile section
5. Refresh the page and select the back button to go back to "Request money-cash" page to continue requesting

## Expected Result:
"Request money-cash" page should open and continue the process of requesting money

## Actual Result:
The back button on the profile section after refreshing stopped the requesting money process

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d61c9d70-bf10-42f5-999d-494cd9213dc3

https://github.com/Expensify/App/assets/93399543/40e9e739-9465-4d83-bd8e-e5109287271f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Yokabdk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689167956017229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0199790e31e5ad6e47</li>
        <li>Upwork Job ID: 1681633507196174336</li>
        <li>Last Price Increase: 2023-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26245839</li>
</ul></li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-07-15 22:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a user is on the `ProfilePage `that was navigated to from the **IOU confirmation page**, pressing the back button navigates the user back to the **home page** instead of the IOU confirmation page. This behavior is observed even without a page refresh.

### What is the root cause of that problem?
The issue stems from the back navigation logic within the `ProfilePage `component, which defaults to the home screen if there's no prior screen in the React Navigation stack. This problem arises when the user navigates to the `ProfilePage `from the IOU confirmation page. As the `ProfilePage `is on a different StackNavigator (`ProfileModalStackNavigator`) than the `MoneyRequestModalStackNavigator`, there's no record of the IOU confirmation page in the React Navigation stack, causing the back button to default to the home screen.

### What changes do you think we should make in order to solve the problem?
1. Add the `ProfilePage `component to the `MoneyRequestModalStackNavigator `in the `ModalStackNavigator `page. This change ensures that when a user clicks on the profile icon in the IOU confirmation, they are redirected to the `ProfilePage `within the `MoneyRequestModalStackNavigator`. This will require modifications to the `MoneyRequestConfirmationList `component and related routing files.

2. Introduce a new **fallbackRoute** property that can be passed to the `ProfilePage `component. This property specifies the route to navigate to when the back button is pressed, if there's no prior route in the navigation stack.

The back navigation code would be updated as follows:
```
<HeaderWithBackButton
    title={props.translate('common.profile')}
    onBackButtonPress={() => Navigation.goBack(props.fallbackRoute || ROUTES.HOME)}
/>
```
This snippet would be added to the `MoneyRequestModalStackNavigator `component in the `ModalStackNavigators `file:
```
{
    getComponent: () => {
        const ProfilePage = require('../../../pages/ProfilePage').default;
        const WrappedComponent = React.forwardRef((props, ref) => {
            return (
                <ProfilePage
                    ref={ref}
                    {...props}
                    fallbackRoute={ROUTES.getProperRoute(arg1, arg2)}
                />
            );
        });
        return WrappedComponent;
    },
}

```

These changes ensure that if a user is on the `ProfilePage `and presses the back button, they are correctly navigated back to the IOU confirmation page.

Please find the attached video demonstrating the proposed solution:

https://github.com/Expensify/App/assets/65986357/5bb552f3-16ac-4d15-98a8-125671838344

**Comment by muttmuure** [comment] 2023-07-19 11:58
@abdulrahuman5196 @ygshbht's proposal looks promising. Could you take a look?

**Comment by sababer9** [comment] 2023-07-19 13:05
My suggested options for fix:
- Open profile in an on-page popup or hover/popup while requesting cash OR
- When vieweing the profile while requesting money, the Url should not just change to profile Url but a new Url that has both Request cash and profile info, so that when it is refreshed, App loads the process where it was left

**Comment by abdulrahuman5196** [comment] 2023-07-24 12:37
Will check this in a while

**Comment by abdulrahuman5196** [comment] 2023-07-26 16:10
Sorry for the delay. Will close other review today,

**Comment by abdulrahuman5196** [comment] 2023-07-31 18:56
@ygshbht On the proposal here https://github.com/Expensify/App/issues/22802#issuecomment-1636899904

How do you intend to get the fallback route on refresh? Profile page has lots of ingress, so do we find the last route initiated?

What is the `ROUTES.getProperRoute(arg1, arg2)`

**Comment by ygshbht** [comment] 2023-07-31 19:11
@abdulrahuman5196 
The profile page will have another new route and will be imported again in `MoneyRequestModalStackNavigator`
Thew new route can be defined in the `ROUTES.js` file

![image](https://github.com/Expensify/App/assets/65986357/4d79f049-7445-4b00-9eec-81125aff68c9)

Some components that are imported multiple times in [ModalStackNavigators.js](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/ModalStackNavigators.js) include:
`AddPersonalBankAccountPage` `AddDebitCardPage ` `EnablePaymentsPage` etc.

![image](https://github.com/Expensify/App/assets/65986357/65b7ae8c-3c59-45ee-9642-597e679726f8)



Regarding `ROUTES.getProperRoute(arg1, arg2)`
This will give you the new route address that you crated for the Profile Page. It is similar to the get funcitons `getBankAccountRoute` `getSettingsAddLoginRoute` defined in the `ROUTES.js`

**Comment by ygshbht** [comment] 2023-07-31 19:24
@abdulrahuman5196 You can see the new routes i used in the video i have attached https://github.com/Expensify/App/issues/22802#issuecomment-1636899904

**Comment by abdulrahuman5196** [comment] 2023-08-03 15:53
Will do a another review morning

**Comment by abdulrahuman5196** [comment] 2023-08-06 15:52
@ygshbht I don't understand why do we need to 

>This snippet would be added to the MoneyRequestModalStackNavigator component in the ModalStackNavigators file:

This issue is basically we are providing goback(HOME) screen as fallback route and it causes to go to home screen when there is no previous screen. So we basically have to provide valid goBack() route so that it goes to request confirmation page properly.

Maybe you could also take reference from `MoneyRequestDescriptionPage` which works fine

**Comment by ygshbht** [comment] 2023-08-06 16:44
> @ygshbht I don't understand why do we need to
> 
> > This snippet would be added to the MoneyRequestModalStackNavigator component in the ModalStackNavigators file:
> 
> This issue is basically we are providing goback(HOME) screen as fallback route and it causes to go to home screen when there is no previous screen. So we basically have to provide valid goBack() route so that it goes to request confirmation page properly.
> 
> Maybe you could also take reference from `MoneyRequestDescriptionPage` which works fine

@abdulrahuman5196 Exactly! The necessity stems from our need to specify a fallback route by incorporating the `ProfilePage` into the `MoneyRequestModalStackNavigator`.

Several pages redirect to the `ProfilePage`. When you're on the `ProfilePage` and perform a refresh, the history gets lost in the app. This results in a fallback to the `HOME` screen when attempting to `go back`. To ensure proper fallback behavior, we must assign another `route` to the `ProfilePage` so it's aware of its origin.

The `MoneyRequestDescriptionPage` redirects back to a page that's set as its fallback route:
https://github.com/Expensify/App/blob/4230f289341c8d6d9a8b780d54da0725d4764b2b/src/pages/iou/MoneyRequestDescriptionPage.js#L76-L78

We need to implement a similar strategy for the `ProfilePage`: providing it with a `fallbackRoute`. However, we shouldn't hardcode it within the `ProfilePage` since there are several pages that could lead to the `ProfilePage`. Instead, we should pass this from the flow it belongs to, which in this context is the `MoneyRequestModalStackNavigator`.

**Comment by ygshbht** [comment] 2023-08-06 16:46
@abdulrahuman5196 If it's okay here and you don't mind, I'd be more than happy to discuss this over a call to clarify any doubts

**Comment by abdulrahuman5196** [comment] 2023-08-06 17:47
@ygshbht I agree on having a fallback route.

>We need to implement a similar strategy for the ProfilePage: providing it with a fallbackRoute. However, we shouldn't hardcode it within the ProfilePage since there are several pages that could lead to the ProfilePage


But I am not seeing a reason to add it in the `MoneyRequestModalStackNavigator` 

We have a similar requirement in `IOUCurrencySelection` page where we use `backTo` prop. Won't we be able to use the same? Any reason we need to add it in `MoneyRequestModalStackNavigator`

**Comment by ygshbht** [comment] 2023-08-06 18:02
@abdulrahuman5196  We can certainly implement something similar to what is done in `IOUCurrencySelection` 
https://github.com/Expensify/App/blob/1c8f9353f1d3d4a14c0e9c23a5f5299aec36f17f/src/pages/iou/IOUCurrencySelection.js#L83-L89

It ultimately comes down to your preference.

From my perspective, it's preferable to keep this logic outside of the `ProfilePage`. The primary reason is that determining where the `ProfilePage `came from isn't inherently the responsibility of the `ProfilePage `itself. It's more about the components managing navigation. However, if you believe that incorporating the logic directly into the `ProfilePage `is more suitable, I'm open to that approach as well.

**Comment by abdulrahuman5196** [comment] 2023-08-06 18:10
>We can certainly implement something similar to what is done in IOUCurrencySelection
It ultimately comes down to your preference.

Its not my preference actually. What is the best approach and consistent with the existing codebase is what we try to review.

Can you update your proposal with this as alternate solution? I am not super inclined on adding to `MoneyRequestModalStackNavigator`

**Comment by ygshbht** [comment] 2023-08-06 18:11
Sure! Give me 5 mins

**Comment by ygshbht** [comment] 2023-08-06 18:55
## Proposal

[Updated](https://github.com/Expensify/App/issues/22802#issuecomment-1636899904)

@abdulrahuman5196

**Comment by muttmuure** [comment] 2023-08-09 20:42
@abdulrahuman5196 just waiting on your feedback to [this comment](https://github.com/Expensify/App/issues/22802#issuecomment-1666944262)

**Comment by abdulrahuman5196** [comment] 2023-08-13 07:42
Created a thread on confirmation of path forward - https://expensify.slack.com/archives/C01GTK53T8Q/p1691912177038759

**Comment by abdulrahuman5196** [comment] 2023-08-13 13:01
@ygshbht Meanwhile your solution was working for this issue, but if we press back on the profile page opened from different origin, it is crashing.

**Comment by ygshbht** [comment] 2023-08-13 13:10
@abdulrahuman5196 Can you share the code or video/ error?

**Comment by abdulrahuman5196** [comment] 2023-08-18 18:02
Hi, I got the response on the slack couple days back and its fine for us to go with the proposed change

**Comment by abdulrahuman5196** [comment] 2023-08-18 18:04
@ygshbht 's alternate proposal here https://github.com/Expensify/App/issues/22802#issuecomment-1636899904 looks good. We should use the `backTo` param option similar to currency selection page.

🎀 👀 🎀
C+ Reviewed

**Comment by NikkiWines** [comment] 2023-08-21 17:50
Nice, agreed using `backTo` here as well makes sense 👍

**Comment by NikkiWines** [comment] 2023-08-21 17:53
Oh, hmm - I guess cause this was internal it didn't update accordingly. Let me adjust the labels and re-assign

**Comment by ygshbht** [comment] 2023-08-21 17:54
Thanks! I'll have the PR ready in a day

**Comment by ygshbht** [comment] 2023-08-22 07:47
@abdulrahuman5196  I've created the [PR](https://github.com/Expensify/App/pull/25658). As of now I've been unable to run android emulator. I'll post video on Android web/ Android native as soon as the emulator runs. Thanks!

**Comment by abdulrahuman5196** [comment] 2023-09-04 10:24
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. But this has been the case during implementation/navigation refractor.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Go to FAB> Request money
2) Enter the amount you want to request
3) Select any user
4) Click the avatar to open the profile section
5) Refresh the page and select the back button to go back to "Request money-cash" page to continue requesting
6) Verify you can go back to request confirmation and not home page

**Comment by ygshbht** [comment] 2023-09-15 06:43
@muttmuure @NikkiWines The payment is long overdue :(

**Comment by NikkiWines** [comment] 2023-09-18 08:48
Yep, I've reached out to @muttmuure to get that started. Sorry for the delay @ygshbht 

@abdulrahuman5196, could you please complete [this checklist](https://github.com/Expensify/App/issues/22802#issuecomment-1696129878)? Once that's done I believe we can officially close this one out.

**Comment by abdulrahuman5196** [comment] 2023-09-18 08:50
Checklist is already completed here https://github.com/Expensify/App/issues/22802#issuecomment-1705009019

**Comment by ygshbht** [comment] 2023-09-18 08:50
No problem. I also tried to apply for the Upwork job but it is no longer available

**Comment by muttmuure** [comment] 2023-09-19 05:39
Offer sent to @ygshbht

**Comment by ygshbht** [comment] 2023-09-19 05:40
Accepted!

**Comment by muttmuure** [comment] 2023-09-19 05:44
Huge - paid

**Comment by muttmuure** [comment] 2023-09-19 05:45
@ygshbht - $1500
@abdulrahuman5196  - $1500
@Yokabdk - $250

**Comment by Yokabdk** [comment] 2023-09-19 07:52
@muttmuure I couldn't apply for the reporting bonus because it's not available. here is my upwork profile https://www.upwork.com/freelancers/~01e63a00357238a4b6

**Comment by muttmuure** [comment] 2023-09-19 08:11
Offer sent

**Comment by muttmuure** [comment] 2023-09-19 08:15
Offer sent to @abdulrahuman5196

**Comment by Yokabdk** [comment] 2023-09-19 08:17
@muttmuure offer accepted

**Comment by abdulrahuman5196** [comment] 2023-09-19 08:46
@muttmuure accepted

**Comment by muttmuure** [comment] 2023-09-21 06:40
Everyone has been paid

**Closed by muttmuure** 2023-09-21 06:40 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
