### ISSUE TITLE
[HOLD for Payment OCT 08] [$250] [Search v2.3] - Default name is not displayed correctly for multiline system message thread

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49330] opened 2024-09-17 09:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Submit an expense with a multiline description.
4. Go to transaction thread.
5. Click Description.
6. Edit the description while maintaining the multiline format and save it.
7. Right click on the system message > Reply in thread.
8. Send a reply in thread.
9. Go to Search > Chats.
10. Click Filters > Select "In".
11. Select the thread in Step 8 > Save.
12. Click Save search.

## Expected Result:
The title of the saved search should only have one line.

## Actual Result:
The title of the saved search has multiple lines and it is not displayed correctly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ada2fbd2-fe7c-442a-a7f1-080bbdbbaa1b

<img width="1440" alt="Bug6606270_1726554285396!Screenshot_2024-09-17_at_14 22 04" src="https://github.com/user-attachments/assets/99c9ea5b-8764-4671-a0c5-612b61c33117">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836683698134866207</li>
        <li>Upwork Job ID: 1836683698134866207</li>
        <li>Last Price Increase: 2024-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 104047003</li>
<li>Krishna2323 | Contributor | 104047004</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by IuliiaHerets** [comment] 2024-09-17 09:43
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment] 2024-09-17 09:43
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CyberAndrii** [comment] 2024-09-17 10:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Saved search - Default name is not displayed correctly for multiline system message thread

### What is the root cause of that problem?

The title text is not wrapped correctly.

### What changes do you think we should make in order to solve the problem?

Add `titleStyle: styles.textNoWrap,` here

https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/pages/Search/SearchTypeMenu.tsx#L110

**Comment by drminh2807** [comment] 2024-09-17 10:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Saved search - Default name is not displayed correctly for multiline system message thread

### What is the root cause of that problem?
The title text is not wrapped correctly.

### What changes do you think we should make in order to solve the problem?
add `numberOfLinesTitle: 2,` in
https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/pages/Search/SearchTypeMenu.tsx#L108-L117

### What alternative solutions did you explore? (Optional)
add noWrap style
`titleStyle: styles.textNoWrap,`

**Comment by truph01** [comment] 2024-09-18 04:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The title of the saved search has multiple lines and it is not displayed correctly.

### What is the root cause of that problem?
- We return the raw report name in this:
https://github.com/Expensify/App/blob/7bd9e53edfd2508dd4584e1db97fbf7a69f8a646/src/libs/SearchUtils.ts#L715

so the saved search name can contain multiple lines.
### What changes do you think we should make in order to solve the problem?
- We can fix the issue by fixing the Text style, but with that approach, we need to apply the fix on all platforms. So I suggest that we can format this:

https://github.com/Expensify/App/blob/7bd9e53edfd2508dd4584e1db97fbf7a69f8a646/src/libs/SearchUtils.ts#L715

so it can be:

```
        return ReportUtils.formatReportLastMessageText(ReportUtils.getReportName(reports?.[`${ONYXKEYS.COLLECTION.REPORT}${filter}`]));
```

like we did in this:

https://github.com/Expensify/App/blob/7bd9e53edfd2508dd4584e1db97fbf7a69f8a646/src/components/DisplayNames/DisplayNamesWithTooltip.tsx#L59

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-09-19 15:12
@paultsimura What do you think about my solution, which just needs to use ```ReportUtils.formatReportLastMessageText``` without any style changes? Thank you.

**Comment by truph01** [comment] 2024-09-19 16:05
@paultsimura Please note we need to fix the search header page with that solution as well:

![image](https://github.com/user-attachments/assets/b5524211-4c0b-4e1f-99c1-07dbcb64d4c5)

**Comment by shawnborton** [comment] 2024-09-20 08:29
It should only be 1 line and then truncated but why is it not occupying more horizontal space? There's a lot more space over on the right that it could be using.

**Comment by shawnborton** [comment] 2024-09-20 08:44
Ah nice, that's much better

**Comment by luacmartins** [comment] 2024-09-26 02:14
PR merged

**Comment by abekkala** [comment] 2024-10-02 18:02
### PAYMENT SUMMARY FOR OCT 08

- Fix: @Krishna2323 [$250, if no regressions] [OFFER](https://www.upwork.com/nx/wm/offer/104047004)
- PR Review: @paultsimura [$250, if no regressions] [OFFER](https://www.upwork.com/nx/wm/offer/104047003)
Please complete checklist below

**Comment by abekkala** [comment] 2024-10-02 18:03
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ]  [@paultsimura] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@paultsimura] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@paultsimura] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.
- [ ]  [@paultsimura] Determine if we should create a regression test for this bug.
- [ ]  [@paultsimura] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ]  [@abekkala] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by abekkala** [comment] 2024-10-08 15:42
@Krishna2323 @paultsimura payments sent and contracts ended - thank you! 🎉

**Closed by abekkala** 2024-10-08 15:42 UTC
Labels: Reviewing, External, Weekly, Bug
