### ISSUE TITLE
HIGH: [Reliability] Unread/Read status failed to sync between devices due to missing API call

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#37324] opened 2024-02-27 17:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-20
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  
**Email or phone of affected tester (no customers):** mattmo2025@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @muttmuure 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708968443611769

## Action Performed:

1. On Android client and Web client, open the same user account
2. On Web mark multiple messages in the Chat unread
3. On Web, mark the parent message in the LHN option list unread
4. On Android, observe the read/unread status of the same chat in the LHN
5. Repeat until the status is not updated on the Android device

## Expected Result:
The status should succeed in syncing from server to client 100% of the time
 
## Actual Result:
The Android client failed to receive the updates from the server, or the server failed to receive the updates from the Web client

## Workaround:
Refresh the app

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/46995600/c7036f67-3266-4803-965a-bffa0ac37c33

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment] 2024-02-27 17:28
Adding logs

[Web logs-2024-02-26 16_58_14.681.txt](https://github.com/Expensify/App/files/14423560/Web.logs-2024-02-26.16_58_14.681.txt)
[Android logs-2024-02-26_16_56_52.028-2024-02-26 16_58_02.553.txt](https://github.com/Expensify/App/files/14423561/Android.logs-2024-02-26_16_56_52.028-2024-02-26.16_58_02.553.txt)

**Comment by muttmuure** [comment] 2024-02-27 17:31
Gonna snag this one as I'm actively testing it and sharing logs

**Comment by muttmuure** [comment] 2024-03-05 11:35
I think that the [Missing Cors Headers](https://expensify.slack.com/archives/C06M8ERLNMV) issue is actually to blame here. I only experienced this missing API call bug on web, and it’s probably due to some WARP rate-limiting issue.

When I tested mobile to mobile it worked 100% fine after about an hour of testing

**Comment by muttmuure** [comment] 2024-03-06 19:08
OK, we had some feedback that CORS is not to blame here. I think the next step is to test that theory but also to try to reproduce it again with some tests.

**Comment by danieldoglas** [comment] 2024-03-18 16:54
No updates on this one yet, need to finish other tasks before I can look into it

**Comment by danieldoglas** [comment] 2024-04-02 09:29
@muttmuure [cannot reproduce](https://expensify.slack.com/archives/C0671JDRKQW/p1711797194203419?thread_ts=1709607733.180039&cid=C0671JDRKQW) this anymore, so closing it!

**Closed by danieldoglas** 2024-04-02 09:29 UTC
Labels: Engineering, Weekly, Bug
