### ISSUE TITLE
[HOLD for payment 2023-08-07] [$1000] Android - Copy icon is not aligned with other texts

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22259] opened 2023-07-05 11:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App on Android phone
2. Click on avatar to open settings menu > Profile > Contact methods

## Expected Result:
Copy icon should get aligned with other texts (like [on iOS](https://github.com/Expensify/App/issues/22259#issuecomment-1625112339))

## Actual Result:
Copy icon is not aligned with other texts

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.35-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a2512fd2-3cba-4045-bf3a-155660bc5a7e

![Screenshot from 2023-07-04 16-32-24](https://github.com/Expensify/App/assets/93399543/6c4d4ed1-a055-4f36-b8ec-08319424191f)
![Screenshot from 2023-07-04 16-32-15](https://github.com/Expensify/App/assets/93399543/0069fb03-2745-4cc5-9863-05902dffd0c9)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @muxriddinmuqimov77
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688470298151389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01294f4a678e2bc1c2</li>
        <li>Upwork Job ID: 1678413644500803584</li>
        2023-07-17<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li> |  | 0</li>
<li> |  | 0</li>
</ul></li>
    </ul>
</details>

**Comment by DanutGavrus** [comment] 2023-07-05 14:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Copy icon is not aligned with other texts

### What is the root cause of that problem?  

https://github.com/Expensify/App/blob/f9a8529f18696b2584d57c960933cefdf7b2e6af/src/components/Pressable/PressableWithDelayToggle.js#L109-L123  

Our `Icon` is a child of `PressableWithoutFeedback` which has no `height` set and which is inside `PressableWithDelayToggle.js component` which is inside `CopyTextToClipboard.js component` which is inside `ContactMethodsPage.js component`. Here, we may see that our `Icon` is a grand-child of a `Text`:  

https://github.com/Expensify/App/blob/f9a8529f18696b2584d57c960933cefdf7b2e6af/src/pages/settings/Profile/Contacts/ContactMethodsPage.js#L121-L128  

1. The `Text` has the default `defaultProps` of `fontSize: variables.fontSizeNormal` which is `getValueUsingPixelRatio(15, 21)`, on my tests I've got `15px`;
2. Our `Icon` has the `height={variables.iconSizeSmall}` which has the value of `16px`.
3. The text is in *lowercase* so it appears even smaller.

I think this is an issue for all platforms as the icon is too big comparing to the surrounding text.

### What changes do you think we should make in order to solve the problem?
We should replace the `height={variables.iconSizeSmall}` of our `Icon` to `getValueUsingPixelRatio(15, 21) - x`(3 for example, which in my tests becomes `12px`). We should also replace the `width` with the same value to keep the aspect ratio.

Before:
![image](https://github.com/Expensify/App/assets/56603839/bde25f4b-feeb-4edc-b3dc-085f03c871e6)

After:
![image](https://github.com/Expensify/App/assets/56603839/86a6bef7-7ca5-4937-8f4e-70641648c8a7)

**Comment by DrLoopFall** [comment] 2023-07-05 19:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy icon is not aligned with the text

### What is the root cause of that problem?
By default, the inline element(copy icon) aligns with the baseline of text, so it appears offset from the text, which may not be desired.

### What changes do you think we should make in order to solve the problem?
Align the center of the text with the center of the icon, which looks more desirable and aligned.

Add `styles.dInlineFlex` and `styles.alignItemsCenter` to `CopyTextToClipboard`
```js
<PressableWithDelayToggle
    styles={[styles.dInlineFlex, styles.alignItemsCenter]}
```
or add the styles to `PressableWithDelayToggle` itself.

![Screen Shot 2023-07-06 at 00 19 54 Cropped](https://github.com/Expensify/App/assets/120749263/5fa24130-6f6f-4af7-a94c-95d285a44311)

**Comment by DrLoopFall** [comment] 2023-07-05 19:41
Also, I think the icon size should be based on the device pixel ratio.

**Comment by conorpendergrast** [comment] 2023-07-07 09:03
Ah yikes, I missed this on Wednesday, sorry! Reviewing tnow

**Comment by conorpendergrast** [comment] 2023-07-07 09:15
Yeah you can see on Android the verticle alignment is slightly higher, and it's bumping against the text in the line above

| Android  | iOS |
| ------------- | ------------- |
| <img width="309" alt="image" src="https://github.com/Expensify/App/assets/5802477/527a7127-cbe4-48ea-90d6-d4294d79f8be"> | <img width="309" alt="image" src="https://github.com/Expensify/App/assets/5802477/8b225b24-c07c-4492-af22-e4ac839cb008"> |


@Expensify/design Any desired outcome here?

**Comment by shawnborton** [comment] 2023-07-07 12:50
The iOS style would be the desired outcome.

**Comment by umair-outlier** [comment] 2023-07-11 20:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The copy icon is not aligned with the text on android OS on contact method page

### What is the root cause of that problem?
Icon is given a `absolute` position with value of `top: 2`, that is why icon is not appearing in line with the text and slightly hovers above

### What changes do you think we should make in order to solve the problem?

we should change `top: 2` to `top: 3` in  [IconWrapperStyles -> index.js](https://github.com/Expensify/App/blob/main/src/components/Icon/IconWrapperStyles/index.js) I propose this solution because this file is only used in one component, which is in question right now so changing this file won't have affect on other areas, also it is the most simple change as well. 

- Tested on IOS - Simulator Iphone 14 ✅ 
- Tested on Android - Emulator Google Pixel 
- Tested on Android - real device - Samsung A52

Before: 
<img width="383" alt="Screenshot 2023-07-12 at 1 28 32 AM" src="https://github.com/Expensify/App/assets/72895478/26dbd2b4-4d9e-4df4-bc50-675ade7df9e4">

After:
<img width="376" alt="Screenshot 2023-07-12 at 1 26 43 AM" src="https://github.com/Expensify/App/assets/72895478/5652545d-a71b-42fb-9c02-1e3063acf5ad">



### What alternative solutions did you explore? (Optional)
- I explored drilling down styles to get the icon in line
- alternative solution I explored was to pass in `additionalStyles` prop to icon component as it accepts it already


**Additionally found a small issue**:  we provide `style` prop to Icon component, but Icon component does not make use of `props.style` anywhere, instead it uses `props.additionalStyles` so we can remove this `style` prop from [here](https://github.com/Expensify/App/blob/85739ea075b554a5a15c8750f2d92bed27005f2f/src/components/Pressable/PressableWithDelayToggle.js#L120) 

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by umair-outlier** [comment] 2023-07-11 20:59
Contributor details
Your Expensify account email:  umairahmedbajwa97@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ef6da402835a55e6

**Comment by DanutGavrus** [comment] 2023-07-14 10:18
@rushatgabhane 
> 2. If we scale all icons with the text, the app will look really weird.  

That's right.

> 1. Why apply the scaling to only some icons? Why not Avatar, and other design elements.  

This icon seems different as this has text on left & right, it's an icon *inline with the surrounding text*. That's why I think it might be a good idea *for this one* to have it's `height` related to the `line-height` of the text.  

The text's `font-size` does not exceed the `line-height`, otherwise the text would get cropped. On devices which get the **lowest** values for the text properties, the image retains its `fixed height` and does not get cropped. Thus, it may *overlap* the text above or under, as per this issue.

Correct me if I'm wrong though 😁

**Comment by conorpendergrast** [comment] 2023-07-17 17:59
Looks like proposals are being discussed at the moment. Progress!

**Comment by conorpendergrast** [comment] 2023-07-19 20:57
@rushatgabhane Anything more on proposal reviews here?

**Comment by rushatgabhane** [comment] 2023-07-24 15:43
@DrLoopFall can we remove `top` property  and use your proposal?

https://github.com/Expensify/App/blob/9dd3a3ff1d82c944bb0e5d631511348107734e7a/src/components/Icon/IconWrapperStyles/index.js#L1

**Comment by DrLoopFall** [comment] 2023-07-24 15:45
@rushatgabhane, sure I'll remove it in the PR.

**Comment by rushatgabhane** [comment] 2023-07-24 15:45
Will it work for all platrforms?

**Comment by DrLoopFall** [comment] 2023-07-24 15:45
Yes

**Comment by rushatgabhane** [comment] 2023-07-24 15:50
nice! i like @DrLoopFall's [proposal](https://github.com/Expensify/App/issues/22259#issuecomment-1622321481) 
🎀 👀 🎀

**Comment by hayata-suenaga** [comment] 2023-07-24 16:14
assigning @DrLoopFall

**Comment by DrLoopFall** [comment] 2023-07-24 18:52
Hi @rushatgabhane and @hayata-suenaga,
While implementing the solution, I looked deeper and found the real root cause of the problem, the `inline` property was missing from the `Icon` (looks like it was somehow missed in this commit 152daf1b77fd656f27490bde8676045021d27a71).

So just adding `inline={props.inline}`, would solve the issue.
Also, we can't remove the `top`, we have to retain it, sorry for the confusion earlier.

I've updated my [proposal](https://github.com/Expensify/App/issues/22259#issuecomment-1622321481) accordingly, and have checked in all the supported platforms, it just works totally fine.
If you think the solution is good, I can make a PR now.

**Comment by DrLoopFall** [comment] 2023-07-25 11:40
Thank you,
I've made PR #23541, and it's ready for review.

**Comment by conorpendergrast** [comment] 2023-08-02 15:12
@DrLoopFall Could you please confirm your Upwork profile URL? 

@muxriddinmuqimov77 Please could you apply to [this Upwork job](https://www.upwork.com/jobs/~01294f4a678e2bc1c2) to make sure you get paid the bug bounty?

**Comment by DrLoopFall** [comment] 2023-08-02 15:15
Hi @conorpendergrast
Here's my Upwork profile https://www.upwork.com/freelancers/~01c8c2835e5319aa72

**Comment by muxriddinmuqimov77** [comment] 2023-08-02 16:59
https://github.com/conorpendergrast I applied for a Job on Upwork

**Comment by rushatgabhane** [comment] 2023-08-03 04:53
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment] 2023-08-03 04:57
Created a manual request - https://staging.new.expensify.com/r/8613046851814433

**Comment by conorpendergrast** [comment] 2023-08-07 15:54
## Payouts due:

- [ ] Issue Reporter: $250 @muxriddinmuqimov77 
- [ ] Contributor: $1000 + 50% urgency bonus @DrLoopFall 
- Contributor+: $1000 + 50% urgency bonus @rushatgabhane [via NewDot](https://staging.new.expensify.com/r/8613046851814433)

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/22259#issuecomment-1652379225)

Upwork job is [here](https://www.upwork.com/ab/applicants/1678413644500803584/job-details).

**Comment by conorpendergrast** [comment] 2023-08-07 15:57
All done and closing out. Thanks!

**Closed by conorpendergrast** 2023-08-07 15:57 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-08 03:32
Reviewed the payment details for @rushatgabhane. This is approved for payment on NewDot.
