### ISSUE TITLE
[$500] Chat - Mention suggestion list doesn't close on new line break if @text matches any user name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36617] opened 2024-02-15 18:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4319148
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to New Expensify
2. Enter "@<any user name>" in compose box, in my case "@andres"
3. Create numerous line breaks by holding SHIFT+ENTER keys
4. Delete line breaks added in previous step by holding BACKSPACE key

## Expected Result:
Either mention suggestions list should close when adding new line breaks, or it should stick to the top of compose box

## Actual Result:
Mention suggestions list does not close when adding line breaks, so it is displayed in the middle of the compose box if it's height exceeds list position
After deleting line breaks the list jumps above compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3341ee04-04fc-4dd3-8211-aebfe1da2bad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3bd6566bb964b48</li>
        <li>Upwork Job ID: 1758196770938699776</li>
        <li>Last Price Increase: 2024-02-15</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-15 18:29
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by bernhardoj** [comment] 2024-02-16 08:04
I think this is dupe of https://github.com/Expensify/App/issues/35518

**Comment by abdulrahuman5196** [comment] 2024-02-16 16:14
> I think this is dupe of #35518

Yup. this is a dupe. We can close out this.

**Comment by sonialiap** [comment] 2024-02-19 16:35
Closing as dupe

**Closed by sonialiap** 2024-02-19 16:35 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
