### ISSUE TITLE
[HOLD for payment 2024-02-20] [LOW] Drafts: Migrate the next steps to client side wherever it makes sense

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28771] opened 2023-10-03 23:59 UTC
Part of https://github.com/Expensify/Expensify/issues/308213

Coming from [here in the doc](https://docs.google.com/document/d/1vZtGpW_Fy-Wq_R6gvnjdmWVA86FnR42y3LtnNA--vcY/edit?pli=1#bookmark=id.m0j5o9fufhkn), we are planning to migrate some of the next steps which make sense to do so to be client side/ optimistic.

**Comment by greg-schroeder** [comment] 2023-11-13 18:34
I think this one might go to @rezkiy37 per slack discussion

**Comment by greg-schroeder** [comment] 2023-11-20 21:59
Can you comment on this issue @rezkiy37?

**Comment by rezkiy37** [comment] 2023-11-21 09:05
> Can you comment on this issue @rezkiy37?

AFAIK, it is a general issue and does not require any actions now. [Slack thread](https://callstack-hq.slack.com/archives/C02MW39LT9N/p1699666779404299).

**Comment by rezkiy37** [comment] 2023-11-21 09:12
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2023-11-21 09:13
it is still a general issue and does not require any actions now. [Slack thread](https://callstack-hq.slack.com/archives/C02MW39LT9N/p1699666779404299).

**Comment by mountiny** [comment] 2023-11-21 22:17
Yeah I think we actually can focus on other stuff which brings us more value than this right now.

**Comment by mountiny** [comment] 2024-01-04 16:58
Repening now as we are in spot where this makes more sense

**Comment by rezkiy37** [comment] 2024-01-08 10:10
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2024-01-11 17:56
Working on the issue.

**Comment by rezkiy37** [comment] 2024-01-12 16:23
Actively working on the issue. I've opened a [draft PR](https://github.com/Expensify/App/pull/34450), it is not ready for review yet.

**Comment by rezkiy37** [comment] 2024-01-19 17:28
Actively working on the issue.

**Comment by rezkiy37** [comment] 2024-01-22 15:17
@mountiny, I've opened an additional [PR](https://github.com/Expensify/App/pull/34887). Please take a look 🙂

**Comment by rezkiy37** [comment] 2024-01-24 16:18
Integrated last business day logic.

**Comment by mountiny** [comment] 2024-01-24 20:05
@rezkiy37 let me know when its ready for review

**Comment by rezkiy37** [comment] 2024-01-25 17:37
Preparing the PR to review. Writing a description to cover all possible scenarios.

**Comment by rezkiy37** [comment] 2024-01-26 16:25
Finishing with the [draft PR](https://github.com/Expensify/App/pull/34450). Currently, recording videos.

**Comment by rezkiy37** [comment] 2024-01-29 09:51
@mountiny, just opened the PR for review.

**Comment by rezkiy37** [comment] 2024-01-30 13:40
**Regression Test Proposal:**
- Create/have 2 users at least. One of them is a member of workspaces. The 2nd one is an admin.
- Create/have 2 paid workspaces via **OD**: **Collect** and **Control**. The feature does not work for a free workspace.
- Use **OD** to manipulate with the workspaces.

#### 1. Generates an optimistic `nextStep` once a report has been OPENED

##### 1. Self review

1. The member: opens a workspace chat.
2. The member: requests money.
3. The member: Verify that there is a next step with a comment: "_Waiting for **you** to **submit** these expenses._" and label is "Next Steps".

##### 2. Scheduled submit enabled

1. The admin: sets **"Scheduled Submit"** enabled via **OD** in the **"Reports"** section.
2. The admin: selects each value one by one. The label is "Next Steps" and corresponding comments:
- `Daily`: "These expenses are scheduled to **automatically submit later today**! No further action required!";
- `Weekly`: "These expenses are scheduled to **automatically submit on Sunday**! No further action required!";
- `Twice` a month: "These expenses are scheduled to **automatically submit on the 1st and 16th of each month**! No further action required!";
- `Monthly`: "These expenses are scheduled to **automatically submit on the [Selected report submission date] of each month**! No further action required!";
- `Trip`: "These expenses are scheduled to **automatically submit at the end of your trip**! No further action required!";
- `Manual`: "_Waiting for **you** to **submit** these expenses._";
3. The member: requests money.
4. The member: Verify that there is a next step with a corresponding comment mentioned above.

##### 3. Self submitting prevented 

1. The admin: sets **"Prevent Self-Approval"** enabled via **OD** in the **"Members"** section > **"Workflow Enforcement"**.
2. The admin: requests money.
3. The admin: Verify that there is a next step with a comment: "_Oops! Looks like you're submitting to **yourself**. Approving your own reports is **forbidden** by your policy. Please submit this report to someone else or contact your admin to change the person you submit to._" and label is "Next Steps".

#### 2. Generates an optimistic `nextStep` once a report has been SUBMITTED

##### 1. Self review

1. Do steps: **1.3**.
2. The admin: clicks on a **"Submit"** button.
3. The admin: Verify that there is a next step with a comment: "_Waiting for **you*** to **review** these expenses._" and label is "Next Steps".

##### 2. Another reviewer

1. Do steps: **1.1**.
2. The member: clicks on a **"Submit"** button.
3. The member: Verify that there is a next step with a comment: "_Waiting for **[the admin's display name]*** to **approve** these expenses._" and label is "Next Steps".

##### 3. Another owner

1. Do steps: **1.1**.
2. The admin: clicks on a **"Submit"** button.
3. The admin: Verify that there is a next step with a comment: "_**[the member's login]*** is waiting for **you** to **review** these expenses._" and label is "Next Steps" and label is "Next Steps". However, when you are not a manager a verb **review** is replaced with **approve**.

#### 3. Generates an optimistic `nextStep` once a report has been APPROVED

##### 1. Self review

1. Do steps: **1.3** and **2.1**.
2. The admin: clicks on an **"Approve"** button.
3. The admin: Verify that there is a next step with a comment: "_Waiting for **you*** to **review** these expenses._" and label is "Next Steps".

##### 2. Another owner

1. Do steps: **1.1** and **2.3**.
2. The admin: clicks on an **"Approve"** button.
3. The admin: Verify that there is a next step with a comment: "_No further action required!_" and label is "Finished!".

#### 4. Generates an optimistic `nextStep` once a report has been PAID

##### 1. Paid with wallet

1. Do steps: **1.1** and **2.3**, **3.1** or **3.2**.
2. The admin: clicks on a **"Pay elsewhere"** button.
3. The admin: Verify that there is a next step with a comment: "_**You** have marked these expenses as **paid**._" and label is "Finished!".

##### 2. Paid outside of Expensify

1. Do steps: **1.1** and **2.3**, **3.1** or **3.2**.
2. The admin: clicks on a **"Pay with Expensify"** button.
3. The admin: Verify that there is a next step with a comment: "_**You** have marked these expenses as **paid** outside of Expensify._" and label is "Finished!".

- Do we agree 👍 or 👎

**Comment by rezkiy37** [comment] 2024-01-30 13:59
I've updated a value usage because of https://github.com/Expensify/App/issues/35398.

**Comment by mountiny** [comment] 2024-01-30 19:04
Thanks for this update, that will be helpful

**Comment by mountiny** [comment] 2024-01-31 11:23
@allroundexperts taking on the testing

**Comment by allroundexperts** [comment] 2024-01-31 11:24
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Comment by allroundexperts** [comment] 2024-01-31 11:34
> @allroundexperts this is an issue, not the PR

I did realise that instantly and deleted 😆

**Comment by mountiny** [comment] 2024-02-08 18:54
PR in review!

**Comment by rezkiy37** [comment] 2024-02-14 16:44
Just taken the deploy blocker issue. Going to fix it soon.

**Comment by mountiny** [comment] 2024-02-19 20:35
I believe this is going to be ready for a review.

**Comment by mallenexpensify** [comment] 2024-02-21 01:44
Contributor+: @allroundexperts owed $500 via NewDot  

Do we need to update or create a new regression test here? Seems like we might want a new one?

**Comment by allroundexperts** [comment] 2024-02-21 12:14
@mallenexpensify Yep, we'll have to create a new one. The test steps given in the PR description [here](https://github.com/Expensify/App/pull/34450) look comprehensive enough to me. Let me know if you need any help with those.

**Comment by mountiny** [comment] 2024-02-21 12:15
Yep I think we should create new ones here, I have asked @rezkiy37 if he could clean them up for the regression testing purpose

**Comment by allroundexperts** [comment] 2024-02-21 12:17
On a side note, this PR caused a [bug](https://github.com/Expensify/App/issues/36705) so the payment should technically be 1/2. Although, I think this was a complex PR which took me some time to review, so if we can waive the penalty, that would be great. Please let me know.

**Comment by mountiny** [comment] 2024-02-21 12:20
I think that we should not decrease payment because of that. The Cancel Payment was a new feature added along with this so it was hard to notice regression like this

**Comment by mountiny** [comment] 2024-02-21 15:31
@mallenexpensify Michal has actually already written the tests here https://github.com/Expensify/App/issues/28771#issuecomment-1916873382

**Comment by mallenexpensify** [comment] 2024-02-23 22:39
Thanks all! We should be set. TestRail GH is here
- https://github.com/Expensify/Expensify/issues/372499

**Closed by mallenexpensify** 2024-02-23 22:39 UTC
Labels: Daily, NewFeature, Overdue, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-03-02 00:00
$500 approved for @allroundexperts based on [this summary](https://github.com/Expensify/App/issues/28771#issuecomment-1954423267).
