### ISSUE TITLE
Copy icon is not hovered when we hover over at the edge of it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22347] opened 2023-07-06 14:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Click on avatar to open settings menu > Profile > Contact methods
3. Hover the mouse over at the edge of the copy icon
## Expected Result: 
Copy icon should be hovered even we hover over at the edge of it
## Actual Result: 
Copy icon is not hovered when we hover over at the edge of it

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (12).webm](https://github.com/Expensify/App/assets/43996225/2dd6f778-6f21-4a9b-ba82-77bc6acb00e5)

https://github.com/Expensify/App/assets/43996225/9f063181-0f7a-4dee-9fb4-daa0ef14e09a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @muxriddinmuqimov77
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688557412829339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DanutGavrus** [comment] 2023-07-06 14:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy icon is not hovered when we hover over at the edge of it

### What is the root cause of that problem?  
1. Our `Icon` is a child of `PressableWithoutFeedback` which has no `height` so it gets it automatically. `PressableWithoutFeedback` also holds the `hovered state`:
2. https://github.com/Expensify/App/blob/e937c43fc9515dae60a49e9012398ffd5a463c45/src/components/Pressable/PressableWithDelayToggle.js#L109-L127
3. 2. `PressableWithoutFeedback` is a child of `PressableWithDelayToggle` in `CopyTextToClipboard` which has a *higher height* inherited, thus resulting in a gap of **4px** between our `Icon's bottom` and `PressableWithoutFeedback's bottom`.
### What changes do you think we should make in order to solve the problem?
We should add the corresponding `height` to `PressableWithoutFeedback` which would be `Icon's height + 4`. We may pass `props` from the corresponding father if we want to make changes only in the place reported by this issue.

**Comment by DrLoopFall** [comment] 2023-07-06 17:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy icon is not highlighted when hovered at the bottom edge.

### What is the root cause of that problem?
The copy icon is aligned with the baseline of the text, which results in some extra space below the icon(because of the descender, the space below the baseline), which is not a part of the icon, but `PressableWithDelayToggle` which causes the cursor to change to pointer.

### What changes do you think we should make in order to solve the problem?
Stretch the icon to fill the height of the line, add `styles.alignItemsStretch` to the icon
https://github.com/Expensify/App/blob/afaf3371443f24c752a35fdee9e07791094a4b5c/src/components/Pressable/PressableWithDelayToggle.js#L105-L108
```diff
 <Tooltip
-     containerStyles={[styles.flexRow]}
+     containerStyles={[styles.flexRow, styles.alignItemsStretch]}
      text={tooltipText}
 >

**Comment by joekaufmanexpensify** [comment] 2023-07-07 12:14
Discussed in the above thread and decided this is not a bug. Closing!

**Closed by joekaufmanexpensify** 2023-07-07 12:14 UTC
Labels: Daily, Bug
