### ISSUE TITLE
[HOLD for payment 2024-08-02] No "Mark as Cash" button is displayed in Pending Expense

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#43540] opened 2024-06-12 09:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.82-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+pendingreceipt@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Issue reported by:** Applause - Internal Team

## Action Performed:
_**Setup**_

1. Login with applausetester+[pendingreceipt@applause.expensifail.com](mailto:pendingreceipt@applause.expensifail.com)
2. Navigate to Account settings > Wallet
3. Make sure that under Assigned Cards the "Discover" card is assigned under the applause.expensifail domain

If this ^ is not setup, follow these steps:

1. Login with [applausetester@applause.expensifail.com](mailto:applausetester@applause.expensifail.com) or an admin of the domain
2. Navigate to Domain Control > Company Cards
3. Assign a card to the account applausetester+[pendingreceipt@applause.expensifail.com](mailto:pendingreceipt@applause.expensifail.com)

**STEPS to reproduce the issue**
1. Navigate to a workspace transaction that is in pending state
2. Verify a "Mark as cash" button is displayed below the pending state message
1. Click on the "Mark as cash" button
2. Verify the pending state is removed
3. Verify that in the expense transaction thread, there is a system message indicating that you marked the expense as cash, e.g. marked this receipt as cash

## Expected Result:
Mark as cash button should be displayed in the header of the transaction thread when the expense is in pending state

## Actual Result:
Mark as cash button is not displayed.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/44479856/f6faeb17-f3f6-4c05-9e4a-14597b397e65)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment] 2024-06-19 04:37
I went ahead and put this in #wave-control. Yuwen and I are more focused on NetSuite/Intacct implementations this week, though we will circle back to this one soon.

**Comment by JmillsExpensify** [comment] 2024-06-26 04:01
@yuwenmemon it'd be good to get to the bottom of this one once NetSuite/Intacct are farther into implementation.

**Comment by JmillsExpensify** [comment] 2024-07-03 05:05
We're prioritizing higher-value things atm

**Comment by JmillsExpensify** [comment] 2024-07-10 04:25
Still working on higher value things.

**Comment by JmillsExpensify** [comment] 2024-07-16 23:22
@yuwenmemon I think we should start circling back on this one. What do you think?

**Comment by yuwenmemon** [comment] 2024-07-17 00:03
Yep! I'm getting slightly more bandwidth each day outside of NS and Intacct and #fast-apis so taking a look at this soon 🎉

**Comment by yuwenmemon** [comment] 2024-07-18 23:54
@kubabutkiewicz Any idea why the button might not be showing here?

**Comment by yuwenmemon** [comment] 2024-07-18 23:55
@smelaa Any idea why the button would not be showing here? I believe you built out this UI originally...

**Comment by yuwenmemon** [comment] 2024-07-19 00:21
Ah apologies, looks like this is more closely related to work from @BrtqKr - sending a PR for their review.

**Comment by JmillsExpensify** [comment] 2024-08-07 14:24
No payment due and regression tests being added centrally. I'll close this one.

**Closed by JmillsExpensify** 2024-08-07 14:24 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
