### ISSUE TITLE
[$250] Chat - In LHN preview there is no space between quoted text and normal text @thesahindia

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11494] opened 2022-10-01 02:25 UTC
### If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any chat
2. Type > quoted text
3. Press shift + enter and type normal text
4. Send
5. Check the LHN if there's a space after quoted text
6. Refresh and check again

## Expected Result:
There should be a space in LHN

## Actual Result:
The space goes away just after sending the message and gets added after refresh

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.10.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193379402-20cfe42e-4e09-4afc-aef2-1f98f355573b.mp4

https://user-images.githubusercontent.com/93399543/193379409-32a0f2e6-0e64-4f39-9c2d-a61c8b555549.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @thesahindia

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664201097246429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01edbd4e0d1c5a3651
- Upwork Job ID: 1597298848115892224

**Comment by isabelastisser** [comment] 2022-10-12 11:20
I was OOO for the past 3 weeks and catching up now, will review this soon.

**Comment by isabelastisser** [comment] 2022-10-23 01:26
Reviewing this now.

**Comment by isabelastisser** [comment] 2022-10-23 01:34
I was able to reproduce it on the web and mobile.

https://user-images.githubusercontent.com/31258516/197368939-17adf234-93c9-4b96-96a2-60f58d583a3e.mp4

**Comment by isabelastisser** [comment] 2022-10-25 09:35
Hey @mananjadhav , any updates here?

**Comment by tienifr** [comment] 2022-10-27 07:47
It's problem from BE:
when we call API `AddComment` with `reportComment` = `<blockquote>quoted text</blockquote>test`
<img width="586" alt="Screen Shot 2022-10-27 at 14 41 24" src="https://user-images.githubusercontent.com/113963320/198221635-e7c1eddb-0673-4bca-81bd-f3747e279fbd.png">

In https://github.com/Expensify/App/blob/03d7e8f3faba23befb0878b97a66417e492736d1/src/libs/actions/User.js#L313
I logged the result returned from BE:
<img width="783" alt="Screen Shot 2022-10-27 at 14 42 17" src="https://user-images.githubusercontent.com/113963320/198221550-b7bf8eee-d7bc-4497-a5cd-ea0596d7e793.png">

**Comment by mananjadhav** [comment] 2022-10-27 18:02
I agree with what @tienfr pointed out that we're using `lastMessageText`, which trims all the HTML.

@marcaaron I think it is intentional. Do we know the expected behavior here?

**Comment by marcaaron** [comment] 2022-10-28 14:43
>@marcaaron I think it is intentional. Do we know the expected behavior here?

I'm not following. Can you please clarify what you think is intentional or the expected behavior and ask this question another way?

I don't see how this is a problem with the back end. If we are sending a block quote _without a space_ to the API then it seems like an issue with the parameter passed to `AddComment`. @tienifr's screenshot clearly shows we are sending `<blockquote>quoted text</blockquote>test` to the API. Why is there no space there? Seems like a front end issue to me.

**Comment by vladamx** [comment] 2022-10-28 19:53
@marcaaron

I did take a look at this issue last week and parser actually inserts space when striping html tags so when lastMessageHtml goes through parser lastMessageText is properly displayed.

By taking a quick glance i couln't find the exact spot where lastMessageHtml and lastMessageText get de-synced.

I think that actual problem here is that we are duplicating information in state. We can only store lastMessageHtml and calculate lastMessageText where needed. In that way we are sure we don't have de-synced state.

**Comment by marcaaron** [comment] 2022-10-28 21:26
Able to link to some code examples or something @vladamx? I'm having trouble following what you are saying, thanks.

**Comment by isabelastisser** [comment] 2022-10-31 11:12
Hey @vladamx , any updates here as per Marc's request? Thanks!

**Comment by marcaaron** [comment] 2022-10-31 16:07
@isabelastisser not sure why @vladamx was assigned (maybe accidentally). We are still discussing things here.

**Comment by mananjadhav** [comment] 2022-11-01 06:40
I checked again, yeah the issue seems to be on the App side itself. I haven't pin pointed on the App side but the API request is correct and the data received from the API also has the space.

**Comment by isabelastisser** [comment] 2022-11-09 11:29
Not overdue.

**Comment by isabelastisser** [comment] 2022-11-18 14:54
Not overdue. We are still discussing proposals here.

**Comment by allroundexperts** [comment] 2022-11-24 13:46
## Proposal

### Problem

The issue is with the `quote` rule of the `ExpensiMark` library. The `quote` rule is trimming the string after removing the initial `&gt;` (>). This can be seen here:

https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js#L524-L525
Side note: Line 525 is redundant as we're already trimming on line 524.

### Fix
We should either be not trimming the string or just trimming the end of the string. As such, the following changes from:
https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js#L524-L525
to:
```
textSplitted[i] = textSplitted[i].substr(4).trimEnd();
```

On another side note, I think we're trimming the whole string on purpose as highlighted by this comment:
https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js#L148-L150

Although, I am not sure what the reasoning was behind this.

**Comment by mananjadhav** [comment] 2022-11-27 06:40
I don't have the bandwidth to check this. Can we please reassign? @isabelastisser @marcaaron

**Comment by marcaaron** [comment] 2022-11-28 21:12
@aldo-expensify this seems pretty similar to the issue you were working on related to `<br/>` tags [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1669149309886219). 

I think that we could actually simplify a lot of these issues by just only showing on line at a time. Whenever we encounter a `<br/>`, new line, quote, etc instead of combining them we could just show the first line of the last message and not support multi-line messages collapsing into a single line. That would be much simpler and I don't think anyone would greatly favor one over the other.

Also curious what @shawnborton thinks about that idea since it's kind of a design question.

**Comment by shawnborton** [comment] 2022-11-28 21:39
I think I like the idea of only showing on line at a time. But I think it's worth bringing that discussion to Slack to see if others agree as well.

**Comment by marcaaron** [comment] 2022-11-28 21:46
Posted here: https://expensify.slack.com/archives/C01GTK53T8Q/p1669671957761929

**Comment by aldo-expensify** [comment] 2022-11-28 22:19
About the example of this GH issue:

```
> quoted text
normal text
```

the `message[0].html` ends up like: `<blockquote>quoted text</blockquote>normal text`

The `message[0].text` ends up with `quoted textnormal text`, so we can't take the first line anymore from this. An option is that when we convert `message[0].html` to `message[0].text`, we replace `</blockquote>` by `\n` to preserve the line break these blocks cause.

**Comment by aldo-expensify** [comment] 2022-11-28 22:23
Once the `<blockquote>` gets replaced by a `\n` in `message[0].text` it is easier to make [ReportUtils.formatReportLastMessageText](https://github.com/Expensify/App/blob/fedefd12c8ef55040fcdb200e41dc87d3520354a/src/libs/ReportUtils.js#L405-L407) keep everything before the first `\n`

**Comment by marcaaron** [comment] 2022-11-28 22:59
Could we just make our regex for `lastMessageText` cut everything after:

- the first new line
- the first line break element
- before or after a blockquote

?

**Comment by aldo-expensify** [comment] 2022-11-28 23:29
> Could we just make our regex for `lastMessageText` cut everything after:
> 
> * the first new line
> * the first line break element
> * before (if there's anything there) or after a blockquote
> 
> ?

I'm not sure about which regex for `lastMessageText`  are we talking about... are you talking about the `ExpensiMark.htmlToText` and the [group of regexes](https://github.com/Expensify/expensify-common/blob/db2c245c1e6b39232092b1415b9235fadda2a529/lib/ExpensiMark.js#L281-L301) it uses?

Are you suggesting cutting `message[0].html` with a regex to produce `lastMessageText` directly? This would skip calling ExpensiMark.replace [here](https://github.com/Expensify/App/blob/ecb3574bc8aabf42289f91199c04306caece0f4b/src/libs/ReportUtils.js#L628)

Right now, the process seems to be:

- `message[0].html` becomes `message[0].text` by calling ExpensiMark.replace and ExpensiMark.textToHtml on it
- `message[0].text` becomes the `lastMessgeText` by calling ReportUtils.formatReportLastMessageText on it.

**Comment by marcaaron** [comment] 2022-11-29 00:04
To clarify, I was speaking at a high level - I'm not sure where any of this is happening in the code 😄

**Comment by aldo-expensify** [comment] 2022-11-29 20:24
Had a look at `<blockquotes>`, consider this example:

The markdown
```
before quotes
> quoted text
after quotes
```

this translate to the **html** `before quotes<blockquote>quoted text</blockquote>after quotes`. This is fine in my opinion.

Then, the **html** above is transformed by `ExpensiMark.htmlToText` to `before quotes quoted text after quotes`. This is using when copying to clipboard and in the LHN. In my opinion this should have been translated to `before quotes\nquoted text\nafter quotes` (note the line breaks) because `<blockquote>` are block elements and they do cause line breaks when rendered. Doing this change makes it easier to later take only the first line for the LHN and fixes it also for the clipboard.

This update has to be done in `ExpensiMark.htmlToText` regexes and also in the code in the Web API that tries to do the same thing. A final step is to fix [ReportUtils.formatReportLastMessageText](https://github.com/Expensify/App/blob/fedefd12c8ef55040fcdb200e41dc87d3520354a/src/libs/ReportUtils.js#L405-L407) to take only the first line if there are line breaks.

**Comment by marcaaron** [comment] 2022-11-29 23:02
@aldo-expensify can I assign you here? It looks like you're gonna make this change, but not sure. Let me know! 🙇

**Comment by aldo-expensify** [comment] 2022-11-29 23:03
@marcaaron yes!

**Comment by isabelastisser** [comment] 2022-11-30 12:47
@aldo-expensify , there are no proposals and it looks like you're going to fix this, so can I remove the _External_ label and add the _Internal_ label instead?

**Comment by aldo-expensify** [comment] 2022-11-30 21:10
Replaced @eVoloshchak by @rushatgabhane because he is assigned to the [PR](https://github.com/Expensify/App/pull/12968) as C+ reviewer

**Comment by mollfpr** [comment] 2022-12-05 23:14
@isabelastisser accepted, thanks!

**Comment by isabelastisser** [comment] 2022-12-05 23:19
@mollfpr paid! Thanks!

Closing this issue, all set!

**Comment by thesahindia** [comment] 2022-12-06 19:19
@isabelastisser, it's also eligible for reporting compensation.

**Comment by aldo-expensify** [comment] 2022-12-08 17:50
Reopening because there seem to be a [pending payment](https://github.com/Expensify/App/issues/11494#issuecomment-1339465271)

**Comment by isabelastisser** [comment] 2022-12-08 20:12
Thanks for the heads up! To clarify, are @rushatgabhane AND @thesahindia missing payment here?

**Comment by aldo-expensify** [comment] 2022-12-08 21:05
I know that @rushatgabhane is expected to be payed because he reviewed the PR https://github.com/Expensify/App/pull/12968, I don't know about @thesahindia. @thesahindia are you waiting for payment too?

**Comment by thesahindia** [comment] 2022-12-08 21:06
@aldo-expensify, this is eligible for reporting compensation. I reported this.

**Comment by isabelastisser** [comment] 2022-12-10 19:03
@rushatgabhane and @thesahindia, I extended the contract to you in Upwork; please apply, and I will issue the payment.

**Comment by isabelastisser** [comment] 2022-12-14 01:15
@thesahindia paid!

@rushatgabhane please accept the offer and I will hire you and issue the payment in Upwork. Thanks!

**Comment by isabelastisser** [comment] 2022-12-15 19:39
@rushatgabhane paid!

**Closed** 2022-12-15 19:39 UTC
Labels: Reviewing, Daily, Internal, Bug
