### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Distance - Unable to save second distance edit offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38814] opened 2024-03-22 16:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Create a distance request with three waypoints.
4. Go to request details page.
5. Go offline.
6. Click Distance.
7. Drag and drop the waypoints and save it.
8. Repeat Step 6 and 7.

## Expected Result:
User will be able to save the second distance edit.

## Actual Result:
User is unable to save the second distance edit.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e711432a-b5fc-4c2b-aa9d-2c3ec25ad848

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b020e3127d156e8f</li>
        <li>Upwork Job ID: 1772031538674204672</li>
        <li>Last Price Increase: 2024-03-24</li>
<li>Automatic offers: </li>
<ul>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by nkdengineer** [comment] 2024-03-22 17:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is unable to save the second distance edit.

### What is the root cause of that problem?
We prevent the user save the distance if the transaction is loading.

https://github.com/Expensify/App/blob/7f5cf61abb853fe9cdfbbd4711513634aa5a8adf/src/pages/iou/request/step/IOURequestStepDistance.js#L190-L192

So in offline, after the first time we edit the distance, we can't edit this anymore.
### What changes do you think we should make in order to solve the problem?
As the old edit distance flow, we should allow user saving the distance if we're offline event the transaction is loading


```
if (duplicateWaypointsError || atLeastTwoDifferentWaypointsError || hasRouteError || isLoadingRoute || (isLoading && !isOffline)) {
    setShouldShowAtLeastTwoDifferentWaypointsError(true);
    return;
}
```
https://github.com/Expensify/App/blob/7f5cf61abb853fe9cdfbbd4711513634aa5a8adf/src/pages/iou/request/step/IOURequestStepDistance.js#L190-L192

### What alternative solutions did you explore? (Optional)
NA

**Comment by srikarparsi** [comment] 2024-03-24 22:43
This looks external since editing the order of the points does work while offline when creating the request. Opening it up to see if there's any proposals before Monday.

**Comment by nkdengineer** [comment] 2024-03-24 23:08
@srikarparsi What do you think about my proposal?

**Comment by srikarparsi** [comment] 2024-03-25 17:03
Ah looks like @DylanDylann is working on a [fix](https://github.com/Expensify/App/pull/38911)

**Comment by mallenexpensify** [comment] 2024-03-25 18:03
@GandalfGwaihir , you are due compensation. We strive to have processes and documentation to address situations like this and, since we added the External > Help Wanted label and since your code was used in the solution, you should be paid.  Please keeps 👀 on the PR if you can, in case there's any feedback you can offer.  I'll pay 7 days after the PR hits production.

**Comment by mallenexpensify** [comment] 2024-03-25 19:12
PR is actively being worked on so bumped to `Daily`

**Comment by cubuspl42** [comment] 2024-03-26 08:34
I [advised to split the PR](https://github.com/Expensify/App/pull/38911#issuecomment-2019814344) to speed up the processing of this issue.

**Comment by DylanDylann** [comment] 2024-03-26 08:45
@cubuspl42 This PR is ready for review https://github.com/Expensify/App/pull/38987 I will finish screenshot soon

**Comment by cubuspl42** [comment] 2024-03-26 10:50
I'm having trouble with testing anything right now, possibly I was blacklisted by the backend (?), I'm getting `429 Too Many Requests`. [I asked on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1711444749789849).

If this blocker needs urgent handling, we might need some help from the C+ team.

**Comment by cubuspl42** [comment] 2024-03-29 10:47
We're actively working on the PR

**Comment by cubuspl42** [comment] 2024-04-02 13:56
During testing, we found out that the app crashes on Android Native (and possibly iOS Native?) if one re-orders the waypoints while offline. This happens on `main`. I believe that's a serious issue and we should hold this one on the discovered one. I couldn't find an existing GH issue for this problem, so [I reported this on `#expensify-bugs`](https://expensify.slack.com/archives/C049HHMV9SM/p1712065680115269).

**Comment by cubuspl42** [comment] 2024-04-02 15:18
Pros of holding:
- We can re-test the original scenario without workarounds after the crash is fixed
- The QA will be able to use [the provided QA Steps](https://github.com/Expensify/App/pull/38987#issue-2207597287) without encountering a crash 

Cons of holding:
- Not sure if there are any, as the other issue should be a deploy blocker in my opinion

>  I don't think it is related

If performing the testing steps for a solution for issue A triggers a crash (or other undesirable behavior) from issue B, that _makes_ them related. This is the most typical kind of relation between issues I can think of.

**Comment by DylanDylann** [comment] 2024-04-02 15:33
@cubuspl42 The original bug and the discovered one are different totally. I [updated](https://github.com/Expensify/App/pull/38987) test step. Then this point can be resolved

- The QA will be able to use https://github.com/Expensify/App/pull/38987#issue-2207597287 without encountering a crash


About the second point: 
- We can re-test the original scenario without workarounds after the crash is fixed

I don't think it is the workaround. The RCA and solution of the original bug are so clear

**Comment by cubuspl42** [comment] 2024-04-02 15:42
I'm not strongly _against_ merging #38987, but I'm also not sure why are you pushing so hard for merging it right-here-right-now. I'm just being cautious and somewhat uncomfortable with merging something where we have to tip-toe to avoid a crash. I'd prefer to have the crash fixed first.

The strongest argument for fixing issues fast is delivering the fix to the user, but I'd assume this won't happen before the crash is fixed.

If I'm missing something here, you can let me know. Maybe there's some personal reason you'd like to have this merged ASAP?

**Comment by cubuspl42** [comment] 2024-04-02 17:06
I'm not uncomfortable about the bump. I'm uncomfortable with merging PRs whose functionality closely relates to an area with a serious issue (crashing). I know that we didn't introduce the crash (if we did, we'd be fixing it, not holding!), but I'd like to re-test the behavior after the mentioned crashing is fixed, if possible.

>  But this is a deployed blocker

![image](https://github.com/Expensify/App/assets/2590174/64a20d5b-832b-4856-bb00-0cf7f70e00ac)

This is not a deploy blocker anymore; if it was one, we'd be rushing to merge it indeed.

The discovered issue **should be** a deploy blocker, though, in my opinion.

**Comment by cubuspl42** [comment] 2024-04-03 11:32
After rethinking this, I approved the PR, leaving the final decision to the internal engineer.

**Comment by mvtglobally** [comment] 2024-04-12 05:28
Issue not reproducible during KI retests. (First week)

**Comment by abdulrahuman5196** [comment] 2024-04-12 13:38
There is no C+ payment since it's regression fix. And I didn't review the PR.

**Comment by mallenexpensify** [comment] 2024-04-12 22:11
@GandalfGwaihir can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01b020e3127d156e8f

Compensation is 50% of the job price, $250, because authoring a PR and testing wasn't involved.

**Comment by mallenexpensify** [comment] 2024-04-16 23:43
Contributor: @GandalfGwaihir paid $250 via Upwork

Thanks!

**Closed by mallenexpensify** 2024-04-16 23:43 UTC
Labels: External, Engineering, Daily, Awaiting Payment
