### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] Web - Skeleton loader has incorrect spacing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27387] opened 2023-09-13 18:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report, wait for it to load and make sure the skeleton loader is in view.

## Expected Result:
There should be 12px of margin between the fake avatar circle and the fake message lines to the right of it.

## Actual Result:
Currently there is only 8px of margin between the fake avatar and the fake message lines.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (40)](https://github.com/Expensify/App/assets/93399543/f0a4d07d-037b-437e-b8f0-04e3846f0713)

![image (41)](https://github.com/Expensify/App/assets/93399543/b0763ba3-2485-4cbf-9d73-0142d6439329)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694439750361219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100b93c103be50626</li>
        <li>Upwork Job ID: 1702032405100154880</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26722896</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-13 18:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
BUG: Skeleton loader has incorrect spacing
### What is the root cause of that problem?
The four SVG `Rect` beside the avatar have x = 67 as absolute x value, but this value is incorrect.
The correct value should be (avatar width + avatar margin left + avatar margin right) = 40 + 20 + 12 = 72.
https://github.com/Expensify/App/blob/0805f728f962d02eb254de457328f5914d31e9c6/src/components/ReportActionsSkeletonView/SkeletonViewLines.js#L28-L38
### What changes do you think we should make in order to solve the problem?
Replace The four SVG `Rect` x = 72 instead of 67.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by PiyushChandra17** [comment] 2023-09-14 01:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect spacing b/w fake avatar circle and fake messages line to the right of it

### What is the root cause of that problem?
In `SkeletoViewLines` component, we have <Circle> to show fake avatar circle and <Rect> to show fake messages line.

https://github.com/Expensify/App/blob/3e2723cd698bfe1a2318bad7ebc7b43eb6df4b0f/src/components/ReportActionsSkeletonView/SkeletonViewLines.js#L28-L60

According to the calculation:
Rect x - (Circle cx + Circle radius),
67 - (40 + 20) = 7 which is incorrect spacing, it should be 12.

### What changes do you think we should make in order to solve the problem?
Replace all `Rect x` SVG to `72` instead of '67

### What alternative solutions did you explore? (Optional)
NA

**Comment by mallenexpensify** [comment] 2023-09-14 08:38
Reckon this should be an easy fix. I'm unsure about reproducing since I don't know how to differentiate between 8-12 pixels, since Bortman reported the bug and @kbecciv provided a screenshot, I'm assuming you two are _right_. 

@mananjadhav can you review the above propsals?

I unassigned you Mills, I'll manage BZ here.

**Comment by mananjadhav** [comment] 2023-09-17 18:35
@mallenexpensify I checked the pixel distance. 

@dukenv0307's proposal [here](https://github.com/Expensify/App/issues/27387#issuecomment-1718150422) looks good.

🎀 👀 🎀 C+ reviewed.

**Comment by mallenexpensify** [comment] 2023-09-29 16:22
Issue reporter: internal
Contributor: @dukenv0307 paid $750 via Upwork
Contributor+: @mananjadhav due $750 via NewDot. 

@mananjadhav , please complete the BZ checklist above.  Thx

**Comment by mananjadhav** [comment] 2023-10-02 15:35
This spacing issue was added by me in this [PR](https://github.com/Expensify/App/pull/8042). I've also added a comment for the reviewers to see [here](https://github.com/Expensify/App/pull/8042#issuecomment-1743246561).

I don't think we need a regression test for this one.

**Comment by mallenexpensify** [comment] 2023-10-03 19:39
Thanks @mananjadhav closing

**Closed by mallenexpensify** 2023-10-03 19:39 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 21:04
$750 payment approved for @mananjadhav based on BZ summary.
