### ISSUE TITLE
[$500] Profile - Display name is replaced by legal name for new users

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37524] opened 2024-02-29 16:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0

**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create new account
3. Tap settings >> Profile menu
4. Enter legal name & save in Private section
5. Observe Display name in Public section is replaced by legal name
## Expected Result:
Expected, display name should not get replaced by legal name for new users

## Actual Result:
Display name is replaced by legal name for new users

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/b7e41773-4196-4f23-a9c4-1dd4e1a64bba

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d81fb0ecfc9d993</li>
        <li>Upwork Job ID: 1764828022966251520</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-02-29 16:11
@strepanier03 FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by strepanier03** [comment] 2024-03-05 01:40
Okay, moved to `External`. I'll work on adding it to a wave/vip.

**Comment by abzokhattab** [comment] 2024-03-05 01:52
I think this is a backend issue since the backend returns the personal details with the first and last name having the same values as the `legalFirstName` and `legalLastName`

**Comment by strepanier03** [comment] 2024-03-05 03:02
Thanks for the heads up @abzokhattab. @c3024 - You agree with flipping this to `Internal`?

**Comment by c3024** [comment] 2024-03-05 03:45
I think this might be expected behaviour. The display name gets updated with legal name only if the display name is empty (that is never set before and it is by default shown as the email). Changing legal name again after there is a non-default display name does not override the display name.

This looks like expected behaviour to me. If this is indeed considered a bug then yes, this should be fixed from backend and made `Internal`.

@strepanier03

**Comment by c3024** [comment] 2024-03-07 06:07
Updating display name with legal name if display name is empty appears to be the expected behaviour.

However, we might consider updating it optimistically as suggested here [in the proposal](https://github.com/Expensify/App/issues/37524#issuecomment-1978217660) by @dukenv0307 which looks good to me.

 🎀 👀 🎀 C+ Reviewed

**Comment by c3024** [comment] 2024-03-07 06:16
@srikarparsi 

Doing nothing or updating optimistically both look fine. This case of someone updating legal name before display name is rare. Updating display name optimistically in this case for offline cases also does not look super important.

Your call about how we should go about it
1. Do nothing or 
2. Go ahead and fix this with [this proposal](https://github.com/Expensify/App/issues/37524#issuecomment-1978217660).

**Comment by srikarparsi** [comment] 2024-03-07 20:53
I agree, let's do nothing in this case. It looks like expected behavior and the optimistic data doesn't seem too important for this.

**Closed by srikarparsi** 2024-03-07 20:53 UTC
Labels: External, Daily, Help Wanted, Bug
