### ISSUE TITLE
[HOLD for payment 2024-05-22] [$250] [Bug] ActiveClientManager doesn't track the currently active tab well and needs improved

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#40044] opened 2024-04-10 21:28 UTC
# Problem
The purpose of `ActiveClientManager` is to ensure that when there are multiple tabs open, only one tab handles write requests. There are a few bugs with this. 

In order to test this, I used the following diff and then ran `ActiveClientManager.isClientTheLeader()` from the command line.

```
diff --git a/src/setup/addUtilsToWindow.ts b/src/setup/addUtilsToWindow.ts
index d2d11e1384..30419a5eb5 100644
--- a/src/setup/addUtilsToWindow.ts
+++ b/src/setup/addUtilsToWindow.ts
@@ -1,6 +1,7 @@
 import Onyx from 'react-native-onyx';
 import * as Environment from '@libs/Environment/Environment';
 import markAllPolicyReportsAsRead from '@libs/markAllPolicyReportsAsRead';
+import * as ActiveClientManager from '@libs/ActiveClientManager';
 import * as Session from '@userActions/Session';

 /**
@@ -49,5 +50,7 @@ export default function addUtilsToWindow() {
         // Workaround to give employees the ability to mark reports as read via the JS console
         // eslint-disable-next-line @typescript-eslint/no-explicit-any
         (window as any).markAllPolicyReportsAsRead = markAllPolicyReportsAsRead;
+
+        window.ActiveClientManager = ActiveClientManager;
     });
 }
```

### Bug 1: Multiple tabs becoming active
1. Open a single tab (TabA)
2. Verify `isClientTheLeader() === true`
3. Open a second tab (TabB) in the same window
4. Verify `isClientTheLeader() === true`
5. Go back to TabA

Expected result:
`isClientTheLeader() === false` because TabB took over as the new leader

Actual result:
`isClientTheLeader() === true` and both tabs think they are the leader

### Bug 2: If active tab is closed, there are no active tabs
> [!NOTE]
> I was unable to reproduce this because of Bug1. However, once Bug1 is fixed, I think this bug would happen.

1. Have TabA open and be the active client
2. Have TabB open and be a non-active client
3. Close TabA

Expected result: 
Tab B takes over and becomes the new active client

Actual result:
Tab B remains as an inactive client
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e35885da3cd69cf</li>
        <li>Upwork Job ID: 1778173291530903552</li>
        <li>Last Price Increase: 2024-04-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by Skakruk** [comment] 2024-04-11 09:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

I believe Bug 1 is not an issue, since the client becomes the lead once the user activates the tab.
In the test, when we have 2 windows - one per account, and in first window opens 2 tabs, we write from the second account and we can spot that only one is reporting `isClientTheLeader() === true`. 

https://github.com/Expensify/App/assets/1768919/7a7c5494-fa3f-472f-a8cc-1554c868422d

Bug 2 If active tab is closed, there are no active tabs

### What is the root cause of that problem?

Bug 2.

Indeed, when the second tab is closing, we still preserve its `clientID` in Onyx.  But this happens, only when we close the lead tab after navigating to some 3rd party tab. And will not activate the following tab (after closing tab browser will not be focused on the following tab).

The root cause is that the following tab is not receiving updates on active clients. It still handles the list of active clients, which is not the least created one.

### What changes do you think we should make in order to solve the problem?

I propose to add `beforeunload` event listener so that the client will clean up its `clientID` from the list of active clients just before it is closed (or reloaded).

```
window.addEventListener("beforeunload",  () => {
        activeClients = activeClients.filter((id) => id !== clientID);
        ActiveClients.setActiveClients(activeClients);
    });
```

In this case, any of the remaining app tabs will become a leader. And, as a bonus, the `activeClients` list will not grow. 

### What alternative solutions did you explore? (Optional)

**Comment by gitaumoses4** [comment] 2024-04-11 10:07
# Proposal

## Please re-state the problem that we are trying to solve in this issue

ActiveClientManager does not track the current active tab correctly, especially when the active tab is closed.

## What is the root cause of that problem?

### Bug 1

This can be viewed as a bug, or a desired outcome based on what is needed.

If we want the currently active tab to be the client leader - then it works as expected
If we want the newly created tab to be the client leader - then this can be considered a bug.

The currently activated tab by the user, takes in the role of the "Active client". This means that when a user:
1. Opens a single tab (Tab A) - it takes in the role of client leader
2. Opens another tab (Tab B) - it takes in the role of the client leader
3. Switches from Tab B to tab A - Tab A takes in the role of the client leader

This means that we only have one client leader since it's activated when a user opens/reloads the tab.

This happens because the `init` method is invoked on the active tab to make it the client leader.

```javascript
const init: Init = () => {
    activeClients = activeClients.filter((id) => id !== clientID);
    activeClients.push(clientID);
    ActiveClients.setActiveClients(activeClients).then(resolveSavedSelfPromise);
};

```

### Bug 2
When a tab is closed, the clientID is not released from the list of active clients. This causes the other tabs remain in an inactive state.

## What changes do you think we should make in order to solve the problem?

### Bug 1

If we consider this a bug, then we can make the following changes.

```javascript
let isInitialized = false;
const init: Init = () => {
    if( isInitialized ) return;

    activeClients = activeClients.filter((id) => id !== clientID);
    activeClients.push(clientID);
    ActiveClients.setActiveClients(activeClients).then(resolveSavedSelfPromise);
    isInitialized = true;
};

```

This results in the newly created/reloaded tab taking over as the active client as the `init` function is not invoked when the tab is re-activated.

The advantage of this is that the client leader does not keep changing as the user changes tabs, and only when a new tab is created/or an existing one is reloaded.

### Bug 2

When a tab is closed, or the browser window is closed, we can detect this using the `beforeunload` event.

```javascript
window.addEventListener("beforeunload", () => {
    activeClients = activeClients.filter((id) => id !== clientID);
    ActiveClients.setActiveClients(activeClients);
})
```

This will notify other tabs of the release of the currently active tab.
The previously active tab will now take over the role of client leader. (Whether it's a currently active browser tab or not)


## What alternative solutions did you explore? (Optional)

N/A

**Comment by gitaumoses4** [comment] 2024-04-11 10:09
Contributor details
Your Expensify account email: gitaumoses4@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/gitau

**Comment by tgolen** [comment] 2024-04-15 14:36
@Santhosh-Sellavel Will you be able to look at these proposals today?

**Comment by allroundexperts** [comment] 2024-04-15 19:01
Taking over as C+

**Comment by tgolen** [comment] 2024-04-16 16:26
I am not 100% sure about that, no. It sounds like most of the proposals here are able to disprove that theory. It was just what I was able to observe, which isn't actually what was happening.

**Comment by isabelastisser** [comment] 2024-04-19 18:06
@tgolen, do I need to assign a contributor to this issue since it's external?

**Comment by allroundexperts** [comment] 2024-04-19 19:47
Checking this again tonight to confirm the actual bug.

**Comment by allroundexperts** [comment] 2024-04-19 20:18
Yep, for sure. @tgolen over to you.

**Comment by bondydaa** [comment] 2024-04-19 21:25
not sure why i got assigned but going to leave this for tim.

**Comment by tgolen** [comment] 2024-04-22 15:57
I don't think it matters if the currently focused tab is leader, or if it's the last opened tab. The most important thing is that there is always 1 leader.

**Comment by isabelastisser** [comment] 2024-04-24 18:12
@Skakruk, can you please provide an update? Thanks!

**Comment by gitaumoses4** [comment] 2024-04-24 18:14
I'm ready to work on this. @isabelastisser

**Comment by Skakruk** [comment] 2024-04-24 18:16
@isabelastisser I'm preparing a PR, the code is ready

**Comment by isabelastisser** [comment] 2024-05-08 21:40
@Skakruk, is this ready for payment? Can you please provide an update? Thanks!

**Comment by Skakruk** [comment] 2024-05-09 06:26
@isabelastisser yesterday we agreed on the implementation and PR was approved. Waiting for reviewer checklist completion.

**Comment by isabelastisser** [comment] 2024-05-09 14:53
@allroundexperts, please complete the checklist below.

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified. Link to the PR: 

- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 

- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 

- [ ]  Determine if we should create a regression test for this bug. 

- [ ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

- [ ]  [@isabelastisser] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by allroundexperts** [comment] 2024-05-09 18:34
> @allroundexperts, please complete the checklist below. Thanks!
> 
> BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  The PR that introduced the bug has been identified. Link to the PR:
> * [ ]  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [ ]  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [ ]   Determine if we should create a regression test for this bug.
> * [ ]  If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [ ]   [@isabelastisser] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

PR hasn't been merged yet @isabelastisser

**Comment by danieldoglas** [comment] 2024-05-13 23:33
I just saw that there's a fixed PR for this, but I came here to say that my client was stuck and showing a lot of `[info] [Pusher] Received updates, but ignoring it since this is not the active client - "`.

**Comment by tgolen** [comment] 2024-05-15 12:48
This wasn't really a regression. It was more just a flaw with the original feature. I don't think this needs the checklist filled out or any regression tests created.

**Comment by isabelastisser** [comment] 2024-05-20 17:34
Sounds good. Thanks @tgolen! I will process the payments on May 22.

**Comment by isabelastisser** [comment] 2024-05-22 19:41
@Skakruk, can you please share your Upwork profile?

**Comment by Skakruk** [comment] 2024-05-22 19:44
@isabelastisser here is my profile https://www.upwork.com/freelancers/~013b95670960c26f03

**Comment by isabelastisser** [comment] 2024-05-22 20:04
Thank you! all set.

**Closed by isabelastisser** 2024-05-22 20:04 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by allroundexperts** [comment] 2024-05-25 19:31
@isabelastisser I get paid through ND. Can you please update the summary? Thanks!

**Comment by isabelastisser** [comment] 2024-05-29 12:43
Payment Summary

[Upwork Job](https://www.upwork.com/jobs/~012e35885da3cd69cf)

Contributor: @Skakruk paid $250 via Upwork
C+ review: @allroundexperts paid $250 via NewDot. `PENDING PAYMENT`

**Comment by JmillsExpensify** [comment] 2024-07-09 23:08
$250 approved for @allroundexperts
