### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000]  App allows to add link in code block and does not display the same on copy and send

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22492] opened 2023-07-08 18:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send link in following format : [```Test```](google.com)
4. Observe that it displays link inside code block (till now, we have intentionally made sure to not display link in code block)
5. Hover and click on copy to clipboard
6. Paste in compose box and send
7. Observe that now, it does not display link in code block
## Expected Result: 
App should not display link inside code block and maintain same display format on copy to clipboard and send again as message
## Actual Result: 
App displays link inside code block if sent in specific format and on copy to clipboard and sending as normal message, it does not maintain the format
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ece2ab63-c0c2-4f1c-a65c-b1632dee93f1

https://github.com/Expensify/App/assets/43996225/96e0f0fa-9c89-46c4-9c95-684095a34b51

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688796230285319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f921043b5d238f9f</li>
        <li>Upwork Job ID: 1678721695254556672</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-07-08 18:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App allows to add link in code block and does not display the same on copy and send.

### What is the root cause of that problem?

The following markdown input

```
[```code```](google.com)
```

is translated into html 

```html
<a href="https://google.com" target="_blank" rel="noreferrer noopener"><pre>code</pre></a>
```

from frontend by method [ExpensiMark.replace](https://github.com/Expensify/expensify-common/blob/d636fef3f22b4e5fcf61333ddc89a5d2e08cacc9/lib/ExpensiMark.js#L383) applying [code fence rule](https://github.com/Expensify/expensify-common/blob/d636fef3f22b4e5fcf61333ddc89a5d2e08cacc9/lib/ExpensiMark.js#L23-L39) and [link rule](https://github.com/Expensify/expensify-common/blob/d636fef3f22b4e5fcf61333ddc89a5d2e08cacc9/lib/ExpensiMark.js#L75-L85).

The backend corrects the above html into following html

```html
<a href="https://google.com" target="_blank" rel="noreferrer noopener"></a><pre><a href="https://google.com" target="_blank" rel="noreferrer noopener">code</a></pre><a href="https://google.com" target="_blank" rel="noreferrer noopener"></a>
```

which is translated into following markdown when clicking to edit the comment 

````
```
[code](https://google.com)
```
````

Note the starting and ending anchor tag, `<a href="https://google.com" target="_blank" rel="noreferrer noopener"></a>`, are same and translated into empty string.

So, the root cause of this issue is that the [link rule](https://github.com/Expensify/expensify-common/blob/d636fef3f22b4e5fcf61333ddc89a5d2e08cacc9/lib/ExpensiMark.js#L75-L85) doesn't skip to translate markdown link syntax if its alias text inside `[]` contains code fence tag `<pre>`.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should avoid translating link markdown syntax if its alias text part contains `<pre>` tag.

To achieve it, we can change following condition

https://github.com/Expensify/expensify-common/blob/d636fef3f22b4e5fcf61333ddc89a5d2e08cacc9/lib/ExpensiMark.js#L454

 of method modifyTextForUrlLinks by checking if the alias text part, `match[1]`, includes `<pre>` tags 

```js
if (abort || match[1].includes('<pre>')) {
```

 to skip replacing link syntax to html.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by zanyrenney** [comment] 2023-07-11 11:03
Reviewed, adding external.

**Comment by hayata-suenaga** [comment] 2023-07-14 17:28
I'm not familiar with ExpensiMark 😓, so I gonna trust your assessment @thesahindia

assigning @eh2077

**Comment by eh2077** [comment] 2023-07-17 02:29
@thesahindia The PR https://github.com/Expensify/expensify-common/pull/558 for expensify-common is ready for review.

**Comment by pecanoro** [comment] 2023-07-17 17:47
@thesahindia It seems puller bear failed to assign people to the PR and I can't seem to assign you, can you leave a comment in the PR so I can assign you? I think it works after that happens

**Comment by hayata-suenaga** [comment] 2023-07-19 16:12
@thesahindia @eh2077 can you check @parasharrajat's comment above ⬆️

**Comment by Antasel** [comment] 2023-07-20 06:06
@hayata-suenaga @thesahindia @pecanoro 
I know @eh2077 has been assigned for this issue.
But I could not stop to propose more improved approach. I think `if (abort || match[1].includes('<pre>')) {` is not reasonable (ofc, it results expected behavior), because `modifyTextForUrlLinks` function is called from both of link and autolink rule and then we can't figure out which rule needs the condition, so better to add a tweak on MARKDOWN_LINK_REGEX pattern. (simply add `(?!\\[[\\s\\S]*<pre>[\\s\\S]*\\])`)

```
const MARKDOWN_LINK_REGEX = new RegExp(`(?!\\[[\\s\\S]*<pre>[\\s\\S]*\\])\\[([^\\][]*(?:\\[[^\\][]*][^\\][]*)*)]\\(${MARKDOWN_URL_REGEX}\\)(?![^<]*(<\\/pre>|<\\/code>))`, 'gi');
```
Your thoughts ?

**Comment by hayata-suenaga** [comment] 2023-07-20 16:08
@Antasel thank you very much for sharing your detailed thoughts. If you think there is still an issue left, could you post your finding as a bug report? Otherwise, @eh2077 is already working on it and we gonna go with their proposal 🙇

**Comment by Antasel** [comment] 2023-07-21 01:23
ok, i am just gonna contribute more improved solution. thanks for your reply

**Comment by zanyrenney** [comment] 2023-08-01 17:02
Invites have been sent to @eh2077 @thesahindia and @dhanashree. The final step is payment. I am going OOO so please can you pay out these? Thank you BZ team member!

**Comment by dhanashree-sawant** [comment] 2023-08-01 17:44
Thanks @zanyrenney, @Christinadobrzyn,
Invite accepted.

**Comment by Christinadobrzyn** [comment] 2023-08-01 19:32
Ready for payment

@thesahindia should we have a regression test for this?

**Comment by Christinadobrzyn** [comment] 2023-08-03 19:56
nudge @thesahindia ^

**Comment by Christinadobrzyn** [comment] 2023-08-03 20:02
Paying out in Upwork - https://www.upwork.com/jobs/~01f921043b5d238f9f

@dhanashree-sawant paid through Upwork for reporting the bug $250
@eh2077 paid through Upwork for contributor work $1000 + $500 speed bonus
@thesahindia paid through NewExpensify $1000 + $500 speed bonus

**Comment by Christinadobrzyn** [comment] 2023-08-07 20:33
Created Regression Test - https://github.com/Expensify/Expensify/issues/306418
Closing this GH

**Closed by Christinadobrzyn** 2023-08-07 20:33 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 21:45
$1,500 payment approved for @thesahindia based on BZ summary.
