### ISSUE TITLE
[HOLD for payment 2024-08-19] [HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] Chat - "Deleted Message" Notification Appears with Its Reply in IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43175] opened 2024-06-06 14:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to FAB > SUBMIT EXPENSE
2. Add an amount, choose a workspace chat, and add a merchant
3. Submit the expense and write a message in IOU
4. Delete the submitted expense

## Expected Result:
Only the "Deleted Message" notification should appear in IOU

## Actual Result:
The "Deleted Message" notification appears along with its reply in the IOU

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/06727f42-9392-4a96-92eb-14cf7f1668ad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc874ffd38131fb8</li>
        <li>Upwork Job ID: 1798767748175264943</li>
        <li>Last Price Increase: 2024-06-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment] 2024-06-06 14:35
@dangrous  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-06 14:35
We think that this bug might be related to #vip-vsp

**Comment by neil-marcellini** [comment] 2024-06-06 16:59
Here's a good comparison between staging and prod

staging
![Google Chrome 2024-06-06 09 29 51](https://github.com/Expensify/App/assets/26260477/e65f4fda-72f0-4e38-a9b3-dc377e692dae)

prod
![Google Chrome 2024-06-06 09 29 44](https://github.com/Expensify/App/assets/26260477/f9b4bc52-c0cc-4413-8ab4-1e0a20e6aea8)

We recently reverted something related to threads and expense reports, so I'll see if it's fixed on dev. It still happens on dev.

**Comment by dangrous** [comment] 2024-06-06 17:31
I think it's front end, since checking out `production` locally seems to fix it.

**Comment by dangrous** [comment] 2024-06-06 17:38
Looks like it's https://github.com/Expensify/App/pull/42554- investigating further and looking at a fix.

**Comment by kmbcook** [comment] 2024-06-06 20:18
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Chat - "Deleted Message" Notification Appears with Its Reply in IOU

### What is the root cause of that problem?
The root cause stems from https://github.com/Expensify/App/pull/34640 where ReportUtils.getAllAncestorReportActions was originally written. We now know this because fixing that root cause in https://github.com/Expensify/App/pull/42554 causes this regression. See https://github.com/Expensify/App/issues/41519#issuecomment-2093608757 for details.

### What changes do you think we should make in order to solve the problem?
Address the root cause by using the correct ancestor reportID, instead of leaving the root cause in place and reverting https://github.com/Expensify/App/pull/42554.

**Comment by dangrous** [comment] 2024-06-11 17:44
Hey @kmbcook! Since this was a regression I think you can move forward and fix; I know you're working on some other related issues too so can probably combine. Ping me on the PR when it's ready for review, if it doesn't assign automatically!

**Comment by adelekennedy** [comment] 2024-06-20 20:08
Catch me if I'm wrong but I don't think any payment is due here - the linked PR is all internal employees

**Comment by mananjadhav** [comment] 2024-06-20 20:18
Yeah no payment here.

**Comment by dangrous** [comment] 2024-06-25 14:34
Just because I got confused here and wasn't sure if this needed any action, a summary:

I believe we're just waiting for https://github.com/Expensify/App/issues/43175 to automatically close this once it's merged/deployed. No payment, no nuthin.

**Comment by dangrous** [comment] 2024-06-28 14:38
waiting on linked PR to be completed

**Comment by dangrous** [comment] 2024-07-01 08:16
Fix still in process

**Comment by neil-marcellini** [comment] 2024-07-01 16:54
Still waiting on a PR

**Comment by dangrous** [comment] 2024-08-05 15:23
Looks like we're almost there, passed C+ review just waiting on internal (and some merge conflicts)

**Comment by dangrous** [comment] 2024-08-07 15:41
Hey, we're merged! Hopefully deployed soon and the automation should fire

**Comment by dangrous** [comment] 2024-08-12 14:36
eyyyy should we recheck this and close out?

**Comment by dangrous** [comment] 2024-08-13 17:51
this is fixed on staging! just tested it. Closing.

**Closed by dangrous** 2024-08-13 17:51 UTC
Labels: External, Engineering, Weekly, Help Wanted, Awaiting Payment
