### ISSUE TITLE
Task – Members and settings options are present in deleted task RHP, chat isn’t archived

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45829] opened 2024-07-20 13:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4747510
**Email or phone of affected tester (no customers):** applausetester+jpcategory_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open chat with user B
4. Create a task
5. Open task detail and send a message
6. Click on the header and delete the task

## Expected Result:
Members and settings options disappears in deleted task RHP. Chat is archived

## Actual Result:
Members and settings options are present in deleted task RHP

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/429c5d74-cda8-4767-b4d1-a2f495e6be1c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-07-20 20:20
cc @srikarparsi this seems to be related to some of the closed reports logic, not sure if specifically this PR https://github.com/Expensify/App/pull/45568

**Comment by srikarparsi** [comment] 2024-07-20 21:03
Hey! Yup, it's related to those changes but I think it's expected (that you can see the full report details when a task is cancelled). But @puneetlath if you could take a look at this too that would be great. The slack conversation where we talked about using `state=MANUALREIMBURSED` and `status=CLOSED` for cancelling tasks is [here](https://expensify.slack.com/archives/C03TQ48KC/p1717696303543429).

Because of the Closed & Archived changes, we show the full report details for all closed reports now (which I think is good unless I'm missing any edge cases). If we want to change this, then we should modify this [check](https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/pages/ReportDetailsPage.tsx#L282) to include [isClosedReport](https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/libs/ReportUtils.ts#L1308).

The other option is, if we want cancelling a task to mimic archiving a task (no longer can comment, can't see the full report details, floats to bottom of LHN, etc.), we could add the isArchived rNVP in [Auth](https://github.com/Expensify/Auth/blob/f9ffec3c7587882f5a330a9a950b1561632936ac/auth/command/CancelTask.cpp#L60).

But I personally think this is expected behavior, let me know what you think @puneetlath. I can also bring it up in slack if you would like.

**Comment by mountiny** [comment] 2024-07-20 21:12
Thanks, lets discuss [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1721509915383439?thread_ts=1721483271.237909&cid=C01GTK53T8Q)

**Comment by mountiny** [comment] 2024-07-21 20:25
From the thread its clear this is not a blocker but still continuing the debate there

**Comment by youssef-lr** [comment] 2024-07-24 19:19
Not overdue

**Comment by srikarparsi** [comment] 2024-07-26 06:40
I think we should be good to close this out per this [discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1721483271237909)? cc @mountiny @puneetlath

**Comment by srikarparsi** [comment] 2024-07-29 18:53
Closing this out ([Discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1721483271237909))

**Closed by srikarparsi** 2024-07-29 18:53 UTC
Labels: Engineering, Daily
