### ISSUE TITLE
[HOLD for payment 2024-01-26] [$500] Wallet - `Fix the errors` button is non-functional in Additional details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32520] opened 2023-12-05 19:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL
2. Log in wirh any account
3. Go to Settings -> Wallet-> Enable wallet
4. Go through the process of connecting to Idology questions
5. Click [Save@Submit](mailto:Save@Submit)
without choosing any variant
6. Click on `Fix the errors`

## Expected Result:
The first unselected radio button is activated

## Actual Result:
`Fix the errors` button is non-functional

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/80cebb0e-f767-4f52-a07e-41b69090987b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ddd8bb8dc018a4a6</li>
        <li>Upwork Job ID: 1732125580300574720</li>
        <li>Last Price Increase: 2024-01-02</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28095131</li>
</ul></li>
    </ul>
</details>

**Comment by happy-devs** [comment] 2023-12-05 21:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking the "Fix the errors" button does not focus the first radio option as expected in the Idology question form

### What is the root cause of that problem?
There are parameters missing within the `FormProvider` component used by `IdologyQuestions`. This should trigger an automatic focus of the child input but has some extra complexity in the `FormProvider` wrapper, perhaps do the existence of two error messages in the form.

https://github.com/Expensify/App/blob/f80fbe34db2dbb5839946ccfe8b46d8c16462f83/src/pages/EnablePayments/IdologyQuestions.js#L134-141

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)
A longer-term proposal can be to assign the following items to the Typescript migration project (https://github.com/orgs/Expensify/projects/46): 
- https://github.com/Expensify/App/blob/f80fbe34db2dbb5839946ccfe8b46d8c16462f83/src/components/Form/FormWrapper.js
- https://github.com/Expensify/App/blob/f80fbe34db2dbb5839946ccfe8b46d8c16462f83/src/components/FormAlertWrapper.js
- https://github.com/Expensify/App/blob/f80fbe34db2dbb5839946ccfe8b46d8c16462f83/src/pages/EnablePayments/IdologyQuestions.js

**Comment by happy-devs** [comment] 2023-12-05 21:50
@lanitochka17 This might need some more clarification from the internal team. Do they want the first option to just be focused in order to draw the user's attention, or actually checked? "activated" is a little unclear

**Comment by mountiny** [comment] 2023-12-06 07:38
@dubielzyk-expensify hello! Would you be able to weigh in and help us with the expected behaviour? I am not sure what our form guidelines say about this but feels odd to me that we should activate/select some option for the user in this case when it comes to validation.

Would we just move the focus on some of the radio buttons so pressing enter would select it?

Should we do nothing in the case? Its pretty clear what needs to be done to fix the error?

Eitherway we should add whatever we decide to the FORMS.md guidelines

**Comment by happy-devs** [comment] 2023-12-06 09:31
This article has some interesting ideas

https://dev.to/andrewmcoupe/dont-fear-custom-radio-buttons-465a

**Comment by dubielzyk-expensify** [comment] 2023-12-14 00:58
Sorry for the late reply. In this instance, I think we shouldn't select anything so if they click next immediately, it's fine to throw an error. We'd want them to make an explicit choice, hence why a default selection is no bueno :)

**Comment by dubielzyk-expensify** [comment] 2023-12-18 23:21
Thanks for that!

>The problem is that clicking 'Fix the errors' in this case doesn't trigger anything (it feels broken)

I'd ideally think we should only have 1 error message here, but if we have to have two then let's just remove the link in "fix the errors" as like you say it doesn't do anything. The errors are self-explanatory by themselves anyways.

**Comment by luacmartins** [comment] 2023-12-21 10:04
I agree that one error message seems better in that case.

**Comment by dubielzyk-expensify** [comment] 2024-01-02 03:19
Let me know when there's any updates for me to take a look at

**Comment by NicMendonca** [comment] 2024-01-02 17:24
@kowczarz are you interested in working on this?

**Comment by kowczarz** [comment] 2024-01-02 17:40
Hello, tomorrow I can check the issue and proposals. If there will be a good solution then we can leave it to the contributor, otherwise I will take this issue. Does that work for you, @NicMendonca?

**Comment by kowczarz** [comment] 2024-01-03 13:25
Just for the context there is a thread we discussed the new layout of the errors https://github.com/Expensify/App/pull/31401#discussion_r1396510915

As @dubielzyk-expensify suggested we can add a prop that will disable the `fix the errors` button it will look that way:
![Simulator Screenshot - iPhone 15 Pro - 2024-01-03 at 14 16 45](https://github.com/Expensify/App/assets/91068263/a3b17f1f-a311-4e17-8b93-97d8e2fcb30f)

**Comment by kowczarz** [comment] 2024-01-04 10:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app displays `fix the errors` button even tough in case of radio button there is no way to focus proper input.

### What is the root cause of that problem?
Currently we have no option to add custom message, or disable the button in error alert.

### What changes do you think we should make in order to solve the problem?
We can add a prop to `FormAlertWrapper` and pass it down the component tree from `FormProvider`.

<details>
<summary>Image with button disabled</summary>

![Simulator Screenshot - iPhone 15 Pro - 2024-01-03 at 14 16 45](https://github.com/Expensify/App/assets/91068263/80d1fa11-3bfe-4234-8c45-b252a97bafca)


</details>

**Comment by dubielzyk-expensify** [comment] 2024-01-04 10:56
Sorry if I missed something, but I thought we landed on now showing two error on the screen, only one?

**Comment by kowczarz** [comment] 2024-01-04 11:43
@dubielzyk-expensify no, I've added a screenshot, you can see there are two errors, but in second the `fix the errors` is red and non-clickable.

**Comment by kowczarz** [comment] 2024-01-04 15:57
I've prepared a draft PR, as soon as @dubielzyk-expensify will give us green light, I can make it ready for the review.

**Comment by dubielzyk-expensify** [comment] 2024-01-05 00:13
Alright. Adding @Expensify/design team for second eyes, but feel free to send it out for review. I still think we should show only one error message here, but I'll lean on design team for guidance here

**Comment by shawnborton** [comment] 2024-01-05 08:59
Yeah I think I agree, it feels way cleaner to just show one error message and not both. cc @marcaaron as I think you were the Godfather of the form errors. What are your thoughts here?

**Comment by dannymcclain** [comment] 2024-01-05 13:48
I think it's fine to show just one error in this case (since there's only one "field" that needs attention). But I will leave it in the hands of the Godfather.

But can someone tell me why "fix the errors" was ever clickable? Is that something we do in other places? What is it supposed to do if I click it (in other situations)?

**Comment by dannymcclain** [comment] 2024-01-05 17:37
@kowczarz gotcha - thanks for showing me that!

**Comment by marcaaron** [comment] 2024-01-08 21:33
I could go either way on having two errors or not. If we have a single error I'd opt to put it under the input (in this case, the radio buttons). Otherwise, it looks like a server error to me above the button (which is a bit inconsistent with how we decided the forms should work). 

If the "Fix the errors" ends up redundant or unhelpful then it could be logical to hide it. But kind of feels like we are optimizing for a case that is... pretty much fine.

**Comment by dubielzyk-expensify** [comment] 2024-01-08 23:38
I'm okay with only having the error under the radio buttons 👍

**Comment by kowczarz** [comment] 2024-01-11 10:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app displays a redundant alert with `fix the errors` button even tough there is no way to focus proper input.

### What is the root cause of that problem?
We have no possibility to decide wether or not the fix the errors alert should be displayed.

### What changes do you think we should make in order to solve the problem?
In the `FormProvider` we can add a property `shouldHideFixErrorsAlert` that will be passed down the tree to `FormWrapper` and there we make calculation of `isAlertVisible` depending on it, so we can easily hide the alert when needed.

**Comment by kowczarz** [comment] 2024-01-11 15:45
@fedirjh currently the `isAlertVisible` is calculated the following way:
```jsx
isAlertVisible={_.size(errors) > 0 || Boolean(errorMessage) || !_.isEmpty(formState.errorFields)}
```
After update I would like to calculate it that way:
```jsx
isAlertVisible={((_.size(errors) > 0 || !_.isEmpty(formState.errorFields)) && !shouldHideFixErrorsAlert) || Boolean(errorMessage)}
```
So If we will want to display something more specific than `fix the errors`, it will show the alert.

**Comment by blimpich** [comment] 2024-01-11 18:10
Oh Melvin. Was trying to get it to assign @kowczarz as the contributor, but doesn't seem to want to do it. Not sure if that is important since @kowczarz is part of an expert agency. Either way, @kowczarz feel free to raise the PR and we can figure out how to wrangle Melvin if need be.

**Comment by NicMendonca** [comment] 2024-01-31 13:10
@fedirjh you've been paid - thanks!

**Closed by NicMendonca** 2024-01-31 13:10 UTC
Labels: External, Engineering, Weekly, Design, Awaiting Payment, Bug
