### ISSUE TITLE
Workspace - The Hmm.. its not here page is shown briefly when going to accounting feature

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44438] opened 2024-06-26 10:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR :** https://github.com/Expensify/App/pull/44141
**Email or phone of affected tester (no customers):** dave0123seife+stest@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Login to an account without any workspaces (a new account)
2. Account Settings > Workspaces > Create new workspace
3. Go to that workspace details => More feature
4. Enable Accounting section
5. Quickly go to Accounting after enabling it

## Expected Result:
No error page is shown

## Actual Result:
The Hmm.. its not here page is shown briefly when going to accounting feature for the first time

This issue also happens when navigating to the feature immediately after enabling it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [x] Android: mWeb Chrome
- [X] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/08bf79c7-369d-4020-9480-ad7e4a77f151

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2024-06-26 17:43
I think this was a temporary issue - I can't reproduce this. I'll ask QA if they can still reproduce.

**Comment by kavimuru** [comment] 2024-06-26 18:38
Tester is still able to reproduce.

https://github.com/Expensify/App/assets/43996225/076be68f-03d4-4f9b-bb1a-10e2e277b178


https://github.com/Expensify/App/assets/43996225/ebda5615-f005-4694-8569-248138c2d6fd

**Comment by Christinadobrzyn** [comment] 2024-06-26 19:38
I tested on Desktop/chrome/iOS/Android apps & browsers - I was able to reproduce this one (out of 8 tests) time on Native Android - I don't think this issue is happening consistently enough to reproduce and fix. Closing for now.

**Closed by Christinadobrzyn** 2024-06-26 19:38 UTC
Labels: Daily, Bug
