### ISSUE TITLE
[HOLD for checklist] [$1000] Attachment downloaded when user clicked outside the attachment button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19717] opened 2023-05-27 02:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Send an attachment to a chat
3. Click the empty area outside the attachment button

## Expected Result: 
Attachment file shouldn't be downloaded since the user clicked outside the button
## Actual Result: 
Attachment file downloaded and could potentially caused confusion

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/868e6315-69af-4fc0-aa71-30447c0467a0

https://github.com/Expensify/App/assets/43996225/251e247a-d594-4ad1-862c-579038a0bacb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684984471329289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0f07bfc53f77442</li>
        <li>Upwork Job ID: 1663611880864784384</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by therealsujitk** [comment] 2023-05-27 11:30
This is kind of a duplicate of #19017. I'd be happy to fix all occurrences of this. My proposal - https://github.com/Expensify/App/issues/19017#issuecomment-1549907508.

**Comment by therealsujitk** [comment] 2023-05-27 13:43
@hoangzinh I believe in both cases the entire light green portion ONLY is should be clickable. The same issue also exists for displayable attachments such as images and PDFs.

**Comment by greg-schroeder** [comment] 2023-05-30 12:54
I reproduced this - and I tend to agree it looks like the same root cause as https://github.com/Expensify/App/issues/19017

**Comment by greg-schroeder** [comment] 2023-05-30 12:54
I'm asking the team to confirm

**Comment by bernhardoj** [comment] 2023-05-30 13:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We can click outside of attachment box to download it.

### What is the root cause of that problem?
This is a regression of https://github.com/Expensify/App/pull/17496 which we previously set `align-items: start` to the HTML renderer default view. Imagine that the attachment box (and its Pressable) is wrapped by a View that has a style of `align-items: start`. Now, it's removed and moved to the Pressable. So, the Pressable have the full width, while the attachment box still stay the same because we have the `align-items: start` on the Pressable.

https://github.com/Expensify/App/blob/619a5298771ba5e42ae6f1596a37e32b9cd16fc0/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L81-L82

https://github.com/Expensify/App/blob/619a5298771ba5e42ae6f1596a37e32b9cd16fc0/src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.js#L48-L49

This also happens with ImageRenderer.

### What changes do you think we should make in order to solve the problem?

Wrap the Pressable with View and move the `styles.alignItemStart` there.

**Comment by greg-schroeder** [comment] 2023-05-30 18:22
Okay, keeping this separate! Applying External accordingly

**Comment by greg-schroeder** [comment] 2023-05-31 09:04
@thesahindia thoughts on the proposal [here](https://github.com/Expensify/App/issues/19717#issuecomment-1568478768)?

**Comment by greg-schroeder** [comment] 2023-05-31 10:36
Ah yes, sorry @hoangzinh

**Comment by greg-schroeder** [comment] 2023-06-02 10:50
Thanks for taking care of that @grgia! We're on our way. 👍

**Comment by bernhardoj** [comment] 2023-06-02 16:48
Having some issue on my local. I will probably open the PR tomorrow (at my time).

**Comment by greg-schroeder** [comment] 2023-06-05 15:33
PR is up, review underway

**Comment by greg-schroeder** [comment] 2023-06-07 20:24
PR merged, awaiting deploy to staging -> prod

**Comment by greg-schroeder** [comment] 2023-06-13 15:04
cc @grgia

**Comment by greg-schroeder** [comment] 2023-06-13 15:09
This might be a revert candidate

**Comment by grgia** [comment] 2023-06-13 15:38
@greg-schroeder looking into this more, but at a glance, I agree

**Comment by grgia** [comment] 2023-06-13 15:57
@youssef-lr I believe that's it. I think that's probably the best bet cc @thesahindia

**Comment by youssef-lr** [comment] 2023-06-13 16:02
I think we should exclude PR https://github.com/Expensify/App/pull/19545 as it seems unrelated to this issue and is fixing other issues, and remove the troublesome line causing https://github.com/Expensify/App/issues/20669. For the other two we can revert. What do you think @grgia?

**Comment by youssef-lr** [comment] 2023-06-13 16:05
@thesahindia that one is the culprit for this https://github.com/Expensify/App/issues/20669, but only a troublesome [line](https://github.com/Expensify/App/blob/main/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L57) there is causing the issue. I don't think we need to revert the full PR as it's fixing other stuff.

**Comment by bernhardoj** [comment] 2023-06-13 16:19
If I understand correctly, https://github.com/Expensify/App/issues/20669 is caused by https://github.com/Expensify/App/pull/19545 and https://github.com/Expensify/App/issues/20566 is caused by our PR https://github.com/Expensify/App/pull/20440 https://github.com/Expensify/App/pull/20114

In our case, we still need the changes from our PR. I have found a fix for this regression https://github.com/Expensify/App/issues/20566. Can I open the PR now?

**Comment by bernhardoj** [comment] 2023-06-13 16:56
Open it anyway as it's EOD for me.

**Comment by youssef-lr** [comment] 2023-06-13 17:08
Discussing with the team whether we go for a revert or your fix.

**Comment by greg-schroeder** [comment] 2023-06-19 07:41
What's going on with this issue? It's kinda difficult to follow what happened re: reverting all or part of what caused the deploy blocker :/

cc @grgia @youssef-lr @thesahindia

**Comment by grgia** [comment] 2023-06-22 12:20
@youssef-lr bump!

**Comment by greg-schroeder** [comment] 2023-07-06 01:00
Thanks for that @bernhardoj

**Comment by greg-schroeder** [comment] 2023-07-07 07:01
This issue is very difficult to follow given all the regressions, but here's the timeline as far as I can tell:

June 2nd: [PR](https://github.com/Expensify/App/pull/20114) Created
June 7th: PR Merged
June 8th: Regression found
June 13th: [New PR](https://github.com/Expensify/App/pull/20694) created to fix regression
June 27th: PR Merged
June 29th: Regression found
June 30th: [New PR](https://github.com/Expensify/App/pull/21941) created to fix regression
July 6th: PR Merged

I'm removing the payment hold waiting for this newest PR to be deployed, as that'll create a new payment hold.

I have no idea how we're going to pay this one out though, tbh. cc @grgia @thesahindia

**Comment by greg-schroeder** [comment] 2023-07-18 03:28
Okay so we're finally ready for this one I believe!

**Comment by greg-schroeder** [comment] 2023-07-18 09:38
@grgia @youssef-lr Per my comment [here](https://github.com/Expensify/App/issues/19717#issuecomment-1624852432), a LOT happened with this issue...

Can anyone weigh in on the best way to pay this out? I'm honestly not sure because so many things went wrong here. There aren't really clear guidelines when so many things went awry and so many people were involved 😅

**Comment by greg-schroeder** [comment] 2023-07-20 00:17
Hmm, I need to create a new upwork job I guess. Doing.

**Comment by greg-schroeder** [comment] 2023-07-20 01:01
Sent offers to @bernhardoj @kerupuksambel. Given there were two regressions the 50% penalty was applied twice

@thesahindia you'll handle payment via newdot!

**Comment by greg-schroeder** [comment] 2023-07-21 09:35
Payments are complete, waiting for checklist @thesahindia

**Comment by greg-schroeder** [comment] 2023-07-24 17:10
Bump on the above @thesahindia :)

**Closed** 2023-07-26 07:39 UTC
Labels: External, Daily, Help Wanted, Bug
