### ISSUE TITLE
[$250] Clicking into a thread and out disappears message below the parent message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40376] opened 2024-04-17 19:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-14
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @johnmlee101 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713370130959229

## Action Performed:
1. Open any report
2. Click to the thread
3. Click on the the header to return back to the message

## Expected Result:
Should be taken back into the chat report. The URL shouldn't contain the messageID.

## Actual Result:
Taken to just the parent chat message. URL has the messageID appended to it.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/9988761f-5168-4e8f-9daa-70ee22c7e239

https://github.com/Expensify/App/assets/38435837/854ecd44-e002-4e1a-a0d8-b2d2a4df5ce5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc0dcd6e681f7ef2</li>
        <li>Upwork Job ID: 1780701535328817152</li>
        <li>Last Price Increase: 2024-04-17</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2024-04-17 20:52
Yeah this is a legit deploy blocker! Adding external label for help finding out where it broke.

**Comment by rushatgabhane** [comment] 2024-04-17 21:42
Tested on latest `main` branch, the bug isn't reproducible.


https://github.com/Expensify/App/assets/29673073/2304e4f4-bdf1-469c-9a72-b90c90d923a3

**Comment by QichenZhu** [comment] 2024-04-17 21:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The URL of the parent link in a thread header contains parentReportActionID.

### What is the root cause of that problem?
The parentReportActionID in the URL is used to direct users back to the specific message in the parent and highlight that message.

This feature/bug was first introduced in [this commit](https://github.com/Expensify/App/commit/242ead9413a569a7375a415666f944ca113df269#diff-5fb885dfe096826c956a878b7be908f8671cd488ee46c47764fff1b07f6ad170L29-L34), and revised a few times later on. The current version is:
https://github.com/Expensify/App/blob/3ba42e684f75f143d6e7a85e62d23b7d561d7155/src/components/ParentNavigationSubtitle.tsx#L42

### What changes do you think we should make in order to solve the problem?
If it's considered as a feature, leave it as it is.

If it's considered as a bug, revert it to its original version:
https://github.com/Expensify/App/blob/610ce2667f7b4104ecb157a8c399249a15ff91cf/src/components/ParentNavigationSubtitle.tsx#L31

### What alternative solutions did you explore? (Optional)
N/A

**Comment by srikarparsi** [comment] 2024-04-17 22:10
Hey @chiragsalian, do you think you could take a look at this? I think this is expected behavior from [this](https://github.com/Expensify/App/pull/38722) but just want to make sure.

When you click the parent report in the header of a thread, the message id should be in the url right?

**Comment by thienlnam** [comment] 2024-04-18 04:07
https://github.com/Expensify/App/assets/30609178/4ce731d9-943a-4821-8c23-d5d889b5756b

Also seems to be fixed on staging

**Closed** 2024-04-18 04:07 UTC
Labels: External, Engineering, Hourly, Help Wanted, Bug

**Comment by aldo-expensify** [comment] 2024-04-23 18:18
I think this reappeared here: https://github.com/Expensify/App/issues/40644#issuecomment-2072021812
