### ISSUE TITLE
[HOLD for payment 2023-09-13] [$500] Chat - [Attachment] shows in LHN even after close error message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26047] opened 2023-08-28 01:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send any corrupted file
3. Send any message
4. Delete the message
5. Click on X button in Unexpected error message

## Expected Result:
 Last message should show in LHN

## Actual Result:
[Attachment] shows in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b748b93c-b26f-44c9-bcd8-9b7e13a5d2b0

[corrupt_PDF .pdf](https://github.com/Expensify/App/files/12449395/corrupt_PDF.pdf)

https://github.com/Expensify/App/assets/78819774/6379fc6d-0e69-4a26-a7f4-99f46398052c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692447261264769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aad872dd6b0a5da1</li>
        <li>Upwork Job ID: 1697750932793446400</li>
        <li>Last Price Increase: 2023-09-01</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 26485402</li>
<li>c3024 | Contributor | 26485404</li>
<li>gadhiyamanan | Reporter | 26485405</li>
</ul></li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-08-30 00:52
Reached out internally for a discussion about this and will update tomorrow.

**Comment by strepanier03** [comment] 2023-09-01 23:26
All good Melvin, just moved it to the next step and we'll get some proposals reviewed.

**Comment by s77rt** [comment] 2023-09-02 13:37
@c3024 Thanks for the proposal. Your RCA makes sense and the solution looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/26047#issuecomment-1694873322)

**Comment by robertjchen** [comment] 2023-09-04 07:43
Thanks, reviewing this now

**Comment by robertjchen** [comment] 2023-09-04 07:58
I also approve of @c3024 's analysis and proposal 👍

**Comment by s77rt** [comment] 2023-09-06 22:30
- The PR that introduced the bug has been identified: This is more like a feature request than a bug but the inconsistency was introduced by https://github.com/Expensify/App/pull/22342
- The offending PR has been commented on: https://github.com/Expensify/App/pull/22342#discussion_r1317892789
- A discussion in #expensify-bugs has been started: I don't feel this is needed for this case
- Determine if we should create a regression test for this bug: No

**Comment by strepanier03** [comment] 2023-09-13 19:40
@s77rt and @c3024 - I have paid you via Upwork and closed the contracts/left feedback. Thanks again!

@gadhiyamanan - Once you accept the offer let me know here so I can pay it as well. 

Thanks!

**Comment by gadhiyamanan** [comment] 2023-09-14 03:52
@strepanier03 offer accepted but the amount of offer is $50. It is eligible for $250 because it is logged before 30 aug. Please add $200 as bonus

**Comment by strepanier03** [comment] 2023-09-14 20:02
@gadhiyamanan - Got it, thanks for the heads up. I've paid you out at the previous $250 price since this issue was created before the 30th of August. 

All set here now, closing out.

**Closed by strepanier03** 2023-09-14 20:02 UTC
Labels: External, Daily, Awaiting Payment, Bug
