### ISSUE TITLE
[$500] Workspace - Can't add additional workspace members

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33623] opened 2023-12-26 20:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Create a workspace
4. Invite two expensifail members
5. Navigate to any workspace chat
6. Invite two additional new expensifail members

## Expected Result:
I should be able to add new members

## Actual Result:
Can't add additional workspace members

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/eb3359d4-f576-446c-8e35-fe602c163a00

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018c4e84f483fe839b</li>
        <li>Upwork Job ID: 1739744855500054528</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by rrrshtt** [comment] 2023-12-27 17:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We can't add additional members to existing workspaces.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/d6f359fc010fe8120cf8a6761a4dac21c819e270/src/libs/actions/Policy.js#L554
As I can see, we forgot to add the announcement of room members success data. It could be the root of the problem.

### What changes do you think we should make in order to solve the problem?
We need to ensure that every success data is attached.

**Comment by mvtglobally** [comment] 2024-01-11 06:01
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2024-01-14 09:00
@hoangzinh Based on the last QA comment above, I don't think this is reproducible anymore. Closing.

**Closed by JmillsExpensify** 2024-01-14 09:00 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
