### ISSUE TITLE
[$1000] Composer is focused when creating a workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19440] opened 2023-05-23 13:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click on 'Profile' icon
2. Click on 'Workspace' link
3. Click on 'New workspace' button

## Expected Result: 
Composer shouldn't be focused
## Actual Result: 
Composer is focused

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/dddb6bc8-3b5d-4fcd-99cf-359640fdd6e9

https://github.com/Expensify/App/assets/43996225/e01ae64c-93e0-4a71-bf5a-e2cc6ff2d688

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684825988204159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010bb443b5ade008b1</li>
        <li>Upwork Job ID: 1664239819599945728</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-05-23 15:06
Confirmed I can reproduce on staging but not prod. @danieldoglas do you agree this should be a deploy blocker?

**Comment by danieldoglas** [comment] 2023-05-23 17:19
I don't think this is a deploy blocker. It's a bug, but it won't break the app/experience if we deploy it to production. But we need to find the offending PR

**Comment by danieldoglas** [comment] 2023-05-23 17:21
I think this is the PR https://github.com/Expensify/App/pull/19224

**Comment by Natnael-Guchima** [comment] 2023-05-23 17:22
I am guessing this might be the offending PR https://github.com/Expensify/App/pull/19224

**Comment by joekaufmanexpensify** [comment] 2023-05-24 12:46
Thanks! PR is in review.

**Comment by joekaufmanexpensify** [comment] 2023-05-26 18:29
Adding an additional BZ assignee as I'm OOO next week (until June 5th). PR for this one is up, but there is some discussion in the PR about how we should proceed. Next steps here are to just make sure we drive the discussion in the PR to resolution.

**Comment by joekaufmanexpensify** [comment] 2023-05-26 18:29
Adding an additional BZ assignee as I'm OOO next week (until June 5th). PR for this one is up, but there is some discussion in the PR about how we should proceed. Next steps here are to just make sure we drive the discussion in the PR to resolution.

**Comment by danieldoglas** [comment] 2023-06-01 11:57
as discussed in https://github.com/Expensify/App/pull/19492#issuecomment-1569325157, assigning @Santhosh-Sellavel as the C+ for this issue. This was not a regression, but actually something that happened independently of the changes in the PR I tagged above. The changes in the PR just made the issue clear.

Adding this as external.

**Comment by joekaufmanexpensify** [comment] 2023-06-04 16:15
@abekkala I'm back from OOO, so removing your assignment!

**Comment by situchan** [comment] 2023-06-04 16:29
This is a dupe of https://github.com/Expensify/App/issues/18182 and can be closed.

**Comment by joekaufmanexpensify** [comment] 2023-06-05 13:00
Yep, looks like a dupe to me. @danieldoglas cool to close this too?

**Comment by danieldoglas** [comment] 2023-06-05 13:03
oh wow, yes. That one is older. I think it's the same root cause. Let's close this one.

**Closed by danieldoglas** 2023-06-05 13:03 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
