### ISSUE TITLE
Grouped DM Avatar Have A Slightly Visible Outline Around The Avatar

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14204] opened 2023-01-10 19:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login To App
2. Click On FAB Icon
3. Click On New Group
4. Add Group Members At Least 3

## Expected Result:
There Should Be No Visible Outline Around The Avatar

## Actual Result:
There Is A Slight Visible Outline Around The Avatar

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native

**Version Number:** 1.2.52-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/211649108-7df67842-9f71-4001-9c8c-6cdbb40e14d5.jpg" width="40%" height="40%">
<img src="https://user-images.githubusercontent.com/43996225/211649326-6862cf4d-60a0-4fc9-af8b-55bcba9d7033.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @syedsaroshfarrukhdot 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673314602051279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2023-01-10 19:57
@isabelastisser This one is going to be on hold for related bugs. I'm happy to take it over as result and manage that process. Just let me know!

**Comment by isabelastisser** [comment] 2023-01-11 18:20
Thanks for the heads up, @JmillsExpensify! Sure, I will unassign myself.

**Comment by JmillsExpensify** [comment] 2023-01-11 21:29
Awesome! Also as an update, it looks like #13647 is very close to being merged. I'm keeping the daily label on this issue despite the HOLD as a result.

**Comment by JmillsExpensify** [comment] 2023-01-16 22:41
Linked PR still not merged.

**Comment by JmillsExpensify** [comment] 2023-01-20 03:47
Same same.

**Comment by JmillsExpensify** [comment] 2023-02-07 04:12
Now that https://github.com/Expensify/App/pull/13647 is merged, let's take this off hold.

**Comment by JmillsExpensify** [comment] 2023-02-07 04:18
Hmm, I just tried reproducing this and I wasn't able. It must have been resolved at some point, 
![Screenshot 2023-02-06 at 22 17 02](https://user-images.githubusercontent.com/1127863/217147052-47430422-1b42-49c6-b287-b688764ee19c.png), so per the linked Slack thread we've held on this and there is nothing to do here. I'm closing the issue as a result.

**Closed by JmillsExpensify** 2023-02-07 04:18 UTC
Labels: Weekly, Bug
