### ISSUE TITLE
[$500] mWeb-Workspace-In offline, the user edited only "default currency" but workspace name also greyed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27929] opened 2023-09-21 10:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap preferences
4. Tap toggle on forced offline
5. Tap back button
6. Tap Workspaces
7. Tap on a workspace
8. Tap on the workspace name
9. Tap default currency and select any other currency and save it
10. Tap on Workspace name

## Expected Result:
In offline, the edited option "default currency" section must alone be greyed out and workspace name should not be greyed.

## Actual Result:
In offline, the user edited only "default currency" section but when user taps workspace name and revisit the page, both workspace name and default currency section is greyed out.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/1f3393a8-bc10-471e-9c5c-ef9b60a88314

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c9579670771915c</li>
        <li>Upwork Job ID: 1706202398272712704</li>
        <li>Last Price Increase: 2023-09-25</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-22 03:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace-In offline, the user edited only "default currency" but the workspace name also greyed

### What is the root cause of that problem?
When editing the currency, we are setting pendingFields.generalSettings: 'update' and we using this field to grey out both input fields
https://github.com/Expensify/App/blob/757c1217a0d0ead3812cd92b7f5816062bed5a4c/src/pages/workspace/WorkspaceSettingsPage.js#L133-L153

### What changes do you think we should make in order to solve the problem?
We should split pendingFields.generalSettings into 2 fields separatlypendingFields.generalSettings.currency and pendingFields.generalSettings.name. Then we only update pendingFields.generalSettings.currency if we change currency and the same to update the name.
We also need to use 2 OfflineWithFeedback components to wrap name TextInput and currency Picker separately with specifical pendingField

### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment] 2023-09-25 07:01
not sure why applause didn't add the label for this one!

**Comment by zanyrenney** [comment] 2023-10-02 09:41
Closing as expected behaviour.

**Closed by zanyrenney** 2023-10-02 09:41 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
