### ISSUE TITLE
[HOLD for payment 2023-11-06] [HOLD for payment 2023-11-02] BA - Icons and text on “Connect online with Plaid” button is offset relative other buttons

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30400] opened 2023-10-25 22:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com or open Expensify app and login with any account
2. Go to existing workspace or create new one
3. Go to Settings > Workspace > Bank Account
4. Check the placement of icons and text on the buttons

## Expected Result:
Icons and text on all buttons have the same location and alignment

## Actual Result:
Icons and text on “Connect online with Plaid” button is offset relative other buttons

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 
![Bug6250961_1698272010524!iOS-Stag-Connect-BA-Plaid-button](https://github.com/Expensify/App/assets/78819774/35ec8743-9f4b-46d3-9a0f-d4c8f9233c59)

![Bug6250961_1698272010543!iOS-Prod-Connect-BA-Plaid-button](https://github.com/Expensify/App/assets/78819774/10348e01-c5aa-41fd-add0-fd55a57262d6)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment] 2023-10-25 23:58
### Bug0 Triage Checklist ([Main S/O](https://stackoverflowteams.com/c/expensify/questions/14418))

### Bug Zero Checklist

- [x] This "bug" occurs on a supported platform (ensure `Platforms` in OP are ✅)
- [x] This bug is not a duplicate report (check [E/App issues](https://github.com/Expensify/App/issues) and [#expensify-bugs](https://expensify.slack.com/archives/C049HHMV9SM))
    - If it is, comment with a link to the original report, close the issue and add any novel details to the original issue instead
- [x] This bug is reproducible using the reproduction steps in the OP. [S/O](https://stackoverflowteams.com/c/expensify/questions/14418#:~:text=The%20bug%20is%20reproducible)
    - If the reproduction steps are clear and you're unable to reproduce the bug, check with the reporter and QA first, then close the issue.
    - If the reproduction steps aren't clear and you determine the correct steps, please update the OP.
- [x] This issue is filled out as thoroughly and clearly as possible
    - Pay special attention to the title, results, platforms where the bug occurs, and if the bug happens on staging/production.
- [x] I have reviewed and subscribed to the linked Slack conversation to ensure Slack/Github stay in sync

**Comment by strepanier03** [comment] 2023-10-25 23:59
On Mac/Chrome staging.new.expensify.com.

Confirmed they don't line up.

<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/10925636/67aea09f-c92f-4646-b393-a0a4c6f8c6dd">

**Comment by c3024** [comment] 2023-10-26 07:26
PR #30192 added this 
https://github.com/Expensify/App/blob/062c25d91c0f5dc01e0716b665cca8989bde8d1b/src/styles/styles.ts#L485
Now the button has all its info centered.

**Comment by s-alves10** [comment] 2023-10-26 08:59
Yeah. we need to take these cases into account
I'll create a PR for this in a few hours

**Comment by s-alves10** [comment] 2023-10-26 10:48
PR is ready for review https://github.com/Expensify/App/pull/30417

**Comment by marcaaron** [comment] 2023-10-26 18:50
Looks fixed now

![2023-10-26_08-49-53](https://github.com/Expensify/App/assets/32969087/85c56094-e5bd-4406-acec-5fbc3175366a)

**Comment by strepanier03** [comment] 2023-11-02 18:10
@chiragsalian is anyone eligible for payment for this one?

**Comment by strepanier03** [comment] 2023-11-02 19:47
Chatted with Chirag 1:1 and we're going to pay the C+ for reviewing the PR. I'm working on that now.

**Comment by strepanier03** [comment] 2023-11-02 20:08
https://github.com/Expensify/App/issues/30400#issuecomment-1784627441

**Comment by strepanier03** [comment] 2023-11-02 20:10
@getusha - I've hired you to a job in Upwork. I'll check tomorrow to see if you accepted so I can pay it out.

**Comment by getusha** [comment] 2023-11-02 20:13
> @getusha - I've hired you to a job in Upwork. I'll check tomorrow to see if you accepted so I can pay it out.

Accepted, thanks!

**Comment by strepanier03** [comment] 2023-11-03 23:11
All right, this has been paid. Thank you @getusha for being a part of the community and for your hard work. Cheers!

Closing this out now.

**Closed by strepanier03** 2023-11-03 23:11 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
