### ISSUE TITLE
[HOLD] [$1000] Chat - Site preview is not updated once link is changed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21729] opened 2023-06-27 18:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21227
## Action Performed:
1. Login to NewDot
2. Open chat
3. Send message: google.com
4. Preview is displayed
5. Edit link
6. Change URL google.com to any other

## Expected Result:
URL preview should change

## Actual Result:
Site preview is not updated once link is changed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.33.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6fe8601f-f713-4543-addc-c0500acf579d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c6da8df46fdbd12</li>
        <li>Upwork Job ID: 1674119321287651328</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-06-28 06:33
### Proposal

This is an issue because `linkMetadata` is not update when call `ExpandURLPreview`.

Solution 1: need to update `linkMetadata` using ``message.html` when call  `ExpandURLPreview`.
Solution 2: if we need to keep previous all `linkMetadata`. then we can show embedded url when `message.html` contain that link.

Thanks.

**Comment by yh-0218** [comment] 2023-06-28 06:42
### Proposal

This is an issue because `linkMetadata` is not updated after report action `ExpandURLPreview`.

Solution 1: Need to update `linkMetadata` using `message.html` after report action `ExpandURLPreview`.
Solution 2: If we need to keep all previous `linkMetadata`, then we can show only some embedded urls that are contained in `message.html`.

Thanks

**Comment by yh-0218** [comment] 2023-06-28 06:47
Contributor details
Your Expensify account email: appstar0112@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015fe6ea816a7eb7fc

**Comment by kaomoua** [comment] 2023-06-28 21:58
Contributor details
Your Expensify account email: [kao.moua94@gmail.com](mailto:kao.moua94@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/kaomoua

**Comment by maddylewis** [comment] 2023-06-30 14:13
@eVoloshchak - can you review @allroundexperts's proposal above? thanks!

**Comment by eVoloshchak** [comment] 2023-07-02 20:57
I think this and https://github.com/Expensify/App/issues/21191 are related, fix for https://github.com/Expensify/App/issues/21191 should also resolve this one

**Comment by maddylewis** [comment] 2023-07-05 13:33
holding for #21191 - https://github.com/Expensify/App/issues/21729#issuecomment-1616816851

moving to `weekly` until 21191 is live.

**Comment by maddylewis** [comment] 2023-07-14 00:18
oy, now #21191 is on hold

**Comment by maddylewis** [comment] 2023-07-24 16:32
this one is off hold now - https://github.com/Expensify/App/issues/21191

**Comment by eVoloshchak** [comment] 2023-07-26 17:53
This was resolved when https://github.com/Expensify/App/issues/20832 was fixed I think, unable to reproduce anymore

https://github.com/Expensify/App/assets/9059945/4a251b48-ebeb-4067-8699-2be33b8cf305

**Comment by eVoloshchak** [comment] 2023-07-31 15:50
@maddylewis, could you re-test if this is still reproducible on your end? 
I think this can be closed

**Comment by eVoloshchak** [comment] 2023-08-09 12:39
Not overdue, waiting for someone else to confirm this is not reproducible (it isn't on my end)

**Comment by maddylewis** [comment] 2023-08-21 14:30
sorry for missing this - im not able to repro. closing!

**Closed by maddylewis** 2023-08-21 14:30 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
