### ISSUE TITLE
[$500] Assign task - Error page appears when a group member first opens an assigned task

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26341] opened 2023-08-30 20:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account
3. Navigate to a Group Chat that has 2 or more participants
4. Click on the + in the compose box and select "Assign task"
5. Enter a Title only, leave description blank
6. Create the task
7. Log out and log in as another participant of the group
8. Navigate to the group conversation where the task was created
9. Click on the task to navigate to the task "conversation"

## Expected Result:
The task "conversation" page opens

## Actual Result:
An error page opens for a moment and then the task "conversation" page
`hmm, it is not here' You don’t have access to this chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5d9b8726-801e-4160-8818-f70f8db10392

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164d2ba0c33231da2</li>
        <li>Upwork Job ID: 1697182720906133504</li>
        <li>Last Price Increase: 2023-08-31</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-08-31 09:40
Reproduced!

**Comment by BhuvaneshPatil** [comment] 2023-08-31 09:58
try checking in this verison - v1.3.60-1

I am on dev (latest main).

**Comment by luacmartins** [comment] 2023-08-31 16:32
It sure seems related and could share the same root cause. I say we close this issue

**Comment by conorpendergrast** [comment] 2023-09-01 09:56
Happy to. Thanks!

**Closed by conorpendergrast** 2023-09-01 09:56 UTC
Labels: External, Daily, Help Wanted, Bug
