### ISSUE TITLE
[Guided Setup Stage 2] Keyboard not opened when navigating to enter name screen

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40750] opened 2024-04-23 06:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/39951
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app and log in with a new account
2. Tap Settings > Troubleshoot > Onboarding Flow
3. Select any option

## Expected Result:
The keyboard is opened, and placeholder is pushed up

## Actual Result:
The keyboard is not opened until the field is selected, and cursor is overlapping the placeholder

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e3fe66f0-2cec-4062-a859-f61b7882cfd5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-23 06:59
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-23 06:59
We think this issue might be related to the #vip-vsb.

**Comment by mountiny** [comment] 2024-04-23 09:13
@filip-solecki @rezkiy37 @cdOut could you please fix this in your  onboarding PRs? thanks!

**Comment by rezkiy37** [comment] 2024-04-23 09:16
I am fixing this problem in my [PR](https://github.com/Expensify/App/pull/40688).

**Comment by rezkiy37** [comment] 2024-04-23 11:24
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2024-04-23 14:45
I've tried to reproduce the bug. I was not able to get it. It works properly on an emulator and a real Android device.

<details><summary>Details</summary>
<p>

https://github.com/Expensify/App/assets/57314631/3e811819-0172-4929-8db4-cc287b72cf34


https://github.com/Expensify/App/assets/57314631/324535c6-ee34-4173-850d-c87855682f38


https://github.com/Expensify/App/assets/57314631/3a5d73de-3588-4c25-88ed-f7932e15f0e1

</p>
</details>

**Comment by joekaufmanexpensify** [comment] 2024-04-23 20:00
I also cannot reproduce. 

https://github.com/Expensify/App/assets/54866469/4b44d27b-9316-4492-9cb4-d7195f080840

**Comment by joekaufmanexpensify** [comment] 2024-04-23 20:01
Is anyone able to consistently reproduce this?

**Comment by mountiny** [comment] 2024-04-23 22:57
@kavimuru @izarutskaya can you please check what device/ android version have you reproed this at?

**Comment by joekaufmanexpensify** [comment] 2024-04-25 13:50
I'm going to close this for now since it cannot be reproduced. Happy to take another look if someone ends up being able to consistently reproduce this on a specific device/android version.

**Closed by joekaufmanexpensify** 2024-04-25 13:50 UTC
Labels: Engineering, Daily, Bug
