### ISSUE TITLE
[$250] mWeb - Predictive text feature avoids editing a message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49815] opened 2024-09-26 20:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5007338
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to any conversation
2. Send any message
3. Edit the sent message by adding a word or deleting characters
4. Tap the Check button

## Expected Result:
The changes are saved and the edited message is displayed correctly in the conversation

## Actual Result:
If a word is still underlined when I tap the Check button, the changes are not saved
Only changes on words that are not underlined are saved, whether I delete characters or add a word

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/dfcdf112-1fbb-47b9-9bdf-afa4442ee1ed

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841971979384429666</li>
        <li>Upwork Job ID: 1841971979384429666</li>
        <li>Last Price Increase: 2024-10-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by lanitochka17** [comment] 2024-09-26 20:50
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-09-27 06:21
Same root cause as https://github.com/Expensify/App/issues/49486

**Comment by VictoriaExpensify** [comment] 2024-10-01 00:07
I can't reproduce this - I have tried on:

 Android: Native
 Android: mWeb Chrome
 MacOS: Chrome / Safari
 MacOS: Desktop

**Comment by VictoriaExpensify** [comment] 2024-10-01 00:10
Posted in Slack:
https://expensify.slack.com/archives/C01GTK53T8Q/p1727741424696559

**Comment by m-natarajan** [comment] 2024-10-01 23:27
Tester used Samsung Keyboard, More information about this issue can be found in the [comment](https://github.com/Expensify/App/issues/49486#issuecomment-2368666801).

**Comment by VictoriaExpensify** [comment] 2024-10-03 22:42
Ah ok, understood. Based on the linked issue, it looks like this is something we want to fix.

**Comment by waterim** [comment] 2024-10-04 11:09
Hello, Im Artem from Callstack and would like to help with this issue

**Comment by waterim** [comment] 2024-10-07 20:56
MY update:
Couldn't reproduce at the beginning, but after several tries and different emulators I was able to reproduce it not only with Predictive text feature but also with a regular text

**Comment by VictoriaExpensify** [comment] 2024-10-10 02:56
Not overdue

**Comment by VictoriaExpensify** [comment] 2024-10-14 03:50
Since this looks to be resolved through [this issue](https://github.com/Expensify/App/issues/49486#issuecomment-2371140251), I'm closing this out

**Closed by VictoriaExpensify** 2024-10-14 03:50 UTC
Labels: External, Daily, Help Wanted, Bug
