### ISSUE TITLE
Request Money - App crashes after tapping “Request Money”

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29602] opened 2023-10-14 12:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing PR https://github.com/Expensify/App/pull/28214

**Version Number:** 1.3.84-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N 

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Open Android or iOS App
2. Login with any account
3. Tap FAB > Request Money

## Expected Result:
Request money flow starts

## Actual Result:
Android - App crashes
iOS - Blank page loads

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/88b24680-0c8f-41b9-96fb-a5899cb61b1c

[log crash.txt](https://github.com/Expensify/App/files/12905400/log.crash.txt)

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/115492554/5fca8861-ccb7-4ade-b731-1cc62127cc9d

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a16c7aacf48e902</li>
        <li>Upwork Job ID: 1713177488589635584</li>
        <li>Last Price Increase: 2023-10-14</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-10-14 14:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crash for request money screen due to bad value for opacity 

### What is the root cause of that problem?
It is a regression from this [PR](https://github.com/Expensify/App/pull/27660) of styles migration where `tabOpacity` func is updated to return the object https://github.com/Expensify/App/pull/27660/files#diff-eec5d8b1dfad21f2e7bac8456d093eddd72fcbd5ea76411e3dd3c713beb9fb84R3623-R3625. 
Earlier it was returning just number and that value we were setting for the opacity prop but now we are trying to set an object for the opacity value.
https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/components/TabSelector/TabLabel.js#L28-L31
https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/components/TabSelector/TabIcon.js#L29-L35

### What changes do you think we should make in order to solve the problem?
We can use the opacity object(activeOpacity, inactiveOpacity) directly which we pass to `TabLabel` and `TabIcon` components.

For an example,
https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/components/TabSelector/TabLabel.js#L28
```js
<Animated.View style={[activeOpacity]}>
```

Suggesting as we are already using an object for func `tabBackground`.

**Comment by ikevin127** [comment] 2023-10-14 14:10
The app does not crash anymore on latest main for iOS.
The only issue is the labels missing from tab selector Request money > Manual / Scan / Map.
<details>
<summary>iOS: Native</summary>

<img width="383" alt="Screenshot 2023-10-14 at 17 04 04" src="https://github.com/Expensify/App/assets/56457735/d3e8392f-c4eb-4f13-8ba0-d77bdaf94c46">

</details>

For android it still crashes as a regression of this PR: https://github.com/Expensify/App/pull/27660 due to the fact that incorrect opacity style is passed to View component as the error below mentions and is referenced in [this](https://expensify.slack.com/archives/C049HHMV9SM/p1697279968400179?thread_ts=1697210216.244469&cid=C049HHMV9SM) Slack message.

<details>
<summary>Android: Native</summary>

<img width="403" alt="Screenshot 2023-10-14 at 17 07 34" src="https://github.com/Expensify/App/assets/56457735/7a409f79-6369-4be8-add9-2ceaa08378c8">

</details>

**Comment by mananjadhav** [comment] 2023-10-14 14:42
@Pujan92's proposal here looks good to me. 

🎀 👀 🎀 C+ reviewed.

**Comment by jayeshmangwani** [comment] 2023-10-14 15:07
> 
> offending PR #27596
> 
@ishpaul777 How is this offending [PR](https://github.com/Expensify/App/issues/27596)? , in that issue we are trimming the value only

**Comment by kubabutkiewicz** [comment] 2023-10-14 20:06
Created [PR](https://github.com/Expensify/App/pull/29629) per request from @situchan

**Comment by mountiny** [comment] 2023-10-15 18:46
Thanks the pr author/ Callstack resolved this

**Comment by mountiny** [comment] 2023-10-16 09:17
Fixed in staging, internally reported, closing

**Closed by mountiny** 2023-10-16 09:17 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
