### ISSUE TITLE
Add Bank Account - Generic error when entering numbers instead of letters in first/last name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25836] opened 2023-08-24 12:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the testing app
2. Open settings > workspace > bank accounts > manual > company info > personal info
3. Enter numbers in both fields First and Last name
4. Observe error

## Expected Result:
Error handling appears informing user that they must enter letters A-Z in the first/last name field or the entered data is invalid

## Actual Result:
Generic error appears ""An unexpected error occurred while trying to verify your information, Please verify it and try again" and user does not know for which field they entered incorrect data
""An unexpected error occurred while trying to verify your information, Please verify it and try again"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS  / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.57-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6174483_Screen_Shot_2023-08-23_at_3 14 37_PM](https://github.com/Expensify/App/assets/78819774/8f88bd75-be3c-47b9-997a-c99ad7784e54)

https://github.com/Expensify/App/assets/78819774/ffda439c-e371-46f4-949d-3580fd7ef306

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2023-08-25 22:17
Reproduced 
<img width="870" alt="image" src="https://github.com/Expensify/App/assets/36425901/9d0f8af9-e526-49cd-af2e-d5fe3f3f4593">

**Comment by MitchExpensify** [comment] 2023-08-25 22:18
Dupe of: https://expensify.slack.com/archives/C049HHMV9SM/p1692198598449099

**Closed** 2023-08-25 22:19 UTC
Labels: Daily, Bug
