### ISSUE TITLE
[PAYMENT DUE 6/18 - $250][Live Markdown] Multiple italics markdown in a message are not shown correctly 

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#41110] opened 2024-04-26 17:52 UTC
Actual
![image](https://github.com/Expensify/App/assets/30609178/3228271b-a65f-4082-88e1-6db8e4431f4b)

![image](https://github.com/Expensify/App/assets/30609178/ef4bccbc-542e-4b7b-9fb7-e01703246cf2)

Expected
All the phrases in between `_message_` should be italicized correctly

cc @tomekzaw 

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by skyweb331** [comment] 2024-04-26 19:49
Duplicated issue https://github.com/Expensify/App/issues/40571

**Comment by skyweb331** [comment] 2024-04-26 19:53
So this happens because of `ExpensiMark` module... It is using regex to parse html to markdown but it has its limitation. It is really difficult to parse complex html to markdown using regex only.
I had discussion with @ikevin127  https://expensify.slack.com/archives/C01GTK53T8Q/p1713721057329569

So solution is to change the parsing logic. (ie using `xml2js`)

cc @jjcoffee

**Comment by slafortune** [comment] 2024-04-30 20:16
closing duplicate

**Comment by sobitneupane** [comment] 2024-05-01 03:16
@slafortune I am not very confident that https://github.com/Expensify/App/issues/40571 will solve this issue. @jjcoffee Will this issue be solved by the selected proposal in https://github.com/Expensify/App/issues/40571?

**Comment by skyweb331** [comment] 2024-05-01 04:25
@slafortune @sobitneupane I made a mistake... This is related to **ExpensiMark** parsing Markdown to HTML, and above duplicated ticket is to parsing HTML to Markdown... So it is not a duplicated issue... I am sorry for this and will submit the proposal now.

**Comment by jjcoffee** [comment] 2024-05-01 09:21
@sobitneupane Yeah this isn't a duplicate as far as I can tell.

**Comment by skyweb331** [comment] 2024-05-01 10:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Multiple italics markdown in a message are not shown correctly
### What is the root cause of that problem?
`ExpensiMark` does not parse markdown to HTML correctly for italics.
https://github.com/Expensify/expensify-common/blob/1713f28214f0e7176c4fd13433fb0ea15491ebf9/lib/ExpensiMark.js#L293-L303

This regex does not parse following italics when there is `<pre>, <code>, <a>, <mention-user>` tags.

And found one more thing,
It does not parse `_blank_` to `<em>blank</em>` because current regex pattern detects `_blank` as  one of `target="_blank"`.

### What changes do you think we should make in order to solve the problem?
My solution is to ignore `<pre>,<code>,<a>,<mention-user>` tags first, so that any italicizing inside those contents can be passed.
I already completed this and passed all tests.
https://github.com/Expensify/expensify-common/commit/8035d6771cb5a0382271eb8e10f632ae9320ed2f

### What alternative solutions did you explore? (Optional)
n/a

**Comment by sobitneupane** [comment] 2024-05-08 08:57
Thanks for your [proposal](https://github.com/Expensify/App/issues/41110#issuecomment-2088256400) @skyweb331 

What will be the result of following input after applying your solution?

<img src="https://private-user-images.githubusercontent.com/30609178/326066254-3228271b-a65f-4082-88e1-6db8e4431f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTg3MjgsIm5iZiI6MTcxNTE1ODQyOCwicGF0aCI6Ii8zMDYwOTE3OC8zMjYwNjYyNTQtMzIyODI3MWItYTY1Zi00MDgyLTg4ZTEtNmRiOGU0NDMxZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA4NTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NDEwNWRlNDI4NzAxNmQyYTk4NDA4ZTA1NGEwNTliNGVkYTdjZTRkNGNhYmE3NTcxZTQ1ZGU2OWNiZDNkZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mg4keV9TgTs1wjMTVXlNKj7UZAz_5ifmpf_77bnuWMk"/>

**Comment by skyweb331** [comment] 2024-05-08 10:43
Results are here.

![image](https://github.com/Expensify/App/assets/25519849/9a430b44-085a-4e41-8248-ca9c3355866b)
![image](https://github.com/Expensify/App/assets/25519849/76294775-5e18-4bbb-a2de-6a0e27063b09)

Live editor still does not working and it seems this is duplicated issue - https://github.com/Expensify/App/issues/41107
I checked that issue and this live editor does not work correct even though ExpensiMark converts Markdown to HTML correctly.

**Comment by tomekzaw** [comment] 2024-05-08 10:46
> Live editor still does not work and it seems this is duplicated issue

@skyweb331 `react-native-live-markdown` has its own bundle with ExpensiMark, you'll need to bump expensify-common in `react-native-live-markdown` as well as rebuild the JS parser

**Comment by skyweb331** [comment] 2024-05-08 10:51
@tomekzaw Maybe, because my update is not applied to `react-native-live-markdown` yet???
Just thought `react-native-live-markdown` does not working correctly like https://github.com/Expensify/App/issues/41107, which `ExpensiMark` parses Markdown to HTML correctly but results are not working.

Will you let me know how can I update `react-native-live-markdown` to use my current `ExpensiMark` in my node_modules folder???

**Comment by skyweb331** [comment] 2024-05-08 15:44
@sobitneupane Anyhow, the issue is related to `ExpensiMark` and my solution works fine on web, so it should work fine for Live Editor too. I am on checking if this works correctly on LiveEditor too.

**Comment by sobitneupane** [comment] 2024-05-13 09:28
Sorry for the delay here. I will try to review the proposal asap.

**Comment by sobitneupane** [comment] 2024-05-14 08:39
@skyweb331 Your proposal looks good to me.

Have you been able to test it in a live editor to ensure it works well?

**Comment by skyweb331** [comment] 2024-05-14 09:18
@sobitneupane  Just tested it on live editor too.
![image](https://github.com/Expensify/App/assets/25519849/4134416a-eb49-42fc-8884-697b7f265cee)

**Comment by sobitneupane** [comment] 2024-05-21 03:31
PR is ready for final review. Should be merged today/tomorrow.

**Comment by slafortune** [comment] 2024-05-23 22:41
PR is still being reviewed.  I'll be on vacation until June 4th, so adding another BZ in the meantime.

**Comment by sobitneupane** [comment] 2024-05-27 07:42
We are waiting for the final review in the PR from @thienlnam .

**Comment by thienlnam** [comment] 2024-05-28 22:33
Some commits need to be re-signed

**Comment by sobitneupane** [comment] 2024-05-31 05:42
PR is in review.

**Comment by skyweb331** [comment] 2024-06-03 19:52
@sobitneupane PR is merged into expensify-common, so not sure when it will be deployed...

**Comment by anmurali** [comment] 2024-06-05 02:39
Will check on this internally and update.

**Comment by sobitneupane** [comment] 2024-06-05 10:20
`expensify-common` was bumped and later reverted [here](https://github.com/Expensify/App/pull/42914) due to some issue. I think we should wait for the issue in `expensify-common` to be resolved before bumping the version.

**Comment by slafortune** [comment] 2024-06-10 19:07
@sobitneupane looks like this was [deployed](https://github.com/Expensify/App/pull/42914#issuecomment-2147613171) to production last week.

**Comment by sobitneupane** [comment] 2024-06-11 06:29
@skyweb331 `expensify-common` version is bumped. Can you please retest and verify that the issue is resolved.

**Comment by skyweb331** [comment] 2024-06-11 08:39
![image](https://github.com/Expensify/App/assets/25519849/f9dbd799-1ca0-4efe-b95b-8ce56ea7d7c3)
This is working fine on staging.

**Comment by sobitneupane** [comment] 2024-06-11 08:46
I can verify that the issue has been resolved.

<img width="1055" alt="Screenshot 2024-06-11 at 14 30 52" src="https://github.com/Expensify/App/assets/25876548/a709327b-9cf1-42e9-ac77-b1d250786473">

**Comment by skyweb331** [comment] 2024-06-11 08:47
Did you test it on production? I tested it but it does not work on production. Maybe because of cache???

**Comment by sobitneupane** [comment] 2024-06-17 07:37
The issue is not reproducible in production as well.

<img width="1066" alt="Screenshot 2024-06-17 at 13 22 17" src="https://github.com/Expensify/App/assets/25876548/495dd598-4457-457b-8eb0-df0d7db8cb7c">

**Comment by slafortune** [comment] 2024-06-17 19:54
The 18th will cover the regression period - so I can pay this out tomorrow.

**Comment by slafortune** [comment] 2024-06-19 16:18
@skyweb331 I am not able to locate your UpWorks profile - can you please link that here?

**Comment by skyweb331** [comment] 2024-06-19 16:27
@slafortune My upwork profile link is https://www.upwork.com/freelancers/~019e5171478d2a22f7

**Comment by slafortune** [comment] 2024-06-19 16:39
@skyweb331 offer sent - https://www.upwork.com/nx/wm/offer/102797646

**Comment by slafortune** [comment] 2024-06-19 16:51
@skyweb331 paid $250 via upworks
@sobitneupane owed for C+ $250 via NewDot

**Closed by slafortune** 2024-06-19 16:51 UTC
Labels: External, Daily, Overdue, Bug

**Comment by JmillsExpensify** [comment] 2024-06-22 16:45
$250 approved for @sobitneupane
