### ISSUE TITLE
[$500] Workspace – WS name and avatar changed to default after deleting WS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38505] opened 2024-03-18 19:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/38365
## Action Performed:
1. Log in
2. Create new WS
3. Change name and avatar
4. Go to chats
5. Go back to WS settings and delete WS
6. Go back to chats and observe WS name and avatar

## Expected Result:
WS name and avatar don’t change to default after deleting WS

## Actual Result:
WS name and avatar change to default after deleting WS

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bd093b31-1a8e-4624-87d0-038323493ba5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7aa9ecfc6f965dd</li>
        <li>Upwork Job ID: 1773074259104903168</li>
        <li>Last Price Increase: 2024-09-30</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @grgia</details>

**Comment by lanitochka17** [comment] 2024-03-18 19:16
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-18 19:16
We think that this bug might be related to #vip-vsp

**Comment by alexpensify** [comment] 2024-03-18 22:55
Adding this one to my testing list.

**Comment by alexpensify** [comment] 2024-03-20 17:28
No update yet

**Comment by alexpensify** [comment] 2024-03-22 19:33
I'll test this one soon.

**Comment by alexpensify** [comment] 2024-03-26 00:25
On my testing list

**Comment by alexpensify** [comment] 2024-03-27 19:44
I tested and confirmed that the avatar changes when you delete the workspace. The name does not change. 

## Before

![2024-03-27_12-42-47](https://github.com/Expensify/App/assets/8107070/7de21a30-9ad6-4cd0-bb86-12a7102b6b0b)

## After 
![2024-03-27_12-43-30](https://github.com/Expensify/App/assets/8107070/eed217c0-7f71-4f10-8ad7-39cc8b82e5b6)

**Comment by alexpensify** [comment] 2024-03-27 19:48
@alitoshmatov - we need to prevent the avatar from changing when a workspace is deleted. It looks like the other mention here does not appear in my recent tests.

**Comment by nkdengineer** [comment] 2024-03-28 01:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS name and avatar change to default after deleting WS

### What is the root cause of that problem?
We're clearing the workspace avatar [here](https://github.com/Expensify/App/blob/054d12914a6d1846b659237d3a6ce15def42124d/src/libs/actions/Policy.ts#L324) when deleting workspace.

### What changes do you think we should make in order to solve the problem?

Remote [this line](https://github.com/Expensify/App/blob/054d12914a6d1846b659237d3a6ce15def42124d/src/libs/actions/Policy.ts#L324) to preserve the workspace avatar after deleting. 

There might be similar back-end change needed.

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-03-28 01:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS name and avatar change to default after deleting WS

### What is the root cause of that problem?
We're clearing the workspace avatar [here](https://github.com/Expensify/App/blob/054d12914a6d1846b659237d3a6ce15def42124d/src/libs/actions/Policy.ts#L324) when deleting workspace. And after coming online, the workspace will be removed completely from Onyx.

### What changes do you think we should make in order to solve the problem?

Since after coming online, the workspace will be removed completely from Onyx. We'll need to add a new field `oldPolicyAvatar` in the workspace-related reports, just like we do for workspace name [here](https://github.com/Expensify/App/blob/054d12914a6d1846b659237d3a6ce15def42124d/src/libs/actions/Policy.ts#L355). Then when retrieving avatar for the report, we'll use `oldPolicyAvatar` of the report first if it exists. This is the same approach we currently use to preserve the policy name, that's why we can see the workspace name does not disappear, but the workspace avatar disappears.

There might be similar back-end change needed to add support for the `oldPolicyAvatar` field.

Optionallly, we can remove [this line](https://github.com/Expensify/App/blob/054d12914a6d1846b659237d3a6ce15def42124d/src/libs/actions/Policy.ts#L324) to preserve the workspace avatar in the `policy` in Onyx after deleting. 

### What alternative solutions did you explore? (Optional)
When retrieving the workspace avatar for display, for example in [here](https://github.com/Expensify/App/blob/054d12914a6d1846b659237d3a6ce15def42124d/src/libs/ReportUtils.ts#L1530), fallback to `avatarUrl` first, if `avatar` is empty.

Another approach is we can modify the back-end to still return the deleted policy in the API response (and subsequent ReconnectApp API calls), so we still have the policy data in the front-end to show in archived reports, ... but we don't show or have any entry point to that deleted policy's pages in the front-end if the policy was deleted.

**Comment by alexpensify** [comment] 2024-03-29 17:24
No update yet, this one needs a proposal review.

**Comment by alexpensify** [comment] 2024-04-01 23:18
@alitoshmatov - please keep me posted if you cannot review this one and I'll reassign it. Thanks!

**Comment by alitoshmatov** [comment] 2024-04-02 08:59
@alexpensify Sorry, had some work on my plate, please reassign.

**Comment by DylanDylann** [comment] 2024-04-02 09:01
I am happy to take over this one if @alitoshmatov is busy

**Comment by alexpensify** [comment] 2024-04-03 00:14
@DylanDylann you are up. I used the label to reassign a C+ via the auto-assigner for fairness and you were picked here. Please keep us posted if any of the proposals will help fix the issue. Thanks!

**Comment by DylanDylann** [comment] 2024-04-03 07:49
I agree with @nkdengineer that we should apply the same pattern as we did with the policy name. Let's go with [their proposal](https://github.com/Expensify/App/issues/38505#issuecomment-2024247435)

**Comment by DylanDylann** [comment] 2024-04-03 07:50
I agree with @nkdengineer that we should apply the same pattern as we did with the policy name. Let's go with [their proposal](https://github.com/Expensify/App/issues/38505#issuecomment-2024247435)

🎀 👀 🎀 C+ reviewed

**Comment by alexpensify** [comment] 2024-04-05 22:29
@grgia we need a PR review here. Thanks!

**Comment by grgia** [comment] 2024-04-08 09:26
@alexpensify I don't see a PR linked

@nkdengineer is your PR up?

**Comment by grgia** [comment] 2024-04-08 09:26
@nkdengineer all yours!

**Comment by nkdengineer** [comment] 2024-04-10 05:31
@DylanDylann The PR is [here](https://github.com/Expensify/App/pull/39986).

@grgia Please help to handle the change from back-end to add `oldPolicyAvatar` filed as well.

**Comment by alexpensify** [comment] 2024-04-16 00:38
@DylanDylann can you please review the PR that @nkdengineer shared here? Thanks!

**Comment by DylanDylann** [comment] 2024-04-16 02:35
@alexpensify The issue needs some changes from the BE side as mentioned [here](https://github.com/Expensify/App/issues/38505#issuecomment-2046567501). Waiting @grgia for updating in the BE

**Comment by grgia** [comment] 2024-04-18 10:32
@DylanDylann @nkdengineer the proposal mentioned BE changes only in the alternative section, could you please explain in detail what changes are required? Specifically, the command name, what it returns now, and what you need it to return.

**Comment by nkdengineer** [comment] 2024-04-22 02:23
@grgia We should return an extra field `oldPolicyAvatar` for report data in `OpenReport` and `OpenApp` API.

**Comment by alexpensify** [comment] 2024-04-26 21:16
@nkdengineer - to confirm, do you need that action before the PR can go through the review process? Thanks!

**Comment by alexpensify** [comment] 2024-05-01 23:49
@nkdengineer can we get an update here to my last question? Thanks!

**Comment by nkdengineer** [comment] 2024-05-02 04:03
> @nkdengineer - to confirm, do you need that action before the PR can go through the review process? Thanks!

Yes, we need this action before the PR can go through. If we don't have that, the PR will not works when we logout and login again because we only update the data in optimistic data, not update anything from BE.

> We should return an extra field oldPolicyAvatar for report data in OpenReport and OpenApp API.


cc @grgia

**Comment by alexpensify** [comment] 2024-05-03 17:06
Thank you for that update! 

## Heads up, I will be offline until Tuesday, May 7, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment] 2024-05-10 23:13
@grgia - any update here?

**Comment by alexpensify** [comment] 2024-05-17 16:37
## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by nkdengineer** [comment] 2024-05-23 07:59
@grgia Can you please take a look at this comment here https://github.com/Expensify/App/issues/38505#issuecomment-2068369871

**Comment by nkdengineer** [comment] 2024-06-04 02:38
@grgia Friendly bump.

**Comment by DylanDylann** [comment] 2024-06-19 08:10
@alexpensify Please help to add the [Hold BE] label.

**Comment by grgia** [comment] 2024-06-19 10:23
adding to hot picks and unassigning

**Comment by alexpensify** [comment] 2024-07-09 21:46
No update yet, this one is still a hot pick.

**Comment by DylanDylann** [comment] 2024-07-30 14:49
@alexpensify Any update here?

**Comment by alexpensify** [comment] 2024-08-01 01:08
No, it's still a hot pick

**Comment by alexpensify** [comment] 2024-08-21 19:29
Still a hot pick

**Comment by alexpensify** [comment] 2024-09-10 21:47
Hot Pick

**Comment by DylanDylann** [comment] 2024-09-24 03:54
@alexpensify Should we continue on this issue anymore? It has been delayed for 5 months

**Comment by alexpensify** [comment] 2024-09-25 21:26
@DylanDylann, good call; I'm going to close now.

**Comment by DylanDylann** [comment] 2024-09-26 09:20
@alexpensify Could you please hanlde payment in this issue? As mentioned on [Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1723055151068559?thread_ts=1723015261.405329&cid=C02NK2DQWUX), C and C+ should get fully paid because we are hired and did the work ([The PR](https://github.com/Expensify/App/pull/39986) was created)

cc @nkdengineer

**Comment by alexpensify** [comment] 2024-09-26 14:38
Thank you for flagging, my mistake here. Let me reopen and prepare the payment process tomorrow.

**Comment by alexpensify** [comment] 2024-09-30 19:31
Payouts due: 09-30-2024

- [ ] Contributor: $500 @nkdengineer - I need to create a new Upwork job 
- [ ] Contributor+: $500 @DylanDylann - I've paid 

Upwork job is [here](https://www.upwork.com/jobs/~01d7aa9ecfc6f965dd). This one falls under the $500 amount since it was opened before the pricing change.

**Comment by alexpensify** [comment] 2024-09-30 19:37
@nkdengineer - I sent an offer here: https://www.upwork.com/nx/wm/offer/104201713. Please accept and I can complete the payment process. Thanks!

**Comment by nkdengineer** [comment] 2024-10-01 17:07
@alexpensify Thanks! I accepted however it seems the issue number in the offer is incorrect (#45879). If possible please update it to avoid confusion later.

**Comment by alexpensify** [comment] 2024-10-01 23:47
@nkdengineer thanks for flagging that my edits didn't save, I created a new offer here: https://www.upwork.com/nx/wm/offer/104222417

I'll withdraw the other one and please accept the new one. Sorry for the extra step but Upwork is blocking me from edits.

**Comment by nkdengineer** [comment] 2024-10-02 02:47
@alexpensify Sure thing, I accepted

**Closed** 2024-10-02 21:39 UTC
Labels: Reviewing, Monthly, Internal, Bug, Hot Pick
