### ISSUE TITLE
Expensify Card - Blue outline does not wrap the user row properly when navigating via Tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44871] opened 2024-07-04 19:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applaus - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > More features
3. Enable Expensify Card
4. Navigate through user list via Tab key

## Expected Result:
The blue outline will wrap the user row properly

## Actual Result:
The blue outline does not wrap the user row properly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0078e80b-1ea8-4626-92f6-1ca40a8d2c50

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-04 19:56
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by tgolen** [comment] 2024-07-04 20:12
I am demoting this one since it doesn't impact the user and tab navigation is not a mainline flow.

**Comment by neonbhai** [comment] 2024-07-04 22:07
roposal

### Please re-state the problem that we are trying to solve in this issue.
Expensify Card - Blue outline does not wrap the user row properly when navigating via Tab

### What is the root cause of that problem?
We have incorrectly configured the styles on `WorkspaceCardListRow`:
https://github.com/Expensify/App/blob/77d380ce7d1fcaad2045a3c590dc16a1363d4cd1/src/pages/workspace/expensifyCard/WorkspaceCardListRow.tsx#L41-L43
We need to update these, so that blue border is applied correctly.

### What changes do you think we should make in order to solve the problem?
We should have `styles.selectionListPressableItemWrapper` as the wrapping styles on the Pressable [here](https://github.com/Expensify/App/blob/77d380ce7d1fcaad2045a3c590dc16a1363d4cd1/src/pages/workspace/expensifyCard/WorkspaceExpensifyCardListPage.tsx#L124-L128)

We should update the view styles [here](https://github.com/Expensify/App/blob/77d380ce7d1fcaad2045a3c590dc16a1363d4cd1/src/pages/workspace/expensifyCard/WorkspaceCardListRow.tsx#L42)

```jsx
<View style={[styles.flexRow, styles.flex1, styles.justifyContentBetween, styles.userSelectNone, styles.alignItemsCenter, style]}>
```

We should update the `contentContainerStyle` as `styles.mb3` for the `OfflineWithFeedback` [here](https://github.com/Expensify/App/blob/77d380ce7d1fcaad2045a3c590dc16a1363d4cd1/src/pages/workspace/expensifyCard/WorkspaceExpensifyCardListPage.tsx#L119-L123)

We will do other small adjustments to clean up the styles.

[Branch here](https://github.com/Expensify/App/compare/main...neonbhai:Expensify:fix-expensify-card-border?expand=1)

### Result

https://github.com/Expensify/App/assets/64629613/190aa1aa-a6d6-4818-b5a4-b73ca8e85480

**Comment by mountiny** [comment] 2024-07-04 22:28
Taking this on @koko57 @narefyev91 @allgandalf @DylanDylann 

Can you please handle this polish. thanks

**Comment by DylanDylann** [comment] 2024-07-05 05:31
@allgandalf @narefyev91 It seems this issue relates to your PR

**Comment by narefyev91** [comment] 2024-07-05 09:17
Please assign to me - will pick it up

**Closed** 2024-07-10 16:19 UTC
Labels: Reviewing, Engineering, Weekly
