### ISSUE TITLE
LHN - Page skeleton appears instead of LHN when going offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25436] opened 2023-08-17 21:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Remove old builds and instal iOS / Android App build 1.3.55.3
2. Login with any account
3. After LHN downloaded go offline

## Expected Result:
LHN keeps displayed when user goes offline

## Actual Result:
Page skeleton appears instead of LHN when going offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6c87cdce-cbf9-4cfc-9e1a-d16c88b3a228

https://github.com/Expensify/App/assets/78819774/567848fc-ab16-4387-9931-7f5e65e88651

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2023-08-17 22:20
This is a dupe of https://github.com/Expensify/App/issues/24573

**Closed** 2023-08-17 22:20 UTC
Labels: Engineering, Hourly
