### ISSUE TITLE
[$250] Send Money - Incorrect chat conversation displayed after send money to non-existing account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9084] opened 2022-05-18 23:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing PR:** https://github.com/Expensify/Web-Expensify/pull/33293

## Action Performed:
1. Go to staging.new.expensify.com
2. Login and click on Send money
3. Put in an amount and tap Continue
4. Enter the email of a non-existing account
4. Select "I'll settle up elsewhere"

## Expected Result:
Correct chat conversation displayed after send money to non-existing account

## Actual Result:
Incorrect chat conversation displayed after send money to non-existing account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.63.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

https://user-images.githubusercontent.com/93399543/169173654-cdacbba6-7fff-47d6-9044-b85d6caad024.mp4

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment] 2022-05-19 14:57
Oh wow... yes, terrible bug.

**Comment by thesahindia** [comment] 2022-05-19 19:12
This bug isn't only about non-existing accounts. We just don't navigate to the report when a user sends money. 

### Proposal

When a user sends money [payIOUReport](https://github.com/Expensify/App/blob/11a1f0debac2dfee461e6b71751c3b3bcfb9f2cf/src/libs/actions/IOU.js#L285) gets called, inside the function after the api request we get two reports in the response the first one contains the reportID of the report that the user send money to we can just access that and we need to navigate user to that report.

To do this we can use this code -

```js
            const userReportID = lodashGet(_.first(_.values(response.reports)), 'reportID', '');
            Navigation.navigate(ROUTES.getReportRoute(userReportID));
```
(not sure what should be the variable name)

After this -
https://github.com/Expensify/App/blob/11a1f0debac2dfee461e6b71751c3b3bcfb9f2cf/src/libs/actions/IOU.js#L312-L325

**Comment by adelekennedy** [comment] 2022-05-20 17:57
[Internal](https://www.upwork.com/ab/applicants/1527709952287178752/job-details)
[External](https://www.upwork.com/jobs/~01fad31b09e62ce761)

**Comment by flodnv** [comment] 2022-05-30 10:31
@parasharrajat can you please review the proposal from @[thesahindia](https://github.com/thesahindia)?

**Comment by parasharrajat** [comment] 2022-05-30 10:32
Oh. I didn't see the proposal. I will review this today.

**Comment by parasharrajat** [comment] 2022-05-30 14:59
https://github.com/Expensify/App/pull/6992 shows that this is expected behavior.  cc: @flodnv @iwiznia 

@thesahindia Your proposal is half of the needed solution. We indeed navigate after sendMoney request is completed but it does not navigate to the report that we sent money. So Instead of your solution we need to correct the existing navigation logic (If this change is needed).

**Comment by flodnv** [comment] 2022-05-30 16:52
>https://github.com/Expensify/App/pull/6992 shows that this is expected behavior. cc: @flodnv @iwiznia

😕 @marcaaron any thoughts on that?

**Comment by iwiznia** [comment] 2022-05-31 21:27
Oh damn, when I looked at it I thought the same thing, but then for some reason thought the request was showing in the chat you had selected. I now realize that request was already there. I agree to close this out as this is not a bug.

**Comment by flodnv** [comment] 2022-06-01 10:35
Agree

**Comment by Justicea83** [comment] 2022-06-06 18:31
Agree

**Comment by adelekennedy** [comment] 2022-06-06 18:36
@flodnv @iwiznia @marcaaron are we good to close this?

**Comment by iwiznia** [comment] 2022-06-06 19:13
Yep

**Comment by madmax330** [comment] 2022-09-12 12:01
@iwiznia why did you put 👎🏽  on the regression comment? The issue that it mentioned (https://github.com/Expensify/App/issues/10902) is the same as this one no? 
So there was a regression somewhere right?

**Comment by iwiznia** [comment] 2022-09-12 12:10
This issue was closed with no changes, so it can't have caused a regression. We decided this is not a bug.

**Closed by iwiznia** 2022-09-12 12:10 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
