### ISSUE TITLE
[$500] [HOLD for payment 2024-02-14] mweb - Compose - Tapping emoji picker, keypad pops up on emoji box page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35720] opened 2024-02-02 20:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.5.36.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4279600
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Tap emoji picker from compose box

## Expected Result:
When user taps emoji picker, keypad must not pop up on emoji box page

## Actual Result:
When user taps emoji picker, keypad pops up on emoji box page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/08e0145a-937a-4cd8-acf1-3261f8d64e2e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad9a549f2e03c9fe</li>
        <li>Upwork Job ID: 1757788628485996544</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-02 20:45
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by aldo-expensify** [comment] 2024-02-02 20:59
Reproduced in `staging` and can't reproduce in `production`

https://github.com/Expensify/App/assets/87341702/896e1ff4-53d3-42e5-84ae-fd0af89f4c44

**Comment by aldo-expensify** [comment] 2024-02-02 21:45
Sorry, got distracted with other issues. I think the keyboard appears immediately because the "Search" field gets automatically focused. I don't see that auto-focus in production.

**Comment by francoisl** [comment] 2024-02-02 22:16
This might not be worth being a blocker, but yes ideally we'd stay consistent with other platforms and not show the keyboard.

**Comment by francoisl** [comment] 2024-02-02 22:25
Could be a red herring but this PR from the checklist modified the EmojiPicker https://github.com/Expensify/App/pull/34581

**Comment by aldo-expensify** [comment] 2024-02-02 22:49
> Could be a red herring but this PR from the checklist modified the EmojiPicker https://github.com/Expensify/App/pull/34581

I noticed this PR, but it doesn't appear to be in staging yet, or at least the comment of deployment to staging is missing

**Comment by aldo-expensify** [comment] 2024-02-02 22:56
Seems like I'm wrong and the https://github.com/Expensify/App/pull/34581 is already merged in version `v1.4.36-0` unless I'm looking at the wrong things

**Comment by aldo-expensify** [comment] 2024-02-02 23:04
tested a revert of the PR https://github.com/Expensify/App/pull/35737 and it does fix the deploy blocker

**Comment by francoisl** [comment] 2024-02-02 23:04
Hm yeah there was supposed to be a comment in the PR saying that it was deployed to staging, looks like a bug :(
I checked the `1.4.36-0` tag locally and the code from that PR is definitely on it, so yes it's deployed to staging at the moment.

**Comment by aldo-expensify** [comment] 2024-02-02 23:06
Thanks @francoisl for the help, and yess, the missing comment mislead me, I won't trust that anymore :P

**Comment by francoisl** [comment] 2024-02-02 23:35
Sounds good, feel free to send the PR my way and we can CP it.

**Comment by aldo-expensify** [comment] 2024-02-02 23:50
> Sounds good, feel free to send the PR my way and we can CP it.

In case they prefer to do some easy/quick fix rather than reverting, I was going to wait till Monday since we are not deploying today anyways. What do you think?

**Comment by francoisl** [comment] 2024-02-02 23:57
Good idea, at least we'll have the revert as an option on Monday if it's still blocking the deploy.

**Comment by TMisiukiewicz** [comment] 2024-02-05 07:16
Working on a fix

**Comment by mountiny** [comment] 2024-02-05 11:49
Demoting this from a deploy blocker, I see a fix has been raised but I dont think we have to CP

**Comment by roryabraham** [comment] 2024-02-05 18:14
PR merged, but per @mountiny's comment I'm not going to request CP. Sorry we missed this in the previous PR, and thanks @aldo-expensify for giving @TMisiukiewicz some time to fix this, good call 👍🏼

**Comment by jjcoffee** [comment] 2024-02-13 12:41
No payment required here as it was a regression fix!

**Comment by alexpensify** [comment] 2024-02-14 15:30
@jjcoffee - another one to accept, thanks! 

https://www.upwork.com/jobs/~01ad9a549f2e03c9fe

**Comment by jjcoffee** [comment] 2024-02-14 15:38
@alexpensify Ah sorry, I think no payment is due on this one as it was just a minor regression fix!

**Comment by alexpensify** [comment] 2024-02-14 18:44
@jjcoffee thanks for flagging, let me review and I'll reply tomorrow with an update.

**Comment by alexpensify** [comment] 2024-02-15 23:20
Ok, I've closed the job in Upwork but still left positive feedback. Thanks again for your help and flagging the payment breakdown here.

**Closed by alexpensify** 2024-02-15 23:20 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment
