### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] iOS - back button position on skeleton loader and 'Hmm its not here' page is different

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34915] opened 2024-01-22 19:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4210614
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Login with any user and minimize the app
3. From any other app (eg: Slack, gmail) open any non existing link eg: staging.new.expensify.com/anything
4. Observe that when skeleton loader is displayed, back button position is slightly on right and when 'Hmm its not here' page is displayed, back button position is shifted slightly on left More explanation: https://applause-ts.slack.com/archives/G01CL838B8T/p1705942846594149

## Expected Result:
App should keep a constant position for back button on all the pages

## Actual Result:
Back button shifts slightly to left when page changes from skeleton loader to 'Hmm its not here' page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4ab5cdb1-6ac0-4e9a-9055-802644af8bc9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b2a0aec800ce383</li>
        <li>Upwork Job ID: 1749515068968927232</li>
        <li>Last Price Increase: 2024-01-22</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28120114</li>
<li>dukenv0307 | Contributor | 28120116</li>
</ul></li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-01-22 20:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The layout shifts between the loading skeleton and the not found page.

### What is the root cause of that problem?
The app uses a common <HeaderwithBackButton/> Component. However the loading skeleton does not render this same component, it has it's own implementation <ReportHeaderSkeletonView />where the styling differs.

### What changes do you think we should make in order to solve the problem?
We should update the ReportHeaderSkeletonView styling to match that of HeaderwithBackButton to get a consistent styling.

We should reuse the layout styling so that it's maintaing in one place.


### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2024-01-23 07:36
[Proposal here](https://github.com/Expensify/App/issues/34915#issuecomment-1905259580) by @dukenv0307 looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by amyevans** [comment] 2024-02-01 23:36
Hmm realizing we've never had a BZ assigned here

**Comment by c3024** [comment] 2024-02-05 17:05
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
 
* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: This is a very minute style mismatch of the back arrow when not found page is displayed after a skeleton loading page. No specific PR needs to be held responsible.
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: NA
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not started because it cannot help in identifying this earlier.
* [x]  [@c3024] Determine if we should create a regression test for this bug. This is a minor style mismatch that occurs in a rare case. So, regression test is not required.
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. NA

**Comment by JmillsExpensify** [comment] 2024-02-07 02:44
@c3024 Do you agree with the regression comment above? If so, then I'll update the payment summary based on that.

**Comment by JmillsExpensify** [comment] 2024-02-08 23:07
Quick reminder on the comment above.

**Comment by c3024** [comment] 2024-02-09 14:40
> Another regression - #35892

@JmillsExpensify 

No, I don't think that regression was caused by PRs related to this issue. That was caused by a commit unrelated to this PR. Here is [more information](https://github.com/Expensify/App/issues/35892#issuecomment-1936047010) about it.

**Comment by JmillsExpensify** [comment] 2024-02-10 17:50
Great, thank you! Payment summary as follows:

 - Contributor: @dukenv0307 $500
 - Contributor+: @c3024 $500

**Comment by JmillsExpensify** [comment] 2024-02-10 17:52
All contributor offers paid and no regression test required. Closing this issue out!

**Closed by JmillsExpensify** 2024-02-10 17:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
