### ISSUE TITLE
[HOLD for Payment [2024-05-15][$250] [Search v1] Resizing the screen to switch from the large screen to small screen breaks the back navigation on RHP.

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#41579] opened 2024-05-03 14:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed
cc @adamgrzybowski @Kicu @WojtekBoman 

1. On web only
2. Open the search page, `Profile > Troubleshoot > New Search Page`
3. Click on a transaction
4. Verify that it opens in the RHP
5. Resize the window to the narrow view
6. Click the back button
7. Verify that it navigates to a not found page and the URL is `/Search_Bottom_Tab`

## Expected Result:
Navigation should work

## Actual Result:
Navigation is broken

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/22219519/0e7d557e-41c2-4780-b381-3dbfa5554d6d

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017875690bb8f76af2</li>
        <li>Upwork Job ID: 1786402424713957376</li>
        <li>Last Price Increase: 2024-05-03</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by luacmartins** [comment] 2024-05-03 18:19
@cretadn22 your solution looks hood. Maybe we can use a ternary though for simplicity and also apply the solution for the other headers in the RHP.

**Comment by Christinadobrzyn** [comment] 2024-05-08 08:50
looks like PR is in the works! https://github.com/Expensify/App/pull/41611

**Comment by luacmartins** [comment] 2024-05-08 14:52
That PR has been merged. Just waiting on deploy.

**Comment by Christinadobrzyn** [comment] 2024-05-14 08:13
PR in production on May 9th payment due May 16th.

**Comment by Christinadobrzyn** [comment] 2024-05-14 08:18
Payouts due:

- [ ] Contributor: $250 @cretadn22 (Upwork offer - https://www.upwork.com/nx/wm/offer/102298899)
- [ ] Contributor+: $250 @DylanDylann (upwork offer - https://www.upwork.com/nx/wm/workroom/37183705/overview)

Upwork job is [here](https://www.upwork.com/jobs/~017875690bb8f76af2).

Do we need a regression test for this?

**Comment by luacmartins** [comment] 2024-05-14 09:11
No test needed, we'll add when we wrap up the project.

**Comment by Christinadobrzyn** [comment] 2024-05-16 08:28
Awesome, thanks @luacmartins. Paid this out based on this [payment summary](https://github.com/Expensify/App/issues/41579#issuecomment-2109565494). Closing!

**Closed by Christinadobrzyn** 2024-05-16 08:28 UTC
Labels: Reviewing, External, Weekly, Bug
