### ISSUE TITLE
[$500] Chat - Multiline code block (three back ticks) using makes the hyperlink broken

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34678] opened 2024-01-17 21:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open Expensify App
2. Log in
3. Open any chat
4. In compose box enter any link for example google.com and send
5. Tap and hold on the sent link in the step 4
6. Select Edit comment
7. Enter three back ticks inside the square brackets for example [```google.com```]
8. Send the link

## Expected Result:
The hyperlink should not be broken even if multiline code block (three back ticks) is used

## Actual Result:
The hyperlink is broken if multline code block is used

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1e0dc5a3-5d70-4594-8529-ec74ac9a0887

![Bug6345774_1705524199886!IMG_20240117_234237](https://github.com/Expensify/App/assets/78819774/5e3ea770-6a25-4af3-bacc-2659f17c79a5)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a4dae0f313f46d1</li>
        <li>Upwork Job ID: 1747734779200806912</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-17 21:38
[#vip-vsb](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ)

**Comment by agilejune** [comment] 2024-01-18 00:41
![image](https://github.com/Expensify/App/assets/86615752/1140fd12-2260-4747-a6c6-52f7aff8ac65)

it's expected behavior

**Comment by zickezacke** [comment] 2024-01-18 03:40
### Issue
The issue is related when an edit action is triggered for an http link. 
### Cause
The cause is due to the getActionText function in file ContextMenuActions.tsx line 33. 
This function retrieves the last message from the Onyx store.
A link is stored in following form at the moment:
```
[link](https://link)
```
The issue is not limited to editing the link within the `[]` by adding `''`. Another issue occurs when the link within the `()` is edited which will cause an inconsistency between the link items between `[]` and `()` not matching anymore.
### Solution
Implement a new feature for the `getActionText` function which handles link values accordingly by returning the link as shown in the chat window.
Additionally I suggest to add a sanitation feature which checks the link prior storing the result in the Onyx key/value store. The color of the text field can be changed to red in case a link is malformed like: `htp://test.com`.

I have the local development environment running and was able to reproduce the problem.
I feel confident to have a solution in a timely manner ready.

**Comment by zickezacke** [comment] 2024-01-19 01:18
Contributor details
Your Expensify account email: [zickezacke@gmail.com](mailto:zickezacke@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01d632f2317d732aa4

**Comment by zickezacke** [comment] 2024-01-19 13:27
> You can't make the whole multi-line codeblock a link. Why would anyone need that?

Thank you for your feedback, I wasn't referring to make it a link. I suggest to keep the entered content the same format like it was entered. In above example of the issue:
```
User entered: google.com
```
When edit action is triggered:
```
Show: google.com for editing without the braces.
```

**Comment by allroundexperts** [comment] 2024-01-21 23:16
Is this a bug really? And are we sure that its worth fixing?

**Comment by zickezacke** [comment] 2024-01-22 02:05
Great question.
I understand:
1. User enters an address like. test.com
2. Edit shows : [test.com](http://test.com)
The entered link is not consistent with the edit link.
Therefor the issue with the editing was reported. 
Thoughts?

**Comment by cubuspl42** [comment] 2024-01-22 09:37
> [#vip-vsb](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ)

I'm not sure what the context here is. I guess that we're talking about a concern raised by an important client.

If this weren't the case, it would be a no-brainer to close this issue immediately.

Still, the first action would be asking them what they actually expect here, as a multi-line codeblock being a giant link is something I've never seen. It makes little sense to me.

**Comment by stephanieelliott** [comment] 2024-01-24 00:08
> [#vip-vsb](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ)

This is an internal project -- not tied to a client or customer! Agree that this is probably not worth fixing, let's close it!

**Closed by stephanieelliott** 2024-01-24 00:08 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by cubuspl42** [comment] 2024-01-24 08:56
For future reference, it's not only not worth fixing, but not a bug at all. Works as expected. ExpensiMark is inspired by MarkDown and is nearly compatible with it. MarkDown is currently specified in the CommonMark specification. CommonMark classifies multi-backtick code blocks as _blocks_, while links are _inlines_. You can never wrap a block with an inline in CommonMark; it's impossible by definition.

**Comment by zickezacke** [comment] 2024-01-24 13:52
While the current edit feature is using the correct MarkDown syntax, is it expected that an end user has knowledge of how to use MarkDown to edit the field?

**Comment by cubuspl42** [comment] 2024-01-25 09:55
No, it's not. The users can follow the Expensify help pages.

Relating to MarkDown/CommonMark can help us decide what is an expected behavior and how we want to shape ExpensiMark, so it is based on the battle-tested standard solution unless we know we want to deviate.
