### ISSUE TITLE
Task – Error message appears when mark as complete the task as group external user

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36874] opened 2024-02-20 11:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login
3. Navigate to a Group Chat
4. Click on the + in the compose box and select "Assign task"
5. Enter a Title and assign a user who is NOT part of the group and that you have access to
6. Create the task
7. Log in as the user that was assigned the task
8. Click on the task report/conversation
9. Click on complete the task

## Expected Result:
Task is marked as complete

## Actual Result:
Error message appears when mark as complete the task as user C (task assignee, not task creator, not group member). The red dot appears in LHN and not disappearing after dismissing the error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0a5f2f73-1273-4e03-898a-58892162597b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c97b911e31ddbd1b</li>
        <li>Upwork Job ID: 1770164676400545792</li>
        <li>Last Price Increase: 2024-03-19</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-20 11:59
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by sonialiap** [comment] 2024-02-26 14:41
[Checking if part of vip-vsb](https://expensify.slack.com/archives/C066HJM2CAZ/p1708958472801599)

**Comment by sonialiap** [comment] 2024-02-27 09:37
Added to vsb and moved to weekly because we're not fixing bugs yet

**Comment by sonialiap** [comment] 2024-03-05 15:55
Changing to weekly because we're not fixing bugs yet

**Comment by sonialiap** [comment] 2024-03-11 12:36
Bugs are in the future ✨

**Comment by sonialiap** [comment] 2024-03-26 18:27
The future is not overdue

**Comment by sonialiap** [comment] 2024-06-04 14:20
Still on hold for the _future_

**Comment by sonialiap** [comment] 2024-07-09 10:26
This has been waiting for the "future" for quite a while so I've asked for a retest in QA

**Comment by kbecciv** [comment] 2024-07-09 11:47
Issue is still reproducible 

https://github.com/Expensify/App/assets/93399543/01066d2b-bd46-41f5-a109-16a295f1292f

**Comment by sonialiap** [comment] 2024-07-09 15:31
Thanks Katya!

Keeping the issue open to be fixed once priority is increased

**Comment by sonialiap** [comment] 2024-07-24 12:45
Closing per this [thread](https://expensify.slack.com/archives/C066HJM2CAZ/p1721760866963099?thread_ts=1721729395.916419&cid=C066HJM2CAZ)

**Closed by sonialiap** 2024-07-24 12:45 UTC
Labels: Engineering, Monthly, Internal, Bug
