### ISSUE TITLE
[$500] Chat - Reply chat notification email with markdown text does not show it in the app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34665] opened 2024-01-17 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app and log in with account A
2. Go to a chat with account B with an email you have access to
3. Send dome messages, but do not read them with the receiver account
4. Go to account B email and look for the chat notification email
5. Reply it with a markdown text
6. Go to the chat again as account A

## Expected Result:
Markdown text should be displayed on the chat

## Actual Result:
The text is displayed without markdown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6345623_1705515831687!image](https://github.com/Expensify/App/assets/78819774/bdbb9477-43c2-48e1-81fd-a648d21d32e2)

![Bug6345623_1705515831686!IMG_2467](https://github.com/Expensify/App/assets/78819774/aa7a6bf5-dcf6-45eb-9bb2-746ea40840df)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f8f3d47ee75887e</li>
        <li>Upwork Job ID: 1747717905448091648</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2024-01-17 20:58
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Email chat replay with markdown text is displayed without markdown

## What is the root cause of that problem?

The payload that comes from the back-end is not formatted the same as say a comment with markdown is formatted when posted via composer, this causes the `ReportActionItemFragment.js` to render the markdown comment as unformatted.

## What changes do you think we should make in order to solve the problem?

Check the payload type that's comming from back-end and apply the same markdown formatter to the text of the comment which will render it correctly as formatted markdown.

**Comment by ikevin127** [comment] 2024-01-17 22:10
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Email chat replay with markdown text is displayed without markdown.

## What is the root cause of that problem?

The payload that comes from the back-end is not formatted the same as say a comment with markdown is formatted when posted via composer, this causes the `ReportActionItemFragment.js` to render the markdown comment as unformatted.

Whenever any kind of comment is coming from email reply, markdown or not it is wrapped in `<div dir="ltr">whatever</div>` which just renders the plain text within the div.

## What changes do you think we should make in order to solve the problem?

Within `RenderCommentHTML.js` filter out the wrapping div for email source comments via regex then apply `parser.replace` which replaces markdown with corresponding html element for any valid markdown.


## Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/56457735/b94970bf-2e10-478d-b86d-d7b2b5c9e6fb

</details>

**Comment by zanyrenney** [comment] 2024-01-22 18:13
@thesahindia what do you think about the proposal above, can you review please?

**Comment by zanyrenney** [comment] 2024-01-23 17:53
bump @thesahindia

**Comment by Beamanator** [comment] 2024-01-25 09:10
Hmm I believe that proposal could work, but I also think this could be useful to try to "fix" / change in the backend, no? I think this would benefit from some internal investigation to figure out why / if we need this wrapping div, on email responses

**Comment by ikevin127** [comment] 2024-01-25 11:07
@Beamanator @thesahindia Actually, while I was testing my fix against our [ExpensiMark](https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js) library which parses markdown and I found out there's more than just the div that we have to remove in order to render the expected markdown in the chat.

This is the regex map I came up with after going line-by-line against our [ExpensiMark](https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js) library source and sending all types of markdown from email reply:
```javascript
COMMENT_HTML_REGEX_MAP: {
        '<div dir="ltr">|<\\/div>': '', // the initial wrapping div
        '<a href="(.*)">(.*)<\\/a>': '$1', // when we post [some link](https://www.google.com) the email formatting adds a wrapping a tag around the link
        '<br \\/>': '\n', // when we use newline in comment via email
        '@mailto:': '@', // when we post [some email](test@email.com) // the email formatting adds `@mailto:` in front of the email
        '&gt;': '>', // the email replaces > with &gt;
        '&lt;': '<', // the email replaces < with &lt;
        'mailto:': '', // for the ExpensiMark `autoEmail` case, the email formatting adds mailto: in front of it
    }
```

All these need to be replaced with their correct keys from the map in order to be rendered correctly as expected by the ExpensiMark in the front-end - which will match and align with the markdown we can send from the composer.

**Note**: this happens regardless, because of how the email client is formatting different markdown. The back-end would basically have to do the exact same thing using this regex map and replace the email formatting.

I have the PR ready to go if we decide to do this from the front-end side 🚀

### Updated [proposal](https://github.com/Expensify/App/issues/34665#issuecomment-1897065165)
- added the newfound details explained above

**Comment by zanyrenney** [comment] 2024-01-26 12:51
@Beamanator let us know what you think of the updated proposal with your feedback!

**Comment by Beamanator** [comment] 2024-01-26 14:38
Hmm here's my thoughts:
1. If there's more than 1 type of mapping / markdown that's broken, it would be great to fix them all at once (or as many as we can right now) instead of 1 by 1
2. If we want to do ^, I think we should make sure we're clear about what doesn't work correctly (& how to reproduce) so we can be 100% sure the fix DOES work, during testing & after the fix goes live
3. About the `type OriginalMessageSource` bug, this would be great to comment in the original PR (if you haven't already) since the typescript migration is currently ongoing

> Note: this happens regardless, because of how the email client is formatting different markdown. The back-end would basically have to do the exact same thing using this regex map and replace the email formatting.

Hmm so @ikevin127 you're basically saying this mapping you created probably needs to be implemented in the client or backend side, right? 

What do you think @thesahindia ?

**Comment by ikevin127** [comment] 2024-01-26 15:01
Fully agree with 1 and 2 🚀

As for 3 I will look into it as I don't think it's a typescript migration issue but something changed in that we're getting an object now instead of a string from the `source` prop in the `RenderCommentHTML.tsx` component.

This is most likely coming from a parent up in the stack. 🔍 I will look into it and try to find what changed recently that prompted getting an object instead of a string for the `source` prop. 

> you're basically saying this mapping you created probably needs to be implemented in the client or backend side, right?

It can be done on either side, but it's less work if we process this in the front-end since the back-end, besides using the regex map to remove / replace the formatting added by the email client, I assume they would also have to format the response sent to the front-end to match the response we get when posting markdown via the composer.

Ultimately, I'm cool with either side handling this - I'll leave it to your discretion 🙌

**Comment by zanyrenney** [comment] 2024-01-29 12:13
bump @Beamanator which path forward should we opt for?

**Comment by Beamanator** [comment] 2024-01-30 11:09
Thanks for your responses so far @ikevin127 ! One final potential concern I have is: We *currently* have 3 codebases for our 3 "front ends" - NewDot, OldDot, and OldApp. If we do this mapping in "the front end" won't we have to do the same mapping in all 3 places?

**Comment by ikevin127** [comment] 2024-01-30 11:14
This particular issue is targeting ND, beyond that it's above my knowledge.

I guess for the other 2 FE codebases we have to ask the team if we even have any markdown posting capabilities in the chat.

If not, a FE fix can work here. If not then there's no choice then to go with a BE fix.

**Comment by Beamanator** [comment] 2024-02-01 11:40
Sorry I'm not planning to prioritize this till next week, I'll def post back here when I have some next steps!

**Comment by zanyrenney** [comment] 2024-02-05 17:35
waiting on @Beamanator priority.

**Comment by zanyrenney** [comment] 2024-02-08 16:36
@Beamanator any chance you can take a look at this one now please?

**Comment by Beamanator** [comment] 2024-02-13 14:41
@zanyrenney this isn't part of a VIP or wave, so I haven't been prioritizing it - do you think I really need to get to work on it ASAP? It seems like an edge case, I don't know anyone who replies to emails using markdown 😅

**Comment by zanyrenney** [comment] 2024-02-15 19:13
Fair challenge @Beamanator if we don't think this a priority, let's make it weekly for now then.

**Comment by zanyrenney** [comment] 2024-02-27 14:22
is weekly still appropriate? @Beamanator

**Comment by Beamanator** [comment] 2024-02-28 15:07
Merp,  good question - I honestly think `monthly` would be a fine priority level, I don't see people responding via email in markdown format often at all -  I'm also heading OOO on Friday for 8 days - so we can either look for volunteers to pick this up in the meantime or else I can stay assigned to try to pick this up in March

**Comment by zanyrenney** [comment] 2024-03-11 10:38
changing to monthly as per the guideance above from @Beamanator

**Comment by zanyrenney** [comment] 2024-03-19 17:48
I think we can close this based on this question from the BZ team analysis:
**Is this truly a high enough priority / ROI bug to fix?**
Will this affect more than x # of users?
Does it affect users who pay us?
**How much of an edge case is it?**
**If we fix the bug later, in a year or two, will that be OK?**

**Closed by zanyrenney** 2024-03-19 17:48 UTC
Labels: Engineering, Monthly, Internal, Bug
