### ISSUE TITLE
[$1000] Workspace - User is allowed to create 2 workspaces in the same name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24488] opened 2023-08-12 17:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Workspaces
4. Tap new workspace
5. Tap on workspace name
6. Change name to "v"
7. Tap save
8. Follow step2-step7 and create another workspace in the same name "v"

## Expected Result:
User should not be allowed to create 2 workspaces in the same name

## Actual Result:
User is allowed to create 2 workspaces in the same name "v"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c0e90030-d9a0-44be-b6d4-466b21be0843

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a918b4f91b57aa4</li>
        <li>Upwork Job ID: 1691205791973748736</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by iSatVeerSingh** [comment] 2023-08-15 07:06
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The user is allowed to create 2 workspaces with the same name.

### What is the root cause of that problem?
Currently, we do not validate if the workspace name or policy name in all policies list already exists or not. We are not showing an error if the workspace already exists.

### What changes do you think we should make in order to solve the problem?
1. Write a function in [Policy.js](https://github.com/Expensify/App/blob/main/src/libs/actions/Policy.js) to check if workspace name or policy name already exists or not.
```js
/**
 * Check if the workspace already exists or not. Return true if workspace name or policy.name already exists.
 * @param {String} worksapceName
 * @returns {Boolean}
 */
function isExistingWorkspace(worksapceName) {
    return _.some(allPolicies, (policy) => policy.name === worksapceName)
}
```
2. Add an if condition in [WorkspaceSettingsPage.js](https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/pages/workspace/WorkspaceSettingsPage.js) to validate new workspace name and show an appropriate error if workspace name is not valid.
```js
else if (Policy.isExistingWorkspace(name)) {
            errors.name = 'workspace.editor.nameAlreadyExistsError';
}
```
3. Add `nameAlreadyExistsError` in [languages](https://github.com/Expensify/App/blob/main/src/languages/en.js) in workspace.editor object to define an error message.
[en.js](https://github.com/Expensify/App/blob/c43491adbdde7346aba6e808d3581549b9b1624c/src/languages/en.js#L1267)
```js
nameAlreadyExistsError: 'Workspace with that name already exists.',

```
[es.js](https://github.com/Expensify/App/blob/c43491adbdde7346aba6e808d3581549b9b1624c/src/languages/es.js#L1278)
```js
nameAlreadyExistsError: 'El espacio de trabajo con ese nombre ya existe.',

```
4. if user is at workspace settings page and decided to not to change the name, he can simply go back without changing the name.

Here is screencast for this solution.
[Screencast from 2023-08-15 11-58-57.webm](https://github.com/Expensify/App/assets/85070570/d32d2904-4d83-44c5-8837-ce7d0823630d)


### What alternative solutions did you explore? (Optional)
There is also another situation. For example, the user is at the workspace setting page and 
try to save name without changing it, we ask the user to 'Please change name or Go back to workspaces to keep it unchanged'. it is more user friendly. 

For this we can add another logic in `isExistingWorkspace` function to check if user is trying to save name without changing it. I have already code for this in my mind.

I can submit PR with all above code within just 1 hour.

**Comment by iSatVeerSingh** [comment] 2023-08-15 07:09
Contributor details
Your Expensify account email: developer.satveer@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016bb3597ed6938fbc

**Comment by iSatVeerSingh** [comment] 2023-08-15 10:38
@parasharrajat Can you please review proposals on this?

**Comment by shubham1206agra** [comment] 2023-08-15 12:43
This is intentional
https://github.com/Expensify/App/issues/23448#issuecomment-1650133087

**Comment by iSatVeerSingh** [comment] 2023-08-15 13:29
@shubham1206agra Two workspace with same name does not make any sense. If users are allowed to make workspace with same name, then what is the purpose of workspace. In any application, workspace concept exits, so user can categorise things according to their needs. Any user identify its workspace by name. If user can make multiple workspace with same name, how will he know, what thing he put in which workspace. Tell me how workspaces with same name make sense????

**Comment by johncschuster** [comment] 2023-08-15 19:55
I'm still working on finding the conversation in which we decided the behavior was intentional. Once I locate it, I'll report back!

**Comment by Premsjce** [comment] 2023-08-23 00:59
This was raised earlier, and was closed saying intentional

https://github.com/Expensify/App/issues/23448

**Comment by johncschuster** [comment] 2023-08-28 14:34
@parasharrajat thanks for the bump! No, I haven't been able to find the conversation yet. Let me bump some folks and see what I can find!

**Comment by johncschuster** [comment] 2023-08-29 19:59
I bumped the linked issue above to find the expected behavior. The BZ team member is currently OOO, but it looks like they'll be back online tomorrow, so I should have a response soon!

**Comment by johncschuster** [comment] 2023-09-05 20:16
I'm still chasing down the expected behavior.

**Comment by johncschuster** [comment] 2023-09-05 20:17
As of now, it's my understanding that this behavior is expected.

**Comment by johncschuster** [comment] 2023-09-06 20:34
From Ben:

> From memory, it was a two stage slack process - in https://expensify.slack.com/archives/C049HHMV9SM/p1682075335194889, the same issue had been raised, and that itself had been back-linked to https://expensify.slack.com/archives/C049HHMV9SM/p1682086817167539?thread_ts=1682075335.194889&cid=C049HHMV9SM, where Georgia/Shawn confirmed things were as expected

**Comment by johncschuster** [comment] 2023-09-13 21:14
Thanks, @parasharrajat! I'm going to close the issue since the behavior is expected.

**Closed** 2023-09-13 21:14 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
