### ISSUE TITLE
[HOLD for payment 2023-09-27] [HOLD for #26747] [$1000] Request money - Amount is partially covered by top selection menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24603] opened 2023-08-15 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**issue found when executing PR** https://github.com/Expensify/App/pull/23698
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Tap the green plus button
4. Tap on "Request money"

## Expected Result:
Amount should be fully visible

## Actual Result:
The amount is partially covered by top selection menu (because of the banner on top of the screen)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0576f922-c093-44c2-9016-e6184fe3ec34

![Bug6166123_IMG_E8963](https://github.com/Expensify/App/assets/78819774/b59e819b-f45d-414b-8b7b-bb53da502f61)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152c32e49ad0a8a1b</li>
        <li>Upwork Job ID: 1691855787116150784</li>
        <li>Last Price Increase: 2023-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26249176</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2023-08-16 21:19
@parasharrajat Apple iPhone SE (2020) / Safari

**Comment by shawnborton** [comment] 2023-08-17 12:58
Will comment in the thread

**Comment by shubham1206agra** [comment] 2023-08-18 08:07
> We are doing something similar to 1. We will have to add logic to apply the smaller buttons when the screen dpi/height is smaller(link iPhone SE devices). For the rest of the screens, the normal button will show. This will only be applied to keypad buttons.

Can't we remove the BigNumberPad when screen is small and use normal keyboard?

**Comment by shawnborton** [comment] 2023-08-18 12:26
Let's first try the smaller button approach. We won't be changing any percentage-based heights, we'll just see how small the viewport is and swap out our big buttons for small buttons. 

![image](https://github.com/Expensify/App/assets/2319350/02890039-ea94-44fe-a7d1-ce36776cb4f8)

Let's try both our regular buttons (40px) and our small buttons (28px) for the numbers and see how it goes. The bottom green button will be unchanged.

**Comment by shawnborton** [comment] 2023-08-21 11:02
Yup, medium works for me!

**Comment by stitesExpensify** [comment] 2023-08-21 20:50
Agreed, that proposal looks good to me

**Comment by wildan-m** [comment] 2023-08-30 03:48
Hi, the PR create [this regression](https://expensify.slack.com/archives/C049HHMV9SM/p1693367178391569)

**Comment by stephanieelliott** [comment] 2023-09-08 15:12
Removing `Hold for payment`, will update once #26747 is merged.

**Comment by stephanieelliott** [comment] 2023-09-18 01:07
https://github.com/Expensify/App/pull/26747 still open

**Comment by stitesExpensify** [comment] 2023-09-18 06:12
FYI ^that is incorrect. I did not review this on time because we were on a merge hold, so this is eligible for a bonus

**Comment by stitesExpensify** [comment] 2023-09-18 06:39
Ah 🤦 thanks for the clarification

**Comment by stephanieelliott** [comment] 2023-09-29 05:14
Summarizing payment on this issue: 
 - Issue reporter: @wildan-m $250 via Upwork (offer extended in Upwork)
 - Contributor: @tienifr $1000 (paid in Upwork)
 - Contributor+: @parasharrajat $1000 via Newdot 
 
 Upwork job is [here](https://www.upwork.com/jobs/~0152c32e49ad0a8a1b), no bonus

**Comment by wildan-m** [comment] 2023-09-29 05:46
Hi @stephanieelliott thanks for the offer. I wanted to confirm the amount. My bug report is valid but it's not exported to github yet. If we refer to [this link](https://expensify.slack.com/archives/C01GTK53T8Q/p1693461675643149?thread_ts=1693424078.129649&cid=C01GTK53T8Q), how much I should receive? $50 or $250? (Of course I'll be happy with the last one 😁)

Note: my bug report posted one day before [bonus recalibration](https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649?thread_ts=1693424078.129649&cid=C01GTK53T8Q) published.

**Comment by stephanieelliott** [comment] 2023-10-04 00:45
@wildan-m I'm basing off the date this GH issue was created, so it would be $250. Thanks for checking!

**Comment by stephanieelliott** [comment] 2023-10-04 00:46
All paid!

**Closed by stephanieelliott** 2023-10-04 00:46 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by wildan-m** [comment] 2023-10-04 00:56
@stephanieelliott Thanks, you are the best! 😺

**Comment by JmillsExpensify** [comment] 2023-10-05 20:44
$1,000 payment approved for @parasharrajat based on BZ summary.
