### ISSUE TITLE
[HOLD for payment 2023-08-07] [$1000] Chat - Word that follows after the multiline hyperlink is located between multiline hyperlink

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22362] opened 2023-07-06 18:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any conversation
3. Type the following message
[Multiline
text}(link) hello
4. Send the message

## Expected Result:
The word 'hello' after the multiline hyperlink is located after the multiline hyperlink

## Actual Result:
The word 'hello' after the multiline hyperlink is located in the middle of multiline hyperlink

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/95e52d29-5a36-4d68-8129-179c1bc090e9

![Bug6118738_Screenshot_20230707_013402](https://github.com/Expensify/App/assets/78819774/d93c271d-1c0d-4b41-8511-cbedc771b4df)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad0d167a3f25ee3b</li>
        <li>Upwork Job ID: 1678480571176464384</li>
        2023-07-17<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 25731139</li>
<li> |  | 0</li>
</ul></li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2023-07-10 19:05
Reproduced and do not see a dupe of this

**Comment by MitchExpensify** [comment] 2023-07-12 20:55
@aimane-chnaif how does @bernhardoj 's proposal look to you?

**Comment by MitchExpensify** [comment] 2023-07-20 22:02
@bernhardoj any estimate on when the PR will be ready?

**Comment by MitchExpensify** [comment] 2023-07-24 20:54
> Waiting for 🟢 from @techievivek

Friendly bump on an update here @techievivek 👍

**Comment by techievivek** [comment] 2023-07-25 04:39
Sorry for missing this out 😢, [proposal](https://github.com/Expensify/App/issues/22362#issuecomment-1624995709) looks good to me.

**Comment by MitchExpensify** [comment] 2023-07-27 17:45
Summary of payments eventually due:

$250 - Reporting bonus: N/A Applause
$1500 - C: @aimane-chnaif 
$1500 - C+: @bernhardoj

**Comment by MitchExpensify** [comment] 2023-08-01 18:12
Reminder added to call to pay on 8/7 🚀 

Let's get the BZ steps complete in advance of that @aimane-chnaif 👍

**Comment by techievivek** [comment] 2023-08-07 07:54
Not overdue, waiting for the payment. @aimane-chnaif can you please fill the BZ steps, thanks.

**Comment by MitchExpensify** [comment] 2023-08-07 14:07
Paid @aimane-chnaif 

Just waiting on @bernhardoj to accept the offer to close this one out post payment

**Comment by MitchExpensify** [comment] 2023-08-07 14:37
Thanks, Paid! Just waiting on Upwork to stop being buggy so I can end the contract.

Reminder on the BZ steps [here](https://github.com/Expensify/App/issues/22362#issuecomment-1658922577) @aimane-chnaif

**Comment by MitchExpensify** [comment] 2023-08-09 21:00
Contracts ended! Friendly bump on the BZ steps https://github.com/Expensify/App/issues/22362#issuecomment-1658922577 @aimane-chnaif - Thanks! Lets get this closed out

**Comment by MitchExpensify** [comment] 2023-08-13 17:12
Awesome, thanks @aimane-chnaif

**Closed by MitchExpensify** 2023-08-13 17:12 UTC
Labels: External, Daily, Awaiting Payment, Bug
