### ISSUE TITLE
[$1000] Dev: IOS -  Native app is extremely slow and have multiple warnings.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22370] opened 2023-07-06 19:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run ios app localy
2. Open any chat
3. Observe the slowness of the buttons to respond.

## Expected Result:
The app works without any lags and smoothly

## Actual Result:
The app is laggy and takes several seconds to respond to any action

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-5 Dev
**Reproducible in staging?:**  n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4b4ac3ac-c080-4177-97dc-0e3b4591f8bc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @getusha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688669318699019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01900427dc42b82bc1</li>
        <li>Upwork Job ID: 1678405752372568064</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by anmurali** [comment] 2023-07-10 10:56
This just feels like a general performance issue rather than a specific bug. That's what [#vip-fast-apis](https://expensify.slack.com/archives/C05CBC62HGW) is about.

**Comment by shubham1206agra** [comment] 2023-07-11 13:48
@anmurali @thesahindia I think the issue is not about performance issue. It's a bug with `react-native`, specifically with `LayoutAnimations` component, which is used in `KeyboardAvoidingView`, and some places in the App.

About the warnings, they are coming from `KeyboardAvoidingView` component, which I have already identified.

**Comment by anmurali** [comment] 2023-07-17 17:48
Yea, I don't think we have enough to go on and still think we should close this.

**Comment by getusha** [comment] 2023-07-19 07:17
I think it's worth investigating https://expensify.slack.com/archives/C01GTK53T8Q/p1689709605850189?thread_ts=1688384483.429669&cid=C01GTK53T8Q

**Closed** 2023-07-19 23:02 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
