### ISSUE TITLE
Sending money - User can't search for a currency because the search function is blocked

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8926] opened 2022-05-10 20:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Log into a verified user
3. Search for any user and open a chat
4. Click on the "Plus" icon
5. Click on "Send Money"
6. Click on the "Currency symbol"
7. In the search bar, attempt to write something

## Expected Result:
The user expects to be able to search for his/her desired currency

## Actual Result:
The search toggle is completely blocked and the user is forced to scroll through the currencies to try and find the correct one

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web
-IOS

**Version Number:** 1.1.57.12

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/167715434-d62f7ace-5251-4756-a7c4-ac194596da13.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment] 2022-05-11 19:43
Looks like this is reproducible on dev as well and does not happen on production.

**Comment by chiragsalian** [comment] 2022-05-11 19:51
I suspect this commit - https://github.com/Expensify/App/commit/f88b00529881642b661414f64833744cdc474c2f

**Comment by chiragsalian** [comment] 2022-05-11 20:14
Cool looks like the issue is because the code is calling onBlur. So when the currency icon is clicked here,
![image](https://user-images.githubusercontent.com/14356145/167937790-17816c86-745d-43d5-857c-642f1bef4f04.png)

The onblur gets called and is locking focus to the currency numbers which is why we can't type anything here,
![image](https://user-images.githubusercontent.com/14356145/167939386-00139288-e623-47cc-9db5-6758f5977c44.png)

Okay i'll just revert the offending PR and let them know about it.

**Comment by chiragsalian** [comment] 2022-05-12 01:01
This should be resolved in version `1.1.57-14` or higher.
@kbecciv, can you retest and if it passes then remove deployBlocker and check if off the checklist? 🙇‍♂️

**Comment by Beamanator** [comment] 2022-05-12 11:13
Thanks for investigating & reverting - can this issue now be closed?

**Comment by Julesssss** [comment] 2022-05-12 11:23
I think we're just awaiting @Expensify/applause testing

**Comment by chiragsalian** [comment] 2022-05-12 17:52
QA mentioned it was [tested](https://github.com/Expensify/App/issues/8777#issuecomment-1125070475). removing deploy blocker label. Actually yeah i'll close these as well since there is no reason to continue seeing them and it takes a while to go to prod.

**Closed by chiragsalian** 2022-05-12 17:52 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Hourly
