### ISSUE TITLE
Taxes - Error shows up when selecting tax rate in split scan menu

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40755] opened 2024-04-23 07:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Collect workspace has a few tax rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a split scan.
4. When the receipt is scanning, enter amount and merchant.
5. Click Tax rate.
6. Select a different tax rate.

## Expected Result:
User is able to select a different tax rate without issue.

## Actual Result:
Error "Unexpected error editing this expense, please try again later" shows up when selecting a different tax rate.
The selected tax rate is highlighted in tax rate list, but the Tax rate row in split menu still shows the previous tax rate.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/03f0f5a3-deb0-48dd-a87e-761175796b3c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145ac3902090baef8</li>
        <li>Upwork Job ID: 1782707567042936832</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-23 07:45
@Christinadobrzyn I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-23 07:45
We think this issue might be related to the #collect project.

**Comment by nkdengineer** [comment] 2024-04-23 10:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error "Unexpected error editing this expense, please try again later" shows up when selecting a different tax rate.
The selected tax rate is highlighted in tax rate list, but the Tax rate row in split menu still shows the previous tax rate.

### What is the root cause of that problem?
We're not handling the case for edit split bill tax rate in `IOURequestStepTaxRatePage` so when we select a tax rate in this page, this isn't updated in confirmation page

https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/iou/request/step/IOURequestStepTaxRatePage.tsx#L70
### What changes do you think we should make in order to solve the problem?
Like other IOU step pages, we should subscribe `splitTransactionDraft` in `IOURequestStepTaxRatePage` and then if we're editing split bill we will get the taxRate data from `splitTransactionDraft` to display the selected tax rate correctly. And when we save the tax rate we will call `setDraftSplitTransaction` if we're editing the split bill.

https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/iou/request/step/IOURequestStepTaxRatePage.tsx#L70


We should do the same for tax amount page.
### What alternative solutions did you explore? (Optional)
NA

**Comment by MonilBhavsar** [comment] 2024-04-23 10:30
We can demote it from a blocker as Tax for splits is WIP here
https://github.com/Expensify/App/issues/39690

Though if this is a blocker, we might have shipped some bad code related to this workflow

**Comment by mountiny** [comment] 2024-04-23 10:44
Seems like we can demote based on the comment but lets make sure this is fixed fast

**Comment by MonilBhavsar** [comment] 2024-04-23 11:02
This is internal issue https://expensify.slack.com/archives/C01GTK53T8Q/p1713870117792039?thread_ts=1713867930.076379&cid=C01GTK53T8Q
Co assigning and looking

**Comment by nkdengineer** [comment] 2024-04-23 11:12
> Though if this is a blocker, we might have shipped some bad code related to this workflow
    
@MonilBhavsar I created a branch for the fix here https://github.com/nkdengineer/App/tree/fix/40755, it's simple and we only use the exist function. So I think we can fix this ASAP here and we will not have the bad code.

**Comment by grgia** [comment] 2024-04-23 12:13
@MonilBhavsar seems related to https://github.com/Expensify/Auth/pull/9616

**Comment by grgia** [comment] 2024-04-23 12:22
I think we need to add an early return for null/empty strings to the above linked PR @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2024-04-29 14:17
@grgia sorry, could you please explain that early return case

--- 

The server error is returned because when receipt is uploded, we're still in scanning state and IOU report hasn't been created.
We should be updating report optimistically, and that is being worked on https://github.com/Expensify/App/pull/40443 and then https://github.com/Expensify/App/issues/39690

**Comment by c3024** [comment] 2024-05-01 05:47
@MonilBhavsar 

From the issue
>Actual Result:
Error "Unexpected error editing this expense, please try again later" shows up when selecting a different tax rate.
The selected tax rate is highlighted in tax rate list, but the Tax rate row in split menu still shows the previous tax rate.

The first part needs to be handled from backend.
The second part needs a frontend fix as well as suggested by @nkdengineer because tax is similar to any other field like category. 

cc: @grgia

**Comment by Christinadobrzyn** [comment] 2024-05-06 00:54
Tracking https://github.com/Expensify/App/pull/40443 and https://github.com/Expensify/App/issues/39690

**Comment by Christinadobrzyn** [comment] 2024-05-07 07:48
Tracking https://github.com/Expensify/App/pull/40443 and https://github.com/Expensify/App/issues/39690

I wonder if this should be weekly for the time being? @c3024 @MonilBhavsar @grgia what do you think?

**Comment by c3024** [comment] 2024-05-07 15:38
Those issues do not cover `Split Bill` flow. So, this issue will not fixed with that PR.

**Comment by Christinadobrzyn** [comment] 2024-05-08 07:40
Ah [thank you](https://github.com/Expensify/App/issues/40755#issuecomment-2098751546) @c3024. 

@MonilBhavsar @c3024 @grgia can you confirm the best next step or a status for this? TY!

**Comment by MonilBhavsar** [comment] 2024-05-08 07:41
> Those issues do not cover Split Bill flow. So, this issue will not fixed with that PR.

https://github.com/Expensify/App/issues/39690 does

**Comment by c3024** [comment] 2024-05-08 08:14
> > Those issues do not cover Split Bill flow. So, this issue will not fixed with that PR.
> 
> #39690 does

Thanks. 

Sorry for the confusion @Christinadobrzyn. This can be moved to `Weekly`. Looks like PR for issue #39690 will take some time.

**Comment by Christinadobrzyn** [comment] 2024-05-14 08:41
monitoring - https://github.com/Expensify/App/issues/39690

**Comment by Christinadobrzyn** [comment] 2024-05-21 07:44
monitoring - https://github.com/Expensify/App/issues/39690

**Comment by Christinadobrzyn** [comment] 2024-05-28 07:38
monitoring - https://github.com/Expensify/App/issues/39690

**Comment by Christinadobrzyn** [comment] 2024-06-05 08:31
monitoring - https://github.com/Expensify/App/issues/39690

**Comment by Christinadobrzyn** [comment] 2024-06-12 09:08
monitoring - https://github.com/Expensify/App/issues/39690

Just a heads up - I'm going to be ooo until June 24th. I'm not going to assign anyone new but if you need a new BZ teammate for any reason please feel free to ask for one to be assigned here.

**Comment by MonilBhavsar** [comment] 2024-06-12 09:24
This bug is fixed, we can close this issue

**Closed by MonilBhavsar** 2024-06-12 09:24 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
