### ISSUE TITLE
[HOLD for payment 2024-04-25] [HOLD for payment 2024-04-17] [Guided Setup] [$250] Sign up - Welcome modal window on Abracadabra page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39837] opened 2024-04-08 16:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2616817
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Enter new email
3. Copy magic link from received email
4. Change link to stage
5. Open link in a new tab
6. Navigate to original tab

## Expected Result:
The abracadabra page is displayed
On original tab Concierge chat opens. The 'Welcome to Expensify' modal window appears

## Actual Result:
The abracadabra page is displayed. The 'Welcome to Expensify' modal window appears on abracadabra page.
On original tab the skeleton loader displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fa16c7f8-a020-492e-b660-5483a129f6b3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ea247a272b092bf</li>
        <li>Upwork Job ID: 1777419039357227008</li>
        <li>Last Price Increase: 2024-04-08</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by lanitochka17** [comment] 2024-04-08 16:27
@cead22  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by cead22** [comment] 2024-04-08 18:38
I think it's a regression from https://github.com/Expensify/App/pull/37733

**Comment by cead22** [comment] 2024-04-08 19:32
Coming from @mountiny [on slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1712601879373609?thread_ts=1712593621.330529&cid=C01GTK53T8Q)
>Could we make the issue external and see if any proposals come in? Given this PR is an important piece for wave-collect Release 1 I think we would prefer not to revert and ideally CP a fix (if we confirm the revert fixes the blocker, we can CP it once we are close to the deploy - that wont happen until tomorrow)

**Comment by cead22** [comment] 2024-04-08 19:32
cc @MaciejSWM @eVoloshchak

**Comment by filip-solecki** [comment] 2024-04-08 19:50
Hi @mountiny @cead22 , I've checked it quickly looks like some changes in `Welcome.ts` file causes this behavior, not sure what exactly

**Comment by mountiny** [comment] 2024-04-08 20:36
I will try to help manage this in my morning if this wont be resolved by then.

**Comment by mananjadhav** [comment] 2024-04-09 06:29
This change looks promising, but @hoangzinh @mountiny @adamgrzybowski do we know what would break if this block is reverted?

**Comment by adamgrzybowski** [comment] 2024-04-09 11:57
@mananjadhav Okay I did some investigation and I think the solution is somehow similar but not exactly the same.

The problem is that `if` should only handle pages that deeplinks to a bottom tab page. 

https://github.com/Expensify/App/blob/38ced972725d4a5d9e9855d00a6f85cc6cc7fad1/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L315-L340

Instead of reverting the lines mentioned above we need to modify the if `if(bottomTabNavigator)` to the `if(bottomTabNavigator && bottomTabNavigator.state)`

Additionally it would be great to add a comment before if, maybe something like 

```js
// We need to make sure that this if only handles states where we deeplink to the bottom tab directly
if(bottomTabNavigator && bottomTabNavigator.state) {
```

**Comment by mananjadhav** [comment] 2024-04-09 12:27
I think your solution would solve for both @adamgrzybowski. But I haven't tested the solution yet.

**Comment by adamgrzybowski** [comment] 2024-04-09 13:08
@hoangzinh sure! Okay so the intention for the `if(bottomTabNavigator)` was to handle all deeplinks to bottom tab navigator. e.g. /home /settings and probably more in the future. 

Just checking if the navigator exists make sense for navigators like RHP or central pane because it will be present in the generated by the original getStateFromPath only if we deeplink to them.

This is not true for the bottomTabNavigator because it is set as the `initialRoute` in the linkingConfig
<img width="501" alt="image" src="https://github.com/Expensify/App/assets/67908363/c1c2d7d9-aff0-4c99-b038-8c8158632ee4">

To make sure that we really deeplinks to the screen in bottom tab we need to check if the state inside the bottom tab exists.

 The bug above was present becuase when we wanted to generated state for the ValidateLogin page and it was handled as deeplinking to a page in bottom tab page. As a result unnecessary central pane screen was added on top of the ValidateLogin page. You can see it on the right side.
 
 
<img width="849" alt="image" src="https://github.com/Expensify/App/assets/67908363/a13d5d98-48ab-49d9-96fa-0d1ce8f9697b">

**Comment by trjExpensify** [comment] 2024-04-15 12:57
Can we close this now?

**Comment by mananjadhav** [comment] 2024-04-15 14:05
@trjExpensify this needs to be paid out for me and @hoangzinh for the PR and the review.

**Comment by mountiny** [comment] 2024-04-15 14:43
I think that sounds good, thanks fo rthe work here

@miljakljajic could you please pay $250 to @mananjadhav and to @hoangzinh for their work on this bug?

**Comment by JmillsExpensify** [comment] 2024-04-25 00:15
$250 approved for @mananjadhav

**Comment by JmillsExpensify** [comment] 2024-04-25 00:16
Whoops, removed that comment and holding off until the checklist is done and the payment date comes due.

**Comment by mananjadhav** [comment] 2024-04-27 17:41
@JmillsExpensify This was deployed on production and the original payout date was 2024-04-17.  PR that caused the regression is https://github.com/Expensify/App/pull/37733. It was already explained during the initial findings. We don't need a regression test here. 

This is ready for payout.

**Comment by miljakljajic** [comment] 2024-04-30 13:43
@hoangzinh please accept the payment offer

@mananjadhav payment summary: owed 250 USD

**Comment by JmillsExpensify** [comment] 2024-04-30 23:19
$250 approved for @mananjadhav

**Comment by mananjadhav** [comment] 2024-05-03 18:25
I think we're good to close this one. @miljakljajic @mountiny

**Comment by cead22** [comment] 2024-05-06 22:36
Which payment is missing?

**Comment by miljakljajic** [comment] 2024-05-07 11:16
paid!

**Closed by miljakljajic** 2024-05-07 11:16 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by miljakljajic** [comment] 2024-08-13 09:04
resolved
