### ISSUE TITLE
[Hold for #39597] [$500] Web - Chat - Text in composer is enlarged after removing emoji from text and sending it

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39269] opened 2024-03-29 17:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58.0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:

1. Go to staging.new.expensify.com/
2. Go to any chat.
3. Enter en emoji, followed by some text.
4. Delete the emoji.
5. Send the text.
6. Type in the composer.

## Expected Result:
The text in the composer will not appear enlarged.

## Actual Result:
The text in the composer is enlarged.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/c85a7a7a-93e9-41c5-8e93-950e03183037

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013bf0f2cfd910f86b</li>
        <li>Upwork Job ID: 1775514075929288704</li>
        <li>Last Price Increase: 2024-04-10</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-03-29 17:36
We think this bug might be related to #vip-vsb

**Comment by m-natarajan** [comment] 2024-03-29 17:37
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by thienlnam** [comment] 2024-03-29 18:32
Not a blocker, though this is funny - added to the main tracking issue

**Comment by sonialiap** [comment] 2024-04-03 13:22
Adding external label

**Comment by happylifesdev** [comment] 2024-04-04 11:52
I analyzed the text size problem in the project in detail.
As you can see from the video uploaded below, you can see that the font-size of the Text Input that the id of element is root, remains the font-size of the emoticon.
It is estimated that the tube problem between the emoticon module and the text input is estimated.
I think we need to find the cause in the emoticon module, or if we find an element that the id of element is root in the HTML page, you will always solve the problem if you attach a little code to the code so that font-size keeps 15px.

https://drive.google.com/file/d/17LCUxb9URVbofFTXZ621pVdSI75uIVl1/view?usp=sharing

Phone: 12818960915(whatsapp)
Mail: happylifesdev@gmail.com

**Comment by jjcoffee** [comment] 2024-04-04 11:57
@happylifesdev Please make sure you read through our [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and make sure to use the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md).

**Comment by happylifesdev** [comment] 2024-04-04 12:03
I just edited the proposal.

**Comment by happylifesdev** [comment] 2024-04-04 12:24
I analyzed the text size problem in the project in detail.
As you can see from the video uploaded below, you can see that the font-size of the Text Input that the id of element is root, remains the font-size of the emoticon.
It is estimated that the tube problem between the emoticon module and the text input is estimated.
I think we need to find the cause in the emoticon module, or if we find an element that the id of element is root in the HTML page, you will always solve the problem if you attach a little code to the code so that font-size keeps 15px.

https://drive.google.com/file/d/17LCUxb9URVbofFTXZ621pVdSI75uIVl1/view?usp=sharing

Phone: 12818960915(whatsapp)
Mail: happylifesdev@gmail.com

Contributor details
Your Expensify account email: happylifesdev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/hemanthbellala

**Comment by jjcoffee** [comment] 2024-04-05 15:04
@happylifesdev Please follow the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) by copy and pasting it into the comment box and filling out all fields. Thanks! :pray:

**Comment by withmussy** [comment] 2024-04-06 00:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Text in composer is enlarged after removing emoji from the text and sending it
### What is the root cause of that problem?
To understand the problem, let's look at two scenarios where this issue doesn't happen:

**First Scenario:**

1. Add an emoji and some text.
2. Remove the emoji.
3. Press the left or right arrow key.
4. Send the text.
5. Type again in the composer.

Here, the text size remains normal at 15px.

**Second Scenario:** If we use the following code to clear the text, the next text size stays normal. However, refreshing the page brings back a space in the composer.

[this line is in ComposerWithSuggestions file line 482](https://github.com/Expensify/App/blob/f1502291a14d4e15e04249b241109f146bdb512f/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L482)
```javascript
updateComment(' ');
```

The issue seems to be with the `updateComment` function and how the `MarkdownTextInput` component handles empty inputs. It incorrectly sizes new text at 20px within a span tag unless the `ComposerWithSuggestions.tsx` component is re-rendered by an action like pressing an arrow key or receiving a non-empty input.

The core issue lies with the `@expensify/react-native-live-markdown` package in the composer component.


### What changes do you think we should make in order to solve the problem?
I have two suggestions:

**Main Idea:** Improve the `@expensify/react-native-live-markdown` so it resets correctly with empty inputs or fully removes the span tag after an emoji is deleted. This approach targets the core of the problem.

**Alternative:** As a quick fix, we could reset the `Composer` component inside `ComposerWithSuggestions` right after sending a message. However, this is more of a temporary workaround.

I recommend the first solution for a lasting fix. Looking forward to your thoughts and approval to proceed.

### What alternative solutions did you explore? (Optional)

**Comment by withmussy** [comment] 2024-04-06 00:29
Contributor details
Your Expensify account email: mostafasalehi796@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016b2ad2638bba37f2

**Comment by sonialiap** [comment] 2024-04-09 13:40
@jjcoffee what do you think of the proposal?

**Comment by jjcoffee** [comment] 2024-04-09 15:56
@withmussy Thanks for your [proposal](https://github.com/Expensify/App/issues/39269#issuecomment-2040822181)! Please can you update your proposal to provide more details in your solution? We need specifics on what changes you propose to make.

**Comment by withmussy** [comment] 2024-04-09 16:12
@jjcoffee, thank you for considering my proposal. I sent you two solutions. Which one do you prefer?

**Comment by jjcoffee** [comment] 2024-04-10 06:40
Agreed, @sonialiap can we add a HOLD for https://github.com/Expensify/App/pull/39597? Thanks :pray:

**Comment by sonialiap** [comment] 2024-04-16 09:43
https://github.com/Expensify/App/pull/39597 is merged but not deployed, still on hold for it ⏳

**Comment by mvtglobally** [comment] 2024-04-18 15:54
Issue not reproducible during KI retests. (First week)

**Comment by thienlnam** [comment] 2024-04-18 18:19
We're live!

**Closed by thienlnam** 2024-04-18 18:19 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
