### ISSUE TITLE
Personal details - "common.zipCodeExampleFormat" appears under Zip / Postcode field

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38660] opened 2024-03-20 10:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Address is not filled in Private section.

1. Go to staging.new.expensify.com.
2. Go to Profile
3. Click Address.

## Expected Result:
There will be no strings under Zip / Postcode field since the address is not filled.

## Actual Result:
"common.zipCodeExampleFormat" appears under Zip / Postcode field.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1440" alt="Bug6420278_1710929184259!zipcode" src="https://github.com/Expensify/App/assets/115492554/5f6eece5-4631-426f-88b6-c23f49ee22b1">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-20 10:19
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-03-20 10:20
Production

![image (2)](https://github.com/Expensify/App/assets/115492554/9acf1d69-2e98-4575-b023-60bcea118a5a)

**Comment by hungvu193** [comment] 2024-03-20 10:46
Regression from this one: https://github.com/Expensify/App/pull/37200
cc @hurali97

**Comment by hungvu193** [comment] 2024-03-20 11:00
> @hungvu193 are you sure that Regression is from #37200?

I believe so 😄

**Comment by hurali97** [comment] 2024-03-20 11:05
@hungvu193 I tried it on main which has all of the latest code and this issue is not regressed by https://github.com/Expensify/App/pull/37200. I commented out the cache mechanism which was introduced in the PR and the issue still persists.

After applying @Krishna2323 's suggestion [here](https://github.com/Expensify/App/issues/38660#issuecomment-2009225101), the issue seems to be resolved. 

https://github.com/Expensify/App/assets/47336142/16e3511e-1813-47b0-a117-37cb89547ad7

**Comment by hungvu193** [comment] 2024-03-20 11:13
> @hungvu193 This issue is not regressed by #37200. I commented out the cache mechanism which was introduced in the PR and the issue still persists.
> 
> After applying @Krishna2323 's suggestion [here](https://github.com/Expensify/App/issues/38660#issuecomment-2009225101), the issue seems to be resolved.
> 
>  VEED.CREATE.Edit.mp4

 I apologize if I was wrong, but can you try to revert your PR and test it? Or you can checkout this commit `f042015061` (this is the commit before your PR got merged), the issue will disappear.

**Comment by hurali97** [comment] 2024-03-20 11:20
@hungvu193  I checked out to the commit and below is what I get now:

<img width="1362" alt="Screenshot 2024-03-20 at 4 19 30 PM" src="https://github.com/Expensify/App/assets/47336142/c1c22412-5040-44c3-b80b-6d018170bf3a">

Is it correct as we don't have the placeholder US number?

**Comment by hungvu193** [comment] 2024-03-20 11:22
I think @izarutskaya mentioned it here as expected result here but I'm sure.
<img width="845" alt="Screenshot 2024-03-20 at 18 21 23" src="https://github.com/Expensify/App/assets/16502320/91d63efc-369c-492f-9aa3-b30fa7cce885">

**Comment by hurali97** [comment] 2024-03-20 11:26
@hungvu193 Okay I am working on to find the cause in my PR 👍

**Comment by hungvu193** [comment] 2024-03-20 11:32
> @hungvu193 Okay I am working on to find the cause in my PR 👍

AFAIK, `common.zipCodeExampleFormat` doesn't seem to exist in `cacheForLocale`. I hope this will help.

**Comment by hurali97** [comment] 2024-03-20 11:35
@hungvu193 I have tried commenting out the cache mechanism but things are still the same. It's probably due to the fact that `getTranslatedPhrase` is a recursive function, so there's something fishy going on.

**Comment by hungvu193** [comment] 2024-03-20 11:43
> @hungvu193 I have tried commenting out the cache mechanism but things are still the same. It's probably due to the fact that `getTranslatedPhrase` is a recursive function, so there's something fishy going on.

I don't have context about how cache work, but any reason other phrases exist in `cacheForLocale` except `common. zipCodeExampleFormat`?

**Comment by hurali97** [comment] 2024-03-20 11:46
<img width="1417" alt="Screenshot 2024-03-20 at 4 43 34 PM" src="https://github.com/Expensify/App/assets/47336142/bacbbad2-69ab-4c6f-9703-c2b77dcc6b45">

Hey @hungvu193,

So I have found the issue. Basically, `common. zipCodeExampleFormat` doesn't work because we have a condition which checks whether `translatedPhrase` is a truthy value and `common.zipCodeExampleFormat` returns an empty string, which is a falsy value and the code returns the key as is. And the other phrases works because they return something other than an empty string.

Below is how I think we should change the condition:

<img width="1451" alt="Screenshot 2024-03-20 at 4 45 18 PM" src="https://github.com/Expensify/App/assets/47336142/39afa78e-9476-4167-b5a8-3ea6c15e8f09">

**Comment by hungvu193** [comment] 2024-03-20 11:55
> > @hungvu193 I have tried commenting out the cache mechanism but things are still the same. It's probably due to the fact that `getTranslatedPhrase` is a recursive function, so there's something fishy going on.
> 
> I don't have context about how cache work, but any reason other phrases exist in `cacheForLocale` except `common. zipCodeExampleFormat`?

@hurali97 Cool. This is only the concern I have now 🤔

**Comment by hurali97** [comment] 2024-03-20 11:57
> > > @hungvu193 I have tried commenting out the cache mechanism but things are still the same. It's probably due to the fact that `getTranslatedPhrase` is a recursive function, so there's something fishy going on.
> > 
> > 
> > I don't have context about how cache work, but any reason other phrases exist in `cacheForLocale` except `common. zipCodeExampleFormat`?
> 
> @hurali97 Cool. This is only the concern I have now 🤔

Oh yes. The thing is in cache we don't store any phrases which are bound to a variable as it kills the purpose of cache.

**Comment by hurali97** [comment] 2024-03-20 12:15
@dragnoir Oh yeah, agreed 👍 

@hungvu193 How do you want this issue to be addressed? Should I create a PR fixing this issue or you've someone else to do it?

**Comment by hungvu193** [comment] 2024-03-20 12:20
> @dragnoir Oh yeah, agreed 👍 
> 
> 
> 
> @hungvu193 How do you want this issue to be addressed? Should I create a PR fixing this issue or you've someone else to do it?

I think you should create a PR to fix it if you're available

**Comment by roryabraham** [comment] 2024-03-21 17:21
I requested some changes on the PR, but since @hurali97 appears to be out for the day @hayata-suenaga has volunteered to do it. Thanks @hayata-suenaga!

**Comment by roryabraham** [comment] 2024-03-21 20:32
Closing this as it is fixed, and no additional payments are due since this was a regression

**Closed by roryabraham** 2024-03-21 20:32 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug
