### ISSUE TITLE
[$1000] Dev: Web - Workspace members are automatically removed when inviting them after creating a room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22438] opened 2023-07-07 18:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to the  userA’s account
2. Go to the Setting > Workspace > New Workspace
3. Navigate to the "New room" section
4. Enter a name for the room and select the created workspace
5. Set the visibility of the room to "Public"
6. Click on the "Create room" button
7. Go to the room details > Settings > Welcome message
8. Enter welcome message and save it
9. Now go to Share code > Copy URL to clipboard
10. Open another browser and log in with userB account
11. Join the room by pasting the copied room URL
12. Return back to the userA account
13. Go to the workspace that is connected with room (Workspace > Members)
14. Invite some members and refresh the page

## Expected Result:
Workspace members should not be automatically removed when inviting them after creating a room

## Actual Result:
Workspace members are automatically removed when inviting them after creating a room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.37-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/897dfb41-ec59-4854-a871-f72d58dd57d8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688683716593489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d649ae38343d6258</li>
        <li>Upwork Job ID: 1679642756049620992</li>
        <li>Last Price Increase: 2023-07-21</li>
    </ul>
</details>

**Comment by ayazhussain79** [comment] 2023-07-07 18:26
Also Invite User B, who joined the userA's room, when you invite the other members

**Comment by stephanieelliott** [comment] 2023-07-11 01:39
Given that this is only happening in DEV and won't be experienced by an end user, gonna close this for now

**Comment by ayazhussain79** [comment] 2023-07-11 06:43
@stephanieelliott it is reproducible on staging not only dev

**Comment by ayazhussain79** [comment] 2023-07-12 08:05
@stephanieelliott can you please check that it it reproducible on staging

**Comment by ayazhussain79** [comment] 2023-07-13 13:26
@stephanieelliott i have reproduced again I tested that on dev because i don't have room access on staging

It is reproducible on staging you can try that


https://github.com/Expensify/App/assets/56740856/f494a35a-b2c7-4855-8c47-573cae60f005

**Comment by stephanieelliott** [comment] 2023-07-14 00:03
Thanks for the bump @ayazhussain79. Was able to reproduce this on staging, that was not noted on the original issue body so updating to `Reproducible in staging?: yes`.

**Comment by solarisrascal** [comment] 2023-07-14 01:10
Hi. This is Nicolas from Upwork.
I just read the issue and want to be a contributor on this issue.
Through attached video I have a clear understanding about the issue and to give a right solution in detail I'd love to know more about the issue in detail and want to move forward to next steps.

**Comment by solarisrascal** [comment] 2023-07-14 01:13
Contributor details
My Expensify account email: solarisrascal@gmail.com
Upwork Profile Link:  https://www.upwork.com/freelancers/~016a86f536c1f47ac9

**Comment by ShogunFire** [comment] 2023-07-19 12:26
So @stephanieelliott said that a user can be in a room without being a member of the corresponding workspace, which means the api should not return a Unique Constraint Violation. I think this issue should be internal

**Comment by ShogunFire** [comment] 2023-07-20 21:37
@fedirjh Can I make a proposal to display the error when there is one ?

**Comment by ShogunFire** [comment] 2023-07-21 03:07
@fedirjh I just retried it and it looks like the change in the backend has already been made because I don't reproduce anymore. Can you reproduce ?

https://github.com/Expensify/App/assets/19537677/835e8d80-02d8-4c16-9f2b-aa7e8f1cf318

**Comment by ShogunFire** [comment] 2023-07-21 16:20
I am confused, I don't reproduce anymore and when I simulate an error I have the error message already showing as expected ^^
![image](https://github.com/Expensify/App/assets/19537677/221fd678-6617-4961-868b-b3526d55d010)

Anyways, if you can reproduce, I will wait to see what happens internally

**Comment by stephanieelliott** [comment] 2023-07-24 20:04
Thanks for the review @fedirjh, adding the `Internal` label

**Comment by stephanieelliott** [comment] 2023-07-24 20:12
@neil-marcellini some context on why we think this needs to be fixed internally in https://github.com/Expensify/App/issues/22438#issuecomment-1644571315

**Comment by neil-marcellini** [comment] 2023-07-26 20:46
Woops I had forgotten about this because it has the external label too. I'm way too busy but I'll try to get to it soon.

**Comment by neil-marcellini** [comment] 2023-07-28 18:06
Heads up, I'm going to be OOO Monday and Tuesday next week. I'll ask in Slack if anyone can take over these issues while I'm out.

**Comment by stephanieelliott** [comment] 2023-08-01 17:18
Neil is back from OOO tomorrow so will wait rather than reassigning.

**Comment by neil-marcellini** [comment] 2023-08-04 00:55
I've been OOO and I'm working on my backlog of other daily issues

**Comment by neil-marcellini** [comment] 2023-08-07 17:42
I will try to work on this when I have time.

**Comment by neil-marcellini** [comment] 2023-08-09 21:40
Same

**Comment by neil-marcellini** [comment] 2023-08-15 01:34
I haven't had time. I'm prioritizing distance requests above this.

**Comment by stephanieelliott** [comment] 2023-08-22 15:51
I'm not able to repro this anymore -- @kbecciv is this still happening for you? It's been a while since this was reported, possible it was fixed in a recent release

**Closed** 2023-08-25 16:17 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug

**Comment by ayazhussain79** [comment] 2023-08-25 16:29
@stephanieelliott am i eligible for reporting bonus?

**Comment by kbecciv** [comment] 2023-08-26 13:37
Hello @stephanieelliott! I'm back from OOO, let me check in latest build!

**Comment by kbecciv** [comment] 2023-08-26 13:48
Unable to reproduce it on build v1.3.57-5.

https://github.com/Expensify/App/assets/93399543/e8654cc6-b58e-4ef4-bc78-d9e3401e362b
