### ISSUE TITLE
User is not navigated last active conversation after loading Home URL - Reported by @K4tsuki 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8355] opened 2022-03-30 01:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging new expensify
2. Visit chat using LHN
3. Close expensify tab
4. Open staging expensify in new tab by home url [staging new expensify com]
5. Verify active chat is not last visited chat

## Expected Result:
Active chat must be last visited chat before closing the expensify tab

## Actual Result:
Active chat is not last visited chat

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.46-3
**Reproducible in staging?:**  Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/160735028-bcc545af-5b9a-4069-8812-b7dd20f77590.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @K4tsuki 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1647325938362069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment] 2022-03-30 15:13
Hmmm I can't reproduce this. When I close and open a new tab on staging, I'm taken to my last active chat.

**Comment by lschurr** [comment] 2022-03-30 15:14
Is this still happening for you @K4tsuki?

**Comment by lschurr** [comment] 2022-03-30 21:20
I couldn't reproduce this. Adding the triage label again.

**Comment by lschurr** [comment] 2022-03-30 21:21
@michaelhaxhiu - I'd say we can close if you also don't see this happening.

**Comment by michaelhaxhiu** [comment] 2022-03-31 12:46
@lschurr thanks for testing this forreal - not everyone does that consistently!

Also, I agree with you - this isn't reproducible for me either. Closing.

![big gifs ](https://user-images.githubusercontent.com/13206896/161057760-c645b41d-0e42-49c4-8623-1f79debf63f5.gif)

**Closed by michaelhaxhiu** 2022-03-31 12:46 UTC
Labels: Daily
