### ISSUE TITLE
[HOLD for payment 2023-06-23] [HOLD for payment 2023-06-21] Web - Chat - Cursor on staging link is not pointer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20669] opened 2023-06-13 11:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Copy current URL and send in report
4. Hover on link to observe that cursor is not pointer

## Expected Result:
 App should display pointer cursor on links

## Actual Result:
App displays normal cursor on staging expensify links

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/567fa792-9217-4243-80bc-1ab5e25554be

https://github.com/Expensify/App/assets/93399543/554e5083-aba1-4a2b-9d2b-4be7b915adc3

**Expensify/Expensify Issue URL:**

**Issue reported by:** @adeel0202 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686648377836269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by eh2077** [comment] 2023-06-13 15:02
It's possibly related to https://github.com/Expensify/App/issues/19717 as their fix changed styles of link.

**Comment by youssef-lr** [comment] 2023-06-13 15:19
Actually this is the offending https://github.com/Expensify/App/pull/19545.

**Comment by grgia** [comment] 2023-06-13 15:37
@youssef-lr all these PRs seem to be linked to https://github.com/Expensify/App/issues/19717

I think we should consider reverting

**Comment by Nikhil-Vats** [comment] 2023-06-13 16:21
This is caused by my PR but reverting it is not the solution because we were adding the pointer cursor not to the link but to its parent which showed the pointer at places around the link -

https://github.com/Expensify/App/assets/31413407/6aef044c-2c0d-4045-b767-567c45a6e803

The root cause for this issue is that for some reasons links like `https://staging.new.expensify.com/random_text_here` are rendered in `div` rather than `a` which is wrong.

https://github.com/Expensify/App/assets/31413407/cc9318c9-bc07-44d5-b8ff-e34007642172

So, we need to figure out why links are rendered in `div` and change it to `a` to fix it the right way.

**Comment by youssef-lr** [comment] 2023-06-13 16:27
Ahh gothcu. Do you think you might be able to find a fix? We can always revert than implement the new solution in a follow up PR as this is a deploy blocker. If we can't find the fix quickly then we'll have to revert.

**Comment by youssef-lr** [comment] 2023-06-13 16:46
Sounds good to me @parasharrajat.

**Comment by youssef-lr** [comment] 2023-06-13 17:12
@parasharrajat another clue, why do links to `https://new.expensify.com/r/801524823110380` e.g. not staging, work? They're internal as well. Do you think we're doing something differently when handling staging links?

**Comment by Nikhil-Vats** [comment] 2023-06-13 17:21
@youssef-lr I found a solution basically for internal links since they are rendered as `div` we can explicitly set cursor pointer here (for other links it is default) -
https://github.com/Expensify/App/blob/6e8435ec6cba470dae50262439f2bacecea9222f/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L68-L71

This would solve all the related issues without a regression.

**Comment by Nikhil-Vats** [comment] 2023-06-13 17:26
Sure @parasharrajat, but since you are aware about the internal links special handling and all the related issues. can you provide your suggestions on the solution above?

**Comment by youssef-lr** [comment] 2023-07-24 18:49
@parasharrajat I can go ahead and close this?

**Comment by sophiepintoraetz** [comment] 2023-08-29 00:10
FYI - @sakluger - all that's needed here is the reporting payment for @adeel0202 ($250)

**Comment by sakluger** [comment] 2023-08-29 01:42
Just sent you an offer through upwork @adeel0202!

https://www.upwork.com/jobs/~0117619b8e4dbdc25f

**Closed** 2023-08-31 21:03 UTC
Labels: Reviewing, Engineering, Daily, Awaiting Payment, Bug
