### ISSUE TITLE
[$500] Thread - Not here page shows up when recipient opens thread for the first time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32812] opened 2023-12-11 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [User A and B] Open the chat with each other.
2. [User A] Send a message to User B.
2. [User A] Right click on the message > Reply in thread > send a reply.
3. [User B] Open the thread.

## Expected Result:
The thread page opens successfully.

## Actual Result:
Not here page shows up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/6648a327-1b56-4e5c-b4ad-fb44d5422899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f76d6eadb3fc262</li>
        <li>Upwork Job ID: 1734214326980894720</li>
        <li>Last Price Increase: 2023-12-18</li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-12-11 14:22
This is backend issue.

**Comment by mallenexpensify** [comment] 2023-12-11 22:26
unable to reproduce using steps in the OP

https://github.com/Expensify/App/assets/22508304/7fa66e29-8db2-4995-a4e7-1539bb241387

When I'm able to reproduce, it's inconsistent 


https://github.com/Expensify/App/assets/22508304/34cd3101-9539-4048-9397-e8ec6a495957

This might be tangentially related, because click `1 reply` leads to crash screen
- https://github.com/Expensify/App/issues/32485#issuecomment-1850899837

**Comment by strepanier03** [comment] 2023-12-12 01:07
Thanks @mallenexpensify 🙌 

----

I am able to reproduce this using the steps in the OP consistently. 

- MacOS: Desktop

<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/10925636/d69f5232-5950-41b8-9f5b-5bb2dc2c80ab">

**Comment by mallenexpensify** [comment] 2023-12-12 21:38
This could be related too
https://github.com/Expensify/Expensify/issues/347675

**Comment by mallenexpensify** [comment] 2023-12-18 21:27
The below just hit staging, 🤞  it might help/fix this too?  
https://github.com/Expensify/App/issues/32485#issuecomment-1860734324

Pretty sure it does, based on my repro on desktop, staging. Sheena can you try too plz. 
Version 1.4.13-7 is what I'm on now.

**Comment by strepanier03** [comment] 2023-12-19 22:50
Was OoO but now that I'm back online I'll test this and update.

**Comment by strepanier03** [comment] 2023-12-19 23:00
Confirming I can no longer reproduce this behavior @mallenexpensify.

**Comment by strepanier03** [comment] 2023-12-19 23:01
I am going to close this out since we've had two different testers and aren't able to repro any longer. If we need to reopen this again in the future we can.

**Closed by strepanier03** 2023-12-19 23:01 UTC
Labels: External, Daily, Help Wanted, Bug
