### ISSUE TITLE
Dev: Pressing the back button on the room members page closes the page instead of returning to the room details

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22267] opened 2023-07-05 12:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the "New room" section.
2. Enter the room name and select User A's workspace
3. Set the visibility to "Public"
4. Click on "Create room"
5. Navigate to the room details and click on "Members"
6. On the members page, press the back button

## Expected Result:
Pressing the back button on the room members page should return to the room details

## Actual Result:
Pressing the back button on the room members page closes the page instead of returning to the room details

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-4 DEV
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/48554912-9fd0-4288-9fcf-d3e8fcb8cf7a

**Expensify/Expensify Issue URL:**
**Issue reported by:** ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688495604372219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-07-05 12:42
### Proposal
**Please re-state the problem that we are trying to solve in this issue.**
Currently, when the back button is pressed on the room members page, the page is closed instead of returning to the room details.
**What is the root cause of that problem?**
The issue arises from the fact that pressing the back button does not navigate back to the detail page, we are not using "onBackButtonPress" resulting in the closure of the modal page.
**Issue is in ReportParticipantsPage.js:**
```
                <HeaderWithBackButton
                        title={props.translate(
                            ReportUtils.isChatRoom(props.report) || ReportUtils.isPolicyExpenseChat(props.report) || ReportUtils.isChatThread(props.report)
                                ? 'common.members'
                                : 'common.details',
                        )}
                    />
```
**What changes do you think we should make in order to solve the problem?**
To address this problem, we should implement the following changes:
In the file ReportParticipantsPage.js, modify the code as shown below
```
<HeaderWithBackButton
    title={props.translate(
        ReportUtils.isChatRoom(props.report) || ReportUtils.isPolicyExpenseChat(props.report) || ReportUtils.isChatThread(props.report)
            ? 'common.members'
            : 'common.details',
    )}
    onBackButtonPress={() => Navigation.goBack(ROUTES.getReportDetailsRoute(props.report.reportID))}
/>
```
**What alternative solutions did you explore? (Optional)**

**Comment by sonialiap** [comment] 2023-07-11 16:53
I can't reproduce. My guess is that it may have been fixed by https://github.com/Expensify/App/pull/20497

**Closed by sonialiap** 2023-07-11 16:53 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
