### ISSUE TITLE
[HOLD for payment 2024-06-05] Web - Chat - Console error shows up when selecting a phone number mention

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40414] opened 2024-04-18 10:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Type @.
4. Select a phone contact from the list.

## Expected Result:
No console error will show up.

## Actual Result:
Console error shows up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6dfd33ba-5015-42c2-bd99-f60081753514

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by izarutskaya** [comment] 2024-04-18 10:04
@sonialiap I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-18 10:04
We think this issue might be related to the #vip-vsb.

**Comment by pecanoro** [comment] 2024-04-18 12:05
I can reproduce it, it's failing to add the mention styling because of the error:

![image](https://github.com/Expensify/App/assets/6474442/66117b4b-c000-4f33-add4-6660780a2bfc)

**Comment by robertKozik** [comment] 2024-04-18 13:28
It stem expensify-common version bump inside [my PR](https://github.com/Expensify/App/pull/40279). I'll prepare followup PR's for `expensify-common`, `react-native-live-markdown` and E/App respecively

**Comment by robertKozik** [comment] 2024-04-22 16:33
@pecanoro I've created the PR for `expensify-common`. I'll now wait until it would be merged

**Comment by pecanoro** [comment] 2024-04-25 10:33
PR https://github.com/Expensify/expensify-common/pull/687 has been merged!

**Comment by pecanoro** [comment] 2024-04-29 13:45
@robertKozik We are still pending a PR in App with the new expensify-common changes, right?

**Comment by pecanoro** [comment] 2024-05-02 12:10
@robertKozik Friendly bump!

**Comment by robertKozik** [comment] 2024-05-06 07:50
Sorry for not updating on this issue, I was OOO. PR with updating `expensify-common` on `react-native-live-markdown` is open now. Next would be to create PR in E/App with bumping both `expensify-common` and `react-native-live-markdown`

**Comment by jayeshmangwani** [comment] 2024-05-27 07:21
@sonialiap Please assign me to the issue here to track the payment

**Comment by sonialiap** [comment] 2024-06-06 09:57
Payment summary
- @jayeshmangwani $250 - please request in ND and complete the [checklist](https://github.com/Expensify/App/issues/40414#issuecomment-2136927001)

**Comment by jayeshmangwani** [comment] 2024-06-06 10:54
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40279 
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40279#issuecomment-2063778321
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **No need to create a discussion for this bug as this is a UI bug that can be caught during the PR process but somehow missed it for phone number case**
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug.
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

## Regression Test Proposal

1. Open Chat
2. Type any user with phone number mention (for example: @+48111222333)
3. Verify that there is no console error and mention input is correctly styled

Do we agree 👍 or 👎

**Comment by jayeshmangwani** [comment] 2024-06-06 10:57
payment requested in ND

**Closed** 2024-06-06 11:21 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-07 03:51
$250 approved for @jayeshmangwani
