### ISSUE TITLE
[HOLD for payment 2022-12-20] [$1000] Unable to bold/ italiced the email addresses and the email address is altered too as it is prefixed with strong

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13073] opened 2022-11-28 04:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. Enter an email inside the asterisks to bold it or enter inside underscore to italics
3. Send the comment
4. Click the Edit comment icon

## Expected Result:
The email address is bold or italic as per the selection

## Actual Result:
The email address is not bold or italic and it is altered too

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.32-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**  

https://user-images.githubusercontent.com/43996225/204192229-7d27d1c5-42ec-41b1-84af-72f2d30bf56a.mp4
https://user-images.githubusercontent.com/43996225/204192345-13fd141d-b32e-4aa1-ac21-276e077f3e5f.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669359923600849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~012d84e703908b4743
- Upwork Job ID: 1598382404523278336

**Comment by s77rt** [comment] 2022-11-28 08:32
### Proposal
```diff
diff --git a/ExpensiMark.js b/ExpensiMark2.js
index 129fca3..c2c2278 100644
--- a/ExpensiMark.js
+++ b/ExpensiMark2.js
@@ -97,8 +97,10 @@ export default class ExpensiMark {
              */
             {
                 name: 'autoEmail',
-                regex: /(?![^<]*>|[^<>]*<\\)([_*~]*?)([a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z]+?(\.[a-zA-Z]+)+)(?![^<]*(<\/pre>|<\/code>|<\/a>))/gim,
-                replacement: '<a href="mailto:$2">$2</a>',
+                regex: /(?![^<]*>|[^<>]*<\\)([_*~]*)([a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z]+?(\.[a-zA-Z]+)+)\1(?![^<]*(<\/pre>|<\/code>|<\/a>))/gim,
+                replacement: (match, g1, g2) => {
+                    return `${g1}<a href="mailto:${g2}">${g2}</a>${g1}`;
+                },
             },
 
             /**
```
https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js

### Details
The problem is that the email regex (`autoEmail` rule) treats the special chars such as * and _ as a part of the email since they are valid.
The fix was to alter the regex to capture those special chars in a another group if the email is surrounded by the same chars, as in this case. Modification:
1. Removed the lazy quantifier, it will never match if it's lazy
2. Added a back-reference to detect if the text is surrounded by the first captured group 

PS: I have noticed a similar regex on `autolink`, it may be worth checking the behaviour there as well.



https://user-images.githubusercontent.com/16493223/204230256-3809d85e-a406-4704-b6a3-5e635610d512.mp4

**Comment by johncschuster** [comment] 2022-11-28 16:03
Coming from the [thread in Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1669359923600849), it looks like we consider this a feature request, but a request worth resolving nonetheless.

**Comment by thienlnam** [comment] 2022-12-01 18:22
Yeah, this will likely have to be fixed with our Expensimark regex - it looks like @s77rt already has a solid proposal ready for review

**Comment by thesahindia** [comment] 2022-12-02 14:10
@s77rt, the proposal won't work in some cases, e.g.` ~_test@gmail.com_~` `*_test@gmail.com_*`

**Comment by s77rt** [comment] 2022-12-02 15:33
### Proposal (Updated)
```diff
diff --git a/ExpensiMark.js b/ExpensiMark2.js
index 129fca3..871d9b3 100644
--- a/ExpensiMark.js
+++ b/ExpensiMark2.js
@@ -97,8 +97,10 @@ export default class ExpensiMark {
              */
             {
                 name: 'autoEmail',
-                regex: /(?![^<]*>|[^<>]*<\\)([_*~]*?)([a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z]+?(\.[a-zA-Z]+)+)(?![^<]*(<\/pre>|<\/code>|<\/a>))/gim,
-                replacement: '<a href="mailto:$2">$2</a>',
+                regex: /(?![^<]*>|[^<>]*<\\)([_*~]*)([_*~]*)([a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z]+?(\.[a-zA-Z]+)+)\2\1(?![^<]*(<\/pre>|<\/code>|<\/a>))/gim,
+                replacement: (match, g1, g2, g3) => {
+                    return `${g1}${g2}<a href="mailto:${g3}">${g3}</a>${g2}${g1}`;
+                },
             },
 
             /**
```

### Update
@thesahindia The ideal fix of this won't be easy, Ideally we would just reverse the captured group 1 in the back-reference. This is not possible with regex as far as I know, we can do it in two regex but that does not sound good at all.
Luckily I found that adding another group will cover most of the cases (and maybe all), tested with:
```
test@gmail.com
*test@gmail.com*
_test@gmail.com_
*_test@gmail.com*
~_test@gmail.com_~
*_test@gmail.com_*
*_*_test@gmail.com_*_*
*__test@gmail.com__*
*__*test@gmail.com*__*
_~__test@gmail.com__~_
**__test@gmail.com__**
```

**Comment by thesahindia** [comment] 2022-12-05 10:01
The updated [proposal](https://github.com/Expensify/App/issues/13073#issuecomment-1335427843) looks good to me.

C+ reviewed 🎀👀🎀

cc: @thienlnam

**Comment by s77rt** [comment] 2022-12-05 18:55
Applied in [Upwork](https://www.upwork.com/jobs/~012d84e703908b4743) (+50% bonus)
[PR](https://github.com/Expensify/expensify-common/pull/479) is ready

**Comment by thienlnam** [comment] 2022-12-08 22:45
Changes have been merged, pending production regression wait

**Comment by johncschuster** [comment] 2022-12-09 20:48
@adeel0202 and @thesahindia, can you apply to the job? https://www.upwork.com/jobs/~012d84e703908b4743

**Comment by thienlnam** [comment] 2022-12-22 20:30
This was just not a case that was handled in the making of the original auto-email regex

Also, this should be ready for payment now

**Comment by mallenexpensify** [comment] 2022-12-22 20:43
It appears the time from hire to the PR being merged was 2 days so @s77rt and @thesahindia are due a 50% bonus. 

**Paid** 
@adeel0202 $250 for reporting
@thesahindia $1500 for C+, job+bonus
@s77rt $1500 for contributor, job+bonus, @s77rt I'm unsure if you did so, John might have, please don't increase the price of jobs, or request more money in Upwork for bonuses.  Feel free to add a comment to the associated GH issue if the bonus is due (we're wanting to avoid someone paying the bonus on top of an increased price listed in Upwork)

**Closed by mallenexpensify** 2022-12-22 20:43 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by s77rt** [comment] 2022-12-22 20:46
@mallenexpensify Sorry about that, I have been informed about this recently, won't happen again. And thanks for issuing the payment.
