### ISSUE TITLE
[$500] Web - The last message in LHN has a colon character (:) different from the last message in the task report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27671] opened 2023-09-18 13:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report
2. Create a task
3. In the task detail click mark as done
4. Observe that the last message shown in LHN and task report are different

## Expected Result:
 Last message in LHN does not have a colon character (:)

## Actual Result:
The last message shown in LHN and task report are different

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/89992dff-8cce-4083-a39b-951b32d3d3ba

https://github.com/Expensify/App/assets/93399543/9fe14813-b964-465c-a8c6-6bf38d65dc65

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694877258526769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by HardikChoudhary24** [comment] 2023-09-18 14:29
### Proposal
### Please re-state the problem that we are trying to solve in this issue
- The last message in LHN has a colon character (:) different from the last message in the task report.

## What is the root cause of that problem?

- The root cause of this issue lies within the TaskAction Component, which is primarily responsible for rendering the message action. The problem stems from the absence of a semicolon between ```${taskStatusText}``` and ```${taskReportName}```
 
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/components/ReportActionItem/TaskAction.js#L58-L60

### What changes do you think we should make in order to solve the problem?

- To address this problem, we can resolve it by simply inserting a semicolon between `` ${taskStatusText} ``  and  ``${taskReportName}``.

**What alternative solutions did you explore? (Optional)**
N/A

**Comment by strepanier03** [comment] 2023-09-18 23:03
Double assignment, taking myself off. This is happening quite often lately.

**Comment by narefyev91** [comment] 2023-09-19 08:00
Proposal from @namhihi237 looks good to me - https://github.com/Expensify/App/issues/27671#issuecomment-1723367800
Both renders should be the same

**Comment by DylanDylann** [comment] 2023-09-19 08:02
@narefyev91 @namhihi237 proposal is invalid. It not work for me

**Comment by DylanDylann** [comment] 2023-09-19 08:04
@narefyev91 It seems @namhihi237's proposal is outdated now

**Comment by narefyev91** [comment] 2023-09-19 08:04
Proposal from @namhihi237 looks good to me - https://github.com/Expensify/App/issues/27671#issuecomment-1723367800
Both renders should be the same
LGTM!
🎀 👀 🎀 C+ reviewed

**Comment by narefyev91** [comment] 2023-09-19 08:06
> @narefyev91 It seems @namhihi237's proposal is outdated now

Code changes were done after @namhihi237 posted proposal - in any case area and root case were identified correctly from his side - and any code changes should be discussed during PR review

**Comment by narefyev91** [comment] 2023-09-19 08:28
> @narefyev91
> 
> > We should create a function to return the message action and use both places
> 
> It seems that the utils function in this case isn't suitable even before the new change. [My proposal](https://github.com/Expensify/App/issues/27671?notification_referrer_id=NT_kwDOB7gGPLQ3NzU2ODc0ODQwOjEyOTUwMDczMg#issuecomment-1724808365) is simpler and easier to implement.

Some one already did this logic inside Task.getTaskReportActionMessage - which is now can be used in any place to correctly build `${taskStatusText} ${report.reportName}` - and those util should be used as well in SideBar.js - to make code in one place and avoid such issues which we currently have - i think @namhihi237 was planning to write something similar

**Comment by namhihi237** [comment] 2023-09-19 08:30
@narefyev91 yeah, that's my ideal, if we want simple we can use my alternative solutions

**Comment by narefyev91** [comment] 2023-09-20 09:03
@dukenv0307 We should use getTaskReportActionMessage in SidebarUtils for this lines
<img width="1044" alt="Screenshot 2023-09-20 at 10 06 06" src="https://github.com/Expensify/App/assets/28352309/4c39d133-5fbf-4a04-abfa-e15d14f29bea">

**Comment by narefyev91** [comment] 2023-09-20 09:28
> @narefyev91 If we use getTaskReportActionMessage in SidebarUtils, we will make a logic change in case actionName is TASKCANCELLED

Hmm sorry not sure if i get you right - it will changed like this 
<img width="1134" alt="Screenshot 2023-09-20 at 12 27 44" src="https://github.com/Expensify/App/assets/28352309/629a49b6-41b5-447f-b2b1-776c2faf7b42">

**Comment by narefyev91** [comment] 2023-09-20 09:40
@dukenv0307 not see any issue in sidebar to get correct action - and base on this action get correct translation based on getTaskReportActionMessage function. In any case i think we can leave final decision for @bondydaa

**Comment by narefyev91** [comment] 2023-09-20 10:41
@dukenv0307 let's summarise a bit correctly:
1. proposal from @namhihi237 - who rise a proposal to have one function to return correct task statuses - (after some hours someone already implement those function getTaskReportActionMessage - but made a mistake not including ":" between `${taskStatusText} ${report.reportName}`; 
2. If for some reason we will not use proposal from @namhihi237 - second proposal should be picked from @HardikChoudhary24  - just to insert ":" between `${taskStatusText} ${report.reportName}`;

**Comment by zanyrenney** [comment] 2023-09-25 04:28
Thanks for the summary @narefyev91 

Just going to ping @bondydaa to confirm we're on the right track please?

**Comment by bondydaa** [comment] 2023-09-25 04:57
> proposal from @namhihi237 - who rise a proposal to have one function to return correct task statuses - (after some hours someone already implement those function getTaskReportActionMessage - but made a mistake not including ":" between ${taskStatusText} ${report.reportName};

Okay so am I understanding correctly that we just need to add a `:` somewhere? 

I'm going to assign @namhihi237 and lets add it in whatever method that was updated but didn't have it.

**Comment by bondydaa** [comment] 2023-10-02 04:04
looks like this Issue & PR changed the messages completely and removed the colons all together in favor of more streamlined messaging https://github.com/Expensify/App/issues/24601

Asked this on the PR but do we need to still do anything here then? Otherwise we can probably close this out?

**Comment by zanyrenney** [comment] 2023-10-02 08:11
I think this is all closed out @bondydaa and we can close this. Closing!

**Closed by zanyrenney** 2023-10-02 08:11 UTC
Labels: Reviewing, External, Weekly, Bug
