### ISSUE TITLE
Group - Offline added avatar doesn't persist

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40433] opened 2024-04-18 12:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** No, new feature
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Crate a group chat
2. Navigate to the group chat
3. Apply offline mode
4. Click on chat header > click on upload avatar icon
5. Upload avatar > change network to online mode

## Expected Result:
Offline uploaded avatar should persist

## Actual Result:
Offline added avatar reverts to default avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/dc3753cd-1941-44df-8bd1-41eae03ff541

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-18 12:52
@garrettmknight I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-18 12:53
We think this issue might be related to the #vip-vsb.

**Comment by MahmudjonToraqulov** [comment] 2024-04-18 13:52
Couldn't repro.

**Comment by arosiclair** [comment] 2024-04-18 15:42
Couldn't reproduce either on **v1.4.63-0**:

https://github.com/Expensify/App/assets/6833644/2bc693d0-bedb-4434-a654-abcea4317258

Going to close this out

**Closed by arosiclair** 2024-04-18 15:42 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
