### ISSUE TITLE
[HOLD for payment 2023-10-16] [$1000] Android - Inconsistency bug: App allows user to scroll behind mention results

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27140] opened 2023-09-11 12:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app on android
2. Open any report
3. Search for mentions in a way that search results should be less then 5
4. Scroll over mention options and observe that app scrolls messages behind
5. Try the same on android chrome and observe that it does not scroll messages behind

## Expected Result:
App should not scroll messages behind on scroll over mention options when results are less then 5

## Actual Result:
App scrolls messages behind on scroll over mention options when results are less then 5

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8d22ed30-693f-43e1-8262-953c99bd2162

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690045709955489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b12986525d5d8282</li>
        <li>Upwork Job ID: 1701215683522777088</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26922103</li>
<li>getusha | Contributor | 26922109</li>
<li>dhanashree-sawant | Reporter | 26922112</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-09-11 20:57
Removed @laurenreidexpensify because we both got assigned when the external label was added.

**Comment by redpanda-bit** [comment] 2023-09-12 15:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Prevent scrolling of messages when mentions suggestions are less than 5.

### What is the root cause of that problem?
It appears that the android operating system handles absolutely positioned views on top of scrollview different from the expected. Instead of registering the scroll in the mentions list, it registers it as if the user scrolled on the messages list instead.

### What changes do you think we should make in order to solve the problem?
I found that the issue goes away when the **mentions list** is scrollable. Therefore, I would enable scrolling of the mentions list when it has less than 5 items. 

This can be accomplished by reducing the `height` of the container element in (`height` is returned by this function in [BaseAutoCompleteSuggestions.js](https://github.com/Expensify/App/blob/c0363b79139fb73743170976e2bb9e7df3b2a907/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js#L16-L29)) just enough to make the component scrollable (`-0.5`). This little hack would produce the result below, bringing the experience closer to the iOS experience.

https://github.com/Expensify/App/assets/25206487/0987ca9a-1074-4697-8641-634b79546a1c

Here is the condition I would use:

```js
// On android reduce total height by 0.5 (smallest amount needed) to make component scrollable
if (getOperatingSystem() === CONST.OS.ANDROID) {
  return numRows * CONST.AUTO_COMPLETE_SUGGESTER.SUGGESTION_ROW_HEIGHT - 0.5;
}
```



### What alternative solutions did you explore? (Optional)
1. Lock the messages list from scrolling while the mentions list is visible. `scrollEnabled` set to `false` if mentions list is visible.
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by sakluger** [comment] 2023-09-14 17:35
@cubuspl42 could you please review the above proposal?

**Comment by cubuspl42** [comment] 2023-09-15 11:58
@redpanda-bit This might work, but such hacks are a last resort. Have you found exactly what's the root cause of the bug? Is it actually a known problem or Android and/or React Native on Android? Are there any open upstream issues?

**Comment by redpanda-bit** [comment] 2023-09-17 16:57
Thanks for catching that.

I could not find statements that directly backup my proposal.

Closest ones were these two:

1. "[Scrollview] Doesn't yet support other contained responders from blocking this scroll view from becoming the responder." (doesn't mention android). [Source](https://reactnative.dev/docs/scrollview#:~:text=Doesn%27t%20yet%20support%20other%20contained%20responders%20from%20blocking%20this%20scroll%20view%20from%20becoming%20the%20responder).
2.  "if you click inside a portal, and the portal is wrapped in `<div onClick>`, that onClick handler will fire." (mentions list is wrapped in a `createPortal`, however, the scrolling list is not the wrapping component). [Source](https://react.dev/reference/react-dom/createPortal#:~:text=if%20you%20click%20inside%20a%20portal%2C%20and%20the%20portal%20is%20wrapped%20in%20%3Cdiv%20onClick%3E%2C%20that%20onClick%20handler%20will%20fire).

Essentially what my proposal is doing is stopping the propagation of the scroll event to the list behind by keeping itself the scroll responder.

**Comment by cubuspl42** [comment] 2023-09-18 09:18
1.

> Doesn't yet support other **contained** responders

Does it apply to us? Is the suggestion list _contained_ within the report scroll view?

2. You already noticed that this doesn't apply

What I mean in general is that we observe a quite serious UI bug that seems to have its origin on the framework level. Intuitively, the behavior we observe on the attached videos should never happen in a reasonable UI framework, unless the upper widget is explicitly annotated as interactively transparent. Sure, sometimes things like this need a workaround, but such a workaround should be applied with awareness of how this bug is being handled in the upstream.

**Comment by cubuspl42** [comment] 2023-09-18 09:26
@sakluger I think we should raise the bounty to $1k. From what was shown so far, this doesn't look like a problem on _our_ side. I'd like to attract this kind of contributor input we haven't got so far:

- Investigating the _preceise_ root cause of the problem
- Finding the upstream issue(s) for the problem
  - When/if they are found, applying the (potentially better) workarounds shared in the relevant discussion

**Comment by redpanda-bit** [comment] 2023-09-18 19:23
> > Doesn't yet support other **contained** responders
> 
> Does it apply to us? Is the suggestion list _contained_ within the report scroll view?

Doesn't apply to us.

I agree with waiting for a precise root cause, might be ambitious but it's technically the right thing to do, unless the issue becomes high priority/blocker.

**Comment by sakluger** [comment] 2023-09-22 03:22
Raised the bounty to $1000.

**Comment by getusha** [comment] 2023-09-22 09:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
when you scroll through the list of mentions, the app also scrolls the content behind the mention results.
### What is the root cause of that problem?
This specific issue was fixed before here https://github.com/Expensify/App/issues/18112 using the following solution:
>Instead of setting height directly on FlatList, apply height to the parent View component. Also set flex:1 to FlatList. This fixes the scroll issue with nested Flatlist and prevents the chat list from scrolling instead.

then soon after there was a change intended to improve the UI style https://github.com/Expensify/App/pull/18951 (Not to fix any issue) This [change](https://github.com/Expensify/App/pull/18951/files#diff-7a1cce1ae353f8a3115cbbae05626f4b7d04839df1f01bfd29603f5eb2622eebR1033) involved adjusting the height measurement from "itemsHeight" to a height that includes the border's height along with its value, which rendered the previous fix ineffective.

### What changes do you think we should make in order to solve the problem?


Instead of increasing the height by the "borderWidth," we can instead apply it to the padding. This way, we can maintain the same UI appearance without causing this issue.

https://github.com/Expensify/App/blob/6836eafd97bd9b21b1afa4bdeacf2e9808ae7c6b/src/styles/StyleUtils.ts#L946-L947

```diff
-    const height = itemsHeight + 2 * CONST.AUTO_COMPLETE_SUGGESTER.SUGGESTER_INNER_PADDING + borderWidth;
+    const padding = CONST.AUTO_COMPLETE_SUGGESTER.SUGGESTER_PADDING + optionalPadding + borderWidth;
+    const height = itemsHeight + 2 * CONST.AUTO_COMPLETE_SUGGESTER.SUGGESTER_INNER_PADDING;
```

<details><summary>Result:</summary>

https://github.com/Expensify/App/assets/75031127/70ab1c18-ad97-497f-8439-08fd762af3c1

</details> 


### What alternative solutions did you explore? (Optional)

**Comment by cubuspl42** [comment] 2023-09-22 10:03
@getusha But again, is this a known upstream issue? Or do you think this is not a bug in React Native at all, and it's ever reasonable for the UI to handle input like this?

**Comment by getusha** [comment] 2023-09-22 10:29
@cubuspl42 I don't think this is a bug in React Native, we could ask the same question for [react-native-gesture-handle](https://github.com/software-mansion/react-native-gesture-handler/blob/93f4ed3b7a07f987aec2eb8bff370e4665d96584/src/components/GestureComponents.tsx) but In this case, they have an Android-only [prop](https://docs.swmansion.com/react-native-gesture-handler/docs/next/gesture-handlers/api/nativeview-gh/#shouldactivateonstart-android-only) that appears to be designed for situations like this. but this prop might break some functionalities like swiping right to go back, we can have a condition to determine if the gesture is being swiped vertically or horizontally to set the value. but compared to the solution we applied before i don't think its better.

>shouldActivateOnStart (Android only)
>When true, underlying handler will activate unconditionally when in BEGAN or UNDETERMINED state.


We are usingFlatList from the react-native-gesture-handler library, rather than directly from React Native.

**Comment by cubuspl42** [comment] 2023-09-25 10:11
The proposal by @getusha achieved what I aimed for. It pointed out more precise a root cause, specifically a problem in a third-party library which we fixed before, classifying the problem as a regression.

A fix is simple and its intention is to bring the effect we achieved previously in https://github.com/Expensify/App/issues/18112.

C+ reviewed 🎀 👀 🎀

**Comment by sakluger** [comment] 2023-09-28 07:07
@NikkiWines mind checking the C+ approved proposal?

**Comment by NikkiWines** [comment] 2023-09-28 10:31
Sorry for the delay! Agreed with @cubuspl42, @getusha's proposal looks good.

**Comment by getusha** [comment] 2023-09-28 14:07
@cubuspl42 @NikkiWines the [PR](https://github.com/Expensify/App/pull/28389) is ready for review!

**Comment by NikkiWines** [comment] 2023-10-05 05:43
@MelvinBot is wrong here and the delay was on my end for reviewing - it could have been merged as early as Sept 29th and so should be eligible for the urgency bonus.

**Comment by cubuspl42** [comment] 2023-10-10 09:02
- The PR that introduced the bug has been identified. Link to the PR:
    -  https://github.com/Expensify/App/pull/18951
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - https://github.com/Expensify/App/pull/18951/files#r1351934705
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - We should
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - Launch the application
    - Initiate a chat with an extensive conversation history that spans multiple screen pages
    - Open the mentions dialog, ensuring the results are fewer than 5
    - Scroll through the mention list
    - Confirm that scrolling through the mention list does not affect the background scrolling

**Closed** 2023-10-16 17:22 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by cubuspl42** [comment] 2023-10-17 08:58
@sakluger 

I clarified one step:

> Open the mentions dialog **(by typing "@")**
