### ISSUE TITLE
[HOLD for payment 2023-08-02] [$250] Migrate WorkspaceReimburseSection.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16311] opened 2023-03-20 15:42 UTC
### Filenames
- [ ] [src/pages/workspace/reimburse/WorkspaceReimburseSection.js](https://github.com/Expensify/App/blob/main/src/pages/workspace/reimburse/WorkspaceReimburseSection.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162f373806a50f327</li>
        <li>Upwork Job ID: 1673399849834561536</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-04-13 21:39
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by muxriddinmuqimov77** [comment] 2023-06-06 05:36
I can work on this issue when it goes to external

**Comment by s-alves10** [comment] 2023-06-06 10:09
I'd love to work on this.

**Comment by olexyt** [comment] 2023-06-26 20:22
I love to work on this.

**Comment by asadath1395** [comment] 2023-06-27 00:46
I would love to work on this. Can i get this assigned?

**Comment by dayana7204** [comment] 2023-06-27 20:32
I am ready to work on this ticket :)

**Comment by Elkaramany** [comment] 2023-06-28 10:04
**Issue Description**
The current implementation of the WorkspaceReimburseSection component is based on a class component. There is a request to refactor it into a function-based component to align with best practices and improve code readability.

**Proposed Solution**
To address the request, I propose refactoring the WorkspaceReimburseSection component from a class component to a functional component. This can be achieved by converting the class declaration into a function declaration and rewriting the necessary lifecycle methods and state management logic.

**Refactoring Steps**
Remove the class declaration and replace it with a function declaration for the WorkspaceReimburseSection component.
Remove the constructor and any associated state initialization code.
Replace the componentDidUpdate method with the appropriate useEffect hook to handle the side effects.
Rewrite the setShouldShowLoadingSpinner method using the useState hook to manage the shouldShowLoadingSpinner state.
Update the render method to return JSX directly from the function body.
Adjust the usage of this.props to directly reference the props received as function arguments.

**Testing**
To ensure the refactored component functions correctly, the following tests can be performed:

1. Verify that the refactored component renders without any errors or warnings.
2. Confirm that the functionality of the component remains unchanged after the refactoring.
3. Validate that the refactored component integrates properly with its parent components and passes down the required props.

**Comment by Elkaramany** [comment] 2023-06-28 10:05
Contributor details
Your Expensify account email: MostafaElkaramany@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016dd0b8a3f4b5aabf

**Comment by code0406** [comment] 2023-06-29 07:50
I am eager to take on this task.

**Comment by abdulrahuman5196** [comment] 2023-06-29 14:42
These migration issues are currently first come first served. So @muxriddinmuqimov77  are you available to take this issue?

**Comment by abdulrahuman5196** [comment] 2023-06-29 15:41
@Nodebrute Ok, let me check on this.

From this slack chat https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119. Its mentioning,

"If you want to work on an issue make sure that it is off HOLD and has the External + Help Wanted label applied. The first to leave a comment after the issue is taken off HOLD will most likely get assigned to the issue, but Expensify will use our discretion here in case there is someone we’d rather have the migration done by due to experience, overlap with another project, etc."

So I think we would have consider only the proposals after Help Wanted is added.

@johncschuster  Could you provide some light here?

If we only consider proposals after Help Wanted label is added, @Nodebrute 's proposal takes priority. If not, we have to check if @muxriddinmuqimov77 is available.

**Comment by code0406** [comment] 2023-06-29 23:06
I am eager to take on this task.

**Comment by vdem0115** [comment] 2023-06-30 16:42
I would like to work on this issue.

**Comment by abdulrahuman5196** [comment] 2023-06-30 17:02
@johncschuster  Gentle ping on this https://github.com/Expensify/App/issues/16311#issuecomment-1613433589

**Comment by abdulrahuman5196** [comment] 2023-06-30 17:26
Hi @Nodebrute, Found this comment on the long thread

https://expensify.slack.com/archives/C01GTK53T8Q/p1685984018164909?thread_ts=1685727880.152119&cid=C01GTK53T8Q
"I think out of fairness it should be AFTER the HOLD has been removed. Otherwise you can comment on every issue to “get in line” and honestly that seems kind of a mess to me because everyone will comment on all the issues"

So you should be eligible for this issue. Sorry for the inconvenience.

**Comment by abdulrahuman5196** [comment] 2023-06-30 17:27
@johncschuster  Can we assign @Nodebrute  to this issue since they where the first to comment after the issue went external? https://github.com/Expensify/App/issues/16311#issuecomment-1608059714

**Comment by abdulrahuman5196** [comment] 2023-07-05 18:10
@johncschuster Could you check on this ? https://github.com/Expensify/App/issues/16311#issuecomment-1614959207

**Comment by johncschuster** [comment] 2023-07-07 20:59
Not overdue, Melvin.

**Comment by johncschuster** [comment] 2023-07-19 16:10
@abdulrahuman5196 can you please review the PR above or reassign it if you don't have the bandwidth? Thank you!

**Comment by johncschuster** [comment] 2023-07-30 17:49
@JmillsExpensify it looks like @abdulrahuman5196 is meant to receive payment via NewDot. Unless you say otherwise, I will _not_ issue payment for @abdulrahuman5196 through Upwork so you can handle it through NewDot.

**Comment by johncschuster** [comment] 2023-07-30 17:50
### Summary of payments:
Contributor that fixed the issue - @Nodebrute - $250
Contributor+ that helped on the issue and/or PR - @abdulrahuman5196 - $250 (TO BE PAID VIA NEWDOT)

**Comment by abdulrahuman5196** [comment] 2023-08-01 18:59
>Contributor+ that helped on the issue and/or PR - @abdulrahuman5196 - $250 (TO BE PAID VIA NEWDOT)

@johncschuster Nope. I am still receiving payment from upwork 🤕

**Comment by johncschuster** [comment] 2023-08-02 23:25
Ok cool. Thank you for the heads up!

**Comment by johncschuster** [comment] 2023-08-02 23:25
### Updated Summary of payments:
Contributor that fixed the issue - @Nodebrute - $250
Contributor+ that helped on the issue and/or PR - @abdulrahuman5196 - $250

**Comment by johncschuster** [comment] 2023-08-02 23:28
I have issued payment to everyone! 🎉

**Closed by johncschuster** 2023-08-02 23:28 UTC
Labels: External, Engineering, Daily, Improvement, NewFeature, Awaiting Payment
