### ISSUE TITLE
[$1000] LHN Attachment taking some time to translate into Spanish

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19449] opened 2023-05-23 15:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Preferences > Language
2. Select Spanish language and go back
3. Now open a Chat
4. Send an Attachment to user
5. Check "Attachment" on LHN
6.  After that refresh it or send Attachment again

## Expected Result:
Attachment should be translated into Spanish after sending it to user

## Actual Result:
LHN Attachment taking some to to translate into Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17.0
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0ee36eab-ce4e-4f0b-a66e-8c1f98be0046

https://github.com/Expensify/App/assets/93399543/ef5dc2e0-a531-4ac0-8a77-c87a3a04943e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79 ([already paid](https://github.com/Expensify/App/issues/19449#issuecomment-1592859539))

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684419239615069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d09625bb565179a</li>
        <li>Upwork Job ID: 1661039461752336384</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-05-23 15:58
I have reproduced this, but could only do so on OSX desktop app (not on OSX Chrome).

**Comment by hungvu193** [comment] 2023-05-23 16:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN Attachment taking some to to translate into Spanish
### What is the root cause of that problem?
We are checking the preview message of attachment here:
https://github.com/Expensify/App/blob/a995c4d710593dcdccd8b3c2cdd5dfed61cf2901/src/libs/SidebarUtils.js#L261-L266
If the current last message is attachment then update the last message with the translate message. Now let take a look at function `ReportUtils.isReportMessageAttachment`:
https://github.com/Expensify/App/blob/a995c4d710593dcdccd8b3c2cdd5dfed61cf2901/src/libs/isReportMessageAttachment.js#L10-L16
In this case, the last text message is "Uploading attachment..." which make `isReportMessageAttachment` return false, that's why we still saw the english message even when we changed language to Spanish.
### What changes do you think we should make in order to solve the problem?

We should update the `isReportMessageAttachment` to include the case that our attachment is loading:
```
const UPLOADING_ATTACHMENT = "Uploading attachment...";
export default function isReportMessageAttachment({text, html}) {
    if (!text || !html) {
        return false;
    }

    const regex = new RegExp(` ${CONST.ATTACHMENT_SOURCE_ATTRIBUTE}="(.*)"`, 'i');
    return (text === CONST.ATTACHMENT_MESSAGE_TEXT || text === UPLOADING_ATTACHMENT) && !!html.match(regex);
}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Thanos30** [comment] 2023-05-23 20:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After uploading an attachment while in Spanish, the lastMessage shows [Attachment] until the OpenReport action is fired again.

### What is the root cause of that problem?

Since the upload process is taking some time to finish, we initially add on the report the HTML `Uploading attachment...`.

After the attachment is uploaded, it is being switched to the actual HTML code, which can then be processed by our Regex  and identify the Attachment, translating it successfully. 

The issue is that the report is not updating after the attachment is uploaded, which causes it to show the hardCoded text `[Attachment]`, until the OpenReport action is fired again (opening a different chat and then reopen the chat with the attachment again).

### What changes do you think we should make in order to solve the problem?

While the above proposals are close to the issue, their solution is not gonna work, since the `Uploading attachment...` text won't remain there, it will be updated once the attachment is uploaded.

My suggested solution is to actually reconnect to the Report once the Attachment is uploaded, and therefore translate the text immediately.

On the following code, we should add a line to run the `reconnect` function after the `addAttachment`.

```
addAttachment(file) {
        // Since we're submitting the form here which should clear the composer
        // We don't really care about saving the draft the user was typing
        // We need to make sure an empty draft gets saved instead
        this.debouncedSaveReportComment.cancel();
        const comment = this.prepareCommentAndResetComposer();
        Report.addAttachment(this.props.reportID, file, comment);
        Report.reconnect(this.props.reportID);
        this.setTextInputShouldClear(false);
    }
```

Also, while the attachment is uploading, we show the [Attachment] text. We should probably change that and show 'Uploading..' or something.

**Comment by tienifr** [comment] 2023-05-24 12:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN Attachment taking some to to translate into Spanish.

### What is the root cause of that problem?
When we're uploading an attachment, the last message HTML will be `Uploading attachment...` https://github.com/Expensify/App/blob/5cb2b745c52cedb0fd7ae64c0c438953a7d952b0/src/libs/ReportUtils.js#L1212

It will fail the check in https://github.com/Expensify/App/blob/5cb2b745c52cedb0fd7ae64c0c438953a7d952b0/src/libs/isReportMessageAttachment.js#L16

So the report last message will show the `[Attachment]` text as is without applying translation in https://github.com/Expensify/App/blob/5cb2b745c52cedb0fd7ae64c0c438953a7d952b0/src/libs/SidebarUtils.js#L263

I think there's a deeper problem to this. There're 2 types of text message:
1. User-generated message
2. Our system-defined message, like `[Attachment]`, `Uploading attachment...`, which should be translated when the user changes language.

We're conflating the above 2 types, and try to check hardcoded text (like if the text matches `[Attachment]` exactly, we'll show the translations). This is problematic because:
- It's using hardcoded data which can change anytime, like when the `Uploading attachment...` text is added, it won't be translated
- The user-generated message can coincide with the hardcoded text, if the user sends `[Attachment]` as a text, we shouldn't translate it

There's already another bug related to this, which is if you change the language to `Spanish`, go offline and send an attachment, it will still show `Uploading attachment...` in English.

### What changes do you think we should make in order to solve the problem?


A better way to show the correct message for attachment-related system messages will be to separate the 2 types of text messages. We should introduce a new `key` field in the message, aside from the existing `text` and `html` field.
If we add a system-defined message, like `[Attachment]`, `Uploading attachment...` to the report, we'll not use the `text` field but will use the `key` field, for example we set the `key` of the message to `common.attachment` or `common.uploadingAttachment`.

Then when ww show the attachment-related system messages in the LHN or the report messages, we'll check if the message has the `key` field, if yes we use `Localize.translateLocal(message.key)` to show it to the user. Doing this will make sure it will always show system messages in correct translations in all cases. 

### What alternative solutions did you explore? (Optional)
NA

**Comment by conorpendergrast** [comment] 2023-05-25 14:01
@eVoloshchak We have four proposals here for your review!

**Comment by conorpendergrast** [comment] 2023-05-30 10:40
Escalated the bump [to Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1685443220512549)

**Comment by eVoloshchak** [comment] 2023-05-30 11:09
I agree with @tienifr [on this one](https://github.com/Expensify/App/issues/19449#issuecomment-1561043031), our current implementation isn't ideal. We should have a separate `translationKey` for when an attachment is uploaded (user typing/recording a voice message/recording video/ etc), having user's message replaced with a hardcoded string seems a bit hacky. 

> A better way to show the correct message for attachment-related system messages will be to separate the 2 types of text messages.


🎀👀🎀 C+ reviewed!
cc: @yuwenmemon

**Comment by eVoloshchak** [comment] 2023-06-08 11:06
> I suggest that we remove Uploading attachment and use only Attachment. While the attachment is uploading, the LHN shows Attachment/attachment name and the chat shows an image/attachment placeholder. This matches other messaging platforms like Telegram or Skype. Are we good with this?

This looks good to me. The current behavior looks a bit odd, it currently is: text "uploading attachment" -> image placeholder with loading spinner -> image.
We can safely get rid of the first step. I think it was working like this at some point?

**Comment by conorpendergrast** [comment] 2023-06-09 19:02
I think we should probably discuss that via Slack to confirm that there's collective agreement on removing the "uploading attachment" step. I'll start that on Monday, unless someone beats me to it!

**Comment by conorpendergrast** [comment] 2023-06-12 12:31
Thanks! Tagged a few people in that Slack thread too

**Comment by conorpendergrast** [comment] 2023-06-14 13:12
I proposed next steps [in Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1686748278583679?thread_ts=1684419239.615069&cid=C049HHMV9SM), and will come back here once that's been agreed!

**Comment by conorpendergrast** [comment] 2023-06-15 11:21
Ok, as discussed [in Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1686748278583679?thread_ts=1684419239.615069&cid=C049HHMV9SM): 
1. The fix for [#19449](https://github.com/Expensify/App/issues/19449) is already being tackled in [#9402](https://github.com/Expensify/App/issues/9402) (and that is on hold)
2. So we should close this issue ([#19449](https://github.com/Expensify/App/issues/19449))
3. I’ll pay the bug reporter for ([#19449](https://github.com/Expensify/App/issues/19449))

**Comment by conorpendergrast** [comment] 2023-06-15 11:24
Going to send a bug bounty contract of $250 to @ayazhussain79 now

**Comment by ayazhussain79** [comment] 2023-06-15 11:27
@conorpendergrast offer accepted

**Comment by conorpendergrast** [comment] 2023-06-16 08:35
Reopening to check that, thanks @tienifr!

**Comment by conorpendergrast** [comment] 2023-06-21 08:29
I didn't reopen this 🤦  thanks for the bump

**Comment by conorpendergrast** [comment] 2023-06-22 13:11
Ok, I agree with @tienifr here that we should fix the translations for system messages here, thanks for explaining that so well in [the original proposal](https://github.com/Expensify/App/issues/19449#issuecomment-1561043031). 

@yuwenmemon do you agree?

**Comment by yuwenmemon** [comment] 2023-06-22 17:34
@tienifr what your describing sounds like it will need to be worked on internally though - is that correct?

**Comment by yuwenmemon** [comment] 2023-06-23 18:52
Cool @tienifr - submit a PR and let me know what you need on the back-end.

**Comment by conorpendergrast** [comment] 2023-06-26 10:27
We've confirmed a solution here, no stress about this being "overdue"

**Comment by conorpendergrast** [comment] 2023-07-06 16:07
oops, I didn't hire via Upwork! Looks like @eVoloshchak will request via New Expensify, and so I'll hire @tienifr via Upwork now!

**Comment by conorpendergrast** [comment] 2023-07-12 12:53
That still seems like it's outside of the 3 business day urgency bonus, correct @tienifr?

**Comment by conorpendergrast** [comment] 2023-07-12 15:23
Hah, ok, yes, I agree 👍

**Comment by stephanieelliott** [comment] 2023-07-18 07:37
Heads up it seems  https://github.com/Expensify/App/issues/22937 is a regression of this issue!

**Comment by conorpendergrast** [comment] 2023-07-18 18:30
Ok, thanks @stephanieelliott. That will mean a 50% penalty for the Contributor and Contributor+ on this issue, holding payment until https://github.com/Expensify/App/issues/22937 is fixed and on production for 7 days

**Comment by conorpendergrast** [comment] 2023-07-19 13:12
@tienifr We've adjusted that policy to apply equally to both the C and the C+, and I'm updating the documentation to confirm that [here](https://github.com/Expensify/App/pull/23112)

**Comment by eVoloshchak** [comment] 2023-07-19 13:19
@tienifr, could you take a look at https://github.com/Expensify/App/issues/22937?
Should we revert this PR or is there a fix we could apply?

**Comment by conorpendergrast** [comment] 2023-07-21 23:24
@tienifr and @eVoloshchak can we start making a move on this please? Thanks!

**Comment by eVoloshchak** [comment] 2023-07-26 17:22
@conorpendergrast, could you assign an internal engineer to this? Looks like [back-end changes](https://github.com/Expensify/App/pull/21780#issuecomment-1611123880) are needed for this

**Comment by conorpendergrast** [comment] 2023-07-26 19:45
That's @yuwenmemon!

**Comment by conorpendergrast** [comment] 2023-07-31 09:58
@yuwenmemon Could you take a look here please?

**Comment by conorpendergrast** [comment] 2023-08-03 11:54
@yuwenmemon Buuuuuuuuuummmppp!

**Comment by conorpendergrast** [comment] 2023-08-07 16:03
Ah dammit, I just spotted that Yuwen was OoO last week, and is OoO almost all this week. Reassigning now, welcome @thienlnam. This seems to be an internal change we need to make

**Comment by thienlnam** [comment] 2023-08-07 17:25
Back-end system messages are not localized and we've decided not to address them because it's not a priority right now. This applies to all system messages - not just the attachment one. Where did we decide this? 

IMO we should have not addressed this issue since adding another key to all reportActions is not ideal here

**Comment by conorpendergrast** [comment] 2023-08-08 06:45
@thienlnam So in this case, "Attachment" is the back-end system message? 

<img width="607" alt="image" src="https://github.com/Expensify/App/assets/5802477/7b43778b-d352-40c5-883b-1f00a246454c">

That _was_ localised, it was just taking time (a page refresh) to show in Spanish rather than in English

**Comment by thienlnam** [comment] 2023-08-08 18:02
> So in this case, "Attachment" is the back-end system message?

Yeah, that is a back-end system message.  We're just doing some front-end handling to change the language if it's an attachment hence why we need to refresh to show it in Spanish

In any case, lastMessageTranslationKey does not exist on a report or a reportAction and I don't think we should add it. Let's just call it good here?

**Comment by eVoloshchak** [comment] 2023-08-09 12:37
> Back-end system messages are not localized and we've decided not to address them because it's not a priority right now. This applies to all system messages - not just the attachment one. Where did we decide this?

@thienlnam, this was discussed in [this slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1688134958591739?thread_ts=1687190693.298329&cid=C01GTK53T8Q), but I agree, I should have gotten an approval from more engineers before proceeding

**Comment by thienlnam** [comment] 2023-08-09 17:55
Thanks for linking the thread - yeah I think this requires a larger conversation. Though since this is already done let's leave it and in the future as mentioned in the thread leave small bugs related to this alone especially when related to switching languages

**Comment by conorpendergrast** [comment] 2023-08-14 15:03
Am I right in thinking that we just close this issue out, in that case?

**Comment by thienlnam** [comment] 2023-08-14 15:13
Yup that sounds good to me

**Comment by thienlnam** [comment] 2023-08-18 14:47
We should fix that issue if this PR caused it - that doesn't seem to be due to translation from the BE

**Comment by conorpendergrast** [comment] 2023-08-21 19:05
Ok, then we keep this issue (19449) open in order to fix https://github.com/Expensify/App/issues/22937, correct?

**Comment by thienlnam** [comment] 2023-08-21 21:04
Yeah sounds good to me

cc @tienifr / @eVoloshchak Are you able to handle the [regression](https://github.com/Expensify/App/issues/22937) made from this PR for this issue?

**Comment by thienlnam** [comment] 2023-08-24 18:47
Going to close this and move the convo into https://github.com/Expensify/App/issues/22937 as that is the bug we still need to fix

**Comment by conorpendergrast** [comment] 2023-11-15 10:05
Sorry, reopening to take a look at this!

**Comment by conorpendergrast** [comment] 2023-11-27 14:08
@tienifr ok, it sounds like I'll need to send an offer for payment to you and @eVoloshchak for $500 each ($1000 * 50% for a regression). Do you agree that's correct?

**Comment by conorpendergrast** [comment] 2023-11-27 14:22
Assuming that's the case, payouts due:

- [x] Issue Reporter: $50 @ayazhussain79 - [this job](https://www.upwork.com/jobs/~015d09625bb565179a)
- [ ] Contributor: $500 ($1000 * 50%) @tienifr - [this job](https://www.upwork.com/jobs/~0129f2ad5017ac5f0a) | this offer
- [ ] Contributor+: $500 ($1000 * 50%) @eVoloshchak  - [this job](https://www.upwork.com/jobs/~0129f2ad5017ac5f0a) | [this offer](https://www.upwork.com/nx/wm/offer/27848586)

**Comment by conorpendergrast** [comment] 2023-12-04 12:13
@eVoloshchak please accept [the offer](https://www.upwork.com/nx/wm/offer/27848586)!

**Comment by conorpendergrast** [comment] 2023-12-07 14:04
Last bump to accept [the offer](https://www.upwork.com/nx/wm/offer/27848586) please

**Comment by eVoloshchak** [comment] 2023-12-08 11:20
@conorpendergrast, no need for Upwork, I just requested the payment via NewDot
Apologies for a delay

**Comment by conorpendergrast** [comment] 2023-12-08 11:23
Ah, sorry, I forgot to check that! All done, closing

**Closed by conorpendergrast** 2023-12-08 11:23 UTC
Labels: External, Engineering, Daily, Bug

**Comment by JmillsExpensify** [comment] 2023-12-11 01:22
$500 payment approved for @Santhosh-Sellavel based on [this comment](https://github.com/Expensify/App/issues/19449#issuecomment-1827930658).
