### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$250] Migrate ValidationStep.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16248] opened 2023-03-20 08:51 UTC
### Filenames
- [ ] [src/pages/ReimbursementAccount/ValidationStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/ValidationStep.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ca415fbb372eba9</li>
        <li>Upwork Job ID: 1693721287278202880</li>
        <li>Last Price Increase: 2023-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26248714</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-06-06 10:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate ValidationStep.js to function component
### What is the root cause of that problem?
No root cause, just refactoring
### What changes do you think we should make in order to solve the problem?
We should update [src/pages/ReimbursementAccount/ValidationStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/ValidationStep.js) to be functional component

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-06-06 11:11
I'd love to work on this.

**Comment by payal-lathidadiya** [comment] 2023-07-01 20:07
I'd like to work on this if opens up for external contribution

**Comment by vdem0115** [comment] 2023-07-04 15:29
I would like to work on this.

**Comment by alpeshl** [comment] 2023-07-05 12:54
I can work this issue

**Comment by disha-np** [comment] 2023-07-06 08:30
can I work on this?

**Comment by disha-np** [comment] 2023-07-06 08:32
Your Expensify account email: disha.np.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f9d897d8ff4be081

**Comment by disha-np** [comment] 2023-07-06 08:34
Contributor details
Your Expensify account email: disha.np.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f9d897d8ff4be081

**Comment by olexyt** [comment] 2023-07-07 14:57
I can work on this issue.

**Comment by to-ai** [comment] 2023-07-11 21:25
I am able to work on this task.

**Comment by josemazhuvanchery1** [comment] 2023-07-25 14:52
I would like to work on this issue.

**Comment by josemazhuvanchery1** [comment] 2023-07-25 15:41
Contributor details
Your Expensify account email: jose1998mathew@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01be2b3c21f1891e44

**Comment by BartoszGrajdek** [comment] 2023-08-21 12:22
Hey! I’m Bartosz from Software Mansion, an expert agency, and I’d like to work on this issue

**Comment by payal-lathidadiya** [comment] 2023-08-23 03:57
can I work this

**Comment by abdulrahuman5196** [comment] 2023-10-10 12:57
@BartoszGrajdek Could you check on this ? https://github.com/Expensify/App/pull/25663#discussion_r1342792421

It has been waiting for sometime

**Comment by bfitzexpensify** [comment] 2023-10-20 18:20
Payment due 10/23

**Comment by abdulrahuman5196** [comment] 2023-10-23 18:39
No checklist for migration PR.

**Comment by bfitzexpensify** [comment] 2023-10-24 22:45
Payment complete, closing this out.

**Closed by bfitzexpensify** 2023-10-24 22:45 UTC
Labels: External, Engineering, Daily, NewFeature, Awaiting Payment
