### ISSUE TITLE
[$1000] Web - Routing number field for new workspace is populated with value from deleted workspace.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23480] opened 2023-07-24 12:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Create a workspace.
3. Go to Bank Account
4. Update currency to USD on popup.
5. Click on 'connect manually'.
6. Enter a routing number.
7. Now instead of clicking on continue, go back and delete that workspace.
8. Create a workspace again.
9. Go to Bank account and change currency to USD.
10. Go to 'connect manually'

## Expected Result:
The routing number field should be empty.

## Actual Result:
Routing number field is populated with routing number value which we had entered in our deleted workspace.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/97cdfc91-0e35-4e24-bc5f-bcddf430925f

https://github.com/Expensify/App/assets/93399543/a244758f-c41d-486c-a6d2-b52299a01d25

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mehvash-Khan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690113213055829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d45e1d746eb489a</li>
        <li>Upwork Job ID: 1683580182181593088</li>
        2023-07-24<li>Automatic offers: </li>
<ul>
<li>samh-nl | Contributor | 25818185</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-07-24 16:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A new workspace is populated with routing number field of a deleted workspace.

### What is the root cause of that problem?
The bank account form data is re-used between all workspaces because we use same `inputID`
https://github.com/Expensify/App/blob/80ac6969cdf51e060a13e8113527d2a0d7149b16/src/pages/ReimbursementAccount/BankAccountManualStep.js#L95-L107
### What changes do you think we should make in order to solve the problem?
We can get `policyID` as props from `ReimbursementAccountPage` -> `BankAccountStep` -> `BankAccountManualStep`.
And we can use different `inputID` between workspaces
```
inputID={`${props.policyID}-routingNumber`}
defaultValue={props.getDefaultStateForField(`${props.policyID}-routingNumber`, '')}
```
In this case, input will be clear on new workspace and we can use other values between workspace
### What alternative solutions did you explore? (Optional)

**Comment by jasperhuangg** [comment] 2023-07-28 22:41
I think it's a bit odd that we're sharing bank account information between workspaces. Even if we could auto-fill them for convenience, chances are that different workspaces will be associated with different bank accounts. This is normally how it works in OldDot. Therefore, I think we should make it so that the bank account form data is unique between each workspace. Let's move forward with @samh-nl's proposal.

**Comment by mehvash-Khan** [comment] 2023-07-29 08:16
I have applied to the Upwork job. Thanks.

**Comment by mehvash-Khan** [comment] 2023-08-18 19:21
Hi @parasharrajat , Is this issue open for more proposals? Can I add a proposal?

**Comment by jasperhuangg** [comment] 2023-08-21 17:47
> we are touching mostly everything related to policies in the app and there can be unexpected bugs with these changes

@parasharrajat Can you outline what changes introduced in the PR might cause bugs with policies?

**Comment by jasperhuangg** [comment] 2023-08-28 19:07
@samh-nl I'm honestly starting to think we can just do nothing here. I don't think this particular bug is extremely detrimental to user experience. I'm not really sure if it's worth considering this a bug at all, it could even be considered a feature that your bank account information is saved between workspaces. I'm going to go ahead and close this out.

**Closed by jasperhuangg** 2023-08-28 19:07 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by kevinksullivan** [comment] 2023-10-09 21:47
We only pay when someone has done the work, sorry for any confusion here.
