### ISSUE TITLE
Web - Profile - The text gets bigger when using autofill

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19853] opened 2023-05-30 21:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Profile -> Display name
4. Clear any fields
5. Choose any text using autofill 

## Expected Result:
The text does not get bigger when using autofill

## Actual Result:
The text gets bigger when using autofill

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome i
- [ ] MacOS / Desktop

**Version Number:** 1.3.20.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/b856084436f6824d6839295694a6d65d3aae6551c33a414b67beac44c28a2484

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2023-05-30 22:13
Cannot reproduce - Closing until we have reliable reproduction steps

**Closed by MitchExpensify** 2023-05-30 22:13 UTC
Labels: Daily, Needs Reproduction, Bug
