### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Split Bill - Number keeps on changing its initials

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27557] opened 2023-09-15 19:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB -> Split Bill
2. Enter some amount
3. In email or phone enter "[+919999676352](tel:+919999676352)"
4. Select/Unselect the user suggested bewlow

## Expected Result:
The user should be shown either [+919999676352](tel:+919999676352) or 09999676352

## Actual Result:
 It keep switching initials on click from [+919999676352](tel:+919999676352) to 09999676352 and vice versa

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.70-5.

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/22dba0eb-f4c4-4845-8c9b-7571ae32d602

https://github.com/Expensify/App/assets/115492554/39411ddb-dbb3-46ee-8184-a25328fe3341

**Expensify/Expensify Issue URL:**

**Issue reported by:** @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692652454644699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c4451db1b16853c4</li>
        <li>Upwork Job ID: 1702760550821027840</li>
        <li>Last Price Increase: 2023-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 26877939</li>
<li>DinalJivani | Reporter | 26877941</li>
</ul></li>
    </ul>
</details>

**Comment by robertKozik** [comment] 2023-09-18 10:53
Hi @ZhenjaHorbach! I appreciate your proposals; they correctly identify the root cause. I'm wondering if we could retain the formatter instead of disabling it entirely? Disabling it creates a discrepancy between the phone number in the title and the one below it in the subtitle. Ideally, they should match in my opinion.

**Comment by neil-marcellini** [comment] 2023-09-22 03:57
Hi guys. I'm not understanding the root cause explanation. Specifically, why does the formatting change when the option is selected vs not selected. How should the numbers be formatted? There must be a reason we have the phone number formatter so I don't want to disable it without a clear explanation why.

@ZhenjaHorbach please let me know when you have updated your proposal.

**Comment by robertKozik** [comment] 2023-09-25 06:58
@ZhenjaHorbach I think your root cause is lacking why the number keeps changing (in other words why the formatter is triggered only when user is selected)

**Comment by neil-marcellini** [comment] 2023-09-26 06:57
Ok I'm good with @ZhenjaHorbach's proposal. In the future please only update your original proposal.

**Comment by johncschuster** [comment] 2023-09-28 18:27
Sorry about that, @DinalJivani! You're right! Let me adjust that.

**Comment by neil-marcellini** [comment] 2023-10-12 17:59
Gentle bump @johncschuster @robertKozik

**Comment by johncschuster** [comment] 2023-10-12 18:06
Payment has been issued! We're just waiting on the BZ Checklist to be completed.

**Comment by robertKozik** [comment] 2023-10-12 20:19
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: I was unable to pinpoint exact PR, propably it was missed since implementation
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. I don't think it's suitable case for creating the regression test - this bug don't interfere with any of user flows
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A

**Comment by neil-marcellini** [comment] 2023-10-16 20:59
I'm bumping @johncschuster

**Comment by johncschuster** [comment] 2023-10-16 22:06
The BZ Checklist is done, which is the only thing we were waiting on. Closing!

**Closed by johncschuster** 2023-10-16 22:06 UTC
Labels: External, Daily, Awaiting Payment, Bug
