### ISSUE TITLE
[HOLD for payment 2024-10-10] [$250] Copilot - Missing email in RHP header and message when adding new contact

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48968] opened 2024-09-11 09:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Login as copilot
3. Go to Account settings.
4. Click on the account switcher.
5. Switch to another account.
6. Click Contact method.
7. Click New contact method.
8. Enter a new contact method > Next.

## Expected Result:
The RHP header will show the current contact method.
## Actual Result:
The RHP header is missing when confirming magic code for adding new contact method.
Also, the message "Please enter the magic code sent to" is also missing the email.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/13793b42-b666-462f-abfd-61f37ff10dba

https://github.com/user-attachments/assets/91527319-07f0-4b56-8c85-84591231b31a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834067418784580129</li>
        <li>Upwork Job ID: 1834067418784580129</li>
        <li>Last Price Increase: 2024-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103936362</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by IuliiaHerets** [comment] 2024-09-11 09:14
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment] 2024-09-12 03:02
> Go to staging.new.expensify.com
> Login as copilot

I don't appear to be able to do this at all. I have tried multiple accounts with copilots and I don't have the drop-down.

**Comment by RachCHopkins** [comment] 2024-09-12 03:03
@kadie is gonna repro for me.

**Comment by kadiealexander** [comment] 2024-09-12 03:06
Reproduced in web chrome:

https://github.com/user-attachments/assets/e1959f18-09f3-4b99-abaf-571699fb3b67

**Comment by nkdengineer** [comment] 2024-09-12 03:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The RHP header is missing when confirming magic code for adding new contact method.
Also, the message "Please enter the magic code sent to" is also missing the email.

### What is the root cause of that problem?
We get the contact method by accessing `account?.primaryLogin`. In the case of accessing account via Copilot, the account data doesn't have  `primaryLogin` field

<img width="1512" alt="Screenshot 2024-09-12 at 10 37 35" src="https://github.com/user-attachments/assets/69d662ca-2f4d-4147-9aab-48e62328a211">

https://github.com/Expensify/App/blob/336e4782aec98bb29a06c28e0d630c276d4eddf6/src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx#L41
### What changes do you think we should make in order to solve the problem?
We should use session data to get the email of the user 

```
const [session] = useOnyx(ONYXKEYS.SESSION);
const contactMethod = session?.email ?? '';
```
https://github.com/Expensify/App/blob/336e4782aec98bb29a06c28e0d630c276d4eddf6/src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx#L41

```
const contactMethod = Object.keys(loginList ?? {}).find((login) => loginList?.[login]?.partnerUserID === login);
```
or if we want to default contact method we can find in the login list that has the email is `partnerUserID`


### What alternative solutions did you explore? (Optional)
NA

**Comment by sobitneupane** [comment] 2024-09-12 13:18
Thanks for the proposal @nkdengineer 

I believe we should use `session?.email` only if `account?.primaryLogin ` is not available. What do you think?

```    
const contactMethod = account?.primaryLogin ?? session?.email ?? '';
```

> We also need to fix the other cases in that we use account?.primaryLogin

Could you please specify which other features or cases require changes involving the use of account?.primaryLogin?

**Comment by nkdengineer** [comment] 2024-09-12 13:48
> I believe we should use session?.email only if account?.primaryLogin is not available. What do you think?

@sobitneupane  I think that makes sense. I think we can create a util for this and use in other places.


> Could you please specify which other features or cases require changes involving the use of account?.primaryLogin?

I checked the use of `account?.primaryLogin` in the App and see that we have some other places that we use this data.

**Comment by sobitneupane** [comment] 2024-09-12 14:03
Thanks for the update @nkdengineer 

[Proposal](https://github.com/Expensify/App/issues/48968#issuecomment-2345207080) from @nkdengineer looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by rafecolton** [comment] 2024-09-12 20:35
Proposal LGTM, assigning @nkdengineer

**Comment by rafecolton** [comment] 2024-09-30 19:04
Approved the PR, waiting for a response [here](https://expensify.slack.com/archives/C03TQ48KC/p1727722725164299) before merging.

**Comment by rafecolton** [comment] 2024-10-01 22:48
PR is merged

**Comment by RachCHopkins** [comment] 2024-10-02 00:24
@sobitneupane the automation has failed here, can I get you to do the checklist, please? 

And I guess this will be ready to pay on 8 October.

**Comment by sobitneupane** [comment] 2024-10-02 10:49
**Regression Test Proposal**

1. Login as copilot
2. Go to Account settings.
3. Click on the account switcher.
4. Switch to another account.
5. Click Contact method.
6. Click New contact method.
7. Enter a new contact method > Next.
8. Verify that correct contact method is displayed on the RHP header.

Do we agree 👍 or 👎

**Comment by RachCHopkins** [comment] 2024-10-10 20:35
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Closed by RachCHopkins** 2024-10-10 20:35 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by sobitneupane** [comment] 2024-10-11 12:35
@RachCHopkins I will need payment summary to request payment in newdot.

**Comment by RachCHopkins** [comment] 2024-10-14 03:31
Sorry @sobitneupane I didn't realise Melvin's summary was leaving that out!

Payment Summary:

- Contributor: @nkdengineer paid $250 via Upwork
- Contributor+: @sobitneupane to be paid $250 via NewDot manual request

Upwork job [here](https://www.upwork.com/jobs/~021834067418784580129)

**Comment by garrettmknight** [comment] 2024-10-23 10:12
$250 approved for @sobitneupane
