### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Android - Accounting-Confirm button doesn't work while keyboard is up

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45193] opened 2024-07-10 18:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/44921
## Action Performed:
Pre-requisite
- Collect workspace with accounting enabled
- NetSuite beta enabled for the user. (Use expensifail account)
- Setup NetSuite in OldDot
1. Open the app with the pre-setup workspace
2. Go to Accounting
3. Tap on the Advanced button
4. Tap on Reimbursable expense option (Enable Custom form ID to access this field)
5. Tap inside the input field and type something
6. Tap on Confirm
7. Do step 5 and 6 for Non-reimbursable expense option as well

## Expected Result:
Confirm button saves the input value regardless of the keyboard open state

## Actual Result:
Confirm button doesn't work while the soft keyboard is in open state

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a0d190a8-2dbd-42a7-af47-e2999ef3997b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01223454e1811195b9</li>
        <li>Upwork Job ID: 1811119420448681401</li>
        <li>Last Price Increase: 2024-07-10</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 103068524</li>
<li>shubham1206agra | Reviewer | 103068526</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment] 2024-07-10 18:07
@luacmartins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment] 2024-07-10 19:22
Seems to come from https://github.com/Expensify/App/pull/44921

**Comment by luacmartins** [comment] 2024-07-10 19:24
I don't think this needs to be a blocker since the button still works, just not when the virtual keyboard is active. Tagging the author and reviewers of the original PR to investigate this issue @shubham1206agra @mananjadhav @yuwenmemon

**Comment by mananjadhav** [comment] 2024-07-10 19:34
@shubham1206agra and I will take care of this. You can assign this to us. Also this is behind beta so not a deploy blocker.

cc - @yuwenmemon

**Comment by luacmartins** [comment] 2024-07-10 19:35
Done!

**Comment by Junio00r** [comment] 2024-07-10 22:55
Do you still have the issue with the button?

**Comment by luacmartins** [comment] 2024-07-11 15:38
@shubham1206agra is there something blocking the view and thus the press? Maybe there's an invisible element there.

**Comment by luacmartins** [comment] 2024-07-11 17:23
hmm then maybe it is a problem with the new code 😄

**Comment by kabeer95** [comment] 2024-07-11 20:47
Issue Report: Accounting - Confirm Button Not Functional with Keyboard Open on Expensify

Summary:

The "Confirm" button in the Accounting section of Expensify is not responding to clicks when the keyboard is open on mobile devices. This issue hinders users from completing the accounting process, leading to frustration and potential errors.

Reproduction Steps:

Open Expensify on a mobile device.
Navigate to the Accounting section.
Open the keyboard to enter or edit accounting information.
Attempt to click the "Confirm" button while the keyboard is still open.
Expected Result:

The "Confirm" button should respond to clicks and complete the accounting process.

Actual Result:

The "Confirm" button does not respond to clicks, and the accounting process cannot be completed.

Proposed Solution:

To resolve this issue, we recommend implementing one of the following solutions:

Disable keyboard when clicking the Confirm button: Automatically close the keyboard when the user clicks the "Confirm" button, ensuring the button is clickable.
Make the Confirm button keyboard-agnostic: Modify the button's functionality to work independently of the keyboard state, allowing users to click the button even when the keyboard is open.
Estimated Development Time:

We estimate 30 hours to implement the chosen solution and resolve this issue.

Benefits:

Resolving this issue will improve the overall user experience, reduce frustration, and increase the efficiency of the accounting process on Expensify.

Please let us know if you would like to discuss this issue further or proceed with the proposed solution.

**Comment by cdOut** [comment] 2024-07-29 11:32
I've tested it and the problem clearly lays in the wrapper component `ConnectionLayout`, which has been added recently for the integrations only and is used here in `NetSuiteCustomFormIDPage.tsx`. If we replace it with other components that fulfil a similar role it works properly. I'll go into how this component is implemented and find a fix so it doesn't disrupt this flow whenever it's used.

**Comment by cdOut** [comment] 2024-07-29 11:53
Turns out to be a very simple fix. The keyboard doesn't act correctly if the wrapper `ConnectionLayout` has the attribute `shouldUseScrollView` set to true. This seems like it has been a simple overlook while implementing the `NetSuiteCustomFormIDPage`.

I've set the attribute to `false` since this page does not require it, and it works properly now.

**Closed** 2024-08-12 09:38 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment
