### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] Web -  Phone number is shown twice in the preview tooltip.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21197] opened 2023-06-21 12:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Opened the website.
2. Hovered over the account without a name that contains a phone number.
3. Observed that the tooltip displays the contact details twice.

## Expected Result:
The phone number should not be shown twice in the tooltip.

## Actual Result:
The phone number is shown twice in the preview tooltip.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-06-21 at 3 46 04 AM](https://github.com/Expensify/App/assets/93399543/7fe20574-7859-4701-8d47-e00a9323711b)

https://github.com/Expensify/App/assets/93399543/a840a1e6-b779-4655-8c37-3874fc1e1520

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Tushu17

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686735136443679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011baa54223aee0feb</li>
        <li>Upwork Job ID: 1671800200350584832</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by manjesh-yadav** [comment] 2023-06-21 14:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Phone number is shown twice in the preview tooltip
### What is the root cause of that problem?

We display two texts in the tooltip `displayName` and `login`

```js
<Text style={[styles.mt2, styles.textMicroBold, styles.textReactionSenders, styles.textAlignCenter]}>
                    {String(userDetails.displayName).trim() ? userDetails.displayName : ''}
                </Text>

                <Text style={[styles.textMicro, styles.fontColorReactionLabel]}>
                    {String(userDetails.login || '').trim() && !_.isEqual(userDetails.login, userDetails.displayName) && !Str.isSMSLogin(userDetails.login) ? Str.removeSMSDomain(userDetails.login) : ''}
                </Text>

``
if `login` and `displayName` is the same we do not display the second text in

we check this by this line of code
```js
String(userDetails.login || '').trim() && !_.isEqual(userDetails.login, userDetails.displayName) && !Str.isSMSLogin(userDetails.login)
```

1. When user sign up with with there phone number we save the `displayName` same as the phone number and login id append with SMS domain `"+phoneNumber@expensify.sms"`
2. For the phone number case our condition failed to check `login` and `displayName` is same and we display same number twice








### What changes do you think we should make in order to solve the problem?
We can fix it by modifying our condition 

from: 
```js
{String(userDetails.login || '').trim() && !_.isEqual(userDetails.login, userDetails.displayName) && !Str.isSMSLogin(userDetails.login)}
```


to like this:

```js
{String(userDetails.login || '').trim() && !_.isEqual(userDetails.login, userDetails.displayName) ? Str.removeSMSDomain(userDetails.login) : ''}
```

<details>

<summary> Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by Tushu17** [comment] 2023-06-21 14:31
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
Phone number is shown twice in tooltip on user with no name.
### What is the root cause of that problem?
In the `UserDetailsTooltip` component, we are currently checking whether `userDetails.login` is equal to `userDetails.displayName` in order to determine if the user has a display name or not. This approach works correctly for accounts that use email as the login method. However, for phone number accounts, the `userDetails.displayName` string differs from the `userDetails.login` string.
https://github.com/Expensify/App/blob/0b7455fa832b53eccb99ca23c70e131b3464fb1d/src/components/UserDetailsTooltip/index.js#L31
### What changes do you think we should make in order to solve the problem?
We can check if user has a empty `userDetails.firstName` and `userDetails.lastName` instead of checking `userDetails.displayName`

`{String(userDetails.login).trim() && _.isEmpty(userDetails.firstName) && _.isEmpty(userDetails.lastName) ? '' : Str.removeSMSDomain(userDetails.login)}`
### What alternative solutions did you explore? (Optional)
Na

**Comment by conorpendergrast** [comment] 2023-06-22 08:39
Reproduced on OSX desktop app too. Thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-06-22 19:21
@manjesh-yadav [proposal](https://github.com/Expensify/App/issues/21197#issuecomment-1600911946) looks straightforward and good to me! 

But we should discuss something here, one number is with country code one is without in some cases. We should show the number consistently let's discuss this once CME jump's in thanks!

🎀 👀 🎀 
C+ Reviewed

Other Proposals are kind of redundant to the original proposals or slightly over-engineered.
cc: @conorpendergrast

**Comment by Nikhil-Vats** [comment] 2023-06-22 20:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Phone number is shown twice in the preview tooltip.
### What is the root cause of that problem?
In line 31 below, we show the third text (user login - email/phone number) only if `displayName` and `login` are different.
https://github.com/Expensify/App/blob/9bef5074ae858e7efb0d757473409ef099dac309/src/components/UserDetailsTooltip/index.js#L30-L32

`!_.isEqual(userDetails.login, userDetails.displayName)` returns `true` for phone numbers without `displayName` set because -
1. `login` contains `@expensify.sms` at end. 
2. Also `displayName` is localized while `login` is not. So, for numbers within the same region, `displayName` doesn't contain the country code while `login` does. 

Ex - `displayName` will be `09999111122` while login will be `+919999111122@expensify.sms` so even if we remove SMS domain, they will be different.

### What changes do you think we should make in order to solve the problem?
We should do the following changes -
1. Make a function to get number in e164 format from national number and region code like -
    ```javascript
    function convertLocalizedPhoneNumberToE164(number) {
        if (!number) {
            return '';
        }
    
        const numberWithoutSMSDomain = Str.removeSMSDomain(number);
        const parsedPhoneNumber = parsePhoneNumber(numberWithoutSMSDomain, {regionCode: getRegionCodeForCountryCode(countryCodeByIP)}); 
        // countryCodeByIP is a local variable and getRegionCodeForCountryCode is a function from the 'awesome-phonenumber' library that is already imported
    
        // return the string untouched if it's not a phone number
        if (!parsedPhoneNumber.valid) {
            if (parsedPhoneNumber.number && parsedPhoneNumber.number.e164) {
                return parsedPhoneNumber.number.e164;
            }
            return numberWithoutSMSDomain;
        }
    
        return parsedPhoneNumber.number.e164;
    }
    ```
2. Then, we should make a utility function to compare displayName with login like so -
 a. Check if login is via number using `Str.isSMSLogin(login)` function.
 b. If it is, then use `Str.removeSMSDomain(login)` to get `login` in e164 format.
 c. Use the function created above to get `displayName` in e164 format. If `displayName` is not a number the function above will return the original `displayName` only. We can also add an additional check for this.
 d. If `login` is not a number then we can simply use `_.isEqual(login, displayName)` function.
 e. Then if `login` and `displayName` are not equal we return `Str.removeSMSDomain(login)` otherwise `''`.
```javascript
function getLoginText(login, displayName) {
    if (_.isEmpty(login)) return '';
    const isSMSLogin = Str.isSMSLogin(login);
    let isLoginAndDisplayNameEqual = false;

    if (isSMSLogin) {
        isLoginAndDisplayNameEqual = _.isEqual(Str.removeSMSDomain(login), LocalePhoneNumberUtils. convertLocalizedPhoneNumberToE164(displayName));
    } else {
        isLoginAndDisplayNameEqual = _.isEqual(login, displayName);
    }

    return !isLoginAndDisplayNameEqual ? Str.removeSMSDomain(login) : '';
}
```
We can further improve the names of the variables and the function.

### What alternative solutions did you explore? (Optional)
NA

Result -

https://github.com/Expensify/App/assets/31413407/591fd807-7cb5-4cc6-bb95-c3c224aadd4d

**Comment by Nikhil-Vats** [comment] 2023-06-22 21:03
@Santhosh-Sellavel @manjesh-yadav's proposal will create a regression since the new condition -
```javascript
{String(userDetails.login || '').trim() && !_.isEqual(userDetails.login, userDetails.displayName) && !Str.isSMSLogin(userDetails.login) ? Str.removeSMSDomain(userDetails.login) : ''}
```

If `login` is a number then `!Str.isSMSLogin(userDetails.login)` will return `false` so even if `displayName` is set and is different from `login` then `login` will not be shown. So for phone numbers, `login` will never be shown regardless of `displayName`.

**Comment by conorpendergrast** [comment] 2023-06-26 10:34
Waiting for @mountiny's review here

**Comment by conorpendergrast** [comment] 2023-06-29 10:48
Ah, Vit is OoO this week! Reassigning

**Comment by conorpendergrast** [comment] 2023-06-29 10:49
@Li357 Welcome! Waiting for an engineering review of the proposal https://github.com/Expensify/App/issues/21197#issuecomment-1603195212

**Comment by Li357** [comment] 2023-06-29 15:46
@manjesh-yadav Proposal looks good!

**Comment by manjesh-yadav** [comment] 2023-06-29 19:18
@Santhosh-Sellavel  PR is ready for review.
https://github.com/Expensify/App/pull/21893

cc @conorpendergrast

**Comment by conorpendergrast** [comment] 2023-07-14 14:08
@manjesh-yadav @Tushu17 Please [apply to the job via Upwork](https://www.upwork.com/jobs/~011baa54223aee0feb)! 

@Santhosh-Sellavel Looks like you'll send a ND request 👍

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 21:20
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/20276
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20276/files#r1264182812
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This could be have been caught in testing.
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. Yes
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [ ]  [@conorpendergrast] Link the GH issue for creating/updating the regression test once the above steps have been agreed upon:

@Li357 Let me know if you differ from any of the above

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 21:21
**Bug:**  Login is shown twice in the user details tooltip

Steps from PR looks great!

### Regression Test Steps
1. Opened Expensify on a desktop browser or application.
2. Hovered over the account without a name that register with a phone number.
3. Hovered over the account with a name that register with a phone number.
4. Hovered over the account without a name that register with an email.
5. Hovered over the account with a name that register with an email.
6. Verify that in every step you did not see the email or phone number twice in the tooltip.

👍 or 👎

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 21:48
Requested payment on ND

**Comment by conorpendergrast** [comment] 2023-07-17 16:49
Contract sent to @manjesh-yadav, waiting for @Tushu17 to apply [to the job](https://www.upwork.com/ab/applicants/1671800200350584832/job-details).

**Comment by conorpendergrast** [comment] 2023-07-17 16:52
QA test request here: https://github.com/Expensify/Expensify/issues/300411

**Comment by conorpendergrast** [comment] 2023-07-17 16:53
Paid @manjesh-yadav!

**Comment by Tushu17** [comment] 2023-07-17 17:03
> Contract sent to @manjesh-yadav, waiting for @Tushu17 to apply [to the job](https://www.upwork.com/ab/applicants/1671800200350584832/job-details).

@conorpendergrast I'm not able to access the job posting, Ig you haven't shared the correct link. Can you just send me an invitation to my Upwork ID? https://www.upwork.com/freelancers/~01d43dd6772957dbb0

**Comment by Santhosh-Sellavel** [comment] 2023-07-17 17:08
@Tushu17 [here](https://github.com/Expensify/App/issues/21197#issuecomment-1635918792) is the link provided earlier it works for me

https://www.upwork.com/jobs/~011baa54223aee0feb

**Comment by Tushu17** [comment] 2023-07-17 17:14
Thank you, @Santhosh-Sellavel. @conorpendergrast I've applied for the job.

**Comment by conorpendergrast** [comment] 2023-07-17 19:59
Sorry, there are so many "fun" URLs in Upwork. I've sent the offer now!

**Comment by Tushu17** [comment] 2023-07-17 22:46
@conorpendergrast I've accepted the offer. Thank you.

**Comment by conorpendergrast** [comment] 2023-07-18 18:49
Nice, thanks. All done

**Closed by conorpendergrast** 2023-07-18 18:49 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
