### ISSUE TITLE
WS – Unable to invite a new user to the WS.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37970] opened 2024-03-08 13:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4407731
**Email or phone of affected tester (no customers):** ponikarchuks+138324@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go to settings/WS/Members
4. Click on Invite member button and add a new expensifail accoount

## Expected Result:
New user is invited

## Actual Result:
Unable to invite a new user to the WS. Error appears and user disappears from the list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/cba26d87-5721-4422-a9e7-b2a70d631b8a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161517fef7abe3bc3</li>
        <li>Upwork Job ID: 1767131506125549568</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by srikarparsi** [comment] 2024-03-08 19:24
Hi, I'm not able to reproduce this. @JmillsExpensify do you think you can check if it works for you. If not, I believe we can close this out.

https://github.com/Expensify/App/assets/48188732/3397721f-e496-487c-9c3d-0a45f3567def

**Comment by izarutskaya** [comment] 2024-03-08 21:29
Still reproducible 
But only when you add a new account, not existing.
Thank you

https://github.com/Expensify/App/assets/115492554/cff4e34c-dc61-438b-90ef-c7cf1326d656

**Comment by srikarparsi** [comment] 2024-03-09 02:04
Ah got it thank you, taking a look

**Comment by srikarparsi** [comment] 2024-03-09 02:35
https://github.com/Expensify/App/assets/48188732/568fd139-28e9-4fbe-88c9-916f492bec3a

Hm, I'm still not able to reproduce this

**Comment by srikarparsi** [comment] 2024-03-09 02:42
Still not able to reproduce with a new workspace.

https://github.com/Expensify/App/assets/48188732/ebda3fa1-71ab-4314-93ca-a13acd6adeaf

@izarutskaya do you think you could take a screenshot of your console if you reproduce. Specifically, the AddMembersToWorkspace command in the Network tab?

**Comment by izarutskaya** [comment] 2024-03-09 19:26
@srikarparsi still reproducible for me 
build v1.4.49-3
Check please my video, is it correct tab? Thanks

![Screenshot 2024-03-09 211928](https://github.com/Expensify/App/assets/115492554/a6295de5-da6a-4aae-8b46-f8e89ea67721)

https://github.com/Expensify/App/assets/115492554/0a6d6f53-959d-49fb-8dcd-72db6c4969c3

**Comment by srikarparsi** [comment] 2024-03-11 08:49
Hm, interestingly I'm still not able to reproduce this. @JmillsExpensify do you think you could check if this is happening for you if you get a chance?

**Comment by mountiny** [comment] 2024-03-11 10:12
Here are the [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228612e5c008812481-KBP%22)+AND+timestamp:[2024-03-08T11:41:05.465Z+TO+2024-03-08T13:41:05.465Z]&index=logs_expensify-027189) for the QA testers.

The error is `404 Account not found` which we throw [here](https://github.com/Expensify/Auth/blob/ffe65fb35947613eedb81cabbee971708dfbbea4/auth/command/GetRestrictedAuthToken.cpp#L134-L136) eventually.

Its not clear to me why is that for this account and I think we have to investigate it ad fix it, but its not App deploy blocker so demoting

**Comment by srikarparsi** [comment] 2024-03-19 04:26
Haven't gotten to this yet. I'll try to look at this on Wednesday.

**Comment by srikarparsi** [comment] 2024-03-27 01:07
Demoting this to a weekly, this bug seems to be account-specific since I'm not able to reproduce it but it's occurring for the QA tester.

**Comment by srikarparsi** [comment] 2024-04-10 02:37
No update yet.

**Comment by JmillsExpensify** [comment] 2024-04-24 05:42
Same as above.

**Comment by brunovjk** [comment] 2024-04-25 12:16
I can no longer reproduce on the latest main 🙂 **v1.4.65-5 (04/25)**
Can we check please? Thanks.

https://github.com/Expensify/App/issues/40301#issuecomment-2075543273: _"I think this should have been fixed in https://github.com/Expensify/Web-Expensify/pull/41771"_

**Comment by brunovjk** [comment] 2024-04-25 18:36
I can no longer reproduce.

_"I think this should have been fixed in https://github.com/Expensify/Web-Expensify/pull/41771"_

**Comment by srikarparsi** [comment] 2024-04-25 21:59
I'm not able to reproduce either. @izarutskaya is this reproducible for you still?

**Comment by srikarparsi** [comment] 2024-05-09 04:13
Bump @izarutskaya

**Comment by srikarparsi** [comment] 2024-05-16 21:09
Closing this out because I am not able to reproduce. But if anyone is, please reopen and I can look at the logs of the reproducible request.

**Comment by JmillsExpensify** [comment] 2024-05-19 18:07
Closing this out per the comment above.

**Closed by JmillsExpensify** 2024-05-19 18:07 UTC
Labels: Engineering, Weekly, Internal, Bug
