### ISSUE TITLE
[$500] Android-Room-Enter multi-line description, shows dots in header below title

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36015] opened 2024-02-07 12:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37 -0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a room chat
3. Tap header
4. Tap room description
5. Enter a multi-line message, in that enter first line message as 1 or 2 character( eg: 4,y, fg, 23)
6. Tap back button
7. Note room chat header

## Expected Result:
When we enter multi-line room description with first line message as 1 or 2 character, only dots must not be shown in header below title.

## Actual Result:
When we enter multi-line room description with first line message as 1 or 2 character, only dots shown in header below title.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e5f24783-bf48-4baf-a5ad-e0d4a65d44e8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115b48f34c4193ce8</li>
        <li>Upwork Job ID: 1755210340633886720</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-07 12:42
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by stephanieelliott** [comment] 2024-02-09 19:48
Hey @fedirjh we have a proposal here, can you review when you get a sec?

**Comment by dragnoir** [comment] 2024-02-12 17:19
Not able to reproduce this, even on Android.

**Comment by stephanieelliott** [comment] 2024-02-14 07:44
Yeah this feels like expected behavior to me also. Given that this does not fit in with a product wave,  I am gonna close this

**Closed by stephanieelliott** 2024-02-14 07:44 UTC
Labels: External, Daily, Help Wanted, Bug
