### ISSUE TITLE
Web - IOU - Unable to create request with large image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40569] opened 2024-04-19 13:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+gm164@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to any chat
2. Start creating manual request> On confirmation page on 3-dot menu Add receipt larger than 10 mb
3. Complete the request flow

## Expected Result:
Request should be created and not error message should appear

## Actual Result:
"Unexpected error creating this chat" error shows up when add large receipt image (10mb) and request disappear when dismiss the error
On the other hand, I can successfully replace other receipts with image bigger than 10mb

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bad5b844-8c01-4fda-8420-62ecb0811a4d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142d321c9ec7d5a4a</li>
        <li>Upwork Job ID: 1783460704301268992</li>
        <li>Last Price Increase: 2024-04-25</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-19 13:52
@laurenreidexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-19 13:53
We think that this bug might be related to #vip-vsp

**Comment by laurenreidexpensify** [comment] 2024-04-22 11:33
@quinthar this feels like a polish ?

**Comment by laurenreidexpensify** [comment] 2024-04-25 11:39
@mollfpr can you confirm if this is BE?

**Comment by mollfpr** [comment] 2024-04-29 05:52
@laurenreidexpensify Yes, this is a BE issue, but I can't confirm what the issue is.

![Screenshot 2024-04-29 at 12 51 51](https://github.com/Expensify/App/assets/25520267/f00cea1d-8866-4a96-be68-8f838b602624)

**Comment by laurenreidexpensify** [comment] 2024-05-02 10:29
waiting for internal eng

**Comment by laurenreidexpensify** [comment] 2024-05-07 07:50
waiting for internal eng

**Comment by laurenreidexpensify** [comment] 2024-05-10 06:21
waiting for internal eng

**Comment by laurenreidexpensify** [comment] 2024-05-13 11:10
waiting for internal eng

**Comment by laurenreidexpensify** [comment] 2024-05-16 08:46
waiting for internal eng

**Comment by laurenreidexpensify** [comment] 2024-05-20 09:03
waiting for internal eng

**Comment by laurenreidexpensify** [comment] 2024-05-28 09:45
waiting for internal eng

**Comment by laurenreidexpensify** [comment] 2024-06-07 13:10
Waiting on internal eng

**Comment by laurenreidexpensify** [comment] 2024-06-10 11:09
Waiting on internal eng

**Comment by anmurali** [comment] 2024-07-08 20:00
I actually cannot reproduce this in staging any longer. Am closing it.

**Closed by anmurali** 2024-07-08 20:00 UTC
Labels: Weekly, Internal, Overdue, Bug
