### ISSUE TITLE
[$250] Workspace - Toggle btn changed to green but the dot oriented incorrectly in WS settings

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47637] opened 2024-08-19 15:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4864753&group_by=cases:section_id&group_id=316342&group_order=asc
**Email or phone of affected tester (no customers):** applausetester+omco4@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: create Control workspace in OD
1. Sign in with the same account in ND
2. Navigate to Settings > Control Workspace > More features
3. Enable "Report Fields" option
4. Navigate to Report Fields settings page
5. Add field with any name and Text type
6. Set any Initial value for the text field and tap on "Save" button
7. Navigate to "More Features" page
8. Disable "Report Fields" toggle button
9. In OD update with any new text the initial value for created Text field
10. Observe the "Report Fields" toggle button status

## Expected Result:
"Report Fields" button should be be displayed green color and toggle on state should be enabled

## Actual Result:
"Report Fields" buttons changed color to green, but toggle button state remains disabled (the the dot inside the button is oriented incorrectly)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/91514fd0-a4a9-4768-a15c-18a04e11ad84

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014197c427158deea5</li>
        <li>Upwork Job ID: 1825967658437935245</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103803779</li>
<li>FitseTLT | Contributor | 103803780</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by lanitochka17** [comment] 2024-08-19 15:12
We think that this bug might be related to #wave-control

**Comment by lanitochka17** [comment] 2024-08-19 15:13
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-08-20 19:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tags settings –Tags not appears in the LHP of the workspace settings if added in OldDot
and `Warning: Maximum update depth exceeded` loop bug occurs
### What is the root cause of that problem?
The root cause is when the report field enabling comes from OD `enabledItem` is set to the reportField item so `highlighted` will be true for the reportField item 
https://github.com/Expensify/App/blob/d4d5a2586910ff46147219ee3e98bb3e936f8037/src/pages/workspace/WorkspaceInitialPage.tsx#L433-L434
But the problem is `shouldHighlight` will be fixed to be true in `useAnimatedHighlightStyle` which will set `startHighlight`
https://github.com/Expensify/App/blob/d4d5a2586910ff46147219ee3e98bb3e936f8037/src/hooks/useAnimatedHighlightStyle/index.ts#L68-L69
and that will in turn run this effect
https://github.com/Expensify/App/blob/d4d5a2586910ff46147219ee3e98bb3e936f8037/src/hooks/useAnimatedHighlightStyle/index.ts#L75-L76
which will set it to false so we will get into a loop and `Warning: Maximum update depth exceeded` occurs.
### What changes do you think we should make in order to solve the problem?

The starting of the highlight should only be triggered on `shouldHighlight` change not be triggered continously if it is true  which will cause a loop as in this current issue. 
So we need to change 
https://github.com/Expensify/App/blob/d4d5a2586910ff46147219ee3e98bb3e936f8037/src/hooks/useAnimatedHighlightStyle/index.ts#L69-L70
```
    }, [shouldHighlight]);

```
### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2024-08-26 18:29
@FitseTLT Thank you for your proposal. You solution is fixing `Maximum update depth exceeded` error but toggle is not getting enabled. 

There is just a lot of issue going on here. For example when there is a change in old dot, `Report fields` toggle is getting enabled but it is not getting added to workspace menu. Moreover the same happening after some changes in old dot, the `Report fields` is not appearing in the menu after enabling it using toggle

**Comment by FitseTLT** [comment] 2024-08-26 18:46
> @FitseTLT Thank you for your proposal. You solution is fixing `Maximum update depth exceeded` error but toggle is not getting enabled.
> 
> There is just a lot of issue going on here. For example when there is a change in old dot, `Report fields` toggle is getting enabled but it is not getting added to workspace menu. Moreover the same happening after some changes in old dot, the `Report fields` is not appearing in the menu after enabling it using toggle

I don't understand @alitoshmatov Everything is working fine for me:

https://github.com/user-attachments/assets/a35a96cd-65c6-4e62-ba3a-2fe6e24c7b19

**Comment by puneetlath** [comment] 2024-08-30 20:21
@alitoshmatov any thoughts?

**Comment by alitoshmatov** [comment] 2024-09-03 17:43
Sorry for late response, @FitseTLT I remember having some issues back then but now everything is working correctly after applying your solution maybe messed up something last time.

**Comment by alitoshmatov** [comment] 2024-09-03 17:44
We can go with @FitseTLT 's [proposal](https://github.com/Expensify/App/issues/47637#issuecomment-2299643355)

C+ reviewed 🎀 👀 🎀

**Comment by FitseTLT** [comment] 2024-10-03 12:06
@puneetlath payment overdue here

**Comment by alitoshmatov** [comment] 2024-10-06 10:00
This issue eroded to monthly issue. The pr went into [production](https://github.com/Expensify/App/pull/48601#issuecomment-2362374923) on 20th of september.

**Comment by puneetlath** [comment] 2024-10-09 15:54
All paid. Sorry for the delay.

**Closed by puneetlath** 2024-10-09 15:54 UTC
Labels: Reviewing, External, Monthly, Bug
