### ISSUE TITLE
[Details revamp] No option to cancel payment for paid expense as 3-dot menu is removed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45077] opened 2024-07-09 13:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Admin and employee are in the same workspace
- Workspace is connected to bank account
- Employee has personal bank account

1. Go to staging.new.expensify.com
2. [Employee] Go to workspace chat and submit an expense
3. [Admin] Go to the expense report from employee
4. [Admin] Pay the expense with Expensify
5. [Admin] On expense report, click on the report header

## Expected Result:
There should be an option to cancel payment. On prod, cancel payment option is accessible from 3-dot menu

## Actual Result:
There is no option to cancel payment for paid expense as 3-dot menu is removed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9f19c210-a7a1-4cd0-9a2a-a8bde5d57a94

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-09 14:00
@Gonals  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-09 14:00
We think that this bug might be related to #wave-collect - Release 1

**Comment by cdOut** [comment] 2024-07-09 14:08
This was caused by the [PR I worked on](https://github.com/Expensify/App/pull/44025) from the Details Revamp that removed the 3-dot menu, it must've been something that we overlooked while testing during the removal. I will create a PR that re-adds this feature into the Details page.

**Comment by cdOut** [comment] 2024-07-09 14:32
@parasharrajat I've looked back and no, this button was never considered in the design doc nor was it included anywhere in the issue descriptions / discussion threads that we did. We have added others for deleting, booking a call etc. but this one was missed during considerations.

**Comment by cdOut** [comment] 2024-07-09 14:32
I'll focus on getting a PR up for this one as soon as possible.

**Comment by Gonals** [comment] 2024-07-09 21:51
@cdOut, how is this going?

**Comment by cdOut** [comment] 2024-07-09 23:19
@Gonals I've created a PR for it and moved it to review.

**Comment by mountiny** [comment] 2024-07-10 10:23
https://github.com/Expensify/App/pull/45130#issuecomment-2220119935 QA worked well in staging

**Comment by cdOut** [comment] 2024-07-29 09:55
Can we close out this issue as the PR for it has been merged?

**Comment by trjExpensify** [comment] 2024-07-29 13:33
Payment summary as follows: 

- $250 to @allroundexperts for the PR review

Feel free to request, closing!

**Closed by trjExpensify** 2024-07-29 13:33 UTC
Labels: Reviewing, Engineering, Weekly
