### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Mweb – Assign Task – Mention options hides behind header.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22930] opened 2023-07-15 10:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any " Assign Task " chat.
2. Type “@” in composer, so that options appear.
3. Notice that the first option hides behind header.

## Expected Result:
 Options should not hide, infect adjust itself according to the space.

## Actual Result:
Mention options hide behind header

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6c3fef5e-fcd6-4d47-abbb-df786eef0fb1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689313870564749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0132b9832a42192981</li>
        <li>Upwork Job ID: 1681653446268710912</li>
        <li>Last Price Increase: 2023-08-02</li>
    </ul>
</details>

**Comment by jahnical** [comment] 2023-07-19 15:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mention Options hide behind header in Task reporting page when you use @ to tag someone. 

### What is the root cause of that problem?
The `MentionSuggestions` is not cutting off items "yet" but it's being hidden by the Header because its z-index (Depth in the z axis which determines which element is in front of the other) is lower than that of the header, Making it overlapped by the header component. This problem can also happen on a larger screen when the suggestions are many.

### What changes do you think we should make in order to solve the problem?

It's a matter of changing the styling by making the z-index of `MentionSuggestions` larger than the Header and also give it maximum height make it to scroll on overflow instead of hiding other suggestions.

### What alternative solutions did you explore? (Optional)
Other alternatives could be making the `MentionSuggestions` a modal so that it always overshadows the other elements.

**Comment by jahnical** [comment] 2023-07-19 15:45
Contributor details
Your Expensify account email: jahnics1@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0172473540122a1271

**Comment by kevinksullivan** [comment] 2023-07-24 14:55
Hey @aimane-chnaif , have you been able to review the proposals above?

**Comment by kevinksullivan** [comment] 2023-07-28 22:46
Recruiting a new C+. @robertKozik can you review the proposals above?

**Comment by robertKozik** [comment] 2023-07-31 09:44
Hey all! Will look into this issue shortly!

**Comment by kevinksullivan** [comment] 2023-08-01 16:50
Thanks @robertKozik !

**Comment by robertKozik** [comment] 2023-08-02 07:35
Shortly was longer than I expected 😅 I've checked both of the proposals in action:

- @jahnical - the approach with z-index was not working for me. Could you please specify exactly on which component it has to be applied?
- @allroundexperts - your solution works like a charm, but it's causing a behavior change in FloatingMessageCounter. Even after applying your fix for not rendering it, the animation looks different as it's not sliding out from behind the bar (videos attached). If we can somehow tackle it, it would be a strong contender.

https://github.com/Expensify/App/assets/61146594/c5611d7d-a47e-4e01-8bdb-27c543d27c90

animaton after:

https://github.com/Expensify/App/assets/61146594/d3c05a23-4e96-41a5-a7ea-b50ed3a96c5a


Also, I was thinking about restricting the height of the mention options to always be below the header, even at the cost of fewer mentions being rendered at the time. It should solve the issue. Do you think it's possible?

**Comment by kevinksullivan** [comment] 2023-08-04 21:34
Proposals still in review

**Comment by kevinksullivan** [comment] 2023-08-04 21:36
@johncschuster I am going OOO for a week, so tapping you in to help out in the interim. Thanks!

**Comment by robertKozik** [comment] 2023-08-05 15:44
@allroundexperts @jahnical pinging you for addressing my review of your proposals

**Comment by robertKozik** [comment] 2023-08-07 11:42
Thanks @allroundexperts for this insight and updating the proposal. I think we can proceed with your updated proposal, as it no longer has the problem with animaton and it's not changing the already established behaviour of the mentions options.

Selected proposal: [Proposal](https://github.com/Expensify/App/issues/22930#issuecomment-1636786706)
Author of proposal: @allroundexperts 

🎀 👀 🎀 C+ reviewed

**Comment by johncschuster** [comment] 2023-08-09 20:36
Not overdue. This was just assigned out.

**Comment by johncschuster** [comment] 2023-08-21 21:57
No problem! Thanks, Kev!

**Comment by kevinksullivan** [comment] 2023-08-22 15:29
Awaiting review from @AndrewGable

**Comment by kevinksullivan** [comment] 2023-08-30 21:32
@allroundexperts @robertKozik please finish up the checklist above when you get a chance. Thanks!

**Comment by kevinksullivan** [comment] 2023-09-13 03:09
Upwork job expired so I created a new one and sent offers to @usmantariq96 and @allroundexperts . Lmk when you accept.

**Comment by kevinksullivan** [comment] 2023-09-13 03:10
Also, @allroundexperts please finish out the checklist above

**Comment by usmantariq96** [comment] 2023-09-13 03:19
@kevinksullivan accepted
Thanks

**Comment by kevinksullivan** [comment] 2023-09-14 16:40
Paid @usmantariq96 , waiting on @allroundexperts

**Comment by kevinksullivan** [comment] 2023-09-15 15:07
Payment summary:

- Reporter - @usmantariq96 $250 
- Contributor - @allroundexperts $1,000 (paid in newdot)

**Comment by kevinksullivan** [comment] 2023-09-15 15:07
@anmurali for newdot payment

**Comment by kevinksullivan** [comment] 2023-09-15 15:26
Anu doesn't do this, so looping in @JmillsExpensify

**Comment by kevinksullivan** [comment] 2023-09-21 06:23
Looks good to me, just waiting on @JmillsExpensify for payment

**Comment by kevinksullivan** [comment] 2023-09-27 04:24
closing issue, just waiting on jason

**Closed by kevinksullivan** 2023-09-27 04:24 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 12:54
$1,000 payment approved for @allroundexperts based on BZ summary.
