### ISSUE TITLE
[$250] Android - Secondary Log in - An endless spinner when trying validate the secondary login

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11964] opened 2022-10-18 16:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to NewDot with any account
2. Log into OldDot with the same account and add a Secondary Login from Account Settings
3. Open validate secondary log in email Verify secondary email for Expensify and copy the last part of the URL, i.e. /v/16/WSSWMNNM (Everything after the /v/)
4. In a text box - Formulate the URL by using the path obtained from step 3 http://staging.new.expensify.com/v/
5. Navigate to the compiled link

## Expected Result:
You should redirected to LHN with no error message displayed

## Actual Result:
An endless spinner when trying validate the secondary login

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** v1.2.17-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196486373-783326ea-e485-4c84-8db4-43078c1d7b6c.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment] 2022-10-18 17:03
Weird, where did we get these reproduction steps from? Do we support validating a secondary login on NewDot?

**Comment by kavimuru** [comment] 2022-10-20 23:11
@neil-marcellini This is from the regression steps https://expensify.testrail.io/index.php?/tests/view/2893709&group_by=cases:section_id&group_order=asc&group_id=229043

**Comment by neil-marcellini** [comment] 2022-10-21 00:05
Okay got it thanks for clarifying. I'm able to reproduce the issue. I'm also able to reproduce the issue on iOS. I can't reproduce on Web so maybe it has something to do with the small screen width? I'll send it external because if it's limited to certain platforms then it's probably a front end issue.

https://user-images.githubusercontent.com/26260477/197080855-aed861a4-3531-40f7-b8b5-2008781e7e68.mov

**Comment by davidcardoza** [comment] 2022-10-23 23:09
I can't reproduce the issue on iOS or web. This error seems to be isolated to Android only.

**Comment by tgolen** [comment] 2022-10-26 13:17
Waitng for proposals

**Comment by wildan-m** [comment] 2022-10-28 09:07
### Proposal (Updated)

@thesahindia, you are right, I can also reproduce it in Safari.

I still believe that it's caused by the different triple-click behavior of browsers
At this time, behavior of default action of triple-click isn't specified the W3C spec
Other repos also experience similar issues:
https://github.com/facebook/lexical/issues/2660
https://github.com/ckeditor/ckeditor4/issues/484
https://github.com/ckeditor/ckeditor4/issues/3118

I've resolved glitches in my previous solution by changing the `onClick` event to `onMouseDown` and adding preventDefault if the subsequent click is more than two.

https://github.com/Expensify/App/blob/73922083c9bc4f2b1f050406b6e3b24c6ba98fc7/src/pages/home/report/ReportActionItemMessage/index.web.js#L10-L40

These changes will be implemented for the web and desktop only.

Complete comparison:
https://github.com/Expensify/App/commit/73922083c9bc4f2b1f050406b6e3b24c6ba98fc7

No more flickering:

https://user-images.githubusercontent.com/11847279/198174311-e405f8b6-6ac9-4d6f-909c-0b350869832a.mp4

**Comment by wildan-m** [comment] 2022-10-29 07:52
### Proposal

### Root cause:
`<FullScreenLoadingIndicator />` is not dismissed before calling `Navigation.navigate(ROUTES.HOME);` in `validateLogin`

### Solution

Adding `Navigation.goBack();` before navigating to home will resolve the issue.

```diff
diff --git a/src/libs/actions/User.js b/src/libs/actions/User.js
index c1f11e3610..8d549fb099 100644
--- a/src/libs/actions/User.js
+++ b/src/libs/actions/User.js
@@ -220,6 +220,7 @@ function validateLogin(accountID, validateCode) {
         accountID,
         validateCode,
     }, {optimisticData});
+    Navigation.goBack();
     Navigation.navigate(ROUTES.HOME);
 }
```

Another solution is also to pop the navigation when the user logged in or logged out:
```diff
diff --git a/src/libs/Navigation/Navigation.js b/src/libs/Navigation/Navigation.js
index e937e50159..9bfd819e12 100644
--- a/src/libs/Navigation/Navigation.js
+++ b/src/libs/Navigation/Navigation.js
@@ -64,7 +64,6 @@ function openDrawer() {
     if (!canNavigate('openDrawer')) {
         return;
     }
-
     navigationRef.current.dispatch(DrawerActions.openDrawer());
     Keyboard.dismiss();
 }
@@ -140,15 +139,14 @@ function navigate(route = ROUTES.HOME) {
     }
 
     if (route === ROUTES.HOME) {
+        // If we're navigating to the signIn page, pop whatever screen is on top
+        // since it's guaranteed that the sign in page will be underneath (since it's the initial route).
+        // Also, if we're coming from a link to validate login (pendingRoute is not null), we want to pop the loading screen.
+        navigationRef.current.dispatch(StackActions.pop());
         if (isLoggedIn && pendingRoute === null) {
             openDrawer();
             return;
         }
-
-        // If we're navigating to the signIn page while logged out, pop whatever screen is on top
-        // since it's guaranteed that the sign in page will be underneath (since it's the initial route).
-        // Also, if we're coming from a link to validate login (pendingRoute is not null), we want to pop the loading screen.
-        navigationRef.current.dispatch(StackActions.pop());
         return;
     }
```

The second solution might affect another part since `Navigation.navigate(ROUTES.HOME)` is used in multiple places.

**Comment by eVoloshchak** [comment] 2022-10-31 16:25
@wildan-m, thanks for your proposal!

Moving `navigationRef.current.dispatch(StackActions.pop());` would result in it being called every time user is navigating back to root. 

Calling `Navigation.goBack()` in [validateLogin](https://github.com/Expensify/App/blob/388760bbac17c14c6efd96fd595d66db9da8d6e1/src/libs/actions/User.js#L210) would actually work. But this feels like a workaround.

The proposal should answer the question of _why_ is this happening?
Why [ValidateLoginPage](https://github.com/Expensify/App/blob/main/src/pages/ValidateLoginPage.js) is displayed on top, even when navigating away from it?

**Comment by tgolen** [comment] 2022-11-03 21:09
Still working on proposals above. Bump @wildan-m for the questions in the previous comment.

**Comment by wildan-m** [comment] 2022-11-04 15:08
### Proposal (Updated)

### Root Cause
`ValidateLoginPage` and `MainDrawer` is `<RootStack.Navigator>` screen and `Navigation.navigate(ROUTES.HOME)` is directly open the drawer when the user is logged in:

https://github.com/Expensify/App/blob/a2eda4d48f8ab94912af0f9af90bb75c8359f1e8/src/libs/Navigation/Navigation.js#L142-L147

I think we can't directly trigger `openDrawer` when the parent navigator is a Stack navigator

I've tried it here:
https://snack.expo.dev/@muhliswildan/nesting-navigators-%7C-react-navigation

### Solution

We can replace the dispatch with  `navigationRef.current.dispatch(StackActions.replace(SCREENS.HOME))` if it comes from `ValidateLogin` page.


```diff
git diff src/libs/Navigation/Navigation.js
diff --git a/src/libs/Navigation/Navigation.js b/src/libs/Navigation/Navigation.js
index e937e50159..dbe4665bda 100644
--- a/src/libs/Navigation/Navigation.js
+++ b/src/libs/Navigation/Navigation.js
@@ -6,6 +6,7 @@ import Onyx from 'react-native-onyx';
 import Log from '../Log';
 import linkTo from './linkTo';
 import ROUTES from '../../ROUTES';
+import SCREENS from '../../SCREENS';
 import DeprecatedCustomActions from './DeprecatedCustomActions';
 import ONYXKEYS from '../../ONYXKEYS';
 import linkingConfig from './linkingConfig';
@@ -141,6 +142,11 @@ function navigate(route = ROUTES.HOME) {
 
     if (route === ROUTES.HOME) {
         if (isLoggedIn && pendingRoute === null) {
+            if(navigationRef.current?.getCurrentRoute()?.name === "ValidateLogin")
+            {
+                navigationRef.current.dispatch(StackActions.replace(SCREENS.HOME));
+                return;
+            }
             openDrawer();
             return;
         }
```

cc: @eVoloshchak @tgolen

**Comment by tgolen** [comment] 2022-11-07 15:24
Thanks for the updated proposal.

> ValidateLoginPage and MainDrawer is <RootStack.Navigator> screen and Navigation.navigate(ROUTES.HOME) is directly open the drawer when the user is logged in:

Sorry, I'm not really following this. It kind of looks like words are missing or the grammar is wrong enough that I'm not understanding the reason. Can you try to reword this, please?

> I think we can't directly trigger openDrawer when the parent navigator is a Stack navigator

This sounds like a good guess, but let's make _sure_ that's the problem. Also, if this is indeed the root cause of the problem, can the fix be something that looks at the parent navigator to see if it's a stack navigator or not? I don't like how the proposal only references the `ValidateLogin` route, since it sounds like it could apply to any route where the parent navigator is a stack navigator.

**Comment by wildan-m** [comment] 2022-11-07 23:49
### Proposal (Updated)

@tgolen 
> Sorry, I'm not really following this. It kind of looks like words are missing or the grammar is wrong enough that I'm not understanding the reason. Can you try to reword this, please?

Please have a look at this hierarchy

https://github.com/Expensify/App/blob/4f92e57bb4fa08339527f8082f207f81628492d8/src/libs/Navigation/AppNavigator/AuthScreens.js#L162-L199

`MainDrawer` and `ValidateLogin` are `RootStack` navigator screens.

`ValidatLoginPage` will call this function

https://github.com/Expensify/App/blob/91acada3b65af8c465febe6853bcc7d37995f0f4/src/pages/ValidateLoginPage.js#L23

which will dispatch the screen with the home screen:
https://github.com/Expensify/App/blob/91acada3b65af8c465febe6853bcc7d37995f0f4/src/libs/actions/User.js#L226



But this `navigate` function directly opens the drawer

https://github.com/Expensify/App/blob/91acada3b65af8c465febe6853bcc7d37995f0f4/src/libs/Navigation/Navigation.js#L142-L146

Since `ValidateLoginPage` is a stack navigator screen and `MainDrawer` is a child of StackNavigator, `openDrawer` will not work. The `MainDrawer` is not loaded/stacked yet.

> can the fix be something that looks at the parent navigator to see if it's a stack navigator or not?

I've tweaked the code to include all of the root routes. Please have a look:

```diff
git diff src/libs/Navigation/Navigation.js
diff --git a/src/libs/Navigation/Navigation.js b/src/libs/Navigation/Navigation.js
index e937e50159..06e71d173c 100644
--- a/src/libs/Navigation/Navigation.js
+++ b/src/libs/Navigation/Navigation.js
@@ -6,6 +6,7 @@ import Onyx from 'react-native-onyx';
 import Log from '../Log';
 import linkTo from './linkTo';
 import ROUTES from '../../ROUTES';
+import SCREENS from '../../SCREENS';
 import DeprecatedCustomActions from './DeprecatedCustomActions';
 import ONYXKEYS from '../../ONYXKEYS';
 import linkingConfig from './linkingConfig';
@@ -141,6 +142,13 @@ function navigate(route = ROUTES.HOME) {
 
     if (route === ROUTES.HOME) {
         if (isLoggedIn && pendingRoute === null) {
+            const rootRoutes = navigationRef.current.getRootState().routeNames;
+            if(rootRoutes.indexOf(navigationRef.current.getCurrentRoute()?.name) !== -1)
+            {
+                navigationRef.current.dispatch(StackActions.popToTop(SCREENS.HOME));
+                Keyboard.dismiss();
+                return;
+            }
             openDrawer();
             return;
         }
```

**Comment by tgolen** [comment] 2022-11-08 14:17
Ah, great. Thank you for the more thorough proposal! I think the solution is looking better and I like how it's a bit more generalized now. I was talking with @marcaaron about this issue and he has a lot of knowledge about the navigators, so I think getting his perspective on this proposal would be ideal.

**Comment by marcaaron** [comment] 2022-11-08 21:29
Really appreciate the investigation here so far. However, since validating a secondary login has a workaround (can validate via OldDot) and since we are [actively discussing deprecating the use of the drawer navigator](https://expensify.slack.com/archives/C01GTK53T8Q/p1667940831213829). I'm not sure we should invest anymore time or energy into short term fixes that are difficult to understand and create a high barrier to entry for our internal engineers and contributors.

**Comment by eVoloshchak** [comment] 2022-11-11 16:08
Not overdue, the discussion is in progress on whether to use the drawer navigator

**Comment by eVoloshchak** [comment] 2022-11-14 14:27
Not overdue

**Comment by davidcardoza** [comment] 2022-11-14 16:20
Based on @marcaaron's latest assessment of the issue I think we are good to close this issue. If anyone disagrees please reopen the issue.

**Comment by kavimuru** [comment] 2023-02-17 13:02
@davidcardoza Issue is reproducible in Web, mWeb and Desktop as well. Are these navigation issues are on Hold now?

**Comment by davidcardoza** [comment] 2023-02-18 00:19
I'll lean on @marcaaron's expertise here because I am not sure if we're still actively looking to deprecate the use of the drawer navigator, which would potentially make this not a priority.

**Comment by tgolen** [comment] 2023-02-21 17:48
I'm pretty sure our plan is still to deprecate the drawer navigator. This is all being handled in https://github.com/Expensify/App/issues/11768 so I will keep this closed.

**Closed by tgolen** 2023-02-21 17:48 UTC
Labels: External, Engineering, Daily, Improvement, Help Wanted, Overdue, Bug
