### ISSUE TITLE
Web - Expense - Console error shows up when opening description field that has multiline text

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48063] opened 2024-08-27 09:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Copy a multiline text.
3. Go to DM.
4. Submit an expense with multiline description by pasting the text in Step 2.
5. Go to transaction thread.
6. Wait for a while.
7. Click on the description field.

## Expected Result:
No console error will show up.

## Actual Result:
Console error shows up when opening description field that contains multiline text.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f6e00233-530b-4435-95b4-20f3c4776441

[2708.txt](https://github.com/user-attachments/files/16760027/2708.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by IuliiaHerets** [comment] 2024-08-27 09:45
We think that this bug might be related to #wave-collect - Release 1

**Comment by pecanoro** [comment] 2024-08-27 10:38
I am going to remove the deploy blocker label since this is only an error console and it seems to be working. I am going to find the PR that caused it.

**Comment by pecanoro** [comment] 2024-08-27 14:01
I managed to reproduce it once, but not anymore, so I am wondering if this has been a thing for a while. It doesn't break anything and everything seems to be working even though a multiline comment is not allowed unless you copy and paste.

**Comment by pecanoro** [comment] 2024-08-27 14:01
@slafortune Can you see if you can reproduce it?

**Comment by slafortune** [comment] 2024-08-27 21:47
@pecanoro I'm having some internet issues, I'll have to test in the morning.

**Comment by slafortune** [comment] 2024-08-28 18:07
@pecanoro I was not able to recreate this error - not even once. 

<img width="982" alt="image" src="https://github.com/user-attachments/assets/1e0b7c76-f633-41a7-ae57-5a4a97c22a80">

**Comment by pecanoro** [comment] 2024-08-29 08:44
@slafortune Thank you! I am going to close it for now and if it happens again, then we can have someone take a look since it's super minor so I feel we can use the resources for some other issue.

**Closed by pecanoro** 2024-08-29 08:44 UTC
Labels: Engineering, Daily, Bug
