### ISSUE TITLE
[HOLD for payment 2024-11-01] [$250] TransitionOD-ND - When disabling tax in OD, ND "page not Found", "Back" takes to WS selection

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50465] opened 2024-10-08 18:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5053996
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open ND App
2. Create a WS
3. Log in as the same user in OD
4. In OD Click on Workspaces
5. Select the same WS as in ND
6. In OD go to WS settings and enable Tax
7. In ND go to WS settings, on LHP click on Tax icon
8.With Tax page open in ND, navigate to OD and disable Tax option

## Expected Result:
In ND the user is navigated to the LHP/WS editor page

## Actual Result:
The user is shown "Ops...It's not here" page, the "Back" button takes you back to the WS selection page(User leaves the WS editor page)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/f79895d5-f082-4c99-9529-3921efb87aa1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845793851841023680</li>
        <li>Upwork Job ID: 1845793851841023680</li>
        <li>Last Price Increase: 2024-10-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by lanitochka17** [comment] 2024-10-08 18:56
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-10-09 10:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Going back from not found tax page leads to workspace list page.

### What is the root cause of that problem?
When we disable the tax page, it's expected that a full screen not found page will show. The reason pressing back leads to the workspace list page is because a `Navigation.dismissModal` is called, which closes the workspace details page.

https://github.com/Expensify/App/blob/5d25b40eab1416d2d67624a376099853a2b6af86/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L88-L97

### What changes do you think we should make in order to solve the problem?

`shouldShowFullScreenFallback` is true if the feature is disabled or the policy is not accessible.
https://github.com/Expensify/App/blob/5d25b40eab1416d2d67624a376099853a2b6af86/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L169

I think we should only close the workspace detail page if the policy is not accessible. To do that, we need to pass both `isFeatureEnabled` and `isPolicyNotAccessible` to `PageNotFoundFallback` and remove the `shouldShowFullScreenFallback` props and instead, add it as a local variable in `PageNotFoundFallback`.

```
isFeatureEnabled={isFeatureEnabled}
isPolicyNotAccessible={isPolicyNotAccessible}
```

Then, in PageNotFoundCallback,
https://github.com/Expensify/App/blob/5d25b40eab1416d2d67624a376099853a2b6af86/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L88-L98

only use `dismissModal` if the policy is not accessible. If the feature is disabled, then we will just go back.

```
const shouldShowFullScreenFallback = !isFeatureEnabled || isPolicyNotAccessible;
onBackButtonPress={() => {
    if (isPolicyNotAccessible) {
        Navigation.dismissModal();
        return;
    }
    Navigation.goBack(policyID && !isMoneyRequest ? ROUTES.WORKSPACE_PROFILE.getRoute(policyID) : undefined);
}}
```

**Comment by mananjadhav** [comment] 2024-10-14 15:16
Got assigned today. Will review the proposal.

**Comment by mananjadhav** [comment] 2024-10-14 17:05
I think @bernhardoj's [proposal](https://github.com/Expensify/App/issues/50465#issuecomment-2401962916) looks good. We'll need to check if it exists for other pages such as "Tags", etc.

🎀 👀 🎀 C+ reviewed.

**Comment by bernhardoj** [comment] 2024-10-15 14:55
PR is ready
cc: @mananjadhav

**Comment by mananjadhav** [comment] 2024-10-15 17:08
Thanks, I'll review and test by tomorrow.

**Comment by mananjadhav** [comment] 2024-11-01 18:13
I tried to find an offending PR for this one but I couldn't. We refactored this code quite a bit but I think we should add a regression test for this.

@sonialiap Here's the regression test proposal and this one is ready for payout.

Prerequisite: logged in as the same user in 2 tabs/devices.

1. Open any workspace > More features > Enable taxes.
2. Open Taxes.
3. From the other devices, disable the taxes from the More features page.
4. Back to the first device, verify a not found page is shown.
5. Press the back button.
6. Verify you are navigated back to the WS settings page.

**Comment by bernhardoj** [comment] 2024-11-02 04:01
Requested in ND.

**Closed** 2024-11-04 10:13 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-11-04 10:49
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment] 2024-11-06 10:06
$250 approved for @mananjadhav
