### ISSUE TITLE
[HOLD for payment 2023-06-23] [$1000] Android/iOS - Chat - jpg image opens always with loading spinner in preview

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19920] opened 2023-05-31 23:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Go to any chat
4. Send a jpg image
5. Open the image you just sent in the preview

## Expected Result:
jpg image opens the first time with the loading spinner, but the next times without it

## Actual Result:
jpg image opens always with loading spinner

## Workaround:
Unkown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e721ec50-d21e-4e3f-96eb-5707770af77d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b826cfb93c10d6b</li>
        <li>Upwork Job ID: 1665390224439746560</li>
        <li>Last Price Increase: 2023-06-04</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-06-01 16:28
I was able to reproduce this consistently on both Android and iOS native apps, it's working fine on other platforms. Also, PDF works fine on native apps.

This may be a duplicate of https://github.com/Expensify/App/issues/19369, I've asked over there if it's the same root cause and if we should fix them together.

**Comment by sakluger** [comment] 2023-06-04 16:08
Sounds like this bug is unique from the other one, adding the external label. @jliexpensify I've also added you as another BZ team member to watch over this since I'm out all next week.

**Comment by bondydaa** [comment] 2023-06-05 17:27
@tienifr can you clarify this for me?

> We can remove that InteractionManager.runAfterInteractions logic and set isLoading to false directly after the image finishes loading. There

Are you saying remove all of the logic in `InteractionManager.runAfterInteractions`? or just removing the setting of the `isLoading` state from outside of the `runAfterInteractions`?

**Comment by s77rt** [comment] 2023-06-05 18:35
@tienifr Thanks for the proposal. Can you please explain why this happen on jpg images only? (or it does not?)

**Comment by s77rt** [comment] 2023-06-06 13:08
@tienifr Thanks! Your solution looks good to me, if the image is loaded we should set `isLoading` to `false` without further delay.  Based on the code comment we did this to prevent stutter, this was first added by https://github.com/Expensify/App/pull/6442. Can you please use the image in that PR (and others) to navigate through and confirm the animation is smooth?

I have also asked here for better reproduction steps here https://github.com/Expensify/App/pull/6442#discussion_r1219621596.

**Comment by s77rt** [comment] 2023-06-07 14:55
@tienifr There seems to be some lag. Can you please attach another video that keeps the `InteractionManager.runAfterInteractions` delay.

**Comment by s77rt** [comment] 2023-06-08 10:06
@tienifr I think we still have some lag in the second video as well. Do you see that?

**Comment by s77rt** [comment] 2023-06-08 11:13
@tienifr Since the lag is not a regression here we can move forward and handle the lag bug separately.

:ribbon: :eyes: :ribbon: C+ reviewed

cc @bondydaa

**Comment by jliexpensify** [comment] 2023-06-15 01:49
Invited @tienifr and @s77rt

**Comment by jliexpensify** [comment] 2023-06-15 03:19
Cool, good to know - cheers @tienifr . We'll add the 50% bonus then.

**Comment by sakluger** [comment] 2023-06-16 02:38
Sent offers to @tienifr and @s77rt in Upwork.

**Comment by sakluger** [comment] 2023-06-23 20:06
All paid, thanks everyone!

**Closed by sakluger** 2023-06-23 20:06 UTC
Labels: External, Daily, Awaiting Payment, Bug
