### ISSUE TITLE
[$250] Chat - Breadcrumbs shows Expensify instead of selected workspace after refreshing the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39936] opened 2024-04-09 13:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Click on the workspace switcher
3. Select another workspace
4. Refresh the page
5. Click on the workspace switcher

## Expected Result:
In Step 4, the breadcrumbs will show the selected workspace name because the workspace is still selected (Step 5)

## Actual Result:
In Step 4, the breadcrumbs shows Expensify instead of the selected workspace, when the workspace switcher is not reset (Step 5)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/112c4da8-17f3-41d9-a7da-8d56e9285dc9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176a1c6553749e06e</li>
        <li>Upwork Job ID: 1777701234737819648</li>
        <li>Last Price Increase: 2024-04-09</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-09 13:39
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-09 13:39
We think that this bug might be related to #vip-vsp

**Comment by twisterdotcom** [comment] 2024-04-09 14:12
Super easy to repro.

**Comment by godofoutcasts94** [comment] 2024-04-09 14:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Breadcrumbs shows Expensify instead of selected workspace after refreshing the page
### What is the root cause of that problem?
Over here :
https://github.com/Expensify/App/blob/792c6976fe8c3e667007259d64302b07f919c544/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx#L51-L60
when we refresh the page, the policy gets removed and it goes back to default breadcrumbs
### What changes do you think we should make in order to solve the problem?

We need to add a way to retain the policy, so that the breadcrumb doesn't go back to default breadcrumb.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by Skakruk** [comment] 2024-04-09 18:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - Breadcrumbs shows Expensify instead of selected workspace after refreshing the page

### What is the root cause of that problem?

The root cause is that React-navigation state is not ready on stage when we try to retrieve the `policyID` from rootState params.

### What changes do you think we should make in order to solve the problem?

It's better to utilize the `useRoute` hook from react-navigation, to retrieve policyID from route params. So it can be passed as `activeWorkspaceID` in `TopBar` component.

### What alternative solutions did you explore? (Optional)

We can use `useRoute()` hook directly in `BaseSidebarScreen` component or create own hook, with logic from `getPolicyIDFromState`

**Comment by ddipole** [comment] 2024-04-10 08:35
**Please re-state the problem that we are trying to solve in this issue.**
Chat - Breadcrumbs shows Expensify instead of selected workspace after refreshing the page

**What is the root cause of that problem?**
The root cause is that the Active Workplace is not getting the value after page is been refreshed.


**What changes do you think we should make in order to solve the problem?**
There is a hook useActiveWorkspace which contains all Active Workspace Details. We just need to import that hook and call useActiveWorkspace(); before useEffect to get the value of Active Workspace.
![image (64)](https://github.com/Expensify/App/assets/102144454/e541f172-c380-4c44-ac19-b05026ecb289)

**Comment by twisterdotcom** [comment] 2024-04-10 11:19
Great, thanks for highlighting that. Let's close this one.

**Comment by roryabraham** [comment] 2024-04-16 23:13
There's still a PR up for this so I'm going to reopen it and just remove the help wanted

**Comment by iwiznia** [comment] 2024-05-15 21:40
This PR caused this regression https://github.com/Expensify/App/issues/42190#issuecomment-2112679058

**Comment by twisterdotcom** [comment] 2024-05-29 13:33
What is happening here now? Are we waiting on a PR to be deployed?

**Closed** 2024-06-12 14:28 UTC
Labels: Reviewing, External, Weekly, Bug
