### ISSUE TITLE
[HOLD for payment 2023-10-02] [HOLD for payment 2023-09-29] [$500] Dev: Web - App crashing on creating new workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27782] opened 2023-09-19 13:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with new account
2. Click on FAB > New workspace
3. App crashes

## Expected Result:
App should not crash and workspace is created

## Actual Result:
 App crashes and a console error is present

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.71-6 
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fe180f55-16ed-4c86-9a48-299654e42742

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695116344613649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016db5c84825401ac4</li>
        <li>Upwork Job ID: 1704127946717769728</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-09-19 13:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web app crashing when creating new workspace from FAB.

### What is the root cause of that problem?
- `hideReactionList` is not defined.

### What changes do you think we should make in order to solve the problem?

- We can add a check to see if `hideReactionList` is defined before calling it.
https://github.com/Expensify/App/blob/778f7636c9b59f592193ffad892c0d2904bc84da/src/pages/home/report/ReportActionsView.js#L135-L140

```diff
- if (isFocused || !context.reactionListRef || !context.reactionListRef.current) {
+ if (isFocused || !context.reactionListRef || !context.reactionListRef.current || !context.reactionListRef.current.hideReactionList) {
    return;
}
```

### What alternative solutions did you explore? (Optional)
-

**Comment by Pujan92** [comment] 2023-09-19 15:17
Seems a regression from https://github.com/Expensify/App/pull/27268 as for me while navigating back from profile crashes the app
<img width="1440" alt="Screenshot 2023-09-19 at 20 46 28" src="https://github.com/Expensify/App/assets/14358475/845a9ed7-e7be-4907-a18b-ff637d357cd2">

**Comment by saranshbalyan-1234** [comment] 2023-09-19 17:34
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Web app crashing while creating a new workspace.
## What is the root cause of that problem?
useImperativeHandle is called in which hideReactionList is used which ultimately uses the ref passed to child component. This is called before rendering of the child component which results in error.
## What changes do you think we should make in order to solve the problem?
We need to return is the ref current is either undefined or null here
https://github.com/Expensify/App/blob/e18ec42511682c1379710b7622b55957aaca20a7/src/pages/home/report/ReactionList/PopoverReactionList/index.js#L32-L36
to this
```javascript
const hideReactionList = () => {
        if (!innerReactionListRef.current) return;
        innerReactionListRef.current.hideReactionList();
    };
```     
Also while using useImperativeHandle, we need to pass the dependency array with the arguments that are being used.
```javascript
    useImperativeHandle(props.innerRef, () => ({showReactionList, hideReactionList, isActiveReportAction}), [innerReactionListRef.current]);

``` 
## What alternative solutions did you explore? (Optional)
N/A

**Comment by ArekChr** [comment] 2023-09-20 08:20
We can close this issue. It has been fixed in https://github.com/Expensify/App/pull/27798

**Comment by mountiny** [comment] 2023-09-20 08:45
This isn now repro in production, merged the fix into main, going to ask for a CP

**Comment by techievivek** [comment] 2023-09-20 09:33
@mountiny I had added you to the issue since you have worked on it.

**Comment by mountiny** [comment] 2023-09-21 03:30
I think we can close as we reverted

**Comment by mountiny** [comment] 2023-09-21 09:43
@muttmuure can you please handle the payment on this one?

**Comment by mountiny** [comment] 2023-09-21 09:43
$50 to @aman-atg

**Comment by mountiny** [comment] 2023-10-04 11:59
@muttmuure Can you please handle the payment of $50 here and then we can close

**Comment by muttmuure** [comment] 2023-10-05 09:42
Invite sent to @aman-atg

**Comment by muttmuure** [comment] 2023-10-11 18:05
Handling

**Comment by muttmuure** [comment] 2023-10-11 18:09
Offer sent

**Comment by muttmuure** [comment] 2023-10-17 14:55
Paid!

**Closed by muttmuure** 2023-10-17 14:55 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment
