### ISSUE TITLE
Web - Attachment – Image is not displayed in chat history and preview

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50000] opened 2024-10-01 15:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** gocemate+a2354@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to any chat
2. Send an image
3. Wait for a while

## Expected Result:
Image should be displayed in chat history and when open preview

## Actual Result:
Image is not displayed in chat history and preview

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/514a6963-c8a6-4d2a-bd51-8b7b4ee4971a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2024-10-01 15:46
I think this was fixed with [this revert](https://github.com/Expensify/Salt/pull/13989)

**Comment by luacmartins** [comment] 2024-10-01 15:47
@IuliiaHerets can you please retest? We think this issue is fixed

**Comment by blimpich** [comment] 2024-10-01 16:45
Asked for retest in slack here: https://expensify.slack.com/archives/C9YU7BX5M/p1727801076828439

**Comment by m-natarajan** [comment] 2024-10-01 17:01
Unable to reproduce from my end. Waiting for tester's response who reported this issue.

https://github.com/user-attachments/assets/3a5e8249-aad1-416a-a751-734de39a1607

**Comment by luacmartins** [comment] 2024-10-01 18:03
I think we can close this. We had multiple people confirm it was fixed in Slack.

**Closed by luacmartins** 2024-10-01 18:03 UTC
Labels: Engineering, Hourly, Bug

**Comment by blazejkustra** [comment] 2024-10-01 18:21
We hit 50k issues btw 😅
