### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] Web - Clicking next to 'Didn't receive a magic code?' link requests a code on sign-in page, but it doesn't on contact methods section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22935] opened 2023-07-15 12:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to sign-in page
2. Enter email & click on 'Continue' button
3. Wait for timeout to finish
4. Hover over the blank space next to 'Didn't receive a magic code?' link & click on the empty space

## Expected Result:
The empty space next to the link shouldn't be clickable as it doesn't on the contact methods section

## Actual Result:
The empty space next to the link is clickable

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d49a5946-db9c-4d7a-be86-d1dd642c6b9c

https://github.com/Expensify/App/assets/93399543/7e5fde1d-08f9-4794-8030-db5234323dbe

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689339820759009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d234fa38b658c551</li>
        <li>Upwork Job ID: 1681240927406481408</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-07-18 09:54
not overdue, added external

**Comment by ishpaul777** [comment] 2023-07-18 12:19
## Proposal
###  Problem
 Clicking next to 'Didn't receive a magic code?' link requests a code on sign-in page, but it doesn't on contact methods section
 
Root Cause
The issue is related to the styling of the PressableWithFeedback component. It lacks a specific width, causing it to take the full width of its parent element by default. This results in the inconsistent behavior when clicking next to the link in the two sections.

Proposed Changes
To address this issue, we will apply the styles.alignSelfStart to the PressableWithFeedback component. This will restrict its width to an appropriate size and ensure consistent behavior across both sections.

**Comment by sobitneupane** [comment] 2023-07-20 11:00
[Proposal](https://github.com/Expensify/App/issues/22935#issuecomment-1636757167) from @namhihi237 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by Natnael-Guchima** [comment] 2023-07-20 11:18
I have accepted the offer. Thanks!

**Comment by Julesssss** [comment] 2023-07-24 08:23
Merged, awaiting deployment

**Comment by laurenreidexpensify** [comment] 2023-08-02 12:49
Payment Summary - 

-  External issue reporter - @Natnael-Guchima $250 in Upwork 
-  Contributor that fixed the issue - @namhihi237 $1000 + $500 3 day bonus in Upwork
-  Contributor+ that helped on the issue and/or PR - @sobitneupane $1000 + $500 3 day bonus -  please request in New Expensify

**Comment by laurenreidexpensify** [comment] 2023-08-02 12:50
Confirmed bonus times:

Issue assigned Thurs Jul 20 @ 12:18pm 
Merged Mon July 24 @ 9:23am

**Comment by Julesssss** [comment] 2023-08-07 10:50
Bump on [this](https://github.com/Expensify/App/issues/22935#issuecomment-1662160871) @sobitneupane

**Comment by laurenreidexpensify** [comment] 2023-08-08 12:09
Bumped @sobitneupane in Slack

**Comment by sobitneupane** [comment] 2023-08-09 05:10
> BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

Rather than a bug, it was inconsistency issue. [This PR](https://github.com/Expensify/App/pull/20732) was the one introducing timer.

**Comment by sobitneupane** [comment] 2023-08-09 05:12
**Regression Test Proposal**

1. Navigate to the sign-in page
2. Enter your email & click on the 'Continue' button
3. Wait for a timeout to finish
4. Hover over the blank space next to 'Didn't receive a magic code?' link
5. Verify that user can not click on the blank next to ''Didn't receive a magic code?'

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-08-09 08:02
Requested payment on newDot.

https://github.com/Expensify/App/issues/22935#issuecomment-1662154745

**Closed** 2023-08-09 15:04 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-10 03:41
Reviewed the payment details for @sobitneupane. $1,500 is approved for payment in NewDot.
