### ISSUE TITLE
[$1000] Chat - Removed reactions by other user offline still displayed after going online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23388] opened 2023-07-22 00:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR ** https://github.com/Expensify/App/pull/17996
## Action Performed:
Precondition: Login as users A & B on Web ; a chat exists between them

1. Open https://staging.new.expensify.com/
2. As users A & B open the common chat
3. As user A add reactions to a message
4. As user B add reactions to a different message
5. As user A go offline
6. As user A remove added reactions
7. As user B remove added reactions
8. As user A go online
9. As user A reload the page

## Expected Result:
After user A goes online and also after they reload the page - user A doesn't see reactions removed by users A & B at steps 6-7

## Actual Result:
After user A goes online - they don't see reactions removed by user A BUT still see reactions removed by user B. (Web, mWeb, Desktop app behaviour).
After user A goes online - they still see both removed reactions from users A &B. (iOS app, Android app behaviour).
Issue persists after reloading the page / restarting the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS /  Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.44.0

**Reproducible in staging?:**  Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/932fd1c1-c51d-4d0c-9dfb-6aa32e6e2960

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d3092dcc6629c8a</li>
        <li>Upwork Job ID: 1683362853973221376</li>
        <li>Last Price Increase: 2023-08-03</li>
    </ul>
</details>

**Comment by robertjchen** [comment] 2023-07-24 06:25
Thanks for the report! Looks like we have at least another regression coming off that PR: https://github.com/Expensify/App/issues/23307

I wouldn't say this would be a deploy blocker per-se, just a regression. We can get it addressed without blocking the deploy 👍

**Comment by StevenKKC** [comment] 2023-07-24 10:54
BE does not send `reportActionsReactions` after goes online and reload the page.

**Comment by pbkompasz** [comment] 2023-07-24 11:46
@StevenKKC I don't think it's a BE issue given that if you remove the cache on the client side and reload everything the issue gets resolved.

**Comment by railway17** [comment] 2023-07-24 13:29
> @StevenKKC I don't think it's a BE issue given that if you remove the cache on the client side and reload everything the issue gets resolved.

Agree with @pbkompasz 
Api returns empty reactions list when turning off force offline.
Just do not update the persistent storage.
I also think that it should be resolved in onyx side

**Comment by railway17** [comment] 2023-07-24 13:31
Contributor details
Your Expensify account email: [hanmingyun1212@gmail.com](mailto:hanmingyun1212@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01bc9266760788d96f

**Comment by railway17** [comment] 2023-07-24 13:33
Contributor details
Your Expensify account email: hanmingyun1212@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01bc9266760788d96f

**Comment by Santhosh-Sellavel** [comment] 2023-07-24 13:43
@puneetlath or @rushatgabhane Please hold on this issue for #23307. I'll post an update whether it's handled there or not. Because I ran into something similar while reviewing PR. So wait for here, thanks!

**Comment by puneetlath** [comment] 2023-08-02 17:59
I just tested on staging and the bug seems to still be occurring.

**Comment by puneetlath** [comment] 2023-08-02 17:59
So @Santhosh-Sellavel I think I'll remove the hold, yeah?

**Comment by Santhosh-Sellavel** [comment] 2023-08-02 18:16
If it's occurring it can come off hold.

**Comment by pbkompasz** [comment] 2023-08-03 19:32
@puneetlath I cannot reproduce the issue anymore
I think it got fixed in this PR [#23371](https://github.com/Expensify/App/pull/23371)

**Comment by puneetlath** [comment] 2023-08-03 22:30
Hmm, yeah I just tried again and also wasn't able to reproduce. Ok closing! Thanks everyone.

**Closed by puneetlath** 2023-08-03 22:30 UTC
Labels: External, Engineering, Weekly, Help Wanted
