### ISSUE TITLE
[HOLD for payment 2024-08-14] [HOLD for payment 2024-08-13] [$250] Workspace - Default currency set in workspace is not displayed in BNP while submit expense in WS chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46727] opened 2024-08-02 14:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4805490
**Email or phone of affected tester (no customers):** applausetester+ck0208@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team
**Slack conversation:**

## Action Performed:
Precondition: Create a new expensifail account on ND site & create a new workspace
1. Go to Workspace settings >> tap on Profile menu
2. Set the workspace currency to something different that your local currency
3. Navigate to the workspace chat
4. Tap on + icon in composer
5. Select Submit expense

## Expected Result:
The same currency that is set in workspace profile settings should display in BNP while submitting expense in workspace chat

## Actual Result:
User's local currency get displayed in BNP while submit expense in WS chat though user has set a different currency in WS settings

Note: Correct default currency get reflected in BNP after refreshing the workspace chat page & then selecting submit expense opetion

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5641bb7b-ec84-427f-b623-c2f3c0c0ef49

![Bug6560237_1722607990817!Screenshot__226_](https://github.com/user-attachments/assets/b4789940-4f59-46bd-8402-2a95463e8749)

![Bug6560237_1722607983557!Screenshot__225_](https://github.com/user-attachments/assets/87587dac-67da-412e-ab80-1ea3bfdbf347)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012cb00b4b68f61310</li>
        <li>Upwork Job ID: 1819442698262740619</li>
        <li>Last Price Increase: 2024-08-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by izarutskaya** [comment] 2024-08-02 14:55
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-08-02 14:56
Production

https://github.com/user-attachments/assets/91220128-fb56-4741-bffb-752918bc40d1

**Comment by bernhardoj** [comment] 2024-08-02 16:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Default workspace currency isn't used when opening submit expense.

### What is the root cause of that problem?
When we start a money request, we will initialize the data here, including the currency from the `policy`.
https://github.com/Expensify/App/blob/fefda46147f1b3389268dadb722fe5d37ec95c16/src/pages/iou/request/IOURequestStartPage.tsx#L95-L100

However, `policy` is initially undefined and we only re-init when the reportID is different or when changing the tab.
https://github.com/Expensify/App/blob/fefda46147f1b3389268dadb722fe5d37ec95c16/src/pages/iou/request/IOURequestStartPage.tsx#L110-L118

This is because the `policy` depends on the `report` onyx,
https://github.com/Expensify/App/blob/fefda46147f1b3389268dadb722fe5d37ec95c16/src/pages/iou/request/IOURequestStartPage.tsx#L184-L190

and it's a known issue if the onyx depends on another onyx as I explained in my proposal on this [old issue](https://github.com/Expensify/App/issues/37466#issuecomment-1970736964). In our case, the `report` is initially undefined for the `policy` onyx `key` function.

Weirdly, this only started to happen after https://github.com/Expensify/App/pull/45762, specifically the PopoverMenu file changes. Before the PR, the `report` is still undefined for the `policy` `key` function, but the component isn't rendered until the `policy` is available.

### What changes do you think we should make in order to solve the problem?

Even though it started to happen after  https://github.com/Expensify/App/pull/45762, the root cause is in the `withOnyx`. Because `withOnyx` is deprecated, we can just migrate IOURequestStartPage to using `useOnyx` which won't have the `withOnyx` bug.

**Comment by bernhardoj** [comment] 2024-08-03 02:49
PR is ready

cc: @mollfpr

**Comment by mollfpr** [comment] 2024-08-03 05:41
Thanks @bernhardoj !

**Comment by roryabraham** [comment] 2024-08-05 16:32
requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1722874615633969

**Comment by m-natarajan** [comment] 2024-08-05 16:57
https://github.com/user-attachments/assets/c45676ff-9da1-487f-bc48-55e60386506c

Unable to reproduce.

**Comment by roryabraham** [comment] 2024-08-05 17:05
Great, this is fixed on staging. Now we'll just wait for it to go to prod and a week later issue payment.

**Comment by bernhardoj** [comment] 2024-08-13 13:17
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-08-14 19:07
$250 approved for @bernhardoj

**Comment by mollfpr** [comment] 2024-08-14 20:36
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I couldn't find the offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

_Prerequisite:
Go to Workspace settings and set the workspace currency to something different than your local currency_

1. Navigate to the workspace chat
2. Tap on the + icon in the composer
3. Select Submit expense
4. Verify the currency shown is the workspace currency
5. 👍 or 👎

**Comment by bfitzexpensify** [comment] 2024-08-15 09:51
Works for me! Proposed in https://github.com/Expensify/Expensify/issues/420653. Closing this out

**Closed by bfitzexpensify** 2024-08-15 09:51 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-20 20:25
$250 approved for @mollfpr
