### ISSUE TITLE
Feature Request: Show list of recent merchant names when typing in the merchant field in Manual request

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39014] opened 2024-03-26 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
We don't show the list of recent merchants based on the account as we begin typing when submitting a manual request in NewDot.

## Solution:
As in OldDot, suggested merchant list appears from the recent saved merchants as we begin typing merchant name based on the account

## Context/Examples/Screenshots/Notes:

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @MarcFillari 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711460237297499

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec16821075063fa6</li>
        <li>Upwork Job ID: 1777875370191978496</li>
        <li>Last Price Increase: 2024-04-10</li>
    </ul>
</details>

**Comment by MarcFillari** [comment] 2024-03-26 20:20
some additional background discussion in this wave-collect slack thread
https://expensify.slack.com/archives/C036QM0SLJK/p1711388819931499
<img width="943" alt="image" src="https://github.com/Expensify/App/assets/124016105/6ea51fd6-4266-43a4-9587-9aff7464d451">

**Comment by nkdengineer** [comment] 2024-03-26 23:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Feature Request: Show list of recent merchant names when typing in the merchant field in Manual request
### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
1. We need to create a onyx collection to store this data, named ```recentlyUsedMechants_```
2. Then, update this once we create request money, edit request money (same as categories) (BE also need to do that)
3. In [IOURequestStepMerchant.](https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepMerchant.js), use ```SelectionList``` with prop ```showConfirmButton: true```  rather than the current form. Below is a pseudo code:
```
 const [searchValue, debouncedSearchValue, setSearchValue] = useDebouncedState('');
    const filteredRecentlyUsedMerchants = useMemo(
        () => recentlyUsedMerchants.filter((merchant) => merchant.toLowerCase().includes(searchTerm?.toLowerCase() ?? ''))[(searchTerm, recentlyUsedMerchants)],
    );

    return (
        <StepScreenWrapper
            headerTitle={translate('common.merchant')}
            onBackButtonPress={navigateBack}
            shouldShowWrapper
            testID={IOURequestStepMerchant.displayName}
        >
            <SelectionList
                sections={[{data: filteredRecentlyUsedMerchants}]}
                headerMessage={headerMessage}
                textInputValue={searchValue}
                textInputLabel={shouldShowTextInput ? translate('common.search') : undefined}
                onChangeText={setSearchValue}
                onSelectRow={(value) => updateMerchant(value)}
                ListItem={RadioListItem}
                initiallyFocusedOptionKey={selectedOptionKey ?? undefined}
                isRowMultilineSupported
                showConfirmButton
                onConfirm={() => {
                    if (isEmpty(validate())) {
                        updateMerchant(searchValue);
                    }
                }}
            />
        </StepScreenWrapper>
    );
```

### What alternative solutions did you explore? (Optional)
- NA

**Comment by mallenexpensify** [comment] 2024-03-27 00:18
Added to #wave-collect project.  Tom will assign status/priority.  This does seam like it'd be nice to have.

**Comment by mallenexpensify** [comment] 2024-04-10 01:45
@hoangzinh , do you think this can be external?

**Comment by mallenexpensify** [comment] 2024-04-12 19:58
Thanks for asking @hoangzinh , I'm a lil concerned this feature could end up being more work and planning than most others. 

[Posted in #expensify-open-source for eyes ](https://expensify.slack.com/archives/C049HHMV9SM/p1712951861486859?thread_ts=1711460237.297499&cid=C049HHMV9SM)
> Is anyone working on showing recent searches for merchants in NewDot?  Or any other search-related projects for features that might use similar logic for showing recent results?
Asking because I'm a lil concerned with building [Feature Request: Show list of recent merchant names when typing in the merchant field in Manual request](https://github.com/Expensify/App/issues/39014#top) as a one-off external project.  If there's work being done elsewhere, or a standard to base the results off, I'd like to review that.  cc 
[@HZ](https://expensify.slack.com/team/U04UFGPNG05)

**Comment by mallenexpensify** [comment] 2024-04-12 20:12
Closing pending [Mills comment in the thread](https://expensify.slack.com/archives/C049HHMV9SM/p1712952722291959?thread_ts=1711460237.297499&cid=C049HHMV9SM)
> We’re going to implement a recents list for Search v2. It’ll be part of the general search widget.

**Comment by mallenexpensify** [comment] 2024-04-12 20:25
D'oh, got a lil trigger happy.  Going to leave open, @JmillsExpensify added to #wave-colllect and will be addressing before too long.

**Comment by mallenexpensify** [comment] 2024-04-23 23:14
Weird, added `Monthly` two weeks ago and it went overdue ¯\_(ツ)_/¯

**Comment by mallenexpensify** [comment] 2024-05-29 02:15
[Checking on in  #wave-collect s](https://expensify.slack.com/archives/C036QM0SLJK/p1716948867883439)ince it was there before it got auto closed a month ago.

**Comment by mallenexpensify** [comment] 2024-05-29 15:53
Gonna close for now cuz Jason shared in   #wave-collect 
> I kind of think we keep it closed for now. We are going to persist recents for search as part of Search v2, and then after that we can implement the same for categories, tags, merchants, etc. Basically all in one go.

**Closed** 2024-05-29 15:53 UTC
Labels: Weekly, Internal, NewFeature
