### ISSUE TITLE
[$250] Cursor is misplaced after pasting a multiline message on Description field in request Money flow.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42112] opened 2024-05-13 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715584445797959

## Action Performed:
1. Create a new money request via `Submit expense`.
2. Enter amount and go to confirmation page.
3. Click `Description` Now paste a multiple text.
4. Observe the cursor after text is pasted.

## Expected Result:
Cursor should be at the end of pasted text.
## Actual Result:
Cursor is at the second last character of the pasted text.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/23d65cfe-13dc-4b8a-8e21-0f69679b5815

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b95c1756beba7a4b</li>
        <li>Upwork Job ID: 1790840678415347712</li>
        <li>Last Price Increase: 2024-05-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by alexrasla** [comment] 2024-05-15 23:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The cursor in the `description` field of the `Submit expense` model does not render at the end of the input text when we paste multiple lines

### What is the root cause of that problem?

The root cause of the problem is that we are treating the input field as an HTML `input` element, when it is really a `content-editable` div`

### What changes do you think we should make in order to solve the problem?

We need to check whether the `input` variable passed in `updateMultilineInputRange` is a `input` HTML element, or a `content-editable` div. If it is a `input` element, use the same functionality we have now, but if it is a `content-editable` div, we want to utilize the `document.createRange` and `window.getSelection` functions to move the cursor to the end of the `content-editable` div value. Something like this is a solution that works, but will be optimized if my proposal is selectedd:

```
if (shouldAutoFocus && document.createRange && window.getSelection) {
        const range = document.createRange();
        range.selectNodeContents(input);
        range.collapse(false); // false means collapse to end (true would be collapse to start)
        const selection = window.getSelection();
        if (selection) {
            selection.removeAllRanges();
            selection.addRange(range);
        }
        // eslint-disable-next-line no-param-reassign
        input.scrollTop = input.scrollHeight;
    }
```

**Comment by Christinadobrzyn** [comment] 2024-05-16 05:28
Hey @rushatgabhane do you think this [issue](https://github.com/Expensify/App/issues/42216) has the same root? Can they be fixed together?

**Comment by moonstar-95515** [comment] 2024-05-17 06:17
I can't reproduce on staging.

**Comment by moonstar-95515** [comment] 2024-05-19 01:21
@parasharrajat 
Still can't reproduce it. 

> Then copy the title of any issue from GitHub like this one and paste it in the field.

Could you please add example GitHub issue title?

**Comment by rushatgabhane** [comment] 2024-05-20 15:59
agree, can't repro this issue

**Comment by johncschuster** [comment] 2024-05-21 22:07
Great! Thanks for confirming that! Can we close this one?

**Comment by rushatgabhane** [comment] 2024-05-22 07:47
@johncschuster yes

**Closed** 2024-05-28 19:07 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
