### ISSUE TITLE
[$500] Details - In details page, instead of mail id, "hidden" is shown for newly created account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28202] opened 2023-09-26 00:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Create one new account
3. Again login into any existing account
4. Tap fab
5. Tap send message
6. Enter and select newly created account as first user and any other contact as second user
7. Tap create group
8. Tap header
9. Note the details of above newly created account in details page

## Expected Result:
In details page, "hidden" must not be shown and mail id of newly created account must be shown

## Actual Result:
In details page, instead of mail id, "hidden" is shown for newly created account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.74-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/76f4a033-51da-4e00-a252-adb53790a974

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014637fdc103f5f54c</li>
        <li>Upwork Job ID: 1707442613502255104</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-09-26 19:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The alternate text in the participant list shows as hidden for newly created users. 


### What is the root cause of that problem?

The text hidden shows up when the user has no login is set yet. 

### What changes do you think we should make in order to solve the problem?
We can use the displayName value as an alternative text while waiting for the login property to be set, if the display name does not exist we can then fallback to the hidden text. 

https://github.com/Expensify/App/blob/cfad43ff96f2a104c51fd475e07f0980c4379fcd/src/pages/ReportParticipantsPage.js#L70C1-L70C1

We can update it to 
 
`const userLogin = LocalePhoneNumber.formatPhoneNumber(userPersonalDetail.login || '') || userPersonalDetail.displayName || translate('common.hidden');`

![image](https://github.com/Expensify/App/assets/144037189/5e318629-0bd3-438f-af3a-d0b47ed8305a)


### What alternative solutions did you explore? (Optional)

N/A

**Comment by maddylewis** [comment] 2023-09-28 17:10
adding external label to review existing proposal

**Comment by saad995** [comment] 2023-09-29 17:34
[Please re-state the problem that we are trying to solve in this issue.]
When starting a new group and adding new participants with email address. The participants email address does not appear below the display name, instead hidden is being shown.

[What is the root cause of that problem?]
![image](https://github.com/Expensify/App/assets/24203380/2fdc5b01-0326-4df5-95ed-250271e642d5)
![image](https://github.com/Expensify/App/assets/24203380/e52b6270-e769-4604-bbd6-c2d1ccbc1804)

As it seems, the login id does not appear because the object "userPersonalDetail" does not have the property "login" in it. This is because when the API is called with command "OpenReport" it responds with an altered object which does not include "login" property along with some other properties.

[What changes do you think we should make in order to solve the problem?]
I believe if we can check into the API response and try to respond with same data object, it will solve the issue.

**Comment by saad995** [comment] 2023-09-29 17:38
Contributor details
Your Expensify account email: saad26_95@live.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010ccc708154c23a1c

**Comment by maddylewis** [comment] 2023-10-02 14:29
@robertKozik - bump on proposal review - ty!

**Comment by robertKozik** [comment] 2023-10-02 14:50
hi all @abdel-h66 @saad995 ! I'm having difficulties with reproducing this bug. Could you confirm me if it still exists? As we need the new account for this, do I need to log into this new account beforehand?

**Comment by saad995** [comment] 2023-10-02 16:03
Hi @robertKozik, yes you need to log in and then start a group chat with unknown email ids.

I was trying to upload a video here for you but there are some file size limitations.

Let me know if you there's anything else you need

**Comment by saad995** [comment] 2023-10-06 10:36
Guys any update on this?

**Comment by robertKozik** [comment] 2023-10-06 12:09
Ok got it! thanks @saad995 . I'll review the proposals then :D

**Comment by robertKozik** [comment] 2023-10-06 12:21
Thank you, @saad995 and @abdel-h66, for your valuable input on this issue. Based on our findings, it appears that this will require some insight or a fix from the internal backend side, as the root cause seems to be the absence of the login property.

@maddylewis, could you please add the internal tag, as we suspect that the root cause lies on the backend side?

**Comment by robertKozik** [comment] 2023-10-12 16:41
@maddylewis bump

**Comment by maddylewis** [comment] 2023-10-13 19:03
sorry for the delay, @robertKozik. i added the internal label. let me know if there's anything else i can do on this issue rn. 

@saad995 - we will process payment for the overall analysis you did on this one. it will be less than the standard bounty. i will confirm the payment amount and send you an offer once we've confirmed a fix for this one.

**Comment by maddylewis** [comment] 2023-10-19 14:15
@robertKozik - would love some direction on the best next steps for this issue - ty! 

https://github.com/Expensify/App/issues/28202#issuecomment-1762049252

**Comment by robertKozik** [comment] 2023-10-23 11:07
Sorry for the delay here. I believe we need the insight from the internal engineer - the login property is missing as stated in the @saad995 [analysis](https://github.com/Expensify/App/issues/28202#issuecomment-1741262390) and (if it's not intentional) we can fix this on the backend

**Comment by maddylewis** [comment] 2023-10-25 16:03
it looks like an engineer didn't get assigned to this one last week. @deetergp - when you have a chance, can you take a look a this comment? ty! https://github.com/Expensify/App/issues/28202#issuecomment-1774955740

**Comment by deetergp** [comment] 2023-11-01 00:43
Apologies gang, I've been very heads down on a time-sensitive project. To confirm @saad995, you're saying the `OpenReport` command does not return the expected data?

**Comment by saad995** [comment] 2023-11-01 09:39
Hi @deetergp,
Yes, it seems OpenReport command responds with inconsistent object structure as mentioned in the screenshots provided above.

**Comment by deetergp** [comment] 2023-11-08 00:15
Was OOO for a couple days, will try to investigate this one further tomorrow AM.

**Comment by saad995** [comment] 2023-11-14 07:48
Hi guys, is there any update on this?

**Comment by deetergp** [comment] 2023-11-14 23:11
I finally had a chance to dig deeper into this one and from what I can see in the API code, this is very much on purpose and we would have to undo lot of very intentional looking code in order to surface this by default. As each member joins the chat, their details become visible to the rest of the group. 

@puneetlath I see your name in the git blame for a lot of this, any thoughts on which is is?

![Bug or Feature](https://otb.cachefly.net/wp-content/uploads/2015/07/nerdiest-joke-ever-volkswagon-bug-with-feature-vanity-plate.jpg)

**Comment by puneetlath** [comment] 2023-11-15 16:00
Yes, this is on purpose and not a bug. If you don't "know" someone, then we don't share their login info with you and show "hidden" instead. Closing!

**Closed by puneetlath** 2023-11-15 16:00 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by saad995** [comment] 2023-11-15 17:47
Such a waste of time.....this is the third bug on which I have faced this....please do not post on upwork, i need to report it.
