### ISSUE TITLE
[$1000] Chat -  The link previews are all showing previews for the wrong messages.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23456] opened 2023-07-23 23:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the Lounge announce room 

## Expected Result:
 All link previews are correct

## Actual Result:
Link previews go to the wrong site

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.44.0

**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-21 at 1 27 54 PM](https://github.com/Expensify/App/assets/93399543/c8c889d7-8a50-4def-94bc-74a40648707c)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @johnmlee101 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689960464567709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c41fbcfed654e28a</li>
        <li>Upwork Job ID: 1683976637129768960</li>
        <li>Last Price Increase: 2023-08-08</li>
    </ul>
</details>

**Comment by cubuspl42** [comment] 2023-07-24 10:44
Reproducible. It seems a bit random (can go back and forth between correct previews and messed-up previews). Looks like a backend problem.

**Comment by tjferriss** [comment] 2023-07-25 22:24
Asking a few clarifying questions in [Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1690323818381329?thread_ts=1689960464.567709&cid=C049HHMV9SM)

**Comment by tjferriss** [comment] 2023-07-25 23:05
I got access to the lounge #announce room and was able to replicate the bug. Public link is here: https://new.expensify.com/r/8292963527436014

**Comment by mollfpr** [comment] 2023-07-27 16:58
The link preview metadata is from the BE, and there is nothing we can do to fix it in this E/App.

**Comment by tjferriss** [comment] 2023-08-01 22:12
Based on @mollfpr we might need someone internal to take a look at what is going on here https://github.com/Expensify/App/issues/23456#issuecomment-1654001087

**Comment by tjferriss** [comment] 2023-08-03 18:40
@AndrewGable are you able to take a look at this for us?

**Comment by kevinksullivan** [comment] 2023-08-04 21:17
@tjferriss FYI I am going OOO for next week, but since we're both assigned and on BZ I assume you can keep an eye on it and I don't need to assign someone else.

**Comment by AndrewGable** [comment] 2023-08-08 20:05
We can take this internal.

**Comment by tjferriss** [comment] 2023-08-15 19:43
@AndrewGable I'm confused here. Are you going to take this on as an internal issue?

**Comment by AndrewGable** [comment] 2023-08-24 19:50
This is an internal issue, I am not going to have time to work on it this next week as I will be OOO, so feel free to assign if it's more urgent!

**Comment by tjferriss** [comment] 2023-08-28 22:10
I'm going to re-assign this one with Andrew being OOO.

**Comment by tjferriss** [comment] 2023-09-11 22:52
I'm not able to reproduce this one anymore so I'm going to close. The links in this room and all others I'm in appear to be working correctly.

<img width="975" alt="Screenshot 2023-09-11 at 15 51 57" src="https://github.com/Expensify/App/assets/8292562/68b344ee-6608-4e87-b4d9-0a1f6ecc6703">

**Comment by johnmlee101** [comment] 2023-09-12 09:29
Hmm, there's no link preview at all for that

**Comment by johnmlee101** [comment] 2023-09-12 09:29
We'd expect something, right?

**Comment by grgia** [comment] 2023-09-21 04:15
Asked about link previews in slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1695269684080189

**Comment by grgia** [comment] 2023-10-02 09:09
Closing as we've disabled link previews for now

**Closed by grgia** 2023-10-02 09:09 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
