### ISSUE TITLE
[$500] Background image crop after resize

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29237] opened 2023-10-10 21:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696951102341389

## Action Performed:
1. Open a chat with any user
2. Click avatar to open RHN
3. Resize browser to smaller and back original
## Expected Result:
The background image is not partially cropped
## Actual Result:
The background image is partially cropped
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/4dd3cc19-8692-4ad0-a0a7-3b9863e84fab

https://github.com/Expensify/App/assets/38435837/3dfb8d0a-74b3-4ac4-8c7c-659b8973b8af

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/d707f36f-f2b6-4f3f-adf0-83a005e83375

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015433ddd90da9816b</li>
        <li>Upwork Job ID: 1711859135278239744</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2023-10-10 21:40
## Proposal by @namhihi237 
### Please re-state the problem that we are trying to solve in this issue.
The background image is not partially cropped after resizing the screen
### What is the root cause of that problem?
When opening RHN and resizing the screen background image, the part that RHN occupies will be lost [here](https://github.com/Expensify/App/blob/main/src/pages/home/report/AnimatedEmptyStateBackground.js)
### What changes do you think we should make in order to solve the problem?
we use a state variable forceRender to trigger a re-render of the component when the screen is focused.
When the screen is focused, we increment the forceRender variable, which causes the component to re-render with a different key.
This forces React to unmount and remount the component, effectively triggering a re-render of the AnimatedEmptyStateBackground component when the screen receives focus.
We update [here](https://github.com/Expensify/App/blob/main/src/pages/home/report/AnimatedEmptyStateBackground.js)
```js
 const [forceRender, setForceRender] = useState(0);
 const isFocused = useIsFocused();
    useEffect(() => {
        if (!isFocused) {
            return;
        }
        setForceRender((prev) => prev + 1);
      }, [isFocused]);
```
We add key
```js
        <Animated.Image
            key={forceRender}
```
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2023-10-10 23:15
I can repro this:

<img width="956" alt="image" src="https://github.com/Expensify/App/assets/16232057/816a9b0b-90cd-4a3a-9506-80d64f2baa31">

**Comment by ashuvssut** [comment] 2023-10-11 01:30
# Proposal  
----------------------
### Please re-state the problem that we are trying to solve in this issue.

The background image is partially cropped after resizing the screen at the point when `isSmallScreenWidth` is true 

What is the root cause of that problem?
`useAnimatedStyle` doesnt have `isSmallScreenWidth` state the deps array.

What changes do you think we should make in order to solve the problem?
1. `isSmallScreenWidth` state must be added to the deps array`.
2. transition worked properly when provided with proper transition end styles
 ```diff
 if (!isSmallScreenWidth) {
-       return {};
+      return {transform: [{translateX: withSpring(0)}, {translateY: withSpring(0)}]};
 }
```




## POC

I have fixed this issue. Please view the POC video

https://github.com/Expensify/App/assets/60546840/bb1bad0a-8533-46e2-8024-280f3da6d4e7

**Comment by ashuvssut** [comment] 2023-10-11 09:02
@fedirjh

**Comment by trjExpensify** [comment] 2023-10-16 12:00
Ah yeah, same. I can't repro it anymore since that got deployed. We can close this issue out then! :)

**Closed by trjExpensify** 2023-10-16 12:00 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
