### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] Chat - Compose Box is shown above empty space and doesn't resize properly

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39061] opened 2024-03-27 14:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4459664
**Email or phone of affected tester (no customers):** gatantm@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to any chat
2. Tap on the compose box
3. Type a few lines and tap on expand icon

## Expected Result:
The compose box is directly above the keyboard, expands with the first few lines added and expands to half the screen when tapping the expand icon

## Actual Result:
The compose box has empty space between it and the keyboard, expands with the first few lines but either doesn't expand when tapping the expand icon or contracts.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/510d64ab-96f7-42c1-bca2-631d98897f17

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013eedeeb058661915</li>
        <li>Upwork Job ID: 1772998191642521600</li>
        <li>Last Price Increase: 2024-03-27</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by izarutskaya** [comment] 2024-03-27 14:11
@JmillsExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-27 14:11
We think that this bug might be related to #vip-vsb.

**Comment by izarutskaya** [comment] 2024-03-27 14:14
Production video 

https://github.com/Expensify/App/assets/115492554/8bdede3d-f00f-4b4e-8772-a803262263bf

**Comment by JmillsExpensify** [comment] 2024-03-27 14:41
@tgolen Do you think this is a blocker? I agree with QA that it's a #vip-vsb issue, though I also think this is largely cosmetic.

**Comment by tgolen** [comment] 2024-03-27 14:44
It is a pretty ugly bug, but since it doesn't prevent any functionality and only affects a single platform, I agree it's not a blockers. Let's make this a normal bug and I'll see if I can quickly spot the PR that might have caused the regression. I'll remove the deploy blocker label for now.

**Comment by tgolen** [comment] 2024-03-27 14:50
@suneox Do you think this might have been a regression of your recent PR https://github.com/Expensify/App/pull/38755 ?

**Comment by tgolen** [comment] 2024-03-27 16:33
Thanks for looking into this. It should just be the `staging` branch.

**Comment by sobitneupane** [comment] 2024-03-29 09:30
Regression from https://github.com/Expensify/App/issues/35380 issue https://github.com/Expensify/App/pull/38755 PR. @situchan will be reviewing the PR.

**Comment by sobitneupane** [comment] 2024-04-05 07:50
@situchan is on leave this month. So, I think I should go ahead and review the PR.

**Comment by JmillsExpensify** [comment] 2024-04-30 23:32
Payment summary:

 - Contributor: @suneox $500
 - Contributor+: @sobitneupane $500

**Comment by JmillsExpensify** [comment] 2024-04-30 23:34
Contributor paid out. @sobitneupane since you're paid via Expensify, I'm going to close this issue, though please fill out the BZ checklist before requesting. Thanks!

**Closed by JmillsExpensify** 2024-04-30 23:34 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by sobitneupane** [comment] 2024-05-07 10:03
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/38755
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/38755#issuecomment-2027314901
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2024-05-07 10:05
**Regression Test Proposal**

1. Go to any chat in mWeb/Safari
2. Tap on the compose box
3. Type a few lines and tap on expand icon
4. Verify that the compose box resizes properly.

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-05-12 19:09
$500 approved for @sobitneupane.
