### ISSUE TITLE
Black bar appeaers below context menu for brief moment when long pressing a message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18906] opened 2023-05-14 11:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app in android chrome
2. Open any report
3. While keyboard is open, long press any message to open popup and observe that app displays big black bar below popup for few seconds
4. Try the same on android app and observe that it does not allow to long press and open popup while keyboard is open

## Expected Result: 
App should allow to long press and open popup while keyboard is open like it doesn't on android app
## Actual Result: 
App allows to long press and open popup while keyboard is open on android chrome which causes app to display big black bar below popup for few seconds

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.13.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ef068395-329c-42f6-9f11-0dd43fbc22d7

https://github.com/Expensify/App/assets/43996225/fb0772c1-1314-4da6-b66d-6b48646e63c7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683991567745719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment] 2023-05-15 17:37
Hm, I'm not able to reproduce on Android Chrome..

<img width="288" alt="image" src="https://github.com/Expensify/App/assets/33293730/7dab1ae0-a391-4e05-9322-8391f5f7b8f8">

**Comment by lschurr** [comment] 2023-05-15 17:37
@kavimuru are you able to reproduce this?

**Comment by lschurr** [comment] 2023-05-16 18:08
Discussing in Slack: https://expensify.slack.com/archives/C049HHMV9SM/p1684256194134059?thread_ts=1683991567.745719&cid=C049HHMV9SM

**Comment by lschurr** [comment] 2023-05-16 19:47
I'm heading OOO from May 17-23rd. I've re-added the Bug label to reassign and will keep myself assigned as well. If any action is needed on May 24th, I'll take this back from you @flaviadefaria 

Latest: Slack discussion is still happening to determine whether we need to fix this or not: https://expensify.slack.com/archives/C049HHMV9SM/p1684260483156519?thread_ts=1683991567.745719&cid=C049HHMV9SM

**Comment by flaviadefaria** [comment] 2023-05-17 14:08
Alright based on the Slack discussion I'm closing this GH.

**Closed by flaviadefaria** 2023-05-17 14:08 UTC
Labels: Daily, Needs Reproduction, Bug
