### ISSUE TITLE
Error message is not translated to Spanish on sign in page, but it is translated to spanish on the contact methods page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#26807] opened 2023-09-05 16:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Change language preference to 'Spanish'
2. Click on 'Profile' avatar > click on 'Profile' > click on 'contact methods'
3. Click on 'New contact method' > enter email address  & click on 'Add' button
4. Open the newly added contact method
5. Enter a wrong magic code & and observe that the error message is in Spanish
6. Sign out
7. Scroll to the bottom & and change the language preference to Spanish
8. Enter email & click on 'Continue' button
9. Enter a wrong magic code

## Expected Result:
 Error message is not translated to Spanish as contact methods section
## Actual Result:
Error message should be consistently translated to Spanish on Sign in page too.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/3fb21a57-899f-4afe-8fe5-014bc9b57db2

https://github.com/Expensify/App/assets/38435837/925bae12-707e-4949-bfb5-246ad952b453

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-Guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693292456452099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kanno927** [comment] 2023-09-05 17:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error message is not translated to Spanish on sign in page, but it is translated to spanish on the contact methods page

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/cbda2b03824d9b125ec6ab19e87ff533bea1b22f/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js#L206C31-L206C48

As you can see the code, error message isn't translated. This is the root cause of the problem.

### What changes do you think we should make in order to solve the problem?
We should translate the error message.
```js
const {translate} = useLocalize();

// other code

setFormError({validateCode: translate('validateCodeForm.error.pleaseFillMagicCode')});
```

**Comment by ishpaul777** [comment] 2023-09-05 17:58
This is Backend issue, backend should return a translation key for error, not ful error message.

**Comment by isabelastisser** [comment] 2023-09-05 21:00
Thanks @ishpaul777 !

Closing.

**Closed by isabelastisser** 2023-09-05 21:00 UTC
Labels: Daily, Bug
