### ISSUE TITLE
[HOLD for payment 2024-02-20] Fix clearing read push notifications on Android

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#33568] opened 2023-12-25 20:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @arosiclair 
**Slack conversation:** N/A

## Action Performed:
1. Log into NewDot
2. Send yourself a few messages
3. Verify push notifications display for those messages
4. Open the chat

## Expected Result:
The chat's notifications are cleared

## Actual Result:
The notifications are NOT cleared

## Workaround:
Clear notifications manually

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

N/A

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b960cce35b944ac</li>
        <li>Upwork Job ID: 1749477913412370432</li>
        <li>Last Price Increase: 2024-01-22</li>
    </ul>
</details>

**Comment by arosiclair** [comment] 2023-12-25 20:57
@anmurali no need to triage this. I'm going to get an expert contributor to work on this issue since it requires a bit of a refactor in native code.

**Comment by arosiclair** [comment] 2023-12-25 21:20
## Problem
We implemented functionality to clear notifications for a chat when opening in https://github.com/Expensify/App/pull/31762. 

However, this didn't work well on Android because clearing notifications using Airship's JS APIs like we do [here](https://github.com/Expensify/App/blob/595bf4075988c0b64cb0db1e37694284637fbea2/src/libs/Notification/clearReportNotifications/index.ios.ts#L34), does not run our native [onNotificationDismissed callback](https://github.com/Expensify/App/blob/9788965c9ddd912dbd2978180b17a464ffe3a055/android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationListener.java#L46-L53) which means our [NotificationCache](https://github.com/Expensify/App/blob/main/android/app/src/main/java/com/expensify/chat/customairshipextender/NotificationCache.java) doesn't get updated. We use the cache to build threaded notifications, so subsequent notifications incorrectly display old cached messages. 

To fix this we temporarily disabled the clearing functionality on Android in [this PR](https://github.com/Expensify/App/pull/33386).

## Solution
Let's get rid of the cache and use native APIs to query active notifications instead. Specifically, we can use [getActiveNotifications()](https://developer.android.com/reference/android/app/NotificationManager#getActiveNotifications()). Any extra data we need to store on the notification like the `reportID` can be stored in [extras](https://developer.android.com/reference/android/app/Notification#extras). This should allow us to continue using JS APIs to clear notifications without having to worry maintaining a cache in native code.

**Comment by arosiclair** [comment] 2023-12-26 17:08
Just shared this with a few agencies. Looking to get somebody to work on it pretty soon.

**Comment by arosiclair** [comment] 2023-12-27 20:15
Most people are out until the new year. I'll revisit this next week.

**Comment by mateuuszzzzz** [comment] 2024-01-03 10:54
Hi, I'll be working on that issue

**Comment by arosiclair** [comment] 2024-01-08 21:48
FYI for contributors: you need to replace development `appKey` and `appSecret` in [airshipconfig.properties](https://github.com/Expensify/App/blob/main/android/app/src/development/assets/airshipconfig.properties) with the [production ones](https://github.com/Expensify/App/blob/main/android/app/src/main/assets/airshipconfig.properties)

**Comment by anmurali** [comment] 2024-01-12 18:14
@mateuuszzzzz can you just post an update of your progress here?

**Comment by mateuuszzzzz** [comment] 2024-01-15 15:42
> @mateuuszzzzz can you just post an update of your progress here?

Hi, sorry for the delay.

Probably the problem is in `ReactAutopilot.kt` which handles adding` ReactNotificationProvider` and later by creating an extender it adds our custom provider. I will investigate it more and maybe we will be able to fix this autopilot instead of doing a fallback to the official Android notifications API.

**Comment by arosiclair** [comment] 2024-01-15 16:00
We had some conversation about this [here](https://expensify.slack.com/archives/C04878MDF34/p1705331372313159?thread_ts=1703610436.579849&cid=C04878MDF34)

**Comment by arosiclair** [comment] 2024-01-19 15:03
@mateuuszzzzz any more progress? This has been open for a while so we should start prioritizing fixing it. I saw you're also working on the ideal nav for wave8. if you don't have the bandwidth, maybe someone else at SWM can pick this up?

**Comment by anmurali** [comment] 2024-01-22 23:00
@mateuuszzzzz - can you respond to Andrew here? (https://github.com/Expensify/App/issues/33568#issuecomment-1900586221)

**Comment by robertKozik** [comment] 2024-01-25 20:31
Hi @arosiclair 👋🏼 In order to prioritize this issue, I'll be taking care of it from this point. Before diving in, I've familiarized myself with the context and connected with @mateuuszzzzz to gather more information about it. From what I've seen, the preferred solution is to eliminate the NotificationCache entirely, and I've successfully done that today. If time permits, my next steps involve rewriting a part of the solution to pass Parcelable objects to extras instead of more primitive information about the user. After that, I'll proceed with re-enabling the clearing functionality.

**Comment by arosiclair** [comment] 2024-01-26 14:41
Thanks for the update! Assigning you

**Comment by anmurali** [comment] 2024-01-30 00:12
@robertKozik has just been assigned and is working on this.

**Comment by robertKozik** [comment] 2024-01-31 08:50
Hi! The [PR](https://github.com/Expensify/App/pull/35304) is ready to review!
cc. @arosiclair

**Comment by arosiclair** [comment] 2024-02-14 14:26
This is not a regression (the feature was just not implemented for Android yet), but we should add regression steps now that it is implemented on all platforms.

**Comment by situchan** [comment] 2024-02-14 14:27
Maybe I was responsible for BZ Checklist. Please assign me here

**Comment by arosiclair** [comment] 2024-02-14 14:30
**Regression Test Proposal**

1. Log in
4. Accept prompt for notification permission
2. Open concierge chat
3. Send 3 messages to yourself
5. Verify notifications display for the messages
6. Switch to the chat
7. Verify those notifications are cleared
8. Switch away from the app
    - On web/desktop, switch tabs or minimize the window
    - On native, go to the home screen
9. Send another 3 messages to yourself
10. Switch back to the app
11. Verify those notifications are cleared
12. Switch to the concierge chat
13. Send another 3 messages to yourself
14. Switch to _other_ chats (not the one with the messages)
15. Verify those notifications are NOT cleared 

Do we agree 👍 or 👎

**Comment by anmurali** [comment] 2024-02-16 15:54
So far as I can tell, no one needs to be paid out manually. But confirming [here](https://expensify.slack.com/archives/C049HHMV9SM/p1708098821798629), and assigning a backup in case he does need to be paid as I am OOO

**Comment by Christinadobrzyn** [comment] 2024-02-16 18:47
Payouts due:

Contributor+: $250 @robertKozik (is with SWM so no Expensify payment needed) 

Eligible for 50% #urgency bonus? NA

Upwork job is = NA

Regression test submitted here - https://github.com/Expensify/Expensify/issues/370314

We'll keep this open since it's still in a regression period

**Comment by Christinadobrzyn** [comment] 2024-02-20 15:21
hi! Sorry I'm ooo sick today - I'll follow up on this tomorrow

**Comment by Christinadobrzyn** [comment] 2024-02-21 23:12
Paid out based on the payment summary here - https://github.com/Expensify/App/issues/33568#issuecomment-1954422479

Closing as complete

**Closed by Christinadobrzyn** 2024-02-21 23:12 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
