### ISSUE TITLE
[HOLD for payment 2022-10-18] [$250] Workspace - User can edit/delete and use other actions in the archived chat (only emoji picker is disabled at edit field) @Puneet-here

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11079] opened 2022-09-18 18:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and log in with any account
2. Create a workspace
3. . Search the announce room for it
4. Open it
5. Send some messages
6. Delete the workspace
7. Go to the archived chat and try editing/deleting the messages

## Expected Result:
The actions should be disabled

## Actual Result:
You can still use most of the actions

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.1.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190923833-9250861a-8eda-49c3-8643-aebd64daf090.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Puneet-here

**Slack conversation:**  https://expensify.slack.com/archives/C01GTK53T8Q/p1661530821388659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment] 2022-09-18 19:43
I was able to reproduce on NewDot following the steps outlined in the OP. Sending out to engineering.

**Comment by sobitneupane** [comment] 2022-09-19 03:00
**Proposal:**
This can be achieved by disabling the context menu item `edit` when the report is archived.
https://github.com/Expensify/App/blob/56dcf61a18dc391b6f52f05d05cb975f8352b63a/src/libs/ReportUtils.js#L99-L106
```diff
function canEditReportAction(reportAction) {
    return reportAction.actorEmail === sessionEmail
        && reportAction.reportActionID
        && reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT
        && !isReportMessageAttachment(lodashGet(reportAction, ['message', 0], {}))
        && reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE
        && reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE; 
+      && reportAction.isArchivedRoom;
}
```
 We might want to disable delete as well for Archived Room(not sure).
 https://github.com/Expensify/App/blob/56dcf61a18dc391b6f52f05d05cb975f8352b63a/src/libs/ReportUtils.js#L116-L122
```diff
function canDeleteReportAction(reportAction) {
    return reportAction.actorEmail === sessionEmail
        && reportAction.reportActionID
        && reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT
        && reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE
        && reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE; 
+      && reportAction.isArchivedRoom;
}
```
Similarly, we can achieve the expected output if we want to disable other context menu items as well.

**Comment by sobitneupane** [comment] 2022-09-19 03:07
@davidcardoza @stitesExpensify I just wanted to inform that no one is assigned to this issue.

**Comment by davidcardoza** [comment] 2022-09-19 07:17
Assigned to @stitesExpensify I am not sure how he was unassigned. I must have fat fingered the auto assignment.

**Comment by sobitneupane** [comment] 2022-09-20 06:31
**Proposal:**
This can be achieved by disabling the context menu item `edit` when the report is archived.
https://github.com/Expensify/App/blob/56dcf61a18dc391b6f52f05d05cb975f8352b63a/src/libs/ReportUtils.js#L99-L106
```diff
function canEditReportAction(reportAction) {
    return reportAction.actorEmail === sessionEmail
        && reportAction.reportActionID
        && reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT
        && !isReportMessageAttachment(lodashGet(reportAction, ['message', 0], {}))
        && reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE
        && reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE; 
+      && reportAction.isArchivedRoom;
}
```
 We might want to disable delete as well for Archived Room(not sure).
 https://github.com/Expensify/App/blob/56dcf61a18dc391b6f52f05d05cb975f8352b63a/src/libs/ReportUtils.js#L116-L122
```diff
function canDeleteReportAction(reportAction) {
    return reportAction.actorEmail === sessionEmail
        && reportAction.reportActionID
        && reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT
        && reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE
        && reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE; 
+      && reportAction.isArchivedRoom;
}
```
We can achieve the expected output similarly if we want to disable other context menu items as well.

**Comment by adelekennedy** [comment] 2022-09-22 04:49
[internal](https://www.upwork.com/ab/applicants/1572810150589730816/job-details)
[external](https://www.upwork.com/jobs/~012b296a29978d6406)

**Comment by mananjadhav** [comment] 2022-09-24 23:06
@sobitneupane Your proposal looks good to me. The only thing is `shouldShow` has existing 3rd and 4th parameters, so this should go as a new param. Also I'll leave it to @stitesExpensify if we should just pass the `report` object instead of `isArchivedRoom`.  I am fine with both.

@Puneet-here I didn't understand your proposal. Are you suggesting we don't show the messages at all? I don't think we would want that. Also I would reckon that it is good to have `Copy to Clipboard` and `Mark as Unread` too for the archived chats.

🎀 👀 🎀 
C+ reviewed

**Comment by Puneet-here** [comment] 2022-09-26 06:09
> @Puneet-here I didn't understand your proposal. Are you suggesting we don't show the messages at all? I don't think we would want that. Also I would reckon that it is good to have Copy to Clipboard and Mark as Unread too for the archived chats.

I am suggesting to only render the code for message without wrappers for different actions.

**Comment by mananjadhav** [comment] 2022-09-26 06:12
> without wrappers for different actions.

and does that mean we'll see no Context actions?

**Comment by Puneet-here** [comment] 2022-09-26 06:13
> and does that mean we'll see no Context actions?

Yeah only for archived chats.

**Comment by mananjadhav** [comment] 2022-09-26 06:15
Okay thanks for clarifying, but I feel we should retain Copy to Clipboard and Mark as unread.

**Comment by Puneet-here** [comment] 2022-09-26 06:23
The reason I am suggesting this is that we are going to have more new actions then we will have to disable them as well and we are rendering too much code for actions in archived chat messages, I agree that Copy to Clipboard can be useful but most of the people use web and desktop so they can copy the message by selecting the text. However not sure how much useful Mark as unread will be in the archived chats. I think it's rare for someone to visit archived chats.

**Comment by mananjadhav** [comment] 2022-09-28 05:02
@stitesExpensify Bump on the [comment here](https://github.com/Expensify/App/issues/11079#issuecomment-1257079895)

**Comment by stitesExpensify** [comment] 2022-09-28 16:26
> Also I'll leave it to @stitesExpensify if we should just pass the report object instead of isArchivedRoom. I am fine with both.

I think passing `isArchivedRoom` is fine. @sobitneupane go ahead and apply for the job on upwork!

**Comment by adelekennedy** [comment] 2022-10-10 15:53
Not overdue! It looks like this was deployed to staging.

**Comment by mananjadhav** [comment] 2022-10-18 17:53
Accepted @adelekennedy

**Comment by adelekennedy** [comment] 2022-10-18 18:23
@Puneet-here nearly missed the reporting bonus - will you apply as well?

**Comment by Puneet-here** [comment] 2022-10-18 18:37
I have applied to the job. Thank you.

**Comment by stitesExpensify** [comment] 2022-10-21 15:08
This is ready to be paid out, right?

**Comment by mananjadhav** [comment] 2022-10-21 15:11
I as paid here and I am assuming Sobit was paid too. Guessing reporting bonus is pending.

**Comment by sobitneupane** [comment] 2022-10-21 15:18
I was also paid.

**Comment by Puneet-here** [comment] 2022-10-21 16:12
> Guessing reporting bonus is pending

Yes, it's pending.

cc: @adelekennedy

**Comment by adelekennedy** [comment] 2022-10-24 15:52
paid and complete!

**Closed by adelekennedy** 2022-10-24 15:52 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
