### ISSUE TITLE
[$125] Attachment - Keyboard shows up with delay after canceling taking photo flow

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47082] opened 2024-08-08 14:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4829914
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app and log in
2. Select any chat
3. Tap the + button > Add attachment > Take photo
4. Close the camera or tap the back button

## Expected Result:
The keyboard shows up right after exiting camera

## Actual Result:
The keyboard shows up with a delay, the grey area instead of the keyboard is displayed briefly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1dc9666a-6566-42c2-88d4-d6f79182e2bc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b1d8e65cdd9c8c7</li>
        <li>Upwork Job ID: 1823386646555076621</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103753396</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by izarutskaya** [comment] 2024-08-08 14:55
We think this issue might be related to the  #vip-vsb

**Comment by sakluger** [comment] 2024-08-13 15:50
I'm not sure how complex this one is, but it looks like it might be pretty simple to fix. I'm going to set the price to $125, but I am open to increasing the price if it's more complex.

**Comment by eh2077** [comment] 2024-08-16 16:31
The root cause of this keyboard issue is subtle. So, I need to spend sometime to understand it.

**Comment by eh2077** [comment] 2024-08-19 15:28
@sakluger There should be a proposal posted above right? I'm going to review it but I found it was deleted by the author.

**Comment by sakluger** [comment] 2024-08-19 16:51
Yeah, I remember seeing a proposal posted on this issue. I'm not sure where it went 🤷‍♂️

**Comment by eh2077** [comment] 2024-08-23 00:56
not overdue, still looking for proposals

**Comment by eh2077** [comment] 2024-08-27 01:37
not overdue, still looking for proposals

**Comment by rezkiy37** [comment] 2024-08-27 14:19
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by rezkiy37** [comment] 2024-08-28 14:08
I was able to reproduce this behavior, but I wouldn't say that it is a bug for my device at least. It opens quickly. @izarutskaya what device do you have? However, I am still investigating the problem.

https://github.com/user-attachments/assets/53c1047d-81d1-48ab-b360-89a5cfb5bd53

**Comment by rezkiy37** [comment] 2024-08-28 15:32
There is a [windowSoftInputMode](https://developer.android.com/guide/topics/manifest/activity-element.html) value of the Android app. This mode is responsible for the behavior of the keyboard. I would like to play with it and probably another mode is better for the app.

**Comment by rezkiy37** [comment] 2024-08-29 09:43
Firstly, I want to mention that I have the keyboard animation ([video](https://github.com/Expensify/App/issues/47082#issuecomment-2315426784)) on my real Android device. It looks fine. I use the default keyboard. However, the keyboard appears roughly on your [video](https://github.com/Expensify/App/issues/47082#issue-2456017586). As I can see, it seems like not a default keyboard. Can you please confirm it? If I am right, please retest on a default one for your device. Moreover, please retest on other devices to confirm if the bug is replicable. 

**What's about the technical questions:**

There is a native behavior of the keyboard on Android. It is specified right here in `AndroidManifest.xml`:

https://github.com/Expensify/App/blob/b9af3d1f7ab160f7d817102d081b0e6186ba2d02/android/app/src/main/AndroidManifest.xml#L32

Android doc [says](https://developer.android.com/guide/topics/manifest/activity-element.html#wsoft): 

> _"adjustResize" - The activity's main window is always resized to make room for the soft keyboard on screen._ 

The grey area is due to the app resizing. It is expected behavior.

Regarding the Exfy app, this prop was set since the app initialization [here](https://github.com/rezkiy37/Expensify/commit/798eed62e0c59634afb9b9840f16d826289d3f42#diff-63272c98a6330850888e633b43ba4c9decee6431a115e0d2731564838eaa1d1d) **4 years ago**. This behavior has been going on for a considerable amount of time. 

**What's about the solutions to fix:**

1. Do not focus the input after interactions with those modals. Moreover, it is not clear why the app opens the keyboard if it was closed before the interactions. 

<details><summary>Videos</summary>

https://github.com/user-attachments/assets/d3505330-911e-4f2d-9e4d-121c027771fb

</details> 

I checked other messengers like Telegram and What's Up and they don't open the keyboard then if the user clicks on attachments to invoke modals on IOS at least. It works pretty smoothly.

<details><summary>Videos</summary>

https://github.com/user-attachments/assets/bcd8dd7b-87be-47fb-b553-14615cc8999f

https://github.com/user-attachments/assets/22cb43ff-2ab6-467e-bea5-809ba70a2110

</details> 

3. Change the native property to `adjustPan`. The doc says: 

> _"adjustPan" - The activity's main window isn't resized to make room for the soft keyboard. Rather, the contents of the window automatically pan so that the current focus is never obscured by the keyboard, and users can always see what they are typing. This is generally less desirable than resizing, because the user might need to close the soft keyboard to get at and interact with obscured parts of the window._

It means the keyboard behavior would be similar to IOS. However, this change requires adjusting `KeyboardAvoidingView` and testing all pieces where the app uses inputs and the keyboard.

<details><summary>Video</summary>

https://github.com/user-attachments/assets/526fb6d1-112d-47ff-a8f3-af36bca54378

</details> 

**Summury**

Please do not consider this comment as a proposal. It contains my questions and investigations. It is still not clear how should go here. So I would like to ask @mountiny as well. @sakluger @izarutskaya @eh2077 WDYT?

**Comment by sakluger** [comment] 2024-08-30 17:22
@rezkiy37 thanks for investigating - I assigned you on the issue.

I'll bump @izarutskaya in Slack to let them know we would like a retest.

**Comment by mountiny** [comment] 2024-09-02 11:21
I think we can do 1. in this case. I dont think we have to focus to the composer when the attachement or image picker is closed.

**Comment by mvtglobally** [comment] 2024-09-02 12:59
Still reproducible on Pixel 6 / Android 14

https://github.com/user-attachments/assets/dcd77a84-16d0-4f68-85ae-171c5fb1d76c

**Comment by rezkiy37** [comment] 2024-09-02 14:35
@mvtglobally, please answer the [questions](https://github.com/Expensify/App/issues/47082#issuecomment-2317177612) above:

> ...As I can see, it seems like not a default keyboard. Can you please confirm it? If I am right, please retest on a default one for your device. Moreover, please retest on other devices to confirm if the bug is replicable....

I'd like to know how many devices have this bug because I have different keyboard behavior.

**Comment by rezkiy37** [comment] 2024-09-02 15:03
Okay, guys. I will prepare a proposal and post it tomorrow 🙂

**Comment by eh2077** [comment] 2024-09-02 21:00
Not overdue as the team has decided how to move forward with this issue.

**Comment by rezkiy37** [comment] 2024-09-03 11:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

When the user opens modals (_menu items, attachment options, and emojis_), the keyboard shows up with a delay, the grey area instead of the keyboard is displayed briefly.

### What changes do you think we should make in order to solve the problem?

Do not focus `Composer` after interactions with those modals (_menu items, attachment options, and emojis_). 

<details><summary>Video</summary>

https://github.com/user-attachments/assets/63b60309-57f3-4821-85f2-493097f4cef1

</details> 

I checked other messengers like Telegram and What's Up and they don't open the keyboard then if the user clicks on attachments to invoke modals on IOS at least. It works pretty smoothly.

<details><summary>Videos</summary>

https://github.com/user-attachments/assets/bcd8dd7b-87be-47fb-b553-14615cc8999f

https://github.com/user-attachments/assets/22cb43ff-2ab6-467e-bea5-809ba70a2110

</details> 

### What alternative solutions did you explore? (Optional) 
Change the native property to adjustPan. The doc says:

> _"adjustPan" - The activity's main window isn't resized to make room for the soft keyboard. Rather, the contents of the window automatically pan so that the current focus is never obscured by the keyboard, and users can always see what they are typing. This is generally less desirable than resizing, because the user might need to close the soft keyboard to get at and interact with obscured parts of the window._

This means that the keyboard behavior is similar to that of IOS. However, this change requires adjusting `KeyboardAvoidingView` and testing all pieces where the app uses inputs and the keyboard. It is too big of a change to justify fixing this bug, as we will have to check every place that interacts with the keyboard and will possibly create other issues we aren’t aware of.

**Comment by rezkiy37** [comment] 2024-09-03 16:23
Hey!
I will be OOO from 04.09 (_afternoon_) till 09.09. I will continue to work on this one once I am back.

**Comment by rezkiy37** [comment] 2024-09-04 07:09
Hey!
I've opened PR (https://github.com/Expensify/App/pull/48415) for review (_in order of my proposal (https://github.com/Expensify/App/issues/47082#issuecomment-2326318309)_) because I will be OOO this week. So if C+ approves the proposal please start to review the PR then.

**Comment by eh2077** [comment] 2024-09-04 07:42
@rezkiy37 I'll be able to review the PR by the EOD, so it's a bit rushed for us to get it merged before you're ooo. At the first glance, we fix it by removing lines and chances look good to me. While the issue relates to composer focusing is usually subtle, so I'll need to do more testing on this. 

I think we can wait until you're back from leave because it doesn't seem like an urgent issue.

**Comment by rezkiy37** [comment] 2024-09-04 08:05
@eh2077, it makes sense. So you can test it and we will merge it next week 🙂

**Comment by rezkiy37** [comment] 2024-09-09 11:29
Hey! 
I am back 🙂

**Comment by eh2077** [comment] 2024-09-09 12:00
@rezkiy37 If open the camera from the camera icon of attachment options, then WhatsApp will focus back the keyboard and there's a delay too, see


https://github.com/user-attachments/assets/1f61efd7-14cd-486d-bdbb-9c458cb1a1e9

**Comment by tylerkaraszewski** [comment] 2024-10-01 01:06
Why did I get assigned to this now? Seems like it's already done?

**Comment by rezkiy37** [comment] 2024-10-01 09:05
Yes, the PR was merged. We can go ahead and close the issue.

**Comment by sakluger** [comment] 2024-10-10 16:19
Hey @eh2077, you are definitely eligible for payment. Thanks for letting us know, and sorry for missing that.

**Comment by sakluger** [comment] 2024-10-10 16:19
Summarizing payment on this issue:

Contributor+: @eh2077 $125, please request on Newdot

**Closed by sakluger** 2024-10-10 16:19 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by eh2077** [comment] 2024-10-10 16:43
Requested in NewDot

**Comment by JmillsExpensify** [comment] 2024-10-11 09:35
$125 approved for @eh2077
