### ISSUE TITLE
[$250] [Search v2.2] – All messages from pinned chat are displayed in search pinned section

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49570] opened 2024-09-21 12:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49186
**Email or phone of affected tester (no customers):** gocemate+a2244@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to LHN> Pin any 1:1 chat that have messages from other user
2. Go to Search> Chat> Pinned
3. Take a look at chats in this section> Open few messages and take a look at the green line

## Expected Result:
Pinned chat should be present in Pinned section and when open a message green line should remain on the first unread message

## Actual Result:
All messages between users from pinned chat are displayed in search pinned section. When open few messages green line change it's position

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bb0a7573-0660-4eac-8eac-b974961ca548

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838084013513034465</li>
        <li>Upwork Job ID: 1838084013513034465</li>
        <li>Last Price Increase: 2024-09-30</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 104082378</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by luacmartins** [comment] 2024-09-22 23:06
I don't think this is a deploy blocker. All messages showing up is the expected behavior. Only thing that needs to be fixed is the unread marker jumping around.

**Comment by luacmartins** [comment] 2024-09-22 23:06
I can take this issue as part of the Search project

**Comment by luacmartins** [comment] 2024-09-23 07:50
@abzokhattab as I mentioned [here](https://github.com/Expensify/App/issues/49570#issuecomment-2367005805), that part is expected. We should only fix the unread marker jumping around.

**Comment by QichenZhu** [comment] 2024-09-24 12:56
Looks like @wildan-m's [proposal](https://github.com/Expensify/App/issues/47735#issuecomment-2301619030) on another issue can fix the unread maker issue here.

**Comment by wildan-m** [comment] 2024-09-25 23:36
@rayane-djouah sure. Thanks for mentioning that @QichenZhu

**Comment by wildan-m** [comment] 2024-09-26 01:39
/## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

We are not updating unread marker time when the last unread report action deleted

### What changes do you think we should make in order to solve the problem?

We can update unread marker time when some of the report actions deleted, we can add new condition to indicate some report action deleted add this condition: `mostRecentReportActionCreated >= prevMostRecentReportActionCreated`

Change [this code](https://github.com/Expensify/App/blob/21e519cce7c6d6a92e0c6a5e8f0802339171053a/src/pages/home/report/ReportActionsList.tsx#L265-L278) to:

```tsx
    const mostRecentReportActionCreated = sortedVisibleReportActions[0]?.created ?? '';
    const prevMostRecentReportActionCreated = usePrevious(mostRecentReportActionCreated);
    useEffect(() => {
    
        if (unreadMarkerReportActionID) {
            return;
        }
    
    
        if (mostRecentReportActionCreated <= unreadMarkerTime && mostRecentReportActionCreated >= prevMostRecentReportActionCreated) {
            return;
        }
    
        setUnreadMarkerTime(mostRecentReportActionCreated);
```

### What alternative solutions did you explore? (Optional)

To maintain the unread marker visible after repeated search clicks, `lastReadTime` should not be updated in `openReport`. A backend modification is needed to introduce a new parameter `shouldUpdateLastReadTime` set to true for routes other than `SCREENS.SEARCH.REPORT_RHP`.

Also wrap `setUnreadMarkerTime` in `src/pages/home/report/ReportActionsList.tsx` with the `REPORT_RHP` check

```tsx

    const [unreadMarkerTime, setUnreadMarkerTime] = useState(report.lastReadTime ?? '');

    const setUnreadMarkerTimeIfNotSearchReport = (lastReadTime: string) => {
        if(route.name === SCREENS.SEARCH.REPORT_RHP)
        {
            return;
        }
        setUnreadMarkerTime(lastReadTime)
    }


```

**Comment by wildan-m** [comment] 2024-09-26 01:41
[Proposal Updated](https://github.com/Expensify/App/issues/49570#issuecomment-2375566668)

- adjust solution with latest source code link
- Add alternative solution

**Comment by luacmartins** [comment] 2024-10-01 01:30
@rayane-djouah let me know what you think of the updated proposal https://github.com/Expensify/App/issues/49570#issuecomment-2375568811

**Comment by luacmartins** [comment] 2024-10-02 18:50
Cool, I agree. Let's close this out once @IuliiaHerets confirms.

**Comment by IuliiaHerets** [comment] 2024-10-02 20:31
@luacmartins This bug report contains two issues.
1. All messages are displayed in Pinned section ( not sure if that's expected, it is still repro)
2. Green line appears on every open message from pinned chats (this is not repro any more)

https://github.com/user-attachments/assets/15f7d99f-e44b-48c0-bb27-d033ca10cbd8

**Comment by luacmartins** [comment] 2024-10-02 20:33
Thanks for confirming! 

>All messages are displayed in Pinned section ( not sure if that's expected, it is still repro)

Yes, this is expected

**Comment by luacmartins** [comment] 2024-10-02 20:33
Cool, seems like the issue here is resolved. Closing.

**Closed by luacmartins** 2024-10-02 20:33 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
