### ISSUE TITLE
[HOLD] [$1000] "Get secure link"(Personal information Step 3 of 5) page's data is disappeared when resize the browser

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22185] opened 2023-07-04 15:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Click to Avatar (settings) > Workspaces > Any Workspace > Cards > Connect Bank Account > Connect manually > Reach 3rd step (Passport & Driver's License) > Select Passport or Driver License >  Get Secure Link btn
3. Resize the browser
## Expected Result: 
"Get secure link"(Personal information Step 3 of 5) page's data shouldn't be disappeared when resize the browser
## Actual Result: 
"Get secure link"(Personal information Step 3 of 5) page's data is disappeared when resize the browser

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (3).webm](https://github.com/Expensify/App/assets/43996225/1b588da0-c126-4533-a116-fe24fb5ae0ce)

https://github.com/Expensify/App/assets/43996225/3511ba7a-e2a0-4649-9894-928e8f12adae

**Expensify/Expensify Issue URL:**
**Issue reported by:** @muxriddinmuqimov77
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688382201123319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0189835f2cbc119f38</li>
        <li>Upwork Job ID: 1676277453289750528</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by rain2o** [comment] 2023-07-05 09:47
I suspect this is related to #20404. I've seen [other bugs with similar behavior put on hold](https://github.com/Expensify/App/issues/20929#issuecomment-1620639129) to see if fixing the underlying bug will resolve all of these.

**Comment by wildan-m** [comment] 2023-07-05 10:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

There are two issues here:
1. Onfido page is reloaded when the window resized
2. The embedded Onfido page is hidden after resized with a width under 600px

### What is the root cause of that problem?
1. `StackNavigator` change `isSmallScreenWidth` prop that can cause the component re-mounted. A better explanation can be found [here](https://github.com/Expensify/App/issues/20404).
2. We customize onfido inner container height with a percentage to avoid cut-off here

https://github.com/Expensify/App/blob/15e547e3bceeb7bfe693f78fc8b90fdc28b1b32f/src/components/Onfido/index.css#L21-L24

I don't know why it's not hidden when we specify the height with px instead of %

### What changes do you think we should make in order to solve the problem?

For the first issue, I think we should wait for [this discussion result](https://app.slack.com/client/T03SC9DTT/C01GTK53T8Q/thread/C01GTK53T8Q-1687994616.930989).

If we can separate the issue, then I can provide a solution for the second issue.

We can solve the second issue by adding `flex-grow:1` to the onfido container.

the `flexGrow1` property can be put directly into this `div`

https://github.com/Expensify/App/blob/15e547e3bceeb7bfe693f78fc8b90fdc28b1b32f/src/components/Onfido/BaseOnfidoWeb.js#L127

we can directly set style there or add and extract `containerStyle` props there if required

or we can also add it to the [index.css](https://github.com/Expensify/App/blob/main/src/components/Onfido/index.css).

```
#onfido-mount{
    flex-grow: 1;
}
```

### What alternative solutions did you explore? (Optional)
We can set the height percentage as pixel [here](https://github.com/Expensify/App/blob/15e547e3bceeb7bfe693f78fc8b90fdc28b1b32f/src/components/Onfido/index.css#L21-L24).

**Comment by b4s36t4** [comment] 2023-07-06 05:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Get secure link"(Personal information Step 3 of 5) page's data is disappeared when resize the browser
### What is the root cause of that problem?

Interpretation of mobile width. In `index.css` we're making modal height `92%` for mobile which is having media query for `max-width: 600px` but onfido uses media query of `max-width: 479px` if we resize the window to any size in between these width ranges we don't see the action buttons from onfido.


### What changes do you think we should make in order to solve the problem?

We should follow the same media query onfido is following. Main reason for adding this `height: 92%` is to override the onfido making `height: 100%` but it only happening below screensize of 479px. To match with the same we should use same media query as onfido does.

https://github.com/Expensify/App/blob/41eb9ba94b7540e70b4a700cda98bbe7f586bdcf/src/components/Onfido/index.css#L19 We need to update the media query to `max-width: 479px` in this file.
 
<img width="443" alt="Screenshot 2023-07-06 at 10 47 14 AM" src="https://github.com/Expensify/App/assets/59088937/f3b32d09-1be7-4b9e-9dc0-5b63a7c06b28">


### What alternative solutions did you explore? (Optional)
NA

**Comment by dylanexpensify** [comment] 2023-07-07 08:42
@parasharrajat where's the conversation heading, can you update here? Will put on hold for now!

**Comment by dylanexpensify** [comment] 2023-07-10 09:41
Nice, so hold still applies, yes?

**Comment by dylanexpensify** [comment] 2023-07-12 08:42
Still on hold

**Comment by dylanexpensify** [comment] 2023-07-17 09:17
Still on hold! Moving to weekly

**Comment by dylanexpensify** [comment] 2023-07-26 07:50
Hold - @parasharrajat any eta on when we can remove the hold?

**Comment by dylanexpensify** [comment] 2023-08-04 12:10
on hold

**Comment by dylanexpensify** [comment] 2023-08-11 20:01
on hold

**Comment by dylanexpensify** [comment] 2023-08-18 19:15
on hold

**Closed** 2023-09-19 10:13 UTC
Labels: External, Monthly, Help Wanted, Overdue, Bug
