### ISSUE TITLE
Web - Emoji - Emojis picker window overlaps with the compose box

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10089] opened 2022-07-25 22:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Access any chat you prefer
3. Click on Emoji

## Expected Result:
The emojis window should not overlap the compose box

## Actual Result:
The emojis window overlaps the compose box

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.86-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** any
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5662760_Untitled](https://user-images.githubusercontent.com/43996225/180886260-e56fc801-a508-4511-9c76-6afd560458d4.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment] 2022-07-26 20:09
Looks like the screenshots were approved by the design team in [this PR](https://github.com/Expensify/App/pull/7580), and there haven't been any regressions to its position since then, so I'm going to close this as expected behavior.

**Closed by amyevans** 2022-07-26 20:09 UTC
Labels: Engineering, Daily
