### ISSUE TITLE
[HOLD for payment 2023-09-08] [$1000] mWeb - Chat - Hide the keyboard on click of confirm button

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25570] opened 2023-08-21 10:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat and send password protected pdf
2. click on PDF and type wrong password
3. click on confirm button

[example protected PDF.pdf](https://github.com/Expensify/App/files/12428724/example.protected.PDF.pdf)
Password: `25570`

## Expected Result:
Should not hide the keyboard same as native app

## Actual Result:
Keyboard hides and user have to click on input field to open keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/bae36a1b-cd7b-4efc-900a-8b6141692559

https://github.com/Expensify/App/assets/115492554/e46fba83-0dac-449f-93a6-843d31bab57e

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691657367673159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0130b6dd1d51afa360</li>
        <li>Upwork Job ID: 1694669713222795264</li>
        <li>Last Price Increase: 2023-08-24</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26322364</li>
<li>alitoshmatov | Contributor | 26322365</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-08-21 10:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - Chat - Hide the keyboard on click of confirm button
### What is the root cause of that problem?
When button is pressed, text input is losing focus.
### What changes do you think we should make in order to solve the problem?
We can add 
```
  onMouseDown={e=>e.preventDefault()}
``` 
to keep focus in textinput like we are doing in other places.
We add above code to confirm button here:
https://github.com/Expensify/App/blob/70000a49ea00e48e6c81c5184dc1d42d8f0cbff7/src/components/PDFView/PDFPasswordForm.js#L134-L140


### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment] 2023-08-24 03:53
Reassigning another Bug team member: I realized that this one still needs to be reassigned and I'm OOO until Monday, August 28. 😞 I will take it back if it's still open by my return date. 

Required action from the team: I ran out of time and have not tested this one. To avoid delaying the process, I've reassigned to test and confirm if there is a bug here. Thanks!

**Comment by conorpendergrast** [comment] 2023-08-24 11:15
Looking good!

**Comment by cubuspl42** [comment] 2023-08-25 08:33
The solution by @alitoshmatov is straight to the point.

@tienifr I appreciate the effort to clarify the code but I'm not convinced by the suggested approach. Adding a property strictly related to the keyboard feels over-specific; if anything, it should be related to _focusing_. But that assumes that (un)focusing is the only default User Agent effect of pressing the button, while I'm not completely sure whether it's the case. In short, I agree that the `preventDefault` contract is a bit unclear, and using it can require a comment, but I'm not sure whether something can be done about it.

I suggest we go with @alitoshmatov here.

C+ reviewed 🎀 👀 🎀

**Comment by alitoshmatov** [comment] 2023-08-28 06:57
Sorry for the delay, PR is ready - https://github.com/Expensify/App/pull/26025

**Comment by alexpensify** [comment] 2023-08-30 01:30
Thanks for the update here @alitoshmatov. 

@conorpendergrast - you are a legend, I'm back online and will keep moving this one forward.

**Comment by cubuspl42** [comment] 2023-09-02 08:25
https://github.com/Expensify/App/pull/9141/files#r1313778917

- The PR that introduced the bug has been identified. Link to the PR:
    - https://github.com/Expensify/App/pull/9141
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - https://github.com/Expensify/App/pull/9141/files#r1313778917
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No need for a new regression test
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by cubuspl42** [comment] 2023-09-02 08:25
- The PR that introduced the bug has been identified. Link to the PR:
    - https://github.com/Expensify/App/pull/9141
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - https://github.com/Expensify/App/pull/9141/files#r1313778917
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No need for a new regression test
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by cubuspl42** [comment] 2023-09-02 21:19
@parasharrajat You're definitely right that it can also be seen that way. It's a tricky topic, as many Expensify bugs are related to some unexpected user experience, and there's no written down definitive source of truth how the app should behave. When something used to work in a more pleasant way and it _changed_, then it's easy - we have a regression! A bug. When it never worked the way we, at some point, decide is the right one; then either it was always broken, or it's just a new requirement.

But I don't think it really matters in this case... That issue is long past its regression period, so I don't think my comment did any harm... I was just doing the checklist ✓

**Comment by cubuspl42** [comment] 2023-09-03 09:47
@parasharrajat
>  It matters if we start adding wrong PRs into regression checklist.

The text of the bullet is "The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake", it doesn't mention anything about a regression explicitly. A regression is when something is working and stops. When a new feature is added with behavior that's later decided to be "wrong", it can be said that it was some kind of a mistake not to make it "right" from the beginning. As long as it's about learning, I can't see any negative consequences of my comment and you didn't mention any.

Maybe the text of the bullet is different than than the intention behind it?

> Can you please fix it?

As you don't have any direct authority over me, to the best of my knowledge, I will gladly change it when you convince me to.

**Comment by alexpensify** [comment] 2023-09-08 23:29
Here is the payment summary: 

-  External issue reporter @gadhiyamanan $250 
-  Contributor that fixed the issue @alitoshmatov $1000
-  Contributor+ that helped on the issue and/or PR @cubuspl42 $1000 

Upwork Job: https://www.upwork.com/jobs/~0130b6dd1d51afa360

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: No bonus but everyone has been paid or payment has been prepared in Upwork. Please confirm receipt and I can close. Thanks!

**Comment by alexpensify** [comment] 2023-09-11 22:05
Alright, everyone has been paid here. I'm going to close for now.

**Closed** 2023-09-11 22:06 UTC
Labels: External, Weekly, Awaiting Payment, Bug
