### ISSUE TITLE
Keyboard should be email type in New chat screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24049] opened 2023-08-02 10:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB -> New chat
2. Focus search textfield -> See keyboard
## Expected Result: 
Keyboard type should be email type
## Actual Result: 
Keyboard type is not email in new chat screen

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/948f4a23-914d-48a8-aeb0-19c372bbf211

<img src="https://github.com/Expensify/App/assets/43996225/8243ecc4-34cf-4697-b738-f3f38426f3ad" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690741484281689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-08-02 10:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Keyboard should be email type in New chat screen
### What is the root cause of that problem?
There is no prop `keyboardType={CONST.KEYBOARD_TYPE.EMAIL_ADDRESS}` in `OptionsSelector` [here](https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/pages/NewChatPage.js#L191)
### What changes do you think we should make in order to solve the problem?
Add prop `keyboardType={CONST.KEYBOARD_TYPE.EMAIL_ADDRESS}` in `OptionsSelector` [here](https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/pages/NewChatPage.js#L191)

### What alternative solutions did you explore? (Optional)
N/A

**Comment by gadhiyamanan** [comment] 2023-08-02 10:42
dupe of https://github.com/Expensify/App/issues/15917

**Comment by adelekennedy** [comment] 2023-08-02 15:43
Dupe and nab - closing

**Closed by adelekennedy** 2023-08-02 15:43 UTC
Labels: Daily, Bug
