### ISSUE TITLE
IOU - “Hmm... it’s not here...” page is open if tap on Request Money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26137] opened 2023-08-28 22:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25429
## Action Performed:
1. As user A (gmail account) request $10 from user B
2. Go to the IOU report
3. Right click or long press the IOU preview

## Expected Result:
Verify you can see "Edit Request" button

## Actual Result:
“Hmm... it’s not hereYou don’t have access to this chat” page is open if tap on Request Money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.58-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/fa24c964-c807-4636-b32f-85cd2c6f6c93

**Expensify/Expensify Issue URL:**

**Issue reported by:**. Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ayazhussain79** [comment] 2023-08-28 23:01
Dupe of https://github.com/Expensify/App/issues/26116

**Comment by luacmartins** [comment] 2023-08-28 23:04
We have [8 open issues](https://github.com/Expensify/App/issues?q=is%3Aissue+is%3Aopen+%22Hmm...+it%E2%80%99s+not+here...%22) for this, we don't need another one. Closing.

**Closed by luacmartins** 2023-08-28 23:04 UTC
Labels: Engineering, Hourly
