### ISSUE TITLE
Login - Magic code input remains highlighted when clicking outside but can't type

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27026] opened 2023-09-08 13:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the Sign in page
2. Enter your email
3. Observe that the first input of the magic code is focused (green underline)
4. Click anywhere outside of the magic code inputs
5. Observe that the first input of the magic code is still focused (green underline)
6. Press any number on the keyboard, e.g. 1
7. Observe that no number is entered into the magic code input

## Expected Result:
The magic code input should be filled with the entered number.

## Actual Result:
The magic code input is not filled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.66-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/77a783c0-3156-419e-94d5-4c3e7cd3b27f

https://github.com/Expensify/App/assets/115492554/b8320115-3a44-493c-8bd9-6730931bc1b0

**Expensify/Expensify Issue URL:**

**Issue reported by:** @samh-nl

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693319251825219
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ishpaul777** [comment] 2023-09-08 14:01
dupe of https://github.com/Expensify/App/issues/18244

**Comment by zanyrenney** [comment] 2023-09-11 10:45
Closing due to dupe.

**Closed by zanyrenney** 2023-09-11 10:45 UTC
Labels: Daily, Overdue, Bug
