### ISSUE TITLE
Login - The email field is cleared after the login page update

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19692] opened 2023-05-26 19:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19512

## Action Performed:
1. Open URL https://staging.new.expensify.com/
2. Check if your email is automatically filled
3. Refresh the page

## Expected Result:
The email field NOT cleared

## Actual Result:
The email field is cleared

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/0a456a5c8ce0d4087453b86bd635f9f8c99ae14cccf8719dc8a8627299cd23ed

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by therealsujitk** [comment] 2023-05-27 11:52
I don't think this is a bug, it's intended behaviour. Maybe this should be a feature request?

**Comment by hungvu193** [comment] 2023-05-29 10:09
Similar one here: https://github.com/Expensify/App/issues/19382
It was decided to closed.

**Comment by luacmartins** [comment] 2023-05-29 19:39
Thanks for the input everyone! I agree this is not a bug. Closing.

**Closed by luacmartins** 2023-05-29 19:39 UTC
Labels: Daily, Overdue, Bug
