### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] Android - LHN - When quickly clicking on different chats on LHN it opens one by one

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20517] opened 2023-06-09 14:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Quickly clicking on different chats on LHN

## Expected Result:
Only the first chat opens after quickly clicking on different chats on LHN

## Actual Result:
When quickly clicking on different chats on LHN it opens one by one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/716d2407-8c1d-43dc-8f2b-133784035e17

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e43b1f085016d112</li>
        <li>Upwork Job ID: 1669122882913021952</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2023-06-12 10:06
Hey @arielgreen - I'm sorry - this one came in over my weekend and I didn't get a chance to reproduce before heading OOO. If you can, could you please run through the bug process? I'll stay assigned in case there's anything for me to pick up on 20 June when I'm back!

**Comment by arielgreen** [comment] 2023-06-14 23:22
@stitesExpensify can you confirm if this can be fixed externally or if it needs to be moved internal? 

I _think_ it's okay for external but I would appreciate a second check.

**Comment by developerdavi** [comment] 2023-06-15 00:05
Hey! I applied for the job via Upwork. Do I need to do something or just wait for you guys review it?

**Comment by developerdavi** [comment] 2023-06-15 00:10
Contributor details
Your Expensify account email: developer.davi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014daee03ebd13895a

**Comment by mananjadhav** [comment] 2023-06-15 05:29
Thanks @tienifr for the proposal. Your root cause seems to be correct. What I didn't understand:

1. `Navigation.getTopmostReportId()` isn't it needed to be compared to some reportID? Are we just checking the existence?
2. Your video shows you clicked on about 4-5 reports in LHN and ideally it should've opened the last one clicked? (if my guess is right, #announce room). But yours shows something in middle opened?

**Comment by mananjadhav** [comment] 2023-06-15 05:40
Okay thanks for clarifying I got confused between the first and the second chat. I just saw IOU amount 559 to identify the reports. Considering the expected result @tienifr's proposal looks good to me.

@stitesExpensify All yours.

**Comment by stitesExpensify** [comment] 2023-06-15 19:58
@developerdavi please check out our contributing guidelines [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to see how the hiring process works!

**Comment by arielgreen** [comment] 2023-06-19 22:37
Reassigning, team change

**Comment by stitesExpensify** [comment] 2023-06-20 15:43
@kadiealexander same question :D https://github.com/Expensify/App/issues/20517#issuecomment-1593658017

**Comment by sophiepintoraetz** [comment] 2023-06-22 00:38
@stitesExpensify - for the briefest of moments my instinct is that the _last_ chat clicked should open but I can't articulate why. I'm going to double-check in [#contributor-plus](https://expensify.slack.com/archives/C02NK2DQWUX/p1687394293587839)

**Comment by sophiepintoraetz** [comment] 2023-06-23 04:01
Still discussing in slack.

**Comment by ShogunFire** [comment] 2023-06-25 20:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When clicking multiple report quickly they all open one by one

### What is the root cause of that problem?

The root cause is that in SidebarLink here https://github.com/Expensify/App/blob/23ca9a7907738e0bd0e0ad53957946097b090b94/src/pages/home/sidebar/SidebarLinks.js#L145 
We navigate to the report without checking if there are other reports that have been clicked recently

### What changes do you think we should make in order to solve the problem?


I think we should create a new variable lastReportOpening where we store the last report that has been clicked. 

Also when we click a report, instead of opening it right away we can set a timeout and only open lastReportOpening in x ms for example 200ms. 

We only open a report if are not already in a report. We can do all that with the following code:


```
this.lastReportOpening  = option.reportID

setTimeout(
    () => {
        if (!Navigation.getTopmostReportId()){
                  Navigation.navigate(ROUTES.getReportRoute(this.lastReportOpening ));
                  this.props.onLinkClick();
              }
          },
          1000,
      );
```

Result with 1000ms which is a lot:




https://github.com/Expensify/App/assets/19537677/53bfa0d7-47f6-49ae-830c-74e08da1587e







### What alternative solutions did you explore? (Optional)

**Comment by ShogunFire** [comment] 2023-06-25 20:08
@sophiepintoraetz Hello, I have done a different proposal in case it is decided to open the last report clicked and not the first.

Also to say that I have been able to reproduce on web chrome even if it's harder to reproduce

**Comment by sophiepintoraetz** [comment] 2023-06-25 22:44
In slack, we agreed that the behaviour should be:
>I agree with showing the first chat clicked and disabling the next clicks.

@mananjadhav - would you mind reviewing the proposals? 🙏

**Comment by ShogunFire** [comment] 2023-06-25 23:34
## Proposal
[Updated](https://github.com/Expensify/App/issues/20517#issuecomment-1606247760)

**Comment by ShogunFire** [comment] 2023-06-25 23:36
I updated my proposal to navigate to the first chat only

**Comment by mananjadhav** [comment] 2023-06-27 10:11
thanks for the ping @sophiepintoraetz. I still think @tienifr's proposal is better than using timeout or debounce. 

🎀 👀 🎀 C+ reviewed.

**Comment by ShogunFire** [comment] 2023-06-27 11:09
Hello @mananjadhav , I don't agree that @tienifr proposal is better, for me it was creating a big regression on platforms like web that can have both the LHN opened and the report opened because once you have a report opened, getTopMostReportId will return something and, clicking on other reports in the LHN never opens them even if you click on them 5s later.

Also I think debounce is basically made for that kind of cases where an.action takes some time and you don't want to do the action multiple times  before the first time is finished

**Comment by ShogunFire** [comment] 2023-06-27 11:20
@tienifr As I said here https://github.com/Expensify/App/issues/20517#issuecomment-1606248496 I reproduced this on web too so your solution wouldn't resolve the bug on every platforms

**Comment by Julesssss** [comment] 2023-06-27 12:40
Yeah, I'd agree that this issue is more relevant to mobile.

**Comment by Julesssss** [comment] 2023-06-27 12:41
I am still learning hooks, but is it not possible to use `useEffect` or something similar instead of `setTimeout`?

**Comment by ShogunFire** [comment] 2023-06-27 12:42
> Yeah, I'd agree that this issue is more relevant to mobile.

I agree with that too now that I am testing more. But I still prefer my debounce solution :P

**Comment by Julesssss** [comment] 2023-06-27 12:48
The trouble with debounce is that we need to specify ms and it will never handle every possible case.

**Comment by sophiepintoraetz** [comment] 2023-06-29 01:23
Did we reach a conclusion here @mananjadhav / @Julesssss on which proposal to go with? Or do we need to take this discussion elsewhere to move it forward?

**Comment by ShogunFire** [comment] 2023-06-29 02:05
Hello @sophiepintoraetz , I think @mananjadhav  made his decision here https://github.com/Expensify/App/issues/20517#issuecomment-1609205316 , I shouldn't have argued after that but I was worried about the regression on big screen, since @tienifr confirmed that this proposal would only be applied on small screen I think @mananjadhav will not change his decision. Sorry for the waste of time...

**Comment by Julesssss** [comment] 2023-06-29 08:30
No worries!

**Comment by Julesssss** [comment] 2023-06-29 08:31
@stitesExpensify just realized I took this from you at some point... I blame auto-assignment.

**Comment by mananjadhav** [comment] 2023-07-06 20:23
PR is being tested.

**Comment by mananjadhav** [comment] 2023-07-10 16:27
C+ Review done on the PR.

**Comment by mananjadhav** [comment] 2023-07-19 16:49
I checked for this one. I can't attribute this to any specific PR as this is more of a performance issue. Neither do I think we need a regression test as this is specifically failing for Android, and unlikely to change.

**Comment by mananjadhav** [comment] 2023-07-20 02:14
@stitesExpensify For this one, I would request the timeline bonus be applied to just @tienifr. I was unexpectedly OOO and couldn't get to this sooner.  It would've been closed sooner if I were able to get to it. Can we work that out?

**Comment by stitesExpensify** [comment] 2023-07-20 13:47
That makes sense to me CC @sophiepintoraetz. Thank you for the context @mananjadhav

**Comment by sophiepintoraetz** [comment] 2023-07-21 03:47
All right - offer sent!

**Closed by sophiepintoraetz** 2023-07-21 03:47 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by anmurali** [comment] 2023-07-21 19:08
Approved $1000 to Manan based on above.
