### ISSUE TITLE
[REPORTING BONUS PAYMENT] [$250]  IOU - The number of requests in IOU comment increases by one after paying IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24421] opened 2023-08-11 12:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Have User A request money two times from User B
3. As User B, go to the IOU and select Pay elsewhere

## Expected Result:
The number of requests does not change

## Actual Result:
The number of requests changes from two to three. The behaviour we are seeing is that a paid message is considered as a request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/80096e2b-9fe7-45cc-aa0d-8b84a40bb3a8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team / @tymatein

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f16a485984ea234</li>
        <li>Upwork Job ID: 1690875737961791488</li>
        <li>Last Price Increase: 2023-08-23</li>
    </ul>
</details>

**Comment by tymatein** [comment] 2023-08-11 13:12
Originally reported by https://expensify.slack.com/archives/C049HHMV9SM/p1691614025611059

**Comment by tymatein** [comment] 2023-08-11 13:17
Contributor details
Your Expensify account email: tymatein@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01baf1de6864df6df3

**Comment by jliexpensify** [comment] 2023-08-13 23:56
Yep, can reproduce this!

![image](https://github.com/Expensify/App/assets/30815269/9ca2e207-08ef-492e-9f15-5b76cf1ba40f)

**Comment by pbkompasz** [comment] 2023-08-14 06:51
BE issue. The created report has the same `childMoneyRequestCount` value as `childCommenterCount`.

![Screenshot from 2023-08-14 09-49-27](https://github.com/Expensify/App/assets/47194071/c1683449-c754-4e25-8fe1-4cbbf4c74d85)

**Comment by alitoshmatov** [comment] 2023-08-14 07:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The number of requests in IOU comment increases by one after paying IOU
### What is the root cause of that problem?
In [`payMoneyRequest`](https://github.com/Expensify/App/blob/8131df576b10bd4ff2b89d4affd1a4b717f1cfd3/src/libs/actions/IOU.js#L1450) we are calling which is calling `getPayMoneyRequestParams` and it is calling [`updateReportPreview`](https://github.com/Expensify/App/blob/8131df576b10bd4ff2b89d4affd1a4b717f1cfd3/src/libs/actions/IOU.js#L1261)

Here we are increasing `childMoneyRequest` to +1
https://github.com/Expensify/App/blob/a03a21d25832760cf9db4235b0fbc88cc08bd490/src/libs/ReportUtils.js#L1908

The same issue is also happening in the backend where `PayMoneyRequestWithWallet` or `PayMoneyRequest` requests are increasing `childMoneyRequest` count

### What changes do you think we should make in order to solve the problem?
We should remove `+1` here
https://github.com/Expensify/App/blob/a03a21d25832760cf9db4235b0fbc88cc08bd490/src/libs/ReportUtils.js#L1908
And also fix it from backend

### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment] 2023-08-16 05:04
Will review this today.

**Comment by mananjadhav** [comment] 2023-08-16 13:29
I think we should first fix this from backend, and then take a look at this issue.

Tagging an internal engineer here.

🎀 👀 🎀 C+ reviewed.

**Comment by arosiclair** [comment] 2023-08-16 15:12
Yeah this does look like a backend issue. Reaching out internally for somebody who my have worked on this recently.

**Comment by arosiclair** [comment] 2023-08-17 20:16
No response. I'll take a look at this in a bit

**Comment by jliexpensify** [comment] 2023-08-21 04:38
Not overdue! @arosiclair as a heads up, I'm at a conference this week - if you need payments sorted, please feel free to reassign another B0 team member.

**Comment by mountiny** [comment] 2023-08-23 13:47
Made Auth PR with a fix

**Comment by mananjadhav** [comment] 2023-08-23 17:18
Okay got it. Thanks for clarifying.

**Comment by mountiny** [comment] 2023-08-25 13:34
done

**Comment by mountiny** [comment] 2023-08-25 13:35
We need to pay reporting bonus to @tymatein

**Comment by tymatein** [comment] 2023-08-25 13:41
@mountiny Thanks for thinking of me.
BTW is it enough to fix the BE only? I would expect a glitch in the UI before the response from the server is returned. But I haven't tested it.

**Comment by mountiny** [comment] 2023-08-25 15:03
I am waiting to confirm, but the latest main has dropped the `X Requests` copy for the iou preview

**Comment by jliexpensify** [comment] 2023-08-26 07:13
@tymatein can you:

1. Apply for the job here? https://www.upwork.com/jobs/~018f16a485984ea234 (I can't seem to invite you)
2. Add your Upworks name to your GH? Thanks!

**Comment by tymatein** [comment] 2023-08-26 07:41
@jliexpensify Thanks, done.

**Comment by jliexpensify** [comment] 2023-08-27 00:16
Paid, job closed!

**Closed by jliexpensify** 2023-08-27 00:16 UTC
Labels: Daily, Internal, Bug
