### ISSUE TITLE
[HOLD for payment 2023-12-15] [$500] Web - Search Term in WorkspaceMembersPage lost when clicking on Invite

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22534] opened 2023-07-09 19:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Click on workspaces
3. Click on Members
4. Search for a string till no results are found
5. Click on invite to invite this user

## Expected Result:
The TextInput now in InviteUser page should have the string searched in WorkspaceMembersPage because once no results are found for a search string in WorkspaceMembersPage the search string should be there in Invite Page so that it should not be typed again from beginning.

## Actual Result:
Search string in TextInput of InvitePage is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6e3f4e74-3882-40fa-b6cf-9bde15a1afa9

https://github.com/Expensify/App/assets/93399543/c671eb1f-4d4d-42d7-be5e-0b52748d331f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @c3024 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688895491063239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d2f1bf2a057285a</li>
        <li>Upwork Job ID: 1717179788878622720</li>
        <li>Last Price Increase: 2023-11-24</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27905086</li>
<li>DylanDylann | Contributor | 27905088</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-09 19:43
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Search string is lost when clicking on Invite members from `WorkspaceMembersPage`
### What is the root cause of that problem?
We are not passing the search string to Invite page
Presently the route for invite page in `ROUTES` is as follows:
```
getWorkspaceInviteRoute: (policyID, search) => `workspace/${policyID}/invite`
```
The Invite route is not receiving search string from `WorkspaceMembersPage`
### What changes do you think we should make in order to solve the problem?
We should change this to
```
getWorkspaceInviteRoute: (policyID, search) => `workspace/${policyID}/invite/?search=${search}`
```
so that search string is captured in route
and navigation route in `inviteUser` in `WorkspaceMembersPage` to
```
Navigation.navigate(ROUTES.getWorkspaceInviteRoute(props.route.params.policyID, searchValue));
```
and we initialize `searchTerm` in `state` of `WorkspaceInvitePage` to
```
searchTerm: props.route.params.search ||  '',
```
Similar changes can be made if we want to use the search string in invite page in `WorkspaceMembersPage`
### What alternative solutions did you explore? (Optional)

**Comment by shawnborton** [comment] 2023-07-10 12:42
Just want to comment that this is definitely not a bug, this would be a feature request. I do think it's a clever idea to maintain the search term between the manage members page and the invite page, but we should not be paying out a bounty for this one.

**Comment by shawnborton** [comment] 2023-07-10 13:02
That's a good question for our engineers, so maybe once we start taking proposals, we can sort that out.

**Comment by situchan** [comment] 2023-07-10 13:08
It was intentional to clear search in https://github.com/Expensify/App/issues/15661. But now the behavior is reversed?

**Comment by shawnborton** [comment] 2023-07-10 13:09
Oh, if that's the case then we can just close this out and consider it not a bug/feature request.

**Comment by sakluger** [comment] 2023-07-11 16:11
I'm going to close this one since it looks like we already decided to consistently clear the value.

**Comment by mallenexpensify** [comment] 2023-09-12 02:17
Dropping here for reference since I [just posted in #expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1694483913391899)

> Not really a bug nor feature request but everytime I end up on this RHP modal, I think I can add someone to the room by typing in the name/email then clicking the green invite button to invite them. (edited) 
<img width="382" alt="image" src="https://github.com/Expensify/App/assets/22508304/87865f3f-4f92-4abb-bd75-2874d814662d">

Thanks @c3024 for sharing this link. 

Should we reopen this as a feature request instead of a bug?  I have a feeling many/most people think similarly to my thoughts above.  I can take a poll in #expensify-open-source if it's be helpful.

**Comment by mallenexpensify** [comment] 2023-09-13 10:18
Reopening, removing assignees, assigned to me. Removed `Bug` label and `Daily`, added `Weekly`.  Unsure what to do next but, at least, it'll show in my K2 (GH issue list) and I'l be reminded of it every week or two

**Comment by mallenexpensify** [comment] 2023-09-26 07:09
No progress

**Comment by mallenexpensify** [comment] 2023-10-04 17:38
Competing priorities right now, hope to have time soon to look into

**Comment by mallenexpensify** [comment] 2023-10-14 00:42
Hopefully find time to get to soon

**Comment by mallenexpensify** [comment] 2023-10-25 14:03
Added `Internal` to get C+ 👀.  @ArekChr 
1. Do you agree this feature request is useful/helpful?
2. If so, do you think this can be worked on externally by a contributor?

Thx

**Comment by c3024** [comment] 2023-10-25 14:50
Since a lot has changed in almost four months, I am [updating my proposal](https://github.com/Expensify/App/issues/22534#issuecomment-1627807225) in case this issue will be worked on externally.
### What changes do you think we should make in order to solve the problem?
The broad changes we need to do are as follows:
https://github.com/Expensify/App/blob/0c2578e65e68e112185b9b19599af0a3d66fba1e/src/ROUTES.ts#L319
to
```js
getRoute: (policyID: string, search: string) => `workspace/${policyID}/invite/?search=${search}`,
```
https://github.com/Expensify/App/blob/0c2578e65e68e112185b9b19599af0a3d66fba1e/src/pages/workspace/WorkspaceInvitePage.js#L68
to
```js
const [searchTerm, setSearchTerm] = useState(props.route.params.search ||  '');
```
https://github.com/Expensify/App/blob/0c2578e65e68e112185b9b19599af0a3d66fba1e/src/pages/workspace/WorkspaceMembersPage.js#L170
to
```js
Navigation.navigate(ROUTES.WORKSPACE_INVITE.getRoute(props.route.params.policyID, encodeURIComponent(searchValue)));
```
Any fine tuning can be done in the PR.
<details>
<summary>Result</summary>


https://github.com/Expensify/App/assets/102477862/1105e314-958c-4876-83f2-0d84ab78664e






</details>

**Comment by ArekChr** [comment] 2023-10-26 10:22
@mallenexpensify I believe it would be best to consult with our design team to ensure alignment with our overall design principles and user experience goals. cc:  @Expensify/design

**Comment by shawnborton** [comment] 2023-10-26 12:01
I don't think this one is too complicated - I think the proposal is just to keep the input text from the members page and move it over to the input on the invite page once the invite button is tapped.

**Comment by mallenexpensify** [comment] 2023-11-03 23:28
Added External and Help Wanted cuz I think/hope a contributor can now work on this.

**Comment by DylanDylann** [comment] 2023-11-04 04:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Search Term in WorkspaceMembersPage lost when clicking on Invite

### What is the root cause of that problem?
We don't have the logic to save the search term in the Member Page and set it as the initial search value in the Invite Page

### What changes do you think we should make in order to solve the problem?
We need to create a new function to update searchvalue to ONYX like we did with the main composer
```
const debouncedSaveSearchTerm = useMemo(
        () =>
            _.debounce((policyID, newSearchTerm) => {
                Policy.saveSearchTerm(policyID, newComment || '');    // Also need to create new function in policy utlils
            }, 1000),
        [],
    );
```

And then we use this function to update searchTerm. In the Invite Page we need to set the new ONYX field above as initial value of search input





### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-11-04 04:18
@shawnborton @mallenexpensify Could you help to confirm these thing?
1. We agree that we will pass the search value of Member Page to Invite Page. What about the opposite flow, do you guys want to pass the search value of Invite Page to Member Page
2. When we close Member Page and Invite Page, do you guys want to reset the search value to empty?

**Comment by dubielzyk-expensify** [comment] 2023-11-05 22:20
>1. We agree that we will pass the search value of Member Page to Invite Page. What about the opposite flow, do you guys want to pass the search value of Invite Page to Member Page
>2. When we close Member Page and Invite Page, do you guys want to reset the search value to empty?

Chiming in for Shawn as he's OOO:
1) I think given it goes one way, let's make it predictable for users and make it go both ways.
2) Yes, I think a reset to empty is appropriate.

**Comment by DylanDylann** [comment] 2023-11-06 08:16
@dubielzyk-expensify 
> After refresh browser on that page, should we keep the previous search value?

How about this case ?
cc @shawnborton

**Comment by dubielzyk-expensify** [comment] 2023-11-06 10:55
I'm not sure if we do that elsewhere and I don't think it's needed for this as it's not super sensitive. If it was a long form, sure, but given it's a "add member" flow I think it's not needed

**Comment by dubielzyk-expensify** [comment] 2023-11-06 11:09
Exactly. cc @Expensify/design

**Comment by DylanDylann** [comment] 2023-11-09 08:28
@aimane-chnaif [Updated proposal](https://github.com/Expensify/App/issues/22534#issuecomment-1793332489)

**Comment by c3024** [comment] 2023-11-09 08:49
@aimane-chnaif 
Is saving to Onyx preferred to passing the string as param in URL?

**Comment by DylanDylann** [comment] 2023-11-10 10:20
@aimane-chnaif just updated proposal in section ***What alternative solutions did you explore? (Optional)***, please help check

**Comment by DylanDylann** [comment] 2023-11-14 02:03
@aimane-chnaif what about creating a global variable that mentioned in my proposal? It will auto-reset when refreshing

**Comment by DylanDylann** [comment] 2023-11-18 01:16
@aimane-chnaif 
- I think we do not need to clear the input in [this case](https://github.com/Expensify/App/issues/22534#issuecomment-1816699584) because based our above discussion, i think we just need to clear the input once we refresh page.
- Also, the need to keep the inconsistency when clicking on the deeplink that is pasted in any chat: the app states are not cleared (navigation state, current inputs, ...)

**Comment by mallenexpensify** [comment] 2023-11-21 23:48
@aimane-chnaif , what's needed to move this forward? Read above a bit but wasn't sure.

**Comment by DylanDylann** [comment] 2023-11-22 09:38
@aimane-chnaif updated proposal to match the requirement (by adding the cleanup function when [WorkspaceInvitePage ](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceInvitePage.js) unmounted ):

> When we close Member Page and Invite Page, do you guys want to reset the search value to empty
- So with this change, [your comment](https://github.com/Expensify/App/issues/22534#issuecomment-1816699584) is also fixed

**Comment by DylanDylann** [comment] 2023-11-27 19:41
@rlinoz In my opinion, there are a few reasons that we should not share the value in the URL:
1. It makes the URL messy  
2. Our other search pages do not have the search query in the URL, so if we only add the search query to the URL in Workspace Member page, it will lead to the inconsistency

**Comment by DylanDylann** [comment] 2023-11-30 14:06
@rlinoz Did internal team discuss about the expected behavior?

**Comment by rlinoz** [comment] 2023-11-30 18:18
Sorry, posted about it [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1701368313851029) today.

**Comment by rlinoz** [comment] 2023-11-30 23:29
There is really no clear winner in the thread, but nothing against going with @aimane-chnaif approved proposal from @DylanDylann, so I think we can go ahead.

Thanks everyone!

**Comment by rlinoz** [comment] 2023-12-04 22:02
I think we can demote this to weekly and wait for @DylanDylann updates.

**Comment by mallenexpensify** [comment] 2023-12-05 20:41
@DylanDylann , it's been 5 days since you were assigned, when can we expect a PR?

**Comment by DylanDylann** [comment] 2023-12-06 02:12
@mallenexpensify I am working on it. Will open the PR today

**Comment by mallenexpensify** [comment] 2023-12-18 17:48
Reporter: @c3024 owed $250 via Upwork (bug was reported in July)
Contributor: @DylanDylann  paid $500 via Upwork
Contributor+: @aimane-chnaif paid $500 via Upwork

@c3024 , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~013d2f1bf2a057285a

Regression test GH
https://github.com/Expensify/Expensify/issues/351498

**Comment by c3024** [comment] 2023-12-18 22:31
Accepted. Thanks. @mallenexpensify

**Comment by mallenexpensify** [comment] 2023-12-19 04:51
Should be all set! @c3024 paid and comment above has been updated to reflect payment

**Closed by mallenexpensify** 2023-12-19 04:51 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
