### ISSUE TITLE
Web – Xero – Error page 500 appears when connect to Xero

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49156] opened 2024-09-13 09:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.34-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48519
**Email or phone of affected tester (no customers):** applausetester+jp_113924@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Log in with expensifail account
3. Create a workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to Xero
7. Enable 2 FA
8. Enter Xero credentials
9. Click on Continue with one organization

## Expected Result:
The sync is complete

## Actual Result:
Error page 500 appears

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/af47659f-3f7c-4c24-8c67-be099eb0dcf4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-13 09:24
We think that this bug might be related to #wave-collect - Release 1

**Comment by grgia** [comment] 2024-09-13 11:04
@nyomanjyotisa cc @ikevin127  @Beamanator this deploy blocker was found while QAing your PR, could you please let me know if you have any additional context

**Comment by luacmartins** [comment] 2024-09-13 12:20
This kinda looks like an API issue to me with the oauth callback. @grgia can you reproduce this on staging?

**Comment by luacmartins** [comment] 2024-09-13 12:26
[Logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%225KSmZa%22)+AND+timestamp:[2024-09-13T05:29:04.446Z+TO+2024-09-13T07:29:04.446Z]&index=logs_expensify-030246)

```
Couldn't get valid connection data ~~ integration: 'xero' policyID: '84A1663F6E414ACE' data: 'is_temp_logs54a6cbb0-f8e6-4426-8b30-ca2072979ae9.log' class: 'ExpensifyException' msg: 'Invalid connection configuration' code: '410'
Couldn't load Xero connection data ~~ policyID: '84A1663F6E414ACE' class: 'ExpensifyException' msg: 'Invalid connection configuration' code: '410'
```

**Comment by luacmartins** [comment] 2024-09-13 12:27
We can see the URL is `staging.expensify.com` too. @grgia maybe this is a web blocker. Please confirm.

**Comment by grgia** [comment] 2024-09-13 16:01
looking @luacmartins

**Comment by grgia** [comment] 2024-09-13 16:06
@mananjadhav @dangrous I see you've been working on Xero stuff, maybe you have more info on the above? Still looking into this being a web blocker @luacmartins

**Comment by grgia** [comment] 2024-09-13 16:07
'Invalid connection configuration' code: '410'
seems to be hitting here https://github.com/Expensify/Integration-Server/blob/b23547d64498d85179125738f36763b5b47cd5ea/src/expensify/beans/expensify/policy/integration/xero/XeroConfiguration.java#L362

**Comment by grgia** [comment] 2024-09-13 16:11
Also cc @francoisl

**Comment by grgia** [comment] 2024-09-13 16:22
I'm 99% sure we can remove this from the app deploy blocker list, works in staging for me

**Comment by grgia** [comment] 2024-09-13 16:22
<img width="1131" alt="image" src="https://github.com/user-attachments/assets/5a5adea1-9acd-4e0c-8317-07e8420f4932">

Gonna close this out @luacmartins

**Comment by IuliiaHerets** [comment] 2024-09-21 12:21
QA team can reproduce this issue in the latest build - v9.0.39-0. Cannot reproduce the issue on an incognito window.

https://github.com/user-attachments/assets/5e03a1ba-fcfd-40b6-b5a2-584bb2390cc1

**Comment by grgia** [comment] 2024-09-23 10:20
triaged and adding to hot picks cc @lakchote @arosiclair as part of connections project

**Comment by trjExpensify** [comment] 2024-09-23 15:09
@hungvu193 remind me, why does this happen again? I feel like we've been here before...

**Comment by lakchote** [comment] 2024-09-23 15:36
This error occurred quite a bit during our implementation.

[Here](https://expensify.slack.com/archives/C036QM0SLJK/p1716383320651429?thread_ts=1716238514.357639&cid=C036QM0SLJK) was the solution to it.

**Comment by trjExpensify** [comment] 2024-09-23 22:29
Hm, but they're connecting to a fresh workspace though? 🤔

**Comment by lakchote** [comment] 2024-09-24 07:31
> Hm, but they're connecting to a fresh workspace though? 🤔

You're right.

I've investigated, the Xero's connection config is not in a correct state for the policy ID `48F701BD3789D925`.

Here's what it is:
```
            "connections": {
                "xero": {
                    "config": {
                        "credentials": {
                            "access_token": "xx",
                            "companyID": "2f72d547-7f63-4fa4-b85b-af0fa49c5529",
                            "expires": 1726209671,
                            "refresh_token": "xx",
                            "scope": "accounting.transactions accounting.settings accounting.contacts accounting.attachments accounting.reports.read files offline_access",
                            "token_type": "Bearer"
                        },
                        "tenantID": "e5dd812d-6458-4f79-ab4d-59a5c9802471"
                    }
                }
```

We're checking [here](https://github.com/Expensify/Integration-Server/blob/main/src/expensify/beans/expensify/policy/integration/IntegrationConnection.java#L141C1-L142), if the connection has a `config` property set, if it does we try to validate its format. 
However the `config` above doesn't have the necessary properties we check for [here](https://github.com/Expensify/Integration-Server/blob/main/src/expensify/beans/expensify/policy/integration/xero/XeroConfiguration.java#L359-L371).

I've removed the `connections` data for Xero for this policy ID.

@IuliiaHerets could you please retest for policy ID `48F701BD3789D925`?

**Comment by trjExpensify** [comment] 2024-09-24 15:46
>I've investigated, the Xero's connection config is not in a correct state for the policy ID 48F701BD3789D925.

**Comment by trjExpensify** [comment] 2024-09-24 15:47
>I've investigated, the Xero's connection config is not in a correct state for the policy ID 48F701BD3789D925.

Do we know why the connection config is getting into that state?

**Comment by lakchote** [comment] 2024-09-25 08:02
> > I've investigated, the Xero's connection config is not in a correct state for the policy ID 48F701BD3789D925.
> 
> Do we know why the connection config is getting into that state?

Honestly, I do not have the answer to that question. cc @francoisl maybe you'll have the answer? Otherwise, we'd need to try to reproduce that state. My guess would be an incomplete setup flow triggers that state.

**Comment by m-natarajan** [comment] 2024-09-26 12:41
Bug is not reproducible anymore.

https://github.com/user-attachments/assets/d6f8725c-a698-408b-85ab-e8de932a830c

**Comment by sakluger** [comment] 2024-09-26 16:31
Okay sounds like this is fixed. Closing!

**Comment by mananjadhav** [comment] 2024-09-26 16:33
I was able to reproduce this recently on staging if you check the video attached [here](https://github.com/Expensify/App/issues/49559#issuecomment-2372046398). So I am not sure if we did something that fixed it.

**Comment by trjExpensify** [comment] 2024-09-27 01:33
Yeah, I'm not convinced this is fixed personally.

**Comment by trjExpensify** [comment] 2024-09-27 01:34
I'd be curious for Franc's take on [Lucien's q above](https://github.com/Expensify/App/issues/49156#issuecomment-2373350679) before closing in haste.

**Comment by mananjadhav** [comment] 2024-09-27 01:38
Yeah I haven't got a chance to look at this again. But I've always got this when I try a fresh login and first time sync. I have a few workspaces connected to other accounting integrations for my QA. But I think this would have to be fixed internally. The error page that we see is on `staging.expensify.com` ie the OldDot. 

Few things that come on top of my head are:
1. Payload size must be causing the issue? (highly likely)
2. Any rate limits per IP or from Xero?
3. Any backend bug (less likely as subsequent sync work fine).

**Comment by francoisl** [comment] 2024-09-28 01:39
When that happens, can you try to open https://staging.expensify.com and https://staging.new.expensify.com in separate tabs, and check if you're signed in the **same** Expensify account in both?

From what I'm seeing in the logs for the rayID `8c25fa7d6995ca59` from the screencast in the OP, there are 2 separate accounts involved - applausetester+jp_113924@applause.expensifail.com, and a gmail address.
([logs1](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228c25fa7d6995ca59-KBP%22)+AND+timestamp:[2024-09-13T05:11:12.092Z+TO+2024-09-13T07:11:12.092Z]&index=logs_expensify-030245), [logs2 by policyID](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%2248F701BD3789D925%22%20AND%20timestamp%3A%5B2024-09-13T06%3A00%20TO%202024-09-13T07%3A00%5D)).

Because of that, the backend thinks you're trying to update a policy you don't have access to, and returns an error. I'm not sure why it ends up as a "bad gateway" error though.

**Comment by sakluger** [comment] 2024-09-30 14:47
> From what I'm seeing in the logs for the rayID 8c25fa7d6995ca59 from the screencast in the OP, there are 2 separate accounts involved

I would expect us to return an error in this scenario, but maybe we should use a more descriptive error than a 500?

**Comment by sakluger** [comment] 2024-10-02 15:05
@IuliiaHerets could you please try this again and check @francoisl's question above?

> When that happens, can you try to open https://staging.expensify.com/ and https://staging.new.expensify.com/ in separate tabs, and check if you're signed in the same Expensify account in both?

**Comment by IuliiaHerets** [comment] 2024-10-03 07:13
@sakluger Issue is not reproducible now

https://github.com/user-attachments/assets/3f441224-8a1a-4bcb-9fe8-2cc4b56f3c74

**Comment by sakluger** [comment] 2024-10-06 20:44
Okay, since @grgia couldn't reproduce before and now @IuliiaHerets can't reproduce, we can close it out again. Feel free to reopen if it happens again.

**Closed by sakluger** 2024-10-06 20:44 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug, Hot Pick
