### ISSUE TITLE
[AWAITING PAYMENT] [$250] Expense - Payment option is not selected from the dropdown unless it is reselected

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49331] opened 2024-09-17 09:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+watashiwastar2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has set up bank account.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense.
4. On the main chat, click on the payment dropdown button.
5. Select the other payment option.
6. Click on the payment dropdown button.
7. Select the other payment option again.

## Expected Result:
The payment option will be selected without issue.

## Actual Result:
The payment option is not selected until it is selected for the second time.
On Android and iOS app, the payment option is selected without issue during the first attempt, but it reverts to the previous option when opening dropdown and dismissing the modal.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/271b68ff-ee76-40ad-a80a-43ce88768e8c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841124636355272101</li>
        <li>Upwork Job ID: 1841124636355272101</li>
        <li>Last Price Increase: 2024-10-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by IuliiaHerets** [comment] 2024-09-17 09:59
We think that this bug might be related to #wave-collect - Release 2

**Comment by grgia** [comment] 2024-09-17 11:04
potentially related to https://github.com/Expensify/App/pull/48863 @shubham1206agra

**Comment by mountiny** [comment] 2024-09-17 11:22
> Reproducible in production?: N/A - new feature, doesn't exist in prod

Interesting, this does not feel like a new feature

**Comment by grgia** [comment] 2024-09-17 15:01
@ZhenjaHorbach do you think we'll be able to get a fix up today or consider reverting this PR for the deploy?

**Comment by grgia** [comment] 2024-09-17 15:24
I think that's fine @ZhenjaHorbach. Do you happen to know why we added the policyId selector here?

```jsx
const [lastPaymentMethod = '-1'] = useOnyx(ONYXKEYS.NVP_LAST_PAYMENT_METHOD, {selector: (paymentMethod) => paymentMethod?.[policyID]});
```

**Comment by grgia** [comment] 2024-09-17 15:27
@ZhenjaHorbach sounds good to me

**Comment by mountiny** [comment] 2024-09-17 16:20
Thanks for looking into this, just for my understanding that PR is already in production right? So that would mean it cannot be the root cause of the deploy blocker, right?

**Comment by mountiny** [comment] 2024-09-17 17:45
Demoting as this is already in production

**Comment by garrettmknight** [comment] 2024-10-01 14:40
Offers out to both @ZhenjaHorbach and @dukenv0307

**Comment by garrettmknight** [comment] 2024-10-02 19:24
@dukenv0307 just you then!

**Comment by garrettmknight** [comment] 2024-10-08 19:12
All paid up, closing.

**Closed by garrettmknight** 2024-10-08 19:12 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
