### ISSUE TITLE
[HOLD for E/App #49802] "Release options" modal ( CTRL+D) does not appear when image is open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50114] opened 2024-10-02 20:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a2386@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to any chat
2. Open a image from chat history
3. Press Ctrl+D to open "Release options" modal

## Expected Result:
"Release options" modal should appear

## Actual Result:
"Release options" modal ( CTRL+D) does not appear when image is open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/68fc9a78-59f5-4c6d-b955-684c52fc289e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-02 20:28
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-10-03 03:58
Same root cause as https://github.com/Expensify/App/issues/49802

**Comment by alexpensify** [comment] 2024-10-04 23:17
@bernhardoj do you think we should close this one or put it on hold for https://github.com/Expensify/App/issues/49802

**Comment by bernhardoj** [comment] 2024-10-05 03:42
Let's hold it for https://github.com/Expensify/App/issues/49802

**Comment by alexpensify** [comment] 2024-10-07 21:15
Thanks for the feedback!

**Comment by alexpensify** [comment] 2024-10-09 22:36
Weekly Update: On hold for https://github.com/Expensify/App/issues/49802

**Comment by alexpensify** [comment] 2024-10-16 21:50
Weekly Update: The PR for https://github.com/Expensify/App/issues/49802 is under review

**Comment by alexpensify** [comment] 2024-10-23 22:24
Weekly Update: It looks like the PR is on hold

**Comment by alexpensify** [comment] 2024-10-30 22:13
Weekly Update: The PR for https://github.com/Expensify/App/issues/49802 should go into production by next week

**Comment by alexpensify** [comment] 2024-11-07 00:05
@lanitochka17 - the issue we have been on hold for has gone into production. Can we get a retest here? Thanks!

**Comment by lanitochka17** [comment] 2024-11-07 14:55
This issue is not repro anymore

https://github.com/user-attachments/assets/1394b93e-e843-4380-ba8d-dc3d5388a92a

**Comment by alexpensify** [comment] 2024-11-13 22:51
Awesome - closing!

**Closed by alexpensify** 2024-11-13 22:51 UTC
Labels: Weekly, Bug, retest-weekly
