### ISSUE TITLE
[$1000] iOS - Chat Notification Received even after reading the message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28327] opened 2023-09-27 16:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS ND app as User A
2. Login as User B on another device
3. User A: Open chat with User B
4. User B sends message to User A
5. Minimize the app
6. Wait for sometime and that message notification received

## Expected Result:
 Notification shouldn't received for already read messages.

## Actual Result:
Notification received for already read messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d25d2cc9-0441-4124-a2e8-b3801597095f

https://github.com/Expensify/App/assets/93399543/8f8893c9-90f6-46c5-9136-914fa337c085

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ufumerfarooq
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695730539089759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e75fe3ba091d029c</li>
        <li>Upwork Job ID: 1707068559914348544</li>
        <li>Last Price Increase: 2023-11-06</li>
    </ul>
</details>

**Comment by studentofcoding** [comment] 2023-09-28 10:26
# Proposal

## Please re-state the problem that we are trying to solve in this issue

The problem is that iOS users are receiving chat message notifications even after they have already read the messages.

## What is the root cause of that problem?

On `src/libs/Notification/PushNotification/index.native.js` we still didn't check the condition of the read messages https://github.com/Expensify/App/blob/07dd8e83dcb67198f89d96247ad59a23596c3755/src/libs/Notification/PushNotification/index.native.js#L25-L55 

Therefore, the push notification event callback is triggered for all received push notifications, regardless of whether the message has already been read or not

## What changes do you think we should make in order to solve the problem?

To solve the problem, we need to add a condition to skip triggering the callback for push notifications that correspond to already-read messages.

Here's the modified code:
```
function pushNotificationEventCallback(eventType, notification) {
    // Other code

    // Skip triggering the callback for already read messages
    if (eventType === EventType.PushReceived && payload.isRead) {
        Log.info('[PushNotification] Skipping callback for already read message.');
        return;
    }

    action(payload);
}
```

### Result 

![Notification_fix (1)](https://github.com/Expensify/App/assets/20473526/d6b749f0-8713-4735-824a-082c7f312165)

**Comment by lschurr** [comment] 2023-10-02 12:04
@cubuspl42 could you review the proposal here?

**Comment by cubuspl42** [comment] 2023-10-02 12:10
@studentofcoding 

Please prefer videos over gifs.

Where did you learn about the `isRead` property? Is it documented anywhere in the code?

**Comment by lschurr** [comment] 2023-10-04 16:04
Bump @cubuspl42 @studentofcoding

**Comment by cubuspl42** [comment] 2023-10-05 09:04
@studentofcoding Would you comment on the `isRead` property?

If @studentofcoding is unavailable, I'll ask for help on Slack. There's a possibility this might have to be made internal.

**Comment by studentofcoding** [comment] 2023-10-05 11:05
Hey @cubuspl42 I've checked the code and changed checking on `isRead` property to use [another way here](https://github.com/Expensify/App/issues/28327#issuecomment-1738882727), with the same RCA.

**Comment by cubuspl42** [comment] 2023-10-05 11:17
@studentofcoding While I appreciate the change, I would ask you to walk me through the process, i.e. answer the original question in some way, and describe why you're making the change in the proposal.

**Comment by studentofcoding** [comment] 2023-10-05 11:24
> @studentofcoding While I appreciate the change, I would ask you to walk me through the process, i.e. answer the original question in some way, and describe why you're making the change in the proposal.

Sure @cubuspl42, in simple terms, after finding the RCA and wrote it on my proposal, im just drawed a rough code changes without checking 'isRead' property in the first place

**Comment by cubuspl42** [comment] 2023-10-05 11:33
So you kind of... hallucinated that it exists?

**Comment by lschurr** [comment] 2023-10-09 16:54
What's the latest here @cubuspl42?

**Comment by cubuspl42** [comment] 2023-10-09 17:10
I decided to reject the proposal by @studentofcoding, regardless of the update. The fact that an utterly non-existing property was used suggests that either:

- The proposal was very reckless
- The proposal was written using a Large Language Model (like ChatGPT or another), which tends to "hallucinate" , referring to non-existing things (it's impossible to prove, though)

@studentofcoding Thank you for you contribution, but for now, please focus on other issues and be sure to refer only to existing APIs in the future.

**Comment by cubuspl42** [comment] 2023-10-09 17:15
I [advertised the issue on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1696871651279209)

**Comment by studentofcoding** [comment] 2023-10-09 17:24
> I decided to reject the proposal by @studentofcoding, regardless of the update. The fact that an utterly non-existing property was used suggests that either:
> 
> 
> 
> - The proposal was very reckless
> 
> - The proposal was written using a Large Language Model (like ChatGPT or another), which tends to "hallucinate" , referring to non-existing things (it's impossible to prove, though)
> 
> 
> 
> @studentofcoding Thank you for you contribution, but for now, please focus on other issues and be sure to refer only to existing APIs in the future.

No worries @cubuspl42, I understand your POV. Also I already shared that It's a raw code changes that I shared directly on Github to post it fast. And there are many cases that there's a slight error or typo on another issues

If you think that It's reckless or generated, then I understand your pov, but I must say that It's nothing but a harsh speculation

**Comment by cubuspl42** [comment] 2023-10-09 17:34
@studentofcoding Thank you for understanding

**Comment by mvtglobally** [comment] 2023-10-12 03:52
Issue not reproducible during KI retests. (First week)

**Comment by lschurr** [comment] 2023-10-12 15:35
@cubuspl42 are you able to reproduce this?

**Comment by cubuspl42** [comment] 2023-10-13 08:14
@lschurr Not 100% of the time, but it's certainly possible. Significantly if you minimize quite fast.

https://github.com/Expensify/App/assets/2590174/5d5fbdc9-b299-42c7-b7ab-ed3e8777f296

**Comment by lschurr** [comment] 2023-10-16 15:50
Thanks, so it sounds like we're still waiting on proposals correct @cubuspl42?

**Comment by cubuspl42** [comment] 2023-10-17 09:13
Yes. [Re-advertised on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1697533015599099?thread_ts=1696871651.279209&cid=C01GTK53T8Q).

**Comment by cubuspl42** [comment] 2023-10-19 10:06
I bumped once more on Slack, I'm trying to figure out whether this needs a bounty adjustment.

**Comment by lschurr** [comment] 2023-10-23 15:25
Any update @cubuspl42?

**Comment by cubuspl42** [comment] 2023-10-23 15:28
@lschurr We [received feedback](https://expensify.slack.com/archives/C01GTK53T8Q/p1697722389108729?thread_ts=1696871651.279209&cid=C01GTK53T8Q) that this issue is very hard to debug. I'm still not convinced by our single proposal so far. Let's bump the bounty, this needs more eyes.

**Comment by lschurr** [comment] 2023-11-02 16:07
Bump @robertjchen

**Comment by lschurr** [comment] 2023-11-06 16:38
Alright, I've updated the bounty on this one.

**Comment by Julesssss** [comment] 2023-11-06 17:09
This isn't a bug, we haven't yet got to this feature request. It's on a long list of [internal notification issues](https://github.com/Expensify/Expensify/issues/255265).

**Comment by cubuspl42** [comment] 2023-11-07 10:28
@Julesssss 

Well, it's arguable whether this is or isn't a bug (I would say it is), but if we agree that it is considered a known limitation, are we closing this issue?

**Closed** 2023-11-07 11:06 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by Julesssss** [comment] 2023-11-07 11:43
> Well, it's arguable whether this is or isn't a bug (I would say it is), but if we agree that it is considered a known limitation, are we closing this issue?

it's not a bug because we designed and implemented notifications to show on all devices. We still have some issues with notification delivery and not displaying notifications for read messages makes testing and debugging notifications harder. We will eventually get to this, but it requires further though and might be handled by the backend.
