### ISSUE TITLE
Console error when removing members from workspace - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11135] opened 2022-09-20 05:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click on use icon to open setting page.
2. Click on workspace > manage members > select member > 
3. Click on remove

## Expected Result:
No console error.

## Actual Result:
Console error: Uncaught (in promise) Error: BrowserNotification must include title and body parameter.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.0-8
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/191176856-7d9b81d3-1a47-4499-a369-49870b5f4910.mov

https://user-images.githubusercontent.com/43995119/191176862-bba80127-cda6-40a4-9475-01e19bc24fea.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661438201907079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment] 2022-09-21 01:33
I will test tomorrow.

**Comment by alexpensify** [comment] 2022-09-21 20:59
I can't replicate, here are the results in my tests via Chrome. I tried with two users: 

First attempt: 
![2022-09-21_13-49-22](https://user-images.githubusercontent.com/8107070/191609006-08c09397-8cfa-4fde-ac35-b1bb2e486244.jpg)

Second attempt: 
![2022-09-21_13-54-24](https://user-images.githubusercontent.com/8107070/191609047-04059cf9-4382-4488-b128-9fd8f3385002.jpg)

Status after the two tests: 
![2022-09-21_13-55-02](https://user-images.githubusercontent.com/8107070/191609061-afc2045a-244d-44f3-bd13-731e32a3a9a3.jpg)

**Comment by alexpensify** [comment] 2022-09-21 21:06
@mvtglobally - I noticed in the Slack thread you were unable to reproduce this issue. I'm going to close it for now instead of assigning back to you since you were successful to remove users too.

**Comment by aneequeahmad** [comment] 2022-09-22 09:14
@alexpensify this error is reproducible and `exists` in latest production build `v1.2.3-1`

cc: @mvtglobally 

Video and Screenshot:


https://user-images.githubusercontent.com/36359331/191707924-38f08bb4-f277-4ab0-bade-23751db85936.mov

**Comment by alexpensify** [comment] 2022-09-22 21:27
Reopening - @mvtglobally can you reproduce? I've been unsuccessful to replicate this experience after following the steps in the .mov file.

**Comment by aneequeahmad** [comment] 2022-09-22 22:51
@alexpensify Please try [these](https://github.com/Expensify/App/issues/11135#:~:text=Action%20Performed%3A,Click%20on%20remove) steps on the URL https://new.expensify.com/

**Comment by alexpensify** [comment] 2022-09-22 23:25
Correct, that's what I did here: 

https://github.com/Expensify/App/issues/11135#issuecomment-1254221551

**Comment by mvtglobally** [comment] 2022-09-26 05:52
@alexpensify we are also not able to reproduce. Really not sure why.

**Comment by alexpensify** [comment] 2022-09-26 15:12
Thanks, @mvtglobally - At this point, I'm going to close this issue since two people were unable to replicate the experience following the steps listed in this issue.

**Comment by aneequeahmad** [comment] 2022-09-26 19:02
Still reproducible on latest production `v1.2.5-2`.  

**Platform:** Mac (Google chrome)

Steps are simple.

- Click on use icon to open setting page.
- Click on workspace > manage members.
- Click on invite button and add a few members.
- Select a few members and click on remove.
- See the console. The error will appear after a few second( 6 seconds on my `macBook Pro 2015, core i7`)

**Video:**

https://user-images.githubusercontent.com/36359331/192358262-f8b083ab-8e90-40d3-9f33-201f59bce4db.mov

cc: @alexpensify, @mvtglobally

**Comment by alexpensify** [comment] 2022-09-26 20:13
After chatting with the team, we decided that it's best to assign to Engineering for another set of eyes since the screen share includes JS details.

**Comment by cristipaval** [comment] 2022-10-05 21:06
I couldn't reproduce it either 👀

**Comment by MitchExpensify** [comment] 2022-10-19 22:03
@thesahindia kindly tried to reproduce and was not able - closing

**Comment by MitchExpensify** [comment] 2022-10-19 22:05
Unable to reproduce - closing

**Closed by MitchExpensify** 2022-10-19 22:05 UTC
Labels: Engineering, Daily, Needs Reproduction, Bug

**Comment by aneequeahmad** [comment] 2022-10-27 03:35
**Last Version where issue exist**

- This issue is reproducible in version `1.2.10-1` 

Video: 


https://user-images.githubusercontent.com/36359331/198185166-01cd83f0-0612-4cdd-84ef-8ca8800200b1.mov



**Issue fixed in version**

- This issue is fixed in version `1.2.11.0` in commit no `607f8e936`


https://user-images.githubusercontent.com/36359331/198185177-705b7d31-9383-4352-9ad7-f8b7dd70fdfe.mov



cc: @MitchExpensify, @mvtglobally

**Comment by aneequeahmad** [comment] 2022-11-04 21:44
Reminder

@MitchExpensify , @mvtglobally

**Comment by MitchExpensify** [comment] 2022-11-07 11:44
If this isn't reproducible in the latest version, is there any action to be taken?

**Comment by aneequeahmad** [comment] 2022-11-07 12:02
@MitchExpensify, Yeah you're right this isn't reproducible on the latest version as it has been fixed internally like i explained in comment [here](https://github.com/Expensify/App/issues/11135#:~:text=This%20issue%20is%20fixed%20in%20version%201.2.11.0) 
in commit # 607f8e936.

I am eligible to be paid for reporting bonus i assume as commented in slack open source [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1666130775191049?thread_ts=1663581586.519609&cid=C01GTK53T8Q)

**Comment by MitchExpensify** [comment] 2022-11-07 14:22
Got it! Thanks for catching me up. Invited you to this job for reporting payment https://www.upwork.com/jobs/~01264dd1cc5bd0e222

**Comment by aneequeahmad** [comment] 2022-11-07 14:26
@MitchExpensify Thanks for inviting me. i have applied for the job
