### ISSUE TITLE
[HOLD for payment 2024-01-22] [$500] Emoji - Emoji skin tone is not updated when changing skin tone while suggestion list is open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33064] opened 2023-12-14 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to any chat.
3. Type :+1
4. Open emoji picker.
5. Select a different skin tone.
6. Tap outside the emoji picker to close it.

## Expected Result:
The emoji in the suggestion list is updated to the latest selected skin tone.

## Actual Result:
The emoji in the suggestion list is still shown in the previously selected skin tone.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/70418f2b-21b7-47a9-a177-a62a09c17f53

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016670ca4c87bf3293</li>
        <li>Upwork Job ID: 1735303593508749312</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Contributor | 28089152</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by neonbhai** [comment] 2023-12-14 15:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emoji - Emoji skin tone is not updated when changing skin tone while suggestion list is open

### What is the root cause of that problem?
We don't update Emoji Suggestion List if the `preferredSkinTone` changes

### What changes do you think we should make in order to solve the problem?
We should make `preferredSkinTone` as dependency of this `useEffect`:

https://github.com/Expensify/App/blob/207d4ac23598dd10dad0275344d750b62b67a4a3/src/pages/home/report/ReportActionCompose/SuggestionEmoji.js#L184-L189

**Comment by DylanDylann** [comment] 2023-12-14 15:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Emoji - Emoji skin tone is not updated when changing skin tone while suggestion list is open
### What is the root cause of that problem?
- This bug only appears in the native platform.
- The RCA is that, the EmojiSuggestions component are using the FlashList to display the suggestion list. When the ```preferredSkinToneIndex``` is changed, FlashList is not rerender because it only rerender once the data or the extraData props changes.

### What changes do you think we should make in order to solve the problem?
- We just need to add the ```preferredSkinToneIndex``` to the ```extraData``` props


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by laurenreidexpensify** [comment] 2023-12-18 10:49
@sobitneupane bump for review ^^

**Comment by sobitneupane** [comment] 2023-12-18 11:08
Thanks for the proposal everyone.

To reflect the change in language, we have `preferredLocale` as dependency in `calculateEmojiSuggestion` in `SuggestionEmoji`. So, I believe we should do the same for `preferredSkinTone` as well.

@neonbhai Your proposal aligns closely with my suggestion. Kindly revise your proposal accordingly, if you agree. I welcome any alternative viewpoints you may have. Please let me know your thoughts.

**Comment by neonbhai** [comment] 2023-12-18 11:45
@sobitneupane Thank you for the suggestion! I'm thinking adding it to the dependency array of the function will cause the function to be recreated but may not cause the component to rerender (so the function is not called again), so we might need to add it to the `useEffect` which calls the function:

https://github.com/Expensify/App/blob/207d4ac23598dd10dad0275344d750b62b67a4a3/src/pages/home/report/ReportActionCompose/SuggestionEmoji.js#L184-L189

**Comment by Pujan92** [comment] 2023-12-18 14:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emoji skin tone is not updated in the suggestion list when change skin tone applied

### What is the root cause of that problem?
Even though `renderSuggestionMenuItem` is changed based on `preferredSkinToneIndex` dependency, the `Flashlist` does not get re-rendered.
https://github.com/Expensify/App/blob/e9d05f8190c217c375743220b08e732b5c74ff91/src/components/EmojiSuggestions.tsx#L75

It seems for optimization purposes re-rendering more depends on `keyExtractor`.
https://github.com/Shopify/flash-list/issues/699

### What changes do you think we should make in order to solve the problem?
We need to pass `renderSuggestionMenuItem` also in the `extraData` to rerender the list.

`extraData={[highlightedSuggestionIndex, renderSuggestionMenuItem]}`
https://github.com/Expensify/App/blob/e9d05f8190c217c375743220b08e732b5c74ff91/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.tsx#L99

**Comment by laurenreidexpensify** [comment] 2023-12-20 14:17
@sobitneupane what do you think of these updates ^^

**Comment by laurenreidexpensify** [comment] 2023-12-29 09:46
@sobitneupane bump for review of comments above thanks

**Comment by laurenreidexpensify** [comment] 2024-01-02 10:34
@sobitneupane bump thanks

**Comment by sobitneupane** [comment] 2024-01-03 15:39
Sorry for the delay. I will review the proposal shortly.

**Comment by sobitneupane** [comment] 2024-01-04 11:03
Thanks for the proposal everyone. 

On re-evaluating the proposals, I believe it is not a good idea recalculate emoji suggestions as nothing changes on `emojis={suggestionValues.suggestedEmojis}` when `preferredSkinTone` changes. 

In `renderSuggestionMenuItem` in EmojiSuggestions, we have used `preferredSkinToneIndex` in dependencyList. Should it not trigger the re-render when `preferredSkinToneIndex` changes?

**Comment by Pujan92** [comment] 2024-01-04 11:11
Yes, extraData seems to be responsible for re-rendering outside of the data.
https://shopify.github.io/flash-list/docs/usage/#extradata

**Comment by sobitneupane** [comment] 2024-01-05 16:51
Thanks for the update.

> this issue came from FlashList's rendering optimisation with extraData.
If you debug, even BaseAutoCompleteSuggestions component is re-rendered whenever preferredSkinToneIndex changes. But renderItem of FlashList inside BaseAutoCompleteSuggestions is not re-rendered.



>Yes, extraData seems to be responsible for re-rendering other than data changes.

In that case, I believe it makes sense to pass `renderSuggestionMenuItem` to `extraData` as suggested by @Pujan92 in his proposal. As it is a generic component, I don't think we should pass child component specific prop like `preferredSkinTonIndex `.

[Proposal](https://github.com/Expensify/App/issues/33064#issuecomment-1860646219) from @Pujan92 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by laurenreidexpensify** [comment] 2024-01-22 10:53
Payment Summary:

Contributor - @Pujan92 $500 paid in Upwork
C+ Review - @sobitneupane $500 to be paid in Newdot

**Comment by laurenreidexpensify** [comment] 2024-01-22 10:53
Remaining Steps: 

@sobitneupane please complete the checklist so we can close out thanks

**Comment by laurenreidexpensify** [comment] 2024-01-25 11:05
@sobitneupane bump thanks

**Comment by laurenreidexpensify** [comment] 2024-01-26 10:22
waiting for checklist to be completed before closing

**Comment by sobitneupane** [comment] 2024-01-29 06:20
Sorry for the delay. I was mostly unavailable last week. I will get it done this week (probably tomorrow).

**Comment by laurenreidexpensify** [comment] 2024-01-29 11:12
Still waiting on Sobit to complete, he's aiming for Tuesday 30th 👍

**Comment by sobitneupane** [comment] 2024-02-01 15:41
I will complete the checklist by EOD.

**Comment by sobitneupane** [comment] 2024-02-02 08:34
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

This is an edge case. It was probably existent from the inception of the feature.
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

N/A
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2024-02-02 08:35
**Regression Test proposal:**

1. Launch New Expensify app in IOS/native or Android/native.
2. Go to any chat.
3. Type :+1
4. Open emoji picker.
5. Select a different skin tone.
6. Tap outside the emoji picker to close it.
7. Verify that the emoji in the suggestion list is updated to the latest selected skin tone.

Do we agree 👍 or 👎

**Closed** 2024-02-05 13:42 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-02-14 22:41
$500 approved for @sobitneupane based on [this summary](https://github.com/Expensify/App/issues/33064#issuecomment-1903745199).
