### ISSUE TITLE
[HOLD for payment 2023-09-06] [$2000] Web - The backtick is outside the code block when sending a message with two backticks

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23352] opened 2023-07-21 12:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send a text wrapped in two backticks

## Expected Result:
Backtick should be in the code block

## Actual Result:
One Backtick is out of the code block

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f52476ed-b734-4056-96cb-f684a22c8eb5

https://github.com/Expensify/App/assets/93399543/90d7f02d-9aa1-4df4-9a1e-c6ff43fb333f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689891927706399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f54ca2df0a387770</li>
        <li>Upwork Job ID: 1684220588166258688</li>
        <li>Last Price Increase: 2023-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26116411</li>
<li>daveSeife | Reporter | 26116415</li>
</ul></li>
    </ul>
</details>

**Comment by manan-upadhyay** [comment] 2023-07-26 18:41
I think this issue can be fixed as follows:
- When user press the backtick key, two backticks would be types and the cursor would be placed in between the ticks, so naturally the message would be send without any extra backticks

**Comment by manan-upadhyay** [comment] 2023-07-26 18:49
Contributor details
Your Expensify account email: upadhyaymanan01@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0122e0ed8ca6eca7fa

**Comment by Victor-Nyagudi** [comment] 2023-07-27 06:06
This issue seems like a likely candidate to be added to the [markdown tracking issue](https://github.com/Expensify/App/issues/20304). 

A [discussion was held in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1684840420322509) about another [issue involving backticks](https://github.com/Expensify/App/issues/17196), and the consensus was it's better not to overcomplicate the code blocks' regular expressions for certain scenarios. 

I'd like to hear your thoughts on this one, @greg-schroeder, since you took part in the Slack discussion.

**Comment by abdulrahuman5196** [comment] 2023-07-31 11:56
Reviewing today

**Comment by Antasel** [comment] 2023-08-01 08:47
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
text wrapped in two backticks is not parsed properly with code block, one backtick is out of code block.

### What is the root cause of that problem?
in inline codeblock rule's regex pattern is using lazy mode to get code block content, so last backtick is not contained in code block content.

### What changes do you think we should make in order to solve the problem?
to fix the root cause, add a tweak(adding a backtick option in negative lookahead) on [inline codeblock's regex pattern](https://github.com/Expensify/expensify-common/blob/fea1a755affabdbb8b6d7c5b754241849124f488/lib/ExpensiMark.js#L50)
which would be like following after fixed.

```
regex: /(\B|_|)&#x60;(.*?\S.*?)&#x60;(\B|_|)(?!&#x60;|[^<]*<\/pre>)/g,
```

relevant test case is like below
```
const testString = '``JavaScript``';
expect(parser.replace(testString)).toBe('<code>&#x60;JavaScript&#x60;</code>');
```

it doesn't make other auto test cases failed, all passed.

**Comment by muttmuure** [comment] 2023-08-02 19:22
@abdulrahuman5196 let me know if any of these look good to you

**Comment by abdulrahuman5196** [comment] 2023-08-06 18:58
On @samh-nl 's proposal here.

It would work for the current case.But for the below it will put all the numbers in the codeblock which wouldn't be the expected one.
```
`123`456`789`
```

@Antasel 's proposal works fine for the requirement.
I will test with couple of other scenarios and update here.

**Comment by s-alves10** [comment] 2023-08-09 06:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Backtick is outside the code block when sending a message with two backticks

### What is the root cause of that problem?

The current backtick parser regex is as follows
```
        regex: /(\B|_|)&#x60;(.*?\S.*?)&#x60;(\B|_|)(?![^<]*<\/pre>)/g,
```

`*?` will match as few characters as possible to satisfy the regex pattern.
The above pattern finds the first backtick and the earliest backtick followed by the fewest non-space characters after the previous backtick. So in the case of ``a``, it'll match the first and third backtick.

This is the root cause

### What changes do you think we should make in order to solve the problem?

First backtick is fine. We have to find the 2nd backtick as the last backtick in the backticks followed by the fewest non-space characters after the first one

In order to do this, I suggest the following regex
```
        regex: /(\B|_|)&#x60;(.*?\S.*?(?:&#x60;)*)&#x60;(\B|_|)(?![^<]*<\/pre>)/g,
```

`(?:&#x60;)*` was added to match the preceding backtick characters

<details>
    <summary>Result</summary>

```
    `ab` -> <code>ab</code>
    `ab`` -> <code>ab&#x60;</code>
    ``ab`` -> <code>&#x60;ab&#x60;</code>
    ```ab`` -> <code>&#x60;</code>ab&#x60;&#x60;
    ``ab```cc -> <code>&#x60;ab&#x60;&#x60;</code>cc
    `a`b`c`d -> <code>a</code>b<code>c</code>d
```

</details>

### What alternative solutions did you explore? (Optional)
In the above tests, ```ab`` was parsed `<code>&#x60;</code>ab&#x60;&#x60;`. If we want to parse this as `<code>&#x60;&#x60;ab&#x60;</code>` we can use the following regex
```
        regex: /(\B|_|)&#x60;(.*?[^\s&#x60;].*?(?:&#x60;)*)&#x60;(\B|_|)(?![^<]*<\/pre>)/g,
```

**Comment by muttmuure** [comment] 2023-08-09 20:52
@abdulrahuman5196 do we think @Antasel's proposal is good enough? @s-alves10 has one too

**Comment by abdulrahuman5196** [comment] 2023-08-13 13:38
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-08-13 14:10
@s-alves10 's new proposal provides the same results as the proposal here https://github.com/Expensify/App/issues/23352#issuecomment-1659859472

**Comment by abdulrahuman5196** [comment] 2023-08-13 14:13
@Antasel 's proposal here https://github.com/Expensify/App/issues/23352#issuecomment-1659859472 looks good and works well. It solves the solution in simplest way by adding a negative lookahead of `

🎀 👀 🎀
C+ Reviewed

**Comment by jasperhuangg** [comment] 2023-08-14 17:01
@abdulrahuman5196 Totally agree with you. Let's assign @Antasel, thanks!

**Comment by abdulrahuman5196** [comment] 2023-08-16 04:00
@Antasel any update on the PR?

**Comment by Antasel** [comment] 2023-08-16 15:10
@abdulrahuman5196 @jasperhuangg 
Thanks for your review and assignment. i will raise PR asap. 
I was struggling to build android app, to fix build issue

who will approve me to  join slack channel ? I've sent email to contributors@expensify.com from  anayetrasel@yahoo.com

**Comment by Antasel** [comment] 2023-08-16 16:49
@abdulrahuman5196 The PR https://github.com/Expensify/expensify-common/pull/565 for expensify-common is ready for review

**Comment by jasperhuangg** [comment] 2023-08-21 17:16
Just merged @Antasel's expensify-common PR–awaiting his App PR and we can close this out!

**Comment by abdulrahuman5196** [comment] 2023-08-21 17:20
@jasperhuangg  we didn't do any C+ review on common package. Do we plan to do it in the APP package PR?

**Comment by jasperhuangg** [comment] 2023-08-21 17:32
@abdulrahuman5196 Yes! I was able to do some testing on my end so I'm pretty confident with the changes. Apologies, I wasn't aware that we also did C+ reviews on the expensify-common PRs.

**Comment by abdulrahuman5196** [comment] 2023-08-21 17:33
@jasperhuangg  ok sure. I will do the C+ review then at APP PR. @Antasel kindly raise the App PR as soon as possible.

**Comment by Antasel** [comment] 2023-08-22 08:40
@jasperhuangg @abdulrahuman5196 
App PR https://github.com/Expensify/App/pull/25659 is ready

**Comment by jasperhuangg** [comment] 2023-08-22 18:38
Thanks @Antasel! Taking a look

**Comment by abdulrahuman5196** [comment] 2023-09-04 10:29
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. This issue is present from implementation.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. We have already added Unit test cases to common package.

**Comment by Antasel** [comment] 2023-09-07 21:16
@abdulrahuman5196 @muttmuure 
We are still in regression period ? I think it's over. 
And I am not sure how can I get offer on Upwork .

**Comment by Antasel** [comment] 2023-09-13 03:55
@jasperhuangg @muttmuure 
Looks like a week passed. Do we have any update to move forward :smile:

**Comment by muttmuure** [comment] 2023-09-18 00:26
Catching up from OOO and looking today

**Comment by muttmuure** [comment] 2023-09-18 01:44
Reporter $250 - @daveSeife
C $2000 - @Antasel 
C+ $2000 - @abdulrahuman5196

**Comment by Antasel** [comment] 2023-09-18 03:17
@muttmuure Thanks, Accepted offer

**Comment by muttmuure** [comment] 2023-09-21 04:30
@Antasel paid

**Comment by muttmuure** [comment] 2023-09-21 04:31
@daveSeife paid

**Comment by muttmuure** [comment] 2023-09-21 04:32
@abdulrahuman5196 paid

**Closed by muttmuure** 2023-09-21 04:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
