### ISSUE TITLE
[$500] Web/windows - Receipt - Receipt view closes when pressing ESC key on file explorer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34436] opened 2024-01-12 12:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to details page of request with receipt.
2. Click on the receipt.
3. Click Download.
4. Press ESC key.

## Expected Result:
Only the file explorer closes.

## Actual Result:
Both file explorer and receipt view close.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3aa5aec2-9923-497c-89e4-b1607a0965b3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec93e1d678665cb8</li>
        <li>Upwork Job ID: 1745779675576864768</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2024-01-12 12:23
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Both file explorer and receipt view close.

## What is the root cause of that problem?

When the save / download file explorer dialog is open, `Esc` is still captured.

## What changes do you think we should make in order to solve the problem?

When the save / download file explorer dialog is open, prevent the `Esc` key from being captured.

**Comment by situchan** [comment] 2024-01-17 17:43
@dukenv0307 if it's upstream issue, can you create issue there?

**Comment by situchan** [comment] 2024-01-23 21:36
Awaiting proposals

**Comment by situchan** [comment] 2024-01-29 14:42
Same

**Comment by mvtglobally** [comment] 2024-01-30 04:55
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2024-01-31 17:26
Let's see if it's not reproducible again, and then we can close.

**Comment by situchan** [comment] 2024-01-31 17:40
This is still reproducible on windows chrome.

This should be enabled in chrome://settings/downloads

<img width="676" alt="Screenshot 2024-01-31 at 11 40 04 PM" src="https://github.com/Expensify/App/assets/108292595/de35fea2-e0c2-426f-a64b-eaf73b9d471f">

**Comment by situchan** [comment] 2024-02-06 15:42
Not overdue

**Comment by situchan** [comment] 2024-02-12 16:06
Not overdue

**Comment by situchan** [comment] 2024-02-19 15:28
Same

**Comment by JmillsExpensify** [comment] 2024-02-21 20:24
Still awaiting proposals.

**Comment by situchan** [comment] 2024-02-26 16:42
Same

**Comment by situchan** [comment] 2024-03-04 14:43
Same

**Comment by JmillsExpensify** [comment] 2024-03-06 21:40
Same

**Comment by JmillsExpensify** [comment] 2024-03-13 04:12
Still waiting for proposals

**Comment by JmillsExpensify** [comment] 2024-03-20 02:44
Still awaiting proposals

**Comment by situchan** [comment] 2024-03-22 14:34
@JmillsExpensify I suggest to close this for now as windows only bug.
We can reopen after wave is gone.

**Comment by JmillsExpensify** [comment] 2024-03-23 20:05
Sounds good to me!

**Closed by JmillsExpensify** 2024-03-23 20:05 UTC
Labels: Engineering, Daily, Internal, Bug
