### ISSUE TITLE
[$500] There are notification of unread message on fresh install of the app

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38715] opened 2024-03-20 22:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kadiealexander 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710921050509239

## Action Performed:
1. Fresh install the app from Testflight
2. Observe the app icon
## Expected Result:
There shouldn't be notification for unread message
## Actual Result:
There is a unread message notification
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/c104faf7-412a-4d76-82be-6fc5b7d2907c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a7449e9320304743</li>
        <li>Upwork Job ID: 1772385027376979968</li>
        <li>Last Price Increase: 2024-03-25</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2024-03-20 23:58
I don't think we should worry about Testflight install related bugs

**Comment by m-natarajan** [comment] 2024-03-21 15:37
@MitchExpensify I tested in staging, but happens in app store build https://expensify.slack.com/archives/C049HHMV9SM/p1710921050509239

https://github.com/Expensify/App/assets/38435837/e1779bb8-1c16-45e2-9b51-abf2da8573a6

**Comment by MitchExpensify** [comment] 2024-03-21 23:18
Reopening to take a second look at this

**Comment by kadiealexander** [comment] 2024-03-22 01:13
Just for context I didn't experience this when using TestFlight, this happened from the actual App Store on my physical iPhone.

**Comment by MitchExpensify** [comment] 2024-03-25 22:08
Waiting on proposals, labelling external

**Comment by jayeshmangwani** [comment] 2024-03-27 12:13
@ShridharGoel thanks for the proposal , Have you tested the app locally after adding the above code ?
And I was able to find one [SO](https://stackoverflow.com/questions/23365024/badge-count-is-persisted-after-deleting-an-app-and-installing-it-again) question that state that the same as you've mentioned in the proposal that notification count persists at least a day .

**Comment by jayeshmangwani** [comment] 2024-03-27 13:42
Yes that was exactly my doubt/thought, So issue will not be solved completely, as for the first time when user install the app they can see the badge count, badge will be set to 0 when app will be opened

**Comment by jayeshmangwani** [comment] 2024-03-27 13:59
@ShridharGoel This scenario altogether is very rare, as its very rare that someone uninstall & re-install the app often in one day. I'll do some search this badge issue today and if this is the [only way](https://github.com/Expensify/App/issues/38715#issuecomment-2021418730) then we can go with [this way](https://github.com/Expensify/App/issues/38715#issuecomment-2021418730)

**Comment by jayeshmangwani** [comment] 2024-03-28 11:41
@ShridharGoel Can you write steps how you've testes your proposal ?

In local app I am not able to reproduce this issue, I have followed these steps:

1. Install(run) app in simulator
2. Login with an old accounnt that contains few chats
3. Minimise app, now able to see the 3 badge for the app
4. Uninstalled the app
5. Re-installed(run) tha app
6. Able to see the old badge count 3
7. Opened the app and Now minimise the app, badge count disappeard

**Comment by jayeshmangwani** [comment] 2024-03-28 12:18
then can you add the steps here how *.app* file you have installed ?

**Comment by jayeshmangwani** [comment] 2024-03-29 07:11
@ShridharGoel Yes I was able to test.
If I have installed the previous  app version from the app store and app have some badge count, and then I have updated the app version whenever we get the new version to app store, then again `didFinishLaunchingWithOptions` will called, right ?
And previous badge count will be set to 0 ?

**Comment by jayeshmangwani** [comment] 2024-03-29 07:24
Woow, thanks for the link

**Comment by jayeshmangwani** [comment] 2024-03-29 07:40
If we go with the this [proposal](https://github.com/Expensify/App/issues/38715#issuecomment-2021418730) there is one drawback, If we have some badge count before uninstalling the app and then we re-install the app from store/testflight:

- If we open the app then all good we will not see the previous badge count,
- but if app is installing and then we minimise the app installation and go back to home page, then after installation finished, we can see the badge count very first time, until we open the app.

@MitchExpensify @kadiealexander Please suggest your thoughts on this, and should we need to open the discussion in #expensify-open-source?

**Comment by jayeshmangwani** [comment] 2024-04-01 07:24
@ShridharGoel 's [Proposal](https://github.com/Expensify/App/issues/38715#issuecomment-2021418730), Overall looks good of setting the `applicationIconBadgeNumber` to 0 on `didFinishLaunchingWithOptions.`

🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment] 2024-04-01 07:25
@johnmlee101 , [This](https://github.com/Expensify/App/issues/38715#issuecomment-2026814716) is a Summary of the selected proposal. Please suggest your thoughts on this. If it looks good, we can proceed with the above proposal.

**Comment by johnmlee101** [comment] 2024-04-01 15:32
Yeah it feels like this is outside of our control to some degree. I think we can go with that proposal

**Comment by jayeshmangwani** [comment] 2024-04-02 11:34
@ShridharGoel you are assigned to the issue; go for the PR.

**Comment by jayeshmangwani** [comment] 2024-04-22 10:26
@MitchExpensify Automation failed here, this issue is ready to be payout

**Comment by MitchExpensify** [comment] 2024-04-22 22:07
**Payment summary:**

$500 C+ @jayeshmangwani 
$500 C @ShridharGoel

**Comment by MitchExpensify** [comment] 2024-04-22 22:08
Paid and contract ended @jayeshmangwani 

Please accept the offer here https://www.upwork.com/nx/wm/offer/101682717

**Comment by MitchExpensify** [comment] 2024-04-25 01:57
Paid and contract ended, thanks everyone! 

Any testing steps you recommend @jayeshmangwani ?

**Comment by jayeshmangwani** [comment] 2024-04-25 14:49
@MitchExpensify Regression Tests

## **Regression Test Proposal**

1. Ensure you have a badge icon(some unread messages) on the Expensify logo on iOS.
2. Uninstall the App.
3. Install it again via the App Store.

Option A:

4. Open the App directly from the App Store. Close the App.
5. Verify that the Badge should not show. 
 
Option B:

4. Minimise App Store when the App is being installed.
5. If the App is being installed in the background, then the Badge will be visible Once the installation is finished.
6. Open the App and Close/Minimise the App.
7. Verify that the Badge should not show.

**Comment by MitchExpensify** [comment] 2024-04-25 21:31
Thanks!

**Closed by MitchExpensify** 2024-04-25 21:31 UTC
Labels: Reviewing, External, Weekly, Bug
