### ISSUE TITLE
[regression] [HOLD til 03-04-2024] Expense - Expanded confirmation page is collapsed when returning from Amount

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36077] opened 2024-02-07 21:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Start manual request flow
4. Proceed to confirmation page
5. Click Show more to expand the page
6. Click Date > back button
7. Note that the page is not collapsed
8. Repeat Step 5 with Date, Merchant, Description and Amount

## Expected Result:
When returning to confirmation page from each row, the confirmation page will remain expanded

## Actual Result:
When returning to confirmation page from Amount, the confirmation page is collapsed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a7b50bb0-e5eb-4f2e-ae8a-40f132caf51a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2c64eb58af55274</li>
        <li>Upwork Job ID: 1755336478259703808</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-07 21:04
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by Pujan92** [comment] 2024-02-08 10:09
Isn't it regression from https://github.com/Expensify/App/pull/34075?

**Comment by shubham1206agra** [comment] 2024-02-09 05:32
@hoangzinh I didn't think of this situation while implementing the loading indicator.
I can issue the fix of this fix. But it will be the same as https://github.com/Expensify/App/issues/36077#issuecomment-1932955191.

**Comment by stephanieelliott** [comment] 2024-02-14 07:48
> Just wondering, Isn't this supposed to be an external? @thesahindia @stephanieelliott

It is external, @abzokhattab  -- that's indicated by the `External` label being applied to the issue!

**Comment by stephanieelliott** [comment] 2024-02-14 07:51
@shubham1206agra  want to make sure I am understanding correctly -- this is a regression from https://github.com/Expensify/App/pull/34075 and you'll be raising a separate PR to fix this issue? Is that right?

**Comment by stephanieelliott** [comment] 2024-02-15 05:25
@abzokhattab For context, sometimes new issues are created by our QA team under the assumption that it is a bug, and we don't yet realize that it is actually a regression. So the standard labels are applied (which includes `Help Wanted`) and the issue is treated like a basic bug issue until someone (usually the C+) realizes that it's a regression and notes it on the issue, and the original PR author and/or C+ confirms it. 

The `Help Wanted` label just means that the issue is labeled External but no one has been assigned on the issue to fix it -- it is auto-removed once there is an assignee on the issue. So I understand why that's probably confusing in this case. However in the case of regressions, the original PR author will always be assigned to fix it as we do not pay for regressions (i.e. you'll get paid fixing the original issue, but we do not pay for fixing any regressions that you caused).

**Comment by stephanieelliott** [comment] 2024-02-19 23:29
PR is on staging

**Comment by stephanieelliott** [comment] 2024-02-27 02:49
The PR was deployed to prod today. Putting a 7 day hold on this just for good measure, but no payment is due seeing as this is a regression.

**Closed** 2024-03-05 01:17 UTC
Labels: Reviewing, External, Weekly, Bug
