### ISSUE TITLE
[$250] Workspace - Approver isn't getting an error message when trying to leave the WS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44094] opened 2024-06-20 15:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions: Have a Collect workspace with an expensifail owner and approver. Add approvals should be enabled and the approver account set under it.
1. Navigate to https://staging.new.expensify.com/
as the approver
2. Navigate to the workspace list
3. Leave the workspace
4. Navigate to the LHN
5. Log out
6. Log back
7. Navigate to the workspace list

## Expected Result:
The approver shouldn't be able to leave the workspace until somebody else is set as the approver. An error message should be sent similar to the one an admin gets when trying to remove the actual approver

## Actual Result:
Approver isn't getting an error message when trying to leave the WS where the account was set as an approver. The leave seems to be successful, the workspace disappears, RBR shows next to Workspaces and Account settings without any error messages. Some of the workspace rooms display "archived" in the LHN. The workspace appears again after relogging

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1224b3da-5652-4363-a778-bc40f2bc3263

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015aa4fdce9445849b</li>
        <li>Upwork Job ID: 1805946684614558394</li>
        <li>Last Price Increase: 2024-07-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by lanitochka17** [comment] 2024-06-20 15:54
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-20 15:54
We think that this bug might be related to #wave-collect - Release 1

**Comment by muttmuure** [comment] 2024-07-03 17:40
@sobitneupane proposal for you

**Comment by sobitneupane** [comment] 2024-07-04 18:04
I will review the proposal today.

**Comment by sobitneupane** [comment] 2024-07-05 08:50
Thanks for the proposal @nyomanjyotisa 

Overall [your proposal](https://github.com/Expensify/App/issues/44094#issuecomment-2200483041) looks good. 

@muttmuure User takes "Leave workspace" action from the Workspaces page(/settings/workspaces) with list of workspaces. So, instead of showing the error message in Members Page of the workspace (/settings/workspaces/_id_/members), should we show the error message in Workspace Page(/settings/workspaces).

**Comment by sobitneupane** [comment] 2024-07-09 07:03
Bump on https://github.com/Expensify/App/issues/44094#issuecomment-2210469697 @muttmuure

**Comment by mvtglobally** [comment] 2024-07-11 03:55
Issue not reproducible during KI retests. (First week)

**Comment by sobitneupane** [comment] 2024-07-15 07:35
Bump on https://github.com/Expensify/App/issues/44094#issuecomment-2210469697 @muttmuure

**Comment by sobitneupane** [comment] 2024-07-18 06:32
Bump @muttmuure https://github.com/Expensify/App/issues/44094#issuecomment-2210469697

**Comment by muttmuure** [comment] 2024-07-23 10:04
Hm, good question. I'm not sure which pattern we've standardized on

**Comment by trjExpensify** [comment] 2024-07-23 10:37
I think this might be a dupe of https://github.com/Expensify/App/issues/43508

CC: @Beamanator

**Comment by Beamanator** [comment] 2024-07-23 15:12
Huh so in this case there is a button for an owner approver to leave the workspace?! That should definitely not be showing.

This kinda seems like the opposite of https://github.com/Expensify/App/issues/43508 where we are handling a case to SHOW the leave button, right @trjExpensify ?

**Comment by trjExpensify** [comment] 2024-07-23 15:23
Nah, in the OP of the issue the account taking the action is not the owner: 

<img width="1341" alt="image" src="https://github.com/user-attachments/assets/0bc8d8c1-d2aa-4f74-a357-ae31a50bad14">

**Comment by Beamanator** [comment] 2024-07-23 15:44
aah ook i misread that, so if it's a non-owner, YES they should be able to leave & it looks like they are "able to see that button" but the backend isn't actually letting them leave :/ so that sounds kiiiiiiinda like a dupe, yeah

**Comment by sobitneupane** [comment] 2024-07-25 07:53
>Expected Result:
The approver shouldn't be able to leave the workspace until somebody else is set as the approver. An error message should be sent similar to the one an admin gets when trying to remove the actual approver

@Beamanator Do we want to allow the approver to leave the workspace? According to the Expected Result, we don't want approver to leave the workspace.

If we don't want to allow the approver to leave the workspace, I believe we should either show the error message in Workspaces page(/settings/workspaces) rather than Members page (https://github.com/Expensify/App/issues/44094#issuecomment-2210469697) or remove the "Leave Workspace" option.

**Comment by trjExpensify** [comment] 2024-07-25 21:46
>@Beamanator Do we want to allow the approver to leave the workspace? 

Yes, it's the same concept as letting you remove an approver from the workspace. We'll then set the workspace owner as your approver if necessary. I believe Alex has already implemented a modal confirmation for that case, though I'm a little hazy on what has or hasn't been done overall.

**Comment by trjExpensify** [comment] 2024-07-25 21:47
Either way, seems like we agree it's a dupe of https://github.com/Expensify/App/issues/43508?

**Comment by sobitneupane** [comment] 2024-07-26 05:50
> Yes, it's the same concept as letting you remove an approver from the workspace. We'll then set the workspace owner as your approver if necessary. I believe Alex has already implemented a modal confirmation for that case

In that case, we can either close this issue or hold.

**Comment by muttmuure** [comment] 2024-07-30 15:10
Let's close and see where we are when the other one is implemented

**Closed by muttmuure** 2024-07-30 15:10 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
