### ISSUE TITLE
[$250] Receipt scanning camera captures more image than the preview shows

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51499] opened 2024-10-25 20:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dangrous 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729793577184539

## Action Performed:
1. Tap FAB button > Submit expense
2. Scan a receipt or any image
3. Select any user or WS
4. Submit the expense
5. Open the receipt image
## Expected Result:
Receipt image should match what was focused with camera
## Actual Result:
 final image contains significantly more image on top/bottom than the interface showed when taking the photo
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
![IMG_1368](https://github.com/user-attachments/assets/8d5e7311-726c-42ae-9cc3-98490c89663d)
![IMG_1369](https://github.com/user-attachments/assets/f2c30022-77fc-4cb4-a5b0-692621614772)

https://github.com/user-attachments/assets/83c7fe34-df03-4d48-9b17-b7bebbb3428f

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851295732504418897</li>
        <li>Upwork Job ID: 1851295732504418897</li>
        <li>Last Price Increase: 2024-11-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by greg-schroeder** [comment] 2024-10-29 16:11
Sending through to `External` to start with

**Comment by greg-schroeder** [comment] 2024-11-01 20:37
Awaiting proposals

**Comment by alitoshmatov** [comment] 2024-11-03 13:05
Not overdue, waiting for proposals

**Comment by QichenZhu** [comment] 2024-11-04 04:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The camera preview frame is cropped.

### What is the root cause of that problem?
The default resize mode of the camera view is `cover`.

https://github.com/mrousavy/react-native-vision-camera/blob/782b131999dc54abb12a04e8e0ee1d0c7d52ad94/package/ios/React/CameraView.swift#L65

<img width="748" alt="Screenshot 2024-11-04 at 5 13 06 PM" src="https://github.com/user-attachments/assets/86446fe0-35ee-44f7-af34-fc53a029ddef">

### What changes do you think we should make in order to solve the problem?
1. Set the resize mode to `contain`

https://github.com/Expensify/App/blob/bef062b4caa7f665159dc107911e708031e648c4/src/pages/iou/request/step/IOURequestStepScan/index.native.tsx#L617

```TSX
    resizeMode="contain"
```

2. Also change the background to black if needed.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by greg-schroeder** [comment] 2024-11-08 18:24
Proposal review up next

**Comment by alitoshmatov** [comment] 2024-11-10 20:10
@QichenZhu Thank you for your proposal, I don't think we should change preview mode as it affects design significantly. I think our goal is making final image the same as what preview is showing right now

**Comment by QichenZhu** [comment] 2024-11-11 12:14
## Proposal
[**Updated:** Added an alternative solution.](https://github.com/Expensify/App/issues/51499#issuecomment-2453798344)

**Comment by QichenZhu** [comment] 2024-11-11 12:18
@alitoshmatov Thanks for your review. I agree that cropping the photo to fit the preview window is straightforward, but it zooms in the photo and doesn't fully utilize the camera's physical pixels, which goes against the purpose of using the wide-angle and ultra-wide-angle cameras.

https://github.com/Expensify/App/blob/12233119e9b4793b32ed2c8b38366097a0efc792/src/pages/iou/request/step/IOURequestStepScan/index.native.tsx#L65

Should we check with the design team?

**Comment by alitoshmatov** [comment] 2024-11-11 18:07
Ok. @greg-schroeder Can we make sure what is expected behavior here:

A) Match resulting image to the what user sees in the preview right now
B) Change preview to show fully expected image, which means preview would be taller rectangle possible having blank spaces on the side

**Comment by greg-schroeder** [comment] 2024-11-11 20:30
I don't actually know. I've asked for the team to weigh in [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1731356985916479) -- will update shortly

**Comment by greg-schroeder** [comment] 2024-11-13 04:42
I bumped the team again as nobody seems to know 😅

**Comment by greg-schroeder** [comment] 2024-11-15 08:57
Team agrees that current behavior is actually fine. So I'm going to close this.

**Closed by greg-schroeder** 2024-11-15 08:57 UTC
Labels: External, Daily, Help Wanted, Bug
