### ISSUE TITLE
[HOLD for payment 2024-02-26] HIGH: Show "Workspace description" everywhere (2/2, external)

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#32955] opened 2023-12-13 01:55 UTC
*Note: This is held on https://github.com/Expensify/App/issues/32954 to fix a confusing name before we build on it further, as well as on https://github.com/Expensify/App/issues/32615 to provide the foundation for room descriptions and description editing*

**Problem:**
We have a "workspace welcome message" that is confusingly named (and will be renamed to "workspace description") and used unpredictably:

1. It is saved for the next invite, but cannot be edited outside of the invite flow
2. It is sent a standalone workspace invite email 
3. It is sent *again* in a whisper in the new workspace chat

It's a strangely important and yet hidden feature.

**Solution:**
Let's show this important information in more places:

1. Similar to what is proposed for editing the [room description](https://github.com/Expensify/App/issues/32615), show the "workspace description" as an HTML output (ie, with hyperlinks) that can be tapped to edit via push-to-page.  This will not only make it more obvious how to set it, but also show it to members looking at the workspace.

```
+-------------------------+
| < Workspace             |
|           +----+        |
|           |    |        |
|           |    |        |
|           +----+        |
|       Expensify Chat    |
|                         |
| (workspace description) | <- Show HTML description; push to page to edit
|                         |
| S Settings              |
| C Cards                 |
| R Reimbursements        |
| B Bills                 |
| I Invoices              |
| T Travel                |
| M Members               |
| B Bank account          |
| D Delete workspace      |
|                         |
|                         |
|                         |
+-------------------------+
```
2. This description will live in the `description` field on the policy in Onyx and be updated via the `UpdateWorkspaceDescription` API command

3. We should support the `POLICYCHANGELOG_UPDATE_DESCRIPTION` reportAction for displaying the changelog for the description in the #admins room

4. Let's remove the "add message" page from the invite flow altogether. 

<img width="324" alt="image" src="https://github.com/Expensify/App/assets/1371996/9db351b6-d9e7-4cf4-b759-f312b8638a69">

5. Let's se the workspace description *as the room description* for the workspace chat.  So replace this message:

> Collaboration between David Barrett and Expensify Inc. (NewDot Test Workspace) starts here! 🎉 This is the place to chat, request money and settle up.

With the workspace description:

> Welcome to our NewDot test policy.  You have been invited to submit ...

In this image:

<img width="1054" alt="image" src="https://github.com/Expensify/App/assets/575186/cfcc24b8-6fcf-4b0d-b3e7-b8ff23157673">

This should reuse the the [new room description](https://github.com/Expensify/App/issues/32615) feature code, so it'll appear both in the room description, as well as in the header:

<img width="324" alt="image" src="https://github.com/Expensify/App/assets/575186/6db0f831-5db6-4139-a6e5-61355e520051">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01172a1898d99f6e20</li>
        <li>Upwork Job ID: 1747013547396116480</li>
        <li>Last Price Increase: 2024-01-15</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28108605</li>
<li>esh-g | Contributor | 28108607</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-12-28 14:41
# Proposal

## Please re-state the problem we are trying to solve?
Change 'workspace welcome message' to 'workspace description` and implement design

## What is the root cause of the problem?
N/A (New feature)

## What changes should be made to fix this?
1. To add the `Description` menu field to the `WorkspaceInitialPage` we can just add a `MenuItemWithTopDescription` just like I proposed for the `roomDescription` page here: https://github.com/Expensify/App/issues/32615#issuecomment-1870782450
We would also need to add a `WORKSPACE_DESCRIPTION` route and page for that route which can be just like the `WelcomeMessage` page for room description using the utilities that will be implemented in the internal issue.
```js
<MenuItemWithTopDescription
      shouldShowRightIcon={isPolicyAdmin}
      description={translate('common.description')}
      title={policy.description}
      shouldRenderAsHTML
      onPress={() => Navigation.navigate(ROUTES.WORKSPACE_DESCRIPTION.getRoute(policyID))}
  />
```

2. As for displaying the header, I have already included it [my proposal for `roomDescription`](https://github.com/Expensify/App/issues/32615#issuecomment-1870782450)
<img width="411" alt="Screenshot 2023-12-28 at 8 10 54 PM" src="https://github.com/Expensify/App/assets/77237602/714b695b-79a9-4be7-b285-f120d1b4dfde">


3. Now for the Welcome message text, we can once again use the same approach used in [my proposal for `roomDescription`](https://github.com/Expensify/App/issues/32615#issuecomment-1870782450) here:
https://github.com/Expensify/App/blob/88d837c2e88c8c4c22a4c80f93b622d634e67290/src/components/ReportWelcomeText.js#L83-L90
```js
{policy.description ? <RenderHTML html={policy.description} /> : (
```

**Comment by esh-g** [comment] 2024-01-16 16:45
one proposal to review here: https://github.com/Expensify/App/issues/32955#issuecomment-1871236364

**Comment by puneetlath** [comment] 2024-01-17 16:51
@jjcoffee when do you think you'll be able to review?

**Comment by jjcoffee** [comment] 2024-01-18 07:40
Ah apologies, I was waiting for this to come off hold! @esh-g's proposal looks good to me; they also worked on the room description PR so have good context for working on this too. 

The proposal doesn't deal with points 3&4 in the issue description directly, but I think they're straight forward enough that we can just work on them on the PR.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by puneetlath** [comment] 2024-01-18 18:45
I agree, sounds good.

**Comment by puneetlath** [comment] 2024-01-18 18:46
The API is on staging btw @esh-g

**Comment by quinthar** [comment] 2024-01-19 02:19
Awesome, what's the ETA for this issue?

**Comment by quinthar** [comment] 2024-01-21 23:01
@esh-g - Can you link to "the `roomDescription` PR"?  I'm not 100% sure what you are referring to.  Regardless, did it get done last week?  If not, what's the new ETA?

**Comment by esh-g** [comment] 2024-01-22 18:01
@quinthar Here you go: https://github.com/Expensify/App/pull/34150
Even after the BE changes hit staging, there was a discrepancy where the `UpdateRoomDescription` api call would return a description with `{html: string}` whereas `OpenReport` api call would just return `string`.
But @puneetlath insisted to go forward with the PR and the backend issue to be figured out after it was live.
I have made the expected changes in the PR and hope it can be reviewed soon and merged possibly in a couple of days (hopefully).

**Comment by quinthar** [comment] 2024-01-26 02:00
Ok, so am I correct in understanding that:
1. You are currently blocked on waiting for the *ROOM* description PRs to merge
2. And then you will reuse its code for this *WORKSPACE* description stuff
Is that right?  What exactly has to happen to move that forward?

**Comment by esh-g** [comment] 2024-01-26 06:42
Yes @quinthar that assessment is accurate. The [PR](https://github.com/Expensify/App/pull/34150) just got a new C+ assigned and hopefully the review can be completed soon.

**Comment by JmillsExpensify** [comment] 2024-01-27 16:23
I happened to run across this issue in the catch-up, and I noticed point 4. 

> 4. Let's remove the "add message" page from the invite flow altogether. 

> <img width="324" alt="image" src="https://github.com/Expensify/App/assets/1371996/9db351b6-d9e7-4cf4-b759-f312b8638a69">

I recommend that we remove this from the solution. As part of an upcoming release, internally called "Simplified Collect", we're going to do two things in this flow:

 - Send the description of the workspace to all invited members
 - All admins to add an additional custom message 

Basically, adding a message on invite is one of the most popular features in the invite flow. I don't agree that we should remove it in this issue, as we're just going to add it back in short order.

**Comment by puneetlath** [comment] 2024-02-07 15:44
@esh-g I believe you said you expect to have a PR for this one ready today, is that right?

**Comment by esh-g** [comment] 2024-02-07 18:44
Made the PR here: https://github.com/Expensify/App/pull/36058
Some polishing and adding test steps is left. I'll add the steps ASAP.

**Comment by puneetlath** [comment] 2024-02-12 21:00
Yes, sounds good. We can always decide to do that after. It doesn't need to be a blocking decision for this PR for sure.

**Comment by puneetlath** [comment] 2024-02-14 15:34
PR was merged. 

Putting this from @jjcoffee here, so we don't forget: 
>[@puneetlath](https://github.com/puneetlath) Just wanted to flag a few issues that haven't been fixed here.
[Bug](https://github.com/Expensify/App/pull/36058#issuecomment-1935863928): Android Native: The description text input doesn't immediately render at the correct size. - we decided this is most likely unrelated to this PR and should be fixed either separately or on a followup.
[Bug](https://github.com/Expensify/App/pull/36058#issuecomment-1938503411): Sign out and sign in again, open a workspace chat with a description set. The chat initially shows "Workspace chat" before the actual description loads. (I couldn't replicate the same thing for room descriptions). - this [seems](https://github.com/Expensify/App/pull/36058#issuecomment-1938667091) like a BE issue
[Bug](https://github.com/Expensify/App/pull/36058#issuecomment-1938464518): refreshing after navigating to the settings page to edit the description will display the chat in the background, rather than the settings page. - we've agreed [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1707751366198779?thread_ts=1706584967.766219&cid=C01GTK53T8Q) that this shouldn't be a blocker (I believe this should be fixed at some point though!)

**Comment by jjcoffee** [comment] 2024-02-28 11:41
**Regression Test Proposal**

1. Navigate to the settings tab for any workspace and add a description
2. Verify that the description is saved
3. Go to the policy expense chat
4. Verify that the added description is shown both in header and chat masthead
5. Verify that clicking on the header description or chat masthead description opens the description edit page
6. Update the description
7. Verify that the #admins workspace room has the updated description report action

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2024-02-29 09:24
@puneetlath Friendly bump for payment on this :bow:

**Comment by puneetlath** [comment] 2024-02-29 16:10
Sorry for the delay. All paid. Thanks y'all!

**Closed by puneetlath** 2024-02-29 16:10 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
