### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] The "Not Found" page does not display when we press on the deleted message link.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50120] opened 2024-10-02 22:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727868246323429

## Action Performed:
1. Go to any chat.
2. Long-press on any message that you have sent and select "Copy Link."
3. Send that link in the chat.
4. Delete the message for which you selected "Copy Link."
5. Press on the link in the chat.
6. The user scrolls in the chat, but the "Not Found" page does not appear.
7. Now press any pressable on the page, e.g., Emoji.
8. Now, we can see the "Not Found" page after pressing the button.

## Expected Result:
The "Not Found" page should be visible immediately if the message is deleted.
## Actual Result:
The "Not Found" page does not display when we press on the deleted message link.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7fa3489a-b512-41c5-a4ea-f62834cf1ba9

https://github.com/user-attachments/assets/c4104637-fe09-4179-95a9-89dd182f9c16

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841649844209879395</li>
        <li>Upwork Job ID: 1841649844209879395</li>
        <li>Last Price Increase: 2024-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104343030</li>
<li>Nodebrute | Contributor | 104343031</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by greg-schroeder** [comment] 2024-10-03 01:21
Typically I'd put this in #vip-vsb but that project is closed/paused. It sounds like this kind of chat bugs falls under #newdot-quality now per DBs comment [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1727455774700809).

**Comment by huult** [comment] 2024-10-04 08:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

he "Not Found" page does not display when we press on the deleted message link.

### What is the root cause of that problem?

`prevIsLinkedActionDeleted` returns `undefined` because the previous value is `undefined`. As a result, the "Not found" page cannot be displayed due to this condition
https://github.com/Expensify/App/blob/f83b69e45451946c7505b773fb6e085fb2fe66c0/src/pages/home/ReportScreen.tsx#L364

### What changes do you think we should make in order to solve the problem?
To resolve this issue, we simply trigger an update to the value of prevIsLinkedActionDeleted(https://github.com/Expensify/App/blob/main/src/pages/home/ReportScreen.tsx#L340). 
```diff
// .src/pages/home/ReportScreen.tsx#L666
useEffect(() => {
        // If the linked action is previously available but now deleted,
        // remove the reportActionID from the params to not link to the deleted action.
        const isLinkedActionBecomesDeleted = prevIsLinkedActionDeleted !== undefined && !prevIsLinkedActionDeleted && isLinkedActionDeleted;
        if (!isLinkedActionBecomesDeleted) {
+           if (!isLinkedActionInaccessibleWhisper && isLinkedActionDeleted) {
+                fetchReportIfNeeded();
+            }
            return;
        }
        Navigation.setParams({reportActionID: ''});
-    }, [prevIsLinkedActionDeleted, isLinkedActionDeleted]);
+   }, [prevIsLinkedActionDeleted, isLinkedActionDeleted, isLinkedActionInaccessibleWhisper, fetchReportIfNeeded]);
```
<summary>
<details>POC

https://github.com/user-attachments/assets/b89886fe-73a8-4c54-8cb7-26e29b0da459

</details>
</summary>

**Comment by greg-schroeder** [comment] 2024-10-14 21:49
PR is up, looks like waiting on @aldo-expensify to review next!

**Comment by aldo-expensify** [comment] 2024-10-15 17:26
Merged

**Closed** 2024-10-24 22:54 UTC
Labels: External, Weekly, Awaiting Payment, Bug
