### ISSUE TITLE
[$500] IOU - Missing Tag violation on IOU details page when tag was disabled in OD

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36380] opened 2024-02-12 21:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35048

## Action Performed:
Precondition: set up Admin and Employee accounts and add only one tag to the workspace in OD
1. Open app
2. Sign in with Employee account
3. Click on FAB
4. Select Request money > manual
5. Write any amount and click on Continue button
6. Select the Workspace room
7. Click on "Show more"
8. Select the custom tag
9. Click on merchant and write any name
10. Click on Request button
11. Navigate to OD and sign in as Admin account
12. Disable the custom tag selected in step 8
13. Navigate to app > IOS details page
14. Refresh the page

## Expected Result:
The tag violation should be displayed on the IOU details page

## Actual Result:
The tag violation is missing on the IOU details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2ad73c6d-11b0-4eaa-83b8-27029e0a8acb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da546d53cc21957d</li>
        <li>Upwork Job ID: 1757158561545486336</li>
        <li>Last Price Increase: 2024-02-12</li>
    </ul>
</details>

**Comment by brandonhenry** [comment] 2024-02-15 16:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem is that when a custom tag is selected for an IOU and then later disabled by an admin in Old Dot (OD), the expected tag violation does not appear on the IOU details page within the app. This leads to improper functionality due to a disabled tag being able to be used for an IOU.

### What is the root cause of that problem?
The root cause seems to be a failure in the app's logic to check for tag status changes in OD after an IOU is created. There appears to be either a missing real-time update flow from OD to the app or a lack of validation check for tag status when displaying the IOU details.

### What changes do you think we should make in order to solve the problem?

- Implement a mechanism to sync policy updates from OD in real-time or via periodic checks to ensure the app has the latest policy settings.
- Introduce a validation check in the IOU details page logic to verify the status of the tag and display a violation if the tag has been disabled after the IOU was created.
- Update the state management within the app to reflect any changes in tag status and trigger UI updates accordingly.
- Perform thorough testing on all platforms to validate that tag violations appear as expected when tags are disabled post-IOU creation.

### What alternative solutions did you explore? (Optional)

An alternative could be to prevent the disabling of tags in OD if they have been used in any outstanding IOUs, thus avoiding this issue altogether.

**Comment by allroundexperts** [comment] 2024-02-17 03:44
Thanks for your proposal @brandonhenry. Your proposal seems too generic and does not provide a clear cut solution.

**Comment by allroundexperts** [comment] 2024-02-17 03:44
Still looking for more proposals.

**Comment by brandonhenry** [comment] 2024-02-17 21:02
@allroundexperts i did some more digging on this one and I wonder if this issue is well defined? The video shows interaction with the workspace via Expensify Classic and the workspace of New Expensify. Are these supposed to be connected? I am currently have issues with there seemingly being two types of workspaces? The New Expensify workspace settings doesn't seem to have a tag option and I can't seem to get any workspace made inside of Expensify classic to show up in New Expensify. 

Maybe this one is a bit beyond me for my first contributor assist but I am curious why I am having the user experience I am. 

Reproduce steps:
1. Login to admin account
2. Go to Expensify classic
3. Settings -> New Workspace
4. Go to New Expensify
5. Notice you cannot see the workspace that was just made in classic

If you create the workspace in New Expansify first, you cannot see that workspace inside of classic either. In addition, I do not see any way to create a non-free workspace inside of New Expansify, so i am unable to work with tags inside of the New Expansify app..

**Comment by brandonhenry** [comment] 2024-02-17 21:06
Going to still do some digging but was finding it hard to find the particularly screen shown in the original post without being able to access a paid workspace inside of New Expansify..

**Comment by brandonhenry** [comment] 2024-02-17 21:43
@allroundexperts managed to find the hopeful culprit.

##  Updated Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem is that when a custom tag is selected for an IOU and then later disabled by an admin in Old Dot (OD), the expected tag violation does not appear on the IOU details page within the app. This leads to improper functionality due to a disabled tag being able to be used for an IOU.

### What is the root cause of that problem?
The root cause seems to be a failure in the app's logic to check for tag status changes in OD after an IOU is created. There appears to be either a missing real-time update flow from OD to the app or a lack of validation check for tag status when displaying the IOU details.

### What changes do you think we should make in order to solve the problem?

[// Inside the MoneyRequestView component ](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/components/ReportActionItem/MoneyRequestView.tsx#L374)

In order for the error to properly show when a tag is disabled / not there, we need to update the inline error property for the MenuItem to check if the tag is available and enabled like so:

```

const isTagDisabled = policyTags?.[transactionTag]?.isEnabled === false;

// When rendering the tag field
{shouldShowTag && (
    <OfflineWithFeedback pendingAction={getPendingFieldAction('tag')}>
        <MenuItemWithTopDescription
            description={policyTag?.name ?? translate('common.tag')}
            title={PolicyUtils.getCleanedTagName(transactionTag ?? '')}
            interactive={canEdit}
            shouldShowRightIcon={canEdit}
            titleStyle={styles.flex1}
            onPress={() =>
                Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_TAG.getRoute(CONST.IOU.ACTION.EDIT, CONST.IOU.TYPE.REQUEST, transaction?.transactionID ?? '', report.reportID))
            }
            brickRoadIndicator={isTagDisabled ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : undefined}
            error={isTagDisabled ? translate('common.error.tagDisabled') : ''}
        />
    </OfflineWithFeedback>
)}
```

### What alternative solutions did you explore? (Optional)

An alternative could be to prevent the disabling of tags in OD if they have been used in any outstanding IOUs, thus avoiding this issue altogether.

**Comment by allroundexperts** [comment] 2024-02-19 04:30
@brandonhenry Thanks for the updated proposal. Your proposal is making sense now. However, I am unsure what exactly is the expected behaviour of this issue. Pulling in an internal engineer for further discussion 🎀 👀 🎀

**Comment by allroundexperts** [comment] 2024-02-19 04:50
@neil-marcellini Shouldn't the backend be attaching a violation to the `transaction` object in the case where a used tag gets disabled in admin? If so, then this should be handled on the backend.

**Comment by cead22** [comment] 2024-02-19 23:48
I think we should put a hold on this issue, since this is a known issue that we need to holistic solution for, because updating tags is only one case where the violations displayed in the UI might be outdated.

The tag change on old dot should push the updated tag lists to the relevant new dot clients, but that alone doesn't trigger the re-render of the money request view (or money request preview, or report preview) to display violations

**Comment by neil-marcellini** [comment] 2024-02-20 18:33
Ok sounds good @cead22. What issue should we hold this on?

**Comment by cead22** [comment] 2024-02-20 18:35
We don't have one yet. Should we make this one internal, and I'll take it over, or do you think it's better that I create a new one?

**Comment by cead22** [comment] 2024-02-20 21:11
Actually, let's close this in favor of https://github.com/Expensify/App/issues/34541 since it's a dupe

**Closed by cead22** 2024-02-20 21:11 UTC
Labels: External, Daily, Help Wanted, Bug
