### ISSUE TITLE
[HOLD for payment 2024-12-16] [$250]  No way to save a search after searching for a custom query

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53036] opened 2024-11-23 19:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation** (hyperlinked to channel name): [expensify-expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1732198278634479)

## Action Performed:
1. Go to search
2. Click on search 
3. Enter any query to give results
4. Click filters
## Expected Result:
Should have an option to save the results
## Actual Result:
No option to save the search for a custom query
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/59a11bdb-9b16-4d18-a3cc-57f4d8b42b5a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861022728491645753</li>
        <li>Upwork Job ID: 1861022728491645753</li>
        <li>Last Price Increase: 2024-11-25</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 105057798</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by Shahidullah-Muffakir** [comment] 2024-11-24 19:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a query is entered in the `SearchRouter`, the `Save Search `button does not appear in the `AdvancedSearchFilters`. Currently, it only appears if a filter is applied from `AdvancedSearchFilters`
### What is the root cause of that problem?
The issue lies here where it determines whether the **Save Search** button should be displayed:
the Save Search button is displayed only if certain filters are applied.

https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/pages/Search/AdvancedSearchFilters.tsx#L404
https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/libs/SearchQueryUtils.ts#L630-L638
This restriction was introduced to prevent showing the button for "canned" (default) search queries.

However, when a user manually inputs a query, the code does not account for this case, leading to the button not being displayed.
### What changes do you think we should make in order to solve the problem?
We have two options
Option 1:  Include the searchAdvancedFilters.keyword Check
https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/pages/Search/AdvancedSearchFilters.tsx#L404
 as: 
 ` const displaySearchButton = queryJSON && (!SearchQueryUtils.isCannedSearchQuery(queryJSON) || !!searchAdvancedFilters.keyword)`


Option 2. Check If `queryString` Is Not the Default

**Comment by Kicu** [comment] 2024-11-25 11:12
This feature works correctly IF values are picked using autocomplete suggestion list.
This issue/bug appears only when pasting in the full query, because then the autocomplete logic is not run as we don't know what `accountID` was picked.

The solution above is not the best way to solve this, as the core of the issue is the replacement of `user email <----> user id` both ways.
This was heavily discussed on slack here: https://swmansion.slack.com/archives/C06ML6X0W9L/p1732225727559059?thread_ts=1732198278.634479&cid=C06ML6X0W9L

Please assign me to this task, and I will take care of the email part of this issue, after https://github.com/Expensify/App/pull/52568 is merged.

CC @luacmartins

**Comment by luacmartins** [comment] 2024-11-25 18:49
Thanks @Kicu

**Comment by Kicu** [comment] 2024-11-29 10:00
I have not started working on this, but I will start as soon as I'm done with https://github.com/Expensify/App/pull/53198

**Comment by Kicu** [comment] 2024-12-03 11:12
I'm starting to work on this today.

**Comment by ikevin127** [comment] 2024-12-13 00:12
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by ikevin127** [comment] 2024-12-16 18:46
cc @twisterdotcom for visibility

**Comment by twisterdotcom** [comment] 2024-12-17 00:27
Payment Summary:

- @Kicu **does not** require payment (Contractor)
- @ikevin127 paid $250 [here](https://www.upwork.com/nx/wm/offer/105057798) (Reviewer)

**Closed** 2024-12-17 00:42 UTC
Labels: External, Daily, Awaiting Payment, Bug
