### ISSUE TITLE
New Room - The room notifications change randomly

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11262] opened 2022-09-24 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Click on FAB button/New Room/create New Room
3. Tap on "Settings"
4. Disable the internet connection on the device
5. Change the name of the #Room and Click/tap Save
6. Change the notification settings for couple times
7. Go back online

## Expected Result:
The room settings should not change randomly after coming back online

## Actual Result:
The room settings change randomly after coming back online

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.6.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192102893-3f3fd06d-84fd-47cb-9c46-f8e063b7b391.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2022-09-24 14:25
This issue could be the same root of cause https://github.com/Expensify/App/issues/11126

**Comment by amyevans** [comment] 2022-09-27 16:57
Reproducible on the `main` branch locally.

This looks like another manifestation of the problem described by @jasperhuangg [in this Slack thread](https://expensify.slack.com/archives/C03TQ48KC/p1663797332998359) / https://github.com/Expensify/Expensify/issues/229696.

So we should keep this issue `Internal`. @jasperhuangg do you want to take it?

**Comment by mvtglobally** [comment] 2022-10-18 11:27
Issue not reproducible during KI retests. (First week)

**Comment by Christinadobrzyn** [comment] 2022-10-19 02:47
I think this was assigned the wrong way - should have gone first to triage and then to Eng. I'm asking [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1666147427523899) just to make sure there isn't a workflow change that hasn't been updated in this triage [SO](https://stackoverflow.com/c/expensify/questions/4749).

**Comment by roryabraham** [comment] 2022-10-31 16:28
Still on HOLD

**Comment by roryabraham** [comment] 2022-11-14 21:22
Since https://github.com/Expensify/App/pull/12219 was deployed to production, I'm guessing this issue is no longer reproducible.

**Comment by roryabraham** [comment] 2022-11-14 21:27
Sorry @slafortune, should've used the `Bug` label. Confirmed that this is still reproducible.

**Comment by roryabraham** [comment] 2022-11-14 23:39
Got a PR to fix this halfway: https://github.com/Expensify/App/pull/12728

**Comment by roryabraham** [comment] 2022-11-14 23:58
Second PR to fix this the rest of the way: https://github.com/Expensify/Web-Expensify/pull/35572

**Comment by maddylewis** [comment] 2022-11-15 19:56
BUG issue checklist:
- [ ] The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)
- [ ] The bug is reproducible, follow the reproduction steps 
- [ ] The GH is filled out as clearly as possible
- [ ] Review Slack convo to confirm we should fix this
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer
- [ ] Add Internal or External label

_BUG GHs should remain Daily until closed or until the associated PR has been deployed to production and the GH title has been updated with "[HOLD for payment]" where payment is due in 7 days if no regressions._

**Comment by kbecciv** [comment] 2022-11-18 15:55
Updated the title with platforms, this PR https://github.com/Expensify/App/pull/12728  is Fail in Android and IOS app

https://user-images.githubusercontent.com/93399543/202746728-9ce15560-d811-49b6-a179-bfea14dc0432.MP4


https://user-images.githubusercontent.com/93399543/202746733-264ed169-300a-4620-ad05-4fc83c981036.mp4

**Comment by roryabraham** [comment] 2022-11-18 17:27
Okay, let's wait for the second half of the fix https://github.com/Expensify/Web-Expensify/pull/35572 and see if it's still reproducible after that. Also we should create a separate issue for this:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/47436092/202765342-e1ad0b61-a03d-4ae4-bab4-e24499c63071.png">

**Comment by mvtglobally** [comment] 2022-11-22 21:00
Issue not reproducible during KI retests. (Second week)

**Comment by roryabraham** [comment] 2022-11-28 20:46
I think this is fixed now, the BugZero checklist is all that's left to do here.

**Comment by mvtglobally** [comment] 2022-11-30 04:58
Issue not reproducible during KI retests. (Third week) Are we ok to close now?

**Comment by roryabraham** [comment] 2022-11-30 21:49
> The PR that introduced the bug has been identified

I didn't do this, but I don't think it was necessarily a regression.

**Comment by roryabraham** [comment] 2022-11-30 21:57
Filling out the remainder of the BZ checklist:

> A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again

Not needed, since this is already covered by an [existing regression test](https://expensify.testrail.io/index.php?/tests/view/2894086&group_by=cases:section_id&group_order=asc&group_id=229067)

> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake

n/a since this wasn't a regression

> A discussion in #contributor-plus has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner

n/a since this wasn't a regression 

>  Payment has been made

The only payment due is the C+ review payment to @eVoloshchak for https://github.com/Expensify/App/pull/12728

**Comment by roryabraham** [comment] 2022-11-30 21:58
@maddylewis Let's pay @eVoloshchak the standard amount for their review of https://github.com/Expensify/App/pull/12728, then close this out

**Comment by maddylewis** [comment] 2022-12-01 13:45
thanks for the bump @roryabraham - on it!

**Comment by maddylewis** [comment] 2022-12-01 16:50
sent @eVoloshchak the offer here - https://www.upwork.com/ab/applicants/1598314928368742400/job-details

**Comment by eVoloshchak** [comment] 2022-12-01 17:48
> sent @eVoloshchak the offer here - https://www.upwork.com/ab/applicants/1598314928368742400/job-details

Accepted

**Comment by maddylewis** [comment] 2022-12-01 19:29
@eVoloshchak paid: $250

milestone closed in UW - we should be all set 👍

**Closed by maddylewis** 2022-12-01 19:29 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
