### ISSUE TITLE
[HOLD for payment 2023-12-29] [$500] mWeb/Chrome-Contact methods-Confirmation window moves when trying to remove secondary contact method

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32262] opened 2023-11-30 12:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.5-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings - Profile - Contact method - New contract method
4. Add a new contract method, but not validate
5. Open just added contact method
6. When the keyboard opens, tap on the remove button

## Expected Result:
Confirmation window not moves

## Actual Result:
Confirmation window moves

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3a553cef-285c-4564-84d5-5281d1889f28

![Bug6295867_1701344893403!Screenshot_2023-11-29-23-20-08-17_99c04817c0de5652397fc8b56c3b3817](https://github.com/Expensify/App/assets/115492554/1a8fc897-217b-4b90-b19b-2801a8b98bbe)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d076df7ad5db3f2</li>
        <li>Upwork Job ID: 1730200102411456512</li>
        <li>Last Price Increase: 2023-11-30</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28035618</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-11-30 15:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Confirmation window moves
### What is the root cause of that problem?
Because keyboard is closed During show the modal.
### What changes do you think we should make in order to solve the problem?
we need update like this.
```
toggleDeleteModal(isOpen) {
        Keyboard.dismiss();
        InteractionManager.runAfterInteractions(() => {
                 this.setState({isDeleteModalOpen: isOpen});
        });
}
```
https://github.com/Expensify/App/blob/e2f421491cfe87878a21a212b927b1bd9107cfc6/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L211-L215
### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment] 2023-12-04 17:47
Hey @allroundexperts we've got a few proposals here for review -- can you take a look please?

**Comment by allroundexperts** [comment] 2023-12-05 00:58
I think this is a trivial case which can be solved in a relatively simple way by using `InteractionManager`. Since its being used elsewhere as well, I would prefer this over other solutions which are more complex.

Since @dukenv0307 was the first to propose the above, I say we go with there [proposal](https://github.com/Expensify/App/issues/32262#issuecomment-1833680475).

The assigned internal engineer can double confirm this though.

🎀 👀 🎀 C+ reviewed

**Comment by stephanieelliott** [comment] 2023-12-08 17:39
Hey @grgia, can you help us confirm [this comment](https://github.com/Expensify/App/issues/32262#issuecomment-1839819431)?

> I think this is a trivial case which can be solved in a relatively simple way by using InteractionManager. Since its being used elsewhere as well, I would prefer this over other solutions which are more complex.
> 
> Since @dukenv0307 was the first to propose the above, I say we go with there https://github.com/Expensify/App/issues/32262#issuecomment-1833680475.
> 
> The assigned internal engineer can double confirm this though.
>

**Comment by grgia** [comment] 2023-12-11 15:36
@allroundexperts @dukenv0307 proposal looks good to me, assigned!

**Comment by stephanieelliott** [comment] 2023-12-19 22:03
PR is merged and undergoing QA!

**Comment by grgia** [comment] 2024-01-02 21:02
@stephanieelliott I think this one's ready for payment, let me know if you need anything from me!

**Comment by stephanieelliott** [comment] 2024-01-03 14:13
This is all paid!

**Closed by stephanieelliott** 2024-01-03 14:13 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by situchan** [comment] 2024-01-05 14:52
@stephanieelliott there was [regression](https://github.com/Expensify/App/issues/33410) which was not handled by original author / reviewer

**Comment by situchan** [comment] 2024-01-05 14:54
If this doesn't apply penalty, along with https://github.com/Expensify/App/issues/33410#issuecomment-1866784975, I will take this for future reference.

**Comment by situchan** [comment] 2024-01-05 15:08
ok so I'd like to confirm that original folks don't take responsible for follow-up issues caused by their PR if they're not counted as regression.
