### ISSUE TITLE
[$1000] System throws an error when user request an IOU to the secondary login account 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18810] opened 2023-05-12 02:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with account A
2. Add account B as a secondary login in the contact methods section
3. Open new tab (window) & sign in with account C
4. Click on 'FAB' icon
5. Click on 'Split bill' link
6. Enter amount, and click on 'Next' button
7. Enter secondary login account B in the search field, and select the account 
8. Click on 'Next' button
9. Click on 'Split' button

## Expected Result: 
Systems should send a successful IOU request
## Actual Result: 
System throws an error message
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/218d4c6b-15d2-40cf-8a48-211fa3cbfb31

https://github.com/Expensify/App/assets/43996225/10a38a39-31ef-437b-a292-77f85c1ff7c6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683793394254349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01de99bdd46652a0b4</li>
        <li>Upwork Job ID: 1658035527396896768</li>
        <li>Last Price Increase: 2023-05-15</li>
    </ul>
</details>

**Comment by zanyrenney** [comment] 2023-05-15 09:03
Thanks for this!

**Comment by hungvu193** [comment] 2023-05-15 10:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
System throws an error when user request an IOU to the secondary login account
### What is the root cause of that problem?
We are blocking user from creating IOU to their login list on the server, but doesn't validate it from client. So when an user tried to create IOU to the secondary account, it will show the generic error.

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/components/MoneyRequestConfirmationList.js#L263
Right now, in `MoneyRequestConfirmationList` we only disable the bottom button if the selected participants length equals to 0. We can improve that by checking if inside  selected participants have user from loginList then disable the button, we can also show a message to let user know they shouldn't create IOU request to themself.
So the shouldDisableButton condition will look like this:
```javascript
 const isIncludeCurrentUSer = _.some(selectedParticipants, OptionsListUtils.isCurrentUser);
 const shouldDisableButton = selectedParticipants.length === 0 || isIncludeCurrentUSer;
```
We can also add a error message at the Footer of the component to let user know they shouldn't request money to themself.
```javascript
                footerContent={
                    <>
                        {shouldShowSettlementButton ? (
                            <SettlementButton
                                isDisabled={shouldDisableButton}
                                onPress={this.confirm}
                                shouldShowPaypal={Boolean(recipient.payPalMeAddress)}
                                enablePaymentsRoute={ROUTES.IOU_SEND_ENABLE_PAYMENTS}
                                addBankAccountRoute={ROUTES.IOU_SEND_ADD_BANK_ACCOUNT}
                                addDebitCardRoute={ROUTES.IOU_SEND_ADD_DEBIT_CARD}
                                currency={this.props.iou.selectedCurrencyCode}
                            />
                        ) : (
                            <ButtonWithMenu
                                isDisabled={shouldDisableButton}
                                onPress={(_event, value) => this.confirm(value)}
                                options={this.getSplitOrRequestOptions()}
                            />
                        )}
                        {isIncludeCurrentUSer && <FormHelpeMessage message={"You can't send IOU request to yourself"} />}
                    </>
                }
```
### What alternative solutions did you explore? (Optional)
Do nothing

### Result

**Comment by zanyrenney** [comment] 2023-05-15 17:12
Not overdue, waiting on the proposals and for @deetergp view on which is the best :)

**Comment by deetergp** [comment] 2023-05-15 21:47
I'm removing both the `External` and `Help Wanted` labels, as these errors are coming from the deepest depths our back end. Additionally, I think there needs to be a deep discussion about how we want this to work before we start planning how to fix it.

**Comment by deetergp** [comment] 2023-05-16 20:58
This is being discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1684188424832229).

**Comment by deetergp** [comment] 2023-05-19 20:40
There has been more discussion, but no real decision on how we're going to approach it. I'm going to downgrade this to a weekly but it will likely get closed.

**Comment by zanyrenney** [comment] 2023-05-25 17:34
Cool, thanks @deetergp . I am going OOO so if it doesn't get closed and you need BZ management, please reapply the label!

**Comment by hungvu193** [comment] 2023-05-26 07:11
For more context, after this PR https://github.com/Expensify/App/pull/19431#issuecomment-1563907063 is merge. We will block user from messaging their other contact method email and they can't send IOU request to these account any more. I think we can close this one.

**Closed** 2023-05-26 21:16 UTC
Labels: Daily, Bug
