### ISSUE TITLE
mWeb - Cursor is not showing properly on multiline field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23347] opened 2023-07-21 11:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any #announcement of WS
2. Click on #announcement for details view
3. Click on setting and select welcome messages
4. Click on message field and go to next line

## Expected Result:
Cursor should show properly

## Actual Result:
Cursor is show in middle of textfield line and message area.
This issue is all multiline field.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f6a6d101-04ff-4be5-825a-bb77889a2d91

![IMG_3634](https://github.com/Expensify/App/assets/93399543/6e775b5d-98d2-4bfa-b8f5-e4eeec22f82e)

https://github.com/Expensify/App/assets/93399543/a2ab7820-1f95-45da-8b96-474f6ddebcf0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689868334427829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2023-07-21 11:16
dupe of https://github.com/Expensify/App/issues/21271

**Comment by sophiepintoraetz** [comment] 2023-07-25 01:30
Agreed dupe!

**Closed by sophiepintoraetz** 2023-07-25 01:30 UTC
Labels: Daily, Overdue, Bug
