### ISSUE TITLE
SignIn - Unable proceed to setting with new applausecard account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51478] opened 2024-10-25 15:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** tester+092424f@applausecard.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create new account on old dot [tester+092424f@applausecard.expensifail.com](mailto:tester+092424f@applausecard.expensifail.com)
(admin)
2. Login with same account on old App on iOS
3. Try to go to settings

## Expected Result:
Able to go to setting on OD App with new account

## Actual Result:
Unable proceed to setting with new applausecard account
1. App shown multi times popup "welcome to Expensify" and unable to proceed to settings
2. After reinstalling App: App freeze after login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ce961be0-63ee-4004-9375-a7497422edb9

https://github.com/user-attachments/assets/383de6f9-106a-42ab-91e3-1233c5e4b8e3

![9663](https://github.com/user-attachments/assets/50fdaf44-5001-4314-bf64-5365189a790d)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment] 2024-10-28 11:05
@lanitochka17 is this affecting only the applausecard accounts or other test domains as well?

**Comment by sonialiap** [comment] 2024-10-31 11:32
[Asking in slack](https://expensify.slack.com/archives/C9YU7BX5M/p1730374285592719)

**Comment by sonialiap** [comment] 2024-11-04 11:14
Seems like this might be specific to the applausecard.expensifail.com accounts, @AndrewGable does that make it internal?

**Comment by AndrewGable** [comment] 2024-11-11 18:01
I don't think that makes it internal per se, I think we need better reproduction steps before sending it internal or external.

**Comment by sonialiap** [comment] 2024-11-27 13:13
taking to slack

**Comment by izarutskaya** [comment] 2024-11-27 16:35
Issue not reproducible with applausetester@applause.expensifail.com domain

https://github.com/user-attachments/assets/9fd7d67f-6c13-459d-b0cb-a8ed66fe38c9

**Comment by sonialiap** [comment] 2024-12-04 11:05
@isabelastisser do you think this is a big issue for you guys? Since it's affecting login to old app with applausecard using a specific flow, seems like it might not be crucial? As I understand this flow is still possible with other QA accounts that aren't applausecard

**Comment by isabelastisser** [comment] 2024-12-05 16:02
@sonialiap, I agree that this is not crucial. Let's close this!

**Closed by isabelastisser** 2024-12-05 16:02 UTC
Labels: Weekly

**Comment by sonialiap** [comment] 2024-12-09 14:06
@isabelastisser whoops, sorry that was the wrong tag! I meant to tag izarutskaya 😆 Thank you for double checking though
