### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Android - Keyboard doesn't open automatically while verifying contact method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21415] opened 2023-06-23 14:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings -> Profile -> contact method
2. Go to new contact method
3. Enter email/phone and add
4. Now click the recently added mail/number to verify
5. Form field to enter magic code appears. However, Notice that there appears no keyboard to type .

## Expected Result:
Keyboard should be shown on default . like on magic code entry page in signing page.

## Actual Result:
Keyboard appears only after user click in verify new contact method page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**1.3.27-7

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b22d21fe-66b7-4d28-840d-cce75c284d9c

https://github.com/Expensify/App/assets/93399543/205de6c0-5627-471a-8a27-2c77c5ee08f7

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686916708232399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148ec17c8af49cf8c</li>
        <li>Upwork Job ID: 1672352190027980800</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-06-23 16:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Keyboard doesn't open in android when magic code input gets focused

### What is the root cause of that problem?
In android, keyboard doesn't open because of navigation transition.

### What changes do you think we should make in order to solve the problem?
**Solution 1:** use `shouldDelayFocus`

In /Contacts/BaseValidateCodeForm component:
- import shouldDelayFocus from /libs/shouldDelayFocus
- pass `shouldDelayFocus={shouldDelayFocus}` to `MagicCodeInput`

In MagicCodeInput component:
- If `shouldDelayFocus` = true, don't focus (both [manually](https://github.com/Expensify/App/blob/main/src/components/MagicCodeInput.js#L164) and [automatically](https://github.com/Expensify/App/blob/main/src/components/MagicCodeInput.js#L325))

**Solution 2:** remove `autoFocus` [here](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L136) and focus manually on `onEntryTransitionEnd` callback of `ScreenWrapper` in `ContactMethodDetailsPage`

**Comment by flaviadefaria** [comment] 2023-06-23 21:12
Hey @lukemorawski feel free to submit your proposal and it will be reviewed by the C+ like all others. If you have the best proposal you will be assigned to the GH.

**Comment by lukemorawski** [comment] 2023-06-26 09:14
@allroundexperts my solution is almost identical with an addtional removal of `autoFocus` prop from inputs as it's already handled by the programatically in on of the `useEffect` hooks. I can confirm that this solution works.

**Comment by situchan** [comment] 2023-06-26 11:04
> While we wait, @situchan, can you please verify that your solution 2 really works? Please post a video if possible.

yes it works but ref needs to be passed multiple times as BaseValidateCodeForm is not a direct children of ContctMethodDetailsPage. So I prefer Solution 1. If TextInput and ScreenWrapper are in the same component, maybe Solution 2 is prefered.
I don't think it's a problem whether to pick up Solution 1 or 2 because app already has those 2 inconsistent approaches of auto-focus across all the pages.
i.e. #15184 (shouldDelayFocus), #18889 (onEntryTransitionEnd)

**Comment by flaviadefaria** [comment] 2023-06-30 22:18
Waiting for PR

**Comment by techievivek** [comment] 2023-07-03 08:24
Assigned the task to @situchan, thanks.

**Comment by situchan** [comment] 2023-07-04 11:14
@allroundexperts [PR](https://github.com/Expensify/App/pull/22164) is ready for review

**Comment by flaviadefaria** [comment] 2023-07-18 10:21
Payment to be processed:

@ashimsharma10 = $250 (UW)
@allroundexperts $1000 + $500 bonus = $1500 (Expensify)
@situchan $1000 + $500 bonus = $1500  (UW)

@allroundexperts can you please fill out the checklist above so that I can process payment? Thanks!

**Comment by anmurali** [comment] 2023-07-20 01:55
Approved payment to @allroundexperts based on https://github.com/Expensify/App/issues/21415#issuecomment-1639950981

**Comment by ashimsharma10** [comment] 2023-07-21 08:20
@flaviadefaria Accepted the invitation. waiting for payment

**Comment by flaviadefaria** [comment] 2023-07-24 12:12
Oops, I was meant to send it to @situchan. Withdrawing it and sending it correctly to @situchan.

**Comment by flaviadefaria** [comment] 2023-07-24 12:17
Offer sent to @situchan 
@ashimsharma10 I can see two "Ashim S."  in Upworks, can you send me your profile link or clarify if you're the one based in Nepal or Bangladesh? Thanks!

**Comment by ashimsharma10** [comment] 2023-07-24 12:31
@flaviadefaria Nepal it is . Haha

**Comment by flaviadefaria** [comment] 2023-07-24 14:04
Offers sent! 
@situchan and @ashimsharma10 just need you to accept them so that I can pay you and close this :)

**Comment by flaviadefaria** [comment] 2023-07-24 14:25
@ashimsharma10 paid

**Comment by flaviadefaria** [comment] 2023-07-25 15:48
@situchan paid. Closing this.

**Closed by flaviadefaria** 2023-07-25 15:48 UTC
Labels: External, Daily, Awaiting Payment, Bug
