### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] Tax - Enable/disable option shows rates text in plural instead rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51017] opened 2024-10-17 13:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9. 0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap profile icon - workspaces -- workspace
3. Tap more features - enable taxes
4. Create few tax rates
5. Disable a tax rate
6. Long press and select one disabled and one enabled tax rate
7. Tap dropdown on top and view options

## Expected Result:
Enable/disable option must not show rates text in plural and it must show rate

## Actual Result:
Enable/disable option shows rates text in plural instead rate when only one enabled and disabled rate are selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/deec09fd-e1b3-41f3-9be1-106d776c3799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846961178055724837</li>
        <li>Upwork Job ID: 1846961178055724837</li>
        <li>Last Price Increase: 2024-11-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by lanitochka17** [comment] 2024-10-17 13:25
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Nodebrute** [comment] 2024-10-17 13:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Enable/disable option shows rates text in plural instead rate
### What is the root cause of that problem?
Here we only check if selected tags are more than 2
https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L186
### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by Nodebrute** [comment] 2024-10-17 13:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Enable/disable option shows rates text in plural instead rate 
### What is the root cause of that problem?
Here we only see if selected tags are more than 1 instead of checking disable/enable tags count
https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L186
### What changes do you think we should make in order to solve the problem?

We can create 2 new variables 
```
        const disableTaxes = selectedTaxesIDs.filter((taxID) => policy?.taxRates?.taxes[taxID]?.isDisabled);
        const enabledTaxes = selectedTaxesIDs.filter((taxID) => !policy?.taxRates?.taxes[taxID]?.isDisabled);
```

and then in here we can [check](https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L198) 
```
   if (disableTaxes.length > 0)
```
and in [here](https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L201) we can change this to  
```
 text: disableTaxes.length === 1 ?  translate('workspace.taxes.actions.disable') : translate('workspace.taxes.actions.disableMultiple'),
```

We can do same for enable tags
### What alternative solutions did you explore? (Optional)

**Comment by ChavdaSachin** [comment] 2024-10-17 13:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tax - Enable/disable option shows rates text in plural instead rate

### What is the root cause of that problem?
Irrespective of number of available rates to enable/disable, we check only for number of selections here.
https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L186
https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L201
https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L211

### What changes do you think we should make in order to solve the problem?
Rather create new objects `enabledRates` and `disabledRates`
```js
        const enbledRates = selectedTaxesIDs.filter((taxID) => policy?.taxRates?.taxes[taxID]?.isDisabled);
        const disabledRates = selectedTaxesIDs.filter((taxID) => !policy?.taxRates?.taxes[taxID]?.isDisabled);
```
now use `enabledRates?.length` here to saw the option
```js
        if (enabledRates?.length) {
```
https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L198
and use `enabledRates?.length > 1` instead of `isMultiple` here
https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L201
Similar for Enable option use 'disabledRates?.length' here.
```js
        if (disabledRates?.length) {
```
https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L208
And use `disabledRates?.length > 1` instead of `isMultiple` here.
https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L211

This way we optimize the solution and do not have to filter array twice.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ChavdaSachin** [comment] 2024-10-17 13:58
[Updated Proposal](https://github.com/Expensify/App/issues/51017#issuecomment-2419610766)
Added perfectly optimized way to solve the issue as alternate solution.

**Comment by isabelastisser** [comment] 2024-10-22 19:27
@getusha, can you please review the proposals above and provide an update? Thanks!

**Comment by isabelastisser** [comment] 2024-10-23 19:31
Bump @getusha for an update, thanks!

**Comment by isabelastisser** [comment] 2024-10-25 14:56
@twilight2294 @getusha, to clarify, is this issue fixed?

https://github.com/Expensify/App/issues/51017#issuecomment-2435031474

**Comment by techievivek** [comment] 2024-10-28 04:16
Given that we have fixed the same thing in the case of workspaces, I think we can fix this one too. @getusha, let's review the proposal. Thanks.

**Comment by isabelastisser** [comment] 2024-11-04 21:09
@techievivek, should we close this?

**Comment by isabelastisser** [comment] 2024-11-07 17:38
@getusha , please provide an update. Thanks!

**Comment by isabelastisser** [comment] 2024-11-08 21:30
Bump @getusha for an update. Thanks!

**Comment by techievivek** [comment] 2024-11-12 07:34
@getusha Do you have an update here? Can you check the comment here https://github.com/Expensify/App/issues/51017#issuecomment-2457134315

**Comment by isabelastisser** [comment] 2024-12-02 13:07
I was OOO last week, I will review this today.

**Comment by isabelastisser** [comment] 2024-12-02 16:39
@getusha, do we need a regression test?

**Comment by isabelastisser** [comment] 2024-12-02 16:41
Payment summary:

Reviewer: @getusha owed $250 via NewDot C+ `PENDING`
ROLE: @twilight2294 owed $250 via Upwork ([LINK](https://www.upwork.com/jobs/~021846961178055724837))

**Comment by isabelastisser** [comment] 2024-12-03 15:27
@getusha confirmed via DM that we don't need a regression test. all set!

**Closed by isabelastisser** 2024-12-03 15:27 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2025-01-29 21:07
$250 approved for @getusha
