### ISSUE TITLE
[HOLD for payment 2022-07-05] [$250] Remove button isn't disabled when a user is removed by pressing Enter/Return until cursor is moved - reported by  @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8935] opened 2022-05-11 03:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Open any workspace
3. Click Manage members
4. Select any member
5. Click on the remove button
6. Press enter/return key on the remove popup and keep the cursor still
7. Observe that the remove button is still enabled and clicking it does nothing
8. Now move the cursor and observe that the remove button disables

## Expected Result:
The remove button should be disabled right after the member is removed

## Actual Result:
The remove button doesn't disable until the cursor is moved

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.57-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/167765240-ba924ea7-89f1-4d74-8bb6-e89d4d9ac487.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649961947883629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment] 2022-05-12 13:54
This seems like a good candidate for external :)

**Comment by jliexpensify** [comment] 2022-05-13 06:17
Posted!

Internal - https://www.upwork.com/ab/applicants/1524997142160097280/job-details
External - https://www.upwork.com/jobs/~01e1184d00a75ad62c

**Comment by Subash-G** [comment] 2022-05-13 08:10
Hi... !

I can able to fix this issue. 

Solution:

Need to add disable condition like if the selected user list is empty - Disable the remove button. If the selected user list is contain data, Enable the remove button.

After every remove confirmation, need to clear the value in selected user list

**Comment by MarionRosete** [comment] 2022-05-14 03:53
Problem:
 Button integration
 Button State listener when user is selected 
Solution:
 Button behavior when hover out, hover in, clicked and select some users
 Button State Listener

**Comment by Santhosh-Sellavel** [comment] 2022-05-15 18:21
@MarionRosete @Subash-G 
Would you please elaborate on technical code changes, why this occurs or what causes the issue? so that I can review the proposal.

Look at this past [jobs](https://github.com/Expensify/App/issuesq=is%3Aissue+is%3Aclosed+label%3A%22Awaiting+Payment%22) as a reference to write proposals!

And If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) first!

**Comment by Subash-G** [comment] 2022-05-16 04:15
Hi @Santhosh-Sellavel 

The given past proposal link is not working. Can you send me again?

**Comment by Santhosh-Sellavel** [comment] 2022-05-16 05:01
updated the link @Subash-G

**Comment by Subash-G** [comment] 2022-05-18 11:51
Proposal:

Hi, I would like to do this work.

Solution:

Need to add condition check wheather button disabled or not

[   (this.props.danger && hovered) ? styles.buttonDangerHovered : undefined,](https://github.com/Expensify/App/blob/24294f27547eb88dde790f89a84230535ab9cb0b/src/components/Button.js#L269)


![remove](https://user-images.githubusercontent.com/55589996/169032107-3e91e359-9f91-430c-b25c-206c400dcee0.PNG)

**Comment by Subash-G** [comment] 2022-05-19 08:00
Hi @Santhosh-Sellavel  Kindly review this propsal

**Comment by Santhosh-Sellavel** [comment] 2022-05-19 21:01
@pecanoro this seems to dupe of #8934 i.e the cause is the same and handled by the  PR https://github.com/Expensify/App/pull/9093.

**Comment by Santhosh-Sellavel** [comment] 2022-05-19 21:03
Sorry @Subash-G this was already worked internally feel free submit proposals on any other [open jobs](https://github.com/Expensify/App/labels/Help%20Wanted)

**Comment by jliexpensify** [comment] 2022-05-20 00:49
Closing this off and removing job from Upworks. Sorry @Subash-G and thanks @Santhosh-Sellavel !

**Comment by adeel0202** [comment] 2022-05-22 16:36
Am I not eligible for the reporting bonus? Just wanted to confirm.
cc: @jliexpensify

**Comment by jliexpensify** [comment] 2022-05-22 23:10
Ah, sorry @adeel0202 - I missed that one. Thanks for letting me know!

**Comment by jliexpensify** [comment] 2022-05-22 23:13
@adeel0202 - I couldn't undo/re-open the closed job, so I invited you to a new job I created: 

https://www.upwork.com/ab/applicants/1528513936497311744/job-details
https://www.upwork.com/jobs/~014d5ef312ecc2678c

Tag me here once you've accepted and I'll pay $250. Thanks!

**Comment by adeel0202** [comment] 2022-05-23 06:05
Thanks @jliexpensify, I have applied.

**Comment by jliexpensify** [comment] 2022-05-23 23:38
@adeel0202 - once you accept the offer I can pay the bonus. Can you tag me when you've done so? Cheers!

**Comment by adeel0202** [comment] 2022-05-24 05:22
@jliexpensify, I have accepted the offer.

**Comment by jliexpensify** [comment] 2022-05-24 05:40
Paid @adeel0202 - thanks!

**Comment by Santhosh-Sellavel** [comment] 2022-05-31 16:40
I am not able to reproduce it even now.

https://user-images.githubusercontent.com/85645967/171227791-7d597602-407c-4637-b7a5-69e3d278d617.mov

**Comment by adeel0202** [comment] 2022-05-31 16:45
@Santhosh-Sellavel, try it on safari.

**Comment by Santhosh-Sellavel** [comment] 2022-05-31 16:53
Thanks @adeel0202 !

**Comment by Santhosh-Sellavel** [comment] 2022-05-31 16:57
Also, it's better to report these cases peculiar to the specific browser by mentioning them in the issue title. Somehow I missed that here. I am just focused on Web/Desktop here.

**Comment by mallenexpensify** [comment] 2022-05-31 17:29
> You should have checked on all browsers

Technically.. yes but since `Safari` wasn't reported in the issue (although the screen capture shows Safari), it's understandable that checking all browsers got missed.  Reopening.

**Comment by Santhosh-Sellavel** [comment] 2022-06-01 16:26
@pecanoro or  @jliexpensify
 We're still looking for a proposal here. As I'm going on OOO unassigning this one. Can anyone re-apply `Exported` label again here, thanks?

**Comment by allroundexperts** [comment] 2022-06-02 08:23
# Proposal

## Problem
When the button is disabled, even if you hover over it, the renderProp `hover` property of the `Pressable` react native component is `false`. However, if the button is not disabled, the `hover` property starts to work fine. In our case, the button is active initially, thus the hover style get applied correctly. When we remove the user by keyboard, the button state changes to disabled but the hover style still applies. This might be due to a bug in the `Pressable` component.

## Solution

This following:
https://github.com/Expensify/App/blob/3e0ba3a74cfa67c747a26e0f2547030ebd2714ad/src/components/Button.js#L251-L282
should be changed to:
```
                {({pressed, hovered}) => {
                    const activeAndHovered = !this.props.isDisabled && hovered;
                    return (
                        <OpacityView
                            shouldDim={pressed}
                            style={[
                                styles.button,
                                this.props.small ? styles.buttonSmall : undefined,
                                this.props.medium ? styles.buttonMedium : undefined,
                                this.props.large ? styles.buttonLarge : undefined,
                                this.props.extraLarge ? styles.buttonExtraLarge : undefined,
                                this.props.success ? styles.buttonSuccess : undefined,
                                this.props.danger ? styles.buttonDanger : undefined,
                                (this.props.isDisabled && this.props.success) ? styles.buttonSuccessDisabled : undefined,
                                (this.props.isDisabled && this.props.danger) ? styles.buttonDangerDisabled : undefined,
                                (this.props.isDisabled && !this.props.danger && !this.props.success) ? styles.buttonDisable : undefined,
                                (this.props.success && activeAndHovered) ? styles.buttonSuccessHovered : undefined,
                                (this.props.danger && activeAndHovered) ? styles.buttonDangerHovered : undefined,
                                this.props.shouldRemoveRightBorderRadius ? styles.noRightBorderRadius : undefined,
                                this.props.shouldRemoveLeftBorderRadius ? styles.noLeftBorderRadius : undefined,
                                ...this.props.innerStyles,
                            ]}
                        >
                            {this.renderContent()}
                            {this.props.isLoading && (
                                <ActivityIndicator
                                    color={(this.props.success || this.props.danger) ? themeColors.textReversed : themeColors.text}
                                    style={[styles.pAbsolute, styles.l0, styles.r0]}
                                />
                            )}
                        </OpacityView>
                    );
                }}
```

## Result

https://user-images.githubusercontent.com/30054992/171585934-117c8445-6ead-4b10-96c5-d04518dded4f.mov

**Comment by allroundexperts** [comment] 2022-06-02 12:40
@parasharrajat Updated.

**Comment by parasharrajat** [comment] 2022-06-02 14:25
Looking at the code on react-native-web. I can that changing the disabled prop does not change the hovered state. I don't if this is a bug or expected behaviour. Hovering is a gesture of mouse. But a disabled item will never be hovered. Based on this https://github.com/necolas/react-native-web/issues/1803. Maintainer suggested the same solution. 

@allroundexperts 's proposal looks good to me.

cc: @pecanoro 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by jliexpensify** [comment] 2022-06-03 01:15
Assigning Kadie as I am heading OOO

**Comment by pecanoro** [comment] 2022-06-06 19:24
Thanks @parasharrajat, proposal sounds good to me too! @allroundexperts, feel free to apply for the job in Upwork! I will assign the issue to you

**Comment by allroundexperts** [comment] 2022-06-06 19:29
> Thanks @parasharrajat, proposal sounds good to me too! @allroundexperts, feel free to apply for the job in Upwork! I will assign the issue to you

@pecanoro The job is no longer available. Can you check?

**Comment by pecanoro** [comment] 2022-06-06 19:38
@kadiealexander Can you check if the job is still there?

**Comment by kadiealexander** [comment] 2022-06-06 22:40
@allroundexperts please try here:

upwork.com/ab/applicants/1533941873075810304/job-details
https://www.upwork.com/jobs/~01ca764cc89eb24cad

**Comment by allroundexperts** [comment] 2022-06-06 22:53
Applied.

**Comment by kadiealexander** [comment] 2022-06-06 22:55
Thanks for the quick turnaround, just sent you an offer.

**Comment by jliexpensify** [comment] 2022-07-06 03:27
@allroundexperts  - going to pay you now.

@parasharrajat and @adeel0202 - have sent you invites! Once you accept, I'll pay and close the job.

**Comment by jliexpensify** [comment] 2022-07-06 05:02
Paid @adeel0202

**Comment by jliexpensify** [comment] 2022-07-06 05:45
Paid @parasharrajat , closing!

**Closed by jliexpensify** 2022-07-06 05:45 UTC
Labels: Reviewing, Exported, External, Engineering, Daily, Improvement, Awaiting Payment
