### ISSUE TITLE
[HOLD for payment 2024-04-25] [Distance rates] mweb - IOU - Changing unit or default category shows "updated the Distance pendingFields" message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39183] opened 2024-03-28 14:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-condition: Login as admin of collect workspace, categories , distance rate feature enabled
1. Go to https://staging.new.expensify.com/home
2. Tap profile --- Workspaces --- collect Workspace
3. Tap distance rate --- settings
4. Change the unit
5. Navigate to admin report of collect Workspace
6. Note the message "updated the Distance pendingFields from "" to "Array"
7. Tap profile --- Workspaces --- collect Workspace
8. Tap distance rate --- settings
9. Change the default category
10. Navigate to admin report of collect Workspace
11.Note the message "updated the Distance pendingFields from "" to "Array"

## Expected Result:
In admin collect WS a/c, in distance rate settings page, changing unit or default category must not show the message "updated the Distance pendingFields from "" to "Array"

## Actual Result:
In admin collect WS a/c, in distance rate settings page, changing unit or default category shows message "updated the Distance pendingFields from "" to "Array"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1c34a296-028b-49f4-8366-39a4aa079d6c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by mallenexpensify** [comment] 2024-03-28 18:46
Added to #wave-collect cuz it's distanced related, status should be Release 1. 
Tried to repro on two different devices in Browserstack but unable to.  Since it's an edgecase, I'll try again tomorrow then post in #bug-zero if I need someone with a real device to test.

**Comment by mallenexpensify** [comment] 2024-04-03 01:17
Haven't been able to get to yet

**Comment by trjExpensify** [comment] 2024-04-04 18:13
Interesting! Can't say I've seen this bug. CC: @luacmartins

**Comment by luacmartins** [comment] 2024-04-04 19:22
PR [here](https://github.com/Expensify/App/pull/39643)

**Comment by abdulrahuman5196** [comment] 2024-04-09 20:23
Hi, @luacmartins Could you kindly assign me this issue for PR review.

**Comment by trjExpensify** [comment] 2024-04-09 20:24
Done!

**Comment by mallenexpensify** [comment] 2024-04-26 01:23
@abdulrahuman5196 , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~019de39c59da774b14

(automation was hella weird on this issue)

**Comment by abdulrahuman5196** [comment] 2024-04-26 03:58
Hi @mallenexpensify  accepted the offer.

**Comment by mallenexpensify** [comment] 2024-04-26 19:58
Contributor+: @abdulrahuman5196 paid $500 via Upwork. 

@abdulrahuman5196 can you fill out the BZ checklist above plz?  Thx

**Comment by abdulrahuman5196** [comment] 2024-05-01 13:41
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be a regression. Internal fix.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1. Navigate to /settings/workspaces/<policyID>/distance-rates
2. Tap Settings
3. Change the unit
4. Change the default category
5. Navigate to #admin report of collect Workspace
6. Note the policy change log message says updated the Distance unit from "..." to "..."
7. Note the policy change log message says updated the Distance default category from "..." to "..."


@mallenexpensify

**Comment by luacmartins** [comment] 2024-05-01 14:41
Seems like we're good to close this one! Please reopen if I missed something.

**Closed by luacmartins** 2024-05-01 14:41 UTC
Labels: Daily, Awaiting Payment, Bug

**Comment by mallenexpensify** [comment] 2024-05-03 01:28
Testrail GH 
- https://github.com/Expensify/Expensify/issues/392936
