### ISSUE TITLE
[$500] Web - There is no validation error and it goes to the login page without showing account closed successfully message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27553] opened 2023-09-15 18:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Go to Settings > Workspace
3. Create a workspace if there is no workspace or Open any workspace from the list if there is a workspace
4. Click member
5. Invite a user into a workspace
6. Go back to Setting
7. Click Security
8. Click Close account
9. Add default account email and confirm to close an account
10. Observe the result

## Expected Result:
There should be a validation error which is called "You still own policies that are shared with other users. Please delete the policy or have another user take ownership before you try again"

## Actual Result:
There is no validation error which is called "You still own policies that are shared with other users. Please delete the policy or have another user take ownership before you try again" when closing an account which shared polices with someone

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d15d231a-4f0d-4a6c-b602-fc26b7862cc7

https://github.com/Expensify/App/assets/93399543/826158ef-4873-49b6-8538-84bdff235ac8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694730557456749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0151d7d35b4a0c323d</li>
        <li>Upwork Job ID: 1702753838184976384</li>
        <li>Last Price Increase: 2023-09-29</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 27012652</li>
<li>misgana96 | Reporter | 27012653</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-09-18 10:01
Assigned to GK first, dropping off. (Can't wait till' we fix that issue).

**Comment by garrettmknight** [comment] 2023-09-19 02:34
Repro'd opening up.

**Comment by garrettmknight** [comment] 2023-09-21 10:47
@sobitneupane can you review the proposal we have when you get a chance?

**Comment by sobitneupane** [comment] 2023-09-25 08:08
@rayane-djouah Thanks for [your proposal](https://github.com/Expensify/App/issues/27553#issuecomment-1722450663).

We should add the function `hasSharedPolicies` in Policyutils. @rayane-djouah How will you determine if the policy is shared and the current user is only admin of the policy?

**Comment by garrettmknight** [comment] 2023-09-28 10:14
@sobitneupane can you review the update when you get a chance?

**Comment by sobitneupane** [comment] 2023-10-04 05:20
@rayane-djouah's [proposal](https://github.com/Expensify/App/issues/27553#issuecomment-1722450663) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by misgana96** [comment] 2023-10-04 06:56
Offer accepted

**Comment by sobitneupane** [comment] 2023-10-09 14:13
@Gonals We used to notify users to close shared policies upon account closure, but we no longer do so. It appears that we have even removed the error messages that made me wonder if this change was intentional.

**Comment by Gonals** [comment] 2023-10-10 11:37
> @Gonals how do we want to display the error if a user try to close his account but he has shared policies? Should we display BlockingView component when he click on the close account option from the settings menu like so
> 
> ![image](https://user-images.githubusercontent.com/77965000/273350467-992a35b9-11cf-4d07-8bab-ba2465d08fc9.png) what do you think about this solution? If we should do so, could you please provide the copy of the error message and which icon to use? Thank you.

@garrettmknight, that ⬆️ might be a question for the design team. What do you think?

**Comment by Gonals** [comment] 2023-10-10 11:38
> @Gonals We used to notify users to close shared policies upon account closure, but we no longer do so. It appears that we have even removed the error messages that made me wonder if this change was intentional.

Can you link to the change/conversation?

**Comment by sobitneupane** [comment] 2023-10-11 03:57
@Gonals I recall that we once had the feature, but I'm unsure about when it was removed. If I remember correctly, we used to display a modal similar to the attached image."

<img width="1028" alt="Screenshot 2023-10-10 at 14 48 07" src="https://github.com/Expensify/App/assets/25876548/f39a6cc7-1262-4463-beaf-60e65037e692">

**Comment by garrettmknight** [comment] 2023-10-18 12:53
That error looks good and I agree that this would be better shown optimistically, but we'll want to sub `workspace` for `policy`. As for a translation, I've asked for a double check on how we're translating workspace [in #espaniol-translations](https://expensify.slack.com/archives/C21FRDWCV/p1697633429012389), but @Gonals can probably help:
`Sigues siendo propietario de espacios de trabajo compartidos con otros usuarios. Elimina el espacio de trabajo o pídele a otro usuario que sea el propietario antes de volver a intentarlo.`

**Comment by Gonals** [comment] 2023-10-18 14:54
`Sigues siendo propietario de espacios de trabajo compartidos con otros usuarios. Elimina el espacio de trabajo o asigna otro propietario antes de volver a intentarlo.` Sounds a bit better to me, but either should be fine

**Comment by sobitneupane** [comment] 2023-10-31 11:20
Sorry for the delay in PR. I was OOO. We will be actively working on the PR and will get it merged asap.

**Comment by sobitneupane** [comment] 2023-11-03 09:51
I would prefer the 2nd option. We would want it to be consistent with other form errors. The error is already present there. We just need to add optimistic value in error field.

**Comment by garrettmknight** [comment] 2023-11-03 12:13
I'd agree that the second option is more consistent with other errors - let's go with that.

**Comment by sobitneupane** [comment] 2023-11-28 08:19
@rayane-djouah What's your proposal to handle the situation?

**Comment by sobitneupane** [comment] 2023-11-28 10:00
@rayane-djouah We show error above the button in `NewTaskPage` as well.  We use `FormAlertWithSubmitButton` in `NewTaskPage`. The situation is similar here as well. Can we do the same? https://github.com/Expensify/App/blob/70813dbf3e2f73a73e52f880312bc198b39f4dec/src/pages/tasks/NewTaskPage.js#L123

**Comment by sobitneupane** [comment] 2023-12-18 18:27
Sorry for the delay @rayane-djouah.

>we need to keep using the FormProvider component for the formID handling and for validation. if we want to display the error above the button, we need to change the FormProvider and FormWrapper components to handle an additional form error message.

In that case, let's set error message in CloseAccountPage and pass it to FormProvider and ultimately to FormWrapper. 

cc: @Gonals

**Comment by Gonals** [comment] 2024-02-05 11:12
> @Gonals I recall that we once had the feature, but I'm unsure about when it was removed. We have another similar issue reported in [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1696521815818459).
> 
> We do show error message in the Close Account Page. But we need to re-login to see the error. Based on these informations, I am pretty sure we show the server returned error. Here we need to either wait for response from server or optimistically show error message if we have shared policy.
> 
> I believe better choice is to optimistically show error message if we have shared policy. We should make sure to use same logic as the backend for this.
> 
>  Screen.Recording.2023-10-11.at.09.54.50.mov 
> Error Message: "You still own policies that are shared with other users. Please delete the policy or have another user take ownership before you try again." We will need Spanish translation of the error message. <img alt="Screenshot 2023-10-11 at 10 02 41" width="371" src="https://private-user-images.githubusercontent.com/25876548/274140958-cc9dbcf5-342e-4906-a953-6b1274298a83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzE0MjAsIm5iZiI6MTcwNzEzMTEyMCwicGF0aCI6Ii8yNTg3NjU0OC8yNzQxNDA5NTgtY2M5ZGJjZjUtMzQyZS00OTA2LWE5NTMtNmIxMjc0Mjk4YTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDExMDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NjQxOGNkYTcyZjI3NzI2NjM4MmJmNmYzOGQ5MGU1NDJhN2Y2YTdmYTBiMjAxMjViNzIzYjQxZGJiM2FkZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J4UAhAkjp9vt8baAJqa0Nw0ZBkDIeNT7i_yrUNwnQLo">

After the discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1705688697784969), it seems we don't have a great way of optimistically showing the error. We won't have the needed data in Onyx, and pinging the server to get it defeats the purpose of doing this optimistically.

We can't really close the account while offline, so I propose enforcing Pattern C (Not allowing this flow while offline), and making sure we wait and correctly display the error when/if it comes back from the server.

Thoughts? @sobitneupane, @rayane-djouah, @mountiny

**Comment by mountiny** [comment] 2024-02-05 11:29
Pattern C for closing account makes sense to me

**Comment by sobitneupane** [comment] 2024-02-05 11:32
@Gonals 

> We can't really close the account while offline, so I propose enforcing Pattern C (Not allowing this flow while offline), and making sure we wait and correctly display the error when/if it comes back from the server.

We can do that. So, how should we inform the user the request is being processing?

https://github.com/Expensify/App/assets/25876548/56b9666f-3cc2-4396-907b-ad4283a7f3e6

**Comment by sobitneupane** [comment] 2024-02-05 11:33
WOW!! Looks like the issue is not reproducible any longer.

https://github.com/Expensify/App/assets/25876548/540f2a8c-f118-41da-a6c1-31cac7fd6d4c

**Comment by Gonals** [comment] 2024-02-08 12:09
Huh. Seems like we are now waiting for it and displaying the message correctly. I guess that's it 🤷. Closing

**Closed by Gonals** 2024-02-08 12:09 UTC
Labels: Reviewing, External, Engineering, Monthly, Bug
