### ISSUE TITLE
[HOLD FOR PAYMENT] [$250] Categorizing - RHP closes instead of returning to category list after deleting a category

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43616] opened 2024-06-12 21:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has disabled all the categories
1. Go to staging.new.expensify.com
2. Go to FAB > Track expense > Manual
3. Track a manual expense
4. Click Categorize it from the actionable whisper
5. Select the workspace that has disabled all the categories
6. Click Edit categories
7. Click on any category
8. Click Delete
9. Delete the category

## Expected Result:
RHP will return to category list after deleting a category

## Actual Result:
RHP closes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/18ddcf37-4382-4cd9-8c30-851935529803

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138b0b86909b7d865</li>
        <li>Upwork Job ID: 1802749240400742682</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 102863915</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Krishna2323</details>

**Comment by garrettmknight** [comment] 2024-06-20 18:23
Reassigning C+ since Sibtain is out - @eVoloshchak can you take a look at this one?

**Comment by garrettmknight** [comment] 2024-06-24 19:26
@eVoloshchak bump when you get a chance. Thanks!

**Comment by allroundexperts** [comment] 2024-06-25 00:24
I can jump in again since @eVoloshchak hasn't started on it.

**Comment by allroundexperts** [comment] 2024-06-25 00:28
Thanks for the proposals everyone. @Krishna2323 pointed out the correct RCA in his [proposal](https://github.com/Expensify/App/issues/43616#issuecomment-2164032929) and mentioned the correct fix as well. 

@cretadn22 proposal seems more or less similar to what @Krishna2323 proposed earlier, only with minor changes such as encapsulation of common logic.

I think we can easily encapsulate this logic inside a common function in the PR phase. As such, we can proceed with @Krishna2323's [proposal](https://github.com/Expensify/App/issues/43616#issuecomment-2164032929).

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment] 2024-07-03 19:57
@garrettmknight Can you please assign this issue (and the PR) to me? It slipped from my K2 because of this.

**Comment by francoisl** [comment] 2024-07-03 20:05
Assigned you @allroundexperts. Will you review the PR too?

**Comment by allroundexperts** [comment] 2024-07-03 20:58
Yes, please assign the PR to me as well.

**Comment by allroundexperts** [comment] 2024-07-29 08:14
## Checklist
1. https://github.com/Expensify/App/pull/38379
2. https://github.com/Expensify/App/pull/38379/files#r1694783270
3. N/A
4. A regression test would be good.

### Regression Test

Pre-req: Workspace has disabled all the categories

1. Open the app and Go to FAB -> Track expense -> Manual
2. Track a manual expense
3. Click Categorize it from the actionable whisper
4. Select the workspace that has disabled all the categories
5. Click Edit categories and click on any category
6. Click Delete and delete the category

Verify that the RHP will return to category list after deleting a category

Do we 👍 or 👎 ?

**Comment by garrettmknight** [comment] 2024-08-09 18:04
@Krishna2323 sorry about this one, on it now!

**Comment by garrettmknight** [comment] 2024-08-09 18:08
**Payment Summary:**
- Contributor: @Krishna2323 $250 paid via upwork
- Reviewer: @allroundexperts $250

**Comment by allroundexperts** [comment] 2024-08-11 22:57
@garrettmknight I have noted this down for payment. Feel free to close the issue.

**Closed** 2024-08-13 16:45 UTC
Labels: Reviewing, External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-10-04 11:08
$250 approved for @allroundexperts
