### ISSUE TITLE
[HOLD for Payment] Room - Description field is empty when there is only one line description

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48050] opened 2024-08-27 06:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a room.
3. Click on the room header.
4. Click Description.
5. Add a single line description and save it.

## Expected Result:
Description field will show the room description.

## Actual Result:
Description field is empty when there is only one line description.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6852465f-948e-41cc-bdc8-d1188a22c97f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment] 2024-08-27 06:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Description field is empty when there is only one line description.

### What is the root cause of that problem?
We pass `shouldTruncateTitle` as `true` for the description item. Then it will call `truncateHTML` [here](https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/components/MenuItem.tsx#L492)


https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/pages/ReportDetailsPage.tsx#L726

In this function, we have a `while` loop that will execute if `matches` is not `undefined` and then we will get the  `truncatedContent` in this loop. The problem here is if the room description doesn't have any HTML tag, `matches` is `undefined` then the loop doesn't execute that makes this function return an empty string.

https://github.com/nkdengineer/expensify-common/blob/d11466167bc562447d2dfdad624145040153efae/lib/ExpensiMark.ts#L1361
### What changes do you think we should make in order to solve the problem?
We have a check when the `matches` is `undefined` in this loop, we can also check this after the `while` loop to cover the case we don't move to this loop.

```
if (!matches && totalLength < maxLength) {
    matches = URL_REGEX.exec(htmlString);
    if (!matches || matches.index >= maxLength) {
        truncatedContent += htmlString.substring(0, this.getEndPosition(htmlString, undefined, maxLength, totalLength, opts));
    } else {
        while (matches) {
            endResult = matches[0];
            if (endResult !== null) {
                index = matches.index;
                truncatedContent += htmlString.substring(0, index + endResult.length - totalLength);
                htmlString = htmlString.substring(index + endResult.length);
                matches = URL_REGEX.exec(htmlString);
            }
        }
    }
}
```

https://github.com/nkdengineer/expensify-common/blob/d11466167bc562447d2dfdad624145040153efae/lib/ExpensiMark.ts#L1413-L1433

We can also add some unit tests for this function in this case.

### What alternative solutions did you explore? (Optional)

**Comment by cristipaval** [comment] 2024-08-27 14:16
@nkdengineer could you also find the offending PR?

**Comment by nkdengineer** [comment] 2024-08-27 14:46
```
if (shouldTruncateTitle && title !== Parser.htmlToText(title)) {
    titleToWrap = Parser.truncateHTML(titleToWrap, characterLimit, {ellipsis: '...'});
}
```

@shubham1206agra What do you think if we prevent calling `truncateHTML` if the `title` doesn't contain html tag.

**Comment by puneetlath** [comment] 2024-08-27 15:08
@nkdengineer how about we wrap it in `<comment>` tags when passing to `truncateHTML`? Would you be able to raise a PR?

**Comment by nkdengineer** [comment] 2024-08-27 15:15
@puneetlath Yes I can raise a PR now.

**Comment by nkdengineer** [comment] 2024-08-27 15:15
Yeah I think that also is an option.

**Comment by nkdengineer** [comment] 2024-08-27 15:27
@shubham1206agra Updated [proposal](https://github.com/Expensify/App/issues/48050#issuecomment-2311711164).

**Comment by puneetlath** [comment] 2024-08-27 15:29
Ok please raise a PR now.

**Comment by nkdengineer** [comment] 2024-08-27 16:01
@puneetlath The PR is ready.

**Comment by puneetlath** [comment] 2024-08-27 16:57
I confirmed this is fixed on staging. Demoting.

**Comment by abekkala** [comment] 2024-09-20 16:06
@puneetlath are you able to confirm if this is an issue of the automation failing or has this one really not been deployed to prod yet?

**Comment by puneetlath** [comment] 2024-09-20 16:34
This one should be on production as of a couple weeks ago. Right @nkdengineer?

**Comment by nkdengineer** [comment] 2024-09-20 16:52
@puneetlath Yes.

**Comment by abekkala** [comment] 2024-09-20 19:50
### PAYMENT SUMMARY: 

- Fix: @nkdengineer [Offer](https://www.upwork.com/nx/wm/offer/104060816)
- PR Review: @shubham1206agra [Offer](https://www.upwork.com/nx/wm/offer/104060850)

**Comment by abekkala** [comment] 2024-09-23 13:19
@shubham1206agra payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment] 2024-09-23 13:22
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: 
- [ ] [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 
- [ ] [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.
- [ ] [@shubham1206agra] Determine if we should create a regression test for this bug.
- [ ] [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@abekkala] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by abekkala** [comment] 2024-09-23 20:32
@nkdengineer payment sent and contract ended - thank you! 🎉

**Closed by abekkala** 2024-09-23 20:32 UTC
Labels: Reviewing, Engineering, Monthly, Bug
