### ISSUE TITLE
[$500] IOU - No payment button IOU for small amount in another currency

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35243] opened 2024-01-26 13:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team 
**Slack conversation:**

## Action Performed:
Preconditions:
Create a WS on behalf of admin, set the base currency for the WS to $, invite a participant to the WS.
Steps:
1. Open https://staging.new.expensify.com/
2. Log in as an administrator
3. In incognito mode, log in as a WS member
4. Navigate to the WS conversation on the member behalf.
5. Send a money request in the amount of "KZT 1" on behalf of the member to the WS conversation
6. Under the administrator, open the WS conversation with the member
7. Note the IOU received

## Expected Result:
The user should be able to pay for the IOU in another currency if the amount is too small for the main currency of the policy

## Actual Result:
It is not possible to pay for an IOU in another currency if the amount is too small for the main policy currency

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1a6ab309-6c38-4933-b2e1-0ca14078b4e1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cfb215c443e46eb4</li>
        <li>Upwork Job ID: 1750878849752887296</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-26 13:51
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by ikevin127** [comment] 2024-01-27 17:57
# Proposal

### Please re-state the problem that we are trying to solve in this issue

It is not possible to pay for an IOU in another currency if the amount is too small for the main policy currency.

### What is the root cause of that problem?

This can be reproduced with currencies that have a considerably higher exchange rate then the workspace currency. 

Examples:
1. Iranian Rial (IRR): 1 USD = ~378,075 IRR (highest one)
2. Lebanese Pound (LBP): 1 USD = ~86,500 LBP
3. Somali Shilling (SOS): 1 USD = ~24,300 SOS
4. Laos Kip (LAK): 1 USD = ~17,230 LAK
5. Indonesia Rupiah (IDR): 1 USD = ~14,703 IDR
6. Kazakhstani Tenge (KZT): 1 USD = ~ 450 KZT (current example)

https://github.com/Expensify/App/blob/c5ca9a810b529cdc8b8fceb179e9cfc01061355a/src/libs/CurrencyUtils.ts#L89

As per the line above, we don't support currencies with more than two decimal places.
Therefore anything that converts to the workspace's currency with more than 1 zeros as decimals, examples:
- 1 IRR = 0.000024 USD
- 1 KZT = 0.0022 USD

will show as 0 and will not be payable.

### What changes do you think we should make in order to solve the problem?

A simple solution for these types of workspace IOU requests, in order to inform the user as to why the request is not payable. For this we can add some checks on the front-end side to do the following:
- if the request currency is different than the workspace's main currency and the workspace's currency amount returned from the BE is 0 (for cases like the ones mentioned in RCA)
- we display a red brick dot error and on the **request preview**
- when navigated to the **request view** screen, under the amount field we will display an error like:
`The {transactionCurrency} amount is too low for a valid {parentReport.currency} conversion.`

This will let the user know that they have to increase the amount in order to be able to make the request payable.
Obviously we will apply this logic to every place where this issue occurs within the app.

### What alternative solutions did you explore? (Optional)

Handle this edge case error from the back-end side, returning an error for the same checks as mentioned in the main solution.

### Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

| Before | After (POC) |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/80879e35-81c0-468f-ba8b-e498b54fac3e"> | <video src="https://github.com/Expensify/App/assets/56457735/645e2297-d1f6-4769-8bb1-1113fb9c1b28"> |

</details>

**Comment by itssourabhs** [comment] 2024-01-28 16:42
Hmmm here's my 2-Cents, 

I somewhat agree with @ikevin127 but when you are giving end-users the option to select a payment merchant then show what's the minimum amount with the currency that it supports which can be different from country to country(superset) and payment gateway provider to provider(subset this shouldn't be the case but it could be). You must have given the option to configure the provider to admin, if you have only integrated some US's providers then it's not the correct way if you want your solution to be global. based on the user's demographic their PPP(purchasing power parity) in their country might be low so why are you forcing everyone to pay in USD? give users some space where they can request for integration for a provider that is not listed, it's definitely going to cost the maintainers but do your research, is it really worth the time and money to integrate the requested provider of that country? if not then don't, If yes then why not, it would be helpful for users and yeah you have to maintain it(provider conf because it can change a lot wrt to country's or provider's policies)  



I could be wrong since all I wrote above is based on my assumptions if I had to build the system then how would I have done that?

And since I haven't used the system, I'm sorry for taking too much of your time.

**Comment by zanyrenney** [comment] 2024-02-05 18:16
Considering this does not fall within our wave/VIP roadmap, and is an edge case that doesn't seem to affect real users at this moment, i'm closing this out for focus: https://expensify.slack.com/archives/C01SKUP7QR0/p1707155321297619

**Closed by zanyrenney** 2024-02-05 18:16 UTC
Labels: External, Daily, Internal, Help Wanted, Overdue, Bug
