### ISSUE TITLE
[Wave 6: Drafts] Backwards compatibility - Empty $0 draft report created on OldDot doesn’t show on NewDot

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#33449] opened 2023-12-21 20:47 UTC
**Slack conversation:** https://expensify.slack.com/archives/C02MW39LT9N/p1703190611537479?thread_ts=1703187017.215259&cid=C02MW39LT9N

## Action Performed:

- As the member, go to OldDot and create a report without an expense
- Switch back to NewDot and navigate to the workspace chat
- Verify you can see the empty draft report preview component in the chat :x:

## Expected Result:

- Cross-platform reports actions - you should see a draft in NewExpensify if it's created in OldDot

## Actual Result:

- Cross-platform reports actions  - Report drafts aren't created in NewExpensify

## Screenshots/Videos

<img width="914" alt="image" src="https://github.com/Expensify/App/assets/51066321/598671ae-d311-4c56-b52b-64115d5bcda1">
<img width="910" alt="image" src="https://github.com/Expensify/App/assets/51066321/7c2b9f41-7fd9-437a-8d3b-240aa0a2c187">

https://github.com/Expensify/App/assets/51066321/2a520137-395e-482c-80fa-4127730f12aa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

cc @mountiny 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be34bb45b7460b8a</li>
        <li>Upwork Job ID: 1744597869054656512</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2023-12-22 02:58
Asking for clarification on how to handle this.

**Comment by peterdbarkerUK** [comment] 2023-12-22 09:46
I've started going through [testing for wave5](https://docs.google.com/document/d/14p1-_-Uk841xvxJ4bs2NlhVhyC2cD23NykRIpUDis5c/edit#heading=h.nhtsmauf72jq), and also ran into this. I'm honestly not sure if this bug should be under wave 5 or 6 as a result, cc @DylanDylann

**Comment by sophiepintoraetz** [comment] 2023-12-22 19:59
Moving to weekly while I'm OOO - not reassigning given the low workforce online during that period.

**Comment by mountiny** [comment] 2023-12-26 15:32
@peterdbarkerUK This should be wave6 as there are no open reports on free plan

**Comment by sophiepintoraetz** [comment] 2024-01-03 22:02
Ah - @greg-schroeder - I think as wave 6 curator you're determining the priority of these bugs?

**Comment by sophiepintoraetz** [comment] 2024-01-09 05:37
Bumped in slack.

**Comment by trjExpensify** [comment] 2024-01-12 13:30
@greg-schroeder was this closed for a reason? I.e it's being addressed elsewhere?

**Comment by trjExpensify** [comment] 2024-01-23 18:44
Bumparoo!

**Comment by greg-schroeder** [comment] 2024-01-23 20:07
Oh, what the hell, I don't remember closing this and it was a mistake

**Comment by rlinoz** [comment] 2024-01-24 19:39
I believe this is fixed, the video is for a free policy in prod, but I tested in dev with a collect policy and it works as well.

https://github.com/Expensify/App/assets/5201282/df704b99-060f-43de-afdb-c6f1199da2af

**Comment by iwiznia** [comment] 2024-01-24 21:18
I don't understand this issue... what does `you should see a draft in NewExpensify if it's created in OldDot` mean?

**Comment by greg-schroeder** [comment] 2024-01-24 21:49
@iwiznia I think that "draft" in this context is supposed to mean "open report" ... this stems from Tom's report here:

https://expensify.slack.com/archives/C02MW39LT9N/p1703190611537479?thread_ts=1703187017.215259&cid=C02MW39LT9N

With that said, I don't think this is actually the case now... Vit just showed this working yesterday:

https://expensify.slack.com/archives/C02MW39LT9N/p1705964873937549?thread_ts=1705957191.862429&cid=C02MW39LT9N

So I think we can close this actually... what do you think?

**Comment by iwiznia** [comment] 2024-01-24 21:56
I am not going to give an opinion on if we can close an issue or not if I don't understand the issue to begin with 😄 
 could read the 64 replies in the thread, but given you think we should close, I won't...

If the problem is gone, then for sure let's close it

**Comment by trjExpensify** [comment] 2024-01-24 22:00
I think @mountiny had an expense on that open report being shown, and @rlinoz, can you show us it on collect with an `open` report for ref? 

@iwiznia.. "Draft" = NewDot terminology for an `open` report. 

1. Go to OldDot, create an open report and don't add anything to it yet. 
2. Switch over to NewDot, the report isn't created or visible in the workspace chat. 

So until the first expense gets added to the `open` report, it doesn't seem to show up in NewDot. I don't think anyone knows why, when they should be in sync.

**Comment by iwiznia** [comment] 2024-01-24 22:03
Why would we want to show an empty report in newDot? How would it even show? I am so confused...

**Comment by iwiznia** [comment] 2024-01-24 22:04
For context, I _think_ know why it does not show. It's because we create the IOU action when creating expenses, not when creating reports

**Comment by mountiny** [comment] 2024-01-24 22:34
> So until the first expense gets added to the open report, it doesn't seem to show up in NewDot. I don't think anyone knows why, when they should be in sync.

I have tested this locally yesterday and all works expected, you can see the empty report just fine.

**Comment by mountiny** [comment] 2024-01-24 22:38
https://github.com/Expensify/App/assets/36083550/61a551da-7087-4031-8517-5ca9b951f6c1

**Comment by trjExpensify** [comment] 2024-01-25 00:45
Ah cool, so then we can close this out! Thanks!

**Closed by trjExpensify** 2024-01-25 00:45 UTC
Labels: Engineering, Daily, Internal, Bug, Hot Pick

**Comment by greg-schroeder** [comment] 2024-01-25 19:43
Thanks all 👍
