### ISSUE TITLE
[$250] [LOW] [Splits] IOU - Header of IOU transaction thread is not grayed out when created offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39352] opened 2024-04-01 12:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4466053
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Request money from a user with no previous chat.
4. Go to 1:1 DM, IOU report and transaction thread.
5. Note the header of the three reports.

## Expected Result:
The header of 1:1 DM, IOU report and transaction thread should be all grayed out.

## Actual Result:
The header of 1:1 DM and IOU report is grayed out, but not for transaction thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Bug6434082_1711970322335!bandicam_2024-04-01_19-15-38-587](https://github.com/Expensify/App/assets/115492554/eb6c4095-7efb-4ea5-bd15-f3cda4eeb7fd)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d9117dc1c8dc5c7</li>
        <li>Upwork Job ID: 1777456926421372928</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-04-01 12:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The transaction thread header is not grayed out when created while offline which is inconsistent with the chat and IOU/expense report header.

### What is the root cause of that problem?
When we create a new request while offline, we will optimistically create the chat and IOU report (if new) and add a pending fields.
https://github.com/Expensify/App/blob/c848cb6bf29b600eecb8b338222fffe8a36d0329/src/libs/actions/IOU.ts#L516
https://github.com/Expensify/App/blob/c848cb6bf29b600eecb8b338222fffe8a36d0329/src/libs/actions/IOU.ts#L529-L531

The pending fields will be used to grayed out the whole report screen, including the header.

However, we never add a pending fields for the optimistic transaction thread.
https://github.com/Expensify/App/blob/c848cb6bf29b600eecb8b338222fffe8a36d0329/src/libs/actions/IOU.ts#L573-L575

Thus, both the header and the composer are not grayed out.

### What changes do you think we should make in order to solve the problem?

Add a pending fields the same as chat/IOU report.
```
value: {
    ...transactionThreadReport,
    pendingFields: {createChat: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD},
},
```

Then, clear it when fails just like we did for chat/IOU report too. (we already clear it when success)

**Comment by MitchExpensify** [comment] 2024-04-01 18:31
Seeing as this is IOU related I'm assigning to vip-split

**Comment by MitchExpensify** [comment] 2024-04-08 22:02
Let's fix!

**Comment by MitchExpensify** [comment] 2024-04-09 21:26
Waiting on proposals

**Comment by srikarparsi** [comment] 2024-04-15 18:04
Assigning @bernhardoj

**Comment by bernhardoj** [comment] 2024-04-16 05:37
PR is ready

cc: @hoangzinh

**Comment by MitchExpensify** [comment] 2024-05-12 16:57
*Payment summary:*

C $250 @bernhardoj (Upwork)
C+ $250 @hoangzinh (Upwork)

**Comment by MitchExpensify** [comment] 2024-05-12 17:00
Done! Thanks

**Closed by MitchExpensify** 2024-05-12 17:00 UTC
Labels: Reviewing, External, Monthly, Bug
