### ISSUE TITLE
[$500] [MEDIUM] Request Money > Scan – The red dot does not appear in all related chats while in an error state.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27184] opened 2023-09-11 18:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB (Plus sign).
2. Select the "Request Money" option from the menu.
3. Select the "Scan" option.
4. Click the “Choose File” button.
5. Select any file.
6. Select any User
7. Click the "Request" button.
8. In a chat thread, click "Reply in Thread."
9. Modify the date to any other value, and observe that the error message appears before the arrow next to "Amount" and "Merchant."
10. Notice that the red dot doesn't appear in the chat opened in step 8. It only appears in the chat from where the money was initially requested.

## Expected Result:
 In error state red dot should appear in all related chats.
 
## Actual Result:
In error state red dot doesn’t appear in all related chats.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.67.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fc62e702-1b38-4c51-a4ca-4f5271f53b15

https://github.com/Expensify/App/assets/93399543/e8a1d2bd-dd07-4caf-be1b-07ec98bea1c9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694144250026179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170884ea52fcd297d</li>
        <li>Upwork Job ID: 1701299482920194048</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by zukilover** [comment] 2023-09-12 10:48
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
In error state red dot doesn’t appear in all related chats.

### What is the root cause of that problem?
`OptionsListUtils` is checking missing smart scan fields only for preview-report action:
https://github.com/Expensify/App/blob/37feea67f55c429776d0e10be679f1a385eca7da/src/libs/OptionsListUtils.js#L356-L367

To show the red dots for all related chats, it should also check for create-report action.

### What changes do you think we should make in order to solve the problem?
Add another condition to check missing smart scan fields for create-report action, e.g.:
```
         } else if (
            ReportActionUtils.isCreatedAction(action)
        ) {
            if (ReportUtils.hasMissingSmartscanFields(report.chatReportID)) {
                _.extend(reportActionErrors, {smartscan: ErrorUtils.getMicroSecondOnyxError('report.genericSmartscanFailureMessage')});
            }
        }
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ayazalavi** [comment] 2023-09-12 15:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In some cases red dot doesnt appear for chat that has missing field

### What is the root cause of that problem?
Red dor appears once you have brickRoadIndicator. https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/components/LHNOptionsList/OptionRowLHN.js#L103

This indicator depends on number of errors:
https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/libs/SidebarUtils.js#L246-L247

**`getAllReportErrors`** loops through reportActions. This loop is not handling **`### MODIFIEDEXPENSE`** type of chats so they get skipped while calculating for chat errors.

### What changes do you think we should make in order to solve the problem?
Change below code in **`getAllReportErrors`**
https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/libs/OptionsListUtils.js#L358-L360
to 
```
else if (ReportActionUtils.isReportPreviewAction(action) || ReportActionUtils.isModifiedExpenseAction(action)) {
            const iouReportID = (() => {
                if(ReportActionUtils.isReportPreviewAction(action))
                    return ReportActionUtils.getIOUReportIDFromReportActionPreview(action);
                else if (ReportActionUtils.isModifiedExpenseAction(action)) {
                    return report.chatReportID
                }
            })()
```
In above code we need to use ReportActionUtils.isModifiedExpenseAction to check for these chats. secondly we cant use getIOUReportIDFromReportActionPreview so we can use chatReportID instead for isModifiedExpenseAction case.

### What alternative solutions did you explore? (Optional)
Write helper to fetch IOU report ID for modified expense chats.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mananjadhav** [comment] 2023-09-12 17:52
@kevinksullivan @Christinadobrzyn Can you please reassign this?

**Comment by Christinadobrzyn** [comment] 2023-09-12 18:42
I wonder if we can combine this issue with this issue https://github.com/Expensify/App/issues/27083?

**Comment by Christinadobrzyn** [comment] 2023-09-13 22:12
doesn't seem to be related to https://github.com/Expensify/App/issues/27083 and I'm wondering if this is expected... the RBR doesn't show on the request only the IOU... @kevinksullivan do you think this is expected?

**Comment by ayazalavi** [comment] 2023-09-14 18:04
> doesn't seem to be related to #27083 and I'm wondering if this is expected... the RBR doesn't show on the request only the IOU... @kevinksullivan do you think this is expected?

@Christinadobrzyn is IOU sending money to other user and is request is requesting money from other user? I am new to the platform so I need some knowledge.

**Comment by Christinadobrzyn** [comment] 2023-09-14 21:46
Great question @ayazalavi - If I have this right, here's what each LHN topic looks like when requesting money. 

<img width="888" alt="image" src="https://github.com/Expensify/App/assets/51066321/863f4bf2-c445-4b1b-a691-0eb95c5421fb">

So the IOU shows an RBR because there's something wrong with the request. The request and the chat don't show an RBR. So I'm not sure if this is expected but I feel like it is. Asking the team -

**Comment by ayazalavi** [comment] 2023-09-15 12:17
@Christinadobrzyn Thank you. It was very helpful.

**Comment by Christinadobrzyn** [comment] 2023-09-15 18:54
Sounds like this behaviour is going to change with https://github.com/Expensify/Expensify/milestone/610 which has no due date so I'm going to move this out to monthly and put it on HOLD for now.

**Comment by Christinadobrzyn** [comment] 2023-10-17 23:51
holding for - https://github.com/Expensify/Expensify/milestone/610

**Comment by Christinadobrzyn** [comment] 2023-11-27 23:27
still on hold for https://github.com/Expensify/Expensify/milestone/610

**Comment by Christinadobrzyn** [comment] 2024-01-03 01:14
added to Wave 6 for tracking - https://github.com/Expensify/Expensify/milestone/610

**Comment by burczu** [comment] 2024-01-08 07:55
Hey @Christinadobrzyn! I'm leaving C+ role today and joining Waves. Please assign another C+ instead of me. Thank you!

**Comment by situchan** [comment] 2024-01-08 08:32
I can take over as C+

**Comment by Christinadobrzyn** [comment] 2024-02-08 23:22
Added you @situchan - I think this is still on hold... or am I missing something?

**Comment by greg-schroeder** [comment] 2024-02-20 06:49
This doesn't need to be on hold anymore probably, but I'm going to re-initiate the conversation here: https://expensify.slack.com/archives/C01SKUP7QR0/p1694728347724019

**Comment by Christinadobrzyn** [comment] 2024-02-20 15:22
discussing if we can just close this

**Comment by Christinadobrzyn** [comment] 2024-02-21 20:41
It sounds like the [conclusion](https://expensify.slack.com/archives/C01SKUP7QR0/p1694997238975279?thread_ts=1694728347.724019&cid=C01SKUP7QR0) is that the RBR should show only on the IOU at this time and not the chat. 

So I think we should just close this for now as it's happening as expected.

**Closed by Christinadobrzyn** 2024-02-21 20:41 UTC
Labels: External, Daily, Bug
