### ISSUE TITLE
[HOLD for payment 2023-10-05] [$500] Web -  Composer send button is enabled even when the input contains only space

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26433] opened 2023-08-31 20:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Type multiple spaces and verify the send button is still disabled
3. Close the chat or navigate to another chat
4. Open back the chat

## Expected Result:
The send button stays disabled because it contains only space

## Actual Result:
The send button is enabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d2d7a800-a5e8-4bdf-9b9e-98b25c5d7367

https://github.com/Expensify/App/assets/93399543/126c6c8e-c746-496d-af70-9fd86c545b31

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693037242762969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148ad3caa7badc613</li>
        <li>Upwork Job ID: 1697749457182527488</li>
        <li>Last Price Increase: 2023-09-01</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26518770</li>
<li>bernhardoj | Contributor | 26518772</li>
<li>bernhardoj | Reporter | 26518773</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-08-31 20:45
Proposal by: @bernhardoj
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1693037242762969

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The composer send button is enabled even when it contains only space.
### What is the root cause of that problem?
We disable the send button if `isCommentEmpty` state is true. The initial value of `isCommentEmpty` comes from `isCommentEmptyProp`.
https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L131
[https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#[…]8](https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L445-L448)
Notice that we check using _.isEmpty which considers space only as not empty. This is different from what we do when typing something in the composer.
[https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src[…]ages/home/report/ReportActionCompose/ComposerWithSuggestions.js](https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L183)
### What changes do you think we should make in order to solve the problem?

This issue happens after the `ReportActionCompose` refactor. Previously, when the composer mounted, we always called `updateComment` to make sure `isCommentEmpty` had a correct value, but this approach raised this [issue](https://github.com/Expensify/App/issues/25551).
Even though the issue is marked as not a bug, I still think it's a bug and we shouldn't use the old approach which is a workaround. To fully solve the issue, we should replace _.isEmpty with the regex we use when typing in the composer.
```
isCommentEmpty: {
    selector: (comment) => !comment || !!comment.match(/^(\s)*$/)
// comment could be undefined, so we also use !comment
```

**Comment by alifhaider** [comment] 2023-08-31 22:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Composer send button is not disabled when typed text is only spaces

### What is the root cause of that problem?
Send Button is only checking for disabled if field is empty or not.
https://github.com/Expensify/App/blob/64ff471fc614a57645edf34b5d2ac346046f12c1/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L452-L455

### What changes do you think we should make in order to solve the problem?
We can trim the comment and then update `isCommentEmpty`. By this, it will remove the start and ending spaces of text, and then make the button enabled and disabled based on that. 
```
isCommentEmpty: {
            key: ({reportID}) => `${ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT}${reportID}`,
            selector: (comment) => _.isEmpty(comment) || _.isEmpty(comment.trim()),
        },
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by alifhaider** [comment] 2023-08-31 22:45
Contributor details
Your Expensify account email: alifhaider57@gmail.com
Upwork Profile Link: (https://www.upwork.com/freelancers/~014066482556c551be)

**Comment by alphaboss1104** [comment] 2023-09-01 07:47
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Composer send button is not disabled when typed text is only spaces

### What is the root cause of that problem?

We disable the send button if `isCommentEmpty` state is true.
We set the `isCommentEmpty` 's value by `comment` is empty or not when the chat is reopened or navigated back to.

https://github.com/Expensify/App/blob/ec95ab05e2c9d14ac91aa33946a5beeb39099e1f/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L452-L455

This is the root cause of this issue.

### What changes do you think we should make in order to solve the problem?

We should also check if the `comment` is a string full of spaces like this.

```js
        isCommentEmpty: {
            key: ({reportID}) => `${ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT}${reportID}`,
            selector: (comment) => _.isEmpty(comment) || !!comment.match(/^(\s)*$/),
        },
```

### What alternative solutions did you explore? (Optional)

We can also be resolved by adding a check in the `useEffect` hook that handles the reopening or navigation back to chat [here](https://github.com/Expensify/App/blob/ec95ab05e2c9d14ac91aa33946a5beeb39099e1f/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L436).

```js
    useEffect(() => {
        if (value.length === 0) {
            return;
        }

+       setIsCommentEmpty(value.trim().length === 0);

        Report.setReportWithDraft(reportID, true);
    }, []);
```

**Comment by rsiota** [comment] 2023-09-02 20:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we open a chat and type multiple spaces in the composer, the send button remains disabled. But if we switch chats and navigate back to the original chat, the send button becomes enabled, instead of remaining disabled.
### What is the root cause of that problem?
The root cause of the problem is that the check used to determine if a comment is empty, uses the _.isEmpty() underscore function, which, for strings and array-like objects, checks if the length property is 0. This function doesn't account for white spaces within a string.

The current check happens on ```ReportActionCompose.js```, in the following lines:

```javascript
452    isCommentEmpty: {
453        key: ({reportID}) => `${ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT}${reportID}`,
454        selector: (comment) => _.isEmpty(comment),
455    },
```

### What changes do you think we should make in order to solve the problem?
I would propose to add a further check to determine if the empty comment has white spaces. I think that it would be useful to have a utility function that could be composed when doing the check.

I was looking for a place on the basecode that might be appropriate for adding the utitlity function, and I thought of ReportUtil.js, but, without knowing the basecode in depth, I understand, there might be other files, where this utility function, might be more appropriately placed.
 
I would suggest the following changes:

```ReportUtil.js```

```Javascript
/**
* Checks if a comment has white space
*
* @param {String} comment
* @returns {Boolean}
*/
function hasWhiteSpace(comment) {
    return /\s/g.test(comment);
} 
```

```Javascript
export {
    ...
    hasWhiteSpace,
    ...
};
```


```ReportActionCompose.js```

```javascript
isCommentEmpty: {
    key: ({reportID}) => `${ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT}${reportID}`,
    selector: (comment) => _.isEmpty(comment) || ReportUtils.hasWhiteSpace(comment),
},
```
 
### What alternative solutions did you explore? (Optional)
An alternative solution would be to inline the check for white spacing directly, instead of using a separate function. I thought that using a separate function might help with readability.

**Comment by rsiota** [comment] 2023-09-02 20:21
Contributor details
Your Expensify account email: rsiota@gmail.com
Upwork Profile Link: https://www.upwork.com/en-gb/freelancers/~016641e7b5affe3105

**Comment by aldo-expensify** [comment] 2023-09-05 17:03
I'm not being able to assign @bernhardoj for the moment

<img width="383" alt="image" src="https://github.com/Expensify/App/assets/87341702/446ee259-2b02-4693-a868-198ced292bc2">

I was having some problems with Github crashing a few minutes ago, maybe is related to that, I'll try later.

**Comment by strepanier03** [comment] 2023-09-05 23:59
Hmm, I gave it a go and can't assign them either 🤔

**Comment by strepanier03** [comment] 2023-09-06 00:01
@bernhardoj - Can you comment on this GH, please? I ran into this issue on another GH in the past and commenting allowed assigning, not sure why.

**Comment by strepanier03** [comment] 2023-10-06 00:39
@bernhardoj - You've been paid in Upwork. I left a note on the bonus payment but I thought we had two separate contracts for this job for you so I added the bonus to pay the reporting payment after the fact. Let me know if you have any questions. 

@fedirjh - I'll keep my eyes open for an update on the checklist and move forward once there's one. 

Thanks everyone!

**Comment by strepanier03** [comment] 2023-10-06 23:11
Sure thing @fedirjh, I'll do that now.

**Comment by strepanier03** [comment] 2023-10-06 23:16
@fedirjh - Sent!

Working on reg test GH now.

**Comment by strepanier03** [comment] 2023-10-06 23:21
@bernhardoj - I'll work on closing that next week. For some reason both contracts linked here are for the same contract and paid already.

**Comment by strepanier03** [comment] 2023-10-09 15:36
@fedirjh - I have finished paying you as well. Thanks for accepting that.

Thank you both for being part of our community and working so hard to help us achieve the New Expensify dream.

**Closed by strepanier03** 2023-10-09 15:36 UTC
Labels: External, Daily, Awaiting Payment, Bug
