### ISSUE TITLE
[HOLD for payment 2022-12-27] [$1000] Chat - Edited message hides at the bottom after saving it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12198] opened 2022-10-27 16:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the test app and login with any account
2. Send any message in a chat that has at least a full page of messages.
3. Edit the message
4. Save the message
5. Observe the edited message

## Expected Result:
Edited message is displayed properly after saving changes.

## Actual Result:
Edited message hides at the bottom after saving it. Need to scroll to view it.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/198351707-92f8e255-8c34-42b7-978b-b06a4af40ef3.mp4

**Upwork job URL:** https://www.upwork.com/jobs/~01b9d92e7c3fc4c620
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment] 2022-10-27 19:13
Slight edit to the Actions Performed - I only was able to reproduce this if the chat was longer than a single screen in my app (that is, if it was only a couple messages, it worked fine).

However this definitely is happening. Going to push external, weekly.

**Comment by michaelhaxhiu** [comment] 2022-10-28 17:58
Posting to Upwork.

**Comment by michaelhaxhiu** [comment] 2022-10-28 18:05
Job link - https://www.upwork.com/jobs/~01b9d92e7c3fc4c620

**Comment by dangrous** [comment] 2022-10-31 17:16
Not overdue, waiting for proposals

**Comment by dangrous** [comment] 2022-11-03 00:57
Not sure what the new guidance is on Daily vs. Weekly for these - I think @michaelhaxhiu will know more than me - so for now just commenting to pre-empt the bot. Still waiting for proposals.

**Comment by michaelhaxhiu** [comment] 2022-11-07 18:53
Doubling job!

**Comment by Santhosh-Sellavel** [comment] 2022-11-07 21:21
I've requested it before process changes @michaelhaxhiu

**Comment by michaelhaxhiu** [comment] 2022-11-07 21:36
👍 sorry we didn't announce it more clearly sooner! All good now :)

**Comment by dangrous** [comment] 2022-11-10 14:52
Will review shortly - thanks @mollfpr! All yours @Santhosh-Sellavel if you can get to it first.

**Comment by Santhosh-Sellavel** [comment] 2022-11-14 16:36
I'm confused about the logic here and need more clarity on why & how this fixes the issue! @mollfpr 

cc: @dangrous

**Comment by dangrous** [comment] 2022-11-16 17:06
Agreed, this does seem to work but I have no idea why haha. We should definitely figure out what's going on to make sure we understand it!

**Comment by michaelhaxhiu** [comment] 2022-11-16 17:09
Can we post this in Slack and get visibility on it? Maybe in #contributor-plus or #expensify-bugs?

**Comment by Santhosh-Sellavel** [comment] 2022-11-16 18:07
Ya please go ahead if you haven't @michaelhaxhiu!

**Comment by michaelhaxhiu** [comment] 2022-11-16 18:18
Ah let me clarify.... @mollfpr are you able to explain a little more on **why** the proposed solution of changing the padding-top works? If not, you post this solution in #expensify-bugs and get more eyes? If we can justify it, you'll be eligible to get the job and the bounty :)

**Comment by puneetlath** [comment] 2022-11-17 21:21
@dangrous To help us clear out the large backlog of /App bugs, we're putting the spotlight every bug in the repo already than 4 weeks old. To help unblock the roadmap and get our bug pipeline back in equilibrium, can you:  
 
- Decide whether any proposals currently meet our guidelines and can be approved as-is 
- For any that can't, please take this issue internal and treat it as one of your highest priorities 
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by dangrous** [comment] 2022-11-17 22:00
Re: ^ @mollfpr's proposal is currently being reviewed! Should hopefully be able to accept and get this moving shortly!

**Comment by mollfpr** [comment] 2022-11-18 17:57
Sorry guys, need more times to debug this again.

**Comment by michaelhaxhiu** [comment] 2022-11-18 18:47
Re-assigning myself as I'm going OOO.

**Comment by s77rt** [comment] 2022-11-19 14:00
Not reproducible from my end.

**Comment by Santhosh-Sellavel** [comment] 2022-11-21 14:52
@kavimuru Can you check whether this is reproducible, unable to reproduce from my end too!

**Comment by kavimuru** [comment] 2022-11-22 14:14
@Santhosh-Sellavel checking with the tester and will update here shortly.

**Comment by kavimuru** [comment] 2022-11-22 17:01
@Santhosh-Sellavel Tester is still able to reproduce.

https://user-images.githubusercontent.com/43996225/203375900-df1e78d6-cad6-454d-8d5e-bc8dfe5ce6d5.MP4

**Comment by robertjchen** [comment] 2022-11-23 11:24
Was able to reproduce this locally as well! @mollfpr do you possibly have an update on your debugging efforts and explanation on your proposed solution? 🙏

**Comment by laurenreidexpensify** [comment] 2022-11-28 11:28
@mollfpr bump do you have an update yet :)

**Comment by mollfpr** [comment] 2022-11-28 12:36
Sorry, I miss this issue. I'll make a summary within an hour.

**Comment by mollfpr** [comment] 2022-11-28 13:36
The issue is only reproduced if the chat shows the recipient's local time and we will set `contentContainerStyle` with `padding-top=0`. Also, it not only reproduces when saving the message but also canceling the edited message.

The issue is from the `maintainVisibleContentPosition.autoscrollToTopThreshold` of the `FlatList` component. While `maintainVisibleContentPosition` is used to fix https://github.com/Expensify/App/issues/7145 so we can't remove that.
https://github.com/Expensify/App/blob/d3acbab01146fcca6965ac86821879188cd6bac0/src/components/InvertedFlatList/BaseInvertedFlatList.js#L147

I don't have any explanation for why setting the padding-top to `0` is causing the problem and setting the padding-top to more than `0` will fix the issue.

**Comment by robertjchen** [comment] 2022-11-28 15:58
Got it, thanks for the summary! I think it's probably a quirk with how the visibility is calculated with the component and having a padding-top > 0 makes all the difference 🤷 

Given the current state of things, I'd say we can move forward with this hack for now 👍 but let's make sure it doesn't have any discernible visual effects on the other platforms: desktop/web/android, etc. and if we can have a small comment there with additional context on why we have the padding-top > 0, that would be great!

**Comment by mollfpr** [comment] 2022-11-29 03:10
We can move the `padding-top=5` from `styles.chatItemComposeSecondaryRow` on `ParticipantLocalTime` style to the `contentContainerStyle` flat list. In this way don't need any extra padding to fix the issue and keep the style the same as before.

```diff
diff --git a/src/pages/home/report/ParticipantLocalTime.js b/src/pages/home/report/ParticipantLocalTime.js
index a93d2e57a..74f581c96 100644
--- a/src/pages/home/report/ParticipantLocalTime.js
+++ b/src/pages/home/report/ParticipantLocalTime.js
@@ -60,7 +60,7 @@ class ParticipantLocalTime extends PureComponent {
                 : this.props.participant.displayName);

         return (
-            <View style={[styles.chatItemComposeSecondaryRow]}>
+            <View style={[styles.chatItemComposeSecondaryRow, styles.pt0]}>
                 <Text
                     style={[
                         styles.chatItemComposeSecondaryRowSubText,
diff --git a/src/pages/home/report/ReportActionsList.js b/src/pages/home/report/ReportActionsList.js
index d62d4e247..98e068a72 100644
--- a/src/pages/home/report/ReportActionsList.js
+++ b/src/pages/home/report/ReportActionsList.js
@@ -159,7 +159,7 @@ class ReportActionsList extends React.Component {
                     renderItem={this.renderItem}
                     contentContainerStyle={[
                         styles.chatContentScrollView,
-                        shouldShowReportRecipientLocalTime && styles.pt0,
+                        shouldShowReportRecipientLocalTime && styles.chatContentRecipientLocalTime,
                     ]}
                     keyExtractor={this.keyExtractor}
                     initialRowHeight={32}
diff --git a/src/styles/styles.js b/src/styles/styles.js
index b6b617b30..977b27588 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1275,6 +1275,10 @@ const styles = {
         paddingVertical: 16,
     },

+    chatContentRecipientLocalTime: {
+        paddingTop: 5,
+    },
+
     // Chat Item
     chatItem: {
         display: 'flex',
```


https://user-images.githubusercontent.com/25520267/204429359-0537fb94-d806-4e65-bad8-d1e8b489c6b0.mov

**Comment by robertjchen** [comment] 2022-11-29 03:49
@mollfpr Great find! That sounds like an even better approach 👍

**Comment by JmillsExpensify** [comment] 2022-11-29 21:15
Are we hiring @mollfpr? If so, let's please get him assigned to the issue.

**Comment by dangrous** [comment] 2022-11-29 23:34
This looks great, @mollfpr! Assigning you now.

**Comment by laurenreidexpensify** [comment] 2022-11-30 11:53
@Santhosh-Sellavel @mollfpr both hired in Upwork ✔️

**Comment by mollfpr** [comment] 2022-11-30 14:18
Thank you! Will raise the PR in a couple of hours.

**Comment by mollfpr** [comment] 2022-11-30 18:19
Sorry about this [proposal](https://github.com/Expensify/App/issues/12198#issuecomment-1330017539) not working well. The style of `styles.chatItemComposeSecondaryRow` uses using margin (I don't know why I see it as padding), so moving the margin style to the list container will remove the spacing between the recipient's local time text.

 I ended up just adding `padding-top=1` to the list container instead. Are we okay with this?

cc @robertjchen @dangrous

**Comment by dangrous** [comment] 2022-11-30 19:07
@mollfpr I think that would probably be fine. However, I was just looking at your PR and I tried testing on `main` first just to make sure I knew the bad behavior and... I'm not actually seeing it anymore. I'm wondering if something with the new theming somehow fixed it?

Are you (or @robertjchen or @Santhosh-Sellavel) still able to reproduce? We may not need this after all... Unless it's something with my simulator which is perfectly possible.

**Comment by mollfpr** [comment] 2022-11-30 19:24
@dangrous I'm able to reproduce it in the simulator. Is your chat showing the recipient's local time above the composer?

<img width="434" alt="Screen Shot 2022-12-01 at 02 24 16" src="https://user-images.githubusercontent.com/25520267/204889715-2ac111b2-afd1-401c-86e3-c73cbb37a8df.png">

**Comment by Santhosh-Sellavel** [comment] 2022-11-30 19:35
@mollfpr Please attach a video performing steps, that's solid to keep us working on that!

**Comment by Santhosh-Sellavel** [comment] 2022-11-30 19:36
> Sorry about this [proposal](https://github.com/Expensify/App/issues/12198#issuecomment-1330017539) not working well. The style of `styles.chatItemComposeSecondaryRow` uses using margin (I don't know why I see it as padding), so moving the margin style to the list container will remove the spacing between the recipient's local time text.
> 
> I ended up just adding `padding-top=1` to the list container instead. Are we okay with this?
> 
> cc @robertjchen @dangrous

No, It's better to re-evaluate things let's make it open to proposals or dig more to find the exact cause.

**Comment by Santhosh-Sellavel** [comment] 2022-11-30 19:38
> @mollfpr I think that would probably be fine. However, I was just looking at your PR and I tried testing on `main` first just to make sure I knew the bad behavior and... I'm not actually seeing it anymore. I'm wondering if something with the new theming somehow fixed it?
> 
> Are you (or @robertjchen or @Santhosh-Sellavel) still able to reproduce? We may not need this after all... Unless it's something with my simulator which is perfectly possible.

@dangrous I too have trouble reproducing it but it was able to reproduce by QA Last week [here](https://github.com/Expensify/App/issues/12198?notification_referrer_id=NT_kwDOBRraj7M0Njk5ODAwODAzOjg1NjQ1OTY3#issuecomment-1323986030)

@kavimuru Can you check this one more time now, also is this able to reproduce consistently by the tester? Thanks!

**Comment by mollfpr** [comment] 2022-11-30 19:49
>@mollfpr Please attach a video performing steps, that's solid to keep us working on that!

Sorry, here's the video.

https://user-images.githubusercontent.com/25520267/204894141-8b273e78-492c-4671-b05f-d443cc346575.mov

> @dangrous I too have trouble reproducing it but it was able to reproduce by QA Last week https://github.com/Expensify/App/issues/12198?notification_referrer_id=NT_kwDOBRraj7M0Njk5ODAwODAzOjg1NjQ1OTY3#issuecomment-1323986030

I think it would be great if you could record the step you do. So we would have a clue why is reproduce in some places.

**Comment by Santhosh-Sellavel** [comment] 2022-12-01 17:00
@mollfpr I am able to reproduce this issue Maybe I tried earlier without the timezone.

https://user-images.githubusercontent.com/85645967/205113829-5b6dd19d-2276-416c-aa97-9a345becc6af.mp4

cc: @dangrous

**Comment by dangrous** [comment] 2022-12-02 16:08
Took me a couple tries but was able to reproduce again as well. Alright, @mollfpr if it's okay maybe we keep digging to try to figure out another option than the added padding... If we can't, let's do a thorough check to make sure that doesn't make any visible difference anywhere else, and then we can move forward if needed. Thanks!

**Comment by mollfpr** [comment] 2022-12-02 16:14
Yup, I’m okay with that! Should I assign it while we are digging?

**Comment by Santhosh-Sellavel** [comment] 2022-12-02 16:29
@dangrous 
Let's unassign @mollfpr, and add the help wanted label here! As we are nowhere near a solution we both could just end up penalized.

cc: @laurenreidexpensify Also let's double this up to our new price $1000. To get more eyes thanks!

**Comment by dangrous** [comment] 2022-12-02 18:47
Unassigned and added the label back. @Santhosh-Sellavel and @mollfpr do you want to start a discussion in Slack to see if we can get some other eyes on this? Might be good to see what ideas the other folx in the channel have

**Comment by priyeshshah11** [comment] 2022-12-02 18:48
@dangrous I have found the actual issue/fix, posting my proposal soon.

**Comment by priyeshshah11** [comment] 2022-12-02 19:34
# Proposal

## Problem

The main issue here is that the height of the list view changes due to the toggling of edit mode i.e. `<ReportActionItemMessage />` and `<ReportActionItemMessageEdit />` have different heights. This causes confusion to the list view in terms of where it needs to scroll to when the keyboard is being closed. It scrolls to the original place where the edit input was, assuming it is still visible. But that's when the edit input gets hidden which reduces the height of the item & the list, which cause the edited comment to go out of the visible part of the list view.

**Reproduced it in slow motion here**

https://user-images.githubusercontent.com/38547776/205369737-fc2d578f-c2c7-408e-a408-8ad89044c311.mov

## Solution

Set a timeout of X ms (500ms seems to work fine) to scroll to the current item in the list once the editing is complete.
We can do this by adding the setTimeout line below in `deleteDraft` as it is called by both the cancel & save changes buttons for editing.

```
    deleteDraft() {
        this.debouncedSaveDraft.cancel();
        Report.saveReportActionDraft(this.props.reportID, this.props.action.reportActionID, '');
        toggleReportActionComposeView(true, this.props.isSmallScreenWidth);
        ReportActionComposeFocusManager.focus();
        setTimeout(() => ReportScrollManager.scrollToIndex({animated: true, index: this.props.index}, false), 500);
    }
```

**After Fix**

https://user-images.githubusercontent.com/38547776/205370013-8c7a4162-ae1b-4fb0-a957-33fa02bb7b1a.mov

https://user-images.githubusercontent.com/38547776/205370021-85602d5c-a8dc-48fd-8342-d67c817b2fed.mov

@dangrous @Santhosh-Sellavel Please review.

**Comment by mollfpr** [comment] 2022-12-04 03:23
https://reactnative.dev/docs/scrollview#maintainvisiblecontentposition-ios
>Caveat 2: This uses contentOffset and frame.origin in native code to compute visibility. Occlusion, transforms, and other complexity won't be considered whether content is "visible" or not.

It's stated that `maintainVisibleContentPosition` is using `contentOffset.` Also, as I said, this issue only occurred when the keyboard was closing, and the height of the list was changing due to the removed edit composer input.

**_When we use padding-top <= 0 to `contentContainerStyle,` the `contentOffset.y` last value is `28`._**

https://user-images.githubusercontent.com/25520267/205471379-771a042b-9c8a-4263-9f43-a4ebefb9db04.mov


**_It has different results when we use a padding-top one. The `contentOffset.y` last value is `-27`._**

https://user-images.githubusercontent.com/25520267/205471384-7a147c5d-d3d9-41cc-9fcd-7024279560d8.mov


- `contentContainerStyle` padding-top <= 0
  - When showing the edit composer input, `contentOffset.y` start at `36.333333333333336` and change to `50` because of the edit composer input height.
  - When the edit composer input showed the `contentOffset.y` value is `0.`
  - When the edit composer input is closing, the `contentOffset.y` value is `-50.333333333333336` (diff from the `contentSize.height` when the edit composer input is removed) and ends at `50.333333333333336` and makes the chat offset

- `contentContainerStyle` padding-top > 0
  - When showing the edit composer input, `contentOffset.y` start at `0` and change to `16` (the value of our padding vertical for the list)
  - When closing the edit composer input, `contentOffset.y` is only set once, and it's a minus value where it's not changing the position

My conclusion for the above, the doc said in **Caveat 2** that there is a possibility that content is not managed correctly to show its visibility.

---

I also found on chat that not showing the recipient's local time and editing the last message; there's a gap below the edit composer input. I don't know if this desire looks. I think we should set the padding top for the list to the container in all conditions.

https://user-images.githubusercontent.com/25520267/205472062-71d09d05-e936-4049-8356-18479eb0de2e.mov

The solution might depend on the action we take for the above issue.
---

@priyeshshah11 also has a good point about the [problem](https://github.com/Expensify/App/issues/12198#issuecomment-1335721999) is, but using `setTimeout` is not what we looking for.

**Comment by Santhosh-Sellavel** [comment] 2022-12-04 15:52
@priyeshshah11 We don't recommend use of setTimeout. 

Thanks @mollfpr for detailed explanation here!

**Comment by laurenreidexpensify** [comment] 2022-12-05 12:17
Increased to $1000

**Comment by Santhosh-Sellavel** [comment] 2022-12-05 14:07
@priyeshshah11 Never update the proposal which is already reviewed. Always submit it in a new comment, it's easy to track things that happened here. So please submit a new comment with the changes, thanks!

**Comment by priyeshshah11** [comment] 2022-12-05 14:15
> @priyeshshah11 Never update the proposal which is already reviewed. Always submit it in a new comment, it's easy to track things that happened here. So please submit a new comment with the changes, thanks!

@Santhosh-Sellavel sure, here it is.

# Proposal

**Reproduced it in slow motion here**

https://user-images.githubusercontent.com/38547776/205369737-fc2d578f-c2c7-408e-a408-8ad89044c311.mov

## Solution

Scroll to the current item in the list once the editing is complete i.e. once the keyboard has closed.
We can do this by adding the `keyboardDidHide` event listener below in `deleteDraft` as it is called by both the cancel & save changes buttons for editing and then clear the listener at the end of that callback.
Also, we should only do this for the last comment as this is only an issue for the last comment otherwise it creates an unnecessary scroll for other comments.

https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItemMessageEdit.js#L129-L134
```
    deleteDraft() {
        this.debouncedSaveDraft.cancel();
        Report.saveReportActionDraft(this.props.reportID, this.props.action.reportActionID, '');
        toggleReportActionComposeView(true, this.props.isSmallScreenWidth);
        ReportActionComposeFocusManager.focus();
        if (this.props.index === 0) {
            const keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', () => {
                ReportScrollManager.scrollToIndex({animated: true, index: this.props.index}, false);
                keyboardDidHideListener.remove();
            });
        }
    }
```

**After Fix**



https://user-images.githubusercontent.com/38547776/205658309-cd5a8db3-de1a-4a92-8741-8c9a4ef1fa4a.mp4

**Comment by mollfpr** [comment] 2022-12-06 12:52
I couldn't find any clue how we can solve this with JS. The scroll with threshold is done in the native ScrollView.
```c
      CGRect newFrame = self->_firstVisibleView.frame;
      CGFloat deltaY = newFrame.origin.y - self->_prevFirstVisibleFrame.origin.y;
      if (ABS(deltaY) > 0.1) {
        CGFloat bottomInset =
            self.inverted ? self->_scrollView.contentInset.top : self->_scrollView.contentInset.bottom;
        CGFloat y = self->_scrollView.contentOffset.y + bottomInset;
        self->_scrollView.contentOffset =
            CGPointMake(self->_scrollView.contentOffset.x, self->_scrollView.contentOffset.y + deltaY);
        if (autoscrollThreshold != nil) {
          // If the offset WAS within the threshold of the start, animate to the start.
          if (y - deltaY <= [autoscrollThreshold integerValue]) {
            [self scrollToOffset:CGPointMake(self->_scrollView.contentOffset.x, -bottomInset) animated:YES];
          }
        }
      }

```
https://github.com/facebook/react-native/blob/913ebd207c2e7bc1182eab0bd8d82e7d9d7ee567/React/Views/ScrollView/RCTScrollView.m#L953-L967

---

I guess adding padding-top is influent the `deltaY` value and triggers the scroll threshold in the correct position. The lowest value for padding-top we can add is `0.2`.

**Comment by priyeshshah11** [comment] 2022-12-06 18:15
> @Santhosh-Sellavel sure, here it is.

@Santhosh-Sellavel  any feedback on this proposal?

**Comment by Santhosh-Sellavel** [comment] 2022-12-06 21:53
Sorry for the delay,  but this is unnecessary for other platforms.

**Comment by priyeshshah11** [comment] 2022-12-07 00:10
> Sorry for the delay, but this is unnecessary for other platforms.

Then should we apply my suggested fix just for `iOS` by adding this line
`if (Platform.OS !== 'ios') { return; }` after in **deleteDraft** ?

```
deleteDraft() {
    this.debouncedSaveDraft.cancel();
    Report.saveReportActionDraft(this.props.reportID, this.props.action.reportActionID, '');
    toggleReportActionComposeView(true, this.props.isSmallScreenWidth);
    ReportActionComposeFocusManager.focus();
    if (this.props.index === 0) {
        const keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', () => {
            ReportScrollManager.scrollToIndex({animated: true, index: this.props.index}, false);
            keyboardDidHideListener.remove();
        });
    }
}
```

**Comment by dangrous** [comment] 2022-12-07 19:12
Yeah I don't love that it's basically useless anywhere but iOS, but it does make sense.... If we were to go this route though I'd definitely prefer having it fire all the time to the `Platform.OS !== 'ios' ` version. Will the first version of the code cause any problems on web/desktop/anywhere there's no `Keyboard` to hide?

What do you think @robertjchen?

**Comment by Santhosh-Sellavel** [comment] 2022-12-07 19:21
> Will the first version of the code cause any problems on the web/desktop/anywhere there's no Keyboard to hide?
 
 Yeah, console errors are thrown.

**Comment by dangrous** [comment] 2022-12-07 19:35
Ah, okay thanks for clarifying. Yeah we'll want to keep looking then I think

**Comment by JmillsExpensify** [comment] 2022-12-07 21:22
@laurenreidexpensify Can you double this job please? Thanks!

**Comment by priyeshshah11** [comment] 2022-12-07 21:42
> I'm confused this looks straightforward but also unnecessary at the same time. As this occurs happens only when participant time is shown.

@Santhosh-Sellavel @dangrous I was able to reproduce this even without the participant time showing.

https://user-images.githubusercontent.com/38547776/206302728-6391a0a4-52e5-4b8a-ae85-a338b5d7c062.mov

**Comment by priyeshshah11** [comment] 2022-12-07 22:04
> > Will the first version of the code cause any problems on the web/desktop/anywhere there's no Keyboard to hide?
> 
> Yeah, console errors are thrown.

@Santhosh-Sellavel have you tested it? because I don't see any console errors in the browser.

**Comment by mollfpr** [comment] 2022-12-08 02:50
> @Santhosh-Sellavel @dangrous I was able to reproduce this even without the participant time showing.

@priyeshshah11 What version is this? And from your video, no padding between the latest chat message and the composer where it's should be padding there.

**Comment by MitchExpensify** [comment] 2022-12-09 15:11
@dangrous  this is one of the oldest issues in the /App repo. To help us clear out the large backlog of bugs, can you:

- Decide whether any proposals currently meet our guidelines and can be approved as-is
- For any that can't, please take this issue internal and treat it as one of your highest priorities
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by dangrous** [comment] 2022-12-09 16:47
So I just tested @priyeshshah11 's [proposal](https://github.com/Expensify/App/issues/12198#issuecomment-1337443387) on the latest `main` and I think it should work - it _is_ unnecessary for the other platforms but I'm not getting any console errors so I think we might be fine. Doesn't seem to affect behavior on non-timezone chats, and works on the timezone ones.

@Santhosh-Sellavel do you mind double checking my work (e.g. testing) and see if you're seeing any reason not to move forward here, other than the slight conceptual sadness of having it be a global solution only for iOS?

**Comment by Santhosh-Sellavel** [comment] 2022-12-09 17:03
@dangrous 

![Uploading Screenshot 2022-12-09 at 10.33.32 PM.png…]()

**Comment by priyeshshah11** [comment] 2022-12-09 17:26
> @dangrous
> 
> Have you tried editing a message on web/desktop?
> 

That seems very weird as I am not getting those errors, I have been testing on web. I can see the addListener function when I log `Keyboard`.

<img width="525" alt="Screen Shot 2022-12-10 at 4 25 05 AM" src="https://user-images.githubusercontent.com/38547776/206758414-2161d48e-014a-4378-9c61-b4915e5d943e.png">

**Comment by dangrous** [comment] 2022-12-09 17:26
yeah, I did... nothing showed up for me. Did you import Keyboard up top?

`import {InteractionManager, View} from 'react-native';`

(L3 of that file)

**Comment by Santhosh-Sellavel** [comment] 2022-12-09 17:57
Ah 😁 yeah, I missed importing it rookie mistake! 

The solution works on iOS, But still, this looks like a workaround to me.

@dangrous. Need to test on other platforms to ensure it doesn't have any weird effects there.

**Comment by priyeshshah11** [comment] 2022-12-09 18:49
> Ah 😁 yeah, I missed importing it rookie mistake!
> 
> The solution works on iOS, But still, this looks like a workaround to me.
> 
> @dangrous. Need to test on other platforms to ensure it doesn't have any weird effects there.

Tested on iOS, web, mweb & desktop, works well on all of them. Trying to get android emulator going.

**Comment by dangrous** [comment] 2022-12-09 21:26
I checked out Android, iOS, desktop web, and Desktop and they all seemed okay; mobile web is not working for me right now so TBD on those ones. If we can move forward on Monday, that would be great!

As for this being a workaround or not, I mean I guess I can see where you're coming from. But, I don't feel like this is particularly hacky per se - the Keyboard tends to cause all sorts of problems and this is a relatively clean solution. @robertjchen - would love to know what you think, as you're more experienced!

**Comment by priyeshshah11** [comment] 2022-12-12 12:53
@Santhosh-Sellavel all platforms have now been tested and are working well, are we good to proceed?

**Comment by Santhosh-Sellavel** [comment] 2022-12-12 15:56
Okay let's proceed with the @priyeshshah11 proposal, thanks!

**Comment by priyeshshah11** [comment] 2022-12-12 22:33
Applied on upwork & the PR will be ready either today or tomorrow. Also, should the job be $2000 as per https://github.com/Expensify/App/issues/12198#issuecomment-1341614648 ? It is currently set at $500 on upwork.

**Comment by Santhosh-Sellavel** [comment] 2022-12-12 22:59
@priyeshshah11 Final payment will be made correctly. 

Let me know when PR is ready for review!

**Comment by priyeshshah11** [comment] 2022-12-12 23:06
> @priyeshshah11 Final payment will be made correctly.
> 
> Let me know when PR is ready for review!

@Santhosh-Sellavel https://github.com/Expensify/App/pull/13543#issuecomment-1347465470

**Comment by laurenreidexpensify** [comment] 2022-12-28 11:18
@priyeshshah11 apols for the delay here - Christmas holidays have messed up this week a bit 😅 Once you accept contract in Upwork I will issue payment. Thanks

@Santhosh-Sellavel your fee has been issued now 👍🏽

**Comment by Santhosh-Sellavel** [comment] 2022-12-28 14:06
@laurenreidexpensify this qualifies bonus also As it is merged within 3 business days.

**Comment by priyeshshah11** [comment] 2022-12-28 16:21
> @priyeshshah11 apols for the delay here - Christmas holidays have messed up this week a bit 😅 Once you accept contract in Upwork I will issue payment. Thanks

@laurenreidexpensify No worries, I understand 😁 I have replied to you on upwork for the bonus. Thanks! 😊

**Comment by laurenreidexpensify** [comment] 2022-12-29 11:52
@Santhosh-Sellavel @priyeshshah11 All sorted- payments and bonuses issued 👍🏽

**Comment by laurenreidexpensify** [comment] 2023-01-03 14:45
@Santhosh-Sellavel / @robertjchen / @dangrous - waiting on you to complete these steps https://github.com/Expensify/App/issues/12198#issuecomment-1358867572 so we can close. thanks

**Comment by dangrous** [comment] 2023-01-03 17:20
I feel like I've been saying this for all of my bugs lately, but I think this is not really a regression, rather it's an unnoticed case that we hadn't accounted for when the code was created - i.e. it never had the proper behavior. We've had [a number of issues with the keyboard](https://github.com/Expensify/App/issues/10273) so this might just be a similar one.

@Santhosh-Sellavel or @robertjchen feel free to disagree - what do you think?

**Comment by Santhosh-Sellavel** [comment] 2023-01-03 19:17
I agree with you @dangrous

**Closed** 2023-01-05 10:04 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
