### ISSUE TITLE
[HOLD for payment 2024-08-13] [$250] mWeb - Workspace - In archived workspace, in iou details page sideways caret are shown for fields

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45851] opened 2024-07-20 21:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home

2. Tap on a workspace chat
3. Submit an expense entering all fields
7. Navigate to LHN
8. Tap profile icon -- workspaces -- workspace
9. Tap on 3 dots icon next to workspace
10. Delete the workspace
11. Navigate to LHN
12. Open the archived workspace chat
13. Open the IOU
14. Open amount and description field using sideways caret
15. Note hhm not here page is shown

## Expected Result:
Like in task details page, sideways caret must not be shown in iou details page in archived workspace

## Actual Result:
In archived workspace, in iou details page sideways caret for amount & description field are shown directing to hhm not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a30269bc-e29a-43fd-9579-5cc4c30dbdcf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019bd42da3fc0d7c59</li>
        <li>Upwork Job ID: 1815412203411994715</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103308909</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by lanitochka17** [comment] 2024-07-20 21:13
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-20 21:13
We think that this bug might be related to #wave-collect - Выпуск 1

**Comment by joekaufmanexpensify** [comment] 2024-07-22 15:42
This doesn't seem to be happening only on Android. I reproduced it on Chrome web. I also don't think the task steps are necessary for reproducing. They help show that you can't edit fields on a task with an archived workspace, but I removed them from OP to make the bug easier to reproduce.

**Comment by joekaufmanexpensify** [comment] 2024-07-22 15:42
Makes sense to me that we wouldn't allow you to edit any fields on an expense when the workspace it's reported on is archived.

**Comment by Tony-MK** [comment] 2024-07-23 07:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

mWeb - Workspace - In archived workspace, in iou details page sideways caret are shown for fields

### What is the root cause of that problem?

The root cause of the problem is that `canEditMoneyRequest` function will return `true` in this case when the policy is not found and `isManager` is `true` to allow the user to edit an expense report even if it is a state higher than `OPEN (0)`.

https://github.com/Expensify/App/blob/38cddeeb3879a1eefd4458ba69083c84c8fd83b1/src/libs/ReportUtils.ts#L2717-L2719

However, if the expense is not open, the `canEditMoneyRequest` function returns `true` to allow the user still to edit the description, category, or tag sections.

### What changes do you think we should make in order to solve the problem?


Let's check if the `moneyRequestReport` is not archived on the [line](https://github.com/Expensify/App/blob/38cddeeb3879a1eefd4458ba69083c84c8fd83b1/src/libs/ReportUtils.ts#L2718).

https://github.com/Expensify/App/blob/38cddeeb3879a1eefd4458ba69083c84c8fd83b1/src/libs/ReportUtils.ts#L2719

```
return !isArchivedRoom(moneyRequestReport);
```

Just like how a user can not edit a task from an archived report.

https://github.com/user-attachments/assets/f914ca10-6227-4b5d-99b5-c72ec31a834b

**Comment by joekaufmanexpensify** [comment] 2024-07-23 13:21
Pending review of proposals

**Comment by hungvu193** [comment] 2024-07-23 14:18
I'll take a look tomorrow morning

**Comment by hungvu193** [comment] 2024-07-24 03:39
Thanks for proposals everyone, @Krishna2323 's [proposal](https://github.com/Expensify/App/issues/45851#issuecomment-2241494175) looks straight forward to me.

🎀 👀 🎀  C+ reviewed

**Comment by hungvu193** [comment] 2024-07-24 05:32
Thanks for the information, IIRC we still allow user to edit information with error report.
Can you please confirm?  @joekaufmanexpensify

**Comment by hungvu193** [comment] 2024-07-24 09:55
I see your point here, no need to discuss further, let wait for [this confirmation](https://github.com/Expensify/App/issues/45851#issuecomment-2246937909). Thanks

**Comment by cristipaval** [comment] 2024-07-24 13:12
@hungvu193 please tag me again after you clarify. Thanks!

**Comment by joekaufmanexpensify** [comment] 2024-07-24 13:38
>Thanks for the information, IIRC we still allow user to edit information with error report.
Can you please confirm?

Is the question whether it's expected that you can edit an expense when it has an error like that and the workspace is not archived? Or when the workspace is archived? 

If the latter, then I would expect you could not edit the expense. If the workspace is not archived, I would think you could, but I am not 100% sure. Please confirm the steps to get an expense into that state and I will test on my end.

**Comment by hungvu193** [comment] 2024-07-25 07:04
@joekaufmanexpensify you can use [these steps](https://github.com/Expensify/App/issues/45851#issuecomment-2247984990).




> Is the question whether it's expected that you can edit an expense when it has an error like that and the workspace is not archived? Or when the workspace is archived?

Yes, incase report has error but it's not archived.

**Comment by joekaufmanexpensify** [comment] 2024-07-25 14:42
>I don't think it is edge case. The RequestMoney API encounters the error in the common case. Here is another way to reproduce that case:
1. FAB > Submit expense > Manually
2. Do the creating expense until we visit the confirmation page.
3. Type CMD+D then choose "Simulate failing network requests".
4. Click on "Submit ..." button in confirmation page.
5. Wait until the created expense throw the error.
6. Open expense transaction thread.
7. Try to edit any field.

I can't get these reproduction steps to work. I just get stuck on the skeleton UI after step 4. 

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/b2c2a448-e6ba-46cf-bb45-a907bbb3d918">

**Comment by joekaufmanexpensify** [comment] 2024-07-25 14:48
Okay, I was able to reproduce this. When you create an expense with an error like this, you should not be able to edit any of the fields, because the expense was not successfully created. As soon as you click the `X` on the IOU preview, or actually within it, the expense will be deleted. We're just alerting you to the error so you know you'll need to create it again in the future. 

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/d58d77d8-c5c5-4ed3-9fd6-1b1fc9a2d859">

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/890a4c2f-7147-4478-8b78-643c24fc3bf2">

**Comment by joekaufmanexpensify** [comment] 2024-07-25 14:49
If we can clean up this behavior too in the same PR and remove the carets to edit the fields (since editing the fields isn't possible), alongside doing this for archived workspaces, that'd be great.

**Comment by hungvu193** [comment] 2024-07-25 14:53
Thanks @joekaufmanexpensify for your detailed explanation 🙏 

In this case, I'd go with @dominictb 's [proposal here](https://github.com/Expensify/App/issues/45851#issuecomment-2241575465).

🎀 👀 🎀 C+ reviewed

**Comment by joekaufmanexpensify** [comment] 2024-07-26 13:37
Pending sign off on selected proposal

**Comment by hungvu193** [comment] 2024-07-29 11:03
little bump @cristipaval

**Comment by joekaufmanexpensify** [comment] 2024-07-30 12:52
@dominictb is there an ETA for the PR here?

**Comment by joekaufmanexpensify** [comment] 2024-08-05 13:27
PR merged

**Comment by hungvu193** [comment] 2024-08-13 03:11
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42571 is not really the offending PR, we can treat this issue as an improvement.
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug: Yes

**Regression test:**
1. Create an expense for any workspace.
2. Go to that workspace and delete the workspace.
3. Visit that expense again, click on that expense to open the detail page.
4. Verify that you can not edit the expense information and the sideways caret aren't shown.

Do we 👍  or 👎  ?

**Comment by joekaufmanexpensify** [comment] 2024-08-13 13:47
All set to issue payment. We need to pay: 

- @dominictb - $250 for PR via upwork. 
- @hungvu193 - $250 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment] 2024-08-13 13:48
@dominictb $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-08-13 13:48
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-08-13 13:48
Closing for now, since all that's left is for @hungvu193 to request payment via NewDot. Thanks everyone!

**Closed by joekaufmanexpensify** 2024-08-13 13:48 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-14 17:39
$250 approved for @hungvu193
