### ISSUE TITLE
Web - Room - Unable to use arrow keys to select notification options

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21435] opened 2023-06-23 17:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new..expensify.com
2. Go to any room
3. Click on room header
4. Go to Settings > Notify me about new messages
5. Use keyboard arrow keys to navigate the options

## Expected Result:
User is able to use arrow keys to select notification options

## Actual Result:
User is unable to use arrow keys to select notification options

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/81f301c3-70ee-4773-b750-98d0e920bb3e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment] 2023-06-24 06:11
This is not a bug as we haven't implemented arrow selection on any of the select list. As in language also user is not able to select the language using arrow keys.

Arrow keys navigation is Currently Implemented at:
- Messages List
- Selecting a user from user's list
- Emoji List
- Attachment picker
- Context Menu List

**Comment by sophiepintoraetz** [comment] 2023-06-26 01:43
I agree - @jeet-dhandha - do you have the GH/PRs handy where we reference this? If anything, this would be a new feature request, and a low priority one at that so closing for now.

**Closed by sophiepintoraetz** 2023-06-26 01:43 UTC
Labels: Daily, Bug

**Comment by jeet-dhandha** [comment] 2023-06-26 08:29
@sophiepintoraetz - I just searched through the code for the list. Don't have any particular PR.
