### ISSUE TITLE
[HOLD for payment 2022-10-21] [$250] When a user is offline clicking on internal links shows a growl that you are offline - Reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10625] opened 2022-08-29 03:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message which contains https://www.expensify.com/inbox.
2. Click on the link.

## Expected Result:
A growl is shown to the user that you are offline.

## Actual Result:
User should be taken to that link as it is a valid url and not of our app's domain.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.91-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/187115018-c45f595d-ce40-48b6-a420-b4786fc11259.mp4

https://user-images.githubusercontent.com/43995119/187115081-5f418034-a4a0-4978-8371-c9316e362722.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660322955708219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sketchydroide** [comment] 2022-08-29 11:13
Adding @AndrewGable cause you recently did some work on the links so you might know a bit more of the logic.
This is not a deploy blocker so I think it could be an external.

That said @mvtglobally the 2 videos seems to be the same, not sure if that is on purpose or one of them is the wrong, can you check please

**Comment by sketchydroide** [comment] 2022-09-05 09:50
I'm settign this one as an external

**Comment by arielgreen** [comment] 2022-09-13 23:42
https://www.upwork.com/jobs/~01e669d3893dab99be

**Comment by vladamx** [comment] 2022-09-14 09:14
Hi all,

There are 2 related files to this issue:
1. [AnchorRenderer.js](https://github.com/Expensify/App/blob/main/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L43)
which is detecting that we are actually navigating to oldExpensifyPath
2. [Link.js](https://github.com/Expensify/App/blob/main/src/libs/actions/Link.js#L37)
which fails early if no network because it assumes that it needs authToken for the link to work. For the authToken exchange - network is required

Proposal:
Fallback to just navigating to the link without authToken(short-lived authentication token) param if no service, otherwise append authToken param. This will open the link in a new browser tab like any other link. 
After network is online again everything seems to work fine - the app will even maintain user's login state if there was any, otherwise it will show login page.

Bonus:
Do we even need authToken exchange at all? From my testing the observable behavior of the app doesn't change with or without it.

**Comment by quidam93** [comment] 2022-09-14 10:01
### PROPOSAL
**Root Cause**
There is a filter process in the AnchorRenderer to verify the links as internal links and external links. Issue is, this process thinks that expensify.com/index is an external link because it does not start with "www.". 
![image](https://user-images.githubusercontent.com/26013008/190122921-f9272f0f-e8e4-479a-bda0-2e8e3b1c3ec5.png)
As you can see, it checks for an URL if they start with "EXPENSIFY_URL" constant. And this constant if set to "https://www.expensify.com/'" right now. 

While the dynamic links are loaded into this component at first, links without a "www." gets their href as "https://expensify/index". So when checking if they are an internal or external, since the link doesn't have "www." prefix, they are treated as an external link. And external links are handled with opening a new window as per in the code below.
![image](https://user-images.githubusercontent.com/26013008/190123847-0b2cd7b2-589b-4b9f-8e9a-eae23dfae3f0.png)


**Solution**
We can change all link to handled without "www." prefix. To do that, we can delete this prefix if it exists.
![image](https://user-images.githubusercontent.com/26013008/190124166-453c4e29-b8a4-43a9-90ef-1123be1bfa59.png)

And in the constant side
![image](https://user-images.githubusercontent.com/26013008/190124356-a7d9a66e-a26b-44f0-8536-d335128372d8.png)

Now all links that has www. or not will be treated as same in the application. 

**Solution 2**
We can define a new constant for Expensify url without a "www." prefix and change the filter accordingly. 

Thanks!

**Comment by sketchydroide** [comment] 2022-09-19 11:09
@chiragsalian not sure why it assigned you if I can myself take this?
Feel free to unasign if you want, or if you want to keep it unasign me 🤷🏼

**Comment by arielgreen** [comment] 2022-09-21 21:49
@mananjadhav please see above proposals!

**Comment by mananjadhav** [comment] 2022-09-24 23:12
Hey @arielgreen I am a bit tied up with my backlog. I didn't see this issue, can you please reassign this one.

**Comment by sketchydroide** [comment] 2022-09-27 11:33
not overdue, we had to assgin a new C+

**Comment by arielgreen** [comment] 2022-09-29 00:33
@rushatgabhane see above proposals, please

**Comment by arielgreen** [comment] 2022-09-30 01:33
@sobitneupane can you please review the proposals above?

**Comment by sobitneupane** [comment] 2022-09-30 15:29
>  Fallback to just navigating to the link without authToken(short-lived authentication token) param if no service, otherwise append authToken param. This will open the link in a new browser tab like any other link.

@vladamx I like your idea  [here](https://github.com/Expensify/App/issues/10625#issuecomment-1246475018). But can you be more concrete with your proposal? How and where are you planning to "Fallback to just navigating to the link" ? Some code blocks will make it more clear.

@quidam93 I don't think your proposal is aligned to the problem description.

**Comment by vladamx** [comment] 2022-09-30 17:50
@sobitneupane 
Either this
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/11381171/193327721-34134a17-85d2-433a-8aa9-da9da9267a45.png">

OR

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/11381171/193327896-eb972f0a-c48f-4e7d-a1da-72d22a1e2a10.png">

**Comment by sobitneupane** [comment] 2022-10-02 02:15
> Do we even need authToken exchange at all? From my testing the observable behavior of the app doesn't change with or without it.

@vladamx  We need authToken to signin user to the browser if he/she is not already logged in.

@sketchydroide @chiragsalian Proposal from @vladamx with explanation in https://github.com/Expensify/App/issues/10625#issuecomment-1246475018 and code in https://github.com/Expensify/App/issues/10625#issuecomment-1263852727 first image looks good to me.

🎀👀🎀 C+ reviewed

**Comment by chiragsalian** [comment] 2022-10-04 18:16
Proposal LGTM, i didnt realize i was still assigned here. Unassigning myself since you are working on the issue @sketchydroide 🙂 

Since he's approved it as well assigning issue to @vladamx. Feel free to create the PR.

**Comment by vladamx** [comment] 2022-10-04 18:23
Applied to Upwork. 

PR 5.10.2022

**Comment by arielgreen** [comment] 2022-10-05 05:11
Offer sent

**Comment by arielgreen** [comment] 2022-10-13 02:04
PR still under review

**Comment by mvtglobally** [comment] 2022-10-18 11:22
Issue not reproducible during KI retests. (First week)

**Comment by arielgreen** [comment] 2022-10-20 19:46
<img width="933" alt="image" src="https://user-images.githubusercontent.com/37308300/197043413-3d3a9237-7c47-4fd7-a6b8-cf6e28198a70.png">
Payment due tomorrow.

**Comment by arielgreen** [comment] 2022-10-21 16:44
Paid.

**Closed by arielgreen** 2022-10-21 16:44 UTC
Labels: External, Engineering, Daily, Bug
