### ISSUE TITLE
[HOLD 20935] Account Number accepts 'X' as a number

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22301] opened 2023-07-05 19:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > workspace > Bank Account > Connect Manually.
2. Add the routing number as "074000078" and the account number as "XXXXX6789".
3. Observe that the application does not display an error message for the invalid account number
## Expected Result: 
The account number field should only accept numeric values.
## Actual Result: 
The application does not show an error message when we enter "XXXXX6789" as the account number.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e8c5df42-bb3a-4455-85c6-e6648dc4c96b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688391230054399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-07-05 19:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Account number doesn't show errors when we enter "XXXXX6789"

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/d2de7795edba44a3803f9c10db06ba515a896e69/src/pages/ReimbursementAccount/BankAccountManualStep.js#L40-L43

We are checking the `MASKED_US_ACCOUNT_NUMBER` as well. "XXXXX6789" meets this regex and no error shows.
This is the root cause

### What changes do you think we should make in order to solve the problem?

This `MASKED_US_ACCOUNT_NUMBER` regex is for masked account number and not needed here.
Removing it is a fine solution

```
        if (!values.accountNumber || !CONST.BANK_ACCOUNT.REGEX.US_ACCOUNT_NUMBER.test(values.accountNumber.trim())) {
```

This works as expected.


### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2023-07-06 18:04
Asking if this will be resolved with - https://github.com/Expensify/App/issues/21065#issuecomment-1624108002

**Comment by Christinadobrzyn** [comment] 2023-07-06 19:59
Added a hold label to the title while this issue is reviewed by @Santhosh-Sellavel to see if it will be fixed with - https://github.com/Expensify/App/issues/20935#issuecomment-1624115157

**Comment by eh2077** [comment] 2023-07-07 09:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Account Number accepts 'X' as a number. 

### What is the root cause of that problem?

The root cause of this issue is that we accept an account number if 

1. It's not empty and
2. It matches regex [CONST.BANK_ACCOUNT.REGEX.US_ACCOUNT_NUMBER](https://github.com/Expensify/App/blob/bf94b78a60f21bcf39a1d3c865f9fdfad228bedb/src/CONST.js#L226) or [CONST.BANK_ACCOUNT.REGEX.MASKED_US_ACCOUNT_NUMBER](https://github.com/Expensify/App/blob/bf94b78a60f21bcf39a1d3c865f9fdfad228bedb/src/CONST.js#L230)

See

https://github.com/Expensify/App/blob/bf94b78a60f21bcf39a1d3c865f9fdfad228bedb/src/pages/ReimbursementAccount/BankAccountManualStep.js#L40-L44

Regex CONST.BANK_ACCOUNT.REGEX.MASKED_US_ACCOUNT_NUMBER matches input `XXXXX6789` 

```js
/^[X]{0,9}[0-9]{4}$|^[0-9]{6}[X]{4,7}[0-9]{4}$/.test('XXXXX6789') === true
```

So, the invalid account number, `XXXXX6789`, is accepted.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should improve the validation condition

https://github.com/Expensify/App/blob/bf94b78a60f21bcf39a1d3c865f9fdfad228bedb/src/pages/ReimbursementAccount/BankAccountManualStep.js#L40-L44

to avoid accepting invalid account number.

As we can save data in step 2 and the account number is masked with `X` after saving. So, after saving data in Step 2, if you want to go back to previous steps, like step 1, and then continue to step 2 again, then we need to let the form field validation pass the account number marked by `X`. 

The account number is marked by rule described here

https://github.com/Expensify/App/blob/bf94b78a60f21bcf39a1d3c865f9fdfad228bedb/src/CONST.js#L228-L230

To achieve it, we can improve the validation to 

```js
const accountNumber = values.accountNumber && values.accountNumber.trim();
if (
    !accountNumber ||
    (
        // Check if the account number is saved and marked by the backend
        accountNumber === this.props.getDefaultStateForField('accountNumber', '')
            // Validate saved account number marked by X
            ? !CONST.BANK_ACCOUNT.REGEX.MASKED_US_ACCOUNT_NUMBER.test(accountNumber)
            // Validate user input account number
            : !CONST.BANK_ACCOUNT.REGEX.US_ACCOUNT_NUMBER.test(accountNumber)
    )
) {
    errorFields.accountNumber = 'bankAccount.error.accountNumber';
```

See demo video

<details>
  <summary>Click to see demo video</summary>

  https://github.com/Expensify/App/assets/117511920/c21bd0c7-c4e7-4381-b1c4-6a8ec0aa4ed9
</details>

### What alternative solutions did you explore? (Optional)

N/A

**Comment by Christinadobrzyn** [comment] 2023-07-07 21:34
Monitoring - https://github.com/Expensify/App/issues/20935#issuecomment-1624115157

**Comment by Christinadobrzyn** [comment] 2023-07-10 20:52
Monitoring - https://github.com/Expensify/App/issues/20935#issuecomment-1624115157

**Comment by dylanexpensify** [comment] 2023-07-11 09:57
closing after discussion [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1689022835735929)!

**Closed by dylanexpensify** 2023-07-11 09:57 UTC
Labels: Daily, Bug

**Comment by eh2077** [comment] 2023-07-11 10:02
Hey @dylanexpensify The slack discussion link is not public accessible. Can you share a short summary about the discussion to decide to close this issue? Thank you!
