### ISSUE TITLE
[$500] Search - Delayed Removal of Loader When Removing a Character from the Search Field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31800] opened 2023-11-23 21:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to the Search
2. Enter a character and remove it
3. Notice the loader is not immediately hiding with the removing character, taking 3 to 4 seconds to disappear

## Expected Result:
When removing a character, the loader should be promptly removed with it because the data is already loaded

## Actual Result:
After removing the character, the loader is eventually removed, but there is a noticeable delay of 3 to 4 seconds before it disappears, creating the impression that data is still loading/searching

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b8ea475e-1655-47cf-a44b-4732e515b51d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141bb6ce1d327d478</li>
        <li>Upwork Job ID: 1727796034918838272</li>
        <li>Last Price Increase: 2023-11-30</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27910413</li>
<li>paultsimura | Contributor | 27910414</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-11-23 21:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Delayed Removal of Loader When Removing a Character from the Search Field
### What is the root cause of that problem?
Normally, whenever there is a change of `searchInput` it will call `Report.searchInServer` that queries the server and set the loading indicator state on until it gets back the data from the server, so in empty input it is also sending query and not removing the loading indicator. 
### What changes do you think we should make in order to solve the problem?

We should not call search in server when the search input is empty and set the loading indicator off immediately. 
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-11-24 02:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Delayed Removal of Loader When Removing a Character from the Search Field
This problem happen in many pages, we need to fix all
### What is the root cause of that problem?
When we update search input, we will set IS_SEARCHING_FOR_REPORTS is true in optimistic data and reset it to false in successData and failureData. So even though we clear input, IS_SEARCHING_FOR_REPORTS is only set to false when API is done.

### What changes do you think we should make in order to solve the problem?
This problem happen in NewChatPage, SearchPage, MoneyRequestParticipantsSelector, TaskShareDestinationSelectorModal,...
In all these pages, we need add condition to hide the loading spinner if the search value is empty.

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2023-11-24 08:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When quickly typing and removing a character in search, the spinner is still loading.

### What is the root cause of that problem?
We show the spinner when `ONYXKEYS.IS_SEARCHING_FOR_REPORTS === true`. This value is not set to `false` until the API request is completed.

### What changes do you think we should make in order to solve the problem?
First of all, it's worth noticing that such a behavior happens in all the pages where we currently use `Report.searchInServer()`. And in all the pages, we use the same logic:

```js
if (text.length) {
    Report.searchInServer(text);
}
```

To fix this behavior, we should update `Report.searchInServer()` in the following way:
- Set `ONYXKEYS.IS_SEARCHING_FOR_REPORTS` to `false` when the input is **blank**
- Check the input to be blank so we don't show the spinner when entering a bunch of empty spaces

```js
if (isNetworkOffline || !searchInput.trim().length) {
    Onyx.set(ONYXKEYS.IS_SEARCHING_FOR_REPORTS, false);
    return;
}
```

https://github.com/Expensify/App/blob/39d2d98b3b89b69da36cc5e00776f5b7aa17d03c/src/libs/actions/Report.js#L2496-L2507

We should also remove all the `if (text.length) ...` checks from the pages where we use the `Report.searchInServer()`, as this will be handled inside the function.

### What alternative solutions did you explore? (Optional)

**Comment by faisal-ibrahim** [comment] 2023-11-24 12:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue at hand (Search - Delayed Removal of Loader When Removing a Character from the Search Field #31800) involves the delayed removal of a loader when search input emptied from the search field. 

### What is the root cause of that problem?
The root cause of the problem lies in the asynchronous nature of the API call triggered by the onChangeText function. When the user quickly emptied the input before the API call completes, the loader is not dismissed as expected.

```
onChangeText(searchValue = '') { 
     if (searchValue.length) { 
         Report.searchInServer(searchValue); 
     } 
  
     this.setState({searchValue}, this.debouncedUpdateOptions); 
 } 
```


### What changes do you think we should make in order to solve the problem?
The quick workaround involves updating the `Report.searchInServer` function to check if the input value is empty before initiating the API call. If the input is empty, the loader display from the previous API call is immediately removed. 

```
function searchInServer(searchInput) { 
    if (isNetworkOffline || searchInput.trim() === '') { 
        Onyx.set(ONYXKEYS.IS_SEARCHING_FOR_REPORTS, false); 
        return; 
    }

    // Set the loading state right away
    Onyx.set(ONYXKEYS.IS_SEARCHING_FOR_REPORTS, true); 
    debouncedSearchInServer(searchInput); 
}
```
We also need to eliminate the string length/empty checks from the calls to the Report.searchInServer method.
For example:
```
 onChangeText(searchValue = '') { 
     Report.searchInServer(searchValue); 
     this.setState({searchValue}, this.debouncedUpdateOptions); 
 } 
```
This solution improves code readability and maintainability.

### What alternative solutions did you explore? (Optional)
An alternative solution is proposed to optimize the process further by maintaining a hashmap of already searched terms. This avoids unnecessary API calls when the user repeats a search term, enhancing performance.
```
...
const alreadySearchedTerms = new Set();


....
function searchInServer(searchInput) { 
    if (isNetworkOffline || alreadySearchedTerms.has(searchInput.trim())) { 
        Onyx.set(ONYXKEYS.IS_SEARCHING_FOR_REPORTS, false); 
        return; 
    }

    // Set the loading state right away
    Onyx.set(ONYXKEYS.IS_SEARCHING_FOR_REPORTS, true); 
    debouncedSearchInServer(searchInput); 
}
```
This alternative solution minimizes API calls by checking if the search term has been used before, providing a more efficient search mechanism. The hashmap is reset on page load to ensure the latest data is considered.

**Note**: This approach introduces a caching mechanism. A potential drawback of caching is that it may not always provide the most up-to-date data during the search period. However, if immediate data updates are crucial, then additional API call should also be triggered when the search input is empty to fetch the latest information.

**Comment by faisal-ibrahim** [comment] 2023-11-24 13:44
Contributor details
Your Expensify account email: faisal.im048@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/faisalibrahim

**Comment by JmillsExpensify** [comment] 2023-11-24 19:51
@jjcoffee thoughts on the proposals so far?

**Comment by jjcoffee** [comment] 2023-11-27 10:22
Thanks for the proposals everyone! All of the proposed solutions here are workable, but I personally prefer @paultsimura's [proposal](https://github.com/Expensify/App/issues/31800#issuecomment-1825335503) as it makes the code more DRY by moving the repeated uses of `if (searchValue.length)` to a single use within `searchInServer`. I also like the extra bit of handling of multiple empty spaces.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by DylanDylann** [comment] 2023-11-27 10:52
@jjcoffee The meaning of IS_SEARCHING_FOR_REPORTS field is checking whether if search API is executing or not. So I see that @paultsimura's will make logic become confusing. We shouldn't reset ONYXKEYS.IS_SEARCHING_FOR_REPORTS to false while the API is executing. 

cc @Gonals

**Comment by DylanDylann** [comment] 2023-11-27 12:17
It's up to our expected. I think `IS_SEARCHING_FOR_REPORTS` is global variable, we should keep the meaning of this field as it's name.

**Comment by JmillsExpensify** [comment] 2023-11-29 00:26
Working through proposals

**Comment by jjcoffee** [comment] 2023-11-30 14:01
Just waiting on @Gonals to assign @paultsimura per [this comment](https://github.com/Expensify/App/issues/31800#issuecomment-1827550402).

**Comment by paultsimura** [comment] 2023-12-01 18:16
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/32371

**Comment by jjcoffee** [comment] 2023-12-07 16:21
Had the some on a couple other issues on the same deploy so there must have been something up with the automation! @JmillsExpensify Could you add the `Awaiting Payment` label and update the title? Thanks!

**Comment by JmillsExpensify** [comment] 2023-12-13 05:19
Payment summary:

 - Issue reporter: N/A
 - Contributor: $500 @paultsimura
 - Contributor+: $500 @jjcoffee

**Comment by JmillsExpensify** [comment] 2023-12-13 16:34
No comments on the above, so I'm going to issue payments now.

**Comment by JmillsExpensify** [comment] 2023-12-13 16:38
All contributors paid, though @jjcoffee would you mind completing the BZ checklist first so we can close this out?

**Comment by jjcoffee** [comment] 2023-12-13 17:23
- The PR that introduced the bug has been identified. Link to the PR: **N/A - this is how `Report.searchInServer` has always worked**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to the Search
2. Enter a character and remove it
3. Verify that the loading spinner is removed almost immediately
4. Enter a set of empty spaces
5. Verify that the loader does not appear 

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2023-12-13 17:23
@JmillsExpensify Thanks for processing the payment, and apologies for missing the checklist. Done now!

**Comment by JmillsExpensify** [comment] 2023-12-14 17:29
Thank you! All looks good. I'll get that regression test added.

**Closed** 2023-12-14 17:30 UTC
Labels: Reviewing, External, Weekly, Bug
