### ISSUE TITLE
[HOLD for payment 2023-11-22] [Payment due: 17 Nov] [$500] Dev: amount does not appears after split bill in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28330] opened 2023-09-27 16:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go offline
2. Click on FAB icon and select request money
3. Enter amount and select users for split bill
4. Split the money which will redirects to report screen
5. Check amount

## Expected Result:
Only owes: appears

## Actual Result:
Should show amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Dev 1.3.74-2
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9acbaf3e-849d-46c8-8762-3d34507de548

https://github.com/Expensify/App/assets/93399543/21f0e468-6e71-49f9-a034-7ceb7166fb69

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695720688727649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by studentofcoding** [comment] 2023-09-27 21:04
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Dev: amount does not appears after split bill in offline mode

## What is the root cause of that problem?

On `MoneyRequestPreview` component, specifically in the `getDisplayAmountText` function. We didn't ensure the function correctly retrieves and displays the split bill amounts even when the device is offline.

Here is the relevant code block:
```
    const getDisplayAmountText = () => {
        if (isDistanceRequest) {
            return CurrencyUtils.convertToDisplayString(TransactionUtils.getAmount(props.transaction), props.transaction.currency);
        }

        if (isScanning) {
            return props.translate('iou.receiptScanning');
        }

        return CurrencyUtils.convertToDisplayString(requestAmount, requestCurrency);
    };
```

## What changes do you think we should make in order to solve the problem?

We should ensure that this function can correctly retrieve and display the split bill amounts even when the device is offline, with checking if requestAmount and requestCurrency are not null or undefined.

```
const getDisplayAmountText = () => {
    if (isDistanceRequest) {
        return CurrencyUtils.convertToDisplayString(TransactionUtils.getAmount(props.transaction), props.transaction.currency);
    }

    if (isScanning) {
        return props.translate('iou.receiptScanning');
    }

    // Check if requestAmount and requestCurrency are not null or undefined
    if (requestAmount && requestCurrency) {
        return CurrencyUtils.convertToDisplayString(requestAmount, requestCurrency);
    }
};
```

## What alternative solutions did you explore? (Optional)

None

## Result

https://github.com/Expensify/App/assets/20473526/c66a472f-edc0-4612-ae36-b8ab8f6f4e94

**Comment by sophiepintoraetz** [comment] 2023-10-03 06:08
Not overdue - just waiting on proposal review!

**Comment by sophiepintoraetz** [comment] 2023-10-04 06:23
Bump @situchan

**Comment by sophiepintoraetz** [comment] 2023-10-07 04:46
Hey @adelekennedy, can you please baby sit this issue for me while I'm OOO till the 17 Oct? I've asked for another C+ volunteer [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1696653955363279) to review the issue, as it seems like @situchan can't get to this.

**Comment by situchan** [comment] 2023-10-07 04:57
I will provide update by Monday

**Comment by adelekennedy** [comment] 2023-10-09 15:41
@situchan will provide update today!

**Comment by situchan** [comment] 2023-10-11 12:26
@tienifr's proposal looks promising. Will test and approve shortly

**Comment by adelekennedy** [comment] 2023-10-16 19:26
@situchan were you able to test @tienifr proposal? Any updates on a selection?

**Comment by adelekennedy** [comment] 2023-10-18 16:28
@situchan and update here?

**Comment by situchan** [comment] 2023-10-18 16:44
@tienifr's [proposal](https://github.com/Expensify/App/issues/28330#issuecomment-1739016393) looks good to me.
Note: this happens only when split bill with new user and Onyx has `report_undefined` report
🎀 👀 🎀 C+ reviewed

**Comment by sophiepintoraetz** [comment] 2023-10-18 19:32
Thank you @adelekennedy for looking after this!

**Comment by situchan** [comment] 2023-10-20 03:21
I am also not able to reproduce on latest main.

**Comment by sophiepintoraetz** [comment] 2023-10-23 21:25
All right, if the issue is no longer reproducible, I am closing this out (feel free to reopen it if it crops up again!)

Thank you @tienifr and @situchan!

**Comment by sophiepintoraetz** [comment] 2023-10-30 03:27
Hi @tienifr - to be clear, the issue you linked was an exceptional circumstance (personal reasons) so not particularly relevant here. You will remember that it is at our discretion whether or not we decide to compensate. Usually, I would agree with you, but in this instance, @situchan held up the review which could have had this issue implemented in a timely manner. I personally don't think this is eligible for compensation on that basis.

**Comment by situchan** [comment] 2023-10-30 09:33
If same root cause, makes sense to fix it here.
@johnmlee101 will decide whether to continue PR or not

**Comment by johnmlee101** [comment] 2023-10-30 15:56
To clarify, the fix is the exact same as previously?

**Comment by sophiepintoraetz** [comment] 2023-11-15 19:48
Yes, payment will be subject to the usual 7 day regression period, so we're still a couple of days out.

**Comment by sophiepintoraetz** [comment] 2023-11-22 03:56
Offers sent - @situchan - I'll complete payment for yours once you've done the checklist, thank you!

**Comment by situchan** [comment] 2023-11-27 15:07
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/24639
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/24639/files#r1406299214
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Invite new member to WS
2. Go offline
3. Press FAB > Request money > Manual
4. Enter amount > Select invited member > Split
5. Verify that split request is created and amount shows in split preview

**Comment by sophiepintoraetz** [comment] 2023-11-28 04:36
All paid here.

**Closed by sophiepintoraetz** 2023-11-28 04:36 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
