### ISSUE TITLE
Android - Expensify Classic opens after relaunching when New Expensify is last opened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52664] opened 2024-11-16 14:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+zm51@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch hybrid app
2. Sign in
3. If app lands on Expensify Classic, go to Menu > Try New Expensify
4. If app lands on New Expensify, go to Settings > Switch to Expensify Classic
5. On Expensify Classic, open Menu > Try New Expensify to go back to New Expensify
5. Kill app
6. Relaunch app

## Expected Result:
New Expensify will open on hybrid app after relaunching app because New Expensify is the last opened section

## Actual Result:
Expensify Classic opens on hybrid app after relaunching app when New Expensify is the last opened section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>

https://github.com/user-attachments/assets/c1a23a58-0b17-4fdb-ac8e-55dfa0af9e13

  <summary>Add any screenshot/video evidence</summary>

   

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment] 2024-11-18 15:41
Working on getting access to the Android beta for OldApp

**Comment by arosiclair** [comment] 2024-11-18 16:10
Okay I reproduced in **v9.0.63-3**

**Comment by arosiclair** [comment] 2024-11-18 16:19
Looks like the root of this problem is that opening the new experience does _not_ update `tryNewDot.classicRedirect.dismissed` to `false`. I'm not sure why yet.

**Comment by arosiclair** [comment] 2024-11-18 16:27
Okay we already merged a PR to fix it! This was caused by mixed up params that skipped updating the `tryNewDot` NVP from https://github.com/Expensify/Mobile-Expensify/pull/13257 and should be fixed with https://github.com/Expensify/Mobile-Expensify/pull/13286.

**Closed by arosiclair** 2024-11-18 16:27 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
