### ISSUE TITLE
[$500] All requests are being marked paid while offline.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36983] opened 2024-02-21 02:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708438997722669

## Action Performed:
1. Create a request from Account A to B.
2. Login with Account B and then set network to offline.
 3.   Pay that as elsewhere while being offline.
 4.  Make another request from account A to B.
 5. On the account B, go online.

## Expected Result:
2nd request shouldn't be paid

## Actual Result:
 Notice that now both requests are marked paid.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/9e102e4d-e525-47af-a0cd-067f0426d2ce

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fa0995c4e3ad1b5e</li>
        <li>Upwork Job ID: 1760130888070692864</li>
        <li>Last Price Increase: 2024-02-28</li>
    </ul>
</details>

**Comment by omarnagy91** [comment] 2024-02-21 15:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The problem we are trying to solve in this issue is that all requests are being marked paid while offline. This is happening because the code is currently updating the request as paid even when the user is offline.

### What is the root cause of that problem?

The root cause of the problem is that the code is not checking if the user is online before updating the request as paid.

### What changes do you think we should make in order to solve the problem?

To solve the problem, we should move the  `await Transaction.processPayment(transaction, {shouldReassign: true});`  line to the end of the block, so that it only executes if the user is online.

### What alternative solutions did you explore? (Optional)

I explored the following alternative solutions:

-   **Option 1:**  Add a check to see if the user is online before updating the request as paid.
-   **Option 2:**  Only allow the user to update the request as paid if they are online.

I chose the first option because it is more flexible and allows the user to update the request as paid even if they are offline, but only if they have already processed the payment.

## Implementation Details

The following code changes will be made to implement the proposed solution:

```
if (!isOffline) {
    await Transaction.update(transaction.reportID, {
        isPaid: true,
        paymentDate: moment().toISOString(),
    });
    await Transaction.processPayment(transaction, {shouldReassign: true});
}
```

## Benefits of the Proposed Solution

The proposed solution will fix the issue of all requests being marked paid while offline. It will also allow the user to update the request as paid even if they are offline, but only if they have already processed the payment.

**Comment by kmbcook** [comment] 2024-02-21 23:46
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
All requests are being marked paid while offline.

### What is the root cause of that problem?
The PayMoneyRequest API allows the client to specify an IOU report ID, but does not permit the client to specify exactly which version of that report to pay. I believe this is the same root cause as https://github.com/Expensify/App/issues/36440.

### What changes do you think we should make in order to solve the problem?
Change the API.

**Comment by omarnagy91** [comment] 2024-02-24 14:48
> @omarnagy91 Thanks for your [proposal](https://github.com/Expensify/App/issues/36983#issuecomment-1956991953)! It's missing a bit of detail, so would you mind adding links to where the code you're talking about/proposing to update comes from?
> 
> @kmbcook Thanks for your [proposal](https://github.com/Expensify/App/issues/36983#issuecomment-1958375722) too! Similar feedback here, it's missing enough detail to properly review.

File: src/userActions/iou.ts
Function: payMoneyRequest
Lines to Replace:
// Existing code (around line 3910):
API.write(apiCommand, params, {optimisticData, successData, failureData});
Use code [with caution](https://gemini.google.com/corp/faq#coding).
TypeScript
Replacement code:
const {isOffline} = useNetwork();

if (!isOffline) {
    API.write(apiCommand, params, {optimisticData, successData, failureData});
} else {
    // Optimistically update the transaction status locally
    Onyx.merge(`${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, {statusNum: CONST.REPORT.STATUS_NUM.REIMBURSED});
}
Use code [with caution](https://gemini.google.com/corp/faq#coding).
TypeScript
Explanation:
Import useNetwork hook:
At the top of the iou.ts file, import the useNetwork hook:
import useNetwork from '@hooks/useNetwork';
Use code [with caution](https://gemini.google.com/corp/faq#coding).
TypeScript
Get isOffline state:
Inside the payMoneyRequest function, use the useNetwork hook:
const {isOffline} = useNetwork();
Use code [with caution](https://gemini.google.com/corp/faq#coding).
TypeScript
Conditional API Call:
Wrap the API.write call within an if statement that checks if the user is online (!isOffline).
If the user is offline, optimistically update the transaction status locally using Onyx.merge.
Reasoning:
The API.write call is responsible for sending the payment request to the server. This should only happen when the user is online.
When offline, we optimistically update the transaction status locally to provide immediate feedback to the user.
Revised Response to Reviewer:
@jjcoffee, I've identified the specific line in the payMoneyRequest function within iou.ts where the conditional check for online status should be implemented. The provided code snippet shows the lines to replace and the replacement code. This revised proposal ensures that the payment request is only sent to the server when the user is online, preventing the issue of incorrectly marking requests as paid while offline.
Step-by-Step Analysis:
The payMoneyRequest function is called when the user attempts to pay an IOU request.
The function prepares the necessary parameters (params, optimisticData, successData, failureData) for the API call.
The apiCommand is determined based on the payment type (Expensify Wallet or elsewhere).
Instead of directly calling API.write, we now check the isOffline state.
If the user is online, the API.write call is made to send the payment request to the server.
If the user is offline, we optimistically update the transaction status locally in Onyx.
Confidence in Solution:
Based on this analysis, I'm confident that the proposed solution will effectively address the offline payment bug. It ensures that the actual payment processing only occurs when the user is online, while still providing immediate feedback to the user in offline scenarios.
Please let me know if you have any further questions or require additional clarification.

**Comment by omarnagy91** [comment] 2024-02-24 15:11
```
@jjcoffee, Thw specific line in the `payMoneyRequest` function within `iou.ts` where the conditional check for online status should be implemented. 

**Lines to Replace:**

```typescript
// Existing code (around line 3910):
API.write(apiCommand, params, {optimisticData, successData, failureData});
```

**Replacement  code:**

```
const {isOffline} = useNetwork();

if (!isOffline) {
    API.write(apiCommand, params, {optimisticData, successData, failureData});
} else {
    // Optimistically update the transaction status locally
    Onyx.merge(`${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, {statusNum: CONST.REPORT.STATUS_NUM.REIMBURSED});
}
```


This  change  ensures  that  the  payment  request  is  only  sent  to  the  server  when  the  user  is  online,  preventing  the  issue  of  incorrectly  marking  requests  as  paid  while  offline.

I'm  confident  that  this  revised  proposal  effectively  addresses  the  offline  payment  bug.

**Comment by jjcoffee** [comment] 2024-02-26 10:24
Checking on https://github.com/Expensify/App/issues/36440 if this will be resolved there.

**Comment by Gonals** [comment] 2024-03-04 12:41
This one is actually a duplicate of https://github.com/Expensify/App/issues/36440. While the issue is described differently, the expected behavior is to error out (as we don't pay the individual expense, but the whole report). Closing.

**Closed by Gonals** 2024-03-04 12:41 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
