### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Room - Unable to create a public room if I don't select a workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34647] opened 2024-01-17 14:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing** https://github.com/Expensify/App/pull/33715

## Action Performed:
1. Log in with a new expensifail account
2. From the initial open FAB menu, select Start chat
3. Click on the "Room" button
4. Click on the "Learn More" button
5. Create a new workspace
6. Go to FAB - Start chat - Room
7. Type in "123" as the room name (don't select a workspace)
8. Create the room

## Expected Result:
I should be receiving an error message that I must select a workspace before creating a room.

## Actual Result:
Unable to create a public room. "Unexpected error creating this chat, please try again laterPolicy rooms can not be created on personal policies".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cfe2d1f7-867b-40dd-af76-d9920240f361

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014dfbb95a9411a4d8</li>
        <li>Upwork Job ID: 1747630089482182656</li>
        <li>Last Price Increase: 2024-01-17</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 28106888</li>
<li>s-alves10 | Contributor | 28107483</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by ikevin127** [comment] 2024-01-17 14:44
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Unable to create a public room. "Unexpected error creating this chat, please try again laterPolicy rooms can not be created on personal policies".

## What is the root cause of that problem?

There's no workspace validation present when creating a room.

## What changes do you think we should make in order to solve the problem?

Add workspace validation for when submitting the form so that user cannot create the room if no workspace is present.

**Comment by s-alves10** [comment] 2024-01-17 14:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Can create a public room without selecting a workspace, but results in errors. When trying to create a public room, error message to select a workspace should be shown to the user

### What is the root cause of that problem?

We initialize the `policyID` here
https://github.com/Expensify/App/blob/3033f999751cf51e89727aa6993a05b298710023/src/pages/workspace/WorkspaceNewRoomPage.js#L103

We also initialize the public workspace options here
https://github.com/Expensify/App/blob/3033f999751cf51e89727aa6993a05b298710023/src/pages/workspace/WorkspaceNewRoomPage.js#L199-L207

The problem is that there are cases that `activePolicyID` isn't included in public workspaces. The workspace options include only public workspaces, but `activePolicyID` indicates private workspace. So the validation doesn't fails, but it looks like workspace field is empty

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to clear the `policyID` when it isn't a public workspace

Update 
https://github.com/Expensify/App/blob/3033f999751cf51e89727aa6993a05b298710023/src/pages/workspace/WorkspaceNewRoomPage.js#L103
to
```
    const workspaceOptions = useMemo(
        () =>
            _.map(PolicyUtils.getActivePolicies(props.policies), (policy) => ({
                label: policy.name,
                key: policy.id,
                value: policy.id,
            })),
        [props.policies],
    );
    const [policyID, setPolicyID] = useState(() => {
        if (workspaceOptions.some(option => option.value === props.activePolicyID)) {
            return props.activePolicyID;
        }
        return '';
    });
```
Update
https://github.com/Expensify/App/blob/3033f999751cf51e89727aa6993a05b298710023/src/pages/workspace/WorkspaceNewRoomPage.js#L145-L150
to
```
    useEffect(() => {
        if (policyID) {
            return;
        }
        if (workspaceOptions.some(opt => opt.value === props.activePolicyID)) {
            setPolicyID(props.activePolicyID);
        } else {
            setPolicyID('');
        }
    }, [props.activePolicyID, policyID, workspaceOptions]);
```

This works as expected
<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/f8905ee3-8462-463e-9000-ccae4391d8d7

</details>

### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment] 2024-01-17 21:58
So I haven't thoroughly reviewed all the proposals yet, but at a high level I'm proposing a twofold solution:

1. (front-end) Don't let people create rooms without filling out the workspace field. Already, it looks like the workspace field appears as empty if the activePolicyID is a personal policy that isn't in NewDot yet.
2. (back-end) Given that someone's activePolicyID is a personal policy, and they aren't a member of a group policy yet; when they create their first workspace via NewDot, update that to be their activePolicyID.

**Comment by roryabraham** [comment] 2024-01-17 22:01
For `1`, it looks like most of the proposals here would work, so I'm going to select the first that I think is sufficient.

**Comment by ikevin127** [comment] 2024-01-17 22:56
https://github.com/Expensify/App/pull/34691 ready for review!

**Comment by s-alves10** [comment] 2024-01-18 00:29
@roryabraham 

I am so confused about how the selection process goes here. It looks like you didn't check the edit history of proposals. The first proposal was wrong and so I submitted a proposal with correct RCA. The former proposals was updated later. Of course, I would respect the decision of C+/internal team, but I want you to check the edit history at least.

We have similar discussions recently. Please check https://expensify.slack.com/archives/C01GTK53T8Q/p1703083893742679
@ikevin127 you know about that discussion, I think

**Comment by roryabraham** [comment] 2024-01-18 06:20
Whoa, my mistake. You're right that I didn't check the edit history of the proposals in this case. I apologize for that and will try to be more cognizant of it in the future for the sake of fairness. However, the edit history for a comment does not show precise timestamps, so all I can see is that @s-alves10' proposal and @ikevin127's first edit (the one with major substantive changes), came in 14 hours ago. It looks like like @mkhutornyi might have been first to post the root cause.

(I know I could technically use the GitHub API to figure out which proposal came first, but as a reviewer I feel like I shouldn't have to do that).

I'm not sure what our official guidelines are here, but I'm going to bring a suggestion to slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1705558552266309?thread_ts=1703083893.742679&cid=C01GTK53T8Q

**Comment by roryabraham** [comment] 2024-01-18 06:48
Thanks for the tip @mkhutornyi 👍🏼 

@ikevin127 reading [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1703083893742679), it's clear that you're aware of potential fairness problems with so-called **speedrun proposals**, but in this instance it seems clear that's exactly what you've done, and that you updated your proposal to include the RCA from later proposals. To me, this feels like a Rule #2 violation. In the future, if you update a proposal based on the content of another proposal (as opposed to feedback from a reviewer), please call that out clearly.

Let's also continue to discuss in slack to try and address the underlying fairness problem and to discourage **speedrun proposals** to give everyone a more even playing field to take the time they need to post quality proposals, and also to discourage plagiarism.

I know the "official rules" are still a bit mirky here, but I'm going to make a judgement call on what feels most fair to me in this case and reassign the issue. I hope you understand @ikevin127, but if you want to talk about it I'm happy to do that. I want to do what I can to make this community as open, inclusive, and fair as possible.

> we need to select another if this policy isn't enabled. That will make consistent when this policy is enable or not and we don't need to validate for the workspace field.

This is actually a great point, and not one I realized before. The first proposal that accomplishes this behavior is [this one](https://github.com/Expensify/App/issues/34647#issuecomment-1895989896) from @s-alves10.

**Comment by trjExpensify** [comment] 2024-01-18 19:49
>the proposal from @s-alves10 is set the activePolicyID to empty

I'm a bit confused by this, I don't think we should be someone's activePolicyID. It has pretty wide consequences across OldDot (i.e where you forwarded receipts import, where new expenses you create default to etc). 

I thought the solution here would be something like: 

1. If the activePolicyID is a group workspace, show it in the `Workspace` field
2. If the activePolicyID is a personal workspace (where rooms are not supported), leave the `Workspace` field blank
3. In the case of (2), if they click `Create room` without choosing a group workspace from the select list, show an error telling the user they need to choose a workspace first. 

Note on #3: They'll always have a group workspace type to select in #3, because if they don't, they won't see the room creation page anyway: 

<img width="385" alt="image" src="https://github.com/Expensify/App/assets/16232057/71221271-2a75-4cb5-8548-8b4001c6d203">

**Comment by s-alves10** [comment] 2024-01-18 20:25
@trjExpensify 

I'm suggesting to set `policyID`(not `activePolicyID`) to empty when it's not an active workspace. What this means is exactly what you want [here](https://github.com/Expensify/App/issues/34647#issuecomment-1899108698)

cc @mkhutornyi

**Comment by roryabraham** [comment] 2024-01-24 03:15
@thesahindia let me know when you think you'll be able to review https://github.com/Expensify/App/pull/34489

**Comment by s-alves10** [comment] 2024-01-24 09:46
@thesahindia PR is ready for review https://github.com/Expensify/App/pull/34796

**Comment by trjExpensify** [comment] 2024-02-09 10:19
👋 checklist time here!

**Comment by trjExpensify** [comment] 2024-02-12 12:10
Same Melv, awaiting the checklist!

**Comment by trjExpensify** [comment] 2024-02-14 22:09
Don't forget about the rest of the checklist? :) 

As for the regression test, looks like we're going to be adding one already, so I've suggested a modification to it in that GH.

**Comment by trjExpensify** [comment] 2024-02-19 12:45
Regression test sorted, @thesahindia you need to complete the rest of the checklist so we can issue payments and close this one out.

**Comment by trjExpensify** [comment] 2024-02-22 11:05
Thanks! Payment summary as follows: 

- @thesahindia $500 for the C+ review (to request on ND). 
- @s-alves10 $500 for the fix (Paid). 

Closing this out!

**Closed by trjExpensify** 2024-02-22 11:05 UTC
Labels: External, Daily, Awaiting Payment, Bug
