### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Deeplinks - Inconsistency in Error pages content

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33351] opened 2023-12-20 12:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/a/hello

## Expected Result:
A page not found should be displayed and "Oops, this page cannot be found" should be visible

## Actual Result:
Inconsistency in Error pages content. "Oops, this page cannot be found" is not present when navigate to non-existing profile via ink

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/71b4320d-1509-4f15-a8bd-c13f37016a5d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017aa5d48046de3a69</li>
        <li>Upwork Job ID: 1737457309416439808</li>
        <li>Last Price Increase: 2024-01-03</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28090559</li>
<li>dukenv0307 | Contributor | 28093492</li>
</ul></li>
    </ul>
</details>

**Comment by Berndy** [comment] 2023-12-20 13:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The not found page is inconsistent with other pages, displaying "Hmm... it's not here" instead of 'Oops, this page cannot be found'

### What is the root cause of that problem?
We use the wrong static text in the blocking view.

### What changes do you think we should make in order to solve the problem?
We exchange the `notFound.notHere` static text for the `notFound.pageNotFound` static text

https://github.com/Expensify/App/blob/d4c3f2f08f8e4b3869598b2cb1ced243cb6adfbd/src/pages/ProfilePage.js#L271

### What alternative solutions did you explore? (Optional)

**Comment by Berndy** [comment] 2023-12-20 13:30
Actually, @kbecciv could you elaborate if this issue is about an entirely missing error page or just inconsistent text? I was a bit confused by the attached video, as it does not show any navigation to your example profile. For now I went with your explanation and what I saw when reproducing, but might want to submit a different proposal if i misunderstood the issue.

**Comment by MrAdeelBaig** [comment] 2023-12-20 19:38
What is the main issue?
As stated by @Berndy, the test is not showing correctly because of the text is wrong, and the other issue is that deep linking is not implemented properly, when user navigates to a link that isn't existing any more, then it should show the error page with the text visible. Am i right?

**Comment by MrAdeelBaig** [comment] 2023-12-21 08:35
The project isn't cloning.

**Comment by burczu** [comment] 2023-12-21 09:40
@kbecciv Could you please update the video you've attached? It seems not related to this issue. Thanks

**Comment by burczu** [comment] 2023-12-22 13:34
Hey @dylanexpensify! I'll be OOO till January 6th, and right after that I'm leaving the C+ role and joining Waves. Could you assign another C+ engineer to handle this issue from now on? Thanks.

**Comment by situchan** [comment] 2023-12-22 14:51
I can take over

**Comment by situchan** [comment] 2023-12-22 14:52
@dylanexpensify as https://github.com/Expensify/App/issues/32905 was closed, should this be closed as well?

**Comment by kbecciv** [comment] 2023-12-29 21:06
@burczu Added correct video, sorry for inconvenience.

**Comment by mvtglobally** [comment] 2024-01-03 05:50
Issue not reproducible during KI retests. (First week)

**Comment by dylanexpensify** [comment] 2024-01-04 10:09
Sorry team, was ooo! @burczu mind confirming next steps here when back?

**Comment by situchan** [comment] 2024-01-04 10:12
@dylanexpensify please check https://github.com/Expensify/App/issues/33351#issuecomment-1867695928.
Assign me if you let me take over.

**Comment by situchan** [comment] 2024-01-09 12:31
I agree to wrap profile page with `FullpageNotFoundView` to be consistent with other not found pages.
@dukenv0307 proposed first [here](https://github.com/Expensify/App/issues/32905#issuecomment-1851780495)
🎀 👀 🎀 C+ reviewed

**Comment by dylanexpensify** [comment] 2024-01-17 09:34
@situchan bump

**Comment by dylanexpensify** [comment] 2024-01-23 13:21
bump @situchan

**Comment by situchan** [comment] 2024-01-23 13:23
PR is in review. completing today

**Comment by dylanexpensify** [comment] 2024-01-29 11:51
Nice, seems we haven't merged yet, let's get that done today! 🎉

**Comment by dylanexpensify** [comment] 2024-02-07 10:31
Hmmm @situchan what's left here? cc @dukenv0307

**Comment by situchan** [comment] 2024-02-07 10:36
resolving constant conflicts. hopefully merge today/tomorrow

**Comment by dylanexpensify** [comment] 2024-02-13 20:21
nice, @situchan seems still open - what's our thoughts?

**Comment by situchan** [comment] 2024-02-13 20:22
conflict resolved 2 hrs go. So planning to complete review by tomorrow

**Comment by dylanexpensify** [comment] 2024-02-21 10:44
Seems still not merged? @situchan @dukenv0307 update please? 🙇‍♂️

**Comment by situchan** [comment] 2024-02-21 13:10
I requested changes

**Comment by dylanexpensify** [comment] 2024-02-28 08:59
@dukenv0307 where we at my man?

**Comment by dylanexpensify** [comment] 2024-03-06 11:00
Tomorrow is payday!

**Comment by dylanexpensify** [comment] 2024-03-11 09:40
Payment Summary:

Contributor: @dukenv0307 $500
Contributor+: @situchan $500

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-03-11 09:42
@situchan can you complete checklist?

Payments have been issued.

**Comment by situchan** [comment] 2024-03-11 09:46
There was no regression. This was inconsistent UX issue.
As this was caught by QA team, we can skip regression test.

**Comment by dylanexpensify** [comment] 2024-03-13 10:10
ty!

**Closed by dylanexpensify** 2024-03-13 10:10 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
