### ISSUE TITLE
Public room - new messages button is displayed for anon user and it can not be dismissed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38870] opened 2024-03-23 14:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4444224
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to any public room as anonymous user, e. g. https://staging.new.expensify.com/r/3504895439653267

## Expected Result:
New messages button should not appear as there is no new messages.

## Actual Result:
New messages button is always shown for anon user and it can not be dismissed.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/16106f56-ebff-42d8-b984-772b8b842af8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-03-23 14:04
We think that this bug might be related to #vip-vsb

**Comment by rlinoz** [comment] 2024-03-25 13:04
This is probably being caused by this PR https://github.com/Expensify/App/pull/30269

**Comment by rlinoz** [comment] 2024-03-25 14:09
Maybe @perunt or @roryabraham can help?

**Comment by yuwenmemon** [comment] 2024-03-25 21:21
Closing in favor of https://github.com/Expensify/App/issues/38848

**Closed by yuwenmemon** 2024-03-25 21:21 UTC
Labels: DeployBlockerCash, Engineering, Hourly
