### ISSUE TITLE
[$250] Report - Added content is lost after editing in offline mode and refreshing the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40455] opened 2024-04-18 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/tests/view/4494531)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Send a message in any report
2. Apply offline mode
3. Edit the sent message
4. Refresh the page
5. Change network mode to online

## Expected Result:
Added comment while editing in offline mode should persist

## Actual Result:
Add comment while editing in offline mode is lost

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/02e8991c-0906-45e4-95f7-0a16a148611b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf8721625590c5d0</li>
        <li>Upwork Job ID: 1783009829966831616</li>
        <li>Last Price Increase: 2024-04-24</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-18 14:17
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-18 14:19
We think that this bug might be related to #vip-vsp

**Comment by JmillsExpensify** [comment] 2024-04-24 05:47
Yikes, this doesn't seem good. I agree that it's #vip-vsb so I will add it to the project. Also going to start with external since that'll be picked up faster.

**Comment by Pujan92** [comment] 2024-04-26 16:34
@lanitochka17 I am not able to reproduce it, can you plz check and confirm

https://github.com/Expensify/App/assets/14358475/2169444d-1ce7-4a1d-ab9a-ad098d3515b3

**Comment by lanitochka17** [comment] 2024-04-26 17:07
@Pujan92 Tester is still  able to reproduce this issue 


https://github.com/Expensify/App/assets/78819774/20be07db-c554-44ba-97ba-c0fac597c80e

**Comment by bernhardoj** [comment] 2024-04-29 08:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The edited comment is discarded when refreshing the page while offline.

### What is the root cause of that problem?
When we do an API request while offline, we will save it to the `networkRequestQueue` Onyx so we can process it when we are back online. 
https://github.com/Expensify/App/blob/777d2188755f12d47474a2b74962ef56fefecbb4/src/libs/actions/PersistedRequests.ts#L25-L30

However, the queue is never saved because we pass the same instance of the array. You can see in the log that the `hasChanged` is `false`.
<img width="579" alt="Screenshot 2024-04-29 at 16 06 35" src="https://github.com/Expensify/App/assets/50919443/1291d9f9-1668-4f84-b684-1d20a014990d">

So, when we refresh the page, the edit request will never be processed, and the OpenReport/ReconnectApp request will return the message data from the BE which is unedited.

### What changes do you think we should make in order to solve the problem?

Create a new instance of array before saving the queue.

```
const requests = [...persistedRequests, requestToPersist];
persistedRequests = requests;
Onyx.set(ONYXKEYS.PERSISTED_REQUESTS, requests)
```

**Comment by Pujan92** [comment] 2024-04-29 19:47
I agree with @bernhardoj's RCA and solution as it is not getting updated in the Onyx due to the ref issue. We should assign the new array to the onyx which will do the check correctly for `hasValueChanged` on 2 different refs.

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-04-30 23:13
PR is ready

cc: @Pujan92

**Comment by Pujan92** [comment] 2024-05-14 06:35
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [X] [@Pujan92] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40180
- [X] [@Pujan92] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40180/files#r1599450028
 - [X] [@Pujan92] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: NA
 - [X] [@Pujan92] Determine if we should create a regression test for this bug.: I think no.
 - [X] [@Pujan92] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by Pujan92** [comment] 2024-05-17 19:47
Bump @JmillsExpensify for the payment as PR hit the prod a week ago, automation seems broken here.

**Comment by JmillsExpensify** [comment] 2024-05-19 18:26
Payment summary:

 - Contributor: @bernhardoj $250 
 - Contributor+: @Pujan92 $250

**Comment by JmillsExpensify** [comment] 2024-05-19 18:28
All contracts paid out via Upwork and the BZ checklist is complete. Closing this one out!

**Closed by JmillsExpensify** 2024-05-19 18:28 UTC
Labels: Reviewing, External, Weekly, Bug
