### ISSUE TITLE
[$250] mWeb - Invoice - Invoice created selecting contact shows hmm not here and not delivered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47283] opened 2024-08-13 00:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/tests/view/4845908)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap fab -- create a new workspace
3. Tap fab -- send invoice
4. Enter an amount and tap next
5. Enter an user and tap next
6. Tap Send invoice
7. In mweb, login as user to whom invoice sent and pay as individual
8. In Android app, as sender from invoice room, tap plus icon -- send invoice
9. Complete the flow
10. In mweb, login as user to whom invoice sent and pay as individual
11. As sender in Android app, tap fab -- send invoice
12. Complete the flow entering the same user to whom user sent invoice above and select the contact (don't select invoice report with user)
13. Tap on invoice created
14. Note it turns to hmm not here in few seconds
15. In mweb, login as user to whom invoice sent and note invoice not received

## Expected Result:
Invoice created selecting contact must not show hmm not here and must be delivered

## Actual Result:
Invoice created selecting contact shows hmm not here and invoice not delivered to whom it is sent

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/909a1ee6-6071-44aa-ba82-8502f3e3bc0e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0163233c625ee3bd29</li>
        <li>Upwork Job ID: 1825545141198317784</li>
        <li>Last Price Increase: 2024-08-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment] 2024-08-13 00:57
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment] 2024-08-16 15:06
As I don't have an android, I am having to use browser stack so can't repro mWeb on Android in the same way.

**Comment by zanyrenney** [comment] 2024-08-16 15:07
Doing some more research and looking in the channel for similar/related issues

**Comment by zanyrenney** [comment] 2024-08-19 14:48
No needs reproduction label added, and my initial research isn't given me heaps more context. Adding external as this seems like a real issue we need to fix. cc @ishpaul777 if you can test this on an android to confirm, that would be awesome please!

**Comment by zanyrenney** [comment] 2024-08-30 11:50
As @ishpaul777 can't reproduce and neither could I as per this [comment](https://github.com/Expensify/App/issues/47283#issuecomment-2296764490) closing this one out until we can ascertain it's a real bug.

**Closed by zanyrenney** 2024-08-30 11:50 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
