### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Partial approved reports don’t have GBR in the LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43014] opened 2024-06-03 22:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717128748434439

## Action Performed:
1. Pre-requisite: Create a Collect workspace with user A (member) and user B (admin).
2. Pre-requisite: Enable approvals and have user B approve for user A
3. Have user A create several expenses
4. As user B, hold one of the expenses
5. Click approve and choose to partial approve what isn’t held

## Expected Result:
The newly created report for the held expense is GBR’ed in the LHN

## Actual Result:
The newly created report is not GBRed in the LHN

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![CleanShot 2024-05-30 at 22 12 43](https://github.com/Expensify/App/assets/38435837/53b16a10-a230-493b-b58e-49dc51786dfa)

https://github.com/Expensify/App/assets/38435837/58be228b-7a90-477e-83fb-cb9fd9310bdc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a11884101dc8ca36</li>
        <li>Upwork Job ID: 1798821044516715695</li>
        <li>Last Price Increase: 2024-06-13</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 102784355</li>
<li>dominictb | Contributor | 102784358</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by DivyamUp14** [comment] 2024-06-07 12:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When partially approving reports we dont have GBR in LHN

### What is the root cause of that problem?
In case of partial approval we will always have to show GBR as there are some pending approval.
[Here](https://github.com/Expensify/App/blob/02bd068156f2f357b5698c0606508f04fb6eea62/src/libs/actions/IOU.ts#L6182C13-L6182C105) we are calculating whether chat have more approvable or payable actions but [here](https://github.com/Expensify/App/blob/02bd068156f2f357b5698c0606508f04fb6eea62/src/libs/actions/IOU.ts#L6138C16-L6138C72) we are skipping the check for the current report which can have more approvals pending in case of partial. But in case of full it still can be approved because of the old data.
 
### What changes do you think we should make in order to solve the problem?
Since for partial approval the pending expenses can be approved we can set `hasOutstandingChildRequest` to `true` skipping GBR calculation for partial approvals [here](https://github.com/Expensify/App/blob/4fcc5a9fbef90114ab4f38a1be698c471e3e75d1/src/libs/actions/IOU.ts#L6182C1-L6182C105) like below. 
```js
            hasOutstandingChildRequest: full ? hasIOUToApproveOrPay(chatReport, expenseReport?.reportID ?? '') : true,
```
Additionally we will have to update `src/components/SettlementButton.tsx` [here](https://github.com/Expensify/App/blob/02bd068156f2f357b5698c0606508f04fb6eea62/src/components/SettlementButton.tsx#L245) as below to send the full argument as true as below to consider approval from Report preview as full which is how it is currently.
```js
            IOU.approveMoneyRequest(iouReport ?? {}, true);
```
Note: We can directly set this to true and do not need calculate if it partial or full as this part of code is called only for full approval. 

### What alternative solutions did you explore? (Optional)
NA

**Comment by DivyamUp14** [comment] 2024-06-07 15:29
Currently when user Approves from Report preview all the held transactions are getting unheld.
FYI @allgandalf

**Comment by DivyamUp14** [comment] 2024-06-07 18:57
@dominictb I agree this is not handled in offline mode currently but if you approve from Report view it without sending full flag as true even in the API is considered as full payment which in turn changes the transactions which are on hold to unheld.

**Comment by DivyamUp14** [comment] 2024-06-10 04:53
@allgandalf I checked the response data for transaction in the next request after approval and it returns data with transaction with unhold status. In the UI it is not updated because the optimistic data set in approval API is based on the full parameter which is not sent at the time of approving from Request preview

**Comment by johncschuster** [comment] 2024-06-11 14:27
No worries, @allgandalf! Thanks for the update! I hope you're feeling better!

**Comment by johncschuster** [comment] 2024-06-12 22:19
@allgandalf what's the latest here? Were you able to test this again?

**Comment by johncschuster** [comment] 2024-06-12 22:22
@allgandalf what's the latest here? Were you able to test this again?

**Comment by DivyamUp14** [comment] 2024-06-13 05:51
@allgandalf the issue is with data not being optimistically set, Once you approve the GBR disappears and then after the API response it shows up.

**Comment by DivyamUp14** [comment] 2024-06-14 20:02
@allgandalf this seems to be an existing bug and not because of the changes in proposal, do we need to address this bug in the solution of the current issue.

**Comment by DivyamUp14** [comment] 2024-06-14 20:15
### Updated [Proposal](https://github.com/Expensify/App/issues/43014#issuecomment-2154711718)
Tried to better explain the RCA.
FYI @allgandalf

**Comment by DivyamUp14** [comment] 2024-06-16 04:42
@allgandalf this is fixed in the latest main branch. If you take a pull and retry with my changes the issue is not there.

**Comment by DivyamUp14** [comment] 2024-06-17 08:09
@allgandalf I think its still an existing issue , checked in staging and its there.
[Exisitng Issue.webm](https://github.com/Expensify/App/assets/62924080/2e979840-3db3-4193-8742-3cbdab40e0b5)

**Comment by DivyamUp14** [comment] 2024-06-17 08:27
### Updated [proposal](https://github.com/Expensify/App/issues/43014#issuecomment-2154711718)
Updated proposal as with the latest changes the popup for confirmation of partial or full approval is shown on report preview also so no need to set approvals as full by default.
FYI @allgandalf

**Comment by DivyamUp14** [comment] 2024-06-17 15:26
@allgandalf a minor difference is still a difference as in [this proposal](https://github.com/Expensify/App/issues/43014#issuecomment-2154711718) the function will anyway always return true and so no need to call the function at all.

**Comment by blimpich** [comment] 2024-06-18 19:01
@dominictb @DivyamUp14 thank you both for carefully approaching this problem and explaining your solutions. It was very easy for me to read through this issue comment by comment and understand what was going on. Great work!

@dominictb congrats on having the selected proposal, feel free to raise a PR.

@allgandalf thank you for carefully considering and testing the proposals for regressions. Feel free to tag me in discussions related to that bug you found and I can make sure we create an issue and look into it.

**Comment by johncschuster** [comment] 2024-06-28 14:08
Deployed to staging 3 days ago 👍 I'll issue payment once it clears the waiting period.

**Comment by johncschuster** [comment] 2024-07-01 14:56
It's been 6 days since deployed to staging. We're almost there.

**Comment by johncschuster** [comment] 2024-07-02 18:46
@blimpich I noticed the PR linked above was deployed a week ago to staging, but hasn't yet been deployed to production. Do you know why we haven't deployed it yet?

**Comment by johncschuster** [comment] 2024-07-03 15:18
@allgandalf I'm not quite following. Are you saying the PR _has_ been deployed to production, but there's no comment making that known, or are you saying it _hasn't_ been deployed to production because an automation may have failed?

**Comment by johncschuster** [comment] 2024-07-08 14:18
Thanks for calling out that the code has been deployed to prod, @allgandalf. I've issued payment!

Can you please complete the BZ Checklist above?

**Closed** 2024-07-10 19:18 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
