### ISSUE TITLE
[hold for payment 2024-05-29][$250] Chat icons visible before input field renders

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#41397] opened 2024-05-01 08:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-4

## Action Performed:
- Kill the app 
- Open the app
- Navigate to a chat

## Expected Result:
- Buttons and input field should become visible at the same time

## Actual Result:
- Icons are visible before the input field renders
- They jump from left side to right which looks bad

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native UNTESTED
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Screenshot 2024-05-01 at 09 36 13](https://github.com/Expensify/App/assets/10736861/6b0e07a2-f6c6-4b3b-a022-9abcbf5b6d74)

https://github.com/Expensify/App/assets/10736861/0cb566e4-5905-42be-9fad-d51a383f0aaa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012097aedd79eaa599</li>
        <li>Upwork Job ID: 1785589469415067648</li>
        <li>Last Price Increase: 2024-05-01</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2024-05-01 23:40
♻️ Reviewing proposal.

**Comment by ikevin127** [comment] 2024-05-02 01:26
@ShridharGoel Thanks for your proposal !

Your **RCA** is correct in the sense that some elements are rendered as children of `AttachmentModal` therefore they become visible with delay. Regarding this being necessary or not: I think that it is since these components are using children props like `displayFileInModal` passed from `AttachmentModal` which are required for: `AttachmentPickerWithMenuItems`, `ComposerWithSuggestions` and `ReportDropUI` to work as expected (as children of AttachmentModal).

When it comes to the proposed **solution**, because `AttachmentModal` is a complex component used in other parts of the app, I am reserved when it comes to the addition of the `attachment` prop and additional logic mentioned since adding an additional state variable would increase the render count which we want to avoid, except when absolutely necessary.

> [!tip]
> Instead of moving the mentioned `AttachmentModal` children components outside of the AttachmentModal, I'd direct my attention towards the components that are outside of the AttachmentModal and try to find a solution that would make it such that all of the components become visible at the same time, as mentioned in the **expected result**.

**Comment by c3024** [comment] 2024-05-02 07:40
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Chat icons appear to jump from left to right because the attachment picker button and the composer are loaded with delay
### What is the root cause of that problem?
Composer and AttachmentPicker are inside the AttachmentModal so the icons are loaded quicker than the composer and attachment picker.
### What changes do you think we should make in order to solve the problem?
I think the jumping of icons from left to right is what causing the bad look. We can position them at the right from the beginning by adding `styles.justifyContentEnd`
https://github.com/Expensify/App/blob/1c651a1ac7c6af25df9459861ba4128e8d50e2fb/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L396
Instead of the above, we can add the `justifyContentEnd` to `chatItemComposeBox` here
https://github.com/Expensify/App/blob/1c651a1ac7c6af25df9459861ba4128e8d50e2fb/src/styles/index.ts#L2034
It does not break anything because this style is used only from composer and edit composer.
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-05-02 14:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The add action button and the input itself is missing when opening a chat for the first time after killing the app.

### What is the root cause of that problem?
The add button and the input/composer are wrapped with an AttachmentModal component.
https://github.com/Expensify/App/blob/f851f575ef433c0a87cac2c6cf20951483887566/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L398-L466

AttachmentModal connects to several onyx data,
https://github.com/Expensify/App/blob/f851f575ef433c0a87cac2c6cf20951483887566/src/components/AttachmentModal.tsx#L615-L634

as we (probably) know, withOnyx [will render null](https://github.com/Expensify/react-native-onyx/blob/2704488296482930e52941217b21ebb77fd7ee48/lib/withOnyx.js#L316-L318) if the data is not all ready yet.

In our case, both parentReport and policy are not available yet.
<img width="401" alt="Screenshot 2024-05-02 at 22 19 44" src="https://github.com/Expensify/App/assets/50919443/97196215-4290-4f22-97b9-0c6db82eeca5">

### What changes do you think we should make in order to solve the problem?

Reading through the code, both parentReport and policy actually aren't being used anymore.
https://github.com/Expensify/App/blob/f851f575ef433c0a87cac2c6cf20951483887566/src/components/AttachmentModal.tsx#L415-L418
https://github.com/Expensify/App/blob/f851f575ef433c0a87cac2c6cf20951483887566/src/components/AttachmentModal.tsx#L457

The above code shows the only usage of both data.

Both data are first added in https://github.com/Expensify/App/pull/28373 to check whether the user can edit the receipt or not, but the condition (`canEditReceipt`) is now "transformed" into a prop, so it's now controlled by the parent component. So, it's best to remove both parentReport and policy.

### What alternative solutions did you explore? (Optional)
Set the initial value for both data as an empty object

OR

Replace useOnyx with withOnyx

**Comment by ikevin127** [comment] 2024-05-02 16:02
♻️ Reviewing proposals.

**Comment by ikevin127** [comment] 2024-05-02 18:43
@c3024 Thanks for your proposal.

**RCA:**
> Composer and AttachmentPicker are inside the AttachmentModal so the icons are loaded quicker than the composer and attachment picker.

Your RCA is partially correct, except the other way around. The components inside the AttachmentModal appear slower to load then the ones outside it.

Regarding your **solution**: while it solves the positioning of the components outside of the AttachmentModal by keeping them at the right of the container instead of having them move from left to right, it still **does not fix** the issue as the icons inside the AttachmentModal are still appearing with delay (see attached video).

<details>
<summary>Android: Native (OnePlus 7T - Android 14)</summary>

https://github.com/Expensify/App/assets/56457735/cd555fa0-f92e-473a-8c09-8c02719c1ac0

</details>

> [!note]
> If you feel like I missed something from your proposal, please let me know and if the argument is solid I can reconsider assignment.

**Comment by ikevin127** [comment] 2024-05-02 18:43
@bernhardoj Thanks for your proposal.

**Part of RCA:**
> as we (probably) know, withOnyx [will render null](https://github.com/Expensify/react-native-onyx/blob/2704488296482930e52941217b21ebb77fd7ee48/lib/withOnyx.js#L316-L318) if the data is not all ready yet.
>
> In our case, both parentReport and policy are not available yet.

Your RCA is correct when it comes to the `withOnyx` rendering `null` if all imported keys data is not ready yet. I would accept this RCA as correct, if your proposed solution would actually fix the issue.

Regarding your **solution**: I tested it and there's still an issue with the `+` (attachment picker component) in the sense that it still appears with delay and there's a weird UI glitch (see video below), therefore your combination of RCA + solution does not fix our issue as per the **expected result**.

<details>
<summary>Android: Native (OnePlus 7T - Android 14)</summary>


https://github.com/Expensify/App/assets/56457735/38cd2757-9474-4abb-9418-7284a8d99116



</details>

> [!note]
> If you feel like I missed something from your proposal, please let me know and if the argument is solid I can reconsider assignment.

**Comment by ikevin127** [comment] 2024-05-02 18:43
Given @ShridharGoel's updated [proposal](https://github.com/Expensify/App/issues/41397#issuecomment-2088237370), I'd say the root cause was identified and the updated solution fixes our issue (see video below) as per the **expected result** which states:  "Buttons and input field should become visible at the same time".

<details>
<summary>Android: Native (OnePlus 7T - Android 14)</summary>

https://github.com/Expensify/App/assets/56457735/72986012-95bf-4460-98fa-2a3d874bf3b3

</details>

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-05-03 06:00
Hmm, I don't see the + action button shown with delay. 
https://github.com/Expensify/App/assets/50919443/0d1f4926-0ee3-48a0-9005-bb8c630b09e9

The AttachmentPickerWithMenuItems is also connected with a policy data, but it's available when I log it,
https://github.com/Expensify/App/blob/ee8f9c661f269f405a5ae8ba47ea07f42a306c6c/src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx#L330-L334

Can you test adding an initial value ({}) to it?

@ikevin127

**Comment by Julesssss** [comment] 2024-05-03 08:27
Thanks all, I'll let Kevin take another look at @bernhardoj's updated proposal before assigning.

**Comment by bernhardoj** [comment] 2024-05-03 11:28
false alarm, just linking to a similar issue

**Comment by ikevin127** [comment] 2024-05-03 21:23
> Thanks all, I'll let Kevin take another look at @bernhardoj's updated proposal before assigning.

Given @bernhardoj's updated proposal, the RCA is correct and makes sense now! The updated solution targets the root cause of the issue and fixes it more efficiently then the previously selected proposal (see videos below).

<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/56457735/4d9bee6d-b317-4781-b1a3-3f42fd3cc14a




</details>

<details>
<summary>iOS: Native</summary>


https://github.com/Expensify/App/assets/56457735/a3820b70-6bd9-49d3-8d2e-4742b73f8366



</details>

**Reasoning:**

The updated proposal completely removes the bottleneck which delayed the display of the child components within `AttachmentModal` and `AttachmentPickerWithMenuItems` component -> this renders all chat icons at the same time and a lot faster than the previously selected proposal.

**Why ?**
The previously selected proposal's solution worked in the sense that it would display all chat icons at the same time but it would do this by delaying all the icons display, instead of targeting the root cause which is that components wrapped with `withOnyx` don't render until all imported onyx keys data is ready.

🎀👀🎀 C+ reviewed

**Comment by joekaufmanexpensify** [comment] 2024-05-06 13:03
waiting for sign off on proposal

**Comment by bernhardoj** [comment] 2024-05-07 09:51
PR is ready

cc: @ikevin127

**Comment by joekaufmanexpensify** [comment] 2024-05-13 14:17
PR merged today!

**Comment by joekaufmanexpensify** [comment] 2024-05-20 14:23
On staging

**Comment by ikevin127** [comment] 2024-05-23 00:25
⚠️ **Automation failed**: This was deployed to **production** today [here](https://github.com/Expensify/App/pull/41727#issuecomment-2125962321), therefore should be **[HOLD for Payment 2024-05-29]** and have `Awaiting Payment` label.

cc @joekaufmanexpensify @Julesssss

**Comment by joekaufmanexpensify** [comment] 2024-05-29 13:51
All set to issue payment

**Comment by joekaufmanexpensify** [comment] 2024-05-29 13:54
@bernhardoj $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-05-29 13:54
@ikevin127 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-05-29 13:55
All set, thanks everyone!

**Closed by joekaufmanexpensify** 2024-05-29 13:55 UTC
Labels: Reviewing, External, Weekly, Bug
