### ISSUE TITLE
[$500] Workspace - Avatar in chat header does not revert to default avatar after deleting workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30724] opened 2023-11-01 17:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29554
## Action Performed:
1. Go to staging.new.expensify.com
2. Create a workspace and add a custom avatar.
3. Go to the #announce room.
4. Go to workspace settings.
5. Delete the workspace.
Note that

## Expected Result:
The workspace avatar in all part of the app will revert to the default avatar

## Actual Result:
The custom workspace avatar in LHN and chat as well as room details page is reverted to the default avatar, except the custom avatar in the room chat header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0d20defa-9cac-4f2e-9465-c857ab3df31e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by yh-0218** [comment] 2023-11-01 22:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avatar in chat header does not revert to default avatar after deleting workspace
### What is the root cause of that problem?
I think this is not relative with `policy `

The root cause of this problem is that we don't use `memo` correctly on `HeaderView`
https://github.com/Expensify/App/blob/a31933a049b9a9aa4222a4d3edab19b54a4555b7/src/pages/home/HeaderView.js#L274
### What changes do you think we should make in order to solve the problem?
We need to correct memo here
https://github.com/Expensify/App/blob/a31933a049b9a9aa4222a4d3edab19b54a4555b7/src/pages/home/HeaderView.js#L274
```
export default compose(
    withWindowDimensions,
    withLocalize,
    withOnyx({
        guideCalendarLink: {
            key: ONYXKEYS.ACCOUNT,
            selector: (account) => (account && account.guideCalendarLink) || null,
            initialValue: null,
        },
        parentReport: {
            key: ({report}) => `${ONYXKEYS.COLLECTION.REPORT}${report.parentReportID || report.reportID}`,
            selector: reportWithoutHasDraftSelector,
        },
        session: {
            key: ONYXKEYS.SESSION,
        },
    }),
)(
    memo(
        HeaderView,
        (prevProps, nextProps) =>
            lodashGet(prevProps.props, 'report.statusNum') === lodashGet(nextProps, 'report.statusNum') &&
            lodashGet(prevProps.props, 'report.stateNum') === lodashGet(nextProps, 'report.stateNum'),
    ),
)
```
### What alternative solutions did you explore? (Optional)


https://github.com/Expensify/App/assets/65789015/0cca2849-a24c-4c0b-8173-fb149336f928

**Comment by MitchExpensify** [comment] 2023-11-07 01:04
@robertKozik How do these proposals look to you?

**Comment by MitchExpensify** [comment] 2023-11-09 20:44
Friendly bump on a review of these proposals @robertKozik 🚀

**Comment by robertKozik** [comment] 2023-11-10 10:24
Sorry for the delay, I'll look into the proposals today 👀

**Comment by robertKozik** [comment] 2023-11-10 19:29
@yh-0218 Your proposal looks promising. Could you check the performance of your change? I saw that this memo was added due to performance reason and I would not like to degradate this metric

**Comment by yh-0218** [comment] 2023-11-10 20:52
hello, @robertKozik my [Proposal](https://github.com/Expensify/App/issues/30724#issuecomment-1789760527) is updated.

**Comment by yh-0218** [comment] 2023-11-14 20:06
hi, @robertKozik How about my proposal?

**Comment by robertKozik** [comment] 2023-11-16 12:13
@yh-0218 your updated proposal doesn't work on my end. I've checked once more previous version of it, and I can encounter some unnecessary re-renders, for example when admin changed the default currency of the workspace. This info is not used inside HeaderView so shouldn't cause re-renders

**Comment by robertKozik** [comment] 2023-11-16 12:21
@dukenv0307 could you profile your solution and check whether it is causing unnecessary re-renders? I've tried your proposed solution with, a subscribing only to selected keys:
```diff
export default memo(
    compose(
        withWindowDimensions,
        withLocalize,
        withOnyx({
            guideCalendarLink: {
                key: ONYXKEYS.ACCOUNT,
                selector: (account) => (account && account.guideCalendarLink) || null,
                initialValue: null,
            },
            parentReport: {
                key: ({report}) => `${ONYXKEYS.COLLECTION.REPORT}${report.parentReportID || report.reportID}`,
                selector: reportWithoutHasDraftSelector,
            },
            session: {
                key: ONYXKEYS.SESSION,          
            },
+           policy: {
+               key: ({report}) => `${ONYXKEYS.COLLECTION.POLICY}${report.policyID}`,
+               selector: (policy) => _.pick(policy, ['name', 'avatar']),
+           },
        }),
    )(HeaderView),
);
```

it restricts vast of unnecessary re-renders, but It doesn't work when workspace is deleted.

> OPTION: we can only get some necessary field of policy to make this component doesn't re-render many times.

could you incorporate this Option into your primary proposed solution? Then I'll checked it once more

**Comment by yh-0218** [comment] 2023-11-16 16:56
Hi, @robertKozik, I think we need to rerender when only change policy avatar.
Then we can get result. Not need `pendingAction` or `name`
```
   compose(
        withWindowDimensions,
        withLocalize,
        withOnyx({
            guideCalendarLink: {
                key: ONYXKEYS.ACCOUNT,
                selector: (account) => (account && account.guideCalendarLink) || null,
                initialValue: null,
            },
            parentReport: {
                key: ({report}) => `${ONYXKEYS.COLLECTION.REPORT}${report.parentReportID || report.reportID}`,
                selector: reportWithoutHasDraftSelector,
            },
            session: {
                key: ONYXKEYS.SESSION,
            },
+            policy: {
+                key: ({report}) => `${ONYXKEYS.COLLECTION.POLICY}${report.policyID}`,
+                selector: (policy) => _.pick(policy, ['avatar']),
+            },
        }),
    )(HeaderView),
```

**Comment by robertKozik** [comment] 2023-11-17 11:30
@yh-0218 all keys are necessary to fully cover all the cases. When subscribing only to the `avatar` key, the header won't update when changing the workspace name (thus adding `name`), or removing the workspace entirely (thus adding `pendingAction`)

**Comment by robertKozik** [comment] 2023-11-17 11:34
@dukenv0307 thanks for your cooperation, now I think your [solution](https://github.com/Expensify/App/issues/30724#issuecomment-1789356040) is sufficient. It solves the issue, and is not causing unnecessary re-renders

🎀 👀 🎀 C+ reviewed

**Comment by yh-0218** [comment] 2023-11-17 20:56
hi @robertKozik please check again, now header is updated without `name` and `pendingAction` when change name or remove workspace

**Comment by roryabraham** [comment] 2023-11-21 19:58
@dukenv0307 assigned you to make a PR so that we subscribe to only one policy instead of the full collection. Also, can you please update the component to replace `withWindowDimensions` and `withLocalize` with `useWindowDimensions` and `useLocalize`, respectively? Thanks!

**Comment by MitchExpensify** [comment] 2023-12-05 23:18
**Payment summary:**

- $500 @dukenv0307 requires payment via Upwork

**Comment by MitchExpensify** [comment] 2023-12-07 20:39
Created an Upwork job for payment as the old one is dust: https://www.upwork.com/jobs/~01ed8ba36b00a44817

**Comment by roryabraham** [comment] 2023-12-11 17:17
Looks like we're just waiting for @dukenv0307 to accept the offer of payment so that we can close this out

**Comment by roryabraham** [comment] 2023-12-15 00:53
Tried DMing @dukenv0307 in slack to get this closed out. I also don't appear to have access to @MitchExpensify's view in Upwork, so I can see they're hired but it's not clear to me if they've been paid yet

**Comment by roryabraham** [comment] 2023-12-15 00:53
@MitchExpensify As payment is the last todo here, I'm making you the issue owner for K2 purposes

**Comment by MitchExpensify** [comment] 2023-12-15 17:52
Sorry for the delay! Paid and contract ended

**Closed by MitchExpensify** 2023-12-15 17:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
