### ISSUE TITLE
[HOLD for payment 2023-08-28] [$1000] Web - Can create a task on a room archived

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23361] opened 2023-07-21 17:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a WS
2. Go to an admin room
4. Delete above WS , observed nothing can be done with WS admin room has been deleted
5. Click FAB => Assign task
6. Enter title => Next
7. Click => share somewhere section , observed that the admin room was archived before
8. Select admin room was archived
9. Go back admin room on LHN, observe that the task has been created

## Expected Result:
Cannot create task in archived room

## Actual Result:
Can create task in archived room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6b9eb00e-8f0a-4a66-ae3d-439c4ae514b9

https://github.com/Expensify/App/assets/93399543/c15346e8-01ef-41b9-b683-4e3af8842426

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689876140321539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e9e5e6cb40b0c193</li>
        <li>Upwork Job ID: 1683971766866116608</li>
        <li>Last Price Increase: 2023-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26071849</li>
<li>Nikhil-Vats | Contributor | 26071851</li>
<li>namhihi237 | Reporter | 26071855</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-21 17:36
## Proposal
by: @namhihi237
### Please re-state the problem that we are trying to solve in this issue.
Cannot create a task in an archived room
### What is the root cause of that problem?
- When in the step of selecting Share somewhere, we still list archived rooms in [here](https://github.com/Expensify/App/blob/eebb9e1ebbbf632df5e0b1c2a0746c1cc32aae96/src/pages/tasks/TaskShareDestinationSelectorModal.js#L62C1-L71C1) and [here](https://github.com/Expensify/App/blob/eebb9e1ebbbf632df5e0b1c2a0746c1cc32aae96/src/libs/OptionsListUtils.js#L841C1-L848C1)
- The backend hasn't checked if the room is archived.
### What changes do you think we should make in order to solve the problem?
We have 2 issues to update:
- Filter archived rooms like this:
```
_.filter(recentReports ,report => !report.isArchivedRoom)
```
- Backend should be check not allowed with the archived room.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by Nikhil-Vats** [comment] 2023-07-21 18:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users can share a task in an archived room.

### What is the root cause of that problem?
In `TaskShareDestinationSelectorModal`, we are filtering the reports using `isAllowedToComment` function.
https://github.com/Expensify/App/blob/2c5dd690028c11edb5bbaca134f7db663835e4a4/src/pages/tasks/TaskShareDestinationSelectorModal.js#L51-L60

In `isAllowedToComment` function, we don't check for archived reports -
https://github.com/Expensify/App/blob/2c5dd690028c11edb5bbaca134f7db663835e4a4/src/libs/ReportUtils.js#L534-L551
### What changes do you think we should make in order to solve the problem?
We have another function in `ReportUtils` called `shouldHideComposer` which hides the composer if report is archived, it has errors, user is not allowed to comment or user is anonymous -
https://github.com/Expensify/App/blob/2c5dd690028c11edb5bbaca134f7db663835e4a4/src/libs/ReportUtils.js#L2550-L2552

We should just use `shouldHideComposer` in `TaskShareDestinationSelectorModal` line 54 rather than using `isAllowedToComment`. This will not show the archived reports while searching for reports.

This will be consistent because if we are hiding composer then we shouldn't let the user share tasks in that report too.
### What alternative solutions did you explore? (Optional)
NA

**Comment by kbecciv** [comment] 2023-07-25 21:40
**Archived Room Allows Unauthorized Task Editing and Completion**

## Action Performed:
1 Go to the archived room and locate the old task
2 Click on the task thread
3 Mark it has incomplete
4 Change the title and verify you are successful
5 Mark it has complete and reopen it multiple times
6 Observe you are getting reopened and completed message

## Expected Result:
Unable to edit task

## Actual Result:
 Successful in editing title, closing and reopening tasks in an archived room
 
**Version Number:** 1.3.45.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation


https://github.com/Expensify/App/assets/93399543/f6b7c662-e01c-4116-ace0-2182fcbd53bd


https://github.com/Expensify/App/assets/93399543/2268dcb0-3c55-49e7-9979-4a478f13825e



**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690250190898259

**Comment by thienlnam** [comment] 2023-07-25 21:59
Had applause add this bug here since we should make sure we handle these edge cases in this issue as well

**Comment by twisterdotcom** [comment] 2023-07-25 22:46
Had some OOO followed by some unexpected OOO today. Just getting to this now.

**Comment by twisterdotcom** [comment] 2023-07-28 14:42
@aimane-chnaif any thoughts on these?

**Comment by thienlnam** [comment] 2023-07-28 17:19
Right now, we hide the composer, emoji picker, etc. if room is archived, permission is admins only or if there's an error of type errorFields.addWorkspaceRoom or errorFields.createChat. Since the composer is hidden in these cases, we should also not let user select these reports as share destination or edit task already shared in these reports, right? Or should we only check for archived rooms?
When task is opened(not completed), we have a cancel option in three dots menu, should we also disable that in cases above? I think we should.

Thanks for the questions @Nikhil-Vats 

Since tasks are essentially a thread with a complete state - I think we should follow what threads do when the parent room is archived. I haven't checked, but I'm guessing they stay open as they are independent reports and you can still chat on them. If that's the case, tasks should also stay open and you should still be able to modify and interact with them as normal despite what happens in the parent room.

> Since the composer is hidden in these cases, we should also not let user select these reports as share destination or edit task already shared in these reports, right?

I don't think we should check whether the composer is hidden or not to determine whether we should show these reports as a share destination. I'd rather have checks specifically for admin only permission rooms and archived rooms

**Comment by thienlnam** [comment] 2023-07-28 17:58
> Based on this statement of yours, https://github.com/Expensify/App/issues/23361#issuecomment-1650599098 is no longer a bug, right?

Yeah that's correct. Let's just handle preventing a new task from being created in an archived room in this issue

**Comment by twisterdotcom** [comment] 2023-07-31 08:34
What are we going with here then @aimane-chnaif?

**Comment by twisterdotcom** [comment] 2023-08-03 21:41
Bump @aimane-chnaif and @thienlnam. Could we get an answer for @Nikhil-Vats?

**Comment by thienlnam** [comment] 2023-08-03 23:54
Can we check if this is reproducible on main? We had another PR that touched share somewhere options and it might have resolved this

**Comment by thienlnam** [comment] 2023-08-04 18:12
Cool, let's handle that in this issue then!

**Comment by twisterdotcom** [comment] 2023-08-07 10:02
bump @aimane-chnaif

**Comment by twisterdotcom** [comment] 2023-08-10 10:57
Bump: https://expensify.slack.com/archives/C02NK2DQWUX/p1691665028402409

**Comment by arosiclair** [comment] 2023-08-11 16:09
Proposal LGTM. We should think about renaming this `ReportUtils.shouldHideComposer` function since at this point it is for a lot more than just the composer, but let's not block on that.

**Comment by twisterdotcom** [comment] 2023-08-18 10:18
Apologies but I am finally going on Parental Leave. I am reassigning to another member of the team.

**Comment by avi-shek-jha** [comment] 2023-08-22 04:52
Hi, Just wanted to confirm if I will get paid for this? Since the bug that I reported was merged into this one.

Reference:
https://github.com/Expensify/App/issues/23361#issuecomment-1650599098

**Comment by garrettmknight** [comment] 2023-08-28 17:12
@avi-shek-jha sure, can you retest your case and make sure it was fixed by the PR?

**Comment by garrettmknight** [comment] 2023-08-28 17:20
**Summarizing payments for this issue:**

#urgency bonus? Yes

Reporter: @namhihi237 $250 paid via Upwork
Reporter: @avi-shek-jha $250 upon confirmation that this fixed their reported bug.
Contributor: @Nikhil-Vats $1500 paid via Upwork
Contributor+: @aimane-chnaif  $1500

Upwork job is here: https://www.upwork.com/jobs/~01e9e5e6cb40b0c193

**Comment by garrettmknight** [comment] 2023-08-28 17:21
@aimane-chnaif are you receiving payment via NewDot or Upwork?

**Comment by avi-shek-jha** [comment] 2023-08-28 17:35
> As per this [comment](https://github.com/Expensify/App/issues/23361#issuecomment-1656111575) by Jack @avi-shek-jha 's bug report was deemed not a bug

Understood. Thank you.

**Comment by garrettmknight** [comment] 2023-08-29 16:19
@aimane-chnaif cool, once you complete the checklist I'll pay you in Upwork.

**Comment by garrettmknight** [comment] 2023-08-30 16:09
All paid up, closing.

**Closed by garrettmknight** 2023-08-30 16:09 UTC
Labels: External, Daily, Awaiting Payment, Bug
