### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] Web - Inconsistent color on "<- Back" button under Bank Connection (3 rd step: Personal Information)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21971] opened 2023-06-30 17:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website and settings
2. Go to Workspace > Bank Connection (3 rd step: Personal Information)

## Expected Result:
Consistent color on "<- Back" button under Bank Connection (3 rd step: Personal Information)

## Actual Result:
Inconsistent color on "<- Back" button under Bank Connection (3 rd step: Personal Information)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fc71de53-54a3-41f3-befc-3e565ef443c6

[screen-capture (32).webm](https://github.com/Expensify/App/assets/93399543/426a59be-aadb-4306-bb79-8e635440bdcb)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688044752235619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb9d718d13e9e41d</li>
        <li>Upwork Job ID: 1676689985038139392</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2023-07-05 20:31
@narefyev91 what do you think of the proposal above? This is a pretty inconsequential issue but if the fix works let's implement

**Comment by Vishrut19** [comment] 2023-07-05 21:32
Not able to go beyond this step @kbecciv 
<img width="1469" alt="Screenshot 2023-07-06 at 2 59 55 AM" src="https://github.com/Expensify/App/assets/53470896/6021e96a-1aa3-4628-a322-4acc9cc751c3">

**Comment by b4s36t4** [comment] 2023-07-05 21:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Inconsistent color on "<- Back" button under Bank Connection (3 rd step: Personal Information)
### What is the root cause of that problem?

Default styles from onfido, onfido SDK have some default styles applied to the webpage.

### What changes do you think we should make in order to solve the problem?

If we customize the UI config while initiating the onfido SDK it might cause issues with other buttons.

We should override the styles for navigation bar of onfido SDK.

### Styles to Override.
> onfido used `visibilit` prop for `Back` text, which we could override in `index.css`.

> for back icon, onfido uses background image with different variants to fix this we should override the icon data URI  `index.css`.

_Removing hover states entirely would give the consistent color & background_

**PS: Maybe we need to use !important for css values to make them default in any case.**


Output: 
<img width="397" alt="Screenshot 2023-07-06 at 3 09 09 AM" src="https://github.com/Expensify/App/assets/59088937/62ff9c10-3176-48cb-bb8c-c90f7f9ec51e">



### What alternative solutions did you explore? (Optional)

NA, maybe just override the styles for button while initiating the onfido SDK (maybe causes other places to break which is unintended behaviour)

**Comment by narefyev91** [comment] 2023-07-06 06:56
Proposal of @ginsuma looks good to me https://github.com/Expensify/App/issues/21971#issuecomment-1615162561 - it's indicated the root case of the issue
🎀 👀 🎀 C+ reviewed

**Comment by narefyev91** [comment] 2023-07-10 09:03
@Gonals friendly ping here

**Comment by MahmudjonToraqulov** [comment] 2023-07-11 07:39
Upwork ID: https://www.upwork.com/freelancers/~01347b2040312758ec

**Comment by Pujan92** [comment] 2023-07-11 16:23
I think this issue was raised earlier and closed with the comment here https://github.com/Expensify/App/issues/17790
cc: @JmillsExpensify

**Comment by adelekennedy** [comment] 2023-07-11 16:46
I don't feel super strongly about it - if the fix above works and makes the product more unified great. If @JmillsExpensify you feel that we should just close to focus on higher priority tasks that works for me 👍

**Comment by MahmudjonToraqulov** [comment] 2023-07-17 07:36
Hey @narefyev91 @Gonals. I saw PR is merged. Will I apply for a job for reporter role?

**Comment by MahmudjonToraqulov** [comment] 2023-07-18 14:18
I applied on Upwork for a job.

**Comment by adelekennedy** [comment] 2023-07-25 20:56
Payment due!
@narefyev91 will you apply to the [Upwork Job](https://www.upwork.com/jobs/~01bb9d718d13e9e41d)

**Comment by MahmudjonToraqulov** [comment] 2023-07-26 04:41
@adelekennedy  I accepted the offer.

**Comment by adelekennedy** [comment] 2023-07-28 02:01
Issue reporter: @MahmudjonToraqulov $250 paid via Upwork
Contributor: @ginsuma  $1500 paid via Upwork (issue payment and speed bonus)
Contributor+: @narefyev91 $1500 paid via Upwork (issue payment and speed bonus)

**Comment by adelekennedy** [comment] 2023-07-31 21:56
just pending @narefyev91 to apply - I want to make sure i'm not paying the wrong person!

**Closed** 2023-08-01 05:14 UTC
Labels: External, Daily, Awaiting Payment, Bug
