### ISSUE TITLE
[HOLD for payment 2023-08-14] Update App to React native 0.72 version

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#18444] opened 2023-05-04 21:08 UTC
Let's stay up to date with the latest React native version for the best performance and features available and update our RN version to 0.72

Previous internal issue https://github.com/Expensify/Expensify/issues/275274

**Comment by fabioh8010** [comment] 2023-05-05 19:16
Hi, I'm Fábio from Callstack - expert contributor group - I would like to work on this issue

**Comment by fabioh8010** [comment] 2023-05-05 20:18
PR is ready: https://github.com/Expensify/App/pull/18507

**Comment by mountiny** [comment] 2023-05-15 11:09
Being hyper focused on the EC3 committment so unable to help out here much, hopefully we can get more time on this next week

**Comment by michaelhaxhiu** [comment] 2023-05-23 22:32
New Feature isn't as pressing as Bug. But we'll get this done soon ⏲️ 🧇

**Comment by mountiny** [comment] 2023-06-01 23:34
@fabioh8010 continues working on this

**Comment by mountiny** [comment] 2023-06-14 16:48
Not overdue we changed strategy

**Comment by mountiny** [comment] 2023-06-23 09:02
@fabioh8010 is focusing on this 100% now, there is a stable release 🎉

**Comment by mountiny** [comment] 2023-07-03 11:55
Still making progress

**Comment by michaelhaxhiu** [comment] 2023-07-11 20:35
Last comment on the PR was ~7 hours ago https://github.com/Expensify/App/pull/18507#issuecomment-1630812013

It's progressing!

**Comment by mountiny** [comment] 2023-07-20 20:31
Still in review

**Comment by mountiny** [comment] 2023-07-31 08:47
We are 🤏 this close

**Comment by michaelhaxhiu** [comment] 2023-08-04 14:31
Note: I'm preparing to go OOO for ~2 weeks. @MitchExpensify can I ask you for a favor to ensure payment is handled properly. 

I am not sure how this will get compensated because the PR https://github.com/Expensify/App/pull/18507 has numerous C+ assigned but I think @mountiny has a clear sense of that piece!

**Comment by mountiny** [comment] 2023-08-06 17:42
I believe its @aimane-chnaif and @parasharrajat being paid $1000 for this PR great job! 

agency C+ are paid differently.

**Comment by MitchExpensify** [comment] 2023-08-07 14:02
Thanks! And just to be sure @vitHoracek, is it ok to send the payment now and close this out?

**Comment by roryabraham** [comment] 2023-08-07 20:32
Yes we can close this out. We'll have another follow-up soon, but that's separate

**Comment by MitchExpensify** [comment] 2023-08-08 20:14
Thanks @roryabraham ! Offer sent [here](https://www.upwork.com/jobs/~010996343f450c5b40) for payment before closure cc @parasharrajat @aimane-chnaif

**Comment by MitchExpensify** [comment] 2023-08-08 22:41
Paid @aimane-chnaif! 

@parasharrajat Have you made the NewDot request for $1000?

**Comment by suraj-mandal** [comment] 2023-08-09 03:59
Hi! I found this issue while going through the job description on upwork. Is this issue still existing? If yes, I would like to work on this

**Comment by puneetlath** [comment] 2023-08-11 21:46
The automation didn't work for some reason. Added hold for payment to the title.

**Comment by JmillsExpensify** [comment] 2023-08-16 03:08
@MitchExpensify In the future can you summarize payment in one post? I'll accept the above since multiple people confirmed the amount.

**Comment by JmillsExpensify** [comment] 2023-08-16 03:09
Reviewed the details for @parasharrajat. Approved by payment in NewDot based on the $1,000 BZ summary above.

**Comment by MitchExpensify** [comment] 2023-08-16 20:20
> @MitchExpensify In the future can you summarize payment in one post? 

For sure!

**Comment by MitchExpensify** [comment] 2023-08-16 20:21
Closing as we're all paid out here and no BZ steps necessary

**Closed by MitchExpensify** 2023-08-16 20:21 UTC
Labels: Daily, NewFeature, Awaiting Payment
