### ISSUE TITLE
[HOLD for Payment][$500] Inconsistency of redirection after creating IOU and task

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30883] opened 2023-11-04 12:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699054252287299

## Action Performed:
1. Log in to ND
2. Create a Request money
3. Redirected to the DM
4. Create a task
5. Observe
## Expected Result:
After creating IOU or task should be redirected to DM
## Actual Result:
After creating task redirected to task itself
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/17e62f59-271b-467e-9148-d71307d62dad

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c50b7a867fe5efd</li>
        <li>Upwork Job ID: 1720787853214482432</li>
        <li>Last Price Increase: 2023-11-11</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 27643579</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by s-alves10** [comment] 2023-11-04 13:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Task creation redirects to the task report. Should redirect to the DM chat

### What is the root cause of that problem?

We're redirecting to the task report after creating a task as you can see
https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/libs/actions/Task.js#L216

This is the root cause

### What changes do you think we should make in order to solve the problem?

When creating a task, we have `shareDestination` and `assignee`. 
I think it's reasonable to redirect to the `shareDestination`, not to DM chat

Updating
https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/libs/actions/Task.js#L216
to
```
    Navigation.dismissModal(parentReportID);
```

would redirect user to share destination


<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)
In the case we still want to redirect to the DM, we can update the above code to
```
    Navigation.dismissModal(assigneeChatReportID || parentReportID);
```

**Comment by eh2077** [comment] 2023-11-05 01:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inconsistency of redirection after creating IOU and task

### What is the root cause of that problem?

The root cause of this issue is that after creating task, we open the task report, see

https://github.com/Expensify/App/blob/846a4b74ef81fa17ecaed4af8bfe22ad2eeeb8c8/src/libs/actions/Task.js#L216

### What changes do you think we should make in order to solve the problem?

To be consistent with IOU, I think we can open chat with assignee(DM like IOU) after creating task and set notification about new task. We can change 

https://github.com/Expensify/App/blob/846a4b74ef81fa17ecaed4af8bfe22ad2eeeb8c8/src/libs/actions/Task.js#L216

to similar logic of IOU

https://github.com/Expensify/App/blob/846a4b74ef81fa17ecaed4af8bfe22ad2eeeb8c8/src/libs/actions/IOU.js#L879-L880

So, we can redirect to DM after creating a new task and have a notification about new task like IOU.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by quinthar** [comment] 2023-11-06 08:33
The decision to redirect to the parent report (eg, the DM or the workspace
chat) when creating a money request is intentional and not up for
consideration here.  Accordingly, please model task creation on this, and
also redirect to the parent chat room when creating the task.

**Comment by eh2077** [comment] 2023-11-07 14:51
### Proposal
[Updated](https://github.com/Expensify/App/issues/30883#issuecomment-1793602583) to redirect to the parent chat room after task creation.

**Comment by s-alves10** [comment] 2023-11-14 07:47
@allroundexperts 

May I ask you a question? I'm afraid I didn't understand correctly. Will you kindly explain what the below sentence means?

> If the task is being created from within the chat itself, simply show the task preview and redirect nowhere

**Comment by s-alves10** [comment] 2023-12-03 19:25
@danieldoglas 

Could you please check on the payment status? The PR was merged into production 2 weeks ago

**Comment by kevinksullivan** [comment] 2023-12-12 01:31
Payment summary

- Contributor: @s-alves10  $500 
- C+: @allroundexperts $500 (NewDot)

Paid out @s-alves10 . @allroundexperts am I good to close this, assuming you'll request in newdot? Let me know if not and I can reopen!

**Closed by kevinksullivan** 2023-12-12 01:31 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-01-24 23:57
$500 payment to @allroundexperts based on comment above.
