### ISSUE TITLE
[HOLD for payment 2023-06-23] [$1000] Offline message is not positioned correctly for settings page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20426] opened 2023-06-07 23:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Go to admins chat
3. Open details page
4. Click on settings
5. Go offline
## Expected Result: 
Offline message is at the bottom of the page
## Actual Result: 
It is not at the bottom of the page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/1af0e4df-844a-4fad-8c92-b48cfc9be0ee" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/6e13ec0c-6747-4f6f-8b36-40408113902f" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685906171088159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e15c728e0a56930d</li>
        <li>Upwork Job ID: 1666701415554134016</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-06-07 23:53
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The offline message on the settings page is not positioned correctly.
### What is the root cause of that problem?
The root cause of this problem is that the page is not utilizing the entire available height, causing the error message to appear in the middle of the page rather than at the bottom.
### What changes do you think we should make in order to solve the problem?

To fix this issue we need to use ScrollView with styles.flex1 inside src/pages/Report/ReportSettingsPage.js
### Demo
![image](https://github.com/Expensify/App/assets/28243942/38b744f9-9672-4b94-a35a-50a8af7af653)

**Comment by kadiealexander** [comment] 2023-06-08 06:58
Reproduced:

![IMG_1170](https://github.com/Expensify/App/assets/59587260/6ece6335-5d32-45f5-8832-e2570c6d393b)

**Comment by mollfpr** [comment] 2023-06-08 16:31
@aman-atg @kushu7 I just try to use `ScrollView` and it looks good without `flex1`. Is `flex1` necessary to solve this issue?

**Comment by jeet-dhandha** [comment] 2023-06-08 17:41
# Proposal

##Please re-state the problem that we are trying to solve in this issue.
- The message `youAppearToBeOffline` on the admin settings page is not currently positioned at the bottom.

## What is the root cause of that problem?
- In the `ReportSettingPage.js` file, the children of the `ScreenWrapper` component do not take up the full height.

## What changes do you think we should make in order to solve the problem?
- To address this problem, a `View` with the `flex1` style is added beneath the `ScreenWrapper`. This solution resolves the issue not only for the Admin Screen but also for any other component that does not occupy the full height.

- Solution Code is as below

<img width="1025" alt="Screenshot 2023-06-08 at 10 46 30 PM" src="https://github.com/Expensify/App/assets/78416198/060a9ee6-a00d-41f1-9162-f82f05627c6e">

## What alternative solutions did you explore? (Optional)
- Although a `ScrollView` was mentioned earlier as a possible solution, it is unnecessary in this context as it would most likely be redundant and provide no significant benefit.

**Comment by mollfpr** [comment] 2023-06-09 17:53
>No, flex: 1 is not necessary. However, using flex: 1 on a child component typically ensures that it takes up all the available space in its parent container. This approach is also consistent with the majority of our codebase.

Yes, I'm inclined to have consistency between page components.

@AndrewGable Let's go with @aman-atg [proposal](https://github.com/Expensify/App/issues/20426#issuecomment-1581665721) since they propose it first.

Thanks everyone for the other proposals!

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment] 2023-06-12 16:41
Bump @AndrewGable @kadiealexander

**Comment by kadiealexander** [comment] 2023-06-19 07:07
@kevinksullivan I'm going OOO so I've reassigned this to ensure everyone gets paid on time. I've sent out all the offers which you can find [here](https://www.upwork.com/ab/applicants/1666701415554134016/hired), and  @mollfpr and @aman-atg  are due an #urgency bonus for their quick work [(here)](https://github.com/Expensify/App/issues/20426#issuecomment-1591608459). Thanks so much for your help!

**Comment by kevinksullivan** [comment] 2023-06-19 15:06
Sounds good @kadiealexander !

**Comment by AndrewGable** [comment] 2023-06-21 22:12
Awaiting payment

**Closed** 2023-06-23 13:46 UTC
Labels: External, Daily, Awaiting Payment, Bug
