### ISSUE TITLE
[$1000] Web - When hovering over the message in the reply thread, the icon changes its position in the Task Assign section.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22297] opened 2023-07-05 19:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the Plus button.
2. Go to Task Assign.
3. Add a title, assign and share information, and confirm tasks.
4. Write a message and hover over it.
5. Click on "reply thread" and write a message.
6. Hover over the message in the reply thread.

## Expected Result:
The position of the icon should remain unchanged when hovering over a message in the reply thread.

## Actual Result:
When hovering over the message in the reply thread, the icon changes its position in the Task Assign section.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d78c7b77-8001-46b7-b2f7-1a53e84c3285

https://github.com/Expensify/App/assets/93399543/40a3fbc1-b432-426b-b67d-7b5369fac4eb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688581881998149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b8f2af3b67caa455</li>
        <li>Upwork Job ID: 1676692535250608128</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2023-07-05 19:30
Removing the blocker since it doesn't look like an issue that should block deploy

**Comment by olexyt** [comment] 2023-07-05 20:48
It is still opened for proposal?

**Comment by alexxxwork** [comment] 2023-07-06 03:03
Couldn't reproduce. I just don't have "mark as offensive" icon.

**Comment by joh42** [comment] 2023-07-06 16:46
Also unable to reproduce both locally and on staging. Seems like the flag icon is erroneously shown on your own messages, but is then (correctly) removed

**Comment by lschurr** [comment] 2023-07-07 20:19
@hayata-suenaga are you able to reproduce this or can it be closed?

**Comment by abdulrahuman5196** [comment] 2023-07-08 09:50
@lschurr  I am unable to reproduce this issue even in staging. If you are also unable to reproduce. We should close this one.

**Comment by lschurr** [comment] 2023-07-10 16:40
Closing.

**Closed by lschurr** 2023-07-10 16:40 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
