### ISSUE TITLE
Search - Tooltip is not displayed on the new Saved search indicating the name can be edited

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51531] opened 2024-10-26 19:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3284916
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to the Search page
2. Click on the filter icon
3. Set a filter for the category “Advertising”
4. Click on Save > Save Search button

## Expected Result:
A new “Saved” section is displayed on the Search page navigation.
A tooltip is displayed on the new Saved search indicating the name can be edited

## Actual Result:
A tooltip is not displayed on the new Saved search indicating the name can be edited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/97f93be2-d79a-40c2-813a-e76ad93c0f88

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-26 19:26
We think that this bug might be related to #wave-control

**Comment by Shahidullah-Muffakir** [comment] 2024-10-26 20:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip is not displayed on the saved search.
### What is the root cause of that problem?
we are only showing the tooltip once, based on this comment and code: 
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/pages/Search/AdvancedSearchFilters.tsx#L290-L293

### What changes do you think we should make in order to solve the problem?

if we want to show the tooltip each time a user save the search , we can remove the condition, and directly write:
            `SearchActions.showSavedSearchRenameTooltip();`

**Comment by Shahidullah-Muffakir** [comment] 2024-10-26 20:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip is not displayed on the saved search.
### What is the root cause of that problem?
we are only showing the tooltip once, based on this comment and code: 
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/pages/Search/AdvancedSearchFilters.tsx#L290-L293

### What changes do you think we should make in order to solve the problem?

if we want to show the tooltip each time a user save the search , we can remove the condition, and directly write:
            `SearchActions.showSavedSearchRenameTooltip();`


https://github.com/user-attachments/assets/d9be8cc9-ba0b-4a71-a38e-750fd6485410

**Comment by Christinadobrzyn** [comment] 2024-10-28 05:47
Gonna test this tomorrow when I'm back from ooo

**Comment by FitseTLT** [comment] 2024-10-28 12:56
Lo


https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/pages/Search/AdvancedSearchFilters.tsx#L290-L293

**Comment by Christinadobrzyn** [comment] 2024-10-29 02:18
I'm not sure I understand the problem, the video doesn't match the steps in the OP. What are we trying to solve? Where is the 'tooltip' - do you mean the hamburger with the option to Rename?

**Comment by izarutskaya** [comment] 2024-10-29 10:31
We refer to https://github.com/Expensify/App/pull/49473 and expect to see this tooltip

![Screen Shot 2024-10-26 at 7 36 13 PM](https://github.com/user-attachments/assets/fcd35ffd-77fe-491e-8824-e3e6f2a2fb39)

Let me know if  I can help something else

**Comment by Christinadobrzyn** [comment] 2024-10-30 06:29
Ah okay, I don't see that is possible in https://staging.new.expensify.com/ either.

**Comment by izarutskaya** [comment] 2024-10-30 12:16
We tested step by step in [TR](https://expensify.testrail.io/index.php?/cases/view/3284916) and step 8 says that `Verify a tooltip is displayed on the new Saved search indicating the name can be edited` 

![Screenshot 2024-10-30 140055](https://github.com/user-attachments/assets/ef2c8efa-dc31-44bd-99f6-618c6cd85ad8)

Screenshot with tooltip from this [PR](https://github.com/Expensify/App/pull/49473) and you will see link with PR at the bottom of the page in "Comments or Known issue". 

![Screenshot 2024-10-30 140621](https://github.com/user-attachments/assets/644d8a75-3d8e-4de9-8e95-5f34b0339d67)

**Comment by Christinadobrzyn** [comment] 2024-10-31 05:55
Amazing! Thank you for all the information @izarutskaya! 

@lanitochka17 and @luacmartins since you were part of this [issue](https://github.com/Expensify/App/pull/49473)

Can you confirm that we want the tooltip to show on a saved search? From what I can tell, the tooltip doesn't show with any desktop version so I just want to make sure we want it. 

 Here's an image of the tooltip that we're referring to
 
 https://github.com/Expensify/App/issues/51531#issuecomment-2443837075

Thanks!

**Comment by luacmartins** [comment] 2024-10-31 15:50
@izarutskaya the tooltip should only be shown the first time ever you save a search. So if you are testing on an existing account that has already saved a search in the past (even though all saved searches are deleted), we should NOT show the tooltip again. Hope that clarifies things.

**Comment by Christinadobrzyn** [comment] 2024-11-01 06:06
Thanks @luacmartins - I think this is happening as expected but asking @izarutskaya if they can double-check - https://expensify.slack.com/archives/C9YU7BX5M/p1730441140139549?thread_ts=1730168405.943419&cid=C9YU7BX5M

**Comment by luacmartins** [comment] 2024-11-01 17:23
Cool, seems like we can close this one then.

**Closed by luacmartins** 2024-11-01 17:23 UTC
Labels: Daily, Bug
