### ISSUE TITLE
[HOLD for payment 2024-01-28] [$500]Chat - App crashes when the window height is minimum

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33615] opened 2023-12-26 19:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Minimize the window.
3. Resize it to the minimum height.
4. Expand the window.

## Expected Result:
App does not crash.

## Actual Result:
App crashes when the window height is minimum

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f7fb4cd3-1584-4426-9d46-fe7bf4a3e952

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d893fa799f5b5c2</li>
        <li>Upwork Job ID: 1739723395197186048</li>
        <li>Last Price Increase: 2024-01-09</li>
<li>Automatic offers: </li>
<ul>
<li>aswin-s | Contributor | 28097059</li>
</ul></li>
    </ul>
</details>

**Comment by aswin-s** [comment] 2023-12-26 19:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App crashes when the window height is at minimum

### What is the root cause of that problem?

In ReportActionList component variable `initialNumToRender` is computed based on window height. This value gets passed down to FlastList component. When window height is at minimum this number becomes negative, which in turn causes FlatList component to throw an error and crash the application.

https://github.com/Expensify/App/blob/2b58e1cbef63c4fdce8a6e8fb3ee52089009a8d8/src/pages/home/report/ReportActionsList.js#L313-L317

https://github.com/Expensify/App/blob/2b58e1cbef63c4fdce8a6e8fb3ee52089009a8d8/src/pages/home/report/ReportActionsList.js#L464

### What changes do you think we should make in order to solve the problem?

Update the `initialNumToRender` method to limit the value to zero and above.

```tsx
const initialNumToRender = useMemo(() => {
        const minimumReportActionHeight = styles.chatItem.paddingTop + styles.chatItem.paddingBottom + variables.fontSizeNormalHeight;
        const availableHeight = windowHeight - (CONST.CHAT_FOOTER_MIN_HEIGHT + variables.contentHeaderHeight);
        // Wrap the result in Math.max(value, 0) to limit the lowest value
        return Math.max(Math.ceil(availableHeight / minimumReportActionHeight),0);
    }, [styles.chatItem.paddingBottom, styles.chatItem.paddingTop, windowHeight]);
```

### What alternative solutions did you explore? (Optional)
None (edited)

**Comment by Santhosh-Sellavel** [comment] 2023-12-27 18:16
Defaulting `initialNumToRender` to  `0` won't cause any side effects?

**Comment by aswin-s** [comment] 2023-12-27 19:13
> Defaulting `initialNumToRender` to  `0` won't cause any side effects?

@Santhosh-Sellavel  Doesn't seem to be causing any issues in my testing. We could also set the minimum value as 1. Flatlist seems to be throwing error only when the number becomes negative.

**Comment by JmillsExpensify** [comment] 2024-01-03 04:31
Proposal discussion on-going.

**Comment by Santhosh-Sellavel** [comment] 2024-01-09 18:30
> > Defaulting `initialNumToRender` to  `0` won't cause any side effects?
> 
> @Santhosh-Sellavel Doesn't seem to be causing any issues in my testing. We could also set the minimum value as 1. Flatlist seems to be throwing error only when the number becomes negative.

Sorry, I got lost in the discussion. Still making 0 seems kinda feels off to me, can we make it `undefined` as its the default prop?

**Comment by aswin-s** [comment] 2024-01-09 22:44
@Santhosh-Sellavel That works. I've [updated my proposal](https://github.com/Expensify/App/issues/33615#issuecomment-1869744487) to return undefined if item count is less than or equal to zero.

**Comment by Santhosh-Sellavel** [comment] 2024-01-11 19:36
C+ Reviewed
🎀 👀 🎀 

@aswin-s's [proposal](https://github.com/Expensify/App/issues/33615#issuecomment-1869744487) looks good to me!

**Comment by Santhosh-Sellavel** [comment] 2024-01-11 19:45
@hayata-suenaga Let me know your thoughts on this [proposal](https://github.com/Expensify/App/issues/33615#issuecomment-1869744487), please tag any FlatList experts to get some insights on this!

**Comment by aswin-s** [comment] 2024-01-13 05:12
Accepted offer and [PR raised](https://github.com/Expensify/App/pull/34470).

**Comment by hayata-suenaga** [comment] 2024-01-30 18:23
Melvin, we're just waiting for payment

**Comment by JmillsExpensify** [comment] 2024-01-31 03:35
@Santhosh-Sellavel Do you mind kicking off the BZ checklist above?

**Comment by JmillsExpensify** [comment] 2024-01-31 03:35
In the meantime, payment summary is as follows:

 - Issue reporter: QA
 - Contributor: @aswin-s $500
 - Contributor+: @Santhosh-Sellavel $500

**Comment by JmillsExpensify** [comment] 2024-01-31 03:36
Contributor has been paid, so just C+ and BZ checklist at this point.

**Comment by JmillsExpensify** [comment] 2024-02-07 02:43
Going to close this issue out since the only thing remaining is C+ payment.

**Closed by JmillsExpensify** 2024-02-07 02:43 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by Santhosh-Sellavel** [comment] 2024-02-10 21:04
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: N/A
* [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
* [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
* [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A Applause raised this, tests already exists.
* [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
* [x]  [@JmillsExpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon: N/A

I suspect the crash occurred due to a react-native upgrade and a rare case.

**Comment by JmillsExpensify** [comment] 2024-02-11 13:07
$500 approved for @Santhosh-Sellavel based on summary above.
