### ISSUE TITLE
[$250] [HOLD for payment 2024-06-20] Hold expense - Unable to hold expense with failed scanning when there is only one expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43207] opened 2024-06-06 18:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-3
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat that has no unsettled expense.
3. Submit a scan expense with an invalid receipt.
4. Wait for the scanning to fail.
5. When the scanning fails, go to transaction thread.
6. Click 3-dot menu > Hold.
7. Enter reason and save it.
8. Return to main chat.
9. Go to transaction thread.
10. Click 3-dot menu.

## Expected Result:
The held expense with failed scanning will remain held status.

## Actual Result:
The held expense with failed scanning return to unheld status.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/a34fc26d-c64b-4a50-8dad-d50fb97c3842

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c2dfe28442e0872</li>
        <li>Upwork Job ID: 1803913741255552220</li>
        <li>Last Price Increase: 2024-06-20</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 102817385</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-06-06 18:13
@alexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-06 18:13
We think that this bug might be related to #wave-collect - Release 1

**Comment by srikarparsi** [comment] 2024-06-06 18:35
I think this is probably related to this [PR](https://github.com/Expensify/App/pull/42374)

**Comment by srikarparsi** [comment] 2024-06-06 20:17
Not reproducible when reverting the [PR](https://github.com/Expensify/App/pull/42374). The PR adds functionality to hold on single expense views.

**Comment by srikarparsi** [comment] 2024-06-06 21:57
[Checking](https://expensify.slack.com/archives/C01GTK53T8Q/p1717710880449239?thread_ts=1717699373.036439&cid=C01GTK53T8Q) to see if we can demote this to a daily, similar to what we did [here](https://github.com/Expensify/App/issues/43203#issuecomment-2153241753).

**Comment by trjExpensify** [comment] 2024-06-07 10:06
@srikarparsi @blimpich if we reverted the offending PR, do we need to check this off the deploy blocker list: https://github.com/Expensify/App/issues/43168?

**Comment by blimpich** [comment] 2024-06-07 12:36
@trjExpensify Yup! Didn't get around to it because I was offline when the revert was merged, but just checked it off.

**Comment by trjExpensify** [comment] 2024-06-07 13:47
Understandable man!

**Comment by roryabraham** [comment] 2024-06-07 17:17
Not a big deal because I caught it, but generally things should only be checked off after the issue is retested in staging and we verify that it no longer happens. In this case, the revert never actually made it to staging.

**Comment by srikarparsi** [comment] 2024-06-07 18:24
[PR](https://github.com/Expensify/App/pull/42374) got reverted and changes are being CPed to staging. QA is [retesting](https://expensify.slack.com/archives/C01GTK53T8Q/p1717784620934509?thread_ts=1717780790.948359&cid=C01GTK53T8Q), will check it off once they finish

**Comment by kavimuru** [comment] 2024-06-07 18:48
Issue is not reproducible. 

https://github.com/Expensify/App/assets/43996225/2cc728e3-d45a-457e-8a2c-728eab45e803

**Comment by srikarparsi** [comment] 2024-06-07 18:52
Perfect, closing this out and checking it off ([slack link](https://expensify.slack.com/archives/C01GTK53T8Q/p1717784667742159?thread_ts=1717780790.948359&cid=C01GTK53T8Q))

**Comment by c3024** [comment] 2024-06-17 03:24
@srikarparsi 

I reviewed the related PR #43237 . Can you please reopen this and assign this issue to me for payment? Thanks!

**Comment by blimpich** [comment] 2024-06-17 16:48
@alexpensify @srikarparsi re-opened to handle payment for @c3024

**Comment by alexpensify** [comment] 2024-06-17 19:50
Noted, I'll work on the payment process before the due date.

**Comment by alexpensify** [comment] 2024-06-20 22:16
@c3024 -  I've sent over an offer via Upwork. Please accept, and then I can complete the payment process. Thanks!

**Comment by c3024** [comment] 2024-06-20 22:19
Accepted, thanks @alexpensify

**Comment by alexpensify** [comment] 2024-06-20 22:20
Payouts due: 2024-06-20

- [ ] Contributor: Internal 
- [ ] Contributor+: $250 @c3024 

Upwork job is [here](https://www.upwork.com/jobs/~019c2dfe28442e0872).

**Comment by alexpensify** [comment] 2024-06-20 22:22
All set, I've completed the payment process in Upwork. Closing!

**Closed by alexpensify** 2024-06-20 22:22 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
