### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Chat - Inconsistent behavior on deleting message that have reply/thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21103] opened 2023-06-20 10:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat on new.expensify.com
2. Write and send a message
3. Reply to your own message, it will lead you to thread page(good)
4. Go back to conversation page and delete the message
5. It says "[deleted message] 1 reply" (good), delete that message again.
6. It will remove the [deleted message] with the 1 reply temporarily, then go to the thread that is created when you reply to the message
7. Go back to the conversation, observe the "[deleted message]" reappeared(bad)
Note that: I am not saying the deleted message is reappearing but  the label "[deleted message]" is appearing again after it is deleted

## Expected Result:
When the [deleted message] is deleted it should permanently be not shown, or it always shouldn't allow the label [deleted message] to be deleted based on Expensify rule. At least, it should be consistent.

## Actual Result:
Now, it is not consistent. When you delete the "[deleted message]" label in the conversation it will delete temporarily, then after you get in to the thread and get back to the conversation you will see it reappearing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**1.3.28-5

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c7af1a5a-a401-4624-b88e-8c2bc695eb53

https://github.com/Expensify/App/assets/93399543/46915661-7574-4c42-ba01-9526c9d5a3ab

**Expensify/Expensify Issue URL:**

**Issue reported by:** @kalll

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686645553886709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b1d6662d4b09fb2</li>
        <li>Upwork Job ID: 1671865093908606976</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-06-20 20:54
i can reproduce this. I think this is related to the above issue. Sense checking next steps here.

**Comment by joekaufmanexpensify** [comment] 2023-06-21 19:54
Still determining next steps

**Comment by joekaufmanexpensify** [comment] 2023-06-23 18:12
@fedirjh thoughts on the above proposal?

**Comment by joekaufmanexpensify** [comment] 2023-06-26 18:46
Yeah @techievivek and I chatted about this and are cool to treat this like a separate issue, rather than a regression.

**Comment by joekaufmanexpensify** [comment] 2023-06-27 17:42
Sounds good! This is pending review from @joelbettner now.

**Comment by joekaufmanexpensify** [comment] 2023-06-28 19:09
Bumped Joel 1:1

**Comment by joekaufmanexpensify** [comment] 2023-06-29 20:38
Ah, I see Joel is OOO. Asked [here. ](https://expensify.slack.com/archives/C03TQ48KC/p1688071119833569)

**Comment by joekaufmanexpensify** [comment] 2023-06-30 17:33
Added the engineering label to temporarily re-assign someone while Joel is OOO, as he won't be back until late next week. @MonilBhavsar when you have a chance, could you just review and sign off on [this proposal](https://github.com/Expensify/App/issues/21103#issuecomment-1608608789)? 

Then, we'll be all set to get started on this one. Thanks!

**Comment by KALLL** [comment] 2023-06-30 19:51
> 📣 @KALLL 🎉 An offer has been automatically sent to your Upwork account 🎉
> 
> Reporter - [$1000] Chat - Inconsistent behavior on deleting message that have reply/thread

Thanks! I replied on Upwork, can you review?

**Comment by joekaufmanexpensify** [comment] 2023-07-03 13:11
Pending review of proposals.

**Comment by KALLL** [comment] 2023-07-03 19:10
@MelvinBot @lschurr waiting approval following your offer on Upwork as a reporter!

**Comment by MonilBhavsar** [comment] 2023-07-04 12:01
@fedirjh Just to clarify, are we going with the alternate proposal here? https://github.com/Expensify/App/issues/21103#issuecomment-1598596884
Also, looks like the idea is to hide Delete button for already deleted action. Sounds fair

**Comment by MonilBhavsar** [comment] 2023-07-04 12:46
Yes, that makes sense. Also, I think DeleteComment API response should send originalMessage in response if OpenReport is sending it. I am trying to figure out why we have two keys - message and originalMessage

**Comment by MonilBhavsar** [comment] 2023-07-04 14:16
Thanks! Makes sense little bit, but still I think that can be done with one key - `message`.
We're also discussing internally https://expensify.slack.com/archives/C03TQ48KC/p1688478763318449 to make server return originalMessage when calling DeleteComment or UpdateComment and introduce consistency

**Comment by joekaufmanexpensify** [comment] 2023-07-05 18:19
I think we are close to approving a proposal here. is that right @MonilBhavsar @fedirjh ?

**Comment by joekaufmanexpensify** [comment] 2023-07-06 16:18
Great, thanks!

**Comment by joekaufmanexpensify** [comment] 2023-07-07 16:53
Still close to selecting a proposal.

**Comment by joekaufmanexpensify** [comment] 2023-07-10 13:46
@fedirjh Could you share what we need to get a proposal selected here?

**Comment by joekaufmanexpensify** [comment] 2023-07-11 19:54
Sounds good! I bumped the discussion.

**Comment by joekaufmanexpensify** [comment] 2023-07-12 18:45
Reached out to Monil.

**Comment by joekaufmanexpensify** [comment] 2023-07-13 18:08
Chatted to @MonilBhavsar 1:1 and he's going to follow up here!

**Comment by MonilBhavsar** [comment] 2023-07-14 09:29
I am testing some theories and seems like this issue is fixed. Can anyone please confirm

**Comment by MonilBhavsar** [comment] 2023-07-14 09:31
Seems like this PR fixed the issue https://github.com/Expensify/App/pull/20460

**Comment by MonilBhavsar** [comment] 2023-07-14 10:58
Sorry, yes it is not fixed. I was just on my working branch.

> @MonilBhavsar have you checked my comment here https://github.com/Expensify/App/issues/21103#issuecomment-1605442271 😅 ? and this comment https://github.com/Expensify/App/issues/21103#issuecomment-1605490198 :

Yes, I like your proposal. Since, optimistically, we're updating the `message` field while deleting the comment. We can check message field to determine if message is deleted or not. And, we can send the originalMessage from server, but we should not hold on that, and I think we can polish it later.

Sounds good?

**Comment by MonilBhavsar** [comment] 2023-07-14 12:00
So, we go with @hungvu193's alternative proposal for now https://github.com/Expensify/App/issues/21103#issuecomment-1598596884
And, as a followup/cleanup, we update server to return original message

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:05
BZ checklist is now complete, all set to issue payment. @hungvu193 was assigned on 2023-07-14, and the PR was merged on 2023-07-17. The 15th and 16th were weekend days, so the PR was merged in ~1 business day and qualifies for a bonus. So we need to make the following payments: 

- @fedirjh $1,500 - C+ review and speed bonus. 
- @hungvu193 $1,500 - PR and speed bonus. 
- @KALLL $250 - reporting bonus.

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:07
@hungvu193 $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:13
@KALLL It looks like our automation incorrectly sent you two offers for this job in Upwork. I see the first automatically paid you $250 for the reporting bonus here on 2023-07-14. So I've gone ahead and closed out the second with no payment. 

Please let us know if you have any questions. Thanks!

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:25
@KALLL you should have been sent an escrow refund request for $250 for the duplicate payment, since we ended the contract with no payment. Please confirm here once you've accepted it. Thanks!

I also went ahead and ended the contract for which you received your $250 payment as well!

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:34
Great, thanks! @fedirjh $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:34
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:35
Bug is fixed, BZ checklist complete, and all payment issued. Closing as this is all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-07-26 13:35 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
