### ISSUE TITLE
Web - Search - The last result in search page is not visible when pressing up key

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33672] opened 2023-12-27 21:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click on 'Search' icon
2. Press up key

## Expected Result:
The last result should be visible

## Actual Result:
Last result is not visible. It is only made visible by scrolling the list up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f41686c4-8a61-47e3-b9ac-5745cd7900db

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment] 2023-12-27 21:40
Sorry, but I don't get what this issue is saying. Is the scroll in the video happening automatically? If so, I can't reproduce it... 
 
https://github.com/Expensify/App/assets/521248/e6c69fd5-3302-453f-8b43-247fe9311ed4

**Comment by iwiznia** [comment] 2023-12-27 22:18
Conversation here https://expensify.slack.com/archives/C9YU7BX5M/p1703713279179439

**Comment by iwiznia** [comment] 2023-12-27 22:51
I need to look into this more, but given I see the same behavior in my account in production and that applause is reproducing inconsistently (see link above) I think this is not a blocker.

**Comment by iwiznia** [comment] 2023-12-27 23:02
Steps to reproduce (not in all accounts):
- Open search
- Press arrow up
- Check how it DOES NOT scroll you down to the bottom to show the last contact selected

**Comment by Pujan92** [comment] 2023-12-27 23:26
It is due to the extra line height which makes the option row of 71px, but in `getItemLayout` we consider it 64px. Will be fixed after this [PR](https://github.com/Expensify/App/pull/33662) is merged.

**Comment by iwiznia** [comment] 2023-12-28 16:18
Awesome, that PR is being CPed and we can test.

**Comment by mountiny** [comment] 2023-12-28 20:29
https://github.com/Expensify/App/assets/36083550/85c12792-96ec-4c59-93b3-fea1b2bdeb8b

I think this is fixed and can be closed

**Comment by iwiznia** [comment] 2023-12-28 20:43
Nope, still bad for me, but should not block deploy since it's also bad for me in production

**Comment by JmillsExpensify** [comment] 2024-01-03 04:34
Why is this even an issue? Did we support it and break it? I'm mainly asking because we really don't support keyboard navigation holistically throughout the app.

**Comment by JmillsExpensify** [comment] 2024-01-31 03:31
Still not clear what's going on here.

**Comment by JmillsExpensify** [comment] 2024-01-31 03:31
Additionally, we don't officially support keyboard navigation so I'm going to close this issue.

**Closed by JmillsExpensify** 2024-01-31 03:31 UTC
Labels: Engineering, Weekly, Bug
