### ISSUE TITLE
[HOLD for payment 2024-01-31] Web - Chat - Cursor shows a hand instead of a text cursor "I" when hovering over text in code block

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31085] opened 2023-11-08 23:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to any chat
3. Send a code block
4. Hover over code block

## Expected Result:
The cursor shows a text cursor "I"

## Actual Result:
The cursor shows a hand cursor

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1022e4a4-a9e3-49fd-8631-4614bca9e06c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment] 2023-11-09 00:55
Hmm, I'm not able to reproduce this and I don't think this is a deploy blocker - @tylerkaraszewski - do you agree?

**Comment by s-alves10** [comment] 2023-11-09 03:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Pointer cursor shows instead of text cursor when hovering over the code block

### What is the root cause of that problem?

We removed the role 'text' and use 'presentation' instead(from the PR https://github.com/Expensify/App/pull/24482)
But we're still use 'text' below to set the cursor
https://github.com/Expensify/App/blob/a63a8962ed3a1ba38de278b4331bbb655104ca7f/src/components/Pressable/GenericPressable/BaseGenericPressable.tsx#L135

Also we replaced the `accessibilityRole` with role in the same PR, but we're still using `accessibilityRole` below
https://github.com/Expensify/App/blob/dee9b3110a7ebe0aa250c3f966d6a69925d916f4/src/components/Pressable/GenericPressable/index.tsx#L14

This is the root cause

### What changes do you think we should make in order to solve the problem?

We should use the `CONST.ACCESSIBILITY_ROLE.TEXT` instead of ``text'` here
https://github.com/Expensify/App/blob/a63a8962ed3a1ba38de278b4331bbb655104ca7f/src/components/Pressable/GenericPressable/BaseGenericPressable.tsx#L135

And remove this line
https://github.com/Expensify/App/blob/dee9b3110a7ebe0aa250c3f966d6a69925d916f4/src/components/Pressable/GenericPressable/index.tsx#L14

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/b7ab3e65-c1e1-402d-aeb2-a12b4528227d


</details>

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-11-09 03:12
@sophiepintoraetz 

This issue is reproducible in staging(version: 1.3.97-1), but not in production.

**Comment by sophiepintoraetz** [comment] 2023-11-09 03:33
@s-alves10 - my URL shows it's staging.

**Comment by s-alves10** [comment] 2023-11-09 03:35
@sophiepintoraetz 

Yeah. It looks like you used '`', not '```'

**Comment by s-alves10** [comment] 2023-11-09 04:06
@sophiepintoraetz @tylerkaraszewski 

Yeah. It looks like you used "`". Please try with "```"

**Comment by getusha** [comment] 2023-11-09 06:01
@s-alves10 @aimane-chnaif the PR is not deployed to staging how could this be a regression from that?

**Comment by s-alves10** [comment] 2023-11-09 06:03
https://github.com/Expensify/App/pull/24482#issuecomment-1801315358

**Comment by getusha** [comment] 2023-11-09 06:16
Seems like a minor issue we missed i can raise a PR to fix it.

**Comment by s-alves10** [comment] 2023-11-09 06:18
There are some other places we need to replace(accessibilityRole -> role)

**Comment by sophiepintoraetz** [comment] 2023-11-10 00:18
Ah yes, thanks for the correct, @s-alves10 - able to reproduce!
![image](https://github.com/Expensify/App/assets/42940078/d022add8-006d-477f-b932-36a94bbd844a)

**Comment by tylerkaraszewski** [comment] 2023-11-10 00:33
This is pretty minor, I am going to remove the deploy blocker tag and assign @getusha to fix it.

**Comment by getusha** [comment] 2023-11-13 17:41
PR will be ready tomorrow.

**Comment by sophiepintoraetz** [comment] 2023-11-21 03:45
@getusha - what's happening here?

**Comment by getusha** [comment] 2023-11-21 07:33
Raised the PR https://github.com/Expensify/App/pull/31605

**Comment by tylerkaraszewski** [comment] 2023-12-28 23:08
Has this been abandoned? Should we re-assign it? What's going on with the PR?

**Comment by situchan** [comment] 2023-12-29 03:16
@narefyev91 was C+ reviewer in PR but he's now not in C+ team.
I can take over if needed

**Comment by sophiepintoraetz** [comment] 2024-01-04 02:27
Ah yes, let's do that - thank you @situchan

**Comment by situchan** [comment] 2024-01-11 17:14
PR is in review

**Comment by getusha** [comment] 2024-01-23 18:00
PR merged recently.

**Comment by sophiepintoraetz** [comment] 2024-01-31 02:54
Offers sent @getusha and @situchan! @situchan - can you complete the checklist please?

**Comment by situchan** [comment] 2024-01-31 04:27
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/24482
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: It was large PR and PR author (@getusha) is [aware](https://github.com/Expensify/App/issues/31085#issuecomment-1803225733) of it and thus fixed it
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug. No need regression test as this is super minor and caught by QA team during staging regression testing
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by MitchExpensify** [comment] 2024-02-03 23:28
Sorry to ask but I'm having trouble tracking down the contracts for this job in Upwork. Mind sharing the links here for payment @getusha @situchan ? Thanks

**Comment by MitchExpensify** [comment] 2024-02-03 23:29
Reminder set to pay

**Comment by MitchExpensify** [comment] 2024-02-06 22:04
Friendly bump on the above, I took another look but don't see anything - Do I need to create contracts for you both @getusha @situchan ?

**Comment by getusha** [comment] 2024-02-06 22:18
I assume i am not eligible to get paid since we handled it as a regression.

**Comment by MitchExpensify** [comment] 2024-02-08 23:32
> I assume i am not eligible to get paid since we handled it as a regression.

Typically yes no additional payment on regression issues

**Closed by MitchExpensify** 2024-02-08 23:32 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
