### ISSUE TITLE
[$250] Chat - Clicking "Leave Thread" button logs user out automatically

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43843] opened 2024-06-17 15:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
. Open any chat and write a message
2. Reply to a message, click on the three dots, then select "Leave Thread"

## Expected Result:
The user should exit the thread without logging out

## Actual Result:
Clicking "Leave Thread" logs the user out instead of leaving the thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3d7afe08-9ecc-4080-b20b-ec04e59102ee
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e8295cbabac200d1</li>
        <li>Upwork Job ID: 1802846072655751812</li>
        <li>Last Price Increase: 2024-06-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by lanitochka17** [comment] 2024-06-17 15:10
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-17 15:10
We think that this bug might be related to #vip-vsp

**Comment by rigestshala** [comment] 2024-06-18 11:37
Contributor details
Your Expensify account email: rigest.shala@gmail.com
Upwork Profile Link: [https://www.upwork.com/freelancers/rigests](https://www.upwork.com/freelancers/rigests)

**Comment by c3024** [comment] 2024-06-18 14:29
> I am unable to repro

@jainilparikh Try with a fresh account (before verifying with any magic code).

**Comment by garatkarr** [comment] 2024-06-18 21:42
I've also tried to repo multiple times, including inviting a new user. Unable to repro. Need more information.

**Comment by lschurr** [comment] 2024-06-18 21:59
Closing since we can't reproduce this bug.

**Closed by lschurr** 2024-06-18 21:59 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by rigestshala** [comment] 2024-06-18 22:38
I actually was able to reproduce and tracked it down to this line. I'm new to this project, but it seems that the API was logging out the user.

https://github.com/Expensify/App/blob/11b66a04015d137f90d80b16714935bf044a750b/src/libs/actions/Report.ts#L2699C1-L2700C1
