### ISSUE TITLE
[HOLD for payment 2024-03-29] [$500] [Polish] Web - LHN - "This is the beginning of your chat" message can be seen for "Your space"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38087] opened 2024-03-11 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4416342&group_by=cases:section_id&group_id=229070&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with a new account
2. Pin "Your space" from search if it's not visible in the LHN

## Expected Result:
The message shouldn't be seen.

## Actual Result:
"This is the beginning of your chat" message can be seen for "Your space" in the LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/e5ae99e6-efc1-48f9-a0ce-546822679901)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dd0f2883a58d68d9</li>
        <li>Upwork Job ID: 1767615221483282432</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-11 20:07
@garrettmknight I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by nkdengineer** [comment] 2024-03-12 11:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web - LHN - "This is the beginning of your chat" message can be seen for "Your space"
### What is the root cause of that problem?
- When there is no action in current user's space, the last message text to display is from this [logic](https://github.com/Expensify/App/blob/c039ff7421afb6eade7bb6107d80908564cc792a/src/libs/SidebarUtils.ts#L366-L388), that leads to the current behavior
### What changes do you think we should make in order to solve the problem?
- We can add condition ```ReportUtils.isSelfDM(report) ||``` to [this](https://github.com/Expensify/App/blob/c039ff7421afb6eade7bb6107d80908564cc792a/src/libs/SidebarUtils.ts#L329), then the last message text in case there is no actions will be ```No activity yet```

### What alternative solutions did you explore? (Optional)
- NA

**Comment by nkdengineer** [comment] 2024-03-12 18:16
@garrettmknight Can you confirm the expected behavior? (What text should be displayed in LHN instead of "This is begining of your chat")

**Comment by garrettmknight** [comment] 2024-03-14 21:28
@nkdengineer I think it should be "This is your personal space. Use it for notes, tasks, drafts, and reminders." since that's the default in the room to start.

**Comment by getusha** [comment] 2024-03-17 10:21
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/38087#issuecomment-1989357346) looks good to me
🎀 👀 🎀 C+ Reviewed.

**Comment by getusha** [comment] 2024-03-17 10:23
🎀 👀 🎀

**Comment by getusha** [comment] 2024-03-17 10:24
🎀 👀 🎀 C+ Reviewed

**Comment by quinthar** [comment] 2024-03-20 01:34
@getusha what is the ETA for review?

**Comment by garrettmknight** [comment] 2024-03-28 18:57
Sorry for the wait - @getusha @Krishna2323 offers out to you both.

**Comment by garrettmknight** [comment] 2024-03-29 17:05
Paid out, closing.

**Closed by garrettmknight** 2024-03-29 17:05 UTC
Labels: External, Daily, Awaiting Payment, Bug
