### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Dev: Web - Console error on click of Connect online with Plaid button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22448] opened 2023-07-07 20:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create workspace if not created
2. Go to settings > Workspaces >Connect bank account
2. Click on Connect online with Plaid button

## Expected Result:
 Should not show any console error

## Actual Result:
Multiple console error appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.37-6
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bdce3177-82a1-4c16-861c-e4bcbf4db333

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688724565368739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01422f8298b6001281</li>
        <li>Upwork Job ID: 1677488790826577920</li>
        <li>Last Price Increase: 2023-07-08</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-07-08 01:24
I can't reproduce this ... I think it's Dev only? Will ask C+ to help

**Comment by greg-schroeder** [comment] 2023-07-08 01:25
Oh hey @allroundexperts - you already have a proposal for this 😅 - I can't reproduce it but I'm assuming you have? Also what's the protocol for accepting your own proposal if you get assigned to an issue as C+ after creating a proposal? lol not sure I've seen that before

**Comment by Vishrut19** [comment] 2023-07-09 04:57
I can reproduce this error and I can see a lot of errors in console. 

https://github.com/Expensify/App/assets/53470896/fdd027e7-e1b1-44cf-99ba-30caef4ebf71

All these are saying as required - translate, numberFormat, datetimeToRelative etc. all are stated as required but still not passed. So, I think as stated by @allroundexperts with we remove `withLocalizePropTypes` and use `use useLocalize`then it should solve all the problems as when I was migrating BankAccountManualStep.js file I saw all these same errors but after removing `withLocalize` HOC and replacing it with `useLocalize` hooks along with removing the extra prop types as well using `..._.omit(StepPropTypes, _.keys(withLocalizePropTypes))` which are not required.

**Comment by hayata-suenaga** [comment] 2023-07-17 22:02
wait i'm confused here so @allroundexperts are you already working on the fix PR?

**Comment by hayata-suenaga** [comment] 2023-07-17 22:11
> HAHAHAHA, My proposal looks good to me. That's lit 🔥🔥🔥

haha, then I read this

> regression from https://github.com/Expensify/App/pull/21778. Since the mentioned PR is within the 7 days regression period, the related C+ and contributor will fix this.

so is this already handled by the PR author or we have to assign the contributor to this?

**Comment by hayata-suenaga** [comment] 2023-07-18 16:11
ah I see then this issue will be automatically closed when the PR is deployed

**Comment by greg-schroeder** [comment] 2023-07-26 12:27
Okay so this was a regression and is being handled here (payments, etc.): https://github.com/Expensify/App/issues/16242

**Closed by greg-schroeder** 2023-07-26 12:27 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Awaiting Payment, Bug

**Comment by gadhiyamanan** [comment] 2023-07-26 12:39
@greg-schroeder i think reporting bonus should be done here, right?

**Comment by greg-schroeder** [comment] 2023-07-26 12:47
Ye, but the C/C+ are in the other issue

**Comment by gadhiyamanan** [comment] 2023-07-26 13:24
> You have an offer for reporting in Upwork.

@greg-schroeder i do not have any offer for reporting
