### ISSUE TITLE
[HOLD for payment 2024-08-07][$250] [Search v1] Implement action buttons

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39890] opened 2024-04-09 02:09 UTC
Implement this section of the design doc - https://docs.google.com/document/d/1ldZ85fyQO4662hLZRNFfm0_IxaP7-PWvaqc8Z33jsLQ/edit#bookmark=id.kt71e0n7yfsm

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f3a821ed6381f7c6</li>
        <li>Upwork Job ID: 1821233586009483173</li>
        <li>Last Price Increase: 2024-08-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by luacmartins** [comment] 2024-04-24 00:01
On hold

**Comment by Kicu** [comment] 2024-05-06 08:03
hey, I would like to work on this task today

**Comment by Kicu** [comment] 2024-05-06 12:26
@luacmartins some questions regarding design doc:

#### 1.
Which set of actions should we support? according to the list in design doc: https://docs.google.com/document/d/1ldZ85fyQO4662hLZRNFfm0_IxaP7-PWvaqc8Z33jsLQ/edit#bookmark=id.kt71e0n7yfsm
we have: `done | paid | review | pay | approve | hold | submit`
**but** in the pseudocode below there is also `delete` should I include it?


#### 2.
Is the action type and translation `view` or `review` because right now api returns `view`?


#### 3.
I can see that we already have API commands for some of these functions, example: https://github.com/Expensify/App/blob/bb8ad521b43495c3b6db42ef788ecefe64c80f7f/src/libs/API/types.ts#L384 and they have their payloads defined. So I'm assuming that I should be using those existing commands.
If yes - then where should I take the required params from? For example Pay (https://github.com/Expensify/App/blob/a86501a237cdecd54356cb47b64c629086e6a30f/src/libs/API/parameters/PayMoneyRequestParams.ts) we need: `iouReportID, chatReportID, reportActionID, paymentMethodType` Should I assume they will be available inside the TransactionItem data?

**Comment by luacmartins** [comment] 2024-05-06 17:06
>Which set of actions should we support?

I added the missing ones to the doc, but the full list is: `done | paid | review | pay | approve | hold | submit | delete | view`

>Is the action type and translation view or review because right now api returns view?

We have both, view just navigates the user to the transaction thread reportID in the RHP. Review will do the same, but will be shown when hasErrors is true, indicating that the admin should review the request (and potentially make edits)  instead of just view it.

>I can see that we already have API commands for some of these functions, example:

No, we'll need to create new commands since the existing ones update "live" Onyx data and work offline. The API requests from Search will not work like that because the users might not have "live" data for those transactions, reports, policies, etc. So those commands need to rely only on the Search data in `snapshot.data`. These commands will only work online with the limited information available in the snapshot key.

**Comment by luacmartins** [comment] 2024-05-06 22:51
@Kicu also noting that this issue will be put on hold until we migrate some existing code in the backend. So I'd recommend picking another one for now.

**Comment by Kicu** [comment] 2024-05-07 08:41
Alright I'm stopping work on this one for now 👍 thanks for the answers they will be useful when I return to this.

I created a draft just so that I won't loose my work, its unfinished so don't review

**Comment by greg-schroeder** [comment] 2024-05-09 05:36
Held

**Comment by greg-schroeder** [comment] 2024-05-22 00:19
Thanks @luacmartins - good looking out

**Comment by luacmartins** [comment] 2024-06-18 17:19
@Kicu I think we can get started on the `Delete` bulk action. We already return `canDelete` field for transactions, so the only thing missing from the backend would be the new API command `DeleteMoneyRequestOnSearch`. I'll get that started on my end as well.

**Comment by luacmartins** [comment] 2024-06-18 20:48
I put up PRs to introduce the `Done` and `Paid` badges. We might be able to work on `Hold` and `Unhold` actions since that doesn't depend on the migration we're doing. @Kicu wanna get started on that one? I'd need to work on the API still, but we could get started on the App changes.

**Comment by Kicu** [comment] 2024-06-19 07:30
Yeah sure.
To be honest the easiest for me would be to simply start to handle all the types of actions in one PR so I will start with that. We can comment out/filter some code in case API is not ready.

Can you give the me the details of api actions and endpoint names and payloads?

**Comment by Kicu** [comment] 2024-06-19 13:34
@luacmartins 
If you want you can take a quick look at this unfinished draft: https://github.com/Expensify/App/pull/41725/files

I need 2 main things from you to continue:
 1. the list of all actions that this PR should support, and their names/payloads. Is this still correct: https://github.com/Expensify/App/issues/39890#issuecomment-2096516066?
 2. what should we display for Report item and its transactions. Specfically what does the button on `ReportItem` do and where do I get the action for it?
 
<img width="500" alt="Screenshot 2024-06-19 at 15 32 55" src="https://github.com/Expensify/App/assets/3929868/971d7257-3f4f-4559-af21-370d3fe1178e">

**Comment by luacmartins** [comment] 2024-06-19 15:54
@Kicu I think that for now we'd implement the `Hold` and `Unhold` methods. We have this section in the [design doc](https://docs.google.com/document/d/1ldZ85fyQO4662hLZRNFfm0_IxaP7-PWvaqc8Z33jsLQ/edit#bookmark=id.kt71e0n7yfsm), that mentions the behavior on press and the API method it should call and payload. Let me know if you have any questions. FYI these commands don't exist yet

**Comment by luacmartins** [comment] 2024-06-20 18:06
AFAIK you can't hold/unhold reports, only transactions. The report item should have its [own action](https://github.com/Expensify/App/blob/5c4ab7762b9ab3f50d34e1090217a7b11d297a49/src/types/onyx/SearchResults.ts#L114), so we should use that.

**Comment by eh2077** [comment] 2024-06-21 11:32
> Implement this section of the design doc - https://docs.google.com/document/d/1ldZ85fyQO4662hLZRNFfm0_IxaP7-PWvaqc8Z33jsLQ/edit#bookmark=id.kt71e0n7yfsm

@luacmartins Can I have access to this design doc as I was assigned to review the PR, thank you!

**Comment by luacmartins** [comment] 2024-06-21 16:05
Shared the doc with you

**Comment by greg-schroeder** [comment] 2024-07-03 19:37
Looks like no payments (via upwork or ND) or regression test will be necessary here (as its a new feature), so I'm going to close this now. Please reopen if you disagree.

**Comment by Kicu** [comment] 2024-07-04 11:09
This PR is still active for this task: https://github.com/Expensify/App/pull/41725

There were 2 PRs - one for actions on a single item and one for bulk actions. The one for single is still being developed.
I think we might want to reopen @greg-schroeder

**Comment by greg-schroeder** [comment] 2024-07-04 11:49
Okay thanks! got it

**Comment by greg-schroeder** [comment] 2024-07-10 14:34
https://github.com/Expensify/App/pull/41725 now on staging

**Comment by Kicu** [comment] 2024-07-10 15:01
yeah now we can continue with normal flow for this issue. There should be no more PRs for it at this point

**Comment by luacmartins** [comment] 2024-07-10 18:53
We'll still need to implement the buttons for Pay, Approve and Submit. I think we could do those now too and once the API is implemented we'd already support it in NewDot

**Comment by Kicu** [comment] 2024-07-11 13:32
So that would mean to write the necessary actions for pay, approve and submit and assume they would work basically?

because the `ActionCell` component is almost ready to display different actions. I think only translations are missing right now.
So:
 - add new actions that call api
 - add them to the if here: https://github.com/Expensify/App/blob/main/src/components/SelectionList/Search/ActionCell.tsx#L53
 - update translations

Do you see any bigger changes required @luacmartins ? Would we need any confirmation modals or similar redirects? because that is usually the biggest amount of work and code changes.

If its not too much work then I would happily do a PR tomorrow, inbetween doing the tasks for Search v2

**Comment by luacmartins** [comment] 2024-07-11 15:40
I don't think there would be any redirect, no. @JmillsExpensify can you confirm if submitting, approving and paying transactions from the Search page should display any modals or ask for more information? Maybe the `Pay` button if the user doesn't have a default payment set?

**Comment by greg-schroeder** [comment] 2024-07-16 21:42
bump @JmillsExpensify on the above, can you help confirm Carlos' expectation?

**Comment by JmillsExpensify** [comment] 2024-07-17 17:48
Here's the case: 

 - Employee submits a report
 - First manager puts a couple of reports on hold
 - First manager gets distracted doesn't approve the report
 - First manager comes back to the report on the search page, clicks `Approve`
 - We need to ask the manager whether we approve the entire report, or just part of the report. 
 
 Does that make sense?

**Comment by luacmartins** [comment] 2024-07-18 15:39
So it sounds like we do need to show modals for other cases too. Do we have these flows that require modals mapped out somewhere?

**Comment by JmillsExpensify** [comment] 2024-07-18 16:28
The only case I can think of is the Hold case. @trjExpensify do any others come to mind?

**Comment by trjExpensify** [comment] 2024-07-23 00:36
I'm not 100% following the question. Is it asking about when a centered modal might appear when taking an action on a report/expense row in the Search results?

**Comment by luacmartins** [comment] 2024-07-23 01:58
Correct. Which actions taken from the Search page, i.e. `Hold, Unhold, Delete, Submit, Approve, Pay` require us to show a centered confirmation modal?

**Comment by trjExpensify** [comment] 2024-07-23 13:23
Okay, got it. 

- `Approve` and `Pay` - both conceivably have a centered alert modal to choose what to approve or pay when the report contains held expenses. That's because when the approver===reimburser, we show them the `Pay` button to avoid the double click of `Approve` then `Pay`. 

- `Delete` - this does show a "danger" centered confirmation modal to confirm the irreversible action. 

- `Hold` - putting something on hold doesn't have a centered confirmation modal, entering the reason for the hold is in a rightDockedSideModal ("RHP"). So yes, this one results in a modal after the action is taken, but not a centered confirmation modal. 

- `Submit` `Unhold` - no modals at all.

**Comment by luacmartins** [comment] 2024-07-23 15:01
Cool, thanks for confirming! 

>both conceivably have a centered alert modal to choose what to approve or pay when the report contains held expenses. 

do you know if this exists in App already?

**Comment by trjExpensify** [comment] 2024-07-23 19:41
Yeah, that's been in place since the collect-approvers wave. Marco implemented it. 👍

**Comment by luacmartins** [comment] 2024-07-25 14:36
Nice, thanks for confirming.

**Comment by luacmartins** [comment] 2024-08-07 17:13
Ah yea, gonna assign you too since you reviewed the PR https://github.com/Expensify/App/pull/41725

**Comment by luacmartins** [comment] 2024-08-07 17:14
Also, I think this issue is done. We're missing the bulk actions, but we have separate issues for those, e.g. https://github.com/Expensify/App/issues/46072, https://github.com/Expensify/App/issues/46074

**Comment by greg-schroeder** [comment] 2024-08-08 10:41
Processing

**Comment by greg-schroeder** [comment] 2024-08-08 10:47
Okay, got it, thank you

**Comment by eh2077** [comment] 2024-08-08 11:01
My case is similar - I helped to review this PR https://github.com/Expensify/App/pull/41725 and there's no automation to track the payment.

**Comment by luacmartins** [comment] 2024-08-08 13:25
>Processing - are there other payments I need to make here? This issue is a bit difficult to follow 😅

I think only the payments to @ishpaul777 and @eh2077 as mentioned in the summary [here](https://github.com/Expensify/App/issues/39890#issuecomment-2274041393)

**Comment by greg-schroeder** [comment] 2024-08-12 10:09
Okay got it, processing, sorry for delay

**Comment by greg-schroeder** [comment] 2024-08-12 12:34
Offers sent to @eh2077 and @ishpaul777

**Comment by greg-schroeder** [comment] 2024-08-12 12:34
I'll pay these ASAP as soon as you accept 👍

**Closed by greg-schroeder** 2024-08-12 12:34 UTC
Labels: External, Daily, NewFeature, Awaiting Payment

**Comment by eh2077** [comment] 2024-08-12 13:33
@greg-schroeder Offer accepted, thank you!

**Comment by greg-schroeder** [comment] 2024-08-12 13:44
? That's... weird. I definitely didn't withdraw it, lol

**Comment by greg-schroeder** [comment] 2024-08-12 13:45
Upwork is a very good program. I will try again

**Comment by greg-schroeder** [comment] 2024-08-12 13:52
Re-sent
