### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250] Emojis - Large emoji is cut off in preview on iOS and Android app

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40535] opened 2024-04-19 09:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR:** https://github.com/Expensify/App/pull/39597
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Access the New Expensify app
2. Sign into a valid account
3. Go to any chat
4. Send an Emoji on iOS or Android (Notice that the emoji will be enlarged before typing anything, but if it is not, type a couple of letters to get the emoji to switch sizes)

## Expected Result:
User expects the Emoji to fit in the text box

## Actual Result:
The emoji is cut in half

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f15fdb07-72c8-4fb6-9fa8-a55f68757e25

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed0b5667ecd2ce23</li>
        <li>Upwork Job ID: 1782357324514742272</li>
        <li>Last Price Increase: 2024-04-22</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-19 09:22
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-04-19 09:23
Production less cut off

![IMG_3200](https://github.com/Expensify/App/assets/115492554/39bf3340-ac60-4625-b8cd-e8954e6e31ba)

**Comment by thienlnam** [comment] 2024-04-20 01:10
Ah, this looks related to the recent emoji changes we added - cc @Skalakid

**Comment by thienlnam** [comment] 2024-04-20 01:10
Going to demote since this only happens if you send just emojis, but looks like something we should def fix

**Comment by Skalakid** [comment] 2024-04-22 10:43
cc @tomekzaw @robertKozik since they worked on live markdown native implementation

**Comment by robertKozik** [comment] 2024-04-25 07:24
Hi! I'll take over it

**Comment by laurenreidexpensify** [comment] 2024-04-25 10:15
Assigned to @robertKozik

**Comment by laurenreidexpensify** [comment] 2024-05-09 14:53
Payment Summary: 

- C+ - @Ollyws - offer sent in upwork $250 please accept thanks
- Contributor - @robertKozik does not require payment (Contractor)

**Comment by laurenreidexpensify** [comment] 2024-05-14 09:29
Payment Summary:

C+ - @Ollyws - paid in upwork $250
Contributor - @robertKozik does not require payment (Contractor)

No regression test as picked up in KI testing report by Applause

**Closed by laurenreidexpensify** 2024-05-14 09:29 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
