### ISSUE TITLE
[$500] Expense - Default avatar is displayed for expense report in LHN for user with custom avatar

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31692] opened 2023-11-22 12:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Precondition: User has a custom avatar.
1. Go to workspace chat > + > Request money.
2. Create a manual request.
3. Click on the expense preview to open the expense report.

## Expected Result:
The user avatar for the expense report in LHN shows the custom avatar.

## Actual Result:
The user avatar for the expense report in LHN shows the default avatar instead of the custom avatar.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/32fedbaf-7e3f-4e0f-9c55-e8cfbd6602cf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017598aca57b80b0c8</li>
        <li>Upwork Job ID: 1727300809820229632</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-11-22 17:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Default avatar display for expense chat
### What is the root cause of that problem?
We have this issue in many cases.
The root cause is that `participantAccountIDs` of some reports don't have `ownerAccountID`.
So we see default avatar instead of owner avatar

https://github.com/Expensify/App/assets/65789015/7797a609-8a6a-4b3c-8064-d1552bd72177

### What changes do you think we should make in order to solve the problem?
We need to add `ownerAccountID` to `participantAccountIDs`
Like this 
```
const participantsPersonalDetails = OptionsListUtils.getPersonalDetailsForAccountIDs(
       [...itemFullReport.participantAccountIDs, itemFullReport.ownerAccountID],
       personalDetails
);
```
https://github.com/Expensify/App/blob/0cca90ab9aa7fd9467ef45ca35c4d0ad3c3334ae/src/components/LHNOptionsList/LHNOptionsList.js#L120

https://github.com/Expensify/App/assets/65789015/25e00462-1c8e-4a7a-b7f8-d4745ad3f31c


### What alternative solutions did you explore? (Optional)

**Comment by peterdbarkerUK** [comment] 2023-11-24 14:13
Dupe of https://github.com/Expensify/App/issues/31284

**Closed by peterdbarkerUK** 2023-11-24 14:13 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
