### ISSUE TITLE
[HOLD for payment 2023-11-06] [$500] Dev - wider gap between mention or emoji suggestion box and composer

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26393] opened 2023-08-31 12:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Type ':' & start searching for emoji
3. Observe the gap between the suggestion box and the composer
4. Clear the composer & type '@'
5. Observe the gap between the suggestion box and the composer
## Expected Result: 
The margin between the suggestion box and the composer should be smaller
## Actual Result: 
The margin between the suggestion box and the composer is wider compared to the gap it has on staging

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ea54a25c-23f5-4933-afc3-d752896faee4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692990862094189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011eeb44265c91fc05</li>
        <li>Upwork Job ID: 1697231915838853120</li>
        <li>Last Price Increase: 2023-09-21</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26876537</li>
<li>natnael-guchima | Reporter | 26876542</li>
<li>Pujan92 | Contributor | 27301559</li>
</ul></li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-08-31 12:56
This is a regression but we're handling it as a normal `External` issue per team discussion in linked thread

**Comment by Pujan92** [comment] 2023-08-31 13:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Extra local time space between composer and suggestions

### What is the root cause of that problem?
We are providing a prop called `shouldIncludeReportRecipientLocalTimeHeight` to consider a height of local time which causes the suggestions to add that margin.

### What changes do you think we should make in order to solve the problem?
We can remove the prop for both(emoji/mention) suggestions to start exactly on top of the composer.

**Comment by Pujan92** [comment] 2023-08-31 13:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Extra local time space between composer and suggestions

### What is the root cause of that problem?
We are providing a prop called `shouldShowReportRecipientLocalTime` from the `ReportActionCompose` which will consider the  `shouldIncludeReportRecipientLocalTimeHeight` in the `AutoSuggestions` and that leads to giving that padding of that height which will decrease the top value and cause the issue.

https://github.com/Expensify/App/blob/dd71b38513990379ec8c8ea80531d9b4627b284c/src/styles/StyleUtils.js#L1074

https://github.com/Expensify/App/commit/3d4403e37dbdbb1e961ac96d3e5f0cc1dd4b8d2d#diff-eb38db48f3cc2cf1fc35a8e7d25d3624174802bc1fb213ba79419ea4f4656627R356


### What changes do you think we should make in order to solve the problem?
I think we can get rid of the `shouldShowReportRecipientLocalTime` prop and `shouldIncludeReportRecipientLocalTimeHeight` in AutoCompleteSuggestions as it seems not required now.

https://github.com/Expensify/App/blob/dd71b38513990379ec8c8ea80531d9b4627b284c/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L392

**Comment by greg-schroeder** [comment] 2023-09-04 12:22
Awaiting proposal review

**Comment by greg-schroeder** [comment] 2023-09-08 06:17
bump @abdulrahuman5196

**Comment by greg-schroeder** [comment] 2023-09-11 14:13
bump @abdulrahuman5196

**Comment by greg-schroeder** [comment] 2023-09-14 14:44
Are you able to take a look at this ASAP @abdulrahuman5196 ?

**Comment by Pujan92** [comment] 2023-09-16 08:35
@abdulrahuman5196 can you plz review my [proposal](https://github.com/Expensify/App/issues/26393#issuecomment-1701058009)

**Comment by greg-schroeder** [comment] 2023-09-18 10:48
bump @abdulrahuman5196

**Comment by greg-schroeder** [comment] 2023-09-25 07:20
Bump @abdulrahuman5196

**Comment by greg-schroeder** [comment] 2023-09-26 04:48
Re-adjusting C+ to someone with a bit more bandwidth!

**Comment by situchan** [comment] 2023-09-26 05:02
> Please hold on #27771. It removes `shouldShowReportRecipientLocalTime`

Makes sense

**Comment by situchan** [comment] 2023-09-26 05:02
@Pujan92 are you able to find offending PR which caused this regression?

**Comment by Pujan92** [comment] 2023-09-26 05:08
@situchan it is from https://github.com/Expensify/App/pull/25758

**Comment by situchan** [comment] 2023-09-26 05:10
Let's wait until #27771 is merged. After that, you might need to update proposal based on latest codebase.

**Comment by Pujan92** [comment] 2023-09-26 10:38
@situchan updated proposal as the other PR gets merged.

**Comment by situchan** [comment] 2023-09-26 11:09
@Pujan92 your solution doesn't work on native

**Comment by situchan** [comment] 2023-09-26 11:10
@greg-schroeder can we remove `Needs Reproduction` label, remove `Dev - ` in issue title and add `Help Wanted` label?

**Comment by Pujan92** [comment] 2023-09-26 11:52
> @Pujan92 your solution doesn't work on native

Yes, I have updated the proposal again accordingly. Thanks!

**Comment by situchan** [comment] 2023-09-26 12:05
@Pujan92 make sure that offline feedback is only for local time display. And it doesn't affect composer, suggestions and typing indicator.

**Comment by Pujan92** [comment] 2023-09-26 12:35
Isn't it needed for the entire View when there is some pending action?(I am seeing it for all) 

https://github.com/Expensify/App/assets/14358475/9351135a-5e2b-4400-8d08-31e9ce8d516a

**Comment by situchan** [comment] 2023-09-26 12:37
> Isn't it needed for the entire View when there is some pending action?(I am seeing it for all)
> 
>  Screen.Recording.2023-09-26.at.18.04.24.mov

So you're saying that your solution will cause regression, right?

**Comment by Pujan92** [comment] 2023-09-26 12:39
I just shared the existing main branch screencast where offline feedback is applied to all.  

> @Pujan92 make sure that offline feedback is only for local time display. And it doesn't affect composer, suggestions and typing indicator.

Replying to this I am saying isn't offline feedback should affect all instead of just local time display.

**Comment by Pujan92** [comment] 2023-09-27 04:49
> @Pujan92 make sure that offline feedback is only for local time display. And it doesn't affect composer, suggestions and typing indicator.

I think this makes sense to avoid offline feedback(reduce opacity) for the mentioned parts but we don't have that logic in the current implementation, so I haven't covered it in my proposal.

**Comment by greg-schroeder** [comment] 2023-10-02 02:50
bump @situchan on the above!

**Comment by greg-schroeder** [comment] 2023-10-04 16:00
bump @situchan

**Comment by situchan** [comment] 2023-10-04 16:07
@Pujan92 after applying your solution, all of these will be out of OfflineWithFeedback:
suggestions, offline indicator, exceeded comment length

Let's make sure that those views are not affected after removing offline feedback

**Comment by Pujan92** [comment] 2023-10-05 14:08
> OfflineWithFeedback -> ParticipantLocalTime
> View -> PortalHost -> OfflineWithFeedback -> rest content

I assume you are referring this, but as per the order only PortalHost we are taking out due to suggestions should not reduce opacity as per the this [transparent suggestions fix PR](https://github.com/Expensify/App/pull/27771). So your mentioned parts(offline indicator, exceeded comment length) won't be out from `OfflineWithFeedback`

**Comment by greg-schroeder** [comment] 2023-10-10 16:23
Thoughts on the above comment @situchan?

**Comment by situchan** [comment] 2023-10-10 16:56
@Pujan92 can you please share test branch? I wanna do regression test before approval stamp

**Comment by greg-schroeder** [comment] 2023-10-13 19:13
Waiting for test branch

**Comment by greg-schroeder** [comment] 2023-10-16 14:45
Same as above bump @Pujan92

**Comment by Pujan92** [comment] 2023-10-18 08:35
Sorry for the delay. 
@situchan test branch is here [fix/26393](https://github.com/Pujan92/App/tree/fix/26393).

**Comment by situchan** [comment] 2023-10-20 13:04
@Pujan92's [proposal](https://github.com/Expensify/App/issues/26393#issuecomment-1701058009) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by francoisl** [comment] 2023-10-20 21:36
👍 proposal looks good to me

**Comment by greg-schroeder** [comment] 2023-10-23 10:19
Not overdue, awaiting PR to be opened

**Comment by Pujan92** [comment] 2023-10-24 02:41
@situchan [PR](https://github.com/Expensify/App/pull/30226) is ready for review!

**Comment by greg-schroeder** [comment] 2023-11-07 19:11
Working on payments now

**Comment by situchan** [comment] 2023-11-07 19:23
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/25758
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/25758#issuecomment-1799671921
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This is minor style issue and caused by big composer refactor, I don't see the need of new regression test. Users can still chat, mention users and send emoijs.

**Comment by greg-schroeder** [comment] 2023-11-09 11:00
Payments made now, filing regression test per above

**Closed** 2023-11-09 11:10 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
