### ISSUE TITLE
[$500] Category & Tag - No red dot in expense preview and LHN for reports containing missing item

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34583] opened 2024-01-16 15:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace on Old Dot
- Collect workspace has set category and tag to "Require"
1. Go to workspace chat
2. Create a manual request without category and tag
3. Go to request details page

## Expected Result:
Since there is a red dot next to Category and Tag in request details page, there should be a red dot in expense preview and also in LHN for request details report

## Actual Result:
There is no red dot in expense preview and also in LHN for request details report that has missing Category and Tag

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d9823fd7-5a65-466c-a1db-20e6affdaf3f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177d7754be628a53d</li>
        <li>Upwork Job ID: 1747272895104839680</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2024-01-16 15:24
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
There is no red dot in expense preview and also in LHN for request details report that has missing Category and Tag

## What is the root cause?
We are not checking for those fields in the `TransactionUtils.areRequiredFieldsEmpty` method here:
https://github.com/Expensify/App/blob/0798ed7d05300a790a25a490c0fc63e760b49aa8/src/libs/TransactionUtils.ts#L158-L162

## What changes should be made?
We should add methods like `isCategoryMissing` and `isTagMissing` just like we do for amount and created here:
https://github.com/Expensify/App/blob/0798ed7d05300a790a25a490c0fc63e760b49aa8/src/libs/TransactionUtils.ts#L150-L156
We can then use the methods in the `TransactionUtils.areRequiredFieldsEmpty`

**Comment by amyevans** [comment] 2024-01-16 19:19
cc @cead22 since it's violations related

**Comment by cead22** [comment] 2024-01-16 20:21
Thanks @amyevans 

> There is no red dot in expense preview and also in LHN for request details report that has missing Category and Tag

This is true, but the PR that implements that functionality isn't merged yet, so closing for now

**Closed by cead22** 2024-01-16 20:21 UTC
Labels: External, Daily, Help Wanted, Bug
