### ISSUE TITLE
[$4000] The last line of the message is not visible when we close the expanded message view of the compose box

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13622] opened 2022-12-15 15:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open IOS app and login
2. Open any chat
3. Enter 3+ lines of text in expanded form
4. Close the expanded view

## Expected Result:
The last line of the message should be visible when we close the advanced message view

## Actual Result:
The last line of the message is not visible when we close the advanced message view

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.4-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/207904844-4145917d-1c09-4eac-8423-352047541d0f.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128082759019a32b0</li>
        <li>Upwork Job ID: 1603795713760645120</li>
        <li>Last Price Increase: 2022-12-30</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2022-12-16 15:05
I can reproduce 👍

**Comment by pecanoro** [comment] 2022-12-16 16:53
So what we want is for the focus to be on the last line after closing the expanded view as we do for Android! Assigning External.

**Comment by abdulrahuman5196** [comment] 2022-12-16 17:33
Proposal:
We can make the Composer focus() incase of collapse button click. We can also focus() on expand as well to cover any edge cases

Solution:```


--- a/src/pages/home/report/ReportActionCompose.js
+++ b/src/pages/home/report/ReportActionCompose.js
@@ -564,6 +564,7 @@ class ReportActionCompose extends React.Component {
                                                             onPress={(e) => {
                                                                 e.preventDefault();
                                                                 Report.setIsComposerFullSize(this.props.reportID, false);
+                                                                this.textInput.focus();
                                                             }}
 
                                                             // Keep focus on the composer when Collapse button is clicked.
@@ -583,6 +584,7 @@ class ReportActionCompose extends React.Component {
                                                             onPress={(e) => {
                                                                 e.preventDefault();
                                                                 Report.setIsComposerFullSize(this.props.reportID, true);
+                                                                this.textInput.focus();
                                                             }}
 
                                                             // Keep focus on the composer when Expand button is clicked.
```

**Comment by priyeshshah11** [comment] 2022-12-17 07:10
## Proposal

### Problem

This issue persists on all platforms as the issue is caused due to the `componentDidUpdate` in Composer.js where we unnecessary call `updateNumberOfLines` when the `isFullComposerView` is toggled which causes it to rerender and resets the scroll position to start from top.

### Solution - Works for all platforms

Do not call `updateNumberOfLines` when `isFullComposerView` is toggled as there is no change in number of lines. This fixes the problem of automatically scrolling to the top and stays where it was when the `isFullComposerView` was toggled. However, this doesn't scroll to the end in web if the selection was towards the end before toggling, thus the solution is to always scroll to the end and set the selection to the end whenever the fullComposerView is closed on web.

```diff
diff --git a/src/components/Composer/index.js b/src/components/Composer/index.js
index 34046295f..d4563fcc8 100755
--- a/src/components/Composer/index.js
+++ b/src/components/Composer/index.js
@@ -152,8 +152,7 @@ class Composer extends React.Component {
         }
 
         if (prevProps.value !== this.props.value
-            || prevProps.defaultValue !== this.props.defaultValue
-            || prevProps.isComposerFullSize !== this.props.isComposerFullSize) {
+            || prevProps.defaultValue !== this.props.defaultValue) {
             this.updateNumberOfLines();
         }
 
diff --git a/src/pages/home/report/ReportActionCompose.js b/src/pages/home/report/ReportActionCompose.js
index 7811d1c25..62c2c87ab 100644
--- a/src/pages/home/report/ReportActionCompose.js
+++ b/src/pages/home/report/ReportActionCompose.js
@@ -130,6 +130,7 @@ class ReportActionCompose extends React.Component {
         this.getInputPlaceholder = this.getInputPlaceholder.bind(this);
         this.getIOUOptions = this.getIOUOptions.bind(this);
         this.addAttachment = this.addAttachment.bind(this);
+        this.resetFocus = this.resetFocus.bind(this);
 
         this.comment = props.comment;
         this.shouldFocusInputOnScreenFocus = canFocusInputOnScreenFocus();
@@ -509,6 +510,16 @@ class ReportActionCompose extends React.Component {
         this.props.onSubmit(comment);
     }
 
+    /**
+     * Refocusing the input keeps the cursor in view on mobile.
+     */
+    resetFocus() {
+        this.textInput.blur();
+        this.textInput.focus();
+    }
+
     render() {
         // Waiting until ONYX variables are loaded before displaying the component
         if (_.isEmpty(this.props.personalDetails)) {
@@ -566,6 +577,24 @@ class ReportActionCompose extends React.Component {
                                                             onPress={(e) => {
                                                                 e.preventDefault();
                                                                 Report.setIsComposerFullSize(this.props.reportID, false);
+
+                                                                // Pointer goes out of sight when isComposerFullSize is toggled.
+                                                                // Refocusing the input keeps the cursor in view on mobile.
+                                                                this.resetFocus();
+                                                                InteractionManager.runAfterInteractions(() => {
+                                                                    // Reseting the focus does not bring the cursor insight on web.
+                                                                    // Thus, we scroll to bottom and move the cursor to the end on web.
+                                                                    if (this.props.isSmallScreenWidth) { return; }
+                                                                    this.textInput.scrollTo({
+                                                                        top: this.textInput.scrollHeight,
+                                                                    });
+                                                                    this.setState({
+                                                                        selection: {
+                                                                            start: this.comment.length,
+                                                                            end: this.comment.length,
+                                                                        },
+                                                                    });
+                                                                });
                                                             }}
 
                                                             // Keep focus on the composer when Collapse button is clicked.
@@ -585,6 +614,7 @@ class ReportActionCompose extends React.Component {
                                                             onPress={(e) => {
                                                                 e.preventDefault();
                                                                 Report.setIsComposerFullSize(this.props.reportID, true);
+                                                                this.resetFocus();
                                                             }}
```

@mollfpr @pecanoro

**Comment by s77rt** [comment] 2022-12-17 17:41
### Proposal
1. Implement [scrollRangeToVisible](https://developer.apple.com/documentation/uikit/uitextview/1618613-scrollrangetovisible?language=objc) on RN
2. Use the implemented method e.g. `scrollRangeToVisible(this.state.selection)`

**Comment by mollfpr** [comment] 2022-12-18 06:30
Thanks for the proposals!

@abdulrahuman5196 [proposal](https://github.com/Expensify/App/issues/13622#issuecomment-1355278334) and @priyeshshah11 [proposal](https://github.com/Expensify/App/issues/13622#issuecomment-1356080439) is similar but @priyeshshah11 add mWeb case.

I don't think blurring and focusing the input when collapsing/expanding the composer is what we are looking for. It's seems doesn't have a problem in iOS but in Android, the keyboard is closed and opened when collapsing the composer, I don't think we want that.

https://user-images.githubusercontent.com/25520267/208284721-9bc60e25-39fe-4034-9ff1-f4f2227ee2ab.mov

**Comment by priyeshshah11** [comment] 2022-12-18 06:41
> Thanks for the proposals!
> 
> @abdulrahuman5196 [proposal](https://github.com/Expensify/App/issues/13622#issuecomment-1355278334) and @priyeshshah11 [proposal](https://github.com/Expensify/App/issues/13622#issuecomment-1356080439) is similar but @priyeshshah11 add mWeb case.
> 
> I don't think blurring and focusing the input when collapsing/expanding the composer is what we are looking for. It's seems doesn't have a problem in iOS but in Android, the keyboard is closed and opened when collapsing the composer, I don't think we want that.
> 
>  Screen.Recording.2022-12-18.at.13.17.29.mov

Ok @mollfpr as this issue does not occur on android, how about we reset focus in `componentDidUpdate` in `Composer/index.ios.js` when `isComposerFullSize` is toggled which will not affect the behaviour in android and fix it elsewhere?

**Comment by abdulrahuman5196** [comment] 2022-12-18 06:44
@mollfpr Exactly, thats why i mentioned in the note we can only make this blue and focus change for iOS alone(safari as well if required) as in other platforms it will cause flickering of keyboard which I noticed on testing other platforms. But as far as I know we don't require fix for Android or chrome as I am unable to repro this issue there as pointed in issue detail, correct me if I am wrong if others are able to reproduce in other platforms.
I was checking react native docs on why this issue is happening only for iOS but couldn't find any relevant information.

**Comment by mollfpr** [comment] 2022-12-18 06:59
@priyeshshah11 @abdulrahuman5196 Thank you!

I'm still thinking your proposals still a workaround because it's not happening on Android. My suggestion is we try to find what the root cause is and if it's a bug on RN, we should try to fix it upstream. But it is in our code we should address what is wrong with it and how we should do it correctly.

cc @pecanoro

**Comment by priyeshshah11** [comment] 2022-12-18 08:00
@mollfpr yes you're right, it's a workaround but I think this workaround should be fine in this case as this happens on web too. This is a known issue in the outside world without a fix. It occurs due to the adding/removing of the scroll element when the visible content size changes. It seems like web (html) & native iOS do not automatically scroll to the selection but andorid does. Thus, we do this by refocusing the TextInput. 

This has also been implemented in the paste function in Composer/index.js (I know it's not necessary to implement something if we have already done it somewhere else but in this case I think there's a good case to do it)

cc @pecanoro

**Comment by priyeshshah11** [comment] 2022-12-18 08:58
## Proposal 2 - Initial proposal [here](https://github.com/Expensify/App/issues/13622#issuecomment-1356080439)

@mollfpr @pecanoro Based on my comments above, here is the updated solution which works well for all platforms

```diff
diff --git a/src/components/Composer/index.ios.js b/src/components/Composer/index.ios.js
index b31a5b462..03ca2c7f7 100644
--- a/src/components/Composer/index.ios.js
+++ b/src/components/Composer/index.ios.js
@@ -83,6 +83,13 @@ class Composer extends React.Component {
     }
 
     componentDidUpdate(prevProps) {
+        if (prevProps.isComposerFullSize !== this.props.isComposerFullSize && !this.props.isComposerFullSize) {
+            // Pointer goes out of sight when isComposerFullSize is toggled off.
+            // Refocusing the input keeps the cursor in view on mobile.
+            this.textInput.blur();
+            this.textInput.focus();
+        }
+
         if (prevProps.shouldClear || !this.props.shouldClear) {
             return;
         }
diff --git a/src/components/Composer/index.js b/src/components/Composer/index.js
index 34046295f..9cfec9ed6 100755
--- a/src/components/Composer/index.js
+++ b/src/components/Composer/index.js
@@ -161,6 +161,13 @@ class Composer extends React.Component {
             // eslint-disable-next-line react/no-did-update-set-state
             this.setState({selection: this.props.selection});
         }
+
+        if (prevProps.isComposerFullSize !== this.props.isComposerFullSize) {
+            // Pointer goes out of sight when isComposerFullSize is toggled.
+            // Refocusing the input keeps the cursor in view on mobile.
+            this.textInput.blur();
+            this.textInput.focus();
+        }
     }
 
     componentWillUnmount() {
diff --git a/src/pages/home/report/ReportActionCompose.js b/src/pages/home/report/ReportActionCompose.js
index 7811d1c25..851de25e3 100644
--- a/src/pages/home/report/ReportActionCompose.js
+++ b/src/pages/home/report/ReportActionCompose.js
@@ -566,6 +566,21 @@ class ReportActionCompose extends React.Component {
                                                             onPress={(e) => {
                                                                 e.preventDefault();
                                                                 Report.setIsComposerFullSize(this.props.reportID, false);
+
+                                                                // The cursor goes out of sight on web when the composer's height is changed.
+                                                                // Thus, we scroll to the bottom and move the cursor to the end.
+                                                                if (this.props.isSmallScreenWidth) { return; }
+                                                                InteractionManager.runAfterInteractions(() => {
+                                                                    this.textInput.scrollTo({
+                                                                        top: this.textInput.scrollHeight,
+                                                                    });
+                                                                    this.setState({
+                                                                        selection: {
+                                                                            start: this.comment.length,
+                                                                            end: this.comment.length,
+                                                                        },
+                                                                    });
+                                                                });
                                                             }}
```

**Comment by aneequeahmad** [comment] 2022-12-19 02:07
### PROPOSAL

**ROOT CAUSE**

After debugging for quite sometime i figured out the following:

- On IOS -  if the last typed character is emoji the last line of message is visible when we close the expanded message view of the compose box(`ScreenRecording is attached below`). 

- On IOS - if the last typed character is emoji the last line of message is not visible when we close the expanded view.

**Screen Recording:** 

https://user-images.githubusercontent.com/36359331/208330421-ac2b87f3-48c7-4156-9b9b-587cd98f3972.mov


**Explanation:**

Why last line is visible in case of emoji ?

As when emoji is selected from the the emojiPicker we first add the emoji to the text box update state and comment and then we set the focus on text input using the prop ` onModalHide={() => this.focus(true)}` which sets the focus at the right point of the text input and that's why the last line is visible. 

Whereas, when the last typed char is anything other than emoji multiple states are updated and focus is already set and doesn't focus to the end of the line. There was the same issue with Android but was fixed [here](https://github.com/facebook/react-native/issues/15778) quite a while ago. 


**SOLUTION**



The quickest and simplest solution would be to add IOS specific check for this use case in `OnPress` of collapse here
https://github.com/Expensify/App/blob/ecb60196794be5acbe835f22f45e5c74c77461b6/src/pages/home/report/ReportActionCompose.js#L565-L571

_Updated code will be:_ 

```

   onPress={(e) => {
        e.preventDefault();
       isIOS  &&  this.textInput.blur();
        Report.setIsComposerFullSize(this.props.reportID, false);
        isIOS  && this.focus();
    }}
```

**Comment by mollfpr** [comment] 2022-12-19 16:25
>After debugging for quite sometime i figured out the following:
> - On IOS - if the last typed character is emoji the last line of message is visible when we close the expanded message view of the compose box(ScreenRecording is attached below).
> - On IOS - if the last typed character is emoji the last line of message is not visible when we close the expanded view.



@aneequeahmad I confuse with your analysis, both statements say _**if the last typed character is emoji the last line of message**_ but have different results?

Btw, I just tested with the last line as emoji, the input is not scrolled to the cursor.

https://user-images.githubusercontent.com/25520267/208472350-8393c035-ce4a-454f-bf87-d1f1aae47626.mov

---

@priyeshshah11 Let's wait for @pecanoro thoughts on applying the workaround to this issue.

**Comment by aneequeahmad** [comment] 2022-12-19 18:15
@mollfpr Ahhhhh yes apologies i just corrected the analysis

> On IOS - if the last typed character is emoji the last line of message is visible when we close the expanded message view of the compose box(ScreenRecording is attached below).

> On IOS - if the last typed character is any alphabet or character other than emoji the last line of message is not visible when we close the expanded view.

Oh the behavior mentioned is when soft keyboard is not opened and even than the the last line visible indicates that the focus is happening right and that is why it scrolls and the focused point is in sight.

Have you seen the explanation and tried the solution ? Solution is simple and fixes the issue on IOS



https://user-images.githubusercontent.com/36359331/208492518-7f281209-c685-4fde-8de9-c7a91aeee43f.mov

**Comment by s77rt** [comment] 2022-12-19 18:49
@mollfpr Can I get a feedback on my [proposal](https://github.com/Expensify/App/issues/13622#issuecomment-1356351213)?

Do I have to actually write code for that proposal?

However, since the issue may actually exist on Android too (and every other platform) we need to make sure there is a similar method on Android.

**Comment by abdulrahuman5196** [comment] 2022-12-19 19:45
@mollfpr Although I agree this may seem as a workaround solution to refocus the text input, i am unable to find any relevant docs or information even in the react native docs related to this issue. I am not sure we would get immediate traction on this. 
My suggestion would be to make the change for iOS and fix the issue, while we can cut a issue to RN and have them debug on their end(might be a long poll)

**Comment by aneequeahmad** [comment] 2022-12-19 20:15
@s77rt I have tested this issue only exists on IOS. Android is working fine as there was issue on android and it was fixed please see this [link](https://github.com/facebook/react-native/issues/15778).

**Comment by s77rt** [comment] 2022-12-19 21:10
In this case, I think we need to locate the issue
- Is it in iOS? (iOS does not have this feature that Android has)
- In react native
- In Expensify/App

And for that we need a minimal example to test with in each case.

**Comment by bernhardoj** [comment] 2022-12-20 03:44
It happens on iOS and web.

**Comment by aneequeahmad** [comment] 2022-12-21 03:59
@bernhardoj You're right it also happens on web and my [propopsal](https://github.com/Expensify/App/issues/13622#:~:text=onPress%3D%7B(e)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20e.preventDefault()%3B%0A%20%20%20%20%20%20%20isIOS%20%20%26%26%20%20this.textInput.blur()%3B%0A%20%20%20%20%20%20%20%20Report.setIsComposerFullSize(this.props.reportID%2C%20false)%3B%0A%20%20%20%20%20%20%20%20isIOS%20%20%26%26%20this.focus()%3B%0A%20%20%20%20%7D%7D) fixes in all cases.

**Comment by s77rt** [comment] 2022-12-21 12:01
@aneequeahmad Your solution is to refocus the input right?
What about on Android, does it work without explicitly refocusing the input?

**Comment by aneequeahmad** [comment] 2022-12-21 12:35
@s77rt Yeah, i cant think of any other way to get the focus in sight other than this simple solution. 
What's wrong in this approach ? It isn't complicated and also it doesn't have any chance to cause regressions right ?

**Comment by s77rt** [comment] 2022-12-21 12:37
I'm concerned about Android, it works on Android just fine without the focus solution, right?

**Comment by bernhardoj** [comment] 2022-12-21 12:46
I think it just the different native behavior between platforms when the text input number of lines/height is changed and only Android keeps the scroll position. If you check on LinkedIn chat (web), you can type 5 lines and scroll to bottom, then expand and collapse it. You will see the scroll position will reset to top (it's hard to notice actually).

So, I think the workaround by refocus the input is not that bad?

Just giving my opinion.

**Comment by s77rt** [comment] 2022-12-21 14:26
> I think it is just the different native behavior between platforms

That's what I'm trying to be sure of, maybe it's not, maybe it's a bug on RN

**Comment by mollfpr** [comment] 2022-12-21 15:18
Okay, it's reproducible on the Web, mWeb, iOS, and Desktop.

@pecanoro current workaround is blurring and focusing the input when collapsing the composer but it might make the keyboard disappear and appear (currently I can only ensure this on Android).

My thoughts are: 
1. We close this and leave it as is
2. Accept the workaround
3. Waiting for more days to see if we have another solution

**Comment by priyeshshah11** [comment] 2022-12-21 15:25
> @pecanoro current workaround is blurring and focusing the input when collapsing the composer but it might make the keyboard disappear and appear (currently I can only ensure this on Android).

@mollfpr [This proposal](https://github.com/Expensify/App/issues/13622#issuecomment-1356741379) avoids the keyboard disappearing and re-appearing on android (and basically all platforms as it only happens on android)

**Comment by mollfpr** [comment] 2022-12-21 15:38
@priyeshshah11 Thanks for pointing that out!

Let's wait for @pecanoro thoughts and I'll review all the proposals later.

---

>@mollfpr Can I get a feedback on my https://github.com/Expensify/App/issues/13622#issuecomment-1356351213?
>
>Do I have to actually write code for that proposal?
>
>However, since the issue may actually exist on Android too (and every other platform) we need to make sure there is a similar method on Android.

@s77rt It's better if you provide a code proposal either it's for the implementation you mention or in our codebase.

---

One last thing, let's have a constructive discussion about this issue. Thank you!

**Comment by s77rt** [comment] 2022-12-21 16:46
I can replicate this on Android too

https://user-images.githubusercontent.com/16493223/208958756-475e88c0-02dc-47d2-962e-c5c2b8dd8d2d.mp4

**Comment by mollfpr** [comment] 2022-12-21 16:49
>Okay, it's reproducible on the Web, mWeb, iOS, and Desktop.

@s77rt Your video is from mWeb, right? Is it reproducible on the Android app?

**Comment by s77rt** [comment] 2022-12-21 16:59
@mollfpr Sorry my bad, I was working on something else on mWeb Android, I thought to take the chance to test this issue on, yet was testing on mWeb instead of native

On Android it's working as expected

https://user-images.githubusercontent.com/16493223/208961658-d3bb5234-3de6-42ca-ba51-a6bfe21aaebe.mp4

**Comment by aneequeahmad** [comment] 2022-12-21 18:29
Like i said about Android [There was the same issue with Android but was fixed quite a while ago](https://github.com/Expensify/App/issues/13622#:~:text=There%20was%20the%20same%20issue%20with%20Android%20but%20was%20fixed%20here%20quite%20a%20while%20ago) that's why it is working fine and i think IOS was fine when android issue was fixed but i'm not sure.

cc: @mollfpr, @s77rt

**Comment by s77rt** [comment] 2022-12-21 21:14
### Proposal
```diff
diff --git a/src/components/Composer/index.ios.js b/src/components/Composer/index.ios.js
index b31a5b462f..6d5e970892 100644
--- a/src/components/Composer/index.ios.js
+++ b/src/components/Composer/index.ios.js
@@ -83,6 +83,11 @@ class Composer extends React.Component {
     }
 
     componentDidUpdate(prevProps) {
+        if (prevProps.isComposerFullSize && !this.props.isComposerFullSize) {
+            this.textInput.setSelection(0, 0);
+            this.textInput.setSelection(this.props.selection.start, this.props.selection.end);
+        }
+
         if (prevProps.shouldClear || !this.props.shouldClear) {
             return;
         }
diff --git a/src/components/Composer/index.js b/src/components/Composer/index.js
index 34046295f1..336eda0b33 100755
--- a/src/components/Composer/index.js
+++ b/src/components/Composer/index.js
@@ -161,6 +161,14 @@ class Composer extends React.Component {
             // eslint-disable-next-line react/no-did-update-set-state
             this.setState({selection: this.props.selection});
         }
+
+        if (prevProps.isComposerFullSize && !this.props.isComposerFullSize) {
+            this.setState({}, () => {
+                this.textInput.blur();
+                this.textInput.focus();
+                this.textInput.setSelectionRange(this.props.selection.start, this.props.selection.end);
+            });
+        }
     }
 
     componentWillUnmount() {
```

### Details
If workarounds are acceptable in this issue, I have a better workaround

1. iOS: Resetting the selection instead of refocusing is enough.
2. web: Unfortunately resetting the selection is not enough, thus I'm refocusing


https://user-images.githubusercontent.com/16493223/209003316-7d2794f7-19f3-4545-84f2-b1eb5b414dd2.mp4

**Comment by pecanoro** [comment] 2022-12-22 12:50
Let's try to confirm first where this bug is coming from. After reading this, it seems this is a [bug](https://github.com/facebook/react-native/issues/15778) with react-native itself? If any of you can confirm, then we should open an issue there to get it fixed. If not, we definitely need to fix it here since the behaviour is pretty annoying to be honest 😄

**Comment by pecanoro** [comment] 2022-12-22 20:28
> @pecanoro the RN issue mentioned above is different to this bug. Auto scrolling when adding more lines in the composer is already working. The issue here is due to changing heights.

I know it's not the same bug, but both look extremely related. Either way, we still need to figure out first is this bug is coming from react-native or it's only us.

**Comment by allroundexperts** [comment] 2022-12-22 21:33
@pecanoro This is coming from React Native. And I don't think this has been reported before.

**Comment by s77rt** [comment] 2022-12-22 21:37
@allroundexperts If this is coming from React Native, can you confirm that this working fine using a simple iOS app?

**Comment by priyeshshah11** [comment] 2022-12-23 08:44
@mollfpr @pecanoro I don't think it's a bug (as far as RN is concerned), It's a bug in the Expensify app. From a RN POV, I feel it is working as expected, because if you look at `ScrollView`s, they do not bring the last known scrollOffset postion into the visible area of the view when we dynamically change/reduce the scrollView's height. 

We had a somewhat similar issue with `ScrollView` in #12198 where the height of the content inside the `ScrollView` was changing dynamically which caused the last message in the chat to be hidden/go out of the visible view area.
> Note: Even that issue was not happening in Android, which suggests that Android ScrollView is just better at remembering & scrolling to the last visible position.

The use case that we are after is "`TextInput` should scroll to the selection/cursor when its height changes" which is not a common use case which is why I guess it hasn't been reported before. Thus, I feel this needs to be fixed in Expensify & not in React Native.

**Comment by s77rt** [comment] 2022-12-23 10:10
@priyeshshah11 Let's first agree on how we define/locate bugs:
- You are clamming that this is a bug in Expensify App, this can only be true if it works fine on RN. Does it work in RN?
- If it does not work on RN, then it may be a bug in RN, but this can only be true if it works fine on native iOS App. Does it work in a native iOS App (no RN involved)?
- If it does not work on a native iOS App, then the bug is in iOS sdk (bug or an unrealised feature)

If the bug is in iOS itself, then any changes applied to RN or Expensify App will be either:
1. a workaround to fix the bug
2. a feature request

**Comment by mollfpr** [comment] 2022-12-23 16:09
https://snack.expo.dev/@mollfpr/textinput-cursor-position-not-visible

This snack is not accurate but just a simple replication of when the TextInput height is changed the cursor is not visible on iOS.

**Comment by priyeshshah11** [comment] 2022-12-23 16:12
> https://snack.expo.dev/@mollfpr/textinput-cursor-position-not-visible
> 
> This snack is not accurate but just a simple replication of when the TextInput height is changed the cursor is not visible on iOS.

Exactly, the same behaviour happens on LinkedIn messages which I think is a native iOS app (not 100% sure)

**Comment by s77rt** [comment] 2022-12-23 16:15
@mollfpr Thanks
We can confirm this is not a bug in Expensify App.

**Comment by priyeshshah11** [comment] 2022-12-23 16:17
> @mollfpr Thanks We can confirm this is not a bug in Expensify App.

Nor it is a bug in React Native or iOS. It is a new feature request.

**Comment by s77rt** [comment] 2022-12-23 16:23
The line between whether it's a bug or a feature request is thin in this case. Anyway, how can we processed now?
Implementing [scrollRangeToVisible](https://developer.apple.com/documentation/uikit/uitextview/1618613-scrollrangetovisible?language=objc) seems as an overkill at this point since we can replicate this behaviour with `setSelection`.

As for the web, I have no idea except to `blur`/`focus`

**Comment by mollfpr** [comment] 2022-12-23 16:30
@priyeshshah11 @s77rt I just try LinkedIn messages on iOS, and they also same have the same behavior as this issue. They also seem using Objective-C for the app (lookup on Quora).

Does anyone want to confirm the LinkedIn messages on Android? If the cursor is visible, then they should be bothered to fix the problem on iOS 🤷‍♂️.

cc @pecanoro

**Comment by s77rt** [comment] 2022-12-23 16:37
@mollfpr on Android it's working as expected, the cursor is visible

**Comment by mollfpr** [comment] 2022-12-25 08:26
>Let's try to confirm first where this https://github.com/facebook/react-native/issues/15778 is coming from. After reading this, it seems this is a bug with react-native itself? If any of you can confirm, then we should open an issue there to get it fixed. If not, we definitely need to fix it here since the behaviour is pretty annoying to be honest 😄

We have confirmed that the behavior on iOS and Android is different with simple a snack. I guess we can justify this as a bug in RN.

The next step will be to report the bug to RN or someone maybe can propose the solution to the upstream that would be great.

cc @pecanoro

**Comment by pecanoro** [comment] 2022-12-27 23:50
I have been out a couple of days for the holidays, catching up with the whole conversation tomorrow morning so we decide the next steps!

**Comment by pecanoro** [comment] 2022-12-30 17:48
I brought this up internally and since it's native behavior, we agreed that in general, we should not override native behavior. Because of that, I am going to close it. Thank you so much everyone who participated in this conversation!

**Closed by pecanoro** 2022-12-30 17:48 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug

**Comment by mallenexpensify** [comment] 2023-01-04 00:51
@mollfpr paid $1000 for C+ work, discussion [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1672675766512469)
