### ISSUE TITLE
[HOLD for payment 2024-10-16] [$250] Update beginningOfChatHistory for certain cases with fresh copy

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#47427] opened 2024-08-14 14:38 UTC
## Problem
New users often write in confused about how to use New Expensify. Key points of confusion still seem to be “How do I submit expenses?” or “How do I use this?” or are just unclear why they are looking at a chat platform. They then become frustrated or just leave us all together.

## Solution
Update the `beginningOfChatHistory` copy in all rooms to be clearer and more concise, as well as remove any noise around features that don’t lead to conversion.

P/S is also [here](https://expensify.slack.com/archives/C07JPSLTD0U/p1725399084220649?thread_ts=1724773606.387999&cid=C07JPSLTD0U) in Slack.

## Copy updates
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-bdbb33a2-7fff-03dc-b2ec-ea543fcd7329"><div dir="ltr" style="margin-left:0pt;" align="left">
Type | Current example | Proposed copy
-- | -- | --
Concierge | This is the beginning of your chat with Concierge. | This chat is with Concierge. Ask questions and get 24/7 realtime support.
DM (aka beginningOfChatHistory) | This is the beginning of your chat with Daniel Vidal. You can also use the + button to split an expense, submit an expense, pay expenses, or assign a task! | This chat is with [recipient]. Use the + button to split, submit, or pay an expense.
Group chat (can’t find this in the code) | This is the beginning of your chat with Anu, Daniel and James. | This chat is with [recipients that don't include you]. Use the + button to split an expense.
Workspace chat (aka beginningOfChatHistoryPolicyExpenseChat) | Collaboration between James Dean (Marketing/PR) and NewDot Test - Expensify US starts here! 🎉 This is the place to chat, submit expenses and settle up. You can also use the + button to split an expense, submit an expense, track an expense, or assign a task! | This is where [submitter] will submit expenses to [workspaceName]. Just use the + button.
#announce room (aka beginningOfChatHistoryAnnounceRoom) | Collaboration between all Expensify's Workspace 6 members starts here! 🎉 Use #announce to chat about anything Expensify's Workspace 6 related. | This chat is with everyone in [workspaceName]. Use it for the most important announcements.
#admins room (aka beginningOfChatHistoryAdminRoom) | Collaboration among james@expensify.com Small Business Expo admins starts here! 🎉 Use #admins to chat about topics such as workspace configurations and more. | This chat is with [workspaceName] admins. Use it to chat about workspace setup and more.
Domain room (aka beginningOfChatHistoryDomainRoom) | Collaboration with everyone at #expensify.com starts here! 🎉 Use #expensify.com to chat with colleagues, share tips, and ask questions. | This chat is with all Expensify members on the [domain] domain. Use it to chat with colleagues, share tips, and ask questions.
User-created room (aka beginningOfChatHistoryUserRoom) | Collaboration starts here! 🎉 Use this space to chat about anything #bravo-clubhouse related. | This chat room is for anything #[roomName] related. It was created by [displayName].
Invoice room (aka beginningOfChatHistoryInvoiceRoom) | Collaboration starts here! 🎉 Use this room to view, discuss, and pay invoices. | This chat is for invoices between [invoice sender/bill payer workspaceName] and [invoice/paid bill receiver workspaceName OR displayName]. Use the + button to send an invoice.

</div></b>

## Important
We need to make sure that the `beginningOfChatHistory` never gets replaced by a custom `roomDescription` if someone sets one. The `roomDescription` will instead be included/updated elsewhere (in the subheader). 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831355584440701165</li>
        <li>Upwork Job ID: 1831355584440701165</li>
        <li>Last Price Increase: 2024-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103838820</li>
<li>nkdengineer | Contributor | 104176525</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by danielrvidal** [comment] 2024-08-16 19:05
@jamesdeanexpensify, what do you think is still needed for this? Just to get an engineer to pick it up or do we need to keep fleshing out the proposal?

**Comment by jamesdeanexpensify** [comment] 2024-08-16 20:21
Just left you a comment in the doc, and then it would be great to get an engineer to pick it up and ask any remaining questions. I just thought you wanted to wait to house it under the F1 deadline.

**Comment by jamesdeanexpensify** [comment] 2024-08-19 16:05
@danielrvidal I think this is ready for an engineer whenever!

**Comment by danielrvidal** [comment] 2024-08-21 13:07
@jamesdeanexpensify now that this is in a whatsnext room/project, I imagine you should be able to recruit an engineer. I'm going to drop an update in the room but I think you should be good to go.

**Comment by jamesdeanexpensify** [comment] 2024-08-21 14:17
Posted [here](https://expensify.slack.com/archives/CC7NECV4L/p1724249837156849) as a next step!

**Comment by jamesdeanexpensify** [comment] 2024-09-03 21:20
Renewed the convo [here](https://expensify.slack.com/archives/C07JPSLTD0U/p1725387318000809?thread_ts=1724773606.387999&cid=C07JPSLTD0U).

**Comment by mariapeever** [comment] 2024-09-04 18:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update beginningOfChatHistory for certain cases with fresh copy #47427
### What is the root cause of that problem?
Current copy is not clear enough for new Expensify users.  
### What changes do you think we should make in order to solve the problem?
Update the current copy to match the proposed copy.
Updates to the language file (en.ts):
- [ ] Concierge - add a beginningOfChatHistoryConcierge property specific for Concierge just before beginningOfChatHistory.
- [ ] DM (aka beginningOfChatHistory) - update the beginningOfChatHistory property and add a participantNames param.
- [ ] Group chat - Count the participants' names for a group chat and re-use the beginningOfChatHistory property
		https://github.com/Expensify/App/blob/c885f96f66f4c552308fafb81b6251daf1fb4136/src/languages/en.ts#L603
		https://github.com/Expensify/App/blob/dc1407a56bfe70ee72e471c3733da9faa552590c/src/libs/SidebarUtils.ts#L530-L555

- [ ] Workspace chat (aka beginningOfChatHistoryPolicyExpenseChat) - Combine the beginningOfChatHistoryPolicyExpenseChat parts 1-3 into 1 and add parameters for participantName and policyName.
		- beginningOfChatHistoryPolicyExpenseChatPartOne
        	- beginningOfChatHistoryPolicyExpenseChatPartTwo
        	- beginningOfChatHistoryPolicyExpenseChatPartThree
        https://github.com/Expensify/App/blob/c885f96f66f4c552308fafb81b6251daf1fb4136/src/languages/en.ts#L604-L606
        https://github.com/Expensify/App/blob/dc1407a56bfe70ee72e471c3733da9faa552590c/src/libs/SidebarUtils.ts#L508-L513

- [ ] #announce room (aka beginningOfChatHistoryAnnounceRoom) - Combine the beginningOfChatHistoryAnnounceRoom parts 1-2 into 1 with a parameters for workspaceName and reportName.
		- beginningOfChatHistoryAnnounceRoomPartOne
        	- beginningOfChatHistoryAnnounceRoomPartTwo
      https://github.com/Expensify/App/blob/c885f96f66f4c552308fafb81b6251daf1fb4136/src/languages/en.ts#L597-L599
        https://github.com/Expensify/App/blob/dc1407a56bfe70ee72e471c3733da9faa552590c/src/libs/SidebarUtils.ts#L582-L584

- [ ] #admins room (aka beginningOfChatHistoryAdminRoom) - Combine the beginningOfChatHistoryAdminRoom parts 1-2 into 1 with a parameters for workspaceName and reportName.
		- beginningOfChatHistoryAdminRoomPartOne
        	- beginningOfChatHistoryAdminRoomPartTwo
       https://github.com/Expensify/App/blob/c885f96f66f4c552308fafb81b6251daf1fb4136/src/languages/en.ts#L595-L596
        https://github.com/Expensify/App/blob/dc1407a56bfe70ee72e471c3733da9faa552590c/src/libs/SidebarUtils.ts#L580-L581

- [ ] Domain room (aka beginningOfChatHistoryDomainRoom) - Combine the beginningOfChatHistoryDomainRoom parts 1-2 into 1 with a parameter for domainRoom.
		- beginningOfChatHistoryDomainRoomPartOne
        	- beginningOfChatHistoryDomainRoomPartTwo
        https://github.com/Expensify/App/blob/c885f96f66f4c552308fafb81b6251daf1fb4136/src/languages/en.ts#L593-L594
     https://github.com/Expensify/App/blob/dc1407a56bfe70ee72e471c3733da9faa552590c/src/libs/SidebarUtils.ts#L576-L578

- [ ] User-created room (aka beginningOfChatHistoryUserRoom) - Combine the beginningOfChatHistoryUserRoom parts 1-2 into 1 with a parameter for reportName.
		- beginningOfChatHistoryDomainRoomPartOne
        	- beginningOfChatHistoryDomainRoomPartTwo
    https://github.com/Expensify/App/blob/c885f96f66f4c552308fafb81b6251daf1fb4136/src/languages/en.ts#L593-L594
 https://github.com/Expensify/App/blob/dc1407a56bfe70ee72e471c3733da9faa552590c/src/libs/SidebarUtils.ts#L588-L591

- [ ] Invoice room (aka beginningOfChatHistoryInvoiceRoom) - Edit the beginningOfChatHistoryInvoiceRoom property and add params for invoice sender/bill payer workspaceName and invoice/paid bill receiver workspaceName OR displayName
			- beginningOfChatHistoryInvoiceRoom
     https://github.com/Expensify/App/blob/c885f96f66f4c552308fafb81b6251daf1fb4136/src/languages/en.ts#L602
        https://github.com/Expensify/App/blob/dc1407a56bfe70ee72e471c3733da9faa552590c/src/libs/SidebarUtils.ts#L585-L587

https://github.com/Expensify/App/blob/dc1407a56bfe70ee72e471c3733da9faa552590c/src/libs/SidebarUtils.ts#L593

### What alternative solutions did you explore? (Optional)
	N/A

**Comment by nkdengineer** [comment] 2024-09-04 18:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update beginningOfChatHistory for certain cases with fresh copy

### What is the root cause of that problem?
This is a new feature

### What changes do you think we should make in order to solve the problem?
- concierge chat, we can create a new translation for this one as per the description above or we can still use `beginningOfChatHistory` and create a new translation text for the additional text `Ask questions and get 24/7 realtime support.` and add it here if the report is concierge.

https://github.com/Expensify/App/blob/cb2bdf28addd44c3f0c265f55b8df948c2f9cfc8/src/components/ReportWelcomeText.tsx#L178

- DM chat and group chat, we can update `beginningOfChatHistory` translation as the description to `This chat is with` and then update `usePlusButton` to `\nUse the + button to ${additionalText}, or assign a task!`

https://github.com/Expensify/App/blob/cb2bdf28addd44c3f0c265f55b8df948c2f9cfc8/src/languages/en.ts#L603

https://github.com/Expensify/App/blob/cb2bdf28addd44c3f0c265f55b8df948c2f9cfc8/src/languages/en.ts#L613

OPTIONAL: We can remove `or assign a task` text.

- Policy expense chat: update three phrase `beginningOfChatHistoryPolicyExpenseChat` translations as the description

```
beginningOfChatHistoryPolicyExpenseChatPartOne: 'This is where ',
beginningOfChatHistoryPolicyExpenseChatPartTwo: ' will submit expenses to the ',
beginningOfChatHistoryPolicyExpenseChatPartThree: ' workspace. Just use the + button.',
```

https://github.com/Expensify/App/blob/cb2bdf28addd44c3f0c265f55b8df948c2f9cfc8/src/languages/en.ts#L604-L607

- Admin room and announce room: Update two phrase of the `beginningOfChatHistoryAnnounceRoom` translation and `beginningOfChatHistoryAdminRoom` as the description

https://github.com/Expensify/App/blob/cb2bdf28addd44c3f0c265f55b8df948c2f9cfc8/src/languages/en.ts#L595-L599


- Domain room: Update the `beginningOfChatHistoryDomainRoom` translation as the description with `domain` param is the `report.reportName`

https://github.com/Expensify/App/blob/cb2bdf28addd44c3f0c265f55b8df948c2f9cfc8/src/languages/en.ts#L593-L594


-  User-created room: Update two phrases the `beginningOfChatHistoryUserRoom` translation as the description

https://github.com/Expensify/App/blob/cb2bdf28addd44c3f0c265f55b8df948c2f9cfc8/src/languages/en.ts#L600-L601

- Invoice room: Update the `beginningOfChatHistoryInvoiceRoom` translation as the description with two extra params `invoice sender/bill payer workspaceName` is the display name of the user that is invited to the invoice room and `invoice/paid bill receiver workspaceName OR displayName` is the display name user that creates the send invoice or the workspace name of the workspace that we create the send invoice.

For all translations, we should update the all places that we use this translation if the param is changed.

> We need to make sure that the beginningOfChatHistory never gets replaced by a custom roomDescription if someone sets one. The roomDescription will instead be included/updated elsewhere (in the subheader).

We already have handled this in `getRoomWelcomeMessage` function

### What alternative solutions did you explore? (Optional)

**Comment by AsfandSoomro** [comment] 2024-09-05 10:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Update beginningOfChatHistory for certain cases with fresh copy

### What is the root cause of that problem?
Chat header message is not clear to new users

### What changes do you think we should make in order to solve the problem?
First of all we need to re-code all _beginningOfChatHistory(all)_ data in _reportActionsView_ object in a clear and consistent way. They all need to accept arguments if they need dynamic message so we can pass (e.g workspace name, recipient name, or multiple recipients names etc) rather than the current _PartOne PartTwo PartThree_ different keys. This will be more flexible and easier to change the message in future.
Something like this: ```welcomeToRoom: ({roomName}: WelcomeToRoomParams) => `Welcome to ${roomName}!`,```  
#### Files that will be affected
- src/languages/en.ts
- src/languages/es.ts
- src/libs/SidebarUtils.ts

#### My approach to solve the problem
- For **Concierge** create new key _beginningOfChatHistoryConcierge_ in _reportActionsView_ it won't accept any parameters, just static message. And in `getWelcomeMessage()` function figure out if the recipient name is Concierge since we don't have a Report util function like this `ReportUtils.isSelfDM(report)` to check if user is in chatroom with Concierge.
- For **DM** same key remains, just dynamic.
- For **Group Chat** new dynamic key _beginningOfChatHistoryGroupChat_. And in `getWelcomeMessage()` figure out the way to remove the name of the client user before the recipients names message constructor loop.   

Similar approach in all others. This way I think messages will be more flexible and easy to change in future as well.

P.S I have only explored Expensify code now and have not contributed to Open Source before. Still reading the contribution.md file

### What alternative solutions did you explore? (Optional)

**Comment by AsfandSoomro** [comment] 2024-09-05 10:52
Contributor details
Your Expensify account email: asfandsoomro13@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0184a98fdca35057cc

**Comment by ikevin127** [comment] 2024-09-05 22:16
Given this is a **copy update issue** I'd say we can go with the `first come, first served` method here and assign @mariapeever based on the posted [proposal](https://github.com/Expensify/App/issues/47427#issuecomment-2329681103) given the RCA is obvious and the solution is straight-forward.

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment] 2024-09-07 05:20
👋 Hey @mariapeever, please leave a comment letting us know when we can expect a PR to be ready for review 🧑‍💻

Otherwise, if there's no response in ~48h (2 days) from time of assignment (https://github.com/Expensify/App/issues/47427#issuecomment-2332987965, 1 day already passed) we'll have to reassign the task to the contributor next in line, as per the guidelines (if I recall correctly).

> [!note]
> If you have any questions regarding your first assignment, how does this work, or any other information feel free to ask.

##

@roryabraham Please correct me if the 'no response' rule has different timelines as I wasn't able to find info on this specific case.

**Comment by mariapeever** [comment] 2024-09-09 17:33
@ikevin127 I have submitted a proposal on Upwork and have been waiting for it to get approved. I can submit a PR by the end of today.

**Comment by mariapeever** [comment] 2024-09-09 18:14
@ikevin127 Thanks! Does this mean that I can create a PR before my Upwork proposal has been approved?

**Comment by ikevin127** [comment] 2024-09-09 18:33
@mariapeever For sure, as mentioned - when the payment is due date, the BZ team member which handles the payments will make sure you accept your offer and you get paid.

Given the whole deploy and 7-days regression period process can take several days, the sooner the PR is opened, the better - but keep in mind that rushing to open the PR can lead to regressions if not tested thoroughly.

**Comment by ikevin127** [comment] 2024-09-12 22:07
@mariapeever Any updates on the PR or whether you plan on working on this issue ? Asking because there's been 7+ days from [assignment](https://github.com/Expensify/App/issues/47427#issuecomment-2332987965) and we're looking at fixing this issue. Please let us know!

**Comment by ikevin127** [comment] 2024-09-14 02:06
⌛ I think we should consider moving on with the 2nd [proposal](https://github.com/Expensify/App/issues/47427#issuecomment-2329687192) and assign @nkdengineer as contributor since they are the next in line. @roryabraham @jamesdeanexpensify What do you think ?

**Comment by mariapeever** [comment] 2024-09-14 06:01
@ikevin127 Sorry for the delay. I was busier than usually the last few days. I will create a PR today.

**Comment by dubielzyk-expensify** [comment] 2024-09-18 04:34
Can we add `Travel room` to the list here @jamesdeanexpensify ?

**Comment by ikevin127** [comment] 2024-09-21 21:36
👋 I have to take some accountability here for assignment and admit that I did not think this issue / PR will be as complex as it is in terms of code changes and now it's becoming clear to me that I did not take in consideration the codebase familiarity when I assigned @mariapeever given that this was their very first contribution.

Given that it's been over 1 week since the PR was opened and we're **not even close** to merge and also some of the feedback I provided in the **IMPORTANT** notes ([ref1](https://github.com/Expensify/App/pull/49209#issuecomment-2357393418), [ref2](https://github.com/Expensify/App/pull/49209#issuecomment-2359387258)) **was not taken in consideration** - I discussed with the team in this #contributor-plus Slack [thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1726870382488509) and decided that given the timeline of the issue, we're going to re-assign this to the contributor next in line given they have more experience with the codebase.

Therefore @nkdengineer if you're still available for this, let us know and we can take it from there.

Spanish translations were provided and verified ([slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1726624473137749)) already:

<details>
<summary>Translations - ES</summary>


1. `This chat is with Concierge. Ask questions and get 24/7 realtime support`. / `Este chat es con Concierge. Haz preguntas y obtén soporte en tiempo real las 24/7`.
2. `This chat is with [recipient]. Use the + button to split, submit, or pay an expense.` / `Este chat es con [recipient]. Usa el botón + para dividir, enviar o pagar un gasto`.
3. `This chat is with [recipients that don't include you]. Use the + button to split an expense.` / `Este chat es con [recipients that don't include you]. Usa el botón + para dividir un gasto`.
4. `This is where [submitter] will submit expenses to the [workspaceName] workspace. Just use the + button.` / `Aquí es donde [submitter] enviará los gastos al espacio de trabajo [workspaceName]. Solo usa el botón +`.
5. `This chat is with everyone in the [workspaceName] workspace. Use it for the most important announcements.` / `Este chat es con todos en el espacio de trabajo [workspaceName]. Úsalo para los anuncios más importantes`.
6. `This chat is with [workspaceName] workspace admins. Use it to chat about workspace setup and more.` / `Este chat es con los administradores del espacio de trabajo [workspaceName]. Úsalo para hablar sobre la configuración del espacio de trabajo y más`.
7. `This chat is with all Expensify members on the [domain] domain. Use it to chat with colleagues, share tips, and ask questions.` / `Este chat es con todos los miembros de Expensify en el dominio [domain]. Úsalo para chatear con compañeros de trabajo, compartir consejos y hacer preguntas`.
8. `This chat room is for anything #[roomName] related. It was created by [displayName].` / `Este chat es para todo lo relacionado con #[roomName]. Fue creado por [displayName]`.
9. `This chat is for invoices between [invoice sender/bill payer workspaceName] and [invoice/paid bill receiver workspaceName OR displayName]. Use the + button to send an invoice.` / `Este chat es para facturas entre [invoice sender/bill payer workspaceName] y [invoice/paid bill receiver workspaceName OR displayName]. Usa el botón + para enviar una factura.`

</details>

**Note**: The task is more complex than just replacing copy, we have multiple places where this needs to be done **without** breaking current behaviour: workspace rooms, invoice rooms, chat rooms, rooms and on top of this most of these have the (archived) version when the workspace associated is removed and some of these can have a custom description which is an extra case which needs to be accounted for when changing these copies. More context in the initial PR ([ref1](https://github.com/Expensify/App/pull/49209#issuecomment-2357393418), [ref2](https://github.com/Expensify/App/pull/49209#issuecomment-2359387258)).

cc @roryabraham

**Comment by nkdengineer** [comment] 2024-09-22 01:05
@ikevin127 Yes I'm available to take this issue.

**Comment by ikevin127** [comment] 2024-09-23 23:24
♻️ I just performed another review after latest updates from the author (https://github.com/Expensify/App/pull/49209#issuecomment-2368412668) on the PR and unfortunately it's still not ready for merge as logic is still broken. Therefore, @nkdengineer you can start working on the PR and while doing that please keep in mind all the edge cases and complexities encountered in the first PR https://github.com/Expensify/App/pull/49209 as there are multiple cases in which applying the new copy changes can break currently working logic:
- workspaces / rooms with custom description
- workspaces / rooms archived

additionally, once you think you have everything working as expected - please double check before (current staging) / after (your PR) in all different scenarios described by my reviews in first PR https://github.com/Expensify/App/pull/49209 to ensure no logic is broken compared to staging where not required by this issue.

**Comment by nkdengineer** [comment] 2024-09-24 09:13
@roryabraham Based on the comment above, can you please assign me here then I can start working on the PR.

**Comment by ikevin127** [comment] 2024-09-24 23:10
My latest review from the first PR https://github.com/Expensify/App/pull/49209#issuecomment-2369747376:

> Just checked out the latest changes and unfortunately there's still issues with archived workspace rooms which had a custom description added before the workspace was deleted (archived), and also with active workspace member chats:
>
> Screenshots
>
> ##
> 
> Given this, I will ask the other contributor to open a PR and will let them know about our discussion in this PR so they'd know about all the complexities and edge cases such that we can get to the bottom of this issue.
> 
> While you can close this PR now, I recommend you to keep your branch so that the PR and discussion remains here in the closed PR for when payment is due to get your compensation for the work done here and also to keep a record on the timeline of events from this PR.

Keep in mind ^ this is my 4th review ([review 1 ref](https://github.com/Expensify/App/pull/49209#issuecomment-2354257770), [review 2 ref](https://github.com/Expensify/App/pull/49209#issuecomment-2357393418), [review 3 ref](https://github.com/Expensify/App/pull/49209#issuecomment-2359387258)) of the PR and at this point it was still incomplete both terms of functionality and PR Author Checklist.

**Note**: I also helped provide and verify the spanish translations in Slack [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1726624473137749).

##

The latest author response after 4th review https://github.com/Expensify/App/pull/49209#issuecomment-2370134985:

> @ikevin127 I don't think that this is ok. I have done all the work already. There are just minor changes that are required. I'd like another reviewer from your team to be dealing with the PR from now on, please. You are not allowed to use any of my work with no payment.

##

**Here's the #expensify-open-source Slack discussion:** https://expensify.slack.com/archives/C02NK2DQWUX/p1726870382488509 where the decision was to move on with the next in line contributor (@nkdengineer) since they have a better understanding of the codebase.

**Comment by jamesdeanexpensify** [comment] 2024-09-26 03:58
**Please note** I've just made small tweaks to the **Proposed copy** for:

- Workspace chat
- #announce room
- #admins room

in the [original comment](https://github.com/Expensify/App/issues/47427#issue-2466045073) at the top of this issue!

**Comment by nkdengineer** [comment] 2024-09-30 11:14
I prepared a draft PR [here](https://github.com/Expensify/App/pull/49919). Just have a problem with `beginningOfChatHistoryUserRoom`, how can we know who is the user that created this room? cc @ikevin127 @roryabraham

**Comment by ikevin127** [comment] 2024-09-30 22:52
@nkdengineer Not entirely sure these would help you, but they may point you in the right direction:
1. This [proposal](https://github.com/Expensify/App/issues/49260#issuecomment-2373031512) from another issue related to report name, indicates existing code that extracts `reportOwnerDisplayName`.
2. This [line](https://github.com/Expensify/App/pull/49209/files#diff-3258457b3b73b3f6fde322dfd4d925501f57daeee25e2ae30e671a53460aa06cR598) from the previous PR which extracts `displayName` to use for `beginningOfChatHistoryUserRoom`.

**Comment by nkdengineer** [comment] 2024-10-01 09:59
@ikevin127 The PR is [here](https://github.com/Expensify/App/pull/49919).

**Comment by ikevin127** [comment] 2024-10-03 08:58
♻️ **Status update**: PR is looking good and will start working on the checklist in about 10h.

##

⚠️ We only have 1 PR blocking issue related to `User-created room (aka beginningOfChatHistoryUserRoom)`, specifically ⬇️ 

Before:
> Collaboration starts here! 🎉 Use this space to chat about anything #bravo-clubhouse related.

After:
> This chat room is for anything #[roomName] related. It was created by [displayName].

Problem being with the last part `It was created by [displayName].`, specifically not being able to get the #room creator's [displayName] because in the report object we don't have the data to determine the user who created the room. Note that in the `Before` copy we did not have this variable either.

What @nkdengineer did currently was to use the workspace name as [displayName], having it look like this:

<details>
<summary>Screenshot</summary>

<img width="972" alt="Screenshot 2024-10-02 at 17 03 31" src="https://github.com/user-attachments/assets/84585705-6f0d-41a3-b835-fb712ab7f49d">

</details>

I see 3 possible ways to approach this:
1. Do nothing, keeping it as is in the screenshot above (using WS name instead of the name of who created the room).
2. Remove / replace the last part of the copy (`It was created by [displayName].`).
3. Apply BE change to return user who created the room.

> [!note]
> This is currently the only blocker for the PR.

cc @jamesdeanexpensify @roryabraham

**Comment by jamesdeanexpensify** [comment] 2024-10-03 16:28
Let's just remove that part of the copy, thanks!

**Comment by roryabraham** [comment] 2024-10-04 23:09
Heading on parental leave, we'll need another Expensify engineer to take over as CME here.

**Comment by roryabraham** [comment] 2024-10-04 23:47
@stitesExpensify assigning you here just in case the PR is reverted and more internal engineering help is needed. Picked you at random, hope you don't mind

**Comment by nkdengineer** [comment] 2024-10-08 15:51
@jamesdeanexpensify Please help to confirm what the expected for this case above then I will fix this in this [PR](https://github.com/Expensify/App/pull/50384).

cc @parasharrajat

**Comment by jamesdeanexpensify** [comment] 2024-10-08 17:23
I don't think you can start a group chat with just yourself, can you?

**Comment by jamesdeanexpensify** [comment] 2024-10-08 19:23
It might make the most sense in that case to route you straight to your Self DM. It would be a super fringe case to start a group chat with yourself, so much so that I'm not even sure we should allow it. 

@JmillsExpensify any thoughts here? Basically, we're updating beginningOfChatHistory copy in this issue and there's a way to start a group chat with yourself. In that case, we're trying to figure out what the beginningOfChatHistory should actually say. But I wonder if instead when you create a group chat with yourself, we just take you directly to Self DM instead.

**Comment by thienlnam** [comment] 2024-10-08 19:44
I think we should just block this use-case. It seems like it's a workaround to create a group chat with yourself anyways. You select and then deselect someone else

**Comment by thienlnam** [comment] 2024-10-08 19:50
Actually, seems like it is intended from this conversation https://expensify.slack.com/archives/C01GTK53T8Q/p1728401433760799 so we can just remove the copy in this case where you are the only participant? cc @nkdengineer

**Comment by nkdengineer** [comment] 2024-10-08 19:52
@thienlnam Let me update this in the working PR.

**Comment by ikevin127** [comment] 2024-10-15 21:17
* [x] [@ikevin127] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

I don't think we need regression test here since this was copy update, if I'm wrong please let me know.

##

@jamesdeanexpensify Not sure who's the BZ here for payment but we had [1 regression](https://github.com/Expensify/App/issues/50390) which was handled in a follow-up PR (https://github.com/Expensify/App/pull/50384), therefore the payment should have a -50% penalty here.

**Comment by ikevin127** [comment] 2024-10-17 20:21
cc @VictoriaExpensify Payment details in https://github.com/Expensify/App/issues/47427#issuecomment-2415185057.

**Comment by ikevin127** [comment] 2024-10-19 19:12
Bumped on Slack [thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1729364777140889?thread_ts=1726870382.488509&cid=C02NK2DQWUX) for payment as well, here's a short summary:

> **Summary**
> - me (reviewer) and merged PR author should get $125 (-50% penalty for 1 [regression](https://github.com/Expensify/App/issues/47427#issuecomment-2400391304), see above)
> - I vote for 25% for Maria Peever, meaning $62.5 for their work on the first PR which we did not merge (hopefully still around to get paid)

**Comment by VictoriaExpensify** [comment] 2024-10-23 00:31
As discussed in Slack, this is how the payment breakdown will work out:

- @ikevin127 and @nkdengineer  will get $125 (-50% penalty for 1 regression, see issue)
- @mariapeever will get $62.5 for their work on the first PR which we did not merge

Everyone is paid via Upwork, fixing this up now

**Comment by VictoriaExpensify** [comment] 2024-10-23 00:36
Payment summary:
Contributor: @nkdengineer paid $125 via Upwork
Contributor+: @ikevin127 paid $125 via Upwork

@mariapeever I have sent you an offer for the work you did on the initial PR. Once accepted I will approve the payment

Thanks all for getting this fixed up

**Comment by ikevin127** [comment] 2024-10-23 17:08
Not overdue, most of the payments were completed - awaiting completion of last payment to contributor once they accept the offer.

**Comment by ikevin127** [comment] 2024-10-28 20:05
Not overdue, most of the payments were completed - awaiting completion of last payment to contributor once they accept the offer.

**Comment by jamesdeanexpensify** [comment] 2024-11-04 03:05
What's next here? Thanks!

**Comment by VictoriaExpensify** [comment] 2024-11-12 03:21
Hmm still waiting for @mariapeever to accept my offer. I've bumped her in the Open Source channel and sent her a message in upwork. We'll give her a few more days before we close this out I guess.

**Comment by VictoriaExpensify** [comment] 2024-11-13 03:17
Still nothing from Maria. I'll close this out tomorrow if I haven't heard anything

**Comment by VictoriaExpensify** [comment] 2024-11-14 03:08
Maria still hasn't accepted the offer. Not much more we can do here so I'm closing this out.

**Closed by VictoriaExpensify** 2024-11-14 03:08 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
