### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] Deeplink - Duplicate concierge chat is displayed on LHN when deeplinking to concierge

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44465] opened 2024-06-26 14:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44063
## Action Performed:
1. Sign out from ND
2. Paste this link to the browser tab https://staging.new.expensify.com/concierge
3. Press Enter key
4. Enter a new user email address in the email field
5. Click Continue button
6. Click the Join button
7. While staying in the onboarding process, observe the LHN

## Expected Result:
Only one concierge chat is displayed on the LHN

## Actual Result:
Duplicate concierge chat is briefly displayed on the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f12f02f1-b0a5-4f87-a2b3-7d3304ea975c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01761bb8fe9958d8df</li>
        <li>Upwork Job ID: 1808128563862616294</li>
        <li>Last Price Increase: 2024-10-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by lanitochka17** [comment] 2024-06-26 14:38
We think that this bug might be related to #vip-vsp

**Comment by jnowakow** [comment] 2024-07-03 08:13
Hello, I'm from SoftwareMansion, an expert agency, and I'm going to work on this one

**Comment by jnowakow** [comment] 2024-07-03 08:29
It's strange, I'm able to reproduce this issue on staging but when I try to do so on local build it works correctly:

https://github.com/Expensify/App/assets/56261019/5b08bb42-48b4-48f7-b956-3845af6df18d

**Comment by getusha** [comment] 2024-07-04 10:06
Same, not able to reproduce this on local build.

![Screenshot 2024-07-04 at 12 58 25 in the afternoon](https://github.com/Expensify/App/assets/75031127/d501a000-4cee-4681-a3f1-15b03e448fba)

**Comment by sonialiap** [comment] 2024-07-12 11:21
@jnowakow @getusha I'm not sure how local build is created (not an engineer 😅), is the local build based on staging or is it possible for staging to be different from a local build? Maybe the builds have to be renewed?

**Comment by mvtglobally** [comment] 2024-07-19 03:22
Issue not reproducible during KI retests. (First week)

**Comment by getusha** [comment] 2024-07-30 19:45
Seems like the issue is not reproducible anymore, i will confirm it tomorrow
https://github.com/Expensify/App/issues/44465#issuecomment-2238040878

**Comment by mvtglobally** [comment] 2024-08-03 04:07
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2024-08-09 04:25
Issue not reproducible during KI retests. (Third week)

**Comment by sonialiap** [comment] 2024-08-09 13:55
Closing since it's not reproducible for 3 weeks

**Comment by IuliiaHerets** [comment] 2024-09-10 19:17
The issue is still reproducible with the latest build if you first go to the deep link in the browser. Build - v9.0.31-22

https://github.com/user-attachments/assets/a5d9ff11-701a-410e-9a06-2b793e218630

**Comment by sonialiap** [comment] 2024-09-11 10:07
looking for proposals

**Comment by wildan-m** [comment] 2024-09-12 06:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Duplicate concierge chat displayed on LHN when deeplinking.

### What is the root cause of that problem?

In `navigateToConciergeChat`, we are trying to create the concierge chat when it's not found:

https://github.com/Expensify/App/blob/336e4782aec98bb29a06c28e0d630c276d4eddf6/src/libs/actions/Report.ts#L2155-L2159

Deeplinking can cause issues when there is a conflict between the existing concierge chat from the server and a newly created one. This can lead to the focus being moved to the existing chat or, optimistically, the newly created concierge report showing a "not found" page.

### What changes do you think we should make in order to solve the problem?

If concierge chat doesn't exist, we should wait for the report to load instead of recreating it.

We can either add a new `NVP_CONCIERGE_CHAT_REPORT_ID` or utilize `NVP_ONBOARDING`'s chatReportID (uncertain if NVP_ONBOARDING consistently represents concierge report id).

In this check code:

https://github.com/Expensify/App/blob/336e4782aec98bb29a06c28e0d630c276d4eddf6/src/libs/actions/Report.ts#L1390-L1394


We can fill `NVP_CONCIERGE_CHAT_REPORT_ID` value with `report.reportID`

```tsx
    if (report?.reportID) {
        if (ReportUtils.isConciergeChatReport(report)) {
            conciergeChatReportID = report.reportID;
            Onyx.set(ONYXKEYS.NVP_CONCIERGE_CHAT_REPORT_ID, report.reportID);
        }
    }
```

Reset here:

https://github.com/Expensify/App/blob/336e4782aec98bb29a06c28e0d630c276d4eddf6/src/libs/actions/Report.ts#L168-L172

```tsx
        // When signed out, val is undefined
        if (!value?.accountID) {
            conciergeChatReportID = undefined;
            Onyx.set(ONYXKEYS.NVP_CONCIERGE_CHAT_REPORT_ID, undefined);
            return;
        }
```

In `src/libs/actions/Welcome/index.ts`
Add new if condition to `checkServerDataReady`
```tsx
function checkServerDataReady() {
    if (isLoadingReportData || isEmpty(conciergeChatReportID)) {
        return;
    }

    resolveIsReadyPromise?.();
}
```

And listen to the key

```tsx
Onyx.connect({
    key: ONYXKEYS.NVP_CONCIERGE_CHAT_REPORT_ID,
    initWithStoredValues: false,
    callback: (value) => {
        conciergeChatReportID = value ?? '';
        checkServerDataReady();
    },
});
```

We navigate once the conciergeChatReportID is ready, without having to recreate the chat.

Change [this code](https://github.com/Expensify/App/blob/336e4782aec98bb29a06c28e0d630c276d4eddf6/src/libs/actions/Report.ts#L2148-L2166) to

```tsx
function navigate(reportID: string, shouldDismissModal: boolean, actionType?: string) {
    if (shouldDismissModal) {
        Navigation.dismissModal(reportID);
    } else {
        Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(reportID), actionType);
    }
}

function navigateToConciergeChat(shouldDismissModal = false, checkIfCurrentPageActive = () => true, actionType?: string) {
    // If conciergeChatReportID contains a concierge report ID, we navigate to the concierge chat using the stored report ID.
    // Otherwise, we would find the concierge chat and navigate to it.
    if (!conciergeChatReportID) {
        // In order to avoid creating concierge repeatedly,
        // we need to ensure that the server data has been successfully pulled
        Welcome.onServerDataReady().then(() => {
            // If we don't have a chat with Concierge then create it
            if (!checkIfCurrentPageActive()) {
                return;
            }

            if(!conciergeChatReportID){
                return;
            }

            navigate(conciergeChatReportID, shouldDismissModal, actionType);
        });
    } else {
        navigate(conciergeChatReportID, shouldDismissModal, actionType);
    }
```

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/44465-duplicate-concierge?expand=1)

### What alternative solutions did you explore? (Optional)

Add small delay after data ready here:

https://github.com/Expensify/App/blob/336e4782aec98bb29a06c28e0d630c276d4eddf6/src/libs/actions/Report.ts#L2154-L2160

This ensure that the concierge chat loaded, there is a chance that chat not loaded even if `isLoadingReportData` is false, applying onyx updates, especially report take longer than setting `isLoadingReportData` to false.

**Comment by wildan-m** [comment] 2024-09-12 07:09
[Proposal Updated](https://github.com/Expensify/App/issues/44465#issuecomment-2345421832)

- Add optimization suggestion as alternative 2

**Comment by getusha** [comment] 2024-09-16 07:33
I am not able to reproduce this

https://github.com/user-attachments/assets/5127c82a-38d2-4b80-a118-283f46b5c2ba

**Comment by wildan-m** [comment] 2024-09-16 08:31
@getusha it's reproducible in desktop now, 

no need for new user, you can use existing user, just access

https://staging.new.expensify.com/concierge (not direct concierge chat with id)

and then open link in desktop

Like this rep steps:

https://github.com/Expensify/App/issues/44465#issuecomment-2341834174

**Comment by sonialiap** [comment] 2024-09-24 10:47
I can also still reproduce

When I open the link and log in, I am shown two Concierge messages in the LHN. If I click out of the one that's displayed first then it vanishes (I'm not in #focus mode) and the only way to get back to it is to click the browser back button.

<img width="1514" alt="image" src="https://github.com/user-attachments/assets/17aed1a8-1404-4ae5-a49d-91ce9c82d0fd">

**Comment by ugogiordano** [comment] 2024-09-28 09:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Duplicate concierge chat displayed on LHN when deeplinking to `/concierge` path.

### What is the root cause of that problem?

When users log out and deep link to the concierge page, logging back in should open the concierge chat. However, if the reports are not fully loaded from the server, the `navigateToConciergeChat` function creates a new report instead of navigating to the existing concierge chat.

https://github.com/Expensify/App/blob/ee772a9e599c1adfee46047ba27e961574617e62/src/pages/ConciergePage.tsx#L37-L50

The root cause is that the `conciergeChatReportID` is not populated when `navigateToConciergeChat` is called. This occurs because the function checks the `conciergeChatReportID` to determine whether to navigate to an existing report or create a new one. If the reports have not been loaded yet, the `getChatByParticipants` function defaults to using an empty reports parameter from `ReportConnection.getAllReports()`, which leads to it returning an **empty object**. Consequently, the `navigateToAndOpenReport` function incorrectly attempts to create a new concierge chat.

Here's the relevant source code for clarity:
https://github.com/Expensify/App/blob/ee772a9e599c1adfee46047ba27e961574617e62/src/libs/actions/Report.ts#L2155-L2176

The key issue lies within the `navigateToAndOpenReport` function, specifically in this block of code:
https://github.com/Expensify/App/blob/ee772a9e599c1adfee46047ba27e961574617e62/src/libs/actions/Report.ts#L1005-L1012

The getChatByParticipants function uses ReportConnection.getAllReports() as its default parameter:
https://github.com/Expensify/App/blob/ee772a9e599c1adfee46047ba27e961574617e62/src/libs/ReportUtils.ts#L6137
When the data isn’t ready, ReportConnection.getAllReports() returns an empty report collection. As a result, this leads to the creation of a new concierge chat instead of navigating to the existing one.


### What changes do you think we should make in order to solve the problem?


We should implement a check to ensure that the reports are fully loaded before calling `navigateToConciergeChat`. If the reports are not yet available, we can delay the navigation or provide feedback to the user. This would involve modifying the function to wait for the reports to load before proceeding with navigation logic.

We can define a variable to check if the reports are still loading, using something like:
~~~typescript
const [isLoadingReportData] = useOnyx(ONYXKEYS.IS_LOADING_REPORT_DATA, {initialValue: true});
~~~

Before navigating to the concierge chat, we should ensure that `isLoadingReportData` is defined and false. If it's still loading or undefined, we should not proceed with the navigation.

The revised source code for `ConciergePage` would look like this:
~~~typescript
function ConciergePage({session}: ConciergePageProps) {
    const styles = useThemeStyles();
    const isUnmounted = useRef(false);
    const {shouldUseNarrowLayout} = useResponsiveLayout();
    const [isLoadingReportData] = useOnyx(ONYXKEYS.IS_LOADING_REPORT_DATA, {initialValue: true});

    useFocusEffect(
        useCallback(() => {
            if (session && 'authToken' in session) {
                App.confirmReadyToOpenApp();
                Navigation.isNavigationReady().then(() => {
                    if (isUnmounted.current || !!isLoadingReportData) {
                        return;
                    }
                    Report.navigateToConciergeChat(true, () => !isUnmounted.current);
                });
            } else {
                Navigation.navigate();
            }
        }, [session, isLoadingReportData]),
    );

    useEffect(() => {
        isUnmounted.current = false;
        return () => {
            isUnmounted.current = true;
        };
    }, []);

    return (
        <ScreenWrapper testID={ConciergePage.displayName}>
            <View style={[styles.borderBottom, styles.appContentHeader, !shouldUseNarrowLayout && styles.headerBarDesktopHeight]}>
                <ReportHeaderSkeletonView onBackButtonPress={Navigation.goBack} />
            </View>
            <ReportActionsSkeletonView />
        </ScreenWrapper>
    );
}
~~~

By wrapping the callback in `useCallback`, we can avoid unnecessary re-renders and ensure the effect only runs when necessary.

### What alternative solutions did you explore? (Optional)
I considered a workaround where we immediately navigate to the chat but add logic to prevent creating a new report if the ID isn’t available. However, this could lead to inconsistencies, and ensuring the reports are fully loaded first is a more robust solution.

**Comment by ugogiordano** [comment] 2024-09-28 10:04
Contributor details
Your Expensify account email: ugo.giordano1987@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0113b790fc6c7a1ad9

**Comment by sonialiap** [comment] 2024-10-01 10:06
@getusha what do you think of the above proposal?

**Comment by getusha** [comment] 2024-10-01 15:40
Reviewing, i'll update today

**Comment by getusha** [comment] 2024-10-03 11:46
@ugogiordano seems like we already fixed/attempted to fix this as i can see 

https://github.com/Expensify/App/blob/ee772a9e599c1adfee46047ba27e961574617e62/src/libs/actions/Report.ts#L2162-L2164

`navigateToAndOpenReport` is called on onServerDataReady. I am still trying to understand why isLoadingReportData remains true after onServerDataReady.

**Comment by wildan-m** [comment] 2024-10-03 19:17
[Proposal Updated](https://github.com/Expensify/App/issues/44465#issuecomment-2345421832)
- Add Alternative 3 -- Wait for ReportConnection.getAllReports()  not undefined
- provide more description to the root cause





> I am still trying to understand why isLoadingReportData remains true after onServerDataReady.

@getusha did you mean, why `isLoadingReportData` become `false` but we can't find concierge report?
`isLoadingReportData` supposed to be true if not all report data loaded.

The answer might be in my proposal https://github.com/Expensify/App/issues/44465#issuecomment-2345421832

> there is a chance that chat not loaded even if isLoadingReportData is false, applying onyx updates, especially report take longer than setting isLoadingReportData to false.

There is a gap between `isLoadingReportData` become `false` and `allReports` being actually populated.

The situation can be described this way:
1. `isLoadingReportData` being set to false after `getOnyxDataForOpenOrReconnect`
2. Then `applyingOnyxUpdate` process will asynchronously update data from the 1st request
3. `allReports` data might be null or partially added, especially if we have huge number of reports
4. Then since `isLoadingReportData` already false `onServerDataReady()` will be executed, but 3rd step might not completed yet

My alternative 3 has the same pattern with `checkRequiredData` from `ProrityMode` 

https://github.com/Expensify/App/blob/b027baaf086c4a8f57bec48dd1cbbfb3c317726b/src/libs/actions/PriorityMode.ts#L79-L85

**Comment by getusha** [comment] 2024-10-06 06:45
@wildan-m @ugogiordano i am not able to reproduce this, could you please check?
https://streamable.com/ud25n3

**Comment by wildan-m** [comment] 2024-10-06 06:57
@getusha you should trigger opening the desktop app from staging. dev not trigger open to desktop dialog

**Comment by getusha** [comment] 2024-10-06 10:49
@wildan-m is there any way to reproduce it from dev so that we can test the solutions?

**Comment by wildan-m** [comment] 2024-10-06 11:42
@getusha we can npm run desktop from dev and while the desktop version running, trigger the deeplinking through staging site, that way we can debug the issue

**Comment by sonialiap** [comment] 2024-10-14 10:04
@getusha can I help with anything to get this issue resolved?

**Comment by huult** [comment] 2024-10-16 13:50
@wildan-m , @getusha This video guides you on how to test in the dev environment
<summary>
<details>

https://github.com/user-attachments/assets/0ba7e383-7fd7-466e-8014-9063c4175b7b

</details>
</summary>

**Comment by wildan-m** [comment] 2024-10-17 04:36
[Proposal Updated](https://github.com/Expensify/App/issues/44465#issuecomment-2345421832)

- Add missing details and branch for alternative 3

**Comment by lanitochka17** [comment] 2024-10-17 13:06
Issue is not reproducible on the  version v9.0.49-1

https://github.com/user-attachments/assets/3f3be0c7-5f93-4882-ace9-ae5fefd3fe95

**Comment by flaviadefaria** [comment] 2024-10-17 14:23
Added this issue to the Migration project, which is a top priority for the company.

**Comment by mvtglobally** [comment] 2024-10-19 03:48
Issue not reproducible during KI retests. (First week)

**Comment by flaviadefaria** [comment] 2024-10-21 17:47
Any updates on if the issue is reproducible? cc @getusha

**Comment by danielrvidal** [comment] 2024-10-22 00:30
We also have a Full Story video of a user running into it linked here: https://expensify.slack.com/archives/C07HPDRELLD/p1729192456274989

Let @anmurali and I know if you need more. We've seen it in multiple sessions. I think we should treat this as CRITICAL because it confuses real users.

**Comment by ugogiordano** [comment] 2024-10-29 09:36
Hi, I can work on a PR today but the Upwork job results as no longer available, so I can't apply to it.

![Screenshot 2024-10-29 at 10 36 37](https://github.com/user-attachments/assets/ef852534-c10a-4a9d-9f0d-3d132d7db691)

**Comment by sonialiap** [comment] 2024-10-29 09:51
@ugogiordano the upwork job is necessary for payment, in the case where the job closes before completion or isn't created for an issue, the BZ (in this case me) will manually send a payment after the issue is completed. You can work on the PR without the job being open. Since your proposal has been chosen and you've been assigned, please proceed with the PR :)

**Comment by ugogiordano** [comment] 2024-10-29 09:57
@sonialiap thanks for the clarification. I'll submit a PR by today.

**Comment by mvtglobally** [comment] 2024-10-30 09:40
Issue not reproducible during KI retests. (Second week)

**Comment by ugogiordano** [comment] 2024-10-30 10:11
@mvtglobally the issue is reproducible by following these steps:
1. Sign in at https://staging.expensify.com/.
2. Navigate to Support and then select Concierge.
3. Copy the URL into a new tab and replace the hostname with https://dev.new.expensify.com:8082/.
4. Verify that only one Concierge chat is displayed.

Video is here: https://github.com/Expensify/App/issues/44465#issuecomment-2416909187

The PR is on its way; I apologize for the delay. I’m currently gathering videos of the reproduction in all environments and will complete it by the end of the day.

**Comment by ugogiordano** [comment] 2024-10-31 14:22
I submitted the [PR](https://github.com/Expensify/App/pull/51794).

I was unable to build the Android app because of the following error:
~~~
Execution failed for task ':react-native-app-logs:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 17m 33s.
~~~

**Comment by flaviadefaria** [comment] 2024-11-18 19:41
There have been no updates here for weeks. What's the latest update? This is a high-priority issue for #migrate.

**Comment by aldo-expensify** [comment] 2024-11-18 19:46
Seems like the [PR](https://github.com/Expensify/App/pull/51794) has some checks failing,  left a message asking to fix them

**Comment by aldo-expensify** [comment] 2024-11-21 01:49
PR merged

**Comment by sonialiap** [comment] 2024-12-02 12:03
Payment summary:
- @getusha $250 via NewDot - please complete the [checklist](https://github.com/Expensify/App/issues/44465#issuecomment-2494691295)
- @ugogiordano $250 - offer sent in [upwork](https://www.upwork.com/nx/wm/offer/105156162)

**Comment by ugogiordano** [comment] 2024-12-02 12:17
@sonialiap, can I get the offer on the first "Upwork Profile for payment" you can see on my bio? I have attached the VAT ID to it.

**Comment by sonialiap** [comment] 2024-12-03 10:04
@ugogiordano the offer should be sent to Rosaria V., is that correct?

**Comment by ugogiordano** [comment] 2024-12-03 10:05
> @ugogiordano the offer should be sent to Rosaria V., is that correct?
Yes correct, thank you so much!

**Comment by sonialiap** [comment] 2024-12-03 12:56
@ugogiordano offer sent! 

https://www.upwork.com/nx/wm/offer/105173644

**Comment by sonialiap** [comment] 2024-12-09 09:55
@getusha bumping for the [checklist](https://github.com/Expensify/App/issues/44465#issuecomment-2494691295) :)

**Comment by getusha** [comment] 2024-12-12 07:53
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [x] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:  N/a this was fixed before https://github.com/Expensify/App/issues/17884

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/a

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

We already have a regression test created for this issue https://github.com/Expensify/App/issues/17884

**Comment by sonialiap** [comment] 2024-12-12 10:04
Thanks!

**Closed** 2024-12-12 10:04 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2025-01-29 21:07
$250 approved for @getusha
