### ISSUE TITLE
[HOLD for payment 2023-02-08] pinned chat become unpinned when user pinned chat in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14584] opened 2023-01-26 01:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. go to offline
2. click into an existing chat or create a new one
3. click on  pin button to pin the chat
4. confirm the pin icon is lit up, i.e. the chat was pinned
5. go to online

## Expected Result:
chat should be pinned

## Actual Result:
chat becomes unpinned

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / ~Safari~
- [ ] MacOS / Desktop

Seems to be only affecting Chrome on computer and mobile device

**Version Number:** 1.2.59-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214737387-711a8106-b56d-4e9b-8a6b-3a20e61f1f60.mp4

https://user-images.githubusercontent.com/43996225/214737411-6144c366-a75a-4e15-ac04-f7f612cfa127.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674207539542629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018bae5da04b47a887</li>
        <li>Upwork Job ID: 1618712481741504512</li>
        <li>Last Price Increase: 2023-01-26</li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-01-26 20:48
Can reproduce this one on dev. You don't need to create a new chat with a user while offline though. It happens because we are making an identical request and for some reason we are trying to deduplicate them here:

https://github.com/Expensify/App/blob/91939483199f070ea4d62e874ad504c1f4ed89ec/src/libs/actions/NetworkRequestQueue.js#L20

This is not how the sequential queue is supposed to work so there's a gap in the implementation. Gonna grab this one.

**Comment by sonialiap** [comment] 2023-02-01 21:52
I can only reproduce the issue on Chrome

Desktop, Android app, and Safari are all correctly keep the chat pinned

**Comment by sonialiap** [comment] 2023-02-01 21:56
As a heads up, I will be OOO Feb 2-11

**Comment by sonialiap** [comment] 2023-02-02 22:57
I'm OOO Feb 2-11, reassigning bug0

**Comment by sobitneupane** [comment] 2023-02-07 12:41
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x] The PR that introduced the bug has been identified. Link to the PR:

Looks like it was introduced by https://github.com/Expensify/App/pull/8312 PR.

> * [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/8312#issuecomment-1420708543


> * [x]  [@sobitneupane] Propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-02-07 12:44
#### Regression Test Proposal

- Go offline
- Click into an existing chat or create a new one
- Click on pin button to pin the chat
- Confirm that the chat is pinned
- Go online
- Verify that the pinned chat is still pinned.

Do we agree 👍 or 👎

**Comment by marcaaron** [comment] 2023-02-07 15:35
>Looks like it was introduced by https://github.com/Expensify/App/pull/8312 PR.

@sobitneupane I'm not sure if I see the connection there. Would you mind explaining why it caused a regression? If you aren't sure then we shouldn't check this box:

> - [ ] The PR that introduced the bug has been identified. Link to the PR:

The purpose of this process is to help people understand what caused a regression to see if it's preventable. Just checking the box doesn't achieve our goal.

>pointing out the bug it caused _and why, so the author and reviewers can learn from the mistake_

**Comment by marcaaron** [comment] 2023-02-07 15:38
@sobitneupane The regression test could be improved by asking the tester to queue up several "pin" and "unpin" events while offline. The last action should be the one that sticks when they come back from offline. Thank you!

**Comment by sobitneupane** [comment] 2023-02-07 17:15
Thanks for the suggestions @marcaaron.

**Comment by sobitneupane** [comment] 2023-02-07 17:17
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/6556
> * [ ]  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:


https://github.com/Expensify/App/pull/6556#discussion_r1098962239

**Comment by sobitneupane** [comment] 2023-02-07 17:31
#### Regression Test Proposal

- Go offline
- Open an existing chat or create a new one
- "Pin" and "Unpin" the chat several times
- Go online
- Verify that the last action that was taken (either pinned or unpinned) is stuck and is not changed after going online.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-02-07 17:34
@marcaaron Please let me know if you see any further room for improvement.

**Comment by marcaaron** [comment] 2023-02-07 23:40
I'd update this to:

>Verify that the last action that was taken (either pinned or unpinned) is stuck and is not changed after going online.

Verify that the last action that was taken (either pinned or unpinned) is the eventual final state after going online.

(in reality the state could switch between pinned unpinned before eventually landing on the correct state) <- expected behavior

**Comment by sobitneupane** [comment] 2023-02-08 02:34
Thanks @marcaaron. Updated the step in [Regression Test Proposal](https://github.com/Expensify/App/issues/14584#issuecomment-1421166379).

**Comment by abekkala** [comment] 2023-02-09 19:44
- Reported by: @gadhiyamanan $250
- PR Review: @sobitneupane $1000 

@marcaaron I see that this one was Internal. can you confirm those are the only two payments needed.

**Comment by abekkala** [comment] 2023-02-09 19:49
Offers sent, in Upwork, to @gadhiyamanan and @sobitneupane

**Comment by marcaaron** [comment] 2023-02-09 20:59
@abekkala If an issue has only ever been `Internal` and there were no proposals then my understanding is the C+ and issue reporter are the only ones who require compensation.

**Comment by abekkala** [comment] 2023-02-10 13:25
ok, yes, that's what I was thinking too but figured I'd get confirmation to be sure! 😃

**Comment by abekkala** [comment] 2023-02-10 15:42
Upwork confirms payments have been sent

**Comment by gadhiyamanan** [comment] 2023-02-10 15:44
@abekkala please close the upwork contract

**Comment by abekkala** [comment] 2023-02-10 15:48
yes @gadhiyamanan after initiating payments I was also in the process of closing for both you and @sobitneupane!
I've just closed them and came to make note: 


Both payments have been sent, the contract has been completed, and the Upwork job post has been closed.

**Comment by abekkala** [comment] 2023-02-13 12:51
not overdur

**Comment by abekkala** [comment] 2023-02-13 16:09
@marcaaron @sobitneupane Can I confirm that the current TestRail that already exists applies to this. (based on the Regression Test Proposal shown above)
<img width="663" alt="Screenshot 2023-02-13 at 10 08 38 AM" src="https://user-images.githubusercontent.com/11966460/218510539-ca82201d-e85e-4a14-af3b-c0c5c973f6b0.png">

**Comment by marcaaron** [comment] 2023-02-13 20:24
@abekkala I think we can update it slightly so that we are specifically testing for several "pin" / "unpin" actions in a row while offline? The issue we fixed here is technically not be covered by the existing regression test.

**Comment by abekkala** [comment] 2023-02-14 20:12
@marcaaron ah ok, I guess then I'm not sure which one this test would fall under as this particular test says to Pin and Unpin several times. 
Our current testing has test steps for the Pin action and then separate test steps for the Unpin action. (both while Offline)

Or, is it just a matter of adding a last step to both of them: 
`Verify that the last action taken (either pinned or unpinned) is the final state after returning to online`

**Comment by marcaaron** [comment] 2023-02-14 23:21
>this particular test says to Pin and Unpin several times

There are two tests so in that sense tester would pin/unpin more than once. The specific behavior would be something like:

- Go offline
- pin
- unpin
- pin
- unpin
- Go online
- Verify the chat ends up in an upinned state eventually

Lmk if that clears it up!

**Comment by abekkala** [comment] 2023-02-15 12:57
omg - yes. Thanks @marcaaron I (for some reason) was thinking about that a different way

**Comment by marcaaron** [comment] 2023-02-17 21:10
I think we are done with this one? Gonna close - but feel free to repopen if there's anything left.

**Closed by marcaaron** 2023-02-17 21:10 UTC
Labels: Daily, Internal, Overdue, Bug
