### ISSUE TITLE
[HOLD for payment 2023-09-27] [$250] Web – Split Bill – Difference in padding among amount and description.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26210] opened 2023-08-29 14:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Go to any chat and split a bill.
2.	Notice the difference in padding among amount and description. Amount is relatively above then description.

## Expected Result:
Padding should be consistent among amount and description.

## Actual Result:
Padding is not consistent among amount and description.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/8e1dfb6f-9540-4459-bcc8-35540da903fe

![1](https://github.com/Expensify/App/assets/115492554/61b8f9f8-3191-4632-8992-3bc67a41c016)

![image](https://github.com/Expensify/App/assets/115492554/698e1a2e-1f82-48c0-8da7-fb70277d77af)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692690646431509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137a2de3122624eed</li>
        <li>Upwork Job ID: 1699562237383294976</li>
        <li>Last Price Increase: 2023-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 26568205</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-08-29 14:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Split bill preview has inconsistency in padding among amount and description

### What is the root cause of that problem?

Description has style `styles.mt1` but amount doesn't

### What changes do you think we should make in order to solve the problem?

I suggest to add `styles.mt1` to the parent here
https://github.com/Expensify/App/blob/17025aa62b1a8c40bb451a97000d3f4605c7bdae/src/components/ReportActionItem/MoneyRequestPreview.js#L278

and remove all mt1 in its children


### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment] 2023-09-01 20:15
I agree the padding is obviously off. I think it should be fixed but considering how minor this is, adjusting the price to $250.

**Comment by PiyushChandra17** [comment] 2023-09-04 05:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Padding is not consistent among amount and description.

### What is the root cause of that problem?
We are using styles.ml1 while styling the amount each text

### What changes do you think we should make in order to solve the problem?
Instead of using styles.ml1, we should add styles.mt1 on styling the amount each text (just to be consistent on both the description and amount text)

### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment] 2023-09-06 23:16
Forgot to add External label, @robertKozik looks like we have a proposal https://github.com/Expensify/App/issues/26210#issuecomment-1704650204

**Comment by munsuyog** [comment] 2023-09-07 05:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inconsistent padding between amount and description.

### What is the root cause of that problem?

styles.ml1 is being used for styling.

### What changes do you think we should make in order to solve the problem?

In MoneyRequestPreview.js, add styles.mt1

`<Text style={[styles.textLabel, styles.colorMuted, styles.mt1]}>`

### What alternative solutions did you explore? (Optional).

**Comment by robertKozik** [comment] 2023-09-07 16:02
Thanks for pinging @stephanieelliott !

Thank you all for your proposals 🙇🏼
It seems that each of you has correctly pinpointed the root cause of the issue. Additionally, the proposed solutions were quite similar. I'm inclined to choose @namhihi237's proposal, as it was the quickest and first to introduce this particular solution. However, I believe we should proceed with your alternative solution to avoid any style duplications on children nodes.

Selected proposal: [Proposal](https://github.com/Expensify/App/issues/26210#issuecomment-1697530954)
Contributor: @namhihi237 

🎀 👀 🎀 C+ reviewed

**Comment by PiyushChandra17** [comment] 2023-09-08 04:47
@stephanieelliott How about my proposal ? I think it's slightly different from what's @namhihi237 proposed

**Comment by aldo-expensify** [comment] 2023-09-08 17:05
@PiyushChandra17 thanks for the proposal, but to me it looks almost the same as @namhihi237's [proposal](https://github.com/Expensify/App/issues/26210#issuecomment-1697530954), except that you are dropping the left margin (`styles.ml1`) which I'm not sure is something we want.

**Comment by aldo-expensify** [comment] 2023-10-02 11:08
ping @robertKozik for the [checklist](https://github.com/Expensify/App/issues/26210#issuecomment-1727192239)

**Comment by stephanieelliott** [comment] 2023-10-04 01:09
Summarizing payment on this issue: 
 - Issue reporter: @usmantariq96 $250 (paid via Upwork)
 - Contributor: @namhihi237 $250 (paid via Upwork)
 - Contributor+: @robertKozik, no payment due 
 
 Upwork job is [here](https://www.upwork.com/jobs/~0137a2de3122624eed), no bonus onpayout

**Closed by stephanieelliott** 2023-10-04 01:09 UTC
Labels: External, Daily, Awaiting Payment, Bug
