### ISSUE TITLE
[$500] Chat - Unable to close Emoji-reacted popover when click outside, near the bottom of popover

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25976] opened 2023-08-25 20:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Hover on any chat message and send a any Emoji
3. Right click on an emoji reacted of a message
4. Verify that and Emoji-reacted popover is displaying
5. Click outside, but near the bottom of popover, horizontally

## Expected Result:
The Emoji-reacted popover should be closed if we click outside.

## Actual Result:
The Emoji-reacted popover is not closed, until we click other outside area.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d7a9c432-8bef-4f34-9931-3024e6e6f2c2

https://github.com/Expensify/App/assets/115492554/ab3174a5-ab1d-4967-8b5f-20fca218beb0

**Expensify/Expensify Issue URL:**

**Issue reported by:** @hoangzinh

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692145547162429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a318eb91f3f42c7c</li>
        <li>Upwork Job ID: 1699231586202316800</li>
        <li>Last Price Increase: 2023-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26614588</li>
<li>samh-nl | Contributor | 26614590</li>
<li>hoangzinh | Reporter | 26614591</li>
</ul></li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-08-26 07:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Reaction List is not closing when clicking on `ReportActionItemEmojiReactions` section.

### What is the root cause of that problem?
- There are some context ref issues with the `ReportActionItemEmojiReactions` component.

### What changes do you think we should make in order to solve the problem?
- First of all in `ReportActionItemEmojiReactions` component, we need to remove `popoverReactionListAnchor` ref.
- After that we need to pass `contextMenuAnchor` ref to `ReportActionItemEmojiReactions` component from `ReportActionItem` component.
    - Like this `contextMenuAnchor={popoverAnchorRef}`. We will define the prop in propTypes too.
- Now in `BasePopoverReactionList` component to keep the consistency we need to change `reactionListAnchor` to `anchorRef`.
    - And also we will create a new `reactionListContextMenuAnchor` ref for measuring content dimensions.
    - And we will pass the recieved `contextMenuAnchor` ref to `reactionListContextMenuAnchor` ref, similar to `PopoverReportActionContextMenu` component.

Finally we will be able to make this work.


### What alternative solutions did you explore? (Optional)
- N/A

**Comment by anmurali** [comment] 2023-08-31 02:07
Will reproduce and slap the label on tomorrow

**Comment by jeet-dhandha** [comment] 2023-09-05 05:27
Bump @anmurali

**Comment by anmurali** [comment] 2023-09-06 01:22
It looks like the area immediately below the popover is some kinda "dead" zone!

**Comment by thepranays** [comment] 2023-09-06 04:56
What's the issue with @samh-nl solution ? Why it is not merged ?

**Comment by mollfpr** [comment] 2023-09-07 05:11
>There are some context ref issues with the ReportActionItemEmojiReactions component.

@jeet-dhandha What is the issue? Please put more explanation for the RCA so that it can be aligned with your proposed solution and help to understand your proposal.

**Comment by mollfpr** [comment] 2023-09-07 05:25
I tested on @samh-nl proposal, and it's working well.

I agree with the RCA; the solution is fixing the root cause. Let's go with @samh-nl [proposal](https://github.com/Expensify/App/issues/25976#issuecomment-1693963084) 🚀

🎀 👀 🎀 C+ reviewed!

**Comment by jeet-dhandha** [comment] 2023-09-07 05:26
adding

**Comment by jeet-dhandha** [comment] 2023-09-07 05:26
@mollfpr

**Comment by jeet-dhandha** [comment] 2023-09-07 05:30
@mollfpr If u r available then please check my updated proposal (https://github.com/Expensify/App/issues/25976#issuecomment-1694204559) with more context.

**Comment by jeet-dhandha** [comment] 2023-09-07 05:34
@mollfpr Just one thing instead of creating new ref's why aren’t we more aligned to using same refs which we have used in `MoneyRequestAction` and `ReportPreview` in `ReportActionItem`.

**Comment by mollfpr** [comment] 2023-09-07 06:00
@jeet-dhandha I don't see any relation to using the context menu ref. Why do we need to use that for the emoji component?

> So to fix this we should have same ref for both open and close.

I also don't understand the above. So currently the ref for open the emoji reaction are wrong?

**Comment by jeet-dhandha** [comment] 2023-09-07 06:06
I don't have much knowledge on how ref's work (so will need your help in learning that) but i just re-checked my code and it could have created a regression so yeah we can go with @samh-nl 's solution. 👍

**Comment by mollfpr** [comment] 2023-09-11 16:54
Friendly bump @madmax330 for the review.

**Comment by mollfpr** [comment] 2023-10-19 12:46
Weird Melvin doesn't add the payment title here. I'll add the checklist soon.

**Comment by mollfpr** [comment] 2023-10-20 16:36
> The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/15685

> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/15685/files#r1367226768

> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> Determine if we should create a regression test for this bug.
> If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**_Precondition: a report must contain a message that has at least one emoji reaction._**

1. Go to a report
2. Go to a message that has at least one emoji reaction and right-click (web/desktop) or long-press (mobile) an emoji reaction.
3. Press on the empty area directly below the popover (web/desktop) or anywhere outside the popover (mobile).
4. Verify that the popover is closed.
5. 👍 or 👎

---

Friendly bump @anmurali. The PR has been in production since Sept 18th, and this is eligible for the urgency bonus.

**Comment by anmurali** [comment] 2023-11-14 14:35
Everyone's been paid with speed bonus where applicable since this is an old pending payment. 
Regression test proposed https://github.com/Expensify/Expensify/issues/336286

**Closed by anmurali** 2023-11-14 14:35 UTC
Labels: Reviewing, External, Daily, Bug
