### ISSUE TITLE
[$250] Attachments - App crashes after uploading attachment/message offline & killing the app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49792] opened 2024-09-26 14:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5009376&group_by=cases:section_id&group_id=292107&group_order=asc
**Email or phone of affected tester (no customers):** applausetester+ck10925@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch ND app
2. Go to any 1:1 DM chat
3. Disable the internet connection in the device
4. Write something in the compose box
5. Upload attachment to a chat while there is text content in the composer
6. Force kill the app

## Expected Result:
App should not crash when force kill the app after uploading attachment in offline mode

## Actual Result:
App crashes after uploading attachment/message offline & killing the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d8622996-4232-4180-893a-7319bbf55534

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839719498497677489</li>
        <li>Upwork Job ID: 1839719498497677489</li>
        <li>Last Price Increase: 2024-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 104270041</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment] 2024-09-26 14:05
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by rezkiy37** [comment] 2024-10-03 15:04
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by rezkiy37** [comment] 2024-10-04 10:59
Hello!
I've tried to reproduce the bug. Luckily, I was not able to do it. I tested on the latest staging 9.0.44-6 and main 9.0.44-0 (_develop_). Please confirm that the bug is replicable on your side, @ishpaul777 @lanitochka17 @abekkala 🙂 

<details><summary>Details</summary>
<p>

https://github.com/user-attachments/assets/5ed94417-97aa-4129-8da9-c5bf45d1871f

</p>
</details>

**Comment by lanitochka17** [comment] 2024-10-04 17:37
Issue is still reproducible on the latest build 9.0.44-10

https://github.com/user-attachments/assets/f63a5d47-dd14-4f25-a0a0-07e30981f3e1

**Comment by rezkiy37** [comment] 2024-10-08 13:30
Well, I will try to reproduce one more time.

**Comment by rezkiy37** [comment] 2024-10-08 14:35
I cannot reproduce the bug on the latest staging (_9.0.46-3_) and `main` (_9.0.46-1 Develop_). Can you please reset the cache and reinstall the app? Probably there is some issue on the device because of the cache. I will ask my colleagues to test it as well.

**Comment by pasyukevich** [comment] 2024-10-09 12:29
For me, this bug is also not reproducible

**Comment by abekkala** [comment] 2024-10-09 18:52
I also was not able to reproduce today - closing

**Closed by abekkala** 2024-10-09 18:52 UTC
Labels: External, Daily, Bug
