### ISSUE TITLE
Workspace invite SMS - Unable to unsubscribe from messages

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8294] opened 2022-03-24 15:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Enter http://staging.new.expensify.com and login
2. Click on the green plus icon
3. Click "New workspace"
4. Click "Manage members"
5. Click "Invite"
6. Enter phone number belonging to tester (with area extension)
7. Click 'Invite"

## Expected Result:
Phone number receives SMS invitation to join Expensify and is able to respond "STOP" to unsubscribe from messages

## Actual Result:
Phone number receives SMS invitation to join Expensify but is unable to respond "STOP" to unsubscribe from messages, despite message reading "Reply STOP to unsubscribe from messages"

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.1.44-3

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
![Bug5503108_2](https://user-images.githubusercontent.com/43996225/159946222-9b4cbd5b-cf25-4b72-b7f5-36dd07993dfb.jpg)

https://user-images.githubusercontent.com/43996225/159946256-8b015378-ec2e-4384-bcd1-74ad88cab03f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment] 2022-03-29 05:07
Issue not reproducible during KI retests. (First week)

**Comment by robertjchen** [comment] 2022-03-29 07:06
Looks like this might be a backend issue, as the phone number we're using does not allow for replies. We would have to make some SMS service settings tweaks to allow for this. Thanks again for the report- closing this for now 👍

**Closed by robertjchen** 2022-03-29 07:06 UTC
Labels: Engineering, Daily, Overdue
