### ISSUE TITLE
[$500] Theme - App returns to main chat instead of previous page when returning from changing theme

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35689] opened 2024-02-02 18:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .1.4-36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Click Settings from the bottom
3. Click Profile from the top
4. Click back button
5. Note that app returns to Settings
6. While in Workspaces page, click Profile > Preferences > Theme
7. Select a different theme
8. Click Back button

## Expected Result:
App returns to Workspaces page

## Actual Result:
App returns to main chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a0854c6f-df4b-44cb-bb54-fbb755576bec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc56887b7e795d9e</li>
        <li>Upwork Job ID: 1753588018262831104</li>
        <li>Last Price Increase: 2024-02-03</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-02 18:20
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by luacmartins** [comment] 2024-02-02 21:41
I think this is actually related to Wave8: Ideal Nav

**Comment by luacmartins** [comment] 2024-02-02 21:43
I'm on the fence of this being a blocker, it doesn't really break any functionality, it's just slightly unexpected. I'll leave the decision to @tylerkaraszewski though

**Comment by tylerkaraszewski** [comment] 2024-02-02 22:53
I don't think it needs to be a blocker. It seems it can probably be external as well, does any one object to that?

**Comment by jeremy-croff** [comment] 2024-02-03 05:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Back button does not go to the previous Stack from the theme modal.

### What is the root cause of that problem?
Deep linking is required to go back to the /settings/preferences previous stack

### What changes do you think we should make in order to solve the problem?
This is achieved by updating the back handler here:
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/settings/Preferences/ThemePage.js#L43
And specifying the deep link instead:
`https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/settings/Preferences/ThemePage.js#L43`

### What alternative solutions did you explore?
I observed that the follow screens also all will require a deep link from settings/preferences stack: Priority Mode, Language, and finally Theme.

**Comment by hayata-suenaga** [comment] 2024-02-04 05:08
> this issue needs to be handled here: https://github.com/orgs/Expensify/projects/94/views/2?pane=issue&itemId=51976513

Thank you for pointing that out. I'll close this one in favor of that one 🙇

**Closed by hayata-suenaga** 2024-02-04 05:08 UTC
Labels: External, Engineering, Daily, Help Wanted
