### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000]  'Link sent!' message is not dynamically updated when changing language preference

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18827] opened 2023-05-12 08:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Add a secondary login account, and leave it unverified
2. Open new tab
3. Navigate to sign in page
4. Enter the unverified email address
5. Click on Unlink button
6. Verify that 'Link sent!' message is displayed
7. Scroll down, and select Spanish as a language preference

## Expected Result: 
'Link sent!' message should be dynamically updated to Spanish
## Actual Result:
 'Link sent!' message is not dynamically updated to Spanish

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2f37361c-60f6-4de9-8b6c-a1e93a3b3b99

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683649359591549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0198d8720bb9bfb004</li>
        <li>Upwork Job ID: 1659222928961388544</li>
        <li>Last Price Increase: 2023-05-18</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-05-12 09:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Link sent isn't changed dynamically on language change

### What is the root cause of that problem?
In the onyx success message we are storing the translated message so it won't get updated on language change.
https://github.com/Expensify/App/blob/6d27757667e0757d02a390623c072c69238c7070/src/libs/actions/Session/index.js#L713

### What changes do you think we should make in order to solve the problem?
We should store the translation key in the onyx successData message instead of the translated value and In the component, we need to use this translation key to get the value which makes the text language specific.

https://github.com/Expensify/App/blob/6d27757667e0757d02a390623c072c69238c7070/src/pages/signin/UnlinkLoginForm.js#L65-L69

**Comment by kevinksullivan** [comment] 2023-05-13 00:19
Discussing in slack

https://expensify.slack.com/archives/C049HHMV9SM/p1683937177713499?thread_ts=1683649359.591549&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment] 2023-05-18 15:42
Ok, got the go ahead yesterday on moving this forward in that slack thread above.

**Comment by Natnael-Guchima** [comment] 2023-05-18 15:46
> Ok, got the go ahead yesterday on moving this forward in that slack thread above. 

@kevinksullivan if this is something that can be fixed, it might be a good idea to fix [this](https://expensify.slack.com/archives/C049HHMV9SM/p1683650481712599?thread_ts=1683650481.712599&cid=C049HHMV9SM) issue too here - with a single PR. The issue I have referenced here has the same nature as the one that is being fixed here.

**Comment by eh2077** [comment] 2023-05-18 16:07
I'm willing to fix similar issues together as I mentioned in [proposal](https://github.com/Expensify/App/issues/18827#issuecomment-1545496634) 
cc @parasharrajat @cristipaval

**Comment by kevinksullivan** [comment] 2023-05-23 19:06
Offers sent in upwork @parasharrajat @Pujan92

**Comment by Pujan92** [comment] 2023-05-23 19:17
Sorry for the delay @parasharrajat , just raised a [PR](https://github.com/Expensify/App/pull/19480).

**Comment by kevinksullivan** [comment] 2023-06-09 01:35
@parasharrajat  wanted to check in on this since it's been a bit (hope you're feeling better!).  I see some comments from 3 days ago. What's your ETA for  finishing this out?

**Comment by kevinksullivan** [comment] 2023-06-16 14:04
@Natnael-Guchima @parasharrajat @Pujan92 please accept the offer in Upwork when you get a chance. Thanks!

**Comment by Natnael-Guchima** [comment] 2023-06-23 09:39
@kevinksullivan it seems you have sent me a $1000 offer by accident

**Comment by kevinksullivan** [comment] 2023-06-23 14:07
Thanks @Natnael-Guchima , I modified the amount on the offer.

**Comment by kevinksullivan** [comment] 2023-06-23 14:08
@parasharrajat bump on accepting offer, and can you complete the checklist above before we pay this out?

**Comment by Natnael-Guchima** [comment] 2023-06-23 14:24
You are welcome 🙌. Accepted the offer, thanks.

**Comment by cristipaval** [comment] 2023-06-26 15:46
bump @parasharrajat

**Comment by kevinksullivan** [comment] 2023-06-26 23:47
Paid out. Thanks everyone!

**Closed by kevinksullivan** 2023-06-26 23:47 UTC
Labels: External, Daily, Awaiting Payment, Bug
