### ISSUE TITLE
[$1000] Dev: Cannot split money in DM group chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22440] opened 2023-07-07 18:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create new group chat with existing contacts
2. Click + on composer and Split bill
3. Enter amount and click Next
4. Click Split xxx button

## Expected Result:
Money is split correctly

## Actual Result:
hows console error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.37-6
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/98b81d9b-68a8-4c59-be1f-9691bdc4fa7c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @0xmiroslav
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688715731926879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a656ab6a105b57b</li>
        <li>Upwork Job ID: 1678431703910395904</li>
        <li>Last Price Increase: 2023-08-04</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2023-07-11 10:01
Discussing the next steps in [Slack.](https://expensify.slack.com/archives/C049HHMV9SM/p1689069652041229?thread_ts=1688715731.926879&cid=C049HHMV9SM)

**Comment by isabelastisser** [comment] 2023-07-14 08:28
We can't reproduce this. @chiragxarora, if you can help with reproducible steps (as per Carlo's suggestion in the Slack discussion), please follow up on this issue.

I am closing this for now.

**Comment by kbecciv** [comment] 2023-07-27 21:14
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1690404444868009
**Posting a clear reproduction steps:**

1. Create a group with 2 unknown users
2. Create Split bill in this group

https://github.com/Expensify/App/assets/93399543/9478c33e-3c48-45f8-a2e0-a58503a5024c

**Comment by isabelastisser** [comment] 2023-07-31 20:29
Still waiting for proposals.

**Comment by StevenKKC** [comment] 2023-08-01 10:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cannot split money in DM group chat.

### What is the root cause of that problem?
The root cause is that new user does not have `login` field.
This is expected if another user has never interaction with you and is the purpose of login => accountID migration.

After create a group chat with new users, BE responds `personalDetailsList` as below.
![Screenshot 2023-08-01 054241](https://github.com/Expensify/App/assets/131836113/b4fd1688-1b92-4e81-90ac-3b9b144d7b18)

If split money success, BE responds as below.
![Screenshot 2023-08-01 054307](https://github.com/Expensify/App/assets/131836113/3b342dad-2b0d-4096-82b1-ed242380d02a)

In `MoneyRequestConfirmPage` page, `participants` will be retrieved as below.
https://github.com/Expensify/App/blob/89dfb7788ed3a533da5d5e2c9e55335028570d82/src/pages/iou/steps/MoneyRequestConfirmPage.js#L71
https://github.com/Expensify/App/blob/89dfb7788ed3a533da5d5e2c9e55335028570d82/src/libs/OptionsListUtils.js#L207-L234
So the `login` field of `participants` is set to `undefined`.

In these line, because `login` field is `undefined`, so the console error will be shown, and cannot split money.
https://github.com/Expensify/App/blob/89dfb7788ed3a533da5d5e2c9e55335028570d82/src/libs/actions/IOU.js#L452
https://github.com/Expensify/App/blob/89dfb7788ed3a533da5d5e2c9e55335028570d82/src/libs/actions/IOU.js#L574

### What changes do you think we should make in order to solve the problem?
We can set `login` field of `participants` as below, because `displayName` of new user is just email address.
After split money success, the `login` of new user will be set correctly.
* Pass `reportID` to `PopoverReactionList` in [this line](https://github.com/Expensify/App/blob/89dfb7788ed3a533da5d5e2c9e55335028570d82/src/libs/OptionsListUtils.js#L215).
```js
    return {
        keyForList: String(detail.accountID),
-       login,
+       login: login || displayName,
        ...
    };
```
### What alternative solutions did you explore? (Optional)
We can pass proper value to `Localize.arrayToString` and `OptionsListUtils.addSMSDomainIfPhoneNumber` in `IOU.js`.
```js
-   const formattedParticipants = Localize.arrayToString([currentUserLogin, ..._.map(participants, (participant) => participant.login)]);
+   const formattedParticipants = Localize.arrayToString([currentUserLogin, ..._.map(participants, (participant) => participant.login || participant.displayName)]);
```
```js
-   const email = OptionsListUtils.addSMSDomainIfPhoneNumber(participant.login).toLowerCase();
+   const email = OptionsListUtils.addSMSDomainIfPhoneNumber(participant.login || participant.displayName).toLowerCase();
```

**Comment by StevenKKC** [comment] 2023-08-01 10:38
After create a group chat, duplicated contacts is stored in `Onyx`.
This will be fixed in https://github.com/Expensify/App/issues/21706

**Comment by isabelastisser** [comment] 2023-08-01 18:44
@fedirjh it seems like we only have one proposal above, can you please review it and let me know if we should move forward with that?

**Comment by isabelastisser** [comment] 2023-08-03 18:56
We don't have a proposal yet.

**Comment by puneetlath** [comment] 2023-08-03 21:32
I think this can probably be closed as a dupe of https://github.com/Expensify/App/issues/21268

**Comment by isabelastisser** [comment] 2023-08-07 16:13
Based on the comments below, I will close this.

https://github.com/Expensify/App/issues/22440#issuecomment-1664673279

https://github.com/Expensify/App/issues/22440#issuecomment-1665866448

**Comment by isabelastisser** [comment] 2023-08-07 16:14
Payment summary: 

Issue reported by: @0xmiroslav $250

I will process the payment in Upwork now.

**Closed by isabelastisser** 2023-08-07 16:14 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by isabelastisser** [comment] 2023-08-23 19:01
@0xmiroslav I resent the offer in Upwork now, please accept it and I will process the payment. Thanks!

**Comment by isabelastisser** [comment] 2023-08-23 19:31
Hey @0xmiroslav, thanks for the heads up! I reviewed the discussion now and re-sent the proposal to Volodymyr L.

All set.
