### ISSUE TITLE
[HOLD for payment 2024-01-11] [$500] Welcome message - Hmm its not here not displayed for wrong link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33230] opened 2023-12-18 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open #announce of workspace of which you are admin
3. Click on header and open settings - >welcome message
4. Copy the link and paste in the report
5. Modify the link and send eg: Add 's' in the end
6. Click on modified link and observe that nothing happens

## Expected Result:
App should display 'hmm its not here' page for wrong welcome message link click

## Actual Result:
App does nothing on wrong welcome message link click

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d2a806ad-2ce6-4b4e-941d-e254a8d5e594

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb5caa50cbb1c6aa</li>
        <li>Upwork Job ID: 1736751063588982784</li>
        <li>Last Price Increase: 2023-12-25</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 28071736</li>
<li>samilabud | Contributor | 28071737</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by samilabud** [comment] 2023-12-18 14:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Welcome message - Hmm its not here not displayed for wrong link

### What is the root cause of that problem?
When we copy and paste using the composer component, the links are preformatted in HTML keeping the same href.

### What changes do you think we should make in order to solve the problem?
We should modify the link when pasting/typing to change the href (URL) to be the same as the user type when modifying a current link

**Comment by samilabud** [comment] 2023-12-18 14:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Welcome message - Hmm its not here not displayed for wrong link

### What is the root cause of that problem?
We are not validating the URL route for the second parameter when we are building our routes for 'r' parameter in https://github.com/Expensify/App/blob/main/src/ROUTES.ts. e.g: 

https://github.com/Expensify/App/blob/11d78212e7575261ad53c34ab41cc40b39a4c52a/src/ROUTES.ts#L155

### What changes do you think we should make in order to solve the problem?
We should validate if the reportActionID exists to return our custom 404 error.

**Comment by yh-0218** [comment] 2023-12-18 15:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Welcome message - Hmm its not here not displayed for wrong link
### What is the root cause of that problem?
Because we don't handle 404 page.
### What changes do you think we should make in order to solve the problem?
1. we can validate link and go to 404 page
2. we need to 404 route
```js 
RANDOM_URL: {
        route: 'r/:reportID/:any',
        getRoute: (reportID: string, any: string) => ` r/${reportID}/${any}` as const,
}
```
and create 404 right modal.
In this case we need to several routes.
### What alternative solutions did you explore? (Optional)

**Comment by unicorndev-727** [comment] 2023-12-18 15:26
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
For the optimistic account, the ReportWelcomeText shows the email as text, not a link.
### What is the root cause of that problem?
The root cause is that `r/:reportId/welcomeMessages` is converted to `r/:reportID?/:reportActionID?` and the Report page will be displayed.
![image](https://github.com/Expensify/App/assets/75538817/6abe2d98-96e1-4def-8a78-857537d78356)

### What changes do you think we should make in order to solve the problem?
If the format of route is `r/:reportID?/:reportActionID?` and  is not isModalNavigator, we should check if reportActionId is valid.
If not valid, should return 404 error page here.

https://github.com/Expensify/App/blob/7515847fbc32af4d67fa1e787f82bc43b106fa81/src/libs/Navigation/linkTo.ts#L108
### What alternative solutions did you explore? (Optional)
  N/A

**Comment by shahinyan11** [comment] 2023-12-18 15:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Welcome message - Hmm its not here not displayed for wrong link 
### What is the root cause of that problem?
The main cause is `reportActionID` in [REPORT_WITH_ID](https://github.com/Expensify/App/blob/7515847fbc32af4d67fa1e787f82bc43b106fa81/src/ROUTES.ts#L154C1-L157C7) t route . How I see `reportActionID` is not used in `getRoute` and the question arises: why is it added there?

When we navigate to link like following `r/5104260884112886/ANYTHING` the text after last `/`  will  be our `reportActionID` and so that we have such route the 404 screen will not be shown . 
### What changes do you think we should make in order to solve the problem?
I do nor know why we use `reportActionID` in `REPORT_WITH_ID` but we can remove or if we know that the valid `reportActionID` can be only numeric text we can validate that the txt after last / will numeric

### What alternative solutions did you explore? (Optional)

**Comment by karimiBadr** [comment] 2023-12-18 16:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Welcome message - Hmm its not here not displayed for wrong link

### What is the root cause of that problem?

The presence of an unnecessary segment `/:reportActionID?` in the [ROUTES.ts](https://github.com/Expensify/App/blob/main/src/ROUTES.ts#L155C9-L155C50) config:
```
REPORT_WITH_ID: {
	route: 'r/:reportID?/:reportActionID?',
	getRoute: (reportID: string) => `r/${reportID}` as const,
},
```

### What changes do you think we should make in order to solve the problem?
Remove `/:reportActionID?` : 

```
REPORT_WITH_ID: {
	route: 'r/:reportID?',
	getRoute: (reportID: string) => `r/${reportID}` as const,
},
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by shubham1206agra** [comment] 2023-12-21 11:46
@samilabud's [proposal](https://github.com/Expensify/App/issues/33230#issuecomment-1860724093) looks good

🎀👀🎀 C+ reviewed

**Comment by shubham1206agra** [comment] 2023-12-21 11:47
@hayata-suenaga This might be related to comment linking project.

**Comment by shubham1206agra** [comment] 2023-12-21 11:49
@roryabraham @perunt as you have worked on comment linking

**Comment by roryabraham** [comment] 2023-12-23 00:29
I don't think this necessarily has to HOLD for comment linking. I agree with @shubham1206agra's [recommended proposal](https://github.com/Expensify/App/issues/33230#issuecomment-1860724093).

**Comment by samilabud** [comment] 2023-12-23 02:00
> What happens if numeric but doesn't exist? i.e. `r/:reportId/1234567890`

In this case, the deep link does reach the correct route:` 'r/:reportID?/:reportActionID',` but this is not handling any error/404 page for this when reportId is not found, I imagine this would be another bug or feature to develop if not please let me know.

**Comment by shubham1206agra** [comment] 2023-12-23 04:58
> What happens if numeric but doesn't exist? i.e. `r/:reportId/1234567890`

That will be handled in comment linking project

**Comment by shubham1206agra** [comment] 2023-12-28 13:02
@hayata-suenaga Waiting for your assignment here

**Comment by shahinyan11** [comment] 2023-12-28 13:31
@shubham1206agra @roryabraham I'm so sorry. But I have a complaint. @samilabud's suggestion is updated after my proposal, and the proposed solution is the same as what I proposed earlier. I think it is  against below point in contibution.md
![Screenshot 2023-12-28 at 17 22 49](https://github.com/Expensify/App/assets/46921547/45bb205f-50f5-4312-a344-991f9c0a9036)

**Comment by samilabud** [comment] 2023-12-28 13:49
> @shubham1206agra @roryabraham I'm so sorry. But I have a complaint. @samilabud's proposal was updated after my proposal, and the proposed solution is the same as what I proposed earlier. if you check any version of his proposal before last update , there is not anything about validating the reportActionID to be numeric. I have doubts that his proposal has been updated based on my proposal. I think this contradicts the point below in contribution.md.
> 
> ![Screenshot 2023-12-28 at 17 31 41](https://private-user-images.githubusercontent.com/46921547/293214422-fdb98d98-ba8f-42b0-be70-5848998fe76d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NzEzMzAsIm5iZiI6MTcwMzc3MTAzMCwicGF0aCI6Ii80NjkyMTU0Ny8yOTMyMTQ0MjItZmRiOThkOTgtYmE4Zi00MmIwLWJlNzAtNTg0ODk5OGZlNzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDEzNDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYWRjMjY1OGJmMmYwZGIxMmViOGM0Y2I0ZTM1NTNkNzRiNzcxOTVkMmJlNWRmMjYwYjdiN2VjNmI0YWIwZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z-mGlykHrAUC2OdniwVLuj-jQZXqFm3DYkbaar0Z4MA)

Sorry @shahinyan11 from my first proposal I said we should validate the reportActionID, then I made the change to confirm my proposal and made the update using the code I made to fix this and uploading videos related. From what I see your proposal vs mine only has that overlap the rest has a different approach.

**Comment by samilabud** [comment] 2023-12-28 14:20
> > from my first proposal I said we should validate the reportActionID
> 
> @samilabud You said we should validate if the reportActionID exists . Your approach was about validation of existence.
> 
> Anyway, I don't want us to discuss this with each other. I wrote a complaint, let the reviewers decide whether I’m right or wrong

Yes of course, JTLYN I have never seen your proposal, if you see the time in which I edit mine vs yours the time is so similar that I can not write all that code based on a keyword in your proposal:

<img width="615" alt="image" src="https://github.com/Expensify/App/assets/5216036/39073f1e-c39d-4005-81fa-7b6eff030474">

<img width="639" alt="image" src="https://github.com/Expensify/App/assets/5216036/ccc5d61b-3577-45ad-b4f1-6eed1717bc62">

**Comment by shubham1206agra** [comment] 2023-12-28 14:26
> > > from my first proposal I said we should validate the reportActionID
> > 
> > 
> > @samilabud You said we should validate if the reportActionID exists . Your approach was about validation of existence.
> > Anyway, I don't want us to discuss this with each other. I wrote a complaint, let the reviewers decide whether I’m right or wrong
> 
> Yes of course, JTLYN I have never seen your proposal, if you see the time in which I edit mine vs yours the time is so similar that I can not write all that code based on a keyword in your proposal:
> <img alt="image" width="615" src="https://private-user-images.githubusercontent.com/5216036/293221107-39073f1e-c39d-4005-81fa-7b6eff030474.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NzM1MjIsIm5iZiI6MTcwMzc3MzIyMiwicGF0aCI6Ii81MjE2MDM2LzI5MzIyMTEwNy0zOTA3M2YxZS1jMzlkLTQwMDUtODFmYS03YjZlZmYwMzA0NzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMTQyMDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQxN2RiZTYwYmE2ZTQ1MTkzZWJhOTg0ZWJjMDBjODVhMDIzNzY1ZTBmOTcxMDc1MTRiNzExNjg0YmZiNjZlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._Rs0TOEE2URvGz-OX4jbOyyeWlaI3yoqUzIHPaN3HFs"> <img alt="image" width="639" src="https://private-user-images.githubusercontent.com/5216036/293221205-ccc5d61b-3577-45ad-b4f1-6eed1717bc62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NzM1MjIsIm5iZiI6MTcwMzc3MzIyMiwicGF0aCI6Ii81MjE2MDM2LzI5MzIyMTIwNS1jY2M1ZDYxYi0zNTc3LTQ1YWQtYjRmMS02ZWVkMTcxN2JjNjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMTQyMDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY2NWFhNDA2OTU0ZmQ1N2E0ZjBkNzdiZjYzZWU3NjljNzJiZDkzMmNmMDk4NmQ1NDFmYTZjYTE2YzQ3OGU1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vg_kTUBIByOlZ3Toc6r0lVFfQ8dDnvPk0cer4WiuzV4">

This is not a valid argument in this case. 

But I am gonna side with @samilabud in this case. As @shahinyan11, your RCA was right, but your solution is little vague, and I was unable to judge what you are saying, and in what direction you are going with your solution.

**Comment by shahinyan11** [comment] 2023-12-28 15:29
> Yes of course, JTLYN I have never seen your proposal, if you see the time in which I edit mine vs yours the time is so similar that I can not write all that code based on a keyword in your proposal:

@samilabud Why are you comparing your first proposal and my proposal? You should compare your last update with mine where there is a 3 hour difference

**Comment by shahinyan11** [comment] 2023-12-28 15:32
> This is not a valid argument in this case.
> 
> But I am gonna side with @samilabud in this case. As @shahinyan11, your RCA was right, but your solution is little vague, and I was unable to judge what you are saying, and in what direction you are going with your solution.

@shubham1206agra If you think it's fair then decide so

**Comment by perunt** [comment] 2023-12-28 16:05
Hey guys! Whatever decision you will make, please don't delete the `reportActionID` from the route path. This stuff will be used in the Comment Linking.

**Comment by shubham1206agra** [comment] 2023-12-28 16:41
> Hey guys! Whatever decision you will make, please don't delete the `reportActionID` from the route path. This stuff will be used in the Comment Linking.

We are not deleting the `reportActionID`. We are just going to validate this

**Comment by shubham1206agra** [comment] 2023-12-28 16:42
> > This is not a valid argument in this case.
> > But I am gonna side with @samilabud in this case. As @shahinyan11, your RCA was right, but your solution is little vague, and I was unable to judge what you are saying, and in what direction you are going with your solution.
> 
> @shubham1206agra You can check the difference between the latest and all previous versions of proposals from @samilabud. And then If you think it's fair then decide so

Sorry. But I still feel we should go with @samilabud's proposal

**Comment by roryabraham** [comment] 2023-12-29 03:17
Looks like @hayata-suenaga is OOO until 2024-01-08, so I'll jump in and take over as the Expensify engineer here.

**Comment by slafortune** [comment] 2024-01-11 19:33
@shubham1206agra can you please complete the above checklist then accept the job offer? Thanks!

**Comment by shubham1206agra** [comment] 2024-01-12 12:25
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/24411
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/24411#issuecomment-1889046394
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No as this is a new feature (comment linking project) being worked on.
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@slafortune] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Closed** 2024-01-12 20:24 UTC
Labels: External, Daily, Awaiting Payment, Bug
