### ISSUE TITLE
[HOLD for payment 2022-12-05] [$1000] mWeb - Payment Page is not scrollable. Reported by @sobitneupane

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11695] opened 2022-10-10 00:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and log in
2. Go to Settings
3. Click on Payments and try to scroll the page.

## Expected Result:
Page should be scrolled

## Actual Result:
Page is not scrollable.

## Workaround:
Unknow

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.12.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/194785845-592044e9-5580-4cf2-b083-6f167e314bb9.mp4

![309569071_828736321616969_2064140144598699415_n](https://user-images.githubusercontent.com/93399543/194785846-6eea8c2a-c1c6-4301-a6dd-a8b5edb8eb48.jpg)

**Upwork URL:** https://www.upwork.com/jobs/~01787df7c25949e98d

**Issue reported by:** @sobitneupane

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664359447566049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2022-10-10 04:21
**Proposal**

we have to use `scrollView` instead of  `View`https://github.com/Expensify/App/blob/7d1e65fe22a4f59c93d6aeaa1615468c61ed2983/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L272

we have to use `_map` instead of `Flatlist` otherwise it gives error ` VirtualizedLists should never be nested inside plain ScrollViews....`

https://github.com/Expensify/App/blob/ba1d5aefbd0d277d383ca11e487e661e53232f02/src/pages/settings/Payments/PaymentMethodList.js#L213-L218

replace it with 
`{this.getFilteredPaymentMethods().length
              ? _.map(this.getFilteredPaymentMethods(), this.renderItem)
              : this.renderListEmptyComponent()}`
              
add key to `renderItem`
![Screenshot 2022-10-10 at 9 48 37 AM](https://user-images.githubusercontent.com/54790231/194798733-32de4397-d935-4e81-a807-098a7cffd22b.png)

**Comment by trjExpensify** [comment] 2022-10-10 19:22
👋 Is this to say it's _only_ a bug in landscape mode, or portrait as well? It's kinda' weird for the title of the issue versus a note for the reproducer. 

>This issue can be clearly noticed in landscape mode

**Comment by sobitneupane** [comment] 2022-10-11 02:33
> 👋 Is this to say it's only a bug in landscape mode, or portrait as well?

Issue exists both in portrait and landscape mode. It is clearly noticeable even with one or two payment methods in landscape mode because of smaller height.

**Comment by MandarDevarshi** [comment] 2022-10-12 05:26
## Proposal

While comparing with other pages I feel there was just `<Scrollview>` missing around child components in the `BasePaymentsPage`. Please check.

> Tested on v1.2.12.3 

![Screenshot from 2022-10-12 10-36-29](https://user-images.githubusercontent.com/34445750/195254917-36012f7c-d4f0-4790-bd36-541a4d7825e6.png)
![Screenshot from 2022-10-12 10-36-37](https://user-images.githubusercontent.com/34445750/195254905-2f1b8161-d528-48d4-b136-e1967af0912d.png)
---
After `<Scrollview>`

https://user-images.githubusercontent.com/34445750/195256791-06d45646-ac67-498b-b1d4-8855271520a8.mp4

[My Upwork Profile](https://www.upwork.com/freelancers/~01c1af53a71eb0a42e)

**Comment by trjExpensify** [comment] 2022-10-12 16:54
@eVoloshchak any input on this proposal?

**Comment by eVoloshchak** [comment] 2022-10-12 18:31
> @eVoloshchak any input on this proposal?

I think @MandarDevarshi's [proposal](https://github.com/Expensify/App/issues/11695#issuecomment-1275607399) is the better solution
There are multiple components where this fix would also need to be implemented

Per [discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1665597477187449?thread_ts=1665434639.537719&cid=C01GTK53T8Q) on slack 
> let's try to fix as many places as we can reasonably see would have the same issue. I don't think we need to be exhaustive, but I think we can do better than just fixing this single flow
I think the best course of action here is to treat similar reported bugs as dupes atm and try to fix this issue as many places as we can in https://github.com/Expensify/App/issues/11695

However, this solution has a drawback: on iOS it makes the screen scrollable/draggable even is the content fits the screen

https://user-images.githubusercontent.com/9059945/195420541-acd8fbed-def1-468c-b8e3-c8f7ee32be09.mov


https://user-images.githubusercontent.com/9059945/195420565-309d1ea4-288d-4ab5-9cf5-32e6932f0bf3.mov

Is this something we want to avoid? I think there are ways to do it

**Comment by gadhiyamanan** [comment] 2022-10-12 18:41
@eVoloshchak have you checked my [proposal](https://github.com/Expensify/App/issues/11695#issuecomment-1272769635)

**Comment by MandarDevarshi** [comment] 2022-10-12 18:45
@eVoloshchak 
For iOS there is `alwaysbouncevertical` prop could this be of any help here to make things consistent across platforms ?

[See here @ `react-docs`](https://reactnative.dev/docs/scrollview#alwaysbouncevertical-ios)

[See here @ `apple-docs`](https://developer.apple.com/documentation/uikit/uiscrollview/1619383-alwaysbouncevertical)
> If the value of this property is true and [bounces](https://developer.apple.com/documentation/uikit/uiscrollview/1619420-bounces) is true, the scroll view allows vertical dragging even if the content is smaller than the bounds of the scroll view. The default value is false.

**Comment by gadhiyamanan** [comment] 2022-10-12 18:47
> However, this solution has a drawback: on iOS it makes the screen scrollable/draggable even is the content fits the screen

It's default behaviour of ios (we can handle this by bounces prop). you can check this behaviour on other screens which are scrollable.

**Comment by gadhiyamanan** [comment] 2022-10-12 19:03
> @eVoloshchak have you checked my [proposal](https://github.com/Expensify/App/issues/11695#issuecomment-1272769635) 

@eVoloshchak any thoughts?

**Comment by marcochavezf** [comment] 2022-10-17 22:57
>we need to figure out all of the places where this should be fixed. Or is this the contributor's job?

Hi @eVoloshchak, yeah that's the idea. It will be great if the proposal includes the solution for this specific case and also includes all the possible places that need to be fixed with that solution. I think it will be worth increasing the price since the scope has been expanded, what do you think @trjExpensify?

**Comment by trjExpensify** [comment] 2022-10-21 16:00
@gadhiyamanan any thoughts on this question? 

>But removing FlatList and using map instead seems like it will hinder performance in some cases. Is this the only way?

**Comment by trjExpensify** [comment] 2022-10-21 16:02
In the meantime, job is on Upwork here: https://www.upwork.com/jobs/~01787df7c25949e98d

**Comment by Prince-Hamza** [comment] 2022-10-22 06:05
**Proposal**
you can simply add ` {flexGrow:1}` to a FlatList. like :

 ```
 <FlatList
            data={restaurantInfo}
            renderItem={({ item }) => renderRestaurantInfo(item)}
            keyExtractor={item => item.id * Math.random()}
            contentContainerStyle={{
                flexGrow: 1,
            }}
        />
```

 No need of ScrollView. works without virtualizedList error or any other error. 
tested on react native web nd Android.
Code Sandbox : https://codesandbox.io/s/async-tree-mdvw7l?&file=/src/App.js

**Comment by eVoloshchak** [comment] 2022-10-24 19:08
@Prince-Hamza, thanks for your proposal

Could you please explain in more detail where exactly would you add this prop? [This](https://github.com/Expensify/App/blob/83676c1036299ffecbf82f4b829a7f8cbd741cd7/src/pages/settings/Payments/PaymentMethodList.js#L213) Flatlist?

**Comment by Prince-Hamza** [comment] 2022-10-25 05:47
ok i was sleeping.am working on it now

**Comment by Prince-Hamza** [comment] 2022-10-25 12:22
code on your page will ook like this:

```
 return (
            <>
                <FlatList
                    data={this.getFilteredPaymentMethods()}
                    renderItem={this.renderItem}
                    keyExtractor={item => item.key}
                    ListEmptyComponent={this.renderListEmptyComponent()}
                    contentContainerStyle={{    flexGrow: 1    }}   />  // i added this line
                {
                    this.props.shouldShowAddPaymentMethodButton
                    && (
                        <FormAlertWrapper>
                            {
                                isOffline => (
                                    <Button
                                        text={this.props.translate('paymentMethodList.addPaymentMethod')}
                                        icon={Expensicons.CreditCard}
                                        onPress={e => this.props.onPress(e)}
                                        isDisabled={this.props.isLoadingPayments || isOffline}
                                        style={[styles.mh4, styles.mb4, styles.buttonCTA]}
                                        iconStyles={[styles.buttonCTAIcon]}
                                        key="addPaymentMethodButton"
                                        success
                                        shouldShowRightIcon
                                        large
                                    />
                                )
                            }
                        </FormAlertWrapper>
                    )
                }
            </>
        );
```


i can clone and test if you want

**Comment by eVoloshchak** [comment] 2022-10-26 14:59
> I can clone and test if you want

Yup, that would be awesome!

**Comment by trjExpensify** [comment] 2022-10-31 14:45
Any luck with that test, @Prince-Hamza?

**Comment by Prince-Hamza** [comment] 2022-10-31 15:39
there are errors installing and running app.i will give you final result tomorrow.

**Comment by eVoloshchak** [comment] 2022-10-31 15:46
> there are errors installing and running app

If you're experiencing issues while building android, changing [this](https://github.com/Expensify/App/blob/62ff507162d7712c2aa76b5eb96141f83ec2dd91/android/build.gradle#L48) line to 
`mavenCentral()` should help

**Comment by trjExpensify** [comment] 2022-11-03 22:15
@Prince-Hamza were you able to get setup to test here? Don't hesitate to let us know if you continue to struggle with that!

**Comment by trjExpensify** [comment] 2022-11-07 20:32
@Prince-Hamza any luck to progress with reviewing the feasibility of your proposal? 

In the meantime, the job has been doubled on Upwork to $1,000 and still open to proposals!

**Comment by cowboycito** [comment] 2022-11-07 20:57
@trjExpensify is this still open for proposals?

**Comment by jayeshmangwani** [comment] 2022-11-07 20:57
# Proposal

For making the PaymentsPage scrollable, we can replace View with FormScrollView 

https://github.com/Expensify/App/blob/aaea5578a819df555c509dfd7a4b14e5aa77bee2/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L272

```diff
+import FormScrollView from '../../../../components/FormScrollView';


-                <View style={styles.flex1}>
+                <FormScrollView style={styles.flex1}>

```

## Video After Fix

https://user-images.githubusercontent.com/35371050/200413727-298b7130-793d-41c1-b1bc-f1091839c644.mov

**Comment by trjExpensify** [comment] 2022-11-08 00:49
https://github.com/Expensify/App/issues/11695#issuecomment-1306180668 - Yes, @cowboycito! Anything with the `Help wanted` label is still open.

**Comment by huzaifa-99** [comment] 2022-11-08 08:06
I thought we were not handling landscape mode on mobile?

**Comment by trjExpensify** [comment] 2022-11-08 11:05
This is a mWeb issue. We can remove that line in the issue title though as I [commented here](https://github.com/Expensify/App/issues/11695#issuecomment-1273721371), as the problem exists in portrait mode.

**Comment by huzaifa-99** [comment] 2022-11-09 23:10
I believe there won't be a lot of payment methods to render here so maybe @gadhiyamanan suggestion of using `_map` instead of `FlatList` would work.

Thoughts @eVoloshchak

**Comment by eVoloshchak** [comment] 2022-11-10 12:25
> I believe there won't be a lot of payment methods to render here 

@huzaifa-99, that's a great point actually! 
If the list isn't overflowing the screen, there will be no performance difference between `flatList` and a simple list generated by `map`

@gadhiyamanan, are you still interested in working on this issue? If so, could you please update your proposal listing the screens that also need this fix?

> let's try to fix as many places as we can reasonably see would have the same issue. I don't think we need to be exhaustive, but I think we can do better than just fixing this single flow
It will be great if the proposal includes the solution for this specific case and also includes all the possible places that need to be fixed with that solution.

**Comment by gadhiyamanan** [comment] 2022-11-10 12:40
other pages are having scrolling issues on mWeb while mobile has on landscape mode and as per [slack discussion ](https://expensify.slack.com/archives/C01GTK53T8Q/p1666959007327629?thread_ts=1666928166.032089&cid=C01GTK53T8Q) it's not worth fixing for now

cc: @eVoloshchak

**Comment by trjExpensify** [comment] 2022-11-10 19:05
@gadhiyamanan this issue exists in portrait mode? CC: @sobitneupane from [here](https://github.com/Expensify/App/issues/11695#issuecomment-1274010949).

>I believe there won't be a lot of payment methods to render here

That's not true over the long term. This list and `Payments` page will grow, so we should be mindful of that.

**Comment by jayeshmangwani** [comment] 2022-11-11 07:33
# Updated Proposal

> @jayeshmangwani, thanks for the proposal! Wrapping the screen with `ScrollView` has been [proposed before](https://github.com/Expensify/App/issues/11695#issuecomment-1272769635), but it has the drawback of throwing a warning on native platforms `VirtualizedLists should never be nested inside plain ScrollViews`


@eVoloshchak we are using FlatList for the PaymentMethodList so the payment list is scrollable, so rather than creating another scrollable view let's just use the ListHeaderComponent prop of the FlatList for the wallet amount and payment methods title

 1. we have to create a prop in the PaymentMethodList page for ListHeaderComponent
 
https://github.com/Expensify/App/blob/ae385f9f676ba1527cf44fa5ec658072ba070113/src/pages/settings/Payments/PaymentMethodList.js#L213-L218
 ```diff
 +                     ListHeaderComponent={this.props.listHeaderComponent}
 ```
 2. pass the wallet amount and title to the header component of the flatlist so that top part of the BasePaymentsPage can be scrollable
  https://github.com/Expensify/App/blob/ae385f9f676ba1527cf44fa5ec658072ba070113/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L273-L310
  
 ```diff
 -{Permissions.canUseWallet(this.props.betas) && (
-    <>
-        <View style={[styles.mv5]}>
-            <OfflineWithFeedback
-                pendingAction={CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD}
-                errors={this.props.walletTerms.errors}
-                onClose={PaymentMethods.clearWalletTermsError}
-                errorRowStyles={[styles.ml10, styles.mr2]}
-            >
-                <CurrentWalletBalance />
-            </OfflineWithFeedback>
-        </View>
-        {this.props.userWallet.currentBalance > 0 && (
-            <KYCWall
-                onSuccessfulKYC={this.navigateToTransferBalancePage}
-                enablePaymentsRoute={ROUTES.SETTINGS_ENABLE_PAYMENTS}
-                addBankAccountRoute={ROUTES.SETTINGS_ADD_BANK_ACCOUNT}
-                addDebitCardRoute={ROUTES.SETTINGS_ADD_DEBIT_CARD}
-                popoverPlacement="bottom"
-            >
-                {triggerKYCFlow => (
-                    <MenuItem
-                        title={this.props.translate('common.transferBalance')}
-                        icon={Expensicons.Transfer}
-                        onPress={triggerKYCFlow}
-                        shouldShowRightIcon
-                        disabled={this.props.network.isOffline}
-                    />
-                )}
-            </KYCWall>
-        )}
-    </>
-)}
-<Text
-    style={[styles.ph5, styles.mt6, styles.formLabel]}
->
-    {this.props.translate('paymentsPage.paymentMethodsTitle')}
-</Text>
 ```
 https://github.com/Expensify/App/blob/ae385f9f676ba1527cf44fa5ec658072ba070113/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L318-L327
 ```diff
 +listHeaderComponent={()=>(
+    <>
+        {Permissions.canUseWallet(this.props.betas) && (
+            <>
+                <View style={[styles.mv5]}>
+                    <OfflineWithFeedback
+                        pendingAction={CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD}
+                        errors={this.props.walletTerms.errors}
+                        onClose={PaymentMethods.clearWalletTermsError}
+                        errorRowStyles={[styles.ml10, styles.mr2]}
+                    >
+                        <CurrentWalletBalance />
+                    </OfflineWithFeedback>
+                </View>
+                {this.props.userWallet.currentBalance > 0 && (
+                    <KYCWall
+                        onSuccessfulKYC={this.navigateToTransferBalancePage}
+                        enablePaymentsRoute={ROUTES.SETTINGS_ENABLE_PAYMENTS}
+                        addBankAccountRoute={ROUTES.SETTINGS_ADD_BANK_ACCOUNT}
+                        addDebitCardRoute={ROUTES.SETTINGS_ADD_DEBIT_CARD}
+                        popoverPlacement="bottom"
+                    >
+                        {triggerKYCFlow => (
+                            <MenuItem
+                                title={this.props.translate('common.transferBalance')}
+                                icon={Expensicons.Transfer}
+                                onPress={triggerKYCFlow}
+                                shouldShowRightIcon
+                                disabled={this.props.network.isOffline}
+                            />
+                        )}
+                    </KYCWall>
+                )}
+            </>
+        )}
+        <Text
+            style={[styles.ph5, styles.mt6, styles.formLabel]}
+        >
+            {this.props.translate('paymentsPage.paymentMethodsTitle')}
+        </Text>
+    </>
+)}
 ```

**Comment by mountiny** [comment] 2022-11-13 06:18
> cc: @mountiny since you first proposed to consider these kinds of issues not priority for now

We have since moved to bugZero, where any reproducible bug should be fixed and that is a priority. I think we should pick something which works fine here.

I think the ideal solution here is that the list is Scrollable only if it overflows.

**Comment by trjExpensify** [comment] 2022-11-14 12:45
>I think the ideal solution here is that the list is Scrollable only if it overflows.

I agree with that. It's also in-line with how we handle the `Workspaces`, `Settings` and `Profile` pages etc, right?

**Comment by eVoloshchak** [comment] 2022-11-16 17:21
@jayeshmangwani's [proposal](https://github.com/Expensify/App/issues/11695#issuecomment-1311334665) is great, using FlatList's header prop is the best approach we could take imo

With this change, we'd lose sticky header behavior for the amount, but that's the **expected result** I suppose?

Before:

https://user-images.githubusercontent.com/9059945/202249368-1f3d66a3-b4d8-4aaf-bb32-0473beb0460e.mov

After:


https://user-images.githubusercontent.com/9059945/202249410-4a0a40df-7e38-4fde-99f6-05adf2b84931.mov

**Comment by trjExpensify** [comment] 2022-11-16 23:57
Why is the `payment method` header above the wallet balance in that video? 🤔

**Comment by eVoloshchak** [comment] 2022-11-17 00:15
> Why is the `payment methods` header above the wallet balance in the `After` video? 🤔

My bad, probably didn't save a file
I've updated the `After` video

**Comment by trjExpensify** [comment] 2022-11-17 01:32
Ah, cool. @mountiny @marcochavezf, thoughts?

**Comment by mountiny** [comment] 2022-11-17 13:12
I agree, that looks good to me.

However, will this **NOT** scroll when the page is long enough right?

**Comment by eVoloshchak** [comment] 2022-11-17 16:55
It will have the same behavior as other settings pages (profile, preferences, etc): it will not scroll when the page is long enough on all platforms except for iOS. On iOS, scroll is always enabled, but that's how it is throughout the app

**Comment by trjExpensify** [comment] 2022-11-21 12:05
Okay cool, so what are the next steps here? @eVoloshchak if you're happy with the proposal, let's have @marcochavezf review it and @jayeshmangwani can get going.

**Comment by trjExpensify** [comment] 2022-11-21 14:12
Yes, let's apply the fix on the `Connect bank account` page (after a bank account has been added) in the workspace settings as well, I can't recall any others? 🤔

**Comment by eVoloshchak** [comment] 2022-11-21 14:51
I also can't find any other pages with this problem
@jayeshmangwani, please make sure to fix this for the `connect bank account` page also (I suppose the fix is the same?)
[Proposal](https://github.com/Expensify/App/issues/11695#issuecomment-1311334665) looks good to me, let's get the PR started
🎀👀🎀 C+ reviewed!

**Comment by jayeshmangwani** [comment] 2022-11-22 14:55
I am waiting for the @marcochavezf's green signal for my proposal 
cc: @eVoloshchak @trjExpensify

**Comment by jayeshmangwani** [comment] 2022-11-22 17:05
PR is up, 

added scrollable for, the payments page and connect bank account page.

cc: @eVoloshchak @marcochavezf

**Comment by trjExpensify** [comment] 2022-11-22 22:16
Awesome. Sent you both offers on Upwork [here](https://www.upwork.com/jobs/~01787df7c25949e98d).

**Comment by trjExpensify** [comment] 2022-11-24 16:41
PR has gone through C+ review, @marcochavezf this is over to you now! 🚀

**Comment by mvtglobally** [comment] 2022-11-30 05:07
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment] 2022-12-05 23:57
Alrighty, time to settle up!

- $250 to @sobitneupane for reporting 
- $1,500 to @jayeshmangwani for the fix incl. 50% bonus for a merge within 3 days
- $1,500 to @eVoloshchak for the review incl. 50% bonus for a merge within 3 days

Jayesh and Eugene, I've settled up. @sobitneupane you hadn't applied, so I've sent an offer.

**Comment by trjExpensify** [comment] 2022-12-06 00:02
>[@eVoloshchak / @marcochavezf] The PR that introduced the bug has been identified. Link to the PR:
>[@eVoloshchak / @marcochavezf] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

Eugene & Marco, any movement on these?

**Comment by sobitneupane** [comment] 2022-12-06 03:39
> @sobitneupane you hadn't applied, so I've sent an offer.

@trjExpensify Thanks for the offer. Accepted.

**Comment by trjExpensify** [comment] 2022-12-06 11:49
Cool, settled up with you @sobitneupane!

@marcochavezf, @eVoloshchak. Let's discuss the checklist so we can close this one out. 

- Was this a regression? If so, which PR? 

My take is that this was an oversight on the two pages we found with this issue (Connect Bank Account & Payments). It wasn't previously implement such that you could scroll the page and thereafter changed causing a regression. Can you confirm? 

- How can we prevent it from happening again? 

We can probably be better here to help inform contributors about the `Scrollview` component, as these pages weren't wrapped in that component right? If we agree on that, then where's the best place to surface this for future contributors? PR checklist? Curious for your thoughts.

**Comment by eVoloshchak** [comment] 2022-12-06 12:05
- Was this a regression? If so, which PR?

@trjExpensify, it was introduced by https://github.com/Expensify/App/pull/7088, but judging by the discussion it was the expected behavior back then

- How can we prevent it from happening again?

I also think adding it to the checklist is a good idea. That probably means something like "I tested all of the pages that are affected by this change in portrait orientation on mWeb"

**Comment by trjExpensify** [comment] 2022-12-06 22:49
>@trjExpensify, it was introduced by https://github.com/Expensify/App/pull/7088, but judging by the discussion it was the expected behavior back then

Ah, what about the `Connect bank account` page?

>"I tested all of the pages that are affected by this change in portrait orientation on mWeb"

Is this descriptive enough, what are they testing for specifically? The implied expectation is testing mWeb in portrait orientation isn't it, because we aren't focused on landscape. We already ask to test on all platforms (incl. mWeb).

**Comment by marcochavezf** [comment] 2022-12-07 01:24
> > @trjExpensify, it was introduced by #7088, but judging by the discussion it was the expected behavior back then
> 
> Ah, what about the `Connect bank account` page?

Yeah, for the `EnableStep` (`Connect bank account`) page, it was an oversight of not using `ScrollView` when it was implemented. I think the PaymentsPage could also eventually use ScrollView (to keep the pages uniform with the ScrollView implementation), but that would require refactoring PaymentMethodList to use `_.map` to render the payment methods.

Said that I agree and I think it would be enough to add a new item in the checklist about the use of `ScrollView` on new pages. It could be something like: `If a new page is added, I verified it's using the ScrollView component to make it scrollable in landscape mode or when more elements are added to the page.`

**Comment by marcochavezf** [comment] 2022-12-07 01:34
For the checklist item, I created this [PR](https://github.com/Expensify/App/pull/13388).

**Comment by trjExpensify** [comment] 2022-12-07 01:39
I'm about to head out for the night, but hang fire on merging the PR. We should discuss it more widely about whether we want to add it first as per the checklist item instruction:

> [@eVoloshchak / @marcochavezf] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:


>If a new page is added, I verified it's using the ScrollView component to make it scrollable in landscape mode or when more elements are added to the page.

I'm not sure about the landscape framing in this as we aren't focused on that and this implies we are, but I can understand the point about when more elements are added to the page etc.

**Comment by marcochavezf** [comment] 2022-12-07 01:42
>I'm not sure about the landscape framing in this as we aren't focused on that and this implies we are, but I can understand the point about when more elements are added to the page etc.

Good point, we can remove the landscape part: 

`If a new page is added, I verified it's using the ScrollView component to make it scrollable when more elements are added to the page.`

**Comment by marcochavezf** [comment] 2022-12-08 01:25
Ah, not all the pages are using `ScrollView`, but I think the contributor and reviewer should be aware of using it for new pages. Asking [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1670462665971449) for more opinions.

**Comment by trjExpensify** [comment] 2022-12-09 15:35
Cool, so that's done and should be enough to catch it going forward. Closing it out! :)

**Closed by trjExpensify** 2022-12-09 15:35 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
