### ISSUE TITLE
[Hold #20841][$1000] IOS - Assign task - Multiline description is displayed as one line

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21825] opened 2023-06-28 17:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21371
## Action Performed:
1. Login to NewDot iOS app
2. Assign a task with multi-line description
3. Task chat is displayed

## Expected Result:
There should be indication, that description has additional lines except first one, which are not displayed until you expand it

## Actual Result:
Multiline description is displayed as one line (there is no any indication that there are any more line except for the first one)
Only iOS. Android has "..." and web shows all description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34.
1
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/189bd1c4-d486-44d5-ad94-dffa311aa61c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cab68f81113415f5</li>
        <li>Upwork Job ID: 1674777522394394624</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by manjesh-yadav** [comment] 2023-06-28 19:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Assign task - Multiline description is displayed as one line
### What is the root cause of that problem?
Here we are using  `MenuItemWithTopDescription` component which is generally used for one-line or two-line headings that is why multiline descriptions are displayed as one line


### What changes do you think we should make in order to solve the problem?

We should redesign our description text in `src/components/TaskHeader.js` and not change in `MenuItemWithTopDescription` as this component use many places
https://github.com/Expensify/App/blob/de9cec890a758938f309d281ad53a2ff76b1c4de/src/components/TaskHeader.js#L128-L135

change this with the below initial design
```js
<PressableWithFeedback
                onPress={() => Navigation.navigate(ROUTES.getTaskReportDescriptionRoute(props.report.reportID))}
                disabled={!isOpen}
                accessibilityRole="button"
            >
                    <View style={[styles.ph5, styles.pb5]}>
                        <Text
                            style={[styles.pre, styles.textLabelSupporting]}
                        >
                           {props.translate('newTaskPage.description')}
                        </Text>
                        <Text
                            style={[styles.headerText, styles.pre]}
                        >
                           {lodashGet(props.report, 'description', '')}
                        </Text>
                    </View>
            </PressableWithFeedback>
```
<details>

<summary> Result</summary>

![IMG_0501](https://github.com/Expensify/App/assets/70934016/11b55167-de24-4d15-8ae6-2d09707e1534)

</details>

**Comment by sonialiap** [comment] 2023-06-30 13:50
Reproducible, triaging to external

**Comment by sonialiap** [comment] 2023-07-03 15:39
@fedirjh we have a proposal above, could you take a look to see if we can move forward with it?

**Comment by thienlnam** [comment] 2023-07-03 17:43
Agreed with @fedirjh

**Comment by sonialiap** [comment] 2023-07-06 21:39
Sounds good, adding hold to title

**Comment by Christinadobrzyn** [comment] 2023-07-10 19:51
Hi @fedirjh @sonialiap would you be able to confirm if this issue is a dupe of this one? (I think so?)
https://github.com/Expensify/App/issues/22453

**Comment by sonialiap** [comment] 2023-07-14 12:03
Sounds good, closing

**Closed by sonialiap** 2023-07-14 12:03 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
