### ISSUE TITLE
[$500] LHN - Created Split Bill Group chat in offline displays in bottom in LHN

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30467] opened 2023-10-26 20:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
Precondition: user should be signed in to HT account with multiple chats in LHN
1. Open https://staging.new.expensify.com/
2. Disable internet connection
3. Click on FAB
4. Click on Request Money
5. Enter amount and click Next button
6. Select two or more attendees with non-existing account and Click next
7. On final confirmation page click Split button
8. Scroll down the LHN and find the created group chat position

## Expected Result:
Created Split Bill group chat should be displayed on top in LHN

## Actual Result:
Created split bill group chat displayed in bottom in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Safari ( The issue is not reproducible in Chrome browser)
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Safari</summary>

https://github.com/Expensify/App/assets/115492554/fed4df60-08eb-4fc6-9981-53dcac6d0d74

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ec1c10c1e85daae</li>
        <li>Upwork Job ID: 1717647104275853312</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by rojiphil** [comment] 2023-10-27 13:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When a money request is split with participants with whom there is no open IOU Report, the LHN displays the IOU Reports with such participants towards the end of the LHN. 

### What is the root cause of that problem?

When a split money request is created, the optimistic data of the IOU Report is set [here](https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/libs/actions/IOU.js#L172C1-L180C11). However, since this would be a new report `lastVisibleActionCreated` will not be set as seen in the optimistic creation of iou reports [here](https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/libs/actions/IOU.js#L1096C1-L1099C1). Since LHN sorts the reports based on `lastVisibleActionCreated` as shown [here](https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/libs/SidebarUtils.ts#L209C1-L220C6), the newly created IOU Reports will be displayed towards the end of LHN. This is the root cause.

### What changes do you think we should make in order to solve the problem?

To set `lastVisibleActionCreated` for newly created IOU Reports, we can set it to the report action like this [here](https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/libs/actions/IOU.js#L178)

```
                ...(isNewIOUReport ? {pendingFields: {createChat: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD}, lastVisibleActionCreated: iouAction.created} : {}),

```
### What alternative solutions did you explore? (Optional)

**Comment by samilabud** [comment] 2023-10-30 15:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN - Created Split Bill Group chat in offline displays in bottom in LHN

### What is the root cause of that problem?
The root cause is that Android only converts RTL text to LTR text using Unicode controls and by default, when you start writing in a language that is written in RTL mode it converts the input text to RTL.

### What changes do you think we should make in order to solve the problem?
The best solution is to add \u2066 unicode character before starting to write, I suggest modifying the next function (`updateComment`):

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L213

This is the result:

https://github.com/Expensify/App/assets/5216036/3ed28629-258e-446c-9a82-6e6438f7dbfe

**Comment by twisterdotcom** [comment] 2023-10-31 17:23
Bump here @rushatgabhane.

**Comment by rojiphil** [comment] 2023-11-01 22:31
Dupe of #30472

**Comment by twisterdotcom** [comment] 2023-11-02 22:22
Okay, lets close.

**Closed by twisterdotcom** 2023-11-02 22:22 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
