### ISSUE TITLE
[CRITICAL] Backwards Compatibility: When a report is submitted on NewDot, we’re sending two emails to the approver. One from OldDot, one from NewDot

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#33453] opened 2023-12-21 21:03 UTC
**Slack conversation:** https://expensify.slack.com/archives/C02MW39LT9N/p1703192299970489?thread_ts=1703187017.215259&cid=C02MW39LT9N

Note, to test this you must follow [these steps](https://stackoverflowteams.com/c/expensify/questions/17518) to have a collect workspace on newdot. 

## Action Performed:

1. As the member, go to NewDot
2. Go to global create (+) > Request money > enter an amount > confirm
3. Navigate to the expense report view
4. Tap the Submit button
5. Notice an email is sent from OldExpensify and NewExpensify

cc @puneetlath  

## Expected Result:

You get one email - but this might be expected and it could be something we change with our Wave 7 migration plans. 

## Actual Result:

You get two emails. 

## Screenshots/Videos

<img width="920" alt="image" src="https://github.com/Expensify/App/assets/51066321/27381b66-15a2-4cc0-87de-52344c94d075">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01049166d1dd9085c8</li>
        <li>Upwork Job ID: 1745295485071425536</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aldo-expensify</details>

**Comment by kadiealexander** [comment] 2023-12-22 03:30
I wasn't able to reproduce this one:

![image](https://github.com/Expensify/App/assets/59587260/eb32de49-64d2-46cd-8767-82e74105391a)

Have asked about the repro steps [here](https://expensify.slack.com/archives/C02MW39LT9N/p1703215674531249?thread_ts=1703187017.215259&cid=C02MW39LT9N). 

Just noting that I'm on leave from tomorrow until Jan 8th and will check in on my return, but please reassign if this needs to move before then!

**Comment by kadiealexander** [comment] 2024-01-08 05:53
Holding for @greg-schroeder to review as discussed [here](https://expensify.slack.com/archives/C02MW39LT9N/p1704359045663509?thread_ts=1703187017.215259&cid=C02MW39LT9N).

**Comment by kadiealexander** [comment] 2024-01-11 04:03
Not overdue.

**Comment by kadiealexander** [comment] 2024-01-11 04:05
@0xmiroslav could you please take a look and see if this could be worked on externally?

**Comment by aldo-expensify** [comment] 2024-01-15 15:43
Haven't worked on this yet, I'll pick it up in the asap

**Comment by aldo-expensify** [comment] 2024-01-16 21:33
Started looking into this, but I think we first have to decide what the Expected Outcome should be:

> You get one email - but this might be expected and it could be something we change with our Wave 7 migration plans.

Asking here: https://expensify.slack.com/archives/C02MW39LT9N/p1705440821021659?thread_ts=1703187017.215259&cid=C02MW39LT9N

**Comment by aldo-expensify** [comment] 2024-01-16 22:25
I think there is something missing in the testing steps. I only got one email "test-collect-email-wp-admin owes $23.00"

**Comment by aldo-expensify** [comment] 2024-01-19 22:09
PR: https://github.com/Expensify/Web-Expensify/pull/40602

**Comment by aldo-expensify** [comment] 2024-01-22 13:18
PR under review

**Comment by mallenexpensify** [comment] 2024-01-24 00:43
Removed @0xmiroslav as C+, I think automation failed and they weren't requested to the review the [PR that just hit staging](https://github.com/Expensify/Web-Expensify/pull/40602#issuecomment-1907150804).

**Comment by greg-schroeder** [comment] 2024-01-25 23:40
Adjusting the priority of this to fit migration plan

**Comment by greg-schroeder** [comment] 2024-01-25 23:41
Looks like this is finished up though!

**Comment by aldo-expensify** [comment] 2024-01-31 18:18
The [PR](https://github.com/Expensify/Web-Expensify/pull/40602) was merged and deployed a while ago. Have in mind that the OldDot notification will only be skipped if the manager has an account that is being redirected to NewDot.

**Closed by aldo-expensify** 2024-01-31 18:18 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
