### ISSUE TITLE
[$500] Live Markdown conflicting with auto text replacement in mac

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36188] opened 2024-02-08 23:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707431230675759

## Action Performed:
1. Open any report
2. Try to type the word "current" on mac Web
## Expected Result:
The word "current" should be typed out
## Actual Result:
The word "See yourrent" is the result. This is due to the default autocorrect which transforms `cu` into "see you". Normally, typing more characters wouldn't result in the autocorrect being used, but live markdown appears to have broken this so that the autocorrect is always applied.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e37feeb8-dab8-4d5f-b4d0-a882d292f08c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014026cc737dde97e6</li>
        <li>Upwork Job ID: 1755730686614876160</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2024-02-08 23:31
These are regressions from https://github.com/Expensify/App/pull/35837, keeping track of them in https://github.com/Expensify/App/issues/36071

**Comment by mallenexpensify** [comment] 2024-02-09 15:20
@thienlnam , is this the same or should I file a new bug report?

https://github.com/Expensify/App/assets/22508304/7e4a7b7c-2ee7-4048-9cce-770d13a31481

**Comment by thienlnam** [comment] 2024-02-09 19:52
That looks pretty related, I'm guessing it's the same root cause so we can keep track of it in this issue as well

**Comment by thienlnam** [comment] 2024-02-21 17:45
Not a current bug, but being worked on as part of https://github.com/Expensify/App/issues/36071

**Comment by thienlnam** [comment] 2024-02-29 23:56
Latest update: https://expensify.slack.com/archives/C06BDSWLDPB/p1709233583044319?thread_ts=1708724096.745109&cid=C06BDSWLDPB

**Comment by thienlnam** [comment] 2024-03-12 19:34
Resolved in the repo

**Closed by thienlnam** 2024-03-12 19:34 UTC
Labels: Engineering, Weekly, Overdue
