### ISSUE TITLE
[$500] App displays invalid date error for selecting first enabled date in step 3 add bank account

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#27406] opened 2023-09-14 03:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->bank account->connect manually
3. Fill in details of step 1 and step 2 and continue
4. On step 3, fill in all the details, in date of birth, select first possible selectable date eg: Currently first possible selectable date is 23/08/1873
5. Click on continue, observe it will display 'Please provide a valid Date of birth' error

Expected Result: App should either disable that first date as we have disabled other invalid options or should not throw an error to it when selected for Date of birth in connect bank account

## Expected Result:
App should either disable that first date as we have disabled other invalid options or should not throw an error to it when selected for Date of birth in connect bank account

## Actual Result:
App displays invalid date error for selecting first enabled date in Date of birth field of step 3 of connect bank account

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/eb9709c3-3cd3-4146-b3d2-a065ca44f41b

![Screen Shot 2023-09-13 at 11 43 08 PM](https://github.com/Expensify/App/assets/43995119/08bd1542-9684-480d-b296-f075f67157e8)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692806921754809 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111c674e017e53585</li>
        <li>Upwork Job ID: 1702166202759577600</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by poemsforaphrodite** [comment] 2023-09-14 08:28
this is not a bug
dupe of #24377

**Comment by Christinadobrzyn** [comment] 2023-09-14 20:50
I agree this is similar to https://github.com/Expensify/App/issues/24377 - I don't think this is a bug and this is a feature request instead.

**Closed by Christinadobrzyn** 2023-09-14 20:50 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by dhanashree-sawant** [comment] 2023-09-15 05:01
Hi @Christinadobrzyn, #24377 is for not displaying error when invalid date is entered, in this issue, the date is valid as selectable from datepicker. Here we just need to disable first possible enabled date as we disable other invalid date as server side logic considers that as invalid.
