### ISSUE TITLE
[One expense reports] [$250] Deleting an expense on a one-expense report doesn’t delete the corresponding report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41656] opened 2024-05-05 15:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714841273549179

## Action Performed:
1. Go to a workspace chat
2. Click plus and Submit expense
3. Navigate to the report
4. Write a comment or two
5. Choose Delete expense in the three-dot overflow menu
6. Navigate back to the workspace chat
## Expected Result:
The one-expense report is deleted along with expense
## Actual Result:
The one-expense report remains with a $0 balance
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-05-04 at 10 47 59@2x](https://github.com/Expensify/App/assets/38435837/2d357dc6-82e0-4474-bf8e-aeea03bbd804)

https://github.com/Expensify/App/assets/38435837/ab51b124-8426-433e-865d-afdcbd071da3

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159a6f1b83dfeb303</li>
        <li>Upwork Job ID: 1787848035385294848</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2024-05-06 12:28
For clarity, in the case that a one-expense report is deleted and it has comments from users, we should use the existing pattern, which is:

- The report appears as `[Deleted report]` 
- User comments are saved
- The report is converted to a `chat` report so that the `expense` report totals and report fields are no longer visible.

**Comment by trjExpensify** [comment] 2024-05-07 10:06
@JmillsExpensify did we make this change somewhere else, can you link me to it? 

>The report is converted to a chat report so that the expense report totals and report fields are no longer visible.

**Comment by amyevans** [comment] 2024-05-07 13:19
Yep that's where we landed - implemented in https://github.com/Expensify/Auth/pull/10640, there's some screenies and a vid in there

**Comment by trjExpensify** [comment] 2024-05-07 14:12
Nice! Moving it on!

**Comment by nkdengineer** [comment] 2024-05-07 14:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The one-expense report remains with a $0 balance

### What is the root cause of that problem?
When deleting the money request [here](https://github.com/Expensify/App/blob/222419b8a5d439e8360d269b37ebc6840bd4c22b/src/libs/actions/IOU.ts#L5034), if it's single transaction view, we're not setting the status of the IOU report to `CLOSED`, so it doesn't satisfy [this condition](https://github.com/Expensify/App/blob/222419b8a5d439e8360d269b37ebc6840bd4c22b/src/pages/home/report/ReportActionItem.tsx#L535) and does not show `[Deleted report]` correctly. 

### What changes do you think we should make in order to solve the problem?

When deleting the money request [here](https://github.com/Expensify/App/blob/222419b8a5d439e8360d269b37ebc6840bd4c22b/src/libs/actions/IOU.ts#L5034), if it's single transaction view, we should set the status of the IOU report to `CLOSED`.

Eg. in [here](https://github.com/Expensify/App/blob/80a9d707964716b6b98b9a279b42ad9676686573/src/libs/actions/IOU.ts#L5096) we can add
```
if (isSingleTransactionView) {
    updatedIOUReport.statusNum = CONST.REPORT.STATUS_NUM.CLOSED;
}
```
We can make the condition more specific like if it's `isSingleTransactionView` and `shouldDeleteIOUReport`

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-05-07 15:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The one-expense report remains with a $0 balance

### What is the root cause of that problem?
When deleting the money request [here](https://github.com/Expensify/App/blob/222419b8a5d439e8360d269b37ebc6840bd4c22b/src/libs/actions/IOU.ts#L5034), if it's single transaction view, we're not setting the status of the IOU report to `CLOSED`, so it doesn't satisfy [this condition](https://github.com/Expensify/App/blob/222419b8a5d439e8360d269b37ebc6840bd4c22b/src/pages/home/report/ReportActionItem.tsx#L535) and does not show `[Deleted report]` correctly. 

### What changes do you think we should make in order to solve the problem?

1. When deleting the money request [here](https://github.com/Expensify/App/blob/222419b8a5d439e8360d269b37ebc6840bd4c22b/src/libs/actions/IOU.ts#L5034), if it's single transaction view, we should set the status of the IOU report to `CLOSED`.

Eg. in [here](https://github.com/Expensify/App/blob/80a9d707964716b6b98b9a279b42ad9676686573/src/libs/actions/IOU.ts#L5101) we can add
```
if (isSingleTransactionView) {
    updatedIOUReport.statusNum = CONST.REPORT.STATUS_NUM.CLOSED;
}
```
We can make the condition more specific like if it's `isSingleTransactionView` and `shouldDeleteIOUReport` is `false` (because if `shouldDeleteIOUReport` we just delete the IOU report and doesn't need to update the status)

2. Optionally, we also need to update [here](https://github.com/Expensify/App/blob/80a9d707964716b6b98b9a279b42ad9676686573/src/libs/ReportUtils.ts#L1497) so that the user cannot add transactions to a deleted single-transaction IOU report
```
if (moneyRequestReport?.statusNum === CONST.REPORT.STATUS_NUM.CLOSED) {
    return false;
}
```
3. To make sure it works for personal IOU, we will need to expand the condition [here](https://github.com/Expensify/App/blob/80a9d707964716b6b98b9a279b42ad9676686573/src/libs/ReportUtils.ts#L1216) so that it will also apply to IOU report, not just expense report

### What alternative solutions did you explore? (Optional)
NA

**Comment by trjExpensify** [comment] 2024-05-09 15:16
@akinwale can you review this proposal today please? Thanks!

**Comment by kmbcook** [comment] 2024-05-09 17:36
> Yep that's where we landed - implemented in https://github.com/Expensify/Auth/pull/10640, there's some screenies and a vid in there

@amyevans I changed "Auth" to "App" in the link above but it still doesn't look like the right PR to me.

**Comment by amyevans** [comment] 2024-05-09 18:11
@kmbcook the link was to a backend PR which has restricted access. You can see the existing pattern of
> The report appears as [Deleted report]
> User comments are saved
> The report is converted to a chat report so that the expense report totals and report fields are no longer visible.

by following these steps though:
1. As a member of a collect policy with the workspace chat beta enabled, create an expense report with at **two expenses** and at least **one comment**
2. Delete the report in OldDot

https://github.com/Expensify/App/assets/7277067/c6ccd76d-121d-45c9-be71-4b00cea7b1c7

So in this GH we are expecting that an expense report with **one expense** and **1+ comments**, when deleted, displays the same as shown above

**Comment by kmbcook** [comment] 2024-05-09 23:03
Looks to me like this is a backend change. For DeleteMoneyRequest, all the app essentially does is to send transactionID and reportActionID. The backend does everything else.

**Comment by kmbcook** [comment] 2024-05-10 01:12
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
Deleting an expense on a one-expense report doesn’t delete the corresponding report

### What is the root cause of that problem?
The backend does not change the expense report to a chat report, in this situation.

### What changes do you think we should make in order to solve the problem?
In the one-expense view check to see if all IOU actions of the expense report are marked as deleted. If so, change the view as if the report were a chat report. Do the same for the expense report preview.

**Comment by akinwale** [comment] 2024-05-10 06:26
We can move forward with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/41656#issuecomment-2098723314) here.

🎀👀🎀 C+ reviewed.

**Comment by kmbcook** [comment] 2024-05-10 14:36
@akinwale, I could be missing something but it appears to me that nkdengineer's proposal will not work. His proposal is to set the status of the IOU report to closed, by setting the status of the optimistically generated IOU report to closed. The change to optimistic data is temporary, right?

**Comment by blimpich** [comment] 2024-05-10 17:56
@kmbcook I think it should work. I believe the optimistic data is being set to make sure that the app still works well even if the user's internet cuts out. The problem is not that the expense isn't being handled correctly in the backend, its that the frontend doesn't correctly render it. We want the UI to change in response to the user deleting the expense report immediately. And as @nkdengineer said in their proposal, setting that piece of state will mean that when we hit [this conditional](https://github.com/Expensify/App/blob/222419b8a5d439e8360d269b37ebc6840bd4c22b/src/pages/home/report/ReportActionItem.tsx#L535) we will correctly render the report.

**Comment by kmbcook** [comment] 2024-05-11 17:38
> For clarity, in the case that a one-expense report is deleted and it has comments from users, we should use the existing pattern, which is:
> 
> * The report appears as `[Deleted report]`
> * User comments are saved
> * The report is converted to a `chat` report so that the `expense` report totals and report fields are no longer visible.

@blimpich the only way I can see for the third requirement above to be satisfied, to convert the expense report to a chat report, is for the backend to do it.

**Comment by nkdengineer** [comment] 2024-05-13 04:21
@akinwale The PR is [here](https://github.com/Expensify/App/pull/42031).

**Comment by kmbcook** [comment] 2024-05-14 17:59
@akinwale I can see from the submitted PR that the originally approved proposal does not work. What do you think of my proposal?

**Comment by blimpich** [comment] 2024-05-17 21:43
@kmbcook I think you were right to say this really is an internal issue. This should not be fixed externally. Apologies for not realizing that sooner.

@akinwale please take note so that in the future we can mark issues like this as internal sooner rather than later.

I can't prioritize this right now but I'll mark this as internal and a hot pick and leave some of my investigation notes for whoever picks this up.

**Comment by blimpich** [comment] 2024-05-17 22:02
**Investigation notes:**

I looked more deeply into this issue after the proposed PR ran up against a seemingly incorrect backend response ([link](https://github.com/Expensify/App/pull/42031#issuecomment-2112210180)). I was aware of [this PR](https://github.com/Expensify/Auth/pull/10640) which made it so that reports with comments that are deleted in old dot are converted into chats so that their history can be preserved, so I presumed that we must be calling this command incorrectly when deleting from new dot and therefore it should be a frontend issue.

However, when clicking "delete expense" in new dot we aren't actually calling `auth/command/DeleteReport.cpp` under the hood, we are calling `auth/command/DeleteMoneyRequest.cpp`. So the problem most likely lies in there, in the backend. 

The core of the logic that is executed as part of the DeleteMoneyRequest command is in `Transaction::deleteMoneyRequest`. That is a 200 line function that has [comments](https://github.com/Expensify/Auth/blob/main/auth/lib/Transaction.cpp#L2821) that indicate that it should already be properly handling this scenario where a deleted report has comments that we want to preserve, but it doesn't seem to be working correctly.

I imagine the fix involves extracting the logic for what is done in [this PR](https://github.com/Expensify/Auth/pull/10640/files) and gluing that together in `Transaction::deleteMoneyRequest`. But I'm unsure if `Transaction::deleteMoneyRequest` has a bug or just never handled this scenario to begin with. Whatever we do we should not make `Transaction::deleteMoneyRequest` more complicated than it already is. It's already gigantic and too complicated to be considered at all readable.

**Comment by mountiny** [comment] 2024-05-20 19:54
I would say this case was definitely working fine before as its quite simple case to test. I am wondering if we are passing wrong data to the backend with the one-expense view.

Is the transactionID and reportActionID [correct](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/MoneyReportHeader.tsx#L166) when calling the deleteMoneyRequest in case of one expense report @blimpich ?

**Comment by blimpich** [comment] 2024-05-20 20:59
From what I can see yes, the correct transactionID and reportActionID are being passed.

![Screenshot 2024-05-20 at 1 58 10 PM](https://github.com/Expensify/App/assets/17171674/5c94f8d2-57a2-4822-8eb3-f714356cd822)
![Screenshot 2024-05-20 at 1 58 19 PM](https://github.com/Expensify/App/assets/17171674/8ca5c52b-75a5-4ecb-8635-92a757aa3bd1)

**Comment by rlinoz** [comment] 2024-05-29 23:40
Asked for a Auth deploy.

**Comment by rlinoz** [comment] 2024-05-31 13:07
Deployed to prod https://github.com/Expensify/Auth/pull/10979#issuecomment-2140490642

**Closed by rlinoz** 2024-05-31 13:07 UTC
Labels: Weekly, Internal, Bug
