### ISSUE TITLE
[$250] Split - Individual split amount reverts to previous amount when returning from member selection page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42537] opened 2024-05-23 16:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Split expense
3. Enter amount X and select participants
4. On confirmation page, the individual split amount for each member is x
5. Click Amount
6. Change to amount Y so that the individual split amount for each participant is y
7. Click on the back button to return to participant selection page
8. Hit Next button

## Expected Result:
The individual split amount will remain y because the split amount is Y

## Actual Result:
The individual split amount becomes x when the split amount is Y

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d9c7ea01-4b6d-4921-9c5a-58a2650cebf5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013636955ff301674e</li>
        <li>Upwork Job ID: 1800212211980093639</li>
        <li>Last Price Increase: 2024-06-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by lanitochka17** [comment] 2024-05-23 16:21
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-23 16:21
We think that this bug might be related to #vip-split

**Comment by bernhardoj** [comment] 2024-05-24 03:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The split share of individual amount is reset back to the previous amount when go back to participant selector and then go next again.

### What is the root cause of that problem?
When we go next from the participant page, we calculate the split amount based on the transaction amount.
https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/pages/iou/request/step/IOURequestStepParticipants.tsx#L106-L114

When we update the amount, the transaction amount gets updated, so the function should work normally. However, even though the transaction data is updated, the function itself `goToNextStep` that is called in `MoneyRequestParticipantsSelector`,
https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/pages/iou/request/step/IOURequestStepParticipants.tsx#L151-L154

The `onFinish` callback still holds the old reference of `goToNextStep` which holds the old reference of the transaction amount. It's because we memoize the component,
https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L372-L376

but doesn't check for the `onFinish` callback props.

### What changes do you think we should make in order to solve the problem?

Add `onFinish` comparison to the memo.
`prevProps.onFinish === nextProps.onFinish && ...`

The other props that is not added to the comparison is `onParticipantsAdded` & `action`. We can optionally add them or just remove the memoization.

**Comment by zanyrenney** [comment] 2024-06-10 17:03
yikes, this got assigned after I was OOO.

**Comment by zanyrenney** [comment] 2024-06-10 17:03
Adding external label to get the proposal reviewed.

**Comment by zanyrenney** [comment] 2024-06-10 17:04
hey @abdulrahuman5196 we already have a proposal above, please can you review it and let me know what you think here? Thank you!

**Comment by zanyrenney** [comment] 2024-06-12 09:55
bump @abdulrahuman5196 please can you review the two proposals?

**Comment by zanyrenney** [comment] 2024-06-18 18:04
We have paused work on split, so closing this out for now.

**Closed by zanyrenney** 2024-06-18 18:04 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
