### ISSUE TITLE
[HOLD for #30153 - $500] The selected attachment modal don't hide when drag a file

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27564] opened 2023-09-15 20:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report
2. Click +
3. Click Add Attachment
4. Drag a file to report screen
## Expected Result: 
The selected attachment modalshould hide when drag a file
## Actual Result: 
The selected attachment modal don't hide when drag a file

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.70-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cda42b5d-5049-4155-bb9d-c7f9245afa0c

https://github.com/Expensify/App/assets/43996225/83224e1d-09af-4f3a-b822-9df37623e136

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694578316488209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148455e0883b1f9ba</li>
        <li>Upwork Job ID: 1702778220407894016</li>
        <li>Last Price Increase: 2023-10-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by raymondchooi** [comment] 2023-09-15 21:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

File picker does not close on file drag and drop

### What is the root cause of that problem?

The user is allowed to drop files in the `<ReportDropUI />` component while the file picker is open.

### What changes do you think we should make in order to solve the problem?

1) When the picker is opened with `Add attachment`:

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/components/AttachmentPicker/index.js#L80

2) We can call another function to set the state `setIsAttachmentPreviewActive` to false:

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L239

3) We should probably rename this state to something like `setIsAttachmentPicking`

### What alternative solutions did you explore? (Optional)

As we have limited access to the file picker, we could listen for images dropped and force a redirect or similar to trigger the file picker to close

**Comment by peterdbarkerUK** [comment] 2023-09-19 09:32
Discussed a little [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1695114320660199?thread_ts=1695110083.825969&cid=C01SKUP7QR0).

**Comment by raymondchooi** [comment] 2023-09-19 14:04
@peterdbarkerUK ignore if the discussion link wasn't meant to be seen externally but I can't access the link or see/find any other discussions other than the initial linked slack discussion

**Comment by peterdbarkerUK** [comment] 2023-09-21 02:52
Hey @raymondchooi - yes, that one was private, left it here for my own ease of tracking! Apologies for the confusion

**Comment by peterdbarkerUK** [comment] 2023-09-25 14:22
@situchan - what do you think of the proposal?

**Comment by situchan** [comment] 2023-10-03 11:32
Let's fix this case as well so ideally all popovers, system modals should be closed while dragging file.

https://github.com/Expensify/App/assets/108292595/2745c4e9-521d-4b8a-85cc-17bdad4f7da2

Still open for better proposals

**Comment by peterdbarkerUK** [comment] 2023-10-09 12:48
@raymondchooi bump on this :)

**Comment by peterdbarkerUK** [comment] 2023-10-12 22:36
ya agreed. I am gonna sense check and come back to this tomorrow.

**Comment by DylanDylann** [comment] 2023-10-13 07:39
@peterdbarkerUK @situchan The file picker dialog can only be controlled by the user through standard interaction, such as selecting a file or canceling the operation. It cannot be dismissed or closed by JavaScript code for security reasons. This is to ensure that the user always has control over what files are selected and uploaded.
I think we need to updated the expected for this one

**Comment by situchan** [comment] 2023-10-13 12:03
still looking for solution to close popover as in [this video](https://github.com/Expensify/App/issues/27564#issuecomment-1744774749)

**Comment by peterdbarkerUK** [comment] 2023-10-13 12:10
I've not yet had a response to my internal question, let's hold further work on this for now :)

**Comment by peterdbarkerUK** [comment] 2023-10-16 20:28
Waiting til tomorrow to start bumping people for a response

**Comment by peterdbarkerUK** [comment] 2023-10-17 08:36
Bumped it [internally](https://expensify.slack.com/archives/C01SKUP7QR0/p1697531745839029?thread_ts=1697492599.331149&cid=C01SKUP7QR0)

**Comment by DylanDylann** [comment] 2023-10-19 03:46
I am not sure, @situchan Could you help to give your thought?

**Comment by situchan** [comment] 2023-10-24 09:09
Agree to do nothing on system file picker. But we can still fix our own popover cases - https://github.com/Expensify/App/issues/27564#issuecomment-1744774749

**Comment by DylanDylann** [comment] 2023-10-24 11:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The action modal in composer don't hide when drag a file

### What is the root cause of that problem?
We don't have any logic to hide the action modal when isDraggingOver is true

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/cc3c51c1d58ce013e444b59bd06c87e4b750e550/src/components/DragAndDrop/Provider/index.js#L37
Here we should set a new field on ONYX called isDraggingOver with the value is true

And then in here
https://github.com/Expensify/App/blob/cc3c51c1d58ce013e444b59bd06c87e4b750e550/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L145
we should create new useEffect to setMenuVisibility(false) if isDraggingOver is true

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2023-10-27 13:43
Let's see if we can fix without introducing new Onyx key

**Comment by DylanDylann** [comment] 2023-11-01 09:06
@situchan 
# Proposal
[Updated proposal](https://github.com/Expensify/App/issues/27564#issuecomment-1777043363)

**Comment by situchan** [comment] 2023-11-02 10:37
@DylanDylann let's try to find general solution


https://github.com/Expensify/App/assets/108292595/a8ef8ea8-40a2-45e4-a92d-70484a833cf4

**Comment by DylanDylann** [comment] 2023-11-03 10:27
@situchan Currently, we only detect dragging state based on DragAndDropContext.isDraggingOver. But DragAndDropContext only cover this part 

<img width="1343" alt="Screenshot 2023-11-03 at 17 22 13" src="https://github.com/Expensify/App/assets/141406735/d7071ea6-b1c1-4459-bb3d-a08e7a1cdc5f">

I think when dragging over we only need to hide modal in the drag area. what do you think about my suggestion?

**Comment by peterdbarkerUK** [comment] 2023-11-07 21:12
@situchan could you @DylanDylann's proposal? Thx!

**Comment by peterdbarkerUK** [comment] 2023-11-13 14:47
Friendly bump on this one @situchan :)

**Comment by DylanDylann** [comment] 2023-11-23 09:19
@situchan It seems we have another PR handle [this issue](https://github.com/Expensify/App/pull/31154)

**Comment by situchan** [comment] 2023-11-27 14:40
@peterdbarkerUK let's hold this for https://github.com/Expensify/App/issues/30153. I subscribed to [that PR](https://github.com/Expensify/App/pull/31154) so we'll see how it goes.

**Comment by situchan** [comment] 2023-12-01 12:20
Holding PR is still in review

**Comment by situchan** [comment] 2023-12-05 00:05
https://github.com/Expensify/App/pull/31154 was merged today. Waiting for hitting production

**Comment by DylanDylann** [comment] 2023-12-08 06:31
Can't reproduce anymore. let's close this

**Comment by situchan** [comment] 2023-12-08 11:56
Let's close

**Closed** 2023-12-12 20:47 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
