### ISSUE TITLE
IOU - In online, the app crashes after paying money in offline and deleting request money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27799] opened 2023-09-19 16:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: use two devices: main device and secondary device
1. Go to staging.new.expensify.com on both devices
2. Open a chat with the user that is logged in a secondary device
3. Secondary device - Request money to the account logged in the main testing device
4. Verify a green dot (GBR) is displayed in the LHN conversation
5. Disable the internet connection in the main device
6. Pay the IOU
7. Secondary Device - Delete the IOU
8. Enable the internet connection in the main device

## Expected Result:
The app must not crash when user returns to online while navigating to LHN

## Actual Result:
The app crashes when user returns to online while navigating to LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/74611fec-3aa0-4d19-8482-1e73ee87d966

https://github.com/Expensify/App/assets/78819774/74f6b0cd-02dc-4e9f-814b-ef21506c9fab

[log.txt](https://github.com/Expensify/App/files/12664208/log.txt)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2023-09-20 19:41
The steps in the OP don't seem to be in the correct order and I can't reproduce this

After a report is paid, I can't find the method to delete it in the Android app

this is causing me to not be able to test this. The OP steps need to be updated if this is still happening.

**Comment by kbecciv** [comment] 2023-09-21 18:40
Hey @Christinadobrzyn! Sorry for the confusion, I just cross checked the issue and reproduction steps. 
What I found:
1. Issue found when executing TR https://expensify.testrail.io/index.php?/tests/view/3675009
2. Tester used 2 platforms the same time.
I checked on two platforms (mWeb and Web) and issue is not reproducible on build 1.3.72.9

https://github.com/Expensify/App/assets/93399543/f811fff1-d212-4676-8079-6a43c475cd5f

https://github.com/Expensify/App/assets/93399543/304f7776-380e-4c46-8a06-dfd58facb5f7

**Comment by Christinadobrzyn** [comment] 2023-09-22 18:57
Thanks @kbecciv! 

I can't reproduce this on v1.3.73-0 so I think we can just close this for now. 
I checked on two platforms (mWeb and Web) Samsung 22

**Closed by Christinadobrzyn** 2023-09-22 18:57 UTC
Labels: Daily, Needs Reproduction, Bug
