### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250] Android - Workspace -  Workspace name is not displayed when navigate via join link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44639] opened 2024-06-28 18:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a470@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. [User B] Copy a workspace join link that User A is not a member
2. [User A] Open the workspace join link

## Expected Result:
Workspace name should be displayed when User A open join link

## Actual Result:
Workspace name is not displayed when navigate to Workspace via join link until the member is accepted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![mage__1_ (1)](https://github.com/Expensify/App/assets/78819774/463530a2-3659-40b3-8bcf-0c4b27c48610)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138fb5ddd26e517e8</li>
        <li>Upwork Job ID: 1807485642236308668</li>
        <li>Last Price Increase: 2024-06-30</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 102948824</li>
<li>bernhardoj | Contributor | 102948826</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by bernhardoj** [comment] 2024-06-29 05:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pending join WS name isn't displayed in small screen.

### What is the root cause of that problem?
The requested badge takes the whole space which hides the workspace name. (the green box is the requested badge container box)
<img width="378" alt="Screenshot 2024-06-29 at 13 17 59" src="https://github.com/Expensify/App/assets/50919443/540efc54-466e-4499-9d89-0e9aec1edc19">

The badge view is wrapped with 2 view.
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/pages/workspace/WorkspacesListRow.tsx#L145-L148

The first view, set the the flex1 style. The flex1 style will grow/shrink based on the space. However, the second View wrapper doesn't limit the width. 

For example, if we set it to 50px width, then the WS name will be visible. Or if we set the flex1 to the second View, then the WS name will be visible too. But I think we don't have a static width for the container for now and we don't want to set the flex1 because it means it will have equal width between the Requested badge and the WS avatar + name.

### What changes do you think we should make in order to solve the problem?

Remove the badge view wrapper flex1 style
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/pages/workspace/WorkspacesListRow.tsx#L147-L148

But we have another problem. If you notice, the Requested badge is overflown the green box container and also not centered.
<img width="374" alt="Screenshot 2024-06-29 at 13 14 03" src="https://github.com/Expensify/App/assets/50919443/f480963f-3ceb-4061-93d4-4a3ea13db7be">

That's because of the `workspaceListBadge` style, so we need to remove it too.
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/styles/index.ts#L3357-L3361

Last, another existing issue in large screen the requested badge doesn't have the same width as the 3-dot.
<img width="798" alt="image" src="https://github.com/Expensify/App/assets/50919443/274a9e73-f8a9-46a8-9dd0-3d633a98a357">

We can add padding left of 20 to the badge (large screen only) or have a static width for it, for example 128 (the 3-dot width).
<img width="810" alt="image" src="https://github.com/Expensify/App/assets/50919443/736ee1a6-16b4-4868-9f5b-4b631dea1cca">

Result on small screen
<img width="393" alt="image" src="https://github.com/Expensify/App/assets/50919443/d5316d01-929a-4a64-b306-d317e3c9350f">

**Comment by hungvu193** [comment] 2024-07-01 02:01
I'll review today!

**Comment by hungvu193** [comment] 2024-07-01 02:53
@bernhardoj ['s proposal here](https://github.com/Expensify/App/issues/44639#issuecomment-2197991216) looks good to me! 

🎀 👀 🎀  C+ reviewed

**Comment by bernhardoj** [comment] 2024-07-02 04:45
PR is ready

cc: @hungvu193

**Comment by bernhardoj** [comment] 2024-07-10 12:40
I'll request in ND once payment is due.

**Comment by bernhardoj** [comment] 2024-07-16 02:05
The payment should be due [tomorrow](https://github.com/Expensify/App/issues/44639#issuecomment-2220195477) (07-17)

**Comment by bernhardoj** [comment] 2024-07-17 03:00
Requested in ND.

**Comment by hungvu193** [comment] 2024-07-17 03:05
@lschurr I will also request on ND, I'll withdraw my upwork offer.

**Comment by hungvu193** [comment] 2024-07-17 03:24
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42017
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:https://github.com/Expensify/App/pull/42017/files#r1680353812
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug: YES

**Regression test:**
1. [User B] Copy a workspace join link that User A is not a member.
2. [User A] Open the workspace join link (On a mobile device).
3. Verify that workspace name display correctly.

Do we 👍  or  👎

**Comment by lschurr** [comment] 2024-07-17 16:43
Payment summary:

- Contributor: @bernhardoj $250 (To be paid in NewDot)
- Reviewer: @hungvu193 $250 (To be paid in NewDot)

**Comment by lschurr** [comment] 2024-07-17 16:46
Added QA test request. Closing :)

**Closed by lschurr** 2024-07-17 16:46 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-19 02:24
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment] 2024-07-19 02:43
$250 approved for @hungvu193
