### ISSUE TITLE
[$500]  Web - Workspace - The email address becomes "hidden"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35824] opened 2024-02-05 15:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35525
## Action Performed:
1. [User A] Create a private room and invite User B
2. [User B] Leave the room
3. [User A] Log out and log in again
4. [User A] Go to #admin room of the private workspace
5. [User A] Click on the room link in room leaving message

## Expected Result:
The email address should be still visible

## Actual Result:
The email address becomes "hidden". You can repro it on the primary device too after a relog

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1ce8236c-88d6-49c6-8f26-491855ed1ab5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf7f3242fc62d0cc</li>
        <li>Upwork Job ID: 1754527920681496576</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2024-02-05 22:12
Hmm, I can't reproduce the message showing as `Hidden` here. Closing, as this doesn't seem to be reproducible.

**Closed by joekaufmanexpensify** 2024-02-05 22:12 UTC
Labels: External, Daily, Help Wanted, Bug
