### ISSUE TITLE
[HOLD for payment 2023-10-23] [$1000] Web - Notification count visible while signed out

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26167] opened 2023-08-29 10:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in to an account
2. Go through different chats
3. Sign out
4. Click back and forward

## Expected Result:
Notification count should not be shown( navigating between back and forward)

## Actual Result:
Notification count is visible and (can navigate back and forth)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/0b5241ec-ba2f-4b57-8188-44b75f99b264

https://github.com/Expensify/App/assets/115492554/a250b9e5-7478-47a5-8eca-c2cfd3e30d9a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @kassahun-asefa

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692687393180699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3dd545988985a10</li>
        <li>Upwork Job ID: 1697587793185431552</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>pradeepmdk | Contributor | 27139829</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-08-29 20:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Notification count visible while signed out
### What is the root cause of that problem?
We only update count when `Onyx connection`
### What changes do you think we should make in order to solve the problem?
We need to update title when user click back button.
```
 useEffect(() => {
        window.onpopstate = e => {
               // We can add title update here.
         }
 }, [window])
```
https://github.com/Expensify/App/blob/main/src/libs/UnreadIndicatorUpdater/index.js#L7-L14
we can make and export this as function and call that function on above commment.
### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment] 2023-09-01 12:30
Reproducible but more of a polish than a bug. Triaging to external at $250

**Comment by b4s36t4** [comment] 2023-09-01 13:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Notification count visible while signed out 
### What is the root cause of that problem?

No particular RC, it's just we're not clearing the state of title or icon when we logout.

### What changes do you think we should make in order to solve the problem?

We already have a method `updateUnRead` which does have platform specific code to remove the count.

We're calling `redirectToSignIn` after we logout which does have some other cleanups as well. Adding this function to that well works out.

https://github.com/Expensify/App/blob/6673ba4eb3d0dacad6f63000b00c70950e6fb2c6/src/libs/actions/SignInRedirect.js#L85

```jsx
updateUnRead(0)
```

Should reset the count on web, but there might be multiple changes required for other platforms(need to work on them).



### What alternative solutions did you explore? (Optional)
NA

**Comment by sobitneupane** [comment] 2023-09-05 11:46
@b4s36t4 @yh-0218 

Let's investigate more on root cause. We expect onyx to be cleared when user sign out. Notification count might indicate that onyx is not cleared properly. If Onyx is not cleared properly, we should look more on onyx issue.

**Comment by yh-0218** [comment] 2023-09-05 17:02
@sobitneupane 
I think Onyx is cleared, but update function is not called when click back button.
So I thought we need to call update function when click back button (on my proposal).
Thanks.

**Comment by sonialiap** [comment] 2023-09-12 06:42
@sobitneupane what do you think of @yh-0218 's [comment](https://github.com/Expensify/App/issues/26167#issuecomment-1706986609)? Do you think we can move forward with their proposal or are we still looking for one that addresses your concerns?

**Comment by sobitneupane** [comment] 2023-09-14 09:52
@yh-0218 thanks for the update. But I am expecting a detailed RCA before going with any proposal. We had similar issues previously as well. So, I want to make sure we find the root cause and solve the issue there.

More detailed RCA will be aprreciated.

**Comment by sonialiap** [comment] 2023-09-18 09:30
Still looking for proposals

**Comment by sonialiap** [comment] 2023-09-20 10:31
still looking for proposals

**Comment by sonialiap** [comment] 2023-09-25 04:27
Still looking for proposals

**Comment by sonialiap** [comment] 2023-09-28 07:41
👀 for proposals. If none come in this week then I'll reach out to the contracting teams to see if anyone is available to pick it up

**Comment by yh-0218** [comment] 2023-09-28 08:25
Hi, @sobitneupane @sonialiap , I think this is simple issue.
This is cause we don't update notification count when click back button.
We can add update function and call that when click back button.

**Comment by pradeepmdk** [comment] 2023-09-28 10:53
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
notification count visible after signout and clicking the browser navigation button

### What is the root cause of that problem?
browser will maintain the history state including the title. when we click the browser navigation button whatever is previously registered in the state it will show. we are updating the title 
https://github.com/Expensify/App/blob/67d4a7acebf613dc8fac9fd1423a7a23d1583e59/src/libs/UnreadIndicatorUpdater/index.js#L7-L14
when report collection updates not every path.
ex: 

https://github.com/Expensify/App/assets/16595846/e543dfbd-23d6-466d-bb64-c28b6e35e5ad



### What changes do you think we should make in order to solve the problem?
we need to use `popstate_event` when the browser button is triggered and make sure the user is not logged in means we will update the document title to CONFIG.SITE_TITLE.
https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event#when_popstate_is_sent

**Comment by sonialiap** [comment] 2023-10-04 04:55
@sobitneupane what do you think of the above comments?

**Comment by sobitneupane** [comment] 2023-10-04 07:22
Thanks for the proposal @pradeepmdk.

Would you mind explaining more about the solution? Where will you implement the solution and please do include the pseudocode if necessary.

**Comment by pradeepmdk** [comment] 2023-10-04 08:12
@sobitneupane This platform-specific issue so we need to do only website here 
https://github.com/Expensify/App/blob/67d4a7acebf613dc8fac9fd1423a7a23d1583e59/src/libs/UnreadIndicatorUpdater/updateUnread/index.website.js
```javascript
let authToken;
Onyx.connect({
    key: ONYXKEYS.SESSION,
    callback: (val) => {
        authToken = lodashGet(val, 'authToken', null);
    },
});

window.addEventListener('popstate', (event) => {
    if(!authToken) {
        console.error("enter to update")
        updateUnread(0)
    }
    console.log(event, authToken);
})

``` 
currently this unread count is import in `expensify.js`
https://github.com/Expensify/App/blob/67d4a7acebf613dc8fac9fd1423a7a23d1583e59/src/Expensify.js#L37
using `popstate` update the history state title.
### Option 2
we need to create one more file functional component based on the website alone and import it in `expensify.js` same above logic move into functional component.

**Comment by b4s36t4** [comment] 2023-10-04 08:34
@sobitneupane I'm just wondering why aren't we clearing the entire history once we logout? navigating again after logging out doesn't make sense to me.

**Comment by pradeepmdk** [comment] 2023-10-04 08:59
@b4s36t4 we can't do that. because the browser is maintaining that data. for security reasons, users are only able to clear the history from their browser.

**Comment by sobitneupane** [comment] 2023-10-09 11:41
Sorry for the delay.

I will try to review the proposals before EOD tomorrow (NPT).

**Comment by sonialiap** [comment] 2023-10-09 13:30
Thanks Sobit! :)

**Comment by sobitneupane** [comment] 2023-10-10 07:24
Thanks for your proposal @pradeepmdk .

It explains the root cause and also demonstrates that the issue exists not only when the user is signed out. When a user opens an unread report, the notification count decreases by one, but if the user presses the back button, the notification count will increase by one.

To address this issue comprehensively, we should adopt a holistic approach.

**Comment by pradeepmdk** [comment] 2023-10-10 08:48
@sobitneupane you are correct. to address this i updated my solution https://github.com/Expensify/App/issues/26167#issuecomment-1746361833

**Comment by sobitneupane** [comment] 2023-10-11 10:45
Thanks for the update @pradeepmdk

Option 1 in [proposal](https://github.com/Expensify/App/issues/26167#issuecomment-1746361833) from @pradeepmdk looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by pradeepmdk** [comment] 2023-10-12 02:12
@sobitneupane Pr is ready for review

**Comment by kassahun-asefa** [comment] 2023-10-14 08:46
@MariaHCD
@pradeepmdk
@sonialiap
@sobitneupane

I haven't received my reporting bonus. Currently, there is a problem with my account can i receive my bonus through my brother's Upwork account?

**Comment by sonialiap** [comment] 2023-10-17 14:12
I'm OOO Oct 16-23. Adding leave buddy

Status: waiting to issue payment https://github.com/Expensify/App/issues/26167#issuecomment-1765331037

**Comment by sakluger** [comment] 2023-10-17 16:14
@kassahun-asefa we issue all payments, including the reporting bonus, after the fix has been pushed live to production. You'll receive payment on the 23rd. Just to confirm, you'd like us to send the offer here https://www.upwork.com/freelancers/~0130c45e8d1f512bf8?

**Comment by kassahun-asefa** [comment] 2023-10-17 16:52
thanks for the response @sakluger Yes, I would like to receive the bonus through that account but @thienlnam had a different [opinion](https://github.com/Expensify/App/issues/23517). but i would really like if it is possible though. i can cooperate in any way to solve the issue

**Comment by thienlnam** [comment] 2023-10-17 18:17
@sakluger Just an fyi https://expensify.slack.com/archives/C01SKUP7QR0/p1697477730039989?thread_ts=1696628676.482209&cid=C01SKUP7QR0

**Comment by sakluger** [comment] 2023-10-17 19:05
@kassahun-asefa we can only issue a payment to the Upwork profile associated with the person who reported the bug. Since the bug was reported by Kassahun Asefa in Slack, we must pay Kassahun Asefa. Could you please provide an Upwork profile for Kassahun Asefa?

**Comment by kassahun-asefa** [comment] 2023-10-17 19:29
https://www.upwork.com/freelancers/~01e9c1bf271216783f

**Comment by sakluger** [comment] 2023-10-18 16:37
Thanks @kassahun-asefa, I sent you an offer via Upwork.

**Comment by kassahun-asefa** [comment] 2023-10-19 15:21
@sakluger I have accepted the offer

**Comment by sakluger** [comment] 2023-10-23 18:52
@kassahun-asefa Thanks!
@sobitneupane could you please complete the BZ checklist?

**Summarizing payouts for this issue:**

Reporter: @kassahun-asefa $250 (paid via Upwork)
Contributor: @pradeepmdk $1500 (paid via Upwork)
Contributor+: @sobitneupane $1500 (payable via Manual Request after BZ checklist is completed)

Above payments include efficiency bonus 🎉 
Upwork job: https://www.upwork.com/jobs/~01c3dd545988985a10

**Comment by sonialiap** [comment] 2023-10-24 08:02
Thank you for subbing in, Sasha! I can keep an eye on the checklist step now that I'm back

**Comment by sakluger** [comment] 2023-10-24 21:14
Thanks @sonialiap! Stepping back out. :ohnothing:

**Comment by sonialiap** [comment] 2023-10-27 08:19
@sobitneupane bump on completing the checklist :)

**Comment by sobitneupane** [comment] 2023-10-27 13:06
Sorry for the delay. I was OOO. I will try to get it done in the weeknd.

**Comment by sobitneupane** [comment] 2023-10-30 07:43
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  The PR that introduced the bug has been identified. Link to the PR:

I am pretty sure the issue was present from the very beginning.
> * [ ]  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

N/A
> * [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It is an edge case which can easily be missed while testing. I believe adding regression test should be enough to catch such issue.
> * [ ]  Determine if we should create a regression test for this bug.

Yes.
> * [ ]  If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-10-30 07:47
**Regression Test Proposal**

- Sign in to an account with some unread chats
- Go through different chats
- Sign out
- Click back and forward
- Observe the Notification count in the tab and verify that notification count is not shown.

**Comment by sobitneupane** [comment] 2023-10-30 13:54
https://github.com/Expensify/App/issues/26167#issuecomment-1775824721

Requested payment on newDot.

**Closed** 2023-10-31 09:20 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-03 22:15
$1,500 payment approved for @sobitneupane based on [this comment](https://github.com/Expensify/App/issues/26167#issuecomment-1775824721).
