### ISSUE TITLE
[Hold] Getting console error when opening public room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21634] opened 2023-06-26 20:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Login as any user.
2. Open any public room (/r/5593084223054221)
## Expected Result: 
No console error occurs
## Actual Result: 
A console error occurs stating:
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/aee3868d-96b9-4619-bd8e-342fb615920a

![Screenshot 2023-06-22 at 1 36 07 AM (1)](https://github.com/Expensify/App/assets/43996225/051e25af-1cb8-46ae-88af-0d0b5f6ecdd3)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @allroundexperts 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687379866272869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cubuspl42** [comment] 2023-06-26 21:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When a user mention is displayed, the console error about Function Components is shown.

### What is the root cause of that problem?

We're passing `ref` to a Function Component, which in React is considered an error.

### What changes do you think we should make in order to solve the problem?

In `Hoverable`, we can pass `ref` to the cloned element only if there was any original `ref`.

```js
class Hoverable extends Component {
    // ...
    
    render() {
        // ...

        const {ref} = child;

        const wrappedRef = ref ? (el) => {
            this.wrapperView = el;

            // Call the original ref, if any
            if (_.isFunction(ref)) {
                ref(el);
                return;
            }

            if (_.isObject(ref)) {
                ref.current = el;
            }
        } : undefined;

        return React.cloneElement(React.Children.only(child), {
            ref: wrappedRef,
            
            // ...
        });
    }
}
```

**Comment by cubuspl42** [comment] 2023-06-26 21:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When a user mention (`MentionUserRenderer`) is displayed, the console error about Function Components is shown.

### What is the root cause of that problem?

[`MentionUserRenderer` wraps a `TextLink` with a `Tooltip`](https://github.com/Expensify/App/blob/67561d81bd95681e47dab14261349eb6eaad384d/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L41), while [`Tooltip` passes its child to `Hoverable`](https://github.com/Expensify/App/blob/67561d81bd95681e47dab14261349eb6eaad384d/src/components/Tooltip/index.js#L153). In turn, [`Hoverable` expects its child to be an instance of a component that accepts the `ref` special property](https://github.com/Expensify/App/blob/67561d81bd95681e47dab14261349eb6eaad384d/src/components/Hoverable/index.js#L81).

However, `TextLink` is a simple function component. Function components don't support `ref` by default.

### What changes do you think we should make in order to solve the problem?

A simple, local fix is to forward the reference in `TextLink`.

```jsx

const TextLink = forwardRef((props, ref) => {
    const rest = _.omit(props, _.keys(propTypes));
    const additionalStyles = _.isArray(props.style) ? props.style : [props.style];

    // ...

    return (
        <Text
            ref={ref}
            // ...
        >
            {props.children}
        </Text>
    );
});
```

### What alternative solutions did you explore?

I tried figuring out how `Hoverable` implementation could be adjusted, so it doesn't require its child to accept `ref`, but that seems to be trickier than I thought. It's probably beyond the scope of this particular issue.

**Comment by gadhiyamanan** [comment] 2023-06-27 02:39
I think this is dupe https://github.com/Expensify/App/issues/21496

**Comment by gadhiyamanan** [comment] 2023-06-27 02:44
The root cause is same

**Comment by flaviadefaria** [comment] 2023-06-30 17:49
@gadhiyamanan @allroundexperts will this be resolved by the changes in https://github.com/Expensify/App/issues/21496?

**Comment by flaviadefaria** [comment] 2023-07-03 18:41
Ok so I'll put this on hold until https://github.com/Expensify/App/issues/21496 closes and switch it to weekly.

**Comment by flaviadefaria** [comment] 2023-07-26 17:43
Still on hold

**Comment by flaviadefaria** [comment] 2023-08-09 10:45
Alright https://github.com/Expensify/App/issues/21496 has now closed do we want to check if the error is still happening?

**Comment by flaviadefaria** [comment] 2023-08-10 09:31
It looks like we're good here so closing this.

![image](https://github.com/Expensify/App/assets/80457174/2041b149-5c4b-4bb7-bfa3-288a6704f2b0)

**Closed by flaviadefaria** 2023-08-10 09:31 UTC
Labels: Daily, Bug
