### ISSUE TITLE
[HOLD for payment 2024-04-15] [HOLD for payment 2024-04-09] Group chat - Group chat avatar leads to not here page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39249] opened 2024-03-29 15:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat.
3. Create a group chat.
4. Tap on the group chat header.
5. Tap on the group chat avatar.

## Expected Result:
Group chat avatar opens in full screen view without issue.

## Actual Result:
Group chat avatar leads to not here page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f7bf3541-a272-4a05-9389-c8f531f4224a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-29 15:36
@adelekennedy I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-29 15:37
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-03-29 15:37
Production 
![image (5)](https://github.com/Expensify/App/assets/115492554/3be68383-ff9c-4fb8-b4ec-99444852538c)

**Comment by marcaaron** [comment] 2024-03-29 16:26
Thanks - that first link doesn't seem to go anywhere.

**Comment by marcaaron** [comment] 2024-03-29 16:33
We will soon modify this to allow adding a custom avatar. So, I think it would be ok to just disable opening an avatar for a Group Chat.

`icon.id === -1` is pretty confusing. How about something like this:

```diff
diff --git a/src/components/RoomHeaderAvatars.tsx b/src/components/RoomHeaderAvatars.tsx
index 9298062aa6..ee75f91d58 100644
--- a/src/components/RoomHeaderAvatars.tsx
+++ b/src/components/RoomHeaderAvatars.tsx
@@ -15,8 +15,12 @@ type RoomHeaderAvatarsProps = {
     reportID: string;
 };

-function RoomHeaderAvatars({icons, reportID}: RoomHeaderAvatarsProps) {
+function RoomHeaderAvatars({icons, reportID, isGroupChat}: RoomHeaderAvatarsProps) {
     const navigateToAvatarPage = (icon: Icon) => {
+        if (isGroupChat) {
+            return;
+        }
+
         if (icon.type === CONST.ICON_TYPE_WORKSPACE) {
             Navigation.navigate(ROUTES.REPORT_AVATAR.getRoute(reportID));
             return;
```

```diff
diff --git a/src/pages/ReportDetailsPage.tsx b/src/pages/ReportDetailsPage.tsx
index 80563fcf7b..ccfe329419 100644
--- a/src/pages/ReportDetailsPage.tsx
+++ b/src/pages/ReportDetailsPage.tsx
@@ -218,6 +218,7 @@ function ReportDetailsPage({policies, report, session, personalDetails}: ReportD
                                 <RoomHeaderAvatars
                                     icons={icons}
                                     reportID={report?.reportID}
+                                    isGroupChat={ReportUtils.isGroupChat(report)}
                                 />
                             )}
                         </View>
```

**Comment by kavimuru** [comment] 2024-04-01 20:53
This is a pass. Tapping the avatar does not navigate to anywhere.

https://github.com/Expensify/App/assets/43996225/9c8da62e-1194-40ca-a316-67236d986879

**Comment by adelekennedy** [comment] 2024-04-11 16:00
@marcaaron what payment is due here? It looks like there are two connected PRs both reviewed by @s77rt - is the only payment due for the C+ PR reviews?

**Comment by s77rt** [comment] 2024-04-12 10:23
No payment is due here. This is a part of a https://github.com/Expensify/App/issues/32317

**Comment by s77rt** [comment] 2024-04-12 10:26
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/37458
- The offending PR has been commented on: Not needed. Author and Reviewer were tagged on the PR fixing this
- A discussion in #expensify-bugs has been started: n/a
- Determine if we should create a regression test for this bug: No

**Comment by s77rt** [comment] 2024-04-12 10:26
Let's close this

**Closed** 2024-04-12 15:09 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
