### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] mWeb -  Can't paste magic code on text input

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21708] opened 2023-06-27 17:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in and click next
2.  Copy the code
3. Try to paste the code

## Expected Result:
Use able to paste

## Actual Result:
User is not able to paste

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Chrome
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/878f06ea-1895-4c88-883a-d0d366d31e91

https://github.com/Expensify/App/assets/93399543/1f725267-10a9-41a8-b74c-decf18e37490

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dan1d
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687541947014449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cecac183f21046d7</li>
        <li>Upwork Job ID: 1673903402036682752</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2023-06-28 03:23
Haven't been able to repro on staging - commented on the slack thread. will reopen if get better qa steps.

https://github.com/Expensify/App/assets/42940078/ddcaca5f-fadd-4155-b6bb-637f84546901

**Comment by sophiepintoraetz** [comment] 2023-06-28 03:57
Okay, clarified that it's only Chrome browser that this occurs in - able to reproduce now:

https://github.com/Expensify/App/assets/42940078/04974890-df29-49fc-bba9-de34345f0ae2

**Comment by sophiepintoraetz** [comment] 2023-07-03 02:49
@Santhosh-Sellavel can you take a look at @tienifr's proposal?

**Comment by Santhosh-Sellavel** [comment] 2023-07-05 17:22
Sorry, somehow this slipped through my radar, will check today!

**Comment by Santhosh-Sellavel** [comment] 2023-07-05 21:44
@tienifr's 

This is root cause
> But userAgent on mweb chorme ios contains CriOS => isMobileSafari is false

Then how this would solve the issue.

>use const isMobileSafari = Browser.getBrowser()==='safari';

Can you elaborate root cause, and how your solution address the problem more clearly thanks!

**Comment by sophiepintoraetz** [comment] 2023-07-10 09:14
Still reviewing the proposal!

**Comment by Santhosh-Sellavel** [comment] 2023-07-11 17:27
Sorry somehow I missed this!

**Comment by Santhosh-Sellavel** [comment] 2023-07-11 17:43
@tienifr's [Proposal](https://github.com/Expensify/App/issues/21708#issuecomment-1610685948) looks good to me. Solution 2 or 3 Both are fine for me.

C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2023-07-11 17:44
Please let me know which one you prefer @marcaaron!

**Comment by marcaaron** [comment] 2023-07-11 19:33
I am sort of wondering why we make this style exception only for mobile Safari. It feels like we should be applying this style change consistently throughout the various platforms. Can we get some mocks of what this looks like on Safari vs. Chrome?

also cc @shawnborton as it's design related

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 19:39
@tienifr Can please you share how it looks before and after?

**Comment by marcaaron** [comment] 2023-07-15 00:57
waiting for the answer to my question 😄 thanks

**Comment by marcaaron** [comment] 2023-07-18 17:55
Still waiting.

**Comment by marcaaron** [comment] 2023-07-18 21:07
The proposal we have seems OK and the solution is not complex. I am just trying to figure out what this is going to look like. Normally, we avoid platform inconsistencies with our designs. @Santhosh-Sellavel can you work with @tienifr so we can get unblocked here?

**Comment by marcaaron** [comment] 2023-07-18 21:09
Another option is to raise this in the Slack channel to get more consensus and share the result here.

**Comment by Santhosh-Sellavel** [comment] 2023-07-19 13:09
@tienifr what about android platforms?

**Comment by Santhosh-Sellavel** [comment] 2023-07-19 13:09
Okay @marcaaron 👍

**Comment by marcaaron** [comment] 2023-07-20 00:48
>I applied the current Safari logic to all platforms

I am not sure if you guys are getting what I am asking so I will try again...

How do things look today? And are we materially changing anything about the **visual appearance**? 

I see this code here:

https://github.com/Expensify/App/blob/52a18912a42567fdc25cb6c64676516959a16781/src/components/MagicCodeInput.js#L322

Does it make a difference if we use `styles.bgTransparent` or `styles.opacity0`? Can we use `styles.bgTransparent` on every platform? Or would this change something about the appearance or behavior? The solution we currently have on `main` is not cross platform. 

Do we agree we can make it cross platform without introducing visual inconsistency?

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 19:08
> Does it make a difference if we use `styles.bgTransparent` or `styles.opacity0`? Can we use `styles.bgTransparent` on every platform? Or would this change something about the appearance or behavior? The solution we currently have on `main` is not cross platform.
> 
> Do we agree we can make it cross platform without introducing visual inconsistency?

No @marcaaron we can't it will cause this issue.

<img width="385" alt="Screenshot 2023-07-21 at 12 37 20 AM" src="https://github.com/Expensify/App/assets/85645967/6a2a7824-8d0c-4f99-b83a-109eeaa7e1a7">

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 20:05
As Marc said using `bgTransparent` for all platforms
> Does it make a difference if we use styles.bgTransparent or styles.opacity0? Can we use styles.bgTransparent on every platform? Or would this change something about the appearance or behavior? The solution we currently have on main is not cross platform.

**Comment by marcaaron** [comment] 2023-07-20 20:21
Ok well, I think it would be nice to solve this at the root cause and come up with a cross platform solution. But there's already kind of a hack in the code where we are using two different styles so it's not a blocker. 

However, let's ask this question:

Is it always safe to use either `bgTransparent` vs. `opacity0`? Because maybe we can do something like a `styles.transparent` which can be computed depending on the platform instead of inline with a util everywhere we need this change.

If this is an issue with the mobile web platforms then we are going to run into it with any `View` that wraps something interactive?

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 20:54
@marcaaron

> Is it always safe to use either bgTransparent vs. opacity0? Because maybe we can do something like a styles.transparent which can be computed depending on the platform instead of inline with a util everywhere we need this change.

Yeah, we could come up with a util like that a life save

> If this is an issue with the mobile web platforms then we are going to run into it with any View that wraps something interactive?

But this seems like a case for the mobile safari web alone. So how we can do that?

**Comment by Santhosh-Sellavel** [comment] 2023-07-21 21:31
Thanks, @tienifr, I've looked at the PR. 

Having a platform-specific check in a component is something we are trying to sort out here, making a check from `isMobileSafari` to `isBrowser` is not the way to go. 

We have a few exceptional where we already using `isMobileSafari` check, so I think it is better to stick with the same just improve it and handle it for now. So we don't break anything on the platforms. Or unless we have a holistic approach.

@marcaaron Thoughts? Also bump on [this](https://github.com/Expensify/App/issues/21708#issuecomment-1644592079)

**Comment by marcaaron** [comment] 2023-07-22 01:58
I meant something like: 

```js
export function getTransparentStyle() {return isMobileSafari ? styles.bgTransparent : styles.opacity0;}
```

Does that make more sense now? We can just avoid any `isMobileSafari` checks inside the components then

**Comment by marcaaron** [comment] 2023-07-22 02:00
We don't have to update any usages. Just the one. Just want it to be in the `styles` instead of in the component.

**Comment by Santhosh-Sellavel** [comment] 2023-07-23 18:05
No @marcaaron we can't

Here `styles.opacity0` is used to hide the view and its child. This works for all the platforms, but mobile web safari we handle it quite differently

With the help of check `isMobileSafari`,

-  used` styles.bgTransparent` to make the bg of the view transparent.
-  Also here we hide input & caret separately using the inputStyle & props
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/components/MagicCodeInput.js#L351-L352

**Comment by marcaaron** [comment] 2023-07-25 19:35
Let's raise a PR at this point and continue the conversation there?

**Comment by Santhosh-Sellavel** [comment] 2023-07-26 00:10
@marcaaron [PR](https://github.com/Expensify/App/pull/23254) is already raised, at this [point](https://github.com/Expensify/App/issues/21708#issuecomment-1646257739).

Please go through PR and discussion from [here](https://github.com/Expensify/App/issues/21708#issuecomment-1646257739)
Please let us know your thoughts, thanks!

**Comment by sophiepintoraetz** [comment] 2023-08-02 04:55
Just so I'm clear, are we needing @marcaaron to review the https://github.com/Expensify/App/pull/23254 is already raised, at this https://github.com/Expensify/App/issues/21708#issuecomment-1646257739 and add his thoughts before we close this one out?

**Comment by marcaaron** [comment] 2023-08-02 21:12
We are waiting for @Santhosh-Sellavel to review and for @tienifr to make some changes that I requested.

**Comment by Santhosh-Sellavel** [comment] 2023-08-03 21:18
cc: @sophiepintoraetz @marcaaron 

Requesting not to apply any penalty here, there was some delay in communication that caused this long if not we could have wrapped this up sooner.

**Comment by marcaaron** [comment] 2023-08-03 21:27
@Santhosh-Sellavel My feedback would be to be more proactive in the future. Try to resolve concerns and ask clarifying questions (in realtime on Slack if necessary) to get through reviews faster. If you don't understand something feel free to speak up sooner or grab me in a DM to sort it out. Thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-08-03 21:44
Sorry @marcaaron

Based on past experience this kind of delay happens only when CMEs are busy working on priority items or they are not available (OOO). Only if it takes more than two days I would start DM & Ping them on channels, but some discussions happen sooner. Also, we rarely would run into situations like this.

What I felt we have could done differently, is we could have had this conversion before assigning @tienifr here. Because we didn't go with the selected proposal. We wanted something different here and had our doubts about the existing implementation itself.

I would try and speed up things with you in the future, thanks!

**Comment by marcaaron** [comment] 2023-08-03 22:23
The bonuses/penalties we have are meant to inspire everyone to take initiative. The CMEs are here to support you and are just as motivated to close these issues as you are.

Here's some more specific feedback on this ticket that I think would be helpful in avoiding delays...

- pick a **single proposal** instead of recommending two different proposals (this gives the CME more work to do and will likely cause delays)
- ask for help in Slack if you can't figure out which proposal is best
- anticipate whether the proposal _really_ makes **complete sense** and summarize anything unclear (not doing this gives the CME more work to do and will cause delays). Are all parts of the proposal template clearly filled out? Or could they be improved?
- if the CME has follow up questions then the ball is back in your court. lead the investigation and get them answered with urgency.
- if the CME assigns someone then ensure a PR is created with urgency.
- if the CME leaves questions on the PR bump the assignee to get them answered.
- avoid further delays by not questioning the clear instructions of the CME. ask for clarification if you feel like progress is blocked.
- bump your assignee so they do not take so long to update the PR.

There are arguably some factors outside of your control e.g. the proposal was accepted, but more questions needed to be answered. But is that really so different from any conversation on any PR review that could slow something down? By recommending the proposal you are communicating to us to "start the clock".

Anyways, we are here to support you - not slow you down. But IMO you need to be able to show that you made every effort to expedite if you are going to claim that something outside of your control slowed stuff down.

**Comment by sophiepintoraetz** [comment] 2023-08-16 17:29
Confirming payments (paid out now) based on Marc's feedback [here](https://github.com/Expensify/App/issues/21708#issuecomment-1664715414):

Payouts due:

Issue Reporter: $250 @@dan1d
Contributor: $500 @tienifr 
Contributor+: $500 @Santhosh-Sellavel

Eligible for 50% #urgency bonus? N

**Closed** 2023-08-16 17:32 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by Santhosh-Sellavel** [comment] 2023-08-17 18:42
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/18771
* [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/18771#issuecomment-1682783840
* [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A Should have been caught while testing
* [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug.
* [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A. Basic case
* [x]  [@sophiepintoraetz] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by Santhosh-Sellavel** [comment] 2023-08-30 19:19
Requested on ND

**Comment by JmillsExpensify** [comment] 2023-09-01 22:48
Reviewed the details for @Santhosh-Sellavel. $500 approved for payment in NewDot based on BZ summary.
