### ISSUE TITLE
Task shows "no activity yet" in LHS with activities.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#25937] opened 2023-08-25 13:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open acc A  & B
2. Create a task from acc A and assign to any user (except B)
3. Add some messages to task report from account A
4. Assign it to account B
5. Observe last message of task in LHS
## Expected Result:
The task report should show the latest message in the LHS.
## Actual Result:
The task report shows no activity yet in the LHS.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/272537bf-e9df-4084-b9cb-12fa233c4a9f

https://github.com/Expensify/App/assets/38435837/df80c941-f752-4e6c-8442-6887ab859107

**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692182548574889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a929c2ede7994053</li>
        <li>Upwork Job ID: 1696219199991738368</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2023-08-28 17:53
Not overdue, applied the external label.

**Comment by tomgilon** [comment] 2023-08-29 09:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When assigning a new assignee to a task, the task report shows "No Activity Yet" on the LHS of all participants, even though there may be chat messages on the task.
Actually, it seems that this happens for every type of task edit, not just assignee change. (for example editing the title has the same effect).

### What is the root cause of that problem?
It seems to me that the php server (who's code I don't think I have access to) wrongfully changes the "lastMessageText" attribute of the report to an empty string when the EditTaskAssignee API call is made.

### What changes do you think we should make in order to solve the problem?
Change the server code so that it does not remove the lastMessageText when a task is edited.

### What alternative solutions did you explore? (Optional)
Alternatively, we could add another `else if` clause here in line `391` that would check if the last report action was an edit action and if so, display the last *visible* report action which is already found in line `378`:
https://github.com/Expensify/App/blob/fd755ee94ee9aed354e528abc0b62d19a90802c2/src/libs/OptionsListUtils.js#L377-L392

**Comment by DylanDylann** [comment] 2023-08-29 10:04
I think it is a BE bug. The BE should return reportActions of task report to new assignee

**Comment by tomgilon** [comment] 2023-08-29 11:25
Adding for clarification to https://github.com/Expensify/App/issues/25937#issuecomment-1697055990 :
note that the reopening of a task and the completion of task use different API calls and so are not affected by this bug, as can be seen in the reporter's videos

**Comment by isabelastisser** [comment] 2023-08-29 17:44
Hey @rushatgabhane, can you please review @tomgilon proposal above? Thanks!

**Comment by carlosalmonte04** [comment] 2023-08-29 18:57
We don't see the correct preview because we use reportActions to craft the correct message, and 0 reportActions come in when the task arrives at account B. _This is also why the message is fixed once we navigate to the task – this causes the reportActions to be fetched and in turn the correct message to be created._

We should:
a) send the latest `reportAction` when changing the task assignee -RECOMMENDED, the 2nd report related to the task (the other chat) gets updated like this.
**or** 
b) send `latestMessageText` when changing assignee.

Both approaches require BE changes and might **only** need BE changes actually.

**Comment by tomgilon** [comment] 2023-08-29 21:26
ok, so there are actually **two** problems here
1. like @carlosalmonte04 and @DylanDylann say the backend doesn't return the reportAction until we navigate to the task
2. like I said in my original comment, `report.lastMessageText` is empty. And this is the property which is **generally** used to craft the LHS message. The only reason reopened task message appears correctly once you've navigated is because it has special treatment here in line 310:
https://github.com/Expensify/App/blob/117e9d77b00f679acbc132e0da9c9844cd046574/src/libs/SidebarUtils.js#L305-L316

As you can see (line 314), for other types of messages (like regular messages), the problem persists and "No Activity Yet" continues to be displayed even after navigating to the task.

**Comment by isabelastisser** [comment] 2023-08-30 15:08
Hey @rushatgabhane, what are the next steps here?

**Comment by isabelastisser** [comment] 2023-09-05 14:54
Bump @rushatgabhane

**Comment by isabelastisser** [comment] 2023-09-11 16:20
Bump @rushatgabhane, what's next here?

**Comment by isabelastisser** [comment] 2023-09-11 17:15
@grgia bump!

**Comment by grgia** [comment] 2023-09-14 10:22
Removed help wanted label

**Comment by grgia** [comment] 2023-09-14 10:22
cc @thienlnam this is an internal task bug

**Comment by isabelastisser** [comment] 2023-09-20 16:07
@grgia are we working on this? What are the next steps? Thanks!

**Comment by isabelastisser** [comment] 2023-10-03 14:26
@grgia any updates?

**Comment by isabelastisser** [comment] 2023-10-16 16:42
Bump @grgia. Are we working on this?

**Comment by isabelastisser** [comment] 2023-10-25 16:13
Hey @grgia are we working on this? Should we close this?

**Comment by isabelastisser** [comment] 2023-11-03 18:25
@grgia are you working on this?

**Comment by grgia** [comment] 2023-11-13 15:34
Making monthly for now

**Comment by isabelastisser** [comment] 2023-12-15 18:03
@grgia, should we close this one, given our roadmap?

**Comment by isabelastisser** [comment] 2024-01-16 11:55
Bump @grgia

**Comment by isabelastisser** [comment] 2024-02-16 16:20
@grgia I DM'd you for an update. Thanks!

**Comment by isabelastisser** [comment] 2024-03-18 23:52
I DM'd @grgia again now.

**Comment by grgia** [comment] 2024-04-03 14:27
I think we can just close this out for now @isabelastisser

**Closed** 2024-04-03 14:26 UTC
Labels: Engineering, Monthly, Internal, Bug
