### ISSUE TITLE
[HOLD for payment 2023-09-12] [$500] DEV: [distance] flow is showing on Split Bill

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#26661] opened 2023-09-04 13:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Request money from Fab and navigate to distance
2. Close the RHP
3. Open new split bill from FAB.
4. Enter amount and continue.
5. Check that distance header is opened. (1st bug)
6. Then press next the MapBox is shown. (2nd bug).

## Expected Result:
Describe what you think should've happened

Split bill flow should have been continued.

## Actual Result:
Describe what actually happened

Distance Request flow is shown.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/36083550/537de597-0f0e-43b3-976d-988da38050dc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jeet-dhandha 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693771673626369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111d98650a9c274fc</li>
        <li>Upwork Job ID: 1698686027280314368</li>
        <li>Last Price Increase: 2023-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26737252</li>
<li>jeet-dhandha | Reporter | 26737254</li>
</ul></li>
    </ul>
</details>

**Comment by napster125** [comment] 2023-09-04 13:18
I can't reproduce it.

**Comment by rezkiy37** [comment] 2023-09-04 13:30
Hi, I'm Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by situchan** [comment] 2023-09-04 13:31
PR will be ready in 5 min

**Comment by b4s36t4** [comment] 2023-09-04 13:31
Doesn't this need any external proposal? @situchan

**Comment by mountiny** [comment] 2023-09-04 13:32
@b4s36t4 proposal was madde in c+ slack channel, due to urgency I have asked @situchan to raise the PR straight away

**Comment by conorpendergrast** [comment] 2023-09-11 11:50
@puneetlath This is waiting for payment, tomorrow!

**Comment by puneetlath** [comment] 2023-09-12 15:06
It looks like @situchan was the contributor and @allroundexperts the C+, is that right? 

@allroundexperts friendly bump on the checklist so that we can pay!

**Comment by puneetlath** [comment] 2023-09-15 14:42
@allroundexperts bump again on the checklist please.

**Comment by puneetlath** [comment] 2023-09-18 17:46
For the regression test, I asked about it here: https://expensify.slack.com/archives/C05DWUDHVK7/p1695059126120129

@situchan @jeet-dhandha it seems for some reason the offers didn't automatically go out. Can you both apply to this job: https://www.upwork.com/jobs/~0111d98650a9c274fc

**Comment by situchan** [comment] 2023-09-18 17:53
@puneetlath can you please try this:
- remove `Awaiting Payment`
- unassign me
- add `Help Wanted`
- assign me again

**Comment by puneetlath** [comment] 2023-09-20 08:05
Regression test issue: https://github.com/Expensify/Expensify/issues/318409

**Comment by puneetlath** [comment] 2023-09-20 08:07
Payment summary: 
 
@situchan - Contributor -> $500 + $250 urgency bonus = $750 (paid via Upwork)
@allroundexperts - Contributor+ -> $500 + $250 urgency bonus = $750
@jeet-dhandha - Reporter -> $50 (paid via Upwork) 

Thanks everyone. Closing!

**Closed by puneetlath** 2023-09-20 08:07 UTC
Labels: External, Daily, Bug
