### ISSUE TITLE
Chat - Attachment as a last message in LHN but last is Money request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25632] opened 2023-08-21 23:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to the app
2. Go to chat with Person B
3. Send attachment (image)
4. Send Money request
5. See LHN

## Expected Result:
There should be "Person B owes <amount>" as a last message

## Actual Result:
There is [Attachment] as a last message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

Uploading expensify-bug-202308111802-attachment-as-last-message.mov…

https://github.com/Expensify/App/assets/78819774/89ee4cab-591f-471a-9a9b-d5f748bdb08a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tymatein

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691770589848159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment] 2023-08-21 23:38
## Proposal
Proposal from @DylanDylann
### Please re-state the problem that we are trying to solve in this issue.
Request Money don’t reflect to LHN
###  What is the root cause of that problem?
Let’s see how we get the last message in LHN
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/libs/OptionsListUtils.js#L383-L391
In isReportMessageAttachment
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/libs/isReportMessageAttachment.js#L11-L20
When requesting money, we miss 2 things:
- We don’t reset lastMessageTranslationKey when requesting money
- we don’t reset lastMessageText and lastMessageHtml when requesting money
So, isReportMessageAttachment function return true and the last message display incorrect
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/c435734d8cf360e964e20eea1fb54c541f6fa7ea/src/libs/actions/IOU.js#L336
At the end of step 1, we should set optimistic lastMessageText, lastMessageHtml and lastMessageTranslationKey for chatReport like this
```
const formattedTotal = CurrencyUtils.convertToDisplayString(amount, currency);
   chatReport.lastMessageTranslationKey = ‘’;
   chatReport.lastMessageText = `${payerEmail} owes ${formattedTotal}`;  (we also set this field as an empty string)
   chatReport.lastMessageHtml = `${payerEmail} owes ${formattedTotal}`; (we also set this field as an empty string)
```
The value of lastMessageText and lastMessageHtml is not important because we reset this value to isReportMessageAttachment function return the correct value, we had another logic to get lastMessagetext in case the lastMessage is request money.
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/libs/OptionsListUtils.js#L385-L386
We also need to set lastMessageTranslationKey for IOU report (anywhere we reset lastMessageText we also need to reset lastMessageTranslationKey)
https://github.com/Expensify/App/blob/c435734d8cf360e964e20eea1fb54c541f6fa7ea/src/libs/actions/IOU.js#L120
```
lastMessageTranslationKey: ‘’,
```
###  What alternative solutions did you explore? (Optional)

**Comment by pradeepmdk** [comment] 2023-08-21 23:51
same issue https://github.com/Expensify/App/issues/24246#issuecomment-1669637160

**Comment by DylanDylann** [comment] 2023-08-22 01:49
I think It is another bug

**Comment by tjferriss** [comment] 2023-08-24 16:16
I agree that this looks to be a dupe of https://github.com/Expensify/App/issues/24246. I'm going to close in favor of that issue.

**Closed by tjferriss** 2023-08-24 16:16 UTC
Labels: Daily, Overdue, Bug
