### ISSUE TITLE
[HOLD for payment 2024-12-11] [$250]  mweb - Netsuite - Offline indicator is below the text in Auto-sync page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52626] opened 2024-11-15 15:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+29302390@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51949
## Action Performed:
Precondition:
- Workspace is connected to NetSuite
1. Go to staging.new.expensify.com
2. Go to workspace settings
3. Go to Accounting
4. Tap Advanced
5. Tap Auto-sync
6. Go offline

## Expected Result:
Offline indicator will be at the bottom of the page

## Actual Result:
Offline indicator is below the text instead of bottom of the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ad25a3d1-bfe6-46ee-a207-7cf0d1963a25

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857460821129435659</li>
        <li>Upwork Job ID: 1857460821129435659</li>
        <li>Last Price Increase: 2024-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Contributor | 104956911</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by yuwenmemon** [comment] 2024-11-15 16:28
Yeah doesn't look like a blocker to me.

**Comment by akinwale** [comment] 2024-11-18 14:49
@yuwenmemon Since this is a regression, the C+ who reviewed the initial PR can be assigned here as well, unless they're currently unavailable.

**Comment by rojiphil** [comment] 2024-11-18 17:17
> Since this is a regression, the C+ who reviewed the initial PR can be assigned here as well, unless they're currently unavailable.

Yeah! That makes sense. @yuwenmemon Please assign me here. Thanks.

**Comment by rojiphil** [comment] 2024-11-18 17:18
@twilight2294 When can you raise a PR for this?

**Comment by rojiphil** [comment] 2024-12-09 14:25
@yuwenmemon I think we can close this as we can consider this to be part of the implementation [here](https://github.com/Expensify/App/pull/51949)

**Comment by OfstadC** [comment] 2024-12-11 16:13
@rojiphil are you indicating payment doesn't need to be issued on this issue?

**Comment by rojiphil** [comment] 2024-12-11 16:43
@OfstadC yeah. you can close this out

**Closed** 2024-12-11 17:48 UTC
Labels: External, Engineering, Daily, Awaiting Payment
