### ISSUE TITLE
[$1000] Chat - Send button is not enabled if only 1 character is typed after sending another message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24193] opened 2023-08-07 03:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-requisite: user must be logged in and in any chat

1. Type and send any message
2. Type a new message with only 1 character

## Expected Result:
The send button should be enabled after typing 1 character

## Actual Result:
User must have to type more than 1 character for the send button to be enabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2e5b15bb-ddcd-4a6b-b1b9-e21e748d50c0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010168816ae3accfb6</li>
        <li>Upwork Job ID: 1688437010257268736</li>
        <li>Last Price Increase: 2023-08-07</li>
    </ul>
</details>

**Comment by techievivek** [comment] 2023-08-07 05:29
@hungvu193 
> Feel like this is issue with our current react native version when multiline is enable.

Did we enable `multiline` recently?

**Comment by techievivek** [comment] 2023-08-07 06:29
@hungvu193 Okk, then using the patch sounds good to me.

**Comment by pradeepmdk** [comment] 2023-08-07 06:32
already discussed here same issue https://github.com/Expensify/App/issues/24147

**Comment by techievivek** [comment] 2023-08-07 06:44
@pradeepmdk ohh, thanks. We are discussing this internally if we should update the RN version or can we just patch-fix this.

**Comment by pradeepmdk** [comment] 2023-08-07 06:45
Thanks for the update @techievivek

**Comment by MonilBhavsar** [comment] 2023-08-07 12:01
Closing considering a dupe of https://github.com/Expensify/App/issues/24147

**Closed by MonilBhavsar** 2023-08-07 12:01 UTC
Labels: Reviewing, DeployBlockerCash, External, Engineering, Weekly, Help Wanted
