### ISSUE TITLE
[$1000] Web - Profile - Timezone setting shifts to another region momentarily but reverts back after a fraction of a second.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23505] opened 2023-07-24 19:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the "Settings" menu.
2. Access your user "profile."
3. Click on the "Timezone" option.
4. Notice that when the timezone settings open, the region temporarily changes to another location but returns to the correct setting after a few microseconds.

## Expected Result:
The timezone options should open without any region shifting.

## Actual Result:
The timezone options momentarily display a different region but quickly revert back to the correct region after a few microseconds.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/47130af0-1010-401a-aaab-1a8048ab8b32

https://github.com/Expensify/App/assets/93399543/ebfa636c-1673-4b70-85c9-ede2c5f548fc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690191633365859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a21909dd9f24bd3</li>
        <li>Upwork Job ID: 1683774803555397632</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-07-24 21:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Timezone setting shifts to another region momentarily but reverts back after a fraction of a second. 
### What is the root cause of that problem?
We are using `SectionList` to show list of timezone.
https://github.com/Expensify/App/blob/82669ae1201f3778986ee26209fb80878f166cbd/src/components/SelectionListRadio/BaseSelectionListRadio.js#L241
When open timezone select, `SelctionList` is scrolled from first to user's timzone.
https://github.com/Expensify/App/blob/82669ae1201f3778986ee26209fb80878f166cbd/src/components/SelectionListRadio/BaseSelectionListRadio.js#L258-L264
ex. from `Africa/Abidjan` to `Europe/Kyiv`
### What changes do you think we should make in order to solve the problem?
We can hide items of `SelctionList` during scrolling.
```
 if (firstLayoutRef.current) {
     return null;
 }
```
https://github.com/Expensify/App/blob/82669ae1201f3778986ee26209fb80878f166cbd/src/components/SelectionListRadio/BaseSelectionListRadio.js#L160-L172
### What alternative solutions did you explore? (Optional)

**Comment by studentofcoding** [comment] 2023-07-25 12:17
Hello All, I want to contribute to this issue, how to participate?

Here are my email and my Upwork profile
Email: yonathanevan@gmail.com
Upwork: https://www.upwork.com/freelancers/yonathanevan

Thanks!

cc: @ArekChr @dylanexpensify

**Comment by studentofcoding** [comment] 2023-07-25 12:25
Contributor details
Your Expensify account email: yonathanevan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/yonathanevan

**Comment by dylanexpensify** [comment] 2023-07-27 10:34
@ArekChr can we get an update/review today?

**Comment by ArekChr** [comment] 2023-07-27 11:49
@thiagobrez is currently refactoring the `SelectionList` in phase 3. Given his familiarity with the List structure, it would be efficient to address this issue within his ongoing [issue](https://github.com/Expensify/App/issues/11795), which is still open.

**Comment by thiagobrez** [comment] 2023-07-27 12:33
Hey @ArekChr @dylanexpensify! Thanks for reporting, I actually already have this fixed in Phase 3 branch of the Selection List refactor as Arek mentioned, and I believe I'm using a slightly better solution by implementing SectionList's `initialScrollIndex` instead of manually hiding the items. I think sending the fix I have within my branch would be more optimal, but let me know what you prefer 🙌🏻

**Closed** 2023-07-31 09:08 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
