### ISSUE TITLE
[$1000] Web - Chat - Attachment link begins with old dot link staging.expensify.com

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20717] opened 2023-06-13 21:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat with image attachment.
3. Right click on the image and open the image in new tab.

## Expected Result:
The image link begins with staging.new.expensify.com

## Actual Result:
The image link begins with staging.expensify.com

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8a10bdfb-2642-4760-ae04-f863a7272fd2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e8d1b479be1cd1d</li>
        <li>Upwork Job ID: 1669464027768901632</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-06-15 21:58
@lschurr - I am leaving for sabbatical this evening and need to reassign. I did the testing and moved to external today because I was able to recreate. 

No immediate action is required by you today. 

Thank you for seeing this through!

**Comment by lschurr** [comment] 2023-06-15 23:26
Looks like the labels got a little messed up on this one, so I added @mollfpr back and added Eng.

**Comment by developerdavi** [comment] 2023-06-16 00:25
@lschurr I found the root cause of this issue. Is this issue still receiving proposals or is it already assigned to someone?

**Comment by Fe-eze** [comment] 2023-06-16 14:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When an image is attached in a web chat, the image links save as the old [expensify.com](url) url.
It should be new.expensify.com

### What is the root cause of that problem?
The file getAttachmentDetails.js seems to be responsible for building up the attachment url link
The function in turn points to tryResolveUrlFromApiRoot to resolve the url

It looks like tryResolveUrlFromApiRoot.js has the following line
`const ORIGINS_TO_REPLACE = ['/+', Config.EXPENSIFY.EXPENSIFY_URL, Config.EXPENSIFY.STAGING_API_ROOT, Config.EXPENSIFY.DEFAULT_API_ROOT];`

This seems to be why the image urls are still pointing to the old expensify link.
The config file needs to be updated and the tryResolveUrlFromApiRoot function should be linked to the new config.

### What changes do you think we should make in order to solve the problem?
CONFIG.js
The config file should be updated and the following line added as a new default value (under line 16 of CONFIG.js)
`const newStagingExpensifyURL = Url.addTrailingForwardSlash(lodashGet(Config, 'NEW_STAGING_EXPENSIFY_URL', 'https://staging.new.expensify.com/'));`

Then, add the following to the default exports (under line 43)
`NEW_STAGING_API_ROOT: newStagingExpensifyURL`

tryResolveUrlFromApiRoot.js
Finally, in tryResolveUrlFromApiRoot.js, change line 7 to
`const ORIGINS_TO_REPLACE = ['/+', Config.EXPENSIFY.NEW_EXPENSIFY_URL, Config.EXPENSIFY.NEW_STAGING_API_ROOT, Config.EXPENSIFY.DEFAULT_API_ROOT];`

**Comment by Fe-eze** [comment] 2023-06-16 14:06
Contributor details
Your Expensify account email: fe-eze@nytengaletech.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0123f506afd674933c?s=996364627857502209

**Comment by Gonals** [comment] 2023-06-19 10:17
This isn't really a bug. That is where the image is stored. Closing

**Closed by Gonals** 2023-06-19 10:17 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
