### ISSUE TITLE
[HOLD for payment 2023-11-30] Notification - User is navigated to LHN after opening notification when app is closed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31625] opened 2023-11-21 14:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Kill the ND app
2. Wait for about 1 minute
3. Send a message from the secondary device to the user logged in on the main device
4. After notification is received, wait 10 seconds and disable the internet
5. Double-tap the notification

## Expected Result:
User is navigated to the correct chat

## Actual Result:
User is navigated to the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a10060ce-ae9b-4f8b-94d1-9d68abbcf941

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by lanitochka17** [comment] 2023-11-21 14:06
Production :

https://github.com/Expensify/App/assets/78819774/3af33eb7-91d4-4e0c-9960-79eaf8dc0835

**Comment by pecanoro** [comment] 2023-11-21 16:11
I managed to reproduce on staging even when online

https://github.com/Expensify/App/assets/6474442/f100ed0e-2c3f-4b4a-b1be-b4036e2fe5fe

**Comment by johnmlee101** [comment] 2023-11-21 16:38
cc @arosiclair

**Comment by johnmlee101** [comment] 2023-11-21 17:48
Keeping some discussion here: https://expensify.slack.com/archives/C07J32337/p1700588638959299?thread_ts=1700588255.529729&cid=C07J32337 

But this was logged in some of the requests
```
829a53ea89181879-EWR | staging-www1.sjc | 2023-11-21 16:32:26 933 | john@expensify.com | MobilePushNotifications - NewDot notification payload data exceeded the maximum allowable. Deleting onyxData field.
```

**Comment by arosiclair** [comment] 2023-11-21 21:07
I can reproduce this in dev. It seems like there are no issues with handling the notification click:

`DEBUG  [info] Navigating to route - {"path":"/r/34"}`

however it looks like there's code navigating back to the home page _after_ we navigate to the chat which is breaking this functionality:

`[info] Navigating to route - {"path":"/"}`

Maybe one of this deploy's PRs added an extra navigation that's doing this?

```
DEBUG  Timing:development.new.expensify.trie_initialization 2390
 LOG  Running "NewExpensify" with {"rootTag":11}
 DEBUG  [OnyxUpdateManager] Listening for updates from the server
 DEBUG  [info] [PushNotification] Callback triggered for com.airship.push_received - ""
 DEBUG  [info] [PushNotification] received report comment notification in the foreground - {"reportID":34,"reportActionID":"3096043123628849351"}
 DEBUG  [info] [Onyx] merge() called for key: report_34 properties: reportID,reportName,type,chatType,ownerEmail,ownerAccountID,managerEmail,managerID,policyID,participantAccountIDs,visibleChatMemberList,isPinned,lastReadTime,lastReadSequenceNumber,lastVisibleActionCreated,lastVisibleActionLastModified,lastMessageText,lastActorAccountID,notificationPreference,welcomeMessage,stateNum,statusNum,oldPolicyName,isOwnPolicyExpenseChat,lastMessageHtml,iouReportID,hasOutstandingIOU,hasOutstandingChildRequest,writeCapability,total,currency,submitterPayPalMeAddress,isWaitingOnBankAccount,nonReimbursableTotal,maxSequenceNumber,hasDraft - ""
 DEBUG  [info] [Onyx] merge() called for key: reportActions_34 properties: 2279458499987116741,1810592943714682823,720260980807411269,5021502884569866715,3096043123628849351 - ""
 DEBUG  [info] [PushNotification] Subscribing to notifications - ""
 DEBUG  [info] Called API write - {"command":"OptInToPushNotifications","deviceID":"sunfish13b96e6e-7517-9667-9384-7d9653abb2b6"}
 DEBUG  [info] [Onyx] set() called for key: networkRequestQueue properties: 0,1,2,3,4 - ""
 DEBUG  [info] [Onyx] merge() called for key: pushNotificationsEnabled - ""
 DEBUG  [info] Found existing deviceID - "sunfish13b96e6e-7517-9667-9384-7d9653abb2b6"
 DEBUG  [info] Making API request - {"command":"ReconnectApp"}
 DEBUG  [info] [PushNotification] Callback triggered for com.airship.notification_response - ""
 DEBUG  [info] [PushNotification] onSelected() - called - {"reportID":34,"reportActionID":"3096043123628849351"}
 DEBUG  [info] [PushNotification] Callback triggered for com.airship.notification_response - ""
 DEBUG  [info] [PushNotification] onSelected() - called - {"reportID":34,"reportActionID":"3096043123628849351"}
 DEBUG  [info] [NetworkConnection] NetInfo state change - {"details":{"isConnectionExpensive":false,"txLinkSpeed":780,"rxLinkSpeed":866,"linkSpeed":780,"subnet":"255.255.255.0","ipAddress":"192.168.86.118","frequency":5180,"strength":99,"bssid":"02:00:00:00:00:00"},"isConnected":true,"type":"wifi","isInternetReachable":true,"isWifiEnabled":true}
 DEBUG  [info] [Migrate Onyx] start - ""
 DEBUG  [info] [Onyx] merge() called for key: network properties: isOffline - ""
 DEBUG  [info] [Onyx] set() called for key: demoInfo properties:  - ""
 DEBUG  [info] [Onyx] set() called for key: isCheckingPublicRoom - ""
 DEBUG  [info] [Migrate Onyx] Skipped migration RenameReceiptFilename because there are no transactions - ""
 DEBUG  [info] [Migrate Onyx] Skipped migration KeyReportActionsDraftByReportActionID because there were no reportActionsDrafts - ""
 DEBUG  [info] [Migrate Onyx] Skipped TransactionBackupsToCollection migration because there are no transactions - ""
 DEBUG  [info] [Migrate Onyx] finished in 47ms - ""
 DEBUG  [info] [NetworkConnection] listenForReconnect called - ""
 DEBUG  [info] [PushNotification] onSelected() - Navigation is ready. Navigating... - {"reportID":34,"reportActionID":"3096043123628849351"}
 DEBUG  [info] Navigating to route - {"path":"/?initial=true&screen=Report&params=%5Bobject%20Object%5D&path=%2Fr%2F34"}
 DEBUG  [info] Navigating to route - {"path":"/r/34"}
 DEBUG  [info] [PushNotification] onSelected() - Navigation is ready. Navigating... - {"reportID":34,"reportActionID":"3096043123628849351"}
 DEBUG  Timing:development.new.expensify.homepage_initial_render 641
 DEBUG  [info] Navigating to route - {"path":"/"}
 DEBUG  [info] Navigating to route - {"path":"/"}
 DEBUG  [hmmm] [PusherConnectionManager] state change - {"states":{"previous":"connecting","current":"connected"}}
 DEBUG  [hmmm] [PusherConnectionManager] connected event - ""
 DEBUG  [info] [Pusher] Attempting to subscribe to channel - {"channelName":"private-encrypted-user-accountID-2-f1f0504637ff4702af969520f3c069df","eventName":"multipleEvents"}
 DEBUG  [info] [PusherAuthorizer] Attempting to authorize Pusher - {"channelName":"private-encrypted-user-accountID-2-f1f0504637ff4702af969520f3c069df"}
 DEBUG  [info] Called API makeRequestWithSideEffects - {"command":"AuthenticatePusher","socket_id":"582391.201247","channel_name":"private-encrypted-user-accountID-2-f1f0504637ff4702af969520f3c069df","shouldRetry":false,"forceNetworkRequest":true}
 DEBUG  [info] Making API request - {"command":"AuthenticatePusher"}
```

**Comment by luacmartins** [comment] 2023-11-21 23:58
Removing the blocker label since we CPed a fix.

**Comment by arosiclair** [comment] 2023-12-06 15:23
This should be all set so closing this out

**Comment by arosiclair** [comment] 2023-12-08 13:36
@laurenreidexpensify can you handle payment for @aimane-chnaif's C+ review? Thanks!

**Comment by laurenreidexpensify** [comment] 2023-12-10 12:42
Payment Summary:

C+ Review - $500 @aimane-chnaif Offer sent in Upwork https://www.upwork.com/en-gb/jobs/~01a9cda98c1c4a1734

**Comment by laurenreidexpensify** [comment] 2023-12-12 12:34
Payment Summary:

C+ Review - $500 @aimane-chnaif paid in Upwork

**Closed by laurenreidexpensify** 2023-12-12 12:34 UTC
Labels: Engineering, Daily, Bug
