### ISSUE TITLE
[HOLD for payment 2024-03-26] [$500] Web - Expense - App crashes when changing the role of user from auditor to employee

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34879] opened 2024-01-22 13:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4208303
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user have must created a collect workspace, submit an expense as an employee and invited another user as an auditor.
1. As the auditor on ND, go to an expense report submitted by another employee.
2. As the admin on OD on another device, change the role of the auditor to an employee.
3. Verify the expense report page on the "auditor" side.

## Expected Result:
No crashes should occur.

## Actual Result:
The app crashes for the auditor side after the admin change their role from auditor to employee.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/85857225-0625-4bd0-b973-eebfb4c654fc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176be1dfa904141ed</li>
        <li>Upwork Job ID: 1749419039920336896</li>
        <li>Last Price Increase: 2024-01-22</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Contributor | 28116898</li>
<li>tienifr | Contributor | 28144968</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-22 13:09
Issue found While performing https://expensify.testrail.io/index.php?/tests/view/4208303

**Comment by kbecciv** [comment] 2024-01-22 13:10
We think that this bug might be related to #wave7-collect-approvers
CC @RachCHopkins

**Comment by paultsimura** [comment] 2024-01-22 13:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the expense is opened as Auditor, the app crashes after the user is demoted to Employee

### What is the root cause of that problem?
The root cause lies here:

https://github.com/Expensify/App/blob/1d21e28dd78d587a7fe9a7d86c79f9f0418c3e29/src/pages/home/ReportScreen.js#L616-L622

When the user is demoted, they do not have access to the expense report anymore, so the `parentReportActions` here is `undefined`. And we are trying to access `undefined[key]`, which causes the crash.

### What changes do you think we should make in order to solve the problem?
We need to early return if the `parentReportActions` is undefined:

```js
selector: (parentReportActions, props) => {
    const parentReportActionID = lodashGet(props, 'report.parentReportActionID');
    if (!parentReportActions || !parentReportActionID) {
        return {};
    }
    return parentReportActions[parentReportActionID];
},
```

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-22 18:13
> This is not reproducible on main

Yup, was fixed by https://github.com/Expensify/App/pull/34648

**Comment by jliexpensify** [comment] 2024-01-23 00:52
Great, so to confirm: this can be closed?

**Comment by jliexpensify** [comment] 2024-01-23 05:00
Weird, assigned you @aimane-chnaif

**Comment by jliexpensify** [comment] 2024-01-29 23:40
Bumping @roryabraham for a review, cheers!

**Comment by jliexpensify** [comment] 2024-02-05 02:59
Bumping @roryabraham

**Comment by jliexpensify** [comment] 2024-02-06 03:37
Bumped Rory on ND.

**Comment by jliexpensify** [comment] 2024-02-23 05:51
@tienifr @aimane-chnaif how's the PR going?

**Comment by roryabraham** [comment] 2024-03-01 19:23
that looks like a bug in the back-end. Let's file it as a separate issue

**Comment by jliexpensify** [comment] 2024-03-20 00:30
@MitchExpensify hello! I am headed OOO from the 21st to 31st so have re-assigned for a buddy to help out.

PAYMENT SUMMARY

- C: @tienifr $500
- C+: @aimane-chnaif $500

[Upwork job](https://www.upwork.com/jobs/~0176be1dfa904141ed)

Thanks!

**Comment by roryabraham** [comment] 2024-03-25 19:15
making this weekly while we HOLD for payment

**Comment by MitchExpensify** [comment] 2024-03-26 19:47
Paid and contracts ended

**Comment by MitchExpensify** [comment] 2024-03-26 19:47
Do we need to complete BZ steps here @aimane-chnaif ?

**Closed by MitchExpensify** 2024-03-26 19:47 UTC
Labels: External, Weekly, Awaiting Payment, Bug
