### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Workspace - Error page when navigate to Workspace Join link after leaving the workspace

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43436] opened 2024-06-10 21:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4609575&group_by=cases:section_id&group_order=asc&group_id=229065
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Login to staging.expensify.com
2. Navigate to this link - https://staging.new.expensify.com/settings/workspaces/CEFA9CA2E2CBFFC0/join?email=applausetester+joinlink@applause.expensifail.com
3. Click on 3-dot menu> Leave
4. Navigate to this link again - https://staging.new.expensify.com/settings/workspaces/CEFA9CA2E2CBFFC0/join?email=applausetester+joinlink@applause.expensifail.com

## Expected Result:
User should be able to navigate to the workspace

## Actual Result:
Error page when navigate to Workspace Join link after leaving the workspace

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/8bd5b199-72f2-445a-8eb7-78c84ead1fe9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191daed4e48342857</li>
        <li>Upwork Job ID: 1800535491968568315</li>
        <li>Last Price Increase: 2024-06-25</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 102892807</li>
<li>bernhardoj | Contributor | 102892809</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by m-natarajan** [comment] 2024-06-10 21:54
@isabelastisser FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-06-11 06:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The not found page is shown when we reopen the workspace join link after leaving it.

### What is the root cause of that problem?
When we successfully leave from a workspace, we still keep the policy object data. It's really weird that the pending action is still `delete`.
https://github.com/Expensify/App/blob/65db65069390cdd9fd386e087b6d8eed94ee22b0/src/libs/actions/Policy/Policy.ts#L649-L660

When we reopen the join link/page, the condition below detects that the workspace exists, thus we are navigated to the profile page.
https://github.com/Expensify/App/blob/65db65069390cdd9fd386e087b6d8eed94ee22b0/src/pages/workspace/WorkspaceJoinUserPage.tsx#L45-L51

The not found page will be shown if the policy/workspace has a pending action of delete, thus we see the not found page.
https://github.com/Expensify/App/blob/65db65069390cdd9fd386e087b6d8eed94ee22b0/src/pages/workspace/WorkspacePageWithSections.tsx#L153

### What changes do you think we should make in order to solve the problem?

First, we should clear the policy data after successfully leaving a workspace.
```
const successData: OnyxUpdate[] = [
    {
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.POLICY}${policyID}`,
        value: null,
    },
];
```

Next, because not found page will be shown for pending delete workspace, we need to add a new check here to make sure the pending action is not `delete` so we don't get navigated to the not found workspace profile page.
https://github.com/Expensify/App/blob/65db65069390cdd9fd386e087b6d8eed94ee22b0/src/pages/workspace/WorkspaceJoinUserPage.tsx#L45-L51

```
if (!isEmptyObject(policy) && !policy?.isJoinRequestPending && !PolicyUtils.isPendingDeletePolicy(policy)) {
```

_We can optionally check for the policy ID. Let me know if we want to do that_

**Comment by isabelastisser** [comment] 2024-06-14 16:43
@abdulrahuman5196, can you please review the proposal above? Thanks!

**Comment by isabelastisser** [comment] 2024-06-17 14:37
@mananjadhav please review the proposal above. Thanks!

**Comment by isabelastisser** [comment] 2024-06-18 15:46
@abdulrahuman5196, please provide an update. Thanks!

**Comment by abdulrahuman5196** [comment] 2024-06-18 17:38
Hi, @isabelastisser I am back now since  I was OOO for  couple of days as posted in slack. Will work on review today.

**Comment by abdulrahuman5196** [comment] 2024-06-20 15:12
checking now

**Comment by abdulrahuman5196** [comment] 2024-06-20 15:19
>Navigate to this link - https://staging.new.expensify.com/settings/workspaces/CEFA9CA2E2CBFFC0/join?email=applausetester+joinlink@applause.expensifail.com

Hi @isabelastisser / @bernhardoj , this link is only setting the workspace as `Requested`, how do I generate this link or use it for testing?

<img width="1504" alt="Screenshot 2024-06-20 at 8 48 38 PM" src="https://github.com/Expensify/App/assets/46707890/f3b67991-ed3e-4eb2-9b44-a383cf9f88cd">

**Comment by isabelastisser** [comment] 2024-06-26 13:40
@abdulrahuman5196 I DM'd you for visibility.

**Comment by abdulrahuman5196** [comment] 2024-06-26 13:41
Checking now

**Comment by abdulrahuman5196** [comment] 2024-06-26 13:43
Hi @isabelastisser Sorry for the delay, I have limited availability at the moment. So unassigning myself. Kindly reassign another C+ for review.

**Comment by isabelastisser** [comment] 2024-06-28 14:42
@allgandalf, did you have a chance to review the PR?

**Comment by bernhardoj** [comment] 2024-07-08 16:03
Just FYI, I will request the payment through ND.

**Comment by bernhardoj** [comment] 2024-07-10 10:31
Requested in ND

**Comment by isabelastisser** [comment] 2024-07-10 15:47
Payment summary:

@bernhardoj contributor / $250 / pending in NewDot
@allgandalf C+ review / $250 / paid in Upwork

**Comment by isabelastisser** [comment] 2024-07-10 15:48
@AndrewGable can you please review the regression test proposal? thanks!

**Comment by JmillsExpensify** [comment] 2024-07-10 16:03
$250 approved for @bernhardoj

**Comment by isabelastisser** [comment] 2024-07-12 20:27
@AndrewGable https://github.com/Expensify/App/issues/43436#issuecomment-2220885775

**Comment by AndrewGable** [comment] 2024-07-15 12:24
Yes, looks good

**Comment by isabelastisser** [comment] 2024-07-15 15:02
All set!

**Closed by isabelastisser** 2024-07-15 15:02 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
