### ISSUE TITLE
[$250] Workspace switcher - Workspace switcher reopens after selecting a workspace with keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35823] opened 2024-02-05 15:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .1.4-36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User has less than 7 workspaces
- Workspace filter is "Expensify"
1. Go to staging.new.expensify.com
2. Open workspace switcher
3. Click on any workspace
4. Open workspace switcher again
5. Using keyboard arrow key, select another workspace and hit Enter

## Expected Result:
The workspace switcher will not reopen

## Actual Result:
The workspace switcher reopens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0f90ec75-d17d-4850-b413-86aa97ca8152

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b6b390114d02e71</li>
        <li>Upwork Job ID: 1754525872518934528</li>
        <li>Last Price Increase: 2024-02-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by mountiny** [comment] 2024-02-05 15:22
Not a blocker, making external

**Comment by godofoutcasts94** [comment] 2024-02-05 15:24
I want to work on it

**Comment by lanitochka17** [comment] 2024-02-05 15:24
We think that this bug might be related to #wave8
CC @zanyrenney

**Comment by Tony-MK** [comment] 2024-02-05 20:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace switcher - Workspace switcher reopens after selecting a workspace with keyboard

### What is the root cause of that problem?

In [`WorkspaceSwitcherPage`](https://github.com/Expensify/App/blob/3ec79bd254fe9b06bf2add8d768aab7dc7143f90/src/pages/WorkspaceSwitcherPage.ts), the [`selectPolicy`](https://github.com/Expensify/App/blob/3ec79bd254fe9b06bf2add8d768aab7dc7143f90/src/pages/WorkspaceSwitcherPage.tsx#L111-L114) function calls `Navigation.goBack()` which reopens the workspace switcher.

https://github.com/Expensify/App/blob/3ec79bd254fe9b06bf2add8d768aab7dc7143f90/src/pages/WorkspaceSwitcherPage.tsx#L111-L114

### What changes do you think we should make in order to solve the problem?


Change the code snippet above to something similar to the one below to prevent the `Navigation.goBack()` from being called unnecessary.

```
if (!activeWorkspaceID){
    Navigation.goBack()
}
if (policyID !== activeWorkspaceID) {
    Navigation.navigateWithSwitchPolicyID({policyID, isPolicyAdmin});
}
```

**Comment by agent3bood** [comment] 2024-02-05 21:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace switcher - Workspace switcher reopens after selecting a workspace with keyboard

### What is the root cause of that problem?

After opening the workspace switcher, the `WorkspaceSwitcherButton` will still have focus. Pressing enter will trigger the onClick event.

### What changes do you think we should make in order to solve the problem?

In `BaseOptionSElector.selectFocusedOption` add `e.stopPropagation();`.

### What alternative solutions did you explore? (Optional)

Adding custom logic to handle `workspace-switcher` route.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by agent3bood** [comment] 2024-02-05 21:43
Contributor details
Your Expensify account email: abdullah.alsigar@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d5fb72b5d46a967a

**Comment by sakluger** [comment] 2024-02-07 17:21
@situchan it looks like there are a few proposals. Do any of them look good to you?

**Comment by situchan** [comment] 2024-02-12 15:37
I am not able to reproduce anymore

**Comment by situchan** [comment] 2024-02-12 15:40
@muas19 it's intentional to hide text input when <8 so 👎 to your proposal.
@agent3bood please explain your root cause in more detail. Especially why https://github.com/Expensify/App/issues/35823#issuecomment-1938914642.

**Comment by agent3bood** [comment] 2024-02-13 08:49
@situchan 
Explaining root cause:
The `BaseOptionsSelector` has two paths
    1. when `shouldShowTextInput == true` the code will request focus on the input, removing focus from any previously focused node.
    2. when `shouldShowTextInput != true` no focus is requested and whatever node was focused before opening the page will still has focus, in this case it is `WorkspaceSwitcherButton`.

When the user uses keyboard to select new workspace it will be handled by a global listener `BaseOptionsSelector.subscribeToEnterShortcut`, this listener needs to stop the event from propagating after handling it.

But if the user used mouse click to select new workspace, the event will be handled by the `div` that shows the workspace and cannot propagate to the  `WorkspaceSwitcherButton`.

**Comment by mountiny** [comment] 2024-02-14 16:19
Still waiting for proposals

**Comment by situchan** [comment] 2024-02-15 17:46
@agent3bood thanks. The root cause makes sense but still not follow your solution.
We should not easily stop propagation in general component.

**Comment by agent3bood** [comment] 2024-02-15 18:29
@situchan I think this is the most practical solution, there are other places the same approach is used includes the general hook `useKeyboardShortcut` does have `shouldPreventDefault` and `shouldStopPropagation` props.

The other option would be requesting focus on the selected list item, this is more involved as it require passing refs with each item from the most top component.

**Comment by muas19** [comment] 2024-02-15 18:39
https://github.com/Expensify/App/issues/35823#issuecomment-1930912196 Updated proposal @situchan

**Comment by muas19** [comment] 2024-02-16 14:33
I would also like to report a bug that I found out after investigation. Where can I do this and propose another fix?

**Comment by mountiny** [comment] 2024-02-19 14:22
@situchan no good proposals so far?

**Comment by situchan** [comment] 2024-02-19 15:12
No viable proposal yet

The ideal solution would be to lose focus on switcher button when switcher modal is open

**Comment by situchan** [comment] 2024-02-19 15:24
@muas19 I remember similar issues (with the same root cause) happened in the past. Can you find the code in our codebase which applied your solution?

**Comment by agent3bood** [comment] 2024-02-19 15:41
[Updated](https://github.com/Expensify/App/issues/35823#issuecomment-1928142775)

**Comment by muas19** [comment] 2024-02-21 14:55
https://github.com/Expensify/App/issues/35823#issuecomment-1930912196 Proposal updated after C+ feedback https://github.com/Expensify/App/issues/35823#issuecomment-1952685403 Inspiration from this pull https://github.com/Expensify/App/pull/9093 @situchan

**Comment by sakluger** [comment] 2024-02-21 15:54
Commenting for Melvinbot, since we just got updated proposals and there hasn't been time to review them both yet.

**Comment by sakluger** [comment] 2024-02-23 17:00
@situchan could you please review the updated proposals? Thanks!

**Comment by situchan** [comment] 2024-02-23 17:03
@muas19 well, I don't think https://github.com/Expensify/App/pull/9093 is the same case.

**Comment by godofoutcasts94** [comment] 2024-02-23 17:19
Hey @situchan just asking is this issue still open for proposals?

**Comment by situchan** [comment] 2024-02-23 17:29
@godofoutcasts94 yes please. `Help Wanted` label seems accidentally removed

**Comment by godofoutcasts94** [comment] 2024-02-24 03:27
> I am not able to reproduce on wrench tab
> 
>  Screen.Recording.2024-02-12.at.8.32.46.PM.mov 
> but reproducible on chats tab
> 
>  Screen.Recording.2024-02-12.at.9.38.56.PM.mov

Hey @situchan! I am unable to reproduce it in the chat tab as well.

<summary>
<details>
Dev

https://github.com/Expensify/App/assets/158435970/a0a711bc-0faa-4710-993d-718d95c972c6

</details>
</summary>

<summary>
<details>Staging

https://github.com/Expensify/App/assets/158435970/0748539e-cd3a-4fd9-ad3d-5ce8019c3bda

</details>
</summary>

**Comment by sakluger** [comment] 2024-02-25 19:11
Sorry about that, sometimes when we're changing one label, GH will add or remove another. I've added back the help wanted label.

**Comment by godofoutcasts94** [comment] 2024-02-26 07:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace switcher - Workspace switcher reopens after selecting a workspace with keyboard
### What is the root cause of that problem?
The root cause of the problem, is here :

https://github.com/Expensify/App/blob/5eed6322bd2e559c684481e8bc0122b0825779e7/src/components/WorkspaceSwitcherButton.tsx#L47-L51

is that when we press the `Workspace Switcher Button`, we run the `interceptAnonymousUser` function which checks if the user is anonymous or not and after that it makes a `callback` which navigates us again back to the `Workspace Switcher` button.
### What changes do you think we should make in order to solve the problem?


Rather what we should do is 
```
                onPress={() => {
                    if (DomUtils.getActiveElement()) {
                        Navigation.navigate(ROUTES.WORKSPACE_SWITCHER);
                        (DomUtils.getActiveElement() as HTMLElement | null)?.blur();
                    }
                }}
```
this will help us to navigate away from the workspace switcher button.

### Result

https://github.com/Expensify/App/assets/158435970/3cb1d44e-775a-46f2-bd38-9027c804f9d3

### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment] 2024-02-26 07:21
hello @situchan please review this [proposal](https://github.com/Expensify/App/issues/35823#issuecomment-1963457490), If you want some other solution or if you have any other thoughts then please let me know

**Comment by godofoutcasts94** [comment] 2024-02-26 15:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace switcher - Workspace switcher reopens after selecting a workspace with keyboard
### What is the root cause of that problem?
The root cause of the problem, is here :

https://github.com/Expensify/App/blob/5eed6322bd2e559c684481e8bc0122b0825779e7/src/components/WorkspaceSwitcherButton.tsx#L47-L51

is that when we press the `Workspace Switcher Button`, we run the `interceptAnonymousUser` function which checks if the user is anonymous or not and after that it makes a `callback` which navigates us again back to the `Workspace Switcher` button.
### What changes do you think we should make in order to solve the problem?


Rather what we should do is 
```
                onPress={() => {
                    if (DomUtils.getActiveElement()) {
                        Navigation.navigate(ROUTES.WORKSPACE_SWITCHER);
                        (DomUtils.getActiveElement() as HTMLElement | null)?.blur();
                    }
                }}
```
this will help us to navigate away from the workspace switcher button.

### Result

https://github.com/Expensify/App/assets/158435970/2db2fd7c-3f66-4679-881a-4dece7bce595


### What alternative solutions did you explore? (Optional)
N/A

**Comment by situchan** [comment] 2024-02-26 16:03
@godofoutcasts94 thanks for the proposal but I don't think the root cause is correct.

**Comment by godofoutcasts94** [comment] 2024-02-26 16:12
> @godofoutcasts94 thanks for the proposal but I don't think the root cause is correct.

okay, thanks for updating. I will think more about it @situchan

**Comment by sakluger** [comment] 2024-02-29 22:19
I'll leave this issue as is for another few days in case @godofoutcasts94 wants to submit an updated proposal. Next week, I'm going to reach out to one of the agencies we work with to se if they're able to help here.

**Comment by situchan** [comment] 2024-03-04 14:50
Still awaiting proposals

**Comment by sakluger** [comment] 2024-03-06 22:41
Asked for help from Callstack: https://expensify.slack.com/archives/C03UK30EA1Z/p1709764872486059

**Comment by sakluger** [comment] 2024-03-07 16:44
Callstack is unavailable. I asked SWM as well: https://expensify.slack.com/archives/C04878MDF34/p1709829864088989

**Comment by cdOut** [comment] 2024-03-07 23:41
Hello, I’m Tymoteusz from Software Mansion, the expert agency, and I’d like to work on this task.

**Comment by sakluger** [comment] 2024-03-08 00:34
Thanks @cdOut! I've assigned you now.

**Comment by sakluger** [comment] 2024-03-11 16:37
Hey @cdOut, any updates on this one?

**Comment by sakluger** [comment] 2024-03-14 19:02
Thanks @cdOut. Are you still determining the root cause, or are you just finishing your proposal?

**Comment by mountiny** [comment] 2024-03-18 11:22
Asked for an update in [Slack](https://expensify.slack.com/archives/C04878MDF34/p1710760878896769)

**Comment by cdOut** [comment] 2024-03-18 11:53
Updated you on slack, please check the thread @mountiny

**Comment by cdOut** [comment] 2024-03-18 11:55
As a follow up to the slack discussion, I will be working on it today and try to provide a working solution by tomorrow.

**Comment by cdOut** [comment] 2024-03-19 11:45
I'm still investigating this issue, I asked around the team and got some pointers to where to look for potential fixes from people who worked on the switcher.

**Comment by cdOut** [comment] 2024-03-21 09:59
I'm still investigating it, we've found another bug in the same functionality and condition for the workspace switcher so I'm trying to tackle a good solution for it.

https://github.com/Expensify/App/assets/88325488/f6af6d2b-671b-42f7-9f7e-b82af7bf10db

**Comment by cdOut** [comment] 2024-03-25 10:10
I'm working on creating a draft PR for this issue, should be up by tomorrow.

**Comment by mountiny** [comment] 2024-03-27 23:45
@cdOut any updates?

**Comment by cdOut** [comment] 2024-03-28 09:51
I've been testing my fix implementation on different devices and came across some errors for native especially, I'll be fixing it today and a draft for this bug should hit at last by the EOW.

**Comment by mountiny** [comment] 2024-03-29 22:08
@cdOut have you had a chance to create a draft?

**Comment by rushatgabhane** [comment] 2024-03-30 06:46
i can be c+ since @situchan is OOO. please reassign

**Comment by mallenexpensify** [comment] 2024-04-01 16:29
@situchan is out OOO, reassigning a C+ via the auto-assigner for fairness.

**Comment by cdOut** [comment] 2024-04-02 13:53
@mountiny  I've created the PR and we already checked it interally, it's currently waiting for review and approve. The delay with it was caused by [this issue appearing after changes to main](https://github.com/Expensify/App/issues/35823#issuecomment-2011796368) which I was trying to tackle in this PR.

The secondary issue as it turns out was fixed by proxy in [this PR](https://github.com/Expensify/App/pull/38490) which has been merged yesterday and now after merging with main the workspace switcher bug should be fully solved.

**Comment by cdOut** [comment] 2024-04-02 13:53
@getusha This PR is ready for review, let me know if you find any issues.

**Comment by cdOut** [comment] 2024-04-03 12:50
While the Workspace Switcher and numerous associated utils were undergoing simultaneous refactoring, it's possible that this problem was inadvertently resolved in one of these processes. 

Nonetheless, I recommend incorporating the fix into our codebase. This action will effectively clear the focus from the Workspace Switcher button upon activation, thereby preventing similar issues from occurring in future when navigating with the keyboard.

**Comment by sakluger** [comment] 2024-05-17 08:00
Catching up here, it sounds like:

1. The issue mostly self-resolved
2. We still merged & deployed the PR for the proposed fix because it will prevent similar issues from cropping up in the future

@isabelastisser could you please help process the payment for this issue since I'm going OOO today for the next two weeks? Thanks!

**Comment by isabelastisser** [comment] 2024-05-18 18:21
Payment summary:

@getusha C+ review $250
@cdOut Contributor $250


https://www.upwork.com/ab/applicants/1791896534622019584/job-details

**Comment by getusha** [comment] 2024-05-19 13:34
@isabelastisser accepted the offer

**Comment by mountiny** [comment] 2024-05-20 19:04
@cdOut is agency worker so no payment there

Once @getusha is paid out we can close this issue @isabelastisser

**Comment by isabelastisser** [comment] 2024-05-21 16:09
@getusha, can you please share your Upwork profile? Thanks!

**Comment by situchan** [comment] 2024-05-21 16:27
Am I eligible for partial payment for proposals review? I had to reassign just because of OOO, while waiting for agency PR.

**Comment by getusha** [comment] 2024-05-22 18:21
> @getusha, can you please share your Upwork profile? Thanks!

@isabelastisser https://www.upwork.com/freelancers/~01460cf774c356f209

**Comment by mountiny** [comment] 2024-05-23 21:31
@situchan I think that in this we will just move ahead, the most work has been done on the PR and the review/ checklist/ testing there so I would say only $250 to @getusha in this case. 

There will be many more opportunities for you

**Comment by isabelastisser** [comment] 2024-05-24 00:12
Thanks, team! Closing.

**Closed by isabelastisser** 2024-05-24 00:12 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug

**Comment by getusha** [comment] 2024-05-24 10:19
@isabelastisser accepted the offer, could you end it? thanks
