### ISSUE TITLE
IOU - IOU preview briefly displayed when navigating via deeplink & blank space below transaction

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39509] opened 2024-04-03 14:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4471359
**Issue reported by:** Applause - Internal Team

## Action Performed:
precondition: user created one IOU and copied the link
1. Log out of ND
2. Using the deeplink navigate to the IOU report
3. Log in with the account used to create the IOU

## Expected Result:
The combined expense view is displayed

## Actual Result:
IOU preview is displayed briefly. After the combined expense view is opened, there is a blank space below the transaction details (iOS). It disappears after scrolling

## Workaround:
Unkn0wn

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/670f16c3-5603-4bef-9e3c-3f84bf5b7bfb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bondydaa** [comment] 2024-04-03 17:13
Trying to reproduce this, this is what I see after I create a new IOU report between 2 users:

<img width="2168" alt="image" src="https://github.com/Expensify/App/assets/4073354/39f646ff-5c54-4539-988f-2012f5a474a4">

copying this url https://staging.new.expensify.com/r/4716128617010173 then and logging into a new incognito browser: i see 
<img width="1922" alt="image" src="https://github.com/Expensify/App/assets/4073354/c0a6d7c5-093e-4c17-befb-de4bae4f8f89">

Here's a video: https://github.com/Expensify/App/assets/4073354/f07008a1-40fb-49af-aff5-33f3497b92b6


But you're saying I should see this? 
<img width="1922" alt="image" src="https://github.com/Expensify/App/assets/4073354/4b8f333a-f83b-48a5-a7be-06242348ce96">


I am able to view that report if I use this url https://staging.new.expensify.com/r/6436117858044165 instead.

**Comment by bondydaa** [comment] 2024-04-03 17:15
using that same url https://new.expensify.com/r/4716128617010173 for prod takes me to 
<img width="2169" alt="image" src="https://github.com/Expensify/App/assets/4073354/69f01752-70c4-4dbe-8227-51c6bb6e01fb">

**Comment by bondydaa** [comment] 2024-04-03 17:17
@lschurr can you help me out here and confirm if this happens on iOS? I don't have any iOS devices to test with.

I'm not exactly sure either on what the behavior is, as best I can tell depending on the link you use it seems to redirect properly after you sign in.

**Comment by lschurr** [comment] 2024-04-03 17:31
Hmmm I'm having a hard time reproducing. I grabbed the link from web via lschurr@expensifail.com and opened it on iOS and got this screen:

<img width="369" alt="image" src="https://github.com/Expensify/App/assets/33293730/c61c81f9-619a-41c5-a77f-74c77b608a06">

Seems correct to me?

**Comment by bondydaa** [comment] 2024-04-03 18:07
okay after figuring all of that out, i see now what your video is showing that the chat report with the preview opens very briefly first before showing the IOU / expense report view of the single expense. trying to test this again on browserstack

**Comment by bondydaa** [comment] 2024-04-03 19:02
Hmm okay I can't reproduce this and @mountiny and @NikkiWines agreed this wasn't a blocker. I'm going to close it out but if others can reproduce it then feel free to reopen

**Closed by bondydaa** 2024-04-03 19:02 UTC
Labels: Engineering, Hourly, Bug
