### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] Web - Frequently used emojis is listed wrong

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27464] opened 2023-09-14 18:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Open the emoji picker
3. Choose an emoji that is not in the frequently used emoji list
4. Open the emoji picker again and see at what position this emoji is in the frequently used emoji list
5. Close the emoji picker
6. Type a lot of characters
7. Open the emoji picker

## Expected Result:
 The emoji you chose should be at the same position in step 4 and step 7 because you didn't used it more

## Actual Result:
The emoji you used is in the top position of the frequently used emoji

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a33cfa20-b74b-440f-ace9-97e4ddd08b7e

https://github.com/Expensify/App/assets/93399543/88f10020-8fbd-4c1f-a9b6-aad544352d0a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ShogunFire
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694526008852389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-09-14 18:17
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The frequently used emojis list is in the wrong order
### What is the root cause of that problem?
We are updating the frequently used emojis with the emojis we inserted here:
https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L134-L137
And we are retrieving those emojis in updateComment here:
https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L182
The emojis are extracted from the text in [replaceAndExtractEmojis](https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/libs/EmojiUtils.js#L360)
The problem with that method is that we are returning the emojis from the text even when they were already there before so at each character the user type we will add the same emojis which will make us think that we are using the emoji way more than what is actually happening
### What changes do you think we should make in order to solve the problem?
We need to save the emojis that were in the text before in a variable called emojisPresentBefore and the insertedEmojis variable that we use to update the frequently used emoji will be filled with emojis that are in this text minus the emojis from emojisPresentBefore.
The same behaviour is present in ReportActionItemMessageEdit so we need to do the same thing.
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-09-15 08:18
@ShogunFire It seems your solution will cause the regression, but I am not sure about that. To confirm could you help to detail your solution?

**Comment by ShogunFire** [comment] 2023-09-15 14:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The frequently used emojis list is in the wrong order

### What is the root cause of that problem?

We are updating the frequently used emojis with the emojis we inserted here:
https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L134-L137
And we are retrieving those emojis in updateComment here:
https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L182
The emojis are extracted from the text in [replaceAndExtractEmojis](https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/libs/EmojiUtils.js#L360)
The problem with that method is that we are returning the emojis from the text even when they were already there before so at each character the user type we will add the same emojis which will make us think that we are using the emoji way more than what is actually happening

### What changes do you think we should make in order to solve the problem?

We need to save the emojis that were in the text before in a variable called emojisPresentBefore and the insertedEmojis variable that we use to update the frequently used emoji will be filled with emojis that are in this text minus the emojis from emojisPresentBefore.

1) emojisPresentBefore must be filled with the emojis present in the drafts to avoid sending the draft emojis twice:
```
var emojisPresentBefore = [];
const [value, setValue] = useState(() => {
    const draft = getDraftComment(reportID) || '';
    if (draft) {
        emojisPresentBefore = EmojiUtils.extractEmojis(draft);
    }
    return draft;
});
```

2) We can remove the callback onInsertedEmoji because the emojis inserted with suggestion list will be parsed and added in the frequent emojis list in updateComment like the other emojis

3) In update comment we fill insertedEmojis only with the new emojis like this:
```
const newEmojis = EmojiUtils.getAddedEmojis(emojis, emojisPresentBefore);

insertedEmojisRef.current = [...insertedEmojisRef.current, ...newEmojis];
```
And after that we also update emojisPresentBefore in every cases even if there is no emoji

4) The new method getAddedEmojis looks like this for now: Maybe there is a better way to get the new emojis:
```
function getAddedEmojis(currentEmojis, formerEmojis){
    
    let newEmojis = [...currentEmojis];
    // We are removing the emojis from the newEmojis array if they were already present before.
    formerEmojis.forEach((formerEmoji) => {
        const indexOfAlreadyPresentEmoji = newEmojis.findIndex(newEmoji => newEmoji.code == formerEmoji.code);
        if(indexOfAlreadyPresentEmoji >= 0) {
            newEmojis.splice(indexOfAlreadyPresentEmoji, 1);
        }
    });
    return newEmojis;
}
```

5) Right now extractEmojis method only returns 1 time the emojis even if there are 3 occurences of the same emoji, we need to return the 3 occurences

The same behaviour is present in ReportActionItemMessageEdit so we need to do the same thing.

This is just the primary version but here is my branch that is working fine for  ComposerWithSuggestions:
https://github.com/ShogunFire/App/tree/fixFrequentlyUsedEmojiSentMultipleTimes



### What alternative solutions did you explore? (Optional)

**Comment by ShogunFire** [comment] 2023-09-15 14:43
@DylanDylann I couldn't edit the proposal but yes this was a little more complex than I thought, I hope the regression you were speaking about is not present with that version

**Comment by mananjadhav** [comment] 2023-09-17 18:40
I think @ShogunFire's proposal will work. It looks a bit complex and we can try to simplify during the PR stage. For instance, @ShogunFire will this simplify your `getAddedEmojis` logic, if I understand it correct?

```
function getAddedEmojis(currentEmojis, formerEmojis) {
    return currentEmojis.filter((currentEmoji) => {
        return !formerEmojis.some((formerEmoji) => currentEmoji.code === formerEmoji.code);
    });
}

```


🎀 👀 🎀 C+ reviewed.

**Comment by ShogunFire** [comment] 2023-09-18 02:35
@mananjadhav Thanks, I don't think we can do that because if we have "🙂" before and "🙂🙂" after I think we need to update the count of the emoji so getAddedEmojis has to return 1 🙂. I will think of a better way to do that but it looks kind of hard to make it simple.

**Comment by Pujan92** [comment] 2023-09-18 07:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unnecessary api calls for frequently used emoji when we update the comment and that leads to the wrong order.

### What is the root cause of that problem?
Currently, we are incorporating the below 3 scenarios for calling the `UpdateFrequentlyUsedEmojis` api.

1. When we select an emoji from the emojipicker [here](https://github.com/Expensify/App/blob/01c5b71e8f9d3385a583d669b98579a02936f867/src/components/EmojiPicker/EmojiPickerMenu/index.js#L258-L260)
2. Select an emoji from the emoji suggestions for the composer [here](https://github.com/Expensify/App/blob/01c5b71e8f9d3385a583d669b98579a02936f867/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L138-L141)
3. Type an emoji code(: smile :) in the composer [here](https://github.com/Expensify/App/blob/01c5b71e8f9d3385a583d669b98579a02936f867/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L176-L182)

In the `updateComment` function we fetch the emojis from the comment and make an update api call, instead it should only call if a user enters the emoji code.

### What changes do you think we should make in order to solve the problem?

We can update `replaceAndExtractEmojis` function to only return new emojis which will be replaced in the comment text.
With that, we don't get an emojis array every time when the comment gets updated and that prevents unnecessary api calls.

https://github.com/Expensify/App/blob/01c5b71e8f9d3385a583d669b98579a02936f867/src/libs/EmojiUtils.js#L360-L365

```
return { 
    text: convertedText, 
    emojis
}
```

https://github.com/Expensify/App/assets/14358475/1f0c8cb3-cf6c-449c-a266-df89de2da32c

- With my suggested solution 1 scenario won't work and I just wanted to clarify that are we also supporting adding the emoji to the `FrequentlyUsedEmojis` when it is copied & pasted into the composer?

@mananjadhav @joelbettner

**Comment by DylanDylann** [comment] 2023-09-18 07:27
@Pujan92 
```
emojis: emojis.concat(extractEmojis(text)), 
```

This is a feature, we can't remove it

**Comment by Pujan92** [comment] 2023-09-18 08:07
> emojis: emojis.concat(extractEmojis(text)), 
>
> This is a feature, we can't remove it ref: #21786

Thanks @DylanDylann , I tried but wasn't able to find this ref earlier.

**Comment by stephanieelliott** [comment] 2023-10-06 05:12
Hey @mananjadhav have you had a chance to review?

**Comment by mananjadhav** [comment] 2023-10-06 05:21
@stephanieelliott Yes I did my review and completed the [checklist](https://github.com/Expensify/App/pull/27687#issuecomment-1747713041). Waiting for @joelbettner now.

**Comment by mananjadhav** [comment] 2023-10-10 10:44
@joelbettner quick bump

**Comment by stephanieelliott** [comment] 2023-10-11 05:09
Hey @joelbettner this one is waiting for your review: https://github.com/Expensify/App/issues/27464#issuecomment-1722538988

**Comment by mananjadhav** [comment] 2023-10-11 05:11
@stephanieelliott this was merged 14 hours ago.

**Comment by joelbettner** [comment] 2023-10-23 21:01
I'm so confused...

It took me forever to get to this since I was working on other high-priority, time sensitive issues. But...it looks like the soltion for this has already been merged/deployed?? If not, I think the proposal [here](https://github.com/Expensify/App/issues/27464#issuecomment-1721395451) seems good. (cc: @mananjadhav @stephanieelliott @ShogunFire)

**Comment by stephanieelliott** [comment] 2023-10-24 02:11
Ya Melvin kirked out on this one, it's a single PR that triggered the automation multiple times. Everything is done here though, just needs to be paid out! 

Summarizing payment: 
 - Issue reporter: @ShogunFire $50, pay via Upwork
 - Contributor: @ShogunFire $500, pay via Upwork 
 - Contributor+: @mananjadhav $500, request via NewDot
 
 Upwork job is [here](https://www.upwork.com/jobs/~01bec5d8c4497434db), not eligible for bonus

**Comment by stephanieelliott** [comment] 2023-10-24 02:11
@ShogunFire I extended the offer to you in Upwork, can you please accept when you get a chance? Thanks! https://www.upwork.com/jobs/~01bec5d8c4497434db

**Comment by ShogunFire** [comment] 2023-10-24 17:35
@stephanieelliott thanks , I did

**Comment by mananjadhav** [comment] 2023-10-24 18:13
I've raised the request on NewDot.

**Comment by JmillsExpensify** [comment] 2023-10-24 18:36
$500 payment approved for @mananjadhav based on summary above.

**Comment by stephanieelliott** [comment] 2023-10-25 21:12
All paid!

**Closed by stephanieelliott** 2023-10-25 21:12 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by ShogunFire** [comment] 2024-05-26 11:07
Hello @stephanieelliott , sorry for the late request but could you please put the [upwork mission](https://www.upwork.com/jobs/~01bec5d8c4497434db) as complete ? It still shows as in progress on my profile. Thanks

**Comment by stephanieelliott** [comment] 2024-05-30 21:51
Hey @ShogunFire no problem. I saw your email come through and have I closed this contract as well as the other 2 completed contracts that were still active on your profile (#20998, #19389)
