### ISSUE TITLE
[HOLD #311970][$500] [Wave 6: Tags] After deleting the tags on OD, the tags are still displayed on ND

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30455] opened 2023-10-26 16:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in as the admin of collect workspace on OD and as employee of the same workspace on ND. Also, a tag must have been added to the workspace
1. As admin of workspace on OD, go to workspace settings
2. Go to "Tags" tab
3. Delete all the tags
4. As the employee on ND. go to workspace chat
5. Initiate a manual money request
6. Enter the amount and click on "Next"
7. Click on the tag field

## Expected Result:
There should be no tags, since they were eliminated

## Actual Result:
The tags are still shown as selectables

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/Expensify/App/assets/78819774/48f27fe2-f3da-4eff-bf2b-497669f8ac08

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01107a2cd309d2e06c</li>
        <li>Upwork Job ID: 1717581208383598592</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

**Comment by iiredalert** [comment] 2023-10-26 17:12
Hello, how do you access the workspace settings page that allows you to add / remove tags for a workspace?

**Comment by abdel-h66** [comment] 2023-10-28 19:49
`openDraftWorkspaceRequest` should set the policy tags as it does for the categories. This is a backend issue.

**Comment by mollfpr** [comment] 2023-10-30 13:39
@iiredalert You can ask to be invited to the collect workspace in the Slack channel.

**Comment by wlegolas** [comment] 2023-10-31 22:35
Hi @mollfpr I sent a message on Slack to have this access, but anyone answered, could you help me, please?

Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1698706963990009

**Comment by mollfpr** [comment] 2023-11-01 09:09
@wlegolas I can add your account to the demo workspace. Just give me your email, and I'll invite you.

**Comment by wlegolas** [comment] 2023-11-01 09:56
> @wlegolas I can add your account to the demo workspace. Just give me your email, and I'll invite you.

Hi @mollfpr, thank you for your help.

I'm using two emails, for the admin I'm using wesshead@gmail.com, and for the employee, I'm using wlegolas@hotmail.com

With this invitation, can I be the admin of the collection workspace in OD? I'm just asking if with this invitation my users will have the prerequisite to test this behavior.

**Comment by Victor-Nyagudi** [comment] 2023-11-01 10:27
I'd also like to be added to the demo workspace, please @mollfpr. 

Email: vicktests4@gmail.com

**Comment by mollfpr** [comment] 2023-11-01 10:36
@wlegolas @Victor-Nyagudi Invited!

**Comment by wlegolas** [comment] 2023-11-01 22:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Request Money - After deleting the tags on OD, the tags are still displayed on ND

### What is the root cause of that problem?

Policy tags are not syncing when removing all of the tags in the OD application. When removing all tags in the OD application, the ND application has the Policy tags in the Onyx state, that's why the tags are available when creating a new request for money.

### What changes do you think we should make in order to solve the problem?

We should reset the Policy tags in the Onyx state before making the request `OpenDraftWorkspaceRequest`, changing the method `openDraftWorkspaceRequest`:

https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/libs/actions/Policy.js#L1319-L1321

This is an example of the change that we should do to fix this behavior:

```
/**
 * @param {String} policyID
 */
function openDraftWorkspaceRequest(policyID) {
    Onyx.set(`${ONYXKEYS.COLLECTION.POLICY_TAGS}${policyID}`, {});

    API.read('OpenDraftWorkspaceRequest', {policyID});
}
```

### What alternative solutions did you explore? (Optional)

N/A

**POC**

https://github.com/Expensify/App/assets/698363/18fb13e6-f3a4-482d-9409-da6b17d35ef8

**Comment by Victor-Nyagudi** [comment] 2023-11-02 10:55
@mollfpr I think I'll let this one go.

Kindly remove me from the workspace. All the activity there is bloating up my LHN.

I'd do it myself, but I don't see the option to leave a workspace.

**Comment by mollfpr** [comment] 2023-11-02 13:52
@wlegolas Could you check if this issue only happens on tags or if it also happens on categories?

**Comment by wlegolas** [comment] 2023-11-02 14:08
Sure @mollfpr, but I need to remove all categories, is it ok?

**Comment by mollfpr** [comment] 2023-11-02 15:02
@wlegolas Don't then 😅

I think we might encounter the same problem with the categories. What do you think?

**Comment by wlegolas** [comment] 2023-11-03 00:03
> @wlegolas Don't then 😅
> 
> I think we might encounter the same problem with the categories. What do you think?

Don't worry I didn't remove the categories.

I'm not 100% sure, but the same problem may occur for categories.

If you want, I can change my proposal to reset the current Policy's Tags and Categories in the Onyx state.

**Comment by CortneyOfstad** [comment] 2023-11-06 16:56
@mollfpr any updates? TIA!

**Comment by mollfpr** [comment] 2023-11-06 17:48
@wlegolas I did test the issue on the categories, but it's not occurring.

The [proposal](https://github.com/Expensify/App/issues/30455#issuecomment-1789802138) from @wlegolas makes sense to me. We will get the tags (if there are any) by calling `OpenDraftWorkspaceRequest`.

There's another option to fix this issue from BE.
1. Creating the pusher notification on deleting the tags as we did for the categories
2. Fixing the `OpenDraftWorkspaceRequest` API to return an empty object without tags data.

🎀 👀 🎀 C+ reviewed!

**Comment by wlegolas** [comment] 2023-11-06 22:00
Hi @mollfpr, I'm sorry to ask I'm confused.

In this case, my [proposal](https://github.com/Expensify/App/issues/30455#issuecomment-1789802138)  was not accepted or is it awaiting further analysis?

**Comment by amyevans** [comment] 2023-11-07 16:52
👋 Apologies for only seeing this bug now, but this is the direction we should go:

> Creating the pusher notification on deleting the tags as we did for the categories

This is planned functionality, just hasn't been implemented yet. Relevant internal issue: https://github.com/Expensify/Expensify/issues/311970

**Comment by wlegolas** [comment] 2023-11-07 22:23
> @wlegolas It depends on @marcochavezf decision, if we decide to fix the issue from the FE side, we can go with your proposal, and I'd recommend your proposal to them.

Hi @mollfpr thank you for clarifying, I asked because I didn't understand if I needed to start the changes or wait.

I think the @amyevans's message answered my question.

If you need anything else and I can help, you can count on me, thank you for all your support.

**Comment by marcochavezf** [comment] 2023-11-08 01:21
> 👋 Apologies for only seeing this bug now, but this is the direction we should go:
> 
> > Creating the pusher notification on deleting the tags as we did for the categories
> 
> This is planned functionality, just hasn't been implemented yet. Relevant internal issue: [Expensify/Expensify#311970](https://github.com/Expensify/Expensify/issues/311970)

Hi @amyevans, just for clarification, should we implement the frontend changes proposed by @wlegolas? Or will it also be addressed internally?

**Comment by amyevans** [comment] 2023-11-08 13:26
@marcochavezf the backend change is all that's needed to close this out. You can `HOLD` this on 311970 and/or assign over to me

**Comment by marcochavezf** [comment] 2023-11-08 15:26
Sounds good, thanks @amyevans!

**Comment by puneetlath** [comment] 2023-11-13 16:52
I think we can just close this out as a dupe of https://github.com/Expensify/Expensify/issues/311970. Feel free to reopen if you disagree!

**Closed by puneetlath** 2023-11-13 16:52 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
