### ISSUE TITLE
[HOLD for payment 2024-11-18] [$500] [MEDIUM] Distance - Details page does not show error when invalid address is added in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29783] opened 2023-10-17 14:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Go to workspace chat
3. Create a distance request
4. Open the distance details page
5. Go offline
6. Tap on Distance > Add stop
7. Enter an invalid and non-existent address and save it
8. Go online
9. Tap on Distance

## Expected Result:
The error message about invalid point show appear in both distance details page and distance editor

## Actual Result:
The error message about invalid point only appears in the distance editor

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/30332532-991f-4d1d-96fa-cd93393b31c0

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101b2f741a0bdb5c5</li>
        <li>Upwork Job ID: 1714289099635212288</li>
        <li>Last Price Increase: 2023-10-24</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Contributor | 27429661</li>
<li>dukenv0307 | Contributor | 27442050</li>
<li>paultsimura | Contributor | 104962397</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by kadiealexander** [comment] 2023-10-24 04:26
@aimane-chnaif please review above

**Comment by kadiealexander** [comment] 2023-10-27 03:34
@aimane-chnaif I've asked if someone can take over this issue as the proposal is 9 days old.

**Comment by getusha** [comment] 2023-10-27 03:47
@kadiealexander This issue was decided to be closed before because it is intentional behavior and not a bug. and i think we should close it.  check the discussion in this issue https://github.com/Expensify/App/issues/27021

**Comment by getusha** [comment] 2023-10-27 08:33
@kadiealexander please assign @aimane-chnaif again.

**Comment by kadiealexander** [comment] 2023-10-30 01:54
Added @aimane-chnaif.

**Comment by francoisl** [comment] 2023-10-30 18:07
Makes sense to me, let's go with this proposal!

**Comment by danielrvidal** [comment] 2023-11-02 19:38
What is the suggestion? I think I see two:
- In the [video](https://github.com/Expensify/App/issues/29783#issuecomment-1766568011) I see: `Please select a valid waypoint`
- But then above, I see: `Distance request has route error` in English

But either way, I think for an error where the address is wrong I would say:
- `Please select a valid address`
- I think it's more common to say address than waypoint. 
- It is more specific than `Distance request has route error`

**Comment by danielrvidal** [comment] 2023-11-02 19:43
I'm going to unassign myself but don't hesitate to add me back on if I'm needed again. Sorry for the delay!

**Comment by neil-marcellini** [comment] 2023-11-22 18:35
@kadiealexander FYI only @situchan should be paid for C+ review based on [this comment](https://github.com/Expensify/App/pull/30621#issuecomment-1823279345) on the PR

**Comment by kadiealexander** [comment] 2023-12-20 03:44
PR is still being worked on actively.

**Comment by neil-marcellini** [comment] 2024-10-31 16:19
Re-opening because this is reproducible again as @dukenv0307 [pointed out here](https://expensify.slack.com/archives/C02NK2DQWUX/p1730390864141779?thread_ts=1730390770.231389&cid=C02NK2DQWUX).

**Comment by mvtglobally** [comment] 2024-11-08 15:26
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-11-16 01:54
Issue not reproducible during KI retests. (Second week)

**Comment by kadiealexander** [comment] 2024-11-19 02:58
Payouts due:

- [ ] Contributor: $250 @dukenv0307 ([offer](https://www.upwork.com/nx/wm/offer/27442050))
- [ ] Reviewer: $250 @paultsimura ([offer](https://www.upwork.com/nx/wm/offer/104962397))

Upwork job is [here](https://www.upwork.com/jobs/~0101b2f741a0bdb5c5).

**Closed** 2024-11-20 02:34 UTC
Labels: External, Daily, Awaiting Payment, Bug
