### ISSUE TITLE
[$250] RBR displayed on expense preview but no error in expense details on Employee 1 side

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#48025] opened 2024-08-26 19:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisite: Create a Control workspace, set "Manually approve all expenses over" to $10 and set Advanced approval in OD as:

1. Boss owner (admin) submits to Mini owner
2. Mini owner (admin) submits Boss owner
3. Manager (employee) submits to Mini owner, forwards to Mini owner, over limit forwards (limit 100) to Boss owner
4. Employee 1 (employee) submits to Manager

## Expected Result:
RBR on expense preview should be displayed if there is an error displayed on expense details page.

## Actual Result:
RBR is displayed on expense preview but there is no error on expense details page.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/aa34e55b-30cc-4863-b7c2-2c331ce4de89

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c80d6113db7d8a4e</li>
        <li>Upwork Job ID: 1829381375681672456</li>
        <li>Last Price Increase: 2024-08-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ntdiary</details>

**Comment by jliexpensify** [comment] 2024-08-30 04:51
I can't reproduce this one reliably, going to assign `External` to see if C+ can!

**Comment by jliexpensify** [comment] 2024-09-06 03:45
Any luck @ntdiary?

**Comment by jliexpensify** [comment] 2024-09-06 04:18
Ok, thanks for trying! Lets close this one then.

**Closed by jliexpensify** 2024-09-06 04:18 UTC
Labels: External, Daily, Help Wanted, Bug
