### ISSUE TITLE
[$500] Android - Login - Autofill not triggered when tap on email field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20274] opened 2023-06-06 15:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Android app
2. Tap on Email field

## Expected Result:
There's an autofill feature when focusing the email field

## Actual Result:
Autofill is not triggered when user taps on email field. Autofill feature works on mWeb chrome on the same device.
(I have saved account data in Google password manager for the following domains : expensify.com ; new.expensify.com ; staging.expensify.com; staging.new.expensify.com)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8028c2a6-78d8-49d1-8ba5-c5a34a36b831

https://github.com/Expensify/App/assets/93399543/fb0a8117-84ca-4314-9950-341255d461d9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a1ed062599e71d9</li>
        <li>Upwork Job ID: 1706259828412588032</li>
        <li>Last Price Increase: 2024-07-16</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment] 2023-06-06 23:42
@kbecciv - this issue says the bug occurs on `mweb` (title) and `Android / Chrome` (body), but the video seems to show the Android Native app doesn't show the autofill option and Chrome does?

Which is correct? Does this come from a test at all?

**Comment by kbecciv** [comment] 2023-06-07 13:05
Hey @twisterdotcom Sorry for confusion, It happened on Android app only , QA team only demonstrated the mWeb behaviour to show that the autofill is enabled on the device.
Please attached a new video, will update the original issue as well.

https://github.com/Expensify/App/assets/93399543/2e1d6347-1359-420a-9f1e-30864ee90de1

**Comment by twisterdotcom** [comment] 2023-06-12 10:20
Thanks for the update, I will test today.

**Comment by twisterdotcom** [comment] 2023-06-14 15:21
I have updated my Android  device and apps finally. I still do not see this error:
https://drive.google.com/file/d/1j6Z1nkKbnkIkqRkjV_FyGcZhCepR__vi/view?usp=sharing

**Comment by lanitochka17** [comment] 2023-09-11 18:21
Issue reproducible on Build 1.3.67-1 / Android

https://github.com/Expensify/App/assets/78819774/3472d199-58f9-4d12-be7d-2d8bbc4bd6c4

**Comment by sophiepintoraetz** [comment] 2023-09-25 10:51
Given that Applause have been able to reproduce it, I am going to make this External. Though I'm not sure why this hasn't triggered the auto assigner for a C+ - was going to ask them to confirm whehter they can reproduce- @trjExpensify, just assigned you to baby sit whilst Ted is OOO.

**Comment by akinwale** [comment] 2023-09-25 10:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On the login form on Android native, autofill suggestions are not displayed when the input field is focused.

### What is the root cause of that problem?
The autoComplete prop is not specified in the BaseLoginForm component.

### What changes do you think we should make in order to solve the problem?
Add the `autoComplete` prop to the TextInput in BaseLoginForm. This can be set to "username" to maintain consistency with the other autofill related props, or "email".

### What alternative solutions did you explore? (Optional)
None.

**Comment by trjExpensify** [comment] 2023-09-25 11:41
Thread [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1695639425204229), looking for a fresh repro on Android native.

**Comment by akinwale** [comment] 2023-09-25 12:31
@thesahindia No extra row is displayed above the keyboard in the native app. That is a Chrome-only feature.

On native, the autofill suggestion(s) are displayed in the top row of the soft keyboard when you start typing, as seen in the video.

[20274-demo.webm](https://github.com/Expensify/App/assets/4160319/660729fa-08b6-44cd-8941-a92fdade7f20)

**Comment by b4s36t4** [comment] 2023-09-25 16:25
<img width="1728" alt="Screenshot 2023-09-25 at 9 53 30 PM" src="https://github.com/Expensify/App/assets/59088937/fca8fc4e-78c6-4e43-8c68-431e1d78a358">

I don't this that results are from updating `autoComplete`, without it also able to get result in keyboard. Keyboard suggestions are from keyboard maybe??

**Comment by b4s36t4** [comment] 2023-09-25 16:31
even the suggestions are from keyboard, but keyboard is only saving the suggestions when we update the prop.
![IMAGE 2023-09-25 22:01:28](https://github.com/Expensify/App/assets/59088937/3e2cf8ef-14ec-40ca-8ff4-b9090ae4d843)

But I do expect the suggestions like this, not from keyboard :). I think twitter also uses react-native so it is possible ;)

**Comment by trjExpensify** [comment] 2023-09-26 03:12
So what's the verdict here, sorry?

**Comment by b4s36t4** [comment] 2023-09-26 03:14
@trjExpensify I think as far as I see expected behavior should be same as attachment I shared Or close the issue as it might become impossible to implement.

**Comment by trjExpensify** [comment] 2023-09-26 10:18
Sorry if I'm being dense. Is this accurate? 

1. We are using auto-fill on Android native, insofar that it's supported in the software keyboard suggestions? 
2. On Android mWeb chrome we are using auto-fill, insofar that it's supported with an extra row above the keyboard?

If so, then we should be good to close this out.

**Comment by akinwale** [comment] 2023-09-27 03:40
Been doing some digging on this. It looks like there's a general bug with React Native's autofill implementation on Android which is preventing this from working. I'm trying to figure out a fix.

**Comment by trjExpensify** [comment] 2023-09-28 11:17
That would be great!

**Comment by twisterdotcom** [comment] 2023-10-02 13:24
I'll take this back over now. @akinwale keep me posted.

**Comment by twisterdotcom** [comment] 2023-10-05 12:14
@akinwale I'm going to make this Weekly. If we don't find anything, then I'm going to go with the recommendation from @trjExpensify and @b4s36t4 to just close.

**Comment by mvtglobally** [comment] 2023-10-12 03:42
Issue not reproducible during KI retests. (First week)

**Comment by twisterdotcom** [comment] 2023-10-16 11:45
Okay, let's close. Thanks for everyone's input here.

**Comment by lanitochka17** [comment] 2024-07-16 15:42
Issue is still reproducible 

https://github.com/user-attachments/assets/73708d1f-b5ab-4dd0-95e9-10ff0ae99f0f

**Comment by twisterdotcom** [comment] 2024-07-17 11:13
I think this is expected, and when you start typing an email it will prompt you: https://drive.google.com/file/d/1Bz6STrEzg20yjzPd9FogX_R-9y9JvEWx/view?usp=sharing

As discussed previously in this issue, I do not think this is an important thing to focus on fixing right now.

**Closed by twisterdotcom** 2024-07-17 11:13 UTC
Labels: External, Weekly, Help Wanted, Bug
