### ISSUE TITLE
[$250] [Search v1.2] Expense preview count & expense report do not update after deleting expense from Search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47617] opened 2024-08-18 21:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Manual.
3. Submit two expenses to any user.
4. Go to Search.
5. Select one of the submitted expenses in Step 3 via checkbox.
6. Click on the dropdown > Delete.
7. Delete the expense.
8. Go back to Inbox.
9. Open DM with the user in Step 3.
10. Click on the expense preview.

## Expected Result:
In Step 9, the expense preview count should update and no longer shows "2 expenses".
In Step 10, the expense report will be a combined report as there is only one expense.

## Actual Result:
In Step 9, the expense preview count does not update and still shows "2 expenses".
In Step 10, the expense report does not show combined report when there is only one expense.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7f3eb890-baeb-4fed-86f6-100648c82bf4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164693244e7052703</li>
        <li>Upwork Job ID: 1825574897454530648</li>
        <li>Last Price Increase: 2024-08-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by IuliiaHerets** [comment] 2024-08-18 21:25
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-08-18 21:26
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MarynaKip** [comment] 2024-08-19 21:08
Proposal

Update a count for support text substracting a number of deleted expanses:

ReportPreview.tsx

    const {supportText} = useMemo(() => {
        if (formattedMerchant && formattedMerchant !== CONST.TRANSACTION.DEFAULT_MERCHANT && formattedMerchant !== CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT) {
            return {supportText: truncate(formattedMerchant, {length: CONST.REQUEST_PREVIEW.MAX_LENGTH})};
        }
        if (formattedDescription ?? moneyRequestComment) {
            return {supportText: truncate(StringUtils.lineBreaksToSpaces(formattedDescription ?? moneyRequestComment), {length: CONST.REQUEST_PREVIEW.MAX_LENGTH})};
        }
        if (formattedMerchant === CONST.TRANSACTION.DEFAULT_MERCHANT) {
            return {supportText: formattedMerchant};
        }
        return {
            supportText: translate('iou.expenseCount', {
                count: numberOfRequests - numberOfScanningReceipts - numberOfPendingRequests,
                scanningReceipts: numberOfScanningReceipts,
                pendingReceipts: numberOfPendingRequests,
            }),
        };
    }, [formattedMerchant, formattedDescription, moneyRequestComment, translate, numberOfRequests, numberOfScanningReceipts, numberOfPendingRequests]);

**Comment by MarynaKip** [comment] 2024-08-19 21:13
Contributor details
Your Expensify account email: maryna.i.kipenko@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0135072b780205cb5e

**Comment by Amoralchik** [comment] 2024-08-19 22:08
@MarynaKip 
Please make sure you've read Contributing to Expensify and once you've understood everything, please format your comment according to the proposal template if you're interested in fixing this issue; otherwise, it won't be considered for review.

**Comment by Amoralchik** [comment] 2024-08-19 22:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
expense report do not update after deleting expense from Search
### What is the root cause of that problem?
After deleting a transaction on the Search page, the transaction still remains in ONYX.
### What changes do you think we should make in order to solve the problem?
We can add the following code to `deleteMoneyRequestOnSearch`:

```javascript
transactionIDList.forEach((transactionID) => {
    optimisticData.push({
        onyxMethod: Onyx.METHOD.SET,
        key: `${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`,
        value: {},
    });
    finallyData.push({
        onyxMethod: Onyx.METHOD.SET,
        key: `${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`,
        value: {},
    });
});
```
Thus, after executing the API request, we will remove the transaction data from Onyx.
### What alternative solutions did you explore? (Optional)
Maybe we can ask someone from the internal team to ensure that we receive a response that allows us to update the values in ONYX.

**Comment by codewaseem** [comment] 2024-08-19 23:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The expense preview count does not get updated when the report is deleted from the Search page. 

### What is the root cause of that problem?
The corresponding transactions are not set to null and the report actions are not filtered out if deleted.

### What changes do you think we should make in order to solve the problem?

Only setting the transactions to null will fix the count as also suggested by @Amoralchik, but it causes this bug. 
<img width="1058" alt="Screenshot 2024-08-20 at 04 23 48" src="https://github.com/user-attachments/assets/ff6e86de-4e3e-4dca-9dd5-5250b341ec63">

We also need to filter out the deleted report action from `ReportScreen` using `ReportActionsUtils.isDeletedAction(reportAction)`

### What alternative solutions did you explore? (Optional)

Alternatively, we can follow a similar approach as done in `deleteMoneyRequest` to handle other scenarious if needed. 
https://github.com/Expensify/App/blob/78c20f046be7a307a52050657bc041dd57d2fd53/src/libs/actions/IOU.ts#L5754-L5984

**Comment by ikevin127** [comment] 2024-08-21 16:20
@paultsimura We just pushed some changes related to this last week but seems like this is still happening. Digging into it to find out why ⛏️

**Comment by trjExpensify** [comment] 2024-08-26 13:07
Moving to wave-control project.

**Comment by luacmartins** [comment] 2024-08-26 18:11
This seems to have the same route cause as https://github.com/Expensify/App/issues/47385.

**Comment by sakluger** [comment] 2024-08-30 17:30
Thanks @luacmartins. Are you working on the BE issue for https://github.com/Expensify/App/issues/47385 or do we still need to recruit an engineer to fix the issue?

**Comment by sakluger** [comment] 2024-08-30 22:36
Commenting again for Melvin.

**Comment by sakluger** [comment] 2024-09-04 18:17
I'm just going to put a hold on this issue if it has the same root cause as https://github.com/Expensify/App/issues/47385.

**Comment by sakluger** [comment] 2024-09-12 21:53
The hold issue is fixed! I added the retest-weekly label to see if this one is fixed as well.

**Comment by sakluger** [comment] 2024-09-20 17:31
I asked again for a retest in the Slack QA channel: https://expensify.slack.com/archives/C9YU7BX5M/p1726853413386789

**Comment by m-natarajan** [comment] 2024-09-22 15:10
Able to reproduce this 



https://github.com/user-attachments/assets/36c79913-890d-4bba-a97f-30a44584e2bb

**Comment by sakluger** [comment] 2024-09-26 22:18
@luacmartins it seems that the hold issue didn't fix this one. Any ideas why it didn't fix this one?

**Comment by luacmartins** [comment] 2024-09-26 23:42
Not sure, gonna remove the hold to investigate.

**Comment by luacmartins** [comment] 2024-10-01 23:35
Haven't been able to prioritize this one yet, but it's on my list for this week.

**Comment by sakluger** [comment] 2024-10-07 16:23
@luacmartins any updates?

**Comment by luacmartins** [comment] 2024-10-09 17:26
I'm working on a [draft PR](https://github.com/Expensify/Auth/pull/12673)

**Comment by luacmartins** [comment] 2024-10-11 23:39
PR in review

**Comment by sakluger** [comment] 2024-10-17 20:59
@luacmartins I see that the PR was deployed. Does anything else need to be done here? Otherwise, I think we can just close the issue since there was no C+ review.

**Comment by luacmartins** [comment] 2024-10-17 21:24
I think we're good to close.

**Closed** 2024-10-17 21:24 UTC
Labels: Reviewing, Daily, Internal, Bug
