### ISSUE TITLE
[HOLD for payment 2023-08-07] Chat - Delete button is not functional

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19066] opened 2023-05-16 19:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensifail.com
2. Log in with any account
3. Click on FAB menu
4. Select Request money
5. Select the user and complete the request flow.
6. Open the Chat with requested money
7. Click on three dots
8. Select Delete button

Also this issue: https://expensify.slack.com/archives/C049HHMV9SM/p1684333083150029

## Expected Result:
Delete button is functional

## Actual Result:
Delete button is not functional

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** No (new feature)

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7d9c9fc8-c21b-45ad-ba2e-e9e44bfce19d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team and @niravkakadiya25

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684237536816689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0130f7d5c07b1b4ed7</li>
        <li>Upwork Job ID: 1658743808373661696</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-05-17 07:58
@luacmartins assume you picked this one up?

**Comment by laurenreidexpensify** [comment] 2023-05-18 17:34
Thanks, can you link the draft PR?

**Comment by luacmartins** [comment] 2023-05-18 23:11
Done! https://github.com/Expensify/App/pull/19095

**Comment by laurenreidexpensify** [comment] 2023-05-22 10:04
Carlos still drafting PR

**Comment by luacmartins** [comment] 2023-05-23 23:29
Auth and Web-E PRs are in review. Still working on some bugs on the App PR and confirming the expected behavior for some edge cases.

1. IOU Preview checkmark
2. LHN last messages

Confirming the following via our group DM

1. Do we need to update the IOUPreview of the request being deleted? Do we show it at all?
2. What should happen when we delete a transaction in the transaction view? Do we remove that thread and navigate the user to the IOU report?
3. Are we deleting the IOU report if the transaction being deleted is the last one in the report?

**Comment by luacmartins** [comment] 2023-05-24 20:55
Posted a few questions in [Slack](https://expensify.slack.com/archives/C02HWMSMZEC/p1684961254098309). Both Tom and Jason are ooo this week too, so I'm expecting progress to be slow on this one since we're still missing some high level pieces.

**Comment by luacmartins** [comment] 2023-05-29 15:12
Still waiting to align on the expected behavior in [this thread](https://expensify.slack.com/archives/C02HWMSMZEC/p1685018550757609), since a lot of people were ooo last week.

**Comment by luacmartins** [comment] 2023-05-30 20:20
Discussion is still ongoing. Here are the latest options we're considering: https://expensify.slack.com/archives/C02HWMSMZEC/p1685472162845689?thread_ts=1685018550.757609&cid=C02HWMSMZEC

**Comment by luacmartins** [comment] 2023-06-02 22:04
We've finally landed on a [solution](https://expensify.slack.com/archives/C02HWMSMZEC/p1685651090349129?thread_ts=1685018550.757609&cid=C02HWMSMZEC) to this. I made some progress today, but there's still a lot to do. I'll get back to it on monday.

**Comment by luacmartins** [comment] 2023-06-05 20:02
Working on it today. Progress in the PR.

**Comment by luacmartins** [comment] 2023-06-06 20:18
I'm working on it. Hopefully I'll get the App PR up today.

**Comment by laurenreidexpensify** [comment] 2023-06-07 10:55
I am OOO til 19 June, not assigning any other Bug Zero folks, offer has been sent to @0xmiroslav in Upwork, if payment is due before 19 June @luacmartins can you please assign another BZ person to pay. Thanks!

**Comment by luacmartins** [comment] 2023-06-07 15:16
Will do!

**Comment by luacmartins** [comment] 2023-06-09 21:23
Created Web-E PR and will start working on Auth soon.

**Comment by luacmartins** [comment] 2023-06-12 17:11
Coming back to this today

**Comment by luacmartins** [comment] 2023-06-13 20:11
This is my priority and I'm working on Web-E and Auth today

**Comment by luacmartins** [comment] 2023-06-15 21:17
Still working on this.

**Comment by luacmartins** [comment] 2023-06-19 15:23
Still working on the Auth PR.

**Comment by luacmartins** [comment] 2023-06-21 20:24
Still working on this

**Comment by luacmartins** [comment] 2023-06-23 20:34
Haven't made much progress on this because of the deploy for SHN this week. Gonna come back to it on monday.

**Comment by luacmartins** [comment] 2023-06-26 16:11
Gonna jump back on this after the deploy today.

**Comment by laurenreidexpensify** [comment] 2023-06-28 11:17
@luacmartins is there an update on this one yet? Thanks

**Comment by luacmartins** [comment] 2023-06-28 16:02
I made solid progress on Web-E and Auth yesterday and I'm currently testing the whole flow and fixing bugs. I'm hoping to have this ready for review by EOD.

**Comment by luacmartins** [comment] 2023-06-29 00:02
Feature is working on my branches. Web-E PR is ready, but I still need to add tests to Auth PR so everything can go into review. Gonna work on those tomorrow!

**Comment by luacmartins** [comment] 2023-06-29 23:31
I spent most of my day working on this today, but I'm still battling Auth tests. There are 5 failing tests now that I need to address. I'm ooo tomorrow and on Monday so I'll come back to this on Tuesday.

**Comment by laurenreidexpensify** [comment] 2023-07-03 10:51
@luacmartins is still OOO, will work on this tomorrow

**Comment by luacmartins** [comment] 2023-07-05 20:29
Made progress yesterday. I need to address 2 failing tests in Auth and then we should be good to go.

**Comment by luacmartins** [comment] 2023-07-05 23:19
Auth and Web-E PRs are in review. App is ready too but I still need to complete the checklist

**Comment by luacmartins** [comment] 2023-07-06 17:11
All PRs are in review

**Comment by laurenreidexpensify** [comment] 2023-07-19 13:05
@luacmartins looks like we're on prod? is outstanding step here to pay @0xmiroslav

**Comment by luacmartins** [comment] 2023-07-19 15:27
@laurenreidexpensify auth is in prod, web-e and app are still in review.

**Comment by laurenreidexpensify** [comment] 2023-07-31 10:25
@luacmartins can you give an update on where we are? What is still in review? Going by the deploy blocker above am guessing sometihng has been deployed now 😅

**Comment by luacmartins** [comment] 2023-07-31 17:12
Ah yes, the [final PR](https://github.com/Expensify/App/pull/19095#pullrequestreview-1469444750) was merged last Wednesday and is in staging now. I think the automation failed to update this issue. 

I also created [this issue](https://github.com/Expensify/Expensify/issues/302985) to track cleanup and any bugs that may show up.

**Comment by luacmartins** [comment] 2023-07-31 19:01
Ah there you go, seems like automation worked after all just needed to wait for it to get deployed to prod.

**Comment by laurenreidexpensify** [comment] 2023-08-07 12:14
@0xmiroslav @luacmartins please advise on regression steps above thanks

**Comment by laurenreidexpensify** [comment] 2023-08-08 16:15
Updated payment summary: 

- External issue reporter - internal issue report from @mountiny, no payment - please note that the issue [flagged here](https://expensify.slack.com/archives/C049HHMV9SM/p1684237536816689) is not the same bug as [this](https://expensify.slack.com/archives/C049HHMV9SM/p1684333335156299?thread_ts=1684333083.150029&cid=C049HHMV9SM) and was part of the parts broken as per this update
- Contributor that fixed the issue - internal engineer resolved @luacmartins, no payment
- Contributor+ that helped on the issue and/or PR - @0xmiroslav, $1000 payment issued in Upwork AND @aimane-chnaif $1000 - offer sent in Upwork

**Comment by laurenreidexpensify** [comment] 2023-08-09 14:57
Final payment summary:

External issue reporter - internal issue report from @mountiny, no payment - please note that the issue [flagged here](https://expensify.slack.com/archives/C049HHMV9SM/p1684237536816689) is not the same bug as [this](https://expensify.slack.com/archives/C049HHMV9SM/p1684333335156299?thread_ts=1684333083.150029&cid=C049HHMV9SM) and was part of the parts broken as per this update
Contributor that fixed the issue - internal engineer resolved @luacmartins, no payment
Contributor+ that helped on the issue and/or PR - @0xmiroslav, $1000 payment issued in Upwork AND @aimane-chnaif $1000 - payment issued in Upwork via new tracking issue here https://github.com/Expensify/App/issues/24277

**Comment by laurenreidexpensify** [comment] 2023-08-09 14:58
So just to confirm, we do not need to introduce any regression testing for this, as it is already covered in existing tests, correct @luacmartins @0xmiroslav ?

**Comment by luacmartins** [comment] 2023-08-09 15:58
Correct!

**Closed** 2023-08-10 09:10 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
