### ISSUE TITLE
[$250] Web - Room - Тransfer from room to workspace modal stuck for a moment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28468] opened 2023-09-29 12:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging,new.expensify.com
2.Login with a new account
3. Click on "Send Message" from FAB
4. Click on the # Room tab
5. Click on "Create a new workspace"

## Expected Result:
Тransfer from room to workspace modal flow should be smooth

## Actual Result:
Тransfer from room to workspace modal stuck for a moment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2378f8a1-95db-48e2-ba1f-1c50dbaeaf3f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013af8250fe34bf678</li>
        <li>Upwork Job ID: 1708377271789256704</li>
        <li>Last Price Increase: 2023-10-08</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-10-01 07:05
Demoting this to a normal bug, the functionality works fine and this is a specific flow seemingly not smooth only on one platform.

I think we could close this but keeping it open in case people find root cause to this specific transition issue

**Comment by CoderAbhi22454545454** [comment] 2023-10-01 10:56
Hi I have find the issue how can I reached out to you guys?

**Comment by peterdbarkerUK** [comment] 2023-10-03 22:37
not overdue

**Comment by peterdbarkerUK** [comment] 2023-10-06 13:59
Still waiting for proposals

**Closed** 2023-10-12 20:43 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
