### ISSUE TITLE
[$500] Web - Chat - Some emojis change when there is markdown in the message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32833] opened 2023-12-11 17:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with any account
2. Navigate to any chat
3. Send a message which consists of a few emojis and any markdown

## Expected Result:
Emojis should match the emojis selected when drafting the message.

## Actual Result:
Some emojis change when there is a markdown in the message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0d66d25c-afc6-49c1-b9ed-d8ded0458da0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015728063279fccae6</li>
        <li>Upwork Job ID: 1734259059703267328</li>
        <li>Last Price Increase: 2024-07-09</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-12-11 18:30
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Web - Chat - Some emojis change when there is markdown in the message

### What is the root cause of that problem?

This happens only on Windows due to the difference in the the rendering engine used on bold and normal text. Bold text uses `TRenderEngineProvider`, which uses `singleFontFamily`, and normal text uses RNText, which `multiFontFamily`.



### What changes do you think we should make in order to solve the problem?

Add `Windows Segoe UI Emoji` for Windows platform in `systemFonts` in `TRenderEngineProvider`

### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2023-12-11 23:46
@kbecciv I'm on Staging v1.4.11-6 and can't repro this.

>Some emojis change when there is a markdown in the message.

Can you define `some`? Are there specific emojis that always change? Does the change always occur?

Also, you're missing a step - there should be something like: 4. Click `Edit` to remove the * around the markdown and save the message.

**Comment by it-education-md** [comment] 2023-12-12 03:05
I can't repro this issue.

**Comment by shubham1206agra** [comment] 2023-12-12 03:06
@jliexpensify This can be repro on Windows platform only

**Comment by dragnoir** [comment] 2023-12-13 11:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Windows emojis change when there is markdown in the message.

### What is the root cause of that problem?

When there's any HTML (fragments/markdown..) on the comment, the `TextCommentFragment` will use `RenderHTMLSource` to render the comment
https://github.com/Expensify/App/blob/38b3990ce5a3823ee75ec32a56926befa592f47a/src/pages/home/report/comment/TextCommentFragment.js#L62-L74

The `TRenderEngineProvider` from `RenderHTMLSource` use `baseStyle` to render the elment inline style.
https://github.com/Expensify/App/blob/38b3990ce5a3823ee75ec32a56926befa592f47a/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js#L76-L81

Until here we have 2 issues:
- The font missing `Windows Segoe UI Emoji`, is not listed inside `systemFonts` props
- 
![image](https://github.com/Expensify/App/assets/12425932/945a650b-b0ef-4943-88cb-3cbb15edc7e3)

- The TRE will pick the first match as mentioned [here](https://meliorence.github.io/react-native-render-html/docs/content/textual#font-selection)
If we provide ⇒ `font-family: 'ExpensifyNeue-Regular, Segoe UI Emoji, Noto Color Emoji',` 
then the TRE will pick the 1st available font wih is ExpensifyNeue-Regular and will ignore the rest.

### What changes do you think we should make in order to solve the problem?

1- We need to add `Windows Segoe UI Emoji` to `systemFonts`
```js
const  emojiRenderfonts  = ['Windows Segoe UI Emoji', ..._.values(singleFontFamily)];
// rest of the code
systemFonts={emojiRenderfonts}
```

2- We need to change the baseStyle to something like
```js
baseStyle={styles.webViewStyles.RenderHTMLSourceFontStyle}
```
Where `RenderHTMLSourceFontStyle` is a new style inside src/styles/styles.ts
```js
RenderHTMLSourceFontStyle: {
	color:  theme.text,
	fontSize:  variables.fontSizeNormal,
	fontFamily:  'Windows Segoe UI Emoji',
	flex:  1,
	lineHeight:  variables.fontSizeNormalHeight,
	...writingDirection.ltr,
},
```
### POC
![image](https://github.com/Expensify/App/assets/12425932/17b3a143-58ed-4ea4-9feb-ce17a282f385)

**Comment by dragnoir** [comment] 2023-12-13 11:11
@jliexpensify here's the full list of icons: https://emojipedia.org/microsoft
Those are icons supported by Windows. Windows OS style those icons using the default `Windows Segoe UI Emoji` font (there's two styles windows10 and windows 11). Same fonts are styled in another way in other platforms.

**Comment by jliexpensify** [comment] 2023-12-14 02:40
Thanks @dragnoir - @abdulrahuman5196 we have some proposals for review now

**Comment by abdulrahuman5196** [comment] 2023-12-14 12:48
Hi, Will review today

**Comment by shubham1206agra** [comment] 2023-12-14 12:52
@abdulrahuman5196 Please hold this on https://github.com/Expensify/App/issues/31389

**Comment by jliexpensify** [comment] 2023-12-14 23:03
Thanks @shubham1206agra - have updated the title. Let us know when the other GH is resolved, cheers!

**Comment by jliexpensify** [comment] 2023-12-28 04:30
Still on hold

**Comment by jliexpensify** [comment] 2024-01-08 21:34
Still on hold

**Comment by jliexpensify** [comment] 2024-01-18 04:50
Still on hold, changed to Monthly

**Comment by jliexpensify** [comment] 2024-02-19 23:25
Still on hold

**Comment by jliexpensify** [comment] 2024-03-17 23:33
Still on hold

**Comment by jliexpensify** [comment] 2024-04-01 02:04
On hold, moved to #vsb project based on other GH

**Comment by jliexpensify** [comment] 2024-05-06 09:35
Still on hold

**Comment by mallenexpensify** [comment] 2024-06-10 20:25
Off hold, the below hit production a bit ago. 
@jliexpensify @abdulrahuman5196 , please attempt reproduction. I'ave also added `retest-weekly` 

Found this cuz I have this other emoji+markdown issue but I don't think it's directly related
- https://github.com/Expensify/App/issues/43322#issuecomment-2155557559

**Comment by jliexpensify** [comment] 2024-06-14 01:30
Hmm I can't seem to replicate this issue, all my emojis seem like they are correct:
![image](https://github.com/Expensify/App/assets/30815269/aca66b18-3034-4a29-8da9-f64bfe44fe77)

What I do notice is that the emojis start off as large in the chat viewer, but as soon as you apply the first *, they change in size. I assume that's intended?

![image](https://github.com/Expensify/App/assets/30815269/f79a1127-85f7-4b53-bc06-f901e8991325)

goes to

![image](https://github.com/Expensify/App/assets/30815269/edf53c39-7be0-456c-a914-bfb0c5b96fd9)

**Comment by jliexpensify** [comment] 2024-06-19 03:22
Not overdue, waiting for @kbecciv to re-test/Applause to re-test weekly.

**Comment by jliexpensify** [comment] 2024-06-24 03:52
Not overdue, waiting for a retest from Applause.

**Comment by jliexpensify** [comment] 2024-07-03 05:14
Waiting for a retest

**Comment by mvtglobally** [comment] 2024-07-03 14:51
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-07-11 03:53
Issue not reproducible during KI retests. (Second week)

**Comment by jliexpensify** [comment] 2024-07-11 03:59
Closing!

**Closed by jliexpensify** 2024-07-11 03:59 UTC
Labels: External, Weekly, Help Wanted, Bug, retest-weekly
