### ISSUE TITLE
[Feature] Desktop needed 3 updates to get to most recent version 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9091] opened 2022-05-19 05:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Saw there was a new version of desktop
2. Clicked Update New Expensify
3. App updated to Version 1.1.60-3

## Expected Result:
App to update to most recent version.

## Actual Result:
Had to follow below steps to get to latest version
Clicked Update New Expensify
App updated to Version 1.1.61-0
Clicked Update New Expensify
App Updated to Version 1.1.61-2 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.63-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screen Shot 2022-05-19 at 1 14 23 AM](https://user-images.githubusercontent.com/43995119/169213871-cb6b6dcc-a56a-4086-8f07-3f2d6fdb146b.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652728059909569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-05-25 01:02
Unsure sure if `External` engineers are able to test this updating flow as they would need to trigger a new deploy? Gonna leave it as `Internal` for someone to investigate.

**Comment by mallenexpensify** [comment] 2022-05-31 17:25
Happened again this morn. Version 1.1.69-2 (1.1.69-2) then showed there was another update available to Version 1.1.70-1 (1.1.70-1)

**Comment by mallenexpensify** [comment] 2022-09-05 23:37
Reopening cuz some version of this has happened to me the past few weeks.  I'll _try_ to not update the app for a couple days then see if I can get repro steps

**Comment by puneetlath** [comment] 2022-10-19 14:20
I think I would consider this a new feature. It's not a bug per-se. So I'm going to make it a weekly new feature and unassign.

**Comment by JmillsExpensify** [comment] 2022-10-19 23:31
I think that if no one is going to assign themselves to this issue, we should just close it. Doing that now, so for anyone that wants to re-open please assign yourself.

**Closed by JmillsExpensify** 2022-10-19 23:31 UTC
Labels: Engineering, Weekly, Internal, NewFeature

**Comment by mallenexpensify** [comment] 2022-10-20 20:10
I don't think it's the highest priority but I think, on a quality scale, I'd consider an app lower quality if it didn't update to the most recent version when I clicked to update it.  That said.. most people will be on web and mobile for a while. And.. we can reopen if/when needed.
