### ISSUE TITLE
[Hold for payment: 2024-09-20] [$250] Track expense - Clicking back navigates user back to the share with my accountant flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45774] opened 2024-07-19 13:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to your chat and create a track expense
3. Click on "Share with my accountant" on the actionable whisper for the track expense
4. Go with the flow until the end
5. Click on the browser back button

## Expected Result:
App should navigate user back to the previously opened chat report

## Actual Result:
App navigates user back to the "Share with my accountant" flow and user can go through the previously done flow again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/87e6a369-1fdc-4cd0-a55e-2dac469c459d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b38481aa14324c79</li>
        <li>Upwork Job ID: 1815753645056507384</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103784904</li>
<li>shubham1206agra | Contributor | 103784908</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by lanitochka17** [comment] 2024-07-19 13:24
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-07-19 13:25
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by c3024** [comment] 2024-07-22 14:28
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Clicking back on clicking the browser back button after completing the Share with my accountant flow opens the Share with accountant flow RHP
### What is the root cause of that problem?
When we complete the share to my accountant flow, we open the invite members page here
https://github.com/Expensify/App/blob/c2ded1dc91252803795948fa97888e420b0e648f/src/libs/actions/IOU.ts#L3807-L3811
but we cannot ensure this exact order of dismissing modal and then opening the invite room page. This must be causing a mismatch between device history and the navigation state.

So, when we click back at the invite page (or after completing inviting a member) the navigation state does not change as expected.

This is how the navigation state changes when clicking back on the invite page (this will be similar in the flow after completing inviting a member as well)

![Screenshot 2024-07-22 at 7 48 15 PM](https://github.com/user-attachments/assets/a46582a4-1bcb-4493-9de5-7a1850c0e83c)

When we click back it removes the RHP and a report (WS chat here) and adds a RHP. The correct thing to happen here is to only remove the RHP and add the invite room RHP.

I think this is due to browser history mismatch with the navigation state because we cannot ensure the dismissModal and navigate order actions correctly in the trackExpense flow.

### What changes do you think we should make in order to solve the problem?
I think we should have a promise based dismissModal for situations like these. We can add a state listener to identify state change of dismissModal action and resolve the promise after the dismissModal navigation is complete.

Here is the [sample test branch](https://github.com/c3024/App/tree/dismissModalPromise) with detailed changes.
### What alternative solutions did you explore? (Optional)

**Comment by dylanexpensify** [comment] 2024-07-23 14:19
reviewed

**Comment by Zakpak0** [comment] 2024-07-24 04:36
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

When using the browser's back button to navigate after sharing an expense there share modal needs to be closed.

### What is the root cause of that problem?

There is no action being made to close the modal after sharing the expense and navigating to the next page.

What changes do you think we should make in order to solve the problem?

We can dismiss the share modal before we navigate so it does not appear in our history.
[src/libs/actions/IOU.ts](https://github.com/Expensify/App/blob/main/src/libs/actions/IOU.ts#L3834-L3836)
```typescript
    if (action === CONST.IOU.ACTION.SHARE) {
            Navigation.dismissModal(linkedTrackedExpenseReportID ?? "-1")
            Navigation.navigate(ROUTES.ROOM_INVITE.getRoute(activeReportID ?? '-1', CONST.IOU.SHARE.ROLE.ACCOUNTANT));
    }
```

Additionally I noticed the same issue with the "Invite to workspace" modal. It will cause the same problem so we should dismiss that as well.
[src/pages/RoomInvitePage.tsx](https://github.com/Expensify/App/blob/main/src/pages/RoomInvitePage.tsx#L194)
```typescript
        Navigation.dismissModal(reportID ?? "-1")
        Navigation.navigate(backRoute);
```

[Here](https://github.com/Zakpak0/Expensify-App-Fork/tree/zakpak0/bugfix-issue-%2345774) is a test branch with my changes

### What alternative solutions did you explore? (Optional)
N/A

**Comment by c3024** [comment] 2024-07-24 08:26
Thanks for your proposal @Zakpak0 .

When the right hand panel opens with the Invite Page, the Centre Pane should show the workspace chat. I tested your branch. It shows the selfDM chat in the Center Pane when the Invite Page appears in the `Share to accountant` flow.

Could you fix that?

**Comment by c3024** [comment] 2024-07-24 10:23
Browser back button on Invite Page in Right Hand Panel (RHP) takes the user to Share RHP with the latest branch. This should not happen.


https://github.com/user-attachments/assets/c5849b75-350c-4404-8dae-47caf84d0164

**Comment by Zakpak0** [comment] 2024-07-24 12:32
## Proposal

[Updated](https://github.com/Expensify/App/issues/45774#issuecomment-2246850857)
@c3024  I updated it so that it handles pressing back from the RHM back button.
One thing I noticed though was that you must directly navigate to the workspace before you can handle the navigation to the RHP invite overlay.
This RHP navigation route being independent of the report we have open seems to be intentional?
Another thing is we must wait for the navigation state to be updated before we move on to our next navigation command.
Otherwise we won't be editing the state correctly. 

https://github.com/user-attachments/assets/1a96c67b-f054-4d25-a369-0446b7ca16d8

**Comment by c3024** [comment] 2024-07-30 13:16
@Zakpak0 That branch works, but it seems more like a workaround to delay navigation to the room invite page. Navigation is ready all the time in this case. `isNavigationReady` is always `true` once the `NavigationContainer` is mounted. So, checking if it is ready only delays the navigation to the invite page slightly because it’s being done in the `.then` chained to the `isNavigationReady` promise.

I think the current bug is due to navigating to the room invite page before `dismissModal` is fully complete. We need something like a `dismissModalWithPromise`, as seen in this [branch](https://github.com/c3024/App/tree/dismissModalPromise), to ensure that navigation to the room invite page happens only after `dismissModal` is fully complete. This also allows for reuse of this new function in other cases where navigation might occur before `dismissModal` is complete.

**Comment by Zakpak0** [comment] 2024-08-01 04:30
@c3024 thanks, this makes a lot of sense. I'm going to check this out right now!

**Comment by c3024** [comment] 2024-08-03 05:37
Waiting for proposals.

**Comment by c3024** [comment] 2024-08-07 07:43
Waiting for proposals!

**Comment by c3024** [comment] 2024-08-13 08:03
Waiting for proposals.

**Comment by c3024** [comment] 2024-08-17 02:35
Waiting for proposals!

**Comment by wildan-m** [comment] 2024-08-27 07:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When perform Track expense clicking back navigates user back to the share with my accountant flow

### What is the root cause of that problem?

The activeReportID in this code points to the destination report, not the previous one.

https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/libs/actions/IOU.ts#L3815

### What changes do you think we should make in order to solve the problem?
I think share actions will only occur in selfDM. If that's the case, using linkedTrackedExpenseReportID is appropriate. Another option is to use ReportUtils.findSelfDMReportID() or include a new optional parameter prevActiveReportID in trackExpense report.

Change:

https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/libs/actions/IOU.ts#L3815-L3819

To
```tsx
    const isShareAction = action === CONST.IOU.ACTION.SHARE;
    const modalReportID = isShareAction ? linkedTrackedExpenseReportID : (isSearchTopmostCentralPane() ? undefined : activeReportID);
    
    Navigation.dismissModal(modalReportID);
    
    if (isShareAction) {
        const inviteRoute = ROUTES.ROOM_INVITE.getRoute(activeReportID ?? '-1', CONST.IOU.SHARE.ROLE.ACCOUNTANT);
        Navigation.navigate(inviteRoute);
    }    

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by WojtekBoman** [comment] 2024-08-27 09:54
We should wrap the navigation action with ` Navigation.setNavigationActionToMicrotaskQueue`:

```tsx
    Navigation.dismissModal(isSearchTopmostCentralPane() ? undefined : activeReportID);
    if (action === CONST.IOU.ACTION.SHARE) {
        Navigation.setNavigationActionToMicrotaskQueue(() => Navigation.navigate(ROUTES.ROOM_INVITE.getRoute(activeReportID ?? '-1', CONST.IOU.SHARE.ROLE.ACCOUNTANT)));
    }

```
Thanks to this, we will be sure that the first modal has already been closed and we can perform the next navigation action.

Here's the video with the fixed version:

https://github.com/user-attachments/assets/b2cedb6e-1360-4bf0-9447-ef6509a0a09f

**Comment by c3024** [comment] 2024-08-29 00:19
I'll update.

**Comment by c3024** [comment] 2024-08-31 13:11
I am not sure if the task queued in the microtask queue always gets executed after the dismiss modal action is complete. The dismiss modal action might take a bit longer, and since the navigate action is in a different promise chain, it might get executed earlier.

Ideally, we should chain the navigate action to a dismiss modal action function returning a promise, like [this](https://github.com/c3024/App/blob/ead165430f6906e5e7bbae39e2c548b78d4d2837/src/libs/Navigation/dismissModalWithReport.ts#L133-L152).

However, in practice, the delay caused by adding the `navigate` action to the microtask queue seems to be sufficient for the dismiss modal action to complete. Therefore, the added verbosity and complexity of creating another dismissModal function that returns a promise might to be worth it.

@WojtekBoman and @shubham1206agra's proposals [here](https://github.com/Expensify/App/issues/45774#issuecomment-2312076067) and [here](https://github.com/Expensify/App/issues/45774#issuecomment-2312330173) LGTM!

🎀 👀 🎀 C+ Reviewed

**Comment by cead22** [comment] 2024-09-02 16:03
> @WojtekBoman and @shubham1206agra's proposals [here](https://github.com/Expensify/App/issues/45774#issuecomment-2312076067) and [here](https://github.com/Expensify/App/issues/45774#issuecomment-2312330173) LGTM!

@c3024 sorry, can you clarify which one you selecte?

**Comment by c3024** [comment] 2024-09-02 16:09
Both proposals are the same. @WojtekBoman is an expert agency member. I think @shubham1206agra asked him for the fix for this on Slack [here](https://github.com/Expensify/App/issues/45774#issuecomment-2312335232) and he posted a proposal in the standard format with the same solution. So, I guess Shubham will work on it if he is assigned.

**Comment by c3024** [comment] 2024-09-14 09:37
Automation failed here. Deployed to production on 13-Sep. Should be on `HOLD` for payment till 20-Sep or 21-Sep.

cc: @dylanexpensify

**Comment by dylanexpensify** [comment] 2024-09-18 10:42
Payment summary:

Contributor: @shubham1206agra $250 
Contributor+: @c3024 $250

Please apply/request!

**Comment by c3024** [comment] 2024-09-23 15:20
Gentle bump for payment @dylanexpensify

**Comment by dylanexpensify** [comment] 2024-09-23 17:56
done!

**Closed by dylanexpensify** 2024-09-23 17:56 UTC
Labels: Reviewing, External, Weekly, Bug
