### ISSUE TITLE
Web - Task Completion Discrepancy: Check Mark Not Displayed for completed Tasks in Incognito Mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22092] opened 2023-07-02 23:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to the app with User A.
2. Create a room and set it to public mode.
3. Assign a task from within the room: Add title, description, choose any assignee and verify if the newly created room is selected by default.
4. Mark the assigned task as complete from User A.
5. Verify the presence of a check mark indicating task completion within the room.
6. Go to details > share code and copy the link
7. Open the shared room code link in incognito mode
8. Locate the assigned task within the room and verify if you can see the check mark

## Expected Result:
The assigned task in the room should display a check mark indicating task completion for all users, including those accessing the room via incognito mode. Incognito mode represents new first time possible users.

## Actual Result:
In incognito mode, the assigned task does not display a check mark, even though it is marked as complete by User A. The absence of the check mark creates a discrepancy in task completion visibility between regular and incognito user sessions

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5.
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/351c2b21-e722-4bf8-b864-7be40b610294

https://github.com/Expensify/App/assets/93399543/9942d102-3163-4f18-a603-0fc1da69ebbe

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688255339915979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by crystal6117** [comment] 2023-07-03 03:23
Hello, @kbecciv Will you let me know how create a new room? Unfortunately there is no menu "New Room" in my account.
![Screenshot 2023-07-02 at 10 23 20 PM](https://github.com/Expensify/App/assets/55975468/aef46285-53cb-4fd0-91ae-27c51319a10f)

**Comment by manjesh-yadav** [comment] 2023-07-03 07:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task Completion Discrepancy: Check Mark Not Displayed for completed Tasks in Incognito Mode
### What is the root cause of that problem?

In src/components/ReportActionItem/TaskPreview.js we set default props as empty Object ({})

This is cause problems to check `tastkReport` available or not for variable `isTaskCompleted`

```Js
const defaultProps = {
    taskReport: {},
    isHovered: false,
};
```

```Js
const isTaskCompleted = props.taskReport
        ? props.taskReport.stateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.taskReport.statusNum === CONST.REPORT.STATUS.APPROVED
        : props.action.childStateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.action.childStatusNum === CONST.REPORT.STATUS.APPROVED;
```



### What changes do you think we should make in order to solve the problem?

We should also check for empty {} like  `!_.isEmpty(props.taskReport)`

```JS
const isTaskCompleted = props.taskReport && !_.isEmpty(props.taskReport)
        ? props.taskReport.stateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.taskReport.statusNum === CONST.REPORT.STATUS.APPROVED
        : props.action.childStateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.action.childStatusNum === CONST.REPORT.STATUS.APPROVED;
```

**Comment by flaviadefaria** [comment] 2023-07-03 19:37
Indeed that looks like a dupe so closing this.

**Closed by flaviadefaria** 2023-07-03 19:37 UTC
Labels: Daily, Bug
