### ISSUE TITLE
[HOLD for payment 2024-04-05] App crashes trying to render QAB

### ISSUE THREAD

**Issue by rafecolton** [Expensify/App#38972] opened 2024-03-26 00:26 UTC
Introduced in https://github.com/Expensify/App/pull/38669

cc @Gonals @marcaaron 

**Version Number:** Tested on `main@1b0fe6d2ee`
**Reproducible in staging?:** 
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** me
**Slack conversation:** https://expensify.slack.com/archives/C03TQ48KC/p1711407644753289 (Expensify internal)

## Action Performed:
Break down in numbered steps
1. Create a new chat from one new user to another new user
2. App crashes

## Expected Result:
App doesn't crash

## Actual Result:
App crashes due to empty string being passed to `translate()`

![Screenshot 2024-03-25 at 4 00 55 PM](https://github.com/Expensify/App/assets/1058475/467700df-7d06-48ee-ae9a-e5acd505064e)

There's also a proptypes warning which is likely due to the wrong type being passed from the API

![Screenshot 2024-03-25 at 3 58 57 PM](https://github.com/Expensify/App/assets/1058475/2df5c3e9-c948-4f8b-8f62-8c678825f7ab)

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rafecolton** [comment] 2024-04-04 16:57
Hi @paultsimura, I'm new to working with contributors, so asked in Slack [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1712249837969799) (internal) to confirm the process. Thanks for your patience.

**Comment by rafecolton** [comment] 2024-04-04 18:55
Assigned! Added @Christinadobrzyn yo handle payment

**Comment by Christinadobrzyn** [comment] 2024-04-05 00:22
Payouts due:

- [ ] Contributor+: $500 @paultsimura (Upwork offer - https://www.upwork.com/nx/wm/offer/101740503)

Upwork job is [here](https://www.upwork.com/jobs/~011031b16797ff1cf2)

@paultsimura can you accept the upwork offer? Thanks!

**Comment by Christinadobrzyn** [comment] 2024-04-05 04:20
Awesome! I paid this out based on this [payment summary](https://github.com/Expensify/App/issues/38972#issuecomment-2038489452). 

Closing this our since there's no regression test.

**Closed by Christinadobrzyn** 2024-04-05 04:20 UTC
Labels: Weekly, Awaiting Payment, Bug
