### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Search - Transaction report shows multiline title for expense with multiline description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41584] opened 2024-05-03 14:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense
3. Submit an expense containing multiline description and no merchant
4. Click on the search icon
5. If the transaction report does not show up in Search list, go to transaction thread and edit the description while maintaining multiline format

## Expected Result:
The transaction report in search list will show single line title

## Actual Result:
The transaction report in search list shows multiline title

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2d457c02-a1d3-403b-8bad-7d31bc0d66a0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01765f6dc12ad2c849</li>
        <li>Upwork Job ID: 1793043171906035712</li>
        <li>Last Price Increase: 2024-05-21</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 102449287</li>
<li>nkdengineer | Contributor | 102449290</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by lanitochka17** [comment] 2024-05-03 14:35
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-03 14:35
We think that this bug might be related to #vip-vsp

**Comment by nkdengineer** [comment] 2024-05-04 04:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The transaction report in search list shows multiline title

### What is the root cause of that problem?
In `HeaderView` or LHN, we use `DisplayNames` component to show to report name and it used `ReportUtils.formatReportLastMessageText` function to replace all break line to space character.


https://github.com/Expensify/App/blob/2f5173c9c0f041967acfbdf9581ce52327623fa6/src/components/DisplayNames/DisplayNamesWithTooltip.tsx#L59

But in `UserListItem`, we don't do this so the bug happens in the finder page.
https://github.com/Expensify/App/blob/2f5173c9c0f041967acfbdf9581ce52327623fa6/src/components/SelectionList/UserListItem.tsx#L122
### What changes do you think we should make in order to solve the problem?
We should do the same way as we do [here](https://github.com/Expensify/App/blob/2f5173c9c0f041967acfbdf9581ce52327623fa6/src/components/DisplayNames/DisplayNamesWithTooltip.tsx#L59
) to replace all line break when display the title of  `UserListItem`

```
text={ReportUtils.formatReportLastMessageText(Str.removeSMSDomain(item.text ?? ''))}
```
https://github.com/Expensify/App/blob/2f5173c9c0f041967acfbdf9581ce52327623fa6/src/components/SelectionList/UserListItem.tsx#L122



### What alternative solutions did you explore? (Optional)
NA

**Comment by kevinksullivan** [comment] 2024-05-08 18:55
Hm I am not experiencing this error @lanitochka17 . The search result shows as one line, even when I Am I misunderstanding?


<img width="380" alt="image" src="https://github.com/Expensify/App/assets/22508290/13064397-2ec5-4689-b9d0-f85c5aef7c71">

<img width="1282" alt="image" src="https://github.com/Expensify/App/assets/22508290/6c63cba2-4372-4223-99e0-eb79b3e75ecd">

**Comment by lanitochka17** [comment] 2024-05-10 14:53
@kevinksullivan Need to create two transactions.

https://github.com/Expensify/App/assets/78819774/66b21a26-4a15-4119-b3ee-7b196398e682

**Comment by shawnborton** [comment] 2024-05-21 11:57
Friendly bump on this one.

**Comment by kevinksullivan** [comment] 2024-05-21 22:16
Thanks for clarifying @lanitochka17 . Can you update the original post with the correct steps? It didn't mention creating another transaction. I'll move this forward in the meantime!

**Comment by DylanDylann** [comment] 2024-05-22 09:47
@nkdengineer Your proposal looks promising, but I think we should format the report name in `getReportName` function because we always want to shorten the report name to a fixed length and trim spaces the report name in every place

**Comment by nkdengineer** [comment] 2024-05-22 10:18
@DylanDylann Thanks for your feedback, I updated alternative solution to format the report name in `getReportName` function https://github.com/Expensify/App/issues/41584#issuecomment-2094002682.

**Comment by DylanDylann** [comment] 2024-05-23 04:29
Let's go with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/41584#issuecomment-2094002682)

🎀 👀 🎀 C+ reviewed

**Comment by nkdengineer** [comment] 2024-05-27 09:23
@DylanDylann  this [PR](https://github.com/Expensify/App/pull/42631) is ready for preview

**Comment by DylanDylann** [comment] 2024-06-17 06:42
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **No**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

I think this is minor, we don't need to create a regression test for this bug


Do we agree 👍 or 👎

**Comment by cristipaval** [comment] 2024-06-17 11:49
This issue is on @kevinksullivan now.

**Comment by kevinksullivan** [comment] 2024-06-17 18:17
payments made!

**Closed by kevinksullivan** 2024-06-17 18:17 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
