### ISSUE TITLE
[$250] Integrations - Preferred exporter check-mark is missing before manual change

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46675] opened 2024-08-01 16:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4785182
**Email or phone of affected tester (no customers):** applausetester+82pronin@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a new workspace
3. Go to workspace settings > "More Features" > Enable the "Accounting" toggle
4. Go to Accounting > Connect QBO
5. Add one more admin to Workspace
6. Go to Export
7. Observe there is an email displayed under Preferred exporter
8. Click Preferred exporter

## Expected Result:
Preferred exporter email should have a checkmark

## Actual Result:
Preferred exporter check-mark is missing until manually selected. However preferred email is displayed on Export page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a87f4de3-e653-4546-946d-4dcc3b326669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101fae98e11baef98</li>
        <li>Upwork Job ID: 1819087142058065734</li>
        <li>Last Price Increase: 2024-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103495929</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-08-01 16:47
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-08-02 06:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Preferred exporter check-mark is missing until manually selected. However preferred email is displayed on Export page

### What is the root cause of that problem?
After we connect to QBO, `exportConfiguration?.exporter` is `undefined` so no option is selected here

https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/pages/workspace/accounting/qbo/export/QuickbooksPreferredExporterConfigurationPage.tsx#L48

But we fall back to the policy's owner here
https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/pages/workspace/accounting/qbo/export/QuickbooksExportConfigurationPage.tsx#L42

### What changes do you think we should make in order to solve the problem?
We should update the condition `isSelected` here to select the policy owner if `exportConfiguration?.exporter` is not available

```
isSelected: (exportConfiguration?.exporter ?? policy?.owner) === exporter.email,
```

https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/pages/workspace/accounting/qbo/export/QuickbooksPreferredExporterConfigurationPage.tsx#L48
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-08-02 06:47
### Updated [proposal](https://github.com/Expensify/App/issues/46675#issuecomment-2264665973)

- Add the fix for other integrations

**Comment by hungvu193** [comment] 2024-08-02 09:11
I can't seem to reproduce this issue 🤔 

https://github.com/user-attachments/assets/5f0ae3c9-7939-41a7-8343-37c476e8f0ca

**Comment by hungvu193** [comment] 2024-08-02 10:14
Ok, I can reproduce in latest main. Reviewing shortly 😄

**Comment by hungvu193** [comment] 2024-08-02 10:40
Thanks for the proposals everyone. That's straightforward changes and minor improvements can be addressed during PR's review process. @ShridharGoel 's [proposal](https://github.com/Expensify/App/issues/46675#issuecomment-2263869170) looks good to me!

🎀 👀 🎀  C+ reviewed

**Comment by nkdengineer** [comment] 2024-08-02 10:43
@hungvu193 This condition from the selected proposal isn't correct which will make the policy owner always selected even though another exporter is selected.

```
isSelected: exportConfiguration?.exporter === exporter.email || exporter.email === policy?.owner,
```

**Comment by hungvu193** [comment] 2024-08-02 10:55
> @hungvu193 This condition from the selected proposal isn't correct which will make the policy owner always selected even though another exporter is selected.
> 
> ```
> isSelected: exportConfiguration?.exporter === exporter.email || exporter.email === policy?.owner,
> ```

@nkdengineer  My bad. Yeah, you're correct. Thanks for pointing it out.
@ShridharGoel Your updated proposal is now a dupe of @nkdengineer proposal.


I updated my [review here](https://github.com/Expensify/App/issues/46675#issuecomment-2265088655). Sorry for this confusion.

**Comment by nkdengineer** [comment] 2024-08-02 10:55
@hungvu193 Can you please check again? My proposal is the first proposal that has the correct solution.

**Comment by hungvu193** [comment] 2024-08-02 11:15
> We can avoid showing policy owner on the export page.

We have already confirmed this while working on the QBO and Xero projects. (I worked on them). So I don't think need to confirm from the team.

**Comment by hungvu193** [comment] 2024-08-06 00:21
Little bump @grgia

**Comment by hungvu193** [comment] 2024-08-08 02:45
Still waiting for the assignment.

**Comment by mallenexpensify** [comment] 2024-08-12 17:37
@grgia 👀 above plz

**Comment by grgia** [comment] 2024-08-12 17:57
@hungvu193 let me know if you need anything else

**Comment by nkdengineer** [comment] 2024-08-13 09:46
@hungvu193 this [PR](https://github.com/Expensify/App/pull/47290) is ready for review

**Comment by trjExpensify** [comment] 2024-08-29 23:50
Deployed to prod on the 19th, @mallenexpensify.

**Comment by mallenexpensify** [comment] 2024-08-30 22:52
Contributor: @nkdengineer paid $250 via Upwork 
Contributor+: @hungvu193 owed $250 via NewDot

@hungvu193 plz complete the BZ checklist. 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by hungvu193** [comment] 2024-08-31 04:46
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/39191
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/d140a2a4d939cce101f43ed069aedf63607ffcd7#r146055805
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug: Yes

**Regression test**:
1. Login with any account.
2. Go to workspace settings > "More Features" > Enable the "Accounting" toggle
3. Go to Accounting > Connect QBO
4. Add one more admin to Workspace
5. Go to Export => Preferred Exporter.
6. Verify that your email has a checkmark, and you are able to change Preferred Exporter successfully.

Do we 👍  or 👎  ?

**Comment by garrettmknight** [comment] 2024-08-31 12:47
$250 approved for @hungvu193

**Comment by lschurr** [comment] 2024-09-02 21:13
Added the regression test. Looks like the payment summary is complete.

**Closed by lschurr** 2024-09-02 21:13 UTC
Labels: External, Daily, Overdue, Awaiting Payment
