### ISSUE TITLE
Notification on iOS from Chronos is showing it's from me

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13263] opened 2022-12-02 02:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Send 10am to Chronos
2. Chronos replied, got notification on iOS
3. Shows from me, not Chronos

## Expected Result:
Notification shows from Chronos

## Actual Result:
Shows from me

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.32-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="713" alt="image (1)" src="https://user-images.githubusercontent.com/43996225/205202026-925f8f37-49bc-43ed-93e1-4b4e48f655cd.png">
![IMG_8313](https://user-images.githubusercontent.com/43996225/205202029-de5b7aa6-ff30-4eec-a4b2-805ae5378eb6.jpg)
![IMG_9491](https://user-images.githubusercontent.com/43996225/205202030-62bd14a6-d386-4f24-8e1b-1e75635b2e0f.PNG)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665170409741649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sketchydroide** [comment] 2022-12-05 10:36
will work on it at some point this week, might start today

**Comment by sketchydroide** [comment] 2022-12-05 15:50
I don't think this is reproducible anymore, it was in the morning, but I can't see it again

**Comment by sketchydroide** [comment] 2022-12-05 15:52
@kavimuru can you check if this still happens, I was able to reproduce in the morning, but after the latest update I can't anymore

**Comment by sketchydroide** [comment] 2022-12-07 10:48
still happening, just happened again to me
![IMG_7B69C45F5FFD-1](https://user-images.githubusercontent.com/242568/206158952-6734b062-146e-4ada-ac27-90b7bf9754e1.jpeg)

Not sure if related but it happened on the first update.
The Second message had the correct na
![IMG_ED535F6A8E76-1](https://user-images.githubusercontent.com/242568/206159420-a88ed7a8-d512-4038-aae1-bd877a2fbffb.jpeg)
me

**Comment by kavimuru** [comment] 2022-12-09 02:58
@sketchydroide I am not receiving notification in iOS now. Will check if I could reproduce.

**Comment by sketchydroide** [comment] 2022-12-09 10:53
no problem, once that is working again we can try again

**Comment by sketchydroide** [comment] 2022-12-12 09:38
can only look at this when iOS app is working and Notificatiosn are working as well

**Comment by sketchydroide** [comment] 2022-12-15 12:17
did not manage yesterday, will try to work on it today

**Comment by sketchydroide** [comment] 2022-12-16 11:13
I think I won't be able to do it today, probably next week

**Comment by sketchydroide** [comment] 2022-12-19 11:12
Ok I can probably look at this tomorrow

**Comment by sketchydroide** [comment] 2022-12-20 14:37
can check this again today

**Comment by sketchydroide** [comment] 2022-12-22 16:39
moving to next week, tbh not sure if this sould be a daily, it only affects us, but will leave it like that for now.

**Comment by JmillsExpensify** [comment] 2022-12-26 21:59
Given that this only affects us, and no user would ever experience this in production, I'm adding a `[HOLD WAQ]` to this issue. WAQ is about fixing any possible but that users encounter using our app, and again, this one is just us. Feel free to keep working on it regardless.

**Comment by sketchydroide** [comment] 2022-12-27 10:12
moving to weekly then

**Comment by sketchydroide** [comment] 2023-01-05 10:47
Have had not had the time for this, not even sure if it's still a problem, I have not had this happen to me again.

**Comment by sketchydroide** [comment] 2023-01-18 13:16
will try to work on it this week

**Comment by JmillsExpensify** [comment] 2023-01-18 16:49
Oh interesting. I just noticed that there isn't a BZ member assigned to this issue. I'll go ahead and add myself and test.

**Comment by JmillsExpensify** [comment] 2023-01-18 16:50
I was able to reproduce this two weeks ago, but I'm unable to reproduce now. It's possible that it was fixed in the most recent round of reliable notifications PRs. Either way, adding the needs reproduction label and closing.

**Comment by JmillsExpensify** [comment] 2023-01-18 16:51
@sketchydroide Feel free to try again and see if you're able to.

**Closed by JmillsExpensify** 2023-01-18 16:50 UTC
Labels: Weekly, Internal, Bug

**Comment by sketchydroide** [comment] 2023-01-18 17:19
I was already unable to reproduce, so happy to have this closed
