### ISSUE TITLE
 Chat - Deleted whitespace is added again in the composer for native emojis

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41453] opened 2024-05-01 20:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4533081&group_by=cases:section_id&group_id=292106&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open any chat
2. Right click on the compose and select "Emoji"
3. Select a native emoji
4. Click in the composer and delete the whitespace after the emoji

## Expected Result:
Deleted whitespace shouldn't appear again

## Actual Result:
Deleted whitespace is added again in the composer for native emojis

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6229db0d-2ba1-4980-a6ba-eaf764320d63

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-01 20:47
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-01 20:47
We think that this bug might be related to #vip-vsp

**Comment by joekaufmanexpensify** [comment] 2024-05-02 13:20
I can't reproduce on my end. Closing for now as this is not consistently reproducible.

**Closed by joekaufmanexpensify** 2024-05-02 13:20 UTC
Labels: Daily, Bug
