### ISSUE TITLE
Chat - New message overlaps edited tag to a quote

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25678] opened 2023-08-22 13:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to http://staging.new.expensify.com/
and log in
2. Open any chat
3. Send a quote
4. Send a new message
5. Edit the quote

## Expected Result:
There is enough space between the new message and the "Edited" tag

## Actual Result:
The new message overlaps the "Edited" tag

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b6dfcded-ef3b-4814-bce0-815416851af7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by daordonez11** [comment] 2023-08-22 15:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
edited message is overlapping with the next message in the chat if a quote is used

### What is the root cause of that problem?
Due to this [PR](https://github.com/Expensify/App/pull/24235/files) in `BaseHTMLEngineProvider` `defaultViewProps` now have `styles.w100, styles.h100` which are causing the issue of the `blockquote` element specifically height 100%

### What changes do you think we should make in order to solve the problem?
I think there might be more issues since this is used by the `RenderHTMLSource` but this is the first visible so there are two ways of solving it:
1. remove from defaultViewProps h100 and w100 and include it in the specific element required using `webViewStyles.tagStyles`
2. In the `webViewStyles.tagStyles.blockquote` element we can override height to avoid the issue.
I'm inclined to using solution #1 but it would require help from the author of the display receipts in chat to avoid any side effect in the implementation.

### What alternative solutions did you explore? (Optional)

cc @Li357 @mountiny This is fixed with https://github.com/Expensify/App/pull/25691

Sorry posted in wrong issue

**Comment by dangrous** [comment] 2023-08-23 18:12
This is confirmed to be fixed on staging, I'm going to close it out.

**Closed by dangrous** 2023-08-23 18:12 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Daily
