### ISSUE TITLE
[$250] Some emoji tooltips have empty content and name.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50729] opened 2024-10-14 15:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728903816467859

## Action Performed:
Precondition:  Go to https://www.copyandpasteemojiart.com/?m=1 copy the emoji
1. Go to staging.new.expensify.com
2. Paste the copied emoji into composer.
3. Send the message
4. Hover on the emojis.
5. Observe the tooltip content.
## Expected Result:
Tooltip content is not empty.
## Actual Result:
Tooltip content is empty.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/782c26aa-ddec-4f7b-aa72-b930d0a8e202

https://github.com/user-attachments/assets/d92c5591-fff4-4c8a-b181-2be48d5aa627

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846688054401470306</li>
        <li>Upwork Job ID: 1846688054401470306</li>
        <li>Last Price Increase: 2024-10-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by Shahidullah-Muffakir** [comment] 2024-10-14 16:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip is not showing content for some emojis, appearing blank instead.

### What is the root cause of that problem?

1. The issue occurs with both external and existing app emojis.
2. It also happens with emojis selected from the emoji picker.
3. The tooltip's background color matches some emoji colors(like the emoji show in the OP), making them invisible.
4. For emojis that do not have associated names, we display only the emoji itself in the tooltip, with the name formatted as **::**. This behavior is consistent for external emojis that also lack names, and it is functioning as expected without any issues.

### What changes do you think we should make in order to solve the problem?
We have two options to solve this issue:
1: Change the background color of the tooltip
Modify the tooltip's background color to ensure contrast with all emoji colors.
2: Add text shadow to the tooltip content
Apply a text shadow that creates an outline effect, ensuring visibility on any background.
Here:
https://github.com/Expensify/App/blob/8ab4792e28190cf13bb37c12b05b5d8f4c25649b/src/components/EmojiWithTooltip/index.tsx#L34
as:
`        <Tooltip wrapperStyle={{backgroundColor:'red'}} renderTooltipContent={emojiTooltipContent}>
`

For testing I added Red as bg colour:

https://github.com/user-attachments/assets/753c5dea-2af9-48ab-b9ea-c512ca8cea0f

**Comment by trjExpensify** [comment] 2024-10-16 23:01
@Expensify/design whatcha' want to do here? Seems like the tooltip bg colour is whitewashing some emojis. 🤷

**Comment by dubielzyk-expensify** [comment] 2024-10-17 02:29
I don't think this is really an issue cause this thing we're copying isn't in the standard emoji set. This is almost acting like a unicode character or something. Feels like a huge edge case. The actual emoji equivalent that people use via their emoji picker is `:cloud:` ☁️  which doesn't have any issues when following the steps:
![CleanShot 2024-10-17 at 12 24 55@2x](https://github.com/user-attachments/assets/942979a4-3898-41ed-944e-bb8d5f5d5606)

The way Slack deals with this is actually converting the character into the emoji. You can try it by pasting the same emoji in Slack and sending it:
![CleanShot 2024-10-17 at 12 28 17](https://github.com/user-attachments/assets/058e909f-f75e-4ea6-ac83-464aae75ff8d)

Is the text color for the emoji in the popover set to be the dark? 

Unless we can do something similar, I'd vote to do nothing.

**Comment by dubielzyk-expensify** [comment] 2024-10-17 04:04
> I think if we don't have the name, we shouldn't display the tooltip.

Yeah that's a fair point. Maybe that's a better solution. Do we know how hard it is to convert it into an emoji?

**Comment by shawnborton** [comment] 2024-10-17 07:00
Yeah I feel like if it's just a unicode character that's not a real emoji, we shouldn't show a tooltip at all. 

I would also be down to just close this and do nothing as I feel like it's an extreme edge case...

**Comment by Shahidullah-Muffakir** [comment] 2024-10-17 16:58
> > 3\. It also happens with emojis selected from the emoji picker.
> 
> @Shahidullah-Muffakir can you provide an example here?

@trjExpensify I meant **it can** happen with emojis selected from the emoji picker if the color is the same as the background color. Sorry for the confusion!

**Comment by trjExpensify** [comment] 2024-10-17 17:00
Got it, but it doesn't? Okay cool, then I'm fine with closing this out if it's just these emojis from outside the app. Closing!

**Closed by trjExpensify** 2024-10-17 17:00 UTC
Labels: External, Daily, Help Wanted, Bug
