### ISSUE TITLE
[$250] Web - Chat - Approver see empty messages for requests made before the approver role was set

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34880] opened 2024-01-22 13:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4208303
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have created a collect workspace, add a member as employee A.
1. On ND, create some expenses with the employee A account and submit them.
2. As the admin in OD, add a member as the approver.
3. Log in to ND with the approver account and verify the chat with employee A and WS.

## Expected Result:
The approver should be able to see all the unapproved expenses.

## Actual Result:
The approver see empty messages for expenses submitted before the approver role was set.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/f46615ba-1244-40b9-8a7e-4416cec2e68b)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017fc2499c2e4e9f5a</li>
        <li>Upwork Job ID: 1749420326491856896</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-22 13:15
Issue found while performing https://expensify.testrail.io/index.php?/tests/view/4208303

**Comment by kbecciv** [comment] 2024-01-22 13:15
We think that this bug might be related to #wave7-collect-approvers
CC @RachCHopkins

**Comment by dylanexpensify** [comment] 2024-01-23 16:04
Nice, will let @RachCHopkins confirm!

**Comment by dylanexpensify** [comment] 2024-01-29 12:15
bump @RachCHopkins

**Comment by dylanexpensify** [comment] 2024-01-31 09:53
dm'ing

**Comment by dylanexpensify** [comment] 2024-02-05 12:56
Hmm @RachCHopkins I think you forgot to post here 😄

**Comment by dylanexpensify** [comment] 2024-02-07 10:35
@RachCHopkins 🙏

**Comment by dylanexpensify** [comment] 2024-02-13 19:51
confirming if approver should see these before having the approver role

**Comment by dylanexpensify** [comment] 2024-02-13 19:51
asked [here](https://expensify.slack.com/archives/C036QM0SLJK/p1707853899926809?thread_ts=1707853813.722569&cid=C036QM0SLJK)

**Comment by dylanexpensify** [comment] 2024-02-20 09:49
bumped thread

**Comment by dylanexpensify** [comment] 2024-02-26 11:19
kept it going, almost there!

**Comment by dylanexpensify** [comment] 2024-02-28 09:05
Moving to wave8 based on convo, cc @zanyrenney!

**Comment by dylanexpensify** [comment] 2024-03-06 10:40
Apologies, I've been OOO sick, but am reviewing today!

**Comment by dylanexpensify** [comment] 2024-03-20 10:10
@jjcoffee can you repro? I can't seem to

**Comment by jjcoffee** [comment] 2024-03-21 12:56
Yup they show up fine for me, unless there are some magic missing steps. Can you retest @kbecciv?

**Comment by kbecciv** [comment] 2024-03-21 13:59
@jjcoffee Checking with team!

**Comment by kbecciv** [comment] 2024-03-21 20:01
Issue is reproducible
![image (1)](https://github.com/Expensify/App/assets/93399543/9162fd3f-fce7-443a-aaa9-35aa546d4bd5)

**Comment by dylanexpensify** [comment] 2024-03-25 20:10
Just tried again and still can't repro. @kbecciv can you confirm the steps are complete? Nothing I'm missing?

**Comment by dylanexpensify** [comment] 2024-03-29 13:17
bump @kbecciv 🙇‍♂️

**Comment by kbecciv** [comment] 2024-03-29 18:09
@dylanexpensify Issue is reproducible on build 1.4.58.0, recorded a video with whole process.

https://github.com/Expensify/App/assets/93399543/3087288c-030d-4c43-bbb6-23520e4a82bd

**Comment by dylanexpensify** [comment] 2024-04-09 08:28
Ah ok, so there is some differences between the OP instructions and this, mainly:
- you invited the employee who submits in ND in OD _first_ as the admin of the workspace
- you then updated the approver role in OD via the Submit+Approve modal

Also, what was causing the difficulty for getting the approver to sign in?

**Comment by dylanexpensify** [comment] 2024-04-09 08:36
Went through with above comment's updates and still couldn't reproduce @kbecciv. @jjcoffee can you try again?

**Comment by kbecciv** [comment] 2024-04-09 14:00
@jjcoffee Checking

**Comment by dylanexpensify** [comment] 2024-04-12 16:29
@kbecciv any update?

**Comment by dylanexpensify** [comment] 2024-04-15 10:56
Bump @kbecciv

**Comment by kbecciv** [comment] 2024-04-15 17:32
Just retested - issue is reproducible on build v1.4.62-8

https://github.com/Expensify/App/assets/93399543/7d2739a1-b40a-4087-9e77-01b937558ce3

**Comment by jjcoffee** [comment] 2024-04-17 08:59
Finally managed to reproduce this! I _think_ setting the approval mode in OD to `Submit and Approve` might be the key.

> The approver should be able to see all the unapproved expenses.

I'm unsure if the expected result is correct for requests made before the approver is added, but if it is then this primarily requires BE changes in order to retrospectively give the new approver access to those reports. Opening any of the requests results in `Report not found` and a `jsonCode` of `403`.

**Comment by dylanexpensify** [comment] 2024-04-24 20:35
Nice! Thanks @jjcoffee! Let me confirm internally 👍

**Comment by dylanexpensify** [comment] 2024-04-29 10:20
[posted here!](https://expensify.slack.com/archives/C03U7DCU4/p1714386031958039)

**Comment by dylanexpensify** [comment] 2024-04-29 11:57
confirmed, approvers shouldn't see requests from before they were made an approver, only admins should

**Comment by dylanexpensify** [comment] 2024-04-29 18:17
Apologies, but after further conversation, we've deemed this a bug as all history should be visible in the chat when a user joins as an approver

**Comment by jjcoffee** [comment] 2024-04-30 08:33
@dylanexpensify I think this needs to be internal, see my comment [here](https://github.com/Expensify/App/issues/34880#issuecomment-2060755179).

**Comment by dylanexpensify** [comment] 2024-05-01 07:43
Ah, yes - thanks @jjcoffee!

**Comment by dylanexpensify** [comment] 2024-05-07 11:20
pending assignee internally!

**Comment by dylanexpensify** [comment] 2024-05-14 12:34
Pending availability for internal engineer

**Comment by dylanexpensify** [comment] 2024-05-21 20:24
Same, moving to weekly as we wait for internal engineer

**Comment by dylanexpensify** [comment] 2024-05-29 06:56
Similar

**Comment by dylanexpensify** [comment] 2024-06-05 09:44
Same, not a high priority

**Comment by dylanexpensify** [comment] 2024-06-17 18:04
Same

**Comment by dylanexpensify** [comment] 2024-06-26 09:24
Same

**Comment by dylanexpensify** [comment] 2024-07-03 08:45
No update

**Comment by dylanexpensify** [comment] 2024-07-10 08:17
Same

**Comment by mvtglobally** [comment] 2024-07-11 03:52
Issue not reproducible during KI retests. (First week)

**Closed** 2024-07-16 17:42 UTC
Labels: Engineering, Weekly, Internal, Help Wanted, Bug
