### ISSUE TITLE
[$500] Workspace-Some workspaces are shown in bold and some not

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#35766] opened 2024-02-03 21:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Pre-condition: open account with many workspaces created
1. Go to https://staging.new.expensify.com/
2. Tap in top right icon
3. Scroll down list of workspaces

## Expected Result:
All workspaces should be displayed in same manner.

## Actual Result:
Some workspaces are shown in bold and some not.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6f5d691b-dff9-4219-851e-649ad1b816ad

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015db9082b5dbefc79</li>
        <li>Upwork Job ID: 1753900794333388800</li>
        <li>Last Price Increase: 2024-02-03</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-03 21:59
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by puneet2715** [comment] 2024-02-03 22:41
@ZhenjaHorbach then the actual bug is that some workspace names are not getting the bold font even after having a green or red dot, meanwhile some have bold text even without a dot.

**Comment by ikevin127** [comment] 2024-02-04 14:02
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Some workspaces names are not shown in bold text when they are supposed to due to either having red / green brick indicators.

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/ReportUtils.ts#L3569-L3578

Both `getWorkspacesUnreadStatuses` and `ReportUtils.isUnread` functions are working as expected. If there's any unread report within a workspace (policy) based on the code block above -> the isUnread will return `true` for that said report which is part of the workspace -> therefore we will see the workspace name text having the bold style.

If what we want here as expected result is to keep the workspace name in bold style when there's no unread reports, but we have red / green brick indicators present then the problem is we're missing an additional condition where we set the `boldStyle: hasUnreadData(policy?.id)`.

### What changes do you think we should make in order to solve the problem?

Within the `WorkspaceSwitcherPage` component, add additional condition to `boldStyle` as follows:
- `boldStyle: hasUnreadData(policy?.id) || !!getIndicatorTypeForPolicy(policy?.id)`

this way if within any of that workspace's reports there's any kind of indicator present -> the workspace name text will have the bold style until the indicator is resolved by the user within the report that is causing it.

### Videos

<details>
<summary>iOS: Native</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/30af3f34-e3bb-4eb8-8790-b59361a4e7ff"> | <video src="https://github.com/Expensify/App/assets/56457735/365b78bb-33bc-48d1-936b-34e824e05c30"> |

</details>

**Comment by mountiny** [comment] 2024-02-05 13:31
This is not a blocker, I actually think this is expected behaviour

**Comment by mountiny** [comment] 2024-02-05 13:38
This is a dupe of existing issue with better issue body/ repro steps here https://github.com/Expensify/App/issues/35682

**Comment by trjExpensify** [comment] 2024-02-05 13:38
Right, if the workspace in question has chats with unread messages, the row should be bold. We don't add a GBR for unread messages. 

That said, I think there's a bug with the bold rows, as logged here: https://github.com/Expensify/App/issues/35682

Perhaps this issue is just a dupe.

**Closed** 2024-02-05 13:38 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
