### ISSUE TITLE
[$250] Thread - New line marker appeared incorrectly when mark as read is clicked

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46421] opened 2024-07-29 15:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N/A
**Email or phone of affected tester (no customers):** biruknew45+3456@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to [staging.new.expensify.com].
2. Open any chat
3. Send a random text message
4. Right-click on the message and select "Reply in Thread."
5. Send a random text in the thread
6. Reply in the thread to the text message sent in step 5. (The second thread which is in the middle)
7. Send another random text message in the thread
8. Hover over the text message sent in step 5
9. Right-click on the message and select "Mark as Unread."
10. Head over to the Left Hand Navigation (LHN)
11. Right-click on the bold message in the LHN. (The thread where you clicked as Unread on step 9)
12. Click "Mark as Read."

## Expected Result:
When a message is marked as unread in step 9, the new line marker should appear immediately. The marker should not appear upon marking the message as read in step 12

## Actual Result:
In step 9, after marking the message as unread, the new line marker does not appear as expected. In step 12, when the message is marked as read, the new line marker incorrectly appears in the chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/bcbb41b2-89b4-45e1-aef2-e9be89494e09

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016aa3122eebc32cef</li>
        <li>Upwork Job ID: 1819054764777494946</li>
        <li>Last Price Increase: 2024-08-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by lanitochka17** [comment] 2024-07-29 15:32
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-29 15:32
We think that this bug might be related to #vip-vsp

**Comment by FitseTLT** [comment] 2024-07-29 21:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Thread - New line marker appeared incorrectly when mark as read is clicked

### What is the root cause of that problem?
When marked as unread the first time the `report.lastReadTime` of the parent report is changed and  `getAllAncestorReportActions` will be called to recalculate ancestor report actions with the new value of the parent report however with the way we grab the parent report from onyx here
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/libs/ReportUtils.ts#L6793-L6794
it doesn't get the up-to-date value of the parent report (it gets the previous version of the parent report) and hence the marker not shown and second time we mark as read it will get the parent report status it had when we marked as unread the first time so this time the maker will appear.
### What changes do you think we should make in order to solve the problem?

In `ReportActionItemParentAction` we need to pass the up-to-date [ancestorReports](https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/pages/home/report/ReportActionItemParentAction.tsx#L66-L67) list to `getAllAncestorReportActions` as a param and use it instead of value found from `getReportOrDraftReport` here
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/libs/ReportUtils.ts#L6793-L6794
```
        const parentReport = ancestorReports[parentReportID] ?? getReportOrDraftReport(parentReportID);

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-29 21:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Thread - New line marker appeared incorrectly when mark as read is clicked

### What is the root cause of that problem?
When marked as unread the first time the `report.lastReadTime` of the parent report is changed and  `getAllAncestorReportActions` will be called to recalculate ancestor report actions with the new value of the parent report here
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/pages/home/report/ReportActionItemParentAction.tsx#L75-L79
however at that moment with the way we grab the parent report from onyx here
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/libs/ReportUtils.ts#L6793-L6794
it doesn't get the up-to-date value of the parent report (it gets the previous version of the parent report) and hence the marker not shown and second time we mark as read it will get the parent report status it had when we marked as unread the first time so this time the maker will appear.
### What changes do you think we should make in order to solve the problem?

In `ReportActionItemParentAction` we need to pass the up-to-date [ancestorReports](https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/pages/home/report/ReportActionItemParentAction.tsx#L66-L67) list to `getAllAncestorReportActions` as a param and use it instead of value found from `getReportOrDraftReport` here
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/libs/ReportUtils.ts#L6793-L6794
```
        const parentReport = ancestorReports[parentReportID] ?? getReportOrDraftReport(parentReportID);

```
### What alternative solutions did you explore? (Optional)

**Comment by eVoloshchak** [comment] 2024-08-07 15:23
@FitseTLT, thank you for the thorough [explanation](https://github.com/Expensify/App/issues/46421#issuecomment-2257074603)!

> however at that moment with the way we grab the parent report from onyx, it doesn't get the up-to-date value of the parent report (it gets the previous version of the parent report)

What's causing this? `getReportOrDraftReport` uses [allReports](https://github.com/Expensify/App/blob/0a33186c80eb821d67d75b44bca527640204852c/src/libs/ReportConnection.ts#L12), is it not up to date? If so, how do we make it up to date? That would ensure we fix this (and similar bugs that might be caused by this) throughout the app

**Comment by eVoloshchak** [comment] 2024-08-12 12:19
> We can also delay the execution of getAllAncestorReportActions to be executed on another execution cycle on which case now allReports will have been updated at the end of the current execution cycle and the up-to-date value will be ready then.

@FitseTLT, let's avoid using setTimeout unless there is no alternative

> but its value is updated in another [onyxSubscribe](https://github.com/Expensify/App/blob/0e46257f3295243e5ef306b723288cb1673ed6f1/src/pages/home/report/ReportActionItemParentAction.tsx#L77-L81) callback after the execution of our onyx callback [here](https://github.com/Expensify/App/blob/0e46257f3295243e5ef306b723288cb1673ed6f1/src/pages/home/report/ReportActionItemParentAction.tsx#L77-L81)

Looks like a typo, both links are identical, but it's still clear what's happening, thank you for the explanation

> The problem lies in calling getAllAncestorReportActions in onyx subscribe callback which depends on allReports which only gets updated later on the same execution cycle

What determines the order in which these entries are updated? Can we change the order so `allReports` are updated before the `ancestorReport`?

**Comment by FitseTLT** [comment] 2024-08-12 12:31
>What determines the order in which these entries are updated? 

It's because `allReports` is a collection subscription (and also with `waitForCollectionCallback `) but `ancestorReport` is a single report subscription. 
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/ff57293b-a6bf-4c91-8f07-4d7581b20694">

>Can we change the order so allReports are updated before the ancestorReport?

As far as I know, No.

**Comment by eVoloshchak** [comment] 2024-08-21 17:27
> As far as I know, No.

In that case, I think we should proceed with @FitseTLT's [proposal](https://github.com/Expensify/App/issues/46421#issuecomment-2257074603)

🎀👀🎀 C+ reviewed!

**Comment by anmurali** [comment] 2024-08-28 01:49
Sent offers to @eVoloshchak (https://www.upwork.com/offer/103712109) and @FitseTLT (https://www.upwork.com/offer/103712116). Let's get the fix started!

**Comment by mvtglobally** [comment] 2024-09-21 04:24
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-10-05 03:07
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2024-10-19 03:48
Issue not reproducible during KI retests. (Third week)

**Comment by eVoloshchak** [comment] 2024-10-20 18:25
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that has caused this, this is a limitation of the initial implementation
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not needed, this is a rare edge case
- Determine if we should create a regression test for this bug
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? Yes_
It's easy to test for and is related to core functionality, so we might want to add a regression test

**Comment by eVoloshchak** [comment] 2024-10-20 18:25
**Regression Test Proposal**

1. Go to [staging.new.expensify.com].
2. Open any chat
3. Send a random text message
4. Right-click on the message and select "Reply in Thread."
5. Send a random text in the thread
6. Reply in the thread to the text message sent in step 5. (The second thread which is in the middle)
7. Send another random text message in the thread
8. Hover over the text message sent in step 5
9. Right-click on the message and select "Mark as Unread."
10. Verify that the green unread marker is shown above the message.

**Do we agree 👍 or 👎**

**Comment by eVoloshchak** [comment] 2024-10-20 18:26
@anmurali, the automation has failed, but this has been deployed to production for quite a while and is ready for payment

**Comment by FitseTLT** [comment] 2024-10-20 18:45
@anmurali FYI You had already paid me accidentally, even before I raised the PR.

**Comment by mvtglobally** [comment] 2024-10-30 09:40
Issue not reproducible during KI retests. (Fourth week)

**Comment by mvtglobally** [comment] 2024-11-08 15:21
Issue not reproducible during KI retests. (Fifth week) Can we close it?

**Comment by eVoloshchak** [comment] 2024-11-10 19:36
@anmurali, could you handle the payment on this one please? Thanks!

**Comment by anmurali** [comment] 2024-11-12 02:43
@eVoloshchak - you have declined [the offer](https://www.upwork.com/nx/wm/offer/103712109)
Are you able to still reverse that and accept it?

**Comment by anmurali** [comment] 2024-11-12 02:44
Rotating the label so we can assign another BZ member while I am OOO. @OfstadC - you need to add regression test and handle @eVoloshchak payment.

**Comment by eVoloshchak** [comment] 2024-11-12 20:27
> Are you able to still reverse that and accept it? Or do we need to send you a new offer?

I'll request the payment through NewDot, all I need is a payment summary. Thank you!

**Comment by OfstadC** [comment] 2024-11-12 22:13
[Regression test
](https://github.com/Expensify/Expensify/issues/443670)
Sounds like @FitseTLT was already [paid](https://github.com/Expensify/App/issues/46421#issuecomment-2425174889). Please correct me if i'm wrong!

## Payment Summary 
- @eVoloshchak due $250 via manual New Dot request

**Closed** 2024-11-12 22:13 UTC
Labels: Reviewing, External, Daily, Help Wanted, Bug

**Comment by JmillsExpensify** [comment] 2024-11-18 16:10
$250 approved for @eVoloshchak
