### ISSUE TITLE
[$250] Settings - Infinite loading on Private section if notification is received

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38602] opened 2024-03-19 15:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/37967

**Version Number:** 1.4.54.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: Notifications should be enabled.

1. Log out and close all Chrome windows
2. Open Chrome and log in with a new expensifail user
2. Navigate to Account settings - Profile

## Expected Result:
The section should load.

## Actual Result:
Infinite loading on Profile - Private section if notification is received from Concierge. It loads at first but starts spinning after receiving the notification.
I'm unable to check prod as I'm not getting a notification there.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9708e3e6-ed5d-4882-83f2-05d0818ec9f2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ce0234e9c243c7c</li>
        <li>Upwork Job ID: 1775984986283810816</li>
        <li>Last Price Increase: 2024-04-04</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-19 15:23
We think this issue might be related to the #collect project.

**Comment by nkdengineer** [comment] 2024-03-21 11:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Settings - Infinite loading on Private section if notification is received
### What is the root cause of that problem?
- When signing in the app, the API ```OpenApp``` is called. It returns ```private_personalDetails: []```.
- Then if we open the setting profile, the API ```OpenPersonalDetailsPage``` is called. It returns:
```
{
  "legalFirstName": "",
  "legalLastName": "",
  "dob": "",
  "address": {
    "street": "",
    "city": "",
    "state": "",
    "zip": "",
    "country": ""
  },
  "isLoading": false
}
```
- If the API ```OpenPersonalDetailsPage``` is called successfully before the other one, ```OpenApp```, the bug will occur. Because:
- In the ProfilePage, we use the below logic to decide whether we should display the loading indicator or not:
https://github.com/Expensify/App/blob/51ef6c1bd1cd3d981db744bff1fcff9e7c670c0c/src/pages/settings/Profile/ProfilePage.tsx#L73
and in this case, ```isLoadingPersonalDetails``` is always ```true``` because ```privatePersonalDetails: []```
### What changes do you think we should make in order to solve the problem?
- We already have logic to call the ```OpenPersonalDetailsPage``` again if ```privatePersonalDetails``` is not available as below:
https://github.com/Expensify/App/blob/82065804528dc66daaa6ba652ab2dea84684c619/src/hooks/usePrivatePersonalDetails.ts#L11-L18
but it is not called again when the ```privatePersonalDetails``` is changed.
- So the solution is that we should add the ```privatePersonalDetails``` to the above useEffect 's dependencies.
- For example, instead of using ```usePrivatePersonalDetails``` like [here](https://github.com/Expensify/App/blob/51ef6c1bd1cd3d981db744bff1fcff9e7c670c0c/src/pages/settings/Profile/ProfilePage.tsx#L70), we can use:
```
  useEffect(() => {
        if (network?.isOffline || (Boolean(personalDetails) && personalDetails?.isLoading !== undefined)) {
            return;
        }

        PersonalDetails.openPersonalDetails();
    }, [network?.isOffline, personalDetails]);
```
- Note: the above is just a quick code change to test.
### What alternative solutions did you explore? (Optional)

- NA

**Comment by trjExpensify** [comment] 2024-04-02 08:46
👋 I see this one was added to Hot Picks. Is it a backend issue, or is it frontend and can go `External`?

**Comment by nkdengineer** [comment] 2024-04-02 08:53
I think it is FE issue based on RCA [here](https://github.com/Expensify/App/issues/38602#issuecomment-2011985152)

**Comment by trjExpensify** [comment] 2024-04-04 20:33
Cool, let's send it External!

**Comment by Pujan92** [comment] 2024-04-08 13:08
I can reproduce with the steps

1. Logout
2. Try to open profile link directly(eg. https://staging.new.expensify.com/settings/profile)
3. Login with the account where private details haven't been updated yet
4. infinite loading can be observed for the private section

**Comment by Pujan92** [comment] 2024-04-08 14:28
RCA mentioned by @nkdengineer looks correct where `private_personalDetails` merged with `[]` with the later call of `OpenApp` api.

I think the issue is with the `OpenApp` API `private_personalDetails` return type, it should be consistent by providing the object `{}` instead `[]`. With that, I believe this should require a BE fix. @isabelastisser @trjExpensify Can we add engineering label here to confirm?

<details>
<summary>Video</summary>

https://github.com/Expensify/App/assets/14358475/a7c65a92-37f9-4532-ad72-dd92d0cffcae

</details>

**Comment by nkdengineer** [comment] 2024-04-08 18:09
@Pujan92 I think if we just "providing the object {} instead []", the issue is not fixed

**Comment by Pujan92** [comment] 2024-04-08 18:17
It will be fixed @nkdengineer as merging empty object won't overwrite the existing data which implies there isn't anything to update. So `isLoading` will remain available with the respective bool value.

https://github.com/Expensify/App/assets/14358475/ca461dc3-8187-46f8-9585-c1d8bf99bbd8

**Comment by nkdengineer** [comment] 2024-04-08 18:18
Yeah that make sense @Pujan92

**Comment by nkdengineer** [comment] 2024-04-08 18:36
Just confuse about why the key name is ```private_personalDetails``` but not ```private_personalDetail```

**Comment by trjExpensify** [comment] 2024-04-08 23:08
Do we still need clarification here?

**Comment by Pujan92** [comment] 2024-04-09 03:05
No @trjExpensify, it is a BE issue and we need to assign internal engineer.

**Comment by nkdengineer** [comment] 2024-04-10 15:16
@trjExpensify Can you help confirm why the key name is ```private_personalDetails``` (multiple elements) but not ```private_personalDetail``` (single element)? Can we have more than one perrsonal detail data?

**Comment by isabelastisser** [comment] 2024-04-11 21:00
Not overdue.

**Comment by isabelastisser** [comment] 2024-04-15 17:05
@Pujan92 please provide an update. Thanks!

**Comment by Pujan92** [comment] 2024-04-15 17:07
@isabelastisser needs to assign an internal engineer as change is required in the backend.

**Comment by isabelastisser** [comment] 2024-04-16 13:43
`HOT PICK` label has been added already. We are waiting for an engineer to be assigned to this issue. cc @trjExpensify

**Comment by mvtglobally** [comment] 2024-04-18 15:54
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment] 2024-04-19 17:30
Not overdue.

**Comment by trjExpensify** [comment] 2024-04-24 23:26
Yeah, more accurately we need an engineering volunteer as we don't auto-assign issues out anymore. ;) It's being called out in Hot Picks. I'll drop this to `Weekly` for yah. 👍

**Comment by Beamanator** [comment] 2024-04-25 08:53
I'm happy to jump in here, not sure the #wave-collect priority 😅

**Comment by Pujan92** [comment] 2024-05-09 14:38
@Beamanator Wondering if I(c+) need to stay assigned for the issues that are internal and changes needed in the backend?

**Comment by Beamanator** [comment] 2024-05-10 06:44
Good call @Pujan92 , probably not :D 

FYI the fix went to prod 1 week ago - @Expensify/applauseleads can we get this retested please? 🙏

**Comment by nkdengineer** [comment] 2024-05-20 16:10
> FYI the fix went to prod 1 week ago

@Beamanator What is the output after fixing? The ```private_personalDetails``` is always object ```{}``` instead of ```[]``` in ```OpenApp``` API, right?

**Comment by Beamanator** [comment] 2024-05-21 08:00
@nkdengineer exactly, technically `private_personalDetails` should include your private personal details IF set, but if you haven't set any, it should return `{}` instead of `[]`

**Comment by Beamanator** [comment] 2024-05-30 08:27
Adding `retest-weekly` to hopefully get applause's attention to retest! 🙏

**Comment by mvtglobally** [comment] 2024-06-05 21:23
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment] 2024-06-07 20:17
Not overdue.

**Comment by Beamanator** [comment] 2024-06-09 07:19
Niiiice, maybe we wait till 1 more retest then close if it's fixed 👍

**Comment by isabelastisser** [comment] 2024-06-26 14:12
Bump @mvtglobally

**Comment by mvtglobally** [comment] 2024-07-03 14:33
Issue not reproducible during KI retests. (Second week)

**Comment by Beamanator** [comment] 2024-07-08 10:48
Looks like we'll close this this week 🙏

**Comment by mvtglobally** [comment] 2024-07-11 03:53
Issue not reproducible during KI retests. (Third week)

**Comment by Beamanator** [comment] 2024-07-15 09:44
Nice, closing!

**Closed by Beamanator** 2024-07-15 09:44 UTC
Labels: Weekly, Internal, Bug, retest-weekly
