### ISSUE TITLE
[$500] BUG:  Copy / Pasting a last message in the compose box, returning the copied text and some random text reported by @mollfpr 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11921] opened 2022-10-17 17:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat
2. Go to the last chat of a thread
3. Double/triple tap until all the text is highlighted and copy with CMD+C / CTRL+C
4. Paste the text to the composer input or notepad

## Expected Result:
The pasted text is the text that you just copy

## Actual Result:
The pasted text is the text that you just copy and some random text and error message appears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.16-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196245398-44c8e0e9-d06d-4dda-ac78-1c2a51465e83.mp4
https://user-images.githubusercontent.com/43996225/196245405-3f3d68f8-2a5f-452f-8dfe-ac9057ccec10.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mollfpr 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666000158578689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment] 2022-10-17 21:33
@kavimuru - I'm unable to replicate this issue. Can you please try again? Thanks!

**Comment by mollfpr** [comment] 2022-10-18 02:53
@alexpensify Could you try to send a message and double/triple tap on empty space chat to highlight the text then copy with `cmd+c` or `ctrl+c`?

https://user-images.githubusercontent.com/25520267/196324722-81d55ece-dfe0-42e6-aa05-a78346de2cd9.mov

**Comment by alexpensify** [comment] 2022-10-18 13:40
I'm still unable to replicate it. I followed the new steps to select the white space and input `cmd+c` and was successful to copy. Assigning it to Engineering for another review.

**Comment by alexpensify** [comment] 2022-10-18 13:41
Here are screenshots from my test via the web app: 

![image](https://user-images.githubusercontent.com/8107070/196446466-08a883b2-ea91-4c60-9b46-6b46c16b2f4a.png)

![image](https://user-images.githubusercontent.com/8107070/196446503-8c0303fb-f800-41a7-8d07-98dc929b79fc.png)

**Comment by jasperhuangg** [comment] 2022-10-18 17:13
Can repro on both staging and production. Going to investigate

**Comment by abekkala** [comment] 2022-10-19 17:04
@NikkiWines Can I get your opinion if your [GH here](https://github.com/Expensify/App/issues/11131) would also fix this one?

**Comment by abekkala** [comment] 2022-10-19 17:32
confirmed this one is unique and won't fix with that one

**Comment by abekkala** [comment] 2022-10-20 13:40
https://www.upwork.com/ab/applicants/1583090429121454080/job-details
https://www.upwork.com/jobs/~0134f44cfb0341e791

**Comment by osama256** [comment] 2022-10-24 07:20
### PROPOSAL
Replacing `copySelectionToClipboard` method in `src/components/CopySelectionHelper.js` with this method :
```javascript

  import React from 'react';
  import ExpensiMark from 'expensify-common/lib/ExpensiMark';
+ import Str from 'expensify-common/lib/str';

....


    copySelectionToClipboard() {
        const selection = SelectionScraper.getCurrentSelection();
        if (!selection) {
            return;
        }
        const parser = new ExpensiMark();
        if (!Clipboard.canSetHtml()) {
            Clipboard.setString(parser.htmlToMarkdown(selection));
            return;
        }
        if (selection.match(/It's.*Chats/)) {
            const replacement = parser.htmlToMarkdown(selection.split(/It's.*Chats/)[0]);
            Clipboard.setHtml(Str.htmlEncode(replacement), parser.htmlToText(selection).split(/It's.*Chats/)[0]);
            return;
        }
        if (selection.includes('Chats') && selection.includes('Concierge')) {
            const replacement = parser.htmlToMarkdown(selection.split(/Chats/)[0]);
            Clipboard.setHtml(Str.htmlEncode(replacement), parser.htmlToText(selection).split(/Chats/)[0]);
            return;
        }
        Clipboard.setHtml(selection, parser.htmlToText(selection));
    }
```


https://user-images.githubusercontent.com/51829206/197469228-b1f200da-6a42-409c-8d4e-ca250c7a2b66.mp4

**Comment by sobitneupane** [comment] 2022-10-25 15:14
I was able to reproduce it on Desktop v1.2.19-1.

@osama256 Thanks for your proposal.
Your proposal does not state the cause of the issue. Can you please explain the cause of this issue?

It looks like you have added two conditions. I am not convinced with the approach you are proposing. It looks like a temporary solution. What if we start using Spanish translation of "Chats" when Spanish is selected as language?

**Suggestion:** Can you please use diff instead of plain code block in your proposals. Diff is better to understand what changes you are proposing.

**Comment by abekkala** [comment] 2022-10-28 18:48
@osama256 can you address the requested information for your proposal, please.

**Comment by abekkala** [comment] 2022-10-31 14:31
@osama256 are you able to provide the information requested by @sobitneupane ?

**Comment by osama256** [comment] 2022-11-01 18:47
@abekkala Sorry for the delay, I agree with @sobitneupane [this solution](https://github.com/Expensify/App/issues/11921#issuecomment-1288531628) is a temporary solution.

The reason of this issue is we are using `@react-navigation/drawer` version higher than `6.3.1`, if you downgrade to `6.3.1` or below you won't see this issue, in these versions the drawer use legacy implementation `useLegacyImplementation={true}` by default, I already submitted a proposal that will cover both issues [here](https://github.com/Expensify/App/issues/12028#issuecomment-1298942334).

**Comment by mvtglobally** [comment] 2022-11-03 03:19
Issue not reproducible during KI retests. (First week)

**Comment by jasperhuangg** [comment] 2022-11-03 18:56
I'm unable to reproduce this on dev, staging, and production. Closing this out

**Comment by trjExpensify** [comment] 2022-11-04 01:07
It can be reliably reproduced on my side on `v1.2.23-7`. Got a vid Jasper? Are you tapping three times?  

![copy junk](https://user-images.githubusercontent.com/16232057/199863397-a3059304-2922-4f09-a692-60fddd0af303.gif)

**Comment by abekkala** [comment] 2022-11-07 12:53
@jasperhuangg can you try to replicate again? it seems that @trjExpensify was able to replicate

**Comment by jasperhuangg** [comment] 2022-11-07 21:53
^TLDR: we're still looking for proposals for this one!

**Comment by trjExpensify** [comment] 2022-11-07 21:57
Yeah, the URL bug is here: https://github.com/Expensify/App/issues/11735

**Comment by abekkala** [comment] 2022-11-08 15:39
price doubled to $500
https://www.upwork.com/ab/applicants/1583090429121454080/job-details
https://www.upwork.com/jobs/~0134f44cfb0341e791

**Comment by wildan-m** [comment] 2022-11-10 08:24
### Proposal
Seems this issue has the same fix with #12028
Please review it:
https://github.com/Expensify/App/issues/12028#issuecomment-1309908376

**Comment by abekkala** [comment] 2022-11-10 18:44
@jasperhuangg @sobitneupane 
If you approve of the above proposal just give me a quick thumbs ups and I'll start the hiring steps in Upwork

**Comment by trjExpensify** [comment] 2022-11-10 18:51
If the fix for this is going to be coming in the same PR as the one for #12028, then we should combine C+ reviewers and issues.

**Comment by sobitneupane** [comment] 2022-11-11 01:07
@trjExpensify It is likely that the same PR will solve both the issues.

**Comment by sobitneupane** [comment] 2022-11-14 08:16
@trjExpensify Should I also review the proposal https://github.com/Expensify/App/issues/12028#issuecomment-1309908376 for this issue?

**Comment by trjExpensify** [comment] 2022-11-14 13:38
@sobitneupane it looks like @thesahindia has reviewed that proposal and given it the ✅. Though, @thesahindia can you confirm it fixes this issue as well ahead of us closing it?

**Comment by abekkala** [comment] 2022-11-14 14:27
Closed Upwork job.

**Closed by abekkala** 2022-11-14 14:27 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
