### ISSUE TITLE
LHN - Conversation is not grayed out in LHN in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24102] opened 2023-08-03 12:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to http://staging.new.expensify.com/
2. Log in with a HIGH TRAFFIC account
3. Enable Airplane mode to simulate a connection loss
4. Send message to any conversation

## Expected Result:
When send message in offline mode - the conversation in LHN view should be grayed out

## Actual Result:
Conversation is not grayed out in LHN in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.49.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e5f843b0-2dd4-450f-99e2-cb56482b098d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2023-08-03 19:30
I'm not able to reproduce this - the message is greyed out when testing. Asking for QA to check this - https://expensify.slack.com/archives/C9YU7BX5M/p1691091026199849

**Comment by Christinadobrzyn** [comment] 2023-08-04 21:46
Thanks @dukenv0307, my confusion is that the LHN message isn't bolded which indicates it is not a new message. 

I see the chat message is greyed out - to be expected when offline. 
But the LHN chat is not bold which would indicate the new message isn't showing there yet either. 

![image](https://github.com/Expensify/App/assets/51066321/824ecf2c-de97-46a9-8db1-addfeb951759)

So I don't understand what is expected that isn't happening... It seems like it's working as expected.

**Comment by Victor-Nyagudi** [comment] 2023-08-07 11:58
I also believe this isn't a bug. 

The message in the chat is greyed out to show it hasn't been sent yet, but greying out the chat in the LHN could imply the entire chat is disabled. 

In addition, the chats in the LHN are already greyed out to some degree to indicate no new messages have been received.

**Comment by Christinadobrzyn** [comment] 2023-08-07 18:05
The LHN message is not bolded in my screenshot here https://github.com/Expensify/App/issues/24102#issuecomment-1666210882 and in all the videos. 

I think this is behaving as expected. The LHN should be greyed out until the user is online and then the message in the chat will be sent making the LHN bold. I'm closing this without action.

**Closed by Christinadobrzyn** 2023-08-07 18:05 UTC
Labels: Daily, Overdue, Bug
