### ISSUE TITLE
[$500] Chat - Whisper for flagged message meant for the offender is visible to person who flags it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31443] opened 2023-11-16 13:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [User A] Send a message (MODERATION_TEST) to user B.
2. [User B] On Android or iOS app, flag the message as Assault.

## Expected Result:
User B will not be able to see the whisper message that is meant for User A.

## Actual Result:
User B is able to see the whisper message that is meant for User A.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1d47bb86-182d-42f0-bb5b-61f104a2dab4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc7ea43f03435a3c</li>
        <li>Upwork Job ID: 1725150741846491136</li>
        <li>Last Price Increase: 2023-11-16</li>
    </ul>
</details>

**Comment by erquhart** [comment] 2023-11-16 14:37
I would expect this to be addressed on the backend, whispers for other users shouldn't be in the api responses.

**Comment by NikkiWines** [comment] 2023-11-21 00:20
Yep, definitely a backend issue. cc: @pecanoro in case you want to snag this since you have familiarity with our whisper logic.

**Comment by pecanoro** [comment] 2023-11-21 00:52
This is unrelated to the whisper logic, I am 99% sure that whoever wrote the flagging functionality is sending push notifications to all chat participants instead of the person in the whisperedTo (the function to send the notification has an additional parameter to only send the notification to some accountIDs and it's probably missing).

**Comment by pecanoro** [comment] 2023-11-21 00:54
Adding to my previous comment, that was my theory because if you log out and log in again the whisper is gone, so basically this is due to some faulty pusher events.

**Comment by NikkiWines** [comment] 2023-11-28 21:11
Been OOO, will look into this when I'm back

**Comment by NikkiWines** [comment] 2023-12-05 01:24
Dropping this to weekly for now, still on my radar

**Comment by NikkiWines** [comment] 2023-12-08 06:03
I'm not longer able to reproduce this. @kbecciv can we confirm this is still an issue please?

**Comment by NikkiWines** [comment] 2023-12-09 00:54
Confirmed not reproducible on staging v1.4.10-1. Closing

https://github.com/Expensify/App/assets/16747822/cd055ad9-0953-4b2a-986a-2a3b0782fcfd

**Closed by NikkiWines** 2023-12-09 00:54 UTC
Labels: Engineering, Daily, Internal, Bug
