### ISSUE TITLE
[$1000] We can add and verify any random contact method in settings.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23608] opened 2023-07-26 02:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on settings.
2. Go to profile > Contact Methods.
3. Add any random email/phone number in "New Contact method". (Make sure that email is not already registered with Expensify and if trying with some random phone number make sure it is not a VOIP number)
4. Add another account that you own(I used the same account with alias that Im logged into the Expensify app).
5. Now use the magic code you got in you real account(From step 4) and use that code to verify the random email/phone you don't own.
6. You'll notice the fake contact method will be verified.
## Expected Result: 
Magic code received in another account should not be able to verify random contact methods.
## Actual Result:
 Magic code received in another account can verify random contact methods.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.45-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/38949117-2c1c-4925-8f2c-6314ec2f5335

https://github.com/Expensify/App/assets/43996225/3cdcde92-7634-4416-857b-f5d286f1beb8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priyankrawat
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690270991069259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ef527f07ddc5bd8</li>
        <li>Upwork Job ID: 1686492677634899968</li>
        <li>Last Price Increase: 2023-08-01</li>
    </ul>
</details>

**Comment by neonbhai** [comment] 2023-07-26 03:34
Seems like a backend issue. This function should fail:
https://github.com/Expensify/App/blob/0fec944de6f8014f6a4586c7d4b988ffdf8ea495/src/libs/actions/User.js#L354

**Comment by priyankrawat** [comment] 2023-07-26 04:46
[src/languages/es.js](https://github.com/priyankrawat/expensify/pull/2#issue-1821568863)

**Comment by tjferriss** [comment] 2023-08-01 21:43
Yikes. I was able to reproduce this one.

<img width="541" alt="Screenshot 2023-08-01 at 14 42 30" src="https://github.com/Expensify/App/assets/8292562/47f292de-43bc-48dd-bdb3-f8b5d432dc4e">

**Comment by tjferriss** [comment] 2023-08-01 21:44
I'm also going to add the `Engineering` label because I have a feeling we'll need someone internal to take a look at the back end settings.

**Comment by icarus-0520** [comment] 2023-08-01 21:52
TJ is right, I suspect the codes being generated are stored in a DB table with an expiration time, but not with the accompanying email address/phone number. Based on the UI, the verify action will be able to pass that information to the server, so that will minimize complexity, as you won't need to work that out from the broader user session. As such, the contact info that is associated with a code should be stored alongside that code and its expiration time in a database, and the API call should pass the code and the piece of contact info. On the server the expiration can be checked in addition to the validity of the code for that piece of contact info.

**Comment by icarus-0520** [comment] 2023-08-01 21:53
Contributor details
Expensify account email: aidan@disillusion.io
Upwork profile link: https://www.upwork.com/freelancers/~01ee97b9ff5ee5d693

**Comment by pecanoro** [comment] 2023-08-02 14:59
Confirmed it's duplicated, closing!

**Closed by pecanoro** 2023-08-02 14:59 UTC
Labels: External, Engineering, Daily, Bug
