### ISSUE TITLE
[$250]  Sign up - Not here page opens instead of Concierge after creating a new account

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45565] opened 2024-07-17 07:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Expensifail account.

## Expected Result:
Concierge chat opens.

## Actual Result:
Not here page opens.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9d6b0309-20fa-4fb4-9776-3e0eb1b82649

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167a324c0a8b8f5a2</li>
        <li>Upwork Job ID: 1813601728342001608</li>
        <li>Last Price Increase: 2024-07-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by izarutskaya** [comment] 2024-07-17 07:25
We think this issue might be related to the  #vip-vsb

**Comment by izarutskaya** [comment] 2024-07-17 07:26
Production

https://github.com/user-attachments/assets/625d6478-6950-4a01-8427-20c884eb686e

**Comment by youssef-lr** [comment] 2024-07-17 15:48
I can reproduce as well. Adding External in case this is an issue in App. I'll continue investigation meanwhile.

**Comment by youssef-lr** [comment] 2024-07-17 16:52
This seems to be an issue specifically with expensifail and perhaps any validated domain. There is no onboarding step that appears and we end up in the not-found page.

**Comment by thienlnam** [comment] 2024-07-17 21:05
With the above context, doesn't look like this is a blocker

**Comment by lschurr** [comment] 2024-07-23 22:15
Any update on this one @youssef-lr - Is this reproducible?

**Comment by madmax330** [comment] 2024-07-25 16:37
We have a similar issue here, could it be related to this one @fedirjh

**Comment by lschurr** [comment] 2024-07-25 19:54
@youssef-lr @fedirjh - Could you take a look?

**Comment by lschurr** [comment] 2024-07-29 15:49
Ok, it seems like we can close this one. Correct me if I'm wrong @fedirjh @madmax330

**Closed by lschurr** 2024-07-29 15:49 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
