### ISSUE TITLE
LHN - No GBR in LHN when there is a submitted expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51278] opened 2024-10-22 17:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** biruknew45+1782@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Go to the chat with User B
3. Submit an expense
4. Log out and log in as User B

## Expected Result:
A GBR should appear in the LHN for the submitted expense

## Actual Result:
There is no GBR displayed in the LHN for the submitted expense. it only appear after opening it and navigating back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/9443836b-49c0-4e34-a89b-b2d94f13d24d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-22 17:52
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-10-23 13:13
BE is returning proper value of `hasOutstandingChildRequest` only on OpenReport. BE bug.

**Comment by slafortune** [comment] 2024-10-24 19:08
Able to recreate this

**Comment by slafortune** [comment] 2024-10-25 20:19
not overdue - HotPick

**Comment by blimpich** [comment] 2024-10-28 18:21
Picking this up

**Comment by blimpich** [comment] 2024-10-28 20:36
Confirmed @FitseTLT assessment. `hasOutstandingChildRequest` should be set to true but is false until we open the report. Need to make the onyx data be included when opening the application and getting the reports. Hopefully a simple fix. Looking into it.

**Comment by blimpich** [comment] 2024-10-28 22:58
Looks like we're getting the onyx updates from Auth, not from Web, so the fix should be in there.

Seems like the stack trace for this error is OpenApp command -> Report::getChats(). getChats() is a massive function though that is quite difficult to understand, though I think I'm narrowing it down. [This](https://github.com/Expensify/Auth/blob/e92662e740063086376c2dc0a7a1d49bd43fc5ee/auth/lib/Report.cpp#L8420-L8425) is where it looks like we should be adding the `hasOutstandingChildRequest` onyx key, but we never get there when we call OpenApp because the report is type chat and doesn't have a parentID, which we filter out on before getting to the block of code we need. [This comment](https://github.com/Expensify/Auth/blob/e92662e740063086376c2dc0a7a1d49bd43fc5ee/auth/lib/Report.cpp#L8371-L8373) inside getChats helps explain a lot. 

I tried looking at the code history to understand why we filter out early, but this seems to have been in place for awhile.

My next question is, how does OpenReport correctly identify that this report has `hasOutstandingChildRequest` set to true? If I can find that logic then maybe I can reuse it in getChats() to make sure all the reports we look at have that onyx key set to the correct value.

**Comment by blimpich** [comment] 2024-10-29 00:00
GetReport command -> postProcess -> addReportSummaryToResponse -> getStructuredOnyxReportAndLastMessageData -> structureReportForOnyx -> ...eventually we hit [this line](https://github.com/Expensify/Auth/blob/e92662e740063086376c2dc0a7a1d49bd43fc5ee/auth/lib/Report.cpp#L10506) where we assign it for OpenReport.

Looks like it just checks the reportSummary, which we get by calling getChats ([link](https://github.com/Expensify/Auth/blob/e92662e740063086376c2dc0a7a1d49bd43fc5ee/auth/command/OpenReport.cpp#L686)).

So we should be able to get the data from within getChats since that is actually where OpenReport is getting the data from. But for some reason when we call getChats from openApp we don't get the hasOutstandingChildRequestData, but when we call it from openReport we do. Looks like it comes back to [this conditional](https://github.com/Expensify/Auth/blob/e92662e740063086376c2dc0a7a1d49bd43fc5ee/auth/lib/Report.cpp#L8370); that conditional is true in OpenApp but not in openReport, so we get down to [this block](https://github.com/Expensify/Auth/blob/e92662e740063086376c2dc0a7a1d49bd43fc5ee/auth/lib/Report.cpp#L8467-L8470) which sets it.

The biggest problem I see with this is that getChat is a 800+ line function in one of the most core classes of the whole app, and there isn't a ton of documentation on this, so messing with it is very delicate. Will keep working on this tomorrow.

**Comment by blimpich** [comment] 2024-10-29 00:12
At the very very last minute of my day I figured out a small change to fix this, but I'm 80% it'll cause other issues. I need more context on the code. Regardless, putting up a draft PR: https://github.com/Expensify/Auth/pull/12952

**Comment by blimpich** [comment] 2024-10-30 00:56
Posted asking for help today here: https://expensify.slack.com/archives/C03TQ48KC/p1730226386005509

Lots of things learned today. We can solve this by sending all the IOUs to the frontend, but that breaks tests and is probably unnecessary. So currently trying to fix it without doing that, but its proving to be much more complicated. Hoping tomorrow I'll have the time to get a new fix out.

**Comment by blimpich** [comment] 2024-10-30 21:04
Figured out a different way of fixing the bug without sending a bunch of IOU reports to the frontend. Polishing up the PR and then will put it out for review.

**Comment by blimpich** [comment] 2024-11-11 17:03
This was deployed to production a few days ago

**Closed by blimpich** 2024-11-11 17:03 UTC
Labels: Reviewing, Daily, Internal, Bug
