### ISSUE TITLE
[HOLD for payment 2024-06-05] [$250]  iOS - Wallet - App crashes when scrolling up and down bank account selection list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41069] opened 2024-04-26 08:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to Account settings.
3. Go to Wallet.
4. Tap Add bank account > Personal bank account.
5. Log in to Chase account.
6. On ND, scroll up and down the bank account selection modal.

## Expected Result:
App will not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9509fdb4-0201-4f5e-99f7-876e4f006e58

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0113aa04e4d3e2832e</li>
        <li>Upwork Job ID: 1790371872885301248</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by izarutskaya** [comment] 2024-04-26 08:40
We think this issue might be related to the #vip-vsb.

**Comment by abekkala** [comment] 2024-04-29 18:59
I wasn't able to reproduce this - applying re-test weekly label

**Comment by bernhardoj** [comment] 2024-05-06 08:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crash when scrolling in the add personal bank account plaid bank account picker.

### What is the root cause of that problem?
The crash will happen if you scroll to the "Choose an account" item. The issue started to happen after the [fabric support](https://www.github.com/react-native-picker/picker/pull/456) was added to @react-native-picker/picker.

The "Choose an account" is a placeholder item with an empty value.
https://github.com/Expensify/App/blob/8383d80013cf61e83fc8bd90eef5f8357f69cf91/src/components/AddPlaidBankAccount.tsx#L311-L314

If the value is empty, it will be converted to `nil` when creating the picker items map/dict.
https://github.com/react-native-picker/picker/blob/7b7a95f4fe842d0a0c696310f9f10a8267247227/ios/RNCPickerComponentView.mm#L51

When selection the picker item, if the value is `nil`, it will be converted to `kCFNull` which will crash inside [RCTStringFromNSString](https://github.com/facebook/react-native/blob/362abb9ffea5af7e6e5616849fbce28166c758a0/packages/react-native/React/Fabric/RCTConversions.h#L33-L36).
https://github.com/react-native-picker/picker/blob/7b7a95f4fe842d0a0c696310f9f10a8267247227/ios/RNCPicker.mm#L160

### What changes do you think we should make in order to solve the problem?

Don't convert to `nil` if the value is empty. So, we can replace `RCTNSStringFromStringNilIfEmpty` with `RCTNSStringFromString`. I think we can do the same for `label` and `testID`.

Then, we can remove `RCTNullIfNil` from [here](https://github.com/react-native-picker/picker/blob/7b7a95f4fe842d0a0c696310f9f10a8267247227/ios/RNCPicker.mm#L160) since it's not possible anymore to have a null value because we always [cast the value to string](https://github.com/react-native-picker/picker/blob/7b7a95f4fe842d0a0c696310f9f10a8267247227/js/PickerIOS.ios.js#L142).

**Comment by abekkala** [comment] 2024-05-08 17:49
we're retesting this

**Comment by mvtglobally** [comment] 2024-05-13 14:15
Issue not reproducible during KI retests. (First week)

**Comment by bernhardoj** [comment] 2024-05-14 02:03
It's still reproducible. You just need to select the Choose an account item.

https://github.com/Expensify/App/assets/50919443/4012ad99-00fd-47ab-868c-c044ec822e5c

**Comment by bernhardoj** [comment] 2024-05-17 11:11
I have opened the upstream PR [here](https://www.github.com/react-native-picker/picker/pull/567)

**Comment by amyevans** [comment] 2024-05-17 13:36
Thank you! Subscribed

**Comment by bernhardoj** [comment] 2024-05-20 08:39
Upstrea PR is merged. Waiting for a new picker version to be released.

**Comment by amyevans** [comment] 2024-05-20 13:40
Nice! 🙌

**Comment by bernhardoj** [comment] 2024-05-21 03:23
The fix has been released. PR to update the version is ready.

cc: @Ollyws @amyevans

**Comment by abekkala** [comment] 2024-05-29 16:47
### PAYMENT SUMMARY FOR JUNE 05

- Fix: @bernhardoj [$250, if no regressions] [Offer link](https://www.upwork.com/nx/wm/workroom/37292844/overview)
- PR Review: @Ollyws [$250, if no regressions] [Offer link,](https://www.upwork.com/nx/wm/offer/102341257) please complete checklist above

**Comment by abekkala** [comment] 2024-06-05 18:04
@bernhardoj payment sent and contract ended - thank you! 🎉 

@Ollyws can you please complete the checklist above? Thanks!

**Comment by abekkala** [comment] 2024-06-06 14:50
@Ollyws can you please accept the payment offer in Upwork and complete the checklist above?

**Comment by abekkala** [comment] 2024-06-07 13:39
@Ollyws can you please accept the payment offer in Upwork and complete the checklist above so that we can close this one out?

**Comment by abekkala** [comment] 2024-06-10 15:09
### PAYMENT SUMMARY: 

- @Ollyws PR Review [$250]

**Closed** 2024-06-10 15:09 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-11 18:25
$250 approved for @Ollyws
