### ISSUE TITLE
[HOLD for payment 2023-08-03] [HOLD for payment 2023-08-02] Bank Account - Unable to enter year of birth from keyboard on Personal Information page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23576] opened 2023-07-25 18:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Desktop App or go to staging.new.expensify.com on Chrome
2. Login with expensifail account
3. Go to existing or create new workspace
4. Go to Workspace > Connect Bank Account > Connect with plaid and follow the flow to the Personal Information page
5. Enter the date of birth using keyboard

## Expected Result:
User can enter date of birth using keyboard

## Actual Result:
Unable to enter YEAR of birth from keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.45.3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ea572e85-18cf-4b4d-bcf7-e36849c85ae1

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2023-07-25 19:13
- Confirmed broken on staging.
- Looking for offending PR.

**Comment by marcaaron** [comment] 2023-07-25 19:15
@srikarparsi @marcochavezf looks like this one -> https://github.com/Expensify/App/pull/20864

**Comment by srikarparsi** [comment] 2023-08-08 05:44
No payment needed for this issue as it was reported by applause and resolved internally.

**Comment by srikarparsi** [comment] 2023-08-08 05:45
Actually, @allroundexperts were you paid for testing the [PR](https://github.com/Expensify/App/pull/23588)?

**Comment by srikarparsi** [comment] 2023-08-08 06:27
Cool! Can you please raise a manual request whenever you get a chance?

**Comment by srikarparsi** [comment] 2023-08-10 20:52
Closing this out.

**Closed by srikarparsi** 2023-08-10 20:52 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2023-08-15 16:22
@srikarparsi Can you confirm in writing that @allroundexperts should be compensated $1,000 for this PR review?

**Comment by JmillsExpensify** [comment] 2023-08-15 16:38
Thanks for confirming! Approved for payment in NewDot.

**Comment by JmillsExpensify** [comment] 2023-08-15 16:47
Actually this is a component refactor and may only be eligible for $250. Asking internally first.

**Comment by srikarparsi** [comment] 2023-08-15 17:00
Just confirmed that this should be $250 for reviewing a revert to a refactor functional component PR. Sorry for the confusion @allroundexperts, could you please request $250 instead?
