### ISSUE TITLE
[$250] iOS - Composer - "Write something..." is not in the middle of the composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46443] opened 2024-07-29 19:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Open any chat

## Expected Result:
"Write something..." will be in the middle of the composer

## Actual Result:
"Write something..." is not in the middle of the composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/789a4e8d-3ebe-4bb5-949f-b488d41fb344

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013fd28700fc476d2f</li>
        <li>Upwork Job ID: 1818012292903295394</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @marcochavezf</details>

**Comment by lanitochka17** [comment] 2024-07-29 19:49
@marcochavezf  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-29 19:49
We think that this bug might be related to #vip-vsp

**Comment by roryabraham** [comment] 2024-07-29 19:54
not a back-end deploy blocker, but I think since this negatively affects a very core component of the app it should be treated as a blocker

**Comment by roryabraham** [comment] 2024-07-29 19:58
agree, was just coming to post the same thing. Would love to see this fixed rather than just reverting that PR which took a long time to land

**Comment by stephanieelliott** [comment] 2024-07-29 20:19
Cool, so @roryabraham are you thinking we treat this as if it's a regular bug and get proposals on it?

**Comment by marcochavezf** [comment] 2024-07-29 20:57
Hi @mkhutornyi can you look at [@ShridharGoel's proposal](https://github.com/Expensify/App/issues/46443#issuecomment-2256831491)?

**Comment by hayes65** [comment] 2024-07-29 21:17
I still dont understand how does the proposal above fixes [this issue ](https://github.com/Expensify/App/issues/46443#issuecomment-2256831491)... the issue doesn't happen when you type an emoji and two characters .. so what is the problem with typing an emoji and one character ?

**Comment by roryabraham** [comment] 2024-07-29 21:53
> Cool, so @roryabraham are you thinking we treat this as if it's a regular bug and get proposals on it?

yeah but still treat is as an hourly for now. That would be my inclination

**Comment by stitesExpensify** [comment] 2024-07-29 23:13
Personally I agree with a revert since there are now 3 deploy blockers / regressions linked

**Comment by marcochavezf** [comment] 2024-07-29 23:54
I created a revert [here](https://github.com/Expensify/App/pull/46463) to unblock the deploy today

**Comment by roryabraham** [comment] 2024-07-30 23:57
We CP'd the revert, so this should be fixed now. Will retest on TF...

**Comment by roryabraham** [comment] 2024-07-30 23:58
confirmed this is fixed ✅

**Closed by roryabraham** 2024-07-30 23:58 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
