### ISSUE TITLE
Search - Some of the expense amounts are truncated

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49930] opened 2024-09-30 13:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** komaromalberlet@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an old account that has a lot of expenses
3. Click on "Search"
4. Scroll down

## Expected Result:
Expense amounts should be fully visible

## Actual Result:
Some of the expense amounts are truncated. Android is more affected than web or desktop. Different expenses are truncated on different environments. Short and long amounts can be both truncated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/fade9851-6ed0-4ae1-ba96-aee6813e0855

![4255_New_Expensify](https://github.com/user-attachments/assets/3cda7702-de7c-4132-abfc-a62862bef003)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by etCoderDysto** [comment] 2024-09-30 13:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Some of the expense amounts are truncated
### What is the root cause of that problem?
We are not passing numberOfLines={0} below, and the amount is truncated since the defaultNumberOfLines = 1
https://github.com/Expensify/App/blob/0e3b82cc9d5e5425bf7dae5652538fdb494c7799/src/components/SelectionList/Search/TransactionListItemRow.tsx#L166-L169
### What changes do you think we should make in order to solve the problem?

We should pass numberOfLines={0}
### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-09-30 13:49
[Proposal updated ](https://github.com/Expensify/App/issues/49930#issuecomment-2383232084)
* Added result

**Comment by joekaufmanexpensify** [comment] 2024-10-01 21:38
Hmmm, this truncating behavior seems pretty standard to me for handling this with smaller screens for keeping the amounts in a consistent place. It only impacts longer numbers, and you can always view the full details by clicking into any individual expense. I'm going to close this for now, as I don't think this is really a bug. 

Let me know if this is expected behavior, and happy to push this through. cc @luacmartins

**Closed by joekaufmanexpensify** 2024-10-01 21:38 UTC
Labels: Daily, Bug
