### ISSUE TITLE
[Payment due 3/6][$500] Font in "Hold Request" reason heading text is looks wrong

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37039] opened 2024-02-21 17:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.43-7
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708436683366409

## Action Performed:
1. Create a IOU request
2. Open the IOU details and click on 3 dot and select "Hold request" option
3. Look at the `Explain why you're holding this request`

## Expected Result:
Should match with same font in other section like `display name`

## Actual Result:
It shows with different font.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screen Shot 2024-02-21 at 12 50 00 PM](https://github.com/Expensify/App/assets/38435837/1107d17d-5c6b-402d-a3a2-c823c275fa88)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017627c882f3450aea</li>
        <li>Upwork Job ID: 1760361321264185344</li>
        <li>Last Price Increase: 2024-02-21</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>shahinyan11 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2024-02-21 17:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Font in "Hold Request" reason heading text is looks wrong
### What is the root cause of that problem?
Set `styles.textHeadline` for this text
### What changes do you think we should make in order to solve the problem?
Change [this](https://github.com/Expensify/App/blob/04737ae9074c78d262502f75e879c45283db1178/src/pages/iou/HoldReasonPage.tsx#L79C31-L79C50) style with corresponding style

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2024-02-21 20:27
@shahinyan11 Thanks for the proposal. Your RCA is correct. The solution looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/37039#issuecomment-1957522973)

**Comment by s77rt** [comment] 2024-02-21 20:29
@codinggeek2023 Thanks for the proposal. Unfortunately it's a dupe.

**Comment by s77rt** [comment] 2024-02-21 20:30
@dukenv0307 Thanks for the proposal. Your RCA is correct but the solution does not achieve the expected results.

**Comment by s77rt** [comment] 2024-02-21 20:38
@codinggeek2023 No worries. I didn't imply that you copied the solution 😅. I checked the timeline both solutions posted closely at the same time (2 mins apart).

**Comment by handipriyono** [comment] 2024-02-22 08:05
is this still open? or still figuring out ?

**Comment by robertjchen** [comment] 2024-02-23 03:00
Thanks @codinggeek2023 ! 

cc: @Expensify/design for a quick sanity check (👍 / 👎 ). Based on the [Slack discussion](https://expensify.slack.com/archives/C049HHMV9SM/p1708467284842419?thread_ts=1708436683.366409&cid=C049HHMV9SM) it sounds like we're simply removing the textheadline style from the text to match that of the [display name message](https://github.com/Expensify/App/blob/72bdedb226d0813a68e2b8caa909194064ed92a9/src/pages/settings/Profile/DisplayNamePage.js#L100) (which has none)?

**Comment by dannymcclain** [comment] 2024-02-23 14:13
> it sounds like we're simply removing the textheadline style from the text to match that of the display name message (which has none)


That's correct! It should end up looking something like this
![CleanShot 2024-02-23 at 08 12 31@2x](https://github.com/Expensify/App/assets/7516624/f6fa2f73-a745-4031-a04a-4a164156ce61)

**Comment by hayata-suenaga** [comment] 2024-03-04 21:54
payment should be issued after the regression period is over

**Comment by slafortune** [comment] 2024-03-06 15:25
@s77rt can you please complete the check list?

 1. The PR that introduced the bug has been identified. Link to the PR:
 2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
 3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 
 4. Determine if we should create a regression test for this bug:
 5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again:

**Comment by s77rt** [comment] 2024-03-06 23:23
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/33897
- The offending PR has been commented on: https://github.com/Expensify/App/pull/33897#discussion_r1515277961
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No, this kind of bug is not something that's likely to resurface

**Comment by s77rt** [comment] 2024-03-06 23:23
@slafortune Done ^

**Comment by slafortune** [comment] 2024-03-08 13:39
Great!  Thanks @s77rt 👍 
No regression test
Both @s77rt and @shahinyan11 are paid
Closing

**Closed by slafortune** 2024-03-08 13:39 UTC
Labels: External, Weekly, Bug
