### ISSUE TITLE
[HOLD for payment 2023-10-24] [$125] Bank Account -  Some menu items left icon alignment is broken

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29650] opened 2023-10-16 01:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697378426782819

## Action Performed:
1. Go to any workspace -> Click Bank account
2. On the bank account step observe the left icon for
     - Connect online with plaid
     - Connect manually

## Expected Result:
 Left icon should be aligned on same place for all menu items

## Actual Result:
 Left icon is misaligned for connect manually button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 
![Screenshot_1697378579 (1)](https://github.com/Expensify/App/assets/93399543/f0618cf1-6c9d-4eb4-b1c1-7c971ffd0e6c)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 
![Screenshot_1697378971 (1)](https://github.com/Expensify/App/assets/93399543/950276c2-c937-4a6d-950a-31acefb311b7)

</details>

<details>
<summary>iOS: Native</summary>

 
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-10-15 at 19 31 24 (1)](https://github.com/Expensify/App/assets/93399543/ac99db6c-b369-4b8b-8d43-196a85ef9242)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-10-15 at 19 33 37 (1)](https://github.com/Expensify/App/assets/93399543/4d8bca59-411e-423f-9356-dbee8aa116ba)

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/d2f175d8-80e4-47f4-bc6b-4efc92f3de3a

</details>

<details>
<summary>MacOS: Desktop</summary>

 
![Screenshot 2023-10-15 at 19 31 19 (1)](https://github.com/Expensify/App/assets/93399543/294907e5-1fc2-4665-b3e8-fa7f60a58615)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-10-16 01:12
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Menu items left icon alignment is not consistent
### What is the root cause of that problem?
It seems a regression from [PR](https://github.com/Expensify/App/pull/26406) where left padding has been removed from `cardMenuItem` which we have used for this kind of buttons. Earlier we had the left padding of 8px.
https://github.com/Expensify/App/pull/26406/files#diff-8ab8ba45ab927f1430b8d1209d187e003a9cdfe476f809e4483ef64cdba253ebL3080
https://github.com/Expensify/App/blob/0b06446b0bd420550ccc9896bd0f9bf8d57e90e2/src/styles/styles.ts#L3143-L3144
### What changes do you think we should make in order to solve the problem?
Correct the `paddingLeft` with 8px like the same it was earlier. Bcoz I see that class isn’t used in the offended PR. Might be changed unintentionally. cc: @pac-guerreiro
https://github.com/Expensify/App/assets/14358475/594432d1-70d6-4188-9093-6a52863fc471

**Comment by mountiny** [comment] 2023-10-16 13:50
Creating the PR

**Comment by mountiny** [comment] 2023-10-16 14:24
PR merged and being CPed. I have used @Pujan92 solution

I propose to pay $100 altogether to @Pujan92 for reporting and for the fix I have used from him as he was not able to raise PR quickly.

**Comment by mountiny** [comment] 2023-10-16 14:26
<img width="372" alt="image" src="https://github.com/Expensify/App/assets/36083550/8681e0f1-962a-4795-bc48-fb8ca594aed9">
 fixed

**Comment by puneetlath** [comment] 2023-10-17 17:22
Looks like we just need payment for @Pujan92 for bug reporter on this one.

**Comment by mountiny** [comment] 2023-10-23 12:28
No checklist are needed here as a deploy blocker the offending pr has been identified and we do not need regression test for this one either imho

**Comment by puneetlath** [comment] 2023-10-25 13:22
So only the bug reporter needs payment here, is that right @mountiny?

**Comment by mountiny** [comment] 2023-10-25 13:50
Correct @Pujan92 $50

**Comment by puneetlath** [comment] 2023-10-25 15:38
@Pujan92 sent you an offer here: https://www.upwork.com/nx/wm/offer/27370555

Please comment on this issue once you've accepted it.

**Comment by puneetlath** [comment] 2023-10-25 15:44
Thanks for the link. Paid!

**Closed by puneetlath** 2023-10-25 15:44 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
