### ISSUE TITLE
[$250] Android - For task creation with 1:1 user, notifications received 3 times

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49425] opened 2024-09-18 20:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4980313
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: User A ( redmi note 10s android 13 )and user B(samsung galaxy m21, android 12) logged in 2 devices. Keep notifications enabled in devices
1. Launch app
2. Open 1:1 dm with user B
3. Create a task
4. Note in other device, user B receives 3 times notification.

## Expected Result:
For task creation with 1:1 user, notifications must not be received 3 times.

## Actual Result:
For task creation with 1:1 user, notifications received 3 times.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3e8b68ca-0d99-4fb9-92ac-7568c71880f6

https://github.com/user-attachments/assets/d388a1e0-c911-437d-8a53-f4c36c93209d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838631615739816293</li>
        <li>Upwork Job ID: 1838631615739816293</li>
        <li>Last Price Increase: 2024-09-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by IuliiaHerets** [comment] 2024-09-18 20:30
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment] 2024-09-24 17:28
Unfortunately, I can't reproduce this with browserstack :(

**Comment by zanyrenney** [comment] 2024-09-24 17:28
I'm going to add the external label and hope that one of our contributors can verify this.

**Comment by zanyrenney** [comment] 2024-09-26 11:14
Just an FYI I'll be OOO until Tuesday 1st, please reapply the bug label if this needs urgent action in my absence. Otherwise I will get to it when I return. Thanks!

**Comment by s77rt** [comment] 2024-09-27 18:18
Still looking for proposals

**Comment by rezkiy37** [comment] 2024-09-30 11:27
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by s77rt** [comment] 2024-09-30 14:03
@zanyrenney Please assign @rezkiy37

**Comment by rezkiy37** [comment] 2024-10-01 10:30
Hi!
I've investigated the bug. I can confirm that it is replicable for **Android** and **IOS** native. By the way, I receive notifications twice not 3 times. As I see from the network from the sending side, it works properly and sends one request per task. So to recap it is a backend issue or **FCM** and **APNs**. I think some internal engineer needs to debug how often the backend asks for notifications. 

<details><summary>Details</summary>
<p>


https://github.com/user-attachments/assets/1db5da8b-54cb-4b31-abcc-fbbfcca8de0e

![Android](https://github.com/user-attachments/assets/86cb948a-deff-491f-86bf-b7e5bf1b992c)

![IMG_9681](https://github.com/user-attachments/assets/f8189804-5cde-43e2-83cf-d42bf5da488c)

<img width="1201" alt="Screenshot 2024-10-01 at 12 27 46" src="https://github.com/user-attachments/assets/d72c0a18-119f-4a80-9bb5-663ad2e62a26">

</p>
</details>

**Comment by s77rt** [comment] 2024-10-01 18:27
🎀 👀 🎀 This one seems `Internal` (Pusher notifications)

**Comment by luacmartins** [comment] 2024-10-02 18:34
@arosiclair @Julesssss @cristipaval would either of you be able to look into this since it seems related to reliable notifications?

**Comment by Julesssss** [comment] 2024-10-03 07:54
I can, though it'd have to be prioritised behind other issues.

**Comment by luacmartins** [comment] 2024-10-03 13:52
Thanks! Assigned you to it

**Comment by Julesssss** [comment] 2024-10-03 14:07
Just FYI I can't get to this for a few weeks. I'm going to unassign as I can't update this daily.

**Comment by arosiclair** [comment] 2024-10-03 16:24
I don't have the bandwidth to pick this either atm. Here's what I'd do though:

1. Reproduce the issue
2. Take a look at both [ReportUtils::sendPushNotification](https://github.com/Expensify/Web-Expensify/blob/4a185020bea73fec652e60fa62eef2bc3350b8c6/lib/ReportUtils.php#L2588) in Web-E and [ReportAction::buildOnyxUpdatesForNewAction](https://github.com/Expensify/Auth/blob/21d38e5b475c19f0d8e94847a02c54175b304df5/auth/lib/ReportAction.cpp#L1827) in Auth.
    - The Web-E function is the old, deprecated way. Auth is the new preferred flow
    - If both of these are being called for Task actions, it will produce duplicate push notifications
3. Fix the duplication and be sure to cover this with a new test in [MobilePushNotificationsTest](https://github.com/Expensify/Web-Expensify/blob/56be9502c01a286301252eae1d05a96e0e3ae4d4/_tests/integration/lib/MobilePushNotificationsTest.php)

**Comment by s77rt** [comment] 2024-10-10 22:43
Still waiting for someone to pick this up

**Comment by s77rt** [comment] 2024-10-14 18:44
Same ^

**Comment by s77rt** [comment] 2024-10-18 18:21
Still `Internal`. @arosiclair did you get a chance to look into this one?

**Comment by mvtglobally** [comment] 2024-10-19 03:50
Issue not reproducible during KI retests. (First week)

**Comment by rezkiy37** [comment] 2024-10-21 11:21
I've retested the bug as well. It is not replicable anymore.

<details><summary>Details</summary>
<p>


https://github.com/user-attachments/assets/d608c963-c89a-415a-84bc-22869fab7b38



</p>
</details> 

cc @s77rt

**Comment by rezkiy37** [comment] 2024-10-21 11:21
No overdue.

**Comment by luacmartins** [comment] 2024-10-21 14:54
We can close this issue since we can't reproduce it anymore.

**Closed by luacmartins** 2024-10-21 14:54 UTC
Labels: Daily, Internal, Overdue, Bug, Hot Pick
