### ISSUE TITLE
[$500] Task – Task details page becomes unread in LHN when edit task Offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35575] opened 2024-02-01 17:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4262665
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a task in a group chat and open Task details
4. Go Offline and edit task name, description, assignee
5. Find Task details in the LHN and go back Online (don’t click on the Task details page)

## Expected Result:
Task details page is read in LHN

## Actual Result:
Task details page becomes unread in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c420048e-c8b4-4151-8500-5259cd960625

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019a8f6449e90ae629</li>
        <li>Upwork Job ID: 1753102600156340224</li>
        <li>Last Price Increase: 2024-02-08</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2024-02-06 00:56
Thoughts on this connection to #vip-vsb @quinthar? Waiting for proposals either way

**Comment by greg-schroeder** [comment] 2024-02-09 03:06
Still awaiting proposals

**Comment by greg-schroeder** [comment] 2024-02-12 21:41
Same as above

**Comment by bi-kash** [comment] 2024-02-13 12:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After editing a task offline, returning online doesn't mark the Task details page as read in the LHN as expected.

### What is the root cause of that problem?
The issue stems from the fact that the lastReadTime (the time when the user reads the last message) for a task doesn't get updated when offline. The condition for determining unread status is the same for both task editing and general message updates.

``` JavaScript
function isUnread(report: OnyxEntry<Report>): boolean {
    if (!report) {
        return false;
    }

    // lastVisibleActionCreated and lastReadTime are both datetime strings and can be compared directly
    const lastVisibleActionCreated = report.lastVisibleActionCreated ?? '';
    const lastReadTime = report.lastReadTime ?? '';
    const lastMentionedTime = report.lastMentionedTime ?? '';

    // If the user was mentioned and the comment got deleted the lastMentionedTime will be more recent than the lastVisibleActionCreated
    return lastReadTime < lastVisibleActionCreated || lastReadTime < lastMentionedTime;
}
```
### What changes do you think we should make in order to solve the problem?
To address the issue, we can add a condition in the isUnread function: if lastActorAccountID is the same as currentUserAccountID, then return false.

### What alternative solutions did you explore? (Optional)
We can update lastReadTime even when offline. However, I think above solution is more robust..

**Comment by bi-kash** [comment] 2024-02-13 12:19
Contributor details
Your Expensify account email: bkash.timsina@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01113b8ddddd2dbada

**Comment by greg-schroeder** [comment] 2024-02-16 05:23
Bump @tylerkaraszewski to confirm the contributor assignment [here](https://github.com/Expensify/App/issues/35575#issuecomment-1943540939), thanks!

**Comment by bi-kash** [comment] 2024-02-17 10:16
The pull request (PR) is expected to be ready for review by this upcoming Monday.

**Comment by bi-kash** [comment] 2024-02-19 05:41
PR is ready: https://github.com/Expensify/App/pull/36762

**Comment by mvtglobally** [comment] 2024-02-21 02:29
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment] 2024-02-21 02:55
Seems to be confirmed @cubuspl42

**Comment by cubuspl42** [comment] 2024-02-21 08:34
Alright, we should close this issue and the PR then.

Per the process, in such (rare) cases, ["payment is due for C+ and the contributor"](https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit#bookmark=id.2pc73hazgt7h).

**Comment by bi-kash** [comment] 2024-02-29 15:53
If it's not too much trouble, could we please finish the remaining steps for this issue and close it? I've noticed that the contribution guidelines specifically mention that new contributors should focus on one problem at a time. Will this open issue that is assigned to me prevent me from submitting proposals for other jobs?

**Comment by cubuspl42** [comment] 2024-03-01 09:42
@bi-kash In practice, we're not too strict about that rule. If your capacity is not affected (and here it's not), feel free to apply to another issue. It's good to remember about the common sense.

**Comment by cubuspl42** [comment] 2024-03-01 09:43
> During the work on the PR, we found out that the issue is no longer reproducible, possibly because of the backend changes.
> 
> @lanitochka17 @greg-schroeder Would you confirm this?

Bump

**Comment by greg-schroeder** [comment] 2024-03-02 00:21
Confirmed. Let me recap what happened here to consider potential payments.

**Comment by greg-schroeder** [comment] 2024-03-02 00:21
@bi-kash you're free to take on something else, this issue is considered resolved for your purposes

**Comment by greg-schroeder** [comment] 2024-03-02 00:28
I paid @cubuspl42 and sent an offer to @bi-kash - once you accept, I'll send you a payment. Thanks for your effort even though this didn't go forward. You can close the PR if we're finished there.

**Closed by greg-schroeder** 2024-03-02 00:28 UTC
Labels: Reviewing, External, Weekly, Bug
