### ISSUE TITLE
[PAYMENT - 02-07 - $250] Safari - Command+X does not work in chat compose box (but works fine in search) 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14528] opened 2023-01-24 23:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report/chat
3. Write any text (but don't press send)
4. Select the text and use Command+X 

## Expected Result:
It should cut the text (works on chrome)

## Actual Result:
It does nothing on Safari (Mac) and just produces a beep/pop sound

## Workaround:
Unknown

## Platforms:
- [ ] MacOS  / Safari

**Version Number:** Production v1.2.58-4, Staging v1.2.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214442451-63dddb54-2453-4e48-8edc-644722dd175f.mov

https://user-images.githubusercontent.com/43996225/214442561-4bd46aab-5362-4b1f-8062-8bc91bc2ddd3.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674325552276489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01930fb51d524ae477</li>
        <li>Upwork Job ID: 1618081755781881856</li>
        <li>Last Price Increase: 2023-01-25</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-01-25 02:57
Tested on a newer version, can confirm I only hear a "beep" sound:

![image](https://user-images.githubusercontent.com/30815269/214469956-81033dec-118a-4f4e-ba26-03d16e4579c3.png)

Also logged into Staging (v1.2.59-0) and can see the same issue.

[This is a pretty commonly used command](https://support.apple.com/en-au/HT201236#:~:text=Command%2DX%3A%20Cut%20the%20selected,the%20current%20document%20or%20app.), so my guess is a bug?

**Comment by wildan-m** [comment] 2023-01-25 04:37
Seems my PR will also resolve this issue.

The root cause is the same. Selection lost during `setHTMLSync` execution.

https://github.com/Expensify/App/pull/14506

cc: @youssef-lr, @mollfpr

**Comment by mollfpr** [comment] 2023-01-25 04:40
@wildan-m Nice catch! Yes, it's not reproduced in your PR.

https://user-images.githubusercontent.com/25520267/214481263-2f7d580e-2be1-4634-8d8a-723579eb8908.mov

**Comment by jliexpensify** [comment] 2023-01-25 04:52
Awesome, so just a reporting bonus to @dhanashree-sawant then! Thanks @wildan-m and @mollfpr !

**Comment by jliexpensify** [comment] 2023-01-26 21:35
Removed Upworks job + Help Wanted label for now, just awaiting the PR.

**Comment by jliexpensify** [comment] 2023-01-29 23:27
PR deployed on January 28th.

@dhanashree-sawant - I'll send you an Invite on Upworks for payment on the 4th of Feb.

**Comment by ctkochan22** [comment] 2023-02-01 18:00
Not overdue i believe

**Comment by jliexpensify** [comment] 2023-02-01 21:28
Correct, this issue will be resolved with a recently deployed PR (I changed the payment date) - I'll pay out then.

**Comment by jliexpensify** [comment] 2023-02-01 21:33
@wildan-m - just tested this bug in the newest version, and it's _* chef's kiss *_ Nice one!

**Comment by wildan-m** [comment] 2023-02-01 23:46
@jliexpensify great! Thanks for letting me know

**Comment by jliexpensify** [comment] 2023-02-07 01:58
Will pay out once @dhanashree-sawant accepts :)

**Comment by dhanashree-sawant** [comment] 2023-02-07 02:15
@jliexpensify Thanks, offer accepted

**Comment by jliexpensify** [comment] 2023-02-07 02:29
Paid, and job closed. Thanks everyone!

**Closed by jliexpensify** 2023-02-07 02:29 UTC
Labels: External, Daily, Bug
