### ISSUE TITLE
[Payment 2024-10-10] [$250] Chat - In mweb, deleting emoji+text in offline, emoji not striked but striked in Android

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49053] opened 2024-09-12 10:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: Go offline
1. Launch both mweb and Android
2. Open a chat
3. Paste in composer 🧐 hai
4. Send the message
5. Long press the message and tap delete comment
6. Confirm delete
7. Note the appearance of strike down text in both mweb and Android

## Expected Result:
Deleting emoji+text in offline, behavior must be same in both mweb and Android.

## Actual Result:
In mweb, deleting emoji+text in offline, emoji is not striked through but in Android it is striked.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7085c28c-65b0-48ef-896c-fef455d08c9b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837299922286222160</li>
        <li>Upwork Job ID: 1837299922286222160</li>
        <li>Last Price Increase: 2024-09-21</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 104110872</li>
</ul></li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-09-12 10:23
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by c3024** [comment] 2024-09-15 17:49
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Emoji is not struck through in web apps when a comment with both emoji and text is deleted offline.
### What is the root cause of that problem?
When the comment only contains emojis, we add the `line-through` style here:
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/home/report/comment/TextCommentFragment.tsx#L92
So it works fine when the comment contains only emojis.

However, when the deleted message contains both emojis and text, we use `RenderCommentHTML` to show the message, which in turn uses `RenderHTMLSource` from `react-native-render-html`.
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/home/report/comment/TextCommentFragment.tsx#L60-L72
But the custom `EmojiRenderer` is not passed the `style` prop here:
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/components/HTMLEngineProvider/HTMLRenderers/EmojiRenderer.tsx#L6
So, the `textDecorationStyle` is not applied to the `EmojiWithTooltip`, and consequently to the emoji.

This works fine on native apps because the parent style still has the correct `textDecorationStyle`, and this is correctly inherited in native apps, which use only the `Text` element here:
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/components/EmojiWithTooltip/index.native.tsx#L5
However, in the `index.tsx`, there are interspersed `View` components between the `Text` and its parent here:
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/components/EmojiWithTooltip/index.tsx#L18-L36
As a result, the `textDecorationStyle` is not correctly inherited in non-native apps.
>Text style inheritance is only available within Text subtrees. The consequence of this is that default text styles cannot be set on View for an entire subtree. ["](https://necolas.github.io/react-native-web/docs/styling/)
### What changes do you think we should make in order to solve the problem?
We should pass the `style` prop to `EmojiRenderer`, add necessary styles, and pass them to `EmojiWithTooltip` here:
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/components/HTMLEngineProvider/HTMLRenderers/EmojiRenderer.tsx#L6-L11
like this:
```js
function EmojiRenderer({style, tnode}: CustomRendererProps<TText | TPhrasing>) {
    const styles = useThemeStyles();
    const mergedStyle = {...style, ...'islarge' in tnode.attributes ? styles.onlyEmojisText : {}};
    return (
        <EmojiWithTooltip
            style={[mergedStyle, styles.cursorDefault, styles.emojiDefaultStyles]}
```
### What alternative solutions did you explore? (Optional)

**Comment by strepanier03** [comment] 2024-09-17 23:35
Okay, got this tested and easy to repro. The question is what do actually want because I think just the word being strikes is expected, but I think them both striked looks better. 

I'll confirm quick.

**Comment by strepanier03** [comment] 2024-09-21 01:16
Okay, this is good to move forward. 

The end goal is consistency and the majority int he discussion voted for fully struck through, emoji and text. 

Let's move forward with making that consistent across devices. If there is a limitation let's discuss it.

**Comment by strepanier03** [comment] 2024-09-21 01:18
**Heads up**

I am out of the office from September 21 to October 3. If during that time BZ action is needed please post in Slack to ask for a hand getting it done. I'll check in when I'm back online on the 3rd and get caught up. 

Thanks everyone!

**Comment by sobitneupane** [comment] 2024-09-24 12:53
Thanks for the [proposal](https://github.com/Expensify/App/issues/49053#issuecomment-2351699098) @c3024 

[Proposal](https://github.com/Expensify/App/issues/49053#issuecomment-2351699098) from @c3024 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by strepanier03** [comment] 2024-10-10 15:17
### Payment Summary

**Comment by strepanier03** [comment] 2024-10-10 15:22
@sobitneupane - I'll check back later today for the checklist and once it's done I'll take the payment summary off hold.

**Comment by strepanier03** [comment] 2024-10-10 15:22
@c3024 - I paid your contract and closed it in Upwork. Thank you!

**Comment by strepanier03** [comment] 2024-10-14 19:03
@sobitneupane - friendly bump on the checklist [here](https://github.com/Expensify/App/issues/49053#issuecomment-2390449303) so I can finish this up.

**Comment by strepanier03** [comment] 2024-10-16 18:30
@sobitneupane I set ownership of this on you. Once you do the checklist please set it back to me and I'll remove the hold from the payment summary.

**Comment by sobitneupane** [comment] 2024-10-21 08:06
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/37814
> * [ ]  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/37814#issuecomment-2425922575
> * [ ]  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [ ]  [@sobitneupane / @c3024] Determine if we should create a regression test for this bug.

Yes.
> * [ ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2024-10-21 08:08
Regression Test Proposal
- Go offline
- Send a message with emoji (for example, 😄 hello) in any chat
- Delete the message
- Verify that the emoji is struck through

Do we agree 👍 or 👎

**Comment by strepanier03** [comment] 2024-10-21 20:56
https://github.com/Expensify/Expensify/issues/437795

**Comment by strepanier03** [comment] 2024-10-21 20:57
@sobitneupane - Payment summary is posted [here](https://github.com/Expensify/App/issues/49053#issuecomment-2405412607). 

I removed the hold and made the reg test GH so you're good to request payment.

**Closed by strepanier03** 2024-10-21 20:57 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-10-23 10:12
$250 approved for @sobitneupane
