### ISSUE TITLE
[HOLD for payment 2024-01-18] Fix FlatList jumping

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#23220] opened 2023-07-19 23:41 UTC
# Part of the _Comment Linking_ project
Main issue: https://github.com/Expensify/App/issues/20282
Doc section: https://docs.google.com/document/d/1v-ZaIRTZL5LIsyPWB0IopBNNgCajf5WC1OA8cVKtd8I/edit#bookmark=id.bry74gx446k1
Project: [Comment Linking](https://github.com/orgs/Expensify/projects/62/views/1) 

# <Feature Description>
Address the noticeable jumps in the list when scrolling and simultaneously adding items from the bottom of the list. This fix will be applied on both native and web sides.

# Manual Test Steps
TBD

#Automated Tests
TBD – probably none

**Comment by roryabraham** [comment] 2023-07-19 23:41
cc @perunt

**Comment by perunt** [comment] 2023-07-25 17:11
I re-tested this with a large dataset, and I can confirm that it is performing significantly better. I noticed that in version 0.72.1, the react-test-renderer was removed from the runtime, which seems to have improved things. When using a single item render per batch, it functions kinda ok(similar to previous performance levels). As such, I don't believe we need to make any changes here. And we can hop on the next steps.
Here [video](https://www.dropbox.com/scl/fi/p43f0moq7bunfx781hrs1/Screen-Recording-2023-07-25-at-18.36.20.mov?rlkey=qbzisxdkk80xf0r2yhat7rbk8&dl=0)
@roryabraham , wdyt?

**Comment by roryabraham** [comment] 2023-07-26 01:20
Sounds good. Hopefully we'll get much better performance (and no scroll-jumps) when we integrate WishList

**Comment by thienlnam** [comment] 2023-11-10 03:58
We ended up having to revert this

**Comment by dangrous** [comment] 2023-11-10 18:35
Here's one of the regressions it caused - https://github.com/Expensify/App/issues/31143 - should I keep that issue open, or would you prefer to handle it on this one? Not quite sure what our default process is for that

**Comment by thienlnam** [comment] 2023-11-13 01:02
Since the issue no longer exists we can close it, we'll just add a note on the next PR that need to make sure it doesn't reproduce that

**Comment by thienlnam** [comment] 2023-11-19 18:34
Oops, didn't mean to close - we're still working on adding a PR here

**Comment by perunt** [comment] 2024-02-06 09:49
Hey, it was merged a while ago. There will be another enhancement for the scrolling experience, but the original issue has been fixed. I guess we can close it

**Closed** 2024-02-06 20:26 UTC
Labels: Engineering, Weekly, Awaiting Payment
