### ISSUE TITLE
[HOLD for Payment 2024-04-30] [$500] BA - Disconnected bank account is still displayed on bank account preview on Workflows page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39439] opened 2024-04-02 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4469599
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: user must be logged in, have created a collect workspace and have connected a bank account.
1. Go to Workspace > Workflows > Bank account.
2. Tap on "Disconnect bank account" and confirm.
3. Tap on the back arrow.
4. Verify the bank account is still displayed on the bank account preview.
5. Go to Settings > Wallet.
6. Delete the bank account.
7. Go to Workspace > Workflows.
8. Verify the bank account is still displayed on the bank account preview.

## Expected Result:
The bank account should not be displayed on the preview after the account has been disconnected.

## Actual Result:
The bank account is still displayed on the preview after the account has been disconnected.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2cd91dc4-d301-4ec5-a1c6-48709368cfe5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018935ae4d1df3ea3c</li>
        <li>Upwork Job ID: 1775552022142980096</li>
        <li>Last Price Increase: 2024-04-10</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by kbecciv** [comment] 2024-04-02 20:29
Linking closed and fixed  KI https://github.com/Expensify/App/issues/38200

**Comment by hayata-suenaga** [comment] 2024-04-02 22:56
@kbecciv, am I correct to understand that the fix for this issue has been deployed to production in the PR you linked and the issue is no longer reproducible both on staging or production?

The linked PR appears to have been deployed to production about 11 hours ago. I don't know why this issue was detected on staging about 2 hours ago.

**Comment by hayata-suenaga** [comment] 2024-04-02 23:07
[confirmed that the issue is not reproducible](https://expensify.slack.com/archives/C02NK2DQWUX/p1712099222568989?thread_ts=1712098717.547699&cid=C02NK2DQWUX)

**Comment by kavimuru** [comment] 2024-04-03 00:35
@hayata-suenaga Tester reproduced this bug.


https://github.com/Expensify/App/assets/43996225/da557bba-8d6a-404c-a75d-1e83e802b2c2

**Comment by nkdengineer** [comment] 2024-04-04 08:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The bank account is still displayed on the preview after the account has been disconnected.

### What is the root cause of that problem?
The workspace workflows page relies on the `policy?.achAccount` [here](https://github.com/Expensify/App/blob/ae6cc4927ce57e5be59e024109436909ed7e1bb5/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L87) do decide whether to show the bank name in the bank account preview part.

However, when we disconnect the bank account, we're not setting `achAccount` to `null` in optimistic data [here](https://github.com/Expensify/App/blob/ae6cc4927ce57e5be59e024109436909ed7e1bb5/src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.ts#L40).

So the bank account preview will still show.

### What changes do you think we should make in order to solve the problem?

Set `achAccount` to `null` in optimistic data [here](https://github.com/Expensify/App/blob/ae6cc4927ce57e5be59e024109436909ed7e1bb5/src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.ts#L40), and potentially restore it in failureData.

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-04-08 12:28
@rayane-djouah In your video the bank account is still displayed in the background there, after you confirm bank account disconnection. If you dismiss the RHN right after disconnecting the bank account, you'll see that the bank account persist in `Make or track payments` for a long time until the back-end request is successful. That's the bug.

Let me know if anything needs to be clarified 👍 

![Screenshot (4)](https://github.com/Expensify/App/assets/161821005/80903021-8b3f-4024-a688-c56895e54d2a)

**Comment by nkuoch** [comment] 2024-04-10 12:32
Sounds good to set achAccount to null optimistically as [nkdengineer](https://github.com/nkdengineer) is [proposing](https://github.com/Expensify/App/issues/39439#issuecomment-2036576092 )

**Comment by nkdengineer** [comment] 2024-04-15 02:55
Will open PR today.

**Comment by nkdengineer** [comment] 2024-04-15 08:54
@rayane-djouah The PR is [here](https://github.com/Expensify/App/pull/40226).

**Comment by sakluger** [comment] 2024-04-30 17:55
Sent an offer to @nkdengineer: https://www.upwork.com/nx/wm/offer/102102495/

**Comment by sakluger** [comment] 2024-05-02 00:53
@nkdengineer please let me know once you've accepted the offer. @rayane-djouah bump on the BZ checklist.

**Comment by sakluger** [comment] 2024-05-02 16:05
I completed payment to @nkdengineer. Now just waiting on the BZ checklist before we can close the issue.

**Comment by sakluger** [comment] 2024-05-03 19:27
Thanks!

**Closed by sakluger** 2024-05-03 19:27 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
