### ISSUE TITLE
Dev - Missing LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26311] opened 2023-08-30 17:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login the app, LHN is not observed
## Expected Result: 
LHN is display
## Actual Result: 
LHN is not display

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-08-31 at 00 07 12](https://github.com/Expensify/App/assets/43996225/43cea411-3dbb-47bf-91a4-3ba6e472daf0)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693415219465709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-08-30 18:15
I cannot reproduce this issue.

**Comment by luacmartins** [comment] 2023-08-30 18:17
Closing.

**Closed by luacmartins** 2023-08-30 18:17 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
