### ISSUE TITLE
[$500] The updated amount is not copied to clipboard.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26664] opened 2023-09-04 13:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money
2. Open IOU and change amount.
3. Click on Copy to clipboard on IOU item.
4. Paste to chat.
## Expected Result: 
The updated amount should appear.
## Actual Result: 
The updated amount does not appear.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/52d27192-1b42-47d6-a76a-06ea16f67a69

https://github.com/Expensify/App/assets/43996225/dd023c59-0db7-4089-93b9-42c6cd51d213

**Expensify/Expensify Issue URL:**
**Issue reported by:** @oleksandr-pantsyr
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692986644530329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d2ba9ac8db0e8b1</li>
        <li>Upwork Job ID: 1699071512490926080</li>
        <li>Last Price Increase: 2023-09-05</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-09-04 19:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Modified request amount is not copied to clipboard (side note: neither is the modified description).

### What is the root cause of that problem?
On updating the money request, we only update the `transaction` and create a new `updatedReportAction` in the thread 
https://github.com/Expensify/App/blob/4304851b42882c3e221ebb5d00996ef39cfe704c/src/libs/actions/IOU.js#L982

The message on the original `reportAction` is not updated. While the `copyToClipboard` action copies the action's message here:
https://github.com/Expensify/App/blob/94c20d7af722f9c5c720b4ca1ba0620b90ddfe9d/src/pages/home/report/ContextMenu/ContextMenuActions.js#L190

### What changes do you think we should make in order to solve the problem?
In the IOU.editMoneyRequest, along with 2 existing merge requests, add the following:

```javascript
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${iouReport.reportID}`,
            value: {
                [parentReportAction.reportActionID]: {
                    message: ReportUtils.getIOUReportActionMessage(
                        parentReportAction.originalMessage.IOUReportID,
                        parentReportAction.originalMessage.type,
                        updatedTransaction.modifiedAmount,
                        updatedTransaction.comment.comment,
                        updatedTransaction.modifiedCurrency,
                    ),
                },
            },
        },
```

This will update the message of the original reportAction.

**Note:** This apparently requires updating the `EditMoneyRequest` API handler on BE as well, because the optimistically stored message gets eventually reset to the original one.



### What alternative solutions did you explore? (Optional)

**Comment by alphaboss1104** [comment] 2023-09-04 19:57
This is BE issue. Because when we send the `editMoneyRequst` request to BE, it doesn't return any value to set the `MoneyRequestPreview` 's reportAction.
![image](https://github.com/Expensify/App/assets/137152763/658840f6-e230-4318-ae43-e9031123a0c2)

As I see @paultsimura 's opinion for root cause is correct but his solution isn't enough.
In  his solution he merged only message but we should merge all necessary details.

**Comment by paultsimura** [comment] 2023-09-04 20:41
My proposal fixes the clipboard issue, right what is described in the ticket.

However, I'd like to understand what is the "all necessary details" - from my understanding, the details like `currency`, `description`, `amount` are stored in the `originalMessage`, which should not be modified. And all of that data can (and should) be fetched from the transaction.

> As I see @paultsimura 's opinion for root cause is correct but his solution isn't enough.
> 
> In  his solution he merged only message but we should merge all necessary details.

**Comment by zanyrenney** [comment] 2023-09-05 14:46
Yep, this is reproducible, adding the external label.

**Comment by mountiny** [comment] 2023-09-07 16:26
@parasharrajat thats correct the MoneyRequestAction component is basically just a view for the Transaction which is assocaited with ti and the link is in the message.IOUTransactionID field, this way you can pull the transaction object and get the data you want

**Comment by BhuvaneshPatil** [comment] 2023-09-07 16:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The updated amount is not copied to clipboard

### What is the root cause of that problem?
We are getting the copied text from `html` property but if we debug that, html property shows the previous value
<img width="1169" alt="Screenshot 2023-09-07 at 9 55 17 PM" src="https://github.com/Expensify/App/assets/27822551/ba181aaa-618f-4883-8c31-b36ddbf79662">

That's why we are not getting updated value.

### What changes do you think we should make in order to solve the problem?
To get the value of text correctly we should notice how it's being done in `MoneyRequestPreview`.
We use `getTransactionDetails()` method for getting required fields.
- amount 
- currency
- comment
- merchant
from `transaction`. We have transactionId from `originalMessage`
<img width="380" alt="Screenshot 2023-09-07 at 9 59 56 PM" src="https://github.com/Expensify/App/assets/27822551/06b8f6c4-b861-43a1-a1ae-1953f564baaa">


We can add new check for checking if the action is IOU or not (which is in case of money request preview)
And handle that separately.

More concisely - 
- Create a new method that will give us final string in case of IOU in `ContextMenuAction`

There is another caveat to this, handling in case of description is present.

We need confirmation from expensify how to handle that, current behaviour is `requested ₹343.00 for abdasd`
 
### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2023-09-07 16:38
sure @parasharrajat

**Comment by paultsimura** [comment] 2023-09-07 18:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The modified request amount is not copied to the clipboard.

### What is the root cause of that problem?
On copy-to-clipboard action, we copy only the static `reportAction.message` instead of building it from `transaction`.

### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/94c20d7af722f9c5c720b4ca1ba0620b90ddfe9d/src/pages/home/report/ContextMenu/ContextMenuActions.js#L185

To the chain of if/else, add the following logic:

```js
                } else if (ReportActionsUtils.isMoneyRequestAction(reportAction)) {
                    const transaction = getTransaction(reportAction.originalMessage.IOUTransactionID);
                    const [iouMessage] = ReportUtils.getIOUReportActionMessage(
                        reportAction.originalMessage.IOUReportID,
                        reportAction.originalMessage.type,
                        transaction.modifiedAmount,
                        transaction.comment.comment,
                        transaction.modifiedCurrency,
                    );
                    Clipboard.setString(lodashGet(iouMessage, 'html', ''));
                }
```



### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2023-09-07 18:12
Updated proposal

**Comment by pecanoro** [comment] 2023-09-11 07:58
I am going to close this issue because it's basically the same root cause as https://github.com/Expensify/App/issues/26571 and this was created after.

**Closed by pecanoro** 2023-09-11 07:58 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by BhuvaneshPatil** [comment] 2023-09-11 10:51
@pecanoro This issue is about money request and the other one is about task and the solution is totally different

**Comment by BhuvaneshPatil** [comment] 2023-09-11 10:52
The issue #26571 is possible dupe of https://github.com/Expensify/App/issues/26753

**Comment by pecanoro** [comment] 2023-09-12 04:08
@BhuvaneshPatil It's a regression for the same PR, so we need to solve it in a single PR.
