### ISSUE TITLE
[$500] Login - "Account closed successfully" on login screen not shown for old existing accounts

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32734] opened 2023-12-08 18:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in New Expensify with an old existing account
2. Navigate to Settings > Security > Close account
3. Enter default contact method and close account

## Expected Result:
User should be redirected to the log in page and an "Account closed successfully" message should be displayed below email field

## Actual Result:
User is redirected to the log in page. However, the message indicating account closure is not shown
Notes:
Issue is not reproducible with completely new accounts

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/d347753c-4a0d-4190-8921-a1186cee68f6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c816d72eac6bd533</li>
        <li>Upwork Job ID: 1733187364495233024</li>
        <li>Last Price Increase: 2023-12-08</li>
    </ul>
</details>

**Comment by wlegolas** [comment] 2023-12-09 01:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Login - "Account closed successfully" on login screen not shown for old existing accounts

### What is the root cause of that problem?

The `closeAccount` method is called to a request to close this action, in this code is called the `API.write` method to close this account and after this API request is redirect the user to the sing-in page (`redirectToSignIn` method), when the user is redirected to the sing-in page the request to close the account still in progress, that's the reason that the message is not displayed below the field.

https://github.com/Expensify/App/blob/632c5c6fb416e330cc90878b6258a9b5e23347cb/src/libs/actions/User.js#L49-L74


### What changes do you think we should make in order to solve the problem?

We should change the `closeAccount` to pass to the API a `successData` updating the Onyx state with the information that the account was closed until the request is completed.

For example:

```js
function closeAccount(message) {
    const optimisticData = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM,
            value: {
                success: 'Account closed successful'
            },
        },
    ];
    const successData = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM,
            value: {isLoading: true},
        }
    ];
    const failureData = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM,
            value: {isLoading: false},
        },
    ];
    // Note: successData does not need to set isLoading to false because if the CloseAccount
    // command succeeds, a Pusher response will clear all Onyx data.
    API.write(
        'CloseAccount',
        {message},
        {optimisticData, successData, failureData},
    );
    // Run cleanup actions to prevent reconnection callbacks from blocking logging in again
    redirectToSignIn();
}
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by brunovjk** [comment] 2023-12-11 21:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The current issue involves the delayed display of the "Account closed successfully" message on the login screen after closing an old existing account.

### What is the root cause of that problem?
After calling the [closeAccount ](https://github.com/Expensify/App/blob/632c5c6fb416e330cc90878b6258a9b5e23347cb/src/libs/actions/User.js#L49) API request, the user is redirected to sing-in page.
Upon redirection, the close account request is still in progress.
The backend sends an empty value for `optimisticData.value.success` and then fetch the `successData.value.success`, causing a delay in displaying the success message.

2 - I also notice that upon refreshing the page after closing an account, the "Account closed successfully" message persists.

### What changes do you think we should make in order to solve the problem?

1 - We can modify the `optimisticData.value` to include a success message. This change aims to provide immediate feedback to the user during the transition from optimisticData to successData. Example:

```
        value: {
            success: 'Closing account', // or Account closed successfully
            isLoading: true
        },
```

However, we have a UX problem here, in the transition from `optimisticData` to `successData` for a moment the backend sends an empty value of `closeAccount: {key: ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM},`

https://github.com/Expensify/App/assets/95647348/808d82a5-5619-48d2-9b81-110b24c8a7cf

I believe this is a **backend** issue, as it should pass the value of `optimisticData` and transition to `successData` without problems.

2 - On the firsrt render, check if the account was closed and have success message in Onyx, so we can clear it.
We add this:
```
        // On the firsrt render, check if the account was closed and have success message in Onyx, so we can clear it
        if (!_.isEmpty(props.closeAccount.success)) {
            CloseAccount.setDefaultData();
        }
```

Here:
https://github.com/Expensify/App/blob/632c5c6fb416e330cc90878b6258a9b5e23347cb/src/pages/signin/LoginForm/BaseLoginForm.js#L205

### What alternative solutions did you explore? (Optional)
**Problem:**
Users currently face a non-intuitive experience as they are redirected to the sign-in page before learning about the outcome of closing their account.

**Solution:**
Utilize the existing "Close Account" modal to instantly communicate the closure outcome, streamlining the user experience.

**Comment by abekkala** [comment] 2023-12-13 13:06
@eVoloshchak have you had a moment to review the proposals?

**Comment by abekkala** [comment] 2023-12-13 17:13
@lanitochka17 you created a duplicate. 

You already reported this here first
https://github.com/Expensify/App/issues/32733

Closing this one

**Closed by abekkala** 2023-12-13 17:13 UTC
Labels: External, Daily, Help Wanted, Bug
