### ISSUE TITLE
[$1000] Chat - Composer Not focused when clicking on composer box

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25892] opened 2023-08-24 20:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send a message
3. Click on Edit from the reaction menu
4. Click on the emoji menu in the edit composer
5. Now without closing the emoji box click on the main composer

## Expected Result:
Clicking on the main composer box focuses the composer

## Actual Result:
Clicking on the main composer box focuses on the main composer for a second and then focuses on the edit Composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.57-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4769bf78-138c-49eb-b734-1a87ff23a738

https://github.com/Expensify/App/assets/78819774/1fb3cb4e-2436-41d7-9d85-2a2fa1a3b4e2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692048812228079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161d746e7dbb99cde</li>
        <li>Upwork Job ID: 1695206421110677504</li>
        <li>Last Price Increase: 2023-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26745373</li>
<li>daveSeife | Reporter | 26745374</li>
</ul></li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2023-08-28 06:31
Isn’t this an expected behaviour? When the EmojiPicker is displayed, we do not allow interactions with any other element in Report Screen until it is dismissed. A tap on anywhere else other than the EmojiPicker will hide and bring the focus back on the currently edited message input.

**Comment by MitchExpensify** [comment] 2023-08-30 16:51
@parasharrajat do you still think this is the best course of action here?

> My intuition is asking to hold this issue as we have done for https://github.com/Expensify/App/issues/23403.

**Comment by MitchExpensify** [comment] 2023-09-03 13:17
> I am monitoring the review of the other issue. If it seems that we are not solving this issue there, I will continue here.

This sounds great to me! Thank you

**Comment by MitchExpensify** [comment] 2023-09-06 12:06
Sounds like @tienifr's proposal is updated and ready for you @parasharrajat

**Comment by MitchExpensify** [comment] 2023-09-11 16:58
Friendly bump on an update here @parasharrajat 👍

**Comment by MitchExpensify** [comment] 2023-09-13 19:32
Bump @parasharrajat 🙇

**Comment by MitchExpensify** [comment] 2023-09-14 22:58
I can still reproduce @parasharrajat

**Comment by ilkeruyanik** [comment] 2023-09-17 17:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When emoji picker is closed, text input is focused even if it should not focus.

### What is the root cause of that problem?

EmojiPickerButton Component's onModalHide property sets focus without any condition in ReportActionItemMessageEdit Component, when emoji picker is closed.

### What changes do you think we should make in order to solve the problem?
1. Instead of setting focus directly, we should use ReportActionComposeFocusManager.
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/home/report/ReportActionItemMessageEdit.js#L411-L414

These lines will be changed with
```
onModalHide={() => {
    InteractionManager.runAfterInteractions(() => {
        if (EmojiPickerAction.isEmojiPickerVisible()) {
            return;
        }
        ReportActionComposeFocusManager.focus();
    });
}}
```
We need to use `InteractionManager`, because user may open emoji picker while already open for another edit composer.

2. New property 'onPress' will be added to EmojiPickerButton component. We will send a function for run on onPress.
In this case, we will use it for set `ReportActionComposeFocusManager.onComposerFocus` function. We will need to set `ReportActionComposeFocusManager.onComposerFocus` because user may close emoji picker without focus on edit composer.
```
onPress={() => {
    ReportActionComposeFocusManager.onComposerFocus(() => {
        if (!textInputRef.current) {
            return;
        }

        textInputRef.current.focus();
    });
}}
```
Current action is setting  `ReportActionComposeFocusManager.onComposerFocus`  on onFocus in Composer Component.
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/components/Composer/index.js#L471-L483

### Result

https://github.com/Expensify/App/assets/93402058/61304066-809e-4dd2-935d-e4607fd7af60

This approach is fixing [#27612](https://github.com/Expensify/App/issues/27612) as well as fixing this bug.

**Comment by johnmlee101** [comment] 2023-09-26 05:27
@tienifr do you mind sharing a work-in-progress PR so we can stay up-to-date on progress you're making?

**Comment by MitchExpensify** [comment] 2023-09-30 11:53
Whats the latest here @tienifr ?

**Comment by MitchExpensify** [comment] 2023-10-03 18:37
Bump @tienifr

**Comment by MitchExpensify** [comment] 2024-07-15 22:02
What is the latest here @parasharrajat ?

**Comment by isabelastisser** [comment] 2024-07-18 18:26
Bump @parasharrajat, can you please provide an update? Thanks!

**Comment by isabelastisser** [comment] 2024-08-05 15:55
@tienifr, please provide an update. I will DM you for visibility. Thanks!

**Comment by isabelastisser** [comment] 2024-08-08 17:47
@tienifr @parasharrajat will the PR be merged soon?

**Comment by isabelastisser** [comment] 2024-09-11 20:07
@parasharrajat, any news?

**Comment by isabelastisser** [comment] 2024-09-30 18:48
Payment summary:

- $1000 to @parasharrajat for C+ review - payment `pending` in NewDot.
- $250 to @tienifr for accepted proposal - payment `pending` in NewDot.
- $50 to @daveSeife for bug report - payment in Upwork.

**Comment by isabelastisser** [comment] 2024-09-30 18:49
@parasharrajat, can you please confirm that the payment summary is correct? Thanks!

**Comment by isabelastisser** [comment] 2024-10-04 20:31
@parasharrajat, do we need a regression test?

**Comment by JmillsExpensify** [comment] 2024-10-05 10:56
Do we have a BZ checklist for this issue?

**Comment by JmillsExpensify** [comment] 2024-10-05 11:00
Sorry I'm unable to, as that would fail our financial controls.

**Comment by JmillsExpensify** [comment] 2024-10-05 17:47
Thanks! $1,000 approved for @parasharrajat

**Comment by isabelastisser** [comment] 2024-10-07 12:54
@JmillsExpensify:

> $1000 to @tienifr for accepted proposal - payment `PENDING` in NewDot.

**Comment by isabelastisser** [comment] 2024-10-07 12:55
@johnmlee101, can you please review the test proposal when you have a chance? Thanks!

https://github.com/Expensify/App/issues/25892#issuecomment-2395067030

**Comment by johnmlee101** [comment] 2024-10-07 15:04
LGTM!

**Comment by isabelastisser** [comment] 2024-10-08 17:34
All set!

**Closed by isabelastisser** 2024-10-08 17:34 UTC
Labels: Reviewing, Engineering, Daily, Internal, Not a priority, Bug

**Comment by isabelastisser** [comment] 2025-01-06 20:12
@tienifr, I sent you an offer in Upwork. Please accept it, and I will process the payment; thanks!

https://www.upwork.com/nx/wm/offer/105584889
