### ISSUE TITLE
 iOS - New Chat - When returning online, messages appear above the avatar and then go down.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14620] opened 2023-01-27 14:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the New Expensify App
2. Disable the internet connection in the device
3. Click on the green + button
4. Click on the "New Chat" option (chat with new user)
5. Send some messages
6. Enable the internet connection

## Expected Result:
Messages should be displayed below the avatar when back online.

## Actual Result:
When returning online, messages appear above the avatar and then go down.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / native

**Version Number:** 1.2.60.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/215112092-b673966f-7ffd-4efc-ab7a-2aaea92ca931.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment] 2023-01-27 23:27
I've reached out for help [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1674862012175599)-- I don't have an iPhone.

**Comment by alexpensify** [comment] 2023-01-27 23:49
Daniel confirmed this is a bug, so assigning it to Engineering to identify if it will be internal or external.

**Comment by alexpensify** [comment] 2023-01-30 18:41
Not overdue, this was assigned on Friday.

**Comment by alexpensify** [comment] 2023-02-01 00:59
@yuwenmemon have you been able to review this one? Let me know if I need to reassign. Thanks!

**Comment by yuwenmemon** [comment] 2023-02-01 19:30
Looking now!

**Comment by yuwenmemon** [comment] 2023-02-01 19:45
Unable to reproduce with the latest updates, closing!

https://user-images.githubusercontent.com/4741899/216147065-fca474f2-6e5c-45be-aa6f-78260ea3481c.mp4

**Closed by yuwenmemon** 2023-02-01 19:45 UTC
Labels: Engineering, Daily, Bug

**Comment by alexpensify** [comment] 2023-02-02 20:02
Thanks!
