### ISSUE TITLE
[$500] [Held requests] Red dot and hold request message do not show up on LHN until after refresh

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36830] opened 2024-02-20 04:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** newfeature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a manual request from any user.
3. Go to request details page.
4. Click 3-dot menu > Hold request.
5. Add a reason and save it.
6. Refresh the page.
## Expected Result:
In Step 5, the LHN preview for the request details report will automatically show red dot and the latest "hold request" message without having to refresh the page
## Actual Result:
In Step 5, the LHN preview for the request details report does not automatically show red dot and the latest "hold request" message. LHN only updates after the report is refreshed in Step 6.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/54160eec-d0c9-493b-b1d8-13e40840a3bd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b065bf0f3c2216e1</li>
        <li>Upwork Job ID: 1759793785828028416</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by MariaHCD** [comment] 2024-02-20 08:33
Related to https://github.com/Expensify/Expensify/issues/274076

I don't think this should block the deploy but would like to confirm with @robertjchen first!

**Comment by sakluger** [comment] 2024-02-20 17:15
Maria asked in Slack here: https://expensify.slack.com/archives/C07J32337/p1708417347484129?thread_ts=1708417025.325189&cid=C07J32337

**Comment by robertjchen** [comment] 2024-02-20 22:03
yep, not a blocker! 👍

**Comment by sakluger** [comment] 2024-02-23 16:58
I added to the Wave 7 project and marked as LOW priority to match the priority of another issue where refreshing is required.

@robertjchen, I have a few questions for you on this one since it sounds like you're working on fixing it yourself.

- Should we leave as a daily, or are you treating this more like a weekly?
- Should we leave @rushatgabhane assigned so they can review your PR once it's ready?

**Comment by robertjchen** [comment] 2024-02-27 01:09
> Should we leave as a daily, or are you treating this more like a weekly?

Weekly is better, since this might be related to violations logic, which is currently a WIP

> Should we leave @rushatgabhane assigned so they can review your PR once it's ready?

I think we can unassign for now while I figure things out 👍

**Comment by sakluger** [comment] 2024-03-06 22:39
@robertjchen any updates?

**Comment by robertjchen** [comment] 2024-03-11 04:13
We'll revisit after partial pay/approve is out, this is now categorized under polish for #wave-collect

**Comment by robertjchen** [comment] 2024-03-12 12:03
Potential fix under review.

**Comment by sakluger** [comment] 2024-03-14 19:03
Thanks! Linking the PR here to make it easier for me to find later: https://github.com/Expensify/Auth/pull/10178.

**Comment by robertjchen** [comment] 2024-03-18 07:30
reliable updates fix should be deployed later today

**Comment by robertjchen** [comment] 2024-03-19 07:07
This is live, can the issue still be reproduced? 🙏

**Comment by sakluger** [comment] 2024-03-20 23:03
I added the retest-weekly label, QA will retest and let us know if it's still reproduceable.

**Comment by mvtglobally** [comment] 2024-03-28 04:29
Issue not reproducible during KI retests. (First week)

**Comment by robertjchen** [comment] 2024-04-01 03:31
Thanks for testing- closing this out for now!

**Closed by robertjchen** 2024-04-01 03:31 UTC
Labels: Engineering, Weekly, Bug, retest-weekly
