### ISSUE TITLE
[$500] Scan-App crashes tapping on scan request split bill amount&merchant

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31226] opened 2023-11-11 11:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap fab
3. Tap request money
4. Tap scan
5. Take a photo
6. Select any 2 users and tap split
7. Tap Add to split
8. Tap split
9. Tap scan split bill created
10. Tap amount
11. Tap merchant

## Expected Result:
Tapping on amount and merchant in scan request split bill, app must not crash.

## Actual Result:
Tapping on amount and merchant in scan request split bill, app crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/4f528627-902f-4c98-bced-27ffc9df3221

https://github.com/Expensify/App/assets/115492554/6a3b5241-a8bc-4b07-ac81-b5ad02f3f7b7

[amtcrasj.txt](https://github.com/Expensify/App/files/13325341/amtcrasj.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2c24def63298e44</li>
        <li>Upwork Job ID: 1723301697309106176</li>
        <li>Last Price Increase: 2023-11-11</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-11-11 11:30
Not reproducible on production.

https://github.com/Expensify/App/assets/115492554/d9bbc3df-9db5-4768-8e0a-3655f3c7bd79

**Comment by DylanDylann** [comment] 2023-11-11 11:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Scan-App crashes tapping on scan request split bill amount&merchant

### What is the root cause of that problem?
In 1 withOnyx we are using the result of the previous field to get the next field 
### What changes do you think we should make in order to solve the problem?
We should separate into 2 withOnyx function

### What alternative solutions did you explore? (Optional)

**Comment by Gensu123** [comment] 2023-11-11 18:04
### **### Problem Statement:**
The Expensify app crashes when tapping on the amount and merchant in a scan request split bill, caused by reportActions being undefined when used in the transaction key within EditSplitBillPage.js.

### Proposed Solution:
Implement a refactor in EditSplitBillPage.js using two separate withOnyx higher-order components. This approach will isolate the reportActions and transaction keys, ensuring that each is properly defined and accessed, thereby resolving the undefined issue leading to the crash.

### Technical Implementation:

Modify the EditSplitBillPage.js file to use two withOnyx components.
Ensure each component separately handles reportActions and transaction keys.
Conduct thorough testing to confirm that the issue is resolved and no new bugs are introduced.


Approach 1: Separating into Two withOnyx Functions
```
import { compose } from 'react-compose';
import { withOnyx } from 'react-native-onyx';
import ONYXKEYS from 'YOUR_PATH_TO_ONYX_KEYS';

export default compose(
    withOnyx({
        reportActions: {
            key: ({route}) => `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${route.params.reportID}`,
            canEvict: false,
        }
    }),
    withOnyx({
        transaction: {
            key: ({route, reportActions}) => {
                const reportAction = reportActions[`${route.params.reportActionID.toString()}`];
                return `${ONYXKEYS.COLLECTION.TRANSACTION}${lodashGet(reportAction, 'originalMessage.IOUTransactionID', 0)}`;
            },
        },
        draftTransaction: {
            key: ({route, reportActions}) => {
                const reportAction = reportActions[`${route.params.reportActionID.toString()}`];
                return `${ONYXKEYS.COLLECTION.SPLIT_TRANSACTION_DRAFT}${lodashGet(reportAction, 'originalMessage.IOUTransactionID', 0)}`;
            },
        },
    })
)(EditSplitBillPage);
```

Approach 2: Using withReportAndReportActionOrNotFound

```
import { compose } from 'react-compose';
import { withOnyx, withReportAndReportActionOrNotFound } from 'react-native-onyx';
import ONYXKEYS from 'YOUR_PATH_TO_ONYX_KEYS';

export default compose(
    withReportAndReportActionOrNotFound,
    withOnyx({
        transaction: {
            key: ({route, reportActions}) => {
                const reportAction = reportActions[`${route.params.reportActionID.toString()}`];
                return `${ONYXKEYS.COLLECTION.TRANSACTION}${lodashGet(reportAction, 'originalMessage.IOUTransactionID', 0)}`;
            },
        },
        draftTransaction: {
            key: ({route, reportActions}) => {
                const reportAction = reportActions[`${route.params.reportActionID.toString()}`];
                return `${ONYXKEYS.COLLECTION.SPLIT_TRANSACTION_DRAFT}${lodashGet(reportAction, 'originalMessage.IOUTransactionID', 0)}`;
            },
        },
    })
)(EditSplitBillPage);
```

**Comment by rlinoz** [comment] 2023-11-13 13:20
Removing the Help Wanted label because it seems that this was fixed reverting a PR here https://github.com/Expensify/App/pull/31231

**Comment by stephanieelliott** [comment] 2023-11-13 15:58
Hey @izarutskaya can you retest this for us please?

**Comment by roryabraham** [comment] 2023-11-14 16:59
Confirmed this issue is fixed: https://expensify.slack.com/archives/C9YU7BX5M/p1699981118689649?thread_ts=1699980359.470499&cid=C9YU7BX5M

**Comment by roryabraham** [comment] 2023-11-14 16:59
No payments due, closing this out

**Closed by roryabraham** 2023-11-14 16:59 UTC
Labels: Reviewing, DeployBlockerCash, External, Engineering, Weekly, Bug
