### ISSUE TITLE
[$500] Dev: Web - Console error after create new account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27963] opened 2023-09-21 20:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new account
2. Check the console

## Expected Result:
It should nor show any console error

## Actual Result:
console error appears (Cannot update a component (`ReportActionsList`) while rendering a different component (`CellRenderer`). )

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev v1.3.72-5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8b7d4137-2b0a-4742-8d9e-07fdf96d3c34

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695200429086149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01900cad6a4d595a0a</li>
        <li>Upwork Job ID: 1704960584429547520</li>
        <li>Last Price Increase: 2023-09-28</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27054099</li>
<li>gadhiyamanan | Reporter | 27054102</li>
</ul></li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment] 2023-09-21 22:21
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
While logging in with a new user, there is an error in console.
### What is the root cause of that problem?
**Cannot Set States During Render**
We are setting one state (setCurrentUnreadMarker) in the usecallback which is getting called during the rendering
https://github.com/Expensify/App/blob/65fd4350829a60399aa36693a4731ac69b8e2b70/src/pages/home/report/ReportActionsList.js#L277-L328
which further gets called over here
https://github.com/Expensify/App/blob/65fd4350829a60399aa36693a4731ac69b8e2b70/src/components/InvertedFlatList/BaseInvertedFlatList.js#L121-L146
### What changes do you think we should make in order to solve the problem?
Instead of calling setCurrentUnreadMarker, we can store this in a variable and assign its value in the usecallback.
## What alternative solutions did you explore? (Optional)
N/A

**Comment by kaushiktd** [comment] 2023-09-22 05:30
### Please re-state the problem that we are trying to solve in this issue.
While logging in with a new user, there is an error in console error appears (Cannot update a component (ReportActionsList) while rendering a different component (CellRenderer). )

### What is the root cause of that problem?

The issue occurred because the renderItem function is called for each item in list during the rendering process. If this function attempts to update the component's state (e.g., setCurrentUnreadMarker) based on conditions during rendering, it can lead to this error.

### What changes do you think we should make in order to solve the problem?

The solution involved using a `useRef` instead of a state variable to store the `currentUnreadMarker`. `useRef` is suitable for storing mutable values that doesn't trigger re-renders when changed.
https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsList.js
 ```
const currentUnreadMarkerRef = useRef(null);

  const renderItem = useCallback(
    ({ item: reportAction, index }) => {
      let shouldDisplayNewMarker = false;

      if (!currentUnreadMarkerRef.current) {
        const nextMessage = sortedReportActions[index + 1];
        const isCurrentMessageUnread = isMessageUnread(reportAction, report.lastReadTime);
        shouldDisplayNewMarker = isCurrentMessageUnread && !isMessageUnread(nextMessage, report.lastReadTime);

        if (!messageManuallyMarked.read) {
          shouldDisplayNewMarker = shouldDisplayNewMarker && reportAction.actorAccountID !== Report.getCurrentUserAccountID();
        }
        const canDisplayMarker =
          scrollingVerticalOffset.current < MSG_VISIBLE_THRESHOLD
            ? reportAction.created < userActiveSince.current
            : true;

        if (!currentUnreadMarkerRef.current && shouldDisplayNewMarker && canDisplayMarker) {
          // Update the currentUnreadMarker using the ref
          currentUnreadMarkerRef.current = reportAction.reportActionID;
        }
      } else {
        shouldDisplayNewMarker = reportAction.reportActionID === currentUnreadMarkerRef.current;
      }

      // ... Rest of your renderItem logic
    },
    [
      report,
      hasOutstandingIOU,
      sortedReportActions,
      mostRecentIOUReportActionID,
      messageManuallyMarked,
      shouldHideThreadDividerLine,
    ]
  );
```

### Video: 
https://drive.google.com/file/d/1Dt797PLuDX18wL6laW8vn9s8-ujpAoh0/view?usp=sharing

**Comment by isabelastisser** [comment] 2023-09-25 15:39
Hey @mananjadhav, please review the proposals above. Thanks!

**Comment by isabelastisser** [comment] 2023-09-27 19:07
Bump @mananjadhav to review the proposals above.

**Comment by mananjadhav** [comment] 2023-10-02 17:06
I'll have them reviewed by tomorrow.

**Comment by mananjadhav** [comment] 2023-10-03 05:08
Thanks for the proposal folks. @saranshbalyan-1234 I am not sure if storing it in a variable will help. @kaushiktd if you look at the history, we earlier had useRef, which we moved to useState. So I don't think we want to go back to the ref.

I liked @tienifr's [proposal](https://github.com/Expensify/App/issues/27963#issuecomment-1730732471) as it retains the useState and covers all the information.

🎀 👀 🎀 C+ reviewed.

**Comment by kaushiktd** [comment] 2023-10-03 05:10
I appreciate your feedback on this, Manan! Thank you.

**Comment by mananjadhav** [comment] 2023-10-09 16:08
@techievivek @isabelastisser, As @tienifr mentioned [here](https://github.com/Expensify/App/pull/28996#issuecomment-1752303266) this isn't reproducible anymore because https://github.com/Expensify/App/pull/28146 resolved this too.

I don't think we need the PR anymore, but we should payout as the PR was ready for review, and we were only waiting for conflicts to be resolved before completing the checklist.

**Comment by techievivek** [comment] 2023-10-18 05:44
Yeah, I agree we should pay for the effort here. 

@tienifr: 500
@mananjadhav: 500
Does that sound correct?

**Comment by mananjadhav** [comment] 2023-10-18 10:14
Thanks @techievivek.

**Comment by JmillsExpensify** [comment] 2023-10-18 17:34
$500 payment approved for @mananjadhav based on summary above.

**Comment by mananjadhav** [comment] 2023-10-19 16:39
@isabelastisser Can you help with the payouts for @tienifr and @gadhiyamanan ?

**Comment by isabelastisser** [comment] 2023-10-19 18:23
I processed the payments in Upwork, all set!

**Closed by isabelastisser** 2023-10-19 18:23 UTC
Labels: Reviewing, External, Weekly
