### ISSUE TITLE
[$1000] Request money - Tab does not update instantly when switching to different tab by swiping

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24422] opened 2023-08-11 12:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money
3. Swipe left or right

## Expected Result:
The tab (Manuel, Scan and Distance) updates instantly after switching to a different tab by swiping

## Actual Result:
It takes a while for the tab to update after switching to a different tab by swiping

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e4e35e64-c510-4890-af7c-22bcb463b25f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1b2ff52ba48a48c</li>
        <li>Upwork Job ID: 1696529022164119552</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-08-15 11:50
@lanitochka17 Is there a beta you need to be part of, for that UI? I can't see that in my test account conor+24537aa@conorpendergrast.com or 20303b@conorpendergrast.com

**Comment by conorpendergrast** [comment] 2023-08-29 14:22
Ah, looks like this is available for @expensify.com users. I've reproduced via Browserstack on my own account now!

**Comment by conorpendergrast** [comment] 2023-08-29 14:24
Contributors, you'll [need the beta for this one](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#working-on-beta-features)!

**Comment by conorpendergrast** [comment] 2023-09-04 08:46
Yeah, nice, smooth as butter. 


https://github.com/Expensify/App/assets/5802477/57aa330f-74bf-440a-bb26-4e2419cb0277


Closing out, thanks @allroundexperts

**Closed by conorpendergrast** 2023-09-04 08:46 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
