### ISSUE TITLE
[$500] Task reports showing in my LHN when marked as complete, even though I never joined them

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36777] opened 2024-02-19 01:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708112484653809

## Action Performed:

1. Create a chat room with workspace visibility
2. Add users A, B and C to the same chat room
3. Have user A create a thread. Make sure users A, B and C join the same thread
4. Have user A assign a task to user B in the thread
5. Have either user A or B mark the task as completed

## Expected Result: 
User C would never see completed tasks show up in the LHN, unless they joined the task

## Actual Result: 
User C sees completed tasks in their LHN for tasks their never joined

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/978774e1-8352-4902-bf0e-5f13f81ef5b7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d155bfb18dccb9fa</li>
        <li>Upwork Job ID: 1759382319530778624</li>
        <li>Last Price Increase: 2024-02-19</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2024-02-19 16:29
Hmm, unable to reproduce.

**Comment by joekaufmanexpensify** [comment] 2024-02-19 16:30
[Discussing ](https://expensify.slack.com/archives/C049HHMV9SM/p1708360222829239?thread_ts=1708112484.653809&cid=C049HHMV9SM)

**Comment by hkopser99** [comment] 2024-02-20 13:18
Hi @joekaufmanexpensify, I tried to visit the 'Discussing' link above but it looks like it's been archived. I am testing this and not only is the completed task visible to my user C but that user can change the task to being marked 'incomplete' (see screenshot attached). Looks like this is a larger issue w/ access to the task for User C in the thread than simply seeing the completed tasks. Would you like me to dig in and come up with a solution or was this resolved in the archived thread in slack?

<img width="743" alt="Screenshot 2024-02-20 at 2 17 21 PM" src="https://github.com/Expensify/App/assets/144170694/0d5c1053-e107-4bf5-9b05-439290432264">

**Comment by joekaufmanexpensify** [comment] 2024-02-20 14:41
Got it. I'll take a closer look today

**Comment by joekaufmanexpensify** [comment] 2024-02-22 16:07
Didn't get to this then but will today

**Comment by joekaufmanexpensify** [comment] 2024-02-23 16:55
I'm going to close this for now since it doesn't appear to be consistently reproducible following the conditions in OP of the issue. If anyone has modified steps they're able to follow to consistently reproduce this please LMK and happy to take another look!

**Closed by joekaufmanexpensify** 2024-02-23 16:55 UTC
Labels: External, Daily, Help Wanted, Bug
