### ISSUE TITLE
[HOLD for payment 2022-12-20] Connect bank account -  The green option row and standard option row don’t line up correctly & icons and text are not aligned

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13318] opened 2022-12-04 23:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to workspace setting 
2. Click `Connect back account`
3. Observe the green option row and standard option row
4. Hover over the `connect manually`

## Expected Result:
There should be no alignment issue and should be full rounded pill shape

## Actual Result:
The green option row and standard option row don’t line up correctly, the icons and text are not perfectly aligned and the hover style should use the full rounded pill shape as well

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** v1.2.36 -1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="955" alt="8" src="https://user-images.githubusercontent.com/43996225/205521912-95605ca8-c982-4a64-902b-0392dcbe334d.png">
<img width="960" alt="7" src="https://user-images.githubusercontent.com/43996225/205521913-ed561f8e-559d-4006-9021-6eab89ff45c5.png">

<img width="364" alt="image (1)" src="https://user-images.githubusercontent.com/43996225/205521945-5c5365dc-5b51-4725-88b6-6207267fa626.png" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/205521943-c751b583-1513-4843-b21f-92f7388245ab.png" width="40%" height="40%">

<img width="793" alt="image (3)" src="https://user-images.githubusercontent.com/43996225/205521946-d7b9e79c-6fcb-40ad-85a2-f72f8908aa1a.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670023956657779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2022-12-05 01:58
### **Proposal**

- define this in `/src/styles/styles.js`:
```diff
    cardMenuButton: {
        height: variables.componentSizeLarge,
        alignItems: 'center',
        borderRadius: variables.buttonBorderRadius,
        paddingHorizontal: 8,
    },
```

- update MenuItem wrapperStyle in [BankAccountStep](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/BankAccountStep.js):
```diff
                        <MenuItem
                            icon={Expensicons.Connect}
                            title={props.translate('bankAccount.connectManually')}
                            disabled={!props.user.validated}
                            onPress={() => BankAccounts.setBankAccountSubStep(CONST.BANK_ACCOUNT.SETUP_TYPE.MANUAL)}
                            shouldShowRightIcon
                            iconFill={themeColors.success}
-                           wrapperStyle={[styles.cardMenuItem]}
+                           wrapperStyle={[styles.cardMenuButton]}
                        />
```
![image](https://user-images.githubusercontent.com/108292595/205532449-fa597895-506e-425d-84a0-6e3145fda673.png)

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-05 08:45
Proposal:-

As we need need to change style  MenuItem hover in this page I suggest it should be done all over the application so we need to change it's style all over the app so it would be safe to restyle `cardMenuItem`  to fix it all over the app.

We can change `cardMenuItem` in `styles.js` to 

      cardMenuItem: { 
           borderRadius: variables.buttonBorderRadius,
           height: variables.componentSizeLarge,
           paddingHorizontal : 8,
           paddingVertical : 8,
          alignItems : "center"     
       },

After Fix:-

**Comment by dangrous** [comment] 2022-12-13 21:58
This is merged and being deployed.

**Comment by dangrous** [comment] 2022-12-13 23:01
@kevinksullivan since this wasn't really a bug, just something that didn't fully change as much as it should have in the redesign, I don't think we need a regression test - that is, this was not a regression, but open to your thoughts (and checks in the checkbox haha)

**Comment by kevinksullivan** [comment] 2022-12-14 23:08
that sounds good to me, and also aligned with shawn's [comment in slack](https://expensify.slack.com/archives/C049HHMV9SM/p1670987737401469?thread_ts=1670972430.685449&cid=C049HHMV9SM).

**Comment by dangrous** [comment] 2022-12-15 06:40
Great! Closing this out since no payment needed.

**Closed by dangrous** 2022-12-15 06:40 UTC
Labels: Reviewing, Weekly, Awaiting Payment, Bug
