### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Profile - Save button is disabled in Display name page in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28148] opened 2023-09-25 14:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27025
## Action Performed:
1. Launch New Expensify app
2. Go offline
3. Go to Settings > Profile > Display name
4. Make some changes

## Expected Result:
User is able to save the changes in offline mode

## Actual Result:
Save button is disabled and user cannot make changes during offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/35622173-11a4-4362-a434-00e417171245

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134557e3ac359277d</li>
        <li>Upwork Job ID: 1706560446209835008</li>
        <li>Last Price Increase: 2023-09-26</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 26896617</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-25 14:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Save button is disabled in Display name page in offline mode

### What is the root cause of that problem?
In FormProvider, the enabledWhenOffline prop is not being forwarded to the `FormWrapper` component.

### What changes do you think we should make in order to solve the problem?
Forward the enabledWhenOffline prop to the `FormWrapper` component.

### What alternative solutions did you explore? (Optional)
None.

**Comment by tjferriss** [comment] 2023-09-26 06:46
I'm able to reproduce this one, though I'm not sure if this qualifies as a deploy blocker.

**Comment by akinwale** [comment] 2023-09-26 07:36
> Looks like it @akinwale's [proposal](https://github.com/Expensify/App/issues/28148#issuecomment-1733869721) looks good.
> 
> 🎀 👀 🎀 C+ reviewed
> 
> @akinwale Are you able to create the PR in the next few hours?

@parasharrajat Yes, I'm currently available. Do I wait to be assigned or should I just create the PR?

**Comment by marcochavezf** [comment] 2023-09-27 01:57
Let's go with @akinwale's solution to fix it

**Comment by akinwale** [comment] 2023-09-27 04:10
@parasharrajat My [PR](https://github.com/Expensify/App/pull/28295) is ready for review.

**Comment by chiragsalian** [comment] 2023-09-28 18:21
Tested on staging and this looks resolved to me. Removing blocker label.

**Comment by tjferriss** [comment] 2023-09-29 07:36
Payment Summary:

- External issue reporter NA Applause
- Contributor that fixed the issue @akinwale $750
- Contributor+ that helped on the issue and/or PR @parasharrajat $750

**Comment by tjferriss** [comment] 2023-10-05 21:13
@parasharrajat can you get started on the checklist?

**Comment by tjferriss** [comment] 2023-10-06 20:13
To clarify, payment is expected on 2023-10-09 as long as we don't see any regressions.

**Comment by akinwale** [comment] 2023-10-06 23:43
> To clarify, payment is expected on 2023-10-09 as long as we don't see any regressions.

This was originally deployed to production on 2023-09-28, so the payment date of 2023-10-05 is the correct one. Looks like it got mixed up in the deployment process a second time so the bot got confused.

**Comment by tjferriss** [comment] 2023-10-09 22:10
@akinwale has been paid via Upworks. We're waiting on @parasharrajat to be paid, then we can close the issue.

**Comment by akinwale** [comment] 2023-10-09 23:11
> @akinwale has been paid via Upworks. We're waiting on @parasharrajat to be paid, then we can close the issue.

Received. Thanks!

**Closed** 2023-10-11 03:48 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-12 22:18
$750 payment approved for @parasharrajat based on BZ summary.
