### ISSUE TITLE
Unauthorized Assignment of Tasks to Unregistered Users - Mobile number/Email

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22000] opened 2023-06-30 20:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
In the current system, there is a bug that allows users to assign tasks to unregistered users, bypassing the necessary validation checks.
1 Login as User A and click on assign task
2 Fill title and description
3 Under assignee, search for an unregistered mobile number (Try this one if you do not have one : +918969862299)
4 Leave share to blank and create the task
5 Send messages in task and create another task from within the chat
6 Mark the chat as complete
7 Verify if you can send messages, assign tasks from within the chat and mark it as complete as well
## Expected Result: 
When attempting to assign a task to a user, the system should validate and verify the user's registration status. If the user is unregistered, the system should prevent the task assignment and display an appropriate error message.
## Actual Result: 
The bug allows users to assign tasks to individuals who have not registered an account or provided necessary authentication. User A can send messages, assign tasks, mark it to completion with User B although User B never registered at all.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-4
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/71a4c905-cb87-4df2-b1a5-030b0e6c32ae

https://github.com/Expensify/App/assets/43996225/a4adb84f-6289-416c-94f3-4bb148560369

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688101199462919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment] 2023-07-01 06:41
This also seems to work with a fake email:

![image](https://github.com/Expensify/App/assets/30815269/aa53fced-1977-43f9-918c-407bd88b29f2)

**Comment by jliexpensify** [comment] 2023-07-01 06:53
Asking for clarification here - https://expensify.slack.com/archives/C01SKUP7QR0/p1688194420492439

**Comment by jliexpensify** [comment] 2023-07-02 00:31
@avi-shek-jha and @kavimuru - so I checked internally and this is actually intended behaviour (as I suspected). Here is the confirmation from David:

![image](https://github.com/Expensify/App/assets/30815269/42b62056-8bfc-482c-b46a-80a6c2cedd24)

**Closed by jliexpensify** 2023-07-02 00:31 UTC
Labels: Daily, Bug
