### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$500] LHN - IOU report page of amount changed is shown options to pin in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27458] opened 2023-09-14 16:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap request money
4. Enter an amount
5. Tap next
6. Select any user
7. Tap request amount
8. Tap on IOU
9. Tap on IOU in report page
10. Tap on amount and change the IOU request amount
11. Go to LHN
12. Open the new IOU report for changed request amount displayed
13. Navigate to LHN and long press the new IOU report for changed request amount displayed

## Expected Result:
The IOU report page of request amount changed has no pinned options and in LHN also when long pressing it, pinned option must not be shown

## Actual Result:
The IOU report page of request amount changed has no pinned options. But in LHN, when long pressing IOU report of changed request amount, pinned option is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.70-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/68bd1561-14eb-4e48-9475-d20a490f0b52

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112a786dd027cefd2</li>
        <li>Upwork Job ID: 1704236046264397824</li>
        <li>Last Price Increase: 2023-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27099388</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by s-alves10** [comment] 2023-09-14 18:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

`Pin` option is shown for IOU transaction thread in LHN

### What is the root cause of that problem?

We show `pin` option in cases below statement returns true
https://github.com/Expensify/App/blob/62b8e71105959aaa4392da20b251ca1fafd5ab3d/src/pages/home/report/ContextMenu/ContextMenuActions.js#L338

As you can see, we don't show `Pin` option for money request report(IOU report or Expense report). We don't limit the `Pin` option for IOU/Expense transaction thread.

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to limit the `Pin` option for IOU/Expense transaction thread. Add the `!ReportUtils.isMoneyRequest(reportID)` condition like below
```
        type === CONTEXT_MENU_TYPES.REPORT && !isPinnedChat && !ReportUtils.isMoneyRequestReport(reportID) && !ReportUtils.isMoneyRequest(reportID),
```

This works fine

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/a1e79dbd-b907-4bf6-b1bc-e92eb419f97a


</details>


### What alternative solutions did you explore? (Optional)

**Comment by johncschuster** [comment] 2023-09-19 20:48
Sorry I missed this one! Triaged!

**Comment by carlitose** [comment] 2023-09-20 00:16
**Proposal for Fixing Issue #27458**

**Problem:** The pinned option is incorrectly displayed in the LHN when long pressing the IOU report of a changed request amount.

**Proposed Solution:** 

1. Investigate the issue by reproducing it using the provided steps.
2. Identify the root cause in the code that handles the display of the pinned option in the LHN.
3. Modify the code to add a condition that checks if the IOU report amount has been changed. If it has, the pinned option should not be displayed in the LHN.
4. Test the solution on all platforms where the bug was reproducible to ensure it works as expected and doesn't introduce new issues.
5. Document all changes and explain how they resolve the issue.

I believe this approach will effectively address the bug. I look forward to your feedback.


Remember to review their Contributor Guidelines before submitting your proposal.
Contributor details
Your Expensify account email: [carlog.sergi@gmail.com](mailto:carlog.sergi@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01b0d12422bbdbf2d3

**Comment by DylanDylann** [comment] 2023-09-20 08:55
I see It's a dupe. I am not sure which specific issue. But we are having the plan to move pin option to context menu so the previous bug is closed.

**Comment by DylanDylann** [comment] 2023-09-26 08:58
@parasharrajat ref: https://github.com/Expensify/App/issues/26550

**Comment by DylanDylann** [comment] 2023-10-04 03:31
@parasharrajat ICYMI, What do you think about [my proposal](https://github.com/Expensify/App/issues/27458#issuecomment-1740837433)?

**Comment by johncschuster** [comment] 2023-10-04 21:41
bump @parasharrajat!

**Comment by DylanDylann** [comment] 2023-10-05 10:13
> We want it to be visible only for single request chat. Your proposal does not satisfy this.

@parasharrajat Could you help to clarify `single request chat`

My proposal make sure that the pin option will be hidden if it is a request money report or an IOU report

**Comment by DylanDylann** [comment] 2023-10-05 10:19
> pin option should not be shown for iOU and Expense Reports.

@parasharrajat Could you check the isMoneyRequest function
https://github.com/Expensify/App/blob/25f7ac14d3dcadbb60e24074494b12d181567ba3/src/libs/ReportUtils.js#L742-L745

I see it covers iOU and Expense Reports

**Comment by DylanDylann** [comment] 2023-10-06 06:53
> Above reports should not have pin/unpin functionality which is working as expected currently.

Do you mean that everything works well now?

Currently on lastest main: 
1. Expense Report doesn't have pin/unpin functionality (Working well as expected)
2. IOU Report has pin functionality when right-clicking on LHN (It is unexpected, we need to fix it)

<img width="1440" alt="Screenshot 2023-10-06 at 13 51 28" src="https://github.com/Expensify/App/assets/141406735/9e13cfdd-d5c5-405c-9baa-c5dfdb2f1f40">

**Comment by DylanDylann** [comment] 2023-10-06 07:03
We are using 
- `isMoneyRequestReport` function to check if it is expense report
-  `isMoneyRequest ` function to check if it is IOU report


But in ContextMenuAction the condition to show pin option
https://github.com/Expensify/App/blob/dfb3f9b0b536d9640f81a85d59e095581dc06dba/src/pages/home/report/ContextMenu/ContextMenuActions.js#L339

We only check `!isMoneyRequestReport` so the pin functionality doesn't exist on expense report
We need to add `!isMoneyRequest` to hide pin functionality on IOU Report

I am not sure why you said that It is not safety in [here](https://github.com/Expensify/App/issues/27458#issuecomment-1748536776). Could you help to detail it?

**Comment by DylanDylann** [comment] 2023-10-06 07:32
@parasharrajat Could you help to screenshot IOU report?

**Comment by DylanDylann** [comment] 2023-10-06 07:36
@parasharrajat Could you check the OP?

**Comment by DylanDylann** [comment] 2023-10-06 09:50
@parasharrajat Sure. I will update now. The expected is that we display pin/unpin button for IOU Request in both LHN and header ?

**Comment by s-alves10** [comment] 2023-10-06 11:38
@parasharrajat 

Did you check [my proposal](https://github.com/Expensify/App/issues/27458#issuecomment-1719963705)?

**Comment by DylanDylann** [comment] 2023-10-06 12:58
@parasharrajat We still discuss on Slack Thread. I have a bit curious, could you help to verify how we are naming report

## 1. Main Report 
<img width="1440" alt="Screenshot 2023-10-06 at 19 55 08" src="https://github.com/Expensify/App/assets/141406735/2b3fabf3-245d-4e89-9143-edfdb0e93042">

## 2. IOU Report
<img width="1440" alt="Screenshot 2023-10-06 at 19 55 24" src="https://github.com/Expensify/App/assets/141406735/dadbcc85-5de4-4155-847d-42f47f8cbe67">

## 3. IOU Thread 
<img width="1440" alt="Screenshot 2023-10-06 at 19 55 46" src="https://github.com/Expensify/App/assets/141406735/32ca8011-5972-4ecf-b9ee-06a1e27fe9e3">

## So which is the expense report?

**Comment by DylanDylann** [comment] 2023-10-06 18:35
@parasharrajat From the [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1696611184365509?thread_ts=1696578659.871609&cid=C01GTK53T8Q), in this issue we only need enable pin/unpin option for IOU request, don't need to care to Expense/IOU Report.

Finally, we only need to add pin functionality to the header of the IOU Thread.

[Updated proposal](https://github.com/Expensify/App/issues/27458#issuecomment-1740837433)

**Comment by DylanDylann** [comment] 2023-10-07 10:35
@parasharrajat [Updated proposal](https://github.com/Expensify/App/issues/27458#issuecomment-1740837433) for more detail

**Comment by DylanDylann** [comment] 2023-10-07 10:52
@parasharrajat Thanks for deep reviewing and your reminder. It is great to work with you

**Comment by iwiznia** [comment] 2023-10-09 12:16
> In MoneyRequestHeader, define threeDotsMenuItems like this

Hmmm instead of duplicating all this code, wouldn't it be better to make it it's own component and use it in both places?

Other than that, proposal looks good

**Comment by DylanDylann** [comment] 2023-10-10 04:25
@parasharrajat  this (PR)[https://github.com/Expensify/App/pull/29078] ready for review

**Comment by DylanDylann** [comment] 2023-10-10 04:29
> Hmmm instead of duplicating all this code, wouldn't it be better to make it it's own component and use it in both places?

@iwiznia I think it's not necessary to create own component because each `threeDotsMenuItems` has a different logic and shares only the Pin and Unpin parts

**Comment by iwiznia** [comment] 2023-10-10 11:33
What different logic do they have exactly?

**Comment by DylanDylann** [comment] 2023-10-11 04:48
@iwiznia The logic of threeDotMenuItems in HeaderView Component and MoneyRequestHeader Component is differrent
1. In HeaderView, It includes markAsIncomplete, cancel, joinThread/leaveThread, pin/unpin, Zoom, GoogleMeet
2. In MoneyRequestHeader, It includes addReceipt, deleteAction, pin/unpin

**Comment by iwiznia** [comment] 2023-10-11 11:44
> @iwiznia The logic of threeDotMenuItems in HeaderView Component and MoneyRequestHeader Component is differrent

Oh, I was saying to create a component for the pin/unpin button only, since that's the one we are duplicating.

> One more thing, how we add pin/unpin option to threeDotMenuItems in 2 components also be different based on the order of this option in the list

Not sure I get what you mean... that the pin/unpin is in a different position inside the list?

**Comment by johncschuster** [comment] 2023-10-25 21:58
# Summary of payments:
This issue is [eligible](https://github.com/Expensify/App/issues/27458#issuecomment-1759372279) for an urgency bonus

@parasharrajat does not require payment (Eligible for Manual Requests) - $750 ($500 + 50% bonus)
@DylanDylann requires payment of $750 ($500 + 50% bonus) via [Upwork](https://www.upwork.com/nx/wm/offer/27099388)

**Comment by johncschuster** [comment] 2023-10-25 22:00
Keeping open so I can handle the regression issue tomorrow

**Comment by johncschuster** [comment] 2023-10-30 16:33
Regression test issue has been opened! I'm going to close this out.

**Closed by johncschuster** 2023-10-30 16:33 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-12-11 01:31
$750 payment approved for @parasharrajat based on [this comment](https://github.com/Expensify/App/issues/27458#issuecomment-1780114465).
