### ISSUE TITLE
Workspace avatar reverts to default after reopening the app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22002] opened 2023-06-30 22:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS/Android/Desktop App or go to staging.new.expensify.com
2. Go to existing or create new workspace
3. Upload workspace avatar and tap 'Save'
4. Close and re-open app or reload web page

## Expected Result:
Avatar saved and showing as workspace avatar

## Actual Result:
Workspace avatar is not saved and reverts to default after reopening the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.35.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7b5ceb06-2255-436f-a712-384642141e91

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014fa14191ff031aab</li>
        <li>Upwork Job ID: 1675931134956208128</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2023-07-03 13:40
Didn't have time to investigate further, but I'm removing the deploy blocker label as this is reproducible on prod.

https://github.com/Expensify/App/assets/10736861/09a1abe9-0c60-4f5c-a90d-9aacb7e47eb3

https://github.com/Expensify/App/assets/10736861/9d4de49c-7016-46bb-876b-16446ed4f3a5

**Comment by marcaaron** [comment] 2023-07-04 02:49
Ok, I found the root cause and it's in the backend. 

When we are returning the policySummaryList it has the key of `avatar` and not `avatarURL`. Easy fix.

**Comment by marcaaron** [comment] 2023-07-04 02:58
@0xmiroslav Just a heads up that I don't think we need any help testing here as there won't be any NewDot PR

**Comment by marcaaron** [comment] 2023-07-11 00:02
We can close this now as solution been deployed to prod.

**Closed by marcaaron** 2023-07-11 00:02 UTC
Labels: Reviewing, Engineering, Daily, Internal
