### ISSUE TITLE
[HOLD for payment 2023-08-02] [$250] Migrate BaseKeyboardSpacer.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16173] opened 2023-03-20 08:39 UTC
### Filenames
- [ ] [src/components/KeyboardSpacer/BaseKeyboardSpacer.js](https://github.com/Expensify/App/blob/main/src/components/KeyboardSpacer/BaseKeyboardSpacer.js)
    - **type:** `React.PureComponent`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca21614168991470</li>
        <li>Upwork Job ID: 1678836792784138240</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by muxriddinmuqimov77** [comment] 2023-06-06 06:57
I'd like to work on this issue

**Comment by s-alves10** [comment] 2023-06-06 10:28
I'd love to work on this.

**Comment by olexyt** [comment] 2023-07-07 13:53
I can work on this issue.

**Comment by vadymbokatov** [comment] 2023-07-11 18:42
I'd like to work on this issue.

**Comment by alexxxwork** [comment] 2023-07-11 18:44
I would love to work on this issue

**Comment by payal-lathidadiya** [comment] 2023-07-11 18:46
dibs?

**Comment by crazy-coding** [comment] 2023-07-11 18:48
I'd love to work on this.

**Comment by yh-0218** [comment] 2023-07-11 18:49
I can work on this task. Thanks.

**Comment by disha-np** [comment] 2023-07-11 18:50
I'd like to work on this

**Comment by Vadym-33** [comment] 2023-07-11 18:50
I hope to work on this task.

**Comment by alpeshl** [comment] 2023-07-11 18:51
can I work on this

**Comment by vadymbokatov** [comment] 2023-07-11 18:51
Contributor details
Expensify account email: vadymbakatovdev@gmail.com
Upwork profile link: https://www.upwork.com/freelancers/~01eb98dceed660ed38

**Comment by Talha345** [comment] 2023-07-11 18:52
I'd love to work on this.

**Comment by Vadym-33** [comment] 2023-07-11 18:52
Contributor details
Your Expensify account email: halchynskyivadym@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015cbd34d51b762360

**Comment by mejed-alkoutaini** [comment] 2023-07-11 18:53
I'm able to work on this if needed! 😇

**Comment by neonbhai** [comment] 2023-07-11 18:57
I would love to work on this!

**Comment by KrAbhas** [comment] 2023-07-11 19:02
I would like to work on this

**Comment by vdem0115** [comment] 2023-07-11 19:04
I can work on this

**Comment by manishram** [comment] 2023-07-11 19:08
Contributor details
Your Expensify account email: gaheci7435@iturchia.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01bfc30274dd754971

**Comment by mjbarcomb** [comment] 2023-07-11 19:37
Contributor details
Your Expensify account email: mbarcomb@me.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0143c0ca4d93fb6ed6

**Comment by Talha345** [comment] 2023-07-11 19:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We are trying to refactor `BaseKeyboardSpacer.js` from a class component to a function component.

### What is the root cause of that problem?

N/A

### What changes do you think we should make in order to solve the problem?

We should understand the existing class component and re-write it using functional syntax. Class states and lifecycle methods should be updated to use hooks (useState, useEffect) and references to props should be converted to prop arguments.

Finally, the references to the component should be updated and testing should be done to make sure everything is working correctly.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by manishram** [comment] 2023-07-11 20:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
`BaseKeyboardSpacer.js` needs to be refactored to make it functional based component. Currently it is a class based component.

### What is the root cause of that problem?
There are various advantages of functional based components over class based but one of the most important reason is  that React Hooks are only available in functional components. Hooks allow us to use state and other React features, such as lifecycle methods, without writing a class. They provide a more flexible and intuitive way of managing state and side effects in your components.

### What changes do you think we should make in order to solve the problem?
Need to rewrite the code of `BaseKeyboardSpacer.js` in functional based component. After refactoring, testing needs to be done to check if everything is working.

### What alternative solutions did you explore? (Optional)
None

**Comment by to-ai** [comment] 2023-07-11 21:18
I am able to work on this task.

**Comment by to-ai** [comment] 2023-07-11 21:21
I am able to work on this task.

**Comment by mkhutornyi** [comment] 2023-07-11 21:34
I'd like to work on this.

**Comment by lofi-marz** [comment] 2023-07-11 21:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Refactoring "BaseKeyboardSpacer.js" from a Class Component to a functional component

### What is the root cause of that problem?
 "BaseKeyboardSpacer.js" has been written in the older Class component style, and has no reason not to be converted into a functional component.
 
### What changes do you think we should make in order to solve the problem?
 - The state values contained in the component can be refactored to several useState hooks
 - The component contains two Class component lifecycle methods, 
    componentDidMount and componentDidUnmount, which can both be refactored into one useEffect hook
 - The component contains some methods attached to the class, which could be easily moved to separate functions

**Comment by lofi-marz** [comment] 2023-07-11 21:48
Contributor details
Your Expensify account email: marzipant.e@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019c194b11d5dfabbc

**Comment by marcaaron** [comment] 2023-07-11 22:15
Just clarifying that @mollfpr is the C+ on this one. They were unassigned erroneously. Re-adding the Help Wanted label.

**Comment by manishram** [comment] 2023-07-11 22:20
Hey @marcaaron what is the criteria to get the task assignment?

**Comment by alexxxwork** [comment] 2023-07-11 23:33
@manishram No need for proposal. Just leave a comment that you would like to take this issue and be the first commenter without similar issues already assigned.

**Comment by mollfpr** [comment] 2023-07-12 09:11
We can assign this to @muxriddinmuqimov77 they comment on it first and haven't assigned to any open issue.

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment] 2023-07-12 11:02
@rayane-djouah The link you attach it's not working, it didn't bring me to any thread.

**Comment by mollfpr** [comment] 2023-07-12 11:17
>I think out of fairness it should be AFTER the HOLD has been removed. Otherwise you can comment on every issue to “get in line” and honestly that seems kind of a mess to me because everyone will comment on all the issues 

Let's follow the rules. The first comment after HOLD was removed and the label added is @vadymbokatov [here](https://github.com/Expensify/App/issues/16173#issuecomment-1631329333). Also, they didn't have any PR/issue assigned.

cc @cristipaval

**Comment by vadymbokatov** [comment] 2023-07-12 11:19
@mollfpr I can start to work on this issue right now.

**Comment by mollfpr** [comment] 2023-07-12 11:20
@vadymbokatov That's great! But let's wait until you get assigned to the issue.

**Comment by usman-dataprism** [comment] 2023-07-12 11:47
Contributor details
Your Expensify account email: usman.ashraf678@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/usmanashraf678

**Comment by vadymbokatov** [comment] 2023-07-12 17:18
Thank you for assigning me this task to me.
I have submitted my proposal on upwork.
I will create PR in 3 hours.

**Comment by cristipaval** [comment] 2023-07-25 10:11
> Based on my calculations, the pull request did not get merged within 3 working days of assignment. Please, check out my computations here:
> 
> * when @vadymbokatov got assigned: 2023-07-12 16:56:13 Z
> * when the PR got merged: 2023-07-24 18:11:27 UTC
> * days elapsed: 8
> 
> On to the next one 🚀

@slafortune The PR was ready to review but it took longer because I was ooo last week.

**Comment by mollfpr** [comment] 2023-08-03 15:44
Friendly bump @slafortune for payment.

**Comment by slafortune** [comment] 2023-08-03 19:20
Sorry for the delay @mollfpr - Paid 👍 
@vadymbokatov - offer sent!

**Comment by vadymbokatov** [comment] 2023-08-03 19:24
@slafortune Accepted offer.

**Comment by slafortune** [comment] 2023-08-03 19:33
All paid! Bonus sent separate.

**Comment by vadymbokatov** [comment] 2023-08-03 19:34
Thank you

**Closed by slafortune** 2023-08-03 19:33 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment

**Comment by slafortune** [comment] 2023-08-10 13:32
The bonus was paid in error on this.  Migration issues do not qualify for a speedy bonus - some of the reasoning is it doesn’t apply because these migrations are not fixing any bugs, so whether it’s merged in 1 or 7 days, it doesn’t have any effect on the product.

**Comment by vadymbokatov** [comment] 2023-08-10 13:39
@slafortune Oh. This is my first commit for this project. I didn't know that rule.
