### ISSUE TITLE
[$250] QAB - QAB changes to "Scan receipt" after submitting manual expense with receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43775] opened 2024-06-14 14:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4629367
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM
3. Submit a manual expense with receipt
4. Open FAB right after submitting the expense
5. Note that QAB shows "Submit expense"
6. Wait for a while (to let the expense created successfully)
7. Open FAB again

## Expected Result:
QAB will continue to show "Submit expense" because the manual expense with receipt is submitted

## Actual Result:
QAB changes to "Scan receipt" after submitting manual expense with receipt

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5950fdd5-7c92-47a3-b59e-5ae5dab103d7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af2c1012b0aeda1d</li>
        <li>Upwork Job ID: 1803068216115939348</li>
        <li>Last Price Increase: 2024-08-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by lanitochka17** [comment] 2024-06-14 14:03
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-06-14 14:03
@bfitzexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment] 2024-06-14 21:47
I think it is BE issue

**Comment by alitoshmatov** [comment] 2024-06-19 10:00
Couldn't reproduce this issue

https://github.com/Expensify/App/assets/59907218/ed498140-e054-432c-a828-dce78050b31a

**Comment by bfitzexpensify** [comment] 2024-06-25 16:29
I am also having difficulty reproducing.

**Comment by mvtglobally** [comment] 2024-07-03 15:08
Issue is reproducible during KI retests.

https://github.com/Expensify/App/assets/43995119/5683e722-2cb7-4902-8de7-5f002c733749

**Comment by alitoshmatov** [comment] 2024-07-09 19:06
Seems like issue still [exists](https://github.com/Expensify/App/issues/43775#issuecomment-2206470242)

Waiting for proposals here

**Comment by alitoshmatov** [comment] 2024-07-24 09:07
No proposals yet

**Comment by bfitzexpensify** [comment] 2024-08-06 16:13
Going to close this as an edge case for now

**Closed by bfitzexpensify** 2024-08-06 16:13 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
