### ISSUE TITLE
[HOLD for payment 2024-05-08] [HOLD for payment 2024-05-06] Public room - "Message Concierge for help with setup" banner appears for anonymous user

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41135] opened 2024-04-27 13:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #40701
**Version Number:** 1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log out if logged in.
3. Navigate to a public room link (https://staging.new.expensify.com/r/2376199970894587).

## Expected Result:
"Message Concierge for help with setup" banner will not appear for anonymous user viewing the public room.

## Actual Result:
"Message Concierge for help with setup" banner appears for anonymous user viewing the public room.
This banner also disappears after delay after logging in to public room.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img width="1440" alt="Bug6463583_1714206061984!Screenshot_2024-04-27_at_16 20 21" src="https://github.com/Expensify/App/assets/38435837/20ad3f2f-bbd5-4550-aa30-8644b13cf3fd">

https://github.com/Expensify/App/assets/38435837/735c3d14-ff8c-4c65-8071-ed38afab772a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by m-natarajan** [comment] 2024-04-27 13:46
@iwiznia FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors. 

We think this bug might be related to #wave-collect - Release 1

**Comment by m-natarajan** [comment] 2024-04-27 13:46
We think this bug might be related to #vip-vsb

**Comment by neonbhai** [comment] 2024-04-27 14:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Public room - "Message Concierge for help with setup" banner appears for anonymous user

### What is the root cause of that problem?
We dont check for anonymous user when displaying the `SystemChatReportFooterMessage` Report Footer

### What changes do you think we should make in order to solve the problem?
We should add a check for `!isAnonymousUser` when displaying the banner here:

https://github.com/Expensify/App/blob/10fc359d9fdd1e05e03a4769e2a73f95e703be51/src/pages/home/report/ReportFooter.tsx#L144

**Comment by iwiznia** [comment] 2024-04-29 14:10
This seems to be coming from https://github.com/Expensify/App/pull/40010
@rezkiy37 do you want to take a look or should I revert that PR?

**Comment by iwiznia** [comment] 2024-04-29 14:13
Asked here https://expensify.slack.com/archives/C01GTK53T8Q/p1714399960286809

**Comment by neonbhai** [comment] 2024-04-29 15:19
This will be fixed with https://github.com/Expensify/App/pull/41200

@iwiznia @isabelastisser

**Comment by iwiznia** [comment] 2024-04-29 15:24
Oh ok

**Comment by isabelastisser** [comment] 2024-04-29 15:27
@iwiznia @neonbhai, does it mean that this issue can be closed?

**Comment by neonbhai** [comment] 2024-04-29 15:47
We aren't proceeding with the revert, just changing visiblity logic (ref: [here](https://github.com/Expensify/App/issues/41184#issuecomment-2082386002))

We could keep it open so it is tested for regressions after deploy?

cc: @isabelastisser

**Comment by isabelastisser** [comment] 2024-05-08 21:50
@iwiznia, can I close this or do you need to complete the BZ list above first?

**Closed** 2024-05-08 22:26 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
