### ISSUE TITLE
No errors shown when edit amount/date of scanned receipt

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48147] opened 2024-08-28 07:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
Issue was found when executing this PR: https://github.com/Expensify/App/pull/47607
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: user is logged in desktop app.

1. Go to any chat > Submit expense
2. Choose Scan
3. Upload a receipt with a date
4. After SmartScan completed, Edit the amount to be higher than the original amount
5. Edit the date

## Expected Result:
After steps 4 and 5, RBR on the money request report/thread appears.
The error message below edited field is shown.

## Actual Result:
RBR on the money request report/thread appears in LHN.
No error messages below edited field is shown.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f6b0e819-eaa2-4d97-a8f7-62d73ba0d73e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-08-28 07:17
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-08-28 07:17
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CortneyOfstad** [comment] 2024-08-30 15:58
This is not a bug from what I see. I have not come across any reference where we provide an error or violation in new dot when first creating/editing an unsubmitted expense, as the message itself is notification/error/violation that the amount and date have been changed on the expense. When the receipt is submitted, we show a violation to notify the admin/approver, but not at this stage. 

Closing!

**Closed by CortneyOfstad** 2024-08-30 15:58 UTC
Labels: Reviewing, Weekly, Bug
