### ISSUE TITLE
Web -  Sign-in icons ( Google & Apple ) are not disabled while offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26528] opened 2023-09-01 21:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the Sign-in page. Or logout if you are logged in
2. Go offline
3. Notice the Sign-in Icons

## Expected Result:
Sign-in icons should be disabled while offline.
The sign-in icon method should be consistent with the regular sign-in method, which involves entering an email and then clicking the continue button. In this case, the continue button is disabled.

## Actual Result:
Sign-in icons ( Google & Apple ) are not disabled while offline.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 28-08-23 04_44_06.webm](https://github.com/Expensify/App/assets/93399543/d5f9842b-6d3e-4b7b-a81a-e59cd8e9402c)

https://github.com/Expensify/App/assets/93399543/a9aea75c-489a-466d-9ffa-ce22e08ba851

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693188179181359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment] 2023-09-01 21:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
Update onPress handlers in the AppleSignIn and GoogleSignIn button components to not do anything when the network is offline. Also set the disabled icon.

### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment] 2023-09-05 14:40
Agreed with the reasoning in https://github.com/Expensify/App/issues/23257#issuecomment-1644470444, I'm going to close this out too.

**Closed by bfitzexpensify** 2023-09-05 14:40 UTC
Labels: Daily, Overdue, Bug
