### ISSUE TITLE
[HOLD for payment 2024-01-18] [$500] Add markdown syntax for creating a new task

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#32864] opened 2023-12-11 21:16 UTC
We want to create some syntax that will create a task when the following message is added to the composer

`[] @jack This is the task name`

Should create a task in the current room that:
- Is assigned to jack
- Has the title 'This is the task name'
- The share destination would be the current report where this comment is posted

The assignee can be optional, in which case the command would look something like this

`[] This is the task name`

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d0a874d62f021b7</li>
        <li>Upwork Job ID: 1734321392740421632</li>
        <li>Last Price Increase: 2023-12-18</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28066406</li>
<li>suneox | Contributor | 28066407</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by AmjedNazzal** [comment] 2023-12-12 12:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Add markdown syntax for creating a new task

### What is the root cause of that problem?

This is a new feature

### What changes do you think we should make in order to solve the problem?

To start, we would modify `ReportActionCompose` `submitForm` function to the following:

```javascript
const submitForm = useCallback(
        (e) => {
            if (e) {
                e.preventDefault();
            }

            const newComment = composerRef.current.prepareCommentAndResetComposer();
            if (!newComment) {
                return;
            }

            const Taskregex = /^\[\]\s*(.+)/;
            const match = newComment.match(Taskregex);
           
            if (match && match[1]) {
                const TaskDetails = match[1];
                return onTriggerTaskCreation(TaskDetails);
            }

            onSubmit(newComment);
        },
        [onSubmit],
    );
```

What we are doing is we first use a regex that will look for [] at the start of the newComment text and if there is, it will be saved in `match` variable.
After that we check if that match in index[1] is not empty, and if it's not we assign it's value to TaskDetails constant and pass it to a new function `onTriggerTaskCreation` which will contain the following logic:

```javascript
const onTriggerTaskCreation = useCallback((taskDetails) => {
    const assigneeRegex = /@([\S]+)/; 
    const assigneeMatch = taskDetails.match(assigneeRegex);
    const assignee = assigneeMatch ? assigneeMatch[1] : '';
    let assigneeAccountID = 0;
    let assigneeChatReport = null;
    if (assignee) {
        const assigneeDetails = Object.values(personalDetails).find(entry => entry.login === assignee) || {};
        assigneeAccountID = assigneeDetails.accountID ?? 0;
        assigneeChatReport = assigneeDetails.assigneeChatReport ?? Task.setAssigneeValue(assignee, assigneeAccountID);
    }
    const title = assignee
        ? taskDetails.replace(`@${assignee}`, '').trim() || "Untitled Task"
        : taskDetails.trim();

    Task.createTaskAndNavigate(
        reportID,
        title,
        '',
        assignee,
        assigneeAccountID,
        assigneeChatReport,
        report.policyID,
    );
}, []);
```

The logic of the function works as follows: 

1) 
```javascript
const onTriggerTaskCreation = useCallback((taskDetails) => {
    const assigneeRegex = /@([\S]+)/; 
    const assigneeMatch = taskDetails.match(assigneeRegex);
    const assignee = assigneeMatch ? assigneeMatch[1] : '';
    let assigneeAccountID = 0;
    let assigneeChatReport = null;
    if (assignee) {
        const assigneeDetails = Object.values(personalDetails).find(entry => entry.login === assignee) || {};
        assigneeAccountID = assigneeDetails.accountID ?? 0;
        assigneeChatReport = assigneeDetails.assigneeChatReport ?? Task.setAssigneeValue(assignee, assigneeAccountID);
    }
}, []);
```

In this part we are grabbing the first @ item and assign it to assignee, otherwise it will be empty since it's not required
If there is an assignee we need to access and retrieve it's `assigneeAccountID` and `assigneeChatReport` but if there is an `assigneeAccountID` but no `assigneeChatReport` then we need to create an optimistic report for it using `Task.setAssigneeValue` 

2) 
```javascript
    const title = assignee
        ? taskDetails.replace(`@${assignee}`, '').trim() || "Untitled Task"
        : taskDetails.trim();

    Task.createTaskAndNavigate(
        reportID,
        title,
        '',
        assignee,
        assigneeAccountID,
        assigneeChatReport,
        report.policyID,
    );
}, []);
```

In this section we are assigning a title, the logic is that if there is an assignee, we will filter it out and assign the rest of the text as a title 
If there is no assignee, we will just assign the whole text to the title
If there is an assignee but no text after it, we will take the assignee and then give the title "Untitled Task" as a placeholder

After that's taken care of we can call `Task.createTaskAndNavigate` and create the task.

**Comment by AmjedNazzal** [comment] 2023-12-14 10:50
@Ollyws I think it should be on submit because otherwise the task could be created before the user is ready to create it

**Comment by thienlnam** [comment] 2023-12-14 18:53
@Ollyws 

It should only be created once the message is submitted

**Comment by iwiznia** [comment] 2023-12-20 21:07
Sorry I dropped the ball on this. Assigned @suneox as the proposal looks good, the only thing I have doubts is the regex.

**Comment by thienlnam** [comment] 2024-01-04 00:23
@Ollyws Are you able to get to this soon? If not we can assign another C+ to it

**Comment by iwiznia** [comment] 2024-01-22 18:31
Looks good to me

**Comment by anmurali** [comment] 2024-01-22 22:53
@Ollyws - the previously issued offer expired. So I had to reissue an offer to pay you. It is [here](https://www.upwork.com/nx/wm/offer/100571731)
@suneox is paid

**Comment by iwiznia** [comment] 2024-01-29 16:27
@anmurali can we close this then?

**Comment by iwiznia** [comment] 2024-01-29 20:18
@anmurali can you pay then?

**Comment by anmurali** [comment] 2024-01-30 00:13
Paid @Ollyws now.

**Closed by anmurali** 2024-01-30 00:13 UTC
Labels: External, Daily, NewFeature, Overdue, Awaiting Payment
