### ISSUE TITLE
[$500] Web - "Unexpected error while posting the comment, please try again later We were unable to process this file" error appears even after closing it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27522] opened 2023-09-15 12:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send any corrupted file to generate error
3. Close the error
4. Reload the page

## Expected Result:
Error should not appears on reload

## Actual Result:
Error appears on reload

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/33e35f6d-090e-41e9-821b-2a90ed123a7f

https://github.com/Expensify/App/assets/93399543/f56e3333-1657-41c2-b977-481b391ace86

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694669757383259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f1c69f2df59aa59c</li>
        <li>Upwork Job ID: 1702665113574621184</li>
        <li>Last Price Increase: 2023-09-29</li>
    </ul>
</details>

**Comment by abekkala** [comment] 2023-09-15 13:33
unassigning myself as the dupe assignee

**Comment by akamefi202** [comment] 2023-09-15 17:53
I was not able to reproduce the issue. How can I make corrupt file for reproduce?

**Comment by greg-schroeder** [comment] 2023-09-18 10:58
@gadhiyamanan do you know how to explain that ☝️ ?

**Comment by gadhiyamanan** [comment] 2023-09-18 11:05
i shared corrupt file in [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1694669801227629?thread_ts=1694669757.383259&cid=C049HHMV9SM) or there are some websites which corrupts file

**Comment by akamefi202** [comment] 2023-09-20 11:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the user uploads a corrupt file, "Unexpected error while posting the comment, please try again later We were unable to process this file" error appears even after closing it and reloading.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/4c207ec07ce4d0b3ca3cc4a6f90b02524b4b440f/src/libs/actions/ReportActions.js#L14-L18

When the user clicks "Close" button, `clearReportActionErrors` function is called.
The function removes the comment from optimistic data but it doesn't remove it completely from OnyxDB.
So if the user reloads the page, the comment with error will be shown again.

### What changes do you think we should make in order to solve the problem?
To fix this issue, we need to delete the comment completely if `actionName` is "AddComment".

If `actionName` is "AddComment", the command is "AddComment" or "AddAttachment".
If these commands are failed with error, the comment with error shouldn't be shown after closing it and reloading.

But in other cases, the comment should be shown again after reloading. For example, "UpdateComment".

So we need to update `clearReportActionErrors` function for this.
```
if (reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT) {
    // Delete the comment if action is AddComment
    Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${originalReportID}`, {
        [reportAction.reportActionID]: {
            pendingAction: null,
            message: [
                {
                    translationKey: '',
                    html: '',
                    text: '',
                }
            ],
            errors: null,
        },
    });
} else {
    // Delete the optimistic action
    Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${originalReportID}`, {
        [reportAction.reportActionID]: null,
    });
}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by akamefi202** [comment] 2023-09-22 10:44
Before fix:

[Screencast from 2023年09月22日 18时37分26秒.webm](https://github.com/Expensify/App/assets/53784473/e186d764-0c53-4724-904d-186ae1058a48)

After fix:

[Screencast from 2023年09月22日 18时39分49秒.webm](https://github.com/Expensify/App/assets/53784473/8180a227-4e12-49fc-afe8-4e7ffbe6c9b5)

**Comment by greg-schroeder** [comment] 2023-09-25 07:36
Thoughts on the above @aimane-chnaif?

**Comment by mvtglobally** [comment] 2023-09-28 03:20
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment] 2023-09-28 07:34
bump @aimane-chnaif

**Comment by greg-schroeder** [comment] 2023-10-02 15:10
Let me know if you need any help w/ this one Aimane!

**Comment by akamefi202** [comment] 2023-10-05 14:57
@aimane-chnaif Can't reproduce this issue anymore. Looks like fixed already.

**Comment by greg-schroeder** [comment] 2023-10-06 07:59
Same. Seems this may have been fixed and this is a dupe, then.

**Closed by greg-schroeder** 2023-10-06 07:59 UTC
Labels: External, Daily, Help Wanted, Bug
