### ISSUE TITLE
[HOLD for payment 2023-11-29] [$125] Desktop - Avatars in split preview card too close to right edge

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31394] opened 2023-11-15 18:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1700000146978699

## Action Performed:
1. Create a split with two other people
2. Look at the preview card

## Expected Result:
Avatar stacak should be 20px (or is it 16px?) away from the right edge of the card, it should match the same padding as left side

## Actual Result:
Avatar stack is too close to right edge

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2023-11-14 at 17 13 14@2x (1)](https://github.com/Expensify/App/assets/93399543/57c7cf57-e0df-4540-bdb6-83f969110539)

https://github.com/Expensify/App/assets/93399543/06b7652d-e12c-4bbe-a912-f219f21fcc7f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ce3040ec2425cf6</li>
        <li>Upwork Job ID: 1724853684623753216</li>
        <li>Last Price Increase: 2023-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 27689355</li>
</ul></li>
    </ul>
</details>

**Comment by youssef-lr** [comment] 2023-11-15 18:17
I'm going to try and fix this in an ongoing PR. If not we can let this be external.

**Comment by paultsimura** [comment] 2023-11-15 18:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The avatars are incorrectly placed

### What is the root cause of that problem?
The avatars use the negative margin here:

https://github.com/Expensify/App/blob/e953a657a5d4bb492a1b4cb7b74dcd6acc6ad9f9/src/styles/styles.ts#L2662

### What changes do you think we should make in order to solve the problem?

We should remove this negative margin:

https://github.com/Expensify/App/blob/e953a657a5d4bb492a1b4cb7b74dcd6acc6ad9f9/src/styles/styles.ts#L2662

### What alternative solutions did you explore? (Optional)

**Comment by abzokhattab** [comment] 2023-11-15 18:23
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
The avatars are incorrectly placed

# # What is the root cause of that problem?
The avatars margin is -10 instead of 16 

[App/src/styles/styles.ts](https://github.com/Expensify/App/blob/e953a657a5d4bb492a1b4cb7b74dcd6acc6ad9f9/src/styles/styles.ts#L2662)
        
## What changes do you think we should make in order to solve the problem?

we have 16 px in the front padding so we need to make the avatar padding `-16` instad of `-10`
```
 marginRight: -16, 
```

**Comment by yh-0218** [comment] 2023-11-15 18:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The avatars are incorrectly placed
### What is the root cause of that problem?
We have incorrect marginRight in `moneyRequestPreviewBoxAvatar`
### What changes do you think we should make in order to solve the problem?
We need to remove marginRight or smaller than now.
https://github.com/Expensify/App/blob/cc5a272b3fdcdbe9ecfca056cc8bbd4a405a5b17/src/styles/styles.ts#L2683
### What alternative solutions did you explore? (Optional)
<img width="395" alt="Screenshot 2023-11-15 at 8 56 14 PM" src="https://github.com/Expensify/App/assets/65789015/2888c884-d625-4591-a859-7e768bd3786b">

**Comment by paultsimura** [comment] 2023-11-16 11:19
Thanks. The PR is ready: https://github.com/Expensify/App/pull/31430

**Comment by puneetlath** [comment] 2023-11-22 16:31
Payment summary: 
- C - @paultsimura - $125 - paid via Upwork
- C+ - @parasharrajat - $125 - to be paid via NewDot

Closing. Thanks everyone!

**Closed by puneetlath** 2023-11-22 16:31 UTC
Labels: External, Weekly, Awaiting Payment, Bug
