### ISSUE TITLE
mWeb - User can't focus on input field of any search page after scrolling to bottom @Tushu17

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10771] opened 2022-09-02 03:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Open mWeb
 2. Go to search page
 3. Scroll to the bottom of the selectable user list
 4. Touch on search input field.

## Expected Result:
User should be able to focus on search input field

## Actual Result:
User isn't able to focus on search input field.

## Workaround:
Uknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.96.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/188055320-2296cd2c-9061-4efa-8c08-f49c32804c34.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Tushu17

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658179008439469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by madmax330** [comment] 2022-09-05 08:55
I'm not able to reproduce this on my phone

**Comment by madmax330** [comment] 2022-09-05 09:24
Asked if anyone can reproduce here: https://expensify.slack.com/archives/C01GTK53T8Q/p1662368455439869 
If no one can repro I'll close this out.

**Comment by mountiny** [comment] 2022-09-05 09:45
@madmax330 Also cant repro. I am not able to focus if it is still scrolling, but that is not a problem I think. Once the scrolling comes to still, I can focus just fine.

**Comment by mountiny** [comment] 2022-09-05 09:45
@kbecciv @mvtglobally Can you repro this? Otherwise we can close this

**Comment by madmax330** [comment] 2022-09-06 09:22
closing this since it looks like no one was able to reproduce

**Closed by madmax330** 2022-09-06 09:22 UTC
Labels: Engineering, Daily, Improvement
