### ISSUE TITLE
[$1000] Failed to Load is shown when opening a PDF offline but Infinite load is shown for an image

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26259] opened 2023-08-29 20:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From user A, Send a PDF file and An image to user B.
2. Be offline for user B before opening the Attachments
3. Click on the PDF file sent from User A and Notice the ''Failed to Load'' Message is shown.
4. Now Open the Image, Notice an infinite Loading is shown
## Expected Result: 
The ''Failed to Load'' Message is shown for both
## Actual Result: 
Failed to Load is shown when opening a PDF offline but Infinite load is shown for an image

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/869f1f93-039d-4443-b85e-0702830078fa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692410929128509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186e21daad25f0652</li>
        <li>Upwork Job ID: 1696760880483250176</li>
        <li>Last Price Increase: 2023-08-30</li>
    </ul>
</details>

**Comment by tamdao** [comment] 2023-08-30 05:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Failed to Load is shown when opening a PDF offline but Infinite load is shown for an image

### What is the root cause of that problem?
You don't have any logic to handle error when the Image component can't load the image

https://github.com/Expensify/App/blob/bb432aa6d787c6ba95faed521286cd169cbcade6/src/components/Image/index.js#L45-L50

### What changes do you think we should make in order to solve the problem?
Update Image component to add onError handler like this:

```js
const onError = useCallback(() => {
    setIsError(true);
}, []);

return isError ? (
    <Text>Failed to load image</Text>
) : (
    <RNImage
        // eslint-disable-next-line react/jsx-props-no-spreading
        {...forwardedProps}
        onError={onError}
        source={source}
    />
);
```

**Comment by kadiealexander** [comment] 2023-08-30 05:44
Reproduced:

https://github.com/Expensify/App/assets/59587260/d070818b-b1fc-4cc2-a5fc-bf3709cb17c9

**Comment by b4s36t4** [comment] 2023-08-30 06:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Failed to Load is shown when opening a PDF offline but Infinite load is shown for an image
### What is the root cause of that problem?
We have error handler added for the pdf which is tied to the `error` with `Document` component inside `PdfView.js` which shows error whenever we have an error loading issue.
### What changes do you think we should make in order to solve the problem?
We should handle the `onError` event inside the `ImageView` component as well.

We have used `Image` component two times inside the `ImageView` one for mobile screens and one for large devices. 

We need add the following changes.

```jsx

const [isError, setIsError] = useState(false)

/// Image component

<Image 
    ...props
    onError={() => setIsError(true)}
 />

```

using the above `isError` prop we could show some error message with proper stylings.



### What alternative solutions did you explore? (Optional)
NA

**Comment by kadiealexander** [comment] 2023-08-31 07:01
Good catch @hungvu193! Closing as a dupe.

**Closed by kadiealexander** 2023-08-31 07:01 UTC
Labels: External, Daily, Help Wanted, Bug
