### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000]  Paypal payment doesn't appear to settle IOU

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19311] opened 2023-05-19 19:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Preparation

-  Add a Paypal.me handle to NewDot account (Account A) that you have access to via Avatar > Payments
-  Complete the request money flow and send a payment request to another account (Account B) that you have access to

1.  1. Log into account B and click the Pay button

## Expected Result:
Verify that Pay with Paypal.me is visible as an option in the pay selector dropdown.

## Actual Result:
Pay with Paypal.me doesn't visible as an option in the pay selector dropdown.
Issue occurred on all environments.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Bug6061206_PP](https://github.com/Expensify/App/assets/43996225/db78ba9e-9fd7-4c1a-829c-846365094aa7)

https://github.com/Expensify/App/assets/43996225/67eac50e-d4aa-4d3e-8b77-994ba276e80a

**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109043fef9255546e</li>
        <li>Upwork Job ID: 1661109432056991744</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by miljakljajic** [comment] 2023-05-23 08:45
I'm running into a completely different bug when I try to reproduce this (request for payment not going through at all) - I am OOO today so I will re-assign to another BZ member to reproduce. Sorry for the delay in getting to this GH - EC3 has been very busy.

**Comment by NikkiWines** [comment] 2023-05-26 00:25
@abdulrahuman5196 can you review @allroundexperts's proposal [here](https://github.com/Expensify/App/issues/19311#issuecomment-1555188192) please? 🙇

**Comment by abdulrahuman5196** [comment] 2023-05-26 14:07
@allroundexperts  root cause is correct and his proposed solution solves the issues.

But I have some clarifications to make before approving the proposal. @NikkiWines 
1) In the chat report we need to show downdrop for paypal selection right? I assume yes then we need to pass `shouldShowPaymentOptions` props to the `SettlementButton`

2) Not related to this issue page. As @allroundexperts pointed out this issue of paypal option not shown in settlement buttion is also happening in MoneyRequestHeader component [here](https://github.com/allroundexperts/Expensify/blob/9e43cb7d811599ae67d1f31d78bac8327ce2061c/src/components/MoneyRequestHeader.js#L164-L174) for small screen devices. For other device we properly handle in MoneyRequestHeader, but for choosing if we want to show a paypal method we are using `Boolean(lodashGet(props.personalDetails, [moneyRequestReport.managerEmail, 'payPalMeAddress']))` [here](https://github.com/allroundexperts/Expensify/blob/main/src/components/MoneyRequestHeader.js#L153) but `getting paypal address from managerEmail` props value doesn't seem be reliable compared to `submitterPayPalMeAddress` as far as I tested. 
2.a) Should we include the MoneyRequestHeader issue as well part of this issue or take it as a separate issue?
2.b) What is the recommended props we should use to decide if we want to show paypal option. `submitterPayPalMeAddress` or `getting paypal address from managerEmail`


tagging @luacmartins  for providing further clarification on point 2

**Comment by luacmartins** [comment] 2023-05-26 15:59
>1. In the chat report we need to show downdrop for paypal selection right? 

@abdulrahuman5196 @allroundexperts this is not the intended behavior. The ReportPreview component within the Chat report should only show the latest payment method used. This is to allow 1-tap payment from the preview. Only the buttons in the iou/expense report should display the other options.

>As @allroundexperts pointed out this issue of paypal option not shown in settlement buttion is also happening in MoneyRequestHeader component [here](https://github.com/allroundexperts/Expensify/blob/9e43cb7d811599ae67d1f31d78bac8327ce2061c/src/components/MoneyRequestHeader.js#L164-L174) for small screen devices

This seems like a real issue. The MoneyRequestHeader should show the dropdown with all options, defaulting to the latest payment method.

**Comment by abdulrahuman5196** [comment] 2023-05-26 17:18
@luacmartins  
>@abdulrahuman5196 @allroundexperts this is not the intended behavior. The ReportPreview component within the Chat report should only show the latest payment method used. This is to allow 1-tap payment from the preview. Only the buttons in the iou/expense report header should display the other options.

**Got it. Then I don't think we need to do anything there.**





But curious question. 
I don't see the default value changing in the ReportPreview when we settle with a different payment in iou/expense report header. I think we should raise a separate issue for this.

https://github.com/Expensify/App/assets/46707890/6f351c06-40aa-46be-9532-29d592754779






<br/>
<br/>
>This seems like a real issue. The MoneyRequestHeader should show the dropdown with all options, defaulting to the latest payment method.
Yes. This is an issue.

Sameways we have this as well
>For choosing if we want to show a paypal method we are using Boolean(lodashGet(props.personalDetails, [moneyRequestReport.managerEmail, 'payPalMeAddress'])) [here](https://github.com/allroundexperts/Expensify/blob/main/src/components/MoneyRequestHeader.js#L153) but getting paypal address from managerEmail props value doesn't seem be reliable compared to submitterPayPalMeAddress as far as I tested.


Can we create a new issue for the MoneyRequestHeader? @allroundexperts proposal could be polished to fix that as well.

**Comment by luacmartins** [comment] 2023-05-26 17:48
Those seem like valid issues. @mountiny did we decide to only set the `lastPaymentMethod` NVP for Workspaces? What's the expected behavior for IOUs?

**Comment by mountiny** [comment] 2023-05-29 09:40
@luacmartins Correct that only works for workspaces as thats how we planned it in the Design doc, its tied to policy

**Comment by luacmartins** [comment] 2023-05-29 15:26
Hmm we could also tie it to the user's personal policy? I think it'd be valuable to have your last payment method always set for IOUs too. @trjExpensify @JmillsExpensify

**Comment by mountiny** [comment] 2023-05-30 07:35
I agree, I can work on this if we want to

**Comment by trjExpensify** [comment] 2023-05-30 14:16
>Hmm we could also tie it to the user's personal policy? I think it'd be valuable to have your last payment method always set for IOUs too. @trjExpensify @JmillsExpensify

How does that work? It's dependent on the person you're paying rather than your own personal policy preference. I.e I don't get the option to settle up with Vit via paypal.me if he doesn't have a paypal.me handle added to his account.

**Comment by abdulrahuman5196** [comment] 2023-05-30 15:32
Not overdue Melvin. Discussing on the options.

**Comment by luacmartins** [comment] 2023-05-30 15:51
@trjExpensify I think that's a good point that it depends on the person you're paying, but we could always try your preferred method but default to something else if that method is not available?

**Comment by luacmartins** [comment] 2023-05-30 19:59
Discussed 1:1 with @NikkiWines and I'm gonna take this one over since we have more context due to Manual Requests

**Comment by trjExpensify** [comment] 2023-05-30 20:28
>@trjExpensify I think that's a good point that it depends on the person you're paying, but we could always try your preferred method but default to 'elsewhere' if that method is not available?

With the workspace, it's always "sticky" such that your last choice to pay is remembered. It's somewhat unpredictable in the IOU case. So perhaps just more simply it's Wallet (if you can), or "Pay elsewhere" if you can't.

**Comment by luacmartins** [comment] 2023-05-30 22:28
I think we'd have the Paypal issue with workspaces too, no? An employee could remove their Paypal handle and suddenly the admin can't use that method anymore. I think it'd be fine to have it be sticky in a personal policy and always have a default for `Elsewhere` in case the method is not available.

**Comment by isabelastisser** [comment] 2023-05-31 15:44
Hey @luacmartins, based on [this comment](https://github.com/Expensify/App/issues/19311#issuecomment-1569010508), should I change this to `internal`?

**Comment by luacmartins** [comment] 2023-05-31 16:57
Yea, this will involve API changes.

**Comment by trjExpensify** [comment] 2023-06-01 14:16
>I think we'd have the Paypal issue with workspaces too, no? An employee could remove their Paypal handle and suddenly the admin can't use that method anymore.

True, though employers typically have one payment method for all employees, and the likelihood of employees 1) using paypal.me 2) changing how to get reimbursed is pretty edge case. Still, I suspect we should fallback on in-app if possible and elsewhere if not, yeah? Like why default to outside of the app if in-app is possible?

Kinda' separately, given that the personal policy is going to be used for tracking money in a personal capacity as well, and not just "settling IOUs", I still think we don't set a blanket sticky payment method on the personal policy at this point until things develop a bit further.

**Comment by mountiny** [comment] 2023-06-01 14:29
> Kinda' separately, given that the personal policy is going to be used for tracking money in a personal capacity as well, and not just "settling IOUs", I still think we don't set a blanket sticky payment method on the personal policy at this point until things develop a bit further.

I planned to add this for the personal policies too, I think it would make code clearer since we would not distinguish between these two.

I think it would not be a problem for the users if the last payment method they used for IOU would be shown as default somewhere else.

**Comment by mountiny** [comment] 2023-06-01 14:41
I mean we should not allow that method in any case, same as we dont give user Paypal option if the recipient does not have paypal address

**Comment by luacmartins** [comment] 2023-06-01 14:48
>Still, I suspect we should fallback on in-app if possible and elsewhere if not, yeah? Like why default to outside of the app if in-app is possible?

I agree that we should default to in-app first and then elsewhere if in-app is not available.

@mountiny since you worked on this for workspaces, would you like to take this issue as well?

**Comment by mountiny** [comment] 2023-06-01 14:53
I can take this on, thanks

**Comment by abdulrahuman5196** [comment] 2023-06-04 18:32
@mountiny  Are we also tracking issue 2 mentioned here https://github.com/Expensify/App/issues/19311#issuecomment-1564448955 or should we create separate issue for it?

**Comment by mountiny** [comment] 2023-06-05 13:27
Thanks I think both of these should be fixed here https://github.com/Expensify/App/pull/19817

**Comment by isabelastisser** [comment] 2023-06-07 20:18
Internal, not overdue.

**Comment by mountiny** [comment] 2023-06-12 22:09
Asking QA to retest this

**Comment by mvtglobally** [comment] 2023-06-12 22:30
no longer repro

![Screenshot_2023-06-13-01-23-24-32_4f9154176b47c00da84e32064abf1c48](https://github.com/Expensify/App/assets/43995119/4d5a75e9-bdcc-4126-a55d-96c993177df9)

https://github.com/Expensify/App/assets/43995119/b7fa5ec0-c3ce-4c9d-b95e-3ae627c8f7df

**Comment by mountiny** [comment] 2023-06-14 18:50
Thanks I think we can close this one now

**Comment by trjExpensify** [comment] 2023-07-07 15:19
I can still reproduce the bug report in the OP. The logic for displaying the [Paypal.me](http://paypal.me/) settlement method seems to be conditional on **the payer** having a PayPal handle added to their account, not the **person that’s owed**.

Steps to repro if you need them: 

1. As userB, add a [Paypal.me](http://paypal.me/) handle i.e tomrhys
2. As userB, send a request to userA for $1.00 such that userB is owed
3. As userA, navigate to the iouReport
4. Observe that the option to Pay via [Paypal.me](http://paypal.me/) is not visible on the report
5. Now as userA add a [PayPal.me](http://paypal.me/) handle.
6. Navigate to the iouReport
7. Observe that the option to Pay via [Paypal.me](http://paypal.me/) is visible on the report

If the person that’s owed has a [Paypal.me](http://paypal.me/) handle added to their account, the payment method should show.

**Comment by isabelastisser** [comment] 2023-07-10 10:02
@mountiny how should we move this forward?

**Comment by mountiny** [comment] 2023-07-10 15:29
I already got a draft PR for this 🙇

**Comment by isabelastisser** [comment] 2023-07-21 15:48
Just confirming that since this is an internal issue, no payments need to be processed. Also, this issue was reported by Applause.

**Comment by mountiny** [comment] 2023-07-21 16:01
Yep closing thnaks!

**Comment by isabelastisser** [comment] 2023-08-03 18:06
@mountiny do we need to do something else here based on @lanitochka17 comment above?

**Comment by lanitochka17** [comment] 2023-08-03 21:29
According to the comment above the  issue not reproduced


https://github.com/Expensify/App/assets/78819774/c38ea6f4-2c7d-4a4c-ad71-b411402a84f3

**Comment by mountiny** [comment] 2023-08-06 18:38
@lanitochka17 correct me if I am wrong but we can close this issue again, I think it seems to work fine from the video

**Closed by mountiny** 2023-08-06 18:38 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
