### ISSUE TITLE
[$1000] Web -  Login Screen animation laggy

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22994] opened 2023-07-17 11:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Open the app, not signed in, so you are on the login screen
2. Notice how on safari the animations is really laggy / not smooth

## Expected Result:
The animation should be smooth

## Actual Result:
The animation is laggy

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS/ Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/be2eb6f6-2920-41f1-bb5d-ce66c02050f9

**Expensify/Expensify Issue URL:**
**Issue reported by:** Hanno Gödecke
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689333058606669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6ca30f65c74633c</li>
        <li>Upwork Job ID: 1681763129811836928</li>
        <li>Last Price Increase: 2023-07-26</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment] 2023-07-19 20:30
I could reproduce easily on Safari (and noticed this on Chrome a few days ago myself - but i can't reproduce on chrome anymore). 

One thing that made it easier to reproduce was switching between staging.new.expensify.com and new.expensify.com

https://recordit.co/IMpjbigQI9

**Comment by b4s36t4** [comment] 2023-07-20 15:29
https://github.com/Expensify/App/issues/23137#issuecomment-1644092706 This would solve this as well.

**Comment by michaelhaxhiu** [comment] 2023-07-31 13:15
closing.

**Comment by michaelhaxhiu** [comment] 2023-07-31 13:16
thanks @thesahindia

**Closed by michaelhaxhiu** 2023-07-31 13:15 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
