### ISSUE TITLE
[Wave Collect] [Workflows] Authorized payer - Admin list is blank if Members tab is not visited before

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38290] opened 2024-03-14 11:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/38221

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is an owner of Collect workspace.
- There is at least another admin in the workspace.
- Bank account is set up in "Make or track payments" and there is an authorized payer.
- User has NOT visited Collect workspace member page (rlogin if visited).

1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Workflows (if it does not appear in side bar, go to More features to trigger it).
4. Click Authorized payer under Make or track payments.
5. Note that the list is empty.
6. Go to Members tab.
7. Return to Workflows > Authorized payer.

## Expected Result:
In Step 4, the list of admins will show up in Authorized payer RHP.

## Actual Result:
In Step 4, the list of admins does not show up in Authorized payer RHP.
It only shows up (Step 7) after members page is rendered in Step 6.
On production, the list shows up without visiting Members tab.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8574a1b5-67c6-4e1c-8fda-1b6c5f119f0c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f3ab1c1e1a527e48</li>
        <li>Upwork Job ID: 1768267208532287488</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-14 11:28
@Beamanator I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-14 11:30
We think that this bug might be related to #wave-control
CC @jason

**Comment by mountiny** [comment] 2024-03-14 13:26
This is not a blocker as these are new feature

I think this needs to be internal because we need to load the policy members when the page is loaded

**Comment by ikevin127** [comment] 2024-03-14 13:33
Offending PR: https://github.com/Expensify/App/pull/37629 - which is still within the regression period (deployed to production 17h ago, see https://github.com/Expensify/App/pull/37629#issuecomment-1995549416).

> I think this needs to be internal because we need to load the policy members when the page is loaded

I confirm and agree that we're missing the `getWorkspaceMembers()` call which we do call when loading the Members page -> reason why we see the list populated **after** visiting the Members page.

**Comment by luacmartins** [comment] 2024-03-14 17:18
cc @lakchote seems like we also need to load the list of members in `OpenPolicyWorkflowsPage`

**Comment by luacmartins** [comment] 2024-03-14 17:22
Got this draft PR - https://github.com/Expensify/Auth/pull/10212

**Comment by luacmartins** [comment] 2024-03-14 17:30
>I confirm and agree that we're missing the getWorkspaceMembers() call which we do call when loading the Members page -> reason why we see the list populated after visiting the Members page.

I don't think this is the right solution since it'd make 2 API calls. The fix is in the backend.

**Comment by MitchExpensify** [comment] 2024-03-19 02:59
Not overdue Melvin, @luacmartins is working on the backend fix here https://github.com/Expensify/Auth/pull/10212

**Comment by luacmartins** [comment] 2024-03-20 15:05
PR in review!

**Comment by trjExpensify** [comment] 2024-04-02 09:22
Can we close this? The linked AuthPR hit prod last week.

**Comment by luacmartins** [comment] 2024-04-02 16:29
Yea, good to close

**Closed by luacmartins** 2024-04-02 16:29 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
