### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500]  Login - Enter key does not submit recovery code

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28092] opened 2023-09-24 16:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23390
## Action Performed:
1. Go to [https://staging.new.expensify.com](https://staging.new.expensify.com/sign-in-with-google)
2. Enter the email of an account with 2FA enabled.
3. Enter magic code
4. Click Use recovery code
5. Enter any incorrect code
6. Hit Enter

## Expected Result:
Enter key submits the recovery code. Error will show up

## Actual Result:
Enter key does not submit the recovery code. No error shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.73-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3492a704-5494-4cf0-93b3-59f36683953e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e8bad5388f05b443</li>
        <li>Upwork Job ID: 1706566640146960384</li>
        <li>Last Price Increase: 2023-09-26</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Contributor | 26933666</li>
</ul></li>
    </ul>
</details>

**Comment by tjferriss** [comment] 2023-09-25 02:48
I'm able to reproduce. At first I thought there was no error because I clicked on the Sign In after entering the incorrect recovery code. As the instructions outline, you need to use the "Enter" button to reproduce the issue.

**Comment by mountiny** [comment] 2023-09-25 07:56
I dont hink this is a deploy blocker and I think it should be handled as a regression from the PR of @alitoshmatov cc @MonilBhavsar @abdulrahuman5196

**Comment by MonilBhavsar** [comment] 2023-09-25 09:35
Sounds good, We'll handle this as a regression 👍

**Comment by tjferriss** [comment] 2023-09-26 07:09
Adding External label so that a C+ can review proposals

**Comment by alitoshmatov** [comment] 2023-09-27 08:26
Working on it, PR will be ready shortly

**Comment by alitoshmatov** [comment] 2023-09-28 17:51
PR is ready - https://github.com/Expensify/App/pull/28409

**Comment by MonilBhavsar** [comment] 2023-09-29 00:14
This was regression from original PR, so updating assignees

**Comment by tjferriss** [comment] 2023-10-06 20:24
Payment Summary:
- Contributor @alitoshmatov $500
- Reviewer @abdulrahuman5196 $500

**Comment by alitoshmatov** [comment] 2023-10-07 04:06
@tjferriss This was a follow up PR and does not require payment

**Comment by abdulrahuman5196** [comment] 2023-10-07 05:47
@tjferriss No payment needed here as discussed - https://github.com/Expensify/App/issues/22335#issuecomment-1748609763

We can close this issue directly.

**Comment by MonilBhavsar** [comment] 2023-10-09 07:19
Yes, thanks everyone! We can close this one 👍

**Closed by MonilBhavsar** 2023-10-09 07:19 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
