### ISSUE TITLE
[HOLD for payment 2024-09-10] [$250]  iOS - Scan - Unable to delete receipt

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#46852] opened 2024-08-06 04:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.16-5
**Reproducible in staging?:** Y 
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**[applausetester+kh040803@applause.expensifail.com](mailto:applausetester+kh040803@applause.expensifail.com)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace chat.
3. Submit an expense with a receipt.
4. Go to transaction thread.
5. Tap on the receipt.
6. Tap 3-dot menu.
7. Tap Delete receipt.

## Expected Result:
Delete receipt modal will appear.

## Actual Result:
Delete receipt modal does not appear. Unable to delete receipt.

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
 
https://github.com/user-attachments/assets/18ca8906-406c-4cf2-a3ba-0f3c796cd922

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0e9a861da3dc3f7</li>
        <li>Upwork Job ID: 1823033534353897628</li>
        <li>Last Price Increase: 2024-08-12</li>
    </ul>
</details>

**Comment by mvtglobally** [comment] 2024-08-06 04:10
We this this might be related to #wave-control

**Comment by bernhardoj** [comment] 2024-08-06 07:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't delete receipt because the delete confirmation modal doesn't show.

### What is the root cause of that problem?
This happens after https://github.com/Expensify/App/pull/45762 where we call the `onSelected` callback of popover immediately. The `onSelected` of the delete receipt option will show another modal and without waiting for the previous modal to hide (which we did before the PR), the second modal won't show.
https://github.com/Expensify/App/blob/f7e265a65f695edd85870bd0c8048cf4578e14fb/src/components/AttachmentModal.tsx#L425-L433

### What changes do you think we should make in order to solve the problem?

We have been fixing this issue by using `Modal.close` to wait for the modal to completely close, however, in our case, calling `Modal.close` will close the transaction receipt modal too. Instead of using `Modal.close` one by one, I propose to take a different approach to fix https://github.com/Expensify/App/issues/45417.

Before the PR, the popover item `onSelected` is called when the modal is completely closed and this will stay as the default behavior. To fix https://github.com/Expensify/App/issues/45417, we can have a new prop for the menu items to tell whether we want to wait for the modal to hide or not, we can call it `selectOnModalHide`.

Here is the detail:
1. Revert https://github.com/Expensify/App/pull/45762 and any changes that add `Modal.close` to fix the regression that comes after the PR.
2. In `selectItem`, if `selectOnModalHide` is false, then call `onSelected` immediately, otherwise, call it when the modal hides.
https://github.com/Expensify/App/blob/f7e265a65f695edd85870bd0c8048cf4578e14fb/src/components/PopoverMenu.tsx#L126-L129

```
if (selectedItem.selectOnModalHide !== false) {
    selectedItemIndex.current = index;
} else {
    selectedItem.onSelected?.();
}
```
3. Then, we can pass `selectOnModalHide` as false to any popover menu that we want to select the item immediately.
Usage example:
```
menuItems.push({
    icon: Expensicons.Link,
    text: 'Open Link',
    selectOnModalHide: false,
    onSelected: () => {
        Link.openLink(getQuickBooksOnlineSetupLink('DF6835925B6E1C85'), CONST.NEW_EXPENSIFY_URL);
    },
});
```

**Comment by zfurtak** [comment] 2024-08-07 06:15
hello 😊
Yesterday I was looking into this case, but haven't found a suitable solution yet, as this exact screen has crazy re-render logic with 3 modals at the same moment. Still thinking... 🤔
I'm not a big fan of reverting changes, as the previous solution was a bit of a workaround. However it might be a good idea to add a flag with a default value and only change it where it's needed. This will make it easier for contributors to work with `PopoverMenu` in the future.
I will continue my investigation today 👍

**Comment by greg-schroeder** [comment] 2024-08-12 12:53
@zfurtak @arosiclair do you guys think this should be sent to `External` or will it be taken care of as a sort of regression?

**Comment by arosiclair** [comment] 2024-08-12 16:27
Yeah this is external. Assigning @zfurtak

**Comment by zfurtak** [comment] 2024-08-13 15:40
hello 😊
I managed to find a solution for this problem without reverting previous changes and in the same time being easier to maintain in the future 🚀

My idea is to add flag to every item that needs calling after the modal is hidden and for this specific case (deleting receipt) I had to changed code in `Modal` component as the logic was adjusted to a fix from the future and was causing a problem here.
I created [a PR](https://github.com/Expensify/App/pull/47341), which is yet in draft as I need one internal review to push it further 🤓

**Comment by war-in** [comment] 2024-08-19 12:25
@fedirjh @arosiclair Could you mark https://github.com/Expensify/App/pull/47341 as ready for review? 🙏 
I'm going to take this over from @zfurtak because she is OOO but I'm not the author and can't mark it 😓

**Comment by arosiclair** [comment] 2024-08-20 21:37
[In review](https://github.com/Expensify/App/pull/47341)

**Comment by greg-schroeder** [comment] 2024-08-27 05:42
Just tracking for record keeping purposes - [original PR](https://github.com/Expensify/App/pull/47341) was reverted.

[New PR](https://github.com/Expensify/App/pull/47991) is in review

**Comment by zfurtak** [comment] 2024-09-04 16:54
The issue is fixed by [this PR](https://github.com/Expensify/App/pull/47991#issuecomment-2327617277).

**Comment by greg-schroeder** [comment] 2024-09-09 06:29
Thanks @zfurtak

**Comment by greg-schroeder** [comment] 2024-09-09 06:29
Regression period 2024-09-10

**Comment by greg-schroeder** [comment] 2024-09-09 06:29
Will prep this for Tuesday

**Comment by greg-schroeder** [comment] 2024-09-11 09:28
@fedirjh I believe you're paid via NewDot now, right? If so, you can make a manual request for $125 for the C+ role.  $250 original price x 50% given the regression/revert.

**Closed by greg-schroeder** 2024-09-11 09:28 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-10-23 10:19
$125 approved for @fedirjh
