### ISSUE TITLE
[HOLD for payment 2024-10-30] [$250] Mweb/Chrome Android - Submit expense - Highlight jumps to manual when clicking back from start/stop

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50265] opened 2024-10-04 18:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** Negasofonias@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Click on FAB and select submit expense
2. Click on distance and select either start or stop
3. Click back and observe the highlight jumps to manual and then to distance like a glitch

## Expected Result:
While clicking back highlight shouldnt bounce/glitch and only remain on distance

## Actual Result:
Highlight bounces to manual and then bounces back to distance

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/463bd1ae-0948-4e68-84a2-f75f9f34275d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843796630602598892</li>
        <li>Upwork Job ID: 1843796630602598892</li>
        <li>Last Price Increase: 2024-10-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by lanitochka17** [comment] 2024-10-04 18:35
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment] 2024-10-08 23:32
This is pretty minor, but it does feel sub-premium so I am going to apply labels to get a fix.

**Comment by kubabutkiewicz** [comment] 2024-10-09 08:39
Hello, Im Jakub from Callstack and would like to help with this issue

**Comment by stephanieelliott** [comment] 2024-10-11 04:31
Awesaome, thanks @kubabutkiewicz! Assigned the issue to you.

**Comment by kubabutkiewicz** [comment] 2024-10-14 18:37
Hi, I am still looking for a root cause of this issue.

**Comment by sobitneupane** [comment] 2024-10-15 05:45
https://github.com/Expensify/App/issues/50265#issuecomment-2411976966

**Comment by kubabutkiewicz** [comment] 2024-10-17 14:06
Hey @sobitneupane I created a PR with a fix for this issue.

**Comment by stephanieelliott** [comment] 2024-10-22 07:13
PR is on staging

**Comment by stephanieelliott** [comment] 2024-10-31 08:41
Summarizing payment on this issue: 

 - Contributor: N/A (agency)
 - Contributor+: @sobitneupane $250 via NewDot -- please request

**Closed by stephanieelliott** 2024-10-31 08:41 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-12 10:52
$250 approved for @sobitneupane
