### ISSUE TITLE
[Hold on #30140] [$500] Error occurs when attempting to Request money after a failed to add a Secondary contact method

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30220] opened 2023-10-23 22:58 UTC
HOLD for https://github.com/Expensify/App/issues/30140

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698081057727509

## Action Performed:
1. Log in to any account.
2. Start a chat with a NEW account X.
3. Go to Profile Settings >> Contact methods >> Add a New Contact Method.
4. Add account X as a Secondary contact method >> an error will occur.
5. Remove the error by clicking the X icon.
6. Log out and then log in again (to ensure that account X is displayed in the search list)
7. Click the FAB button >> select either "Request Money" or "Send Money" option.
8. Select account X (used in step 2) >> enter the amount >> and send the request.
9. Observe that an error will be displayed.
.
## Expected Result: .
The request should be processed successfully without any issues or error messages.
## Actual Result: .
Error occurs when attempting to Request money after a failed to add a Secondary contact method

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/98016b9b-5755-45ca-af3a-649d9376ed25

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/6f4479dc-3d7b-4a31-82de-333dc636a4fc

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/41bb04f7-9a85-4d70-bd26-e160c056444b

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/30595ff9-767a-4f40-b92f-f8734c0b0a90

https://github.com/Expensify/App/assets/38435837/611899b1-da29-42bf-aec4-cbefc3ee710d

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/1603c630-e2d4-4639-b4d2-51db9eadd888

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01256a6696ea3f8e5f</li>
        <li>Upwork Job ID: 1716589937614139392</li>
        <li>Last Price Increase: 2023-11-06</li>
    </ul>
</details>

**Comment by iiredalert** [comment] 2023-10-24 17:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When requesting money using the FAB button, if the chat between the current user and the user we are requesting money from already exists we are presented with the error message that it is unable to create the chat because it already exists.

### What is the root cause of that problem?

When searching for existing chats in IOU.js#getMoneyRequestInformation, we are only including the payer account ID for the search.
```
    if (!chatReport) {
        chatReport = ReportUtils.getChatByParticipants([payerAccountID]);
    }
```

The ReportUtils.getChatByParticipant does a sorted equals on the participant list provided and the participant list that is on the actual chat, but we are only providing a single participant so the existing chat is not found.

### What changes do you think we should make in order to solve the problem?

We should also include the current logged in user's account id in this search. 
```
    if (!chatReport) {
        chatReport = ReportUtils.getChatByParticipants([payerAccountID, currentUser]);
    }
```

This could be passed in from MoneyRequestConfirmPage.js

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-10-27 09:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- After checking, I found out that the steps to reproduce this issue can be reduced:
1. Log in to any account.
2. Start a chat with a NEW account X.
3. Click the FAB button >> select either "Request Money" or "Send Money" option.
4. Select account X (used in step 2) >> enter the amount >> and send the request.
5. Observe that an error will be displayed.
### What is the root cause of that problem?
- In step 2, we created a report with NEW account X, that has report.id = ```reportID-x```.
- Generally, this bug appears because we call ```IOU.requestMoney``` with the first param: report is undefined.
https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/pages/iou/steps/MoneyRequestConfirmPage.js#L157-L158 So we need to create the new optimistic report that has report.id = ```reportID-y```. That leads to BE will return an error "Already has conversation with this account".

**Explain more about "Why we called ```IOU.requestMoney``` with undefined report:**
- In [MoneyRequestParticipantsPage](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js), the report with NEW account X in step 2 is not selected (in other words, the report with NEW account X in step 2 is not displayed in search result), because in this line:
https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/libs/OptionsListUtils.js#L1243-L1244
we use ```!reportOption.login``` to check if the report has multiple participants or not, but it also remove the report with NEW account X in step 2, because its login value is undefined.
- So the ```lodashGet(iou, 'participants.0.reportID', '')``` will return undefined, that lead to the ```getIOUReportID``` below return undefined
https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/libs/actions/IOU.js#L2945-L2947
### What changes do you think we should make in order to solve the problem?
- Because the RCA is the report with new account is removed from search result, so we just need update
- 
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by DylanDylann** [comment] 2023-10-30 08:43
@ntdiary 
> I'm not too sure if we really want to support requesting money from a new account

Currently, user still can request money from a new account.

**Comment by DylanDylann** [comment] 2023-10-30 09:11
@ntdiary 
> Additionally, I think the root cause is that on the participants page, the search results did not return the account info from when the chat was created

Slightly correct! The NEW report is not displayed in the search result, because of this line:
https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/libs/OptionsListUtils.js#L1243-L1244
 so it will create a new info account.

**Comment by conorpendergrast** [comment] 2023-11-10 14:22
Ah, I missed that message earlier, thanks. Putting on hold for https://github.com/Expensify/App/issues/30140

**Comment by conorpendergrast** [comment] 2023-11-16 11:01
No change here; still on hold for https://github.com/Expensify/App/issues/30140

**Comment by conorpendergrast** [comment] 2023-11-29 13:27
Still held on https://github.com/Expensify/App/issues/30140

**Comment by conorpendergrast** [comment] 2023-12-06 14:22
Yep, still held!

**Comment by conorpendergrast** [comment] 2023-12-20 09:45
Still held

**Comment by conorpendergrast** [comment] 2024-01-08 14:34
Still held on https://github.com/Expensify/App/issues/30140

**Comment by conorpendergrast** [comment] 2024-01-24 13:35
This is still held on https://github.com/Expensify/App/issues/30140, which is held on https://github.com/Expensify/Expensify/issues/328013

**Comment by conorpendergrast** [comment] 2024-01-29 16:56
I'm gonna keep this out of a wave until it's off hold. Once it's off hold, it's likely to be part of #vip-vsb

**Comment by anmurali** [comment] 2024-02-16 16:14
Held issues still being worked on, adding a backup BZ member for my OOO

**Comment by lschurr** [comment] 2024-02-19 19:50
Looks like this is still on hold.

**Comment by lschurr** [comment] 2024-02-22 17:10
On hold

**Comment by lschurr** [comment] 2024-03-04 16:17
On hold.

**Comment by lschurr** [comment] 2024-03-12 20:55
This is on hold. And also I think I can remove myself since there are two of us BZ folks on here :)

**Comment by anmurali** [comment] 2024-04-02 20:39
The held issue is low priority so I am gonna toggle this to a monthly and leave it on hold.

**Comment by anmurali** [comment] 2024-05-06 21:15
Same status as above.

**Comment by anmurali** [comment] 2024-06-11 19:02
The issue this is held on is held on [323235](https://github.com/Expensify/Expensify/issues/323235) and we're not working on VIP-SPLIT at the moment. So I am gonna close this and we can reopen and test and fix down the line.

**Closed by anmurali** 2024-06-11 19:02 UTC
Labels: External, Monthly, Help Wanted, Overdue, Bug
