### ISSUE TITLE
[HOLD for payment 2023-07-03] [$1000] Profile page loads infinitely with accountID is undefined

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20854] opened 2023-06-15 20:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with any account
3. Open with URL https://staging.new.expensify.com/a/undefined

## Expected Result: 
Profile page should show ''Hmm... it's not here"
## Actual Result: 
Profile page loads infinitely

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[Screencast from 09-06-2023 13_35_24.webm](https://github.com/Expensify/App/assets/43996225/d061cf34-b51e-4933-a018-76afe118befc)

https://github.com/Expensify/App/assets/43996225/5ae15da3-9b66-4289-ac99-2af5261a185f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686292516315989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5268811dd99e507</li>
        <li>Upwork Job ID: 1670909262930079744</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-06-15 20:18
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
### What is the root cause of that problem?
With accountID being `undefined` string, `openPublicProfilePage` isn't called in `useEffect`.
https://github.com/Expensify/App/blob/82ce35f114a01a0f48180632f1f045aeaae7c8b3/src/pages/ProfilePage.js#L96-L100
So `details` always an empty object,  `hasMinimumDetails` is false, `isLoading` is true
https://github.com/Expensify/App/blob/82ce35f114a01a0f48180632f1f045aeaae7c8b3/src/pages/ProfilePage.js#L124-L125
And loading component always displays
https://github.com/Expensify/App/blob/82ce35f114a01a0f48180632f1f045aeaae7c8b3/src/pages/ProfilePage.js#L212
### What changes do you think we should make in order to solve the problem?
We should check accountID is valid or not in here to change isLoading to false if accountID is invalid
`(lodashGet(details, 'isLoading', false) || _.isEmpty(details)) && (accountID > 0)`
https://github.com/Expensify/App/blob/82ce35f114a01a0f48180632f1f045aeaae7c8b3/src/pages/ProfilePage.js#L125
### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment] 2023-06-15 22:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Profile page loads infinitely with accountID is undefined

### What is the root cause of that problem?
Seems the variable `isLoading` is not derived and assigned correctly to the Views. `isLoading` we are updating optimistically with the `OpenPublicProfilePage` api.

### What changes do you think we should make in order to solve the problem?

- We should depend only on optimistic `isLoading` value
`const isLoading = lodashGet(details, 'isLoading', false);`
https://github.com/Expensify/App/blob/9fda6a55bb5f8997863dd6a6c994934bf36eaad9/src/pages/ProfilePage.js#L125

- For showing the profile details we also need to check `isLoading`
`{hasMinimumDetails && !isLoading && (`
https://github.com/Expensify/App/blob/9fda6a55bb5f8997863dd6a6c994934bf36eaad9/src/pages/ProfilePage.js#L140

- To show loading indicator we can only use `isLoading` value
`{isLoading && <FullScreenLoadingIndicator style={styles.flex1} />}`
https://github.com/Expensify/App/blob/9fda6a55bb5f8997863dd6a6c994934bf36eaad9/src/pages/ProfilePage.js#L212

<details>
<summay>Result</summary>

https://github.com/Expensify/App/assets/14358475/ee2f3c06-f490-41f2-8fa2-35fe54320fd8

</details>

**Comment by anmurali** [comment] 2023-06-19 21:39
Reproduced, added an external label for contributors to pick up

**Comment by sobitneupane** [comment] 2023-06-21 11:33
[Proposal](https://github.com/Expensify/App/issues/20854#issuecomment-1593674498) from @dukenv0307 looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by Pujan92** [comment] 2023-06-21 11:51
@sobitneupane isn't [this](https://github.com/Expensify/App/issues/20854#issuecomment-1593785063) makes more sense where for `isLoading` state we don't rely on  the empty details object?

**Comment by sobitneupane** [comment] 2023-06-21 12:21
@Pujan92 These few lines have some context.

https://github.com/Expensify/App/blob/9fda6a55bb5f8997863dd6a6c994934bf36eaad9/src/pages/ProfilePage.js#L124-L128

It was added in [this PR](https://github.com/Expensify/App/pull/20144). It should have been added to prevent showing blocking view if the details are yet to be loaded.

**Comment by Pujan92** [comment] 2023-06-21 12:34
> It should have been added to prevent showing blocking view if the details are yet to be loaded.

I think that won't be the case as `isLoading` we are only turning to false on api success/failure. And for blocking view we can use the `!isLoading` which I have proposed in the solution. So the priority should be loader -> blocking view -> details content. My thinking is to as we already maintaining `isLoading` then only use that instead of combining other fields.

**Comment by arosiclair** [comment] 2023-06-21 15:01
@Pujan92 The client may already have personal details loaded even while we are loading updates so we shouldn't block the UI on `isLoading` in this case. That's what we have `hasMinimumDetails` for.

**Comment by anmurali** [comment] 2023-07-06 02:54
Sent @hungvu193 an offer - https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/25386217
@sobitneupane can you please complete the checklist and create a manual request?

**Comment by sobitneupane** [comment] 2023-07-10 08:12
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/20144
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/20144#issuecomment-1628451948
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I don't think any change in PR review checklist is required. It was overlooked while adding a new component.

> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-07-10 08:15
**Regression Test Proposal**

1. Login with any account
2. Open any profile route that has invalid route number(eg: /a/undefined)
3. Verify that Not Found Page is displayed.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-07-10 09:05
Requested money from Expensify.

**Comment by arosiclair** [comment] 2023-10-03 09:41
I reached out to @anmurali

**Comment by anmurali** [comment] 2023-10-03 14:37
Sorry about that. I now paid him. And am closing this issue.

**Closed by anmurali** 2023-10-03 14:37 UTC
Labels: External, Daily, Awaiting Payment, Bug
