### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] Pay Someone-Payment amount from "Pay someone" shows 0.00 on LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43907] opened 2024-06-18 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** berhanesarah.testing+@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to FAB
2. Click on "Pay someone"
3. Enter an amount
4. Select a person to share with and click `Pay Elsewhere`
6. Open the report preview and observe the LHN

## Expected Result:
The correct amount paid is displayed 

## Actual Result:
Payment amount shows 0.00

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0973b388-1ddc-48a1-a61d-f78920e7ee39

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ccd1bdf56c93987f</li>
        <li>Upwork Job ID: 1805623061027700874</li>
        <li>Last Price Increase: 2024-06-25</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 102906573</li>
<li>dominictb | Contributor | 102906574</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by lanitochka17** [comment] 2024-06-18 14:18
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-18 14:19
We think that this bug might be related to #wave-collect - Release 1

**Comment by OfstadC** [comment] 2024-06-19 14:20
Thanks! I'm having trouble setting up a wallet to test this as my flow (without a bank/card linked) is different. I'll follow up soon

**Comment by OfstadC** [comment] 2024-06-20 16:03
I'm having an issue adding a wallet - hoping to resolve today so I can test this. 😃

**Comment by mallenexpensify** [comment] 2024-06-21 18:20
Able to repro.  Want me to take this from ya @OfstadC ? 

https://github.com/Expensify/App/assets/22508304/91821012-96ab-4c1a-a678-822444762eb5

logs
[logs-2024-06-21 18_18_43.259.txt](https://github.com/user-attachments/files/15931651/logs-2024-06-21.18_18_43.259.txt)

**Comment by OfstadC** [comment] 2024-06-24 13:14
Added to #vip-split

**Comment by c3024** [comment] 2024-06-25 15:10
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
On paying someone, LHN of the payment transaction shows 0.00 as the paid amount instead of the actual paid amount.
### What is the root cause of that problem?
When we pay someone we create different optimistic reports, report actions, iou actions etc. here
https://github.com/Expensify/App/blob/0bcd005ad37f613c204e323b06280a16c90afd53/src/libs/actions/IOU.ts#L5606
We generate an optimistic IOU report here
https://github.com/Expensify/App/blob/0bcd005ad37f613c204e323b06280a16c90afd53/src/libs/actions/IOU.ts#L5632
and we pass it here 
https://github.com/Expensify/App/blob/0bcd005ad37f613c204e323b06280a16c90afd53/src/libs/actions/IOU.ts#L5641-L5643
to generate `optimisticIOUReportAction` among other things
and here
https://github.com/Expensify/App/blob/0bcd005ad37f613c204e323b06280a16c90afd53/src/libs/ReportUtils.ts#L5174-L5182
we pass the `iouReport.reportID` to the `buildOptimisticIOUReportAction` in `buildOptimisticMoneyRequestEntities`
and the `iouReportID` is further passed here
https://github.com/Expensify/App/blob/0bcd005ad37f613c204e323b06280a16c90afd53/src/libs/ReportUtils.ts#L4163
and we fetch the report from this `iouReportID`here
https://github.com/Expensify/App/blob/0bcd005ad37f613c204e323b06280a16c90afd53/src/libs/ReportUtils.ts#L4024
and pass it to `getMoneyRequestSpendBreakdown` here
https://github.com/Expensify/App/blob/0bcd005ad37f613c204e323b06280a16c90afd53/src/libs/ReportUtils.ts#L4032
to get the `amount`.

This fetching of report with `iouReportID` is what causes the issue because we create all the optimistic values in  `getSendMoneyParams` and they are all written together to Onyx in `sendMoneyElsewhere` and `sendMoneyWithWallet`.

But in the flow of generating the `optimisticIOUReportAction`, we are fetching the report from Onyx here 
https://github.com/Expensify/App/blob/0bcd005ad37f613c204e323b06280a16c90afd53/src/libs/ReportUtils.ts#L4024
during the optimistic generation of the values and the `iouReport` with its `reportID` does not exist in Onyx yet because it has not been written to Onyx yet.

Since the `report` fetched here 
https://github.com/Expensify/App/blob/0bcd005ad37f613c204e323b06280a16c90afd53/src/libs/ReportUtils.ts#L4024
is `undefined` the `totalDisplaySpend` is returned as `0` here
https://github.com/Expensify/App/blob/0bcd005ad37f613c204e323b06280a16c90afd53/src/libs/ReportUtils.ts#L2377

### What changes do you think we should make in order to solve the problem?
We should instead pass the `iouReport` instead of `iouReport.reportID` to `buildOptimisticIOUReportAction` and so on.

<details>
<summary>Test branch with sample code </summary>



https://github.com/c3024/App/tree/correctSendMoneyLHNSubtitle

</details>

### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2024-06-26 06:21
The issue arises because the `report` is accessed in the `getIOUReportActionMessage` while generating the `optimisticIOUReportAction`, before the `optimisticIOUReport` is actually stored in Onyx.

Implementing Solution 2 from @dominictb's [proposal](https://github.com/Expensify/App/issues/43907#issuecomment-2189347083)—which involves replacing `iouReport` with `iouReportID`—would require altering the parameters of `buildOptimisticIOUReportAction` and other related functions. Since `buildOptimisticIOUReportAction` is a widely used function, and using only `iouReportID` (without immediate access to the report in Onyx) appears to function correctly in other scenarios, it would be prudent to avoid this modification.

Therefore, integrating the `!isEmptyObject(report)` check into the conditional and utilizing `total` (a param in the `getIOUReportActionMessage`) to derive the message, as outlined in Solution 1 of @dominictb’s [proposal](https://github.com/Expensify/App/issues/43907#issuecomment-2189347083), seems to be the preferable approach.

🎀 👀 🎀 C+ Reviewed

**Comment by OfstadC** [comment] 2024-06-27 18:53
Friendly bump @stitesExpensify 😃

**Comment by stitesExpensify** [comment] 2024-06-27 21:13
I agree, solution 1 makes sense!

**Comment by OfstadC** [comment] 2024-07-11 18:31
@c3024 Could you please complete the BZ Checklist? Thank you 😃

**Comment by c3024** [comment] 2024-07-12 12:15
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
 
* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #24639 
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/24639/files#r1675756776
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No. This is too specific a bug to be identified earlier.
* [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression test proposal

1. Press on FAB > `Pay someone`
2. Enter some amount 'X' > Next
3. Select a user to share with and press `Pay Elsewhere`
4. Press on the report preview of this paid request and observe the LHN
5. Verify that LHN shows `paid 'X' elsewhere` instead of `paid (or sent) 0.00 elsewhere`

**Comment by c3024** [comment] 2024-07-17 05:53
@OfstadC 

Checklist [here](https://github.com/Expensify/App/issues/43907#issuecomment-2225457703). There seems to be some issue with automation. Payment is due on 17-Jul.

**Comment by OfstadC** [comment] 2024-07-17 18:45
Payment Summary: 
@c3024 paid $250 via Upwork
@dominictb  paid $250 via Upwork

**Comment by OfstadC** [comment] 2024-07-17 18:47
Closing this out since Regression testing has been created and payment has been issued 😃

**Closed by OfstadC** 2024-07-17 18:47 UTC
Labels: External, Daily, Awaiting Payment, Bug
