### ISSUE TITLE
[$1000] Web - Money Request IOU doesn't doesn't appear as latest reportAction

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22884] opened 2023-07-14 10:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new chat.
2. Request money once.
3. Send some message.
4. Request money again.

## Expected Result:
When requesting money, the IOU should be shown at the last, after all messages.

## Actual Result:
IOU isn't the last message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/01cec45f-700b-47f8-818d-b083d6379e89

https://github.com/Expensify/App/assets/93399543/d1429902-3ec7-4462-b087-da6368999989

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689165314598769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01382dceefde674ee1</li>
        <li>Upwork Job ID: 1681366780094275584</li>
        <li>Last Price Increase: 2023-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>ShogunFire | Contributor | 26036615</li>
<li>esh-g | Reporter | 26036617</li>
</ul></li>
    </ul>
</details>

**Comment by Victor-Nyagudi** [comment] 2023-07-14 12:38
If the issue ends up being the IOU report not appearing as the latest `reportAction`, then I think it could be linked to another [money request issue](https://github.com/Expensify/App/issues/22796) where the message in the LHN displays the other user's email instead of their display name after deleting the message directly after the money request.

**Comment by multijump** [comment] 2023-07-14 20:21
I couldn't reproduce this issue in v1.3.41-0

**Comment by sakluger** [comment] 2023-07-18 18:16
This seems like a unique bug, adding external label.

**Comment by ShogunFire** [comment] 2023-07-19 13:08
I have another bug when I follow the steps: 
https://expensify.slack.com/archives/C049HHMV9SM/p1689771818966349

**Comment by Talha345** [comment] 2023-07-19 13:13
> e another bug when I follow t

@ShogunFire We already have a issue for that:
https://github.com/Expensify/App/issues/23038

Please mark your bug report as dupe.

**Comment by ShogunFire** [comment] 2023-07-19 13:16
Thanks @Talha345 I should verify better before reporting bugs

**Comment by Talha345** [comment] 2023-07-19 13:38
Unable to reproduce on STG.

**Comment by ShogunFire** [comment] 2023-07-19 16:33
I made a proposal that fix both bugs[ here](https://github.com/Expensify/App/issues/23038#issuecomment-1642405186)

**Comment by sakluger** [comment] 2023-07-21 02:07
@ShogunFire just go confirm, are you saying that this bug only happens when you request money from someone who does not have an Expensify account? And you think that this bug has the same root cause as https://github.com/Expensify/App/issues/23038?

**Comment by ShogunFire** [comment] 2023-07-21 02:16
Yes I think

**Comment by ShogunFire** [comment] 2023-07-21 02:25
Actually as @Victor-Nyagudi said here https://github.com/Expensify/App/issues/22884#issuecomment-1635795980 it happens not only to people that don't have expensify but to people that have not send us a message since we don't have their login in personalDetails

**Comment by sakluger** [comment] 2023-07-25 01:14
@jasperhuangg - @ShogunFire thinks that this issue is happening because of the changes we made around personal details. Do you think this is related to the privacy project changes?

**Comment by sakluger** [comment] 2023-07-27 23:20
@jasperhuangg just checking in again.

**Comment by sakluger** [comment] 2023-08-01 15:59
Checked with @jasperhuangg via DM.

**Comment by sakluger** [comment] 2023-08-05 01:07
Checked with @jasperhuangg again, I'll ask in Slack on Monday if I don't hear back.

**Comment by sakluger** [comment] 2023-08-07 20:09
Tagged @jasperhuangg in the bug report Slack thread. Jasper is out until tomorrow, so we'll likely need to wait another day or two.

**Comment by jasperhuangg** [comment] 2023-08-09 17:31
This seems related to the fact that we're getting the `login` from the personalDetails, but it's undefined. However, I am confused as to how we're starting a Money Request flow with someone you don't have a login for, since we're only allowing options in the options list that have logins [here](https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.js#L632-L633).

If @ShogunFire can explain why that is happening then I'd be happy to accept their proposal.

**Comment by ShogunFire** [comment] 2023-08-09 18:49
It happens because in getOptions here: https://github.com/Expensify/App/blob/d4490726ca1f6cc340b3c03044fd8c2ca350fdb8/src/libs/OptionsListUtils.js#L803-L813

If there is no options in our known personal details but the search value is a valid email or phone number we create and return an option userToInvite.

This option will then be added to the list that the user can choose from, for example here:

https://github.com/Expensify/App/blob/c74032fc99deca987e9238d7da850a38d8895975/src/pages/NewChatPage.js#L99-L106

**Comment by jasperhuangg** [comment] 2023-08-09 20:24
@ShogunFire got it, thanks for clarifying! If that's the case then your proposal sounds good to me. Assigning you

**Comment by jasperhuangg** [comment] 2023-08-09 20:25
Not overdue

**Comment by ShogunFire** [comment] 2023-08-10 03:19
Thanks @jasperhuangg I am almost done with the PR, is the C+ going to review it ? It's working but I am doubting if there is a cleaner way to do it. Also I created a new optional argument to buildOptimisticIOUReport which is called in multiple places, do you think I should verify if other places need to pass that argument ?

**Comment by jasperhuangg** [comment] 2023-08-10 17:08
Yes, the @thesahindia should be able to help you review it.

**Comment by ShogunFire** [comment] 2023-08-10 17:09
PR ready for review

**Comment by ShogunFire** [comment] 2023-08-15 03:29
@jasperhuangg It doesn't look like @thesahindia is present for the review

**Comment by jasperhuangg** [comment] 2023-08-15 19:47
Unassigning @thesahindia since they weren't able to review any proposals here and haven't been able to review the PR.

**Comment by sakluger** [comment] 2023-08-23 21:27
@mountiny I looked through the PR and it looks like we may be going a different direction (although if seems that @ShogunFire has one more idea). If we do go a different direction, would we close out this GH issue or just restart the process of accepting proposals?

**Comment by mountiny** [comment] 2023-08-24 00:58
Yeah the problem with these flows is that using email in combination with the secure logins is very hard and there is many workarounds.

So the better solution is to update the flows to accept accountIDs but that also means more backend work. Aldo already has that on his plate but currently its deprioritized to focus on the recent waves.

I think it might be better to close/ hold this for the solution with accountIDs as thats the real solution

**Comment by mountiny** [comment] 2023-08-24 13:39
I have not been following this issue that much but isn't the problem here the created timestamp update for the report preview action? Do we correctly update it when optimistic actions take place?

Ot is the issue body outdated

**Comment by luacmartins** [comment] 2023-08-25 20:19
I'm not able to reproduce this issue following the steps in the OP, am I missing something?

**Comment by luacmartins** [comment] 2023-08-25 21:21
Chatted 1:1 with @jasperhuangg and we decided to close this issue since it's no longer reproducible with the instructions in the OP. Please report a new bug if anything comes up.

**Closed** 2023-08-25 21:22 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
