### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] Dupe detect - Removed expense during review offline is accessible & fields open not here page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45917] opened 2024-07-22 15:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two same expenses (same amount. date and merchant)
4. Go to any transaction thread
5. Go offline
6. Click Review duplicates
7. Click Keep this one (any)
8. On confirmation page, click Confirm
9. Return to the expense report
10. Click on the expense preview with skeleton

## Expected Result:
The expense which is removed during duplicate review offline should be crossed out and inaccessible

## Actual Result:
The expense which is removed during duplicate review offline is accessible and all the fields in the transaction thread lead to not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/26de8a30-03db-4330-9b1d-8edaf127f882

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011cf834f88beec2ec</li>
        <li>Upwork Job ID: 1815779453230360541</li>
        <li>Last Price Increase: 2024-07-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by MariaHCD** [comment] 2024-07-22 16:01
@lanitochka17 just to confirm, this bug is not reproducible on production? Do you have a recording of the behavior on production?

**Comment by roryabraham** [comment] 2024-07-22 16:20
was able to reproduce this one locally

**Comment by roryabraham** [comment] 2024-07-22 18:49
A broad set of changes will be required here:

- update the `lastMessageText` and `lastMessageHTML` for the `policyExpenseChat`
- set `message.deleted` for the IOU action on the expense report
- update the `message[0].text` and `message[0].html` for the `REPORT_PREVIEW` action in the `policyExpenseChat`
- update the `MoneyRequestAction` component to return null if the action is deleted

**Comment by roryabraham** [comment] 2024-07-22 20:25
WIP PR to fix this issue: https://github.com/Expensify/App/pull/45961

**Comment by francoisl** [comment] 2024-07-23 01:30
Any luck with that PR @roryabraham?

**Comment by roryabraham** [comment] 2024-07-23 02:06
That PR fixes this issue, and I was working on fixing related issues where the total on the expense report and policyExpenseChat are not optimistically updated to account for the merged dupes. I think I may have fixed it but didn't get a chance to test it

**Comment by mountiny** [comment] 2024-07-23 06:25
Demoting per the discussing in[ slack](https://expensify.slack.com/archives/C07J32337/p1721715910391279?thread_ts=1721712044.479069&cid=C07J32337), the feature is behind beta and since we have only few blockers left, not going to hold on this one

**Comment by roryabraham** [comment] 2024-07-23 16:02
Just added external to get a job created for the C+ review. The [PR](https://github.com/Expensify/App/pull/45961) is already ready for review

**Comment by brunovjk** [comment] 2024-07-23 16:04
Sure! I will review after lunch. Thank you.

**Comment by brunovjk** [comment] 2024-07-30 18:32
[PR](https://github.com/Expensify/App/pull/45961) is on staging.

**Comment by OfstadC** [comment] 2024-08-06 13:58
@brunovjk Please complete the checklist today so we can issue payment tomorrow 😃

**Comment by brunovjk** [comment] 2024-08-06 17:09
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: **N/A**
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. **Yes**
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal:**

1. Sign in
2. Create a workspace if needed
3. Submit two duplicate expenses to the policy expense chat for that workspace
4. Open the expense thread for one of the violations (it should appear in the LHN with a red dot)
5. Go offline
6. Click `Resolve Duplicates`
7. Pick either one of the duplicate transactions then confirm
8. _verify_ that the total of the report updates correctly in the LHN.
9. Click on the workspace chat.
10. _verify_ that there's no skeleton action for the removed expense
11. _verify_ that the expense report preview shows the correct total

Do we agree 👍 or 👎

**Comment by OfstadC** [comment] 2024-08-07 13:26
@brunovjk I sent you a manual offer in Upwork - can you accept? 😃 Thanks!

**Comment by OfstadC** [comment] 2024-08-07 13:27
https://www.upwork.com/nx/wm/offer/103433638

**Comment by brunovjk** [comment] 2024-08-07 13:29
Done @OfstadC, thank you

**Comment by OfstadC** [comment] 2024-08-07 22:26
https://github.com/Expensify/Expensify/issues/418708

Closing since regression test was created and Upwork contract has been paid/closed

**Closed by OfstadC** 2024-08-07 22:26 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
