### ISSUE TITLE
[$250] Workspace - WS profile image revert to previous avatar everytime on uploading a new avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39179] opened 2024-03-28 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+cknov@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app & login
2. Go to settings >> Workspaces >> select any WS with no profile image
3. Select Profile
4. Tap on the avatar icon >> Upload photo >> Choose image & save
5. Repeat step 4 few times uploading new image everytime

## Expected Result:
WS profile image should display the correct saved avatar & not revert to previous image everytime on uploading new avatar

## Actual Result:
WS profile image revert to previous avatar everytime on uploading a new avatar
Issue happens in both online & offline modes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9597021b-4940-4f20-aa0f-5c981e9489bb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc1549a219183fea</li>
        <li>Upwork Job ID: 1773417569304784896</li>
        <li>Last Price Increase: 2024-05-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-28 14:11
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Valo21** [comment] 2024-03-29 04:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

There is a persistent reversion of the profile image to a previous avatar every time a new avatar is uploaded.

### What is the root cause of that problem?

It is a common issue of react native when catching images. In the AvatarWithImagePicker component the source url is being cached by react native so it will load a previous version of it after it is uploaded.
https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/components/AvatarWithImagePicker.tsx#L318-L331

### What changes do you think we should make in order to solve the problem?

The url of the image should be modified adding query params to break the caching so it will load the new version after is uploaded

**Comment by Valo21** [comment] 2024-03-29 04:31
Contributor details
Your Expensify account email: [valentin.faciano@gmail.com](mailto:valentin.faciano@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01e421ea2282a582ee

**Comment by s77rt** [comment] 2024-03-29 21:40
I'm not able to reproduce but I'm seeing a different bug where the image is not cut properly

https://github.com/Expensify/App/assets/16493223/f45cdd30-dbf7-4f1b-809f-7152eed03102

**Comment by s77rt** [comment] 2024-03-29 21:41
@Valo21 Thanks for the proposal. Were you able to reproduce the bug? And is the same bug present throughout the app e.g. on the profile page?

**Comment by Valo21** [comment] 2024-03-29 22:50
Yeah, i tried on the app from the play store, i have problems installing the dependencies to run the repository locally. The bug was the same from the video and i didn't have any problems cropping the image. I didn't see the bug in other pages. Anyways its a little tricky because it happens sometimes and others don't, so it is possible that is happening in other images, it happend to me time ago while i was practicing with react native.

**Comment by s77rt** [comment] 2024-03-30 23:49
@Valo21 Can you elaborate on how we will add the query param to new images without breaking the cache functionality?

**Comment by Valo21** [comment] 2024-03-31 01:07
@s77rt the query param could be added in the source attribute of <Avatar/> inside the AvatarWithImagePicker component. So the image will be refreshed every time that component loads. It is only adding a random string as a query param like using Date.now() so react will recognize it as a diferent version of the image. It could be applied only to components that are gonna be updated like in this case.
Also instead of using the query param, the image cache could be cleared before the image is uploaded. I think there is a function for something like that:
https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/libs/actions/Policy.ts#L1495-L1503
I'm not sure about this anyways, correct me if i am wrong.

**Comment by s77rt** [comment] 2024-04-01 00:49
@Valo21 That will break the cache functionality i.e. we will always download the image even if it didn't change

**Comment by s77rt** [comment] 2024-04-01 00:49
@Valo21 The function you linked is unrelated to cache

**Comment by s77rt** [comment] 2024-04-04 20:10
Still looking for proposals

**Comment by s77rt** [comment] 2024-04-08 19:40
Still looking for proposals...

**Comment by s77rt** [comment] 2024-04-15 11:05
Not overdue ^

**Comment by s77rt** [comment] 2024-04-29 16:34
@puneetlath Did you get a chance to look into the BE fix?

**Comment by puneetlath** [comment] 2024-04-29 18:22
I haven't had a chance yet. It's on my list, but lots of higher priority stuff ahead of it.

**Comment by mvtglobally** [comment] 2024-05-22 04:39
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-05-30 01:26
Issue not reproducible during KI retests. (Second week)

**Comment by puneetlath** [comment] 2024-05-31 01:09
Hm, seems like maybe this got fixed somewhere along the way. Gonna close it out since it's no longer reproducible.

**Closed by puneetlath** 2024-05-31 01:09 UTC
Labels: Monthly, Internal, Help Wanted, Overdue, Bug
