### ISSUE TITLE
[HOLD for payment 2023-08-08] [$1000] Android - User icons overlapping in the group header and outline is not showing perfectly.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22952] opened 2023-07-15 19:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App and Go offline
2. Press FAB > New Group
3. Select 8 participants > Press Create Group
4. Observe the page Header where one avatar of the user and +7 are written & also observe the 8 Avatars in the Chat Header

## Expected Result:
Chat header icons should be like the ios where we can not see the avatar of another user from semi-transparent background.

## Actual Result:
Chat header icons should be like the ios where icons do not overlap another icon.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.41-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Group-icon-overlap](https://github.com/Expensify/App/assets/93399543/2812d629-3350-4b1f-a633-85575b300589)
![group-chat-header](https://github.com/Expensify/App/assets/93399543/3bdf7a2e-e950-405d-8a47-97ecd9487831)

https://github.com/Expensify/App/assets/93399543/6cbdabcb-db26-4edf-86a3-4ba044ff6e3f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689364266408539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194b561dccf84201f</li>
        <li>Upwork Job ID: 1681461212925595648</li>
        2023-07-19<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 25762373</li>
<li>jayeshmangwani | Contributor | 25762376</li>
<li>jayeshmangwani | Reporter | 25762379</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-15 19:44
## Proposal
from: @jayeshmangwani 

### Please re-state the problem that we are trying to solve in this issue.
User icons overlapping in the group header and outline is not showing perfectly.

### What is the root cause of that problem?
On [Android](https://github.com/facebook/react-native/issues/10530), when we apply opacity to a parent, all of its children will inherit the opacity; context is here in the [issue](https://github.com/Expensify/App/issues/15283#issuecomment-1439413441)

### What changes do you think we should make in order to solve the problem?
We need to pass [needsOffscreenAlphaCompositing](https://reactnative.dev/docs/view#needsoffscreenalphacompositing) prop to the OfflineWithFeedback parent Of the Group page Header and Chat header Components here so that Android can align with other platforms and child does not inherit the opacity

At these two places, we need to add the `needsOffscreenAlphaCompositing` prop to OfflineWithFeedback

**1. For Report screen header**
https://github.com/Expensify/App/blob/0b00e1cc82a4f6023aff6b89796a91fba6be91a2/src/pages/home/ReportScreen.js#L330-L333

**2. For Chat Header where 8 users Avatar is visible**
https://github.com/Expensify/App/blob/0b00e1cc82a4f6023aff6b89796a91fba6be91a2/src/pages/home/report/ReportActionItemCreated.js#L58-L62

**This Same Issue happens at a few places on the Android**

**1. Workspace Thread header**
![WS-header](https://github.com/Expensify/App/assets/35371050/9cc50cb9-5814-4d46-a8a4-551b1ca63a6e)

**2. LHN OptionsList**

![LHN-OptionsList](https://github.com/Expensify/App/assets/35371050/6816039d-a600-42d4-bb37-de854a958dc1)

We also need to add the `needsOffscreenAlphaCompositing` prop to parent OfflineWithFeedback. 

https://github.com/Expensify/App/blob/0b00e1cc82a4f6023aff6b89796a91fba6be91a2/src/components/OptionRow.js#L148-L151

https://github.com/Expensify/App/blob/0b00e1cc82a4f6023aff6b89796a91fba6be91a2/src/components/LHNOptionsList/OptionRowLHN.js#L134-L137

**Note: We will test all the overlapping icons offline on Android in part of this issue so that those can be fixed in this single issue**

**Comment by jayeshmangwani** [comment] 2023-07-16 09:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User icons overlapping in the group header and outline is not showing perfectly.

### What is the root cause of that problem?
On [Android](https://github.com/facebook/react-native/issues/10530), when we apply opacity to a parent, all of its children will inherit the opacity; context is here in the [issue](https://github.com/Expensify/App/issues/15283#issuecomment-1439413441)

### What changes do you think we should make in order to solve the problem?
We need to pass [needsOffscreenAlphaCompositing](https://reactnative.dev/docs/view#needsoffscreenalphacompositing) prop to the OfflineWithFeedback parent Of the Group page Header and Chat header Components here so that Android can align with other platforms and child does not inherit the opacity

At these two places, we need to add the `needsOffscreenAlphaCompositing` prop to OfflineWithFeedback

**1. For Report screen header**
https://github.com/Expensify/App/blob/0b00e1cc82a4f6023aff6b89796a91fba6be91a2/src/pages/home/ReportScreen.js#L330-L333

**2. For Chat Header where 8 users Avatar is visible**
https://github.com/Expensify/App/blob/0b00e1cc82a4f6023aff6b89796a91fba6be91a2/src/pages/home/report/ReportActionItemCreated.js#L58-L62

**This Same Issue happens at a few places on the Android**

**1. Workspace Thread header**
![WS-header](https://github.com/Expensify/App/assets/35371050/9cc50cb9-5814-4d46-a8a4-551b1ca63a6e)

**2. LHN OptionsList**

![LHN-OptionsList](https://github.com/Expensify/App/assets/35371050/6816039d-a600-42d4-bb37-de854a958dc1)

We also need to add the `needsOffscreenAlphaCompositing` prop to parent OfflineWithFeedback. 

https://github.com/Expensify/App/blob/0b00e1cc82a4f6023aff6b89796a91fba6be91a2/src/components/OptionRow.js#L148-L151

https://github.com/Expensify/App/blob/0b00e1cc82a4f6023aff6b89796a91fba6be91a2/src/components/LHNOptionsList/OptionRowLHN.js#L134-L137

**Note: We will test all the overlapping icons offline on Android in part of this issue so that those can be fixed in this single issue**

**Comment by michaelhaxhiu** [comment] 2023-07-19 00:29
reproduced!

**Comment by s77rt** [comment] 2023-07-19 19:03
Started a Slack thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1689793295080599

**Comment by s77rt** [comment] 2023-07-22 00:48
Not overdue. Based on the latest discussion on the slack thread, the use of `needsOffscreenAlphaCompositing` may cause some "incompatibilities". In this case the global fix seems less favorable but I think it's still worth it as those incompatibilities can be fixed. I have bumped the thread for more :eyes:.

**Comment by s77rt** [comment] 2023-07-24 10:08
Not overdue, Melvin. No activity on that Slack thread yet but we will probably go with a solution this week

**Comment by jayeshmangwani** [comment] 2023-07-27 07:43
@s77rt [PR](https://github.com/Expensify/App/pull/23710) is ready for Review

**Comment by s77rt** [comment] 2023-08-03 10:13
- The PR that introduced the bug has been identified: None. This is an Android thing
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: We have this (#expensify-open-source) https://expensify.slack.com/archives/C01GTK53T8Q/p1689793295080599
- Determine if we should create a regression test for this bug: No

**Comment by michaelhaxhiu** [comment] 2023-08-04 15:31
Note: I'm preparing to go OOO for ~2 weeks and need a BZ buddy to watch over this in the meantime. 🙏

Next steps:

Wait for 8/8 to arrive. After that's done, we'll process payments as follows (assuming no regressions 🤞):

- [ ] Bug reporter & Contributor that fixed it $1750 ($1500 + $250) for @jayeshmangwani
- [ ] C+ $1500 for @s77rt 

I'll take this over when I return if it's not complete. Thanks in advance @kadiealexander

**Comment by kadiealexander** [comment] 2023-08-07 02:28
https://www.upwork.com/ab/applicants/1681461212925595648/hired

**Comment by kadiealexander** [comment] 2023-08-08 03:41
Everyone is paid! 🎉

**Closed by kadiealexander** 2023-08-08 03:41 UTC
Labels: External, Daily, Awaiting Payment, Bug
