### ISSUE TITLE
[$250] Xero- Unable to change Preferred exporter and Purchase bill date in Export menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45768] opened 2024-07-19 12:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4735600
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition
Xero connection is established in the workspace.
There is more than one admin in the workspace
1. Navigate to Workspace settings > Accounting
2. Click on Export
3. Click
4. Select the unchecked workspace admin
5. Navigate back to Accounting page
6. Notice that an error is displayed that "can't connect to Xero"
7. Navigate back to export settings
8. Click Purchase Bill Date
9. Change to one of the other options e.g. Export date
10. Navigate back to the Accounting page
11. Notice that an error is displayed that "can't connect to Xero"

## Expected Result:
In step 4. The selected workspace admin is displayed as the preferred exporter
In step 10. The changed setting is displayed in the purchase bill date

## Actual Result:
In step 4. The default workspace admin is displayed as the preferred exporter and not the changed one
In step 10. The default setting is displayed in the purchase bill date and not the changed one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/89f30bf6-7561-44bb-8585-da9507dc7ee7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ba7b3a401236944</li>
        <li>Upwork Job ID: 1815702924409852725</li>
        <li>Last Price Increase: 2024-08-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by lanitochka17** [comment] 2024-07-19 12:48
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-19 12:49
We think that this bug might be related to #wave-collect - Release 2

**Comment by zanyrenney** [comment] 2024-07-23 10:57
Triaged!

**Comment by zanyrenney** [comment] 2024-07-23 10:58
@lakchote maybe one for you if its a quick fix?

**Comment by trjExpensify** [comment] 2024-07-24 00:10
Lucien is now out for a month on leave. @rushatgabhane @mananjadhav @hungvu193 any ideas what might have broken here?

**Comment by trjExpensify** [comment] 2024-07-24 10:42
Let's ask for a retest maybe?

**Comment by hungvu193** [comment] 2024-07-24 10:43
Agreed 😄

**Comment by trjExpensify** [comment] 2024-07-24 13:38
Put it on retest-weekly.

**Comment by situchan** [comment] 2024-07-25 05:06
Waiting for retest

**Comment by zanyrenney** [comment] 2024-08-02 14:42
Just tried and also can't repro this anymore.

**Comment by situchan** [comment] 2024-08-05 05:12
Waiting for QA team to re-test

**Comment by mvtglobally** [comment] 2024-08-09 04:31
Issue is reproducible during KI retests. 

https://github.com/user-attachments/assets/0552e152-9e36-4946-8200-1b218b37654d

**Comment by trjExpensify** [comment] 2024-08-09 16:47
I think this is probably a dupe of: https://github.com/Expensify/App/issues/44398

**Comment by zanyrenney** [comment] 2024-08-13 19:15
Closing in favour of issue above! https://github.com/Expensify/App/issues/44398

**Closed by zanyrenney** 2024-08-13 19:15 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
