### ISSUE TITLE
[HOLD for Payment 2024-09-24] Implement Android conversation notifications

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#37604] opened 2024-03-01 14:58 UTC
In Android 11, conversation notifications were added that offer a richer notification experience for messaging.

![conv_notification](https://github.com/Expensify/Expensify/assets/6833644/ef74b03b-2e1c-42fc-b9d6-6d86f79252eb)

Conversation notifications are placed highest in the notification shade and prominently display avatars and names with the app's logo in the corner. Individual notifications can be marked as a priority allowing them to cut through Do Not Disturb settings. This is very similar to communication notifications which we implemented for iOS [here](https://github.com/Expensify/App/pull/32765).

- [Android docs](https://developer.android.com/develop/ui/views/notifications/conversations)

**Comment by arosiclair** [comment] 2024-03-01 15:02
FYI this is a copy of the old internal issue here: https://github.com/Expensify/Expensify/issues/258528

**Comment by arosiclair** [comment] 2024-03-01 15:12
From the [docs](https://developer.android.com/develop/ui/views/notifications/conversations), we need to implement these to get conversation notifications

 - [x] The notification uses [MessagingStyle](https://developer.android.com/reference/androidx/core/app/NotificationCompat.MessagingStyle).
- [ ] (Only if the app targets Android 11 or higher) The notification is associated with a valid [long-lived](https://developer.android.com/reference/androidx/core/content/pm/ShortcutInfoCompat.Builder#setLongLived(boolean)) dynamic or cached sharing shortcut. The notification can set this association by calling [setShortcutId()](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setShortcutId(java.lang.String)) or [setShortcutInfo()](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setShortcutInfo(androidx.core.content.pm.ShortcutInfoCompat)). If the app targets Android 10 or lower, the notification doesn't have to be associated with a shortcut, as discussed in the [fallback options](https://developer.android.com/develop/ui/views/notifications/conversations#non-11) section.

Which means we should just need to implement sharing shortcuts. I'm going to look for a contributor to work on this.

@robertKozik you worked on our last issue for clearing notifications on Android. Would you be interested in working on this as well?

**Comment by staszekscp** [comment] 2024-03-04 14:57
Hey @arosiclair! I can take care of this feature, because I work currently on the HybridApp, where we will refactor notifications in order to make sure the work for both OldDot, and NewDot. However, could we slightly wait with implementation of this feature? I just want to make sure that the notifications work fine after the refactor, and then, as a follow-up, I will add the conversation notifications to Android.

**Comment by arosiclair** [comment] 2024-03-04 15:26
Makes sense I'll assign you and put this on hold. Keep us updated 🙏

**Comment by bfitzexpensify** [comment] 2024-03-13 00:00
Still held @staszekscp?

**Comment by arosiclair** [comment] 2024-03-25 14:25
Still held I believe. cc @staszekscp for any updates

**Comment by staszekscp** [comment] 2024-03-25 14:29
Hey! Sorry, I missed the previous comment - the [PR with the refactor](https://github.com/Expensify/Mobile-Expensify/pull/12610) is open, I just have to find one fix for a bug that I noticed. After merging I will work on this issue - I have already done some small testing, and I think I know what needs to be done 😄

**Comment by bfitzexpensify** [comment] 2024-04-07 13:18
Still held on https://github.com/Expensify/Mobile-Expensify/pull/12610

**Comment by bfitzexpensify** [comment] 2024-04-16 22:45
Remains held

**Comment by bfitzexpensify** [comment] 2024-04-23 15:50
Stil held on https://github.com/Expensify/Mobile-Expensify/pull/12610

**Comment by arosiclair** [comment] 2024-05-03 16:37
Asked for an update on the PR. Still held for now.

**Comment by bfitzexpensify** [comment] 2024-05-13 20:28
Still held.

**Comment by bfitzexpensify** [comment] 2024-05-24 00:03
Still held, but the latest comment in that PR indicates we're getting closer:

>Seems like we need to merge main, but probably also fix New Arch + iOS still, so this is close to being ready for a merge

**Comment by bfitzexpensify** [comment] 2024-05-30 22:47
Still held.

**Comment by arosiclair** [comment] 2024-06-11 14:27
Haven't been able to make progress in the last couple months. Dropping this to monthly.

**Comment by arosiclair** [comment] 2024-07-15 16:33
Looks like https://github.com/Expensify/Mobile-Expensify/pull/12610 was merged! @staszekscp what's the plan for this issue?

**Comment by bfitzexpensify** [comment] 2024-08-13 14:01
Bump @staszekscp

**Comment by staszekscp** [comment] 2024-08-13 14:36
Sorry, I haven't seen the last bump! Actually I could try to open a PR tomorrow with the change, if nothing critical comes up for the HybridApp release. If something happens, I'll pass the task to someone in the SWM team for next week in order to finish it. Again, sorry for the delay, I was swamped by the HybridApp issues 😢

**Comment by arosiclair** [comment] 2024-08-14 12:24
No worries this is definitely lower priority compared to core functionality for the HybridApp

**Comment by staszekscp** [comment] 2024-08-14 13:51
I had a bit of time to work on that, and the "styling" part is done - the notification appears as the conversation type, and works just fine 😄 The thing that I need to work on, is to implement the conversation shortcut. It's a feature to open a conversation, after selecting it from a menu that appears after long press on the app icon. The shortcut is there, but it doesn't open any chat yet

https://github.com/user-attachments/assets/67c6e8e6-7161-49ef-9ae2-f74ea186fa9a

**Comment by arosiclair** [comment] 2024-08-14 15:53
Nice!

> It's a feature to open a conversation, after selecting it from a menu that appears after long press on the app icon. The shortcut is there, but it doesn't open any chat yet

Lemme know if you need any help figuring this part out

**Comment by staszekscp** [comment] 2024-08-14 16:33
Thanks! Actually I've just gotten it working 😄 I still need to do a major cleanup, but on Monday I'll open the PR! (There is a bank holiday in Poland, and we'll be OOO on Thursday and Friday!

https://github.com/user-attachments/assets/a7700951-e056-42ab-80d8-a57258517d22

**Comment by bfitzexpensify** [comment] 2024-09-06 14:53
I am heading out of office until September 21st, so assigning a buddy to watch over this in my absence. 

Current status: PR being worked on in https://github.com/Expensify/App/pull/47626

**Comment by garrettmknight** [comment] 2024-09-19 19:43
Awaiting payment

**Comment by bfitzexpensify** [comment] 2024-09-23 11:08
I'm back from OOO, and can take this one back over - thanks for keeping an eye on it @garrettmknight

**Comment by bfitzexpensify** [comment] 2024-09-24 08:20
Regression steps proposed in https://github.com/Expensify/Expensify/issues/430593

Payment complete. Closing this one out!

**Closed by bfitzexpensify** 2024-09-24 08:20 UTC
Labels: Daily, NewFeature, Awaiting Payment
