### ISSUE TITLE
Invite member - Incorrect selection of member using Tab key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25883] opened 2023-08-24 19:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify,com
2. Go to Settings > Workspace > Members > Invite.
3. Press Tab on keyboard to navigate to the checkbox next to the member (not the first member) and press Enter.
4. Repeat Step 3 but navigate to the member row instead of the checkbox.

## Expected Result:
In Step 3 and 4, only the selected member is selected.

## Actual Result:
In Step 3, only the member in green highlight is selected, not the one selected by checkbox
In Step 4, the first member in green highlight is selected and also the member selected via Tab key

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.57-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e09295b2-43a8-4604-bdfd-8c076fb27bb3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2023-08-24 22:49
This appears to be caused by https://github.com/Expensify/App/pull/22622

**Comment by thienlnam** [comment] 2023-08-24 22:50
There seems to be a few focus issues from the above - cc @thiagobrez do you have the chance to take a look here?

**Comment by thiagobrez** [comment] 2023-08-25 07:28
@thienlnam Yeah, taking a look right now!

**Comment by mountiny** [comment] 2023-08-25 19:43
confirmed this si fixed in staging, no reporting bonus, closing

**Closed by mountiny** 2023-08-25 19:43 UTC
Labels: Engineering, Hourly
