### ISSUE TITLE
[$500] [HOLD for payment 2024-08-19] CRITICAL: Add Pay as Business option for invoices sent to an individual who is admin of their primary workspace

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#40438] opened 2024-04-18 13:29 UTC
# Part of the **Invoicing V0.3** project
Main issue: https://github.com/Expensify/Expensify/issues/341717
Doc section: [Invoicing V1](https://docs.google.com/document/d/1HhnjCVUVN8gw3vfxRA4jCXXQvuIfm1puMhzHoOKe5jY/edit#bookmark=id.1pnsna7h8vtu)
Project: [#vip-billpay](https://join.slack.com/share/enQtNjkzNDU4NTI3OTY4Ni03M2RlY2IwNzhjMDEzMGE1NjZmYmM5MGJmZDZmNTc4NjRhYmRlOWM4NzMzYmJmOGUyZDAzNWFiNTgyNjQ0YTg0)

# Feature Description
Implement the Pay as business option in the App for the individuals who are admin of their primary workspace. This also includes calling the PayInvoice API command.

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d3f5acd99a5e211f</li>
        <li>Upwork Job ID: 1825773836120920532</li>
        <li>Last Price Increase: 2024-08-20</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 103598175</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2024-04-29 06:17
@cristipaval any updates here?

**Comment by cristipaval** [comment] 2024-04-29 06:50
Still held. This is part of Invoicing V0.2. We'll get to this when Invoicing V0.1 is done.

**Comment by kadiealexander** [comment] 2024-05-08 05:15
Still on hold! Shifting to monthly while we wait for V2.

**Comment by kadiealexander** [comment] 2024-05-15 00:10
[No longer on hold!](https://expensify.slack.com/archives/CSL3XBCCR/p1715731738186479)

**Comment by kadiealexander** [comment] 2024-05-15 03:24
Actually, still on hold!

**Comment by VickyStash** [comment] 2024-05-20 10:24
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment] 2024-05-22 12:40
@shawnborton If I paid the invoice as a business:
1) Should the report preview say that I paid the invoice or should it say that my workspace paid the invoice (ex: _viktoryia.kliushun+2 @callstack.com paid_ or _Vik's Workspace paid_):
![IMG1](https://github.com/Expensify/App/assets/23176449/18f1b372-e2c5-4be1-8ee1-2ca2764f2416).

![IMG22](https://github.com/Expensify/App/assets/23176449/bbc0852f-afe0-4218-ae17-a39597521695)

2) Should the invoice report preview avatars be updated to be workspace-to-workspace same way as the room avatars are updated? Same question for all previously/future created invoices in the room?

**Comment by VickyStash** [comment] 2024-05-22 15:55
### Updates:
- Updated `SettlementButton` component and `IOU.payInvoice` method to support paying as a business
- Updated `getPayMoneyRequestParams` function to change invoice room from B2C to B2B 
- Fixed `getPrimaryPolicy` method

Waiting for some design clarifications to make sure UI looks as expected.

**Comment by shawnborton** [comment] 2024-05-23 09:47
> Should the report preview say that I paid the invoice or should it say that my workspace paid the invoice (ex: viktoryia.kliushun+2 @callstack.com paid or Vik's Workspace paid):

Good question, I think it would say Workspace paid. We already do this for submitting expenses, when your workspace pays you back and not the individual who approved/paid within the workspace:
![CleanShot 2024-05-23 at 11 45 41@2x](https://github.com/Expensify/App/assets/2319350/51657fa8-572c-4938-8f60-9f2c91c0674b)

> Should the invoice report preview avatars be updated to be workspace-to-workspace same way as the room avatars are updated? Same question for all previously/future created invoices in the room?

So are you saying that if the invoice receiver choses to pay via a business bank account, and we update that invoice to be workspace-to-workspace, right? In that case, yes, we should update all of the avatars to reflect the nature of it being workspace-to-workspace.

**Comment by VickyStash** [comment] 2024-05-23 10:26
@shawnborton @cristipaval 
1) Could you please also clarify this use case: I have a workspace-to-individual invoice room with three open invoices. And I pay invoice number 2 using business bank account. The room turns into workspace-to-workspace room. So invoices 1 and 3 will have workspace-to-workspace avatars and will say `"Workspace A owes:"` instead of `"viktoryia.kliushun@callstack.com owes:"`, right?
![image](https://github.com/Expensify/App/assets/23176449/ff06977a-6c19-4e5f-bc7b-c2fede1d147b)

---
2) In case of Workspace expenses, when a workspace pays the expense, inside the expense view we have a message that the individual paid expense using something:
![image](https://github.com/Expensify/App/assets/23176449/b185e0cd-c0ba-45c6-8d07-73fcf2528877)
How this message should look like for the invoice paid by BBA?

**Comment by VickyStash** [comment] 2024-05-24 10:37
Some examples of how the B2B invoice room looks (offline mode, since API updates are still in work).
<img width="1348" alt="INV_EX3" src="https://github.com/Expensify/App/assets/23176449/1ffaca53-bc8c-49ab-806e-81ad476f04e1">
<img width="1344" alt="INV_EX4" src="https://github.com/Expensify/App/assets/23176449/4a116415-29fa-46e8-b233-ea2cca80481e">
<img width="1344" alt="INV_EX5" src="https://github.com/Expensify/App/assets/23176449/01e270e2-9b69-43b7-96d8-88eea217bdee">

**Comment by shawnborton** [comment] 2024-05-24 14:21
> 1. The room turns into workspace-to-workspace room. So invoices 1 and 3 will have workspace-to-workspace avatars and will say "Workspace A owes:" instead of "viktoryia.kliushun@callstack.com owes:", right?

That's my understanding, yes!

> How this message should look like for the invoice paid by BBA?

I think we'd follow the same pattern as workspace expenses - it would show the individual that actually took the action. But cc @davidcardoza and @danielrvidal to confirm

**Comment by davidcardoza** [comment] 2024-05-25 00:17
Yes, we should show in the message both the user who made the payment and the user who owes the payment. This is important for approval and audit purposes to confirm who processed the payment.

**Comment by VickyStash** [comment] 2024-05-29 18:53
Updates: Waiting for https://github.com/Expensify/App/issues/40437 to be merged to continue working on this one.

**Comment by VickyStash** [comment] 2024-06-04 15:15
[Draft PR](https://github.com/Expensify/App/pull/43036) is ready. 
HOLD for API updates for the `OpenReport` and `OpenApp` commands to provide invoice receiver policy info for the invoice sender.

**Comment by cristipaval** [comment] 2024-06-06 11:50
I asked [here](https://expensify.slack.com/archives/C0714QF3A1Z/p1717673640019669) for permission to merge the PR that adds the name and avatar of the invoice receiver policy in the response of the `OpenApp` and `OpenReport` commands.

@VickyStash, I'll let you know if the team agrees to deploy it.

**Comment by VickyStash** [comment] 2024-06-07 15:34
**Updates:**
- Tested the app over API updates for the `OpenReport` and `OpenApp` commands to provide invoice receiver policy.
- Fixed UI issues for B2B invoice room display for invoice sender.
- Resolved conflicts
- Added recordings/screenshots to the Draft PR

When the API issue with `previousReportActionID: "0"` will be resolved I'll open the PR for review

**Comment by VickyStash** [comment] 2024-06-13 12:32
**Updates:** [The PR](https://github.com/Expensify/App/pull/43036) has been opened for the review

**Comment by VickyStash** [comment] 2024-06-17 17:35
**Updates:** working on the C+ reviewer [feedback](https://github.com/Expensify/App/pull/43036#issuecomment-2168178183) applying

**Comment by davidcardoza** [comment] 2024-06-24 23:32
@VickyStash any new update on this issue?

**Comment by VickyStash** [comment] 2024-06-25 06:35
@davidcardoza The related [PR](https://github.com/Expensify/App/pull/43036) is [ON HOLD](https://github.com/Expensify/App/pull/43036#issuecomment-2178980231) till API updates to support at most one b2b and one b2c invoice room between the sender and the receiver are implemented.

**Comment by jjcoffee** [comment] 2024-06-28 10:53
Just a heads up that I'll be going OOO until Jul 24 or so, but the PR is pretty close to being approved and I'll be able to check in to retest until we're done.

**Comment by VickyStash** [comment] 2024-06-28 14:37
Same, I'm going to be OOO Jul 1- Jul 7 🌴

**Comment by jjcoffee** [comment] 2024-07-01 09:56
@davidcardoza PR approved from my end as it's just waiting for BE changes left, so we should be all good!

**Comment by VickyStash** [comment] 2024-07-09 14:48
**Updates:** Investigating blockers that caused the PR revert and applying fixes in Draft PR

**Comment by cristipaval** [comment] 2024-07-10 11:47
the PR for this issue was reverted

**Comment by VickyStash** [comment] 2024-07-11 10:38
I've put [Draft PR](https://github.com/Expensify/App/pull/44970) on hold for now, till two affecting issues are resolved, see the [comment](https://github.com/Expensify/App/pull/44970#issuecomment-2222592611).

**Comment by VickyStash** [comment] 2024-07-22 10:24
One more blocker issue was found during the testing of the [Draft PR](https://github.com/Expensify/App/pull/44970). See the [discussion](https://github.com/Expensify/App/pull/44970#issuecomment-2236406756) for more details. It looks like it can be the Onyx issue.

**Comment by kadiealexander** [comment] 2024-07-26 05:32
@cristipaval is that comment above relevant here? Does it impact the payout?

**Comment by davidcardoza** [comment] 2024-07-30 16:52
@VickyStash Is there any update on this issue?

**Comment by VickyStash** [comment] 2024-07-30 17:02
@davidcardoza I'm working on the FE fix for the room update to B2B after the receiver paid as a business for the first time.
As soon as it is resolved, I think I'll reopen the PR.

**Comment by VickyStash** [comment] 2024-07-31 16:33
**Updates:** I've almost finished fixing the mentioned issue with the B2B room update. If nothing new pops up,  I should be able to open the PR for review tomorrow.

**Comment by VickyStash** [comment] 2024-08-01 13:59
The FE issue is resolved!

There are two separate issues that were mentioned previous time:
- API related issue: https://github.com/Expensify/App/issues/44818 - it marked as closed, could you confirm @cristipaval 
- UI issue which depends on the API fix: https://github.com/Expensify/App/issues/44992 - this one is not related to this PR

@cristipaval Should we block the PR for the current issue due to these two?

**Comment by cristipaval** [comment] 2024-08-02 12:17
It seems that these are not related to the current PR, so I wouldn't block the PR on them.

**Comment by jjcoffee** [comment] 2024-08-19 10:01
**Regression Test Proposal**

1. Login to the app as User A. The user should be the admin of any workspace.
2. Go to FAB -> Select "Send invoice"
3. Send an invoice of any amount to User B (who should be the admin of his primary workspace)
4. Login as User B and open the invoice room from step 3.
5. Tap the Pay button and select Pay as business -> Pay elsewhere
6. Verify that:
- the invoice got paid
- the room is turned into a B2B invoices room, the title and avatars reflect the workspace names and any custom avatars.
7. Login as User A and open the same invoice room. Verify against step 6.

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2024-08-19 10:05
@kadiealexander I'd like to request a payment boost here to $500, if possible. There was a large amount of work and time involved in testing and retesting this, and there were essentially two PRs to test as the first got reverted (due I think mostly to [this issue](https://github.com/Expensify/App/issues/44818) that I don't think could reasonably be caught by the reviewer's checklist!). Thanks for the consideration! :pray:

**Comment by kadiealexander** [comment] 2024-08-20 06:02
@jjcoffee let me know when you've accepted the offer :)

**Comment by jjcoffee** [comment] 2024-08-20 06:50
@kadiealexander Thanks Kadie, I've accepted the offer! :pray:

**Comment by kadiealexander** [comment] 2024-08-20 09:34
Paid!

**Closed by kadiealexander** 2024-08-20 09:34 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
