### ISSUE TITLE
[$1000] Personal Details - Date of birth does not display save value when we open year selection by deep link and go back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22117] opened 2023-07-03 15:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open profile
4. Open personal details
5. Open date of birth
6. If no value is saved then select and save any date and again open date of birth
7. Open year search and copy the URL
8. Logout and paste the URL
9. Login again with same user, it will open year search page
10. Click on back and observe that 'YYYY-MM-DD' is displayed in place of current saved date

## Expected Result:
App should display saved date value (if present) if we navigate back from year search

## Actual Result:
App displays placeholder 'YYYY-MM-DD' when we logout, open year search by deep link, login and go back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bf2544c3-ae2b-429d-a4ff-be831e651c08

https://github.com/Expensify/App/assets/93399543/fe7fb514-de23-40cf-9862-f4979276b47d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688277163827609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186dac9ad4c1d2858</li>
        <li>Upwork Job ID: 1679106574603264000</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-07-04 05:46
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
- Pressing back on Year Selector Screen for DOB which was navigated using link, the date is not set in Date Picker.

### What is the root cause of that problem?
- Default value is not setting on mount of DatePicker. So a initial default value is needed.

### What changes do you think we should make in order to solve the problem?
- The default value needs to be provided to Date Picker based on the selected year. We can use moment's code from `NewDatePicker`.
- Also had to update `dobYear` variable's code as it was returning `NaN` in string.

```diff
- const dobYear = String(moment(privatePersonalDetails.dob).year());

+ const numDob = moment(privatePersonalDetails.dob).year();
+ const dobYear = _.isNaN(numDob) ? '' : String(numDob);
+ const date = selectedYear.length ? moment().set('year', selectedYear).format(CONST.DATE.MOMENT_FORMAT_STRING) : null;

<NewDatePicker 
-    defaultValue={privatePersonalDetails.dob || ''}
+    defaultValue={date || privatePersonalDetails.dob || ''}
/>
```


### What alternative solutions did you explore? (Optional)
- N/A

**Comment by JmillsExpensify** [comment] 2023-07-12 12:32
I'm able to reproduce this bug, and I'll triage for now, though @mountiny I'm curious if this is by design at the moment?

**Comment by saadbinsaeed** [comment] 2023-07-13 09:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- When we directly hit the deep link of date of birth sidebar, it does not show the value that has already saved.

### What is the root cause of that problem?

- The data is not loaded when we directly hit the link.
- Calendar component does not pick up the changed default value.

### What changes do you think we should make in order to solve the problem?

- The problem is that when we are hitting directly the URL of date of birth sidebar  ( which is using DateOfBirthPage component), in that case, personal details are not loaded. So we need to load details in the DateOfBirth component which can be done using a React hook - UseEffect hook.

Problem with this approach? 
Every time when we will open the date of birth sidebar, this code will make an API call. So this is not an optimized solution, however, this code can be optimised using and identifier to check if the details are already loaded or not? If yes, we will not make that API call to load the personal details. 

- 2nd problem: The calendar component was not showing the updated value if it is changed and sent from the parent components, so we need to do some tweaks inside the Calendar component by using the React lifecycle hook componentDidUpdate and dictate the component to get the updated value.

Here's the video of the proposed solution


https://github.com/Expensify/App/assets/21288440/2194a22e-9ddb-4990-983a-eb12acce4e34



### What alternative solutions did you explore? (Optional)
N/A

**Comment by mountiny** [comment] 2023-07-13 17:56
Yep this is s a dupe, closing

**Closed by mountiny** 2023-07-13 17:56 UTC
Labels: External, Daily, Help Wanted, Bug
