### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] Add boundary to transparent background images on Share QR code screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19569] opened 2023-05-25 00:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to staging dot on web chrome
2. Click on profile
3. Change the profile picture to any image with background
4. Click the back arrow
5. Click on Share code and notice that the image is shown in circular frame between the QR code that looks great
6. But now try to change the profile picture that has transparent background (example: 
![transparent photo](https://github.com/Expensify/App/assets/51066321/e6d6ecb1-f5a9-480a-8045-8dfe97e6ff12))

7. Click on Share code and notice that since the image doesn't have any background, it looks weird in between the QR code. Thus, a circular frame should be provided in all the images irrespective of the background

## Expected Result:
A circular frame should be provided in all the images irrespective of the background in the QR code
## Actual Result:
Transparent background images looks weird in Share QR code unlike images with backgrounds

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [X] Android / Chrome
- [X] iOS / native
- [X] iOS / Safari
- [x] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number:** 1.3.18-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bf86c919-c734-429c-96d8-21a36962fdb9

https://github.com/Expensify/App/assets/43996225/064e6572-6733-4c3b-b379-ffa991fb631a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684818587259709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01916a33b50e2bee79</li>
        <li>Upwork Job ID: 1661800609949470720</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by ahmedyasin21** [comment] 2023-05-26 02:10
Contributor details
Your Expensify account email: [ahmedyasin1947@gmail.com](mailto:ahmedyasin1947@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/mahmedyasin

Myself Ahmed Yasin, a certified React Native Developer.

This problem comes when png photos gets uploaded so to handle this thing. To change image type, dimensions and replace the background with blurry background of that particular image. I can fix this. 

I'm confident and feel myself a best contributor for this job. So , hoping for your response.

**Comment by ahmedyasin21** [comment] 2023-05-26 02:11
Contributor details
Your Expensify account email: ahmedyasin1947@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/mahmedyasin

Myself Ahmed Yasin, a certified React Native Developer.

This problem comes when png photos gets uploaded so to handle this thing. To change image type, dimensions and replace the background with blurry background of that particular image. I can fix this.

I'm confident and feel myself a best contributor for this job. So , hoping for your response.

**Comment by madmax330** [comment] 2023-05-29 09:23
Waiting on proposal reviews @rushatgabhane

**Comment by shawnborton** [comment] 2023-05-31 12:23
Sorry, what exactly is the bug and what do you need me to review?

**Comment by shawnborton** [comment] 2023-05-31 12:27
I'd say we just stay consistent with what we do elsewhere, yeah.

**Comment by shawnborton** [comment] 2023-05-31 12:50
Personally I think we should treat this avatar the same as we treat avatars anywhere else in the app, so I would vote yes.

**Comment by Christinadobrzyn** [comment] 2023-06-02 20:16
Moving this to weekly while we wait for the PR process.

**Comment by Christinadobrzyn** [comment] 2023-06-13 21:36
Hired in Upwork: 
Internal job: https://www.upwork.com/ab/applicants/1661800609949470720/job-details
External Job: https://www.upwork.com/jobs/~01916a33b50e2bee79

- Reporter @Priya Jha
- C+ @rushatgabhane 
- Contributor @allroundexperts 

I think there should be a test regression for this? @rushatgabhane?

**Comment by Christinadobrzyn** [comment] 2023-06-20 19:13
@rushatgabhane do you think we need a regression test for this? I don't think so... but just checking!

**Comment by Christinadobrzyn** [comment] 2023-06-21 21:28
Thanks @rushatgabhane sorry two more questions: 

- It looks like a speed bonus doesn't apply here (PR created May 31st & merged June 7th)... can you double-check?
- It looks like you haven't accepted the Upwork job invitation, should I invite a different profile?

**Comment by Christinadobrzyn** [comment] 2023-06-23 23:33
Thanks @rushatgabhane! I just invited you to the job - https://www.upwork.com/jobs/~01916a33b50e2bee79

Thanks!

**Comment by madmax330** [comment] 2023-06-26 10:36
Waiting on payment

**Comment by Christinadobrzyn** [comment] 2023-06-26 14:53
Paid @rushatgabhane closed job in Upwork - closing this. Thanks!

**Comment by aldo-expensify** [comment] 2023-07-10 18:46
Reopening to handle payment

**Comment by Christinadobrzyn** [comment] 2023-07-10 21:23
Oh weird, sorry about that @allroundexperts - I don't know if I missed the payment or if something didn't finish in Upwork but I paid you again! Feel free to reach out if something comes up! 

![image](https://github.com/Expensify/App/assets/51066321/e0d53ba5-baa9-43d5-a0a2-ee32a86bf609)

**Closed by Christinadobrzyn** 2023-07-10 21:23 UTC
Labels: External, Daily, Design, Awaiting Payment, Bug
