### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500]  Search/Send money/Request money - Last option is not selected when pressing up arrow key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38430] opened 2024-03-15 20:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4428031
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify with Expensifail account
2. Click on search
3. Press up arrow key on keyboard

## Expected Result:
Last option in the list should be selected and the list should scroll down to the bottom as it is the case in Start chat list

## Actual Result:
List does not move at all
Reproducible in Search, Send money and Request money lists

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a964a8a3-ee4f-4137-abb3-04fd24e6c4b6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121c95e267ea04cc2</li>
        <li>Upwork Job ID: 1768768968790626304</li>
        <li>Last Price Increase: 2024-03-15</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 0</li>
<li>abzokhattab | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-15 20:49
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-15 20:49
We think that this bug might be related to #vip-vsp

**Comment by jeremy-croff** [comment] 2024-03-15 23:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We have an inconsinstent experience between the Search user list and the Send Money user list.

### What is the root cause of that problem?
We use 2 different components that have different code. This would be a new feature to implement it for the Send Money List component.
Search: https://github.com/Expensify/App/blob/2979e3c709f9e0d8cfe3b25dc132fea03d046a5a/src/components/OptionsSelector/BaseOptionsSelector.js#L616
Send: https://github.com/Expensify/App/blob/2979e3c709f9e0d8cfe3b25dc132fea03d046a5a/src/components/SelectionList/BaseSelectionList.tsx#L467

In Search, it accurately tracks the visible sections, and can maintain the index for the arrows keys. In Send it has the length of even the invisible items so the index is out of bounds for what the user can view.

### What changes do you think we should make in order to solve the problem?
We can see that the implementation from search uses [logic](https://github.com/Expensify/App/blob/2979e3c709f9e0d8cfe3b25dc132fea03d046a5a/src/components/OptionsSelector/BaseOptionsSelector.js#L616) here to determine if it's actually visible or not.
We can implement the same method for the Send BaseSelectionList.tsx and generate a visible Index in the same manner.

### What alternative solutions did you explore? (Optional)
Combing the lists into the same component, but this seems very high risk.

**Comment by jeremy-croff** [comment] 2024-03-15 23:14
The experience after filtering out the flattenedSections with [this same logic]([logic](https://github.com/Expensify/App/blob/2979e3c709f9e0d8cfe3b25dc132fea03d046a5a/src/components/OptionsSelector/BaseOptionsSelector.js#L616))
https://github.com/Expensify/App/assets/157416545/ff5f79fc-6245-441b-ab6a-a8017932c721

**Comment by bfitzexpensify** [comment] 2024-03-18 17:26
Proposals ready for review @mollfpr - thank you!

**Comment by mollfpr** [comment] 2024-03-19 16:47
I guess 700+ reports don't reproduce the issue.

@abzokhattab How do you get the account with 4k report?

**Comment by mollfpr** [comment] 2024-03-20 17:14
Thanks @abzokhattab it's working great now!

The [proposal](https://github.com/Expensify/App/issues/38430#issuecomment-2000596375) from @abzokhattab looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by bfitzexpensify** [comment] 2024-04-09 15:04
Payment summary:

$500 to @abzokhattab for contributor work - paid via Upwork ✅ 
$500 to @mollfpr for C+ work - @mollfpr, can you please accept the Upwork job offer, and also complete the BZ checklist? Thanks!

**Comment by mollfpr** [comment] 2024-04-10 17:23
Sorry for the delay @bfitzexpensify! I'll do a manual request in NewDot, thank you!

>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I couldn't find the offending PR. 

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Open App
2. Go to the search page
3. Press up arrow key on the keyboard
4. Ensure that the last item in the list is selected
5. 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-04-10 18:06
$500 approved for @mollfpr

**Comment by bfitzexpensify** [comment] 2024-04-11 12:51
Thanks @mollfpr - agree with those regression steps, proposed they be added via https://github.com/Expensify/Expensify/issues/387069. Closing this out - thanks everyone!

**Closed by bfitzexpensify** 2024-04-11 12:51 UTC
Labels: External, Daily, Awaiting Payment, Bug
