### ISSUE TITLE
Desktop - When creating a task, the "Description" field is shown as a large field, then shrinks to a single line

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21507] opened 2023-06-24 19:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in to New Expensify
2. Click the FAB, then Assign Task
3. Observe the size of the Description field, and then click in to the field

## Expected Result:
The Description field should remain a consistent size when you first see it, and when you click into it

## Actual Result:
The Description field resizes as soon as you click into it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.28-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (90)](https://github.com/Expensify/App/assets/93399543/afb9c038-4765-46e8-8b94-4cbe5cc0e74f)
![image (89)](https://github.com/Expensify/App/assets/93399543/4c01da0b-10ab-4d55-a4fa-dff379675989)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Conor Pendergrast
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687182874231119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dan1d** [comment] 2023-06-25 04:24
I cannot reproduce anymore!

**Comment by twisterdotcom** [comment] 2023-06-26 19:15
Closing as a duplicate of https://github.com/Expensify/App/issues/21280

**Closed by twisterdotcom** 2023-06-26 19:15 UTC
Labels: Daily, Needs Reproduction, Bug
