### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] Android-Attachments-App crashes on uploading specific PDF

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29743] opened 2023-10-17 09:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on a report
3. Tap plus icon near compose
4. Tap Add attachments
5. Tap Choose document
6. Select the below attached PDF

## Expected Result:
User must be able to upload all pdf and app must not crash while trying to upload any pdf.

## Actual Result:
When user tries to upload specific pdf app crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/d1be5106-5736-4c39-a9fc-c02c36ef04e3

[utest-dl.s3.amazonaws.com_12102_26469_432782_6239948_bugAttachment_Bug6239948_1697510571673%21pdf_rash.txt_X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231017T095403Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Credential=AK.txt](https://github.com/Expensify/App/files/12927231/utest-dl.s3.amazonaws.com_12102_26469_432782_6239948_bugAttachment_Bug6239948_1697510571673.21pdf_rash.txt_X-Amz-Algorithm.AWS4-HMAC-SHA256.X-Amz-Date.20231017T095403Z.X-Amz-SignedHeaders.host.X-Amz-Expires.86400.X-Amz-Credential.AK.txt)

[class-9-maths-chapter-10-solutions.pdf](https://github.com/Expensify/App/files/12927237/class-9-maths-chapter-10-solutions.pdf)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f2fe87b1c515e0af</li>
        <li>Upwork Job ID: 1714218588456812544</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by pradeepmdk** [comment] 2023-10-17 12:26
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Android-Attachments-App crashes on uploading specific PDF
### What is the root cause of that problem?

this bug from [react](https://www.npmjs.com/package/react-native-pdf) 
here when we parse json its throws the error because above pdf has maths logic so that contains json string like this 
![Screenshot 2023-10-17 at 5 54 07 PM](https://github.com/Expensify/App/assets/16595846/e4231d75-c752-49ad-8d3b-8010f2f69596)

https://github.com/wonday/react-native-pdf/blob/b700b0a2f27b29728dcc9665289e6e628a669f56/index.js#L374


### What changes do you think we should make in order to solve the problem?

we need fix this on upstream adding try catch.

or we can add patch fix for this.

**Comment by abekkala** [comment] 2023-10-19 14:54
@fedirjh Can you review the proposal that has been submitted for this? thanks!

**Comment by pradeepmdk** [comment] 2023-10-26 17:06
@fedirjh sorry for the delay. proposal updated https://github.com/Expensify/App/issues/29743#issuecomment-1766313301

**Comment by pradeepmdk** [comment] 2023-10-26 22:51
@fedirjh Yes this platform-specific code 
https://github.com/wonday/react-native-pdf/blob/b700b0a2f27b29728dcc9665289e6e628a669f56/index.js#L408

**Comment by abekkala** [comment] 2023-10-31 16:05
@pradeepmdk can you address the question by @fedirjh 

If we're not able to accept an suitable proposal I will need to pull in another contributor to get this one moving along and finished

**Comment by pradeepmdk** [comment] 2023-10-31 16:06
i will update now

**Comment by pradeepmdk** [comment] 2023-10-31 16:53
@fedirjh 
1) this is android specific code 
https://github.com/wonday/react-native-pdf/blob/b700b0a2f27b29728dcc9665289e6e628a669f56/index.js#L408
```javascript
  Platform.OS === "android" || Platform.OS === "windows"?(
                                        <PdfCustom
                                            ref={component => (this._root = component)}
                                            {...this.props}
                                            style={[{flex:1,backgroundColor: '#EEE'}, this.props.style]}
                                            path={this.state.path}
                                            onChange={this._onChange}
                                        />
                                    ):(
``` 
2) so when we upload onchange will be trigger 
```javascript
 _onChange = (event) => {

        let message = event.nativeEvent.message.split('|');
        //__DEV__ && console.log("onChange: " + message);
        if (message.length > 0) {
            if (message.length > 5) {
                message[4] = message.splice(4).join('|');
            }
            if (message[0] === 'loadComplete') {
                this.props.onLoadComplete && this.props.onLoadComplete(Number(message[1]), this.state.path, {
                    width: Number(message[2]),
                    height: Number(message[3]),
                },
                message[4]&&JSON.parse(message[4]));
            } else if (message[0] === 'pageChanged') {
                this.props.onPageChanged && this.props.onPageChanged(Number(message[1]), Number(message[2]));
            } else if (message[0] === 'error') {
                this._onError(new Error(message[1]));
            } else if (message[0] === 'pageSingleTap') {
                this.props.onPageSingleTap && this.props.onPageSingleTap(Number(message[1]), Number(message[2]), Number(message[3]));
            } else if (message[0] === 'scaleChanged') {
                this.props.onScaleChanged && this.props.onScaleChanged(Number(message[1]));
            } else if (message[0] === 'linkPressed') {
                this.props.onPressLink && this.props.onPressLink(message[1]);
            }
        }

    };
``` 
 1) first they are splitting the message to array using `let message = event.nativeEvent.message.split('|');`
2 )after that on message length > 5 means they are splice and join again` message[4] = message.splice(4).join('|');`
so in this case this specfic pdf data like this 
```javascript
 message[4]  = '[{"children":[],"mNativePtr":-5476376628811613152,"pageIdx":0,"title":"Answer 1:"},{"children":[],"mNativePtr":-5476376628811612288,"pageIdx":0,"title":"Answer 2:"},{"children":[],"mNativePtr":-5476376628811611760,"pageIdx":1,"title":"Answer 3:"},{"children":[],"mNativePtr":-5476376628811610992,"pageIdx":1,"title":"D                        c"},{"children":[],"mNativePtr":-5476376628811609264,"pageIdx":1,"title":"A                                         B"},{"children":[],"mNativePtr":-5476376628811608592,"pageIdx":1,"title":"Answer 4:"},{"children":[],"mNativePtr":-5476376628811464464,"pageIdx":1,"title":"E"},{"children":[],"mNativePtr":-5476376628811462784,"pageIdx":1,"title":"D                            C"},{"children":[],"mNativePtr":-5476376628811461296,"pageIdx":1,"title":"A                            B"},{"children":[],"mNativePtr":-5476376628811459520,"pageIdx":2,"title":"Given:  ABCD is a square in which AB \u003d BC \u003d CD \u003d DA. ΔEDC is an equilateral triangle in which ED \u003d EC \u003d DC and  ∠EDC  \u003d   ∠ DEC \u003d ∠DCE \u003d  60o. To prove:  AE \u003d BE and ∠DAE \u003d 15o Proof: In ΔADE and ΔBCE, as , AD \u003d BC              [Sides of a square]"},{"children":[],"mNativePtr":-5476376628811456928,"pageIdx":2,"title":"Answer 5:"},{"children":[],"mNativePtr":-5476376628811455776,"pageIdx":2,"title":"D                                          C"},{"children":[],"mNativePtr":-5476376628811454912,"pageIdx":2,"title":"A                                           B"},{"children":[],"mNativePtr":-5476376628811452608,"pageIdx":3,"title":"Answer 6:"},{"children":[],"mNativePtr":-5476376628811442448,"pageIdx":4,"title":"Answer 7:"},{"children":[],"mNativePtr":-5476376628811441584,"pageIdx":5,"title":"Answer 8:"},{"children":[],"mNativePtr":-5476376628811441152,"pageIdx":5,"title":"Let ABCD be a quadrilateral with diagonals AC and BD and O is a point within the quadrilateral."},{"children":[],"mNativePtr":-5476376628811439952,"pageIdx":5,"title":"Suppose In ΔAOC, OA + OC \u003e 𝐴𝐶…………..(1)"},{"children":[],"mNativePtr":-5476376628811438464,"pageIdx":6,"title":"Answer 9:"},{"children":[],"mNativePtr":-5476376628811437984,"pageIdx":7,"title":"Answer 10:"},{"children":[],"mNativePtr":-5476376628811437408,"pageIdx":7,"title":"S"},{"children":[],"mNativePtr":-5476376628811435296,"pageIdx":7,"title":"R"},{"children":[],"mNativePtr":-5476376628811434432,"pageIdx":7,"title":"P                                                      Q   Let PQRS be a quadrilateral and ∠1, ∠2, ∠3 and ∠4  are its four angles . Join QR which divides PQRS in two triangles, ΔPQR and ΔQRS. In ΔPQR,  ∠1 + ∠2 + ∠P \u003d 180       ......"},{"children":[],"mNativePtr":-5476376628811433856,"pageIdx":8,"title":"EXERCISE 10B"},{"children":[],"mNativePtr":-5476376628811432944,"pageIdx":8,"title":"Answer 1: (1)"},{"children":[],"mNativePtr":-5476376628811432272,"pageIdx":8,"title":"Answer 2: (1)"},{"children":[],"mNativePtr":-5476376628811427216,"pageIdx":9,"title":"Answer 3: (1)"},{"children":[],"mNativePtr":-5476376628811426736,"pageIdx":9,"title":"Given: parallelogram ABCD, M is the midpoint of side BC and ∠BAM \u003d ∠DAM. To prove: AD \u003d 2CD Proof: Since, AD∥BC and AM is the transversal. So, ∠𝐷𝐴𝑀\u003d∠𝐴𝑀𝐵      (Alternate interior angles) But, ∠𝐷𝐴𝑀\u003d∠𝐵𝐴𝑀 (Given) Thus, ∠𝐴𝑀𝐵\u003d∠𝐵𝐴𝑀 ⇒𝐴𝐵\u003d𝐵..."},{"children":[],"mNativePtr":-5476376628811426016,"pageIdx":9,"title":"As we know angles opposite to equals sides are equal and opposite sides of parallelogram are equal            Now, 𝐴𝐵 \u003d 𝐶𝐷        ⇒2𝐴𝐵\u003d2𝐶𝐷"},{"children":[],"mNativePtr":-5476376628811425344,"pageIdx":10,"title":"So, ⇒(𝐴𝐵+𝐴𝐵)\u003d2𝐶𝐷 ⇒𝐵𝑀+𝑀𝐶\u003d2𝐶𝐷      (AB \u003d BM and MC \u003d BM) ⇒𝐵𝐶\u003d2𝐶𝐷"},{"children":[],"mNativePtr":-5476376628811423904,"pageIdx":10,"title":"∴𝐴𝐷\u003d2𝐶𝐷       (AD\u003dBC)hence proved"},{"children":[],"mNativePtr":-5476376628811422032,"pageIdx":10,"title":"Answer 4: (1)"},{"children":[],"mNativePtr":-5476376628811421504,"pageIdx":11,"title":"Answer 5: (1)"},{"children":[],"mNativePtr":-5476376628811420832,"pageIdx":12,"title":"Answer 6: (1)"},{"children":[],"mNativePtr":-5476376628811419728,"pageIdx":12,"title":"Answer 7: (1)"},{"children":[],"mNativePtr":-5476376628811419248,"pageIdx":13,"title":"Answer 8: (1)"},{"children":[],"mNativePtr":-5476376628811418816,"pageIdx":13,"title":"Answer 9: (1)"},{"children":[],"mNativePtr":-5476376628811418336,"pageIdx":14,"title":"Answer 10: (1)"},{"children":[],"mNativePtr":-5476376628811417904,"pageIdx":15,"title":"Answer 11:"},{"children":[],"mNativePtr":-5476376628811417424,"pageIdx":15,"title":"Let PQRS be a rhombus. ∴ PQ \u003d QR \u003d RS \u003d SP Here, PR and QS are the diagonals of PQRS, where PR \u003d 24 cm and QS \u003d 18 cm. Let the diagonals intersect each other at M.  ∴ ΔPMQ is a right angle triangle in which MP \u003d ,𝐴𝐶-2.\u003d ,24-2.\u003d 12 cm and MQ \u003d ,𝑄𝑆-..."},{"children":[],"mNativePtr":-5476376628811416608,"pageIdx":16,"title":"Answer 12:"},{"children":[],"mNativePtr":-5476376628811366112,"pageIdx":16,"title":"S (1)"},{"children":[],"mNativePtr":-5476376628811365584,"pageIdx":16,"title":"P                                               R"},{"children":[],"mNativePtr":-5476376628811365152,"pageIdx":16,"title":"Q"},{"children":[],"mNativePtr":-5476376628811364720,"pageIdx":16,"title":"Let PQRS be a rhombus. ∴ PQ \u003d QR \u003d RS \u003d SP \u003d 10 cm Let PR and QS are the diagonals of PQRS. Let PR \u003d y and QS \u003d 16 cm and M be the intersection point of the diagonals. ∴ ΔPMQ is a right angle triangle, in which"},{"children":[],"mNativePtr":-5476376628811364240,"pageIdx":16,"title":"MP \u003d ,𝑃𝑅-2.\u003d ,𝑦-2. and MQ \u003d ,𝑄𝑆-2.\u003d ,16-2.\u003d 8 cm. Now, PQ2\u003d MP2 + MQ2              [Pythagoras theorem] ⇒102 \u003d (,𝑦-2.) 2 + 82⇒100 − 64 \u003d ,𝑦2-4. ⇒36 ×4 \u003d y2 ⇒y2 \u003d144 ∴ y \u003d 12 cm Hence, the other diagonal of the rhombus is 12 cm. ∴ Area of the rh..."},{"children":[],"mNativePtr":-5476376628811363520,"pageIdx":16,"title":"Answer 13:"},{"children":[],"mNativePtr":-5476376628811362896,"pageIdx":17,"title":"(i) ABCD is a rectangle. The diagonals of a rectangle are congruent and bisect each other. Therefore, in Δ AOB, as ,    OA \u003d OB     ∴ ∠OAB \u003d ∠OBA \u003d 35o ∴ x \u003d 90o − 35o \u003d 55o In ∆AOB"},{"children":[],"mNativePtr":-5476376628811362464,"pageIdx":17,"title":"∠OAB + ∠OBA +∠AOB \u003d 180∘"},{"children":[],"mNativePtr":-5476376628811361888,"pageIdx":17,"title":"And ∠AOB \u003d 180o − (35o + 35o) \u003d 110o ∴ y \u003d ∠AOB \u003d 110o                     [Vertically opposite angles] Hence, x \u003d 55o and y \u003d 110o  (ii) In ΔAOB, as ,"},{"children":[],"mNativePtr":-5476376628811361456,"pageIdx":17,"title":"Given, ∠AOB \u003d 100         OA \u003d OB    As, ∠OAB \u003d ∠OBA"},{"children":[],"mNativePtr":-5476376628811361024,"pageIdx":17,"title":"Then, ∠AOB + ∠OBA + ∠OAB \u003d 180"},{"children":[],"mNativePtr":-5476376628811360448,"pageIdx":17,"title":"⇒2∠𝐴𝑂𝐵\u003d180−∠𝐴𝑂𝐵…………………..(∠OAB \u003d ∠OBA)"},{"children":[],"mNativePtr":-5476376628811359920,"pageIdx":17,"title":"⇒2∠𝐴𝑂𝐵\u003d180−110\u003d70"},{"children":[],"mNativePtr":-5476376628811359440,"pageIdx":17,"title":"⇒∠𝐴𝑂𝐵\u003d ,1-2.×70\u003d35  so, ∴ y \u003d ∠BAC \u003d 35o                 [Interior alternate angles]"},{"children":[],"mNativePtr":-5476376628811358960,"pageIdx":17,"title":"Here at ∠C  is at right angle ∆ by fig,"},{"children":[],"mNativePtr":-5476376628811358288,"pageIdx":17,"title":"⇒ 90o \u003d  x + y  ⇒x \u003d 90o − y                           ⇒ x \u003d 90o − 35o \u003d 55o                      Thus, x \u003d 55o and y \u003d 35o"},{"children":[],"mNativePtr":-5476376628811357088,"pageIdx":19,"title":"Answer 15:"},{"children":[],"mNativePtr":-5476376628811356128,"pageIdx":19,"title":"Answer 16:"},{"children":[],"mNativePtr":-5476376628811355696,"pageIdx":19,"title":"Given: A rhombus ABCD.  To prove: Diagonal AC bisects ∠A as well as ∠C and diagonal BD bisects ∠B as well as ∠D.  Proof: In ΔABC, 𝐴𝐵 \u003d 𝐵𝐶         (Sides of rhombus are equal.) ∠𝐴𝐶𝐵 \u003d ∠𝐶𝐴𝐵          (Angles opposite to equal sides are equal.)..."},{"children":[],"mNativePtr":-5476376628811355216,"pageIdx":21,"title":"Answer 17:"},{"children":[],"mNativePtr":-5476376628811354784,"pageIdx":21,"title":"Given: In a parallelogram ABCD, AM \u003d CN.  To prove: AC and MN bisect each other. Construction: Join AN and MC. Proof: As, ABCD is a parallelogram. ⇒𝐴𝐵∥𝐷𝐶⇒𝐴𝑀∥𝑁𝐶 And, 𝐴𝑀 \u003d 𝐶𝑁           (Given) Therefore, AMCN is a parallelogram. As, the dia..."},{"children":[],"mNativePtr":-5476376628811354352,"pageIdx":21,"title":"Answer 18:"},{"children":[],"mNativePtr":-5476376628811185744,"pageIdx":22,"title":"Answer 19:"},{"children":[],"mNativePtr":-5476376628811185264,"pageIdx":22,"title":"Given, ABCD is a parallelogram whose diagonals intersect each other at O. A line segment EOF is drawn to meet AB at E and DC at F."},{"children":[],"mNativePtr":-5476376628811184640,"pageIdx":23,"title":"Answer 20:"},{"children":[],"mNativePtr":-5476376628811184160,"pageIdx":23,"title":"Z                                               Y"},{"children":[],"mNativePtr":-5476376628811183584,"pageIdx":23,"title":"N"},{"children":[],"mNativePtr":-5476376628811182960,"pageIdx":23,"title":"W                                              X"},{"children":[],"mNativePtr":-5476376628811182336,"pageIdx":23,"title":"M"},{"children":[],"mNativePtr":-5476376628811181904,"pageIdx":23,"title":"Given: In parallelogram WXYZ, ZM⊥ WX, WN ⊥ XY and ∠MZN \u003d 60  In quadrilateral ZMXN, by angle sum property,  ∠𝑀𝑍𝑁+∠𝑍𝑀𝑋+∠𝑋+∠𝑋𝑁𝑍\u003d360"},{"children":[],"mNativePtr":-5476376628811181424,"pageIdx":23,"title":"⇒60 +90 +∠𝑋+90 \u003d360"},{"children":[],"mNativePtr":-5476376628811180992,"pageIdx":23,"title":"⇒∠𝑋\u003d360 −240 ⇒∠𝑋\u003d120 ⇒∠𝑋 \u003d 120  Also, ∠𝑋\u003d∠𝑍\u003d120            (Opposite angles of a parallelogram are equal.) ∠𝑊+∠𝑋\u003d180            (Adjacent angles of a parallelogram are supplementary.) ⇒∠𝑊+120 \u003d180 ⇒∠𝑊\u003d180 −120 ⇒∠𝑊\u003d60  Also,  ∠𝑊\u003d∠𝑌\u003d60      ..."},{"children":[],"mNativePtr":-5476376628811180464,"pageIdx":23,"title":"Answer 21:"},{"children":[],"mNativePtr":-5476376628811180032,"pageIdx":24,"title":"Given: In rectangle ABCD, AC bisects ∠A, i.e. ∠DAC \u003d ∠CAB and AC bisects ∠C, i.e.      ∠DCA \u003d ∠ACB.  To prove: (i) ABCD is a square, (ii) diagonal BD bisects ∠B as well as ∠D. Proof: (i)  Since, AD∥BC                                   (Opposite sides..."},{"children":[],"mNativePtr":-5476376628811179456,"pageIdx":24,"title":"Answer 22:"},{"children":[],"mNativePtr":-5476376628811178976,"pageIdx":24,"title":"Given, ABCD is  parallelogram in which AB is produced to E."},{"children":[],"mNativePtr":-5476376628811178304,"pageIdx":24,"title":"BE \u003d AB (given)"},{"children":[],"mNativePtr":-5476376628811177680,"pageIdx":25,"title":"Answer 23:"},{"children":[],"mNativePtr":-5476376628811175904,"pageIdx":26,"title":"Answer 24:"},{"children":[],"mNativePtr":-5476376628811174992,"pageIdx":26,"title":"l       X                  P"},{"children":[],"mNativePtr":-5476376628811174464,"pageIdx":26,"title":"Q (1)"},{"children":[],"mNativePtr":-5476376628814540800,"pageIdx":26,"title":"m                              S"},{"children":[],"mNativePtr":-5476376628814540368,"pageIdx":26,"title":"R                    Y"},{"children":[],"mNativePtr":-5476376628814539600,"pageIdx":26,"title":"Given: l ,, m and the bisectors of interior angles intersect at X and Y. To prove: PQRS is a rectangle. Proof: Since, l ,, m                       (Given) So, ∠𝑋𝑃𝑅\u003d∠𝑃𝑅𝑌            (Alternate interior angles) ⇒,1-2.∠XPR\u003d,1-2.∠PRY  ⇒∠𝑄𝑃𝑅\u003d∠𝑃𝑅'
``` 
so this data will set on `message[4]`

now finally 
```javascript
this.props.onLoadComplete && this.props.onLoadComplete(Number(message[1]), this.state.path, {
                    width: Number(message[2]),
                    height: Number(message[3]),
                },
                message[4]&&JSON.parse(message[4]));
``` 
enter here `message[4]` is not a proper JSON stringify so its failed here 

i hope this will clarify you if not we can schedule call also.

**Comment by pradeepmdk** [comment] 2023-11-06 13:06
sure I will create upstream but not sure how long that will take to merge

**Comment by abekkala** [comment] 2023-11-08 21:32
@pradeepmdk do you have an update?

**Comment by pradeepmdk** [comment] 2023-11-09 01:21
@abekkala I will create the upstream PR today.

**Comment by abekkala** [comment] 2023-11-13 16:25
@pradeepmdk do you have a PR for this?

**Comment by pradeepmdk** [comment] 2023-11-20 12:44
@fedirjh my system is broken I am setting up new system mostly I will pr will up tomorrow

**Comment by abekkala** [comment] 2023-11-22 15:31
@pradeepmdk do you have an update?

**Comment by pradeepmdk** [comment] 2023-11-22 15:33
@abekkala working on it on the new system facing some android build issues fixing on it.

**Comment by abekkala** [comment] 2023-11-22 15:44
@pradeepmdk do you have an estimated time for the PR?

**Comment by pradeepmdk** [comment] 2023-11-22 15:46
i will push the PR before end of this week. before 26.

**Comment by pradeepmdk** [comment] 2023-11-25 18:35
@fedirjh @abekkala upstream Pr is up now https://github.com/wonday/react-native-pdf/pull/791

**Comment by abekkala** [comment] 2023-11-30 21:21
@mountiny do you agree with @fedirjh [above](https://github.com/Expensify/App/issues/29743#issuecomment-1827921633)

**Comment by mountiny** [comment] 2023-12-01 12:22
Ueah I think having a patch is fine

@pradeepmdk I see your PR got merged, any guess how long it might take to get a new release?

**Comment by pradeepmdk** [comment] 2023-12-06 01:03
@mountiny I created a new PR for version upgrade https://github.com/wonday/react-native-pdf/pull/795 i hope this will be merged within in week. can we wait until released or patch we can move?

**Comment by mountiny** [comment] 2023-12-06 11:29
@pradeepmdk How common are these PDF files? what is the aspect which makes them crash? ie if this crashes for more PDF udpates we should patch if its minority I think we can wait

**Comment by situchan** [comment] 2023-12-06 12:47
We can wait for upstream release.
In https://github.com/Expensify/App/issues/30492, they merged the same day [PR](https://github.com/wonday/react-native-pdf/pull/781) was created and then it took only 2 weeks to publish new release.

**Comment by mountiny** [comment] 2023-12-06 13:15
Lets wait then, thanks!

**Comment by mountiny** [comment] 2023-12-11 11:20
On hold

**Comment by abekkala** [comment] 2023-12-19 20:38
### STATUS:
I'm ooo through Jan 03. 

This issue on hold for https://github.com/wonday/react-native-pdf/pull/795.

- Issue reported by: Applause-Internal Team
- Fix: @pradeepmdk (create a patch fix)
- PR Review: @fedirjh 
-

**Comment by alexpensify** [comment] 2023-12-19 20:41
@abekkala - I'll keep an eye out this week, but I'm OOO starting Friday and won't be back online until January 4.

**Comment by alexpensify** [comment] 2023-12-23 02:54
Weekly Check-In: Moving to `Weekly` now since this one is still on hold. I'm going to be unassigning myself too since I will be offline until January 4.

**Comment by pradeepmdk** [comment] 2023-12-23 07:46
My PR IS MERGED

**Comment by pradeepmdk** [comment] 2023-12-23 08:13
Sure

**Comment by alexpensify** [comment] 2023-12-23 18:20
Awesome, I've removed the hold here and we can continue forward. Thanks for the updates here.

**Comment by mountiny** [comment] 2023-12-26 11:48
@pradeepmdk Let me and @fedirjh know when the PR is ready for testing and review so we can merge this 🚀

**Comment by pradeepmdk** [comment] 2023-12-26 12:03
I am working on it my android build is failing so maximum tomorrow PR will be ready.

**Comment by pradeepmdk** [comment] 2023-12-27 06:41
Pr is ready

**Comment by alexpensify** [comment] 2024-01-04 19:06
I checked in today, and it looks like the PR is moving along.

**Comment by alexpensify** [comment] 2024-01-09 01:13
@abekkala - I think you are back online and handing the BZ role back to you here. Thanks!

**Comment by pradeepmdk** [comment] 2024-01-09 08:52
@fedirjh  what will be the next step here?

**Comment by mountiny** [comment] 2024-01-09 13:58
@fedirjh I think if there is a clear way to fix this, then we can apply the patch

Ideally we can also help fix this upstream

**Comment by mountiny** [comment] 2024-01-09 14:12
Ih sorry I misunderstood, I thought a patch for the new issue. Then I think we can go ahead with the patch until the other issue is resolved.

> The upstream bug arise from a recently merged PR : https://github.com/wonday/react-native-pdf/pull/792 , I think we should just revert it as the PR doesn’t include any revelent description or details.

If you know its that PR do you want to create Revert PR upstream and tag the maintainer, maybe they will be fine with the revert. Thanks!

**Comment by pradeepmdk** [comment] 2024-01-10 10:06
thanks @mountiny i will prepare the patch PR

**Comment by abekkala** [comment] 2024-01-24 14:50
@mountiny can you help untangle this a bit for me? 
Did the original PR for this issue (20743) cause the regression noted above that required a revert and patch fix? 

I'm not sure how payments works for this one given the original PR, revert, patch, etc. that has occurred here.

**Comment by abekkala** [comment] 2024-01-25 20:38
@fedirjh 
> This is not yet ready for payment. We are still awaiting updates from @pradeepmdk.

Perfect, thanks for confirming. It didn't think it was so figured I'd better make sure I hadn't missed something!

**Comment by pradeepmdk** [comment] 2024-01-26 06:52
@fedirjh PR is ready.

**Comment by abekkala** [comment] 2024-02-08 18:36
### PAYMENTS FOR FEB 14

- Issue reported by: Applause-Internal Team
- Fix: @pradeepmdk [$500 - if no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/100827536)
- PR Review: @fedirjh [$500 - if no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/100827580)

**Comment by abekkala** [comment] 2024-02-15 17:17
@pradeepmdk payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment] 2024-02-15 17:17
@fedirjh can you complete the checklist, please? I can then send payment for this job

**Comment by abekkala** [comment] 2024-02-15 18:15
@fedirjh payment sent and contract ended - thank you! 🎉

**Closed by abekkala** 2024-02-15 18:15 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
