### ISSUE TITLE
Profile pictures are not displayed in the bump emails sent

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13856] opened 2022-12-28 16:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND and login as a new user A that's not an expensify.com email. 
2. Go to any report (user B) and leave message to user B
3. Create a workspace
4. Observe the bump email received from user A
5. Also observe the email received from your setup specialist

## Expected Result:
Emails should show the avatars of the person sending the message

## Actual Result:
Some random blue avatar is appearing

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image (1)](https://user-images.githubusercontent.com/43996225/209841144-e09d3362-ef64-42e2-a68d-d4fe9f4b8f34.png)
<img width="771" alt="Screenshot (140)" src="https://user-images.githubusercontent.com/43996225/209841162-df4e3d6e-e487-4c7c-8ace-469e44a8753b.png">
<img width="715" alt="Screenshot (139)" src="https://user-images.githubusercontent.com/43996225/209841164-1fb2a91e-1577-432e-b7ad-b7a0ec8713b3.png">
<img width="766" alt="Screenshot (138)" src="https://user-images.githubusercontent.com/43996225/209841166-951d3592-1b7e-4e9f-8c4d-ccfe72fbd393.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Douglas   (guide)
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1672185116276059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment] 2022-12-29 07:38
I am going out of the office for the next 2 days, I am going to reassign this issue out to make sure it gets picked up.

**Comment by mallenexpensify** [comment] 2022-12-30 00:58
Took me a while to reproduce, likely because I initially tried to use my main expensify.com email. You'll want to use a brand new email address so you can get a guide/setup specialist assigned and they will send you a message.  Both recieved messages won't show the correct avatars, just a blue default one.  

UUUUGHHHH, GH hasn't been allowing me to paste images into comments for weeks, need to restart comp. 

@madmax330 I'm unsure if this can be worked on externally but my guess is no.

**Comment by mallenexpensify** [comment] 2022-12-30 01:13
Still can't upload pics after restarting ¯\_(ツ)_/¯

**Comment by madmax330** [comment] 2023-01-02 13:10
Hmm I don't think this is something we can fix. I will ask the room, but I think these are profile pictures that you set in google.

**Comment by sketchydroide** [comment] 2023-01-02 13:14
Yeah I think I agree, not something we can fix, maybe at some point we could have the avatars as part of the body, I don't think this is the case.
I think this is avatar is pulled out fo your contacts, of the gmail profile as well

**Comment by madmax330** [comment] 2023-01-02 14:15
Closing this per: https://expensify.slack.com/archives/C01GTK53T8Q/p1672665080731749

I don't think it's something we can fix, and it's probably not worth the effort at this point

**Closed by madmax330** 2023-01-02 14:15 UTC
Labels: Engineering, Daily, Bug
