### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Workspace - Unable to remove error reported member

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26339] opened 2023-08-30 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap workspace
4. Tap any created workspace
5. Tap members
6. Tap invite
7. Tap any invalid number
8. Tap invite
9. Tap on close button in workspace members page
10. Select error reported member and tap remove
11. Tap confirm Remove
12. Navigate back to general settings page
13. Refresh page
14. Tap workspace
15. Tap members

## Expected Result:
The workspace members page must not display error reported member which is removed

## Actual Result:
The workspace members page displays removed error reported member again after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e33e821b-dc04-4f5e-8041-b663bb805f91

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011d44b0b1f472370a</li>
        <li>Upwork Job ID: 1699206903663333376</li>
        <li>Last Price Increase: 2023-09-05</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26546537</li>
<li>tienifr | Contributor | 26546540</li>
</ul></li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-09-01 23:03
Hmmm, I do not have the same experience when trying to repro this. 

Following the steps from the recording, I do not have the option to select an invalid phone number at all. I tried entering just "84" as the video and I have to enter a full phone number to be able to select anything. When I do, the number is valid and I don't get the error report as described.

**Comment by strepanier03** [comment] 2023-09-01 23:07
@lanitochka17 - Anything different in your setup that isn't covered in the bug report? Can you still repro?

**Comment by lanitochka17** [comment] 2023-09-03 18:40
Issue reproducible on Build 1.3.62-2
Please try again with invalid number +84566123455

![Screenshot_20230903-215141_Chrome](https://github.com/Expensify/App/assets/78819774/f36df7d0-491f-47a9-8727-92fc1f2543e3)

**Comment by strepanier03** [comment] 2023-09-05 23:44
Okay finally got it, thanks @lanitochka17. 

I was able to repro just fine using the new number you provided. Moving on.

**Comment by jjcoffee** [comment] 2023-09-07 13:48
Happy to go with @tienifr's [proposal](https://github.com/Expensify/App/issues/26339#issuecomment-1708243121). The RCA is correct and the solution makes sense. I think we can just use the existing `keyForList` property rather than adding a new `accountID` one.

@bernhardoj's proposal is almost the same, except they propose to wait for the Onyx issue to be resolved, which we don't have a timeline for so it makes sense to just fix now. We also already do the same here:
https://github.com/Expensify/App/blob/db1a306659648704baf834f65cdb804f26e13aa5/src/libs/actions/Policy.js#L734-L741

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment] 2023-09-07 15:22
@bernhardoj Ah gotcha, sorry I missed that nuance first time round! It doesn't look like we can do anything about it here though, but @tienifr I wonder what's the use of updating this to 

```
 [accountID]: {
            pendingAction: null,
            errors: null,
        },
```

If it still won't remove the user from Onyx?

**Comment by jjcoffee** [comment] 2023-09-07 15:46
> setting each field to null is good enough

Agree this is the best way forward for now. We would need to revert the code back to `[accountID]: null` once Onyx is fixed. Could you comment on a relevant issue (if there is one!) noting this? Or is there a better way to handle this? @dangrous :sweat_smile:

**Comment by jjcoffee** [comment] 2023-09-08 15:33
Hopefully reviewing [the PR](https://github.com/Expensify/App/pull/26975) on Monday!

**Comment by dangrous** [comment] 2023-09-11 15:32
So it looks like the Onyx fix is in process - https://github.com/Expensify/react-native-onyx/pull/333 - Do we want to hold in favor of that, and retest afterwards? I didn't realize it was getting fixed so speedily.

**Comment by jjcoffee** [comment] 2023-09-12 07:29
@dangrous Ah yes, just saw that - I also thought it'd take a lot longer! I think we're good to hold on it. cc @tienifr

**Comment by dangrous** [comment] 2023-09-12 16:28
I'll put that in the title for now!

**Comment by dangrous** [comment] 2023-09-18 04:09
That PR has been merged! I think we need to wait for the version update in the App though, before testing? Not quite sure how that process works.

**Comment by jjcoffee** [comment] 2023-09-18 08:31
@tienifr Do you want to bump the react-native-onyx version in your PR and retest?

**Comment by jjcoffee** [comment] 2023-09-19 14:31
@tienifr Do you mean merging the null value isn't deleting the user? Can you maybe add a comment to back [this one](https://github.com/Expensify/react-native-onyx/pull/333#issuecomment-1722726499) up?

**Comment by jjcoffee** [comment] 2023-09-21 09:14
@tienifr According to [this PR](https://github.com/Expensify/App/pull/27842) it should be v1.0.84 where the change was merged.

**Comment by jjcoffee** [comment] 2023-09-22 08:13
Ah great find, thanks! I think we can hold on https://github.com/Expensify/react-native-onyx/pull/359 then cc @dangrous

**Comment by chrispader** [comment] 2023-09-25 21:13
> Ah great find, thanks! I think we can hold on [Expensify/react-native-onyx#359](https://github.com/Expensify/react-native-onyx/pull/359) then cc @dangrous

#359 got merged :)

**Comment by dangrous** [comment] 2023-09-26 07:06
Sweet! @tienifr can you test react-native-onyx 1.0.89 in your PR and see how it goes?

**Comment by strepanier03** [comment] 2023-10-09 15:32
@tienifr - I have paid you via Upwork and closed the contract!

@jjcoffee - I will keep an eye open for the checklist items and handle the regression test as needed. Once that's done I'll pay you via Upwork as well.

**Comment by jjcoffee** [comment] 2023-10-10 15:04
- The PR that introduced the bug has been identified. Link to the PR: **N/A - this was a known issue**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A** - it came from an Onyx update so hard to catch
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **See below**

**Comment by jjcoffee** [comment] 2023-10-10 15:07
**Regression test proposal**

1. On any workspace, invite a member with an invalid number, e.g. `+84566123459@expensify.sms`
2. Select the error reported member and remove
3. Navigate back to general settings page
4. Refresh the page
5. Go back to the workspace members list and verify that the member is removed

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2023-10-10 15:09
@strepanier03 Checklist complete - sorry for the delay! Also, I _think_ this may be due the timeliness bonus as we ended up needing to hold for a react-native-onyx update. After that update [came](https://github.com/Expensify/App/issues/26339#issuecomment-1734470977), our PR was merged [within](https://github.com/Expensify/App/pull/26975#pullrequestreview-1647809203) 3WD.

**Comment by strepanier03** [comment] 2023-10-11 00:26
No worries on the checklist, we're all busy and it was done pretty quickly still anyway. 

Thanks for the heads-up on the Onyx changes. I'll review the timeline and update the payment post with a final determination. If we apply the bonus, I'll add an additional payment for the contributor as well to make things square. 

Will update you soon!

**Comment by strepanier03** [comment] 2023-10-11 00:52
**Timeline:**

- contributor assigned 2023-09-07
- comment from C+ about placing PR on hold 2023-09-12
- contributor bumped for review 2023-09-26
- C+ requested review from Expensify 2023-09-27
- Expensify merged 2023-09-27

@jjcoffee - Can you give me some context regarding when the PR was first put on hold? Was it created under the assumption it would be on hold right away because of the Onyx work? I think that it was likely before 2023-09-12 when a hold comment was left on the PR. If that's the case I want to consider that in my review.

Thanks!

**Comment by jjcoffee** [comment] 2023-10-11 08:39
@strepanier03 Sure! We actually thought the Onyx fix would take a while to come together so the plan was to add a temporary fix in the PR and then revert once the Onyx change was ready. Those Onyx changes came earlier than expected so we didn't need that initial workaround PR in the end and just decided to hold until the Onyx changes got merged.

**Comment by strepanier03** [comment] 2023-10-12 20:11
Thank you so much for that context. I'm going to update this for the urgency bonus and appreciate you raising it and discussing it with me. 

I'll finish updating this now.

**Comment by strepanier03** [comment] 2023-10-12 20:36
All right, this is all done. 

I've updated the payment for @tienifr to include the speed bonus and paid out @jjcoffee as well. 

Thank you both for the hard work you've done and the fantastic communication. You're both great members of the community and I enjoyed working with you.

**Closed by strepanier03** 2023-10-12 20:36 UTC
Labels: External, Daily, Awaiting Payment, Bug
