### ISSUE TITLE
[$500] Manage Members - Incorrect number disappeared from the list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35414] opened 2024-01-30 16:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4253323
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** We think that this bug might be related to 
**Slack conversation:**

## Action Performed:
1. Click/tap on Manage Members
2. Disable the internet connection in the device
3. Click/tap on the invite button
4. Enter a valid number with an incorrect international code, e.g +025857527444 and click/tap invite
5. Verify the number is grayed out in the members list
6. Close the settings sidebar
7. Enable the internet connection in the device
8. Verify Manage members is displayed with a red dot
9. Click/tap on Manage members
10. Verify the number is grayed out and a error message is displayed below it in the members list

## Expected Result:
Number is greyed out and an error message appears below the number in the list

## Actual Result:
Although red dot appears next to the Members/profile/WS name, the incorrect number disappears from the list, keeping the user questioning about the source of the error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bae321e4-b773-4dd6-a13a-2b0f4b511cab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011af31c3b882c3492</li>
        <li>Upwork Job ID: 1752362097915830272</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-30 16:05
We think that this bug might be related to  #wave8-collect-admins
CC @zanyrenney

**Comment by bernhardoj** [comment] 2024-01-30 16:08
Dupe of https://github.com/Expensify/App/issues/34852

**Comment by Christinadobrzyn** [comment] 2024-01-30 17:18
Thanks @bernhardoj closing in favour of https://github.com/Expensify/App/issues/34852

**Closed by Christinadobrzyn** 2024-01-30 17:18 UTC
Labels: External, Daily, Help Wanted, Bug
