### ISSUE TITLE
Log in - The Fab menu does not open automatically when log in with new account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10232] opened 2022-08-03 13:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. In the email field, enter a gmail email address for a new account.
3. Press continue
4. Verify there’s a message saying that a Magic Link has been sent to the email address
5. Navigate to the email inbox of the account and open the validation email
6. Copy the link and change it to staging.
7. Navigate to the staging link
8. Verify you’re brought to the “Set a Password” page
9. Set a password that follows the password requirements
10. After setting the password, verify the user is navigated to the main screen and Fub menu is open automatically

## Expected Result:
The Fab menu opens automatically when log in with new account

## Actual Results:##
The Fab menu does not open automatically when log in with new account

## Workaround:
Unknkown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.87.8

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any new account

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/182617042-c26a6bf4-cd10-4b7a-9350-bfcf19a47789.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by robertjchen** [comment] 2022-08-06 01:06
We are working on revamping this flow with the refactors, will revisit after those changes go out 🤔

**Comment by CortneyOfstad** [comment] 2022-10-18 19:27
@kbecciv Hello! Just doing some GH clean-up and wanted to see if this issue was still occurring? If so, let me know and I can continue troubleshooting from a Triage perspective. Thanks!

**Comment by CortneyOfstad** [comment] 2022-10-18 19:29
Sorry @tylerkaraszewski! Was in the wrong GH tab — PLEASE IGNORE!

**Comment by kbecciv** [comment] 2022-10-18 20:28
@CortneyOfstad Issue is still reproduced in build 1.2.17.4

https://user-images.githubusercontent.com/93399543/196537185-1d86a655-a569-4603-ab81-cc3f71903136.mp4

**Comment by Beamanator** [comment] 2022-10-19 13:57
I can reproduce in staging! The weird thing is, when I searched through lots & data returned by `OpenApp` I saw `"isFirstTimeExpensifyUser": "true"` - I wonder if the problem is that there's just soooo much data coming back in that command?

cc @luacmartins I wonder if you have an idea what's going on here since you've worked a lot on `OpenApp` I think?

**Comment by Beamanator** [comment] 2022-10-19 13:57
Marking `Internal` b/c this could definitely be related to our API side code

**Comment by luacmartins** [comment] 2022-10-19 16:05
@Beamanator I did some quick debugging and the issue is that we no longer set the `IS_LOADING_POLICY_DATA` key in OpenApp, so [this promise](https://github.com/Expensify/App/blob/ca501d965217c42ddc30f3516c1db7c10361c461/src/libs/actions/Welcome.js#L31-L35) never resolves and we don't show the FAB menu. We have a [PR](https://github.com/Expensify/App/pull/11627) that should fix this

**Comment by JmillsExpensify** [comment] 2022-10-19 23:32
I'll assign myself them and keep track of the related PR.

**Comment by Beamanator** [comment] 2022-10-20 10:08
Aah nice thanks for the link @luacmartins 👍

**Comment by luacmartins** [comment] 2022-10-20 15:17
@Beamanator the [App PR](https://github.com/Expensify/App/pull/11627) was merged, but I noticed that Auth can return 0 or 1 instead of a bool, which makes the first part of [this conditional](https://github.com/Expensify/App/blob/df900108b413826dd7c4b0e51ab6cf8092223289/src/libs/actions/Welcome.js#L30) fail. So I put up a fix [here](https://github.com/Expensify/Web-Expensify/pull/35239).

**Comment by JmillsExpensify** [comment] 2022-10-26 16:39
Given that both the [linked PR](https://github.com/Expensify/App/pull/11627) that put this issue on hold is now on staging, and related, so is the [PR fix](https://github.com/Expensify/Web-Expensify/pull/35239) mentioned immediately above, let's take this issue off hold, right?

**Comment by JmillsExpensify** [comment] 2022-10-26 16:40
I'm going to go ahead and do that @Beamanator and @luacmartins, and at that point we're just waiting for both PRs to hit production for this issue to close. Yeah?

**Comment by luacmartins** [comment] 2022-10-26 16:48
@JmillsExpensify that's correct!

**Comment by JmillsExpensify** [comment] 2022-10-26 16:51
Awesome thank you!

**Comment by luacmartins** [comment] 2022-10-27 18:27
Both PRs are in prod. Closing this issue, please reopen if needed!

**Closed by luacmartins** 2022-10-27 18:27 UTC
Labels: Reviewing, Engineering, Daily, Improvement, Internal, Bug
