### ISSUE TITLE
[HOLD] [$500] Workspace - WS member list when inviting users to workspace and room appears different

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31374] opened 2023-11-15 15:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Workspaces > any workspace > Members
3. Click Invite
4. Go to any room
5. Click on the room header > Members
6. Click Invite
Note that the list in these two invite pages is different

## Expected Result:
The list of members in the workspace when inviting members to the workspace and to the room should be the same, and in both, members should be displayed in alphabetical order

## Actual Result:
The list of members in the workspace when inviting members to the workspace and to the room is different
The list when inviting members to the workspace used to appear the same as the list when inviting members to room

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
</details> 

![Bug6277597_1700057363150!bandicam_2023-11-15_22-05-36-493](https://github.com/Expensify/App/assets/78819774/3f8c79f1-51e5-445a-80b9-18f118410e85)

https://github.com/Expensify/App/assets/78819774/ea4f5467-764b-43d6-bd34-c9c7b006fc36

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174fd74e2f19eea53</li>
        <li>Upwork Job ID: 1724806336848719872</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by unicorndev-727** [comment] 2023-11-15 15:28
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
The list of members in the workspace when inviting members to the workspace and to the room should be the same
### What is the root cause of that problem?
The root cause is that  RoomMembers filter report.participantAccountIDs and Workspaces filter policyMembers.
https://github.com/Expensify/App/blob/9d79fd12ce8f5d1dcb8870b61a8bc4513f55c935/src/pages/RoomMembersPage.js#L185
https://github.com/Expensify/App/blob/9d79fd12ce8f5d1dcb8870b61a8bc4513f55c935/src/pages/workspace/WorkspaceMembersPage.js#L299
### What changes do you think we should make in order to solve the problem?
We need to adjust these two values.
### What alternative solutions did you explore? (Optional)
  N/A

**Comment by unicorndev-727** [comment] 2023-11-15 16:17
Contributor details
Your Expensify account email: cory.stagg@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0184e107e8ee954e0d

**Comment by barros001** [comment] 2023-11-15 16:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The list of users looks different when inviting users to a workspace vs inviting users to a room. They are sorted differently

### What is the root cause of that problem?

https://github.com/Expensify/App/pull/29044/files

This PR introduced a way to invite multiple users to a workspace. By doing that, in changed the way the list of users is handled:

```js
            // Only add the user to the invites list if it is valid
            if (userToInvite) {
                newUsersToInviteDict[userToInvite.accountID] = userToInvite;
            }

            // Add all personal details to the new dict
            _.each(inviteOptions.personalDetails, (details) => {
                newPersonalDetailsDict[details.accountID] = details;
            });

            // Add all selected options to the new dict
            _.each(newSelectedOptions, (option) => {
                newSelectedOptionsDict[option.accountID] = option;
            });

...
...
...
setPersonalDetails(_.values(newPersonalDetailsDict));
```

When the users are pushed into `newPersonalDetailsDict` and later `_.values(newPersonalDetailsDict)` is called, it sorts the list of users differently.

RoomInvitePage.js does not do that, although it also allow to invite multiple users.

### What changes do you think we should make in order to solve the problem?


We have to lists that does pretty much the exact same thing with duplicate logic:

* [WorkspaceInvitePage](https://github.com/Expensify/App/blob/48782c700e6abd56c73d317ac1c5bc9462547cfc/src/pages/workspace/WorkspaceInvitePage.js#L66)
* [RoomInvitePage](https://github.com/Expensify/App/blob/48782c700e6abd56c73d317ac1c5bc9462547cfc/src/pages/RoomInvitePage.js#L65)

Both allow to invite multiple users but the implementation varies. My proposal is to extract the logic into a shared hook and use it in both invite pages so that logic is shared and we avoid this type of problem in the future.


### What alternative solutions did you explore? (Optional)

This is mostly a sorting issue. Another approach is to explicitly sort the list by name/email/telephone so that regardless of the logic, the list would still look the same. This approach would be the easiest and less risky.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by unicorndev-727** [comment] 2023-11-15 16:19
Contributor details
Your Expensify account email:cory.stagg@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0184e107e8ee954e0d

**Comment by unicorndev-727** [comment] 2023-11-15 16:20
Contributor details
Your Expensify account email: cory.stagg@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0184e107e8ee954e0d

**Comment by unicorndev-727** [comment] 2023-11-15 16:26
Contributor details
Your Expensify account email: cory.stagg@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0184e107e8ee954e0d

**Comment by Santhosh-Sellavel** [comment] 2023-11-15 17:19
@stephanieelliott Can you assign a new C+ plus here? Unassigning myself due to low bandwidth.

**Comment by mananjadhav** [comment] 2023-11-26 17:51
I'll review them today/tomorrow.

**Comment by mananjadhav** [comment] 2023-11-27 17:25
@tienifr @barros001 both identified the correct root cause. @tienifr's [proposal](https://github.com/Expensify/App/issues/31374#issuecomment-1812755925) looks good to me.

**Comment by cead22** [comment] 2023-11-30 18:04
I don't think we should do what's in the approved proposal. We've seen this type of issue elsewhere, where we have 2 places using different logic when they should use the same logic, and the proposal is to update 1 of the two places, because when we updated one we didn't update the other.

I think what we should be doing is designing this in a way that we reuse the code that's supposed to have the same logic for both places

**Comment by mananjadhav** [comment] 2023-11-30 18:11
> I think what we should be doing is designing this in a way that we reuse the code that's supposed to have the same logic for both places.

@cead22  Agreed. The proposal mentions the same thing? Atleast that's what I interpreted by the following lines in the proposal. 

> For usersToInvite we should did the same as
> for personalDetails and selectedOptions, we should do the same as RoomInvitePage to preserve the order

**Comment by cead22** [comment] 2023-12-01 00:06
Oh, perhaps I misunderstood. My read was that we were going to update `RoomInvitePage.js` to have the same logic that's in `WorkspaceInvitePage.js`.

If that's the case, we'll end up with the same code in 2 places, and those 2 places have duplicate logic.

Would it be possible to extract the common logic into a function, that is called from both places?

**Comment by barros001** [comment] 2023-12-01 02:23
> Would it be possible to extract the common logic into a function, that is called from both places?

That’s exactly what i suggested on [my proposal](https://github.com/Expensify/App/issues/31374#issuecomment-1812842387)

**Comment by cead22** [comment] 2023-12-06 01:40
@tienifr to be honest, I don't fully understand your proposal, specifically, I don't know what you're suggesting specifically in your "What changes do you think we should make in order to solve the problem?" section. Can you update the proposal to make it clearer?
- "For usersToInvite we should did the same as" this links to `setUsersToInvite(_.values(newUsersToInviteDict));`
- "to support multiple emails as we did in https://github.com/Expensify/App/pull/29044", what exactly are we copying from that PR?
-  "for personalDetails and selectedOptions, we should do the same as RoomInvitePage to preserve the order", what exactly are you proposing we do similarly?

**Comment by cead22** [comment] 2023-12-07 15:47
@mananjadhav any thoughts on the comments above?

**Comment by barros001** [comment] 2023-12-07 16:30
Just wanted to give a quick update. I’ve been traveling for the past 30 hours and as soon as I settle, in a few more hours, I’ll address the comments above.

**Comment by barros001** [comment] 2023-12-07 18:27
[cead22](https://github.com/cead22)
> @barros001 why is your alternative easier and less risky than your main proposal?

It's less risky in the sense that we don't need to change a lot of code nor move things around. Sorting by name is the right way IMO so we would just make sure the other page that sorts by account id will keep its sorting by name. But to @tienifr point, this is a quick way out, but not necessarily the ideal solution. I don't see why we have similar logic duplicated in multiple places. Looks like what we need is a single component for selecting users that can be used in multiple pages.

Looking again at the code, I was very confused by what exactly `newUsersToInviteDict` does. It appears that at one point users were able to type multiple phone numbers and or emails and multiple rows would show to invite them (not search, but rather invite new people in), but that has [since been removed](https://github.com/barros001/expensify-app/commit/cf357fb70e66b9f5255db39c45fbaa0beef9f0a4). All the new logic around `newUsersToInviteDict` and how everything is grouped by account id is no longer necessary and really not doing any good.

Unless I'm missing something here, `RoomInvitePage` does exactly the same thing as `WorkspaceInvitePage` with a much cleaner and simpler logic. If that's true, then we should convert `WorkspaceInvitePage` and make it the same as  `RoomInvitePage` (there might be some extra fixes on workspace that's not on room so there's a change that we would pick the best of each component).. That said, duplicate logic is no good, so ideally we extract the logic into a new component and reuse it on both pages. 

This new component would encapsulate the following (might not be a complete list, I'm quickly looking over the code and could be missing something):

* `getSections`
* `toggleOption`
* the initial `useEffect`
* `<SelectionList/>`
* Maybe even `<FormAlertWithSubmitButton/>`
* and take a callback that would be called when the selected options change, to notify the page

That's most of the page, but we still need to leave out all the specific logic for each page such as the `inviteUsers` function, among others.

Glad to collaborate with @tienifr on this if there's an appropriate path to doing so. I just wanted to point out that I'll have lower bandwidth for the next week or so due to travels.

**Comment by cead22** [comment] 2023-12-12 02:17
Following up on this since Melvin is bumping, any progress on this yet?

**Comment by mananjadhav** [comment] 2023-12-12 04:24
I did go through the conversation @cead22. I am okay with @tienifr and @barros001 collaborating on this one. I am just not sure yet if we have defined the expected behavior here? By which field do we want them to be sorted? Can we update that in the issue? Then it would make sense to approve the proposals.

**Comment by barros001** [comment] 2023-12-12 09:54
> I am just not sure yet if we have defined the expected behavior here? By which field do we want them to be sorted? Can we update that in the issue?

The list is already sorted as can be seen here:

https://github.com/Expensify/App/blob/4239252d5ace1039fa2aaf8d707f4e5de8523309/src/libs/OptionsListUtils.js#L1611

`WorkspaceInvitePage` is the one doing things wrong and re-sorting it (accidentally) again by account id. We should just maintain the sorting we already have.

**Comment by cead22** [comment] 2023-12-12 15:36
I like sorting alphabetically 👍

**Comment by mananjadhav** [comment] 2023-12-17 18:35
Okay thanks for confirming @cead22. As I said we can have both collaborating, how do we assign the issue?

**Comment by stephanieelliott** [comment] 2023-12-18 19:55
Heya @tienifr and @barros001,  I've assigned you both on this issue, given that you are going to be collaborating on this one! Payment will be split 50/50 (so $250/ea), but if you think this should be reevaluated feel free to raise a case as described [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#user-content-payment-for-contributions).

**Comment by quinthar** [comment] 2023-12-26 02:03
@mallenexpensify is doing an overhaul of this invite component, so I suggest we pause this.

**Comment by quinthar** [comment] 2023-12-26 02:30
Let's pause work on this until we settle having a unified design here: https://expensify.slack.com/archives/C01GTK53T8Q/p1703557793897069?thread_ts=1703360093.158969&cid=C01GTK53T8Q

**Comment by cead22** [comment] 2023-12-26 17:55
Updated title to reflect this is on hold

**Comment by stephanieelliott** [comment] 2024-01-10 20:07
This is still paused while we settle on a unified design.

**Comment by stephanieelliott** [comment] 2024-02-09 19:18
The actual design has not yet been settled, but we have agreed to standardize to a singular Workspace > Members design that will apply basically everywhere -- when creating a split or group, adding/removing members from a workspace, room, group or thread, etc. 

That Workspace > Members design is going to be implemented as part of Wave 8: Simplified Collect ([internal doc link](https://docs.google.com/document/d/1Qv6V4nRqIbZfzQML_saCbrAEqQVIBsiQ3HE1UO7RCxQ/edit)). So seeing as this is going to be overhauled soon anyway, I think we should close this issue and not make any changes to the current behavior in the meantime. @cead22 what do you think, do you agree?

**Comment by cead22** [comment] 2024-02-09 19:37
Yes

**Comment by mallenexpensify** [comment] 2024-02-12 17:36
Reopening, pending discussion of potential compensation.

**Comment by mananjadhav** [comment] 2024-02-12 18:43
@mallenexpensify My recommendation is we payout for the issue. We did review the proposals, went through some discussions both the contributors engaged, and also created the PR. I did partial review of the PR. It was put on hold before I could finish the review, and hence I didn't work on the checklist.

**Comment by stephanieelliott** [comment] 2024-02-12 19:03
Thanks for raising this @mananjadhav and @barros001 (and @mallenexpensify for kickstarting the discussion). Closing this without issuing payment was an oversight, and I agree that this should be paid as normal due to the amount of that was done. This is also in line with our internal documentation on contributor payment structure [here](https://stackoverflowteams.com/c/expensify/questions/8590/8591#8591).

**Comment by mananjadhav** [comment] 2024-02-12 19:06
No worries @stephanieelliott. Would you be able to post the payout summary? For the contributors, the amount needs to be split between @barros001 and @tienifr. thank you 🙌

**Comment by stephanieelliott** [comment] 2024-02-12 19:11
Yep! Summarizing payment on this issue: 

 - Contributor: @barros001 and @tienifr ([split payment](https://github.com/Expensify/App/issues/31374#issuecomment-1861476678)) 
    - @barros001 $250 via Upwork -- offer extended, please accept! 
    - @tienifr $250 via Upwork -- offer extended, please accept! 
 - Contributor+: @mananjadhav $500, please request via NewDot 
 
 Upwork job is here: https://www.upwork.com/jobs/~019b0016e1e6bb4d02

**Comment by JmillsExpensify** [comment] 2024-02-12 19:46
$500 approved for @mananjadhav based on summary above.

**Comment by stephanieelliott** [comment] 2024-02-14 07:34
All paid, thanks!

**Closed by stephanieelliott** 2024-02-14 07:34 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Bug
