### ISSUE TITLE
[$1000] [HIGH] Approver is incorrectly subscribed to the thread of a smartscanned receipt 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#35072] opened 2024-01-24 16:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** n/a
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705614762271629

## Action Performed:
_Preconditions: a employee and approver must be setup in a collect workspace. Both are logged in simultaneously_
1. As the employee - navigate to the collect workspace chat
2. Submit a receipt that will fail smartscan 

## Expected Result:
The approver should not be subscribed to the expense thread where the smartscan failed. The conversation is displayed in the LHN. 
## Actual Result:
The approver is subscribed to the receipt thread and it's visible in LHN

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/44479856/1ccba3e2-ddfc-4367-9b3c-e9fc3f2e70a0)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014dbb9cde5df6d294</li>
        <li>Upwork Job ID: 1750193774879903744</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by bfitzexpensify** [comment] 2024-01-25 20:43
Yes, I'm not sure this is definitely internal. Adding external label so that contributors can at least take a look at the cause.

**Comment by bfitzexpensify** [comment] 2024-01-31 21:42
Still awaiting proposals.

**Comment by bfitzexpensify** [comment] 2024-02-02 21:09
No action for a week here, doubling this to get some eyes on it.

**Comment by puneetlath** [comment] 2024-02-02 21:59
@bfitzexpensify I think there's a strong chance this is a back-end issue.

**Comment by bfitzexpensify** [comment] 2024-02-06 07:46
Checking in Slack [here](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1707171857156309)

**Comment by youssef-lr** [comment] 2024-02-12 22:11
Investigating tomorrow.

**Comment by youssef-lr** [comment] 2024-02-15 10:39
I have been tried to reproduce this yesterday but with no luck. I'm on it again today.

**Comment by youssef-lr** [comment] 2024-02-17 02:47
This should be fixed once this https://github.com/Expensify/Auth/pull/9713 deploys.

**Comment by youssef-lr** [comment] 2024-02-20 04:35
Changing to weekly and we'll keep an eye if this is still an issue. But I'm 95% sure it should be fixed.

**Comment by youssef-lr** [comment] 2024-02-22 01:12
Adding `Reviewing` to bypass Melvin changing this to Weekly.

**Comment by youssef-lr** [comment] 2024-02-27 05:56
We haven't seen reports of this bug again, closing!

**Closed** 2024-02-29 09:44 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug
