### ISSUE TITLE
[HOLD for payment 2023-12-28] [$500] Settings - Focus lost from message on visiting shortcut and back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33173] opened 2023-12-15 16:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open settings->profile->status
3. Use any keyboard shortcut like CTRL+J to open any shortcut page in RHN
4. Click on back and observe that app does not focus back on Message field

## Expected Result:
App should focus back on Message field on back from any keyboard shortcut on status page

## Actual Result:
App does not focus back on Message field on back from any keyboard shortcut on status page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/37f49140-124c-4460-9aec-7a84798831d0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e6a18e5a303c446</li>
        <li>Upwork Job ID: 1735697081490046976</li>
        <li>Last Price Increase: 2023-12-15</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28063848</li>
<li>bernhardoj | Contributor | 28063849</li>
</ul></li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-12-18 15:47
@sophiepintoraetz I'm OOO starting Monday, December 18 (today) through Tuesday, January 2.

**Current status:**
PR is ready for review!

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by sophiepintoraetz** [comment] 2023-12-21 04:36
@Ollyws @bernhardoj Just to clarify - it looks like the PR has merged so I think we're subject to the 7 day regression period, correct? This would place us at 26th Dec.

If that's correct, unfortuantely, this places us in the middle of my OOO (I'm back 3 Jan) and there will be a lot of OOO at that time, so the payment will be processed once @johncschuster is back in office on 2 Jan. To help facilitate a quick payment, please make sure that you have accepted the offers and that the BZ checklist has been completed prior to 2 Jan!

**Comment by sophiepintoraetz** [comment] 2023-12-22 01:43
@johncschuster - as noted [here](https://github.com/Expensify/App/issues/33173#issuecomment-1865463777), neither of us will be in office to facilitate payment and to no overload the people who are working over the holidays, I said payment will be processed once you are back in office. 

For next time, ideally, you would be keeping this issues to assigned to you or at least please don't unassign yourself from an issue - keep yourself assigned and if the co-assignee ends up completing the chore where they will unassign you. That's all captured in this [SO here](https://stackoverflowteams.com/c/expensify/questions/8836).

**Comment by strepanier03** [comment] 2023-12-28 19:38
@Ollyws - Please complete the checklist and feel free to ping me when you do so I can finish up here. 

@bernhardoj - I've paid you out and closed the contract, thanks for you work!

**Comment by strepanier03** [comment] 2024-01-03 21:15
Thank you @Ollyws - I'm just getting back into the office today and working on this now. Update soon!

**Comment by strepanier03** [comment] 2024-01-03 21:24
@Ollyws - All set, I've paid out this contract and finished up my steps. Going to close this out now, thanks again everyone!

**Closed by strepanier03** 2024-01-03 21:24 UTC
Labels: External, Daily, Awaiting Payment, Bug
