### ISSUE TITLE
Sage Intacct - Back button on workspace editor returns to Accounting page again

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44813] opened 2024-07-04 10:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/43661
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User has a few workspaces.
- One of the workspaces is connected to Sage Intacct.

1. Go to staging.new.expensify.com
2. Go to another workspace that is not connected to Sage Intacct.
3. Go to Accounting.
4. Tap Connect next to Sage Intacct.
5. Select Reuse existing connection.
6. Tap on the workspace that is connected to Sage Intacct.
7. Tap back button on the top left.
8. Tap back button again.

## Expected Result:
App will return to workspace list.

## Actual Result:
App returns to Accounting page again (from Step 3).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fddb9791-012f-42ae-8f05-e980a811f600

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-07-04 10:28
@twisterdotcom FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-07-04 10:28
We think this issue might be related to the #collect project.

**Comment by lakchote** [comment] 2024-07-04 13:11
cc @SzymczakJ since you've worked on https://github.com/Expensify/App/pull/43661

**Comment by lakchote** [comment] 2024-07-04 13:13
I'd say it's not a blocker, as it's an edge case and it doesn't affect core functionality. 

Plus, it's behind the `intacctOnNewExpensify` beta.

**Comment by twisterdotcom** [comment] 2024-07-04 13:24
@SzymczakJ let us know if you want to take this. Otherwise we can open it up.

**Comment by SzymczakJ** [comment] 2024-07-04 13:27
Implementation of this feature is in progress and "Reuse existing connection" screen is still not ready. Right now I'm working on [follow-up PR](https://github.com/Expensify/App/issues/44669) for Sage Intacct and I'll fix this navigation bug in it. Is it okay with you? 
Assign me to this one so I can notify you to retest when my fix is merged 😃

**Comment by hungvu193** [comment] 2024-07-04 13:31
@lakchote  Please assign me as well since I worked with @SzymczakJ in the offending PR

**Comment by SzymczakJ** [comment] 2024-07-08 09:21
[Follow up PR](https://github.com/Expensify/App/issues/44669) still under work, waiting for some BE features.

**Comment by hungvu193** [comment] 2024-07-11 04:11
Still working on the PR.

**Comment by lakchote** [comment] 2024-07-15 10:48
Not overdue, @hungvu193 just commented.

**Comment by SzymczakJ** [comment] 2024-07-16 09:37
[Follow-up merged](https://github.com/Expensify/App/issues/44669), this should be fixed 😄

**Comment by twisterdotcom** [comment] 2024-07-18 21:31
Are we just waiting for a deploy now?

**Comment by hungvu193** [comment] 2024-07-19 01:01
I think the PR that fixed this issue was deployed to staging, we can retest this and close if we can't reproduce

**Comment by lakchote** [comment] 2024-07-19 06:39
The [PR](https://github.com/Expensify/App/pull/44850) that fixed it was actually even deployed to production

Asked for a QA retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1721371021731659)

**Comment by twisterdotcom** [comment] 2024-07-19 11:51
Okay, do we need to handle any payment here? Or will this be handled in https://github.com/Expensify/App/issues/44669 then?

**Comment by hungvu193** [comment] 2024-07-19 11:52
No payment needed here. We can close it.

**Closed** 2024-07-19 11:54 UTC
Labels: Engineering, Daily, Bug
