### ISSUE TITLE
The archived room's welcome message displays with "__fake__" username instead of the actual username

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22386] opened 2023-07-06 22:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to UserA's account
2. Navigate to the "New room" section
3. Enter a name for the room and select UserA's workspace
4. Set the room visibility to "Public"
5. Click on the "Create room" button
6. Go to the room details
7. Go to the Share code > Copy URL to clipboard
8. Now go to the connected workspace and delete the it
9. Open another browser and paste the room's URL
## Expected Result: 
The archived room's welcome message should display the actual username instead of "__fake__" username
## Actual Result: 
The archived room's welcome message is displayed with the "__fake__" username instead of the actual username

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6b39eacc-f403-491c-a1a6-df7a17ac9a4f

https://github.com/Expensify/App/assets/43996225/8a9d6266-86aa-4ede-9f6f-7ac14128df06

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688594374085059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ygshbht** [comment] 2023-07-07 09:52
Probably a backend issue 
![image](https://github.com/Expensify/App/assets/65986357/102ef7c9-b3d1-49ca-b57b-8783a9960369)

**Comment by lschurr** [comment] 2023-07-07 15:02
Hey @AndrewGable - should this be something we handle internally?

**Comment by AndrewGable** [comment] 2023-07-07 15:05
I think we need to have a discussion on expected behavior here first, but if it needs to be a backend change then we can handle it internally.

**Comment by lschurr** [comment] 2023-07-07 15:47
Cool, looks like the Slack thread also mentions that this might fix it - https://github.com/Expensify/App/issues/20940

**Comment by AndrewGable** [comment] 2023-07-07 15:48
Let's mention this as a case in that issue and close this one 👍

**Closed** 2023-07-07 15:56 UTC
Labels: Engineering, Daily, Bug
