### ISSUE TITLE
[$500] IOU - The selected participant is marked as Split briefly when returning from confirmation page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33068] opened 2023-12-14 14:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal 
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Click + > Request money > Manual.
3. Enter amount and select a participant.
4. On the confirmation page, click Back.

## Expected Result:
The selected participant will not be marked as split when returning from confirmation page.

## Actual Result:
The selected participant is marked as split briefly when returning from confirmation page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/85f0e430-6d4b-496a-b70d-7a4abcc10977

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0125b21107076e6c23</li>
        <li>Upwork Job ID: 1735308667400241152</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-12-14 15:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU - The selected participant is marked as Split briefly when returning from confirmation page
### What is the root cause of that problem?
When press back button, we clear participants if iou is not split.
https://github.com/Expensify/App/blob/207d4ac23598dd10dad0275344d750b62b67a4a3/src/pages/iou/request/step/IOURequestStepConfirmation.js#L112-L114
### What changes do you think we should make in order to solve the problem?
We need to remove that.
### What alternative solutions did you explore? (Optional)


https://github.com/Expensify/App/assets/65789015/796c5973-72c4-4b3a-af1f-562e922e709a

**Comment by sfurqan2** [comment] 2023-12-14 15:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is a brief state where the participant is marked as split. When we go back.
### What is the root cause of that problem?
The problem comes from the fact that there is a delay between loading the state from ONYX. As the check only checks for showing the Selected tag as button, if that fails it defaults to showing the tick.
### What changes do you think we should make in order to solve the problem?
We can hide the tick behind a check so that its only shown when the participant is marked as split.


### What alternative solutions did you explore? (Optional)
N/A

**Comment by zukilover** [comment] 2023-12-14 15:25
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Split button briefly in a selected state when navigating back from confirmation tab

### What is the root cause of that problem?
When navigating back, what happens is, the store is clearing `participants` then navigate back.
But this process happens synchronously.

https://github.com/Expensify/App/blob/b4d1777c17623da386281ff5a38fff5f059e90df/src/pages/iou/request/step/IOURequestStepConfirmation.js#L112-L115

### What changes do you think we should make in order to solve the problem?
We need to make sure that navigating back happens AFTER store update is resolved.

Change these lines:
https://github.com/Expensify/App/blob/b4d1777c17623da386281ff5a38fff5f059e90df/src/libs/actions/IOU.js#L246-L248

to:
```javascript
async function setMoneyRequestParticipants_temporaryForRefactor(transactionID, participants) {
    await Onyx.merge(`${ONYXKEYS.COLLECTION.TRANSACTION_DRAFT}${transactionID}`, {participants});
}

and navigate after store is resolved:
```javascript
if (iouType === CONST.IOU.TYPE.REQUEST) {
                await IOU.setMoneyRequestParticipants_temporaryForRefactor(transactionID, []);
            }
```
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by unicorndev-727** [comment] 2023-12-14 15:31
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
For the optimistic account, the ReportWelcomeText shows the email as text, not a link.
### What is the root cause of that problem?
The root cause is that  there is time delay to delete participants when returning back to participant page.
https://github.com/Expensify/App/blob/207d4ac23598dd10dad0275344d750b62b67a4a3/src/pages/iou/request/step/IOURequestStepConfirmation.js#L112-L114
### What changes do you think we should make in order to solve the problem?
We can add the condition in here.
https://github.com/Expensify/App/blob/207d4ac23598dd10dad0275344d750b62b67a4a3/src/pages/iou/request/step/IOURequestStepParticipants.js#L92

```
<MoneyRequestParticipantsSelector
                ref={(el) => (optionsSelectorRef.current = el)}
                participants={iouType === CONST.IOU.TYPE.SPLIT ? participants : []}
                onParticipantsAdded={addParticipant}
                onFinish={goToNextStep}
                iouType={iouType}
                iouRequestType={iouRequestType}
            />
```
### What alternative solutions did you explore? (Optional)
  N/A

**Comment by joekaufmanexpensify** [comment] 2023-12-14 22:03
I am not sure this is really worth fixing. Going to bring to Slack to discuss.

**Comment by joekaufmanexpensify** [comment] 2023-12-14 22:06
Discussing [here. ](https://expensify.slack.com/archives/C05RECHFBEW/p1702591566329989)

**Comment by alitoshmatov** [comment] 2023-12-18 08:00
Waiting for @joekaufmanexpensify confirmation here

**Comment by joekaufmanexpensify** [comment] 2023-12-18 15:36
I bumped the internal discussion

**Comment by joekaufmanexpensify** [comment] 2023-12-18 16:21
We decided to proceed. @alitoshmatov please proceed with reviewing proposals!

**Comment by alitoshmatov** [comment] 2023-12-20 08:48
Reviewing

**Comment by alitoshmatov** [comment] 2023-12-20 09:11
@ZhenjaHorbach Your solution is not working, can you provide me with recording if it is working for you. Also I do not agree with your approach, it making everything complex and I have not seen similar approach throughout the app

**Comment by alitoshmatov** [comment] 2023-12-20 09:12
@yh-0218 I think you misunderstood this issue, the issue is that selected avatar is appearing with a checkmark for a small amount of time. We should fix that

**Comment by alitoshmatov** [comment] 2023-12-20 09:16
@sfurqan2 Can you elaborate your solution and provide some code. I am not sure what you are talking about

**Comment by alitoshmatov** [comment] 2023-12-20 09:18
@zukilover As far as I know we don't use `async` `await` approach in this app. Also I haven't seen any usage of delaying navigation this way

**Comment by alitoshmatov** [comment] 2023-12-20 09:22
@unicorndev-727  If we provide empty participants won't it split action where all selected participants should be checked when coming back to participants page. I doubt your solution works. Can you provide screen recording of your solution.

**Comment by unicorndev-727** [comment] 2023-12-20 11:16
> @unicorndev-727 If we provide empty participants won't it split action where all selected participants should be checked when coming back to participants page. I doubt your solution works. Can you provide screen recording of your solution.

@alitoshmatov
I updated my [proposal](https://github.com/Expensify/App/issues/33068#issuecomment-1856064063) based on your suggestion and added the result video.

**Comment by joekaufmanexpensify** [comment] 2023-12-21 16:12
Moving this to weekly for the holidays. @alitoshmatov are we close to selecting a proposal?

**Comment by joekaufmanexpensify** [comment] 2024-01-01 17:37
@alitoshmatov bump on whether any of the proposals here work?

**Comment by alitoshmatov** [comment] 2024-01-02 10:38
@ZhenjaHorbach Can you explain where did `isFocused` and `isFocusedPrevious` come from?

**Comment by alitoshmatov** [comment] 2024-01-02 10:41
@unicorndev-727 I think your solution is a workaround and overcomplicating everything

**Comment by unicorndev-727** [comment] 2024-01-02 14:35
> @unicorndev-727 I think your solution is a workaround and overcomplicating everything

@alitoshmatov 
I just used two additional variables and added the logic for identifying if the page is focused and previous IOU type is not `split` after clicking `next` button.
Two conditions are very important, I think.

**Comment by DylanDylann** [comment] 2024-01-03 09:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The selected participant is marked as split briefly when returning from confirmation page.

### What is the root cause of that problem?
The navigation finish before the data is updated to ONYX


### What changes do you think we should make in order to solve the problem?
First, let's see this code
https://github.com/Expensify/App/blob/2fe11741539c96dadd2ce109b8538b01d02a60cb/src/pages/PrivateNotes/PrivateNotesListPage.js#L64-L69

I suggest we do the same thing as we did in PrivateNotesListPage above

In here
https://github.com/Expensify/App/blob/2fe11741539c96dadd2ce109b8538b01d02a60cb/src/pages/iou/request/step/IOURequestStepConfirmation.js#L112
Using setTimeout with 100 ms
```
const navigateToParticipantPageTimeout = setTimeout(() => {
                console.log('navigateToParticipantPageTimeout')
                Navigation.goBack(ROUTES.MONEY_REQUEST_STEP_PARTICIPANTS.getRoute(iouType, transactionID, reportID));
            }, 100);
            
            return () => {
                clearTimeout(navigateToParticipantPageTimeout);
            };

```

### What alternative solutions did you explore? (Optional)
NA

**Comment by joekaufmanexpensify** [comment] 2024-01-03 14:28
Still discussing proposals

**Comment by alitoshmatov** [comment] 2024-01-04 11:37
I don't think any proposals is addressing the main issue which is race condition of navigation and onyx. Even though function for setting onyx data is called first, going back navigation function is finishing before that.

Started slack discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1704368050838699

**Comment by DylanDylann** [comment] 2024-01-04 13:22
@alitoshmatov could you help to check [my proposal](https://github.com/Expensify/App/issues/33068#issuecomment-1875089835)? I suggest we use the old pattern here
https://github.com/Expensify/App/blob/2fe11741539c96dadd2ce109b8538b01d02a60cb/src/pages/PrivateNotes/PrivateNotesListPage.js#L64-L69

**Comment by joekaufmanexpensify** [comment] 2024-01-04 15:48
We chatted about this in Slack, and it turns out this issue will be handled in [this PR](https://github.com/Expensify/App/pull/33482). Closing as no action is needed here.

**Closed by joekaufmanexpensify** 2024-01-04 15:48 UTC
Labels: External, Daily, Help Wanted, Bug
