### ISSUE TITLE
[$500] State values not arranged alphabetically

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29818] opened 2023-10-17 18:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697537729402059

## Action Performed:
1. Open the app
2. Open settings->profile->personal details->address
3. Select united states as country
4. Open state and scroll down, observe that 'Vermount' is after 'Virginia', 'West Virginia' is after 'Wisconsin' and 'District of columbia' is in the end
## Expected Result: 
App should arrange state values alphabetically as we do for other fields in address and throughout the app
## Actual Result: 
App does not arrange state values alphabetically

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/b30299fd-5c78-487c-a2c1-2737203bfe01

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/265cd7e1-0740-41b6-9cf3-87cf7ce95b60

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/93bb6f4d-b554-4a1e-b2a0-04a5271b7916

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/a36e19d0-afa8-423a-81d8-c9fffe0d2224

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/0e927aa2-4666-408b-b813-f726c7ab44cd

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/71c5b493-8d56-4543-9e55-5ce7005a48b5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1c8db2aac1aa51d</li>
        <li>Upwork Job ID: 1714353027249922048</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-10-17 18:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

State values not arranged alphabetically

### What is the root cause of that problem?

The root cause of this issue is that the countryStates is not sorted after mapped from `COMMON_CONST.STATES`, see 

https://github.com/Expensify/App/blob/623ea8470629ac72aa1e8e416c50fbb708120775/src/components/StatePicker/StateSelectorModal.js#L55-L69

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should sort state list after mapping from `COMMON_CONST.STATES`. We can apply in place sorting and sort states by `text` field. We can change this [line](https://github.com/Expensify/App/blob/623ea8470629ac72aa1e8e416c50fbb708120775/src/components/StatePicker/StateSelectorModal.js#L67) to

```js
            }).sort((a, b) => a.text.localeCompare(b.text)),
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by abzokhattab** [comment] 2023-10-17 18:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Not found page display briefly when we access the WorkspaceSettingsCurrencyPage via deep link

### What is the root cause of that problem?

we dont sort states alphabetically here:

https://github.com/Expensify/App/blob/4b4498154180a60a275b922d0d04db0194b87079/src/components/StatePicker/StateSelectorModal.js#L55-L69

### What changes do you think we should make in order to solve the problem?

add soryBy stateName:

````js

    const countryStates = useMemo(
        () =>
            _.chain(COMMON_CONST.STATES)
                .keys()
                .map((state) => {
                    const stateName = translate(`allStates.${state}.stateName`);
                    const stateISO = translate(`allStates.${state}.stateISO`);
                    return {
                        value: stateISO,
                        keyForList: stateISO,
                        text: stateName,
                        isSelected: currentState === stateISO,
                        searchValue: StringUtils.sanitizeString(`${stateISO}${stateName}`),
                    };
                })
                .sortBy((state) => state.text.toLowerCase())
                .value(),
        [(translate, currentState)],
    );
    ```

````

**Comment by ayazhussain79** [comment] 2023-10-17 18:50
### Proposal 
### Please re-state the problem that we are trying to solve in this issue. 

We currently face an issue where the state values in the **StateSelectorModal.js** file are not sorted alphabetically, 
### What is the root cause of that problem? 

The problem originates from the countryStates function in StateSelectorModal.js, which fails to sort the states alphabetically.

**What changes do you think we should make in order to solve the problem?**

To tackle this issue effectively, we can replacing the current countryStates function with the following optimized code:
```
 const countryStates = useMemo(
        () =>
            _.chain(_.keys(COMMON_CONST.STATES))
                .map((state) => {
                    const stateName = translate(`allStates.${state}.stateName`);
                    const stateISO = translate(`allStates.${state}.stateISO`);
                    return {
                        value: stateISO,
                        keyForList: stateISO,
                        text: stateName,
                        isSelected: currentState === stateISO,
                        searchValue: StringUtils.sanitizeString(`${stateISO}${stateName}`),
                    };
                })
                .sortBy((state) => state.text.toLowerCase())
                .value(),
        [translate, currentState]
    );
```
 ###  What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2023-10-18 00:42
## Proposal 
### Please re-state the problem that we are trying to solve in this issue. 

State values not arranged alphabetically

### What is the root cause of that problem? 

The States are sorted using `StateISO` with only exception in `District Of Columbia` in `expensify-common`.

### What changes do you think we should make in order to solve the problem?

We need to confirm the order of States with an Engineer (maybe its intentional), if it comes `District Of Columbia` should be rearranged properly, we will rearrange this in `expensify-common` only.

As using sort will impact performance

 ### What alternative solutions did you explore? (Optional)
NA

**Comment by AliYar-Khan** [comment] 2023-10-18 09:47
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
State values not arranged alphabetically

###What is the root cause of that problem?
we dont have sorted states alphabetically comming from expensify-common/lib/CONST

### What changes do you think we should make in order to solve the problem?
Sort the states in expensify common lib alphabetically

###What alternative solutions did you explore? (Optional)
Sort the states after the import

**Comment by eh2077** [comment] 2023-10-18 10:56
@Ollyws Thanks for checking proposals. 




> I agree with @shubham1206agra here, the states are ordered by the ISO value in [expensify-common](https://github.com/Expensify/expensify-common/blob/6517be47d31aef07b15c90fdf347a341f3b9b58d/lib/CONST.jsx#L62). I'm not sure if this is a bug...

I think this is a bug. Because [COMMON_CONST.STATES](https://github.com/Expensify/expensify-common/blob/6517be47d31aef07b15c90fdf347a341f3b9b58d/lib/CONST.jsx#L62) is a dictionary actually which is unordered. In StateSelectorModal, we get state keys from `COMMON_CONST.STATES` and map state key to stateName and stateIOS by calling `translate` method to enable locale feature. 

So, I think we should sort the list of states, `countryStates`, by the `text` field (stateName) using `localeCompare` method to compare them.

See

https://github.com/Expensify/App/blob/623ea8470629ac72aa1e8e416c50fbb708120775/src/components/StatePicker/StateSelectorModal.js#L55-L69

**Comment by adelekennedy** [comment] 2023-10-24 00:54
ah! Okay closing this one

**Closed by adelekennedy** 2023-10-24 00:54 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
