### ISSUE TITLE
[$250] Onboarding - The app freezes if a FAB menu is clicked before the onboarding video shows

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46531] opened 2024-07-30 19:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Input anything for "First name" and click on the "Continue" button
4. Quickly click on the FAB and on any button from the dropdown menu
5. Click anywhere to close the RHP
6. Click on any interactable element

## Expected Result:
I should be able to interach with the app

## Actual Result:
The app freezes if a FAB menu is quickly clicked before the onboarding video shows

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/520f6634-bc2d-4d98-873c-969380bcd6d4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab200147805fc6ce</li>
        <li>Upwork Job ID: 1818775055281225355</li>
        <li>Last Price Increase: 2024-08-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MonilBhavsar</details>

**Comment by lanitochka17** [comment] 2024-07-30 19:02
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mallenexpensify** [comment] 2024-07-31 22:27
Able to repro, def seems like something we want to fix.  You have to click the FAB then another button quickly so it's def an edge case

@eVoloshchak , comment if you *don't* think this can be external.  Thx


https://github.com/user-attachments/assets/82dc6975-91fd-401d-8c11-af8636eba89c

**Comment by ravindra-encoresky** [comment] 2024-08-01 06:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On onboarding if we click FAB button and select an option before welcome video, app freezes.
### What is the root cause of that problem?
Welcome video modal not really dismissing due to change in routes before it show. Because we are using ```Navigation.goBack()``` to dismiss it.
### What changes do you think we should make in order to solve the problem?

On closeModal function of FeatureTrainingModal we are just using ```Navigation.goBack()```. This works fine if there is no change in navigation before modal shows 
https://github.com/Expensify/App/blob/d69b203c298a879e609ebff4be249f550456f98e/src/components/FeatureTrainingModal.tsx#L168

but if there is change in navigation before FeatureTrainingModal show Navigation.goBack() not really dismiss the modal.
we need to dismiss modal using ```dismissModal``` global function.
```tsx
 const closeModal = useCallback(() => {
        if (!willShowAgain) {
            User.dismissTrackTrainingModal();
        }
        setIsModalVisible(false);
        Navigation.goBack();
        Navigation.dismissModal(); // we need to add this
    }, [willShowAgain]);
```

Also need to add navigator in global dismiss modal function
dismissModal.ts
```tsx
case NAVIGATORS.WELCOME_VIDEO_MODAL_NAVIGATOR:
```

### What alternative solutions did you explore? (Optional)
Suggestion - 2 seconds delay in showing welcome video modal causing others issues as well. If it is not very very necessary we can consider removing it

**Comment by ravindra-encoresky** [comment] 2024-08-02 07:11
@eVoloshchak please have a look at the above proposal. thanks.

**Comment by ravindra-encoresky** [comment] 2024-08-07 11:12
hi @eVoloshchak @mallenexpensify please have a look at the above proposal.

**Comment by eVoloshchak** [comment] 2024-08-07 15:44
@ravindra-encoresky's [proposal](https://github.com/Expensify/App/issues/46531#issuecomment-2262181033) looks good to me!

🎀👀🎀 C+ reviewed!

> 2 seconds delay in showing welcome video modal causing others issues as well. If it is not very very necessary we can consider removing it

Could you please elaborate on what other issues it is causing?

**Comment by ravindra-encoresky** [comment] 2024-08-08 04:13
> Could you please elaborate on what other issues it is causing?

if we navigate to profile tab before welcome video modal appear, we got this issue https://github.com/Expensify/App/issues/46548
And current issue if we navigate to menu in fab button
There is possibility of other issues if navigate to other screens before welcome video modal appear.

**Comment by ravindra-encoresky** [comment] 2024-08-08 07:27
@MonilBhavsar please have a look at the above proposal.
thanks.

**Comment by trjExpensify** [comment] 2024-08-09 00:25
@anmurali @danielrvidal aren't we going to kill this welcome video in favour of videos in setup tasks? Trying to assess whether this is worth fixing.

**Comment by ravindra-encoresky** [comment] 2024-08-09 06:50
@trjExpensify so what's for me in this now ?

**Comment by MonilBhavsar** [comment] 2024-08-12 16:03
Waiting on clarification https://github.com/Expensify/App/issues/46531#issuecomment-2276938077 if it's worth fixing

**Comment by danielrvidal** [comment] 2024-08-13 01:08
Asking for clarification here, I'll report back when I have a direction 

https://expensify.enterprise.slack.com/archives/C036QM0SLJK/p1723511235420929

**Comment by mallenexpensify** [comment] 2024-08-16 00:43
@danielrvidal what's the take away from[ the (long ass) thread discussion](https://expensify.slack.com/archives/C036QM0SLJK/p1723511235420929)?

**Comment by MonilBhavsar** [comment] 2024-08-16 10:41
Latest^

**Comment by MonilBhavsar** [comment] 2024-08-19 17:14
We're still discussing if we want to fix it cc @danielrvidal

**Comment by danielrvidal** [comment] 2024-08-19 19:18
I'm not sure, I think we're still planning to remove it but I asked in that thread.

**Comment by MonilBhavsar** [comment] 2024-08-23 16:58
> Yea, I think we’d remove it and see then measure if more people are then engaging with the onboarding tasks.

https://expensify.slack.com/archives/C036QM0SLJK/p1724187631995739?thread_ts=1723511235.420929&cid=C036QM0SLJK

It does seem like we are removing the video and testing. So we can close it for now. cc @danielrvidal @mallenexpensify

**Closed** 2024-08-23 16:58 UTC
Labels: External, Daily, Help Wanted, Bug
