### ISSUE TITLE
[$500] iOS - Navigation - "Hmm it's not here" error message when navigating to a specific deep link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32766] opened 2023-12-08 23:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Open "staging.new.expensify.com/concierge" fron iCloud notes
Log in with a new account

## Expected Result:
Concierge chat should load

## Actual Result:
"Hmm it's not here" error message is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6ec58597-2e19-484b-bbac-6afce133ba4a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc6576993bdb8669</li>
        <li>Upwork Job ID: 1733270999629123584</li>
        <li>Last Price Increase: 2023-12-29</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-12-13 05:50
@lanitochka17 are you able to reproduce?

**Comment by lanitochka17** [comment] 2023-12-13 22:19
Issue reproducible on latest build 1.4.12-0

https://github.com/Expensify/App/assets/78819774/631b4f53-66ae-4caa-a210-4f6490895994

**Comment by mollfpr** [comment] 2023-12-18 17:06
I can't reproduce the issue in dev.

**Comment by mollfpr** [comment] 2023-12-23 12:14
I still can't reproduce it with `URI-scheme`; I'll see if there's another way to duplicate the step in dev.

**Comment by JmillsExpensify** [comment] 2023-12-27 23:40
Still trying to reproduce.

**Comment by JmillsExpensify** [comment] 2024-01-03 04:23
Closing. Please re-open if anyone can reproduce.

**Closed by JmillsExpensify** 2024-01-03 04:23 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
