### ISSUE TITLE
[HOLD for payment 2023-07-14] Web -  First cell of magic input field is not focused on clicking 'Didn't receive a magic code' link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22258] opened 2023-07-05 11:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Navigate to staging sign-in page
2. Enter email > click on continue
3. Wait for the 30 second time out to finish
4. Enter wrong magic code
5. Click on 'Didn't receive a magic code' link

## Expected Result:
The first cell of the magic code input field should be focused

## Actual Result:
The first cell of the magic code input field is not focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e9bb9e61-b1fe-4462-a8ad-247c4cb85ab2

https://github.com/Expensify/App/assets/93399543/1689d50f-ffb9-443d-8e61-bebfc51e6609

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688554945270799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment] 2023-07-05 11:37
Looking to see if this is related to https://github.com/Expensify/App/pull/21724

**Comment by MariaHCD** [comment] 2023-07-05 11:46
> After a failed validation, we decided to blur the input

In this case, there was no failed validation. The user just requested for a new code.

> Because if you type one single number it'll auto-submit because you have 6 digits in the input

Oh, interesting. Why does it auto-submit when only a single digit has been entered?

**Comment by MariaHCD** [comment] 2023-07-05 11:54
> 1. Get an error by submitting wrong code

Even if you don't submit a code at all and then click resend code, the input is blurred.

**Comment by MariaHCD** [comment] 2023-07-05 11:55
@HezekielT All good, please create the PR. Thanks! The fix looks you outlined [here](https://github.com/Expensify/App/issues/22258#issuecomment-1621601631) looks like it will fix this!

**Comment by Julesssss** [comment] 2023-07-05 16:18
Cp'd! Removing the blocker label.

**Comment by Julesssss** [comment] 2023-07-05 16:38
We have already validated the AdHoc build, but here are some screenshots from the staging build: 

<img width="852" alt="Screenshot 2023-07-05 at 17 38 29" src="https://github.com/Expensify/App/assets/10736861/afb70022-2192-47ee-b769-6c43b996804c">

![Screenshot_20230705-150109 (1)](https://github.com/Expensify/App/assets/10736861/6a748e52-fb0c-48dd-8798-93e9564a8dd0)

**Comment by Julesssss** [comment] 2023-07-05 16:39
We have already validated the AdHoc build, but here are some screenshots from the staging build: 

<img width="852" alt="Screenshot 2023-07-05 at 17 38 29" src="https://github.com/Expensify/App/assets/10736861/afb70022-2192-47ee-b769-6c43b996804c">

![Screenshot_20230705-150109 (1)](https://github.com/Expensify/App/assets/10736861/4c08bd89-a5f1-4181-b073-0ea0c964c6bb)

**Comment by MariaHCD** [comment] 2023-07-06 06:51
This was a regression from https://github.com/Expensify/App/pull/21724

No payments required here. I think we are good to close this out.

**Comment by Natnael-Guchima** [comment] 2023-07-06 06:54
Hello @MariaHCD, I have reported this issue.

**Comment by MariaHCD** [comment] 2023-07-06 07:03
@zanyrenney this deploy blocker was a regression and was already fixed [here](https://github.com/Expensify/App/pull/22265). We just need to pay out the reporting bonus to @Natnael-Guchima.

**Comment by Natnael-Guchima** [comment] 2023-07-06 07:05
No problem. Thanks @MariaHCD

**Comment by MariaHCD** [comment] 2023-07-07 11:33
Let's update the existing regression test [here](https://expensify.testrail.io/index.php?/cases/view/1970996). Specifically, I've just added steps 12 & 13

```
Online

1. Navigate to https://staging.new.expensify.com/
2. In the email field, enter a gmail email address for a new account
3. Press continue
4. Verify there's a welcome message - "It's always great to see a new face..."
5. Verify there’s a message saying that a Magic Code has been sent to the email address
6. Verify there’s a button to resend the Magic Code
7. Navigate to the email inbox of the account and open the validation email
8. Copy the code
9. Enter a incorrect the code in the magic code field
10. Verify there's a user friendly message that the code is incorrect or to request a new code
11. Verify the field turns red and the user is unable to proceed
12. Wait for `Request magic code in xx:xx` timer to finish and click on `Didn't receive magic code?` option.
13. Verify that the error is cleared, the field is no longer red and the first input of the magic code input is focused
```

**Comment by MariaHCD** [comment] 2023-07-10 05:51
Nice catch, @HezekielT! Updated.

**Comment by zanyrenney** [comment] 2023-07-14 09:46
Added the issue for the regression test.

**Comment by zanyrenney** [comment] 2023-07-17 14:32
https://github.com/Expensify/App/issues/22258#issuecomment-1623102933 as per this comment, creating an upwork job specifically for reporting bonus.

**Comment by zanyrenney** [comment] 2023-07-17 14:37
Invited you: https://www.upwork.com/jobs/~011861274c564ee819 @Natnael-Guchima

**Comment by Natnael-Guchima** [comment] 2023-07-17 15:43
> Invited you: https://www.upwork.com/jobs/~011861274c564ee819 @Natnael-Guchima 

I have applied to the job. Thanks @zereraz

**Comment by zanyrenney** [comment] 2023-07-18 13:23
That is all paid!

**Closed by zanyrenney** 2023-07-18 13:23 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
