### ISSUE TITLE
[HOLD for payment 2022-11-29] [Hold for payment 2022-11-21] [$250] Mac / Safari : After selecting a text via mouse and then using`CMD+C` to copy it does not work reported by @parasharrajat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12554] opened 2022-11-08 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. Select a part of any message
3. Use shortcuts to copy the text.
4. Try pasting the text in the composer.

## Expected Result: 
the selected text should be copied and pasted in the composer.

## Actual Result :

1. Select part of the old message, right click my mouse, our context menu shows rather than the browser's menu, click Copy to Clipboard, and paste into input area, the whole message been pasted, not the selection text.
2. Select part of the old message, press Cmd+C to copy selection, and press Cmd+V or the browser's menu to paste into input area, nothing been pasted.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200601134-a32f9e93-98ad-417a-b15e-36b7c68fc13b.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat 
**Slack conversation:** 
https://expensify.slack.com/archives/C01GTK53T8Q/p1667834088430199
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yevheniitsuryk** [comment] 2022-11-08 20:53
### Proposal

The actual problem is in these lines of code:

https://github.com/Expensify/App/blob/ea35c4622fcc93cad07871907e216b7f50b50105/src/pages/home/report/ReportActionItem.js#L171-L174

This fix was made according to this PR https://github.com/Expensify/App/pull/8443 for this issue https://github.com/Expensify/App/issues/7853

It's unfocusing the whole message including selected text, when you press any button.

So, I propose to add next condition/exception for shortcuts meta keys (CMD + Ctrl):
```
onKeyDown={(event) => {
    if (event.metaKey) { return; }
    event.target.blur();
}}
```
It's perfectly working in Safari, and other platforms. The previous issue is also fixed.


https://user-images.githubusercontent.com/64137632/200672446-16fa1c55-ed30-4d37-8118-35497d943748.mp4

**Comment by parasharrajat** [comment] 2022-11-08 23:27
Good find @yevheniitsuryk. 

https://github.com/Expensify/App/blob/ea35c4622fcc93cad07871907e216b7f50b50105/src/pages/home/report/ReportActionItem.js#L171-L174 looks very problematic to me. It could have many unknown side-effects. This issue is just one of them.  

Based on the real issue, looks like we want to disable the blue border on `Shift+click` or say it `Shift` only. So What about we restrict this keyDown handler to these combinations? It is important that this blue border is shown when the user uses `Shift+Tab or `Tab` for navigation.

**Comment by yevheniitsuryk** [comment] 2022-11-09 10:50
@parasharrajat actually if we remove fix with .blur(), it triggers focus on every keyPress (not only Shift key). Check it on video, on Safari all symbol keys, on Chrome literally every key (except functional keys like Ctrl/cmd alt/option):

https://user-images.githubusercontent.com/64137632/200776213-69768fca-c4a5-4b61-a4d7-6a14868f5a7a.mp4


https://user-images.githubusercontent.com/64137632/200806509-d1890727-3fc9-4f04-9f7b-dd45508d47a8.mp4

So the problem turned out to be more serious than it seemed at first)

I tried to research this strange behavior with focusing on every key press, but no results for now.

Also tried to fix behavior by adding more conditions (exception) on shift and tab keys, but problem is that you can't catch shift + tab shortcut - firstly you catch Shift button press, after you are catching Tab (with pressed shift). 

```
                onKeyDown={(event) => {
                    console.log('event', event)

                    if (event.metaKey || (event.shiftKey && event.keyCode === 9) || event.keyCode === 9) { return; }

                    event.target.blur();
                }}
```

And if we catch Shift - we make blur() for event.target element and after that we have different behaviors in browsers (Safari loses previous focusable element and then start focusing on first element on page, and Chrome loses focus on current element, but after that still able to catch previous and next focusable elements), you may check next videos:


https://user-images.githubusercontent.com/64137632/200809826-b9c3a3dd-3c3e-4039-bac4-29a1aab4f47d.mp4


https://user-images.githubusercontent.com/64137632/200810341-5d0107fa-a754-44da-9d4d-720fb5bc7eb4.mp4

I think in this case we should solve the root of the issue - disable focusing on elements on every key press

**Comment by parasharrajat** [comment] 2022-11-09 11:42
Thanks for digging into this.  

> I think in this case we should solve the root of the issue - disable focusing on elements on every key press.

Does this [proposal](https://github.com/Expensify/App/issues/12554#issuecomment-1307812617) still work? And you are prefering fix the above root cause instead of this. 


Question: 
1. So we are blurring on each key press. Does it have any issues with it?

**Comment by yevheniitsuryk** [comment] 2022-11-09 12:20
@parasharrajat yes, this [proposal](https://github.com/Expensify/App/issues/12554#issuecomment-1307812617) works okay, it's fixing problem with text selection on messages. Answering your question - no issues with blurring on each keypress. I made modification according to your comment - now it will blur on single Shift key press, navigation on Tab and Shift+Tab works, and there is final code:

```
  onKeyDown={(event) => {
     if (event.metaKey || (event.shiftKey && event.keyCode === 9) || event.keyCode === 9) { return; }
     event.target.blur();
   }}
```
(Tested on Safari)

![CleanShot 2022-11-09 at 14 15 31](https://user-images.githubusercontent.com/64137632/200828154-341eb997-f8e2-4729-bb7e-4f5e8d3bd6dd.gif)

**Comment by parasharrajat** [comment] 2022-11-09 12:37
Ok, so you are saying that your proposal is working and has no inconsistencies across browsers. And changing the conditon has different effects on different browsers. 

I will test your solution and I think it also needs a general discussion as I don't think blurring on the key press is a good idea. May be we can seek a better solution as part of this issue.

**Comment by WestDon** [comment] 2022-11-09 16:02
**Proposal**

Instead of a blur that breaks copy, we can just add, or remove the style. Method onKeyUp needs to restore default Tab focus highlight behaviour.

```
                onKeyDown={(event) => {
                    const target = event.target;

                    // Hide blue formatting if Div and not s Tab
                    if (target.nodeName === 'DIV' && event.code !== 'Tab') {
                        target.style.outline = 'none';
                        target.style.boxShadow = 'none';
                    }
                }}
                onKeyUp={(event) => {
                    const target = event.target;

                    // Restore blue formatting if any combination with Tab
                    if (target.nodeName === 'DIV' && event.code === 'Tab') {
                        target.style.outline = null;
                        target.style.boxShadow = null;
                    }
                }}
```

**Comment by henriquefalconer** [comment] 2022-11-09 17:42
### Proposal

The `Pressable` component inside [src/components/PressableWithSecondaryInteraction/index.js](https://github.com/Expensify/App/blob/f654cc13794aa749a29b6561bad94d80a9580fd4/src/components/PressableWithSecondaryInteraction/index.js), when processed by `react-native-web`, is rendered as a `div` with the default HTML attribute `tabindex="0"`.
```html
<div tabindex="0" class="css-view-175oi2r r-cursor-1loqt21 r-touchAction-1otgn73" style="touch-action: auto; -webkit-user-select: none; -webkit-user-drag: none;">
```

The `tabindex` attribute makes the `div` focus when the user presses a key, which seems to be the root cause of the problem noted in this issue and the one in issue [#7853](https://github.com/Expensify/App/issues/7853).

So I propose to add in `componentDidMount()` inside `PressableWithSecondaryInteraction` the following code, which sets the native prop `tabindex` of the `Pressable` component to `undefined`, removing `tabindex` from the page:

```javascript
this.pressableRef.setNativeProps({
    tabIndex: undefined,
});
```

#### IMPORTANT: This solution is not aligned with your migration to Fabric. Read "P.S" for more details.

The entire `componentDidMount()` would look like this:

```javascript
    componentDidMount() {
        // Prevent unwanted focusing of element (Pressable auto implements tabindex="0")
        this.pressableRef.setNativeProps({
            tabIndex: undefined,
        });
        if (this.props.forwardedRef && _.isFunction(this.props.forwardedRef)) {
            this.props.forwardedRef(this.pressableRef);
        }
        this.pressableRef.addEventListener('contextmenu', this.executeSecondaryInteractionOnContextMenu);
    }
```

Also, this would mean that this portion of the code would be eliminated:

https://github.com/Expensify/App/blob/ea35c4622fcc93cad07871907e216b7f50b50105/src/pages/home/report/ReportActionItem.js#L171-L174

Leaving the `PressableWIthSecondaryInteraction` free of the code that seemed problematic, and without creating unnecessary side-effects.

It's perfectly working in Safari, and other platforms. The previous issue is also fixed.

https://user-images.githubusercontent.com/58156196/200882107-fc4d370f-7714-433c-bb4d-eabba18090fb.mov

P.S.: I know you are migrating to Fabric. `setNativeProps` is not allowed with it. I'm looking for alternate solutions right now, but I imagine the easiest would include altering the file [src/modules/createDOMProps/index.js](https://github.com/Expensify/react-native-web/blob/master/packages/react-native-web/src/modules/createDOMProps/index.js) on your forked [@expensify/react-native-web](https://github.com/Expensify/react-native-web) lib and adding a new option to the existing `focusable` prop values, allowing for `tabindex` to not be included (`focusable` controls `tabindex`). [Here's how `focusable` works nowadays](https://necolas.github.io/react-native-web/docs/accessibility/#keyboard-focus). None of the existing `focusable` values currently removes `tabindex`.

**Comment by parasharrajat** [comment] 2022-11-09 17:54
Both are interesting solutions. Resetting the style is a good idea but very hacky. 

@henriquefalconer Correct, we are migrating to the fabric so we can't use `setNativeProps`. I also think we should not deep into workarounds for this issue. If you think that we should add a new feature to RN-web. I would say your propose that on the RN-web and let's see what the maintainer has to say. 

I will prefer the best simple solution for this task.

**Comment by henriquefalconer** [comment] 2022-11-09 23:28
### Updated proposal

As requested, here's an alternate and simpler solution for this task.

I propose changing the `Pressable` component inside [src/components/PressableWithSecondaryInteraction/index.js](https://github.com/Expensify/App/blob/f654cc13794aa749a29b6561bad94d80a9580fd4/src/components/PressableWithSecondaryInteraction/index.js) into a `TouchableWithoutFeeback` component. It has all `Pressable` props needed and doesn't generate a `tabindex` attribute.

Here's what it looks like currently:

https://github.com/Expensify/App/blob/ed864876a097a9cfd382330ac99d3c2b1b88dae1/src/components/PressableWithSecondaryInteraction/index.js#L67-L81

And here's what it will look after my alterations:

```jsx
        return (
            <LongPressGestureHandler onHandlerStateChange={this.callSecondaryInteractionWithMappedEvent}>
                <TouchableWithoutFeedback
                    onPressIn={this.props.onPressIn}
                    onPressOut={this.props.onPressOut}
                    onPress={this.props.onPress}
                    // eslint-disable-next-line react/jsx-props-no-spreading
                    {...defaultPressableProps}
                >
                    <>
                        <View style={this.props.inline && styles.dInline} ref={el => this.pressableRef = el}>
                            {this.props.children}
                        </View>
                    </>
                </TouchableWithoutFeedback>
            </LongPressGestureHandler>
        );
```

In order for this to work, I inserted `this.props.children` inside a fragment and a `View`, as `TouchableWithoutFeeback` only accepts one child (and for some reason removing the fragment made the blue border appear again), and also altered the location of the `ref` prop, as `TouchableWithoutFeeback` won't accept `ref` as a functional prop.

The outcome does not produce any unwanted effects, and retains all current funcionality:

- `onPressIn` prop used on [src/pages/home/report/ReportActionItem.js](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.js) and [src/pages/settings/AppDownloadLinks.js](https://github.com/Expensify/App/blob/main/src/pages/settings/AppDownloadLinks.js) behaves the same way
- `onPressOut` prop used on [src/pages/home/report/ReportActionItem.js](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.js) and [src/pages/settings/AppDownloadLinks.js](https://github.com/Expensify/App/blob/main/src/pages/settings/AppDownloadLinks.js) behaves the same way
- `inline` style prop used on [src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js](https://github.com/Expensify/App/blob/main/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js) behaves the same way
- `preventDefaultContentMenu` prop used on [src/pages/home/report/ReportActionItem.js](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.js) behaves the same way

P.S.: Applying this would also mean that this portion of the code could be eliminated:

https://github.com/Expensify/App/blob/ea35c4622fcc93cad07871907e216b7f50b50105/src/pages/home/report/ReportActionItem.js#L171-L174

It's perfectly working in Safari, and other platforms. The previous issue is also fixed.

https://user-images.githubusercontent.com/58156196/200962352-84425af2-16a8-4611-b46c-d80acc73bb4f.mov

**Comment by parasharrajat** [comment] 2022-11-10 00:14
Awesome @henriquefalconer that looks more reasonable to do. I will test it just to be sure first. https://github.com/Expensify/App/blob/f654cc13794aa749a29b6561bad94d80a9580fd4/src/components/PressableWithSecondaryInteraction/index.js is deeply involved in many things.

**Comment by parasharrajat** [comment] 2022-11-10 17:17
Ok, I tested it. It seems to work great . 

@henriquefalconer's [proposal](https://github.com/Expensify/App/issues/12554#issuecomment-1309534644) looks good.

cc: @puneetlath 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by s77rt** [comment] 2022-11-11 18:54
Won't the @henriquefalconer proposal's remove the tabbing functionality? We can't tab thought messages?

**Comment by parasharrajat** [comment] 2022-11-11 18:55
I think checked that. let me do that again.

**Comment by s77rt** [comment] 2022-11-11 19:15
@parasharrajat 
Can you upload a video?
I can't tab from my side

**Comment by s77rt** [comment] 2022-11-11 20:00
https://user-images.githubusercontent.com/16493223/201422554-0865b0e8-7831-42ca-b6ff-fbe69479b868.mp4

**Comment by parasharrajat** [comment] 2022-11-11 20:22
is it Safari?

**Comment by s77rt** [comment] 2022-11-11 20:40
Yes, version 16. Other browsers are effected too and this is expected since we removed the tabindex attr in the proposed solution.
Can you retest on your side?

**Comment by parasharrajat** [comment] 2022-11-11 21:22
Ok. Thanks. May be I had cache. You are correct it breaks the highlight on tab. Retracting my decision.

**Comment by parasharrajat** [comment] 2022-11-11 21:25
As a last resort, I will revert https://github.com/Expensify/App/pull/8443 as it caused a bigger issue for disabling a minor UI effect.

**Comment by s77rt** [comment] 2022-11-11 21:33
@parasharrajat Mind checking [my proposal](https://github.com/Expensify/App/issues/12010#issuecomment-1312059021)
The issue #7853 affects every key not just SHIFT which is a bit annoying

**Comment by henriquefalconer** [comment] 2022-11-11 22:50
@parasharrajat I would argue that my fix (removing `tabindex` from [src/components/PressableWithSecondaryInteraction/index.js](https://github.com/Expensify/App/blob/f654cc13794aa749a29b6561bad94d80a9580fd4/src/components/PressableWithSecondaryInteraction/index.js)) is still valid.

When considering that [src/components/PressableWithSecondaryInteraction/index.js](https://github.com/Expensify/App/blob/f654cc13794aa749a29b6561bad94d80a9580fd4/src/components/PressableWithSecondaryInteraction/index.js) is used only in instances we want to override secondary action (like on `ReportActionItem`, `BaseAnchorForCommentsOnly` and `AppDownloadLinks`), there's no need to allow highlight on tabbing, specifically on the container.

From an accessibility perspective, elements on the page that don't respond to left-click action (such as the case with the container of these messages) have usually the same behavior as any other static element on a page, and are not highlighted by default. 

What is highlighted, instead, are for exemple the user's profile and interaction buttons inside the message, that produce action when the user presses `Enter` after tabbing (this is what happens with my proposal currently).

@s77rt's proposal not only allows for the message container to be highlighted, but also makes the user select something that doesn't produce an action when `Enter` is pressed.

IMHO the message container by itself should not be considered a highlightable element, and from my perspective my proposal stills stands as the reasonable fix for this issue, as well as for issue [#7853](https://github.com/Expensify/App/issues/7853)

**Comment by parasharrajat** [comment] 2022-11-11 23:13
It is a valid point. I will have to discuss this.

**Comment by parasharrajat** [comment] 2022-11-14 18:56
I gave a thought to https://github.com/Expensify/App/issues/12554#issuecomment-1312248080 and I disagree with the suggestion of removing the focus target from the message item. 

There is a very specific reason for it. 
1. User can tab over the message and use Keyboard to open the context menu. This can also be done if you focus on the name or avatar of the message but not all messages have avatars and names. 

Due to this, messages such as the second block in the image below will be ignored which does not look good to me. 
![Screenshot 2022-11-15 00:26:16](https://user-images.githubusercontent.com/24370807/201742854-c74c0b54-596b-45cc-8c35-6ca1d40fe3bf.png)

**Comment by parasharrajat** [comment] 2022-11-14 19:04
I am going to revert the Regression PR https://github.com/Expensify/App/pull/8443 which is causing a trail of regressions.

cc: @puneetlath 

What do you think?

**Comment by s77rt** [comment] 2022-11-14 19:08
@parasharrajat 
I still think my proposal is better than the revert, any reasons why you think we should revert instead?

Also i think we should close this issue and track only on #12010

**Comment by parasharrajat** [comment] 2022-11-14 19:13
I think all of these issues originated from that PR and closing it gets rids of them so it is better. 

If you think we should solve https://github.com/Expensify/App/issues/7853, you can open a new discussion on slack to reopen that. 

Thanks.

**Comment by s77rt** [comment] 2022-11-14 19:19
@parasharrajat Understood. I was for the revert at first but then I found that the issue effect every key not only SHIFT.
Click on any chat, press any key, the border appears, it's a little annoying. If you think it's still acceptable then I'm okay with the revert.

**Comment by parasharrajat** [comment] 2022-11-14 19:21
Yup, I discussed that already. We are good to keep that for now. But as I said, if you have a better solution in mind, you can raise the same on slack and tag the previous issue.

**Comment by puneetlath** [comment] 2022-11-14 21:12
@parasharrajat I agree let's revert that. I think tha

**Comment by henriquefalconer** [comment] 2022-11-14 22:21
Alright @parasharrajat! Thanks for considering my proposal 😉

**Comment by parasharrajat** [comment] 2022-11-14 22:25
Unfortunately, there is no clean solution available for this. I was happy to do https://github.com/Expensify/App/issues/12554#issuecomment-1309534644 but it still has one issue so reverting is a good call. 

Looking forward to your contributions on other issues.

**Comment by parasharrajat** [comment] 2022-11-15 21:27
> The PR that introduced the bug has been identified. Link to the PR:

#8443

**Comment by puneetlath** [comment] 2022-11-21 14:50
@parasharrajat @rushatgabhane sent you hiring offers in Upwork.

**Comment by puneetlath** [comment] 2022-11-22 23:31
@rushatgabhane quick bump on accepting the hiring offer. Then we'll be able to close this out. Thanks!

**Comment by puneetlath** [comment] 2022-11-28 16:03
All paid!

**Closed by puneetlath** 2022-11-28 16:03 UTC
Labels: External, Weekly, Awaiting Payment, Bug
