### ISSUE TITLE
[$1000] Copy button does not work while requesting money in newly registered Users with console error

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22387] opened 2023-07-06 23:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Note: Please create a new account. Copy functionality works well with old accounts. This issue is currently seen in new accounts only.
1. Create a new account (Very important.)
2. Go to + > chat > enter email of any old account > initiate chat
3. Send a message
4. Copy the message using the copy button. Verify that it works.
5. Initiate Request money. You will receive [{Username} owes you {dollar}amount] message
6. Copy the “[{Username} owes you {dollar}amount]” message using the copy button. Verify if it works by pasting it.
7. Right click on the “[{Username} owes you {dollar}amount]” message and click on copy to clipboard.
8. Paste it. Verify if it works
9. Open console and verify if you can see console error.
## Expected Result: 
Copy was successful
## Actual Result: 
Copy was not successful. Console error

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cf06d194-30f3-41b1-8c29-e795677036eb

https://github.com/Expensify/App/assets/43996225/d55a6620-b4c0-4209-ba06-89d64c291d34

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688598829319479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c4de90299f3adb9</li>
        <li>Upwork Job ID: 1677488450554494976</li>
        <li>Last Price Increase: 2023-07-29</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-07 08:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy button does not work while requesting money in newly registered users with console error.

### What is the root cause of that problem?
When display `REPORTPREVIEW`, the message is retrieved using `ReportUtils.getReportPreviewMessage`.
https://github.com/Expensify/App/blob/5723571398adc89c53e17e9dfca387493d3ae631/src/components/ReportActionItem/ReportPreview.js#L100

When copy to clipboard, just copy the report action's last html message.
https://github.com/Expensify/App/blob/5723571398adc89c53e17e9dfca387493d3ae631/src/pages/home/report/ContextMenu/ContextMenuActions.js#L175-L176

If reqeust money with newly registered user, the report action contains empty html message.
So copy to clipboard does not work.
But if request money with old accounts, the report action contains correct html message, so copy to clipboard works well.

### What changes do you think we should make in order to solve the problem?
We can generate correct message in [copy to clipboard handler](https://github.com/Expensify/App/blob/5723571398adc89c53e17e9dfca387493d3ae631/src/pages/home/report/ContextMenu/ContextMenuActions.js#L174-L195) just like in chat report.
```js
    onPress: (closePopover, {reportAction, selection}) => {
        const message = _.last(lodashGet(reportAction, 'message', [{}]));
-       const messageHtml = lodashGet(message, 'html', '');

+       let messageHtml = '';
+       if (reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.REPORTPREVIEW) {
+           const iouReport = ReportUtils.getReport(ReportActionUtils.getIOUReportIDFromReportActionPreview(reportAction));
+           messageHtml = ReportUtils.getReportPreviewMessage(iouReport, reportAction);
+       } else {
+           messageHtml = lodashGet(message, 'html', '');
+       }
        ...
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by greg-schroeder** [comment] 2023-07-08 01:23
There are several issues related to the copy functionality behaving inconsistently but I don't see any that match this exact report

**Comment by greg-schroeder** [comment] 2023-07-10 19:01
Looks like we have one proposal here https://github.com/Expensify/App/issues/22387#issuecomment-1625068379 @0xmiroslav

**Comment by greg-schroeder** [comment] 2023-07-12 20:32
Pending proposal review by C+

**Comment by greg-schroeder** [comment] 2023-07-15 16:55
Bump @0xmiroslav

**Comment by greg-schroeder** [comment] 2023-07-17 20:46
Friendly bump

**Comment by mvtglobally** [comment] 2023-07-20 02:54
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment] 2023-07-21 09:51
Hmm. Okay. I'm not really sure to do with this one 🤔 In your comment [here](https://github.com/Expensify/App/issues/22387#issuecomment-1640442016) @0xmiroslav are you saying we shouldn't fix this here or that the issue isn't focused on the right thing?

**Comment by greg-schroeder** [comment] 2023-07-24 16:56
Got it. Yes, I think you're right it makes sense to fix here

**Comment by greg-schroeder** [comment] 2023-07-26 21:17
Okay so are any of the proposals here worth going with?

**Comment by greg-schroeder** [comment] 2023-07-31 14:14
Hey @0xmiroslav sorry, what should we do this? Do we need more proposals? Should I double the bounty you think?

**Comment by mvtglobally** [comment] 2023-08-02 16:45
Issue not reproducible during KI retests. (Second week)

**Comment by greg-schroeder** [comment] 2023-08-02 17:34
Hmm. Was this maybe fixed somewhere else?

**Comment by greg-schroeder** [comment] 2023-08-07 15:07
Hmm - I can't reproduce this one anymore.

**Comment by greg-schroeder** [comment] 2023-08-09 23:12
I posted in the open source room for more 👀 as I don't know the best approach

**Comment by greg-schroeder** [comment] 2023-08-14 08:57
Still waiting for folks to weigh in, bumped thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1691622733067609

**Comment by pecanoro** [comment] 2023-08-15 12:20
I can't reproduce this one either so I am going to close it unless we get better reproduction steps from the reporter.

**Closed by pecanoro** 2023-08-15 12:20 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by pecanoro** [comment] 2023-08-15 12:23
@0xmiroslav Yeah, I checked and while I can reproduce the other one, I can't reproduce this one at all, this one gets copied fine.

**Comment by pecanoro** [comment] 2023-08-15 12:24
@0xmiroslav Can you still reproduce this issue with the original steps?

**Comment by pecanoro** [comment] 2023-08-15 12:51
Ahh I see, then yes, after checking the content of the message, I think we can add it as well. I will add it to the other issue!
