### ISSUE TITLE
[$1000] Web - Task Detail screen is empty

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23296] opened 2023-07-20 18:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any announce
2. Assign a new task
3. Fill in Title and click Next
4. Click Confirm task button to create a new task
5. Click on the header to open Detail Screen
6. Notice that the Detail screen is empty

## Expected Result:
Detail screen is not empty

## Actual Result:
Detail screen is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/402fa0c9-3fa2-4da9-bc72-c3efa1672a55

https://github.com/Expensify/App/assets/93399543/8153de45-7430-43ec-b47b-3c13a5c6c7f8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689829433314039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f23789ed29030efc</li>
        <li>Upwork Job ID: 1682226624340627456</li>
        <li>Last Price Increase: 2023-08-09</li>
    </ul>
</details>

**Comment by proshir** [comment] 2023-07-20 20:13
Yeah. I could reproduce this problem too.
So I gonna work on this issue .

**Comment by proshir** [comment] 2023-07-20 21:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When following the steps to create a new task, the user fills in the required information such as the Title and clicks on the "Next" button. Upon reaching the "Confirm Task" page and clicking the "Confirm Task" button, a new task should be created and the Detail Screen should be populated with the task details. However, the Detail Screen remains empty, displaying no information about the newly created task.

### What is the root cause of that problem?
navigateToDetailsPage ( in ReportUtils.js ) doesn't have any option for task detail page unlike other things like ChatRoom and ChatThread.

### What changes do you think we should make in order to solve the problem?
So we should add this option for this function for task detail and also add the necesary details:
```
function navigateToDetailsPage(report) {
    const participantAccountIDs = lodashGet(report, 'participantAccountIDs', []);
    if (isChatRoom(report) || isPolicyExpenseChat(report) || isChatThread(report)) {
        Navigation.navigate(ROUTES.getReportDetailsRoute(report.reportID));
        return;
    }
    if (participantAccountIDs.length === 1) {
        Navigation.navigate(ROUTES.getProfileRoute(participantAccountIDs[0]));
        return;
    }
    Navigation.navigate(ROUTES.getReportParticipantsRoute(report.reportID));
}
```

**Comment by proshir** [comment] 2023-07-20 21:12
Excuse me, how do you think I can find a job that no one has chosen? I have done several jobs here, but they all turned out like this. Those who are "help wanted" are also filled quickly.

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 21:26
Thanks, @Nodebrute, and @jasper We caught this while [reviewing](https://github.com/Expensify/App/pull/22586#issuecomment-1636122174)  as well. I was told [here](https://github.com/Expensify/App/pull/22586#issuecomment-1636142186) will be handled in another issue.

**Comment by proshir** [comment] 2023-07-20 21:29
So now this issue will be investigated to solve the problem that I gave a solution for?

**Comment by lanitochka17** [comment] 2023-08-09 15:38
Issue reproducible. Build 1.3.52.1

https://github.com/Expensify/App/assets/78819774/7347cc42-5e45-4b21-b9c2-9b60a457301c

**Comment by s77rt** [comment] 2023-08-09 16:59
@lanitochka17 We will handle this in https://github.com/Expensify/App/issues/24144

**Closed** 2023-08-15 19:48 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Bug
