### ISSUE TITLE
[$250] [Bug] Details - Time is not updated in the details page if it's left open reported by @jayeshmangwani

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12651] opened 2022-11-10 20:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with user A
2. navigate to any chat with user B
3. Press on user B profile icon
4. Check the Local time for user B
5. Wait for an minute keeping the details page open
6. Check the time for the user at Composer and Details page

## Expected Result: 
Time should be same at both the places

## Actual Result: 
Details page Local time is not updating

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.26-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1672" alt="Screenshot 2022-11-10 at 9 39 01 PM" src="https://user-images.githubusercontent.com/43996225/201199061-df363ded-b813-49fb-9176-11371e7f0346.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1668097040973149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/201199078-9eb01c17-0d71-46b9-ae01-8c84f5d93c57.mp4

**Comment by hungvu193** [comment] 2022-11-11 03:16
<b>Proposal</b>
In our current `DetailPage.js`, we only calculated the time inside render function, that's why the time's only updated when the component is rendered and rerendered.
<b>Solution</b>
We have 2 solutions here, force component to re-render every certain time or calculate the time again after certain time.
I will provide the code for the second solution:
```diff
From a6057eef6a02021fb8ad215238fc236baad4271b Mon Sep 17 00:00:00 2001
From: Hans <visaocuoitroi193@gmail.com>
Date: Fri, 11 Nov 2022 10:12:50 +0700
Subject: [PATCH] calculate time

---
 src/pages/DetailsPage.js | 43 +++++++++++++++++++++++++++++++++++++++-
 1 file changed, 42 insertions(+), 1 deletion(-)

diff --git a/src/pages/DetailsPage.js b/src/pages/DetailsPage.js
index 17ad4f971..69b02c7d1 100755
--- a/src/pages/DetailsPage.js
+++ b/src/pages/DetailsPage.js
@@ -24,6 +24,7 @@ import MenuItem from '../components/MenuItem';
 import AttachmentModal from '../components/AttachmentModal';
 import PressableWithoutFocus from '../components/PressableWithoutFocus';
 import * as Report from '../libs/actions/Report';
+import Timers from '../libs/Timers';
 
 const matchType = PropTypes.shape({
     params: PropTypes.shape({
@@ -71,7 +72,22 @@ const getPhoneNumber = (details) => {
 };
 
 class DetailsPage extends React.PureComponent {
+    constructor(props) {
+        super(props);
+        this.getParticipantLocalTime = this.getParticipantLocalTime.bind(this);
+        this.state = {
+            updatedTime: this.getParticipantLocalTime(),
+        };
+    }
+
     componentDidMount() {
+        this.timer = Timers.register(
+            setInterval(() => {
+                this.setState({
+                    updatedTime: this.getParticipantLocalTime(),
+                });
+            }, 1000),
+        );
         if (lodashGet(this.props.route.params, 'login')) {
             return;
         }
@@ -80,6 +96,29 @@ class DetailsPage extends React.PureComponent {
         Navigation.dismissModal();
     }
 
+    componentWillUnmount() {
+        clearInterval(this.timer);
+    }
+
+    getParticipantLocalTime() {
+        const details = lodashGet(
+            this.props.personalDetails,
+            lodashGet(this.props.route.params, 'login'),
+        );
+        const reportRecipientTimezone = details.timezone
+            ? details.timezone.selected
+            : CONST.DEFAULT_TIME_ZONE;
+        const reportTimezone = DateUtils.getLocalMomentFromTimestamp(this.props.preferredLocale, null, reportRecipientTimezone);
+        const currentTimezone = DateUtils.getLocalMomentFromTimestamp(this.props.preferredLocale);
+        const reportRecipientDay = reportTimezone.format('dddd');
+        const currentUserDay = currentTimezone.format('dddd');
+
+        if (reportRecipientDay !== currentUserDay) {
+            return `${reportTimezone.format('LT')} ${reportRecipientDay}`;
+        }
+        return `${reportTimezone.format('LT')}`;
+    }
+
     render() {
         let details = lodashGet(this.props.personalDetails, lodashGet(this.props.route.params, 'login'));
         if (!details) {
@@ -94,8 +133,10 @@ class DetailsPage extends React.PureComponent {
 
         // If we have a reportID param this means that we
         // arrived here via the ParticipantsPage and should be allowed to navigate back to it
+
         const shouldShowBackButton = Boolean(this.props.route.params.reportID);
         const timezone = details.timezone ? DateUtils.getLocalMomentFromTimestamp(this.props.preferredLocale, null, details.timezone.selected) : null;
+
         const GMTTime = timezone ? `${timezone.toString().split(/[+-]/)[0].slice(-3)} ${timezone.zoneAbbr()}` : '';
         const currentTime = (timezone && Number.isNaN(Number(timezone.zoneAbbr()))) ? timezone.zoneAbbr() : GMTTime;
         const shouldShowLocalTime = !ReportUtils.hasExpensifyEmails([details.login]);
@@ -185,7 +226,7 @@ class DetailsPage extends React.PureComponent {
                                             {this.props.translate('detailsPage.localTime')}
                                         </Text>
                                         <Text numberOfLines={1}>
-                                            {timezone.format('LT')}
+                                            {this.state.updatedTime}
                                             {' '}
                                             {currentTime}
                                         </Text>
-- 
2.31.0


```

**Comment by sophiepintoraetz** [comment] 2022-11-14 20:43
Hey @yuwenmemon - any thoughts here?

**Comment by yuwenmemon** [comment] 2022-11-14 21:05
@hungvu193 The jist of your proposal makes sense although I think we could easily DRY the code up a bit by reusing the logic we already have to get the initial current time.

**Comment by hungvu193** [comment] 2022-11-15 00:29
> @hungvu193 The jist of your proposal makes sense although I think we could easily DRY the code up a bit by reusing the logic we already have to get the initial current time.

Yeah, I agree, we already had similar logic, I will update my proposal soon

**Comment by hungvu193** [comment] 2022-11-15 03:04
@yuwenmemon 
<b>Updated proposal</b>
I created a new function called: `getParticipantLocalTime` to reuse.

```diff
From 008fb89f00312c47b2964818da8426f5732e1ba0 Mon Sep 17 00:00:00 2001
From: Hans <visaocuoitroi193@gmail.com>
Date: Tue, 15 Nov 2022 10:02:58 +0700
Subject: [PATCH] Update participantLocalTime

---
 src/libs/DateUtils.js                         | 23 ++++++++++++
 src/pages/DetailsPage.js                      | 35 ++++++++++++++++++-
 src/pages/home/report/ParticipantLocalTime.js | 10 +-----
 3 files changed, 58 insertions(+), 10 deletions(-)

diff --git a/src/libs/DateUtils.js b/src/libs/DateUtils.js
index 3582e6723..84ef1af8b 100644
--- a/src/libs/DateUtils.js
+++ b/src/libs/DateUtils.js
@@ -161,6 +161,28 @@ function getMicroseconds() {
     return Date.now() * CONST.MICROSECONDS_PER_MS;
 }
 
+/**
+ * Get the participant local time in string
+ * @param {String} locale
+ * @param {String} currentSelectedTimezone
+ * @returns {String}
+ */
+function getParticipantLocalTime(locale, currentSelectedTimezone) {
+    const reportTimezone = getLocalMomentFromTimestamp(
+        locale,
+        null,
+        currentSelectedTimezone,
+    );
+    const currentTimezone = getLocalMomentFromTimestamp(locale);
+    const reportRecipientDay = reportTimezone.format('dddd');
+    const currentUserDay = currentTimezone.format('dddd');
+
+    if (reportRecipientDay !== currentUserDay) {
+        return `${reportTimezone.format('LT')} ${reportRecipientDay}`;
+    }
+    return `${reportTimezone.format('LT')}`;
+}
+
 /**
  * @namespace DateUtils
  */
@@ -173,6 +195,7 @@ const DateUtils = {
     canUpdateTimezone,
     setTimezoneUpdated,
     getMicroseconds,
+    getParticipantLocalTime,
 };
 
 export default DateUtils;
diff --git a/src/pages/DetailsPage.js b/src/pages/DetailsPage.js
index 7ca5afb9c..2d51f226f 100755
--- a/src/pages/DetailsPage.js
+++ b/src/pages/DetailsPage.js
@@ -24,6 +24,7 @@ import MenuItem from '../components/MenuItem';
 import AttachmentModal from '../components/AttachmentModal';
 import PressableWithoutFocus from '../components/PressableWithoutFocus';
 import * as Report from '../libs/actions/Report';
+import Timers from '../libs/Timers';
 
 const matchType = PropTypes.shape({
     params: PropTypes.shape({
@@ -71,7 +72,22 @@ const getPhoneNumber = (details) => {
 };
 
 class DetailsPage extends React.PureComponent {
+    constructor(props) {
+        super(props);
+        this.getParticipantLocalTime = this.getParticipantLocalTime.bind(this);
+        this.state = {
+            updatedTime: this.getParticipantLocalTime(),
+        };
+    }
+
     componentDidMount() {
+        this.timer = Timers.register(
+            setInterval(() => {
+                this.setState({
+                    updatedTime: this.getParticipantLocalTime(),
+                });
+            }, 1000),
+        );
         if (lodashGet(this.props.route.params, 'login')) {
             return;
         }
@@ -80,6 +96,21 @@ class DetailsPage extends React.PureComponent {
         Navigation.dismissModal();
     }
 
+    componentWillUnmount() {
+        clearInterval(this.timer);
+    }
+
+    getParticipantLocalTime() {
+        const details = lodashGet(
+            this.props.personalDetails,
+            lodashGet(this.props.route.params, 'login'),
+        );
+        const reportRecipientTimezone = details.timezone
+            ? details.timezone.selected
+            : CONST.DEFAULT_TIME_ZONE;
+        return DateUtils.getParticipantLocalTime(this.props.preferredLocale, reportRecipientTimezone);
+    }
+
     render() {
         let details = lodashGet(this.props.personalDetails, lodashGet(this.props.route.params, 'login'));
         if (!details) {
@@ -94,8 +125,10 @@ class DetailsPage extends React.PureComponent {
 
         // If we have a reportID param this means that we
         // arrived here via the ParticipantsPage and should be allowed to navigate back to it
+
         const shouldShowBackButton = Boolean(this.props.route.params.reportID);
         const timezone = details.timezone ? DateUtils.getLocalMomentFromTimestamp(this.props.preferredLocale, null, details.timezone.selected) : null;
+
         const GMTTime = timezone ? `${timezone.toString().split(/[+-]/)[0].slice(-3)} ${timezone.zoneAbbr()}` : '';
         const currentTime = (timezone && Number.isNaN(Number(timezone.zoneAbbr()))) ? timezone.zoneAbbr() : GMTTime;
         const shouldShowLocalTime = !ReportUtils.hasExpensifyEmails([details.login]);
@@ -185,7 +218,7 @@ class DetailsPage extends React.PureComponent {
                                             {this.props.translate('detailsPage.localTime')}
                                         </Text>
                                         <Text numberOfLines={1}>
-                                            {timezone.format('LT')}
+                                            {this.state.updatedTime}
                                             {' '}
                                             {currentTime}
                                         </Text>
diff --git a/src/pages/home/report/ParticipantLocalTime.js b/src/pages/home/report/ParticipantLocalTime.js
index b62a7ba5e..47802a4f1 100644
--- a/src/pages/home/report/ParticipantLocalTime.js
+++ b/src/pages/home/report/ParticipantLocalTime.js
@@ -42,15 +42,7 @@ class ParticipantLocalTime extends PureComponent {
 
     getParticipantLocalTime() {
         const reportRecipientTimezone = lodashGet(this.props.participant, 'timezone', CONST.DEFAULT_TIME_ZONE);
-        const reportTimezone = DateUtils.getLocalMomentFromTimestamp(this.props.preferredLocale, null, reportRecipientTimezone.selected);
-        const currentTimezone = DateUtils.getLocalMomentFromTimestamp(this.props.preferredLocale);
-        const reportRecipientDay = reportTimezone.format('dddd');
-        const currentUserDay = currentTimezone.format('dddd');
-
-        if (reportRecipientDay !== currentUserDay) {
-            return `${reportTimezone.format('LT')} ${reportRecipientDay}`;
-        }
-        return `${reportTimezone.format('LT')}`;
+        return DateUtils.getParticipantLocalTime(this.props.preferredLocale, reportRecipientTimezone.selected);
     }
 
     render() {
-- 
2.31.0


```

**Comment by amyevans** [comment] 2022-11-15 18:40
@rushatgabhane could you review the above proposal?

**Comment by hungvu193** [comment] 2022-11-18 12:54
> @hungvu193 wait, why exactly do you need the participant prop? I don't see it being used in your diff

No, I mean the way `ParticipantLocalTime` calculate the time by using participant.

**Comment by hungvu193** [comment] 2022-11-21 09:02
> @hungvu193 you could then create two functions `getParticipantLocalTime()` & `getCurrentUserLocalTime()`

Cool, I'll take a look at it.

**Comment by s77rt** [comment] 2022-11-22 09:37
still accepting proposals on this?

**Comment by sophiepintoraetz** [comment] 2022-11-22 20:24
@s77rt - we are accepting proposals!

**Comment by s77rt** [comment] 2022-11-22 22:51
### Proposal
```diff
diff --git a/src/pages/DetailsPage.js b/src/pages/DetailsPage.js
index ce2ea1f4c..d37c001ec 100755
--- a/src/pages/DetailsPage.js
+++ b/src/pages/DetailsPage.js
@@ -24,6 +24,7 @@ import MenuItem from '../components/MenuItem';
 import AttachmentModal from '../components/AttachmentModal';
 import PressableWithoutFocus from '../components/PressableWithoutFocus';
 import * as Report from '../libs/actions/Report';
+import Timers from '../libs/Timers';
 
 const matchType = PropTypes.shape({
     params: PropTypes.shape({
@@ -71,7 +72,26 @@ const getPhoneNumber = (details) => {
 };
 
 class DetailsPage extends React.PureComponent {
+    constructor(props) {
+        super(props);
+
+        this.getDetails = this.getDetails.bind(this);
+        this.getLocalTime = this.getLocalTime.bind(this);
+
+        this.details = this.getDetails();
+
+        this.state = {
+            localTime: this.getLocalTime(),
+        };
+    }
+
     componentDidMount() {
+        this.timer = Timers.register(setInterval(() => {
+            this.setState({
+                localTime: this.getLocalTime(),
+            });
+        }, 1000));
+
         if (lodashGet(this.props.route.params, 'login')) {
             return;
         }
@@ -80,7 +100,11 @@ class DetailsPage extends React.PureComponent {
         Navigation.dismissModal();
     }
 
-    render() {
+    componentWillUnmount() {
+        clearInterval(this.timer);
+    }
+
+    getDetails() {
         let details = lodashGet(this.props.personalDetails, lodashGet(this.props.route.params, 'login'));
         if (!details) {
             const login = lodashGet(this.props.route.params, 'login');
@@ -90,14 +114,25 @@ class DetailsPage extends React.PureComponent {
                 avatar: ReportUtils.getDefaultAvatar(),
             };
         }
+        return details;
+    }
+
+    getLocalTime() {
+        const details = this.details;
+        const timezone = details.timezone ? DateUtils.getLocalMomentFromDatetime(this.props.preferredLocale, null, details.timezone.selected) : null;
+        const GMTTime = timezone ? `${timezone.toString().split(/[+-]/)[0].slice(-3)} ${timezone.zoneAbbr()}` : '';
+        const currentTime = (timezone && Number.isNaN(Number(timezone.zoneAbbr()))) ? timezone.zoneAbbr() : GMTTime;
+
+        return {currentTime, timezone};
+    }
+
+    render() {
+        const details = this.details;
         const isSMSLogin = Str.isSMSLogin(details.login);
 
         // If we have a reportID param this means that we
         // arrived here via the ParticipantsPage and should be allowed to navigate back to it
         const shouldShowBackButton = Boolean(this.props.route.params.reportID);
-        const timezone = details.timezone ? DateUtils.getLocalMomentFromDatetime(this.props.preferredLocale, null, details.timezone.selected) : null;
-        const GMTTime = timezone ? `${timezone.toString().split(/[+-]/)[0].slice(-3)} ${timezone.zoneAbbr()}` : '';
-        const currentTime = (timezone && Number.isNaN(Number(timezone.zoneAbbr()))) ? timezone.zoneAbbr() : GMTTime;
         const shouldShowLocalTime = !ReportUtils.hasExpensifyEmails([details.login]);
 
         let pronouns = details.pronouns;
@@ -182,9 +217,9 @@ class DetailsPage extends React.PureComponent {
                                             {this.props.translate('detailsPage.localTime')}
                                         </Text>
                                         <Text numberOfLines={1}>
-                                            {timezone.format('LT')}
+                                            {this.state.localTime.timezone.format('LT')}
                                             {' '}
-                                            {currentTime}
+                                            {this.state.localTime.currentTime}
                                         </Text>
                                     </View>
                                 ) : null}
```

### Details
Refactored the page to have similar logic to https://github.com/Expensify/App/blob/main/src/pages/home/report/ParticipantLocalTime.js

**Comment by aldo-expensify** [comment] 2022-11-23 23:04
> @hungvu193 that's a creative idea. But let's not `forceUpdate` the component.
> 
> [force update react docs](https://reactjs.org/docs/react-component.html#:~:text=calling%20forceupdate()%20will%20cause%20render()%20to%20be%20called%20on%20the%20component%2C%20skipping%20shouldcomponentupdate().%20this%20will%20trigger%20the%20normal%20lifecycle%20methods%20for%20child%20components%2C%20including%20the%20shouldcomponentupdate()%20method%20of%20each%20child.%20react%20will%20still%20only%20update%20the%20dom%20if%20the%20markup%20changes)

I see that the docs says that we should avoid `forceUpdate`... but maybe this is one of the cases where we should make an exception? it is just so much simple and it also doesn't make 100% sense for me to put the current time in the state just for the sake of avoiding `forceUpdate`.

Maybe we should take this to slack to get more opinions?

**Comment by vladamx** [comment] 2022-11-23 23:41
@rushatgabhane We could just update the time on details focus in order to avoid timers and force update shenanigans.

**Comment by vladamx** [comment] 2022-11-24 03:09
> > update the time on details focus in order to avoid timers and force update shenanigans.
> 
> @vladamx sorry, i don't understand what update time on details focus means 
> 
> but hell yeah, please post a proposal! sounds interesting if we can avoid times etc

When details get navigation focus

**Comment by hungvu193** [comment] 2022-11-28 03:54
@rushatgabhane 
I moved the component for calculating time into a new component, by doing this way everytime it update it won't cause the whole DetailPage re-renders.

```diff
diff --git a/src/components/AutoUpdateTime.js b/src/components/AutoUpdateTime.js
new file mode 100644
index 000000000..68fc119f3
--- /dev/null
+++ b/src/components/AutoUpdateTime.js
@@ -0,0 +1,85 @@
+import {View} from 'react-native';
+import React, {PureComponent} from 'react';
+import styles from '../styles/styles';
+import DateUtils from '../libs/DateUtils';
+import withLocalize, {withLocalizePropTypes} from './withLocalize';
+import personalDetailsPropType from '../pages/personalDetailsPropType';
+import * as ReportUtils from '../libs/ReportUtils';
+import Timers from '../libs/Timers';
+import Text from './Text';
+
+const propTypes = {
+    details: personalDetailsPropType,
+    ...withLocalizePropTypes,
+};
+
+const defaultProps = {
+    details: {},
+};
+
+class AutoUpdateTime extends PureComponent {
+    constructor(props) {
+        super(props);
+        this.getCurrentUserLocalTime = this.getCurrentUserLocalTime.bind(this);
+        this.state = {
+            timezone: this.getCurrentUserLocalTime(),
+        };
+    }
+
+    componentDidMount() {
+        this.timer = Timers.register(setInterval(() => {
+            this.setState({
+                timezone: this.getCurrentUserLocalTime(),
+            });
+        }, 1000));
+    }
+
+    componentWillUnmount() {
+        clearInterval(this.timer);
+    }
+
+    getCurrentUserLocalTime() {
+        return this.props.details.timezone
+            ? DateUtils.getLocalMomentFromDatetime(
+                this.props.preferredLocale,
+                null,
+                this.props.details.timezone.selected,
+            )
+            : null;
+    }
+
+    render() {
+        const GMTTime = this.state.timezone
+            ? `${this.state.timezone
+                .toString()
+                .split(/[+-]/)[0]
+                .slice(-3)} ${this.state.timezone.zoneAbbr()}`
+            : '';
+        const currentTime = this.state.timezone
+          && Number.isNaN(Number(this.state.timezone.zoneAbbr()))
+            ? this.state.timezone.zoneAbbr()
+            : GMTTime;
+        const shouldShowLocalTime = !ReportUtils.hasExpensifyEmails([
+            this.props.details.login,
+        ]);
+        if (!shouldShowLocalTime) {
+            return null;
+        }
+        return (
+            <View style={[styles.mb6, styles.detailsPageSectionContainer]}>
+                <Text style={[styles.formLabel, styles.mb2]} numberOfLines={1}>
+                    {this.props.translate('detailsPage.localTime')}
+                </Text>
+                <Text numberOfLines={1}>
+                    {this.state.timezone.format('LT')}
+                    {' '}
+                    {currentTime}
+                </Text>
+            </View>
+        );
+    }
+}
+
+AutoUpdateTime.defaultProps = defaultProps;
+AutoUpdateTime.propTypes = propTypes;
+export default withLocalize(AutoUpdateTime);
diff --git a/src/pages/DetailsPage.js b/src/pages/DetailsPage.js
index ce2ea1f4c..fd6f9969e 100755
--- a/src/pages/DetailsPage.js
+++ b/src/pages/DetailsPage.js
@@ -24,6 +24,7 @@ import MenuItem from '../components/MenuItem';
 import AttachmentModal from '../components/AttachmentModal';
 import PressableWithoutFocus from '../components/PressableWithoutFocus';
 import * as Report from '../libs/actions/Report';
+import AutoUpdateTime from '../components/AutoUpdateTime';
 
 const matchType = PropTypes.shape({
     params: PropTypes.shape({
@@ -95,11 +96,6 @@ class DetailsPage extends React.PureComponent {
         // If we have a reportID param this means that we
         // arrived here via the ParticipantsPage and should be allowed to navigate back to it
         const shouldShowBackButton = Boolean(this.props.route.params.reportID);
-        const timezone = details.timezone ? DateUtils.getLocalMomentFromDatetime(this.props.preferredLocale, null, details.timezone.selected) : null;
-        const GMTTime = timezone ? `${timezone.toString().split(/[+-]/)[0].slice(-3)} ${timezone.zoneAbbr()}` : '';
-        const currentTime = (timezone && Number.isNaN(Number(timezone.zoneAbbr()))) ? timezone.zoneAbbr() : GMTTime;
-        const shouldShowLocalTime = !ReportUtils.hasExpensifyEmails([details.login]);
-
         let pronouns = details.pronouns;
 
         if (pronouns && pronouns.startsWith(CONST.PRONOUNS.PREFIX)) {
@@ -176,18 +172,7 @@ class DetailsPage extends React.PureComponent {
                                         </Text>
                                     </View>
                                 ) : null}
-                                {shouldShowLocalTime && details.timezone ? (
-                                    <View style={[styles.mb6, styles.detailsPageSectionContainer]}>
-                                        <Text style={[styles.formLabel, styles.mb2]} numberOfLines={1}>
-                                            {this.props.translate('detailsPage.localTime')}
-                                        </Text>
-                                        <Text numberOfLines={1}>
-                                            {timezone.format('LT')}
-                                            {' '}
-                                            {currentTime}
-                                        </Text>
-                                    </View>
-                                ) : null}
+                                <AutoUpdateTime details={details} />
                             </View>
                             {details.login !== this.props.session.email && (
                                 <MenuItem
```
Let's me know what you think.

**Comment by cead22** [comment] 2022-11-28 21:51
I don't know how much more complex this is, but can we have this component update once every minute, instead of once every second? perhaps the function should be queued to run at the top of the minute or 1 second after the top of the minute, every time

**Comment by cead22** [comment] 2022-11-28 21:53
Also should we pass separate props for `timezone`, `selectedTimezone` and `login` (or `shouldShowLocalTime`) instead of a `details` object that contains these keys?

**Comment by sophiepintoraetz** [comment] 2022-11-28 22:49
Not overdue - still discussing proposals

**Comment by hungvu193** [comment] 2022-11-29 00:45
> Also should we pass separate props for `timezone`, `selectedTimezone` and `login` (or `shouldShowLocalTime`) instead of a `details` object that contains these keys?

Yeah that make sense :)

**Comment by cead22** [comment] 2022-11-29 01:35
@hungvu193 I'll re-review your proposal tomorrow!

**Comment by cead22** [comment] 2022-11-29 20:12
@hungvu193 thanks for your patience, 👍 please  go ahead with your proposal. Here's a couple of notes
- I noticed that if `details.timezone` isn't set, I think we'll end up displaying `Local Time` and then nothing under it, because the logic to show this UI before was `!ReportUtils.hasExpensifyEmails && details.timezone ` and now it's `!ReportUtils.hasExpensifyEmails`
- Given that, I think you should consider leaving `shouldShowLocalTime` where it is so we end up with something like `{shouldShowLocalTime && details.timezone && <AutoUpdateTime details={details} />} in `src/pages/DetailsPage.js`
- And we don't need `if (!shouldShowLocalTime) {` in `AutoUpdateTime`

**Comment by amyevans** [comment] 2022-11-29 22:45
Discussed with @cead22 and will reassign him as CME here 😄

**Comment by hungvu193** [comment] 2022-11-30 00:46
> @hungvu193 thanks for your patience, 👍 please  go ahead with your proposal. Here's a couple of notes
> 
> - I noticed that if `details.timezone` isn't set, I think we'll end up displaying `Local Time` and then nothing under it, because the logic to show this UI before was `!ReportUtils.hasExpensifyEmails && details.timezone ` and now it's `!ReportUtils.hasExpensifyEmails`
> 
> - Given that, I think you should consider leaving `shouldShowLocalTime` where it is so we end up with something like `{shouldShowLocalTime && details.timezone && <AutoUpdateTime details={details} />} in `src/pages/DetailsPage.js`
> 
> - And we don't need `if (!shouldShowLocalTime) {` in `AutoUpdateTime`

Cool, I'll make a PR later today

**Comment by hungvu193** [comment] 2022-11-30 06:26
@cead22 https://github.com/Expensify/App/pull/13183 is ready!

**Comment by sophiepintoraetz** [comment] 2022-12-04 22:05
Not overdue

**Comment by sophiepintoraetz** [comment] 2022-12-08 18:31
Still reviewing the PR - not overdue

**Comment by trjExpensify** [comment] 2022-12-12 21:46
Let's remember to add the `reviewing` label once a PR goes into review. 

@rushatgabhane, can we get an ETA on completing the review checklist please?

**Comment by trjExpensify** [comment] 2022-12-15 01:23
@rushatgabhane you did submit to get whitelisted, right? Ping us in Slack if you're still having trouble!

**Comment by sophiepintoraetz** [comment] 2022-12-20 22:18
[Asking in #contributor-plus](https://expensify.slack.com/archives/C02NK2DQWUX/p1671574621867409) to see if we can get someone else to review the PR.
@cead22 it could be faster to have another Expensify engineer to review the PR?

**Comment by mananjadhav** [comment] 2022-12-21 02:52
Thanks for assigning @sophiepintoraetz. I'll get to it in 1-2 hours.

**Comment by mananjadhav** [comment] 2022-12-21 06:17
Reviewed and left comments.

**Comment by aldo-expensify** [comment] 2023-01-03 14:39
PR merged

**Comment by mananjadhav** [comment] 2023-01-03 18:34
PR was merged today, but I wonder why bot commented, when an update was added by @aldo-expensify 3 hours go.

**Comment by aldo-expensify** [comment] 2023-01-03 19:21
> PR was merged today, but I wonder why bot commented, when an update was added by @aldo-expensify 3 hours go.

My guess is that my comment didn't have any effect because I'm not assigned to the issue (just a guess)

**Comment by mananjadhav** [comment] 2023-01-11 18:29
PR is deployed to production 5 days back. Waiting for the regression period to cross.

**Comment by sophiepintoraetz** [comment] 2023-01-13 02:56
I'll look into payment next week, @mananjadhav! thanks for the reminder.

**Comment by mananjadhav** [comment] 2023-01-17 02:57
@sophiepintoraetz Did you get a chance to look this ?

**Comment by sophiepintoraetz** [comment] 2023-01-17 04:54
Tomorrow!

**Comment by sophiepintoraetz** [comment] 2023-01-18 00:33
Summary of payouts here:
@jayeshmangwani - $250
@hungvu193 - $1000 + potential bonus
@mananjadhav - $1000 + potential bonus

Regarding the potential bonus payment - this is something I will need to discuss internally, as there are a few technicalities I want to address first. I apologies for the delay here!

**Comment by mananjadhav** [comment] 2023-01-18 02:50
Thank you so much @sophiepintoraetz.

**Comment by sophiepintoraetz** [comment] 2023-01-19 02:48
Thanks for bearing with me. I confirmed internally that there will be no bonuses made due to the timing of PR reviews/deployment. The payment will be as follows:

@jayeshmangwani - $250
@hungvu193 - $1000
@mananjadhav - $1000

Job is [here](https://www.upwork.com/jobs/~01e7ef7e53a2403709) (though you've been hired)

**Comment by mananjadhav** [comment] 2023-01-19 02:52
Thanks for the update @sophiepintoraetz. Appreciate the effort!

**Closed** 2023-01-19 04:35 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
