### ISSUE TITLE
Task - Multiple presses of the "Enter" button create duplicate tasks

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47190] opened 2024-08-09 23:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4841867
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with any account
3. Navigate to any conversation
4. Start creating a task
5. Add a multi-sided description
6. Click on the "Next" button
6. Press repeatedly the "Enter" button or the "Confirm task" button

## Expected Result:
Tasks should not be duplicated after repeatedly pressing "Enter" or the "Confirm task" button itself

## Actual Result:
Multiple presses of the "Enter" button create duplicate tasks

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5d1eb046-c1b3-46f8-bb8e-ec6533a6e7a8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-09 23:02
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-08-09 23:02
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neonbhai** [comment] 2024-08-10 00:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - Multiple presses of the "Enter" button create duplicate tasks

### What is the root cause of that problem?
This happens as we are missing the useSingleExecution logic for onSubmit when creating task [here](https://github.com/Expensify/App/blob/6be470f60f6027b49b63ff6507b33f98e2904662/src/pages/tasks/NewTaskPage.tsx#L98-L100)

### What changes do you think we should make in order to solve the problem?
We should wrap the onSubmit here with a useSingleExecution hook:

https://github.com/Expensify/App/blob/6be470f60f6027b49b63ff6507b33f98e2904662/src/pages/tasks/NewTaskPage.tsx#L98-L100



### Alternatively
We can add a prop to FormAlertWithSubmitButton called useSingleExecution

**Comment by hayes102** [comment] 2024-08-10 00:13
issue is not reproducible on main.

**Comment by neonbhai** [comment] 2024-08-10 00:36
Reproducible:



https://github.com/user-attachments/assets/64ca6662-02e4-46a6-9e2e-0a750782090f

3 tasks are created

**Comment by adelekennedy** [comment] 2024-08-12 21:41
I can't even reproduce this going as fast as I can on v v9.0.19-4 - closing this

**Closed by adelekennedy** 2024-08-12 21:41 UTC
Labels: Daily, Bug
