### ISSUE TITLE
IOU - Settled up elseware displayed in LHN when settled using paypal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22958] opened 2023-07-15 20:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. As userB, add a Paypal.me handle i.e tomrhys
2. As userB, send a request to userA for $1.00 such that userB is owed
3. As userA, navigate to the iouReport settle the request by selection paypal option

## Expected Result:
Report comment updated as settled $ using Pay pal me for both parent and child

## Actual Result:
Parent report updated as settled elsewhere

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7043d8c1-cf12-4fd3-9c1b-d470980ed4e8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by getusha** [comment] 2023-07-16 07:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU settled up elsewhere displayed after settling with paypal
### What is the root cause of that problem?
The backend will return `...using PayPal.me`  but our regex explicitly matches only `Paypal.me`

https://github.com/Expensify/App/blob/6e5b07cf45944f28373e188d6f02620a12d6da29/src/libs/ReportUtils.js#L1103

### What changes do you think we should make in order to solve the problem?


we can easily fix this issue by updating the regex to `/ Paypal.me$/i` adding `i` which is case insensitive.

### What alternative solutions did you explore? (Optional)

**Comment by sakluger** [comment] 2023-07-18 17:09
This may be a duplicate of https://github.com/Expensify/App/issues/23022. This one was created first, but that one has already had the external label added so I'm going to hold off until we confirm whether they are dupes.

**Comment by mountiny** [comment] 2023-07-18 17:29
Dupe off https://github.com/Expensify/App/issues/23022

**Closed by mountiny** 2023-07-18 17:29 UTC
Labels: Daily, Bug
