### ISSUE TITLE
[$500] Chat - The contact is highlighted when you create a conversation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37800] opened 2024-03-05 21:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4380775
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in to your HT account
3. Tap on the green plus button (FAB)
4. Select Start chat

## Expected Result:
In mWeb and native apps, highlighting contacts should not happen since there is no arrow navigation.

## Actual Result:
The contact is highlighted when you create a conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/98aae4f2-1c9d-4edc-918d-b96f5ae3cfe0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017825971f9646dbf3</li>
        <li>Upwork Job ID: 1767170648931237888</li>
        <li>Last Price Increase: 2024-04-29</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-05 21:20
@sonialiap I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment] 2024-03-05 21:21
We think that this bug might be related to #vip-vsb
@quinthar

**Comment by nkdengineer** [comment] 2024-03-06 01:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Chat - The contact is highlighted when you create a conversation
### What is the root cause of that problem?
- When implementing ArrowKeyFocusManager, we do not consider if the device is small width device or not
### What changes do you think we should make in order to solve the problem?
- We can update [this](https://github.com/Expensify/App/blob/9bfe961622d03de5ac8e18652bbb56dda5ed9f60/src/components/OptionsList/BaseOptionsList.tsx#L185) to:
```
                optionIsFocused={!disableFocusOptions && !isItemDisabled && !DeviceCapabilities.canUseTouchScreen() && focusedIndex === index + section.indexOffset}
```
- Or we can use other method to check if the device is a small screen instead of ```DeviceCapabilities.canUseTouchScreen()```
### What alternative solutions did you explore? (Optional)

- NA

**Comment by dragnoir** [comment] 2024-03-06 11:06
The main component for this behaviour is `OptionsSelector` and it's deprecated https://github.com/Expensify/App/pull/37628. I think we can close this.

**Comment by nkdengineer** [comment] 2024-03-07 01:23
@dragnoir The component that use SelectionList also encountered this behavior

**Comment by sonialiap** [comment] 2024-03-11 12:47
I can reproduce this

**Comment by dragnoir** [comment] 2024-03-11 12:58
Proposal

Please re-state the problem that we are trying to solve in this issue.

Wrong highlighted item.

What is the root cause of that problem?

We will not use OptionsSelector or update it. Deprecated. 

What changes do you think we should make in order to solve the problem?

Replace OptionSelector with SelectionList.

What alternative solutions did you explore? (Optional)

**Comment by superAI4003** [comment] 2024-03-11 16:00
Hello.
I am a freelancer on upwork.
I am very interested in your project.
Thanks

**Comment by dragnoir** [comment] 2024-03-12 20:41
@fedirjh this issue is fixed with https://github.com/Expensify/App/pull/34356

**Comment by nkdengineer** [comment] 2024-03-13 05:31
@fedirjh I just tested but still can reproduce

**Comment by nkdengineer** [comment] 2024-03-13 15:35
@fedirjh The same behavior also appears in other similar components,  for example the search page.

**Comment by dragnoir** [comment] 2024-03-14 11:53
@fedirjh I think we should hold for https://github.com/Expensify/App/pull/34356 refactor

**Comment by sonialiap** [comment] 2024-03-18 15:59
https://github.com/Expensify/App/pull/34356 has been merged, can we proceed with this issue?

**Comment by superAI4003** [comment] 2024-03-18 18:22
Yes, I want $1000.

**Comment by sonialiap** [comment] 2024-04-15 15:42
PR is merged! Waiting for deploy

**Comment by sonialiap** [comment] 2024-04-18 11:40
Thanks Rachid, closing this one out

**Comment by nkdengineer** [comment] 2024-04-22 05:34
@fedirjh Can you help check this [comment](https://github.com/Expensify/App/issues/37800#issuecomment-2063907795) ?

**Comment by nkdengineer** [comment] 2024-04-23 03:16
@fedirjh In my opinion, I believe that on mobile devices, we should avoid having the "highlight" effect as seen in the expected behavior in the original post. This is because the scenario where the user utilizes the "soft keyboard" is infrequent.

**Comment by dubielzyk-expensify** [comment] 2024-04-24 00:55
> cc @Expensify/design I would love to hear your opinion on this. Do you think it would be a good idea to disable the highlighting of contacts within the search list on mobile devices?

Yeah that sounds reasonable to me. Given we focus on the input field for contact when clicking "Start chat" I don't think anything should be selected until you tab out of it. And given on mobile that's not an option (unless you have external keyboard hooked up) it doesn't make sense to show any highlight at all. Keen to hear what rest of @Expensify/design thinks though.

**Comment by shawnborton** [comment] 2024-04-24 12:10
Yeah, I think I generally agree with this from the OP:

> Expected Result:
> In mWeb and native apps, highlighting contacts **should not happen** since there is no arrow navigation.

**Comment by shawnborton** [comment] 2024-04-24 12:11
I see the point about the enter key though... and if we decide to keep that kind of behavior, then it would make sense to keep the highlighting.

**Comment by dannymcclain** [comment] 2024-04-24 13:40
I also agree that no list items should be highlighted/focused until you specifically tab down into the list.

**Comment by dannymcclain** [comment] 2024-04-24 19:51
Ok looking through this again, is this the correct expected behavior:

- No items highlighted when you first load the list (and have _not_ typed anything)
- Once you start typing, we filter the list based on your query and highlight the first list item
- If you press `Enter/Return`, we navigate you to the highlighted list item

If this is the expected behavior, I think it is ok to keep it on mobile as well, since it's been pointed out that using the mobile enter key still functions the same way.

Seems like the video in the description of this issue is showing that the first list item is highlighted _before_ a search term is even entered, which is inconsistent with the expected behavior bullets I outlined above (if those are the correct expected behaviors!)

**Comment by sonialiap** [comment] 2024-04-30 12:32
Closing 👍

**Closed by sonialiap** 2024-04-30 12:32 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
