### ISSUE TITLE
[$1000] HTML code (like &amp;) in split bill description are converted to HTML character in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20590] opened 2023-06-12 14:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any group report
3. Click on plus and click on split bill
4. Enter any amount and click Next
5. Click on Description and add `&amp;` in it with any other text if needed
6. Click on split and observe the split bill message in LHN and in report
Expected Result: App should not convert HTML codes like &amp; to HTML characters in LHN

## Expected Result:
App should not convert HTML codes like &amp; to HTML characters in LHN

## Actual Result:
App converts HTML codes (like &amp;) in split bill description to HTML characters in LHN (it works fine for normal messages)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1da1e271-c62e-46b4-a998-c2b91ab47431

https://github.com/Expensify/App/assets/93399543/32ed1b17-2b48-498b-b00a-324ed764f211

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686204285224359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012bacc768041b8cae</li>
        <li>Upwork Job ID: 1669456962217844736</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by Nikhil-Vats** [comment] 2023-06-12 20:24
I think this is fixed by the PR for https://github.com/Expensify/App/issues/20492. Not reproducible on main anymore.

**Comment by dhanashree-sawant** [comment] 2023-06-13 07:48
Still able to reproduce on staging though.

**Comment by strepanier03** [comment] 2023-06-13 22:20
Hmm, @dhanashree-sawant - What devices are you using on staging? I've tested from Mac Desktop and Mac/Chrome on staging and I can repro.

**Comment by dhanashree-sawant** [comment] 2023-06-15 05:51
Hi @strepanier03, I have tested on mac chrome, mac safari and was able to recreate on current staging.

https://github.com/Expensify/App/assets/87513216/3d84706e-6b69-4648-905d-8d71d1d8f5be

**Comment by strepanier03** [comment] 2023-06-15 21:28
Tested and I can recreate so I'll update the repro steps. 

Also found [this](https://expensify.slack.com/archives/C01SKUP7QR0/p1677563132745579) in Slack where we confirmed we don't want to convert HTML code. 

Thanks @dhanashree-sawant!

**Comment by strepanier03** [comment] 2023-06-15 21:30
@MitchExpensify - I am heading out for sabbatical this evening so I need to reassign it. 

I just finished testing and sent to external for there are no immediate steps you need to take. In the coming days/weeks we'll need to keep pressure on to have this move forward and handle payment. 

Thank you for wrapping this up!

**Comment by kermodebear** [comment] 2023-06-16 07:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App should not convert html characters like `&amp;` in LHN

### What is the root cause of that problem?
When building `lastMessageText`  report.lastMessageText is [used]( https://github.com/Expensify/App/blob/7b00c47ee7debf7137417ac768efe8d4c6b872d0/src/libs/SidebarUtils.js#L305)

### What changes do you think we should make in order to solve the problem?
Use `report.lastMessageHtml` instead i.e. replace the line 
`lastMessageTextFromReport = report ? report.lastMessageText || '' : '';`
with 
 `lastMessageTextFromReport = report ? report.lastMessageHtml || '' : '';`

**Comment by kermodebear** [comment] 2023-06-16 07:59
Contributor details
Your Expensify account email: nomadneurox@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0151c3a61ade0ad8f0

**Comment by kermodebear** [comment] 2023-06-16 10:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App should not convert html characters like `&amp;` in LHN

### What is the root cause of that problem?
I'd first investigate if the Issue comes from the server side, because in optimisticupdate `report.lastMessageText` correctly 
gets set to `test &amp;` but after a request it changes to `test &`. You can also see it from @dhanashree-sawant s video above. It briefly updates correctly. 

### What changes do you think we should make in order to solve the problem?
One way to fix it from client side would be to change the line from [here]( https://github.com/Expensify/App/blob/7b00c47ee7debf7137417ac768efe8d4c6b872d0/src/libs/SidebarUtils.js#L305)

   ` lastMessageTextFromReport = report ? report.lastMessageText || '' : '';`

to following:

```
const parser = new ExpensiMark(); 
lastMessageTextFromReport  = parser.htmlToText(report ? report.lastMessageHtml || '' : '');
 
```

I've tested it for `&` and `&amp` and it worked correctly

**Comment by MitchExpensify** [comment] 2023-06-16 22:32
@fedirjh How do these proposals / comments sound to you?

**Comment by MitchExpensify** [comment] 2023-06-19 22:04
> @MitchExpensify I believe this should be fixed on server side, @kermodebear has a valid solution for frontend, but I think if the issue is from server then it should be fixed on server

Got it! Applying the Internal label in that case 👍

**Comment by MitchExpensify** [comment] 2023-06-26 09:55
> Seems automation didn’t worked here

Thanks for the catch, labeling `Engineering`

**Comment by MitchExpensify** [comment] 2023-07-01 17:52
Invited @fedirjh & @dhanashree-sawant to the Upwork job for eventual reporter and C+ payment https://www.upwork.com/jobs/~012bacc768041b8cae

**Comment by dhanashree-sawant** [comment] 2023-07-01 17:53
Thanks @MitchExpensify, I have accepted the offer.

**Comment by iwiznia** [comment] 2023-07-03 21:08
Oh crap, did not notice this was marked internal.... catching up.

**Comment by iwiznia** [comment] 2023-07-03 21:31
Indeed this is a backend issue. Started a thread here https://expensify.slack.com/archives/C03TQ48KC/p1688419837215279 to discuss since I don't know why that code exists or how to fix it.

**Comment by MitchExpensify** [comment] 2023-07-10 19:27
Sounds like we're closing in on a solution in [Slack](https://expensify.slack.com/archives/C03TQ48KC/p1688419837215279)! 🎉

**Comment by iwiznia** [comment] 2023-07-11 20:22
I have no idea how to fix this yet.

**Comment by MitchExpensify** [comment] 2023-07-11 23:35
haha ok I misread the Slack thread in that case. My mistake!

**Comment by iwiznia** [comment] 2023-07-21 20:15
Going on sabbatical, please reassign another engineer

**Comment by MitchExpensify** [comment] 2023-07-25 19:11
This thread might be useful to you as you begin to catch up here @puneetlath https://expensify.slack.com/archives/C03TQ48KC/p1688419837215279 

Its a fun one! 😄

**Comment by puneetlath** [comment] 2023-08-08 20:48
I haven't had a chance to dive into this yet, but I hope to soon.

**Comment by puneetlath** [comment] 2023-08-23 21:07
Sorry, I haven't had a chance to look into this yet, but I hope to soon. Not treating it too urgently since it deals with bill splitting.

**Comment by puneetlath** [comment] 2023-09-07 02:47
Haven't had a chance to prioritize this yet. Not super urgent but will get to it eventually.

**Comment by puneetlath** [comment] 2023-09-19 02:47
I still plan to get to it.

**Comment by puneetlath** [comment] 2023-10-04 14:51
I still plan to get to it.

**Comment by puneetlath** [comment] 2023-10-17 23:31
I still plan to get to it.

**Comment by puneetlath** [comment] 2023-11-01 00:51
I still plan to get to it.

**Comment by puneetlath** [comment] 2023-11-21 22:12
@MitchExpensify do you still think this is worth doing anything with? I think we should just close it.

**Comment by puneetlath** [comment] 2023-11-21 22:12
Actually, I'm going to do that, but please reopen if you disagree.

**Closed by puneetlath** 2023-11-21 22:12 UTC
Labels: Engineering, Weekly, Internal, Bug
