### ISSUE TITLE
[HOLD for payment 2024-12-05] [HOLD for payment 2024-12-03] Chat - There is no “Take a 2-minute tour” task at the Concierge chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52985] opened 2024-11-22 21:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with the new Gmail account in incognito mode
3. Complete the incorporation process using the option “Track and Budge Expenses”
4. Enter a first name and click on the Continue button
5. Go to the Concierge chat.

## Expected Result:
A task “Take a 2-minute tour” must be displayed in the Concierge chat

## Actual Result:
The “Take a 2-minute tour” task is not displayed in the Concierge chat. In some cases when executing the tour action, you hear the sound as of a completed task but nothing is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/f9908ae2-0198-47fe-a54b-0e2084af47e6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-11-22 21:59
Production:

https://github.com/user-attachments/assets/e5f26d12-7876-4b5b-bc22-06bcad5f8cdf

**Comment by chiragsalian** [comment] 2024-11-22 22:04
Both the recorded videos are of production so i think maybe you made a mistake there? Can you double check @lanitochka17. 

I tested the same steps on staging with a new account and i see `Take a 2-minute tour`.
![image](https://github.com/user-attachments/assets/8d0cac4a-7819-40cf-b32f-882972261e3f)

**Comment by lanitochka17** [comment] 2024-11-22 22:09
sorry for confusion
correct video:

https://github.com/user-attachments/assets/6388ea02-a151-433f-8397-51c3f669002e

**Comment by Shahidullah-Muffakir** [comment] 2024-11-22 22:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Take a 2-minute tour is not shown in concierge for Track and Budge Expenses

### What is the root cause of that problem?
we did not include selfGuidedTourTask: 
in 
https://github.com/Expensify/App/blob/3ebe8520d74c57a2fe9548b7d4307206e2b7c673/src/CONST.ts#L212-L226
### What changes do you think we should make in order to solve the problem?

add  selfGuidedTourTask to it

**Comment by chiragsalian** [comment] 2024-11-23 00:59
Woah, if i add a first and last name it works. But if i add only first name i don't see "Take a 2-minute tour", weird. Do you know why @Shahidullah-Muffakir?

**Comment by chiragsalian** [comment] 2024-11-23 01:07
But yeah your solution works @Shahidullah-Muffakir, feel free to create the PR. I will be heading out now but we can CP it early on Monday.

**Comment by Shahidullah-Muffakir** [comment] 2024-11-23 01:12
> Woah, if i add a first and last name it works. But if i add only first name i don't see "Take a 2-minute tour", weird. Do you know why @Shahidullah-Muffakir? 👀

@chiragsalian, Not sure, I could produce the issue even by entering first and last name.

**Comment by Shahidullah-Muffakir** [comment] 2024-11-23 01:13
> But yeah your solution works @Shahidullah-Muffakir, feel free to create the PR. I will be heading out now but we can CP it early on Monday.

@chiragsalian, Sure, Thank you.

**Comment by brunovjk** [comment] 2024-11-23 01:48
I can reproduce, reviewing PR.

<details>
<summary>52990_repro: Chrome</summary>



https://github.com/user-attachments/assets/cc66373a-615d-4dda-b486-a60483ef48c7


</details>

**Comment by c3024** [comment] 2024-11-25 11:58
PR #52912 opened for this for fixing all missing cases of tasks.

cc: @rushatgabhane @chiragsalian @jjcoffee @NJ-2020

**Comment by c3024** [comment] 2024-11-25 12:04
This is also on production. It is just that this can be seen only in cases where account id is even.

https://github.com/Expensify/App/blob/8c4661d85b0cfae50b6ab985a20d17c7fcad79f1/src/libs/Permissions.ts#L34-L35

Perhaps, this need to be a deploy blocker.

cc: @mountiny

**Comment by mountiny** [comment] 2024-11-25 15:31
I went ahead and merged and CPed the fix from @Shahidullah-Muffakir as they were assigned and already had the Pr ready and reviewed and tested.

@c3024 please continue with the fix in your linked PR

**Comment by chiragsalian** [comment] 2024-11-25 19:29
> It is just that this can be seen only in cases where account id is even.

Wow that's why it was inconsistent for me. Good to know.

**Comment by CortneyOfstad** [comment] 2024-12-05 21:03
@Shahidullah-Muffakir can you confirm if this needs a regression test?

Also, I've sent you a proposal [here](https://www.upwork.com/nx/wm/offer/105213521) in Upwork — please let me know once you accept. Thanks!

**Comment by Shahidullah-Muffakir** [comment] 2024-12-05 22:26
> @Shahidullah-Muffakir can you confirm if this needs a regression test?
> 
> Also, I've sent you a proposal [here](https://www.upwork.com/nx/wm/offer/105213521) in Upwork — please let me know once you accept. Thanks!

@CortneyOfstad ,
@brunovjk  has reviewed the PR as C+.
Offer Accepted, Thanks!

**Comment by CortneyOfstad** [comment] 2024-12-06 16:28
Oops, sorry about that! @brunovjk can you confirm if this needs a regression test? Thanks!

Also, it looks like you need payment as well — going to whip up an Upwork proposal and get that sent over ASAP!

**Comment by brunovjk** [comment] 2024-12-06 16:32
No problem, I was missing that too :D thanks for letting us know @Shahidullah-Muffakir. I'll fill out the BZ checklist in a moment. Thanks @CortneyOfstad

**Comment by CortneyOfstad** [comment] 2024-12-06 16:32
@brunovjk proposal has been sent [here](https://www.upwork.com/nx/wm/offer/105225889)!

**Comment by brunovjk** [comment] 2024-12-06 18:23
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [x] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [x] 3z. Other: Applause - Internal Team

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/39951#discussion_r1873814359

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
### Test:

1. Log in with a new account
2. Complete the onboarding process by selecting `Track and Budget Expenses` in the onboarding flow.
3. Verify the `Take a 2-minute tour` task appears in the `Concierge` chat.

Do we agree 👍 or 👎

**Comment by brunovjk** [comment] 2024-12-06 18:42
All yours @CortneyOfstad :D

**Comment by brunovjk** [comment] 2024-12-06 19:15
I updated the BZ checklist and posted the comment in the aforementioned PR. Thank you @rayane-djouah

**Comment by CortneyOfstad** [comment] 2024-12-09 18:17
## Payment Summary

@brunovjk — paid $250 via Upwork
@Shahidullah-Muffakir — paid $250 via Upwork

## Regression Test

https://github.com/Expensify/Expensify/issues/451766

**Closed by CortneyOfstad** 2024-12-09 18:17 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
