### ISSUE TITLE
Web - After changing the default contact method on "Account A", "Account B" is unable to send messages to the new email address/phone number of "Account A" from "New Chat" option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23731] opened 2023-07-27 12:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to 2 different Expensify accounts (A and B).
2. Start a conversation with each other from the accounts.
3. Open profile of account A from account B, and then change existing photo of the account A from the settings > Profile.
4. You can see the change is async for account B as well (Account B doesn't have to refresh the page to see this change).
5. Now change the Display Name from Account A. This change is also async for Account B.
6. Now change the default contact method of Account A. You'll notice this change is not async on Account B.
7. Now start a "new chat" from account B by searching the new contact method that is created and made as default contact method on "Account A".
8. "Account B" will not be able to send the message to this new contact address, and will show an error.

## Expected Result:
Change of Contact Method should be async as well from the other account, so that error is not encountered.

## Actual Result:
Change of Contact Method of Account A is not async for the Account B. An error is thrown when trying to chat with the new contact method

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**1.3.45-8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

Uploading emailasync_changeError.mov…

https://github.com/Expensify/App/assets/93399543/d0a70cbc-f93e-49eb-9d1b-a28a206c9b14

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priyankrawat
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690385059672679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01181bab56729b3344</li>
        <li>Upwork Job ID: 1685962546946342912</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-07-27 13:33
Commented in thread on this one for the team that worked on [contact methods](https://expensify.slack.com/archives/C049HHMV9SM/p1690464610825129?thread_ts=1690385059.672679&cid=C049HHMV9SM).

**Comment by trjExpensify** [comment] 2023-07-28 14:02
Sounds like @Beamanator or @cristipaval will take this over as it's already known from the [contact methods](https://github.com/Expensify/App/issues/16666) rollout! Confirming who and then I'll get this over internal.

**Comment by trjExpensify** [comment] 2023-07-31 10:35
Assigning to @Beamanator, and popping on `Internal`.

**Comment by marcusthedev** [comment] 2023-07-31 14:23
Hey guys, since the Upwork job has been posted will I get an offer for reporting the bug? Thanks!

**Comment by abdulrahuman5196** [comment] 2023-08-03 16:45
Not overdue. No PR yet.

**Comment by trjExpensify** [comment] 2023-08-07 10:08
@Beamanator / @cristipaval will you guys link the the PR for this here when ready?

**Comment by trjExpensify** [comment] 2023-08-10 21:23
@Beamanator @cristipaval, what's the game plan for this issue? Also, bump [on this](https://github.com/Expensify/App/issues/23731#issuecomment-1658487444).

**Comment by trjExpensify** [comment] 2023-08-14 10:01
Bump on my question. :)

**Comment by trjExpensify** [comment] 2023-08-21 11:26
Same! https://github.com/Expensify/App/issues/23731#issuecomment-1673939210

**Comment by trjExpensify** [comment] 2023-08-30 13:11
Back from OoO, Melv. @Beamanator @cristipaval, I'm a bit unclear on the next steps here with the radio silence? The issue is now breaking WAQ, so it would be good to put forward a path to get this one resolved.

**Comment by Beamanator** [comment] 2023-08-30 15:39
Oof ya sorry for the delay, we've been mega focused on #wave4 / #wave5 and will remain focused on that for the next week & a half at least (both conferences are next week) 

About "Next steps" - we can definitely open this up to "the pool" if we want, but as for right now, most likely neither of us will be able to pick it up till some time during offshore - and even then it's a pretty low priority change i think, so might get bumped out till October haha. Do you agree this is a relatively low priority fix @trjExpensify @cristipaval ?

**Comment by trjExpensify** [comment] 2023-09-04 09:33
@Beamanator bump, does this have to be `internal`?

**Comment by Beamanator** [comment] 2023-09-06 00:41
That's fair that we should address this soon - and yes I agree it most likely needs to be internal - most of our "secondary contact" logic / account lookup is in the backend

**Comment by Beamanator** [comment] 2023-09-11 09:11
I'm not actually sure this is reproducible still, can someone else try? I thinkkkk the issue used to be the fact that there was an existing chat with a different email address, but i think that problem was solved recently ish - when I tried the steps in the OP I couldn't reproduce


https://github.com/Expensify/App/assets/3885503/0b1f3de5-8e71-4d40-ac85-43352d82847f

**Comment by trjExpensify** [comment] 2023-09-11 10:45
I've [asked](https://expensify.slack.com/archives/C049HHMV9SM/p1694429025440929?thread_ts=1690385059.672679&cid=C049HHMV9SM) in the slack thread! :)

**Comment by Beamanator** [comment] 2023-09-14 02:27
Bumped, maybe we can take this to #expensify-open-source to get more eyes?

**Comment by trjExpensify** [comment] 2023-09-18 09:52
@priyankrawat, as we haven't heard back from you for a week I'm going to close this issue. If you can confirm the reproduction on the latest staging build/main, then give us a shout!

**Closed by trjExpensify** 2023-09-18 09:52 UTC
Labels: Daily, Internal, Overdue, Bug
