### ISSUE TITLE
[HOLD for payment 2023-12-20] [DISTANCE] LOW: PHASE 1: Wave 5 CLEANUP Refactor navigation among screens related to money request features

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26538] opened 2023-09-01 22:53 UTC
### Remove deep-linking support for screens related to money request

In the current code, deep linking to the screen for each step of money request flow is allowed.

There are logics to handle deep linking to a screen that corresponds to a step in the middle of the money request flow. These logics are not scalable and adds additional complexity.

Let's remove the support for deep linking. All screens should be under a single URL and all steps should be completed under that URL.

Relevant Slack discussion: https://expensify.slack.com/archives/C01GTK53T8Q/p1692998235169129

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by tgolen** [comment] 2023-09-15 23:49
We had some more discussion about this in https://expensify.slack.com/archives/C05DWUDHVK7/p1694542449982949 and I believe we should actually double-down on the URL based navigation. It has lots of benefits with the navigation flow (back buttons, screen animations, etc.).

Yes, it is pretty flawed and difficult to understand in its current state. I wouldn't mind taking this issue and having a go at cleaning this up so that it's more predictable and easier to use.

**Comment by tgolen** [comment] 2023-09-25 02:58
Two big pieces for this were merged today. I'll keep working on cleanup.

Note to self: Try to remove `ONYXKEYS.IOU`

**Comment by tgolen** [comment] 2023-10-05 15:23
I'm having to temporarily drop this down to weekly as I have had some higher priority things crop up that I needed to address urgently. My general update on this issue is that I'm about 50% done. I have refactored about 90% of the creation flow, and then I need to do a pass on the edit flow (but it should be easier than the creation flow because it was already following better patterns).

**Comment by tgolen** [comment] 2023-10-05 22:20
I got back to working on this today. I made some good progress for trying to get the confirmation step cleaned up but I'm running into a low-level Onyx error that is causing participants to not be stored in Onyx. I posted about it [here](https://expensify.slack.com/archives/C035J5C9FAP/p1696544350159339?thread_ts=1693594227.145039&cid=C035J5C9FAP) in Slack, but need to keep digging into that.

**Comment by tgolen** [comment] 2023-10-06 21:49
I made really good progress on this today. I've got all the screens built for the create request flow. The next part of this is completing the confirmation step (the part that actually creates the requests). Once that is done, then I'll need to go through and find some scattered `TODO:` items and get them taken care of. Lastly, I'll need to go through the old components to ensure nothing has been added to them during development. 

ETA is end of next week to have a PR ready for this.

**Comment by tgolen** [comment] 2023-10-09 17:35
I approached this refactoring in a way to reduce conflicts. My idea was to essentially make as few changes to existing code as possible while building the new flow from scratch (copying code from the original components). This results in essentially a 100% duplicated flow. Once the two existing flow exist side-by-side, the original flow and files will be removed and they will be audited to ensure any changes since they were originally copied are incorporated into the new files.

I am creating a second issue for this final cleanup: https://github.com/Expensify/App/issues/29107

**Comment by tgolen** [comment] 2023-10-09 17:44
Tasks remaining to be done:

- Finish the confirmation flow (where the requests actually get created)
- Search through code for some straggling TODOs
- Make sure the billable flag gets addressed
- See about moving the NotFound component higher in the view heirarchy

**Comment by tgolen** [comment] 2023-10-09 22:04
Today I:
- got a majority of the straggling TODOs done
- [Posted in Slack](https://expensify.slack.com/archives/C02MW39LT9N/p1696865805270169) about the billable flag
- started on finishing the confirmation flow.

Tasks remaining to be done:
- Finish the confirmation flow (where the requests actually get created)
    - Scan flow
    - ~Distance flow~ 
    - Split flow
    - Split bill flow
    - Manual flow
- Search through code for some straggling TODOs
- Make sure the billable flag gets addressed
- See about moving the NotFound component higher in the view heirarchy
- Test receipt upload in native

**Comment by tgolen** [comment] 2023-10-10 20:50
Today I:
- Wrapped up the confirmation flow for everything
- Addressed all straggler TODOs (including a few others I have nothing to do with)
- Ensured the billable flag works
- Ensured that smartscan works on native
- Made sure the NotFound component is higher up in the view hierarchy

Final things left to do:
- Get PR fully ready for review and do final testing (I'll do that tomorrow)

**Comment by tgolen** [comment] 2023-10-11 20:09
Today I was trying to get the PR _mostly_ ready for review and I got all the components updated with what's in `main`. I then ran into issues with `npm i` failing and `pod install` failing, so I was unable to move into the testing phase. I'll dig into those tomorrow.

**Comment by tgolen** [comment] 2023-10-12 22:17
OK, I finished my local testing today on all platforms 🎉 and I've moved the PR out of draft so it can begin to be reviewed.

**Comment by tgolen** [comment] 2023-10-16 21:18
I had a discussion with @mountiny and @luacmartins and I'm taking a bit of a different approach to getting this PR merged. It seems that it's going to cause a lot of headaches with Money 2020 next week, so we agreed to hold on the majority of the refactor pieces. In the meantime, I am splitting off smaller PRs from it that will be easier to review and merge in isolation without as big of a risk of causing regressions. I created the first PR for that today: https://github.com/Expensify/App/pull/29696

**Comment by tgolen** [comment] 2023-10-18 22:21
Split out these PRs yesterday:
- https://github.com/Expensify/App/pull/29813

Split out these PRs today:
- https://github.com/Expensify/App/pull/29887
- https://github.com/Expensify/App/pull/29880
- https://github.com/Expensify/App/pull/29876

**Comment by tgolen** [comment] 2023-10-20 20:52
I'm adding an official HOLD to the title. There was at least one more PR that I could split out from this refactoring, and I should hopefully be able to get to it next week.

**Comment by neil-marcellini** [comment] 2023-10-25 22:46
Money202 is over tomorrow, removing the HOLD

**Comment by tgolen** [comment] 2023-11-01 17:13
Pushing this back to daily now that the HOLD is removed.

**Comment by tgolen** [comment] 2023-11-06 16:15
I'm planning to work on more testing today. I found that the participants screen wasn't working with splits properly. It should be ready by the EOD today if all goes well.

**Comment by tgolen** [comment] 2023-11-06 21:28
[The PR](https://github.com/Expensify/App/pull/28618) is ready for review now and I'm taking it out of draft and added some tips for reviewing it.

**Comment by tgolen** [comment] 2023-11-08 23:02
The PR is actively being reviewed and testing. I have one bug that I was not able to look into today. That's where I will pick back up on tomorrow.

**Comment by tgolen** [comment] 2023-11-15 14:40
I'm moving this back to daily to reflect my current priority.

**Comment by tgolen** [comment] 2023-11-16 16:23
Today I am getting the PR ready to create an ad-hoc build for Applause to start regression testing.

**Comment by dylanexpensify** [comment] 2023-11-21 20:35
Looks like we got Web-E merged and on prod!!

**Comment by tgolen** [comment] 2023-11-27 16:56
Lots of testing happened on this last week and 22 bugs have been reported so far. Applause hasn't been able to test on desktop yet with the builds failing. I'll start tackling these today and also solving all the conflicts.

**Comment by tgolen** [comment] 2023-11-27 17:44
- [ ] [Expense - App crashes when opening Category list in confirmation page ](https://github.com/Expensify/App/pull/28618#issuecomment-1816801720)
- [ ] [Expense - 'Amount' header disappears after selecting currency in confirmation page](https://github.com/Expensify/App/pull/28618#issuecomment-1816805031)
- [ ] [Expense - Previously entered amount is not preserved after changing currency](https://github.com/Expensify/App/pull/28618#issuecomment-1824765990)
- [ ] [Expense - Future dates are not disabled and user can select it](https://github.com/Expensify/App/pull/28618#issuecomment-1824768199)
- [ ] [Expense - Missing header in Add receipt modal](https://github.com/Expensify/App/pull/28618#issuecomment-1824770628)
- [ ] [Expense - Description input field does not expand when adding multiline text](https://github.com/Expensify/App/pull/28618#issuecomment-1824773907)
- [ ] [Expense - Opening IOU preview in IOU report page redirects user back to the main chat](https://github.com/Expensify/App/pull/28618#issuecomment-1824776162)
- [ ] [Distance - RHP flashes after entering addresses that have no route](https://github.com/Expensify/App/pull/28618#issuecomment-1824777860)
- [ ] [Scan - Scan page is loading infinitely](https://github.com/Expensify/App/pull/28618#issuecomment-1824783919)
- [ ] [Distance - iou.error.duplicateWaypointsErrorMessage when proceeding with same waypoints](https://github.com/Expensify/App/pull/28618#issuecomment-1824784736)
- [ ] [Distance - Addresses in Recent destinations show one-line format](https://github.com/Expensify/App/pull/28618#issuecomment-1824785908)
- [ ] [Request - User is redirected to participant selection page after adding a receipt](https://github.com/Expensify/App/pull/28618#issuecomment-1824788253)
- [ ] [Request-App crashes after adding a receipt when requesting money with user with existing IOU](https://github.com/Expensify/App/pull/28618#issuecomment-1824790520)
- [ ] [Request Money - Tag is not being deselected](https://github.com/Expensify/App/pull/28618#issuecomment-1824797444)
- [ ] [Request – “Hmm... it's not here” appears when reload WS (from OD) page as Admin](https://github.com/Expensify/App/pull/28618#issuecomment-1824823713)
- [ ] [Send money - Send money in 1:1 DM opens Request money RHP](https://github.com/Expensify/App/pull/28618#issuecomment-1824860423)
- [ ] [IOU - To field is empty and Amount is $NaN when opening confirmation page in another tab](https://github.com/Expensify/App/pull/28618#issuecomment-1824861670)
- [ ] [Request – User can drag & drop file on the Distance page. The map does not load.](https://github.com/Expensify/App/pull/28618#issuecomment-1826061998)
- [ ] [Android - Scan Request - Black screen is shown on camera view](https://github.com/Expensify/App/pull/28618#issuecomment-1826082091)
- [ ] [Distance - Unable to delete a waypoint](https://github.com/Expensify/App/pull/28618#issuecomment-1826084751)
- [ ] [Web - Request money - The map is not loaded when creating a distance request](https://github.com/Expensify/App/pull/28618#issuecomment-1826190134)
- [ ] [Distance - Red dot briefly appears next to Amount in distance details page](https://github.com/Expensify/App/pull/28618#issuecomment-1826388214)

**Comment by tgolen** [comment] 2023-11-27 22:39
I was able to make it through about half of these today. Gonna keep the gas pedal down tomorrow and keep working through them.

**Comment by tgolen** [comment] 2023-11-28 22:59
I made some good progress on this. Only three bugs left to go!

**Comment by kbecciv** [comment] 2023-12-04 22:46
Summary of retest:
https://github.com/Expensify/App/pull/28618#issuecomment-1826084751 is fixed

**Comment by kbecciv** [comment] 2023-12-05 14:07
@tgolen 
**Re-testing Summary:**

https://github.com/Expensify/App/pull/28618#issuecomment-1826084751 is fixed
https://github.com/Expensify/App/pull/28618#issuecomment-1816801720 is fixed
https://github.com/Expensify/App/pull/28618#issuecomment-1816805031 is fixed
https://github.com/Expensify/App/pull/28618#issuecomment-1824765990 is fixed
https://github.com/Expensify/App/pull/28618#issuecomment-1824768199 is NOT fixed, still reproducible
https://github.com/Expensify/App/pull/28618#issuecomment-1824797444 is fixed
https://github.com/Expensify/App/pull/28618#issuecomment-1824770628 is fixed
https://github.com/Expensify/App/pull/28618#issuecomment-1824773907 is fixed
https://github.com/Expensify/App/pull/28618#issuecomment-1824776162 is NOT fixed, still reproducible
https://github.com/Expensify/App/pull/28618#issuecomment-1824777860 is fixed
https://github.com/Expensify/App/pull/28618#issuecomment-1824783919 is NOT fixed, still reproducible
https://github.com/Expensify/App/pull/28618#issuecomment-1824785908 is fixed
https://github.com/Expensify/App/pull/28618#issuecomment-1824784736 is fixed
https://github.com/Expensify/App/pull/28618#issuecomment-1824790520 is fixed
https://github.com/Expensify/App/pull/28618#issuecomment-1824788253 is fixed
https://github.com/Expensify/App/pull/28618#issuecomment-1824823713 is NOT fixed, still reproducible
https://github.com/Expensify/App/pull/28618#issuecomment-1826082091, app is crashing after selecting WS - should we create an issue for this?
https://github.com/Expensify/App/pull/28618#issuecomment-1826190134 is NOT fixed, still reproducible
https://github.com/Expensify/App/pull/28618#issuecomment-1826388214 is fixed

**Comment by kbecciv** [comment] 2023-12-05 14:09
@tgolen Also, seeing RHP tab button background colour is wrong, should we create an issue for this?
![image](https://github.com/Expensify/App/assets/93399543/268f707b-163b-4d94-b5ec-0f03bf8f1f01)

**Comment by tgolen** [comment] 2023-12-05 20:14
@kbecciv I had a look through the remaining bugs and here are my results. I still had some issues reproducing some of them, but I think we are in really good shape. I've triggered another ad-hoc build on the PR to ensure there is a build with the most recent changes.

# Resolved
- [Scan - Scan page is loading infinitely](https://github.com/Expensify/App/pull/28618#issuecomment-1824783919) - Fixed
- [Expense - Future dates are not disabled and user can select it](https://github.com/Expensify/App/pull/28618#issuecomment-1824768199) Working as designed. This is a known change in behavior that was requested.
- [Web - Request money - The map is not loaded when creating a distance request](https://github.com/Expensify/App/pull/28618#issuecomment-1826190134)  This is [a known issue](https://github.com/Expensify/App/issues/31665#top)

# Unresolved
- [Expense - Opening IOU preview in IOU report page redirects user back to the main chat](https://github.com/Expensify/App/pull/28618#issuecomment-1824776162). I am not able to reproduce this. Can you please be sure this is reproducible on the latest ad-hoc build and if it's still reproducible, can you upload a video of it to ensure I am trying to reproduce it properly? Also, does it happen if you wait for the network request to complete, or does it only happen if you access the preview before the network request is finished?
- [Request – “Hmm... it's not here” appears when reload WS (from OD) page as Admin](https://github.com/Expensify/App/pull/28618#issuecomment-1824823713) I am not able to reproduce this. I had some confusion about the steps and exactly which reports to access and refresh. Unfortunately, the video that was posted won't fully play for me so I can't properly the flow that's happening. This is a very minor flow and bug. Can you please open a new GH for this and assign it to me so that I can look into it further after this PR is merged?
- [Android - Scan Request - Black screen is shown on camera view](https://github.com/Expensify/App/pull/28618#issuecomment-1826082091) I was not able to reproduce this with my emulator when accessing a workspace chat. Can you please double-check the reproduction steps? Do you know if it only happens with a physical device? @jjcoffee could you try to reproduce this and see what you think?
- [Also, seeing RHP tab button background colour is wrong](https://github.com/Expensify/App/issues/26538#issuecomment-1840865247) I am not able to reproduce this. This looks correct, doesn't it? Is this not what you're seeing on the ad-hoc build?

![image](https://github.com/Expensify/App/assets/1228807/4da61225-0f99-4f6a-b32f-dc1aa9c9623f)

- [Error shown: Split bill is only allowed between a single workspace or individual users...](https://github.com/Expensify/App/pull/28618#issuecomment-1816702786) @jjcoffee I cannot reproduce this. Are you sure it's happening after I fixed this https://github.com/Expensify/App/pull/28618/commits/8d14eff5a19d927ca9fd3311d11e2045e833baec ? I think that fix should solve the problem you're seeing. If you can still reproduce this, please upload a video of it so I can be sure I am reproducing it the same way you are. Here you can see my attempt to reproduce it:


https://github.com/Expensify/App/assets/1228807/39dd9056-6541-44fe-86a5-113d659804be

**Comment by tgolen** [comment] 2023-12-07 16:36
bump @jjcoffee and @kbecciv

**Comment by kbecciv** [comment] 2023-12-07 17:34
@tgolen Could you please share the latest build? I will work on the above issues.

**Comment by kbecciv** [comment] 2023-12-07 17:41
Is this correct build to re-test  https://github.com/Expensify/App/pull/28618#issuecomment-1841478938? @tgolen

**Comment by tgolen** [comment] 2023-12-07 17:59
Yep, that's the right one. 👍

**Comment by kbecciv** [comment] 2023-12-07 19:30
**https://github.com/Expensify/App/pull/28618#issuecomment-1824776162** is still reproducible, try selecting a user you have never chatted with before and request money.

https://github.com/Expensify/App/assets/93399543/591074b2-331b-4ece-b210-126e6b0c7b7b

**https://github.com/Expensify/App/pull/28618#issuecomment-1824823713** is still reproducible. I'm able to reproduce the issue by simply opening any IOU and refreshing the page.

https://github.com/Expensify/App/assets/93399543/0e45ae33-8ba6-4c43-950f-8d724d43aacd

https://github.com/Expensify/App/assets/93399543/6c8ec914-6d25-422d-82dc-f31a1703d85d

**https://github.com/Expensify/App/pull/28618#issuecomment-1826082091** is Fixed!

https://github.com/Expensify/App/assets/93399543/14e5a57d-f8b0-4e85-a685-4a94d673a191

**https://github.com/Expensify/App/issues/26538#issuecomment-1840865247** is fixed!

![image](https://github.com/Expensify/App/assets/93399543/9b430d4e-d8f9-48cd-bd30-0c04cd828fbf)

**Comment by tgolen** [comment] 2023-12-07 20:53
Thank you! Those are helpful tips. I'll look into them.

**Comment by tgolen** [comment] 2023-12-12 16:04
We are churning through the blockers as they come up!

**Comment by jjcoffee** [comment] 2023-12-13 12:28
@tgolen Could you assign me here and add the `Bug` label so a BZ is assigned too for eventual payment? Thanks!

**Comment by tgolen** [comment] 2023-12-18 19:59
We're good here 😅 

Just waiting for this to wrap up and get paid out.

**Comment by tgolen** [comment] 2023-12-26 16:08
Still waiting for @anmurali to pay this out.

**Comment by jjcoffee** [comment] 2024-01-02 10:26
@anmurali Happy New Year! Just a friendly bump for payment :bow:

**Comment by anmurali** [comment] 2024-01-02 23:38
https://www.upwork.com/nx/wm/offer/100268863

**Comment by jjcoffee** [comment] 2024-01-03 08:32
@anmurali Accepted the offer, thanks!

**Comment by anmurali** [comment] 2024-01-10 02:50
Paid.

**Closed by anmurali** 2024-01-10 02:50 UTC
Labels: Daily, Overdue, Awaiting Payment, Plane, Bug, Distance
