### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] A "New Messages" notification is shown when there is no new message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30359] opened 2023-10-25 16:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698164387186969

## Action Performed:
1. Open any chat
2. Have enough messages on the chat, so you are able to scroll
3. Mark the last message as unread
3. Start scrolling up and see that the New Messages notification appears
4. Delete the last message
5. Start scrolling up and Notice that New Messages notification is shown
## Expected Result:
"New Messages" notification is not shown when there is no new message
## Actual Result:
A "New Messages" notification is shown when there is no new message
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/84fcab6e-22d7-43c8-8b8d-14ef7538f625

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/22e3f32c-e1d7-40be-8732-ebbe0beea8e7

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/c90d0ca0-e47f-4216-9e8a-ae8b12a3ffa9

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/b7070842-118e-485a-b006-b824ec267e0f

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/52cf7c6c-5867-4305-85a6-1fe8354cb897

https://github.com/Expensify/App/assets/38435837/4d0607dc-e952-4a78-9a4f-30301ee4811f

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/3c2e9c34-1988-450f-8a18-67f7106151e7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013619be7f4c5f8ab1</li>
        <li>Upwork Job ID: 1717212725821657088</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-10-25 16:21
# issue_01

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The "New Messages" notification is shown even after all the new messages are deleted

### What is the root cause of that problem?

We are setting the `currentUnreadMarker` when `reportActions` or `report.lastReadTime` is changed
https://github.com/Expensify/App/blob/38d647e174acb502e2fae1494faf1c0d9d59e792/src/pages/home/report/ReportActionsList.js#L318-L330
When marking a message unread, the reportActionID of the message is set to `currentUnreadMarker`.
When removing the message after that, we don't set `null` to `currentUnreadMarker` as you can see. So the `currentUnreadMarker` would have the old value even after the message is deleted

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to set `null` to `currentUnreadMarker` if there is no new messages
Update the above useEffect callback function
```
        let markerFound = false;
        _.each(sortedReportActions, (reportAction, index) => {
            if (!shouldDisplayNewMarker(reportAction, index)) {
                return;
            }
            markerFound = true;
            if (!currentUnreadMarker && currentUnreadMarker !== reportAction.reportActionID) {
                setCurrentUnreadMarker(reportAction.reportActionID);
            }
        });

        if (!markerFound) {
            setCurrentUnreadMarker(null);
        }
```

This works as expected

<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)

**Comment by ArekChr** [comment] 2023-10-26 10:36
@s-alves10 What if another user deletes a new message when the current user has opened a report with the new message? I think this could not be handled case, but it is a very similar scenario

**Comment by s-alves10** [comment] 2023-10-26 10:41
then reportActions would change by pusher event and the effect callback will be called. I guess the notification message would disappear. I'll test it shortly

**Comment by s-alves10** [comment] 2023-10-26 10:50
@ArekChr 

I just tested the case you mentioned and the 'New messages' notification disappears when the other user deletes the new message

**Comment by ArekChr** [comment] 2023-10-26 11:31
Great @s-alves10! We can go with your [solution](https://github.com/Expensify/App/issues/30359#issuecomment-1779632727).

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by s-alves10** [comment] 2023-10-27 09:22
@ArekChr 

PR is ready for review https://github.com/Expensify/App/pull/30485

**Comment by alexpensify** [comment] 2023-11-01 18:46
Looks like the PR is merged, waiting for automation here.

**Comment by situchan** [comment] 2023-11-02 13:35
As this caused regression, I suggest to revert [PR](https://github.com/Expensify/App/pull/30485) and just close the issue as dupe of #22174 which is on hold for #25935.
cc: @MonilBhavsar

**Comment by s-alves10** [comment] 2023-11-02 16:00
@situchan 

Will you please explain why this caused the regression?

**Comment by situchan** [comment] 2023-11-02 16:07
@s-alves10 I am not able to reproduce https://github.com/Expensify/App/issues/30696after reverting https://github.com/Expensify/App/pull/30485 locally.

**Comment by s-alves10** [comment] 2023-11-02 16:12
@situchan 

Will you check the changes in this PR? It has a clear logic and I think it has any side-effect.

By the way, here is my question. When deleting a unread message, the new line marker should move to the next message? Unread marker means all the messages after that are unread, I think

**Comment by s-alves10** [comment] 2023-11-02 16:18
@situchan 

I'm finding the root cause of https://github.com/Expensify/App/issues/30696. Please give me a try

**Comment by alexpensify** [comment] 2023-11-09 00:11
Reassigning another team member, I'm going OOO until Tuesday, November 14, and will take it back if it's still open by my return date.

@sonialiap  - Required action from the team: 

This payment is on hold due to regression. Can you please keep an eye out and make sure that we are making progress to address the issue and can prepare for a new payment date? Thanks!

**Comment by madmax330** [comment] 2023-11-13 09:40
@s-alves10 any news?

**Comment by s-alves10** [comment] 2023-11-14 07:09
I don't think this causes a regression. Please check https://github.com/Expensify/App/issues/30696#issuecomment-1791243687

**Comment by alexpensify** [comment] 2023-11-15 00:48
@sonialiap - I'm back online and will take it from here. 

--- 

@madmax330 or @ArekChr - can you please confirm if you agree that this update didn't cause a regression? Also, @ArekChr please complete the checklist https://github.com/Expensify/App/issues/30359#issuecomment-1790409845. I want to complete the payment process this week. Thanks!

**Comment by ArekChr** [comment] 2023-11-15 11:39
- [x] Determine if we should create a regression test for this bug. I think this green marker is important to have a regression test for this scenario:

**Regression test proposal**

1. Open any chat with many messages so you can scroll them.
2. Mark the last message as unread.
3. Start scrolling up and see that the "New Messages" notification appears.
4. Delete the last unread message.
6. Verify that the "New Messages" notification disappeared after scrolling them.

Do we agree :+1: or :-1:

**Comment by ArekChr** [comment] 2023-11-15 11:42
I attempted to reproduce the issue mentioned, but I encountered a different problem which prevented me from doing so. Specifically, I could not delete messages due to new issues related to the action bar. @s-alves10 Did you find the root cause of 30359?

**Comment by s-alves10** [comment] 2023-11-15 11:46
@ArekChr 

What do you mean by root cause of 30359? You mean the root cause of this issue?

**Comment by ArekChr** [comment] 2023-11-15 11:55
> @situchan
> 
> I'm finding the root cause of #30696. Please give me a try

@s-alves10 I regard to this message

**Comment by alexpensify** [comment] 2023-11-16 23:37
@ArekChr - to confirm, is the issue you faced due to regression from this issue or something else? I'm trying to see if we can close this issue and carry on with the payment process tomorrow. Thanks!

**Comment by ArekChr** [comment] 2023-11-17 09:35
@alexpensify After looking at the @s-alves10 investigation. It looks like this issue doesn't introduce regression. We can close the issue and move forward with the payment process.

**Comment by situchan** [comment] 2023-11-17 09:44
Agree not regression and not affect payment but https://github.com/Expensify/App/issues/30696 should be handled follow-up as part of this issue because that issue was raised up after merging this PR.

**Comment by alexpensify** [comment] 2023-11-18 16:44
Here is the payment summary: 

-  External issue reporter @daveSeife $50 
-  Contributor that fixed the issue @s-alves10 $500
-  Contributor+ that helped on the issue and/or PR @ArekChr paid via vendor 

Upwork Job: https://www.upwork.com/jobs/~013619be7f4c5f8ab1

Extra Notes regarding payment: No bonus, the PR was created after the notification period.

**Comment by alexpensify** [comment] 2023-11-18 16:51
@s-alves10 - please accept in Upwork and I can complete this process. Thanks!

**Comment by s-alves10** [comment] 2023-11-18 16:58
@alexpensify 

Offer accepted. Thanks

**Comment by alexpensify** [comment] 2023-11-18 18:58
Awesome! Great work, and thanks for your patience as we sorted if there was regression here. I've paid everyone in Upwork and closed the job. Now, I'm going to close this GH too.

**Closed by alexpensify** 2023-11-18 18:58 UTC
Labels: External, Daily, Awaiting Payment, Bug
