### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] Desktop - Task - Error occurs when update long content for task description for second time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42660] opened 2024-05-27 19:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/21450&group_by=cases:section_id&group_order=asc&group_id=291935
**Email or phone of affected tester (no customers):** crowdtest.expensify+admin@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app
2. Start group chat with another user
3. Create a task for this user without a description
4. Update description with long content + emoji (Can use in attachment)
5. Observe the error message of the app show
6. Update this content to description one more time

## Expected Result:
 The error of the app shows, warning the user because the content too long

## Actual Result:
The error occurs when updating long content for the task description for a second time, after that user can't update the description or task name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/91dacaec-e902-4660-8c54-b3fed216256e

<img width="1920" alt="Bug6493142_1716830309579!Screenshot_2024-05-28_at_00 18 16" src="https://github.com/Expensify/App/assets/78819774/9b1b959d-6a08-4940-b1cf-5a866d35afde">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011028270f108dc08b</li>
        <li>Upwork Job ID: 1795195550390841344</li>
        <li>Last Price Increase: 2024-06-03</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 102597496</li>
<li>samilabud | Contributor | 102597500</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @carlosmiceli / @adelekennedy</details>

**Comment by lanitochka17** [comment] 2024-05-27 19:34
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-27 19:35
We think that this bug might be related to #vip-vsp

**Comment by neonbhai** [comment] 2024-05-27 20:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - Error occurs when update long content for task description for second time

### What is the root cause of that problem?
We don't remove the optimistic message if an error occurs, this interfers with get older report action calls since the current report action does not exist in server.

### What changes do you think we should make in order to solve the problem?
We should update `failureData` here to set the optimistic message's reportActionID to `null`

https://github.com/Expensify/App/blob/c22945ac78471e0a6265a0181e8689221890c9df/src/libs/actions/Task.ts#L489

```jsx
value: {[editTaskReportAction.reportActionID]: null},
```

**Comment by samilabud** [comment] 2024-05-27 22:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Edited Task - Error occurs when description content exceed the 500 characters after parsed as html.

### What is the root cause of that problem?
This error occurs when description content exceed the 500 characters after parsed as html in [buildOptimisticEditedTaskFielReportAction](https://github.com/Expensify/App/blob/63a20f4b3232809f4d9441b3e4ab60180ff591ae/src/libs/actions/Task.ts#L443), when we parse the description to HTML format using `getParsedComment()`. This happens because we validate the limit of 500 characters when it is single text strings, but we send it to the server after parsed, we notice the error when we are near the limit of 500 and the `getParsedComment()` returns converted the lines breaks to `<br />`, because this increase the text 5 characters for every line break. 

<details>
<summary>Technical explanation</summary>

**In other words we validate the text has a max length of 500 characters, ie, the next text has 493 characters:**

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent placerat consectetur enim sit amet sodales. Etiam elementum, lorem id sollicitudin dignissim, quam nibh sodales arcu, imperdiet consequat risus mi sit amet lorem. Donec iaculis at tortor eget vulputate. Duis dignissim non diam id mattis. Suspendisse sit amet consequat elit, feugiat mattis libero. In hendrerit dui ac ante hendrerit condimentum nec

ddddDonec tellus odio, tristique non hendrerit quis, scelerisque placerat odio.

**But this is converted to (505 characters):**

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent placerat consectetur enim sit amet sodales. Etiam elementum, lorem id sollicitudin dignissim, quam nibh sodales arcu, imperdiet consequat risus mi sit amet lorem. Donec iaculis at tortor eget vulputate. Duis dignissim non diam id mattis. Suspendisse sit amet consequat elit, feugiat mattis libero. In hendrerit dui ac ante hendrerit condimentum nec<br /><br />ddddDonec tellus odio, tristique non hendrerit quis, scelerisque placerat odio.

</details>


### What changes do you think we should make in order to solve the problem?
We can validate the parsed description max length instead of the plain text here:

https://github.com/Expensify/App/blob/63a20f4b3232809f4d9441b3e4ab60180ff591ae/src/pages/tasks/TaskDescriptionPage.tsx#L41-L43

Like:
```
const validate = useCallback((values: FormOnyxValues<typeof ONYXKEYS.FORMS.EDIT_TASK_FORM>): FormInputErrors<typeof ONYXKEYS.FORMS.EDIT_TASK_FORM> => {
        const errors = {};
        const parsedDescription = ReportUtils.getParsedComment(values?.description);

        if (parsedDescription && parsedDescription?.length > CONST.DESCRIPTION_LIMIT) {
            ErrorUtils.addErrorMessage(errors, 'description', ['common.error.characterLimitExceedCounter', {length: values.description.length, limit: CONST.DESCRIPTION_LIMIT}]);
        }

        return errors;
    }, []);
```
<details>
<summary>Test:</summary>

https://github.com/Expensify/App/assets/5216036/2e4dd422-b61c-460a-b421-a3da4dd7e91b


</details>



### What alternative solutions did you explore?
We can remove the [ReportUtils.getParsedComment(description)](https://github.com/Expensify/App/blob/63a20f4b3232809f4d9441b3e4ab60180ff591ae/src/libs/actions/Task.ts#L443) and let the description as a plain text.

**Comment by bfitzexpensify** [comment] 2024-05-30 17:12
Adding a second BZ team member to keep an eye on this while I'm ooo until June 11th. 

Current status: proposal review.

**Comment by adelekennedy** [comment] 2024-06-03 18:33
@abdulrahuman5196 there are three proposals to review - will you be able to check them out today?

**Comment by abdulrahuman5196** [comment] 2024-06-04 16:41
hi will check on this today

**Comment by abdulrahuman5196** [comment] 2024-06-04 18:56
@samilabud 's proposal addresses the root cause of html text length mismatch since we use length of the plain text for comparison.

@neonbhai 's proposal should remove the new optimistic task action, but I think the solution should be fixing the html text length mismatch which would fix the issue at root. This could be considered as a extended fix but not the core fix.

@tienifr's proposal seems to be a improved combination of the both, so I don't think I can value it as a separate proposal.

**Comment by abdulrahuman5196** [comment] 2024-06-04 19:00
@samilabud 's proposal here https://github.com/Expensify/App/issues/42660#issuecomment-2134121508 looks good and works well. 

🎀 👀 🎀
C+ Reviewed

**Comment by samilabud** [comment] 2024-06-05 01:00
Hi everyone, the PR is ready to review https://github.com/Expensify/App/pull/43084

**Comment by carlosmiceli** [comment] 2024-06-28 18:35
Checking now to see what happened with the PR review.

**Comment by carlosmiceli** [comment] 2024-07-22 19:40
Seems like the PR hasn't been properly reviewed for some reason. Will move back to weekly because seems like we're close to a solution. cc @mallenexpensify not sure if it's a good idea or not to bring you in here, feel free to tell me if I should handle this differently 🙏

**Comment by abdulrahuman5196** [comment] 2024-07-22 19:42
Hi, @carlosmiceli  sorry for the delay. Working on the review. Will close out in a day

**Comment by carlosmiceli** [comment] 2024-07-29 20:39
Small bump @abdulrahuman5196 👋

**Comment by bondydaa** [comment] 2024-07-30 14:43
this regression was created after the associated PR was deployed to staging https://github.com/Expensify/App/issues/46447

I'm removing the deploy blocker b/c I think this was done intentionally so we either need to update test steps or change the behavior but i'll leave that up to you to sort out.

**Comment by carlosmiceli** [comment] 2024-08-01 23:37
@bondydaa What do you mean by updating the test steps?

**Comment by bondydaa** [comment] 2024-08-02 14:31
regression test steps

**Comment by carlosmiceli** [comment] 2024-08-02 22:49
[These](https://expensify.testrail.io/index.php?/tests/view/4576474&group_by=cases:section_id&group_order=asc&group_id=317485&group_by=cases:section_id&group_order=asc&group_id=317485) test steps here? Update them so that they make sure to maintain the description <500 chars? Sorry for the annoying questions but wanna make sure I do it right, first time logging into TestRail 😅 

<img width="988" alt="Screenshot 2024-08-02 at 7 48 15 PM" src="https://github.com/user-attachments/assets/4432420f-aea2-458b-aceb-6ab927786fbf">

**Comment by mallenexpensify** [comment] 2024-08-06 23:55
@carlosmiceli , @abdulrahuman5196, the C+, is responsible for proposing regression test steps, then the QA team will decide where to create them, if needed

**Comment by carlosmiceli** [comment] 2024-08-07 01:07
@mallenexpensify great, thanks for letting us know! Will cross this off my list of pending things then.

**Comment by adelekennedy** [comment] 2024-08-08 06:16
Payments have been made -we're just waiting for the regression test steps @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2024-08-08 12:15
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression IMO

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Start group chat with another user
2) Create a task for this user without a description
3) Update description with long content + emoji
4) Observe the error message of the app show
5) Update this content to description one more time

@adelekennedy I haven't received payment for this. And I am getting paid in newDot. Thank you.

**Comment by adelekennedy** [comment] 2024-08-08 20:29
@abdulrahuman5196 that's my bad - I see that you ended the contract vs us closing and paying out 

**Payouts due:**
- [ ] Contributor+: $250 @abdulrahuman5196 NewDot

**Comment by adelekennedy** [comment] 2024-08-08 20:35
https://github.com/Expensify/Expensify/issues/new?assignees=applausebot&labels=QA%2C+Weekly&template=AddOrUpdateQATests_TEMPLATE.md&title=QA+-+Add%2FUpdate+test+to+TestRail

**Comment by abdulrahuman5196** [comment] 2024-08-29 17:26
Payment is still pending on this issue.

**Comment by adelekennedy** [comment] 2024-08-30 22:35
<img width="1204" alt="Screenshot 2024-08-30 at 3 34 40 PM" src="https://github.com/user-attachments/assets/2dec1f83-3be8-453c-9cf3-7370423c50bb">

is it @abdulrahuman5196? This is what I see on my end from Upwork that the payment has been remitted

**Comment by abdulrahuman5196** [comment] 2024-08-30 23:11
@adelekennedy I closed the contract before because I am getting paid via newDot now 😅

**Comment by adelekennedy** [comment] 2024-08-30 23:25
🤦‍♀️ 

Payouts due:

- [ ] Contributor+: $250 @abdulrahuman5196 NewDot

**Comment by mallenexpensify** [comment] 2024-08-30 23:29
@abdulrahuman5196 , can you please cancel your NewDot payment request!  I've paid you via Upwork.  You were assigned to this issue before your eligibility date.  Thx

**Comment by abdulrahuman5196** [comment] 2024-08-31 05:46
Ok. Deleted the newDot expense. Thank you for payment.

**Comment by abdulrahuman5196** [comment] 2024-09-02 19:17
We can close this issue @adelekennedy

**Closed** 2024-09-02 22:56 UTC
Labels: External, Daily, Awaiting Payment, Bug
