### ISSUE TITLE
[HOLD for payment 2024-03-13] Incorrect spacing and border radius on receipt thumbnail

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33979] opened 2024-01-04 18:58 UTC
___
### DESIGN UPDATES
___
So this is what I'm thinking we should do for the preview cards. As an outline, here is what we have ([Figma file](https://www.figma.com/file/WlrZyRCTQ0LFoKcjSmtTsd/General-UI-Patterns?type=design&node-id=3137%3A698&mode=design&t=mKdkt0kIqZSM6M3T-1) so you can inspect):
![CleanShot 2024-01-05 at 11 05 44@2x](https://github.com/Expensify/App/assets/2319350/03e68a3d-653b-4faa-a147-7d1fdbabcb4b)

I'm thinking of this preview component as two parts:
- upper receipt area
- lower information area

![CleanShot 2024-01-05 at 11 09 43@2x](https://github.com/Expensify/App/assets/2319350/8da4fd4b-fac1-4a55-ba49-3e198eded440)

When a receipt is present, I have it so that the upper receipt area and the lower info area overlap by -4px, which basically accounts for that inner border stroke (4px) of the receipt area not adding to the height of the lower info area.
![CleanShot 2024-01-05 at 11 06 45@2x](https://github.com/Expensify/App/assets/2319350/8046ad23-0d7c-46cc-9b37-ac32c43a30fa)

The upper receipt area has a border radius of 16px:
![CleanShot 2024-01-05 at 11 11 13@2x](https://github.com/Expensify/App/assets/2319350/d40a0ddf-7c24-4a1d-9548-2f6e88762949)

And that means the inner receipt area there has a border radius of 12px (16px minus the 4px border):
![CleanShot 2024-01-05 at 11 11 49@2x](https://github.com/Expensify/App/assets/2319350/0c13b097-8bb4-4c1e-8af8-c188dc773cee)

For the bottom info area, the whole thing has a padding of 16px (vertically and horizontally):
![CleanShot 2024-01-05 at 11 12 16@2x](https://github.com/Expensify/App/assets/2319350/0240eecb-0aaf-4edc-8178-2cc380883e80)

The eyebrow part (`XXXX owes:`) should use our `label` font size, with a line height of 16px. It's in our text supporting color.
![CleanShot 2024-01-05 at 11 12 47@2x](https://github.com/Expensify/App/assets/2319350/d22562d0-8d39-4032-b71b-2f2efe31d59a)

The amount is good as it is, which is our h2 size. The merchant/description line below should use our normal text size and use our text supporting color. It should have a line height of 20px. 

In terms of spacing, I'm thinking it goes:
- Eyebrow/top line
- 8px gap
- Amount
- 4px gap
- Merchant/description
- 16px gap
- Button

![CleanShot 2024-01-05 at 11 19 54@2x](https://github.com/Expensify/App/assets/2319350/29f22346-9583-4e4d-b4a1-81df18e17427)

___

### ORIGINAL ISSUE

___
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704274831152639

## Action Performed:
Create a receipt request in a workspace

## Expected Result: 
The receipt image in the request preview should have a border radius that is exactly 4px less than the outer border radius of the request preview card

## Actual Result:
 It looks like the receipt has the same border radius as the outer preview card.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screen Shot 2024-01-04 at 1 56 02 PM](https://github.com/Expensify/App/assets/38435837/9ef693e3-9220-4449-b132-62fab574bd1d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175c678ba62df22b2</li>
        <li>Upwork Job ID: 1743007697809223680</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @grgia</details>

**Comment by shawnborton** [comment] 2024-01-05 10:21
So this is what I'm thinking we should do for the preview cards. As an outline, here is what we have ([Figma file](https://www.figma.com/file/WlrZyRCTQ0LFoKcjSmtTsd/General-UI-Patterns?type=design&node-id=3137%3A698&mode=design&t=mKdkt0kIqZSM6M3T-1) so you can inspect):
![CleanShot 2024-01-05 at 11 05 44@2x](https://github.com/Expensify/App/assets/2319350/03e68a3d-653b-4faa-a147-7d1fdbabcb4b)

I'm thinking of this preview component as two parts:
- upper receipt area
- lower information area

![CleanShot 2024-01-05 at 11 09 43@2x](https://github.com/Expensify/App/assets/2319350/8da4fd4b-fac1-4a55-ba49-3e198eded440)


When a receipt is present, I have it so that the upper receipt area and the lower info area overlap by -4px, which basically accounts for that inner border stroke (4px) of the receipt area not adding to the height of the lower info area.
![CleanShot 2024-01-05 at 11 06 45@2x](https://github.com/Expensify/App/assets/2319350/8046ad23-0d7c-46cc-9b37-ac32c43a30fa)

The upper receipt area has a border radius of 16px:
![CleanShot 2024-01-05 at 11 11 13@2x](https://github.com/Expensify/App/assets/2319350/d40a0ddf-7c24-4a1d-9548-2f6e88762949)


And that means the inner receipt area there has a border radius of 12px (16px minus the 4px border):
![CleanShot 2024-01-05 at 11 11 49@2x](https://github.com/Expensify/App/assets/2319350/0c13b097-8bb4-4c1e-8af8-c188dc773cee)

For the bottom info area, the whole thing has a padding of 16px (vertically and horizontally):
![CleanShot 2024-01-05 at 11 12 16@2x](https://github.com/Expensify/App/assets/2319350/0240eecb-0aaf-4edc-8178-2cc380883e80)

The eyebrow part (`XXXX owes:`) should use our `label` font size, with a line height of 16px. It's in our text supporting color.
![CleanShot 2024-01-05 at 11 12 47@2x](https://github.com/Expensify/App/assets/2319350/d22562d0-8d39-4032-b71b-2f2efe31d59a)

The amount is good as it is, which is our h2 size. The merchant/description line below should use our normal text size and use our text supporting color. It should have a line height of 20px. 

In terms of spacing, I'm thinking it goes:
- Eyebrow/top line
- 8px gap
- Amount
- 4px gap
- Merchant/description
- 16px gap
- Button

![CleanShot 2024-01-05 at 11 19 54@2x](https://github.com/Expensify/App/assets/2319350/29f22346-9583-4e4d-b4a1-81df18e17427)


Let me know how all of that sounds! cc @Expensify/design for eyes too.

**Comment by dannymcclain** [comment] 2024-01-05 13:44
@shawnborton if you haven't already, can you please put these screens someplace where we can reference them when building out the legit preview component? I don't want these details to get lost in the void! 💚

**Comment by dubielzyk-expensify** [comment] 2024-01-07 23:19
>can you please put these screens someplace where we can reference them when building out the legit preview component? I don't want these details to get lost in the void!

This is brilliant. I'll use this for my Preview Card Figma component.

**Comment by shawnborton** [comment] 2024-01-08 10:01
@dannymcclain totally! I put the Figma link at the very beginning of my comment [here](https://github.com/Expensify/App/issues/33979#issuecomment-1878440557)

**Comment by grgia** [comment] 2024-01-09 20:42
@shawnborton fantastic write up! I should be able to get to this one this week

**Comment by grgia** [comment] 2024-01-12 21:36
Looking at this, I was trying to see if there's an easy way to get this component in storybook without tons of fake onyx data so we can prevent future regressions as well

**Comment by grgia** [comment] 2024-01-17 00:12
I have a draft for this

**Comment by shawnborton** [comment] 2024-01-19 11:42
@grgia another thing to add to the list here... for preview cards, we used to change some colors around on hover because the row hover was the same color as the card BG. But now that we have a separate color value for row hovers that doesn't collide with the card BG, we can remove the changing colors that happen when you hover on a preview card, for example the small counter in the bottom right

Not Hovered | Hovered
----- | -----
![CleanShot 2024-01-19 at 12 42 09@2x](https://github.com/Expensify/App/assets/2319350/97a8bce5-c5c0-4215-9474-f23688f5edad) | ![CleanShot 2024-01-19 at 12 40 31@2x](https://github.com/Expensify/App/assets/2319350/3c5a361d-61a3-483e-a423-5e4586ff39b8)

**Comment by grgia** [comment] 2024-01-26 22:38
I think @dubielzyk-expensify brought up one more change that needs to be made for this component, mind adding that as a comment as well? I can then resummarize everything so I know we're all on the same page

**Comment by shawnborton** [comment] 2024-01-27 11:23
Yup, I actually already covered that in my big comment above:
![CleanShot 2024-01-27 at 06 23 11@2x](https://github.com/Expensify/App/assets/2319350/136db432-7811-4c24-9b7a-8edeb9476469)

**Comment by grgia** [comment] 2024-01-30 00:09
Should be able to jump back into this

**Comment by grgia** [comment] 2024-01-30 05:16
Here's a first pass of the Report Preview:
<img width="480" alt="image" src="https://github.com/Expensify/App/assets/38015950/ef805b0c-b358-46b2-a028-5b181a082d6b">


@shawnborton do we need to make any updates to the money request preview as well or is it okay?
<img width="447" alt="image" src="https://github.com/Expensify/App/assets/38015950/a3e8a74f-4bd6-41b4-8a9b-853a93aff197">

**Comment by shawnborton** [comment] 2024-01-30 12:46
The money request preview basically be using the same exact component. Gotta ask though - how did you get those two little avatars to show up for the money request preview?

**Comment by grgia** [comment] 2024-01-30 16:44
@shawnborton I hardcoded the split avatars to show up for testing. But these are actually two different components in the app. I'm thinking I can consolidate them, but I'd probably need to see all the cases in figma to be sure

**Comment by shawnborton** [comment] 2024-01-30 16:44
Okay cool, I love the idea of consolidating if possible!

**Comment by grgia** [comment] 2024-01-30 16:46
@shawnborton, what would you name this component if you were referring to it in Figma?

**Comment by trjExpensify** [comment] 2024-01-30 23:30
>Merchant/description line
> - If report: "Merchant || Description", if one expense on the report. "N requests", if multiple expense on the report. "N requests, n scanning" if multiple expense on the report and it has SmartScanning receipts added to it.
> - If expense: Show merchant if one exists, if not, show description

**Comment by shawnborton** [comment] 2024-01-30 23:50
Sweet, thanks for clearing that up! Also cc @dubielzyk-expensify since you are working on the preview component, this logic should help guide the designs!

**Comment by grgia** [comment] 2024-02-01 18:56
PR in progress!

**Comment by abekkala** [comment] 2024-02-08 18:37
@grgia do you want to link the PR to this?

**Comment by grgia** [comment] 2024-02-08 20:43
@abekkala I was working on a wave-related doc, but that's done so I'll get the PR merged and ready for final review before EOW!

**Comment by abekkala** [comment] 2024-02-08 23:40
@grgia ah ok! I misinterpreted your post above! sorry about that.

**Comment by grgia** [comment] 2024-02-09 18:20
Updating PR now

**Comment by abekkala** [comment] 2024-03-07 14:47
### PAYMENT SUMMARY FOR MAR 13

- Fix: Internal 
- PR Review: @situchan [$500]  [Offer Link](https://www.upwork.com/nx/wm/offer/101262583)
please complete checklist above

**Comment by situchan** [comment] 2024-03-07 14:49
No regression. This is design inconsistency fix. I don't think regression test is needed here.

**Comment by abekkala** [comment] 2024-03-13 15:43
@situchan can you accept the offer in Upwork so I can release payment today? thanks!

**Comment by situchan** [comment] 2024-03-13 15:44
sorry I thought I accepted offer. Just did now

**Closed** 2024-03-13 15:53 UTC
Labels: Weekly, Internal, Awaiting Payment, Bug
