### ISSUE TITLE
[HOLD for payment 2024-07-10] Send invoice - Hold option appears for invoice and error shows up when attempting to hold it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44450] opened 2024-06-26 12:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice
3. Enter amount > Next
4. Send invoice to any user
5. Go to invoice thread
6. Click 3-dot menu
7. Click Hold
8. Enter a reason and save it

## Expected Result:
Hold option should not appear for invoice if it is not supported (production behavior)

## Actual Result:
Hold option appears for invoice and error shows up when attempting to hold the invoice

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/be89c474-bfe5-4749-8ab2-ef667b55cf37

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by lanitochka17** [comment] 2024-06-26 12:43
@carlosmiceli  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment] 2024-06-26 12:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hold option appears for invoice and error shows up when attempting to hold it
### What is the root cause of that problem?
We are not checking if the report is an invoice report before adding the `hold` menu item to `threeDotsMenuItems` here
https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/components/MoneyReportHeader.tsx#L258-L263
### What changes do you think we should make in order to solve the problem?
Check if the report is invoice [here](https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/components/MoneyReportHeader.tsx#L246-L250) by adding the following code 
```javascript
const isInvoiceReport = ReportUtils.isInvoiceReport(moneyRequestReport);
```
Add `&& !isInvoiceReport` to the condition below to prevent adding `hold` menu item to `threeDotsMenuItems` if the report is an invoice report 
```javascript
if (!isOnHold && (isRequestIOU || canModifyStatus) && !isScanning && !isInvoiceReport)
```
https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/components/MoneyReportHeader.tsx#L258
### What alternative solutions did you explore? (Optional)

**Comment by carlosmiceli** [comment] 2024-06-26 19:33
@etCoderDysto that looks promising, let's do it!

**Comment by etCoderDysto** [comment] 2024-06-26 19:35
Great! I am raising a PR now.

**Comment by yuwenmemon** [comment] 2024-06-26 22:04
@etCoderDysto Any update here?

**Comment by etCoderDysto** [comment] 2024-06-26 22:05
Pr is almost ready. It will be ready for review under 30 minutes.

**Comment by yuwenmemon** [comment] 2024-06-26 22:06
@etCoderDysto Can you confirm whether or not this came from the following PR? https://github.com/Expensify/App/pull/43618

**Comment by etCoderDysto** [comment] 2024-06-26 22:13
> @etCoderDysto Can you confirm whether or not this came from the following PR? #43618

I have checked with git blame and the issue seems to come from the PR.

**Comment by etCoderDysto** [comment] 2024-06-26 22:54
@yuwenmemon @carlosmiceli 
[PR](https://github.com/Expensify/App/pull/44508) is ready for review

**Comment by carlosmiceli** [comment] 2024-06-26 22:55
@etCoderDysto  Reviewing.

**Comment by carlosmiceli** [comment] 2024-06-26 23:01
@yuwenmemon Just approved/merged the PR.

**Comment by mountiny** [comment] 2024-06-27 17:38
The PR has been CPed and QA has confirmed it worked so removing the DB label

**Comment by abekkala** [comment] 2024-07-08 20:48
### PAYMENT SUMMARY FOR JUL 10

- Fix: @etCoderDysto [$250, if no regressions] 
- PR Review: @carlosmiceli - internal, no payment 😉 

@etCoderDysto I'm having a hard time finding your profile in Upwork. Can you link it here and I can send your offer!
Thanks

**Comment by etCoderDysto** [comment] 2024-07-08 20:50
Hi @abekkala, here is my upwork profile: https://www.upwork.com/freelancers/~01ea78e0164390eb79

**Comment by abekkala** [comment] 2024-07-08 20:58
updated summary above with your offer

**Comment by etCoderDysto** [comment] 2024-07-08 21:02
I have accepted the offer. Thank you!

**Comment by etCoderDysto** [comment] 2024-07-09 08:07
Since we are removing three-dot menu in recent releases, I don't think we need a regression test step.

**Comment by abekkala** [comment] 2024-07-10 15:03
@etCoderDysto payment sent and contract ended - thank you! 🎉

**Closed** 2024-07-10 15:03 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
