### ISSUE TITLE
[HOLD for payment 2023-08-08] [$1000] App translates paid message to english after deleting last message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23380] opened 2023-07-21 21:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open the app in another device and login with user B
3. If language is english for user A, change it to spanish
4. From user B, request money to user A
5. Open user B report and click on green button to pay, observe in LHN that paid text is in spanish
6. From user A, send message to user B
7. Delete the message sent in step 6 and observe in LHN, app displays paid text in english even though language is spanish
## Expected Result: 
App should not auto translate paid message to english from spanish is language is kept as spanish
## Actual Result: 
On deleting message after paid message in report, app translates paid message to english even though language is spanish

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop
 
**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c1890d40-9d1c-49ed-acd2-0e8ad0c2b166

https://github.com/Expensify/App/assets/43996225/49489654-6c05-4f7d-a670-13c7b2b41b44

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689780932673749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a539a89487c96136</li>
        <li>Upwork Job ID: 1683611319166062592</li>
        2023-07-24<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 25790663</li>
<li>dhanashree-sawant | Reporter | 25790667</li>
</ul></li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-07-22 01:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN IOU message loses translation if the following message is deleted

### What is the root cause of that problem?
Improper access of data/ filtering of reportAction messages in `OptionsListUtils.js` file's `getLastMessageTextForReport `function

### What changes do you think we should make in order to solve the problem?
In `OptionsListUtils` replace this line 
`const sortedReportActions = ReportActionUtils.getSortedReportActions(_.toArray(actions), true);
`with 
`const sortedReportActions = ReportActionUtils.getSortedReportActionsForDisplay(_.toArray(actions), true);

You can also then instead of replacing `lastReportActions`,can write a new variable `lastReportActionsVisible` and access that in the       `getLastMessageTextForReport `funciton like
`const lastReportAction = lastReportActionsVisible[report.reportID];
`
`

**Comment by tjferriss** [comment] 2023-07-25 22:39
@ArekChr can you please take a look at the proposals when you have time?

**Comment by ArekChr** [comment] 2023-07-26 08:28
[tienifr](https://github.com/tienifr) Your proposal with a flickering issue fix looks good to me.
:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by ygshbht** [comment] 2023-07-26 08:57
Thank you, @ArekChr, for taking the time to review the proposals.

I'd like to share some thoughts. It appears that both proposals aim to solve the problem by filtering out deleted messages when fetching the last message text. The only discernable difference seems to be the consideration of a 'pending delete' action in the other proposal to prevent a potential flickering issue in the LHN.

While the attention to the 'pending delete' action to avoid flickering in the LHN is noteworthy, it seems relatively minor compared to the core issue we're addressing. Essentially, it's akin to a spin-off from the main problem. If this minor detail had been highlighted during the review of my PR, I would have been more than capable of incorporating a similar fix into my solution.

Could you please provide further clarification on why this minor detail was significant enough to select the second proposal over mine? I was under the impression that our primary evaluation criteria were based on how effectively each proposal addressed the main issue. Both solutions seem to accomplish this effectively. My proposal, submitted three days earlier, identified the same root cause and offered a similar approach towards resolving it.

**I understood the purpose of these proposals to be the presentation of a coherent plan of action, rather than delivering a complete solution before the contract commences. I would appreciate any insights that could help enhance my understanding of this process.**

Understanding your perspective would be highly beneficial for me to tailor my future proposals more effectively and contribute more efficiently to the project.

Thank you for your time.

**Comment by ArekChr** [comment] 2023-07-27 08:56
@ygshbht, Thank you for your feedback. The selection of the second proposal was largely due to its handling of the 'pending delete' action, which helped to avoid the additional regression and potential flickering issue. I appreciated both proposals, and the decision doesn't reflect negatively on your proposal. I encourage open discussions and if you have further concerns, feel free to raise them on our open-source channel.

Your contributions are highly valued, and I look forward to your continued participation.

**Comment by ygshbht** [comment] 2023-07-27 09:36
Thanks, Please find the conversation here https://expensify.slack.com/archives/C01GTK53T8Q/p1690450324972079

**Comment by tjferriss** [comment] 2023-08-01 21:18
Waiting for PR to hit production to complete next steps.

**Comment by tjferriss** [comment] 2023-08-02 03:58
Payment comment updated. @ArekChr can you get started on the checklist when you have a minute?

**Comment by ArekChr** [comment] 2023-08-02 12:49
[x] Link to the PR: it was not a regression here.
[x] Link to comment: no comments.
[x] Link to discussion: no discussions.
[x] Determine if we should create a regression test for this bug. I think we don't need a regression tests for translations.

**Comment by tjferriss** [comment] 2023-08-09 04:25
Payments have been sent via Upworks

**Closed by tjferriss** 2023-08-09 04:25 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
