### ISSUE TITLE
[$500] Bank Account - Beneficial owner form isn't displayed after filling it, exit the BA set up and return

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31848] opened 2023-11-24 17:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.2
**Reproducible in staging?:** y
**Reproducible in production?:** unable to check VBA in production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have initiated the process to add a BA and reach the Beneficial owner page.
1. Toggle the box to add a beneficial owner.
2. Fill out the form.
3. Exit the BA modal, go to LHN.
4. Go back to the BA modal and the beneficial owner page.

## Expected Result:
Additional beneficial owner form should be displayed.

## Actual Result:
Additional beneficial owner form is not displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/51deaa44-3edb-4e07-9418-01651ecb5345

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b94c3bd60aca7e1</li>
        <li>Upwork Job ID: 1729116399924043776</li>
        <li>Last Price Increase: 2023-11-27</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27898874</li>
<li>bernhardoj | Contributor | 27898876</li>
</ul></li>
    </ul>
</details>

**Comment by Sergio16T** [comment] 2023-11-27 16:09
**Proposal**
Please re-state the problem that we are trying to solve in this issue.
The beneficial owners form doesn't show if we close and reopen the bank account page.

**What is the root cause of that problem?**
The Form conditionally renders when `inputValues.hasOtherBeneficialOwners` is true. 
https://github.com/Expensify/App/blob/4efa2c069d0b9a15764141ac975efe3156b27e52/src/pages/ReimbursementAccount/ACHContractStep.js#L215

InputValues is provided as the FormProvider component via Render Prop Here 
https://github.com/Expensify/App/blob/4efa2c069d0b9a15764141ac975efe3156b27e52/src/pages/ReimbursementAccount/ACHContractStep.js#L168

FormProvider HOC Component inherits the draft state from onyx here 
https://github.com/Expensify/App/blob/4efa2c069d0b9a15764141ac975efe3156b27e52/src/components/Form/FormProvider.js#L347

The inputData is initialized with an empty object here and does not inherit the draft state set by the ACHContractStep
https://github.com/Expensify/App/blob/4efa2c069d0b9a15764141ac975efe3156b27e52/src/components/Form/FormProvider.js#L110

ACHContractStep sets the draft state in ONYX here 
https://github.com/Expensify/App/blob/4efa2c069d0b9a15764141ac975efe3156b27e52/src/pages/ReimbursementAccount/ACHContractStep.js#L109

 The FormProvider Higher Order Component is initializing the inputValues state as an empty object. 
Instead it should inherit the draft state provided by onyx for ONYXKEYS.REIMBURSEMENT_ACCOUNT

** What changes do you think we should make in order to solve the problem? ** 
I suggest that the FormProvider Component be updated to initialize the state with draftValues provided by Onyx. 
`
    const [inputValues, setInputValues] = useState({...draftValues});
`

**Comment by Sergio16T** [comment] 2023-11-27 16:16
Contributor details
Your Expensify account email: sergio.tapiafikes.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010bae9ca8601bb144

**Comment by Li357** [comment] 2023-11-29 17:32
@cubuspl42 Any thoughts? I want to get this done before end-of-week or else I will have to reassign.

**Comment by Li357** [comment] 2023-11-29 19:01
@miljakljajic can you you reapply the Engineering label to assign another internal engineer here? I'll be back at school EOW, thanks!

**Comment by Sergio16T** [comment] 2023-11-29 19:17
@Li357, @miljakljajic  I can put up a PR today if it's still available for contributors. Already did the research and provided proposal in comment above. Before assigning it to internal engineer, I'd love the opportunity to do the dev work on this.

**Comment by cubuspl42** [comment] 2023-11-30 10:57
@Sergio16T This issue is the review phase, it's in my queue and I'll jump to it today. As per the process, your proposal has to be reviewed and selected first, before you put up a PR. Please ensure you've read the [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by cubuspl42** [comment] 2023-11-30 12:21
@bernhardoj 

Just a formal question: did you test this?

**Comment by cubuspl42** [comment] 2023-12-27 08:48
@miljakljajic The PR is reviewed and merged 👍

**Comment by miljakljajic** [comment] 2024-01-03 12:00
Thank you! Apologies, it seems like we didn't update the title for this one. I will get everyone paid today.

**Comment by miljakljajic** [comment] 2024-01-03 12:27
Paid, contracts ended!

**Closed by miljakljajic** 2024-01-03 12:27 UTC
Labels: Reviewing, External, Engineering, Monthly, Bug
