### ISSUE TITLE
[HOLD for payment 2023-09-21] [$1000] iOS- mWeb Chrome redirects to bottom and focus language option

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25759] opened 2023-08-23 12:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to mWeb Chrome
2. go to login page
3. Focus email or phone number textfield
4. press down arrow above keyboard

## Expected Result:
 it should show arrow disabled like safari

## Actual Result:
it shows arrow to navigate and on clicking focus the language option at end of the page 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Chrome
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-18

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/a5ff804a-3ead-428c-869f-afa4df939ac7

https://github.com/Expensify/App/assets/115492554/b8a5a65f-a156-4f52-8700-76c8f945a00f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691703082196079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b682288ea67dbb24</li>
        <li>Upwork Job ID: 1694846732824039424</li>
        <li>Last Price Increase: 2023-08-31</li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-08-23 23:14
I am able to recreate this using Browserstack with a virtual iPhone 14.

<img width="262" alt="image" src="https://github.com/Expensify/App/assets/10925636/84f79dd8-970a-4bee-aa5c-6004a754df78">
<img width="281" alt="image" src="https://github.com/Expensify/App/assets/10925636/3e2b0465-cfc3-40f2-97d7-f51102393d7f">

**Comment by strepanier03** [comment] 2023-08-23 23:20
I raised a discussion on this in the bug report thread in [Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1692832818596449?thread_ts=1691703082.196079&cid=C049HHMV9SM). Will action when we have a consensus and discussion.

**Comment by strepanier03** [comment] 2023-08-24 22:58
Moving this forward after discussion.

**Comment by ArekChr** [comment] 2023-08-28 08:24
I can't reproduce this error on iPhone 14 arrows are disabled. On which OS system it happens?

**Comment by strepanier03** [comment] 2023-08-28 23:22
@ArekChr - I tested on a 13 using Browserstack.

**Comment by ArekChr** [comment] 2023-08-29 07:35
Still, I can not reproduce it on iPhone 13 as well, @strepanier03 What OS version do you have on the iPhone simulator? 

<img width="564" alt="Zrzut ekranu 2023-08-29 o 09 34 40" src="https://github.com/Expensify/App/assets/24796318/7e21be64-1576-47c3-bfc2-a44d6417b11a">

**Comment by DinalJivani** [comment] 2023-08-29 10:30
@ArekChr 
If I'm not wrong you're using Safari Right? This is happening in iOS/Chrome only. 
For Safari it is disabled. iOS/Chrome is only affected one.

**Comment by ArekChr** [comment] 2023-08-29 11:06
@DinalJivani, you are right. Thanks, and sorry for the oversight 😊 Confirming that the regression exists on iOS/Chrome. Reviewing proposals.

**Comment by ArekChr** [comment] 2023-08-29 12:10
@tienifr How will this affect other pickers when we set `tabIndex: -1` in the base picker for all selectors? 

It would be good to hide this bar with up/down buttons because it takes up unnecessary space and is not used on this screen.

**Comment by ArekChr** [comment] 2023-08-30 09:19
I investigated that, and I didn't found any possibilities to hide this bar. The [proposal](https://github.com/Expensify/App/issues/25759#issuecomment-1693119050) from @tienifr makes sense, let's go with the tabIndex fix.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by ArekChr** [comment] 2023-09-01 08:21
bump @grgia @strepanier03

**Comment by ArekChr** [comment] 2023-09-15 09:20
- [x] Link to the PR: No bug identified.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I don’t think we need to add a regression test here.

**Comment by strepanier03** [comment] 2023-09-21 21:39
@tienifr - I have paid you via Upwork and closed the contract. I don't know how but we had two contracts for you for this job. I paid one and closed it and closed the other without payment. If there are some special circumstances here that I'm not aware of please just leave me a message and ping and I'll revisit.

@DinalJivani - It doesn't look like a job was created for you for reporting this. I've created on and hired you. Can you accept that and ping me when you do so I can wrap this up?

@ArekChr - Thank you for the checklist items!

**Comment by DinalJivani** [comment] 2023-09-21 22:29
@strepanier03 
Offer accepted

**Comment by strepanier03** [comment] 2023-09-21 22:33
So speedy, I love it, thank you! Handling it now.

**Comment by strepanier03** [comment] 2023-09-21 22:36
Okay, that is paid. Closing this out as completed now.

**Closed by strepanier03** 2023-09-21 22:36 UTC
Labels: External, Daily, Awaiting Payment, Bug
