### ISSUE TITLE
[$1000] Chat - An offline deleted message can be edited and restored

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24070] opened 2023-08-02 19:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Go to the chat room where there are already messages sent from you
3. Turn off the internet or use "Force offline".
4. Edit any of your messages
5. Delete the message from step 4
6. Turn the internet back on or use the "Force offline" switch
7. After 1-2 seconds, turn off the Internet again or use the "Force offline" switch
8. Edit the deleted message that appeared again
9. Turn the Internet back on or use the "Force offline" switch

## Expected Result:
After deleting a message offline and then turning on the Internet, the message should be deleted and no longer appear in the chat history

## Actual Result:
After deleting a message in offline mode and then turning the Internet on and off, the message disappears and then reappears in the chat history and can be edited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.49.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cc665d1e-7676-4c58-b7fa-416c984566f7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Tea

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b97798d34c14a2a</li>
        <li>Upwork Job ID: 1687579790467248128</li>
        <li>Last Price Increase: 2023-08-25</li>
    </ul>
</details>

**Comment by rushatgabhane** [comment] 2023-08-03 07:34
> props.network.isOffline || props.network.shouldForceOffline

that looks like a hack because the root cause is "The isOffline flag in below code is not being updated sometimes"

**Comment by kevinksullivan** [comment] 2023-08-04 21:43
hey @flaviadefaria I am going OOO for a week, so tapping you in to help out in the interim. Thanks!

**Comment by Victor-Nyagudi** [comment] 2023-08-07 10:10
Can we treat this as an edge case?

It's rare for an internet connection to flicker on and off in a span of 1 to 2 seconds (this usually happens for electricity), so if a user performed a couple of actions offline, when they do go online, wouldn't there be enough time for the API calls to go through? Unless, of course, they manually go offline in 1 to 2 seconds, but when would someone ever do that?

Let's say the internet flickering is a main concern and the user is puzzled why they still see a message they deleted. The "You appear to be offline" notification will show up which should explain why the message is still there.

**Comment by flaviadefaria** [comment] 2023-08-07 12:34
Waiting for @robertKozik to review the proposals.

**Comment by robertKozik** [comment] 2023-08-10 08:27
Looking into it 👀

**Comment by robertKozik** [comment] 2023-08-11 16:08
First of all, sorry for the delay on this 😔 
To be honest I'm also leaning towards the edge-case here, but I need some more time to be sure

**Comment by kevinksullivan** [comment] 2023-08-17 18:05
I'm back @flaviadefaria ! Thanks for keeping this up in the interim. @robertKozik still waiting on an update here, let us know what you find!

**Comment by kevinksullivan** [comment] 2023-08-17 18:07
Ah I'll keep you assigned for credit @flaviadefaria , but I'll take care of the payments and such

**Comment by kevinksullivan** [comment] 2023-08-21 22:07
Hi @robertKozik when do you expect to have an update for us?

**Comment by kevinksullivan** [comment] 2023-08-22 15:29
Sounds good

**Comment by robertKozik** [comment] 2023-08-23 10:28
@tienifr, I believe your identified root cause is accurate – offline requests entering the queue can indeed lead to the issue. As you pointed out, while editing and then deleting, the pending action could be consistently overwritten by the first request in the queue.

I didn't implement your solution because it seems like quite a complex refactoring. However, it should be effective. My only concern is that it might not entirely resolve the issue. Please correct me if I'm mistaken, but if we have, for example, two edit requests for the same report action, we could still encounter the situation where the edit key in the pendingAction object is overwritten after the first request.

**Comment by robertKozik** [comment] 2023-08-23 15:33
Yeah, I believe so. If we are starting to messing up with pendingAction let's fix it entirely. But the scope of the changes will be huge with the object approach

**Comment by robertKozik** [comment] 2023-08-24 16:09
Yeah sure, I didn't even think of extending the scope beyond ReportAction , but still it would be not that small PR. 
If you could add the batch edit into your proposal I think we would have fix that covers the root cause in 100%.

**Comment by kevinksullivan** [comment] 2023-08-28 19:03
@robertKozik can you provide an update for the week? Thanks!

**Comment by robertKozik** [comment] 2023-08-29 11:03
Sure, @kevinksullivan. It appears that this issue exposes a problem with storing the `pendingAction` within Onyx. Currently, we have only one field to store it, which leads to potential overwriting of the `pendingAction` if multiple actions exist in the offline queue.

To address this, @tienifr proposed a solution that involves extending the `pendingAction` to become an object with keys corresponding to each type of action (`ADD`, `MODIFY`, `DELETE`). We're currently awaiting @tienifr's update to the proposal as I've requested a tweak to the fix. This tweak aims to ensure that multiple modify requests in the queue are also covered, thus fully resolving the issue.

**Comment by kevinksullivan** [comment] 2023-08-30 21:39
We're close to a solution here. @tienifr will you be able to priooritize @robertKozik 's suggested changes this week? If not we'll need to take it internal.

**Comment by NikkiWines** [comment] 2023-09-01 19:02
This would be a pretty significant change to how we handle pending actions so going to run this by the team internally to be sure it's a change we want to implement

**Comment by NikkiWines** [comment] 2023-09-04 22:15
Chatted with @marcaaron about this [here](https://expensify.slack.com/archives/C03TQ48KC/p1693612909359109) (internal channel) and while this is something we should look into resolving at some point, it is a pretty edge-case scenario. We'd want to have a larger discussion internally on how we want to fix it as well. 


So, for the moment, let's close this out to be potentially addressed at a later date. Sorry for all the back and forth and thanks for the proposals 🙇

**Closed** 2023-09-05 17:40 UTC
Labels: Engineering, Daily, Internal, Bug
