### ISSUE TITLE
[$250] Expensify personal - Not here page opens when opening Expensify profile from group member list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43841] opened 2024-06-17 15:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Create a group chat with "Expensify"
4. Click on the group chat header > Members
5. Click Expensify
6. Click Profile

## Expected Result:
Expensify profile will open without issue

## Actual Result:
Not here page shows up when opening Expensify profile from group chat member list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/348bf3a4-d4c5-4b37-a065-fc7d05180255

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f91896edfd02fabc</li>
        <li>Upwork Job ID: 1820597582663880018</li>
        <li>Last Price Increase: 2024-08-19</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-06-17 15:06
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-06-18 07:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not found page shows when opening the expensify account from group member list.

### What is the root cause of that problem?
The profile page will show the not found page if the account is in the restricted account list and the expensify account is in that list (and the only one).
https://github.com/Expensify/App/blob/b33542383ac2cb8ea1e922aa12dd2265efccd0ab/src/pages/ProfilePage.tsx#L144
https://github.com/Expensify/App/blob/b33542383ac2cb8ea1e922aa12dd2265efccd0ab/src/CONST.ts#L2073-L2076

But previously, we can't create a group with an expensify account at all, but this [PR](https://github.com/Expensify/App/pull/41290) now allows the expensify account to be shown in the new chat/search list result.

### What changes do you think we should make in order to solve the problem?

We can hide the Profile button if the account is the restricted account.
https://github.com/Expensify/App/blob/b33542383ac2cb8ea1e922aa12dd2265efccd0ab/src/pages/ReportParticipantDetailsPage.tsx#L138-L143

Or if we want to allow the user to see the expensify profile, then we need to remove the restricted account check here.
https://github.com/Expensify/App/blob/b33542383ac2cb8ea1e922aa12dd2265efccd0ab/src/pages/ProfilePage.tsx#L144

Or again, we can prevent the expensify account from being added to the group.
https://github.com/Expensify/App/blob/9ec57c03f64e56271b2b507064fa72323463c560/src/pages/NewChatPage.tsx#L209-L213
<img width="388" alt="image" src="https://github.com/Expensify/App/assets/50919443/4f886f02-084d-4d0a-a216-d5d13ed1f235">
```
if (item.isSelfDM || CONST.RESTRICTED_ACCOUNT_IDS.includes(item.accountID)) {
    return null;
}
```

_notice there is another expensify account and we can add it to the restricted list if needed_

**Comment by alexpensify** [comment] 2024-06-19 18:17
I'll review this one soon.

**Comment by alexpensify** [comment] 2024-06-21 22:11
No update yet

**Comment by alexpensify** [comment] 2024-06-24 22:42
Still on my testing radar

**Comment by alexpensify** [comment] 2024-06-26 21:05
Other GHs and customer tasks have been a higher priority, I'll get to this one soon.

**Comment by alexpensify** [comment] 2024-07-01 14:18
Closing - I'm unable to replicate this experience by following the steps here 

![2024-07-01_07-15-33](https://github.com/Expensify/App/assets/8107070/7ce1f8d7-8268-465c-9bb6-11ef4e34498c)

**Comment by alexpensify** [comment] 2024-07-01 14:21
## Heads up, I will be offline until Monday, July 8, 2024, and will not actively watch over this GitHub during that period.

If this GitHub needs an urgent update, please ask for help in the #expensify-open-source Slack Room. If it can wait, I'll continue the review process when I return online. Thanks!

**Comment by bernhardoj** [comment] 2024-07-02 03:31
@alexpensify hi, it's still reproducible, you need to create a group with notifications@expensify.com

https://github.com/Expensify/App/assets/50919443/d81fdbd0-70e7-4b9e-a058-cba62f4c5007

**Comment by alexpensify** [comment] 2024-07-08 17:38
@bernhardoj I'm catching up from being OOO. I see the other GH mentioned here is closed too. Should we move this convo to a Slack 🧵 or keep this one closed? Thanks for the feedback!

**Comment by bernhardoj** [comment] 2024-07-09 03:27
The other GH is closed because it's expected that Expensify is shown in the contact list which I mentioned in my proposal, but in this issue, opening the Expensify profile from the group members list page shows not found page. I think the first thing is to clarify what should be the expected behavior. There are 3 possible solutions (hide the profile button for Expensify, allow the user to see the Expensify profile, or not allow the user to add Expensify to a group) in my proposal. I think we can reopen this and assign an internal engineer to take a look and decide what should be the expected behavior.

**Comment by alexpensify** [comment] 2024-07-10 17:45
OK, tomorrow, I'll start a discussion in the Slack room for more crowdsourced feedback.

**Comment by bernhardoj** [comment] 2024-07-23 17:32
@alexpensify hi, is there any update with the discussion?

**Comment by alexpensify** [comment] 2024-07-29 19:22
Reopening so this one doesn't slip out of my radar

**Comment by trjExpensify** [comment] 2024-07-29 20:25
You shouldn't be able to `Add to group` the Chronos or Expensify users, so let's prevent that. Both are allowing me to select `Add to group` on them. 


![Image](https://github.com/user-attachments/assets/83886f31-0ff1-40da-9d0d-c45756a86594)

**Comment by alexpensify** [comment] 2024-08-01 22:53
@trjExpensify - do you agree to make this `External` based on your feedback here?

**Comment by trjExpensify** [comment] 2024-08-02 14:54
Yep!

**Comment by alexpensify** [comment] 2024-08-05 23:08
Open for proposals here

**Comment by abdulrahuman5196** [comment] 2024-08-08 12:50
>You shouldn't be able to Add to group the Chronos or Expensify users, so let's prevent that. Both are allowing me to select Add to group on them.

@trjExpensify Is it only for groups creation or we shouldn't even list those accounts in the start chart list?

**Comment by trjExpensify** [comment] 2024-08-08 13:05
Group creation. You can navigate to Chronos DM or Expensify DM from here.

**Comment by alexpensify** [comment] 2024-08-12 21:45
No update; we need proposals here.

**Comment by bernhardoj** [comment] 2024-08-13 02:54
I have a [proposal above](https://github.com/Expensify/App/issues/43841#issuecomment-2175304751) for review

**Comment by alexpensify** [comment] 2024-08-13 04:32
@abdulrahuman5196 when you get a chance, can you review the proposal? Sorry, I missed it. Thanks!

**Comment by abdulrahuman5196** [comment] 2024-08-13 17:47
> Group creation. You can navigate to Chronos DM or Expensify DM from here.

@trjExpensify Just to confirm. Is the screenshot present in @bernhardoj 's proposal here https://github.com/Expensify/App/issues/43841#issuecomment-2175304751 is the UX expectation?

**Comment by trjExpensify** [comment] 2024-08-13 23:15
>@trjExpensify Just to confirm. Is the screenshot present in @bernhardoj 's proposal here https://github.com/Expensify/App/issues/43841#issuecomment-2175304751 is the UX expectation?

Yep, as the `Add to group` button is how you create a group.

**Comment by alexpensify** [comment] 2024-08-15 19:59
@abdulrahuman5196 - are we good to go here or do you need more feedback from the team? Thanks for the update.

**Comment by abdulrahuman5196** [comment] 2024-08-20 16:38
Hi, Checking now

**Comment by abdulrahuman5196** [comment] 2024-08-20 17:00
@bernhardoj 's proposal here https://github.com/Expensify/App/issues/43841#issuecomment-2175304751 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by iwiznia** [comment] 2024-08-20 18:17
> But previously, we can't create a group with an expensify account at all, but this PR now allows the expensify account to be shown in the new chat/search list result.

Asking [here](https://expensify.slack.com/archives/C03TQ48KC/p1724177824258659) because I don't know why we did that.

**Comment by iwiznia** [comment] 2024-08-20 18:44
Just to clarify, the part of the proposal we are doing is just this right?
> Or again, we can prevent the expensify account from being added to the group.

Assuming the answer is yes and assigning @bernhardoj

**Comment by bernhardoj** [comment] 2024-08-21 06:41
> Just to clarify, the part of the proposal we are doing is just this right?

Yes

PR is ready. I also have a question about the expected results [here](https://github.com/Expensify/App/pull/47770/files#r1724480422)

cc: @abdulrahuman5196 @trjExpensify @iwiznia

**Comment by alexpensify** [comment] 2024-08-26 15:12
## Next Steps

This PR is going through the review process and waiting for @iwiznia to final review it. 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment] 2024-09-03 23:07
I'm catching up from being OOO last week and I see that this went into production yesterday. Seven days will be Monday, September 9.

**Comment by alexpensify** [comment] 2024-09-11 23:04
Automation didn't kick in here, so I'll manually work on the process tomorrow.

**Comment by alexpensify** [comment] 2024-09-13 15:34
Payouts due: 2024-09-09

- [ ] Contributor: $250 @bernhardoj 
- [ ] Contributor+: $250 @abdulrahuman5196 

Upwork job is [here](https://www.upwork.com/jobs/~021834615275438771805). I'll pay via Upwork because this one was created on June 17. Please accept and I can complete the payment process. Thanks!

**Comment by bernhardoj** [comment] 2024-09-13 15:53
Accepted

**Comment by abdulrahuman5196** [comment] 2024-09-14 19:54
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/41290#issuecomment-2351127475

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Press FAB > Start Chat
2) Search for [notifications@expensify.com](mailto:notifications@expensify.com)
3) Verify there is no "Add to group" button for the account

@alexpensify accepted the offer

**Comment by alexpensify** [comment] 2024-09-16 21:26
Closing - I've completed the payment process in Upwork.

**Closed by alexpensify** 2024-09-16 21:26 UTC
Labels: Reviewing, External, Weekly, Bug
