### ISSUE TITLE
 Back Button Redirects to incorrect pages instead of last visited page -inside room - task- chat thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22033] opened 2023-07-02 01:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
(Either use an old test account with previous made rooms and workspaces or follow the following steps)
1 From User A, create a workspace and invite user B.
2 Create a new room in (public mode) and share the code to User B
3 Have few chats between User A and B
4 User A assigns a task to User B in the room.
5 User A enters the chat thread of the assigned task.
6 Inside the chat thread, User A clicks on the "To" field to open the search functionality.
7 User A clicks on the back button
8 Verify if the chat thread opens as the last visited page.
## Expected Result: 
Upon clicking the back button, the last visited page should open instead of create task interface
## Actual Result: 
When clicking the back button, the create task interface was opened instead of the last visited page.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5f437467-6f23-4aeb-9645-eac62c89ed12

https://github.com/Expensify/App/assets/43996225/3046cc60-5579-4f0a-84db-6d6c016f3b11

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688107071051049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment] 2023-07-04 12:49
Closing for Dupe of https://github.com/Expensify/App/issues/21200

**Closed by zanyrenney** 2023-07-04 12:49 UTC
Labels: Daily, Bug
