### ISSUE TITLE
[$1000] [HOLD for payment 2023-07-24] [HOLD for payment 2023-07-21] Chat -  Copy to clipboard does not copy with format

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22833] opened 2023-07-13 18:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send message with styling characters eg: # testing
4. Hover on click on copy to clipboard
5. Paste in compose box and observe that it does not copy text with format i.e. if same message send as step 3 then it will paste 'testing' in place of '# testing'

## Expected Result:
App should copy text with formatting on click of copy to clipboard

## Actual Result:
App does not copy text with formatting on click of copy to clipboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e7371008-e277-44aa-80f0-4b2b24fc9463

https://github.com/Expensify/App/assets/93399543/3da58a76-b11b-43b6-ae09-65a2abc82cce

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689272192380209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109720246c50a4eba</li>
        <li>Upwork Job ID: 1683456836334284800</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by francoisl** [comment] 2023-07-13 18:43
I can reproduce on staging as well. @robertKozik I think the issue is coming from this[ PR](https://github.com/Expensify/App/pull/22817), any idea how to fix it?

**Comment by Santhosh-Sellavel** [comment] 2023-07-13 19:14
@francoisl It's not related that as it never hit production

**Comment by francoisl** [comment] 2023-07-13 19:28
Yeah, removing this new block solves the issue for me:

```js
if (['INPUT', 'TEXTAREA'].includes(event.target.nodeName)) {
    return;
}
```

... but it also reintroduces [this other issue](https://github.com/Expensify/App/issues/22803) 🙃

**Comment by mountiny** [comment] 2023-07-13 19:31
I think the previous issue is less serious than this one so reverting would make sense to me

**Comment by Santhosh-Sellavel** [comment] 2023-07-13 19:36
Yeah, Let's revert it!

**Comment by robertKozik** [comment] 2023-07-13 19:41
Sorry I was unavailable for a while. Yeah let's revert this if needed. I wasn't aware of such a consequences of that fix

**Comment by Santhosh-Sellavel** [comment] 2023-07-13 21:47
Didn't work and multiple event listeners for the same event in a component. Bad!

**Comment by Santhosh-Sellavel** [comment] 2023-07-13 21:59
Seems you updated the changes after posting. We tested it earlier

**Comment by Santhosh-Sellavel** [comment] 2023-07-13 22:01
But it has another issue cursor gets misplaced and still not opting due
"multiple event listeners for the same event in a component"

https://github.com/Expensify/App/assets/85645967/bb32e705-1b5f-4c3d-be2c-cc062d1e5bc3

**Comment by robertKozik** [comment] 2023-07-13 22:13
@Santhosh-Sellavel I think the cursor misplacement is whole new isse not related with this. The ReportActionMessageEdit's composer doesn't have `shouldCalculateCaretPosition` prop set up (it's present  in ReportActionCompose's Composer). After adding this prop, caret is placed correcly

**Comment by Santhosh-Sellavel** [comment] 2023-07-13 22:14
@robertKozik it does not happen on main though!

**Comment by robertKozik** [comment] 2023-07-13 22:15
You're right. Must be something here

**Comment by francoisl** [comment] 2023-07-14 22:24
Should we close this and centralize discussions in https://github.com/Expensify/App/issues/22803 instead? That was the original issue, which is still open because of the revert for this issue here.

**Comment by francoisl** [comment] 2023-07-18 17:26
Let's close this issue and keep the discussion in https://github.com/Expensify/App/issues/22803 

@joekaufmanexpensify we'll just need to compensate @Santhosh-Sellavel for reviewing the internal fix PR https://github.com/Expensify/App/pull/22845

**Comment by joekaufmanexpensify** [comment] 2023-07-18 18:21
@francoisl Sounds good! Just to clarify, you mean don't complete the BZ checklist here (as this was a regression of the other issue). And then just pay @Santhosh-Sellavel for reviewing the PR fix here (once the 7 day regression period is up on 2023-07-21?

If so, that sounds good to me!

**Comment by francoisl** [comment] 2023-07-18 18:29
Correct, no need to complete the BZ checklist.

**Comment by joekaufmanexpensify** [comment] 2023-07-18 18:33
Cool cool, thanks! Going to set this back to weekly for now. And then we'll pay Santhosh $1,000 for reviewing on 2023-07-01!

**Comment by joekaufmanexpensify** [comment] 2023-07-21 13:17
@Santhosh-Sellavel when you have a sec, could you please request $1,000 for this issue, and leave a comment here once you've submitted your request?

**Comment by Santhosh-Sellavel** [comment] 2023-07-21 20:37
Requested on ND

**Comment by anmurali** [comment] 2023-07-23 07:41
Approved

**Comment by dhanashree-sawant** [comment] 2023-07-23 08:21
Hi @francoisl, @joekaufmanexpensify is it eligible for reporting bonus?

**Comment by joekaufmanexpensify** [comment] 2023-07-24 12:38
Ah, yep thanks for pointing that out @dhanashree-sawant . This is eligible for a reporting bonus.

**Comment by joekaufmanexpensify** [comment] 2023-07-24 12:39
Adding external label to create upwork job

**Comment by joekaufmanexpensify** [comment] 2023-07-24 12:40
@dhanashree-sawant offer sent for $250!

**Comment by joekaufmanexpensify** [comment] 2023-07-24 13:36
@dhanashree-sawant $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-07-24 13:36
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-07-24 13:36
All payment is issued, closing as this is all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-07-24 13:36 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
