### ISSUE TITLE
Profile - When adding magic code offline Block icon is displayed instead of Loading icon

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22176] opened 2023-07-04 13:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Navigate to account settings > Profile
3. Click on "Contact Method"
4. Click on "New Contact method"
5. Add e-mail address and click "Add" button
6. Navigate to the email inbox of the new contact method
7. Verify there's an email to "Verify secondary email for Expensify"
8. Copy the Magic Code included in the email
9. Disable the internet connection
10. Back in NewDot - paste the magic code in the field
11. Try to click on "Verify" button

## Expected Result:
There should be a loading icon on the button

## Actual Result:
Block icon is displayed instead of Loading icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c66e7d34-5001-46b4-a02f-1f3d370c231d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment] 2023-07-05 11:16
I agree with @samh-nl that this should be the intended behavior. Closing this GH.

**Closed by flaviadefaria** 2023-07-05 11:16 UTC
Labels: Daily, Bug
