### ISSUE TITLE
 Workspace - The price $9 in upgrade page is not legible in light mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44965] opened 2024-07-08 13:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43822
## Action Performed:
Precondition:
- App theme is light
1. Go to staging.new.expensify.com
2. Go to Workspace settings.
3. Add upgrade/report-fields to the url (eg, https://staging.new.expensify.com/settings/workspaces/31DF97D37125FBD6/upgrade/report-fields
)

## Expected Result:
The content will be legible in light mode

## Actual Result:
The price $9 is not legible in light mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![08 07 2024](https://github.com/Expensify/App/assets/78819774/31feb39b-5fa5-485f-860e-5745f3904245)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-08 13:48
@Gonals  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-08 13:49
We think that this bug might be related to #wave-collect - Release 2

**Comment by etCoderDysto** [comment] 2024-07-08 13:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The price $9 in upgrade page is not legible in light mode
### What is the root cause of that problem?
We are passing `styles.textWhite` instead of `styles.themeTextColor` here

https://github.com/Expensify/App/blob/51dd814bf6a142fbaf590b69f90932dec2fe6507/src/pages/workspace/upgrade/UpgradeIntro.tsx#L50
### What changes do you think we should make in order to solve the problem?
Change `styles.textWhite` to `styles.themeTextColor` below 
https://github.com/Expensify/App/blob/51dd814bf6a142fbaf590b69f90932dec2fe6507/src/pages/workspace/upgrade/UpgradeIntro.tsx#L50

### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment] 2024-07-08 14:27
This was a side effect of [this PR](https://github.com/Expensify/App/pull/43822). 

@allroundexperts after the other PR review, would you mind submitting a small fix here that uses the theme text colour?

**Comment by Julesssss** [comment] 2024-07-08 14:50
I realise this shouldn't be a blocker as the feature is locked, but I had already started...

PR in review

**Comment by Julesssss** [comment] 2024-07-08 14:59
Merged, no need to CP

**Closed** 2024-07-30 14:29 UTC
Labels: Reviewing, Engineering, Weekly, Improvement
