### ISSUE TITLE
Web - Send Money - If currency is changed and send money is sent from specific account, error page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32597] opened 2023-12-06 22:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into [applausetester+emilio@applause.expensifail.com](mailto:applausetester+emilio@applause.expensifail.com)
3. Click on send money
4. Change the default Currency
5. Submit the send money flow and click on "Pay elsewhere"
6. Click on the iOU twice

## Expected Result:
User expects to be redirected to the IOU details page

## Actual Result:
User receives a page not found error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/be6065ae-a8b8-4cf2-aaa0-dc95595340b4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2023-12-06 23:42
Removing deploy blocker label because I reproduced in production:


https://github.com/Expensify/App/assets/87341702/b178c291-c74e-4412-bfcf-5f6bafc85cd0

**Comment by aldo-expensify** [comment] 2023-12-08 19:27
I tried to investigate to see if this should be external or internal, but I'm failing to reproduce in dev, staging and production. 
I also tested with the account applausetester+emilio@applause.expensifail.com in staging.

@lanitochka17 can you confirm if this is still reproducible? 🙏 If it is not, we can close :)

**Comment by bfitzexpensify** [comment] 2023-12-11 21:54
I tested with the applausetester+emilio@applause.expensifail.com account on staging too and also could not reproduce - so let's close this one out for the moment.

**Closed by bfitzexpensify** 2023-12-11 21:54 UTC
Labels: Engineering, Daily, Overdue, Bug
