### ISSUE TITLE
[$1000] Inconsistent spacing in workspace modal header.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21460] opened 2023-06-23 21:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into an account with a workspace already created.
2. Click on settings in the LHN header (the circular avatar icon).
3. Click on workspaces and then click on a workspace.
4. Observe the space between the screen's right edge and the 3 vertical dots in the modal's header and the same space with the right-facing arrows below.
## Expected Result: 
The 3 vertical dots should be aligned with the right-facing arrows below it.
## Actual Result: 
The 3 vertical dots are aligned slightly to the left of the right-facing arrows.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![expensify-workspaces-modal-header-spacing](https://github.com/Expensify/App/assets/43996225/e23ff68f-c696-479f-9f14-995da9b8d598)

<img width="945" alt="Screenshot (374)" src="https://github.com/Expensify/App/assets/43996225/8d6b962d-60ab-44d2-aa82-12cb24a3b6f5">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687075680956699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f7e04ac05c5ce5c</li>
        <li>Upwork Job ID: 1672433479678611456</li>
        <li>Last Price Increase: 2023-06-24</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-06-24 02:36
Oh yeah, it is inconsistent!

**Comment by crystal6117** [comment] 2023-06-24 04:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In workspace modal, all right icons including 3-dot and right arrow icons are not aligned. And in my view, all left icons are not aligned, too.

### What is the root cause of that problem?
Current styling are not adjusted to align them. Here is a screenshot to show the root case.
![Screenshot 2023-06-23 at 10 50 56 PM](https://github.com/Expensify/App/assets/55975468/29314ef1-2a3d-4b7b-a891-e2ecbf471b60)

### What changes do you think we should make in order to solve the problem?
1. Should adjust style that the workspace header and every items have the same padding, so that all left and right icons in the header and every items are aligned.
2. Should solve the problem due to the width of scrollbar for web and desktop platforms.
To solve this problem, we can create an overlay scrollbar that sits on top of the content, without affecting the layout. This approach allows the content to retain its dimensions while still providing scrolling functionality. You can achieve this by combining overflow with position: relative on the container, and position: absolute on the scrollbar.
```
.container {
  position: relative;
  overflow: hidden;
}

.scrollbar {
  position: absolute;
  right: 0;
  top: 0;
  bottom: 0;
  width: 10px;
  /* Add any other desired styling */
}
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by nitin-kukreti** [comment] 2023-06-24 08:18
# Proposal
   ## Please re-state the problem that we are trying to solve in this issue.
   In workspace modal, all right icons including 3-dot and right arrow icons are not aligned. And in my view, all left icons are not aligned, too.
  ## What is the root cause of that problem?
  the root cause of problem is not because of any code glitch it just a different browser render scroll bar differently for example in Firefox their scrollbar position is absolute but in Chrome and some other browser position of scrollbar is not absolute its static.
  ### Firefox example
 you can see that their is no problem in Firefox because position of scrollbar in Firefox web-kit is absolute
[Screencast from 24-06-23 01:32:46 PM IST.webm](https://github.com/Expensify/App/assets/59364817/ae702b21-0c58-4307-a337-ad5d3a2468e3)

   ### Chrome example
  you can see that their is a problem in alignment in chrome because position of scrollbar is not absolute in chrome webkit
[Screencast from 24-06-23 01:36:25 PM IST.webm](https://github.com/Expensify/App/assets/59364817/16588bca-e88b-4162-bacb-a64d03b6c861)

  ## What changes do you think we should make in order to solve the problem?
  solution 1 : we can remove scroll bar by content will be scroll-able  but scrollbar will be not shown
[Screencast from 24-06-23 01:44:25 PM IST.webm](https://github.com/Expensify/App/assets/59364817/ac34b424-e860-4d2a-8600-98b0ad94c59f)
 solution 2:  After implement first solution if showing scrollbar is necessary then we can create our own custom scrollbar component  and attach it to scroll view

**Comment by nitin-kukreti** [comment] 2023-06-24 16:43
Is this job is open

**Comment by nitin-kukreti** [comment] 2023-06-25 05:37
## Proposal
[Updated](https://github.com/Expensify/App/issues/21460#issuecomment-1605307458)

**Comment by Serg-Kochkin** [comment] 2023-06-25 15:25
Hi there.
I found one of the solutions how to fix this issue, we can add a conditional (ternary) operator to the style of View component if a button with three dots is passed to it, so it will look like this:

`this.props.shouldShowThreeDotsButton? styles.pr4 : styles.pr5`

This way it won't break the alignment for other buttons.

Also, I have some other solutions, so let me know if this solution is not acceptable.

**Comment by Serg-Kochkin** [comment] 2023-06-25 15:30
Contributor details
Your Expensify account email: serhiy.kochkin@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e41c99d55ac7ccab

**Comment by nitin-kukreti** [comment] 2023-06-25 15:54
> Hi there. I found one of the solutions how to fix this issue, we can add a conditional (ternary) operator to the style of View component if a button with three dots is passed to it, so it will look like this:
> 
> `this.props.shouldShowThreeDotsButton? styles.pr4 : styles.pr5`
> 
> This way it won't break the alignment for other buttons.
> 
> Also, I have some other solutions, so let me know if this solution is not acceptable.

this will not work because this issue arise due to extra space taken by scrollbar by some browsers because they render it differently .
one solution will be we completely align items to left but it will not look good.
best solution is we can design custom scrollbar for scroll view component which display property will be absolute so user experience remain same in each and every browser and device

**Comment by jliexpensify** [comment] 2023-06-25 21:58
Hi @nitin-kukreti 

>Is this job is open?

For future reference, anything with the `Help Wanted` label is open and available for proposals. So anytime you can see this label on a GH, you can assume that we're seeking proposals.

For your comment [here](https://github.com/Expensify/App/issues/21460#issuecomment-1606141007), we appreciate your input, but keep in mind that it's the C+'s job (i.e. @mananjadhav) to determine the best solution and choose someone based on their proposal.

**Comment by nitin-kukreti** [comment] 2023-06-26 03:54
@jliexpensify thank you so much for information

**Comment by mananjadhav** [comment] 2023-06-26 05:44
I don't see this as an alignment issue. I think we're mixing the header and the content. Had it been the content is overflowing and the header is a bit reduced width then it could be an issue.

Nevertheless, I would still like to confirm from @shawnborton @Expensify/design and weigh in their thoughts. If we want to align the header and the content, I'll take a look at the proposals.

**Comment by nitin-kukreti** [comment] 2023-06-26 12:25
@mananjadhav  Yes you are right their is no any alignment issue pic which was shared by @kavimuru is already align but vertical  line which was drawn by him it seem to be not align but it  is align as width of hamburger icon is less than width of arrow icon .
but when you run this app in chrome browser you feel in desktop you seen alignment issue which is arise due to scrollbar display property in  static so its shifts all elements towards rightward direction.

**Comment by shawnborton** [comment] 2023-06-26 13:25
I'm not so sure that this is really a bug. I think I would recommend we just close this one - most platforms won't even show the scrollbar anyways. 

I'm not sure if we want to purposely hide the scrollbar either, even though it does look nicer.

**Comment by nitin-kukreti** [comment] 2023-06-26 13:43
@shawnborton  yes this is not a bug It arise due to different browser implemented scrollbar styling differently.
if we hide scrollbar then issue will be resolve but we have to do at each position where we have implemented ScrollView
because we are using hard-coded scroll-view component in code-base
Or 
We can create custom component for ScrollView component which have it own dedicated scrollbar but that process will be little complex because in that we have perform some mathematical  calculation for scrollbar

**Comment by shawnborton** [comment] 2023-06-26 13:51
Yeah I hear you, or I might recommend that we just do nothing here.

**Comment by mananjadhav** [comment] 2023-06-27 03:21
I would also recommend closing this one out. In case we find bigger issues then we can put efforts in hiding the scrollbar?

wdyt @shawnborton @jliexpensify ?

**Comment by nitin-kukreti** [comment] 2023-06-27 03:56
@shawnborton  @mananjadhav  @jliexpensify  
I can do this work without any up-work job if you think its smaller issue for an up-work job. should I send PR for it at least I will got  contributor tag.

**Comment by shawnborton** [comment] 2023-06-27 10:39
Cool, I say we close this out.

**Comment by jliexpensify** [comment] 2023-06-28 00:21
Job removed from Upworks, closing out! Thanks Shawn.

**Closed by jliexpensify** 2023-06-28 00:21 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by AmirTallap** [comment] 2023-06-28 20:05
Contributor details
Your Expensify account email: fox.4.billing@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01997c67035623a7ba
