### ISSUE TITLE
[$500] "Hmm, it's not here page" when clicking "Description" in send money flow

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36711] opened 2024-02-16 16:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jamesdeanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708042986840429

## Action Performed:
1. Click on FAB and select "send money"
2. Enter amount and select a member
3. Click on "Description"

## Expected Result:
Able to add the description

## Actual Result:
"Hmm...it's not here." page appears

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/adefcbf1-9c61-4dd5-9d7f-c94dfbcac4ce

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d41934c99998d4c</li>
        <li>Upwork Job ID: 1758527199783079936</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2024-02-16 16:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Hmm, it's not here page" when clicking "Description" in send money flow
### What is the root cause of that problem?
The transaction Id is missing
### What changes do you think we should make in order to solve the problem?
Use `withFullTransactionOrNotFound` in [compose](https://github.com/Expensify/App/blob/bea6aafa5e1b4a80462c3da1f3c56325d3a3977d/src/pages/iou/steps/MoneyRequestConfirmPage.js#L441C16-L441C23) of `MoneyRequestConfirmPage` .
This approach is already used in [IOURequestStepConfirmation](https://github.com/Expensify/App/blob/bea6aafa5e1b4a80462c3da1f3c56325d3a3977d/src/pages/iou/request/step/IOURequestStepConfirmation.js#L468C5-L468C34)

### What alternative solutions did you explore? (Optional)

**Comment by force2008** [comment] 2024-02-18 10:36
### Please re-state the problem that we are trying to solve in this issue.
![image](https://github.com/Expensify/App/assets/931868/d8edbb70-3014-4bc4-b3b0-861dd744635b)

### What is the root cause of that problem?
when click on the Description item in src\components\MoneyRequestConfirmationList.js , it navigates to the action of edit, which will check the transactionID, then cause FullPageNotFoundView show.


![image](https://github.com/Expensify/App/assets/931868/f86f3b97-670f-4eed-852a-fc56e74f0e29)

### What changes do you think we should make in order to solve the problem?
change action type will solve the issue

### What alternative solutions did you explore? (Optional)
none

**Comment by aneequeahmad** [comment] 2024-02-19 19:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When click on Description in send money flow "Hmm, its not here page" appears

### What is the root cause of that problem?
When [Action performed](https://github.com/Expensify/App/issues/36711#:~:text=Click%20on%20FAB,Click%20on%20%22Description%22) `Route` isn't correct for `Description Page`
### 
**Reason:**

- Route For `Description page` was updated for `request amount flow` which has a transactionID already created for new money request. 

- Also if noticed the `Route`  is like `send/new/amount/` on send money flow confirmation page and when clicked on amount and when description option is clicked the url changes to `edit/send/description/undefined/?backTo=%2Fsend%2Fnew%2Fconfirmation%2F` which is isn't correct for send money flow. 

### What changes do you think we should make in order to solve the problem?


[Here](https://github.com/Expensify/App/blob/9cd533b9374bbfe1a27e0dd47c03724cfa918ad5/src/components/MoneyRequestConfirmationList.js#L674-L676) need to check if it's send money flow `if(props.iouType === CONST.IOU.TYPE.SEND)` then Route should be like `send/new/description/` like it used to be till app version `v1.4.38-6`


### What alternative solutions did you explore? (Optional)

N/A

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by brandonhenry** [comment] 2024-02-20 04:25
## Problem Statement

When a user tries to add a description in the send money flow, they encounter a "Hmm...it's not here." page instead of being able to add the description.

## Root Cause

The issue is related to the navigation route parameters passed to `Navigation.navigate()` in the `MoneyRequestConfirmationList` [component](https://github.com/Expensify/App/blob/9cd533b9374bbfe1a27e0dd47c03724cfa918ad5/src/components/MoneyRequestConfirmationList.js#L677). Specifically, we don't want to use `ROUTES.MONEY_REQUEST_STEP_DESCRIPTION`. This is the wrong route, this points to https://github.com/Expensify/App/blob/5427e8fb70e183ba4eeece4b40348b5efbe8ba7d/src/libs/Navigation/linkingConfig/config.ts#L366

This results in an error because that specific routes expects a `transaction` and `transaction.transactionID` in order to build it. However, where we are calling that function `MoneyRequestCategoryPage` / `MoneyRequestConfirmationList`, we are initializing transaction to `{}` and transactionID to `''`. 

`ROUTES.MONEY_REQUEST_STEP_DESCRIPTION` is actually tied to https://github.com/Expensify/App/blob/1806422ea2208540a89271da7026799a1ade9d69/src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx#L90C28-L90C44 

That is a different route, specifically for when someone is requesting and not sending. So, we need a new screen for send description 


## Proposed Solution

1. **Add a New Screen for Money Request Description:**
   - Create a new screen `SCREENS.MONEY_REQUEST_DESCRIPTION` in the `SCREENS` constant file.
   - Define the corresponding route in the `ROUTES` constant file and the linking configuration.

2. **Update Navigation in `MenuItemWithTopDescription`:**
   - Replace the incorrect route `ROUTES.MONEY_REQUEST_STEP_DESCRIPTION` with the new route for `SCREENS.MONEY_REQUEST_DESCRIPTION` in the `onPress` callback.

```javascript
Navigation.navigate(
    ROUTES.MONEY_REQUEST_DESCRIPTION.getRoute( // change here
        CONST.IOU.ACTION.EDIT,
        props.iouType,
        transaction.transactionID,
        props.reportID,
        Navigation.getActiveRouteWithoutParams(),
    ),
);
```

3. **Implement the Description Screen:**
   - Implement the Description screen based on how we have implemented screens in the past. For example `src/pages/ious/steps/MoneyRequestCategoryPage.js`

https://github.com/Expensify/App/commit/ab6a7ec2a7a2cbf7f182989b82b8f9fcae932309#diff-6e896ede958248cb2e8e85d63852f3412c3cad4c9842fc87f1504f691a67f9b9

  - Design screen based on `IOUSRequestStepDescription.js`

https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepDescription.js

4. **Test the Flow:**
   - Ensure that navigating to the description screen works correctly and that the user can add and save a description successfully.

For the `SCREENS` and `ROUTES` constant files:

In `SCREENS` constant file:
```javascript
const SCREENS = {
    ...
    MONEY_REQUEST_DESCRIPTION: 'MoneyRequestDescription',
    ...
};
```

In `ROUTES` constant file:
```javascript
const ROUTES = {
    ...
    MONEY_REQUEST_DESCRIPTION: {
        route: ':iouType/new/description/:reportID?',
        getRoute: (iouType: string, reportID = '') => `${iouType}/new/description/${reportID}` as const,
    },
    ...
};
```

Make sure to adjust the implementation details according to your project structure and naming conventions.

**Comment by aneequeahmad** [comment] 2024-02-20 15:06
@brandonhenry Isn't your proposal the duplicate of my proposal ? Thats the same root cause and solution that i have posted. You just explained what i proposed.

**Comment by JmillsExpensify** [comment] 2024-02-21 01:58
@eVoloshchak thoughts on the proposals so far?

**Comment by eVoloshchak** [comment] 2024-02-26 01:09
Agree with @ZhenjaHorbach's [comment](https://github.com/Expensify/App/issues/36711#issuecomment-1948844987), this is a duplicate of https://github.com/Expensify/App/issues/36342 (which is on hold)

**Comment by eVoloshchak** [comment] 2024-02-28 22:09
Not overdue, https://github.com/Expensify/App/issues/36711#issuecomment-1963149983

**Comment by eVoloshchak** [comment] 2024-03-04 22:09
@JmillsExpensify, I think we should close this since it's a duplicate of https://github.com/Expensify/App/issues/36342

**Comment by srikarparsi** [comment] 2024-03-08 02:17
Hey! Yup, this looks like a duplicate of https://github.com/Expensify/App/issues/36342. I can take care of it in the other issue so I think we can close it out here @JmillsExpensify

**Closed** 2024-03-13 04:41 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
