### ISSUE TITLE
 [PAID][$250] Categories -Empty state does not display introduction text right after deleting all categories

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46238] opened 2024-07-25 20:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Network should be slow
1. Go to staging.new.expensify.com
2. Go to workspace settings
3. Go to Categories
4. Delete all the categories
5. Note that the empty state does not show the introduction text after deleting all the categories
6. Go to Troubleshoot > Clear cache and restart > Reset and restart
7. Return to workspace settings > Categories
8. Now the empty state shows the introduction text

## Expected Result:
In Step 5, the empty state will display the introduction text right after deleting all the categories

## Actual Result:
In Step 5, the empty state does not display the introduction text right after deleting all the categories
It only displays after the categories are really deleted or clearing cache and restarting app

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e718e710-1fcf-4a1a-98aa-5307018492b5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a227da0825fc4b73</li>
        <li>Upwork Job ID: 1818264117366582298</li>
        <li>Last Price Increase: 2024-07-30</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103402129</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by lanitochka17** [comment] 2024-07-25 20:53
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-07-25 21:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Categories -Empty state does not display introduction text right after deleting all categories
### What is the root cause of that problem?
We are displaying the text if the category list is zero but it is not zero 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L313-L314
### What changes do you think we should make in order to solve the problem?

We should change it to
```
                {(!shouldUseNarrowLayout || !hasVisibleCategories || isLoading) && getHeaderText()}

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-25 21:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Categories -Empty state does not display introduction text right after deleting all categories
### What is the root cause of that problem?
We are displaying the text if the `categoryList` length is zero but when we delete categories only `pendingAction` to delete  
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L313-L314
### What changes do you think we should make in order to solve the problem?

We should change it to
```
                {(!shouldUseNarrowLayout || !hasVisibleCategories || isLoading) && getHeaderText()}

```

### What alternative solutions did you explore? (Optional)
We might need to create a new variable by taking out `isOffline` variable in the definition of `hasVisibleCategories` here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L260-L261

Alternatively We can also use both conditions like
```
                {(!shouldUseNarrowLayout || !hasVisibleCategories ||categoryList.length === 0 || isLoading) && getHeaderText()}

```

**Comment by nkdengineer** [comment] 2024-07-26 04:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 5, the empty state does not display the introduction text right after deleting all the categories
It only displays after the categories are really deleted or clearing cache and restarting app

### What is the root cause of that problem?
We're displaying the introduction text on the small screen if there is no category in the list. But when we delete the category we only update `pendingAction` to `delete` in optimistic data. So the introduction text is not displayed immediately after we delete all categories

https://github.com/Expensify/App/blob/0559307e0b0fb0d08d454b68a21adf8b984a9553/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L313

This bug also happens on the tag page since we use the same condition.
https://github.com/Expensify/App/blob/0559307e0b0fb0d08d454b68a21adf8b984a9553/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L336
### What changes do you think we should make in order to solve the problem?
We should replace this condition`categoryList.length === 0` with `!hasVisibleCategories` that already checked the categories have pending action is `delete`

```
{(!shouldUseNarrowLayout || !hasVisibleCategories || isLoading) && getHeaderText()} 
```
https://github.com/Expensify/App/blob/0559307e0b0fb0d08d454b68a21adf8b984a9553/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L313

And we need to do the same for the tag page

```
{(!shouldUseNarrowLayout || !hasVisibleTag || isLoading) && getHeaderText()} 
```
https://github.com/Expensify/App/blob/0559307e0b0fb0d08d454b68a21adf8b984a9553/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L336

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-07-26 04:27
[Proposal updated](https://github.com/Expensify/App/issues/46238#issuecomment-2251945346)

- Add a similar bug on the report field page

**Comment by sobitneupane** [comment] 2024-08-02 12:40
Thanks for the proposal everyone.

I can easily reproduce the issue in Tags as well. [Proposal](https://github.com/Expensify/App/issues/46238#issuecomment-2251945346) from @nkdengineer looks good to me. It covers all the cases.

🎀 👀 🎀 C+ reviewed

**Comment by NikkiWines** [comment] 2024-08-02 12:47
thanks for confirming the auto-assignment there github-actions 😛

**Comment by FitseTLT** [comment] 2024-08-02 12:53
> Thanks for the proposal everyone.
> 
> I can easily reproduce the issue in Tags as well. [Proposal](https://github.com/Expensify/App/issues/46238#issuecomment-2251945346) from @nkdengineer looks good to me. It covers all the cases.
> 
> 🎀 👀 🎀 C+ reviewed

Tag and report fields are not in the scope of the OP but you are making it the main reason to not select my first proposed solution before 3 hours [here](https://github.com/Expensify/App/issues/46528#issuecomment-2264956117) and yesterday [here](https://github.com/Expensify/App/issues/46204#issuecomment-2263777531) on another issue I proposed a proposal that covers all cases but it wasn't selected because it is out of scope. The selection process is super frustrating honestly speaking. 
cc @NikkiWines

**Comment by FitseTLT** [comment] 2024-08-02 13:26
> I don't think this case is the same as this [issue](https://github.com/Expensify/App/issues/46528#issuecomment-2264956117).
> 
> * In the mentioned issue, other related places also use the same data that is `listValues` and we can easily think of it in the PR.
> * In this issue, each page uses different data and we can easily miss some cases in the PR phase if nobody mentions it in the proposal.

You are raising a subjective discussion topic here @nkdengineer obviously you want your proposal selected and you praise the out of scope cases you covered in your proposal, but at the end, it is the same case and the inconsistency in the decision making is frustrating. We should make a consistent decision guide on these type of decisions.

**Comment by sobitneupane** [comment] 2024-08-02 13:42
> In the case of workspace tag and field page this issue doesn't occur because the data is emptied when we delelte all the lists but only for category case the pendingAction is set to delete instead of deleting the list, therefore this bug occurs and so:

@FitseTLT, you mentioned in your proposal that the issue is not reproducible on the tag and field pages. However, it is indeed reproducible, and these pages cannot be considered out of scope as the issue occurs in different features on the same page. @nkdengineer had correctly covered all those cases in his proposal. Therefore, I had to go with his proposal. I am completely open to following your proposal if @NikkiWines thinks otherwise.

**Comment by FitseTLT** [comment] 2024-08-02 14:09
> > In the case of workspace tag and field page this issue doesn't occur because the data is emptied when we delelte all the lists but only for category case the pendingAction is set to delete instead of deleting the list, therefore this bug occurs and so:
> 
> @FitseTLT, you mentioned in your proposal that the issue is not reproducible on the tag and field pages. However, it is indeed reproducible, and these pages cannot be considered out of scope as the issue occurs in different features on the same page. @nkdengineer had correctly covered all those cases in his proposal. Therefore, I had to go with his proposal. I am completely open to following your proposal if @NikkiWines thinks otherwise.

@sobitneupane If you offline delete tags or fields and turn online in tags and fields page the list is not cleared only until the response comes from the server but in the categories case the server doesn't clear the categories list at all but only sets the pendingAction to delete so the issue persists and that's why the issue's OP only includes categories and not tags I was refering to that difference in my proposal (`is not reproducible on the tag and field page`). The case for tags and fields is just on in the scope of the OP and the problem is not the same as for categories. Here is a debug video

https://github.com/user-attachments/assets/10c62a7b-91ec-424d-b483-eb695e15d08c

**Comment by nkdengineer** [comment] 2024-08-02 14:26
We can easily see that the bug also happens briefly for the tag page in the video of OP

https://github.com/user-attachments/assets/0c4f20f0-d3a0-4894-ac25-055159a890c9

**Comment by NikkiWines** [comment] 2024-08-05 13:59
I agree with @sobitneupane's review and also noticed that the issue was visible for Tags in the video for the OP - I don't think it's out of scope for this issue to try to solve the case for both. @nkdengineer's proposal is the best fit to solve the problem most comprehensively. 

@FitseTLT, the evaluation that occurs on one issue isn't always directly applicable to another - we evaluate each on a case-by-case basis. I understand that it's not a perfect system and can sometimes be frustrating, but please try to keep your discussions amicable instead of accusatory. Thanks! 🙇

**Comment by sonialiap** [comment] 2024-08-16 13:11
@strepanier03 I'm OOO Aug 19-30, adding leave buddy. 
Status: waiting for build

**Comment by strepanier03** [comment] 2024-08-22 22:56
Contract paid and closed.

**Closed by strepanier03** 2024-08-22 22:56 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug

**Comment by sobitneupane** [comment] 2024-08-23 05:50
@strepanier03 I will need payment summary to request payment in newDot.

**Comment by sobitneupane** [comment] 2024-09-02 08:43
Bump @strepanier03

**Comment by sobitneupane** [comment] 2024-10-21 08:41
@strepanier03 @sonialiap I will need payment summary to request payment in newDot.

**Comment by sonialiap** [comment] 2024-10-23 15:46
Payment summary:
- @sobitneupane $250 please request in ND
- nkdengineer $250 paid in [upwork](https://www.upwork.com/ab/applicants/1818264117366582298/hired)

**Comment by garrettmknight** [comment] 2024-12-12 10:58
$250 approved for @sobitneupane
