### ISSUE TITLE
[HOLD for payment 2023-07-12] [HOLD for payment 2023-07-10] Copilot - Copilot and regular account actions are displayed the same in #admins room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21970] opened 2023-06-30 17:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21246
## Action Performed:
OldDot:
1. Create Control policy
2. Make changes in policy setting both under regular account and then co-pilot (or copilot and then regular account)
NewDot:
3. Verify there is visual difference between actions taken under regular account and copilot

## Expected Result:
Regular account and copilot should be displayed differently.

## Actual Result:
All actions taken by both accounts are displayed under the name who did first actions

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2613adba-c822-4d56-b6c0-be0b1bda60c2

https://github.com/Expensify/App/assets/78819774/8ede2fb7-3bf1-45f5-9c9a-cc7072847ab8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by tylerkaraszewski** [comment] 2023-06-30 21:09
@hayata-suenaga - Since you reviewed the original PR I'm handing this to you, I unfortunately can't look into it as I'm about to leave on my sabbatical.

**Comment by hayata-suenaga** [comment] 2023-06-30 21:33
I was able to reproduce

<img width="400" alt="Screenshot 2023-06-30 at 2 32 23 PM" src="https://github.com/Expensify/App/assets/98560306/f360b939-5a39-4189-89c3-b1fcc524059a">

The last message should be sent from a copilot account

**Comment by hayata-suenaga** [comment] 2023-06-30 21:41
When there are time gap between when the actual user and when the copilot edit the policies, the policy log message is sent from a correct person.

However, when the time is short, the the account of first person who make changes to the policy (actual user or copilot user) is used for subsequent messages.

**Comment by hayata-suenaga** [comment] 2023-06-30 21:49
I think these lines should not exists will test on my dev

https://github.com/Expensify/App/blob/50c16acc8365839d0de581701fcdb8811c2ee4eb/src/pages/home/report/ReportActionItemSingle.js#L85-L93

**Comment by hayata-suenaga** [comment] 2023-06-30 22:54
the above method didn't work.

I'm still investigating I gonna ask help on slack

**Comment by hayata-suenaga** [comment] 2023-06-30 23:07
still not working. When the copilot takes action, the policy change log message is shown as taken by the real user, not the copilot.

<img width="400" alt="Screenshot 2023-06-30 at 4 06 03 PM" src="https://github.com/Expensify/App/assets/98560306/cac94e80-91bb-4e97-b00a-6d4511d804e1">

**Comment by hayata-suenaga** [comment] 2023-06-30 23:19
@yuwenmemon please disregard the screenshot above https://github.com/Expensify/App/issues/21970#issuecomment-1615264600

that is the effect from the code change I made in https://github.com/Expensify/App/issues/21970#issuecomment-1615224701

**Comment by Julesssss** [comment] 2023-07-03 13:24
The fix for this was [merged and Cp'd ](https://github.com/Expensify/App/pull/22006). Marking it off the checklist 👍

**Comment by yuwenmemon** [comment] 2023-07-11 22:58
This does not need payment it was all internal

**Closed by yuwenmemon** 2023-07-11 22:58 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
