### ISSUE TITLE
Report - Unresponsive report header

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43898] opened 2024-06-18 12:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to any chat
2. Click on chat header

## Expected Result:
User's profile page should open

## Actual Result:
Report header is not responding to a click

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/833a7e6b-354c-48e6-8d78-2f1f00ebdfd5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-06-18 12:58
We think that this bug might be related to  #vip-vsb

**Comment by srikarparsi** [comment] 2024-06-18 17:23
This is frontend because it's only reproducible on the desktop version, removing the regular DeployBlocker label.

**Comment by srikarparsi** [comment] 2024-06-18 23:37
It looks like there's a problem with the onPress function [here](https://github.com/Expensify/App/blob/main/src/pages/home/HeaderView.tsx#L250) on desktop. I added a `console.log` but it's only logging on web and not on desktop.

**Comment by srikarparsi** [comment] 2024-06-18 23:39
It looks like the search button also isn't working on staging desktop, could be a problem with PressableWithoutFeedback in general?

**Comment by srikarparsi** [comment] 2024-06-18 23:47
Tried reverting these two PRs to see if they could be related ([bump onyx](https://github.com/Expensify/App/pull/43764), [bump expensify-common](https://github.com/Expensify/App/pull/43764)) but didn't fix the bug

**Comment by srikarparsi** [comment] 2024-06-19 02:55
Was caused by this [PR](https://github.com/Expensify/App/pull/43785) and we reverted it [here](https://github.com/Expensify/App/pull/43971)

**Comment by srikarparsi** [comment] 2024-06-19 19:01
Closing this out since this PR was deployed to staging [here](https://github.com/Expensify/App/pull/43971#issuecomment-2177463849). We are re-adding this change [here](https://github.com/Expensify/App/pull/44006) but that is being kept track of in this [issue](https://github.com/Expensify/App/issues/43827).

**Closed by srikarparsi** 2024-06-19 19:01 UTC
Labels: Engineering, Hourly, Bug
