### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] Thread - App shows not here page when clicking on blue "Thread" in thread view

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43172] opened 2024-06-06 14:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Create a manual expense
4. Click on the expense preview to go to expense report
5. Send a message
6. Open the message in thread
7. Click on the blue "Thread" above the parent message

## Expected Result:
App will return to the main chat

## Actual Result:
App shows not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e4fdfe75-db88-48e0-b789-c16f09a5b847

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-06 14:14
@Julesssss  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-06 14:14
We think that this bug might be related to #wave-collect - Release 1

**Comment by Julesssss** [comment] 2024-06-06 14:52
I can reproduce. We seem to get stuck in a loop infinitely calling `OpenReport` and `GetOlderActions`

<img width="140" alt="Screenshot 2024-06-06 at 15 51 54" src="https://github.com/Expensify/App/assets/10736861/4ff66cac-ae94-4da2-b296-7df70f7383ad">

**Comment by Julesssss** [comment] 2024-06-06 15:38
Actually, this isn't always reproducible. Sometimes it does work. Here are some potentially related issues that I will comment on: 
- https://github.com/Expensify/App/pull/43086
- https://github.com/Expensify/App/pull/42554
- https://github.com/Expensify/App/pull/42932
- https://github.com/Expensify/App/pull/43027

**Comment by luacmartins** [comment] 2024-06-06 16:52
@Julesssss I tried to [revert](https://github.com/Expensify/App/pull/43200) https://github.com/Expensify/App/pull/43086, but it did not solve the issue

**Comment by luacmartins** [comment] 2024-06-06 16:55
Here's the [revert PR](https://github.com/Expensify/App/pull/43201) if we decide to revert it

**Comment by ikevin127** [comment] 2024-06-06 17:01
I reported this issue yesterday on #expensify-bugs, tested on staging before the latest production deploy: https://expensify.enterprise.slack.com/archives/C049HHMV9SM/p1717629970008689

**Comment by luacmartins** [comment] 2024-06-06 17:17
That link seems unrelated to this issue

**Comment by ikevin127** [comment] 2024-06-06 17:30
My bad, I mistaken the link / issue.

I posted the same thing here yesterday: https://github.com/margelo/expensify-app-fork/pull/20#issuecomment-2151246149 thinking it's caused by that PR which is not merged yet, therefore confirming that the issue wasn't present yeaterday on staging (at time of testing).

**Comment by kmbcook** [comment] 2024-06-06 20:21
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Thread - App shows not here page when clicking on blue "Thread" in thread view

### What is the root cause of that problem?
The root cause stems from https://github.com/Expensify/App/pull/34640 where ReportUtils.getAllAncestorReportActions was originally written. We now know this because fixing that root cause in https://github.com/Expensify/App/pull/42554 causes this regression. See https://github.com/Expensify/App/issues/41519#issuecomment-2093608757 for details.

### What changes do you think we should make in order to solve the problem?
Address the root cause by using the correct ancestor reportID, instead of leaving the root cause in place and reverting https://github.com/Expensify/App/pull/42554.

**Comment by Julesssss** [comment] 2024-06-07 08:37
Should be fixed with [this ](https://github.com/Expensify/App/pull/43201)revert

**Comment by kmbcook** [comment] 2024-06-07 14:27
This is a duplicate of https://github.com/Expensify/App/issues/43190. See my [proposal](https://github.com/Expensify/App/issues/43190#issuecomment-2153349337) there.

**Comment by luacmartins** [comment] 2024-06-20 20:31
I think we can close this since we fixed it with a revert and it was all done internally

**Closed by luacmartins** 2024-06-20 20:32 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
