### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] Request Money - The gap between error message and 'Next' button is much larger for Request Money's Manual Page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28515] opened 2023-09-29 17:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Click on FAB > Request Money > Manual tab
3. Enter '0' if not already there in the amount
4. Click on Next

## Expected Result:
The gap between the error messages is consistent, just like on other pages, such as Home Address, Legal Name, Date of Birth, etc

## Actual Result:
The gap is much larger than the gap between error message and CTA button on any other page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-09-29 at 9 19 02 PM](https://github.com/Expensify/App/assets/93399543/86360ca5-2b2b-4834-b0a6-ea089de9e03f)
![Screenshot 2023-09-29 at 4 25 04 AM](https://github.com/Expensify/App/assets/93399543/20c072d1-ce0a-43ec-a84b-864c426e4eb5)

https://github.com/Expensify/App/assets/93399543/eac55810-1ef6-46c7-abe9-960df1ee862a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695942566946709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c93d7659514ccde7</li>
        <li>Upwork Job ID: 1707802938882224128</li>
        <li>Last Price Increase: 2023-09-29</li>
<li>Automatic offers: </li>
<ul>
<li>aman-atg | Contributor | 26975517</li>
<li>aman-atg | Reporter | 26975520</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-29 17:02
Proposal by: @aman-atg
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1695942566946709

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The gap between error message and 'Next' button is much larger for Request Money's Manual Page

### What is the root cause of that problem?
We are using `styles.mt5` [here](https://github.com/Expensify/App/blob/dfb3f9b0b536d9640f81a85d59e095581dc06dba/src/pages/iou/steps/MoneyRequestAmountForm.js#L270) which works for platforms where `BigNumberPad` component is visible but for other platforms this much gap is unnecessary. And `FormHelpMessage` itself has marginBottom values which further increases the gap between the error message and the button.
 
### What changes do you think we should make in order to solve the problem?


We can define a variable like `canUseTouchScreen` and use it to determine which value to use for the top margin.

Example:
```jsx
 
                {canUseTouchScreen ? (
                    <BigNumberPad
                      // ...other props
                    />
                ) : null}
                <Button
                    // ...other props
                    style={[styles.w100, canUseTouchScreen ? styles.mt5 : styles.mt2]}
                />
```

Here, I've used `styles.mt2` but we can use any other value as well as per design team's suggestion.
With this, the total gap between will be 12px, considering `styles.mt2` from the Button and styles.mb1 from the `FormHelpMessage`

### What alternative solutions did you explore? (Optional)
We can use various margin spacing combinations for the `FormHelpMessage` and `Button` components, such as using `styles.mb0` and `styles.mt3` respectively when `canUseTouchScreen` is false.

However, changing FormHelpMessage's style will also have an effect when `canUseTouchScreen` is true and BigNumberPad is visible so it needs to be validated by the design team if we choose to do so.

**Comment by saranshbalyan-1234** [comment] 2023-09-29 17:55
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Error message have different space in some places
### What is the root cause of that problem?
Due to extra styles passed as props, we are getting this error.
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/67d4a7acebf613dc8fac9fd1423a7a23d1583e59/src/pages/iou/steps/MoneyRequestAmountForm.js#L260-L274
Just need to replace mt5 with mt3 like this
```javascript
  <Button
                    success
                    medium={isExtraSmallScreenHeight}
                    style={[styles.w100, styles.mt2]}
                    onPress={submitAndNavigateToNextPage}
                    pressOnEnter
                    text={buttonText}
                />
``` 
no need to change it with respect to devices as there is already a condition based on DeviceCapabilities.canUseTouchScreen() on top
### What alternative solutions did you explore? (Optional)
N/A

**Comment by Gonals** [comment] 2023-10-02 08:12
Sounds good to me! @aman-atg, can you comment in this GH? It won't let me assign you otherwise 😁

**Comment by Gonals** [comment] 2023-10-02 08:20
Assigned!

**Comment by flaviadefaria** [comment] 2023-10-12 10:42
@allroundexperts can you please respond to the above comment so that I can issue payment? Thanks!

**Comment by flaviadefaria** [comment] 2023-10-16 09:53
Bump @allroundexperts I'm no longer in BZ team but should action this as it was due last week. Thanks!

**Comment by flaviadefaria** [comment] 2023-10-16 09:54
Payment Summary:

>For reference, here are some details about the assignees on this issue:
@aman-atg requires payment [offer](https://www.upwork.com/nx/wm/offer/26975517) (Contributor)
@allroundexperts does not require payment (Eligible for Manual Requests)
@aman-atg requires payment [offer](https://www.upwork.com/nx/wm/offer/26975517) (Contributor)

@aman-atg - $500 + $250 (50% bonus) + $50 (reporting bonus) = $800
@allroundexperts - $500 + $250 (50% bonus) = $750

**Comment by flaviadefaria** [comment] 2023-10-18 14:15
@allroundexperts, @NicMendonca misinterpreted the internal documentation - we just clarified this internally. There's no additional bonus for reporting and fixing their own bug. They simply get paid the reporting bonus on top of what they get for fixing the bug. So $800 is the correct amount.

**Comment by flaviadefaria** [comment] 2023-10-18 14:19
@aman-atg you've been paid so closing this GH.

**Closed by flaviadefaria** 2023-10-18 14:19 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-18 18:18
$750 payment approved for @allroundexperts based on BZ summary.
