### ISSUE TITLE
[$500] Chat - Composer add new line or point instead of space when user enter space

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28729] opened 2023-10-03 15:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Fill in composer with some characters without space until 4 lines
2. move cursor to the start of second line of composer and then enter space
3. Notice instead of space new line is inserted. Try to enter it multiple times, new lines are inserted instead of spaces. (On macos chrome - web -mweb)
4. On android and ios (notice a point is inserted when user entering space and have some weird behavior)

## Expected Result:
Composer must insert space when user press space key

## Actual Result:
Composer insert new line or point instead of space

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.76-6

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/cc45a692-d522-428a-bf47-ffb4c7003277

https://github.com/Expensify/App/assets/115492554/0948ead5-343f-4d2e-af3e-ffda471683db

https://github.com/Expensify/App/assets/115492554/af53d8f1-31ae-441b-ac4c-955e37123b88

https://github.com/Expensify/App/assets/115492554/03275d69-53ee-40cc-9474-77f7ee1f0ad0

https://github.com/Expensify/App/assets/115492554/0b793d18-6803-46ab-970e-bdbedffca0c9

https://github.com/Expensify/App/assets/115492554/21f200ca-8e3d-4b3b-82b7-2ca4ff5938af

https://github.com/Expensify/App/assets/115492554/eff71f2e-060e-4ff3-8c3c-88b0704972df

https://github.com/Expensify/App/assets/115492554/91850a96-ac35-4fba-a500-1cd7a0f4aa7c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tsa321

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696250660043669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ed352969a9bccd5</li>
        <li>Upwork Job ID: 1709233871301963776</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by kevin-williams** [comment] 2023-10-03 17:28
Neither of these situations are bugs.   The web version is set to overflow word wrap.  It is not inserting a new line, but rather adding a space and then splitting on that (abnormally long) word.    When typing normal sentences it splits on the word like it is supposed to.

In the mobile world, if you type 2 spaces it assumes you are ending a sentence so adds a period.   This is the normal autocomplete for mobile devices.   Again it looks weird because of the abnormally long strings of characters, but if you were typing a normal sentence it would appear perfectly normal.

IMO this should be closed as a non-issue.

**Comment by robertKozik** [comment] 2023-10-04 09:17
Not a bug for me as well - @kevin-williams explenation covers it perfectly.

@tsa321 Checked on github, correct me if I'm wrong, but this looks like the same behaviour

https://github.com/Expensify/App/assets/61146594/9d89c990-24e5-42ec-8648-45a3614393b3

**Comment by jliexpensify** [comment] 2023-10-05 01:18
Thanks everyone!

**Closed by jliexpensify** 2023-10-05 01:18 UTC
Labels: External, Daily, Help Wanted, Bug
