### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] [MEDIUM] IOU - Inconsistency of disabled category and tag message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34539] opened 2024-01-15 22:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** [sustinov@applausemail.com](mailto:sustinov@applausemail.com)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
In OldDot under admin, create a Collect group policy, enable Categories and Tag, add 3 Categories and 3 Tag, add an employee to the policy
1. Open https://staging.new.expensify.com/
2. Log in to the employee's account
3. Tap on the green plus button (FAB)
4. Select Request money
5. Select any currency and amount
6. Click next
7. Choose a WS room
8. Click on "Show more"
9. In the "Category" section, select any category
10. In the "Tag" section, select any tag
11. Complete the IOU
12. Open https://staging.expensify.com/
13. Log in to the admin account
14. Navigate to the Collect group policy settings
15. In the category tab, disable the employee's selected category from step 9
16. In the Tag tab, disable the employee's selected tag from step 10
17. In the employee's account in ND, open the IOU details

## Expected Result:
The message from the disabled Category and Tag should have the same appearance

## Actual Result:
The message from the disabled Category and Tag are different

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6343600_1705354412324!Screenshot_2024-01-15_at_23 41 57_1](https://github.com/Expensify/App/assets/78819774/257c65a8-5ab8-4385-909e-878e7f873855)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3be1122ebca12e5</li>
        <li>Upwork Job ID: 1747275792072568832</li>
        <li>Last Price Increase: 2024-01-16</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 28104172</li>
<li>s77rt | Contributor | 28104173</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment] 2024-01-16 00:27
Dont think this has to be a blocker, minor issue. Adding to wave 6 project

**Comment by luacmartins** [comment] 2024-01-16 15:12
@neonbhai your proposal looks good. Assigning you to the issue.

**Comment by s77rt** [comment] 2024-01-16 15:20
@luacmartins Shouldn't we drop the variables tagName/taxName and always use Tag/Tax respectively, to be consist with categoryOutOfPolicy and customUnitOutOfPolicy

https://github.com/Expensify/App/blob/d5f0f6f5057430998b107d63e372dec35c8e57f4/src/languages/en.ts#L2082-L2084

**Comment by luacmartins** [comment] 2024-01-16 17:35
That's a good point. I think we'd go the other way around and add `categoryName` and `customUnitName` to be consistent with tag and tax and be more specific.

Tagging @cead22 for confirmation, since those came from [this PR](https://github.com/Expensify/App/pull/32594)

**Comment by s77rt** [comment] 2024-01-18 18:44
Not overdue. @neonbhai is assigned here

**Comment by twisterdotcom** [comment] 2024-01-22 14:25
Same:

>Not overdue. @neonbhai is assigned here.

@neonbhai any update on this at all?

**Comment by cead22** [comment] 2024-01-25 22:34
Assigning to review PR, and submit a backend fix necessary to make this work

**Comment by cead22** [comment] 2024-01-25 22:51
The backend fix should be on staging on Monday 🤞

**Comment by twisterdotcom** [comment] 2024-02-07 13:13
Still being reviewed: https://github.com/Expensify/App/pull/35048#issuecomment-1931784795

**Comment by s77rt** [comment] 2024-02-13 21:05
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/32594
- The offending PR has been commented on: https://github.com/Expensify/App/pull/32594#discussion_r1488575742
- A discussion in #expensify-bugs has been started: Not needed (a unique bug)
- Determine if we should create a regression test for this bug: No. This is not a bug that could just resurface

**Comment by twisterdotcom** [comment] 2024-02-20 21:36
Payment Summary:

- @s77rt paid $500 [here](https://www.upwork.com/nx/wm/offer/28104173) (Contributor+)
- @neonbhai paid $500 [here](https://www.upwork.com/nx/wm/offer/28104172) (Contributor)

**Closed by twisterdotcom** 2024-02-20 21:36 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
