### ISSUE TITLE
[$250] iOS Split - Submit button appears then disappears when keyboard is open

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52828] opened 2024-11-20 15:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+29302390@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch ND or hybrid app.
2. Open chat.
3. Tap + > Split expense > Manual.
4. Enter amount > Next.
5. Tap on the split input.

## Expected Result:
Submit button will not appear and disappear when keyboard is open.

## Actual Result:
Submit button appears then disappears when keyboard is open.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c8203976-80f0-49e6-9223-123edf48bdba
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021860016281597788500</li>
        <li>Upwork Job ID: 1860016281597788500</li>
        <li>Last Price Increase: 2024-11-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by QichenZhu** [comment] 2024-11-22 03:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The submit button appears and disappears when the keyboard opens on the money request confirmation page.

### What is the root cause of that problem?
The submit button is hidden on purpose after the keyboard opens to resolve https://github.com/Expensify/App/issues/50663.

https://github.com/Expensify/App/blob/686b8b45ca606453e4b8a5f11e2a16e75dd0b15d/src/components/MoneyRequestConfirmationList.tsx#L827-L829

The problem is that the keyboard opens with an animation, but the button is hidden only after the keyboard is fully open.

https://github.com/Expensify/App/blob/686b8b45ca606453e4b8a5f11e2a16e75dd0b15d/src/components/withKeyboardState.tsx#L29

### What changes do you think we should make in order to solve the problem?
Replace `keyboardDidShow` with `keyboardWillShow` in the code mentioned above. Since this change affects many places in the app, we need to test it carefully.

```TSX
const keyboardDidShowListener = Keyboard.addListener('keyboardWillShow', (e) => { 
```

### What alternative solutions did you explore? (Optional)
Introduce a new state that listens to `keyboardWillShow` and use it specifically in the money request confirmation page. This approach might be safer than the main solution.

**Comment by s77rt** [comment] 2024-11-24 13:27
The offending PR has been [reverted](https://github.com/Expensify/App/pull/52976). Let's close this

**Closed** 2024-11-25 17:25 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Bug
