### ISSUE TITLE
 [Distance] IOU Distance - Recent list disappears after clearing address field, leaving a big space

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26482] opened 2023-09-01 13:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25990
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Distance
3. Click Start > Use current location
4. Go to Start again
5. Highlight the address field
6. Clear the input

## Expected Result:
The recent address list will not disappear

## Actual Result:
The recent address list disappears, leaving a huge space between the address field and Use current location button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.61-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/53035d02-bfbb-4f13-bfe1-a83d4cc45cac

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-09-01 15:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On clearing the text list shows empty space

### What is the root cause of that problem?
On input change within `AddressSearch` we set the `displayListViewBorder` to false when the text is empty.
https://github.com/Expensify/App/blob/main/src/components/AddressSearch/index.js#L337-L339

Based on `displayListViewBorder` value we are applying a style to scale down to 0 which is causing the issue.
https://github.com/Expensify/App/blob/5db24452f475e51226be1d12ef5e8d47878d8879/src/components/AddressSearch/index.js#L346
https://github.com/Expensify/App/blob/5db24452f475e51226be1d12ef5e8d47878d8879/src/styles/StyleUtils.js#L1190-L1192

### What changes do you think we should make in order to solve the problem?
When `predefinedPlaces` is available we don't need to scale to 0, for that we need to update the condition
```
if (_.isEmpty(text) && _.isEmpty(props.predefinedPlaces)) {
```

**Comment by Pujan92** [comment] 2023-09-01 16:08
@huzaifa-99 I think this issue is not due to your PR as we are passing `predefinedPlaces` earlier too.
cc: @grgia

**Comment by Pujan92** [comment] 2023-09-01 16:16
It exists from this [PR](https://github.com/Expensify/App/pull/25974), but at that moment we don't have any other content below that so not easily caught. Since you added the current location option below that which highlights the issue.

**Comment by luacmartins** [comment] 2023-09-01 19:21
We reverted the offending PR. Removing the blocker label.

**Comment by hayata-suenaga** [comment] 2023-09-01 21:34
@huzaifa-99 when you open the new PR, please link this issue there

**Comment by Pujan92** [comment] 2023-09-01 22:09
@hayata-suenaga just to inform this issue is not from the reverted PR. 
proposal - https://github.com/Expensify/App/issues/26482#issuecomment-1702967318 
issue still persists - https://github.com/Expensify/App/issues/26482#issuecomment-1702999940

If you still think it needs to be considered with the @huzaifa-99 PR, I am fine but wanted to highlight it! :)

**Comment by hayata-suenaga** [comment] 2023-09-01 23:27
@huzaifa-99 I don't have much background why `displayListViewBorder` is needed and why UI flickering occurs in the first place without it.

> Based on displayListViewBorder value we are applying a style to scale down to 0 which is causing the issue.

What are we scaling down? `GooglePlacesAutocomplete`? And how that is related to the gap that is observed?

**Comment by Pujan92** [comment] 2023-09-02 12:37
> @huzaifa-99 I don't have much background why `displayListViewBorder` is needed and why UI flickering occurs in the first place without it.

@hayata-suenaga `displayListViewBorder` is used to decide whether to show the hint below the textinput or not. It means when we are showing the list we hide the hint otherwise list starts after the hint.

> What are we scaling down? `GooglePlacesAutocomplete`? And how that is related to the gap that is observed?

It seems scaling down was added to avoid showing the empty area which created through padding when user searches but there aren't any options. Now we don't require scaling down part as we have a separate `ListEmptyComponent`.

If we remove the `ListEmptyComponent` and take out the scaling down then this issue occurs.

https://github.com/Expensify/App/assets/14358475/9fd22b00-c739-477a-9edc-d93993b5feb3

**Comment by hayata-suenaga** [comment] 2023-09-05 04:16
ah yea I see that

<img width="400" alt="Screenshot 2023-09-04 at 9 11 35 PM" src="https://github.com/Expensify/App/assets/98560306/0f927ddb-f627-4d4b-a751-85903455c21e">

> @hayata-suenaga just to inform this issue is not from the reverted PR.
> proposal - https://github.com/Expensify/App/issues/26482#issuecomment-1702967318
> issue still persists - https://github.com/Expensify/App/issues/26482#issuecomment-1702999940
> 
> If you still think it needs to be considered with the @huzaifa-99 PR, I am fine but wanted to highlight it! :)

**Comment by Pujan92** [comment] 2023-09-05 05:12
@huzaifa-99 still we need to make a change to get rid of `displayListViewBorder` for the styling part here

https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/components/AddressSearch/index.js#L350

https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/styles/StyleUtils.ts#L1044-L1057

**Comment by Pujan92** [comment] 2023-09-05 10:45
We need still scaling for the smooth transition for hiding the hint and showing the list otherwise it flickers a bit. So @hayata-suenaga what @huzaifa-99 added in their PR seems fine to me. 

https://github.com/Expensify/App/assets/14358475/7eb8e238-f867-4979-bd32-4125c1bc4a42

**Comment by hayata-suenaga** [comment] 2023-09-05 20:23
thank you for confirming!

**Comment by hayata-suenaga** [comment] 2023-11-01 00:34
are we good to close this issue?

seems like @huzaifa-99 fixed this issue in their PR?

**Closed** 2023-11-01 16:27 UTC
Labels: Reviewing, Engineering, Monthly
