### ISSUE TITLE
[$1000] Web - Thread - Emojis never appear at first in thread but after switching chats it appears.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20454] opened 2023-06-08 13:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on any “chat”
2. Send any message and react with emojis
3. Click on “Reply in thread”
4. Now react again on the first message

## Expected Result:
Emoji should appear at the same time when applied

## Actual Result:
Emojis take a long time to appear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6bfc71cc-0d74-49dd-ba1a-a1558363df56

https://github.com/Expensify/App/assets/93399543/16a7cd4f-6711-4729-9174-07be63495bc4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686033497072859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011001dca91abe26f8</li>
        <li>Upwork Job ID: 1666871413503741952</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-06-08 17:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emojis never appear at first in thread, but it appears after switching other chat and back

### What is the root cause of that problem?

When a new thread is created, we show the parent action as the first action in the thread.
In this case, `ReportActionItem` has its own report ID and parent's action as its props as you can see below

https://github.com/Expensify/App/blob/81b631b404cc16c5bb167b03d1128d9d72224272/src/pages/home/report/ReportActionItemParentAction.js#L64-L71

That's why, `toggleEmojiReaction` is called with the child report ID and parent action
https://github.com/Expensify/App/blob/81b631b404cc16c5bb167b03d1128d9d72224272/src/libs/actions/Report.js#L1597

That's why the updated emojis isn't properly updated in the frontend. This is the root cause

### What changes do you think we should make in order to solve the problem?

For parent action item, we can get parent report ID and pass it to the `toggleEmojiReaction` function.

https://github.com/Expensify/App/blob/81b631b404cc16c5bb167b03d1128d9d72224272/src/pages/home/report/ContextMenu/ContextMenuActions.js#L62
https://github.com/Expensify/App/blob/81b631b404cc16c5bb167b03d1128d9d72224272/src/pages/home/report/ReportActionItem.js#L177


This works perfectly

<details>
    <summary>Result</summary>

</details>


### What alternative solutions did you explore? (Optional)

**Comment by conorpendergrast** [comment] 2023-06-08 18:14
I reproduced *but* the emojis did appear after a long time, without needing to switch back and forth. Either way, a bug worth fixing

**Comment by danieldoglas** [comment] 2023-06-08 23:19
Yeah, this was fixed on https://github.com/Expensify/App/issues/19238#issuecomment-1583135311 on the backend. Should reach production tomorrow.

**Comment by conorpendergrast** [comment] 2023-06-12 13:50
Ok, looks like a duplicate report of [the same bug](https://github.com/Expensify/App/issues/19238). Sorry I missed that before! Closing

**Closed by conorpendergrast** 2023-06-12 13:50 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
