### ISSUE TITLE
 Chat - Emoji picker closes when switching to another tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27056] opened 2023-09-08 19:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Open any chat
3. Open emoji picker
4. Switch to another tab
5. Return to the tab in Step 3

## Expected Result:
Emoji picker does not close

## Actual Result:
Emoji picker closes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.66-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/03699ad6-adfc-4abc-bc75-c186d8ca0ebe

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2023-09-11 19:58
Sounds like this is a feature request, not a bug based on @allroundexperts input. @allroundexperts where are you getting the information that's intentional? Maybe that would be good to add here.

**Comment by Christinadobrzyn** [comment] 2023-09-12 19:42
Going to close this for now as it was reported by QA and appears to be intentional.

**Closed by Christinadobrzyn** 2023-09-12 19:42 UTC
Labels: Daily, Bug
