### ISSUE TITLE
[HOLD for payment 2023-09-12] [$500] Web - Tab switches to left when panning the map in distance tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26435] opened 2023-08-31 21:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Make sure you have the distance beta
2. Click on request money
3. Select the distance tab
4. Try panning the map to the left (by holding the pointer and moving it right)

## Expected Result:
 The map should pan normally

## Actual Result:
The tab changes to the scan tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/051ecbff-4178-4e3a-834c-653989255e69

https://github.com/Expensify/App/assets/93399543/23e03e40-5c9a-47b4-8aa3-1cf0455afa7d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693041114251089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f83fc119f988649</li>
        <li>Upwork Job ID: 1697604624145059840</li>
        <li>Last Price Increase: 2023-09-01</li>
<li>Automatic offers: </li>
<ul>
<li>esh-g | Reporter | 26455096</li>
</ul></li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-09-01 13:38
Haha, nice. FYI @neil-marcellini and @arosiclair as I believe you're working on distance requests

**Comment by parteekcoder** [comment] 2023-09-01 15:40
Hey I am not able to get these tabs like Distance etc. when I open `request money`

**Comment by closedspace** [comment] 2023-09-01 16:03
@parteekcoder you need to enable beta features. Go to Permission.js and set the `canUseAllBetas` function to always return `true`

**Comment by neil-marcellini** [comment] 2023-09-01 16:34
@allroundexperts looks like you found a good fix and I agree about the root problem. Could you explain a bit more how the panResponder is used to prevent panning the map from swiping the tab?

**Comment by conorpendergrast** [comment] 2023-09-11 11:51
@garrettmknight I'm on parental leave; re-assigning! This is waiting for payment, tomorrow!

**Comment by garrettmknight** [comment] 2023-09-19 04:05
Oops, missed this one, paying now.

**Summary of Payments for this issue:**
- urgency bonus? Yes
- Reporter: @esh-g - $250 paid via Upwork
- Contributor: @allroundexperts $750
- Contributor+: N/A

Upwork job: https://www.upwork.com/jobs/~017f83fc119f988649

**Comment by garrettmknight** [comment] 2023-09-19 04:05
@allroundexperts it looks like this got merged in the bonus timeline.

**Comment by garrettmknight** [comment] 2023-09-19 04:06
Separately, but related, should we introduce a regression test here? @allroundexperts

**Comment by garrettmknight** [comment] 2023-09-22 10:46
Cool, all done! Just awaiting payment.

**Comment by neil-marcellini** [comment] 2023-10-02 17:31
Not overdue

**Comment by JmillsExpensify** [comment] 2023-10-05 13:08
$750 payment approved for @allroundexperts based on BZ summary.

**Comment by garrettmknight** [comment] 2023-10-10 20:40
Cool, we're good to close then!

**Closed by garrettmknight** 2023-10-10 20:40 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug
