### ISSUE TITLE
[HOLD for payment 2023-09-27] [$1000] After deleting a mobile contact from a WorkSpace, it starts showing up in contacts as @expensify.sms

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26121] opened 2023-08-28 20:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with any of your logins
3. Create a new workspace or open an existing one
4. Open the workspace & click on "Members"
5. Click on 'Invite' button
6. Search for an invalid phone number (+2523234211)
7. Select the user > click on "Next" > click on "Invite"
8. Select the user & click on the "Remove" button
9. Click on 'Invite' button

## Expected Result:
The previously added contact should appear as a phone number, without the @expensify.sms termination

## Actual Result:
A previously added contact is displayed as a phone number with @expensify.sms at the end

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.58-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/4fc01bef-7aa5-451c-82a0-60e30e1ca24f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b0b1a782b2526c6</li>
        <li>Upwork Job ID: 1696345977519468544</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26454047</li>
<li>pradeepmdk | Contributor | 26454050</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-08-29 02:13
[Confirmed that we shouldn't show @expensify.sms anywhere](https://github.com/Expensify/App/issues/22999#issuecomment-1646692318)

**Comment by pradeepmdk** [comment] 2023-08-29 03:52
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
After deleting a mobile contact from a WorkSpace, it starts showing up in contacts as @expensify.sms

### What is the root cause of that problem?
We are not formatting the @expensify.sms text anywhere.

### What changes do you think we should make in order to solve the problem?
for this case https://github.com/Expensify/App/blob/a5ab459e731badcce4faea56fbce074a54f8495b/src/libs/OptionsListUtils.js#L1047
we can wrap up with 
```
 LocalePhoneNumber.formatPhoneNumber(lodashGet(member, 'text', '') || lodashGet(member, 'displayName', ''))
``` 
but we can able to see wherever phone number present. because  onyx have the @expensify.sms  that only
![Screenshot 2023-08-29 at 9 17 03 AM](https://github.com/Expensify/App/assets/16595846/0b9caa5d-2bbe-4d5f-8369-9c163005fdce)

so we need write selector whenever fetch the personalDetails from onyx. this selector is common function so moved lib folder 
```
 personalDetails: {
            key: ONYXKEYS.PERSONAL_DETAILS_LIST,
            selector: (select) => {
                const data = _.chain(select).clone().mapObject(entry => {
                    if (entry.displayName) {
                      entry.displayName = LocalePhoneNumber.formatPhoneNumber(entry.displayName)
                    }
                    return entry;
                  }).value();
                return data;
            }
        },
``` 
### What alternative solutions did you explore? (Optional)
if we don't need @expensify.sms  means we can fix from backend.

**Comment by pradeepmdk** [comment] 2023-08-29 15:13
@mollfpr because when api falling `onyxData`  empty but we stored in the   optimisticData with  `OptionsListUtils.addSMSDomainIfPhoneNumber` so that its happening. so that in  my proposal remove the `addSMSDomainIfPhoneNumber` on display name

https://github.com/Expensify/App/blob/a5ab459e731badcce4faea56fbce074a54f8495b/src/libs/actions/Policy.js#L346
<img width="769" alt="Screenshot 2023-08-29 at 8 39 42 PM" src="https://github.com/Expensify/App/assets/16595846/e2db6108-f895-47ad-a388-a1da472a7495">

**Comment by mollfpr** [comment] 2023-08-29 15:31
![Screenshot 2023-08-29 at 22 05 18](https://github.com/Expensify/App/assets/25520267/c799887f-5af0-422d-b282-81e566e901ee)

@pradeepmdk Sorry, I don't understand your point. In the above image, the valid phone number also has the domain, but it displays fine; why is that?

@c3024 Nope, it just added.

**Comment by pradeepmdk** [comment] 2023-08-29 15:59
@mollfpr This issue was when we storing `optimisticData`  in Onyx whenever API falling

**Comment by pradeepmdk** [comment] 2023-08-29 16:50
@mollfpr 
> I think we don't have anything wrong with the API action and the optimistic data, so I prefer to keep it that way.

this is wrong write the display name with ` @expensify.sms` this happened only from `optimisticData`  but API give correct response without `@expensify.sms`
<img width="287" alt="Screenshot 2023-08-29 at 10 17 57 PM" src="https://github.com/Expensify/App/assets/16595846/9e85b31b-0447-4a74-b77d-0e0d4f37ce18">

**Comment by Li357** [comment] 2023-08-30 12:38
@pradeepmdk Seems like you're right. I would prefer to fix the optimistic data generated, can you demonstrate this fix working everywhere we currently show @expensify.sms?

**Comment by mollfpr** [comment] 2023-08-30 12:41
@pradeepmdk You have a good point on the optimistic data, but fixing the optimistic data is not enough. We also need to format the option list too. Otherwise, the issue still persists for the wrong existing data.

I also suspect that this issue is a regression from https://github.com/Expensify/App/pull/22904.

**Comment by mollfpr** [comment] 2023-08-30 12:57
In other PR https://github.com/Expensify/App/pull/23157, we have optimistic with `displayName` formatted.

The error personal details should be removed in #22904, but the failure data setup is removed in https://github.com/Expensify/App/pull/23947

**Comment by pradeepmdk** [comment] 2023-08-30 13:04
@mollfpr 
but we can format only displayname right?  `displayName: LocalePhoneNumber.formatPhoneNumber(login),` This will solve other places too.


its working  fine for me 
https://drive.google.com/file/d/1t-FM8J5xXghkqffkZb8VVLH2g8JRo9oP/view?usp=sharing

**Comment by mollfpr** [comment] 2023-08-30 13:31
@pradeepmdk So, regardless of the fix on the optimistic data, do we need to format the option list to fix the existing data?

**Comment by mollfpr** [comment] 2023-08-30 13:45
@Li357 What is your call here? I think @pradeepmdk got the RCA correct. I didn't get that at first until several looked up the history changes.

**Comment by Li357** [comment] 2023-09-01 15:49
@mollfpr Sorry for the delay here. I agree that @pradeepmdk included more in the RCA. I'm going to assign them to this

**Comment by pradeepmdk** [comment] 2023-09-01 22:32
@Li357 @mollfpr one doubt need to wait for `merge freeze` to complete or else can I raise the PR now?
https://expensify.slack.com/archives/C01GTK53T8Q/p1693347701566439

**Comment by mollfpr** [comment] 2023-09-04 03:42
@pradeepmdk I think it's okay, to raise the PR now and get it approved.

**Comment by pradeepmdk** [comment] 2023-09-04 06:52
@mollfpr so is that eligible for getting the bonus as well? because they mentioned here https://expensify.slack.com/archives/C01GTK53T8Q/p1693407966629239?thread_ts=1693347701.566439&cid=C01GTK53T8Q

**Comment by mollfpr** [comment] 2023-09-04 07:02
Usually, the bonus will be counted from when you got assigned until the C+ approves the PR.

@jliexpensify Could you confirm if the merge freeze will affect the speed bonus, or will no bonus be applied at this stage?

**Comment by jliexpensify** [comment] 2023-09-04 07:29
Great question - so I would imagine that you could raise a PR but it won't be merged/deployed unless it's related to what Vit has outlined [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1693347701566439).

For bonuses, I'm not 100% sure how it works with a freeze - let me check in with the team here!

**Comment by jliexpensify** [comment] 2023-09-04 07:52
[Looks like there are no urgency bonuses](https://expensify.slack.com/archives/C01GTK53T8Q/p1693407966629239?thread_ts=1693347701.566439&cid=C01GTK53T8Q) for anything not related to receipt scanning and distance requests

**Comment by pradeepmdk** [comment] 2023-09-04 07:55
@mollfpr Pr is ready for review 
@jliexpensify  so after the merge freeze is complete we are getting eligible bouns? if this PR is raised after `merge freeze`

**Comment by jliexpensify** [comment] 2023-09-04 08:27
My understanding is that no bonuses will be paid, since they won't be merged in time. The only scenario would maybe be you raising a PR as the merge freeze is ending, and it gets merged pretty soon after.

**Comment by pradeepmdk** [comment] 2023-09-04 08:39
So here anyway this is not urgent and not going to merge until the merge freezes.  @mollfpr @jliexpensify   so can you help to get the bonuses as well?

**Comment by jliexpensify** [comment] 2023-09-04 08:41
> so can you help to get the bonuses as well?

Sorry, what do you mean by this?

**Comment by pradeepmdk** [comment] 2023-09-04 08:47
@jliexpensify 
>The only scenario would maybe be you raising a PR as the merge freeze is ending, and it gets merged pretty soon after.

I thought if we raised pR after merge freeze chance to get bouns. but now I already raised PR. What should I do? this is a little bit confusing to me

**Comment by mollfpr** [comment] 2023-09-04 16:09
> The only scenario would maybe be you raising a PR as the merge freeze is ending, and it gets merged pretty soon after.

This doesn't make sense to me. There will be no difference in raising the PR now or later.

> but now I already raised PR. What should I do? this is a little bit confusing to me

This is fine. I'll be relieved to get the job done as soon as possible.

**Comment by jliexpensify** [comment] 2023-09-05 02:45
Hey sorry everyone, maybe I haven't communicated this clearly: my understanding from what Vit has posted is that bonuses won't be paid out during this merge freeze, since we're pausing on all non-essential PR's for the next week.

For my statement here:

>The only scenario would maybe be you raising a PR as the merge freeze is ending, and it gets merged pretty soon after.

I was thinking that if you raised a PR pretty much the same time as we lifted the merge freeze, then you might qualify for a bonus (as the merge freeze would be lifted).

**Comment by pradeepmdk** [comment] 2023-09-05 17:33
@mollfpr @jliexpensify for on your eye.
https://github.com/Expensify/App/issues/25704#issuecomment-1706961089
https://expensify.slack.com/archives/C01GTK53T8Q/p1693932139950359

**Comment by mollfpr** [comment] 2023-09-06 01:03
@pradeepmdk To be honest, I still have no idea if it is a bonus speed or not 😅

**Comment by jliexpensify** [comment] 2023-09-06 01:09
I think if the PR is related to either SmartScanning or distance requests, then it would very likely be prioritised, and you'd get the bonus. But this issue is around @expensify.sms showing up right? So it's not really related to either.

**Comment by pradeepmdk** [comment] 2023-09-14 10:56
@mollfpr Pr is ready

**Comment by jliexpensify** [comment] 2023-09-18 00:46
Bump @mollfpr to complete the checklist!

**Comment by mollfpr** [comment] 2023-09-19 16:10
@jliexpensify The second PR is still on QA, so the payment date will be change.

**Comment by jliexpensify** [comment] 2023-09-20 01:31
@mollfpr is this the other PR? https://github.com/Expensify/App/pull/26638

**Comment by mollfpr** [comment] 2023-09-20 01:34
@jliexpensify It's #27408

**Comment by jliexpensify** [comment] 2023-09-20 01:40
Cool, just changed the payment date and will check back next week to see how things are going - thanks!

**Comment by jliexpensify** [comment] 2023-09-25 03:41
Payment Summary:

- Contributor: @pradeepmdk $1000
- C+: @mollfpr $1000

[Upworks Job](https://www.upwork.com/ab/applicants/1696345977519468544/hired)

@mollfpr bump to complete the checklist, thanks!

**Comment by mollfpr** [comment] 2023-09-27 06:22
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I couldn't find the offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


**For WorkSpace**

1. Open https://staging.new.expensify.com/
2. Open the workspace or create one & click on "Members"
3. Click on the 'Invite' button
4. Search for an invalid phone number (+2523234211)
5. Select the user > click on "Next" > click on "Invite"
6. Select the user & click on the "Remove" button
7. Click on the 'Invite' button
8. Verify the display name on the newly added user without the domain name

**For Request Money**

1. Open the Request money from the fab menu
2. go to offline
3. Create a `Request money` with an invalid phone number (either manual or distance)
4. Verify the display name on the chat page without the domain name

**For Split bill**

1. Open the Split bill from the fab menu
2. go to offline
3. Create split money with an invalid phone number
4. Verify the display name on the chat page without the domain name

**Comment by jliexpensify** [comment] 2023-09-28 01:16
Paid and job closed!

**Closed by jliexpensify** 2023-09-28 01:16 UTC
Labels: External, Weekly, Awaiting Payment, Bug
