### ISSUE TITLE
[$500] IOU - In WS, request money without merchant allowed to create when add receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34186] opened 2024-01-09 20:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.23
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on Workspace report page
3. Tap plus icon--- request money--- manual
4. Enter an amount and tap next
5. Tap request
6. Note merchant field not entered error displayed
7. Tap 3 dots on top right and select "add receipt "
8. Upload a receipt
9. Tap request
10. Note user after adding receipt able to create request without entering merchant field

## Expected Result:
In WS, request money without merchant should not be allowed to create, when add receipt is used

## Actual Result:
In WS, request money without merchant allowed to create, when add receipt is used

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/14f41c15-ff8f-4af6-8c32-9e68ca33a89b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123185e12b5eebfb3</li>
        <li>Upwork Job ID: 1744819582596452352</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-09 20:35
This is being discussed here: https://github.com/Expensify/App/issues/33588

**Comment by aim-salam** [comment] 2024-01-09 21:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - In WS, request money without merchant allowed to create when add receipt

### What is the root cause of that problem?

In `MoneyTemporaryForRefactorRequestConfirmationList`, `isMerchantRequired` need 3 condition to become true which is
`isPolicyExpenseChat && !isScanRequest && shouldShowMerchant`.

When receipt added `shouldShowMerchant` switch to false, this is because `shouldShowSmartScanFields` one of his condition was changed.

Delete `shouldShowMerchant` condition. Because both of its condition nothing to do with functionality.
`const shouldShowMerchant = shouldShowSmartScanFields && !isDistanceRequest;`

```diff
 const isMerchantRequired = isPolicyExpenseChat && !isScanRequest 
- && shouldShowMerchant;
```

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by aim-salam** [comment] 2024-01-09 21:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - In WS, request money without merchant allowed to create when add receipt

### What is the root cause of that problem?

In `MoneyTemporaryForRefactorRequestConfirmationList`, `isMerchantRequired` need 3 condition to become true which is
`isPolicyExpenseChat && !isScanRequest && shouldShowMerchant`.

When receipt added `shouldShowMerchant` switch to false, this is because `shouldShowSmartScanFields` one of his condition was changed.

### What changes do you think we should make in order to solve the problem?
Depend

1. If you want `merchant` keep required either have receipt or not.

```diff
 const shouldShowMerchant = 
-     shouldShowSmartScanFields && 
     !isDistanceRequest;
```
### What alternative solutions did you explore? (Optional)

**Comment by youssef-lr** [comment] 2024-01-10 03:10
Closing this in favor of https://github.com/Expensify/App/issues/33588.

**Closed by youssef-lr** 2024-01-10 03:10 UTC
Labels: External, Daily, Help Wanted, Bug
