### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] Expense Details - Square bracket displayed in system message for unapproved expense report

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49160] opened 2024-09-13 10:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.34-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** biruknew45+906@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in as an admin in OldDot.
2. Create a Collect workspace.
3. Add user B as an employee.
4. As the employee, log in to NewDot and submit an expense in the workspace chat.
5. As the employee, go to the expense details page.
6. As the admin, go to the expense report in OldDot.
7. Approve the expense and then unapprove it.
8. As the employee in NewDot, check the system message when the expense is unapproved.

## Expected Result:
The system message should correctly specify that the admin has unapproved the report.

## Actual Result:
Square brackets ("[]") are displayed in the system message

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6602049_1726217027493!1](https://github.com/user-attachments/assets/b0ce1e41-3398-45cb-8e11-ed6fd12306a9)

https://github.com/user-attachments/assets/8cf1dc7d-9d3c-40af-8b9a-2dadad95cb09

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838747538236628276</li>
        <li>Upwork Job ID: 1838747538236628276</li>
        <li>Last Price Increase: 2024-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 104127878</li>
<li>nkdengineer | Contributor | 104127879</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by IuliiaHerets** [comment] 2024-09-13 10:37
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-09-13 10:37
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-09-14 06:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The system message for unapproved if done from OD shows `[]`.

### What is the root cause of that problem?
This is a BE problem. When we receive the unapproved message, the object contains `[]` as the message. After we refresh, it now looks like this:
<img width="288" alt="image" src="https://github.com/user-attachments/assets/733505e6-142e-4bbe-b999-9292816ae951">

For unapproved action, we just show what is inside the action `message` array. It's different with the approved action where we format it manually and localize it.
https://github.com/Expensify/App/blob/51a64cfe90a9314b51a5f3de00c945aeeea4ee1b/src/pages/home/report/ReportActionItem.tsx#L642-L643

We already has the translation, but we never use it.
https://github.com/Expensify/App/blob/51a64cfe90a9314b51a5f3de00c945aeeea4ee1b/src/languages/en.ts#L4191

The translation was added in https://github.com/Expensify/App/pull/43079 but never being used.

### What changes do you think we should make in order to solve the problem?

We need to fix this on the FE & BE by using the translations for the unapproved message, so the message is shown correctly and localized.
1. Add a new check for unapproved action in ReportActionItem
```
} else if (action.actionName === CONST.REPORT.ACTIONS.TYPE.UNAPPROVED) {
    children = <ReportActionItemBasicMessage message={ReportUtils.getIOUUnapprovedMessage(action)} />;
```
2. Create the new function for getIOUUnapprovedMessage
```
function getIOUUnapprovedMessage(reportAction: ReportAction) {
    return Localize.translateLocal('iou.unapprovedAmount', {amount: getFormattedAmount(reportAction)});
}
```
3. Update the translation to move the `unapproved` within `iou` object.
```
iou: {
    ...,
    unapprovedAmount: ({amount}: UnapprovedParams) => `unapproved ${amount}`,
    ...,
}
```
4. Update `getFormattedAmount` to accept unapproved action.
https://github.com/Expensify/App/blob/51a64cfe90a9314b51a5f3de00c945aeeea4ee1b/src/libs/ReportUtils.ts#L4447-L4450
```
if (... && !ReportActionsUtils.isApprovedAction(reportAction)) {
```

The changes on the FE is done, but the message will show `unapproved` without any amount and currency and that's because the report action original message of the unapproved from OD has an empty `originalMessage`.
<img width="205" alt="image" src="https://github.com/user-attachments/assets/0c0c8667-a7c5-47b3-95f6-30cea336f9b6">

Compared to the unapproved action done from ND.
<img width="312" alt="image" src="https://github.com/user-attachments/assets/c022be46-9e5f-45af-bfd8-ad2f6a49ed7c">

So, we need a BE fix too to return the correct `originalMessage`.

**Comment by nkdengineer** [comment] 2024-09-25 08:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Square brackets ("[]") are displayed in the system message

### What is the root cause of that problem?
When we unapproved the request in OD, we received the pusher data for `UNAPPROVED` action with `message` and `originalMessage` as an empty array

<img width="1511" alt="Screenshot 2024-09-25 at 15 23 00" src="https://github.com/user-attachments/assets/bcd85b11-9a71-481f-8ea4-fe09ce057dec">

Then because we don't have a special case for unapproved action, it displays the data from `html` of `message`


### What changes do you think we should make in order to solve the problem?
1. From backend, we should return the correct data via pusher for `UNAPPROVED` action


2. We should add a case for `UNAPPROVED` action to translate it as we do for approved action. We're had the translation key for this action [here](https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/languages/en.ts#L4160)

https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/pages/home/report/ReportActionItem.tsx#L632

- Create a util to check the action is unapproved action or not in `ReportActionUtils`

```
function isUnapprovedAction(reportAction: OnyxInputOrEntry<ReportAction>): reportAction is ReportAction<typeof CONST.REPORT.ACTIONS.TYPE.UNAPPROVED> {
    return isActionOfType(reportAction, CONST.REPORT.ACTIONS.TYPE.UNAPPROVED);
}
```
- Create a util to get the unapproved message in `ReportUtils`

```
function getIOUUnapprovedMessage(reportAction: ReportAction) {
    return Localize.translateLocal('iou.unapprovedAmount', {amount: getFormattedAmount(reportAction)});
}
```

- Add a case for unapproved action in `getFormattedAmount` function

```
if (!ReportActionsUtils.isSubmittedAction(reportAction) && !ReportActionsUtils.isForwardedAction(reportAction) && !ReportActionsUtils.isApprovedAction(reportAction) && !ReportActionsUtils.isUnapprovedAction(reportAction)) {
    return '';
}
```

https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/libs/ReportUtils.ts#L4435

- Add a case for unapproved action in `ReportActionItem`

```
} else if (action.actionName === CONST.REPORT.ACTIONS.TYPE.UNAPPROVED) {
    children = <ReportActionItemBasicMessage message={ReportUtils.getIOUUnapprovedMessage(action)} />;
```
https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/pages/home/report/ReportActionItem.tsx#L632

- Do the same way as we do for approved action to add a case for unapproved action in other places

```
else if (lastReportAction?.actionName === CONST.REPORT.ACTIONS.TYPE.UNAPPROVED) { 
     lastMessageTextFromReport = ReportUtils.getIOUUnapprovedMessage(lastReportAction); 
 }
```
https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/libs/OptionsListUtils.ts#L664-L667

```
if (parentReportAction?.actionName === CONST.REPORT.ACTIONS.TYPE.UNAPPROVED) { 
   return getIOUUnapprovedMessage(parentReportAction); 
} 
```
https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/libs/ReportUtils.ts#L3718-L3720

```
else if (reportAction?.actionName === CONST.REPORT.ACTIONS.TYPE.UNAPPROVED) { 
     const displayMessage = ReportUtils.getIOUUnapprovedMessage(reportAction); 
     Clipboard.setString(displayMessage); 
```
https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L445-L447
### What alternative solutions did you explore? (Optional)
NA

**Comment by DylanDylann** [comment] 2024-09-25 09:47
We need to modify the BE to return the correct data

For FE, I agree with contributors about handling translation for unapproved messages. Let's go with @nkdengineer's proposal because their proposal covered all instances 

🎀 👀 🎀 C+ reviewed

**Comment by iwiznia** [comment] 2024-09-25 16:51
> From backend, we should return the correct data via pusher for UNAPPROVED action

Yep, sent a PR for this in our backend: https://github.com/Expensify/Auth/pull/12615

Not very familiar with the App code for this, so have a few questions:
> Create a util to check the action is unapproved action or not in ReportActionUtils

Why do we do this (in general)? Why not have just one method `isActionType(reportAction, type)`?

> Create a util to get the unapproved message in ReportUtils

Both approve and unapprove have the same data format, no? Could we reuse `getIOUApprovedMessage` instead of duplicating it (maybe changing the name a bit)?

> Add a case for unapproved action in getFormattedAmount function

Why do we keep adding ifs there, wouldn't it be better to check if the amount and currency are set?

**Comment by nkdengineer** [comment] 2024-09-25 17:07
@iwiznia Thanks for your feedback.

> Why do we do this (in general)? Why not have just one method isActionType(reportAction, type)?

We create a new until then we can use this function in other places of the app with only one param. That is similar to `isSubmittedAction`

 > Both approve and unapprove have the same data format, no? Could we reuse getIOUApprovedMessage instead of duplicating it (maybe changing the name a bit)?

We can reuse this. We can rename this function, and change the format of `unapproved` translation to be similar to `approve` translation.

> Add a case for unapproved action in getFormattedAmount function

This check is used to predict the type of action, and then we can access `amount` and `currency` safer and easier

Why do we keep adding ifs there, wouldn't it be better to check if the amount and currency are set?

**Comment by iwiznia** [comment] 2024-09-25 17:43
> We create a new until then we can use this function in other places of the app with only one param. That is similar to isSubmittedAction

ok, kind of think that having one method for each action type is more work and makes writing code harder (you need to remember/find the names of each action). But since we already do this everywhere, let's keep it.

> We can reuse this. We can rename this function, and change the format of unapproved translation to be similar to approve translation.

Awesome

> This check is used to predict the type of action, and then we can access amount and currency safer and easier

It is certainly not easier as we need to add each action to the if, I am not sure I am convinced it's safer, what is the risk? That someone calls this method for an "invalid" report action that casually has `currency` and `amount` but they contain some different data than the actual currency and amount?

**Comment by nkdengineer** [comment] 2024-09-27 07:23
@DylanDylann this [PR](https://github.com/Expensify/App/pull/49831) is ready for review

**Comment by nkdengineer** [comment] 2024-09-30 16:31
@iwiznia we have an open PR [here](https://github.com/Expensify/App/pull/49831) but currently Back End doesn't return `message` and `originalMessage` when admin `unapproved` the expense in Old Dot. Please check again

![Old Dot](https://github.com/user-attachments/assets/9b28a4c1-25fc-4569-90cf-efcbc00d1650)

**Comment by iwiznia** [comment] 2024-09-30 17:19
Yeah, the backend PR should get deployed tomorrow.

**Comment by DylanDylann** [comment] 2024-10-03 09:51
@nkdengineer Any updates?

**Comment by nkdengineer** [comment] 2024-10-05 05:10
@DylanDylann, looks like the PR on the backend has been merged. This [PR](https://github.com/Expensify/App/pull/49831) is ready for review

**Comment by DylanDylann** [comment] 2024-10-17 02:25
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **This change seems like a new improvement, not a bug**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Log in as an admin in OldDot.
2. Create a Collect workspace.
3. Add user B as an employee.
4. As the employee, log in to NewDot and submit an expense in the workspace chat.
5. As the employee, go to the expense details page.
6. As the admin, go to the expense report in OldDot.
7. Approve the expense and then unapprove it.
8. As the employee in NewDot, check the system message when the expense is unapproved.
9. Verify that: The system message should correctly specify that the admin has unapproved the report.


Do we agree 👍 or 👎

**Comment by DylanDylann** [comment] 2024-10-28 07:11
Waiting for @anmurali to complete the payments and close

**Comment by iwiznia** [comment] 2024-10-29 20:15
Not overdue, @anmurali needs to pay

**Comment by anmurali** [comment] 2024-10-29 22:27
Done.

**Closed by anmurali** 2024-10-29 22:27 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
