### ISSUE TITLE
[$1000]  Text is flickering when click on checkbox

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22526] opened 2023-07-09 05:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website and Click on avatar to open settings
2. Click Workspaces > any Workspace > Cards > Connect Bank Account > Connect Manually > Reach 3rd step (Personal Information)
3. Fill in blanks and come to checkbox.
4. Click checkbox's text multiple times.
## Expected Result: 
Text should be flickered when click on checkbox
## Actual Result: 
Text is flickering when click on checkbox
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/faf505af-e81b-4118-8b92-3a89bacb1542

**Expensify/Expensify Issue URL:**
**Issue reported by:** @muxriddinmuqimov77
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688394732965969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134ff9d9773d47adc</li>
        <li>Upwork Job ID: 1680998431684984832</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-07-09 06:15
That is expected behaviour. As user should get some type of feedback that the text was pressed and due to that the Check Box was selected

**Comment by muxriddinmuqimov77** [comment] 2023-07-09 13:34
@jeet-dhandha I meant second flickering not first. If you see the video properly, when you click on text you see first flickering and It's intentional. But when the checkbox is about to be checked you can see second flickering and It's not intentional.

**Comment by anmurali** [comment] 2023-07-17 17:53
Added the external label to create an Upwork job

**Comment by timothyfisherdev** [comment] 2023-07-17 23:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Text flickers _twice_ when clicking on a `<PressableWithFeedback>` component. We want to eliminate the second flicker but keep the first.

### What is the root cause of that problem?

The root cause of the issue is the setting of the `isExecuting` property in the `<PressableWithFeedback>` component on the `onPress` event.

I first noticed that when you hold down the press, the flicker does not occur. This makes sense according to [this documentation](https://reactnative.dev/docs/pressable) on the `<Pressable>` component. If you hold the press for longer than 500ms, the `onLongPress` event fires, meaning `onPress` does not.

I looked into the `onPress` event and noticed that it is setting a property called `isExecuting` after the press. This is effectively triggering another disable/enable on the component which causes the flickering. I believe the `<Pressable>` component will take care of its state without this event.

### What changes do you think we should make in order to solve the problem?


You can either make it so the `isDisabled` property ignores `isExecuting`, or, simply remove/change the `onPress` event to accept a prop.

Either of those changes results in the desired behavior (a little laggy in my emulator):

[device-2023-07-17-165002.webm](https://github.com/Expensify/App/assets/38889944/b66b33da-06a6-4894-84db-465538e95ca8)

### What alternative solutions did you explore? (Optional)

I also explored the possibility of using the `<PressableWithoutFeedback>` component as noted in the proposal above, but it is to my understanding based on the previous comments in this thread that initial feedback is desired, so it makes sense to use `<PressableWithFeedback>` in my opinion.

**Comment by timothyfisherdev** [comment] 2023-07-17 23:58
> 📣 @timothyfisherdev! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```

```
Contributor details
Your Expensify account email: tpf27@nau.edu
Upwork Profile Link: https://www.upwork.com/freelancers/timothyfisherdev
```

**Comment by timothyfisherdev** [comment] 2023-07-19 04:01
After taking a second look, I have updated my proposal with a better solution that results in the same fix.

**Comment by sobitneupane** [comment] 2023-07-19 11:26
Is this issue reproducible on Android Native? Unable to reproduce.

https://github.com/Expensify/App/assets/25876548/a79173cc-27c5-4875-b59c-fbd3e275268c

**Comment by muxriddinmuqimov77** [comment] 2023-07-19 13:07
> Is this issue reproducible on Android Native? Unable to reproduce.
> 
>  Screen.Recording.2023-07-19.at.17.10.41.mov

@sobitneupane The phone I used is: Redmi Xiaomi Note A5
Maybe you should use some kind of phone that is near to this one.

**Comment by timothyfisherdev** [comment] 2023-07-19 18:21
In Android Studio I emulated Google 3a Pixel XL

**Comment by sobitneupane** [comment] 2023-07-24 11:39
Still trying to reproduce.

**Comment by sobitneupane** [comment] 2023-07-25 14:01
@anmurali Were you able to reproduce the issue? I cannot reproduce the issue.

**Comment by sobitneupane** [comment] 2023-08-02 04:17
@anmurali Were you able to reproduce the issue? I cannot reproduce the issue.

**Comment by anmurali** [comment] 2023-08-09 13:57
Nope I cannot reproduce it either. Closing it.

**Closed by anmurali** 2023-08-09 13:57 UTC
Labels: Engineering, Daily, Internal, Needs Reproduction, Overdue, Bug
