### ISSUE TITLE
Message stays highlighted after closing the context menu 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12889] opened 2022-11-21 15:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to a chat
2. Send a message
3. Right click on the message
4. Click anywhere at the screen to close the context menu

## Expected Result:
The message shouldn't be highlighted after closing the context menu

## Actual Result:
The message stays highlighted

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.29-6
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/203090739-01b29cdc-484d-49d2-bdb4-7a26066e7dd8.mp4

https://user-images.githubusercontent.com/43996225/203090761-a7fb134f-d3f8-4991-8e68-c758011c2fa7.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668851137899819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment] 2022-11-21 16:02
<b>Proposal</b>
Even when the `PopoverReportActionContextMenu` is dismissed, the `reportAction` state is not getting reset.

<b>Solution</b>
Reset the `reportAction` state to {} when `PopoverReportActionContextMenu` is dismissed.
So inside `PopoverReportActionContextMenu` udpate the `hideContextMenu`:
```diff
    /**
     * Hide the ReportActionContextMenu modal popover.
     * @param {Function} onHideActionCallback Callback to be called after popover is completely hidden
     */
    hideContextMenu(onHideActionCallback) {
        if (_.isFunction(onHideActionCallback)) {
            this.onPopoverHideActionCallback = onHideActionCallback;
        }
        this.setState({
            selection: '',
            reportActionDraftMessage: '',
            isPopoverVisible: false,
+           reportAction: {},
        });
    }

```

Result:

https://user-images.githubusercontent.com/16502320/203101565-d8dcb075-e507-4034-9221-9a8629de598b.mov

**Comment by amyevans** [comment] 2022-11-21 16:46
This is a regression caused by https://github.com/Expensify/App/pull/12735, cc @deetergp @Pujan92 @mananjadhav @Julesssss.

I'll open a revert of that PR.

**Comment by amyevans** [comment] 2022-11-21 16:56
Okay, let me review your suggestion a bit locally @0xmiroslav, thanks. The one thing I'm sensitive to is that the regression is currently a deploy blocker, so we'd need to cherry pick a fix today, and I want to avoid introducing any further regressions by not fully considering unintended side effects if moving too quickly.

**Comment by amyevans** [comment] 2022-11-21 18:46
Discussed with @AndrewGable and I'm going to proceed with opening a revert PR to keep the deploy unblocked. @0xmiroslav, feel free to suggest your proposal on the original issue (https://github.com/Expensify/App/issues/11086) for evaluation by the C+ and CME, as the issue will need an updated solution after the revert. Thank you!

**Comment by AndrewGable** [comment] 2022-11-21 23:54
Removing label as the revert was CP-ed

**Comment by mananjadhav** [comment] 2022-11-22 03:30
Thanks @amyevans and @AndrewGable. We'll fix it as a regression on #11086

**Comment by flaviadefaria** [comment] 2022-11-23 18:49
Are we then good to close this?

**Comment by amyevans** [comment] 2022-11-28 15:59
Yes, sorry, I forgot App issues aren't auto-closed when the related PR is deployed!

**Comment by thesahindia** [comment] 2022-11-28 16:42
@amyevans, can we re-open? This is eligible for reporting compensation.

**Comment by amyevans** [comment] 2022-11-28 17:27
Right, apologies @thesahindia! @flaviadefaria can you issue payment to @thesahindia please?

**Comment by flaviadefaria** [comment] 2022-11-29 19:13
@thesahindia I'm just clarifying something internally but will aim to pay you tomorrow!

**Comment by flaviadefaria** [comment] 2022-11-30 10:53
@thesahindia can you please apply for the job so that I can pay you? 
Here's the link to the post -https://www.upwork.com/jobs/~01a04fbcc8b754d462
Please let me know once you've applied!

**Comment by thesahindia** [comment] 2022-11-30 12:00
@flaviadefaria, the job is private.
<img width="840" alt="Screenshot 2022-11-30 at 5 29 06 PM" src="https://user-images.githubusercontent.com/83179295/204790776-fba071c0-86f5-4fe9-a471-848402fd411d.png">

**Comment by flaviadefaria** [comment] 2022-11-30 13:55
Weird can you try again now?

**Comment by thesahindia** [comment] 2022-11-30 14:07
Not sure what's wrong. Can you send me the offer or invite ([Upwork profile](https://www.upwork.com/freelancers/~0107fb10c8087f6a5a))

https://user-images.githubusercontent.com/83179295/204816590-709e11f9-becb-4510-82e9-c0151bd5892e.mov

**Comment by flaviadefaria** [comment] 2022-11-30 14:27
Hm I must have messed up somewhere, I'll invite you to the job thanks for sending your profile.

**Comment by flaviadefaria** [comment] 2022-11-30 14:31
Ok @thesahindia you should have now received my offer!

**Comment by thesahindia** [comment] 2022-11-30 14:37
Accepted, thanks!

**Comment by flaviadefaria** [comment] 2022-11-30 14:47
Alright you should now have been paid. Thanks for your patience @thesahindia!

**Comment by thesahindia** [comment] 2022-11-30 14:53
Let's close this.

**Comment by flaviadefaria** [comment] 2022-11-30 14:56
Closing it - thanks for your help!

**Closed by flaviadefaria** 2022-11-30 14:56 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
