### ISSUE TITLE
[$500] Log in - Chat are not loading after sign in to a specific account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33475] opened 2023-12-22 00:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open staging.expensify.com
2. Login with [applausetester++admin@applause.expensifail.com](mailto:applausetester++admin@applause.expensifail.com)

## Expected Result:
Chat should load with in few seconds

## Actual Result:
Chats never load

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6323336_1703201871837!image__16_](https://github.com/Expensify/App/assets/78819774/29fce4ae-b6c1-42ce-8b27-4957367e30bd)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d2e3da5f46aefcda</li>
        <li>Upwork Job ID: 1737996066757562368</li>
        <li>Last Price Increase: 2023-12-22</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-12-22 18:25
Gonna close this out also, I think can't reproduce

**Closed by Christinadobrzyn** 2023-12-22 18:25 UTC
Labels: External, Daily, Help Wanted, Bug
