### ISSUE TITLE
Payments - App is freezing after open Debit Card option under Payments and trying to close

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8800] opened 2022-04-27 15:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing PR:** https://github.com/Expensify/App/pull/8682

## Action Performed:
1. Launch the app
2. Log in with expensifail account
3. Navigate Workspace > Connect bank account several steps along the flow
4. Navigate Payments > Add payment method > Debit card
5. Close the page

## Expected Result:
User should be able to close the Debit Card option under Payments

## Actual Result:
App is freezing after open Debit Card option under Payments

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.57.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** applausetester+42222abb@applause.expensifail.com/Feya86Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/165560092-11808de3-5cd6-4182-bcd3-7f8d84434237.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment] 2022-04-27 16:23
I don't spot anything in the checklist that looks like it would directly cause this. I'm trying to reproduce the issue now. 

It appears like it works in web, so I'll move onto iOS next.

**Comment by francoisl** [comment] 2022-04-27 17:47
FWIW I can't reproduce either.

Also, to clarify, in the reproduction steps, you say:
> 3. Navigate Workspace > Connect bank account several steps along the flow

Does the issue only occur if you go through the workspace bank account flow first?

**Comment by kbecciv** [comment] 2022-04-27 19:12
@francoisl One account can reproduce this issue.

**Comment by tgolen** [comment] 2022-04-27 19:48
I think if we can't find anyone else that can reproduce this, then we can just close it and not have it be a deploy blocker.

**Closed** 2022-04-28 22:30 UTC
Labels: Engineering, Daily
