### ISSUE TITLE
[HOLD for payment 2023-06-08][$1000] Dev: Console error on reload page in Connect bank account page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19757] opened 2023-05-29 18:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces > Connect bank account
2. Click on connect manually
3. Reload the page

## Expected Result:
It should not show any console error

## Actual Result:
Shows console error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-1

**Reproducible in staging?:** No

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cc8b0cd4-4184-4e7a-9374-b8e1c4127623

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:**https://expensify.slack.com/archives/C049HHMV9SM/p1685008322770599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164470c9b3ebb6fd2</li>
        <li>Upwork Job ID: 1664363385558638592</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-06-01 20:08
Has been reproduced, adding External

**Comment by srikarparsi** [comment] 2023-06-02 16:10
Looks good to me as well, adding you to the issue @dhairyasenjaliya

**Comment by srikarparsi** [comment] 2023-06-05 16:29
Thanks for looking @aimane-chnaif! We'll close out the issue later today or tomorrow.

**Comment by sonialiap** [comment] 2023-06-07 19:29
Hi all! Sorry about the delay. Since the proposal was selected, PR written, and was in the process of being reviewed - you should receive compensation for the work done. I'm off for the night but I will set up payments tomorrow

**Comment by sonialiap** [comment] 2023-06-08 09:03
@gadhiyamanan offer sent for reporting issue
@dhairyasenjaliya offer sent for the fix
@aimane-chnaif offer sent for the review

**Comment by sonialiap** [comment] 2023-06-16 10:18
All paid, closing

**Closed by sonialiap** 2023-06-16 10:18 UTC
Labels: Reviewing, External, Daily, Bug
