### ISSUE TITLE
[Distance] Web - Folder can be dragged and dropped when uploading a receipt

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26892] opened 2023-09-06 17:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB > Request money > Scan
2. Drag & drop a folder

## Expected Result:
Unable to Drag & drop a folder

## Actual Result:
Able to Drag & drop a folder

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/51126fc6-38a6-4e25-bdd5-05f89778b77b

https://github.com/Expensify/App/assets/93399543/5d98ee2f-a564-4a6a-a9e1-f6688695d14c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693664700488289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment] 2023-09-06 17:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Folders can be dragged and dropped on the scan receipt page.

### What is the root cause of that problem?
Folders are not being validated in the validateReceipt method.

### What changes do you think we should make in order to solve the problem?
Update the validateReceipt method to check if the dragged item is a folder and reject accordingly.

### What alternative solutions did you explore? (Optional)
None.

**Comment by conorpendergrast** [comment] 2023-09-07 09:51
I can't reproduce this on Mac OSX Safari. I suspect that this is only happening on Windows, which isn't counted as an official platform at the moment. 

I'll close this as a result, but correct me if I'm wrong! 

![image](https://github.com/Expensify/App/assets/5802477/8f5c6e14-640b-4cd9-ab8b-97220151d385)

**Closed by conorpendergrast** 2023-09-07 09:51 UTC
Labels: Daily, Bug

**Comment by akinwale** [comment] 2023-09-07 10:23
> I agree that a more accurate error message would be helpful. That would be a feature request though, rather than this bug!

[My proposal](https://github.com/Expensify/App/issues/26892#issuecomment-1708846410) (I'm biased) ends up solving both, fixing the error and adding consistency, which I feel is a win-win.
