### ISSUE TITLE
[HOLD for payment 2024-06-20][$250] Room-User is allowed to invite via mentions invalid number.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41078] opened 2024-04-26 10:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4513241
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:**  Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a room report
3. Enter @+91 and send the message
4. Tap invite
5. Note invited message
6. Tap header--members---invite
7. Enter +91
8. Note no options to select and invite the contact is shown

## Expected Result:
User must not be allowed to invite via mentions invalid number.

## Actual Result:
User is allowed to invite via mentions invalid number.
Tapping header -- members -- invite, user unable to invite +91 but via mentions can invite.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/85b3296d-0c3e-41d8-8651-15ed91f8e1d3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cdf72ac69795bc85</li>
        <li>Upwork Job ID: 1784976134411239424</li>
        <li>Last Price Increase: 2024-05-09</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by izarutskaya** [comment] 2024-04-26 10:26
We think this issue might be related to the #vip-vsb.

**Comment by hungvu193** [comment] 2024-05-01 10:26
@lschurr I want to discuss about the expected behavior here. In this case, when we sent a invalid phone number, the whisper message shouldn't be displayed or it's displayed but we can't click the `Invite` button?

**Comment by lschurr** [comment] 2024-05-01 14:52
I'm not 100% sure - Would you mind starting a Slack thread to discuss @hungvu193?

**Comment by hungvu193** [comment] 2024-05-02 02:46
I raised on slack:
https://expensify.slack.com/archives/C01GTK53T8Q/p1714617971723469

**Comment by hungvu193** [comment] 2024-05-02 14:16
Coming from [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1714617971723469), I think we should handle this issue from BE, @lschurr can you please add the Internal label?

**Comment by lschurr** [comment] 2024-05-06 16:13
Asked in the Slack thread about best ways to move forward here. I think we need an Eng volunteer to assign this to.

**Comment by blimpich** [comment] 2024-05-07 21:49
I'll pick this up, I think it'll be a quick fix.

**Comment by blimpich** [comment] 2024-05-07 23:37
**Notes for myself:**

Looks like we have a couple ways in Web for validating a phone number, though we should probably only have 1. We also have ways of validating it from the client; one way to validate it is via a command called `IsValidPhoneNumber` (which doesn't appear to be used ever in App) but we also have ways that leverage other libraries as shown [here](https://github.com/Expensify/App/pull/40962/files#diff-7d43f3c3e4decdb0057928e895f456d51c0f4081837edd5e2c4ed7ddd570e274R1569). Auth doesn't seem to have methods for validating phone numbers, which seems odd to me.

Another funny thing is that we also seem to be making accounts for these invalid phone numbers. Like when you comment `@+91` it actually creates an account with the username +91@expensify.sms, even though we would reject making that account if a user tried to sign up with it. Not sure if we care about that or not. We probably don't care.

It seems like this will be easiest to fix in Web. But that may be problematic because I think these actionable mention whispers are made in Auth. We may need to port over our `TwilioUtils.php` file to Auth, or at least partly port it. That would take a little bit of time. But I think that would be the "best" solution since a Web solution will probably end up being quite hacky. Those are my thoughts after doing an initial inspection.

Will return to this tomorrow.

**Comment by blimpich** [comment] 2024-05-08 22:03
Ugh, this is more complicated than expected. Twilio uses the [E164 format](http://en.wikipedia.org/wiki/E.164) as their standard for what is and isn't a valid phone number, but this standard actually doesn't have a minimum number of digits necessary for it to be valid. See https://www.twilio.com/docs/api/errors/21211. This means that I don't think we can actually say that these phone numbers are invalid.

So, technically, `+91` is a valid phone number. And if you can believe it, according to the leading SMS api in the world, even `+` is a valid phone number. Kinda ridiculous.

I tested this by directing hitting Twilio's api using our own `TwilioUtils->isValidPhoneNumber` method in Web
![Screenshot 2024-05-08 at 1 52 36 PM](https://github.com/Expensify/App/assets/17171674/06023c14-5823-4852-aacd-65f3acca3957).

But we don't allow numbers like that to make accounts! If you type `+94` into the login page it'll tell you that's not a valid number! 
![Screenshot 2024-05-08 at 2 48 37 PM](https://github.com/Expensify/App/assets/17171674/3c3fe0b2-a68e-49d5-86cc-1c4bbdf3d267)
The reason is because we use the [awesome-phonenumber](https://www.npmjs.com/package/awesome-phonenumber) npm package to partly validate our phone numbers. And for some reason it seems to understand that `+94` is not a valid phone number, probably due to a very long if/else chain checking country code against phone number length. For example, Sweden only has to have 7 digits in their phone numbers ([source](https://stackoverflow.com/questions/14894899/what-is-the-minimum-length-of-a-valid-international-phone-number)).

Funnily enough this package is actually based off a C++ package from Google called [libphonenumber](https://github.com/google/libphonenumber). So we could download that into our C++ layer and start using that, but this is getting a little ridiculous.

**Comment by blimpich** [comment] 2024-05-08 22:11
So here's my take: lets fix this is in the frontend. I would have preferred to fix this in the backend but the only place in our stack that has logic that considers `+94` to be an invalid phone number is in the frontend. There is no existing logic in the backend that considers `+94` to be invalid, and knowing whether or not a phone number is invalid is actually surprisingly tricky due every country doing it slightly differently.

**Comment by blimpich** [comment] 2024-05-08 22:26
For what its worth for debugging this, I noticed in our post request to the server when we add a comment we format the comment with an `<mention-user>` tag. Find the logic that does that and make sure we are validating the number in the same way we do on the login screen and I think this will be a straightforward fix on the frontend:
![Screenshot 2024-05-08 at 3 06 46 PM](https://github.com/Expensify/App/assets/17171674/55b9623e-9209-4081-8472-3d5fc8e53b04)

**Comment by puneetlath** [comment] 2024-05-08 22:55
Using the awesome-phonenumber lib to validate whether it's a valid phone number before deciding to treat it as a mention on the client sounds good to me.

**Comment by nkdengineer** [comment] 2024-05-09 07:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is allowed to invite via mentions invalid number.
Tapping header -- members -- invite, user unable to invite +91 but via mentions can invite.

### What is the root cause of that problem?
We don't check the phone number of mention is valid or not before deciding to treat it as mention

https://github.com/Expensify/expensify-common/blob/a018512b1e0fce4d4b5a61c00ca826b8887007ad/lib/ExpensiMark.js#L200
### What changes do you think we should make in order to solve the problem?
We should use `awesome-phonenumber` lib to check the phone number of mention is valid or not

1. Create a `isValidPhoneNumber` function in `Str`

```
import {parsePhoneNumber} from 'awesome-phonenumber';
isValidPhoneNumber(phone) {
    return parsePhoneNumber(phone).possible;
},
```

2. Get the phone number from mention and check if it's not valid, we will not return this as mention

```
if (!Str.isValidMention(match) || (phoneRegex.test(g2) && !Str.isValidPhoneNumber(mention))) {
    return match;
}
```
https://github.com/Expensify/expensify-common/blob/a018512b1e0fce4d4b5a61c00ca826b8887007ad/lib/ExpensiMark.js#L200


Or we can bring this check into `isValidMention` function
### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/Expensify/App/assets/161821005/87110db5-acda-4e40-a4da-19d3f4f21d13

**Comment by roitman-g** [comment] 2024-05-09 15:43
what is considered a valid phone number in the app? For example, are the slashes allowed?

**Comment by blimpich** [comment] 2024-05-09 16:37
> what is considered a valid phone number in the app? For example, are the dashes allowed?

@roitman-g When you go to https://new.expensify.com and try to login using a phone number, any phone number that you can type into the login field without triggering a form error is a valid phone number. The logic for what is and isn't a valid number is dictated by https://www.npmjs.com/package/awesome-phonenumber.

**Comment by hungvu193** [comment] 2024-05-11 01:28
I'll review this one soon

**Comment by hungvu193** [comment] 2024-05-13 03:47
@nkdengineer I don't think your solution works, checkout this video:

https://github.com/Expensify/App/assets/16502320/2db27022-cca7-4e62-a31a-4208c94ec38e

**Comment by nkdengineer** [comment] 2024-05-13 04:35
@hungvu193 Missed to remove the SMS domain before checking valid phone number with `awesome-phonenumber`. I updated proposal https://github.com/Expensify/App/issues/41078#issuecomment-2102153310.

About the bug phone number doesn't appear as mention in composer, it also happens in main so I think it should be fixed in a separate issue.

**Comment by nkdengineer** [comment] 2024-05-13 07:47
> const mention = g2.slice(1);
if (!Str.isValidMention(match) || (phoneRegex.test(g2) && !Str.isValidPhoneNumber(mention))) {
    return match;
}

@hungvu193 Sorry I missed a line when add pseudo code in my proposal, we should slice the `@` character first. I updated https://github.com/Expensify/App/issues/41078#issuecomment-2102153310


https://github.com/Expensify/App/assets/161821005/2e83214c-6800-4a1e-ae18-e1be7d3e2a74


https://github.com/Expensify/App/assets/161821005/ea1447ed-df07-4167-be45-d959f43ad6e9

**Comment by hungvu193** [comment] 2024-05-13 09:11
This won't work when you tried to type a number with `expensify.sms` format, ie: @+81@expensify.sms

https://github.com/Expensify/App/assets/16502320/891c9504-4fb8-4b10-995b-7aa4d4e140e2

**Comment by nkdengineer** [comment] 2024-05-13 09:52
@hungvu193 Thanks for your feedback, this case doesn't work because `phoneRegex.test(g2)` has maximum `14` character after `@` and will return `false` when we type `+91@expensify.sms`. 

Updated proposal https://github.com/Expensify/App/issues/41078#issuecomment-2102153310 to also fix this case



https://github.com/Expensify/App/assets/161821005/debd7b25-b218-4d38-ac76-356cba5522e2

**Comment by hungvu193** [comment] 2024-05-14 03:01
Did you miss some steps or codes? The latest proposal updated broke the mention.

https://github.com/Expensify/App/assets/16502320/d3191c2b-169c-4a46-8738-b5daea25291d

**Comment by nkdengineer** [comment] 2024-05-14 03:31
@hungvu193 Sorry it's wrong typo I updated again https://github.com/Expensify/App/issues/41078#issuecomment-2102153310.

**Comment by hungvu193** [comment] 2024-05-14 04:06
I see. The only problem is the inconsistency of mention with sms domain between the composer and after it's being sent:


https://github.com/Expensify/App/assets/16502320/d74fcf71-c577-4529-8e01-4e9efa70bb3a

**Comment by nkdengineer** [comment] 2024-05-14 04:09
@hungvu193 I believe this can be fixed when we bump the `expensify-comon` version in `react-native-live-markdown`

**Comment by hungvu193** [comment] 2024-05-14 06:34
nkdengieer 's [proposal here](https://github.com/Expensify/App/issues/41078#issuecomment-2102153310) looks good to me.
cc @blimpich

**Comment by nkdengineer** [comment] 2024-05-15 09:48
@hungvu193 we have open PR [here](https://github.com/Expensify/expensify-common/pull/697)

**Comment by blimpich** [comment] 2024-05-17 22:06
waiting for merge freeze to be over

**Comment by lschurr** [comment] 2024-05-20 14:46
Same as last update I believe.

**Comment by lschurr** [comment] 2024-05-23 15:36
PR is still open

**Comment by blimpich** [comment] 2024-05-24 20:43
We are close to fixing, held up because merge freeze / slush. I'd like to wait till we are back to a normal deploy schedule to merge this.

**Comment by blimpich** [comment] 2024-05-27 17:13
Not overdue, waiting for merge freeze to be over.

**Comment by blimpich** [comment] 2024-05-28 21:31
Expensify-common PR is merged, but shouldn't be considered fixed until we have updated App to have the corresponding PR to update its commons' version. @nkdengineer please feel free to raise that 2nd PR

**Comment by blimpich** [comment] 2024-05-28 23:07
**Update:** reproducing the exact issue locally is a bit of a pain since there are two other bugs occurring in this same general flow:
1. when a submitter submits to an approver who is an admin, then the email actually shows "pay" instead of "approve" and doesn't group the IOU preview amounts
2. when submitting multiple normal IOUs between normal users if two IOUs are stacked on top of each other in the product then in the email the subject will have the report total but the IOU preview will have only the first IOU amount

The actual original bug described in the description of this issue, from what I can tell, is when we create a request to a approver who is not an admin on a policy with a smart scanned receipt _sometimes_ the IOU preview will display `$0.00` when it should display a non-zero value. A initially persuasive idea is that this is all due to smart-scanning taking longer than 10 minutes, which is how long it takes for the `NotifyOfflineUserAboutActivity` job to kick in and send this email. However, it seems that this bug is reproducible even when smartscanning finishes in time ([link](https://expensify.slack.com/archives/C049HHMV9SM/p1714162408179479?thread_ts=1713804836.727149&cid=C049HHMV9SM)). So I'm actually not 100% sure why this is happening.

**Here's my plan:**
I'm gonna report bug #1 that I found up there since I think that is actually a different issue and I'm gonna fix bug #2 as part of this issue. My hope is that fixing bug #2 will fix this issue since they seem to be very closely related.

If that doesn't work I'll start adding logs to get a better idea of what is going on here.

**Comment by hungvu193** [comment] 2024-05-30 03:11
Bump @nkdengineer , do you have any ETA for the bump version?
Also as you mentioned [here](https://github.com/Expensify/App/issues/41078#issuecomment-2109242732), we probably need to update `react-native-live-markdown` as well?

**Comment by nkdengineer** [comment] 2024-05-30 03:18
I'm going to create PR today.

**Comment by nkdengineer** [comment] 2024-05-30 10:53
I created a PR for react-native-live-markdown here https://github.com/Expensify/react-native-live-markdown/pull/360 but having some problem when run build parser.

**Comment by hungvu193** [comment] 2024-06-03 03:44
Can you please raise a discussion on slack about your issue?

**Comment by nkdengineer** [comment] 2024-06-03 05:11
I resolved the problem now. The PR is here https://github.com/Expensify/react-native-live-markdown/pull/360

**Comment by nkdengineer** [comment] 2024-06-10 03:56
@hungvu193 I create an additional PR here https://github.com/Expensify/expensify-common/pull/714 to fix the preview mention with invalid phone number.

**Comment by hungvu193** [comment] 2024-06-10 13:58
Thank you. I'll take a look tomorrow

**Comment by hungvu193** [comment] 2024-06-12 01:08
- [x] The PR that introduced the bug has been identified. Link to the PR: No offending PR
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.

We don't need regression test for this one imo, this was how our markdown worked, we can treat this issue as a improvement.

**Comment by nkdengineer** [comment] 2024-06-12 03:54
@hungvu193 The PR to bump Expensify-common in live-markdown [here](https://github.com/Expensify/react-native-live-markdown/pull/384)

**Comment by nkdengineer** [comment] 2024-06-13 10:17
@hungvu193 The App PR is [here](https://github.com/Expensify/App/pull/43644).

**Comment by lschurr** [comment] 2024-06-20 16:45
Payment summary:

- Contributor: @nkdengineer $250 (paid in Upwork)
- Reviewer: @hungvu193 $250 (paid in Upwork)

**Comment by nkdengineer** [comment] 2024-06-20 17:28
It's not a blocker from our PR here. Ref: https://github.com/Expensify/App/issues/44085#issuecomment-2181139931.

**Comment by lschurr** [comment] 2024-06-20 18:08
Great! Closing this one out since it's paid.

**Closed by lschurr** 2024-06-20 18:08 UTC
Labels: External, Daily, Awaiting Payment, Bug
