### ISSUE TITLE
[$250] Web - Control Workspace - The approver in next steps does not change to the owner

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49502] opened 2024-09-19 21:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4984506
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Preconditions:

Control workspace has advanced approval set with 2 approvers

Employee submits to approver A
Approver A submits to approver B
Approver B is the final approver

Employee
- Navigate to the workspace chat and submit a expense

Admin steps - OldDot

1. Navigate to the workspace settings > Members
2. Remove Approver A and B from the approval flow so they're not approvers anymore
3. Set the approvals to the admin (owner of the workspace)

Admin steps - NewDot
1. Log in as the admin (owner)
2. Navigate to the employee workspace chat
3. Click on the header > members

## Expected Result:
The previous approver have been removed from the chat member list
and the approver in next steps is the owner of the workspace

## Actual Result:
The previous approver have not been removed from the chat member list
and the approver in next steps is not the owner of the workspace

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7aaff1e4-d249-4613-acf7-772ee7ca6e76

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021842133983186199999</li>
        <li>Upwork Job ID: 1842133983186199999</li>
        <li>Last Price Increase: 2024-10-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>

**Comment by IuliiaHerets** [comment] 2024-09-19 21:17
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dylanexpensify** [comment] 2024-09-25 10:14
@Beamanator as I think this is related to our wave-control initiative cc @garrettmknight

**Comment by Beamanator** [comment] 2024-09-26 01:33
Hmm ok so there's 2 things reported here and here are my thoughts:

> The previous approver have not been removed from the chat member list

The previous approvers (A & B) definitely should have been removed from the workspace chat IFF they're non-admins

> and the approver in next steps is not the owner of the workspace

I believe the new approver (workspace owner) should NOT be in the next steps as the approver because the first step taken was `Employee submits to approver A` which makes `approver A` the report manager & that report manager shouldn't change when the approval chain is updated

**Comment by dylanexpensify** [comment] 2024-10-03 11:42
Thanks for clarifying @Beamanator! Should we then break this into two issues, one for each scenario?

**Comment by Beamanator** [comment] 2024-10-03 15:52
aah maybe i wasn't too clear - i was thinking there's actually only 1 bug here, even though 2 different "bugs" were reported

**Comment by dylanexpensify** [comment] 2024-10-07 12:23
Pending proposals

**Comment by suneox** [comment] 2024-10-09 15:12
@MelvinBot not overdue, still pending proposals

**Comment by suneox** [comment] 2024-10-14 18:39
Same above

**Comment by dylanexpensify** [comment] 2024-10-17 20:33
Hey @greg-schroeder! I'm heading out on parental leave so reassigning this! TY! 🙇‍♂️

**Comment by mvtglobally** [comment] 2024-10-19 03:50
Issue not reproducible during KI retests. (First week)

**Comment by suneox** [comment] 2024-10-21 18:23
Issue not reproducible so still waiting KI retest on next week

**Comment by greg-schroeder** [comment] 2024-10-24 20:19
closing as not reproducible

**Closed by greg-schroeder** 2024-10-24 20:19 UTC
Labels: External, Daily, Help Wanted, Bug
