### ISSUE TITLE
[HOLD for payment 2024-06-20] [Search v1] Opening transactions on search page can lead to not found page

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#41578] opened 2024-05-03 14:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Open the search page, `Profile > Troubleshoot > New Search Page`
2. Click on a transaction
3. Verify that you see a not found page

Note: this seems to only happen for older transactions that don't have a transaction thread created since the value for `transactionThreadReportID` is `0`.

## Expected Result:
We should create the transaction thread and let users open the transaction

## Actual Result:
Not found page is shown

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/22219519/ed64830c-ca4d-4ba7-b95e-c066fe5d6084
![Screenshot 2024-05-03 at 8 25 40 AM](https://github.com/Expensify/App/assets/22219519/483a6e64-a87b-407e-a031-fe8addeb5389)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b78bbfebf5ef557c</li>
        <li>Upwork Job ID: 1786400627125800960</li>
        <li>Last Price Increase: 2024-05-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by grgia** [comment] 2024-05-04 05:10
What we chatted about before:
Create a command - OpenTransactionThread (maybe `OpenSearchPreview` )
That calls auth.transaction.createTransactionThread if it doesn't already exist

Use the loading indicator on the page

**Comment by jliexpensify** [comment] 2024-05-07 01:43
Not overdue. Should we switch to `Weekly` to stop the pings?

**Comment by luacmartins** [comment] 2024-05-07 15:35
I think we might need a new command as @grgia described above, since calling `openReport` wouldn't be enough because we might not have a lot of the data needed, e.g. reportActions, parentReportActions, participant list, etc

**Comment by Kicu** [comment] 2024-05-09 13:07
@luacmartins @grgia I did some testing and in my experience the problem is almost exclusively that a lot of items simply have `reportID` set to `0` and so we try to open route with `0` inside and that gets us the "Not Found" page - which is correct behavior.

A lot of other items that looked legit opened correctly:

https://github.com/Expensify/App/assets/3929868/eae7796a-59fc-4bd7-b4c2-cf65d8ef115c

Sorry if I'm misunderstanding something - can't this be fixed in api by simply always returning some existing reportID?

**Comment by luacmartins** [comment] 2024-05-15 00:46
Still looking for volunteers. @grgia are you interested on working on this one?

**Comment by lakchote** [comment] 2024-05-15 07:25
> You understood it right. This happens because in the past we didn't create these threads for all reports, so they might not exist and we end up returning 0. The solution is to create a new command that will create the thread if it doesn't exist.

It should be fixed  by https://github.com/Expensify/Auth/pull/10456. We should create threads automatically from now on, even for old preexisting transactions.

**Comment by trjExpensify** [comment] 2024-05-15 10:15
Nice, @lakchote! That's on prod, so we can retest then, yeah? If so, @grgia @Kicu did you have some transactions in your account that definitely weren't working before to validate @lakchote's theory?

**Comment by Kicu** [comment] 2024-05-15 11:29
@trjExpensify @lakchote 

For me on dev every row that "looks" normally is correctly opening a report/IOU in RHP.
However every row with `__fake__` field has no `transactionID` and opens error page. I have no idea what these rows are and where do they come from. 

Seems there is an issue for this: https://github.com/Expensify/App/issues/41985

![Screenshot 2024-05-15 at 13 26 52](https://github.com/Expensify/App/assets/3929868/0865d96c-2c4a-4c14-b5cc-9a3d4d82888c)

**Comment by grgia** [comment] 2024-05-15 12:16
@trjExpensify we haven't implemented the fix for this one yet

**Comment by grgia** [comment] 2024-05-15 12:26
I missed this comment https://github.com/Expensify/App/issues/41578#issuecomment-2111774637 let's see

**Comment by trjExpensify** [comment] 2024-05-15 13:06
Cool yeah, we have an issue for expenses created via `Track expense` showing as _FAKE_ #41985

As for Chronos, are we going to hide those entries or something? They shouldn't be in the expenses filter really.

**Comment by jliexpensify** [comment] 2024-05-20 00:26
Not overdue!

**Comment by grgia** [comment] 2024-05-23 10:29
https://github.com/Expensify/App/issues/41578#issuecomment-2094018204 

I started looking into this solution, but haven't gotten a working PR up yet

**Comment by luacmartins** [comment] 2024-05-24 03:22
>on top of this, we'll want to return the snapshot data for that report I believe

Yes, this sounds correct.

**Comment by grgia** [comment] 2024-05-30 18:23
I'm wrapping up pending/scanning so I can focus on search moving forward

**Comment by luacmartins** [comment] 2024-05-31 16:01
I'll be taking over implementation since @grgia is focused on another project atm.

**Comment by luacmartins** [comment] 2024-05-31 19:59
I started investigating this issue today and I think we have 2 issues:

1. Transactions without threads created
2. Transactions in expense reports belonging to policies that are not workspace chat enabled yet

I'll start with 2 and filter out those transactions for now.

**Comment by luacmartins** [comment] 2024-05-31 21:47
Ok, the first PR is ready. I'll put it in review once the other Auth PRs have been merged and I can resolve conflicts.

**Comment by luacmartins** [comment] 2024-05-31 21:47
I'll work on creating the thread on Monday.

**Comment by jliexpensify** [comment] 2024-06-12 00:08
Payment Summary

- C+: @Santhosh-Sellavel $250 (ND payment)

Waiting on checklist

**Comment by jliexpensify** [comment] 2024-06-18 09:43
Is a checklist needed here @Santhosh-Sellavel ?

**Comment by luacmartins** [comment] 2024-06-18 14:49
No checklist needed. This is a new feature and we'll add tests as part of the project wrap up

**Comment by jliexpensify** [comment] 2024-06-19 03:32
Awesome, ty!

[Here's the ND payment summary for JMills](https://github.com/Expensify/App/issues/41578#issuecomment-2161824919)

**Closed** 2024-06-20 22:58 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
