### ISSUE TITLE
Chat scrolls after opening for the 2nd time reported by @thesahindia

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12363] opened 2022-11-02 01:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to a chat
2. Go back
3. Navigate to the same chat again

## Expected Result: 
The chat shouldn't scroll 

## Actual Result:  
The chat scrolls/jumps

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.22-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/199370814-ad69ccfb-8236-46f4-b8ef-18d4647ccb3a.mp4

https://user-images.githubusercontent.com/43996225/199370831-2b9640e6-6f0d-42b8-b84a-88cf4e5c586e.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667344960109819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01724eb25130776098
- Upwork Job ID: 1599617199055544320

**Comment by Christinadobrzyn** [comment] 2022-11-02 02:33
I don't have an Android and I can't replicate it on iOS. 

1. Send a message in chat
2. Tap the < arrow in the LHN
3. Tap on the chat again, there's no bouncing

<img src="user-images.githubusercontent.com/51066321/199381633-d73872b2-d954-48f0-9c45-e19c0ce48321.gif" width="200" height="400" />


I think this might be similar to these reports

https://github.com/Expensify/App/issues/11962
https://github.com/Expensify/App/issues/12237

So I don't know if this needs to be a new fix - sending to eng for a second opinion

**Comment by techievivek** [comment] 2022-11-04 08:57
My Android build is broken, but I think this could be related to https://github.com/Expensify/App/issues/11962
https://github.com/Expensify/App/issues/12237

**Comment by techievivek** [comment] 2022-11-07 08:00
Just tested this and there are 2 scenarios here:
1. If we have scrolled to a chat in the history then re-opening the chat scrolls to the latest input.
2. If we haven't scrolled in the first time and then re-open there is a scroll effect that is visible.

I am entirely sure what is the expected behaviour here so I am going to ask for some help from the team.

**Comment by techievivek** [comment] 2022-11-07 10:10
Not overdue, I have started a discussion on slack. But IMO we can fix the Android scrolling behaviour.

**Comment by techievivek** [comment] 2022-11-08 07:12
We would like to fix the jumping/drifting effect on Android when one re-opens the chat.

**Comment by techievivek** [comment] 2022-11-14 10:40
Looking for a proposal, if no one picks it up in a day I will give it a try myself.

**Comment by slafortune** [comment] 2022-11-15 17:31
Sorry - I hadn't realize I was assigned this 😞 Job created - https://www.upwork.com/ab/applicants/1592570903246962688/suggested

**Comment by puneetlath** [comment] 2022-11-17 21:19
@techievivek this is one of the oldest issues in the /App repo. To help us clear out the large backlog of bugs, can you:  
- Decide whether any proposals currently meet our guidelines and can be approved as-is 
- For any that can't, please take this issue internal and treat it as one of your highest priorities 
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by techievivek** [comment] 2022-11-18 03:16
@puneetlath We haven't received any proposal so far for this issue. I am working limited hours this week(ooo today); otherwise, I can give it a look myself.

**Comment by techievivek** [comment] 2022-11-18 03:33
@puneetlath NVM, I just had a look at the internal discussion. I will start looking into the issue.

**Comment by parasharrajat** [comment] 2022-11-21 20:00
Being reviewed internally.

**Comment by techievivek** [comment] 2022-11-24 08:24
Not overdue, catching up from ooo.

**Comment by techievivek** [comment] 2022-11-28 09:21
Not overdue; already looking into it.

**Comment by techievivek** [comment] 2022-11-28 12:03
Ok, just figured out the issue behind it. It's probably because of this prop `maintainVisibleContentPosition` that gets passed to FlatList [here](https://github.com/Expensify/App/blob/240eca4ce517f57ed5d6a22e6e9b6a340867aa6c/src/components/InvertedFlatList/BaseInvertedFlatList.js#L147). 

Looking into the [documentation](https://reactnative.dev/docs/scrollview#maintainvisiblecontentposition-ios) it says the prop only works for `ios` but it does have some visible effect on `android` as well because looking at the main [issue](https://github.com/Expensify/App/issues/7145) where we added this prop as a fix, it did fix both iOS and Android.

**Comment by techievivek** [comment] 2022-11-28 12:20
Looking at @roryabraham comment [here](https://github.com/facebook/react-native/pull/29466#issuecomment-1288722179) I think we are already supporting this for Android and that could be the reason we are seeing this behaviour.

@roryabraham Any thoughts on this issue?

**Comment by roryabraham** [comment] 2022-11-29 09:13
Yes, we do have `maintainVisibleContentPosition` implemented on Android in our fork.

I'm not sure the "animation glitch" that is described in the OP of this issue is the same as what was fixed in https://github.com/Expensify/App/issues/7145:

- This issue happens repeatably when closing and opening the drawer
- https://github.com/Expensify/App/issues/7145 would only happen when new messages landed in the chat

**Comment by techievivek** [comment] 2022-11-29 17:53
I just tested by commenting out the prop and it seems to not have that drift/scroll effect when we re-open the chat.

With prop
----------

https://user-images.githubusercontent.com/35863227/204604664-cbbb3bd7-de52-4cfe-a607-74254b7951b5.mov


Without Prop
-------------

https://user-images.githubusercontent.com/35863227/204605117-f83a1010-3215-49cf-8551-1243d8ef629f.mov

**Comment by roryabraham** [comment] 2022-11-29 20:38
Oh, good find. We do need that prop implemented. Maybe try playing with the `autoScrollToTopThreshold` value? make it `1` instead of `0`?

**Comment by techievivek** [comment] 2022-11-30 18:05
playing with `autoScrollToTopThreshold` doesn't seem to help but when I am setting `minIndexForVisible` with a value greater than 15 it does work( I am also very clueless with both the properties because it's hard to visualize what effect they will have on scroll view). 

Our window size is `15` so does it have something to do with `minIndexForVisible`?

**Comment by techievivek** [comment] 2022-12-01 13:55
Will be working on this internally.

**Comment by vijeeshin** [comment] 2022-12-02 12:16
@techievivek 

**Proposal**

Add loading in the state

`this.state = {
            fadeInAnimation: new Animated.Value(0),
            loading:false
 };`

 Change data of InvertedFlatList

`data={this.state.loading?this.props.sortedReportActions:[]}`

Add this to onLayout

`onLayout={e=>{
                        this.setState({loading:false},()=>{
                                this.setState({loading:true});
                        });
                        this.props.onLayout(e);
             }}`

This might not be the best solution, but it's the best workaround without major component changes.

**Issue**

Data is available even before the side drawer opens and it is loaded into Flatlist which auto adjusts the scroll height.

**Comment by techievivek** [comment] 2022-12-05 04:13
@vijeeshin Reviewing it today, thanks for the proposal.

**Comment by techievivek** [comment] 2022-12-05 10:46
@vijeeshin I did have a look at the proposal. Though it fixes the issue, the transition doesn't seem to be smooth. Also, it's more of a hack than an actual fix. So my question here is why we can't have a proper fix for this?

**Comment by vijeeshin** [comment] 2022-12-05 11:09
> @vijeeshin I did have a look at the proposal. Though it fixes the issue, the transition doesn't seem to be smooth. Also, it's more of a hack than an actual fix. So my question here is why we can't have a proper fix for this? Also, it's weird that it only happens on Android and not on iOS, any reason?

Yes its an hack, problem i noticed that. When u click on a chat.Data is fed to flatlist even before the page got settled. So it autoadjust the height . If you can introduce a variable which is false on construct and true on componentdidmount and false when componentwillunmount and using that variable to delay data to flatlist will work. Unfortunately componentwillunmount will not work in current scenario. We can discuss it further.

**Comment by vijeeshin** [comment] 2022-12-05 11:38
I will check that

**Comment by techievivek** [comment] 2022-12-06 08:30
@vijeeshin Please have a look at the comments from [here](https://github.com/Expensify/App/issues/12363#issuecomment-1328959309) it will give you the context.

**Comment by vijeeshin** [comment] 2022-12-06 11:20
any option to debug this file MaintainVisibleContentPositionHelper.java, I can see it is calculating computeTargetView on will mount and updateScrollPositionInternal on didMountItems

**Comment by vijeeshin** [comment] 2022-12-06 14:27
I think mistake is in computeTargetView

**Comment by parasharrajat** [comment] 2022-12-06 14:29
FYI, we are using our own version of RN https://github.com/Expensify/App/blob/fa19a2d5e6f27dbc0f72ead48afddcd85e1d20b5/package.json#L89 which probably have support for maintainVisibleContentPosition on Android.

**Comment by techievivek** [comment] 2022-12-08 15:24
@bernhardoj We have already added support for android: https://github.com/Expensify/react-native/pull/32/commits/82517414473d32c3e372509ee69f8d8554527f31

<img width="873" alt="Screenshot 2022-12-08 at 8 54 20 PM" src="https://user-images.githubusercontent.com/35863227/206485434-a5378545-08a1-4880-9129-58204753ba92.png">

**Comment by techievivek** [comment] 2022-12-08 15:26
@janicduplessis Hey, do you mind looking into this issue and see if this has something to do with the android support for the `maintainVisibleContentPosition` prop? Thanks

**Comment by techievivek** [comment] 2022-12-08 18:51
Hey, @janicduplessis; sorry for the bump. We don't want you to be looking into this issue, in fact, we can just hold this issue to our new list component, `WishList`, and hopefully, that would fix it automatically.

**Comment by JmillsExpensify** [comment] 2022-12-08 23:26
Wait, sorry for the confusion. We're super far out on WishList. Is there really no solution we could implement or explore in the meantime. I wouldn't be surprise if WishList is months and months away.

**Comment by techievivek** [comment] 2022-12-09 06:12
This seems to be happening only on android(native) and not on any other platform. I did invest some time looking into it but couldn't find a solid fix. Not sure how worthy it will be to look more into it, but if you suggest, we can leave it open for proposals or share it internally for someone to have a look. Do let me know what you think. Thanks

**Comment by bernhardoj** [comment] 2022-12-09 07:28
@techievivek Ah, my bad. I was checking the code on the main branch and was searching for it. I will take a look at the android implementation.

In the meantime, I tried to remove the `autoscrollToTopThreshold` property from `maintainVisibleContentPosition` and it solves the issue. I still don't understand what that property is doing, maybe we can remove it for Android or both as it is an optional property, maybe not.

**Comment by techievivek** [comment] 2022-12-09 08:16
It fixes the issue when we remove the property `autoscrollToTopThreshold` but we would like to keep that property https://github.com/Expensify/App/issues/12363#issuecomment-1331270306

Could you try looking into native code and see if you find something?

> I still don't understand what that property is doing
I stumbled upon the same question because I am not able to visualize what these properties do.

**Comment by bernhardoj** [comment] 2022-12-09 11:22
I can't find the reason why adding `autoscrollToTopThreshold` to `maintainVisibleContentPosition` creating this issue, but I now understand what it is used for after tested it on iOS. When our scroll offset is within the threshold, it will auto scroll to top (or bottom in inverted) when there is a new chat. But we set it to 0 which means the auto scroll will never happens.

So, if we want to have a simple solution in the meantime while waiting for the WishList to be published, we can remove the `autoscrollToTopThreshold` from `maintainVisibleContentPosition` in `BaseInvertedFlatList.js`

**Comment by vijeeshin** [comment] 2022-12-09 11:45
My observation,


https://user-images.githubusercontent.com/772974/206694934-9518aa9d-1f21-4200-b9f9-6e5407ac3a97.mov

Why loop break, because computeTargetView is called again.

```
 @Override
  public void willDispatchViewUpdates(final UIManager uiManager) {
   UiThreadUtil.runOnUiThread(() -> computeTargetView());
  }

  @Override
  public void willMountItems(UIManager uiManager) {
    computeTargetView();
  } 
```
after willMountItems, willDispatchViewUpdates is called since it is a drawer.  Value of i = 1 

@roryabraham

**Comment by vijeeshin** [comment] 2022-12-09 14:08
159   int currentScroll = mHorizontal ? mScrollView.getScrollX() : mScrollView.getScrollY();

160   for (int i = mConfig.minIndexForVisible; i < contentView.getChildCount(); i++) {

161    View child = contentView.getChildAt(i);

162   float position = mHorizontal ? child.getX() : child.getY();

163     if (position > currentScroll || i == contentView.getChildCount() - 1) {

My observation

After debugging  maintainvisiblecontentposition.java it is understood that

Program runs in this pattern

1. Linenumber 159 determines currentscroll to zero
2. Line 160 where i=0, mConfig.minIndexForVisible = 0 and contentView.getChildCount() =19
3. Line 161 View child = contentView.getChildAt(i);  which retrives child at 0 position of ReactViewGroup

After Line 161 execution instead of moving to line 162, loop breaks and again start from 159.  Then to 160 this time i is not zero but one, then loop runs and breaks at condition is satisfied.

This states that computeTarget runs 2 time before condition is satisfied.

NB: correction need in this line    if (position > = currentScroll || i == contentView.getChildCount() - 1) {

**Comment by JmillsExpensify** [comment] 2022-12-09 15:33
@techievivek Let's remove the hold and see if we can find a reasonable way to solve this ahead of WishList. That's a pretty far out solution.

**Comment by techievivek** [comment] 2022-12-12 06:42
@bernhardoj 
> but scroll it to top (or bottom) when it is within the scroll threshold. But we set it to 0 which means the auto scroll will never happens.

Interesting point, so there is no use in having the property set here; in fact it has some undesirable side effects. Could it be that `autoscrollToTopThreshold` for android has some bug, and even though it is set to 0, it is causing the drift effect when one re-opens the chat? But I agree if the value is `0`, then it doesn't make sense to keep the property. So yes, getting rid of the property seems like one of the solutions here.

@parasharrajat Any thoughts here?

**Comment by trjExpensify** [comment] 2022-12-13 19:13
@techievivek can you confirm what happened from [here](https://github.com/Expensify/App/issues/12363#issuecomment-1333803520) in the issue? 

At more than 4 weeks old we expect it to stay internal for someone to champion. It's currently in limbo as neither internal or external. Can you bring a summary to Slack for a discussion? If you haven't got the bandwidth for it anymore with the navigation reboot project, let's source an internal volunteer to carry the torch forward. Thanks!

**Comment by techievivek** [comment] 2022-12-15 04:45
@parasharrajat Can you please have a look at the comment put by @bernhardoj [here](https://github.com/Expensify/App/issues/12363#issuecomment-1344185604)?

**Comment by trjExpensify** [comment] 2022-12-16 11:58
@parasharrajat did you not get whitelisted yet? 😕

**Comment by techievivek** [comment] 2022-12-19 09:01
Not overdue, waiting for Rajat to share his views on the proposed solution and my comment [here](https://github.com/Expensify/App/issues/12363#issuecomment-1352553417).

**Comment by roryabraham** [comment] 2022-12-21 19:09
> So, if we want to have a simple solution in the meantime while waiting for the WishList to be published, we can remove the autoscrollToTopThreshold from maintainVisibleContentPosition in BaseInvertedFlatList.js.

I think this is okay. Normally we would opt to go for an upstream fix, but realistically we would need help from @janicduplessis to figure that out, and right now I think we'd rather see him dedicate his time to Margelo's incoming replacement for React Native's FlatList.

**Comment by JmillsExpensify** [comment] 2022-12-21 20:23
I agree with that. I think this is a totally valid case to go for the simple solution.

**Comment by techievivek** [comment] 2022-12-25 14:57
We have decided to close this bug because it appears to be minor and only affects the Android build. Additionally, fixing it would require diving into the native side of the code, which we are not currently interested in exploring. 

We are hoping that this bug will be automatically resolved when we migrate to Maregelo's next-gen FlatList implementation aka WishList. 

We have more pressing issues and improvements to work on, so we would like to allocate our resources to those tasks. If you have any comments on this decision, please feel free to add them to this [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1671463632967299) and we can look into it.

**Closed by techievivek** 2022-12-25 14:57 UTC
Labels: Engineering, Daily, Bug

**Comment by JmillsExpensify** [comment] 2022-12-26 16:16
Thanks, agreed with this approach.
