### ISSUE TITLE
[$500] Profile - The timezone does not exist after toggle off `Automatically determine your location`

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28329] opened 2023-09-27 16:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition:
+ Your browser should set timezone to America/Godthab or Asia/Saigon or America/Cordoba or Pacific/Samoa
+ Follow method 1 on this guide to change (https://www.browserstack.com/guide/change-time-zone-in-chrome-for-testing)
1. Go to settings => profile => timezone
2. Change "Automatically determine your location" from on to off.
3. Select Timezone manual from dropdown list

## Expected Result:
The timezone will show and auto select from "Automatically determine your location"

## Actual Result:
No timezone selection

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v 1.3.74-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d1bfe15c-c812-4693-b81a-476b90b18055

https://github.com/Expensify/App/assets/115492554/8daac6c5-3505-4818-8094-0c850f478a94

https://github.com/Expensify/App/assets/115492554/f7cc4c6d-c653-4761-bd4a-c195ba55a616

https://github.com/Expensify/App/assets/115492554/52722bde-9f2a-4731-9014-2d140c25ba2d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @suneox

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695577882053919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ad1c1482cffdc01</li>
        <li>Upwork Job ID: 1707072714927910912</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-09-28 09:11
I don't understand what the bug is here. This is working for me, and my sense is it is in the video as well. Discussing [here. ](https://expensify.slack.com/archives/C049HHMV9SM/p1695892275340409?thread_ts=1695577882.053919&cid=C049HHMV9SM)

**Comment by joekaufmanexpensify** [comment] 2023-09-29 08:10
Closing this based on[ this discussion](https://expensify.slack.com/archives/C049HHMV9SM/p1695974418015899?thread_ts=1695577882.053919&cid=C049HHMV9SM). I can't reproduce the bug, and we don't want to proceed if it is not consistently reproducible.

**Closed by joekaufmanexpensify** 2023-09-29 08:10 UTC
Labels: External, Daily, Help Wanted, Bug
