### ISSUE TITLE
[HOLD for payment 2023-08-28] [$1000] Dev: Web - Emoji-reacted tooltip does not close for User B when User A deletes the message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23308] opened 2023-07-20 20:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to User A's account.
2. Open User B's chat from User A's account.
3. Send a message and react to it with an emoji.
4. Open another browser and log in with User B's account.
5. Open userA chat and right-click on the reacted emoji to open tooltip
6. Go back to User A's account
7. Now, delete the message
8. Notice tooltip will not close after deleting message

## Expected Result:
The emoji-reacted tooltip should close for User B's account when User A deletes the message

## Actual Result:
The emoji-reacted tooltip remains open for User B's account even after the message is deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.43-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/da66e612-783e-4d19-88cb-7bbda1131a69

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689857009202199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01974ea524eb1b8de8</li>
        <li>Upwork Job ID: 1687058873174310912</li>
        <li>Last Price Increase: 2023-08-10</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26111902</li>
<li>hoangzinh | Contributor | 26111904</li>
</ul></li>
    </ul>
</details>

**Comment by ayazhussain79** [comment] 2023-07-20 21:21
This bug might be regression of this [PR](https://github.com/Expensify/App/pull/17996)

**Comment by StevenKKC** [comment] 2023-07-20 21:31
This issue will be fixed by [this proposal](https://github.com/Expensify/App/issues/23307#issuecomment-1644611888).

**Comment by ayazhussain79** [comment] 2023-07-20 21:34
@StevenKKC  Root case of the both is not same right?

**Comment by StevenKKC** [comment] 2023-07-20 21:39
@ayazhussain79 The root cause of this issue is that showing incorrect tooltip, so tooltip does not close automatically.

**Comment by dylanexpensify** [comment] 2023-07-24 08:24
Reviewing today!

**Comment by dylanexpensify** [comment] 2023-07-24 10:08
Agree @StevenKKC

**Comment by ayazhussain79** [comment] 2023-07-27 16:52
@dylanexpensify This bug is still reproducible and [PR](https://github.com/Expensify/App/pull/17996) merged
Same issue reported today https://github.com/Expensify/App/issues/23746

**Comment by CortneyOfstad** [comment] 2023-07-28 18:40
@dylanexpensify Reopening this as have other cases being reported of this, and this one is the earliest case 👍

**Comment by ayazhussain79** [comment] 2023-07-28 19:02
@CortneyOfstad Thank you

**Comment by StevenKKC** [comment] 2023-07-28 21:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emoji-reacted tooltip does not close for User B when User A deletes the message.

### What is the root cause of that problem?
The root cause is `PopoverReactionList` component does not reflect whether the report action is deleted.
In `PopoverReactionList` component, there is no checking whether the report action is deleted.

### What changes do you think we should make in order to solve the problem?
We should check whether the report action is deleted in `PopoverReactionList` component.
* Pass `reportID` to `PopoverReactionList` in [this line]().
```js
    <PopoverReactionList ref={context.reactionListRef} reportID={props.reportID} />
```
* Add `reportActionID` parameter to `showReactionList` function in `PopoverReactionList.js`.
```js
-   showReactionList(event, reactionListAnchor, emojiReaction) {
+   showReactionList(event, reactionListAnchor, emojiReaction, reportActionID) {
        ...
        this.getReactionListMeasuredLocation().then(({x, y}) => {
            this.setState({
                ...
+               reportActionID,
            });
        });
    }
```
* Add checking in `shouldComponentUpdate`.
```js
    shouldComponentUpdate(nextProps, nextState) {
        ...
+       const reportAction = ReportActionsUtils.getReportAction(this.props.reportID, this.state.reportActionID);
+       const isDeletedAction = ReportActionsUtils.isDeletedAction(reportAction);
+       if (isDeletedAction) {
+           this.hideReactionList();
+           return;
+       }

        return (
            ...
        );
    }
```
* Add `reportID` propTypes to `PopoverReactionList` component.
```js
    const propTypes = {
        /** The report currently being looked at */
        reportID: PropTypes.string.isRequired,

        ...withLocalizePropTypes,
    };
    ...

    PopoverReactionList.propTypes = propTypes;
```
* Add `reportActionID` `state` variable in `constructor`.
```js
    constructor(props) {
        super(props);

        this.state = {
            ...
            reportActionID: '',
        };
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by StevenKKC** [comment] 2023-07-28 21:47
@dylanexpensify Sorry for confusion. I said that my proposal will fix this issue, but my proposal does not accepted.

**Comment by dylanexpensify** [comment] 2023-07-31 09:09
reviewing today!

**Comment by dylanexpensify** [comment] 2023-08-03 12:13
@fedirjh to review proposals!

**Comment by dylanexpensify** [comment] 2023-08-10 10:06
@fedirjh let's review these responses today! 🙌

**Comment by dylanexpensify** [comment] 2023-08-11 19:54
bump!

**Comment by dylanexpensify** [comment] 2023-08-14 08:02
looking now

**Comment by Li357** [comment] 2023-08-14 12:57
Thanks for keeping this going everyone. Look forward to centralizing the logic here @hoangzinh

**Comment by dylanexpensify** [comment] 2023-08-18 19:14
Nice one!!

**Comment by dylanexpensify** [comment] 2023-08-25 11:47
Payment coming next week!

**Comment by dylanexpensify** [comment] 2023-08-29 09:25
Woot! Let's get it - Payment Summary:
- Reporter: @ayazhussain79 $250
- Contributor: @hoangzinh $1,500
- Contributor+: @fedirjh $1,500

[Upwork Job](https://www.upwork.com/jobs/~01974ea524eb1b8de8)! Please apply!

**Comment by ayazhussain79** [comment] 2023-08-29 10:45
@dylanexpensify applied on upwork, Thank you

**Comment by dylanexpensify** [comment] 2023-08-31 09:04
Paying out now!

**Comment by dylanexpensify** [comment] 2023-09-01 11:58
Payments sent! @ayazhussain79 offer sent!

**Comment by ayazhussain79** [comment] 2023-09-01 12:00
@dylanexpensify offer accepted, Thank you

**Comment by dylanexpensify** [comment] 2023-09-01 12:06
Done! @fedirjh can you complete checklist please?

**Comment by dylanexpensify** [comment] 2023-09-11 10:18
Looks good!

**Closed** 2023-09-11 10:19 UTC
Labels: External, Engineering, Daily, Needs Reproduction, Awaiting Payment, Bug
