### ISSUE TITLE
[HOLD for payment 2024-05-02] [$250] Workspace features - App shows two not here pages when opening inaccessible feature page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39092] opened 2024-03-27 19:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to feature page of a workspace in which user is not a member. (https://staging.new.expensify.com/settings/workspaces/CE183C61DF23465B/distance-rates
)

## Expected Result:
App will show not here page in full screen

## Actual Result:
App shows not here page on the left and right

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

<img width="1440" alt="Bug6428991_1711560411823!Screenshot_2024-03-28_at_01 24 26" src="https://github.com/Expensify/App/assets/78819774/53d03e4d-8573-4cb7-847c-1ba0e5ca7ef4">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a372bbcef3dbf2a7</li>
        <li>Upwork Job ID: 1773511214615310336</li>
        <li>Last Price Increase: 2024-03-29</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-27 19:02
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-27 19:02
We think that this bug might be related to #wave-control

**Comment by abzokhattab** [comment] 2024-03-29 01:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App shows two not here pages when opening the inaccessible feature page
### What is the root cause of that problem?
 
we use the [NotFound](https://github.com/Expensify/App/blob/972351979f1df98f84a996f8c074895b27481000/src/pages/workspace/AdminPolicyAccessOrNotFoundWrapper.tsx#L53) component in the `AdminPolicyAccessOrNotFoundWrapper` which only shows a minimized "not found" page and it doesn't take the full screen size. 

instead, we should use `FullPageNotFoundView`so that not here page takes the whole view 

### What changes do you think we should make in order to solve the problem?


we need to use the `FullPageNotFoundView`inside the  `AdminPolicyAccessOrNotFoundComponent` only since it's the **parent** component in all of the occurrences ([here](https://github.com/Expensify/App/blob/9d5fed69719033ba8ac932c66b0c68ae50609944/src/pages/workspace/WorkspaceMoreFeaturesPage.tsx#L167) [here](https://github.com/Expensify/App/blob/115730f2389678a312d6bbb534b9a71bb57580cf/src/pages/workspace/categories/CategorySettingsPage.tsx#L74) [here](https://github.com/Expensify/App/blob/9c2312819b9a95e71a0646015900f974cf77f91d/src/pages/workspace/categories/CreateCategoryPage.tsx#L41) , [here](https://github.com/Expensify/App/blob/ea101830b27f2651af841522fb413f93594dbc3c/src/pages/workspace/categories/EditCategoryPage.tsx#L63),  [here](https://github.com/Expensify/App/blob/7f2c7ee0e1fedfb6663efd2117968c02bd5dc99e/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L265), ..... )  
Consequently, there is no necessity to revise the `PaidPolicyAccessOrNotFoundComponent` or any subsidiary wrapper components. They should remain as is.

To do that we need to change [this](https://github.com/Expensify/App/blob/972351979f1df98f84a996f8c074895b27481000/src/pages/workspace/AdminPolicyAccessOrNotFoundWrapper.tsx#L53) to:

```js
     return (
            <FullPageNotFoundView
                shouldForceFullScreen
                shouldShow
                onBackButtonPress={() => Navigation.goBack(ROUTES.WORKSPACE_PROFILE.getRoute(props.policyID))}
            />
        );
```

**Comment by nkdengineer** [comment] 2024-03-29 05:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App shows not here page on the left and right

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/pages/workspace/AdminPolicyAccessOrNotFoundWrapper.tsx#L53) and [here](https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/pages/workspace/PaidPolicyAccessOrNotFoundWrapper.tsx#L53), we only show the `NotFoundPage` which will cover only the main part of the screen, not the left `WorkspaceInitialPage`.

The reason for that is because, if the user has access to the policy, they have access to the `WorkspaceInitialPage` too, just not the specific workspace page in the main UI (because that user is not and admin or the workspace is not a paid one). So it makes sense to show NotFound page only in the main UI so the user could still navigate to other accessible workspace tabs if they want to. We can also see that our intention was to navigate to the workspace profile page of that workspace in `onBackButtonPress` (see [here](https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/pages/workspace/AdminPolicyAccessOrNotFoundWrapper.tsx#L53)), so we are expecting here that the user access to the workspace already.

But this is not always true, there're scenario where the user don't actually have access to that workspace at all (non-existent workspace or the user is not a member of that workspace). In this case the user won't see the left- `WorkspaceInitialPage` too, so it shows as 2 NotFoundPages.

### What changes do you think we should make in order to solve the problem?

We should make clear of 2 scenarios:
1. If the user doesn't have access to the workspace: We need to show the `FullPageNotFoundView` that covers the full screen (not 2 not found pages as currently), and when the user clicks back press, we should `goBack`  with the workspace list pages as fallback (or home screen, depending on team's decision). We can't `goBack` with workspace profile page as we're doing [here](https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/pages/workspace/AdminPolicyAccessOrNotFoundWrapper.tsx#L53), because the user won't have access even to that profile page so that will be another not found screen when the user clicks on back press.
2. If the user has access to the workspace, but not the specific page they're trying to get in: Show not found page in the main UI as currently (the left- `WorkspaceInitialPage` should still be accessibile)

We can do that by updating github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/pages/workspace/AdminPolicyAccessOrNotFoundWrapper.tsx#L52-L54
```
if (shouldShowNotFoundPage) {
    const isPolicyNotAccessible = isEmptyObject(props.policy) || !props.policy?.id;

    if (isPolicyNotAccessible) {
        return <FullPageNotFoundView
            shouldShow
            shouldForceFullScreen
            onBackButtonPress={() => Navigation.goBack(ROUTES.SETTINGS_WORKSPACES)}
        />
    }
    return <NotFoundPage onBackButtonPress={() => Navigation.goBack(ROUTES.WORKSPACE_PROFILE.getRoute(props.policyID))} />;
}
```
(Do the same in `PaidPolicyAccessOrNotFoundComponent`, or in `FeatureEnabledAccessOrNotFoundComponent` too if we want)

### What alternative solutions did you explore? (Optional)
We can show `FullPageNotFoundView` for both scenarios listed above, but importantly we need to `goBack` to the correct page. Either always go back to `ROUTES.SETTINGS_WORKSPACES` or go back to `ROUTES.SETTINGS_WORKSPACES` if workspace is not accessibile, and to `ROUTES.WORKSPACE_PROFILE.getRoute(props.policyID)` if workspace is accessible. If not there'll be a bug when doing back press.
> because the user won't have access even to that profile page so that will be another not found screen when the user clicks on back press.

**Comment by greg-schroeder** [comment] 2024-04-03 09:24
Pending proposal review @alitoshmatov

**Comment by alitoshmatov** [comment] 2024-04-03 21:38
@Krishna2323 Thank you for your proposal, you solution causes to show not fullscreen found page always even though user has access to workspace

**Comment by alitoshmatov** [comment] 2024-04-03 21:41
@nkdengineer Thank you for your proposal, Your RCA is correct and your solution looks good. I think going back to workspaces list is better option when user does not have access to the workspace

We can go with @nkdengineer 's [proposal](https://github.com/Expensify/App/issues/39092#issuecomment-2026678032)

C+ reviewed 🎀 👀 🎀

**Comment by greg-schroeder** [comment] 2024-04-05 21:36
Bump @youssef-lr on contributor selection :)

**Comment by youssef-lr** [comment] 2024-04-06 00:47
LGTM as well!

**Comment by greg-schroeder** [comment] 2024-04-15 02:57
Linked PR is in review, needs @alitoshmatov to take a look as a next step!

**Comment by alitoshmatov** [comment] 2024-05-01 05:09
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/36324
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/36324/files#r1585896057
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. No need

**Comment by greg-schroeder** [comment] 2024-05-03 09:30
@alitoshmatov paid
@nkdengineer manual offer sent, i'll pay you right away as soon as you accept!

no regression test per C+, closing accordingly.

**Closed by greg-schroeder** 2024-05-03 09:30 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by nkdengineer** [comment] 2024-05-06 10:45
@greg-schroeder I accepted the offer 🙏
