### ISSUE TITLE
[HOLD for payment 2023-05-29] Allow admin deleting of comments

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#18727] opened 2023-05-10 17:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem
When offensive or spammy comments are posted in a room, admins should be able to delete the messages right away. We already allow them to remove messages after they are flagged in the moderation process.

## Importance
We want to maintain a pleasant community in NewDot and we can't do that if unwanted messages are hanging around and ruining it for everyone else. This is a top priority for upcoming large conferences like RENDERATL.

## Solution
Allow admins of a room to delete comments

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** N/A
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**
![image (1)](https://github.com/Expensify/App/assets/26260477/71e0ca42-eabe-4087-bf77-f90a3f5f21bf)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar
**Slack conversation:** https://expensify.slack.com/archives/C04QEB4MJEQ/p1683650689339049?thread_ts=1683583595.780049&cid=C04QEB4MJEQ

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment] 2023-05-10 17:54
I'll be working on this internally as my top priority

**Comment by alex-mechler** [comment] 2023-05-11 17:35
Jumping in here to get this across the line while Neil is OOO

**Comment by lschurr** [comment] 2023-05-16 19:24
I'm heading OOO from May 17-23rd so I re-added the Bug label in case any action is needed from the BZ team during that time. If this is still open on May 24th, I'll take it back from you @dylanexpensify!

This is entirely internal I believe, so BZ likely isn't needed.

**Comment by dylanexpensify** [comment] 2023-05-17 07:15
Sounds good!! Have a great time off @lschurr!!

**Comment by neil-marcellini** [comment] 2023-05-17 23:24
The App PR was just merged and will be CPed to staging.

**Comment by sobitneupane** [comment] 2023-05-18 04:59
@dylanexpensify Can you please assign me to the issue. I reviewed the associated PR.

**Comment by alex-mechler** [comment] 2023-05-18 16:14
@sobitneupane Assigned you!

**Comment by dylanexpensify** [comment] 2023-05-22 18:36
[I'm heading OOO tomorrow](https://expensify.slack.com/archives/C01SKUP7QR0/p1684776773511559) for about a week so adding another BZ member while I'm away to help keep the train moving! 🚂  Thanks @sonialiap!!!

**Comment by lschurr** [comment] 2023-05-23 22:19
I'll take this one back since I'm back from OOO. Thanks @dylanexpensify!

**Comment by neil-marcellini** [comment] 2023-05-24 16:02
2023-05-29

**Comment by lschurr** [comment] 2023-05-26 16:38
@sobitneupane - Can you apply for the job? https://www.upwork.com/jobs/~01ef0a0d267f7aff18

**Comment by lschurr** [comment] 2023-05-29 15:46
Offer sent @sobitneupane :)

**Comment by lschurr** [comment] 2023-05-29 16:32
Payment made. Do we need a regression test for this one @sobitneupane?

**Comment by sobitneupane** [comment] 2023-05-30 05:30
**Regression Test Proposal**

1. Set up a policy with a user and an admin
2. Send few messages from the user, and a message from the admin in the #announce room
3. As the user, verify you can delete your comment
4. As the user, verify you cannot delete the admin's comment
5. As the admin, verify you can delete the user's comment
6. As the admin, verify you can delete your own comment

Do we agree 👍 or 👎

**Comment by lschurr** [comment] 2023-05-30 18:44
Great, thanks @sobitneupane! Created GH for adding regression test. Closing this one out.

**Closed by lschurr** 2023-05-30 18:44 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
