### ISSUE TITLE
[$500] Reimbursement - Error when saving new rate after changing workspace currency offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36680] opened 2024-02-16 12:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go offline.
3. Go to workspace profile.
4. Click Currency and change to a different currency.
5. Go to Reimbursement > Track Distance click on Rate > Rate.
6. Change the rate and save it.
7. Go online.
8. Close the error message.
9. Refresh the page as indicated by the error message.
10. Change the rate and save it.

## Expected Result:
In Step 7, the new rate should be saved successfully.
In Step 10, user should be able to save the rate after refreshing the page as instructed by the error message.

## Actual Result:
In Step 7, error shows up after returning online. It fails to save the new rate.
In Step 10, user is unable to save the rate despite refreshing the page as instructed by the error message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/af0dd03b-ff9c-4d04-8af2-beee3d622c14

https://github.com/Expensify/App/assets/51066321/7fc05dbf-6fdf-42e9-a774-04756736ac3d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115e8d6360f0027ad</li>
        <li>Upwork Job ID: 1772534038298525696</li>
        <li>Last Price Increase: 2024-03-26</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-16 12:15
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors


We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by Christinadobrzyn** [comment] 2024-02-16 15:55
I can't reproduce this - I'm not getting an error on the web app or on the iOS app. Wave 5 seems right to me but I don't think this is happening anymore. Asking QA to test again!

**Comment by Christinadobrzyn** [comment] 2024-02-20 15:15
hi! Sorry I'm ooo sick today - I'll follow up on this tomorrow

**Comment by Christinadobrzyn** [comment] 2024-02-21 19:31
Hum, I'm still not getting this error when following the steps in the video or OP. https://expensify.slack.com/archives/C9YU7BX5M/p1708115199906519?thread_ts=1708113328.074849&cid=C9YU7BX5M

https://github.com/Expensify/App/assets/51066321/fd0ee88c-6fcc-49b7-9e3e-e3050e8af333

I'm going to close this as it can't be reproduced but feel free to reopen if you can reproduce

**Comment by lanitochka17** [comment] 2024-03-20 17:17
Issue is still reproducible on the last build 1.4.55-0


https://github.com/Expensify/App/assets/78819774/ecfe8c08-ff5b-407d-a83f-4fbd041b6f15

**Comment by Christinadobrzyn** [comment] 2024-03-21 03:53
I can't seem to set a different currency on a workspace and I'm not sure if that's a bug or if we've moved where you change a currency. 


https://github.com/Expensify/App/assets/51066321/f40ec03b-6bd6-4b50-8a58-13f7ad899bfb

**Comment by Christinadobrzyn** [comment] 2024-03-25 08:39
Sorry I need to test this again, I'll test tomorrow

**Comment by Christinadobrzyn** [comment] 2024-03-26 08:00
Ah okay, I can still reproduce this following the steps in the OP (I used my c.dobrzyn+2@expensicorp.com test email)

https://github.com/Expensify/App/assets/51066321/b59567dd-8d83-4c37-b566-0b0218ea7b7b

I'm not sure if this needs to be Internal - so going to start with External

**Comment by jayeshmangwani** [comment] 2024-03-27 09:09
@Christinadobrzyn Error is coming from the backend, it should be internal

After going from offline to online and refreshing the page , At the time of we call the `UpdateWorkspaceCustomUnitAndRate` again, it is sending the 666 error, I am attaching curl and the response below

<details>
  <summary>Curl:</summary>
  
  ```JavaScript 
  curl 'https://dev.new.expensify.com:8082/api/UpdateWorkspaceCustomUnitAndRate?' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryEusUyw4j8HbVVAqA' \
  -H 'Cookie: __utma=150204642.762912415.1671205453.1682347279.1682347279.1; mutiny.user.token=3387d46c-d6c1-4ec1-9681-932dc16fa002; initialReferer=https%3A%2F%2Fdev.new.expensify.com%3A8082%2F; browserGUID=65af657839907; _gcl_au=1.1.190817434.1707921383; onfido-web-sdk-analytics=abf36025-9918-4517-96fd-e34e1511a3f7; _ga_PNQ04Q4SFF=GS1.2.1708527106.3.1.1708527111.55.0.0; cf_clearance=adUrXQGIblb7hqzU39gvFZip7gSBvjnrcjoRH1yrBCc-1710958899-1.0.1.1-vf_h2B2qJ4bGtAcKB6g6w_RgnhgXyOT1TWk8CLO2YVSPX_qWVdT_lVREwCBOV0xmm1bgVaR_tEnbuwRdIV210Q; _ga=GA1.1.762912415.1671205453; _clck=1l60lse%7C2%7Cfk8%7C0%7C1408; _uetvid=affa30707f2a11ee825773bbcebf49a9; _ga_6BR2QJRCCD=GS1.1.1710962052.8.0.1710962411.60.0.0; _ce.s=v~daa9ba7b7e8788965dbfbeced001f92570390279~lcw~1710962411687~lva~1710958900705~vpv~0~v11.cs~429427~v11.s~092f3e00-e6ee-11ee-a2a6-efe9d6140086~v11.send~1710962052753~gtrk.la~lu06ue1y~v11.sla~1710962411688~lcw~1710962411688; _cfuvid=IAxySkkbFJa8Kh5n9Z.xIFlU5dA4OPtDHbvC.mxB0ps-1711523797989-0.0.1.1-604800000; __cf_bm=va2iZ1ijAwYccZDetu2oDVN9R8nZvRsrMqGdUOORv0g-1711529204-1.0.1.1-u9va9sRZp6c_LpdjJczn_3YKigyaX6D1IQsd1iqy3WbRuttvpZfI5swtVWSTsMa8bcw3vxv4TQg0PZqpDYAXQg' \
  -H 'Origin: https://dev.new.expensify.com:8082' \
  -H 'Referer: https://dev.new.expensify.com:8082/settings/workspaces/7703A1D2BFC35126/rateandunit' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw $'------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="policyID"\r\n\r\n7703A1D2BFC35126\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="lastModified"\r\n\r\n1711529843032023\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="customUnit"\r\n\r\n{"customUnitID":"506E40D25F124","name":"Distance","attributes":{"unit":"mi"},"rates":{"customUnitRateID":"7871B6AB2F50C","name":"Default Rate","rate":68,"currency":"INR","enabled":true,"attributes":[],"subRates":[],"7871B6AB2F50C":{"customUnitRateID":"7871B6AB2F50C","name":"Default Rate","rate":67,"currency":"INR","enabled":true,"attributes":[],"subRates":[]}}}\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="customUnitRate"\r\n\r\n{"customUnitRateID":"7871B6AB2F50C","name":"Default Rate","rate":68,"currency":"INR","enabled":true,"attributes":[],"subRates":[],"7871B6AB2F50C":{"customUnitRateID":"7871B6AB2F50C","name":"Default Rate","rate":67,"currency":"INR","enabled":true,"attributes":[],"subRates":[]}}\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="appversion"\r\n\r\n1.4.57-0\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="apiRequestType"\r\n\r\nwrite\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="pusherSocketID"\r\n\r\n686658.536239\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="shouldRetry"\r\n\r\ntrue\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="canCancel"\r\n\r\ntrue\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="authToken"\r\n\r\nDF6E0C5D7C91C17C1572B98728DB5C4DDF2961F7D3FE742901C5E91350A4CDA2EE6B519043E06AA23E7CBB23902C71A9706BF2A4130BE7EA8AD642CD179172466DA7AB7AADCF6B10260BF72EFC55BE3FD200D3E4F200552140C6A1313984C59B57DCE8F81C5024D6840288FDD2147F48A06F0C3632C0DA7B36A480870AEB2BCD7D7485963A22E1645CA83CD52EE1BA4BC0620FC97F48BEFEDC38F8356F2F82D5FD46A9915CD449BFDD2D961DFA102C293FC052FCFE5AB0583BE1FED83FB43DB43E6DAAC561885D0C31B3036BB2065020857E0A508AE353F7A96F0D6DA2E8ADF000069C1E750594900EF87EFA7FAC1624BF6115041559E0E7961D98712A830E26C9E4F84E6D0710C9947E1CF49100C84967BD38F8A304DDC4C712DF347F8D4AB65DBB43F00309D0D8176203F981FB31AD6E73571077B1EB1F4322CDE4F54C2F444895A10F95A37151E89591F0054EC975AC7B6878C39EDDA1BCBCA4C9EF190A69\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="referer"\r\n\r\necash\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="platform"\r\n\r\nweb\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="api_setCookie"\r\n\r\nfalse\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="email"\r\n\r\njm98289517+40@gmail.com\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA\r\nContent-Disposition: form-data; name="isFromDevEnv"\r\n\r\ntrue\r\n------WebKitFormBoundaryEusUyw4j8HbVVAqA--\r\n'
```
</details>




<details>
  <summary>Response:</summary>
  
```javascript
{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Libs\\Error\\ExpError",
    "UUID": "07EDA082-1E6D-4B4C-896E-A8B2E2819BAC",
    "message": "Invalid data set in newValue",
    "title": "",
    "data": {
        "onyxData": [
            {
                "onyxMethod": "merge",
                "key": "policy_7703A1D2BFC35126",
                "value": {
                    "customUnits": {
                        "506E40D25F124": {
                            "rates": {
                                "7871B6AB2F50C": {
                                    "errors": {
                                        "1711529985857470": "Invalid data set in newValue"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            {
                "onyxMethod": "merge",
                "key": "policy_7703A1D2BFC35126",
                "value": {
                    "lastModified": 1711529843032023,
                    "customUnits": {
                        "506E40D25F124": {
                            "rates": {
                                "7871B6AB2F50C": {}
                            }
                        }
                    }
                }
            }
        ]
    },
    "htmlMessage": "",
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "policy_7703A1D2BFC35126",
            "value": {
                "customUnits": {
                    "506E40D25F124": {
                        "rates": {
                            "7871B6AB2F50C": {
                                "errors": {
                                    "1711529985857470": "Invalid data set in newValue"
                                }
                            }
                        }
                    }
                }
            }
        },
        {
            "onyxMethod": "merge",
            "key": "policy_7703A1D2BFC35126",
            "value": {
                "lastModified": 1711529843032023,
                "customUnits": {
                    "506E40D25F124": {
                        "rates": {
                            "7871B6AB2F50C": {}
                        }
                    }
                }
            }
        }
    ],
    "requestID": "86ae2faa8a588558-BOM"
}


```

</details>

**Comment by Christinadobrzyn** [comment] 2024-03-28 06:44
Thanks for checking @jayeshmangwani - I updated the labels for an internal engineer to grab

Just a heads up that I'm going to be ooo on Friday and Monday for Easter. I'll check in on this on Tuesday when I'm back.

**Comment by Christinadobrzyn** [comment] 2024-04-02 07:48
This might be related to - https://github.com/Expensify/App/issues/38928

**Comment by Christinadobrzyn** [comment] 2024-04-03 04:03
^ Not related to https://github.com/Expensify/App/issues/38928 

I think this still needs to be worked on so gonna ask for a volunteer - https://expensify.slack.com/archives/C066HJM2CAZ/p1712117001415409

**Comment by Christinadobrzyn** [comment] 2024-04-04 02:04
Based on this [discussion](https://expensify.slack.com/archives/C066HJM2CAZ/p1712117001415409), distance rate page will be gone soon. 

Closing this without action.

**Closed by Christinadobrzyn** 2024-04-04 02:04 UTC
Labels: Daily, Internal, Help Wanted, Bug, Hot Pick
