### ISSUE TITLE
[$500] Web - Video - play speed after returning from thread does not update 

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37722] opened 2024-03-05 09:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:

1. Go to staging.new.expensify.com
2. Go to any chat.
3. Send a video.
4. Send a reply to the video.
5. Send a reply to the reply in the video in Step 3.
6. In thread, play the video.
7. Click outside the video to return to the previous thread.
8. Click 3-dot menu > Playback speed.
9. We can hear the sound from previous chat
10. Change the speed or volume
11. Observe that playback speed or volume does not update

## Expected Result:

Step 9: We should not hear the sound from previous chat
Step 11: Playback speed or volume should update

## Actual Result:

Step 9: We can hear the sound from previous chat
Step 11: Playback speed or volume does not updated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/2ee0bf30-3edf-4285-9e25-f519bdafc6a1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fabf464f1c4f13cc</li>
        <li>Upwork Job ID: 1768354460890284032</li>
        <li>Last Price Increase: 2024-03-14</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
<li>tienifr | Contributor | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-05 09:52
@MitchExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by CristiCeban** [comment] 2024-03-05 12:31
## Proposal
 ### Please re-state the problem that we are trying to solve in this issue.
 Web - Video - App crashes when changing play speed after returning from thread

 ### What is the root cause of that problem?
When returning from the tread and changing the playback speed of the video `currentVideoPlayerRef.current.setStatusAsync({rate: speed});` cause crash because `currentVideoPlayerRef` is null there.

https://github.com/Expensify/App/blob/9411a08168d53df44a957fd8bb86fd9a363b25b4/src/components/VideoPlayerContexts/VideoPopoverMenuContext.js#L21-L27
This is because videoRef comes from `PlaybackContext` here https://github.com/Expensify/App/blob/9411a08168d53df44a957fd8bb86fd9a363b25b4/src/components/VideoPlayerContexts/PlaybackContext.js#L105
When returning from the threads, it resets in this useEffect
https://github.com/Expensify/App/blob/9411a08168d53df44a957fd8bb86fd9a363b25b4/src/components/VideoPlayerContexts/PlaybackContext.js#L92-L97
and basically resets the player ref in this function https://github.com/Expensify/App/blob/9411a08168d53df44a957fd8bb86fd9a363b25b4/src/components/VideoPlayerContexts/PlaybackContext.js#L83-L90
thus, the running video has no valid ref and trying to call functions on it, crashes the app
 ### What changes do you think we should make in order to solve the problem?
In the initial chat and in the other chat thread the `currentReportID` is different.
https://github.com/Expensify/App/blob/9411a08168d53df44a957fd8bb86fd9a363b25b4/src/components/VideoPlayerContexts/PlaybackContext.js#L92-L97
I don't see the point of resetting it when it is valid, only when it is null.
So I propose to change it to 
```ts
 useEffect(() => {
        if (currentReportID) {
            return;
        }
        resetVideoPlayerData();
    }, [currentReportID, resetVideoPlayerData]);
```

## Before

https://github.com/Expensify/App/assets/58264709/dfdfbf9b-6f0a-47fc-9ef6-1b99190b28c6


## After

https://github.com/Expensify/App/assets/58264709/b005b3f7-3869-44f3-a0b9-b2d10ce5ea95

**Comment by MitchExpensify** [comment] 2024-03-08 18:58
Reproduced:

<img width="829" alt="image" src="https://github.com/Expensify/App/assets/36425901/821f3e6f-9f9a-44ea-84f1-b306c51d4681">

**Comment by MitchExpensify** [comment] 2024-03-08 19:05
Wave 9 worthy I think

**Comment by bernhardoj** [comment] 2024-03-15 16:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the original OP, the app crashes when changing the video playback speed after opening the thread parent. Now, the ap doesn't crash, but the playback speed button doesn't work at all including the other video controls button (play, full screen, volume)

### What is the root cause of that problem?
If we start playing a video, it will set the `currentlyPlayingURL` context to the video URL (A_url) and set the video player ref from this `useEffect` (`url` is now equal to `currentlyPlayingURL` context).
https://github.com/Expensify/App/blob/8b54aff5c1c711121479d819e092c6bca7f2f5b1/src/components/VideoPlayer/BaseVideoPlayer.js#L176-L181

`currentlyPlayingURL` = A_url
video player ref = A_video_ref

When we press the thread parent message, it will navigate to the thread parent and mount a new report screen and also the video player which triggers the above `useEffect` again. 

We have a logic to reset the video player data, including the `currentlyPlayingURL` and the ref every time we navigate to another report.
https://github.com/Expensify/App/blob/8b54aff5c1c711121479d819e092c6bca7f2f5b1/src/components/VideoPlayerContexts/PlaybackContext.tsx#L80-L85

However, the current report ID value is updated with a delay.
https://github.com/Expensify/App/blob/8b54aff5c1c711121479d819e092c6bca7f2f5b1/src/libs/Navigation/NavigationRoot.tsx#L120-L122

When the video player is mounted, the `currentlyPlayingURL` still contains the previous video URL (A_url) and it's actually the same as the current video `url` (A_url), so the `shareVideoPlayerElements` is called and the video is auto played.

After the current report ID is updated, the video player data is cleared.
`currentlyPlayingURL` = null
video player ref = null

So, every time we try to update the playback speed, it does nothing because the video player ref now is null.

### What changes do you think we should make in order to solve the problem?

If the `resetVideoPlayerData` is called earlier before the video player is mounted, then the thread parent video won't be auto played. If the video isn't auto played, then the user need to press the play button which will set the correct video player ref and we won't have the issue of null ref.

I believe we still want to delay the update of the current report ID (if not, then we can remove the delay), so I'm proposing to manually handle the current report ID in PlaybackContext instead of using the `useCurrentReportID` hook.

```
const [currentReportID, setCurrentReportID] = useState('');

useEffect(() => {
    const listener = navigationRef.addListener('state', () => setCurrentReportID(Navigation.getTopmostReportId(navigationRef.getRootState()) ?? ''));
    return navigationRef.removeListener('state', listener);
}, [])
```

**Comment by bernhardoj** [comment] 2024-03-15 16:55
The app doesn't crash anymore, but the root cause isn't fixed yet as shown in the video below. The playback speed button, volume, and download doesn't have any effect.

https://github.com/Expensify/App/assets/50919443/37ebe1e6-35a0-455c-a7e4-545559ccdbfc

**Comment by MitchExpensify** [comment] 2024-03-20 03:14
Thanks @dukenv0307 !

**Comment by Skalakid** [comment] 2024-03-21 08:28
@bernhardoj You're right. I'm also not a fan of removing this logic.

> The app doesn't crash anymore, but the root cause isn't fixed yet as shown in the video below. The playback speed button, volume, and download doesn't have any effect.

This problem is fixed in my PR: https://github.com/Expensify/App/pull/38407

**Comment by bernhardoj** [comment] 2024-03-22 03:43
> I think @tienifr didn't remove this logic totally,

He mentioned it in point 1. 

> resetVideoPlayerData when BaseVideoPlayer is unmounted.

Also, this won't solve our issue.

> BTW, we should hold this issue until https://github.com/Expensify/App/pull/38407 is merged.

Yes, let's hold for that.

**Comment by MitchExpensify** [comment] 2024-03-25 23:08
Not overdue, held on https://github.com/Expensify/App/pull/38407 merging

**Comment by jasperhuangg** [comment] 2024-03-26 23:42
Let's go ahead and assign both @tienifr @bernhardoj and pay them out together!

**Comment by bernhardoj** [comment] 2024-03-27 02:25
@jasperhuangg I think we're still holding on https://github.com/Expensify/App/pull/38407

_and @tienifr solution will create a regression_

**Comment by MitchExpensify** [comment] 2024-04-01 19:40
https://github.com/Expensify/App/pull/38407 is on staging, let's retest this

**Comment by MitchExpensify** [comment] 2024-04-01 19:51
I'm unable to reproduce in fresh tests

**Comment by bernhardoj** [comment] 2024-04-02 05:47
@MitchExpensify the crash doesn't happen anymore, but the video player control is broken as pointed out in my previous comment [here](https://github.com/Expensify/App/issues/37722#issuecomment-2000067732). So, we should still fix the root cause here.

@dukenv0307 @jasperhuangg Just for confirmation, are we good to go with my solution?

**Comment by bernhardoj** [comment] 2024-04-03 04:30
@dukenv0307 I don't know what has changed, but the `stopAsync` function is always undefined, even when we first play the video.
https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/components/VideoPlayerContexts/PlaybackContext.tsx#L22-L23

We can change it to its equivalent:
```
currentVideoPlayerRef.current?.setStatusAsync?.({ shouldPlay: false, positionMillis: 0 });
```

cc: @Skalakid

**Comment by Skalakid** [comment] 2024-04-03 07:30
@bernhardoj Are video controls still broken? I can't reproduce this. What exactly we are fixing right now?

**Comment by bernhardoj** [comment] 2024-04-03 07:41
@Skalakid Yes, that's the issue that we are trying to fix.

https://github.com/Expensify/App/assets/50919443/08e94973-c575-45a0-a7d5-6580dde01f68

Notice that the volume and playback speed has no effect. I need to press pause twice before it works normal again.

**Comment by Skalakid** [comment] 2024-04-03 07:56
Shouldn't we create separate issue for this?

**Comment by MitchExpensify** [comment] 2024-04-06 21:20
[Nice](https://github.com/Expensify/App/issues/37722#issuecomment-2036129814), updated!

**Comment by bernhardoj** [comment] 2024-04-10 12:26
Updated my [proposal](https://github.com/Expensify/App/issues/37722#issuecomment-2000049459)

**Comment by bernhardoj** [comment] 2024-04-15 09:55
@dukenv0307 I don't remember encountering that problem when I was testing my solution, but I have posted a new [solution](https://github.com/Expensify/App/issues/37722#issuecomment-2000049459) that is more reliable.

**Comment by jasperhuangg** [comment] 2024-05-09 20:13
Looks like the fix for this was deployed 2 weeks ago, it seems the automation failed.

**Comment by jasperhuangg** [comment] 2024-05-09 20:14
@MitchExpensify I believe we need to pay out @bernhardoj for their PR solution and @dukenv0307 for the review

**Comment by MitchExpensify** [comment] 2024-05-12 01:46
*Payment summary:*

$500 C @bernhardoj (Upwork)
$500 C+ @dukenv0307 (Upwork)

**Comment by MitchExpensify** [comment] 2024-05-12 01:51
I wonder if

**Closed by MitchExpensify** 2024-05-12 01:51 UTC
Labels: Reviewing, External, Monthly, Awaiting Payment, Bug
