### ISSUE TITLE
Self DM - Self DM does not show up on new Expensifail accounts

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46055] opened 2024-07-23 17:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Sign in with a new Expensifail account
3. Wait for self DM to show up after login

## Expected Result:
Self DM will show up on LHN

## Actual Result:
Self DM does not show up on LHN
On production, it shows up after a while

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/519ed2c4-6f86-4897-bc1b-82e9e4824bc7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-23 17:06
We think that this bug might be related to #vip-vsp

**Comment by jasperhuangg** [comment] 2024-07-23 17:20
Hmmm I can't reproduce this with a regular fresh account. My hunch is that it has something to do with the enormous expensifail domain.

**Comment by thienlnam** [comment] 2024-07-23 17:51
This Is known and not a blocker - this should be resolved with this issue https://github.com/Expensify/Expensify/issues/395534

**Comment by jasperhuangg** [comment] 2024-07-25 21:58
I'm gonna close this out in favor of https://github.com/Expensify/Expensify/issues/395534

**Closed by jasperhuangg** 2024-07-25 21:58 UTC
Labels: Engineering, Daily, Internal, Overdue
