### ISSUE TITLE
[$500]  Expense - System message for paid expense shows payer, while the copied content is workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33819] opened 2024-01-01 18:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [Member] Request money in workspace chat
2. [Admin] Pay the request
3. [Member] Click on the expense preview to go to expense report
4. [Member] Right click on the paid system message > Copy to clipboard
5. [Member] Paste the content
Note that

## Expected Result:
1. The system message should always start with the action, not the actor, regardless of who is viewing the chat. So the system message should read `paid $10` rather than `John paid $10` or `John's Workspace paid $10`.
2. When a user copies a system message, we should copy only what is printed, rather than adding the actor (so we should copy `paid $10` instead of copying `John Doe paid $10`)

## Actual Result:
1. Depending on who is viewing the report, the system message shows either `paid amount elsewhere` or `[admin] paid amount elsewhere`.
2. When the user copies and pastes the system message, it shows something different from what was printed originally (it shows `[Workspace name] paid amount elsewhere`.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5e7957cd-b471-49d5-be0c-4a263da2187f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015bfbfa9935f7c034</li>
        <li>Upwork Job ID: 1741887749877055488</li>
        <li>Last Price Increase: 2024-01-22</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 28147572</li>
<li>dukenv0307 | Contributor | 28147573</li>
</ul></li>
    </ul>
</details>

**Comment by rrrshtt** [comment] 2024-01-01 18:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clipboard information is different from what you see in chat after the expense paid action.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/fe49e4f7fb9677a5834b53cb776f79fb20f893ce/src/libs/ReportUtils.ts#L4106
https://github.com/Expensify/App/blob/fe49e4f7fb9677a5834b53cb776f79fb20f893ce/src/libs/ReportUtils.ts#L2011
As you can see, in these two lines, we choose payerName for information in clipboard. If it's an Expense report, we consider showing the Policy name instead of the actual user name.

### What changes do you think we should make in order to solve the problem?
We need to specify more precisely the information that should be labeled as "Policy Name" (I don't know the exact product requirements).

### What alternative solutions did you explore? (Optional)
Alternatively, we can simply log the content as is here.
https://github.com/Expensify/App/blob/fe49e4f7fb9677a5834b53cb776f79fb20f893ce/src/pages/home/report/ContextMenu/ContextMenuActions.js#L268-L299

**Comment by sakluger** [comment] 2024-01-02 22:06
Something is definitely wrong here, but I'm not sure what the expected behavior is. Should the system message show the admin's name, the workspace's name, or neither? I'm confident that the system message should NOT show the admin's name, but I'm not sure which of the other two it should show.

I asked for the team's feedback in Slack: https://expensify.slack.com/archives/C02MW39LT9N/p1704233160288869

**Comment by aim-salam** [comment] 2024-01-03 04:12
.

**Comment by sakluger** [comment] 2024-01-04 21:13
I updated the expected behavior and actual behavior. Expected result is now:

1. The system message should always start with the action, not the actor, regardless of who is viewing the chat. So the system message should read paid $10 rather than John paid $10 or John's Workspace paid $10.
2. When a user copies a system message, we should copy only what is printed, rather than adding the actor (so we should copy paid $10 instead of copying John Doe paid $10)

@rrrshtt @gijoe0295 @dukenv0307 would you like to update your proposal based on the new expected result?

**Comment by rrrshtt** [comment] 2024-01-04 22:57
## Proposal
[Updated](https://github.com/Expensify/App/issues/33819#issuecomment-1873439026)

**Comment by sakluger** [comment] 2024-01-05 20:16
@0xmiroslav hopefully one of the above proposals does the trick! Mind taking a look when you hae a chance?

**Comment by sakluger** [comment] 2024-01-10 23:08
@0xmiroslav friendly bump.

**Comment by sakluger** [comment] 2024-01-19 19:20
Oh good question. I think the answer is yes, but I'm going to double check in Slack.

**Comment by sakluger** [comment] 2024-01-23 23:55
Sorry, still discussing expected LHN behavior in Slack.

**Comment by mallenexpensify** [comment] 2024-01-24 03:37
@DylanDylann reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by DylanDylann** [comment] 2024-01-25 09:59
Daily update: We are waiting for @sakluger to give the final expected

**Comment by DylanDylann** [comment] 2024-01-29 08:13
Waiting response from @sakluger

**Comment by trjExpensify** [comment] 2024-01-30 22:58
Regarding [this final question](https://github.com/Expensify/App/issues/33819#issuecomment-1895213368). 

>payer name should be removed in LHN for ReportPreview as well? (this is workspace chat, not expense report)

**Workspace Chat**
LHN Preview: 
>%workspaceName% paid $100.00 

I.e this the name of the report being previewed. If you click the preview component in the workspace chat, you'll also see the title "%workspaceName paid $100.00%" in the header. 

**Expense Report**
LHN Preview:
>%payerName%: paid $100.00 [using Expensify || elsewhere]

I.e this is the reportAction on the report from the payer that's being previewed. If you click the expense report, you would see this reportAction system message in the comments: 

**Tom Rhys Jones 22:57pm** 
paid $100.00 using Expensify

**Comment by sakluger** [comment] 2024-01-31 20:00
Commenting for Melvin since we're still honing in on the expected behavior.

**Comment by trjExpensify** [comment] 2024-02-01 11:55
>1. LHN for report preview is displaying as %workspaceName% paid $100.00 [using Expensify || elsewhere] now. We should remove payType in LHN, right?

Corrrect. There should be no payType in the LHN preview of an expense report in the workspace chat. Like there isn't in the header of the report being previewed either.

I.e 

>Duraflame paid $100.00

2. For the Expense report, we will remove %payerName% in both LHN and report action or still keeping it?

The LHN preview of the paid reportAction is prefixed with `payerName:` as that's who the message being previewed is from.

>LHN Preview:
>%payerName%: paid $100.00 [using Expensify || elsewhere]

I.e 

>Tom: paid $100.00 using Expensify

The report action on the expense itself does not "double up" on the payerName. The message comes from the payer already. 

Correct: 

>Tom Rhys Jones 22:57pm
>paid $100.00 using Expensify

Incorrect: 

>Tom Rhys Jones 22:57pm
>Tom Rhys Jones paid $100.00 using Expensify

**Comment by sakluger** [comment] 2024-02-05 23:07
@trjExpensify thanks for helping to clarify the expected behavior, I appreciate it 🙇 .

@DylanDylann do you think that @dukenv0307's updated proposal is correct and complete?

**Comment by DylanDylann** [comment] 2024-02-06 17:29
Reviewing. I will give a update today

**Comment by DylanDylann** [comment] 2024-02-07 04:04
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/33819#issuecomment-1873807257) looks good to me 

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-02-15 08:36
@trjExpensify Currently, I see that in some cases the preview message and the message from the "Copy to clipboard" button are different. 

https://github.com/Expensify/App/assets/141406735/c0a50c7c-7c17-4002-824a-3c74488ba794

In the above video:
- Preview message in LHN: Scan in progress…
- The message from "Copy to clipboard": requested ₫0

Is this expected? What do you think about displaying The message from "Copy to clipboard" similar to Preview message in LHN

cc @dukenv0307 @srikarparsi

**Comment by trjExpensify** [comment] 2024-02-15 14:10
>What do you think about displaying The message from "Copy to clipboard" similar to Preview message in LHN

Yeah, I think generally what you copy should be what you see, so let's copy the message being previewed. 

P.s why does the receipt thumbnail appear to zoom like that, man? 😂 👀

**Comment by flodnv** [comment] 2024-02-20 18:20
We are reverting the PR: https://github.com/Expensify/App/pull/36932

I think a few considerations were missed as part of the planning of this ~feature request~ bug.

**Comment by srikarparsi** [comment] 2024-02-21 05:31
Left a comment [here](https://github.com/Expensify/App/pull/36993)

**Comment by DylanDylann** [comment] 2024-03-11 03:00
@sakluger The PR was deployed to production 2 weeks ago. Please help to process the next step

**Comment by DylanDylann** [comment] 2024-03-14 09:55
@sakluger Bump this comment

cc @srikarparsi

**Comment by sakluger** [comment] 2024-03-18 17:36
Sorry! All paid out now.

**Closed by sakluger** 2024-03-18 17:36 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
