### ISSUE TITLE
[$500] Web - Search – Secondary log doesn’t add immediately in NewDot account.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30834] opened 2023-11-03 11:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.95-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Log into NewDot with any account.
2. Log into OldDot with the same account and add a Secondary Login from Account Settings.
3. Verify the Secondary login has been validated.
4. Log in to NewDot with the same account that already has a validated secondary login.
5. Navigate – Settings/ Profile/ Contact methods.

## Expected Result:
Account has a secondary login in NewDot.

## Actual Result:
Secondary log doesn’t add immediately in NewDot account. It shows up only after relogin.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/cfc96bff-60f7-4565-bc4b-a12c53426489

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1bfd5f6d6337d88</li>
        <li>Upwork Job ID: 1720404994271817728</li>
        <li>Last Price Increase: 2023-11-03</li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-11-04 19:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Login list is not updated after refresh and only gets updated after a logout/login

### What is the root cause of that problem?
After the user login, the updated logins list is received in the `OpenApp` response. And it's only updated when an action like Add Contact method is manually done by the user. 

### What changes do you think we should make in order to solve the problem?
There should be an extra API endpoint for fetching the User logins list. That we would call when mounting `ContactMethodsPage` 

We would add the API call to `src/libs/actions/User.js`

```js
function openContactMethodsPage() {
    API.read('OpenContactMethodsPage');
}
```

And use it as such 

```js
    useEffect(() => {
        openContactMethodsPage()
    }, [])
```
### What alternative solutions did you explore? (Optional)

N/A

**Comment by trjExpensify** [comment] 2023-11-06 10:24
@twisterdotcom @zanyrenney @Beamanator @cristipaval since the introduction of this feature has this worked immediately? I feel like it might have the same root cause as we've discussed in [this issue](https://github.com/Expensify/App/issues/23873#issuecomment-1695329817) where a member's private personal details aren't returned in OpenApp? CC: @grgia

**Comment by cristipaval** [comment] 2023-11-06 11:49
I don't think this worked immediately. It seems that the backend doesn't send Pusher updates to NewDot in this case, when the secondary login is added in OldDot. By fixing [this issue](https://github.com/Expensify/App/issues/23873#issuecomment-1695329817), we will get the login list updated always when we resume the session in NewDot. But there's still a corner case which I'm not sure it's worth a lot to get fixed: if the NewDot App is foregrounded and the user adds a secondary login in OldDot, the secondary login won't be instantly added in NewDot, it will appear when the user moves out of the App and comes back.

**Comment by trjExpensify** [comment] 2023-11-06 12:06
>But there's still a corner case which I'm not sure it's worth a lot to get fixed: if the NewDot App is foregrounded and the user adds a secondary login in OldDot, the secondary login won't be instantly added in NewDot, it will appear when the user moves out of the App and comes back.

What do we do with other personal settings like updating your name, avatar and timezone?

**Comment by cristipaval** [comment] 2023-11-06 15:57
I totally agree with the above 👍

**Comment by trjExpensify** [comment] 2023-11-06 23:22
Cool, so I'm going to close this out then. Thanks!

**Closed by trjExpensify** 2023-11-06 23:22 UTC
Labels: External, Daily, Help Wanted, Bug
