### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] IOS - Contact Method - keyboard open again for a second when user click on remove button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20608] opened 2023-06-12 17:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go to settings > profile > contact method
2. Click on new contact method
3. Enter any email and click on Add
4. Click on email
5. Open the keyboard if it's not open
5. click on remove button and confirm button

## Expected Result:
 Should not show keyboard after navigates to contact methods screen

## Actual Result:
Show keyboard  for second after navigates to contact methods screen

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** yes

**Reproducible in production?:**yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c44035c2-c396-4995-bbda-fc1a593b9996

https://github.com/Expensify/App/assets/93399543/a1668af9-1474-4c00-ad51-8d88f48ec874

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686204508100569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce16ce28c89bd17e</li>
        <li>Upwork Job ID: 1668503706674507776</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-06-13 06:20
Reproduced on iPhone 13 with iOS 16.5, app version 1.3.26-4.

https://github.com/Expensify/App/assets/59587260/a34c5783-ec6f-4b4d-99c1-f2c1420abaa3

**Comment by esh-g** [comment] 2023-06-13 07:50
# Proposal

## Please Re-state that problem
 keyboard opens again for a second when user click on remove button in contact method details page.
 
 ## What is the root cause of that problem?
 We are not dismissing the keyboard when the delete confirm modal opens. It just gets hidden due to the modal but after modal closes, it re-appears on the other screen.
 
 ## What changes do you think we should make in order to solve the problem?
 We should add `onModalWilHide` `prop` to `ConfirmModal` and `BaseModal` which will pass to `ReactNativeModal`.
 This prop will help us schedule a callback just before the modal hides to dismiss the keyboard by calling `Keyboard.dismiss()`
 
 1. In `ContactMethodDetailsPage.js`
<img width="791" alt="Screenshot 2023-06-13 at 1 11 59 PM" src="https://github.com/Expensify/App/assets/77237602/27e1ae7e-423e-4232-b2ba-f5bd27f4392e">

2. In `ConfirmModal.js`
<img width="791" alt="Screenshot 2023-06-13 at 1 12 15 PM" src="https://github.com/Expensify/App/assets/77237602/ad7016b1-2f2c-429c-a46d-ad0fb5ee3c9f">

3. In `BaseModal.js`
<img width="791" alt="Screenshot 2023-06-13 at 1 12 40 PM" src="https://github.com/Expensify/App/assets/77237602/cda8d27b-a72a-41e6-a49c-d49fa8390a81">

4. We also have to import the `Keyboard` module from `react-native` in `ContactMethodDetailsPage.js`


I have chosen this approach as the best because if we try to hide the keyboard before navigating, it just doesn't work because it takes some time to hide the keyboard. Also, we cannot hide it `onModalHide` for the same reason therefore we have to use `onModalWillHide` at least in my testing. Moreover, I tried dismissing keyboard in the `toggleDeleteModal()` method but that causes the modal not to open again if we cancel the delete modal.


https://github.com/Expensify/App/assets/77237602/da395b0a-eea5-425d-9e12-8f8bca924ed6

**Comment by esh-g** [comment] 2023-06-13 07:56
@hungvu193 Your proposal is incorrect because when the remove button is clicked, the `confirmDeleteAndHideModal` method is executed
https://github.com/Expensify/App/blob/93957f0eb66a7e6998365b201a4c54ea2029ff60/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L185-L188

And the navigation to the previous page happens due to calling `User.deleteContactMethod` not in `componentDidUpdate`
https://github.com/Expensify/App/blob/93957f0eb66a7e6998365b201a4c54ea2029ff60/src/libs/actions/User.js#L285

And after testing, I can say that your solution has no effect on the problem.

https://github.com/Expensify/App/assets/77237602/d46f97b1-d028-460e-b222-8158ed977ab2

**Comment by esh-g** [comment] 2023-06-13 13:51
@tienifr Are you testing on a real device or simulator and if simulator then have you enabled keyboard with cmd + shift + k or just press cmd + k to bring it up every time?

**Comment by idevz1** [comment] 2023-06-13 18:29
Hello. Please check the screen recording and advise. My framerate on the iOS simulator is low but I've showcased my solution with slow animations and normal as well. 

https://github.com/Expensify/App/assets/8914024/b4f2b2c3-f982-47f1-a6e0-ef92c7298062

After dismissing the modal, the keyboard shows back on the ContactMethodDetailsPage and then is animated out rather than showing up directly after the navigation animation is finished and on the Contact methods page.

# Proposal

## What changes do you think we should make in order to solve the problem?

1. In `ContactMethodDetailsPage.js` add 
```
const dismissKeyboard = () => {
    return new Promise((resolve, reject) => {
      const frameListener = Keyboard.addListener('keyboardWillChangeFrame', () => {
        frameListener.remove();
        didListener.remove();
        resolve();
      });
  
      const didListener = Keyboard.addListener('keyboardDidHide', () => {
        frameListener.remove();
        didListener.remove();
        resolve();
      });
  
      Keyboard.dismiss();
    });
  };
```


2. In `confirmDeleteAndHideModal()` add: 
```
this.toggleDeleteModal(false); // Hide the modal

dismissKeyboard().then(() => {
User.deleteContactMethod(this.getContactMethod(), this.props.loginList);
}
```

**Comment by idevz1** [comment] 2023-06-13 18:33
Contributor details
Your Expensify account email: cgeorge.ciobanu@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b69087c3abab2836

**Comment by Santhosh-Sellavel** [comment] 2023-06-13 22:04
@sophiepintoraetz @cead22 Can you assign a new C+ here, there are multiple proposals. And I will not be able to get this soon.

**Comment by kadiealexander** [comment] 2023-06-16 05:20
Not overdue, @fedirjh please check out the proposals above!

**Comment by idevz1** [comment] 2023-06-16 13:41
> @idevz1 your solution didn’t worked for me. Also from your screenshots, it seems you broke something, the contact was not removed.

Could you screen record my solution as well to see how it acts in your case? In my recordings I commented out the API call as I didn't want to send too many requests whilst testing and eventually get timed out by the server, so nothing was really broken.

**Comment by idevz1** [comment] 2023-06-16 22:22
@fedirjh Thank you for providing the screen recording. I noticed a couple of differences in your code vs my proposal. 
1. In your version you edited the `deleteContactMethod()` whilst I edited `confirmDeleteAndHideModal()`
2. The order of the calls is reversed in your code. I call `this.toggleDeleteModal(false);` first

So just to confirm, I did no modifications to `deleteContactMethod()` and my `confirmDeleteAndHideModal()` looks like this: 

```
 confirmDeleteAndHideModal() {
        this.toggleDeleteModal(false);
        dismissKeyboard().then(() => {
            User.deleteContactMethod(this.getContactMethod(), this.props.loginList);
        });
    }
```

**Comment by sophiepintoraetz** [comment] 2023-06-21 02:00
we have proposals, @fedirjh is doing a good job of refining them so i don't think we need to adjust the bounty here.

**Comment by sophiepintoraetz** [comment] 2023-06-22 06:03
@fedirjh - can we get a contributor assigned before the week is out? 🙏

**Comment by kadiealexander** [comment] 2023-06-27 04:10
Dipping out of this one since you've got it covered Sophie, let me know if you need any help!

**Comment by sophiepintoraetz** [comment] 2023-06-29 01:24
@fedirjh thank you for your work on reviewing the proposals so far! Can we get one assigned?

**Comment by sophiepintoraetz** [comment] 2023-07-18 22:24
@Nodebrute - appreciate some patience here - I've been OOO travelling. Additionally, the offer is in your inbox so you can help speed things along by requesting payment on that offer, rather than waiting on me - thanks!

**Comment by sophiepintoraetz** [comment] 2023-07-18 22:42
@fedirjh - I'll release payment once you go through the [PR checklist](https://github.com/Expensify/App/issues/20608#issuecomment-1629880015) 🙏 
@Nodebrute - payment released with timeline bonus.

**Comment by sophiepintoraetz** [comment] 2023-07-24 04:15
Bumping @fedirjh

**Comment by sophiepintoraetz** [comment] 2023-07-26 22:44
Payouts due:

Issue Reporter: $250 @gadhiyamanan - PAID
Contributor: $1500 @Nodebrute - PAID
Contributor+: $1500 @fedirjh - to request via NewDot

Eligible for 50% #urgency bonus? Y

**Comment by sophiepintoraetz** [comment] 2023-07-26 22:51
Test https://github.com/Expensify/Expensify/issues/303405

**Closed by sophiepintoraetz** 2023-07-26 22:51 UTC
Labels: External, Daily, Awaiting Payment, Bug
