### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Android - Error attempting to download an attachment

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25491] opened 2023-08-18 14:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a random report and send an attachment (image, video, etc).
2. If it's an image, click on the image, and when the image opens in full view, click on the download button. If it's a video or a different type of attachment, directly click the download button.
3. Observe the error, and the attachment doesn't download.

## Expected Result:
The attachment downloads successfully to the device without an error.

## Actual Result:
An error appears, and the attachment does not get downloaded to device.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856 

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/a807a33e-08c6-43ab-ba13-12a97ac5bba5

https://github.com/Expensify/App/assets/115492554/0b03a8dc-2777-46d2-9d32-118275e6ee1f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @NajiNazzal

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691506774751679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ea72aefb3af1826d</li>
        <li>Upwork Job ID: 1692654340381872128</li>
        <li>Last Price Increase: 2023-08-18</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26261011</li>
</ul></li>
    </ul>
</details>

**Comment by garrettmknight** [comment] 2023-08-18 21:46
Confirmed in browserstack

**Comment by burczu** [comment] 2023-08-21 07:49
not overdue - I'm reviewing proposals right now

**Comment by burczu** [comment] 2023-08-21 10:21
I wasn't able to reproduce this issue - I've tried Pixel 5 with Android 11 and Pixel 6 Pro with Android 12 (both emulators). On what devices did you test it?

**Comment by izarutskaya** [comment] 2023-08-21 10:45
@burczu I used Samsung M 52/ Android 13 and it's still reproducible for me

https://github.com/Expensify/App/assets/115492554/b97b9574-fd18-432c-aa52-53817637b5fd

**Comment by AmjedNazzal** [comment] 2023-08-21 10:49
@burczu I think it happens on samsung phones which you can't emulate on andriod studio

**Comment by burczu** [comment] 2023-08-21 10:49
Thanks @izarutskaya and @rayane-djouah - I'll give your configs a try.

**Comment by burczu** [comment] 2023-08-21 11:04
Ok, I was able to reproduce it with Pixel 3a with Android API 34, Android 14 as @rayane-djouah suggested. I'll try with Android 13 too, to dispel @AmjedNazzal doubts. Thanks

**Comment by burczu** [comment] 2023-08-21 12:02
Hmm... @AmjedNazzal was right here - it is not reproducible on Pixel 3a with Android 13 🤔 I've also tried on Galaxy Nexus with Android 13 which is available in Android Studio and it is also not reproducible...

@garrettmknight I've wrote that you've confirmed it on BrowserStack - on what device and with which Android?

**Comment by AmjedNazzal** [comment] 2023-08-21 15:27
@burczu I don't think the galaxy nexus would be helpful here. If I'm to guess, the issue is probably occurring because of samsung one ui since it's involved in apps interactions with the native system. We should probably run and test dev on physical samsung phones.

**Comment by garrettmknight** [comment] 2023-08-21 17:32
Tested on a Galaxy S22 v12.0 in browserstack.
<img width="441" alt="Screenshot 2023-08-21 at 11 31 33 AM" src="https://github.com/Expensify/App/assets/1529980/d905b866-3874-41d7-b9c9-021b7e8b986e">

**Comment by burczu** [comment] 2023-08-22 11:06
@aimane-chnaif Yes, thank you - I think your help will be invaluable here. Would you like to just take it over from me?

**Comment by robertjchen** [comment] 2023-08-22 11:28
Thanks, makes sense to me! 👍

**Comment by shubham1206agra** [comment] 2023-08-22 12:28
Please use this to filter
https://stackoverflow.com/a/64021421

**Comment by burczu** [comment] 2023-08-31 09:26
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
 
* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: n/a
* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: n/a
* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: n/a
* [x]  [@burczu] Determine if we should create a regression test for this bug.
* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@garrettmknight] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by garrettmknight** [comment] 2023-09-05 18:42
Payment tomorrow!

**Comment by garrettmknight** [comment] 2023-09-07 10:59
**Summary of payments:**
- urgency bonus?
- Reporter: @NajiNazzal - $250
- Contributor: @dukenv0307  - $1500 paid via Upwork 
- Contributor+: N/A

Upwork Job: https://www.upwork.com/jobs/~01ea72aefb3af1826d

**Comment by garrettmknight** [comment] 2023-09-07 10:59
@NajiNazzal I just sent you an offer in Upwork. Accept and I'll pay this out.

**Comment by garrettmknight** [comment] 2023-09-11 10:20
Paid and done!

**Comment by garrettmknight** [comment] 2023-09-11 10:24
Ah, missed that [here](https://github.com/Expensify/App/issues/25491#issuecomment-1687975865). Let me spin up a contract, but in the future, make sure you're assigned to the issue!

**Comment by garrettmknight** [comment] 2023-09-11 10:26
Offer sent: https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/26607572

**Comment by robertjchen** [comment] 2023-09-14 03:03
Looks like it was accepted, closing this out!

**Comment by robertjchen** [comment] 2023-11-02 13:31
cc

**Closed by robertjchen** 2023-11-02 13:31 UTC
Labels: External, Daily, Awaiting Payment, Bug
