### ISSUE TITLE
[HOLD for payment 2023-10-27] [$500] Double tap on emoji selects am/pm of the time of the message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29021] opened 2023-10-06 17:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any emoji or emoji plus text (ensure emoji is first)
4. Double click on left half of emoji and observe that it select emoji plus AM/PM of above time
## Expected Result: 
App should not select AM/PM from time above on double click selection of emoji
## Actual Result: 
App selects AM/PM from time above on double click selection of emoji
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.79.-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/13d11e41-428d-4a51-b99f-517d6b4446a0

https://github.com/Expensify/App/assets/38435837/9f0082d4-665b-40cf-81e7-c1fdf249f822

https://github.com/Expensify/App/assets/38435837/56358ba3-4900-4d7f-b66f-d7061932d224

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696582198838549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0149fb66dc1d8f480d</li>
        <li>Upwork Job ID: 1710346408992141312</li>
        <li>Last Price Increase: 2023-10-06</li>
<li>Automatic offers: </li>
<ul>
<li>dhanashree-sawant | Reporter | 27220198</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by GianlucaMina** [comment] 2023-10-06 18:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Double tap on emoji selects am/pm of the time of the message

### What is the root cause of that problem?

The problem occurs because when double-clicking a word is selected, and both are pasted for rendering, so they are considered one and causes the error.

### What changes do you think we should make in order to solve the problem?

A space must be added to the end of the word date (am/pm)

### What alternative solutions did you explore? (Optional)

NA

**Comment by KunwarSingh** [comment] 2023-10-06 18:36
### Proposal

Please re-state the problem that we are trying to solve in this issue.
Double tap on emoji selects am/pm of the time of the message

### What is the root cause of that problem?
The problem is related to the way Chrome handles text selection in some cases. It can happen when there are overlapping elements or unusual styling applied to the content.

### What changes do you think we should make in order to solve the problem?
We must add a simple css style to am/pm div

What alternative solutions did you explore? (Optional)
NA

**Comment by KunwarSingh** [comment] 2023-10-06 18:39
Contributor details

Your Expensify account email: thekunwarsingh@gmail.com
Upword Profile Link: https://www.upwork.com/freelancers/~0174c13534125c9866

**Comment by KunwarSingh** [comment] 2023-10-06 18:39
### Proposal

Please re-state the problem that we are trying to solve in this issue.
Double tap on emoji selects am/pm of the time of the message

### What is the root cause of that problem?
The problem is related to the way Chrome handles text selection in some cases. It can happen when there are overlapping elements or unusual styling applied to the content.

### What changes do you think we should make in order to solve the problem?
We must add a simple css style to am/pm div

What alternative solutions did you explore? (Optional)
NA

Contributor details

Your Expensify account email: thekunwarsingh@gmail.com
Upword Profile Link: https://www.upwork.com/freelancers/~0174c13534125c9866

**Comment by KunwarSingh** [comment] 2023-10-06 18:40
@narefyev91 I can quickly resolve this push a fix

**Comment by ayazalavi** [comment] 2023-10-06 18:52
@KunwarSingh what is the css you are adding?

**Comment by KunwarSingh** [comment] 2023-10-06 18:57
separately PM can be selected, but if we double click its not

**Comment by ayazalavi** [comment] 2023-10-07 07:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the web app and desktop app, in the chat listing, if the first chat of each group begins with an emoji as the first character, double-clicking it selects the last word of the previous line.

### What is the root cause of that problem?
The root cause of this issue is the default behavior of Chromium, which selects emojis along with one extra word. This behavior is inherent in all browsers built using Chromium. Here are additional examples from other sites:

<img width="409" alt="Screenshot 2023-10-06 at 11 30 58 PM" src="https://github.com/Expensify/App/assets/767439/43238bc0-1bbf-4d00-8b62-37a3b00151cd">

<img width="527" alt="Screenshot 2023-10-07 at 11 55 53 AM" src="https://github.com/Expensify/App/assets/767439/46baadc7-ddcc-45af-98ad-68ce724c7942">


### What changes do you think we should make in order to solve the problem?
We can avoid this issue by:

1. Detecting if the first character of a particular chat is an emoji.
2. Checking if it is the first chat item, as this issue only occurs when the emoji is the first character of the first chat item.
3. Verifying that it's not a mobile browser since they all use WebKit.
4. Using a Zero-width space character "**_`&#x200b;​`_**" and adding it within the <Text> component at the beginning of the main chat Text component.

To implement this, add the following code to [EmojiUtils.js](https://github.com/Expensify/App/blob/main/src/libs/EmojiUtils.js):

```
function firstLetterIsEmoji(message) {
    const trimmedMessage = Str.replaceAll(message.replace(/ /g, ''), '\n', '');
    const match = trimmedMessage.match(CONST.REGEX.EMOJIS);

    if (!match) {
        return false;
    }

    return trimmedMessage.indexOf(match[0]) === 0;    
}
```

Then, in https://github.com/Expensify/App/blob/389d7b0c4b96c6f2a2295055c685791d35b65252/src/pages/home/report/ReportActionItemMessage.js#L54-L57 add:

`displayAsGroup={props.displayAsGroup}
`

Next at line 116, in https://github.com/Expensify/App/blob/389d7b0c4b96c6f2a2295055c685791d35b65252/src/pages/home/report/ReportActionItemFragment.js#L113-L116 add:

`const firstLetterIsEmoji = EmojiUtils.firstLetterIsEmoji(text);
`

Now, before https://github.com/Expensify/App/blob/389d7b0c4b96c6f2a2295055c685791d35b65252/src/pages/home/report/ReportActionItemFragment.js#L119 add:

` {firstLetterIsEmoji && !props.displayAsGroup && !isMobile() && <Text>&#x200b;</Text>}`

The result can be seen here: 

https://github.com/Expensify/App/assets/767439/ed144c6c-0f49-4743-ba3f-04e10abe9355

### What alternative solutions did you explore? (Optional)
N/A

**Comment by narefyev91** [comment] 2023-10-09 08:19
Proposal from @ayazalavi looks good to me https://github.com/Expensify/App/issues/29021#issuecomment-1751636200
We should not use user-select: none for sure, also personally even adding "Zero-width space character" - looking like a hack to existing Chromium engine. We can try to use window.getSelection to identify which part of the elements we should select - and apply it only for web and desktop and ignore mobile fully.

**But again not sure that we should fix browser normal behaviour. - will wait decision from assigned internal engineer to review** 
🎀 👀 🎀 C+ reviewed

**Comment by ayazalavi** [comment] 2023-10-09 12:39
@narefyev91 When you select an emoji in your browser, it's not just one character; it's a combination of multiple characters, or "Unicode code points," that make up the emoji. The browser selects all of these code points to ensure the emoji is displayed correctly, which might appear as selecting one extra token causing issue mentioned in this ticket. We need to explicitly tell browser to stop collecting tokens in order to avoid this issue. 

Zero-Width Characters: While this can technically work, it might not be the most intuitive solution and can make the code less readable for developers. It's generally better to use other methods if possible.

window.getSelection API: This is a more robust and standard way to manipulate text selection in the browser. You can use it to programmatically select and manipulate text without relying on special characters. This is a cleaner and more maintainable approach if you need to control text selection within your web application.

**Comment by GianlucaMina** [comment] 2023-10-09 17:22
@ayazalavi Could you review my proposal?

**Comment by GianlucaMina** [comment] 2023-10-09 19:18
@narefyev91 Could you review my Proposal?, I think that using userSelect: none applied to a space is the best option since it solves the problem, while still allowing time selection without overcomplicating the problem and ensuring compatibility with all engines, not just chromium.

**Comment by Li357** [comment] 2023-10-11 19:58
@narefyev91 I would say usually we wouldn't fix browser-normal behavior but I think we should fix this. As for proposals, I do think @ayazalavi has the better RCA, but it does seem quite complicated. Is there a downside to `user-select: none` on an empty element? It's not the most elegant but compared to adding a ton of checks to apply for the first character of the first message only on mobile isn't either.

**Comment by GianlucaMina** [comment] 2023-10-11 20:08
@narefyev91 user-select: none has no problems other than readability, I proposed it in the simplest way in am/pm to avoid space problems in rendering, but it can also be transported to the text area (before the emoji) , and can be cleaned up by creating your own component to improve readability.

**Comment by ayazalavi** [comment] 2023-10-12 03:58
@Li357 if we use window.getSelection API then that will help in having better control over selected text which can help full in more use cases later on. Currently it is just the first character that is causing the bug. We can put that in a utility in a function to properly distinguish this issue. That will help clear code and proper understanding of the bug.

**Comment by ayazalavi** [comment] 2023-10-12 11:36
@Li357, we can simply apply the `window.getSelection` functionality to chats and check if a chat message doesn't have "AM/PM" or some other character prepended to it that is not in the chat.

**Comment by narefyev91** [comment] 2023-10-12 11:46
> The `user-select: 'none' `CSS attribute completely disables text selection within an HTML element. Using this CSS attribute requires caution. For instance, in the onPress event, you would need to disable the previous line's selection behavior and re-enable it when the user clicks anywhere else on the page, which can be a tricky process.

@Li357 Based on comment from @ayazalavi :
"The user-select: 'none' CSS attribute completely disables text selection within an HTML element. Using this CSS attribute requires caution. For instance, in the onPress event, you would need to disable the previous line's selection behavior and re-enable it when the user clicks anywhere else on the page, which can be a tricky process."
And for me personally using user-select - is more like a hack - and not a fix for a root case.
But we can choose any approach @Li357

**Comment by Li357** [comment] 2023-10-12 14:28
> However, using userSelect: "none" will disable user selection completely

@ayazalavi But if we're doing this on an empty element, that's not a huge problem right?

@narefyev91 I think any solution is kind of a hack here, since the root cause is a browser-specific bug. I think we can add one comment to an empty View to explain why we need a nonbreaking space. A new utility function and changes in a few files is not as easy to explain or understand IMO.

**Comment by narefyev91** [comment] 2023-10-12 14:36
@Li357 in that case we can choose proposal from @saranshbalyan-1234 https://github.com/Expensify/App/issues/29021#issuecomment-1751347505 because this contributor provide correct root case and correct fix to apply

**Comment by ayazalavi** [comment] 2023-10-12 14:57
> > However, using userSelect: "none" will disable user selection completely
> 
> @ayazalavi But if we're doing this on an empty element, that's not a huge problem right?
> 
> @narefyev91 I think any solution is kind of a hack here, since the root cause is a browser-specific bug. I think we can add one comment to an empty View to explain why we need a nonbreaking space. A new utility function and changes in a few files is not as easy to explain or understand IMO.


There has to be a valid character that instructs the browser to stop calculating emoji bytes, as I mentioned in my proposal. The **Zero-width space character** can help achieve that. If you select `user-select: none`, you will need to add an additional character like `&nbsp;` because an empty `div` with `user-select` will be ignored by the browser, causing it to still select the previous `div`'s last word (i.e., PM/AM). On the other hand, if you add `&nbsp;`, it will introduce an extra space, which is not a valid solution since there will be extra space after AM/PM or before the chat emoji.

Moreover, adding a `user-select` `onPress` event over the chat is not a proper solution, as we have the Selection API available, which can be used instead of dynamically adding `user-select`. Therefore, I still suggest the best solution is to add a ZWSC only if the first character is an emoji. This approach will prevent the selection of AM/PM without disturbing the UI or use the `window.getSelection`, which is even more robust and can be helpful in the long run."

**Comment by GianlucaMina** [comment] 2023-10-12 17:52
> > > Sin embargo, usar userSelect: "none" deshabilitará completamente la selección de usuario.
> > 
> > 
> > @ayazalaviPero si hacemos esto en un elemento vacío, no es un gran problema, ¿verdad?
> 
> Tiene que haber un carácter válido que indique al navegador que deje de calcular bytes de emoji, como mencioné en mi propuesta. El **carácter de espacio de ancho cero** puede ayudar a lograrlo. Si selecciona `user-select: none`, deberá agregar un carácter adicional como porque el navegador ignorará `&nbsp;`un `div`with vacío, lo que provocará que aún seleccione la última palabra del anterior (es decir, PM/AM). Por otro lado, si agregas , introducirá un espacio extra, lo cual no es una solución válida ya que habrá espacio extra después de AM/PM o antes del emoji del chat.`user-select``div``&nbsp;`
> 
> Además, agregar un `user-select` `onPress`evento a través del chat no es una solución adecuada, ya que tenemos disponible la API de selección, que se puede usar en lugar de agregar dinámicamente `user-select`. Por lo tanto, sigo sugiriendo que la mejor solución es agregar un ZWSC solo si el primer carácter es un emoji. Este enfoque evitará la selección de AM/PM sin alterar la interfaz de usuario ni utilizar el `window.getSelection`, que es aún más sólido y puede resultar útil a largo plazo.
> 
> Eche un vistazo al vídeo a continuación que muestra los inconvenientes del uso de la selección de usuario: ninguno. El video muestra claramente que, en caso de elemento vacío, no funciona en absoluto. En otros lugares, el espacio extra será un nuevo error.
> 
>  7f7e79e6-2408-48e0-ba15-bf99e433fc27.mp4

Yes, there is an empty space, but it works correctly as you can see in the video I uploaded with my proposal, you can select both the emoji with the double click and am/pm and even everything together.

I reupload the video so you can see it

https://github.com/Expensify/App/assets/97299911/0173ffef-372c-4271-9e82-f4a3915b0aec

**Comment by GianlucaMina** [comment] 2023-10-12 17:55
> > > However, using userSelect: "none" will disable user selection completely
> > 
> > 
> > @ayazalavi But if we're doing this on an empty element, that's not a huge problem right?
> 
> There has to be a valid character that instructs the browser to stop calculating emoji bytes, as I mentioned in my proposal. The **Zero-width space character** can help achieve that. If you select `user-select: none`, you will need to add an additional character like `&nbsp;` because an empty `div` with `user-select` will be ignored by the browser, causing it to still select the previous `div`'s last word (i.e., PM/AM). On the other hand, if you add `&nbsp;`, it will introduce an extra space, which is not a valid solution since there will be extra space after AM/PM or before the chat emoji.
> 
> Moreover, adding a `user-select` `onPress` event over the chat is not a proper solution, as we have the Selection API available, which can be used instead of dynamically adding `user-select`. Therefore, I still suggest the best solution is to add a ZWSC only if the first character is an emoji. This approach will prevent the selection of AM/PM without disturbing the UI or use the `window.getSelection`, which is even more robust and can be helpful in the long run.
> 
> Please take a look at below video which shows drawbacks of using user-select: none. Video clearly shows in empty element case it doesn't work at all. In other places it will be extra space that is a new bug.
> 
>  7f7e79e6-2408-48e0-ba15-bf99e433fc27.mp4

Yes, there is an empty space, but it works correctly as you can see in the video I uploaded with my proposal, you can select both the emoji with the double click and am/pm and even everything together.

I reupload the video

https://github.com/Expensify/App/assets/97299911/dad9a3e5-1f9f-4a6a-96ee-b2f801285829

**Comment by ayazalavi** [comment] 2023-10-13 13:43
Hello @Li357,

I appreciate your thorough review and the time you've taken to consider my proposal. I understand that there may be some hesitation, but I truly believe that the points I've previously mentioned address the concerns effectively. Your feedback has been invaluable, and I kindly request your support in accepting the proposal based on the reasoning we've discussed.

I am eager to generate a pull request in the next 2-3 hours to wrap up this issue as soon as possible. If there are any additional questions or areas of concern, please feel free to let me know, and I'd be more than happy to provide further clarification.

Thank you for your consideration.

Best regards,
Ayaz

**Comment by ayazalavi** [comment] 2023-10-16 06:01
@Li357 any thoughts regarding my comments above?

**Comment by Li357** [comment] 2023-10-16 13:09
@ayazalavi I appreciate you staying with the issue.  In the interest of getting this done, I'll assign you. I'll review the changes, but try to keep them as minimal as possible to fix the issue at hand. Thanks!

**Comment by ayazalavi** [comment] 2023-10-16 13:50
@Li357 @narefyev91 Thanks for the offer. I am using simplest solution i.e. inserting zero width character for our use case. Sharing PR shortly.

**Comment by sakluger** [comment] 2023-10-27 16:04
@anmurali in case you missed it, this issue caused a regression (https://github.com/Expensify/App/issues/30064) and a fix for that was deployed 1 week ago, so this is ready for payment now.

**Comment by ayazalavi** [comment] 2023-10-31 15:41
https://www.upwork.com/freelancers/ayaz

**Comment by ayazalavi** [comment] 2023-11-03 07:34
@anmurali still waiting for payments.

**Comment by ayazalavi** [comment] 2023-11-10 13:55
any updates guys?

**Comment by anmurali** [comment] 2023-12-06 02:07
@ayazalavi has been paid back on Nov 10. @narefyev91 is a call stack engineer and is handled via invoice. @dhanashree-sawant has also been paid. Closing!

**Closed by anmurali** 2023-12-06 02:07 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug

**Comment by ayazalavi** [comment] 2024-01-21 15:25
@anmurali can you give me ratings in upwork please. 
@narefyev91
