### ISSUE TITLE
[HOLD for payment 2023-09-29] [HOLD for payment 2023-09-27] Split bill - Page freezes when attempting to create split bill

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27713] opened 2023-09-18 20:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25564
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money
3. Select Split for a few members
4. Click Add to split

## Expected Result:
Bill is split successfully

## Actual Result:
Page freezes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1281a87c-950d-4534-aa35-7c14c5abf25c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2023-09-18 21:42
This will be fixed in #27510

**Comment by chiragsalian** [comment] 2023-09-18 23:28
Tagging @thienlnam in this issue since he is reviewing https://github.com/Expensify/App/issues/27510. I think we should also CP the fix since the issue here reports that the app freezes so CP-ing the fix would be nice.

**Comment by situchan** [comment] 2023-09-19 04:43
Based on https://github.com/Expensify/App/issues/27510#issuecomment-1724820875, https://github.com/Expensify/App/pull/26854 might have caused this regression.
cc: @bernhardoj

**Comment by maddylewis** [comment] 2023-09-28 15:27
i will prep payments today

**Comment by maddylewis** [comment] 2023-10-02 14:06
oh...maybe i don't need to pay anyone for this. 

@chiragsalian / @thienlnam - will you review this checklist when you have a chance? https://github.com/Expensify/App/issues/27713#issuecomment-1731407417

and then will you confirm if anyone is due payment for this one? lmk - ty!

**Comment by chiragsalian** [comment] 2023-10-02 17:27
Yeah i believe nothing needs to be done here. The issue was handled elsewhere. Closing this issue.

**Closed by chiragsalian** 2023-10-02 17:27 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
