### ISSUE TITLE
[$500] Distance - Same distance appears twice in the recent list when A-B-A-B distance is created

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34435] opened 2024-01-12 12:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.24-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: There is some history in Recent destination list.

1. Go to workspace chat.
2. Open distance request modal.
3. Enter addresses using A-B-A-B addresses where the first and third addresses are address A, and the second and forth addresses are address B.
4. Create the request.
5. Open the request modal again.
6. Click Start.

## Expected Result:
Address A and B appear only one time in recent destination list

## Actual Result:
Address A and B appear twice in recent destination list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/650e3844-6683-417c-bb41-99bd3007de64

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b842e170e458286</li>
        <li>Upwork Job ID: 1745779025704161280</li>
        <li>Last Price Increase: 2024-01-12</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2024-01-12 12:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Address A and B appear twice in recent destination list.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/a3088d5c5aa5ddc6713f9103a3589ef1f4500d2a/src/libs/actions/Transaction.ts#L99

In here we update NVP_RECENT_WAYPOINTS totally but we use Merge method, so the old value still persist
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/a3088d5c5aa5ddc6713f9103a3589ef1f4500d2a/src/libs/actions/Transaction.ts#L99

We need to update to use SET method instead of MERGE method
### What alternative solutions did you explore? (Optional)
NA

**Comment by DylanDylann** [comment] 2024-01-12 12:35
This is a BE bug, the CreateDistanceRequest API return duplicated waypoint in `expensify_recentWaypoints` key
<img width="405" alt="Screenshot 2024-01-12 at 19 35 23" src="https://github.com/Expensify/App/assets/141406735/8b328ce1-14bd-4ca4-b685-26edf440a033">

**Comment by BhuvaneshPatil** [comment] 2024-01-12 12:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Same address appears twice when waypoints entered in A-B-A-B fashion.

### What is the root cause of that problem?
Backend is returning duplicate waypoints and we setting that in `NVP_RECENT_WAYPOINTS`

### What changes do you think we should make in order to solve the problem?
There are two places that we need to change the code.
- We need to change the `MERGE` method to `SET` method here , this will ensure that we are not putting same address points, further more we can filter the cloned waypoints by unique address so only unique waypoints are set.
https://github.com/Expensify/App/blob/dcd6f5a2a9c115440b8b8c2b376e28771da594a2/src/libs/actions/Transaction.ts#L96-L99
- Even if we perform above step, we still need to show unique address in list for that we need to apply unique filter in here 
https://github.com/Expensify/App/blob/dcd6f5a2a9c115440b8b8c2b376e28771da594a2/src/pages/iou/request/step/IOURequestStepWaypoint.js#L281-L291
This will ensure that we are showing only unique waypoints in offline requests as well. Because for users who already have lots of waypoints in ONYX we have to unique waypoints.

### What alternative solutions did you explore? (Optional)

**Comment by rushatgabhane** [comment] 2024-01-12 13:39
Back-end bug 🎀 👀 🎀

**Comment by techievivek** [comment] 2024-01-15 07:01
Going to assign this to @neil-marcellini as he might have the context on this bug.

**Comment by neil-marcellini** [comment] 2024-01-17 19:32
Yep, this is a pretty straight forward back end bug. I'm going to make it weekly since it's low priority and get to it later.

**Comment by neil-marcellini** [comment] 2024-01-27 04:43
PR is up and under review!

**Closed** 2024-02-02 20:28 UTC
Labels: Reviewing, Daily, Internal, Bug
