### ISSUE TITLE
[HOLD for payment 2024-12-11] Android - Search - Saved search items overlap with navigation bar

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53192] opened 2024-11-27 07:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Device navigation is buttons instead of swipe gestures.
- Account has many saved searches.

1. Launch ND or hybrid app.
2. Go to Search.
3. Tap on the dropdown.
4. Scroll down.

## Expected Result:
Saved search items will not overlap with device navigation bar.

## Actual Result:
Saved search items overlaps with device navigation bar.

This issue is not reproducible if device navigation uses swipe gestures.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6862e950-14f6-4fcf-85ce-75922a977d19

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by techievivek** [comment] 2024-11-27 11:05
@kirillzyusko Are you working on the fix for this? Should we demote it?

**Comment by mountiny** [comment] 2024-11-27 11:06
I can take over, I think we should look into fixing this now as its bad UI/UX, but I would only demote if deploy is getting longer

**Comment by techievivek** [comment] 2024-11-27 11:07
Sounds good, thanks.

**Comment by kirillzyusko** [comment] 2024-11-27 11:30
The iOS also has the same behavior:

<img src="https://github.com/user-attachments/assets/f7c62624-df5a-470f-a59e-33f11a791e69" width="400">

What `edge-to-edge` PR did -> it unified both platforms (now iOS and Android should work in the same way).

I agree that it doesn't look good, but iOS has been working in such way for a long time 🤔 I think at least we should ask UX/UI team opinion (whether we need to apply a bottom padding) and I think we should remove deploy blocker label (because it's not an issue - Android just started to be more similar to iOS).

@mountiny what do you think?

**Comment by mountiny** [comment] 2024-11-27 11:45
I agree its not a blocker as you can click the android buttons, but I would say its not same to compare ios with just a bar on which you always just swipe up to buttons like you can see in the android recording that you have to tap and you can mistap and click on the item behind it

So I am demoting, but lets add a safe area to the android devices that have the buttons in the bottom. I dont feel like this is a problem on ios as you just have the bar on swich you swipe up. But I think we should check what are the ios guidelines on the safe area and follow those

**Comment by mountiny** [comment] 2024-11-27 13:50
@kirillzyusko I put other two issues on hold for this that have same root cause so lets keep it that way

**Comment by trjExpensify** [comment] 2024-12-11 10:38
I think that's incorrect, Melvin. @ZhenjaHorbach reviewed [the PR](https://github.com/Expensify/App/pull/53250).  Can we get the checklist here, please?

**Comment by trjExpensify** [comment] 2024-12-13 00:36
Given that Applause caught this visual bug, I'm inclined to skip adding a standalone regression test for it. Happy for a second opinion on that from @mountiny @techievivek. 

In the meantime, confirming payments as follows: 

- $250 to @ZhenjaHorbach for the C+ review 

Offer sent!

**Comment by trjExpensify** [comment] 2024-12-13 00:38
Paid!

**Comment by mountiny** [comment] 2024-12-13 18:12
definitely no test

**Comment by trjExpensify** [comment] 2024-12-13 18:57
Definitely closing then!

**Closed by trjExpensify** 2024-12-13 18:57 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
