### ISSUE TITLE
[$500] MacOS/Chrome - Background color is stuck on right click/long press on year in year search

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27832] opened 2023-09-20 07:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->profile->personal details->date of birth
3. Click on year to open year search
4. Right click on any unselected value and click on another value to close right click popup or long press on any value on mWeb
5. Hover on other messages in web and observe that background color is stuck on value used in step 4

## Expected Result:
App should remove background color as soon as we hover on other value

## Actual Result:
Background color is stuck on right click/long press on year in year search even on hovering on other value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.71-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/1ff17eef-05e1-4c00-8e27-ecf6595e57b7

https://github.com/Expensify/App/assets/115492554/88672770-0de8-4ae8-9c1e-46dac73ef7c5

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant Dattaram Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695112322258699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01790aaa0a663bd0f8</li>
        <li>Upwork Job ID: 1704394005281148928</li>
        <li>Last Price Increase: 2023-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26982141</li>
<li>dhanashree-sawant | Reporter | 26982143</li>
</ul></li>
    </ul>
</details>

**Comment by studentofcoding** [comment] 2023-09-20 07:41
# Proposal

## Please re-state the problem that we are trying to solve in this issue



## What is the root cause of that problem?

The hover state is not being updated correctly when right-clicking on an element. This is because the `PressableWithoutFeedback` component does not have an event handler for right-click events. As a result, the hover state remains stuck when right-clicking on the element.

## What changes do you think we should make in order to solve the problem?

To fix the issue and make the hover state active when hovering over another element, you can add an onContextMenu event handler to the PressableWithoutFeedback component. This event handler will update the hoveredDay state to null when a right-click event occurs. and also keep tracking onMouseEnter & Leave to track the hovered state

Then on hovered, make the background change

```
<PressableWithoutFeedback
    key={`${index}_day-${day}`}
    disabled={isDisabled}
    onPress={() => this.onDayPressed(day)}
    onContextMenu={() => this.setState({ hoveredDay: null })}
    style={styles.calendarDayRoot}
    accessibilityLabel={day ? day.toString() : undefined}
    focusable={Boolean(day)}
    accessible={Boolean(day)}
    dataSet={{[CONST.SELECTION_SCRAPER_HIDDEN_ELEMENT]: true}}
    onMouseEnter={() => this.setState({ hoveredDay: day })}
    onMouseLeave={() => this.setState({ hoveredDay: null })}
>
    {({ hovered, pressed }) => (
        <View
            style={[
                styles.calendarDayContainer,
                isSelected ? styles.calendarDayContainerSelected : {},
                !isDisabled ? StyleUtils.getButtonBackgroundColorStyle(getButtonState(hovered || day === this.state.hoveredDay, pressed)) : {},
            ]}
        >
            <Text style={isDisabled ? styles.buttonOpacityDisabled : styles.dayText}>{day}</Text>
        </View>
    )}
</PressableWithoutFeedback>
```

## What alternative solutions did you explore? (Optional)

Instead of using the`onMouseEnter` and `onMouseLeave` event handlers, we can use the `onMouseOver` event handler to update the hoveredDay state. The onMouseOver event will be triggered when the mouse pointer enters or leaves the element or any of its child elements.

```
<PressableWithoutFeedback
    key={`${index}_day-${day}`}
    disabled={isDisabled}
    onPress={() => this.onDayPressed(day)}
    onContextMenu={() => this.setState({ hoveredDay: null })}
    style={styles.calendarDayRoot}
    accessibilityLabel={day ? day.toString() : undefined}
    focusable={Boolean(day)}
    accessible={Boolean(day)}
    dataSet={{[CONST.SELECTION_SCRAPER_HIDDEN_ELEMENT]: true}}
    onMouseOver={() => this.setState({ hoveredDay: day })}
>
    {({ hovered, pressed }) => (
        <View
            style={[
                styles.calendarDayContainer,
                isSelected ? styles.calendarDayContainerSelected : {},
                !isDisabled ? StyleUtils.getButtonBackgroundColorStyle(getButtonState(hovered || day === this.state.hoveredDay, pressed)) : {},
            ]}
        >
            <Text style={isDisabled ? styles.buttonOpacityDisabled : styles.dayText}>{day}</Text>
        </View>
    )}
</PressableWithoutFeedback>
```

**Comment by dhanashree-sawant** [comment] 2023-09-20 14:35
Hi @mallenexpensify, @thesahindia whenever you are available, can you change the reported by to my correct handle? currently I am not getting emails due to it. 
Correct handle: @dhanashree-sawant

**Comment by miljakljajic** [comment] 2023-09-21 04:17
@dhanashree-sawant has reported another issue with the background colour being stuck, I think we should combine the two into one issue? @thesahindia what do you think?

https://expensify.slack.com/archives/C049HHMV9SM/p1695223040847299

**Comment by dhanashree-sawant** [comment] 2023-09-21 04:54
They are 2 different components with different cause I guess.

**Comment by miljakljajic** [comment] 2023-09-22 04:50
@thesahindia I'd be curious for your input here as although they're different components, the behaviour is basically identical, so perhaps there is just one root cause that we can identify here.

**Comment by MonilBhavsar** [comment] 2023-09-25 03:31
I see we fixed it here https://github.com/Expensify/App/pull/24577
Where was it updated recently and there's also no blame? anyone has any idea

**Comment by MonilBhavsar** [comment] 2023-09-25 05:43
Welp thanks! That makes sense 👍 
It was deploy last month, so let's handle it separately

**Comment by MonilBhavsar** [comment] 2023-09-25 06:02
> I don't think this fixes the issue at the root, the background is not highlighted any more but the option is still focused and if you press enter, it will still select that option (which is confusing to the user because there's no indication that the option will be selected if pressing enter).

> We should either remove the focus in that case, or keep the focus but also keep the highlight so the user knows what will happen if they press enter.

@dukenv0307 sorry I didn't get the concern here regarding expected behavior. The highlighted background displays the option user is currently viewing and about to select. so on pressing enter, it is expected that it will selected, no?

**Comment by MonilBhavsar** [comment] 2023-09-27 03:26
It also works like this in other sections of the app, so I'm fine 👍 cc @miljakljajic @mallenexpensify would like to have your opinion on this

**Comment by miljakljajic** [comment] 2023-09-29 08:42
Also fine by me

**Comment by MonilBhavsar** [comment] 2023-10-02 15:42
Thanks! We're good to go then 👍

**Comment by MonilBhavsar** [comment] 2023-10-02 16:06
Right! In that case, I think we close this issue? @miljakljajic

**Comment by mallenexpensify** [comment] 2023-10-05 00:37
Also unable to reproduce, closing. Comment and/ore reopen if you disagree or if you're able to reproduce

**Closed by mallenexpensify** 2023-10-05 00:37 UTC
Labels: External, Daily, Bug
