### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Switch to expensify classic button not working on m-web safari

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45941] opened 2024-07-22 19:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  @ishpaul777 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721668187994169

## Action Performed:
1. Go to https://staging.new.expensify.com/settings/exit-survey/reason on mweb
2. Complete the flow
3. Click green Switch to Expensify Classic button
## Expected Result:
User is redirected to olddot
## Actual Result:
User is not redirected to olddot and button nonfunctional
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [X] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3ba0dd6b-7ae5-4942-b2ed-d134233ffc28

https://github.com/user-attachments/assets/dea0236d-321e-4fd5-9fae-cf64905dcf2f

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01550410ab679e7457</li>
        <li>Upwork Job ID: 1815808508017223645</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103303782</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by bernhardoj** [comment] 2024-07-23 05:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Switch to expensify classic doesn't work in mWeb Safari.

### What is the root cause of that problem?
Pressing the switch to expensify classic button will do an API request and will try to open the old dot link after the promise is resolved.
https://github.com/Expensify/App/blob/38cddeeb3879a1eefd4458ba69083c84c8fd83b1/src/pages/settings/ExitSurvey/ExitSurveyConfirmPage.tsx#L86-L94

However, opening a link/new tab inside a promise doesn't work on mWeb Safari. We previously had this kind of issue at https://github.com/Expensify/App/issues/3615 which we fix it by opening a new window first then wait for the promise to complete. 
https://github.com/Expensify/App/blob/38cddeeb3879a1eefd4458ba69083c84c8fd83b1/src/libs/asyncOpenURL/index.website.ts#L13-L28

The issue is that in mWeb Safari, opening a new tab/link requires a user gesture, and [putting it inside a promise won't be considered a user gesture anymore](https://stackoverflow.com/a/23287993/11488790).

### What changes do you think we should make in order to solve the problem?

Call `Link.openOldDotLink(CONST.OLDDOT_URLS.INBOX);` outside of the promise (we can do it only for mWeb Safari).
https://github.com/Expensify/App/blob/38cddeeb3879a1eefd4458ba69083c84c8fd83b1/src/pages/settings/ExitSurvey/ExitSurveyConfirmPage.tsx#L86-L94

```
if (!NativeModules.HybridAppModule) {
    Link.openOldDotLink(CONST.OLDDOT_URLS.INBOX);
}
```


If we only do it in safari, then pressing the Switch to expensify classic will immediately open the new window, while for other platforms, we will wait until the loading is complete.

### What alternative solutions did you explore? (Optional)
The main solution will open the window and set the old link link as the url to the window without waiting the `switchToOldDot` request to complete. If we want to wait for `switchToOldDot`, then we can update `openOldDotLink` to accept a new params called `extraPromise`. We pass the `switchToOldDot` to the `extraPromise` and wait for it to complete.

```
if (!NativeModules.HybridAppModule) {
    Link.openOldDotLink(CONST.OLDDOT_URLS.INBOX, ExitSurvey.switchToOldDot());
} else {
    ExitSurvey.switchToOldDot().then(() => {
        Navigation.resetToHome();
        NativeModules.HybridAppModule.closeReactNativeApp();
    });
}
```

https://github.com/Expensify/App/blob/8e4dc0f032387c00e7ae4a51aff4792bdede5bfa/src/libs/actions/Link.ts#L63-L70

```
extraPromise.then(() => 
    API.makeRequestWithSideEffects(SIDE_EFFECT_REQUEST_COMMANDS.OPEN_OLD_DOT_LINK, {}, {})
        .then((response) => (response ? buildOldDotURL(url, response.shortLivedAuthToken) : buildOldDotURL(url)))
        .catch(() => buildOldDotURL(url))
),
```

**Comment by akinwale** [comment] 2024-07-26 10:41
After reviewing both proposals, we can move forward with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/45941#issuecomment-2244299518) here since the solution follows a pattern that already exists in the codebase.

🎀👀🎀 C+ reviewed.

**Comment by srikarparsi** [comment] 2024-07-29 03:45
Not overdue

**Comment by bernhardoj** [comment] 2024-07-29 05:47
PR is ready

cc: @akinwale

**Comment by abekkala** [comment] 2024-08-02 13:34
### PAYMENT SUMMARY FOR AUG 09, if not regressions

- Fix: @bernhardoj [$250] payment via NewDot
- PR Review: @akinwale [$250] [Offer](https://www.upwork.com/nx/wm/offer/103303782)
please complete checklist

**Comment by akinwale** [comment] 2024-08-03 08:28
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify on Safari on iOS
2. Navigate to Settings then select Switch to Expensify Classic
3. Complete the survey
4. Tap the Switch to Expensify Classic button
5. Verify that a new tab opens and loads the Old Dot URL

Do we agree 👍 or 👎?

**Comment by bernhardoj** [comment] 2024-08-09 01:38
Requested in ND.

**Comment by abekkala** [comment] 2024-08-09 12:57
@akinwale payment sent and contract ended - thank you! 🎉 

Thank you @bernhardoj 

Closing

**Closed by abekkala** 2024-08-09 12:57 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-09 16:22
$250 approved for @bernhardoj
