### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] Distance - Empty waypoint is not discarded but filled with Finish address in distance request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29886] opened 2023-10-18 17:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat > + > Request money > Distance
3. Enter a Start point
4. Leave Finish point empty
5. Click Add stop
6. Enter another distance and proceed with the request creation
7. Open the distance expense details page
8. Click on the Distance

## Expected Result:
Since the waypoint in Step 4 is empty, it should be discarded automatically when the distance request is created

## Actual Result:
The empty waypoint is now filled with the address in Finish point

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/985b6993-e3e1-4c2b-8e84-8d63e275fdd9

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017934cb2ae94a72d9</li>
        <li>Upwork Job ID: 1716323415346421760</li>
        <li>Last Price Increase: 2023-10-23</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27557516</li>
<li>paultsimura | Contributor | 27557519</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-10-18 19:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When creating a Distance request with an empty stop in the middle, it is filled with the Finish address.

### What is the root cause of that problem?
When sending the `CreateDistanceRequest` API request in IOU, we are not removing the empty waypoints.

The `transaction` looks like this:

```json
{
    "comment": {
        "type": "customUnit",
        "customUnit": {
            "name": "Distance"
        },
        "waypoints": {
            "waypoint0": {
                "lat": 10.4958294,
                "lng": -66.884449,
                "address": "Av. Casanova, Caracas, Distrito Capital, Venezuela"
            },
            "waypoint1": {},
            "waypoint2": {
                "lat": 10.5050318,
                "lng": -66.84285249999999,
                "address": "Los Palos Grandes, Caracas 1060, Miranda, Venezuela"
            }
        },
        "isLoading": false
    }
}
```

### What changes do you think we should make in order to solve the problem?

Before sending the API request, we should remove the empty waypoints.

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2023-10-18 20:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When creating a Distance request with an empty stop in the middle, it is filled with the Finish address.

### What is the root cause of that problem?

We are filtering the valid waypoints that will be passed to the BE in this place:

https://github.com/Expensify/App/blob/39d2a8457897439ebab57cf446fc23e90c553a8d/src/libs/actions/IOU.js#L649

However, we do not remove invalid waypoints from the IOU Transaction before building the optimistic data here:

https://github.com/Expensify/App/blob/39d2a8457897439ebab57cf446fc23e90c553a8d/src/libs/actions/IOU.js#L622-L637

As a result, we have an optimistic transaction with the following waypoints in Onyx:

```json
{
    "comment": {
        "type": "customUnit",
        "customUnit": {
            "name": "Distance"
        },
        "waypoints": {
            "waypoint0": {
                "lat": 10.4958294,
                "lng": -66.884449,
                "address": "Av. Casanova, Caracas, Distrito Capital, Venezuela"
            },
            "waypoint1": {},
            "waypoint2": {
                "lat": 10.5050318,
                "lng": -66.84285249999999,
                "address": "Los Palos Grandes, Caracas 1060, Miranda, Venezuela"
            }
        }
    }
}
```

And the `CreateDistanceRequest` API response contains a merge operation with the following data:

```json
{
    "comment": {
        "waypoints": {
            "waypoint0": {
                "lat": 10.4958294,
                "lng": -66.884449,
                "address": "Av. Casanova, Caracas, Distrito Capital, Venezuela"
            },
            "waypoint1": {
                "lat": 10.5050318,
                "lng": -66.84285249999999,
                "address": "Los Palos Grandes, Caracas 1060, Miranda, Venezuela"
            }
        }
    }
}
```

The result of this operation is that waypoint0 and waypoint1 are rewritten, but the waypoint2 remains untouched.

### What changes do you think we should make in order to solve the problem?

We should cleanup the existing transaction's waypoints before building the optimistic data.

I suggest to create a new function in actions/Transaction:

```js
function cleanupWaypoints(transactionID: string): Promise<void> {
    const transaction = allTransactions[transactionID];
    const existingWaypoints = lodashGet(transaction, 'comment.waypoints', {});
    const validWaypoints = TransactionUtils.getValidWaypoints(existingWaypoints, true);

    const updatedWaypoints: WaypointCollection = lodashReduce(existingWaypoints, (result, value, key) => {
        return {
            ...result,
            [key]: validWaypoints[key] ?? null,
        };
    }, {});

    return Onyx.merge(`${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, {
        comment: {
            waypoints: updatedWaypoints,
        },
    });
}
```

Then, cleanup the transaction before calling the IOU.createDistanceRequest here:

```js
Transaction.cleanupWaypoints(props.iou.transactionID).then(() => {
                IOU.createDistanceRequest(...);
});
```

https://github.com/Expensify/App/blob/39d2a8457897439ebab57cf446fc23e90c553a8d/src/pages/iou/steps/MoneyRequestConfirmPage.js#L190-L207

And remove the waypoints cleanup here, as it will already be done:

https://github.com/Expensify/App/blob/39d2a8457897439ebab57cf446fc23e90c553a8d/src/libs/actions/IOU.js#L649




### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2023-10-22 02:13
This doesn't seem like an issue to me? If you don't enter a `FINISH` address but instead add a stop, it make sense that the generated request would have the stop as the finish address, since that's what we assume the destination would be?

cc @hayata-suenaga @neil-marcellini for your thoughts here

**Comment by paultsimura** [comment] 2023-10-22 05:40
> This doesn't seem like an issue to me? If you don't enter a `FINISH` address but instead add a stop, it make sense that the generated request would have the stop as the finish address, since that's what we assume the destination would be?

@jliexpensify The root cause I described above  causes a worse scenario. Please see the recording:

https://github.com/Expensify/App/assets/12595293/d2a5de55-df9e-40d3-9ae4-7abeca8d2945

**Comment by hayata-suenaga** [comment] 2023-10-23 02:12
@jliexpensify the part marked in red below should not appear. so many regression from Wave 5 😢 Thank you for handling this 🙇 

<img width="400" alt="Screenshot 2023-10-23 at 11 11 10 AM" src="https://github.com/Expensify/App/assets/98560306/8634f8fa-16c1-4166-b2a3-ae885d545f4c">

**Comment by jliexpensify** [comment] 2023-10-23 05:19
Got it, thanks for confirming @hayata-suenaga - going to apply the `External` label and get this sorted.

**Comment by DylanDylann** [comment] 2023-10-23 09:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Empty waypoint is not discarded but filled with Finish address in distance request

### What is the root cause of that problem?
A bit context about adding stop flow: When clicking add stop flow the App will redirect to WaypointEditor with index = size of waypoints
https://github.com/Expensify/App/blob/e73cd31a567c5f026f3a9f1435ecb6f99b2fae82/src/components/DistanceRequest/DistanceRequestFooter.js#L104
So when selecting waypoint we need to change index between finish point and the new stop point
We had that logic here
https://github.com/Expensify/App/blob/e73cd31a567c5f026f3a9f1435ecb6f99b2fae82/src/pages/iou/WaypointEditor.js#L122

Come back to this issue, Let's see the logic when selecting the waypoint
https://github.com/Expensify/App/blob/e73cd31a567c5f026f3a9f1435ecb6f99b2fae82/src/pages/iou/WaypointEditor.js#L161-L174

In this logic, we are using save waypoint from Transaction utils directly 
https://github.com/Expensify/App/blob/e73cd31a567c5f026f3a9f1435ecb6f99b2fae82/src/pages/iou/WaypointEditor.js#L167


### What changes do you think we should make in order to solve the problem?
In here
https://github.com/Expensify/App/blob/e73cd31a567c5f026f3a9f1435ecb6f99b2fae82/src/pages/iou/WaypointEditor.js#L167
we should use this function 
https://github.com/Expensify/App/blob/e73cd31a567c5f026f3a9f1435ecb6f99b2fae82/src/pages/iou/WaypointEditor.js#L122
instead of Transaction.saveWaypoint

### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2023-10-26 04:58
@cubuspl42 we have a proposal above, any thoughts?

**Comment by paultsimura** [comment] 2023-10-26 05:52
> we have a proposal above

We have 2 of them, starting with this one: https://github.com/Expensify/App/issues/29886#issuecomment-1769291746

**Comment by cubuspl42** [comment] 2023-10-26 09:40
@paultsimura

I appreciate the detailed and deep root cause analysis! Not for the first time.

On the other hand, the proposal by @DylanDylann is less invasive, as it uses the already existing logic.

Is it possible that the local `saveWaypoint` function archives an equivalent effect to using your new  `cleanupWaypoints` util?

I'm still trying to wrap my head around this.

**Comment by DylanDylann** [comment] 2023-10-26 09:45
@cubuspl42 My solution is small change, I tested and It works well

**Comment by paultsimura** [comment] 2023-10-26 09:48
@cubuspl42 the proposal from @DylanDylann was my alternative approach, but I did not include the actual code (my bad) to keep the proposal cleaner and it was different from the "Expected Behavior" described in the issue:

> Alternatively, we can modify the UX behavior when adding waypoints: replace the first empty waypoint (if there is one) instead of adding a waypoint to the end and keeping an empty waypoint in the middle. However, this needs to be approved by the UX, since this behavior is different from the expected one (as described in the issue). I can provide code for this approach as well (changes in https://github.com/Expensify/App/blob/main/src/pages/iou/WaypointEditor.js), but did not include it here to keep the already long proposal a bit cleaner.

Please also check this part of my proposal, this is the main reason why I suggest going with the actual Onyx cleanup:

> Update:
An important benefit of my solution compared to the one posted below (which was my alternative solution) is that it fixes not only an empty waypoint issue but also the issue when the same waypoint is added multiple times in a row:

But we can combine both the cleanup and the UX change.

**Comment by DylanDylann** [comment] 2023-10-26 09:55
@cubuspl42 Note that: @paultsimura edited his alternative solution after I posted proposal

**Comment by cubuspl42** [comment] 2023-10-26 10:05
@paultsimura Your proposal is solid, but next time don't be afraid to go for the best / most reasonable solution. We quite often modify the app behavior (UX) slightly when solving issues, and it goes without UX approval. And, most importantly, the "Expected result" provided in the issue description should also be looked at with a healthy dose of scepticism. At times, it can be challenged and discussed.

**Comment by cubuspl42** [comment] 2023-10-26 10:06
After giving it a thought, I'll suggest going with @DylanDylann, as they provided a simple change that solves the issue in practice while making an app behave reasonably.

C+ reviewed 🎀 👀 🎀

**Comment by paultsimura** [comment] 2023-10-26 10:24
Thanks @cubuspl42, I understand your reasoning and respect your decision. Just one more question to confirm your POV, and I'll stop the discussion 🙂 

Have you seen this part?

My solution fixes the deeper root cause, that's why it resolves not only an empty waypoint issue but also the issue when the same waypoint is added multiple times in a row (which the other one doesn't):

https://github.com/Expensify/App/assets/12595293/6a0cced0-b042-4ec4-ab30-6547f15d2f2f


Wouldn't it be more efficient to fix 2 issues with a similar root cause together here?

**Comment by paultsimura** [comment] 2023-10-26 10:41
My reasoning here is the following: a new (slightly different in reproduction, but with the same RCA) issue was identified here. It'll be either fixed while working on this issue or created as another issue.
Separating it into another issue is not cost- and time-efficient.

Proposal 1 contains:
- A slightly more complicated fix, but for both issues at once;
- A vague mention of the UX change (although without the code, my bad);

Proposal 2 contains:
- A clear description of the same UX change, which fixes only one issue.
- No mention of the broken waypoints behavior.

So if it is decided to fix the newly identified issue during the development as well, it wouldn't seem fair to go with proposal_2 now and gradually expand the solution to something similar to proposal_1. WDYT?

**Comment by cubuspl42** [comment] 2023-10-26 10:48
If the user adds the same waypoint twice, I'm unsure what they expect. So I'm fine with any reasonable behavior. It seems that the current app behavior can be considered reasonable in _that_ case. So fixing that another issue (which is arguably a problem at all) doesn't add actual value to the solution. I considered it.

Also, the harsh truth is that more invasive changes are always riskier. So if we can solve the problem with a minor change, that's often preferred, unless it's a hack.

This is what I think 🙃

**Comment by iwiznia** [comment] 2023-10-26 11:43
> Separating it into another issue is not cost- and time-efficient.

Agree, especially if the 2 bugs have the same cause or are very closely related

> As a result, we have a transaction with first 2 waypoints from API response, and third - the stale one from the optimistic transaction:

hmmmm this makes me think that there's a bug in the backend, no?

**Comment by cubuspl42** [comment] 2023-10-26 12:12
@paultsimura

**Comment by DylanDylann** [comment] 2023-10-26 12:22
@iwiznia could you help to confirm the new issue mentioned https://github.com/Expensify/App/issues/29886#issuecomment-1780838387 is a bug ?

**Comment by iwiznia** [comment] 2023-10-26 12:42
No idea if we had that issue before, but I agree that if the user adds 2 *contiguous* identical waypoints, we should discard one of them, as it makes no sense to save it twice.

**Comment by paultsimura** [comment] 2023-10-26 12:56
@iwiznia this is not a BE issue: the BE returns what we pass to it.
It's an issue that we do not remove the duplicate and empty waypoints before sending them to the BE in the `transaction`. We perform the cleanup only in the parameter that goes directly into MapBox.

**Comment by iwiznia** [comment] 2023-10-26 13:07
> The issue would be gone if the BE returned the set operation instead of merge, but this is a dangerous approach and has a lot of grey areas.

What do you mean? 

> BE waypoints (these are correctly cleaned):

Oh, then we can just wait for the data to come back from the backed appropriately cleaned.

**Comment by paultsimura** [comment] 2023-10-26 13:09
> Oh, then we can just wait for the data to come back from the backed appropriately cleaned.

But it's already cleaned, isn't it?
Or do you mean that we should expect the BE to respond with nulls included?

```json
{
    "waypoint0": {
        "address": "Kraków, Poland",
        "lat": 50.06465009999999,
        "lng": 19.9449799
    },
    "waypoint1": {
        "address": "Wrocław, Poland",
        "lat": 51.1078852,
        "lng": 17.0385376
    },
    "waypoint2": {
        "address": "Kraków, Poland",
        "lat": 50.06465009999999,
        "lng": 19.9449799
    },
    "waypoint3": null
}
```

**Comment by iwiznia** [comment] 2023-10-26 13:12
I meant that if we change the backed from merge to set, then we can do nothing in the frontend and just wait for the backend to remove the duplicates.
But that would imply changing the backend to use set, which you seem to think is not a good idea, but not sure why.

**Comment by DylanDylann** [comment] 2023-10-26 13:12
@iwiznia I don't think 2 bugs have the same root cause. The extra bug happen because we don't have logic to make error for this case. Note that In the getValidatedWaypoint function we removed duplicated waypoints before sending data to BE. So if we still want to fix this bug, we can add simple check in FE

**Comment by iwiznia** [comment] 2023-10-26 13:26
> The extra bug happen because we don't have logic to make error for this case.

The extra bug meaning the duplicate note getting removed?

> Note that In the getValidatedWaypoint function we removed duplicated waypoints before sending data to BE. So if we still want to fix this bug, we can add simple check in FE

Where exactly?

**Comment by paultsimura** [comment] 2023-10-26 13:26
> Which you seem to think is not a good idea, but not sure why.

The `CreateDistanceRequest` API calls are time-consuming because they wait for a response from MapBox. So there may be a race condition when a request is placed, then some data is changed, and then the response comes that overwrites the whole transaction with the `set` operation. Can this be the case?

In my understanding, using `set` for the already existing keys is mostly considered a bad manner and it's recommended to avoid using it where possible:

```
Actions should favor using `Onyx.merge()` over `Onyx.set()` so that other values in an object aren't completely overwritten.
```

Also, based on this comment, I believe there's an intention to move away from using `set` even for the optimistic action:

https://github.com/Expensify/App/blob/f6a9dde37803302b3b1a1dd2b5c5f720ab309f6d/src/libs/actions/IOU.js#L509-L513

**Comment by DylanDylann** [comment] 2023-10-26 14:33
@iwiznia maybe we already have an issue with the extra bug 
https://github.com/Expensify/App/issues/28477
https://github.com/Expensify/App/issues/29895

**Comment by iwiznia** [comment] 2023-10-26 14:39
Oh, ok, in that case let's go with your solution @DylanDylann

**Comment by DylanDylann** [comment] 2023-10-27 04:55
@cubuspl42 this [PR](https://github.com/Expensify/App/pull/30474) ready for review

**Comment by cubuspl42** [comment] 2023-10-27 10:15
@iwiznia @DylanDylann @paultsimura 

Hey guys, I must apologize. I misunderstood the proposal by @DylanDylann and needed to put more time in testing it.

I think there might have been a misunderstanding about the actual behavior the proposal brings.

https://user-images.githubusercontent.com/141406735/278538836-9dd655fb-d72b-4542-9cc1-14aea63f5a29.mp4

As I see it, the distance request is just left here in a state that I would call inconsistent (the Finish waypoint is left empty).

My mistake is big enough that we should consider re-selecting a proposal.

Again, I apologize for my mishandling here.

**Comment by DylanDylann** [comment] 2023-10-27 10:24
@cubuspl42 the Finish waypoint is left empty because the user doesn't fill it. You mean that the expected should prevent the user from going to the next page if the finish waypoint is empty.

**Comment by cubuspl42** [comment] 2023-10-27 10:40
There were some subtle, but important details I missed during the review, so I'd like to sum them up now:

Our two proposals have major UX differences.

The proposal by @paultsimura assumes the "Add stop" button means "Add a waypoint". From the user's perspective, it _adds_ an empty _stop_ in the middle and _edits_ the "Finish" waypoint. At this point, I don't think this is a good UX. **But** the request is correctly sanitized and in the end it ends up as a reasonable two-point Start-Finish distance request.

The proposal by @DylanDylann assumes "Add stop" really means "Add a stop", i.e. add something labeled as _Stop_ which is a _stop_ between Start and Finish waypoints. Now I consider this good. **But** it makes the current verification logic confused and allows to submit a request without a Finish point, leaving the distance request inconsistent.

So, in the end, neither of the solutions seems entirely proper. We either need to improve the editing UX in the first (make "Add stop" actually add a _stop_) or improve the correctness of the other (leave distance requests in a valid state, either by error messages or by post-sanitizing).

I should've noticed this earlier, and I think this deserves going back to the proposal selection. I think both of the Contributors should have a chance to improve their solutions, as the premature proposal selection was my fault.

**Comment by cubuspl42** [comment] 2023-10-27 10:43
> @cubuspl42 the Finish waypoint is left empty because the user doesn't fill it. You mean that the expected should prevent the user from going to the next page if the finish waypoint is empty.

As I explained above, what's the problem is leaving it in an inconsistent state. Empty Finish waypoint may be reasonable as a temporary state of the UI editor, but not as a persistent permanent state of the request. Solution-wise, both explicitly rejecting such request (error messages) or sanitizing it (deleting the empty Finish waypoint and treating the last stop as Finish waypoint) would sound acceptable for me.

**Comment by DylanDylann** [comment] 2023-10-27 10:52
@cubuspl42 
1. User fill stop point but the finish point is filled instead of stop point
Let's see on staging

https://github.com/Expensify/App/assets/141406735/c3ef9f03-1da9-4561-ae61-8e0da726f985

When finish the first stop waypoint, the App fill the finish waypoint instead of the stop waypoint. It is incorrect and we need to fix it. My proposal did that. (more context: https://github.com/Expensify/App/issues/26888#issuecomment-1720655160)


2. We need to confirm that the finish waypoint and start waypoint need to be filled before moving to the next screen or not
Currently, this is the logic to prevent the next button 
https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/components/DistanceRequest/index.js#L225
we don't have logic to check if the start point or finish point is empty
If we decide to fix this bug, we need to add a condition to check if the start point or finish point is empty we need to prevent the user from going to the next page. I am happy to fix this bug in my PR now

**Comment by paultsimura** [comment] 2023-10-27 10:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When creating a Distance request with an empty stop in the middle, it is filled with the Finish address.

### What is the root cause of that problem?

We are not properly handling the UX behaviour when adding a stop while an empty waypoint exists.

### What changes do you think we should make in order to solve the problem?

**First**, use `saveWaypoint` instead of `Transaction.saveWaypoint` here:

```js
saveWaypoint(waypoint, isEditingWaypoint);
```

https://github.com/Expensify/App/blob/073110231c7a0425ba8fbb21cbdc016fa690f42f/src/pages/iou/WaypointEditor.js#L171

**Second**, update the saveWaypoint function to the following format:

```js
    const saveWaypoint = (waypoint, isEditingWaypoint = false) => {
        const firstEmptyWaypoint = _.findKey(allWaypoints, (value) => _.isEmpty(value));
        const emptyWaypointIndex = _.keys(allWaypoints).indexOf(firstEmptyWaypoint);

        if (emptyWaypointIndex >= 0) {
            Transaction.saveWaypoint(transactionID, emptyWaypointIndex, waypoint, isEditingWaypoint);
        } else {
            Transaction.saveWaypoint(transactionID, waypointIndex, waypoint);
        }
    };
```

It will make sure that:
1. If there's an empty waypoint – it will be filled instead of adding a new stop;
2. Adding a stop will result in appending a new finish point (which seems more user-friendly, but can be reconsidered if we want the stop to be a stop in-between start and finish, not a new waypoint).

https://github.com/Expensify/App/blob/073110231c7a0425ba8fbb21cbdc016fa690f42f/src/pages/iou/WaypointEditor.js#L125-L133

#### Result:


https://github.com/Expensify/App/assets/12595293/cc6e610c-cb11-42c8-9692-1da827e8ae9c


### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-10-27 11:39
[updated proposal](https://github.com/Expensify/App/issues/29886#issuecomment-1774772120)

**Comment by paultsimura** [comment] 2023-10-27 11:56
## Proposal

Updated proposal: https://github.com/Expensify/App/issues/29886#issuecomment-1782714921

**Comment by DylanDylann** [comment] 2023-10-28 10:33
# Proposal

Updated proposal: https://github.com/Expensify/App/issues/29886#issuecomment-1774772120

**Comment by cubuspl42** [comment] 2023-10-30 08:01
Thanks for the updates!

@DylanDylann The error handling you suggested should do the job.

@paultsimura That's an interesting idea! Unfortunately, I see challenges here. Google Maps has a "linear" model of waypoints without distinguished "Start" and "Finish" points. All points are called "destinations," once you fill in the first two, you can add more. I think it rhymes with how the users might think about planning their journey ("First, let's go to Ann's place, then pick up Bob, and finally we head to Charlie's party"). Expensify picked a different model, and it might confuse the user as to why they cannot plan the journey in this order. I'm saying that this will happen for sure, as I haven't done any UX research here, but it's too big a risk in the context of our original issue.

As I see it, we can resume the work with @DylanDylann. Sorry for all the fuss, but I wanted to ensure that the process is relatively fair.

**Comment by paultsimura** [comment] 2023-10-30 08:33
I'm not competing for this issue anymore, just need to complete my understanding.

> Expensify picked a different model, and it might confuse the user as to why they cannot plan the journey in this order.

@cubuspl42 Could you please elaborate on this?

In my understanding, Expensify currently works exactly like Google Maps: on clicking "Add stop" we append a new waypoint to the end of the route. That's the same linear model, isn't it?

https://github.com/Expensify/App/assets/12595293/4f530a3e-9b8d-4eaa-a524-923dd2fae80c

My suggestion was just to simplify the UX without changing the current approach 🤔

**Comment by cubuspl42** [comment] 2023-10-30 09:09
@paultsimura You're right... I missed it. This issue is not my lucky one...

> In my understanding, Expensify currently works exactly like Google Maps

It seems that it indeed does... But it's not what I expected. The waypoints are labelled in a misleading way. You fill a _Start_ point, a _Finish_ point, and then press "Add stop". Instead of adding what's labeled a "Stop", we change the _Finish_ point to a _Stop_ and we add a new _Finish_ point. Is this really how stopping works?...

We have a real UX issue here that's a starting point of all the technical problems.

As it indeed looks like Expensify uses Google Maps model, just labels it in a misleading way, I now agree that the fix you suggest solves everything.

I'll figure out how we can proceed so we solve the issue so nobody is left at a disadvantage.

**Comment by cubuspl42** [comment] 2023-10-30 09:31
My plan for now is:
- Figuring out / approving the new behavior [in a Slack discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1698657301690469)
- Ensuring that all sides are compensated; if we decide to go with @paultsimura's proposal after all, @DylanDylann could be compensated from my share

**Comment by jliexpensify** [comment] 2023-10-30 23:53
Thanks @cubuspl42 , appreciate you owning this one!

**Comment by DylanDylann** [comment] 2023-10-31 04:36
From Slack discussion, we decided to only show the add button when there are 2+ valid waypoints. Because we change the UX behavior. We also need to update other flow to make sure every work well
This is a bug I see after changing UX behavior even when I applied @paultsimura's proposal

https://github.com/Expensify/App/assets/141406735/482bb102-fdff-4ca3-9474-33664b62b22f

So that I updated [proposal](https://github.com/Expensify/App/issues/29886#issuecomment-1774772120) to follow new UX change and fix other cases

**Comment by paultsimura** [comment] 2023-10-31 05:00
@DylanDylann basically this "other bug" you're mentioning is a regression from [this your PR](https://github.com/Expensify/App/pull/27657), which introduced inconsistency between online & offline "Add stop" flows, but went unnoticed for about a month.
We surely should fix this. But I don't think that using one's own regression as a foundation for a new proposal without even mentioning it is well aligned with our code of conduct.

**Comment by DylanDylann** [comment] 2023-10-31 05:04
@paultsimura It was expected before. But in this issue, we decided to change UX behavior. So we also need to fix it. Note that It is not a bug if we don't change UX behavior.

**Comment by paultsimura** [comment] 2023-10-31 05:08
> @paultsimura 
Note that It is not a bug if we don't change UX behavior.


We're not changing the UX, we're just hiding a button. In current prod, if you add a stop online, it's appended to the end of a route. Offline - in the middle. If it was an expected behavior, it should have been aligned with the online flow.

**Comment by cubuspl42** [comment] 2023-10-31 12:00
Guys, it's important that we maintain a collaborative and respectful environment. Let's try to keep our comments focused on the code and the proposed solutions, rather than on each other's actions.

**Comment by DylanDylann** [comment] 2023-10-31 12:03
@cubuspl42 I [updated proposal](https://github.com/Expensify/App/issues/29886#issuecomment-1774772120) to give more value to our repository and there are nothing else

**Comment by paultsimura** [comment] 2023-11-04 09:55
Hey @cubuspl42, could you please share your final decision here? 🙏 
Probably Melvin doesn't put labels here anymore since it was assigned to a contributor.

**Comment by cubuspl42** [comment] 2023-11-06 10:45
As I see it, the best way to move forward is to reassign this issue to @paultsimura, as their idea to show the "Add stop" button conditionally solves the original issue **and** improves the user experience. It also got approval in [the Slack discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1698657301690469).

CC: @iwiznia

@DylanDylann, I'm sorry about any mistakes I've made when handling this issue. I'll make things right and ensure you get partial compensation for your efforts and time.

This [PR](https://github.com/Expensify/App/pull/30474#issuecomment-1793315221) can be closed.

**Comment by DylanDylann** [comment] 2023-11-07 07:25
@cubuspl42 @iwiznia I think we need to raise PR soon to avoid redundant work in [this issue](https://github.com/Expensify/App/issues/29895#issuecomment-1796093488)

**Comment by paultsimura** [comment] 2023-11-07 13:14
My PR's ready, I'm just waiting to be assigned to this issue.

**Comment by paultsimura** [comment] 2023-11-07 18:41
Thanks. The PR is ready: https://github.com/Expensify/App/pull/31017

**Comment by jliexpensify** [comment] 2023-11-08 02:26
Hi @cubuspl42 - let me know what partial compensation you'd like to offer and I'll write it into my Payment Summary. Thanks!

**Comment by cubuspl42** [comment] 2023-11-08 09:13
@jliexpensify I was thinking about $250 for @DylanDylann. It can be taken from my share.

**Comment by jliexpensify** [comment] 2023-11-08 21:37
Thanks! Assuming there are no regressions/bonuses, here's what the Payment Summary would look like:

- Contributor: @paultsimura $500
- Contributor: @DylanDylann $250 - [comment](https://github.com/Expensify/App/issues/29886#issuecomment-1794541149)
- C+: @cubuspl42 $250 (invoiced) 

[Upwork job](https://www.upwork.com/jobs/~017934cb2ae94a72d9)

**Comment by jo-ui** [comment] 2023-11-15 08:16
@jliexpensify this issue is dupe of #28477 this has been told many times but nothing has been done to close this issue and open the #28477

**Comment by paultsimura** [comment] 2023-11-15 08:41
@jo-ui this is definitely not a dupe of https://github.com/Expensify/App/issues/28477. In fact, during the investigation of this issue, a separate bug was found, but we decided not to fix it because it would be fixed in https://github.com/Expensify/App/issues/28477

> This has been told many times

I can't find any mention of this issue in https://github.com/Expensify/App/issues/28477 – could you please point us to where it was mentioned as a dupe?

**Comment by jo-ui** [comment] 2023-11-15 08:53
@paultsimura sorry for the confusion, I wrote the comment in the wrong issue sorry again

**Comment by cubuspl42** [comment] 2023-11-20 11:55
- The PR that introduced the bug has been identified. Link to the PR:
    -  It seems that the bug was present in the relevant components since they were created
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Yes
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - Go to "+" (FAB) -> "Request money" -> "Distance" tab
        * [ ] Verify that the "Add stop" button is not shown
    - Fill the "Start" waypoint
        * [ ] Verify that the "Add stop" button is still not shown
    - Fill the "Finish" waypoint
        * [ ] Verify that the "Add stop" button is shown now
    - Press "Add stop" and add a waypoint
        * [ ] Verify that the new waypoint is added at the end of a route and is now marked as "Finish"
    - Remove two waypoints, so only one is filled
        * [ ] Verify that the "Add stop" button is not shown anymore

**Comment by jliexpensify** [comment] 2023-11-23 02:41
There's some issues with Upworks atm, going to try paying later today

**Comment by jliexpensify** [comment] 2023-11-23 05:11
Everyone is now paid and job is closed!

**Closed by jliexpensify** 2023-11-23 05:11 UTC
Labels: External, Daily, Awaiting Payment, Bug
