### ISSUE TITLE
[$250] Distance - Search results return no results when submitting tracked distance to someone

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50495] opened 2024-10-09 09:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1707@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to self DM and submit a distance expense
3. Click on submit it to someone
4. Search for any users' email

## Expected Result:
Users show up in the results

## Actual Result:
No users show up and no results found is shown

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/589f2b74-2327-4007-96fd-c476054eb371

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844352786289436667</li>
        <li>Upwork Job ID: 1844352786289436667</li>
        <li>Last Price Increase: 2024-10-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by IuliiaHerets** [comment] 2024-10-09 09:46
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-10-09 10:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The submit to someone result is empty.

### What is the root cause of that problem?
When we select submit to someone, it should show a user list. However, if the account doesn't have a distance P2P beta, then no user will be shown.
https://github.com/Expensify/App/blob/5d25b40eab1416d2d67624a376099853a2b6af86/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L130

https://github.com/Expensify/App/blob/5d25b40eab1416d2d67624a376099853a2b6af86/src/libs/OptionsListUtils.ts#L1983-L1986

### What changes do you think we should make in order to solve the problem?

Hide the submit to someone button if the track is a distance and user/account doesn't have the distance P2P beta.
https://github.com/Expensify/App/blob/5d25b40eab1416d2d67624a376099853a2b6af86/src/pages/home/report/ReportActionItem.tsx#L418-L455

```
const {canUseP2PDistanceRequests} = usePermissions();
const [isActionableTrackDistanceRequest] = useOnyx(
    `${ONYXKEYS.COLLECTION.TRANSACTION}${ReportActionsUtils.isActionableTrackExpense(action) ? ReportActionsUtils.getOriginalMessage(action)?.transactionID : -1}`,
    {selector: (transaction) => isDistanceRequest(transaction)},
)
...

if (ReportActionsUtils.isActionableTrackExpense(action)) {
    const transactionID = ReportActionsUtils.getOriginalMessage(action)?.transactionID;
    const actionableButtons = [
        {
            text: 'actionableMentionTrackExpense.categorize', ...,
        }, ...
    ];

    if (canUseP2PDistanceRequests || !isActionableTrackDistanceRequest) {
        actionableButtons.unshift({
            text: 'actionableMentionTrackExpense.submit',
            key: `${action.reportActionID}-actionableMentionTrackExpense-submit`,
            onPress: () => {
                ReportUtils.createDraftTransactionAndNavigateToParticipantSelector(transactionID ?? '0', reportID, CONST.IOU.ACTION.SUBMIT, action.reportActionID);
            },
            isMediumSized: true,
        });
    }

    return actionableButtons;
}
```

<img width="768" alt="image" src="https://github.com/user-attachments/assets/04e28b3b-a425-4615-aeaa-ac4cbd9846fd">

**Comment by bernhardoj** [comment] 2024-10-24 14:58
This is already fixed in https://github.com/Expensify/App/pull/50331.

**Closed** 2024-10-27 22:13 UTC
Labels: External, Daily, Help Wanted, Bug
