### ISSUE TITLE
[$500] Web - Navigation breaks on opening attachment, reload and opening search by shortcut

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28241] opened 2023-09-26 09:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any attachment
4. Open the attachment
5. Reload
6. Click CTRL+K/CMD+K to open search and observe that URL changes but app still displays image
7. Close the attachment and observe that URL still shows attachment URL but app displays the report

## Expected Result:
App should close the image attachment when we open search page using shortcut

## Actual Result:
App does not close the image attachment when we open attachment, reload and open search page using shortcut and it breaks the further navigation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Build v1.3.74-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/8f078d5d-1707-4379-a538-9caa1dd8a5b1

https://github.com/Expensify/App/assets/115492554/9e9a3b4f-e93f-44f3-8f68-89c5103718d6

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695575577105459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d3cee7fe8b187729</li>
        <li>Upwork Job ID: 1706594842812719104</li>
        <li>Last Price Increase: 2023-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27004795</li>
<li>dhanashree-sawant | Reporter | 27004799</li>
</ul></li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2023-09-26 13:28
# Proposal
## Please re-state the problem that we are trying to solve in this issue
App does not close the image attachment when we open attachment, reload and open search page using shortcut and it breaks the further navigation.

## What is the root cause of that problem?
The cause of the problem is the **KeyboardShortcut.subscribe** function which is supposed to close the modal then navigate to the search route but in this case the **Modal.close()** function does not work as expected, meaning does not trigger the closing of the modal and only calls the callback of the Modal.close() function hence why it navigates to search without closing the modal and therefore breaks the navigation.

## What changes do you think we should make in order to solve the problem?
Within the **AuthScreens.js** component I changed the **KeyboardShortcut.subscribe** function to use **Navigation.dismissModal()** to close the modal then using promise syntax to navigate to search:

```diff
// Listen for the key K being pressed so that focus can be given to
// the chat switcher, or new group chat
// based on the key modifiers pressed and the operating system
this.unsubscribeSearchShortcut = KeyboardShortcut.subscribe(
    searchShortcutConfig.shortcutKey,
    () => {
-            Modal.close(() => {
-                if (Navigation.isActiveRoute(ROUTES.SEARCH)) {
-                    return;
-                }
-                return Navigation.navigate(ROUTES.SEARCH);
-            });
+            Navigation.dismissModal()?.then(() => {
+                if (Navigation.isActiveRoute(ROUTES.SEARCH)) {
+                    return;
+                }
+
+                return Navigation.navigate(ROUTES.SEARCH);
+            });
    },
    searchShortcutConfig.descriptionKey,
    searchShortcutConfig.modifiers,
    true,
);
```

## What alternative solutions did you explore? (Optional)
N/A

**Comment by LiaqatSaeed** [comment] 2023-09-27 11:00
@dukenv0307  what if we close this modal on Pressing "Ctrl +K/cmd+K". We put a check if Modal is visible Close it before opening Search. thoughts?

**Comment by SergeyHTML** [comment] 2023-09-28 15:26
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
Navigation breaks on opening attachment, reload and opening search by shortcut

### What is the root cause of that problem?
Here when the PopoverWithoutOverlay is rendered the first time, it always sets the closeModal function to null, which overrides the closeModal function that is set by the attachment modal when the attachment modal is first rendered. So it fails to close the attachment modal when using the shortcut here.

### What changes do you think we should make in order to solve the problem?
We can check the Modal is open and will not override the method `closeModal`.

We can export `closeModal ` from the `Modal` and in the component `PopoverWithoutOverlay` add the condition.
```javascript
if (!Modal.closeModal) {
            Modal.setCloseModal(props.isVisible ? () => props.onClose(props.anchorRef) : null);
        }
``` 

### What alternative solutions did you explore? (Optional)

N/A

**Comment by kaushiktd** [comment] 2023-09-29 12:08
### Please re-state the problem that we are trying to solve in this issue.
when users open an image attachment within the application, reload the application, and then attempt to open the search page using a keyboard shortcut, the application fails to close the previously opened image attachment. This behavior disrupts further navigation within the application.

### What is the root cause of that problem?
The root cause of this problem appears to be related to how the application manages the state of opened attachments and how it handles navigation. Specifically, when the attachment is initially rendered, it doesn't close properly when switching to the search page using a keyboard shortcut.

### What changes do you think we should make in order to solve the problem?
file path: https://github.com/Expensify/App/blob/main/src/components/PopoverWithoutOverlay/index.js

Create a Ref for `isVisible`: Instead of relying on the previous value of `isVisible` stored in a state variable, we can use a ref to keep track of the previous value. Refs persist across renders and can be helpful for comparing previous and current values without causing re-renders.
```
const prevIsVisibleRef = React.useRef(props.isVisible);

// Update the ref when isVisible changes
React.useEffect(() => {
  prevIsVisibleRef.current = props.isVisible;
}, [props.isVisible]);

Modify the useEffect: In the useEffect block, you can now directly compare the current isVisible prop with the value stored in the ref to determine if it has changed.
React.useEffect(() => {
  // Check if isVisible has changed
  if (prevIsVisibleRef.current !== props.isVisible) {
    if (props.isVisible) {
      props.onModalShow();
      onOpen({
        ref,
        close: props.onClose,
        anchorRef: props.anchorRef,
      });
    } else {
      props.onModalHide();
      close(props.anchorRef);
      Modal.onModalDidClose();
    }
    Modal.willAlertModalBecomeVisible(props.isVisible);
    Modal.setCloseModal(props.isVisible ? () => props.onClose(props.anchorRef) : null);
  }
}, [props.isVisible]);

```
By using this approach, you maintain a reference to the previous value of `isVisible` without causing additional re-renders. This can help ensure that the `Modal.setCloseModal` logic is only executed when there is a change in the `isVisible` prop.

### Video:- 
https://drive.google.com/file/d/1j6K3FmCYpXD-zXvj5smSgu2RhRZuK5YR/view?usp=sharing

**Comment by kaushiktd** [comment] 2023-09-29 15:15
@parasharrajat, I am wondering if you checked my proposal earlier today! Would love your feedback. Feedback will help me either way! 🙂

**Comment by NicMendonca** [comment] 2023-10-02 20:19
bump @deetergp - https://github.com/Expensify/App/issues/28241#issuecomment-1740929220

**Comment by deetergp** [comment] 2023-10-03 19:12
Heya, since @parasharrajat is back in the next day or two, I will assign @dukenv0307 today.

**Comment by NicMendonca** [comment] 2023-10-18 19:38
@parasharrajat are we holding payment here? 👀

**Comment by deetergp** [comment] 2023-10-23 17:17
I believe we are still waiting on the resolution of #27244?

**Comment by deetergp** [comment] 2023-10-25 07:04
Looks like https://github.com/Expensify/App/issues/27244 has been merged and is in the regression period. We should know by Tuesday.

**Comment by NicMendonca** [comment] 2023-10-31 21:50
@deetergp @parasharrajat what's the next steps for this one? Are we paying out now?

**Comment by deetergp** [comment] 2023-11-01 00:57
Would someone be willing to retest this to see if https://github.com/Expensify/App/issues/27244 resolved our issue?

**Comment by NicMendonca** [comment] 2023-11-02 19:16
Oh sorry, the hold for payment automation didn't click in

**Comment by NicMendonca** [comment] 2023-11-02 19:20
Reporter: @dhanashree-sawant  - $50
Contributor: @dukenv0307 - $500 
C+: @parasharrajat $500 - paid via Expensify

**Comment by NicMendonca** [comment] 2023-11-02 19:21
@dhanashree-sawant, @dukenv0307 you've been paid! 

@parasharrajat don't forget to request payment via Expensify!

🎉

**Closed by NicMendonca** 2023-11-02 19:21 UTC
Labels: Daily, Internal, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-04-08 03:02
$500 approved for @parasharrajat
