### ISSUE TITLE
Web - Member appears twice when added to a Workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21904] opened 2023-06-29 21:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. User A: Create a new workspace
2. Invite User B to the workspace
3. Observe that User B appears twice in the participants list

## Expected Result:
User B should appear once

## Actual Result:
User B appears twice

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9ba15f4b-4e47-4f82-8789-2515f7346d33

**Expensify/Expensify Issue URL:**
**Issue reported by:** @samh-nl
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687982344998189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2023-06-30 15:47
Dupe of https://github.com/Expensify/App/issues/21706 actually! (just like https://github.com/Expensify/App/issues/21782 and https://github.com/Expensify/App/issues/21957)

**Closed by conorpendergrast** 2023-06-30 15:47 UTC
Labels: Daily, Needs Reproduction, Bug
