### ISSUE TITLE
[hold #17246] [$1000] Web-Zooming in picture from the trackpad exits the picture view

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23876] opened 2023-07-29 23:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing PR #23072
## Action Performed:
1. Add multiple attachments (images and PDFs) in any chat.
2. Tap/click to open an attachment, make sure the right attachment is opened.
3. Scroll or swipe between attachments.
4. Test out the zoom and pan features.
## Expected Result:
Image displayed when zoomed in using track pad by two fingers

## Actual Result:
Zooming in picture from the trackpad exits the picture view or results in a generic uh oh error. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1af4aeb5-1d96-4e23-a027-dbe6f32beafa

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153ec226a44c7109e</li>
        <li>Upwork Job ID: 1686107386665205760</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-07-31 20:10
I can't reproduce this exact behavior (of exiting the picture view). But when I try and pinch to zoom in the picture view, the components do not resize correctly for me, and I end up getting a generic uh oh error. 

https://github.com/Expensify/App/assets/54866469/d1614dd5-ba33-4c96-a37c-2e585969e8a9

**Comment by joekaufmanexpensify** [comment] 2023-07-31 20:12
Though, I wonder if this is a duplicate of https://github.com/Expensify/App/issues/17246 . Curious what you think @mananjadhav ?

**Comment by mananjadhav** [comment] 2023-08-01 04:09
Thanks for the ping @joekaufmanexpensify. I wouldn't say exact duplicate, but I think the refactor could solve this. Instead of closing, we should put this on Hold.

**Comment by joekaufmanexpensify** [comment] 2023-08-01 20:42
Cool sounds good. And then just test once it's complete and validate whether it was in fact fixed?

**Comment by mananjadhav** [comment] 2023-08-02 05:28
Yeah, that's right.

**Comment by joekaufmanexpensify** [comment] 2023-08-07 13:07
On hold

**Comment by joekaufmanexpensify** [comment] 2023-08-21 13:27
Same.

**Comment by joekaufmanexpensify** [comment] 2023-08-28 13:41
Held

**Comment by joekaufmanexpensify** [comment] 2023-09-04 17:54
Same

**Comment by joekaufmanexpensify** [comment] 2023-09-11 13:41
Held

**Comment by joekaufmanexpensify** [comment] 2023-09-17 08:38
on hold

**Comment by joekaufmanexpensify** [comment] 2023-09-25 03:03
Same

**Comment by joekaufmanexpensify** [comment] 2023-10-02 21:27
Still held

**Comment by joekaufmanexpensify** [comment] 2023-10-09 15:12
Same

**Comment by joekaufmanexpensify** [comment] 2023-10-16 14:55
Held

**Comment by joekaufmanexpensify** [comment] 2023-10-23 14:09
Still held

**Comment by joekaufmanexpensify** [comment] 2023-10-30 14:06
Same

**Comment by joekaufmanexpensify** [comment] 2023-11-08 14:36
Same.

**Comment by joekaufmanexpensify** [comment] 2023-11-20 14:14
Same.

**Comment by joekaufmanexpensify** [comment] 2023-11-27 15:02
Same

**Comment by joekaufmanexpensify** [comment] 2023-12-04 16:16
Held

**Comment by joekaufmanexpensify** [comment] 2023-12-11 14:33
Held issue is closed. Going to retest to see if this is all set

**Comment by joekaufmanexpensify** [comment] 2023-12-11 16:29
Retested and confirmed this is fixed. Closing as no action is needed here!

**Closed by joekaufmanexpensify** 2023-12-11 16:29 UTC
Labels: External, Daily, Help Wanted, Bug
