### ISSUE TITLE
Cannot refresh website using pull-to-refresh 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14396] opened 2023-01-18 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Visit https://staging.new.expensify.com/
2. Try pull-to-refresh

## Expected Result:
Refresh icon shows and website should be reloaded

## Actual Result:
Nothing happens

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / Chrome

**Version Number:** 1.2.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/213289291-72bb07fd-8151-419e-ac25-b69c3e6467ce.jpg" width="40%" height="40%">

https://user-images.githubusercontent.com/43996225/213289467-5f479499-a99a-4426-93f2-0ab68619fd14.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @0xmiroslav 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674040409891389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment] 2023-01-20 03:17
Getting clarity on intended behaviour [here](https://expensify.slack.com/archives/C049HHMV9SM/p1674184537753609?thread_ts=1674040409.891389&cid=C049HHMV9SM).

**Comment by kadiealexander** [comment] 2023-01-23 20:50
Closing, as agreed in Slack!

**Closed by kadiealexander** 2023-01-23 20:50 UTC
Labels: Daily, Overdue, Bug
