### ISSUE TITLE
Web - IOU - Wrong values for Amount and Total fields in Offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36184] opened 2024-02-08 22:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34135

## Action Performed:
Precondition: user is a member of workspace. User is logged in ND.
1. Navigate to a workspace chat
2. Disable the internet connection
3. Click on "+"
4. Select "Request Money"
5. Click on the "Distance" tab
6. Proceed to the confirmation page
7. Complete the distance request
8. Navigate (if not already) to the chat that contains the recently created Distance request

## Expected Result:
Amount is displayed as "Route pending..."
In the LHN, the preview shows "Route pending..."
Total Expense shows $0

## Actual Result:
Amount is blank in request details page and absent in preview.
In the LHN, the preview shows "Route pending..."
Total Expense is absent on preview.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d7e395cf-2c95-45a7-afa1-0dfd4d3798aa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-02-08 22:16
We think that this bug might be related #wave6-collect-submitters
CC @greg-schroeder

**Comment by neil-marcellini** [comment] 2024-02-08 22:21
Not a bug, I don't see anything wrong here in related to the QA steps in that PR. It looks like this is working as intended according to the desired changes from [the issue](https://github.com/Expensify/App/issues/33362).

However, we do need to update the existing distance regression steps. I'm going to close this, and make a note in the issue to get the regression steps updated.

**Closed by neil-marcellini** 2024-02-08 22:21 UTC
Labels: Engineering, Hourly
