### ISSUE TITLE
[$1000] Chat - User is not navigated to last open chat from staging.new.expensify.com/r/

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22918] opened 2023-07-14 20:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22260
## Action Performed:
1. Go to staging.new.expensify.com
2. Switch between different chats.
3. Navigate to staging.new.expensify.com/r/

## Expected Result:
User is navigated to the last open chat

## Actual Result:
User is occasionally not navigated to the last open chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8a4e8570-b5a0-41db-a5c6-8660894ee2b9

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110410e5de5300b96</li>
        <li>Upwork Job ID: 1680957601760178176</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-07-17 15:08
I was able to recreate this, so going to get eyes on it, in line with the linked GH above

**Comment by CortneyOfstad** [comment] 2023-07-20 12:57
Not overdue — just waiting on proposals

**Comment by CortneyOfstad** [comment] 2023-07-24 13:45
@kameshwarnayak any updates?

**Comment by CortneyOfstad** [comment] 2023-07-25 17:42
I am also having a heck of a time recreating this now. @lanitochka17 can you confirm that you're still experiencing this?

**Comment by CortneyOfstad** [comment] 2023-07-28 16:02
@kameshwarnayak any updates on this?

**Comment by mananjadhav** [comment] 2023-07-28 19:12
I am unable to reproduce this @lanitochka17 do we have any better reproduction steps?

**Comment by CortneyOfstad** [comment] 2023-07-31 13:02
@lanitochka17 bump on @mananjadhav's comment above ^^^

**Comment by mvtglobally** [comment] 2023-08-02 16:50
Issue not reproducible during KI retests. (First week)

**Comment by NicMendonca** [comment] 2023-08-03 22:40
^^ I think we can close this!

**Closed by NicMendonca** 2023-08-03 22:40 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
