### ISSUE TITLE
[HOLD for payment 2023-10-18] [$1000] Web - Request money - No hover indicator for top tab options

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26648] opened 2023-09-04 11:37 UTC
Please read: Please review [this slack discussion ](https://expensify.slack.com/archives/C049HHMV9SM/p1693396751536049)and incorporate the design framework being discussed there in any proposals.
___
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB
2. Request money
3. Hover over the top tab options ("Manual", "Scan", and "Distance")

## Expected Result:
There should be a hover indicator

## Actual Result:
No hover state indicator is present

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/50f6b1d3-44ac-4d57-9518-f50395b2dbd4

https://github.com/Expensify/App/assets/93399543/a910df2a-4301-4802-b2d9-a91acf32b6ca

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation** https://expensify.slack.com/archives/C049HHMV9SM/p1693396751536049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011fec984afd4c346b</li>
        <li>Upwork Job ID: 1699409777798025216</li>
        <li>Last Price Increase: 2023-09-26</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26915529</li>
<li>wildan-m | Contributor | 26915530</li>
<li>Nathan-Mulugeta | Reporter | 26915533</li>
</ul></li>
    </ul>
</details>

**Comment by garrettmknight** [comment] 2023-09-05 18:33
Confirming whether this is expected or not in thread.

**Comment by garrettmknight** [comment] 2023-09-06 13:09
This isn't working as designed - @neonbhai (and anyone else who wants to work on this) please review [this slack discussion ](https://expensify.slack.com/archives/C049HHMV9SM/p1693396751536049)and incorporate the design framework from there.

**Comment by wildan-m** [comment] 2023-09-07 10:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Request money - No hover indicator for top tab options

### What is the root cause of that problem?

hover is not defined in the `TabSelectorItem`

### What changes do you think we should make in order to solve the problem?

I think we have to combine `Hoverable` component to get isHovered, and use `pressed` state from from the `Pressable`.

To achieve this we can change the `TabSelectorItem` render to

```
        <Hoverable>
            {(isHovered) => (
                <Animated.View style={[styles.flex1]}>
                    <PressableWithFeedback
                        accessibilityLabel={title}
                        style={({ pressed }) => [
                            { backgroundColor },
                            style,
                            !interactive && styles.cursorDefault,
                            StyleUtils.getButtonBackgroundColorStyle(getButtonState(focused || isHovered, pressed, success, disabled, interactive), true),
                            (isHovered || pressed) && hoverAndPressStyle,
                            shouldGreyOutWhenDisabled && disabled && styles.buttonOpacityDisabled,
                        ]}

                        wrapperStyle={[styles.flex1]}
                        onPress={onPress}

........
```

`style` default props value is `styles.tabSelectorButton`

If we also need to replace the Icon, we can use

```
                        {({ pressed }) => (
                            <>
                                <Icon
                                src={icon}
                                fill={StyleUtils.getIconFillColor(getButtonState(focused || isHovered, pressed, success, disabled, interactive), true)}
                            />

```

This logic is adopted from `MenuItem` component

### What alternative solutions did you explore? (Optional)
N/A

**Comment by garrettmknight** [comment] 2023-09-11 09:22
Convo is still going on tool tips/hover.

**Comment by garrettmknight** [comment] 2023-09-15 10:37
Refer to this thread for more info on fixing this: https://expensify.slack.com/archives/C049HHMV9SM/p1694605007634609?thread_ts=1693396751.536049&cid=C049HHMV9SM

**Comment by wildan-m** [comment] 2023-09-18 07:21
@Ollyws, @garrettmknight Proposal [Updated](https://github.com/Expensify/App/issues/26648#issuecomment-1709891162).

Change Log:
Adjust the styling behavior to slack convo, add alternative solution

**Comment by garrettmknight** [comment] 2023-09-19 03:39
>This is a big change requiring a lot of modifications to coupled and animating components. @garrettmknight requesting to please raise compensation.
That's fair, bumping to $1k

**Comment by wildan-m** [comment] 2023-09-22 09:31
@Ollyws, @garrettmknight, my [main proposal updated](https://github.com/Expensify/App/issues/26648#issuecomment-1709891162).

Change log:

Use hovered status from pressable. `Hoverable` component does not play nice with `AnimatedPressableWithFeedback` component, the hovering result is not reliable with these reproduction steps:
1. select tab 0
2. wait about 2 second
3. move the mouse to tab 1
4. select tab 1
5. wait about 2 seconds
6. move the mouse to tab 0

quiet often the hover not working as expected

**Comment by wildan-m** [comment] 2023-09-26 14:50
> @wildan-m Will removing the createAnimatedComponent when using PressableWithFeedback here not reduce performance? The benefit we have now is that the entire PressableWithFeedback is running on the UI thread after we convert it to an Animated component.

Thank you for this helpful feedback, I agree that It can degrade the performance.

@Ollyws, @garrettmknight, my [main proposal updated](https://github.com/Expensify/App/issues/26648#issuecomment-1709891162).

Change Log:

Instead of separating the Pressable and Animated.View, I'd recommend creating an inner `View` to handle hover background.

This way we can handle unreliable hover background as [mentioned here](https://github.com/Expensify/App/issues/26648#issuecomment-1731111414) and also not sacrifice performance.

**Comment by wildan-m** [comment] 2023-09-28 01:29
@Ollyws [the PR](https://github.com/Expensify/App/pull/28357) is ready to review.

**Comment by wildan-m** [comment] 2023-09-28 03:10
> This adds a volatile state change on an event (mouseover) that can happen quickly quite a few times in a short span of time. This will cause performance regression if the device running is not powerful.

@neonbhai do you have any source?

**Comment by wildan-m** [comment] 2023-09-28 04:24
@Ollyws my [proposal updated](https://github.com/Expensify/App/issues/26648#issuecomment-1709891162).

In case @neonbhai statements are accurate and the solution to this issue is quite straightforward, I hope the first one who can complete the issue without a bug will be selected.
Change log:
Added alternative 2 solution

This is what was suggested in https://github.com/Expensify/App/issues/26648#issuecomment-1738330090but wrapped with a view and remove flex1 in the pressable wrapper to handle iOS native issue.

this is what happened without wrapping
![image](https://github.com/Expensify/App/assets/11847279/24b35f96-31c0-4142-8239-d14e7404a016)

**Comment by garrettmknight** [comment] 2023-09-28 06:00
@Ollyws can you chime in on whether @wildan-m or @neonbhai 's solution will work best?

**Comment by garrettmknight** [comment] 2023-10-18 20:48
**Summary of payments**
- Urgency Bonus: No
- Reporter: @Nathan-Mulugeta $50 paid via Upwork
- Contributor: @wildan-m $1000 paid via Upwork
- Reviewer: @Ollyws requires $1000 payment [offer](https://www.upwork.com/nx/wm/offer/26915529)

@Ollyws can you complete the checklist and I'll pay you out?

**Comment by garrettmknight** [comment] 2023-10-23 19:38
Cool, paid and closing!

**Closed by garrettmknight** 2023-10-23 19:38 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
