### ISSUE TITLE
[$500] Web - Password protected PDF password field stays in focus even on error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27281] opened 2023-09-12 18:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send password protected PDF
4. Open the PDF and click on 'enter the password'
5. Press enter to submit and observe that even though error was triggered, field still has focus

## Expected Result:
App should lose focus from the password field after error as we do for all the fields throughout the app

## Actual Result:
App keeps the focus on the password field after error in password protected PDF preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8a363c2f-28f9-4138-8e48-9b2614a07551

https://github.com/Expensify/App/assets/93399543/4a4bbde7-0c5a-49f8-8a73-748b01371f69

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694280104869819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ece584d36e5bf8f</li>
        <li>Upwork Job ID: 1701667882556108800</li>
        <li>Last Price Increase: 2023-09-12</li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-09-12 19:06
## Proposal 

### Problem 
 Password protected PDF password field stays in focus even on error
 
### Root cause
We are not removing focus from input when there is a error

### changes
Blur textinput if there is a errortext.

 const errorText = useMemo(() => {
        if (isPasswordInvalid) {
            textInputRef.current.blur()
            return translate('attachmentView.passwordIncorrect');
        }
        if (!_.isEmpty(validationErrorText)) {
            textInputRef.current.blur()
            return translate(validationErrorText);
        }
        return '';
    }, [isPasswordInvalid, translate, validationErrorText]);

**Comment by studentofcoding** [comment] 2023-09-13 06:12
> It seems expected behavior since this change #26025

Yup, agree,  I also think it's expected behaviour

**Comment by dhanashree-sawant** [comment] 2023-09-13 06:21
It is inconsistent with other fields throughout the app

**Comment by garrettmknight** [comment] 2023-09-14 11:25
This feels pretty consistent in this password case. We're keeping focused on the only thing you can interact with and you'd want to retype your password or leave. Closing.

**Closed by garrettmknight** 2023-09-14 11:25 UTC
Labels: External, Daily, Help Wanted, Bug
