### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500] Web - Attachment - Console error shows up when closing the PDF view while it is loading

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31209] opened 2023-11-10 20:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to chat.
3. Click + > Add attachment.
4. Upload a PDF.
5. After upload is done, click on the PDF.
6. While the PDF is still loading, close the PDF view with ESC key.

## Expected Result:
No console error will show up.

## Actual Result:
Console error 'Uncaught (in promise) Error: Worker was terminated' shows up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/78da9ca5-270a-4db1-9261-7884341096b9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cba1c5a184872fe2</li>
        <li>Upwork Job ID: 1723074341611794432</li>
        <li>Last Price Increase: 2023-11-10</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 27707739</li>
</ul></li>
    </ul>
</details>

**Comment by vladimir-8** [comment] 2023-11-11 01:51
This error is emitted by `react-pdf` library. I found it's already been reported in their repository: https://github.com/wojtekmaj/react-pdf/issues/1062 I guess the best solution is to patch it there

**Comment by shubham1206agra** [comment] 2023-11-11 10:25
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Web - Attachment - Console error shows up when closing the PDF view while it is loading

### What is the root cause of that problem?

This is because `loadingTask.destroy()` is not working correctly which is explained in detail in https://github.com/mozilla/pdf.js/issues/11595.

### What changes do you think we should make in order to solve the problem?

We can patch the unmounting method in the Document by adding 
```js
if (this.loadingTask) {
    this.loadingTask._worker.destroy();
    this.loadingTask.destroy();
}
```
in the `react-pdf` library.

### What alternative solutions did you explore? (Optional)

**Comment by narefyev91** [comment] 2023-11-13 11:12
Proposal from @shubham1206agra looks good to me https://github.com/Expensify/App/issues/31209#issuecomment-1806776560
Based on the comments in react-pdf - issue still reproduced in v7 - my concern will be to make a patch and apply changes to  fix error in console.
🎀 👀 🎀 C+ reviewed

**Comment by trjExpensify** [comment] 2023-11-13 14:26
Over to you Franc for the secondary proposal review!

**Comment by francoisl** [comment] 2023-11-16 23:46
LGTM

**Comment by trjExpensify** [comment] 2023-11-30 18:50
👋 Checklist time please! :).

**Comment by trjExpensify** [comment] 2023-12-04 11:35
Thanks, agreed. @shubham1206agra paid!

**Closed by trjExpensify** 2023-12-04 11:35 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by AlfredMadere** [comment] 2024-06-21 16:23
I'm still getting this exact issue on v9. I am not loading the workerSrc locally as shown below due to some annoying project requirements. Is it possible that this fix only works if you use the local script method?

```typescript
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`
```
