### ISSUE TITLE
Request/Split bill - Page crash after money request/Split bill while offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14136] opened 2023-01-09 15:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Preconditions: Login to yuriy.turbo+ch7@gmail.com/Aa111111
1. Open Desktop App or Chrome Web
2. Go Offline
3. Make money request or Split bill
4. Restart the App if issue is not reproduced and try again

## Expected Result:
The user should be able to use Money request or Split bill while offline without any issues

## Actual Result:
Page crash after money request/Split bill while offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Web / Chrome
- [ ] Android app
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.50.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** yuriy.turbo+ch7@gmail.com/Aa111111

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211339791-c4c0379b-97c1-48be-a696-2f213289e4db.mp4

https://user-images.githubusercontent.com/93399543/211439209-66c0bbae-d7f3-4499-b3f9-ae95051ee92c.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad625fac3be8adfa</li>
        <li>Upwork Job ID: 1613530024908873728</li>
        <li>Last Price Increase: 2023-01-12</li>
    </ul>
</details>

**Comment by amyevans** [comment] 2023-01-09 15:43
Self-assigning. I tried a few times on prod to repro and couldn't, so I'm still curious to see if you can repro @adelekennedy (and if there are more reliable repro steps to do so). But I see the line of code where the error is from the video and should be able to add some defense against a crash. Will look into this one a bit closer later today or early tomorrow.

**Comment by adelekennedy** [comment] 2023-01-09 17:12
@amyevans it's not reproducible for me either, adding the needs reproducing label for additional 👀

**Comment by amyevans** [comment] 2023-01-12 13:34
Sounds good!

**Comment by amyevans** [comment] 2023-01-23 14:13
Have more pressing priorities, will circle back to this as soon as possible though (but it's just clean up at this point).

**Comment by sobitneupane** [comment] 2023-02-02 16:37
I believe this issue is not reproducible any longer. This issue was handled in https://github.com/Expensify/App/issues/14355 by [this PR](https://github.com/Expensify/App/pull/14400).

**Comment by amyevans** [comment] 2023-02-02 16:51
Oh nice, thanks for calling attention to that @sobitneupane. This issue definitely looks to be a dupe of https://github.com/Expensify/App/issues/14355, which has a fixed deployed as of last week. Closing.

**Closed by amyevans** 2023-02-02 16:51 UTC
Labels: Weekly, Internal, Needs Reproduction, Bug
