### ISSUE TITLE
[HOLD for task cleanup] LOW: Update `childVisibleActionCount` of parent report action when canceling child thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31630] opened 2023-11-21 15:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Go to any Chat
2. Send a Message
3. Right-click on the Message you sent and click on the reply in thread
4. Click on the plus button on the composer > Assign task
5. Write a title and Click on Next
6. Confirm task
7. Go to the main chat and notice that the Reply number is shown.
8. Go back to the tread
9. Click on the task to go to the task report page
10. Cancel the task
11. Return to the thread and notice that the task is not shown. No reply is shown in the tread
12. Go to the main chat and notice that the Reply number is still shown.

## Expected Result:
The reply number is not shown when there is no reply in the thread

## Actual Result:
Reply number is shown with no reply in the thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/571bea83-a637-4e21-aee3-2a00ae8ab9dc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a799300c7807dc5</li>
        <li>Upwork Job ID: 1726979634179018752</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-21 15:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Reply number is shown for no replies on the thread

### What is the root cause of that problem?
When canceling task in the child thread, we don't update `childVisibleActionCount` of parent report action

### What changes do you think we should make in order to solve the problem?
We need to update `childVisibleActionCount` of parent report action when cancelling task in both optimistic data and BE response

### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment] 2023-12-13 15:36
Looks like this is a BE issue. Posting in #vip-vsb to see if this is worth fixing.

**Comment by quinthar** [comment] 2024-01-22 01:38
Nice find.   We're holding on all these task issues for now, but we'll tackle this when we loop back to clean up tasks.  Thanks!

**Comment by mvtglobally** [comment] 2024-01-30 04:55
Issue not reproducible during KI retests. (First week)

**Comment by strepanier03** [comment] 2024-02-01 21:22
We should have a BZ assigned to every bug issue in E/App so that we have some ownership. I'm going to reassign the BZ label.

**Comment by joekaufmanexpensify** [comment] 2024-02-01 22:14
I too cannot reproduce this anymore. Closing as this is now fixed!

**Closed by joekaufmanexpensify** 2024-02-01 22:14 UTC
Labels: Engineering, Daily, Internal, Bug, Hot Pick
