### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] Track - Self-DM chat appears briefly when track expense from FAB

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46674] opened 2024-08-01 16:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/tests/view/4798300&group_by=cases:section_id&group_order=asc&group_id=309130)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to FAB> Track expense> Finish the flow
2. Go to self-DM chat> Select Do nothing from actionable whispers
3. Open any other chat
4. Go back to FAB> Track Expense

## Expected Result:
Self-DM chat should not appears when select option to track expense

## Actual Result:
Self-DM chat appears briefly when track expense from FAB even other chat was open before this action

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/54530f14-452d-4345-82e9-fd528c3cf8fe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184fba06192689bb7</li>
        <li>Upwork Job ID: 1819379087245531554</li>
        <li>Last Price Increase: 2024-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103403398</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser / @isabelastisser</details>

**Comment by lanitochka17** [comment] 2024-08-01 16:44
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-08-01 16:44
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by OfstadC** [comment] 2024-08-01 20:56
Didn't get to this today. Reassigning as i'm out tomorrow and Monday. Happy to take back on Tuesday if no forward movement before then

**Comment by bernhardoj** [comment] 2024-08-02 04:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The self DM shows briefly when open track expense.

### What is the root cause of that problem?
The self DM shows because the matching route here for the track expense page is the self DM report.
https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L188

It checks the screen params and if reportID is found and valid, then the report is returned.
https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L153-L156

Track expense page reportID params is the self DM reportID. Because the matching route is found, we push it to the adapted routes,
https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L207-L209

which will be later used if isCentralPaneAndBottomTabMandatory or isFullScreenNavigatorMandatory is true, which is true in our case.
https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/libs/Navigation/linkTo/index.ts#L135-L142

### What changes do you think we should make in order to solve the problem?

We can include the money request screen in `RHP_SCREENS_OPENED_FROM_LHN` list so it won't be added to the stack when navigating to the money request page, including track expense.
https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L189-L193
https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L207-L209

```
const RHP_SCREENS_OPENED_FROM_LHN = [SCREENS.MONEY_REQUEST.CREATE, ...];
```

**Comment by isabelastisser** [comment] 2024-08-02 14:25
#vip-vsb [status](https://expensify.slack.com/archives/C066HJM2CAZ/p1721760866963099?thread_ts=1721729395.916419&cid=C066HJM2CAZ).

**Comment by c3024** [comment] 2024-08-04 11:45
@bernhardoj 's [proposal here](https://github.com/Expensify/App/issues/46674#issuecomment-2264511818) LGTM!

🎀 👀 🎀 C+ Reviewed

**Comment by bernhardoj** [comment] 2024-08-06 03:32
PR is ready

cc: @c3024

**Comment by c3024** [comment] 2024-08-19 05:45
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #37421 
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37421/files#r1721237982
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think this bug could not have been identified earlier so no discussion was started.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Press FAB > Track Expense
2. Press back
3. Verify there is no self-DM page

**Comment by isabelastisser** [comment] 2024-08-19 17:08
@puneetlath do you agree with the regression test proposal?

**Comment by bernhardoj** [comment] 2024-08-20 01:57
Requested in ND.

**Comment by isabelastisser** [comment] 2024-08-20 15:08
Payment summary:

$250 to @c3024 for C+ review. Paid in Upwork.
$250 to @bernhardoj for proposal. Requested in ND, `PENDING`.

**Comment by isabelastisser** [comment] 2024-08-20 15:29
All set!

**Closed by isabelastisser** 2024-08-20 15:29 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-21 11:02
$250 approved for @bernhardoj
