### ISSUE TITLE
[$500] Web - "You do not have the permission to do the requested action" error on completing task from 2 accounts in offline mode.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27372] opened 2023-09-13 16:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Assign a task to account B from A
2. Open task report in both accounts
3. Go offline in both accounts
4. Complete task from both accounts
5. Go online
6. Observe the error in account that has completed the task after the first one

## Expected Result:
Task report should not display any errors.

## Actual Result:
Task report displays an error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f1f1876a-e211-457e-b7b2-75cdb3b9f56d

https://github.com/Expensify/App/assets/93399543/b11d45ae-6057-4ec7-a191-2e871f1dc4a4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694371674667319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7fd343924858bd0</li>
        <li>Upwork Job ID: 1701992736708005888</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by akamefi202** [comment] 2023-09-13 19:40
Looks like a backend issue. The backend returns error on CompleteTask API call if the task is completed already.
As a result, the user sees the error message.

**Comment by grgia** [comment] 2023-09-14 02:27
cc @thienlnam This looks like a tasks BE bug?

**Comment by imranaalam** [comment] 2023-09-14 04:24
---

**Problem Statement:**  
When two accounts go offline, complete the same task, and then come online to sync their actions, the backend returns an error for the second account's `CompleteTask` API call if the task is already completed by the first account. This leads to an error message being displayed to the user of the second account.

**Root Cause:**  
The backend is not designed to handle redundant actions gracefully. When the `CompleteTask` API endpoint is invoked for a task that's already completed, it treats it as an error rather than acknowledging the redundant action.

**Proposed Solution:**  
Modify the `CompleteTask` API endpoint on the backend. If a request is made to complete a task that is already completed, the backend should return a successful response indicating that the task's status is already as desired. Optionally, the response can include a message stating "Task already completed" to inform the frontend. On the frontend side, this can either be silently acknowledged or a non-intrusive message can be displayed to the user.

**Backend Example Code (Express.js)**:
```javascript
const express = require('express');
const app = express();
const PORT = 3000;

app.put('/CompleteTask/:taskId', (req, res) => {
    const taskId = req.params.taskId;

    // Fetch the task from the database (pseudo-code)
    const task = getTaskFromDatabase(taskId);

    if (!task) {
        return res.status(404).json({ message: 'Task not found.' });
    }

    if (task.status === 'completed') {
        // Task is already completed, return a successful response
        return res.status(200).json({ message: 'Task already completed.' });
    }

    // Complete the task (pseudo-code)
    completeTaskInDatabase(taskId);

    return res.status(200).json({ message: 'Task successfully completed.' });
});

app.listen(PORT, () => {
    console.log(`Server started on http://localhost:${PORT}`);
});
```

**Frontend Example Code (Fetch API)**:
```javascript
function completeTask(taskId) {
    fetch(`/CompleteTask/${taskId}`, {
        method: 'PUT',
    })
    .then(response => response.json())
    .then(data => {
        if (data.message === 'Task already completed.') {
            // Option 1: Silently acknowledge
            console.log('Task was already completed.');

            // Option 2: Display a non-intrusive message to the user
            // alert('Task already completed by another user.');
        } else {
            console.log('Task successfully completed.');
        }
    })
    .catch(error => {
        console.error('Error completing task:', error);
    });
}
```

**Alternative Solution:**  
Implement an idempotent design for the `CompleteTask` API. This ensures that making the same API call multiple times will have the same effect as making it once. Alongside this, the frontend can be equipped with a caching mechanism to remember actions performed offline. Before syncing, it checks the current state of tasks. If the frontend identifies that the task is already in the desired state, it can skip making the redundant API call.

**Comment by ArekChr** [comment] 2023-09-14 11:04
I think this should be fixed on backend side

**Comment by lschurr** [comment] 2023-09-18 08:22
@grgia @thienlnam - what shall we do with this one?

**Comment by thienlnam** [comment] 2023-09-18 08:37
Yeah maybe if the task is already completed, we just return a successful response instead of throwing an error. I can update the BE

**Comment by lschurr** [comment] 2023-09-21 00:20
Any update @thienlnam?

**Comment by thienlnam** [comment] 2023-09-25 03:06
Just created a PR that I'll get into review soon

**Comment by lschurr** [comment] 2023-09-28 01:38
Bump @thienlnam

**Comment by thienlnam** [comment] 2023-09-28 01:44
I actually had to revert the PR as it added some regressions - will have to create another PR soon

**Comment by thienlnam** [comment] 2023-10-04 05:30
I'm mostly OOO this week, going to bump this to a weekly since it's low priority but I have a draft PR in the works https://github.com/Expensify/Auth/pull/8805

**Comment by thienlnam** [comment] 2023-10-05 07:54
Same same as above ^

**Comment by thienlnam** [comment] 2023-10-12 17:31
Same same, draft PR is here https://github.com/Expensify/Auth/pull/8805 working on it today / tommorow

**Comment by lschurr** [comment] 2023-10-16 15:48
Any update @thienlnam?

**Comment by thienlnam** [comment] 2023-10-16 18:18
Currently in review!

**Comment by lschurr** [comment] 2023-10-19 15:49
Looks like the PR was merged: https://github.com/Expensify/Auth/pull/8805

**Comment by lschurr** [comment] 2023-10-19 15:49
Are there any payments for this one? Maybe just the bug reporter? @thienlnam

**Comment by thienlnam** [comment] 2023-10-19 22:13
Yup, just the bug reporter here. Let's also confirm that the original bug is fixed from the internal PR

**Comment by lschurr** [comment] 2023-10-23 16:53
Great! Offer sent.

**Closed** 2023-10-26 15:49 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
