### ISSUE TITLE
[$500] Android - It is impossible to scan the receipt with the camera, an error is displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34750] opened 2024-01-18 17:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the App
2. Login with any account
3. Tap on FAB -> Request money -> Scan
4. Tap on shot camera button

## Expected Result:
You can take a photo and continue the process

## Actual Result:
Camera error displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1d9d1b14-9c0e-4b11-a552-6d96ca5f29bb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dcae17afc7313b12</li>
        <li>Upwork Job ID: 1748038364144406528</li>
        <li>Last Price Increase: 2024-01-18</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 28120363</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-18 17:43
[#wave5-free-submitters](https://expensify.enterprise.slack.com/archives/C05DWUDHVK7)

**Comment by aswin-s** [comment] 2024-01-18 22:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Error displayed while trying to scan a receipt on Android

### What is the root cause of that problem?

Error is displayed while trying to capture image with camera before requesting for permissions. Even though a message requesting CameraPermission is shown above the shutter button, tap on the shutter button itself is not prevented.

https://github.com/Expensify/App/blob/31b19eaaf00c23492c6e5132b9501abdeb210e78/src/pages/iou/request/step/IOURequestStepScan/index.native.js#L296

This causes camera.takePicture to get invoked even before camera ref is set, resulting in the error

https://github.com/Expensify/App/blob/31b19eaaf00c23492c6e5132b9501abdeb210e78/src/pages/iou/request/step/IOURequestStepScan/index.native.js#L256-L268

### What changes do you think we should make in order to solve the problem?

Though is it quite evident from the message that camera permission is required, the shutter button is not disabled. 
The issue could be resolved by invoking the `askForPermissions` method instead of `capturePhoto` if permission is not available. This feels more natural as the intension of user tapping the shutter button is to capture an image anyway.

```tsx

<PressableWithFeedback
    role={CONST.ACCESSIBILITY_ROLE.BUTTON}
    accessibilityLabel={translate('receipt.shutter')}
    style={[styles.alignItemsCenter]}
    onPress={cameraPermissionStatus !== RESULTS.GRANTED? askForPermissions:  capturePhoto}
>
    <ImageSVG
        contentFit="contain"
        src={Shutter}
        width={CONST.RECEIPT.SHUTTER_SIZE}
        height={CONST.RECEIPT.SHUTTER_SIZE}
    />
</PressableWithFeedback>

```


### What alternative solutions did you explore? (Optional)
None

**Comment by ikevin127** [comment] 2024-01-19 02:08
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Camera error displayed when tapping the shutter button of the camera on scan request.

## What is the root cause of that problem?

When `cameraPermissionStatus` is **not** granted, we see the screen that says `Camera access is required to take pictures of receipts.` with a Continue button that if pressed calls the `askForPermissions` function.

While the permission is **not** granted, if the user will press the shutter button, the `capturePhoto` function is called which attempts to take a photo but because the camera is not available we get the error.

## What changes do you think we should make in order to solve the problem?

In order to make things as convenient as possible for the user, without extra click / press I suggest to have a `useEffect` that runs once which if the permission is not granted already, calls the `askForPermissions` function - this will prompt the camera permission everytime the user navigates to the scan request screen, unless granted.

```javascript
    useEffect(() => {
        if (cameraPermissionStatus === RESULTS.GRANTED) {
            return;
        }
        
        askForPermissions();
    }, []);
```

This way every button has 1 function and the permission prompt will show up as long as the permission is not granted everytime the user opens the scan request screen - this will clear things up as there won't be any confusion as to why the error shows when the user is pressing the shutter button right after they denied / dismissed the camera permission prompt.

## Videos

<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/56457735/b9414aa2-4c53-4e9c-9d83-92f2cbfe7c29

</details>

**Comment by alexpensify** [comment] 2024-01-19 19:51
@thesahindia - Can you please review the proposals here? Thanks!

**Comment by alexpensify** [comment] 2024-01-22 19:08
@thesahindia - any update here?

**Comment by alexpensify** [comment] 2024-01-24 17:51
@thesahindia - keep us posted if you can review this one or let me know if you can't, so we can find a replacement. Thanks!

**Comment by aldo-expensify** [comment] 2024-01-24 21:32
As a summary, I understand that we have the following proposals:

- @aswin-s 's [proposal](https://github.com/Expensify/App/issues/34750#issuecomment-1899315799): Make the shutter button ask for permissions to use the camera if permissions have not been granted
- @ikevin127 's [proposal](https://github.com/Expensify/App/issues/34750#issuecomment-1899526879): On mounting, ask for permissions to use the camera. The user could deny permissions and still click the shutter causing the error, but the user should be more aware why that happened.
- @Krishna2323 's [proposal](https://github.com/Expensify/App/issues/34750#issuecomment-1899806506): I think it implements the same behaviour compared to @aswin-s 's [proposal](https://github.com/Expensify/App/issues/34750#issuecomment-1899315799), but it is just different way to code it.

I wanted to confirm that @ikevin127 's proposal behaviour is really what we want and not @aswin-s 's proposed behaviour, so I'll ask in slack

**Comment by aldo-expensify** [comment] 2024-01-24 21:50
I was pointed out that in web mobile we ask immediately for permissions, so I think we should just be consistent with that.

**Comment by ikevin127** [comment] 2024-01-24 22:18
> without having granted permissions

This is the key here, if already granted - it won't ask again on subsequent mount.

**Comment by ikevin127** [comment] 2024-01-24 22:28
I disagree since these platform dependent details are usually handled during the PR while completing the checklist - so no worries 😁

**Comment by ikevin127** [comment] 2024-01-24 22:35
I think it's important to always respect C+ decision when it comes to the review process.

**Comment by ikevin127** [comment] 2024-01-24 23:26
This issue has nothing to do with the mWeb behaviour - it's strictly on natives.

> Expected Result: You can take a photo and continue the process.

In order to fulfil the issue's expected result - the user has to grant the camera permission again since they are on the Scan tab - we can assume they want to use the camera. This argument is a matter of how we want to approach asking for the permission.

If we were to align the native behaviour with mWeb that wound mean that on native, if the user denied the permission once or just dismissed it (which still has denied status), this would **force the user to leave the app**, go to the app settings and grant the permission from there as there's no other way since we only display the permission prompt once (like on web).

In web it's way easier to grant permissions as you don't need to leave the browser app.
My thinking is that in this case mWeb and native should not behave the same.

> the selected proposal is incorrect, it will ask for permission every time we visit scan tab

You forgot to add `unless the user granted it` 🙂

**Comment by ikevin127** [comment] 2024-01-25 00:35
PR https://github.com/Expensify/App/pull/35118 ready for review 🚀

In case my proposal ends up not being the desired solution in this case, I'm more than happy to close the PR and move forward to tackling other issues! 🤝

**Comment by aldo-expensify** [comment] 2024-01-25 20:41
Sorry, I had to log out yesterday.

Reading the conversation and thinking about it, I think the ideal behaviour would be:

1. As soon as the scan tab is opened, ask for permissions
2. Don't ask for permissions again if the user denied the first time to avoid being annoying if the user is just attaching images fro the gallery (same as webm behaviour)
3. If the user denied and after taps the shutter button, then we should prompt for permissions again. This is because it is much easier for the user to grant permissions like this than having to go to the phone settings, and the intention is clear about using the Camera.

I consider @Krishna2323 's proposal (and the alternative solution) an improvement/polish over the two other existing proposals and not an original proposal by itself.

If we agree and want to implement the behaviour stated above, this would mean to do a mix of the existing proposals.

**Comment by ikevin127** [comment] 2024-01-25 21:29
@aldo-expensify I agree!

I came to realize my solution was pretty weak and I did not really like it even after opening the PR.
Therefore I just closed the PR and ended the accepted upwork contract.

This one can go to @Krishna2323 as he seems to be very passionate about handling it 🙂
I give full permission to use any part of my proposal (if needed / useful).

Been' an honor! 🫡

**Comment by aldo-expensify** [comment] 2024-01-25 23:58
What about the following:



- Implement Krishna2323's [proposal](https://github.com/Expensify/App/issues/34750#issuecomment-1899806506), including the alternative solution so we have the behaviour described [here](https://github.com/Expensify/App/issues/34750#issuecomment-1910964516)
- Pay @Krishna2323 , @ikevin127  and @aswin-s  $250 each because I think there is significant contribution to the final solution from everyone mentioned.

**Comment by ikevin127** [comment] 2024-01-26 00:01
Absolutely cool w/ me! 🎩\t

**Comment by aldo-expensify** [comment] 2024-01-26 00:05
@ikevin127 can you modify your PR to include the changes from @Krishna2323 's [proposal](https://github.com/Expensify/App/issues/34750#issuecomment-1899806506)? 🙏

**Comment by ikevin127** [comment] 2024-01-26 00:09
> Therefore I just closed the PR and ended the accepted upwork contract.

I think you guys might've missed this line from earlier, the PR is gone (deleted, incl. branch) as I thought @Krishna2323 is going to handle this one himself.

I took on other issues in the meantime and have a few other opened PR's - therefore no capacity to take on this one really, sorry guys!

**Comment by alexpensify** [comment] 2024-01-26 18:45
Awesome, thanks!

**Comment by alexpensify** [comment] 2024-01-31 20:32
Thanks for the update!

**Comment by alexpensify** [comment] 2024-02-07 23:52
PR is in the works

**Comment by alexpensify** [comment] 2024-02-13 22:42
Weekly Update: PR is merged and making progress forward!

**Comment by ikevin127** [comment] 2024-02-20 00:37
Looks like the automation failed to set the 7-day hold for payment here since the PR https://github.com/Expensify/App/pull/35640#issuecomment-1945392415 was deployed to production 5 days ago (02/15/2024, 07:24 EET)🧐

Hold for payment date should be:
2024-02-22

cc @alexpensify

**Comment by alexpensify** [comment] 2024-02-20 15:28
@ikevin127 - thanks for flagging, I agree and have a reminder to continue the payment process in two days.

**Comment by alexpensify** [comment] 2024-02-22 16:13
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue -  @Krishna2323 , @ikevin127 and @aswin-s $250 each
-  Contributor+ that helped on the issue and/or PR - @thesahindia still working on this number because there is one GH that states regression was caused by this GH and another that states no regression here. 

Upwork Job: https://www.upwork.com/jobs/~01dcae17afc7313b12

Extra Notes regarding payment: https://github.com/Expensify/App/issues/34750#issuecomment-1911189208 that's the discussion where we decided to include feedback from multiple proposals and split up the payment.

**Comment by alexpensify** [comment] 2024-02-22 16:20
@Krishna2323 and @aswin-s - please accept the job in Upworks and I can complete the process. Thanks!

**Comment by ikevin127** [comment] 2024-02-22 16:24
@alexpensify I also need an offer for $250 as I ended the initial contract, mentioned here https://github.com/Expensify/App/issues/34750#issuecomment-1911027528.

**Comment by aswin-s** [comment] 2024-02-22 16:36
@alexpensify Accepted the offer

**Comment by alexpensify** [comment] 2024-02-23 00:01
The contributors have been paid via Upwork. I'm still working with @aldo-expensify  to confirm the payment for the C+ since there is one GH stating this PR created regression and then another GH states it did not. For now, those paid via Upwork have been paid there.

**Comment by alexpensify** [comment] 2024-02-28 00:50
I updated the summary here: https://github.com/Expensify/App/issues/34750#issuecomment-1959784159

After reviewing more, there is no clear evidence that regression was caused by this GH. @thesahindia please input a request in chat for the payment. Closing for now. 

Thanks to everyone here for figuring out a good plan.

**Closed by alexpensify** 2024-02-28 00:50 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-04-08 03:24
$500 approved for @thesahindia
