### ISSUE TITLE
Web - Emoji selector covers LHN when clicking add reaction bubble below a comment

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25395] opened 2023-08-17 13:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat.
2. React to a comment.
3. Click on the "add reaction bubble"

## Expected Result:
Emoji picker should not cover the LHN and should be shown towards right.

## Actual Result:
Emoji picker partly covers the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/2ece5051-4c63-4041-abfc-b833f274edd5

https://github.com/Expensify/App/assets/115492554/56765d7c-8996-4eec-9c7c-ab2f8b7fd31a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @c3024

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691314449495069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BartoszGrajdek** [comment] 2023-08-18 12:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Emoji picker should be moved to the right so that it doesn't cover LHN

### What is the root cause of that problem?

The root cause of the problem is how anchor for the Emoji Popover is calculated, and how it's origin is set. The popover is anchored to top right corner and facing the left side, which causes it to cover LHN.

### What changes do you think we should make in order to solve the problem?


The easiest and quickest solution (1-line change) would be to make the popover face right-hand side instead of left-hand side.

We could tweak how emoji picker origin is set, this way the position of emoji picker will be calculated properly, and it will stick to top right corner of Emoji picker button facing right-hand side. Here you can see how it is displayed after the changes:

<details>
<summary>Screen shots</summary>

![image](https://github.com/Expensify/App/assets/41169160/a427b653-fca7-4220-bd0d-53ac198cb0a4)

![image](https://github.com/Expensify/App/assets/41169160/ba8aed3f-5fda-4144-ba27-977610520090)

</details>

### What alternative solutions did you explore? (Optional)

Another way to solve this problem (which may be better in terms of UX) would be to tweak emoji popover so that it behaves just like the one in slack (screenshot below), in a nutshell it would be anchored to top left corner of Emoji picker button while facing right-hand side.

However we would need to change a little more in the code itself as it requires some customization in the way that the position of popover is calculated.

<details>
<summary>How slack emoji popover reacts (Screen shot)</summary>

![image](https://github.com/Expensify/App/assets/41169160/37e17cf3-6e66-41fb-8928-59d03cc6eef2)

Here you can see how emoji picker is anchored differently
</details>

**Comment by anyongjitiger** [comment] 2023-08-18 12:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The problem is that when we click add reaction bubble below a comment. Emoji selector covers LHN

### What is the root cause of that problem?

The root cause of the problem is here: 

https://github.com/Expensify/App/blob/6319e59c29bf7304654e4ede3c2215a6e65016bf/src/components/EmojiPicker/EmojiPicker.js#L47
Prop anchorOrigin is undefined  So it was set to the default value.
https://github.com/Expensify/App/blob/6319e59c29bf7304654e4ede3c2215a6e65016bf/src/components/EmojiPicker/EmojiPicker.js#L14
And the horizontal origin is ‘right’

### What changes do you think we should make in order to solve the problem?

We can pass in the anchorOrigin value with a horizontal origin of 'center', or simply set the default horizontal origin  to ‘center'

### What alternative solutions did you explore? (Optional)

None

### Result
![截屏2023-08-18 20 14 18](https://github.com/Expensify/App/assets/9712610/a2f0addf-646f-46c6-b2ac-a62de2946a02)

**Comment by anyongjitiger** [comment] 2023-08-18 12:31
Contributor details
Your Expensify account email: anyongjitiger@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01225df0c309fea73e

**Comment by MitchExpensify** [comment] 2023-08-18 15:14
I don't think this is a bug or one worth solving right now, closing and thanks for reporting!

**Closed by MitchExpensify** 2023-08-18 15:14 UTC
Labels: Daily, Bug
