### ISSUE TITLE
[$500] Budget - Amount for processing report and open report is computed incorrectly in #admin message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33821] opened 2024-01-01 18:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an admin of Control workspace
- The Control workspace has a category that is set up with a budget
Old Dot
1. Create expenses with category that has a budget and add them to the report until the total amount exceeds the workspace threshold
2. Submit and final approve the report
3. Create another report with some expenses with the same category
4. Submit the report without approving it
5. Create another report with some expenses with the same category
6. Leave this report in the open state
New Dot
1. Navigate to #admin room of the Control workspace.

## Expected Result:
The amount for processing report and open report in notification message in #admin room reflects the correct amount from Old Dot

## Actual Result:
The amount for processing report and open report in notification message in #admin room is different from the amount in Old Dot

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e59c7ee9-f91a-4a64-bc2e-e4f2619385cd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d208c0a80533d09</li>
        <li>Upwork Job ID: 1741889214842585088</li>
        <li>Last Price Increase: 2024-01-01</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2024-01-03 01:13
@lanitochka17 Is this "bug" part of any Regression/QA Steps? I've noticed a few "Old Dot to New Dot" bugs being reported, so just curious about this - I thought that the focus was primarily on ND. Any thoughts @fedirjh?

**Comment by jliexpensify** [comment] 2024-01-03 02:09
@MonilBhavsar [based on this thread,](https://expensify.slack.com/archives/C03U7DCU4/p1703865073587779) I'm assigning you this as it's Budgets-related.

**Comment by MonilBhavsar** [comment] 2024-01-03 05:19
Yes, thank you!

**Comment by MonilBhavsar** [comment] 2024-01-03 05:41
I can confirm it is working as expected

<img width="681" alt="Screenshot 2024-01-03 at 11 08 36 AM" src="https://github.com/Expensify/App/assets/32012005/056f3d50-c505-4661-b9fc-7805f6b59e85">

The reproduction steps here are not correct

> 2. Submit and final approve the report

In step 2. when you submit and final approve the report that is over the budget. We send the notification and since at that time the open report and submitted report were not created, we do not include them in the notification message. The open and submitted reports were created later in step 4 and step 6.
Instead they should be created before a report is approved with amount over budget. cc @lanitochka17 @isagoico

**Comment by jliexpensify** [comment] 2024-01-04 23:41
Hi @MonilBhavsar if this is working as expected, can this GH be closed? Thanks!

**Comment by isagoico** [comment] 2024-01-05 03:53
@jliexpensify @MonilBhavsar - Apologies for this one, the TCs that were recently added to our regression run had a mistake, I inverted some steps that caused the creation of this issue. I have already fixed TCs that had the incorrect order of steps and updated the TR update issue [here](https://github.com/Expensify/Expensify/issues/355173).

**Comment by MonilBhavsar** [comment] 2024-01-05 05:04
No worries, thanks a lot!!
We can close this now

**Closed by MonilBhavsar** 2024-01-05 05:04 UTC
Labels: External, Daily, Help Wanted, Bug
