### ISSUE TITLE
[$1000] Task - Task description is not displayed for both users

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24667] opened 2023-08-16 22:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1-First login to different accounts which two different users, one as user  A and the other as user B
2-[user A] Start chat witch user B
3-[user A] Click plus sign and open Assign task
4-[user A] Write a title and click Next button
5-[user A] Click Confirm task
6-[user B] Opens the task assigned by user A
7-Open the Description at the same time with user A and with user B.
8-[user A] Type a description and click the Save button.
9-[user B] Do not type a description and click the Save button

## Expected Result:
Must show user B the description written by user A

## Actual Result:
Show only the description to user A

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/694f9102-612e-47c2-a039-c4d19d9a6ede

https://github.com/Expensify/App/assets/78819774/dc7624d9-9a51-485d-9c0c-dee8bf7fc429

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Mauri-salazar

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691436100802139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a985484f47845712</li>
        <li>Upwork Job ID: 1692267054011924480</li>
        <li>Last Price Increase: 2023-08-24</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-08-17 03:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The description is not displayed for both users when one user is trying to update the description while another is viewing the same task description.

### What is the root cause of that problem?
While two different users are attempting to edit a description for the same task, if one of the users updates the description first, a subsequent update done by the other user would overwrite the first update.

### What changes do you think we should make in order to solve the problem?
A UX flow can be implemented which prompts a user editing the description with a confirmation dialog to get an updated value for the description, if it was changed elsewhere.

This can be implemented in the TaskDescriptionPage component.

### What alternative solutions did you explore? (Optional)
None.

**Comment by Christinadobrzyn** [comment] 2023-08-17 20:07
Wow, thank you for the super thorough steps @Mauri-salazar! I can reproduce it, don't see any other jobs about this issue, adding external label

**Comment by Pluto0104** [comment] 2023-08-18 00:15
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The problem is that when we update the task description in the Expensify app to an empty string `""`, the app does not update the Onyx store with the new value.

### What is the root cause of that problem?
The root cause of the problem is that when the task description is an empty string, the backend returns an Onyx merge object with no description property. This means that the `Onyx.merge()` method does not update the description property in the Onyx store, because it only updates the properties that are specified in the merge object.

![1](https://github.com/Expensify/App/assets/136573674/9918e43c-4edc-4836-b041-ae7734c4019e)

![2](https://github.com/Expensify/App/assets/136573674/24e1b5d2-9dbe-4da8-83c3-ce76598fa2ed)

### What changes do you think we should make in order to solve the problem?
To solve this problem, we can fix it on the backend side. We should make sure that when the description is an empty string, we add description: `""` to the Onyx merge object. This way, the `Onyx.merge()` method will update the description property in the Onyx store with the new value.

### What alternative solutions did you explore? (Optional)
We can also validate the description input on the frontend side. We can prevent users from submitting an empty string as a task description, or show a warning message if they do so. This way, we can avoid sending an invalid value to the backend and keep the data consistent. However, this approach is not suitable for addressing this particular issue, as the description is considered an optional value.

**Comment by Pluto0104** [comment] 2023-08-21 15:53
> @Pluto0104 You are saying that if the user updates the description to empty string, other user won't receive it in update? It sounds to me as different issue

Hmm, can you reproduce this error when the description is not empty string?

**Comment by Christinadobrzyn** [comment] 2023-08-21 20:48
Awesome! Working on/reviewing proposals...

**Comment by Christinadobrzyn** [comment] 2023-08-23 15:39
@robertKozik would you happen to have an update on the proposal review? 

Based on the Slack [convo](https://expensify.slack.com/archives/C01GTK53T8Q/p1692628651370439) it sounds like we want to silently update the task description for all users when the description has changed. Does that align with any proposals?

**Comment by Pluto0104** [comment] 2023-08-23 15:50
@robertKozik, @Christinadobrzyn, could you please take a look [here](https://github.com/Expensify/App/issues/24667#issuecomment-1686590494)? Currently, the task description is displayed for both users if it is a non-empty string. However, when the task description is updated to an empty string, it is not working as expected. I believe this is a backend problem based on the information provided [here](https://github.com/Expensify/App/issues/24667#issuecomment-1683144766).

**Comment by robertKozik** [comment] 2023-08-23 16:13
@Pluto0104 Alright I got it. Actually now I see here two problems, one of which @Pluto0104 You pointed out:
1) TextInput is not updated for the second user when first one updated the description in the meantime
2) When description is going to be overwritten with the empty one, **the description field (the one in the chat not RHN) is not updated**

The first one is answered by proposals of @akinwale and @huzaifa-99, the later by @Pluto0104.

@Christinadobrzyn Maybe you know which one is the focal point of this issue?

**Comment by Christinadobrzyn** [comment] 2023-08-23 20:45
I'm no expert but I kinda think that 1 is the focal point as it seems to be the primary control in this issue. But let me add an engineer to the issue to see if they might have better insights.

**Comment by pecanoro** [comment] 2023-08-24 23:39
@Christinadobrzyn I can't reproduce this bug, it's updating correctly for me. Can you try to reproduce it again?

**Comment by Pluto0104** [comment] 2023-08-24 23:54
@pecanoro it's working properly when we update description to non-empty string, but in case of empty string, it's not working.
Please take a look [here](https://github.com/Expensify/App/issues/24667#issuecomment-1683144766), and [slack conversation](https://expensify.slack.com/archives/C049HHMV9SM/p1691436100802139).

**Comment by pecanoro** [comment] 2023-08-25 00:21
Yes, I set the description to an empty string and it was updating on both ends just fine. I will record a video tomorrow.

**Comment by Mauri-salazar** [comment] 2023-08-25 01:41
Excuse me, I checked that it is still playable.


https://github.com/Expensify/App/assets/106186325/fc3d27ec-7af4-48c9-b679-187220cc59ff

**Comment by pecanoro** [comment] 2023-08-25 14:22
Ok, I managed to reproduce it finally, it only seems to happen to me if the description was empty already, not if initially had set one. Either way, after reading this [comment](https://github.com/Expensify/App/issues/24667#issuecomment-1690247540), it seems only #2 seems to be a problem? If user A updates the description, user B gets the new one.

**Comment by pecanoro** [comment] 2023-08-25 15:04
@huzaifa-99 Gotcha! I don't think we should fix that, it would be extremely disruptive if you are typing and suddenly it gets updated. Also because changes that something like that will happen are extremely low.

I am creating a PR to fix problem #2.

**Comment by Christinadobrzyn** [comment] 2023-09-15 19:09
watching PR - https://github.com/Expensify/Web-Expensify/pull/38634

**Comment by pecanoro** [comment] 2023-09-19 02:16
@Christinadobrzyn Ohh this was fixed a while ago, we can pay the reporting bonus to @Mauri-salazar and close it.

**Comment by Christinadobrzyn** [comment] 2023-09-19 17:59
Yep! sounds good! 

@Mauri-salazar can you please accept my Upwork offer - https://www.upwork.com/jobs/~0134f3baed94be65b7 so I can pay you?

**Comment by Mauri-salazar** [comment] 2023-09-19 18:34
@Christinadobrzyn Ready accepted, thank you very much

**Comment by Christinadobrzyn** [comment] 2023-09-19 19:17
Okay, paid @Mauri-salazar in Upwork. Let me know if there's anything else to do here or if we can just close it!

**Comment by Mauri-salazar** [comment] 2023-09-19 21:16
@Christinadobrzyn I checked it and the error was resolved.

**Comment by Christinadobrzyn** [comment] 2023-09-19 22:04
Sounds good! @pecanoro can you confirm only the reporter needs to be paid for this GH?

**Comment by pecanoro** [comment] 2023-09-20 02:10
Yes, that's it, closing!

**Closed by pecanoro** 2023-09-20 02:10 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
