### ISSUE TITLE
[HOLD for payment 2024-04-05] [$250] [Categories] - Category row is not grayed out entirely when disabled offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38262] opened 2024-03-13 23:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an admin of Collect workspace.

1. Go to staging.new.expensify.com.
2. Go to Settings > Workspaces > Collect workspace.
3. Go to Categories.
4. Go offline.
5. Click on the checkbox of any category.
6. Click dropdown menu > Disable categories (or Enable if disabled).

## Expected Result:
The entire category row will appear grayed out.

## Actual Result:
Only the status column is grayed out.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/8cba2407-b627-483c-8bbc-66ccbf32aa42

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013df311dce09e48bb</li>
        <li>Upwork Job ID: 1768698540734349312</li>
        <li>Last Price Increase: 2024-03-15</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by akinwale** [comment] 2024-03-14 00:50
I believe this behaviour is intentional since it's the state value (enabled / disabled) that's changing. @ArekChr can confirm.

**Comment by nkdengineer** [comment] 2024-03-14 05:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Only the status column is grayed out.

### What is the root cause of that problem?
When we disable the category, we update `pendingFields` of category and I think it's expected that we update the pendingField like this

https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/libs/actions/Policy.ts#L2654-L2656

but we don't get this as `pendingAction` here so the category row isn't grayed out 
https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L84


### What changes do you think we should make in order to solve the problem?
We should update the `pendingAction` here by fallback `value.pendingFields.enable`

```
pendingAction: value.pendingAction || value?.pendingFields?.enabled,

```

https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L84

OPTIONAL: In the feature we can have other `pendingFields` like name, ... We can create a utils like `getCategoryPendingAction` and use it in all places that we want to get the pendingAction of category. We can do the same for tag or other policy features
### What alternative solutions did you explore? (Optional)
NA

**Comment by ikevin127** [comment] 2024-03-14 13:05
> **ArekChr** can confirm.

Offending PR https://github.com/Expensify/App/pull/37734 - which is still within the regression period (deployed to staging 17h ago, see https://github.com/Expensify/App/pull/37734#issuecomment-1995595509).

**Comment by luacmartins** [comment] 2024-03-14 15:13
@mountiny do you have a link to the discussion?

**Comment by mountiny** [comment] 2024-03-15 17:59
Sorry it was this one https://expensify.slack.com/archives/C036QM0SLJK/p1710425480916719 seems like this is already se up so we can proceed with implementation

**Comment by mountiny** [comment] 2024-03-15 18:12
This is a minor change so taking the opportunity to reflect the reward.

Can you also make the same change for tags if possible

**Comment by mountiny** [comment] 2024-03-15 18:19
I think @Krishna2323 proposal looks good, I will assign you and please do.

I believe we already have the taxes and distance rates in main, can you copy the same approach for those too please?

**Comment by cubuspl42** [comment] 2024-03-18 11:01
It's Monday, in the US the workday hasn't even started yet 🙂

**Comment by mountiny** [comment] 2024-03-18 22:08
@Krishna2323 the video you have shown is correct, if that's not how it behaves for tags, then that is a bug

**Comment by mountiny** [comment] 2024-03-18 22:13
@Krishna2323 yes, tags should follow what categories do now

When you open RHP, all tags/ categories should de deselected.

**Comment by mountiny** [comment] 2024-03-18 22:14
> I found that when we update category in offline mode the row is disabled, do we need to do that for tags also? Haven't added recordings since we might want to fix this as well.

regarding this, we are still discussing internally, its not in scope of this PR

@Krishna2323 could you however align the tags behaviour with categories in your PR please? Thank you

**Comment by trjExpensify** [comment] 2024-03-21 10:50
Where we at with this? What's the ETA on the PR? Thanks!

**Comment by cubuspl42** [comment] 2024-03-21 10:58
@trjExpensify 

In review. ETA today/tomorrow. Do you know whether the category UI element should be completely disabled when grayed out? I.e. should I be able to click/tap it to display the details, or maybe change the category name?

**Comment by luacmartins** [comment] 2024-03-21 13:35
I think users should be able to interact with it and update other values, unless the row is in a pending delete state, in which case it should be disabled

**Comment by trjExpensify** [comment] 2024-03-21 21:17
Agree with what Carlos said!

**Comment by cubuspl42** [comment] 2024-03-22 08:25
I raised this topic, because it felt odd; in most cases, we _can_ edit the thing that has pending offline actions. But we didn't change anything in this aspect in our PR, so maybe let's consider this out of scope?

**Comment by trjExpensify** [comment] 2024-03-22 12:17
>@luacmartins, are you sure we don't need to disabled the tags/categories when updated offline,

Are you specifically asking in the pending create state or the pending delete case? Because they are handled differently. 

If you add a category offline, you can edit its settings as well. Generally the philosophy here is that we should let people "work" offline as much as possible. So blocking them from being able to edit the category they just added goes against that. It would be somewhat pointless to allow you to add categories when offline if we didn't. 

If you delete a category offline, you can't edit its settings. It's treated as if you deleted it when online, the only difference is that it's still displayed as a breadcrumb while its pending to confirm the action was successful.

**Comment by mountiny** [comment] 2024-03-29 22:31
$250 to @Krishna2323 and $250 to @cubuspl42

**Comment by mountiny** [comment] 2024-03-29 22:31
Puneet has been originally assigned using the bug label so adding you to handle payments here, thank you!

**Comment by puneetlath** [comment] 2024-04-04 19:49
@cubuspl42 friendly reminder on the checklist so that we can pay tomorrow.

**Comment by cubuspl42** [comment] 2024-04-05 08:31
- The PR that introduced the bug has been identified. Link to the PR:
    -  https://github.com/Expensify/App/pull/37734
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - https://github.com/Expensify/App/pull/37734#issuecomment-2039234485
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
  - N/A

**Comment by puneetlath** [comment] 2024-04-05 15:42
All paid. Thanks everyone!

**Closed by puneetlath** 2024-04-05 15:42 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
