### ISSUE TITLE
[$1000] [MEDIUM] Scan - No red dot for transaction thread in LHN when scanning fails

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34827] opened 2024-01-19 18:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/31448
## Action Performed:
1. Go to workspace chat
2. Create a scan request with receipt that will fail the scanning
3. Wait for the scanning to fail
4. Click on the preview to open report page
5. Click on the preview to open details page

## Expected Result:
- The transaction thread should have the RBR on the LHN for the submitter.
- The transaction thread should **not** have the RBR on the LHN for the admin.
- The expense report should **not** have the RBR on the LHN for either user

## Actual Result:
Both expense report and details page do not show red dot in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/de240dda-8f67-4d86-babe-83e5914a0238

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2581b13bb117eee</li>
        <li>Upwork Job ID: 1757711391539257344</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2024-01-19 18:18
We should fix this but I dont think its that major to be a deploy blocker now cc @cead22

**Comment by cead22** [comment] 2024-01-19 20:21
Agreed, let's HOLD this one too, since I think it may be fixed by a fix for a bug we just found in the main violations PR -- context here https://expensify.slack.com/archives/C01GTK53T8Q/p1705693401154309?thread_ts=1705692222.233999&cid=C01GTK53T8Q

**Comment by laurenreidexpensify** [comment] 2024-01-22 11:13
on hold for bug mentioned above, not overdue

**Comment by marcochavezf** [comment] 2024-02-05 19:20
Hi @cead22, this is the [PR](https://github.com/Expensify/App/pull/34838) we were holding for this issue, correct?

**Comment by cead22** [comment] 2024-02-05 20:35
It looks like it, so we can remove the HOLD here if this is still happening

> Both expense report and details page will show red dot in LHN

That said, the expected result is that
- The transaction thread should have the RBR on the LHN for the submitter.
- The transaction thread should **not** have the RBR on the LHN for the admin.
- The expense report should **not** have the RBR on the LHN for either user

**Comment by marcochavezf** [comment] 2024-02-09 17:04
I'm already assigned to other wave issues. Dropping it in wave6 channel https://expensify.slack.com/archives/C02MW39LT9N/p1707498241279089

**Comment by laurenreidexpensify** [comment] 2024-02-13 12:09
Just to be clear - is this one `internal` @marcochavezf @cead22 ?

**Comment by cead22** [comment] 2024-02-13 17:41
This one's external

**Comment by laurenreidexpensify** [comment] 2024-02-16 16:58
increased bounty

**Comment by Tony-MK** [comment] 2024-02-16 22:38
I don't think this is reproducible anymore.

**Comment by bernhardoj** [comment] 2024-02-17 06:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Based on the new expected result, I see only the last one that doesn't match, that is the red dot shown in the expense report.

### What is the root cause of that problem?
We have a logic here to get the report errors that include expense/IOU reports which will show the red dot error if the user is the owner.
https://github.com/Expensify/App/blob/20af9e52db6031dea6d0086a6692682eb15e422a/src/libs/OptionsListUtils.ts#L487-L490

This was first added in https://github.com/Expensify/App/pull/27494.

### What changes do you think we should make in order to solve the problem?

If we want to change it, then we can simply remove the condition or just the expense report if we want to keep the IOU one.

_(IOU report only) Related to the red dot, I see that the red dot is shown in the report preview, DM chat LHN, and the request preview even though they are not the owner. I think the red dot shouldn't be shown if they aren't the owner because they can't edit it. We need to check the owner, but I didn't include the details here as it could be expected and probably out of scope_

**Comment by Tony-MK** [comment] 2024-02-18 01:32
### Please re-state the problem that we are trying to solve in this issue.

Scan - No red dot for transaction thread in LHN when scanning fails

### What is the root cause of that problem?

In trying to reproduce this bug, the following expectations from https://github.com/Expensify/App/issues/34827#issuecomment-1928050071 were fulfilled:
- The transaction thread should have the RBR on the LHN for the submitter.
- The transaction thread should not have the RBR on the LHN for the admin.

However the third expectation, "The expense report should not have the RBR on the LHN for either user", is not fulfilled.

https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L481-L493

The third expectation is caused by the third condition in the [`getAllReportErrors`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L481-L493) function since the function does not consider `report?.ownerAccountID === currentUserAccountID`.

Therefore, the third condition will pass because the [`ReportUtils.hasSmartscanError`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/ReportUtils.ts#L4819) returned true for the `reportActions`. 

### What changes do you think we should make in order to solve the problem?

In the third condition, check if the report is an expense report, to prevent `reportActionErrors.smartscan` to be being set to expense reports that didn't meet the `report?.ownerAccountID === currentUserAccountID`  conditions.

Hence, let's use the [`ReportUtils.isExpenseReport`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/ReportUtils.ts#L618) function as such:

```
else if (!(ReportUtils.isExpenseReport(report) && report?.ownerAccountID === currentUserAccountID) && ReportUtils.hasSmartscanError(Object.values(reportActions ?? {})))
```

https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L491-L493

**Comment by Tony-MK** [comment] 2024-02-18 02:00
### Please re-state the problem that we are trying to solve in this issue.

Scan - No red dot for transaction thread in LHN when scanning fails

### What is the root cause of that problem?

In trying to reproduce this bug, the following expectations from https://github.com/Expensify/App/issues/34827#issuecomment-1928050071 were fulfilled:
- The transaction thread should have the RBR on the LHN for the submitter.
- The transaction thread should not have the RBR on the LHN for the admin.

However the third expectation, "The expense report should not have the RBR on the LHN for either user", is not fulfilled.

https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L481-L493

The third expectation is caused by the third condition in the [`getAllReportErrors`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L481-L493) function since the function does not consider `report?.ownerAccountID === currentUserAccountID`.

Therefore, the third condition will pass because the [`ReportUtils.hasSmartscanError`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/ReportUtils.ts#L4819) returned true for the `reportActions`. 

### What changes do you think we should make in order to solve the problem?

In the third condition, check if the report is an expense report, to prevent `reportActionErrors.smartscan` to be being set to expense reports that didn't meet the `report?.ownerAccountID === currentUserAccountID`  conditions.

Hence, let's use the [`ReportUtils.isExpenseReport`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/ReportUtils.ts#L618) function as such:

```
else if (!ReportUtils.isExpenseReport(report) && ReportUtils.hasSmartscanError(Object.values(reportActions ?? {})))
```

https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L491-L493

**Comment by Tony-MK** [comment] 2024-02-18 02:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Scan - No red dot for transaction thread in LHN when scanning fails

### What is the root cause of that problem?

In trying to reproduce this bug, the following expectations from https://github.com/Expensify/App/issues/34827#issuecomment-1928050071 were fulfilled:
- The transaction thread should have the RBR on the LHN for the submitter.
- The transaction thread should not have the RBR on the LHN for the admin.

However the third expectation, "The expense report should not have the RBR on the LHN for either user", is not fulfilled.

https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L481-L493

The third expectation is caused by the third condition in the [`getAllReportErrors`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L481-L493) function since the function does not consider `report?.ownerAccountID === currentUserAccountID`.

Therefore, the third condition will pass because the [`ReportUtils.hasSmartscanError`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/ReportUtils.ts#L4819) returned true for the `reportActions`. 

### What changes do you think we should make in order to solve the problem?

In the third condition, check if the report is an expense report, to prevent `reportActionErrors.smartscan` to be being set to expense reports that didn't meet the `report?.ownerAccountID === currentUserAccountID`  conditions.

Hence, let's use the [`ReportUtils.isExpenseReport`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/ReportUtils.ts#L618) function as such:

```
else if (!ReportUtils.isExpenseReport(report) && ReportUtils.hasSmartscanError(Object.values(reportActions ?? {})))
```

https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L491-L493

**Comment by laurenreidexpensify** [comment] 2024-02-19 10:32
@allroundexperts couple of proposals to review ^^

**Comment by allroundexperts** [comment] 2024-02-20 04:00
Still reviewing these. Need a little more time. Will provide an update shortly.

**Comment by allroundexperts** [comment] 2024-02-20 06:34
Can we confirm if even for IOU reports, we don't want to show the RBR in LHN if there is a smart scan error? @marcochavezf @cead22

**Comment by allroundexperts** [comment] 2024-02-20 06:38
@bernhardoj Removing the second condition won't work in this case since the third condition would simply kick in, causing the RBR to show up.

@Tony-MK Removing only the last condition would result in showing of an RBR for the expense report if the user is admin which we don't want. As such, I don't think that your proposal would work.

**Comment by allroundexperts** [comment] 2024-02-20 06:38
Still looking for a more accurate proposal.

**Comment by bernhardoj** [comment] 2024-02-20 07:07
The third condition won't kick in because it will return false if it's not a report preview action. The condition is used to show the RBR on the chat report if there is a split bill or report preview error.
https://github.com/Expensify/App/blob/0797c0ac556e9d3822f6121e4a9fd3943d990a2c/src/libs/ReportUtils.ts#L4767-L4770

**Comment by allroundexperts** [comment] 2024-02-20 07:11
Ah, I did not notice this condition. Given this, your proposal should be good.

We just need to confirm if we need to show the RBR for IOU report or not.

🎀 👀 🎀 C+ reviewed

**Comment by cead22** [comment] 2024-02-20 18:17
If by IOU report you mean reports holding p2p request between users and outside of a workspace, then those won't get violations. Only money requests on workspaces get violations. Let me know if that answers your question

**Comment by Tony-MK** [comment] 2024-02-20 22:17
@allroundexperts, I think you might be confusing the two Prospal.

My proposal did not suggest removing the third condition. 

Kindly, could you re-review my proposal?

**Comment by Tony-MK** [comment] 2024-02-20 22:20
@allroundexperts, I think you might be confusing the two proposals.

My proposal did not suggest removing any conditions. 

Kindly, could you re-review my proposal?

Thanks

**Comment by Tony-MK** [comment] 2024-02-20 22:21
Hi @cead22, Just a quick question.  

In a p2p request, is it expected to show the RBR of IOUs for only the requestor to be notified? 🤔

**Comment by Tony-MK** [comment] 2024-02-20 22:21
Hi @cead22, just a quick question.  

In a p2p request, is it expected to show the RBR of IOUs for only the requestor to be notified? 🤔

Thank you.

**Comment by cead22** [comment] 2024-02-20 23:23
- In a p2p request that is outside of a workspace, there should be no RBR for violations showing for any user
- In a money request made in the context of a workspace, the RBR should show for everyone on the report preview, and theh money request preview. And the RBR on the LHN should only be shown to the person making the request

**Comment by mvtglobally** [comment] 2024-02-21 02:30
Issue not reproducible during KI retests. (First week)

**Comment by laurenreidexpensify** [comment] 2024-02-21 09:08
I am closing based on the above comment that this is no longer reproducible

**Closed by laurenreidexpensify** 2024-02-21 09:08 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by eVoloshchak** [comment] 2024-02-26 01:24
Hey folks, this is still reproducible in https://github.com/Expensify/App/issues/37044
Should we handle it there or re-open this issue?

**Comment by allroundexperts** [comment] 2024-02-27 07:48
We should re-open this. cc @laurenreidexpensify
