### ISSUE TITLE
[$250] For the failed smartscan LHN shows workspace chat with RBR for approver even though receipt not displayed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40150] opened 2024-04-11 19:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.62-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712769270599409

## Action Performed:
Prerequisite: As an employee request money to an approver (Submit two receipts,One legit and one failed smart smartscan)

1.Log in as an admin
2.Open the report with two expenses and approve as admin
3. As employee delete the expense where smartscan failed
## Expected Result:
After step 2 as admin able to see the failed smartscan expense in the workspace chat
After step 3 employee able to delete the expense and no UI break

## Actual Result:
After step 3:Failed smartscan expense not displayed and RBR on the workspace chat in the LHN.The expense displayed in old dot.
For employee the failed smartscan expense moved back to the state where it's only visible to me (like when a smartscan was in progress), even though the scan had already failed. 

After step 4:When delete the expense (smartscan failed) it seems to have broken the workspace chat for both employee and admin,  just see the skeleton UI above  the deleted expense, and anything above that won't load.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image](https://github.com/Expensify/App/assets/38435837/85cc7b7c-2516-4798-a468-a2ba15b94098)

https://github.com/Expensify/App/assets/38435837/fd7044c4-b84f-4f39-8a20-30ea3fc0cf84

https://github.com/Expensify/App/assets/38435837/7efe4b75-2c42-4c81-9fdb-d2a797fd67f0

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0187175888a80d2284</li>
        <li>Upwork Job ID: 1778536545544392704</li>
        <li>Last Price Increase: 2024-05-16</li>
    </ul>
</details>

**Comment by nkdengineer** [comment] 2024-04-12 08:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After step 3:Failed smartscan expense not displayed and RBR on the workspace chat in the LHN.The expense displayed in old dot.
For employee the failed smartscan expense moved back to the state where it's only visible to me (like when a smartscan was in progress), even though the scan had already failed.

### What is the root cause of that problem?
When a smart scan request fails, it's still whisper action and it doesn't appear from approver's side. But in `hasSmartScanError`, we don't exclude this action to check the error so RBR shows in LHN although it's not displayed.

https://github.com/Expensify/App/blob/c7d692662d069ef8d9c756833767c47e1f7410a2/src/libs/ReportUtils.ts#L5438


### What changes do you think we should make in order to solve the problem?
We should add the check here to exclude the report action that isn't displayed in the screen. We can use `ReportActionsUtils.shouldReportActionBeVisible` function which already handles this case.

```
return reportActions.some((action, key) => {
        if (!ReportActionsUtils.isSplitBillAction(action) && !ReportActionsUtils.isReportPreviewAction(action) && !ReportActionsUtils.shouldReportActionBeVisible(action, key)) {
            return false;
        }
```


https://github.com/Expensify/App/blob/c7d692662d069ef8d9c756833767c47e1f7410a2/src/libs/ReportUtils.ts#L5438

### What alternative solutions did you explore? (Optional)
NA

**Comment by isabelastisser** [comment] 2024-04-15 17:13
I am waiting for proposals.

**Comment by isabelastisser** [comment] 2024-04-19 17:26
No proposals yet.

**Comment by eh2077** [comment] 2024-04-24 05:30
@isabelastisser Should we ask a retest for this issue to see if it's still reproducible?

**Comment by isabelastisser** [comment] 2024-04-24 17:09
@eh2077, yes!

@Puneet-here, can you still reproduce this?

**Comment by puneetlath** [comment] 2024-04-25 18:21
@isabelastisser I don't have a scenario where this is happening currently to be able to test. Can you send me an expense in your NewDot test workspace? One or two real ones and then one where SmartScan is guaranteed to fail?

**Comment by isabelastisser** [comment] 2024-04-29 13:25
I will test this later today!

**Comment by mvtglobally** [comment] 2024-05-01 13:41
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment] 2024-05-01 14:15
Sorry for the delay here, @puneetlath! I will prioritize this today.

**Comment by eh2077** [comment] 2024-05-04 16:32
Not overdue, this is not reproducible in last retest. Waiting for the next retest.

**Comment by isabelastisser** [comment] 2024-05-07 01:31
Not overdue.

**Comment by isabelastisser** [comment] 2024-05-09 16:02
@eh2077 @mvtglobally, can you confirm that this is no longer reproducible? Thanks!

**Comment by isabelastisser** [comment] 2024-05-14 14:27
Bump @mvtglobally

**Comment by isabelastisser** [comment] 2024-05-17 19:23
I'm closing this because it's not reproducible anymore. @mvtglobally, please reopen it if you can reproduce this again in the future. Thanks!

**Closed by isabelastisser** 2024-05-17 19:23 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
