### ISSUE TITLE
[Awaiting Payment 9th August] [$250] Accounting - Accounting isn't enabled in ND if a connection is made in OD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45080] opened 2024-07-09 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44743
## Action Performed:
Precondition: Have a workspace in OD with a connection to QBO or Netsuite. Haven't logged in to ND yet.
1. Navigate to https://staging.new.expensify.com/
2. Log in with an account that has a workspace in OD
3. Navigate to Workspace settings - More features
4. Enable "Accounting"

## Expected Result:
Accounting should be enabled

## Actual Result:
Accounting isn't enabled in ND if a connection is made in OD. The connection is visible when Accounting is enabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d6664f03-a97b-43a6-983a-fafa4f13a564

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e7910738bf73906</li>
        <li>Upwork Job ID: 1811348357918542670</li>
        <li>Last Price Increase: 2024-07-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment] 2024-07-10 17:47
👋 @hayata-suenaga @aldo-expensify @lakchote! Can I get an opinion on whether this is FE or BE?

**Comment by lakchote** [comment] 2024-07-11 06:52
> 👋 @hayata-suenaga @aldo-expensify @lakchote! Can I get an opinion on whether this is FE or BE?

I'd say this is FE. https://github.com/Expensify/App/blob/a19ef9889c85991414943da1515abe811c05e31d/src/pages/workspace/WorkspaceMoreFeaturesPage.tsx#L87

**Comment by trjExpensify** [comment] 2024-07-11 10:34
Cool, moving it on external.

**Comment by NJ-2020** [comment] 2024-07-15 07:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Accounting isn't enabled in ND if a connection is made in OD
### What is the root cause of that problem?
When we made a connection for QB inside the OD, the `areConnectionsEnabled` property doesn't get set to true by the BE, so when we go to ND, the FE checks if the `areConnectionsEnabled` is true, but it will return false because when we connect to QB inside OD, the BE doesn't change the value of this property `areConnectionsEnabled` to true.
https://github.com/Expensify/App/blob/a19ef9889c85991414943da1515abe811c05e31d/src/pages/workspace/WorkspaceMoreFeaturesPage.tsx#L87
### What changes do you think we should make in order to solve the problem?
Inside this line
https://github.com/Expensify/App/blob/a19ef9889c85991414943da1515abe811c05e31d/src/pages/workspace/WorkspaceMoreFeaturesPage.tsx#L87
We can check if `policy.areConnectionsEnabled`  is true or the `policy.connections` is not empty and we need to check that also for the below code:
https://github.com/Expensify/App/blob/77d95c54b3b4d9d9eb7db560f150137de433f657/src/pages/workspace/WorkspaceMoreFeaturesPage.tsx#L150-L159
&
https://github.com/Expensify/App/blob/77d95c54b3b4d9d9eb7db560f150137de433f657/src/pages/workspace/WorkspaceInitialPage.tsx#L109
&
https://github.com/Expensify/App/blob/77d95c54b3b4d9d9eb7db560f150137de433f657/src/pages/workspace/withPolicyConnections.tsx#L31
& this
https://github.com/Expensify/App/blob/77d95c54b3b4d9d9eb7db560f150137de433f657/src/libs/PolicyUtils.ts#L388-L394
and enable the connection feature by checking i.e `policy?.areConnectionsEnabled || !isEmptyObject(policy?.connections)`

I've tried and it's working very well
### Result

https://github.com/user-attachments/assets/edc3d99d-188b-4db8-b315-00c217239f32

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-07-15 23:37
@mollfpr what do you think of this proposal?

**Comment by NJ-2020** [comment] 2024-07-16 01:39
Also Instead of doing this `policy?.areConnectionsEnabled || !isEmptyObject(policy?.connections)` we can do this `policy?.areConnectionsEnabled ? policy?.areConnectionsEnabled : !isEmptyObject(policy?.connections)`

**Comment by mollfpr** [comment] 2024-07-17 06:30
Checked the proposal from @NJ-2020 and it's looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by lakchote** [comment] 2024-07-17 11:29
@NJ-2020's proposal LGTM.

**Comment by NJ-2020** [comment] 2024-07-18 03:17
I will let you know as soon as it's done
I've applied to the Upwork job

**Comment by mvtglobally** [comment] 2024-07-19 03:24
Issue not reproducible during KI retests. (First week)

**Comment by NJ-2020** [comment] 2024-07-19 09:15
PR is ready

cc: @mollfpr

**Comment by trjExpensify** [comment] 2024-07-19 10:47
Interesting... https://github.com/Expensify/App/issues/45080#issuecomment-2238042618

So is it reproducible?

**Comment by NJ-2020** [comment] 2024-07-19 11:20
> Interesting... [#45080 (comment)](https://github.com/Expensify/App/issues/45080#issuecomment-2238042618)
> 
> So is it reproducible?

@trjExpensify I've tried again on Expensify web and it's still reproducible

**Comment by trjExpensify** [comment] 2024-07-19 11:21
Cool 👍

**Comment by carlosmiceli** [comment] 2024-08-01 23:22
Can we close this?

**Comment by NJ-2020** [comment] 2024-08-02 03:27
@carlosmiceli Can you please accept my proposal on Upwork for payment?

**Comment by trjExpensify** [comment] 2024-08-02 12:35
Looks like the automation failed, so I'll update this issue to note the regression period has started and I've hired you in Upwork. Payment will be issued 7 days from the prod deploy, if there aren't any regressions. 

<img width="976" alt="image" src="https://github.com/user-attachments/assets/92710974-da0e-4608-bc50-239b40cabf18">

**Comment by NJ-2020** [comment] 2024-08-02 13:21
@trjExpensify Thank you

**Comment by trjExpensify** [comment] 2024-08-02 14:56
NP!

**Comment by carlosmiceli** [comment] 2024-08-02 19:50
Remove overdue, Melvin

**Comment by trjExpensify** [comment] 2024-08-05 20:26
Payment due on the 9th, Melvin.

**Comment by mollfpr** [comment] 2024-08-07 07:43
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR was found.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Create a new workspace in ND or use any workspace that doesn't have the **Accounting** feature enabled
2. Go to OD select the workspace, go to the Connections tab, click Connect to Quickbooks
3. Go back to New Dot and open the **More features** page
4. Verify the **Accounting** feature is enabled and the connection to Quickbooks is a success
5. 👍 or 👎

**Comment by trjExpensify** [comment] 2024-08-09 18:02
Thanks! Payment summary as follows:

- $250 to @mollfpr for the C+ review (go ahead and request!)
- $250 to @NJ-2020 for the bug fix (paid)

Regression test issue created. Closing!

**Closed by trjExpensify** 2024-08-09 18:02 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-12 16:34
$250 approved for @mollfpr
