### ISSUE TITLE
[HOLD for payment 2023-09-12] [HOLD for payment 2023-09-11] [$500]  Request money - Enter key does not move to next page on big number pad page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26588] opened 2023-09-02 23:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26520
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money
3. Enter an amount
4. Hit Enter on the keyboard

## Expected Result:
You can press enter on both, amount and Distance request page to continue to a next step

## Actual Result:
Request money flow is not proceeded to the next page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b26859d3-d24c-41e0-818e-41720dcadddf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tony-MK** [comment] 2023-09-03 01:09
Seems to be fixed because I unable to reproduce it on staging and production environments.

**Comment by napster125** [comment] 2023-09-03 13:46
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Request money - Enter key does not move to next page on big number pad page.
### What is the root cause of that problem?
The root cause of this problem lies within the Button component, specifically in the way the Enter key listener is set up. 
https://github.com/Expensify/App/blob/52b1e3e9abaabdaf79c0eeafef5665292cf2ab9c/src/components/Button/index.js#L167-L190
Currently, this listener is only established during the `componentDidMount` lifecycle. This issue primarily occurs on the "New Request Money" page because the text field starts empty, causing the `isDisabled` property to be initially set to true, and subsequently to false as the user inputs data. However, the Button component does not respond to this change in `isDisabled` during the `componentDidUpdate` lifecycle, preventing the Enter key event from being properly handled.

It's worth noting that this issue is observed in the development environment but is not likely a regression of [commit](https://github.com/Expensify/App/commit/5b8cd86677b74544699dd364cb1e32b94efa2457), as the behavior of the Button component may be expected.

### What changes do you think we should make in order to solve the problem?
To resolve this issue, I recommend adding the same logic for setting up the Enter key listener in the `componentDidUpdate` lifecycle when `isDisabled` changes. This modification ensures consistent behavior regardless of the initial state of `isDisabled`.

```
componentDidMount() {
    this.setupEnterKeyListener();
}
componentDidUpdate(prevProps) {
    if (prevProps.isDisabled === this.props.isDisabled || this.props.isDisabled) {
        return;
    }
    this.setupEnterKeyListener();
}
componentWillUnmount() {
    // Cleanup event listeners
    if (!this.unsubscribe) {
        return;
    }
    this.unsubscribe();
}
```
### What alternative solutions did you explore? (Optional)
n/a

### Result

https://github.com/Expensify/App/assets/136437976/e386530c-3146-4f5f-a1ce-efd4afe16f83

**Comment by mountiny** [comment] 2023-09-03 13:50
@mkhutornyi I think your solution sounds good and I would prefer it over @napster125 proposed way as we dont want to mess with `Button` component logic right now give its such heavily used component.

Can you describe how you gonna get the isActiveTab? 

> remove pressOnEnter prop from DistanceRequest's button

this will make it work for other pages, but then it does not work on the Distance request page.

**Comment by mountiny** [comment] 2023-09-03 13:52
I think I will just remove the pressOnEnter now because I am not sure if its trivial to get the tab index. I think we can live without the Enter working on the distance given it will be mainly used on mobile.

**Comment by napster125** [comment] 2023-09-03 13:57
@mountiny it's impossible because this line will prevent the enter key event when isDisabled is true.

https://github.com/Expensify/App/blame/52b1e3e9abaabdaf79c0eeafef5665292cf2ab9c/src/components/Button/index.js#L178

**Comment by mountiny** [comment] 2023-09-03 14:00
@napster125 what is impossible specifically?

**Comment by napster125** [comment] 2023-09-03 14:01
@mountiny if so, your PR won't fix this issue. without `pressOnEnter`, we can't move to next page.

**Comment by b4s36t4** [comment] 2023-09-03 14:02
> we can't move to next page.

Even if we click?

**Comment by napster125** [comment] 2023-09-03 14:02
> @napster125 what is impossible specifically?

This is from my [proposal](https://github.com/Expensify/App/issues/26588#issuecomment-1704311195).
> Currently, this listener is only established during the componentDidMount lifecycle. This issue primarily occurs on the "New Request Money" page because the text field starts empty, causing the isDisabled property to be initially set to true, and subsequently to false as the user inputs data. However, the Button component does not respond to this change in isDisabled during the componentDidUpdate lifecycle, preventing the Enter key event from being properly handled.

**Comment by napster125** [comment] 2023-09-03 14:03
> > we can't move to next page.
> 
> Even if we click?

No, I mean when we press enter key.

**Comment by mountiny** [comment] 2023-09-03 14:05
> we can't move to next page.

Yeah I know:

> I think I will just remove the pressOnEnter now because I am not sure if its trivial to get the tab index. I think we can live without the Enter working on the distance given it will be mainly used on mobile.

I think that is better given the urgency, basically the flow we need for the conference will be people on their phones mainly so if the enter does not work on the distance page, thats fine, but we prefer to fix this on the other pages.

I would then let this issue to be exported to figure out a general solution which will enable enter on all pages so feel free to think about that

**Comment by napster125** [comment] 2023-09-03 14:07
@mountiny if so, we don't need to remove pressOnEnter.

**Comment by mountiny** [comment] 2023-09-03 14:10
https://github.com/Expensify/App/blob/447d2169845a3304bd6be1be05fd80a958191ca5/src/pages/iou/ReceiptSelector/NavigationAwareCamera.js#L15-L77

yeah we can do something like this

@mkhutornyi could you update your proposal with more details and video showing it works correctly when switching through the tabs too?

**Comment by mountiny** [comment] 2023-09-03 14:11
Given the deploy blocker I am just proceeding with as quick fix as possible for the behaviour which is the closest to expected one, we can make a better solution with more time I am sure.

**Comment by mountiny** [comment] 2023-09-03 14:40
@thesahindia Could you review the proposals and help us decide which one is the best general solution for the money request flows without risking regressions on the Button component. Thanks

**Comment by napster125** [comment] 2023-09-03 15:15
@parasharrajat @mkhutornyi so do you mean current enter key event is triggered on distance tab?

**Comment by napster125** [comment] 2023-09-03 15:17
@parasharrajat did you test your solution?

**Comment by napster125** [comment] 2023-09-03 15:23
@mountiny I didn't change the logic of the button component; I added some logic. Also, in my opinion, the active tab is not involved in this issue. It's not triggering the 'enter' event on the distance tab.

https://github.com/Expensify/App/assets/136437976/f045545e-8ac8-49bf-8ba7-bacb2d6c1ae9

**Comment by mountiny** [comment] 2023-09-03 18:37
Fixed in staging, keeping this as a normal issue

**Comment by dylanexpensify** [comment] 2023-09-13 09:18
Reviewing!

**Comment by dylanexpensify** [comment] 2023-09-19 08:25
Ah got it - @parasharrajat so to confirm: 
- We need to pay you for internal review of PR in deploy blocker?
- We haven't selected a proposal yet for this issue? cc @thesahindia 

Is that right?

**Comment by mountiny** [comment] 2023-09-19 08:41
What is the bug still left here to solve?

**Comment by mountiny** [comment] 2023-09-19 08:51
Ok, @dylanexpensify maybe we could create a new ticket for this issue so we can keep stuff separate and cleaner.

**Comment by dylanexpensify** [comment] 2023-09-19 15:14
Done ^

**Comment by dylanexpensify** [comment] 2023-09-19 15:16
@parasharrajat mind applying here: https://www.upwork.com/jobs/~019e7a2b44273824ea

**Comment by dylanexpensify** [comment] 2023-09-22 14:40
@parasharrajat yes [here](https://github.com/Expensify/Expensify/issues/318132)!

**Comment by b4s36t4** [comment] 2023-09-25 07:37
@mountiny I think you can close this as there's another issue created for tracking the main issue. #28022

**Comment by mountiny** [comment] 2023-09-25 14:28
thanks! Feel free to reopen if closing is not the best path forwards

**Closed by mountiny** 2023-09-25 14:28 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by dylanexpensify** [comment] 2023-10-09 17:03
Payment summary:

- contributor+: @parasharrajat $500

**Comment by JmillsExpensify** [comment] 2023-10-09 17:04
$500 payment approved for @parasharrajat based on BZ summary.
