### ISSUE TITLE
[HOLD for payment 2023-11-07] [$500] Web - App crash on device toolbar toggle

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30278] opened 2023-10-24 16:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @sourcecodedeveloper 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698075798349259

## Action Performed:
1. Login to https://staging.new.expensify.com/
2. Press F12 to open console
3. Click on toggle device toolbar

## Expected Result:
App is resized to selected device

## Actual Result:
The App crashes

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

[web.webm](https://github.com/Expensify/App/assets/93399543/5b3fa3e8-9b7d-4ace-8814-bca132bd57b0)

https://github.com/Expensify/App/assets/93399543/596a4cb8-7909-42a3-9172-a65c4895aaec

</details>

<details>
<summary>MacOS: Desktop</summary>

  

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013db618c7bafaf3c8</li>
        <li>Upwork Job ID: 1716860148517441536</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by brunovjk** [comment] 2023-10-24 17:17
@kbecciv I can't reproduce it, it works perfectly here, do you have any idea why? Thanks.

local:
![local](https://github.com/Expensify/App/assets/95647348/21041eb3-9446-43f0-a4a4-e4256ef6e8dd)

stag:
![stag](https://github.com/Expensify/App/assets/95647348/7acffe71-97d0-4138-9c53-db0be6a5afc6)

**Comment by FitseTLT** [comment] 2023-10-24 17:19
It happens when you switch from wide view to mobile view 👍

**Comment by situchan** [comment] 2023-10-24 17:43
@kacper-mikolajczak is already working on this - https://github.com/Expensify/App/issues/16161#issuecomment-1777523317
cc: @youssef-lr

**Comment by brunovjk** [comment] 2023-10-24 17:51
> wide view

That's strange, I try what you said and I still can't reproduce it. @FitseTLT You did it?

**Comment by brunovjk** [comment] 2023-10-24 17:51
> It happens when you switch from wide view to mobile view 👍

That's strange, I try what you said and I still can't reproduce it. @FitseTLT You did it?

**Comment by yh-0218** [comment] 2023-10-24 18:06
This error comes from `BoundsObserver` of `BaseTooltip`

**Comment by iiredalert** [comment] 2023-10-24 21:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When switching device screen size the application crashes at <BoundsObserver .../> in BaseTooltip.js

### What is the root cause of that problem?

The _childRef.current in BoundsObserver is set to null due to the rendered element from the BoundsObserver's render() function being destroyed.

### What changes do you think we should make in order to solve the problem?
The logic in @react-ng/bounds-observer is fairly straight forward and doesn't change often.  We can implement our own equivalent that simply ignores and does nothing if the callback or childref are undefined. 

### What alternative solutions did you explore? (Optional)

**Comment by youssef-lr** [comment] 2023-10-25 15:35
cc @kacper-mikolajczak @cubuspl42 , what do you guys think about the proposal above?

**Comment by iiredalert** [comment] 2023-10-26 13:59
Could it be related to the library using https://react.dev/reference/react/cloneElement ?  I am still trying to figure out why it needs to clone the element and it doesn't just render it.

We could also add a check to see if children.ref is defined before rednering the BaseTooltip.  This will prevent the error from happening but the mouse pointer and tooltips disappear are not rendered until we turn off the device toggle mode in chrome.
```
    // Skip the tooltip and return the children if the text is empty,
    // we don't have a render function or the device does not support hovering
    if ((_.isEmpty(text) && renderTooltipContent == null) || !hasHoverSupport || !children.ref) {
        return children;
    }
```

**Comment by kacper-mikolajczak** [comment] 2023-10-26 18:48
> I am still trying to figure out why it needs to clone the element and it doesn't just render it.

@iiredalert By using `cloneElement` library "hijacks" the child's `ref` prop so then it can be used internally by `BoundsObserver` ([here is an actual usage](https://github.com/react-ng/bounds-observer/blob/2ff5fff1aedb8451c01829c84757ebcdb97edc14/src/index.tsx#L121)).

**Comment by kacper-mikolajczak** [comment] 2023-10-26 19:08
Thanks for sparking the discussion guys - while I was responding to your comments something struck me. 

### Investigation

The app crash is not caused by any layout changes - Chrome changes the input mode whenever we toggle the device toolbar.

Here is a recording showing that the app does not crash on desktop input mode but does on mobile:

https://github.com/Expensify/App/assets/62747088/e8fa2718-191a-43e4-bb6f-9c6dc9b1eac0

### Solution

In order to fix this we need to, in early return of `Hoverable` component:

```tsx
    if (!DeviceCapabilities.hasHoverSupport()) {
        return child;
    }
```

 hijack the ref of a children as we do in the regular return:
 
 ```tsx
    if (!DeviceCapabilities.hasHoverSupport()) {
        return React.cloneElement(child, {
            ref: (el) => {
                ref.current = el;
                assignRef(child.ref, el);
            },
        });
    }
```

Here is a recording of the final outcome:

https://github.com/Expensify/App/assets/62747088/b9f26cf0-486a-4e6b-a1f6-d070a1e7e764

@cubuspl42 @iiredalert Thanks a lot once again for the discussion, it was invaluable in this case 🔥 🙇 

@youssef-lr I will create a PR with a fix and link it here! 🔧

**Comment by sourcecodedeveloper** [comment] 2023-10-27 08:09
@kbecciv I sent github handle for issue reporter.

**Comment by cubuspl42** [comment] 2023-10-27 08:57
@kacper-mikolajczak It still feels like there is some issue in `BoundsObserver`, right? The path that threw the exception was not meant to be entered.

**Comment by kacper-mikolajczak** [comment] 2023-10-27 09:16
@cubuspl42 We did not pass the ref correctly from child to the BoundsObserver. If the intention is to fail fast, then it is working as expected, otherwise we could change the behaviour so it silently opt-out of detecting the bounds when no proper ref is available from children (that I guess might be the favorable for production, so we don't crash entire app). 

As a last resort, this might be configurable via props, but I am not sure if that wouldn't unnecessarily extend the complexity.

**Comment by dangrous** [comment] 2023-10-27 15:26
@youssef-lr I got assigned to this (via the [PR](https://github.com/Expensify/App/pull/30462)) but it looks like you were involved before. Do you want to grab it? If not I can move forward, just let me know.

**Comment by youssef-lr** [comment] 2023-10-28 11:27
Sounds good @dangrous!

**Comment by trjExpensify** [comment] 2023-10-30 11:15
Just catching up after a couple of days out. I've removed the `Help wanted` label as this looks to have been handled by @kacper-mikolajczak in [this PR](https://github.com/Expensify/App/pull/30462).

Also to confirm, this was a known regression coming out of [here](https://github.com/Expensify/App/issues/16161)?

**Comment by sourcecodedeveloper** [comment] 2023-10-30 12:06
@trjExpensify The [PR](https://github.com/Expensify/App/pull/30462) is associated with the bug report(https://github.com/Expensify/App/issues/30278). I had posted the issue in #expensify-bugs. Please confirm from [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) if eligible for $50 reward.

**Comment by kacper-mikolajczak** [comment] 2023-10-30 14:24
HI @trjExpensify 👋  That's right, the fix was handled in the linked PR.

I am not sure where this issue was first documented. CC @youssef-lr

**Comment by trjExpensify** [comment] 2023-10-30 15:35
Okay, if it wasn't found when executing the issue linked originally, the first report of this would be in #expensify-bugs by @sourcecodedeveloper.

**Comment by youssef-lr** [comment] 2023-10-30 15:39
We encountered this 2 weeks ago and I pinged Kacper [here](https://github.com/Expensify/App/pull/29844#issuecomment-1769163247) and that's when he started working on a solution. This was first brought to my attention by @situchan when he was testing this revert [PR](https://github.com/Expensify/App/pull/29844). 

Soo I'm not sure, it was officially reported by @sourcecodedeveloper, you decide @trjExpensify :D

**Comment by situchan** [comment] 2023-10-30 15:44
I don't think bonus applies here as the research already started before bug report on slack.
Similar cases: https://github.com/Expensify/App/issues/22513#issuecomment-1640942001, https://github.com/Expensify/App/issues/23821#issuecomment-1663364426

**Comment by trjExpensify** [comment] 2023-10-30 15:47
Ah yes, then I agree. If it was found earlier while executing the related PRs then there isn't a bug report bounty to pay out.

**Comment by sourcecodedeveloper** [comment] 2023-10-30 17:11
According to [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 
Note about proposed bugs: Expensify has the right not to pay the $50 reward if the suggested bug has already been reported. Following, if more than one contributor proposes the same bug, the contributor who posted it first in the [#expensify-bugs](https://expensify.slack.com/archives/C049HHMV9SM) Slack channel is the one who is eligible for the bonus.

@trjExpensify The guidelines indicate that if more than one contributor proposes the same bug, the contributor who posted it first in the #expensify-bugs channel is the one who is eligible for the $50 reward. According to the guidelines, situchan may have first bought the issue to attention of @youssef-lr but bug report was also needed otherwise how else can the QA team decide if the bug has already been reported. I also find that holding back on $50 reporter bounty seems harsh and discourages reporting.
@mountiny Can you please utilize the 25% rule regarding the bug report bounty.

**Comment by trjExpensify** [comment] 2023-10-31 14:57
>@trjExpensify The guidelines indicate that if more than one contributor proposes the same bug, the contributor who posted it first in the #expensify-bugs channel is the one who is eligible for the $50 reward. 

Yup, I agree with that. What this means is if two contributors post in #expensify-bugs (as you often see happen) then the one that reported it first is eligible. This isn't to say that the people involved in the PR/issue that introduced the bug need to report it in #expensify-bugs as they prep a follow-up PR, typically linked to the original issue (or a deploy blocker issue created). 

That said, reviewing the convos, I can see how this one is a little more ambiguous than usual. A PR wasn't in the works and the investigation to figure out the root cause picked back up here in this issue. We probably wouldn't have got to a resolution on the timeline we did without it, so I think I'm cool with going ahead to pay this bug bounty.

**Comment by youssef-lr** [comment] 2023-11-09 20:47
@ArekChr @kacper-mikolajczak can we complete checklist please?

**Comment by ArekChr** [comment] 2023-11-13 07:36
- [x] Determine if we should create a regression test for this bug.

I believe we might not require dedicated regression tests for this issue, as it appears that it would be detected during our existing testing processes.

**Comment by trjExpensify** [comment] 2023-11-13 14:42
Yep, I tend to agree this doesn't need a regression test as a customer isn't likely to be using dev tools in the console.

@sourcecodedeveloper you need to either provide me with your Upwork account profile or apply to [this job](https://www.upwork.com/jobs/~013db618c7bafaf3c8) for me to pay you the $50 bug bounty.

**Comment by sourcecodedeveloper** [comment] 2023-11-13 17:02
@trjExpensify https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by trjExpensify** [comment] 2023-11-13 17:18
Thanks, sent an offer.

**Comment by trjExpensify** [comment] 2023-11-13 17:48
Settled, closing!

**Closed by trjExpensify** 2023-11-13 17:48 UTC
Labels: External, Daily, Awaiting Payment, Bug
