### ISSUE TITLE
[$250] skeleton view goes over the edges of the screen reported by @parasharrajat 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12744] opened 2022-11-15 19:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to the app on mobile app.
2. Navigate to any report that shows skeleton view.

## Expected result: 
Skeleton view should have right padding like the left edge of 20px.

## Actual: 
There is not padding at the right edge of the Skeleton view, it seems to go over the edge.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.2.27-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/202008564-ecfbdef1-045d-47b9-8af7-72209b19aaa2.PNG" width="40%" height="40%">
<img src="https://user-images.githubusercontent.com/43996225/202008915-356f2d80-8846-4a34-ac0c-3779a63933fe.png" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat 
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1668532881726039
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~0104a6f656912f7483
- Upwork Job ID: 1593381015543803904

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-16 13:40
**Proposal** :-


We need to increase width to `100%` in `SkeletonViewLines.js` and pass styles.mr5 to `SkeletonViewContentLoader`

https://github.com/Expensify/App/blob/652a51ac2bfbe3164b807dc5efaa4e0156ae0bdf/src/components/ReportActionsSkeletonView/SkeletonViewLines.js#L18

Like This

     <SkeletonViewContentLoader
        height={CONST.CHAT_SKELETON_VIEW.HEIGHT_FOR_ROW_COUNT[props.numberOfRows]}  
        style={styles.mr5}
    >
        <Circle cx="40" cy="26" r="20" />
        <Rect x="67" y="11" width="20%" height="8" />
        <Rect x="67" y="31" width="100%" height="8" />
        {props.numberOfRows > 1 && <Rect x="67" y="51" width="50%" height="8" />}
        {props.numberOfRows > 2 && <Rect x="67" y="71" width="50%" height="8" />}
       
    </SkeletonViewContentLoader>



Web :- 


<img width="1440" alt="Screen Shot 2022-11-16 at 6 35 29 PM" src="https://user-images.githubusercontent.com/81307212/202195412-f106633b-7439-443b-b9f1-80e9e3548a6f.png">


Native :- 

![Simulator Screen Shot - iPhone 13 Pro - 2022-11-16 at 18 34 40](https://user-images.githubusercontent.com/81307212/202195544-4e8c83e4-f358-49ed-b0d2-2dd75b342cd4.png)


mWeb :- 


![Simulator Screen Shot - iPhone 13 Pro - 2022-11-16 at 18 35 55](https://user-images.githubusercontent.com/81307212/202195602-70847854-6b8e-49e8-b549-9b5af820cc18.png)

**Comment by parasharrajat** [comment] 2022-11-16 14:01
@shawnborton Can you please review this issue?

**Comment by shawnborton** [comment] 2022-11-16 22:00
Yup, that looks good. But do we know why this happened in the first place? There must have been a regression at some point right?

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-17 03:06
@shawnborton  I looked up and and found that this initial commit in SkeletonViewLines.js https://github.com/Expensify/App/commit/0bfe1bac6fcbc0f2a304cab6811a5031d40e12da had the similar issue on android / IOS. So I believe it wasn't a regression. It might have been overlooked during development. 

The issue is there is no initial marginLeft we are setting cx="40" for the eclipse which move eclipse on x-axis and when we give `width` to Rect to `"90%" ` it creates issue in native platform so we can increase width to `"100%"` and give marinRight 20 to parent view to achieve the desired Goal of spacing at the right side so it doesn't overflow. My Proposal https://github.com/Expensify/App/issues/12744#issuecomment-1317041426

**Comment by mananjadhav** [comment] 2022-11-18 02:25
Thanks for the proposal @syedsaroshfarrukhdot. Your proposal looks good to me. I had worked on the original implementation. I wonder how I missed this. 

@grgia All yours.

🎀 👀 🎀 
C+ reviewed

**Comment by MitchExpensify** [comment] 2022-11-19 00:20
Offers sent to all! https://www.upwork.com/jobs/~0104a6f656912f7483

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-19 03:00
Thank You. Just Accepted The Offer Will Be Making A PR Today.

**Comment by mananjadhav** [comment] 2022-11-27 06:45
@MitchExpensify @grgia The PR was deployed to production 3 days back but the title wasn't updated

**Comment by mananjadhav** [comment] 2022-11-29 18:56
@MitchExpensify @grgia This is ready for payout tomorrow. Also eligible for 50% bonus to complete within 3 days.

**Comment by mananjadhav** [comment] 2022-11-30 17:23
@MitchExpensify Quick bump on the payout, and here's the offending [PR](https://github.com/Expensify/App/pull/8042) that added the bug. I worked on it so I have it handy.

**Comment by MitchExpensify** [comment] 2022-12-01 00:53
Sorry for the delay @mananjadhav, I've been sick the last few days. Paying now

**Comment by MitchExpensify** [comment] 2022-12-01 01:02
Everyone's been paid - Thank you! Will need to manually get the bug zero checklist in here as a next step (Awaiting payment label didn't do the trick)

**Comment by MitchExpensify** [comment] 2022-12-01 01:07
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@grgia @mananjadhav] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@grgia @mananjadhav] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@grgia @mananjadhav] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@MitchExpensify] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by mananjadhav** [comment] 2022-12-01 07:44
Thanks @MitchExpensify. I've linked the offending PR.

**Comment by MitchExpensify** [comment] 2022-12-02 23:07
@mananjadhav Nice! Mind taking the other [steps here](https://github.com/Expensify/App/issues/12744?notification_referrer_id=NT_kwDOAivQrbM0ODQyNjI4MjcyOjM2NDI1OTAx#issuecomment-1332998637) when you get a chance?

**Comment by MitchExpensify** [comment] 2022-12-02 23:18
In terms of a regression test, [asked here in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1670023064546889)

**Comment by mananjadhav** [comment] 2022-12-08 13:00
@grgia @MitchExpensify Quick bump here.

**Comment by MitchExpensify** [comment] 2022-12-08 18:10
Created an issue for the regression test!

**Comment by MitchExpensify** [comment] 2022-12-12 20:23
> I am not sure if we follow a template to post the comment and discussion?

there is no template

**Comment by MitchExpensify** [comment] 2022-12-12 20:24
@grgia Seeing as we only have those two checks to complete before closing this, mind handling that once done? I'm heading ooo so if you could cover closing this issue once they're checked off it'd be great!

**Comment by grgia** [comment] 2022-12-12 21:07
Done! Commented on PR and discussion [started](https://expensify.slack.com/archives/C049HHMV9SM/p1670879207542109)

**Comment by MitchExpensify** [comment] 2022-12-12 21:15
Nice! Closing out

**Closed by MitchExpensify** 2022-12-12 21:15 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
