### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Reimbursements - Track distance: inconsistency in units capitalization

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26897] opened 2023-09-06 18:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Workspace settings -> Reimbursements -> Track Distance
2. Open the "Unit" dropdown

## Expected Result:
Both "Miles" and "Kilometers" should be either capitalized or not.

## Actual Result:
"Kilometers" starts from uppercase letter, "miles" – lowercase.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.65.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/521f8984-cdb0-4ee0-8f51-5967dec0f900

https://github.com/Expensify/App/assets/93399543/ca0f6211-6b55-4aed-a475-8aa02227d041

**Expensify/Expensify Issue URL:**
**Issue reported by:** @paultsimura

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693685221686339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf988c4c1ae85fdd</li>
        <li>Upwork Job ID: 1701545859200626688</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 26724769</li>
<li>paultsimura | Reporter | 26724772</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-06 18:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Track distance: inconsistency in units capitalization
### What is the root cause of that problem?
The `common.miles` start with lowercase but `workspace.reimburse.kilometers` start with uppercase.
https://github.com/Expensify/App/blob/4d855643cbfa79f0de91fd16bde132fb6e7b5ada/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js#L44-L45
### What changes do you think we should make in order to solve the problem?
We need to make the two values start with uppercase.
For that, we can create new translated value `workspace.reimburse.miles` start with uppercase.
and/or fix `common.miles` and this values also which used it in request many distance
https://github.com/Expensify/App/blob/4d855643cbfa79f0de91fd16bde132fb6e7b5ada/src/languages/en.js#L167-L170
![Screenshot 2023-09-03 at 8 04 59 PM](https://github.com/Expensify/App/assets/41129870/d5787bf8-9b80-4671-8102-38c7a2ba08a7)


### What alternative solutions did you explore? (Optional)
we can instead make all value lowercase by update `workspace.reimburse.kilometers`

**Comment by kbecciv** [comment] 2023-09-06 18:49
Issue reported by: Pavlo Tsimura
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1693685221686339

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Kilometers and miles units have different capitalization style
### What is the root cause of that problem?
We are using inconsistent copies:
reimburse.kilometers: 'Kilometers'
common.miles: 'miles'
https://github.com/Expensify/App/blob/d7ab6407544a5a6162e42c7474c80e7cad8b28e7/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js#L42-L47
This issue was introduced in this commit: https://github.com/Expensify/App/commit/d7ab6407544a5a6162e42c7474c80e7cad8b28e7
### What changes do you think we should make in order to solve the problem?
Use one of the following:
reimburse.kilometers and reimburse.miles with capitalized letter;
common.kilometers and common.miles with all lowercase (IMO this one is preferred).
### What alternative solutions did you explore? (Optional)
N/A

**Comment by sonialiap** [comment] 2023-09-12 10:33
Standardizing on lowercase sounds good to me 👍

**Comment by burczu** [comment] 2023-09-15 12:55
Yes, [the proposal](https://github.com/Expensify/App/issues/26897#issuecomment-1708915460) from @kbecciv makes sense and we can proceed with it (with lowercase copies - https://github.com/Expensify/App/issues/26897#issuecomment-1715470250).

🎀 👀 🎀 C+ reviewed

**Comment by paultsimura** [comment] 2023-09-15 12:59
Thank you, waiting for assignment and creating the PR right after.
Also @kbecciv thank you for going an extra mile and sharing the proposal from thread 🙏

**Comment by JmillsExpensify** [comment] 2023-09-18 04:56
Agree with standardizing on lowercase.

**Comment by burczu** [comment] 2023-09-26 08:00
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [ ]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/25707
* [ ]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/25707#discussion_r1336791219
* [ ]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Didn't find
* [ ]  [@burczu] Determine if we should create a regression test for this bug.
* [ ]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@sonialiap] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by sonialiap** [comment] 2023-10-02 04:41
@paultsimura report  = $50 - paid ✔️ 
@paultsimura fix + bonus = $500 + $250 = $750 - paid ✔️ 
@burczu does not require payment (Contractor)

**Closed** 2023-10-02 04:41 UTC
Labels: External, Daily, Awaiting Payment, Bug
