### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] [MEDIUM] Expensify Cards: Transactions - Update Generic Receipts to use ReceiptBackground

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28827] opened 2023-10-04 15:25 UTC
All details needed are below, so no worries if you can't access this!

### Overview 
Currently for Scan Receipt, we have a [few options of png previews for different file types](https://github.com/Expensify/App/blob/fda0cee2a80d5195ead61ed88ced96ebdef59a54/src/libs/ReceiptUtils.js#L8-L11). We need to replace these with the new ReceiptBackground component. Basically, it should be relatively simple, replacing the existing thumbnail with [EReceiptThumbnail](https://github.com/Expensify/App/blob/5df6055eb88862b738bafae9911d71749927fa04/src/components/EReceiptThumbnail.tsx#L23)

We'll also need to update the component to support a label like the existing images - e.g. HTML, PDF, etc.

<details><summary>Design Doc</summary>
### Design Doc Section
https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.xnc4hi7wlvbg
![Image](https://github.com/Expensify/App/assets/38015950/2ffc776b-4c68-4c3b-94d9-d235207a0ed7)
</details>

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d3d6d9c663db1e73</li>
        <li>Upwork Job ID: 1709590683807113216</li>
        <li>Last Price Increase: 2024-01-09</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Contributor | 28092661</li>
<li>FitseTLT | Contributor | 28097509</li>
</ul></li>
    </ul>
</details>

**Comment by grgia** [comment] 2023-10-13 20:56
not overdue, this is just clean up and can be de-prioritized for now

**Comment by zanyrenney** [comment] 2023-10-23 09:41
What is it being de-priotised in favour of? Should we not finish it off?

If it should be de-prioritised @grgia please can you update the labels to reflect the cadence it should be worked on? e.g. change this to Monthly / put it on "hold"

**Comment by grgia** [comment] 2023-10-23 10:42
@zanyrenney weekly is the correct label

**Comment by zanyrenney** [comment] 2023-10-31 14:05
any further update here @grgia ?

**Comment by grgia** [comment] 2023-10-31 18:10
Adding monthly for now

**Comment by grgia** [comment] 2023-12-01 13:55
Unassigning for now to free up. I don't think this is worth refactoring right now

**Comment by zanyrenney** [comment] 2023-12-12 21:34
shall we put this on hold?

**Comment by dylanexpensify** [comment] 2023-12-14 20:07
No, let's find someone who can take on! Posting in update about it!

**Comment by dangrous** [comment] 2024-01-09 19:16
@mollfpr feel free to ignore, we already have @narefyev91 on this one. Thanks!

**Comment by dangrous** [comment] 2024-01-09 19:37
yes!

**Comment by b4s36t4** [comment] 2024-01-09 20:24
@dangrous design doc is access denied, anyone give access?
mail: maheshvagicherla99438@gmail.com

**Comment by dangrous** [comment] 2024-01-09 20:40
I updated the description with (I think) all the details that are needed!

**Comment by FitseTLT** [comment] 2024-01-09 21:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LOW: Transactions - Update Generic Receipts to use ReceiptBackground

### What is the root cause of that problem?
New Feature
### What changes do you think we should make in order to solve the problem?

Currently we are using `ReceiptUtils.getThumbnailAndImageURIs` to get receipt previews when there are pending waypoints in the `transaction` so it will return receipt source if there is no pending waypoints So to move to `EReceiptThumbnail` usage we need to create a component that displays the receipt when there is no pending waypoints and display the preview according to the file type using `EReceiptThumbnail` when there are pending waypoints. 
For instance here in `DistanceEReceipt`
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/components/DistanceEReceipt.js#L70-L75
So we should do everywhere in the code base where we display the receipt previews like `MoneyRequestView` , `MoneyRequestView` etc...
### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2024-01-10 04:30
@dangrous @narefyev91 is no longer C+. You need to reassign someone else.

**Comment by situchan** [comment] 2024-01-10 04:49
> @mollfpr feel free to ignore, we already have @narefyev91 on this one. Thanks!

Maybe assign @mollfpr back

**Comment by dangrous** [comment] 2024-01-10 14:10
Oh whoops, will do! Also proposers, please note, I just added one more criteria to the issue (adding a text label option to the component to allow for matching the old style images). Please let me know if you have any questions!

**Comment by dangrous** [comment] 2024-01-10 14:51
melvin is confused; @mollfpr you're acting as C+ here - thanks!

**Comment by FitseTLT** [comment] 2024-01-10 15:31
Updated [Proposal](https://github.com/Expensify/App/issues/28827#issuecomment-1883819067) to include all the requirements.

**Comment by mollfpr** [comment] 2024-01-10 15:39
I'll finish the review in the morning!

**Comment by dangrous** [comment] 2024-01-12 15:35
hey @mollfpr how is the review going? Thanks!

**Comment by mollfpr** [comment] 2024-01-12 16:25
Sorry for the delay! I think the [proposal](https://github.com/Expensify/App/issues/28827#issuecomment-1883819067) from @FitseTLT has most of the part the right to do it. Let's go with the proposal then!

🎀 👀 🎀 C+ reviewed!

**Comment by dangrous** [comment] 2024-01-12 20:33
Great, I think this makes sense - we'll have to get a full list of where receipt images show up in the app to make sure the new component functions well in all cases, but I think we can move forward with this implementation.

**Comment by zanyrenney** [comment] 2024-01-15 11:24
how are we getting on here @FitseTLT when do you expect the PR to be ready? cc @dangrous @mollfpr ?

**Comment by FitseTLT** [comment] 2024-01-15 11:44
Will create PR in 2 Days

**Comment by zanyrenney** [comment] 2024-01-17 12:55
Please can you link the PR when its created? It's been 2 days so assume we should get it today? @FitseTLT Thanks!

**Comment by FitseTLT** [comment] 2024-01-17 20:40
@zanyrenney Will create and link tomorrow. Thnx!!

**Comment by dangrous** [comment] 2024-01-18 15:10
Looking forward to seeing the PR today @FitseTLT !

**Comment by FitseTLT** [comment] 2024-01-18 19:33
Sorry guys for the delay, it didn't go as I planned, but hopefully will finalize it tomorrow 🙏

**Comment by zanyrenney** [comment] 2024-01-19 11:56
thanks for the update, look forward to the PR today then? @FitseTLT ?

**Comment by dangrous** [comment] 2024-01-19 18:14
Thanks @FitseTLT! Just a heads up, given that it's been a week since the initial assignment, if we can't get the PR into review by EOD today we'll likely have to look out for other options. Hopefully that won't be a problem but wanted to call it out.

**Comment by mollfpr** [comment] 2024-01-24 12:52
@dangrous @grgia I want to clarify the expectation in this issue. We want to replace the current eReceipt thumbnail with a new component with an eReceipt background.

So, the result will remain the same as the current thumbnail.

<img width="752" alt="272540944-2ffc776b-4c68-4c3b-94d9-d235207a0ed7" src="https://github.com/Expensify/App/assets/25520267/bc79aab4-8722-4844-a729-3e7e188ee465">

Am I correct?

I'm asking for clarification because the PR from @FitseTLT currently has a different result.

| Result from PR | Scan doc on Staging | Scan HTML on Staging |
|---|---|---|
| ![Screenshot 2024-01-24 at 19 46 54](https://github.com/Expensify/App/assets/25520267/46d64f09-0a4c-4797-85f6-46173863e244) | ![Screenshot 2024-01-24 at 19 47 09](https://github.com/Expensify/App/assets/25520267/74aa8aac-ffb9-4b4c-bfe5-61f3a97c1d40) | ![Screenshot 2024-01-24 at 19 47 34](https://github.com/Expensify/App/assets/25520267/f67854cc-e028-48f8-813d-191beb6c0b0f) |

On the PR, it will showng the same thumbnail and without the extension label.

**Comment by dangrous** [comment] 2024-01-24 18:21
Hey @mollfpr thanks for asking! So yes, you are correct - basically, the changes made here should result in essentially **no visible changes** from the existing behavior, but it should use a dynamically created images. So it might be slightly different in terms of color, exact alignment, etc., but it should have the receipt image and the file type, just like the screenshots you have from staging.

(Correct me if I'm wrong @grgia)

**Comment by FitseTLT** [comment] 2024-01-24 18:31
Color and size of text ??? @dangrous

**Comment by dangrous** [comment] 2024-01-24 20:32
Color, it looks like it should be the darker of the two image colors (I believe that's defined as `backgroundColor` [here](https://github.com/Expensify/App/blob/5df6055eb88862b738bafae9911d71749927fa04/src/components/EReceiptThumbnail.tsx#L47-L49)

As for text size, that's a good question, for now let's see if you can match the size in the existing components (again, it should visually be almost exactly the same), and if @Expensify/design has any alternate ideas, they are welcome!

**Comment by shawnborton** [comment] 2024-01-25 12:14
Interesting, how are these generic receipt images created? I kinda figured we would just give you a .svg or .png of that entire thumbnail image and thus you don't need to worry about adding dynamic text? I could be wrong though!

**Comment by dangrous** [comment] 2024-01-25 15:32
Ha so yeah they were previously just a non-dynamic image, but as part of this doc we're using the dynamic component - https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.xnc4hi7wlvbg

**Comment by mollfpr** [comment] 2024-01-26 18:22
@FitseTLT Could you attach the screenshot here so the design team can review it? Thanks!

**Comment by FitseTLT** [comment] 2024-01-26 18:41
Here is how it looks after the label is added 
![Screenshot_20240126-214035_Chrome](https://github.com/Expensify/App/assets/38649957/3cf84ad2-c0ab-43ef-b849-1f5b90e980bd)

**Comment by shawnborton** [comment] 2024-01-26 18:51
That feels pretty good to me, curious if others agree though!

**Comment by dannymcclain** [comment] 2024-01-26 19:15
Yup—looks pretty solid to me too!

**Comment by dangrous** [comment] 2024-02-05 15:28
How are we looking on this one? Do we think we'll be able to final review and merge sometime this week? Thanks!

**Comment by mollfpr** [comment] 2024-02-05 16:37
@dangrous I just finished reviewing and testing. It looks good to me!

**Comment by FitseTLT** [comment] 2024-02-05 18:47
Only one doubt I have @dangrous is `EReceiptThumnail` sets its bg color dynamically based on the transaction id so it might cause some confusions, for instance, when we create a request because it is a draft transaction (with transactionID 1) on confirmation page it will always be orange and after you create the request it will have different bg color when it gets its real transaction id. So should we set static bg color or we can go with the current dynamic bg color status ???

**Comment by dangrous** [comment] 2024-02-05 22:35
Eh, I think it'll be fine - I'm not that concerned about that for now.

I will have time to look through the PR tomorrow morning! Looking forward to it.

**Comment by zanyrenney** [comment] 2024-04-05 14:32
**payment summary**

@mollfpr requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28092661) (Contributor) 
@FitseTLT requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28097509) (Contributor)-$500

**Comment by mollfpr** [comment] 2024-04-05 19:54
>[@mollfpr] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

I don't think we need a regression test here.

@zanyrenney I'll do manual request in NewDot, thank you!

**Comment by zanyrenney** [comment] 2024-04-09 14:58
payment summary

@mollfpr requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28092661) (Contributor) to be paid $500 on ND.
@FitseTLT requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28097509) (Contributor)- paid $500

**Closed by zanyrenney** 2024-04-09 14:58 UTC
Labels: External, Weekly, NewFeature, Awaiting Payment, ECard

**Comment by JmillsExpensify** [comment] 2024-04-10 18:06
$500 approved for @mollfpr
