### ISSUE TITLE
[$250] Reports - The "Travel and expense..." modal is not displayed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54156] opened 2024-12-14 12:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.76-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/54065
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team
**Device used:** Windows 10/ Chrome, Samsung S23FE/ Android 14
**App Component:** Search

## Action Performed:
1. Sign into an account in OldDot
2. Set the nudgeMigration nvp in the JS console by doing: SSetNameValuePair('tryNewDot', {clasicRedirect: {dismissed: false}, nudgeMigration: "2024-12-12"} );
3. Sign into the same account on NewDot
4. Make sure you see the "Travel and expense, at the speed of chat" modal
5. Make sure that after clicking/tapping "Let's go" that you are on the Search/Reports page

## Expected Result:
The "Travel and expense, at the speed of chat" modal is displayed, and after clicking/tapping "Let's go" the user is on the Reports page.

## Actual Result:
The "Travel and expense, at the speed of chat" modal is not displayed and the user lands on Inbox as usual.

Hybrid Android behavior: After completing steps 1 and 2, the app redirects to OD. Before running the snippet, the app was redirected to ND.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d2713ed6-aa30-4b1a-8727-ae9363fa7f9a

https://github.com/user-attachments/assets/28588e9e-370e-4faf-839e-dd5b2745efa4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021868478624829865820</li>
        <li>Upwork Job ID: 1868478624829865820</li>
        <li>Last Price Increase: 2024-12-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by mkzie2** [comment] 2024-12-16 09:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Travel and expense, at the speed of chat" modal is not displayed and the user lands on Inbox as usual.

### What is the root cause of that problem?
The type of `nudgeMigration` is an object with `timestamp` field as a date string. But in the test `nudgeMigration` is a string.


https://github.com/Expensify/App/blob/653af04f8bf51661eb18f1c48a56c1362e5c61b2/src/libs/onboardingSelectors.ts#L32-L35

https://github.com/Expensify/App/blob/653af04f8bf51661eb18f1c48a56c1362e5c61b2/src/types/onyx/TryNewDot.ts#L26-L29
### What changes do you think we should make in order to solve the problem?
1. If `nudgeMigration` is a string, we should update type [here](https://github.com/Expensify/App/blob/653af04f8bf51661eb18f1c48a56c1362e5c61b2/src/types/onyx/TryNewDot.ts#L26-L29) and replace all using of `tryNewDotData?.nudgeMigration?.timestamp` to `tryNewDotData?.nudgeMigration`.

2. If not, we can update the test and close this issue.

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)
NA

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mkzie2** [comment] 2024-12-16 09:37
@puneetlath Can you please confirm what is the correct?

1. In this [PR](https://github.com/Expensify/App/pull/54065), you added the test step with `nudgeMigration` as a string.

2. In the current code, `nudgeMigration` is an object.

**Comment by puneetlath** [comment] 2024-12-16 16:23
My apologies. It's an object. With the key `timestamp` inside it.

**Comment by mkzie2** [comment] 2024-12-17 08:27
> My apologies. It's an object. With the key timestamp inside it.

@puneetlath Based on this we can close this issue

**Closed** 2024-12-17 15:32 UTC
Labels: External, Daily, Help Wanted, Bug
