### ISSUE TITLE
[$1000] Default profile avatar is different in tooltip

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20800] opened 2023-06-15 11:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat with default tooltip
2. hover over profile pic

Note: This happens in multiple places in the app

## Expected Result:
Profile should not be different in tooltip

## Actual Result:
Profile is different in tooltip

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** `main` (latest)
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686828292914429
- https://expensify.slack.com/archives/C049HHMV9SM/p1686830645725319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd1cc4ea3187cd31</li>
        <li>Upwork Job ID: 1669689115344900096</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by Beamanator** [comment] 2023-06-15 11:41
@s-alves10 please do, but please provide a proposal how you think this can be fixed first 🙏

**Comment by spcheema** [comment] 2023-06-15 11:59
.

**Comment by grgia** [comment] 2023-06-15 12:59
Avatar needs name, source, and type props for the default avatar to work. I also [reported](https://expensify.slack.com/archives/C049HHMV9SM/p1686821040533159) that the workspace avatars are incorrect for the same reason. I can potentially also take this one

**Comment by BhuvaneshPatil** [comment] 2023-06-15 14:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Default profile avatar is different in tooltip


### What is the root cause of that problem?
We are using `login` here in `UserDetailsTooltip`
https://github.com/Expensify/App/blob/d39643006874bf5ffec923291afa6b43884a4aec/src/components/UserDetailsTooltip/index.js#L18-L33

### What changes do you think we should make in order to solve the problem?
We shall use `accountID` instead

### What alternative solutions did you explore? (Optional)

**Comment by spcheema** [comment] 2023-06-15 14:37
@s-alves10 Can you please review my proposal. It requires changes on multiple files?

**Comment by twisterdotcom** [comment] 2023-06-15 16:41
@alex-mechler is this resolved by https://github.com/Expensify/App/pull/20818 as well?

**Comment by alex-mechler** [comment] 2023-06-15 16:54
This is not @twisterdotcom

**Comment by s-alves10** [comment] 2023-06-15 17:10
Is this still reproducible on staging? I can't reproduce

**Comment by gadhiyamanan** [comment] 2023-06-15 17:16
@s-alves10 this is reproducible in dev(main branch) not in staging

**Comment by BhuvaneshPatil** [comment] 2023-06-15 17:26
@s-alves10 @gadhiyamanan 
I just took a fresh pull of master, the bug is there (v1.3.28-4)

https://github.com/Expensify/App/assets/27822551/3fd7109e-5aad-4730-adcb-fc8f4c002fb1

**Comment by spcheema** [comment] 2023-06-15 20:40
@twisterdotcom Sure I will make sure not to repeats this. I was supposed to type I solution but pulled off by somethings. But agree with you.

**Comment by spcheema** [comment] 2023-06-16 09:00
Noted 🖋️ thank you @twisterdotcom

**Comment by twisterdotcom** [comment] 2023-06-16 09:24
I can't really reproduce until it's on staging, and I still can't reproduce now:

https://github.com/Expensify/App/assets/9133401/4bab4095-0bb6-4fb5-bfe7-37bd19ff52b9

**Comment by Beamanator** [comment] 2023-06-16 09:26
Yeah sadly the code that potentially broke this is still in `main` / only the dev environment. I'll test real quick

**Comment by twisterdotcom** [comment] 2023-06-16 09:32
I think if it is, let's just throw `External` on it and assign @BhuvaneshPatil if the C+ assigned agrees.

**Comment by Beamanator** [comment] 2023-06-16 09:41
I can reproduce in `main` 👍 

<img width="248" alt="Screenshot 2023-06-16 at 12 41 21 PM" src="https://github.com/Expensify/App/assets/3885503/e0fe035e-1e21-4590-852c-e4154ac1e5ef">

(Note: There's no `email` shown in my environment b/c I'm testing some other changes)

**Comment by twisterdotcom** [comment] 2023-06-16 12:52
@eVoloshchak - what do you think of the proposals here?

**Comment by twisterdotcom** [comment] 2023-06-19 15:48
Bump @eVoloshchak to review these proposals.

**Comment by eVoloshchak** [comment] 2023-06-19 17:11
@BhuvaneshPatil's [proposal](https://github.com/Expensify/App/issues/20800#issuecomment-1593158076) looks good to me, I think we should proceed with it

🎀👀🎀 C+ reviewed!
cc: @twisterdotcom

**Comment by situchan** [comment] 2023-06-19 17:18
This was fixed already (https://github.com/Expensify/App/pull/21026#issuecomment-1597068835)

**Comment by situchan** [comment] 2023-06-19 17:20
Latest codebase:
https://github.com/Expensify/App/blob/e9a7a54fb8b4f6fae634ec59464edf27d56d2b17/src/components/UserDetailsTooltip/index.js#L20-L23

**Comment by eVoloshchak** [comment] 2023-06-19 17:31
Awesome, thanks @situchan!

**Comment by BhuvaneshPatil** [comment] 2023-06-19 17:58
Yeah, this was fixed by @Beamanator - https://github.com/Expensify/App/commit/2a67b3e76567c78208b72b48e1ea5cb27d5584d3

**Comment by twisterdotcom** [comment] 2023-06-19 21:13
Okay, let's close then. Dupe of https://github.com/Expensify/App/pull/21026#issuecomment-1597068835

**Closed by twisterdotcom** 2023-06-19 21:13 UTC
Labels: External, Daily, Needs Reproduction, Bug, Upwork Automation
