### ISSUE TITLE
[HOLD for payment 2024-08-29] [$250] 2FA - No recovery codes in 2FA page for unverified account

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43603] opened 2024-06-12 19:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ikevin127 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718145760414179

## Action Performed:
Precondition: Login with a new email and don't verify account.
Note: This means that you login with a new email and you're not asked to input the magic code, unless you do this manually by navigating to Settings > Profile > Contact method > click on your email to verify it.
1. Once logged in -> click on **Settings > Security > Two-factor authentication**.
2. Click **Copy** and **Download** buttons.
3. Click on **Next** button.

## Expected Result:
1. The recovery code should be visible on 2FA page (step 1).
2. Upon clicking **Copy** the recovery code should be copied to clipboard.
3. Upon clicking **Download** the recovery codes should be downloaded in a text file.
## Actual Result:
1. The recovery code is not visible on 2FA page (step 1).
2. Upon clicking **Copy** nothing is copied to clipboard.
3. Upon clicking **Download** the downloaded text file is empty (0 B).
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/e020732b-9eab-4736-b138-25d1dcf2178f

https://github.com/Expensify/App/assets/38435837/e8071b83-3d23-482c-966e-74cbd6352c2b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145289401f3afe680</li>
        <li>Upwork Job ID: 1803637508828282692</li>
        <li>Last Price Increase: 2024-06-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment] 2024-06-13 09:11
Yeah, you shouldn't be able to set up 2FA with an unvalidated account, which I suspect is what's happening here, it's just not very good in the UI. We should improve the UI to prompt for validation as the first screen in the 2FA flow for an unvalidated account, so triggering a magic code and displaying an input to enter the code. After which, display the recovery codes and let the (now) validated user proceed to enable 2FA. CC: @Expensify/design for input on that. 

@techievivek do you think that can be worked on externally, and I suspect might need a little help on some backend work to support putting that in place?

**Comment by shawnborton** [comment] 2024-06-13 14:04
That makes sense to me.

**Comment by dannymcclain** [comment] 2024-06-13 14:07
Makes sense to me too.

**Comment by etCoderDysto** [comment] 2024-06-13 16:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
The root cause is that we are not checking if the user validated in [SecuritySettingsPage](https://github.com/Expensify/App/blob/06cde0ab006e51b02838f0b152aef77b8201ad42/src/pages/settings/Security/SecuritySettingsPage.tsx#L19) before we allow the user to open 2FA page. 
### What changes do you think we should make in order to solve the problem?
We should fetch user details from onyx using `ONYXKEYS.USER` key. Then we will use `user?.validated` prop to disable the 2FA menu item, hide the right icon, and alternatively display a hint text that says 'Verify your account first'.
```
disabled: !user?.validated,
shouldShowRightIcon: user?.validated,
hintText: !user?.validated && 'Verify your account first',
 ```
https://github.com/Expensify/App/blob/06cde0ab006e51b02838f0b152aef77b8201ad42/src/pages/settings/Security/SecuritySettingsPage.tsx#L25-L30

Note: we will fetch `hintText` value using `translate` method. And the changes will be made in `baseMenuItems` and `baseMenuItems.map` code blocks.  
### What alternative solutions did you explore? (Optional)
N/A

**Comment by trjExpensify** [comment] 2024-06-18 21:17
@techievivek what do you think of this proposal, and I take it we can send this external?

**Comment by etCoderDysto** [comment] 2024-06-19 13:02
[Update my proposal](https://github.com/Expensify/App/issues/43603#issuecomment-2166175246)
   * I have added alternative solution

**Comment by techievivek** [comment] 2024-06-20 03:56
This can be handled externally. Since the user is in an unvalidated state, they shouldn't be shown the 2FA page. We can manage this on the frontend, as the backend already ensures that recovery codes are not sent.

**Comment by nkdengineer** [comment] 2024-06-20 04:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The recovery code is not visible on 2FA page (step 1).

### What is the root cause of that problem?
We don't have a step to validate the account (if account is unvalidated) before showing the `CodesStep`

### What changes do you think we should make in order to solve the problem?

Add a step to validate the account (if account is unvalidated)
1. Build a new page `ValidateAccountStep` that will use the `ValidateCodeForm` like the add secondary contact flow [here](https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.tsx#L229). That page will send the code and wait for the user to enter the codes. The implementation details can be found in the `ContactMethodDetailsPage` where there is a similar feature. That `ValidateCodeStep` will navigate to the `CodeSteps` upon successful validation
2. In https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthSteps.tsx#L57, add a new step and render the `CONST.TWO_FACTOR_AUTH_STEPS.VALIDATE_ACCOUNT` and return the `ValidateAccountStep` if the `currentStep` is that step
3. Connect to `ONYXKEYS.ACCOUNT` and in https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthSteps.tsx#L40, check `account?.validated`. If `false` set `currentStep` to `CONST.TWO_FACTOR_AUTH_STEPS.VALIDATE_ACCOUNT` and set a local state `hasValidateAccountStep` to `true` (initialized as `false`), if not still use the `CONST.TWO_FACTOR_AUTH_STEPS.CODES`.
5. Pass the `hasValidateAccountStep` local state above to the relevant steps [here](https://github.com/Expensify/App/blob/main/src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthSteps.tsx#L57-L68)
4. We need to update the step counter in https://github.com/Expensify/App/blob/main/src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx#L52-L56 (and other steps after `VALIDATE_ACCOUNT`) to correctly show the steps in case of an additional `VALIDATE_ACCOUNT` step at the beginning. Here we can make use of the `hasValidateAccountStep` prop above. If it's false the step counter [here](https://github.com/Expensify/App/blob/main/src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx#L52-L56) stays the same, if `true` both `step` and `total` will be incremented by 1. 

Few other considerations:
- Should we allow going back from `CodesStep` to `ValidateAccountStep`. I believe no, as the user was already validated. So going back from `CodesStep` should dismiss the modal. Or we still show `ValidateAccountStep` but shows a message that the user was already validated

### What alternative solutions did you explore? (Optional)
NA

**Comment by trjExpensify** [comment] 2024-06-20 11:46
@shawnborton @dannymcclain @dubielzyk-expensify can you guys weigh in on the desired design for this flow. Do we want to add an additional step first before the recovery codes step is displayed for an unvalidated account? This might feel cleaner and we could style that page a bit better maybe.

Alternatively, do we want to replace the box that contains the recovery codes with the error message to prompt for validation. So hiding the box seen here, and just showing the error message:

<img width="944" alt="image" src="https://github.com/Expensify/App/assets/16232057/9fbc0c26-e94c-4205-a4c6-40ea7144001d">

The latter option is probably more consistent with the bank account flow that prompts for validation:

<img width="804" alt="image" src="https://github.com/Expensify/App/assets/16232057/442a2bf8-313d-40c8-98ca-8e3ac287fe29">

**Comment by dannymcclain** [comment] 2024-06-20 13:04
I don't mind either approach, but I do kinda like how your second suggestion is similar to the wallet flow. It feels a little less clear, but a bit more consistent 🤷‍♂️ 

If we went that route, I'd probably leave the box how it is (but make the buttons disabled like in the wallet flow) and maybe add some placeholder skeletons for where the codes should be? Or something like that? Curious for others' thoughts too.

**Comment by dubielzyk-expensify** [comment] 2024-06-20 14:36
Yeah I think the second way sounds alright too. That page is more sparse so I think an error message would stand out reasonably well

**Comment by dubielzyk-expensify** [comment] 2024-06-20 14:37
I don't feel strongly, but I'd probably hide the box and show the error to make it clearer where the action is, but I'm happy with Danny's suggestion too

**Comment by shawnborton** [comment] 2024-06-20 15:07
I like the second idea, and I tend to agree with Jon here - I would just kill the box entirely and show the error message in its place.

**Comment by dannymcclain** [comment] 2024-06-20 15:14
That works for me!

**Comment by trjExpensify** [comment] 2024-06-20 15:32
Dope, let's do that then! @mollfpr if you could review the proposals. I think it mostly aligns with the alt proposed [here](https://github.com/Expensify/App/issues/43603#issuecomment-2166175246), but with the addition of replacing the box with the error message.

**Comment by mollfpr** [comment] 2024-06-20 15:49
Yup, will review it in a few minutes.

**Comment by mollfpr** [comment] 2024-06-20 16:35
The alternative [proposal](https://github.com/Expensify/App/issues/43603#issuecomment-2166175246) from @etCoderDysto looks good to me!

🎀 👀 🎀 C+ reviewed!

@trjExpensify to confirm, should the next button be removed too, or just gray it out? Also, for the copy do we want to use the same copy from connect bank flow? If yes, we can create a new component only for the copy and use it on the connect bank page and 2FA page.

**Comment by trjExpensify** [comment] 2024-06-20 18:20
>to confirm, should the next button be removed too, or just gray it out?

I think we keep it but disable it, more consistent with forms that have errors. 

>for the copy do we want to use the same copy from connect bank flow?

Yeah, I think we keep the same copy as it's the same instruction!

**Comment by etCoderDysto** [comment] 2024-06-26 18:01
I am working on a PR. I will comment when the PR is ready for review.

**Comment by etCoderDysto** [comment] 2024-06-28 18:16
Working on a [PR](https://github.com/Expensify/App/pull/44635) melvin.

**Comment by trjExpensify** [comment] 2024-06-28 19:37
Thanks for the update, looking forward to it!

**Comment by trjExpensify** [comment] 2024-07-01 09:43
How we getting on with a PR, any ETA on putting it into review?

**Comment by etCoderDysto** [comment] 2024-07-01 10:02
Hi @trjExpensify, The PR is almost ready for review. There is one navigation issue I wanted to fix before requesting a final review. I am hopping to fix the navigation issue in 2 days max. If I couldn't I will ask for help form @mollfpr. 

###Progress so far
1. Sign out and verify your account first scenario 

https://github.com/Expensify/App/assets/171434916/429a651b-154e-4e99-84d9-1f243cbc78a1

2. Validate your account in contact methods section 


https://github.com/Expensify/App/assets/171434916/4e99b296-c0ba-44dc-a73c-a0b2e8b982cc


###Error to fix 
* User is not navigated back to 2FA page when clicking browser back button from contact methods section 
* Background below RHP turns to profile section when clicking 'verify your account here' link

https://github.com/Expensify/App/assets/171434916/706dcc7f-0cb9-4c5c-b3c5-f2b5a2d995b3

Expected behaviour for navigation error 

https://github.com/Expensify/App/assets/171434916/4a3f7379-3cd4-4c0c-a113-f36f249f89c7

**Comment by etCoderDysto** [comment] 2024-07-01 10:05
I will change the PR status to ready for review. I can work on navigation issues while the PR is being fixed. Is this alright to do @trjExpensify, @mollfpr ?

**Comment by trjExpensify** [comment] 2024-07-01 17:34
Works for me!

**Comment by etCoderDysto** [comment] 2024-07-16 19:20
Update: I am having a discussion on how to handle a navigation issue I have faced in [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1720188194953249)

**Comment by trjExpensify** [comment] 2024-07-23 13:00
Can we get an update here, please? Thanks!

**Comment by etCoderDysto** [comment] 2024-07-25 18:49
Sorry for the delay. There is a navigation issue that I am trying to fix. It is a bit complicated. That is why the PR is delayed. [There is a solution](https://expensify.slack.com/archives/C01GTK53T8Q/p1720188194953249) I am testing out to see if it fixes the navigation issue and if it doesn't cause a regression. And I am also working on secondary solution where I will create modal stack navigator for Two factor auth page. I will comment with the results of my testing. 

Sorry for the delaying this again.

**Comment by trjExpensify** [comment] 2024-07-25 21:32
Appreciate the update!

**Comment by trjExpensify** [comment] 2024-07-30 17:26
How are we getting on with this PR?

**Comment by etCoderDysto** [comment] 2024-07-30 20:27
Hi @trjExpensify, I have tried implementing [this suggestion](https://expensify.slack.com/archives/C01GTK53T8Q/p1721748771567429?thread_ts=1720188194.953249&cid=C01GTK53T8Q) to fix t[his navigation issue ](https://github.com/Expensify/App/pull/44635#issuecomment-2202515219). The solution has fixed an issue where the user is not navigating back to 2fa page when clicking browser's back button from contact method details page. But it causes another navigation regression. It seems I am not going anywhere with the navigation issue. Should we assign the issue to someone who is experienced with navigation? 

Sorry for the inconvenience that I have caused.

**Comment by adamgrzybowski** [comment] 2024-07-31 09:59
Hey @etCoderDysto what is the regression?

**Comment by etCoderDysto** [comment] 2024-07-31 10:41
Hi @adamgrzybowski, 
1. Go to security -> 2FA -> Click outside of the right hand modal -> Workspace -> click on existing workspace

**Actual result:** User is navigated to profile settings
**Expected Result:** User should be navigated to workspace details page

https://github.com/user-attachments/assets/a1f96ea0-0271-405b-ba5c-546dbf9a47bd

**Comment by etCoderDysto** [comment] 2024-07-31 10:48
When we navigate to contact method details section for `Connect bank account`, only the RHP navigates to the the contact method details page, and the background remains in place. Is it possible to mimic this behaviour in 2fa page? That might solve the issue I think. 
Steps: 
1. Go to workspace settings page -> enable workflow -> Navigate to Workflows > click on Connect bank account > clickon verify your account here link

https://github.com/user-attachments/assets/823a91f4-a715-42f0-91e5-36153c8ef5ca

**Comment by adamgrzybowski** [comment] 2024-07-31 11:25
Hmm, this may be a solution. I would love to understand what is happening nevertheless. 
Q:
1. Have you pushed the newest changes to your branch so I can experiment with it?
2. Do you know from which screens we can open this screen? I think if there is more than one we may need to use the `backTo` param for this screen. That should help.

<img width="144" alt="image" src="https://github.com/user-attachments/assets/dfb4c8fb-75c7-4e25-b947-689bfc6408c8">

For now, I can see two:
- connect bank account
- two factor auth

**Comment by etCoderDysto** [comment] 2024-07-31 11:41
1. I have pushed the latest changes except the navigation fix you have suggested me 
2. Which screens do open contact method details page? 
* Currently we are opening this screen (`ContactMethodDetailsPage`) form `BankAccountStep` page, which is rendered by `ReimbursementAccountPage` page. 
* `ReimbursementAccountPage` page is defined [here](https://github.com/Expensify/App/blob/4d62be9a0de127913b04584310774a8bb6485ad8/src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx#L463-L465) and [here](https://github.com/Expensify/App/blob/4d62be9a0de127913b04584310774a8bb6485ad8/src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx#L289)  in Modal stack navigator 
* On my branch `CodesStep` from `TwoFactorAuthPage` page opens `ContactMethodDetailsPage`

3. For context, the feature - 'verify your account here' link - that navigates user form `BankAccountStep` to `ContactMethodDetails` page is introduced in [this PR](https://github.com/Expensify/App/pull/38726)

**Comment by adamgrzybowski** [comment] 2024-07-31 14:10
Okay so just to make clear. Before it could be open from only one page:
- BankAccountStep
and now we want to be able to open it from two different pages:
- BankAccountStep (the old one)
- TwoFactorAuthPage (the new one)

Also bonus question. Do you know from which screens we can open the connect bank account? I can see that it has backTo param already 
<img width="644" alt="image" src="https://github.com/user-attachments/assets/d17861cf-f5cd-489a-bd92-747080c7aca3">

**Comment by etCoderDysto** [comment] 2024-08-01 13:11
That is right! `BankAccountStep` can be opened from `WorkspaceWorkflowsPage`.  I am not sure if other pages use the same component. Wallet section seems to be using different pages `EnablePaymentsPage`

**Comment by adamgrzybowski** [comment] 2024-08-01 14:32
I created diff with new changes. Please check if it works for you. The screen under the overlay won't change if the user opens `CONTACT_METHOD_DETAILS` page.
[backToDiff.txt](https://github.com/user-attachments/files/16457991/backToDiff.txt)

**Comment by etCoderDysto** [comment] 2024-08-05 19:20
> I created diff with new changes. Please check if it works for you. The screen under the overlay won't change if the user opens `CONTACT_METHOD_DETAILS` page. [backToDiff.txt](https://github.com/user-attachments/files/16457991/backToDiff.txt)

I have tried the diff. And it seems to be working well 🎉. Thanks @adamgrzybowski 🙇🏻‍♂️. I will test this thoroughly, if things will go as expected PR will ready for final review soon. 



https://github.com/user-attachments/assets/0ee8e37b-8401-4704-a643-e10cadcabe3d

**Comment by etCoderDysto** [comment] 2024-08-08 18:45
@mollfpr [PR](https://github.com/Expensify/App/pull/44635) is ready for final review 🎉

**Comment by ikevin127** [comment] 2024-08-28 20:26
@trjExpensify Not sure why it says I require payment [here](https://github.com/Expensify/App/issues/43603#issuecomment-2305218377) as my only involvement with this issue is that I reported it (see OP reported by) 🤷‍♂️

**Comment by trjExpensify** [comment] 2024-08-29 14:49
Same, all good though. Thanks for flagging! 

@mollfpr, checklist time!

**Comment by mollfpr** [comment] 2024-09-02 08:34
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

Precondition: Login with a new email and don't verify the account.

1. Go to Settings page > Security
2. Click on **Two-factor authentication**
3. **_Verify_** it open the **Two-factor authentication** page with text and link to validate the account
4. Click on **verify your account here** and verify your account
5. After submit the magic code, _**verify**_ it navigate to the **Two-factor authentication** page and showing the recovery codes.

**Comment by trjExpensify** [comment] 2024-09-02 19:18
Thanks! Payment summary as follows:

- $250 to @etCoderDysto for the fix
- $250 to @mollfpr for the review

Luthfi, go ahead and request. @etCoderDysto, I need your Upwork profile link please.

**Comment by etCoderDysto** [comment] 2024-09-02 19:20
@trjExpensify here is a link to my Upwork profile: https://www.upwork.com/freelancers/~01ea78e0164390eb79
Thanks!

**Comment by trjExpensify** [comment] 2024-09-02 19:50
Offer sent!

**Comment by etCoderDysto** [comment] 2024-09-02 19:52
I have accepted the offer. Thanks!

**Comment by trjExpensify** [comment] 2024-09-02 19:54
Paid, closing!

**Closed by trjExpensify** 2024-09-02 19:54 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-09-03 09:03
$250 approved for @mollfpr
