### ISSUE TITLE
[HOLD Expensify #227234] Android - Chat - Sending any attachment marks chat as "not read"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13472] opened 2022-12-09 15:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Android app and login
2. Open any chat
3. Tap + and select "Add attachment"
4. Choose any image and tap send
5. Go back to LHN without waiting for upload to finish
6. Notice that attachment is marked as unread in LHN, even though it was a message sent to another user. 

## Expected Result:
After upload is done chat should be not marked as "not read" because user did not receive any new messages.

## Actual Result:
After upload is done chat is marked as "not read" like user received a new message

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.38.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/206740858-4db7091e-6790-481e-a283-63012bc49bb8.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e59c0a3d5337819c</li>
        <li>Upwork Job ID: 1603470809285562368</li>
        <li>Last Price Increase: 2022-12-15</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2022-12-09 20:37
Not able to reproduce on Android: 
![2022-12-09_15-36-10 (1)](https://user-images.githubusercontent.com/54866469/206791939-aa0b169e-525a-426d-9e76-b37cea77e37c.gif)

**Comment by kbecciv** [comment] 2022-12-14 01:47
QA team is able to reproduce the issue with build 1.2.38.5

https://user-images.githubusercontent.com/93399543/207484913-1c692c33-4611-4600-a4b4-edee2beb4ef6.mp4

**Comment by joekaufmanexpensify** [comment] 2022-12-14 17:20
Not overdue.

**Comment by joekaufmanexpensify** [comment] 2022-12-14 20:29
okay, I was just able to reproduce on Android as well: 

![2022-12-14_15-22-55 (1)](https://user-images.githubusercontent.com/54866469/207707377-a71dade7-0478-4db9-81f4-a21c09a3a758.gif)

**Comment by joekaufmanexpensify** [comment] 2022-12-14 20:30
Triaging: 

From this SO: https://stackoverflow.com/c/expensify/questions/14418
- [ ] **The "bug" is actually a bug**: 
- [ ] **The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)**: 
- [ ] **The bug is reproducible, following the reproduction steps:**
- [ ] **If you're unable to reproduce the bug, add the _Needs reproduction_ label. Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.**: 
- [ ] **The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?):** 
- [ ] **The GH was created by an Expensify employee or a QA tester:** 
- [ ] **If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it's better to wait, close the GH & provide this justification:** 
- [ ] **If there's a link to Slack, check the discussion to see if we decided not to fix it:** 
- [ ] **Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label:**

**Comment by joekaufmanexpensify** [comment] 2022-12-14 20:36
I think this can likely be external. Assigning to engineering for confirmation and so we can start steps to fix this!

**Comment by joekaufmanexpensify** [comment] 2022-12-15 19:20
Waiting for confirmation that this can be external before we proceed.

**Comment by AndrewGable** [comment] 2022-12-15 19:23
Yes, can be external!

**Comment by dhanashree-sawant** [comment] 2022-12-16 09:31
**Proposal**

Modifiy isUnread function of src/libs/ReportUtils.js to include a condition to check whether last message was from current logged in user and if so, do not display it as unread.

```
@@ -1015,7 +1015,12 @@ function buildOptimisticWorkspaceChats(policyID, policyName) {
function isUnread(report) {
    const lastReadSequenceNumber = report.lastReadSequenceNumber || 0;
    const maxSequenceNumber = report.maxSequenceNumber || 0;
    return lastReadSequenceNumber < maxSequenceNumber;
    if(report.lastActorEmail==currentUserEmail){
        return false;
    }
    else{
        return lastReadSequenceNumber < maxSequenceNumber;
    }
}
```
Explaination: Whenever user exit the chat window after attachment without waiting for attachment image to load, it does not allow application to mark that message as read so by default changing the isUnread method to return false whenever the last message was from current logged in email id fixes the problem.

After the fix:

https://user-images.githubusercontent.com/87513216/208067674-cb8ed143-a254-4c1a-a19d-689324e24fca.mp4

Before the fix:

https://user-images.githubusercontent.com/87513216/208067710-31cae70d-cb1b-4a44-8a62-97320283f190.mp4

**Comment by mananjadhav** [comment] 2022-12-16 11:32
@dhanashree-sawant I think we're jumping to the solutions without identifying the root cause.

>  it does not allow application to mark that message as read

I didn't understand what you mean here? Are you saying if the user lets the attachment to load it won't mark as unread?

Also if you see the platform mentions only Android. With your code we're updating for all platforms. Are you able to reproduce this in other platforms? If no, then why is it different on Android and not reproducible on other platforms.

**Comment by dhanashree-sawant** [comment] 2022-12-16 11:56
Hi @mananjadhav 

My understanding of the issue was the message was not marked as read as soon we exit from report view. I have tried to write a code which won't harm any other platforms as it will only bypass isUnread function if last message was done by the same person as the current login.

**Comment by allroundexperts** [comment] 2022-12-16 13:14
## Proposal
The issue is with the backend pushing events with following values:
```
[
    {
        "onyxMethod": "merge",
        "key": "report_95975725",
        "value": {
            "lastReadSequenceNumber": 21
        }
    }
]
```
```
[
    {
        "onyxMethod": "merge",
        "key": "report_95975725",
        "value": {
            "reportID": "95975725",
            "maxSequenceNumber": 22,
            "lastActionCreated": "2022-12-16 13:07:53.230",
            "lastMessageTimestamp": 1671196073230,
            "lastMessageText": "[Attachment]",
            "lastActorEmail": "allroundexperts+1@gmail.com"
        }
    },
    {
        "onyxMethod": "merge",
        "key": "reportActions_95975725",
        "value": {
            "22": {
                "person": [
                    {
                        "type": "TEXT",
                        "style": "strong",
                        "text": "Sibtain Ali"
                    }
                ],
                "actorEmail": "allroundexperts+1@gmail.com",
                "actorAccountID": 11676893,
                "message": [
                    {
                        "type": "COMMENT",
                        "html": "<img src=\"https://www.expensify.com/chat-attachments/1986911485439927140/w_8a3038f8264d8d47c8a05d6cdcd2d311f6db510e.jpg.1024.jpg\" data-expensify-source=\"https://www.expensify.com/chat-attachments/1986911485439927140/w_8a3038f8264d8d47c8a05d6cdcd2d311f6db510e.jpg\" data-name=\"pexels-momoland-3880576.jpeg\" data-expensify-width=\"3024\" data-expensify-height=\"4032\" />",
                        "text": "[Attachment]",
                        "isEdited": false
                    }
                ],
                "originalMessage": {
                    "clientID": "1671196068450946",
                    "html": "<img src=\"https://www.expensify.com/chat-attachments/1986911485439927140/w_8a3038f8264d8d47c8a05d6cdcd2d311f6db510e.jpg.1024.jpg\" data-expensify-source=\"https://www.expensify.com/chat-attachments/1986911485439927140/w_8a3038f8264d8d47c8a05d6cdcd2d311f6db510e.jpg\" data-name=\"pexels-momoland-3880576.jpeg\" data-expensify-width=\"3024\" data-expensify-height=\"4032\" />"
                },
                "avatar": "https://d1wpcgnaa73g0y.cloudfront.net/02b8945511b967b655c8f6fd80f9574f1b6e85f9_128.jpeg",
                "created": "2022-12-16 13:07:53.230",
                "timestamp": 1671196073,
                "reportActionTimestamp": 1671196073230,
                "automatic": false,
                "sequenceNumber": 22,
                "actionName": "ADDCOMMENT",
                "shouldShow": true,
                "clientID": "1671196068450946",
                "reportActionID": "1986911485439927140",
                "isAttachment": true
            },
            "1671196068450946": null
        }
    }
]
```

As noticed, the first event is causing the `lastReadSequenceNumber` to be 1 less than the `sequenceNumber` of comment. This is causing this issue. For text comments, the first event never gets fired. Thus, text messages work fine.

### Fix
The backend should be fixed so that it does not emit this event for attachments just like for texts.

cc @mananjadhav

**Comment by abdulrahuman5196** [comment] 2022-12-16 15:24
Proposal:

Background:
1) We are showing the chat as unread on condition of 

```
function isUnread(report) {
    const lastReadSequenceNumber = report.lastReadSequenceNumber || 0;
    const maxSequenceNumber = report.maxSequenceNumber || 0;
    return lastReadSequenceNumber < maxSequenceNumber;
}
```

https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L1018

2) When we try to add a attachment, we add 1 to the lastReadSequenceNumber, maxSequenceNumber and set the new Data as 'optimisticData' for the 'AddComment' API. This updates the fields in Onyx locally during the start of 'AddComment' API call.
Reference: https://github.com/Expensify/App/blob/main/src/libs/actions/Report.js#L419


Root cause:

Step1) As we can see above, we are only lastReadSequenceNumber and maxSequenceNumber locally. This value will be updated in the server only when the 'AddComment' API succeeds completely.
eg:
existing - lastReadSequenceNumber(2), maxSequenceNumber(2)
after 'AddComment' start - lastReadSequenceNumber(3), maxSequenceNumber(3)

Step2) But as AddComment API here is uploading a file which takes more time compared to any GET APIs like 'OpenReport'/ 'ReconnectApp'. So in the between time of AddComment Completion, if we make any 'OpenReport' API, it will return the server's lastReadSequenceNumber, maxSequenceNumber which doesn't include the added count of the new 'AddComment' API. So the response of the 'OpenReport' API resets the Onyx data set by the 'AddComment' API locally.
eg:
existing - lastReadSequenceNumber(3), maxSequenceNumber(3)
after 'OpenReport' completion - lastReadSequenceNumber(2), maxSequenceNumber(2)

Step3) Now 'AddComment' API is complete, but in the response of AddComment(or Pusher update), we are having only the updated value of maxSequenceNumber.  lastReadSequenceNumber is missing in the response. As we merge the existing onyx data with the response of 'AddComment',  lastReadSequenceNumber is having the old data and maxSequenceNumber is having the latest data leading to unread status.
eg:
existing - lastReadSequenceNumber(2), maxSequenceNumber(2)
after 'AddComment' completion - lastReadSequenceNumber(2), maxSequenceNumber(3)

Whys:
1) Why is the issue happening for Android alone and not for other platforms?
In ReportActionsView.js (https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsView.js#L88), we listen to AppStateChange which informs incase of state changes like 'active','background',etc. In the callback of the listener we are calling 'OpenReport' API to fetch latest report information.
For Android alone, the AppStateChange changes when we open the attachment picker, resulting in 'OpenReport' API being triggered along with the 'AddComment' API. This results in 'OpenReport' API overriding the 'AddComment' API's local lastReadSequenceNumber value(This is the case i have called out in root cause)

2) Does this only happen in combination with 'OpenReport' API?
No. It can happen with combination of other API, pusher event which refreshes the report data totally like 'ReconnectApp'. But those issues to happen have very low probability as 'AddComment' and other API's having direct contact are low.
('ReconnectApp' combination probability is high for android alone as it is triggered due to AppStateChange)

3) Does it affect other platforms as well?
Yes. But the probability is low as due to similar condition pointed out in 2nd why. 

Solution:

Option 1 (Server side fix):
Return 'lastReadSequenceNumber' also as part of 'AddComment' API success pusher which currently includes only 'maxSequenceNumber'. This way after the completion of 'AddComment' API, the latest lastReadSequenceNumber and maxSequenceNumber gets updated in Onyx. (I think we can also do the same in the 'AddComment' API response. But pusher seems better option as it will work on multiple devices)
Current JSON we get in pusher

```
[
  {
    "onyxMethod": "merge",
    "key": "report_3869931480571495",
    "value": {
      "reportID": "3869931480571495",
      "maxSequenceNumber": 12,
      "lastActionCreated": "2022-12-16 08:50:35.099",
      "lastMessageTimestamp": 1671180635099,
      "lastMessageText": "[Attachment]",
      "lastActorEmail": "abdulrahuman5196@gmail.com"
    }
  },
  {
    "onyxMethod": "merge",
    "key": "reportActions_3869931480571495",
    "value": {
      "12": {
        "person": [
          {
            "type": "TEXT",
            "style": "strong",
            "text": "Abdul Rahuman"
          }
        ],
        "actorEmail": "abdulrahuman5196@gmail.com",
        "actorAccountID": 12994692,
        "message": [
          {
            "type": "COMMENT",
            "html": "<img src=\"https://www.expensify.com/chat-attachments/5033852105401721305/w_24cc0d5f1c713add71d806c67314e3dabc7617a7.jpg.1024.jpg\" data-expensify-source=\"https://www.expensify.com/chat-attachments/5033852105401721305/w_24cc0d5f1c713add71d806c67314e3dabc7617a7.jpg\" data-name=\"rn_image_picker_lib_temp_bf548349-421f-46f4-9801-11d973a253f2.jpg.jpeg\" data-expensify-width=\"3024\" data-expensify-height=\"4032\" />",
            "text": "[Attachment]",
            "isEdited": false
          }
        ],
        "originalMessage": {
          "clientID": "1671180629024943",
          "html": "<img src=\"https://www.expensify.com/chat-attachments/5033852105401721305/w_24cc0d5f1c713add71d806c67314e3dabc7617a7.jpg.1024.jpg\" data-expensify-source=\"https://www.expensify.com/chat-attachments/5033852105401721305/w_24cc0d5f1c713add71d806c67314e3dabc7617a7.jpg\" data-name=\"rn_image_picker_lib_temp_bf548349-421f-46f4-9801-11d973a253f2.jpg.jpeg\" data-expensify-width=\"3024\" data-expensify-height=\"4032\" />"
        },
        "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/avatar_5.png",
        "created": "2022-12-16 08:50:35.099",
        "timestamp": 1671180635,
        "reportActionTimestamp": 1671180635099,
        "automatic": false,
        "sequenceNumber": 12,
        "actionName": "ADDCOMMENT",
        "shouldShow": true,
        "clientID": "1671180629024943",
        "reportActionID": "5033852105401721305",
        "isAttachment": true
      },
      "1671180629024943": null
    }
  }
]

```

Option2 (Mobile side fix):
Add the calculated 'lastReadSequenceNumber' , 'maxSequenceNumber' in the successData of the 'AddComment' API request. This way once the AddComment API is complete it will set the proper 'lastReadSequenceNumber' , 'maxSequenceNumber' values.


Option3 (Other temporary fixes - Just calling out):
We can call 'OpenReport' API after the 'AddComment' API is successful to sync with proper server data.

**Comment by joekaufmanexpensify** [comment] 2022-12-16 17:17
Proposals pending review.

**Comment by s77rt** [comment] 2022-12-18 16:40
@abdulrahuman5196 I agree with you on the RCA. However none of the proposed solutions looks solid.

IMO we need to define some rules for the pusher to ignore some events if they don't meet certain conditions, e.g. for this case the rule could be to only update `maxSequenceNumber` and `lastReadSequenceNumber` if the new value is greater than the stored value.

*The rule above is just an example and it's not solid either.*
___

This issue may be internal as per this comment https://github.com/Expensify/App/issues/12598#issuecomment-1325673998
@marcaaron

**Comment by joekaufmanexpensify** [comment] 2022-12-19 13:06
Proposals still pending review.

**Comment by mananjadhav** [comment] 2022-12-19 13:17
Hi,
I am going to review these by tomorrow. Limited bandwidth.

**Comment by joekaufmanexpensify** [comment] 2022-12-20 21:03
Proposals still pending review.

**Comment by mananjadhav** [comment] 2022-12-21 17:00
Thanks a lot for the patience here. Sorry I couldn't get to it sooner. I agree with @abdulrahuman5196's comment on the root cause and I've started a thread [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1671641933604809) on slack. I think even if we do solve this from backend, there might be some work required on the FE to ensure that the optimisticData does have the number > maxSequenceNumber. I am going to get. more 👀 on this. So please bear with me until we get a good consensus for the resolution.

**Comment by AndrewGable** [comment] 2022-12-21 18:00
@abdulrahuman5196 - Thank you for the research, you will be compensated for this work. 

* Since this starts to touch the backend, I will mark this as **internal**.
* @puneetlath is working on a internal refactor here: https://github.com/Expensify/App/pull/13419 in addition to a backend refactor that should resolve this.
* Therefore I will place this issue on **hold** and @puneetlath will verify this is fixed as a part of https://github.com/Expensify/App/pull/13419

**Comment by abdulrahuman5196** [comment] 2022-12-21 19:17
Hi, @mananjadhav @AndrewGable  Thank you for your reviews on my analysis and proposals. Happy to hear I was helpful in your work and I would be compensated as well. Would be happy to help as a external in future as well if any new requirement comes in this issue.

**Comment by joekaufmanexpensify** [comment] 2022-12-21 21:01
Discussed in Slack, and the plan is to fix this in the above linked PR that @puneetlath is working on. However, given the extensive investigation done by @abdulrahuman5196, we're going to compensate $500.

**Comment by mananjadhav** [comment] 2022-12-21 21:02
@joekaufmanexpensify @AndrewGable the payout also applies to c+ for the proposal reviews?

**Comment by joekaufmanexpensify** [comment] 2022-12-21 21:03
@abdulrahuman5196, could you please confirm that this is your [Upwork profile](https://www.upwork.com/freelancers/~018bbf379ae0a01d70)?

**Comment by joekaufmanexpensify** [comment] 2022-12-21 21:03
@mananjadhav We haven't discussed that. I will raise now, and report back!

**Comment by joekaufmanexpensify** [comment] 2022-12-21 21:25
@mananjadhav We'll compensate $500 here for time spent reviewing as well.

**Comment by abdulrahuman5196** [comment] 2022-12-22 04:48
> @abdulrahuman5196, could you please confirm that this is your [Upwork profile](https://www.upwork.com/freelancers/~018bbf379ae0a01d70)?

@joekaufmanexpensify yes. That is my upwork profile.

**Comment by JmillsExpensify** [comment] 2022-12-27 03:03
This one slipped my radar over the last two weeks. I'm assigning myself as the BZ member helping manage the related bug fixes as sequence number PRs go live.

**Comment by JmillsExpensify** [comment] 2022-12-27 03:06
Circling back to Upwork, @abdulrahuman5196 I've just invited you to the corresponding job. Please apply for $500 so that we can compensate you. @mananjadhav I've proactively hired you for C+ work to get that out of the way, though let's see what's required when we circle back on the internal PR and determine what's needed.

**Comment by abdulrahuman5196** [comment] 2022-12-27 08:23
Thank you @JmillsExpensify . I have applied for the invite. Kindly let me know if anything else is required.

**Comment by JmillsExpensify** [comment] 2022-12-27 16:51
Great! Offer sent in Upwork.

**Comment by abdulrahuman5196** [comment] 2022-12-27 17:06
@JmillsExpensify Thank you. Accepted the invite.

**Comment by JmillsExpensify** [comment] 2022-12-27 17:16
Oh sorry for the confusoin. I'm still waiting for you to accept the offer in Upwork, as I can't pay you until then.

**Comment by JmillsExpensify** [comment] 2022-12-27 17:19
Thanks! I see you accepted now. I've paid out and closed the contract.

**Comment by abdulrahuman5196** [comment] 2022-12-27 17:29
@JmillsExpensify thank you. Got it.

**Comment by JmillsExpensify** [comment] 2023-01-11 05:11
We're still working through the unread refactor, though hopefully we'll be through that in the coming weeks.

**Comment by puneetlath** [comment] 2023-01-11 19:51
I _believe_ this is also fixed now. @kbecciv can you re-test?

**Comment by JmillsExpensify** [comment] 2023-01-11 20:08
Oh sweet, thanks for clarifying. I'll test on Android now.

**Comment by JmillsExpensify** [comment] 2023-01-11 20:13
💥 Nice one, you're right! I'm unable to reproduce on Pixel 7, build 1.2.52-4. Given that there are no issue contributors, and related, we have a separate regression test for this case, I'm going to close. Please comment/re-open if you disgaree!

**Closed by JmillsExpensify** 2023-01-11 20:13 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Bug

**Comment by mananjadhav** [comment] 2023-01-11 20:14
@JmillsExpensify The C+ payout is pending for this one.

**Comment by JmillsExpensify** [comment] 2023-01-12 05:05
@mananjadhav I think this one is a special case, in that the no PRs were reviewed by external contributors. So I think out of fairness, you payment would be similar to what we paid out for the idea that lead to the proposal. In other words, $500. Does that seem fair to you?

**Comment by mananjadhav** [comment] 2023-01-12 05:10
Yes @JmillsExpensify, agreed $500 is good here. Thanks.

**Comment by JmillsExpensify** [comment] 2023-01-12 05:19
Great, you're all set now.
