### ISSUE TITLE
[HOLD #50120][$250] Chat- Inconsistent display of deleted image from deep link in search chat and Inbox chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50470] opened 2024-10-08 19:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N/A
**Email or phone of affected tester (no customers):** applausetester+tw4335353535355335@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open any chat and upload an image
2. Hover over the image > click three dots > copy link
3. Paste the link in the composer and send it > delete the image
4. Click on the link in the chat > It shows empty composer
5. Go to search > select the chat > click on the same link > "Hmm... it's not here" error appears

## Expected Result:
Clicking the link in both the search chat and inbox should show the same result since the links are identical

## Actual Result:
After deleting the image, clicking the link in the inbox chat and search chat shows different results

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/9c3ffe88-56ac-4ac7-bda7-07bb7b4d477f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843744700304943378</li>
        <li>Upwork Job ID: 1843744700304943378</li>
        <li>Last Price Increase: 2024-10-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by lanitochka17** [comment] 2024-10-08 19:13
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-10-08 19:14
We think that this bug might be related to #wave-control

**Comment by DylanDylann** [comment] 2024-10-17 11:31
This issue is fixed, can't reproduce any more

**Comment by DylanDylann** [comment] 2024-10-17 11:31
@daledah could you able to reproduce this issue?

**Comment by DylanDylann** [comment] 2024-10-17 11:32
If not, we can close this one

cc @puneetlath

**Comment by puneetlath** [comment] 2024-10-17 18:25
Sounds good. Closing!

**Closed by puneetlath** 2024-10-17 18:25 UTC
Labels: External, Weekly, Help Wanted, Bug
