### ISSUE TITLE
[$250] mWeb - Workspace - Description/invite field spreads when open after adding custom message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45520] opened 2024-07-16 20:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a655@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create Workspace> Go to Profile> Description
3. Add one line custom content
4. Go back to profile page> Description

## Expected Result:
Description field should be stable and consistent

## Actual Result:
Description field spreads when open after adding custom message, Same behavior with invite to workspace message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9c3ea550-8101-4a8b-ac5a-14cbdfdcca11

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1da63be78ab6ed2</li>
        <li>Upwork Job ID: 1815520376926944760</li>
        <li>Last Price Increase: 2024-07-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by lanitochka17** [comment] 2024-07-16 20:06
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-07-16 20:06
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-07-17 15:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Profile description field expands briefly before shrinking to the correct height when the description is 1 line.

### What is the root cause of that problem?
The profile description text input is an auto-grow input, which means the height is based on the invisible text height as shown below.
https://github.com/Expensify/App/blob/1725d48daa956b0851ce9728d5917a038f12d33b/src/components/TextInput/BaseTextInput/index.tsx#L487-L500

The invisible text is being used to calculate the height and width of the input. However, when we open the page for the first time, the value is initially bigger than what it should be. For example, when I test it, the initial invisible text height is 91, then it shrinks back to 51, the correct one, which causes the height jump.

That happens because the invisible text has a maximum width style which depends on the input container width. We want the width between the invisible text and the input container to be the same, so the calculation is accurate. However, the input container width is initially 0, not calculated yet. That makes the max-width of the invisible text to be 0 too.
https://github.com/Expensify/App/blob/1725d48daa956b0851ce9728d5917a038f12d33b/src/components/TextInput/BaseTextInput/index.tsx#L93
https://github.com/Expensify/App/blob/1725d48daa956b0851ce9728d5917a038f12d33b/src/components/TextInput/BaseTextInput/index.tsx#L483
https://github.com/Expensify/App/blob/1725d48daa956b0851ce9728d5917a038f12d33b/src/styles/index.ts#L1164-L1166

Because the max-width is 0, the invisible text is cramped, resulting in a bigger height.

### What changes do you think we should make in order to solve the problem?

Only set the max-width if it's > 0.
https://github.com/Expensify/App/blob/1725d48daa956b0851ce9728d5917a038f12d33b/src/styles/index.ts#L1164-L1166
`maxWidth: maxWidth ? maxWidth : undefined,`

**Comment by VictoriaExpensify** [comment] 2024-07-22 00:51
Trying to reproduce this but having trouble getting magic codes for my test accounts. will come back to it later today

**Comment by VictoriaExpensify** [comment] 2024-07-22 00:58
I have not been able to recreate this issue:

Uploading screen-20240722-101254 (1).mp4…

@bernhardoj have you been able to recreate this?

**Comment by bernhardoj** [comment] 2024-07-22 03:09
Yes, I can repro it.

https://github.com/user-attachments/assets/57fefbfa-586a-466b-82b9-34ae44f6e782

I can't see your recording, did you try to test it in Android mWeb?

It's reproducible in web too, but just harder to notice.

**Comment by VictoriaExpensify** [comment] 2024-07-22 06:03
Oh why didn't my attachment work? Hmm strange, I tested this on Android mWeb. I've uploaded it again:


https://github.com/user-attachments/assets/cbff3a89-e42c-4349-9081-c6c6cf2ca9ed

**Comment by VictoriaExpensify** [comment] 2024-07-22 06:04
https://github.com/user-attachments/assets/8f8ec65f-9844-4928-89c8-64ee0d3405d9

**Comment by bernhardoj** [comment] 2024-07-22 09:05
If I stop your video at 0:36, then I can see the field is expanded.
<img width="454" alt="image" src="https://github.com/user-attachments/assets/52254eb1-d370-4d9e-8568-67fedc5eed7f">

I think you can try using a High Traffic account to "slow down" the app so it's easier to reproduce.

**Comment by m-natarajan** [comment] 2024-07-22 15:50
Tester is able to reproduce in the latest staging build

https://github.com/user-attachments/assets/eac75044-0560-42aa-a465-b83848da61c7

**Comment by VictoriaExpensify** [comment] 2024-07-22 22:56
I think this seems too minor to put energy into right now. I'm going to close it out for now and we can revisit down the track if we still think it's worth it

**Closed by VictoriaExpensify** 2024-07-22 22:56 UTC
Labels: External, Daily, Help Wanted, Bug
