### ISSUE TITLE
[HOLD for payment 2023-09-04] [$1000] Split Bill - All user names are showing in IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25640] opened 2023-08-22 01:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.epensify.com
2. Sign into a valid account
3. Split bill

## Expected Result:
User expects that the preview shows the users images and not names

## Actual Result:
All split bill user names and date is displayed in the IOU

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img width="1440" alt="Bug6172869_On_Staging" src="https://github.com/Expensify/App/assets/78819774/c768ce2f-9b43-46b8-bd7a-4bfbc179e1fb">

<img width="1440" alt="Bug6172869_On_PROD" src="https://github.com/Expensify/App/assets/78819774/3365f063-7e83-41c4-91e6-8b317c4ede15">

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a8059f6b6485a78</li>
        <li>Upwork Job ID: 1693876610499690496</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26263054</li>
<li>s-alves10 | Contributor | 26263056</li>
</ul></li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-08-22 01:43
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Split Bill - All user names are showing in IOU

### What is the root cause of that problem?
![Screenshot 2023-08-22 at 7 09 38 AM](https://github.com/Expensify/App/assets/16595846/de90a822-ca85-46f3-a680-e8fc78213a91)

this pr enabled  the `merchant` https://github.com/Expensify/App/pull/25449/files

### What changes do you think we should make in order to solve the problem?
I think we need to fix the backend

**Comment by s-alves10** [comment] 2023-08-22 02:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

All user names appears in split bill

### What is the root cause of that problem?

This is a regression from [this PR](https://github.com/Expensify/App/pull/24235)

We create merchant info optimistically when we create split bill here
https://github.com/Expensify/App/blob/120bcbfde6d0ccfac8a63cf11a4aa7f769a048ea/src/libs/actions/IOU.js#L627

We show merchant info below
https://github.com/Expensify/App/blob/120bcbfde6d0ccfac8a63cf11a4aa7f769a048ea/src/components/ReportActionItem/MoneyRequestPreview.js#L257-L261

This is the root cause

### What changes do you think we should make in order to solve the problem?

I don't think we need to show merchant information in money request preview

Removing the merchant information from the [MoneyRequestPreview](https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/MoneyRequestPreview.js) will solve the issue


### What alternative solutions did you explore? (Optional)

**Comment by robertjchen** [comment] 2023-08-22 06:44
Looks like we have a few proposals here already, let's see if we can get a fix reviewed and out as soon as possible

**Comment by jjcoffee** [comment] 2023-08-22 07:53
@pradeepmdk I'm not sure I understand why we would want to display `requestMerchant` if it's equal to `CONST.REPORT.TYPE.IOU`; I think that would just display `iou`.

@s-alves10 Could you explain what part of [the PR](https://github.com/Expensify/App/pull/24235) you linked caused the regression?

**Comment by s-alves10** [comment] 2023-08-22 07:55
Please check

https://github.com/Expensify/App/pull/24235/files#diff-d8e6b69ad4461bebf91e940a67ddc07adf36a3f7c156d6066363c3bde06a0f8aR257-R261

**Comment by jjcoffee** [comment] 2023-08-22 08:07
@s-alves10 Perfect, thanks! I don't think removing the merchant info altogether is the correct solution here as it's definitely intended for it to display for requests.

**Comment by pradeepmdk** [comment] 2023-08-22 08:29
@jjcoffee Yes it will display always `IOU`, the merchant show is a newly added feature I think we can remove this one 
https://github.com/Expensify/App/blob/c053381c06587d2569247c6d546cf9bd69ceba97/src/libs/actions/IOU.js?#L627
because this is not a 'merchant' here

**Comment by jjcoffee** [comment] 2023-08-22 09:39
@pradeepmdk We do want to display the merchant for money requests, just not for splitting bills (the merchant feature is [disabled](https://github.com/Expensify/App/pull/25449#issuecomment-1684555306) for splits for now).

Still open for proposals that deal with this issue specifically for split bills!

**Comment by jjcoffee** [comment] 2023-08-22 09:41
Bumped on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1692697284463519?thread_ts=1692667111.107069&cid=C01GTK53T8Q) for more proposals.

**Comment by s-alves10** [comment] 2023-08-22 09:43
## Proposal
[Updated](https://github.com/Expensify/App/issues/25640#issuecomment-1687335264)

**Comment by pradeepmdk** [comment] 2023-08-22 09:53
> @pradeepmdk We do want to display the merchant for money requests, just not for splitting bills (the merchant feature is [disabled](https://github.com/Expensify/App/pull/25449#issuecomment-1684555306) for splits for now).
> 
> Still open for proposals that deal with this issue specifically for split bills!

then we can use this` !props.isBillSplit  && requestMerchant ` i think @s-alves10  already updated this

**Comment by jjcoffee** [comment] 2023-08-22 10:01
@s-alves10's [proposal](https://github.com/Expensify/App/issues/25640#issuecomment-1687335264) has the correct RCA, since that PR [introduced](https://github.com/Expensify/App/commit/acb2956ff975a2da464aed99e14b554966adeee8#diff-d8e6b69ad4461bebf91e940a67ddc07adf36a3f7c156d6066363c3bde06a0f8a) the actual display of the `merchant` in the `MoneyRequestPreview`. The solution could do with a bit more detail, but I'm giving a little leeway as this is a deploy blocker!

@robertjchen I'm lacking a bit of context on the rollout of the `merchant` field (since the linked [issues](https://github.com/Expensify/Expensify/issues/301363) are internal), so I'm unsure if hiding the merchant on split bills would just be a temporary fix (whilst merchant is [disabled](https://github.com/Expensify/App/pull/25449#issuecomment-1684555306) for split bills). In any case as this is a deploy blocker, it seems like @s-alves10 fix is appropriate to apply until the merchant field is up and running for split bills.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by robertjchen** [comment] 2023-08-22 10:18
Thanks for all the discussion here! 🙇

@jjcoffee is correct, as this would be a temporary fix and we may not have enough context at the moment 🤔 In reviewing this, I just saw that they were considering reverting the PR that introduced this along with the other issues. https://github.com/Expensify/App/pull/24235#issuecomment-1687652892

To avoid any potential conflicts, I'll defer to them here and see if they want to fix this (and accept this change) or revert. cc: @Li357

**Comment by Li357** [comment] 2023-08-22 13:29
Hi y'all!

I'd prefer not to revert the linked PR due to its internal importance. I think a lot of these are small changes that can be fixed piecemeal. Thanks for catching this!

**Comment by jjcoffee** [comment] 2023-08-22 14:01
@s-alves10 If you have any issues with slow Android build times, please just raise the PR so I can make a head-start on testing. Thanks!

**Comment by s-alves10** [comment] 2023-08-22 14:03
Okay

**Comment by s-alves10** [comment] 2023-08-22 14:12
@jjcoffee 

[PR](https://github.com/Expensify/App/pull/25684) is created as draft.
I'm testing on various platforms now. Will have it ready for review in an hour or 2.

**Comment by s-alves10** [comment] 2023-08-22 16:10
@jjcoffee 

[PR](https://github.com/Expensify/App/pull/25684) is ready for review

**Comment by jjcoffee** [comment] 2023-08-28 09:54
Not sure why the automation didn't kick in here, but the PR was [deployed](https://github.com/Expensify/App/pull/25684#issuecomment-1690921429) to production 2023-08-24. @michaelhaxhiu can you update the title to hold for payment for 2023-08-31? Thanks!

**Comment by jjcoffee** [comment] 2023-09-05 15:03
@michaelhaxhiu Gentle bump for payment on this. Thanks!

**Comment by michaelhaxhiu** [comment] 2023-09-06 20:22
I apologize for the delay!

**Comment by michaelhaxhiu** [comment] 2023-09-06 20:24
both paid, closing!

**Closed by michaelhaxhiu** 2023-09-06 20:24 UTC
Labels: External, Engineering, Daily, Awaiting Payment
