### ISSUE TITLE
[HOLD for payment 2023-12-15] [$500] Dev:  Alternate text on sidebar does not translate when Invite member to room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30087] opened 2023-10-20 15:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev 1.3.87.8
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697793108025429

## Action Performed:
1. Create a room
2. Go to room details
3. Go to members
4. Click Invite and invite 1 member
5. Observed on the room's LHN that Alternate text show invited 1 user
6. Change language to Spanish, Observe that Alternate text is not translated

## Expected Result:
Alternate text should be translated when invite member to room

## Actual Result:
Alternate text is not translated when invite member to room

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/1c825542-4946-42fa-80da-8bcd0818dbfb

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/ca486e13-d5e1-452f-818c-ade315d2afe3

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/a7d83041-b054-4d24-849b-ba6c0191791a

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/f3055cfb-0c02-483b-b9bb-353b6f834830

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/98dd6912-4450-4677-b035-1c2384ee5944

</details>

<details>
<summary>MacOS: Desktop</summary>

 
https://github.com/Expensify/App/assets/93399543/eb510755-f4aa-44ec-bdf2-6b9595c10965

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168a6416641572c9d</li>
        <li>Upwork Job ID: 1715384041364860928</li>
        <li>Last Price Increase: 2023-10-20</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27470092</li>
<li>namhihi237 | Contributor | 27470094</li>
<li>namhihi237 | Reporter | 27470097</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by kbecciv** [comment] 2023-10-20 15:08
Proposal by: @namhihi237
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1697793108025429

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Alternate text on the sidebar should be translated when Invite member to the room
### What is the root cause of that problem?
Currently, we hard code the text relative to inviting members here
https://github.com/Expensify/App/blob/69cf29e32950f915ea888fe294dfdea6a9fabbb5/src/libs/SidebarUtils.js#L370-L384
### What changes do you think we should make in order to solve the problem?
1. Create translate key in en.js and es.js
2. Use `Localize.translate()` instead.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by lalitkumawat1m** [comment] 2023-10-21 07:29
Hey team, want to work on this issue please assign to me

**Comment by cubuspl42** [comment] 2023-10-23 07:03
Ouch, I thought there were no more cases like this left! Sure, needs to be fixed.

I approve the proposal by @namhihi237

C+ reviewed 🎀 👀 🎀

**Comment by mountiny** [comment] 2023-10-23 12:59
@namhihi237 @cubuspl42 this only translates the LHN preview but not the actual message in the chat report, why do we not translate that one there too?

**Comment by mountiny** [comment] 2023-10-23 13:07
Yeah but the current solutionw ould lead to worse experience as you would have it in spanish in one place and in english in another

**Comment by cubuspl42** [comment] 2023-10-24 08:47
@mountiny 

> @namhihi237 @cubuspl42 this only translates the LHN preview but not the actual message in the chat report, why do we not translate that one there too?

I haven't noticed that.

> Yeah but the current solutionw ould lead to worse experience as you would have it in spanish in one place and in english in another

I thought the closer we get to fully localizing the app, the better. I'm not fully convinced that translating one bit leads to worse experience, but I understand that you feel this way.

How do you think we should proceed? Do you think we should coordinate with the backend? What options are open here? Could we make the relevant API return a natural-language-agnostic modeled representation of this data?

Expensify seems to be a architectured as a "thin client" in many spots, and the backend sometimes returns the data in a format that's difficult to be processed on the frontend side. This is one such place, I think.

**Comment by joekaufmanexpensify** [comment] 2023-10-25 16:32
Pending further internal engineering guidance

**Comment by mountiny** [comment] 2023-10-25 21:46
we currently do not have backend localization in place and we do not plan to add it any time soon but I think this just should b consistent with how we show other report actions, for example iou paid report actions are also translated

**Comment by cubuspl42** [comment] 2023-10-26 08:58
@namhihi237 Would you update your proposal with [these changes](https://github.com/Expensify/App/issues/30087#issuecomment-1775395668)?

**Comment by cubuspl42** [comment] 2023-10-26 09:23
@namhihi237 Do you have a Git branch at your fork? I'd like to test the `getReportActionMessageRoomChange` function and see how it's called

**Comment by cubuspl42** [comment] 2023-10-26 11:14
@namhihi237 

I think this isn't expected?

![image](https://github.com/Expensify/App/assets/2590174/32e8d834-5185-4122-828b-b93a97e37084)

**Comment by joekaufmanexpensify** [comment] 2023-10-30 13:50
@cubuspl42 are we close to being able to accept a proposal here?

**Comment by cubuspl42** [comment] 2023-10-30 14:21
@joekaufmanexpensify The proposal is actually [already accepted](https://github.com/Expensify/App/issues/30087#issuecomment-1774552541).

@mountiny With a bit of polishing, the updated proposal by @namhihi237 seems to accomplish the expected goals. Do you think it's acceptable ine the current state?

**Comment by cubuspl42** [comment] 2023-10-30 14:22
Of course we'll do more in-depth testing when the actual PR is filed

**Comment by mountiny** [comment] 2023-11-01 11:45
Yeah I think we can work through its kinks in the PR

**Comment by joekaufmanexpensify** [comment] 2023-11-02 13:42
@namhihi237 do you expect to have a PR up here soon?

**Comment by joekaufmanexpensify** [comment] 2023-11-06 16:00
Pending @namhihi237 submitting a PR

**Comment by cubuspl42** [comment] 2023-11-07 11:08
PR is being worked on

**Comment by mountiny** [comment] 2023-11-07 14:23
Thanks!

**Comment by joekaufmanexpensify** [comment] 2023-11-08 22:07
@namhihi237 will you have a PR in review here soon?

**Comment by cubuspl42** [comment] 2023-11-09 09:37
Yes, we're modifying the exact same part as another PR: https://github.com/Expensify/App/pull/30898

We'll resume the work right after that one is merged

**Comment by joekaufmanexpensify** [comment] 2023-11-13 14:50
held

**Comment by joekaufmanexpensify** [comment] 2023-11-20 14:11
@cubuspl42 The other PR merged, can we continue this one?

**Comment by cubuspl42** [comment] 2023-11-20 14:22
I commented in [the PR associated with our issue](https://github.com/Expensify/App/pull/30927#issuecomment-1819159900)

**Comment by joekaufmanexpensify** [comment] 2023-11-27 15:00
Great! I see the PR is getting close.

**Comment by cubuspl42** [comment] 2023-12-12 15:57
@mountiny Did we trigger the auto-closing regex?

**Comment by joekaufmanexpensify** [comment] 2023-12-12 16:23
Ah, yeah this one is not done yet as we haven't done BZ checklist/issued payment.

**Comment by joekaufmanexpensify** [comment] 2023-12-13 15:02
@cubuspl42 Could you please handle the BZ checklist so we can prep to issue payment on Friday?

**Comment by joekaufmanexpensify** [comment] 2023-12-14 16:49
Bumped checklist [here. ](https://expensify.slack.com/archives/C02NK2DQWUX/p1702572564199129)

**Comment by cubuspl42** [comment] 2023-12-15 09:59
- The PR that introduced the bug has been identified. Link to the PR:
    -  It seems that the bug was present in the relevant components since they were created
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by joekaufmanexpensify** [comment] 2023-12-15 14:20
Great, TY! All set to issue payment. We need to issue the following payments: 

- @namhihi237 $50 for reporting. Paid via Upwork. 
- @namhihi237 $250 for PR (50% reduction because of regression). Paid via Upwork. 
- @cubuspl42 $250 for C+ (50% reduction because of regression). Paid via Upwork.

**Comment by joekaufmanexpensify** [comment] 2023-12-15 14:21
@namhihi237 $50 sent and contract ended

**Comment by joekaufmanexpensify** [comment] 2023-12-15 14:22
@namhihi237 $250 sent and contract ended

**Comment by joekaufmanexpensify** [comment] 2023-12-15 14:22
@cubuspl42 $250 sent and contract ended

**Comment by joekaufmanexpensify** [comment] 2023-12-15 14:23
All payment issued. Closing as this is all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-12-15 14:23 UTC
Labels: External, Daily, Awaiting Payment, Bug
