### ISSUE TITLE
[HOLD] [$250] Firefox - All the dropdown options appear gray in color and different font

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9341] opened 2022-06-07 17:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Log in any account
3. Navigate to settings by clicking on the user avatar over LHN
4. Click on Profile
5. Click on “Preferred Pronouns” or Select any of the dropdowns in the settings page (preferences, or from the workspace editor)

## Expected Result:
Dropdowns will have same font as in the app and background color should be white

## Actual Result:
Dropdown options appear gray backgroud color and different font

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- Web - Firefox

**Version Number:** 1.1.73-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
![Bug5600368_firefox_0706-3](https://user-images.githubusercontent.com/43996225/172448467-24ee016d-7b92-48e2-98f6-a3b93097912d.png)
![Bug5600368_firefox_0706](https://user-images.githubusercontent.com/43996225/172448470-30bdeb61-a2d5-4bd0-97b6-e6a1b0701d5a.png)
![Bug5600368_firefox_0706-1](https://user-images.githubusercontent.com/43996225/172448472-0339cf41-fec6-4fe2-86a0-18641efb525d.png)
![Bug5600368_firefox_0706-2](https://user-images.githubusercontent.com/43996225/172448474-59943b83-5fe4-4f96-82a5-8fb92215c586.png)

**Upwork Job Link:** https://www.upwork.com/jobs/~011c612d785f81ca45

**Issue reported by:** 
Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment] 2022-06-08 13:58
Weird/interesting, this is only a problem in firefox (not chrome) 😄 

@kavimuru do you know if it was a regression? 
For whomever gets to work on this, I'm curious to know where this problem is from (and if we can track it to a regression).

**Comment by michaelhaxhiu** [comment] 2022-06-10 23:15
Posted to upwork, link here - https://www.upwork.com/jobs/~011c612d785f81ca45

**Comment by JosueEchandiaAsto** [comment] 2022-06-12 02:50
### Proposal

### Issue
Dropdown options appear gray backgroud color and different font

### Fix
Firefox doesn't allow setting fontFamily in <option> if this font is not installed on the device since the page is consulted.

For example:
Set Futura font to <option> that is install.

![](https://user-images.githubusercontent.com/16966456/173211045-7350affc-fb06-4350-90cc-ee416b519fc7.png)
![](https://user-images.githubusercontent.com/16966456/173211009-b679c9d6-8013-4aa0-8ceb-d4ab39444c9b.png)
Everything works well.

But if you remove Futura from the device.
![Captura de Pantalla 2022-06-11 a la(s) 20 52 06](https://user-images.githubusercontent.com/16966456/173211041-93da0562-3a5b-4bf7-bcd5-5d656c6dbb0c.png)

We have the same problem.
![](https://user-images.githubusercontent.com/16966456/173211090-4f008ae5-7713-41ad-b8f7-c737aeb2e618.png)

Now, knowing that the required font cannot be assigned, how do we avoid displaying such a different font.
We can assign a font for when a browser can't get the font we want. It's like a backup font.
Even better, assign a group of fonts that looks like ours. In this case Sans-Serif o font-family: 'revert'

Option 1: With font-family: 'revert' (Best option)
**[Revert property](https://developer.mozilla.org/en-US/docs/Web/CSS/revert)**
<img width="363" alt="Captura de Pantalla 2022-06-11 a la(s) 21 23 45" src="https://user-images.githubusercontent.com/16966456/173211665-7f016043-fdc9-4c45-ba00-79d938037b5a.png">
<img width="374" alt="Captura de Pantalla 2022-06-11 a la(s) 21 19 28" src="https://user-images.githubusercontent.com/16966456/173211552-b9ededd8-daa0-4fc8-928a-b43aa711fee9.png">

Option 2: With fontFamily:  'GTAmericaExp-Regular, Sans-Serif'
<img width="382" alt="Captura de Pantalla 2022-06-11 a la(s) 21 21 43" src="https://user-images.githubusercontent.com/16966456/173211612-21f4d0e8-0d42-4112-8044-647bd99dca14.png">
<img width="378" alt="Captura de Pantalla 2022-06-11 a la(s) 21 21 51" src="https://user-images.githubusercontent.com/16966456/173211615-b52808c4-d47b-48e0-b71a-302aadac17c0.png">

Between option 1 or option 2 there is only a slight difference in the font when the list of options is displayed.

### As it currently looks
Mac/Safari/Dark mode
<img width="369" alt="Captura de Pantalla 2022-06-11 a la(s) 21 46 17" src="https://user-images.githubusercontent.com/16966456/173212079-e07caf60-e1e8-4384-8cb5-ce7adc9149a3.png">
Mac/Chrome/Dark mode
<img width="369" alt="Captura de Pantalla 2022-06-11 a la(s) 21 46 17" src="https://user-images.githubusercontent.com/16966456/173212094-a438a5b0-4665-4489-b2c4-e6d7cc9aa83b.png">
Mac/Mozilla/Dark mode
<img width="371" alt="Captura de Pantalla 2022-06-11 a la(s) 21 45 11" src="https://user-images.githubusercontent.com/16966456/173212104-f9637d31-2f46-45c8-ae75-9d6691eeb7de.png">

Mac/Safari/Light mode
<img width="369" alt="Captura de Pantalla 2022-06-11 a la(s) 21 46 17" src="https://user-images.githubusercontent.com/16966456/173212160-dc9b5f3d-d6b3-4fb4-a291-460caeba9fac.png">

Mac/Chrome/Light mode
<img width="369" alt="Captura de Pantalla 2022-06-11 a la(s) 21 46 17" src="https://user-images.githubusercontent.com/16966456/173212159-8b003908-f705-4ecd-9636-0134ff033324.png">

Mac/Mozilla/Light mode
<img width="369" alt="Captura de Pantalla 2022-06-11 a la(s) 21 46 17" src="https://user-images.githubusercontent.com/16966456/173212155-cd2a03ba-ff77-4aa5-aa32-f951f7e201c8.png">

**This proposal would only affect Web/Mozilla**

**Comment by flodnv** [comment] 2022-06-13 18:50
Thanks for the insights! Which font is it not getting? Can we not somehow force install it?

**Comment by JosueEchandiaAsto** [comment] 2022-06-13 21:44
GTAmericaExp-Regular is the font that the project is using.
We cannot force the installation of any font on the devices.

**Comment by flodnv** [comment] 2022-06-14 14:22
Thanks. Pardon my ignorance -- how does this work on other platforms / devices? 
@mananjadhav what are you thoughts?

**Comment by JosueEchandiaAsto** [comment] 2022-06-14 15:25
@flodnv In webkit browsers (chrome, safari). the <option> tag can't be styled through CSS. This depends on the operating system.
In Firefox, some styles can be styled via CSS, for example: font-family can be assigned a custom font, but it depends on whether the font exists in the OS.

This is a list of <option> tag:
![Captura de Pantalla 2022-06-14 a la(s) 10 24 10](https://user-images.githubusercontent.com/16966456/173615675-59c6c96f-0575-478b-b19a-8dec0a50f68f.png)

**Comment by mananjadhav** [comment] 2022-06-15 06:33
Please give me time to check possible causes for FF. I vaguely we had set up `@font-face` and relative paths to the fonts in FF for other projects. Let still find some information and get back.

Thank you for your comments @JosueEchandiaAsto.

**Comment by mananjadhav** [comment] 2022-06-16 08:03
Thanks for the insights @JosueEchandiaAsto.

@flodnv I spent some time digging into different approaches to solve this. @JosueEchandiaAsto is right, that the `option` tag doesn't inherit the page/parent font. We can set styles like bold, etc, but not `font-family`. 

I tried multiple faces to force font and `@font-face`, etc. but none of them worked. I also checked other apps like Slack. They don't use the default `select-option` tag for dropdown, but a custom implementation with `div-span`.

**We have the following ways to approach this:**

1. Do nothing as no functionality is breaking or is such a bad UX which makes the app/feature unusable. Firefox has about 7% users.
2. Add a fallback font like `Serif` that firefox supports by default.
3. Replace the `Picker` component to something that uses `div-span` so that appropriate styling can be performed.

Let me know your thoughts.

**Comment by flodnv** [comment] 2022-06-17 19:01
Thanks @mananjadhav. I posted in Slack about this https://expensify.slack.com/archives/C01GTK53T8Q/p1655492405932969 (which we should do when we have to make such big decisions)

**Comment by michaelhaxhiu** [comment] 2022-06-20 12:18
@flodnv & @mananjadhav - Should we **hold on doubling the price of this job** this until we reach a verdict on how to style dropdown options in New Expensify?

**Comment by flodnv** [comment] 2022-06-21 13:32
Agreed, HOLDing!

**Comment by michaelhaxhiu** [comment] 2022-07-25 16:13
Closing per discussion in the slack thread above 👆 . This will be fixed when we re-work the `push to page` functionality (i.e. dropdowns are going away).

**Closed by michaelhaxhiu** 2022-07-25 16:13 UTC
Labels: Exported, External, Engineering, Monthly, Help Wanted
