### ISSUE TITLE
Web - Delete/edit popover in wallet has only delete option when clicked twice

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26517] opened 2023-09-01 19:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to settings -> wallet
2. Add a payment method eg. PayPal
3. Click on PayPal option.
4. Again click on PayPal option.

## Expected Result:
Delete/edit popover should close as we close other popover when clicked twice or Both edit and Delete option should be in popover.

## Actual Result:
 Popover with only Delete option still visible. if clicked PayPal option is clicked multiple time there's Popover flicker

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/39521aa1-0399-4d3e-a240-3c240cd4fef3

https://github.com/Expensify/App/assets/93399543/76cf9f5c-89e2-405c-a5c6-2747c2efc67f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693082286543769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ishpaul777** [comment] 2023-09-01 21:50
## Proposal
### Problem
Delete/edit popover in wallet has only delete option when clicked twice

### Root Cause 
Delete/edit popover should be a toggle popover as Add paymentmethod.

### Changes
we need to pass a anchorref to PaymentMethodList as prop and add the same to MenuItem in PaymentMethodList. (if PaymentMethod is selected method)

Adding more details soon...

**Comment by sonialiap** [comment] 2023-09-12 06:45
Closing as dupe

**Closed by sonialiap** 2023-09-12 06:45 UTC
Labels: Daily, Overdue, Bug
