### ISSUE TITLE
[$500]  Workspace - Workspace name character limit is 80 instead of 100

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36352] opened 2024-02-12 17:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .4.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33601
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings
3. Select a workspace
4. Go to Profile > Name
5. Enter text more than 100 words

## Expected Result:
The workspace name character limit is 100

## Actual Result:
The workspace name character limit is 80 instead of 100

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ec321b3e-b41d-44a4-b124-2a4a7c4ced6c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016db8b2a4859b7008</li>
        <li>Upwork Job ID: 1757089411969716224</li>
        <li>Last Price Increase: 2024-02-12</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-12 17:09
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by godofoutcasts94** [comment] 2024-02-12 17:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Workspace - Workspace name character limit is 80 instead of 100

### What is the root cause of that problem?

It is set to `WORKSPACE_NAME_CHARACTER_LIMIT: 80`

https://github.com/Expensify/App/blob/4ff57926cd5edb60c60082c13618cfcf787dcbc0/src/CONST.ts#L1574

### What changes do you think we should make in order to solve the problem?

set the `WORKSPACE_NAME_CHARACTER_LIMIT: 100`

Working Image 

Before 
<img width="1470" alt="Screenshot 2024-02-12 at 10 48 36 PM" src="https://github.com/Expensify/App/assets/158435970/163fa60c-74f3-49df-8ee6-c6cb3e4b1893">

After 
<img width="1470" alt="Screenshot 2024-02-12 at 10 47 27 PM" src="https://github.com/Expensify/App/assets/158435970/25e9518a-a436-4574-96e2-e1f78fdc4531">

**Comment by godofoutcasts94** [comment] 2024-02-12 17:27
Update [Proposal](https://github.com/Expensify/App/issues/36352#issuecomment-1939188195)

**Comment by youssef-lr** [comment] 2024-02-12 17:52
This should be fixed as part of [this](https://github.com/Expensify/App/issues/18647). Closing this.

**Closed by youssef-lr** 2024-02-12 17:52 UTC
Labels: External, Daily, Help Wanted, Bug
