### ISSUE TITLE
[PAID] [$500] Distance- Expense preview does not show the updated currency when distance currency is changed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34066] opened 2024-01-05 20:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat
2. Create a distance request
3. Go to distance details page
4. Click Amount
5. Change the currency and save it
6. Return to expense report page

## Expected Result:
The distance preview will show the updated currency

## Actual Result:
The distance preview does not show the updated currency

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4facf212-ee84-4995-b5f2-b024b95f9480

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f1b7774b1ba5d7d3</li>
        <li>Upwork Job ID: 1743373752148869120</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28091955</li>
<li>bernhardoj | Contributor | 28091956</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-01-05 21:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The currency for distance request preview doesn't update when we update the currency.

### What is the root cause of that problem?
This only happens with distance request preview. If we look at the normal review, we get the currency from `requestCurrency`, but for distance request, we get it from `transaction.currency` which holds the first currency when we create the transaction.
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/components/ReportActionItem/MoneyRequestPreview.js#L223-L237

`requestCurrency` itself is coming from `TransactionUtils.getCurrency` that gets either `modifiedCurrency` or `currency`.
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/libs/TransactionUtils.ts#L287-L293

### What changes do you think we should make in order to solve the problem?

Use `requestCurrency` for distance request too

**Comment by strepanier03** [comment] 2024-01-09 04:31
Looks good, I'll work on tying this to a wave or VIP tomorrow.

**Comment by strepanier03** [comment] 2024-01-09 22:23
Thanks @jjcoffee, I'll add to the VIP/Wave when I get confirmation.

**Comment by thienlnam** [comment] 2024-01-10 03:26
This looks like it might fit under vip-vsb

**Comment by bernhardoj** [comment] 2024-01-10 04:37
PR is ready

cc: @jjcoffee

**Comment by jjcoffee** [comment] 2024-01-25 09:48
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/24556/
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/24556/files#r1466105952
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A - just required more thorough testing
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open a policy expense chat
2. Create a distance request
3. Press the request preview once to open the expense report
4. Press the request preview again to open the request/transaction detail thread
5. Edit the currency to another currency
6. Go back to the expense report
7. Verify the distance request preview currency is updated

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2024-01-25 09:49
@strepanier03 Friendly bump for payment!

**Comment by strepanier03** [comment] 2024-01-26 22:34
Dang, another one where the automation didn't work to move this over to Daily. I'll work on this now.

**Comment by strepanier03** [comment] 2024-01-26 23:11
All paid up. Handling reg test and then closing.

**Comment by strepanier03** [comment] 2024-01-26 23:13
Thanks everyone 👋

**Closed by strepanier03** 2024-01-26 23:13 UTC
Labels: External, Daily, Awaiting Payment, Bug
