### ISSUE TITLE
[HOLD for payment 2024-01-09] [$250] Chat - When mentioning users, the avatar icon is blank

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33657] opened 2023-12-27 19:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33479

## Action Performed:
1. Access the New Expensify App
2. Sign into a valid account (I used a HT account)
3. Go to any chat and use the mention feature "@"and search for a user like "Expensify Concierge" for example

## Expected Result:
User expects all avatars to show when using the mention feature

## Actual Result:
Multiple users avatars are missing, showing as blank green icon (Repro on both light and dark mode)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/0eaf441b-eb01-4be9-84df-561e45b2cfb0)

https://github.com/Expensify/App/assets/93399543/53e646e4-3906-449e-997b-9756efd46e0f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140012cc347f832e3</li>
        <li>Upwork Job ID: 1740090789811859456</li>
        <li>Last Price Increase: 2023-12-28</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 28071843</li>
<li>paultsimura | Contributor | 28071844</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-12-27 19:31
@paultsimura Seems it is after [PR](https://github.com/Expensify/App/pull/33634), We only need to consider `here` for filling the success color.
```
fill={isIcon ? theme.success : undefined}
```
https://github.com/Expensify/App/pull/33634/files#diff-3e66159ec7e545cdb519881ff0194d3e2151d3d3c9a963bf2b82e46b3119a92cR75

**Comment by paultsimura** [comment] 2023-12-27 19:38
@Pujan92 thanks for the tag. Could you reproduce this issue on your side?
I couldn't neither on Prod nor in Dev. Tried incognito mode just to make sure there is no cache – still couldn't reproduce:

<img width="1137" alt="image" src="https://github.com/Expensify/App/assets/12595293/49766890-fdd8-4d10-83a9-9fb41447d6ba">

**Comment by Pujan92** [comment] 2023-12-27 19:43
I am able to reproduce it on the native.

https://github.com/Expensify/App/assets/14358475/53c34ca8-e64d-4965-81f9-901e5145588e

**Comment by paultsimura** [comment] 2023-12-27 20:51
You're right @Pujan92, thank you for pointing this out.
Looks like this is a regression from https://github.com/Expensify/App/issues/33589. I will spin up a fixing PR now.

**Comment by mountiny** [comment] 2023-12-28 19:51
Assigning @paultsimura as this is related to PR from them and me as a reviewer, but no payment for the PR as its a regression

**Comment by mountiny** [comment] 2023-12-28 19:55
Given the original issue where the fix caused this regression was $250, I am going to adjust the value here to $250 too as it would not make sense to have this fix higher reward than the original

**Comment by slafortune** [comment] 2024-01-10 14:14
@shubham1206agra can you please complete the above checklist?

**Comment by slafortune** [comment] 2024-01-10 14:17
@shubham1206agra @paultsimura please accept the offers that had been sent, I'll adjust the amount from $500 to $250 when I pay them.

**Comment by shubham1206agra** [comment] 2024-01-10 14:24
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/33634
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/33634/files#r1447454237
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No as Applause already has this test in deploy suite here https://github.com/Expensify/App/issues/33589
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@slafortune] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by paultsimura** [comment] 2024-01-10 14:25
Accepted, thanks.

**Closed** 2024-01-11 21:48 UTC
Labels: External, Daily, Awaiting Payment, Bug
