### ISSUE TITLE
[$500] Scan - "Receipt scanning failed. Please enter the details manually" is visible to requestee

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31140] opened 2023-11-09 16:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [User A] Go to chat with User B > + > Request money > Scan
2. [User A] Create a Scan request with a receipt that will fail the smartscanning
2. [User B] Open the Scan request details page when the smartscanning fails
Note that User B can see the Receipt scanning failed message which also asks User A to enter the details manually

## Expected Result:
"Receipt scanning failed. Please enter the details manually" message will not appear to User B

## Actual Result:
"Receipt scanning failed. Please enter the details manually" message appears to User B. It is giving the impression that User B is asked to enter the details manually, when the message is aimed at User A

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6270183_1699546745794!IMG_0726](https://github.com/Expensify/App/assets/78819774/b57b6d4b-2270-40b1-a8dd-17a5d796713c)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0904e9e5de86b0d</li>
        <li>Upwork Job ID: 1722652686187794432</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by SrR0b0** [comment] 2023-11-09 18:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The message shown to the author of scan request when the scan fails also appears to the other users who are assigned in the request. The message prompts the user to upload a new image to be scanned but it doesn't make sense to prompt other users than the author of the request for such a thing.

### What is the root cause of that problem?

The root cause of the problems is in the logic right where the `MoneyRequestConfirmationList` component decides whether to show the `"iou.receiptScanningFailedMessage"` error message.

https://github.com/Expensify/App/blob/5cff53ba5b71bc328d359dbc447cf7dc9157ddb1/src/components/MoneyRequestConfirmationList.js#L275-L278

The problem is that it is not checked whether the user session belongs to the author of the request.

### What changes do you think we should make in order to solve the problem?

Simply adding another message in the translation files for the case the error is being rendered for some user that's not the author of the request and adding a conditional logic in the `MoneyRequestConfirmationList` component to render the proper message would be enough and quite certainly wouldn't introduce any regressions.

### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment] 2023-11-12 12:53
**Debugging observations:**
- when the scan request fails the `notifications@expensify.com`'s message is only shown by re-visiting the report or refreshing the page, I'm assuming this is pusher event related
- `iou.receiptScanningFailedMessage`: `'Receipt scanning failed. Enter the details manually.'` is different than the `notifications@expensify.com`'s message `Receipt scanning failed. Please enter the details manually.` which comes from the back-end after request scan failure, not from the front-end translation

considering these observations I think this issue should be fixed from the back-end where the pusher event notification for when a receipt scan failed should only be sent to the requestor. If a message is needed on the requestee side too, then the message should differ from the one sent to the requestor.

It should be fixed from the back-end because on the front-end side there's no solid way to check for the `notifications@expensify.com`'s scan failed message and hide it both from the report threads preview and and also from within the thread itself.

**Comment by dylanexpensify** [comment] 2023-11-14 10:04
confirming something here!

**Comment by trjExpensify** [comment] 2023-11-14 11:41
👋 Coupla' things.. 

1. The system message is added to the transaction thread visible for all to see as part of the audit history, it's not a whisper message just for the requestor. This part my might be pending wave6 updates but; nobody is subscribed to the transaction thread by default, so they don't get notified about the sys message when added, and I believe this will be made an @-mention for the submitter too with wave6 so they continue to be when receipt scanning fails (CC: @puneetlath @mountiny) 
2. The RBR; so the red dot on the request row when it appears in the LHN as "receipt missing details" and the in-line error messages on the merchant, date and amount rows in error on the request detailed view are only visible for the submitter of the request as it's an action for them to take.
3. When the hold project is done, a failed receipt scan should automatically go on hold and will be visible to all as being on hold, but that's a wave7 initiative. (CC: @robertjchen @JmillsExpensify). 
4. The Expensify user is in the process of being given a display name and Expensify iconmark, the issue for that is [here](https://github.com/Expensify/Expensify/issues/335426). (CC: @Gonals).

As for these: 

>when the scan request fails the notifications@expensify.com's message is only shown by re-visiting the report or refreshing the page, I'm assuming this is pusher event related

Agreed, it shouldn't require a refresh or navigating away/back for the sys message to appear in the transaction thread when the receipt scan fails. 

> iou.receiptScanningFailedMessage: 'Receipt scanning failed. Enter the details manually.' is different than the notifications@expensify.com's message Receipt scanning failed. Please enter the details manually. which comes from the back-end after request scan failure, not from the front-end translation

I agree the FE/BE error messages should be the same. The one from the doc is `Receipt scanning failed. Please enter the details manually` for ref, but I actually don't mind dropping the "please" for brevity and standardising on that. Ah actually, I bet the FE error was added and only used in the split case for the "read-only" confirmation page in the RHP which is a little bit more like a form error atop a button to action on trying to recreate the split after fixing the errors as there is no transaction thread here to add a system message from Expensify. (CC: @youssef-lr).

**Comment by DylanDylann** [comment] 2023-11-17 09:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We have inconsistency between the message from FE and system message 
From FE (using in EditingSplitBillPage: 'Receipt scanning failed. Enter the details manually.'
System Message (using in the transaction thread): 'Receipt scanning failed. Please enter the details manually'

### What is the root cause of that problem?
We have inconsistency between the message from FE and system message 
From FE (using in EditingSplitBillPage: 'Receipt scanning failed. Enter the details manually.'
System Message (using in the transaction thread): 'Receipt scanning failed. Please enter the details manually'

### What changes do you think we should make in order to solve the problem?
We need to update the message in FE to match the system message (Spanish too). Or we also update the new message and use it in both FE and BE for consistency

### What alternative solutions did you explore? (Optional)

**Comment by dylanexpensify** [comment] 2023-11-17 09:50
thanks @trjExpensify for the notes! Closing

**Comment by DylanDylann** [comment] 2023-11-17 10:04
@dylanexpensify What do you think about this point in [@trjExpensify's comment](https://github.com/Expensify/App/issues/31140#issuecomment-1810047413)
> I agree the FE/BE error messages should be the same. The one from the doc is Receipt scanning failed. Please enter the details manually for ref, but I actually don't mind dropping the "please" for brevity and standardising on that

**Comment by trjExpensify** [comment] 2023-11-17 10:42
Yeah, to be clear I think there appear to be two things uncovered from this issue to work on: 

1. It shouldn't require a refresh or navigating away/back for the sys message to appear in the transaction thread when the receipt scan fails. What's going on with that pusher event? (CC: @Gonals here)
2. The FE/BE error messages are using slightly different copy. Even though they are used in different places, let's standardise. Meaning, update the sys message one to `Receipt scanning failed. Enter the details manually.` dropping the "please".

**Comment by mountiny** [comment] 2023-11-20 11:55
Reopening as it seems like we are not done here based on the latest comments

**Comment by dylanexpensify** [comment] 2023-11-22 09:23
Good call, reviewing today!

**Comment by dylanexpensify** [comment] 2023-11-22 10:58
Agree with @trjExpensify's comments - @DylanDylann do you have a proposal that would tackle those two points he brought up? cc @eVoloshchak

**Comment by DylanDylann** [comment] 2023-11-22 13:26
@dylanexpensify My proposal will not fix 2 above bugs, we need to fix on BE side

**Comment by eVoloshchak** [comment] 2023-11-27 14:58
To summarize, we have 3 issues than need to be resolved

1. Update the system message to `Receipt scanning failed. Enter the details manually` dropping the "please". - needs to be done on back end
2. The refresh or navigating away/back is required for the system message to appear in the transaction thread when the receipt scan fails. Adding to this, until you open a transaction on User A's device, it will not be marked as "scan failed" for User B
3. The system message is added to the transaction thread visible for all to see as part of the audit history - looks like [it will be resolved](https://github.com/Expensify/App/issues/31140#issuecomment-1810047413) in wave6

@DylanDylann, can item 2 be resolved on the front end?

**Comment by DylanDylann** [comment] 2023-11-28 04:29
@eVoloshchak I tested again and saw that If User A requests money by scanning image to User B, User B sees this request only when it is a success or failure. If the receipt is scanning, It doesn't display on User B

In case the scanning fail, the error message will display immediately in transaction thread (note that: transaction thread only be accessed when request fail)

**Comment by dylanexpensify** [comment] 2023-12-05 20:01
@eVoloshchak mind giving an update

**Comment by dylanexpensify** [comment] 2023-12-11 09:25
bump @evol

**Comment by dylanexpensify** [comment] 2023-12-11 09:25
bump @eVoloshchak

**Comment by dylanexpensify** [comment] 2023-12-13 08:47
bump @eVoloshchak

**Comment by evoL** [comment] 2023-12-13 09:12
@dylanexpensify It's possible that they didn't receive the notification because, well, I did. I'd recommend reaching out to them through different means.

I've already reported this issue to GitHub, no response yet.

**Comment by eVoloshchak** [comment] 2023-12-13 22:23
@dylanexpensify, apologies for the delay
There are two sub-tasks left for this:

1. Update the system message to Receipt scanning failed. Enter the details manually dropping the "please". - needs to be done on back end
2. The system message is added to the transaction thread visible for all to see as part of the audit history - looks like https://github.com/Expensify/App/issues/31140#issuecomment-1810047413 in wave6

This needs an internal engineer to make a small change on the back end, after which we might put this on hold for wave6

**Comment by dylanexpensify** [comment] 2023-12-20 09:32
Perfect, will get a volunteer/tribute!

**Comment by eVoloshchak** [comment] 2024-01-03 18:48
Not overdue, https://github.com/Expensify/App/issues/31140#issuecomment-1864142734

**Comment by dylanexpensify** [comment] 2024-01-09 12:22
still asking around

**Comment by dylanexpensify** [comment] 2024-01-15 11:49
Woot! @rlinoz how's this coming along?

**Comment by rlinoz** [comment] 2024-01-16 14:01
Opening a PR today to avoid the need to refresh the page to get the scan failed message.

**Comment by dylanexpensify** [comment] 2024-01-17 09:28
Wooot!

**Comment by rlinoz** [comment] 2024-01-22 13:49
PR is merged, waiting for deploy 😄

**Comment by dylanexpensify** [comment] 2024-01-23 13:30
Woooot!

**Comment by rlinoz** [comment] 2024-01-24 13:53
This has been deployed to production!

Can we close it?

**Comment by dylanexpensify** [comment] 2024-01-26 11:47
Payment summary:
- Contirbutor+: @eVoloshchak $500

Please request!

**Closed** 2024-01-26 11:46 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by JmillsExpensify** [comment] 2024-02-03 18:29
$500 approved for @eVoloshchak based on summary above.

**Comment by youssef-lr** [comment] 2024-02-05 16:19
@eVoloshchak did we have an App PR for this, or only a backend fix?

**Comment by JmillsExpensify** [comment] 2024-02-05 23:16
Holding on approving this one until we get clarity.

**Comment by eVoloshchak** [comment] 2024-02-06 17:30
I thought we did update the system message to `Receipt scanning failed. Enter the details manually` on front end, but looking at https://github.com/Expensify/App/issues/31140#issuecomment-1828000293, this was done on the back end
I don't think I'm eligible for payment on this one, apologies for the confusion everyone

**Comment by youssef-lr** [comment] 2024-02-06 17:32
All good, thanks for confirming!

**Comment by JmillsExpensify** [comment] 2024-02-06 17:37
No worries! Thanks
