### ISSUE TITLE
Task - Can't mark as done task that user set to "Assigned to me"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21311] opened 2023-06-22 13:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Login as user A on Web and user B on other environment (e.g. Desktop app or different browser);
Users A & B are members of same group DM.

1. Open http://staging.new.expensify.com/
2. As user B send a task into group DM without assignee
3. As user A open the same chat
4. Click on the same task
5. Click on Task header
6. Click on "Assign to me" user profile
7. Click on "Mark as Done"
8. As user B open same task report

## Expected Result:
At step 7 Assigned task is successfully marked as done
At step 8 user B can see that this task is now assigned to user A

## Actual Result:
At step 7 Assigned task is not "marked as done"
At step 8 user B still see that the task doesn't have an assignee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9c9a5447-1915-4cdf-9f9b-1cd8bb759238

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2023-06-22 18:49
@thienlnam Do we have anything like a clean up milestone for polish/bugs related to the tasks feature?

**Comment by thienlnam** [comment] 2023-06-22 18:57
I've just been adding it to the Expensify Tasks project to keep track of bugs

Though this issue looks like a dupe of this https://github.com/Expensify/App/issues/20542
We essentially need the onyx failure to set an error on the reportAction

**Closed by thienlnam** 2023-06-22 18:57 UTC
Labels: Daily, Bug
