### ISSUE TITLE
Android- Chat - Message combinations sent offline showing again after delete it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13314] opened 2022-12-04 15:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12626

## Action Performed:
1. Launch the app
2. Log in with any account
3. Open a chat
4. Scroll all the way back to the beginning. Verify that you see the report welcome message at the start of the chat.
5. Send a few messages in the chat. (1,2,3)
6. Verify that the new chats appear in order at the end of the chat.
7. Turn off your internet
8. Send a few more messages in the chat. (Test 1, Test 2, Test 3)
9. Those chats should appear as pending while you're offline, but they should appear in the correct order at the end of the chat.
10. Come back online.
11. The chats should become finalized and no longer be pending.
12. Delete a message (Test1) verify that it disappears.

## Expected Result:
Delete message should be disappear

## Actual Result:
Message combinations sent offline showing again after delete it

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.36.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/205498184-32fb18ed-32bc-4009-b49d-4a97eaa705f6.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment] 2022-12-07 01:02
I wasn't able to reproduce this on the production app v1.2.35 so it sounds specific to the current staging. That said, it looks enough of an edge case that we shouldn't block the deploy on this, in my opinion. Would you agree @luacmartins?

**Comment by strepanier03** [comment] 2022-12-08 03:04
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [ ] The "bug" is actually a bug 
- [ ] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [ ] The bug is reproducible, following the reproduction steps.
  - [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [ ] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  - [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [ ] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [ ] The GH was created by an Expensify employee or a QA tester 
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [ ] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by strepanier03** [comment] 2022-12-08 03:10
I was unable to reproduce this on staging on my Android Pixel 6.

**Comment by luacmartins** [comment] 2022-12-08 19:54
I can't reproduce this either. My guess is that a pending request got stuck due to the `sequenceNumber` bug and that will be addressed by the design doc. I think we should close this issue.


https://user-images.githubusercontent.com/22219519/206554119-de26e2e3-7e00-4a97-a3de-5229d86cc878.mov

**Comment by strepanier03** [comment] 2022-12-11 22:36
Sounds good @luacmartins - I tested again today with the same resutls so I'm closing this for now and we can reopen later on if we need to.

**Closed by strepanier03** 2022-12-11 22:36 UTC
Labels: Daily, Bug
