### ISSUE TITLE
[HOLD for payment 2024-07-25] [$250] [CVP] Update Workspace auto naming to include using First Name over the username of a public email. 

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#42677] opened 2024-05-27 22:33 UTC
Problem: If a user does not have a private domain email or input a business name, we'll use the username of their email to name the workspace even if we have better information, like their first or last name. This makes for a confusing workspace name and potentially confusing first time experience for them and their users.

Solution: Update the logic when auto-naming a private workspace such that if we do not have a private domain or business name:
1. If the user inputs a business name, use that. If not,
2. Use the private domain if they have that. If not,
3. Use the their First and/or Last name. If not,
4. Use their email username. If not,
5. Use their phone number.

1-2 should already be the case. But now we'll just auto name workspaces that are created (example: Daniel Vidal's workspace) if the user has input the first name and/or last name. For clarity, we should input the first and/or last name as the workspace name. So even if only one is input that is better than a public email user name. 

Please let me know what else I should help to clarify. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010eb95e450e743861</li>
        <li>Upwork Job ID: 1795571574937968640</li>
        <li>Last Price Increase: 2024-05-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by brunogschaefer** [comment] 2024-05-29 04:38
### Please re-state the problem that we are trying to solve in this issue.
Update Workspace auto naming to include using First Name over the username of a public email

### What is the root cause of that problem?
UX related to auto naming of new workspaces

### What changes do you think we should make in order to solve the problem?
My suggestion is to abstract the behaviour of `generateDefaultWorkspaceName` function, so that it doesn't  just work with the user's email as the default policy name, but with the business name, private domain, first and/or last name, username of the email or telephone number (in this priority sequence).
https://github.com/Expensify/App/blob/2a7d5d497ebec61171c7033ff85cdd0731d710c5/src/libs/actions/Policy/Policy.ts#L1966-L1977

Based on SOLID principles, `generateDefaultWorkspaceName` wouldn't need to pass email as parameter anymore. We could use the `allPersonalDetails` attribute to gather more information as needed, so we can work on the expected behavior.

I didn't test the code, but just to illustrate my main idea, it would be something like this. There's a lot to be improved but I didn't had much time to it

`function generateDefaultWorkspaceName(): string {
    const policyName: string = allPersonalDetails?.[ownerAccountID];
    const email: string = allPersonalDetails?.[ownerAccountID]?.login ?? '';

    const emailParts = email ? email.split('@') : sessionEmail.split('@');
    let defaultWorkspaceName = '';
    if (!emailParts || emailParts.length !== 2) {
        return defaultWorkspaceName;
    }
    const username = emailParts[0];
    const domain = emailParts[1];

    // I need more information regarding the business name
    if (!policyName?.phoneNumber) {
        defaultWorkspaceName = `${Str.UCFirst(phoneNumber)}'s Workspace`;
    }
    else if (PUBLIC_DOMAINS.some((publicDomain) => publicDomain === domain.toLowerCase())) {
        defaultWorkspaceName = `${Str.UCFirst(username)}'s Workspace`;
    }
    else if (!policyName?.firstName || !policyName?.lastName) {
        const firstName = policyName?.firstName ?? '';
        const lastName = policyName.lastName ?? '';
        defaultWorkspaceName = `${Str.UCFirst(firstName.concat(lastName))}'s Workspace`;
    } else {
        defaultWorkspaceName = `${Str.UCFirst(domain.split('.')[0])}'s Workspace`;
    }`

### What alternative solutions did you explore?
The ideal solution would be to work with a single object containing all the relevant data sanitized and validated. Than we wouldn't need to waste performance by splitting the email into user and domain.

**Comment by brunogschaefer** [comment] 2024-05-29 04:41
Contributor details
Your Expensify account email: brunogschaefer@outlook.com
Upwork Profile Link: [Upwork Profile](https://www.upwork.com/freelancers/~01771991f3b84d2fa3?mp_source=share)

**Comment by getusha** [comment] 2024-05-30 03:28
@GandalfGwaihir after applying your solution it doesn't seem to get the correct first name or last name. could you share a complete code snippet or a branch? @brunogschaefer same. thanks!

>// I need more information regarding the business name

@brunogschaefer i think a user will be able to enter a business name when it's a new account (on Onboarding step)

**Comment by danielrvidal** [comment] 2024-05-30 04:29
@GandalfGwaihir for this:
>if we have business name as well as first name and last, after the onboarding flow, the first workspace which gets created get the name of the business name but when we create new workspaces after the initial one, we use the user email in subsequent workspaces. is that intended or that should also be fixed?

Thanks for bringing that up. I think we would use the logic outlined after the business name. So it would be:
1. Use the private domain if they have that. If not,
2. Use the their First and/or Last name. If not,
3. Use their email username. If not,
4. Use their phone number.

If they are creating a second workspace they are likely trained so it's not as important but we should make the logic the same. Thank you!

**Comment by brunogschaefer** [comment] 2024-06-01 03:30
> @GandalfGwaihir after applying your solution it doesn't seem to get the correct first name or last name. could you share a complete code snippet or a branch? @brunogschaefer same. thanks!

I've tested with some changes and it worked, but I have some observations. I will change my proposal a little bit, if you guys don't mind.
The main idea didn't change, but I had to make some changes in order to work

**Please re-state the problem that we are trying to solve in this issue.**
Update Workspace auto naming to include using First Name over the username of a public email

**What is the root cause of that problem?**
Definition of policy auto naming to new workspaces

**What changes do you think we should make in order to solve the problem?**
Most changes were made on the method `generateDefaultWorkspaceName` here [App/src/libs/actions/Policy/Policy.ts](https://github.com/Expensify/App/blob/2a7d5d497ebec61171c7033ff85cdd0731d710c5/src/libs/actions/Policy/Policy.ts#L1970-L1971)

I've created a method to set the default name based on the new rules 
 
![image](https://github.com/Expensify/App/assets/68888545/d6e368af-6b72-48fc-a55c-8b2831859b90)

The rules were made based on the logic that I've posted on my other proposal. Basically, an if condition for each rule. I've made some changes in order to work and to be more concise, but the idea remains the same.
I've got most of the data from the already defined attribute `allPersonalDetails` in the class

But in order for this to work, I had to change functions `createDraftInitialWorkspace` and `createDraftWorkspace` from the same class, so that the const workspace will only receive the return from the generateDefaultWorkspaceName, like this

![image](https://github.com/Expensify/App/assets/68888545/34594d92-4327-4ff5-9577-5f1e328efa74)

But I've some observations regarding this @danielrvidal 

> > if we have business name as well as first name and last, after the onboarding flow, the first workspace which gets created get the name of the business name but when we create new workspaces after the initial one, we use the user email in subsequent workspaces. is that intended or that should also be fixed?
> 
> Thanks for bringing that up. I think we would use the logic outlined after the business name. So it would be:
> 
> 1. Use the private domain if they have that. If not,
> 2. Use the their First and/or Last name. If not,
> 3. Use their email username. If not,
> 4. Use their phone number.
> 
> If they are creating a second workspace they are likely trained so it's not as important but we should make the logic the same. Thank you!

I'm able to create a new account with the business name, but the business name doesn't seems to be stored anywhere except from the initial auto-generated workspace. 
So my code works ok when a new account is created with a business name. The very first workspace will be created with the business name, but that's it. The subsequent workspaces will use those rules that we are talking about.
I don't know if I understood your comment correctly Gandalf, but this is the expected behavior?
If it doesn't, than I would probably need more time so that I could figure out how to get the business name.

Anyway, this is a video evidence of my tests. I couldn't test the first rule (private domain) since I don't have one, but I get the private domain from the same source as the e-mail username (and check if it isn't a public domain), so it shouldn't be a problem

https://github.com/Expensify/App/assets/68888545/59b718e2-2973-4d7b-9412-a7fb1b816fcd

Any doubts, please feel free to reach me anytime

**What alternative solutions did you explore?**
N/A

**Comment by danielrvidal** [comment] 2024-06-04 03:51
@trjExpensify regarding @brunogschaefer question around if we store business name anywhere, I imagine he is correct. We do not store "Business name" we just ask for that in the UI and then update the workspaceName if they fill out that field in onboarding. So I think his approach is correct. Can you confirm?

**Comment by trjExpensify** [comment] 2024-06-04 21:51
>We do not store "Business name" we just ask for that in the UI and then update the workspaceName if they fill out that field in onboarding.

Right, if you go the "Manage my team's expenses" path it's mandatory to enter a business name and we just set that as the workspaceName:

<img width="519" alt="image" src="https://github.com/Expensify/App/assets/16232057/d4013462-17ca-4557-80ad-206e2fcd8710">

I can't see any additional data storage for that.

So @danielrvidal, what cases are you primarily thinking about accommodating here?

- Bottom up submit > pay with business bank account > workspace is created
- Clicking `New workspace` in product somewhere to create a new one

An alternative approach would be to ask for a business name in those flows, so they can set a name for their workspace. Then we'll always have the name they want to give their workspace, instead of the waterfall:

> If the user inputs a business name, use that. If not,
> Use the private domain if they have that. If not,
> Use the their First and/or Last name. If not,
> Use their email username. If not,
> Use their phone number.

Was that discounted for a good reason? Maybe we didn't want to put an additional step in the bottom up > workspace flow or something was it?

**Comment by danielrvidal** [comment] 2024-06-05 03:34
> An alternative approach would be to ask for a business name in those flows, so they can set a name for their workspace. Then we'll always have the name they want to give their workspace, instead of the waterfall:

Yea, I just don't think we considered adding the modal in scope because I'm not sure how we'd fit it in. For the viral onboarding flows, we ask for the first name before we take them to the workspace chat. But we don't know it's a business until the pay via BBA. We discussed putting it in the BBA flow but people thought we should let them get through BBA before asking them another question. So we could add the modal somewhere, I'm just not sure where yet so this was a smaller update.

**Comment by trjExpensify** [comment] 2024-06-05 23:45
Cool, fair enough! @getusha you cool with one of these proposals then, or are there any clarifying questions to resolve?

**Comment by getusha** [comment] 2024-06-06 19:36
>Also, when i checked, if we have business name as well as first name and last, after the onboarding flow, the first workspace which gets created get the name of the business name but when we create new workspaces after the initial one, we use the user email in subsequent workspaces. is that intended or that should also be fixed?


@allgandalf can you expand on your question? i am not sure i understand.

**Comment by danielrvidal** [comment] 2024-06-10 12:05
@getusha, I think I answered @allgandalf question you mention above [here](https://github.com/Expensify/App/issues/42677#issuecomment-2138655746). Let me know if there are still questions.

**Comment by trjExpensify** [comment] 2024-06-11 00:12
@getusha can you get to this one in the morning so we keep it moving? Thanks!

**Comment by getusha** [comment] 2024-06-11 00:23
>If the user inputs a business name, use that. If not,

@trjExpensify based on the discussion above, we are skipping ^ correct?

**Comment by brunogschaefer** [comment] 2024-06-11 03:27
I apologize for extending this conversation, but the functional requirements still seems a little bit unclear for me aswell. I think rewriting it would benefit everyone by avoiding eventual unnecessary mistakes.
It seems to me that there's more than one use case (at least three from my understanding), as mentioned by Tom:

> So @danielrvidal, what cases are you primarily thinking about accommodating here?
> 
> * Bottom up submit > pay with business bank account > workspace is created
> * Clicking `New workspace` in product somewhere to create a new one

(there's the workspace created from the onboarding process aswell)

I know that this might be out of scope, but wouldn't be simpler and convenient to persist the business data before any of those use cases (i. e. at the onboarding stage)? This would solve the problem we are discussing here and it would eventually enable the app to suggest the business name when connecting to a business bank account, for instance.

> But we don't know it's a business until the pay via BBA

With all due respect, this seems a little bit odd to me when a business name was already provided at the onboarding stage.

**Comment by danielrvidal** [comment] 2024-06-11 09:47
We don't ask for the business name in all of onboarding, and in this particular case the user:
1. Is invited to Expensify via an IOU request
2. Opens the app via a link from email or SMS
3. Is taken to the IOU (which might be paid as personal)
4. Decides to pay via a business bank account, at which time we create a workspace for them. 

We are going to be inputting onboarding before they are taken to the IOU, but it will just be in getting their name. We still won't know whether or not they are going to be creating a workspace or not. I hope that clarifies things. 

@getusha does this make sense to you, and do one of the proposals work for this?

**Comment by getusha** [comment] 2024-06-12 13:55
Testing the proposals, i'll update today

**Comment by getusha** [comment] 2024-06-13 07:49
1. Use the private domain else,
2. Use first name and last name else,
3. Use email username else,
4. Use phone number

@danielrvidal, @allgandalf proposal covers these conditions. what do you think?

**Comment by danielrvidal** [comment] 2024-06-13 16:12
That looks good to me, thank you!

**Comment by getusha** [comment] 2024-06-17 12:47
Thanks everyone! @allgandalf's [proposal](https://github.com/Expensify/App/issues/42677#issuecomment-2136203635) looks good to me.
🎀 👀 🎀 C+ Reviewed.

**Comment by chiragsalian** [comment] 2024-06-17 19:09
Proposal LGTM, feel free to create a PR @allgandalf.

**Comment by danielrvidal** [comment] 2024-06-19 22:24
Awesome, thank you! Looking forward to it.

**Comment by danielrvidal** [comment] 2024-06-25 03:43
Awesome, thank you! @getusha let me know if you run into any questions on the review.

**Comment by danielrvidal** [comment] 2024-07-09 00:35
It looks like @getusha ran into some issues but @allgandalf just asked if we have it figured it out in this thread: https://github.com/Expensify/App/pull/44109 

Let us know if you have questions @getusha !

**Comment by getusha** [comment] 2024-07-09 11:43
>It looks like @getusha ran into some issues but @allgandalf just asked if we have it figured it out in this thread: https://github.com/Expensify/App/pull/44109

I was able to build it successfully after pulling from the main branch. Thanks!

**Comment by stephanieelliott** [comment] 2024-07-25 17:22
Hey @danielrvidal, coming from this [Slack conversation](https://expensify.slack.com/archives/C01GTK53T8Q/p1721904603484179),   a heads up that I've issued the $250 payment for @allgandalf on [this Upwork job ](https://www.upwork.com/jobs/~01cc34421cab2bf55c). Will let you post the payment summary though!

**Comment by danielrvidal** [comment] 2024-07-25 17:25
Awesome, should we close the GH then? I don't know the process after payment.

**Comment by stephanieelliott** [comment] 2024-07-25 17:32
@danielrvidal I can wrap it up for you since I already made the payment! But generally the steps to close out the issue are: 

1. Create the regression test (not applicable for this issue)
2. Post the the payment summary 
3. Pay in Upwork 
4. Close the Upwork contract.

**Comment by stephanieelliott** [comment] 2024-07-25 17:33
Summarizing payment on this issue: 

 - Contributor: @allgandalf $250 via Upwork - PAID
 - Contributor+: @getusha $250 via NewDot - please request 
 
 Upwork job is here: https://www.upwork.com/jobs/~01cc34421cab2bf55c

**Closed by stephanieelliott** 2024-07-25 17:33 UTC
Labels: Daily, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-07-25 17:50
$250 approved for @getusha
