### ISSUE TITLE
[$250] mWeb - IOU - As employee, after submitting expense submit button reappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42155] opened 2024-05-14 14:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4558080
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-condition : As admit set currency USD, select schedule submit as manual and also select submit and approve.
1. Go to https://staging.new.expensify.com/
2. Tap employee workspace chat
3. Create an expense
4. Open the expense and tap submit button shown on the header

## Expected Result:
As employee, after submitting expense submit button must not reappear.

## Actual Result:
As employee, after submitting expense submit button reappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/80e736a8-6498-4069-8393-7761c183e041

https://github.com/Expensify/App/assets/78819774/b17558ad-a79a-4b4a-a755-ea72faea70d7

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a59dd40a3c1d5086</li>
        <li>Upwork Job ID: 1793383398935375872</li>
        <li>Last Price Increase: 2024-05-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by lanitochka17** [comment] 2024-05-14 14:07
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by anmurali** [comment] 2024-05-22 20:48
Hmm, it seems I am also getting this weird `chat room has been archived` message at the bottom of the page

https://github.com/Expensify/App/assets/14225673/ccd4d7cb-92e1-43d0-957e-8eb9adbba1fb

**Comment by samilabud** [comment] 2024-05-23 15:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.



### What is the root cause of that problem?
It seems the new module "@expensify/react-native-live-markdown" is the root cause, when we pass it through our RNMarkDownTextInput component (`markdownStyle={markdownStyle}`):

https://github.com/Expensify/App/blob/84290e42da3794c621b792725222a8d7c16664b6/src/components/Composer/index.tsx#L324-L332

### What changes do you think we should make in order to solve the problem?
As the @expensify/react-native-live-markdown component is out of our control (externals) I suggest marking it as internal, meanwhile we can use the [RNMarkDownTextInput](https://github.com/Expensify/App/blob/84290e42da3794c621b792725222a8d7c16664b6/src/components/Composer/index.tsx) without the new markdown styles, like:

```
<RNMarkdownTextInput
                autoComplete="off"
                autoCorrect={!Browser.isMobileSafari()}
                placeholderTextColor={theme.placeholderText}
                ref={(el) => (textInput.current = el)}
                selection={selection}
                style={[inputStyleMemo]}
                value={value}
                defaultValue={defaultValue}
                autoFocus={autoFocus}
                /* eslint-disable-next-line react/jsx-props-no-spreading */
                {...props}
                onSelectionChange={addCursorPositionToSelectionChange}
                onContentSizeChange={(e) => {
                    setTextInputWidth(`${e.nativeEvent.contentSize.width}px`);
                    updateIsFullComposerAvailable({maxLines, isComposerFullSize, isDisabled, setIsFullComposerAvailable}, e, styles);
                }}
                disabled={isDisabled}
                onKeyPress={handleKeyPress}
                onFocus={(e) => {
                    ReportActionComposeFocusManager.onComposerFocus(() => {
                        if (!textInput.current) {
                            return;
                        }

                        textInput.current.focus();
                    });

                    props.onFocus?.(e);
                }}
            />
```

Test after changes:

https://github.com/Expensify/App/assets/5216036/907609eb-3687-4ac7-971f-793668f63057

**Comment by anmurali** [comment] 2024-06-05 02:28
This bug seems to be fixed now. I am closing this.

**Closed by anmurali** 2024-06-05 02:28 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
