### ISSUE TITLE
[HOLD for payment 2023-06-28] Web - Group chat - "Invalid email" error message appears when creating a group DM with Concierge

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21040] opened 2023-06-19 14:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to any account
2. Click Fab > New group
3. Select any random email and concierge as members
4. Click "Create Group"

## Expected Result:
Group is created successfully

## Actual Result:
Invalid email error message appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:**  Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5d9ffdd2-867a-442c-aaaa-b2b6728c2be6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment] 2023-06-19 18:00
https://github.com/Expensify/Web-Expensify/pull/37753 appears to be the root cause for this as well. We're passing empty string as the login for concierge because the client doesn't have it:

![Screenshot 2023-06-19 at 1 59 23 PM](https://github.com/Expensify/App/assets/6833644/39f9edbb-9e03-4dce-bc56-710bc1a92ab1)

FWIW, I'm not sure you're supposed to be able to make a group chat with concierge

**Comment by Beamanator** [comment] 2023-06-20 17:45
Looks like we DO want to be able to create group chats w/ concierge, but not some other expensify emails: https://github.com/Expensify/App/issues/8586

**Comment by Beamanator** [comment] 2023-06-20 17:51
as of right now now I'm unable to reproduce in `main` / `main` / `main`

**Comment by Beamanator** [comment] 2023-06-20 18:22
Here's [some logs](https://staging.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227da5f4f158d6100a-SJC%22)+AND+timestamp:[2023-06-20T17:08:23.375Z+TO+2023-06-20T19:08:23.375Z]&index=logs_expensify-022899) from when I reproduced in `main` / staging

**Comment by Beamanator** [comment] 2023-06-20 19:06
So ya technically this is fixed for starting group chats w/ `Concierge` - now we're chatting about starting group chats w/ other people who you don't have their `login`

**Comment by jasperhuangg** [comment] 2023-06-20 21:54
This is fixed by https://github.com/Expensify/App/pull/21159

**Comment by bondydaa** [comment] 2023-06-21 14:25
removing blocker as this is fixed for group chats with concierge. if there _is_ a new bug about group dms for different cases then lets spin up a new issue.

**Comment by puneetlath** [comment] 2023-06-21 14:42
I just tested a few different scenarios of creating group chats on staging and they all seemed to work.

**Comment by jasperhuangg** [comment] 2023-06-21 17:15
Let's close this out then?

**Comment by Beamanator** [comment] 2023-06-22 12:35
Agreed, no payment due here so we can close 👍

**Closed by Beamanator** 2023-06-22 12:35 UTC
Labels: Engineering, Weekly, Awaiting Payment
