### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] App changes emoji tax number to actual number, causing confusion for user during manual bank account connection

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21065] opened 2023-06-19 18:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the app settings.
2. Navigate to your workspace.
3. Navigate to the bank account section.
4. Manually connect a bank account using routing number 074000078 and account number 12345.
5. Add company information and use the tax number :zero::nine::zero::nine::zero::nine::zero::nine::zero:. Click continue.
6. Observe that the app does not differentiate the emoji number in the tax number field from the actual numbers, causing confusion for the user. When the user goes back to the form, the app changes the emoji number to the actual number.

## Expected Result:
 The app should differentiate the emoji number in the tax number field from the actual numbers and display a relevant error message if an incorrect format is entered. The app should not change the emoji number to the actual number; instead, it is preferable to display an error message initially.

## Actual Result:
The app changes the emoji number in the tax number field to the actual number, causing confusion for the user.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (82) (1).webm](https://github.com/Expensify/App/assets/93399543/1e005fdb-9c8a-4da2-95a2-4bd6d40410bf)

https://github.com/Expensify/App/assets/93399543/792e4a02-1c2d-4c4a-aba6-4864312ffb70

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686476984591029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018839cf0c086e82de</li>
        <li>Upwork Job ID: 1671530734389030912</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-06-21 14:49
😂 that is odd behavior, let's throw an error. Triaging to external

**Comment by eh2077** [comment] 2023-06-22 03:32
Hi @parasharrajat , from Slack [discussion](https://expensify.slack.com/archives/C049HHMV9SM/p1687359264741359?thread_ts=1686476984.591029&cid=C049HHMV9SM), the team suggested to fix ZIP and Tax ID together. Do you agree with it? If you do, then I'll be also happy to fix them together by combining my [proposal](https://github.com/Expensify/App/issues/21062#issuecomment-1597551341) from the other issue. 

cc @sonialiap

**Comment by sonialiap** [comment] 2023-06-22 15:19
Ah, thanks for pointing out that the root causes are different @eh2077, I don't have insight into the code part of the problem so that wasn't something I was aware of.

**Comment by sonialiap** [comment] 2023-06-22 15:24
@parasharrajat US Tax ID numbers and US zipcodes consist of only numbers. When you type a letter into both fields in NewDot _now_, it throws an error about unsupported input. US tax IDs and zipcodes definitely do not consist of emojis :trollface: so we should be throwing an error if a user enters an emoji.

Throwing errors is more in line with our existing practices than preventing input, so I think throwing an error is the way to go with this one. 

To clarify, the tax ID and zip code fields should only accept numerals `0 1 2 3 4 5 6 7 8 9` and a dash `-`

**Comment by sonialiap** [comment] 2023-07-03 13:41
@parasharrajat any update? :)

**Comment by srikarparsi** [comment] 2023-07-05 16:24
Thanks @parasharrajat! @eh2077's proposal looks good to me as well, assigning you to the issue!

**Comment by eh2077** [comment] 2023-07-06 08:53
@parasharrajat The PR https://github.com/Expensify/App/pull/22280 is ready for review, thanks!

**Comment by Christinadobrzyn** [comment] 2023-07-06 18:04
Hey @parasharrajat @eh2077 curious if you think this [issue](https://github.com/Expensify/App/issues/22301) will be resolved with this PR? Issue: when entering an account number "XXX868713" the 'X' is accepted as a number.

**Comment by eh2077** [comment] 2023-07-07 06:54
Hi @Christinadobrzyn , this PR can't fix the issue you mentioned because their root causes are different.

**Comment by eh2077** [comment] 2023-07-20 01:25
Friendly bump @sonialiap This is ready for payment

**Comment by sonialiap** [comment] 2023-07-21 14:31
Apologies for the delay! Somehow I missed this issue 🙈 

@eh2077 offer sent for fix (+bonus)
@tewodrosGirmaA - paid for reporting issue ✔️ 
@parasharrajat - to be paid for review(+bonus) via NewDot

**Comment by sonialiap** [comment] 2023-07-21 14:43
Upwork paid and request to add regression test submitted, closing

**Closed by sonialiap** 2023-07-21 14:43 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-07-27 05:11
Reviewed details for @parasharrajat. This is accurate based on summary from Business Reviewer and approved for payment in NewDot.
