### ISSUE TITLE
Chat - Two windows remain open using Keyboard shortcuts

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26908] opened 2023-09-06 20:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Press CTRL + J then CTRL + K
3. Press CTRL + K then CTRL + J

## Expected Result:
The behavior must be consistent in both cases.
The first window should close when another one is opened

## Actual Result:
In the first case, the first window is closed when the second one is opened, in the second case, the two windows remain open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] Windows / Chrome
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.65-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ca4314e1-1ea3-4144-8bb3-74bddccc0b7b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment] 2023-09-07 05:05
I don't think it's expected that these two actions should behave consistently:

Press CTRL + J then CTRL + K
Press CTRL + K then CTRL + J 

This seems like expected behaviour for both actions. Closing as not a bug.

**Closed by kadiealexander** 2023-09-07 05:05 UTC
Labels: Daily, Bug
