### ISSUE TITLE
[$500] Bank account - User is redirected to BA page when paying with Expensify and BA is set up

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32112] opened 2023-11-28 13:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** cannot check the production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: Workspace has a Chase bank account set up via Connect online with Plaid method.
1. Go to the workspace chat.
2. Create a workspace expense (Manual).
2. Click Pay with Expensify.
3. Click Business bank account.

## Expected Result:
User will be redirected to the next payment step.

## Actual Result:
User is redirected to workspace bank account page although the bank account is already set up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e0d88944-1139-4773-8380-2ca070e2fae5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb3238d2b83fb332</li>
        <li>Upwork Job ID: 1729823536743481344</li>
        <li>Last Price Increase: 2024-02-07</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by johnmlee101** [comment] 2023-11-28 16:28
Hmm all of our code regarding the business bank account refers to setup in our code. 
https://github.com/Expensify/App/blob/a13781346cc018970d6794708bedf3e1098aaad0/src/components/AddPaymentMethodMenu.js#L98
https://github.com/Expensify/App/blob/23dda79b2511b2cad0ea8f2381ee1e291ad40ee6/src/components/KYCWall/BaseKYCWall.js#L102
https://github.com/Expensify/App/blob/1163dc3837dfb04a985f3106026ede7b77108cca/src/pages/settings/Wallet/WalletPage/WalletPage.js#L204

@flodnv it looks like you changed this code most recently however, curious on your thoughts. Maybe this shouldn't be a blocker yet

**Comment by johnmlee101** [comment] 2023-11-28 16:30
Actually this was the commit I was looking at: https://github.com/Expensify/App/commit/e564ecc90c7f6c2af1edb22b78161e24eb352f44

**Comment by johnmlee101** [comment] 2023-11-28 16:32
@mountiny https://github.com/Expensify/App/pull/30582/files#diff-8c06fd96ed7306e88ac43532f2b2cdbc6a46c9914847c6d9f4c14c45af7f36cbR92 I think it originated from the addition here?

**Comment by mountiny** [comment] 2023-11-28 16:56
Discussing in [slack](https://expensify.slack.com/archives/C07J32337/p1701189821899029?thread_ts=1701189230.200889&cid=C07J32337)

**Comment by johnmlee101** [comment] 2023-11-28 22:26
Demoting this since its a very edge-case flow we're debugging, and it requires more time to investigate- but we won't need to block on it

**Comment by mountiny** [comment] 2023-11-29 11:23
So I have done some more testing locally and it just seems that the `reimbursementAccount` onyx key is being deleted somewhere as you navigate from the bank account flow to the report to be paid. If you sign out and sign back in, the bank account is loaded correctly, when you go to the workspace bank account settings, api call loads the correct bank account and then you can pay just fine.

I think we can make this external for more eyes

**Comment by johnmlee101** [comment] 2023-12-19 21:06
No update

**Comment by johnmlee101** [comment] 2024-01-23 21:49
no update

**Comment by johnmlee101** [comment] 2024-01-30 20:52
Same

**Comment by johnmlee101** [comment] 2024-02-06 21:54
Adding bug label to get a bug-zero team member included here

**Comment by rezkiy37** [comment] 2024-02-12 14:50
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2024-02-13 13:31
Can I ask you to clarify: how to connect a bank account to a **workspace**? I was able to connect to my account, but it is not clear how to complete with a workspace configuration. I used the **staging** server. I completed all steps before like verifying identity, filled forms out. Used **Fidelity Bank** with test credentials. Should I wait for something or...?

https://github.com/Expensify/App/assets/57314631/f4dd46bb-cc5b-4200-ba8d-c09c81cce981

**Comment by muttmuure** [comment] 2024-02-13 18:34
@hayata-suenaga do you know if [this is expected behavior](https://github.com/Expensify/App/issues/32112#issuecomment-1941530749) above? Navigating back should go to the previous page right?

**Comment by muttmuure** [comment] 2024-02-14 11:27
Not overdue

**Comment by rezkiy37** [comment] 2024-02-14 14:31
I confirm the bug still exists on the latest `main`.

https://github.com/Expensify/App/assets/57314631/48c443d1-d6ee-4ba4-813b-daf2717eeeca

**Comment by hayata-suenaga** [comment] 2024-02-14 17:16
@rezkiy37 do you have an idea what might be the issue?

**Comment by rezkiy37** [comment] 2024-02-15 10:01
> @rezkiy37 do you have an idea what might be the issue?

@hayata-suenaga, I posted a [question](https://github.com/Expensify/App/issues/32112#issuecomment-1941520374) and asked how to reproduce this flow. The problem exists between those lines: 
https://github.com/Expensify/App/blob/98a51b3eabde795163a4fbc5b18ecde8029764ad/src/components/KYCWall/BaseKYCWall.tsx#L128-L137

**Comment by hayata-suenaga** [comment] 2024-02-15 17:52
@rezkiy37 could you ask the question in #open-source channel?

**Comment by rezkiy37** [comment] 2024-02-16 09:51
> @rezkiy37 could you ask the question in #open-source channel?

Looks like we found an answer [here](https://github.com/Expensify/App/issues/35721#issuecomment-1944534881). Trying today.

**Comment by rezkiy37** [comment] 2024-02-16 14:06
I've successfully added a bank account to my workspace and account. 
Actually, the app has a condition once a user clicks on "Pay with Expensify", the app does not show a drop down menu with debit card or business bank account, when the user has at least 1 connected bank account. So, seems like the bug is not replicable and the "Action Performed" list is not relevant anymore. Please re-test.

https://github.com/Expensify/App/assets/57314631/6d0b2b95-6cf9-4a5b-92ee-68628c3601d9

**Comment by hayata-suenaga** [comment] 2024-02-16 16:42
[asking the QA team](https://expensify.slack.com/archives/C9YU7BX5M/p1708101737805039) for retest

**Comment by hayata-suenaga** [comment] 2024-02-16 18:55
[QA team confirmed](https://expensify.slack.com/archives/C9YU7BX5M/p1708105767058499?thread_ts=1708101737.805039&cid=C9YU7BX5M) that the issue still exists

**Comment by hayata-suenaga** [comment] 2024-02-19 16:16
The QA team tested with your comment in mind, and they were able to confirm the issue still exists. @rezkiy37 please resume work on this 🙇

**Comment by rezkiy37** [comment] 2024-02-20 13:13
Well, let me try one more time.

**Comment by rezkiy37** [comment] 2024-02-20 13:30
@hayata-suenaga, can I ask you to provide more info. I need `KYC Wallet` logs, they are available on the staging **ND** in the console ([example](https://github.com/Expensify/App/issues/32112#issuecomment-1948446876)). Also, I tried with another bank, because there are test credentials. How can I test with a Chase account?

<img width="910" alt="Screenshot 2024-02-20 at 14 21 45" src="https://github.com/Expensify/App/assets/57314631/dd34a389-1d31-4acd-b935-213ca3c4abcf">

**Comment by kavimuru** [comment] 2024-02-20 18:45
@rezkiy37 tester added test cards as a payment card. 
![image](https://github.com/Expensify/App/assets/43996225/f508c9b6-a3ad-4630-9285-75c1c090beb3)

**Comment by rezkiy37** [comment] 2024-02-21 15:04
I've tried to reproduce the bug one more time on the latest `main`. It still works properly from my end. Please let me what I am doing wrong on an attached video below. 

https://github.com/Expensify/App/assets/57314631/8b556b94-fb11-4e1f-87d4-892b6ddfec5a

**Comment by hayata-suenaga** [comment] 2024-02-21 17:15
@rezkiy37 can you test this on staging? if the staging fails and it works on main, maybe some recent PR fixed it.

**Comment by rezkiy37** [comment] 2024-02-22 10:52
@hayata-suenaga, just tested on staging on the same account and workspace. It works properly.

https://github.com/Expensify/App/assets/57314631/419b0fca-4f00-4234-a4f5-adec9373b01e

**Comment by hayata-suenaga** [comment] 2024-02-22 15:40
as this issue is not reproducible, I'm closing this issue

**Comment by lanitochka17** [comment] 2024-03-18 14:35
Issue is still reproducible on the latest build 1.4.53-2


https://github.com/Expensify/App/assets/78819774/c1ecc730-0946-4d9c-8cab-65dc6dde017e

**Comment by hayata-suenaga** [comment] 2024-03-18 18:45
@rezkiy37 @fedirjh could you check back this issue and what step we need to take next? 🙇

**Comment by rezkiy37** [comment] 2024-03-25 13:51
I've tried to reproduce with the same account and configs I had before. I cannot see the problem.

https://github.com/Expensify/App/assets/57314631/a87c56cb-09e1-4c25-97f6-1abbe7840987

**Comment by hayata-suenaga** [comment] 2024-03-25 17:32
seems like this is not reproducible anymore. closing this issue

**Closed by hayata-suenaga** 2024-03-25 17:32 UTC
Labels: External, Engineering, Daily, Overdue, Bug
