### ISSUE TITLE
[$250] Full links on chat messages lose the hyperlink when the message is edited

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#10530] opened 2022-08-24 14:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Write a full link (⁦`https://www.google.com`) in the chat and send the message.
2. It shows as a clickable link:
<img width="331" alt="Screen Shot 2022-08-24 at 4 11 08 PM" src="https://user-images.githubusercontent.com/19366280/186440753-3e2af379-bbbd-43c6-bcb3-15154efa1a80.png">

3. Edit the message, don't change anything and save the changes.

## Expected Result:
The link remains clickable

## Actual Result:
The link is no longer clickable:
<img width="339" alt="Screen Shot 2022-08-24 at 4 12 48 PM" src="https://user-images.githubusercontent.com/19366280/186442370-1de178aa-b12a-43a4-a396-a206e69207b9.png">

## Workaround:
Copy the link on your browser

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:*1.1.89* 
**Reproducible in staging?:*Yes* 
**Reproducible in production?:*Yes* 
**Email or phone of affected tester (no customers):*alberto@expoensify.com* 
**Issue reported by:*Alberto* 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2022-08-24 14:31
Going to take this since I'm working on the contributor management team!

**Comment by Christinadobrzyn** [comment] 2022-08-24 14:39
I wonder if this will be resolved with this job https://github.com/Expensify/App/issues/9332 

@flodnv could you take a peek at this ^ issue and let me know if you think it's unique from [this](https://github.com/Expensify/App/issues/9332)

**Comment by flodnv** [comment] 2022-08-24 16:27
@Christinadobrzyn I kinda doubt it, but could be wrong

**Comment by varshamb** [comment] 2022-08-24 17:18
Proposal

change this line to `const htmlForNewComment = parser.replace(textForNewComment)`


https://github.com/Expensify/App/blob/e504cc3d883a51294a3aca375dee28e66596edf4/src/libs/actions/Report.js#L1226

**Comment by Christinadobrzyn** [comment] 2022-08-24 17:28
Posted Job in Upwork 

External posting - https://www.upwork.com/jobs/~0167db6a4073dce20a
Internal posting - https://www.upwork.com/ab/applicants/1562491902073597952/job-details

**Comment by luacmartins** [comment] 2022-08-24 21:45
@rushatgabhane @mananjadhav yes, let's do an RCA for this. @mananjadhav can you lead the process? Here's the [doc](https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit#heading=h.8iom76ry1bp2)

**Comment by vladnobenladen** [comment] 2022-08-25 03:23
Here's RCA: https://github.com/Expensify/App/issues/4187#issuecomment-1220830528
The proposed solution on this comment will fix both issues - https://github.com/Expensify/App/issues/9090, https://github.com/Expensify/App/issues/10530

**Comment by vladnobenladen** [comment] 2022-08-25 03:42
Another suggestion:
https://github.com/Expensify/App/issues/10530#issuecomment-1226012865
This is revert of this [PR](https://github.com/Expensify/App/pull/9405) and I agree with this.
I haven't seen any other chat platforms yet (except GitHub comment) that displays `[]()` while trying to edit link.
Slack, Skype, WhatsApp, Telegram, etc all handles link automatically even when edit message, and this is more user friendly than markdown type ([]()).
Slack has more feature of customizing link and text but only when click link on input box (not directly showing markdown):

https://user-images.githubusercontent.com/97473779/186569479-ff86b958-3e93-4f4c-9fa6-737799c2eb0a.mov

**Comment by mananjadhav** [comment] 2022-08-25 03:53
Sure @luacmartins, give me a day I'll do the RCA.

**Comment by Santhosh-Sellavel** [comment] 2022-08-25 21:57
this is a duplicate of #9662

**Comment by neil-marcellini** [comment] 2022-08-26 17:18
Yep this is a duplicate, good find.

**Closed by neil-marcellini** 2022-08-26 17:18 UTC
Labels: Exported, External, Engineering, Weekly, Improvement, Help Wanted

**Comment by mananjadhav** [comment] 2022-09-09 22:10
@luacmartins @Santhosh-Sellavel @rushatgabhane @neil-marcellini RCA doc and the RCA spreadsheet updated. Apologies for the delay, this stopped giving notifications and it got slipped.

**Comment by neil-marcellini** [comment] 2022-09-12 16:24
Which row in [the spreadsheet](https://docs.google.com/spreadsheets/d/1u73RE8J1DdX3mDohV1RXgulF6_cke3N_a15Sk-UUdQo/edit?usp=sharing)?

**Comment by mananjadhav** [comment] 2022-09-12 16:26
Row 23, with date of regression `Aug 24, 2022`

**Comment by neil-marcellini** [comment] 2022-09-12 16:31
Thanks, great job on that! Did you send a summary in #expensify-open-source and could you please link it in the spreadsheet?
