### ISSUE TITLE
[$250] [#Wave-Control - Add Sage Intacct] Non-reimbursable options text turns gray when clicked

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45213] opened 2024-07-10 21:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43776
## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with the expensifail account
3. Navigate to Workspace settings - More features
4. Enable "Accounting"
5. Navigate to Accounting - Export - Export non-reimbursable expenses as
6. Click on "Credit card transactions"
7. Click on "Vendor bills"
8. Close the RHP
9. Navigate to Accounting - Export - Export non-reimbursable expenses as
10. Click on "Vendor bills"
11. Click on "Credit card transactions"

## Expected Result:
The text should stay white

## Actual Result:
Non-reimbursable options text turns gray when clicked. Only the first click makes the color change after opening the RHP. Clicking on the other option isn't changing the color

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c62acda9-fcb2-4f07-aa4d-47c7dba55999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010028a93d94af7536</li>
        <li>Upwork Job ID: 1811401490455645006</li>
        <li>Last Price Increase: 2024-07-11</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103079311</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by lanitochka17** [comment] 2024-07-10 21:07
@blimpich  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by blimpich** [comment] 2024-07-10 22:52
Added to the appropriate project so that the project organizer can triage, but this seems very low-priority to me since its just slightly off text color and in a place where exceedingly few customers will see in the next year.

Unassigning as well.

**Comment by mountiny** [comment] 2024-07-10 23:28
cc @yuwenmemon if you are handling it as well?

@blimpich its good to always find the project leader as well and ping them here or send a DM so they are aware and it does not slip through the cracks (there is many issues in the waave-control project)

**Comment by yuwenmemon** [comment] 2024-07-11 14:05
@war-in Can you have a look at this one?

**Comment by war-in** [comment] 2024-07-11 14:23
@yuwenmemon I'm currently looking 👀 The thing is connected with `PressableWithFeedback` component.

We use `OpacityView` there and set dimming when item is pressed. It works correctly on mobile (checked on android) but breaks on web. 
What I found is that `onPressOut` is not triggered just after `onPressIn` function. That's why the pressed component is dimmed.


https://github.com/Expensify/App/assets/61014013/04abef47-0181-4557-a937-7874164fe396

**Comment by hungvu193** [comment] 2024-07-11 14:30
This was caused during our review process of https://github.com/Expensify/App/pull/44739 (https://github.com/Expensify/App/pull/44739#issuecomment-2219455613). Since we already had an issue for this, let's push https://github.com/Expensify/App/pull/44739 forward.
Please assign me to this issue @yuwenmemon

**Comment by war-in** [comment] 2024-07-11 14:56
I found the root cause of the issue! It was wrong `handleMouseUp` prop in `BaseListItem` component.
Fortunately, it's already fixed on [main branch](https://github.com/Expensify/App/commit/212ddc15e09e87abfe25da83cc62f93b0926c2be) 🎉 

I think issue can be closed now :)

**Comment by hungvu193** [comment] 2024-07-11 16:00
Yes I can confirm that this issue is fixed 🎉. We can close it then 😄 

https://github.com/Expensify/App/assets/16502320/983e0137-e9fe-491e-b59a-3f6a8c75032c

**Comment by miljakljajic** [comment] 2024-07-11 17:14
Excellent!

**Closed by miljakljajic** 2024-07-11 17:14 UTC
Labels: External, Engineering, Daily, Bug
