### ISSUE TITLE
[HOLD for payment 2023-09-29] [$1000]  Android - Login - Linkified email from external app is pasted as linkified email in email field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21411] opened 2023-06-23 14:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Copy a linkified email address from external app (like gmail).
2. Launch New Expensify app.
3. Long tap on the email field.
4. Select Paste.

## Expected Result:
Email is not linkified

## Actual Result:
Email is linkified

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4cad0094-8387-4911-84be-0ead9294ba4e

![Bug6103773_Screenshot_20230623_155332](https://github.com/Expensify/App/assets/78819774/0e256751-a7e9-4ddc-916a-fdc1fbd01b30)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fec00bf5a9d050cf</li>
        <li>Upwork Job ID: 1673491584987435008</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by cubuspl42** [comment] 2023-06-23 20:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When pasting rich text to the e-mail field, the formatting is preserved, although we'd like the text to be plain text.

### What is the root cause of that problem?

On Android, `TextInput` for some reason is rich text input by default. It can contain initial formatted text, for example:

```jsx
<TextInput>
    Hello, <Text style={{color:'red'}}>World</Text>
</TextInput>
```

Also, formatted text can be pasted by the user.

### What changes do you think we should make in order to solve the problem?

Surprisingly, [there is no way to disable the rich text properties of the `TextInput`](https://github.com/zulip/zulip-mobile/issues/4660).

There is a workaround, though. One can heuristically detect when the text is pasted and change it to some other text (so the internal formatting markers are cleared), but immediately change it back.

We could introduce these helpers:

```js
const zeroWidthSpace = '\u8203';

/**
 * A very simple heuristic for detecting whether the text was pasted
 *
 * @param {String} oldText
 * @param {String} newText
 * @return {Boolean}
 */
function isTextPasted(oldText, newText) {
    return Math.abs(newText.length - oldText.length) > 1;
}

/**
 * A helper for setting a TextInput-managed state, which ensures that the
 * text keeps being plain, even when formatted text is pasted by the user.
 *
 * @param {Object} component
 * @param {Function} buildState
 * @param {String} oldText
 * @param {String} newText
 */
function setPlainTextInputState(component, buildState, oldText, newText) {
    if (isTextPasted(oldText, newText)) {
        // Set a similar but different text, so TextInput clears formatting markers
        component.setState(buildState(
            `${zeroWidthSpace}${newText}${zeroWidthSpace}`,
        ), () => {
            // Change back to the pasted text (in the plain text)
            component.setState(buildState(newText));
        });
    } else {
        // If it doesn't look like a paste, set the state directly to minimize flickering
        component.setState(buildState(newText));
    }
}
```

And then use them in `LoginForm`'s `onTextInput` method:

```js
    /**
     * Handle text input and clear formError upon text change
     *
     * @param {String} newText
     */
    onTextInput(newText) {
        setPlainTextInputState(
            this,
            (text) => ({login: text}),
            this.state.login,
            newText,
        );

        this.setState({
            formError: null,
        });

        // ...
    }
```

**Comment by Christinadobrzyn** [comment] 2023-06-23 22:10
I'm not able to replicate this - reaching out in Slack to get more specific directions on how the email is copied.

**Comment by cubuspl42** [comment] 2023-06-24 10:31
@Christinadobrzyn 

You can copy any link, for what it's worth. Let's say [from here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a). When I copied from Chrome, I had to use text selection.

https://github.com/Expensify/App/assets/2590174/3b432a29-5602-42fd-a8b5-bc42d61097a1

**Comment by Christinadobrzyn** [comment] 2023-06-27 00:40
I might not be able to get this to work on Browserstack but it seems like enough people can reproduce it so I'll send it to External.

**Comment by fabriziobertoglio1987** [comment] 2023-06-27 14:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Text is copy pasted as rich text on Android TextInput instead of Plain Text.

### What is the root cause of that problem?

Android EditText and iOS UITextField/UITextView have different copy/paste behavior.
- Android TextInput copies/pastes rich text
- iOS UITextField copies/pastes plain text.


| iOS (react-native)   | Android (react-native) |
| ----------- | ----------- |
| <video src="https://user-images.githubusercontent.com/24992535/249170968-8fde35f0-a53c-4c5c-bd89-ee822c08eadf.mp4" width="250" />      | <video src="https://user-images.githubusercontent.com/24992535/249171968-bf0915a0-4060-4586-b267-7c2b463d76f6.mov" width="250" />       |

### What changes do you think we should make in order to solve the problem?

The issue is a bug in react-native https://github.com/facebook/react-native/issues/31442:

1) Android and iOS should behave the same way ([platform parity](https://reactnative.dev/blog/2020/07/17/react-native-principles#every-platform)).
2) onChangeText passes a plain text string to JavaScript, not rich text (text with spans and styles).

The solution is over-riding `onTextContextMenuItem` in [ReactEditText](https://github.com/fabriziobertoglio1987/react-native/blob/71e7bbbc2cf21abacf7009e300f5bba737e20d17/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L82) to copy/paste plain text instead of rich-text.

https://stackoverflow.com/a/45319485/7295772
>Override the EditText's onTextContextMenuItem and intercept the android.R.id.paste to be android.R.id.pasteAsPlainText

I have included below the test performed in an Android App. I will include a test for the react-native implementation soon.

<details><summary>Reproducing the issue on Android</summary>
<p>

https://user-images.githubusercontent.com/24992535/249185416-76f8a687-1aca-4dc9-9abe-3d73d6e2893c.mp4

</p>
</details>

<details><summary>Fixing the issue on Android</summary>
<p>

Sourcecode https://github.com/fabriziobertoglio1987/text-input-cursor-flickering-android/blob/9db7784d30b09c497c32588d080d28cbc9b4aaf5/app/src/main/java/com/example/myapplication/CustomEditText.java#L48-L85

<video src="https://user-images.githubusercontent.com/24992535/249182757-a5dd08c2-38a0-424d-9afb-bf3ab5fa3a7e.mp4" width="1000" />

</p>
</details>

**Comment by s77rt** [comment] 2023-06-27 16:02
@fabriziobertoglio1987 Thanks for the proposal. Your RCA makes sense. I like the simplicity of the solution treating "Paste" as "Paste as plaintext" but then we will have two options that do the same thing, not really a blocker, but can we control the context menu options to show?

**Comment by s77rt** [comment] 2023-06-28 22:58
@fabriziobertoglio1987 Thanks for the update. I think we can start with treating "Paste" as "Paste as plaintext" (make a PR for that). Then we can make a follow up PR to hide the redundant "Paste as plaintext" if needed.

:ribbon: :eyes: :ribbon: C+ reviewed


BTW, can you please use heading styles instead of `<details>`. The details tag does not seem to support indent and this makes it hard to read the proposal. Heading levels are easier to read I think.

**Comment by pecanoro** [comment] 2023-06-29 20:40
This issue already had a CME, removing myself!

**Comment by s77rt** [comment] 2023-06-29 23:45
@pecanoro You accidentally unassigned @Gonals :sweat_smile:

**Comment by pecanoro** [comment] 2023-06-30 00:12
@s77rt Oh my bad 😆

**Comment by pecanoro** [comment] 2023-06-30 00:13
Hmm, I think Melvin got confused when I changed assignees.

**Comment by Christinadobrzyn** [comment] 2023-06-30 17:06
Hi @Gonals when you have a moment, can you review this suggestion from @s77rt 

https://github.com/Expensify/App/issues/21411#issuecomment-1612217992

**Comment by fabriziobertoglio1987** [comment] 2023-07-01 05:04
## Proposal
[Updated](https://github.com/Expensify/App/issues/21411#issuecomment-1611587431)

**Comment by fabriziobertoglio1987** [comment] 2023-07-01 05:04
## Proposal
[Updated](https://github.com/Expensify/App/issues/21411#issuecomment-1609674481)

**Comment by s77rt** [comment] 2023-07-01 11:23
@fabriziobertoglio1987 Thanks! @Gonals This is waiting for your review

**Comment by s77rt** [comment] 2023-07-03 22:31
Not overdue. @Gonals ^

**Comment by Gonals** [comment] 2023-07-04 07:56
> @fabriziobertoglio1987 Thanks for the update. I think we can start with treating "Paste" as "Paste as plaintext" (make a PR for that). Then we can make a follow up PR to hide the redundant "Paste as plaintext" if needed.
> 
> 🎀 👀 🎀 C+ reviewed
> 
> BTW, can you please use heading styles instead of `<details>`. The details tag does not seem to support indent and this makes it hard to read the proposal. Heading levels are easier to read I think.

Agreed with this!

**Comment by fabriziobertoglio1987** [comment] 2023-07-05 04:10
Thanks. I accepted the job on Upwork. I plan to publish the PR between 12th and 18th of July.

**Comment by Christinadobrzyn** [comment] 2023-07-05 20:59
Hired in Upwork: 
Internal job: https://www.upwork.com/ab/applicants/1673491584987435008/job-details
External job: https://www.upwork.com/jobs/~01fec00bf5a9d050cf

@s77rt as C+
@fabriziobertoglio1987 as contributor

**Comment by fabriziobertoglio1987** [comment] 2023-07-07 14:40
#### Update 07/07

- Did not detect any issues in the DRAFT PRs. I will move to ready to review soon
- Today, I had to investigate another issue (more info in https://github.com/Expensify/react-native/pull/57)

**Comment by s77rt** [comment] 2023-07-07 23:04
Working on it; Melvin

**Comment by fabriziobertoglio1987** [comment] 2023-07-08 14:05
### Update 08/07

- Did not detect issues with PRs https://github.com/facebook/react-native/pull/38210 and https://github.com/facebook/react-native/pull/38189. I will move the PRs to ready to review soon.
- Today I worked on another [issue](https://github.com/facebook/react-native/pull/37465#issuecomment-1625110372) for which I published PR [#38258](https://github.com/facebook/react-native/pull/38258).

**Comment by fabriziobertoglio1987** [comment] 2023-07-11 12:55
### Update 11/07
* Today, I worked on regression from PR [#38258](https://github.com/facebook/react-native/pull/38258). The update for that issue is [here](https://github.com/Expensify/react-native/pull/57#issuecomment-1630764901)
* I plan to restart working on this task on the 13th and move the PR to ready to review by the 18th. I did not detect any issue with PRs [38210](https://github.com/facebook/react-native/pull/38210) and [38189](https://github.com/facebook/react-native/pull/38189)

**Comment by fabriziobertoglio1987** [comment] 2023-07-13 07:41
### Update 12/07

* Found the [root](https://github.com/Expensify/react-native/pull/57#issuecomment-1631974179) cause of PR 38258 regression 
* I'll restart working on PRs [38210](https://github.com/facebook/react-native/pull/38210) and [38189](https://github.com/facebook/react-native/pull/38189) on the 14th of July

**Comment by fabriziobertoglio1987** [comment] 2023-07-14 13:27
### Update 14/07 
* Tested and Rebased PRs [38210](https://github.com/facebook/react-native/pull/38210) and [38189](https://github.com/facebook/react-native/pull/38189)
* Did not detected any issues with PRs 38210 and 38189. I plan to move the PRs to Ready to Review next week.
* Today I also worked on another task. I identified the root cause of the issue for https://github.com/facebook/react-native/pull/37465#issuecomment-1631974927 and started to test a solution for that issue.

**Comment by Christinadobrzyn** [comment] 2023-07-14 18:39
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're testing a PR. I'll take this when I'm back if it's still open.

**Comment by s77rt** [comment] 2023-07-14 21:45
We are working on it, Melvin

**Comment by fabriziobertoglio1987** [comment] 2023-07-15 12:56
### Update 15/07
* Did not detect any issues with PRs [38210](https://github.com/facebook/react-native/pull/38210) and [38189](https://github.com/facebook/react-native/pull/38189)
* Published new DRAFT PR for Issue [#17767](https://github.com/Expensify/App/issues/17767#issuecomment-1636757893)

**Comment by fabriziobertoglio1987** [comment] 2023-07-17 12:35
### Update 17/07
* Moved PRs [38210](https://github.com/facebook/react-native/pull/38210) and [38189](https://github.com/facebook/react-native/pull/38189) to Ready for Review

**Comment by s77rt** [comment] 2023-07-19 22:23
Not overdue. Still working on it.

**Comment by fabriziobertoglio1987** [comment] 2023-07-20 03:12
### Update 20/07
I will not work 20th, 21st, 23rd. I'll restart working 22nd July. PRs [38210](https://github.com/facebook/react-native/pull/38210) and [38189](https://github.com/facebook/react-native/pull/38189) are Ready for Review. Thanks.

**Comment by s77rt** [comment] 2023-07-22 00:17
This is still `External`. @Christinadobrzyn can you please fix the labels

**Comment by fabriziobertoglio1987** [comment] 2023-07-22 05:36
### Update 22/07
PRs [38210](https://github.com/facebook/react-native/pull/38210) and [38189](https://github.com/facebook/react-native/pull/38189) are Ready for Review. I will be on holiday starting from 10th of August.
I start to work on the next task and remain available for improvements. Thanks a lot.

**Comment by fabriziobertoglio1987** [comment] 2023-07-24 02:44
### Update 24/07
Added changes from [code review](https://github.com/facebook/react-native/pull/38189#pullrequestreview-1542055466) to PR #38189.

**Comment by fabriziobertoglio1987** [comment] 2023-07-26 02:31
#### Update 26/07

Minor Update. I'm not taking holiday from the 10th of August.

**Comment by fabriziobertoglio1987** [comment] 2023-07-27 03:40
### Update 27/07

Published changes for [code review](https://github.com/facebook/react-native/pull/38189#discussion_r1273654951).

**Comment by fabriziobertoglio1987** [comment] 2023-07-28 22:32
### Update 29/07

Commit [b1ceea456d1cdc00c723582d00e5ae585f066b55](https://github.com/facebook/react-native/commit/b1ceea456d1cdc00c723582d00e5ae585f066b55) landed on facebook main branch.

**Comment by Christinadobrzyn** [comment] 2023-07-31 18:30
Back from ooo - changed the labels per https://github.com/Expensify/App/issues/21411#issuecomment-1646352383

@fabriziobertoglio1987 can you confirm what PR we're currently reviewing for this?

**Comment by fabriziobertoglio1987** [comment] 2023-08-01 04:55
@Christinadobrzyn 

- PR https://github.com/facebook/react-native/pull/38189 has been merged in facebook/react-native main branch (commit https://github.com/facebook/react-native/commit/b1ceea456d1cdc00c723582d00e5ae585f066b55)
- **Expensify/react-native**: Expensify is updating react-native to 0.72 https://github.com/Expensify/App/pull/18507#issuecomment-1623610848
- **facebook/react-native@0.72.4**: I sent a cherry pick request for this [commit](https://github.com/facebook/react-native/commit/b1ceea456d1cdc00c723582d00e5ae585f066b55) in [0.72.4](https://github.com/reactwg/react-native-releases/discussions/83#discussioncomment-6601407), if they decline the cherry-pick request, we can ask again in the next release [0.73](https://github.com/reactwg/react-native-releases/discussions/64).
- **Expensify/react-native**: React Native and Expensify did not yet prepare 0.73 branch. 


Additionally, Expensify does not merge anymore PRs in Expensify/react-native fork:

https://github.com/Expensify/react-native/pull/55#issuecomment-1595567657

>Just for transparency, I think we have consensus that we'll no longer be using our react-native fork going forward. We should focus our efforts on upstream PRs instead. In this case, the upstream PR already landed so we will just need to wait for the first RC of 0.73 to use this.

https://github.com/Expensify/react-native/pull/54#issuecomment-1613877609

>Going to close this because we're no longer using our React Native fork.

I'm happy to open a PR in your Expensify/react-native fork, if required. 
I remain available. Thanks.

**Comment by Christinadobrzyn** [comment] 2023-08-02 20:25
I think this can be moved to weekly while we work on the ^ @s77rt @Gonals does that sound good to you?

**Comment by s77rt** [comment] 2023-08-02 23:09
@Christinadobrzyn Sounds good to me!

**Comment by fabriziobertoglio1987** [comment] 2023-08-08 23:14
#### Update 09/08

The commit was cherry picked in 0.72.4

**Comment by Christinadobrzyn** [comment] 2023-08-21 22:58
Hi @fabriziobertoglio1987 or @s77rt do you have an update on this?

**Comment by s77rt** [comment] 2023-08-22 00:23
@Christinadobrzyn RN 0.72.4 has been released last week. We need to upgrade to that version now. cc @roryabraham What's the process for a minor RN upgrade?

**Comment by roryabraham** [comment] 2023-09-01 15:35
Answered in slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1693582384169649

**Comment by s77rt** [comment] 2023-09-04 11:26
@fabriziobertoglio1987 Can you please prepare a PR to upgrade RN? (instructions are in the above link)

**Comment by fabriziobertoglio1987** [comment] 2023-09-05 23:27
### Update 06/09

I will start working on [upgrading RN](https://expensify.slack.com/archives/C01GTK53T8Q/p1693582384169649) on Saturday 09/09. Thanks

**Comment by fabriziobertoglio1987** [comment] 2023-09-09 09:06
### Update 09/09
- Upgraded Expensify to react-native 0.72.4. Did not detect issues. The fix works as expected.
- Started to check which patches were merged in the upstream branch

[untitled.webm](https://github.com/Expensify/App/assets/24992535/d9664323-1c14-4b9e-b898-4509572ce829)

**Comment by fabriziobertoglio1987** [comment] 2023-09-10 10:24
### Update 10/09

I prepared a branch for the PR. I tested the branch and did not detect issue, but most of the patches do not work on 0.72.4.

I will try to complete the task by the 13th of September, as I will not be away from the 14th of September. 

Branch https://github.com/Expensify/App/compare/main...fabriziobertoglio1987:App:upgrade-react-native-0.72.4?expand=1

Patches that can be deleted because already merged in the Upstream branch.
- react-native-sdk already merged to upstream ([patch](https://github.com/Expensify/App/blob/main/patches/@onfido+react-native-sdk+7.4.0.patch))
- react-navigation material-top already merged to upstream ([patch](https://github.com/Expensify/App/blob/main/patches/%40react-navigation%2Bmaterial-top-tabs%2B6.6.3.patch))
- react-navigation-native merged ([patch](https://github.com/Expensify/App/commit/4a6a58b7c54a807910af6b3d18253c0da6269d5f#diff-e55e67f769adb5ae13639c178048b1be6481c211f26fc3e94b958d8633c04744R173-R177), [upstream](https://github.com/react-navigation/react-navigation/blob/e432c32d1e346f7c40cb42772ae5b515c76ef297/packages/native/src/useLinking.tsx#L63-L69))
- Image manipulator already fixed with [commit](https://github.com/guhungry/react-native-photo-manipulator/commit/67b80ee214af8ae84600b7e5201dc8c00d7c589b)

Patches that need to be reapplied for 0.72.4. The changes needs to be applied manually.
- NumberOfLines (1000+ lines) https://github.com/Expensify/App/blob/main/patches/react-native%2B0.72.3%2B002%2BNumberOfLines.patch (more info in this [comment](https://github.com/Expensify/App/pull/18507#issuecomment-1631482878))
- VerticalScrollBarPosition (few lines) https://github.com/Expensify/App/blob/main/patches/react-native%2B0.72.3%2B003%2BVerticalScrollBarPosition.patch
- react-native-fast-image https://github.com/Expensify/App/blob/main/patches/react-native-fast-image%2B8.6.3.patch
- react-native-modal (few lines) https://github.com/Expensify/App/blob/main/patches/react-native-modal+13.0.1.patch
- Vision-camera (few lines [patch](https://github.com/Expensify/App/blob/main/patches/react-native-vision-camera+2.15.4.patch))
- React-native-web-lottie (1 line [patch](https://github.com/Expensify/App/blob/main/patches/react-native-web-lottie+1.4.4.patch))

**Comment by fabriziobertoglio1987** [comment] 2023-09-13 09:57
### Update 13/09

Published DRAFT pull request https://github.com/Expensify/App/pull/27320

**Comment by fabriziobertoglio1987** [comment] 2023-09-15 00:07
### Update 15/09

Completed DRAFT pull request https://github.com/Expensify/App/pull/27320 to upgrade to react-native 0.72.4. I will move the PR to ready to review this weekend.

**Comment by fabriziobertoglio1987** [comment] 2023-09-16 07:15
#### Update 16/09

Moved the PR to ready to review.

**Comment by s77rt** [comment] 2023-09-23 21:47
- The PR that introduced the bug has been identified: N/A This was a bug in RN
- The offending PR has been commented on: N/A
- A discussion in #expensify-bugs has been started: N/A
- Determine if we should create a regression test for this bug: No

**Comment by Christinadobrzyn** [comment] 2023-09-29 21:44
Payouts due:

Issue Reporter: NA
Contributor: $1000 @fabriziobertoglio1987 
Contributor+: $1000 @s77rt 

Eligible for 50% #urgency bonus? N based on https://github.com/Expensify/App/issues/21411#issuecomment-1726825986 but also it looks like the PR was created Sept 13th & merged Sept 19th - does that sound right? 

Upwork job is [here](https://www.upwork.com/jobs/~01fec00bf5a9d050cf).

**Comment by s77rt** [comment] 2023-09-29 22:59
@Christinadobrzyn Can you please double check the Upwork job. It seems unavailable.

**Comment by Christinadobrzyn** [comment] 2023-10-03 22:03
Hi @s77rt the Upwork job is closed, sorry I didn't realise that meant you couldn't see it. You and @fabriziobertoglio1987 were automatically hired so I can pay you still. 

Will you confirm the payment details here are good and I'll pay this? https://github.com/Expensify/App/issues/21411#issuecomment-1741520648

**Comment by s77rt** [comment] 2023-10-03 22:17
@Christinadobrzyn The payout summary looks correct 👍

**Comment by Christinadobrzyn** [comment] 2023-10-03 22:21
Perfect! Thanks for confirming @s77rt! 

I have paid both you and @fabriziobertoglio1987 based on the payment structure [here](https://github.com/Expensify/App/issues/21411#issuecomment-1741520648)

I'll close this out but please let me know if you need anything else!

**Closed by Christinadobrzyn** 2023-10-03 22:21 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
