### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] Profile - Account settings icon shows green dot with no other indication

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44804] opened 2024-07-04 04:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Complete onboarding (if using public domain).
3. Go to Account settings.

## Expected Result:
There should be a notice in the relevant section if the account settings icon has a green dot.

## Actual Result:
There is no notice in the relevant section if the account settings icon has a green dot.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/ea20b27f-fc0a-4c91-98c3-b2563828cea0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190b5223d5153c89d</li>
        <li>Upwork Job ID: 1808782166169156269</li>
        <li>Last Price Increase: 2024-07-04</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 102985244</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by m-natarajan** [comment] 2024-07-04 04:31
@strepanier03 FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-07-04 04:31
We think that this bug might be related to #vip-vsb

**Comment by madmax330** [comment] 2024-07-04 04:34
I also see this on my account

<img width="1347" alt="Screenshot 2024-07-04 at 8 33 57 AM" src="https://github.com/Expensify/App/assets/7016692/7747d4f7-ec91-4439-b136-b87135ed78cf">

**Comment by nkdengineer** [comment] 2024-07-04 06:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no notice in the relevant section if the account settings icon has a green dot.

### What is the root cause of that problem?
We're using `SubscriptionUtils.hasSubscriptionGreenDotInfo` to check the `infoCheckingMethods`

https://github.com/Expensify/App/blob/58be9bab7d4b82d9895027cdac4501723353c555/src/components/Indicator.tsx#L65

But this function doesn't work as expected. We use `!getSubscriptionStatus()?.isError` so this function also returns true if `isError` is `undefined`.
https://github.com/Expensify/App/blob/58be9bab7d4b82d9895027cdac4501723353c555/src/libs/SubscriptionUtils.ts#L354

### What changes do you think we should make in order to solve the problem?
We should only return `true` if the `isError` is `false`

```
return !getSubscriptionStatus()?.isError === false; 

```
https://github.com/Expensify/App/blob/58be9bab7d4b82d9895027cdac4501723353c555/src/libs/SubscriptionUtils.ts#L354

### What alternative solutions did you explore? (Optional)
NA

**Comment by madmax330** [comment] 2024-07-04 07:45
Thanks @nkdengineer were you able to find the PR that caused the regression?

**Comment by nkdengineer** [comment] 2024-07-04 07:47
@madmax330 This PR https://github.com/Expensify/App/pull/44072 caused the regression.

**Comment by madmax330** [comment] 2024-07-04 08:38
Going to assign @mananjadhav as c+ since they reviewed the offending PR

**Comment by nkdengineer** [comment] 2024-07-04 17:35
Will raise the PR tomorrow morning.

**Comment by tgolen** [comment] 2024-07-04 17:40
Is it at all possible to get a PR going today since this is a deploy blocker?

**Comment by nkdengineer** [comment] 2024-07-04 18:55
@mananjadhav The PR is [here](https://github.com/Expensify/App/pull/44862).
cc @tgolen

**Comment by mananjadhav** [comment] 2024-07-04 19:15
Thanks for raising the PR. Checking this.

**Comment by mananjadhav** [comment] 2024-07-04 19:24
@madmax330 Sorry I am a bit confused when do we want to show the green dot?

**Comment by mananjadhav** [comment] 2024-07-04 19:27
@nkdengineer Your proposal mentions only removing `?? false` with `=== false`. But I can see we've removed `!` from the condition too.

**Comment by nkdengineer** [comment] 2024-07-04 19:30
> We should only return true if the isError is false

@mananjadhav The code diff has a mistake, we should compare `getSubscriptionStatus()?.isError === false` as the idea I proposed in my proposal.

**Comment by mananjadhav** [comment] 2024-07-04 20:08
Thanks. The fix works well. @madmax330 All yours.

**Comment by mountiny** [comment] 2024-07-05 10:05
Pending a CP validation in staging

**Comment by mananjadhav** [comment] 2024-07-05 10:24
> Pending a CP validation in staging

What does this mean?

**Comment by mountiny** [comment] 2024-07-05 10:26
The fix has been cherry-picked to staging, and QA still has to re-test that CPed PR in staging to verify this issue if it is gone. Removing the blocker label because on the deploy checklist, the CPed PR has an unchecked box until QA verifies it was fixed

**Comment by mananjadhav** [comment] 2024-07-05 10:31
Okay thanks for clarifying!

**Comment by strepanier03** [comment] 2024-07-17 23:30
@nkdengineer - I've paid and closed the contract in Upwork. 

@mananjadhav - I'll check tomorrow for the checklist items above and once that's complete I'll post the payment summary so you can request payment.

**Comment by mananjadhav** [comment] 2024-07-18 20:40
@strepanier03 No payout for me here.

**Comment by strepanier03** [comment] 2024-07-19 18:23
Okay, thanks for the heads up @mananjadhav 🙌.

Can you finish up the checklist items so I can make a reg test if needed and close this out?

**Comment by mananjadhav** [comment] 2024-07-22 18:48
@strepanier03 I don't think we need a regression test for this one. The offending PR was already tagged and I posted a comment [here](https://github.com/Expensify/App/pull/44072/files#r1687005839)

> @madmax330 This PR #44072 caused the regression.

**Comment by strepanier03** [comment] 2024-07-24 04:05
Thanks for confirming @mananjadhav. Since I paid the other contract I'm closing this out. Thanks again everyone 🙌

**Closed by strepanier03** 2024-07-24 04:05 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
