### ISSUE TITLE
[HOLD for payment 2023-06-05] [$1000] Remove checkbox from Money request header

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19332] opened 2023-05-19 23:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account, go any request money report.
2. Hover the header title.
3. Notice a checkbox shows on the right side of the component

## Expected Result: 
No checkbox should appear

## Actual Result:   
A checkbox appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b1f1b1c1-20f3-423a-a7f2-1a9c1cadfee9

https://github.com/Expensify/App/assets/43996225/7ac097f2-f7b2-457c-a35d-017743d0865c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684318740704459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0199442829f9113a36</li>
        <li>Upwork Job ID: 1660914295792259072</li>
        <li>Last Price Increase: 2023-05-23</li>
    </ul>
</details>

**Comment by PrashantMangukiya** [comment] 2023-05-20 05:05
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
Money request header title has I beam cursor instead of pointer while hovering.

### What is the root cause of that problem?
Money request header rendered via `src/components/MoneyRequestHeader.js` component.  It consist two rows i.e. Requester and Payee. 

**1. So requestor rows rendered via `<HeaderWithCloseButton>` at line 91**
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/MoneyRequestHeader.js#L91

Eventually HeaderWithCloseButton will render `AvatarWithDisplayName` via this:
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/HeaderWithCloseButton.js#L170-L174

`AvatarWithDisplayName.js`  will render `DisplayNames` via this code:
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/AvatarWithDisplayName.js#L77-L84

We can see at line 82 we are passing text styles without cursor style, So it is display I beam cursor due text being selectable by nature.

**2. Payee render from `MoneyRequestHeader.js` via this code:**
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/MoneyRequestHeader.js#L120-L125

We can see at line 121 we are passing text styles without cursor style, So it display I beam cursor. **So this is the root cause of the problem for both places.**

### What changes do you think we should make in order to solve the problem?
To solve this we have to set default cursor style at two place.
i.e. Within `AvatarWithDisplayName.js`  we have to set `styles.cursorDefault` style at line 82 as shown in code below. 
```javascript
<DisplayNames 
   ...
   // textStyles={[styles.headerText, styles.pre]}   // *** Old  ***
   textStyles={[styles.headerText, styles.pre, styles.cursorDefault]} // *** Updated  ***
   ...
/> 
```

Within `MoneyRequestHeader.js` we have to set `styles.cursorDefault` style at line 121 as shown in code below. 
```javascript
 <Text 
     // style={[styles.headerText, styles.pre]}   // *** Old ***
     style={[styles.headerText, styles.pre, styles.cursorDefault]}  // *** Updated ***
     ...
 > 
     {payeeName} 
 </Text> 
```
So it will solve the issue and shows default cursor for both Requester and Payee  as shown in result video.

**Important:** We can not set pointer cursor because there is not any action on click of the text. So we have to use default cursor.

### What alternative solutions did you explore? (Optional)
None.

<details>
<summary>Results</summary>

https://github.com/Expensify/App/assets/7823358/0a350df6-5781-42af-921a-6b56fe2049aa

</details>

**Comment by shawnborton** [comment] 2023-05-22 13:16
Hmm why does the To field have a checkmark here? cc @JmillsExpensify @trjExpensify 

But I think this isn't really a bug if you can't actually click the header title to navigate anywhere, then no need for a pointer mouse.

**Comment by trjExpensify** [comment] 2023-05-22 13:28
>Hmm why does the To field have a checkmark here? cc @JmillsExpensify @trjExpensify

I think I'm blinded by EC3, can you link me to the vid showing that? 😅 

I agree it shouldn't have a pointer mouse if it's not clickable, and I don't think we have any immediate plans to add some kind of "room details" for a expense/iouReport.

**Comment by trjExpensify** [comment] 2023-05-22 13:48
Ah, I see it now. Yes, that's an error. The transaction view once settled should look like this: 

![image](https://github.com/Expensify/App/assets/16232057/a8e6047d-f004-4bc5-b0c6-cab597451006)

@mountiny @luacmartins @Julesssss - I've been out of the loop at EC3 for a couple of days, is this fix up somewhere else?

**Comment by Julesssss** [comment] 2023-05-22 14:02
> is this fix up somewhere else?

Not as far as I'm aware. Given that it's minor we can probably sneak the fix into this issue/proposal

**Comment by mountiny** [comment] 2023-05-22 14:03
I dont think so, I think this is just the checkmark from the IOU/ expense report as the header is same component.

**Comment by trjExpensify** [comment] 2023-05-22 14:12
Cool, and then on the transactions details we're missing the checkmark alongside the amount field value and "settled" in the amount field header after the dot separator.

**Comment by PrashantMangukiya** [comment] 2023-05-22 17:19
### Proposal

[Updated](https://github.com/Expensify/App/issues/19332#issuecomment-1555559374) that includes Checkmark and "Settled" text.

**Comment by mountiny** [comment] 2023-05-22 18:30
@Julesssss I think we could give this task to @PrashantMangukiya and work with them to resolve it

**Comment by Julesssss** [comment] 2023-05-23 07:44
Hey @aimane-chnaif, could you please give [this proposal](https://github.com/Expensify/App/issues/19332#issuecomment-1555559374) a review before I assign @PrashantMangukiya? Thanks

**Comment by Julesssss** [comment] 2023-05-23 07:56
We'd like to include both in this PR if possible.

**Comment by grgia** [comment] 2023-05-24 07:24
I agree that this is not a bug, the cursor is a pointer on other chat headers because clicking on the avatar opens the details page. Unless we intend to also add that functionality, we can probably close this. What do you think @Julesssss ?

**Comment by PrashantMangukiya** [comment] 2023-05-24 09:43
@Julesssss @aimane-chnaif Thank you. I will prepare and submit PR within three hours asap.

**Comment by tjferriss** [comment] 2023-06-07 22:05
Sorry for the delay. All offers have been sent via Upworks and I'll process payment as they're accepted. @PrashantMangukiya and @aimane-chnaif will get the 50% speed bonus.


@aimane-chnaif can you please help out with the checklist.

**Comment by PrashantMangukiya** [comment] 2023-06-07 22:06
@tjferriss Offer accepted. Thank you.

**Comment by tjferriss** [comment] 2023-06-09 03:31
All the payments have been sent.

**Closed by tjferriss** 2023-06-09 03:31 UTC
Labels: External, Daily, Awaiting Payment, Bug
