### ISSUE TITLE
 Room – @Hidden is shown in system message when invite to the Room user with current account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36367] opened 2024-02-12 20:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4301435
**Email or phone of affected tester (no customers):** applausetester+jpcategory@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login
3. Create a room
4. Invite to the Room user with current account (send a message with @email in the Room chat)
5. Observe a system message

## Expected Result:
@User name is shown in a system message when invite to the Room user with current account

## Actual Result:
@Hidden is shown in a system message when invite to the Room user with current account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5b35a884-4d45-4173-a545-a03de475e17d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-12 20:07
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by Beamanator** [comment] 2024-02-13 09:27
Looks like this was fixed by https://github.com/Expensify/App/pull/36358/files

**Comment by Beamanator** [comment] 2024-02-13 09:28
@lanitochka17 will you please retest this in latest staging? I believe this could have been fixed by ^ linked PR

**Comment by Beamanator** [comment] 2024-02-13 13:40
working well for me on staging!

**Comment by marcochavezf** [comment] 2024-02-13 20:36
I will close it out since it's no longer reproducible on staging

**Closed by marcochavezf** 2024-02-13 20:36 UTC
Labels: Engineering, Daily

**Comment by lanitochka17** [comment] 2024-02-14 20:55
Issue is not reproducible on the build 1.4.41-7


https://github.com/Expensify/App/assets/78819774/47d8d0d2-682e-4942-98ca-a44124d7719e
