### ISSUE TITLE
[$250] Web - User has to click twice to select currency if the currency is around the bottom

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41922] opened 2024-05-09 14:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB > Submit expense > Click on the currency to open the currency selector
3. Click on a currency located around the bottom of the list

## Expected Result:
The currency gets selected on the first click

## Actual Result:
The currency does not get selected on the first click but moves up to be in the middle of the list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9b47f8ee-6d6c-4ed8-90df-a5c4d24e21db

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0151b3d12408cd70e1</li>
        <li>Upwork Job ID: 1790583776832409600</li>
        <li>Last Price Increase: 2024-05-15</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by lanitochka17** [comment] 2024-05-09 14:46
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-09 14:46
We think that this bug might be related to #vip-vsp

**Comment by JmillsExpensify** [comment] 2024-05-15 03:23
Added to #wave-collect and opened up for proposals.

**Comment by bernhardoj** [comment] 2024-05-15 07:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we hold down the list item, the list scrolls and the click is ignored.

### What is the root cause of that problem?
When the item is focused either by keyboard or mouse, it will set the item as the focused index.
https://github.com/Expensify/App/blob/34bccb634fa6ec26db4e4c834a809f4e68099c57/src/components/SelectionList/BaseSelectionList.tsx#L362

When the focused index changes, we scroll to the index.
https://github.com/Expensify/App/blob/34bccb634fa6ec26db4e4c834a809f4e68099c57/src/components/SelectionList/BaseSelectionList.tsx#L235-L237

And because we release the mouse after the list scrolls, the click isn't registered anymore.

### What changes do you think we should make in order to solve the problem?

Don't scroll the list if it's focused by mouse. We can create a new ref called `shouldScrollAfterFocus`. Set it to false in the list item onMouseDown.

```
if (shouldPreventDefaultFocusOnSelectRow || isItemFocused) {
    return;
}
shouldScrollAfterFocus.current = false;
```

We ignore it if `shouldPreventDefaultFocusOnSelectRow` because the item won't receive focus and if the item is already focused.

Then return early here if `shouldScrollAfterFocus` is false.

https://github.com/Expensify/App/blob/34bccb634fa6ec26db4e4c834a809f4e68099c57/src/components/SelectionList/BaseSelectionList.tsx#L235-L237

```
if (!shouldScrollAfterFocus.current) {
    shouldScrollAfterFocus.current = true;
    return;
}
```

### What alternative solutions did you explore? (Optional)
Set `shouldPreventDefaultFocusOnSelectRow` to true by default so the item can't receive focus by mouse.

**Comment by jayeshmangwani** [comment] 2024-05-15 17:09
I am trying to reproduce this issue on staging, but currency selection is working fine for me at the bottom of the list, @bernhardoj  and @tienifr  are you able to reproduce this issue consistently ?

https://github.com/Expensify/App/assets/35371050/506f57c6-2da5-4a2b-84bb-77d6c4b85b8d

**Comment by bernhardoj** [comment] 2024-05-16 05:22
@jayeshmangwani you need to hold down a bit before releasing the click/press

**Comment by jayeshmangwani** [comment] 2024-05-17 13:36
Thanks for the help; now I can reproduce this

**Comment by jayeshmangwani** [comment] 2024-05-20 06:23
I also feel the same as @tienifr ; we should remove the conditional `onMouseDown={shouldPreventDefaultFocusOnSelectRow ? (e) => e.preventDefault() : undefined}` and instead we should use the ` onMouseDown={(e) => e.preventDefault()}`, Conditional onMouseDown was added in this [PR](https://github.com/Expensify/App/pull/29084). Still, I am not sure why it was added conditional instead of directly passing the `e.preventDefault()` for all the `onMouseDown`; we can go with the @tienifr 's [Proposal](https://github.com/Expensify/App/issues/41922#issuecomment-2112071705) of using `onMouseDown={(e) => e.preventDefault()}`.

🎀 👀 🎀 C+ reviewed

**Comment by Julesssss** [comment] 2024-06-10 10:08
During the PR review we realised this behaviour is consistent and are discussing [here](https://github.com/Expensify/App/pull/42380#issuecomment-2157922979) whether we should still continue with the fix. I think not.

**Comment by Julesssss** [comment] 2024-06-13 10:54
PR was just merged

**Comment by jayeshmangwani** [comment] 2024-06-27 06:29
@JmillsExpensify PR Deployed to production 2 weeks ago. The issue is ready for payout

**Comment by JmillsExpensify** [comment] 2024-07-11 04:27
Payment summary:
 - Contributor: @tienifr $250
 - Reviewer: @jayeshmangwani $250 

Both of you are eligible for NewDot payments. Should I cancel the Upwork contracts?

**Comment by jayeshmangwani** [comment] 2024-07-11 05:24
> Both of you are eligible for NewDot payments. Should I cancel the Upwork contracts?

Yes 👍

**Comment by JmillsExpensify** [comment] 2024-07-11 16:16
I'll assume the same for @tienifr. Btw, what about the checklist?

**Comment by mallenexpensify** [comment] 2024-07-11 18:14
Contributor: @tienifr  due $250 via NewDot
Contributor+: @jayeshmangwani due $250 via NewDot. 

@jayeshmangwani it looks like the checklist didn't populate. plz copy/paste the below.  Thx

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by JmillsExpensify** [comment] 2024-07-11 18:17
Thanks @mallenexpensify! I'm closing this issue and will circle back for payments once I review the expenses in New Expensify. Don't forget the checklist please.

**Closed by JmillsExpensify** 2024-07-11 18:17 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by jayeshmangwani** [comment] 2024-07-12 09:20
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/39201
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/39201#discussion_r1675564272
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **Yes**
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again



## Regression Test Proposal
1. Open the app.
2. Click on the FAB -> Submit expense.
3. Click on the currency to open the currency selector.
4. Long press on a currency located near the bottom of the list.
5. Verify that the currency gets selected after releasing the long press.


Do we agree 👍 or 👎

**Comment by jayeshmangwani** [comment] 2024-07-15 20:51
Requested $250 on NewDot

**Comment by JmillsExpensify** [comment] 2024-07-16 04:35
$250 approved for @tienifr

**Comment by JmillsExpensify** [comment] 2024-07-16 04:38
$250 approved for @jayeshmangwani

**Comment by mallenexpensify** [comment] 2024-07-16 22:57
Testrail
- https://github.com/Expensify/Expensify/issues/413282
