### ISSUE TITLE
Web/mWeb - Login via magic link does not work if second tab is opened in incognito

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20431] opened 2023-06-08 01:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log out of NewDot and request a new magic link
2. Navigate to email and locate the magic link - change to staging if needed
3. Open an new INCOGNITO window and navigate to the staging link
## Expected Result:
4. "Abracadabra, you're logged in" page is displayed
5. Navigate to the original window
6. Verify the user is logged in
## Actual Result:
4. "Here is your magic code" page is displayed
5. Navigate to the original window
6. User is NOT logged in
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/07e8ccb1-711c-449e-bb1a-631722e3d7cc

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment] 2023-06-08 06:48
That is expected behavior since incognito tabs are isolated, and don't share data with normal tabs.

**Comment by MitchExpensify** [comment] 2023-06-09 11:32
So @alitoshmatov is your recommendation to edit the testrail steps because this is actually expected?

**Comment by alitoshmatov** [comment] 2023-06-13 02:15
@MitchExpensify maybe, but I am not sure how these tests are created and why above steps are chosen

**Comment by MitchExpensify** [comment] 2023-06-13 15:48
The test steps are chosen to make sure the app is working as expected. Are you saying that this behavior could never be expected because "incognito tabs are isolated, and don't share data with normal tabs" - In other words you wouldn't be able to open the magic sign link in incognito ever? Your comment made me think thats what you were saying @alitoshmatov

**Comment by MitchExpensify** [comment] 2023-06-16 22:50
Friendly bump on your recommendation [here](https://github.com/Expensify/App/issues/20431#issuecomment-1589582549) @alitoshmatov, appreciate it! If you are not able to open the magic sign link in incognito ever we should just update the testing steps cc @kavimuru for your thoughts

**Comment by alitoshmatov** [comment] 2023-06-17 06:32
@MitchExpensify Sorry, I missed this one.
If you open new expensify app in incognito and also open magic link incognito mode, everything works fine.

But, if app is opened in normal tab and magic link itself is opened in incognito it cannot automatically sign in your app, thus just shows `Here is your magic code` page rather than `Abracadabra, you're logged in`

**Comment by MitchExpensify** [comment] 2023-06-19 19:18
Thanks @alitoshmatov - I've asked for another opinion on whether this would ever be expected to work in the open source channel here https://expensify.slack.com/archives/C01GTK53T8Q/p1687202243029599

**Comment by abekkala** [comment] 2023-06-21 16:40
@MitchExpensify ah just noticed this one. I assume this is related: https://github.com/Expensify/App/issues/21111

**Comment by MitchExpensify** [comment] 2023-06-22 01:00
hmm I'm not sure tbh @abekkala - Does these look related to you @rushatgabhane ? I was thinking this issue is more focused on switching from public to incognito browsers

**Comment by MitchExpensify** [comment] 2023-06-22 01:16
Thanks! Given the doubt about whether you would ever be able to jump from public to incognito as described in this flow I'm going to close this out for not being a bug.

**Closed by MitchExpensify** 2023-06-22 01:16 UTC
Labels: Daily, Bug
