### ISSUE TITLE
[HOLD for payment 2022-09-02] [$250] Web - Emoji- First skin tone option is broken in FireFox & Safari Web - reported by @parasharrajat & @Tushu17

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9123] opened 2022-05-20 23:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Click on Emoji
3. Select first option on skin tone

## Expected Result:
First skin tone option has light yellow color in Firefox & shows weird UI in Safari

## Actual Result:
First skin tone option is broken in Firefox & UI is broken in Safari Web

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- Web (Safari & Firefox)

**Version Number:** 1.1.65.3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5577795_FFhand](https://user-images.githubusercontent.com/43996225/169624991-e11e149d-e7b6-49e6-99a0-567e43b286d4.png)

**Upwork job URL:** https://www.upwork.com/jobs/~01935f62be2a68928d
**Issue reported by:** Applause - Exploratory & @parasharrajat & Tushu17
**Slack conversation:**
- Report by Rajat: https://expensify.slack.com/archives/C01GTK53T8Q/p1652457370257659
- Report by Tushu17: https://expensify.slack.com/archives/C01GTK53T8Q/p1645559241745729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment] 2022-05-21 11:02
I reported a similar issue https://expensify.slack.com/archives/C01GTK53T8Q/p1652457370257659. I think we should combine both.

**Comment by Beamanator** [comment] 2022-05-23 12:50
Good idea, I agree @parasharrajat 👍 

How about we just update this issue with details about the broken behavior in web safari (that you reported) and fix both in this issue?

**Comment by Tushu17** [comment] 2022-05-23 14:41
Hi @Beamanator, this issue was originally reported by me [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1645559241745729) can you please look into it.

P.S. It is marked as dupe because of a misunderstanding as there was an issue related to skin tone.

**Comment by parasharrajat** [comment] 2022-05-23 17:08
You can instead assign me as C+. That would be fine.

**Comment by trjExpensify** [comment] 2022-05-23 22:14
Sounds good, @parasharrajat. Added you and posted the job to upwork here: https://www.upwork.com/jobs/~01e88449b26be1fba2

@Tushu17, are you interested in submitting a proposal for this?

**Comment by thesahindia** [comment] 2022-05-31 14:53
### Proposal 
We need to remove `styles.emojiItem` it contains width 12.5% and I found that increasing font size or width breaks it in safari.
https://github.com/Expensify/App/blob/db27a3dc4a61c552b8e827819261310592ad7914/src/components/EmojiPicker/EmojiSkinToneList.js#L70


https://user-images.githubusercontent.com/83179295/171201888-20a00776-0a5b-4035-bbc6-5807eb78992e.mov


I couldn't repro the Firefox issue.

**Comment by parasharrajat** [comment] 2022-05-31 17:31
What a strange issue! @thesahindia Did you run some research on this?

**Comment by thesahindia** [comment] 2022-05-31 18:10
Just found that it is only happening with `Text` as it has styling `white-space: pre-wrap` and if we change that to `white-space: nowrap` then increasing font size or width won't break it.

**Comment by parasharrajat** [comment] 2022-05-31 18:14
Let's try to get to the roots of other mentioned issue in OP.

**Comment by Beamanator** [comment] 2022-06-03 19:02
Yeah it looks like @Tushu17 & @parasharrajat  reported the but on Safari, the issue was reported to occur in Firefox by @kavimuru

**Comment by parasharrajat** [comment] 2022-06-03 19:16
Waiting on something about the issue reported on firefox.

**Comment by trjExpensify** [comment] 2022-06-06 10:14
👋 Hey all! What's the latest here?

**Comment by parasharrajat** [comment] 2022-06-06 14:27
Waiting for proposals/discussion on the issue with Firefox browser.

**Comment by Beamanator** [comment] 2022-06-06 15:35
@kavimuru can you please confirm if this issue still can be reproduced on Firefox?

**Comment by trjExpensify** [comment] 2022-06-09 20:14
^^ what are we doing about that, has someone posted in #expensify-open-source to find someone on Windows?

**Comment by parasharrajat** [comment] 2022-06-09 20:47
No one posted it there. This is still open for proposals.

**Comment by thesahindia** [comment] 2022-06-10 08:52
I tried using `Segoe UI Emoji` font on my friend's windows machine and it will solve the problem. We can add this as a fallback font
https://github.com/Expensify/App/blob/1997b1cb6e55809fac2c578d6aaf5b1f9bc3e8a4/src/styles/styles.js#L1420-L1421

**Comment by parasharrajat** [comment] 2022-06-10 09:41
Hmm Interesting. This is a weird issue. Now what are you proposing to fully solve this issue?

> I tried using Segoe UI Emoji font on my friend's windows machine and it will solve the problem. We can add this as a fallback font

Are you able to share some research on why this font works but not ours?

**Comment by thesahindia** [comment] 2022-06-10 11:49
>Hmm Interesting. This is a weird issue. Now what are you proposing to fully solve this issue?

1. To fix the safari issue we can add `styles.textNoWrap` here 

https://github.com/Expensify/App/blob/db27a3dc4a61c552b8e827819261310592ad7914/src/components/EmojiPicker/EmojiSkinToneList.js#L70

2. To fix the other issue we can replace the line 1421 with 
```js 
fontFamily: `${fontFamily.GTA_BOLD}, ${fontFamily.SEGOE_UI_EMOJI}`
```
(will have to add SEGOE_UI_EMOJI to our fontFamily object)
https://github.com/Expensify/App/blob/1997b1cb6e55809fac2c578d6aaf5b1f9bc3e8a4/src/styles/styles.js#L1420-L1421


>Are you able to share some research on why this font works but not ours?
Couldn't find much info but here's a post about it: https://www.tjvantoll.com/2016/06/15/emoji-on-windows/

**Comment by parasharrajat** [comment] 2022-06-10 13:19
Ok, Does not work on my linux machine. I am running firefox.

![image](https://user-images.githubusercontent.com/24370807/173073192-e1a2ed30-45bd-447f-818a-f83967187255.png)

**Comment by trjExpensify** [comment] 2022-06-13 17:13
> IMO, we should use images instead of unicode. I have see many differences across platforms and browsers

@stitesExpensify might have some added context around the direction we went here as well.

**Comment by thesahindia** [comment] 2022-06-15 06:47
@parasharrajat, on ubuntu I tried Noto Color Emoji and it's working. Can you give it a try?

**Comment by parasharrajat** [comment] 2022-06-15 17:54
No change for me. what changes are you doing? I can try to follow the same.

**Comment by thesahindia** [comment] 2022-06-16 05:46
I tried adding `Noto Color Emoji` font

https://user-images.githubusercontent.com/83179295/174000011-f87fc684-228b-4702-b003-f048fcaa443f.mp4

**Comment by parasharrajat** [comment] 2022-06-16 08:33
Not working for me. I am on Arch Linux. But I think this is fine as it is. As mentioned https://github.com/Expensify/App/issues/9123#issuecomment-1155416531, we will move away from Unicode to images in the future to achieve consistency. 


@thesahindia Let me know your complete proposal so far.

**Comment by thesahindia** [comment] 2022-06-17 17:16
### Updated Proposal 

1. To fix the safari issue we can add `styles.textNoWrap` here 

https://github.com/Expensify/App/blob/db27a3dc4a61c552b8e827819261310592ad7914/src/components/EmojiPicker/EmojiSkinToneList.js#L70

2. To fix the emoji color issue on windows and ubuntu we can replace the line 1421 with 
```js 
fontFamily: `${fontFamily.GTA_BOLD}, ${fontFamily.SEGOE_UI_EMOJI}, ${fontFamily.NOTO_COLOR_EMOJI}`
```

https://github.com/Expensify/App/blob/1997b1cb6e55809fac2c578d6aaf5b1f9bc3e8a4/src/styles/styles.js#L1420-L1421

(will have to add SEGOE_UI_EMOJI and NOTO_COLOR_EMOJI to our fontFamily object)

**Comment by parasharrajat** [comment] 2022-06-17 17:22
@thesahindias's latest proposal looks good to me. 

cc: @Beamanator 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by trjExpensify** [comment] 2022-06-20 15:57
Melv, awaiting a review from @Beamanator!

**Comment by Beamanator** [comment] 2022-06-20 17:13
Sorry for the delay everyone, hired! 👍

**Comment by trjExpensify** [comment] 2022-06-20 20:31
@thesahindia - can you apply to the [job here](https://www.upwork.com/jobs/~01e88449b26be1fba2) please?

**Comment by trjExpensify** [comment] 2022-06-22 23:55
@thesahindia the job expired today, so I've reposted it [here](https://www.upwork.com/jobs/~01935f62be2a68928d) and invited you to it.

**Comment by kaushiktd** [comment] 2022-06-23 05:34
We need to remove width from styles.emojiItem contains a width of 12.5% and I found that when adding width or increasing width is breaking it in safari.

So we need to remove the width from the below file on line#70
https://github.com/Expensify/App/blob/db27a3dc4a61c552b8e827819261310592ad7914/src/components/EmojiPicker/EmojiSkinToneList.js#L70

Need to remove width property from below file on line# 1428
https://github.com/Expensify/App/blob/db27a3dc4a61c552b8e827819261310592ad7914/src/styles/styles.js#L1428

See screen recording here: https://drive.google.com/file/d/1cyTTlDmCbxSSRhT_hUZDzSBrv51qQz15/view

**Comment by thesahindia** [comment] 2022-06-23 19:19
Pushed the code but getting error because of fonts at ios. Tryna work on that now.
![Simulator Screen Shot - iPhone 13 - 2022-06-24 at 00 47 57](https://user-images.githubusercontent.com/83179295/175379977-ee59a104-7eb4-4022-9bc6-acc9b5137677.png)

**Comment by Beamanator** [comment] 2022-06-27 10:39
@kaushiktd thanks for your proposal, but please be aware that this job does not have the `Help Wanted` label at the moment, because we have already hired someone (see this comment too: https://github.com/Expensify/App/issues/9123#issuecomment-1160681324)

**Comment by trjExpensify** [comment] 2022-07-05 12:01
What's the latest on this PR @thesahindia? In the meantime, I'm adding the `reviewing` label as there's a PR up for the issue.

**Comment by Christinadobrzyn** [comment] 2022-07-05 13:57
Hey there! We have another broken emoji in Firefox - the eye seems broken. Do you think this PR will fix that as well?https://github.com/Expensify/App/issues/9686

**Comment by thesahindia** [comment] 2022-07-05 15:21
> It seems so @thesahindia What do you think?

Yeah it will be fixed in the current PR.

**Comment by thesahindia** [comment] 2022-07-09 18:32
> What's the latest on this PR @thesahindia? In the meantime, I'm adding the `reviewing` label as there's a PR up for the issue.

We are trying to deal with the same issue but at different places ( other than emoji picker menu )

**Comment by trjExpensify** [comment] 2022-07-28 10:34
This PR has seemingly stalled in review for the last 9 days. Can we get an ETA on finishing it up, please?

**Comment by thesahindia** [comment] 2022-07-28 10:55
Sorry for the long delay. I was little sick.

**Comment by trjExpensify** [comment] 2022-07-28 11:08
Thanks for the heads up, @thesahindia. Hope you're feeling better!

**Comment by thesahindia** [comment] 2022-07-28 21:00
I have updated the [PR](https://github.com/Expensify/App/pull/9551).

@parasharrajat, feel free to review when you get time.

**Comment by Beamanator** [comment] 2022-08-11 11:38
Bumped review :D

**Comment by trjExpensify** [comment] 2022-08-18 12:05
👋 Where are we at with the review on [the PR](https://github.com/Expensify/App/pull/9551#issuecomment-1213441869). Looks like the changes have been pushed, can this get merged?

**Comment by thesahindia** [comment] 2022-08-19 06:52
Yeah it is ready for the review.

**Comment by mvtglobally** [comment] 2022-08-30 15:19
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment] 2022-09-05 13:03
Okay, so the original Upwork job has closed. Created a new one [here](https://www.upwork.com/jobs/~01a5bfc24204813592). Can you all apply, please? 

@parasharrajat - $250 for C+ 
@Tushu17 - $250 for reporting 
@thesahindia - $250 for the PR

**Comment by trjExpensify** [comment] 2022-09-05 14:18
@parasharrajat - paid.

**Comment by thesahindia** [comment] 2022-09-05 14:45
Applied 🚀

**Comment by mvtglobally** [comment] 2022-09-06 02:59
Issue not reproducible during KI retests. (Second week)

**Comment by trjExpensify** [comment] 2022-09-06 10:29
Offers sent to @thesahindia & @Tushu17.

**Comment by trjExpensify** [comment] 2022-09-06 10:42
@thesahindia - paid!

**Comment by trjExpensify** [comment] 2022-09-06 11:22
@Tushu17 - paid! Closing this out. Thanks everyone! 🎉

**Closed by trjExpensify** 2022-09-06 11:22 UTC
Labels: Reviewing, Exported, External, Engineering, Daily, Awaiting Payment
