### ISSUE TITLE
Login - Infinity loading is displayed for open deep link on Desktop App

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19860] opened 2023-05-30 22:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out of the account 
2. Enter the email on the email field and continue
3. Click on "Go Back"
4. Continue with the log in flow
5. Navigate to the email inbox and look for the magic link email
6. Right-click on the link to open it in a new Tab (change the URL to staging by adding "https://staging.new.expensify.com/")
8. Select "Open New Expensify" on the popup

## Expected Result:
Verify an "Abracadabra, you are signed in!" page is displayed

## Actual Result:
Infinity loading is displayed for open deep link on Desktop App. Issue occurred for all deep link on Mac/Chrome.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.20.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**
https://expensify.testrail.io/index.php?/tests/view/3478763

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/3646371b71ecf433087de948eee2ba0a9e90550ccecf47f1529769c9a8c7d91f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2023-05-31 18:10
Might be related to - https://github.com/Expensify/App/issues/19047 - asking

**Comment by roryabraham** [comment] 2023-06-01 17:19
@Christinadobrzyn this appears unrelated to https://github.com/Expensify/App/issues/19047

**Comment by Christinadobrzyn** [comment] 2023-06-01 18:03
Hey @kbecciv I'm not able to reproduce this. Can you doublecheck this is still happening and update the steps in the Op so I can reproduce?

After I do the following steps at https://staging.new.expensify.com/

- Sign out of the account
- Enter the email on the email field and continue
- Click on "Go Back"
- Continue with the log in flow
- Navigate to the email inbox and look for the magic link email
- Right-click on the link to open it in a new Tab (change the URL to staging by adding "https://staging.new.expensify.com/")
- Select "Open New Expensify" on the popup

I get this password screen in the Desktop app

<img width="1200" alt="image" src="https://github.com/Expensify/App/assets/51066321/0efb2752-61a8-4ee1-9d1e-f4f3a2e39030">

**Comment by Christinadobrzyn** [comment] 2023-06-01 18:39
This is fixed - https://expensify.slack.com/archives/C9YU7BX5M/p1685642660059359

Closing

**Closed by Christinadobrzyn** 2023-06-01 18:39 UTC
Labels: Daily, Bug
