### ISSUE TITLE
Room - Settings - Unable to remove setup specialist from the room @adeel0202

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11416] opened 2022-09-29 13:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace (when you create a new workspace, a setup specialist is assigned and added to that workspace's announce room automatically)
2. Go to that workspace's announce room
3. Click on the announce room name on top to open its details
4. Go to Members
5. Observe that there is a setup specialist in the members list
6. Now go to Settings
7. Go to the workspace you created
8. Go to manage members
9. Select setup specialist user from the members list
10. Click Remove button
11. Click Remove again to confirm
12. Go to the workspace's announce room
13. Click on the announce room name on top to open its details
14. Go to Members
15. Observe that the setup specialist is still there

## Expected Result:
Setup specialist is removed from the room

## Actual Result:
Setup specialist is not removed from the room

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193041171-f301ed30-0b1d-489c-b75b-f8ad1954d317.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @adeel0202

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663578754768679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment] 2022-09-29 19:10
Hmm, I was unable to reproduce in staging. 
I was successful at removing a user and they remained removed.

**Comment by adeel0202** [comment] 2022-09-29 19:22
@abekkala did you follow the steps mentioned with the issue? Because I just check again, this time on android, and I was able to reproduce. I have attached the video recording as well.

https://user-images.githubusercontent.com/13783842/193123470-67cb2316-6dfb-40e2-93e1-cbc9b8b5eb24.mp4

**Comment by adeel0202** [comment] 2022-09-29 19:24
Also, the issue occurs when you remove the setup specialist/guide from the members' list, not when you remove any other user.

**Comment by adeel0202** [comment] 2022-10-03 17:03
@abekkala, reminder to re-open this because this is reproducible.
cc: @kbecciv

**Comment by michaelhaxhiu** [comment] 2022-10-07 11:53
Seems that @kbecciv was able to reproduce this bug based on the GH body. How did you add the `setup specialist user` exactly? 

@adeel0202 can you include that in the repro steps so that @abekkala can attempt to reproduce it exactly?

**Comment by michaelhaxhiu** [comment] 2022-10-07 12:24
Discussed further on slack thread [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1665145346147479?thread_ts=1663578754.768679&cid=C01GTK53T8Q) for context. But tl;dr - updating the repro steps so that it's more detailed. @abekkala can you try again using the updated steps?

**Comment by adeel0202** [comment] 2022-10-07 12:24
I have written the detailed reproduction steps [on slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1665145346147479?thread_ts=1663578754.768679&cid=C01GTK53T8Q).

**Comment by michaelhaxhiu** [comment] 2022-10-10 20:28
@abekkala Ah sorry just for context, I merely copy/pasted the steps from the related [slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1663578754768679). If you aren't able to reproduce still, let's have @adeel0202 triple check these steps are 100% correctly documented  😬 ?

**Comment by michaelhaxhiu** [comment] 2022-10-11 12:57
Got it! Let's try to identify where/how this got fixed to ensure it's really finalized. 

I think we should push this through, so that it gets C+ assignment and we can find the PR responsible for the fix.

Then we can decide on paying the bug reporting bonus.

**Comment by abekkala** [comment] 2022-10-12 18:26
GH from no #announce or #admin rooms being created
https://github.com/Expensify/App/issues/11685

**Comment by michaelhaxhiu** [comment] 2022-10-12 20:42
Is this really `internal`? I don't think I understand why it is 🤔

**Comment by nkuoch** [comment] 2022-10-13 03:07
Sorry, I just started to be ooo, so I just basically wanted to Unassign myself and let someone else internal do the triage. Feel free to change.

**Comment by michaelhaxhiu** [comment] 2022-10-13 03:12
Ah I see!

**Comment by michaelhaxhiu** [comment] 2022-10-13 03:13
>Got it! Let's try to identify where/how this got fixed to ensure it's really finalized.

@techievivek do you think you can help us discern this? 
cc @adeel0202 in case you saw the PR too - it's typically a pre-req to pay out a bug reporting bonus. Just to ensure it's truly fixed.

**Comment by techievivek** [comment] 2022-10-13 03:19
Sorry @michaelhaxhiu, I am working limited hours this week so I won't be able to look into it given I am prioritising some PRs related to account manager docs.

**Comment by adeel0202** [comment] 2022-10-13 08:57
@michaelhaxhiu I couldn't find the PR. My guess is that it got fixed from the server end.

**Comment by techievivek** [comment] 2022-10-27 09:49
I am going to send it back to the pool so someone else can look into it.

**Comment by johncschuster** [comment] 2022-11-03 20:57
I'm unable to reproduce the issue on staging.

**Comment by johncschuster** [comment] 2022-11-03 21:10
@adeel0202, would you be willing to try reproducing this one more time? It seems we've had trouble reproducing this lately, which makes me feel we should close the issue. If you can reproduce it, we'll keep it open, otherwise, let's close it so we can focus.

I'll create an Upwork job so you can get credit for reporting the issue regardless of if we keep it open or closed.

**Comment by michaelhaxhiu** [comment] 2022-11-03 21:19
Thanks for the urgency in responding. @adeel0202 if you can locate the PR that fixed this, you are still eligible for a bug reporting bounty :) (per the contributing.md guide [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#proposing-a-job-that-expensify-hasnt-posted))

**Comment by michaelhaxhiu** [comment] 2022-11-03 21:23
😢 sorry to hear that - maybe it'll surface in coming days. Otherwise not to fear, plenty of other bugs to find :)

**Comment by thesahindia** [comment] 2022-11-04 10:12
Will give it a shot at night.

**Comment by johncschuster** [comment] 2022-11-04 14:06
Closing the issue per the conversation above. I'll keep an eye out if you find the PR!

**Comment by johncschuster** [comment] 2022-11-07 17:33
Ok! [The PR has been found!](https://github.com/Expensify/App/pull/10452) I'll issue the bug-reporting bounty.

**Comment by johncschuster** [comment] 2022-11-07 21:01
@adeel0202 here's the link for the bounty job. Can you apply and let me know when you've done that?

https://www.upwork.com/jobs/~01e85a2c16311b56cb

**Comment by johncschuster** [comment] 2022-11-07 22:09
@adeel0202 Great! I've just hired you on Upwork. Once you accept the job I'll get this squared up!

**Comment by michaelhaxhiu** [comment] 2022-11-11 21:30
Stepping in to help.

Paid. :)

**Closed by michaelhaxhiu** 2022-11-11 21:30 UTC
Labels: Engineering, Daily, Needs Reproduction, Bug
