### ISSUE TITLE
[HOLD for payment 2024-01-09] [$250] Migrate `Icon/index.js` to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16163] opened 2023-03-20 08:37 UTC
### Filenames
- [ ] [src/components/Icon/index.js](https://github.com/Expensify/App/blob/main/src/components/Icon/index.js)
    - **type:** `React.PureComponent`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b7c9cb3b537f252</li>
        <li>Upwork Job ID: 1685093774219771904</li>
        <li>Last Price Increase: 2023-07-29</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 26184153</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @maddylewis</details>

**Comment by muxriddinmuqimov77** [comment] 2023-06-06 06:56
I'd like to work on this issue

**Comment by s-alves10** [comment] 2023-06-06 10:27
I'd love to work on this.

**Comment by olexyt** [comment] 2023-07-07 13:57
I can work on this issue.

**Comment by mejed-alkoutaini** [comment] 2023-07-11 18:59
I'm able to work on this if needed!

**Comment by mkhutornyi** [comment] 2023-07-12 03:03
I'd like to work on this.

**Comment by NomanIlyas** [comment] 2023-07-29 01:09
I'm open to work on it, Free to cost :) 
Mainly purpose to engage with highly passionate team

**Comment by NomanIlyas** [comment] 2023-07-29 01:28
Hey @MelvinBot , thank you, good to know that :) 

```
> Contributor details
> Your Expensify account email: noman.ilyas.software@gmail.com
> Upwork Profile Link: https://www.upwork.com/freelancers/~0159a56a118273d26c

**Comment by DamianStankowski** [comment] 2023-07-29 01:32
**Proposal by Damian Stankowski:**

I propose refactoring the existing class component to a function component as follows:

1. Remove the class declaration and replace it with a function that takes props as an argument.
2. Move the rendering code inside the function and ensure that it returns the appropriate JSX.
3. Eliminate any references to this.props and directly use props within the function.
4. If there are any higher-order components (such as PureComponent or Component), they can be removed since React functions are always "pure" and do not need to inherit from a base class.

1. Ensure that PropTypes are properly set up for the React function.

By making these changes, we will have a more concise and efficient codebase while still maintaining the required functionality. Additionally, using function components aligns with modern React best practices and will make the code easier to maintain and understand.

I will proceed with the proposed changes and thoroughly test the component to ensure there are no regressions and that it functions correctly in the application.

If you have any questions or further suggestions, please feel free to reach out. Thank you for considering this proposal.

As an additional complementary idea, I suggest considering the deprecation of PropTypes since React v15.5.0. PropTypes have been marked as deprecated in favor of other more robust solutions like TypeScript or Flow. These alternatives offer a stronger type system and better integration within the React ecosystem.
By adopting TypeScript or Flow for type checking, we can benefit from enhanced code quality and improved error handling during development. These tools provide better static type analysis, helping to catch potential issues early and improving overall code maintainability and reliability.
the migration process to Flow or TypeScript can be done gradually. It's not necessary to tackle the entire codebase at once. We can adopt an incremental approach to minimize disruptions and manage the transition effectively.

Email : damianstankowskifreelancer@gmail.com

**Comment by oluwatobiloba1** [comment] 2023-07-29 01:35
Hello is this issue still open for contribution, i would love to jump on it. Below are my details:
Your Expensify account email: rapzter58@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0196bc80524a3b0c5e

**Comment by DamianStankowski** [comment] 2023-07-29 01:36
> 📣 @DamianStankowski! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: none
> Upwork Profile Link: https://www.upwork.com/freelancers/~0159e57593fa3b3b2a
> ```

**Comment by himanshuragi456** [comment] 2023-07-29 02:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate `Icon/index.js` to function component

### What is the root cause of that problem?
need to change class based component to functional

### What changes do you think we should make in order to solve the problem?
- component state and props from class to function syntax
- render method from class to function syntax
- update callbacks from class to function syntax (possibly with useCallback hook)
- update refs from class to function syntax
- any other class component logic to function component
- and ensure no regressions occur.

This component doesn't use lifecycle methods so we don't have to worry about that.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Parshvi16** [comment] 2023-07-29 03:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate `Icon/index.js` to function component

### What is the root cause of that problem?
need to change class based component to functional

### What changes do you think we should make in order to solve the problem?
- component state and props from class to function syntax
- render method from class to function syntax
- lifecycle methods to hooks(if any)
- update callbacks from class to function syntax (possibly with useCallback hook)
- update refs from class to function syntax
- any other class component logic to function component
- and ensure no regressions occur.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by alexxxwork** [comment] 2023-07-29 04:22
I would love to work on this issue

**Comment by reinesarchisorte** [comment] 2023-07-29 04:28
Can I work this one?

**Comment by priyankrawat** [comment] 2023-07-29 04:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migration of [src/components/Icon/index.js](https://github.com/Expensify/App/blob/main/src/components/Icon/index.js) to the function component.

### What is the root cause of that problem?
No root cause, just need to migrate class component to function component.

### What changes do you think we should make in order to solve the problem?
To solve the problem, the following changes should be made:

1. Remove the extends PureComponent from the Icon component.
2. Rewrite the Icon component as a function component using the React.memo hook to achieve the same performance optimization as the PureComponent.
3. Ensure that all functionality, including handling props and rendering SVG icons, is preserved in the function component.
4. Finally make sure there is no regression.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ishpaul777** [comment] 2023-07-29 06:06
Would love to work on this

**Comment by rushatgabhane** [comment] 2023-07-30 11:21
@NomanIlyas is the first non-assigned contributor to call dibs on migration issue. https://github.com/Expensify/App/issues/16163#issuecomment-1656503294
c+ reviewed 🎀 👀 🎀

**Comment by himanshuragi456** [comment] 2023-07-30 11:35
@rushatgabhane no one before me has used the proposal template. I believe Expensify won't appreciate assigning issues to contributors who have not even read the guidelines. It is also risky to assign to someone who did not go through all the guideline rules. If they would have read the guidelines, they must have submitted a proper proposal in the standard template.
To get more clarity, I'll ask on slack here.

**Comment by rushatgabhane** [comment] 2023-07-30 11:43
clarified @himanshuragi456's question on slack https://expensify.slack.com/archives/C01GTK53T8Q/p1690717341268659?thread_ts=1690717192.438039&cid=C01GTK53T8Q

**Comment by roryabraham** [comment] 2023-08-02 00:12
I'm going to make this a weekly now but @NomanIlyas we'll look forward to the PR

**Comment by rushatgabhane** [comment] 2023-08-10 09:23
@NomanIlyas any updates?

**Comment by maddylewis** [comment] 2023-08-17 19:27
wow, this was very buried in my k2. i think my outstanding to-do here is to process $250 payment to @rayane-djouah via Upwork ⚡

**Comment by maddylewis** [comment] 2023-08-24 18:09
@rushatgabhane - bump https://github.com/Expensify/App/issues/16163#issuecomment-1684228485

**Comment by maddylewis** [comment] 2023-08-30 16:36
@rushatgabhane - let us know where we are with this one - ty!

**Comment by roryabraham** [comment] 2023-09-04 07:19
Some recent discussion in slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1693267309039549

Seems we have a good solution incoming soon

**Comment by maddylewis** [comment] 2023-09-11 16:34
PR is awaiting review still

**Comment by maddylewis** [comment] 2023-09-14 18:04
still awaiting review

**Comment by maddylewis** [comment] 2023-09-18 18:10
PR Is still being reviewed

**Comment by roryabraham** [comment] 2023-10-19 01:09
Still awaiting new react-native-reanimated release

**Comment by marcaaron** [comment] 2023-11-22 18:47
What's the latest on this one?

**Comment by roryabraham** [comment] 2023-11-27 06:56
react-native-reanimated release should come on Tuesday: https://expensify.enterprise.slack.com/archives/C04878MDF34/p1701026988133139?thread_ts=1701011610.023949&channel=C04878MDF34&message_ts=1701026988.133139

**Comment by marcaaron** [comment] 2023-11-28 01:29
Sick, thanks @roryabraham !

**Comment by roryabraham** [comment] 2023-12-20 20:09
Looks like the PR was reverted and we have a replacement here: https://github.com/Expensify/App/pull/33336

**Comment by roryabraham** [comment] 2023-12-27 22:45
Seems the last step here is to issue payment tomorrow

**Comment by maddylewis** [comment] 2023-12-28 15:12
im OOO until Jan 2, but will issue payment upon my return 👍

**Comment by roryabraham** [comment] 2023-12-28 19:29
Thanks @maddylewis, making this a weekly

**Comment by situchan** [comment] 2023-12-28 20:13
PR was [reverted](https://github.com/Expensify/App/pull/33325) and 2nd [PR](https://github.com/Expensify/App/pull/33336) is not merged yet

**Comment by roryabraham** [comment] 2023-12-29 02:00
Sorry I missed that. The 2nd PR has been merged

**Comment by isabelastisser** [comment] 2024-01-09 19:28
Payment summary: 

- @rushatgabhane requires payment through NewDot Manual Requests - Contributor+: $250
- @rayane-djouah (Contributor), payment made via Upwork: $250

**Closed by isabelastisser** 2024-01-09 19:28 UTC
Labels: External, Engineering, Daily, NewFeature, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-01-30 16:35
$250 payment approved for @rushatgabhane based on summary above.
