### ISSUE TITLE
iOS - User can't add Fidelity bank because of connectivity error message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11796] opened 2022-10-13 10:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the New expensify app
2. Sign into a valid account
3. Tap on Profile > Workspace > Connect to bank
4. Select "Plaid" and select Fidelity Bank

## Expected Result:
User expects to be able to continue with the VBA flow

## Actual Result:
User receives an error message and can not proceed

## Workaround:
unknown
## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.12.13-3
**Reproducible in staging?:** y
**Reproducible in production?:** can't check
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** https://user-images.githubusercontent.com/43996225/195569592-2f097a1f-51f2-402f-b663-9adeb59d5951.mp4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PauloGasparSv** [comment] 2022-10-13 14:20
Taking a look at this in the afternoon since right now Fidelity connection is unavailable:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/6564265/195622752-72791871-412e-4f45-a026-c9d9ff8c0642.png">

**Comment by kbecciv** [comment] 2022-10-14 17:48
@PauloGasparSv There is another error message in Web when using "Plaid"  option, please let me know if we need to  create a new GH issue for that.

https://user-images.githubusercontent.com/93399543/195909350-1cc2880d-3923-41ec-86d0-048e60312a2c.mp4

**Comment by PauloGasparSv** [comment] 2022-10-14 18:15
No need @kbecciv, this new error replaced the old right?
Sorry for taking so long to work on this, it's the very next item on my todo list : )

**Comment by kavimuru** [comment] 2022-10-14 18:19
@PauloGasparSv  We are still seeing this error message in iOS though. But in the web, we are seeing the above error in step 4 of 5.

**Comment by PauloGasparSv** [comment] 2022-10-14 19:44
No way, there is another window of time where the service is unavailable! 🤦🤦🤦
I'll only have time to look at it on Monday because of that, sorry!

So from 9AM to 11AM ET and from 3PM to 5PM ET the service is down.
Which means I have 11AM to 3PM ET (12PM to 16PM BRT) to debug this on Monday


<img width="501" alt="image" src="https://user-images.githubusercontent.com/6564265/195928716-00a0774a-f88f-41d7-af49-0c6c18e80102.png">

**Comment by PauloGasparSv** [comment] 2022-10-17 11:52
Taking a look at this today during the timeframe the service is up (right after lunch)

**Comment by PauloGasparSv** [comment] 2022-10-17 15:32
@kavimuru  @kbecciv I just tried again on desktop following [this comment+video](https://github.com/Expensify/App/issues/11796#issuecomment-1279295524)!

I got the same error message then tried again with the `SSN` as `3333` as specified in [this S.O.](https://stackoverflow.com/c/expensify/questions/342/525#525) and it worked!

<img width="381" alt="image" src="https://user-images.githubusercontent.com/6564265/196219560-eab0935b-e8be-48a2-b27e-28c9f6ef2ce2.png">

@kavimuru  @kbecciv Can you test this again with that test user but with the `3333` SSN and see if works for you too?

**Comment by kbecciv** [comment] 2022-10-17 15:41
@PauloGasparSv 
Re-testing, update you shortly.

**Comment by PauloGasparSv** [comment] 2022-10-17 16:28
Oh! Maybe it only worked for me because of that too but I thought the SSN fixed it!
Testing it again here

**Comment by PauloGasparSv** [comment] 2022-10-17 16:38
Replicated here, the `SSN` was not the issue.
For some reason the first attempt to save the Fidelity connection fails but if you go back and try again it works.

Investigating the issue here!

**Comment by PauloGasparSv** [comment] 2022-10-17 17:37
Will take some more time to work on this. Can't debug web-secure to understand the error due to the Php8.1 upgrade that is happening right now, Web-Secure is still not working with the updated version.

Will debug this again tomorrow since the timeframe of the Fidelity API's is closing by anyway!

**Comment by PauloGasparSv** [comment] 2022-10-18 18:19
Getting a blank screen now instead of the error, debugging it locally (just finished setting web-scure up with php 8.1)! Not sure what the cause is yet.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/6564265/196512296-31287f80-b512-4081-9012-6e29b6a9dadb.png">

**Comment by PauloGasparSv** [comment] 2022-10-26 19:15
Tested once again but the connection worked at first try this time and did not give me that unvailable timeframe error:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/6564265/198116002-b81cbaf6-cbc0-4fa4-81dc-59d5ea599ec5.png">

Then I removed the bankAccount from my user and tried connecting it to the workspace  again and got this error I'm investigating:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/6564265/198116483-ddae89f7-4bf3-4017-beba-751b20ced053.png">

**Comment by PauloGasparSv** [comment] 2022-10-26 22:05
@kbecciv Do you mind testing this again? Other than staging iOS and Android the Fidelity connection should be working on all the other platforms.

I got the errors above when the service went down like it does daily but it to work locally on Web, locally on mobile and on staging Web!

[This got super confusing](https://expensify.slack.com/archives/C01GTK53T8Q/p1666811104732769) so I'd appreciate another round of tests : p

**Comment by kbecciv** [comment] 2022-10-26 22:08
@PauloGasparSv I will test  the Web and mWeb shortly, will update you with videos.

**Comment by kbecciv** [comment] 2022-10-27 01:38
@PauloGasparSv Just checked with recent build 1.2.20 and got crashed on both environments.

https://user-images.githubusercontent.com/93399543/198170885-3aeeed5d-27c9-4f8a-84b1-5976dbb8f8e9.mp4


https://user-images.githubusercontent.com/93399543/198170924-6da2a814-83d4-4335-a6dc-5902e7846f0f.mp4

**Comment by PauloGasparSv** [comment] 2022-10-27 12:58
What!!!!! Thks @kbecciv, I got that error **once** from all the 10 or attempts I did yesterday.
I'll try digging into this some more and reach for help if I can't find anything

**Comment by PauloGasparSv** [comment] 2022-11-07 17:50
Can't find time to work on the issue this week. Asked for [help on slack](https://expensify.slack.com/archives/C03SSAQ7P/p1667837358217579)!

**Comment by davidcardoza** [comment] 2022-11-10 19:13
@PauloGasparSv Could those go to an external contributor? I can create an Upwork post if so.

**Comment by PauloGasparSv** [comment] 2022-11-10 19:33
Sorry but even after investigating I can't say for sure @davidcardoza! I think this should be kept as internal for now.

**Comment by techievivek** [comment] 2022-11-14 08:05
I did test this couple of times on staging but I wasn't able to reproduce this even once.
<img width="1311" alt="Screenshot 2022-11-14 at 1 08 07 PM" src="https://user-images.githubusercontent.com/35863227/201604727-9753b2b8-92a3-45ad-8fb5-c989701c9811.png">

**Comment by techievivek** [comment] 2022-11-14 08:42
Looking more into it using Logs from here https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22An%20unexpected%20error%20occurred%20while%20trying%20to%20update%20your%20bank%20account%22%20AND%20timestamp%3A%5B2022-11-01T00%3A00%20TO%202022-11-15T23%3A59%5D
Will update shortly.

**Comment by techievivek** [comment] 2022-11-14 10:56
The error is shown for 3 commands. `ConnectBankAccountWithPlaid, UpdateCompanyInformationForBankAccount, UpdatePersonalInformationForBankAccount`. And it has to do with the bankAccountID passed. From newDot when we add a new VBBA for the first two commands it doesn't expect us to pass the bank account but in the instances where errors are thrown it's mostly a bankAccountID is passed and I would assume that bankAccountID doesn't belong to the user and it throws an error when it doesn't find it in the list of bank accounts that user has. In the case of `UpdatePersonalInformationForBankAccount` it throws an error when bankAccountID = 0 so in this case I would guess the pusher hasn't sent the newly created bankAccountID to the user. I will dig into some more during the later part of the day.

**Comment by techievivek** [comment] 2022-11-17 08:13
I wasn't able to look into it because my xdebug was broken, just fixed it by rebuilding the VM.

**Comment by davidcardoza** [comment] 2022-11-22 00:44
@techievivek any update here?

**Comment by techievivek** [comment] 2022-11-23 07:22
Sorry, I was ooo. I will look into it today and give an update.

**Comment by techievivek** [comment] 2022-11-24 13:32
@kbecciv I did have another look into it and tested it again on staging, but I can't seem to reproduce it. Can you try reproducing this one more time because even logs are no longer available? Thanks

**Comment by kbecciv** [comment] 2022-11-25 20:13
Checking

**Comment by techievivek** [comment] 2022-11-28 04:54
@kbecciv That seems like standard connectivity down info and doesn't look like an error from our end. I tested this myself on staging seems like it is fine.


https://user-images.githubusercontent.com/35863227/204196717-6ef5b506-0689-4b71-9d58-c1e3d789d1fd.mov

**Comment by techievivek** [comment] 2022-11-28 06:34
Tried this with a new account and I was able to add the account without any issues. @kbecciv what you have shared is not something we can fix from our end, if you can reproduce some error while adding the bank account then that is something concerning for us. If there are no issues while adding the bank account(unrelated to Plaid showing something from their end) things seem to work fine.

@davidcardoza Any thoughts here?

**Comment by davidcardoza** [comment] 2022-11-29 00:07
I tried reproducing myself and couldn't come up with an error. I am going to close this out. Please reopen if the issue is reproducible Expensify error and not one stemming from Plaid.

**Closed by davidcardoza** 2022-11-29 00:07 UTC
Labels: Engineering, Daily, Bug

**Comment by mvtglobally** [comment] 2022-12-05 21:22
check this tread as well https://expensify.slack.com/archives/C01GTK53T8Q/p1666811104732769

**Comment by davidcardoza** [comment] 2022-12-05 22:08
Tested on iOS. I am still not reproducing 


https://user-images.githubusercontent.com/6643649/205752746-34e824c7-96e9-480b-8994-704af2b8ebe3.MP4
