### ISSUE TITLE
Chat – New Message button missing after navigating back from thread in room

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47973] opened 2024-08-24 21:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.24-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4886687
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any room chat with a long history
4. Mark the latest message as unread
5. Scroll up the chat list and go into any sub-thread (Create one if needed)
6. Go back to the main chat

## Expected Result:
New Message button appears

## Actual Result:
New Message button is missing

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/da95912b-3200-428a-a126-5d08b323ad69

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-08-24 21:39
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jaydamani** [comment] 2024-08-25 14:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"New message" does not appear when you go back from thread
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/pages/home/report/ReportActionsList.tsx#L224

The "New Message" marker appears based on `unreadMarkerReportActionID`. When we go back to chat from thread, the scroll position is at the bottom of chat for 1 frame and then scrolled to the message with thread on another frame. Due to the useMemo, the unreadMarkerReportActionID is not recalculated for the second frame so the "New Message" marker is not shown.
### What changes do you think we should make in order to solve the problem?

Update the second argument of useMemo to include scrollingVerticalOffset.current

**Comment by garrettmknight** [comment] 2024-08-28 19:02
Can't reproduce on v9.0.25-13, closing.

**Closed by garrettmknight** 2024-08-28 19:02 UTC
Labels: Daily, Overdue, Bug

**Comment by garrettmknight** [comment] 2024-08-30 17:32
Still not reproducing for me:


https://github.com/user-attachments/assets/a969f4e9-b5fe-4078-9a02-8ee182b36b21
