### ISSUE TITLE
[HOLD for payment 2024-03-18] [$500] [Simplified Collect][Members] WorkspaceMemberDetailsPage: full page implementation (without the Change owner feature)

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35715] opened 2024-02-02 20:19 UTC
Implement `WorkspaceMemberDetailsPage: full page implementation (without the Change owner feature)` from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c86d95485fe71541</li>
        <li>Upwork Job ID: 1755658986412068864</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2024-02-02 20:19
@burczu can you please comment here so I can assign you to the issue?

**Comment by burczu** [comment] 2024-02-05 09:05
Hi! I'm Bartek from Callstack - expert contributor group. I'll work on this issue so please assign me. Thank you.

**Comment by laurenreidexpensify** [comment] 2024-02-08 17:54
@burczu is there a draft PR up for this yet?

**Comment by burczu** [comment] 2024-02-09 07:49
@laurenreidexpensify this is one of the issues regardning bigger project and I'm working on these issues in an order - I didn't start working on this issue yet - I'll let you know here once started

**Comment by abdulrahuman5196** [comment] 2024-02-12 15:55
Not overdue. Waiting on PR

**Comment by trjExpensify** [comment] 2024-02-12 16:10
Hehe, looks like @burczu is ⭐'d on the issue, so only his updates will clear the `overdue` label and keep Melvin at bay.

**Comment by burczu** [comment] 2024-02-13 06:44
not overdue - I haven't started the implementation yet

**Comment by abdulrahuman5196** [comment] 2024-02-19 09:06
Waiting on PR

**Comment by luacmartins** [comment] 2024-02-19 17:08
@burczu is this on hold for another issue?

**Comment by burczu** [comment] 2024-02-20 13:23
yes, I'll write a comment here once I start the implementation

**Comment by abdulrahuman5196** [comment] 2024-02-26 10:38
Waiting on PR

**Comment by CortneyOfstad** [comment] 2024-02-26 14:16
@burczu any update on the implementtion?

**Comment by burczu** [comment] 2024-02-28 16:12
Still not started working on this issue.

**Comment by CortneyOfstad** [comment] 2024-02-28 17:39
@burczu can you have a PR created by EOW? This has been assigned for a few weeks, so we would like to get this resolved as soon as we can. Thank you!

**Comment by burczu** [comment] 2024-02-28 18:15
@CortneyOfstad I'm not sure if you are aware that this issue is one of 7 issues related to the new Members page (this is part of the Simplified collect project). I'm assigned to all of them and work on them one by one - I know this was assigned some time ago but this was intended.

Good news is that this issue is next in my queue and I'll start working on it once this PR is merged: https://github.com/Expensify/App/pull/37199 - most likely tomorrow. But I don't think the PR for this issue will be ready EOW - I think Monday/Tuesday is more probable.

**Comment by luacmartins** [comment] 2024-02-28 18:32
@CortneyOfstad thanks for checking in and asking for an update. As @burczu said, they are making progress on the other issues in the pipeline. We'll get to this one soon enough :)

**Comment by CortneyOfstad** [comment] 2024-02-28 19:05
@burczu no worries and thank you for that additional context! I was not aware of that, so I recommend you sharing that now!

**Comment by burczu** [comment] 2024-03-01 11:03
Just to inform everyone: I'm starting the implementation of this issue and will post some daily updates here on the progress.

**Comment by luacmartins** [comment] 2024-03-04 16:16
@burczu do we have a draft PR that you can link to this issue yet?

**Comment by burczu** [comment] 2024-03-05 08:28
> @burczu do we have a draft PR that you can link to this issue yet?

Added

**Comment by luacmartins** [comment] 2024-03-05 14:08
Thanks for the update!

**Comment by burczu** [comment] 2024-03-06 11:11
@luacmartins The PR is ready for review.

**Comment by luacmartins** [comment] 2024-03-19 23:21
Left a review on the draft PR today

**Comment by laurenreidexpensify** [comment] 2024-03-21 11:09
@abdulrahuman5196 please apply to job in Upwork - https://www.upwork.com/jobs/~01183d516188835326- thanks

**Comment by abdulrahuman5196** [comment] 2024-03-23 08:50
> @abdulrahuman5196 please apply to job in Upwork - https://www.upwork.com/jobs/~01183d516188835326- thanks

@laurenreidexpensify This link shows 404 error for me.

**Comment by laurenreidexpensify** [comment] 2024-03-26 10:17
Sorry @abdulrahuman5196 https://www.upwork.com/jobs/~01183d516188835326

**Comment by abdulrahuman5196** [comment] 2024-03-26 18:14
> Sorry @abdulrahuman5196 https://www.upwork.com/jobs/~01183d516188835326

@laurenreidexpensify Applied on upwork.

**Comment by laurenreidexpensify** [comment] 2024-03-27 11:57
Thanks - offer sent @abdulrahuman5196, will issue payment once you accept

**Comment by laurenreidexpensify** [comment] 2024-03-27 13:32
- Contributor: @burczu is from an agency-contributor and not due payment
- ROLE: @abdulrahuman5196 paid $500 via Upwork

**Closed** 2024-03-27 13:37 UTC
Labels: External, Engineering, Daily, NewFeature, Awaiting Payment
