### ISSUE TITLE
[HOLD for payment 2023-10-13] [HOLD for payment 2023-10-12] [$500] Dev: Web - Hmm it's not there message appears if open private notes in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27591] opened 2023-09-16 18:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create workspace
2. Go offline
3. Go to #admins
4. Click on header
5. Go to Private notes

## Expected Result:
It should show private notes

## Actual Result:
hmm it's not there message appear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5f57fd36-9c67-4bf7-8a05-fac81fadd920

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694784369659399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114cd1c2b0e08bcd2</li>
        <li>Upwork Job ID: 1703114589030166528</li>
        <li>Last Price Increase: 2023-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Contributor | 26937500</li>
<li>gadhiyamanan | Reporter | 26937502</li>
<li>tienifr | Contributor | 26938659</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-16 18:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
hmm it's not there message appears if open private notes in offline mode
### What is the root cause of that problem?
the `FullPageNotFoundView` shouldShow has `(!report.isLoadingPrivateNotes && network.isOffline && _.isEmpty(lodashGet(report, 'privateNotes', {})))` which make it true when offline and page not loaded before
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/PrivateNotes/PrivateNotesListPage.js#L122
### What changes do you think we should make in order to solve the problem?
In this case, We can show offline view instead of not fount
```javascript
const isOfflineAndEmpty = !report.isLoadingPrivateNotes && network.isOffline && _.isEmpty(lodashGet(report, 'privateNotes', {}));


<FullPageNotFoundView
    shouldShow={_.isEmpty(report.reportID) || isOfflineAndEmpty}
    icon={isOfflineAndEmpty ? Expensicons.OfflineCloud : undefined}
    titleKey={isOfflineAndEmpty ? "common.youAppearToBeOffline" : undefined}
    subtitleKey={isOfflineAndEmpty ? "common.thisFeatureRequiresInternet" : undefined}
    onBackButtonPress={() => Navigation.goBack()}
>

```
we need to add prop icon to `FullPageNotFoundView` to control it by prop

also we can remove subtitle or use other subtitle words

### What alternative solutions did you explore? (Optional)
we can instead remove `network.isOffline &&` and keep page in loading

**Comment by narefyev91** [comment] 2023-09-18 07:51
Proposal from @ahmedGaber93 looks good to me https://github.com/Expensify/App/issues/27591#issuecomment-1722289142
If feature required internet we show show those info instead of not found page
🎀 👀 🎀 C+ reviewed

**Comment by narefyev91** [comment] 2023-09-18 08:50
@tienifr based on your changes - what user will see - loading screen?

**Comment by ahmedGaber93** [comment] 2023-09-18 09:22
I think there is no prevent API call here. because useEffect deps hase `network.isOffline` and when user back online this dependency will change, and the api will call

https://github.com/Expensify/App/blob/4d97719d69654cc18960bac5fd4a95965e4b4215/src/pages/PrivateNotes/PrivateNotesListPage.js#L64-L69

**Comment by narefyev91** [comment] 2023-09-18 11:59
Yup i think we need here correct behaviour - in case in expected results we not see a clear picture.
We have 2 cases here - either we show offline screen - with suggestion to go online or we show loaded - until user will not get back to online
First case - proposal from @ahmedGaber93
Second case proposal from @tienifr 
We will need your help @grgia

**Comment by narefyev91** [comment] 2023-09-21 07:02
Friendly bump - @grgia

**Comment by grgia** [comment] 2023-09-25 08:06
@narefyev91 could you explain what you mean by "offline screen" with a screenshot

**Comment by narefyev91** [comment] 2023-09-25 08:21
@grgia 
<img width="379" alt="Screenshot 2023-09-25 at 11 20 41" src="https://github.com/Expensify/App/assets/28352309/fe4c5bb8-2576-4e0b-bfa9-b0bb0ec3fe24">

**Comment by grgia** [comment] 2023-09-25 11:15
I prefer the offline page pattern @narefyev91, could you remind me which proposal that was?

**Comment by narefyev91** [comment] 2023-09-25 11:45
@grgia https://github.com/Expensify/App/issues/27591#issuecomment-1722289142 from @ahmedGaber93

**Comment by ahmedGaber93** [comment] 2023-09-26 08:51
I think is a normal and expected behavior to displaying offline page when **user offline and no onxy data yet**

**Comment by grgia** [comment] 2023-09-29 01:59
@narefyev91 is that your proposal selection?

**Comment by narefyev91** [comment] 2023-09-29 07:43
> @narefyev91 is that your proposal selection?

If we want to show offline page - yes

**Comment by grgia** [comment] 2023-09-29 07:49
Apologies, I didn't mean to assign. Let me check on this internally

**Comment by grgia** [comment] 2023-09-29 08:07
@tienifr @narefyev91 

I agree with the above reasoning, let's use the loading page pattern instead

**Comment by narefyev91** [comment] 2023-09-29 08:09
> @tienifr @narefyev91
> 
> I agree with the above reasoning, let's use the loading page pattern instead

Cool! Thanks! Updated proposal pick from @tienifr

**Comment by kbecciv** [comment] 2023-10-12 17:46
Issue is not fixed, build 1.3.83.1

https://github.com/Expensify/App/assets/93399543/9fac804b-c15f-427a-8537-a7cde0c4bf1a

**Comment by tranvantoan-qn** [comment] 2023-10-13 02:44
This seem not fixed yet OR there is a similar case as I reported here (but marked as DUPE) - https://expensify.slack.com/archives/C049HHMV9SM/p1697131558107909

Furthermore, with this solution, consider the following scenario:
- User is in **online** mode.
- User views **A's private notes**.
- User goes **offline**.
- User navigates to somewhere else in the app in **offline** mode.
- User goes back to **A's private notes**.

**Question**: Will the private notes still display, or will the offline page display? We need to **make sure that the private notes are still showing.**

(IMO, showing Skeleton UI can be a better option)

**Comment by NicMendonca** [comment] 2023-10-13 19:01
@grgia what do you think? ^

**Comment by grgia** [comment] 2023-10-16 13:26
@tranvantoan-qn 

Yes, if the data is loaded, we should show it.

**Comment by tranvantoan-qn** [comment] 2023-10-16 13:38
So we need to confirm that the original proposal is already merged then to check the case I mentioned above

**Comment by grgia** [comment] 2023-10-19 12:44
@narefyev91 could you take a look at the progression of this issue?

**Comment by narefyev91** [comment] 2023-10-19 12:53
@tienifr can you please take a look at the latest comments - seems after we get on Private Notes - and after some times spinner is moving away and we still see "Hmmm is not here page"

**Comment by NicMendonca** [comment] 2023-10-20 20:19
reporter: @gadhiyamanan - you've been paid! 
contributor: @tienifr - you've been paid! 


@tienifr do we need to keep this open for any reason?

**Comment by grgia** [comment] 2023-10-24 11:29
closing

**Closed by grgia** 2023-10-24 11:29 UTC
Labels: External, Daily, Overdue, Awaiting Payment
