### ISSUE TITLE
[$250] Removing all members by pressing enter/return key on the remove popup sets focus on the disabled Remove button - Reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8934] opened 2022-05-11 03:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Open any workspace
3. Click Manage members
4. Check Select all checkbox
5. Click on the Remove button
6. Press enter/return key on the remove popup

## Expected Result:
The disabled remove button should not be focused/highlighted

## Actual Result:
The disabled remove button is focused/highlighted

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.57-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/167765030-b640eca6-9c48-44a4-830f-0dca17fb8a0a.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649961604941709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by madmax330** [comment] 2022-05-16 08:14
This should be an easy fix

**Comment by Justicea83** [comment] 2022-05-16 16:08
Yes

> Wait @Justicea83 did you assign this issue cos you want to take it on, or cos you're wanting to be the contributor manager engineer?

 @laurenreidexpensify I wanna take it on

**Comment by metehanozyurt** [comment] 2022-05-16 16:29
## Proposal
### Cause

When we press enter button goes focus:visible state.  

related style here:

https://github.com/Expensify/App/blob/eddcc0f167ad05f0bc794cf81e7c30a0020226c0/web/index.html#L35-L38

### Solution
when button disable we can pass this style `boxShadow: 'none'`.
```js
<Button
                            medium
                            danger
                            style={[styles.ml2, this.state.selectedEmployees.length === 0 ? {boxShadow: 'none'} : {}]}
                            isDisabled={this.state.selectedEmployees.length === 0}
                            text={this.props.translate('common.remove')}
                            onPress={this.askForConfirmationToRemove}
                        />
```

https://user-images.githubusercontent.com/6093207/168638280-65b88e0d-c562-4894-9335-b7954df9118f.mp4

**Comment by Santhosh-Sellavel** [comment] 2022-05-16 18:07
> Yes
> 
> > Wait @Justicea83 did you assign this issue cos you want to take it on, or cos you're wanting to be the contributor manager engineer?
> 
> @laurenreidexpensify I wanna take it on

@thienlnam If @Justicea83  wanna take this one then we can remove the external & help wanted label here, can you confirm this?

cc: @laurenreidexpensify

**Comment by Santhosh-Sellavel** [comment] 2022-05-16 18:14
Also, there are couple more issues I saw on slack
1 - https://expensify.slack.com/archives/C01GTK53T8Q/p1652631140387289
2 - https://expensify.slack.com/archives/C01GTK53T8Q/p1652632605348319

Both seem related to this issue since the unnecessary focus is set to buttons in all the cases.

Another common thing all happens Safari Web
cc: @thienlnam

**Comment by adeel0202** [comment] 2022-05-16 18:26
> Another common thing is all issues occurred on Safari Web

@Santhosh-Sellavel, this issue occurs on chrome web as well. The two other issues occur only on safari web.

**Comment by Santhosh-Sellavel** [comment] 2022-05-16 19:16
https://github.com/Expensify/App/issues/8935 This might be related to @Justicea83

**Comment by Justicea83** [comment] 2022-05-19 11:59
> Also, there are couple more issues I saw on slack 1 - https://expensify.slack.com/archives/C01GTK53T8Q/p1652631140387289 2 - https://expensify.slack.com/archives/C01GTK53T8Q/p1652632605348319
> 
> Both seem related to this issue since the unnecessary focus is set to buttons in all the cases.
> 
> Another common thing is all issues occurred on Safari Web cc: @thienlnam

I don't think they're related in the sense that one button is disabled the other isn't.

**Comment by Justicea83** [comment] 2022-05-19 16:33
https://expensify.slack.com/archives/C01GTK53T8Q/p1652631140387289 is fixed in the linked PR, but can we create separate issue for this(https://expensify.slack.com/archives/C01GTK53T8Q/p1652632605348319) ?

**Comment by Santhosh-Sellavel** [comment] 2022-05-19 18:30
> but can we create separate issue for this(https://expensify.slack.com/archives/C01GTK53T8Q/p1652632605348319) ?

I will leave a comment in slack that it's a different issue, so the issue will be created when the time comes. @Justicea83

**Comment by Santhosh-Sellavel** [comment] 2022-05-19 18:30
> https://github.com/Expensify/App/issues/8935 This might be related to @Justicea83

What about this one, is it a different issue too?

**Comment by Justicea83** [comment] 2022-05-20 08:23
> > #8935 This might be related to @Justicea83
> 
> What about this one, is it a different issue too?

This is a different issue and i guess its closed

**Comment by Santhosh-Sellavel** [comment] 2022-05-20 11:20
> > > #8935 This might be related to @Justicea83
> 
> > 
> 
> > What about this one, is it a different issue too?
> 
> 
> 
> This is a different issue and i guess its closed

It's solved by the PR. I can't reproduce so I left a comment to close it.

**Comment by Santhosh-Sellavel** [comment] 2022-05-27 19:31
@Justicea83 The fix PR is causing regression as mentioned here https://github.com/Expensify/App/pull/9093#issuecomment-1137558114

**Comment by adeel0202** [comment] 2022-06-14 12:28
The fix for this issue has been deployed to production 25 days ago and it is not reproducible now, so I think we are good to close it. cc: @Justicea83 
Also, I'm expecting the reporting bonus @laurenreidexpensify

**Comment by laurenreidexpensify** [comment] 2022-07-27 13:21
@adeel0202 sorry we missed this one. Paid 👍🏽

**Comment by adeel0202** [comment] 2022-07-27 13:30
Thanks @laurenreidexpensify, and no worries 😊

**Closed** 2022-08-01 10:59 UTC
Labels: Reviewing, Engineering, Daily, Internal
