### ISSUE TITLE
[HOLD for payment 2024-12-05] Verify account - No right side window animation when 2FA setup is dismissed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52339] opened 2024-11-11 20:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.60-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** wjiojdoowjojwodj@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Gmail account.
3. Go to Settings > Security > Two-factor authentication.
4. Dismiss the RHP.

## Expected Result:
There will be animation when Validate your account RHP from 2FA setup is dismissed.

## Actual Result:
There is no animation (side window doesn't slide close like on other pages) when Validate your account RHP from 2FA setup is dismissed.

## Workaround:
Гтлтщцт

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fb7d41ec-7ad3-4b76-86a5-47706005d2ac
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by deetergp** [comment] 2024-11-11 23:40
I don't think this is a blocker since it is a new feature and isn't breaking any existing functionality.

**Comment by Christinadobrzyn** [comment] 2024-11-12 04:22
The steps in the OP verify the issue but I'm not sure if this should be a priority. Asking the team.

**Comment by bernhardoj** [comment] 2024-11-12 04:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No animation when closing the 2fa validate code page.

### What is the root cause of that problem?
The validate code itself is a modal and it will be visible as long as the user is not validated.
https://github.com/Expensify/App/blob/64cb4ee92b1f4c66e5deb96e23caf47e25423c00/src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx#L164-L176

When we close the page, the modal stays visible until the 2FA page is closed (by `TwoFactorAuthActions.quitAndNavigateBack`).

### What changes do you think we should make in order to solve the problem?

We need to store the modal visibility state to a state.
```
const [isModalVisible, setIsModalVisible] = useState(!isUserValidated);
```

And we can update it whenever isUserValidated is updated.

```
useEffect(() => {
    setIsModalVisible(!isUserValidated);
}, [isUserValidated]);
```

Then, we can set it to false when closing the modal.
```
onClose={() => {
    setIsModalVisible(false)
    TwoFactorAuthActions.quitAndNavigateBack(backTo)
}}
```

**Comment by mountiny** [comment] 2024-11-12 12:19
@deetergp feel free to assign me if you want as I reviewed the offending PR, happy to take over

**Comment by mountiny** [comment] 2024-11-12 23:19
@hungvu193 as a C+ on the offending PR, can you please review the proposal here?

**Comment by hungvu193** [comment] 2024-11-12 23:40
Yeah surre

**Comment by ishakakkad** [comment] 2024-11-13 05:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Animation is not showing when closing two factor authentication modal.

### What is the root cause of that problem?
2FA modal only shows when isUserValidated = false. In case we close the modal without authenticate isUserValidated is always false so it does not animate it.
https://github.com/Expensify/App/blob/64cb4ee92b1f4c66e5deb96e23caf47e25423c00/src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx#L164-L167

### What changes do you think we should make in order to solve the problem?
To fix this problem we need to make sure as long as close event is fire modal will hidden. To fix this we need to introduce new state variable.
```
const [showValidateCodeModal, setValidateCodeModal] = useState(false);
```
And pass state value as props in ValidateCodeActionModal, so once state value set to false modal will be closed.
https://github.com/Expensify/App/blob/64cb4ee92b1f4c66e5deb96e23caf47e25423c00/src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx#L167
Replace with
```
isVisible={showValidateCodeModal}
```
Set showValidateCodeModal to false when we close modal. To make it cleaner extract modal close logic into handler. 
https://github.com/Expensify/App/blob/64cb4ee92b1f4c66e5deb96e23caf47e25423c00/src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx#L175
Replace with
```
onClose={handleValidateCodeModalClose}
```
```
const handleValidateCodeModalClose = () => {
    setValidateCodeModal(false);
    TwoFactorAuthActions.quitAndNavigateBack(backTo);
};
```
Update showValidateCodeModal value whenever isUserValidated is changed. We already have useEffect which runs when isUserValidated value changed. So we can use same effect.
https://github.com/Expensify/App/blob/64cb4ee92b1f4c66e5deb96e23caf47e25423c00/src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx#L55-L62
Replace with 
```
useEffect(() => {
    setValidateCodeModal(!isUserValidated);
    // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
    if (account?.requiresTwoFactorAuth || account?.recoveryCodes || !isUserValidated) {
        return;
    }
    Session.toggleTwoFactorAuth(true);
    // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps -- We want to run this when component mounts
}, [isUserValidated]);
```



### What alternative solutions did you explore? (Optional)
NA

**Comment by ishakakkad** [comment] 2024-11-13 05:24
Contributor details
Your Expensify account email: isha.kakkad.invest@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018e905fce69c8896f

**Comment by hungvu193** [comment] 2024-11-15 14:31
Sorry not yet. I've been a bit under the water today. I'll try to review this weekend

**Comment by hungvu193** [comment] 2024-11-17 08:41
@ishakakkad Your proposal is a dupe of @bernhardoj  proposal. Please checkout our [contributing guides](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) here before posting proposal. Ty.


Let's go with @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/52339#issuecomment-2469611645).

🎀 👀 🎀  C+ reviewed.

**Comment by bernhardoj** [comment] 2024-11-19 06:37
PR is ready

cc: @hungvu193

**Comment by Christinadobrzyn** [comment] 2024-12-02 22:09
@hungvu193 can you let us know about a regression test? TY!

**Comment by hungvu193** [comment] 2024-12-03 03:46
## Regression Tests:
**2FA Flow on Web**:
1. Login with a brand new account.
2. Go to Settings => Security => Two factor authentication.
3. Click outside to dismiss the modal.
4. Verify that the modal is dismissed with animation.

**Other flows using ValidateCodeActionModal**:
*Prerequisite*: Using your Android Chrome browser
1. Login with a brand-new account.
2. Go to any flow that needs validate code (VerifyContactMethod or 2FA or Add Bank Account etc...)
3. Once the ValidateCode modal appears, press the ack button.
4. Verify that the modal is closed with animation.

Do we 👍 or 👎  ?

**Comment by hungvu193** [comment] 2024-12-04 03:46
@mountiny I'm not sure if I'm eligible to be paid for this issue. During PR process we realized this issue also happened every where on mWeb Chrome and we fixed it as well.

**Comment by mountiny** [comment] 2024-12-04 12:30
@hungvu193 to confirm, you have been a c+ on the offending PR, right? then I think we should not really issue a payment here. Or am I misunderstanding your question?

**Comment by hungvu193** [comment] 2024-12-05 09:09
> @hungvu193 to confirm, you have been a c+ on the offending PR, right? then I think we should not really issue a payment here. Or am I misunderstanding your question?

Ah I mean, while working on the PR, we found out the the right side animation didn't work on mWeb (which is not a regression from the PR that I reviewed) and we fixed it as well.

**Comment by mountiny** [comment] 2024-12-05 12:34
ok sounds like $250 to @hungvu193 too

**Comment by Christinadobrzyn** [comment] 2024-12-05 21:44
Regression test - https://github.com/Expensify/Expensify/issues/450960

Payment summary here - https://github.com/Expensify/App/issues/52339#issuecomment-2519688188

Feel free to submit a NewDot payment request @hungvu193 and @bernhardoj

**Comment by bernhardoj** [comment] 2024-12-06 03:41
Requested in ND.

**Comment by Christinadobrzyn** [comment] 2024-12-06 15:36
DMd @hungvu193 to request payment in ND. Going to close this out.

**Closed by Christinadobrzyn** 2024-12-06 15:36 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug

**Comment by hungvu193** [comment] 2024-12-06 15:48
Thanks for reminding me. I've just requested on ND

**Comment by JmillsExpensify** [comment] 2024-12-09 10:24
$250 approved for @bernhardoj via the summary

**Comment by garrettmknight** [comment] 2024-12-12 11:23
$250 approved for @hungvu193
