### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Web - On reload on attachment preview and close, app displays random chat for few seconds

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23958] opened 2023-07-31 20:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any image attachment
4. Click and open attachment in preview
5. Copy the attachment preview url
6. Go to other chat
7. Paste the saved url in the current search bar
8. Reload
9. Close the preview and observe that app displays random chat for few seconds before again displaying the right chat

## Expected Result:
App should display same chat in which attachment is located when we close the preview - navigation should occur before closing the modal

## Actual Result:
App displays random chat when we click on attachment, reload on preview and close the preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/258e753d-c23d-4cf4-9b62-df1ffce7e4c0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690103101672499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ceaa38feb4bfce8</li>
        <li>Upwork Job ID: 1687635491784937472</li>
        <li>Last Price Increase: 2023-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26201629</li>
<li>dhanashree-sawant | Reporter | 26201630</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-08-05 01:24
Updated the reproduction steps in the original description, thanks!

**Comment by rushatgabhane** [comment] 2023-08-05 17:56
I like @tienifr's proposal!  https://github.com/Expensify/App/issues/23958#issuecomment-1659554531
C+ reviewed 🎀 👀 🎀

**Comment by rushatgabhane** [comment] 2023-08-05 17:58
@bernhardoj thanks for your proposal but I think we should display the report where attachment is coming from vs the last acessed report id

**Comment by sakluger** [comment] 2023-08-09 20:55
Friendly bump @Julesssss

**Comment by Julesssss** [comment] 2023-08-14 15:46
> I don't think so, the attachment URL is just same like the internal link, when we click on the internal link, we should navigate to that page.

it would be less annoying to me if the report redirect occurred **PRIOR** to the attachment modal being closed. That's the annoying part to me. 

> we want to navigate to target report after dismissing the modal.

Lets update the desired behaviour: Yes you should see the parent report when the modal is closed, but the navigation shouldn't occur only after closing the modal.

Does anyone disagree?

**Comment by sakluger** [comment] 2023-08-14 16:10
> Lets update the desired behaviour: Yes you should see the parent report when the modal is closed, but the navigation shouldn't occur only after closing the modal.

To rephrase, are you saying that the navigation should occur before closing the modal?

**Comment by Julesssss** [comment] 2023-08-14 17:50
Nice so that looks good to me, but we'll need to look out for regressions here. Just in case other things depend on the existing logic.

**Comment by Julesssss** [comment] 2023-08-14 17:50
@rushatgabhane can you review again pls

**Comment by sakluger** [comment] 2023-08-17 18:40
> As we are combining the proposal from @tienifr and mine, will it make sense for me to get the bounty too?

Yes, I think that would make sense. Since you're not actually writing the PR, your payment will not be the full amount - once the proposal is accepted, I can discuss with the team to see what amount makes sense.

@rushatgabhane could you please have a look at the updated proposal?

**Comment by rushatgabhane** [comment] 2023-08-18 04:07
@Julesssss  @tienifr's [proposal](https://github.com/Expensify/App/issues/23958#issuecomment-1659554531) tests well

C+ reviewed 🎀 👀 🎀

**Comment by Julesssss** [comment] 2023-08-20 20:13
_FYI I am OOO this week. Feel free to reassign in the meantime, or I will be back on Monday 28th_

**Comment by sakluger** [comment] 2023-08-23 21:38
@cristipaval I've assigned you to help review the PR: https://github.com/Expensify/App/pull/25521

If you can't review, let us know, @Julesssss can do it when he's back.

**Comment by sakluger** [comment] 2023-09-05 17:44
I went ahead and paid out the reporter bounty to @dhanashree-sawant

@rushatgabhane could you please complete the BZ checklist by tomorrow? That way we can approve your manual payment right away after the 7-day hold.

**Comment by sakluger** [comment] 2023-09-06 18:03
Thanks @rushatgabhane! I assigned @JmillsExpensify to handle the payment request.

Everyone else has been paid out, I'll leave this open so Jason can approve the final payment.

**Comment by sakluger** [comment] 2023-09-08 03:08
We're good to close, the NewDot payment requests will be handled.

**Closed by sakluger** 2023-09-08 03:08 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-07 15:17
$1,500 payment approved for @rushatgabhane based on BZ summary.
