### ISSUE TITLE
[HOLD for payment 2022-12-01][$250] Infinite spinner for user details when creating chats offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12276] opened 2022-10-28 21:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Turn off internet connection
2. Hit green fab > New chat
3. Press the chat details for the user and notice the spinner

## Expected Result:
Some user details should show up

## Actual Result:
Infinite spinner

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.21-4

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/198737560-82be6ace-96bd-49b6-9e0b-d037162992df.mov
https://user-images.githubusercontent.com/43996225/198737571-0813f482-f1ba-4c25-95b7-e0093a3caa1b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @luacmartins 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666990493452569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2022-10-29 15:49
reproduced with totally new chats. Asked in Slack here if we still want to fix https://expensify.slack.com/archives/C01GTK53T8Q/p1667058521092939?thread_ts=1666990493.452569&cid=C01GTK53T8Q

**Comment by MitchExpensify** [comment] 2022-11-02 01:10
We do still want to fix! Labeling external

**Comment by MitchExpensify** [comment] 2022-11-02 01:13
[Upwork Job](https://www.upwork.com/jobs/~01125a78e44d2fd173)

**Comment by imranali126** [comment] 2022-11-02 01:24
Hi this is your fetching issue.. When data is not coming then spinning infinity..

**Comment by imranali126** [comment] 2022-11-02 01:37
> Triggered auto assignment to Contributor-plus team member for initial proposal review - @mananjadhav (`External`)

Hi this is your fetching issue.. When data is not coming then spinning infinity..

**Comment by AwaisSikander** [comment] 2022-11-02 01:54
[Upwork Job](https://www.upwork.com/jobs/~01125a78e44d2fd173) @kavimuru  I have tried to explain the solution in upwork perposal for this job

**Comment by mananjadhav** [comment] 2022-11-02 02:41
@AwaisSikander @imranali126 Please refer to the contributing guidelines [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). 

@AwaisSikander Please send your proposal here so that it can be reviewed.

**Comment by AwaisSikander** [comment] 2022-11-02 02:56
@mananjadhav 
Infinite Loading is due to Ajax Promise call which change the state of loading to true when u are offline

**Comment by AwaisSikander** [comment] 2022-11-02 02:57
I would love to solve this problem.
Kind Regards
Awais Sikander
awais-cs-eng.com

**Comment by mananjadhav** [comment] 2022-11-02 05:23
@AwaisSikander We would need a proposal with some technical details, and some granular details like the lines you would change, the files you'll update the code to?

> @mananjadhav Infinite Loading is due to Ajax Promise call which change the state of loading to true when u are offline

Also please take a look at our source code to get the understanding on how our API calls work. They ain't the general AJAX calls that you see in JS.

**Comment by deetergp** [comment] 2022-11-04 19:12
Hey @tienifr thanks for your interest in this issue! You are putting the cart before the horse by submitting a pull request. Please submit your proposals with technical details in the GH issue. It is from the GH issues that we select the winning proposal, then move on to pull requests, and PR reviews.

**Comment by mananjadhav** [comment] 2022-11-05 19:31
Thanks for the interest @tienifr. But as @deetergp mentioned, please send a proposal instead of a PR to be able to review and move forward to the PR stage. I like your idea of creating `optimisticData` but I don't agree with a lot of your changes on modify the function parameters, I am not sure how you're gonna get `icons[0]` for login being offline etc.

So can you send in a proposal with the technical details and explanation to be able to better review this?

**Comment by tienifr** [comment] 2022-11-05 19:33
@mananjadhav @deetergp thank for your review, I'll update my proposal asap.

**Comment by tienifr** [comment] 2022-11-06 17:09
# Updated Proposal
## Solution

The main idea is to create the default records for the new users then update them as optimisticData in `personalDetails`.
To do that, I have to get the data from `option` value such as icons, login.
<img width="647" alt="Screen Shot 2022-11-06 at 23 27 56" src="https://user-images.githubusercontent.com/113963320/200182513-7702cc28-d425-4bb8-9d6b-1c1a10467b9e.png">

In https://github.com/Expensify/App/blob/0724337138a4d80f6603074cc9af5c186cb524ec/src/pages/NewChatPage.js#L200-L215 I'll pass `option` to `getOrCreateChatReport` instead of `login`.

```diff
    createChat(option) {
-        this.getOrCreateChatReport([option.login]);
+        this.getOrCreateChatReport([option]);
    }

    /**
     * Creates a new group chat with all the selected options and the current user,
     * or navigates to the existing chat if one with those participants already exists.
     */
    createGroup() {
-        const userLogins = _.pluck(this.state.selectedOptions, 'login');
-        if (userLogins.length < 1) {
+        if (this.state.selectedOptions.length < 1) {
            return;
        }
-        this.getOrCreateChatReport(userLogins);
+        this.getOrCreateChatReport(this.state.selectedOptions);
    }
```
 In https://github.com/Expensify/App/blob/0724337138a4d80f6603074cc9af5c186cb524ec/src/pages/NewChatPage.js#L139
I'll find the `userLogins` from `option` to keep the former logic, then get the default records for the new users (`newPersonalDetail`) from `PersonalDetails.buildNewPersonalDetails(option)` and pass it to `openReport`

```diff
-    getOrCreateChatReport(userLogins) {
+    getOrCreateChatReport(option) {
+       const userLogins = _.pluck(option, 'login');
        const formattedUserLogins = _.map(userLogins, login => OptionsListUtils.addSMSDomainIfPhoneNumber(login).toLowerCase());
        let newChat = {};
+       let newPersonalDetail = {};
        const chat = ReportUtils.getChatByParticipants(formattedUserLogins);
        if (!chat) {
            newChat = ReportUtils.buildOptimisticChatReport(formattedUserLogins);
+           newPersonalDetail = PersonalDetails.buildNewPersonalDetails(option);
        }
        const reportID = chat ? chat.reportID : newChat.reportID;
-        Report.openReport(reportID, newChat.participants, newChat);
+        Report.openReport(reportID, newChat.participants, newChat, newPersonalDetail);
        Navigation.navigate(ROUTES.getReportRoute(reportID));
    }
```

In https://github.com/Expensify/App/blob/main/src/libs/actions/PersonalDetails.js

I'll build the new function `buildNewPersonalDetails` to create the default records for the new users.
I have to filter the new users and then build the default record for each one.

```diff
+ function buildNewPersonalDetails(options) {
+    const newPersonalDetails = _.filter(options, (o) => {
+        const login = Str.isValidPhone(o.login) ? OptionsListUtils.addSMSDomainIfPhoneNumber(o.login).toLowerCase() : o.login.toLowerCase();
+        return !personalDetails[login];
+    });
+    return _.reduce(newPersonalDetails, (acc, cur) => {
+        const personalDetail = buildNewPersonalDetail(cur);
+        acc[personalDetail.login] = personalDetail;
+        return acc;
+    }, {});
+ }
```
Function `buildNewPersonalDetail` is to build the default record for each user. In `option` we have `icons` field that contains the default avatars so I can use it out of the box.

```diff
+ function buildNewPersonalDetail(detail) {
+    const login = Str.isValidPhone(detail.login) ? OptionsListUtils.addSMSDomainIfPhoneNumber(detail.login).toLowerCase() : detail.login.toLowerCase();
+    return {
+        avatar: detail.icons[0],
+        avatarHighResolution: detail.icons[0],
+        login,
+        displayName: login,
+        firstName: '',
+        lastName: '',
+        payPalMeAddress: '',
+        pronouns: '',
+        timezone: CONST.DEFAULT_TIME_ZONE,
+        validated: false,
+    };
+ }
```

Finally, In https://github.com/Expensify/App/blob/0724337138a4d80f6603074cc9af5c186cb524ec/src/libs/actions/Report.js#L701
I'll pass new arg `newPersonalDetail` to add the new users to `personalDetails` before it's updated from server.
```diff
- function openReport(reportID, participantList = [], newReportObject = {}) {
+ function openReport(reportID, participantList = [], newReportObject = {}, newPersonalDetail = {}) {
...

            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`,
            value: ReportUtils.buildOptimisticCreatedReportAction(newReportObject.ownerEmail),
        };
+        onyxData.optimisticData[2] = {
+            onyxMethod: CONST.ONYX.METHOD.MERGE,
+            key: ONYXKEYS.PERSONAL_DETAILS,
+            value: newPersonalDetail,
+        };
    }
    API.write('OpenReport',
        {
```

**Comment by tienifr** [comment] 2022-11-06 17:10
@mananjadhav @deetergp I've updated my proposal, pls help check again. Thanks

**Comment by mananjadhav** [comment] 2022-11-07 06:36
Thanks for your proposal. We can work out small kinks in the PR. But yeah I am fine with your proposal

@deetergp All yours.


🎀 👀 🎀 
C+ reviewed

**Comment by deetergp** [comment] 2022-11-07 20:29
@tienifr Thank you for updating your proposal, it looks good 👍 

@mananjadhav Thanks for your review 👍 

@MitchExpensify let's hire @tienifr to do the work ✅

**Comment by tienifr** [comment] 2022-11-10 00:42
@MitchExpensify Thanks, I've applied to the job, the PR will be ready by November 12

**Comment by tienifr** [comment] 2022-11-10 04:47
Hi @mananjadhav I just created a PR for this issue https://github.com/Expensify/App/issues/12151, please help to review it. Thanks

**Comment by mananjadhav** [comment] 2022-11-10 17:06
I am going to review this one in a while

**Comment by mananjadhav** [comment] 2022-11-10 21:22
@kavimuru @tienifr Quick question, are you still able to reproduce this?


https://user-images.githubusercontent.com/3069065/201206250-62387a82-6a15-471b-b606-dce7d9bb64ef.mov

**Comment by deetergp** [comment] 2022-11-10 22:26
Oh, hmm… Nice catch, @mananjadhav. Confirmed that the infinite spinner no longer happens anymore in `main` in web.

**Comment by tienifr** [comment] 2022-11-11 02:18
I can't reproduce anymore

**Comment by kavimuru** [comment] 2022-11-11 02:31
@mananjadhav Not able to reproduce any more.

https://user-images.githubusercontent.com/43996225/201249787-c5045572-1823-4393-a8f5-403121a0c006.mp4

**Comment by mananjadhav** [comment] 2022-11-14 08:56
On Hold, waiting for the QA to run the KI tests

**Comment by MitchExpensify** [comment] 2022-11-17 00:41
Not overdue, on hold

**Comment by mananjadhav** [comment] 2022-11-17 03:46
@kavimuru there isn't any update of KI test since a week? Shouldn't this issue be considered in KI test?

**Comment by MitchExpensify** [comment] 2022-11-17 23:10
bump @kavimuru

**Comment by mvtglobally** [comment] 2022-11-18 00:06
Because the issue had HOLD in header, it was excluded from KIs. We will add it this week to retest  and update

**Comment by mananjadhav** [comment] 2022-11-18 02:21
Thanks @mvtglobally.

**Comment by deetergp** [comment] 2022-11-21 17:28
Not overdue. Still on hold, pending the results from the KIs. Eager to see what @mvtglobally has to say!

**Comment by mvtglobally** [comment] 2022-11-22 21:25
Issue not reproducible during KI retests. (First week)

**Comment by mananjadhav** [comment] 2022-11-27 06:42
Waiting for the second week of KI. If not reproducible, then we'll decide on the payout and close this one out.

**Comment by trjExpensify** [comment] 2022-11-30 12:16
👋 Let's not wait for KI tests before making a call here. For example, if this was an issue not reported by Applause, it wouldn’t get re-tested anyway - so it’s a partial strategy/solution for only a subset of issues in the App repo. Given that you both can’t reproduce it anymore, let's move forward with closing it. 

Mitch as the assigned BZ can re-test for good measure if a third opinion is needed ahead of settling up if that’s required here. 👍

**Comment by mananjadhav** [comment] 2022-11-30 12:22
Ohh is that so! I can confirm it isn't reproducible anymore.

**Comment by deetergp** [comment] 2022-11-30 18:28
If @mananjadhav says it is no longer reproducible, then I think we can go ahead and close this one.

**Comment by mananjadhav** [comment] 2022-11-30 18:39
@deetergp @trjExpensify this might have to be open for the payout here?

**Comment by deetergp** [comment] 2022-11-30 18:53
Good point, @mananjadhav 😅

**Comment by mananjadhav** [comment] 2022-12-01 18:44
@MitchExpensify Can you help with the payout here?

**Comment by JmillsExpensify** [comment] 2022-12-01 18:58
Updated the title. Let's get this one paid out today!

**Comment by MitchExpensify** [comment] 2022-12-02 18:13
All paid!

**Closed** 2022-12-02 18:14 UTC
Labels: External, Daily, Help Wanted, Bug
