### ISSUE TITLE
[HOLD for payment 2024-03-11] [$500] Login - Two offline indicators in login screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37336] opened 2024-02-27 18:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Reporter:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Log out if logged in.
3. Go offline.

## Expected Result:
There will be only one offline indicator.

## Actual Result:
There are two offline indicators - One below email input, one at the bottom of the screen.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/5b9cce13-dfed-4ffd-9c18-cb2f101ca9d1)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c29d8f94d59d6b6e</li>
        <li>Upwork Job ID: 1762550251289456640</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-27 18:48
We think that this bug might be related to #vip-vsb
@quinthar

**Comment by allroundexperts** [comment] 2024-02-27 19:22
@marcaaron Can we clarify on where to show the indicator on large and small screens?

**Comment by allroundexperts** [comment] 2024-02-27 19:31
@marcaaron Can we clarify on where to show the indicator on large and small screens?

In Prod, its always below the form for both large and small screens FYI.

If we want to maintain the behaviour on Prod, then @gijoe0295's [proposal](https://github.com/Expensify/App/issues/37336#issuecomment-1967392753) looks good. 

If however, we want to show the indicator at the bottom of the page for both large and small screens, then @dukenv0307's [proposal](https://github.com/Expensify/App/issues/37336#issuecomment-1967391468) looks good.

Lastly, if we want a mix and match of both (on large screens display the indicator at the bottom of form and on small screen display it at the bottom of the page), then @neonbhai's [proposal](https://github.com/Expensify/App/issues/37336#issuecomment-1967405749) would work well!

🎀 👀 🎀 C+ reviewed

**Comment by marcaaron** [comment] 2024-02-27 20:40
Thanks so much for the help here. We have decided this is not urgent enough to block the deploy so let's assign it back to whoever created the regression. Which I believe would be @suneox in this case? @allroundexperts (or anyone) please kindly confirm that [this PR](https://github.com/Expensify/App/pull/36803) did indeed cause the regression? 🙇

**Comment by shawnborton** [comment] 2024-02-28 13:53
@dubielzyk-expensify makes a fair point - we could just pick one spot and use it across both mobile and desktop.

**Comment by dannymcclain** [comment] 2024-02-28 14:07
Agree with the other designers—I kinda think we should just stick with just below the button for all viewport sizes. Especially because the button is disabled. I think keeping the indicator close would be helpful/make offline status (and therefore why you can't sign in) more obvious.

**Comment by marcaaron** [comment] 2024-02-28 21:33
Many thanks @suneox 🙇

**Comment by marcaaron** [comment] 2024-03-04 18:34
Looks like the fix is on staging.

**Comment by laurenreidexpensify** [comment] 2024-03-12 10:59
Payment Summary [here](https://github.com/Expensify/App/issues/37336#issuecomment-1989226508)

**Closed by laurenreidexpensify** 2024-03-12 10:59 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-04-01 17:42
$500 approved for @allroundexperts
