### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] Request money - Not here page appears in RHP after requesting money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32807] opened 2023-12-11 13:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Open a new chat,
3. Click + > Request money.
4. Enter amount and proceed to confirmation page.
5. Click Request.
(Might need to repeat Step 3 - 5 to see the issue).

## Expected Result:
Not here page will not show up in RHP after requesting money.

## Actual Result:
While RHP is closing, not here page can be seen in the RHP.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/11bbdfe2-84f1-4167-9f45-cb5e50465e17

![image](https://github.com/Expensify/App/assets/93399543/da8e5455-1a01-4f40-bbd4-3d6af549dfd6)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e13942c515d900b4</li>
        <li>Upwork Job ID: 1734223793696989184</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 28036036</li>
<li>paultsimura | Contributor | 28036038</li>
</ul></li>
    </ul>
</details>

**Comment by tgolen** [comment] 2023-12-11 14:45
I'm going to demote this from being a deploy blocker. It doesn't effect the user in any way and the flow still works. I've applied the help wanted label to get some more eyes on this.

**Comment by tgolen** [comment] 2023-12-11 16:20
Ah, cool. I didn't know about the `isFocused` hook. Looks like that would do the trick. I like using `shouldShow`. I don't think we want a loading indicator during those transitions.

**Comment by paultsimura** [comment] 2023-12-11 18:28
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/32849

**Comment by paultsimura** [comment] 2023-12-12 18:11
@Julesssss This shouldn't have been closed as it's not paid out yet, if I'm not mistaken.

**Comment by Julesssss** [comment] 2023-12-13 09:14
Thanks

**Comment by peterdbarkerUK** [comment] 2023-12-21 20:04
$500 to @paultsimura for Contributor, paid and thanks! 

@getusha could you take a spin through the regression checklist, and then accept [the offer](https://www.upwork.com/nx/wm/offer/28036036)?

**Comment by getusha** [comment] 2023-12-21 20:15
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28618

- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28618/files#r1434478894

- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/a

- [x] Determine if we should create a regression test for this bug. *i think this bug is minor and hard to notice so No**.

- [ ] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by getusha** [comment] 2023-12-21 20:19
@peterdbarkerUK accepted the offer

**Comment by tgolen** [comment] 2023-12-26 15:54
@peterdbarkerUK Is there more to do here to complete the payments?

**Comment by peterdbarkerUK** [comment] 2023-12-27 11:33
Nope, was just OoO. 

Payments processed!

**Closed by peterdbarkerUK** 2023-12-27 11:33 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
