### ISSUE TITLE
[$500] Split Distance - Unable to create split distance request from FAB menu

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33673] opened 2023-12-27 21:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat > + > Split bill.
2. Go to Distance.
3. Create a split distance request.
4. Click FAB button > + > Request money.
5. Go to Distance.
6. Enter addresses > Next.

## Expected Result:
User is able to create split distance request from FAB menu.

## Actual Result:
There is no option to split distance request from FAB menu.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4757997d-0611-4429-9cc1-88c4e69141ec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a142d59d8337d5f</li>
        <li>Upwork Job ID: 1740122740055339008</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by zukilover** [comment] 2023-12-27 22:15
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Split request is not shown in FAB for distance request

### What is the root cause of that problem?
Split request is disabled for distance request as defined here:
https://github.com/Expensify/App/blob/80ebfdd3ba2b95aeb9243ccd5e8992d562e04902/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L272

### What changes do you think we should make in order to solve the problem?
Change this line:
https://github.com/Expensify/App/blob/80ebfdd3ba2b95aeb9243ccd5e8992d562e04902/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L303-L304

to:

```javascript
<OptionsSelector
    canSelectMultipleOptions
```

(Remove `isAllowedToSplit` condition)

### What alternative solutions did you explore? (Optional)

N/A

**Comment by aim-salam** [comment] 2023-12-28 00:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split Distance - Unable to create split distance request from FAB menu

### What is the root cause of that problem?

FloatingActionButtonAndPopover.js file

menuItems in PopoverMenu component didnt have Split Bill item.

### What changes do you think we should make in order to solve the problem?

FloatingActionButtonAndPopover.js file

add splitbill item in menuItems


### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2024-01-03 04:34
Hmm, yeah I don't understand why you'd split a distance request.

**Comment by jliexpensify** [comment] 2024-01-17 00:11
Hi @JmillsExpensify just coming from this [thread](https://expensify.slack.com/archives/C05DWUDHVK7/p1705329555812999?thread_ts=1703805792.841859&cid=C05DWUDHVK7) - Neil has suggested implementing P2P distance requests are implemented first before working on these types of issues. Did you want to close this? cc @shubham1206agra

**Comment by JmillsExpensify** [comment] 2024-01-24 03:20
Yes, I think we should close it.

**Closed by JmillsExpensify** 2024-01-24 03:20 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
