### ISSUE TITLE
[HOLD for payment 2023-09-08] [$250] Migrate index.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16202] opened 2023-03-20 08:44 UTC
### Filenames
- [ ] [src/components/SignInPageForm/index.js](https://github.com/Expensify/App/blob/main/src/components/SignInPageForm/index.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139e2c951f46681da</li>
        <li>Upwork Job ID: 1685092318042664960</li>
        <li>Last Price Increase: 2023-07-29</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 25889648</li>
</ul></li>
    </ul>
</details>

**Comment by dayana7204** [comment] 2023-06-27 19:30
I am ready to work on this ticket. :)

**Comment by vdem0115** [comment] 2023-07-07 14:43
I would like to work on this issue.

**Comment by olexyt** [comment] 2023-07-07 14:52
I can work on this issue.

**Comment by mejed-alkoutaini** [comment] 2023-07-11 19:12
I'm able to work on this if needed!

**Comment by ojasjadhav2** [comment] 2023-07-29 03:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate `SignInPageForm/index.js` to function component

### What is the root cause of that problem?
need to change class based component to functional

### What changes do you think we should make in order to solve the problem?
- component state and props from class to function syntax
- render method from class to function syntax
- lifecycle methods to hooks(if any)
- update callbacks from class to function syntax (possibly with useCallback hook)
- update refs from class to function syntax
- any other class component logic to function component
- and ensure no regressions occur.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by alexxxwork** [comment] 2023-07-29 04:19
I would love to work on this issue

**Comment by reinesarchisorte** [comment] 2023-07-29 04:27
Can I work this one?

**Comment by priyankrawat** [comment] 2023-07-29 04:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migration of [components/SignInPageForm/index.js](https://github.com/Expensify/App/blob/main/src/components/SignInPageForm/index.js) to the function component.

### What is the root cause of that problem?
No root cause, just need to migrate class component to function component.


### What changes do you think we should make in order to solve the problem?
1. Replace the class component SignInPageForm with a function component.
2. Use the useRef hook to create the formRef and replace the ref used in the class component.
3. Replace the instance method preventFormDefault with a regular function within the function component.
4. Utilize the useEffect hook to handle the setup and cleanup of event listeners.
5. Finally make sure there is no regression.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Shampinon** [comment] 2023-07-29 04:58
Proporsal

```
export const Form = (props) => {
  const formRef = useRef();
  
  const preventFormDefault = useCallback((event) => {
    event.preventDefault();
  }, []);
  useEffect(() => {
   const form = formRef.current;
    if (form) {
        form.setAttribute('method', 'post');
        form.setAttribute('action', '/');

        form.addEventListener('submit', preventFormDefault);
   
    }
  }, [prventFormDefault])
  
  
          return (
            <FormElement
                ref={formRef }
                {...props}
            />
        );
}
```

**Comment by ishpaul777** [comment] 2023-07-29 06:05
Would love to work on this

**Comment by sakluger** [comment] 2023-08-01 05:34
Hey everyone, please note that we will not assign an issue to you just because you ask to work on it - you'll need to submit a proposal and we will select the best proposal. Please review https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md for our contributor guide to see how to work with Expensify and get selected for jobs.

**Comment by sakluger** [comment] 2023-08-01 16:41
@rayane-djouah thanks for that, I missed that announcement. You're right - for this particular set of issues, we're taking volunteers without proposals. We're only considering people who volunteered after the hold was taken off.

@reinesarchisorte was the first one to volunteer that isn't already assigned another issue, but @rayane-djouah was the very first one to volunteer and has already submitted a PR for their other assigned issue. @0xmiroslav I'll let you decide who we should assign this issue to!

**Comment by sakluger** [comment] 2023-08-23 21:24
Looks like @0xmiroslav reviewed and requested changes a few days ago.

**Comment by sakluger** [comment] 2023-09-18 05:28
Really sorry for the delay! Not sure why this wasn't switched back to daily.

**Summarizing payouts for this issue:**

Contributor: @rayane-djouah $250 (hired and paid via Upwork)
Contributor+: @0xmiroslav $250 (payable via Manual Request after BZ checklist is completed)

@0xmiroslav I'm going to close the issue, please request payment via NewDot manual request.

**Closed by sakluger** 2023-09-18 05:28 UTC
Labels: External, Engineering, Weekly, NewFeature, Awaiting Payment
