### ISSUE TITLE
[HOLD for payment 2024-04-15] [$250] mWeb - Send money-In send money report page, an extra skeleton preview is displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39306] opened 2024-03-29 22:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report with no previous conversation
3. Tap plus icon -- send money
4.Enter an amount and tap next
5.Tap pay elsewhere
6.Open the newly created send money request

## Expected Result:
In send money report page, an extra skeleton preview must not be displayed

## Actual Result:
In send money report page, an extra skeleton preview is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d8b90e32-751f-4412-9101-7cecdc937004

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01523fec2621a20689</li>
        <li>Upwork Job ID: 1773847838939754496</li>
        <li>Last Price Increase: 2024-03-29</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by lanitochka17** [comment] 2024-03-29 22:09
@hayata-suenaga  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-29 22:09
We think that this bug might be related to #vip-vsp

**Comment by mountiny** [comment] 2024-03-29 22:26
I am going to take over this one, I think ti might be related to https://github.com/Expensify/App/pull/36657 @dukenv0307 @abdulrahuman5196 the issue is actually minor and I dont think its a blocker

**Comment by mountiny** [comment] 2024-03-29 22:28
@abdulrahuman5196 @dukenv0307 could you please test if this occurs also in revert of the PR?

**Comment by mmmbytes** [comment] 2024-03-30 07:40
# **Proposal**

## Please re-state the problem that we are trying to solve in this issue.

In send money report page, an extra skeleton preview is displayed

## What is the root cause of that problem?

The root cause is found [here](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/pages/home/report/ReportActionsView.tsx#L500). 

```
const moneyRequestActions = reportActions.filter(
            (action) => action.actionName === CONST.REPORT.ACTIONS.TYPE.IOU && action.originalMessage && action.originalMessage.type === CONST.IOU.REPORT_ACTION_TYPE.CREATE,
        );
```

We are filtering out all report action types except CREATE. This causes the moneyRequestActions.length number to be incorrect when the originalMessage action type is PAY, for example. 

## What changes do you think we should make in order to solve the problem?

This depends on product requirements. Assuming we want to apply this flow for any IOU ReportAction we can drop the originalMessage filters like so:

```
 const moneyRequestActions = reportActions.filter(
            (action) => action.actionName === CONST.REPORT.ACTIONS.TYPE.IOU 
);
```

Alternatively, if we want to only allow certain types, we can extend the conditional. For example, if the types are PAY and CREATE, it would look like this:  

```
const moneyRequestActions = reportActions.filter(
            (action) =>
                action.actionName === CONST.REPORT.ACTIONS.TYPE.IOU &&
                action.originalMessage &&
                (action.originalMessage.type === CONST.IOU.REPORT_ACTION_TYPE.CREATE || action.originalMessage.type === CONST.IOU.REPORT_ACTION_TYPE.PAY),
        );
```

## What alternative solutions did you explore? (Optional)

N/A

**Comment by mananjadhav** [comment] 2024-03-30 19:25
@mountiny Does this need C+ review?

**Comment by mmmbytes** [comment] 2024-03-30 19:59
@dukenv0307 @mountiny 

It looks like you used the root cause and second solution from my proposal for this PR. As I said, we simply extend the conditional to match the product requirements. Would you please confirm if you will award me the bug bounty since my work is being used for this?

**Comment by mmmbytes** [comment] 2024-03-31 19:38
Thank you for your response, dukenv0307. For clarity, if you re-read my proposal you can see that I mentioned that depending on product requirements, we can extend the conditional to encompass other action types such as PAY. 

This is what your PR has done. You extended the conditional to include PAY and TRACK. The only difference between my proposal and your PR is that you check for IOUDetails if the action type is PAY. This is a minor detail, but the logic is still the same.

**Comment by mountiny** [comment] 2024-03-31 20:45
@mananjadhav Assigning @abdulrahuman5196 coming from the original PR

@mmmbytes Thank you for the proposal. Since this bug originated from recent PR, the guidelines suggest the PR author should be the one fixing it. Unfortunately, in this case, we have only confirmed that after you have already made the proposal.

**Comment by abdulrahuman5196** [comment] 2024-04-01 07:03
Checking now

**Comment by mmmbytes** [comment] 2024-04-01 20:56
@mountiny I see. Thanks for clarifying this.

**Comment by Christinadobrzyn** [comment] 2024-04-16 00:41
Payouts due:

- [ ] Contributor: $250 @abdulrahuman5196 (paid in Upwork - https://www.upwork.com/nx/wm/workroom/36962727/overview)

Upwork job is [here](https://www.upwork.com/jobs/~01523fec2621a20689).

@mananjadhav should you be paid as the C+?

@mananjadhav or @abdulrahuman5196 do we need a regression test?

**Comment by mananjadhav** [comment] 2024-04-16 02:51
@Christinadobrzyn i don’t think any payouts are needed. IIRC this was a regression.

**Comment by Christinadobrzyn** [comment] 2024-04-16 02:57
Oh thanks @mananjadhav  - sorry @abdulrahuman5196 I just requested a refund for the $250 paid to you via Upwork. sorry about that - I should have asked before paying. Let me know if I'm missing anything

**Comment by abdulrahuman5196** [comment] 2024-04-16 05:53
@Christinadobrzyn done.

**Comment by Christinadobrzyn** [comment] 2024-04-17 07:16
thank you @abdulrahuman5196 so sorry about that. I think this can be closed since there's no payments or regression test. 

Closing but let me know if I'm missing anything

**Closed by Christinadobrzyn** 2024-04-17 07:16 UTC
Labels: External, Engineering, Daily, Awaiting Payment
