### ISSUE TITLE
Chat - Compose box not highlighted after sending and copying a message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44447] opened 2024-06-26 12:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4672050
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Send a message
4. Copy the message
5. Type something in compose box

## Expected Result:
Compose box should be highlighted as it is focused

## Actual Result:
Compose box is not highlighted after copying a message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/adff6725-d54b-4246-a2e2-3479e15f9d14

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-26 12:14
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-26 12:14
We think that this bug might be related to #vip-vsp

**Comment by joekaufmanexpensify** [comment] 2024-06-26 14:37
I can reproduce this. However, this is a pretty niche set of reproduction steps, since it only happens after copying a message when you immediately go to send another AND requires being on android mobile web. 

It also has a clear workaround (tapping out and back into the compose box after copying a message fixes this). So I'm not really convinced there is much user impact here.

**Comment by joekaufmanexpensify** [comment] 2024-06-26 14:38
Since we paused #vip-vsb, this issue doesn't feel important enough to prioritize fixing to override that the project is paused. Even if it weren't paused, I'd be in the camp of doing nothing until we get feedback from actual customers on this.

**Comment by joekaufmanexpensify** [comment] 2024-06-26 14:38
Closing for now.

**Closed by joekaufmanexpensify** 2024-06-26 14:38 UTC
Labels: Daily, Bug
