### ISSUE TITLE
[$500] [QAB] Shortcut - Request money shortcut for workspace remains after workspace is deleted

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39051] opened 2024-03-27 12:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Request money from the workspace chat.
4. Delete the workspace.
5. Click FAB.
6. Click Request money shortcut.

## Expected Result:
After deleting the workspace, Request money shortcut should lead user to select a new participant.

## Actual Result:
After deleting the workspace, Request money shortcut for the deleted workspace still remains. Clicking on the shortcut results in not here page.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4dd89a61-1b43-4387-b186-e8e07467a27f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016af2ad690a3296e0</li>
        <li>Upwork Job ID: 1772979000228327424</li>
        <li>Last Price Increase: 2024-03-28</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-27 12:51
@mallenexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-27 12:51
We think that this bug might be related to #vip-vsb.

**Comment by lakchote** [comment] 2024-03-27 13:29
Related to https://github.com/Expensify/App/pull/38669

cc @Gonals @parasharrajat

**Comment by Habtamu-Asefa** [comment] 2024-03-27 16:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Shortcut not being updated when a workspace related to the shortcut item is deleted

### What is the root cause of that problem?
When a workspace is deleted, the shortcut(QuickAction) is not cleared.

### What changes do you think we should make in order to solve the problem?

When a workspace is deleted checking if it is in quick action, if it is resetting quick action
Adding a code like

```
  let policyInQuickAction: string | undefined;
    Onyx.connect(
       { key: ONYXKEYS.NVP_QUICK_ACTION_GLOBAL_CREATE,
        callback: (value)=> {
            policyInQuickAction = ReportUtils.getReportPolicyID(value?.chatReportID);
        },}
    )
    // Reset the quickAction policy
    if (policyID === policyInQuickAction){
        resetQuickAction();
    }
```

around here
https://github.com/Expensify/App/blob/69a2849f163640021e3248eda536d2db112cb153/src/libs/actions/Policy.ts#L432-L435

and a code like this to clear the current quick action
```
/**
 * Reset quick action
 */
function resetQuickAction(){
    Onyx.set(ONYXKEYS.NVP_QUICK_ACTION_GLOBAL_CREATE, null);
}
```


### What alternative solutions did you explore? (Optional)

**Comment by lakchote** [comment] 2024-03-28 07:13
Putting @parasharrajat as the reviewer since he has context on the issue.

**Comment by nkdengineer** [comment] 2024-03-28 07:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After deleting the workspace, Request money shortcut for the deleted workspace still remains. Clicking on the shortcut results in not here page.

### What is the root cause of that problem?
We don't clear or hide the quick action when the report is archived or we cannot access to this report anymore

### What changes do you think we should make in order to solve the problem?
1. In `FloatingActionButtonAndPopover`, we should subscribe the report of quickAction with id is `quickAction.chatReportID`

2. Add a useEffect that will clear the `quickAction` if the report is archived or it become `undefined` or we cannot access to this report anymore, we will clear the quickAction. That can cover all cases like we remove the user from workspace or we delete the workspace on another device, ....

3. Create a util function to clear the `quickAction`
### What alternative solutions did you explore? (Optional)

For point 2, we also can create a state to control the quickAction should be displayed or not and update this accordingly in the useEffect that is mentioned at point 2.

**Comment by mallenexpensify** [comment] 2024-03-28 18:34
@parasharrajat can you share the Slack link plz? 
I'm adding to #wave-collect  cuz it's the earliest project that someone would encounter this bug.

**Comment by mallenexpensify** [comment] 2024-03-29 23:21
Thanks @parasharrajat , put on hold, removed `Help Wanted` and `External`

**Comment by trjExpensify** [comment] 2024-04-04 18:11
Did we confirm with @Gonals that https://github.com/Expensify/App/issues/38051 will take care of it? 

>I'm adding to #wave-collect cuz it's the earliest project that someone would encounter this bug.

@mallenexpensify more to the point, it's related to the Quick Action Button (QAB) project.

**Comment by trjExpensify** [comment] 2024-04-04 20:08
Dope!

**Comment by lakchote** [comment] 2024-04-15 08:45
[PR](https://github.com/Expensify/App/pull/39413) got approved, waiting for another reviewer's approval to be merged.

**Comment by mallenexpensify** [comment] 2024-04-23 23:06
PR is on main
https://github.com/Expensify/App/pull/39413

**Comment by mallenexpensify** [comment] 2024-04-26 00:09
Taking off hold, added `retest-weekly` label.

**Comment by trjExpensify** [comment] 2024-05-02 09:48
I think this is probably the same as: https://github.com/Expensify/App/issues/41467

We have a PR up for that, so this can be closed. @Gonals can confirm though!

**Comment by Gonals** [comment] 2024-05-03 08:17
Yep! This should be handled by https://github.com/Expensify/App/pull/41474

**Closed by Gonals** 2024-05-03 08:17 UTC
Labels: Engineering, Weekly, Bug, retest-weekly

**Comment by trjExpensify** [comment] 2024-05-03 10:21
Excellllent. Another one bites the dust!
