### ISSUE TITLE
[$250] Chat - The page crashes when text from the link is pasted into the compose box

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41322] opened 2024-04-30 12:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.68-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4529259
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go to any 1:1 chat
4. In another tab open link https://www.lipsum.com/feed/html
5. Copy all text using keys Ctrl+A and Ctrl+C
6. Open 1:1 chat and using Ctrl+V paste the text some times

## Expected Result:
The page doesn't crash when text from the link is pasted into the compose box

## Actual Result:
The page crashes when text from the link is pasted into the compose box

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/48891862-5bf8-4e31-b142-297a765d4914

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f12644a0568c03a</li>
        <li>Upwork Job ID: 1785835515701108736</li>
        <li>Last Price Increase: 2024-05-30</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-30 12:42
@sakluger FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment] 2024-04-30 12:43
We think that this bug might be related to #vip-vsb

**Comment by sakluger** [comment] 2024-05-02 00:56
Added to vip-vsp and added the external label.

**Comment by abdulrahuman5196** [comment] 2024-05-07 12:17
@gijoe0295 Kindly provide the proposals as per our contributing guidelines, with root cause analysis

**Comment by abdulrahuman5196** [comment] 2024-05-07 12:18
We don't have any proposals to approve yet.

**Comment by sakluger** [comment] 2024-05-10 04:07
Still no proposals.

**Comment by mvtglobally** [comment] 2024-05-13 14:18
Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment] 2024-05-15 22:51
I'll retest this tomorrow.

**Comment by sakluger** [comment] 2024-05-16 21:05
@anmurali I'm assigning you to help watch this issue while I'm OOO through May 31.

The latest update is that Applause says this is no longer reproducible. I wanted to test myself before closing, but I haven't been able to since the site issues have been pretty bad the past day or two. I'll leave it up to you whether we need to test again or if we can just close the issue.

**Comment by mvtglobally** [comment] 2024-05-22 04:39
Issue not reproducible during KI retests. (Second week)

**Comment by abdulrahuman5196** [comment] 2024-05-22 20:03
> Issue not reproducible during KI retests. (Second week)

@anmurali I think we can close this.

**Comment by mvtglobally** [comment] 2024-05-30 01:27
Issue not reproducible during KI retests. (Third week)

**Closed** 2024-06-03 23:15 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
