### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] LHN – Concierge chat opens when change priority mode to Most recent

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46110] opened 2024-07-24 13:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4761236&group_by=cases:section_id&group_order=asc&group_id=296775
**Email or phone of affected tester (no customers):** gocemate+a686@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login with new gmail account
2. Go to Account settings> Preferences> Focus
3. Go to Account settings> Preferences> Most recent

## Expected Result:
User should stay on Preferences page

## Actual Result:
User navigates to Concierge chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/user-attachments/assets/8c012b76-f938-4e90-aa59-9ddf3294cda6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd28acd2df01cf0e</li>
        <li>Upwork Job ID: 1816460956793747307</li>
        <li>Last Price Increase: 2024-07-25</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103326560</li>
<li>nkdengineer | Contributor | 103326561</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by lanitochka17** [comment] 2024-07-24 13:23
We think that this bug might be related to #vip-vsp

**Comment by francoisl** [comment] 2024-07-24 17:05
Hm interestingly, it doesn't happen if you already have multiple chats or rooms. Doesn't seem like something worth blocking for, going to demote.

**Comment by nkdengineer** [comment] 2024-07-25 08:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User navigates to Concierge chat

### What is the root cause of that problem?
When the onboarding data is changed we resolve the onboarding value here. If we log in with a new account and complete the onboarding flow and then `isOnboardingFlowCompleted` the second time, `isOnboardingFlowStatusKnownPromise` promise will return the onboarding data to the old data because after we complete the onboarding flow, the onboarding data is changed and we don't reset the `isOnboardingFlowStatusKnownPromise` promise.

https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/actions/Welcome.ts#L178


The problem happens when we change the priority mode from `focus` to `recent`, we have a logic here to call the `OpenApp` API again.
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/actions/App.ts#L72-L76

It leads `isLoadingApp` changing and this `useEffect` is triggered again. As I explained above because the `onboarding` data is the old data `onNotCompleted` callback is called and the navigation state is reset. Then the concierge chat is opened as the recent chat.
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L59-L63
### What changes do you think we should make in order to solve the problem?
We should reset the `isOnboardingFlowStatusKnownPromise` promise when the onboarding data is changed

```
isOnboardingFlowStatusKnownPromise = new Promise<OnboardingData>((resolve) => {
    resolveOnboardingFlowStatus = resolve;
});
resolveOnboardingFlowStatus(value);
```

https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/actions/App.ts#L72-L76

### What alternative solutions did you explore? (Optional)
Or we can revert the change in this PR https://github.com/Expensify/App/pull/45327 to use an `onboarding` variable and update it every time the onboarding data changes.
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/actions/App.ts#L72-L76

**Comment by DylanDylann** [comment] 2024-07-29 10:46
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/46110#issuecomment-2249809016) looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by arosiclair** [comment] 2024-07-29 15:43
Proposal looks okay. Can @filip-solecki or @mountiny also take a look?

**Comment by filip-solecki** [comment] 2024-07-30 04:56
Looks good for me too 👍

**Comment by nkdengineer** [comment] 2024-07-31 09:12
@DylanDylann this [PR](https://github.com/Expensify/App/pull/46559) is ready for review

**Comment by sonialiap** [comment] 2024-08-16 13:09
Payment summary:
- @DylanDylann $250 - offer in upwork
- @nkdengineer $250 - offer in upwork

**Comment by sonialiap** [comment] 2024-08-16 13:10
@mallenexpensify I'm OOO Aug 19-30, adding leave buddy. 
Status: if no regressions please complete [payment](https://github.com/Expensify/App/issues/46110#issuecomment-2283547612) and submit new QA test once Dylan completes the checklist

**Comment by mallenexpensify** [comment] 2024-08-20 00:34
@DylanDylann , @nkdengineer , can you confirm if there are regressions on this issue?  See [one revert after staging in the PR.](https://github.com/Expensify/App/pull/46559#issuecomment-2274437825)  Thx

**Comment by nkdengineer** [comment] 2024-08-20 02:49
@mallenexpensify We had a regression on this issue and I fixed it [here](https://github.com/Expensify/App/issues/47054). All revert PRs were closed.

**Comment by mallenexpensify** [comment] 2024-08-21 00:13
Thx @nkdengineer per CONTRIBUTING.md
> a 50% penalty will be applied to the Contributor and [Contributor+](https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md) for each regression on an issue

Contributor: @nkdengineer  paid $125 via Upwork
Contributor+: @DylanDylann paid $125 via Upwork. 

@DylanDylann plz complete the BZ checklist above. , thanks

**Comment by DylanDylann** [comment] 2024-08-21 04:50
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Login with new gmail account
2. Go to Account settings> Preferences> Focus
3. Go to Account settings> Preferences> Most recent
4. Verify that: User should stay on Preferences page


Do we agree 👍 or 👎

**Comment by DylanDylann** [comment] 2024-08-26 09:06
Not overdue. Waiting for @mallenexpensify

**Comment by mallenexpensify** [comment] 2024-08-26 15:13
Thanks @DylanDylann , all set!
- https://github.com/Expensify/Expensify/issues/423313

**Closed by mallenexpensify** 2024-08-26 15:13 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
