### ISSUE TITLE
[$1000] Workspace - Custom invite message is not preserved after refreshing the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22842] opened 2023-07-13 20:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Workspace > any workspace > Members > Invite
3. Select some members > Next
4. Edit the invite message
5. Refresh the page

## Expected Result:
Custom invite message is preserved after refreshing the page

## Actual Result:
Custom invite message is not preserved after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40.2
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e53c931b-3980-4dfc-aaf8-42743b72ef4d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a28e2b1bec4d29a</li>
        <li>Upwork Job ID: 1679941413948968960</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-14 08:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Custom invite message is not preserved after refreshing the workspace invite page.

### What is the root cause of that problem?
`Form` component supports saving draft value to `Onyx` using `shouldSaveDraft`.
If use `shouldSaveDraft`, the form item value will be saved to `Onyx` and restore after refresing page.
https://github.com/Expensify/App/blob/754b6edf175a10deb6c6876bdba13c2a99e0ffec/src/components/Form.js#L314-L316

But in `WorkspaceInviteMessagePage`, the `TextInput` element does not have `shouldSaveDraft` props, so the invite message is not preserved.
https://github.com/Expensify/App/blob/754b6edf175a10deb6c6876bdba13c2a99e0ffec/src/pages/workspace/WorkspaceInviteMessagePage.js#L211-L225
### What changes do you think we should make in order to solve the problem?
We should pass `shouldSaveDraft` to `TextInput` component as below.
```js
    <TextInput
        ref={(el) => (this.welcomeMessageInputRef = el)}
        accessibilityRole={CONST.ACCESSIBILITY_ROLE.TEXT}
        inputID="welcomeMessage"
        label={this.props.translate('workspace.inviteMessage.personalMessagePrompt')}
        accessibilityLabel={this.props.translate('workspace.inviteMessage.personalMessagePrompt')}
        autoCompleteType="off"
        autoCorrect={false}
        autoGrowHeight
        textAlignVertical="top"
        containerStyles={[styles.autoGrowHeightMultilineInput]}
        defaultValue={this.state.welcomeNote}
-       value={this.state.welcomeNote}
        onChangeText={(text) => this.setState({welcomeNote: text})}
+       shouldSaveDraft
    />
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by s-alves10** [comment] 2023-07-14 10:12
Looks like a dupe of [20929](https://github.com/Expensify/App/issues/20929)

**Comment by maddylewis** [comment] 2023-07-14 19:51
ah, just saw the dupe message - https://github.com/Expensify/App/issues/22842#issuecomment-1635634028

yep, seems like a duplicate. ill close this one out for now!

**Closed by maddylewis** 2023-07-14 19:51 UTC
Labels: External, Daily, Help Wanted, Bug
