### ISSUE TITLE
[$500]  Chat- User unable to tap header and check details of non existing number

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26878] opened 2023-09-06 14:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap FAB
3. Tap new chat
4. Enter an non existing number
5. Try to tap on header of conversation page to check details of non existing number

## Expected Result:
The user must able to tap header of conversation page and check details of non existing number

## Actual Result:
The user unable to tap header of conversation page and check details of non existing number. The error displays in seconds after user select non existing number.After error closed, concierge page gets opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6ced2e85-6e04-40d9-a8a9-cc0b2dd3d4d8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca96175d6d9865df</li>
        <li>Upwork Job ID: 1699850874581069824</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-09-06 23:26
@lanitochka17 - Are you still able to reproduce this? I have not been able to repro this on a Android/Chrome on a Pixel 6, using staging site.

When I click the header the below is what I see. 

![image](https://github.com/Expensify/App/assets/10925636/f2adcc68-a3df-4b06-8514-82e46a0cf527)

The same thing happens if I enter a phone number instead of an email.

**Comment by lanitochka17** [comment] 2023-09-07 14:37
I am able to reproduce on Build 1.3.65-3
I used phone number +911332276464


https://github.com/Expensify/App/assets/78819774/b263ad82-1324-4e7f-ae84-29447460f53f

**Comment by strepanier03** [comment] 2023-09-07 17:29
Thanks for confirming, I will attempt again.

**Comment by strepanier03** [comment] 2023-09-07 18:23
I was able to recreate with the number provided.

**Comment by strepanier03** [comment] 2023-09-11 12:39
We're waiting for proposals Melvin, we're okay for now.

**Comment by strepanier03** [comment] 2023-09-18 20:37
@0xmiroslav - Aaah okay. I guess thinking about it more it could be expected because it's an invalid number in the first place. 

I'm thinking we should close this, do you agree?

**Comment by strepanier03** [comment] 2023-09-21 01:26
Thanks @0xmiroslav. Closing this.

**Closed by strepanier03** 2023-09-21 01:26 UTC
Labels: External, Daily, Help Wanted, Bug
