### ISSUE TITLE
[$1000] Preview load every time when receive any image

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24517] opened 2023-08-13 21:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. click on FAB icon and select new chat option
2. create a new chat with user
3. send a image to user
4. on receiver side click on image to see preview
5. from sender send a new image
## Expected Result: 
preview loads for a seconds on receive any new image
## Actual Result: 
preview does not load
Platforms: Web
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8f2dd588-de2a-47a7-a4e6-80978d1e7c66

https://github.com/Expensify/App/assets/43996225/b3d2d575-20a7-41cb-8ce1-1f2269d02f1c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691216620506039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010173971d7c24dc56</li>
        <li>Upwork Job ID: 1694035230172463104</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by aditygrg2** [comment] 2023-08-13 21:53
Not reproducible.

**Comment by StevenKKC** [comment] 2023-08-14 08:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Preview load every time when receive any image.

### What is the root cause of that problem?
When the sender sends a new image, on the receiver side, app receives the push event, and then the following code is executed.
Since `initialItem` is an object that contains `file`, `isAuthTokenRequired`, `source` fields, and is created from scratch on every re-render. 
As a result, this dependency are always different on a re-render, and then cause the following effect to re-run.

So `onNavigate` is called, and then `onCarouselAttachmentChange` is called.
Therefore preview load every time when receive image.

### What changes do you think we should make in order to solve the problem?
We can modify `useEffect` dependency to `initialItem.source`.
```js
    useEffect(() => {
        ...
    }, [initialIsActive?.source]);
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by muttmuure** [comment] 2023-08-14 17:12
I'm not sure I understand what the problem is here

**Comment by StevenKKC** [comment] 2023-08-17 21:03
@muttmuure Please check second video. Each time send a new image, preview will be reloaded on the receiver side.

**Comment by muttmuure** [comment] 2023-08-22 17:24
Not overdue

**Comment by muttmuure** [comment] 2023-09-01 22:46
Just waiting for @eVoloshchak to review https://github.com/Expensify/App/issues/24517#issuecomment-1676926310

**Comment by eVoloshchak** [comment] 2023-09-03 21:14
I'm unable to reproduce this (Chrome-Chrome, Chrome-Safari, Chrome-Desktop)
@StevenKKC, could you verify this is still reproducible? Thanks

**Comment by StevenKKC** [comment] 2023-09-04 10:29
@eVoloshchak This is still reproducible. Please see console.
[ice_video_20230904-062507.webm](https://github.com/Expensify/App/assets/131836113/536a5c6f-9745-4dc0-9fa7-7c92bc84f615)

**Comment by StevenKKC** [comment] 2023-09-06 18:24
@eVoloshchak I think this is fixed by https://github.com/Expensify/App/pull/23143

**Comment by eVoloshchak** [comment] 2023-09-08 07:48
@muttmuure, looks like this was fixed by another PR (I'm unable to reproduce this on my end)
If that's the case, I think we should close this

**Comment by mvtglobally** [comment] 2023-09-13 17:18
Issue not reproducible during KI retests. (First week)

**Comment by eVoloshchak** [comment] 2023-09-14 14:20
Not overdue, this was resolved by another PR and isn't reproducible anymore, let's wait for the next week's KI tests and close this one out if nothing changes

**Comment by eVoloshchak** [comment] 2023-09-21 09:40
@mvtgloballym, could you please confirm if this is still reproducible? Thanks!

**Comment by muttmuure** [comment] 2023-09-26 10:13
I will test this tomorrow and close if it's not reproducible anymore

**Comment by mvtglobally** [comment] 2023-09-28 03:12
Issue not reproducible during KI retests. (Second week)

**Comment by eVoloshchak** [comment] 2023-10-02 09:40
Not overdue, this is not reproducible
@muttmuure, I think this one can be closed

**Comment by muttmuure** [comment] 2023-10-04 13:27
Love that energy

**Closed** 2023-10-04 13:27 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
