### ISSUE TITLE
[$250] iOS Hybrid - Composer - Keyboard does not reopen after dismissing the context menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50830] opened 2024-10-15 19:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to DM
3. Send a message
4. With keyboard up, long press on the message
5. Tap outside the context menu

## Expected Result:
The keyboard will reopen after dismissing the context menu (production behavior and staging mweb behavior)

## Actual Result:
The keyboard does not reopen after dismissing the context menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/261b4b34-4ad6-4d0a-9459-c84a777221ae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846522126717879513</li>
        <li>Upwork Job ID: 1846522126717879513</li>
        <li>Last Price Increase: 2024-10-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by marcaaron** [comment] 2024-10-15 20:00
>Reproducible in production?: Y

So, not a blocker right?

**Comment by lanitochka17** [comment] 2024-10-15 21:42
sorry, my mistake.
Reproducible in production?: N

**Comment by rezkiy37** [comment] 2024-10-16 15:39
It is not a bug. This is the expected behavior now. That's a [PR](https://github.com/Expensify/App/pull/48415) where it was changed.

**Comment by rezkiy37** [comment] 2024-10-16 15:44
> @rezkiy37 Should we remove this hook [#50830 (comment)](https://github.com/Expensify/App/issues/50830#issuecomment-2417190014)

Just to clarify: this is the expected result.

> Actual Result:
> The keyboard does not reopen after dismissing the context menu

So I don't think we should touch something. So just close the issue.

**Comment by flodnv** [comment] 2024-10-16 15:53
Thanks for the clarification and details @rezkiy37, I agree with you 👍

**Closed by flodnv** 2024-10-16 15:53 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly
