### ISSUE TITLE
Web - Workspace - Workspace chat doesn't show added member

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12019] opened 2022-10-19 23:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/ and login with any account
2. Create a new workspace
3. Invite 1 more member
4. Refresh the page and observe members in #announce room, and workspace chats

## Expected Result:
I would expect to see 2 members for all workspace chats and #announce room

## Actual Result:
In Workspace chat I see only original member. New member is added only to #announce room, and a chat with this new member is created.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196820397-0a07a260-eff4-40aa-ab97-52d9202abcf5.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment] 2022-10-24 11:47
Reassigning for triage.

**Comment by jliexpensify** [comment] 2022-10-24 21:50
@kbecciv I am unable to reproduce on Staging v1.2.18-9. Admittedly, there's a delay in having the user populate, but a refresh worked: 

![image](https://user-images.githubusercontent.com/30815269/197635706-3a4b9425-02da-4a31-bacc-b73fe6320d9e.png)

I wanted to dig into these behaviours:

> **In Workspace chat I see only original member.** 

I think this is intended? The member should only populate on the LHN if they start a chat with you.

> **New member is added only to #announce room, and a chat with this new member is created.**

This is also intended behaviour: any new user is added to #announce, and only Admins are added to #admins.

So right now, I don't think there's an issue - reassigning this GH back to you, feel free to check with v1.2.18-9 and report back with a new video if you're seeing otherwise.

**Comment by kbecciv** [comment] 2022-10-26 18:08
@jliexpensify Thank you for your explanation, going to check with latest build and update you shortly.

**Comment by jliexpensify** [comment] 2022-10-26 21:32
Hi @kbecciv - you haven't invited that second user as an Admin, right? If not, they will not show up in the #admins room.

They do show up in the #anounce room, which is correct behaviour (everyone who's invited should).

On the new build, the user is also added to the room instantly. So I'm still not seeing the issue - can you reclarify what you think the specific issue is for me?

**Comment by kbecciv** [comment] 2022-10-30 02:30
@jliexpensify Correct, I didn't invite that second user as an Admin.
Thank you for your explanation

**Comment by jliexpensify** [comment] 2022-10-30 23:04
No worries. Lets close this one out, it seems like intended behaviour!

**Closed by jliexpensify** 2022-10-30 23:04 UTC
Labels: Daily, Bug
