### ISSUE TITLE
[HOLD for payment 2022-11-02] [$250] The ‘Multiple users are typing’ vertical text alignment is incorrect

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10486] opened 2022-08-23 05:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open group chat as user A 
2. Type as User B on another device 
3. Observe underlying "typing..." display as User A 
4. Type as User B and User C on 2 different devices simultaneously
5. Observe underlying "typing..." display as User A 

## Expected Result:
Text should be aligned 

## Actual Result:
The ‘Multiple users are typing’ vertical text alignment is incorrect. When a single user is typing the text remains centered, but when multiple users are typing the text becomes uncentered:

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.88-14
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/186073675-03975813-c8ee-42ad-a242-9d17e9a94583.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Julesssss 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660833359041749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2022-08-23 09:12
@robertjchen I'll take this as I'm on the C+ team, and reported the issue.

**Comment by MitchExpensify** [comment] 2022-08-23 20:02
[Upwork Job](https://www.upwork.com/jobs/~01036fc7640bb23216)

**Comment by MitchExpensify** [comment] 2022-09-02 12:40
Not overdue, the PR is being drafted. When do you think it will be ready for review @mdneyazahmad ?

**Comment by Santhosh-Sellavel** [comment] 2022-09-09 19:31
This issue is no longer reproducible in the main @parasharrajat!

**Comment by Santhosh-Sellavel** [comment] 2022-09-09 19:33
Should be resolved this PR https://github.com/Expensify/App/pull/10591

**Comment by Santhosh-Sellavel** [comment] 2022-09-09 20:00
But still, the changes proposed here are worth doing as they are missed out while refactoring is done [here](https://github.com/Expensify/App/pull/10140).

**Comment by Julesssss** [comment] 2022-09-14 11:33
The issue is resolved for me too: 

https://user-images.githubusercontent.com/10736861/190142935-06a425d0-8537-4feb-a8b5-8b26db05fc99.mov


> But still, the changes proposed here are worth doing as they are missed out while refactoring is done [here](https://github.com/Expensify/App/pull/10140).

@Santhosh-Sellavel would you mind reminding me why that is?

**Comment by Santhosh-Sellavel** [comment] 2022-09-14 11:43
@Julesssss 
Ah Sorry, I missed sending this earlier. The issue might still occur in mobile native  &  mWeb apps. 

https://user-images.githubusercontent.com/85645967/190144467-1637a28c-c34f-44e0-a375-8cd0ccc4560a.mov

**Comment by MitchExpensify** [comment] 2022-09-20 22:21
So will @mdneyazahmad 's [PR](https://github.com/Expensify/App/pull/10790) fix all cases? If not, how should we move forward here?

**Comment by Julesssss** [comment] 2022-09-21 09:24
@MitchExpensify yeah, I believe this is a full solution. Hey @mdneyazahmad, are you able to go ahead and submit the PR? Thanks!

**Comment by Julesssss** [comment] 2022-10-04 17:16
It looks like there's an ongoing discussion in the [PR review](https://github.com/Expensify/App/pull/10790).

**Comment by Julesssss** [comment] 2022-10-13 10:17
Hey @mdneyazahmad, there are some outstanding comments in the [PR](https://github.com/Expensify/App/pull/10790#issuecomment-1270563182), are you able to take a look? Thanks!

**Comment by mdneyazahmad** [comment] 2022-10-14 08:10
Sorry for the delay. I will update it sometime today. Thanks!

**Comment by MitchExpensify** [comment] 2022-10-25 00:18
Any update @mdneyazahmad ?

**Comment by mdneyazahmad** [comment] 2022-10-25 04:45
@MitchExpensify PR is deployed on staging https://github.com/Expensify/App/pull/10790#issuecomment-1289804155

**Comment by Julesssss** [comment] 2022-11-02 10:18
Not overdue, awaiting payment

**Comment by Julesssss** [comment] 2022-11-02 10:19
Oh cool, it's the second today. Is that why the label changed priority? 🤯

**Comment by MitchExpensify** [comment] 2022-11-02 23:08
I had to [repost the job](https://www.upwork.com/jobs/~01a945b0d0f6f56057) and have sent you both offers @parasharrajat & @mdneyazahmad. Will pay and close this once accepted! Thank you

**Comment by MitchExpensify** [comment] 2022-11-04 15:47
Paid! Thanks all

**Closed by MitchExpensify** 2022-11-04 15:47 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
