### ISSUE TITLE
Web - "Failed to delete contact method" appears when user remove contact method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34758] opened 2024-01-18 19:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34125

## Action Performed:
1. On staging, enable "Simulate failing network requests" in Settings > Preferences
2. Go to Settings > Profile > Contact method
3. Add a phone number as a new contact method
4. Wait for the pending add operation to fail
5. Once you see the red dot, click on the contact method and clear the error
6. Wait for a while - red dot reappears with new message that user cannot delete contact method

## Expected Result:
The red dot should disappear after the error is cleared and no other error message should appear

## Actual Result:
After a while - "Failed to delete contact method" message appears when user remove the phone number contact method

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/58f485fc-6adc-4c31-9a0a-c6f8c219c159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment] 2024-01-18 20:18
Isn't this just because we are simulating failing network requests, and deleting the contact method is also a network request?

**Comment by dangrous** [comment] 2024-01-18 20:22
I also am unable to reproduce, unless it takes a VERY long time for the second error to show up. I'll ask if anyone else can.

**Comment by dangrous** [comment] 2024-01-18 20:32
@danieldoglas can you take a look at this, coming from https://github.com/Expensify/App/pull/34125 ? I'm still trying to trace back why this is happening (it's also showing both errors, which I think is particularly incorrect), but wanted to ping right away

<img width="393" alt="image" src="https://github.com/Expensify/App/assets/5487802/84c31caf-b9c2-41de-b02a-2117b3335f5c">

**Comment by dangrous** [comment] 2024-01-18 21:11
I think this might be intended behavior, though I'm not entirely clear on why. Like, that deletion error is being sent back appropriately from Auth - it's [this line](https://github.com/Expensify/Auth/blob/ed421357a276a10fe0de45d6eba791e3d43743a5/auth/command/DeleteLogin.cpp#L36), just with `It belongs to accountID: 0` because it doesn't exist at all. My only confusion is whether or not we should be able to see BOTH errors ever, which I would think no?

**Comment by dangrous** [comment] 2024-01-18 21:26
Here are more specific questions, for those investigating:
* The “bug” is that when you click “Remove” on a contact method you just unsuccessfully added, it then calls DeleteContactMethod which, in turn, fails because the contact method was never actually added. This seems bad, but seems intentional based on the code that is there now (both on the front end and in Auth). Maybe it’s just an edge case though, and we should update the front end to just visually remove rather than sending the request to the backend. This is my preferred suggestion, as of now.
* The reproduction steps include turning on “simulate failing network requests” but at least on dev my requests are indeed going to the backend. Why? Does it still send them, it just pretends it doesn’t? I’m not sure that affects the bug, but I’m still confused.
* A second part to this ^ - as noted in a previous comment, shouldn't the DeleteContactMethod request throw an error no matter what since we have simulated failures? Why doesn't that - or the initial request - go red immediately?
* When the second error shows up, it shows the first one again. This seems incorrect, but I'm not clear on why it's happening. This may be the only thing that's actually related to #33021, though I'm not sure. Is this fine, though, since if we fix the removing of the nonexistent contact method, we'll never see this screen?

All in all I'm sort of confused as to which part of this is the actual bug. Hopefully those thoughts help!

**Comment by mountiny** [comment] 2024-01-18 22:04
cc @tienifr @ntdiary to confirm this behaviour

I dont think this has to be blocker as it does not seem worse than before

**Comment by dangrous** [comment] 2024-01-19 16:53
Oh okay - thank you @tienifr for the explanation. So I think... that this isn't a bug, right? Normally, we wouldn't get that second error but we are here because we're simulating failures.

@tienifr can you confirm then that the issue is not with the new code but with the QA tests (by default, we will get an error when we delete the failed contact method)? Is there an alternate set we can use to confirm this is okay on the server?

Thanks!

**Comment by dangrous** [comment] 2024-01-22 16:34
Same! My question is mostly where do we go from here. From that response, it seems like this isn't a bug and we can close. Let me know if you agree!

**Comment by dangrous** [comment] 2024-01-24 20:18
Bumping the above when you have time @tienifr ! Basically:

* Is there a way to test that the changes made in PR https://github.com/Expensify/App/pull/34125 actually fix the original [issue](https://github.com/Expensify/App/issues/33021)?

I'm ready to close this issue but I want to make sure that the PR actually passes QA. Thanks!

**Comment by dangrous** [comment] 2024-01-29 15:42
Going ahead and closing this, commented on the semi-outstanding question here: https://github.com/Expensify/App/issues/33021#issuecomment-1914963914

**Closed by dangrous** 2024-01-29 15:42 UTC
Labels: Engineering, Daily, Overdue
