### ISSUE TITLE
[HOLD for payment 2024-11-01] Unread chats are missing from LHN (left hand navigation)

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#50100] opened 2024-10-02 19:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.42-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** tgolen@expensify.com
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1727795413457949

## Action Performed:
1. Sign into NewDot
2. Make sure you are in focus mode
3. Have some unread chats in your LHN
4. Open the chat finder window (magnifying glass on the top-right of the LHN)

## Expected Result:
The Chat Finder page should not show the hidden chats as bold/unread. The hidden chats should remain invisible in LHN.

## Actual Result:
There are unread chats in the chat finder which don't appear in the LHN

## Workaround:
The workaround is to open the chat finder to locate the unread chats.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/user-attachments/assets/a9ef2fa5-a335-4911-bd12-23ec6d8616d7)
![image](https://github.com/user-attachments/assets/09a0291d-b154-41a7-bef7-22ed315e0d67)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by nkdengineer** [comment] 2024-10-02 19:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There are unread chats in the chat finder which don't appear in the LHN

### What is the root cause of that problem?
The RCA here is the unread chat has `isHidden` is `true` and `shouldOverrideHidden` doesn't cover the case the chat is unread

https://github.com/Expensify/App/blob/f12d016ff0f4d0ab3235f270d26f7a7e61748d7a/src/libs/SidebarUtils.ts#L137-L145
### What changes do you think we should make in order to solve the problem?
We should add the check unread to `shouldOverrideHidden` to avoid hiding the unread chat if we're in focus mode.

```
const shouldOverrideHidden =
  // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
  hasValidDraftComment(report.reportID) ||
  hasErrorsOtherThanFailedReceipt ||
  isFocused ||
  isSystemChat ||
  report.isPinned ||
  isExpenseReportWithoutParentAccess ||
  (ReportUtils.isUnread(report) && isInFocusMode);
```
https://github.com/Expensify/App/blob/f12d016ff0f4d0ab3235f270d26f7a7e61748d7a/src/libs/SidebarUtils.ts#L137-L145

Or if we always want to show the unread chat in LHN we can remove `&& isInFocusMode` in the condition above.
### What alternative solutions did you explore? (Optional)

**Comment by tgolen** [comment] 2024-10-02 20:09
Yeah, we want to be sure unread chats show in either view mode. @nkdengineer Is this a recent regression?

**Comment by mountiny** [comment] 2024-10-03 10:43
I am not sure if the expected scenario here is correct, discussing [here](https://expensify.slack.com/archives/C05LX9D6E07/p1727952174843669?thread_ts=1727795413.457949&cid=C05LX9D6E07)

**Comment by mountiny** [comment] 2024-10-03 13:14
After discussion, I have updated the expected behaviour:

> The Chat Finder page should not show the hidden chats as bold/unread; they should remain invisible in LHN.

@ZhenjaHorbach @nkdengineer can you update the PR to reflect that please?

**Comment by nkdengineer** [comment] 2024-10-03 14:16
@mountiny Thanks for the update, I will update the PR soon.

**Comment by bfitzexpensify** [comment] 2024-11-04 17:16
Offers sent to both @ZhenjaHorbach and @nkdengineer 

@ZhenjaHorbach, please complete the BZ [checklist](https://github.com/Expensify/App/issues/50100#issuecomment-2436678946)

**Comment by nkdengineer** [comment] 2024-11-05 17:50
> @nkdengineer, please accept the offer in Upwork.

@bfitzexpensify Done 👍

**Comment by bfitzexpensify** [comment] 2024-11-05 17:51
Great - payment complete, closing this one out. Thanks everyone!

**Closed by bfitzexpensify** 2024-11-05 17:51 UTC
Labels: External, Daily, Awaiting Payment, Bug
