### ISSUE TITLE
Android - Distance - Scrolling doesn't work when the number of waypoints increases

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27382] opened 2023-09-13 17:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27076
## Action Performed:
1. Login into New Expensify
2. Open Request Money from FAB
3. Choose the Distance tab
4. Add multiple new waypoints by selecting the "Add stop" button
5. Attempt to scroll up

## Expected Result:
User is able to scroll up to input stops

## Actual Result:
User is unbale to scroll up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/aa728ab9-a46d-4257-adcd-31aeaecb2b22

Not reproducible in Production

https://github.com/Expensify/App/assets/78819774/42110250-01bb-4538-9eff-dae3426e87f0

**Expensify/Expensify Issue URL:**

**Issue reported by:** @situchan 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694021625336179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment] 2023-09-13 21:18
Yeah looks like it's almsot certainly tied to https://github.com/Expensify/App/pull/27076 since that modified scrolling for multiple waypoints. 

cc: @jjcoffee @arosiclair

**Comment by NikkiWines** [comment] 2023-09-13 22:39
@arosiclair was able to reproduce this on v1.3.68-17 (yesterday's [deploy](https://github.com/Expensify/App/issues/27210)) so this isn't actually a blocker and https://github.com/Expensify/App/pull/27076 isn't the root cause. 

This isn't a blocker, but will continue to look into to see if we can find the root cause for it.

**Comment by situchan** [comment] 2023-09-14 09:54
@bernhardoj's root cause is correct. It's scrolling limit in android.
`nestedScrollEnabled=true` also seems the only solution unless we prevent scrolling in parent view.

**Comment by NikkiWines** [comment] 2023-09-15 01:10
Ah cool, so it's a regression of https://github.com/Expensify/App/pull/26728? 

@hayata-suenaga tagging you since you're the internal eng/ for that PR, do you want to handle this as a regression or shall we handle this as a separate issue and start looking at proposals?

**Comment by hayata-suenaga** [comment] 2023-09-15 01:47
thank you for letting me know about this issue Nikki

We can actually close this issue as we're making an UI change [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1694741869387169?thread_ts=1694509495.995009&cid=C05DWUDHVK7) and making the waypoint list not scrollable

**Closed by hayata-suenaga** 2023-09-15 01:47 UTC
Labels: Engineering, Daily
