### ISSUE TITLE
[$500] Web - Tricky emoji is displaying as black square and not easy to delete it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31387] opened 2023-11-15 16:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31259

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go to Setting - Workspace
4. With workspace selected go to Settings,
5. Try input with emojis, especially tricky ones (e.g. 😶‍🌫️, 🏴󠁧󠁢󠁥󠁮󠁧󠁿),‍‍

## Expected Result:
Tricky emoji is not displaying as black square

## Actual Result:
Tricky emoji is displaying as black square

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/42787369-b323-4bca-92de-80044426f6d1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017082a343b966e0fd</li>
        <li>Upwork Job ID: 1724830935366795264</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by newtome8888** [comment] 2023-11-15 22:01
### Proposal
---
#### Please re-state the problem that we are trying to solve in this issue.
The emojis, especially 🏴󠁧󠁢󠁥󠁮󠁧󠁿 is displayed as black square in system, this is not correct.
#### What is the root cause of that problem?
The root cause of this problem is the font family ```Windows Segoe UI Emoji```.
#### What changes do you think we should make in order to solve the problem?
Remove ```Windows Segoe UI Emoji``` from font family or replace it with another font will solve this problem. 
#### Result
Effect with ```Windows Segoe UI Emoji``` in font-family:
![withsegoeui](https://github.com/Expensify/App/assets/58249340/9261205f-1931-44f6-8867-3a8b8112abd5)

![withsegoeui_p](https://github.com/Expensify/App/assets/58249340/593649d4-733e-4cea-9cda-36c030eb2703)

Effect without ```Windows Segoe UI Emoji``` in font-family:
![withoutui](https://github.com/Expensify/App/assets/58249340/cf64cf97-ab70-47fd-a799-28fcbf12246e)
![withoutui_p](https://github.com/Expensify/App/assets/58249340/a2983020-f576-41b1-b5b0-3e455b6c0b3a)
#### What alternative solutions did you explore? (Optional)
If the font ```Windows Segoe UI Emoji``` is neccessary and can not be removed or replaced, there is a compromise plan, just remove it from desktop web, because this problem only happens in desk web.

**Comment by newtome8888** [comment] 2023-11-15 22:05
Contributor details
Your Expensify account email: newtome1111@163.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014062a6096bb8dac5

**Comment by s-alves10** [comment] 2023-11-16 00:13
This issue is related to `Windows Segoe UI Emoji` font which was added for Windows.
![image](https://github.com/Expensify/App/assets/126839717/da4394de-513f-4bab-ab29-5151e8035b96)
As you can see, the black square is `🏴󠁧󠁢󠁥󠁮󠁧󠁿` in this font.

I think we can hold this and related issues till we find a suitable font for Windows

**Comment by situchan** [comment] 2023-11-18 03:38
Based on https://github.com/Expensify/App/issues/31393#issuecomment-1817182124, should this be closed too?

**Comment by sophiepintoraetz** [comment] 2023-11-20 00:02
Agreed, @situchan - closing!

**Closed by sophiepintoraetz** 2023-11-20 00:02 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
