### ISSUE TITLE
[HOLD for payment 2023-11-09] [HOLD #16935] [$500] Web - Clicking the back button brings back the workspace settings panel

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28098] opened 2023-09-24 18:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a new account on ND
2. Click on FAB > New workspace
3. Click on members > invite
4. Click outside the panel to close it
5. Click on the browser back button

## Expected Result:
The side panel should not open when clicking back, instead app should load the previous chat page. This behavior is not repeatable unless it is a new account.

## Actual Result:
App opens up the side panel when clicking back.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ed82d110-7f32-4e9a-b20a-08820c2b7f1a

https://github.com/Expensify/App/assets/93399543/0b8641eb-f1e0-4e0b-b1dd-f0383b8d6fb5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695397220000719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebbc655dc38b6b99</li>
        <li>Upwork Job ID: 1706019315934507008</li>
        <li>Last Price Increase: 2023-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26971957</li>
<li>DylanDylann | Contributor | 26971960</li>
<li>Nathan-Mulugeta | Reporter | 26971961</li>
</ul></li>
    </ul>
</details>

**Comment by husnaink93** [comment] 2023-09-24 20:17
Hi,
I have read your issue on Github and am going to share my proposed solution here.

Proposed Solutions:

Back Button Handling:
To mitigate the issue of the side panel appearing when users press the back button, it is imperative to manage the back button event within our application's source code. This necessitates the customization of the event handling mechanism. For Android, this customization is achievable by modifying the behavior encapsulated within the onBackPressed() method, while iOS would require the management of the UINavigationController.

State Management:
A comprehensive review of our application's state management is advisable. By monitoring the state of the side panel and implementing appropriate code, we can ensure that the panel is promptly closed when users engage the back button. Should our application utilize state management libraries such as Redux (in the case of React Native) or Provider (for Flutter), these resources can facilitate the implementation process.

Conditional Rendering:
The side panel's display can be adjusted through conditional rendering. This entails rendering the panel only under circumstances where its presence is warranted, ensuring that it remains hidden when users navigate via the back button or during specific user interactions.

Testing and Debugging:
Rigorous testing of our application is imperative, particularly in scenarios involving back button interactions. The utilization of debugging tools such as Android Studio or Xcode will aid in pinpointing the root cause of the issue and implementing effective solutions.

Regards
Husnain Khalid

**Comment by husnaink93** [comment] 2023-09-24 20:23
Hi,
I have read your issue on Github and am going to share my proposed solution here.

Proposed Solutions:

Back Button Handling:
To mitigate the issue of the side panel appearing when users press the back button, it is imperative to manage the back button event within our application's source code. This necessitates the customization of the event handling mechanism. For Android, this customization is achievable by modifying the behavior encapsulated within the onBackPressed() method, while iOS would require the management of the UINavigationController.

State Management:
A comprehensive review of our application's state management is advisable. By monitoring the state of the side panel and implementing appropriate code, we can ensure that the panel is promptly closed when users engage the back button. Should our application utilize state management libraries such as Redux (in the case of React Native) or Provider (for Flutter), these resources can facilitate the implementation process.

Conditional Rendering:
The side panel's display can be adjusted through conditional rendering. This entails rendering the panel only under circumstances where its presence is warranted, ensuring that it remains hidden when users navigate via the back button or during specific user interactions.

Testing and Debugging:
Rigorous testing of our application is imperative, particularly in scenarios involving back button interactions. The utilization of debugging tools such as Android Studio or Xcode will aid in pinpointing the root cause of the issue and implementing effective solutions.

Regards
Husnain Khalid

Contributor details
Your Expensify account email: <husnaink93@gmail.com>
Upwork Profile Link: <https://www.upwork.com/fl/~01b377e223ad2fe325>

**Comment by husnaink93** [comment] 2023-09-24 20:26
Hi,
I have read your issue on Github and am going to share my proposed solution here.

Proposed Solutions:

Back Button Handling:
To mitigate the issue of the side panel appearing when users press the back button, it is imperative to manage the back button event within our application's source code. This necessitates the customization of the event handling mechanism. For Android, this customization is achievable by modifying the behavior encapsulated within the onBackPressed() method, while iOS would require the management of the UINavigationController.

State Management:
A comprehensive review of our application's state management is advisable. By monitoring the state of the side panel and implementing appropriate code, we can ensure that the panel is promptly closed when users engage the back button. Should our application utilize state management libraries such as Redux (in the case of React Native) or Provider (for Flutter), these resources can facilitate the implementation process.

Conditional Rendering:
The side panel's display can be adjusted through conditional rendering. This entails rendering the panel only under circumstances where its presence is warranted, ensuring that it remains hidden when users navigate via the back button or during specific user interactions.

Testing and Debugging:
Rigorous testing of our application is imperative, particularly in scenarios involving back button interactions. The utilization of debugging tools such as Android Studio or Xcode will aid in pinpointing the root cause of the issue and implementing effective solutions.

Regards
Husnain Khalid

Contributor details
Your Expensify account email: <husnaink93@gmail.com@expensify.com>
Upwork Profile Link: <https://www.upwork.com/fl/~01b377e223ad2fe325>

**Comment by husnaink93** [comment] 2023-09-24 20:47
Contributor details
Your Expensify account email: ***@***.***
Upwork Profile link: https://www.upwork.com/fl/husnainkhalid8

**Comment by RichardPickman** [comment] 2023-09-24 21:15
> Hi, I have read your issue on Github and am going to share my proposed solution here. Proposed Solutions: Back Button Handling: To mitigate the issue of the side panel appearing when users press the back button, it is imperative to manage the back button event within our application's source code. This necessitates the customization of the event handling mechanism. For Android, this customization is achievable by modifying the behavior encapsulated within the onBackPressed() method, while iOS would require the management of the UINavigationController. State Management: A comprehensive review of our application's state management is advisable. By monitoring the state of the side panel and implementing appropriate code, we can ensure that the panel is promptly closed when users engage the back button. Should our application utilize state management libraries such as Redux (in the case of React Native) or Provider (for Flutter), these resources can facilitate the implementation process. Conditional Rendering: The side panel's display can be adjusted through conditional rendering. This entails rendering the panel only under circumstances where its presence is warranted, ensuring that it remains hidden when users navigate via the back button or during specific user interactions. Testing and Debugging: Rigorous testing of our application is imperative, particularly in scenarios involving back button interactions. The utilization of debugging tools such as Android Studio or Xcode will aid in pinpointing the root cause of the issue and implementing effective solutions. Regards Husnain Khalid Contributor details Your Expensify account email: husnaink93@gmail.com Upwork Profile Link: https://www.upwork.com/fl/husnainkhalid8

I suggest you to push Contributor details as new message, for bot to be able to parse it correctly :)

**Comment by HardikChoudhary24** [comment] 2023-09-24 22:12
### Proposal
### Please re-state the problem that we are trying to solve in this issue
- Clicking the back button brings back the workspace settings panel.

## What is the root cause of that problem?

- The root cause of this issue lies within the WorkspaceInitialPage Component. The problem stems from the absence of ```Navigation.goBack(ROUTES.HOME);``` before ```Navigation.navigate(ROUTES.getWorkspaceMembersRoute(policy.id));``` because we must call goBack() to remove the /transition route from history .
 
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/workspace/WorkspaceInitialPage.js#L152-L152

### What changes do you think we should make in order to solve the problem?

- To address this problem, we can resolve it by simply adding ```Navigation.goBack(ROUTES.HOME);``` before ```Navigation.navigate(ROUTES.getWorkspaceMembersRoute(policy.id));```

**What alternative solutions did you explore? (Optional)**
N/A

## Result


https://github.com/Expensify/App/assets/126149345/0f95dc2c-c448-448e-8311-c2c972267218

**Comment by abzokhattab** [comment] 2023-09-24 23:23
I have a question: 

shouldn't the `/workspace/:id/invite` route be the expected behavior on clicking back? because it's actually the last viewed page, not the workspace settings nor the last chat

**Comment by joekaufmanexpensify** [comment] 2023-09-25 01:56
@dylanexpensify Going to unassign here as I was the duplicate assignee, and this doesn't need two BZ assignees. LMK if there's anything I can help with though!

**Comment by carlitose** [comment] 2023-09-25 10:34
# Improved Proposal

Subject: **Proposed Solutions for Back Button and Side Panel Issue**

Body:

Dear Team,

I have thoroughly reviewed the issue reported on Github regarding the unexpected appearance of the side panel when users press the back button. Here, I present a comprehensive approach to address this concern.

**1. Back Button Event Handling:**

To prevent the side panel from appearing upon pressing the back button, we need to customize the back button event within our application's source code. For Android, we can modify the behavior within the `onBackPressed()` method. For iOS, we will need to manage the `UINavigationController`.

**2. State Management:**

It is crucial to review and manage the state of our application, specifically the state of the side panel. By implementing code that closes the panel when the back button is pressed, we can ensure a smoother user experience. If our application leverages state management libraries like Redux (for React Native) or Provider (for Flutter), these tools can simplify the process.

**3. Conditional Rendering:**

We can control the side panel's visibility using conditional rendering, rendering the panel only when necessary. This approach ensures that the panel remains hidden when users navigate using the back button or during specific user interactions.

**4. Testing and Debugging:**

Thorough testing of the application is essential, especially in scenarios involving back button interactions. Debugging tools such as Android Studio or Xcode can help identify the root cause of the issue and facilitate the implementation of effective solutions.

I hope these proposed solutions provide a clear path forward to address the issue. I look forward to your feedback.

Contributor details
Your Expensify account email: carlog.sergi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b0d12422bbdbf2d3

**Comment by DylanDylann** [comment] 2023-09-26 19:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web - Clicking the back button brings back the workspace settings panel

### What is the root cause of that problem?
- Currently, in the list workspace screen, clicking on "New workspace" button will:
run createWorkspaceAndNavigateToIt function:
https://github.com/Expensify/App/blob/cfad43ff96f2a104c51fd475e07f0980c4379fcd/src/libs/actions/App.js#L317-L334
**Phase 1**. In the case of this bug, it will PUSH a new report screen (#admin report) to the stack.
**Phase 2**. Then PUSH another RIGHT_MODAL_NAVIGATOR screen to the stack. The stack can be describe like [...RIGHT_MODAL_NAVIGATOR, CENTRAL_PANE_NAVIGATOR, RIGHT_MODAL_NAVIGATOR]
- So when the user clicks outside panel to close the RIGHT_MODAL_NAVIGATOR screen, it just removes the 2nd RIGHT_MODAL_NAVIGATOR screen and navigates to #admin report. Then if clicking the back button, it will navigate to RIGHT_MODAL_NAVIGATOR 

### What changes do you think we should make in order to solve the problem?
- In **Phase 1**, we can make sure that the current RIGHT_MODAL_NAVIGATOR screen is REPLACE by report screen, rather than PUSH a new report screen to the stack by using Navigation.dismissModal function:
```
function createWorkspaceAndNavigateToIt(policyOwnerEmail = '', makeMeAdmin = false, policyName = '', transitionFromOldDot = false, shouldNavigateToAdminChat = true) {
    const policyID = Policy.generatePolicyID();
    const adminsChatReportID = Policy.createWorkspace(policyOwnerEmail, makeMeAdmin, policyName, policyID);
    Navigation.isNavigationReady()
        .then(() => {
            if (transitionFromOldDot) {
                // We must call goBack() to remove the /transition route from history
                Navigation.goBack(ROUTES.HOME);
            }

            if (shouldNavigateToAdminChat) {
                Navigation.dismissModal(adminsChatReportID);
            }
        })
        .then(() => {
            return Navigation.isNavigationReady();
        })
        .then(() => {
            Navigation.navigate(ROUTES.WORKSPACE_INITIAL.getRoute(policyID));
        })
        .then(endSignOnTransition);
}
```

### What alternative solutions did you explore? (Optional)
- NA

### Result

[Screencast from 27-09-2023 02:32:03.webm](https://github.com/Expensify/App/assets/141406735/480e2c9d-96b0-40be-89ee-e0b30c8cfd49)

**Comment by dylanexpensify** [comment] 2023-09-27 08:33
reviewing

**Comment by danieldoglas** [comment] 2023-10-02 02:33
@DylanDylann assigned

**Comment by DylanDylann** [comment] 2023-10-02 08:09
@fedirjh PR https://github.com/Expensify/App/pull/28573 is ready for review

**Comment by dylanexpensify** [comment] 2023-10-02 14:15
NICE @fedirjh let's review asap!

**Comment by DylanDylann** [comment] 2023-10-05 02:55
Currently, after clicking on "New workspace", and then pressing the back button in browser,  it not only navigates back to the workspaces list but also replaces the admin report by the concierge report.

[Screencast from 05-10-2023 09:53:20.webm](https://github.com/Expensify/App/assets/141406735/93141eef-eb7c-4b94-9276-d1eaa3a204ec)
I think it is a bug. So what is the expected behavior? @danieldoglas please help check when you have a chance. Thanks

**Comment by danieldoglas** [comment] 2023-10-05 10:06
I think it should go back to the workspace list, but not change the report that is currently being shown in the background @DylanDylann

**Comment by dylanexpensify** [comment] 2023-10-10 11:04
agree - have we factored this into the solution @DylanDylann? 🙇‍♂️

**Comment by DylanDylann** [comment] 2023-10-10 11:06
This issue will be hold for https://github.com/Expensify/App/pull/28573#discussion_r1348966939 @dylanexpensify

**Comment by dylanexpensify** [comment] 2023-10-24 22:52
still on hold

**Comment by dylanexpensify** [comment] 2023-10-30 11:54
hold

**Comment by DylanDylann** [comment] 2023-10-30 11:56
@dylanexpensify this PR https://github.com/Expensify/App/pull/28573 is just merged

**Comment by dylanexpensify** [comment] 2023-11-07 10:15
payment upcoming!

**Comment by danieldoglas** [comment] 2023-11-10 16:14
bump @dylanexpensify

**Comment by dylanexpensify** [comment] 2023-11-14 09:59
Payment summary:

- Reporter: @nathan-mulugeta $50
- Contributor: @DylanDylann $750
- Contributor+: @fedirjh $750

Upwork offers sent! Please accept or request in NewDot!

**Comment by dylanexpensify** [comment] 2023-11-14 10:01
Payments sent!

**Comment by dylanexpensify** [comment] 2023-11-14 10:02
done!

**Closed by dylanexpensify** 2023-11-14 10:02 UTC
Labels: External, Daily, Awaiting Payment, Bug
