### ISSUE TITLE
[HOLD for payment 2023-10-18] [HOLD] [$500] iOS - App crashes on accessing the Date of Birth page in Spanish language

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28315] opened 2023-09-27 12:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND iOS app and navigates to Settings -> Preferences -> Language and Select Spanish
2. Navigate back to Settings -> Profile -> Personal details
3. Click on "Data of birth" view

## Expected Result:
App should open DoB page on click

## Actual Result:
App crashes on click

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1c260031-3c00-4562-b36b-26eb6fb99292

https://github.com/Expensify/App/assets/78819774/c8f09261-4760-441e-97cb-e4a96838a37a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ufumerfarooq

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695668752619709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010dec7e5c136a9983</li>
        <li>Upwork Job ID: 1707015729352577024</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-27 13:11
I think a similar issue is fixed here https://github.com/Expensify/App/issues/26719, and this also should be fixed.

**Comment by ufumerfarooq** [comment] 2023-09-27 13:38
@ahmedGaber93 this issue has been fixed in v1.3.68-17 and I tested this on v1.3.73-1 and it's still reproducible on v1.3.74-0

**Comment by pradeepmdk** [comment] 2023-09-27 14:33
I think we need to wait this pr merge https://github.com/Expensify/App/pull/28175

**Comment by situchan** [comment] 2023-09-27 18:28
We are not keeping moment js in datepicker. Context - https://github.com/Expensify/App/pull/28175#issuecomment-1737880497.
So it makes sense to put this on hold until https://github.com/Expensify/App/issues/19810 is fully done.

**Comment by miljakljajic** [comment] 2023-10-04 09:33
Putting on hold for now

**Comment by miljakljajic** [comment] 2023-10-20 09:12
Looking back it seems like this issue is a duplicate of https://github.com/Expensify/App/issues/26719 given that the app is crashing upon trying to open the date. Going to close.

**Closed by miljakljajic** 2023-10-20 09:12 UTC
Labels: External, Daily, Help Wanted, Overdue, Awaiting Payment, Bug

**Comment by situchan** [comment] 2023-11-26 20:26
@mountiny are we eligible for compensation here based on [This caused a regression but it was found after 7 days it was deployed to production](https://github.com/Expensify/App/issues/19810#issuecomment-1826883626)?
We fixed crash in https://github.com/Expensify/App/issues/26719 but https://github.com/Expensify/App/pull/26248 (we never involved in this PR) caused regression. So we had to re-fix in https://github.com/Expensify/App/pull/28948.
There was no compensation here only because the contributors were same working on 2 PRs.
