### ISSUE TITLE
[$250] Log in - App continues on Account settings page instead of Inbox after log out and log in

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50550] opened 2024-10-10 10:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.47-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh0710001@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in if not logged in.
3. Go to Account settings.
4. Click Sign out.
5. Log in again.

## Expected Result:
App will open Inbox after login.

## Actual Result:
App continues on Account settings page after log out and log in.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8732d366-cb75-47ec-9525-6e434e43c327
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844414446090910816</li>
        <li>Upwork Job ID: 1844414446090910816</li>
        <li>Last Price Increase: 2024-10-10</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2024-10-10 16:01
@MariaHCD would you consider this a deploy blocker? I think we should fix this asap but I don't think this preventing anyone from using the app etc.

**Comment by MariaHCD** [comment] 2024-10-10 16:24
I don't think needs needs to block either the API or the App deploy

**Comment by nafey7** [comment] 2024-10-10 20:05
Try clearing any cache, local storage items, and cookie data and see if the issue is persisting

**Comment by huult** [comment] 2024-10-11 02:56
I can't reproduce this issue on the latest main and staging

**Comment by MariaHCD** [comment] 2024-10-11 08:12
I am also not able to reproduce the behavior on staging. It was reproducible yesterday so perhaps another PR was deployed that fixed this.

@IuliiaHerets could you please retest this?

**Comment by IuliiaHerets** [comment] 2024-10-12 15:37
@MariaHCD Issue was fixed, not repro now 

https://github.com/user-attachments/assets/3953327a-c5d4-4c7e-958c-300c3fac4435

**Comment by adelekennedy** [comment] 2024-10-14 02:25
let's close this!

**Closed by adelekennedy** 2024-10-14 02:25 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
