### ISSUE TITLE
[HOLD for payment 2024-04-15] [$250] Taxes - Transaction thread shows skeleton loading when saving 0.00 tax amount for second time

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39701] opened 2024-04-05 11:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-8
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/33927
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is an employee of Collect workspace with tax rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a manual request with tax exempt (0%).
4. Go to transaction thread.
5. Click Tax amount.
6. Save it without entering any amount.
7. Repeat Step 5 and 6.

## Expected Result:
In Step 6, when saving 0.00 tax amount, the system message will not show $NaN amount,
In Step 7, when saving 0.00 tax amount for the second time, the app will not show skeleton loading.

## Actual Result:
In Step 6, $NaN is shown briefly in the system message.
In Step 7, transaction thread shows skeleton loading when saving 0.00 tax amount for second time.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c58d0b72-1f8d-46ea-b178-d5b0d89acf0d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01091a68b65c340a6a</li>
        <li>Upwork Job ID: 1776234872385998848</li>
        <li>Last Price Increase: 2024-04-05</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-05 11:57
@bfitzexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-05 11:57
We think this issue might be related to the #collect project.

**Comment by MonilBhavsar** [comment] 2024-04-05 12:53
Looking here...

**Comment by MonilBhavsar** [comment] 2024-04-05 13:06
Making it external to see if anyone has proposals as I am close to log off

**Comment by nkdengineer** [comment] 2024-04-05 13:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 6, $NaN is shown briefly in the system message.
In Step 7, transaction thread shows skeleton loading when saving 0.00 tax amount for second time.

### What is the root cause of that problem?
When we try to save the tax amount while entering nothing, it's still saving the empty value (which is converted to `NaN`)

### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/App/blob/2995f2c79751d5096919eb98a26e0bd7b8533658/src/pages/EditRequestPage.js#L126), when we try to save the tax amount while entering nothing, early return since the user didn't set any tax
```
if ((transactionChanges.amount ?? '') === '') {
    return;
}
```


### What alternative solutions did you explore? (Optional)
NA

**Comment by MonilBhavsar** [comment] 2024-04-05 13:16
> When we try to save the tax amount while entering nothing, it's still saving the empty value

Should we not allow saving empty value at the first place?

**Comment by nkdengineer** [comment] 2024-04-05 13:18
@MonilBhavsar You mean to show an error like `Please enter a valid amount before continuing.` right? We can do  that (similar to the request amount page)

**Comment by nkdengineer** [comment] 2024-04-05 13:18
But it will look like the tax amount is a required thing, it might confuse the users. In my proposal, the UX will be, we still dismiss the modal but we'll not save anything.

**Comment by nkdengineer** [comment] 2024-04-05 13:31
[Proposal updated](https://github.com/Expensify/App/issues/39701#issuecomment-2039775225) will alternative solution that will show an error if the tax amount is empty.

@MonilBhavsar Let me know if that looks good 👍

**Comment by MonilBhavsar** [comment] 2024-04-05 13:35
Looks good!

One thing I noticed while reviewing. If zero is entered we don't display zero, but a placeholder. Do you want to fix it too?

<img width="987" alt="Screenshot 2024-04-05 at 7 04 20 PM" src="https://github.com/Expensify/App/assets/32012005/d0714224-eb0b-4dca-a56d-47a0a46b1c3e">

**Comment by MonilBhavsar** [comment] 2024-04-05 13:36
And would you be please able to prioritize PR, given it is a deploy blocker?

**Comment by nkdengineer** [comment] 2024-04-05 13:38
> And would you be please able to prioritize PR

@MonilBhavsar Yes I can

> One thing I noticed while reviewing. If zero is entered we don't display zero, but a placeholder. Do you want to fix it too?

Sure, just noticed that too

**Comment by MonilBhavsar** [comment] 2024-04-05 13:40
@DylanDylann I'm going to take care of this

**Comment by nkdengineer** [comment] 2024-04-05 13:49
> One thing I noticed while reviewing. If zero is entered we don't display zero, but a placeholder. Do you want to fix it too?

@MonilBhavsar This issue was supposed to be fixed by https://github.com/Expensify/App/pull/35797, but that PR [was reverted](https://github.com/Expensify/App/pull/39610). A new PR will be raised soon to fix it properly, so I think we should not fix it in our PR because it might conflict with what they're doing.

What do you think?

**Comment by MonilBhavsar** [comment] 2024-04-05 13:53
Okay fine with that. Thanks for looking

**Comment by nkdengineer** [comment] 2024-04-05 13:56
Thanks, I'm working on the PR now, will raise in a bit

**Comment by cristipaval** [comment] 2024-04-05 14:30
Thanks for jumping into this one, @MonilBhavsar

**Comment by nkdengineer** [comment] 2024-04-05 14:30
@MonilBhavsar The PR is ready.

**Comment by bfitzexpensify** [comment] 2024-04-16 13:43
I don't think a specific regression test is needed for this - it should be caught in regular tax testing. 

Payment complete, so closing this one out.

**Closed by bfitzexpensify** 2024-04-16 13:43 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by nkdengineer** [comment] 2024-07-01 11:53
Sorry @bfitzexpensify It seems I wasn't paid here, could you reopen the issue to help with this?

TIA

**Comment by bfitzexpensify** [comment] 2024-07-01 12:06
@nkdengineer this one was paid on April 16th - title for the Upwork job was _Reviewer - [$250] Taxes - Transaction thread shows skeleton loading when saving 0.00 tax amount for second time_
