### ISSUE TITLE
Web - Chat - User received a push notification twice

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18971] opened 2023-05-15 19:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in with account A.
2. Sign into account B on another device, making sure both devices remain active with the app open.
3. Send a message from A to B.
4. Verify that B receives the message from A.

## Expected Result:
User received a push notification once

## Actual Result:
User received a push notification twice

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.14.6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/00043923-f360-4c59-90ac-dd887b05aa6a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment] 2023-05-16 01:43
JLi and I swapped issues since I can more easily test iOS issues.

**Comment by jliexpensify** [comment] 2023-05-16 01:50
I can't actually repro this one on Mac + Chrome. @kbecciv can you test on v1.3.14-6 and re-open if this is still an issue?

**Comment by kbecciv** [comment] 2023-05-16 02:02
Can you try on Windows/Chrome?

**Comment by jliexpensify** [comment] 2023-05-16 02:05
@kbecciv but where is this actually occurring? You haven't marked off any of the checklist.

**Comment by jliexpensify** [comment] 2023-05-16 02:11
Re-opening as @kadiealexander can replicate this on v1.3.14-6 (not sure why I can't?)

![image](https://github.com/Expensify/App/assets/30815269/edec65ce-646e-4b58-a879-70a0b63de64d)

**Comment by conorpendergrast** [comment] 2023-05-16 13:19
I'm going to close this as a dupe of https://github.com/Expensify/App/issues/18887

**Closed by conorpendergrast** 2023-05-16 13:19 UTC
Labels: Daily, Bug
