### ISSUE TITLE
[HOLD for payment 2024-01-04] [$500] Android - Chat - Message gets displayed from right to left

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30584] opened 2023-10-30 14:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30521
## Action Performed:
1. Launch App
2. Open any chat and paste an RTL text in the compose box, for example " مثال "
3. Continue typing some content

## Expected Result:
Verify that the content gets displayed from left to right

## Actual Result:
The content gets displayed from right to left

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 
![Bug6256757_1698673344323!30521_Android](https://github.com/Expensify/App/assets/78819774/1475c32b-36ad-4bb3-b3ed-10cc860f8496)

https://github.com/Expensify/App/assets/78819774/d7ac6f63-be15-4b10-9a4b-58e66b55d53a

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01278feafdf81fcb73</li>
        <li>Upwork Job ID: 1718998877593833472</li>
        <li>Last Price Increase: 2023-11-20</li>
<li>Automatic offers: </li>
<ul>
<li>samilabud | Contributor | 27900958</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by situchan** [comment] 2023-10-30 14:42
cc: @HardikChoudhary24

**Comment by samilabud** [comment] 2023-10-30 15:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN - Created Split Bill Group chat in offline displays in bottom in LHN

### What is the root cause of that problem?
The root cause is that Android only converts RTL text to LTR text using Unicode controls and by default, when you start writing in a language that is written in RTL mode it converts the input text to RTL.

### What changes do you think we should make in order to solve the problem?
The best solution is to add \u2066 unicode character before starting to write, I suggest modifying the next function (`updateComment`):

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L213

Adding something like:
```
let newCommentConverted = '';
if (!!newComment.match(/^(\s)*$/)) {
       newCommentConverted += '\u2066';
}
newCommentConverted += convertToLTRForComposer(newComment);
```

This is the result:

https://github.com/Expensify/App/assets/5216036/28ac3290-b0f9-4ec2-95b1-6e6955dbe016

**Comment by samilabud** [comment] 2023-10-30 20:23
## Proposal
[Updated](https://github.com/Expensify/App/issues/30584#issuecomment-1785494092)

**Comment by johncschuster** [comment] 2023-11-02 20:34
@allroundexperts can you take a look at the updated proposal above when you get a moment?

**Comment by fabriziobertoglio1987** [comment] 2023-11-09 01:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The text is displayed right to left. 

### What is the root cause of that problem?

The ReactRoot view default textDirection is `firstStrong` ([screenshot1](https://user-images.githubusercontent.com/24992535/281588775-41fb635c-c3d1-4c6b-a007-e9caa16a7444.png), [screenshot2](https://user-images.githubusercontent.com/24992535/281583961-7826db4c-8a1d-49ef-89d1-78924e36fbff.png))

https://developer.android.com/reference/android/view/View.html#attr_android:textDirection
```
firstStrong
Default for the root view. The first strong directional character determines the paragraph direction. 
If there is no strong directional character, the paragraph direction is the view\u2019s resolved layout direction.
```

- The text `مثالa` displays as left-to-right
- The text `aمثال` displays as right-to-left

#### Testing textDirection: firstStrong and textDirection: ltr on Android

https://developer.android.com/reference/android/view/View.html#attr_android:textDirection

https://github.com/fabriziobertoglio1987/text-input-cursor-flickering-android/blob/31db5796c6abbd17ffaa87de1663c38604d1da33/app/src/main/java/com/example/javaexample/CustomEditText.java#L29-L43

| TextDirection firstStrong | TextDirection ltr |
| ----------- | ----------- |
| <image src="https://user-images.githubusercontent.com/24992535/281586494-390ef2cd-78b9-44e5-8eda-4300c2d26767.png" width="350" />      | <image src="https://user-images.githubusercontent.com/24992535/281586783-c0e5d836-e6ed-4863-935e-599856db9d43.png" width="350" />       |

### What changes do you think we should make in order to solve the problem?

Expose textDirection style prop in the React Native API to allow changing the Views (View, TextInput, Text) textDirection.

1) Add a JavaScript textDirection style prop to the React Native API:

```
<View style={{textDirection: "ltr"}}>
   <TextInput style={{textDirection: "inherit"}}>The TextInput inherits the style from the parent</TextInput>
   <TextInput style={{textDirection: "firstStrong"}}>The TextInput content aligns based on the first character content</TextInput>
</View>
```

2) Set the `textDirection` of the Android View using setTextDirection ([android code snippet](https://github.com/fabriziobertoglio1987/text-input-cursor-flickering-android/blob/31db5796c6abbd17ffaa87de1663c38604d1da33/app/src/main/java/com/example/javaexample/CustomEditText.java#L29-L43)).

**Comment by samilabud** [comment] 2023-11-10 15:27
@HardikChoudhary24, we are adding the Unicode \u2066` when we send the message, my proposal is to add it before starting to write and when the user is using Android.

Please see how it looks in Android:
https://github.com/Expensify/App/assets/5216036/1b3b1a36-a98a-4086-b9f6-7d8e9961719a

**Comment by samilabud** [comment] 2023-11-12 22:33
> @samilabud Why doesn't the message show up in the chat once you send it in the above video?

Oh that's was for my connection (was slow) and here the video should be max 10mb 😅, but I can share another video if you want.

**Comment by samilabud** [comment] 2023-11-13 16:25
> > @HardikChoudhary24, we are adding the Unicode `\u2066` when we send the message, my proposal is to add it before starting to write and when the user is using Android.
> > Please see how it looks in Android:
> > Android.chat.messgage.gets.displayed.from.right.to.left.done.mov
> 
> Yes that is what we are doing using the `convertToLTRForComposer` function. We are not adding it when we send the message, we add it as we start to write.

As far as I can see we are using this function to do what you say:
https://github.com/Expensify/App/blob/0d048314505f20f1c77c3d27ba3845f566943ddb/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L230

But this function for Android returns the same text `(text) => text`:

https://github.com/Expensify/App/blob/0d048314505f20f1c77c3d27ba3845f566943ddb/src/libs/convertToLTRForComposer/index.android.ts#L7

Perhaps the confusion is because there is another function with a similar name that does what you say, which is this one:
https://github.com/Expensify/App/blob/main/src/libs/convertToLTR/index.android.ts

**Comment by samilabud** [comment] 2023-11-17 21:57
> > @HardikChoudhary24, we are adding the Unicode `\u2066` when we send the message, my proposal is to add it before starting to write and when the user is using Android.
> > Please see how it looks in Android:
> > Android.chat.messgage.gets.displayed.from.right.to.left.done.mov
> 
> Yes that is what we are doing using the `convertToLTRForComposer` function. We are not adding it when we send the message, we add it as we start to write.

Sorry I was looking at your PR, specifically this [commit](https://github.com/Expensify/App/pull/29434/commits/1dd55f164afdd774b36031d472b5c5916b5a4ef0), and it looks like when the user is using Android it does nothing:
 
<img width="888" alt="image" src="https://github.com/Expensify/App/assets/5216036/5b20780a-f4d5-4158-ae5c-c146a7265247">

(This remains the same in the main branch)

**Comment by johncschuster** [comment] 2023-11-22 22:15
@allroundexperts what are your thoughts after reviewing the discussion @HardikChoudhary24 linked to in [this comment](https://github.com/Expensify/App/issues/30584#issuecomment-1809708599)?

**Comment by allroundexperts** [comment] 2023-11-26 20:23
Okay. It seems like @samilabud's [proposal](https://github.com/Expensify/App/issues/30584#issuecomment-1785494092) works well unlike what @HardikChoudhary24 showed in there [video](https://github.com/Expensify/App/issues/30584#issuecomment-1805859813). Let's proceed with @samilabud's [proposal](https://github.com/Expensify/App/issues/30584#issuecomment-1785494092)!

🎀 👀 🎀 C+ reviewed

**Comment by samilabud** [comment] 2023-11-30 15:50
> @samilabud Are you working on a PR for this?

Not yet, can I start? I have not received an offer yet

**Comment by tgolen** [comment] 2023-11-30 17:53
Oh, you're right. Strange... I will try to reassign you and see if maybe the automation is broken

**Comment by tgolen** [comment] 2023-11-30 17:54
There we go. It was because of the `Internal` label and not `External`.

**Comment by samilabud** [comment] 2023-11-30 17:56
> There we go. It was because of the `Internal` label and not `External`.

Got it thanks 👍

**Comment by johncschuster** [comment] 2023-12-15 22:17
I will be OOO starting Monday, December 18, and will return Tuesday, January 2.

**Current status:** 
There's a PR out, but we're working through a few things.

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by tgolen** [comment] 2023-12-21 15:25
We are still trying to wrap up the PR for this.

**Comment by CortneyOfstad** [comment] 2023-12-22 14:33
Sounds good — I will be OoO next week, so if something needs to be tackled ASAP, feel free to reapply the Bug label. Otherwise I will wrap it up when I am back

**Comment by tgolen** [comment] 2023-12-26 16:06
PR was merged today.

**Comment by situchan** [comment] 2023-12-27 21:53
[PR](https://github.com/Expensify/App/pull/32297) fixing this issue caused [regression](https://github.com/Expensify/App/issues/33675)

**Comment by samilabud** [comment] 2023-12-28 18:37
PR with issue fixed: https://github.com/Expensify/App/pull/33721

**Comment by johncschuster** [comment] 2024-01-05 01:35
# Payment Summary:
@samilabud - $500 - paid via [Upwork](https://www.upwork.com/nx/wm/offer/27900958) (Contributor)
@allroundexperts - $500 - requires payment through NewDot Manual Requests

**Comment by situchan** [comment] 2024-01-05 03:00
Original [PR](https://github.com/Expensify/App/pull/32297) was reverted due to [regression](https://github.com/Expensify/App/issues/33675) and 2nd [PR](https://github.com/Expensify/App/pull/33721) is still in review

**Comment by johncschuster** [comment] 2024-01-09 21:41
Sorry I missed that, @situchan. Thanks for raising the PR under review!

**Comment by johncschuster** [comment] 2024-01-18 22:36
PR to fix the regression is still under review

**Comment by tgolen** [comment] 2024-01-29 15:54
[Regression fix PR](https://github.com/Expensify/App/pull/33721) is still under review.

**Comment by johncschuster** [comment] 2024-02-06 22:55
^Same

**Comment by johncschuster** [comment] 2024-02-27 20:33
Thanks for doing that, @tgolen! It hadn't occurred to me to bump the PR. I'll do that myself going forward.

**Comment by tgolen** [comment] 2024-02-28 02:25
Sounds good! Yep, commenting on the PRs as the BZ person to try and figure out what's going on is always fair game. Hopefully, we will get a response. Next step if we don't is to ping them on Slack or NewDot and try to get a response directly.

**Comment by allroundexperts** [comment] 2024-03-01 07:02
@tgolen This was being discussed internally [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1702050663068809). I think we need to think of a new solution or just do nothing here.

**Comment by tgolen** [comment] 2024-03-04 16:12
@allroundexperts thanks for the reminder about that thread. I think it's probably best to close this for now until we decide we want to have full support for RTL languages. There would be a whole host of things we would need to consider such as:

- Message alignment
- UI alignment
- Window positioning (like modals)

I will go ahead and close this for now.

**Closed by tgolen** 2024-03-04 16:12 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
