### ISSUE TITLE
[HOLD for #318] [$250] iOS - Single emoji is not enlarged on iOS

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41390] opened 2024-05-01 07:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to chat.
3. Open emoji picker,
4. Insert one emoji.

## Expected Result:
The emoji will appear enlarged when only emoji is present in the composer.

## Actual Result:
The emoji is not larged and there is an empty line above it. It only is enlarged when the space behind the emoji is removed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f355fff5-d2cf-4fa0-b125-4c086abb2485

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e913a46985dfa7d8</li>
        <li>Upwork Job ID: 1788661557931286528</li>
        <li>Last Price Increase: 2024-05-09</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by izarutskaya** [comment] 2024-05-01 07:51
@Christinadobrzyn I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-01 07:51
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-05-01 07:52
Production 


https://github.com/Expensify/App/assets/115492554/c3247b99-b3be-4994-b0d1-50a928eb5b31

**Comment by francoisl** [comment] 2024-05-01 18:53
I wonder if it comes from #40617 - testing an ad-hoc build of a revert in [here](https://github.com/Expensify/App/pull/41437).

**Comment by youssef-lr** [comment] 2024-05-01 21:39
Tested the PR and can still reproduce. Checking other suspicious PRs now.

**Comment by youssef-lr** [comment] 2024-05-01 22:06
@robertKozik @Ollyws this [PR](https://github.com/Expensify/App/pull/41027) has caused this issue, can you guys take a look please?

**Comment by francoisl** [comment] 2024-05-01 22:08
Looks like there was also an issue on web reported in [this comment](https://github.com/Expensify/App/pull/41027#issuecomment-2088797788) for that PR. No need to block the deploy on this, we can treat it as a follow-up fix.

**Comment by Christinadobrzyn** [comment] 2024-05-03 05:29
@robertKozik @Ollyws this https://github.com/Expensify/App/pull/41027 has caused this issue, can you guys take a look please?

**Comment by youssef-lr** [comment] 2024-05-07 05:12
friendly bump @robertKozik @Ollyws

**Comment by youssef-lr** [comment] 2024-05-07 20:53
@Ollyws the issue here I think is after that PR the line height is bigger when we type just an emoji

<img width="327" alt="Screenshot 2024-05-07 at 21 51 35" src="https://github.com/Expensify/App/assets/9680864/4bc51b92-a10a-4a2a-b8e9-e47074e861cf">

**Comment by Christinadobrzyn** [comment] 2024-05-09 05:58
It sounds like this should be a new job that's separate from https://github.com/Expensify/App/pull/41027? Is that right @youssef-lr and @Ollyws?

**Comment by youssef-lr** [comment] 2024-05-09 20:05
Sounds good, thanks for confirming @Ollyws.

**Comment by Christinadobrzyn** [comment] 2024-05-10 02:05
Looks like we're waiting for propsoals!

**Comment by Christinadobrzyn** [comment] 2024-05-14 07:59
Asking SWM if they might be able to grab this - https://expensify.slack.com/archives/C04878MDF34/p1715673579757139

**Comment by Christinadobrzyn** [comment] 2024-05-16 02:47
Thank you @filip-solecki! I added you to this GH.

**Comment by filip-solecki** [comment] 2024-05-16 11:49
Hi, looks like it is partially known issue that iOS devices are one step back with the composer and this is why the emoji is not enlarged. I think we should wait until [this PR](https://github.com/Expensify/react-native-live-markdown/pull/318) to live markdown will be merged and then we will recheck this issue.

**Comment by Christinadobrzyn** [comment] 2024-05-17 05:17
Thank @filip-solecki! We'll hold for https://github.com/Expensify/react-native-live-markdown/pull/318

**Comment by Christinadobrzyn** [comment] 2024-05-20 03:49
I think I'll keep this daily but keep an eye on https://github.com/Expensify/react-native-live-markdown/pull/318

**Comment by Christinadobrzyn** [comment] 2024-05-21 05:25
watching - https://github.com/Expensify/react-native-live-markdown/pull/318

**Comment by Christinadobrzyn** [comment] 2024-05-23 02:50
watching - https://github.com/Expensify/react-native-live-markdown/pull/318 - gonna move this to weekly since the PR merge is still in the works

**Comment by Christinadobrzyn** [comment] 2024-05-28 06:14
watching - https://github.com/Expensify/react-native-live-markdown/pull/318

**Comment by Christinadobrzyn** [comment] 2024-06-05 08:03
looks like this is still happening. 

@filip-solecki do you think we should still keep this on hold for https://github.com/Expensify/react-native-live-markdown/pull/318

**Comment by filip-solecki** [comment] 2024-06-05 08:50
Yes, we've tried to upgrade Markdown version [here](https://github.com/Expensify/App/pull/42454) but it was reverted, so I think soon there should be another try and this issue should disappear.

**Comment by Christinadobrzyn** [comment] 2024-06-12 08:53
Thanks for the update @filip-solecki! 

Just a heads up - I'm going to be ooo until June 24th. I'm not going to assign anyone new but if you need a new BZ teammate for any reason please feel free to ask for one to be assigned here.

**Comment by BartoszGrajdek** [comment] 2024-06-18 11:42
The bump went through, so we should be ready to get this retested!

**Comment by kavimuru** [comment] 2024-06-18 13:23
Bug is fixed 

https://github.com/Expensify/App/assets/43996225/ace88fc5-5553-4df9-aa29-5d685f2e6892

**Comment by Christinadobrzyn** [comment] 2024-06-20 19:31
Amazing! I think that means we can close this? @filip-solecki @BartoszGrajdek

**Comment by BartoszGrajdek** [comment] 2024-06-21 08:30
Yes we can! :)

**Closed** 2024-06-24 16:36 UTC
Labels: External, Engineering, Weekly, Bug
