### ISSUE TITLE
 Group – Unable to save uploaded group photo using Enter key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41943] opened 2024-05-09 18:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Click on FAB/Start chat
4. Add to group 2 users and press Next button
5. Click on group photo and upload a photo
6. Choose any photo
7. Press Enter key on keyboard to Save the photo

## Expected Result:
Able to save uploaded group photo using Enter key

## Actual Result:
Unable to save uploaded group photo using Enter key

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d6ba6bdd-fca3-499a-af34-05f782a734e5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-09 18:04
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-09 18:04
We think that this bug might be related to #vip-vsp

**Comment by nkdengineer** [comment] 2024-05-10 04:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Unable to save uploaded group photo using Enter key

### What is the root cause of that problem?
- When opening [AvatarCropModal](https://github.com/Expensify/App/blob/main/src/components/AvatarCropModal/AvatarCropModal.tsx), it will auto-focus on the <button id="overLayTopButton" /> that leads to when pressing on Enter,  ```shouldDisableEnterShortcut``` in [here](https://github.com/Expensify/App/blob/main/src/components/Button/index.tsx#L131) return true, so avatar is not saved
### What changes do you think we should make in order to solve the problem?

- We should update the ```shouldDisableEnterShortcut``` in [here](https://github.com/Expensify/App/blob/main/src/components/Button/index.tsx#L131) so that when the ```overlayTopButton``` is focused, ```shouldDisableEnterShortcut``` is still ```false```
### What alternative solutions did you explore? (Optional)
- NA

**Comment by abekkala** [comment] 2024-05-15 13:50
I don't think clicking Ente/Returnr is the same as clicking **"Save"**
<img width="624" alt="Screenshot 2024-05-15 at 8 49 18 AM" src="https://github.com/Expensify/App/assets/11966460/05bd0217-03a4-4c7e-ac64-b529d9915831">

I'm pretty sure you'd need to click Save in the modal in order to save those changes of adding a profile photo. 
Maaaybe @Expensify/design has a thought on how that should work when adding a profile photo?

**Comment by dannymcclain** [comment] 2024-05-15 14:34
It looks like the `<` back button is what has focus on this screen initially. So tapping enter basically "clicks" the back button. 

If I tab through the screen to focus the save button, hitting `Enter` saves as expected. I really don't feel strongly about this one—this feels like a reaaaaaally minor edge case to me. Happy to let the other designers weigh in as well.

**Comment by abekkala** [comment] 2024-05-15 14:54
thanks @dannymcclain 

> this feels like a reaaaaaally minor edge case to me.
I agree. But I can keep this open for just a bit to see if anyone else wants to lend their opinion.

**Comment by shawnborton** [comment] 2024-05-15 15:32
Yeah, I kinda think we have bigger fish to fry than these edge cases, so I would be cool just closing this.

**Comment by nkdengineer** [comment] 2024-05-15 15:41
> It looks like the < back button is what has focus



No. The < button is not focused. This bug is because we have a button that is added to fix the focus issue on desktop. And that button is focused when we open the edit photo page:
![image](https://github.com/Expensify/App/assets/161821005/c1602127-4db8-492c-954c-831a745e2ca6)

**Comment by dubielzyk-expensify** [comment] 2024-05-16 00:01
> that is added to fix the focus issue on desktop

To fix what issue out of curiosity?

**Comment by nkdengineer** [comment] 2024-05-16 00:04
@dubielzyk-expensify  The issue here:
https://github.com/Expensify/App/blob/8c7ec08d0eacd7e27791ff01b0e34b0fa3cb2597/src/libs/Navigation/AppNavigator/Navigators/Overlay/BaseOverlay.tsx#L28-L31

**Comment by dubielzyk-expensify** [comment] 2024-05-16 00:23
I'm with the designers that I think this is probably worth closing, but definitely seems like the focus should be on the `Save` button in this instance.

**Closed** 2024-05-20 13:37 UTC
Labels: Daily, Overdue, Bug
