### ISSUE TITLE
[$500] Login - User is able to log in with magic link after going back to initial log in page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33339] opened 2023-12-20 10:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open New Expensify app.
2. Enter an email and tap on "Continue".
3. On the magic code page, tap on "Go back".
4. Go to email inbox and look for the magic code email.
5. Tap on the magic link.

## Expected Result:
The user should not be able to log in with the magic link after returning to the initial login page.

## Actual Result:
The user is able to login with magic link after returning to the initial login page (different behavior on Web).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/24a45746-0202-4ca2-b933-ac0e984c6ef8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da73924fa3595221</li>
        <li>Upwork Job ID: 1737421990000820224</li>
        <li>Last Price Increase: 2023-12-20</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2023-12-20 13:04
I think this is the intended behaviour due to differences between platforms.
What I mean by this is if we take a closer look at the different platforms behaviour:

<details>
<summary>Web</summary>
Actions performed:

1. Open New Expensify app.
2. Enter an email and tap on "Continue".
3. On the magic code page, tap on "Go back".
4. Go to email inbox and look for the magic code email.
5. Tap on the magic link.

This is what we see on web if step (3) is performed and the email link is being opened in a (new tab):

<img width="996" alt="Screenshot 2023-12-20 at 14 41 18" src="https://github.com/Expensify/App/assets/56457735/263c259c-4b9c-4739-ab91-79db96514d37">

This is what we see on web if we don't perform step (3) and instead we remain on the magic code page in one tab, and this is a new tab that is opened by the link:

<img width="996" alt="Screenshot 2023-12-20 at 14 43 32" src="https://github.com/Expensify/App/assets/56457735/09e46934-7352-4350-b38d-daa8c1731818">

and in the tab where we stayed on the magic code page, we automatically get logged in once we're shown the page above.

</details>

<details>
<summary>Native</summary>
Actions performed:

1. Open New Expensify app.
2. Enter an email and tap on "Continue".
3. On the magic code page, tap on "Go back".
4. Go to email inbox and look for the magic code email.
5. Tap on the magic link.

On native devices (android / iOS) once the email link is clicked, it automatically opens the mobile app and performs login, no matter if step (3) is performed or not.
</details>

**Comment by Christinadobrzyn** [comment] 2023-12-20 20:27
I don't understand the issue. In testing this I think it is behaving as expected. Maybe the issue is the workflow is different for the mobile app? I'm going to close this without action.

**Closed by Christinadobrzyn** 2023-12-20 20:27 UTC
Labels: External, Daily, Help Wanted, Bug
