### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] Mweb-IOU- In distance request money, the address suggessions are fetched in forced offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26869] opened 2023-09-06 13:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3.Tap Preferences
4.Toggle on Forced offline
5.Navigate to LHN
6.Tap FAB
7. Tap request Money
8.Tap Distance
9.Tap Start
10.Enter few characters of an address
11.Turn off mobile data
12.Enter few characters of an address

## Expected Result:
In distance request money, If we turn off mobile data, the address suggestions are not fetched.
Similarly, the address suggessions must not be fetched in forced offline.

## Actual Result:
In distance request money, If we turn off mobile data, the address suggestions are not fetched.
But, the address suggessions are fetched in forced offline.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/5919ea9d-e393-4ba9-a27d-d4304567436c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**@

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01718c850ed1cc7d9c</li>
        <li>Upwork Job ID: 1700229247184764928</li>
        <li>Last Price Increase: 2023-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 26694110</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-06 13:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 In distance request money, the address suggessions are fetched in forced offline 

### What is the root cause of that problem?
The AddressSearch component uses the Google Places Autocomplete module which fetches data from a different API URL.

### What changes do you think we should make in order to solve the problem?
Update the AddressSearch component by conditionally setting the requestUrl to null when should force offline is enabled.

### What alternative solutions did you explore? (Optional)
None.

**Comment by mountiny** [comment] 2023-09-06 13:48
The forced offline is mainly staging feature, I dont think this is a deploy blocker

**Comment by Christinadobrzyn** [comment] 2023-09-07 19:18
I think this is similar - https://github.com/Expensify/App/issues/26478#issuecomment-1710654264 - asking

**Comment by Christinadobrzyn** [comment] 2023-09-08 19:26
This issue is different so we need to get an external on this

**Comment by DylanDylann** [comment] 2023-09-09 07:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In distance request money, the address suggessions are fetched in forced offline

### What is the root cause of that problem?
In forced offlined, we only prevent making API from the App repository. But we still can call the API from libraries. In this case 
https://github.com/Expensify/react-native-google-places-autocomplete/blob/4324dd7b156075d1817fea60b007584fa73b08ea/GooglePlacesAutocomplete.js#L546-L552

We are making requests in react-native-google-places-autocomplete library. So that the API still can executed
### What changes do you think we should make in order to solve the problem?
I suggest that we should pass isOffline props to GooglePlacesAutocomplete and in GooglePlacesAutocomplete we will prevent making API if  isOffline is true

In here
https://github.com/Expensify/react-native-google-places-autocomplete/blob/4324dd7b156075d1817fea60b007584fa73b08ea/GooglePlacesAutocomplete.js#L502C1-L502C1

we should update like this

```
if (supportedPlatform() && text && text.length >= props.minLength && !props.isOffline)
```

**Comment by Christinadobrzyn** [comment] 2023-09-11 21:53
we're reviewing proposals

**Comment by Christinadobrzyn** [comment] 2023-09-12 20:03
hey @allroundexperts can you let me know what you think of https://github.com/Expensify/App/issues/26869#issuecomment-1712443469

**Comment by akinwale** [comment] 2023-09-15 16:02
@nkuoch @allroundexperts My [main PR](https://github.com/Expensify/App/pull/27542) is ready for review.

I have also created the [dependency PR](https://github.com/Expensify/react-native-google-places-autocomplete/pull/5) in the Google Places Autocomplete repo. There are currently no reviewers assigned, but it will require a review as well before merging.

**Comment by Christinadobrzyn** [comment] 2023-09-29 19:01
@allroundexperts do we want to regression test for this? 

Payouts due:

Issue Reporter: NA
Contributor: $500 + $250 bonus @akinwale (paid in Upwork)
Contributor+: $500 + $250 bonus @allroundexperts (paid in NewExpensify)

Eligible for 50% #urgency bonus? Y - https://github.com/Expensify/App/issues/26869#issuecomment-1725192165

Upwork job is [here](https://www.upwork.com/jobs/~01718c850ed1cc7d9c).

**Comment by Christinadobrzyn** [comment] 2023-09-29 19:34
Sounds good! Thank you! I've paid this out. 

Closing, feel free to reopen if needed!

**Closed by Christinadobrzyn** 2023-09-29 19:34 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 13:28
$750 payment approved for @allroundexperts based on BZ summary.
