### ISSUE TITLE
[$500] Web - Bank Account - Error is shown when clicking on name field

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31890] opened 2023-11-26 22:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.3-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** 
**Slack conversation:** @

## Action Performed:
1. Go to settings > Workspace > choose a works space(currency should be USD)
2. Bank account > Connect Manually
3. Fill in the details of steps 1 and 2 then go to step 3
4. Click on the first name field. and enter your name. Notice that clicking on the field does not bring an error.
5. After filling in the First Name click on the Last Name field and notice that an error is shown

## Expected Result:
Clicking on a Name field does not cause an error

## Actual Result:
Clicking on a name field causes an error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/47c48c7d-61c1-425c-9c01-c9956a5a2dca

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f83b7fb2dea297a0</li>
        <li>Upwork Job ID: 1728902330154385408</li>
        <li>Last Price Increase: 2023-11-26</li>
    </ul>
</details>

**Comment by unicorndev-727** [comment] 2023-11-26 23:11
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
Error is shown when clicking on name field.
### What is the root cause of that problem?
The root cause the default value for lastName is empty here.
https://github.com/Expensify/App/blob/db37e46f58aceea23c0136e1bdce6e3ed9d2d90f/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#249
### What changes do you think we should make in order to solve the problem?
we need to check this line.

### What alternative solutions did you explore? (Optional)
  N/A

**Comment by Tony-MK** [comment] 2023-11-27 00:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Error is shown when clicking on name field

### What is the root cause of that problem?

The root cause of the problem is that by default the `FormProvider` component validates the value in the field when the `OnBlur` event occurs because the default value for the `shouldValidateOnBlur` prop is `true`. This problem also occurs in vice versa and when clicking different fields such as SSN.

### What changes do you think we should make in order to solve the problem?

Apply, `shouldValidateOnBlur={false}`, to any applicable input components in the `IdentityForm` such as the first name, last name, SSN, etc. Possibly add it to any other inputs in the forms in `ReimbursementAccountPage` that are applicable.

**Comment by abzokhattab** [comment] 2023-11-27 01:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error is shown on the first touch of the required fields
### What is the root cause of that problem?
'

Within the code snippet found at [this link](https://github.com/Expensify/App/blob/5c462730b56dbd42597252fdc1c81765a7e40dd6/src/pages/ReimbursementAccount/RequestorStep.js#L44-L45), we validate the input values. This process involves two key functions:

1. getFieldRequiredErrors: This function examines whether any of the required values in the input are empty. If it detects any empty values, it returns the corresponding errors.

2. validate function: Triggered by the `onBlur` event, as specified [here](https://github.com/Expensify/App/blob/50529315eb503732f0a4459b892d5047b528eac6/src/components/Form/FormProvider.js#L269-L291), the validate function encompasses the execution of `getFieldRequiredErrors`. The `onBlur` event occurs when a user clicks on the first field, then clicks on another field, or shifts focus away from the currently selected field. Consequently, the validate function is invoked, internally calling getFieldRequiredErrors. In the specific scenario described, if the second field remains empty, `getFieldRequiredErrors` generates errors.

### What changes do you think we should make in order to solve the problem?

what we want to do is to prevent the isRequired erros on the first touch of any field:

1. to do that, we need to disable the isRequired errors for the current touched field, so  we should add a third arg to the `getFieldRequiredErrors` function, which is the `focusField`:
and exclude the errors of that field as follows:
 
```js
function getFieldRequiredErrors(values: OnyxCommon.Errors, requiredFields: string[], focusedField: string) {
    const errors: OnyxCommon.Errors = {};
    requiredFields.forEach((fieldKey) => {
        if (isRequiredFulfilled(values[fieldKey]) || (focusedField && fieldKey === focusedField)) {
            return;
        }
        errors[fieldKey] = 'common.error.fieldRequired';
    });
    return errors;
}
```

2. update the validate args to  
```js 
const validate = (values, focusedField) => {
    const errors = ValidationUtils.getFieldRequiredErrors(values, REQUIRED_FIELDS, focusedField);
```
3. finally in the `FormProvider`, add a new ref var that saves the current touched field: 
```js
    const touchedInputId = useRef(null);
```

also inside the `onValidate` update the validate call to:
```js
const validateErrors = validate(values, touchedInputId.current) || {};
```
also set the touchedInputId in the `onTouched` `onPressed` `onPressIn` functions:
```js
touchedInputId.current = inputID;
```

finally in the `onBlur` function add an `else` statement to this condition and set the touchedInputId to null in case the focus is moved `if (Visibility.isVisible() && Visibility.hasFocus()) {`:

```js
   } else {
                        touchedInputId.current = null;
                    }
```


# POC:

https://github.com/Expensify/App/assets/59809993/00fcdc89-6396-4e51-ab9f-f5f75c1f7b8d

**Comment by situchan** [comment] 2023-11-27 01:33
Dupe of https://github.com/Expensify/App/issues/31570

**Comment by johncschuster** [comment] 2023-11-29 15:16
Good callout, @situchan! Let's close this issue in favor of #31570.

**Closed by johncschuster** 2023-11-29 15:16 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by tsa321** [comment] 2023-12-06 02:56
@situchan @alitoshmatov  just to confirm is the issue's video is the expected result?
