### ISSUE TITLE
[$500] ESC click while view photo is loading closes everything

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29210] opened 2023-10-10 17:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696952847615929

## Action Performed:
1. Open the app
2. Open settings->click on profile pic-> again click on profile pic
3. Click on view photo and until view photo is fully loaded, click ESC (better recreated on slower network)
4. Observe that app closes RHN too on single ESC click
## Expected Result:
App should only close view photo attachment popup on single ESC click when ESC is clicked while it has partially loaded
## Actual Result:
App closes attachment popup as well as RHN on single ESC click when ESC is clicked while view photo is partially loaded
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/985e9a14-61fe-468d-9234-15537ac09365

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/9485237e-6cf4-4fd5-97b7-2bb517b111ad

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/d6836513-3b46-45f1-b6e3-c5667f025b8b

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/ed39c517-ab19-4846-992d-212034361dd8

https://github.com/Expensify/App/assets/38435837/9633e0bb-ea43-4eab-b516-b75b9c9b245e

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/33067f57-384c-4096-9bf4-db3c101d3027

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5a428f53b9a47a9</li>
        <li>Upwork Job ID: 1711795256567808000</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-10-11 05:35
https://github.com/Expensify/App/assets/141406735/06bc5503-defa-4b67-bcbd-47eb2fb60e35

I can't reproduce

**Comment by cubuspl42** [comment] 2023-10-19 09:35
@m-natarajan As this is not reproducible, let's close this

**Comment by cubuspl42** [comment] 2023-10-25 07:07
@m-natarajan



> @m-natarajan As this is not reproducible, let's close this

**Comment by mvtglobally** [comment] 2023-10-27 00:47
Issue not reproducible during KI retests. (First week)

**Comment by cubuspl42** [comment] 2023-10-27 08:59
@mvtglobally Do you or someone from your team have the required permissions to close this issue? I tried to ping @m-natarajan twice

**Closed** 2023-11-01 13:16 UTC
Labels: External, Daily, Help Wanted, Overdue
