### ISSUE TITLE
Text selection in pdf works weirdly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20537] opened 2023-06-09 17:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Click on +
3. Click on add attachment
4. Choose a pdf file and send
5. Open the pdf
6. Try selecting the text by long pressing and move your cursor
## Expected Result: 
Only the text you are trying to select should be highlighted
## Actual Result: 
The text at the top gets selected multiple times while moving the cursor

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9c133610-158a-46f8-95b7-c80bbf8bfe69

https://github.com/Expensify/App/assets/43996225/89b2bbd1-871b-45c0-8222-5a5146b40539

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685991865005029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment] 2023-06-11 18:11
I'll test soon

**Comment by DanutGavrus** [comment] 2023-06-12 12:49
For context:
- Seems to be this [issue](https://github.com/wojtekmaj/react-pdf/issues/101);
- Which actually won't be fixed as per this [comment](https://github.com/wojtekmaj/react-pdf/issues/101#issuecomment-345846047).

**Comment by DanutGavrus** [comment] 2023-06-13 09:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Text selection in pdf works weirdly.

### What is the root cause of that problem?
This is an older issue inside `react-pdf` dependency as it may be seen [here](https://github.com/wojtekmaj/react-pdf/issues/101#issuecomment-345846047).
We are currently using `react-pdf` version [5.7.2](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.7.2) which was released in __Mar 30, 2022__.
It seems to have been fixed in version [6.1.0](https://github.com/wojtekmaj/react-pdf/releases/tag/v6.1.0) which was released in __Nov 15, 2022__.
Latest version is [7.1.2](https://github.com/wojtekmaj/react-pdf/releases/tag/v7.1.2) which was released in __Jun 12, 2023(yesterday)__.

### What changes do you think we should make in order to solve the problem?
Update to a newer version, latest v6, or latest v7(or any in which the bug is fixed). I've configured both Expensify, and a new Demo app to test some versions in both. In v6 & v7, the new behavior will be:

https://github.com/Expensify/App/assets/56603839/7073421a-44b7-43fc-ac88-e0f2916f4d36

### What alternative solutions did you explore?
Use another library if we find one which has a better selection functionality and everything else we need.

**Comment by alexpensify** [comment] 2023-06-13 17:53
This one is on my testing list

**Closed** 2023-06-14 20:19 UTC
Labels: Daily, Bug

**Comment by DanutGavrus** [comment] 2023-06-14 20:47
@dhairyasenjaliya oh, ok then, I understand

**Comment by alexpensify** [comment] 2023-06-14 23:16
Thanks for flagging that GH @dhairyasenjaliya-- I missed that one when I was reviewing this GH.
