### ISSUE TITLE
[$1000] Web - Error message disappears when copying and pasting URL into new tab in Two-Factor Authentication settings

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23488] opened 2023-07-24 14:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Security > Two-Factor Authentication.
2. Click on the "Copy" button and then click "Next."
3. Enter a random number and observe that the error message appears.
4. Copy the URL and paste it into a new tab. Return to the first tab and wait a moment, and you'll notice that the error message disappears.

## Expected Result:
The error message should remain visible even after copying and pasting the URL into a new tab.

## Actual Result:
When a user copies and pastes a URL in new tabs, the error message in Two-Factor Authentication settings disappears in the first tabs, causing confusion for the user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2756d621-179f-4cfa-847b-a63df05c18b0

https://github.com/Expensify/App/assets/93399543/321bb990-a713-4afc-a86a-ecf8c8609ed6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690146457816229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137e2dcc85cd15329</li>
        <li>Upwork Job ID: 1683502867718090752</li>
        <li>Last Price Increase: 2023-08-14</li>
    </ul>
</details>

**Comment by DreamOfSolution126** [comment] 2023-07-24 16:00
Hi, dear. How are you?
I am the professional software engineer for mobile/web application.
Can I join to your slack channel?
Thanks

**Comment by agiledeveloperbuild** [comment] 2023-07-24 18:08
Contributor details
Your Expensify account email: agiledeveloperbuild@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0161797a9dd152566d

**Comment by HidekiKondo123** [comment] 2023-07-24 18:25
Contributor details
Your Expensify account email: HidekiKondo123@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011726d22dcecd33ee

**Comment by Marwanx10** [comment] 2023-07-24 18:26
Contributor details
Your Expensify account email: marwan.mohsen1000@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018f28971a7021ee62

**Comment by DevWizard0000** [comment] 2023-07-24 19:38
### Please re-state the problem that we are trying to solve in this issue.
The error message doesn't disappear when user open new tab.

### What is the root cause of that problem?
The error message appears when the user validate the code.
The error message is not related to the new open tab.

### What changes do you think we should make in order to solve the problem?
You have to remove error message when user opens the new tab or select another component outside of the panel.

**Comment by mehvash-Khan** [comment] 2023-07-24 21:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error message disappears in `Two-factor authentication` step 2, when the same URL is copied and opened in a different tab.

### What is the root cause of that problem?
The root cause of this problem is that the error message is directly fetched from onyx data [here](https://github.com/Expensify/App/blob/4e7c9e04127d6fd20b2b81f7afa87c0f7633f8c2/src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthForm/BaseTwoFactorAuthForm.js#L90C9-L90C9) instead of maintaining it as a state variable within the component `BaseTwoFactorAuthForm`. When a new tab is opened with the same URL, `account.errors` in onyx data is unset. Since onyx data is maintained in IndexedDB which is common across all tabs, the error message in our original tab also disappears.

### What changes do you think we should make in order to solve the problem?
One solution to this issue can be maintaining a state of our error message within the `BaseTwoFactorAuthForm` component which is currently being fetched from `account.errors` from onyx data. Let us call this state `errorText` for now. Whenever we get error for our account, our state `errorText` will be updated with the message in `account.errors`.

Ideally `errorText` should only be set after the code is submitted. This can be tracked with a new boolean state variable. Let's call it `toggle` for now. We can come up with a better name in the actual solution. When a magic code is be submitted, we can set the `toggle` state to `true`. Now, we will only update the message in the `errorText` state variable when `toggle` is `true`.  When setting `errorText` with the message from `account.errors`, we can reset `toggle` to `false`. This will prevent `errorText` from being set to `null` when `account.errors` is reset for any reason (in our case, when the same page is opened in another tab). Below is the code representing the above explained solution:

`BaseTwoFactorAuthForm.js`
```js
const [errorText, setErrorText] = useState('');
 const [toggle,setToggle] = useState(false);
const accountError = ErrorUtils.getLatestErrorMessage(props.account);
 useEffect(() => {
        if(!toggle) { return; }
            setErrorText(accountError);
            setToggle(false);
    }, [accountError])
```

Now call `setToggle(true)` in function `validateAndSubmitForm`. We will replace our error state below:

<img width="985" alt="Screenshot 2023-07-25 at 1 15 37 AM" src="https://github.com/Expensify/App/assets/127308250/d3f41c24-9c22-4430-9de0-d0c0a49ec77e">
 
 

### What alternative solutions did you explore? (Optional)

**Comment by joh42** [comment] 2023-07-25 15:14
Let me preface my proposal by noting that I'm not sure this corner case is something that should be fixed. In what scenario would a user have two instances of the 2FA setup verification page open in the same browser?

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When opening the 2FA setup verification page more than once, form errors for all other instances of this page are cleared.
### What is the root cause of that problem?
The root cause of the problem is that form errors are shared between 2FA setup validation forms, but the 2FA code is not. Whenever the verification page mounts, the errors are cleared for other instances of this page open in the same browser, but any 2FA codes that have been entered remain.
### What changes do you think we should make in order to solve the problem?

There are a couple ways to approach this issue.

One would be to clear invalid 2FA codes upon submission. This would in my opinion be the best for UX, as it would make it easier for users to enter a new, correct code, and we would not end up with the invalid 2FA error being removed while the actual invalid code remains. That is the way invalid 2FA codes are handled by some other web apps I use.

But the core of the issue is that errors in the 2FA form are stored in Onyx, while the actual 2FA code is not. So when the page is opened in another tab and errors are cleared, 2FA codes are not. As such, another approach would be to make sure that either both errors and 2FA codes are stored in Onyx, or neither of them are. If both are stored in Onyx, we should clear errors and 2FA codes when the page mounts.

But in my opinion, the data for this form does not need to be persistent. Unlike most forms, this is not something you will leave unfinished and then come back to. If you do, you will need to enter a new 2FA code anyway.

### What alternative solutions did you explore? (Optional)

**Comment by DreamSoft0888** [comment] 2023-07-31 04:39
Contributor details
Your Expensify account email: janithaamaradasa0888@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015084d5d2f275fda4

**Comment by laurenreidexpensify** [comment] 2023-07-31 10:02
@thesahindia bump for review pls ^^ thanks

**Comment by sourcecodedeveloper** [comment] 2023-08-03 14:36
Contributor details
Your Expensify account email: sourcecodedeveloper@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by sourcecodedeveloper** [comment] 2023-08-03 14:39
Contributor details
Your Expensify account email: sourcecodedeveloper@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by laurenreidexpensify** [comment] 2023-08-04 14:59
Still waiting for proposals

**Comment by laurenreidexpensify** [comment] 2023-08-07 12:33
Still no proposals coming in

**Comment by mehvash-Khan** [comment] 2023-08-07 12:35
Hey @laurenreidexpensify , Did you get a chance to go through my [proposal](https://github.com/Expensify/App/issues/23488#issuecomment-1648670879)?

**Comment by aditygrg2** [comment] 2023-08-07 19:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

To avoid the data changes on other tabs due to the data states in IndexedDB Store.

### What is the root cause of that problem?

The main problem is that all the data is stored in `Onyx`. It is global to all the browser tabs, so on any event calls the listeners pertaining to all other browser tabs listen to the same data state, which causes problems as there is no tab isolation.

### What changes do you think we should make in order to solve the problem?

This will require some major changes. This issue is present on pages that take data from the Onyx store, including login, signup pages, the 2FA page, and many others. To maintain tab isolation we might generate a UUID in SessionStorage and use that as a composite key for tab isolation. 

The basic map of how it will work is:

1. On the Expensify load, we can generate a `sessionID` (which can be considered as a tab-key - a unique tab key) which will have the same copy on `Onyx` too.
2. We might check if there is a key with a different  `sessionID` on `Onyx`, if different, we may do something. Here things might go complex as we have two choices -

- The simplest thing we can do is to show the user, that the same operation is already happening on another tab. So in this way, we will block the cases where the data from Onyx is required, and already the same thing is being run on another tab.
- Otherwise, we might have to do a lot of changes, as all the data is fetched from `Onyx` itself, we may need to consider doing that via states on the frontend.
- We might also consider sending `sessionID` with every get request to `Onyx`, for requesting data, so tab isolation can be maintained. But then we have some cases where tab isolation should not be guaranteed, for example saving an authentication session, 2FA status should indeed have a global state for all tabs of the browser.

### What alternative solutions did you explore? (Optional)

There might be more solutions to this, and as there is only one global DB for the browser (to all tabs) there might be complexities in doing this. The proposals given above will work well for just 2FA screens but there are a lot of areas where this may happen.

I am still looking for improvements on this proposal as this might not be the perfect solution. Any feedbacks are appreciated.

cc @laurenreidexpensify

**Comment by laurenreidexpensify** [comment] 2023-08-08 15:58
@thesahindia couple of proposals above to review ^^

**Comment by sourcecodedeveloper** [comment] 2023-08-12 22:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error states are not being kept synchronized across tabs because they are not being persisted in gobal data store Indexed DB. Therefore when multiple tabs of a url are open and upon entering invalid code in one tab and refreshing the second tab, the error states and texts 
are cleared from Indexed DB, clearing the error text from the first tab and causing confusion for the user.

### What is the root cause of that problem?
The main issue is that error states are not persisting in global data store Indexed DB. In some areas the error states match across tabs and in some areas it does not. 

### What changes do you think we should make in order to solve the problem?
Going for tab isolation would require major rework and potentially still have problems. The simplest approach here is to perist error states across Onyx DB so when the user opens multiple tabs of the 2FA page, upon refreshing any tab the error state perists in the other tabs. The idea is to keep it same across tabs.

For the changes, I propose adding another key/value pair in Onyx db for persiting error states across page refreshes.
I have made a patch and attaching a video of how it works,

https://github.com/Expensify/App/assets/141340971/ac5beec0-3266-40ec-847d-d16e5ab5f40b

@thesahindia  
The same issue can be reproduced on the profile page when adding secondary contact. So now there are 3 areas (Login, 2FA, Profile-Add secondary contact) where the error states are disppearing.

To make it clear what the UI should be like I have uploaded another video of workspaces error where the error states remain consistant across tabs and upon browser refresh.

https://github.com/Expensify/App/assets/141340971/bd65886b-0d78-42ae-a325-df118e59b31a

Open to suggestions and feedback.

**Comment by laurenreidexpensify** [comment] 2023-08-15 07:26
@parasharrajat can you review this when you have a mo? Thanks

**Comment by laurenreidexpensify** [comment] 2023-08-15 07:27
Reassigned as @thesahindia has limited availability at mo

**Comment by laurenreidexpensify** [comment] 2023-08-22 10:21
@parasharrajat are still thinking :donothing:?

**Comment by laurenreidexpensify** [comment] 2023-08-27 09:29
@parasharrajat bump ^

**Comment by laurenreidexpensify** [comment] 2023-08-27 09:33
Thanks for confirming!

**Closed by laurenreidexpensify** 2023-08-27 09:33 UTC
Labels: Daily, Internal, Bug
