### ISSUE TITLE
[HOLD for payment 2024-07-10] Android & iOS - Tags - "Enabled" badge is not crossed out when tag is deleted offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42673] opened 2024-05-27 21:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/tests/view/4578912
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to workspace settings
3. Go to Tags
4. Add a tag if there is no tag
5. Go offline
6. Delete the tag

## Expected Result:
The "Enabled" badge will be crossed out when tag is deleted offline (web behavior)

## Actual Result:
The "Enabled" badge is not crossed out when tag is deleted offline
This issue also applies to categories, distance rates and tax rates

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dcd0e5b0-83c7-432e-8a93-9445718ef359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment] 2024-05-27 21:41
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-27 21:41
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-05-28 04:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Enabled badge of the right component is not crossed out when deleting a tag while offline.

### What is the root cause of that problem?
The crossed out style is applied from OfflineWithFeedback. OfflineWithFeedback will give the component a deleted style.
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/components/OfflineWithFeedback.tsx#L116-L118

However, the Enabled badge component itself doesn't accept any style props.
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/components/SelectionList/ListItemRightCaretWithLabel.tsx#L14

So, the deleted style is never applied to it.

### What changes do you think we should make in order to solve the problem?

Add a style prop to ListItemRightCaretWithLabel and append it to the label text style here.
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/components/SelectionList/ListItemRightCaretWithLabel.tsx#L20

**Comment by JmillsExpensify** [comment] 2024-05-30 05:09
Opening up to the community.

**Comment by JmillsExpensify** [comment] 2024-06-05 05:29
Still waiting for proposal review. cc @DylanDylann

**Comment by DylanDylann** [comment] 2024-06-05 10:15
This issue only reproduces on the native app. I think the RCA will be more complicated than the above proposals

> However, the children recursive search logic will not work in case the Text is nested inside another custom component like the Badge [here](https://github.com/Expensify/App/blob/a04481ffef2c60243c8c5680222a01a82e162916/src/components/Badge.tsx#L56). In this case, when iterating [here](https://github.com/Expensify/App/blob/a04481ffef2c60243c8c5680222a01a82e162916/src/components/OfflineWithFeedback.tsx#L118), the children of Badge element will be undefined, because children only works for elements directly exposed inside the children of OfflineWithFeedback.tsx. This leads to the Text (a child in Badge structure) not having the strike-through style applied.

@tienifr Thanks for this point. But it is still grey to me, I will need some time to dive deep into this problem. It would be great if you could detail more

**Comment by mvtglobally** [comment] 2024-06-10 12:44
Issue not reproducible during KI retests. (First week)

**Comment by DylanDylann** [comment] 2024-06-11 08:28
@mvtglobally I still reproduce on IOS

**Comment by DylanDylann** [comment] 2024-06-11 08:30
Update: I am still deep diving into @tienifr's proposal. This bug is specific to native device

**Comment by DylanDylann** [comment] 2024-06-11 08:46
@Krishna2323 @bernhardoj Your RCA isn't correct to me because we implement the recursive logic to apply strike-through to child components (read @tienifr's proposal for more detail)

**Comment by DylanDylann** [comment] 2024-06-11 09:00
@tienifr Thanks for your [detail](https://github.com/Expensify/App/issues/42673#issuecomment-2152046288). But It is still grey to me.  In [TableListItem](https://github.com/Expensify/App/blob/a04481ffef2c60243c8c5680222a01a82e162916/src/components/OfflineWithFeedback.tsx#L119) Component, we still TextWithTooltip (it is a custom component) but it still be greyed out

**Comment by DylanDylann** [comment] 2024-06-11 10:36
I would prefer @tienifr's [proposal](https://github.com/Expensify/App/issues/42673#issuecomment-2147636404). Let's go with them

**Comment by JmillsExpensify** [comment] 2024-07-11 18:40
@tienifr mind filling out the BZ checklist? I confirm the $250 payment summary above is correct for both contributors.

**Comment by JmillsExpensify** [comment] 2024-07-11 18:41
@DylanDylann shall I create an Upwork job/contract for you?

**Comment by DylanDylann** [comment] 2024-07-12 17:47
@JmillsExpensify Yes please!

**Comment by JmillsExpensify** [comment] 2024-07-16 17:07
@DylanDylann offer sent!

**Comment by JmillsExpensify** [comment] 2024-07-19 00:44
Reminder on the Upwork contract!

**Comment by DylanDylann** [comment] 2024-07-19 07:17
@JmillsExpensify Sure thing, I accepted the offer, TY

**Comment by JmillsExpensify** [comment] 2024-07-20 16:48
All paid out! @tienifr I'm going to close this issue for now, though before you submit an expense via New Expensify, please make sure to complete the BZ checklist.

**Comment by DylanDylann** [comment] 2024-08-05 05:01
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Go to workspace settings
2. Go to Tags
3. Add several tags if there is no tag
4. Go offline
5. Delete the tags
6. Verify the tag and "Enabled" badge will be crossed out when the tag is deleted offline
7. Go online
8. Verify the tags disappear


Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-08-05 12:02
Ah thanks! I'll re-open this one.

**Comment by JmillsExpensify** [comment] 2024-08-05 12:04
@mallenexpensify would you mind double-confirming payment summary before I approve payment?

**Comment by mallenexpensify** [comment] 2024-08-06 23:19
Contributor: @DylanDylann paid $250 via Upwork
Contributor+: @tienifr owed $250 via NewDot

**Closed by mallenexpensify** 2024-08-06 23:19 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-06 23:38
$250 approved for @tienifr
