### ISSUE TITLE
Web - Task - Checkmark is not automatically updated when assignee is not set

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31909] opened 2023-11-27 13:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2.3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a chat with another account (i.e account B)
2. Inside the chat click on plus icon in the composer
3. Click on assign task
4. Insert a title and click on next
5. Confirm the task without selecting an assignee
6. From account A click on the checkbox of the recently created task
7. Observe the task on account B

## Expected Result:
The checkbox should update and change to being marked as done on account B right after the task is marked as done from account A.

## Actual Result:
The checkbox stays unmarked even after the task was marked as done from account A

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4842e605-bb01-4cd2-afc5-65aaec0d1434

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015113d6ac5682a883</li>
        <li>Upwork Job ID: 1729155989948653568</li>
        <li>Last Price Increase: 2023-11-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-11-27 13:56
Production 

https://github.com/Expensify/App/assets/93399543/6c812e9a-87d9-4f58-8dea-6964abdef130

**Comment by dangrous** [comment] 2023-11-27 14:25
hey @kbecciv can you try your production test again but **don't assign the task**? That seems to be the differentiator here. I'm seeing this bug replicated on production, so I want another set of eyes.

If it's indeed the case, this is a bug we should fix BUT it's not a deploy blocker. Thank you!

**Comment by abzokhattab** [comment] 2023-11-27 15:06
I am also able to reproduce it on prod.. 

I guess this is a backend pusher issue

**Comment by mountiny** [comment] 2023-11-27 15:11
This seems to be more so a backend issue, I will remove the deploy blocker label since its a last blocker

**Comment by kavimuru** [comment] 2023-11-27 15:43
@dangrous able to reproduce in production. 

https://github.com/Expensify/App/assets/43996225/07b28381-768f-4642-8d57-8b0addb682de

**Comment by dangrous** [comment] 2023-11-27 15:46
Great, thank you! We'll move forward with investigation but not as a blocker

**Comment by dangrous** [comment] 2023-11-27 17:54
Okay so two weird things:
* `participantAccountIDs` when the task is completed from the creator's side only includes the creator. That's why it's not being sent. Not sure where this is occurring yet.
* If you try to complete the task from the other account, there's a silent `411 Insufficient privileges` error.
 
So I think somewhere the non-creator account is not being listed as a participant in the task, even though they should be. I think that would explain both bugs. TBD on a fix

**Comment by dangrous** [comment] 2023-11-28 20:02
Putting @thienlnam's comment from Slack here for posterity, will hopefully have time to chug through this this week:

> Yeah I think we’d need to make sure all of those auth commands return the participants of the parent chat in $response['parentParticipants']['participantsAccountIDs'] , and then the parentReportActionID will need to have some more keys that represent the state of the task like childReportState or something similar (you’ll have to check what is returned currently)

**Comment by dangrous** [comment] 2023-12-01 16:28
Haven't had time for this this week, I will likely be able to look into it mid-next week at the earliest (trying to finish out the whatsnext budgets project)

**Comment by dangrous** [comment] 2023-12-05 03:03
as noted, no time yet. will get there.

**Comment by dangrous** [comment] 2023-12-08 21:21
I was out unexpectedly this week, this is somewhat low priority so I will hopefully be able to grab it next week

**Comment by dangrous** [comment] 2023-12-12 22:58
no update since above, hoping to get to this later this week

**Comment by dangrous** [comment] 2023-12-15 21:18
Maybe will have time this afternoon. But it's on my mind!

**Comment by dangrous** [comment] 2023-12-19 00:29
@thienlnam Can we get your advice on this one? I've finally had the chance to look into it, and I have a couple questions. So there are two issues:
* The owner of a task completing it does not update the parent report for another user in the parent report.
  * But I'm confused as to why this is. Shouldn't [this call to sendChildDetailsToParentAction](https://github.com/Expensify/Web-Expensify/blob/ac26ddb1425c58704478cc4f6d46347ff155d94c/lib/ReportAPI.php#L6103) send the status update to any participants in that report? Or does that not actually do what I think it does.
* Another user in the parent report does not have the permissions to complete a task, until they've opened it.
  * Above, I mentioned that it is a 411 error, but I just tried it again and am getting 666 Cannot complete action which means it's now happening before it gets to the [actual check for permissions](https://github.com/Expensify/Auth/blob/11f932c81872012d92814a555b6e7bb2e00d21f3/auth/command/CompleteTask.cpp#L26-L28). So how can we tell auth that that user should have permissions for the task? Do we need to change something on the creation side?

**Comment by thienlnam** [comment] 2023-12-20 22:34
> Shouldn't [this call to sendChildDetailsToParentAction](https://github.com/Expensify/Web-Expensify/blob/ac26ddb1425c58704478cc4f6d46347ff155d94c/lib/ReportAPI.php#L6103) send the status update to any participants in that report?

I think you might have mis-linked but that method should do exactly that - I would maybe check if [this](https://github.com/Expensify/Web-Expensify/blob/ab4528c05bfbd1757a60734414b1be0ded28e561/lib/ReportUtils.php#L3125-L3160) has the parent participants correctly when it is being called but it should be sending that pusher update 

> Another user in the parent report does not have the permissions to complete a task, until they've opened it.

This is what I'm working on in here https://github.com/Expensify/Expensify/issues/339618, it turns out there's a lot of issues that come up when a user is not shared on a report. I believe we can fix this by just sharing the user to the report in the peek() of all these commands. Haven't tested it yet but should hopefully solve this problem

**Comment by dangrous** [comment] 2023-12-21 19:54
Oops yeah, I meant this - https://github.com/Expensify/Web-Expensify/blob/ac26ddb1425c58704478cc4f6d46347ff155d94c/lib/ReportAPI.php#L6089 - I looked at the stuff that it gets called with, and it had the right participants (i.e. everyone) but maybe wasn't sending the status along (but I don't really get why that would happen).

And great about the second question! I can focus on the first (unless you have ideas)

**Comment by thienlnam** [comment] 2023-12-21 20:10
> but maybe wasn't sending the status along (but I don't really get why that would happen).

Oh yes - you're on the right track here. That method needs to send back more parameters (i.e it's not passing back the childStateNum / childStatusNum)

**Comment by dangrous** [comment] 2024-01-02 20:32
Back now, will start trying to get this closed out tomorrow or later today

**Comment by dangrous** [comment] 2024-01-04 21:32
> [Dec 21, 2023](#event-11315043537)
> [<img alt="@dangrous" width="40" height="40" src="https://avatars.githubusercontent.com/u/5487802?s=80&amp;u=aee1f073aaca973344aa8f64014140da0e0ed251&amp;v=4">](/dangrous)
> 
> [ Member ](https://github.com/Expensify/App/commits?author=dangrous)
> ###

Ah lovely, this was it! Putting up a PR now.

**Comment by dangrous** [comment] 2024-01-10 16:35
Just tested this, it works nicely on prod now! I am going to close this - I don't believe any payment is due but @alitoshmatov (or anyone else?) please let me know if I am incorrect and we can reopen if needed!

**Closed by dangrous** 2024-01-10 16:35 UTC
Labels: Reviewing, Engineering, Daily, Internal
