### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] Task checkbox state incorrect for unassigned user in chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21924] opened 2023-06-30 02:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to NewDot on Chrome web with User A
2. User A creates a task within a chat with User B, assigned to User A
3. User A completes the task
4. User B signs in and opens the chat
## Expected Result:
 User B's chat should show the task with completed checkbox.
## Actual Result:
User B sees the checkbox showing as if the task is still open.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2f3cd87b-27ce-4ba3-ad7c-51fe4254d45c

https://github.com/Expensify/App/assets/43996225/d4cab977-12e8-4525-b3de-907804df0aa9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jjcoffee 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687789907864819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170f32a7e598994e4</li>
        <li>Upwork Job ID: 1675756819447054336</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-06-30 02:32
From @jjcoffee.
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Users in the same chat should see the correct task status when they log in.
### What is the root cause of that problem?
Users who are not assigned to a task do not have access to the taskReport itself, only the linked reportAction which shows the taskPreview.
We check for the task's completion state here:
https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/TaskPreview.js#L57-L59
The issue is that we are always using the taskReport since the taskReport prop will always be available, just empty in the case of the user not being assigned/having access to the taskReport.
### What changes do you think we should make in order to solve the problem?
Update the conditional to check if the prop is empty, using _.isEmpty:
const isTaskCompleted = !_.isEmpty(props.taskReport)
	? props.taskReport.stateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.taskReport.statusNum === CONST.REPORT.STATUS.APPROVED
	: props.action.childStateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.action.childStatusNum === CONST.REPORT.STATUS.APPROVED;

**Comment by jjcoffee** [comment] 2023-06-30 09:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users in the same chat should see the correct task status when they log in.

### What is the root cause of that problem?
Users who are not assigned to a task do not have access to the `taskReport` itself, only the linked `reportAction` which shows the `taskPreview`.

We check for the task's completion state here:

https://github.com/Expensify/App/blob/340411170911867fbea149f2f34dfa89671068ed/src/components/ReportActionItem/TaskPreview.js#L57-L59

The issue is that we are always using the `taskReport` since the `taskReport` prop will always be available, just empty in the case of the user not being assigned/having access to the `taskReport`. 

### What changes do you think we should make in order to solve the problem?
Update the conditional to check if the prop is empty, using `_.isEmpty`:

```
const isTaskCompleted = !_.isEmpty(props.taskReport)
	? props.taskReport.stateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.taskReport.statusNum === CONST.REPORT.STATUS.APPROVED
	: props.action.childStateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.action.childStatusNum === CONST.REPORT.STATUS.APPROVED;
```

**Comment by kadiealexander** [comment] 2023-07-03 06:41
Reproduced:

https://github.com/Expensify/App/assets/59587260/1d797aa1-934d-4640-ba4a-70218cc2ffcf

**Comment by narefyev91** [comment] 2023-07-03 07:49
Proposal from @jjcoffee looks good to me https://github.com/Expensify/App/issues/21924#issuecomment-1614421454
🎀 👀 🎀 C+ reviewed

**Comment by jjcoffee** [comment] 2023-07-04 10:23
PR coming today!

**Comment by jjcoffee** [comment] 2023-07-04 12:40
[PR](https://github.com/Expensify/App/pull/22171) ready! cc @narefyev91

**Comment by kadiealexander** [comment] 2023-07-13 05:52
I'm going OOO tomorrow for a long weekend so I need some help with payment on Friday! 

@narefyev91 could you please make sure the checklist is complete, and let us know if you're being paid via NewDot?

**Comment by kadiealexander** [comment] 2023-07-13 05:53
Thanks for the help @muttmuure!!

**Comment by narefyev91** [comment] 2023-07-13 06:33
> I'm going OOO tomorrow for a long weekend so I need some help with [payment](https://www.upwork.com/ab/applicants/1675756819447054336/hired) on Friday!
> 
> @narefyev91 could you please make sure the checklist is complete, and let us know if you're being paid via NewDot?

Hey @kadiealexander I'm from Callstack - and no needs any additional payments :-)

**Comment by narefyev91** [comment] 2023-07-13 06:38
- The PR that introduced the bug has been identified. Link to the PR - https://github.com/Expensify/App/pull/20014/
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - https://github.com/Expensify/App/pull/20014/files#r1262063857
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - no discussions
- Determine if we should create a regression test for this bug - we good to go with QA steps in the merged PR

**Comment by muttmuure** [comment] 2023-07-17 14:55
@jjcoffee paid for reporting and urgency

**Comment by muttmuure** [comment] 2023-07-23 22:45
Everyone is paid and no regression test. Closing

**Closed by muttmuure** 2023-07-23 22:45 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
