### ISSUE TITLE
[$500] Web - Login - Hitting "Enter" key does not save the password

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11413] opened 2022-09-29 11:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App on device 1 (Android App for me)
2. In the email field, enter an email address for a new account
3. Verify there’s a message saying that a Magic Link has been sent to the email address
4. Go to another device 2 (Web for me), follow the next steps on device 2!!!
5. Navigate to the email inbox of the account and open the validation email
6. Copy the link and change it to staging - > Navigate to the staging link
7. Set a password that follows the password requirements
8. Click "Enter" key

## Expected Result:
Enter key should work to save the password

## Actual Result:
Enter key does not work to save the password

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193017901-fc456e15-c7d4-4bdc-bd11-6a8e7dd00c9b.mp4

https://user-images.githubusercontent.com/93399543/193017904-5de6fc72-e647-4f2b-bc7b-79ebbb40005e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by syedsaroshfarrukhdot** [comment] 2022-09-29 16:27
### Proposal

 The issue is caused due to empty onSubmitEditing in NewPasswordForm

https://github.com/Expensify/App/blob/a0340070ebf94fe3acde872c8c0c4222edd984c3/src/pages/SetPasswordPage.js#L113-118

<img width="923" alt="Screen Shot 2022-09-29 at 9 18 26 PM" src="https://user-images.githubusercontent.com/81307212/193085229-fd953cab-1cb6-4f84-9b68-ffc8e1a41276.png">

We just simply need to set onSubmitEditing  to onSubmitEditing={this.validateAndSubmitForm} and it fixes the issue of FormSubmission on enter key press as onSubmitEditing is triggered when you click the text input submit button (from keyboard).

Solution:-
<img width="923" alt="Screen Shot 2022-09-29 at 9 21 12 PM" src="https://user-images.githubusercontent.com/81307212/193085613-63f2eef2-0ec6-4202-a9ee-733ec0ab0822.png">

After Implementing Solution :-

https://user-images.githubusercontent.com/81307212/193086697-182a1eb7-1f96-4f1b-8f98-cd72ae5f9135.mov

**Comment by marcochavezf** [comment] 2022-09-29 17:08
I noticed we have the key enter behavior on the login page, so we should also have it in this page. Thanks @syedsaroshfarrukhdot for the proposal. Applying the External label.

**Comment by marcochavezf** [comment] 2022-09-29 17:09
Hi @sobitneupane could you [review](https://github.com/Expensify/App/issues/11413#issuecomment-1262519145) this proposal?

**Comment by jliexpensify** [comment] 2022-09-29 21:37
Posted

Internal - https://www.upwork.com/ab/applicants/1575600235539378176/job-details
External - https://www.upwork.com/jobs/~016a8ee45661b0d7d7

Invited @sobitneupane

**Comment by CodeSuite1** [comment] 2022-09-30 08:03
Should I take part in it?

**Comment by CodeSuite1** [comment] 2022-09-30 08:05
like I need to be assigned this task on Upwork and will resolve this issue as I was also going through the same bugs because of  a few things now I've sorted them out and looking forward to offering my services here as well
Let me know how can I do that

**Comment by sobitneupane** [comment] 2022-09-30 09:27
@syedsaroshfarrukhdot `onSubmitEditing={() => {}}` was intentionally added in https://github.com/Expensify/App/pull/9445 PR to solve https://github.com/Expensify/App/issues/9058 issue. We have `pressOnEnter` prop set on `<Button>` in FormAlertWithSubmitButton.js. So, SetPassWord should ideally be pressed.

And the other thing, I was not able to consistently reproduce this issue. Few times it worked as expected.

**Comment by syedsaroshfarrukhdot** [comment] 2022-09-30 22:25
@sobitneupane  In PR https://github.com/Expensify/App/pull/9445 details it is mentioned the multiple submits was causing validateAndSubmitForm() to be ran multiple times, and the second time it ran, it would have this.props.userSignUp.authToken from the first request. This caused changePasswordAndSignIn() to be triggered from an invalid state and put the UI into a position where it couldn't fetch all the reports. Since the reports couldn't fully load, it was stuck at a loading spinner.

So it was added this way intentionally to fix that issue since changePasswordAndSignIn() has been deprecated and we are not using it anymore so adding onSubmitEditing={this.validateAndSubmitForm} is safe and it  fixes this issue also. 

I tested it for the issue https://github.com/Expensify/App/issues/9058 after adding onSubmitEditing={this.validateAndSubmitForm} it doesn't cause any problem again of Endless loading spinner.

Video After Adding   onSubmitEditing={this.validateAndSubmitForm} and it fixes the enter key save password issue also.

https://user-images.githubusercontent.com/81307212/193362932-416d0129-b415-4302-b587-837f4f27d8ee.mov

We are also using onSubmitEditing to handle `Enter Key` in `PasswordForm.js` 

https://github.com/Expensify/App/blob/main/src/pages/signin/PasswordForm.js#L155

<img width="923" alt="Screen Shot 2022-10-01 at 3 15 29 AM" src="https://user-images.githubusercontent.com/81307212/193363707-2ed98775-8d13-453e-bc34-fcf6f4a7e553.png">

And if we still prefer not to use onSubmitEditing to handle enter key we need to pass prop enterKeyEventListenerPriority={1} on button in FormAlertWithSubmitButton.js along with pressOnEnter

This fixes the issue

<img width="923" alt="Screen Shot 2022-10-01 at 3 19 43 AM" src="https://user-images.githubusercontent.com/81307212/193364070-20581584-0ae3-40df-9333-8a5495cb3378.png">

After enterKeyEventListenerPriority={1} in FormAlertWithSubmitButton.js 

https://user-images.githubusercontent.com/81307212/193364319-d0055d86-c3ef-42f2-a510-37c65616af94.mov

I have been able to consistently reproduce this issue.

**Comment by syedsaroshfarrukhdot** [comment] 2022-10-04 23:36
### Updated Proposal
@sobitneupane as recommended by you I digged a bit more in Button component and figured that the issue

**Comment by sobitneupane** [comment] 2022-10-05 13:02
> the issue is with this.props.isFocused in Button.js

@syedsaroshfarrukhdot Your finding here looks promising.

Since the screen is focused at the start, why is the `Set Password` button not triggered?

**Comment by syedsaroshfarrukhdot** [comment] 2022-10-07 03:11
> > the issue is with this.props.isFocused in Button.js
> 
> @syedsaroshfarrukhdot Your finding here looks promising.
> 
> Since the screen is focused at the start, why is the `Set Password` button not triggered?
> 
> I dug further and found that a button with text `Continue` is also being rendered. But `this.props.isFocused` for the button is false. <img alt="Screen Shot 2022-10-05 at 18 47 25" width="1440" src="https://user-images.githubusercontent.com/25876548/194066795-5e36e3fa-1e0a-49e5-89b8-4c7c5dd442cf.png">
> 
> This might be the cause of the issue.

@sobitneupane  Yes, that is the reason the SetPassoword page loses screen focus. I looked in more depth and figured out that not only the Continue button but complete Login From is being rendered in the SetPassoword page.

<img width="1366" alt="Screen Shot 2022-10-06 at 9 42 44 PM" src="https://user-images.githubusercontent.com/81307212/194459083-e4874754-8c10-4c24-bc3a-40cd525fbda2.png">

Not sure yet, but I believe it is something to do with Stack Navigator in PublicScreens.js which is rendering SignInPage somehow in SetPasswordPage

https://github.com/Expensify/App/blob/e5d766115babfe4fed51b97e8b7f65b6bec64f21/src/libs/Navigation/AppNavigator/PublicScreens.js#L1-L44

Will be digging a bit more in depth to figure it why login form is being rendered in SetPasswordPage.js

**Comment by sobitneupane** [comment] 2022-10-11 06:53
Waiting for proposals.

**Comment by marcochavezf** [comment] 2022-10-14 17:42
> Waiting for proposals.

Changing it to `Weekly`

**Comment by sobitneupane** [comment] 2022-10-25 15:26
Waiting for proposals.

**Comment by arielgreen** [comment] 2022-11-03 20:03
Hey @jliexpensify, just a reminder to [keep the pressure on](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109) to find a contributor and get this one closed out!

**Comment by jliexpensify** [comment] 2022-11-03 21:09
@syedsaroshfarrukhdot - how did you go with your digging?

**Comment by jliexpensify** [comment] 2022-11-03 21:11
[Have also doubled the price.](https://expensify.slack.com/archives/C01GTK53T8Q/p1667509880973199)

**Comment by marcochavezf** [comment] 2022-11-07 19:16
>Will be digging a bit more in depth to figure it why login form is being rendered in SetPasswordPage.js

Hi @syedsaroshfarrukhdot, were you able to find something out? Don't hesitate to let us know if you found a dead-end! :)

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-07 21:57
Sorry for not replying after mention somehow missed the notification earlier

@marcochavezf Yeah wasn't able to find any solution to it the problem it was pretty much a dead end. As whole Login Form is being rendered in `SetPassword` Screen and I wasn't able to find  why it is happening. Maybe a bug in StackNavigator causing higher level screens to rendered in the rest of the components.

**Comment by marcochavezf** [comment] 2022-11-08 18:52
Oh I see, thanks @syedsaroshfarrukhdot, something I would like to understand is why the `SetPassword` is different from the [PasswordForm](https://github.com/Expensify/App/blob/9815d852c576355f4a3f945736860407dd351224/src/pages/signin/PasswordForm.js), because we have the "Enter" key behavior there, but not in the `SetPassword`. Would it require a different structure to avoid conflicts with the StackNavigator? cc @sobitneupane

**Comment by thesahindia** [comment] 2022-11-08 18:58
I believe we can close this issue, we are closing issues related to password as we will be moving towards #passwordless https://github.com/Expensify/App/issues/11403#issuecomment-1303955452

**Comment by jliexpensify** [comment] 2022-11-08 21:31
@marcochavezf - do you mind confirming we can close? If so, I'll get the Upworks job removed. Thanks!

**Comment by jliexpensify** [comment] 2022-11-14 19:47
Keeping open for payment to C+ as discussed: https://expensify.slack.com/archives/C02NK2DQWUX/p1668132124601409

**Comment by jliexpensify** [comment] 2022-11-15 02:39
New job post for payment: https://www.upwork.com/ab/applicants/1592242364089561088/job-details

**Comment by jliexpensify** [comment] 2022-11-15 22:48
Paid @sobitneupane and job closed.

**Closed by jliexpensify** 2022-11-15 22:48 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
