### ISSUE TITLE
mWeb - Navigation-Height of the navigation items in the Search tab did not update to 52px

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51542] opened 2024-10-27 22:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51169
## Action Performed:
1. Go to Seach tab
2. Inspect on the web/desktop
3. Hover over the LHN nav items(Expenses, Chats, Invoices....)
4. Verify that height in 52px

## Expected Result:
The height of the navigation items in the Search tab has been updated to 52px

## Actual Result:
The height of the navigation items in the Search tab is 64 px instead of 52 px

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>  

https://github.com/user-attachments/assets/a2794050-fc3f-425e-a98c-86a1c01d2dfa

![Bug6647006_1729982278876!51169-mWeb (1)](https://github.com/user-attachments/assets/2e9bb948-4526-486e-a21a-c8c5cb77a700)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-27 22:21
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by huult** [comment] 2024-10-28 05:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Height of the navigation items in the Search tab did not update to 52px

### What is the root cause of that problem?

We used the [`PopoverMenu`](https://github.com/Expensify/App/blob/main/src/pages/Search/SearchTypeMenuNarrow.tsx#L205) component to render a navigation item in the search. Inside it, `FocusableMenuItem` is used to render each item, and within `FocusableMenuItem`, `MenuItem` is utilized. The [`combinedStyle`](https://github.com/Expensify/App/blob/main/src/components/MenuItem.tsx#L449) has a `paddingVertical` value of [`12`](https://github.com/Expensify/App/blob/main/src/styles/index.ts#L1790), and the wrap title content uses a `minHeight` of [`40`](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts#L961), making the total height of each item `64`.

https://github.com/Expensify/App/blob/5103b4bd53ae74dcb301b8450f7046e82dc311d3/src/components/MenuItem.tsx#L591

and

https://github.com/Expensify/App/blob/5103b4bd53ae74dcb301b8450f7046e82dc311d3/src/components/MenuItem.tsx#L719

### What changes do you think we should make in order to solve the problem?

To resolve this issue and avoid impacting other uses of `PopoverMenu`, we should create a new parameter to update paddingVertical to 6. An example of the code change is as follows:
```diff
//.src/pages/Search/SearchTypeMenuNarrow.tsx#214
            <PopoverMenu
                ...
+                isSearchTypeMenuNarrow
            />
//.src/components/PopoverMenu.tsx#L159
    function PopoverMenu({
      ...
+     isSearchTypeMenuNarrow = false,
    }: PopoverMenuProps) {

//.src/components/PopoverMenu.tsx#L309
    <FocusableMenuItem
        ...                           
+        isSearchTypeMenuNarrow={isSearchTypeMenuNarrow}
        ...
    />
//.src/components/MenuItem.tsx#L444
function MenuItem(
    {
        ...
+        isSearchTypeMenuNarrow = false,
    }: MenuItemProps,
    ref: PressableRef,
) 
//.src/components/MenuItem.tsx#L592
    style={({pressed}) =>
        [
            containerStyle,
            combinedStyle,
+            !!isSearchTypeMenuNarrow && [styles.pv1half],
            !interactive && styles.cursorDefault,
            ...
        ] as StyleProp<ViewStyle>
    }
```

<details>
<summary>POC</summary>
- <img width="405" alt="Screenshot 2024-10-28 at 12 49 53" src="https://github.com/user-attachments/assets/b21bda70-fe60-4569-93c7-ef8b894973bb">
</details>

**Comment by trjExpensify** [comment] 2024-10-29 02:26
CC: @jayeshmangwani @s77rt @shawnborton @rafecolton from the [linked PR](https://github.com/Expensify/App/pull/51169), is this a regression to fix or missed?

**Comment by jayeshmangwani** [comment] 2024-10-29 03:49
@trjExpensify This is intentional; we [decided not to change](https://github.com/Expensify/App/pull/51169#issuecomment-2435296051) the height for the Search popover (on mobile devices Android, ios, mobile web), as it will be addressed when we update the styling for all popovers across the app.

**Comment by shawnborton** [comment] 2024-10-29 07:38
That's correct, we can just close this out. cc @Expensify/design

**Comment by dannymcclain** [comment] 2024-10-29 13:18
Agree—this is expected.

**Closed** 2024-10-29 13:42 UTC
Labels: Daily, Bug
