### ISSUE TITLE
[$500] Thread - Copy link of parent message & tap on link, parent message is not highlighted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36057] opened 2024-02-07 18:40 UTC
HOLD on https://github.com/Expensify/App/pull/30269

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Send the message
4. Long press and copy link
5. Paste it in compose and send the message
6. Tap on the link
7. Note the message is highlighted
8. Long press the message and select reply in thread
9. Send a reply
10. Long press parent message and copy link
11. Paste it in compose and send the message
12.Tap on the link
13. Note the parent message is not highlighted

## Expected Result:
In thread page, copy link of parent message and tap on link, parent message must be highlighted

## Actual Result:
In thread page, copy link of parent message and tap on link, parent message is not highlighted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/26a125ca-5992-4f30-881b-59afd40d62fd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed16923747a7ed62</li>
        <li>Upwork Job ID: 1755300519347654656</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 0</li>
<li>abdulrahuman5196 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-07 18:40
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by FitseTLT** [comment] 2024-02-07 18:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread - Copy link of parent message & tap on link, parent message is not highlighted

### What is the root cause of that problem?
We haven't passed `linkedReportAction` for `ReportActionItemParentAction`
as in 
https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/pages/home/report/ReportActionsListItemRenderer.js#L134-L135
### What changes do you think we should make in order to solve the problem?

We should pass `linkedReportActionID` for `ReportActionItemParentAction`
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-02-09 00:34
Hm.. I don't see a `Copy link` menu item in the comment action menu. Leads me to think this might be new and related to comment linking, requiring a beta or something. CC: @roryabraham @marcaaron any ideas?

**Comment by roryabraham** [comment] 2024-02-09 01:37
Yep, it's behind a beta. Putting this on HOLD for https://github.com/Expensify/App/pull/30269

**Comment by trjExpensify** [comment] 2024-02-09 10:56
Excellent, glad I asked! :)

**Comment by situchan** [comment] 2024-02-28 11:43
Same

**Comment by trjExpensify** [comment] 2024-03-08 15:24
Still held on comment linking.

**Comment by trjExpensify** [comment] 2024-03-18 10:53
Still held on comment linking.

**Comment by roryabraham** [comment] 2024-03-21 04:57
Comment linking merged, but I think we should wait for it to settle on prod and take this off HOLD next week

**Comment by trjExpensify** [comment] 2024-03-25 15:14
Makes sense. I'm going to be out until April 2nd from tomorrow. Feel free to update the labels if we're good to ship it out before then.

**Comment by FitseTLT** [comment] 2024-04-02 11:47
@roryabraham Can we move this forward? Also @situchan is OOO so need to re-assign. Thx.

**Comment by trjExpensify** [comment] 2024-04-08 14:44
Sent Rory a message!

**Comment by FitseTLT** [comment] 2024-04-08 19:04
I think this issue was created under our previous price initial of $500, may be it was decreased to $250 because u re-added the external label. WDYT @roryabraham ?

**Comment by FitseTLT** [comment] 2024-04-15 10:14
PR will be ready in 3 days

**Comment by nkdengineer** [comment] 2024-04-15 14:43
Can anyone reproduce this bug anymore?

**Comment by nkdengineer** [comment] 2024-04-15 15:22
@roryabraham @trjExpensify  In step 12:

> 12.Tap on the link

- What is the expected behavior?
1. We should navigate user to the parent report and highlight the parent message
2. User should stay in the thread report and hightlight the parent message
- I wonder this because currently, when I click on the parent message in thread report, we are navigating user to parent report

**Comment by roryabraham** [comment] 2024-04-15 21:31
> I think this issue was created under our previous price initial of $500, may be it was decreased to $250 because u re-added the external label

Fair enough - since you posted the proposal when the issue had a higher price I'll bump it back up

**Comment by roryabraham** [comment] 2024-04-15 21:32
requested retest: https://github.com/Expensify/App/issues/36057

**Comment by nkdengineer** [comment] 2024-04-15 21:56
@roryabraham Maybe the new behavior is related to https://github.com/Expensify/App/issues/39737

**Comment by nkdengineer** [comment] 2024-04-16 19:43
@roryabraham Do you have any feedback about [comment](https://github.com/Expensify/App/issues/36057#issuecomment-2057879364) and [comment](https://github.com/Expensify/App/issues/36057#issuecomment-2057932484) ?

**Comment by roryabraham** [comment] 2024-04-16 20:45
> What behavior is expected below?
We should navigate user to the parent report and highlight the parent message
User should stay in the thread report and hightlight the parent message
I wonder this because currently, in staging, when I click on the parent message in thread report, we are navigating user to parent report

I think the expected behavior is that we navigate the user to the parent report and highlight the parent message

**Comment by nkdengineer** [comment] 2024-04-16 20:53
I have a proposal to fix it [here](https://github.com/Expensify/App/issues/39737). Should I re-post it in here as the issue https://github.com/Expensify/App/issues/39737 is closed ?

**Comment by roryabraham** [comment] 2024-04-16 20:55
we should create a new issue

**Comment by nkdengineer** [comment] 2024-04-16 20:55
> we should create a new issue

We can re-open this https://github.com/Expensify/App/issues/39737

**Comment by nkdengineer** [comment] 2024-04-18 00:11
@roryabraham Can you check this [comment](https://github.com/Expensify/App/issues/36057#issuecomment-2059908124)?

**Comment by nkdengineer** [comment] 2024-04-22 05:37
@roryabraham The PR https://github.com/Expensify/App/pull/40344 can fix the bug https://github.com/Expensify/App/issues/39737 so we do not need to reopen https://github.com/Expensify/App/issues/39737

**Comment by trjExpensify** [comment] 2024-05-10 18:36
PR has conflicts, let's get those addressed and wrap this up next week!

**Comment by FitseTLT** [comment] 2024-05-13 19:56
Yep @trjExpensify The conflicting[PR](https://github.com/Expensify/App/pull/41954) has overlapped with ours and fixed it while our pr was on a review stage.

**Comment by trjExpensify** [comment] 2024-05-14 00:09
Sorry, do you mind restating that?

**Comment by trjExpensify** [comment] 2024-05-16 20:01
Oh, so if I'm following you, we can close this issue then right?

**Comment by FitseTLT** [comment] 2024-05-16 20:10
> Oh, so if I'm following you, we can close this issue then right?

Yep. We can close it but I  had already raised the pr so payment is due.

**Comment by trjExpensify** [comment] 2024-05-16 20:21
Alright, so I think we can pay 50% for the work completed to date.

**Comment by trjExpensify** [comment] 2024-05-16 21:23
Cool, payment summary as follows: 

- $250 to @FitseTLT for the partial PR
- $250 to @abdulrahuman5196 for the partial C+ review of the PR 

Offers sent!

**Comment by trjExpensify** [comment] 2024-05-17 10:46
Settled up with you both, closing!

**Closed by trjExpensify** 2024-05-17 10:46 UTC
Labels: Reviewing, External, Weekly, Bug
