### ISSUE TITLE
[HOLD for payment 2023-06-02] [$1000] white space accepted as description in Assign task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18796] opened 2023-05-11 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

1. ## Action Performed:
2. Click on FAB button -> Click on Assign task option
3. Enter description as white space
4. click on Next button

## Expected Result:  
description should be trimmed
## Actual Result:  
description not trimmed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/98c886c4-9237-4af2-993c-76e1c32ab96f

https://github.com/Expensify/App/assets/43996225/77235a51-8825-4d44-9268-08b061cccf68

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683729900378959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011652c334684162d9</li>
        <li>Upwork Job ID: 1659614646252167168</li>
        <li>Last Price Increase: 2023-05-19</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-05-11 20:30
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
leading and trailing space accepted as description and title in Assign task
### What is the root cause of that problem?
we're not trimming the title and description
### What changes do you think we should make in order to solve the problem?
We can `trim()` the title and description at the below pages
https://github.com/Expensify/App/blob/46390d6355272188cafb8e7e879bce112ba9817a/src/pages/tasks/NewTaskDetailsPage.js#L51
https://github.com/Expensify/App/blob/46390d6355272188cafb8e7e879bce112ba9817a/src/pages/tasks/NewTaskDescriptionPage.js#L50
https://github.com/Expensify/App/blob/46390d6355272188cafb8e7e879bce112ba9817a/src/pages/tasks/NewTaskTitlePage.js#L58
### What alternative solutions did you explore? (Optional)
None

**Comment by gadhiyamanan** [comment] 2023-05-12 05:31
we have similar issues which we have solved 
https://github.com/Expensify/App/issues/17485
https://github.com/Expensify/App/issues/17770
https://github.com/Expensify/App/issues/14287
https://github.com/Expensify/App/issues/18006

**Comment by pecanoro** [comment] 2023-05-12 08:20
I opened a discussion internally to see what we should do in these cases.

**Comment by strepanier03** [comment] 2023-05-12 17:46
I'm following along with the discussion. Also, I don't have the task option in my FAB, so I'll look into that for proper testing on my end.

**Comment by strepanier03** [comment] 2023-05-17 18:43
We haven't reached a decision yet but I bumped the [thread](https://expensify.slack.com/archives/C01SKUP7QR0/p1684348960781889?thread_ts=1683879413.959749&cid=C01SKUP7QR0) so we can move forward.

**Comment by strepanier03** [comment] 2023-05-18 21:33
The discussion was opened up to a wider audience today. Post in #expensify-open-source [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1684442814708029). 

If no pushback by tomorrow I'll move this forward with trimming as the goal.

**Comment by strepanier03** [comment] 2023-05-19 17:38
**Conclusion of discussion:**

We have decided to take an _**always trim**_ stance moving forward so we are free to move this to external to work on trimming the white space. 

Note: We don't want to trim white space between individual words of course.

**Comment by gadhiyamanan** [comment] 2023-05-19 17:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
leading and trailing spaces space accepted as description and title in Assign task 
### What is the root cause of that problem?
we're not trimming the title and description 
### What changes do you think we should make in order to solve the problem?
We can `trim()` the title and description at the below pages
https://github.com/Expensify/App/blob/46390d6355272188cafb8e7e879bce112ba9817a/src/pages/tasks/NewTaskDetailsPage.js#L51
https://github.com/Expensify/App/blob/46390d6355272188cafb8e7e879bce112ba9817a/src/pages/tasks/NewTaskDescriptionPage.js#L50
https://github.com/Expensify/App/blob/46390d6355272188cafb8e7e879bce112ba9817a/src/pages/tasks/NewTaskTitlePage.js#L58
### What alternative solutions did you explore? (Optional)
None

**Comment by BhuvaneshPatil** [comment] 2023-05-19 19:22
Contributor details
Your Expensify account email: bhuvaneshpatil80642@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c9c80846acbe2b2c

**Comment by sobitneupane** [comment] 2023-05-20 06:32
[Proposal](https://github.com/Expensify/App/issues/18796#issuecomment-1555019209) from @gadhiyamanan looks good.


@gadhiyamanan Please make sure to make changes in all task pages. (`TaskTitlePage` and `TaskDescriptionPage` as well)

🎀👀🎀 C+ reviewed
cc: @iwiznia

**Comment by gadhiyamanan** [comment] 2023-05-20 06:49
>Please make sure to make changes in all task pages. (TaskTitlePage and TaskDescriptionPage as well)

Ok, Thanks for the suggestion!

**Comment by gadhiyamanan** [comment] 2023-05-20 08:03
we have to pass `defaultValue=''` for the below task and description input field otherwise it will crash (in Android and IOS) if the user skips the description and we are trying to trim `undefined` value. what's your thoughts @sobitneupane ?

https://github.com/Expensify/App/blob/46390d6355272188cafb8e7e879bce112ba9817a/src/pages/tasks/NewTaskDetailsPage.js#L79-L83
https://github.com/Expensify/App/blob/46390d6355272188cafb8e7e879bce112ba9817a/src/pages/tasks/NewTaskDetailsPage.js#L86-L89

**Comment by sobitneupane** [comment] 2023-05-22 15:06
@gadhiyamanan Let's follow the existing approach. How is the situation handled is being handled in other places?

**Comment by iwiznia** [comment] 2023-05-22 16:13
> We can trim() the title and description at the below pages

@sobitneupane, @gadhiyamanan maybe it would be better to call trim inside all those methods instead of on the caller?

**Comment by gadhiyamanan** [comment] 2023-05-22 16:57
> maybe it would be better to call trim inside all those methods instead of on the caller?

In that case, We can add `trim()` to below lines  

https://github.com/Expensify/App/blob/a891b6c7770533e2b1d45b8141e04ed7f2d9a640/src/libs/actions/Task.js#L289
https://github.com/Expensify/App/blob/a891b6c7770533e2b1d45b8141e04ed7f2d9a640/src/libs/actions/Task.js#L365
https://github.com/Expensify/App/blob/a891b6c7770533e2b1d45b8141e04ed7f2d9a640/src/libs/actions/Task.js#L393
https://github.com/Expensify/App/blob/a891b6c7770533e2b1d45b8141e04ed7f2d9a640/src/libs/actions/Task.js#L401
https://github.com/Expensify/App/blob/a891b6c7770533e2b1d45b8141e04ed7f2d9a640/src/libs/actions/Task.js#L409

**Comment by iwiznia** [comment] 2023-05-22 16:59
Cool, sounds good.

**Comment by gadhiyamanan** [comment] 2023-05-23 13:38
@sobitneupane [PR](https://github.com/Expensify/App/pull/19401) is ready for review

**Comment by strepanier03** [comment] 2023-05-24 17:53
PR is merged and awaiting deploy. All good here for now.

**Comment by strepanier03** [comment] 2023-06-01 22:48
Prepping for hold removal tomorrow.

----

@gadhiyamanan - I have hired you for the job in Upwork. I will pay the reporting bonus for this job in the one I hired you for so we don't have to make a second job, if that's okay. The total with speed bonus will be $1750. 

@sobitneupane - I've hired you as well. Feel free to complete the checklist and I'll update it and create the reg test GH if needed, then do the pay out.

Back tomorrow 👋

**Comment by sobitneupane** [comment] 2023-06-05 08:46
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/17992

> * [x]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/17992#issuecomment-1576371528

> * [x]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1685954728540999

> * [x]  [@sobitneupane] Determine if we should create a regression test for this bug.

I don't think separate regression test will be required. QA should make sure that white space are not accepted in any text input.

**Comment by strepanier03** [comment] 2023-06-05 21:18
Awesome, thank you for that @sobitneupane. 

I have paid everyone and finished off the checklist. Closing this out now. 

Fantastic job everyone!

**Closed by strepanier03** 2023-06-05 21:18 UTC
Labels: External, Daily, Task, Awaiting Payment, Bug
