### ISSUE TITLE
[$250] Taxes - RBR is present in expense preview but no error or violation when tax rate is invalid

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39798] opened 2024-04-07 15:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-13
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/39707
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Admin and employee are in the same Collect workspace.
- The Collect workspace has several tax rates.

1. Go to staging.new.expensify.com
2. [Employee] Go to workspace chat.
3. [Employee] Create manual request with a tax rate in workspace chat.
4. [Admin] On Old Dot, delete the tax rate selected in Step 3.
5. [Employee] Go to Settings > About > Troubleshoot > Clear cache and restart > Reset and refresh (relogin can also be done).
6. [Employee] Navigate to the workspace chat and transaction thread with invalid tax rate.

## Expected Result:
There will be an error or violation under tax rate to indicate that the tax rate is no longer valid.

## Actual Result:
There is RBR in the expense preview in the workspace chat, but there is no error message or violation for the invalid tax rate in the transaction thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b36cda37-e588-4c0e-944a-7b385487a34e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e4229ab6da1ceae</li>
        <li>Upwork Job ID: 1779881866618400768</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-07 15:11
We think this issue might be related to the #collect project.

**Comment by nkdengineer** [comment] 2024-04-08 04:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is RBR in the expense preview in the workspace chat, but there is no error message or violation for the invalid tax rate in the transaction thread

### What is the root cause of that problem?
We don't get the error for tax field and pass it to `MenuItemWithTopDescription` as we do for other fields like `tag`, ... 

https://github.com/Expensify/App/blob/f1502291a14d4e15e04249b241109f146bdb512f/src/components/ReportActionItem/MoneyRequestView.tsx#L442

https://github.com/Expensify/App/blob/f1502291a14d4e15e04249b241109f146bdb512f/src/components/ReportActionItem/MoneyRequestView.tsx#L427-L428
### What changes do you think we should make in order to solve the problem?
We should get the error for tax field via `getErrorField` function and pass `brickRoadIndicator` and `error` prop into 
`MenuItemWithTopDescription` for tax field here

```
brickRoadIndicator={getErrorForField('tax') ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : undefined}
error={getErrorForField('tax')}
```

https://github.com/Expensify/App/blob/f1502291a14d4e15e04249b241109f146bdb512f/src/components/ReportActionItem/MoneyRequestView.tsx#L442

OPTIONAL: We can show the error the both tax code and tax amount.
### What alternative solutions did you explore? (Optional)
NA

**Comment by s77rt** [comment] 2024-04-16 13:13
@nkdengineer Thanks for the proposal. Your RCA is correct and the solution looks good to me, let's fix the bug for all affected fields.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/39798#issuecomment-2041834376)

**Comment by stitesExpensify** [comment] 2024-04-16 18:41
LGTM!

**Comment by nkdengineer** [comment] 2024-04-17 05:45
@s77rt The PR is [here](https://github.com/Expensify/App/pull/40334).

**Comment by s77rt** [comment] 2024-05-02 00:08
Yes but let's give this another test since QA team reported this as still reproducible in the PR https://github.com/Expensify/App/pull/40334#issuecomment-2070927342

cc @nkdengineer

**Comment by nkdengineer** [comment] 2024-05-02 03:53
@s77rt Replied in the PR. It's fixed for me on the latest main. For staging, my account doesn't have violation permission so I can't test.

**Comment by muttmuure** [comment] 2024-05-08 07:14
Going to close this as fixed

**Comment by muttmuure** [comment] 2024-05-08 07:14
Everyone is paid out

**Closed by muttmuure** 2024-05-08 07:14 UTC
Labels: Reviewing, External, Weekly, Bug
