### ISSUE TITLE
[HOLD 19504] - Web - GBR doesn't disappear on cancelled task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22291] opened 2023-07-05 18:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'FAB' icon/ 'Actions' icon
2. Click on 'Assign task' button
3. Enter title & click on 'Next' button
4. Add assignee user B
5. Click on 'Confirm task' button
6. Switch to the tab where account B is signed in
7. Open the task report item on LHN
8. Click on three dots
9. Click on 'Cancel' button

## Expected Result:
GBR should disappear since the task is archived

## Actual Result:
 GBR persists

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/092a405d-81ef-4a49-b015-1daf337148cd

https://github.com/Expensify/App/assets/93399543/a52241fb-37d2-4388-b3e9-e5602d79ac65

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688458540934149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2023-07-05 18:53
We're redesigning the canceled task here https://github.com/Expensify/App/issues/19504, this should hold on that

**Comment by thienlnam** [comment] 2023-07-05 18:56
Actually, this appears to be a dupe of https://github.com/Expensify/App/issues/22029

**Closed by thienlnam** 2023-07-05 18:56 UTC
Labels: Daily, Bug
