### ISSUE TITLE
[Payment due][$500] Distance - Distance rate shows undefined when both workspace and request are created offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30801] opened 2023-11-02 21:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go offline.
3. Create a workspace (do not change workspace settings like name).
4. Go to the workspace chat.
5. Go to + > Request money > Distance.
6. Proceed to confirmation page.

## Expected Result:
The currency for distance rate in Distance row shows the default currency of the workspace.

## Actual Result:
The currency for distance rate in Distance row shows undefined.
If the workspace is created in offline mode and the name is changed, it shows the default currency instead of undefined.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/505b146a-33f9-4055-9a02-6d52f2d225e4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175de9ce3ccbd5187</li>
        <li>Upwork Job ID: 1720189005781348352</li>
        <li>Last Price Increase: 2023-11-09</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27606634</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by brandond98** [comment] 2023-11-02 21:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance rate showing us undefined when creating a workspace and distance expense offline 

### What is the root cause of that problem?

When offline the `currency parameter` passed to the `getDistanceMerchant` function is undefined

### What changes do you think we should make in order to solve the problem?

Add a check to the currencySymbol variable checking if currency is falsy, if it is then provide a default value:

```
const getDistanceMerchant = (hasRoute, distanceInMeters, unit, rate, currency, translate, toLocaleDigit) => {
    const distanceInUnits = hasRoute ? getRoundedDistanceInUnits(distanceInMeters, unit) : translate('common.tbd');

    const distanceUnit = unit === CONST.CUSTOM_UNITS.DISTANCE_UNIT_MILES ? translate('common.miles') : translate('common.kilometers');
    const singularDistanceUnit = unit === CONST.CUSTOM_UNITS.DISTANCE_UNIT_MILES ? translate('common.mile') : translate('common.kilometer');
    const unitString = distanceInUnits === 1 ? singularDistanceUnit : distanceUnit;
    const ratePerUnit = rate ? PolicyUtils.getUnitRateValue({rate}, toLocaleDigit) : translate('common.tbd');
    const currencySymbol = currency ? CurrencyUtils.getCurrencySymbol(currency) || `${currency} ` : CurrencyUtils.getCurrencySymbol('USD');

    return `${distanceInUnits} ${unitString} @ ${currencySymbol}${ratePerUnit} / ${singularDistanceUnit}`;
};
```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by kadiealexander** [comment] 2023-11-07 05:15
@eVoloshchak bump!

**Comment by eVoloshchak** [comment] 2023-11-07 14:16
I think we should proceed with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/30801#issuecomment-1791796445)

While @brandond98's [proposal](https://github.com/Expensify/App/issues/30801#issuecomment-1791596354) would resolve this particular issue, it's fixing a symptom, not the root cause
Adding a default currency in optimistic data when creating a workspace is a better, more general approach

🎀👀🎀 C+ reviewed!

**Comment by robertjchen** [comment] 2023-11-10 08:24
Agreed, @dukenv0307 's approach is better in setting the optimistic data when creating a workspace 👍

**Comment by kadiealexander** [comment] 2023-12-20 03:27
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@eVoloshchak] The PR that introduced the bug has been identified. Link to the PR: 
- [ ] [@eVoloshchak] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 
- [ ] [@eVoloshchak] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 
- [ ] [@eVoloshchak] Determine if we should create a regression test for this bug.
- [ ] [@eVoloshchak] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon: https://github.com/Expensify/Expensify/issues/352462

**Comment by kadiealexander** [comment] 2023-12-20 03:28
Payouts due:

- [ ] Contributor: $500 @dukenv0307
- [ ] Contributor+: $500 @eVoloshchak

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/jobs/~0175de9ce3ccbd5187).

**Comment by kadiealexander** [comment] 2023-12-21 02:03
@eVoloshchak please action the bugzero checklist so we can close this one out :)

**Comment by kadiealexander** [comment] 2023-12-22 02:42
Noting that I'm on leave from tomorrow until Jan 8th and will check in on my return. @eVoloshchak please feel free to request payment via manual request once the BugZero checklist is done from your side.

**Comment by eVoloshchak** [comment] 2023-12-22 14:36
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that introduced this issue, it's an edge case missed during the initial implementation
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed here
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No_

**Comment by eVoloshchak** [comment] 2023-12-22 14:38
**Regression Test Proposal**

1. Go offline
2. Create a new workspace
3. Go to policy expense chat of the workspace
4. Create a distance request
5. Select the start and finish address 
6. Click Next
7. Verify that the default currency is displayed in the Distance row instead of `undefined`

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment] 2023-12-26 16:41
$500 payment approved for @eVoloshchak based on [this comment](https://github.com/Expensify/App/issues/30801#issuecomment-1863792447).

**Comment by robertjchen** [comment] 2023-12-28 11:23
Any remaining steps here before we can close this out?

**Comment by robertjchen** [comment] 2024-01-06 07:04
Closing this out for now, please re-open if we need to do anything else here.

**Closed by robertjchen** 2024-01-06 07:04 UTC
Labels: Reviewing, External, Weekly, Bug
