### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500] Video - App crashes when opening video in full screen while it is still loading

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37710] opened 2024-03-05 03:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Send a video.
4. Play the video.
5. Click on the expand button while the video is still loading.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/05c73188-4fc2-4cec-9dd6-7d523911a96e

[Bug6402236_1709602613462!video_crash.txt](https://github.com/Expensify/App/files/14489827/Bug6402236_1709602613462.video_crash.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010dfc1052e95c8db2</li>
        <li>Upwork Job ID: 1764961446011293696</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by m-natarajan** [comment] 2024-03-05 03:11
We think that this bug might be related to #vip-vsb
cc @quinthar

**Comment by m-natarajan** [comment] 2024-03-05 03:12
@techievivek FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by abzokhattab** [comment] 2024-03-05 03:29
not reproducible from my side on the latest main

**Comment by ShridharGoel** [comment] 2024-03-05 04:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when trying to expand video while it is initially loading.

### What is the root cause of that problem?
`currentVideoPlayerRef.current` is null in `bindFunctions`.

### What changes do you think we should make in order to solve the problem?
Null check needs to be added.
```
const bindFunctions = useCallback(() => {
        if (currentVideoPlayerRef.current == null) {
            return
        }
        currentVideoPlayerRef.current._onPlaybackStatusUpdate = handlePlaybackStatusUpdate;
        currentVideoPlayerRef.current._onFullscreenUpdate = handleFullscreenUpdate;
        // update states after binding
        currentVideoPlayerRef.current.getStatusAsync().then((status) => {
            handlePlaybackStatusUpdate(status);
        });
    }, [currentVideoPlayerRef, handleFullscreenUpdate, handlePlaybackStatusUpdate]);
```

**Comment by techievivek** [comment] 2024-03-05 05:19
Hmm, I am still able to reproduce it.

**Comment by techievivek** [comment] 2024-03-05 05:19
It doesn't need to be a blocker.

**Comment by bernhardoj** [comment] 2024-03-05 06:04
It's a regression from https://github.com/Expensify/App/issues/36833. The attachment carousel is supposed to use the shared video ref, but because this `useEffect` is added, the video ref is overwritten with null.
https://github.com/Expensify/App/blob/eb4683d83613c4dadb47bd5cd6cde0fe6766152b/src/components/VideoPlayer/BaseVideoPlayer.js#L147-L149

**Comment by techievivek** [comment] 2024-03-05 10:34
I mainly demoted it to NAB because it's not affecting any main flow and is related to a new feature. But if you can review the proposal quickly and merge it, I am happy to CP it to staging.

**Comment by bernhardoj** [comment] 2024-03-05 10:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crash when pressing the video player preview expand button.

### What is the root cause of that problem?
It's a regression from https://github.com/Expensify/App/issues/36833. The attachment carousel is supposed to use the shared video ref set by `shareVideoPlayerElements`, but because this `useEffect` is added, the video ref is overwritten with null whenever the video player in an attachment carousel is opened.
https://github.com/Expensify/App/blob/eb4683d83613c4dadb47bd5cd6cde0fe6766152b/src/components/VideoPlayer/BaseVideoPlayer.js#L147-L149

And it will crash in `bindFunctions` because the ref is null.
https://github.com/Expensify/App/blob/9c49ab65db3f40e719c75516d5655f11b68c0f87/src/components/VideoPlayer/BaseVideoPlayer.js#L138-L145

`bindFunctions` is only called for the shared video player.
https://github.com/Expensify/App/blob/9c49ab65db3f40e719c75516d5655f11b68c0f87/src/components/VideoPlayer/BaseVideoPlayer.js#L160-L170

### What changes do you think we should make in order to solve the problem?

Update the `useEffect` to not set the ref when it uses a shared video player.
```
useEffect(() => {
    if (shouldUseSharedVideoElement) {
        return;
    }
    currentVideoPlayerRef.current = videoPlayerRef.current;
}, [url, currentVideoPlayerRef]);
```

**Comment by techievivek** [comment] 2024-03-05 11:00
@aimane-chnaif Can you please review the proposals here, I think we can CP the fix.

**Comment by techievivek** [comment] 2024-03-05 11:38
I added the blocker label back because it's a crash issue, and although this is a relatively new feature, crashing the app is not good and should be fixed with priority.

**Comment by abzokhattab** [comment] 2024-03-05 11:40
I am still not able to reproduce it, is there a specific step I am missing @aimane-chnaif ?

https://github.com/Expensify/App/assets/59809993/deee6873-1e6d-4013-9b0b-65697c6abcbe

**Comment by bernhardoj** [comment] 2024-03-05 11:50
@aimane-chnaif it happens the second time because we set the video player ref to null when the carousel is unmounted. (added from this PR https://github.com/Expensify/App/pull/37386)

https://github.com/Expensify/App/blob/9411a08168d53df44a957fd8bb86fd9a363b25b4/src/components/Attachments/AttachmentView/index.js#L118-L127

It's to fix https://github.com/Expensify/App/issues/37142, but again, we should only do that when `shouldUseSharedVideoElement` is false as mentioned in my proposal [here](https://github.com/Expensify/App/issues/36955#issuecomment-1955915574) (of another issue that has the same root cause as #37142).

The point is, we don't want to mutate the video player ref when it's a shared video player element.

**Comment by abzokhattab** [comment] 2024-03-05 11:50
I have tried it on staging and it's still working fine, if you do not mind  can you please send me the video you are using in the test

**Comment by bernhardoj** [comment] 2024-03-05 11:57
Without fixing [this](https://github.com/Expensify/App/issues/37710#issuecomment-1978556850), yeah.

**Comment by bernhardoj** [comment] 2024-03-05 12:19
> It is not regression. The crash exists even without these changes, just during the second opening

The crash on the second opening is from https://github.com/Expensify/App/pull/37386, but the first crash is from your PR.

> please update proposal to cover that case.

Updated my proposal.

**Comment by techievivek** [comment] 2024-03-05 13:42
@bernhardoj Can you please push a PR for this ASAP, so we can CP it.

**Comment by jeremy-croff** [comment] 2024-03-05 14:33
My PR got linked and I agree with @bernhardoj, I think the comment on PR should be updated because we only want to clean up the refs during upload flow when the in memory video gets closed, but seeing now the video is also in attachment for expanded flow was the miss.

**Comment by jeremy-croff** [comment] 2024-03-05 15:01
I reviewed the branches separately to confirm the crash did not occur independently but rather as a merge conflict since the PRs went in roughly simultaneously.

Thanks for looking into it, @bernhardoj

**Comment by abekkala** [comment] 2024-03-07 14:40
### PAYMENT SUMMARY FOR MAR 13

- Fix:@bernhardoj [$500 - if no regressions] [Offer Link](https://www.upwork.com/nx/wm/workroom/36588978/overview)
- PR Review: @aimane-chnaif [$500 - if no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/101262373)
please complete checklist above

**Comment by abekkala** [comment] 2024-03-11 19:57
### PAYMENT SUMMARY FOR MAR 14

- Fix: @bernhardoj [$500 - if no regressions] [Offer Link ](https://www.upwork.com/nx/wm/offer/101328164)
- PR Review: @aimane-chnaif  [$500 - if no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/101328194)

**Comment by abekkala** [comment] 2024-03-14 20:05
wow - melvin, you're pretty late. I already took care of this!

**Comment by abekkala** [comment] 2024-03-14 20:07
@aimane-chnaif  payment sent and contract ended - thank you! 🎉

**Closed** 2024-03-14 20:07 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
