### ISSUE TITLE
[$500] Conversation - "Chat Skeleton" is blinking on Staging and Chat crashes on PROD site

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28799] opened 2023-10-04 11:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a specific account ([emilio.utest@gmail.com](mailto:emilio.utest@gmail.com))
3. Go to "I am user B" chat (It is an unavailable workspace chat)

## Expected Result:
User expects the chat to load normally or some type of message appear stating that the chat can no longer be accesed

## Actual Result:
The chat never loads, the "Chat skeleton" keeps on blinking and on the PROD site the conversation crashes the site and forces the user to relogin.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.77-2

**Reproducible in staging?:** Y

**Reproducible in production?:** No, on PROD the chat Crashes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/8926fdb0-6fb8-4a38-ad6b-303c1c8082fc

https://github.com/Expensify/App/assets/115492554/e1b87cad-7b82-42e0-9860-23960ab33ba7

[utest-dl.s3.amazonaws.com_12102_26469_432782_6224057_bugAttachment_Bug6224057_1696369362991%21Logs_from_prod_site.txt_X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231004T110923Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Cr.txt](https://github.com/Expensify/App/files/12802562/utest-dl.s3.amazonaws.com_12102_26469_432782_6224057_bugAttachment_Bug6224057_1696369362991.21Logs_from_prod_site.txt_X-Amz-Algorithm.AWS4-HMAC-SHA256.X-Amz-Date.20231004T110923Z.X-Amz-SignedHeaders.host.X-Amz-Expires.86400.X-Amz-Cr.txt)

[utest-dl.s3.amazonaws.com_12102_26469_432782_6224057_bugAttachment_Bug6224057_1696369363099%21Logs_on_staging.txt_X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231004T110908Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Creden.txt](https://github.com/Expensify/App/files/12802563/utest-dl.s3.amazonaws.com_12102_26469_432782_6224057_bugAttachment_Bug6224057_1696369363099.21Logs_on_staging.txt_X-Amz-Algorithm.AWS4-HMAC-SHA256.X-Amz-Date.20231004T110908Z.X-Amz-SignedHeaders.host.X-Amz-Expires.86400.X-Amz-Creden.txt)

**Expensify/Expensify Issue URL:**

**Issue reported by:**  Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01544895bdb4802211</li>
        <li>Upwork Job ID: 1709526511894474752</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-04 11:11
Not repro on Prod

https://github.com/Expensify/App/assets/115492554/8ff34f28-a38a-459e-b38a-c2261bcb0a99

**Comment by mountiny** [comment] 2023-10-04 11:37
this is probably whats causing the crash
```
18:42:11.952 react-dom.production.min.js:186 TypeError: Cannot read properties of undefined (reading 'participantAccountIDs')
    at Za (ReportUtils.js:660:19)
    at Ba (ReportUtils.js:856:13)
    at Object.Va (ReportUtils.js:887:39)
    at ReportActionCompose.js:153:15
    at Object.useMemo (react-dom.production.min.js:182:189)
    at t.useMemo (react.production.min.js:25:208)
    at Ui (ReportActionCompose.js:152:48)
    at br (react-dom.production.min.js:166:137)
    at ys (react-dom.production.min.js:289:386)
    at fl (react-dom.production.min.js:279:389)
```

**Comment by mountiny** [comment] 2023-10-04 11:38
I am not sure how to treat this, we dont have access to the account you have linked for testing, seems like production has crash and staging handles this better

**Comment by mountiny** [comment] 2023-10-04 20:28
@dukenv0307 I think `report &&` this is safe enough isnt it? 

I am not sure about this ad deploy blocker, seems more so as something odd with this specific account for testing

I am going to demote this now, but leave this open for furhter investigation, if there are better repo steps not related to that specific account maybe

**Comment by alexpensify** [comment] 2023-10-06 22:42
To confirm, should the proposal here be reviewed, or wait for more proposals? Thanks!

**Comment by alexpensify** [comment] 2023-10-11 20:48
Still waiting for proposals here

**Comment by alexpensify** [comment] 2023-10-13 17:30
Still waiting for proposals. If no movement next week, I'll start asking around for help.

**Comment by alexpensify** [comment] 2023-10-16 23:34
Still waiting for proposals

**Comment by alexpensify** [comment] 2023-10-18 22:01
We need proposals here

**Comment by akamefi202** [comment] 2023-10-19 19:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Chat Skeleton" is blinking on Staging and Chat crashes on PROD site.

### What is the root cause of that problem?
In my experience, blinking loop error occurs when the back-end returns an empty `reportActions` array on `OpenReport` API Request.
This is unexpected error from the back-end because `reportActions` array usually contains at least one item("Created").

https://github.com/Expensify/App/blob/20cd5229450dd8ca08542e509fa4ce5c4c3000fb/src/pages/home/ReportScreen.js#L166

In more details, if `reportActions` array is empty, the value of `isLoadingInitialReportActions` is equal to `reportMetadata.isLoadingReportActions`.

https://github.com/Expensify/App/blob/20cd5229450dd8ca08542e509fa4ce5c4c3000fb/src/pages/home/ReportScreen.js#L425-L426

https://github.com/Expensify/App/blob/20cd5229450dd8ca08542e509fa4ce5c4c3000fb/src/pages/home/ReportScreen.js#L439

By the value of `isLoadingInitialReportActions`, the report screen shows skeleton view or report actions view.
If the value of `isLoadingInitialReportActions` is changed from `false` to `true`, it mounts skeleton view.
If the value is changed from `true` to `false`, it mounts report actions view.

https://github.com/Expensify/App/blob/fd04739bd20339982c45240ce64e862c75158e39/src/pages/home/report/ReportActionsView.js#L89

When `ReportActionsView` component mounts, it calls `OpenReport` function to get data such as `reportActions` array.

https://github.com/Expensify/App/blob/9ec687612d23a054f39062c99692effc7be6fb94/src/libs/actions/Report.js#L515

https://github.com/Expensify/App/blob/9ec687612d23a054f39062c99692effc7be6fb94/src/libs/actions/Report.js#L481

Inside `OpenReport` function, it sets `reportMetadata.isLoadingReportActions` as `true` in optimistic data and `false` in failure data.
And this updates the value of `isLoadingInitialReportActions` directly and it causes limitless mounting of `ReportActionsView` component.

Because mounting of `ReportActionsView` component calls `OpenReport` function again.
And `OpenReport` function causes another mounting by updating `isLoadingInitialReportActions`.

Usually, this doesn't happen because `reportActions` array has more than one item at least.
And it keeps the value of `isLoadingInitialReportActions` as `false`.
So that `ReportActionsView` doesn't mount again, although `OpenReport` function is called.

### What changes do you think we should make in order to solve the problem?
This is an error from the back-end but we might add an error handler for this.

```
errorFields: {
    openReport: ErrorUtils.getMicroSecondOnyxError('report.genericOpenReportFailureMessage'),
},
```
We can add `openReport` error if `OpenReport` API Request is failed.
Of course, we should clear this error if the request is succeeded.

https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/pages/home/ReportScreen.js#L386-L393

And by updating above code part, we can show appropriate error message if there is `openReport` error & `reportActions` array is empty.
As a result, we can break the loop and the error message will be shown in the report screen.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by alexpensify** [comment] 2023-10-20 21:11
@fedirjh - can you review if this proposal will fix this issue? Thanks!

**Comment by akamefi202** [comment] 2023-10-21 14:29
@fedirjh I'm not able to reproduce this bug.
As you can see in reproduction steps, this error is shown in very specific situation.
I found this error while I was working on other issue, but we fixed the problem from back-end side in that case.

I think the reporter can confirm response of OpenReport API Request using emilio.utest@gmail.com and "I am user B" user.
I don't have access to emilio.utest@gmail.com so I can't follow reproduction steps.

**Comment by madmax330** [comment] 2023-10-25 13:37
@izarutskaya can you check if this is happening? If it's not let's close this out.

**Comment by madmax330** [comment] 2023-11-01 14:51
I'm just going to close this out.

**Closed by madmax330** 2023-11-01 14:51 UTC
Labels: Engineering, Daily, Internal, Bug
