### ISSUE TITLE
[HOLD for payment 2023-12-26] [$500] Web - Chat - Workspace avatar is greyed out in the conversation report preview

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32984] opened 2023-12-13 16:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a NewDot workspace if you don't already have one.
2. Open the workspace chat for your workspace.
3. Press the +, Request Money, then Distance and complete a distance request.

## Expected Result:
Workspace avatar is visible in the conversation report preview

## Actual Result:
Workspace avatar is greyed out in the conversation report preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/21d92d12-6b0a-4a04-87f5-2d03b30d0c6c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d0b71872c14469e</li>
        <li>Upwork Job ID: 1735260103087415296</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-12-13 16:42
@kbecciv Can you confirm this problem with new workspace?

**Comment by NikkiWines** [comment] 2023-12-13 19:46
Confirmed this isn't happening on prod, and is happening on staging and dev. It's occurring even if the backend is pointed to the commit before the merge commit for https://github.com/Expensify/Web-Expensify/pull/40008 so not tied to the backend PR that was tagged. 

It looks like it's most likely the result of https://github.com/Expensify/App/pull/32546 cc: @mountiny @kubabutkiewicz @shubham1206agra

The simplest solution to this is just to use `||` instead of `??` [here](https://github.com/Expensify/App/blob/904cf5635b819971b7b24bc78c3e516beea21239/src/libs/ReportUtils.ts#L1214)

**Comment by NikkiWines** [comment] 2023-12-13 20:15
Yep, I'll apply your solution to my PR @ishpaul777 and you can be compensated for providing a valid solution here

**Comment by NikkiWines** [comment] 2023-12-13 20:17
@laurenreidexpensify can we issue payment to @ishpaul777 for providing the solution to this deploy blocker please

**Comment by laurenreidexpensify** [comment] 2023-12-14 11:26
Will do, following the process where this is on prod for 7 days

**Comment by laurenreidexpensify** [comment] 2023-12-14 11:27
@ishpaul777 pls apply to the job in Upwork thanks [upwork.com/jobs/~014d0b71872c14469e](https://www.upwork.com/jobs/~014d0b71872c14469e)

**Comment by mountiny** [comment] 2023-12-14 11:42
Since it was internal person applying the fix and not the contributor we usually go with 25% of the original reward so that would be $125 to @ishpaul777

**Comment by cubuspl42** [comment] 2023-12-14 11:52
Reproduced on latest `main`. Affects iOS Native too, although I couldn't reproduce this on Android Native. Weird.

PR reviewed & approved.

**Comment by Julesssss** [comment] 2023-12-14 16:48
This is showing on the latest checklist as I didn't remove the label. This is now resolved and awaiting payment.

**Comment by laurenreidexpensify** [comment] 2023-12-18 10:47
Prod for 7 days will be Dec 21st

**Comment by bfitzexpensify** [comment] 2023-12-26 14:53
Offer sent @ishpaul777

**Comment by bfitzexpensify** [comment] 2023-12-26 15:25
Also, @ishpaul777 can you please complete the checklist in https://github.com/Expensify/App/issues/32984#issuecomment-1861977776? Thanks!

**Comment by bfitzexpensify** [comment] 2023-12-26 16:28
Cool, that seems fair to me. OK, let's close this one out then.

**Closed by bfitzexpensify** 2023-12-26 16:28 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
