### ISSUE TITLE
[$250] [HOLD for payment 2024-08-07] [HOLD for payment 2024-08-05] Room - System message for clearing room description is copied differently

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45522] opened 2024-07-16 20:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4728014
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat > Room
3. Create a room
4. Click on the report header
5. Click Room description
6. Enter description and save it
7. Click Room description again
8. Clear description and save it
9. Go back to room chat
10. Right click on "set the room description to:" system message > Copy to clipboard
11. Paste the content in the composer

## Expected Result:
The copied content should be consistent with the room description system message

## Actual Result:
The room description system message is "set the room description to: "
The copied content is "cleared the room description"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4763fc8e-ec8c-4a18-8e65-957a5109bcaf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01db9b6412780cbcba</li>
        <li>Upwork Job ID: 1821275096672049251</li>
        <li>Last Price Increase: 2024-08-07</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-07-16 20:20
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-07-16 20:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room - System message for clearing room description is copied differently

### What is the root cause of that problem?
Inconsistency between how the report action is displayed here
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ReportActionItem.tsx#L652-L653
and how copyied to clipboard
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L366-L367
### What changes do you think we should make in order to solve the problem?

We need to copy to clipboard same as we are displaying the report action  here
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ReportActionItem.tsx#L652-L653

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by FitseTLT** [comment] 2024-07-16 20:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room - System message for clearing room description is copied differently

### What is the root cause of that problem?
For `UPDATE_ROOM_DESCRIPTION` type report action, there is an inconsistency between how the report action is displayed as in here
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ReportActionItem.tsx#L652-L653
and how text is copied to clipboard
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L366-L367
### What changes do you think we should make in order to solve the problem?

We need to copy to clipboard same as we are displaying the `UPDATE_ROOM_DESCRIPTION` type report action as in  here
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ReportActionItem.tsx#L652-L653
by adding condition for `UPDATE_ROOM_DESCRIPTION` type report action
here 
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L420-L421

```
else if (reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ROOM_CHANGE_LOG.UPDATE_ROOM_DESCRIPTION) {
                    const originalMessage = ReportActionsUtils.getOriginalMessage(reportAction);

                    const message = `${Localize.translateLocal('roomChangeLog.updateRoomDescription')} ${(originalMessage as OriginalMessageChangeLog)?.description}`;

                    Clipboard.setString(message);
}
```

### What alternative solutions did you explore? (Optional)
We can also alternatively change what we are diplaying in `ReportActionItem` to be the same as the `cleared ..` message by setting `message` to be `reportAction.message` (same as the value we use to copy to clipboard now) here 
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ReportActionItem.tsx#L651-L653

**Comment by FitseTLT** [comment] 2024-07-16 20:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room - System message for clearing room description is copied differently

### What is the root cause of that problem?
For `UPDATE_ROOM_DESCRIPTION` type report action, there is an inconsistency between how the report action is displayed as in here
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ReportActionItem.tsx#L652-L653
and how text is copied to clipboard
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L366-L367
### What changes do you think we should make in order to solve the problem?

We need to copy to clipboard same as we are displaying the `UPDATE_ROOM_DESCRIPTION` type report action as in  here
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ReportActionItem.tsx#L652-L653
by adding condition for `UPDATE_ROOM_DESCRIPTION` type report action
here 
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L420-L421

```
else if (reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ROOM_CHANGE_LOG.UPDATE_ROOM_DESCRIPTION) {
                    const originalMessage = ReportActionsUtils.getOriginalMessage(reportAction);

                    const message = `${Localize.translateLocal('roomChangeLog.updateRoomDescription')} ${(originalMessage as OriginalMessageChangeLog)?.description}`;

                    Clipboard.setString(message);
}
```

### What alternative solutions did you explore? (Optional)
We can also alternatively change what we are diplaying in `ReportActionItem` to be the same as the `cleared ..` message , which is the same as the value we use to copy to clipboard now here 
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L420-L421
by setting the `message` here
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ReportActionItem.tsx#L651-L653

**Comment by FitseTLT** [comment] 2024-07-16 20:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room - System message for clearing room description is copied differently

### What is the root cause of that problem?
For `UPDATE_ROOM_DESCRIPTION` type report action, there is an inconsistency between how the report action is displayed as in here
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ReportActionItem.tsx#L652-L653
and how text is copied to clipboard
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L366-L367
### What changes do you think we should make in order to solve the problem?

We need to copy to clipboard same as we are displaying the `UPDATE_ROOM_DESCRIPTION` type report action as in  here
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ReportActionItem.tsx#L652-L653
by adding condition for `UPDATE_ROOM_DESCRIPTION` type report action
here 
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L420-L421

```
else if (reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ROOM_CHANGE_LOG.UPDATE_ROOM_DESCRIPTION) {
                    const originalMessage = ReportActionsUtils.getOriginalMessage(reportAction);

                    const message = `${Localize.translateLocal('roomChangeLog.updateRoomDescription')} ${(originalMessage as OriginalMessageChangeLog)?.description}`;

                    Clipboard.setString(message);
}
```

### What alternative solutions did you explore? (Optional)
We can also alternatively change what we are diplaying in `ReportActionItem` to be the same as the `cleared ..` message , which is the same as the value we use to copy to clipboard now as in here 
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L366-L367


so we can set the `message` to it here 
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/home/report/ReportActionItem.tsx#L651-L653

**Comment by nkdengineer** [comment] 2024-07-17 07:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The room description system message is "set the room description to: "
The copied content is "cleared the room description"

### What is the root cause of that problem?
We always display the message `set the room description to:` in LHN and report action even we clear the description.

https://github.com/Expensify/App/blob/52b8fddcda6177b4bf4aa9a803853a1b2670daef/src/pages/home/report/ReportActionItem.tsx#L652-L655


### What changes do you think we should make in order to solve the problem?
We should display the cleared message like the message that is returned by BE if the description is empty

<img width="1512" alt="Screenshot 2024-07-17 at 14 02 51" src="https://github.com/user-attachments/assets/2f81b53a-4e6d-4f7b-b97d-3200ded1397b">

1. Create a new translation key for cleared message
2. Create a util to get the update description message

```
function getUpdateRoomDescriptionMessage(reportAction: ReportAction): string {
    const originalMessage = getOriginalMessage(reportAction) as OriginalMessageChangeLog;
    if (originalMessage.description) {
        return `${Localize.translateLocal('roomChangeLog.updateRoomDescription')} ${originalMessage?.description}`;
    }

    return Localize.translateLocal('roomChangeLog.clearRoomDescription');
}
```

3. Use this function here to get the action message to display in report screen and LHN


```
const message = ReportActionsUtils.getUpdateRoomDescriptionMessage(action);
```
https://github.com/Expensify/App/blob/52b8fddcda6177b4bf4aa9a803853a1b2670daef/src/pages/home/report/ReportActionItem.tsx#L652-L655

```
result.alternateText = `${lastActorDisplayName} ${ReportActionsUtils.getUpdateRoomDescriptionMessage(lastAction)};
```
https://github.com/Expensify/App/blob/52b8fddcda6177b4bf4aa9a803853a1b2670daef/src/libs/SidebarUtils.ts#L424-L428

OPTIONAL: We can also add the case for update room description in context menu action. So the copied message can be translated

https://github.com/Expensify/App/blob/52b8fddcda6177b4bf4aa9a803853a1b2670daef/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L364
### What alternative solutions did you explore? (Optional)
NA

**Comment by alexpensify** [comment] 2024-07-19 23:09
Other GHs have been a priority, I'll review soon

**Comment by alexpensify** [comment] 2024-07-22 23:28
Still on my testing list

**Comment by alexpensify** [comment] 2024-07-22 23:30
@hungvu193 - can you review if one of these proposals will fix this solution? Thanks!

**Comment by hungvu193** [comment] 2024-07-23 03:04
Sure thing. I'll review today

**Comment by hungvu193** [comment] 2024-07-23 03:29
I lean toward to @nkdengineer 's[ proposal here](https://github.com/Expensify/App/issues/45522#issuecomment-2232596441). We should display `clear the room description` instead of unformatted message.

🎀 👀 🎀  C+ reviewed

**Comment by hungvu193** [comment] 2024-07-27 11:44
@kavimuru Please wait for [this PR](https://github.com/Expensify/App/pull/46354) then re-test this again.

**Comment by alexpensify** [comment] 2024-08-05 22:09
Noted that the payment date is on August 7

**Comment by alexpensify** [comment] 2024-08-07 20:06
@nkdengineer - please accept the invite in Upwork and I can complete the payment process - Thanks! 

https://github.com/Expensify/App/issues/45522#issuecomment-2274038463

**Comment by hungvu193** [comment] 2024-08-08 04:14
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/44300
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/44300/files#r1708563460
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug again: Yes.


**Regression test:**
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat > Room
3. Create a room
4. Click on the report header
5. Click Room description
6. Enter the description and save it
7. Click Room description again
8. Clear description and save it
9. Go back to room chat
10. Right-click on the system message and choose copy.
11. Paste it into composer and verify it has correct content.

Do we 👍  or 👎  ?

**Comment by alexpensify** [comment] 2024-08-11 17:59
There is no update; waiting for @nkdengineer to accept the Upwork invite before I can close this GH.

**Comment by nkdengineer** [comment] 2024-08-13 05:57
@alexpensify I accepted the offer, thanks

**Comment by alexpensify** [comment] 2024-08-13 21:29
I'm all set here. I've completed the payment process in Upwork. I'll return later this week to complete the regression test.

**Closed by alexpensify** 2024-08-13 21:29 UTC
Labels: External, Daily, Awaiting Payment, Bug
