### ISSUE TITLE
Request Money/Split Bill - Unexpected error shows up when create IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21208] opened 2023-06-21 14:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot mWeb
2. Use the FAB button to create a IOU

## Expected Result:
User is landed to the chat with the contact chosen for an IOU and there is no any error messages

## Actual Result:
Unexpected error shows up when create an IOU: Unexpected error creating this chat, please try again later
There is a previously existing chat between these users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3bcbdf0b-7b00-4c8a-95ef-b7ce4eaee127

![Bug6101375_Screenshot](https://github.com/Expensify/App/assets/78819774/293f8f40-f9d2-40cb-b1b1-b6162e025a24)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2023-06-21 14:26
I'm unable to reproduce on IOS safari or app staging v1.3.30-0

**Comment by bondydaa** [comment] 2023-06-21 14:30
@lanitochka17 can you share the email of the user you are logged in as that is sending the IOU? I want to look in logs.

**Comment by grgia** [comment] 2023-06-29 15:54
Moving to daily, looking into this

**Comment by grgia** [comment] 2023-07-05 14:40
looking at this, back from OOO

**Comment by grgia** [comment] 2023-07-10 15:47
Not able to reproduce, will try again tomorrow or close

**Comment by grgia** [comment] 2023-07-14 11:55
Closing, no longer reproducible.

**Closed by grgia** 2023-07-14 11:55 UTC
Labels: Engineering, Daily, Overdue
