### ISSUE TITLE
[$500] Clicking on workspace settings also has the byproduct of filtering everything to that workspace

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35742] opened 2024-02-03 02:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** yes
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706912362033189

## Action Performed:

1. Start on the "everything" workspace filter
2. See all your chats/DMs
3. Click the wrench
4. Click Workspace
5. Choose a workspace
6. Click the chat bubble

## Expected Result:
 You are still on the "everything" workspace filter

## Actual Result:
The workspace filter is set to the workspace you selected

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/9e4de0fb-4dd3-4953-b94d-eff2d742d5d4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d34627eb77e1478</li>
        <li>Upwork Job ID: 1753605348928434176</li>
        <li>Last Price Increase: 2024-02-03</li>
    </ul>
</details>

**Comment by nyomanjyotisa** [comment] 2024-02-03 03:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The workspace filter is set to the selected workspace on workplace list in setting page

### What is the root cause of that problem?

When navigating to Workspace_Overview screen, the active workplace on the filter changed to whatever workplace is opened. I happened in this code (handleStateChange in NavigationRoot.tsx file):
![Screenshot 2024-02-03 at 11 49 03](https://github.com/Expensify/App/assets/73281575/b47f35f0-8d4b-4d5c-b4e9-6ce8fb07ae69)

### What changes do you think we should make in order to solve the problem?

Add a condition on handleStateChange in NavigationRoot.tsx file to check the last route screen, if the last route screen is equal to Workspace_Overview then skip the setActiveWorkspaceID(activeWorkspaceID); code that set the active workplace on the filter. So when the Workspace_Overview screen is opened, the active workplace on the filter not changed.

![Screenshot 2024-02-03 at 11 45 22](https://github.com/Expensify/App/assets/73281575/1e48f35c-66b0-4d8a-976b-aa2122c2a789)

### What alternative solutions did you explore? (Optional)

**Comment by jeremy-croff** [comment] 2024-02-03 05:20
Seems expected

**Comment by mountiny** [comment] 2024-02-06 09:05
This is expected, discussing internally.

**Comment by trjExpensify** [comment] 2024-02-06 19:13
As per [the thread](https://expensify.slack.com/archives/C049HHMV9SM/p1706912362033189), closing. We're fixing the issue with the workspace name in the header not changing [here](https://github.com/Expensify/App/issues/35743), which contributed to this confusion.

**Closed by trjExpensify** 2024-02-06 19:13 UTC
Labels: External, Daily, Bug
