### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Chat - The selected 2nd contact is shown in first line

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37250] opened 2024-02-27 02:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4346886
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter @
4. Select here from user suggestions
5. Tap enter key and go to next line
6. Enter @ and select any contact from user suggestion
7. Note, the selected 2nd contact is shown in first line
8. Send the message
9. Note here message is not highlighted

## Expected Result:
Selecting user suggestions here and then another contact, must show 2nd contact at second line in compose box and after sending message, here must be highlighted

## Actual Result:
Selecting user suggestions here and then another contact, showing 2nd contact at first in compose box and after sending message, here is not highlighted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2be6c3cf-b27d-4f6a-a670-cfb20ec1dbd7

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0104f679d006807363</li>
        <li>Upwork Job ID: 1762301377508782080</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-27 02:19
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by youssef-lr** [comment] 2024-02-27 04:43
Looks like this is caused by https://github.com/Expensify/App/pull/36792

**Comment by youssef-lr** [comment] 2024-02-27 07:25
@abdulrahuman5196 @dukenv0307 can you guys take a look please?

**Comment by abdulrahuman5196** [comment] 2024-02-27 07:31
Do ping me if we have a solution.

**Comment by abdulrahuman5196** [comment] 2024-02-27 08:24
> @abdulrahuman5196 I tried this [proposal](https://github.com/Expensify/App/issues/35518#issuecomment-1920503529)'s alternative and didn't get the regression as above. What do you think about this solution?

@dukenv0307 Did we find the root cause of this issue? What is causing this?

**Comment by abdulrahuman5196** [comment] 2024-02-27 10:05
> @abdulrahuman5196 I tried this [proposal](https://github.com/Expensify/App/issues/35518#issuecomment-1920503529)'s alternative and didn't get the regression as above. What do you think about this solution?

@dukenv0307  If we need to implement the alternate solution, it would be better to do a straight revert of the offending PR to unblock staging and to avoid any new regressions from the alternate solution implementation. Since the alternate solution is a different implementation and would need to discuss on that.

@youssef-lr what do you think?

**Comment by abdulrahuman5196** [comment] 2024-02-27 10:48
> > leading to wrong leftString and atSignIndex.
> 
> @abdulrahuman5196 On second thought, I saw that `atSignIndex` is wrong because the left string is cut off from the last break line index meanwhile `atSignIndex` is the index based on the full string so with my main solution we need to update `atSignIndex` correctly by adding it with `newLineIndex + 1`. What do you think about this?

@dukenv0307 
Got it. Seems to be good. Can we raise a quick PR on the same? 
And do check if any other properties need to be updated?

**Comment by abdulrahuman5196** [comment] 2024-03-01 10:34
No payment required here since it was a regression fix. @youssef-lr We can close this issue.

**Comment by abdulrahuman5196** [comment] 2024-03-07 19:29
> No payment required here since it was a regression fix. youssef-lr We can close this issue.

cc: @trjExpensify

**Closed** 2024-03-07 19:34 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment
