### ISSUE TITLE
[HOLD #18244] Not all the magic code input dashes are red when error appears

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20416] opened 2023-06-07 22:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open profile
4. Open contact method
5. If you have pending verfication of contact, click on it OR add new email or phone number and reopen that contact
6. Without writing any code, click on verify and observe that input for 1st digit is displayed in green and for rest digits, it is displayed in red
7. Sign out of the app
8. Insert any email or phone number and continue
9. Without inserting magic code, click on Sign in and observe that input of all digits are displayed in red

## Expected Result: 
App should display all the digit input in red if there is any error during contact method verification
## Actual Result: 
App displays 1st digit input in green and rest in red if we click on verify without inserting any code and 'Please enter your magic code' is triggered
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.25-3
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/24d76d93-2abc-4909-b1fe-bc4263677293

https://github.com/Expensify/App/assets/43996225/ce3199c6-1428-40e6-abde-218f4ea00896

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1685873935586999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by namhihi237** [comment] 2023-06-08 00:02
### Please re-state the problem that we are trying to solve in this issue.
App should display all the digit input in red if there is any error during contact method verification
### What is the root cause of that problem?
After pressing submit the app displays 1st digit input in green because after submitting the app is still focusing on the current input.  It results in the input being blue because the style `styles.borderColorFocus`
https://github.com/Expensify/App/blob/96adb8e58e53fd76c7a316234dab322643dfd479/src/components/MagicCodeInput.js#L309
Use magic code:
https://github.com/Expensify/App/blob/96adb8e58e53fd76c7a316234dab322643dfd479/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#LL123-L133
After submitting and returning an error we haven’t  unfocus it yet:
https://github.com/Expensify/App/blob/96adb8e58e53fd76c7a316234dab322643dfd479/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L106-L119
### What changes do you think we should make in order to solve the problem?
We will update the function validateAndSubmitForm when an error occurs then unfocus input:
```
const  validateAndSubmitForm  =  useCallback(() => {
	if (!validateCode.trim()) {
		setFormError({ validateCode: ‘validateCodeForm.error.pleaseFillMagicCode’ });
		inputValidateCodeRef.current.blur();
		return;
	}
	if (!ValidationUtils.isValidValidateCode(validateCode)) {
		setFormError({ validateCode: ‘validateCodeForm.error.incorrectMagicCode’ });
		inputValidateCodeRef.current.blur();
		return;
	}
	setFormError({});
	User.validateSecondaryLogin(props.contactMethod, validateCode);
}, [validateCode, props.contactMethod]);
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by alitoshmatov** [comment] 2023-06-08 06:45
I think it is related to https://github.com/Expensify/App/issues/18244 , and solution of that issue will resolve this one too, since that issue will gurantee that when clicking outside of magic input, magic input will be blurred

**Comment by kevinksullivan** [comment] 2023-06-09 01:48
Updated @Santhosh-Sellavel

**Comment by kevinksullivan** [comment] 2023-06-13 12:44
Still held.

**Comment by kevinksullivan** [comment] 2023-06-16 13:58
Still held

**Comment by kevinksullivan** [comment] 2023-06-20 13:31
Held

**Comment by kevinksullivan** [comment] 2023-06-26 20:58
Held, and making this weekly as the relevant GH is still in planning.

**Comment by ygshbht** [comment] 2023-07-06 04:53
[22190](https://github.com/Expensify/App/issues/22190#issuecomment-1620988994)
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem we're aiming to solve is an inconsistency in the user experience. Specifically, the cells of the magic code input field stay highlighted (or focused) even when an error occurs. This behavior is noted in the 'Contact methods' section. The desired behavior is for the input field to lose focus (blur) when an error is detected, mirroring the behavior observed during 'Sign in'. This inconsistency between the two scenarios is what we're aiming to rectify.

### What is the root cause of that problem?
The root cause of this issue can be traced back to the absence of a dedicated mechanism within the `MagicCodeInput `and `BaseValidateCodeForm `components to blur the input field upon encountering this particular error. The current implementation lacks the necessary code to handle this specific scenario, which results in the observed inconsistency.

### What changes do you think we should make in order to solve the problem?
To address this issue, we need to implement functionality to blur the input field when such error is encountered. This can be achieved by adding a `useEffect `hook in the `MagicCodeInput `component. The hook will monitor the `hasError `and `errors` props, and call the `blurMagicCodeInput` function when an error is detected:
```
useEffect(()=>{
    if (props.hasError){
        blurMagicCodeInput();
    }
},[props.hasError, props.errors])
```
In the `BaseValidateCodeForm `component, we can pass the `hasError` and `errors` props to `MagicCodeInput` or modify the existing props:
```
<MagicCodeInput
    autoComplete={props.autoComplete}
    ref={inputValidateCodeRef}
    label={props.translate('common.magicCode')}
    name="validateCode"
    value={validateCode}
    onChangeText={onTextInput}
    errorText={formError.validateCode ? props.translate(formError.validateCode) : ErrorUtils.getLatestErrorMessage(props.account)}
    hasError={formError && Object.keys(formError).length !== 0} /* new prop */
    errors={formError} /* new prop */
    onFulfill={validateAndSubmitForm}
    autoFocus
    shouldSubmitOnComplete={false}
/>
```
This solution provides a more consistent user experience by ensuring that the focus is lost from the input field when an error is present. The code can further be refactored to improve generality and maintainability.


https://github.com/Expensify/App/assets/65986357/372484fa-b5e1-4b6d-a12b-6c73c81b2b27

**Comment by ygshbht** [comment] 2023-07-06 05:00
The files I'm referring to changes are ["src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js"](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js).

On a side note (please feel free to ignore this for now), I observed that the input doesn't display red error when "Verify" is clicked with all six fields populated. This could be rectified by making some changes in the "MagicCodeInput" component's props. Here's a snippet:
<MagicCodeInput
    ...
    onChangeText={(...args) => {
        User.clearContactMethodErrors(props.contactMethod, 'validateLogin');
        onTextInput(...args)
    }}
    hasError={(formError && Object.keys(formError).length !== 0) || 
        Object.keys(ErrorUtils.getLatestErrorField(loginData, 'validateLogin')).length >0
    }
    ...
/>

**Comment by Ali-ch88** [comment] 2023-07-06 10:14
**Proposal**

1-**Please re-state the problem that we are trying to solve in this issue.**

Not all the magic code input dashes are red when error appears

2-**What is the root cause of that problem?**

  When we click on the verify button, the currently selected input is focused(),
      so the styling for errors is not applied to it due to the current logic. So, the current focused input will remain green underlined.

3-**What changes do you think we should make in order to solve the problem?**

We can make the current selected input field Blur() when we submit our verification code. In that way, the error styles will be 
applied on it also
![tt](https://github.com/Expensify/App/assets/61835503/01eb9a38-97ea-4b2e-8b84-3cbb47902f20)

4-**What alternative solutions did you explore? (Optional)**
NA

**Comment by kevinksullivan** [comment] 2023-07-12 18:26
held

**Comment by kevinksullivan** [comment] 2023-07-28 23:37
still held

**Comment by kevinksullivan** [comment] 2023-08-21 22:05
held on https://github.com/Expensify/App/issues/18244

**Comment by kevinksullivan** [comment] 2023-10-17 15:52
held

**Comment by kevinksullivan** [comment] 2023-11-27 22:59
still on hold

**Comment by kevinksullivan** [comment] 2023-12-01 20:59
held

**Comment by kevinksullivan** [comment] 2023-12-12 03:21
Closing unless we see it again

**Closed** 2023-12-12 03:21 UTC
Labels: Weekly, Overdue, Bug
