### ISSUE TITLE
[HOLD for Regression Test] Make option row icons use green color

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#13104] opened 2022-11-28 21:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
When viewing option rows in places like Settings or the Workspace editor, we wanted to make the default icon color of these green for the new color changes. 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/2319350/204384692-def0b9d9-d344-40d4-a90c-7c9dcd960f96.png">

Note that for the green option rows (the green brick road CTA), the icon should remain white:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/2319350/204385030-e2d15c05-0f18-466e-8367-e86fad014491.png">

## Expected Result:
Icons should be green

## Actual Result:
Icons are using the theme's general icon color. 

## Workaround:
This does not block any user behavior and thus no workarounds needed. 

## Platform:
Where is this issue occurring? All platforms

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2022-11-28 21:42
<img width="375" alt="image" src="https://user-images.githubusercontent.com/38015950/204387068-d54760c3-580d-4bf8-bc5f-75ea2138c75b.png">
Does this apply to these icons too?

**Comment by shawnborton** [comment] 2022-11-28 21:57
I think so, yup!

**Comment by grgia** [comment] 2022-11-28 22:49
<img width="368" alt="image" src="https://user-images.githubusercontent.com/38015950/204396789-cec7ef9f-602b-4014-aaea-06e434787487.png">
Double checking, the arrows should be the normal icon color?

Here's where the button icons colors are determined (hover, active, etc)- do any of these state colors also need to be changed?
https://github.com/Expensify/App/blob/master/src/styles/StyleUtils.js#L258-#L271

**Comment by shawnborton** [comment] 2022-11-28 22:50
I think we'd keep the arrows as they were previously (standard icon color)

**Comment by shawnborton** [comment] 2022-11-28 22:55
I think we can keep the icon as green for the active/hover states, but I'm curious what this one means: `CONST.BUTTON_STATES.COMPLETE`

**Comment by grgia** [comment] 2022-11-28 23:05
<img width="220" alt="image" src="https://user-images.githubusercontent.com/38015950/204398971-20fb8d2e-77ff-4184-a715-f98171c5dbc3.png">
how about these icons?

**Comment by grgia** [comment] 2022-11-28 23:06
> I think we can keep the icon as green for the active/hover states, but I'm curious what this one means: `CONST.BUTTON_STATES.COMPLETE`

I believe an example of this is the download icon, once the download is complete

**Comment by shawnborton** [comment] 2022-11-28 23:08
I think the mini menu icons can stay as they are, the green is mostly just for the option row component.

**Comment by mollfpr** [comment] 2022-11-29 15:42
Hey @greg-schroeder, since I got assigned to the PR, could you assign the issue and create the Upwork job? Thanks!

**Comment by mollfpr** [comment] 2022-12-02 02:14
Bump @greg-schroeder https://github.com/Expensify/App/issues/13104#issuecomment-1330846322

**Comment by greg-schroeder** [comment] 2022-12-02 02:49
Sorry, taking a look

**Comment by greg-schroeder** [comment] 2022-12-02 08:32
Internal: https://www.upwork.com/ab/applicants/1598595761398837248/job-details
External: https://www.upwork.com/jobs/~0140962a61e192bf23

**Comment by mollfpr** [comment] 2022-12-02 08:34
@greg-schroeder Applied, thanks!

**Comment by mollfpr** [comment] 2022-12-08 18:42
@greg-schroeder bump https://github.com/Expensify/App/issues/13104#issuecomment-1334907835

**Comment by dylanexpensify** [comment] 2022-12-12 17:07
offer sent @mollfpr !

**Comment by dylanexpensify** [comment] 2022-12-12 17:09
@mollfpr payment sent, contract ended!

**Comment by mollfpr** [comment] 2022-12-12 17:10
Thanks, @dylanexpensify!

**Comment by dylanexpensify** [comment] 2022-12-13 11:45
@greg-schroeder paid out @mollfpr, but will leave the other items to you!

**Comment by greg-schroeder** [comment] 2023-01-19 21:55
Working on the regression part, apologies for the delay on this - I was out for a while and catching up on all of my stuff.

**Comment by greg-schroeder** [comment] 2023-01-24 08:08
Getting some assistance and this should be finished up by today 1/24!

**Comment by grgia** [comment] 2023-01-27 20:39
Not overdue melvin!

**Comment by greg-schroeder** [comment] 2023-01-30 12:34
Posted in slack here re: regression: https://expensify.slack.com/archives/C01SKUP7QR0/p1675082018473579

**Comment by greg-schroeder** [comment] 2023-01-30 18:17
Per slack discussion, potential regressions covered by design guidelines - closing!

**Closed by greg-schroeder** 2023-01-30 18:17 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
