### ISSUE TITLE
Chat - New messages not showing up in conversation when clicking on bold text in LHN offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23474] opened 2023-07-24 11:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to http://staging.new.expensify.com/
2.  Log in any account
3. Receive a new message from a user
4. Turn off internet
5. Tap on bold chat in LHN

## Expected Result:
The new messages must be displayed in the conversation history

## Actual Result:
When user in offline mode, tap on bold chat in LHN, the new messages are not displayed in the conversation history

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/efb442bb-fc9e-40a2-9387-a75f40dd56ec

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2023-07-31 23:48
Thanks @bernhardoj 🏆 
Closing, dupe of https://github.com/Expensify/App/issues/21000#issuecomment-1607975714 
and... 
> Yes, in that case I think we should just close this issue and mention that it will be solved by ongoing back-end refactors. Thanks so much for the convo!

**Closed by mallenexpensify** 2023-07-31 23:48 UTC
Labels: Daily, Overdue, Bug
