### ISSUE TITLE
[$500] Task - Chat is not scrolled to bottom when edit a task

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38833] opened 2024-03-22 20:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/20318&group_by=cases:section_id&group_order=asc&group_id=291935
**Email or phone of affected tester (no customers):** shussain+web@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open an existing chat
2. Click the '+' > Assign Task
3. Give the task as Title, Description and Assignee > Confirm Task
4. Click on the created task in the chat
5. Change the name > Save
6. Verify there's an audit trail of the change in the chat thread
7. Make more changes to the task (you can change the title, description, assignee) > click Save
8. Verify that eventually the chat isn't fully scrolled to the bottom of last message (or audit trail change)

## Expected Result:
Chat should always scroll to the bottom of the last message ( you should see the last message after making a change)

## Actual Result:

After making multiple edits to a task, the chat thread isn't scrolled to the bottom. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e27c103f-3f38-4b7d-82f5-021d620d12a9

https://github.com/Expensify/App/assets/51066321/f0ac74bf-5975-40a1-9c3b-15521378e3ce

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d64def74796adc96</li>
        <li>Upwork Job ID: 1772488534557900800</li>
        <li>Last Price Increase: 2024-03-26</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-22 20:06
@Christinadobrzyn FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-22 20:06
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment] 2024-03-23 05:49
Same issue as https://github.com/Expensify/App/issues/38855

**Comment by Christinadobrzyn** [comment] 2024-03-25 03:37
Hum, I'm not able to reproduce this, it looks like the chat is at the bottom and the cursor is in the chat field when making edits to an assigned task. 


https://github.com/Expensify/App/assets/51066321/9edda5d6-c31d-4004-88be-91f74ee70776

Asking QA to clarify what the bug is.

**Comment by Christinadobrzyn** [comment] 2024-03-26 04:59
Ah okay, I think I'm able to reproduce, updated the OP so it's more clear how to reproduce. I think this can be external and part of vip-vsb

**Comment by nkdengineer** [comment] 2024-03-26 05:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After making multiple edits to a task, the chat thread isn't scrolled to the bottom.

### What is the root cause of that problem?
We don't call `notifyNewAction` after we edit the task. 

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/Report.ts#L344-L345

If it's currently a bug, it also happens when we edit a money request.
### What changes do you think we should make in order to solve the problem?
After edit a task or edit a money request, we should call `notifyNewAction` to scroll to bottom of the report.

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/Task.ts#L299

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/Task.ts#L365

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/Task.ts#L429

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/Task.ts#L504

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/Task.ts#L795

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/IOU.ts#L2053

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/IOU.ts#L2030

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/IOU.ts#L2014

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/IOU.ts#L1975

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/IOU.ts#L1952

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/IOU.ts#L1936

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/IOU.ts#L1913

https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/IOU.ts#L3551
### What alternative solutions did you explore? (Optional)
NA

**Comment by 0018akhil** [comment] 2024-03-26 08:03
Hello @gijoe0295 

I'm on Windows OS above issue is only happening in the **staging environment.**

Below is the video comparing both staging and the new website.

https://github.com/Expensify/App/assets/62931444/d4ad3906-9688-4180-8212-bae6a6b0c890

I found this third-party cookies warning in the **staging website** this might be causing the issue(scrolling).
![image](https://github.com/Expensify/App/assets/62931444/c93782df-f437-40de-94b2-dcd869a67efe)

Thanks,
Akhil Achary
(Upwork)

**Comment by 0018akhil** [comment] 2024-03-26 08:49
Contributor details
Your Expensify account email: [0018akhil@gmail.com](mailto:0018akhil@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/akhilachary

Try pointing **staging.new.expensify.com**(staging website) to **new.expensify.com** URL temporarily The party cookies warning will disappear and test it (scrollbar problem).

If you use Cloudflair this can be done easily.

**Comment by nkdengineer** [comment] 2024-03-27 06:12
@fedirjh The reason is here 

https://github.com/Expensify/App/blob/9d9757ffb3dfdad5dbd3dc13cd962faf5e1249d4/src/pages/home/ReportScreen.tsx#L436-L440

The transaction thread report is a chat thread and If we don't add any comment in transaction thread report, the notification of this report is hidden. When we edit the money request, the report is unfocused and then it's focused again after we submit the edit. That makes this useEffect above is triggered when we edit the money request and then the chat scrolls to bottom. 

I think it's another bug and we should add `isSingleTransactionView` check in this `useEffect` to prevent `openReport` is called.


To replicate this bug, we can send a message in this report and edit the money request again.

https://github.com/Expensify/App/assets/161821005/afc1860f-47ce-428a-85d6-412a25c61d2d

**Comment by 0018akhil** [comment] 2024-03-27 06:33
@nkdengineer 
Is this issue happening only on the staging site?

**Comment by Christinadobrzyn** [comment] 2024-03-28 05:02
@0018akhil This appears to be happening in production too


https://github.com/Expensify/App/assets/51066321/d7f2006a-a246-4ed9-9f69-4329387ae511

**Comment by 0018akhil** [comment] 2024-03-28 05:38
Hi @Christinadobrzyn . Okay

So your in Mac. Can you send me the screenshot of your console.

**Comment by Christinadobrzyn** [comment] 2024-03-28 06:37
I see this in the console when changing the task not sure if those are helpful 

<img width="1580" alt="image" src="https://github.com/Expensify/App/assets/51066321/1bef8118-cb59-4047-b7f8-4c2add2aecf5">

**Comment by nkdengineer** [comment] 2024-03-29 03:01
> I was not able to replicate the bug with the money request edit flow. Hence, I don't think we should extend the fix to cover that flow.

> To replicate this bug, we can send a message in this report and edit the money request again.


@fedirjh As I mentioned above, we can replicate this bug on latest main or staging by sending a message in transaction thread report before we edit the money request. I think we should fix all of them in a issue to verify that this bug doesn't happen in the further.

**Comment by Christinadobrzyn** [comment] 2024-04-02 07:36
Not overdue, working on the PR.

**Comment by Christinadobrzyn** [comment] 2024-04-22 05:16
Thanks @gijoe0295 - not sure why the payment auto-message didn't trigger for this. 

Payouts due:

- [X] Contributor: $500 @gijoe0295 (paid in upwork - https://www.upwork.com/nx/wm/workroom/36856139/overview)
- [X] Contributor+: $500 @fedirjh (paid in upwork - https://www.upwork.com/nx/wm/workroom/37008381/overview)

Upwork job is [here](https://www.upwork.com/ab/applicants/1772488534557900800/job-details).

@fedirjh or @gijoe0295 do we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2024-04-23 07:57
Oh thank you for clarifying! Okay, gotcha! 

Please ignore my refund requests. Closing since we don't need a regression. Let me know if I'm missing anything.

**Closed by Christinadobrzyn** 2024-04-23 07:57 UTC
Labels: Reviewing, External, Daily, Bug
