### ISSUE TITLE
 iOS - URLs are hyperlinked instead of hyperlink text when edit message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35831] opened 2024-02-05 16:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.36-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4280657
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to New Expensify
2. Nagivate to any chat
3. Send a hyperilnk using []() format, e. g.: [hyperlink text](hello.com)
4. Edit sent message

## Expected Result:
Hyperlink text should be hyperlinked to reflect what the message would look like when sent, as Live Markdown Preview has been implemented

## Actual Result:
The URL is hyperlinked instead of the text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f4ecaedb-4770-430e-8428-f9856c4b51b5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-05 16:11
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by mountiny** [comment] 2024-02-05 16:42
Not a blocker imho, seems like this works fine, just needs a bit of a polish.

cc @tomekzaw also related to the markdown

**Comment by tomekzaw** [comment] 2024-02-05 16:50
+1, we decided to keep the current way of formatting for now and iterate on it later on

**Comment by thienlnam** [comment] 2024-02-05 23:31
Closing since this is working as designed

**Closed by thienlnam** 2024-02-05 23:31 UTC
Labels: Engineering, Daily
