### ISSUE TITLE
[HOLD #47933] Approval - Next step shows approver is going to pay

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49603] opened 2024-09-23 13:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4934145
**Email or phone of affected tester (no customers):** testpayment935@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Owner, approver and submitter accounts are setup
- Three of them have setup a display name, the owner has setup his display name as "Owner" and approver has its display name setup as "Approver" and submitter does the same as well.
- Bank account is not added as the owner
1. [Submitter] Submit an expense to the workspace
2. [Approver] Go inside the report conversation and approver the expense and take note of the next step

## Expected Result:
The next step shows "Waiting for Owner to pay the expenses" gets shown

## Actual Result:
"Waiting for approver to pay the expenses" gets shown as the next steps

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/2a568261-b438-4e0d-a731-c77de33b85f7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-09-23 13:49
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment] 2024-09-23 15:23
It does seem like it's likely the same issue. Thanks @ishpaul777. Going to put this on hold for that.

**Comment by aldo-expensify** [comment] 2024-09-24 01:35
I think this is also a dupe of https://github.com/Expensify/App/issues/47278, and @dangrous changed this to show "an admin" in this PR: https://github.com/Expensify/Web-Expensify/pull/43483

**Comment by dangrous** [comment] 2024-09-24 16:55
Yeah I think this is being handled, both the action needing to be taken and the name of the person will be changing

**Comment by puneetlath** [comment] 2024-10-07 16:27
Sounds like this should be fixed. Asking for a re-test.

**Comment by m-natarajan** [comment] 2024-10-07 18:37
Issue fixed.
![image (22)](https://github.com/user-attachments/assets/63eab172-2652-4f63-bd50-11fea271baa8)
![image (21)](https://github.com/user-attachments/assets/5834ebeb-517d-4c33-a7cd-b18194efa920)

https://github.com/user-attachments/assets/ae75a5c5-9037-4539-a193-66414a0fef31

**Comment by puneetlath** [comment] 2024-10-07 18:44
Great, thanks for confirming!

**Closed by puneetlath** 2024-10-07 18:44 UTC
Labels: Daily, Bug

**Comment by dangrous** [comment] 2024-10-08 01:13
I'm going to go ahead and close this since it should be fixed by now.
