### ISSUE TITLE
[HOLD for payment 2022-07-05] [$250] Attachment - Download icon isn't turning green when clicking to download  in Preview Page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9124] opened 2022-05-20 23:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account and select any chat
3. Click on any attachment
4. On Preview page click download icon

## Expected Result:
Download icon should turned green after click on it in Preview Page

## Actual Result:
Download icon isn't turned green after click on it in Preview Page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**  1.1.63.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/169625569-ea1fec03-988c-4994-ae29-ceca6df71e27.mp4

![Bug5577820_DownloadIcon](https://user-images.githubusercontent.com/43996225/169625574-30541c8b-ee09-4782-8b7f-7a4d1b3b20ba.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause - Exploratory
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sobitneupane** [comment] 2022-05-22 02:45
**Proposal:**
We can make use of `ContextMenuItem` in HeaderWithCloseButton to solve this issue. 
https://github.com/Expensify/App/blob/56213d07d5e10b5ecf1cb2fae2d82aff9360bb5a/src/components/HeaderWithCloseButton.js#L134-L146
```js
                {
                    props.shouldShowDownloadButton && (
                      <ContextMenuItem
                        icon={Expensicons.Download}
                        text={props.translate('common.download')}
                        successIcon={Expensicons.Download}
                        successText={props.translate('common.download')}
                        isMini={true}
                        key={props.translate('common.download')}
                        onPress={props.onDownloadButtonPress}
                        autoReset
                    />
                    )
                }
```
With autoReset prop in ContextMenu Item, download button remains green for 1800ms as configured in ContextMenuItem. Without autoReset prop, the download button remains green until the modal is closed. Util the button is grey again, download operation cannot be carried out.

**Comment by chiragsalian** [comment] 2022-05-23 18:11
Looks like a straightforward external issue.

**Comment by jliexpensify** [comment] 2022-05-23 23:28
Posted!

Internal - https://www.upwork.com/ab/applicants/1528880284048494592/job-details
External - https://www.upwork.com/jobs/~0113f02a60cc2d761f

**Comment by rushatgabhane** [comment] 2022-05-24 17:49
@sobitneupane the style doesn't fit in with the other buttons.

How about we abstract away some of that timing logic so that it can be used by other components as well?

https://user-images.githubusercontent.com/29673073/170098548-525ed88b-83cd-4763-960d-e8683b3f9a02.mov

**Comment by sobitneupane** [comment] 2022-05-26 10:56
> How about we abstract away some of that timing logic so that it can be used by other components as well?

Sorry. I didn't get you. Do you mean to create a new component with the required logic?

**Comment by rushatgabhane** [comment] 2022-05-26 11:39
@sobitneupane some ideas - a HOC ([see this](https://www.patterns.dev/posts/hoc-pattern/)), utils maybe?

We wanna reuse the logic of a pressable changing it's [style](https://github.com/Expensify/App/blob/50582364b411c61d8f9b8f6ac7439cce7e6f9765/src/components/ContextMenuItem.js#L97) for [1800ms](https://github.com/Expensify/App/blob/50582364b411c61d8f9b8f6ac7439cce7e6f9765/src/components/ContextMenuItem.js#L65-L81).

**Comment by mollfpr** [comment] 2022-05-26 14:56
### Proposal

1. Creating a HOC to handle the logic of pressable icons.
Here I move the logic from the `ContextMenuItem` component that handles the success state. The HOC also have parameter for the auto reseting the success state.
```js
export default function ({autoReset}) {
    return (WrappedComponent) => {
        class WithToggleButtonSuccess extends Component {
            constructor(props) {
                super(props);

                this.state = {
                    success: false,
                };
                this.toggleSuccess = this.toggleSuccess.bind(this);
            }

            componentWillUnmount() {
                if (!this.successResetTimer) {
                    return;
                }

                clearTimeout(this.successResetTimer);
            }

            toggleSuccess() {
                this.setState({
                    success: true,
                });
                if (autoReset) {
                    this.successResetTimer = setTimeout(() => this.setState({success: false}), 1800);
                }
            }

            render() {
                // eslint-disable-next-line react/jsx-props-no-spreading
                return <WrappedComponent {...this.props} success={this.state.success} autoReset={autoReset} toggleSuccess={this.toggleSuccess} />;
            }
        }

        WithToggleButtonSuccess.displayName = `WithToggleButtonSuccess(${getComponentDisplayName(WrappedComponent)})`;
        WithToggleButtonSuccess.propTypes = {
            forwardedRef: PropTypes.oneOfType([
                PropTypes.func,
                PropTypes.shape({current: PropTypes.instanceOf(React.Component)}),
            ]),
        };
        WithToggleButtonSuccess.defaultProps = {
            forwardedRef: undefined,
        };
        return React.forwardRef((props, ref) => (
            // eslint-disable-next-line react/jsx-props-no-spreading
            <WithToggleButtonSuccess {...props} forwardedRef={ref} />
        ));
    };
}
```
2. Updating the `ContextMenuItem` component to use the HOC
We use the HOC and update the `this.state.success` with `this.props.success`. Also for toggling the state changes, we update the function when the icon is pressed to use the function from the HOC which `toggleSuccess`.
https://github.com/Expensify/App/blob/50582364b411c61d8f9b8f6ac7439cce7e6f9765/src/components/ContextMenuItem.js#L73-L80
```js
        if (this.props.successIcon || this.props.successText) {
            this.props.toggleSuccess();
        }
```
3. Updating the `HeaderWithCloseButton` component to get icon fill color by the success state from HOC.
Here we need to pass the `success` state from the parent component that handles the `fileDownload` function which is the `AttachmentModal` component. We also need to change the touch component for the download icon to get the pressable state and get the correct fill icon color.
https://github.com/Expensify/App/blob/50582364b411c61d8f9b8f6ac7439cce7e6f9765/src/components/HeaderWithCloseButton.js#L138-L143
```js
                        <Pressable
                            onPress={props.onDownloadButtonPress}
                            style={[styles.touchableButtonImage]}
                        >
                            {({hovered, pressed}) => (
                                <Icon
                                    src={Expensicons.Download}
                                    fill={StyleUtils.getIconFillColor(getButtonState(hovered, pressed, props.success))}
                                />
                            )}
                        </Pressable>
```
4. Updating the `AttachmentModal` component to use the HOC
We use the HOC with `autoReset` params set to `true` because the modal is not destroyed when it is closed. We toggle the `toggleSuccess` function when the file download is complete by adding the resolve function. We also need to pass the `success` state from the HOC to `HeaderWithCloseButton` component.
https://github.com/Expensify/App/blob/50582364b411c61d8f9b8f6ac7439cce7e6f9765/src/components/AttachmentModal.js#L170
```js
  onDownloadButtonPress={() => fileDownload(sourceURL, this.props.originalFileName).then(this.props.toggleSuccess)}
```
https://github.com/Expensify/App/blob/50582364b411c61d8f9b8f6ac7439cce7e6f9765/src/components/AttachmentModal.js#L166-L179
```js
  success={this.props.success}
```

### Result

https://user-images.githubusercontent.com/25520267/170514362-d63fb250-cea6-4ee9-a6c1-7a0d09cedf5c.mov

*note: It might be worth to change `TouchableOpacity` to `Pressable` to all the icon button on `HeaderWithCloseButton` to have some effect with the download icon button.

**Comment by rushatgabhane** [comment] 2022-05-29 20:57
> Updating the AttachmentModal component to use the HOC... 
We toggle the toggleSuccess function when the file download is complete

@mollfpr I don't think we should do that. Toggling the color back to grey after 1800ms is fine.

> TouchableOpacity to Pressable to all the icon button on HeaderWithCloseButton

Sure!

Also, any more ideas on the name of this new component? `WithToggleButtonSuccess` is confusing.

**Comment by rushatgabhane** [comment] 2022-05-29 21:00
@chiragsalian I like @mollfpr's [proposal](https://github.com/Expensify/App/issues/9124#issuecomment-1138668417).
It moves the timer logic from `ContextMenu` to a HOC which is then reused by `AttachmentModal` and ofc `ContextMenu`.

🎀 👀 🎀 C+ reviewed

**Comment by mollfpr** [comment] 2022-05-30 02:49
@rushatgabhane
> I don't think we should do that. Toggling the color back to grey after 1800ms is fine.

I don’t get this part.

> Where else can we reuse this new component? 

Currently, it’s only introduced by `ContextMenuItem`.

> And, any more ideas on the name? WithToggleButtonSuccess is confusing.

I’ll get onto this later, naming things in code is the hardest part for me 😅

**Comment by chiragsalian** [comment] 2022-05-31 17:17
Proposal LGTM as well. I like the HOC. Feel free to create the PR @mollfpr. As for your questions, we can discuss in the PR as well since it might be easier to tag code.
@jliexpensify, feel free to hire @mollfpr for his work.

**Comment by jliexpensify** [comment] 2022-06-02 01:18
Hired @rushatgabhane 

@mollfpr - sorry, can you confirm your Upworks profile again? Are you Mochammad H. by any chance?

**Comment by mollfpr** [comment] 2022-06-02 01:47
@jliexpensify Applied! That's not me 😅

**Comment by jliexpensify** [comment] 2022-06-08 15:05
@mollfpr - any updates here?

**Comment by mollfpr** [comment] 2022-06-09 12:47
PR is still in review.

**Comment by chiragsalian** [comment] 2022-06-20 21:44
Melvin derping here. Shoo go away melvin. Issue is not overdue. PR is merged and on staging.

**Comment by mvtglobally** [comment] 2022-06-21 04:02
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-06-28 04:02
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2022-07-05 04:38
Issue not reproducible during KI retests. (Third week)

**Comment by jliexpensify** [comment] 2022-07-06 03:22
Paid Rushat and Mohammad! Thanks.

**Closed by jliexpensify** 2022-07-06 03:22 UTC
Labels: Reviewing, Exported, External, Engineering, Daily, Awaiting Payment
