### ISSUE TITLE
[HOLD for payment 2023-09-27] [$1000] Web -  RHP overlapping with the popovers

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22953] opened 2023-07-15 19:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account and open any chat.
2. Click on the avatar in the chat header to open the chat details RHP.
3. Click anywhere else to close it.
4. Press the video call icon in the chat header to open the popover.
5. Press the `forward` button in the browser.

## Expected Result:
RHP should open and popover should close.

## Actual Result:
Both RHP and popover are open.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/773978ad-1f51-45fa-84dc-fffb6a34853c

![image (26)](https://github.com/Expensify/App/assets/93399543/218a3071-c0fb-4ae3-b1de-ffa30ce54b1a)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Sibtain Ali
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689367096915129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013464e806f5099ea9</li>
        <li>Upwork Job ID: 1696143850157252608</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2023-07-26 20:23
still holding

**Comment by NicMendonca** [comment] 2023-08-08 12:53
^ PR almost merged 🎉

**Comment by NicMendonca** [comment] 2023-08-22 15:07
https://github.com/Expensify/App/issues/15289 is closed! removing `hold`

**Comment by napster125** [comment] 2023-08-31 15:40
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The popovers overlap RHP when clicking the "Forward" button in the browser.
### What is the root cause of that problem?
Although the popovers are configured to close when users click outside or scroll down, they are not designed to close when the Right-Hand Panel (RHP) is opened. This issue persists across all popovers.
### What changes do you think we should make in order to solve the problem?
We need to add event listener to execute the ```closePopover()``` function whenever a route change is triggered in ```PopoverContextProvider```. Since the action of opening RHP corresponds to a route change, this step will ensure that any active popover is closed appropriately.

Result:

https://github.com/Expensify/App/assets/136437976/6ff58723-8d2d-42c3-b3ab-3139cfb87480

**Comment by NicMendonca** [comment] 2023-08-31 18:57
@sobitneupane proposal for you! ^

**Comment by napster125** [comment] 2023-09-05 10:31
Hi, @sobitneupane.
This [proposal](https://github.com/Expensify/App/issues/22953#issuecomment-1636876598) only addresses the issue within the video chat popover. However, this problem occurs throughout the entire popover. How does this benefit you?

https://github.com/Expensify/App/assets/136437976/43eeadba-0e06-4c6c-8e20-5c059d839932

**Comment by sobitneupane** [comment] 2023-09-05 11:39
Thanks @napster125 and @allroundexperts, I will re-evaluate the proposals.

**Comment by napster125** [comment] 2023-09-11 10:56
I'm currently facing an issue with my suspended Upwork account. If it's feasible, could you kindly consider sending the offer to my alternate Upwork account? I would greatly appreciate your assistance in this matter. 😞

**Comment by NicMendonca** [comment] 2023-09-11 12:40
@napster125 the job has been posted in this issue. You can apply here: https://www.upwork.com/jobs/~013464e806f5099ea9

**Comment by napster125** [comment] 2023-09-11 13:01
Thanks @NicMendonca Here is my [Upwork URL](https://www.upwork.com/freelancers/~0111689310c69ddae7). If it's not too much trouble, could you please send the offer to this account?

**Comment by dangrous** [comment] 2023-09-11 16:06
this proposal looks good to me! Assigning you, @napster125

**Comment by napster125** [comment] 2023-09-11 16:29
@thienlnam @NicMendonca could you please take a look [here](https://github.com/Expensify/App/issues/22953#issuecomment-1713835424)?

**Comment by napster125** [comment] 2023-09-11 18:12
Hi @NicMendonca, I've submitted a proposal using [this account](https://github.com/Expensify/App/issues/22953#issuecomment-1713835424). Could you please consider hiring me?

**Comment by NicMendonca** [comment] 2023-09-11 18:14
@napster125 you've been hired on Upwork

**Comment by napster125** [comment] 2023-09-12 01:18
@dangrous @sobitneupane The PR is ready to review. Could you please review it?

**Comment by sophiepintoraetz** [comment] 2023-09-12 01:45
@napster125 - until we figure out your payment situation, please do not take any more jobs as we cannot guarantee payment at this stage.

**Comment by NicMendonca** [comment] 2023-09-13 21:29
@napster125 We've had to unassign you this from issue, since we cannot guarantee payment at this time and we don't want to further delay this issue being resolved. 

cc @sobitneupane

**Comment by napster125** [comment] 2023-09-13 21:32
Okay @NicMendonca, @sobitneupane , can you please assign my friend who can resolve this issue? I can help him.

**Comment by napster125** [comment] 2023-09-13 21:43
Got it. @NicMendonca, @sobitneupane, @dangrous, could you please assign my friend who can handle this issue? I'll be available to assist him. He's already an active contributor to Expensify. His GH handle is @Pluto0104. cc @Pluto0104

**Comment by Pluto0104** [comment] 2023-09-13 21:46
If you assign me, I can raise the PR asap with @napster125. Thanks!

**Comment by Pluto0104** [comment] 2023-09-13 23:36
Hi, @sophiepintoraetz, so you mean I need to post my own proposal?

**Comment by Pluto0104** [comment] 2023-09-13 23:40
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Popovers overlapping with the Right-Hand Panel (RHP) when users click the "Forward" button in their browser.
### What is the root cause of that problem?
The problem stems from the fact that while the popovers are set up to close when users click outside or scroll down, they are not designed to close when the Right-Hand Panel (RHP) is opened. This issue is consistent across all popovers.
### What changes do you think we should make in order to solve the problem?
To address this, we propose adding an event listener to trigger the `closePopover()` function whenever a route change occurs within the `PopoverContextProvider`. Given that the action of opening the RHP corresponds to a route change, this step will ensure that any active popover is appropriately closed.

```js
React.useEffect(() => {
    const listener = () => {
        if (!activePopoverRef.current) {
            return;
        }
        const ref = activePopoverRef.current.anchorRef;
        closePopover(ref);
    };
    window.addEventListener('popstate', listener, true);
    return () => {
        window.removeEventListener('popstate', listener, true);
    };
}, [closePopover]);
```

Result:

https://github.com/Expensify/App/assets/136437976/6ff58723-8d2d-42c3-b3ab-3139cfb87480

**Comment by Pluto0104** [comment] 2023-09-14 11:17
@NicMendonca I'm just curious about why you assign @allroundexperts. can you please tell me about this?

**Comment by sophiepintoraetz** [comment] 2023-09-15 05:37
@Pluto0104 - we had an internal discussion and decided this was the best approach. Additionally, Sibtain had volunteered first. Ultimately, we as the BZ programme managers have final say as to what happens, thanks!

**Comment by sobitneupane** [comment] 2023-09-25 04:01
@allroundexperts Since you have worked on the functionality, do you have idea which PR caused this issue?

**Comment by sobitneupane** [comment] 2023-09-25 04:06
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane / @allroundexperts] The PR that introduced the bug has been identified. Link to the PR:

Edge case that is present from long time.
> * [ ]  [@sobitneupane / @allroundexperts] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

N/A
> * [ ]  [@sobitneupane / @allroundexperts] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

N/A
> * [ ]  [@sobitneupane / @allroundexperts] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane / @allroundexperts] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-09-25 04:06
**Regression Test Proposal**

1. Log in to the app and click on the user avatar to open the RHP.
2. Click anywhere else to close it.
3. Open any popover.
4. Press the forward button in the browser.
5. Verify that the popover disappears.

**Comment by dangrous** [comment] 2023-09-27 07:05
I might just update #3 to give some options of popovers, to make it easy. Otherwise looks good!

**Comment by NicMendonca** [comment] 2023-09-27 14:34
all set here, thanks everyone!

**Closed by NicMendonca** 2023-09-27 14:34 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 13:21
$1,800 payment approved for @allroundexperts based on BZ summary.

**Comment by sobitneupane** [comment] 2023-10-09 08:38
https://github.com/Expensify/App/issues/22953#issuecomment-1737497387

Requested payment on newDot

**Comment by JmillsExpensify** [comment] 2023-10-09 17:33
$1,500 payment approved fro @sobitneupane based on BZ summary.
