### ISSUE TITLE
Connect BA - Chase icon is broken

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33684] opened 2023-12-28 00:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the App
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS -> Bank account -> Connect online with Plaid
4. Choose Chase and continue the process until 1-st step with choosing an account
5. Notice that Chase icon is broken

## Expected Result:
Chase icon not broken

## Actual Result:
Chase icon is broken

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6327141_1703716643921!IMG_1510](https://github.com/Expensify/App/assets/78819774/7e17ca4f-6808-4cbb-a7d8-b35fcf44788a)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2023-12-28 01:12
This is probably related to the Expo changes which are on prod already.

>Reproducible in production?: Unable to check prod

It's probably on production.

**Comment by shubham1206agra** [comment] 2023-12-28 02:41
Dupe of https://github.com/Expensify/App/issues/33664 and I am already working on a fix

**Comment by JmillsExpensify** [comment] 2024-01-03 04:35
Great thanks! Closing this one.

**Closed by JmillsExpensify** 2024-01-03 04:35 UTC
Labels: Engineering, Daily, Overdue, Bug
