### ISSUE TITLE
Chat - Unexpected error when completing payment request.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14571] opened 2023-01-25 21:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com
2. Login with gmail account
3. Account A requests money from account B
4. Account B complete the requested payment.

## Expected Result:
No error message should be displayed after complete payment.

## Actual Result:
Unexpected error message occurs after payment is completed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.59.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/214699532-f970485f-b4b0-430c-9324-6454ea283ede.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-01-25 21:53
Could be the same root of cause https://github.com/Expensify/App/issues/14548

**Comment by luacmartins** [comment] 2023-01-25 22:04
That does seem to be related. It should be fixed now though. Can you please retest?

**Comment by mvtglobally** [comment] 2023-01-25 22:04
@luacmartins 
I am seeing this on Desktop now.. Related? 

https://user-images.githubusercontent.com/43995119/214701946-5f283e5b-a8fe-4227-b019-0888124b22be.mp4

**Comment by Luke9389** [comment] 2023-01-25 22:23
Reproducing locally with logs to see if this is a back end issue.

**Comment by mvtglobally** [comment] 2023-01-25 22:26
@luacmartins @Luke9389 I dont see anything in console, but in case you need logs, this is account used on my side applausetester++1014mvt@applause.expensifail.com

**Comment by Luke9389** [comment] 2023-01-25 22:32
Thanks for that info @mvtglobally.

@luacmartins these are the logs I'm getting 
```
2023-01-25T22:30:10.654318+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [hmmm] Throw ExpException - 0f7b9e631cada45edbf331aaf860f4a5 ~~ message: '402 Missing clientID' exceptionMessage: 'Auth PayMoneyRequest returned an error' exceptionFile: '/vagrant/Web-Expensify/lib/Auth.php' exceptionLine: '121' exceptionCode: '402'
2023-01-25T22:30:10.654443+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [trace] StackTrace start
2023-01-25T22:30:10.654559+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [trace] 0/3. file '/vagrant/Web-Expensify/lib/Auth.php' function '_standardResponseHandler' line '6773'
2023-01-25T22:30:10.654649+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [trace] 1/3. file '/vagrant/Web-Expensify/lib/ReportAPI.php' function 'payMoneyRequest' line '4076'
2023-01-25T22:30:10.654685+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [trace] 2/3. file '/vagrant/Web-Expensify/lib/ReportAPI.php' function 'payMoneyRequest' line '4131'
2023-01-25T22:30:10.654713+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [trace] 3/3. file '/vagrant/Web-Expensify/api.php' function 'payMoneyRequestElsewhere' line '2843'
2023-01-25T22:30:10.654776+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [trace] StackTrace end
2023-01-25T22:30:10.655258+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [warn] [OOPS!] API Threw: Auth PayMoneyRequest returned an error ExpException - 0f7b9e631cada45edbf331aaf860f4a5 ~~ message: '402 Missing clientID' exceptionMessage: 'Auth PayMoneyRequest returned an error' exceptionFile: '/vagrant/Web-Expensify/lib/Auth.php' exceptionLine: '121' exceptionCode: '402'
2023-01-25T22:30:10.655377+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [dbug] _send( expensidev2004.web.log.warn:1|c )
2023-01-25T22:30:10.671081+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] DB_Analytics - Connecting to database. ~~ attemptNumber: '1' host: '127.0.0.1' dbName: 'analytics'
2023-01-25T22:30:10.699538+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [benchmark] Stop timing 'DB Connect DB_Analytics' (took 0.0302 seconds)
2023-01-25T22:30:10.699621+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [dbug] DB_Analytics - INSERT INTO serverErrors( created, uuid, message, email, accountID, requestID, source ) VALUES( '2023-01-25 22:30:10', 'WARN_0e572d904e298e98b87914c754dd74f1', '[OOPS!] API Threw: Auth PayMoneyRequest returned an error ExpException - 0f7b9e631cada45edbf331aaf860f4a5', 'spider@animals.com', null, '8FwZ2U', 'api' );
2023-01-25T22:30:10.699659+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] Benchmark started:DB_Analytics - Executing query
2023-01-25T22:30:10.749430+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] Benchmark finished:DB_Analytics - Executing query ~~ time: '0.049474000930786'
2023-01-25T22:30:10.761684+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [push] Push_Service - Sending event ~~ channel: '[0: 'public-debugserverid5e9f713e07e22-7c516c908f6d4b57abbed4262e48a5ae']' eventName: 'debug' eventData: '{"level":"warn","message":"[OOPS!] API Threw: Auth PayMoneyRequest returned an error ExpException - 0f7b9e631cada45edbf331aaf860f4a5 ~~ message: '402 Missing clientID' exceptionMessage: 'Auth PayMoneyRequest returned an error' exceptionFile: '\/vagrant\/Web-Expensify\/lib\/Auth.php' exceptionLine: '121' exceptionCode: '402'"}'
2023-01-25T22:30:10.761779+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [trace] StackTrace start
2023-01-25T22:30:10.761810+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [trace] 0/3. file '/vagrant/Web-Expensify/lib/Auth.php' function '_standardResponseHandler' line '6773'
2023-01-25T22:30:10.761865+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [trace] 1/3. file '/vagrant/Web-Expensify/lib/ReportAPI.php' function 'payMoneyRequest' line '4076'
2023-01-25T22:30:10.761927+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [trace] 2/3. file '/vagrant/Web-Expensify/lib/ReportAPI.php' function 'payMoneyRequest' line '4131'
2023-01-25T22:30:10.761952+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [trace] 3/3. file '/vagrant/Web-Expensify/api.php' function 'payMoneyRequestElsewhere' line '2843'
2023-01-25T22:30:10.761964+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] [trace] StackTrace end
2023-01-25T22:30:10.762751+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] StoreUtils - Clearing all the stores.
2023-01-25T22:30:10.763715+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] TransactionStore cache fully cleared
2023-01-25T22:30:10.763903+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] ReportStore cache cleared
2023-01-25T22:30:10.764481+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] NVPStore - clear cache
2023-01-25T22:30:10.764593+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] NVPStore - clear cache
2023-01-25T22:30:10.767834+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] SharedInNVPStore - clear cache
2023-01-25T22:30:10.769021+00:00 expensidev2004 php-fpm: 8FwZ2U /api.php spider@animals.com !ecash1.2.59-1! ?api? [info] ReportDuplicatedTransactionsStore - Cache cleared
```

Looks like we're failing to send a clientID with that request.

**Comment by mvtglobally** [comment] 2023-01-25 22:36
@Luke9389 Should we log a different issue for this or you want to track here ?

**Comment by Luke9389** [comment] 2023-01-25 22:38
Let's track this one here until they're able to get some logs on [the other issue](https://github.com/Expensify/App/issues/14548). 

I'm not convinced they're the same root cause yet.

**Comment by roryabraham** [comment] 2023-01-25 22:51
> Looks like we're failing to send a clientID with that request.

@Luke9389 I _think_ this should have been fixed by https://github.com/Expensify/Auth/pull/7440, – [`clientID` was made optional in `PayMoneyRequest`](https://github.com/Expensify/Auth/pull/7440/files#diff-a0b41df4347e0aa00058a1894d220bfbb921c6a6a07e4827755d52d0b4144dceR33). Since that's been deployed, can we re-test this?

**Comment by mvtglobally** [comment] 2023-01-25 22:54
@roryabraham I am seeing it right now on this account across all requests. It seem to be specific to account. Since it's the same build, anything else I need to do to verify it?

**Comment by Luke9389** [comment] 2023-01-25 23:16
@roryabraham that sure does seem related. @mvtglobally are you testing with a new payment request each time?

**Comment by mvtglobally** [comment] 2023-01-25 23:44
@Luke9389 Yes, Tried a brand new request from an account I didn't have requests from before just now. Tried to pay with [applausetester++1014mvt@applause.expensifail.com](mailto:applausetester++1014mvt@applause.expensifail.com) and get the same blank screen

**Comment by luacmartins** [comment] 2023-01-26 00:06
I'm unable to reproduce this issue on any platform

https://user-images.githubusercontent.com/22219519/214721902-3549911d-8ce5-4f54-9a6c-f16dbcbab85a.mov

**Comment by Luke9389** [comment] 2023-01-26 00:15
Interesting @luacmartins, I don't see an option for you that says "I'll settle up elsewhere". Not sure why that's the case.


I'm also seeing quite a few of these errors in the logs from the past hour or so. 
https://www.expensify.com/_devportal/tools/logSearch/#sort=desc&size=10000&query=blob%3A%22402%20Missing%20clientID%22%20AND%20timestamp%3A%5B2023-01-25T00%3A00%20TO%202023-01-26T23%3A59%5D


@roryabraham is it possible that PR didn't fix this after all? Or maybe we need a front end change as well?

**Comment by luacmartins** [comment] 2023-01-26 00:19
@Luke9389 you can see that at around 0:19.

I couldn't find anything out of the ordinary in the [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2278f4a4bfcbbac427-SAN%22)+AND+timestamp:[2023-01-25T22:03:40.857Z+TO+2023-01-26T00:03:40.857Z]&index=logs_expensify-020598) for applausetester++1014mvt@applause.expensifail.com

The logs Luke shared above do look suspicious

**Comment by luacmartins** [comment] 2023-01-26 00:22
Actualyl @Luke9389 those logs are from earlier today, all before 2023-01-25 19:58 UTC. Auth deploy was done at around [2023-01-25 21:06 UTC](https://expensify.slack.com/archives/C07J32337/p1674680817041439) and I can't find any more instances of that error in the logs after that time

**Comment by Luke9389** [comment] 2023-01-26 00:28
Oh gotcha. Interesting. I just saw your ping in the thread so we'll discuss further there.

**Comment by thienlnam** [comment] 2023-01-26 00:37
https://expensify.slack.com/archives/C07J32337/p1674693393153289?thread_ts=1674692873.600099&cid=C07J32337

Resolved with auth deploy

**Closed** 2023-01-26 00:37 UTC
Labels: Engineering, Hourly

**Comment by Luke9389** [comment] 2023-01-26 00:38
Thanks @thienlnam. It is true that the unexpected error bug that we saw in the original description has been resolved. 

Later in the thread we began discussing a blank screen, which may or may not be related. 
@mvtglobally, can you open a new issue for the blank screen problem with reproduction steps?

We feel it's best to separate these two issues.

**Comment by mvtglobally** [comment] 2023-01-26 00:48
sure. I will ask team if they can repro and log with the steps
