### ISSUE TITLE
[HOLD for payment 2024-03-19] [HOLD for payment 2024-03-14] [HOLD for payment 2024-03-13] [Workflows] Workflow - Weekly submission frequency is not selected by default

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37764] opened 2024-03-05 15:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** nathanmulugetatesting@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/37213
## Action Performed:
1. Create a new Collect policy on OldDot
2. Enable the Collect workspace to show up on NewDot
3. Login to NewDot, then navigate to Settings > Workspaces. You should see your Collect workspace, click on it
4. Click on Workflows
5. Toggle the Submission frequency sub item. A submenu should open and observe the default value

## Expected Result:
Weekly should be set as the default value

## Actual Result:
No value is set as the default value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a0b3c17e-9462-472f-8a22-8e55ddae43c6

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-05 15:16
@bondydaa  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment] 2024-03-05 15:19
cc @lakchote

**Comment by Tony-MK** [comment] 2024-03-05 16:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workflow - Weekly submission frequency is not selected by default

### What is the root cause of that problem?

The `WorkspaceAutoReportingFrequencyPage` component only finds the selected option if `policy?.autoReportingFrequency` is present.

https://github.com/Expensify/App/blob/5199604ac28f9db9fdcdc8bf7e8b4ce4e406ded8/src/pages/workspace/workflows/WorkspaceAutoReportingFrequencyPage.tsx#L50

Therefore, if `policy?.autoReportingFrequency` is nullified, none of the options will be selected.

### What changes do you think we should make in order to solve the problem?


Change the line above to also consider the default frequency which should be `CONST.POLICY.AUTO_REPORTING_FREQUENCIES.WEEKLY` when finding the selected option.

```
const isSelected = policy?.autoReportingFrequency ? 
 policy.autoReportingFrequency === frequencyKey : 
 CONST.POLICY.AUTO_REPORTING_FREQUENCIES.WEEKLY === frequencyKey;
```

**Comment by luacmartins** [comment] 2024-03-05 19:53
Hmm I actually think the correct solution is to optimistically set weekly as the `autoReportingFrequency`

**Comment by roryabraham** [comment] 2024-03-06 06:13
requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1709690076933769?thread_ts=1709689981.868779&cid=C9YU7BX5M

**Comment by luacmartins** [comment] 2024-03-06 14:54
Demoting to NAB. The remaining issue will be fixed by https://github.com/Expensify/Auth/pull/10076

**Comment by luacmartins** [comment] 2024-03-20 00:10
We're good to close here since the PR was handled internally - https://github.com/Expensify/App/pull/37786

**Closed by luacmartins** 2024-03-20 00:10 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
