### ISSUE TITLE
[Search v1] Tracked expenses show with _FAKE_ on the Search page

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41985] opened 2024-05-10 15:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.72-1
**Reproducible in staging?:** Y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1715353965643159?thread_ts=1715336686.106629&cid=C036QM0SLJK

## Action Performed:
1. Go to global create > `Track expense`
2. Track an expense to the selfDM
3. Go to avatar > Troubleshoot > New search page
4. Observe the tracked expense with the `_Fake_` To/From fields in the table on the Search page

## Expected Result:
The `From:` should be the account holder (i.e `Tom James` and the `To:` should be the name of the selfDM chat (i.e `Tom James (You)`. 

## Actual Result:
_FAKE_ to/from fields. 

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/197cdf4b-044e-4c1a-8bc2-6920c15b2d92">
<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/8979e5fc-fc3c-4924-8043-5f3aac70f778">
<img width="1510" alt="image" src="https://github.com/Expensify/App/assets/16232057/5730d675-6238-4f4b-aad4-9ec506a7ffd0">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01784dd4287018110a</li>
        <li>Upwork Job ID: 1788993640843829248</li>
        <li>Last Price Increase: 2024-05-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by trjExpensify** [comment] 2024-05-13 12:36
@luacmartins is going to look at this later in the week.

**Comment by luacmartins** [comment] 2024-05-15 00:37
Gonna work on this tonight!

**Comment by trjExpensify** [comment] 2024-05-15 15:55
> Gonna work on this tonight!

Why did yah move this into Hot Picks? 🤔

**Comment by luacmartins** [comment] 2024-05-16 11:54
Looking at this now

**Comment by trjExpensify** [comment] 2024-05-16 12:10
> Just wanted to check that you're paying attention to these 😉 Jk jk I moved it by mistake along with the other issues when looking for volunteers.

Hahah.. 4D chess, huh? Just you wait... 😂

**Comment by luacmartins** [comment] 2024-05-16 14:14
PR in review.

**Comment by trjExpensify** [comment] 2024-05-23 23:04
AuthPR deployed to prod. Is that it here or is there more to come?

**Comment by luacmartins** [comment] 2024-05-27 14:56
That was the only PR needed for the track case. @trjExpensify could you test again and see if the issue is fixed or there are other `__FAKE__` edge cases?

**Comment by trjExpensify** [comment] 2024-05-28 20:32
Track is looking good! 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/177275fe-9344-4d4f-a853-77253dfc49df">

**Comment by luacmartins** [comment] 2024-05-28 20:35
We can close this issue then since it's all internal and PR is deployed

**Closed by luacmartins** 2024-05-28 20:35 UTC
Labels: Reviewing, Daily, Internal, Bug
