### ISSUE TITLE
[HOLD for payment 2023-02-02] Manage members: Opacity reduces pressing on the workspace admin

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13769] opened 2022-12-21 21:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Settings.
2. Go to Workspaces.
3. Create or open any existing workspace.
4. Press on admin.

## Expected Result:
Shouldn’t reduce opacity bcz its not a selectable item.

## Actual Result:
Opacity reducing like normal active item.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Windows OS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.42-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209006529-777a04f8-5b8f-4754-83ff-16ff06308f78.mp4

https://user-images.githubusercontent.com/43996225/209006553-736775be-b9a3-45b0-b98a-4e6b41e22b77.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jatinsonijs 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671602565821529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01abccdea17bf0637e</li>
        <li>Upwork Job ID: 1608221055756103680</li>
        <li>Last Price Increase: 2022-12-28</li>
    </ul>
</details>

**Comment by sketchydroide** [comment] 2022-12-22 12:48
I would say that this might be a bug, but it's weird that you can select it as well.
Maybe we shoudl not even show the ceckbox for the admin, right?
Will bring this to slack to get some opinions.

**Comment by sketchydroide** [comment] 2022-12-27 10:42
I will post on the ope source channel about this, but I would adivise either not show the user, or not be selectable (this includes hiding the checkbox for this users)

**Comment by sketchydroide** [comment] 2022-12-28 10:53
So it was decided that just disabling the opacity for the admins was enough as we already show an error on mobile and a tip on desktop and web

**Comment by tjferriss** [comment] 2022-12-28 21:59
@sketchydroide sounds like you're going to make the fix so I'm going to add the internal label.

**Comment by sketchydroide** [comment] 2022-12-28 22:20
it's a bit more complex than that actually, but for now that sounds good.
There is a bit more context on [this slack thread](https://expensify.slack.com/archives/C01SKUP7QR0/p1672155840925419)
But basically I raised some concerns about the UX being quite different on mobile and desktop, and there might be some level of planning involved.

**Comment by sketchydroide** [comment] 2022-12-29 10:39
@JmillsExpensify do you think this should still be a bug atm? I feel there is a bug, still, but kinda maybe a feature as well, as we might use similar patterns elsewhere or in the future.

CCing @Puneet-here and @luacmartins as you might have some input on this

**Comment by JmillsExpensify** [comment] 2022-12-29 17:28
I think it is a bug, but I think it's one of those bugs where solving it requires a broader plan, so we need a process to figure out how to handle these. Like reliable notifications or sequence numbers, they don't fit in WAQ. Perhaps for now we remove any issue with the `planning` label from the WAQ report, just like we're doing for holds.

**Comment by sketchydroide** [comment] 2023-01-02 10:38
> Perhaps for now we remove any issue with the planning label from the WAQ report

yep I think that would make sense, specially since they take way more time to be finished.

@luacmartins I think you should be back from OOO let me know your thoughts on this (not sure if you know anything, but your knowledge of forms would probably help)

**Comment by luacmartins** [comment] 2023-01-04 19:01
Left a comment in the [thread](https://expensify.slack.com/archives/C01SKUP7QR0/p1672858896194739?thread_ts=1672155840.925419&cid=C01SKUP7QR0)

**Comment by sketchydroide** [comment] 2023-01-05 10:46
Your input on the thread sounds good, I think I can do something about it.
Just for making it easier here is @luacmartins suggestion
```
So for consistency, I think that we should allow the user to select any checkbox they want, but show an error when they try to submit it. That will remove the growl and UI/UX inconsistencies.
```

I will updat this GH to better exlpain the issue and the solution

**Comment by sketchydroide** [comment] 2023-01-09 10:40
I might be able to work on it this week if not I'll let someone else pick it up as I'm going OOO after tomorrow for a week

**Comment by tjferriss** [comment] 2023-01-11 18:47
@sketchydroide should we look for a volunteer in Slack or could we add the `First Pick` label?

**Comment by JmillsExpensify** [comment] 2023-01-11 20:26
Given that this `bug` is three weeks old, yes I think we should change tact and either try to get more internal or external people involved. I'd even say external to help jumpstart urgency.

**Comment by sketchydroide** [comment] 2023-01-11 21:19
I would be happy to take it once I get back, but probably best it's an external and we get it sorted faster

**Comment by JmillsExpensify** [comment] 2023-01-16 23:27
What's the next step here? Let's get on this one. We just lost a week.

**Comment by luacmartins** [comment] 2023-01-16 23:56
I can pick this one up, if you'd like @sketchydroide.

**Comment by luacmartins** [comment] 2023-01-16 23:59
I see that @sketchydroide is ooo. I'll take this over until he's back.

**Comment by luacmartins** [comment] 2023-01-16 23:59
Gonna work on this tomorrow!

**Comment by luacmartins** [comment] 2023-01-18 00:05
PR [up](https://github.com/Expensify/App/pull/14347)

**Comment by sketchydroide** [comment] 2023-01-20 12:35
Thanks for picking this up @luacmartins

**Comment by luacmartins** [comment] 2023-01-25 02:38
PR merged! Waiting on deploys!

**Comment by jatinsonijs** [comment] 2023-02-04 06:11
@tjferriss Gentle reminder. Regression period is passed (2 feb).

**Comment by tjferriss** [comment] 2023-02-06 23:44
Sorry for the delay. The original Upworks post was closed so I've created a new one here:https://www.upwork.com/jobs/~0197b675e1adf982dc

@jatinsonijs can you please apply here and we'll get the payment sorted.

**Comment by Johannes-Harald** [comment] 2023-02-07 04:56
Of course I have not seen the boilerplate React but it seems to be an onClick instruction making the opacity reduce.

**Comment by tjferriss** [comment] 2023-02-08 06:22
The offer is pending. Once you accept @jatinsonijs, I can make payment.

**Comment by jatinsonijs** [comment] 2023-02-08 09:12
Accepted @tjferriss

**Comment by tjferriss** [comment] 2023-02-09 23:19
The payment has been made.

**Closed by tjferriss** 2023-02-09 23:19 UTC
Labels: Weekly, Internal, Awaiting Payment, Bug
