### ISSUE TITLE
[$1000] Incorrect Redirection on Page Crash: 'Go Back to Home Page' Button Opens Last Visited Page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21516] opened 2023-06-25 14:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with User A (A mobile number) and create a Workspace
2. Add User B as member
3. Create a new room in restricted mode within that workspace
4. Click on Split money
5. Set amount and description > split
6. Open the split money box from both user A and user B
7. Click on user details and it does not open.
You will see “Hmm... it's not here
Oops, this page cannot be found: Go back to Home page”
8. Click on “Go back to home page”
Verify:
9. Verify if it leads to last visited page or homepage

## Expected Result:
Clicking on the "Go Back to Home Page" button should redirect the user to the home page of the application.
## Actual Result:
Clicking on the "Go Back to Home Page" button does not lead to the home page but rather opens the last visited page
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:**  needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2f4b4221-a2ca-4897-abce-f0856d25eacb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687037591793089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c11837b0985d271a</li>
        <li>Upwork Job ID: 1673363522060816384</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2023-06-28 20:34
@0xmiroslav thoughts on @hungvu193's proposal?

**Comment by puneetlath** [comment] 2023-06-30 15:59
@0xmiroslav bump on the proposal review, thanks!

**Comment by avi-shek-jha** [comment] 2023-07-03 20:00
> I am not able to reproduce this. @avi-shek-jha if this is still reproducible, can you please share video with full reproduction step? Please try to test with 2 fresh accounts.

Hi @oxmiroslav, The "Go back to home page"  button only appears during certain page crashes. To reproduce this, we need to first trigger a page crash. Unfortunately, the steps that triggered a page crash when I reported this, no longer trigger a page crash now.  Also, it is not possible to specify where the page crash will occur in the future. If I get one in the future, I will surely let you know. Perhaps, the internal team can help with this.

**Comment by puneetlath** [comment] 2023-07-06 00:34
I'm going to go ahead and close this since it seems we are no longer able to reproduce. Feel free to report it again if you're able to come up with consistent steps.

**Closed by puneetlath** 2023-07-06 00:34 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Overdue, Bug

**Comment by avi-shek-jha** [comment] 2023-08-04 21:29
@puneetlath Now we have consistent reproducible steps. Take a look if you want to: https://expensify.slack.com/archives/C049HHMV9SM/p1690851151974449
