### ISSUE TITLE
[$250] QBO - The toggles are enabled and disabled twice in Advanced settings

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45201] opened 2024-07-10 19:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4706857
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition
QBO connection is established in the workspace
1. Navigate to workspace settings > Accounting
2. Click on Advanced
3. Enable and disable the toggles of the items a few times
4. Observe how the toggles are behaving after enabling and disabling a few times

## Expected Result:
Enabling and disabling occurs only once

## Actual Result:
Toggles are enabled and disabled twice when the action is performed only once

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1fc98280-3c82-4971-a2b4-748c23dd6281

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01123cce366aa8f37d</li>
        <li>Upwork Job ID: 1811816997002609504</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 103330245</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aldo-expensify</details>

**Comment by lanitochka17** [comment] 2024-07-10 19:12
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-10 19:12
We think that this bug might be related to #wave-collect - Release 1

**Comment by zanyrenney** [comment] 2024-07-10 21:30
I am OOO until Tuesday 16th. This was assigned after my working day, I am readding the bug label.

**Comment by ahmedGaber93** [comment] 2024-07-15 07:37
Waiting on proposals

**Comment by zanyrenney** [comment] 2024-07-17 14:21
I'm back @puneetlath so taking this one back! thanks

**Comment by ahmedGaber93** [comment] 2024-07-18 05:59
No proposals yet

**Comment by ahmedGaber93** [comment] 2024-07-23 18:23
No proposals yet

**Comment by dangrous** [comment] 2024-07-24 20:44
Question about this - do the toggles eventually end up in the right position? Like, even if they're sort of moving on their own at the end, if the last thing the user tried to do was turn them off, they end up off, and vice versa?

I'm asking because my guess is that each time we update from the backend we send the full settings object and so if we're trying to update a lot of things at once, it might not be fully updated on QBO's side yet, but eventually will get there... but if it's not ending up in the preferred state then there might be something else going on.

This will definitely be affected by us refactoring into more individual commands, but I'm not sure how haha

**Comment by ahmedGaber93** [comment] 2024-07-25 10:27
> do the toggles eventually end up in the right position?

@dangrous Not always.

Steps I tested it.
1. enable "Invite employees" then enable "Auto-create entities" 
2. disable "Invite employees" then disable "Auto-create entities" 
3. enable "Invite employees"

The final result is different every time I tested it.

<details>
<summary>videos</summary>

https://github.com/user-attachments/assets/94cbb600-43d7-4c5c-b494-0798b0bb6179



https://github.com/user-attachments/assets/8ef40339-da64-46b6-b963-b2c03d360972





</details>

**Comment by rezkiy37** [comment] 2024-07-29 10:59
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by ahmedGaber93** [comment] 2024-07-29 11:13
@dangrous do you work on fix for this from BE side? or we can move forward with @rezkiy37?

**Comment by rezkiy37** [comment] 2024-07-29 11:20
I need to investigate the update's optimistic, success, and failure data. I guess it could conflict with the backend response.

**Comment by ahmedGaber93** [comment] 2024-07-29 11:27
Yeah, Also you can check `sync` request behavior, do we send `sync` request after every change?

**Comment by rezkiy37** [comment] 2024-07-29 14:10
Guys, how to connect the debug QBO connection properly? Does it work on the dev?

cc @lanitochka17 @ahmedGaber93 @zanyrenney

**Comment by ahmedGaber93** [comment] 2024-07-29 14:29
@rezkiy37 Yest, it works on dev. You just need to remove `.dev` from URL after click connect and complete the steps


https://github.com/user-attachments/assets/80e6450e-d196-4849-ad5f-716520205896

**Comment by rezkiy37** [comment] 2024-07-29 14:49
@ahmedGaber93, do you have testing accounts in QBO?

**Comment by rezkiy37** [comment] 2024-07-30 13:57
Actively working on the issue. I am trying to figure out what invokes those updates. I compare it with the "More features" page, which works properly.

**Comment by dangrous** [comment] 2024-07-30 18:18
Hm yeah let us know what you figure out @rezkiy37 - it feels like this will likely have a backend component as well but I think sorting out the front end will help us confirm that. I'll assign you!

**Comment by rezkiy37** [comment] 2024-07-31 17:05
Actively working on the issue. I have 3 places to investigate why the bug happens:
1. The difference for those toggles is invoking **GetMissingOnyxMessages** once **Pusher** sends updates regarding changes.  [OnyxUpdates.apply()](https://github.com/Expensify/App/blob/55be36f88183345741ec86beffec9c4a111c740f/src/libs/actions/OnyxUpdates.ts#L98) handles **GetMissingOnyxMessages's** response . Looks like right after this response the toggles are going crazy.
2. The [OnyxUpdates.applyPusherOnyxUpdates()](https://github.com/Expensify/App/blob/55be36f88183345741ec86beffec9c4a111c740f/src/libs/actions/OnyxUpdates.ts#L62) updates **Onyx** state because **Pusher** sends progress status messages.
3. [withPolicyConnections.tsx](https://github.com/Expensify/App/blob/main/src/pages/workspace/withPolicyConnections.tsx) is not complex, but probably it has extra rerenders.

**Comment by rezkiy37** [comment] 2024-08-01 15:28
Other tasks occupied me today. Will continue tomorrow.

**Comment by rezkiy37** [comment] 2024-08-02 14:21
I've investigated the problem. So the bug happens because of **GetMissingOnyxMessages**. This request calls after each click on the toggles. It has huge responses sometimes and invokes redundant intermediate updates. I am attaching a video example of skipping the command's responses and ignoring their updates. So definitely we need a backend engineer to reduce the amount of calls and probably batch into one instead of ten updates.

<details><summary>Details</summary>

https://github.com/user-attachments/assets/8b424368-d5c7-42e4-95a3-0d1acc3c6c8a

</details> 

cc @dangrous @ahmedGaber93

**Comment by zanyrenney** [comment] 2024-08-02 17:05
Do you mean one of the internal Expensify team?

**Comment by rezkiy37** [comment] 2024-08-02 17:08
@zanyrenney  Yes, sure.

**Comment by rezkiy37** [comment] 2024-08-02 17:09
There is this note https://github.com/Expensify/App/issues/45201#issuecomment-2258938420 as well.

**Comment by ahmedGaber93** [comment] 2024-08-02 18:08
Not overdue, we still discuss the Potential solution.

**Comment by dangrous** [comment] 2024-08-02 20:29
So we're working on refactoring the QBO API commands [here](https://github.com/Expensify/Expensify/issues/398335) (internal only link sorry!) into individual commands - e.g. instead of `UpdatePolicyConnectionConfiguration` we'll call `UpdateQuickbooksOnlineSyncCustomers` or `UpdateQuickbooksOnlineEnableNewCategories` or `UpdateXeroAutoSync` or whatever. Do we think that will help at all?

And to clarify, too - when you say "we need a backend engineer to reduce the amount of calls and probably batch into one instead of ten updates" - are you referring to the number of calls inside `GetMissingOnyxMessages`? or inside the QBO commands?

Lastly, cc @aldo-expensify since you did some more of the actual implementation here and might have some ideas.

**Comment by aldo-expensify** [comment] 2024-08-03 00:04
ahhhhhhh, I wonder if the multiple `GetMissingOnyxMessages` we see is because of:

- Each change in a setting (each toggle change) creating a resync job in the backend. So your multiple changes in a short time end up creating multiple resync jobs that are running together, all of them creating onyx updates, and the front end goes a bit crazy with the onyx updates arriving not in perfect order.

Would have to investigate if this is true ^

**Comment by rezkiy37** [comment] 2024-08-05 09:00
> And to clarify, too - when you say "we need a backend engineer to reduce the amount of calls and probably batch into one instead of ten updates" - are you referring to the number of calls inside GetMissingOnyxMessages? or inside the QBO commands?

I mean the number of calls inside **GetMissingOnyxMessages**.

**Comment by rezkiy37** [comment] 2024-08-05 13:38
> ...and the front end goes a bit crazy with the onyx updates arriving not in perfect order.

Exactly!

**Comment by ahmedGaber93** [comment] 2024-08-05 14:31
Not overdue, we still discuss the Potential solution.

**Comment by ahmedGaber93** [comment] 2024-08-07 22:35
Not overdue, we still discuss the Potential solution.

**Comment by ahmedGaber93** [comment] 2024-08-13 16:10
> Would have to investigate if this is true ^

@aldo-expensify related to frontend part, me and @rezkiy37 agree with that. What is the potential solution then?
> and the front end goes a bit crazy with the onyx updates arriving not in perfect order.

**Comment by aldo-expensify** [comment] 2024-08-13 20:37
I tested switching fast the toggles and I confirmed that the sync IS jobs are running in parallel, so I think [this guess](https://github.com/Expensify/App/issues/45201#issuecomment-2266283779) is correct

> What is the potential solution then?

I'm not sure. I imagine that the best would be something like:

Prevent running multiple sync jobs in parallel by having a logic like: If a configuration changes while a sync job is already running, a new sync job should be queued to run after, but if there is already a sync job queued, don't queue a second one

I'm not sure if this is feasible or not. @francoisl do you know if we can achieve something like this?

cc @dangrous @lakchote since this affects all our integrations (not only QBO)

**Comment by aldo-expensify** [comment] 2024-08-13 20:37
Removing `External` for now, since this seems like something we need to fix in the backend

**Comment by francoisl** [comment] 2024-08-13 20:48
Yeah this is something I pointed out was going to happen in the NetSuite design doc, but it was decided to continue with the current design.

I think what you'd need here is to queue a non-repeating, `unique:true` bedrock job that takes care of starting the IS accounting sync.

**Comment by francoisl** [comment] 2024-08-13 20:52
Also to clarify:

> If a configuration changes while a sync job is already running, a new sync job should be queued to run after, but if there is already a sync job queued, don't queue a second one

Were you referring to bedrock jobs? As far as I can tell, the API commands to modify QBO settings don't queue bedrock jobs at the moment, right?
I also can't think of a way to do this without bedrock jobs with our current architecture, because 2 API requests to update the QBO configuration could be processed by different webservers & IS servers, that don't know anything about each other.

**Comment by aldo-expensify** [comment] 2024-08-13 20:54
> Were you referring to bedrock jobs?

Nop, I was just talking about IS jobs, and I didn't know if it was possible to "queue" or avoid duplication. What you suggested about using bedrock jobs makes sense to me!

**Comment by aldo-expensify** [comment] 2024-08-13 22:24
I'll try to tackle this implementing a bedrock job.

**Comment by zanyrenney** [comment] 2024-08-16 13:45
how are you getting on with this one @aldo-expensify ?

**Comment by aldo-expensify** [comment] 2024-08-16 17:32
I haven't got to it yet, I'll give it some time today

**Comment by aldo-expensify** [comment] 2024-08-17 00:53
PR up: https://github.com/Expensify/Web-Expensify/pull/43173

**Comment by zanyrenney** [comment] 2024-08-21 11:01
Nice, good work on the PR. @aldo-expensify - looks like the comments from Franc and Rocio have been resolved. Can you merge this today?

**Comment by ahmedGaber93** [comment] 2024-08-21 19:46
I don't think this issue is need a C+ yet. Unassigning me

**Comment by aldo-expensify** [comment] 2024-08-21 20:57
The PR https://github.com/Expensify/Web-Expensify/pull/43173 is in staging

**Comment by rezkiy37** [comment] 2024-08-22 08:34
It works properly now in staging.

https://github.com/user-attachments/assets/e1e7a2dd-953c-4162-9998-70e9c86b9b0c

**Closed** 2024-08-23 01:13 UTC
Labels: Reviewing, Daily, Internal, Bug
