### ISSUE TITLE
[$500][Image] Web - Profile - The avatar is highlighted with a blue frame

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10599] opened 2022-08-26 13:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Go to Profile>Upload photo
3. Choose the photo>Open
4. Press "Esc" key

## Expected Result:
After canceling the upload of the photo using the Esc key, the avatar should not be highlighted with a blue frame

## Actual Result:
After canceling the photo upload using the Esc key, the avatar is highlighted with a blue frame

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.91.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186916573-8072a367-dd70-47eb-99d8-d1bc493ccf53.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by varshamb** [comment] 2022-08-26 15:15
### Proposal 

Use `PressableWithoutFocus` in `AvatarWithImagePicker`.

**Comment by varshamb** [comment] 2022-08-26 16:40
@parasharrajat 
I read the below in contribution policy and interpreted that it is allowed to Propose even before Label `External`. Please correct me if I am wrong. 


![image](https://user-images.githubusercontent.com/111683206/186951760-2398defe-26dc-46c2-a564-4176d8de5f59.png)

**Comment by varshamb** [comment] 2022-08-28 12:10
@parasharrajat  Thanks.

**Comment by NikkiWines** [comment] 2022-08-29 08:28
Able to reproduce this on staging, looks like it's good for an external issue 👍

**Comment by aimane-chnaif** [comment] 2022-09-08 08:59
### **Proposal**
https://github.com/Expensify/App/blob/159249bb82317fcd6bd06bc8d4f9127c300a9f9c/src/components/AvatarWithImagePicker.js#L224-L226
Add this props to Pressable component:
```
                    onMouseDown={e => e.preventDefault()}
```
demo video: https://drive.google.com/file/d/1qXw3l1MhKIQqcfDytCFJZuFEYamqX-Fl/view?usp=sharing

**Comment by varshamb** [comment] 2022-09-16 16:17
@NikkiWines @JmillsExpensify no one is assigned to this issue

**Comment by NikkiWines** [comment] 2022-09-19 07:53
Ah, sorry, this is my bad. Unassigned myself too quickly after the `External` label was assigned so it also unassigned @JmillsExpensify. Re-applying the label.

**Comment by MitchExpensify** [comment] 2022-09-21 01:35
[Upwork Job](https://www.upwork.com/ab/applicants/1572398925555118080/suggested)

**Comment by varshamb** [comment] 2022-09-24 18:36
@MitchExpensify no one is assigned

**Comment by MitchExpensify** [comment] 2022-09-26 17:58
> @MitchExpensify no one is assigned

Good catch! I reassigned @NikkiWines , We also need a C+ right Nikki?

**Comment by NikkiWines** [comment] 2022-09-27 08:06
Hmm the auto-assigner should have taken care of this - going to try applying the label again

**Comment by dhairyasenjaliya** [comment] 2022-09-27 19:32
**Proposal**

- We should add `style={styles.noSelect}` to `<Pressable>` in below file 

https://github.com/Expensify/App/blob/2bef1705d5aac60c9463cc0f080155dc9925d033/src/components/AvatarWithImagePicker.js#L243-L245

- Reason why we should not use `onMouseDown={e => e.preventDefault()}` is that if we add preventDefault() it will lose focus once we press the escape key, here in our code base we are supporting Accessibility for that reason I think we should keep focus to the same component as the user has not updated profile picture yet and still can navigate with the keyboard 

**Result**

https://user-images.githubusercontent.com/47522946/192618188-04892830-ca29-4279-83c3-f69dd2ff3388.mov

**Comment by dhairyasenjaliya** [comment] 2022-09-27 19:44
@parasharrajat AFAIR all the outline issues throughout the app were only found out in m-Safari so I do think this one is different issue as this affects chrome as well

**Comment by dhairyasenjaliya** [comment] 2022-09-29 10:57
hello @parasharrajat finally found the PR that causes outline globally as we have added an outline on pressing tabs and I think we manually need to treat those issues where we don't want to highlight component  PR https://github.com/Expensify/App/issues/8608

**Comment by dhairyasenjaliya** [comment] 2022-10-03 06:40
@parasharrajat yup still reproduced in the latest version: v1.2.10-1


https://user-images.githubusercontent.com/47522946/193515447-087b7b13-21e1-452f-9e33-418e01f57181.mp4

**Comment by parasharrajat** [comment] 2022-10-03 10:17
Ok, Thanks @dhairyasenjaliya. This issue is not happening on the Firefox browser. 

Back to proposals. 

@dhairyasenjaliya 's proposal breaks the focus on tab navigation. 
@varshamb works fine but I found that once the user closes the edit avatar page, the user is not able to set the focus back to the page. 

1. Normally clicking anywhere on the profile page and then pressing tab should take the focus to next focusable element on the page. But I am not able to do it once the edit modal is closed. 


Note: user should be able to use tab navigation and open the menu by pressing enter while profile avatar is focused.

**Comment by parasharrajat** [comment] 2022-10-03 10:18
Waiting for proposals.

**Comment by aldo-expensify** [comment] 2022-10-06 18:17
No overdue, holding now

**Comment by aldo-expensify** [comment] 2022-10-06 18:17
Changing to `Monthly` while in hold.

**Comment by mallenexpensify** [comment] 2022-11-01 17:59
Off hold [per this comment ](https://github.com/Expensify/App/issues/10894#issuecomment-1297788096)and doubled price to $500
New Upwork job 
https://www.upwork.com/jobs/~01dc978d09cea79af1

**Comment by Beamanator** [comment] 2022-11-02 09:22
Yep thanks @mallenexpensify 👍

**Comment by mallenexpensify** [comment] 2022-11-04 01:01
Doubled price two days ago, not rushing this one, it's a minor bug

**Comment by railway17** [comment] 2022-11-04 13:46
### Proposal

I read the issue description and could reproduce it on my side.

Blue border is displaying because we have the below `box-shadow` CSS in the `index.html`
```
        :focus-visible {
            outline: 0;
            box-shadow: inset 0px 0px 0px 1px #0185ff;
        }
```
![image](https://user-images.githubusercontent.com/29966461/199984995-8f33795d-8941-4773-936f-4ae0649c96f3.png)

So, we can fix this issue in 3 ways.
1. We can remove this style from index.html (But I don't think it is good way because it may be used in other components)
2. We can add the inline style like below in `src/components/AvatarWithImagePicker.js`
```diff
        return (
            <View style={[styles.alignItemsCenter, ...additionalStyles]}>
                <Pressable
+                    style={[styles.noSelect]}
                    onPress={() => this.setState({isMenuVisible: true})}
                >
                    <View style={[styles.pRelative, styles.avatarLarge]}>

```
3. We may use `PressableWithoutFocus` component instead of `Pressable` like below
```diff
         return (
             <View style={[styles.alignItemsCenter, ...additionalStyles]}>
-                <Pressable
+                <PressableWithoutFocus
                     onPress={() => this.setState({isMenuVisible: true})}
                 >
                     <View style={[styles.pRelative, styles.avatarLarge]}>
...
                             )}
                         </AttachmentPicker>
                     </View>
-                </Pressable>
+                </PressableWithoutFocus>
                 <ConfirmModal
                     title={this.state.errorModalTitle}
                     onConfirm={this.hideErrorModal}


```

**Comment by mallenexpensify** [comment] 2022-11-07 17:07
@parasharrajat please review @railway17 's proposal when you're able

**Comment by railway17** [comment] 2022-11-08 12:44
@parasharrajat 
Could you kindly review my proposal today?
I have an idea for another issue, but still waiting for your review because I can't submit multiple proposals at a time.
Thank you.

**Comment by parasharrajat** [comment] 2022-11-08 13:56
>  how I can become an experienced contributor
There is still time :smile:. 

Yeah, reviewing it now.

**Comment by parasharrajat** [comment] 2022-11-08 14:40
Overall, this might be the right time to look back at the old solutions and the current state of the app to understand what can be done to fix this issue. 

My suggestion is that you test your solution thoroughly and suggest alternatives to problems that they cause or find a solution to overcome those as well. 

1. Tab navigation focus is useful. 
2. Is there a solution that can be used to fix this issue without breaking the tab navigation focus? 

Let's discuss this to reach a conclusion.

**Comment by parasharrajat** [comment] 2022-11-08 15:05
Mainly a proposal should not match with existing ones. Even if we decide to go with an old posted solution. the Original author will be hired to work on that.

**Comment by mallenexpensify** [comment] 2022-11-09 00:27
@railway17 specifically [from CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=Note%3A%20Before%20submitting%20a%20proposal%20on%20an%20issue%2C%20be%20sure%20to%20read%20any%20other%20existing%20proposals.%20Any%20new%20proposal%20should%20be%20substantively%20different%20from%20existing%20proposals.)
> Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. Any new proposal should be substantively different from existing proposals.

**Comment by aldo-expensify** [comment] 2022-11-11 19:33
Having a look at this issue again, I'm not really convince about doing anything... why do we think there shouldn't be a blue frame if the focus is in the avatar? it is an input after all. If you tab around that page and press enter when the blue frame appears in the avatar, you get the modal to upload a new picture, which makes 100% sense to me. If we remove the blue frame, how would the user know that the avatar is focused and that pressing enter will make the modal appear?

**Comment by JmillsExpensify** [comment] 2022-11-11 19:56
Great point. I agree with you.

**Comment by aldo-expensify** [comment] 2022-11-11 20:04
Great, closing then :)

**Closed by aldo-expensify** 2022-11-11 20:04 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
