### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] QAB - Error shows up when submitting split distance expense via split manual shortcut in QAB

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50694] opened 2024-10-13 17:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to group chat (more than 2).
3. Click + > Split expense > Manual.
4. Split a manual expense in the group chat.
5. Click FAB.
6. Click Split manual under Quick action.
7. Click Distance.
8. Submit a split distance expense.

## Expected Result:
No error will show up when submitting split distance expense via split manual shortcut in QAB.

## Actual Result:
Error shows up when submitting split distance expense via split manual shortcut in QAB.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f15b6f50-ef24-420c-9d36-8edaf9c468b1

  </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845889937723990662</li>
        <li>Upwork Job ID: 1845889937723990662</li>
        <li>Last Price Increase: 2024-10-21</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104666501</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by IuliiaHerets** [comment] 2024-10-13 17:15
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by slafortune** [comment] 2024-10-14 18:07
Was able to recreate 👍

**Comment by neil-marcellini** [comment] 2024-10-16 19:37
@Krishna2323 and @twilight294, would you please update your root cause and suggested solutions to be a bit more specific?

For @Krishna2323's proposal:
What distance request calculations happen on the confirmation page that shouldn't be skipped? Why were we skipping the confirmation before and why should we no longer skip it?

For @twilight294:
> When we create a manual split request, and then from quick actions create a distance request due to shouldSkipConfirmation being true, we create a split request for distance instead of a distance request:

Ok, that makes sense that it breaks when calling SplitBill. Shouldn't we change the type when distance is used instead of leaving it as manual? Why is the solution to not skip the confirmation for group chats? What exact problem does that solve?

Can we not skip confirmation specifically for distance expenses, or can we make it work while skipping confirmation. It would definitely be good to figure out why we are skipping the confirmation page in the first place.

**Comment by mollfpr** [comment] 2024-10-17 11:15
Sorry for the late response. I'm reviewing it now.

**Comment by mollfpr** [comment] 2024-10-21 16:58
>Can we not skip confirmation specifically for distance expenses, or can we make it work while skipping confirmation. It would definitely be good to figure out why we are skipping the confirmation page in the first place.

We don't skip confirmation on QAB split distance, because the `shouldSkipConfirmation` is retained `false`.

https://github.com/user-attachments/assets/5340061b-084a-498b-9a9b-17f25d2c8580

The issue is when on QAB split expense, the `shouldSkipConfirmation` is `true`, similar to https://github.com/Expensify/App/issues/47021. I think the correct solution is to avoid `shouldSkipConfirmation=true` when moving to a distance request.

**Comment by mollfpr** [comment] 2024-10-21 17:27
@twilight2294 I'm not too onboard with the solution. We are probably looking for a way to maintain the value `skipConfirmation` instead of adding a check where it's not necessarily a problem.

**Comment by mollfpr** [comment] 2024-10-23 15:16
>I think we can do that when we change the tab from manual to distance but then if we come back to manual tab, the shouldSkipConfirmation will be false. I don't think we should update like that or try to find a more complex solution when we can just check the iouType [here](https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L112) and return if it is of type split.

@Krishna2323 Do you have a prove that split expense can't skip confirmation?

**Comment by mollfpr** [comment] 2024-10-23 15:25
@twilight2294 I think your alternative solution will make the scan expense not skip the confirmation page. Open the QAB split expense then go to the scan tab and upload a receipt, it's expecting to skip the confirmation.

**Comment by mollfpr** [comment] 2024-10-23 15:30
It's working fine on the latest main and did skip the scan request either from QAB split expense or QAB split scan.

**Comment by mollfpr** [comment] 2024-10-25 08:41
I think I have concluded that we should follow the flow on the QAB distance with split expense distance, which shows the confirmation page whenever the user tries to split expense distance.

---

@twilight2294 For your alternative solution, I understand that you tried to set the `skipConfirmation` for all the QAB actions which is wrong. The QAB split scan still working fine with skip confirmation, so we should keep that.

**Comment by mollfpr** [comment] 2024-10-25 08:47
@twilight2294 Your root cause seems to imply that we called the wrong API for split expense distance because the condition `shouldSkipConfirmation` and `iouType` is split, and your solution is to prevent skip confirmation for group chat. Does this mean that the skip confirmation still works for split expense other that the group chat?

**Comment by mollfpr** [comment] 2024-10-25 08:59
>okay, i will fix that during PR phase

What fix do you plan?

>We will not skip conformation for the QAB split expense of any type according to slack convo

My understanding is different, as Tom said that we making it consistent when don't switch the split type. So it's mean that the skip confirmation page still working for QAB split scan.

**Comment by mollfpr** [comment] 2024-10-25 12:49
We've got newer [feedback](https://expensify.slack.com/archives/C01GTK53T8Q/p1729859875392059?thread_ts=1729791209.675379&cid=C01GTK53T8Q) and for the QAB split scan we leave it as it is.

**Comment by mollfpr** [comment] 2024-10-25 13:08
I think the implementation for skip confirmation on split distance doesn't work well now, and because we agree to not skip the confirmation page for split distance we can safely remove the code here.

https://github.com/Expensify/App/blob/0288c7ab0cb779387b642c339bcf4513678e9073/src/pages/iou/request/step/IOURequestStepDistance.tsx#L286-L303

@twilight2294 Your main solution seems will be working, but using the group chat to determine the value of `shouldSkipConfirmation` is less precise, and prefer the safest way which using the `iouType`, and your alternative solution won't work since we still want to skip confirmation for QAB split scan.

The proposal from @Krishna2323 has the correct step to solve this here, but instead add a check for `iouType` beside the `shouldSkipConfirmation`, we just need to add the `iouType` split check in `shouldSkipConfirmation` which makes it cleaner.

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment] 2024-10-28 16:52
Friendly bump @neil-marcellini for final thoughts https://github.com/Expensify/App/issues/50694#issuecomment-2437734504

**Comment by neil-marcellini** [comment] 2024-10-30 17:19
I agree with what @mollfpr [said](https://github.com/Expensify/App/issues/50694#issuecomment-2437734504) and I'd like to go with @Krishna2323's [proposal](https://github.com/Expensify/App/issues/50694#issuecomment-2409062642). Thanks for your effort as well @twilight2294.

**Comment by mollfpr** [comment] 2024-11-19 07:28
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Comment by abekkala** [comment] 2024-11-19 15:35
Stevies been ooo and returns next week. 

I'll make payment summary

**Comment by abekkala** [comment] 2024-11-19 15:36
### PAYMENT SUMMARY FOR NOV 14

- Fix: @Krishna2323 [$250] [offer](https://www.upwork.com/nx/wm/offer/104666501)
- PR Review:  [$250] @mollfpr payment via NewDot Manual Requests

**Comment by abekkala** [comment] 2024-11-19 15:37
@Krishna2323 payment sent and contract ended - thank you! 🎉

**Closed by abekkala** 2024-11-19 15:37 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-11-26 14:02
$250 approved for @mollfpr
