### ISSUE TITLE
Log in  - Authenticator code is not typeable unless the filed is selected by cursor

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20858] opened 2023-06-15 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Make sure 2FA is setup
2. now try to login -> enter mail/phone number
3. Type magic code -> continue ( Notice that the magic code is typeable directly without selecting the form field)
4. Now try to enter authentication code from 2FA

## Expected Result:
After magic code entry, while typing authenticator code, form should be active so that user can type the code directly.

## Actual Result:
Authenticator code is not typeable unless the filed is selected by cursor.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.7

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/64dfd738-037b-4c9e-8dc5-d9b4d9b45928

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686233024184809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2023-06-17 08:43
Looks like dupe of this https://github.com/Expensify/App/issues/19711

**Comment by alexpensify** [comment] 2023-06-17 16:31
Thanks for flagging @bernhardoj-- I'm going to close this one in favor of the GH above.

**Closed by alexpensify** 2023-06-17 16:31 UTC
Labels: Daily, Bug
