### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] Web - Select a currency page scroll when open

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24336] opened 2023-08-09 18:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB button
2. Click Request money
3. Click into current currency, observer Select a currency page scroll when open

## Expected Result:
Select a currency page not scroll when open

## Actual Result:
Select a currency page scroll when open

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/41d5b39e-929e-4376-a880-ffdc8aace6dd

https://github.com/Expensify/App/assets/43995119/3a6c88cf-a8ed-4637-8839-69ac6cb9d86f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690991772958669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175d78ac3d566ccad</li>
        <li>Upwork Job ID: 1691137102130921472</li>
        <li>Last Price Increase: 2023-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>joh42 | Contributor | 26295320</li>
<li>namhihi237 | Reporter | 26295321</li>
</ul></li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-08-10 19:30
Steps to reproduce:
1. Select any one of these from the last currencies, might differ based on screen height.
<img width="340" alt="Screenshot 2023-08-11 at 12 57 27 AM" src="https://github.com/Expensify/App/assets/78416198/aacc61ed-d81c-4c1a-997f-8d8a892160f1">

2. Now again go to change currency picker. Verify that list scrolls up.

https://github.com/Expensify/App/assets/78416198/9941548f-0052-4429-b533-c383085c26bd

**Comment by sonialiap** [comment] 2023-08-14 17:17
Reproducible. Small jiggle for some currencies and large movement when selecting VND from VUV

https://github.com/Expensify/App/assets/17131195/6d08be37-bd73-4a80-b25b-3766134f6dc3

**Comment by sonialiap** [comment] 2023-08-14 20:20
Not overdue

**Comment by robertKozik** [comment] 2023-08-21 21:29
Hi all! @joh42 Your solution and root cause looks great. But before I would recommend your proposal, I wanted to recheck the issue itself - and I'm having trouble with reproducing. Could you check on your end if you are able to reproduce this issue? 

https://github.com/Expensify/App/assets/61146594/fcb02e47-37ce-4e89-8a8a-6e5d5e619897

**Comment by joh42** [comment] 2023-08-21 22:22
Hi @robertKozik, thanks for reviewing my proposal!

There is a scroll for me, but it is not as smooth as the one shown by others above. It might be worth checking with them to see if they can still reproduce it.

https://github.com/Expensify/App/assets/138504087/32fe0eb8-ba46-430c-8238-5a77ae39f49d


Either way, I do think that the missing transition should be fixed though.

**Comment by robertKozik** [comment] 2023-08-22 08:33
Yeah, I agree. I quick tested your solution (with the fixed delay for convenience) and It looks like it's working fine, despite the list behaviour - during testing on latest main/staging/prod I've encountered different jiggles (strange tho). Fixing transition is an additional asset of fixing this task.
I think we can go with your proposal @joh42 .

Selected proposal: [Proposal](https://github.com/Expensify/App/issues/24336#issuecomment-1677840095)
Contributor: @joh42 

🎀 👀 🎀 C+ reviewed

**Comment by joh42** [comment] 2023-08-24 11:21
Thanks! You can expect a PR shortly.

**Comment by joh42** [comment] 2023-08-27 21:11
Okay so I have some good news and some bad news.

The good news is that the small jiggle disappears when we add delayed focusing. However, while the transition obscures the bigger scrolling, making it nearly impossible to detect, it does not remove it.

After digging into it, my conclusion is that the remaining scrolling is actually caused by how many options are being rendered at once.

### Analysis
Using breakpoints, we can analyze each step of the rendering process. Here is how it looks when VND is selected:
![image](https://github.com/Expensify/App/assets/138504087/4a3845ad-94be-4287-b034-7e37be49f308)

Next up, a few more options are rendered. However, we can see that when the last option, ZMW, has been rendered, there is still an empty space at the bottom:
![image](https://github.com/Expensify/App/assets/138504087/319f683e-268d-434f-b033-204bf81ea985)

Finally, the space at the bottom is removed, which causes VND to move down. We can see that the space below the search input has increased:
![image](https://github.com/Expensify/App/assets/138504087/4d80df2a-6bb6-4adc-a451-171697f6b551)

The behavior for VUV is similar. Initially, it starts 2 options from the top, but when all options have been rendered, it has moved down to 3 options from the top to make sure there is no empty space at the bottom:
![image](https://github.com/Expensify/App/assets/138504087/a29f235e-f7bd-4741-82c1-3b4dda2faf5a)
![image](https://github.com/Expensify/App/assets/138504087/e22d11aa-4374-48da-b399-f22d7a18e99b)

### Similar behaviour elsewhere
We can observe similar behavior for the timezone selector. Note how the selected option is ~1.5 options from the top at the start:
![image](https://github.com/Expensify/App/assets/138504087/942ee937-b8ae-4cf7-9fca-8d3f45f94d2b)

But it is then moved down to ~2.5 options from the top:
![image](https://github.com/Expensify/App/assets/138504087/65eaa908-0703-4d6e-ba67-e3810e40b69f)

### Conclusion & next steps

My conclusion is that not enough options are being rendered initially to know exactly where the options at the top of the screen should be placed. As such, when all options have been rendered, there is empty space at the bottom. When this empty space is removed, it looks like the options are scrolled.

Increasing the [number of options being rendered](https://github.com/Expensify/App/blob/main/src/components/OptionsList/BaseOptionsList.js#L236-L237) from 12/5 to 15/15 fixes it for my screen:

https://github.com/Expensify/App/assets/138504087/4851fa6e-9cdd-4993-ab6a-93dbf130b8ce

https://github.com/Expensify/App/assets/138504087/9f794625-10da-4bc3-a019-2b7892c40fc5

Since the currency and timezone selectors use different components ([OptionsSelector](https://github.com/Expensify/App/blob/main/src/components/OptionsSelector/BaseOptionsSelector.js) and [SelectionList](https://github.com/Expensify/App/blob/main/src/components/SelectionList/BaseSelectionList.js) respectively), I actually think this issue is caused by the underlying React Native component being used by both, [SectionList](https://reactnative.dev/docs/sectionlist).

Just to be clear, the scroll is barely visible at all when opening the currency selector with a proper transition. It is mostly visible when reloading with the currency selector open. For context, this is how the scroll appears when the transition has been fixed:

https://github.com/Expensify/App/assets/138504087/11aa9cf4-5a43-4b4a-bcdd-6a9c7037e709

If you slow down the playback speed to 0.25, you can see the scroll in question.

There are a few ways to approach the remaining scrolling issue:
* Increase the number of options being rendered regardless of screen size
* Try to calculate how many options should be rendered based on screen size
* Do nothing about the larger scrolling - since the transition fixes the smaller jiggles and mostly hides the larger scrolling (IE only fix the transition)
* Something else?



Tagging you initially @robertKozik to get your opinion on the correct way to move forward.

**Comment by joh42** [comment] 2023-08-28 13:25
Also tagging @cead22 / @mountiny for input on how to move forward, since you're both assigned to this issue

**Comment by mountiny** [comment] 2023-08-28 13:49
> Do nothing about the larger scrolling - since the transition fixes the smaller jiggles and mostly hides the larger scrolling (IE only fix the transition)

Personally I think the fix you have provided for now makes the jiggle unnoticeable so I think its a fix which should be sufficient for now. I think adding more computation to the process might not be that beneficial and it will just be brittle in the end. 

As we add more similar selection components to the App, I think it would be good to look at some underlying solution which will fix it everywhere, but what you got that is good enough for this issue imho. @robertKozik what do you think/

**Comment by joh42** [comment] 2023-08-28 14:30
Thanks Vit!

**Comment by robertKozik** [comment] 2023-08-28 16:06
@joh42 Thank you for providing such a detailed response to the problem; it greatly assists in our decision-making process.

I concur with @mountiny's viewpoint that additional calculations might be an overkill for such a minor issue.

However, I believe we can explore the option of increasing the maximum number of options rendered. I traced down the [latest issue that led to the increase in that](https://github.com/Expensify/App/pull/13425) number. If enlarging the numbers a little won't have a negative impact on performance, it could be a viable solution. As per React Native documentation, initialNumToRender should be sufficient to fill the screen, but in our current scenario, we're encountering a situation where we lack an adequate number for larger screens.

@joh42, in your summary, you mentioned that updating the numbers to 15/15 resolves the remaining jiggles. Do we also need to update the batch number, or would adjusting the initialNumToRender suffice? As increasing batch number from 5 -> 15 is quite a large change.

**Comment by joh42** [comment] 2023-08-28 19:27
Thanks for your reply @robertKozik!

Solely increasing the `initialNumToRender` doesn't seem to change anything on my screen. Here I've set it to 20 while leaving `maxToRenderPerBatch` at 5, and this is what it looks like initially:
![image](https://github.com/Expensify/App/assets/138504087/60f61a2c-79d8-4d19-b199-7978c7f5f41e)

At the same time I agree that increasing the batch number would likely be detrimental to performance.

It is a bit annoying that 5 of the options being rendered are not even visible:
![image](https://github.com/Expensify/App/assets/138504087/df7b92db-a468-4e26-adc8-5cce71418e00)

If that was not the case, all options would have been rendered. As far as I can tell we cannot do anything about that though.

**Comment by robertKozik** [comment] 2023-08-30 11:23
Got it @joh42 thanks for checking that out. I checked one more all the comments and I think that the fix which you already have is sufficient, as the rest of the jiggle is almost unnoticeable. Changing the `maxToRenderPerBatch` can be not worth it in terms of performance.

**Comment by mountiny** [comment] 2023-09-21 10:13
@sonialiap ready for payment. 

@robertKozik can you please complete the checklist?

**Comment by mountiny** [comment] 2023-09-21 10:14
Can you calm down melvin

**Comment by robertKozik** [comment] 2023-09-21 10:44
On it 👀

**Comment by sonialiap** [comment] 2023-09-25 04:57
@robertKozik does not require payment (Contractor)
@joh42 fix + time bonus = $1500 - paid ✔️ 
@namhihi237 report $250 - paid ✔️

**Comment by sonialiap** [comment] 2023-09-25 04:58
@robertKozik just need the [checklist](https://github.com/Expensify/App/issues/24336#issuecomment-1717184540) checked to close this out 🎉

**Comment by robertKozik** [comment] 2023-09-25 10:22
> [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **I think we cannot point out exact PR which introduces it, it was tricky hard to observe and minor problem which could be treated lightly beforehand. It could resurfaced after the navigator refactor**
[@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
 [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
 [@robertKozik] Determine if we should create a regression test for this bug. **I don't think it's that major problem to introduce the regression test for that. Moreover it's only minor visual one**
 [@robertKozik] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **N/A**

**Closed** 2023-09-28 01:13 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
