### ISSUE TITLE
[PAID] [$500] Back from request money details page does not open request money page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29056] opened 2023-10-07 19:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report with request money IOU message
3. Click on request money IOU message
4. Click in header, it will open details page
5. Copy the URL and logout
6. Paste URL and login
7. On details page, click back and observe that now app does not display report for which we had opened details page

## Expected Result:
 App should display report for which details page is opened in background if we login with details page URL

## Actual Result:
 App does not display report for which details page is opened in background if we login with details page URL

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native -not testable 
- [x] Android / Chrome
- [ ] iOS / native -not testable 
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop -not testable 

**Version Number:** 1.3.78.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e2b86864-686f-405c-8efd-013de10faf1a

https://github.com/Expensify/App/assets/93399543/383943e7-00e0-449b-813b-95543b3c6ea5

https://github.com/Expensify/App/assets/93399543/15ee75b0-9e12-42de-9687-b7d73c6ad4b4

https://github.com/Expensify/App/assets/93399543/8589d2b2-15ad-41b3-9047-16b2a12a5b13

https://github.com/Expensify/App/assets/93399543/df0bdf81-fd8e-400b-9ee2-05e09d8af85e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Dhanashree-Sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696668016454099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0119568c805cf99a1b</li>
        <li>Upwork Job ID: 1710737969784868864</li>
        <li>Last Price Increase: 2023-10-07</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27131905</li>
<li>Dhanashree-Sawant | Reporter | 27131908</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @burczu</details>

**Comment by abzokhattab** [comment] 2023-10-07 19:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Request money page is not opened on Back from request money details page

### What is the root cause of that problem?

In the `HeaderWithBackButton` of the `ReportDetailsPage` we dont specify a route for the back action leaving the default bahavior of the `HeaderWithBackButton` .. which goes back to the home page `onBackButtonPress = () => Navigation.goBack(ROUTES.HOME)`

https://github.com/Expensify/App/blob/168e7f7c965acfc1d088e49a5a038dc5a58bae37/src/pages/ReportDetailsPage.js#L162

### What changes do you think we should make in order to solve the problem?

We should add `onBackButtonPress` prop to the `HeaderWithBackButton` component with the report route as the default back page:

```javascript
<HeaderWithBackButton
  title={props.translate("common.details")}
  onBackButtonPress={() =>
    Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(props.report.reportID))
  }
/>
```

### POC:

https://github.com/Expensify/App/assets/59809993/e17bf54e-48b8-4220-8e75-61d531574959

**Comment by strepanier03** [comment] 2023-10-09 17:36
Was able to repro easily. Letting this move forward naturally.

**Comment by francoisl** [comment] 2023-10-10 23:17
Agreed. Let's proceed with your proposal @tienifr.

**Comment by francoisl** [comment] 2023-10-11 03:06
The Upwork automation didn't work because it looks like the `Upwork Automation - Do Not Edit` section had been accidentally removed. Re-added it, trying again now.

**Comment by strepanier03** [comment] 2023-10-27 21:05
@burczu - I'll close this out when we have the checklist done.

Everyone else has been paid, thank you @dhanashree-sawant and @tienifr!

**Comment by strepanier03** [comment] 2023-10-30 22:41
Just waiting on checklist stuff from @burczu then this one will be closed. All good melvin.

**Comment by strepanier03** [comment] 2023-11-02 17:22
@burczu - bump on the checklist so we can get this closed out.

**Comment by strepanier03** [comment] 2023-11-06 18:17
@burczu - Please take care of the checklist so we can close this out.

**Comment by francoisl** [comment] 2023-11-07 21:48
Doesn't seem like this came from a regression, also probably no need for a new regression test, going to close.

**Closed by francoisl** 2023-11-07 21:48 UTC
Labels: Engineering, Daily, Internal, Overdue, Awaiting Payment, Bug
