### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] `preDeploy.yml` should not skip on default branch if another run is queued

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#41936] opened 2024-05-09 17:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @blimpich
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1715015588472179?thread_ts=1713554811.796439&cid=C01GTK53T8Q
**cc:** @rayane-djouah 

## Action Performed:
1. merge a PR into main
2. immediately merge another PR into main 

## Expected Result:
Both runs should run to completion

## Actual Result:
The first run is skipped/cancelled.

## Screenshots/Videos

[Example of skipped job](https://github.com/Expensify/App/actions/runs/8997443619/job/24716510345)

Go to https://github.com/Expensify/App/actions/workflows/preDeploy.yml and you will find many examples of skipped jobs by just looking through the recent merges.

## Further context:
This was caused by [this PR](https://github.com/Expensify/App/pull/37532). We don't want to revert this PR because it saves resources on builds for pull requests, we just don't want it to apply to when we're merging into main.

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f9368ae63177d49</li>
        <li>Upwork Job ID: 1788618186197295104</li>
        <li>Last Price Increase: 2024-05-09</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 0</li>
<li>badeggg | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by amgenene** [comment] 2024-05-09 19:44
Proposal:
Please re-state the problem that we are trying to solve in this issue.
The problem we are trying to solve is that when multiple pull requests are merged into the main branch in quick succession, the workflow runs triggered by earlier merges are being canceled due to the cancel-in-progress: true flag in the workflow concurrency configuration.
What is the root cause of that problem?
The root cause of the problem is the cancel-in-progress: true setting, which is designed to cancel any currently running workflows or jobs with the same concurrency group when a new workflow run is triggered. This behavior is desirable for pull requests, where we want to save resources and avoid running redundant workflows or jobs when a new commit is pushed. However, for merges into the main branch, we want all workflow runs to complete without being canceled, even if another merge happens shortly after.
What changes do you think we should make in order to solve the problem?
To solve the problem, we can introduce conditional logic in the workflow files to apply the cancel-in-progress: true setting only for pull requests and not for merges to the main branch.
For the preDeploy.yml workflow file (or any other workflow file that handles merges to the main branch), we can set the cancel-in-progress setting to false
What alternative solutions did you explore? (Optional)
An alternative solution could be to introduce a delay or a manual trigger for workflow runs triggered by merges to the main branch. This would prevent the second workflow run from canceling the first one, but it might introduce additional complexity or manual intervention in the deployment process.

**Comment by badeggg** [comment] 2024-05-11 12:53
@rayane-djouah @blimpich , I think @ShridharGoel's [proposal](https://github.com/Expensify/App/issues/41936#issuecomment-2104554741) is not correct, and I am writing a proposal. 

When `cancel-in-progress: true` do **is not** keep all concurrent workflows, what `cancel-in-progress` influence is only whether cancel running workflows, queued is always canceled.

Based on github doc [here](https://github.com/Expensify/App/issues/41936#issuecomment-2104554741) 
> When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any pending job or workflow in the concurrency group will be canceled. This means that there can be at most one running and one pending job in a concurrency group at any time.

>To also cancel any currently running job or workflow in the same concurrency group, specify cancel-in-progress: true. To conditionally cancel currently running jobs or workflows in the same concurrency group, you can specify cancel-in-progress as an expression with any of the allowed expression contexts.

**Comment by badeggg** [comment] 2024-05-11 13:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Do not skip workflow on main branch

### What is the root cause of that problem?
We have several concurrency config like [this](https://github.com/Expensify/App/blob/ada489f1cc6061d674066e59b26c0c000a0a9a52/.github/workflows/lint.yml#L10-L12), which will skip concurrent workflows. 

### What changes do you think we should make in order to solve the problem?
We should change [this](https://github.com/Expensify/App/blob/ada489f1cc6061d674066e59b26c0c000a0a9a52/.github/workflows/lint.yml#L10-L12) to:
```
concurrency:
  group: "${{ github.ref == 'refs/heads/main' ? github.ref + '-' + github.run_id + '-' + github.run_number : github.ref }}-lint"
  cancel-in-progress: true
```

Similar change need be applied to [here](https://github.com/Expensify/App/blob/ada489f1cc6061d674066e59b26c0c000a0a9a52/.github/workflows/test.yml#L10-L12)

### What alternative solutions did you explore? (Optional)
N/A

**Comment by badeggg** [comment] 2024-05-11 13:33
Little explanation about my proposal.
- check if we are running workflow on main branch by `github.ref == 'refs/heads/main'`
- if it is not, we set up a group based on `github.ref`(which is the fully-formed ref of the branch or tag)
- **if it is the main branch**, we form up a unique group for every workflow run by combine `github.ref` `github.run_id` and `github.run_number`. Which will guarantee every main branch workflow run case have a unique group name, so cause no skip. Check [github doc here](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)
    + > `github.ref` is: The fully-formed ref of the branch or tag that triggered the workflow run. For workflows triggered by push, this is the branch or tag ref that was pushed. For workflows triggered by pull_request, this is the pull request merge branch. For workflows triggered by release, this is the release tag created. For other triggers, this is the branch or tag ref that triggered the workflow run. This is only set if a branch or tag is available for the event type. The ref given is fully-formed, meaning that for branches the format is refs/heads/<branch_name>, for pull requests it is refs/pull/<pr_number>/merge, and for tags it is refs/tags/<tag_name>. For example, refs/heads/feature-branch-1.
    + > `github.run_id` is: A unique number for each workflow run within a repository. This number does not change if you re-run the workflow run.
    + > `github.run_number` is:  A unique number for each run of a particular workflow in a repository. This number begins at 1 for the workflow's first run, and increments with each new run. This number does not change if you re-run the workflow run.

**Comment by badeggg** [comment] 2024-05-11 15:36
I have updated my [proposal](https://github.com/Expensify/App/issues/41936#issuecomment-2105742203) and [explanation](https://github.com/Expensify/App/issues/41936#issuecomment-2105746812):
- github workflow yaml does not support `condition ? 'A' : 'B'` syntax, use `condition && 'A' || 'B'` instead, [doc here](https://docs.github.com/en/actions/learn-github-actions/expressions#example)
- github workflow yaml does not support `+` operator, use [format function](https://docs.github.com/en/actions/learn-github-actions/expressions#format)
- use `github.ref` and `github.sha` to form up unique group name, I think this will make more sense
- delete surrounding `"` on group name to align with another [concurrency config](https://github.com/Expensify/App/blob/ada489f1cc6061d674066e59b26c0c000a0a9a52/.github/workflows/platformDeploy.yml#L15) (though it's negligible)

**Comment by badeggg** [comment] 2024-05-14 04:21
Offer accepted, I will make a pull request in ~24 hrs.

**Comment by badeggg** [comment] 2024-05-14 09:14
I have made pr

**Comment by blimpich** [comment] 2024-05-27 17:27
@rayane-djouah @badeggg https://github.com/Expensify/App/pull/42134 just got merged. Since this can only really be tested in production, can you please test to make sure that this works by confirming that (A) PR builds aren't effected by this change and (B) builds that would have been skipped without this change are not being skipped?

**Comment by badeggg** [comment] 2024-05-28 08:24
Looks fine.

### Evidence for (A) PR builds aren't effected by this change:
#### lint:
[run 1](https://github.com/Expensify/App/actions/runs/9265125540)
[run 2](https://github.com/Expensify/App/actions/runs/9265058608)
[to view more](https://github.com/Expensify/App/actions/workflows/lint.yml)
![image](https://github.com/Expensify/App/assets/10908996/61435787-4361-4fea-96c9-ece27a8236c7)
#### typecheck:
[run 1](https://github.com/Expensify/App/actions/runs/9265627883)
![image](https://github.com/Expensify/App/assets/10908996/704a8dba-d77b-4faf-988d-22916157b57a)
[to view more](https://github.com/Expensify/App/actions/workflows/typecheck.yml)
#### test:
[run 1](https://github.com/Expensify/App/actions/runs/9265627869)
![image](https://github.com/Expensify/App/assets/10908996/471a90c6-2cd8-4448-9074-34987986a702)
[to view more](https://github.com/Expensify/App/actions/workflows/test.yml)
#### e2ePerformanceTests
The trigger condition for this workflow is a relatively rare met, manually trigger or call from another workflow. Only `./workflows/preDeploy.yml` will call it and the trigger condition for `./workflows/preDeploy.yml` is 'push to main branch'. This makes us hard to catch a evidence for `e2ePerformanceTests`.
[maybe come across one case](https://github.com/Expensify/App/actions/workflows/e2ePerformanceTests.yml)



### Evidence for (B) builds that would have been skipped without this change are not being skipped:
Those three commits were pushed almost the same time(less than 1 second), and there is no typecheck/lint/test/e2ePerformanceTests job skip.
[commit e430c2d](https://github.com/Expensify/App/pull/42648) -->  [workflow](https://github.com/Expensify/App/actions/runs/9261051748)
[commit cabf71d](https://github.com/Expensify/App/pull/42454)   --> [workflow](https://github.com/Expensify/App/actions/runs/9261053980)
[commit 3599850](https://github.com/Expensify/App/pull/42426) --> [workflow](https://github.com/Expensify/App/actions/runs/9261056073)
![image](https://github.com/Expensify/App/assets/10908996/e2374a6a-2896-4a3f-b702-80eb265e5481)
![image](https://github.com/Expensify/App/assets/10908996/1f6a8a71-011d-4959-9131-6d38192bed87)
![image](https://github.com/Expensify/App/assets/10908996/9856cb14-4ed0-484c-9254-72417e4d6bf4)

**Comment by blimpich** [comment] 2024-05-28 16:49
Fantastic! Thank you @badeggg for the QA. Very happy with this 🥳

**Comment by bfitzexpensify** [comment] 2024-05-30 22:28
Adding a BZ buddy for payment/regression test update - I will be OOO until June 11th

**Comment by garrettmknight** [comment] 2024-06-06 18:30
All paid out, closing!

**Closed by garrettmknight** 2024-06-06 18:30 UTC
Labels: External, Daily, Awaiting Payment, Bug
