### ISSUE TITLE
[HOLD for payment 2023-10-24] [$500] keyboard opens for a second when user switches to password protected PDF

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#28841] opened 2023-10-04 16:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. send a password protected PDF and one image or pdf
3. click on password protected PDF
4. click on enter password which will opens a keyboard
5. click on Next or previous arrow
6. again go to password protected PDF

## Expected Result:
keyboard should not blink
## Actual Result:
keyboard opens for a second
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.76-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/58045ae2-ce7d-48b1-a970-378d1fe78307

https://github.com/Expensify/App/assets/38435837/7d8c5141-26b0-4c13-a434-bd74c1ed5181

https://github.com/Expensify/App/assets/38435837/468d678e-6288-4275-888c-9c7a89515ede

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696404454786079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0adb84bbc4bbe4e</li>
        <li>Upwork Job ID: 1709618967047499776</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27140726</li>
<li>gadhiyamanan | Reporter | 27140730</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @burczu</details>

**Comment by micahelchan623** [comment] 2023-10-04 17:39
Proposal

Please re-state the issue
keyboard opens for a second

What is the root cause of the problem?
The keyboard did not unmount when navigate to the next screen

What changes do you think should be made to fix this problem?
add `Keyboard.dismiss();` before submit password on PDFPasswordForm.js

``` typescript
    const submitPassword = () => {
        if (!validate()) {
            return;
        }
        Keyboard.dismiss();
        onSubmit(password);
    };
```

What other alternative options did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2023-10-04 19:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
keyboard opens for a second when user switches to password protected PDF
### What is the root cause of that problem?
The keyboard is opening while animation is running and this animation is causing the textfield to lose focus and keyboard to close.

The keyboard is opening when `isFocused` prop is `true`
https://github.com/Expensify/App/blob/99a967c3b22f0b4463820514afcb07db9190117d/src/components/PDFView/PDFPasswordForm.js#L63-L71
And this prop is passed here 
https://github.com/Expensify/App/blob/439a6ae2fa4e328ab03778b58c9a01061c3db91e/src/components/Attachments/AttachmentCarousel/index.native.js#L110
This condition becomes immediately true when we switch to next carousel item without waiting for animation.

### What changes do you think we should make in order to solve the problem?
We should wait for the animation to complete and then focus the keyboard. We can achieve it by using `isActive` argument here which becomes true only after animation is completed
https://github.com/Expensify/App/blob/f0e98e3145f8208b483203b748175e5c909ffeef/src/components/Attachments/AttachmentCarousel/Pager/index.js#L160

We can modify value of `isFocus` prop to also take `isActive` property into consideration, and it looks like this:
```javascript
        ({item, isActive}) => (
            <CarouselItem
                item={item}
                isFocused={isActive && activeSource === item.source}
                onPress={() => setShouldShowArrows(!shouldShowArrows)}
            />
        ),
```
**Result:**
https://github.com/Expensify/App/assets/59907218/ccc80063-a729-4351-aaaa-549c07110265


### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-10-05 08:22
It seems this relate to https://github.com/Expensify/App/issues/19156

**Comment by burczu** [comment] 2023-10-10 11:01
Just reviewed all the proposals.

[The one](https://github.com/Expensify/App/issues/28841#issuecomment-1747359035) from @micahelchan623 just doesn't work, and I don't think it is to correct direction at all.

[The solution](https://github.com/Expensify/App/issues/28841#issuecomment-1747551074) proposed by @alitoshmatov is also incorrect: I don't think we want the text input to be focused right after we switches back to the password protected PDF from other image.

Only [the proposal](https://github.com/Expensify/App/issues/28841#issuecomment-1748632083) from @tienifr works as expected and I think it is a correct solution (even if it uses `setTimeout` but it is an approach advised by @roryabraham [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1694660990479979), as @tienifr pointed out), so I think we could proceed with it.

🎀 👀 🎀 C+ reviewed

**Comment by hayata-suenaga** [comment] 2023-10-26 15:51
waiting for the checklist to be completed and payments

**Comment by johncschuster** [comment] 2023-10-26 19:30
I'll work on payments. @burczu, can you complete the checklist above?

**Comment by johncschuster** [comment] 2023-10-26 19:34
Payments to @tienifr and @gadhiyamanan have been issued!

**Comment by hayata-suenaga** [comment] 2023-10-30 16:32
payments have been issued

**Comment by burczu** [comment] 2023-10-31 12:00
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [ ]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: **Didn't identify such PR.**
* [ ]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **n/a**
* [ ]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **n/a**
* [ ]  [@burczu] Determine if we should create a regression test for this bug. **I don't think so - the bug wasn't impactful and didn't break any important flow in the App.**
* [ ]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@johncschuster] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by johncschuster** [comment] 2023-10-31 13:08
@burczu do you feel this issue requires us to add to our regression steps? If so, can you propose those steps?

**Comment by burczu** [comment] 2023-10-31 13:21
@johncschuster As I wrote in my previous comment: 

>  I don't think so - the bug wasn't impactful and didn't break any important flow in the App.

**Comment by johncschuster** [comment] 2023-11-02 20:41
Ah I missed that. Thanks!

**Comment by johncschuster** [comment] 2023-11-02 20:41
Closing!

**Closed by johncschuster** 2023-11-02 20:41 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
