### ISSUE TITLE
Chat - There is no member search for a group chat with more than 8 members

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41909] opened 2024-05-09 13:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4548098&group_by=cases:section_id&group_id=296760&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with an expensifail account
2. Create a group chat with more than 8 members
3. Navigate to the members tab of the group chat

## Expected Result:
There should be a member search

## Actual Result:
There is no member search for a group chat with more than 8 members

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/32ea58bf-1cbc-44c1-a01f-d06f89818283

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-09 13:16
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neonbhai** [comment] 2024-05-09 13:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - There is no member search for a group chat with more than 8 members

### What is the root cause of that problem?
We don't have the members search bar here as we don't pass the textInputLabel to the List Component.

### What changes do you think we should make in order to solve the problem?
We will pass textInputLabel if the members count is above threshold:

```jsx
const shouldShowTextInput = !isMembersCountBelowThreshold;
```

```jsx
textInputLabel={shouldShowTextInput ? translate('optionsSelector.findMember') : undefined}
```

### Alternatively 
We can have the check in other member pages as needed

**Comment by nkdengineer** [comment] 2024-05-10 06:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no member search for a group chat with more than 8 members

### What is the root cause of that problem?
This is a new feature

### What changes do you think we should make in order to solve the problem?
1. Create a `searchTerm` state to control the value of search input

```
const [searchValue, setSearchValue] = useState<string>('');
```

2. Add `textInputLabel` prop into `SelectionList`, it will be empty if the members `<=8` otherwise it's a string that can be confirm by design team

```
textInputLabel={translate('optionsSelector.findMember')}
textInputValue={searchValue}
onChangeText={setSearchValue}
```
https://github.com/Expensify/App/blob/db469d6e93e8eeae8c1251d1ebd9a94a6dfdd502/src/pages/ReportParticipantsPage.tsx#L347

3. In `getUsers` function, add dependency `searchValue` and we will get the members that match with `searchValue`. To filter the members, we can use the same logic as we do in `RoomMemberPage` [here](https://github.com/Expensify/App/blob/db469d6e93e8eeae8c1251d1ebd9a94a6dfdd502/src/pages/RoomMembersPage.tsx#L197) 

```
// If search value is provided, filter out members that don't match the search value
if (searchValue.trim()) {
    let memberDetails = '';
    if (details.login) {
        memberDetails += ` ${details.login.toLowerCase()}`;
    }
    if (details.firstName) {
        memberDetails += ` ${details.firstName.toLowerCase()}`;
    }
    if (details.lastName) {
        memberDetails += ` ${details.lastName.toLowerCase()}`;
    }
    if (details.displayName) {
        memberDetails += ` ${PersonalDetailsUtils.getDisplayNameOrDefault(details).toLowerCase()}`;
    }
    if (details.phoneNumber) {
        memberDetails += ` ${details.phoneNumber.toLowerCase()}`;
    }

    if (!OptionsListUtils.isSearchStringMatch(searchValue.trim(), memberDetails)) {
        return;
    }
}
```
https://github.com/Expensify/App/blob/db469d6e93e8eeae8c1251d1ebd9a94a6dfdd502/src/pages/ReportParticipantsPage.tsx#L71

4. OPTIONAL: We can also add `headerMessage` into `SelectionList` if there's no member match with `searchValue` and hide the `headerContent` as well. We can discuss more about this on the PR phrase

```
const headerMessage = searchValue.trim() && !participants.length ? translate('roomMembersPage.memberNotFound') : '';
headerMessage={headerMessage}
```
### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/Expensify/App/assets/161821005/5ecac80d-3d66-42fa-b3f7-7e9a72a051fe

**Comment by nkdengineer** [comment] 2024-05-10 06:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no member search for a group chat with more than 8 members

### What is the root cause of that problem?
This is a new feature

### What changes do you think we should make in order to solve the problem?
1. Create a `searchTerm` state to control the value of search input

```
const [searchValue, setSearchValue] = useState<string>('');
```

2. Add `textInputLabel` prop into `SelectionList`, it will be empty if the members `<=8` otherwise it's a string that can be confirm by design team

```
textInputLabel={chatParticipants.length > 8 ? translate('optionsSelector.findMember') : ''}
textInputValue={searchValue}
onChangeText={setSearchValue}
```
https://github.com/Expensify/App/blob/db469d6e93e8eeae8c1251d1ebd9a94a6dfdd502/src/pages/ReportParticipantsPage.tsx#L347

3. In `getUsers` function, add dependency `searchValue` and we will get the members that match with `searchValue`. To filter the members, we can use the same logic as we do in `RoomMemberPage` [here](https://github.com/Expensify/App/blob/db469d6e93e8eeae8c1251d1ebd9a94a6dfdd502/src/pages/RoomMembersPage.tsx#L197) 

```
// If search value is provided, filter out members that don't match the search value
if (searchValue.trim()) {
    let memberDetails = '';
    if (details.login) {
        memberDetails += ` ${details.login.toLowerCase()}`;
    }
    if (details.firstName) {
        memberDetails += ` ${details.firstName.toLowerCase()}`;
    }
    if (details.lastName) {
        memberDetails += ` ${details.lastName.toLowerCase()}`;
    }
    if (details.displayName) {
        memberDetails += ` ${PersonalDetailsUtils.getDisplayNameOrDefault(details).toLowerCase()}`;
    }
    if (details.phoneNumber) {
        memberDetails += ` ${details.phoneNumber.toLowerCase()}`;
    }

    if (!OptionsListUtils.isSearchStringMatch(searchValue.trim(), memberDetails)) {
        return;
    }
}
```
https://github.com/Expensify/App/blob/db469d6e93e8eeae8c1251d1ebd9a94a6dfdd502/src/pages/ReportParticipantsPage.tsx#L71

4. OPTIONAL: We can also add `headerMessage` into `SelectionList` if there's no member match with `searchValue` and hide the `headerContent` as well. We can discuss more about this on the PR phrase

```
const headerMessage = searchValue.trim() && !participants.length ? translate('roomMembersPage.memberNotFound') : '';
headerMessage={headerMessage}
```
### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/Expensify/App/assets/161821005/5ecac80d-3d66-42fa-b3f7-7e9a72a051fe

**Comment by muttmuure** [comment] 2024-05-15 07:37
Handling today

**Comment by muttmuure** [comment] 2024-05-15 13:26
This would be a new feature, it is not a bug

**Comment by dubielzyk-expensify** [comment] 2024-05-16 23:44
Is this something we actually want @Expensify/design ? If so, I suspect we'd do something like this? 

![CleanShot 2024-05-17 at 09 44 30@2x](https://github.com/Expensify/App/assets/145416827/c2cc53dd-226b-48dd-8760-4a224747db6e)

**Comment by shawnborton** [comment] 2024-05-17 01:09
Hmm interesting. I know that when we do selection lists, if there are more than 8 items in the list, that's when we add the search box:
![CleanShot 2024-05-16 at 21 08 11@2x](https://github.com/Expensify/App/assets/2319350/757dc1ed-266e-46bf-a303-4cac95ab7d4a)

However, I'm not sure that we ever discussed how to handle this with our table views. I know we had punted adding any kind of search bar on top of the table view in the Workspace editor until we fleshed out the global search router idea some more. Is that right @JmillsExpensify @trjExpensify?

That being said, @dubielzyk-expensify I do really love what you have here, but I guess we should first figure out how this interacts with the router. Given that this "View Members" view would always show up in the RHP, and would essentially sit on top of the router, I feel like it would be fine to have an encapsulated search box here?

**Comment by dubielzyk-expensify** [comment] 2024-05-17 01:16
Yeah. I remember us exploring it briefly. We also have search in Rooms already:

![CleanShot 2024-05-17 at 11 14 59@2x](https://github.com/Expensify/App/assets/145416827/0e5e091d-305f-4949-85ba-afd58ae2c304)

Which brings up a side-note that the Members page on Groups and Rooms should probably be consistent.

**Comment by shawnborton** [comment] 2024-05-17 01:18
Totally agree. Yeah, I think with the new Groups implementation, @marcaaron implemented a different kind of table view than the old one we had for rooms. Any thoughts on that Marc? I agree though, we should make them consistent.

**Comment by marcaaron** [comment] 2024-05-17 02:09
I definitely agree with making the Room and Group Chat members view consistent. I also really like what @dubielzyk-expensify shared above.

@shawnborton you make a good point about the two step router. Would we need something like that on the "Members" pages? If not, then @dubielzyk-expensify's mockup looks perfect to me and we should align Group Chats and Rooms to both use that. 

Otherwise, I'd worry we might end up with one too many search icons in this view. I don't have any great ideas for what that two-step router would do on this page. So, I think I'd lean towards leaving it out entirely and go with the inline filter instead.

**Comment by shawnborton** [comment] 2024-05-17 12:06
Yeah, I like that idea too personally - I do think that even in a world with a router, this kind of RHP would fly open and sit on top of the router so it's totally cool if we just have a simple search input above the table that filters the current table you are looking at.

**Comment by dannymcclain** [comment] 2024-05-17 14:05
Totally agree with where you all are headed with this!

**Comment by muttmuure** [comment] 2024-06-18 20:44
Future issue

**Comment by dubielzyk-expensify** [comment] 2024-07-23 04:32
Any updates on this?

**Comment by dubielzyk-expensify** [comment] 2024-08-26 09:04
Any updates?

**Comment by muttmuure** [comment] 2024-08-26 12:42
Who is that question for @dubielzyk-expensify? I don't think anyone is working on this

**Comment by dubielzyk-expensify** [comment] 2024-08-27 00:37
I'm just asking cause Melvin keeps saying it's overdue. Shall we close this or is it still being planned at some stage?

**Comment by dubielzyk-expensify** [comment] 2024-10-03 01:20
Same as above

**Comment by dubielzyk-expensify** [comment] 2024-11-05 03:20
Same as above. Not a priority

**Comment by muttmuure** [comment] 2024-12-04 10:16
This issue has been open for a long time. I recommend we close it until someone asks for it.

**Closed by muttmuure** 2024-12-04 10:16 UTC
Labels: Monthly, NewFeature
