### ISSUE TITLE
[Regression - HOLD on #39078 [HOLD for payment 2024-04-03] HIGH: [Video] [$500] iOS Safari - Video file preview not displayed after selecting video from device gallery

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36832] opened 2024-02-20 04:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com & log in
2. Go to 1:1 DM >> tap on + icon in composer field >> select Add atttachment option
3. Select video from photo library

## Expected Result:
Video file preview should be displayed after selecting video from gallery

## Actual Result:
Video file preview not displayed after selecting video from device gallery. Blank space is seen with only the video controls

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/ee708cee-fe54-4bb7-99f2-7223b7c94656

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cbcb9b31f838ae06</li>
        <li>Upwork Job ID: 1759795434302009344</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2024-02-20 04:22
We think this bug might be related to #vip-vsb
cc @quinthar

**Comment by MonilBhavsar** [comment] 2024-02-20 09:04
Not a blocker as it is minor issue on iOS Safari.
The PR for video player was merged yesterday https://github.com/Expensify/App/pull/30829

**Comment by MonilBhavsar** [comment] 2024-02-20 09:06
Commented on main PR https://github.com/Expensify/App/pull/30829#issuecomment-1953763773

**Comment by stephanieelliott** [comment] 2024-02-22 02:05
Thanks @MonilBhavsar! Reposting case it was missed on the PR: @akinwale @kosmydel @kowczarz, tagging you as this is related to the video player -- are any of you interested in picking this one up?

**Comment by MonilBhavsar** [comment] 2024-02-26 09:31
No response yet. Awaiting proposals

**Comment by stephanieelliott** [comment] 2024-02-27 04:21
Posted to #VIP-VSB to confirm it fits under that VIP. That should help us to decide how to prioritize this one! https://expensify.slack.com/archives/C066HJM2CAZ/p1709007618487189

**Comment by MonilBhavsar** [comment] 2024-03-04 11:01
Awaiting proposals

**Comment by stephanieelliott** [comment] 2024-03-06 00:03
Posted in SWM channel to see if we can get an expert contrib on this: https://expensify.slack.com/archives/C04878MDF34/p1709683398829389

**Comment by Skalakid** [comment] 2024-03-06 09:30
Hi, I'm Michał from Software Mansion and expert agency, and I will investigate this issue

**Comment by MonilBhavsar** [comment] 2024-03-06 09:37
Thank you @Skalakid! Assigning this issue to you

**Comment by MonilBhavsar** [comment] 2024-03-11 08:50
Being worked on by @Skalakid.
Anything that we can help with?

**Comment by stephanieelliott** [comment] 2024-03-12 23:13
Hey @Skalakid is there an ETA for when we can expect a PR?

**Comment by Skalakid** [comment] 2024-03-13 12:51
Yes, PR will be ready by the end of this week

**Comment by Skalakid** [comment] 2024-03-15 11:11
@stephanieelliott @MonilBhavsar I created a PR with the fix: https://github.com/Expensify/App/pull/38302

**Comment by MonilBhavsar** [comment] 2024-03-15 11:37
@Skalakid thank you! Can you please explain the cause
From the PR 
> This PR fixes video file previews that were not displayed after selecting video from device gallery, especially on iOS Safari. It was fixed by restricting browser to set video preview after 1 milisecond

Was it that safari couldn't load the video meta data immediately somehow and we have to add a delay?

**Comment by Skalakid** [comment] 2024-03-18 15:42
@MonilBhavsar I think this is pretty common issue on iOS Safari. Video html tags have problem with generating video preview. Probably Safari takes the first frame of the video as a preview, but it is empty one since video not started. I found this solution on [Apple developer forum](https://forums.developer.apple.com/forums/thread/129377).

**Comment by MonilBhavsar** [comment] 2024-03-20 09:05
Thanks!

---

And PR is merged

**Comment by quinthar** [comment] 2024-03-26 05:42
Can we close this?

**Comment by stephanieelliott** [comment] 2024-03-26 22:57
Not yet! This PR is on staging -- once it hits prod and the 7 day regression period passes, it will be ready for payment and can be closed. 

PR we're following is here: https://github.com/Expensify/App/pull/38302

**Comment by stephanieelliott** [comment] 2024-04-04 23:08
Thanks @paultsimura! Putting this on another hold for https://github.com/Expensify/App/issues/39078 since it was opened during the regression period, we'll start the 7 day regression hold again once that PR is merged.

 @Skalakid can you take a look at https://github.com/Expensify/App/issues/39078?

**Comment by Skalakid** [comment] 2024-04-05 07:46
Hi @stephanieelliott @paultsimura, I will take a look right now 😄

**Comment by Skalakid** [comment] 2024-04-05 09:14
@paultsimura I commented under the issue. I think it's a good proposal and we can proceed with that. I also suggested one enhancement

**Comment by stephanieelliott** [comment] 2024-04-10 19:39
Still held on https://github.com/Expensify/App/issues/39078, discussion is going on there.

**Comment by stephanieelliott** [comment] 2024-04-15 22:03
Still held on https://github.com/Expensify/App/issues/39078

**Comment by stephanieelliott** [comment] 2024-04-23 03:22
Still held on https://github.com/Expensify/App/issues/39078

**Comment by MonilBhavsar** [comment] 2024-05-02 06:42
I see other issue is being fixed by another contributor. Can we consider this as a regression and issue payment?

**Comment by stephanieelliott** [comment] 2024-05-02 16:32
Thanks @MonilBhavsar, I think that's a good plan -- let's treat this as a regression and pay this one out. 

Summarizing payment on this issue: 

 - Contributor: @Skalakid, no payment due (SWM)
 - Contributor+: @c3024 $250 ($500 * 50% regression penalty) via Upwork: offer extended, please accept: 
 
 Upwork job is here: https://www.upwork.com/jobs/~015b429315b92a65f2

**Comment by c3024** [comment] 2024-05-02 16:35
@stephanieelliott  accepted, thanks.

**Comment by stephanieelliott** [comment] 2024-05-02 16:41
Thanks @c3024, all paid!

**Closed by stephanieelliott** 2024-05-02 16:41 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
