### ISSUE TITLE
[Hold E/E #290783] Web - Room - In private room , User B is not able to access the chat in contrast to the message shown

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20053] opened 2023-06-02 13:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to web chrome and login with User A which needs to be a phone number and create a new workspace and invite User B
2. Create a room from User A and include the workspace that you created earlier.
3. Select private room and see that it displays the message 'People invited to this room can find it'
4. Now click on the room header and click on share code. Copy the URL.
5. Go to the normal chat with User B and send the link
6. From user B, login in another web chrome which also needs to be a phone number and click on the link that was received
7. Result: See that it doesn't gives access to the chat even when the message earlier displayed 'People invited to this room can find it'

## Expected Result:
In private room , User B should be able to access the chat in accordance with the message shown

## Actual Result:
In private room , User B is not able to access the chat in contrast to the message shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6415f191-8cb2-4467-b82c-f5b0254d9951

https://github.com/Expensify/App/assets/93399543/3edad024-985b-485d-9b5d-23106f08d325

**Expensify/Expensify Issue URL:**

**Issue reported by:** @avi-shek-jha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685513600964899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2023-06-05 16:53
Joining a private room via QR code was never considered in the user created room plan. 

Good call out generally that user created rooms have some loose ends that need tying up. I can try to list them all as a next step. 

Inviting to private rooms via @mentions or the members page was the only way we initially considered that users would join a private room fwiw

**Comment by MitchExpensify** [comment] 2023-06-06 10:43
Asking in #product here https://expensify.slack.com/archives/C03U7DCU4/p1686048196416499

**Comment by MitchExpensify** [comment] 2023-06-09 11:29
I think so yes! Sending out the strategy@ email today once I get some feedback on the best room to continue discussion in [Tracking issue for broader project here](https://github.com/Expensify/Expensify/issues/290783) 

Putting this on hold and switching to weekly

**Comment by trjExpensify** [comment] 2023-06-09 13:20
Dope, donezo.

**Comment by trjExpensify** [comment] 2023-06-20 00:33
Still on hold, Mitch is progressing the pre-design

**Comment by trjExpensify** [comment] 2023-06-30 12:56
@MitchExpensify I'm going to put this on monthly as you progress that.

**Comment by MitchExpensify** [comment] 2023-07-01 18:25
Sounds goooood! thanks

**Comment by trjExpensify** [comment] 2023-08-01 14:43
No change Melv, you eager so and so!

**Comment by trjExpensify** [comment] 2023-09-04 09:32
Doc is still going through the process, Melv.

**Comment by trjExpensify** [comment] 2023-10-06 00:32
Same, Melv.

**Comment by trjExpensify** [comment] 2023-11-06 11:29
@MitchExpensify can you give me an assessment on the next steps for this issue?

**Comment by MitchExpensify** [comment] 2023-11-07 22:56
Yessir! So circling back on the OP.. Sharing a code isn't considered inviting someone so the message around "people invited to this room can see it" holds true - I.e. It is expected that sharing a URL with someone who hasn't been invited via @mention or via the Members pane would not have access. 

All of that said we have a flow in the works for folks viewing a room they do not have access to: Add a "[Request to Join" flow for chats you do not have access to](https://github.com/Expensify/Expensify/issues/324451#top)

**Comment by MitchExpensify** [comment] 2023-11-07 22:57
So perhaps closing this makes most sense? Curious what you think

**Comment by trjExpensify** [comment] 2023-11-07 23:07
Perfect, that works for me. I actually echoed similar at the top of this issue, so if that hasn't changed then I agree we can close this as expected behaviour:

>If you aren't a member of the room already, then you can't join it, so I don't think I'd expect the QR code to work.

**Closed by trjExpensify** 2023-11-07 23:06 UTC
Labels: Monthly, Bug
