### ISSUE TITLE
[HOLD for payment 2023-07-17] Chat  -App crash after remove the member

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22351] opened 2023-07-06 17:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From userA, go to Settings > Workspaces
2. Click on New workspace button
3. Go to the #announce room and send a message
4. Click on the room header
5. Go to Settings > Welcome message
6. Add any message and click on the save button
7. Go to Settings > Workspaces >Members > Invite
8. Invite userB
9. From userB, go to #announce
10. Hover over welcome message > click reply in thread option > 11. send a message in thread
12. From userA, remove the userB from workspace

## Expected Result:
App should not crash

## Actual Result:
App crash for userB

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.37-3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/95f6de19-adda-4298-82cf-c4ba6ec2096b

https://github.com/Expensify/App/assets/93399543/ef6f9af9-73ad-4579-b851-95902a4ec872

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688661191934669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2023-07-06 17:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes after remove member

### What is the root cause of that problem?
Cash happens on this line:
https://github.com/Expensify/App/blob/01a18f02aeff2c1b7a39c094babba56d3a3c5584/src/libs/ReportUtils.js#L477

So after user is removed from policy, report is set to null, not undefined so it doesn't return early

### What changes do you think we should make in order to solve the problem?
Update condition to
```
 if (!report) {
```
or
```
 if (_.isEmpty(report)) {
```

**Comment by cead22** [comment] 2023-07-06 17:44
Looks like that was introduced in [this PR](https://github.com/Expensify/App/pull/21092), cc @chiragsalian

**Comment by chiragsalian** [comment] 2023-07-06 17:48
Technically i think my PR didn't introduce that crash because if you remove [this block](https://github.com/Expensify/App/blob/01a18f02aeff2c1b7a39c094babba56d3a3c5584/src/libs/ReportUtils.js#L477-L479) that i added it would still crash.

So technically crash could not happen on that line because if report is set to null it would never enter that block linked above.

But yes i agree with the changes. I personally prefer isEmpty. Are you creating the PR @cead22 or shall i?

**Comment by situchan** [comment] 2023-07-06 17:49
I am available right now to raise PR 🙂

**Comment by chiragsalian** [comment] 2023-07-06 17:50
Neat, i'll defer to @cead22 since he's assigned so I'm not sure if he's already started working on it.

**Comment by chiragsalian** [comment] 2023-07-06 17:56
I'm taking over this issue from carlos.
@situchan, are you available to create/test and have the PR ready in the next hour or earlier? 🙂

**Comment by situchan** [comment] 2023-07-06 17:57
yes

**Comment by chiragsalian** [comment] 2023-07-06 17:57
uff, sorry for the label and assignment spam. GH is running weird for me. Anyway neat, thanks @situchan, feel free to assign it to me when ready.

**Comment by situchan** [comment] 2023-07-06 17:59
While I am testing, I found another inconsistency between staging and production:

<img width="350" alt="Screenshot 2023-07-06 at 7 57 39 PM" src="https://github.com/Expensify/App/assets/108292595/ecd9d7cf-7f2d-4771-9503-ed9b10d49e3b">
<img width="350" alt="Screenshot 2023-07-06 at 7 57 34 PM" src="https://github.com/Expensify/App/assets/108292595/2bcffee4-ad09-4601-a882-22a3eb05dc9f">

Is this expected?

**Comment by chiragsalian** [comment] 2023-07-06 18:00
I'm assuming left is staging and right is production. Well we improved the subheader code. If there is no workspace to show i think "From unavailable workspace" looks incorrect. So i think the left, assuming its staging looks good to me.

**Comment by situchan** [comment] 2023-07-06 18:23
@chiragsalian [PR](https://github.com/Expensify/App/pull/22360) is up

**Comment by chiragsalian** [comment] 2023-07-06 18:33
I merged the PR. I'll work on CP-ing it to staging now.

**Comment by chiragsalian** [comment] 2023-07-06 18:36
I've kicked off a cherry pick [here](https://github.com/Expensify/App/actions/runs/5478951940).
For how much longer will you be online @situchan? Asking because once the code is on staging web it would be great if you can retest. I think it should be on staging web in approx 20min. If you are not around that's fine too and i can test on staging.

**Comment by chiragsalian** [comment] 2023-07-06 18:42
deploy action just created [here](https://github.com/Expensify/App/actions/runs/5478989554)

**Comment by situchan** [comment] 2023-07-06 18:45
I am still online a few hrs

**Comment by situchan** [comment] 2023-07-06 18:54
Just tested staging web. Not reproducible.
![image](https://github.com/Expensify/App/assets/108292595/881875ad-58db-4325-bd85-347754511d3f)

**Comment by chiragsalian** [comment] 2023-07-06 18:57
Awesome, yes that should suffice. I'll remove the deploy blocker label. Thanks @situchan.
 
@lschurr, can you handle payment for @situchan. I believe it should be after a 7 day regression testing period but if not feel free to correct me.

**Comment by ayazhussain79** [comment] 2023-07-06 21:00
I think this [PR](https://github.com/Expensify/App/pull/22360) has fixed [this bug](https://github.com/Expensify/App/issues/22309) that i have reported before @chiragsalian  can you please chat that

**Comment by chiragsalian** [comment] 2023-07-06 21:46
> do we also need to pay @gadhiyamanan for reporting?

I think so, yes.

> I think this https://github.com/Expensify/App/pull/22360 has fixed https://github.com/Expensify/App/issues/22309 that i have reported before @chiragsalian can you please check that

Yup looks like it. @conorpendergrast i think we have to pay @ayazhussain79 also since its two different bugs solved by the same PR.

**Comment by lschurr** [comment] 2023-07-17 15:22
@gadhiyamanan @situchan - can you apply here? https://www.upwork.com/jobs/~019e655fd4b52e872f

**Comment by situchan** [comment] 2023-07-17 16:11
If you can send direct offer, that would be much appreciated.

**Comment by lschurr** [comment] 2023-07-17 16:22
Could you both put your Upwork profile here?

**Comment by gadhiyamanan** [comment] 2023-07-17 16:29
@lschurr here's my profile link : https://www.upwork.com/freelancers/~01b6fd34f946454a68

**Comment by lschurr** [comment] 2023-07-17 17:49
Great, I've sent invites to you both.

**Comment by situchan** [comment] 2023-07-17 18:33
> Great, I've sent invites to you both.

Accepted, thanks

**Comment by situchan** [comment] 2023-07-17 21:13
@lschurr I maybe eligible for speed bonus as well

**Comment by lschurr** [comment] 2023-07-17 21:18
I think since this was a minor change, we would only pay the base pay - @chiragsalian - do you have thoughts on this?

**Closed** 2023-07-18 17:32 UTC
Labels: Engineering, Daily, Awaiting Payment
