### ISSUE TITLE
[$1000] IOS - iOS app crashes when send message with very long invalid email

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21266] opened 2023-06-21 20:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send this message:
[jaj@asjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfidekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdicdjejajasjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfisjksksjsjssskssjskskssksksksksskdkddkddkdksskskdkdkdksskskskdkdkdkdkekeekdkddenejeodxkdndekkdjddkeemdjxkdenendkdjddekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdicdjejajasjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfidekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdi.cdjd](mailto:jaj@asjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfidekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdicdjejajasjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfisjksksjsjssskssjskskssksksksksskdkddkddkdksskskdkdkdksskskskdkdkdkdkekeekdkddenejeodxkdndekkdjddkeemdjxkdenendkdjddekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdicdjejajasjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfidekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdi.cdjd)

## Expected Result:
iOS app does not crash when send message with very long invalid email

## Actual Result:
iOS app crashes when send message with very long invalid email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![crash (2) (1)](https://github.com/Expensify/App/assets/93399543/69e73c8d-b4a1-4035-8a30-57c37fc40dbf)

https://github.com/Expensify/App/assets/93399543/cb7f686c-92b1-4f8b-bb80-d2d6d7248aaf

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Situ Chandra Shil

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686758977117659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6eba6927987b0dc</li>
        <li>Upwork Job ID: 1673777985979330560</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by tjferriss** [comment] 2023-06-23 14:29
I was not able to reproduce the issue on mobile web. The message was sent as expected.

I'm currently not able to access the iOS testflight app. The chat list is not loading. I will try again later.

**Comment by tjferriss** [comment] 2023-06-27 19:40
The app immediately crashed when I tried to send the message. Even when I click Refresh and try to open the chat back up it crashes again.

![IMG_7178](https://github.com/Expensify/App/assets/8292562/06fdffbe-5b57-475c-a0b3-afa14f61c695)

**Comment by arthurmfgtab** [comment] 2023-06-28 10:06
Hey, @tjferriss 
I'm Arthur from Callstack - expert contributor group - and I'd like to take a look at this issue

**Comment by arthurmfgtab** [comment] 2023-07-04 06:36
Hey, @tjferriss @allroundexperts 
I'm Arthur from Callstack - expert contributor group - and I will start investigating this :)

**Comment by arthurmfgtab** [comment] 2023-07-04 19:44
@allroundexperts @tjferriss 

Hey, peeps, here's an update on the issue

It seems that, more then the length of the email, what's really causing problem is its domain.
I tested it using "aaa@aaaaaaaaaaaaaaaaaaaaaaaaaaaaa.c" and the problem still persists. However, if I switch that ".c" at the end to ".com" it works fine.

Upon some investigation, I noticed that the `URL_WEBSITE_REGEX` (see image below) is made of, among other things, a lot of domains. It looks like if the domain of the email included in our chat message is not there, the `urlRegex.exec(href)` bit will throw.

I'll open a Slack convo tomorrow to discuss possible solutions for the issue :)

<img width="653" alt="image" src="https://github.com/Expensify/App/assets/55854142/703d8b81-83a3-49d5-add7-36e9837c7f7b">

**Comment by arthurmfgtab** [comment] 2023-07-06 06:26
@tjferriss @allroundexperts 

I wonder if you guys had a change to take a look at [this](https://github.com/Expensify/App/issues/21266#issuecomment-1620657530)
I'm preparing a proposal to stop the crashing issue, but I'd like to first know from you guys if invalid domain should be allowed in the app

**Comment by shubham1206agra** [comment] 2023-07-06 06:42
> @tjferriss @allroundexperts
> 
> I wonder if you guys had a change to take a look at [this](https://github.com/Expensify/App/issues/21266#issuecomment-1620657530) I'm preparing a proposal to stop the crashing issue, but I'd like to first know from you guys if invalid domain should be allowed in the app



> @allroundexperts @tjferriss
> 
> Hey, peeps, here's an update on the issue
> 
> It seems that, more then the length of the email, what's really causing problem is its domain. I tested it using "[aaa@aaaaaaaaaaaaaaaaaaaaaaaaaaaaa.c](mailto:aaa@aaaaaaaaaaaaaaaaaaaaaaaaaaaaa.c)" and the problem still persists. However, if I switch that ".c" at the end to ".com" it works fine.
> 
> Upon some investigation, I noticed that the `URL_WEBSITE_REGEX` (see image below) is made of, among other things, a lot of domains. It looks like if the domain of the email included in our chat message is not there, the `urlRegex.exec(href)` bit will throw.
> 
> I'll open a Slack convo tomorrow to discuss possible solutions for the issue :)
> <img alt="image" width="653" src="https://user-images.githubusercontent.com/55854142/250979859-703d8b81-83a3-49d5-add7-36e9837c7f7b.png">

I don't think so its related to regex parsing. I think its something else, as it should not work on any device if there's a problem with regex

**Comment by arthurmfgtab** [comment] 2023-07-06 16:06
Hey @shubham1206agra , thanks for your insight
I tested it by forcing a call to the `getURLObject` function (by putting the following code in the `submitForm` function at /src/pages/home/report/ReportActionCompose.js: `urlUtils.getURLObject('aaa@aaaaaaaaaaaaaaaaaaaaaaaaaaaaa.c');` and then hitting the "send message" button in any chat). When I do it the app crashes and from what I can see it's because of the domain. Do you think that's reasonable? If not, do you have a suggestion on another way to check it?

Thanks in advance :)

**Comment by arthurmfgtab** [comment] 2023-07-06 16:06
I'll be off tomorrow but will be getting back to this on Monday.

**Comment by eh2077** [comment] 2023-07-06 16:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOS - iOS app crashes when send message with very long invalid email

### What is the root cause of that problem?

The root cause of this issue is that we pass a long email, like

```
jaj@asjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfidekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdicdjejajasjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfisjksksjsjssskssjskskssksksksksskdkddkddkdksskskdkdkdksskskskdkdkdkdkekeekdkddenejeodxkdndekkdjddkeemdjxkdenendkdjddekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdicdjejajasjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfidekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdi.cdjd
```

to method `Url.getURLObject`, see

https://github.com/Expensify/App/blob/411d466cabe13b67de1d5da5a61aef303ef38a1f/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L27

https://github.com/Expensify/App/blob/411d466cabe13b67de1d5da5a61aef303ef38a1f/src/libs/Url.js#L20-L30

which causes an error, `Maximum regex stack depth reached`,  thrown by regex engine.

### What changes do you think we should make in order to solve the problem?

As the error, `Maximum regex stack depth reached`, is thrown by the regex engine and it's tricky to improve regex `URL_WEBSITE_REGEX`. 

To fix this issue, we can check if `href` is an email by checking if it starts with `mailto:` or by method 

```js
Str.isValidEmailMarkdown(href.replace(/^mailto:/i, ''))
```

to skip executing `URL_WEBSITE_REGEX` regex for the long email input and thus avoid the regex engine error.

To achieve it, we can add following snippet 

```js
if (Str.isValidEmailMarkdown(href.replace(/^mailto:/i, ''))) {
    return {
        href: undefined,
        protocol: undefined,
        hostname: undefined,
        path: undefined,
    };
}
```



after this line

https://github.com/Expensify/App/blob/411d466cabe13b67de1d5da5a61aef303ef38a1f/src/libs/Url.js#L20

to avoid exec regex `URL_WEBSITE_REGEX` on unusual email input.

See demo video

<details>
  <summary>Click to see demo video</summary>

  https://github.com/Expensify/App/assets/117511920/99f0df17-f849-4e49-a141-dbb2f327caf3
</details>

### What alternative solutions did you explore? (Optional)

N/A

**Comment by shubham1206agra** [comment] 2023-07-07 14:30
@allroundexperts We need to expand this issue. It's not just emails but links too have the problem in IOS.

Example: www.jajasjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfidekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdicdjejajasjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfisjksksjsjssskssjskskssksksksksskdkddkddkdksskskdkdkdksskskskdkdkdkdkekeekdkddenejeodxkdndekkdjddkeemdjxkdenendkdjddekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdicdjejajasjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfidekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdi.cdjd

Error:
<img width="389" alt="image" src="https://github.com/Expensify/App/assets/58412969/3f2c5d47-a8e2-465b-ae1f-6c37602bf83c">

It looks like more problem of expensify-common

**Comment by tjferriss** [comment] 2023-07-10 18:15
@allroundexperts do any of these proposals look good to you?

**Comment by ShogunFire** [comment] 2023-07-10 21:28
Actually we could maybe cut the regex in parts, maybe one part for the http:// 

One part for the name of the website

One part for .com and other domains

One part for routes after the domain

One part for parameters after ?

That way we make it easier for long strings

**Comment by tjferriss** [comment] 2023-07-12 06:02
>Just catch the error to prevent the crash and do nothing (or create smaller regexes for iOS only).

I like this option.

**Comment by tjferriss** [comment] 2023-07-12 19:53
I shared the thread in our internal product channel and asked more people to weigh in.

**Comment by tjferriss** [comment] 2023-07-19 05:26
>Just catch the error to prevent the crash and do nothing (or create smaller regexes for iOS only).

Looks like we're all in agreement with the above solution.

**Comment by eh2077** [comment] 2023-07-19 10:44
@allroundexperts I have suggested to catch the error in my alternative solution https://github.com/Expensify/App/issues/21266#issuecomment-1623942649

**Comment by shubham1206agra** [comment] 2023-07-19 11:31
> Cool, lets go with @eh2077's alternate [proposal](https://github.com/Expensify/App/issues/21266#issuecomment-1623942649).
> 
> 🎀 👀 🎀 C+ reviewed

@allroundexperts I think you might want to wait for other proposals before reviewing it.

Cause the solution was in the discussion stage and the solution proposed is not entirely correct

**Comment by shubham1206agra** [comment] 2023-07-19 11:36
> @shubham1206agra Were you following the Slack [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1689657812893529?thread_ts=1689024254.320539&cid=C01GTK53T8Q)? There was a agreement on just catching the error and doing nothing.

It just handle the email. What about links?
See [this](https://github.com/Expensify/App/issues/21266#issuecomment-1625501370)

**Comment by shubham1206agra** [comment] 2023-07-19 11:39
> > It just handle the email. What about links?
> 
> I think the discussion was around both links and emails.

Yes. But the errors are coming from different areas ig

**Comment by shubham1206agra** [comment] 2023-07-19 11:46
> > Yes. But the errors are coming from different areas ig
> 
> Hm... When we're adding a `try/catch` around the regex expression itself, It will cover all the cases where its being used.

Not really sure about that
I am just saying give some time to get another proposal. If you don't see that as a better proposal, please go with the original one.

**Comment by shubham1206agra** [comment] 2023-07-19 12:49
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

IOS - iOS app crashes when send message with very long invalid email
### What is the root cause of that problem?

In the case of iOS, this is happening due to low stack memory due to architectural difference. (May also happen on other lower end devices too). This is occuring mainly as we are using highly recursive regex.

In the case of emails, this is occuring from the method `Url.getURLObject` which is used in
https://github.com/Expensify/App/blob/411d466cabe13b67de1d5da5a61aef303ef38a1f/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L27

Error coming from
https://github.com/Expensify/App/blob/411d466cabe13b67de1d5da5a61aef303ef38a1f/src/libs/Url.js#L22

Error: `RangeError: Maximum regex stack depth reached, js engine: hermes`

In the case of links, this is occuring from the method `parser.replace(text)` which is used in
https://github.com/Expensify/App/blob/2d2008aae95588443adb0814b12151023ddb9792/src/libs/ReportUtils.js#L2278

Error coming from
https://github.com/Expensify/App/blob/2d2008aae95588443adb0814b12151023ddb9792/src/libs/ReportUtils.js#L1298

Error: `RangeError: Maximum regex stack depth reached, js engine: hermes` 

### What changes do you think we should make in order to solve the problem?

We will add try catch logic at both places as discussed and ignore the error.

In `Url.js`
```js
    try {
        const match = urlRegex.exec(href);
        if (!match) {
            return {
                href: undefined,
                protocol: undefined,
                hostname: undefined,
                path: undefined,
            };
        }
        const baseUrl = match[0];
        const protocol = match[1];
        return {
            href,
            protocol,
            hostname: baseUrl.replace(protocol, ''),
            path: href.startsWith(baseUrl) ? href.replace(baseUrl, '') : '',
        };
    } catch (e) {
        return {
            href: undefined,
            protocol: undefined,
            hostname: undefined,
            path: undefined,
        };
    }
```

And in `ReportUtils.js`
```js
    if (text.length < CONST.MAX_MARKUP_LENGTH) {
        try {
            return parser.replace(text);
        } catch (e) {
            return _.escape(text);
        }
    } else {
        return _.escape(text);
    }
```

### What alternative solutions did you explore? (Optional)

May impose lower limit on number of characters for iOS / May design different regex that may not rely on recursion too much (requires much more thought)

**Comment by shubham1206agra** [comment] 2023-07-19 13:36
> I think I proposed the try/catch solution first and it can also fix another case pointed out by @shubham1206agra https://github.com/Expensify/App/issues/21266#issuecomment-1625501370
> 

Not really
I checked the solution where I will put try catch only in url.js
But it doesn't work on my test case 😕

**Comment by eh2077** [comment] 2023-07-19 14:03
### Proposal

[Updated](https://github.com/Expensify/App/issues/21266#issuecomment-1623942649) to add a more general try/catch solution for email/link parsing related regex in expensify-common repo.

**Comment by bondydaa** [comment] 2023-07-20 16:39
agree we should just implement the try/catch solutions to avoid the crash, which I believe is the "alternative" solution proposed for now.

**Comment by eh2077** [comment] 2023-07-21 06:44
@allroundexperts The PR https://github.com/Expensify/expensify-common/pull/559 for expensify-common is ready for review.

**Comment by eh2077** [comment] 2023-07-24 16:12
@allroundexperts Friendly bump. I added tests in https://github.com/Expensify/expensify-common/pull/559

cc @bondydaa

**Comment by tjferriss** [comment] 2023-07-25 23:08
Looks like PR is still under review.

**Comment by eh2077** [comment] 2023-07-31 02:00
Friendly bump @allroundexperts , can you help to review PR https://github.com/Expensify/App/pull/23774 when you get time?

**Comment by tjferriss** [comment] 2023-08-01 21:19
I see @eh2077 and @allroundexperts are reviewing the PR.

**Comment by bondydaa** [comment] 2023-08-02 22:35
merged PR

**Comment by tjferriss** [comment] 2023-08-09 05:07
PR hit staging yesterday

**Comment by tjferriss** [comment] 2023-08-15 19:54
The PR has been on production for seven days now, but I don't see the payment comment https://github.com/Expensify/App/pull/23774

- [ ] @situchan reporting bonus $250
- [ ] @eh2077 contributor $1000
- [ ] @allroundexperts C+ $1000

@bondydaa can you double check this for me? Then I'll get payments processed in Upworks.

**Comment by tjferriss** [comment] 2023-08-17 18:41
@eh2077 has been paid via Upworks and @situchan has been sent an offer

**Comment by JmillsExpensify** [comment] 2023-08-24 05:09
Reviewed the details for @allroundexperts. $1,000 approved for payment in NewDot based on BZ summary above.

**Comment by Antasel** [comment] 2023-08-24 06:55
@JmillsExpensify @bondydaa @tjferriss @allroundexperts 
I think this issue has not been resolved properly . 
I mean we still have inconsistency between iOS and other platform, it's cased by solution here

new test steps: 
1. send # _aaa.aaaaaaaaaaaaaa.aaaaaaaa.aaaaaaaa_ on web platform, then can see that 'heading1' and 'italic' have been applied .

![Screenshot_3](https://github.com/Expensify/App/assets/139204153/69ed65aa-074c-48cc-bb25-b91f5193bdcf)

2. send same text on iOS, then can check that 'heading1' and 'italic' have not been applied, still `#`, `_` is remained .
![Screenshot_2](https://github.com/Expensify/App/assets/139204153/f3d4b0ab-a3f4-4f1e-a315-402c510f73f9)

The cause is that, in iOS, autolink rule has not been parsed, but it's caught by 'maximum regex stack depth reached', so heading1, italic can't be parsed.

**Comment by tjferriss** [comment] 2023-08-28 22:17
@Antasel I agree, I'm able to reproduce the issue on iOS.

**Comment by Antasel** [comment] 2023-08-28 22:22
@tjferriss Thanks for your rechecking.
So, This issue will be reopened ? or open another issue. I'd like to dig into it to resolve it.

**Comment by tjferriss** [comment] 2023-08-28 22:37
Let's keep working on this issue here. @allroundexperts do you agree with the reasoning @Antasel has outlined above.

**Comment by agilejune** [comment] 2023-08-30 03:19
@bondydaa @tjferriss 
it's possible for me to propose a solution ? I mean you would accept new one?, because here @eh2077 had been assigned a long time ago, but his proposal is incomplete, and he's already get paid for it

**Comment by Antasel** [comment] 2023-08-30 10:53
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
When some strings are parsed by URL_WEBSITE_REGEX, iOS app crashes.

### What is the root cause of that problem ?
The URL_WEBSITE_REGEX pattern has tld part, which is consisted of possible predefined tlds, which is more than 1500 .
when string goes through every tld to be checked, maximum regex stack depth is reached, causing ios crashes

### What changes do you think we should make in order to solve the problem?
To avoid to be checked by a lot tlds, we should replace tlds part with general regex pattern (like `[a-z0-9](?:[-a-z0-9]*[a-z0-9])+`), and check tlds after regex pattern has been executed. 

We need to add a few tweaks in all related to URL_WEBSITE_REGEX.

1. we need to add a few tweaks in expensify-common, by capturing group against tld part, and checking if captured tld candidates are contained in [TLD_REGEX](https://github.com/Expensify/expensify-common/blob/main/lib/tlds.jsx#L1).

The specific changes can be checked in https://github.com/Expensify/expensify-common/compare/main...Antasel:expensify-common:fix-%2321266

2. also need to check tlds in https://github.com/Expensify/App/blob/main/src/libs/ValidationUtils.js#L259
as a result, isValidWebsite(url) function would be as following 
```
function isValidWebsite(url) {
    const urlRegex = new RegExp(`^${URL_REGEX_WITH_REQUIRED_PROTOCOL}$`, 'i');
    const match = urlRegex.exec(url);

    return (match !== null && _.contains(TLD_REGEX.split('|'), match[4].toUpperCase()));
}
```

with above tweaks, we are able to keep original functionality of TLD, and prevent iOS app to cause `'Regex maximum depth reached'` error

PS: I can't find getUrlObject(href) function, maybe which has been removed with other PR .

**Comment by Antasel** [comment] 2023-08-30 10:54
@tjferriss @bondydaa @allroundexperts 
Could you please check my proposal ?

**Comment by agilejune** [comment] 2023-08-30 10:55
> You can submit a proposal for sure!

ok, thanks for your reply

**Comment by Antasel** [comment] 2023-09-04 11:43
@tjferriss @allroundexperts 
I am curious if you ever checked my [proposal](https://github.com/Expensify/App/issues/21266#issuecomment-1698935970)

**Comment by bondydaa** [comment] 2023-09-04 23:00
Ah okay so this isn't about iOS still crashing just that iOS still fails to properly parse the "markdown" and the update proposal is potentially a way to help prevent the regex from errorring?

I started a thread here about this b/c my regex knowledge isn't the best https://expensify.slack.com/archives/C01GTK53T8Q/p1693868279606089

but if we're able to prevent trying to parse the TLD regex if we don't need to then could be worth while.

**Comment by Antasel** [comment] 2023-09-05 01:14
> so this isn't about iOS still crashing just that iOS still fails to properly parse the "markdown" and the update proposal is potentially a way to help prevent the regex from errorring?

iOS is not crashing since parsing markdown has been wrapped by 'try-catch', but [URL_WEBSITE_REGEX](https://github.com/Expensify/expensify-common/blob/main/lib/Url.js#L5) with TLD will still causing 'maximum regex depth reached' error which is caught by 'try-catch'. but it makes iOS app stuck for a few seconds, and all rule after autolink rule will not be parsed.
so we need to prevent to parse TLD regex in URL_WEBSITE_REGEX .

**Comment by Antasel** [comment] 2023-09-14 06:20
@bondydaa @allroundexperts 
Are you about to accept to my solution ?

**Comment by tjferriss** [comment] 2023-09-16 22:16
After some internal discussion, I think we can close out this issue for now. We don't anticipate this being a real issue for users presently.

**Closed by tjferriss** 2023-09-16 22:16 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
