### ISSUE TITLE
[HOLD for payment 2023-10-09] [HOLD for payment 2023-09-27] [Tracking] Improve ReportScreen re-renders

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#26087] opened 2023-08-28 14:24 UTC
### Problem

The Report screen has a lot of performance bottlenecks. Mostly they are caused by unnecessary re-renders and given this component is very heavy to render, it can visibly slow down the App.

### Solution

This is a tracking issue for multiple PRs and improvements which are found.

We are analysing the render cycles via Flipper Profiler and React Dev Tools and finding where are the bottle necks in the rendering of the component and its sub-tree.

So far we have found bugs regarding shared context and misuse of hooks that cause unnecessary re-renders. It might be an issue of death by a thousand paper cuts where seemingly innocuous changes cause large tree re-renders.

- https://github.com/Expensify/App/issues/27214

PRs:
- https://github.com/Expensify/App/pull/26173
- https://github.com/Expensify/App/pull/26772
- https://github.com/Expensify/App/pull/27130
- https://github.com/Expensify/react-native-onyx/pull/329

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010777a443667dee8f</li>
        <li>Upwork Job ID: 1696166898891616256</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by ospfranco** [comment] 2023-08-28 14:25
Assign me :)

**Comment by Christinadobrzyn** [comment] 2023-08-29 19:46
Hey @ospfranco can you complete these steps for the Upwork job assignment? Thanks! https://github.com/Expensify/App/issues/26087#issuecomment-1695797302

**Comment by ospfranco** [comment] 2023-08-30 06:32
I'm working with margelo internally, do I need an upwork account @mountiny?

**Comment by mountiny** [comment] 2023-08-30 12:55
@Christinadobrzyn @ospfranco is from Margelo so he does not use Upwork

**Comment by Christinadobrzyn** [comment] 2023-08-30 22:34
Ah! So sorry for my confusion @ospfranco!

**Comment by Christinadobrzyn** [comment] 2023-08-30 22:35
I think this can be moved to weekly as it looks like a PR is started.

**Comment by mountiny** [comment] 2023-09-12 05:13
Updated the issue body with links to the relevant PRs and issue

**Comment by Christinadobrzyn** [comment] 2023-09-18 20:58
Maybe we should remove the `Bug`, `Awaiting Payment`, and `Internal` labels and then add a `Planning` label? to see if that stop these auto-messages?

**Comment by mountiny** [comment] 2023-09-19 02:28
The payment messages will still come through as the PRs were linked to this issue.

**Comment by Christinadobrzyn** [comment] 2023-09-26 20:06
So are we set to pay these on 9-27? 

[[NoQA] Reduce SidebarLinksData render time #27364](https://github.com/Expensify/App/issues/26087#issuecomment-1727195662)
[Update Onyx to use a map for Onyx collection keys #27130](https://github.com/Expensify/App/issues/26087#issuecomment-1719181223)

If yes, do we have regression tests for these?

**Comment by mountiny** [comment] 2023-09-27 07:06
There are no regression tests needed for these/ already covered with LHN tests and automated tests.

For now I think it just payments to @situchan, can you please help us recap what payments are due for this issue.

**Comment by situchan** [comment] 2023-09-27 07:10
- #27130 (production on Sep 14)
- #27364 (production on Sep 20)

1k total for reviewing 2 PRs above

I am fine either quick payment or wait until all tracking issues are fixed.

**Comment by Christinadobrzyn** [comment] 2023-09-29 00:04
I think we should do one payment at the end of all of this, does that sound okay @situchan?

**Comment by situchan** [comment] 2023-09-29 02:47
> I think we should do one payment at the end of all of this, does that sound okay @situchan?

👍

**Comment by Christinadobrzyn** [comment] 2023-10-10 22:32
hey @situchan or @mountiny are [these](https://github.com/Expensify/App/issues/26087#issuecomment-1736829398) the two PRS we're paying? or are there more?

If it's only those two, are we ready for payment?

**Comment by mountiny** [comment] 2023-10-10 23:23
Correct $1000 to @situchan that is it. Oscar is from agency

**Comment by Christinadobrzyn** [comment] 2023-10-18 23:20
Sounds good, here's the payment details

Payouts due:

Issue Reporter: NA
Contributor: @ospfranco - payment in contract
Contributor+: $1000 @situchan 

Eligible for 50% #urgency bonus? NA- internal job

@situchan are you paid through Upwork? If yes, can you accept the offer here - https://www.upwork.com/jobs/~0102af23fe16b91266

**Comment by mountiny** [comment] 2023-10-18 23:50
@Christinadobrzyn Oscar is paid outside of Upwork since he is from Margelo

**Comment by Christinadobrzyn** [comment] 2023-10-19 21:51
Sounds good - thanks @mountiny. 

@situchan I paid you based on this [payment structure](https://github.com/Expensify/App/issues/26087#issuecomment-1769567129) in Upwork. 

closing this but let me know if I'm missing anything

**Comment by mountiny** [comment] 2023-10-19 22:24
Ah that was my bad too, @fedirjh was additional help on this complex PR, they also reviewed and tested so they should get $1000 too

**Comment by Christinadobrzyn** [comment] 2023-10-20 01:05
Ah sorry for missing that @fedirjh - thank you for letting me know. 

Can you accept my offer in Upwork here - https://www.upwork.com/jobs/~0102af23fe16b91266

**Comment by Christinadobrzyn** [comment] 2023-10-20 22:00
Awesome! @fedirjh Paid you based on this [payment structure](https://github.com/Expensify/App/issues/26087#issuecomment-1769567129)

I think we're good to close, please reopen if anything else is needed!

**Closed by Christinadobrzyn** 2023-10-20 22:00 UTC
Labels: Engineering, Daily, Internal, Planning, Awaiting Payment
