### ISSUE TITLE
[Guided Setup Stage 3] Workspace invites not including a link for invalidated sign ins for first time users

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#44749] opened 2024-07-02 21:33 UTC
As part of our updates to Newdot, [we update organic sign-ups ](https://github.com/Expensify/App/pull/42887)and [email invite links ](https://github.com/Expensify/App/issues/34166) to allow invalidated sign-ins for first-time users. This helps them convert, and after using the product, they can validate their account with a magic code. 

We did not update this for workspace invites, whereas we should be. So the new.expensify.com link below should also allow a first-time user to sign in without validating their account. 

![image](https://github.com/Expensify/App/assets/2364487/e0c32ff6-3db9-4127-99d1-7fe99123d224)

@techievivek is also currently updating the links in the [Pay buttons](https://github.com/Expensify/App/issues/42321#issuecomment-2193872793) for first-time users being sent IOUs for more context. 

We need to update this one too.

**Comment by trjExpensify** [comment] 2024-07-02 21:36
@techievivek I have a feeling this might be something to do with first message (the content of the welcomeNote) being custom subject commented added to the workspace chat, and therefore using the `Notification_Report_CustomSubjectComment` template not `Notification_Report_Comment` maybe?

**Comment by deetergp** [comment] 2024-07-05 19:27
We also need to add this to the Group Chat and User Created Room invites.

**Comment by techievivek** [comment] 2024-07-08 07:57
Sent a PR to fix the behaviour in case of pay button https://github.com/Expensify/App/issues/42321, looking into this one now.

**Comment by techievivek** [comment] 2024-07-08 08:45
I investigated this issue and found that we are not adding the special sign-in code in email because invited users' accounts are not created in a closed state. When users are invited to a chat, their accounts are created in a closed state, but this does not happen for workspace invites. 

We have two options: either update the code to create invited users' accounts in a closed state(not sure about historical reasoning here), or modify the [condition to only require that the account is in an unvalidated state](https://github.com/Expensify/Web-Expensify/blob/f8ab66492022f2a7e333b9f29a54b809a04ca561/lib/Notification/Report/Comment.php#L740), without considering whether it is closed.

**Comment by techievivek** [comment] 2024-07-08 08:48
I think we can move with the second option here since only with auto sign-in from the activity email can the users remain in an invalidated state and be able to access the App. Once that session is over, they must validate their account for further access.

**Comment by techievivek** [comment] 2024-07-08 09:08
@deetergp It doesn't look like we send an email invitation when a user is added to the group chat, can you please confirm? I l tested the above PR for workspace invite and room invite and it is working as expected but there are no email flow for group chat invites. Am I missing anything?

**Comment by deetergp** [comment] 2024-07-08 19:22
@techievivek That's my bad. We don't send an invitation per se, when we create a group chat with un-registered users, or add them to a group chat later, but once someone comments, we send an unread messages summary to them, and that DOES use the new direct sign-in link.

**Comment by trjExpensify** [comment] 2024-07-08 22:52
Nice, thanks for getting to the bottom of the issue and getting the PR merged, Vivek!

**Comment by trjExpensify** [comment] 2024-07-15 14:23
With that, can we close this issue now?

**Comment by techievivek** [comment] 2024-07-17 07:35
Yep, closing this now. Let me know if there are any other flows where we might have missed adding invalidated sign-ins.

**Comment by techievivek** [comment] 2024-07-17 07:38
Coming from this other issue https://github.com/Expensify/App/issues/42321#issuecomment-2231059973, do we need to add a regression test for this?

**Comment by trjExpensify** [comment] 2024-07-19 01:04
I think we can create a GH for QA to modify this test case:  https://expensify.testrail.io/index.php?/cases/view/1971060&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=229065

**Comment by techievivek** [comment] 2024-08-05 11:53
Createa a GH to add new bulltet item to the test mentioned here https://github.com/Expensify/App/issues/44749#issuecomment-2237830751

**Closed by techievivek** 2024-08-05 11:53 UTC
Labels: Reviewing, Daily, Internal
