### ISSUE TITLE
[$500] IOS - Scan - Text in header is truncating instead of wrapping it in IOU detail page 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28851] opened 2023-10-04 18:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on global + button
2. Select Scan
3. Upload an image
4. Once you are taken to the chat with the image in the "scanning" state, click on the preview to go to the details

## Expected Result:
Text in header should be wrapped it in IOU detail page 

## Actual Result:
Text in header is truncating instead of wrapping it in IOU detail page 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.77.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (3)](https://github.com/Expensify/App/assets/93399543/697b4561-a2e2-4ac5-bd4e-93bb87cf2b63)

![IMG_6661 (1)](https://github.com/Expensify/App/assets/93399543/9145db05-5f13-46cc-99b8-aceede1c63c2)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696347198412019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01688dc6d171151612</li>
        <li>Upwork Job ID: 1709643274049388544</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by ayazalavi** [comment] 2023-10-05 12:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Header text is truncating due to shortage of available space

### What is the root cause of that problem?
Root cause is that although we are setting number of lines to 1 but we are not telling text component to render it fully.

### What changes do you think we should make in order to solve the problem?
use [adjustsfontsizetofit](https://reactnative.dev/docs/text#adjustsfontsizetofit) prop to ensure entire text is getting shown fully instead of getting truncating

### What alternative solutions did you explore? (Optional)
N/a

**Comment by jjcoffee** [comment] 2023-10-06 15:31
Clarifying [on Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1696606231737319?thread_ts=1696347198.412019&cid=C049HHMV9SM) what the expected result is here as it looks correct to me.

**Comment by jjcoffee** [comment] 2023-10-10 15:54
@neonbhai If you have a feature request please raise it on Slack, per the [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by JmillsExpensify** [comment] 2023-10-17 20:53
Closing per the comments.

**Closed by JmillsExpensify** 2023-10-17 20:53 UTC
Labels: External, Daily, Help Wanted, Bug
