### ISSUE TITLE
[HOLD for payment 2022-10-20] [$1000] mWeb - Payments- Keyboard is dismissed after tap on eye icon

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10555] opened 2022-08-24 22:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reproduce when executing PR** https://github.com/Expensify/App/pull/10546

## Action Performed:
Precondition: VBA added into testing account
1. Go to staging.new.expensify.com
2. Log in with expensifail account
3. Go to Setting - Payments
4. Select Alberta account
5. Tap Set as Default Payment
6. Type your password
7. Tap on eye icon

## Expected Result:
Keyboard is not dismissed after tap on eye icon,

## Actual Result:
Keyboard is dismissed after tap on eye icon

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.89.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186531922-0b63483e-3387-4fc0-b7b2-018fd9bd6bc9.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhairyasenjaliya** [comment] 2022-08-25 06:14
This issue seems to be globally not only limited to payments



https://user-images.githubusercontent.com/47522946/186588804-471a72b9-f53f-44e2-9a25-81c5148b9e27.mp4

**Comment by Christinadobrzyn** [comment] 2022-08-29 15:13
Created job in Upwork!

Internal posting - https://www.upwork.com/ab/applicants/1564269776150454272/job-details
External posting - https://www.upwork.com/jobs/~01861e855539ef8eb4

**Comment by mazhartejani** [comment] 2022-08-29 20:30
The issue is that the password input field is losing focus when clicking on the eye button.
the issue can be resolved if you make the password input field focused whenever the eye button is clicked.

Mazhar Tejani
From Upwork

**Comment by varshamb** [comment] 2022-08-30 05:53
### Proposal

We should add `keyboardShouldPersistTaps="always"` for all `TextInput` in `PasswordPage`.

**Comment by metehanozyurt** [comment] 2022-08-30 08:29
## Proposal
### Cause
When we click eye icon text input lost focus on mWeb.

### Solution
We can make it focus again when calling the `togglePasswordVisibility` function.

https://github.com/Expensify/App/blob/ca481ed2a28d8b27e116dbcdb55db166b5134825/src/components/TextInput/BaseTextInput.js#L185-L188

need to change like this

```js
togglePasswordVisibility() {
        this.setState(prevState => ({passwordHidden: !prevState.passwordHidden}));
        this.input.focus();
    }
```

video:

https://user-images.githubusercontent.com/6093207/187388712-338bcc3c-5351-4bf5-bda5-00c92d60848c.mp4

**Comment by aimane-chnaif** [comment] 2022-08-30 09:59
### **Proposal**
This is normal behavior in mWeb. In Web, focused input is blurred when any other views are clicked. Therefore keyboard is dismissed in mobile web. There's not such a view property to keep input focused whenever other buttons are pressed.

Also in react-native-web, even though TextInput is inside ScrollView with keyboardShouldPersistTaps = 'handled' or 'always' set, this doesn't work. This props is only for native mobile apps.

**Solution**
We can focus input manually whenever eye icon is clicked.

Important thing to consider:
We should keep current keyboard shown/hidden status when eye icon clicked.
So if input blurred and keyboard dismissed, keep keyboard hidden even after click eye icon.
if input focused and keyboard shown, keep keyboard shown even after click eye icon.
**Why?**
This Payments page will not affect user since it has only 1 input view.
But let's say when user try to login or change password (these pages have multiple input views) and dismiss keyboard intentionally. Tapping eye icon on password field will show keyboard again though user not expected that.
The status should not change between before tap eye icon and after tap eye icon. Just difference should be only password visibility.

NOTE: At the time of **Pressable** `onPress` event, input is already blurred so we cannot check with `this.state.isFocused` (always `false`) on `onPress` callback. But luckily, **Pressable** `onPressIn` event is triggered before input is blurred.
So to implement this, we need to have a new flag to check if input is focused before click button.

Updated Code:
https://github.com/Expensify/App/blob/eafa4940304f8b3682aae4f193ac11e92c845be0/src/components/TextInput/BaseTextInput.js#L284-L288
<img width="671" alt="Pressable" src="https://user-images.githubusercontent.com/96077027/187407184-7f64b8a0-b524-44ab-8bb2-04eab49594cc.png">


https://github.com/Expensify/App/blob/eafa4940304f8b3682aae4f193ac11e92c845be0/src/components/TextInput/BaseTextInput.js#L185-L187
<img width="649" alt="togglePasswordVisibility" src="https://user-images.githubusercontent.com/96077027/187407242-7c4a346e-2dee-4697-b1dc-3d4a3d95bcc6.png">

**Comment by dhairyasenjaliya** [comment] 2022-08-31 11:23
**Proposal**

- We just need to add `onMouseDown={e => e.preventDefault()}` inside below `<Pressable>` since we don't want to remove focus and just toggle password 

https://github.com/Expensify/App/blob/eafa4940304f8b3682aae4f193ac11e92c845be0/src/components/TextInput/BaseTextInput.js#L284-L288 

**Result**

**M-Safari**

https://user-images.githubusercontent.com/47522946/187666349-bb31b61e-96fa-4466-abaa-90a2a2d8993f.mp4

**M-Chrome**

https://user-images.githubusercontent.com/47522946/187666616-35bd34c7-7a0d-4fef-b25e-c392d8638227.mp4

**Note: Here we are adding preventDefault() which will never blur from text input but weirdly when we toggle values by default it places the cursor at an initial value to 0, this might be default behavior from chrome or a react bug that I found here https://github.com/facebook/react/issues/18530**

**Comment by deetergp** [comment] 2022-09-05 11:46
Not overdue, awaiting updated proposals.

**Comment by deetergp** [comment] 2022-09-07 13:41
Since we're awaiting updated proposals, I am going to set this back to weekly.

**Comment by Christinadobrzyn** [comment] 2022-09-08 12:17
Still waiting on proposals - doubled price $500

**Comment by dhairyasenjaliya** [comment] 2022-09-08 15:44
@parasharrajat I did try to investigate this one I found that this one is a bug from reacts (chrome) that exists on the framework itself let me give one good example for instance Netflix is built using react whereby you can check https://www.netflix.com/in/login just try to add password toggle it will jump at the begging (Same as our code base) but if you try the same site in safari no issue, TBH I don't know whether is actual behavior or bug 

- weirdly even manually controlling the cart (cursor) is not available in chrome but other platform works well


https://user-images.githubusercontent.com/47522946/189166123-3ac2057e-919c-405f-a90c-b11079e4b4a8.mov



<img width="1439" alt="Screenshot 2022-09-08 at 9 06 11 PM" src="https://user-images.githubusercontent.com/47522946/189165406-6f9c2fe2-db76-4190-82ed-d8c1db2080ec.png">

**Comment by aimane-chnaif** [comment] 2022-09-08 16:55
### **Updated Proposal**
This is nature of web, so when tap other elements, focused input is blurred as default.
To prevent this, we need to prevent default event on `onMouseDown` by calling `e.preventDefault()`.
And this doesn't affect tap effect since it is handled in `onPress` (this is existing props of react-native-web's Pressable component).

**Solution:**
https://github.com/Expensify/App/blob/d7a7334abbdd699510bc98f566c5f02b12ec46b8/src/components/TextInput/BaseTextInput.js#L291-L299
- We need to use Pressable instead of Checkbox
- Add this to Pressable: `onMouseDown={e => e.preventDefault}`
Final eye icon component will look like this:
```
                                        <Pressable
                                            style={styles.secureInputShowPasswordButton}
                                            onMouseDown={e => e.preventDefault()}
                                            onPress={this.togglePasswordVisibility}
                                        >
                                            <Icon
                                                src={this.state.passwordHidden ? Expensicons.Eye : Expensicons.EyeDisabled}
                                                fill={themeColors.icon}
                                            />
                                        </Pressable>
```
This solves this GH issue basically.
But like in previous comments, `cursor is lost` issue still exists in Google Chrome (works fine on Safari)
To solve this, we need to introduce 2 new flags. I will call it `this.isPending`, `this.selection`

**Why `this.isPending` flag needed?**
We know it's better to call `this.input.setSelectionRange()` directly whenever tap eye icon.
But the issue is that `reset cursor` event is fired only after input type change, which is already after tap eye icon callback.
So it's useless to call `this.input.setSelectionRange()` on tap eye icon callback.
So the solution is to call `this.input.setSelectionRange()` after cursor reset (`onSelectionChange` callback).
But we need to know if `onSelectionChange` callback is automatic from input type change, not manually by user.
That's why `this.isPending` flag needed.

Updated code:
https://github.com/Expensify/App/blob/d7a7334abbdd699510bc98f566c5f02b12ec46b8/src/components/TextInput/BaseTextInput.js#L188-L190
```
    togglePasswordVisibility() {
        this.setState(prevState => ({passwordHidden: !prevState.passwordHidden}));
        if (this.state.isFocused && this.selection && (this.selection.start || this.selection.end)) {
            this.isPending = true;
        }
    }
```
https://github.com/Expensify/App/blob/d7a7334abbdd699510bc98f566c5f02b12ec46b8/src/components/TextInput/BaseTextInput.js#L259
Customize `onSelectionChange` callback on `RNTextInput` component
```
                                        onSelectionChange={(e) => {
                                            if (this.isPending) {
                                                if (this.input.setSelectionRange && this.selection) {
                                                    this.input.setSelectionRange(this.selection.start, this.selection.end);
                                                }
                                                this.isPending = false;
                                            }
                                            this.selection = e.nativeEvent.selection;
                                            if (this.props.onSelectionChange) { this.props.onSelectionChange(e); }
                                        }}
```
In case `onSelectionChange` is not called when input type changes, to prevent `this.isPending=true` forever:
https://github.com/Expensify/App/blob/d7a7334abbdd699510bc98f566c5f02b12ec46b8/src/components/TextInput/BaseTextInput.js#L117-L121
```
    onFocus(event) {
        if (this.props.onFocus) { this.props.onFocus(event); }
        this.setState({isFocused: true});
        this.activateLabel();
        this.isPending = false;
    }
```
https://github.com/Expensify/App/blob/d7a7334abbdd699510bc98f566c5f02b12ec46b8/src/components/TextInput/BaseTextInput.js#L123-L127
```
    onBlur(event) {
        if (this.props.onBlur) { this.props.onBlur(event); }
        this.setState({isFocused: false});
        this.deactivateLabel();
        this.isPending = false;
    }
```

before fix:
https://user-images.githubusercontent.com/96077027/189180996-ab3303c3-9ee1-42ba-91f0-1175c5bb4751.mov

after fix:

https://user-images.githubusercontent.com/96077027/189181052-452333f1-55aa-4619-84c0-8eba4341ed59.mov

**Comment by deetergp** [comment] 2022-09-22 00:39
Let's deal with the behaviors called out in this GH and not worry about the cursor position. If we decide later that cursor position is an issue, we can deal with that in a different GH.

**Comment by dhairyasenjaliya** [comment] 2022-09-22 17:24
@parasharrajat that bluehighlight will not come as I have manually select text to remove

**Comment by dhairyasenjaliya** [comment] 2022-09-22 18:13
ah got your point @parasharrajat, but that is an existing global issue across the app for m-Safari, quick question do we really need spellCheck for passwords inputs I mean we can set the password to any Alpha-numeric or any pattern that doesn't actually require spellCheck functionality

**Comment by dhairyasenjaliya** [comment] 2022-09-23 04:58
- For removing autoCorrect We should check if textbox is secureTextEntry or not if yes then disable autoCorrect only for secureTextEntry 

- Need to add conditions like below in https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L196

- Test this condition with onMouseDown={e => e.preventDefault()} <Checkbox>   

<img width="1386" alt="Screenshot 2022-09-23 at 10 25 20 AM" src="https://user-images.githubusercontent.com/47522946/191894490-b2c50cee-9bd4-4799-b86d-ea3518681ff0.png">

<img width="1388" alt="Screenshot 2022-09-23 at 10 25 42 AM" src="https://user-images.githubusercontent.com/47522946/191894492-8725bc5b-b723-49d7-b0c8-f08fe3a376ac.png">


**Result**

https://user-images.githubusercontent.com/47522946/191894210-42a0be78-96f3-4367-b5ce-bd88a45e5476.MP4

cc: @parasharrajat

**Comment by Christinadobrzyn** [comment] 2022-09-23 10:06
doubled price to $1000

**Comment by deetergp** [comment] 2022-10-03 21:50
It looks like the thread got lost here, but it sounds like @aimane-chnaif's proposal is the one we should go with. Thoughts, @parasharrajat?

**Comment by dhairyasenjaliya** [comment] 2022-10-04 01:46
@deetergp I think you are referring to my proposal along with removing autoCorrect from secureText inputs to avoid blue opacity and also there is no purpose for adding autoCorrect into password fileds

Cc @parasharrajat can you check if this works for removing autoCorrect from secureText inputs https://github.com/Expensify/App/issues/10555#issuecomment-1255802598

**Comment by parasharrajat** [comment] 2022-10-04 09:07
Yes, I am checking this.

**Comment by parasharrajat** [comment] 2022-10-04 12:23
Ok, tested it. @dhairyasenjaliya 's [proposal](https://github.com/Expensify/App/issues/10555#issuecomment-1255802598) looks good if we don't want the autoCorrect for password inputs which I think is fine.

Based on the slack conclusion, we don't have to worry about the cursor position so we don't need a complex solution. 

cc: @deetergp 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by deetergp** [comment] 2022-10-04 16:39
Perfect @parasharrajat, thanks! Okay @Christinadobrzyn, let's hire @dhairyasenjaliya to implement their proposed solution.

**Comment by Christinadobrzyn** [comment] 2022-10-05 05:42
Hired @dhairyasenjaliya for the fix and @parasharrajat as C+!

**Comment by dhairyasenjaliya** [comment] 2022-10-05 06:22
@parasharrajat PR is ready for review/test :)

**Comment by mvtglobally** [comment] 2022-10-18 11:15
Issue not reproducible during KI retests. (First week)

**Comment by Christinadobrzyn** [comment] 2022-10-21 07:17
7 day of product deployment done - paying this out and closing this job. 

$1000 @dhairyasenjaliya for the fix
$1000 @parasharrajat as C+

Closed job in Upwork and closing this GH

**Closed by Christinadobrzyn** 2022-10-21 07:17 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Awaiting Payment, Bug
