### ISSUE TITLE
[HOLD for payment 2023-09-27] [$1000] mWeb - 2FA - The screen jumps when deleting invalid code

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23575] opened 2023-07-25 18:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to http://staging.new.expensify.com/
2. Login into the account
3. Tap the profile avatar
4. Select Security > Two-factor authentication
5. Copy or download recovery codes
6. Tap the "Next" button
7. Enter an invalid code
8. Delete the code

## Expected Result:
The code input stays on focus and there are no unusual jumps

## Actual Result:
The screen jumps when removing digits

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e0ee3b91-6a9c-4e7d-8bc4-c891c4947366

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127543ad8babfd9a3</li>
        <li>Upwork Job ID: 1684832010423627776</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-07-28 07:43
External

**Comment by Pcholka-solution** [comment] 2023-07-28 09:13
1. Analyze the existing codebase and identify the root cause of the screen jumping when deleting invalid code.
2. Implement a fix by modifying the relevant code, ensuring that the screen remains stable during code deletion.
3. Test the solution thoroughly on all platforms to ensure its effectiveness and compatibility.
4. Create a pull request in the Expensify/App GitHub repository with the proposed changes.
5. Provide detailed documentation and screenshots of the changes made, along with confirmation of testing on all platforms.

**Comment by Pcholka-solution** [comment] 2023-07-28 09:15
![image](https://github.com/Expensify/App/assets/140801640/a77bd065-497c-4744-9d60-e034b470c355)
https://www.upwork.com/freelancers/bohdanhmil

**Comment by ishpaul777** [comment] 2023-07-31 07:51
this looks like a [chrome bug](https://github.com/chakra-ui/chakra-ui/issues/6445), we are disabling chrome autofill on [MagicInput](https://github.com/Expensify/App/blob/main/src/components/MagicCodeInput.js#L300C32-L300C32) on every index except 0. this password manager bar is supposed be gone.

When the focus shifts from one to other the bar rerenders. causing the screen jump.
  
Not reproducable on Chrome Emualtor but reproducable on physical device.

https://github.com/Expensify/App/assets/104348397/55e4a7a1-d075-43c6-bf5b-759cd75b68d2

**Comment by ydhandha** [comment] 2023-07-31 19:23
**Objective:** Thoroughly examine a specific element and its parent container in the DOM to assess event bindings and check if scrollTop is being appended to the main parent/body element.

**Events and Logic:** Meticulously assess relevant events such as "onchange" or "keydown/keyup" and evaluate associated chained logic or functions that contribute to navigating to the previous input. Also, investigate the process of removing specific values from the current input and focusing on the preceding input element.

**Debugging:** If needed and if feasible, deploy a debugger within the relevant function to inspect intermediate steps / logic executed during the navigation to the previous input, gaining valuable insights into the sequence of operations.

**Preventive Measures:** Consider using preventive measures like .preventDefault() or .stopPropagation() to avoid default execution of browser events before executing logic for moving to the previous input or any other actions.

**Resolution:** By following these above steps diligently, it is highly probable to identify the root cause of the issue and subsequently implement the required code changes to resolve it effectively.

**Comment by ydhandha** [comment] 2023-07-31 19:32
Contributor details
Your Expensify account email: yashdhandha@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01725b8c71ec683d69

**Comment by ydhandha** [comment] 2023-08-02 10:30
## Proposal
[Updated](https://github.com/Expensify/App/issues/23575#issuecomment-1658999863)

**Comment by bfitzexpensify** [comment] 2023-08-03 16:47
Few proposals for you to review when you get a chance @eVoloshchak - thank you!

**Comment by bfitzexpensify** [comment] 2023-08-07 15:36
Friendly reminder to review these proposals when you get a chance @eVoloshchak

**Comment by bfitzexpensify** [comment] 2023-08-10 15:02
Another bump to review when you get a chance @eVoloshchak - thank you!

**Comment by eVoloshchak** [comment] 2023-08-10 18:01
It's not only when deleting a code, it also happens when you simply enter a code

https://github.com/Expensify/App/assets/9059945/6ba31f02-94ae-4cf5-aba0-254442a193a7

**Comment by eVoloshchak** [comment] 2023-08-10 18:08
> we are disabling chrome autofill on [MagicInput](https://github.com/Expensify/App/blob/main/src/components/MagicCodeInput.js#L300C32-L300C32) on every index except 0. this password manager bar is supposed be gone.

@ishpaul777, I can still reproduce this no matter if autofill is enabled or disabled, but it seems the behavior might have changed
Were you able to resolve this?

**Comment by ishpaul777** [comment] 2023-08-10 18:15
unfortunately no, but i identified the root cause here is a chrome default behaviour with the password bar rerendering everytime a input get focussed. 
when a input blurred it dissapear the bar and quickly when the other input gains focus it rerender bar causing the jump effect. There is no way we can disable the bar programmatically

**Comment by eVoloshchak** [comment] 2023-08-10 18:24
@Pcholka-solution, @ydhandha, welcome and thank you for looking at this!
A proposal should explain what the actual root cause of the issue is and what should we do in order to fix it. 
You can take a look at any of the proposals in https://github.com/Expensify/App/issues/22413 (or any other issue)  as well as [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

**Comment by ydhandha** [comment] 2023-08-10 18:49
@eVoloshchak, I have reviewed and acknowledged the contents of [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job). I am on both the Slack Channels and have shared my contributor details as well

Kindly check my [updated comment](https://github.com/Expensify/App/issues/23575#issuecomment-1658999863) from last week (if not already). If needed, I can provide the solution and code here, along with explanations for necessary changes in the MagicInput file. Your assistance is highly appreciated. Thank you.

**Comment by eVoloshchak** [comment] 2023-08-10 19:03
> f needed, I can provide the solution and code here, along with explanations for necessary changes in the MagicCodeInput file

Yeah, that would be awesome @ydhandha

**Comment by ShogunFire** [comment] 2023-08-11 19:38
I think @ishpaul777 is right but then why we don't have this bar on the report composer, what field is causing this bar ?

**Comment by ydhandha** [comment] 2023-08-11 21:47
> > f needed, I can provide the solution and code here, along with explanations for necessary changes in the MagicCodeInput file
> 
> Yeah, that would be awesome @ydhandha

@eVoloshchak So basically, Android Chrome Browser would show the password manager as default for any input type except for input type="search". Since inputMode="numeric" is already in place it is showing the numeric keyboard but if we check the root  attributes of the input, "inputmode" and "inputtype" both are different.  

**InputMode** provides hints to the browser about the virtual keyboard layout and behavior
**InputType** directly impacts the appearance & behavior of the input field and autofill behavior

The default type for input is text and the same is in here currently. Now, coming back to our original behaviour that we want - Password manager on the 0 index should be seen but not on the rest and so, we can pass type search on the rest of the inputs except at 0 and since search doesn't have any autofill behaviour, we can use type search on other input. 

I have debugged the actual phone and managed to change the above directly through DOM manipulation and I am attaching original behaviour that we have currently and after changes behaviour

Furthermore, since rest of the logic and event like onChangeText, onKeyPress, onFocus is in place as per our requirements, I believe adding this, wouldn't conflict the behaviour and overall requirement considering this is a workaround to prevent the suggestion panel to show up.

https://github.com/Expensify/App/assets/69626304/59c5ae90-850d-44e9-9262-be3611e1e054

https://github.com/Expensify/App/assets/69626304/fbbb8da3-2180-452a-b990-cd448643dfd7

I hope this solution is suitable to overcome the issue and I can provide code where the changes are need to be done. Also if you have anything else on this please let me know

**Comment by ishpaul777** [comment] 2023-08-12 11:33
inputType is not a prop in [TextInput](https://reactnative.dev/docs/textinput#inputmode) and i dont find TextInput provides a way to set type attribute directly. if we are think that we can compromise on semantics and accessibility for this case. 
we have to set the type attribute manually like this and also if we are going this way we should set the type="search" for all the input including the first.
```jsx
<TextInput
             ref={(ref) => {
             ref.setAttribute('type', 'search')
                     inputRefs.current[index] = ref
               }}
               // ...
```
i would add a formal proposal if  we move forward with this. ofc, this would work

**Comment by ydhandha** [comment] 2023-08-12 11:50
Yeah. I am aware inputtype is not a prop in TextInput that we are using but, a default attribute of input tag including inputmode and the same I have mentioned. Also if you set type search for all the inputs, suggestion panel wouldn't appear for first index as well assuming we want to show it in the first input but not for the rest. Talking about the semantic and accessibility I don't forsee any issue since we are not changing any input behaviour or any events but, simply by explicitly setting attribute type search in this case and the rest will be the same as explained above.

**Comment by ishpaul777** [comment] 2023-08-12 12:00
considering setting type="search" is the only way here. i agree with you here.

**Comment by ydhandha** [comment] 2023-08-12 12:40
I have suggested to keep all the inputs type search except for 0 index to show the default password manager and clipboard is something  would be visible for any input type not only for search or text. Furthermore, since I am very new to expensify, I thought not to change overall expectations / behaviour and still if we want to show password manager on 0 index than we should keep as it is and rest should be type search otherwise if keeping all the input type search and don't want to show password manager at all, then correct we should make it type search for all the inputs but surely, I'll go on with what is expected rather than I assume and advice to change it all. I hope this clears your concern @ishpaul777 🙂

**Comment by ydhandha** [comment] 2023-08-12 15:11
@eVoloshchak, I hope you will find each of my comment for the solution useful with the explanation and if you could confirm I shall proceed with setting up the project on my local since in initial stage as per the guideline for the proposal, it was not mandatory to provide the code but the technical explanation or simply an explanation how it is reproduced and how could we resolce the same. 
But I shall only proceed after you confirm, and I would implement the solution and shall regressively check the change on all the supported platforms(given for the expensify) with the expected behaviour 🙂

**Comment by bfitzexpensify** [comment] 2023-08-16 09:31
@eVoloshchak thoughts on the latest comments here?

**Comment by bfitzexpensify** [comment] 2023-08-22 12:24
@eVoloshchak are any of the proposals here good to proceed with?

**Comment by eVoloshchak** [comment] 2023-08-22 17:42
@ydhandha, thank you for such a thorough investigation!

> Currently, I have done the DOM manipulation directly instead of doing it in file since I haven't setup on my local but if you confirm I shall proceed further to setup on my local and can make the changes on MagicCodeInput file

I agree this is the approach we should take (yet it's still a strange behavior, shouldn't we report this in `react-native` repo?)
Could you post a proposal?

**Comment by bfitzexpensify** [comment] 2023-08-23 11:31
Heading ooo for a week. @Christinadobrzyn, this one has been lagging for a little while. I think if we don't hear back from @ydhandha in the next day or two, we should assign an internal engineer to take over and get this fixed up.

**Comment by ydhandha** [comment] 2023-08-23 12:39
> I agree this is the approach we should take (yet it's still a strange behavior, shouldn't we report this in `react-native` repo?) Could you post a proposal?

@eVoloshchak - This is not an issue of react-native framework but a certain behavior of input as I have explained in the above comments. 

@bfitzexpensify,
Since I was waiting for an input from @eVoloshchak, I'll post the proper proposal with the solution by today or by tomorrow morning and whether it can be fitted within the available props in the TextInput or to explicity set the attribute for input as, the  solution(not in react-native context) is already defined in the previous comments of mine and the same needs to be implemented in this project.

**Comment by ydhandha** [comment] 2023-08-23 18:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem arises when a user deletes or enters a code on an Android device using the Chrome browser. Upon each deletion, the screen scrolls up momentarily and then returns to the correct position. This behavior should not occur and the screen should remain fixed at the same position while the user performs this action. 

### What is the root cause of that problem?
The root cause of this problem is with the input and the default behavior of the input which shows the password manager bar when a user is logged in with an Account where their saved passwords can be used and due to that it is causing the screen to move up for a moment and then focus gets back to the original input element which only conflicts on Android Chrome Browser .

### What changes do you think we should make in order to solve the problem?
If we set the input type to search this can be resolved since only type search wouldn't show the password manager and we would still be able to render the same keyboard and no functionality will conflict after setting the same.

Since there is no props available within the TextInput Component where we can set the type to search, we can achieve the same using setAttribute method to the ref element(_as you may see below_) which prevents the password manager bar to show up and below is the alternative solution for which our issue can be resolved.

https://github.com/Expensify/App/blob/15d15117a6c6f7e999803278e2491a2af7f7fd81/src/components/MagicCodeInput.js#L280
```diff
- ref={(ref) => (inputRefs.current[index] = ref)}
+ ref={(ref) => {
+     inputRefs.current[index] = ref;
+ 
+     // Set the type to search to avoid the password manager from showing up.
+     if (ref && ref.setAttribute) {
+         ref.setAttribute("type", "search");
+     }
+ }}
```

**For precise Web/Desktop targeting, I would suggest a solution as following:**

- Create a "setElementAttribute" folder in "libs." 
- Create a "index.js" wherein create a function for an ex: **setElementAttribute(elm, attr, attrValue)** which sets an attribute to respective element(elm) which has been passed using this function and the rest of the logic for null check and setAttribute to be placed
- Maintain the same function as an empty like this **setElementAttribute = () => { }** in "index.native.js" to retain native app behavior. 
- The function defined above to be used whilst importing in MagicInputCode file 
```diff
- ref={(ref) => (inputRefs.current[index] = ref)}
+ ref={(ref) => {
+     inputRefs.current[index] = ref;
+ 
+    setElementAttribute(ref,"type","search");
+     // Which sets it to type search for Web/Desktop but for native app it will be void 
+ }}
```

This above strategy certainly targets to solve the issue on platform-specific rather than changing it globally as well as this created function can be imported in other cases where, we may want to use the same to pass some custom attribute.

**Comment by ishpaul777** [comment] 2023-08-23 19:36
Hopefully if I am not too late I have another solution I want to propose.

# Proposal

## Please re-state the problem that we are trying to solve in this issue
mWeb - 2FA - The screen jumps when deleting invalid code

## What is the root cause of that problem?
https://github.com/Expensify/App/issues/23575#issuecomment-1657853540

## What changes do you think we should make in order to solve the problem?
adding prop `multiline` to will change the input to textarea and prevents the password manager bar to render as it is specifc to input only.

**Comment by Christinadobrzyn** [comment] 2023-08-24 20:23
I think we're still reviewing propsoals? @eVoloshchak can you confirm where we are with this?

**Comment by Christinadobrzyn** [comment] 2023-08-28 21:28
@eVoloshchak can you please leave an update on the proposal review? Thanks!

**Comment by eVoloshchak** [comment] 2023-08-30 18:47
Summary:

This is a [known bug in Mobile Chrome](https://support.google.com/chrome/thread/167858494/password-bar-above-keyboard-on-android-phone-always-there?hl=en). It was reported a year ago, there seems to be no activity or plans to resolve it. 

Since this is pretty severe and will not be fixed in Chrome soon, I think we should apply a workaround.

- @ydhandha's [proposal](https://github.com/Expensify/App/issues/23575#issuecomment-1690485081) is to set textInput's type the only type that isn't affected: `type="search"`. The downside is, this will negatively affect accessibility
- @ishpaul777's [proposal](https://github.com/Expensify/App/issues/23575#issuecomment-1690530440) is passing multiline=true to the textInput, which prevents the password manager bar from rendering

I think we need to fix this for all inputs throughout the app. The bug is present for all numeric inputs, not just the magic input (not the screen jumping, but the password manager bar is present while it shouldn't)

**Comment by ishpaul777** [comment] 2023-08-30 19:55
In my opinion, i dont think applying workaround to all of numeric inputs (that does not efffect UX by rendering password bar) is necessary considering the accessibility tradeoffs, as both are merely workaround and root cause is unfixable. I would recommend selectively applying the workaround to only input that's causing bad UX like Magiccodeinputs on 2fa screen.

**Comment by ishpaul777** [comment] 2023-08-31 07:27
Input or textarea both are built for taking text from user, we by design accepts only one number so user won't be able to enter multiline text or any other text other than a single digit. As you have said text-area are resizable but resizing to text input is disabled by default in the app, Screen readers might associate `type=search` to a search input which I believe is a relatively bigger tradeoff for accessibility than replacing input from textarea.

**Comment by ydhandha** [comment] 2023-08-31 08:24
Yes, that's what I am trying to highlight in here. Since we have everything in place that we require, we can simply change the type to search but since, you have provided to use multiline which converts input to textarea, I have checked the same on my local using multiline prop whilst using the screen reader(NVDA) and below is the output as mentioned:

**Input (using: type="search"):**

- Screen reader reads --- 'Edit Blank" 
- No issue on accessing previous / next / tapped or clicked input and screen reader will read the text as well as if it is blank will read the same as above
- Even for input type text or any other type it still reads the same

**Textarea (using: multiline prop)**

- Screen reader reads --- "Edit Multiline Blank" 
- Because we are using textarea, screen reader reads the above
- No issue on accessing previous / next / tapped or clicked input and screen reader will read the text as well as if it is blank will read the same as above

Furthermore you may check the above using screen readers for checking both the scenario as well as for the accessibility and I would suggest if required, not only on our react-app but you may check the screen readers anywhere(_even a raw file which consists of simply textarea and input with any type_) to compare how screen reader will read for a user for a textarea as well as for an input.

To conclude - Even if we use aria-label attribute which is, specifically, for screen reading, in the end(as a suffix), it would still reads the "Edit Blank" for an input and "Edit Multiline Blank" for textarea 

Example: Consider aria-label="Add OTP here" and we are using textarea and input

**Screen reader Output for Input:**  Add OTP here Edit Blank
**Screen reader Output for Textarea:**  Add OTP here Edit Multiline Blank

I hope I have cover everything in here to explain how it will work in both the scenario.

**Comment by eVoloshchak** [comment] 2023-09-03 20:20
Re-posting summary from my comment above:

>This is a [known bug in Mobile Chrome](https://support.google.com/chrome/thread/167858494/password-bar-above-keyboard-on-android-phone-always-there?hl=en). It was reported a year ago, there seems to be no activity or plans to resolve it.
Since this is pretty severe and will not be fixed in Chrome soon, I think we should apply a workaround.

Testing this with a screen reader, having it say "Edit text. Search field" is better than "Text Area", so @ydhandha's proposal is better from an accessibility standpoint (but it depends on the specific screen reader I'd imagine)

I think we should proceed with @ydhandha's [proposal](https://github.com/Expensify/App/issues/23575#issuecomment-1690485081). 
Changing textinput to a textarea as suggested by @ishpaul777  is a much bigger change and it could potentially introduce some regressions, since there are differences in how different devices/browsers handle textinput and textarea.

🎀👀🎀 C+ reviewed!

**Comment by hayata-suenaga** [comment] 2023-09-05 04:01
I'm focusing on Wave 5 right now, but I'll come back to this issue to review proposals later this week 🙇

**Comment by hayata-suenaga** [comment] 2023-09-07 21:30
@eVoloshchak 

> This above strategy certainly targets to solve the issue on platform-specific rather than changing it globally as well as this created function can be imported in other cases where, we may want to use the same to pass some custom attribute.

I like only applying the text input type change to web, but creating a platform specific files for this seems a little bit overwork 🤔 

Anyway, I think setting attribute to native text input through `useRef` won't affect iOS and Android native text input components... maybe?

Anyway, let's go with your proposal 🎉

**Comment by Christinadobrzyn** [comment] 2023-09-08 03:13
Hey @ydhandha let us know when you have a PR for review!

**Comment by ydhandha** [comment] 2023-09-08 03:48
Hey @hayata-suenaga / @Christinadobrzyn ,

Can you help me with the Upwork Job link? I am seeing job is not available and couldn't apply.

**Comment by eVoloshchak** [comment] 2023-09-10 14:22
@ydhandha, it's normal, the upwork job has just expired. You can go ahead with raising the PR, usually, the whole upwork process is finalized before payment is due, long after the PR was merged
We treat GitHub as the only source of truth, SO as long as you're assigned to the issue on GitHub - you're hired and can create the PR

**Comment by ydhandha** [comment] 2023-09-11 07:41
@eVoloshchak, Thank you for providing details. 

I'll create the PR max by tomorrow and will be ready for review by then.

**Comment by ydhandha** [comment] 2023-09-12 17:57
Hi @eVoloshchak , PR is ready please check at your end.

**Comment by Christinadobrzyn** [comment] 2023-09-26 20:08
Looks like no speed bonus is applied here. 

@eVoloshchak should we have a regression test for this?

**Comment by eVoloshchak** [comment] 2023-09-27 15:46
- The PR that introduced the bug has been identified. Link to the PR: N/A, this is a bug in Chrome mobile
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: it's a visual bug (screen glitching), don't think an additional discussion is needed
- Determine if we should create a regression test for this bug: I think we should, this is a bug in mobile Chrome, it's completely outside of our control, in theory it could come back at any point with a Chrome update

**Comment by eVoloshchak** [comment] 2023-09-27 15:49
**Regression Test Proposal**

(mobile Chrome only)
1. Open Settings > Security > Two-Factor Authentication
2. Copy Code and Press Next
3. Input the code and verify that the password manager bar is not showing above the keyboard whilst adding/removing the code
4. Input the code and verify there are no screen jumps/glitching whilst adding/removing the code

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment] 2023-09-28 00:38
Can I get a payment summary for this issue?

**Comment by bfitzexpensify** [comment] 2023-09-28 10:19
Sure: 

Contributor: @ydhandha $1000 to be paid via Upwork
C+: @eVoloshchak $1000 to be paid via manual request

**Comment by bfitzexpensify** [comment] 2023-09-28 10:20
@ydhandha please apply [here](https://www.upwork.com/jobs/~013b9960a030fc9144)

**Comment by ydhandha** [comment] 2023-09-28 11:40
@bfitzexpensify, I have applied to the job link given. Please check and let me know if anything else is needed from my end!

**Comment by ydhandha** [comment] 2023-09-28 15:15
Hi @Christinadobrzyn, I have accepted the offer.

**Comment by Christinadobrzyn** [comment] 2023-09-29 21:23
Regression test GH: https://github.com/Expensify/Expensify/issues/321481

Thanks @ydhandha! I paid you in Upwork based on this [payment summary](https://github.com/Expensify/App/issues/23575#issuecomment-1738873395)

I think this is good to close?

**Comment by ydhandha** [comment] 2023-09-30 05:16
Thanks @Christinadobrzyn. I am able to see the payment is done!

**Comment by JmillsExpensify** [comment] 2023-10-01 02:13
$1,000 payment for @eVoloshchak approved based on BZ summary.

**Closed** 2023-10-02 17:15 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
