### ISSUE TITLE
[$500] mWeb - LHN - IOU chat is not ordered under pinned messages in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31221] opened 2023-11-10 22:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
1. User A have pinned chats in LHN
Steps:
1. User B request money to User A
2. User A navigates LHN view

## Expected Result:
The chats should be ordered by Pinned > Outstanding IOUs > Drafts > Other chats

## Actual Result:
IOU chat is not ordered under pinned messages in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/34a34d60-2c96-4c8b-bc0f-b4578951c1a1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd8b81f64cb92084</li>
        <li>Upwork Job ID: 1723111524779155456</li>
        <li>Last Price Increase: 2023-11-10</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-11 07:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - LHN - IOU chat is not ordered under pinned messages in LHN

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/f0fb7a825a26967766e9f040e71a79d6006b027e/src/libs/SidebarUtils.ts#L172-L188

We combined the pinned report and GBRReport in the same section and the order of these report in this section is sort by the display name 
### What changes do you think we should make in order to solve the problem?
Let's see [this comment](https://github.com/Expensify/App/issues/29595#issuecomment-1767356522) 
> the green dot always makes the chat go to the top of the list under pinned chats (no matter how the green dot is being set, via mention, outstanding IOU or something else)

I think we should put the pinned report and GBRReport into 2 sections separately and display the pinned report before GBRReport

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-11-11 07:41
@puneetlath @greg-schroeder I see that you have context that relate to this issue in [here](https://github.com/Expensify/App/issues/29595) could you help to confirm the expected ?

**Comment by joekaufmanexpensify** [comment] 2023-11-13 14:39
Going to triage this today

**Comment by puneetlath** [comment] 2023-11-13 15:52
>The chats should be ordered by Pinned > Outstanding IOUs > Drafts > Other chats

Ah yes, we have changed the ordering so that pinned and GBR (green dot) are treated the same. So they will be mixed together. 

@lanitochka17 we might need to update our regression tests to account for this.

**Comment by isagoico** [comment] 2023-11-13 15:57
Thanks for the ping - Have updated the following TC to mention that pending IOUs (green dot) and pinned chats are at the same level for ordering: 
- [LHN - Ordering of Pinned, Outstanding IOUs, Draft and Chats](https://expensify.testrail.io/index.php?/cases/view/2644118)
![image](https://github.com/Expensify/App/assets/44479856/61d40d17-e84e-4842-bc77-aab22b6075bd)

**Comment by puneetlath** [comment] 2023-11-13 16:43
Thanks! Going to go ahead and close this.

**Closed by puneetlath** 2023-11-13 16:43 UTC
Labels: External, Daily, Help Wanted, Bug
