### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] [$250] Scan - Existing expense is removed when dismissing receipt error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#44246] opened 2024-06-24 11:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4662109
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a manual expense without receipt.
4. Go to transaction thread.
5. Tap Receipt thumbnail.
6. Add a corrupted PDF as the receipt (attached below).
7. Wait for the error to show up (re-add the corrupted file again if it disappears).
8. Dismiss the error.
**PDF file**
[LARGE PDF FILE corrupted.pdf](https://github.com/user-attachments/files/15954587/LARGE.PDF.FILE.corrupted.pdf)

## Expected Result:
The "existing" expense should not be deleted because user is only adding the receipt. It should be deleted only when user adds corrupted PDF when creating the expense. In this case, the expense is already created and dismissing the error should only removed the receipt and not the expense together.

## Actual Result:
The "existing" expense is removed after the receipt error is dismissed.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/6657f2ab-2bc2-4f41-ba6c-46082467442d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef5c51a3c66fea79</li>
        <li>Upwork Job ID: 1805206123739282150</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 102860123</li>
<li>bernhardoj | Contributor | 102860126</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by kbecciv** [comment] 2024-06-24 11:30
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-06-24 12:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The transaction/expense is removed when clearing the receipt error.

### What is the root cause of that problem?
This is coming from https://github.com/Expensify/App/pull/43346 where we clear the transaction when there is a receipt error without checking whether it's an existing transaction or not.
https://github.com/Expensify/App/blob/f84ee507c3485d6e130047db1e62dd16c452792b/src/components/ReportActionItem/MoneyRequestView.tsx#L403-L409

### What changes do you think we should make in order to solve the problem?

We should only clear the transaction if the pending action is 'add' which indicates that the transaction has failed to create, so we can safely clear it.
```
if (transaction.pendingAction === 'add' && Object.values(transaction?.errors ?? {})?.find((error) => ErrorUtils.isReceiptError(error))) {
    deleteTransaction(parentReport, parentReportAction);
}
```

**Comment by jjcoffee** [comment] 2024-06-24 12:40
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/44246#issuecomment-2186474156) LGTM! This is a regression from @nkdengineer's PR, so we might want to let them work on the fix. If they're not around we can proceed with @bernhardoj.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by cristipaval** [comment] 2024-06-24 18:37
I tagged @nkdengineer in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1719240106995839?thread_ts=1719228544.858769&cid=C01GTK53T8Q) but they might be overwhelmed with the regressions after the other big PR they deployed. I think we could go with @bernhardoj proposal. @aldo-expensify what do you think? (you might have more context as I see you approved [this PR](https://github.com/Expensify/App/pull/43346))

**Comment by aldo-expensify** [comment] 2024-06-24 18:50
Going with @bernhardoj proposal's proposal makes sense to me, what do you think @eh2077 ?

**Comment by bernhardoj** [comment] 2024-06-25 03:22
PR is ready

cc: @jjcoffee

**Comment by Christinadobrzyn** [comment] 2024-07-02 19:50
Payout date - 

- [X] Contributor: $250 @jjcoffee (Paid in Upwork - https://www.upwork.com/nx/wm/offer/102860123)
- [X] Contributor+: $250 @bernhardoj (Paid in Upwork - https://www.upwork.com/nx/wm/offer/102860126)

Do we need a regression?

**Comment by Christinadobrzyn** [comment] 2024-07-03 19:24
Moving to weekly since we're just waiting on a regression test (and it's a public holiday in the US tomorrow).

**Comment by jjcoffee** [comment] 2024-07-04 09:39
**Regression Test Proposal**

1. Submit a manual expense without receipt.
2. Go to transaction thread.
3. Tap Receipt thumbnail.
4. Add a corrupted PDF as the receipt, e.g. [LARGE PDF FILE corrupted.pdf](https://github.com/user-attachments/files/15954587/LARGE.PDF.FILE.corrupted.pdf)
5. Wait for the error to show up (re-add the corrupted file again if it disappears).
6. Dismiss the error.
7. Verify the error is dismissed and that the transaction isn't deleted.

Do we agree 👍 or 👎

**Comment by Christinadobrzyn** [comment] 2024-07-08 23:26
Payouts due in a few days

- [ ] Contributor: $250 @bernhardoj (offer in Upwork - https://www.upwork.com/nx/wm/offer/102860126)
- [ ] Contributor+: $250 @jjcoffee (offer in Upwork - https://www.upwork.com/nx/wm/offer/102860123)

**Comment by bernhardoj** [comment] 2024-07-09 03:20
I will request the payment through ND when the payout time is due.

**Comment by jjcoffee** [comment] 2024-07-10 07:48
@Christinadobrzyn Isn't this one already paid, per [this comment](https://github.com/Expensify/App/issues/44246#issuecomment-2204261689)? :smile:

**Comment by bernhardoj** [comment] 2024-07-10 07:54
Oh, @jjcoffee right. Looks like the automation messed up adding hold for payment for the 2nd time 😄

**Comment by Christinadobrzyn** [comment] 2024-07-16 23:15
oh gosh! You're right @jjcoffee! This is already paid through Upwork - https://github.com/Expensify/App/issues/44246#issuecomment-2204261689

Do we need a regression test for this?

**Closed** 2024-07-16 23:17 UTC
Labels: External, Engineering, Weekly, Awaiting Payment
