### ISSUE TITLE
[Backwards compatibility] IOU preview not been updated when one expense was moved to the other report

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38388] opened 2024-03-15 11:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4426987&group_by=cases:section_id&group_order=asc&group_id=296773
**Email or phone of affected tester (no customers):** hohovemgo+emplo11@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Preconditions:
1. Create a new Gmail account in OD
2. Create collect workspace
3. Set the workspace policy to USD
4. Open the JS console and run the following script in the collect policy settings page:

if (Url.getCurrentPageName()!="policy" ){ alert('Only run this snippet from a policy editor!'); } else { var p = Policy.getCurrent(); p.policy.isPolicyExpenseChatEnabled = "true"; p.save().done(function(){$.jGrowl('Workspace chat creation enabled!')}); }

5. Invite an employee account to the workspace

Steps:
1. Sign In with employee account in ND and OD
2. Create two empty reports in OD
3. Add two expenses to one of the empty reports
4. Navigate to workspace conversation in OD
5. Tap on the IOU preview with two added expenses
6. Navigate back to the workspace conversation
7. Open the report with two expenses in OD
8. Tap on on of the expense on the report page in OD
9. Change the report the report to other one and click on Save button
10. Navigate to LHN in ND
11. Tap on the workspace conversation

## Expected Result:
The IOU preview in workspace conversation should be updated since one of the expenses was moved to other report in OD

## Actual Result:
The IOU preview remained exactly the same as before when one expense was moved to another report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/911b4ed4-9cae-4f42-9651-6df5fb0c028f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0133592dd5880e808e</li>
        <li>Upwork Job ID: 1775967485159059456</li>
        <li>Last Price Increase: 2024-04-04</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-15 11:36
@JmillsExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-15 11:36
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by JmillsExpensify** [comment] 2024-03-20 02:49
This is actually a #wave-collect backward compatibility issue, though I think it's going to be solved by Maxence's PRs that will update the report/preview when expenses are moved between reports. @trjExpensify Do you agree?

**Comment by trjExpensify** [comment] 2024-03-20 18:04
The steps in the OP are a bit sloppy. Can we make sure to proof read them before posting? 

>4. Navigate to workspace conversation in OD

Is this supposed to say ND?

>8. Tap on on of the expense on the report page in OD
>9. Change the report the report to other one and click on Save button

These don't make sense. 

>This is actually a #wave-collect backward compatibility issue, though I think it's going to be solved by Maxence's PRs that will update the report/preview when expenses are moved between reports. @trjExpensify Do you agree?

Max is working on moving a report to a different workspace. Moving an expense to a different report should be done already: https://github.com/Expensify/App/issues/33177 CC: @yuwenmemon. 

The tester in this video OP might have a bit of a broken account. Notice how there's an empty avatar and `Submitter &` in the header of the expense report preview in the workspace chat? Might be worth a fresh repro on this, Jason.  👍

**Comment by JmillsExpensify** [comment] 2024-03-23 19:50
Not going to spend more time on this, as I don't think it's a priority. Further, the empty avatars is already an existing issue reported and covered elsewhere. That said, I'll highlight in QA for them to re-test.

**Comment by JmillsExpensify** [comment] 2024-04-03 03:24
Requested a retest

**Comment by kavimuru** [comment] 2024-04-03 14:03
@JmillsExpensify Issue is still reproducible Pixel 6/Android 14


https://github.com/Expensify/App/assets/43996225/38a58353-815c-4348-941d-bc8814f32c4d

**Comment by JmillsExpensify** [comment] 2024-04-03 16:13
Thank you!

**Comment by yuwenmemon** [comment] 2024-04-04 19:23
From the looks of it seems like we're probably missing sending an Onyx update somewhere in Auth. This is internal.

**Comment by mallenexpensify** [comment] 2024-04-04 21:37
Added to #wave-collect because we want all bugs and feature requests closed or put on a roadmap project.  Added back @mollfpr , we have C+ on `Internal` issues in case they can review the associated PR.

**Comment by JmillsExpensify** [comment] 2024-04-10 13:28
Still in the queue

**Comment by yuwenmemon** [comment] 2024-04-16 11:26
Got back from OOO last week, going to take a look at this again today/tommorow

**Comment by JmillsExpensify** [comment] 2024-04-24 05:43
Same as above.

**Comment by yuwenmemon** [comment] 2024-04-30 04:56
Argh, my bad on this I have been prioritizing some #wave-collect items over this one. Giving this the midnight look now.

**Comment by yuwenmemon** [comment] 2024-04-30 06:43
Okay, so `ReportTransactions` the API command is not very 1:1:1 at all. Only after it calls Auth's `ReportTransactions`, does it call `UpdateReport` to update the new total here: https://github.com/Expensify/Web-Expensify/blob/1cd3b857b978170c71233f812ef517d0040c17ad/lib/ReportAPI.php#L3230-L3237

This led me to some of the code we use to update the report in Onyx whenever it is updated here. However, there's a filter so that we only do this when the previous report was the Auto Report ID ([PR](https://github.com/Expensify/Auth/pull/9893)):
https://github.com/Expensify/Auth/blame/main/auth/command/UpdateReport.cpp#L149-L181

@deetergp / @Beamanator / @lakchote -- I'm curious as to why we need this check in place. Shouldn't we update the report preview _whenever_ a policy if expense chat is enabled and the report is updated? Or am I missing something here?

**Comment by yuwenmemon** [comment] 2024-04-30 06:47
And just as a note for myself, the proposed change I'd make is this very simple diff:
```diff
diff --git a/auth/command/UpdateReport.cpp b/auth/command/UpdateReport.cpp
index 0bc0df539e..eba95667c0 100644
--- a/auth/command/UpdateReport.cpp
+++ b/auth/command/UpdateReport.cpp
@@ -146,7 +146,7 @@ void UpdateReport::process()
         }
         DB::write(db, "UPDATE reports SET " + setFields + " WHERE reportID=" + SQ(reportID) + cachedDataStaleCheck + ";");
 
-        if (previousReportID == Transaction::IMPORTMERGE_REPORTID && Policy::isPolicyExpenseChatEnabled(db, Report::getPolicyID(db, reportID))) {
+        if (Policy::isPolicyExpenseChatEnabled(db, Report::getPolicyID(db, reportID))) {
             // Initialize the updates
             JSON::Value expenseReportPreviewOnyxUpdates = JSON::Value(JSON::ARRAY);
             JSON::Value expenseReportOnyxUpdates = JSON::Value(JSON::ARRAY);
```

**Comment by lakchote** [comment] 2024-04-30 07:56
I think @deetergp will have more context on this, as he has added this check with `if (previousReportID == Transaction::IMPORTMERGE_REPORTID`

**Comment by deetergp** [comment] 2024-04-30 21:29
Just talked through this on a call with @yuwenmemon. That check was only put in place to make sure I wasn't adversely affecting other report id changes — I was trying to keep it focused solely on reports going from unreported to reported without creating any side effects. If removing it works for this GH, then by all means, let's get rid of it.

**Comment by yuwenmemon** [comment] 2024-05-02 05:53
Draft PR up, will want to most likely add a test

**Comment by yuwenmemon** [comment] 2024-05-03 00:31
Ready for review @deetergp !

**Comment by JmillsExpensify** [comment] 2024-05-19 18:09
Pretty sure that we should close this issue, as the linked PR above is merged. Additionally, no C+ reviews apply.

**Closed by JmillsExpensify** 2024-05-19 18:09 UTC
Labels: Reviewing, Daily, Internal, Bug
