### ISSUE TITLE
[HOLD for payment 2024-10-10] Add labels to the LHN menu items 

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#47339] opened 2024-08-13 15:15 UTC
**Problem**: It's really hard to write quality directions for users to take specific actions that require them to navigate between the Inbox, Search and Settings pages. We have to say things like - click on the magnifying glass icon, or profile photo etc. 

Solution: Just label the icons on the LHN

**English**:
![image](https://github.com/user-attachments/assets/8835adf6-fa7a-4c36-8362-d93f212393f9)

Spanish
![image](https://github.com/user-attachments/assets/ac3197ae-43cb-4f70-ae8a-34471dbde745)

cc @shawnborton 

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by shawnborton** [comment] 2024-08-13 15:20
cc @Expensify/design for visibility too

**Comment by dannymcclain** [comment] 2024-08-13 15:31
@shawnborton My only tiny piece of input is whether we want the active label to be `text`-colored or `success`-colored (to match the icon). I kinda slightly prefer `success`, but don't feel super duper crazy strongly about. Apologies if you have already explored / decided this!

![CleanShot 2024-08-13 at 10 29 29@2x](https://github.com/user-attachments/assets/2466b05e-8125-4277-aa7e-acfd86b4c991)

**Comment by shawnborton** [comment] 2024-08-13 15:35
I haven't explored it yet! I think I lean towards just using text and bold for the active bottom tab because it feels super legible in both themes, whereas success kind of gets a bit lost on the BG in lightmode. 

Curious what @dubielzyk-expensify thinks though. I guess we don't have many other places where we use success colored text, and it feels like sticking with the proposal better matches our active tab styles too?
![CleanShot 2024-08-13 at 11 35 17@2x](https://github.com/user-attachments/assets/497268b0-bf21-4c97-bcc9-2edcdb45cc8b)

**Comment by BhuvaneshPatil** [comment] 2024-08-13 15:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add labels to bottom tab bar

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?
1. We will need to add new Text component to these items - 
https://github.com/Expensify/App/blob/c010e8c73cb8335a2a94fd5de91f4eb05f2d8fb9/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L104-L123

similar for settings and search.

code will look like this - 
```tsx
<Text textAlign='center' color={selectedTab === SCREENS.SEARCH.BOTTOM_TAB ? theme.success : theme.text}>{translate('common.search')}</Text>
```
Here we have conditionally added color
(as @shawnborton Mentioned, we can also add styles for bold conditionally)

Same goes for other two.

It will look like this - 
<img width="680" alt="Screenshot 2024-08-13 at 9 04 36 PM" src="https://github.com/user-attachments/assets/7e254ef3-7a72-4ff3-a166-e31dcfda32f6">


Also, I have a question @shawnborton @dannymcclain Do we need to change the size of icons? If yes what will be new sizes?

### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2024-08-13 15:51
### [Updated proposal](https://github.com/Expensify/App/issues/47339#issuecomment-2286559311)

- Added video 
- Changed sample code for adding bold logic

**Comment by dannymcclain** [comment] 2024-08-13 15:52
>I haven't explored it yet! I think I lean towards just using text and bold for the active bottom tab because it feels super legible in both themes, whereas success kind of gets a bit lost on the BG in lightmode.
>
>Curious what @dubielzyk-expensify thinks though. I guess we don't have many other places where we use success colored text, and it feels like sticking with the proposal better matches our active tab styles too?

Ah great points! I can get behind that.

**Comment by kpadmanabhan** [comment] 2024-08-13 16:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add labels to LHN icons to highlight current selection and help user navigate. Also applicable throughout the app.

### What is the root cause of that problem?
New feature request.

### What changes do you think we should make in order to solve the problem?
At the moment there is hover text available. However there is no highlight to suggest where the user is in LHN.
For e.g. in the screenshot below, no visual indication that I am at present in "Inbox".
![image](https://github.com/user-attachments/assets/6c13416c-74a3-4947-b8cd-706a95b1923e)

Propose following:
- display hover text below icon always for each icon
- make the text bold with a slighly larger font size than others to emphasize current selection
- highlight current selection icon in LHN with a circle or rounded squared background, something similar to what other apps do. for e.g. gmail shows highlight like below
![image](https://github.com/user-attachments/assets/b1b3c556-2033-42b2-be60-ea2b3de80b09)
- hover text can be a big more informative on what is there in "Inbox" or "Settings", something in 2-3 words. For e.g. "Search" could say something like "Search Expenses by status" or something similar.

### What alternative solutions did you explore? (Optional)
N.A.

**Comment by dubielzyk-expensify** [comment] 2024-08-13 23:55
I prefer the success label that @dannymcclain proposed here. I think the mix of `success` and `text` colors doesn't look quite as streamlined as it all being `success`. I think your point on legibility is fair though @shawnborton , but I think that perhaps just highlights the issue with that color in light mode. 

I also prefer the bold text when the tab is active.

**Comment by shawnborton** [comment] 2024-08-14 01:23
Do we have any other examples of using success colored text though? It just feels like the combination of a success colored icon + text colored text feels way more consistent with the rest of the system.

**Comment by dubielzyk-expensify** [comment] 2024-08-14 02:14
The bottom navigation is a pretty unique thing so I don't think there's too much consistency to even draw from it. It's a pretty established pattern to use the same accent color on icon and text. Had a look through to find use cases for both:

![image](https://github.com/user-attachments/assets/f28d0658-5ee2-4663-92af-019b22faa0a5)

If you feel strongly, then go for it though 👍  I don't think the variation looks bad at all.

**Comment by BhuvaneshPatil** [comment] 2024-08-14 02:22
I think we should add success colour, reason being when we are on any tab, we change the fill colour of icon completely, meaning there is significant change in how icon looks when selected, so if we don't change colour for text it will look more of a inconsistent behaviour.

**Comment by shawnborton** [comment] 2024-08-14 12:00
Okay cool, your research is definitely helpful and great to look at! I still think I am in team "different" where the label uses text color, so that would still be my preference but if you all feel super strongly for team "same" I do not want to be a blocker :) But yeah... I think avoiding the success label color in light mode is the way to go for now.

**Comment by dannymcclain** [comment] 2024-08-14 13:19
Man oh man this is a toughy. Seeing them side by side... I think using success color (team "same") looks so much better... I feel like the text labels stand out in a bad way when they're `text`-colored.

So I think if I was forced to decide right this second, I would go with `success` for now. @shawnborton would you be ok implementing it with success and revisiting if we get feedback (internal or otherwise) about it?

![CleanShot 2024-08-14 at 08 15 02@2x](https://github.com/user-attachments/assets/507b9c67-a57a-4aa6-be8d-5829a1cbacc7)

**Comment by shawnborton** [comment] 2024-08-14 13:22
If you two feel strongly, then I don't want to stand in the way. I still have pretty strong concerns about the Success color label being super hard to read though. As in, I think this objectively looks broken:
![CleanShot 2024-08-14 at 09 21 46@2x](https://github.com/user-attachments/assets/4d9847a2-ff20-49e6-9a15-15a183b39976)

So again, I still prefer to use the safer and more consistent option that more closely matches our design system. I'm not seeing what the benefit is of using the success color label.

**Comment by dubielzyk-expensify** [comment] 2024-08-15 00:40
I don't have any additional things to add :)

**Comment by dannymcclain** [comment] 2024-08-15 13:46
`Text` takes it! 🏁

**Comment by shawnborton** [comment] 2024-08-15 14:59
Right on, thanks for hearing me out team!

**Comment by anmurali** [comment] 2024-08-17 15:55
@shawnborton can you post the finals in the issue description so this is easy for the engineer to implement? I don't want them getting confused and implementing a version y'all didn't agree on.

**Comment by shawnborton** [comment] 2024-08-19 12:04
It looks like what we agreed on is the version posted in the original description, so I think we're all good here :)

**Comment by rushatgabhane** [comment] 2024-08-19 12:59
@cretadn22  / @BhuvaneshPatil / @nyomanjyotisa will your proposal still work if the settings menu is selected and it has a status emoji?

Shouldn't we also remove the green circle border around it? Waiting for updated proposals

**Comment by shawnborton** [comment] 2024-08-19 13:11
I don't think we should remove the green circle around Settings. But I can see where we might want to reduce that inner 2px gap to just 1px so we have some extra room to balance out the distance between icon and label across all of them:
![CleanShot 2024-08-19 at 09 10 43@2x](https://github.com/user-attachments/assets/98f0e719-55ce-4c81-abd6-750736a71a49)

We can fine tune that stuff in the PR phase I think.

**Comment by BhuvaneshPatil** [comment] 2024-08-19 13:41
@rushatgabhane @shawnborton 
I made some tweaks for padding and margin and this is how it looks on macos web (please ignore settings text)
Does gap looks good?

<img width="778" alt="Screenshot 2024-08-19 at 7 10 18 PM" src="https://github.com/user-attachments/assets/5ecb06e1-e6e1-47a6-a66e-069c33d6d07b">
<img width="801" alt="Screenshot 2024-08-19 at 7 10 01 PM" src="https://github.com/user-attachments/assets/629d5059-1bde-49aa-ab46-4d5577c1f6ac">

**Comment by shawnborton** [comment] 2024-08-19 13:45
I think that is a good starting point and we can tweak the exact values in the PR phase like I mentioned.

**Comment by rushatgabhane** [comment] 2024-08-19 14:01
cool, i think we can move forward with @BhuvaneshPatil's proposal then

https://github.com/Expensify/App/issues/47339#issuecomment-2286559311

🎀👀🎀

**Comment by rushatgabhane** [comment] 2024-08-19 14:02
hmm that didn't work.

🎀 👀 🎀

**Comment by marcochavezf** [comment] 2024-08-19 21:36
Sounds good, thanks @rushatgabhane! Assigning @BhuvaneshPatil 🚀

**Comment by rushatgabhane** [comment] 2024-09-18 18:41
still in review

**Comment by miljakljajic** [comment] 2024-09-20 13:02
Reassigning as I am heading out on parental leave. Thank you @RachCHopkins

**Comment by RachCHopkins** [comment] 2024-10-08 04:17
@BhuvaneshPatil I have sent you an [offer](https://www.upwork.com/nx/wm/offer/104314269), so we can be ready to issue payment on the 10th!

**Comment by BhuvaneshPatil** [comment] 2024-10-08 04:38
@RachCHopkins I have accepted the offer.

**Comment by RachCHopkins** [comment] 2024-10-10 20:44
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Closed by RachCHopkins** 2024-10-10 20:44 UTC
Labels: External, Engineering, Daily, NewFeature, Awaiting Payment

**Comment by garrettmknight** [comment] 2024-10-15 01:07
$250 approved for @rushatgabhane
