### ISSUE TITLE
mWeb - list-When list values are saved as multiple zeros, report field is not created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48406] opened 2024-09-02 12:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.27
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4908139
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap profile icon -- workspaces -- workspace
3. Tap more features -- enable report fields
4. Tap add field
5. Enter name as 0, type as "list" and list value as 0, select initial value displayed and save
6. Note a report field is created
7. Delete it
8. Tap add field
9. Enter name as 0, type as "list"
10. Create 3 list values -- 0, 00, 000 and save it
11. Select initial value as "00" and save

## Expected Result:
When list values are saved as multiple zeros, report field must be created

## Actual Result:
When list values are saved as multiple zeros, report field is not created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/2947fa3f-ffeb-4951-815c-4b8808d28125

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2024-09-02 15:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The report field creation failed when the list values contain multiple zeros.

### What is the root cause of that problem?
The error is from the BE, but I noticed that the report field was immediately removed from the list when error instead of staying on the list grayed out with an error. That's because we clear the report field on failure data and set the error to `errorFields`.
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/libs/actions/Policy/ReportField.ts#L213-L218

### What changes do you think we should make in order to solve the problem?

1. Don't clear the report field on failure. Instead, set an error property to it.
```
fieldList: {
    [fieldKey]: {
        errors: ErrorUtils.getMicroSecondOnyxErrorWithTranslationKey('workspace.reportFields.genericFailureMessage'),
    },
},
```

2. Pass the error to the list.
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx#L108-L109
```
errors: reportField.errors,
```

3. Dismiss the error when the user clears the error
a. Create a new function to clear the error in `ReportField.ts`
```
function clearReportFieldErrors(policyID: string, fieldID: string) {
    const currentFieldList = allPolicies?.[`${ONYXKEYS.COLLECTION.POLICY}${policyID}`]?.fieldList ?? {};
    const fieldKey = ReportUtils.getReportFieldKey(fieldID);
    
    if (currentFieldList[fieldKey].pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD) {
        Onyx.merge(`${ONYXKEYS.COLLECTION.POLICY}${policyID}`, {
            fieldList: {
                [fieldKey]: null,
            },
        });
        return;
    }

    Onyx.merge(`${ONYXKEYS.COLLECTION.POLICY}${policyID}`, {
        fieldList: {
            [fieldKey]: {errors: null},
        },
    });
}
```
b. Call the new function when dismissing the error
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx#L297-L298
```
const dismissError = (item) => {
    ReportField.clearReportFieldErrors(policyID, item.keyForList);
};

onDismissError={dismissError}
```

**Comment by bfitzexpensify** [comment] 2024-09-06 11:04
I can't think of a scenario where a customer would realistically be naming one of these lists '0', so I'm going to close this as an edge case

**Closed by bfitzexpensify** 2024-09-06 11:04 UTC
Labels: Daily, Overdue, Bug
