### ISSUE TITLE
[SMARTSCAN] [$500] LOW: Web - Request Money - "Changed the date to..." message looks as a new message after refreshing the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26683] opened 2023-09-04 15:50 UTC
~Held on https://github.com/Expensify/App/pull/30603~

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Click on + > Request money > Scan > Choose file, user and continue > Reach "Receipt scan in progress…" page > Change the description and date multiple times > Reload the page

## Expected Result:
 "Changed the date to..." message should not look as a new message even after refreshing the page

## Actual Result:
 "Changed the date to..." message looks as a new message after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.4 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-08-30T175326.879 (2).webm](https://github.com/Expensify/App/assets/93399543/5a1c46b9-ab2a-42b4-9ed5-13889a184412)

https://github.com/Expensify/App/assets/93399543/e4165b44-4619-4154-9152-eef42e89d312

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693399950131659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b6e7b1cbb84756c</li>
        <li>Upwork Job ID: 1698913876057669632</li>
        <li>Last Price Increase: 2023-09-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cristipaval</details>

**Comment by kadiealexander** [comment] 2023-09-05 04:19
Repro:

https://github.com/Expensify/App/assets/59587260/5f304e61-5c85-430b-b720-c70f9bac4f9c

**Comment by nahid633** [comment] 2023-09-05 10:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Request Money - "Changed the date to..." message looks as a new message after refreshing the page

### What is the root cause of that problem?

New message indicator shows when `shouldDisplayNewMarker` is true and  in the code there is state messageManuallyMarked
         if (!messageManuallyMarked.read) {
                    shouldDisplayNewMarker = shouldDisplayNewMarker && reportAction.actorAccountID !== Report.getCurrentUserAccountID();
            }

Basically we need to set mark report as read and make it shouldDisplayNewMarker false

### What changes do you think we should make in order to solve the problem?

We need to add 'OR' case this part of the code
const didManuallyMarkReportAsUnread = report.lastReadTime < DateUtils.getDBTime() && ReportUtils.isUnread(report).

 to check if 
actionName is 'MODIFIEDEXPENSE'  then mark that message as read(dont show new message indicator.).


https://github.com/Expensify/App/assets/22540272/b6f7c1e1-3995-421e-bf0f-695a28255cc0


### What alternative solutions did you explore? (Optional)
none

**Comment by kadiealexander** [comment] 2023-09-12 05:11
@narefyev91 do you agree with [this](https://github.com/Expensify/App/issues/26683#issuecomment-1706441730), that it should be marked `internal`?

**Comment by narefyev91** [comment] 2023-09-12 06:34
> @narefyev91 do you agree with [this](https://github.com/Expensify/App/issues/26683#issuecomment-1706441730), that it should be marked `internal`?

Yes we should mark this as internal - we need some BE support

**Comment by kadiealexander** [comment] 2023-09-13 07:23
@flodnv I got you assigned to handle the backend changes for this bug, thanks for your help!

**Comment by flodnv** [comment] 2023-09-14 05:00
@mountiny I see you wrote this API command in the past couple of months, so I assume this should be assigned to you

**Comment by mountiny** [comment] 2023-09-14 07:46
there is nothing special about the modified expense action comprated to other similar system messages, no special treatment which should make it work differently

I will make this weekly as its low priority

**Comment by mountiny** [comment] 2023-09-18 10:29
Focusing on wave6 design doc

**Comment by mountiny** [comment] 2023-09-25 14:19
I think weekly is an approriate priority for this bug

**Comment by mountiny** [comment] 2023-10-02 20:58
Same I think this will be fixed with wave6 updated notification settings

**Comment by mountiny** [comment] 2023-10-05 21:21
No update from me, I actually think we should make this weekly for the wave 6 notification changes

**Comment by kadiealexander** [comment] 2023-10-17 03:16
Not overdue.

**Comment by kadiealexander** [comment] 2023-10-27 05:08
@mountiny any updates?

**Comment by mountiny** [comment] 2023-10-28 13:36
No updates, was not able to prioritise right now, working on wave6

**Comment by kadiealexander** [comment] 2023-11-07 06:48
No update!

**Comment by mountiny** [comment] 2023-11-24 22:19
Working on wave6 the notification changes might help with this issue

**Comment by mountiny** [comment] 2023-12-05 22:01
Same as above

**Comment by cristipaval** [comment] 2024-01-04 19:50
[PR](https://github.com/Expensify/Auth/pull/9593) up for review

**Comment by cristipaval** [comment] 2024-01-11 20:11
this should be fixed, as [the PR ](https://github.com/Expensify/Auth/pull/9593) hit production 3 days ago

**Comment by cristipaval** [comment] 2024-01-16 22:09
@kadiealexander do we have any payment due here?

**Comment by kadiealexander** [comment] 2024-01-19 04:28
I don't think so!

**Closed by kadiealexander** 2024-01-19 04:28 UTC
Labels: Engineering, Daily, Internal, Overdue, Awaiting Payment, Bug, SmartScan
