### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] Web - Text area is misaligned in close account page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22027] opened 2023-07-01 20:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > security > close account
2. Hover over the first input placeholder and notice the cursor
3. Hover over the second input placeholder and notice the cursor
4. Open dev tools and click on inspect
5. Hover over the first input field

## Expected Result:
The cursor should not change to pointer when hovering over the first text area just like it doesn't on the second text area.

## Actual Result:
The cursor turns to pointer while hovering over the first input field place holder and the while inspecting the text area it is misaligned and the text area starts halfway through the first placeholder.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/af998e8f-36ca-407f-bbcd-73c4fae44275

https://github.com/Expensify/App/assets/93399543/5281bd40-5bb6-4bb0-b25c-6aba488486ce

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688223038310559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a57cf140b61f86f</li>
        <li>Upwork Job ID: 1675942585383223296</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by wildan-m** [comment] 2023-07-04 04:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Wrong cursor when hovering on the textinput outer boundary

### What is the root cause of that problem?

Incorrect `cursorPointer` type used in `PressableWithoutFeedback` on `BaseTextInput` component. Currently the value is `cursor`.

### What changes do you think we should make in order to solve the problem?
We can set `PressableWithoutFeedback` inside `BaseTextInput` cursorPointer style to `text`.

We can set it directly to its style or use `accessibilityRole="text"` or  `role="text"` in the `PressableWithoutFeedback`

https://github.com/Expensify/App/blob/917c344649d1fe8101de0f58a4554f3f5dee8666/src/components/TextInput/BaseTextInput.js#L248-L253

### What alternative solutions did you explore? (Optional)
N/A

**Comment by flaviadefaria** [comment] 2023-07-04 11:18
Not overdue, a proposal was posted and @allroundexperts should get to it soon.

**Comment by s77rt** [comment] 2023-07-11 00:47
Hey, just found we are fixing the same issue https://github.com/Expensify/App/issues/22121. The merged PR does not seem to fix the inconsistency between the two inputs, in multiline the cursor is `default` while in single line the cursor is `text`.

**Comment by flaviadefaria** [comment] 2023-07-24 12:46
Alright, I'm processing payment now, let me know in case something looks of:

@Nathan-Mulugeta = $250 reporting bonus (UW)
@honnamkuan = $1000 no bonus as PR wasn't merged in 3 days (UW)
@allroundexperts = $1000 no bonus as PR wasn't merged in 3 days ( Expensify - I'll cancel the contract in UW).

**Comment by flaviadefaria** [comment] 2023-07-24 13:54
Thanks folks, I updated the amounts below and will process payment now:

@Nathan-Mulugeta = $250 reporting bonus (UW)
@honnamkuan = $1000 + $500 bonus = $1500 (UW)
@allroundexperts = $1000 + $500 bonus = $1500( Expensify - I'll cancel the contract in UW).

**Comment by flaviadefaria** [comment] 2023-07-24 14:00
@Nathan-Mulugeta offer sent
@honnamkuan paid!

**Comment by Nathan-Mulugeta** [comment] 2023-07-24 14:05
Just accepted offer

**Comment by flaviadefaria** [comment] 2023-07-24 14:27
@Nathan-Mulugeta paid!

**Comment by flaviadefaria** [comment] 2023-07-24 14:28
>@allroundexperts = $1000 + $500 bonus = $1500( Expensify - I'll cancel the contract in UW).

Just missing this so we can close this GH.

**Comment by JmillsExpensify** [comment] 2023-07-27 23:31
Reviewed details for @allroundexperts . This is accurate based on summary from Business Reviewer and approved for payment in NewDot.

**Comment by flaviadefaria** [comment] 2023-07-28 13:23
Perfect so closing this.

**Closed by flaviadefaria** 2023-07-28 13:23 UTC
Labels: External, Weekly, Awaiting Payment, Bug
