### ISSUE TITLE
[$500] Status with custom time doesn't work

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33558] opened 2023-12-24 17:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dylanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703354936560399?thread_ts=1703016500.538419&cid=C049HHMV9SM

## Action Performed:

1. Access Profile > Status
2. Add any custom status
3. Click on `Clear After` > `Custom` > `Date`
4. Click Save

## Expected Result:
 It should keep the date you select and save.

## Actual Result:
Didn't keep my selected date, and I was unable to save the status

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a38ce14e-1168-4925-b5c9-350827b7afdf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c1da8c2e9f0e2ec</li>
        <li>Upwork Job ID: 1738972785687736320</li>
        <li>Last Price Increase: 2024-01-07</li>
    </ul>
</details>

**Comment by Famzy-codes** [comment] 2023-12-24 21:15
Contributor details
My account email: famakinwaemmanuel67@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0169127a83f9114c17

**Proposal**

**Problem Statement:**  
When attempting to set a custom date under "Clear After" within "Access Profile > Status" and saving, the selected date is not retained, leading to an inability to save the status with the expected date.

**Root Cause Analysis:**  
Upon analysis, the issue appears to stem from the failure to persist the selected date in the "Clear After" field when saving the status. This indicates a breakdown in the data persistence mechanism associated with custom dates in this particular section of the application.

**Proposed Solution:**  
To rectify this issue, I propose inspecting the data storage and retrieval mechanism linked with the "Clear After" functionality under the "Access Profile > Status." This would involve:
1. Reviewing the code logic governing the handling of custom dates during the save operation.
2. Identifying any errors or omissions in the data persistence flow related to storing and retrieving selected dates.
3. Implementing necessary adjustments to ensure the proper storage and retrieval of custom dates when saving the status.

**Alternative Solutions Explored:**  
Exploring alternative data storage approaches or utilizing client-side storage mechanisms was considered. However, the primary solution centers around rectifying the data persistence issue within the existing storage infrastructure to ensure the accurate saving of selected dates.

I'm prepared to delve into the codebase and address this data persistence issue promptly to ensure the accurate retention and saving of custom dates within the "Clear After" functionality of "Access Profile > Status."

Please note that any proposed changes will be thoroughly tested across supported platforms (MacOS: Chrome / Safari) to guarantee the resolution's effectiveness.

**Comment by Famzy-codes** [comment] 2023-12-24 21:17
Contributor details
Your Expensify account email: <famakinwaemmanuel67@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~0169127a83f9114c17>

**Comment by Famzy-codes** [comment] 2023-12-24 21:18
Contributor details
Your Expensify account email: famakinwaemmanuel67@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0169127a83f9114c17

**Comment by sofi-a** [comment] 2023-12-26 02:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Setting a custom clear status date clears the default/selected date and time.

### What is the root cause of that problem?
Because the date picker is not wrapped with InputWrapper in the [SetDatePage](https://github.com/Expensify/App/blob/fadf1f95d8ef77f405105a836732923c49cc7ce3/src/pages/settings/Profile/CustomStatus/SetDatePage.js#L61C1-L66C19) component, the clear after date value can't be accessed inside the submit function.

### What changes do you think we should make in order to solve the problem?
Wrap the date picker in an InputWrapper.

```jsx
<InputWrapper
    InputComponent={DatePicker}
    inputID="dateTime"
    label={translate('statusPage.date')}
    defaultValue={DateUtils.extractDate(customClearAfter)}
    minDate={new Date()}
/>
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by kaushiktd** [comment] 2023-12-26 13:36
### Please re-state the problem that we are trying to solve in this issue.

When attempting to set a custom date under "Clear After", the selected date is not saved or not worked

### What is the root cause of that problem?

In the `SetDatePage` component, there seems to be an issue related to the date picker not being encapsulated within an `InputWrapper`. This omission is causing difficulty in accessing the cleared date value within the submit function. To elaborate, when a date is cleared, the absence of an InputWrapper around the date picker prevents the submit function from effectively retrieving the cleared date value. 

### What changes do you think we should make in order to solve the problem?

To resolve this issue, you can either utilize `<InputWrapperWithRef/>` in place of `<DatePicker/>`, or you can substitute `<DatePicker/>` with the following code on [here](https://github.com/Expensify/App/blob/fadf1f95d8ef77f405105a836732923c49cc7ce3/src/pages/settings/Profile/CustomStatus/SetDatePage.js#L61):

```
<InputWrapperWithRef>
  <DatePicker />
</InputWrapperWithRef>
```
 
### Video:
https://drive.google.com/file/d/1UScOd8VJi1v-e6XqnywjCjEqL0E4PyXb/view?usp=sharing

**Comment by anmurali** [comment] 2024-01-02 23:05
@eVoloshchak can you please review the proposals and comment (or pick)

**Comment by eVoloshchak** [comment] 2024-01-03 22:41
@anmurali, this one can be closed I think. 
The bug was resolved by https://github.com/Expensify/App/pull/33525 and @rayane-djouah's [proposal](https://github.com/Expensify/App/issues/33558#issuecomment-1868571085) will be/is [discussed on Slack](https://github.com/Expensify/App/pull/33525#issuecomment-1869313160)

**Closed** 2024-01-10 01:44 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
