### ISSUE TITLE
Web - Chat - "You appear to be offline" message isn't showing if you navigate to different chats.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12946] opened 2022-11-22 21:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12877

## Action Performed:
1. Go to staging.new.expensify.com
2. Turn off the internet connection
3. Navigate to different chats

## Expected Result:
"You appear to be offline" message is showing if you navigate to different chats.

## Actual Result:
"You appear to be offline" message isn't showing if you navigate to different chats.

## Workaround:
Unknow

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.30.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![image (2)](https://user-images.githubusercontent.com/93399543/203424839-e4d615bd-4fc9-4b01-8a4f-7a47dc4fcb4f.png)

https://user-images.githubusercontent.com/93399543/203424841-b657db50-10ae-4239-b4d7-f53326326f8f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-11-23 00:23
Gonna assign myself to this one since I came back from ooo and I'm looking for WAQ issues to work on.

**Comment by luacmartins** [comment] 2022-11-23 20:46
This is the expected behavior as we hide the compose box and display the loading skeleton for chats that have no messages loaded. Closing.

**Closed by luacmartins** 2022-11-23 20:46 UTC
Labels: Engineering, Daily, Bug

**Comment by osama256** [comment] 2022-12-01 19:59
Are you looking for something like this?

https://user-images.githubusercontent.com/51829206/203607769-fe4501d7-984d-44e8-aaa6-3cfa156cc733.mov

**Comment by luacmartins** [comment] 2022-12-02 00:32
I'm not sure that we need to fix anything here as we are intentionally hiding the "You are offline" indicator
