### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Web - App closes RHN directly when we open 'Send message' using CTRL+SHIFT+K and back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27669] opened 2023-09-18 12:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open search using CTRL+K/CMD+K
4. Click back, it comes back to settings page
5. Open 'Send message' by CTRL+SHIFT+K
6. Click back and observe that it closes RHN instead of coming back to settings page

## Expected Result:
App should not directly close RHN when we open any page, open Send message by CTRL+SHIFT+K shortcut and go back

## Actual Result:
App directly closes RHN when we open any page, open Send message by CTRL+SHIFT+K shortcut and go back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5c75d57a-9b9c-4953-af53-be179de2c858

https://github.com/Expensify/App/assets/93399543/00d933f3-907c-43d7-a672-4b513a2872c6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695033497745239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01afcf31288891f8d0</li>
        <li>Upwork Job ID: 1704074354945183744</li>
        <li>Last Price Increase: 2023-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>Pluto0104 | Contributor | 26854267</li>
<li>dhanashree-sawant | Reporter | 26854269</li>
</ul></li>
    </ul>
</details>

**Comment by Pluto0104** [comment] 2023-09-18 12:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The problem we are addressing is that the Right Hand Navigation (RHN) is closing when we open the 'Send message' dialog using the keyboard shortcut `CTRL+SHIFT+K` and then navigate back.

### What is the root cause of that problem?

The root cause of this issue is identified as a regression introduced in the https://github.com/Expensify/App/commit/446f29b7d47b3dc60dc0b16d7a4adddd0127b58c. The specific code snippet responsible for this behavior is found in NewChatSelectorPage.js, where `Navigation.dismissModal` is used to close the RHN.

https://github.com/Expensify/App/blob/06e8d3ac13d9b45cae26e0967ff787998d5a4820/src/pages/NewChatSelectorPage.js#L36

### What changes do you think we should make in order to solve the problem?

To address this issue, we propose using the `Navigation.goBack` function instead of `Navigation.dismissModal`. Alternatively, we can consider removing this line altogether, allowing the `onBackButtonPress` function to revert to its default behavior of using `Navigation.goBack`.

### What alternative solutions did you explore? (Optional)

N/A

### Result

https://github.com/Expensify/App/assets/136573674/cc1731a6-975f-4a77-855e-b37df644f2f6

**Comment by Pluto0104** [comment] 2023-09-18 13:28
@nkuoch, if we open the Right Hand Navigation (RHN) using CTRL+K, clicking the back button navigates to the previous RHN instead of dismissing the modal. I believe it's important to maintain consistency in this behavior. Could you please provide clarification on this matter?

**Comment by dhanashree-sawant** [comment] 2023-09-19 06:46
Hi @nkuoch, if we decide closing RHN is correct, shouldn't it be also done for CTRL+K?

**Comment by nkuoch** [comment] 2023-09-19 10:05
All right, makes sense to make it consistent.
Let's just stick with going back rather than closing the modal then.

**Comment by ishpaul777** [comment] 2023-09-21 13:04
@Pluto0104 not sure why you 👎 my proposal. am i missing something?

**Comment by Pluto0104** [comment] 2023-09-21 13:10
Haha 😆 , sorry. I didn't see this:
> Let's just stick with going back rather than closing the modal then.
But I think your proposal is the same as my first proposal.

**Comment by ishpaul777** [comment] 2023-09-21 13:15
I think both are different. You suggest to close modal in Search page and I proposed the changes for the expected behaviour  https://github.com/Expensify/App/issues/27669#issuecomment-1725204426

**Comment by Pluto0104** [comment] 2023-09-21 13:17
cc @nkuoch
First, I noticed this comment:
> So when clicking on the left arrow, I kind of like that it doesn't have to go through the previously opened RHN again.

Due to this, I have modified my proposal. However, I believe the initial one is currently the correct approach. Have you changed your decision? If so, I will revert my proposal back to the previous version.

cc @ishpaul777

> I think both are different. You suggest to close modal in Search page and I proposed the changes for the expected behaviour

Have you had a chance to see my editing logs? You'll find my previous proposal there.

**Comment by dylanexpensify** [comment] 2023-09-21 14:29
@nkuoch to review tomorrow (Bali time)!

**Comment by nkuoch** [comment] 2023-09-21 15:27
Yes @Pluto0104 we can use your initial proposal (please re-edit it to what it was). We do want to goBack rather than close the modal :)

**Comment by Pluto0104** [comment] 2023-09-21 15:28
Thanks for clarification. @nkuoch 😄 I'll try it.

**Comment by dylanexpensify** [comment] 2023-09-25 10:29
@Pluto0104 mind giving us an update, please? 🙇‍♂️

**Comment by Pluto0104** [comment] 2023-09-25 10:46
Yep, I already reverted my proposal. Please check it.

**Comment by nkuoch** [comment] 2023-09-25 11:06
We can go with @Pluto0104 [proposal](https://github.com/Expensify/App/issues/27669#issuecomment-1723338340)

**Comment by dylanexpensify** [comment] 2023-10-02 14:13
Nice work! Waiting on regression period!

**Comment by dylanexpensify** [comment] 2023-10-10 18:41
Payment summary:

- Reporter: @dhanashree-sawant $50
- Contributor: @Pluto0104 $750

**Comment by dylanexpensify** [comment] 2023-10-10 18:52
@robertKozik mind completing checklist? 🙇‍♂️ @Pluto0104 is your Upwork profile not working?

**Comment by Pluto0104** [comment] 2023-10-10 18:55
@dylanexpensify, I'm experiencing some issues with my Upwork profile. If you don't mind, could you make the payment to another Upwork profile instead?

**Comment by dylanexpensify** [comment] 2023-10-16 09:36
@Pluto0104 we cannot, apologies!

**Comment by Pluto0104** [comment] 2023-10-16 10:46
Hey @dylanexpensify, are you saying you won't cover the cost for that?

**Comment by dylanexpensify** [comment] 2023-10-16 11:42
@Pluto0104 we can only make payments to your own Upwork account. If you need time to sort out your account, please do, and ping us when it's back on!

**Comment by Pluto0104** [comment] 2023-10-16 11:57
@dylanexpensify, I've reached out multiple times, but my account has been permanently suspended.

**Comment by dylanexpensify** [comment] 2023-10-16 12:02
discussing internally, one moment! 🙇‍♂️

**Comment by dylanexpensify** [comment] 2023-10-18 08:24
Finishing this up today!

**Closed** 2023-10-30 09:49 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment
