### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] mWeb - Chat - A keyboard briefly appears when navigating to Concierge chat via direct link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35239] opened 2024-01-26 12:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/1971198
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User is logged in https://staging.new.expensify.com/
on mWeb.
1. Open https://staging.new.expensify.com/
2. Send a message in that chat including the url https://staging.new.expensify.com/concierge
3. Click on the link

## Expected Result:
Concierge chat opens. No keyboard appears until user set focus in compose box.

## Actual Result:
Concierge chat opens. A keyboard briefly appears and closes automatically.
NOTE: when user navigates to Concierge chat via conversation link (e.g. https://staging.new.expensify.com/r/5636303947728298
) no keyboard appears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d674d58b-92bf-4d22-88ff-29faefb8fe42

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01388f2992fda42f8a</li>
        <li>Upwork Job ID: 1750854287615062016</li>
        <li>Last Price Increase: 2024-02-16</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-26 12:13
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by bernhardoj** [comment] 2024-01-26 13:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Keyboard opens briefly if we navigate to /concierge from chat.

### What is the root cause of that problem?
We have a logic to refocus the keyboard every time the report screen gets focused.
https://github.com/Expensify/App/blob/54013d34d4fd5d506467f9a637b8cc336dba0543/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L483-L500

When we go to /concierge, it will open ConciergePage, a utility page to go to the concierge chat, and then simply pops out itself.
https://github.com/Expensify/App/blob/54013d34d4fd5d506467f9a637b8cc336dba0543/src/pages/ConciergePage.tsx#L31-L34

When the ConciergePage is popped out from the stack, the current report screen gets refocused, thus the keyboard shows.

### What changes do you think we should make in order to solve the problem?

When we navigate to the concierge page, we can replace the ConciergePage screen with the Concierge report screen instead of popping out itself. This way, we can prevent the previous report screen gets refocused.

```
Navigation.isNavigationReady().then(() => {
    Report.navigateToConciergeChat(false, true);
});

function navigateToConciergeChat(ignoreConciergeReportID = false, shouldReplace = false) {
    navigateToAndOpenReport([CONST.EMAIL.CONCIERGE], false, shouldReplace)
    ...
    Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(conciergeChatReportID), shouldReplace ? 'FORCED_UP' : '');

```

### What alternative solutions did you explore? (Optional)
I have a [PR](https://www.github.com/Expensify/App/issues/34456) here that will add a new param to `navigateToConciergeChat` to dismiss the modal when navigating to concierge chat. We can make use of the dismiss modal too and update `dismissModal` modal logic to include concierge chat.

https://github.com/Expensify/App/blob/54013d34d4fd5d506467f9a637b8cc336dba0543/src/libs/Navigation/dismissModal.ts#L28-L32

`case SCREENS.CONCIERGE:`

or don't refocus on mWeb just like native.

**Comment by dylanexpensify** [comment] 2024-01-29 12:21
confirming today!

**Comment by shubham1206agra** [comment] 2024-02-02 18:25
@bernhardoj Can you confirm the repro on latest main?

**Comment by bernhardoj** [comment] 2024-02-03 02:46
Yes, still reproducible.

https://github.com/Expensify/App/assets/50919443/950349c3-5d25-403e-aa66-d92fed88d5fe

**Comment by dylanexpensify** [comment] 2024-02-05 12:55
bumped confirmation

**Comment by dylanexpensify** [comment] 2024-02-07 10:35
Nice, thanks!

**Comment by dylanexpensify** [comment] 2024-02-13 19:52
@shubham1206agra can you review @bernhardoj proposal

**Comment by dylanexpensify** [comment] 2024-02-20 09:48
@shubham1206agra  can you review @bernhardoj proposal plz

**Comment by bernhardoj** [comment] 2024-02-21 08:11
PR is ready

cc: @shubham1206agra

**Comment by dylanexpensify** [comment] 2024-02-21 10:43
Nice work!

**Comment by dylanexpensify** [comment] 2024-02-28 08:57
@shubham1206agra mind giving an update?

**Comment by dylanexpensify** [comment] 2024-03-06 11:14
tomorrow 🤑

**Comment by dylanexpensify** [comment] 2024-03-11 09:36
@shubham1206agra looking now!

**Comment by dylanexpensify** [comment] 2024-03-11 09:39
I see it pending for you @shubham1206agra [here](https://www.upwork.com/jobs/~01388f2992fda42f8a)!

**Comment by dylanexpensify** [comment] 2024-03-11 09:39
Payment Summary:
- Contributor: @bernhardoj $500
- Contributor+: @shubham1206agra $500

Please apply/request!

**Comment by bernhardoj** [comment] 2024-03-11 14:13
Applied

**Comment by dylanexpensify** [comment] 2024-03-13 10:09
paying out, and will catch up there @shubham1206agra

**Comment by marcochavezf** [comment] 2024-03-15 21:14
On hold for payment https://github.com/Expensify/App/issues/35239#issuecomment-1987998158

**Comment by marcochavezf** [comment] 2024-03-18 21:01
Moving it to weekly meanwhile

**Comment by dylanexpensify** [comment] 2024-03-20 10:58
perf, ty!

**Comment by dylanexpensify** [comment] 2024-03-27 08:20
@shubham1206agra any updates on when we can pay?

**Comment by dylanexpensify** [comment] 2024-04-09 13:36
Payment summary:
- Contributor: @bernhardoj $500
- Contributor+: @shubham1206agra $500

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-05-13 19:03
apply here please: https://www.upwork.com/jobs/~014fe2bcafd0f311d4

**Comment by dylanexpensify** [comment] 2024-05-14 09:27
done!

**Closed by dylanexpensify** 2024-05-14 09:27 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
