### ISSUE TITLE
[$1000] No visual separation between adjacent links

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22377] opened 2023-07-06 20:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send adjacent links eg: [google](google.com)[test](testing.com)
4. Observe that they are displayed as one link
## Expected Result: 
Adjacent links should have separate underlines to distinguish between the links
## Actual Result: 
When links are send adjacent to each other, link underlines are merged and displayed as one making it look like one single link
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/88911cb0-9d1a-47ef-9b27-90bf7993e8a5

https://github.com/Expensify/App/assets/43996225/8736dbe8-22ad-47bf-8562-22f6860deddf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688575497634149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a717ff7bce59f183</li>
        <li>Upwork Job ID: 1678413824138420224</li>
        <li>Last Price Increase: 2023-08-01</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-07-10 14:38
[google.com](google.com)[test](test.com) 

This is the same behaviour in GH - unless there is ` ` between the two words this is expected - 

[google.com](google.com) [test](test.com) 

Closing as this isn't a bug

**Comment by syedusamanasir** [comment] 2023-07-10 15:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No separation between links if we use `[]()` format to put links with each other
### What is the root cause of that problem?
There is not functionality available which caters the edge case of two links being shared with each other.
### What changes do you think we should make in order to solve the problem?

We need to identify which library is being used. Which in our case looks like `expensiMark` in `expensify-common`. We need to write a wrapper or change how the library is being used and identify a regex which identifies if the same formatter which put it as clickable link is used twice, put a space in between them, and it should work with `n` number of links.
### What alternative solutions did you explore? (Optional)
Alternatively, while we are sending message, we can then parse the message and put a space there in case to make sure it is readable and shows proper separated links. 
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ShogunFire** [comment] 2023-07-14 20:12
If we want the same behaviour as github I think we should do Option2 of this proposal https://github.com/Expensify/App/issues/22377#issuecomment-1624905278
Only have an underline if the link is hovered.

**Comment by laurenreidexpensify** [comment] 2023-07-17 15:44
@eVoloshchak bump for review ^^ thanks

**Comment by eVoloshchak** [comment] 2023-07-17 19:53
I think option #2 of @samh-nl's [proposal](https://github.com/Expensify/App/issues/22377#issuecomment-1624905278) is the most appropriate here
> We can only display the underline when hovering over the link

We shouldn't add a space between links, since user specifically didn't add one

🎀👀🎀 C+ reviewed!

**Comment by shawnborton** [comment] 2023-07-18 11:08
Curious for @AndrewGable's thoughts but I kind of feel like this is expected behavior - we are outputting the markdown as the user entered it. If the user enters a space between links, then you would see a space.

**Comment by eVoloshchak** [comment] 2023-07-20 17:11
> I think the space is necessary because if there is no space, then these two would look exactly the same without any difference to an end user
[google](https://github.com/Expensify/App/issues/google.com)[.com](https://github.com/Expensify/App/issues/google.com) and [google.com](https://github.com/Expensify/App/issues/google.com) and he can be fooled easily

> we are outputting the markdown as the user entered it. If the user enters a space between links, then you would see a space

@chiragxarora, I agree with @shawnborton, this isn't a bug in the application, just something the user can do. The same goes for every other application, for instance, Telegram


https://github.com/Expensify/App/assets/9059945/71b6fd3a-7721-4471-b219-466d9d53d55f

I think we just need to display the underline only when hovering over the link as @samh-nl has proposed [here](https://github.com/Expensify/App/issues/22377#issuecomment-1624905278)

**Comment by laurenreidexpensify** [comment] 2023-07-24 10:34
@eVoloshchak should we move forward with [this](https://github.com/Expensify/App/issues/22377#issuecomment-1624905278) proposal?

**Comment by eVoloshchak** [comment] 2023-07-26 18:46
> @eVoloshchak should we move forward with https://github.com/Expensify/App/issues/22377#issuecomment-1624905278 proposal?

@laurenreidexpensify, I think we should close this since this is [expected behavior](https://github.com/Expensify/App/issues/22377#issuecomment-1644290041)
@AndrewGable, what are your thoughts on [this](https://github.com/Expensify/App/issues/22377#issuecomment-1644290041)?

**Comment by laurenreidexpensify** [comment] 2023-07-26 19:12
I agree we should close - @AndrewGable please reopen if you think otherwise.

**Comment by eVoloshchak** [comment] 2023-07-26 19:41
Ah apologies, I overlooked my own comment😅
Yeah, while it's the expected behavior on mobile, desktop web could be improved with @aswin-s's proposal
cc: @laurenreidexpensify, let's open this, sorry for uncertainty

**Comment by AndrewGable** [comment] 2023-08-01 02:44
@eVoloshchak - Can you please confirm you are giving the 🎀 to @aswin-s's proposal?

**Comment by aswin-s** [comment] 2023-08-01 02:50
Not sure how I got mentioned here. I've not made any proposals for this issue. 😅

**Comment by AndrewGable** [comment] 2023-08-01 02:52
😂 Woops - Good think we are confirming!

**Comment by laurenreidexpensify** [comment] 2023-08-01 12:35
did you mean @samh-nl's proposal @eVoloshchak ?

**Comment by shawnborton** [comment] 2023-08-01 12:38
I'm not entirely following either, which proposal are we awarding? I still think this is not a bug and we should just close this out entirely. I don't think we should give these kinds of links any special treatment unless we're making a more holistic change.

**Comment by laurenreidexpensify** [comment] 2023-08-02 12:42
I'm fine with @shawnborton's proposal here - let's close this out.

**Closed by laurenreidexpensify** 2023-08-02 12:42 UTC
Labels: External, Daily, Help Wanted, Bug
