### ISSUE TITLE
[$250] Held expenses - Held expense thread becomes blank after approver approves the unheld amount

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50922] opened 2024-10-16 16:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has an approver (can be admin).

1. Go to staging.new.expensify.com
2. [Employee] Submit two expenses in the workspace chat.
3. [Employee] Hold one of the expenses.
4. [Employee] Go to transaction thread of the held expense.
5. [Approver] Approve only the unheld amount.
6. [Employee] Note that the transaction thread of the held expense becomes empty after approver approves the unheld amount.

## Expected Result:
In Step 6, the transaction thread of the held expense will not become empty after approver approves the unheld amount.

## Actual Result:
In Step 6, the transaction thread of the held expense becomes empty after approver approves the unheld amount.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/20c23467-b517-485f-8f38-2211526c0c7c

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847326112619512407</li>
        <li>Upwork Job ID: 1847326112619512407</li>
        <li>Last Price Increase: 2024-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 104520376</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by IuliiaHerets** [comment] 2024-10-16 16:16
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VickyStash** [comment] 2024-10-21 15:16
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment] 2024-10-21 17:02
**Updates:**
I was able to reproduce the issue and found the reason for it.
Inside the pusher updates after one of the expense approval the next things are going on:

![image](https://github.com/user-attachments/assets/e0ab44dd-a22e-4b94-9fe2-8b6688ddef08)

1 - Inside the expense report the report action related to holded expense is deleted.
2 - The new parent report action is assigned to the holded expense.

I'll continue my investigations to see how we can handle it.

**Comment by VickyStash** [comment] 2024-10-22 11:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The transaction thread of the held expense becomes empty for the submitter after the approver approves the unheld amount.

### What is the root cause of that problem?
After the not-handled expense is approved, the held one is turned into a one-expense report.
This means that the `chatReportID`, `parentReportID`, and `parentReportActionID` are changed for a thread report.
But inside the pusher updates only updated `parentReportActionID` is received.

![image](https://github.com/user-attachments/assets/4b35e4fa-f033-4196-b3a3-c49577b6e8b6)

So the app can't show the report as expected, till `OpenReport` command is called and updated `chatReportID`, and `parentReportID` are received. That's why after the page reloading the thread displays again but refers to another report (you can see it in the attached to the issue video).

Left - report, with pusher updates applied, without `OpenReport` called. Right - returned by `OpenReport` result.
![image](https://github.com/user-attachments/assets/d0c8dfb5-7c50-4b40-8120-5e181c0ace36)


### What changes do you think we should make in order to solve the problem?


Pusher updates should provide not only updated `parentReportActionID`  for the thread report, but also updated `chatReportID` and `parentReportID`.

**Comment by situchan** [comment] 2024-10-22 19:11
Looks like backend bug
🎀👀🎀

**Comment by lakchote** [comment] 2024-10-23 05:42
Making this internal based on @VickyStash's findings.

**Comment by lakchote** [comment] 2024-10-24 14:58
PR is under review.

Thanks @VickyStash for your investigation, it was indeed the culprit.

**Comment by isabelastisser** [comment] 2024-11-04 21:09
@lakchote @situchan, it looks like the PR is merged, what's next here?

**Comment by lakchote** [comment] 2024-11-05 06:26
@isabelastisser let's close this one, as the PR got deployed to production last week.

**Closed by lakchote** 2024-11-05 06:26 UTC
Labels: Reviewing, Daily, Internal, Bug
