### ISSUE TITLE
Android - Profile - An image of 9000x9000 pixels can be uploaded as an User / WS avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37358] opened 2024-02-27 22:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4346635
**Email or phone of affected tester (no customers):** fischer9966+022624a@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open Android App
2. Login with any account
3. Go to Account Settings (Go to any Workspace > Settings > Profile)
4. Tap to user avatar (Tap to Workspace avatar)
5. Tap Upload photo > Choose from Gallery
6. Select very large image (9000x9000 px)
7. Tap "Save"

## Expected Result:
User receives an error message related to the image size

## Actual Result:
Image of 9000x9000 pixels can be uploaded and save as an user / workspace avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6e57acdc-1d46-4af7-8c4f-aba06a1fd26e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-27 22:23
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment] 2024-02-27 22:23
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-03-03 17:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We can upload an image that has a dimension bigger than the max dimensions (4096).

### What is the root cause of that problem?
On Android, when we select an image that is bigger than 2048, [the image will be downsampled](https://www.github.com/facebook/react-native/issues/22145#issuecomment-441868528), so when we use `Image.getSize`, it will give us the downsampled dimension.
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/components/AttachmentPicker/index.native.js#L271-L274

### What changes do you think we should make in order to solve the problem?

I think the downsampling is fine, but if we want to make it consistent with other platforms, we should get the original image size.

For example by using `react-native-image-size` (`ImageSize.getSize`).

_the lib is already installed_

**Comment by kevinksullivan** [comment] 2024-03-19 21:53
Closing this, because from what I can tell this just worked.

**Closed by kevinksullivan** 2024-03-19 21:53 UTC
Labels: Engineering, Daily, Bug
