### ISSUE TITLE
split money isn't working on groups

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21919] opened 2023-06-30 01:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to '+' -> new group -> add members -> next
2. on groups page, go to '+' -> split bill
3. Type in money  -> next ,
4. on split money page , notice the split XXX amount button at the bottom is disabled
## Expected Result:
split XXX amount button at the bottom is disabled
## Actual Result:
split XXX amount button at the bottom of split amount should not be  disabled
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/029e0521-687a-47c3-8aec-a261c519f436

https://github.com/Expensify/App/assets/43996225/3f96546f-b46d-4582-9440-d22ac782b1eb

https://github.com/Expensify/App/assets/43996225/967deb8b-5002-494a-b4fc-eef260d86564

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687783287041229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment] 2023-06-30 11:24
@aldo will this be fixed in https://github.com/Expensify/App/issues/21268? Can we close this GH?

**Comment by flaviadefaria** [comment] 2023-07-03 18:45
Waiting for @aldo-expensify to confirm so  that we can decide if we close this.

**Comment by flaviadefaria** [comment] 2023-07-04 11:32
Will DM Aldo, he probably missed my comments above.

**Comment by aldo-expensify** [comment] 2023-07-11 21:35
I agree, this looks like a duplicate of https://github.com/Expensify/App/issues/21268... closing.

**Closed by aldo-expensify** 2023-07-11 21:35 UTC
Labels: Daily, Overdue, Bug
