### ISSUE TITLE
[HOLD for payment 2023-08-24] [$1000]  Dev: Web - Console log on clicking IOU preview component

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23645] opened 2023-07-26 13:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a tab where account A is signed in
2. Request a money from account B
3. Open a tab where account B is signed in
4. Open chat between account B & A
5. Click on the IOU preview component

## Expected Result:
There should be no console log error

## Actual Result:
 Console log error displayed [Failed prop type: Invalid prop `personalDetails.accountID` of type `number` supplied to `IOUPreview`, expected `object`.]

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.45-8
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e2fea8c2-9a7e-4108-a9a7-6d42cfc5cf8b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690377355421559
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f09e3655eab4d213</li>
        <li>Upwork Job ID: 1686463669325656064</li>
        <li>Last Price Increase: 2023-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26052727</li>
<li>Nodebrute | Contributor | 26052728</li>
<li>Natnael-guchima | Reporter | 26052736</li>
</ul></li>
    </ul>
</details>

**Comment by maddylewis** [comment] 2023-07-29 12:51
heya @deetergp - since this is happening on Dev, we will need an engineer to help with the reproduction steps. thank you!

**Comment by deetergp** [comment] 2023-08-01 19:47
I walked through the reproduction steps and can confirm that I am seeing that same console error. It does look as though it is something an external contributor can work on.

**Comment by icarus-0520** [comment] 2023-08-01 20:55
Proposal from upwork

One possible source of the error is in the proptypes declaration in IOUPreview.js, specifically the personal details key found in lines 83-88. Only one key is declared as belonging to the object, displayName. The first thing I would do is add accountID to this declaration and test to see if this solves the problem. Whether it does or doesn't, the next move would be to find the full JSON object that is being passed and create an interface for it to ensure safety. If this theory does not pan out, my next move would be to add logs throughout function ReportActionItemSingle in ReportActionItemSingle.js, lines 73-183, and function MoneyRequestAction in MoneyRequestAction.js, lines 87-157, to determine the values that are available and set throughout, and compare these with the values expected by IOUPreview. Generally, the solution will be to identify whether the issue lies in inheritance (something goes wrong with the data en route to IOUPreview) or declaration (IOUPreview's expected props are inaccurate), and from there implementing the most efficient type safeguards.

**Comment by icarus-0520** [comment] 2023-08-01 21:00
Contributor details
Expensify account email: aidan@disillusion.io
Upwork Profile Link: https://www.upwork.com/freelancers/~01ee97b9ff5ee5d693

**Comment by alexxxwork** [comment] 2023-08-03 20:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Console log error displayed [Failed prop type: Invalid prop `parentReportID` of type `number` supplied to `ParentNavigationSubtitle`, expected `string`.]

### What is the root cause of that problem?

This issue is caused by backend returning parentReportID of type Number instead of string

### What changes do you think we should make in order to solve the problem?


we could just use toString() to convert parentReportID to string as we already do [here](https://github.com/Expensify/App/pull/20032)

https://github.com/Expensify/App/blob/f3ece51bd5b9c2f8dc5e3be94da134a8af318cbe/src/pages/home/HeaderView.js#L193-L197 


### What alternative solutions did you explore? (Optional)

First of all various values of reportID and parentReportID should be consistent in backend replies - number or string. Then we could apply changes all over the codebase to change ReportIDs to type number.

**Comment by deetergp** [comment] 2023-08-03 23:00
@alexxxwork Can you trace back which API calls are returning `reportID` as numbers instead of strings?

**Comment by alexxxwork** [comment] 2023-08-04 01:15
1.`OpenReport` (same for `ReconnectToReport` or `ReconnectApp`): 
1.1 "parentReportID" as Number when you have an element of report with parentReportID (IOU) or create a thread
1.2. "childReportID" when you have a thread for a message in your report
1.3. "IOUReportID" when you have an IOU in report
2.`RequestMoney` return "reportID", "chatReportID", "childReportID" and "IOUReportID" as numbers
3. `CreateTask` returns "taskReportID", "childReportID"  as numbers
4. `SplitBillAndOpenReport` returns "IOUReportID" in "originalMessage" as number and in other json object as string.

**Comment by alexxxwork** [comment] 2023-08-04 01:19
@deetergp @Nodebrute The problem with ReportIDs type exists for a while, I think that parentReportID isn't included in reportPropTypes intentionally to bypass propTypes problem

**Comment by maddylewis** [comment] 2023-08-06 18:56
hiya @conorpendergrast - i am OOO until ~Aug 20. it looks like we are still deciding between two proposals:
- https://github.com/Expensify/App/issues/23645#issuecomment-1663388322
- https://github.com/Expensify/App/issues/23645#issuecomment-1664599887

We're awaiting @situchan to review those and hire a contributor to the job 👍

**Comment by conorpendergrast** [comment] 2023-08-08 11:17
@situchan Bump on the proposal review please

**Comment by situchan** [comment] 2023-08-08 12:16
@Natnael-Guchima I am not able to reproduce original console error but instead seeing this:

<img width="600" alt="Screenshot 2023-08-08 at 6 15 55 PM" src="https://github.com/Expensify/App/assets/108292595/95430aaf-c3da-4757-b21e-dea244adacf2">



Can you please confirm?

**Comment by Natnael-Guchima** [comment] 2023-08-08 12:40
@situchan Yes, I am seeing a different console log error as well. 

![Screenshot from 2023-08-08 15-39-22](https://github.com/Expensify/App/assets/57330233/50e412d6-5b97-4106-a09f-56ceed4f1db6)

**Comment by situchan** [comment] 2023-08-08 12:41
> Console log error displayed [Failed prop type: Invalid prop personalDetails.accountID of type number supplied to IOUPreview, expected object.]

So this error is gone, right?

**Comment by Natnael-Guchima** [comment] 2023-08-08 12:42
Yes, it seems like it.

**Comment by situchan** [comment] 2023-08-08 16:12
> @situchan I think first error is fixed. ParentReportID is not stored as a number anymore.

still reproducible to me

**Comment by situchan** [comment] 2023-08-08 17:05
> @situchan yes, it's reproducible. Link to related thread https://expensify.slack.com/archives/C01GTK53T8Q/p1691167905181059. I think they have created a new issue to fix it from backend.


Great discussion! As they're trying to fix the root cause in backend, I think we can leave that console error as is now.
Or if it's still annoying for devs meanwhile, we can apply workaround of `String(parentReportID)` as it's already in our codebase.

Btw the main fix here is to fix all hidden bugs where propType is wrongly defined.
@Nodebrute's [proposal](https://github.com/Expensify/App/issues/23645#issuecomment-1669977660) looks good to me.

cc: @deetergp 
🎀 👀 🎀 C+ reviewed

**Comment by Natnael-Guchima** [comment] 2023-08-08 18:48
@situchan I am able to reproduce the issue when User A & User B request money from each other & when there are a total of two standing IOUs.

![Screenshot from 2023-08-08 21-46-54](https://github.com/Expensify/App/assets/57330233/a4514a7d-cf7c-4b4e-9eeb-8cf8e098a93f)


https://github.com/Expensify/App/assets/57330233/3de49385-2bdf-4671-bc1f-5009888b81e4

**Comment by situchan** [comment] 2023-08-09 04:44
@Nodebrute nice catch! Indeed, wrong data is stored in Onyx. Can you please update your proposal to cover this?

<img width="565" alt="Screenshot 2023-08-09 at 10 43 44 AM" src="https://github.com/Expensify/App/assets/108292595/b56de96b-0ab2-4275-8896-f779d734d607">

**Comment by situchan** [comment] 2023-08-09 04:56
I think we can safely remove this optimistic data because "I am going to pay" - this means I already have this payee in my contacts list. But let's make sure it doesn't cause any issue while testing offline.

@deetergp now we found the exact root cause of this issue.
[Proposal](https://github.com/Expensify/App/issues/23645#issuecomment-1669977660) that I [approved](https://github.com/Expensify/App/issues/23645#issuecomment-1669993640) is to fix propTypes errors.
Original issue is wrong optimistic personalDetails data when pay money.
So they have different root causes.
Do you agree fixing both issues together here?

**Comment by situchan** [comment] 2023-08-09 05:01
> @situchan In the event that the same user makes multiple payments, we store their information in Onyx each time. This could lead to the creation of duplicate entries.

It's needed to support offline payment. But if they are already in `ONYXKEYS.PERSONAL_DETAILS_LIST`, no need to create another optimistic data.
Especially when request money to new user I don't know.

**Comment by situchan** [comment] 2023-08-09 05:14
> I think we can safely remove this optimistic data because "I am going to pay" - this means I already have this payee in my contacts list. But let's make sure it doesn't cause any issue while testing offline.

That's what I suggested

**Comment by deetergp** [comment] 2023-08-09 23:51
> Do you agree fixing both issues together here?

Yes, please! Let's do both.

**Comment by situchan** [comment] 2023-08-10 02:43
@deetergp ok, let's assign @Nodebrute as recommended [here](https://github.com/Expensify/App/issues/23645#issuecomment-1669993640)

**Comment by Pujan92** [comment] 2023-08-15 12:14
@Nodebrute @situchan I think regression from this as still seeing the console warnings 

https://github.com/Expensify/App/assets/14358475/6cead4a8-db5d-451e-af16-2577f5e641e2

**Comment by conorpendergrast** [comment] 2023-08-16 11:32
@Pujan92 All good after logout and login?

**Comment by conorpendergrast** [comment] 2023-08-16 11:33
@maddylewis Ah, you're back! I'll unassign myself, assign me again if you need any more help!

**Comment by Pujan92** [comment] 2023-08-16 11:42
> @Pujan92 All good after logout and login?

Yes @conorpendergrast, not seeing the warnings now.

**Comment by conorpendergrast** [comment] 2023-08-16 11:51
Fantastic, thanks for confirming!

**Comment by maddylewis** [comment] 2023-08-21 15:07
moving to daily since payment is coming up this week

**Comment by maddylewis** [comment] 2023-08-24 18:43
### Payments
- [ ] Reporting bonus: @Natnael-Guchima ($250 paid via Upwork)
- [ ] Contributor: @Nodebrute ($1000 paid via Upwork)
- [ ] C+: @situchan  ($1000 paid via Upwork)
______
- Contributor hired on August 10
- PR merged on August 14 - https://github.com/Expensify/App/pull/24386

**Comment by maddylewis** [comment] 2023-08-24 18:43
@situchan - will you lmk if any of this checklist needs to be reviewed? thanks! https://github.com/Expensify/App/issues/23645#issuecomment-1681486486

**Comment by situchan** [comment] 2023-08-24 19:43
@maddylewis this is eligible for bonus. You didn't calculate weekend

**Comment by situchan** [comment] 2023-08-24 19:59
The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/20679
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20679/files#r1304805631

Console error is already in checklist. No need regression test

**Comment by maddylewis** [comment] 2023-08-25 02:12
everyone is paid

**Closed by maddylewis** 2023-08-25 02:12 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
