### ISSUE TITLE
[HOLD for payment 2024-01-31] [$500] New organic sign-up dropped in an “Hmm.. it’s not there” chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33437] opened 2023-12-21 18:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703070069444339

## Action Performed:

1. Go to [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Sign-up with a private domain email address not on the `defaultRoom` beta > get the magic code from email
3. Enter the magic code > land in NewDot

## Expected Result:
An organic sign-up should land in the Concierge chat on first sign-in with the global create FAB expanded

## Actual Result:

- Concierge chat not highlighted in the LHN, and the main pane is a “Hmm.. it’s not there” chat screen (which we reasonable believe to be the default domain room as noted [here](https://github.com/Expensify/App/issues/33437#issuecomment-1878561682)).
- Clicking on the Concierge chat row,  the reportID in the URL updates to the Concierge chat reportID and the main pane updates: https://staging.new.expensify.com/r/8392311097742670

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (15)](https://github.com/Expensify/App/assets/38435837/9f26041c-89b7-4f1e-8e10-ee66a520de3e)

![image (14)](https://github.com/Expensify/App/assets/38435837/c65cb626-e1aa-48eb-89b2-3cdf40aff068)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5beb5290c8be9e8</li>
        <li>Upwork Job ID: 1743242903474585600</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Contributor | 28106268</li>
</ul></li>
    </ul>
</details>

**Comment by miljakljajic** [comment] 2024-01-03 11:23
Just came back online today - will try to reproduce this afternoon

**Comment by miljakljajic** [comment] 2024-01-04 16:50
Couldn't repro on staging or production - asked for others to try on the original slack thread

**Comment by trjExpensify** [comment] 2024-01-05 00:33
Commented in the thread, still reproducible for me: 

<img width="1510" alt="image" src="https://github.com/Expensify/App/assets/16232057/0880c852-1ca0-444e-aafa-abf3dbff6918">

**Comment by trjExpensify** [comment] 2024-01-05 00:34
Account I used to test on this one was tom+hmmtest2@trj.chat if helpful.

**Comment by miljakljajic** [comment] 2024-01-05 11:19
@trjExpensify am I following the repro steps correctly? I get the expected result when I try with milja.nastasia+155@gmail.com and various other email addresses.  


https://github.com/Expensify/App/assets/28715117/1469c0fc-fdc8-42cc-90ad-9da169498814

**Comment by trjExpensify** [comment] 2024-01-05 11:39
Steps are correct. Did you try a private domain email address as well?

**Comment by trjExpensify** [comment] 2024-01-05 12:04
After doing some more testing in the thread, I think for some reason we're trying to send a new private domain email sign-up into the default domain room on first sign-in. As my private domain doesn't have access to the `defaultRooms` beta which is what is hiding that unreleased room from the masses, I'm hitting the "Hmm.. it's not there!" screen as I'm dropped into that chat.

As you can see from this video from @m-natarajan attempting a reproduction on `@applause.expensifail.com` domain which has access to all betas, they get dropped into the domain default room. 

https://github.com/Expensify/App/assets/16232057/6fc359cb-7a9e-49d7-8aba-99f2b38116c1

So the investigation is to figure out when and why that started to happen. The fix is to stop doing that and land a new private domain organic sign-up in the Concierge DM, like we do a public domain sign-up.

CC: @jasperhuangg for visibility as someone with experience with rooms.

**Comment by trjExpensify** [comment] 2024-01-05 12:07
Updated the OP for you, Milja. Let's get eyes on it from the community, adding `External`.

**Comment by rojiphil** [comment] 2024-01-05 12:16
## Proposal

Bringing the proposal from [here](https://github.com/Expensify/App/issues/33551#issuecomment-1868708931)
### Please re-state the problem that we are trying to solve in this issue.

On a fresh signing with a new account, an unintended report is attempted to be displayed in central pane. This is the problem we are trying to solve. 

### What is the root cause of that problem?

When we load the App for the very first time using a new account (i.e. this account was not used for signin before), the `openApp` will also return `Domain Room` as shown in attached image below. Since the App is loaded for the first time, there will be no `reportID` specified in `routes` param due to which `findLastAccessedReport` will be used [here](https://github.com/Expensify/App/blob/7b836cfcee79084177191e3dfb4a927698b09eb4/src/libs/ReportUtils.ts#L822C1-L862C2) to determine the last accessed report id via `ReportScreenIDSetter`. Here, `isFirstTimeNewExpensifyUser` will be true as this is a first time new user and `ignoreDomainRooms` would be true as we want to ignore domain rooms. Since we ignore the domain rooms only after the check for `isFirstTimeNewExpensifyUser`, the domain room report id is returned as the last accessed id thereby resulting in the display of domain room in central pane. This is the root cause of the problem. 

![Screenshot 2023-12-25 at 8 54 30 AM](https://github.com/Expensify/App/assets/3004659/25c63dc2-dd2a-47f3-a988-c389a64af7fc)


### What changes do you think we should make in order to solve the problem?

To solve the problem, we should, first, filter out the domain rooms before deciding on the last accessed report id for the first time Expensify user [here](https://github.com/Expensify/App/blob/7b836cfcee79084177191e3dfb4a927698b09eb4/src/libs/ReportUtils.ts#L844C1-L859C6) like this:

    if (ignoreDomainRooms) {
        // We allow public announce rooms, admins, and announce rooms through since we bypass the default rooms beta for them.
        // Check where ReportUtils.findLastAccessedReport is called in MainDrawerNavigator.js for more context.
        // Domain rooms are now the only type of default room that are on the defaultRooms beta.
        sortedReports = sortedReports.filter(
            (report) => !isDomainRoom(report) || getPolicyType(report, policies) === CONST.POLICY.TYPE.FREE || hasExpensifyGuidesEmails(report?.participantAccountIDs ?? []),
        );
    }

    if (isFirstTimeNewExpensifyUser) {
        if (sortedReports.length === 1) {
            return sortedReports[0];
        }

        return adminReport ?? sortedReports.find((report) => !isConciergeChatReport(report)) ?? null;
    }


### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-01-05 13:52
Nice, thanks for digging in! Have we identified which PR caused this regression as well? It must be fairly recent.

**Comment by rojiphil** [comment] 2024-01-05 14:04
> Nice, thanks for digging in! Have we identified which PR caused this regression as well? It must be fairly recent.

Looks to me that a BE PR decided to send this sometime recently. And FE will show the `domain room` report if it comes.

**Comment by trjExpensify** [comment] 2024-01-08 11:15
>Looks to me that a BE PR decided to send this sometime recently.

If you let me know what "this" is, I might be able to find it. In the meantime, @mananjadhav can you evaluate this please? It makes the first sign-in experience really subpar.

**Comment by mananjadhav** [comment] 2024-01-10 05:11
I checked @rojiphil's proposal and it seems to fix the issue. My concern is whether or not to fix it from BE as this code hasn't been updated. But if we plan to fix it from FE then @rojiphil's proposal is fine.

🎀 👀 🎀 C+ reviewed.

**Comment by rojiphil** [comment] 2024-01-10 08:41
> If you let me know what "this" is, I might be able to find it.

@trjExpensify 
Sorry for the delayed response here. I will send my further analysis in the next comment.

**Comment by rojiphil** [comment] 2024-01-10 08:44
@cristipaval  @mananjadhav  @trjExpensify  

I digged in a little more and I think we have two different issues at hand here:

**Issue 1**: First-time new Expensify user on a private domain does not land in the Concierge chat on first sign-in

The fix for this is purely on the FE side and is regardless of the BE changes as the expectation is to show the Concierge chat on first sign-in which is not what happens.
My [proposal](https://github.com/Expensify/App/issues/33437#issuecomment-1878576298) resolves this issue.

**Issue 2**: Also, the default domain room cannot be accessed in FE. Here, this will show `Hmm.. It’s not here` in Report Screen.

This looks like an intentional change in BE with `defaultRooms` beta as I notice the following changes:
1) default domain room report is sent in `openApp` response (mentioned as part of RCA in my proposal)
2) `betas` don’t have `defaultRooms` in `openApp` response 

As `defaultRooms` beta is no longer sent by BE, we do not allow access to reports [here](https://github.com/Expensify/App/blob/76e5b1cbd80e7dc55c52f47c5572b2984a7f7ed6/src/libs/ReportUtils.ts#L3410) as `canSeeDefaultRoom` will return false [here](https://github.com/Expensify/App/blob/76e5b1cbd80e7dc55c52f47c5572b2984a7f7ed6/src/libs/ReportUtils.ts#L3401). 
Also, there is an additional impact while accessing last accessed id [here](https://github.com/Expensify/App/blob/76e5b1cbd80e7dc55c52f47c5572b2984a7f7ed6/src/libs/ReportUtils.ts#L923C1-L930C6)

Can we confirm the above BE changes and, also, if that is intentional?

**Comment by trjExpensify** [comment] 2024-01-10 23:03
I'm going to tag @jasperhuangg as this seems like a bug caused by some change made on the BE with regards to rooms. 

FWIW, I don't really get this: 

>The fix for this is purely on the FE side and is regardless of the BE changes as the expectation is to show the Concierge chat on first sign-in which is not what happens.

It works fine and as intended for a new public email address organic sign-up. It doesn't work for private domains, and the root cause of that must be related to the domain room we're dropping them in instead. Without that variable, it would work just public email address sign-ups.

**Comment by mvtglobally** [comment] 2024-01-11 06:04
Issue not reproducible during KI retests. (First week)

**Comment by rojiphil** [comment] 2024-01-11 18:23
> Issue not reproducible during KI retests. (First week)

@mvtglobally 
Not quite sure what this means. I can still reproduce this with a private domain account.

**Comment by rojiphil** [comment] 2024-01-11 19:43
@trjExpensify 

> FWIW, I don't really get this:
> 
> > The fix for this is purely on the FE side and is regardless of the BE changes as the expectation is to show the Concierge chat on first sign-in which is not what happens.

What I meant is that fix for `Issue 1` mentioned [here](https://github.com/Expensify/App/issues/33437#issuecomment-1884414344) is purely on the FE side. And it does not have any dependency with BE.

> It works fine and as intended for a new public email address organic sign-up. It doesn't work for private domains, and the root cause of that must be related to the domain room we're dropping them in instead. Without that variable, it would work just public email address sign-ups.

As I understand, the private domain room feature in FE is behind `defaultRooms` beta and BE does not currently send `defaultRooms` as beta . Now, if the BE decides to send `defaultRooms` beta, the only difference is that we would see the private domain room report instead of the `Hmm.. It’s not here` page as it is currently shown. But, the Concierge chat will not be shown on first time sign-in as in public email address sign-ups. That’s Issue 1. 

Or are we doing away with private domain room? If so, there is no need to send domain room from BE and we are good. 

Looking forward to the feedback from @jasperhuangg and also on my queries [here](https://github.com/Expensify/App/issues/33437#issuecomment-1884414344)

**Comment by miljakljajic** [comment] 2024-01-15 17:17
@jasperhuangg any chance you get, we'd appreciate your input on this one. 

>I'm going to tag @jasperhuangg as this seems like a bug caused by some change made on the BE with regards to rooms.

**Comment by jasperhuangg** [comment] 2024-01-17 15:28
Hey! Sorry guys, I've been OOO. I believe a back-end fix would probably work best for this. If a user isn't on the defaultRooms beta we shouldn't be sending them the domain room in OpenApp.

**Comment by jasperhuangg** [comment] 2024-01-17 15:37
Hey guys sorry, been OOO.

@rojiphil Can you confirm which logic in this function we're getting into that's causing this bug? https://github.com/Expensify/App/blob/3033f999751cf51e89727aa6993a05b298710023/src/libs/ReportUtils.ts#L910-L937

I'm unable to reproduce it with a fresh account on a private domain, is this a race condition of some sort? I'm creating an email with https://www.emailondeck.com/

**Comment by jasperhuangg** [comment] 2024-01-17 15:38
We should definitely be redirecting first-time Expensify users to their Concierge chat upon their first-sign in, and not the private domain chat.

**Comment by rojiphil** [comment] 2024-01-17 15:58
> We should definitely be redirecting first-time Expensify users to their Concierge chat upon their first-sign in, and not the private domain chat.

This is the Issue 1 that I was referring to [here](https://github.com/Expensify/App/issues/33437#issuecomment-1884414344). Also, please refer to my follow-up comment [here](https://github.com/Expensify/App/issues/33437#issuecomment-1887852482) for completeness.
Does this make sense?

> Can you confirm which logic in this function we're getting into that's causing this bug?

As mentioned in my proposal [here](https://github.com/Expensify/App/issues/33437#issuecomment-1878576298), first time users would reach [here](https://github.com/Expensify/App/blob/3033f999751cf51e89727aa6993a05b298710023/src/libs/ReportUtils.ts#L920C1-L926C6) but we have still not skipped the domain room as done [here](https://github.com/Expensify/App/blob/3033f999751cf51e89727aa6993a05b298710023/src/libs/ReportUtils.ts#L928C1-L935C6) because of which the private domain room will get displayed.

**Comment by rojiphil** [comment] 2024-01-18 14:41
@mananjadhav 
I tested and it works well.
Over to you for review.

**Comment by mvtglobally** [comment] 2024-01-18 22:21
Issue not reproducible during KI retests. (Second week)

**Comment by miljakljajic** [comment] 2024-01-22 12:24
@mvtglobally can you confirm you're using a private domain to try and reproduce? Still reproducible for me whenever I sign up with a private email address. 

https://github.com/Expensify/App/assets/28715117/50392431-411e-4dee-b103-2e3e4fbe2664

**Comment by cristipaval** [comment] 2024-01-30 15:33
tomorrow is the payment day, melv

**Comment by miljakljajic** [comment] 2024-01-31 17:34
@rojiphil - paid in upwork

Summary for @mananjadhav below:

@mananjadhav is owed 500 USD for their role in reviewing the code. Please request payment in ND.

**Closed by miljakljajic** 2024-01-31 17:34 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-02-01 14:02
$500 approved for @mananjadhav based on summary above.
