### ISSUE TITLE
[$250] Track expense - Chat shows skeleton after the second track expense with receipt is created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40028] opened 2024-04-10 18:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat with no unsettled request
3. Create a manual track expense with receipt
4. Delete the expense
5. Create another manual track expense with receipt

## Expected Result:
The chat will not show skeleton after the second track expense with receipt is created

## Actual Result:
The chat shows skeleton after the second track expense with receipt is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7c50b6f0-3239-4808-9fd0-43b5981a6051

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010cd45fe8e755205b</li>
        <li>Upwork Job ID: 1778160044987084800</li>
        <li>Last Price Increase: 2024-04-17</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-10 18:50
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment] 2024-04-10 18:51
@srikarparsi  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by srikarparsi** [comment] 2024-04-10 19:24
Removing this as a deploy blocker because it's related to a new feature ([Track Expense](https://github.com/Expensify/App/pull/39190)) cc @neil-marcellini

**Comment by kameshwarnayak** [comment] 2024-04-12 07:40
Unable to reproduce

**Comment by sufyan-siddiqui** [comment] 2024-04-12 07:51
It seems that the issue is not reproducing on chrome.

![chrome_waLTTem4p0](https://github.com/Expensify/App/assets/54620116/c4387d7e-7804-4a74-86e9-a6892e7c272f)

**Comment by sufyan-siddiqui** [comment] 2024-04-12 07:54
Contributor details
Your Expensify account email: sufyanahmed403@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e798ed05fcee200a

**Comment by srikarparsi** [comment] 2024-04-17 22:19
Agreed, not able to reproduce as well. Closing this out.

**Closed by srikarparsi** 2024-04-17 22:19 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue
