### ISSUE TITLE
[$1000] Focus is applied and automatically removed from the emoji search field

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19542] opened 2023-05-24 15:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open an existing chat
2. Send money/ request money
3. Right-click on the bottom end of the settle up/ owes message
4. Click on add emoji icon

## Expected Result: 
Focus should remain applied to the emoji search field
## Actual Result: 
Focus is applied to and then automatically removed from the emoji search field

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5a21d0d8-65bd-4d34-9ebe-4d5c7db3c87b

https://github.com/Expensify/App/assets/43996225/d56bdc45-571d-46fe-af7f-27eef3b18126

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684841616606439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e677976150240210</li>
        <li>Upwork Job ID: 1661497540579950592</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by zanyrenney** [comment] 2023-05-24 16:16
I can't reproduce this: 
![2023-05-24_17-15-41 (1)](https://github.com/Expensify/App/assets/56830058/1c3f1124-8fde-4eea-8cec-a3e8040d5763)

**Comment by Natnael-Guchima** [comment] 2023-05-24 16:22
@zanyrenney It is not reproducible when you open the emoji dialog box using the hover-over flow. You have to go through the right-click flow to reproduce the issue. And also the place where you right-clicks matters too. 

![image](https://github.com/Expensify/App/assets/57330233/3ce852ff-ab2c-4960-a6ef-b3da36355bd9)

**Comment by zanyrenney** [comment] 2023-05-24 16:23
Dammit I deleted my comment accidentally: 
![2023-05-24_17-20-02 (1)](https://github.com/Expensify/App/assets/56830058/4018a88a-fb5f-4dbf-bc67-3f80af9d426c)

**Comment by zanyrenney** [comment] 2023-05-24 16:23
Ah nice thank you so much @Natnael-Guchima !

**Comment by zanyrenney** [comment] 2023-05-24 16:25
Able to repro: 
![2023-05-24_17-24-43 (1)](https://github.com/Expensify/App/assets/56830058/9d7980b7-8844-489b-a8cd-5f3d021c1a2e)

**Comment by chiragsalian** [comment] 2023-05-24 22:20
Discussed on slack with vit ([here](https://expensify.slack.com/archives/C01GTK53T8Q/p1684947117570559?thread_ts=1684944050.309239&cid=C01GTK53T8Q)). We feel like this is not a blocker. I did a quick search and nothing stood out to me.
Removing deploy blocker label and marking it as external to be tackled.

**Comment by Natnael-Guchima** [comment] 2023-05-26 16:05
@parasharrajat I will test this in an hour, and I will let you know this is still reproducible.

**Comment by Natnael-Guchima** [comment] 2023-05-26 18:03
@parasharrajat I can't reproduce this issue any longer. It seems that the issue is fixed somewhere on the last two releases: https://github.com/Expensify/App/issues/19565 & https://github.com/Expensify/App/issues/19422

**Comment by Natnael-Guchima** [comment] 2023-05-26 18:33
You are welcome!

**Comment by Natnael-Guchima** [comment] 2023-05-27 09:50
Hello @zanyrenney👋, 
I reported this issue when it was first introduced to staging, and initially was listed as a deploy blocker [here](https://github.com/Expensify/App/issues/19422#:~:text=broken%C2%A0%2319482-,%5B%241000%5D%20Focus%20is%20applied%20and%20automatically%20removed%20from%20the%20emoji%20search%20field%C2%A0%2319542,-%5B%241000%5D%20%5BHOLD%20for). Now, it seems that the issue is fixed somewhere in the latest release, and the fixing PR doesn't seem to be linked to this issue. Am I eligible for reporting bonus?

Thanks.

**Closed** 2023-05-30 17:51 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by Natnael-Guchima** [comment] 2023-05-30 17:56
> @Natnael-Guchima paid you for the bug report. 
> 
> Going to go ahead and close since this is fixed. Thanks everyone!

Thanks, Puneet.

**Comment by Natnael-Guchima** [comment] 2023-05-30 17:56
> @Natnael-Guchima paid you for the bug report. 
> 
> Going to go ahead and close since this is fixed. Thanks everyone!

Thanks, Puneet.

**Comment by Natnael-Guchima** [comment] 2023-05-30 17:57
> @Natnael-Guchima paid you for the bug report. 
> 
> Going to go ahead and close since this is fixed. Thanks everyone!

Thanks, Puneet.
