### ISSUE TITLE
[HOLD for payment 2023-07-21] [$1000] Web - Bank - Back icon on last stage of adding bank account page is not clickable in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21837] opened 2023-06-28 20:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Workspace > Bank account
3. Enter bank account manually using the following information
Routing Number: 011401533
Account Number: 1111222233331111
Company: Alberta Bobbeth Charleson
Tax ID: 123456789
First Name: Alberta
Last Name: Charleson
(put anything in the other fields, but don't add any beneficial owner, not even yourself)
4. At the final step (Submit three amounts), close the side pane.
5. Disconnect internet
6. Go to Settings > Workspace > Bank account
7. Click on the back icon

## Expected Result:
User is able to return to workspace settinggs

## Actual Result:
Back icon is not clickable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/285f0c2b-5b69-483b-a19b-036d4f06acb1

![Bug6110070_bandicam_2023-06-29_03-35-09-425](https://github.com/Expensify/App/assets/78819774/314b4e45-1423-4762-8538-f9ec5623d095)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a97e625eb340b983</li>
        <li>Upwork Job ID: 1674741547786518528</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by Nikhil-Vats** [comment] 2023-06-28 23:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking back icon on last stage of adding bank account page in offline mode doesn't navigate anywhere or close RHN.

### What is the root cause of that problem?
When we are on final step but not done then achData state has the value PENDING. So, when we click back `shouldShowContinueSetupButton` is changed to `true`.
https://github.com/Expensify/App/blob/9fc9f79f7f8db0db55bfc242ebfe2a15916cf1b7/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L306-L315

So, `ContinueBankAccountSetup` should be shown but it is not shown because the condition in if block above it is true and so `ReimbursementAccountLoadingIndicator` keeps on returning and we get stuck on the same step.

The condition in first if block is `true` because ACH data is still loading `shouldShowOfflineLoader` is `true` since we are in offline mode but not in one of the steps listed on line 337. So, we never go to the second `if` block to render `ContinueBankAccountSetup`.
https://github.com/Expensify/App/blob/9fc9f79f7f8db0db55bfc242ebfe2a15916cf1b7/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L334-L360

### What changes do you think we should make in order to solve the problem?
We should just change the order of if blocks so that if `shouldShowContinueSetupButton` is `true` then we return it rather than being stuck in `ReimbursementAccountLoadingIndicator` in offline mode. 
### What alternative solutions did you explore? (Optional)
NA

**Comment by flaviadefaria** [comment] 2023-07-03 18:43
We're waiting for an updated proposal.

**Comment by flaviadefaria** [comment] 2023-07-05 21:32
Still waiting

**Comment by Skalakid** [comment] 2023-07-06 19:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Back icon is not clickable when we are offline and we are at the last step of adding bank account

### What is the root cause of that problem?
When we are at the final step and we try to come back to this page when we are offline the achData state has always the PENDING value. The current logic of the `goBack()` function for `Verification` step does not include offline flow and we are just changing `shouldShowContinueSetupButton` to true. We are blocked in the wrong if statement

### What changes do you think we should make in order to solve the problem?

I think we don't have any special state for `achData` when we are offline, so we can add [here](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L310) a condition if a user is online:
```
    ...
    } else if (!this.props.network.isOffline && achData.state === BankAccount.STATE.PENDING) {
        this.setState({
            shouldShowContinueSetupButton: true,
        });
    } else {
        Navigation.goBack();
    }
```

Here is how it works:

https://github.com/Expensify/App/assets/39538890/c0e60159-e2f1-4b53-a408-b99ca31574fd

**Comment by flaviadefaria** [comment] 2023-07-24 12:26
Alright processing payment for this now:

@allroundexperts $1000 + 500 (50% bonus) = $1500
@Skalakid $1000 + 500 (50% bonus) = $1500

@allroundexperts are you paid in UW or requesting it via Expensify?

**Comment by flaviadefaria** [comment] 2023-07-24 12:39
Ok looks like we're all set here and just waiting for @allroundexperts to request payment and Anu to confirm payment so that we can close this.

**Comment by flaviadefaria** [comment] 2023-07-26 08:36
@allroundexperts can you confirm if you have already requested the $1500 payment?

**Comment by JmillsExpensify** [comment] 2023-07-27 23:30
Reviewed details for @allroundexperts. This is accurate based on summary from Business Reviewer and approved for payment in NewDot.

**Comment by flaviadefaria** [comment] 2023-07-28 11:06
Great so closing this GH.

**Closed by flaviadefaria** 2023-07-28 11:06 UTC
Labels: External, Daily, Awaiting Payment, Bug
