### ISSUE TITLE
[$125] Chat - Emoji is top-aligned instead of centered in the composer

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40412] opened 2024-04-18 09:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Enter only emoji in the composer.

## Expected Result:
The emoji will be centered in the composer.

## Actual Result:
The emoji is top-aligned in the composer.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1440" alt="Bug6453296_1713425287333!emoji_not_centered" src="https://github.com/Expensify/App/assets/115492554/894f807a-0f45-4032-801f-b8f7bd22321f">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167e42daeaa6d9467</li>
        <li>Upwork Job ID: 1781349395352080384</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>MahmudjonToraqulov | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by izarutskaya** [comment] 2024-04-18 09:51
@twisterdotcom I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-18 09:51
We think this issue might be related to the #collect project.

**Comment by MahmudjonToraqulov** [comment] 2024-04-18 10:26
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Chat - Emoji is top-aligned instead of centered in the composer

### What is the root cause of that problem?
The size of Emojis has been made larger but the height of the parent tag (span) is still small.

### What changes do you think we should make in order to solve the problem? 

We should add "`line-height: normal`" to parent element here: 
![photo_2024-04-18_15-25-05](https://github.com/Expensify/App/assets/91727683/1c164190-f9a8-42cf-829a-1ef04503c732)


### What alternative solutions did you explore? (Optional)
N/A


### Result

After Fixed
![photo_2024-04-18_15-18-20](https://github.com/Expensify/App/assets/91727683/63a26cf4-fe36-4232-83bc-634cc59cfbcd)


![photo_2024-04-18_15-18-28](https://github.com/Expensify/App/assets/91727683/ad2cf2f5-a07b-41ad-a59c-8402c70d6e40)

**Comment by twisterdotcom** [comment] 2024-04-18 14:13
@mountiny two things:
1. I'm going to remove the deploy blocker, this is **not** a blocker.
2. I'm going to demote to Daily and assign Design.
3. Can we assign @MahmudjonToraqulov?

**Comment by shawnborton** [comment] 2024-04-18 15:56
Let me know how I can be helpful. Do we have a link to the PR that caused this regression?

**Comment by MahmudjonToraqulov** [comment] 2024-04-18 16:03
> Let me know how I can be helpful. Do we have a link to the PR that caused this regression?

Hey. I included it in my Proposal.

**Comment by shawnborton** [comment] 2024-04-18 16:10
Got it. If @Skalakid's PR broke this, why aren't we asking them to create a follow up to fix it?

**Comment by mountiny** [comment] 2024-04-19 15:49
I agree this does not have to be a blocker. 

I think we can go with @MahmudjonToraqulov solution but it would be great to properly test it.

**Comment by mountiny** [comment] 2024-04-19 15:50
@akinwale can you also check out the proposal?

**Comment by akinwale** [comment] 2024-04-19 15:51
> @akinwale can you also check out the proposal?

Will do.

**Comment by shawnborton** [comment] 2024-04-22 11:58
Not overdue, working through proposals.

**Comment by akinwale** [comment] 2024-04-22 12:08
@MahmudjonToraqulov Looking at your proposal, if we set the line height to the emoji font size, how does it look when there are no emojis and it's just text in the composer?

**Comment by MahmudjonToraqulov** [comment] 2024-04-22 15:09
> @MahmudjonToraqulov Looking at your proposal, if we set the line height to the emoji font size, how does it look when there are no emojis and it's just text in the composer?

Looks normal. You can see it in the video below.

https://github.com/Expensify/App/assets/91727683/34691a32-2fda-494e-8057-7bc52e7c39e1

**Comment by akinwale** [comment] 2024-04-22 15:57
We can move forward with @MahmudjonToraqulov's [proposal ](https://github.com/Expensify/App/issues/40412#issuecomment-2063538025) here.

🎀👀🎀 C+ reviewed.

**Comment by MahmudjonToraqulov** [comment] 2024-04-23 08:00
> We can move forward with @MahmudjonToraqulov's [proposal ](https://github.com/Expensify/App/issues/40412#issuecomment-2063538025) here.
> 
> 🎀👀🎀 C+ reviewed.

Thanks @akinwale. I just found a regression from my Proposal. Let me fix it and make a PR. Thanks.

**Comment by twisterdotcom** [comment] 2024-04-25 21:35
How is this going @MahmudjonToraqulov?

**Comment by MahmudjonToraqulov** [comment] 2024-04-26 03:58
> How is this going @MahmudjonToraqulov?
Hey. I think regression is not related to my PR. I meant this [issue](https://github.com/Expensify/App/issues/41026)
I'll make PR soon.

**Comment by MahmudjonToraqulov** [comment] 2024-04-26 04:27
[PR](https://github.com/Expensify/App/pull/41058) is ready for review.

**Comment by BartoszGrajdek** [comment] 2024-06-18 10:57
Hi, I’m Bartosz from SWM `react-native-live-markdown` team. We’ve recently decided that it would be best to actively participate in all of the issues that could be related to the library we’re working on. That means reviewing proposals together with the Expensify team and supporting external contributors to ensure quality solutions that won’t introduce any additional regressions. 🙌🏻 

I’m currently going through all of the issues that could require any changes to the library. Feel free to tag me if you need anything, later I’ll be diving into the issues more in-depth, but there’s quite a few of them so it can take a while for me to catch up. Oh and feel free to tag me in any live-markdown related issues in the future! 😄

**Comment by BartoszGrajdek** [comment] 2024-06-18 10:58
I believe this could be fixed by a feature we'll be implementing in the coming days, let me come back here later today/tomorrow 👀

**Comment by BartoszGrajdek** [comment] 2024-06-24 13:50
As you can see the PR was merged! We're currently working on a PR with version bump of `react-native-live-markdown` here in E/App, can we test if this problem was fixed there? https://github.com/Expensify/App/pull/44262

**Comment by mountiny** [comment] 2024-08-08 23:36
This seems to have been fixed with the react live markdown update.

I think we should pay $125 to @MahmudjonToraqulov @akinwale still though as they spent considerable time on fixing and testing this across platforms before we put it on hold for react live markdown

**Comment by twisterdotcom** [comment] 2024-08-13 14:16
Payment Summary:

- @MahmudjonToraqulov paid $125 via Upwork [here](https://www.upwork.com/nx/wm/offer/103508154) (Contributor)
- @akinwale paid $125 via Upwork [here](https://www.upwork.com/nx/wm/offer/103508162) (C+)

**Closed by twisterdotcom** 2024-08-13 14:16 UTC
Labels: External, Engineering, Daily, Design, Awaiting Payment, Bug
