### ISSUE TITLE
[HOLD for payment 2023-11-06] [$1000] Chat - When we delete some messages from a thread, the rest of the undeleted messages disappear

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26012] opened 2023-08-26 21:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Login
2.  Enter a chat
3. Write a message A and click the Send button
4. Click in Reply in thread
5. Write a message B and click the Send button
6. Click in Reply in thread
7.  Write a message C and click the Send button
8. Click in Reply in thread
9. Write a message D and click the Send button
10. Click in Reply in thread
11. Write a message E and click the Send button
12. Now delete the message D and B and you will see the rest of the messages for a moment and then they disappear from the thread

## Expected Result:
When we delete a message from a thread, the rest of the thread should not be deleted

## Actual Result:
When we delete a message from a thread, the rest of the thread is deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Safari

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2450cbe2-aafe-4292-9b42-41fe22094b4e

![Screenshot 2023-08-17 at 03 23 43](https://github.com/Expensify/App/assets/78819774/0ae7c7e7-8338-4edb-9ebe-5ab6fe197ebf)

https://github.com/Expensify/App/assets/78819774/669a166c-bae4-4c76-bbb6-84aa92ac01d7

**Expensify/Expensify Issue URL:**

**Issue reported by:**@eusalazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692252890687509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162c908765ad3ae06</li>
        <li>Upwork Job ID: 1697250502676635648</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment] 2023-08-31 14:10
This is a little bit confusing and I will need input from a C+ or Engineer on the expected behavior here.

https://recordit.co/F1uorCO0ij

I tried to reproduce it here and noticed that we deleted/removed more than just the deleted thread response, which looks like the bug report made. But I want to confirm this behavior is _wrong_ or _incorrect_. Assigning `external` to get a hand with this step!

**Comment by michaelhaxhiu** [comment] 2023-09-01 11:14
not overdue melvs

**Comment by michaelhaxhiu** [comment] 2023-09-06 20:26
@situchan do you agree with the nature of this bug?

**Comment by situchan** [comment] 2023-09-06 20:53
> @situchan do you agree with the nature of this bug?

Agree

**Comment by s-alves10** [comment] 2023-09-08 05:34
Now we treat deleted message as an invisible action though they have visible children. This is the root cause.
This issue requires both backend and frontend work.

**Comment by michaelhaxhiu** [comment] 2023-09-11 16:43
Cool we can recruit help from an internal and external engineer if we need! Are you going provide a proposal @s-alves10 ?

**Comment by s-alves10** [comment] 2023-09-11 16:45
Yes

**Comment by rojiphil** [comment] 2023-09-15 09:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we delete some messages from the thread, the rest of the undeleted messages disappear
[The slack conversation here](https://expensify.slack.com/archives/C049HHMV9SM/p1694502825117099) seems to be addressing the same problem discussed here.

### What is the root cause of that problem?
The root cause of the problem is in the FE and BE.

FE Cause: When we delete the parent report action from the Thread, we pass `originalReportID` at this location [here](https://github.com/Expensify/App/blob/c36ac0c98cf8a92a5b7136bbf090550cca5ea90c/src/libs/actions/Report.js#L1014) that represents the parent action’s Report. However, the `optimisticParentReportData` will update the parent action of parent action’s Report which is what causes this problem. This change was made as part of the [PR for this issue here](https://github.com/Expensify/App/issues/23365). 

BE Cause: The BE is also setting `childVisibleActionCount` to 0 which is the problem. Detailed discussion is available in this slack conversation [here](https://expensify.slack.com/archives/C049HHMV9SM/p1694502825117099)

### What changes do you think we should make in order to solve the problem?

There are two changes that need to be made:

1) Instead of passing the `originalReportID` [here](https://github.com/Expensify/App/blob/c36ac0c98cf8a92a5b7136bbf090550cca5ea90c/src/libs/actions/Report.js#L1014) we must pass `reportID` as shown below:

```
    const optimisticParentReportData = ReportUtils.getOptimisticDataForParentReportAction(
        reportID,
        optimisticReport.lastVisibleActionCreated,
        CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE,
    );
```

2) BE also need to change. The change is mentioned [here](https://expensify.slack.com/archives/C049HHMV9SM/p1694711047933359?thread_ts=1694502825.117099&cid=C049HHMV9SM) and [here](https://expensify.slack.com/archives/C049HHMV9SM/p1694713178713469?thread_ts=1694502825.117099&cid=C049HHMV9SM)

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-09-15 17:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

1. Send message A(report AA)
2. Reply in thread(report BB)
3. Send message B
4. Reply in thread(report CC)
5. Send message C
6. Delete the message B in report BB or report CC

In this case, message B in report BB has a visible child action(message C) and so should be shown as [Deleted Message]. So in report AA, message A should have 1 child action but doesn't show child action count

### What is the root cause of that problem?

Please take a look at the below code snippet
https://github.com/Expensify/App/blob/1862aff7d5a4c677b3c7ea0424be1f6361dcc91a/src/libs/actions/Report.js#L1013-L1017

Suppose that we delete a message B in report CC. In this case, `originalReportId` is `BB`.

And the `parentReportAction` is message A here
https://github.com/Expensify/App/blob/1862aff7d5a4c677b3c7ea0424be1f6361dcc91a/src/libs/ReportUtils.js#L1878

We decrease the `childVisibleActionCount` by one below
https://github.com/Expensify/App/blob/1862aff7d5a4c677b3c7ea0424be1f6361dcc91a/src/libs/ReportUtils.js#L1849-L1851

As you can see, message B is still visible because it has a visible child action, but we decrease the `childVisibleActionCount` of the message A(`parentReportAction`).

This is the root cause

### What changes do you think we should make in order to solve the problem?

In case a deleted message has visible child actions, we shouldn't decrease the `childVisibleActionCount` of the `parentReportAction`

Replace this code
https://github.com/Expensify/App/blob/1862aff7d5a4c677b3c7ea0424be1f6361dcc91a/src/libs/actions/Report.js#L1012-L1020

with
```
    // Update optimistic data for parent report action if the report is a child report and reportAction has no visible child actions
    const childVisibleActionCount = reportAction.childVisibleActionCount || 0;
    if (childVisibleActionCount === 0) {
        const optimisticParentReportData = ReportUtils.getOptimisticDataForParentReportAction(
            originalReportID,
            optimisticReport.lastVisibleActionCreated,
            CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE,
        );
        if (!_.isEmpty(optimisticParentReportData)) {
            optimisticData.push(optimisticParentReportData);
        }
    }
```

This logic should be implemented in the backend as well.

The video was recorded in offline mode

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/59a6b239-cff1-46d1-991e-da9f6dbca2da


</details>


### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2023-09-15 18:05
## Proposal

[Updated](https://github.com/Expensify/App/issues/26012#issuecomment-1720939190) to include fix for #23365.
Note: This issue is also closely related to #19722 and #23450

**Comment by situchan** [comment] 2023-09-19 10:25
reviewing updated proposal soon after some urgent DB issues

**Comment by michaelhaxhiu** [comment] 2023-09-21 16:13
@situchan let us know when you get a moment to review. If no proposals are valid please state that, and I'll double the bounty accordingly.

**Comment by situchan** [comment] 2023-09-21 16:36
@s-alves10 thanks for the proposal. Can you verify that the issue still happens after logout and re-login? To confirm if we should fix backend as well.

**Comment by s-alves10** [comment] 2023-09-21 21:28
@situchan 

Yes, this still happens after re-login

**Comment by michaelhaxhiu** [comment] 2023-09-27 14:15
@situchan can you prioritize this please?

**Comment by situchan** [comment] 2023-10-03 11:27
reviewing today

**Comment by abekkala** [comment] 2023-10-03 20:52
@situchan are either of the proposals above sufficient to move forward here?

**Comment by abekkala** [comment] 2023-10-04 18:42
@situchan have you reviewed the proposals yet?

**Comment by situchan** [comment] 2023-10-04 18:44
> Now we treat deleted message as an invisible action though they have visible children. This is the root cause. This issue requires both backend and frontend work.

I think this is bug to fix.
@s-alves10 do you have any link to this discussion if it's expected?

**Comment by s-alves10** [comment] 2023-10-04 22:53
@situchan 

> Now we treat deleted message as an invisible action though they have visible children.

I'm sorry. I meant when decrease the visible child action count of parent report action.

You can see the below statement in [my proposal](https://github.com/Expensify/App/issues/26012#issuecomment-1721607237). I wanted to say that

`As you can see, message B is still visible because it has a visible child action, but we decrease the childVisibleActionCount of the message A(parentReportAction).
`

**Comment by abekkala** [comment] 2023-10-09 14:06
@situchan where are we with this one? 

is the proposal above sufficient? Or should I pull in someone to get this one moving forward?

**Comment by abekkala** [comment] 2023-10-12 14:26
@situchan can you give an update here

**Comment by situchan** [comment] 2023-10-12 14:29
Can we hold this until #28364 is merged? As we need to test LHN last messages as well.

**Comment by abekkala** [comment] 2023-10-16 18:04
On Hold until https://github.com/Expensify/App/pull/28364 is merged?

**Comment by abekkala** [comment] 2023-10-19 14:35
@situchan https://github.com/Expensify/App/pull/28364 has been merged to production

**Comment by situchan** [comment] 2023-10-19 15:07
@rojiphil @s-alves10 is your proposal still valid based on latest codebase?

**Comment by abekkala** [comment] 2023-10-23 21:10
@situchan can you give a quick update on this one

**Comment by situchan** [comment] 2023-10-24 06:20
@s-alves10's [proposal](https://github.com/Expensify/App/issues/26012#issuecomment-1721607237) looks good to me.
We should also update backend logic.
🎀 👀 🎀 C+ reviewed

**Comment by thienlnam** [comment] 2023-10-24 17:23
Yup looks good, agree we should also make the internal changes here

**Comment by s-alves10** [comment] 2023-10-25 00:15
@situchan 

PR is ready for review https://github.com/Expensify/App/pull/30317

**Comment by abekkala** [comment] 2023-10-27 14:59
merged to staging yesterday

**Comment by abekkala** [comment] 2023-10-31 15:41
### PAYMENTS FOR NOV 6

- Reporter: @eusalazar [$250] (this was reported prior to price change)
- Fix: @s-alves10 [$1000 + $500 Bonus]
- PR Review: @situchan [$1000 + $500 Bonus] 

assigned Oct 24 - merged PR Oct 26 

@situchan can you complete the checklist?

Upwork is not letting me create a job posting right now. I'll keep checking and post the offer links here when I'm able.

**Comment by abekkala** [comment] 2023-11-06 18:32
@eusalazar [offer](https://www.upwork.com/nx/wm/offer/27545368) sent. Once accepted I can process payment!

@s-alves10 [offer](https://www.upwork.com/nx/wm/offer/27545383) sent. Once accepted I can process payment!

@situchan please complete checklist and I can send payment

**Comment by situchan** [comment] 2023-11-06 18:55
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/22990
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/22990/files#r1383813987
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

I think this is unusual case and users will most likely not face this.
But in case regression test is still needed:

### Regression Test Proposal

1. Navigate to any chat
2. Send message A and reply in thread
3. Send message B and reply in thread
4. Send message C
5. Disable network
6. Delete message B
7. Verify that the message A still has 1 reply in the chat at Step 2

**Comment by abekkala** [comment] 2023-11-06 19:47
@eusalazar and @situchan payment made and contract ended - Thank you! 🎉 

@s-alves10 once [offer](https://www.upwork.com/nx/wm/offer/27545383) is accepted I'll process payment!

**Comment by s-alves10** [comment] 2023-11-06 22:55
@abekkala 

Offer accepted. Thanks

**Comment by abekkala** [comment] 2023-11-07 15:53
@s-alves10 payment made and contract ended - Thank you! 🎉

**Closed by abekkala** 2023-11-07 15:53 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug

**Comment by puneetlath** [comment] 2024-01-17 17:33
>Yup looks good, agree we should also make the internal changes here

@thienlnam @abekkala is this being handled somewhere?

**Comment by thienlnam** [comment] 2024-01-18 04:22
Good question, I don't remember following up with a change here.

It looks like the last conversation about that happened here https://expensify.slack.com/archives/C049HHMV9SM/p1694502825117099, @chiragsalian do you happen to remember if we made a change here?

**Comment by thienlnam** [comment] 2024-01-18 04:23
Oh, Chirag is on parental leave. Checking the BE code to see if we ended up excluding deleted parent actions from childVisibleActionCount

**Comment by thienlnam** [comment] 2024-01-18 04:30
It doesn't look like we've added it for ADD_COMMENT reportActions. Created an internal issue to keep track of that change
