### ISSUE TITLE
[HOLD for payment 2024-06-06] [HOLD #37891] Keyboard jumps around when swiping back from chat to LHN with gesture 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37923] opened 2024-03-07 19:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @vitHoracek 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709810201224169

## Action Performed:

1. Open app
2. Go to any chat
3. Tap on the composer field to keyboard open
4. Swipe from chat to LHN with gesture and leaving the keyboard open

## Expected Result:
keyboard should close

## Actual Result:
Keyboard jumps and then it gets disappeared

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b4a36e53-4a56-4990-bc7a-c0ab6eb8fa0f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment] 2024-03-11 11:15
Can't reproduce this one on the latest (`v1.4.50-0`). 

Asking @mountiny to retry here: https://expensify.slack.com/archives/C049HHMV9SM/p1710155707974309?thread_ts=1709810201.224169&cid=C049HHMV9SM

**Comment by mountiny** [comment] 2024-03-11 14:25
Noted in the Slack thread, I can still repro, it did not happen the first time but then consequently it happened reliably https://expensify.slack.com/archives/C049HHMV9SM/p1710155707974309?thread_ts=1709810201.224169&cid=C049HHMV9SM

cc @kirillzyusko

**Comment by kirillzyusko** [comment] 2024-03-11 14:44
@mountiny should be fixed in https://github.com/Expensify/App/pull/37891 I believe? 👀

**Comment by mountiny** [comment] 2024-03-11 17:01
Yep, cannot repro 🎉 putting this on hold for the PR
https://github.com/Expensify/App/assets/36083550/925c8c62-8a3d-4bea-bb99-039825d48c8d

**Comment by mountiny** [comment] 2024-04-08 13:31
This should hopefully be fixed wiht the native stack after the fabric branch is merged

**Comment by kirillzyusko** [comment] 2024-05-16 10:08
@mountiny I actually discovered an actual fix that should fix this problem - https://github.com/Expensify/App/pull/42257

May I kindly ask you to have a look on it? 👀

**Comment by mountiny** [comment] 2024-05-16 11:07
Amazing

**Comment by trjExpensify** [comment] 2024-06-07 16:11
👋 checklist please!

**Comment by mountiny** [comment] 2024-06-10 08:47
I dont think this requires a regression test. This is coming from when the bottom navigation was added and we have removed one prop that resolved the keyboard issue.

I think this is good to be paid out to @s77rt  $250 for their review and help

**Comment by trjExpensify** [comment] 2024-06-10 13:49
Okay! Payment summary as follows: 

- @s77rt $250 for the C+ review of the PR 

Offer sent!

**Comment by s77rt** [comment] 2024-06-10 16:57
@trjExpensify Accepted! Thanks!

**Comment by trjExpensify** [comment] 2024-06-11 00:07
Paid!

**Closed by trjExpensify** 2024-06-11 00:07 UTC
Labels: Daily, Awaiting Payment, Bug

**Comment by s77rt** [comment] 2024-10-09 01:05
False positive ^

**Comment by s77rt** [comment] 2024-10-15 09:31
The checklist above ^ is unrelated. Also https://github.com/Expensify/App/issues/37923#issuecomment-2157736424
