### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] Workspace switcher search bar is in the wrong place

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#40826] opened 2024-04-23 20:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**v1.4.64-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps
1. Add enough workspaces so the search in the workspace switcher is visible(8+)
2. Open the workspace switcher

## Expected Result:
Describe what you think should've happened
The search bar should be below the workspaces title
![image](https://github.com/Expensify/App/assets/5201282/7cd9d958-2536-4cb2-8414-a2c1925e5f1d)

## Actual Result:
Describe what actually happened
Search bar is below `Choose workspace`

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
<img width="2672" alt="image" src="https://github.com/Expensify/App/assets/5201282/13fbe433-1fd0-4c55-9e4c-841e68c5604a">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f05cea763c8e597d</li>
        <li>Upwork Job ID: 1782868524583206912</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by Delgee** [comment] 2024-04-24 17:19
Contributor details
Your Expensify account email: stormrage0527@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/delgee

**Comment by getusha** [comment] 2024-05-22 18:14
PR is under review.

**Comment by JmillsExpensify** [comment] 2024-06-22 17:16
Payment summary: 

 - Contributor: @Krishna2323 $250
 - Contributor+: @getusha

**Comment by JmillsExpensify** [comment] 2024-06-22 17:18
I've paid out @Krishna2323. @getusha Mind filling out the BZ checklist above, and additionally, can you prefer if you'll be paid via Upwork or NewDot?

**Comment by getusha** [comment] 2024-06-23 10:17
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@getusha] The PR that introduced the bug has been identified. Link to the PR: **N/a this is a feature request**
 [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/a**
 [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/a**
 [@getusha] Determine if we should create a regression test for this bug: **I don't think we need a regression test for this, as it is not something that will be accidentally affected unless there is intentional UI design change.**
 [@getusha] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/a**

**Comment by getusha** [comment] 2024-06-23 10:18
> I've paid out @Krishna2323. @getusha Mind filling out the BZ checklist above, and additionally, can you confirm if you'll be paid via Upwork or NewDot?

newDot, i just requested. thanks!

**Comment by mallenexpensify** [comment] 2024-06-24 15:37
@getusha , the job was created as a milestone in Upwork so it's been auto-paid. The hire date was before your cutoff date too, can you please rescind your offer request for payment via NewDot?

Contributor: @Krishna2323 paid $250 via Upwork
Contributor+: @getusha paid $250 via Upwork

**Comment by JmillsExpensify** [comment] 2024-06-24 16:23
$250 approved for @getusha

**Comment by getusha** [comment] 2024-06-24 18:54
>@getusha , the job was created as a milestone in Upwork so it's been auto-paid. The hire date was before your cutoff date too, can you please rescind your offer request for payment via NewDot?

@mallenexpensify apologies for the delay, just refunded the amount on UW

![Screenshot 2024-06-24 at 9 53 32 at night](https://github.com/Expensify/App/assets/75031127/ffbeab22-f3f8-443b-b9fc-f203650348fc)

**Comment by JmillsExpensify** [comment] 2024-06-25 03:50
I think we're good here now.

**Comment by mallenexpensify** [comment] 2024-06-26 01:25
> The hire date was before your cutoff date too, can you please rescind your offer request for payment via NewDot?

@getusha we need to pay via Upwork here because you were assigned here before 5/9, your eligible date. Can you please rescind your NewDot payment request and accept this new job I created? Thx
https://www.upwork.com/jobs/~01d662b6ac617b4224

**Comment by getusha** [comment] 2024-06-27 15:42
> @getusha we need to pay via Upwork here because you were assigned here before 5/9, your eligible date. Can you please rescind your NewDot payment request and accept this new job I created? Thx

@mallenexpensify is there a way to refund the ND payment?

**Comment by mallenexpensify** [comment] 2024-06-28 01:43
If you've already been paid via NewDot for this, let's not complicate things with a refund.  Both you and I are assigned to [this issue](https://github.com/Expensify/App/issues/43920), I'll comment there that payment is already made and link to here (assuming it's $250).  Also.. let's consider this an edge case, it should not be used as a reference in the future :)

**Comment by mallenexpensify** [comment] 2024-06-28 01:46
d'oh, looks like you haven't accepted the job in Upwork, can you plz @getusha ?
https://www.upwork.com/jobs/~01d662b6ac617b4224

**Comment by getusha** [comment] 2024-06-28 06:43
>d'oh, looks like you haven't accepted the job in Upwork, can you plz @getusha ?

Accepted. thank you!

**Comment by mallenexpensify** [comment] 2024-06-28 16:33
Paid, thanks @getusha 
Payment confirmation is [correct above](https://github.com/Expensify/App/issues/40826#issuecomment-2186864530)

**Closed by mallenexpensify** 2024-06-28 16:33 UTC
Labels: External, Daily, Awaiting Payment, Bug
