### ISSUE TITLE
[$500] Android - User land to LHN instead of last chat conversation after close the app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28844] opened 2023-10-04 17:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login in NewDot
2. Receive the notification
3. Tap on notification 9you will land to DM) 
4. Close the app by swiping it up on Android to kill the process
5. Open the app again

## Expected Result:
User should land to the last open chat conversation instead of LHN

## Actual Result:
User land to LHN instead of last chat conversation after close the app

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.77.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8f94b714-8472-4358-8a46-9e016e011adc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1696266288909289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e651f821abc26b7e</li>
        <li>Upwork Job ID: 1709617776124280832</li>
        <li>Last Price Increase: 2023-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27258740</li>
</ul></li>
    </ul>
</details>

**Comment by LovelyXinf** [comment] 2023-10-04 17:34
Dear Expensify Team,

I am thrilled to have the opportunity to submit a proposal for the migration-related issue outlined in GitHub issue #28844. As an experienced React Native developer, I am confident that I can contribute to the unification of your front-end across platforms and solve the problems you are facing.

Proposal:
In my proposal, I will provide a technical explanation of the changes required to fix the issue mentioned in GitHub issue #28844. I understand the importance of delivering a reliable and secure system for processing financial transactions, which aligns with Expensify's goal of maintaining its reputation as an innovative leader in the finance industry. While I won't be able to submit the final code along with the proposal, I will outline the steps and approach I would take to address the problem effectively.

Review and Acceptance:
Once my proposal is reviewed and accepted by your team, I will post the proposal on Upwork as per your instructions. Upon acceptance on Upwork and my agreement to take on the job, I will then proceed with implementing the solution.

Code Submission:
After accepting the offer on Upwork, I will create a fork of your codebase from the Expensify/App GitHub repository. From there, I will create a branch to develop and test the necessary changes for the migration issue. Once the code is ready for review, I will submit a pull request to merge the changes into your codebase. I will ensure to include detailed documentation, screenshots, and confirmation that I have thoroughly tested the pull request on all supported platforms.

Contributor Guidelines:
Before submitting my proposal, I will carefully review your Contributor Guidelines located in CONTRIBUTING.md. It is important to me to adhere to your guidelines and expectations while working on this project.

Payment Timelines:
I acknowledge the payment amounts and timelines outlined in your CONTRIBUTING.md file. I understand that the amount of payment is variable and depends on when the pull request is merged and any potential regressions caused by my work. I commit to delivering high-quality code within the specified timelines to avoid penalties or contract termination.

Thank you for considering my proposal. I am excited about the opportunity to contribute to Expensify's success and help in unifying your front-end across platforms. Should you have any questions or require further clarification, please do not hesitate to reach out.

Best regards,
[Your Name]

**Comment by LovelyXinf** [comment] 2023-10-04 17:34
Dear Expensify Team,

I am thrilled to have the opportunity to submit a proposal for the migration-related issue outlined in GitHub issue #28844. As an experienced React Native developer, I am confident that I can contribute to the unification of your front-end across platforms and solve the problems you are facing.

Proposal:
In my proposal, I will provide a technical explanation of the changes required to fix the issue mentioned in GitHub issue #28844. I understand the importance of delivering a reliable and secure system for processing financial transactions, which aligns with Expensify's goal of maintaining its reputation as an innovative leader in the finance industry. While I won't be able to submit the final code along with the proposal, I will outline the steps and approach I would take to address the problem effectively.

Review and Acceptance:
Once my proposal is reviewed and accepted by your team, I will post the proposal on Upwork as per your instructions. Upon acceptance on Upwork and my agreement to take on the job, I will then proceed with implementing the solution.

Code Submission:
After accepting the offer on Upwork, I will create a fork of your codebase from the Expensify/App GitHub repository. From there, I will create a branch to develop and test the necessary changes for the migration issue. Once the code is ready for review, I will submit a pull request to merge the changes into your codebase. I will ensure to include detailed documentation, screenshots, and confirmation that I have thoroughly tested the pull request on all supported platforms.

Contributor Guidelines:
Before submitting my proposal, I will carefully review your Contributor Guidelines located in CONTRIBUTING.md. It is important to me to adhere to your guidelines and expectations while working on this project.

Payment Timelines:
I acknowledge the payment amounts and timelines outlined in your CONTRIBUTING.md file. I understand that the amount of payment is variable and depends on when the pull request is merged and any potential regressions caused by my work. I commit to delivering high-quality code within the specified timelines to avoid penalties or contract termination.

Thank you for considering my proposal. I am excited about the opportunity to contribute to Expensify's success and help in unifying your front-end across platforms. Should you have any questions or require further clarification, please do not hesitate to reach out.

Best regards,
Lucas

**Comment by zahid0162** [comment] 2023-10-04 20:04
Hi, I have a suggestion to fix this issue, we can save the last state of the app in the Shared Preferences e.g the last screen open when user click on the notification. After user kill the app and reopen it, we will get the saved state of app and then we will add check on it at the splash screen and will jump on the specific screen accordingly.

**Comment by zahid0162** [comment] 2023-10-04 20:21
Contributor details
Your Expensify account email: zaidmuneer25@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011067442982de300d

**Comment by maxconnectAbhi** [comment] 2023-10-05 05:41
# Proposal

## Please re-state the problem that we are trying to solve in this issue
User land to LHN instead of last chat conversation after close the app

## What is the root cause of that problem?
navigation to last opened report screen feature is missing

## What changes do you think we should make in order to solve the problem?
1. Make a function on conversation screen that can set the new local Onyx key like `lastOnReportScreen:true` when app is in background.
2. Set the key `lastOnReportScreen:false` when user left the conversation screen by pressing back button / header back arrow icon.
3. Check `lastOnReportScreen` flag, if it's true, we navigate to the ROUTES.REPORT and early return.

```
if (lastOnReportScreen) {
    Navigation.navigate(ROUTES.REPORT);
    return;
}
```
like above proposal
## What alternative solutions did you explore? (Optional)
NA

**Comment by KarthickCk** [comment] 2023-10-06 04:09
**### Proposal**

**Data to store:**

- Chat id

###Storage:

- we can use shared preference or encrypted shared preference to encrypt the chat id

**Place to store:**

- Store the chat id in the chat screen
- clear the chat id in the onDestroy of the chat screen, because onDestroy wont gets triggered when your clean the app from recent apps

**Place to check:**

- On chat list screen check for the previous opened chat id from the shared preference, if its present then open the chat screen with the corresponding chat id

**Contributor details**
Upwork profile - https://www.upwork.com/freelancers/~01c7da601155f08c6b
Expensify id - karthickck0@gmail.com

**Comment by KarthickCk** [comment] 2023-10-06 04:10
Contributor details
Your Expensify account email: karthickck0@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c7da601155f08c6b

**Comment by mollfpr** [comment] 2023-10-09 04:34
@LovelyXinf @zahid0162 @KarthickCk Thank you for your interest in solving this issue. Please review our [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to understand the process better here. Keep in mind that you ALWAYS post a proposal with the [PROPOSAL_TEMPLATE.md](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) to get your proposal reviewed.

**Comment by LovelyXinf** [comment] 2023-10-09 04:42
Hello, i am David

**Comment by KarthickCk** [comment] 2023-10-09 04:50
### Proposal

### Please re-state the problem that we are trying to solve in this issue
User land to LHN instead of last chat conversation after close the app

### What is the root cause of that problem?
We are missing the state of the chat screen, as android kills the process and opens with the launcher activity again.

### What changes do you think we should make in order to solve the problem?

Data to store - Chat id

Storage - we can use shared preference or encrypted shared preference to encrypt the chat id

- Store the chat id in the chat screen and clear the chat id in the onDestroy of the chat screen, because onDestroy wont gets triggered when your clean the app from recent apps
- On chat list screen check for the previous opened chat id from the shared preference, if its present then open the chat screen with the corresponding chat id

### What alternative solutions did you explore? (Optional)
NA

**Comment by KarthickCk** [comment] 2023-10-09 04:50
Contributor details
Your Expensify account email: [karthickck0@gmail.com](mailto:karthickck0@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01c7da601155f08c6b

**Comment by mollfpr** [comment] 2023-10-09 04:52
>In [here](https://github.com/Expensify/App/blob/6d86d5aecc47096bffdfbf59dcaefcb5dd0a0509/src/pages/home/sidebar/SidebarLinks.js#L63), we should check lastOnReportScreen flag, if it's true, we navigate to the ROUTES.REPORT and early return

@dukenv0307 Why do we need an early return here? And what is the reason we navigate the user on `SidebarLinks`?

---

>Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable.

https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job

@maxconnectAbhi Please post a different proposal from the others.

**Comment by mollfpr** [comment] 2023-10-09 04:53
>Storage - we can use shared preference or encrypted shared preference to encrypt the chat id

@KarthickCk Why shared preference? Do we able to do the same with Onyx?

**Comment by KarthickCk** [comment] 2023-10-09 04:56
@mollfpr yes we can do, but shared preference is one of the android default storage mechanism, very easy to use and consider our complexity of the problem, we dont need any third party storage for this one

**Comment by maxconnectAbhi** [comment] 2023-10-09 04:57
@mollfpr  this is a React Native app , and we only use Async-storage or Onyx

**Comment by LovelyXinf** [comment] 2023-10-09 04:58
Yes, I agree.

**Comment by KarthickCk** [comment] 2023-10-09 04:59
yes, then Onyx is the best solution for storage

**Comment by LovelyXinf** [comment] 2023-10-09 05:00
Ok, thanks.

**Comment by LovelyXinf** [comment] 2023-10-09 05:05
let me know if we can contact with telegram or Skype or discord or teams

**Comment by KarthickCk** [comment] 2023-10-09 05:06
@LovelyXinf the above comment is for me?

**Comment by maxconnectAbhi** [comment] 2023-10-09 05:07
> @maxconnectAbhi Please post a different proposal from the others.


@mollfpr only 3rd point is same because we have to use early return anyways

**Comment by KarthickCk** [comment] 2023-10-09 05:11
we need to check with ios also, whether same issue is happening for the same?

**Comment by LovelyXinf** [comment] 2023-10-09 05:15
Done.

**Comment by LovelyXinf** [comment] 2023-10-09 05:15
yes, of course

**Comment by mollfpr** [comment] 2023-10-09 05:18
@LovelyXinf Please stop posting unnecessary comments on the issue!

**Comment by LovelyXinf** [comment] 2023-10-09 05:21
Ok, I will.

**Comment by flaviadefaria** [comment] 2023-10-12 10:44
@Christinadobrzyn I'm officially no longer in the BugZero team so reassigning this as it will not close until tomorrow.

**Comment by LovelyXinf** [comment] 2023-10-12 11:27
Ok, no problem.

**Comment by Christinadobrzyn** [comment] 2023-10-13 22:00
Are we reviewing proposals? @mollfpr

Let me know if you'd like to see more proposals.

**Comment by mollfpr** [comment] 2023-10-16 10:16
Sorry for the delay 🙏

The [proposal](https://github.com/Expensify/App/issues/28844#issuecomment-1747957484) from @dukenv0307 looks good to me!

🎀 👀 🎀 C+ reviewed!

@Christinadobrzyn Could you help with adding the Engineering label? Thank you!

**Comment by LovelyXinf** [comment] 2023-10-16 11:10
No problem, thank you!

**Comment by mountiny** [comment] 2023-10-18 12:53
Please raise a PR, thanks!

**Comment by mollfpr** [comment] 2023-10-20 16:15
>@mountiny @mollfpr on native, why should the app open the most recent chat?

@rushatgabhane You made me compare the behavior with WhatsApp 😄. WhatsApp doesn't show the latest opened chat after you killed the app.

I tried to find the reason but couldn't find the Slack thread for this reported issue.

>This is a feature request. I don't think we should proceed without a problem solution statement.
What do you think?

Yes, this is a feature request. Do you mean without a proposal?

cc @mountiny

---

> The issue is resolved by the PR, but it still has a bug that might affect the redirection when the user opens the app(Please note that the bug is not coming from my code changes )

@dukenv0307 Is this affecting the result of the PR?

**Comment by LovelyXinf** [comment] 2023-10-20 16:31
Yes, I agree.

**Comment by mountiny** [comment] 2023-10-20 16:55
I am not an android user myself so yeah I agree on getting agreement on the behaviour. From ios perspective it seems life to me to open LHN after closing the App.

Could you make a post in open source channel please to discuss

**Comment by LovelyXinf** [comment] 2023-10-20 18:38
Sure, no problem.

**Comment by mountiny** [comment] 2023-10-23 15:47
cc @Julesssss could you please help, I am thinking of closeing this issue as I thin it makes sense the app opens in LHN after closing it

**Comment by Julesssss** [comment] 2023-10-23 15:52
Yeah no worries, I put this at the top of my list to triage tomorrow.

**Comment by LovelyXinf** [comment] 2023-10-23 16:02
That would be great, thanks!

**Comment by Julesssss** [comment] 2023-10-24 07:50
> User should land to the last open chat conversation instead of LHN

Yeah, this is the same for Android. If the user or OS kills the app we should land on the top level page again (LHN).

**Comment by mollfpr** [comment] 2023-10-24 08:29
@mountiny @Christinadobrzyn Are this issue will be compensated? Since we already assigned the contributor and @dukenv0307 is ready for the PR.

**Comment by mountiny** [comment] 2023-10-25 21:35
Ok this was a mistaek on our behalf and we should have caught it before, lets pay 25% so $125 to @mollfpr and @dukenv0307 for their efforts here but no reporting bonus as its not a valid bug

**Comment by mountiny** [comment] 2023-10-28 13:26
Alright @Christinadobrzyn could you process this payment as full payment and no bonus hence $500

**Comment by LovelyXinf** [comment] 2023-10-28 17:12
Sure, no problem.

**Comment by Christinadobrzyn** [comment] 2023-10-30 02:19
Okay, can you double-check this payment structure is correct @mountiny @mollfpr 

Payouts due:

Issue Reporter: NA
Contributor: $500 @dukenv0307 (in Upwork)
Contributor+: $500 @mollfpr (in Upwork)

Eligible for 50% #urgency bonus? N - based on https://github.com/Expensify/App/issues/28844#issuecomment-1783809931

Upwork job is [here](https://www.upwork.com/jobs/~01e651f821abc26b7e).

**Comment by mollfpr** [comment] 2023-10-30 02:28
@Christinadobrzyn I'll do manual request in NewDot, thank you!

**Comment by mountiny** [comment] 2023-10-30 10:23
sounds good to me

**Comment by Christinadobrzyn** [comment] 2023-10-30 15:25
Thanks, paid this out based on this payment structure - https://github.com/Expensify/App/issues/28844#issuecomment-1784373465

Closing this as complete, please feel free to reach out with any questions

**Closed by Christinadobrzyn** 2023-10-30 15:25 UTC
Labels: External, Engineering, Daily, Bug

**Comment by JmillsExpensify** [comment] 2023-11-01 20:11
$500 payment approved for @mollfpr based on [this summary](https://github.com/Expensify/App/issues/28844#issuecomment-1784373465).
