### ISSUE TITLE
[$500] Android - BA - After tapping disconnect BA, in wallet section BA is not removed 

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39355] opened 2024-04-01 12:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4466759
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login app
2. Add a bank account using chase ending 1111
3. Tap disconnect Bank account and delete bank account
4. Navigate to settings---- wallet
5. Note Bank account is shown and not deleted
6. Again navigate to connect BA page
7. Tap connect manually
8. Enter route number and account number
9. Tap next and then tap confirm

## Expected Result:
After tapping disconnect BA, in wallet section BA must not be shown. The deleted bank account must not be shown when tap confirm (after entering details in connect manually page.)

## Actual Result:
After tapping disconnect BA, in wallet section BA is not removed .The deleted bank account is shown when tap confirm (after entering details in connect manually page.)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/273d0a7f-e6fd-49bc-add5-bd445ba17023

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01801c400ba36cbd72</li>
        <li>Upwork Job ID: 1774830276732727296</li>
        <li>Last Price Increase: 2024-04-08</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-01 12:56
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by DylanDylann** [comment] 2024-04-08 06:40
@GandalfGwaihir I still can't connect the bank account. Could you connect the bank account successfully? If yes, could you share a video?

**Comment by nkdengineer** [comment] 2024-04-15 09:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After tapping disconnect BA, in wallet section BA is not removed .The deleted bank account is shown when tap confirm (after entering details in connect manually page.)

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/2ce785c7c0831c9a6857f4a197cada6da28736e3/src/pages/workspace/WorkspaceResetBankAccountModal.tsx#L52

When clicking on "Disconnect bank account" we only reset `achData` from ONYX and we don't remove `bankAccountID` from `bankAccountList`. In the Wallet Page we are using `bankAccountList` to display bank account

### What changes do you think we should make in order to solve the problem?
In here
https://github.com/Expensify/App/blob/2ce785c7c0831c9a6857f4a197cada6da28736e3/src/pages/workspace/WorkspaceResetBankAccountModal.tsx#L52

Besides, removing achData from ONYX, we also should update `bankAccountList` like this

```
onConfirm={() => {
                BankAccounts.resetFreePlanBankAccount(bankAccountID, session, achData?.policyID ?? '', user)
                if (bankAccountID) {
                    BankAccounts.deletePaymentBankAccount(bankAccountID)
                }
}}
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-04-15 09:54
@DylanDylann Please follow [these step](https://expensify.slack.com/archives/C01GTK53T8Q/p1711049879962529) to add bank account. Make sure that you use the correct data is provided in this thread

**Comment by DylanDylann** [comment] 2024-04-15 13:41
@nkdengineer's proposal is clearer and easier to understand with the correct reference. But your idea is the same as @GandalfGwaihir's proposal. Thus, I suggest we should go with @GandalfGwaihir's [proposal](https://github.com/Expensify/App/issues/39355#issuecomment-2029815993) because his proposal is the first one

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-04-17 05:01
Waiting for a review from @puneetlath

**Comment by puneetlath** [comment] 2024-04-22 15:32
Wait, I realize I approved this proposal, but now that I'm reviewing the PR, I don't think this is actually a bug. Disconnecting a bank account from the workspace doesn't mean it should be removed from your wallet. It just means it should no longer be tied to that workspace. I'm going to close this out, but will still pay out since I approved the proposal and the work was done. 

@GandalfGwaihir can you close your PR?

**Comment by puneetlath** [comment] 2024-04-26 14:46
Paid, thanks for the bump.

**Closed by puneetlath** 2024-04-26 14:46 UTC
Labels: Reviewing, External, Weekly, Bug
