### ISSUE TITLE
[$250] Web - Track Expense - Track amount remains on LHN when IOU is removed from self-DM

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43570] opened 2024-06-12 13:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4621293&group_by=cases:section_id&group_id=309130&group_order=asc
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. In OldDot - Create an unreported transaction
2. Verify that it shows up on the self-DM on NewDot
3. In OldDot - add the transaction to a report
4. Check LHN when transaction is removed from the self-DM ( navigate to other chat or refresh the page)

## Expected Result:
Track amount should disappear from LHN and This is your personal space should be present

## Actual Result:
Track amount remains on LHN when IOU is removed from self-DM even user refresh the page. Track amount disappears onlywhen user navigate back to self-DM chat

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/2bfbb6d6-32fc-460d-abd1-0ad7f72ce53f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01018dafbf768a7c7c</li>
        <li>Upwork Job ID: 1800920342613338963</li>
        <li>Last Price Increase: 2024-06-12</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-06-12 13:45
@sakluger FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-12 13:46
We think that this bug might be related to #vip-vsb

**Comment by Gonals** [comment] 2024-06-12 15:58
I think this can be fixed externally. 
We don't really need to block deploy on this, though

**Comment by b4s36t4** [comment] 2024-06-13 15:49
> Verify that it shows up on the self-DM on NewDot

This is not happening for me, any help @Gonals

**Comment by sakluger** [comment] 2024-06-17 18:55
@b4s36t4 - just to confirm, you created an unreported transaction in OldDot, then opened your self-DM in NewDot, and the new transaction is not showing up in your self-DM?

**Comment by b4s36t4** [comment] 2024-06-18 02:01
Yes.

**Comment by sakluger** [comment] 2024-06-18 17:44
I also can't reproduce the issue, but experienced another bug.

1. I created an unreported transaction in OldDot

<img width="1286" alt="image" src="https://github.com/Expensify/App/assets/5997400/a4e82bd3-af56-48c8-8e0b-67a2498b8b83">

2. I opened my self-DM in NewDot. **Result:** The expense shows up but with the skeleton loader, no details are inside.

<img width="930" alt="image" src="https://github.com/Expensify/App/assets/5997400/68e6908b-3141-4374-942f-012d49a2585e">

5. I click on the expense skeleton, but all the details are missing

<img width="927" alt="image" src="https://github.com/Expensify/App/assets/5997400/2bef92b7-d2cc-4773-8e5e-8b5ac1bb65df">

**Comment by sakluger** [comment] 2024-06-18 17:44
I'm going to close this as unreproducible and report the other issue.

**Closed by sakluger** 2024-06-18 17:44 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
