### ISSUE TITLE
[$1000] The preview message does not use all available width when the screen size is around 750px

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18493] opened 2023-05-05 18:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with a new account
2. Keep the screen-size around 750px
3. See concierge message

## Expected Result: 
The available width is fully utilised by the preview message.
## Actual Result : 
Width is not fully utilised by the preview message.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.10
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![4](https://user-images.githubusercontent.com/43996225/236541773-83bd7fd8-8cc9-4bfa-b88c-54a4c222bd15.png)
![image](https://user-images.githubusercontent.com/43996225/236541778-0f092f81-9267-49e8-90cf-60c9511ab9d1.png)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683227454544079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011fc86884e30a2d17</li>
        <li>Upwork Job ID: 1655603876475715584</li>
        <li>Last Price Increase: 2023-05-08</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-05-08 16:01
Reproduced

**Comment by deetergp** [comment] 2023-05-09 00:57
It probably makes more sense to do it on the backend since that's where we are truncating it down to 80 chars. We can diff the original message against the truncated message and if the latter is shorter, we can add a single ellipse (…) character to it.

**Comment by deetergp** [comment] 2023-05-11 21:31
I just put up a back end PR for this one.

**Comment by deetergp** [comment] 2023-05-22 17:10
The related PR has been deployed to production so we can now close this GH.

**Comment by bfitzexpensify** [comment] 2023-09-06 06:57
Ok, all sorted!

**Closed by bfitzexpensify** 2023-09-06 06:57 UTC
Labels: Daily, Internal, Bug
