### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] Chat - App crash when reply in thread image

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29446] opened 2023-10-12 13:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev 1.3.83.1
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697117854435399

## Action Performed:
1. Open any chat
2. Send an image
3. Hover on image and click reply in thread

## Expected Result:
App does not crash

## Actual Result:
App crash

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/ca0395e2-4546-4400-b3a9-cf6c7758714e

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/8364d433-2ce9-49b4-abc6-4789b0d1d896

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015aaed14521ed9d68</li>
        <li>Upwork Job ID: 1712468082854531072</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 27162314</li>
<li>namhihi237 | Reporter | 27162317</li>
<li>s77rt | Contributor | 27162338</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-10-12 14:45
cc: @teneeto @s77rt

**Comment by ikevin127** [comment] 2023-10-12 14:50
The issue is a regression from PR: https://github.com/Expensify/App/pull/29134

# Proposal

## Please re-state the problem that we are trying to solve in this issue
App should not crash when reply in thread is clicked on an attachment.

## What is the root cause of that problem?
The issue seems to be caused by the `chooseBoundingBox` function which might not always return a value i.e., it returns `undefined` when the condition within the `for` loop is not met. This results in `betterBounds` being `undefined` inside `updateBounds` function, leading to the crash.

https://github.com/Expensify/App/blob/f942acd2c87d3babcdb6fb83f19e8dc02518efc8/src/components/Tooltip/BaseTooltip.js#L44-L55

## What changes do you think we should make in order to solve the problem?
Adding a condition to check if `betterBounds` of `updateBounds` function is indeed not `undefined` before performing operations on it:

```diff
    const updateBounds = (bounds) => {
        if (bounds.width === 0) {
            setIsRendered(false);
        }
        // Choose a bounding box for the tooltip to target.
        // In the case when the target is a link that has wrapped onto
        // multiple lines, we want to show the tooltip over the part
        // of the link that the user is hovering over.
        const betterBounds = chooseBoundingBox(target.current, initialMousePosition.current.x, initialMousePosition.current.y);
+       if (betterBounds) {
            setWrapperWidth(betterBounds.width);
            setWrapperHeight(betterBounds.height);
            setXOffset(betterBounds.x);
            setYOffset(betterBounds.y);
+       }
    };
```

## What alternative solutions did you explore? (Optional)
Ensuring that `chooseBoundingBox` always returns a value, even a default one like so:

```diff
function chooseBoundingBox(target, clientX, clientY) {
    const slop = 5;
    const bbs = target.getClientRects();
    const clientXMin = clientX - slop;
    const clientXMax = clientX + slop;
    const clientYMin = clientY - slop;
    const clientYMax = clientY + slop;

    for (let i = 0; i < bbs.length; i++) {
        const bb = bbs[i];
        if (clientXMin <= bb.right && clientXMax >= bb.left && clientYMin <= bb.bottom && clientYMax >= bb.top) {
            return bb;
        }
    }

    // If no matching bounding box is found, fall back to the first one.
    // This could only happen if the user is moving the mouse very quickly
    // and they got it outside our slop above.
+   // or fallback to 0 values if no bounding box is found
-   return bbs[0];
+   return bbs[0] || { top: 0, left: 0, right: 0, bottom: 0, width: 0, height: 0 };
}
```

### Videos:


<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/56457735/ec52984b-5aa9-4fe9-877b-cc1fc1a59585

</details>

**Comment by mountiny** [comment] 2023-10-12 15:30
@teneeto will handle this as an author of the PR

**Comment by s77rt** [comment] 2023-10-12 15:31
@mountiny Assign me as well

**Comment by mountiny** [comment] 2023-10-12 15:31
How do you see these so fast 🤯

**Comment by mountiny** [comment] 2023-10-13 09:01
Merged it, thanks!

**Comment by mountiny** [comment] 2023-10-13 09:02
Only need to pay the reporter so that is $50 to @namhihi237

**Comment by s77rt** [comment] 2023-10-17 00:00
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/29134
- The offending PR has been commented on: https://github.com/Expensify/App/pull/29134#discussion_r1357253061
- A discussion in #expensify-bugs has been started: Not needed. Typescript migration should help prevent such bugs
- Determine if we should create a regression test for this bug: No

**Comment by CortneyOfstad** [comment] 2023-10-18 19:25
I am going to be OoO when this needs to be paid, so reassigning the BZ label 👍 

## Payment Summary

- @namhihi237 to be paid $50 in Upwork as Bug Reporter
- @s77rt to be paid $500 in Upwork (pending any regressions) as Contributor
- @teneeto does not require payment in Upwork as C+

**Comment by laurenreidexpensify** [comment] 2023-10-23 10:11
## Payment Summary

- @namhihi237 - paid $50 in Upwork as Bug Reporter
- @teneeto does not require payment in Upwork - expert contributor
- @s77rt to be paid $500 in Upwork - please apply to job

**Comment by s77rt** [comment] 2023-10-23 19:16
@laurenreidexpensify This is a regression. We only need to pay the bug reporter here. This can be closed.

**Closed** 2023-10-24 10:51 UTC
Labels: External, Daily, Awaiting Payment, Bug
