### ISSUE TITLE
[waiting for payment][$250] Share code- QR code expands to full size after opening for WS rooms, tasks and threads

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44436] opened 2024-06-26 09:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4675372
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app and log in
2. Navigate to any task, thread or a workspace room
3. Tap the header and select Share

## Expected Result:
The QR code is displayed fully

## Actual Result:
The QR code is displayed small briefly and expands to the full size

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/91c91457-a976-4e4d-a368-05544fcacbb0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0a4dbc404a8ab34</li>
        <li>Upwork Job ID: 1805949354249394574</li>
        <li>Last Price Increase: 2024-07-10</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103091801</li>
<li>huult | Contributor | 103091804</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by izarutskaya** [comment] 2024-06-26 09:43
@adelekennedy I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-06-26 09:43
We think this issue might be related to the #vip-vsb

**Comment by huult** [comment] 2024-06-26 10:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
QRCode change size after layout change

### What is the root cause of that problem?
Default QR code [size](https://github.com/Expensify/App/blob/224f09edbb511bd179d79c55f646d5522c1f955d/src/components/QRShare/index.tsx#L52) is 100px, after layout change the QR code recalculate size at this line

https://github.com/Expensify/App/blob/224f09edbb511bd179d79c55f646d5522c1f955d/src/components/QRShare/index.tsx#L32

so the UI will update size
### What changes do you think we should make in order to solve the problem?
We have to set the default initial height for qrcode size at this line

https://github.com/Expensify/App/blob/224f09edbb511bd179d79c55f646d5522c1f955d/src/components/QRShare/index.tsx#L19


### What alternative solutions did you explore? (Optional)

**Comment by Sparth19** [comment] 2024-06-26 12:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- The QR code is initially displayed briefly in a small size before expanding to full size.

### What is the root cause of that problem?

- The initial value of `qrCodeSize` is [undefined](https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/components/QRShare/index.tsx#L19), so it defaults to [120](https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/components/QRCode.tsx#L44). 

- It is displayed at this size initially, and then adjusts based on `onLayout` changes.
https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/components/QRShare/index.tsx#L30-L33

### What changes do you think we should make in order to solve the problem?

- we can use a Loader While onLayout is Calculating the Size.
- This will ensure that the QR code is displayed at the correct size from the beginning and avoids any brief display of an incorrectly sized QR code or resizing issues in any device sizes.

    
           {qrCodeSize ? (
                <QRCode
                    getRef={(svg) => (svgRef.current = svg)}
                    url={url}
                    logo={logo}
                    size={qrCodeSize}
                    logoRatio={logoRatio}
                    logoMarginRatio={logoMarginRatio}
                />
            ) : (
                <ActivityIndicator
                    color={theme.spinner}
                    size="large"
                />
            )}

### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2024-07-03 10:32
Thank you for your proposal @huult. This issue is also happening on ios app. So I don't think writing platform specific code is a good idea

**Comment by alitoshmatov** [comment] 2024-07-03 10:33
Thank you for your proposal @Sparth19 , QR codes are readily available data showing loader just for fixing its layout seems a workaround

**Comment by huult** [comment] 2024-07-03 13:14
@alitoshmatov My proposal is not focused on Android only, so I wrote a note below the code: `! we have to separate to specific platform and calculate based on that`. My proposal covers both Android and iOS by applying `index.native.ts` because mobile uses a fixed size, while the web uses the response size

**Comment by huult** [comment] 2024-07-06 07:42
### [Proposal updated](https://github.com/Expensify/App/issues/44436#issuecomment-2191349072)

>  Thank you for your proposal @huult. This issue is also happening on ios app. So I don't think writing platform specific code is a good idea

Hi @alitoshmatov , I have updated some proposals and explained why we used them. Can you check it again? Thank you.

For mobile devices, the screen width is fixed. We can get the device width using `Dimensions.get('screen').width`, and then calculate the QR code size based on this container's padding. 

For other devices, we use a fixed sidebar width of [375px](https://github.com/huult/App/blob/44436-qr-code-expands/src/styles/variables.ts#L98), and we can calculate the initial QR code size based on this width

Here is [test branch](https://github.com/huult/App/tree/44436-qr-code-expands)

**Comment by alitoshmatov** [comment] 2024-07-06 22:09
Most of the time `onLayout` function working in an instant, I guess it is an issue only in slower devices. 

@truph01 We cannot use `Dimensions.get` directly, there is a `useWindowDimensions` hook for that. For your solution to be viable, we should prove that that window width is always equal to [`event.nativeEvent.layout.width`](https://github.com/Expensify/App/blob/224f09edbb511bd179d79c55f646d5522c1f955d/src/components/QRShare/index.tsx#L30-L33) to prevent size changes

**Comment by huult** [comment] 2024-07-07 06:14
### [Proposal Updated](https://github.com/Expensify/App/issues/44436#issuecomment-2191349072)

> @truph01 We cannot use Dimensions.get directly, there is a useWindowDimensions hook for that. For your solution to be viable, we should prove that that window width is always equal to [event.nativeEvent.layout.width](https://github.com/Expensify/App/blob/224f09edbb511bd179d79c55f646d5522c1f955d/src/components/QRShare/index.tsx#L30-L33) to prevent size changes

@alitoshmatov I used the `useWindowDimensions` hook instead of directly using `Dimensions.get` to prevent size changes. Thank you.

Here is [test branch](https://github.com/huult/App/tree/44436-qr-code-expands)

**Comment by huult** [comment] 2024-07-08 03:18
@alitoshmatov I think [this proposal](https://github.com/Expensify/App/issues/44436#issuecomment-2212415320) duplicates my proposal. It still uses the initial container width to calculate the QR size after removing padding.

**Comment by danieldoglas** [comment] 2024-07-10 11:07
bump @alitoshmatov

**Comment by alitoshmatov** [comment] 2024-07-10 19:34
@truph01 Although @dominictb 's proposal looks similar to yours(even maybe inspired by yours), I do think they made a much needed improvement here. Calculating and passing qr code width in parent container and using `isSmallScreenWidth` rather then platform specific code is substantial difference in my opinion.

**Comment by truph01** [comment] 2024-07-10 19:36
@alitoshmatov Sorry, any mistake here? I see you tagged me in this issue.

**Comment by alitoshmatov** [comment] 2024-07-10 19:37
Sorry for inconvenience, @truph01 Right, I didn't mean to. Yes you can ignore this

**Comment by alitoshmatov** [comment] 2024-07-10 19:39
I think we can go with @dominictb 's [proposal](https://github.com/Expensify/App/issues/44436#issuecomment-2212415320) which is similar to or even derived from  @huult  's [proposal](https://github.com/Expensify/App/issues/44436#issuecomment-2191349072). 

I am not sure about my judgement here, if we look on each proposal separately, @dominictb 's proposal would definitely be the one. But considering @huult was working on their proposal and giving much needed direction I am in doubt here. Would love to hear your take on this one

C+ reviewed 🎀 👀 🎀

**Comment by huult** [comment] 2024-07-11 02:25
@alitoshmatov @danieldoglas My proposal will be provided as soon as possible and will still cover the issue. Regarding`isSmallScreenWidth` or`isMobile`, these are condition checks to detect the container if they want to cover the screen size of other devices, which can be updated during code review or while creating a pull request. As I checked the contributor rules and found item 6 of [proposal for the job](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job) then other proposal should diferent MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable. If other proposal not used inital  container with after remove padding to resolve this issue then it's ok.

**Comment by danieldoglas** [comment] 2024-07-12 11:08
OK, I think we'll go with @huult's proposal. I agree that there are some differences between them, but I think @dominictb's proposal derived from the @huult's and we can address the smaller changes in the PR.

**Comment by danieldoglas** [comment] 2024-07-12 15:41
Assigning @mountiny to see the end of this while I'm OOO

**Comment by mountiny** [comment] 2024-07-12 15:52
@dominictb I understand your concern, and I am sorry that this time, it did not work out. I think both of you and your solutions will work, and they are similar, so @huult should go ahead, as their proposal came in first.

@huult what is your ETA for the PR?

**Comment by huult** [comment] 2024-07-12 15:57
I will create the pull requests soon. The ETA is the next day. Thank you.

**Comment by huult** [comment] 2024-07-13 12:08
here is my [PR](https://github.com/Expensify/App/pull/45373)

**Comment by huult** [comment] 2024-07-31 15:53
Hi @mountiny , @danieldoglas , My [PR](https://github.com/Expensify/App/pull/45373#issuecomment-2240044108) was merged to production a week ago, but I noticed the Mevin bot isn't working as expected compared to other tickets I've worked on. Can I ask if this ticket is currently able to process a payment?
Thank you!

**Comment by adelekennedy** [comment] 2024-08-01 22:35
ty @danieldoglas  let me handle payment now:

Payouts due:

- [ ] Contributor: $250 @huult 
- [ ] Contributor+: $250 @alitoshmatov 

Upwork job is [here](https://www.upwork.com/jobs/~01e0a4dbc404a8ab34).

**Comment by adelekennedy** [comment] 2024-08-01 22:36
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by adelekennedy** [comment] 2024-08-07 19:39
@alitoshmatov checklist above when you get a chance!

**Comment by alitoshmatov** [comment] 2024-08-10 06:11
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/32690
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/32690/files#r1712561692
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug.

**Regression Test Proposal**
1. Open the app and log in.
2. Navigate to any task, thread, or workspace room.
3. Tap the header to open the details and select "Share".
4. Verify that the QR code is displayed in full size and not changing its size while page is opening.

Do we agree 👍 or 👎

**Closed** 2024-08-12 21:33 UTC
Labels: External, Engineering, Daily, Overdue, Bug
