### ISSUE TITLE
[HOLD for payment 2022-11-24] [$500] Bug: mWeb - Firefox - when you open a picker for the first time the popover blinks reported by @thesahindia 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11852] opened 2022-10-14 16:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open ND in Firefox browser on mobile
2. Navigate to preferences
3. Tap on priority mode

## Expected Result:
The popover shouldn't blink

## Actual Result:
The popover blinks

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web - Firefox

**Version Number:** 1.2.15-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195895977-f04c4403-0602-4b4e-9bda-a3ea088990a9.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665696058044339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/195896014-14068e4a-1dfd-474d-80c5-f9f1a433d524.mp4

**Comment by mallenexpensify** [comment] 2022-10-14 23:35
@thesahindia , before moving on to Engineering, do you happen to know if this affects other browsers or platforms?

**Comment by thesahindia** [comment] 2022-10-15 04:34
I was only able to repro this at firefox mobile browser (at Android)

**Comment by mallenexpensify** [comment] 2022-10-20 21:51
@roryabraham can you see if you can repro when you get a chance?

**Comment by roryabraham** [comment] 2022-10-20 23:59
I think I was able to reproduce this on Android Firefox, though it's not as dramatic as what was in the OP:

https://user-images.githubusercontent.com/47436092/197081114-b0d0fdc5-101b-4786-8340-b29160ee381a.mp4

**Comment by mallenexpensify** [comment] 2022-10-21 23:03
Job posted https://www.upwork.com/jobs/~01519c155a21384488

**Comment by mallenexpensify** [comment] 2022-10-24 23:51
Nice work double-dipping here @thesahindia 😆 , get the reporting bonus AND C+ gig.  Now.. to get some proposals coming in

**Comment by mallenexpensify** [comment] 2022-10-27 16:26
Price Doubled to $500
https://www.upwork.com/jobs/~01519c155a21384488

**Comment by thesahindia** [comment] 2022-10-31 10:16
@mallenexpensify, I think melvin should add weekly label once the issue gets external or maybe after the upwork job comment. Any thoughts?

**Comment by mallenexpensify** [comment] 2022-10-31 17:06
Qe used to update the label from Daily to Weekly once the job was created but with the new BugZero (BZ) process we're planning to leave `Daily` with the hopes bugs will get fixed more quickly (since we're not focusing on NewFeatures right now)

**Comment by mallenexpensify** [comment] 2022-11-03 15:42
@thesahindia will you review @Ollyws' proposal above? Thx

**Comment by thesahindia** [comment] 2022-11-03 20:37
Great discovery @Ollyws! 

@roryabraham, I like @Ollyws [proposal](https://github.com/Expensify/App/issues/11852#issuecomment-1302186031). 

We will need to do some thorough testing so that everything works fine.

C+ reviewed 🎀👀🎀

**Comment by mallenexpensify** [comment] 2022-11-04 14:59
Thanks @thesahindia , @roryabraham will you review @Ollyws 's proposal plz?

**Comment by mallenexpensify** [comment] 2022-11-07 19:36
@Ollyws and @thesahindia please apply
https://www.upwork.com/jobs/~01519c155a21384488

**Comment by mallenexpensify** [comment] 2022-11-09 02:20
Reassigning as I'm heading OOO for a month

**Comment by CortneyOfstad** [comment] 2022-11-23 20:28
Unassigning as payment needs to be made tomorrow, and I am OoO for Thanksgiving

**Comment by CortneyOfstad** [comment] 2022-11-23 20:30
Sorry!! Accidentally removed all assignments instead of just my own 🤦

**Comment by conorpendergrast** [comment] 2022-11-28 21:00
Oh yikes, sorry for the timing here - I was OoO last week! I'll get this paid today

**Comment by conorpendergrast** [comment] 2022-11-29 01:19
Updated the earlier checklist: https://github.com/Expensify/App/issues/11852#issuecomment-1312018301

Proposal accepted: 5th Nov
Merged: 12th Nov
7 days minus two weekend days equals 5 business days. 
"Merged PR within 6 business days - 0% bonus"

Paying the job rate for this. 

Contracts ended, job is closed. We're all done here!

**Closed by conorpendergrast** 2022-11-29 01:19 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by thesahindia** [comment] 2022-11-29 07:47
@conorpendergrast, the issue was priced at $500 and I am also the reporter at this issue. (I have only received $250)

**Comment by conorpendergrast** [comment] 2022-11-29 20:56
@thesahindia Yeah Matt had set up two contracts, glad that you saw them both!
