### ISSUE TITLE
[$250]  Profile - Email copied from profile is pasted twice in Private notes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53654] opened 2024-12-05 19:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh16110001@applause.expensifail.com
**Issue reported by:** Applause- Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat
3. Click on the report header
4. Click copy icon next to the email
5. Click Private notes
6. CMD+V to paste the email

## Expected Result:
The email will be pasted one time

## Actual Result:
The email is pasted twice

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/d9c36fbb-19e3-4c59-969b-edb7bef9ddcf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864831556453840652</li>
        <li>Upwork Job ID: 1864831556453840652</li>
        <li>Last Price Increase: 2024-12-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by marcochavezf** [comment] 2024-12-06 00:37
Making it external, since seems to be a FE issue

**Comment by prolahcen** [comment] 2024-12-06 00:51
A Function might be called twice.

**Comment by Tony-MK** [comment] 2024-12-06 01:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Profile - Email copied from profile is pasted twice in Private notes

### What is the root cause of that problem?

We are using the `useHtmlPaste` hook in two places, in the `BaseTextInput` and `PrivateNotesEditPage` with the text input in the `PrivateNotesEditPage` as the ref to both hooks.

Hence, the pasted data will be copied twice into the input.

https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L65-L69

https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/components/TextInput/BaseTextInput/index.native.tsx#L102


### What changes do you think we should make in order to solve the problem?


Remove the second `useHtmlPaste` hook in the `PrivateNotesEditPage` over [here](https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L69).

**Comment by prolahcen** [comment] 2024-12-06 01:29
Another solution is to split the pasted string into half and take the first part of it.

**Comment by marcochavezf** [comment] 2024-12-06 01:43
Yes, git bisect led me to https://github.com/Expensify/App/pull/53367, created a revert [here](https://github.com/Expensify/App/pull/53675)

**Comment by marcochavezf** [comment] 2024-12-06 01:46
I think revert will be the best path to unblock the deploy, since seems there's another deploy blocker caused by that PR

**Comment by marcochavezf** [comment] 2024-12-06 17:31
Requested internally a CP for the revert [here](https://expensify.slack.com/archives/C07J32337/p1733506240404629)

**Comment by marcochavezf** [comment] 2024-12-06 20:58
Tested out in staging after the CP and it's working fine, closing out

**Closed by marcochavezf** 2024-12-06 20:58 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted, Bug

**Comment by allroundexperts** [comment] 2025-06-18 12:36
@marcochavezf @jliexpensify Can I please have a payment summary?

**Comment by jliexpensify** [comment] 2025-06-19 04:16
Oh hmm @marcochavezf did you close this before being deployed to production?

Payment Summary

- C+: @allroundexperts $250 (to be paid via New Expensify payments)
