### ISSUE TITLE
Expense report comment can't get marked as "read" 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11323] opened 2022-09-27 04:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any unread chat with multiple messages 
2. Switch to another chat 
3. Navigate to original chat again 

## Expected Result:
if user sees the message, LHN should reflect as read 

## Actual Result:
Chat goes back to unread each time user switches chats 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/192433936-447a4557-13c3-42bf-a4a9-2c47e52a38a3.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar  @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664239420826399
https://expensify.slack.com/archives/C01GTK53T8Q/p1664206400473949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-09-29 16:05
Haven’t had a chance to look into why this behavior is only affecting expense reports, but I think it should probably be made internal.

**Comment by tgolen** [comment] 2022-09-29 20:42
I was originally impacted by this bug, but just earlier this week, after one of the deployments, it started working (the expense report was marked as read properly). I think this can be closed if it's no longer reproducible for anyone.

**Comment by aldo-expensify** [comment] 2022-10-03 22:37
Tried to reproduce today and couldn't (tested staging and prod), I guess we could close it until we have better reproduction steps (if it still happening)

**Comment by JmillsExpensify** [comment] 2022-10-03 22:41
I also tried and am no longer able to reproduce. I like closing it for now, especially with so many unread updates having been pushed out since this issue was first reported. Anyone else re-open if you feel strongly.

**Closed by JmillsExpensify** 2022-10-03 22:41 UTC
Labels: Engineering, Daily, Internal
