### ISSUE TITLE
[$1000] Chat - Welcome message from admin instead of Concierge

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19690] opened 2023-05-26 19:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing** https://github.com/Expensify/App/pull/18662

## Action Performed:
1. Login to NewDot
2. Create a WS and add user B
3. As user A create a public room and add a welcome message
4. As user B accept invitation to the room (enter the room)

## Expected Result:
Welcome message should be from Concierge

## Actual Result:
Welcome message is displayed from admin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.1

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/f08dd9a05654742690178669b51eba43053026de2a0c4a1b9de9b93a14fbbdbf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ada3b1b1cf50c9d</li>
        <li>Upwork Job ID: 1664729277484212224</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-05-30 23:09
@kbecciv when I click on `Details` > `Members` I don't see an option to add a member, how do I
> As a user A invite user B to public room

**Comment by kbecciv** [comment] 2023-06-01 13:05
Hello @mallenexpensify! Let me correct the steps, you need to invite user first by going to Workspace and Invite user and than create a public room. Sending you full video for linked PR. Please let me know if you have any question and I will be happy to help.

https://github.com/Expensify/App/assets/93399543/91eefbfe-9772-4b8d-8387-5dac523407ff

**Comment by StevenKKC** [comment] 2023-06-02 09:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the public room, welcome message is displayed from admin, instead of from Concierge.

### What is the root cause of that problem?
Welcome message is created by admin, and when display welcome message, display the message's actorEmail, so message is displayed from admin.
https://github.com/Expensify/App/blob/af6fb0768b65e95f8a9feb5e36626ae9df5f2097/src/pages/home/report/ReportActionItemSingle.js#L69-L71

### What changes do you think we should make in order to solve the problem?

When display welcome message, we should change the above code in order to display Concierge's avatar and name.
```
    const whisperedToAccountIDs = lodashGet(props.action, 'whisperedToAccountIDs', []);
    const isWhisper = whisperedToAccountIDs.length > 0;
    const actorEmail = (isWhisper && ReportUtils.isPublicRoom(props.report)) ? CONST.EMAIL.CONCIERGE : props.action.actorEmail.replace(CONST.REGEX.MERGED_ACCOUNT_PREFIX, '');
```
### What alternative solutions did you explore? (Optional)
None

**Comment by mallenexpensify** [comment] 2023-06-02 20:23
Thanks @kbecciv was able to reproduce. Think this might be external 🤞 
<img width="575" alt="image" src="https://github.com/Expensify/App/assets/22508304/057bbcff-8a30-4f89-9ed9-546a3a530a79">

**Comment by pecanoro** [comment] 2023-06-02 20:25
This is intended and not a bug. Only some Expensify-created rooms will have the message sent from Concierge, closing!

**Comment by pecanoro** [comment] 2023-06-02 20:25
This is intended and not a bug. Only some Expensify-created rooms will have the message sent from Concierge, closing!

**Closed by pecanoro** 2023-06-02 20:25 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by pecanoro** [comment] 2023-06-02 20:27
This is intended and not a bug. Only some Expensify-created rooms will have the message sent from Concierge, closing!

**Comment by mallenexpensify** [comment] 2023-06-02 20:27
@pecanoro Thanks, is there a list of rooms that do/don't show messages coming from Conci?  Was thinking that'd be good to document somewhere, maybe the main [Testing Guidelines doc](https://docs.google.com/document/d/1UaWlcieiwLnsKfeKw7iwLF7vgYRmdw_-K8OcY5aPBRU/edit)

**Comment by pecanoro** [comment] 2023-06-02 20:30
Only the SF lounge announce room has the welcome message sent from Concierge. We had the NVP manually to some conferences rooms in the past (like EC3), but it's pretty rare. The image that Applause linked to the issue was from my testing room that I created when I implemented the feature. Any other room, the welcome message will come from the policy owner.

**Comment by mallenexpensify** [comment] 2023-06-06 01:48
Thanks @pecanoro !
