### ISSUE TITLE
[HOLD for payment 2023-07-20] [HOLD for payment 2023-07-17]  Typing feedback text under composer is not being displayed

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22426] opened 2023-07-07 13:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a tab where account A is signed in
2. Open an existing chat with account B
3. Start typing in composer
## Expected Result: 
Account B should be able to see account A is typing feedback under composer
## Actual Result:
 account A is typing feedback is not displayed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9d409677-1026-45a6-a838-18969ed881de

https://github.com/Expensify/App/assets/43996225/7e6a4475-6a7c-493c-9438-c2bc26b606f1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688736356072589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2023-07-07 13:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Typing indicator doesn't show under composer

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/ed21fdaaf90f458f7a063eaeb346bff61bac133e/src/pages/home/report/ReportActionsView.js#L243-L246

As `didSubscribeToReportTypingEvents` is useRef hook, if condition is always false and thus never subscribed.

### What changes do you think we should make in order to solve the problem?
replace `didSubscribeToReportTypingEvents` with `didSubscribeToReportTypingEvents.current` in if condition

**Comment by situchan** [comment] 2023-07-07 13:55
I can raise quick PR for this fix. cc: @neil-marcellini @narefyev91

**Comment by Pujan92** [comment] 2023-07-07 14:04
Seems a regression from https://github.com/Expensify/App/pull/22200

**Comment by Santhosh-Sellavel** [comment] 2023-07-09 18:02
Review done waiting for a CME to merge!

**Comment by flaviadefaria** [comment] 2023-07-18 10:39
I just want to confirm who needs payment here as I see no C+ or contributor assigned to the GH.

@Natnael-Guchima $250
@rayane-djouah $1000 + $500 bonus = $1500
@Santhosh-Sellavel $1000 + $500 bonus = $1500

Does this look correct @srikarparsi?

**Comment by situchan** [comment] 2023-07-18 10:43
This was a regression from https://github.com/Expensify/App/pull/22200. Otherwise [my proposal](https://github.com/Expensify/App/issues/22426#issuecomment-1625449483) would have been accepted as I proposed first.

**Comment by Santhosh-Sellavel** [comment] 2023-07-18 14:50
@flaviadefaria Right this is a regression so @rayane-djouah will not be eligible for compensation here. Only reporter and myself for the review as this is a deploy blocker. So I've reviewed the PR keep this moving forward.

**Comment by flaviadefaria** [comment] 2023-07-19 16:55
Got it. So in this case, should there be a 50% bonus for you or does it not apply?

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 19:37
@flaviadefaria Honestly I'm not sure, never been in this scenario before. Mostly it would be internal PRs, this is the odd one can you please check internally?

Worst case fine with No bonus as well, thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 19:38
@flaviadefaria Please assign me this, let me know the final amount. I'll request on ND!

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 19:41
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@srikarparsi] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/22200
> * [x]  [@srikarparsi] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/22200#discussion_r1256185304
> * [x]  [@srikarparsi] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
> * [x]  [@srikarparsi] Determine if we should create a regression test for this bug. We will have this covered already
> * [x]  [@srikarparsi] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
> * [x]  [@flaviadefaria] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by flaviadefaria** [comment] 2023-07-24 12:05
Thanks!

So @Natnael-Guchima $250
@Santhosh-Sellavel $1000

@Santhosh-Sellavel you are going to request payment vua NewDot right? @Natnael-Guchim I'll process your payment in Upworks now.

**Comment by flaviadefaria** [comment] 2023-07-24 12:08
@Natnael-Guchima offer sent!

**Comment by Natnael-Guchima** [comment] 2023-07-24 12:11
Accepted the offer. Thanks @flaviadefaria

**Comment by flaviadefaria** [comment] 2023-07-24 12:59
@Natnael-Guchima - paid
@Santhosh-Sellavel - I just assigned you. The correct amount to be requested is $1000.

**Comment by Santhosh-Sellavel** [comment] 2023-07-26 01:37
Requested on ND

**Comment by flaviadefaria** [comment] 2023-07-26 09:07
>@Santhosh-Sellavel - I just assigned you. The correct amount to be requested is $1000.

Cool waiting for Anu to pay this so that we can close this.

**Comment by JmillsExpensify** [comment] 2023-07-27 04:55
Reviewed details for @Santhosh-Sellavel. This is accurate and approved for payment in NewDot.

**Comment by flaviadefaria** [comment] 2023-07-27 11:18
Great so closing this GH.

**Closed by flaviadefaria** 2023-07-27 11:18 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
