### ISSUE TITLE
[$250] Search - Report always auto scroll down after editing the expense from RHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45434] opened 2024-07-15 22:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two expenses
4. Go to transaction thread of any of the expenses
5. Send enough messages so that the thread is scrollable
6. Scroll up and click on any field
7. Edit the field and save it
8. Note that the report does not auto scroll down
9. Go to Search
10. Open the report RHP for the same transaction thread
11. Scroll up, click on any field, edit and save it

## Expected Result:
The report will not auto scroll down after editing the expense

## Actual Result:
The report always auto scroll down after editing the expense from RHP

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/bf14a155-29d7-4143-943e-995415bd8dfa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01254f76c66b3ced64</li>
        <li>Upwork Job ID: 1812983922733611293</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103286918</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-07-15 22:26
We think that this bug might be related to #wave-collect - Release 1

**Comment by aldo-expensify** [comment] 2024-07-15 22:53
This behaviour is also in production, so removing the deploy blocker label:


https://github.com/user-attachments/assets/3dc3b026-b80b-43f9-90fc-75caa5c2fbcd

**Comment by bernhardoj** [comment] 2024-07-16 05:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The report chat list always scroll to bottom when editing the money request info if we open it from the search page.

### What is the root cause of that problem?
When we open the report screen from the search page, it's inside an RHP navigator. In RHP navigator, a previous screen is hidden, that is the display is set to 'none' (you can check this yourself from the element inspector). In our case, when we open the report RHP, and then open the description page, the report RHP is hidden.

The list in the report screen uses a custom FlatList which sets up a mutation observer. The mutation observer will scroll to the last scroll offset if it's different than the current offset.
https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/components/FlatList/index.tsx#L123-L134

We continuously save the last scroll offset here.
https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/components/FlatList/index.tsx#L77-L78

But somehow, after updating the money request, the last scroll offset is 0 and the current scroll offset is the correct scroll offset. That is because, when a view has a display of none, the scroll offset is 0 (scrollTop).
https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/components/FlatList/index.tsx#L50-L55

The flow is like this:
1. Open the description page, report RHP is hidden
2. Update the description, a system message that the description is added. This triggers the first mutation observer. The last scroll offset contains the prev scroll offset, but the current scroll offset is 0. This calls `scrollToOffset` to the last scroll offset (the correct scroll offset).
3. The mutation observer calls `prepareForMaintainVisibleContentPosition` which updates the last scroll offset to the current scroll offset, that is 0.
4. The list is displayed, trigger the second mutation observer. At this point, the prev scroll offset is 0 and the current scroll offset is the correct offset. This calls `scrollToOffset` to the last scroll offset, 0, to the bottom.

### What changes do you think we should make in order to solve the problem?

Ignore the mutation observer if the list is hidden.

One way to check if it's hidden is to check whether the height is 0 or not. A hidden view will have a height (or width) of 0.
https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/components/FlatList/index.tsx#L123-L134

```
if (!getScrollableNode(scrollRef.current)?.clientHeight) {
    return;
}
```

OR

Don't save the scroll offset in `prepareForMaintainVisibleContentPosition` if the list is still hidden.


https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/components/FlatList/index.tsx#L72-L78

```
if (contentView == null || !getScrollableNode(scrollRef.current)?.clientHeight/clientWidth) {
```

**Comment by greg-schroeder** [comment] 2024-07-16 22:18
Proposal review underway

**Comment by greg-schroeder** [comment] 2024-07-22 12:23
bump @alitoshmatov

**Comment by alitoshmatov** [comment] 2024-07-24 09:06
Reviewing

**Comment by alitoshmatov** [comment] 2024-07-26 10:39
@bernhardoj Thank you for your proposal, your RCA is correct and you solution does makes and works. I think we can go with your first solution

We can go with @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/45434#issuecomment-2230076486)

C+ reviewed 🎀 👀 🎀

**Comment by aldo-expensify** [comment] 2024-07-26 20:32
Do we really want it to scroll down when you edit a report's field to show you the automatic message? What if you wanted to edit two or three fields? if it scrolls down automatically it would very annoying to have to scroll up for each field you want to change.

I'm going to ask in slack if this is something we really want.

**Comment by aldo-expensify** [comment] 2024-07-27 00:22
I misunderstood the issue and it was the opposite, assigning @bernhardoj !

**Comment by bernhardoj** [comment] 2024-07-27 02:08
PR is ready

cc: @alitoshmatov

**Comment by greg-schroeder** [comment] 2024-07-31 15:06
bump @alitoshmatov on PR review

**Comment by greg-schroeder** [comment] 2024-08-13 15:46
Payment summary:

Contributor: @bernhardoj - $250 - You can make a manual request via ND
C+: @alitoshmatov - $250 - Paid via Upwork

cc @alitoshmatov can you complete [the checklist](https://github.com/Expensify/App/issues/45434#issuecomment-2270330418) so we can close this out? Thanks!

**Comment by bernhardoj** [comment] 2024-08-13 15:48
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-08-14 19:08
$250 approved for @bernhardoj

**Comment by aldo-expensify** [comment] 2024-08-15 22:40
Friendly bump @alitoshmatov on completing the list

**Comment by alitoshmatov** [comment] 2024-08-18 13:21
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/32098
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/32098/files#r1720975881
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. No need

**Comment by aldo-expensify** [comment] 2024-08-20 18:15
@greg-schroeder was everyone payed? are we ready to close this?

**Comment by greg-schroeder** [comment] 2024-08-27 05:31
yup! closing

**Closed by greg-schroeder** 2024-08-27 05:31 UTC
Labels: External, Engineering, Weekly, Bug
