### ISSUE TITLE
[HOLD for payment 2024-03-14] [HOLD for payment 2024-03-13] [$500] Distance - Request details page loads infinitely when the request is created offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37743] opened 2024-03-05 13:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Go to workspace chat.
4. Create a distance request.
5. Go to the distance request details page.

## Expected Result:
User will be able to access request details page even though the request is created offline.

## Actual Result:
The request details page loads infinitely when the request is created offline.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f3045af1-a040-4f5a-875f-731ade37b3b4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dfe56b23d3d01ac3</li>
        <li>Upwork Job ID: 1765255088135561216</li>
        <li>Last Price Increase: 2024-03-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by kbecciv** [comment] 2024-03-05 13:44
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by paultsimura** [comment] 2024-03-05 14:16
It's being fixed in https://github.com/Expensify/App/pull/37232

**Comment by mvtglobally** [comment] 2024-03-06 03:01
seems to be resolved on build v1.4.47-7 

https://github.com/Expensify/App/assets/43995119/4ad6c7cc-7188-49e3-9b4d-ad989be22221

**Comment by roryabraham** [comment] 2024-03-06 05:55
actually, going to reopen this to handle C+ review payment on https://github.com/Expensify/App/pull/37804

**Comment by roryabraham** [comment] 2024-03-06 05:57
@joekaufmanexpensify the only todo here is to issue C+ payment to @paultsimura for their review of https://github.com/Expensify/App/pull/37804.

**Comment by joekaufmanexpensify** [comment] 2024-03-06 15:42
Sounds good. We'll handle this payment 7 days after PR hits production.

**Comment by paultsimura** [comment] 2024-03-11 15:07
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/react-native-onyx/pull/480
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/react-native-onyx/pull/480/files#r1519881887
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug: Yes
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go offline.
2. Go to a workspace chat.
3. Create a new distance request.
4. Open the distance request details page (i.e. transaction thread).
5. Verify the request details page loads successfully even though the request was created offline.

Do we agree 👍 or 👎

**Comment by joekaufmanexpensify** [comment] 2024-03-13 21:20
TY! No additional regression test is needed here. This is already captured in the existing test: `Request Money - Distance Expense - Create distance Expense (Offline)`

**Comment by joekaufmanexpensify** [comment] 2024-03-13 21:21
All set to issue payment. We only need to pay @paultsimura $500 for C+ review via upwork.

**Comment by joekaufmanexpensify** [comment] 2024-03-13 21:22
@paultsimura offer sent for $500!

**Comment by joekaufmanexpensify** [comment] 2024-03-13 21:28
TY!

**Comment by joekaufmanexpensify** [comment] 2024-03-13 21:28
$500 sent and contract ended

**Comment by joekaufmanexpensify** [comment] 2024-03-13 21:28
Upwork job closed.

**Closed** 2024-03-13 21:28 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
