### ISSUE TITLE
Search - Nothing happens after clicking on user with no chat history on Search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50973] opened 2024-10-17 07:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open report.
3. Click search on the top right.
4. Enter the name of user with no chat history (must be the user whose chat has never been opened before).
5. Click on the user.

## Expected Result:
The chat with that user will open.

## Actual Result:
Nothing happens after clicking on user with no chat history on Search.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1747b10d-005f-46e8-b80d-cc25900b3ce9

  </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkzie2** [comment] 2024-10-17 07:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Nothing happens after clicking on user with no chat history on Search.

### What is the root cause of that problem?

We use `dismissModalWithReport` to navigate to the newly created report with the new user:

https://github.com/Expensify/App/blob/c7847b96041b3c69d7507fec86e0305baa8c86a3/src/components/Search/SearchRouter/SearchRouterList.tsx#L163-L165

https://github.com/Expensify/App/blob/c7847b96041b3c69d7507fec86e0305baa8c86a3/src/libs/actions/Report.ts#L1048-L1050

But since we open from Report screen and it is not included in these screens:

https://github.com/Expensify/App/blob/c7847b96041b3c69d7507fec86e0305baa8c86a3/src/libs/Navigation/dismissModalWithReport.ts#L36

causing the `dismissModalWithReport `does not navigate.

### What changes do you think we should make in order to solve the problem?


Add SCREENS.REPORT to the above cases.

**Comment by Kicu** [comment] 2024-10-17 07:59
I will take a look at this one.

**Comment by luacmartins** [comment] 2024-10-17 15:17
Taking this over since it came from a Search PR.

**Comment by Kicu** [comment] 2024-10-17 15:20
Fix ready in a PR.
I was mostly testing on a non-existing user account, but Im 99% sure it's the same behaviour whether this is an actual user that you never talked with or a completely fake user account.

**Comment by luacmartins** [comment] 2024-10-17 18:32
This is fixed in staging.

**Closed by luacmartins** 2024-10-17 18:32 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug
