### ISSUE TITLE
Dev: Web - EXpensify signup text appears on epub and mp4 uploads

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26174] opened 2023-08-29 11:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Upload attachments
3. Select any epub files or mp4 records and send
Notice that after the attachment is uploaded, extra text about expensify is displayed.
P.S doesn't happen with pdfs and jpgs.

## Expected Result:
Extra text about expensify should not be  displayed.

## Actual Result:
Extra text about expensify should is displayed after attachments

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.58.0
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/489d39fc-3f4a-4058-86b0-eb7659f22364

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693306268579329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ashimsharma10** [comment] 2023-08-29 11:24
Apologies. Accidentally I tested this on the really old dev version. Could not reproduce on latest v1.3.58-1 dev.

**Comment by MitchExpensify** [comment] 2023-08-30 03:57
> Apologies. Accidentally I tested this on the really old dev version. Could not reproduce on latest v1.3.58-1 dev.

All good! closing

**Closed by MitchExpensify** 2023-08-30 03:57 UTC
Labels: Daily, Needs Reproduction, Bug
