### ISSUE TITLE
[$500] mWeb/Safari - Chat - After removing an emoji and adding a new, the focus shifts the top of the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31594] opened 2023-11-20 23:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Open any 1:1 chat
3. Insert 3-4 emojis
4. Edit this message, remove the last emoji and add a new one

## Expected Result:
The focus should stay on the edited message

## Actual Result:
After removing an emoji and adding a new, the focus shifts to the top of the page and it shakes once.
On prod, the focus only moves up a little bit and the shake isn't present

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e38a0080-dd2f-4639-8f4a-3b0c47f8ad65

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124d5bed6c31044e5</li>
        <li>Upwork Job ID: 1726740264760147968</li>
        <li>Last Price Increase: 2023-12-11</li>
    </ul>
</details>

**Comment by wlegolas** [comment] 2023-11-21 04:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

mWeb/Safari - Chat - After removing an emoji and adding a new, the focus shifts the top of the page

### What is the root cause of that problem?

When finish the edition the method `deleteDraft` is called to performance the action to draft of the comment being edited. In this method, there is a condition to check if the user is editing the last message, will be added an event listener to the event `keyboardDidHide` in the `Keyboard` object. But adding an event listener to the `Keyboard` object will only work in native devices, in this case we are using a Mobile Browser not a native app. 

https://github.com/Expensify/App/blob/72e73ae6d922b915198e0a5bcff9d71de5a1001b/src/pages/home/report/ReportActionItemMessageEdit.js#L297-L302

### What changes do you think we should make in order to solve the problem?

We should improve the method `deleteDraft` in the `ReportActionItemMessageEdit` component to execute the scroll when the user finish the edition and they are using a Mobile Browser

For example,

```js
/**
 * Delete the draft of the comment being edited. This will take the comment out of "edit mode" with the old content.
 */
const deleteDraft = useCallback(() => {
    InputFocus.callback(() => setIsFocused(false));
    InputFocus.inputFocusChange(false);
    debouncedSaveDraft.cancel();
    Report.saveReportActionDraft(props.reportID, props.action, '');

    if (isActive()) {
        ReportActionComposeFocusManager.clear();
        ReportActionComposeFocusManager.focus();
    }
    // Scroll to the last comment after editing to make sure the whole comment is clearly visible in the report.
    if (props.index === 0) {
        if(Browser.isMobile()) { // <- Here is the new condition
            reportScrollManager.scrollToIndex(props.index, false);
            return;
        }

        const keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', () => {
            reportScrollManager.scrollToIndex(props.index, false);
            keyboardDidHideListener.remove();
        });
    }
}, [props.action, debouncedSaveDraft, props.index, props.reportID, reportScrollManager, isActive]);
```

### What alternative solutions did you explore? (Optional)

N/A

**POC**

**Comment by wlegolas** [comment] 2023-11-22 22:23
Hi @hoangzinh thank you for reviewing my proposal.

About your question, In my analysis, I understood the problem is only related when we edit the message and add a new emoji because when the emoji modal is shown the component's height changes and the position changes in the scroll view.

If you edit the emoji only removing information and saving you'll see that the strange behavior won't occur but if you edit the emoji removing and adding another one, the strange behavior will occur. See the video below.

https://github.com/Expensify/App/assets/698363/1383f902-9626-4e48-8635-522fe470ef8a

**Comment by wlegolas** [comment] 2023-11-28 02:20
> > I understood the problem is only related when we edit the message and add a new emoji because when the emoji modal is shown the component's height changes and the position changes in the scroll view.
> 
> Hi @wlegolas, could you elaborate on this point, which component's height did you mention? I tried to watch your recording and found that the height before and after adding the emoji is same
> 

Hi @hoangzinh , sorry maybe I didn't explain right the problem.

If you see in the video that I put in this comment https://github.com/Expensify/App/issues/31594#issuecomment-1823581685, between the time `0:14` and `0:17` you can see the `ReportActionCompose` is shown and hidden when I clicked on the emoji button (`EmojiPickerButton` component).

![image](https://github.com/Expensify/App/assets/698363/d12192e4-6186-40d9-ba39-f585d231a83f)

That's what I was talking about to change the height.

In the video at the end of this comment, you can see the `InvertedFlatList` component's height started with "**496px**", when I selected the emoji and confirmed the edition, the `InvertedFlatList` height is changed to "**594px**", if we calculate the difference between the two heights (**594px** - **496px**) we will have the value "**98px**", this value is related to `ReportActionCompose` height.

![image](https://github.com/Expensify/App/assets/698363/1c1137d9-413c-4d1a-89dc-f807c0d1ebce)

When is saved the information in the `ReportActionItemMessageEdit` component, the `ReportActionCompose` is only displayed after the  `InvertedFlatList` is updated and that's the reason its height is increased.

If you have any other questions, feel free to bring them up.

https://github.com/Expensify/App/assets/698363/a5549403-cdc5-405b-839c-8a751eebff20

**Comment by wlegolas** [comment] 2023-11-28 02:26
## Proposal
[Updated](https://github.com/Expensify/App/issues/31594#issuecomment-1820217249)

**Comment by CortneyOfstad** [comment] 2023-11-29 14:44
@hoangzinh any thoughts on the proposals above? Thanks!

**Comment by CortneyOfstad** [comment] 2023-12-04 15:41
Not overdue

**Comment by wlegolas** [comment] 2023-12-05 02:25
> @wlegolas your solution doesn't work if we're editing a comment that is not the last comment. I.e before the last comment
> 
> I think we should step back and understand clearly the root cause first, I also reproduced the issue with
> 
> 1. Editing a text comment only
> 2. Then click open Emoji
> 3. Then close Emoji modal
> 4. Click save
Hi @hoangzinh you're right, if we follow your steps above the problem will occur. Sorry for not giving a solution before with the fix for this behavior I focused only on the current behavior when editing the last comment and adding a new emoji.

I could have the same problem following the steps above in my local, here's a video with the behavior.

https://github.com/Expensify/App/assets/698363/c0dc7afe-f5c9-4fdc-998e-585573616399

In my proposal, I said in the alternative solutions section that we can use the method `setShouldShowComposeInput` from the `ComposerActions` to show the composer component before the Flatlist calculates its height, but in my proposal was only related to the last comment.

I'll update my proposal to call the method `setShouldShowComposeInput` before saving the Report draft. We can fix this behavior for any comment in the Flatlist with this change.

https://github.com/Expensify/App/assets/698363/c1c16968-5e41-4eb4-80cf-b590458d9e9e

**Comment by wlegolas** [comment] 2023-12-05 02:42
## Proposal
[Updated](https://github.com/Expensify/App/issues/31594#issuecomment-1820217249)

**Comment by CortneyOfstad** [comment] 2023-12-06 14:20
@hoangzinh thoughts on the proposals above ^^^? Thanks!

**Comment by ikevin127** [comment] 2023-12-11 17:36
> I don't think your RCA is correct. I tried to edit `a message that is at an index different than 0` with text only, this bug does not occur.

The catch is to open the Emoji picker, as soon as you do that and save the edited comment, the scroll jumps - you don't even need to change anything while editing the comment, just opening the emoji picker is enough to make the scroll jump upon saving the edited comment when the `FlatList` layout size is updated.

> I believe this bug happens only in mWeb Safari. Both of your proposals haven't explained why it happens only in mWeb Safari, but not mWeb Chrome.

It does happen on Chrome too, not just Safari. I tried with both real device and simulator and it's consistent between browsers.

To be more specific on what causes the scroll to jump:

<details>
<summary>Flatlist / emoji picker interactions</summary>

_

In React Native, a `FlatList` component uses a `ScrollView` internally to manage its layout and scrolling. When an external component like the emoji picker modal appears and is later closed, here's a high-level overview of what happens:

1. **Modal Presentation**: When the emoji picker modal is presented, especially if it's a half-screen modal that hovers above the main content, it typically does not immediately affect the underlying `FlatList` scrolling position. The modal is overlaid on top of the current screen's content, and as such, the `FlatList` sits in the background unaltered.

2. **Layout Change**: If the modal affects the layout by displacing or resizing the main content (such as when triggering adjustments for the virtual keyboard), this can disrupt the layout of `FlatList`. For example, the keyboard appearing typically causes the screen to resize to fit the remaining space, which would trigger a layout change on the `FlatList`.

3. **Content Offset Preservation**: React Native's `ScrollView` (and by extension `FlatList`) normally tries to preserve the content offset when a layout change occurs. In other words, it endeavors to keep the same content in view despite the change in screen real estate. However, this isn't always perfect, especially if the size of the items in the list changes or the list is dynamically loaded.

4. **Modal Dismissal**: Once a modal is dismissed, any previously applied layout constraints are removed. If the modal presented the keyboard and this affects the `FlatList`, dismissing the modal and hiding the keyboard would trigger another layout change as the screen returns to its full height. The `FlatList` would attempt to restore the scroll position as it was before the modal was presented.

5. **Potential Scroll Issues**: Despite React Native's efforts to preserve scroll position, there can be cases where the scroll position "jumps" or doesn't return exactly to the previous state. This behavior can be due to a number of factors, including dynamic content resizing, incomplete state updates before the layout change, or asynchronous events like network loads that alter the list content during the layout transition.

Considering all these, we also have the focus / blur of the edit composer which when emoji modal is opened from the edit composer, the composer is blurred which causes the main report composer to be rendered back into the `FlatList`, and when closing the emoji picker the edit composer focuses again which causes the main report composer to hide then when saving the edited comment, the main report composer to be rendered back into the `FlatList` again.

So lots of layout changes within the `Flatlist` but the main culprit is the emoji picker.

React Native FlatList doesn't have built-in specific handling for when modals appear or disappear; it simply responds to the resulting layout changes. If encountering scroll position issues after an emoji picker modal is dismissed, we may need to manually handle scroll position preservation and restoration, often involving setting variables that track necessary offsets or selected item indices and then executing scroll actions at appropriate times within the component lifecycle.
_

</details>

**Closed** 2023-12-12 13:47 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
