### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Web -  The "Invalid Two Factor Authentication code" error from the 2FA page is also displayed on the contact methods page even without entering any code

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23592] opened 2023-07-25 21:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
. Go to Settings > Security > Two-factor authentication.
2. Click on "Copy" and proceed to the next step.
3. Enter an incorrect number for Two Factor Authentication.
4. Now go to the Profile > Contact methods.
5. Add a new contact method.
6. Notice that the "Invalid Two Factor Authentication code" error from the 2FA page is displayed on the contact methods page without entering any code

## Expected Result:
The "Invalid Two Factor Authentication code" error should not be displayed on the contact methods page when adding a new contact method

## Actual Result:
The "Invalid Two Factor Authentication code" error from the 2FA page is also displayed on the contact methods page without entering any code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f45b12e5-826d-4be5-8924-6be3dbc6a10d

https://github.com/Expensify/App/assets/93399543/6fa21dd9-2058-47c9-8846-1772af991f90

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690228883804299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b2ef3498aa199c3</li>
        <li>Upwork Job ID: 1686807446598131712</li>
        <li>Last Price Increase: 2023-08-02</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-07-29 19:18
I ran out of time on Thursday and was OOO yesterday. I'll try to review it over the weekend.

**Comment by alexpensify** [comment] 2023-08-01 00:49
Not overdue - still on my testing lists

**Comment by alexpensify** [comment] 2023-08-02 18:35
I tested and marked it as `External`. I was able to replicate. @ArekChr when you get a chance, can you please review the proposals submitted so far? Thank you! 

![2023-08-02_11-31-44](https://github.com/Expensify/App/assets/8107070/09ad445e-62f6-4d90-8bb7-5ca4c0484ae1)

![2023-08-02_11-32-30](https://github.com/Expensify/App/assets/8107070/d3a40026-7636-4a30-8613-8bc9ec8ad6df)

**Comment by ares-dev05** [comment] 2023-08-02 19:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
the "Invalid Two Factor Authentication code" error from the 2FA page is displayed on the contact methods page without entering any code
### What is the root cause of that problem?
In the profile > contact method page, when the component loads, the system messages didn't refresh.
### What changes do you think we should make in order to solve the problem?
In `src\pages\settings\Profile\Contacts\ValidateCodeForm\BaseValidateCodeForm.js`, we have to call `Session.clearAccountMessages();` when component has been loaded.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by 4cidkid** [comment] 2023-08-02 20:08
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> The problem is that /settings/profile/contact-methods/email/details is showing us an error 1691004584222742: "Invalid Two Factor Authentication code. Please re-enter the code from your authentication app." when we introduced incorrect input on /settings/security/two-factor-auth/codes.
> 
> ### What is the root cause of that problem?
>  The root cause is that the value errors on the "account" key is only refreshed when user input is entered on the form and the >  error state en the key "account" persist through the app.
>  see example ---> [https://ibb.co/zPRNMcZ](url)
> 
> 
> ### What changes do you think we should make in order to solve the problem?
> We need to refresh the account key back to it's original state. In the verify page you are already doing this by using
>`    useEffect(() => {
>        Session.clearAccountMessages();
>    }, []);
>` 
> 
> 
> 
>
>
>
>
> 
> ### What alternative solutions did you explore? (Optional)
> Maybe, and just maybe if that dosn't work, we can try to implement a type of "middleware" to check if exist a key errors with > a valid value, and remove that value every time we navigate through a different page, or just a different page located in the /settings page.

**Comment by 4cidkid** [comment] 2023-08-02 20:11
Contributor details
Your Expensify account email: desmondgamesyt@gmail.com
Upwork Profile Link: [<[REPLACE LINK HERE](https://www.upwork.com/freelancers/~0135b280e8a4859638)>]

**Comment by ArekChr** [comment] 2023-08-03 13:30
The [proposal](https://github.com/Expensify/App/issues/23592#issuecomment-1650568589) from @huzaifa-99 looks good to me!
:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by dangrous** [comment] 2023-08-03 15:49
Hi! A question for discussion - is it better to put the `Session.clearAccountMessages()` in the `ContactMethodsDetailsPage` or in the `BaseValidateCodeForm` component? To me, it might make more sense to put it in the component, and keep it centralized. It would also fix things more globally.... but would there be regressions / unintended consequences?

**Comment by dangrous** [comment] 2023-08-04 16:12
Yeah I was wondering about that, using clearAccountMessages() is pretty broad - I'm not sure it's intentional, per se, but I don't think it's something we need to be concerned about here since it's a pattern we're copying.

I'll assign you, @huzaifa-99, and let's put the clear in `BaseValidateCodeForm`. If you disagree strongly @ArekChr, though, we can discuss!

**Comment by alexpensify** [comment] 2023-08-06 16:55
Thank you @huzaifa-99 for that update!

**Comment by ArekChr** [comment] 2023-08-09 12:50
- [x] The PR that introduced the bug has been identified. Link to the PR: no PR has been identified.
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: no comment.
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: no discussion.
- [x] Determine if we should create a regression test for this bug. I think we can have a simple unit test for that.
Regression Test Proposal

1. Mock invalid code for 2FA for storing error messages.
2. Navigate to the Profile > Contact methods.
3. Add a new contact method.
4. Verify if "Invalid Two Factor Authentication code" does not appear.

Do we agree 👍 or 👎?

**Comment by dangrous** [comment] 2023-08-09 16:44
I think we can probably just copy the steps in this issue which have a little bit more detail:

1. Go to Settings > Security > Two-factor authentication.
2. Click on "Copy" and proceed to the next step.
3. Enter an incorrect number for Two Factor Authentication.
4. Now go to the Profile > Contact methods.
5. Add a new contact method.
6. Ensure that the "Invalid Two Factor Authentication code" error from the 2FA page is not displayed on the contact methods page without entering any code

**Comment by alexpensify** [comment] 2023-08-16 23:54
@dangrous do we need to hold the payment here because of regression or good to go?

**Comment by alexpensify** [comment] 2023-08-18 17:35
Thanks, I'll start working on the payment process.

**Comment by alexpensify** [comment] 2023-08-18 22:06
Here is the payment summary: 

-  External issue reporter - @ayazhussain79 $250 
-  Contributor that fixed the issue - @huzaifa-99 $1500
-  Contributor+ that helped on the issue and/or PR - @ArekChr $1500

Upwork Job: https://www.upwork.com/jobs/~017b2ef3498aa199c3

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: There is an urgency bonus here

**Comment by ayazhussain79** [comment] 2023-08-18 22:07
@alexpensify Offer accepted, Thank you

**Comment by alexpensify** [comment] 2023-08-18 22:14
Offers have been sent out and I've completed the payment process for @ayazhussain79

**Comment by alexpensify** [comment] 2023-08-21 16:53
I've completed the payment process in Upwork. Please confirm that you received it. Thanks!

**Comment by alexpensify** [comment] 2023-08-21 23:46
Ok, I need to create the regression test request and then can close out this GH

**Comment by alexpensify** [comment] 2023-08-24 04:25
Closing - the regression test GH has been created

**Closed by alexpensify** 2023-08-24 04:25 UTC
Labels: External, Weekly, Awaiting Payment, Bug
