### ISSUE TITLE
[$500] Web - Visible scroll bars are appearing in the main chat view

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34721] opened 2024-01-18 13:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.27-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705415832931169

## Action Performed:
1. Switch to a chat that you know has lots of new messages 
2. When you see the new messages arrive, the scrollbar shows up
3. When you scroll to the bottom of the chat manually, the scrollbar doesn't go away

## Expected Result:
Visible scroll bars are not appearing in the main chat view

## Actual Result:
Visible scroll bars are appearing in the main chat view

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/b51af312-6b71-436f-b1a7-12a3e10a19af)

https://github.com/Expensify/App/assets/93399543/d92f421f-9d66-4558-9da7-8d32b5f7c84d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01154cf3660b8514de</li>
        <li>Upwork Job ID: 1747970509054373888</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by tgolen** [comment] 2024-01-18 14:45
Thanks, all. I believe this is a recent regression. Would you mind including some details in your root-cause-analysis which locates the cause of the regression?

**Comment by shahinyan11** [comment] 2024-01-18 15:42
@tgolen I can find any pr with regression. I think this behavior has happened before

**Comment by tgolen** [comment] 2024-01-18 20:25
Hm, @mountiny said "They should only be visible on mac when scrolling", which makes me think it was a regression. However, I did check out the code from a month ago and see that the scrollbar is always there 🤔 Maybe we shouldn't do anything here after all. It just seemed to catch me off guard when I saw them a couple of days ago.

**Comment by tgolen** [comment] 2024-01-18 20:30
I think showing it during scroll is helpful, but I agree that it would be nice to have it hidden when it's not being scrolled. Is that possible?

**Comment by tgolen** [comment] 2024-01-18 20:38
Hm, so I also just found this setting in Mac OS preferences:

![image](https://github.com/Expensify/App/assets/1228807/3320b6fd-837f-4cee-b12a-dc72e27056e6)

Changing that setting to "When scrolling" is just what I needed, so I am going to close this. I wonder if this got changed with an OS update or something, which might explain why I just started noticing it.

**Closed by tgolen** 2024-01-18 20:38 UTC
Labels: External, Daily, Help Wanted, Bug
