### ISSUE TITLE
[HOLD for payment 2024-09-18] [$50] Expensify Card - Expensify Card page loads infinitely

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48835] opened 2024-09-09 21:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48632
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Expensify Card.

## Expected Result:
Expensify Card page will not load infinitely.

## Actual Result:
Expensify Card page loads infinitely, unless user clicks on the same tab or refresh the page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0fad53be-c7e1-44c4-b23e-d62a4d4dea95

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833256019789096800</li>
        <li>Upwork Job ID: 1833256019789096800</li>
        <li>Last Price Increase: 2024-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103894214</li>
<li>allgandalf | Contributor | 103894216</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by mountiny** [comment] 2024-09-10 09:42
@daledah can you please link the offending pr so we can reduce payment there if possible

**Comment by AttockOffice85** [comment] 2024-09-10 10:07
Hi, I am new as a contributor/user to the Expensify app.
Not getting **Expensify Cards** option.

Uploading Bug6598003_1725915441991-reproducing-issue.mp4…

**Comment by mountiny** [comment] 2024-09-10 15:41
@daledah What is your ETA to get the PR ready for a review? also what is your Slack handle?

**Comment by mountiny** [comment] 2024-09-10 15:42
@Nodebrute let's have the PR author fix this as its behind beta no rush

**Comment by chiragsalian** [comment] 2024-09-10 19:11
Tested on staging web and the PR works well for me. Removing blocker label and checking it off the checklist.

**Comment by mountiny** [comment] 2024-09-10 21:41
Decreasing the payment on this one. the solution did not work fully and it also brought new regression:
 ![image](https://github.com/user-attachments/assets/40f2c123-744f-45d1-9dc9-4d9b4de143e6)

and the spinner issue still remained on the card list page/ when the policy had some cards

https://github.com/user-attachments/assets/c7f9fdf3-258b-4d39-a73e-57070a2c76eb

As such I think we should actually decrease the payment even further, those were quite basic things to catch during a review and development @daledah please try to be more careful and test the flows fully

**Comment by mountiny** [comment] 2024-09-10 21:56
`showLoadingAsFirstRender={false}` should fix it as a suggestion from @aimane-chnaif

**Comment by rushatgabhane** [comment] 2024-09-10 23:29
> the solution did not work fully and it also brought new regression

im really sorry about this one.  i should have added cards to my account and tested.

**Comment by chiragsalian** [comment] 2024-09-10 23:31
All cool, i missed it too and didn't test with cards on my account. 
Alright so whats next here @daledah, will you prepare a follow-up PR to fix the issue?

**Comment by AttockOffice85** [comment] 2024-09-12 05:09
Contributor details
Your Expensify account email: attockofficeworkonly@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c7ba3745b8d54a7f

**Comment by AttockOffice85** [comment] 2024-09-12 05:36
Hi, I am new as a contributor/user to the Expensify app.
And tried to enable Expensify Card(s) and few other features but failing again and again. 

Kindly help in this regards.

https://github.com/user-attachments/assets/5d9b96a6-233c-4db9-be13-2418f7509d66

**Comment by Christinadobrzyn** [comment] 2024-09-12 18:22
Hi there, can you check to see if this [regression](https://github.com/Expensify/Expensify/issues/427794) is related to this issue? I'm having trouble finding the PR linked.

**Comment by mountiny** [comment] 2024-09-15 23:16
@Christinadobrzyn The linked issue seems to be purely oldDot and the changes in the issue are only in Newdot so I dont think it can be related

**Comment by mountiny** [comment] 2024-09-19 10:21
@daledah and @rushatgabhane $50

**Comment by sonialiap** [comment] 2024-09-19 10:27
Payment summary:
- @daledah $50 - offer sent
- @rushatgabhane $50 - please complete the [checklist](https://github.com/Expensify/App/issues/48835#issuecomment-2344348909) - payment via NewDot

**Comment by sonialiap** [comment] 2024-09-25 09:24
@rushatgabhane bumping for the [checklist](https://github.com/Expensify/App/issues/48835#issuecomment-2344348909) 😊

**Comment by mountiny** [comment] 2024-09-25 09:40
@sonialiap This was a feature behind beta, and we will add the tests for this feature in one go as part of the project. I think for now we can skip the checklist and pay out

**Comment by sonialiap** [comment] 2024-09-25 10:40
Sounds good 👍 
Payment via Upwork completed already and Rushat will need to request via ND. Closing this since we don't need to fill out the checklist

**Closed by sonialiap** 2024-09-25 10:40 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-09-26 15:37
$50 approved for @rushatgabhane
