### ISSUE TITLE
[HOLD for payment 2024-06-13] [$500] Reddot pinned chat appears for approver for submitter's failed scanned receipt 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37044] opened 2024-02-21 19:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708448202824579

## Action Performed:
1. Create a collect policy in OD as account A
2. Invite user B as employee
3. Log in as user B in NewDot 
4. Create a expense report with a invalid receipt to fail the scanning
5. Log in to user A in NewDot

## Expected Result:
No RBR pinned chat appear in the LHN for the error message

## Actual Result:
Seeing red dot pinned chat in LHN for submitter's workspace chat as approver

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screen Shot 2024-02-21 at 2 06 13 PM](https://github.com/Expensify/App/assets/38435837/1c10e371-0d03-47fc-99e8-a1e093c9648c)

![image (10)](https://github.com/Expensify/App/assets/38435837/8493d80c-6959-41e0-b8f3-4ce1941cfc5e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158b53b3b70327b50</li>
        <li>Upwork Job ID: 1760383519930896384</li>
        <li>Last Price Increase: 2024-04-08</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by wildan-m** [comment] 2024-02-22 09:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

Currently errors are not distinguished by owner, so they will show to all users who have access.
### What changes do you think we should make in order to solve the problem?

If the red dot should only be visible to the owner, we can relocate this line:

https://github.com/Expensify/App/blob/d33bf6e0454fae9550422da28b0407f01b23c969/src/libs/SidebarUtils.ts#L238

below this code:

https://github.com/Expensify/App/blob/d33bf6e0454fae9550422da28b0407f01b23c969/src/libs/SidebarUtils.ts#L359-L361

And adjust the logic to:

```
    result.isIOUReportOwner = ReportUtils.isIOUOwnedByCurrentUser(result as Report);
    result.brickRoadIndicator = (hasErrors || hasViolations) && result.isIOUReportOwner ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : '';
```

### What alternative solutions did you explore? (Optional)

**Comment by wildan-m** [comment] 2024-02-22 15:16
@eVoloshchak proposal [updated](https://github.com/Expensify/App/issues/37044#issuecomment-1959066547).

Add an optional condition if we also want to apply the same rule for the workspace switcher.

**Comment by isabelastisser** [comment] 2024-02-23 17:24
Hey @eVoloshchak, can you please review the proposal? Thanks!

**Comment by Tony-MK** [comment] 2024-02-25 02:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Scan - No red dot for transaction thread in LHN when scanning fails

### What is the root cause of that problem?

The second condition block, in the [`getAllReportErrors`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L481-L493) function, won't be executed because on the approver's app, the `report?.ownerAccountID === currentUserAccountID` condition will fail.

https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L487-L489

Hence, the [`getAllReportErrors`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L481-L493) function will continue to the third and last condition which will succeed.

This root cause of this issue is caused by the third condition in the [`getAllReportErrors`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L481-L493) function since the function does not consider that previous condition failed because the report is an expense or iou and `report?.ownerAccountID !== currentUserAccountID`.

https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L491-L492

Therefore, the third condition will pass because the [`ReportUtils.hasSmartscanError`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/ReportUtils.ts#L4819) returned true. After all, the `reportActions` contain scan errors because the `REPORT_PREVIEW` action has to display the RBR in this state. 

### What changes do you think we should make in order to solve the problem?

In the third condition, we should check if the report is an expense report to prevent scan errors from the `reportActions` getting assigned to `reportActionErrors.smartscan` when expense reports do not meet the `report?.ownerAccountID === currentUserAccountID` conditions.

Hence, let's use the [`ReportUtils.isExpenseReport`](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/ReportUtils.ts#L618) function as such:

**Old Condition**

https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/OptionsListUtils.ts#L491-L493

**New Condition**

```
...
else if (
  !ReportUtils.isExpenseReport(report) &&
   ReportUtils.hasSmartscanError(Object.values(reportActions ?? {}))
)
...
```

**Optional** We can also use the `isIOUReport` function to prevent IOUs from being affected.

**Comment by Tony-MK** [comment] 2024-02-25 02:52
This issue was meant to be fixed at https://github.com/Expensify/App/issues/34827.

The expected result was explained in detail in this https://github.com/Expensify/App/issues/34827#issuecomment-1928050071 and https://github.com/Expensify/App/issues/34827#issuecomment-1955320703 by @cead22.

The issue was closed despite the third expected result is not fulfilled: ***The expense report should not have the RBR on the LHN for either user***

**Comment by eVoloshchak** [comment] 2024-02-26 01:24
@Tony-MK, thank you for the added context!
Asking how we should proceed in https://github.com/Expensify/App/issues/34827#issuecomment-1963160201

**Comment by cead22** [comment] 2024-02-26 19:43
@JmillsExpensify do we wanna show RBR on the LHN when receipt scanning fails  **only** to the user requesting money? I think so, and if that's the case, @brandonhenry 's and @dukenv0307 's root cause is accurate

**Comment by isabelastisser** [comment] 2024-02-28 20:44
Not overdue. bump @JmillsExpensify on Carlo's question above ^^

**Comment by isabelastisser** [comment] 2024-03-04 19:16
I DM'd Mills.

**Comment by JmillsExpensify** [comment] 2024-03-04 21:08
> @JmillsExpensify do we wanna show RBR on the LHN when receipt scanning fails **only** to the user requesting money? I think so, and if that's the case, @brandonhenry 's and @dukenv0307 's root cause is accurate

Yes, that's correct. If the receipt scan fails, then we only RBR the LHN of the person that created the request.

**Comment by Tony-MK** [comment] 2024-03-04 23:21
# Updated Proposal
Proposal Link: https://github.com/Expensify/App/issues/37044#issuecomment-1962794790

**Comment by cead22** [comment] 2024-03-05 23:06
> * I think we should only display the RBR in LHN if user can **edit** the request. You can see this [issue](https://github.com/Expensify/App/issues/27333#issuecomment-1717491070)

We should only show this to the user that created the request

> * If we display the RBR if the user is request`s author, it will lead to the case that the LHN display RBR but the MoneyRequestView has no RBR

Is this because RequestMoney isn't returning transaction violations? If so, we'll fix that in the back end

**Comment by isabelastisser** [comment] 2024-03-06 17:35
hEY @eVoloshchak, can you please provide an update here? Thanks!

**Comment by isabelastisser** [comment] 2024-03-07 16:55
Bump for review, @eVoloshchak . Thanks!

**Comment by eVoloshchak** [comment] 2024-03-07 19:24
I think we should clarify @dukenv0307's [question](https://github.com/Expensify/App/issues/37044#issuecomment-1979815363) first, I think it's a valid one. The expected result in https://github.com/Expensify/App/issues/27333 was to show RBR if user can edit the request

> So what about the RBR in MoneyRequestView? I think we should keep the consistency between LHN and report action. Currently, we are using this condition to display:

https://github.com/Expensify/App/blob/1366fb74c123a93f8da9446eadd6381a9b60894b/src/components/ReportActionItem/MoneyRequestView.tsx#L195

@cead22, what is your opinion on https://github.com/Expensify/App/issues/37044#issuecomment-1979815363?

**Comment by cead22** [comment] 2024-03-08 02:08
> @cead22 So what about the RBR in MoneyRequestView? I think we should keep the consistency between LHN and report action.

We've discussed this extensively, and decided that we would treat the RBR on the LHN different than the money request view.

The RBR on the LHN should only show for the user that made the request. The RBRs on the report preview, money request preview, and the ones in the money request view, should show to every user that has access to them.

The reasoning we're using here is that the user that made the request is the one that should be guided towards taking actions to fix the RBR, and that guidance starts with the chat on the LHN. 

Moreover, we don't want to hide RBRs in report previews, money request previews, or the money request view, to anyone that has access to the money requests. And if they have RBRs, we should show them because there's no value in hiding information from people that have access to it.

Keep me honest here @JmillsExpensify @trjExpensify

**Comment by isabelastisser** [comment] 2024-03-11 13:51
@JmillsExpensify @trjExpensify, can you please follow up on Carlos' question above? Thanks!

https://github.com/Expensify/App/issues/37044#issuecomment-1984922236

**Comment by JmillsExpensify** [comment] 2024-03-11 14:50
I agree with everything @cead22 mentioned above.

**Comment by trjExpensify** [comment] 2024-03-12 01:57
Samesies!

**Comment by isabelastisser** [comment] 2024-03-14 17:13
@eVoloshchak, please provide an update. Thanks!

**Comment by eVoloshchak** [comment] 2024-03-18 01:09
@dukenv0307's updated [proposal](https://github.com/Expensify/App/issues/37044#issuecomment-1962257528) looks good to me

🎀👀🎀 C+ reviewed!

> The main difference between the main and alternative solution is just the condition we use to check whether we should display the RBR in LHN or not. In main, we use: canEditMoneyRequest = !isReportApproved(moneyRequestReport) && !isSettled(moneyRequestReport?.reportID) && isRequestor and the alternative solution is just isRequestor

I think once the request has been settled, there is no action that could be required from the user, so we shouldn't display the RBR. @cead22, is that correct?

**Comment by cead22** [comment] 2024-03-18 23:33
> @dukenv0307's updated [proposal](https://github.com/Expensify/App/issues/37044#issuecomment-1962257528) looks good to me

@eVoloshchak which one, the proposed, or the alternative? I think we can improve both. The proposed one has 2 different proposed implementations of `hasMissingSmartscanFields`, so it's not clear to me how we'll update this. And both the proposed and the alternative include the check for `canEditRequest`, and we should show RBR on the LHN only for the user that requested money, and `canEditRequest` shouldn't be inside `hasMissingSmartscanFields` imo. We should either call it outside of that function, or rename `hasMissingSmartscanFields` to something like `shouldShowRBRForMissingSmartscanFields`

> I think once the request has been settled, there is no action that could be required from the user, so we shouldn't display the RBR. @cead22, is that correct?

Correct, and that will be addressed here https://github.com/Expensify/App/issues/34548

**Comment by cead22** [comment] 2024-03-19 23:29
> @cead22 My alternative proposal does not contain the check `canEditRequest`

You're right, that's my bad. I re-read my comment to see if it was a typo, but I think it was just a mistake

> @cead22 so how do you feel about [my proposal](https://github.com/Expensify/App/issues/37044#issuecomment-1961725332)? Any feedback on why it wasn't chosen also @eVoloshchak

Given @eVoloshchak picked @dukenv0307 's proposal, I assumed your root cause wasn't accurate.

---

@eVoloshchak can you re-review @brandonhenry 's proposal and @dukenv0307 's alternative proposal, select one, and share your reasoning please? Thanks

**Comment by isabelastisser** [comment] 2024-03-21 14:43
Hi @eVoloshchak, can you please provide an update? Thanks!

**Comment by eVoloshchak** [comment] 2024-03-22 09:27
> so how do you feel about https://github.com/Expensify/App/issues/37044#issuecomment-1961725332? Any feedback on why it wasn't chosen also @eVoloshchak

@brandonhenry, I didn't choose your [proposal](https://github.com/Expensify/App/issues/37044#issuecomment-1961725332), since it doesn't adhere to the latest requirements from https://github.com/Expensify/App/issues/37044#issuecomment-1984922236

> _**We've discussed this extensively, and decided that we would treat the RBR on the LHN different than the money request view.**_
The RBR on the LHN should only show for the user that made the request. The RBRs on the report preview, money request preview, and the ones in the money request view, should show to every user that has access to them
Moreover, we don't want to hide RBRs in report previews, money request previews, or the money request view, to anyone that has access to the money requests. And if they have RBRs, we should show them because there's no value in hiding information from people that have access to it.


> canEditRequest shouldn't be inside `hasMissingSmartscanFields` imo. We should either call it outside of that function, or rename hasMissingSmartscanFields to something like `shouldShowRBRForMissingSmartscanFields`

I agree with this, we shouldn't change `hasMissingSmartscanFields`, instead we could create `shouldShowRBRForMissingSmartscanFields` method, which would in turn call `hasMissingSmartscanFields` conditionally

cc: @cead22, @dukenv0307

**Comment by isabelastisser** [comment] 2024-03-25 16:07
Hi @eVoloshchak, can you please review the updated proposal above? Thanks!

**Comment by eVoloshchak** [comment] 2024-03-28 19:39
@brandonhenry's updated [proposal](https://github.com/Expensify/App/issues/37044#issuecomment-1961725332) looks good to me, it's cleaner than @dukenv0307's proposal while achieving the same result, I think we should proceed with @brandonhenry's [proposal](https://github.com/Expensify/App/issues/37044#issuecomment-1961725332)

@cead22, what do you think?

**Comment by isabelastisser** [comment] 2024-04-01 13:54
Hi @cead22, can you please follow up on this comment? Thanks!

https://github.com/Expensify/App/issues/37044#issuecomment-2025975084

**Comment by cead22** [comment] 2024-04-01 16:41
@eVoloshchak can you put a bow on the proposal you think is best please?

**Comment by isabelastisser** [comment] 2024-04-02 13:55
@eVoloshchak, please follow up on Carlos's request above. Thanks!

**Comment by isabelastisser** [comment] 2024-04-05 02:39
Bump @eVoloshchak

**Comment by isabelastisser** [comment] 2024-04-05 02:40
I DM'd @eVoloshchak. Waiting!

**Comment by eVoloshchak** [comment] 2024-04-05 10:19
This was a tough choice, both proposals share the same idea and achieve the same result

I think we should proceed with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/37044#issuecomment-1962257528), here's my rationale for that:
- @dukenv0307's proposal was the first to be updated to adhere to the new requirements from (https://github.com/Expensify/App/issues/37044#issuecomment-1984922236)
- @brandonhenry's proposal indeed does not cover the case "The RBRs on the report preview, money request preview, and the ones in the money request view, should show to every user that has access to them". I do not agree that it is a side issue and should not be considered when picking a proposal. It is pretty small, so if it was the only valid proposal, it would be acceptable to work this out on the PR stage, but not when we have an equivalent proposal without the same problem

Apologies for the initial confusion and thank you for the proposals everyone
🎀👀🎀 C+ reviewed!

**Comment by cead22** [comment] 2024-04-05 19:21
@eVoloshchak thank you for sharing your reasoning

**Comment by eVoloshchak** [comment] 2024-05-10 15:05
@isabelastisser, [PR](https://github.com/Expensify/App/pull/39970) is in review, should be merged fairly soon

**Comment by isabelastisser** [comment] 2024-06-13 18:11
@eVoloshchak, can you please complete the BZ list above? Thanks!

**Comment by isabelastisser** [comment] 2024-06-13 18:43
Payment summary:

@eVoloshchak C+ requires payment through NewDot Manual Requests `PENDING` $500
@dukenv0307 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor) - paid in Upwork.

**Comment by isabelastisser** [comment] 2024-06-14 16:41
Bump @eVoloshchak to complete the BZ list before I can close the issue. I will also DM you for visibility. Thanks!

**Comment by eVoloshchak** [comment] 2024-06-17 12:30
- The PR that introduced the bug has been identified. Link to the PR: N/A, this was not a bug, rather a change in expected behavior
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: looks like internal discussion has already took place, which has resulted in https://github.com/Expensify/App/issues/37044#issuecomment-1984922236
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? No
Is the bug related to an important user flow? Yes
Is it an impactful bug? Yes_

**Comment by eVoloshchak** [comment] 2024-06-17 12:32
**Regression Test Proposal**

**Test case 1 (to make sure RBR on the LHN is only shown for the user that made the request):**

1. Create a collect policy in OD as account A
2. Invite user B as employee
3. Log in as user B in NewDot
4. Create an expense report with an invalid receipt to fail the scanning
5. Log in to user A in NewDot
6. No RBR pinned chat appears in the LHN for the error message
7. Log in to user B in NewDot
8. Verify there is RBR pinned chat appearing in the LHN for the error message

**Test case 2 (to make sure the RBRs on the report preview, money request preview, and the ones in the money request view are shown to every user that has access to them):**

1. Create a collect policy in OD as account A
2. Invite user B as employee
3. Log in as user B in NewDot
4. Create an expense report with an invalid receipt to fail the scanning
5. Log in to user A in NewDot
6. Verify the RBRs on the report preview, money request preview, and the ones in the money request view are shown
7. Log in to user B in NewDot
8. Verify the RBRs on the report preview, money request preview, and the ones in the money request view are shown

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment] 2024-06-17 15:41
$500 approved for @eVoloshchak

**Comment by isabelastisser** [comment] 2024-06-17 16:09
All set!

**Closed by isabelastisser** 2024-06-17 16:09 UTC
Labels: External, Engineering, Daily, Internal, Overdue, Awaiting Payment, Bug
