### ISSUE TITLE
[$250] Android - Notifications - Notifications not received in correct order

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50293] opened 2024-10-05 16:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-conditions:Keep android app notifications for expensify site enabled
1. Login mweb and send message to Android app user ( notifications keep enabled)
2. Open a chat
3. Send a message
4. Send a url
5. Send a message
6. Send a URL

## Expected Result:
Notifications must be received in correct order

## Actual Result:
Notifications not received in correct order

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ae38eb30-4a2f-4639-819d-f1e67f770741

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843506678302108606</li>
        <li>Upwork Job ID: 1843506678302108606</li>
        <li>Last Price Increase: 2024-10-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by adelekennedy** [comment] 2024-10-14 02:29
waiting for proposals

**Comment by mvtglobally** [comment] 2024-10-30 09:43
Issue not reproducible during KI retests. (First week)

**Comment by adelekennedy** [comment] 2024-10-30 21:04
I think we can safely close this as I also can't reproduce

**Closed by adelekennedy** 2024-10-30 21:04 UTC
Labels: External, Daily, Help Wanted, Bug
