### ISSUE TITLE
[HOLD for payment 2024-02-26] [$250] Remove MoneyRequestMerchantPage.js and copy any changes since Nov 27 into IOURequestStepMerchant.js

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#34611] opened 2024-01-16 20:51 UTC
This is a part of https://github.com/Expensify/App/issues/29107. You can look at that issue for more context behind the cleanup process.

# Problem
The app has two redundant components:

**Old Component**: `MoneyRequestMerchantPage`
**New Component** `IOURequestStepMerchant`

# Solution
Following the examples ([example 1](https://github.com/Expensify/App/pull/33646), [example 2](https://github.com/Expensify/App/pull/32764)), the Old Component needs to be completely removed from the codebase

1. Look at the history of the Old Component
1. If there are any changes since Nov 27, 2023 which have not been added to the New Component, copy those changes
1. Replace all uses of the Old Component with the New Component
2. Remove all traces of Old Component
3. Be sure to update all routes and navigation to use the new `:action` param (instead of being hard-coded with `"create"`)
4. Update any logic like `isEditing` to use the new action param from the route
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e56ba72ea82ea62</li>
        <li>Upwork Job ID: 1747386410233479168</li>
        <li>Last Price Increase: 2024-01-24</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28132635</li>
<li>DylanDylann | Contributor | 28132636</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2024-01-16 23:27
I can help working on this!

**Comment by njmulsqb** [comment] 2024-01-17 01:39
I would love to take this!

**Comment by DylanDylann** [comment] 2024-01-17 04:22
## Proposal
     
### Please re-state the problem that we are trying to solve in this issue.
Remove MoneyRequestMerchantPage.js and copy any changes since Nov 27 into IOURequestStepMerchant.js 

### What is the root cause of that problem?
Remove deprecated component 

### What changes do you think we should make in order to solve the problem?
1. Remove MoneyRequestMerchantPage component and all traces like


https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx#L102

https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L435

https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/ROUTES.ts#L285-L288

https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/SCREENS.ts#L147

https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/libs/Navigation/types.ts#L230-L235

2. For new component IOURequestStepMerchant

In here
https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/ROUTES.ts#L352-L356
We need to use the new :action param (instead of being hard-coded with "create") like we did here

https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/ROUTES.ts#L362-L366

3. Copy changes since 27 Nov to new components based on list commit here: https://github.com/Expensify/App/commits/main/src/pages/iou/MoneyRequestMerchantPage.js

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-01-18 16:09
Pending review from @sobitneupane

**Comment by joekaufmanexpensify** [comment] 2024-01-22 14:59
@sobitneupane could you please take a look at this one?

**Comment by joekaufmanexpensify** [comment] 2024-01-22 15:05
@sobitneupane could you please take a look at this one?

**Comment by joekaufmanexpensify** [comment] 2024-01-23 14:40
[Bumped](https://expensify.slack.com/archives/C02NK2DQWUX/p1706020792682069)

**Comment by DylanDylann** [comment] 2024-01-23 19:05
@sobitneupane [Updated proposal](https://github.com/Expensify/App/issues/34611#issuecomment-1894915141) as discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1705999852089949)

**Comment by brunovjk** [comment] 2024-01-24 01:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
This belongs to [Wave 5 cleanup](https://github.com/Expensify/App/issues/29107)
Phase 2 is all about removing the original components and any of the duplicated efforts.

### What is the root cause of that problem?
Replace `MoneyRequestMerchantPage` and `EditRequestMerchantPage` to `IOURequestStepMerchant`. **This new component will handle both the create and edit flow based on `action` param**.

### What changes do you think we should make in order to solve the problem?

> Look at the history of the Old Component
> If there are any changes since Nov 27, 2023 which have not been added to the New Component, copy those changes

1. Checked the [X commits](https://github.com/Expensify/App/commits/main/src/pages/iou/MoneyRequestMerchantPage.js?since=2023-11-27&until=2024-01-23) made to the `MoneyRequestMerchantPage` component since 27-Nov. `IOURequestStepMerchant` is already updated with those changes. This way there will be **no need to arrange any changes** from `MoneyRequestMerchantPage` to be transferred to `IOURequestStepMerchant`

> Replace all uses of the Old Component with the New Component
> Remove all traces of Old Component

2. There is no use of the component other than `ModalStackNavigators`. We must remove the `MoneyRequestMerchantPage` component along with:
https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx#L102

3. The new component uses `STEP_MERCHANT` and has it own [`linkingConfig`](https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L402), [`SCREENS`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/SCREENS.ts#L131) and [`ROUTES`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/ROUTES.ts#L356-L360) already configured, we must **remove** `MERCHANT` from [`linkingConfig`](https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L435), [`SCREENS`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/SCREENS.ts#L147) and [`ROUTES`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/ROUTES.ts#L289-L292)

> Be sure to update all routes and navigation to use the new :action param (instead of being hard-coded with "create")

4. Update [Type navigation](https://github.com/Expensify/App/blob/0706c8c1a8914fa5ef4a7a05630e793ff691fd0a/src/libs/Navigation/types.ts#L230-L235)
to
    ```
        [SCREENS.MONEY_REQUEST.STEP_MERCHANT]: {
            iouType: string;
            transactionID: string;
            reportID: string;
            backTo: string;
        };
    ```
5. Update [route and getRoute](https://github.com/Expensify/App/blob/0706c8c1a8914fa5ef4a7a05630e793ff691fd0a/src/ROUTES.ts#L356-L360)
to
    ```
        MONEY_REQUEST_STEP_MERCHANT: { 
            route: ':action/:iouType/merchant/:transactionID/:reportID', 
            getRoute: (action: ValueOf<typeof CONST.IOU.ACTION>, iouType: ValueOf<typeof CONST.IOU.TYPE>, transactionID: string, reportID: string, backTo = '') => 
                getUrlWithBackToParam(`${action}/${iouType}/merchant/${transactionID}/${reportID}`, backTo), 
    }, 
    ```
6. Update [MoneyTemporaryForRefactorRequestConfirmationList](https://github.com/Expensify/App/blob/c3f7bccc1050988c6352ea63fa00bf327761587a/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L718)
to
    ```
    Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_MERCHANT.getRoute(CONST.IOU.ACTION.CREATE, iouType, transaction.transactionID, reportID, Navigation.getActiveRouteWithoutParams()));
    ```
> Update any logic like isEditing to use the new action param from the route

[points that should be taken into consideration](https://github.com/Expensify/App/issues/34609#issuecomment-1901117617)

- _"Where else do the routes need updated (when it's navigating to the edit view)"_:
7. Update [MoneyRequestView](https://github.com/Expensify/App/blob/872eb17903f18f9a99d69abe6e45d6e736c70c77/src/components/ReportActionItem/MoneyRequestView.js#L315)
to
    ```
    Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_MERCHANT.getRoute(CONST.IOU.ACTION.EDIT, CONST.IOU.TYPE.REQUEST, transaction.transactionID, report.reportID, Navigation.getActiveRouteWithoutParams()))
    ```
- _"setMoneyRequestMerchant_temporaryForRefactor needs to be updated to have an isDraft param that's based on the new "action" route param."_:

8. Update [IOURequestStepMerchant.js](https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepMerchant.js) to use `isDraft` :
    ```
        route: {
            params: {action, transactionID, backTo},
        },
    ...
    const isDraft = action === CONST.IOU.ACTION.CREATE;
    ...
        Navigation.goBack(isDraft && backTo || ROUTES.HOME);
    ...
    const updateMerchant = (value) => {
        IOU.setMoneyRequestMerchant_temporaryForRefactor(transactionID, value.moneyRequestMerchant, isDraft);
        navigateBack();
    };
    ```

9. Update [setMoneyRequestMerchant_temporaryForRefactor](https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/actions/IOU.js#L213-L215)  to use `isDraft` :
    ```
    ...
     * @param {Boolean} isDraft - Indicates whether it's a draft or not
     */
    function setMoneyRequestMerchant_temporaryForRefactor(transactionID, merchant, isDraft) {
    const key = isDraft ? ONYXKEYS.COLLECTION.TRANSACTION_DRAFT : ONYXKEYS.COLLECTION.TRANSACTION;
        Onyx.merge(`${key}${transactionID}`, {merchant: merchant.trim()});
    }
    ```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by sobitneupane** [comment] 2024-01-24 02:24
Sorry for the delay. I won't be able to review the proposals soon.  So, unassigning.

**Comment by sobitneupane** [comment] 2024-01-24 02:25
@joekaufmanexpensify Can you please re-apply the External label to re-assign new C+.

**Comment by joekaufmanexpensify** [comment] 2024-01-24 15:33
Done!

**Comment by DylanDylann** [comment] 2024-01-24 16:47
@hoangzinh [Updated proposal](https://github.com/Expensify/App/issues/34611#issuecomment-1894915141) to cover edit split flow as discuss [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1706112572389079?thread_ts=1705999852.089949&cid=C01GTK53T8Q)

**Comment by brunovjk** [comment] 2024-01-24 17:07
## Proposal
[Updated](https://github.com/Expensify/App/issues/34611#issuecomment-1907179442)

The `isEditing` part I updated following [discussions ](https://expensify.slack.com/archives/C01GTK53T8Q/p1705999852089949)

**Comment by joekaufmanexpensify** [comment] 2024-01-25 16:04
Pending review of proposals

**Comment by joekaufmanexpensify** [comment] 2024-01-29 14:35
Proposal pending sign off from @cead22

**Comment by joekaufmanexpensify** [comment] 2024-01-30 14:27
Still pending sign off

**Comment by joekaufmanexpensify** [comment] 2024-01-31 15:22
Bumped 1:1

**Comment by joekaufmanexpensify** [comment] 2024-02-01 21:03
@DylanDylann is there an ETA for a PR here?

**Comment by DylanDylann** [comment] 2024-02-02 04:59
I am working on PR, there are many changes. I will finish the PR today

**Comment by cead22** [comment] 2024-02-16 03:08
Oh hmmm, maybe we need to wait for the prod deploy so the payment automation kicks in, I'll reopen

**Comment by joekaufmanexpensify** [comment] 2024-02-23 14:02
@hoangzinh is any BZ checklist needed here?

**Comment by joekaufmanexpensify** [comment] 2024-02-23 15:33
Sounds good! All set to issue payment on the 26th then.

**Comment by joekaufmanexpensify** [comment] 2024-02-26 15:30
All set to issue payment. We need to pay: 

- @hoangzinh $250 for C+. Paid via upwork. 
- @DylanDylann $250 for PR. Paid via upwork.

**Comment by joekaufmanexpensify** [comment] 2024-02-26 15:33
@hoangzinh $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-02-26 15:33
@DylanDylann $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-02-26 15:35
I also noticed @maddylewis issued a [third offer](https://www.upwork.com/nx/wm/offer/100485807) for this job to a different contributor. I don't see this contributor worked on this job, so thinking this was by mistake. Checking with Maddy, but not blocking on this, since all of the actual payments have been issued.

**Comment by joekaufmanexpensify** [comment] 2024-02-26 15:35
All set. Thanks everyone!

**Closed by joekaufmanexpensify** 2024-02-26 15:35 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
