### ISSUE TITLE
[$500] Task - Deleted task message shown for a second and disappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34803] opened 2024-01-19 14:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tab fab ---- Assign task
3. Enter title
4. Tap next
5. Select a user to share somewhere
6. Tap confirm task
7. Open the newly created task
8. Tap 3 dots on top right and tap delete task
9. Tap confirm delete task

## Expected Result:
Deleted task message must not be disappeared

## Actual Result:
Deleted task message shown for a second and disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/48c5d0c5-d2d7-4ddf-a322-58db0dbdd8fb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb25861564b8fad6</li>
        <li>Upwork Job ID: 1748353253799964672</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2024-01-19 14:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deleted task message shown for a second and disappears

### What is the root cause of that problem?
We miss some props in optimistic report action when deleting task 
### What changes do you think we should make in order to solve the problem?
We should update optimistic data of report actions like response from BE

### What alternative solutions did you explore? (Optional)
NA

**Comment by rojiphil** [comment] 2024-01-19 15:54
This [PR here](https://github.com/Expensify/App/pull/30236) could solve this issue.
Please hold on until the PR is resolved.
cc @abdulrahuman5196

**Comment by mallenexpensify** [comment] 2024-01-19 22:21
> Expected Result:
Deleted task message must not be disappeared

@lanitochka17 , and/or others, I would think the task should be removed and disappear if it's deleted, right?  I could see there _maybe_ being an issue with the click flash but, for some reason, I kinda _like_ to flash to denote the task has been deleted.

**Comment by abdulrahuman5196** [comment] 2024-01-22 11:19
> This [PR here](https://github.com/Expensify/App/pull/30236) could solve this issue. Please hold on until the PR is resolved. cc @abdulrahuman5196

Yes. Already part of this - https://github.com/Expensify/App/issues/27939#issuecomment-1903792580

We can close this issue as duplicate.

**Closed** 2024-01-23 04:10 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
