### ISSUE TITLE
[HOLD for payment 2024-04-15] [$1000] Infinite loading on Invite members page after refresh

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22508] opened 2023-07-09 03:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces
2. Select any workspace
3. Go to Members > Invite
4. Refresh website
## Expected Result: 
Show contacts list to invite
## Actual Result: 
Show skeleton forever

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/eff169d7-15e0-4b0c-8029-0b13183cf0fc

![Snip - (1) New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/43996225/1147ba13-27bb-4fbb-a8d1-d5eb17d887b4)
**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688833373673129
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0160eb205488d8fcdd</li>
        <li>Upwork Job ID: 1691081434892730368</li>
        <li>Last Price Increase: 2023-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2023-07-12 09:24
I'm not able to reproduce this one.

**Comment by situchan** [comment] 2023-07-18 12:17
This is still reproducible to everyone.
@muttmuure if you're not able to reproduce, can you please ask another BZ member internally?

**Comment by muttmuure** [comment] 2023-08-14 17:13
@Santhosh-Sellavel if you are able to take a look [here](https://github.com/Expensify/App/issues/22508#issuecomment-1677182516) that would be great

**Comment by b4s36t4** [comment] 2023-08-14 20:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Infinite loading on Invite members page after refresh
### What is the root cause of that problem?
When we navigate using the URL there is no `transitionEnd` event occurs because it's already happened and we're registering ht listener after the event passed which is the reason for the state `didScreenTransitionEnd` not to update.

Because of `didScreenTransitionEnd` value is still `false` and the line here https://github.com/Expensify/App/blob/1e3f952574e2bbff9566c86c686a0589a5063a55/src/pages/workspace/WorkspaceInvitePage.js#L226 shows the loader infinitely/till `didScreenTransitionEnd` becomes true.

### What changes do you think we should make in order to solve the problem?
As followed up the RCA `transitionEnd` event is occurring but we're capturing it anywhere.

If we can capture it we can solve this issue. We can do this by using the following changes in codebase.

1. Add `listeners` to the navigation/navigation screens here in https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L22 this component like and create a new `ONYX` key to track the transition state.

```jsx
    <ModalStackNavigator.Screen
    ....
    listeners={() => ({
        transitionEnd: () => {
            // eslint-disable-next-line rulesdir/prefer-actions-set-data
            Onyx.set(ONYXKEYS.TRANSITION_END, true);
        },
    })}
```

Using the above change we can track the `transitionEnd` event and we're setting the onyxKey to true.

2. Reset the Onyx Key whenever there is a change in the navigation state. Here in this object https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L7-L11 we need to add a new `listeners` property which reset the onyx key.

```jsx
listeners: {
        state: () => {
            Onyx.set(ONYXKEYS.TRANSITION_END,false)
        }
    }
```

3. Track this Onyx key inside `ScreenWrapper` component and use `componentDidUpdate` to run the logic for variables and function calls.
https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/components/ScreenWrapper/index.js#L155

```jsx
withOnyx({
        completed: {
            key: ONYXKEYS.TRANSITION_END,
        },
    }),
```

and 

```jsx
componentDidUpdate() {
        if (!this.props.completed) return;
        this.setState({didScreenTransitionEnd: true});
        this.props.onEntryTransitionEnd();
    }
```


**This also solves focus issue with TaskTitle page mentioned here #22850. Not able to re-produce on new or staging but was able re-produce it in dev.**

> This doesn't break when the members are high/in high-traffic account.

### What alternative solutions did you explore? (Optional)
NA

## Result

https://github.com/Expensify/App/assets/59088937/9a855c5f-79d8-4a5f-8816-dd3f8af407b0

https://github.com/Expensify/App/assets/59088937/3a515d02-d744-47d8-ba29-f6e066e72cf1

**Comment by Santhosh-Sellavel** [comment] 2023-08-15 20:29
Unable to reproduce this on Main & Staging.

https://github.com/Expensify/App/assets/85645967/7a107ab6-3cdf-4a9e-ad7b-4624161a2632

@aimane-chnaif 
> This is constantly reproducible to me

Do you see any logs or any response errors

**Comment by b4s36t4** [comment] 2023-08-15 20:40
@Santhosh-Sellavel Please un-install/move to trash the expensify app. Because of that (this happens before the page fully load) and after closing the popup website is getting focus. You can re-produce it local dev environment or for a moment delete the desktop app.

**Comment by Santhosh-Sellavel** [comment] 2023-08-15 20:43
> @Santhosh-Sellavel Please uninstall/move to trash the expensify app. Because of that (this happens before the page fully load) and after closing the popup website is getting focus. You can re-produce it local dev environment or for a moment delete the desktop app.

@aimane-chnaif  Is this ☝️  relevant here?

**Comment by Santhosh-Sellavel** [comment] 2023-08-15 20:47
What version of chrome you are using?

**Comment by Santhosh-Sellavel** [comment] 2023-08-15 20:48
@situchan Can you reproduce this issue still?

**Comment by b4s36t4** [comment] 2023-08-15 20:48
@Santhosh-Sellavel it's not relevant bug... because of that RCA is breaking, that's all.

**Comment by situchan** [comment] 2023-08-15 20:49
> @situchan Can you reproduce this issue still?

yes still

**Comment by Santhosh-Sellavel** [comment] 2023-08-15 20:51
@b4s36t4 

> When we navigate using the URL there is no `transitionEnd` event occurs because it's already happened and we're registering the listener after the event passed which is the reason for the state `didScreenTransitionEnd` not to update.

If that's the case, I'm not sure how its loading here

https://github.com/Expensify/App/assets/85645967/e1cd5f18-ae12-4f15-b269-4a0d3acdb2ac

**Comment by Santhosh-Sellavel** [comment] 2023-08-15 20:53
> > @situchan Can you reproduce this issue still?
> 
> yes still

@situchan Can you confirm like @aimane-chnaif did [here](https://github.com/Expensify/App/issues/22508#issuecomment-1679570681)

Also what version of chrome are you using?

**Comment by situchan** [comment] 2023-08-15 20:58
Strange. I reproduced on staging when I report this. But not able to reproduce.
Still 100$ reproducible on localhost

https://github.com/Expensify/App/assets/108292595/25785cb6-2dd7-4f62-b827-59a5871d6880

**Comment by b4s36t4** [comment] 2023-08-15 20:59
I'm not able re-produce it in staging or new... but able to in dev.

https://github.com/Expensify/App/assets/59088937/6dee7d60-69fa-48b8-b407-afc449d2cb49.
Even this https://github.com/Expensify/App/issues/22850. issue is also not re-produceable on staging or new.

**Comment by b4s36t4** [comment] 2023-08-15 21:04
https://github.com/Expensify/App/assets/59088937/336ad3ff-14bd-4956-b500-483d32a39fe5

**Comment by muttmuure** [comment] 2023-08-22 17:23
If we can't reproduce this on staging or prod I will close for now so we can focus on other bugs.

**Comment by lanitochka17** [comment] 2023-12-11 17:01
Issue reproducible on the latest build 1.4.11-1

![image](https://github.com/Expensify/App/assets/78819774/e6e1b75a-fd0e-40c9-ac9f-9039836a78f9)

**Comment by Santhosh-Sellavel** [comment] 2023-12-13 20:05
Do we have any proposals after reopening the issue? 

I'm seeing a blank list invite page after refresh, @lanitochka17 can you confirm this one, I'm not seeing skeleton also

<img width="986" alt="Screenshot 2023-12-14 at 1 33 19 AM" src="https://github.com/Expensify/App/assets/85645967/6a593fa2-8a85-43f6-8a31-ed29e6cc6724">

**Comment by muttmuure** [comment] 2023-12-18 11:59
@Santhosh-Sellavel @bernhardoj has made a proposal [here](https://github.com/Expensify/App/issues/22508#issuecomment-1858871846)!

**Comment by DylanDylann** [comment] 2023-12-18 17:10
## Proposal
   
### Please re-state the problem that we are trying to solve in this issue.
- Infinite loading on Invite members page after refresh

### What is the root cause of that problem?
- After reloading the page, the ```didScreenTransitionEnd``` bellow:
https://github.com/Expensify/App/blob/eb5f3791d010465c60a259027bd4ca6620792f7d/src/pages/workspace/WorkspaceInvitePage.js#L271
is still false because if we reload the page, there is no event "transitionEnd" triggered.
https://github.com/Expensify/App/blob/798deda1a58c0be7579e5042f745566af58e384f/src/components/ScreenWrapper/index.js#L81-L89

### What changes do you think we should make in order to solve the problem?
- We can still use the ```didScreenTransitionEnd```, but it is from ```isScreenTransitionEnded``` in [here](https://github.com/Expensify/App/blob/main/src/hooks/useAutoFocusInput.js)

**Comment by muttmuure** [comment] 2023-12-20 13:20
Not overdue

**Comment by Santhosh-Sellavel** [comment] 2023-12-20 18:45
Thanks @bernhardoj for pointing out, that this seems to be a regression from the PR of the issue which is in the regression period & will be addressed by them!

**Comment by situchan** [comment] 2024-01-08 14:50
This bug is still reproducible in latest version (v1.4.22-3)
The root cause was not fixed yet in any of the PRs.

https://github.com/Expensify/App/assets/108292595/4ee8961a-c0a2-4b9a-85a3-995b41f6c4d6

**Comment by situchan** [comment] 2024-01-29 16:08
This is still reproducible.
@Santhosh-Sellavel is OOO this week (https://expensify.slack.com/archives/C02NK2DQWUX/p1706377711208419)
I can take over and push this forward if needed.
cc: @muttmuure

**Comment by Santhosh-Sellavel** [comment] 2024-02-02 18:54
This was waiting for regression handling as mentioned [here](https://github.com/Expensify/App/issues/22508#issuecomment-1864971219), the issue is not reproducible for me.

https://github.com/Expensify/App/assets/85645967/31ede658-737c-4194-aaec-00e50a38c16e

**Comment by situchan** [comment] 2024-02-02 18:57
The root cause is not fixed yet. Still reproducible to me


https://github.com/Expensify/App/assets/108292595/63a61162-b8d4-47a3-be50-71f29625f465

**Comment by Santhosh-Sellavel** [comment] 2024-02-02 19:05
> The root cause is not fixed yet. Still reproducible to me

Please write a clear step on how to reproduce this one, and elaborate more about what's the root cause here.

**Comment by situchan** [comment] 2024-02-02 19:13
Repro step is same as OP.


https://github.com/Expensify/App/assets/108292595/28d46850-a577-42b7-a8d1-f8b9cad1f5b3

The root cause is explained in @tienifr's RCA in their [proposal](https://github.com/Expensify/App/issues/22508#issuecomment-1628779538)

The interesting thing is that `transitionEnd` is randomly triggered after refresh page.
When triggered, bug not reproducible.
When not triggered, bug reproducible.

So the original root cause is in react-navigation.

**Comment by Santhosh-Sellavel** [comment] 2024-02-02 19:39
I can reproduce it on production sometimes. But on dev, I can no longer reproduce this


https://github.com/Expensify/App/assets/85645967/50cdeeb8-7430-40af-84e3-05fbeca72164

**Comment by bernhardoj** [comment] 2024-02-03 02:41
This is reproducible on the task page for me. You can read the root cause on my [proposal](https://github.com/Expensify/App/issues/22508#issuecomment-1858871846)

_I still prefer my main solution_

**Comment by Santhosh-Sellavel** [comment] 2024-02-06 21:10
We have two proposals so far, but looking for more options. Both seem like work-around

> The interesting thing is that transitionEnd is randomly triggered after refresh page.
> When triggered, bug not reproducible.
> When not triggered, bug reproducible.
> So the original root cause is in react-navigation.

Need to find the reason behind the randomness, fix it properly

**Comment by bernhardoj** [comment] 2024-02-07 04:17
@Santhosh-Sellavel have you read my proposal? It's well explained the root cause.

**Comment by muttmuure** [comment] 2024-02-08 11:52
For ease of scrollback, the proposal is [here](https://github.com/Expensify/App/issues/22508#issuecomment-1858871846).

**Comment by Santhosh-Sellavel** [comment] 2024-02-12 19:58
Since you have more context @situchan please take over this as C+ if you have bandwidth.

Unassigning due to low bandwidth.

cc: @muttmuure Please assign @situchan or assign a new C+ here, thanks!

**Comment by situchan** [comment] 2024-02-12 20:02
Sure I can take over. Thanks

**Comment by situchan** [comment] 2024-02-22 15:23
@bernhardoj you mean the root cause is in Onyx, nothing related to react-navigation?
And your solution is to add `initialValue: true` [here](https://github.com/Expensify/App/blob/e6b6aa940eb8ec1cb59f6662b3baf553d943049d/src/pages/workspace/withPolicyAndFullscreenLoading.tsx#L59-L61), right?

**Comment by bernhardoj** [comment] 2024-02-23 03:24
> you mean the root cause is in Onyx, nothing related to react-navigation?

Correct.

> And your solution is to add initialValue: true [here](https://github.com/Expensify/App/blob/e6b6aa940eb8ec1cb59f6662b3baf553d943049d/src/pages/workspace/withPolicyAndFullscreenLoading.tsx#L59-L61), right?

For the workspace invite page, yes. For the task assignee selector page, we need to set the default value (empty object) of the task [here](https://github.com/Expensify/App/blob/72bdedb226d0813a68e2b8caa909194064ed92a9/src/pages/tasks/TaskAssigneeSelectorModal.js#L232-L234).

**Comment by situchan** [comment] 2024-02-26 13:57
@bernhardoj still reproducible after applying your solution


https://github.com/Expensify/App/assets/108292595/f74adddb-9ba9-4880-9780-af25072ce6c7

**Comment by situchan** [comment] 2024-02-26 13:59
@tienifr can you please share your test branch?

**Comment by bernhardoj** [comment] 2024-02-26 14:43
@situchan oh, please add a default value (empty object) for this onyx data too
https://github.com/Expensify/App/blob/9bfe961622d03de5ac8e18652bbb56dda5ed9f60/src/pages/workspace/WorkspaceInvitePage.tsx#L350-L352
https://github.com/Expensify/App/blob/9bfe961622d03de5ac8e18652bbb56dda5ed9f60/src/pages/workspace/withPolicy.tsx#L142-L147

**Comment by situchan** [comment] 2024-03-13 19:39
Not overdue

**Comment by situchan** [comment] 2024-03-28 02:12
Awaiting proposals

**Comment by bernhardoj** [comment] 2024-03-28 07:11
Oh, I didn't realize you were asking for a test branch. Here is the test branch: https://github.com/bernhardoj/Expensify/tree/fix/22508-infinite-loading-invite-page

Fixed for WS & room invite page and task assignee selector page.

**Comment by situchan** [comment] 2024-03-28 09:50
@bernhardoj thanks. The root cause is correct. I am still testing your solution to find any regressions.

Btw, how about moving this code to parent HOC?
https://github.com/Expensify/App/blob/ff961e46e22740813177d58d1e462cd9b875d6b2/src/pages/workspace/WorkspaceInvitePage.tsx#L89-L99

This is regression-free and fixes the root cause

**Comment by situchan** [comment] 2024-03-28 10:07
> 
> _oh, do you mean we create a new HOC to specifically listen for transitionEnd?_

yes

**Comment by bernhardoj** [comment] 2024-03-28 10:12
That's a good idea. I will try it first.

> or withPolicyAndFullscreenLoading if applicable

I think it will still have the same issue because it is wrapped with onyx. I think creating a new one will make it reusable too as we will use it on 3 pages.

**Comment by bernhardoj** [comment] 2024-03-28 10:51
It works well, here is another test branch for the HOC approach:
https://github.com/bernhardoj/Expensify/tree/fix/22508-infinite-loading-invite-page-2

**Comment by situchan** [comment] 2024-03-28 10:53
> It works well, here is another test branch for the HOC approach: https://github.com/bernhardoj/Expensify/tree/fix/22508-infinite-loading-invite-page-2

Please update your proposal so add it to your alternative solution

**Comment by bernhardoj** [comment] 2024-03-28 10:59
Updated the [proposal](https://github.com/Expensify/App/issues/22508#issuecomment-1858871846) to include the HOC approach.

**Comment by situchan** [comment] 2024-03-28 11:04
@bernhardoj's [proposal (first alternative)](https://github.com/Expensify/App/issues/22508#issuecomment-1858871846) of introducing dedicated HOC looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by rlinoz** [comment] 2024-03-28 21:46
Thanks for the work here, assigning @bernhardoj

**Comment by bernhardoj** [comment] 2024-03-29 02:09
PR is ready

cc: @situchan

**Comment by rlinoz** [comment] 2024-04-15 12:00
I don't think we need a regression test for this one, what do you think @bernhardoj @situchan ?

**Comment by muttmuure** [comment] 2024-04-17 15:23
@bernhardoj paid, @situchan offer sent

**Comment by rlinoz** [comment] 2024-04-22 11:37
Can we close this one then?

**Comment by muttmuure** [comment] 2024-04-25 08:13
Still waiting for @situchan to accept the offer https://www.upwork.com/nx/wm/offer/101907756

**Comment by rlinoz** [comment] 2024-04-29 12:22
@situchan is OOO https://expensify.slack.com/archives/C02NK2DQWUX/p1711774859535809

**Comment by muttmuure** [comment] 2024-05-08 07:56
Waiting for @situchan to accept the offer

**Comment by situchan** [comment] 2024-05-17 00:38
Sorry for late. Accepted

**Comment by rlinoz** [comment] 2024-06-17 14:43
@muttmuure moving back to daily since @situchan is back

**Comment by muttmuure** [comment] 2024-06-19 09:55
Paid up

**Closed by muttmuure** 2024-06-19 09:55 UTC
Labels: External, Daily, Needs Reproduction, Awaiting Payment, Bug
