### ISSUE TITLE
[HOLD for payment 2022-10-31] [$250] Chat - Composer goes to the top on pressing expand @thesahindia

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11437] opened 2022-09-29 18:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to any chat
3. Add few lines and press expand button at the left corner

## Expected Result:
The composer should expand and shouldn't move

## Actual Result:
The composer goes to the top

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App
- Mobile Web/safari

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193113628-adebaae5-99be-46bc-9122-cc330a85022d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @thesahindia

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664196729312989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment] 2022-09-29 20:25
### Proposal

It is happening because the ReportActionCompose is wrapped by OfflineWithFeedback
https://github.com/Expensify/App/blob/b058975f68c53904a9724d1ccccb265f451f3649/src/pages/home/ReportScreen.js#L290-L296

To solve it we need to use style.h100 for the View at 90 and 92
We can pass styles for the first `View` using `style` but we will have to add another prop to pass style to 92 or we can just use styles.h100 or styles.flex1 because it's not breaking anything.

https://github.com/Expensify/App/blob/b058975f68c53904a9724d1ccccb265f451f3649/src/components/OfflineWithFeedback.js#L90-L94

**Comment by amyevans** [comment] 2022-09-30 15:11
Reproducible, releasing to `External`. A reminder @Puneet-here that you need to wait for the `Help wanted` label before submitting proposals, thanks! 😄

**Comment by laurenreidexpensify** [comment] 2022-10-03 09:12
Not overdue, reviewing this morning

**Comment by Beamanator** [comment] 2022-10-03 09:21
Yep ^ @rushatgabhane would you mind reviewing the one proposal in this issue today?

**Comment by laurenreidexpensify** [comment] 2022-10-03 11:14
https://www.upwork.com/jobs/~01b201949be1d1680f

**Comment by Beamanator** [comment] 2022-10-04 13:40
Makes sense to me @rushatgabhane

**Comment by Beamanator** [comment] 2022-10-05 14:49
Ooh thanks for bringing that up @aimane-chnaif , this one is tough since the proposal are both small, but I agree with @rushatgabhane let's change up who was hired 👍

**Comment by Beamanator** [comment] 2022-10-14 13:05
PR under review, should be merged soon 👍

**Comment by laurenreidexpensify** [comment] 2022-10-31 11:08
Payments: 

- [ ] @thesahindia issue reporter PAID 
- [ ] @rushatgabhane Contributor Plus reviewer
- [ ] @aimane-chnaif Contributor 

@rushatgabhane @aimane-chnaif as soon as you've accepted job in Upwork I will issue payment. Thanks

**Comment by laurenreidexpensify** [comment] 2022-10-31 14:08
Everyone has been paid 👍

**Closed by laurenreidexpensify** 2022-10-31 14:08 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
