### ISSUE TITLE
iOS - Composer flickers when navigating back from header settings with a swipe to the right

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53588] opened 2024-12-04 18:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2336@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open iOS hybrid app
2. Create a workspace and navigate to workspace chat
3. Tap on header 
4. Navigate back by swiping from left to right

## Expected Result:
Composer doesn't flicker

## Actual Result:
Composer flickers before opening keyboard

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/efc19666-680f-49b3-8567-a588839cad98

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment] 2024-12-10 12:55
I can't reproduce this on my physical iphone and it seems like extreme UI polish which is not an immediate priority to make the app usable and migrate over our cohorts, so going to close this out.

I can't even really see the flicker in the video linked above TBH.

**Closed by zanyrenney** 2024-12-10 12:55 UTC
Labels: Daily, Overdue, Bug
