### ISSUE TITLE
[HOLD for payment 2023-06-05] [$1000] No hover effect on reactions list

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18905] opened 2023-05-14 11:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. open  group > send message > react with 2 or more accounts
2. hover over the members in list

## Expected results: 
hover effect should be there like other similar components in the app (like start a call menu). Additionally, open the user detail page when the user clicks on a user profile (more details [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1684246281785029)). 

## Actual results: 
no hover effect

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13.
**Reproducible in staging?:** y 
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/184a5593-07e8-42aa-88b6-3251d77b4673

<img width="957" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/48502b91-1909-4633-aa73-36f163dda679">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683975718761019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0b60ca5f036fe39</li>
        <li>Upwork Job ID: 1658661267676348416</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by PrashantMangukiya** [comment] 2023-05-14 11:31
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
No hover effect on reactions list

### What is the root cause of that problem?
Reaction list render via `OptionRow` as shown below:
https://github.com/Expensify/App/blob/148517a48b9ce4418c7e5acedd508f98633122c1/src/pages/home/report/ReactionList/BaseReactionList.js#L43-L63

We can see `hoverStyle` not passed to OptionRow. So it will not show hover effect, this is the root cause of the problem.

### What changes do you think we should make in order to solve the problem?
We have to pass `hoverStyle` prop to `OptionRow` component as shown code below:

```javascript
const renderItem = ({item}) => (
    <OptionRow
        hoverStyle={styles.hoveredComponentBG}   // ** ADD THIS ***
        ...
    />
);
``` 

This will solve the issue and show hover effect.


### What alternative solutions did you explore? (Optional)
None

**Comment by JmillsExpensify** [comment] 2023-05-17 02:30
Hmm, this "bug" is debatable vs a new feature, though I'm triaging it to keep the issue moving while I'm at a conference.

**Comment by JmillsExpensify** [comment] 2023-05-22 19:24
Quick heads up that I'm out of office this week, so if someone from the BugZero team is needed then please re-apply the `bug` label.

**Comment by marcochavezf** [comment] 2023-05-22 20:16
@thesahindia @dhairyasenjaliya let's re-use this GH atm. I agree that this can be debatable, and maybe we'd need to discuss it to define how we can consider this one since it was reported as a bug before the proposal (improvement) was reported/proposed. I will update the OP

**Comment by JmillsExpensify** [comment] 2023-06-08 03:47
Ah yes, thanks. We still need to close out the BZ checklist first and agree on payment. @thesahindia would you mind helping us cross off everything but the last item in the checklist above?

**Comment by JmillsExpensify** [comment] 2023-06-08 03:49
As for the payments, this is what I'm seeing:

Issue reporter: @chiragxarora $250
Contributor: @dhairyasenjaliya $1,000
Contributor+: @thesahindia $1,000

Are we aligned on the above before I issue contracts and what not in Upwork?

**Comment by chiragxarora** [comment] 2023-06-08 13:34
Am I not eligible for the reporting bonus since one way or another the feature originated from this report only.
@JmillsExpensify ?

**Comment by chiragxarora** [comment] 2023-06-08 13:34
Am I not eligible for the reporting bonus since one way or another the feature originated from this report only.
@JmillsExpensify ?

**Comment by chiragxarora** [comment] 2023-06-08 13:34
Am I not eligible for the reporting bonus since one way or another the feature originated from this report only.
@JmillsExpensify ?

**Comment by JmillsExpensify** [comment] 2023-06-09 04:28
@chiragxarora Sorry I'm not clear what you're referring to. The [bonus only applies to PRs](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by JmillsExpensify** [comment] 2023-06-09 04:29
As for the bonus, @marcochavezf can you please clear up the bonus before we issue payments? Let's make sure we're all on the same page.

**Comment by JmillsExpensify** [comment] 2023-06-09 04:32
As for who to award the reporting payment to, can someone help me determine where @dhairyasenjaliya was the report and not @chiragxarora? Perhaps more importantly, we don't pay for feature requests, so if this is not a bug then there is no reporting payment either.

**Comment by marcochavezf** [comment] 2023-06-14 00:57
@JmillsExpensify for this case, I also think it's appropriate to reward @chiragxarora as the issue reporter. This issue resides in a gray area between bug and improvement. However, since we have similar hover effects in other parts of the app, a natural solution would be to show a list of the reactions. Also, the issue was reported before ([May 13](https://expensify.slack.com/archives/C049HHMV9SM/p1683975718761019)) @dhairyasenjaliya reported the improvement ([May 16](https://expensify.slack.com/archives/C01GTK53T8Q/p1684246281785029)). 

Regarding the bonus for urgency, yeah I agree with it.

**Comment by JmillsExpensify** [comment] 2023-06-27 04:54
Ok thanks for walking me through this one. 

So that leaves us:

Issue reporter: @chiragxarora $250
Contributor: @dhairyasenjaliya $1,500
Contributor+: @thesahindia $1,500

Upwork job [is here](https://www.upwork.com/jobs/~016ac25a7e41589287). I'll issue bonuses on final payout.

**Comment by JmillsExpensify** [comment] 2023-06-27 04:58
Everyone should have an offer in their Upwork inbox. Let me know if you don't.

**Comment by JmillsExpensify** [comment] 2023-06-28 18:28
Contributor and issue reporter have been paid out. @thesahindia you have an offer outstanding in Upwork when you have a chance to get to it.

**Comment by JmillsExpensify** [comment] 2023-06-28 20:27
Awesome! Everyone is now paid out. Closing this one out.

**Closed by JmillsExpensify** 2023-06-28 20:27 UTC
Labels: External, Daily, Awaiting Payment, Bug
