### ISSUE TITLE
[$500] mWeb - Chat - Tapping on new messages after marking a message unread leads to a blank page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31591] opened 2023-11-20 22:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in
3. Open a group conversation with a lot of messages
4. Swipe to the middle of the page and mark any message as unread
5. Swipe to the top of the page
6. Tap on the "New messages" button

## Expected Result:
User should be redirected to the unread message.

## Actual Result:
Tapping on new messages after marking a message unread leads to a blank page

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/24775701-2be1-4056-b6dd-d419df8ee56c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b6f62003e67ff2c</li>
        <li>Upwork Job ID: 1726728849329471488</li>
        <li>Last Price Increase: 2023-11-27</li>
<li>Automatic offers: </li>
<ul>
<li>wlegolas | Contributor | 27951745</li>
</ul></li>
    </ul>
</details>

**Comment by wlegolas** [comment] 2023-11-21 03:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

mWeb - The keyboard opens after requesting money in 1:1 DM

### What is the root cause of that problem?

The `FloatingMessageCounter` component receives in the property `onClick` the action to be executed when clicking in the floating message element, the `ReportActionsList` component uses the `FloatingMessageCounter` and pass to the `onClick` property the method `scrollToBottomAndMarkReportAsRead`, this method will always scrolls to the bottom:

https://github.com/Expensify/App/blob/8c909d1a0b1c16d3130cc6d220f656f2ba9b2bdd/src/pages/home/report/ReportActionsList.js#L303-L307

### What changes do you think we should make in order to solve the problem?

We should improve the method `scrollToBottomAndMarkReportAsRead` to find the first index of the first unread message and using the `scrollToIndex` method from the `reportScrollManager` set the scrolls to the first unread message.

For example,

```js
const scrollToBottomAndMarkReportAsRead = () => {
    const firstUnreadMessage = _.findIndex(sortedReportActions, (reportAction, index) => shouldDisplayNewMarker(reportAction, index));

    if (firstUnreadMessage > -1) {
        reportScrollManager.scrollToIndex(firstUnreadMessage);
    } else {
        reportScrollManager.scrollToBottom();
    }

    readActionSkipped.current = false;
    Report.readNewestAction(report.reportID);
};
```

### What alternative solutions did you explore? (Optional)

N/A

**POC**

**Comment by wlegolas** [comment] 2023-11-21 12:21
Hi @parasharrajat 

Sorry, I focused only on the solution to scroll to the first unread message.

I updated my proposal with this root cause and the changes that we need to make to fix it.

If you have any questions, please feel free to contact me

**Comment by wlegolas** [comment] 2023-11-21 23:43
## Proposal
[Updated](https://github.com/Expensify/App/issues/31591#issuecomment-1820145900)

**Comment by JmillsExpensify** [comment] 2023-11-24 19:48
Still working through proposals

**Comment by JmillsExpensify** [comment] 2023-11-29 00:24
Waiting on proposal review

**Comment by wlegolas** [comment] 2023-12-05 02:44
Hi Melvin, I've just started to change the code. In the next days, I will send the PR with the changes.

**Comment by wlegolas** [comment] 2023-12-05 17:00
> 2. We might be able to use `currentUnreadMarker` to get the unread marker location instead of recalculating.

Hi, @parasharrajat regarding your suggestion above, the `currentUnreadMarker` has the value for the `reportActionID`, only with this information I didn't see a way to get the position to go back the scroll to the index.

Using the `currentUnreadMarker` I think we need to calculate the position using the `sortedReportActions` method.

Could you please, give a direction on how to use the `currentUnreadMarker` to get the unread index?

**Comment by wlegolas** [comment] 2023-12-06 03:26
Hi, @parasharrajat 

I finished my changes but before I send the PR, I need to check the "**New messages**" button behaviors.

- When there is an unread message, the "**New messages**" button is displayed, and when the user clicks on this button, we should scroll to the unread message in the view.
- When the user clicks on the "**New messages**" button and scrolls to the unread message in the view, the "**New messages**" button continues showing because there is a logic in the `handleUnreadFloatingButton` to just hide this button if the scroll is close to the Flatlist bottom. (code below)
- When the user goes to the Flatlist bottom the "**New messages**" button is hidden

https://github.com/Expensify/App/blob/2f80993df3170fcd80647b5bc349a8f8205152c6/src/pages/home/report/ReportActionsList.js#L282-L294

The video below shows all these behaviors.

Just to confirm, are these the expected behaviors?

https://github.com/Expensify/App/assets/698363/3fb02d81-9d96-477a-99ab-b75a1681bde7

**Comment by wlegolas** [comment] 2023-12-06 10:50
> > When the user clicks on the "New messages" button and scrolls to the unread message in the view, the "New messages" button continues showing because there is a logic in the handleUnreadFloatingButton to just hide this button if the scroll is close to the Flatlist bottom. (code below)
> 
> This should change now when you are changing the click behaviour.

In this case, should I hide the button when scrolling to the unread message or is there another behavior that you thought?

**Comment by wlegolas** [comment] 2023-12-06 10:51
> I am unsure of whether the scroll to unread logic will work as expected. We should test it with the pagination of chat messages.
> 
> Test Scenario:
> 
> * Let's say you go to the history of messages, mark a message as unread, and then directly open that report from an uncached environment(where the report is not cached to Onyx/storage yet).

I'll do this test, thank you for helping me.

**Comment by wlegolas** [comment] 2023-12-07 04:43
Hi, @parasharrajat I created the PR with the changes to fix the issue. I need to add the evidence for Android Native, I've been having some problems running the simulator.

If you have any suggestions or questions, feel free to add a comment in the PR.

PR: https://github.com/Expensify/App/pull/32630

**Comment by wlegolas** [comment] 2023-12-08 23:58
> Behaviour should be same to what happens currently when we scroll to bottom. Only change we are doing is instead of scrolling to the bottom, we scroll to first unread chat.

Hi, @parasharrajat I finished the implementation, just to let you know how the implementation went, I changed the `handleUnreadFloatingButton` method to **not hide** the new floating message when the user scrolls to the end of the list (the first `if`) the new behavior will show the "**New messages**" when the user is doing the scroll even they are at the end of the list, this new behavior is almost the same as Slack's new message button.

https://github.com/Expensify/App/blob/632c5c6fb416e330cc90878b6258a9b5e23347cb/src/pages/home/report/ReportActionsList.js#L282-L294

I updated my PR with these changes.

You can see this behavior in the following evidence:

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/698363/ce6cb2e0-001e-4c68-993e-adc54c394944

</details>
<details>
<summary>MacOS: Chrome</summary>

https://github.com/Expensify/App/assets/698363/ceb34985-fbf5-407e-a06a-d9df2a9592b4

</details>

**Comment by JmillsExpensify** [comment] 2023-12-13 05:44
Still discussing

**Comment by wlegolas** [comment] 2023-12-14 22:38
Hi @parasharrajat I don't know if you saw my last commit, but I think I finished the fix and the implementations.

If you have any questions or suggestions, please let me know.

**Comment by wlegolas** [comment] 2023-12-19 21:48
Hi @JmillsExpensify and @MariaHCD, I finished the PR and I don't know if @parasharrajat reviewed it, the last message was two weeks ago.

Do you know how we can check with @parasharrajat if this PR is good to merge or not?

**Comment by wlegolas** [comment] 2023-12-21 00:00
> I was busy the last few days. I plan to wrap up soon.

No problem @parasharrajat, I just asked to know if we should do anything else to close this PR.

If you have any questions or suggestions, please let me know.

**Comment by wlegolas** [comment] 2024-01-15 23:55
Hi Melvin, we're having a discussion on the PR.

I think we are going to have the final changes soon after some tests from @parasharrajat

**Closed** 2024-03-13 19:21 UTC
Labels: Reviewing, External, Monthly, Bug
