### ISSUE TITLE
 Chat - Message deleted in offline mode is still displayed in offline mode after being online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31751] opened 2023-11-22 21:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to any chat and send a message
2. Disable internet connection
3. Delete the recently sent message
4. Force-kill and relaunch the app
5. Enable internet connection
6. Open New Expensify app again and go to chat
7. Disable internet connection again

## Expected Result:
The recently deleted message should remain deleted and shouldn't be displayed

## Actual Result:
The recently deleted message is displayed again when user is in offline mode (also displayed in LHN even when online)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c1c0e5ff-9e62-4fc4-8129-9b822bc4a2a2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-11-22 21:40
I think this was caused by https://github.com/Expensify/App/pull/30425 which was reverted and CPed. Gonna test in staging.

**Comment by luacmartins** [comment] 2023-11-22 21:41
yea, can't repro in staging anymore. Closing this issue.

**Closed by luacmartins** 2023-11-22 21:41 UTC
Labels: Engineering, Hourly
