### ISSUE TITLE
[HOLD for payment 2023-09-06] [HOLD for payment 2023-09-04] Workspace- While inviting members, the contact selected is not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25877] opened 2023-08-24 18:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap Workspace
4. Create new workspace
5. Tap Members
6. Tap members
7. Tap Invite
8. Scroll down and select contacts

## Expected Result:
After user selected a contact, the page must automatically scrolls up and he must be shown the selected contact with green tick

## Actual Result:
After user selected a contact, a jump is shown but page not scrolled up automatically to show the selected contact with green tick. The user has to scroll up and see the contacts selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/143ff00c-f5fc-4ca2-acfc-f9ff9c4ee126

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2023-08-24 19:06
@jeet-dhandha I don't think it was always an expected behavior. Do you have any links to where this was discussed?

**Comment by jeet-dhandha** [comment] 2023-08-24 19:09
- Slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1670238226611139
- Issue - https://github.com/Expensify/App/issues/12998

**Comment by joelbettner** [comment] 2023-08-25 01:57
@thiagobrez will you please take a look at this and give us your thoughts.

**Comment by thiagobrez** [comment] 2023-08-25 08:26
@joelbettner I wasn't aware of this behavior, will work on it

**Comment by mountiny** [comment] 2023-08-25 19:39
confirmed this is fixed in staging and not reporting bonus, closing

**Comment by lanitochka17** [comment] 2023-10-14 17:25
Issue reproducible on Build 1.3.84-0

https://github.com/Expensify/App/assets/78819774/8d546bf3-d81f-4470-b61a-b162e312d33d

**Comment by joelbettner** [comment] 2023-10-25 21:34
@mountiny should this be close similar to https://github.com/Expensify/App/issues/25883#issuecomment-1693849387

If not...I think @dylanexpensify might be the person to assign to this to make sure it gets paid since he was also on [this](https://github.com/Expensify/App/issues/25878).

**Closed** 2023-10-25 21:36 UTC
Labels: Engineering, Weekly, Awaiting Payment
