### ISSUE TITLE
[$250] Categorizing - Date picker on confirmation page does not show the selected date

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46763] opened 2024-08-03 14:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4807531
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Track a manual expense
4. Go to transaction thread
5. Click Date and change to another date
6. Return to main chat
7. Click Categorize it > Select any category
8. Click Date on confirmation page
9. Change to a different date and save it
10. Click Date again

## Expected Result:
The date picker will display the latest selected date in Step 9

## Actual Result:
The date picker displays the selected date in Step 5, which is the date edited after tracking the expense and before categorizing
When saving the date without changing it, the latest date in Step 9 remains selected instead of the date shown in Step 10

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/04f51053-7f95-4508-84ce-78514f1bc029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013cac8c72a835b3bf</li>
        <li>Upwork Job ID: 1820982675228792931</li>
        <li>Last Price Increase: 2024-08-07</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103427314</li>
<li>abzokhattab | Contributor | 103427316</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by lanitochka17** [comment] 2024-08-03 14:51
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-03 14:51
We think that this bug might be related to #vip-vsp

**Comment by hayes102** [comment] 2024-08-03 15:54
I can not reproduce the issue

**Comment by mallenexpensify** [comment] 2024-08-07 00:45
@eh2077 plz review @abzokhattab 's [proposal above](https://github.com/Expensify/App/issues/46763#issuecomment-2267003995)

Was able to reproduce, I initially added to #wave-collect cuz it was an _expense_ but, since it's via a self-DM.  I wasn't able to reproduce when submitting an expense on a collect plan.  @abzokhattab and @eh2077 , let me know if either of you are.

**Comment by eh2077** [comment] 2024-08-07 01:45
>I wasn't able to reproduce when submitting an expense on a collect plan. @abzokhattab and @eh2077 , let me know if either of you are.

@mallenexpensify Submitting an expense also works as expected for me. I think this edge case only happens via self-DM where we can categorise an expense.

**Comment by eh2077** [comment] 2024-08-07 01:46
@abzokhattab 's [proposal](https://github.com/Expensify/App/issues/46763#issuecomment-2267003995) looks good to me. We can discuss coding details in PR.

🎀👀🎀 C+ reviewed

**Comment by eh2077** [comment] 2024-08-09 15:40
@abzokhattab Please let us know when we can expect a PR to be ready for review, thanks

**Comment by mallenexpensify** [comment] 2024-08-31 00:14
Contributor: @abzokhattab paid $250 via Upwork  
Contributor+: @eh2077 paid $250 via Upwork  

Hit production a bit ago 
- https://github.com/Expensify/App/pull/47210#issuecomment-2296965760

@eh2077 plz complete the BZ checklist. 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:
- [ ]

**Comment by eh2077** [comment] 2024-09-04 16:01
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**I think this is a missing case when self DM track expense feature was introduced. But I can't figure out the exact PR that is directly responsible for this issue.**_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. **_Yes_**

#### Regression test

1. Go to staging.new.expensify.com
2. Go to self DM
3. Track a manual expense
4. Go to transaction thread
5. Click Date and change to another date
6. Return to main chat
7. Click Categorize it > Select any category
8. Click Date on confirmation page
9. Change to a different date and save it
10. Click Date again
11. Ensure that the new date is shown and not the date from step 5.

**Comment by srikarparsi** [comment] 2024-09-06 00:33
Nice, if this is paid is this good to close out @mallenexpensify?

**Comment by mallenexpensify** [comment] 2024-09-07 00:43
Test case created, good to close now!
- https://github.com/Expensify/Expensify/issues/426646

**Closed by mallenexpensify** 2024-09-07 00:43 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
