### ISSUE TITLE
[$500] User is still able to send messages in a workspace room after being removed from the workspace

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#35010] opened 2024-01-23 21:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** Unknown
**Reproducible in production?:** Unknown
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danieldoglas  
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705513166379819

## Action Performed:
1. Remove a user B from a workspace
2. Log in as User B
3. Navigate to the workspace chat and send some messages

## Expected Result:
Room should have been archive and no more messages can be sent. 

## Actual Result:
User can still send messages in the workspace chat. 

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/44479856/f6151da8-d6dc-47d1-a1fd-f9cbf7fdcfb3)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0f875cc85886e61</li>
        <li>Upwork Job ID: 1749913174318096384</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2024-01-23 23:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

User is still able to send messages in a workspace room after being removed from the workspace

### What is the root cause of that problem?

In the `ReportFooter` and `ReportActionCompose` components, we do not check if the currency user is a policy member to disable the composer or send messages.

### What changes do you think we should make in order to solve the problem?

Use condition such as `PolicyUtils.isPolicyMemeber` to the `isDisabled` prop the `ReportFooter` or in the `ReportActionCompose` to set `isSendDisabled` if only sending it will be disabled.

The `PolicyUtils.isPolicyMemeber` function does not account for the members but matches the `policyID`.

Therefore, we should improve it or create another function that searches and checks if the account is a member from `ONYXKEYS.COLLECTION.POLICY_MEMBERS`.

**Comment by Tony-MK** [comment] 2024-01-23 23:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

User is still able to send messages in a workspace room after being removed from the workspace

### What is the root cause of that problem?

Neither the `ReportFooter` nor `ReportActionCompose` components check if the user is among the policy members to disable the composer or send messages.

### What changes do you think we should make in order to solve the problem?

Use condition such as `PolicyUtils.isPolicyMember` to the `isDisabled` prop the `ReportFooter` or in the `ReportActionCompose` to set `isSendDisabled` if only sending it will be disabled. 

The `PolicyUtils.isPolicyMemeber(policyID, policies)` function does not account for the members but matches if the `policyID` is among the `policies` arg.

Therefore, we should improve it or create a simple function called `PolicyUtils.isMember(accountID, policyID)` that searches and checks if the account is a member from `ONYXKEYS.COLLECTION.POLICY_MEMBERS`.

**Comment by s-alves10** [comment] 2024-01-24 05:27
I think this issue should be handled in the backend. When removing a user from a workspace, the workspace chat should be marked as `archived` by setting `statusNum` to `2`

**Comment by sophiepintoraetz** [comment] 2024-01-29 22:43
@alitoshmatov - mind confirming @s-alves10 comment on whether this should be on the back end?

**Comment by alitoshmatov** [comment] 2024-01-30 18:41
I couldn't reproduce this issue. 
<img width="1402" alt="Screenshot 2024-01-30 at 23 40 36" src="https://github.com/Expensify/App/assets/59907218/51b40bda-219d-47d8-954e-57c4222f7bd7">


@sophiepintoraetz If you can reproduce this issue, a screen recording would be helpful

**Comment by joekaufmanexpensify** [comment] 2024-02-02 18:00
Not reproducible for me either. Closing as this is fixed!

**Closed by joekaufmanexpensify** 2024-02-02 18:00 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
