### ISSUE TITLE
[hold for #28343][$500] Scan receipt - user can scan a video causing undefined participants and "Hmm... it's not here" error

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29493] opened 2023-10-12 21:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AmjedNazzal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697122987537109

## Action Performed:
1. Open a report
2. Click + in the composer and pick Request money
3. Click Scan to go to the scan tab
4. Click "Choose file" and pick a video
5. Click "Request" and you will get receipt scan in process inside the report
6. Click on the processing request and notice the error page
## Expected Result:
Since the backend cannot process receipts from a video there should be no reason the user can use a video for receipt scanning, so the user should get "wrongFileType" or "notAllowedExtension" error and shouldn't be able to proceed using a video.
## Actual Result:
The user can use a video to scan and it results in unexpected behaviour and error page.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/9253735f-5880-4eb8-8200-821852566d94

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/fac1a58f-6110-417a-8edd-904df37f4bf0

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/c9af1fb9-7db0-4ef4-9985-8274032a4b75

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/d8ecb063-d473-457e-b36a-3286c4b1d7f8

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/af22d0bb-d133-44a6-82a5-e88e122968df

https://github.com/Expensify/App/assets/38435837/21c6e1b9-4454-4980-b136-5ce4a6ccb7b4

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/27de0cc9-203c-47fb-b24b-56ce5a8104b0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a82f0fea498f629d</li>
        <li>Upwork Job ID: 1712574150707265536</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2023-10-12 21:01
## Proposal by @AmjedNazzal 
### Please re-state the problem that we are trying to solve in this issue.
Scan receipt - uploading a video causes undefined participants and "Hmm... it's not here" error
### What is the root cause of that problem?
We are trying to use CONST.API_ATTACHMENT_VALIDATIONS.UNALLOWED_EXTENSIONS which it seem like we forgot to define during development and since it seem like the backend cannot process videos, this is causing errors.
https://github.com/Expensify/App/blob/6c7ee53c4d8a287cddbc7fa25afee548bf999e01/src/pages/iou/ReceiptSelector/index.js#L104-L106
https://github.com/Expensify/App/blob/f942acd2c87d3babcdb6fb83f19e8dc02518efc8/src/CONST.ts#L47-L53
### What changes do you think we should make in order to solve the problem?
Even if we are not sure yet what kind of extensions the backend will be able to process in the future, at least for the time being we need to add UNALLOWED_EXTENSIONS and populate commonly used video extentions and any other extensions the backend is unable to process to it
```javascript
API_ATTACHMENT_VALIDATIONS: {
    ...
    UNALLOWED_EXTENSIONS: [
        'mp4', 'avi', 'mkv', 'flv', 'mov',
        'wmv', 'm4v', 'webm', 'mpeg', '3gp'
    ]
```
### Result
https://github.com/Expensify/App/assets/74202751/0e985c14-76cd-4259-9e23-12ffe8a82376

**Comment by DaniloVlad** [comment] 2023-10-13 15:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Scan receipt - user can scan a video causing undefined participants and "Hmm... it's not here" error

### What is the root cause of that problem?
When adding an attachment the file extension is validated against a non-existent constant:
https://github.com/Expensify/App/blob/6c7ee53c4d8a287cddbc7fa25afee548bf999e01/src/pages/iou/ReceiptSelector/index.js#L104-L106

where `UNALLOWED_EXTENSIONS` does not exist in:
https://github.com/Expensify/App/blob/9e19e40aef0f303ab5d5fc1c9cf8c9caf86a8098/src/CONST.ts#L47-L53

### What changes do you think we should make in order to solve the problem?

Since it's more likely that the backend would allow for less filetypes than it would disallow, i think it would make more sense to update the `CONST.ts` to be:
```js
API_ATTACHMENT_VALIDATIONS: {
    // 24 megabytes in bytes, this is limit set on servers, do not update without wider internal discussion
    MAX_SIZE: 25165824,

    // An arbitrary size, but the same minimum as in the PHP layer
    MIN_SIZE: 240,

    // Extensions allowed for scanning
    ALLOWED_EXTENSIONS = ['jpg', 'jpeg', 'png', 'heic'],
},
...
```

and update the validation code to be:
```js
if (!_.contains(CONST.API_ATTACHMENT_VALIDATIONS.ALLOWED_EXTENSIONS, fileExtension.toLowerCase())) {
    setUploadReceiptError(true, 'attachmentPicker.wrongFileType', 'attachmentPicker.notAllowedExtension');
    return false;
}
```

**Comment by DaniloVlad** [comment] 2023-10-13 15:42
Contributor details
Your Expensify account email: vladicicdanilo@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014368a2d754844229

**Comment by kadiealexander** [comment] 2023-10-17 03:59
Placed on hold.

**Comment by kadiealexander** [comment] 2023-10-27 05:05
Still on hold

**Comment by kadiealexander** [comment] 2023-11-13 06:42
Still on hold.

**Comment by kadiealexander** [comment] 2023-11-22 05:35
Still on hold.

**Comment by kadiealexander** [comment] 2023-11-24 02:58
Nice! Closing as no longer reproducible.

**Closed by kadiealexander** 2023-11-24 02:58 UTC
Labels: External, Weekly, Help Wanted, Bug
