### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Inconsistent auto capitalize between legal name page and display name page.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24155] opened 2023-08-04 11:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account.
2. Go to Profile => Display name, Type something, observer the auto capitalize.
3. Go to Profile => Personal Details => Legal Name, Type something, observer the auto capitalize.
## Expected Result: 
Display Name page should not have auto capitalize
## Actual Result: 
Display Name page has auto capitalize

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/75394c38-4076-4ebc-abde-10b8d0bba883

https://github.com/Expensify/App/assets/43996225/9e85f359-e377-446c-a789-c35698ec3c9e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690876355312059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c2450484a7b8c95</li>
        <li>Upwork Job ID: 1688785606581387264</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26310131</li>
<li>hungvu193 | Contributor | 26310133</li>
<li>hungvu193 | Reporter | 26310134</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-08-04 11:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent auto capitalize between legal name page and display name page.
### What is the root cause of that problem?
In `DisplayNamePage` we ad `autoCapitalize` props inside `TextInput`, meanwhile we didn't have that in `LegalNamePage` which caused the issue.
https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/pages/settings/Profile/DisplayNamePage.js#L95
https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/pages/settings/Profile/DisplayNamePage.js#L107
### What changes do you think we should make in order to solve the problem?
To make it consistent, we should also add ` autoCapitalize="words" ` inside `LegalNamePage` in [here](https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/pages/settings/Profile/PersonalDetails/LegalNamePage.js#L103) and [here](https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/pages/settings/Profile/PersonalDetails/LegalNamePage.js#L92)

We can also add that props to other TextInput that use to display Legal Name as well (like BankAccount..etc.).

### What alternative solutions did you explore? (Optional)
Incase we want to remove `autoCapitalize`, we can remove it in [here](https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/pages/settings/Profile/DisplayNamePage.js#L95) and [here](https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/pages/settings/Profile/DisplayNamePage.js#L107)

**Comment by michaelhaxhiu** [comment] 2023-08-04 16:26
Note: I'm preparing to go OOO for ~2 weeks and need a BZ buddy to take this one over please. It was just created today so I will let you own full assignment as I haven't done much to share the glory. 

**Next step:** Ensure this can be reproduced and the BZ checklist is satisfied, then assign `external` or `internal`

Thanks in advance @greg-schroeder 🙏

**Comment by pradeepmdk** [comment] 2023-08-08 06:01
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Inconsistent auto capitalize between legal name page and display name page


### What is the root cause of that problem?
`autoCapitalize` props is missing in the `TextInput` like this
https://github.com/Expensify/App/blob/012d604753e6ed2f97736d47b28486f813995165/src/pages/settings/Profile/DisplayNamePage.js?#L95

### What changes do you think we should make in order to solve the problem?
we need add `autoCapitalize`
https://github.com/Expensify/App/blob/012d604753e6ed2f97736d47b28486f813995165/src/pages/settings/Profile/PersonalDetails/LegalNamePage.js?#L91-L111

**Comment by greg-schroeder** [comment] 2023-08-09 23:10
Awaiting proposal review here

**Comment by abdulrahuman5196** [comment] 2023-08-13 09:00
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-08-13 09:05
@greg-schroeder I understand the inconsistency. But what is the proper approach/behaviour here? Like should legal first name behave like the display name or the other way around? Is it only for names we need the auto capitalize on every word?
Can we confirm this before approving a proposal?

**Comment by greg-schroeder** [comment] 2023-08-16 03:25
>@greg-schroeder I understand the inconsistency. But what is the proper approach/behaviour here? Like should legal first name behave like the display name or the other way around? Is it only for names we need the auto capitalize on every word?
Can we confirm this before approving a proposal?

Yeah, it's honestly not really clear which is better. I started a discussion: https://expensify.slack.com/archives/C01GTK53T8Q/p1692156323235199

**Comment by greg-schroeder** [comment] 2023-08-16 07:59
After thinking about it more I think we should just not auto-capitalize in any field. I don't like the idea of forcing the user to capitalize their name if they don't want to - that may not even be how their name is spelled.

**Comment by greg-schroeder** [comment] 2023-08-18 08:20
Yeah I think that's the way to go. @abdulrahuman5196 with that said shall we pick a proposal and get going on this one? I updated the OP to just say we should remove auto-capitalize

**Comment by greg-schroeder** [comment] 2023-08-21 17:41
bump @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2023-08-23 17:28
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-08-23 17:33
@hungvu193 Could you post a proposal from you GH for assignment?

**Comment by abdulrahuman5196** [comment] 2023-08-23 17:35
@hungvu193 's proposal here https://github.com/Expensify/App/issues/24155#issuecomment-1665493832 looks good and works well.

We can remove auto capitalize as suggested here https://github.com/Expensify/App/issues/24155#issuecomment-1683546464

🎀 👀 🎀
C+ Reviewed

**Comment by aldo-expensify** [comment] 2023-08-24 18:14
Proceeding with removing auto-capitalization

**Comment by abdulrahuman5196** [comment] 2023-09-04 10:28
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. But we had changed the older requirement to capitalize. 

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Won't be beneficial to add regression test for this minor change.

**Comment by greg-schroeder** [comment] 2023-09-06 18:02
Issue Participants:

Issue reported by: @hungvu193
Contributor: @hungvu193
C+: @abdulrahuman5196 

Was this issue merged in time to be eligible for the speed bonus? ✅ 
Were their any regressions? ❌ 

Payment summary:

Reporter: $250
Contributor: $1,500
C+: $1,500

**Comment by greg-schroeder** [comment] 2023-09-06 18:04
Payments/checklist complete, closing.

**Closed by greg-schroeder** 2023-09-06 18:04 UTC
Labels: External, Daily, Awaiting Payment, Bug
