### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] Chat - Unable to navigate to LHN, back button loops between WS details & main chat page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41514] opened 2024-05-02 16:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+1088ck@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** Applause-Internal team
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com or ND app
2. Go to any Workspace chat page
3. Tap + icon >> select Assign task or Submit expense >> Complete the flow
4. Select the created task or expense to go report page
5. Tap on "From" link in header to go back to chat page
6. Tap on header to go to WS details page
7. Tap on back button (User redirected to main chat page)
8. Tap on back button (User again taken back to details page)
9. Repeat steps 7 & 8

## Expected Result:
Unable should redirected to LHN, on tapping back button in main chat page

## Actual Result:
Unable to navigate to LHN, back button loops between WS details & main chat page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1391faa9-f6ab-4117-b66e-8581cd731a63

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110f0cb9e34f0e6c4</li>
        <li>Upwork Job ID: 1787970200405659648</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by izarutskaya** [comment] 2024-05-02 16:39
We think this issue might be related to the #vip-vsb.

**Comment by bernhardoj** [comment] 2024-05-03 07:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The back button loops if we open the report detail page after visiting a linked message of a report.

### What is the root cause of that problem?
If we open the detail page from a report, `shouldNavigateToTopMostReport` will be true.
https://github.com/Expensify/App/blob/7483d10e686e240d07d9fa3e43e89ffdfcda9cbd/src/pages/ReportDetailsPage.tsx#L269-L270

`shouldNavigateToTopMostReport` will navigate to the topmost report ID.
https://github.com/Expensify/App/blob/7483d10e686e240d07d9fa3e43e89ffdfcda9cbd/src/components/HeaderWithBackButton/index.tsx#L154-L157

But the navigation type will be changed to PUSH because the params are different. The topmost report has reportID and reportActionID in the params (linked message), but we navigate to a report without reportActionID.
https://github.com/Expensify/App/blob/7483d10e686e240d07d9fa3e43e89ffdfcda9cbd/src/libs/Navigation/linkTo.ts#L166-L179

If we update the logic to only compares the reportID, this issue won't happen anymore, but it will remove the reportActionID from the param, so the message won't be linked anymore.

### What changes do you think we should make in order to solve the problem?

To solve the issue correctly, we just need to remove `shouldNavigateToTopMostReport` from the details page.

_if we want the user to see the report screen when going back after refresh, then it should be handled in this [issue](https://www.github.com/Expensify/App/issues/41017)_

**Comment by bernhardoj** [comment] 2024-05-13 06:45
> specefically, can you check if removing it will not bring back https://github.com/Expensify/App/issues/30101 as shouldNavigateToTopMostReport was introduced in https://github.com/Expensify/App/pull/30289

https://github.com/Expensify/App/issues/30101 introduced the `shouldNavigateToTopMostReport` prop by taking the logic from ReportDetailsPage to the header component (and modified it), but the logic is first introduced in https://github.com/Expensify/App/pull/29268 to fix https://github.com/Expensify/App/issues/29056 and yes it will bring back the issue because pressing back will simply close the current page, that is the details page. If the user refresh while on the details page and press back, the user will be navigated back to the LHN which will be fixed by https://github.com/Expensify/App/issues/41017.

If you want, we can hold for https://www.github.com/Expensify/App/issues/41017

**Comment by bernhardoj** [comment] 2024-05-13 08:01
> when we click the back button, we should navigate to the linked reportAction

If you don't refresh the page, then you will be navigated to the previous report. If the previous report has a linked action, then you will see the linked action. 

If you refresh and wait for https://github.com/Expensify/App/issues/41017, then going back will show the report without the linked report action ID. This is the behavior on main too, so it's completely oos. We can achieve it by having a new param for the reportActionID for many report-related pages, but it's better to just stick the scope of this issue.

**Comment by bernhardoj** [comment] 2024-05-13 13:07
Ah I see, but that means you would need to modify `getTopmostReportId` to get the topmost report action ID too. It just makes things more complicated and inconsistent since `shouldNavigateToTopMostReport` is only enabled in flag and details RHP pages. I actually think `shouldNavigateToTopMostReport` is not really needed. If you read the logic,

https://github.com/Expensify/App/blob/1e5c18cccefa1fe68cb373e39845029775e8294a/src/components/HeaderWithBackButton/index.tsx#L153-L158

if there is a topmost report, we want to navigate to the report. It can be achieved by simply going back because going back will go back to the topmost report most of the time. If there is no topmost report, then we also go back.

This also means we don't need to wait for https://github.com/Expensify/App/issues/41017 (my bad) because it's already happening on main for details page too.

**Comment by hayata-suenaga** [comment] 2024-05-15 17:12
I agree that we can remove the `shouldNavigateToTopMostReport` 👍

**Comment by bernhardoj** [comment] 2024-05-16 04:26
PR is ready

cc: @rayane-djouah

**Comment by hayata-suenaga** [comment] 2024-05-24 16:21
thank you for the update. we're just waiting for the merge freeze to be lifted so probably not much we need from you 😄

**Comment by johncschuster** [comment] 2024-06-13 14:08
# Payment Summary:
Contributor:  @bernhardoj - $250 - paid via [Upwork](https://www.upwork.com/nx/wm/offer/102323618)
Contributor+: @rayane-djouah - $250 - paid via [Upwork](https://www.upwork.com/nx/wm/offer/102323615)

**Comment by johncschuster** [comment] 2024-06-20 15:43
I've added the QA issue and will work on payment shortly.

**Comment by hayata-suenaga** [comment] 2024-06-24 04:25
Yes that seems to be correct. The C+ authored a PR that introduced the regression and the same C+ reviewed the PR that fixed it.

**Comment by hayata-suenaga** [comment] 2024-06-24 05:09
Melvin, we're just handling payments 😄

**Closed** 2024-06-24 16:14 UTC
Labels: External, Daily, Awaiting Payment, Bug
