### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] Chat - Italic `_@here_` is not displayed as mention

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19857] opened 2023-05-30 21:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19610

## Action Performed:
1. Go to NewDot
2. Open any chat
3. Type `_@here_` and send

## Expected Result:
@here should be displayed as mention (and italic)

## Actual Result:
@here is displayed as italic text, no mention

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/b2bad9b73d47f0eef1ff081f07bd1016aee711c6236b656eabc7617f11b1cbcd

![Screenshot 2023-05-31 at 17 31 14](https://github.com/Expensify/App/assets/93399543/0253b587-9cf7-46d5-9ad1-fb0b47cc714e)

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @bernhardoj 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685027189525539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d06a47c69e1d4cd</li>
        <li>Upwork Job ID: 1663843746285133824</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by sethraj14** [comment] 2023-05-30 22:23
@kbecciv It is showing like this, the expected behaviour is italic `@here`, can you confirm this ?

![Screenshot 2023-05-31 at 3 52 21 AM](https://github.com/Expensify/App/assets/14844259/db1f6d4d-20b1-4608-89c1-252461d27e55)

**Comment by conorpendergrast** [comment] 2023-05-31 09:43
@sethraj14 When you enter: 
`_@here_`
the expectation is that you see 1) a mention (for `@here`) and 2) in italics

**Comment by conorpendergrast** [comment] 2023-05-31 09:43
Compare 
`_@here_`
with
`_@expensifysecond@conorpendergrast.com_`

![image](https://github.com/Expensify/App/assets/5802477/49cbf9cc-ed76-4a33-81b0-3466bf7dccc6)

**Comment by bernhardoj** [comment] 2023-05-31 10:06
@kbecciv can you add me as the reporter too (based on my report [here](https://expensify.slack.com/archives/C049HHMV9SM/p1685027189525539)), please? Thanks!

**Comment by s-alves10** [comment] 2023-05-31 11:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Italic `_@here_` is not displayed as mention.

### What is the root cause of that problem?

Now `hereMention` rule is applied before `italic` rule. Current regexp is as follows.

```
   regex: /[`.a-zA-Z]?@here\b(?![^<]*(<\/pre>|<\/code>|<\/a>))/gm,
```

We use `\b` in order to match `@hero` word, that is, `@here` needs to be followed by space character.
But `_` is considered as a word character and doesn't match. This is the root cause.

### What changes do you think we should make in order to solve the problem?

Including `_` to the space character group would solve the issue successfully.

```
   regex: /[`.a-zA-Z]?@here(?=[\s_])(?![^<]*(<\/pre>|<\/code>|<\/a>))/gm,
```

![image](https://github.com/Expensify/App/assets/126839717/7629193f-395a-41b9-8c55-117bcd7866e6)

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/f4ce6a1e-5d4f-4a5f-8660-49482fc6b6dd

</details>

### What alternative solutions did you explore? (Optional)

**Comment by eh2077** [comment] 2023-06-01 08:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Italic `_@here_` is not displayed as mention.

### What is the root cause of that problem?

The root cause of this issue is from the [regex](https://github.com/Expensify/expensify-common/blob/c898563fe851d9a4d594fa9afbdd1ddab5971636/lib/ExpensiMark.js#L95) of here mention

```js
/[`.a-zA-Z]?@here\b(?![^<]*(<\/pre>|<\/code>|<\/a>))/gm
```

The above regex needs to match a word boundary after keyword `@here` and the underscore character `_` is actually a word character. So, the regex won't match markdown input `_@here_`.

### What changes do you think we should make in order to solve the problem?

As we consider composer input as markdown and the underscore character `_` is used by the Markdown bold syntax, I think we need to handle the special case of underscore character `_` followed right after the `@here` syntax.

To fix this issue, we can insert a capture group `(_?)` before `\b` to capture the `_`. If the `_` occurs, then we also add it back to the end of `</mention-here>` tag.

The new regex will be

```js
/[`.a-zA-Z]?@here(_?)\b(?![^<]*(<\/pre>|<\/code>|<\/a>))/gm,
```

And the replacement method will be

```js
replacement: (match, g1) => {
    if (!Str.isValidMention(match)) {
        return match;
    }
    return `<mention-here>@here</mention-here>${g1}`;
},
```

By doing so, the input `_@here_` will be translated into html

```html
<em><mention-here>@here</mention-here></em>
```

and won't break existing unit test cases of expensify-common lib.

Below test cases will be helpful if you want to verify more corner cases of the new regex.

```
_@here_

@here_
@here_123
@here_abc

@here123
@hereabc
@here abc

@here*
@here~
@here#

```

<img width="800" alt="image" src="https://github.com/Expensify/App/assets/117511920/509465c0-322f-4b14-bf5a-06a2182ab1f3">

### What alternative solutions did you explore? (Optional)

N/A

**Comment by eh2077** [comment] 2023-06-03 01:16
@allroundexperts Thanks for checking proposals! Below is that regex test result comparing on test cases provided in my proposal FYI

|  @eh2077 's proposal  | @getusha 's proposal |
| ------------- | ------------- |
| <img width="400" alt="image" src="https://github.com/Expensify/App/assets/117511920/85a72e60-8ff2-48f8-b2f5-678a1ad322e8">  | <img width="400" alt="image" src="https://github.com/Expensify/App/assets/117511920/92ba176a-bf9d-4778-ab08-5073dfad01ba"> |

Based on the test above my proposal covers 3 more test cases 
```
@here_123
@here_abc

@here123
```

@getusha Hope you don’t mind my testing above as I just did it as requested by the C+ team 🙏

**Comment by s-alves10** [comment] 2023-06-03 01:43
## Proposal
[Updated](https://github.com/Expensify/App/issues/19857#issuecomment-1570028794)

@allroundexperts 
Thank you for your feedback

**Comment by eh2077** [comment] 2023-06-03 03:54
### Proposal 
[Updated](https://github.com/Expensify/App/issues/19857#issuecomment-1571631459) to add an alternative method which is simpler.

**Comment by eh2077** [comment] 2023-06-03 04:19
@getusha Cool. Let's just wait @allroundexperts to evaluate our proposals.

**Comment by sethraj14** [comment] 2023-06-03 20:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Italic _@here_ is not displayed as mention.



What changes do you think we should make in order to solve the problem?
Including _ optionally before and after @here would solve the issue successfully.
### What is the root cause of that problem?

Current regex for the here mentioned check - 
`   regex: /[`.a-zA-Z]?@here\b(?![^<]*(<\/pre>|<\/code>|<\/a>))/gm`,

\b in used here to match @here word, but @here needs to be followed by space character.

### What changes do you think we should make in order to solve the problem?

Change regex to this will solve our problem. Include _ and * to the post negative lookahead check.
`[`.a-zA-Z]?@here(?![^_\s*] | (<\/pre>|<\/code>|<\/a>))`

This will pass all the above test cases mentioned by @allroundexperts 

![Screenshot 2023-06-04 at 2 18 37 AM](https://github.com/Expensify/App/assets/14844259/92ec2d67-aa2b-40da-883e-1f99dd05d353)


### What alternative solutions did you explore? (Optional)

**Comment by eh2077** [comment] 2023-06-04 01:11
### Proposal
[Updated](https://github.com/Expensify/App/issues/19857#issuecomment-1571631459) to
1. Promote alternative solution to use `(?=_\b|\b)` as the main solution
2. Include more realistic test cases to verify the solution to avoid unnecessary misunderstanding caused by previous online regex test.

To have a quick look of the updated proposal, see screenshot
<img width="218" alt="image" src="https://github.com/Expensify/App/assets/117511920/3c223170-94c6-4b74-a521-b5c36c57b1ad">

@allroundexperts As previous online regex tests isn't realistic considering the use of our App, so I hope you can review it using more realistic test cases as I included in my updated proposal. Sorry for the inconvenience caused. I'm looking forward to your feedback again thanks!

**Comment by s-alves10** [comment] 2023-06-04 13:41
@allroundexperts 
Did you check my recent proposal?
Here is my test result

```
      @here     => <mention-here>@here</mention-here>
      @here     => <mention-here>@here</mention-here>
      _@here_   => <mention-here><em>@here</em></mention-here>
      `@here`   => <code>@here</code>
      ```@here```       => <pre>@here</pre>
      [@here](google.com)       => <a href="https://google.com" target="_blank" rel="noreferrer noopener">@here</a>
      [_@here_](google.com)     => <a href="https://google.com" target="_blank" rel="noreferrer noopener"><em><mention-here>@here</mention-here></em></a>
      [*@here*](google.com)     => <a href="https://google.com" target="_blank" rel="noreferrer noopener"><strong><mention-here>@here</mention-here></strong></a>
      [~@here~](google.com)     => <a href="https://google.com" target="_blank" rel="noreferrer noopener"><del><mention-here>@here</mention-here></del></a>
      @here_123 => @here_123
      @here_abc => @here_abc
      @here123  => @here123
      @hereabc  => @hereabc
      @here abc => <mention-here>@here</mention-here> abc
      @here*    => <mention-here>@here</mention-here>*
      @here~    => <mention-here>@here</mention-here>~
      @here#    => <mention-here>@here</mention-here>#
      @here`    => <mention-here>@here</mention-here>&#x60;
      @here@    => <mention-here>@here</mention-here>@
      @here$    => <mention-here>@here</mention-here>$
      @here^    => <mention-here>@here</mention-here>^
      @here(    => <mention-here>@here</mention-here>(
```

And I think `0@here` shouldn't be parsed as here-mention which my solution solves.
Considering I'm the first person who submitted a proposal and my result looks good in here mention inside link, I thought my proposal would be a nice choice.

Can you kindly let me know the drawbacks my proposal has?

Thank you

**Comment by hayata-suenaga** [comment] 2023-06-06 13:24
@allroundexperts what do you need from me? 😃

**Comment by hayata-suenaga** [comment] 2023-06-06 13:29
ah I didn't see [the commnet](https://github.com/Expensify/App/issues/19857#issuecomment-1575519997)

assigning @eh2077

**Comment by conorpendergrast** [comment] 2023-06-09 19:03
Looks like [the second PR](https://github.com/Expensify/App/pull/20445) is under review

**Comment by conorpendergrast** [comment] 2023-06-09 19:06
Hired @allroundexperts and @eh2077 via Upwork

**Comment by bernhardoj** [comment] 2023-06-22 09:38
@conorpendergrast will I get a reporting bonus here as I reported it earlier https://github.com/Expensify/App/issues/19857#issuecomment-1569895086?

**Comment by conorpendergrast** [comment] 2023-06-22 11:56
@bernhardoj Yes, thank you for highlighting that

**Comment by conorpendergrast** [comment] 2023-06-22 12:10
[Offer](https://www.upwork.com/nx/wm/offer/25166310) sent to @bernhardoj. 

Paid and ended contract for @eh2077 and @allroundexperts

**Comment by conorpendergrast** [comment] 2023-06-22 12:13
Regression test issue created: https://github.com/Expensify/Expensify/issues/294092

**Comment by eh2077** [comment] 2023-06-22 12:26
Hi @conorpendergrast , thanks for checking the payment! Can we apply for speed bonus for this issue as we got the two PRs merged within 3 working days? Here's the timeline FYI

Assigned: Jun 6, 2023 at 9:30 PM GMT+8
Merged(The second PR): Jun 10, 2023 at 3:42 AM GMT+8

**Comment by conorpendergrast** [comment] 2023-06-22 13:48
I agree. From [our internal process](https://stackoverflowteams.com/c/expensify/questions/7582/7583#7583):
> Note: If the contributor/c+ work was done within the speed bonuses but only merged later on due to internal engineering delays we can still pay out the speed bonus. As an example: if the PR is approved by c+ within the 3 days and internal engineer doesn't approve+merge until the 4th day then typically the speed bonus should still apply. If you're unsure ask in #bug-zero.

**Comment by conorpendergrast** [comment] 2023-06-22 13:52
@bernhardoj paid and contract ended
Bonus paid to @eh2077 and @allroundexperts. 


Aaaand we're done! Thanks for playing, see you next time

**Closed by conorpendergrast** 2023-06-22 13:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
