### ISSUE TITLE
Chat - Message received after attachment isn't displayed in LHN until reply is sent and deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22937] opened 2023-07-15 13:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com or open Expensify App on two devices as user A and user B
2. User A open chat with user B
3. User A send attachment (image or PDF) to user B
4. User B send text message to user A
5. === (see expected / actual result) ===
6. User A sends a reply to this message and then deletes this reply
7. Message from step 4 is displayed in LHN

## Expected Result:
5. User A receives a message and this message is displayed in LHN

## Actual Result:
5. User A receives a message but this message is NOT displayed in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b9037e0a-6a3a-42c5-b562-5aa552b34780

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by eh2077** [comment] 2023-07-15 15:50
This looks like a regression of https://github.com/Expensify/App/pull/21780

**Comment by stephanieelliott** [comment] 2023-07-18 07:38
Thanks @eh2077, made a note on the corresponding issue as well.

**Comment by stephanieelliott** [comment] 2023-07-19 08:22
Hey @eh2077 Is there a PR for this yet?

**Comment by eh2077** [comment] 2023-07-19 08:40
@stephanieelliott I think the contributor or the C+ will submit a PR to fix this. They'll update in the linked original issue.

**Comment by stephanieelliott** [comment] 2023-07-24 20:15
Oops, thanks @eh2077  -- meant to tag the 🙃 the original C+.

**Comment by stephanieelliott** [comment] 2023-07-24 20:23
Working on a fix in #19449 via https://github.com/Expensify/App/pull/21780

**Comment by stephanieelliott** [comment] 2023-07-28 22:11
Some back end changes needed on this PR, see https://github.com/Expensify/App/issues/19449#issuecomment-1647576502

**Comment by stephanieelliott** [comment] 2023-08-01 17:24
PR still under review, internal changes requested.

**Comment by stephanieelliott** [comment] 2023-08-03 07:58
PR still under review, internal changes requested.

**Comment by thienlnam** [comment] 2023-08-24 18:46
This bug is still happening - going to reopen this so it can be addressed independently

https://github.com/Expensify/App/issues/19449

**Comment by thienlnam** [comment] 2023-08-28 17:52
I'm suggesting we have the original reviewer and author to continue in this issue @tienifr / @eVoloshchak

**Comment by stephanieelliott** [comment] 2023-09-06 22:57
Hey @tienifr, any update on the PR?

**Comment by stephanieelliott** [comment] 2023-09-11 23:18
Just checking in @tienifr, do we have a PR for this yet?

**Comment by stephanieelliott** [comment] 2023-09-18 01:10
Cool, thanks @tienifr!

**Closed by stephanieelliott** 2023-09-18 01:10 UTC
Labels: Daily, Bug
