### ISSUE TITLE
[$500] MEDIUM: Mouse over emoji to get name

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#34307] opened 2024-01-11 01:39 UTC
**Strategy:**
Making the workplace fun is good business.  One way to do that is by supporting emoji, to make conversations more fun.

**Problem:**
Many emoji are kind of unclear, meaning the joke falls flat or whatever message you try to send might be missed.

**Solution:**
On desktop, when you hover over an emoji, show the name of that emoji.  Pay particular attention to performance, as previous hover states have sometimes introduced major performance regressions -- ask in #expensify-open-source for advice.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf03f6fb12beb641</li>
        <li>Upwork Job ID: 1745259225093054464</li>
        <li>Last Price Increase: 2024-01-18</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28118473</li>
<li>dukenv0307 | Contributor | 28118474</li>
</ul></li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2024-01-11 02:25
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Many emoji are kind of unclear, meaning the joke falls flat or whatever message you try to send might be missed.
That being said we're looking at an implementation that would display the name of an emoji when hovering over it while on web / desktop platforms.

## What is the root cause of that problem?

Missing emoji names on hover for web / desktop platforms where cursor is present.

## What changes do you think we should make in order to solve the problem?

Add the html `title` attribute which will display the name of the emoji when hovering over while not affecting performance at all.

**Comment by dragnoir** [comment] 2024-01-11 09:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Hovering eùojies does not display names.

### What is the root cause of that problem?

Missing the hover action when hovering emojies.

### What changes do you think we should make in order to solve the problem?

I suggest displaying the emoji name on this area:

![image](https://github.com/Expensify/App/assets/12425932/29858982-51ed-4d47-a070-ba786da98737)

Then it will be like that:

![2024-01-11 09 38 57](https://github.com/Expensify/App/assets/12425932/e8aaec6c-45f9-4107-801c-e4cab68b3523)

We can add a function here to set hevered emoji
https://github.com/Expensify/App/blob/e54abdf78cbbaab5e2c5c2419a5c111a61d38f68/src/components/EmojiPicker/EmojiPickerMenuItem/index.js#L82

Change the skin tone icon to the right
https://github.com/Expensify/App/blob/e54abdf78cbbaab5e2c5c2419a5c111a61d38f68/src/components/EmojiPicker/EmojiSkinToneList.js#L37-L49

Add new component on the left for displaying the Emoj name.

**Comment by zanyrenney** [comment] 2024-01-15 11:49
Great question, thanks for bringing this up @fedirjh. I'm going to take this to the channel and I will tag Brandon and David for their input seeing as they are the ones that have reported/worked on this in the past.

**Comment by zanyrenney** [comment] 2024-01-15 12:22
asked here - https://expensify.slack.com/archives/C01GTK53T8Q/p1705321349706809

**Comment by stitesExpensify** [comment] 2024-01-16 16:16
@fedirjh we decided to go with the slack style version with an enlarged version of the emoji

**Comment by quinthar** [comment] 2024-01-19 02:39
What are the next steps here?  Who is doing them, and when will it happen?

**Comment by stitesExpensify** [comment] 2024-01-19 02:57
@quinthar we're just following the normal contributor process here! 
We're waiting for an acceptable proposal, at which point @fedirjh will approve it and let me know, and then assuming that I agree, I will assign them and they will make the PR!

**Comment by zanyrenney** [comment] 2024-01-19 12:00
@dukenv0307 please can you post the additional details you mention in the [comment](https://github.com/Expensify/App/issues/34307#issuecomment-1895254076) above here when you have them? Thanks!

**Comment by stitesExpensify** [comment] 2024-01-23 22:49
I think you're right, it should show the text not the emoji when inside of code blocks. Can you post that in expensify-bugs and we'll get it fixed?

**Comment by zanyrenney** [comment] 2024-01-26 12:49
bump @stitesExpensify

**Comment by stitesExpensify** [comment] 2024-01-26 21:57
I've been focused on wave work this week, I'll check it out on monday

**Comment by stitesExpensify** [comment] 2024-01-29 23:05
Created a backend PR ^

**Comment by quinthar** [comment] 2024-02-01 07:45
Hi!  What is the next step on this, who is doing it, and when will it be done?

**Comment by quinthar** [comment] 2024-02-02 05:33
Bumping in Slack to get some faster responses: https://expensify.slack.com/archives/C01GTK53T8Q/p1706851954228519

**Comment by stitesExpensify** [comment] 2024-02-12 23:44
I will look at this first thing tomorrow

**Comment by stitesExpensify** [comment] 2024-02-13 20:30
I put a backend PR up for review, and requested changes on the FE portion

**Comment by situchan** [comment] 2024-02-13 23:38
Heads up: frontend fix (https://github.com/Expensify/expensify-common/pull/640) caused regression - https://github.com/Expensify/App/issues/36437

BUG: https://github.com/Expensify/App/issues/36437#issuecomment-1942797022

**Comment by stitesExpensify** [comment] 2024-03-06 16:33
We don't want emojis to be affected by any markdown, but that is a separate issue technically https://github.com/Expensify/App/issues/14676

**Comment by roryabraham** [comment] 2024-03-13 16:17
removing the HOLD for payment since the first PR was reverted

**Comment by stitesExpensify** [comment] 2024-03-28 21:05
I believe we're just waiting for the PR to be live for a week and then we can issue payment here. We just deployed to prod 2 days ago

**Comment by robertKozik** [comment] 2024-04-02 20:18
Hey hey, coming with a simple question. Is it intended to parse an emoji inside code blocks? We are getting an error on parsing in `react-native-live-markdown` due to adding html tags inside html attributes when emoji is present there and I'm wondering if I can simply prohibit parsing emoji within code blocks 🤔🤔🤔

**Comment by stitesExpensify** [comment] 2024-04-11 20:17
Hm looks like the bot doesn't want to add the payment comments? Do we need the bug label instead of new feature maybe?

**Comment by zanyrenney** [comment] 2024-04-22 09:03
**payment summary**

paid @fedirjh $500 via upwork
paid @dukenv0307 $500 via upwork. 

Closing!

**Closed by zanyrenney** 2024-04-22 09:03 UTC
Labels: External, Daily, NewFeature, Overdue, Awaiting Payment
