### ISSUE TITLE
HOLD [$500] Web -  IOU - When performing a split bill in a group, the skeleton view is stuck

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27200] opened 2023-09-11 20:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. First login to different accounts which two different users, one as user A and the other as user B
2. Create a group that includes user A and user B.
3. [user A] Start chat in the group.
4. Open the same group chat by both users A and B.
5. [user A] Click "plus sign" and select "Split bill".
6. [user A] Enter the amount, click Next button and Split button.

## Expected Result:
Group members (User B) should see the split bill amount.

## Actual Result:
 For the User B, the skeleton view of this action item is stuck forever until the page is refreshed or a chat is switched.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a2deb2e5-bced-45f6-90be-b5329395125f

https://github.com/Expensify/App/assets/93399543/410a310e-01ed-4c9e-930e-07f5405915cb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @paultsimura
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694182124123539
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018574fb33c023d25e</li>
        <li>Upwork Job ID: 1701338078367494144</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-09-11 20:58
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
While sending a "Split bill" request in a group, other participants see the SkeletonView stuck forever
### What is the root cause of that problem?
When the Report is rendered on the User B side, the transaction is not yet processed, so it's not present in the BE response, and therefore – in Onyx.
This leads to the skeleton view being displayed without any report-related actions.
https://github.com/Expensify/App/blob/1bad06126b80fd2b436e870320ed04cc5b34e08a/src/components/ReportActionItem/MoneyRequestPreview.js#L240-L242
### What changes do you think we should make in order to solve the problem?
We should add the following hook inside the MoneyRequestPreview component:
    const isTransactionPresent = !_.isEmpty(props.transaction);
    useEffect(() => {
        if (isTransactionPresent) {
            return;
        }

        Report.openReport(props.chatReportID);
    }, [isTransactionPresent, props.chatReportID]);
This will cause report re-fetch if a transaction is missing for the IOU Item. The dependencies of the hook will ensure it's triggered only once.
Such approach will lead to the skeleton view being visible for a few seconds only with the report being re-fetched immediately.
Result:
https://github.com/Expensify/App/assets/12595293/a6f4562d-3dac-427a-99d6-37e182fd3f58
### What alternative solutions did you explore? (Optional)

**Comment by kbecciv** [comment] 2023-09-11 20:58
Proposal by: @paultsimura
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694182124123539

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
While sending a "Split bill" request in a group, other participants see the SkeletonView stuck forever
### What is the root cause of that problem?
When the Report is rendered on the User B side, the transaction is not yet processed, so it's not present in the BE response, and therefore – in Onyx.
This leads to the skeleton view being displayed without any report-related actions.
https://github.com/Expensify/App/blob/1bad06126b80fd2b436e870320ed04cc5b34e08a/src/components/ReportActionItem/MoneyRequestPreview.js#L240-L242
### What changes do you think we should make in order to solve the problem?
We should add the following hook inside the MoneyRequestPreview component:
    const isTransactionPresent = !_.isEmpty(props.transaction);
    useEffect(() => {
        if (isTransactionPresent) {
            return;
        }

        Report.openReport(props.chatReportID);
    }, [isTransactionPresent, props.chatReportID]);
This will cause report re-fetch if a transaction is missing for the IOU Item. The dependencies of the hook will ensure it's triggered only once.
Such approach will lead to the skeleton view being visible for a few seconds only with the report being re-fetched immediately.
Result:
https://github.com/Expensify/App/assets/12595293/a6f4562d-3dac-427a-99d6-37e182fd3f58
### What alternative solutions did you explore? (Optional)

**Comment by pradeepmdk** [comment] 2023-09-12 10:16
This is pusher issue https://github.com/Expensify/App/issues/26925#issuecomment-1715369591

**Comment by sonialiap** [comment] 2023-09-14 09:41
not sure why it added me as External, I would make the worst C+ 😂  unassigning myself

**Comment by zanyrenney** [comment] 2023-09-21 03:39
Ah, okay thanks, I thought so.

**Comment by zanyrenney** [comment] 2023-09-25 09:33
This is an internal issue so we need to have an internal engineer take a look, assigned you via the auto-assigner @cead22 but let me know if i should be assigning to the project team for split bill? Thanks!

**Comment by cead22** [comment] 2023-09-28 01:53
No update, focused on detailed design for Wave 9: Violations

**Comment by zanyrenney** [comment] 2023-10-02 08:48
Any update, por favor hermano @cead22 ? 

Can you let me know if I should be doing this: 
> let me know if i should be assigning to the project team for split bill?

I know we've decided that's the most fair / efficient way to fix wave related bugs so I am leaning towards that being the best approach.

**Comment by cead22** [comment] 2023-10-02 18:09
Yes @zanyrenney that sounds great actually, otherwise I would make this weekly, and put it in the back burner, so please find somebody from split bill project, and thank you

**Comment by kbecciv** [comment] 2023-10-03 12:05
Issue related https://github.com/Expensify/App/issues/28713

**Comment by zanyrenney** [comment] 2023-10-05 13:39
hey @youssef-lr based on this comment and suggestion [here](https://expensify.slack.com/archives/C056AV5V8UX/p1690245678485799) we decided that engineers should fix the bugs introduced by the sprint team.

I believe this one for bill split arose from wave 7 - and see a bunch of issues from you for bill split - https://github.com/Expensify/Expensify/issues/322294 / https://expensify.slack.com/archives/C03SC9DVD/p1696512527374609

After discussing with @cead22 above, I think this one should be handled by the team. Can you clarify if it's you or someone else on the team and reassign based on that please?

Let me know if you have any questions about this or I am missing context on this one. Thanks!

**Comment by zanyrenney** [comment] 2023-10-05 13:40
Making weekly though for now as not an immediate priority.

**Comment by youssef-lr** [comment] 2023-10-05 13:51
I thinnk I might have an idea why this is happening, I think the transaction of the split bill is not being sent through pusher but only the report action. This wasn't part of TeachersUnite but I'll be happy to keep this assigned to me!

**Comment by zanyrenney** [comment] 2023-10-05 13:53
Thank you so much @youssef-lr ! That's really helpful. Appreciate you!

**Comment by zanyrenney** [comment] 2023-10-05 13:54
Is there an easier way for future for me to check the change and trace it back if I got it wrong here, I'd like to develop a better process for future.

**Comment by youssef-lr** [comment] 2023-10-05 14:01
Honestly things are moving so fast it's hard to keep up :D, I think the most straightforward way is to ask in Slack. You'll either get a reply from whoever is responsible for those code changes or they'll get mentioned by someone else in the thread. For example, whenever I see a bug or a discussion related to Tasks I mention Jack as I'm aware that he's been leading that project. Hope this is helpful! :)

**Comment by youssef-lr** [comment] 2023-10-05 16:05
OK figured it out while working on https://github.com/Expensify/Expensify/issues/322304, turns out we don't send the split transaction from Auth. I'll create a PR this week.

**Comment by zanyrenney** [comment] 2023-10-05 16:21
Thank you - that would be great!

**Comment by cead22** [comment] 2023-10-05 19:43
Thank you both!

**Comment by youssef-lr** [comment] 2023-10-16 10:24
Going to whip out a PR this week.

**Closed** 2024-01-16 17:33 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Help Wanted, Bug
