### ISSUE TITLE
[$500] Chat-Infinite loading occurs if conversation ID is edited to 0

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32651] opened 2023-12-07 11:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Login to ND Expensify
2. On the URL change the conversation ID to 0 (https://staging.new.expensify.com/r/0)
3. Verify you briefly see the skeleton loader
4. Verify you see a "You don't have access to this chat" message in the conversation history

## Expected Result:
"You don't have access to this chat" message in the conversation history is shown

## Actual Result:
Infinite skeleton loader occurs if conversation ID is edited to 0 in the URL
Note: The issue reproduces for only "0" value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6bd8eeda-8441-4e9b-82f3-8e6c1d8a06e5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ee46823d25664a9</li>
        <li>Upwork Job ID: 1732725262675222528</li>
        <li>Last Price Increase: 2023-12-07</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 28066316</li>
<li>bernhardoj | Contributor | 28066317</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-12-11 15:44
https://github.com/Expensify/App/assets/59907218/3e8c6841-8561-4e5f-82ad-1dc7980b5747

@dukenv0307 @yh-0218 Your solution causes this regression, also explained by this comment
https://github.com/Expensify/App/blob/56810906d7c9785295a10f9265bfb3370981bb25/src/pages/home/ReportScreen.js#L241-L242

 @mkhutornyi Can you explain you solution in more details, test it and provide screen recording. I am assuming your solution also results in this, correct me if I am wrong

**Comment by dostongulmatov** [comment] 2023-12-11 16:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat-Infinite loading occurs if conversation ID is edited to 0
### What is the root cause of that problem?
We are early returning when reportID is not valid:
https://github.com/Expensify/App/blob/b0268fab8826bb964ad4c8450c342c27e23d0d50/src/pages/home/ReportScreen.js#L243

which is preventing openReport from being called and setting isLoadingInitialReportActions to false.

### What changes do you think we should make in order to solve the problem?
We should show not found page when reportID is not valid. But when user logs in the reportID won't be present and will be defaulted to 0 which makes reportID not valid thus showing not found page. We should do 2 things
1. Change default value of reportID when it doesn't exist to ''(empty string)
2. Add additional condition to [shouldShowNotFoundPage](https://github.com/Expensify/App/blob/b0268fab8826bb964ad4c8450c342c27e23d0d50/src/pages/home/ReportScreen.js#L370C18-L370C18) 
reportIDFromPath && !ReportUtils.isValidReportIDFromPath(reportIDFromPath)
so that when reportID exists and it is invalid we make shouldShowNotFoundPage true  

### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2023-12-11 19:59
> Yes, it's unnecessary, but currently, we only do it for "null" string and "0". We should have a regex rule for 100% invalid report ID which sounds like a new feature.

Right now we are not sending any request for reportIDs which are invalid based on `isValidReportIDFromPath` function. I mean, let's not break this existing logic.

**Comment by yh-0218** [comment] 2023-12-12 11:56
@alitoshmatov My [proposal](https://github.com/Expensify/App/issues/32651#issuecomment-1845305252) was updated.

**Comment by alitoshmatov** [comment] 2023-12-13 17:32
@dostongulmatov Your solution makes sense, I agree that when reportID exists and it is invalid we should show not found page. Your fixed what other proposals were lacking with changing default reportID to '' when it does not exist.

We can go with @dostongulmatov 's [proposal](https://github.com/Expensify/App/issues/32651#issuecomment-1850453693)
C+ reviewed 🎀 👀 🎀

**Comment by alitoshmatov** [comment] 2023-12-13 17:33
@bernhardoj @yh-0218 Your solution still causes regression I mentioned earlier

**Comment by yh-0218** [comment] 2023-12-13 18:11
@alitoshmatov you checked updated proposal?

**Comment by alitoshmatov** [comment] 2023-12-14 15:05
Thank you, You are right changing default value of reportID is not a good idea.

**Comment by alitoshmatov** [comment] 2023-12-14 15:14
@yh-0218 Your proposal still causing the regression I [mentioned](https://github.com/Expensify/App/issues/32651#issuecomment-1850339556), please test it by logging out and logging in

**Comment by alitoshmatov** [comment] 2023-12-14 15:49
@bernhardoj, @dukenv0307 Both of your proposal are almost the same. Moreover your solution is similar to 2 point in @dostongulmatov 's proposal.

Even though @dostongulmatov overdid their proposal by changing default value in getReportID, he is the first one to suggest adding condition which shows not found page when reportID exists and it is invalid. 

I am just thinking whose proposal to choose 🤔

**Comment by alitoshmatov** [comment] 2023-12-18 08:04
> @alitoshmatov Return empty string in getReportID function is not only not good but also causes the regression here https://github.com/Expensify/App/issues/31089.

I am not doubting that

**Comment by alitoshmatov** [comment] 2023-12-18 08:06
@bernhardoj was the first one to suggest working solution. 
We can go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/32651#issuecomment-1845720239)

C+ reviewed 🎀 👀 🎀

cc: @neil-marcellini

**Comment by alitoshmatov** [comment] 2023-12-19 10:48
>  I'm the one who came up with the reason why we shouldn't return empty in getReportID function.

Firstly, you just pointed out the mistake I made earlier selecting proposal(thanks for that). Secondly, you are not the first one to point it out, @mkhutornyi was. You just gave some additional details which I am sure any other contributor would have provided if there was a need for it.

>Additionally, `const reportIDParams = lodashGet(route.params, 'reportID');` this check is not dry, we should check `!!routes.params.reportID`

To be honest they are the same thing, I would much prefer using `lodashGet` for safety and consistency. 

> we can improve isValidReportIDFromPath to prevent call openReportID with reportID which we can make sure it's invalid like we do in ProfilePage

The main issue here is not improving `isValidReportIDFromPath` function. Would have been nice if we could improved it? Yes. But still the proposal selection is based on solution for the current issue.

**Comment by neil-marcellini** [comment] 2023-12-20 19:08
> @bernhardoj was the first one to suggest working solution. We can go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/32651#issuecomment-1845720239)
> 
> C+ reviewed 🎀 👀 🎀
> 
> cc: @neil-marcellini

Ok, I'm happy with the solution to remove `isValidReportIDFromPath` if we test the flow mentioned in this comment, and if we test all those cases of invalid reportIDs to make sure they still work. The comment was added with the [PR to add the skeleton loader](https://github.com/Expensify/App/pull/14456), which was also authored by @bernhardoj haha.

https://github.com/Expensify/App/blob/80196fcefc867fc6ded66c8c8b03101d4cba13c7/src/pages/home/ReportScreen.js#L261-L265

**Comment by alitoshmatov** [comment] 2023-12-21 07:07
@neil-marcellini Sorry for my miscommunication, I was going to say alternative solution of @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/32651#issuecomment-1845720239) . As I mentioned [here](https://github.com/Expensify/App/issues/32651#issuecomment-1850791580) the main solution causes request being made to invalid reportIDs.

Can you have another look at the alternative solution

**Comment by alitoshmatov** [comment] 2024-01-02 11:09
@neil-marcellini Friendly bump

**Comment by bernhardoj** [comment] 2024-01-16 16:38
@neil-marcellini hi, can you check @alitoshmatov comment above?

**Comment by bernhardoj** [comment] 2024-01-22 11:49
@neil-marcellini gentle bump

**Comment by alitoshmatov** [comment] 2024-01-24 12:51
Let me summarize our progress where we left: 
This issue is taking a long time due to my miscommunication [here](https://github.com/Expensify/App/issues/32651#issuecomment-1865698503). We are waiting for @neil-marcellini confirmation on the following:
@bernhardoj main [solution](https://github.com/Expensify/App/issues/32651#issuecomment-1845720239) is not suitable for our case for the following [reason](https://github.com/Expensify/App/issues/32651#issuecomment-1850419227): 

> I think sending openReport requests for invalid reportIDs is unnecessary action and we should avoid it.

I approved @bernhardoj alternative proposal which states:

> Show the not found page if the report id is not empty and is invalid.

Which solves all the issues and straightforward. 
This issue is extremely rare since user won't update url manually and change `reportID` to 0. That is why I wanted to confirm everything and solve this issue correctly even if it takes longer time

cc: @bernhardoj @neil-marcellini

**Comment by bernhardoj** [comment] 2024-02-01 16:15
@neil-marcellini hi, can you check @alitoshmatov comment above?

**Comment by alitoshmatov** [comment] 2024-02-05 15:54
@abekkala Since @neil-marcellini  is not responding, can we get another internal engineer to take a look at this?

**Comment by abekkala** [comment] 2024-02-05 20:04
I've reached out to @neil-marcellini

**Comment by bernhardoj** [comment] 2024-02-13 19:02
Yes, it was merged yesterday https://github.com/Expensify/App/pull/33394

**Comment by abekkala** [comment] 2024-02-15 18:12
deployed to prod Feb 14

**Comment by abekkala** [comment] 2024-02-23 15:56
7 day waiting period end has ended - no regressions

Fix: @bernhardoj 
PR Review: @alitoshmatov

**Comment by abekkala** [comment] 2024-02-23 15:59
@bernhardoj and @alitoshmatov Upwork payments sent and contracts ended - thank you! 🎉

**Closed by abekkala** 2024-02-23 15:59 UTC
Labels: Reviewing, External, Daily, Bug
