### ISSUE TITLE
[$500] Android - Scan - '+n' box in the expense preview has monotone design compared to other platforms

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29827] opened 2023-10-17 20:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.3.85-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Create more than three Scan requests in workspace chat
3. Go to the workspace chat
Take a look at the '+n' box in the expense preview and see the difference between Android app and web app

## Expected Result:
The '+n' box in the expense preview on Android app shares the same design as the web app

## Actual Result:
The '+n' box in the expense preview on Android app does not have two shades of triangles compared to other platforms (web, mweb, desktop and iOS app)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 
![Bug6240971_1697570682613!Android](https://github.com/Expensify/App/assets/78819774/4ab740b8-9ed4-4b38-86c6-92b23fd48977)

![Bug6240971_1697570682637!web](https://github.com/Expensify/App/assets/78819774/5b79a81e-8335-49cf-8bfb-cc8a343e9fd5)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb1eaa9608e54e7c</li>
        <li>Upwork Job ID: 1714384161488551936</li>
        <li>Last Price Increase: 2023-10-24</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27443578</li>
<li>eh2077 | Contributor | 27443580</li>
</ul></li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-10-19 13:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Android - Scan - '+n' box in the expense preview has monotone design compared to other platforms.

### What is the root cause of that problem?

The root cause of this issue is that the way we draw triangle is not working in RN of Android, see

https://github.com/Expensify/App/blob/b3c44192363caf6d37ede254d8e78f8d31b83fcf/src/styles/styles.ts#L3755-L3767

We're using `borderWith` (and `border*Width`) and `borderColor` (and `border*Color`) to create the shape of triangle, which is a common method to create triangle from web but things become tricky on RN when working with border with transparent color, see [RN issue related to border and transparent](https://github.com/facebook/react-native/issues?q=is%3Aissue+is%3Aopen+border+transparent+).

### What changes do you think we should make in order to solve the problem?

To solve this issue, instead of drawing triangle using `borderWidth` and `borderColor`, we can use `Svg` and `Polygon` from `react-native-svg` to draw the triangle we need.

To achieve it, we replace this [line](https://github.com/Expensify/App/blob/208447611600127ec9f1191b23c71af2239d0714/src/components/ReportActionItem/ReportActionItemImages.js#L92) with

```react
<Svg 
    height={triangleWidth} 
    width={triangleWidth} 
    style={{ position: 'absolute' }}
>
    <Polygon
        points={`${triangleWidth},0 ${triangleWidth},${triangleWidth} 0,${triangleWidth}`}
        fill={isHovered ? theme.border : theme.cardBG}
    />
</Svg>
```

and define triangle width variable like

```react
const triangleWidth = variables.reportActionItemImagesMoreCornerTriangleWidth; // 40
```

See demo

https://github.com/Expensify/App/assets/117511920/41e567f5-da0e-42a0-bae3-43ebe09f6489

### What alternative solutions did you explore? (Optional)

N/A

**Comment by abdulrahuman5196** [comment] 2023-10-20 18:30
Will investigate over the weekend.

**Comment by JmillsExpensify** [comment] 2023-10-24 22:53
Still waiting on issue proposal review

**Comment by abdulrahuman5196** [comment] 2023-10-27 14:56
Sorry for the delay. Will review now

**Comment by abdulrahuman5196** [comment] 2023-10-30 12:52
Working on review today. If not complete by today, will re-assign myself to provide faster update.

**Comment by abdulrahuman5196** [comment] 2023-10-30 17:53
@bernhardoj 's solution here https://github.com/Expensify/App/issues/29827#issuecomment-1767819689 doesn't seem to be working for me.

**Comment by abdulrahuman5196** [comment] 2023-10-30 18:10
@eh2077 's proposal here https://github.com/Expensify/App/issues/29827#issuecomment-1771038349 looks good and works well. 

🎀 👀 🎀
C+ Reviewed

**Comment by MonilBhavsar** [comment] 2023-10-30 19:42
Looks good to me. Let's test it on all platforms regardless of issue happening on Android only and for various screen sizes

**Comment by eh2077** [comment] 2023-10-31 13:21
PR will be ready by tmr.

**Comment by abdulrahuman5196** [comment] 2023-10-31 14:39
Thanks for raising up @bernhardoj. I tried again and your solution is working. 
But still I would opt the current selected solution only. IMO both are straightforward fixes, and having a component for the triangle UI seems better for long term. Even if the solution would have worked the first time of my try, my suggestion would still have been the same.

**Comment by eh2077** [comment] 2023-10-31 16:03
I think using border to create triangle is more like a trick. My understanding is that the App always prefers holistic approaches over tricks.

**Comment by MonilBhavsar** [comment] 2023-10-31 16:04
> May I know why it's better for the long term?

Looks like react-native have issues with the properties we use to generate triangle using CSS and chances are we could run into similar issue again.
https://github.com/facebook/react-native/issues?q=is%3Aissue+is%3Aopen+border+transparent+

**Comment by eh2077** [comment] 2023-11-01 14:02
@abdulrahuman5196 PR https://github.com/Expensify/App/pull/30701 is ready for review, thanks!

**Comment by abdulrahuman5196** [comment] 2023-11-17 13:55
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. A platform specific present from implementation.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Not beneficial for this minor UI bug.

@JmillsExpensify 

Seems melvin didn't update here automatically. This issue should be on payment due today - https://github.com/Expensify/App/pull/30701#issuecomment-1804806250

**Comment by JmillsExpensify** [comment] 2023-11-24 18:03
Payment summary: 

 - Issue reporter: N/A
 - Contributor: @eh2077 $750 (incl. urgency bonus)
 - Contributor+: @abdulrahuman5196 $750 (incl. urgency bonus)

**Comment by JmillsExpensify** [comment] 2023-11-24 18:05
Everyone paid out based on summary above. Closing!

**Closed by JmillsExpensify** 2023-11-24 18:05 UTC
Labels: Reviewing, External, Weekly, Bug
