### ISSUE TITLE
BUG: When I select a different user chat, other user chats disappear reported by @jessica-dooley

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12186] opened 2022-10-27 14:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Cleared cache, cookies, and storage.
2. Refreshed
3. logged out then back in.
4. changed priority mode from focus to most recent then back to focus.
5. refreshed again.

## Expected Result:
Hoped that my users would not disappear.

## Actual Result:
Nothing changed, users still disappeared. When I refresh my page they do return. However, they will disappear again if I click on another user chat.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.19-2
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/198319563-62b7cf90-c482-423e-8445-ccb3b8558b56.mov

https://user-images.githubusercontent.com/43996225/198319573-84e95e15-1bcd-4d4a-8504-3239ae3f51e3.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @jessica-dooley
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666255392749659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment] 2022-10-27 21:16
I'm not sure this is a bug @kavimuru - by design, focus mode should only have unread messages remain in the LHN.

![image](https://user-images.githubusercontent.com/30815269/198399421-4d50a43e-669f-41f3-ab01-6e2b43d65d37.png)![image](https://user-images.githubusercontent.com/30815269/198399704-3ce2e31e-b1d9-40fc-9cb3-61627e0ee4e9.png)

The person who reported this indicated that they've set their settings to Focus Mode - so clicking on users will make them disappear, freeing up the LHN.

**Comment by jliexpensify** [comment] 2022-10-31 23:42
I'm going to close this, see my explanation above.

**Closed by jliexpensify** 2022-10-31 23:42 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
