### ISSUE TITLE
[$500] [Distance] Web - User can select invalid waypoint in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27021] opened 2023-09-08 13:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to offline
2. Click on FAB icon and select request money option
3. Select Distance Tab
4. Go to start or finish
5. Type any random waypoint and click on save button

## Expected Result:
Should not accept random waypoint and show error same as online mode

## Actual Result:
Accept random waypoint

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9d117a0c-5d5b-4afd-9443-31ee75c4868c

https://github.com/Expensify/App/assets/93399543/105b45d7-3c43-48db-a428-f5189c466947

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693818311285339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f9c68f1729818242</li>
        <li>Upwork Job ID: 1700132118272196608</li>
        <li>Last Price Increase: 2023-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>gadhiyamanan | Reporter | 26665559</li>
</ul></li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-09-08 13:21
### Proposal
### Please re-state the problem that we are trying to solve in this issue.

Should not accept random waypoint and show error same as online mode


### What is the root cause of that problem?

https://github.com/Expensify/App/blob/fc8adf99a11a41154ec276d44495485958e43a7d/src/pages/iou/WaypointEditor.js#L129
Here we are allowing to save user-entered text for getting the result when online 

### What changes do you think we should make in order to solve the problem?

before clicking the save button on offline mode we should validate.

here we can change logic if online we can allow the user to enter the address and the backend will fetch the lat/long. offline mode we should ignore the user enter value.
 so that we can avoid invalid waypoint request creation.

https://github.com/Expensify/App/blob/fc8adf99a11a41154ec276d44495485958e43a7d/src/pages/iou/WaypointEditor.js#L106 
here also we should not allowed on offline mode. 

in offline mode we should allow only have lat/long value in the dropdown.

**Comment by zukilover** [comment] 2023-09-08 13:26
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
In offline mode, should not accept random waypoint and show error same as online mode

### What is the root cause of that problem?
It was previously intentional because saving invalid waypoints will be handled by the backend, see these lines:
https://github.com/Expensify/App/blob/fc8adf99a11a41154ec276d44495485958e43a7d/src/pages/iou/WaypointEditor.js#L127-L134

If we are going to disallow random waypoints in offline mode, then we should not only add remove offline checking in the validations, but also:
- Remove offline checking for the search input hint
- Remove the ability to save invalid waypoints in offline mode

### What changes do you think we should make in order to solve the problem?
- Remove offline checking in the validations:
```
        if (waypointValue !== '' && waypointAddress !== waypointValue) {
            errors[`waypoint${waypointIndex}`] = 'distance.errors.selectSuggestedAddress';
        }
```

- Remove offline checking for the search input hint
```
    <AddressSearch
           inputID={`waypoint${waypointIndex}`}
           ref={(e) => (textInput.current = e)}
           hint={translate('distance.errors.selectSuggestedAddress')}
```

- Remove the ability to save invalid waypoints in offline mode
```
/** Remove these lines
      if (isOffline && waypointValue) {
            const waypoint = {
                lat: null,
                lng: null,
                address: waypointValue,
            };

            Transaction.saveWaypoint(transactionID, waypointIndex, waypoint);
        }*/
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Pujan92** [comment] 2023-09-08 13:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For offline waypoint user can enter invalid value

### What is the root cause of that problem?
We are allowing incorrect waypoint enter for the offline mode and not asking to choose from the predefined options.

### What changes do you think we should make in order to solve the problem?
I think for offline also we need to allow user to select only from the list instead of allowing to enter any text in the waypoint.
For that we need to remove this condition
https://github.com/Expensify/App/blob/fc8adf99a11a41154ec276d44495485958e43a7d/src/pages/iou/WaypointEditor.js#L106-L108

Remove first condition of `!isOffline` from here to make it a common place.
https://github.com/Expensify/App/blob/fc8adf99a11a41154ec276d44495485958e43a7d/src/pages/iou/WaypointEditor.js#L112

**Comment by CortneyOfstad** [comment] 2023-09-08 18:44
@isabelastisser it assigned us both as `bug` and `external`. For some reason Melvin is having a moment 😂 

Going to unassign myself 👍

**Comment by isabelastisser** [comment] 2023-09-11 17:22
I will review this when I have a chance.

**Comment by isabelastisser** [comment] 2023-09-11 19:04
Hey @robertKozik, can you please review the proposals above? Thanks!

**Comment by robertKozik** [comment] 2023-09-11 21:27
Of course, I'll get on it first thing tomorrow morning.

**Comment by robertKozik** [comment] 2023-09-13 18:37
Hi all! Thank you for your proposals! 🙇🏼 
I see that all three of you @Pujan92 @zukilover @pradeepmdk @namhihi237 correctly pinpoint root cause of the problem. This said I believe we should go with the @zukilover as it's the only one proposal which addresses the issue as a whole - removing the leftover code in all cases:
- `isOffline` check in validation;
- inside search input;
- saving waypoints in offline mode;

That's why I'm all for @zukilover [proposal](https://github.com/Expensify/App/issues/27021#issuecomment-1711670992)

🎀 👀 🎀 C+ reviewed

**Comment by isabelastisser** [comment] 2023-09-13 18:43
Thanks @robertKozik ! Waiting for @aldo-expensify to approve the proposal.

**Comment by zukilover** [comment] 2023-09-14 03:18
PR will be ready in 3 hrs

**Comment by aldo-expensify** [comment] 2023-09-18 04:00
I was going to review the PR, but from looking at the code changes I noticed that this appeared to be intentional behaviour. I didn't find anyone from Expensify in the communication chain (this issue + slack convo) agreeing with this being a bug and approving the proposed expected outcome.

Started a conversation here: https://expensify.slack.com/archives/C05DWUDHVK7/p1695008113684229 and the conclusion is that this is expected behaviour and not a bug.

cc @isabelastisser

**Comment by zukilover** [comment] 2023-09-19 08:57
@aldo-expensify @isabelastisser Thanks for the updates. Please kindly advise on how to proceed with this, since in the original proposal I already mentioned that it was intentional, but we decided to go forward with the changes.

**Comment by isabelastisser** [comment] 2023-09-20 15:50
We discussed this internally and decided to close this issue. Because this was originally not a bug and intentional behavior, I will process a partial payment to the contributor with the approved proposal - @zukilover - for putting time toward the PR.

We will not process the payment for the issue reporter or C+ review because this was intentional behavior that didn't need to be fixed. 

Thanks!

**Closed by isabelastisser** 2023-09-20 15:50 UTC
Labels: Reviewing, Weekly, Bug
