### ISSUE TITLE
Android - Payments- White space is displayed in Settings after make default payment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10520] opened 2022-08-24 11:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10162

## Action Performed:
Precondition: VBA added into testing account
1. Go to NewDot
2. Log in with account
3. Go to Setting - Payment
4. Select Payment and add as default
5. Go to Settings

## Expected Result:
White space is not displayed in Settings after make default payment

## Actual Result:
White space is displayed in Settings after make default payment

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.89.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186409475-6571334d-2b19-4d4b-b83b-f1ac5a7aaaea.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sketchydroide** [comment] 2022-08-24 13:37
@youssef-lr this might be to much (we need it fixed today), I'll try to see if someone else can pick it up

**Comment by Luke9389** [comment] 2022-08-24 14:14
I'm gonna leave an obnoxious amount of updates on this issue until it's solved.
First step is updating all repos and then reproducing this in my dev environment.

**Comment by Luke9389** [comment] 2022-08-24 14:18
Checking out the onClose of the AddPaymentMethodMenu.

**Comment by mountiny** [comment] 2022-08-24 14:24
cc @rushatgabhane and @dhairyasenjaliya _might_ be related to the changes in https://github.com/Expensify/App/pull/10162 if you could have a look

**Comment by marcaaron** [comment] 2022-08-24 14:26
Random guess but looks like the offline indicator component or keyboard shortcuts modal could be taking up space when in view.

https://github.com/Expensify/App/blob/dbfd0eb5ae2cd321db5075f088492f87ff1e8860/src/components/ScreenWrapper/BaseScreenWrapper.js#L82-L93

**Comment by Luke9389** [comment] 2022-08-24 14:32
Building android is happening _very_ slowly right now.

**Comment by marcaaron** [comment] 2022-08-24 14:37
Can someone confirm that this also happens on web? And if so, what are the reproduction steps?

**Comment by marcaaron** [comment] 2022-08-24 14:38
I followed the steps above but could not reproduce on staging web. The issue description says that these platforms are affected:

Web
iOS
Android
Desktop App
Mobile Web

**Comment by dhairyasenjaliya** [comment] 2022-08-24 14:39
> Random guess but looks like the offline indicator component or keyboard shortcuts modal could be taking up space when in view.
> 
> https://github.com/Expensify/App/blob/dbfd0eb5ae2cd321db5075f088492f87ff1e8860/src/components/ScreenWrapper/BaseScreenWrapper.js#L82-L93

Yup as we tested keyboard spacer but this new changes for offline indicator made android issues

**Comment by mountiny** [comment] 2022-08-24 14:41
> Can someone confirm that this also happens on web? And if so, what are the reproduction steps?

I think they only mentioned Android in title, meaning this is only on Andoird but havent updated the list later on

**Comment by sketchydroide** [comment] 2022-08-24 14:44
> I followed the steps above but could not reproduce on staging web. The issue description says that these platforms are affected:
> 
> Web iOS Android Desktop App Mobile Web

The title says it's specific to Android though, maybe the description was not updated correctly?

**Comment by Luke9389** [comment] 2022-08-24 14:53
Hey @rushatgabhane, how do I disable Hermes?

**Comment by Luke9389** [comment] 2022-08-24 14:55
When testing this, I'm trying to add a payment method, but the option is greyed out, does anyone happen to know why?
<img width="539" alt="Screen Shot 2022-08-24 at 4 55 10 PM" src="https://user-images.githubusercontent.com/49007721/186451276-62aa5acf-7e23-4430-87dc-2bb7d4096da9.png">

**Comment by JmillsExpensify** [comment] 2022-08-24 14:59
FWIW, I'm don't think this is a real deploy blocker given that this part of the App is tied to our internal P2P beta – though obviously we should fix it more generally.

**Comment by dhairyasenjaliya** [comment] 2022-08-24 15:05
> @dhairyasenjaliya Can you please give as much detail as possible on what this means?
> 
> > Yup as we tested keyboard spacer but this new changes for offline indicator made android issues

Soon I will investigate this currently im away from my mac

**Comment by Luke9389** [comment] 2022-08-24 15:09
> FWIW, I'm don't think this is a real deploy blocker given that this part of the App is tied to our internal P2P beta – though obviously we should fix it more generally.

In that case I think we should remove the `DeployBlockerCash` label. @sketchydroide are you cool with that?

**Comment by sketchydroide** [comment] 2022-08-24 15:11
yes, go ahead also let't make is a daily, it needs to be fixed once this in no longer a beta

**Comment by kbecciv** [comment] 2022-08-24 17:00
@sketchydroide @sketchydroide My apologies, issue only accrued in Android app, updated issue environment.

**Comment by sketchydroide** [comment] 2022-08-24 17:01
no worries, it's just good to keep it consistent so we don't loose time testing platforms
thanks 😄

**Comment by dhairyasenjaliya** [comment] 2022-08-24 18:24
**Solution**

- We should remove  LayoutAnimation.configureNext from the baseKeyboard as this animation is getting clashes with `BaseScreenWrapper`   because in the wrapper we are already using `<KeyboardAvoidingView>` which is also using same animation  

https://github.com/Expensify/App/blob/4df4c8bcf24b5649cf39084affa773becb892ef9/src/components/KeyboardSpacer/BaseKeyboardSpacer.js#L55

https://github.com/Expensify/App/blob/4df4c8bcf24b5649cf39084affa773becb892ef9/src/components/KeyboardSpacer/BaseKeyboardSpacer.js#L69

**Result with removing animation (fix)**  

https://user-images.githubusercontent.com/47522946/186494485-11cf8f1d-b445-464a-8b06-c3b6c421ab92.mp4

**Result with animation**

https://user-images.githubusercontent.com/47522946/186494283-51ea63ee-b8f6-4821-89e1-b0c0c200e987.mp4

**Comment by roryabraham** [comment] 2022-08-24 18:59
Was able to confirm that this fixes the issue

**Closed** 2022-08-24 19:23 UTC
Labels: Engineering, Daily
