### ISSUE TITLE
Web - Workspace - 404 error in the console appears when navigating to Workspace settings

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18650] opened 2023-05-09 16:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log with any account
3. Go to Settings -> Workspaces and etc

## Expected Result:
No any errors in console

## Actual Result:
404 error in the console appears when navigating to Workspace settings

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0424e66b-9b86-4202-8b83-8232e5ab4d10

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2023-05-09 18:32
I'm not able to reproduce this, so I think we're missing part of the picture here. Judging by the logs, tt seems like this is more related to tasks than workspaces. What testing did you do before you encountered this issue @kbecciv ?

**Comment by roryabraham** [comment] 2023-05-09 18:34
cc @thienlnam

**Comment by kbecciv** [comment] 2023-05-10 13:47
@roryabraham Be honest, I don't remember what did I do before getting this error.

**Comment by thienlnam** [comment] 2023-05-10 18:33
I think this is related to you creating a task (the API endpoint doesn't exist yet). We've merged some fixes so I imagine this will resolve in the coming days

**Comment by thienlnam** [comment] 2023-05-19 18:26
Okay, should be resolved and not happening anymore

**Closed by thienlnam** 2023-05-19 18:26 UTC
Labels: Engineering, Daily, Overdue, Bug
