### ISSUE TITLE
Task - Assignee list opens with some delay

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36434] opened 2024-02-13 20:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  v1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Assign task..
3. Enter title > Next.
4. Click Assignee.
## Expected Result:
Assignee list opens smoothly.

## Actual Result:
Assignee list opens with some delay.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/827853d7-7ffc-400a-aeb3-449f38171505

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2024-02-13 20:51
I'm not sure why this is a deploy blocker...the behavior in the video for production and staging seem the same? I'm also not really convinced this is even a bug. 

We're showing the skeleton UI while the list is loading. Is the bug that we're even showing the skeleton UI at all?

**Comment by blimpich** [comment] 2024-02-13 21:11
Agreed, I don't see any difference between this and production personally. I do see how this isn't opening smoothly. It kind of has a clunky movement to it if you watch the video. I, however, can't replicate that exact clunkiness on staging, which makes me think this is a fluke.

@kavimuru is the clunkiness that you are experiencing only on staging? And does it persist if you reload the page, or try in a different browser?

**Comment by joekaufmanexpensify** [comment] 2024-02-13 22:05
I can't reproduce it on staging either.

**Comment by joekaufmanexpensify** [comment] 2024-02-14 14:39
I still can't reproduce this. Closing for now. LMK if anyone else ends up being able to reproduce this though, and happy to reopen!

**Closed by joekaufmanexpensify** 2024-02-14 14:39 UTC
Labels: Engineering, Daily, Bug
