### ISSUE TITLE
[HOLD for payment 2023-10-24] [$500] DEV: console error on click of send money

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29464] opened 2023-10-12 16:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev
**Reproducible in staging?:** Reproduced in Dev only
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697088716700199

## Action Performed:
1. click FAB icon
2. select send money option
## Expected Result:
 should not show console error
## Actual Result:
console error appears(forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component?)
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/1090da5e-e6cc-499e-9a27-c2ac547c5e29

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/7d67baf4-3ada-4783-b0c6-9854219fcee7

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/319827f9-a3a3-4fb3-8186-c29437d84f90

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/4b275610-a4fb-4f57-a520-ee8d54350d78

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/a39a441b-d0ea-48d8-8e1c-28c0c4d0d0a2

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/c714d826-4506-4b80-aa2e-8dde51841f5c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01260d59659dd2e2bf</li>
        <li>Upwork Job ID: 1712499464820834304</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 27184034</li>
<li>pradeepmdk | Contributor | 27184036</li>
<li>gadhiyamanan | Reporter | 27184038</li>
</ul></li>
    </ul>
</details>

**Comment by ilmzone** [comment] 2023-10-12 16:26
### Proposed Solution for Issue #29464:

To address the console error on clicking the 'send money' option, I propose the following steps:

1. **Identify the Component**: Start by identifying the React component that's causing the error. This can be done by tracing the error stack or by searching for components that use `forwardRef` and also have `propTypes` or `defaultProps` defined.

2. **Refactor the Component**: Once the component is identified, refactor it to ensure that `propTypes` and `defaultProps` are not being used with `forwardRef`. If necessary, wrap the component in another component that handles the prop types and default props.

3. **Testing**: After refactoring, test the changes in the development environment, specifically on MacOS (both Chrome/Safari and Desktop versions) to ensure the console error no longer appears. Additionally, test other functionalities related to the 'send money' option to ensure no new issues are introduced.

4. **Documentation**: Document the changes made, the reason for those changes, and any potential side effects that might occur.

5. **Pull Request**: Once the changes are tested and documented, create a pull request to merge the changes into the main codebase. Include screenshots and confirmation that the changes have been tested on all affected platforms.

Looking forward to feedback and further instructions.

**Comment by zzarcon** [comment] 2023-10-12 16:39
Just did some initial investigation, and the issue seems to be happening with the `<NavigationAwareCamera>` component 

`src/pages/iou/ReceiptSelector/NavigationAwareCamera.js`

We are assigning `propTypes` and `defaultProps` and later wrapping the component with a `forwardRef` 

```
NavigationAwareCamera.propTypes = propTypes;
NavigationAwareCamera.displayName = 'NavigationAwareCamera';
NavigationAwareCamera.defaultProps = defaultProps;

export default React.forwardRef(NavigationAwareCamera);
```

**Comment by pradeepmdk** [comment] 2023-10-12 16:45
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
console error on click of send money 
### What is the root cause of that problem?
https://expensify.slack.com/archives/C01GTK53T8Q/p1695110739750909
we already discussed in Slack 

### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/main/src/pages/iou/ReceiptSelector/NavigationAwareCamera.js
here we need changes like 
```javascript
const NavigationAwareCamera = React.forwardRef(({torchOn, onTorchAvailability, ...props}, ref) => {
++
export default NavigationAwareCamera
```

**Comment by akinwale** [comment] 2023-10-13 05:12
While both proposals so far would solve the issue, I would recommend going with @pradeepmdk's [solution](https://github.com/Expensify/App/issues/29464#issuecomment-1759985622) as this follows the documented coding standards. The `MenuItem` component would be a good reference point to follow for implementation.

🎀 👀 🎀 C+ reviewed.

**Comment by pradeepmdk** [comment] 2023-10-14 13:37
@akinwale Pr is ready for review

**Comment by lschurr** [comment] 2023-10-23 21:36
@akinwale could you work on the checklist for this one?

**Comment by akinwale** [comment] 2023-10-24 02:49
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:

> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR, but there is now a standard for using `React.forwardRef` as pointed out in the selected [proposal](https://github.com/Expensify/App/issues/29464#issuecomment-1759985622). New implementations can refer to this going forward. https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md#forwardRef

> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression, it was an erroneous implementation approach with `React.forwardRef`.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression test**
1. Launch Expensify in a browser.
2. Open the browser developer tools and select the Console tab to monitor for errors.
3. Open the global create menu and select Send money.
4. Verify that there is no console error after the Send money flow starts.

Do we agree 👍 or 👎

**Comment by akinwale** [comment] 2023-10-24 02:49
@lschurr Done!

**Comment by lschurr** [comment] 2023-10-24 16:31
Payment summary:

- Bug reporter: @gadhiyamanan $50
- Contributor: @pradeepmdk $750
- Contributor+: @akinwale $750

**Comment by lschurr** [comment] 2023-10-24 16:33
All paid! Closing.

**Closed by lschurr** 2023-10-24 16:33 UTC
Labels: External, Daily, Awaiting Payment, Bug
