### ISSUE TITLE
Expense - Duplicate transaction threads with RBR in LHN when sending expense to each other

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43252] opened 2024-06-07 10:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-9
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4601025
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User A and B have no chatted before.
- Both accounts must be new.

1. Go to staging.new.expensify.com
2. [User A] Go offline.
3. [User A] Submit an expense to User B.
4. [User B] Submit an expense with the same amount to User A.
5. [User A] Go online.

## Expected Result:
User A will not have two same transaction threads with RBR on LHN.

## Actual Result:
User A receives two same transaction threads with RBR on LHN (not the main chat).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/eaeca0e0-6eb6-48f0-8b0f-f8c808c7dc86

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-06-07 10:11
@lschurr I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-06-07 10:11
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-06-07 10:12
Production 

https://github.com/Expensify/App/assets/115492554/cd8227b0-c232-4a25-803f-4325318062dd

**Comment by luacmartins** [comment] 2024-06-07 15:20
Seems like it could be caused by https://github.com/Expensify/App/pull/41507

**Comment by luacmartins** [comment] 2024-06-07 15:25
I can confirm that reverting https://github.com/Expensify/App/pull/41507 fixes the issue. I'm gonna go ahead with the revert since that PR also caused other regressions.

**Comment by luacmartins** [comment] 2024-06-07 15:30
Got a revert PR up

**Comment by roryabraham** [comment] 2024-06-07 17:39
fixed by a [revert](https://github.com/Expensify/App/pull/43304), no payments due

**Closed by roryabraham** 2024-06-07 17:39 UTC
Labels: Reviewing, Engineering, Weekly, Bug
