### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] Expensify personal  - Expensify chat has the option to rename

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44193] opened 2024-06-22 12:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Expensify chat
3. Click on the chat header
4. Click Room name
5. Edit the name and save it

## Expected Result:
Expensify chat should not have the option to rename

## Actual Result:
Expensify chat has the option to rename, but it actually cannot be renamed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b7924fb5-8bd6-418c-bf6c-6d0e98643a48

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment] 2024-06-22 12:28
@pecanoro  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neonbhai** [comment] 2024-06-22 13:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expensify personal - Expensify chat has the option to rename

### What is the root cause of that problem?
We use `shouldDisableRename` function to check if a room can be renamed, we don't take into account System Chats for this

https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/libs/ReportUtils.ts#L6146

### What changes do you think we should make in order to solve the problem?
We will add a check for `ReportUtils.isSystemChat(report)` in the `shouldDisableRename` function here:

https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/libs/ReportUtils.ts#L6147-L6157

**Comment by mountiny** [comment] 2024-06-24 09:20
Gonna help moving this one forwards to get the checklist into a better place before deployer comes on

**Comment by mountiny** [comment] 2024-06-24 09:27
Using a solution from @neonbhai works well. $50 for helping identify the fix

**Comment by pecanoro** [comment] 2024-07-02 19:53
We can simply close this one!

**Comment by neonbhai** [comment] 2024-07-02 20:59
@pecanoro hi, I'm eligible for compensation here as noted in https://github.com/Expensify/App/issues/44193#issuecomment-2186033561. Please take a look 🙇

**Comment by mountiny** [comment] 2024-07-05 00:29
Yes $50 for your help @neonbhai

**Comment by pecanoro** [comment] 2024-07-16 20:20
@anmurali Friendly bump on this: https://github.com/Expensify/App/issues/44193#issuecomment-2209666646

**Comment by anmurali** [comment] 2024-07-16 23:30
@neonbhai - [here](https://www.upwork.com/nx/wm/offer/103148241) is your offer

**Comment by neonbhai** [comment] 2024-07-17 00:05
Thank you, offer accepted!

cc: @anmurali

**Comment by anmurali** [comment] 2024-07-23 00:20
Paid.

**Closed by anmurali** 2024-07-23 00:20 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
