### ISSUE TITLE
[$500]  IOU - Blank area displayed instead route preview on distance request details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30741] opened 2023-11-02 00:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
Precondition: user should be signed in as employee in workspace chat and a few distance routes should be cached
1. Open app
2. Click on the workspace conversation in LHN
3. Click on plus button > Request Money
4. Select Distance tab
5. Disable internet connection
6. Select cached routes for Start and Finish
7. Click Next button
8. Click on Request button
9. Navigate to the Requested distance request details page
10. Enable internet connection

## Expected Result:
Distance routes preview should be displayed properly when user goes online

## Actual Result:
Blank area displayed instead distance routes preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bb73bc6c-c9a2-4d61-981e-f1b845604eb0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0f203a9a5482674</li>
        <li>Upwork Job ID: 1719881649915318272</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

**Comment by alvinlee001** [comment] 2023-11-02 07:03
i was trying to work on this, but when i go online, the TBD changed when i was back online.... but was maybe 10-20 seconds later after i was online

**Comment by alvinlee001** [comment] 2023-11-02 07:21
Contributor details
Your Expensify account email: alvinlee001@live.com.my
Upwork Profile Link: https://www.upwork.com/freelancers/~011595cc795447921c

**Comment by s77rt** [comment] 2023-11-06 09:18
Not overdue. Still looking for proposals

**Comment by eh2077** [comment] 2023-11-06 13:59
Can't reproduce it.

**Comment by barttom** [comment] 2023-11-08 09:31
@lanitochka17 could YOu confirm that is still reproducible?

**Comment by s77rt** [comment] 2023-11-08 10:26
Not overdue. Looking for proposals (and may need reproduction confirmation)

**Comment by kbecciv** [comment] 2023-11-08 13:14
Checking @barttom

**Comment by kbecciv** [comment] 2023-11-08 14:07
Issue is not longer reproduced

https://github.com/Expensify/App/assets/93399543/aa5b7b6f-e2bc-4d14-8522-5f909644b465

**Comment by greg-schroeder** [comment] 2023-11-09 11:28
Going to close this accordingly

**Closed by greg-schroeder** 2023-11-09 11:28 UTC
Labels: External, Daily, Help Wanted, Bug
