### ISSUE TITLE
[$500] mWeb - Bank account - Page scrolls to the top when tapping on a field

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36461] opened 2024-02-14 02:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in and have created a workspace.

1. Go to Workspace > Bank account.
2. Select "Connect manually".
3. Tap on any of the fields.
4. Verify the page scrolls to the top.
## Expected Result:
The focus should remain on the selected field.

## Actual Result:
The page scrolls to the top.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/088fbd53-cef4-4f6d-be84-045c4c740f37

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f9f343288d7d26ba</li>
        <li>Upwork Job ID: 1757590702622396416</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>akinwale | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-02-14 03:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want the keyboard not to overlap the input selected

### What is the root cause of that problem?
The keyboard is not adjusting the height to the margin on the screen. As well as the input validation errors.

### What changes do you think we should make in order to solve the problem?
We can make a simple change to update the margin to padding, so that the input doesn't get covered by the keyboard
https://github.com/Expensify/App/blob/023d62cba900f4333f73c52eb735402a994cbc4b/src/pages/ReimbursementAccount/BankInfo/BankInfo.tsx#L137
updating mt3 style to pt3

### What alternative solutions did you explore? (Optional)

**Comment by andreasnw** [comment] 2024-02-14 05:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
component didn't automatically adjust its height and position while the virtual keyboard is displayed.

### What is the root cause of that problem?
the BankInfo component's maximum height is set to 100%, which means it can't adjust or scroll beyond the screen

https://github.com/Expensify/App/blob/023d62cba900f4333f73c52eb735402a994cbc4b/src/pages/ReimbursementAccount/BankInfo/BankInfo.tsx#L126-L131

### What changes do you think we should make in order to solve the problem?


remove the `shouldEnableMaxHeight` props from the `ScreenWrapper` component on `BankList` page.
``` 
        <ScreenWrapper
            testID={BankInfo.displayName}
            includeSafeAreaPaddingBottom={false}
            shouldEnablePickerAvoiding={false}
        >
```
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by miljakljajic** [comment] 2024-02-14 11:18
@fedirjh any thoughts on the above?

**Comment by mountiny** [comment] 2024-02-14 12:19
@MrMuzyk @barttom could have a look

**Comment by mountiny** [comment] 2024-02-14 12:20
Looking at the bug this is not a blocker, rather a minor inconvenience they can still scroll and see the field just fine.

**Comment by mountiny** [comment] 2024-02-14 12:58
@andreasnw Hello! Sorry for the confusion.

This issue has been raised as a regression to a specific PR which was linked above. In such cases, per the contributor guidelines the PR author should be in charge of fixing it as well as the C+ (@akinwale) who has reviewed the original PR.

So in these cases we will prefer them to fix this issue as they already got paid for their work. In case they will use your solution provided, we can reward you with partial payment for help.

I hope this helps

**Comment by andreasnw** [comment] 2024-02-14 13:00
Got it @mountiny, thank you!

**Comment by Swor71** [comment] 2024-02-14 15:02
Hey I'm Marcin from Callstack - expert contributor group - I'd like to work on this issue

**Comment by mountiny** [comment] 2024-02-19 13:45
@Swor71 will tackle this tomorrow

**Comment by Swor71** [comment] 2024-02-21 16:07
fixed in: https://github.com/Expensify/App/pull/37032

**Comment by mountiny** [comment] 2024-03-04 18:22
@andreasnw sorry, this was a follow up to feature Callstack agency worked on and it was starightforward solution, I wont complicate this further, sorry we have mislabelled this as help wanted when agency was supposed to handle this

**Closed by mountiny** 2024-03-04 18:22 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
