### ISSUE TITLE
[HOLD for payment 2023-08-08] Dev: Web - Console log error when trying to unlink secondary contact method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22923] opened 2023-07-14 21:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a tab where account A is signed-in
2. Add secondary contact method B, and do not verify that contact method
3. Open a new window > Navigate to sign-in page
4. Enter secondary contact method B & click on the continue button

## Expected Result:
There shouldn't be any console log error

## Actual Result:
Console log error displayed (ailed prop type: The prop `welcomeText` is marked as required in `SignInPageContent`, but its value is `undefined`.)

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev  1.3.40-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/39606f7d-96cd-4849-a4e4-ec06612db825

**Expensify/Expensify Issue URL:**
**Issue reported by:** React JS Developer | Software QA Analyst | GH: @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689337434182419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-07-14 22:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console log error when trying to unlink secondary contact method.

### What is the root cause of that problem?
The root cause is that `props` does not include `welcomeText`, but `welcomeText` is marked as required.
https://github.com/Expensify/App/blob/272d921d4fbd3f6bf98e6b124c8cc53eefdafc3b/src/pages/signin/SignInPageLayout/SignInPageContent.js#L23

So the console error is displayed.

### What changes do you think we should make in order to solve the problem?
We should remove `isRequired` as below.
```js
    welcomeText: PropTypes.string,
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by sophiepintoraetz** [comment] 2023-07-18 23:42
Hey @MonilBhavsar - assigning you to help with reproducing the console error - as it's in a DEV environment.

**Comment by sophiepintoraetz** [comment] 2023-07-24 04:57
Bump for @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2023-07-24 05:42
Sorry, I'm able to reproduce the issue. Looking if it's a regression, so we can ask author to fix it.

**Comment by MonilBhavsar** [comment] 2023-07-24 06:47
Commented on the PR. Looks like we missed this during Migration from class component to functional component, and is a minor change. Would just push a quick fix and request review from author.

**Comment by sophiepintoraetz** [comment] 2023-07-28 05:03
Reporting offer sent - only payment due here seeing as Monil took the fix internally 🙏

**Comment by Natnael-Guchima** [comment] 2023-07-28 05:56
Accepted the offer. Thank you.

**Comment by sophiepintoraetz** [comment] 2023-08-04 04:54
Payments done!

**Comment by MonilBhavsar** [comment] 2023-08-23 09:46
Reopening to pay c+

**Comment by sophiepintoraetz** [comment] 2023-08-28 05:07
I see that we have an internal discussion on the best way to pay @0xmiroslav - given that we cannot pay another account

**Comment by sophiepintoraetz** [comment] 2023-08-29 01:29
Discussed internally that we cannot pay another account other than to @0xmiroslav - [I've sent an offer here](https://www.upwork.com/nx/wm/offer/26380323)!

**Closed by sophiepintoraetz** 2023-08-29 01:29 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
