### ISSUE TITLE
[Hold of payment 8-27][$250] Cannot scroll down after comment linking

### ISSUE THREAD

**Issue by janicduplessis** [Expensify/App#46217] opened 2024-07-25 18:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @janicduplessis 
**Slack conversation:**

## Action Performed:

- In a chat with many messages copy the link to a message and send it
- Clear the app cache (Troubleshoot -> Clear cache and restart)
- Click on the message link from the first step
- Cannot scroll down

## Expected Result:

Can scroll down after linking to message

## Actual Result:

Cannot scroll down

## Workaround:

Scroll up, then scroll back down

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/711587a0-218d-44f0-b0c0-b90a8f7d33da

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016056b96e55e3a838</li>
        <li>Upwork Job ID: 1817986329686132368</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by janicduplessis** [comment] 2024-07-25 18:11
The issue seems to be related to [this code](https://github.com/Expensify/App/blob/904e95008af0b3ee156421c048570c064f090f01/src/pages/home/report/ReportActionsView.tsx#L400), which prevents newer messages from being rendered. I am looking with the original author of this code to see why it was needed and if it can be removed.

**Comment by janicduplessis** [comment] 2024-07-25 18:36
I have a potential fix, but first need to figure out why this code was needed in the first place and if would cause a regression to remove it.

**Comment by Christinadobrzyn** [comment] 2024-07-26 20:30
Looks like this is the same report as - https://github.com/Expensify/App/issues/46222

Not sure if both of you can work on this as the C+ and contributor? cc @ishpaul777 @janicduplessis

**Comment by janicduplessis** [comment] 2024-07-27 15:37
@ishpaul777 Would it be easier for you if I create a single PR that fixes all the issues?

Right now I identified 4 bugs with comment linking that all cause some slightly different issues. They all have different root cause so code wise they can be isolated, but I think it might be easier for QA to just test with all the fixes applied to see that it is now smooth.

**Comment by Christinadobrzyn** [comment] 2024-07-29 18:11
hi! I'm gonna add @ishpaul777 to this since both this GH and https://github.com/Expensify/App/issues/46222#issuecomment-2256565889 will be resolved together.

**Comment by Christinadobrzyn** [comment] 2024-07-29 18:11
@strepanier03 I'm happy to take this GH if that would be easier for tracking!

**Comment by strepanier03** [comment] 2024-07-29 22:02
@Christinadobrzyn - Sounds good to me. I haven't looked at it until now anyway. I'll assign you, thanks!

**Comment by Christinadobrzyn** [comment] 2024-07-30 17:14
Awesome! Sounds good Sheena!

**Comment by Christinadobrzyn** [comment] 2024-07-31 21:19
Correct me if I'm wrong but the PR for this is here - https://github.com/Expensify/App/issues/46222#issuecomment-2257516099, right?

**Comment by janicduplessis** [comment] 2024-07-31 21:21
Yes, I consolidated the fixes around comment linking in this PR. Currently looking into janky scroll on android which I think I just found the problem, then PR should be ready.

**Comment by Christinadobrzyn** [comment] 2024-08-01 22:34
I'm adding a HOLD on this because the PR is here https://github.com/Expensify/App/issues/46222 so I think this issue can just be tested once the PR is deployed and we can make sure it's resolved too.

**Comment by Christinadobrzyn** [comment] 2024-08-06 22:58
monitoring the PR - https://github.com/Expensify/App/pull/46315

**Comment by Christinadobrzyn** [comment] 2024-08-13 20:43
monitoring the PR - https://github.com/Expensify/App/pull/46315

**Comment by bondydaa** [comment] 2024-08-16 20:34
not sure why I got assigned, looks like @roryabraham is assigned on the PR so going to move it over to you.

**Comment by Christinadobrzyn** [comment] 2024-08-20 21:13
PR is in staging - almost there - https://github.com/Expensify/App/pull/46315

**Comment by roryabraham** [comment] 2024-08-20 23:03
PR deployed to prod

**Comment by Christinadobrzyn** [comment] 2024-08-26 15:09
Awesome! Looks like the 7th day of prod is tomorrow so let's prep for payment. 

- @janicduplessis you are with Margelo so paid separately, correct?
- Do we need a regression test for this?

Payouts due:

- [ ] Contributor+: $250 @ishpaul777 (upwork offer - https://www.upwork.com/nx/wm/offer/103686400)

**Comment by janicduplessis** [comment] 2024-08-26 17:18
@Christinadobrzyn correct!

**Comment by Christinadobrzyn** [comment] 2024-08-27 23:18
Ah, sorry about that, @ishpaul777  - I paid you through the offer associated with this Upwork job. That offer in the payment summary - https://github.com/Expensify/App/issues/46217#issuecomment-2310450224

I'll create the regression test tomorrow

**Comment by Christinadobrzyn** [comment] 2024-08-28 22:59
Regression test - https://github.com/Expensify/Expensify/issues/424177

[payment is done ](https://github.com/Expensify/App/issues/46217#issuecomment-2310450224)- closing!

**Closed by Christinadobrzyn** 2024-08-28 22:59 UTC
Labels: Reviewing, External, Daily, Help Wanted, Bug
