### ISSUE TITLE
[HOLD for payment 2024-05-14][$250] Send invoice - Hide visibility and room name fields in the Settings page of the Invoice room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41280] opened 2024-04-30 02:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40015
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice
3. Enter amount and select a participant
4. Create the invoice
5. Click on the workspace chat header
6. Go to Settings > Visibility
7. Change to a different visibility

## Expected Result:
Invoice workspace chat should not show visibility settings if it cannot be changed

## Actual Result:
Invoice workspace chat shows visibility settings and it always reverts to "Private"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/568b8b7b-86d3-411e-9fe0-a6e537df8caa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3de929b3f13fc60</li>
        <li>Upwork Job ID: 1785187069614149632</li>
        <li>Last Price Increase: 2024-04-30</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-30 02:03
@robertjchen  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by robertjchen** [comment] 2024-04-30 05:58
Does not appear to be a serious deploy blocker to me and should be addressable by external contributors 👍

**Comment by waterim** [comment] 2024-04-30 10:32
Hey, Im Artem from Callstack and would like to take this issue
cc @cristipaval

**Comment by waterim** [comment] 2024-04-30 10:36
> isn’t this issue external? @waterim ? 

Yes, this one can be taken by someone External, will jump to the other issues

**Comment by cristipaval** [comment] 2024-04-30 14:56
this is #vip-billpay related. @danielrvidal could you please help prioritze?

**Comment by danielrvidal** [comment] 2024-04-30 19:42
This is a solid clean up item, but given it's not breaking the room I'm assigning it a Medium.

**Comment by cristipaval** [comment] 2024-04-30 20:49
@GandalfGwaihir go ahead and hide both the visibility and the room name fields on the Settings page

**Comment by cristipaval** [comment] 2024-04-30 20:50
Also, this is critical, @GandalfGwaihir, so please give it the highest urgency 🙏

**Comment by rushatgabhane** [comment] 2024-04-30 21:04
@cristipaval isn't this feature under a beta? should we do nothing if the visibility would be allowed to change in future?

**Comment by cristipaval** [comment] 2024-04-30 21:08
No beta for this feature. For now, we want the invoice rooms to behave like workspace chats. We'll revisit it if we decide to allow visibility change. We'll hide the setting for now.

**Comment by danielrvidal** [comment] 2024-05-01 04:53
Yes, I think we want to hide them please!

**Comment by cristipaval** [comment] 2024-05-01 09:45
yes, thanks!

**Comment by danielrvidal** [comment] 2024-05-02 04:21
Awesome, looks like this should be good to go and on staging tomorrow. Thank you!

**Comment by rushatgabhane** [comment] 2024-05-08 23:23
@cristipaval could you please attach payment summary for this issue 🙇

**Comment by cristipaval** [comment] 2024-05-09 08:44
Payment summary:

@rushatgabhane for the C+ review
@GandalfGwaihir for the fix

Note: I don't think this is a regression as it was not clear in the initial design that we were going to hide these for the invoice rooms

**Comment by cristipaval** [comment] 2024-05-09 08:45
@miljakljajic Could you please help with [this](https://github.com/Expensify/App/issues/41280#issuecomment-2102225554) when it gets due?

**Comment by miljakljajic** [comment] 2024-05-09 12:04
Thank you, I will!

**Comment by cristipaval** [comment] 2024-05-13 11:50
tomorrow is the payment day, Melv

**Comment by miljakljajic** [comment] 2024-05-15 14:04
Issuing these payments!

**Comment by miljakljajic** [comment] 2024-05-15 14:13
@rushatgabhane owed 250 for their work 

@GandalfGwaihir paid in upwork. 

closing!

**Comment by JmillsExpensify** [comment] 2024-05-19 14:13
$250 approved for @rushatgabhane

**Comment by rushatgabhane** [comment] 2024-05-20 15:32
@miljakljajic this should be $500 right? Because critical issue

**Comment by miljakljajic** [comment] 2024-05-21 11:07
Sorry @rushatgabhane 

Updated payment summary:

@rushatgabhane owed 250 for their work

@GandalfGwaihir I will issue a bonus to cover the outstanding amount

**Comment by miljakljajic** [comment] 2024-05-21 11:37
Paid the outstanding 250 USD via an upwork bonus to @GandalfGwaihir

**Comment by rushatgabhane** [comment] 2024-05-25 11:49
@miljakljajic  could you please confirm that im owed 500 for this issue?

**Comment by JmillsExpensify** [comment] 2024-05-26 21:58
Agreed, we still need a payment summary with the $500 amounts.

**Comment by miljakljajic** [comment] 2024-05-27 21:08
@rushatgabhane is owed 500 USD for their work on this issue 

I'm so sorry - I didn't mean to type 250, total mistake on my part

**Closed by miljakljajic** 2024-05-27 21:08 UTC
Labels: External, Engineering, Daily, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-31 03:48
$500 approved for @rushatgabhane
