### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] Scan - No error pop-up and scan expense with corrupted PDF can be submitted via QAB

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43645] opened 2024-06-13 10:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.82-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4622999
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to + > Submit expense > Scan.
4. Upload a corrupted PDF (attached below).
5. Note that it shows error pop-up and the expense is not submitted.
6. Submit a manual request in the workspace chat.
7. Go to FAB > Submit expense under QAB > Scan.
8. Upload the same corrupted PDF.

## Expected Result:
App will show error pop-up and the scan expense is not submitted.

## Actual Result:
There is inconsistency in submitting corrupted PDF via FAB and QAB.
App shows error pop-up and the expense is not submitted when submitting via FAB.
App does not show error pop-up and the scan expense is submitted when submitting via QAB.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ba369c96-6013-4809-8851-a61680c25490

[LARGE PDF FILE corrupted.pdf](https://github.com/user-attachments/files/15817934/LARGE.PDF.FILE.corrupted.pdf)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013830a17b8e9e0b20</li>
        <li>Upwork Job ID: 1801414678071173121</li>
        <li>Last Price Increase: 2024-06-14</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 102912100</li>
<li>Krishna2323 | Contributor | 102912103</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by izarutskaya** [comment] 2024-06-13 10:34
We think this issue might be related to the #collect project.

**Comment by VictoriaExpensify** [comment] 2024-06-14 00:41
Agree this inconsistency should be fixed

**Comment by truph01** [comment] 2024-06-14 08:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is inconsistency in submitting corrupted PDF via FAB and QAB.
App shows error pop-up and the expense is not submitted when submitting via FAB.
App does not show error pop-up and the scan expense is submitted when submitting via QAB.

### What is the root cause of that problem?
- When creating expense by FAB, after uploading the file, we render the file via this logic:
https://github.com/Expensify/App/blob/43cd0f7bbb55b455a57f1996a3a11f66573c58d2/src/components/MoneyRequestConfirmationList.tsx#L1115-L1127
in the confirmation page, so there is an error popup appears in this case.

- But when creating expense by QAB, after uploading file, we skip confirmation page, that leads to there is no way to check whether the file is corrupted pdf file.
### What changes do you think we should make in order to solve the problem?
- We need to validate the corrupted PDF file right after user picks the file, rather than rendering it then need to wait until the onLoadError triggers. To do it, we can create a function ```isCorruptedPdfFile ```:
```
import * as PDFfrom 'pdfjs-dist';

const isCorruptedPdfFile = async (file: FileObject) => {
    try {
        const arrayBuffer = await file.arrayBuffer();
        const loadingTask = PDF.getDocument({data: arrayBuffer});

        const pdf = await loadingTask.promise;
        // If the PDF has at least one page, it is considered valid
        if (pdf.numPages > 0) {
            return false; // PDF is not corrupted
        }
    } catch (error) {
        console.error('Error loading PDF:', error);
    }

    return true; // PDF is corrupted
};
export default isCorruptedPdfFile;

```
then use it in this logic:
https://github.com/Expensify/App/blob/43cd0f7bbb55b455a57f1996a3a11f66573c58d2/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L192
```
if (fileExtension === 'pdf') {
                    return isCorruptedPdfFile(file).then((isCorruptedPdf: boolean) => {
                        if (isCorruptedPdf) {
                            setUploadReceiptError(true, 'attachmentPicker.attachmentError', 'attachmentPicker.errorWhileSelectingCorruptedAttachment');
                            return false;
                        }
                        return true;
                    });
                }
```

- A similar logic should be added in native.
### What alternative solutions did you explore? (Optional)
NA

**Comment by truph01** [comment] 2024-06-14 08:43
@suneox Can you help check my proposal above? TY

**Comment by truph01** [comment] 2024-06-14 09:40
@suneox Thanks for your feedback.

> Can it handle files with passwords and extract error types? Due to scanning receipts also does not support PDF files with passwords.

- I wonder that why do we need to handle password pdf case? I think it is not a scope of this issue

**Comment by truph01** [comment] 2024-06-14 10:13
@suneox I think that the "inconsistency" mentioned in this https://github.com/Expensify/App/issues/43645#issuecomment-2167010794 is about:

> There is inconsistency in submitting corrupted PDF via FAB and QAB.
App shows error pop-up and the expense is not submitted when submitting via FAB.
App does not show error pop-up and the scan expense is submitted when submitting via QAB.

**Comment by grgia** [comment] 2024-06-18 11:16
> I believe the scope of this issue should prevent uploading a PDF file with a password. This is because submit expense also prevents such files. When editing, we should also prevent uploading PDF files with passwords. If we don’t do this, the backend won’t be able to scan PDFs with passwords.

@suneox I agree that we should make all pdf error cases consistent as part of this issue. Does that answer your question?

**Comment by truph01** [comment] 2024-06-18 11:24
@grgia There are two types of pdf files we should not allow user to upload: Protected pdf and corrupt pdf. The @suneox 's question is:

- The scope of this issue only involve handling corrupted pdf or the protected pdf as well?

**Comment by grgia** [comment] 2024-06-18 12:00
@truph01 we should cover both cases

**Comment by truph01** [comment] 2024-06-18 15:39
@suneox I updated the solution to add the implementing in native platform.

**Comment by truph01** [comment] 2024-06-18 15:58
@suneox @grgia What do you think about using [pdf-lib](https://github.com/Hopding/pdf-lib?tab=readme-ov-file#features). Here are a few advantages:
1. Check for corrupt PDFs and handle password-protected PDFs, that will solve our issue.
2. Comprehensive PDF Manipulation: Create, edit, merge PDFs, add text, images, and forms.
3. Client-Side and Server-Side Compatibility: Working in all JavaScript environments - not just in Node or the Browser.

**Comment by truph01** [comment] 2024-06-18 16:37
@suneox 

> I could not find how your proposal extracts an error type

- On web, I create a function ```isCorruptedPdfFile``` to check if the file is corrupted pdf or not. If true, call:
```
setUploadReceiptError(
                    true, 
                    'attachmentPicker.attachmentError', 
                    'attachmentPicker.errorWhileSelectingCorruptedAttachment'
                );
```
that will display the errror popup.

**Comment by truph01** [comment] 2024-06-18 17:09
@suneox Thanks for your feedback. I updated proposal to include the password pdf case.

**Comment by truph01** [comment] 2024-06-18 17:27
[Updated proposal](https://github.com/Expensify/App/issues/43645#issuecomment-2167518816) to remove the platform-specific logic because the lib ```pdf-lib``` can be used in all platform.

**Comment by huult** [comment] 2024-06-18 21:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Validate PDF file before uploading it to the server.

### What is the root cause of that problem?
After select file from [AttachmentPicker](https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L569) the current [action is edit](https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L428) then we [dismiss modal](https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L410), but the validation file show at step [ConfirmationStep](https://github.com/Expensify/App/blob/main/src/components/MoneyRequestConfirmationList.tsx#L1119-1132) 
### What changes do you think we should make in order to solve the problem?
We will handle the validation pdf file and show error message after [validateReceipt](https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L419) file. by adding function `checkPDFState` into `src/libs` with code bellow for browser and native platform

```typescript
// checkPDFState/types.ts

type PDFState = {
  canOpen: boolean;
  error?: Error;
  errorMessage?: 'password' | 'unknown';
}

// checkPDFState/index.ts

import * as pdfjs from 'pdfjs-dist';
import type PDFState from './types';

const checkPDFState = async (source: { url: string }): Promise<PDFState> => {
    try {
        await pdfjs.getDocument(source).promise;
        console.log(`___________ Success ___________`);
        return {canOpen: true};
    } catch (e: unknown) {
        const error = e as Error;
        console.log(`___________ Error ___________`, error);
        if (error?.message?.match(/password/i)) {
            return {canOpen: false, errorMessage: 'password', error};
        }
        return {canOpen: false, errorMessage: 'unknown', error};
    }
}

export default checkPDFState;

// checkPDFState/index.native.ts

import PdfManager from 'react-native-pdf/PdfManager';
import type PDFState from './types';

const checkPDFState = async (source: { url: string }): Promise<PDFState> => {
    const path = unescape(source.url.replace(/file:\/\//i, ''));
    try {
        await PdfManager.loadFile(path);
        console.log(`___________ Success ___________`);
        return { canOpen: true };
    } catch (e: unknown) {
        const error = e as Error;
        console.log(`___________ Error ___________`, error);
        if (error?.message?.match(/password/i)) {
            return { canOpen: false, errorMessage: 'password', error };
        }
        return { canOpen: false, errorMessage: 'unknown', error };
    }
}

```

Then apply the function `checkPDFState` after `validateReceipt`

IOURequestStepScan/index.tsx
```diff
    const setReceiptAndNavigate = (file: FileObject) => {
        validateReceipt(file).then(async (isFileValid) => {
            if (!isFileValid) {
                return;
            }
            // Store the receipt on the transaction object in Onyx
            const source = URL.createObjectURL(file as Blob);
+           const {errorMessage} = await checkPDFState({url: source});
+           if(errorMessage) {
+               if(errorMessage === 'password') {
+                   setUploadReceiptError(true, 'attachmentPicker.attachmentError', 'attachmentPicker.protectedPDFNotSupported');
+                   return;
+               }
+               setUploadReceiptError(true, 'attachmentPicker.attachmentError', 'attachmentPicker.errorWhileSelectingAttachment');
+           }
          ....
```

IOURequestStepScan/index.native.tsx
```diff
    const setReceiptAndNavigate = async (file: FileObject) => {
        if (!validateReceipt(file)) {
            return;
        }

+       const { errorMessage } = await checkPDFState({ url: file?.uri });
+       if (errorMessage) {
+           if (errorMessage === 'password') {
+               Alert.alert(translate('attachmentPicker.attachmentError'), translate('attachmentPicker.protectedPDFNotSupported'));
+               return;
+           }
+           Alert.alert(translate('attachmentPicker.attachmentError'), translate('attachmentPicker.errorWhileSelectingAttachment'));
+       }

```

<details>
<summary>POC</summary>
</details>

### What alternative solutions did you explore? (Optional)

**Comment by huult** [comment] 2024-06-23 14:31
@suneox I don't have plans to make updates for Android native, as the Android native platform does not support exporting functions to load PDF files.

**Comment by grgia** [comment] 2024-06-28 09:58
Thank you @suneox, all yours @Krishna2323 !

**Comment by VictoriaExpensify** [comment] 2024-08-01 21:47
Contributor: @Krishna2323   paid $250 via Upwork

Contributor+: @suneox  paid $250 via Upwork

Upwork job [here](https://www.upwork.com/ab/applicants/1801414678071173121/hired)!

**Comment by VictoriaExpensify** [comment] 2024-08-01 21:48
Thanks for your work @suneox and @Krishna2323! 🙌

**Closed by VictoriaExpensify** 2024-08-01 21:47 UTC
Labels: External, Daily, Awaiting Payment, Bug
