### ISSUE TITLE
 Contact method - mWeb opens when click on unlink link from the email

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37493] opened 2024-02-29 12:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/36850

**Version Number:** 1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Open New Expensify app.
2. Add a new unverified contact method
3. Log out
4. Log in with the unverified contact method
5. Press Unlink
6. Open the unlink link from the email

## Expected Result:
When I open the unlink link from the email I must be redirect to New Expensify app.

## Actual Result:
But when I click on `unlink` link from the email opens in mWeb, not New Expensify app.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a9694b90-8479-42c6-9b94-38d6f96ce2f9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment] 2024-02-29 15:14
@izarutskaya I am going to be honest, I find the **expected result** and **actual result** details very confusing. Can you please clarify those in the original comment, so I can review?

Thanks!

**Comment by CortneyOfstad** [comment] 2024-02-29 20:14
Hi @stephanieelliott! I am heading OoO (back March 11th), so reassigned to keep this moving. At this stage, we're waiting on @izarutskaya to clarify on the **Expected** and **Actual** outcomes since the OG comment wasn't super clear. Thanks!

**Comment by izarutskaya** [comment] 2024-03-01 10:25
Hello @CortneyOfstad ! Sorry for the confusion, I corrected expected, actual results. Thanks

**Comment by bernhardoj** [comment] 2024-03-02 15:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing an unlink login path from an email doesn't redirect user to the installed app.

### What is the root cause of that problem?
The app didn't recognize the unlink login path because we didn't register it to be recognized as a deep link.

### What changes do you think we should make in order to solve the problem?

We should register unlink login path in both [AndroidManifest](https://github.com/Expensify/App/blob/main/android/app/src/main/AndroidManifest.xml#L56-L92) 
```
<data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/u"/>
...
<data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/u"/>
```
and [apple-app-site-association](https://github.com/Expensify/App/blob/main/.well-known/apple-app-site-association).
```
{
    "/": "/u/*",
    "comment": "Unlink login"
},
```

**Comment by stephanieelliott** [comment] 2024-03-05 01:02
I feel this is pretty minor, seeing as it does not affect functionality and does not fit into any of our existing product roadmap waves I am going to close this one

**Closed by stephanieelliott** 2024-03-05 01:02 UTC
Labels: Daily, Overdue, Bug
