### ISSUE TITLE
[$1000] IOU-Offline shows the name of the currency, after going online it shows the symbol of currency

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12573] opened 2022-11-08 22:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Create a money request from User A to user B
3. Go offline
4. Create another money request
5. As user A, go to the IOU details and cancel this IOU request
6. Make sure the request has been cancelled and the IOU preview has been updated (the message should be greyed out)
7. Back online

## Expected Result:
In offline, the currency sign should be displayed immediately

## Actual Result:
Offline shows the name of the currency, after going online it shows the sign of the currency

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.25-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5812702_11720_Web_1](https://user-images.githubusercontent.com/43996225/200688411-a48697f8-58f1-4d55-95da-8318d7f3f268.png)

https://user-images.githubusercontent.com/43996225/200688413-94b68f66-5288-47a2-81ad-eb485dcd0a90.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01b26c2eca8bb1766c
- Upwork Job ID: 1597316650814054400

**Comment by jliexpensify** [comment] 2022-11-08 22:35
@kavimuru I'm actually not seeing this behaviour on my side (I'm also in Staging):

![image](https://user-images.githubusercontent.com/30815269/200690717-8bf0bdf6-15a4-437f-b835-872e916c7f10.png)

Can this be reliably reproduced? Videos would be great. Assigning back to you for further investigation.

**Comment by kavimuru** [comment] 2022-11-08 22:42
@jliexpensify I can repro with CAD and the video already attached in the bug is for the currency UAH

https://user-images.githubusercontent.com/43996225/200691806-8c23a7b0-f9d7-40d4-a2e3-3d3acaec9c22.mp4

**Comment by jliexpensify** [comment] 2022-11-08 23:06
@kavimuru thanks for the video - your reproduction steps were in the wrong order in the original issue so i fixed that.

But I've tested again, multiple times - I still can't reproduce. I'm still getting the same currency symbol for both requests:

![image](https://user-images.githubusercontent.com/30815269/200695203-7918ed81-eba3-4aae-a255-fc0d4cc404a5.png)

**Comment by jasperhuangg** [comment] 2022-11-28 19:48
Hey guys, I can repro! @jliexpensify notice how the symbol changes from `CA$` to `C$` at roughly the 4 second mark on the money request report item in the background:

https://user-images.githubusercontent.com/31285285/204367138-a672ca88-cb75-40d8-8583-c2dbe82830bb.mov

**Comment by jasperhuangg** [comment] 2022-11-28 19:49
Will be looking into this one today myself, but feel free to submit proposals if I haven't submitted a PR yet!

**Comment by jasperhuangg** [comment] 2022-11-28 19:59
Actually, this one might have to be internal, it looks like there's a mismatch between the optimistic report action we're building in the front-end and the one that's returned from `OpenReport`.

**Comment by jliexpensify** [comment] 2022-11-28 22:37
Awesome stuff, thanks @jasperhuangg !

**Comment by jasperhuangg** [comment] 2022-11-28 23:18
Actually after some further investigating it appears that this happens is because the [`Intl` built in library](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) doesn't provide symbols for a number of the currencies we support, so it just returns its currency code instead as a default. In the back-end, we have an actual map of currency code to symbol, which is why we're able to get the symbols.

The currency picker is intended to show the ISO4217 standard currencies, which our back-end already uses.

**Comment by jasperhuangg** [comment] 2022-12-01 20:40
Still pending discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1669822846446869), not overdue!

**Comment by jasperhuangg** [comment] 2022-12-05 15:40
Ionatan and I are more or less on the same page now, just working on ideating a solution

**Comment by jasperhuangg** [comment] 2022-12-05 15:44
PR incoming...

**Comment by jasperhuangg** [comment] 2022-12-08 00:13
Still working on that PR! Hope to have something tested up today!

**Comment by jasperhuangg** [comment] 2022-12-08 07:43
PRs up and ready for review!

**Comment by jasperhuangg** [comment] 2022-12-08 23:41
Realized the testing for https://github.com/Expensify/App/pull/13432 is actually a lot more involved than I had previously assumed so I'm putting the PR back on draft while I iron out the testing steps and screen captures.

**Comment by jasperhuangg** [comment] 2022-12-13 00:44
PRs are both under review, I'm also in @iwiznia 's NewDot DMs to clarify a few things 👀

**Comment by jasperhuangg** [comment] 2022-12-14 10:23
After discussion with @iwiznia we've decided that this actually isn't worth fixing.

Since we store the ReportActions for IOUs as plain strings (rather than storing each of its individual parts like currency code, participants, etc. in an object), we have to parse out the currency code from the report action and replace it with some complicated string manipulation stuff.

I actually already do this in these PRs, but @iwiznia and I have agreed that this is not a good solution, and there aren't any other solutions available either.
https://github.com/Expensify/App/pull/13432
https://github.com/Expensify/Web-Expensify/pull/35777

Since this isn't really breaking anything in the App, we're good to close this out

**Comment by jasperhuangg** [comment] 2022-12-15 06:44
Just a quick update on this one, more great discussion is happening [here in Slack](https://expensify.slack.com/archives/C03TQ48KC/p1671058125624459) about the best approach to solve this issue. We may have to HOLD this on a separate issue that @aldo-expensify is working on, but as for now I'm gonna put the `Planning` label back on.

**Comment by jasperhuangg** [comment] 2022-12-16 03:36
This is solved in Aldo's PR! https://github.com/Expensify/Web-Expensify/pull/35845

**Comment by jasperhuangg** [comment] 2022-12-16 03:39
@aldo-expensify assigning ya so you can also get credit on this!

**Comment by aldo-expensify** [comment] 2022-12-24 02:33
Redoing the PHP API PR: https://github.com/Expensify/Web-Expensify/pull/35908

([Salt PR](https://github.com/Expensify/Salt/pull/11748) was salted adding the missing dependency)

**Comment by aldo-expensify** [comment] 2023-01-04 19:04
No overdue, the https://github.com/Expensify/Web-Expensify/pull/35908 is in staging

**Comment by jasperhuangg** [comment] 2023-01-05 10:32
https://github.com/Expensify/Web-Expensify/pull/35908 is on prod, closing!

**Closed by jasperhuangg** 2023-01-05 10:32 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
