### ISSUE TITLE
[$250] BUG:  Desktop App - Black screen on window close in full-screen mode reported by @fedirjh

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12042] opened 2022-10-20 16:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Desktop App
2. Set full screen mode
3. Click close button

## Expected Result:
Window is hidden

## Actual Result:
Full screen gets black

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/197005671-cd6952ec-748b-4fc9-93bf-a52c7cd22928.mp4

https://user-images.githubusercontent.com/43996225/197005267-69572945-9bcd-4c1e-a7c2-e17ee007d6c5.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** (http://github.com/fedirjh)
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666181224266319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by fedirjh** [comment] 2022-10-20 17:21
this issue happens when we change the default close logic https://github.com/electron/electron/issues/20263
https://github.com/Expensify/App/blob/299f07bfa29c0dd81a6126691aae29e161097baa/desktop/main.js#L262-L269

We have to exit full screen mode then we hide window 

```jsx
browserWindow.on('close', (evt) => { 
    if (quitting || hasUpdate ) { 
        return; 
    } 
 
    evt.preventDefault(); 

    if (browserWindow.isFullScreen()) { 
        browserWindow.once('leave-full-screen', () => browserWindow.hide()) 
        browserWindow.setFullScreen(false) 
    } else { 
        browserWindow.hide() 
    } 
 
});
```

Or we just quit 

```jsx

browserWindow.on('close', (evt) => { 
    if (quitting || hasUpdate || browserWindow.isFullScreen() ) { 
        return; 
    } 
 
    evt.preventDefault(); 
    browserWindow.hide() 
 
});
```

**Comment by CortneyOfstad** [comment] 2022-10-21 11:57
Was able to recreate this on my side and had to completely quit the app in order to get out of the black screen

![2022-10-21_06-56-15 (1)](https://user-images.githubusercontent.com/10926327/197190408-bca24dc8-d772-4ac2-a965-c30deeba99df.gif)

**Comment by PauloGasparSv** [comment] 2022-10-21 16:33
Marking this as External! Found some other fix suggestions on the web other than the one [commented here](https://github.com/Expensify/App/issues/12042#issuecomment-1285900417) so it's not an uncommon issue with electron

**Comment by thesahindia** [comment] 2022-10-24 15:23
I am not sure if we should go with the workaround suggested [here](https://github.com/Expensify/App/issues/12042#issuecomment-1285900417). What's your opinion about it @aldo-expensify ?

**Comment by aldo-expensify** [comment] 2022-10-24 18:01
From a short research I agree with it being a bug on the electron side (https://github.com/electron/electron/issues/20263). I think the workaround proposed is fine while the bug is there.

Besides implementing the solution, we could create a new issue like this one https://github.com/electron/electron/issues/20263, but with the electro version we are using. I understand that the existing issue was closed because it mentions an unmaintained electron version.

I tested the proposed solution and the results is good enough for me:


https://user-images.githubusercontent.com/87341702/197594263-4a6f23cc-72bd-44d3-ba92-2869ec61485c.mov

**Comment by thesahindia** [comment] 2022-10-25 12:06
What are the next steps here?

**Comment by thesahindia** [comment] 2022-10-26 10:06
Cool, let's move forward with @fedirjh's [proposal](https://github.com/Expensify/App/issues/12042#issuecomment-1285900417) (first approach).

C+ reviewed 🎀👀🎀

**Comment by dylanexpensify** [comment] 2022-10-31 09:18
reviewing today!

**Comment by michaelhaxhiu** [comment] 2022-11-03 20:38
@dylanexpensify For this checklist step, I think you can best handle it by posting in #contributor-plus slack channel and using [this type](https://expensify.slack.com/archives/C01SKUP7QR0/p1667507821935299?thread_ts=1667427593.134589&cid=C01SKUP7QR0) of approach (since this checklist is actively evolving):


>Hey @a, @b, @c, @d - this PR (link) caused this bug (link). What do you think we could have done differently in the original PR to prevent this bug from being introduced?

**Comment by dylanexpensify** [comment] 2022-11-04 11:45
ah nice one!

**Comment by dylanexpensify** [comment] 2022-11-04 13:40
@thesahindia and @fedirjh any idea on the offending PR that led to this bug?

**Comment by thesahindia** [comment] 2022-11-04 13:46
@dylanexpensify, as mentioned at https://github.com/Expensify/App/issues/12042#issuecomment-1285900417, It is an electron bug. Not a regression.

**Comment by dylanexpensify** [comment] 2022-11-07 08:22
reviewing today!

**Comment by dylanexpensify** [comment] 2022-11-07 11:32
@fedirjh can you let us know when your PR will be ready for review?

**Comment by thesahindia** [comment] 2022-11-07 11:37
It's already in production.

**Comment by fedirjh** [comment] 2022-11-07 11:48
> @fedirjh can you let us know when your PR will be ready for review?

https://github.com/Expensify/App/pull/12368 : Deployed to production

**Comment by dylanexpensify** [comment] 2022-11-10 10:19
Working through steps on checklist

**Comment by dylanexpensify** [comment] 2022-11-14 08:06
reviewing today!

**Comment by thesahindia** [comment] 2022-11-15 17:48
@dylanexpensify, it's ready to be settled. The PR was deployed to production 11 days ago

**Comment by dylanexpensify** [comment] 2022-11-17 09:55
Will get this paid out today! Sorry for delay all!

**Comment by dylanexpensify** [comment] 2022-11-17 09:57
Upwork https://www.upwork.com/jobs/~01b45454c6b590f926! @fedirjh @thesahindia

**Comment by thesahindia** [comment] 2022-11-17 10:03
Applied 🚀

**Comment by dylanexpensify** [comment] 2022-11-17 10:08
Offer sent!

**Comment by thesahindia** [comment] 2022-11-17 10:10
Accepted, thanks!

**Comment by thesahindia** [comment] 2022-11-17 10:12
> @dylanexpensify can I work on this issue?

It's already fixed. Feel free to check other open [issues](https://github.com/Expensify/App/issues?q=is%3Aissue+is%3Aopen+label%3A%22Help+Wanted%22).

**Comment by fedirjh** [comment] 2022-11-17 10:17
@dylanexpensify applied!

**Comment by dylanexpensify** [comment] 2022-11-17 12:28
offer sent @fedirjh!

**Comment by fedirjh** [comment] 2022-11-17 12:32
Accepted.  Thank you @dylanexpensify

**Comment by dylanexpensify** [comment] 2022-11-17 12:38
payments sent, contracts ended, posting removed! Appreciate you all!

**Closed by dylanexpensify** 2022-11-17 12:38 UTC
Labels: External, Engineering, Daily, Bug

**Comment by thesahindia** [comment] 2022-12-01 14:41
Hey @dylanexpensify, I was looking into open contracts and found that the contract for this issue is still open and I didn't receive the compensation ( not sure if there was another job since I couldn't find it by the issue number ). Can you please look into it. Thanks!
<img width="1103" alt="Screenshot 2022-12-01 at 8 07 41 PM" src="https://user-images.githubusercontent.com/83179295/205081177-295c509b-8aaa-4975-96c8-859776f45799.png">

(job link https://github.com/Expensify/App/issues/12042#issuecomment-1318377830)

**Comment by dylanexpensify** [comment] 2022-12-01 15:36
looking now @thesahindia !

**Comment by dylanexpensify** [comment] 2022-12-01 15:38
Wow, no idea how I missed this, but just sent payment @thesahindia !! sorry about that!

**Comment by thesahindia** [comment] 2022-12-01 15:41
Thanks for looking into it.
