### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Web - Navigation - Chat finder has weird animation when closing up

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#42282] opened 2024-05-16 12:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/40342
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open workspace switcher LHP
3. Press on ctrl + K/Cmd + K to open chat finder
4. Click on the back button of the chat finder at the top left

## Expected Result:
Chat finder closes by sliding to the left side of the screen and the app doesn't navigate to the workspace switcher LHP

## Actual Result:
Chat finder slides to the right and the disappears revealing the workspace switcher LHP

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b02c6d59-1332-4103-a948-6060ba555d18

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018db96bec95e66f96</li>
        <li>Upwork Job ID: 1791352526254919680</li>
        <li>Last Price Increase: 2024-05-17</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 102433234</li>
<li>bernhardoj | Contributor | 102433236</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by kbecciv** [comment] 2024-05-16 12:22
@Christinadobrzyn FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment] 2024-05-16 12:22
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-05-16 16:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The slide animation when opening/closing chat finder after open it from the workspace switcher page is weird.

### What is the root cause of that problem?
The direction for the screen is set to horizontal and it will slide from right to left.

https://github.com/Expensify/App/blob/f16005f751cf4b3481036cf326050fac88ccddc7/src/libs/Navigation/AppNavigator/ModalNavigatorScreenOptions.ts#L13
https://github.com/Expensify/App/blob/5900fea34578ddc5d5a684de5b4cb97af9deec2e/src/libs/Navigation/AppNavigator/Navigators/LeftModalNavigator.tsx#L24
https://github.com/Expensify/App/blob/5900fea34578ddc5d5a684de5b4cb97af9deec2e/src/libs/Navigation/AppNavigator/Navigators/LeftModalNavigator.tsx#L35

But for the chat finder and workspace switcher, we want it to slide from left to right. For the left modal navigator itself, we already set the correct direction for it, that is, horizontal-inverted.
https://github.com/Expensify/App/blob/5900fea34578ddc5d5a684de5b4cb97af9deec2e/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L361-L363
https://github.com/Expensify/App/blob/5900fea34578ddc5d5a684de5b4cb97af9deec2e/src/libs/Navigation/AppNavigator/getRootNavigatorScreenOptions.ts#L68-L72

That's why opening the page for the first time shows the correct animation.

### What changes do you think we should make in order to solve the problem?

For left modal navigator screen, set the `gestureDetection` to `horizontal-inverted` too.

We can do that for example by updating `ModalNavigatorScreenOptions` to accept another param for the gesture direction that defaults to `horizontal`

**Comment by Christinadobrzyn** [comment] 2024-05-17 06:18
Ah interesting - I think this can be external.

**Comment by Christinadobrzyn** [comment] 2024-05-20 03:42
@ishpaul777 can you review the proposal when you have a moment?

**Comment by mountiny** [comment] 2024-05-20 17:56
cc @adamgrzybowski @WojtekBoman for review of the proposal too

**Comment by adamgrzybowski** [comment] 2024-05-23 08:07
@ishpaul777 I confirmed with @WojtekBoman and it looks legit to us as well

**Comment by bernhardoj** [comment] 2024-05-23 11:49
PR is ready

cc: @ishpaul777

**Comment by Christinadobrzyn** [comment] 2024-05-28 06:11
update: monitoring the PR- https://github.com/Expensify/App/pull/42517

**Comment by Christinadobrzyn** [comment] 2024-06-05 07:38
Update: monitoring the PR- https://github.com/Expensify/App/pull/42517

**Comment by Christinadobrzyn** [comment] 2024-06-12 08:50
Just a heads up - I'm going to be ooo until June 24th so going to assign a teammate to watch this while I'm away

Waiting on payments. I think this is the correct summary but let me know if I'm wrong. 

- [ ] Contributor: $250 @bernhardoj (in Upwork - https://www.upwork.com/nx/wm/workroom/37351006/details)
- [ ] Contributor+: $250 @ishpaul777 (in Upwork - https://www.upwork.com/nx/wm/offer/102433234) 

Upwork job is [here](https://www.upwork.com/jobs/~018db96bec95e66f96).

**Comment by Christinadobrzyn** [comment] 2024-06-13 02:53
@ishpaul777 do we need a regression test?

**Comment by JmillsExpensify** [comment] 2024-06-19 04:43
Contributors paid out and regression test created. Closing.

**Closed by JmillsExpensify** 2024-06-19 04:43 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
