### ISSUE TITLE
[HOLD for payment 2023-10-30] [HOLD for payment 2023-09-29] [$500] Dev: Web - My note not translated in Spanish

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27592] opened 2023-09-16 18:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Preferences >Language
2. Change Language to Spanish
3. Create workspace if not created
4. Go to #admins
5. Click on header
6. Go to Private notes

## Expected Result:
My note should be translated in Spanish

## Actual Result:
My note not translated in Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/90f18795-c638-4a0f-aebd-904d79d4b485

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694784868918699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a01358f997cc9909</li>
        <li>Upwork Job ID: 1703115340291780608</li>
        <li>Last Price Increase: 2023-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 26746126</li>
<li>gadhiyamanan | Reporter | 26746127</li>
</ul></li>
    </ul>
</details>

**Comment by tgolen** [comment] 2023-10-02 15:00
@alexpensify Can you issue payment for this, please?

**Comment by alexpensify** [comment] 2023-10-02 16:50
@allroundexperts please complete the checklist and request the payment. 

Right now, everyone who is paid in Upwork has been paid there and I closed the job.

**Comment by alexpensify** [comment] 2023-10-04 16:44
Closing - the regression test request has been created. I'm going to close this GH.

**Comment by isagoico** [comment] 2023-10-18 18:17
Reopening this issue because the current translation in app is not correct. It's showing "Mi notas" which is incorrect in Spanish. 
![image](https://github.com/Expensify/App/assets/44479856/db039724-a3a1-46aa-8819-f0f1e1176215)

It should either be: 
1. For plural: My notes = Mis notas 
2. For singular: My note = Mi nota

**Comment by tgolen** [comment] 2023-10-19 13:59
Thank you for spotting this, Isa! @namhihi237 Can you please fix that?

I looked and I can't find a record of either me nor @allroundexperts checking to make sure that was an official translation. That's something we can learn from and do better at next time.

**Comment by alexpensify** [comment] 2023-10-30 23:09
@allroundexperts and @gadhiyamanan - I'm considering closing with no payment updates. This is not a regression but was a quick fix. Everyone has already paid out already with bonuses in September. Let me know if you disagree. 

cc: @tgolen

**Comment by alexpensify** [comment] 2023-11-01 00:25
Thanks! Closing for now.

**Closed by alexpensify** 2023-11-01 00:25 UTC
Labels: External, Weekly, Awaiting Payment
