### ISSUE TITLE
[$250] Saerch - Track scan expense has "Other" in Category field in Search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45777] opened 2024-07-19 13:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User has at least one workspace that has enabled Categories (so that Category field appears in Search)
1. Go to staging.new.expensify.com
2. Go to self DM
3. Click + > Track expense > Scan
4. Upload a valid receipt
5. Wait for scanning to complete
6. After the scanning is complete, go to transaction thread
7. Note that there is no Category
8. Go to Search
9. Look for the scanned expense in Step 6

## Expected Result:
The category field for the tracked scan expense will be empty in Search

## Actual Result:
The category field for the tracked scan expense is displayed as "Others" in Search

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c8b3659f-d3ff-44ab-844e-784069621c16

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014614834d2399311d</li>
        <li>Upwork Job ID: 1814376610247901572</li>
        <li>Last Price Increase: 2024-07-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by lanitochka17** [comment] 2024-07-19 13:32
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-19 13:33
We think that this bug might be related to #vip-vsp

**Comment by NJ-2020** [comment] 2024-07-20 07:37
The issue is not reproducible

**Comment by s77rt** [comment] 2024-07-21 11:58
Not reproducible from my end either

**Comment by slafortune** [comment] 2024-07-22 14:10
Thanks everyone!  Closing 👍

**Closed by slafortune** 2024-07-22 14:10 UTC
Labels: External, Daily, Help Wanted, Bug
