### ISSUE TITLE
[$500] [LOW] - Expense - Search results are categorised as Recent and All in report field

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36683] opened 2024-02-16 12:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace
- The Collect workspace has dropdown field set up in "Report and Invoice Fields" on Old Dot.

1. Go to workspace chat.
2. Create a request.
3. Go to expense report.
4. Click on the report field with the selection list set up from Old Dot
5. Select an item.
6. Click on the report field again.
7. Search for term that will return results in Recent and All sections.
8 .Repeat the search with category list.

## Expected Result:
In Step 7, the results will not be categorised. Recent and All sections will not appear in the search results (behavior with category search in Step 8).

## Actual Result:
In Step 7, the results are categorised as Recent and All sections.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e7b86a0d-2f2d-4562-b39d-021c8a9dcda7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140d83f72c166b2c5</li>
        <li>Upwork Job ID: 1762288217547255808</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-16 12:22
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors



We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by bfitzexpensify** [comment] 2024-02-19 06:38
This seems expected to me - the report field and categories are two different elements of the report/expense, so it wouldn't make sense to show recent report field items when searching for the category. Going to close this one out.

**Comment by kbecciv** [comment] 2024-02-19 22:07
@bfitzexpensify My apologies for any confusion. We're currently showing the difference in behavior when searching for items in the report field vs the category. Reopening the issue for second chance to review.
Thanks

**Comment by bfitzexpensify** [comment] 2024-02-20 05:38
Thanks for the clarification @kbecciv!

@izarutskaya in your test set-up, are there categories that match the search term "a"? At 0:19, the same `Recent` / `All` itemisation is seen, and it only goes away when searching. For the Report Field search, there are a number of matching results, that are then categorised into `Recent` / `All` as expected.

**Comment by bfitzexpensify** [comment] 2024-02-23 05:18
discussing in this Slack [thread](https://expensify.slack.com/archives/C9YU7BX5M/p1708495331977769)

**Comment by bfitzexpensify** [comment] 2024-02-27 01:26
OK, adding this to #wave06 and prioritising as low for the moment

**Comment by hungvu193** [comment] 2024-02-27 02:37
waiting for proposals

**Comment by bernhardoj** [comment] 2024-02-27 13:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The report field is still categorized when searching.

### What is the root cause of that problem?
Currently, we always return the report field as categorized in all cases.
https://github.com/Expensify/App/blob/cfa0ae37156208ebecdc6b2126464ec462271b76/src/pages/EditReportFieldDropdownPage.tsx#L48-L73

### What changes do you think we should make in order to solve the problem?

Check if there is a `searchValue`, filter all field items, and return it in one section only without a title. Otherwise, return it as categorized as below:

```
if (searchValue) {
    const filteredOptions = fieldOptions.filter((option) => option.toLowerCase().includes(searchValue.toLowerCase()));
    setHeaderMessage(!filteredOptions.length ? translate('common.noResultsFound') : '');
    return [{
        title: '',
        shouldShow: filteredOptions.length > 0,
        data: filteredOptions.map((option) => ({...})),
    }]
}

const restOfOptions = fieldOptions.filter((option) => !recentlyUsedOptions.includes(option));
setHeaderMessage(!restOfOptions.length && !recentlyUsedOptions.length ? translate('common.noResultsFound') : '');
return [
    {
        title: translate('common.recents'),
        shouldShow: recentlyUsedOptions.length > 0,
        data: recentlyUsedOptions.map((option) => ({...})),
    },
    {
        title: translate('common.all'),
        shouldShow: restOfOptions.length > 0,
        data: restOfOptions.map((option) => ({...})),
    },
];
```

**Comment by hungvu193** [comment] 2024-02-28 03:04
@bernhardoj 's proposal looks good to me.
🎀👀🎀 C+ reviewed

**Comment by hungvu193** [comment] 2024-02-29 02:36
little bump @MonilBhavsar for final review 👀

**Comment by MonilBhavsar** [comment] 2024-02-29 16:49
Looks good to me too! 👍

**Comment by bernhardoj** [comment] 2024-03-01 05:37
PR is ready

cc: @hungvu193

**Comment by hungvu193** [comment] 2024-04-08 07:22
I think payment is due for this issue @bfitzexpensify

**Comment by bfitzexpensify** [comment] 2024-04-08 21:17
Thanks for the bump @hungvu193! Seems the automation didn't work. All paid out.

**Closed by bfitzexpensify** 2024-04-08 21:17 UTC
Labels: Reviewing, External, Monthly, Bug
