### ISSUE TITLE
Dev: Web - Composer is focused when reloading after workspace is opened from RHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26186] opened 2023-08-29 11:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Settings > Workspaces
3. Reload the website
4. Observe the composer

## Expected Result:
Composer shouldn't be focused

## Actual Result:
Composer is focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.58.0
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0c86e9ac-eb2c-42f5-b08e-3b8a90e5893e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693280983559619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jscardona12** [comment] 2023-08-29 15:25
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Web - Composer is focused when reloading after workspace is opened from RHN
### What is the root cause of that problem?
Te root cause is that in this [line](https://github.com/Expensify/App/blob/17025aa62b1a8c40bb451a97000d3f4605c7bdae/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L113) modal object sometimes is empty and makes `shouldAutoFocus = true` for short time 

### What changes do you think we should make in order to solve the problem?
we should add `modal.hasOwnProperty('isVisible')`to the `shouldAutoFocus` condition in order to verify thart the object is comming correctly. 

### Solution Working

https://github.com/Expensify/App/assets/16781411/4b504e23-9a8d-410b-9472-bdc83984fac2



### What alternative solutions did you explore? (Optional)
N/A

**Comment by sophiepintoraetz** [comment] 2023-08-31 04:56
@MonilBhavsar - are you able to reproduce this for me given it's on DEV? 🙏

**Comment by jscardona12** [comment] 2023-08-31 13:50
@sophiepintoraetz - i was able to reproduce when i send the proposal but now i'm not able to reproduce it in DEV.

**Comment by MonilBhavsar** [comment] 2023-08-31 20:28
I'm not able to reproduce too. Looks like it is fixed now and we can close this

https://github.com/Expensify/App/assets/32012005/0de1e7a6-284e-405d-8cf4-4b89b2600d00

**Closed** 2023-08-31 20:28 UTC
Labels: Engineering, Daily, Needs Reproduction, Bug
