### ISSUE TITLE
[HOLD for payment 2024-06-06] [$500] iOS - Chat - Unable to select emoji if searching for specific one

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42119] opened 2024-05-13 23:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:**Applause - Internal Team

## Action Performed:
1. Open the app and log in
2. Open any report
3. Tap the emoji picker
4. Enter a search word that would return only one result and not in recently used, e.g. panda, fox, pizza etc
5. Select the emoji

## Expected Result:
User is able to select the emoji, the emoji is displayed in compose

## Actual Result:
User is unable to select the emoji, nothing happens after tapping the emoji

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b99751e9-d219-4737-a091-7a35b029ece0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ff89e96c3fe3cbbb</li>
        <li>Upwork Job ID: 1790382115707867136</li>
        <li>Last Price Increase: 2024-06-07</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
<li>QichenZhu | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment] 2024-05-13 23:27
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-13 23:27
We think that this bug might be related to #vip-vsp

**Comment by garrettmknight** [comment] 2024-05-14 14:02
Reproduced, opening up.

**Comment by QichenZhu** [comment] 2024-05-15 17:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to select the only emoji in the emoji picker.

### What is the root cause of that problem?
The `FlashList`'s footer overlaps the emoji because the `footerDiff` method counts subviews incorrectly. 

https://github.com/Expensify/App/blob/153021e1fe894710c6fd64c96889a0c10dae5e14/patches/%40shopify%2Bflash-list%2B1.6.3.patch#L1012-L1015

Specifically, when there is only one emoji, it counts as 2. The reason is explained in the `fixLayout` method:

https://github.com/Expensify/App/blob/153021e1fe894710c6fd64c96889a0c10dae5e14/patches/%40shopify%2Bflash-list%2B1.6.3.patch#L968-L971

To confirm, you can add a visible footer to the [`FlashList`](https://github.com/Expensify/App/blob/153021e1fe894710c6fd64c96889a0c10dae5e14/src/components/EmojiPicker/EmojiPickerMenu/BaseEmojiPickerMenu.tsx#L103-L127), and you will find the footer misplaced.


```JSX
<FlashList
    ...
    ListFooterComponent={<Text>Footer</Text>}
    ListFooterComponentStyle={{backgroundColor: '#ff00ff20'}}
    ...
```

![Simulator Screenshot - iPhone 15 - 2024-05-16 at 05 11 31](https://github.com/Expensify/App/assets/57348009/d1e5628e-d99c-483b-8f61-7ab523a026bd)

### What changes do you think we should make in order to solve the problem?
Patching the `footerDiff` method to count subviews in the same way as the `fixLayout` method.

### What alternative solutions did you explore? (Optional)
Workaround: Adding `ListFooterComponentStyle={{display: 'none'}}` to the [`FlashList`](https://github.com/Expensify/App/blob/153021e1fe894710c6fd64c96889a0c10dae5e14/src/components/EmojiPicker/EmojiPickerMenu/BaseEmojiPickerMenu.tsx#L103-L127).

**Comment by hungvu193** [comment] 2024-05-16 02:02
Thanks @QichenZhu, your proposal makes sense to me, can you please provide more detail about the solution so I can test it?
AFAIK, we apply that patch to enable new arch, do you think with your change it still works?

**Comment by QichenZhu** [comment] 2024-05-16 14:19
Thanks @hungvu193. For testing, I modified the local file `node_modules/@shopify/flash-list/ios/Sources/AutoLayoutView.swift` as below, in addition to the current patch.

```Diff
@@ -134,6 +134,10 @@
         var maxBoundNextCell: CGFloat = 0
         let correctedScrollOffset = scrollOffset - (horizontal ? frame.minX : frame.minY)
         lastMaxBoundOverall = 0
+        if cellContainers.count == 1 {
+            let firstCellContainer = cellContainers[0]
+            lastMaxBoundOverall = horizontal ? firstCellContainer.frame.maxX : firstCellContainer.frame.maxY
+        }
         cellContainers.indices.dropLast().forEach { index in
             let cellContainer = cellContainers[index]
             let cellTop = cellContainer.frame.minY
@@ -282,12 +286,6 @@
     }
 
     private func footerDiff() -> CGFloat {
-        if viewsToLayout.count == 0 {
-            lastMaxBoundOverall = 0
-        } else if viewsToLayout.count == 1 {
-            let firstChild = viewsToLayout[0]
-            lastMaxBoundOverall = horizontal ? firstChild.frame.maxX : firstChild.frame.maxY
-        }
         let autoLayoutEnd = horizontal ? frame.width : frame.height
         return lastMaxBoundOverall - autoLayoutEnd
     }
```

Regarding your second question, I believe so because those modifications are made to the patched local file and then I'll update the patch to persist those changes.

**Comment by hungvu193** [comment] 2024-05-17 02:36
Thanks for your updates here. Let me test it carefully since it will affect lot of things.

**Comment by hungvu193** [comment] 2024-05-17 11:03
It's working well! Can you update your proposal to explain your change [here](https://github.com/Expensify/App/issues/42119#issuecomment-2115378917)? Thank you 😄 

https://github.com/Expensify/App/assets/16502320/9ed1a10c-5f84-4c23-9e9a-ca689b96e056

**Comment by QichenZhu** [comment] 2024-05-17 11:15
@hungvu193 Thank you for your time!

**Comment by QichenZhu** [comment] 2024-05-17 11:15
## Proposal
[Updated](https://github.com/Expensify/App/issues/42119#issuecomment-2113065513)

**Comment by hungvu193** [comment] 2024-05-17 11:17
@QichenZhu 's [proposal here](https://github.com/Expensify/App/issues/42119#issuecomment-2113065513) looks good to me! 🎀 👀 🎀  C+ reviewed

**Comment by neil-marcellini** [comment] 2024-05-20 19:40
> @QichenZhu 's [proposal here](https://github.com/Expensify/App/issues/42119#issuecomment-2113065513) looks good to me! 🎀 👀 🎀 C+ reviewed

Ok, looks good to me. What's the process to get the fix merged into the actual repo eventually?

**Comment by hungvu193** [comment] 2024-05-21 01:51
> > @QichenZhu 's [proposal here](https://github.com/Expensify/App/issues/42119#issuecomment-2113065513) looks good to me! 🎀 👀 🎀 C+ reviewed
> 
> Ok, looks good to me. What's the process to get the fix merged into the actual repo eventually?

I think @QichenZhu will need to raise an issue in the upstream repo, meanwhile since we're already using patch, we can raise a PR here to apply the fix from @QichenZhu's proposal.

**Comment by QichenZhu** [comment] 2024-06-05 08:38
As [announced](https://expensify.slack.com/archives/C01GTK53T8Q/p1712256409152489) in Slack, could the bounty be increased since the priority is high? Thank you!

**Comment by hungvu193** [comment] 2024-06-05 11:08
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/13767
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/13767/files#r1627535636
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression test**:
1. Open the app and log in.
2. Open any report.
3. Tap the emoji picker.
4. Enter a search word that would return only one result and not in recently used, e.g. panda, fox, pizza etc
5. Select the emoji.
6. Verify that emoji is selected.

Do we 👍 or 👎 ?

**Comment by hungvu193** [comment] 2024-06-05 14:26
> As [announced](https://expensify.slack.com/archives/C01GTK53T8Q/p1712256409152489) in Slack, could the bounty be increased since the priority is high? Thank you!

I think this is complex issue and I was about to request a raise the bounty right before you posted your proposal.

**Comment by garrettmknight** [comment] 2024-06-06 16:03
>There have been questions about what constitutes a job being auto-increased to $500. These jobs are only the ones that have the High Priority label added to them (ie. issue with HIGH or CRITICAL in the title or project status/priority are not auto-increased to $500).
To be clear, this wouldn't be a high priority issue as described in the slack post.

**Comment by garrettmknight** [comment] 2024-06-06 16:05
@hungvu193 can you help me understand what about this issue was particularly complex? I'm not doubting you, just trying to understand.

**Comment by garrettmknight** [comment] 2024-06-06 16:22
> In fact, this issue has been opened for the last 3 weeks with no proposals until @QichenZhu posted his proposal.
I don't think this is the case - it looks like he put his proposal forward 1 day after I opened this up for proposals. It did take a few weeks to get through, but I don't think that's indicative of complexity with the merge freeze in mind.

**Comment by hungvu193** [comment] 2024-06-06 16:38
Actually when an issue was created, contributors will post the proposals even when `Help Wanted` label isn't added. 
But yeah, I agreed with you at this point 😄 
>  it looks like he put his proposal forward 1 day after I opened this up for proposals

**Comment by mallenexpensify** [comment] 2024-06-06 19:06
> As [announced](https://expensify.slack.com/archives/C01GTK53T8Q/p1712256409152489) in Slack, could the bounty be increased since the priority is high? Thank you!

@QichenZhu (and @hungvu193 ), unfortunately no, I [commented on the link](https://expensify.slack.com/archives/C01GTK53T8Q/p1717451725980889?thread_ts=1712256409.152489&cid=C01GTK53T8Q) above earlier this week with
> There have been questions about what constitutes a job being auto-increased to $500. These jobs are only the ones that have the High Priority label added to them (ie. issue with HIGH or CRITICAL in the title or project status/priority are not auto-increased to $500).

If you believe the price should be increased because of added scope of the job, ie. `I think @QichenZhu will need to raise an issue in the upstream repo`, please comment with detailed reasoning about the added scope and the requested increase in price (either @QichenZhu or @hungvu193 can do this)

**Comment by QichenZhu** [comment] 2024-06-07 02:39
@mallenexpensify @garrettmknight Thank you for clarifying the differences between title/label/status. I understand that the priority is decided solely on your end.

Regarding the scope of work, @hungvu193 thoroughly tested my proposal as it modified a basic component and might affect a lot of things. He also explored the upstream repo and [identified a related upstream PR](https://github.com/Expensify/App/pull/42407#issuecomment-2122367442).

**Comment by garrettmknight** [comment] 2024-06-07 15:47
Hey @QichenZhu @hungvu193 - thanks for the detail. After reviewing, I'd agree this deserves an increased bounty!

**Comment by garrettmknight** [comment] 2024-06-07 16:07
**Payment Summary:**
- Contributor: @QichenZhu $500 paid via upwork
- Reviewer: @hungvu193 $500 paid via upwork

**Closed** 2024-06-07 16:08 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by QichenZhu** [comment] 2024-06-08 10:39
Received. Thank you for the bonus!
