### ISSUE TITLE
[HOLD for payment 2022-08-30] [$250]  Android - Deep Links not working on Android 12+@tomivs

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9628] opened 2022-06-29 17:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to NewDot on the app.
2. From an email or external source, click on the link https://new.expensify.com/statements/202202/
3. Verify that the link is opened in the native app, and not the web browser.

## Expected Result:
Links should open in Expensify App in Android 12

## Actual Result:
Links not working on Android 12+

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.79.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/176494918-30aef4f3-e59b-4629-8876-5281f44b53ad.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @tomivs

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650935563541709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment] 2022-06-29 23:14
The deep links are working fine for me on Android 11, but according to the slack convo and doing a [quick search](https://doordash.engineering/2022/01/25/your-deep-links-might-be-broken-web-intents-and-android-12/) on Google seems the deep links (App Links on Android) are indeed broken for Android 12. 

Seems the solution can be implemented by an external contributor.

**Comment by rushatgabhane** [comment] 2022-06-29 23:34
@tomivs I remember you having a proposal for this issue, please submit one if you're interested

**Comment by arielgreen** [comment] 2022-06-30 17:21
https://www.upwork.com/jobs/~018ff7d1127f315de9

**Comment by asif84468** [comment] 2022-07-01 03:38
Maybe this will help you : https://doordash.engineering/2022/01/25/your-deep-links-might-be-broken-web-intents-and-android-12/

**Comment by tomivs** [comment] 2022-07-01 03:45
Thanks guys. I'll post a proposal soon...

**Comment by mim1192** [comment] 2022-07-01 05:08
XML FOLDER PERMISSION REQUIRED ONLY TO RESOLVE IT

**Comment by parasharrajat** [comment] 2022-07-01 17:59
@asif84468 @tomivs @mim1192 Please submit your proposals if you are interested to solve this issue.

**Comment by tomivs** [comment] 2022-07-04 04:12
As I mentioned in this comment: https://github.com/Expensify/App/pull/8656#issuecomment-1102486931

### Root cause:
[Changes for App Links on Android 12](https://developer.android.com/about/versions/12/behavior-changes-12#android-app-links-verification-changes)

### Proposal:
Update App Links for Android 12 which would include:
- Upgrading target SDK version:
  - Update `targetSdkVersion` to 31 (Android 12) in `build.gradle`.
  - Update some old _npm packages_ to versions that support Android 12.
- Update `AndroidManifest.xml` following Android 12 guidelines.

**Comment by parasharrajat** [comment] 2022-07-04 10:38
Thanks for the proposal @tomivs. 

- I don't think upgrade to SDK 31 is required. Is this a required step? Will you make sure that app is working absolutely fine after change and nothing is broken?

>  Update AndroidManifest.xml following Android 12 guidelines. 

What changes will you make overall? Can we configure the links in a way so that user is prompted for choices to open the link instead of directly opening the app?

**Comment by tomivs** [comment] 2022-07-12 23:01
> Thanks for the proposal @tomivs.
> 
>     * I don't think upgrade to SDK 31 is required. Is this a required step? Will you make sure that app is working absolutely fine after change and nothing is broken?
> 
I think It is necessary, otherwise it won't build the App Links for Android 12 (which is happening right now). I will make sure that everything is working after that. I tested and and it doesn't work by only updating the `AndroidManifest.ml`. That's why I said we should upgrade to SDK 31.
> 
> What changes will you make overall? Can we configure the links in a way so that user is prompted for choices to open the link instead of directly opening the app?

Mainly declaring `android:exported` for the activities in the `AndroidManifest.xml`.

I don't think so, at least not for Android 12. Android 12 got rid of the "open with" dialog. So it would directly open the app.

https://developer.android.com/about/versions/12/behavior-changes-12#exported

**Comment by parasharrajat** [comment] 2022-07-13 00:20
Ok. Thanks for the explanation. Need to discuss something internally...

**Comment by jeet-dhandha** [comment] 2022-07-16 02:31
### Proposal 

@parasharrajat according to google's official documentation, here
https://developer.android.com/training/app-links/verify-site-associations

We need to add:
1. `assetlinks.json` to `.well-know` folder, which is at our app's root folder.
```
[{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "com.expensify.chat",
    "sha256_cert_fingerprints":
    ["<Your App’s SHA256 finger print>"]
  }
}]
```
<img width="1440" alt="Screenshot 2022-07-16 at 7 49 31 AM" src="https://user-images.githubusercontent.com/78416198/179335506-f2ac8710-d99a-4480-93d4-d21e65c0fe82.png">

2. Add `autoVerify="true"` to `<intent-filter>` in our `AndroidManifest.xml`. Add this for URL Handler's only as shown in screenshot.

`<intent-filter android:autoVerify="true">`

<img width="1141" alt="Screenshot 2022-07-16 at 7 49 21 AM" src="https://user-images.githubusercontent.com/78416198/179335563-a080ea96-f125-4101-9b00-b303515bfcd5.png">

For Reference: https://doordash.engineering/2022/01/25/your-deep-links-might-be-broken-web-intents-and-android-12/

I will verify this by using localhost and will update here soon.

Thanks, 
Jeet Dhandha.

**Comment by parasharrajat** [comment] 2022-07-18 03:36
What about upgrading the targetSdkVersion to 31 @jeet-dhandha?

**Comment by jeet-dhandha** [comment] 2022-07-18 07:01
@jeet-dhandha We should update that too.

**Comment by parasharrajat** [comment] 2022-07-18 21:51
@jeet-dhandha Ok. My question was Is that a required step?

**Comment by tomivs** [comment] 2022-07-19 00:18
> What is your test plan? How will you test that it worked?

We would simply test that Deep Links work for Android 12 after changing the necessary files. This can be tested locally.

Now, if you're talking about regression testing after upgrading `targetSdkVersion` to 31: only a few npm packages would need to be updated. Testing the features related to those packages should be enough.

We could also create another issue/pull request for updating `targetSdkVersion` to 31 and fix Deep Links for Android 12 afterwards. This in order to test and make sure that everything works as expected.

cc: @parasharrajat

**Comment by parasharrajat** [comment] 2022-07-19 15:19
Ok. Thanks for the explanation @tomivs. 

Although both of the proposals lack clear instructions for all the changes, let's go with @tomivs's proposal as they reported this issue and proposed it first. I agree that many of the things can't be listed before doing them.

Thanks for the proposal @jeet-dhandha. Technically there is no issue in your proposal but let's @tomivs handle this one.  

cc: @deetergp 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by deetergp** [comment] 2022-07-21 00:43
@arielgreen I agree with @parasharrajat, let's go with @tomivs's proposal 👍

**Comment by tomivs** [comment] 2022-07-21 22:17
Awesome guys. So what's next? Should I create the PR and start working on it?

cc: @deetergp @parasharrajat

**Comment by parasharrajat** [comment] 2022-07-21 22:24
Yup, you can or you can wait to be hired on Upwork first. But eventually you will be hired.

**Comment by arielgreen** [comment] 2022-07-25 17:04
@tomivs I do not see an application from you on the Upwork posting. Please apply so I can hire you.

**Comment by tomivs** [comment] 2022-07-25 17:19
@arielgreen Just applied!

**Comment by arielgreen** [comment] 2022-07-25 17:29
Hired!

**Comment by tomivs** [comment] 2022-07-27 03:24
Just opened the PR. Waiting for your reviews and testing.

**Comment by deetergp** [comment] 2022-08-04 18:35
Not overdue. PR is in review.

**Comment by arielgreen** [comment] 2022-08-11 22:45
Still in review

**Comment by deetergp** [comment] 2022-08-19 23:23
This PR was merged 4 days ago. We've got another 3 days to go for regressions then we'll pay it out.

**Comment by tomivs** [comment] 2022-08-23 13:48
Are the 7 days for regression over? Just a friendly bump since last time the bot didn't say anything after the 7 days.

**Comment by tomivs** [comment] 2022-08-30 23:54
Were there any regressions?

**Comment by tomivs** [comment] 2022-08-31 17:02
Any news on this?

cc: @arielgreen @deetergp

**Comment by deetergp** [comment] 2022-09-05 11:33
@tomivs Have you received payment in your account yet?

**Comment by arielgreen** [comment] 2022-09-05 11:35
All contributors have been paid, closing.

**Closed by arielgreen** 2022-09-05 11:35 UTC
Labels: Exported, External, Engineering, Daily, Awaiting Payment
