### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Inconsistency: There is no example for Zip code field on Personal information step 3 of 5 on Bank account page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27448] opened 2023-09-14 14:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Click on settings > Profile > Personal details > Home address > Type wrong numbers into the Zip code field there (You get "Incorrect zip code format. Acceptable format: 205122, 219713, 441699, 287471" error message). After get back to settings page
3. Click on Workspaces > any workspace > Bank account > Connect manually or Continue with setup and reach 3rd step
4. Type wrong numbers into the Zip code field there (You get "Please enter a valid zip code" error message without any examples).

## Expected Result:
Inconsistency: There is no example for Zip code field on Personal information step 3 of 5 on Bank account page

## Actual Result:
There should have example for Zip code field on Personal information step 3 of 5 on Bank account page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.70-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/c485ecb6-710d-4eca-a20f-56141965f2fe

https://github.com/Expensify/App/assets/115492554/ff55712d-439c-4ae3-bb5c-4dd672f88aed

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692787153645409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01639072610d53e68d</li>
        <li>Upwork Job ID: 1702333425891119104</li>
        <li>Last Price Increase: 2023-09-21</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26808377</li>
<li>ishpaul777 | Contributor | 26808379</li>
<li>mahmudjontoraqulov | Reporter | 26808380</li>
</ul></li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-09-14 15:12
### Proposal
### Please re-state the problem that we are trying to solve in this issue
There is no example for Zip code field on Personal information step 3 of 5 on Bank account page

### What is the root cause of that problem?
We are passing a different error text in Addressform used in IdentityForm at step 3 of 5 on Bank account page

```jsx
                errorText={props.errors.zipCode ? props.translate('bankAccount.error.zipCode') : ''}
```

### What changes do you think we should make in order to solve the problem?
We need to replace the translationkey in AddressForm

```
props.translate('privatePersonalDetails.error.incorrectZipFormat', , {zipFormat: CONST.COUNTRY_ZIP_REGEX_DATA.US.samples})
```

**Comment by situchan** [comment] 2023-09-18 10:05
reviewing today

**Comment by garrettmknight** [comment] 2023-09-21 10:47
@situchan did you get a chance to review?

**Comment by situchan** [comment] 2023-09-21 16:20
@ishpaul777's proposal looks good to me. @abdel-h66's proposal is similar but just code refactor.
🎀 👀 🎀 C+ reviewed

**Comment by luacmartins** [comment] 2023-09-22 01:32
Agreed with the proposal

**Comment by ishpaul777** [comment] 2023-09-26 12:28
@situchan Please review PR #28043, when you get the chance

**Comment by garrettmknight** [comment] 2023-10-09 18:06
Summary of payments on this issue:
- urgency bonus? no
- Reporter: @MahmudjonToraqulov - $50 paid via upwork
- Contributor: @ishpaul777 - $500 paid via upwork
- Reviewer: @situchan - $500 paid via upwork

**Comment by garrettmknight** [comment] 2023-10-09 18:07
@situchan can you complete the checklist when you get a chance so we can close this one out?

**Comment by situchan** [comment] 2023-10-09 18:37
- [x] The PR that introduced the bug has been identified. Link to the PR: N/A
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This is minor inconsistency and doesn't require regression test.

**Comment by garrettmknight** [comment] 2023-10-10 14:12
@ishpaul777 thanks for highlighting that - I've paid out the urgency bonus for both you and @situchan

**Closed by garrettmknight** 2023-10-10 14:12 UTC
Labels: External, Daily, Awaiting Payment, Bug
