### ISSUE TITLE
[HOLD for payment 2024-04-03] [Report Fields] [Onyx] Move `policyReportFields_` key back into the `policy_` key

### ISSUE THREAD

**Issue by flodnv** [Expensify/App#36170] opened 2024-02-08 19:20 UTC
# Problem & Solution

Sister issue: https://github.com/Expensify/App/issues/36171

Discussed internally, summarised [here](https://expensify.slack.com/archives/C03TQ48KC/p1707339183790349?thread_ts=1707328858.869149&cid=C03TQ48KC) and concluded [there](https://expensify.slack.com/archives/C03TQ48KC/p1707402878757569?thread_ts=1707328858.869149&cid=C03TQ48KC)

- We added the onyx keys `policyTaxRates_` and `policyReportFields_` for no good reason. There's no size to optimize for in these collections.
- This makes my life harder in trying to fix an architectural problem of sending policy updates in https://github.com/Expensify/Auth/pull/9773 (see https://expensify.slack.com/archives/C03TQ48KC/p1706285244529629 & https://github.com/Expensify/App/issues/34834)
- This makes code more complex than it needs to be (lots of existing data massaging for really no gain)
- As such, we should kill and fix this unnecessarily complex code that was recently introduced. This means, at a minimum (I might be missing things):
	- Moving this data back into the `policy_` key
	- Removing any data massaging from the backend
	- Have the frontend accept the same data as what's in the database
	- Where we should not display disabled fields, then let's use the `disabled` property to hide them. We will need to display them to admins soon enough
- No need to worry about sending updates to policy members when the policy changes, that will be done as part of https://github.com/Expensify/Auth/pull/9773, which includes doing this for all current and future policy attributes

cc @iwiznia @puneetlath @tgolen @marcaaron @francoisl @dangrous @johnmlee101 @MonilBhavsar 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e62ab2c798627fa</li>
        <li>Upwork Job ID: 1755672881949298688</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2024-02-08 20:20
Sibtain will be handling the FE changes and I will take the BE changes

**Comment by marcaaron** [comment] 2024-02-08 20:40
I am not aware of any _documented_ problem with storing everything related to a policy in the `policy_` key.

Some hypothetical problems to watch out for could be:

- Large policy JSON is inefficient to modify in Onyx because we do a deep merge (maybe some copying still happens in some places as well).
- Optimizations exist to deep compare to see if we should update subscribers. Larger the JSON the slower these comparisons would be.
- Subscribing to a subset of data should result in faster updates than subscribing to a large JSON object. Even with the use of a selector. I think it would still be faster.

That's all I have to say on it though. I have not instrumented any of that and it's all just theoretical. This proposal looks fine.

**Comment by flodnv** [comment] 2024-02-09 13:42
>Large policy JSON is inefficient to modify in Onyx 

How large? Tags is the most bloating data and it's already in its own key (and for now we'll leave it there)

>because we do a deep merge

Can you expand on "we do a deep merge"? Where and why? 

---

Thanks for having a look and commenting 🙇

**Comment by marcaaron** [comment] 2024-02-10 00:12
>How large? Tags is the most bloating data and it's already in its own key (and for now we'll leave it there)

I haven't instrumented anything so I can't answer that question.

>Can you expand on "we do a deep merge"? Where and why?

There is a memory cache layer. Before we save things to the Onyx dbs we merge them into the existing objects in the cache. The smaller those objects are the faster they would be to merge (hypothetically). I am not aware that we've hit any kind of limit there yet - but I do know that it was slow enough in the past that we optimized it to make it faster. We could have someone instrument to see at what point the merges get slow - maybe it's a lot or not.

**Comment by allroundexperts** [comment] 2024-02-12 18:53
Will have a PR ready by tomorrow Melv.

**Comment by allroundexperts** [comment] 2024-02-13 20:15
Update: Still working on a PR. Taking me longer than I expected. Will provide an update tomorrow.

**Comment by allroundexperts** [comment] 2024-02-14 23:39
Created draft PR https://github.com/Expensify/App/pull/36553. Please let me know once the backend changes are done and I'll then record the videos.

**Comment by thienlnam** [comment] 2024-02-21 17:47
Still haven't had the chance to add the BE changes as I'm focused on Track, likely will get to it later this week

**Comment by thienlnam** [comment] 2024-02-26 19:49
Back-end PR is in review, as part of simplifying the changes I've made a few additional changes that will need to be reflected in the FE PR
- Report fields are now listed under the 'fieldList' key in the policy and the report
- We're now going to return all the keys on the field list item, that being said we'll need to now have a way on the FE to get the valid options (Removing keys from the values, where disabledOptions are true), and the types upgraded
- The report fields will be returned keyed with expensify_ so we can remove the changes I added [here](https://github.com/Expensify/App/pull/36769)




```
        {
            "type": "formula",
            "fieldID": "text_title",
            "defaultValue": "{report:type} {report:startdate}",
            "value": null,
            "name": "title",
            "target": "expense",
            "values": [],
            "keys": [],
            "externalIDs": [],
            "disabledOptions": [],
            "externalID": null,
            "orderWeight": 0,
            "deletable": true,
            "origin": null,
            "isTax": false,
            "defaultExternalID": null
        },
```
```
   {
            "type": "dropdown",
            "fieldID": "field_id_NUGGET_SHOPZ",
            "defaultValue": "",
            "value": null,
            "name": "Nugget Shopz",
            "target": "expense",
            "values": [
                "Booger King",
                "Chick Fill Hay",
                "Kay Eff See",
                "Mickey Dee's",
                "Wendeez"
            ],
            "keys": [],
            "externalIDs": [],
            "disabledOptions": [
                false,
                false,
                false,
                false,
                false
            ],
            "externalID": null,
            "orderWeight": 1,
            "deletable": false,
            "origin": null,
            "isTax": false,
            "defaultExternalID": ""
        }

```

**Comment by thienlnam** [comment] 2024-03-01 22:21
Most of the BE changes are complete, one last thing I need to do is remove the old COLLECTION_POLICY_REPORT_FIELDS, and have new changes to the report fields update the policy object instead https://github.com/Expensify/Auth/pull/10030

**Comment by thienlnam** [comment] 2024-03-05 19:05
Holding on https://github.com/Expensify/Auth/pull/9773 before the last PR to remove the old onyx key COLLECTION_POLICY_REPORT_FIELDS for pusher updates when a report field changes. 

cc @allroundexperts You should be good to make the corresponding changes added in https://github.com/Expensify/App/issues/36170#issuecomment-1965132057

**Comment by jjcoffee** [comment] 2024-03-06 10:28
@thienlnam Happy to review the FE PR as C+ since I have context from reviewing the other report fields PRs :pray:

**Comment by thienlnam** [comment] 2024-03-12 17:24
Current status:
- Last Auth PR that sends back the new fieldList in the policy key is [here](https://github.com/Expensify/Auth/pull/10133). This is unblocked now since we merged this [PR](https://github.com/Expensify/Auth/pull/9773)
- @allroundexperts has created a draft [PR](https://github.com/Expensify/App/pull/36553) in App that updates the handling to this new key

**Comment by thienlnam** [comment] 2024-03-15 21:44
The last Auth PR was merged and should be getting deployed on Monday - once that is done, we can merge @allroundexperts's App PR here https://github.com/Expensify/App/pull/36553

**Comment by JmillsExpensify** [comment] 2024-03-19 02:15
Auth PR was deployed today, so looks like we need to get @allroundexperts PR into review. When do we expect that to happen?

**Comment by allroundexperts** [comment] 2024-03-20 13:13
@thienlnam @JmillsExpensify [PR](https://github.com/Expensify/App/pull/36553) ready for review!

**Comment by JmillsExpensify** [comment] 2024-03-21 03:56
Thank you!

**Comment by jjcoffee** [comment] 2024-03-21 09:44
@JmillsExpensify Could you assign me here as I reviewed the PR? Thanks! :bow:

**Comment by JmillsExpensify** [comment] 2024-03-23 18:37
Done. I'll go ahead and assign myself for the payment later.

**Comment by JmillsExpensify** [comment] 2024-04-03 03:29
Payment summary: 

 - Contributor: @allroundexperts $500
 - Contributor+: @jjcoffee $500

@jjcoffee Do we need any regression tests for this issue?

**Comment by JmillsExpensify** [comment] 2024-04-03 03:31
Upwork offer sent to C+

**Comment by jjcoffee** [comment] 2024-04-03 07:20
@JmillsExpensify Accepted, thanks! There should already be regression tests that cover the report fields functionality, so I think we're good here.

**Comment by JmillsExpensify** [comment] 2024-04-03 21:27
Awesome! Contract paid, so closing this issue.

**Closed by JmillsExpensify** 2024-04-03 21:27 UTC
Labels: Engineering, Weekly, Internal, Task, Awaiting Payment

**Comment by laurenreidexpensify** [comment] 2024-05-03 17:11
Payment summary:

- Contributor: @allroundexperts $500 newdot
- Contributor+: @jjcoffee $500 upwork

**Comment by JmillsExpensify** [comment] 2024-05-03 17:26
$500 approved for @allroundexperts
