### ISSUE TITLE
[$500] Category selected automatically when create second request without category in parent IOU

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35367] opened 2024-01-30 10:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. As the employee of Collect WS in NewDot navigate to the workspace chat
3. Start a request and fulfil the amount/merchant fields with numbers as long as the amount of digits
4. Reach the categories list and select a category
5. Complete the request
6. Start a new request in a parent IOU
7. Complete the request without category but fulfil the amount/merchant fields with numbers as long as the amount of digits.

## Expected Result:
An uncategorized IOU was created

## Actual Result:
Category selected automatically when create second request without category in a parent IOU.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/31aa7d3d-7b6c-421d-9284-f13c02848b51

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177d7978236042754</li>
        <li>Upwork Job ID: 1752274814624772096</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by JordanLevy19** [comment] 2024-01-30 15:39
**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**
There is an issue where the category of a new expense in a workspace is automatically set to the category of the most recently created expense. This occurs when a user creates an expense request in a workspace chat, fills in the amount and merchant fields, but does not explicitly select a new category. 

**What is the root cause of that problem?**
The root cause appears to be related to how the category selection is handled and stored for transactions in the application. Specifically, from the logic within the buildOptimisticTransaction function in the IOU.js file. This function is responsible for creating a new transaction and includes the category as a parameter. 

**What changes do you think we should make in order to solve the problem?**

**Modify buildOptimisticTransaction Function:**
In the buildOptimisticTransaction function, ensure that the category parameter is explicitly set to a default state (like 'uncategorized' or null) when not provided by the user. 

buildOptimisticTransaction(
    ...,
    category || 'uncategorized',
    ...
);

**Enhance Transaction Initialization in startMoneyRequest_temporaryForRefactor:**
Modify the transaction initialization logic to explicitly set the category to null or a similar default state. This provides each new transaction with a clear category state.

function startMoneyRequest_temporaryForRefactor(...) {
    // Existing logic...
    Onyx.set(`${ONYXKEYS.COLLECTION.TRANSACTION_DRAFT}${newTransactionID}`, {
        amount: 0,
        comment,
        category: null, // Explicitly setting category to null
    });
}

**Update Category Management Functions:**
Enhance the setMoneyRequestCategory_temporaryForRefactor and resetMoneyRequestCategory_temporaryForRefactor functions to manage the category state, especially in cases where no category is selected.

function setMoneyRequestCategory_temporaryForRefactor(transactionID, category) {
    Onyx.merge(`${ONYXKEYS.COLLECTION.TRANSACTION_DRAFT}${transactionID}`, {category: category || null});
}

**Comment by isabelastisser** [comment] 2024-02-01 21:53
@abdulrahuman5196, please review the proposal above. Thanks!

**Comment by abdulrahuman5196** [comment] 2024-02-05 13:53
Hi, Will go through review today

**Comment by isabelastisser** [comment] 2024-02-07 16:09
hEY @abdulrahuman5196, please provide an update. Thanks!

**Comment by abdulrahuman5196** [comment] 2024-02-08 19:38
Hi, Sorry for the delay. Will take care of this in my morning or will re-assign tomorrow night.

**Comment by abdulrahuman5196** [comment] 2024-02-12 06:22
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-02-12 07:28
@JordanLevy19 I am not able to understand the root cause mentioned here https://github.com/Expensify/App/issues/35367#issuecomment-1917264016. Could you kindly explain the root cause and provide code references on the same?

**Comment by isabelastisser** [comment] 2024-02-13 14:17
Hey @JordanLevy19, can you please follow up on @abdulrahuman5196 comment above? Thanks!

**Comment by JordanLevy19** [comment] 2024-02-13 19:20
@abdulrahuman5196 @isabelastisser - please see revised root cause response below

The root cause is the handling of the category parameter in the buildOptimisticTransaction function in the IOU.js. The function constructs a new transaction object, including a category field. If the category is not explicitly defined for a new transaction, the application doesn't reset the field to a neutral state (such as null or 'uncategorized'), leading to the unintentional reuse of the previous transaction category. 

Also, the transactions in startMoneyRequest_temporaryForRefactor and the category management in functions like setMoneyRequestCategory_temporaryForRefactor don't enforce a reset or clear of the category field for a new transaction. 

Link
App/src/libs/actions/IOU.ts
https://github.com/Expensify/App/blob/f438cb7901c4405e7ec2bbb22aaa904bb5b8fb66/src/libs/actions/IOU.ts#L227


Hope this is more of what you are looking for!

**Comment by isabelastisser** [comment] 2024-02-14 01:41
Hey @abdulrahuman5196, pleas review the updated proposal above. Thanks!

**Comment by abdulrahuman5196** [comment] 2024-02-14 18:35
Hi, Will take a look into the review tomorrow

**Comment by isabelastisser** [comment] 2024-02-16 03:29
Hey, @abdulrahuman5196, any updates? Thanks!

**Comment by abdulrahuman5196** [comment] 2024-02-16 06:46
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-02-16 06:58
@JordanLevy19 

I think the root cause you are saying that when we set the transaction to onyx it takes the previous category since we don't explicitly say any category.

I doubt this is true, because we use `Onyx.set` which will override any existing data

https://github.com/Expensify/App/blob/f438cb7901c4405e7ec2bbb22aaa904bb5b8fb66/src/libs/actions/IOU.ts#L243-L246

**Comment by abdulrahuman5196** [comment] 2024-02-16 06:59
And this issue could be related to this https://github.com/Expensify/App/issues/33518.

**Comment by isabelastisser** [comment] 2024-02-20 02:23
@JordanLevy19, can you please follow up on the comment above?

@abdulrahuman5196, does it mean that we need an updated proposal or a new proposal? Thanks!

**Comment by abdulrahuman5196** [comment] 2024-02-20 18:39
> @abdulrahuman5196, does it mean that we need an updated proposal or a new proposal? Thanks!

Yes. Updated proposal. 


And we don't have any other proposals to review right now.

**Comment by isabelastisser** [comment] 2024-02-23 16:25
Not overdue, still waiting for proposals.

**Comment by abdulrahuman5196** [comment] 2024-02-26 10:35
Waiting on proposals

**Comment by isabelastisser** [comment] 2024-02-26 18:26
Based on the chat in Slack and more testing, I agree that this is not a bug, but the result of the implicit categorization working based on the merchant entered.

Closed!

**Closed by isabelastisser** 2024-02-26 18:26 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
