### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$500] Footer for anonymous user sign in modal distorted

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28025] opened 2023-09-22 15:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log out of your test account
2. Go to https://new.expensify.com/r/7277649907280010
3. See the "Welcome to #public-rooooom!"
5. Click on the Sign In button
6. Scroll down to the bottom of the page and observe the footer

## Expected Result: 
It should not get distorted and show the list in vertical order

## Actual Result: 
It gets distorted

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/56406036-e86a-4f0e-bead-6b77815e91e1

https://github.com/Expensify/App/assets/43996225/2bace89e-8123-451d-ac09-da051bb91e22

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695037709793059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0173528f51d8bbad2d</li>
        <li>Upwork Job ID: 1705243190334554112</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Contributor | 27016148</li>
<li>Pujan92 | Reporter | 27016149</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-09-22 15:31
## Proposal by @pujan92
### Please re-state the problem that we are trying to solve in this issue.
Footer for the sign in modal is distorted
### What is the root cause of that problem?
For the sign in page content inside the modal we are not passing the prop for the `Footer` to inform about getting it open in the modal/smaller width.
https://github.com/Expensify/App/blob/023337624273b1a9e7fa22b43867d2aeac755850/src/pages/signin/SignInPageLayout/index.js#L172
### What changes do you think we should make in order to solve the problem?
We need to pass prop `isSmallScreenWidth` explicitly as we know it is going to open in the small screen or right-side modal.
https://github.com/Expensify/App/blob/023337624273b1a9e7fa22b43867d2aeac755850/src/pages/signin/SignInPageLayout/index.js#L172
### What alternative solutions did you explore? (Optional)
Pass prop `isInModal` to the Footer component and use that value to decide whether to show vertically or not. The way we are doing in the `SignInPageLayout` component here.
https://github.com/Expensify/App/blob/a211b6dc7628f2b1412d0fc24d4bf9ed26d6ab21/src/pages/signin/SignInPageLayout/index.js#L65
https://github.com/Expensify/App/blob/a211b6dc7628f2b1412d0fc24d4bf9ed26d6ab21/src/pages/signin/SignInPageLayout/Footer.js#L153
`const isVertical = props.isSmallScreenWidth || props.isInModal;`

**Comment by rootBrz** [comment] 2023-09-25 09:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The footer in Sign In modal gets distorted

### What is the root cause of that problem?
Incorrect width set on the footerColumn elements.

### What changes do you think we should make in order to solve the problem?

Set the correct width on the footer column element, currently, it checks if the device's screen width is small and then checks if the device's width is medium, if it is it sets the width to 50% of the parent and if not to 25%. This causes the footer to look distorted on the large screens.

**Comment by sobitneupane** [comment] 2023-09-27 05:00
Thanks for the proposal @Pujan92 

@Pujan92's proposal looks good to me. We can pass `shouldShowSmallScreen` from SignInPageLayout and use it in `Footer`.

🎀 👀 🎀 C+ reviewed

**Comment by roryabraham** [comment] 2023-09-30 03:00
> we know it is going to open in the small screen or right-side modal

Sorry, how do we know that?

**Comment by roryabraham** [comment] 2023-10-02 22:50
Bump, the given proposal is unfortunately not clear to me.

**Comment by Pujan92** [comment] 2023-10-03 17:17
> > we know it is going to open in the small screen or right-side modal
> 
> Sorry, how do we know that?

Bcoz we have that condition for `shouldShowSmallScreen` in the `SignInPageLayout` and based on that we render the layout differently.

https://github.com/Expensify/App/blob/e30dce19672085a2c8b34576d2fe33ebd8aee249/src/pages/signin/SignInPageLayout/index.js#L66

**Comment by Pujan92** [comment] 2023-10-05 10:55
@sobitneupane [PR](https://github.com/Expensify/App/pull/28904) is ready for review!

**Comment by Christinadobrzyn** [comment] 2023-10-23 22:10
Ready for payment, is there a regression test for this @Pujan92 @sobitneupane?

Once we have a regression test payment will be:

Bug reporter: $50 @Pujan92 (in Upwork)
Contributor: $500 @Pujan92 (in Upwork)
Contributor+: $500 @sobitneupane (paid through NewExpensify)

Speed Bonus: N - based on https://github.com/Expensify/App/issues/28025#issuecomment-1760627060

Upwork job - https://www.upwork.com/jobs/~0173528f51d8bbad2d

**Comment by Pujan92** [comment] 2023-10-24 02:39
@Christinadobrzyn can you plz reconsider the summary for the urgency bonus as the PR was approved by C+ in 2 days, but seems @roryabraham was OOO which delayed the merging.

**Comment by roryabraham** [comment] 2023-10-24 16:07
- @Pujan92 assigned on Oct 4th
- PR created less than 24hrs later on Oct 5th
- PR approved on Oct 6th, less than 48 hours after assignment

So yes, I agree the urgency bonus should apply here

**Comment by Christinadobrzyn** [comment] 2023-10-24 16:12
Added a bonus to the above [payment breakdown](https://github.com/Expensify/App/issues/28025#issuecomment-1776101705) and also added the bonus to @Pujan92 through Upwork.

**Comment by roryabraham** [comment] 2023-10-26 23:57
Completed my section of the BZ checklist

> Should there be a regression test?

There absolutely should be regression tests for the flow where you go to a public room and login from there. Not sure we need anything specific about the footer layout being borked

**Comment by Christinadobrzyn** [comment] 2023-10-27 04:20
Thanks Rory! @Pujan92 or @sobitneupane can you please provide a regression test for this based on -https://github.com/Expensify/App/issues/28025#issuecomment-1782088756 Thanks!

**Comment by sobitneupane** [comment] 2023-10-30 10:46
**Regression Test proposal**

1. Log out from expensify if you are already logged in.
2. Go to a public room.
3. Click on the "Sign In" button
4. Scroll down to the bottom of the page and observe the footer
5. Verify that the footer is not distorted.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-10-30 14:03
https://github.com/Expensify/App/issues/28025#issuecomment-1776101705

Requested payment on newDot.

**Comment by Christinadobrzyn** [comment] 2023-10-30 15:21
Thanks! Created Regression test - https://github.com/Expensify/Expensify/issues/331185

Paid out based on https://github.com/Expensify/App/issues/28025#issuecomment-1776101705

Closing this as complete

**Closed by Christinadobrzyn** 2023-10-30 15:21 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-03 22:24
$750 payment approved based on [this comment](https://github.com/Expensify/App/issues/28025#issuecomment-1776101705).
