### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250]  Distance is not optimistically updated

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41817] opened 2024-05-07 21:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713898800427079
 
## Action Performed:
1. Go to an existing distance request
2. Click the distance field
3. Edit the waypoints and click save

## Expected Result:
The distance optimistically updates to the correct new value.
## Actual Result:
The distance does not optimistically update to the correct new value while online. It updates to a big value, then showing "pending" and then updates.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/7adbe269-c853-4ee3-b938-008d81ecced9

https://github.com/Expensify/App/assets/38435837/44f86893-33fa-4abc-a7e7-df14d3672788

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e08c348144daf8d9</li>
        <li>Upwork Job ID: 1788075386637766656</li>
        <li>Last Price Increase: 2024-05-15</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2024-05-08 05:16
I looks like this 'pending' is happening on all platforms - I think this can be external?

**Comment by Christinadobrzyn** [comment] 2024-05-08 05:16
cc @neil-marcellini and @paultsimura since you were involved in the slack chat - https://expensify.slack.com/archives/C049HHMV9SM/p1713898800427079

**Comment by nkdengineer** [comment] 2024-05-08 05:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The distance does not optimistically update to the correct new value while online. It updates to a big value, then showing "pending" and then updates.

### What is the root cause of that problem?
We always set `amount` to default amount in optimistic data if the waypoints is changed.

https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/libs/actions/IOU.ts#L2322-L2323

### What changes do you think we should make in order to solve the problem?
We should check if the route is also updated, we will calculate the amount and update it in optimistic data. The way to calculate the same as we do in `MoneyRequestConfirmationList` [here](https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/MoneyRequestConfirmationList.tsx#L320)


1. Accept `routes` params in `updateMoneyRequestDistance` function and add it to transactionChanges here
```
const transactionChanges: TransactionChanges = {
    waypoints,
    routes
};
```
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/libs/actions/IOU.ts#L2861-L2862
2. Pass `routes` and `policy` into `IOU.updateMoneyRequestDistance` function here

```
const isRouteChanged = !isEqual(transactionBackup?.routes, transaction?.routes)
if (isEqual(oldAddresses, addresses) && isRouteChanged) {
    Navigation.dismissModal();
    return;
}
IOU.updateMoneyRequestDistance({transactionID: transaction?.transactionID ?? '', transactionThreadReportID: report?.reportID ?? '', waypoints, ...(isRouteChanged ? {routes: transaction?.routes} : {}), policy});

```
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/pages/iou/request/step/IOURequestStepDistance.tsx#L382

3. If the routes exist in `transactionChanges`, we will calculate the amount otherwise set it as default

```
let updateAmount: number = CONST.IOU.DEFAULT_AMOUNT;
if (transactionChanges?.routes) {
    const customUnitRateID = TransactionUtils.getRateID(transaction) ?? '';
    const mileageRates = DistanceRequestUtils.getMileageRates(policy);
    const mileageRate = mileageRates?.[customUnitRateID];
    const {unit, rate} = mileageRate;
    const distance = TransactionUtils.getDistance(transaction);
    updateAmount = -DistanceRequestUtils.getDistanceRequestAmount(distance, unit, rate ?? 0);
}

updatedTransaction = {
    ...updatedTransaction,
    amount: updateAmount,
    modifiedAmount: updateAmount,
    modifiedMerchant: Localize.translateLocal('iou.fieldPending'),
};

```
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/libs/actions/IOU.ts#L2319

Do the same for `getUpdateTrackExpenseParams`.

OPTIONAL: We can create a util to update the amount when the waypoint is changed and use it in these functions
### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/Expensify/App/assets/161821005/31389b39-51c9-469f-ad4c-1ab879e38560

**Comment by Christinadobrzyn** [comment] 2024-05-10 01:47
@akinwale can you check out the ^ proposal and review this [convo](https://expensify.slack.com/archives/C049HHMV9SM/p1713898800427079) with more context? Thank you!

**Comment by Christinadobrzyn** [comment] 2024-05-13 01:48
cc @paultsimura since you were in the Slack convo, just in case you have some input here.

**Comment by neil-marcellini** [comment] 2024-05-16 18:39
> @nkdengineer's [proposal](https://github.com/Expensify/App/issues/41817#issuecomment-2099770283) works here.
> 
> 🎀👀🎀 C+ reviewed.

I agree! Hired. I like the idea of using util functions to avoid repetition and simplify.

**Comment by nkdengineer** [comment] 2024-05-17 08:39
@akinwale The PR is [here](https://github.com/Expensify/App/pull/42337).

**Comment by Christinadobrzyn** [comment] 2024-05-21 07:33
reviewing PR - https://github.com/Expensify/App/pull/42337

**Comment by Christinadobrzyn** [comment] 2024-05-28 06:12
monitoring - https://github.com/Expensify/App/pull/42337

**Comment by Christinadobrzyn** [comment] 2024-06-05 07:55
@akinwale do we need a regression test for this?

Payouts due:

- [ ] Contributor: $250 @nkdengineer (Upwork offer here - https://www.upwork.com/nx/wm/workroom/37320027/overview)
- [ ] Contributor+: $250 @akinwale (Upwork offer - https://www.upwork.com/ab/applicants/1788075386637766656/offers)

Upwork job is [here](https://www.upwork.com/ab/applicants/1788075386637766656/job-details).

**Comment by akinwale** [comment] 2024-06-05 08:02
> @akinwale do we need a regression test for this?

@Christinadobrzyn Yes, we do.

Also, please note that there was a regression from the PR, so there should be a penalty of 50% of the due payment applied.

**Comment by Christinadobrzyn** [comment] 2024-06-07 05:13
hi @akinwale can you provide the regression test for this? Thank you!

**Comment by akinwale** [comment] 2024-06-07 06:48
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch the Expensify app
2. Create a new distance request
3. Navigate to the newly created distance request
4. Change the distance by modifying any of the way points to new locations, or by adding additional waypoints
5. Verify that the amount is updated immediately

Do we agree 👍 or 👎?

**Comment by akinwale** [comment] 2024-06-07 06:48
@Christinadobrzyn Done!

**Comment by Christinadobrzyn** [comment] 2024-06-10 03:21
Thanks @akinwale - regression test here - https://github.com/Expensify/Expensify/issues/403299

Paying out based on this payment summary - https://github.com/Expensify/App/issues/41817#issuecomment-2149129713

Closing this out! let me know if I missed anything!

**Closed by Christinadobrzyn** 2024-06-10 03:21 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
