### ISSUE TITLE
[$1000] The screen becomes blank after dragging over the Concierge hint message in the new group.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22054] opened 2023-07-02 03:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Open the mWeb.
2. Click on :green-plus-button:
3. Create new group.
4. Add member to group, make sure to add 1-2 new users.
5. Navigate to Group chat
6. Touch and drag over the concierge hint message
## Expected Result: 
Screen should not turn blank.
## Actual Result: 
The screen becomes blank after dragging over the Concierge hint message in the new group.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/14a6e882-fd30-4b99-85f2-ac47110a7f46

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ad-eeb
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688160582722119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010740381f9952ebc4</li>
        <li>Upwork Job ID: 1677252071887335424</li>
        <li>Last Price Increase: 2023-07-21</li>
    </ul>
</details>

**Comment by zanyrenney** [comment] 2023-07-04 12:51
@kavimuru and I are both unable to reproduce. Checking with bug reporter if this is still occuring for them.

**Comment by zanyrenney** [comment] 2023-07-04 16:36
> If the reproduction steps are clear and you're unable to reproduce the bug, check with the reporter and QA first, then close the issue.

**Comment by zanyrenney** [comment] 2023-07-07 09:43
Thanks for the update @Ad-eeb !

**Comment by zanyrenney** [comment] 2023-07-10 11:04
Still waiting on proposals here!

**Comment by zanyrenney** [comment] 2023-07-10 11:05
@eVoloshchak have you had a chance to do an initial review too?

**Comment by zanyrenney** [comment] 2023-07-11 09:49
bump @eVoloshchak

**Comment by ShogunFire** [comment] 2023-07-13 01:43
Hello, is it just me that receive the concierge message only on mweb ? Is there a reason for that ?

**Comment by ShogunFire** [comment] 2023-07-13 05:11
Actually it doesn't have to be a concierge message, I don't find the problem but it seems to be related to the drag and drop functionality:
![image](https://github.com/Expensify/App/assets/19537677/4ddc3737-db66-4728-ad91-b187968b8826)

**Comment by eVoloshchak** [comment] 2023-07-13 17:07
Can reproduce this, doesn't have to be a group chat, can also be observed in a conversation with Concierge

https://github.com/Expensify/App/assets/9059945/244ceb54-ea75-4150-b1f5-c77243a73184

**Comment by eVoloshchak** [comment] 2023-07-16 22:53
Not overdue, this is awaiting proposals

**Comment by rezkiy37** [comment] 2023-07-18 15:16
Guys, I've tried to reproduce it on 2 different Android version and it works correctly. So, I am not able to reproduce. 
Could you please clarify what's the Android version do you have? Does your Android device have some specific Android UI, like MIUI, One UI? 

<details><summary>Videos</summary>
<p>

https://github.com/Expensify/App/assets/57314631/2b935bd9-e081-451a-b347-24c070f3d614

https://github.com/Expensify/App/assets/57314631/5721d528-faaa-4884-b36d-fa369e042285

</p>
</details>

**Comment by eVoloshchak** [comment] 2023-07-18 18:14
@rezkiy37, I did reproduce it on Pixel 6 running stock Android 13 
Chrome 114.0.5735.196

https://github.com/Expensify/App/assets/9059945/620e8da3-5a7f-4bac-9177-85f2be55379a

**Comment by rezkiy37** [comment] 2023-07-19 12:07
We tried to reproduce the bug on a real device - Asus Zenfone 9, Android 13. It works fine in Chrome and DuckDuckGo browsers. So, I am continue investigating within the codebase. Will let you know soon.

https://github.com/Expensify/App/assets/57314631/785e9a29-95ab-419a-b4d0-942e9181eb49

**Comment by zanyrenney** [comment] 2023-07-21 16:17
If we can't reproduce the bug on the main devices listed in the OP. I suggest we close this issue unless @rezkiy37 can find anything obvious that is causing this in the codebase.

**Comment by rezkiy37** [comment] 2023-07-24 09:18
> If we can't reproduce the bug on the main devices listed in the OP. I suggest we close this issue unless @rezkiy37 can find anything obvious that is causing this in the codebase.

@zanyrenney, Yeah, unfortunately or fortunately, I and my colleagues from Callstack were unable to reproduce the bug. Also, I haven't found anything that could invoke the bug within the codebase.

**Comment by zanyrenney** [comment] 2023-07-24 11:54
Thanks for the investigation @rezkiy37 I think we better close this one out then.

**Closed by zanyrenney** 2023-07-24 11:54 UTC
Labels: External, Engineering, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
