### ISSUE TITLE
[HOLD for payment 2023-10-23][$1000] IOU - When performing an invoice division in a group, the amount of this is set to zero

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26020] opened 2023-08-27 00:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. First login to different accounts which two different users, one as user A and the other as user B
2. Create a group that includes user A and user B.
3. [user A] Start chat in the group.
4. [user B] Enter in the group
5. [user A] Click plus sign and select Split bill.
6. [user A] Write a number, click Next button and Split button

## Expected Result:
Group members should see the split bill amount

## Actual Result:
Split invoice amount is set to zero

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/44fb2977-3da5-4490-bc6b-6db38461a5b3

https://github.com/Expensify/App/assets/78819774/015e82ed-86d1-4b0c-a2e4-dd668d3a64b2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Mauri-salazar)

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692290507391009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018591b88c96d0a9bb</li>
        <li>Upwork Job ID: 1696254007472058368</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27183589</li>
<li>paultsimura | Contributor | 27183592</li>
<li>Mauri-salazar | Reporter | 27183593</li>
</ul></li>
    </ul>
</details>

**Comment by lschurr** [comment] 2023-08-29 15:26
Waiting for proposals.

**Comment by paultsimura** [comment] 2023-08-30 01:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
While sending a "Split bill" request in a group, other participants see the MoneyRequestPreview with $0

### What is the root cause of that problem?
While executing the `splitBill`, the transaction is created optimistically:
https://github.com/Expensify/App/blob/575524c47efd78cdf1f18a3a40f04a54dcbfb036/src/libs/actions/IOU.js#L910

This leads to the transaction not yet being accessible in Onyx when the `MoneyRequestPreview` component is rendering: https://github.com/Expensify/App/blob/0343bfeda5bdb45140fa5464ca4a9e9390ad30c8/src/components/ReportActionItem/MoneyRequestPreview.js#L340

Therefore, both the currency and amount are set to default: `$0`.

### What changes do you think we should make in order to solve the problem?


When rendering `MoneyRequestPreview`:
`if (_.isEmpty(props.transaction)) -> force Report.openReport(props.chatReportID)` in order to fetch the updated data

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/12595293/85870b2d-8c9e-4887-b057-2c44ef9c3ce3">


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by paultsimura** [comment] 2023-08-30 01:24
Contributor details
Your Expensify account email: paultsimura@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01998fcb3ca1e361ed

**Comment by napster125** [comment] 2023-08-30 06:34
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When users split a bill in a group, the amount of the split is set to zero.

### What is the root cause of that problem?
The root cause of this problem can be traced to specific lines of code:
https://github.com/Expensify/App/blob/bb432aa6d787c6ba95faed521286cd169cbcade6/src/components/ReportActionItem/MoneyRequestPreview.js#L151
https://github.com/Expensify/App/blob/bb432aa6d787c6ba95faed521286cd169cbcade6/src/components/ReportActionItem/MoneyRequestPreview.js#L344-L346
In these code snippets, `action.originalMessage.IOUTransactionID` contains the correct value, but the transaction data isn't present in the OnyxDB. This is due to the fact that only the `report` and `reportAction` are being updated, while the transaction is not. As a result, when `props.transaction` is accessed, it returns an empty object (`{ }`), leading to the displayed transaction amount being zero.
![Screenshot 2023-08-28 220015](https://github.com/Expensify/App/assets/136437976/77db9950-11b4-4ceb-adb1-940254771d81)
![Screenshot 2023-08-28 220032](https://github.com/Expensify/App/assets/136437976/f63d25e4-34ac-4947-9a91-e9159d5ac94e)

### What changes do you think we should make in order to solve the problem?
To resolve this issue, I suggest the following approach:
https://github.com/Expensify/App/blob/bb432aa6d787c6ba95faed521286cd169cbcade6/src/pages/home/ReportScreen.js#L279-L283
https://github.com/Expensify/App/blob/6e17b64be0e571773bed42446346045c659640d6/src/pages/home/ReportScreen.js#L208-L224

In this code snippet, the changes involve:

- Ensuring that the report fetch is triggered only if specific conditions are met.
- Adding the ability to force fetch data without adhering to these conditions.

```
if (onyxReportID === prevReport.reportID && (!onyxReportID || onyxReportID === routeReportID) && !ReportUtils.isUnread(report)) {
  return;
}

fetchReportIfNeeded(true);
```
The function `ReportUtils.isUnread` determines whether a report has been read or remains unread.


The function fetchReportIfNeeded should also be updated as follows:
```
const fetchReportIfNeeded = useCallback((shouldFetch = false) => {
    const reportIDFromPath = getReportID(route);
    if (!reportIDFromPath) {
        return;
    }
    if (!shouldFetch && report.reportID && report.reportID === getReportID(route)) {
        return;
    }
    Report.openReport(reportIDFromPath);
}, [report.reportID, route]);
```
In this updated function, the `shouldFetch` parameter enables a forced fetch without meeting the usual conditions.

Additionally, we should modify the code as follows:

https://github.com/Expensify/App/blob/bb432aa6d787c6ba95faed521286cd169cbcade6/src/components/ReportActionItem/MoneyRequestPreview.js#L151

```
const {
        amount: requestAmount,
        currency: requestCurrency,
        comment: requestComment,
        merchant: requestMerchant,
    } = _.isEmpty(props.transaction) ? lodashGet(props.action, 'originalMessage', {}) : ReportUtils.getTransactionDetails(props.transaction);
```
This modification temporarily uses `props.action.originalMessage` when `props.transaction` is empty, providing a workaround to populate the transaction data.
![get_temp_transaction_data](https://github.com/Expensify/App/assets/136437976/870899f8-c928-4661-b4e6-d6d973f4c2ff)

Lastly, in the section of code related to handling the report action item press, adjustments are necessary to ensure that the component is unavailable to press when `props.transaction` is empty:
https://github.com/Expensify/App/blob/bb432aa6d787c6ba95faed521286cd169cbcade6/src/components/ReportActionItem/MoneyRequestPreview.js#L307-L309

```
if (!props.onPreviewPressed || _.isEmpty(props.transaction)) {
  return childContainer;
}
```

#### Result

https://github.com/Expensify/App/assets/136437976/6ff6c830-aac7-4e20-97a3-82a05850f0a2


### What alternative solutions did you explore? (Optional)
Initially, I attempted to modify the `fetchReportIfNeeded` function to fetch the report, but this approach didn't provide the desired behavior. The amount in the `MoneyRequestPreview` component was briefly set to zero before displaying the correct value. This wasn't the desired behavior.
Subsequently, I made modifications to the `MoneyRequestPreview` component, preventing rendering when `props.transaction` is empty. However, this resulted in the manager's split bill information being displayed without any visible element, which was also undesirable.
The final solution, as proposed, was achieved by modifying the `MoneyRequestPreview` component to display temporary split bill information while fetching and updating the OnyxDB to include transaction data.
This approach addressed the issue effectively while considering user interaction scenarios.

**Comment by lschurr** [comment] 2023-09-01 14:32
Could you review the proposals here @aimane-chnaif?

**Comment by paultsimura** [comment] 2023-09-01 18:37
@lschurr even though an idea of getting paid for this issue seems appealing, I think it will be mostly handled now in https://github.com/Expensify/App/issues/26270

However, the skeleton will still be visible for about a minute (until the next Ping request comes), as the inexistent transaction issue will still be in place. 
Taking that into consideration, I would modify my proposal by only keeping the part about calling `Report.openReport()` if we receive such a request with a not-yet-existing transaction ID.

**Comment by JmillsExpensify** [comment] 2023-09-02 14:23
Agreed. I would close this report.

**Comment by napster125** [comment] 2023-09-02 14:42
https://github.com/Expensify/App/issues/26518#issuecomment-1703287836

Perhaps, the team don't want to add skeleton UI.

**Comment by paultsimura** [comment] 2023-09-02 16:56
Huh, I was unaware of that. In this case I'm keeping my initial proposal🙂

**Comment by lschurr** [comment] 2023-09-04 23:55
@aimane-chnaif could you please review?

**Comment by lschurr** [comment] 2023-09-06 17:55
Bump @aimane-chnaif

**Comment by paultsimura** [comment] 2023-09-08 13:59
## Proposal
Updated proposal https://github.com/Expensify/App/issues/26020#issuecomment-1698344130

**Comment by paultsimura** [comment] 2023-09-08 14:11
@lschurr @aimane-chnaif I've updated my initial proposal.
However, if you think that "skeleton view is stuck" is now a different issue that the one stated in this issue, I have reported it here: https://expensify.slack.com/archives/C049HHMV9SM/p1694182124123539

**Comment by lschurr** [comment] 2023-09-13 17:49
Bump @aimane-chnaif

**Comment by lschurr** [comment] 2023-09-17 10:47
Bumped in Slack as well - https://expensify.slack.com/archives/C01GTK53T8Q/p1694947661478389

**Comment by Pluto0104** [comment] 2023-09-18 11:35
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When users split a bill in a group, the amount of the split is set to zero.

### What is the root cause of that problem?
The root cause of this problem can be traced to specific lines of code:
https://github.com/Expensify/App/blob/bb432aa6d787c6ba95faed521286cd169cbcade6/src/components/ReportActionItem/MoneyRequestPreview.js#L151
https://github.com/Expensify/App/blob/bb432aa6d787c6ba95faed521286cd169cbcade6/src/components/ReportActionItem/MoneyRequestPreview.js#L344-L346
In these code snippets, `action.originalMessage.IOUTransactionID` contains the correct value, but the transaction data isn't present in the OnyxDB. This is due to the fact that only the `report` and `reportAction` are being updated, while the transaction is not. As a result, when `props.transaction` is accessed, it returns an empty object (`{ }`), leading to the displayed transaction amount being zero.

### What changes do you think we should make in order to solve the problem?
To resolve this issue, I suggest the following approach:
https://github.com/Expensify/App/blob/bb432aa6d787c6ba95faed521286cd169cbcade6/src/pages/home/ReportScreen.js#L279-L283
https://github.com/Expensify/App/blob/6e17b64be0e571773bed42446346045c659640d6/src/pages/home/ReportScreen.js#L208-L224

In this code snippet, the changes involve:

- Ensuring that the report fetch is triggered only if specific conditions are met.
- Adding the ability to force fetch data without adhering to these conditions.

```js
if (onyxReportID === prevReport.reportID && (!onyxReportID || onyxReportID === routeReportID) && !ReportUtils.isUnread(report)) {
  return;
}

fetchReportIfNeeded(true);
```
The function `ReportUtils.isUnread` determines whether a report has been read or remains unread.


The function fetchReportIfNeeded should also be updated as follows:
```js
const fetchReportIfNeeded = useCallback((shouldFetch = false) => {
    const reportIDFromPath = getReportID(route);
    if (!reportIDFromPath) {
        return;
    }
    if (!shouldFetch && report.reportID && report.reportID === getReportID(route)) {
        return;
    }
    Report.openReport(reportIDFromPath);
}, [report.reportID, route]);
```
In this updated function, the `shouldFetch` parameter enables a forced fetch without meeting the usual conditions.

Additionally, we should modify the code as follows:

https://github.com/Expensify/App/blob/bb432aa6d787c6ba95faed521286cd169cbcade6/src/components/ReportActionItem/MoneyRequestPreview.js#L151

```js
const {
        amount: requestAmount,
        currency: requestCurrency,
        comment: requestComment,
        merchant: requestMerchant,
    } = _.isEmpty(props.transaction) ? lodashGet(props.action, 'originalMessage', {}) : ReportUtils.getTransactionDetails(props.transaction);
```
This modification temporarily uses `props.action.originalMessage` when `props.transaction` is empty, providing a workaround to populate the transaction data.
![get_temp_transaction_data](https://github.com/Expensify/App/assets/136437976/870899f8-c928-4661-b4e6-d6d973f4c2ff)

Lastly, in the section of code related to handling the report action item press, adjustments are necessary to ensure that the component is unavailable to press when `props.transaction` is empty:
https://github.com/Expensify/App/blob/bb432aa6d787c6ba95faed521286cd169cbcade6/src/components/ReportActionItem/MoneyRequestPreview.js#L307-L309

```js
if (!props.onPreviewPressed || _.isEmpty(props.transaction)) {
  return childContainer;
}
```

#### Result

https://github.com/Expensify/App/assets/136437976/6ff6c830-aac7-4e20-97a3-82a05850f0a2


### What alternative solutions did you explore? (Optional)
N/A

**Comment by lschurr** [comment] 2023-09-25 00:29
Any update @aimane-chnaif?

**Comment by lschurr** [comment] 2023-09-27 06:50
Bumped in Slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1695790942443119

**Comment by paultsimura** [comment] 2023-09-28 10:07
@aimane-chnaif the root cause is different, it's a regression from https://github.com/Expensify/App/pull/25629
But in order to propose a solution I need to understand, what is the expected text to be displayed for such scenario?

**Comment by paultsimura** [comment] 2023-09-28 11:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After a split bill request is created in a group, the group's text in LHN shows "owes $0.00"

### What is the root cause of that problem?
The root cause lies here:

https://github.com/Expensify/App/blob/0c49b1198357f33f443543d6873badafd009b093/src/libs/OptionsListUtils.js#L392-L393

We are checking if the last report action is a money request action. However, we do not check if the report itself is an IOU report.

The group chat is not an IOU report, but the split action is the MoneyRequest action, therefore we proceed to calculate the last message as if the report was an IOU one.

### What changes do you think we should make in order to solve the problem?
We need to check if the report is an IOU report.

```diff
+} else if (ReportUtils.isIOUReport(report) && ReportActionUtils.isMoneyRequestAction(lastReportAction)) {
-} else if (ReportActionUtils.isMoneyRequestAction(lastReportAction)) {
```

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2023-09-28 11:26
@aimane-chnaif please see the proposal above and share your thoughts on the mentioned localization matters.

**Comment by lschurr** [comment] 2023-10-02 12:01
Bump @aimane-chnaif

**Comment by robertjchen** [comment] 2023-10-09 09:48
Would the LNH last message fix still be necessary if the backend is fixed? 🤔

**Comment by robertjchen** [comment] 2023-10-11 00:37
Got it, thanks for the review- let's move forward with @paultsimura's second proposal

**Comment by paultsimura** [comment] 2023-10-11 07:25
@robertjchen for some reason, the automation was not triggered after the assignment – could you please trigger it?

**Comment by lschurr** [comment] 2023-10-16 15:47
Any update @paultsimura?

**Comment by lschurr** [comment] 2023-10-23 15:44
@aimane-chnaif could you work through the checklist?

**Comment by lschurr** [comment] 2023-10-23 21:10
Payment summary:

- Bug reporter: @Mauri-salazar $50
- Contributor: @paultsimura $1500
- Contributor+: @aimane-chnaif $1500

**Comment by lschurr** [comment] 2023-10-23 21:12
This is done!

**Closed by lschurr** 2023-10-23 21:12 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
