### ISSUE TITLE
[HOLD for payment 2023-11-09] [HOLD for #24198] [$500]  Pressing Enter on the state search page submits the form instead of only selecting the state.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26345] opened 2023-08-30 21:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1-Go to settings -> workspaces -> your workspace -> add back 2- account -> connect manually.
3- Fill in the data.
4- Click on the "Connect" button.
5- Open the state search page.
6- Use the arrow keys to navigate to a state.
7- Press Enter.
## Expected Result: 
Pressing Enter should only select the state and return the user to the form.
## Actual Result: 
Pressing Enter selects the state and submits the form.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e01caeda-6273-4ce6-b44e-5cc7e484ad5c

https://github.com/Expensify/App/assets/43996225/27bbe4dd-c135-4d57-9780-b694d8d0a46c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmdshrif
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692629203062389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf4700c16d6a333f</li>
        <li>Upwork Job ID: 1699765868129120256</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-08-30 21:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
The form submit button in the CompanyStep component is receiving key press events even when the screen is not in focus.

### What changes do you think we should make in order to solve the problem?
Set the disablePressOnEnter prop on the form to true when isFocused for the page is false.

### What alternative solutions did you explore?
None.

**Comment by tamdao** [comment] 2023-08-30 23:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing Enter on the state search page submits the form instead of only selecting the state

### What is the root cause of that problem?
We have logic `onKeyDownCapture` to call `onSubmit` function when user type Enter key, but didn't check the input is belong form or not. So, any input event always calls `onSubmit` function if user type Enter and happen for all form has input not belong from.

In this case, the search input is not belonged to form, it uses for search state

https://github.com/Expensify/App/blob/a644050cde79ef995e69e1293bacdeb64bd566c5/src/components/FormSubmit/index.js#L14-L38

### What alternative solutions did you explore?

Update `childrenWrapperWithProps` in `Form` component to add `dataSet` when call `React.cloneElement` line 294
https://github.com/Expensify/App/blob/1b63c766095273dca5bce2fb876f12ebb6c67ad3/src/components/Form.js#L219-L357

like this:

```js
dataSet: {formInputId: inputID},
```

Update `BaseTextInput` to set `dataSet` line 350
https://github.com/Expensify/App/blob/1b63c766095273dca5bce2fb876f12ebb6c67ad3/src/components/TextInput/BaseTextInput.js#L350

```js
dataSet={{...props.dataSet, submitOnEnter: isMultiline && props.submitOnEnter}}
```
Update `AddressSearch` to set `props.dataSet` into `textInputProps`
https://github.com/Expensify/App/blob/1b63c766095273dca5bce2fb876f12ebb6c67ad3/src/components/AddressSearch/index.js#L301-L343

Update submitForm function in `FromSubmit` component to check the `formInputId` dataset
https://github.com/Expensify/App/blob/1b63c766095273dca5bce2fb876f12ebb6c67ad3/src/components/FormSubmit/index.js#L14-L38

like this

```js
...

if (event.shiftKey || event.key !== CONST.KEYBOARD_SHORTCUTS.ENTER.shortcutKey || isEnterWhileComposition(event)) { 
    return; 
} 

if (!lodashGet(event, 'target.dataset.formInputId')) {
    return;
}
...
```

**Comment by sonialiap** [comment] 2023-09-07 12:45
Triaging to external ⏭️

**Comment by edward-potter818** [comment] 2023-09-07 16:01
There should be listener what listens button actions.
When it listens Enter action of keyboard, it should check and validate, and next process will be submitting.
If you give me choice, I will fix it in this way.

**Comment by sicarius97** [comment] 2023-09-08 01:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing enter while in state selector submits the form rather than selecting the state of choice

### What is the root cause of that problem?
The state select dropdown doesn't lock the proper focus when open so actions that should occur inside the focus context of the dropdown instead happen outside of it, as is default behavior for forms, but not very good by accessibility standards

### What changes do you think we should make in order to solve the problem?
While some of the previously proposed solutions mentioned capturing the event and altering its logic to prevent the default behavior, I think it was being altered at the wrong level in the previous proposals in a way that was not as composable. There is already a component for capturing the focus of the arrow keys here:

https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/components/ArrowKeyFocusManager.js#L35

Which is used by multiple selects to capture the focus of the arrow keys. This component can be extended to also capture the focus of the 'ENTER' key stroke and would fix this problem for not only this selection box, but any future selection boxes as well, making it a more extensible solution than previous proposals

**Comment by sicarius97** [comment] 2023-09-08 01:58
Contributor details
Your Expensify account email: icroatt97@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01dbdc4055191721a0

**Comment by sonialiap** [comment] 2023-09-12 08:52
@sobitneupane what do you think of the existing proposal?

**Comment by sobitneupane** [comment] 2023-09-13 08:17
Thanks for the proposal everyone.

> This component can be extended to also capture the focus of the 'ENTER' key stroke

@sicarius97 Can you please share more details on proposal. How are you planning to extend the component to manage ENTER key?

**Comment by sonialiap** [comment] 2023-09-18 09:29
@sobitneupane looks like we got a new proposal 

@sicarius97 bump on the question from https://github.com/Expensify/App/issues/26345#issuecomment-1717161209

**Comment by sonialiap** [comment] 2023-09-20 10:30
@sobitneupane have you had a chance to review the new proposal? If you don't have time to work on this one I can reassign, let me know :)

**Comment by sobitneupane** [comment] 2023-09-21 07:13
> We can add the isFocused check as well to make sure the Form Enter Submit behavior is only triggered if the screen is currently focused.

@tienifr Can you explain more about above statement. I believe it should be enough to solve the issue.

**Comment by sonialiap** [comment] 2023-09-26 06:21
@tienifr bumping Sobit's question :) https://github.com/Expensify/App/issues/26345#issuecomment-1728985270

**Comment by sicarius97** [comment] 2023-09-30 22:32
@sonialiap Sorry I missed the notifications on your earlier questions, I can certainly elaborate on my earlier proposal and I think I found an easier solution that should still apply to any future selection lists like this in forms as well:

In this code here in the base selection list, we use the useKeyboardShortcut hook on ther `Enter` and `Ctrl+Enter` keypress events:

https://github.com/Expensify/App/blob/7c86d09a34c4104c8b4885899f29d5ec92d199c3/src/components/SelectionList/BaseSelectionList.js#L305-L316

If I'm not mistaken, preventing the default behavior by adding the below on this `BaseSelectionList` component should resolve the issue for not only this selection, but future ones built from it as well. It might be better to add that here instead of the ArrowFocusManager like I mentioned before as I am not sure if there are any components that adding such behavior might cause a regression within, so this would be a less invasive option as well for now. Solution:

`
    useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.ENTER, selectFocusedOption, {
        captureOnInputs: true,
        shouldBubble: () => !flattenedSections.allOptions[focusedIndex],
        isActive: !shouldDisableHotkeys && isFocused,
        shouldPreventDefault: true,
    });


    /** Calls confirm action when pressing CTRL (CMD) + Enter */
    useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.CTRL_ENTER, onConfirm, {
        captureOnInputs: true,
        shouldBubble: () => !flattenedSections.allOptions[focusedIndex],
        isActive: Boolean(onConfirm) && isFocused,
        shouldPreventDefault: true,
    });
`

**Comment by sonialiap** [comment] 2023-10-02 04:49
Thanks for the updates!

@sobitneupane what do you think of the above comments?

**Comment by sicarius97** [comment] 2023-10-03 00:35
@sonialiap @sobitneupane @aimane-chnaif After taking a look at it, I think the solution I presented would fix it for both issues and alleviate this for similar issues in the future as well.

**Comment by devrari** [comment] 2023-10-03 02:35
> Dupe of #24198 (same root cause)

I had proposed a solution for #24198  solves the issue in both the cases, 
@sicarius97 shouldPreventDefault will not fix the issue,
we need to introduce shouldStopPropagation key in shortcuts and make shouldStopPropagation value as true.
as I have mentioned the proposal https://github.com/Expensify/App/issues/24198#issuecomment-1676430016

**Comment by sobitneupane** [comment] 2023-10-04 07:40
https://github.com/Expensify/App/issues/26345#issuecomment-1742741375

@aimane-chnaif Should we merge these two issues?

**Comment by sobitneupane** [comment] 2023-10-04 11:46
@sonialiap We have [similar issue](https://github.com/Expensify/App/issues/24198) which might solve this as well. So, let's Hold this issue.

**Comment by sonialiap** [comment] 2023-10-05 05:12
Putting this on hold for https://github.com/Expensify/App/issues/24198

**Comment by sonialiap** [comment] 2023-10-13 09:10
Still on hold for https://github.com/Expensify/App/issues/24198

That issue isn't super close to being resolved and I'll be OOO until Oct 22 so I'm going to update this issue to "weekly" for now.

**Comment by sonialiap** [comment] 2023-11-09 12:34
This is Dupe. Resolved by https://github.com/Expensify/App/issues/24198

**Closed by sonialiap** 2023-11-09 12:34 UTC
Labels: Engineering, Daily, Internal, Overdue, Awaiting Payment, Bug
