### ISSUE TITLE
Screen transitions trigger an excessive number of react commits

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#28158] opened 2023-09-25 15:50 UTC
Coming from here: https://expensify.slack.com/archives/C05LX9D6E07/p1694783353289039 

# Problem

A number of screen transitions (we mainly looked at screens related to workspaces) trigger an excessive number of react commits.

In some scenarios we are seeing hundreds of commits (250+).The majority of these commits are due to subscriptions to onyx. 

# Solution

We should aim at having juts a few commits when a screen is being pushed (ideally just one commit).

Updates for components rendered in a single batch should also be triggered in a single batch and committed with a single commit. 

Figure out how to extend https://github.com/Expensify/react-native-onyx/pull/315 to web.

**Comment by palys-swm** [comment] 2023-09-29 14:21
We've checked how it performs now and it seems that the number of renders decreased by a lot. On iOS, about 15-20 commits are being performed, while on the web it is about 30 - a huge improvement! Most of the commits are unrelated to Onyx. We're still working on proposing a solution that can further decrease the number of them.

At this point, the delay in displaying the workspaces list on iOS is mostly caused by rendering a list of `MenuItem`s which are really expensive (`WorkspacesListPage` renders each `MenuItem` at least twice. The most expensive render of a single item can take up to 7ms.). This probably should be tracked as a separate issue.

**Comment by sebryu** [comment] 2023-10-27 11:12
Hey. I've been working on multiple performance issues, and while they were not only related to screen transition, they help with rendering of both left navbar & report screen itself.

1. Optimize components using report with hasDraft - https://github.com/Expensify/App/pull/30031
2. Ongoing optimization for `personalDetailsList` - https://github.com/Expensify/App/pull/30333

When the second would be merged I can make screen transition profiling once more (that could increase number of react commits but they would be much shorter).

Re. proposed solution
> Figure out how to extend https://github.com/Expensify/react-native-onyx/pull/315 to web.
I believe that onyx change is already used by the web app for some time, so it could also have positive impact on performance.

**Comment by mountiny** [comment] 2023-10-30 11:04
I think we can close this catch all issue as we have made some improvements already and we can focus on new improvements in more directed/ specific problem/ solution issues

**Closed by mountiny** 2023-10-30 11:04 UTC
Labels: Monthly
