### ISSUE TITLE
[HOLD for payment 2024-04-25] [$250] [HOLD for payment 2024-04-17] [Android] VisionCamera not displaying when permission first given

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#38796] opened 2024-03-22 10:11 UTC
### Problem

When first approving the camera permission, the camera doesn't display:

- Create a non-scan money request to someone
- Remove camera permissions
- Kill and reopen app
- Tap request money
- Try to scan receipt
- Permission prompt is shown
- Choose 'Just this time'
- Camera view remains black
- Close the page, then reopen it
- Camera view works as expected

_We're resolving this seperately as discussed [here](https://github.com/Expensify/App/pull/37483#issuecomment-2013009107)._

https://github.com/Expensify/App/assets/10736861/96746d6b-36a9-4f37-ba98-5bb54be5780a

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf28de4f7cebf39a</li>
        <li>Upwork Job ID: 1779703287335849984</li>
        <li>Last Price Increase: 2024-04-15</li>
    </ul>
</details>

**Comment by mrousavy** [comment] 2024-03-25 09:36
👋

**Comment by greg-schroeder** [comment] 2024-03-25 11:27
Hey @Julesssss this will be `Internal` right? Or handled by an agency?

**Comment by Julesssss** [comment] 2024-03-26 09:43
@mrousavy from Margelo is handling this one for, so it's external but not open to contributors

**Comment by greg-schroeder** [comment] 2024-03-26 22:46
Based on roadmap I would guess #wave-collect makes the most sense

**Comment by greg-schroeder** [comment] 2024-04-03 09:25
Assigning @mrousavy per https://github.com/Expensify/App/issues/38796#issuecomment-2019958882

**Comment by mrousavy** [comment] 2024-04-03 11:42
Isn't this a duplicate of https://github.com/Expensify/App/issues/39043?

**Comment by Julesssss** [comment] 2024-04-03 12:27
Thanks I closed the other one

**Comment by chrispader** [comment] 2024-04-04 13:10
The problem here, is that `useTabNavigatorFocus()` gives us a current `tabIndex` of 0 instead of 1 once we render the `NavigationAwareCamera`. Because it is 0 and not 1, `isCameraActive` will be false and therefore the camera will not be activated. 
https://github.com/Expensify/App/blob/e4eead376187181ed5e7d22fad866f05a6dd09aa/src/pages/iou/request/step/IOURequestStepScan/NavigationAwareCamera/index.native.js#L13

I suppose, the reason for this is that because we just requested camera permissions, which opens up the system Android dialog, the logic in `@react-navigation/material-top-tabs` will not calculate the correct `position` somewhere in this file/package: https://github.com/react-navigation/react-navigation/blob/main/packages/react-native-tab-view/src/PanResponderAdapter.tsx

I will try to update the `react-navigation` patch later today. A dirty hack to fix this in the Expensify codebase would be to just programmatically "swipe" between the tabs by like 1px. This will trigger the logic again and the `tabIndex` will be updated.

**Comment by greg-schroeder** [comment] 2024-04-05 21:36
Pending @mrousavy's progress here

**Comment by chrispader** [comment] 2024-04-08 17:00
i'm currently working on this issue. will try to finish it today!

**Comment by chrispader** [comment] 2024-04-08 19:18
@neil-marcellini added a fixing PR for this bug here: https://github.com/Expensify/App/pull/39854

This PR adds a patch for `react-native-tab-view`, though we might want to ask the guys from Callstack to fix this upstream soon.

**Comment by Julesssss** [comment] 2024-04-10 08:50
Hey @greg-schroeder, this wasn't linked correctly but lets handle payment for https://github.com/Expensify/App/pull/39854 here

**Comment by Julesssss** [comment] 2024-04-11 16:59
Awaiting payment next week

**Comment by greg-schroeder** [comment] 2024-04-15 02:48
Adding `External` to create an upwork job

**Comment by greg-schroeder** [comment] 2024-04-15 02:48
Offer sent to @DylanDylann for the C+ role

**Comment by DylanDylann** [comment] 2024-04-15 14:12
@greg-schroeder As [this announcement](https://expensify.slack.com/archives/C01GTK53T8Q/p1712256409152489)

> Any issues created before this date will maintain their original stated price.

Should we update the original price of this issue to $500?

**Comment by greg-schroeder** [comment] 2024-04-15 14:19
You can just accept the offer, I'll pay an extra $250 as a bonus on 4/17

**Comment by DylanDylann** [comment] 2024-04-15 14:54
@greg-schroeder accepted. Thanks

**Comment by greg-schroeder** [comment] 2024-04-18 06:13
Paid

**Closed by greg-schroeder** 2024-04-18 06:13 UTC
Labels: External, Weekly, Awaiting Payment, Bug
