### ISSUE TITLE
Xero -"manually exported" message only appears after revisting export and it is missing "Xero"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45594] opened 2024-07-17 11:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/44170
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Admin and employee are in the same workspace.
- Workspace is connected to Xero.

1. Go to staging.new.expensify.com
2. [Employee] Submit an expense in the workspace chat.
3. [Admin] Go to workspace chat with employee.
4. [Admin] Click on the expense preview.
5. [Admin] Pay elsewhere the report.
6. [Admin] Click "Mark manually as entered" button.

## Expected Result:
- "manually exported" system message will show up in report without revisiting the report.
- "manually exported" system message will be complete.

## Actual Result:
- "manually exported" system message only shows up in report after revisiting the report.
- "marked this report as manually exported to " system message is missing "Xero".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4101ce9f-982b-4845-a765-876a1f2d0fd8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-07-17 11:48
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-07-17 11:48
Production
![Screenshot 2024-07-17 144239](https://github.com/user-attachments/assets/3a335dde-4004-46b0-a507-7eefad5feec3)

**Comment by MariaHCD** [comment] 2024-07-17 12:19
Hmm, looks like we noticed that the name of the platform is missing before we merged the PR: https://github.com/Expensify/App/pull/44170#issuecomment-2231207674

But we can potentially ignore this for now? https://github.com/Expensify/App/pull/44170#issuecomment-2226582104

cc: @arosiclair @francoisl

**Comment by kosmydel** [comment] 2024-07-17 12:37
I think we can ignore it for now. It was noticed [here](https://github.com/Expensify/App/pull/44170#issuecomment-2231265987), and we have decided that the issue is the backend side [here](https://github.com/Expensify/App/pull/44170#issuecomment-2231297888).

**Comment by MariaHCD** [comment] 2024-07-17 13:08
Cool, this doesn't need to block the deploy, then.

@arosiclair @francoisl Do we have an issue to track the BE fix?

**Comment by arosiclair** [comment] 2024-07-17 14:31
> @arosiclair @francoisl Do we have an issue to track the BE fix?

I don't think so. Let's use this one to track it. I'll take over cc @lakchote as well

**Comment by arosiclair** [comment] 2024-07-17 14:56
Alright this is happening because I forgot to add `EXPORTINTEGRATION` to our list of actions we queue onyx updates for [here](https://github.com/Expensify/Auth/blob/cb7cd14ff914279110e2dd6cf187e79e4e8f611f/auth/lib/ReportAction.cpp#L2368). I'll post a PR to fix that

**Comment by arosiclair** [comment] 2024-07-22 13:59
PR hit prod [last week](https://github.com/Expensify/Auth/pull/11681#issuecomment-2237259021). This is all set.

**Closed by arosiclair** 2024-07-22 13:59 UTC
Labels: Engineering, Daily, Overdue, Bug
