### ISSUE TITLE
[$1000] Chat - Outdated message " Send money" displayed at the top of the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22940] opened 2023-07-15 14:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to http://staging.new.expensify.com/
2. Tap on any conversation

## Expected Result:
Outdated message should not be displayed

## Actual Result:
Outdated message "use of plus button to send Or request money" is displayed at the top of the page. Send money option removed from plus icon. But still outdated message " Send" appears on top

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.41.2
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6129022_Screenshot_2023-07-15-16-15-40-001-edit_com android chrome](https://github.com/Expensify/App/assets/78819774/7130966d-00d3-470d-8e1a-b766bba48321)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b5519d452919e75</li>
        <li>Upwork Job ID: 1683526608875266048</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-07-21 20:51
bump!

**Comment by lanitochka17** [comment] 2023-07-21 21:19
@johncschuster Send Money is now officially removed from the front-end.

**Comment by johncschuster** [comment] 2023-07-24 17:16
Thanks, everyone for flagging that! I couldn't recall that `Send Money` was being removed. For my notes, here's the [GH](https://github.com/Expensify/App/issues/21233) where we proposed to make that change

**Comment by ishpaul777** [comment] 2023-07-24 17:44
This is dupe of #19828.
Fixed here- #23248

**Comment by johncschuster** [comment] 2023-07-27 18:36
Ah, I missed that. Thanks!

**Closed** 2023-07-27 18:36 UTC
Labels: External, Daily, Help Wanted, Bug
