### ISSUE TITLE
[HOLD for payment 2024-07-26] [$250] mWeb splash screen displays the iconmark logo at a very small size

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44624] opened 2024-06-28 14:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719557303345799

## Action Performed:
1. Go to staging.new.expensify.com and refresh the page
2. Login and refresh the page
## Expected Result:
Splash screen icon mark logo should be same across all platform
## Actual Result:
mWeb splash screen displays the iconmark logo at a very small size when compared with native app
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/Expensify/App/assets/38435837/7dc709d9-c872-4e12-842b-b1039222625e" width="40%" height="40%">
<img src="https://github.com/Expensify/App/assets/38435837/b1d43f68-0d99-459a-9c18-60a2981e250d" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/38435837/eceff8dc-b015-423f-b983-62abcc5b7c25" width="40%" height="40%">
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a88bc54afc480cd3</li>
        <li>Upwork Job ID: 1807909799628982429</li>
        <li>Last Price Increase: 2024-07-01</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 103095834</li>
<li>ShridharGoel | Contributor | 103095836</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by shawnborton** [comment] 2024-06-28 14:55
I kind of think the best solution is to just get rid of any mobile-only styles here and just use the same thing we use on desktop.

**Comment by neonbhai** [comment] 2024-06-28 15:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb splash screen displays the iconmark logo at a very small size 

### What is the root cause of that problem?
We have different svg sizes defined for small screens here

https://github.com/Expensify/App/blob/937c4186409725b57fdaae6ae8e1d8c85a9d52a0/web/index.html#L91-L96


### What changes do you think we should make in order to solve the problem?
We should have the same logo size for all devices, we will:

Remove the width limit for the desktop size svg style here:
https://github.com/Expensify/App/blob/937c4186409725b57fdaae6ae8e1d8c85a9d52a0/web/index.html#L84-L89


Remove the mobile size svg style here:
https://github.com/Expensify/App/blob/937c4186409725b57fdaae6ae8e1d8c85a9d52a0/web/index.html#L91

**Comment by adelekennedy** [comment] 2024-07-01 22:51
made external - let's goooo

**Comment by huult** [comment] 2024-07-02 17:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

 mWeb splash screen displays the iconmark logo at a very small size

### What is the root cause of that problem?
The iconmark logo appears very small because the width (52px) and height (52px) values set in the media query for screens with a max-width of 479px.
https://github.com/Expensify/App/blob/937c4186409725b57fdaae6ae8e1d8c85a9d52a0/web/index.html#L91-L96

### What changes do you think we should make in order to solve the problem?
The iconmark logo should resize with each screen to avoid the iconmark logo being too big or too small.
```diff

// App/blob/main/web/index.html#L90
@@ -1,6 +1,10 @@
+.splash-logo {
+   position: absolute;
+   left: 50%;
+   top: 50%;
+   transform: translate(-50%, -50%);
+   text-align: center;
+}

// App/blob/main/web/index.html#L91
@media screen and (max-width: 479px) {
   .splash-logo > svg {
-    width: 52px;
+    width: 50%;
-    height: 52px;
+    height: 50%;
+    max-width: 208px;
   }
 }

```
<details>
<summary>POC</summary>

https://github.com/Expensify/App/assets/20178761/aeeafa5c-afca-4841-8e7d-e2942d488de6

</details>

### What alternative solutions did you explore? (Optional)

**Comment by Mmore35** [comment] 2024-07-03 02:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

splash screen displays the iconmark logo at a very small size

### What is the root cause of that problem?

These two styles change the size of the icon based on screen size. The icon's size should be constant for any screen size.

https://github.com/Expensify/App/blob/937c4186409725b57fdaae6ae8e1d8c85a9d52a0/web/index.html#L84-L96 

### What changes do you think we should make in order to solve the problem?

These two styles should be removed and replaced with one style that covers all screen sizes. This change will address this bug and ensure a consistent UX going forward.

Remove lines 84-96 and replace it with:
``` 
//App/web/index.html#L84
.splash-logo > svg {
                width: 104px;
                height: 104px;
}
```

**Comment by Mmore35** [comment] 2024-07-03 02:39
Contributor details
Your Expensify account email: michaela.coding@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a38afc4ef2929c42

**Comment by ahmedGaber93** [comment] 2024-07-03 16:53
@ShridharGoel's [proposal](https://github.com/Expensify/App/issues/44624#issuecomment-2197115250) LGTM!

🎀 👀 🎀 C+ reviewed

**Comment by ahmedGaber93** [comment] 2024-07-04 01:37
I don't think we need to make it resizable based on screen dimensions like what we do in medium and large screen on web, the icon size is fixed, and the green background fit the screen

**Comment by huult** [comment] 2024-07-04 15:42
While a fixed solution might be okay, I believe a responsive icon mark logo will improve the user experience, making it feel more like a native platform.

**Comment by shawnborton** [comment] 2024-07-04 15:43
I really don't think we need multiple sizes for this. I think the size we already use on desktop/web will look great on mobile, and this way we don't need to maintain multiple sizes across devices.

**Comment by ahmedGaber93** [comment] 2024-07-09 05:40
@grgia bump for assignment

**Comment by ahmedGaber93** [comment] 2024-07-15 08:42
@ShridharGoel please let me know when PR is ready

**Comment by adelekennedy** [comment] 2024-07-19 23:09
payment due next week - @ahmedGaber93 will you fill out the checklist when you have a moment?

**Comment by ahmedGaber93** [comment] 2024-07-23 07:53
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/17477 
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **No need this is a design change, not a bug**
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug. No
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

This a small change in the icon size. I think no need for regression test.

**Closed** 2024-07-28 19:01 UTC
Labels: External, Daily, Awaiting Payment, Bug
