### ISSUE TITLE
Task - Ones opened task conv in Focus mode is not displayed in LHN anymore

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24158] opened 2023-08-04 12:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to account A and create a task
2. Assign to account B
3. Login to account B
4. Change to focus mode
5. Open the Task conversation
6. Navigate back to LHN

## Expected Result:
When navigate back to LHN the Task should be still displaying in LHN

## Actual Result:
Ones opened task conv in Focus mode is not displayed in LHN anymore

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c2a956ca-3066-41dc-ae52-989c0273575a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2023-08-07 13:49
Agree with dupe of https://github.com/Expensify/App/issues/23309, thanks @hoangzinh

**Closed by conorpendergrast** 2023-08-07 13:49 UTC
Labels: Daily, Overdue, Bug
