### ISSUE TITLE
[$1000] App loses focus from concierge compose box when visiting concierge chat after connect bank step 3

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22664] opened 2023-07-11 18:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces-> any workspace-> bank account-> connect manually->fill in step 1, step 2, step 3 details and continue
4. On passport page, click on question mark icon in header
5. Click on chat with concierge and observe that app does not focus on compose box
6. Open any other report and observe that app does not focus on any  compose box anymore
## Expected Result: 
App should focus on compose box of concierge chat if we visit the chat from 'Chat with concierge' option from workspace help
## Actual Result: 
App does not focus on compose box of concierge chat if we visit the chat from 'Chat with concierge' option from workspace help after step 3 of connect bank account

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/34eea125-89ab-4496-aed8-3bb8eb0d7589

https://github.com/Expensify/App/assets/43996225/cfbe8428-6d13-453f-a1a0-5642ccda6234

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688575084802769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ecac728c74967838</li>
        <li>Upwork Job ID: 1678833945930260480</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-07-11 18:29
I think that this happens anytime you click on an in-app link directing you to Concierge, since I was able to reproduce this by going to Settings > Account > Report a bug.

**Comment by jeet-dhandha** [comment] 2023-07-11 20:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The composer is not getting focused when navigating to Concierge Page.

Basic Steps:
1. Open any other chat then Concierge. 
2. Open Profile Page. From pressing on loggedin user's avatar.
3. Go to About Page.
4. Press on Report a Bag.

### What is the root cause of that problem?
- I found that the issue is that the AuthScreens is not updating properly and thus `focus` screenListener of RightModalNavigator is called again. And thus `modal.isVisible` is set to `true` in ONYX.

### What changes do you think we should make in order to solve the problem?
- We can handle this issue by adding `Navigation.dismissModal()` at start of `navigateToConciergeChat` to dismiss the modal if it is visible again due to when `modal.isVisible` is set to `true`.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by abdulrahuman5196** [comment] 2023-07-14 14:09
Will review this in my morning

**Comment by abdulrahuman5196** [comment] 2023-07-15 18:52
There is something fundamental wrong with this `modal.isVisible` property. We can reproduce the issue just by,
1) open settings
2) close the tab without closing the modal
3) reopen the app url in another tab
This issue will happen.


@ginsuma / @Nodebrute / @jeet-dhandha Only calling `Navigation.dismissModal()` in different ways will not solve this issue completely.

**Comment by sakluger** [comment] 2023-07-17 21:39
Not overdue melvin, we're just back from the weekend.

**Comment by abdulrahuman5196** [comment] 2023-07-20 16:01
@sakluger There hasn't been any proposals we have made suitable to approve yet. I think we should increase this bounty.

**Comment by abdulrahuman5196** [comment] 2023-07-21 16:06
Thanks for the reference @Nodebrute 

@sakluger It seems we have a tracking issue for these composer focus kind of issues - https://github.com/Expensify/App/issues/15992

**Comment by sakluger** [comment] 2023-07-25 01:11
Good find! I'll leave this open until we hear back from @bondydaa whether this should be included in that tracking issue or not.

**Comment by bondydaa** [comment] 2023-07-26 21:29
throw whatever you want on that tracking issue that's what it's for. no one is assigned to it though so not much is going to get done with it until someone picks it up.

**Comment by sakluger** [comment] 2023-07-27 23:19
I added this to the list of related issues on the tracking issue, let's close for now since this will eventually be fixed there.

**Closed by sakluger** 2023-07-27 23:19 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
