### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Start chat - Chat RHP switches to Room tab when dragging input from right to left

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38177] opened 2024-03-12 20:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** y
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**. N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to FAB > Start chat > # Room.
3. Type anything in the **Room description** field.
4. Drag the input from left to right.

## Expected Result:
RHP will not switch to Room tab.

## Actual Result:
RHP switches to Room tab when dragging input from right to left.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/85894871/9c1085fa-bc34-426b-ae08-74a2b0e7e237

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0180bfc4bd0da32526</li>
        <li>Upwork Job ID: 1767678074407985152</li>
        <li>Last Price Increase: 2024-03-27</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-03-12 20:40
@Christinadobrzyn FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment] 2024-03-12 20:40
We think that this bug might be related to #vip-vsb
cc @quinthar

**Comment by francoisl** [comment] 2024-03-12 21:10
Yep, tested a revert of that PR locally and it fixes the regression. There's already a revert PR [here](https://github.com/Expensify/App/pull/38182).

**Comment by francoisl** [comment] 2024-03-12 22:22
Ah ok, in this case I agree it would make sense to treat this as a regular bug and fix it. I'll update the issue description and open this as External so we can formally review your proposal.

**Comment by luacmartins** [comment] 2024-03-12 22:48
This is fixed in staging. Closing!

**Comment by francoisl** [comment] 2024-03-12 22:51
Reopening as the but somewhat exists on production too, and we can fix it.

**Comment by Santhosh-Sellavel** [comment] 2024-03-13 17:55
@Krishna2323 Your proposal looks good!

> We should also check if this occurs somewhere else.

Can you come up with places where changes might be required?

> Add shouldInterceptSwipe to Input as default.

Also, this seems like a good option, should find why is there any reason, why it was not added initially

**Comment by Santhosh-Sellavel** [comment] 2024-03-13 18:16
> @Santhosh-Sellavel, I checked that we don't need to update it anywhere else, `OnyxTabNavigator` is used in `IOURequestStartPage` & `NewChatSelectorPage` and all inputs in uses `shouldInterceptSwipe` except the `roomDescription`.

That's good

> Adding shouldInterceptSwipe prop to Input as default seems better option to me also since we generally don't want to make inputs swipeable.

Agree, it makes sense. We need to be sure, as we see this seems straightforward then why it was given `false` as default, so Can you spot the PR where the prop was introduced let's check with them

**Comment by Christinadobrzyn** [comment] 2024-03-14 01:26
@luacmartins @francoisl @Santhosh-Sellavel 

Should this be paid out? Or is this a regression from something?

**Comment by luacmartins** [comment] 2024-03-14 01:37
This was a regression

**Comment by Christinadobrzyn** [comment] 2024-03-14 06:52
Okay thanks! I think this can be closed unless we want to write up a regression test for it?

**Comment by luacmartins** [comment] 2024-03-14 17:28
Yea, we can close this one!

**Comment by Santhosh-Sellavel** [comment] 2024-03-25 18:07
@Krishna2323 Can you start a slack thread on the expensify-bugs channel and tag them closed PR notifications might be missed.
If we don't get any response lets go with your plan, thanks!

**Comment by Christinadobrzyn** [comment] 2024-03-26 00:51
Talking this over with @Santhosh-Sellavel I updated the Title of the GH because this is a regression. I believe the regression is being worked on here - https://github.com/Expensify/App/pull/28240/files?diff=split&w=0#r1528738754

**Comment by Santhosh-Sellavel** [comment] 2024-03-28 15:18
@Krishna2323 Have you started the thread is there a link?

**Comment by Santhosh-Sellavel** [comment] 2024-03-29 16:04
@francoisl 

@Krishna2323's [proposal](https://github.com/Expensify/App/issues/38177#issuecomment-1992552072) looks good. It's simple enough just add on `shouldInterceptSwipe` the affected pages rather making the `shouldInterceptSwipe`. What is your thoughts?

**Comment by francoisl** [comment] 2024-03-29 19:09
Ok yes, I just double-checked the issue is still reproducible on staging. The proposal makes sense, let's go ahead with it.

**Comment by Christinadobrzyn** [comment] 2024-04-11 03:31
Payouts due:

- [ ] Contributor: $500 @Krishna2323 (Upwork offer - https://www.upwork.com/nx/wm/workroom/36827535/overview)
- [ ] Contributor+: $500 @Santhosh-Sellavel (payment through NewDot)

Upwork job is [here](https://www.upwork.com/jobs/~0180bfc4bd0da32526).

@Santhosh-Sellavel Do we need a regression test for this?

**Comment by Santhosh-Sellavel** [comment] 2024-04-13 18:45
No, we would not need a regression test here. This is not something important & its a minor UX polish

**Comment by Santhosh-Sellavel** [comment] 2024-04-13 18:46
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR:
> * [ ]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [ ]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [ ]  [@Christinadobrzyn] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by Christinadobrzyn** [comment] 2024-04-16 05:11
This is good to close - payment summary here - https://github.com/Expensify/App/issues/38177#issuecomment-2048869465

**Closed by Christinadobrzyn** 2024-04-16 05:12 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by Santhosh-Sellavel** [comment] 2024-05-22 18:06
Requested on ND

**Comment by JmillsExpensify** [comment] 2024-05-31 04:30
$500 approved for @Santhosh-Sellavel
