### ISSUE TITLE
[HOLD for Payment 2024-09-17] [$250] Multi tags - "Required" switch is enabled after disabling all subtags & reopening subtag list

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47818] opened 2024-08-21 20:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4880485
**Email or phone of affected tester (no customers):**  applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has independant tags set up on OD.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Tags.
3. Click on any main tag.
4. Enable "Required" switch.
5. Select all the subtags > Disable.
6. Disable all the subtags.
7. Note that "Required" switch is locked and disabled.
8. Dismiss the RHP.
9. Click on the same main tag.

## Expected Result:
"Required" switch will remain locked and disabled.

## Actual Result:
Required" switch is enabled after disabling all subtags & reopening subtag list.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6bed2f7d-bc66-4c8b-95f6-ff1e9d1d5715

[Bug6578591_1724267622842!Independent.-.Multi.Level.tags.csv](https://github.com/user-attachments/files/16698507/Bug6578591_1724267622842.Independent.-.Multi.Level.tags.csv)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135a412ea484831b7</li>
        <li>Upwork Job ID: 1826359908145270693</li>
        <li>Last Price Increase: 2024-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103741874</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by IuliiaHerets** [comment] 2024-08-21 20:37
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Shahidullah-Muffakir** [comment] 2024-08-22 02:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When all subtags are disabled, the "required" toggle should be toggled off, but it is currently showing as toggled on.

### What is the root cause of that problem?
In the optimistic state of the data, if all tags are disabled, the required property for the subfields should be a boolean true or false. However, it is currently set to the string "Update" which causes an error.
[[App/src/libs/actions/Policy/Tag.ts]](https://github.com/Expensify/App/blob/12037eef23dfb54b73d05ea28bd0b7334a7ca153/src/libs/actions/Policy/Tag.ts#L731)
[]((https://github.com/Expensify/App/blob/12037eef23dfb54b73d05ea28bd0b7334a7ca153/src/libs/actions/Policy/Tag.ts#L764-L769))
>

```
 optimisticData: [
            {
                onyxMethod: Onyx.METHOD.MERGE,
                key: `${ONYXKEYS.COLLECTION.POLICY_TAGS}${policyID}`,
                value: {
                    [policyTag.name]: {
                        ...(shouldDisableRequiredTag ? {required: false, pendingFields: {required: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE}} : {}),
                        tags: optimisticPolicyTagsData,
                    },
                },
            },
        ],
```

### What changes do you think we should make in order to solve the problem?
Instead of setting the required value to the string "Update", set it to false when all subtags are disabled.
```
optimisticData: [
            {
                onyxMethod: Onyx.METHOD.MERGE,
                key: `${ONYXKEYS.COLLECTION.POLICY_TAGS}${policyID}`,
                value: {
                    [policyTag.name]: {
                        ...(shouldDisableRequiredTag ? {required: false, pendingFields: {required: false} : {}),
                        tags: optimisticPolicyTagsData,
                    },
                },
            },
        ],


```

**Comment by Shahidullah-Muffakir** [comment] 2024-08-22 04:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When all subtags are disabled, the "Required" toggle should be toggled off. However, it is currently showing as toggled on, which creates confusion for users.

### What is the root cause of that problem?
Currently, the "Required" state is only updated when the user manually toggles the Required Toggle. The setPolicyTagsRequired function is invoked solely when the user interacts with the toggle. Consequently, when all subtags are disabled, this function is not called, resulting in the "Required" toggle remaining on. To update the "Required" state correctly, we should call this function whenever getHeaderButtons is executed. If the number of enabled tags is zero, the required button should be turned off.

### What changes do you think we should make in order to solve the problem?
To address this issue, we can implement a check to see if any tags are enabled. If not, we should call the setPolicyTagsRequired function to turn off the required toggle. The suggested code change is as follows:

        if (!Object.values(currentPolicyTag?.tags ?? {}).some((tag) => tag.enabled)) {
            Tag.setPolicyTagsRequired(policyID, false, route.params.orderWeight)
        }
        
 Here is the video afterMy Updates:
https://github.com/user-attachments/assets/ad799020-db34-4c13-9ac5-65581db542c5

**Comment by nkdengineer** [comment] 2024-08-22 10:06
I think this is a BE bug since we can calculate `required` value via `tagListIndex` and `tags` data as we do in optimistic data.

**Comment by struc** [comment] 2024-08-22 13:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Disabling all subtags (individually or in bulk) should make the main tag not required.

### What is the root cause of that problem?
We should update the required attribute on the main tag, if all the subtags are disabled but we are not.

### What changes do you think we should make in order to solve the problem?
I think the simplest solution is to just make a call to `setPolicyTagsRequired` when all the subtags are disabled.
This should also handle the case when the user disable the subtags one by one.

So write after
https://github.com/Expensify/App/blob/12037eef23dfb54b73d05ea28bd0b7334a7ca153/src/libs/actions/Policy/Tag.ts#L286

We can check if the tag should marked as not required, we can call this:

```typescript
    if (shouldDisableRequiredTag) {
        setPolicyTagsRequired(policyID, false, tagListIndex);
    }

```

### What alternative solutions did you explore? (Optional)
Handle this situation on the backed.

**Comment by struc** [comment] 2024-08-22 13:50
Contributor details
Your Expensify account email: m.elsayed.a@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b7e0705471825edf

**Comment by ikevin127** [comment] 2024-08-22 20:20
♻️ Reviewing proposals.

**Comment by ikevin127** [comment] 2024-08-23 02:27
✅ **I've reviewed the existing proposals and we have the following two acceptable options:**
1. @Krishna2323's [proposal](https://github.com/Expensify/App/issues/47818#issuecomment-2303004480) which proposes as solution to fix this from the BE side, since the FE already sends all the required parameters. The proposal was reinforced by another contributor in [#47818 (comment)](https://github.com/Expensify/App/issues/47818#issuecomment-2304278094).
2. @Shahidullah-Muffakir's [proposal](https://github.com/Expensify/App/issues/47818#issuecomment-2303697848) which proposes as solution to fix this from the FE side such that if all sub-tags are disabled, we should have a check in the FE which would set `Required` as disabled and locked.

### I need some help from the assigned CME here to decide the final way to go, I tend to lean towards the first proposal as the right way to do this.

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment] 2024-08-23 02:31
@struc Thanks for your [proposal](https://github.com/Expensify/App/issues/47818#issuecomment-2304726028). Unfortunately we're generally are not in favour of having separate calls as a result of one call which already sends all the required parameters needed in order to fix this issue from the BE side as mentioned in https://github.com/Expensify/App/issues/47818#issuecomment-2304278094.

**Comment by ikevin127** [comment] 2024-08-26 19:26
@puneetlath Callback to https://github.com/Expensify/App/issues/47818#issuecomment-2306068470, we need to decide which way to go with this issue.

**Comment by puneetlath** [comment] 2024-08-29 21:35
I think I prefer the front-end solution. Let's go with that.

**Comment by ikevin127** [comment] 2024-08-29 23:49
♻️ I'm fine with CME's decision, if we encounter issues with the selected solution and we do need to have BE changes I'm sure we will sort things out here on the issue such that everybody is compensated fairily.

##

@Shahidullah-Muffakir Please us know when we can expect a PR to be ready for review 🧑‍💻

**Comment by Shahidullah-Muffakir** [comment] 2024-08-29 23:53
Thank you, I will submit the PR within 24 hours.

**Comment by garrettmknight** [comment] 2024-09-06 17:22
@puneetlath / @ikevin127 might have a regression [here](https://github.com/Expensify/App/issues/48683)

**Comment by puneetlath** [comment] 2024-09-06 17:27
@Shahidullah-Muffakir can you take a look?

**Comment by ikevin127** [comment] 2024-09-06 17:28
@Shahidullah-Muffakir Can you please look into the regression issue and if it indeed comes from our PR, you'd need to have a follow-up PR to fix the regression. Thanks in advance!

**Comment by Shahidullah-Muffakir** [comment] 2024-09-06 17:29
@puneetlath @ikevin127 checking it out now.

**Comment by Shahidullah-Muffakir** [comment] 2024-09-06 18:11
@puneetlath @ikevin127

To hide the "**Required**" label when all tags are disabled, we should implement a similar check to what we applied for the Required toggle. The current check only verifies if the policyTagList is required, but it doesn't account for the scenario where all subtags are disabled

in this :
https://github.com/Expensify/App/blob/7dc25152d1595b7e58013de679fe26a7aa1634bd/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L103
We can update the logic as follows:
`labelText={policyTagList.required && !!Object.values(policyTagList?.tags ?? {}).some((tag) => tag.enabled) ? translate('common.required') : undefined}
`
This way, the label will only appear if the main tag is required and at least one subtag is enabled.


Additionally, I'm not sure if this issue is a regression—it seems more like a separate bug that was overlooked in the previous implementation.

**Comment by Shahidullah-Muffakir** [comment] 2024-09-06 18:16
https://github.com/user-attachments/assets/6c12924a-20ae-4a1f-ba0b-9b74516f75b1

**Comment by Shahidullah-Muffakir** [comment] 2024-09-06 18:28
@ikevin127 Could you guide me on the process for submitting a fix? Should I go ahead and create a PR directly, or is there anything else I need to do before proceeding? Thank you.

**Comment by ikevin127** [comment] 2024-09-06 18:49
@Shahidullah-Muffakir Sure, you can go ahead and open a follow-up PR, tagging the other issue in the FIXED ISSUE section and leave blank for proposal - anything else is the same as any other PR.

You can also post in the other issue once you opened the PR to let people know that you opened PR with a fix as a follow-up. 

Whether the issue was caused by your initial PR or not, we will determine soon and depending on the result we both will either have a penalty here (-50%) if it was indeed caused by the initial PR or possibly no penalty and a separate bounty for the other issue if it was indeed present before the initial changes.

**Comment by Shahidullah-Muffakir** [comment] 2024-09-06 18:57
Thanks for the clarification, @ikevin127! I’ve already opened the follow-up PR and tagged the other issue.

I hope this issue wasn’t caused by my initial PR and that it doesn’t lead to a penalty. :)
Thanks again for your help!

**Comment by ikevin127** [comment] 2024-09-06 19:42
> Additionally, I'm not sure if this issue is a regression—it seems more like a separate bug that was overlooked in the previous implementation.

Regarding the regression, just looked into whether the issue exists on production where the PR was not deployed yet and it looks like it does, meaning the bug was indeed overlooked in a previous implementation (see video below).

The reason it surfaced now is because we fixed the issue of `Required` staying OFF and Locked and not going back to being ON after the RHP is re-opened. Whether this should be considered regression or not, I'll defer that to @puneetlath.

https://github.com/user-attachments/assets/f3ac9b51-b468-4fb0-8615-c92c1da04f40

**Comment by puneetlath** [comment] 2024-09-06 19:46
Doesn't sound like a regression to me.

**Comment by ikevin127** [comment] 2024-09-12 21:27
⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-06-16]** according to 3 days ago production deploy from https://github.com/Expensify/App/issues/48664#issuecomment-2338463845 (the PR is part of the deploy checklist).

cc @puneetlath

**Comment by puneetlath** [comment] 2024-09-13 01:46
Updated the title. I'm a BZ member so I can handle payment. (I'm a bit different than most in that I'm both on the BZ team and on the engineering team).

**Comment by ikevin127** [comment] 2024-09-18 22:53
cc @puneetlath

**Comment by puneetlath** [comment] 2024-09-19 21:17
@ikevin127 can you complete the checklist?

**Comment by ikevin127** [comment] 2024-09-19 21:38
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/43769
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/43769#issuecomment-2362246763
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Go to Workspace Settings > Tags.
2. Click on any main tag to open its settings.
3. Enable the "Required" switch by toggling it on.
4. Select all the subtags associated with the main tag.
5. Disable all the selected subtags.
6. Verify that the "Required" switch becomes locked and is automatically toggled off.
7. Dismiss the Right-Hand Panel (RHP) by closing it.
8. Reopen the same main tag and verify that the "Required" switch remains off and locked, reflecting the disabled state of the subtags.

Do we agree 👍 or 👎.

cc @puneetlath

**Comment by puneetlath** [comment] 2024-09-21 22:53
@ikevin127 has been paid. 

@Shahidullah-Muffakir your offer is here: https://www.upwork.com/nx/wm/offer/104071660. Please ping me on this issue when you've accepted it.

**Closed by puneetlath** 2024-09-21 22:53 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by Shahidullah-Muffakir** [comment] 2024-09-22 06:19
@puneetlath Offer aceepted, Thank you!

**Comment by puneetlath** [comment] 2024-09-22 19:20
Great, all paid. Thanks everyone!
