### ISSUE TITLE
[$500] System message is formatted differently with the names has apostrophe

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33378] opened 2023-12-20 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703015541706559

## Action Performed:
1. Go to a workskpace
2. Add few members with one of the user has apostrophe in the name
3. Open the #admin room
4. Observe the system messages

## Expected Result:
All the messages should be formatted in the same way

## Actual Result:
The one which has apostrophe in the name is formatted differently

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (6)](https://github.com/Expensify/App/assets/38435837/feb45268-a82a-45d7-bbbb-09fb89cd160d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b611c4c2a17b8f3</li>
        <li>Upwork Job ID: 1737982029792141312</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-12-21 23:42
I reported this back in August ([GH](https://github.com/Expensify/Expensify/issues/305975)) and didn't realize that it was the apostrophe that was causing issues. I'm not sure why @m-natarajan is unable to reproduce, I can confirm that I saw the same behavior around names with apostrophes.

**Comment by FlorianWueest** [comment] 2023-12-24 13:59
Unable to replicate the issue, neither on MacOS (Chrome), MacOS (Safari) & Win (Chrome). Also tested adding name normally (first & last name field), or entire name in 'first name' field,  and entire name in 'last name' field.

Screenshot of MacOS (Chrome): 
![MacOS Chrome](https://github.com/Expensify/App/assets/106832588/59f0085a-4f07-49e0-8a18-0c9e6053adc0)

Screenshot of MacOS (Safari): 
![MacOS Safari](https://github.com/Expensify/App/assets/106832588/e6a8062e-862b-407b-a4f2-c196be671d50)

**Comment by mvtglobally** [comment] 2023-12-31 06:12
Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment] 2024-01-02 22:36
I asked in the original Slack thread if it's still reproduceable.

**Comment by sakluger** [comment] 2024-01-04 23:17
No longer reproduceable. Closing!

**Closed by sakluger** 2024-01-04 23:17 UTC
Labels: External, Daily, Help Wanted, Bug
