### ISSUE TITLE
121 Emails not populating in NewDot

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12665] opened 2022-11-11 13:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. 121 emailed me directly.
2. Nothing showed up in NewDot, despite my email always doing this when ANYONE emails me.
3. Tried to refresh, log out, and send a message to them from the NewDot side. (Unsure if they got this via email if it is not working the other direction.)

## Expected Result:
121's email would open a chat in NewDot where I would be able to message back.

## Actual Result:
Did not happen.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image (1)](https://user-images.githubusercontent.com/43996225/201350438-0b093559-8a35-4bd4-abe5-ae6ca464e2c7.png)

<Alex.Loaiza@jaclo.com> to:Rebecca Norris <rebecca.norris@team.expensify.com>
date: Nov 10, 2022, 12:42

![image](https://user-images.githubusercontent.com/43996225/201350439-d258bc21-d602-4ed9-a20f-4b84bbe011ec.png)

![image (2)](https://user-images.githubusercontent.com/16232057/201401408-8e172f61-f00c-4092-ab7e-0ac55230bb29.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rguminski (this is Rebecca, a Guide)
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668117565413029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2022-11-11 18:05
@danielrvidal @flaviadefaria @techievivek @yuwenmemon - what's the expected behaviour here? 

1. lead emailed a guide directly on their teamDot email address
2. The message didn't show in their NewDot DM with the customer

**Comment by yuwenmemon** [comment] 2022-11-11 18:06
That's to be expected, yes. The emails simply go to the guide's gmail inbox.

**Comment by jliexpensify** [comment] 2022-11-13 21:58
Hi - do I need to do anything here? 

Based off Yuwen's statement, it sounds like the Launch Mentor should be confirming with Rebecca (Guide) if the email hit their Gmail, right?

**Comment by rguminski** [comment] 2022-11-14 12:42
Hello, I have had a non 121 email my team.expensify email and they even populated a convo with me and conc in my NewDot. This is NOT normal. And this was a 121 of mine.

**Comment by trjExpensify** [comment] 2022-11-14 13:30
>I have had a non 121 email my team.expensify email and they even populated a convo with me and conc in my NewDot.

Yeah, but that could have been a bug in the first place that we've since fixed. Perhaps because if that happens, it goes to our customer support team that we don't want to happen (unlike the account managers implementation).

**Comment by trjExpensify** [comment] 2022-11-14 13:39
Yeah, they still get an email from you if they don't read it in NewDot.

**Comment by rguminski** [comment] 2022-11-14 13:40
Okay then no worries. I just thought this might be a bug, and my chief concern was the customer knowing I messaged them back.

**Comment by jliexpensify** [comment] 2022-11-15 21:22
@trjExpensify - could we close this GH?

**Comment by trjExpensify** [comment] 2022-11-15 22:07
Yep! Do the honours.

**Closed** 2022-11-15 22:43 UTC
Labels: Daily, Needs Reproduction, Bug
