### ISSUE TITLE
Desktop - Full colon when editing in compose does not trigger or fillter emojis

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26416] opened 2023-08-31 17:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. write something in compose.
2. Try to use `:smi` to filter smily emojis
3. Notice that a popover will show to filter emojis
4. Send the message
5. Try to edit the message you sent
6. Notice that when you try to use a full colon `:` emoji picker does not get triggered .

## Expected Result:
 When you enter a full colon an emoji picker should show just like when you are composing a message for the first time.

## Actual Result:
A emoji picker didn't get triggered when typing a full colon `:`

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/12b03267-dc19-4dd8-9b92-a0af83cb40d6

https://github.com/Expensify/App/assets/93399543/c07f888e-8b0a-4d4a-bcaa-7b8e28051257

**Expensify/Expensify Issue URL:**
**Issue reported by:** @brianmuks 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692912989265419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-08-31 17:14
Isn't this a dupe of https://github.com/Expensify/App/issues/26363?

**Comment by alexpensify** [comment] 2023-08-31 23:49
Closing - thanks for flagging, based on this comment I'm going to close this one too: https://github.com/Expensify/App/issues/26363#issuecomment-1701761900

**Closed by alexpensify** 2023-08-31 23:49 UTC
Labels: Daily, Bug
