### ISSUE TITLE
[$500] Bank Account - Error message for too many bank account requests is misplaced

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27446] opened 2023-09-14 14:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspace > Bank Account and enter routing and account numbers (Routing number: 074000078, Account number: 1234)
2. Enter Company Information in the Company Information section
3. Click "Continue" and notice that the error message is misplaced. It should be placed next to the Connect Bank Account section, not in the Company Information section.

## Expected Result:
The error message for too many bank account requests should be placed next to the Connect Bank Account section.

## Actual Result:
The error message for too many bank account requests is misplaced and appears in the Company Information section instead of next to the Connect Bank Account section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.70-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/7b32f143-9757-4447-9bb5-b627ac858cb2

https://github.com/Expensify/App/assets/115492554/8516d6b0-f2a4-4ad1-bd34-3f6347c1df9c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692779078401859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014fe22271eb53f12c</li>
        <li>Upwork Job ID: 1702328446978674688</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by zukilover** [comment] 2023-09-14 22:55
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Error message for too many bank account requests is misplaced

### What is the root cause of that problem?
This error is triggered from the company step form:

https://github.com/Expensify/App/blob/81caa8419039a0a7b7ce62a86500cbac9fa20f39/src/pages/ReimbursementAccount/CompanyStep.js#L134-L135

while it should really be triggered from the bank account step (via `BankAccounts.connectBankAccountManually`).

### What changes do you think we should make in order to solve the problem?
We can tell the wrapper page to render bank account step if the errors contain a bank account error.

Change this line:

https://github.com/Expensify/App/blob/81caa8419039a0a7b7ce62a86500cbac9fa20f39/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L414-L416

to:

```
if (currentStep === CONST.BANK_ACCOUNT.STEP.BANK_ACCOUNT || 
            this.hasBankAccountErrors() && currentStep === CONST.BANK_ACCOUNT.STEP.COMPANY) {
            return (
                <BankAccountStep
```

where `hasBankAccountErrors` is checking the errors like this:

```
hasBankAccountErrors() {
        const errors = lodashGet(this.props.reimbursementAccount, 'errors', {});
        return _.some(Object.values(errors), (error) => error.includes('Too many users already set up this bank account'))
    }
```

### What alternative solutions did you explore? (Optional)

Return the bank error earlier at the `ConnectBankAccountManually` API.

**Comment by abdel-h66** [comment] 2023-09-15 12:26
I think the best approach here as @zukilover suggested would be returing the error earliler from the API.

**Comment by burczu** [comment] 2023-09-18 08:20
not overdue - I'll review it today

**Comment by burczu** [comment] 2023-09-18 10:17
I agree with @abdel-h66 that the optional solution from @zukilover would be better - @zukilover could you please write more about it in your proposal (what part of code would you like to change and how)?

**Comment by zukilover** [comment] 2023-09-21 22:34
@burczu the alternative solution needs to be fixed from the BE. If that's the route we're going to take, there's no need for any FE changes I think.

**Comment by jliexpensify** [comment] 2023-09-21 23:41
Not overdue

**Comment by jliexpensify** [comment] 2023-09-25 07:46
Hmm @burczu can you confirm if you think this is a back-end fix? Does this need to go to `Internal`?

**Comment by burczu** [comment] 2023-09-25 09:21
@jliexpensify Yes, as I already wrote, it would be best to follow @zukilover's optional solution and I agree with him that this will involve BE changes so I think we can switch to `Internal`.

**Comment by jliexpensify** [comment] 2023-09-26 08:57
@Gonals this looks like it's internal, based off this [comment](https://github.com/Expensify/App/issues/27446#issuecomment-1730433276)

**Comment by Gonals** [comment] 2023-09-29 04:23
I most likely won't be able to work on this for a couple of weeks, so we might want to reassign

**Comment by jliexpensify** [comment] 2023-10-03 04:22
@lakchote friendly bump - this looks to be `Internal`?

**Comment by lakchote** [comment] 2023-10-04 13:24
@jliexpensify 

After investigating the problem, looks like we need additional input from @joelbettner.

Here's the flow that triggers the error for `Too many already set up this bank account`.

We call the API command `UpdateCompanyInformationForBankAccount` that create an `ACHDATA` object based on the user's submission for the `Company Information` step.
With this `ACHDATA` that contains all the different fields info, we call an update of the withdrawal account wich ultimately trigger the `SetupWithdrawalAccount` responsible for the error message.

However if we call in the `Connect Bank Account` step the `SetupWithdrawalAccount` command with empty ACHDATA fields in it (that is normal, as we don't have user's input yet) it causes this error:
<img width="362" alt="image" src="https://github.com/Expensify/App/assets/21549771/d89355f3-0132-4bb6-8c95-739eaf71b941">

This error more specifically after debugging is `402 Missing externalApiResponses in additionalData` from `BankAccount::getFilteredAdditionalDataJSON`.
By trying to prevent the normal flow from occuring we get this error as we don't have the `externalApiResponses` property. Which makes me think it might not be the best option to circumvent the whole flow that was created.

[Looking at GH history](https://github.com/Expensify/Auth/commit/1630ba48e903dd9c232365ad895876c84b159409), it looks like it is @joelbettner that created this safe guard. Could we have your input on this?

**Comment by lakchote** [comment] 2023-10-05 05:47
I've pinged Joel through Slack in case he has missed the GH notification.

**Comment by joelbettner** [comment] 2023-10-05 22:16
So, we have some bad flows happening here that do not follow our 1:1:1 architecture.

This flow does not use the `UpdateCompanyInformationForBankAccount` Auth command. Instead, it waits until the user has entered the account numbers and the company info before calling SetupWithdrawalAccount for both of those steps. Definitely not ideal.

Here is what I think we should do to fix this.

1.) Create a `ConnectBankAccountManually` Auth command. This auth command will:
  - check that the `currentStep` that is passed to it is `BankAccount::STEP_BANK_ACCOUNT`
  - check run all the other checks that `SetupWithdrawalAccount` currently does for the `BankAccount::STEP_BANK_ACCOUNT` step
  - @Gonals is there a reason you didn't call `SetupWithdrawalAccount` from the `ConnectBankAccountManually` method and instead waited until it was called in the next step to actually set up the withdrawal account in Auth?

2.) Update the `BankAccountAPI::connectBankAccountManually` method to make sure it calls the new `ConnectBankAccountManually` Auth command.
  - After this change is implemented, when the user clicks the "continue" button after entering their routing number and account number we will actually make the call to Auth that adds it, and we will correctly display any errors that happen when attempting to add it.

3.) Update the `BankAccountAPI::updateCompanyInformationForBankAccount` method to actually call the `UpdateCompanyInformationForBankAccount` Auth command instead of the `SetupWithdrawalAccount` Auth command.
 - @luacmartins is there a reason you used the old `SetupWithdrawalAccount` command instead of the new `ConnectBankAccountManually` command?

@nkuoch how do you feel about starting to move VBBA setup to the individual auth command calls in NewDot rather than using the `SetupWithdrawalAccount` Auth command? We can leave `SetupWithdrawalAccount` as it is so everything continues to work in OldDot. Personally, I think now is the best time to start getting this moved over to our new Auth commands for NewDot.

**Comment by nkuoch** [comment] 2023-10-06 09:51
1) We want to check it not only when it's manual - also when via Plaid
Alberta didn't write this logic. Back then we wanted to wait for giact checks to be ran before inserting any bank account in the db, as auth side we don't want to have to update a wrong account number or routing number. It always for the user to double check their data before we insert anything. 
The thing is that Giact requires the companyName in order to be ran. That's why we can't run it at bankAccount step, and need to wait for the user to complete the company step first.

**Comment by nkuoch** [comment] 2023-10-06 09:58
3. Hmm I actually didn't know you finished refactoring those completely - I know you started and some PRs got merged, but didn't think they were ready to use. If we use the new commands, we'll definitely need to test very well. Maybe I should be the one doing it as there a several logic and cases that I know well.

**Comment by luacmartins** [comment] 2023-10-06 16:33
>@luacmartins is there a reason you used the old SetupWithdrawalAccount command instead of the new ConnectBankAccountManually command?
Where are we calling `SetupWithdrawalAccount` instead of `ConnectBankAccountManually`?

**Comment by lakchote** [comment] 2023-10-09 12:06
This seems to be in good hands. Unassigning myself for now.

**Comment by joelbettner** [comment] 2023-10-11 22:43
@nkuoch should we close this issue since you are going to start working on breaking SetupWithdrawalAccount into separate Auth commands? I'll close it for now, feel free to re-open if you think that'd be better.

**Closed by joelbettner** 2023-10-11 22:43 UTC
Labels: Engineering, Daily, Internal, Bug
