### ISSUE TITLE
[HOLD for payment 2023-07-28] [$1000] Web -  "(edited)" shows up when user clicks on the show message button on a deleted first thread message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21707] opened 2023-06-27 17:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. Hover over the sent message on account B and click on reply in thread and send a message as a thread reply
3. Hover over the first thread message and click on the flag icon
4. Go to account A and go to the original chat where the thread started off and delete the first message where the thread reply is on
5. Go to account B and select a severity from the panel. For eg. "Intimidation"
6. Click on the show message button on the first message

## Expected Result:
User should see [Deleted message] after clicking on the show message button.

## Actual Result:
 "(edited)" shows up when user clicks on the show message button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/905f3e59-de10-46cb-99df-b70cc944488f

https://github.com/Expensify/App/assets/93399543/e3ff4596-b803-4d70-b453-8bca8ac27e17

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687533238591329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131a4c134074c1f4f</li>
        <li>Upwork Job ID: 1674819820477284352</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-06-27 18:03
`FlagComment` API returns parentReportAction with `isEdited=true`, `isDeletedParentAction=false`. Calling `OpenReport` API again returns `isEdited=true`, `isDeletedParentAction=true`. This is the main reason. Looks like should be fixed in the backend

**Comment by jeet-dhandha** [comment] 2023-06-28 19:50
Is there a way I can help with the API ? @kbecciv

**Comment by CortneyOfstad** [comment] 2023-06-30 16:38
I was able to recreate this on my side as well. Getting some eyes on this

**Comment by CortneyOfstad** [comment] 2023-06-30 19:33
Heading OoO for the week (back July 10) so re-assigning this in the meantime 👍

**Comment by eVoloshchak** [comment] 2023-07-04 16:00
Not overdue, [looks like](https://github.com/Expensify/App/issues/21707#issuecomment-1609987279) this need to be fixed on the back end

**Comment by eVoloshchak** [comment] 2023-07-04 16:01
> Is there a way I can help with the API ? 
@jeet-dhandha, I think contributors can work only on the front end part of the app

**Comment by luacmartins** [comment] 2023-07-06 20:19
PR up https://github.com/Expensify/Web-Expensify/pull/38078

**Comment by luacmartins** [comment] 2023-07-06 20:20
@s-alves10's [comment](https://github.com/Expensify/App/issues/21707#issuecomment-1609987279) was spot on. Even though they couldn't work on a fix because the issue was in the API layer, I think we should still compensate them for the triage/proposed solution.

**Comment by luacmartins** [comment] 2023-07-12 22:58
We're still having this issue even after the API update. That's because we store `reportAction` when `FlagCommentPage` renders, but it's never updated for threads since `props.reportActions` points to the `reportActions` of the thread report and not parent report. I'm gonna look into a solution for this soon.

**Comment by luacmartins** [comment] 2023-07-12 23:06
Actually, since the report action was deleted, I don't think we should be able to flag it at all - see [this line](https://github.com/Expensify/App/blob/08fa90c6ec2851db3b0c6d1541a7e00de5f3309e/src/libs/ReportUtils.js#L2199). I'm wondering if we need to do anything here at all. What do you think @dangrous?

**Comment by luacmartins** [comment] 2023-07-13 15:58
>I believe it should just silently fail 
Yea, this sounds good. I'll work on a fix for showing `[Deleted message]`. Thanks for confirming!

**Comment by johncschuster** [comment] 2023-07-24 20:28
@eVoloshchak bump on the checklist above

**Comment by eVoloshchak** [comment] 2023-07-27 21:40
- The PR that introduced the bug has been identified. Link to the PR: This was a bug on [back end](https://github.com/Expensify/App/issues/21707#issuecomment-1609987279)

- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A

- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not sure an additional discussion is needed here, this was an enge case missed during review, not much we could add to our processes

- Determine if we should create a regression test for this bug. 
Ideally, we want to test both cases: this issue and steps from https://github.com/Expensify/App/pull/22831. 
Both of these cases are similar
_Is it easy to test for this bug? No, requires multiple accounts to test
Is the bug related to an important user flow? Yes
Is it an impactful bug? No_ 
I think we shouldn't create a regression test for this. The bug isn't impactful and doesn't affect user experience, while being not easy to test

**Comment by johncschuster** [comment] 2023-07-30 17:31
Thanks, @eVoloshchak!

> I think we shouldn't create a regression test for this. The bug isn't impactful and doesn't affect user experience, while being not easy to test

@luacmartins what are your thoughts on the above? Do you agree?

**Comment by luacmartins** [comment] 2023-07-31 20:56
I agree. This is an edge case scenario that doesn't prevent the user from using the App.

**Comment by johncschuster** [comment] 2023-07-31 22:42
# Summary of payment:
External issue reporter - @Nathan-Mulugeta - $250
Internal engineer fixed the issue
Contributor+ that helped on the issue and/or PR - @eVoloshchak - $1000 (will request through NewDot)

**Comment by johncschuster** [comment] 2023-08-01 22:01
Working on issuing the bug report payment to Nathan in the above-linked issue.

**Comment by johncschuster** [comment] 2023-08-02 23:31
Payment has been issued to @Nathan-Mulugeta on https://github.com/Expensify/App/issues/23967 🎉

**Comment by johncschuster** [comment] 2023-08-02 23:32
@JmillsExpensify 
# Summary of payment:
External issue reporter - @Nathan-Mulugeta - $250 (Paid via Upwork)
Internal engineer fixed the issue
Contributor+ that helped on the issue and/or PR - @eVoloshchak - $1000 (will request through NewDot)

**Comment by JmillsExpensify** [comment] 2023-08-03 03:23
Reviewed details for @eVoloshchak. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Closed** 2023-08-03 22:09 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
