### ISSUE TITLE
[HOLD for payment 2024-11-01] Validate - Magic code RHP does not animate correctly from pay someone confirmation page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51276] opened 2024-10-22 17:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** sjdoijsojdojsojo@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Gmail account (unvalidated).
3. Complete the onboarding.
4. Open DM with any user.
5. Click + > Pay.
6. Enter amount in USD > Next.
7. Click Pay with Expensify.

## Expected Result:
Magic code RHP will animate correctly.

## Actual Result:
Magic code RHP does not animate correctly from pay someone confirmation page

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f64257e3-4c93-4d1d-a0d5-40b47a0024a7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by nkdengineer** [comment] 2024-10-22 17:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Magic code RHP does not animate correctly from pay someone confirmation page

### What is the root cause of that problem?

The problem here is that we are opening another right modal while one right modal is opened.

### What changes do you think we should make in order to solve the problem?


1. We should use `Navigation.dismissModal()` to dismiss the first right modal then open next right modal
2. We need to update backTo here correctly.

```
         Navigation.dismissModal();
         Navigation.isNavigationReady().then(() => {
                    Navigation.navigate(ROUTES.SETTINGS_WALLET_VERIFY_ACCOUNT.getRoute(ROUTES.SETTINGS_ADD_BANK_ACCOUNT));
         })
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by francoisl** [comment] 2024-10-22 23:18
This will be fixed by https://github.com/Expensify/App/pull/51267

**Comment by yuwenmemon** [comment] 2024-10-23 23:40
https://expensify.slack.com/archives/C07J32337/p1729726700727579

**Comment by greg-schroeder** [comment] 2024-11-01 17:21
Processing

**Closed** 2024-11-01 20:21 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
