### ISSUE TITLE
Web - Console error appears when clicked on 3 dots on workspace after creating and deleting a new workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22184] opened 2023-07-04 14:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. (Imp step) Create a new workspace and immediately delete the workspace
3. Now go to any older workspace and click on it. Click on 3 dots on top and notice the console error

## Expected Result:
 Console error should not appear when clicking on 3 dots on some other workspace after creating and deleting a new workspace

## Actual Result:
 Console error appears when clicked on 3 dots on workspace after creating and deleting a new workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/83be6747-e318-4859-9897-8f42af3d9e45

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687853012354349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DrLoopFall** [comment] 2023-07-04 15:22
Looks like it's a duplicate of #21833

**Closed** 2023-07-05 21:17 UTC
Labels: Daily, Needs Reproduction, Bug
