### ISSUE TITLE
mWeb - Distance - With same start & stop point user allowed to submit expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47414] opened 2024-08-14 12:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4858161
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tab fab -- submit expense-- distance
3. Enter start point " United States " and from dropdown select it
4. Enter stop point "USA" and from dropdown select it
5. Tap nex
6. Tap submit
7. Open the expense

## Expected Result:
With same start & stop point user must not be allowed to submit expense

## Actual Result:
With same start & stop point user allowed to submit expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a08ec270-6a0c-4fc7-8e2f-dca0133fcda1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-14 12:35
We think that this bug might be related to #vip-vsp

**Comment by FitseTLT** [comment] 2024-08-14 12:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Distance - With same start & stop point user allowed to submit expense

### What is the root cause of that problem?
We do check for duplicate waypoints but we check based on `address` and in this case it has different addresses
https://github.com/Expensify/App/blob/4496333dea008e0bd59ac3782ecd62be82483cfc/src/libs/TransactionUtils/index.ts#L644-L647
### What changes do you think we should make in order to solve the problem?

We need to check for the `lng` and `lat` similarity
```
 // Check for adjacent waypoints with the same address
        if (
            (previousWaypoint && currentWaypoint?.address === previousWaypoint.address) ||
            (currentWaypoint?.lat === previousWaypoint?.lat && currentWaypoint?.lng === previousWaypoint?.lng)
        ) {
            return acc;
        }
```
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-08-23 09:38
>We do check for duplicate waypoints but we check based on address and in this case it has different addresses

Given this, I'm going to close the issue as an edge case. I don't think it's worth the overhaul for lng/lat. If you enter two dupe addresses, we throw an error and that would be the common mistake here: 

<img width="375" alt="image" src="https://github.com/user-attachments/assets/aadc02a6-58e4-472f-9c11-1af0ad30894e">

If we see customers actually running into this by entering whole countries like "USA"/"United States" as their waypoints, I'll be pretty amazed, but gladly reconsider. CC: @neil-marcellini for vis if you disagree with this decision.

**Closed by trjExpensify** 2024-08-23 09:38 UTC
Labels: Daily, Overdue, Bug
