### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Task - Anonymous user can delete task in public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37999] opened 2024-03-08 17:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log out if logged in
2. Go to a public room with task. (https://staging.new.expensify.com/r/2376199970894587
)
3. Click on the task
4. Click three-dot menu > Delete task
5. Delete the task

## Expected Result:
User will be presented with login modal when attempting to delete task anonymous

## Actual Result:
Anonymous user can delete the task. The task is not deleted, but there is no action from preventing user to delete it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ee9890c3-f7a1-4c5e-b26e-ac20cff714ad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d7666768e954e45</li>
        <li>Upwork Job ID: 1767210887617179648</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-08 17:58
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-03-11 11:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Task - Anonymous user can delete task in public room
### What is the root cause of that problem?
- In [here](https://github.com/Expensify/App/blob/d37b25e1deda4c01add3253bcddff8c5d2fa36f7/src/pages/home/HeaderView.js#L156), we allow user to click on "Delete" button without checking if user is anonymous user or not.
### What changes do you think we should make in order to solve the problem?
- Just need to wrap the ```() => setIsDeleteTaskConfirmModalVisible(true)``` in [here](https://github.com/Expensify/App/blob/d37b25e1deda4c01add3253bcddff8c5d2fa36f7/src/pages/home/HeaderView.js#L156) by the ```Session.checkIfActionIsAllowed``` as we did with other buttons

### What alternative solutions did you explore? (Optional)
- NA

**Comment by zanyrenney** [comment] 2024-03-11 15:27
Adding the external label to get this resolved!

**Comment by nkdengineer** [comment] 2024-03-11 16:37
Anyone in the design team can help confirm that, when should we display the sign in modal? When user clicks on the "Delete" option as we did with other buttons, or when user clicks on in "Confirm" button?

**Comment by c3024** [comment] 2024-03-12 02:16
I think it is logical to do the check before displaying the confirmation modal.

This is similar to the description and assignee fields. When we click on the description we check directly if the user is anonymous and show Sign-in page in the RHP (instead of showing description page and checking if the user is anonymous after clicking Save button on the description page).

So, the [proposal here](https://github.com/Expensify/App/issues/37999#issuecomment-1988249717) by @nkdengineer looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by blimpich** [comment] 2024-03-12 18:13
> ❌ There was an error making the offer to @c3024 for the Reviewer role. The BZ member will need to manually hire the contributor.

@zanyrenney can you manually hire @c3024 for the reviewer role?

**Comment by nkdengineer** [comment] 2024-03-14 04:08
@c3024 After merging main, I cannot open public room with an anonymous user. Can you help confirm?

**Comment by c3024** [comment] 2024-03-14 04:25
You are right. Neither can I.

**Comment by nkdengineer** [comment] 2024-03-14 11:19
@c3024 Maybe it is related to https://github.com/Expensify/App/issues/38212

**Comment by c3024** [comment] 2024-03-18 16:34
Commented on #38212

**Comment by zanyrenney** [comment] 2024-03-21 17:53
I also can't repro this anymore, i think we can close this one out as seems like it was solved and we're tackling any remaining issue in the issue linked above!

**Comment by nkdengineer** [comment] 2024-03-21 18:02
@zanyrenney I still can reproduce this bug and PR is ready to review because the blocked [issue](https://github.com/Expensify/App/issues/38212) is fixed

**Comment by blimpich** [comment] 2024-03-25 19:34
Yeah I can still repro this, re-opening

**Comment by blimpich** [comment] 2024-03-25 19:35
Merged in the open PR

**Comment by zanyrenney** [comment] 2024-04-05 13:30
@c3024 have invited you to the job. 

@nkdengineer what is your upwork profile please?

**Comment by c3024** [comment] 2024-04-05 13:31
@zanyrenney thanks. Accepted the invite.

**Comment by zanyrenney** [comment] 2024-04-05 14:04
**payment summary**

paid @c3024 $500 via upwork.

**Comment by zanyrenney** [comment] 2024-04-05 14:05
can't find @nkdengineer on upwork.

**Comment by zanyrenney** [comment] 2024-04-10 14:28
Not heard back from @nkdengineer still: 
<img width="879" alt="2024-04-10_15-28-20" src="https://github.com/Expensify/App/assets/56830058/d5fbf6ce-32e5-4018-bcb8-b67e03267ea2">

**Comment by zanyrenney** [comment] 2024-04-12 15:41
@nkdengineer has not accepted the invite still.

**Comment by nkdengineer** [comment] 2024-04-15 15:00
> @nkdengineer has not accepted the invite still.

@zanyrenney I accepted the invitation, thanks a lot!

**Comment by zanyrenney** [comment] 2024-04-16 17:18
**payment summary**
ROLE: @c3024 paid $500 via Upwork 
ROLE: @nkdengineer paid $500 via Upwork

**Closed by zanyrenney** 2024-04-16 17:18 UTC
Labels: External, Weekly, Awaiting Payment, Bug
