### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500] [Nav][Simplified Collect][Workflows] Delayed Submission/Monthly Frequency - Fix redirection screen on reload

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#37517] opened 2024-02-29 15:22 UTC
**Context**

1. Create a Collect policy in NewDot
2. Go to Workspace's settings > Workflows
3. Toggle the `Delayed Submission` and click on `Monthly`
4. A RHP should open, refresh the page

**Expected result**
You should be redirected back to the workflows screen

**Actual Result**
You are redirected to the #admins room

See video:
https://github.com/Expensify/App/assets/29673073/46449156-88c9-476b-b962-2bd73ede5a26

**Task**
Your goal is to fix the navigation issue.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0122ad7d632e92e433</li>
        <li>Upwork Job ID: 1763223792123248640</li>
        <li>Last Price Increase: 2024-02-29</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
<li>ikevin127 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by hereistopdev** [comment] 2024-02-29 15:40
I am freelancer from Upwork. I would like to work on this issue

**Comment by godofoutcasts94** [comment] 2024-02-29 16:06
Ready to help

**Comment by camusfsx** [comment] 2024-02-29 16:16
Contributor details
Your Expensify account email: f1992863292@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0189b8f0baa61b559e?viewMode=1

**Comment by bernhardoj** [comment] 2024-02-29 16:29
Looks like the workflow RHP page is not available yet, but to solve the issue, we should add the central to RHP mapping for workflow here.
https://github.com/Expensify/App/blob/0cc58170ec003d20b606b118afaba62a906c3160/src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts#L4-L9

So this could work.
https://github.com/Expensify/App/blob/0cc58170ec003d20b606b118afaba62a906c3160/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L121-L126

**Comment by situchan** [comment] 2024-02-29 16:35
I think we should hold this until https://github.com/Expensify/App/pull/37213 is merged as not testable yet.
@bernhardoj please submit formal proposal including the case of Categories page (https://github.com/Expensify/App/issues/37505 was closed as same root cause)

**Comment by bernhardoj** [comment] 2024-02-29 16:36
Will post a formal proposal once https://github.com/Expensify/App/pull/37213 is merged.

**Comment by ikevin127** [comment] 2024-02-29 17:20
# Proposal

### Please re-state the problem that we are trying to solve in this issue

We are not navigated back to the workflows screen.

### What is the root cause of that problem?

We're not mapping the workflow RHP routes to the `[SCREENS.WORKSPACE.WORKFLOWS]` central pane [here](https://github.com/Expensify/App/blob/822bdb9f0b29e927ab90f420666484387329475c/src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts#L4-L8).
This causes the central pane to reset, as noted [here](https://github.com/Expensify/App/pull/37213#issuecomment-1971375652) -> hence this issue was created.

### What changes do you think we should make in order to solve the problem?

I checked out https://github.com/Expensify/App/pull/37213 and this way I was able to reproduce and apply solution.

https://github.com/Expensify/App/blob/822bdb9f0b29e927ab90f420666484387329475c/src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts#L4-L8

Within the code block mentioned above we need to map all existing workflow RHP routes to `[SCREENS.WORKSPACE.WORKFLOWS]` like so:

```ts
const CENTRAL_PANE_TO_RHP_MAPPING: Partial<Record<CentralPaneName, string[]>> = {
    /// ...existing mappings
    [SCREENS.WORKSPACE.WORKFLOWS]: [SCREENS.WORKSPACE.WORKFLOWS_AUTO_REPORTING_FREQUENCY, SCREENS.WORKSPACE.WORKFLOWS_AUTO_REPORTING_MONTHLY_OFFSET],
};
```

> [!NOTE]
> So far we only have RHP routes for `WORKFLOWS_AUTO_REPORTING_FREQUENCY` and `WORKFLOWS_AUTO_REPORTING_MONTHLY_OFFSET`, but once the PR is merged I'm assuming there might be other RHP routes -> so we need to add all of them there.

### Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/030e9a2f-0de7-4d63-b387-1cd602f7e3cb"> | <video src="https://github.com/Expensify/App/assets/56457735/0134cb6e-3a4a-4bbd-bba6-5392468de40a"> |

</details>

**Comment by lakchote** [comment] 2024-03-01 14:35
> Will post a formal proposal once #37213 is merged.

@bernhardoj please submit your proposal since it has been merged. Thanks

**Comment by bernhardoj** [comment] 2024-03-01 15:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Refreshing when the submission frequency or workspace category settings show a report screen behind it instead of the workspace-related page.

### What is the root cause of that problem?
When we refresh the web, the previous nav stack is lost. To show the correct/related page behind the RHP, we use `getAdaptedStateFromPath` to customize the nav state based on the current path.

If the state contains an RHP, it will make sure a bottom tab navigator, a central pane, and the RHP itself are included on the nav stack/routes.
https://github.com/Expensify/App/blob/a2d0cf2be02c35afff0b5a92f79e631ae7f816c1/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L156-L160

The bottom tab navigator will be either an LHN (home), all settings, or a workspace page. We already have the bottom tab to central pane mapping [here](https://github.com/Expensify/App/blob/a2d0cf2be02c35afff0b5a92f79e631ae7f816c1/src/libs/Navigation/linkingConfig/TAB_TO_CENTRAL_PANE_MAPPING.ts#L4-L18).

In this issue, the bottom tab navigator is the LHN (home) because the central pane is a report screen.

The central pane is a report screen because the mapping for the workspace workflow central pane with the submission frequency RHP is not available, 
https://github.com/Expensify/App/blob/a2d0cf2be02c35afff0b5a92f79e631ae7f816c1/src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts#L4-L8
https://github.com/Expensify/App/blob/a2d0cf2be02c35afff0b5a92f79e631ae7f816c1/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L121-L126

so it defaults to the report screen.

https://github.com/Expensify/App/blob/a2d0cf2be02c35afff0b5a92f79e631ae7f816c1/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L167-L174

### What changes do you think we should make in order to solve the problem?

Add the central pane to RHP mapping for workspace workflow and workspace category

```
[SCREENS.WORKSPACE.WORKFLOWS]: [SCREENS.WORKSPACE.WORKFLOWS_AUTO_REPORTING_FREQUENCY, SCREENS.WORKSPACE.WORKFLOWS_AUTO_REPORTING_MONTHLY_OFFSET],
[SCREENS.WORKSPACE.CATEGORIES]: [SCREENS.WORKSPACE.CATEGORIES_SETTINGS],
```

**Comment by situchan** [comment] 2024-03-01 15:22
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/37517#issuecomment-1973353805) looks good, though @ikevin127 submitted the formal proposal first.
 @lakchote will give the final call.
🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-03-01 16:52
@iwiznia hi, can you consider my earlier solution [here](https://github.com/Expensify/App/issues/37517#issuecomment-1971506698)?

**Comment by iwiznia** [comment] 2024-03-01 17:03
Oh, did not notice it was previous to the other one and it does look the same. Going to reassign to you, as that's what feels more fair. Next time I recommend you follow the formal proposal to avoid confusion.

**Comment by iwiznia** [comment] 2024-03-01 17:05
Oh wait, no, they are not the same in the OG post, are they?

**Comment by ikevin127** [comment] 2024-03-01 17:07
> @ikevin127 submitted the formal proposal first.

@iwiznia What are we going to do about this though ?

Should I start posting the same kind of comments on issues and expect to be assigned based on whether or not I was first to post a comment (not a formal proposal) ? 👀

**Comment by ikevin127** [comment] 2024-03-01 17:52
PR https://github.com/Expensify/App/pull/37620 ready for review! 🚀

**Comment by bernhardoj** [comment] 2024-03-02 01:59
> Oh wait, no, they are not the same in the OG post, are they?

The solutions are the same

> What are we going to do about this though ?

> Should I start posting the same kind of comments on issues and expect to be assigned based on whether or not I was first to post a comment (not a formal proposal) ? 👀

The page that we are trying to fix isn't even available yet at that time, so it's not a "formal" issue either. I'm not even trying to speedrun a solution as the issue has been open for an hour, yet no one has given any solution yet. An hour later, you took my solution and formatted it into a formal proposal 😄.

**Comment by ikevin127** [comment] 2024-03-02 02:20
> @bernhardoj please submit formal proposal including the case of Categories page (https://github.com/Expensify/App/issues/37505 was closed as same root cause)

to which you replied:

> Will post a formal proposal once https://github.com/Expensify/App/pull/37213 is merged.

I put in the effort to write a formal proposal with a clear RCA / solution and videos before the PR was merged, as to me that wasn't really a blocker. I simply followed the Contributor guidelines mentioned [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job) at (5).

I don't see a problem here, you had a choice and you chose not to do it 🤔

**Comment by bernhardoj** [comment] 2024-03-02 02:32
That's not really an effort if you just copied someone solution. I wouldn't say the RCA is clear as it's just a reverse from the solution.
RCA: we don't map here
Solution: we map here
without even explaining why we should do the mapping and why the report screen is shown.

I must admit it's my fault to not do it earlier as I never expected someone would take the chance to convert my comment into a proposal.

**Comment by ikevin127** [comment] 2024-03-14 20:56
@mallenexpensify 👋 Any blockers from completing the payment here ?

**Comment by mallenexpensify** [comment] 2024-03-15 17:01
Contributor: @ikevin127 paid $500 via Upwork
Contributor+: @situchan paid $500 via Upwork. 

@situchan can you complete the[ BZ checklist above](https://github.com/Expensify/App/issues/37517#issuecomment-1981859407) plz? Thx

**Comment by hereistopdev** [comment] 2024-03-15 17:03
Hi Expensify/App,
If you have any sub-project to fix, Plz let me know.
I am always ready for you.
thanks.

**Comment by mallenexpensify** [comment] 2024-03-15 17:04
@hereistopdev plz review [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). We have a process we follow and all work is completed as part of that process.

**Comment by hereistopdev** [comment] 2024-03-15 17:06
Before, I applied with Expensify account, but you told me the project is
taken by other one.
What I want is just let me know when you have new issues to fix.
Thx

**Comment by situchan** [comment] 2024-03-15 17:09
There's no offending PR. This is follow-up of new feature and original PR author/reviewer was already aware of this during PR review.
I think this is still WIP and full regression test will be added after simplified collect / workflows is completely done.
That being said, we can close this.

**Closed** 2024-03-15 21:58 UTC
Labels: External, Daily, Awaiting Payment, Bug
