### ISSUE TITLE
[$250] Expense - Currently opened report disappears from LHN after DM report throws error

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48255] opened 2024-08-29 11:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4900394
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User A and B have never chatted before.

1. Go to staging.new.expensify.com
2. [User A] Go offline.
3. [User A] Submit an expense to User B.
4. [User B] While online, submit an expense to User A.
5. [User A] While on DM with User B, go online.

## Expected Result:
After the error appears for User A, the currently opened report (DM with error) will be shown and highlighted in LHN.

## Actual Result:
After the error appears for User A, the currently opened report (DM with error) disappears from LHN.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/93552746-3572-457e-9def-6f0a38b61eff

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831333278248310573</li>
        <li>Upwork Job ID: 1831333278248310573</li>
        <li>Last Price Increase: 2024-10-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by IuliiaHerets** [comment] 2024-08-29 11:29
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-08-29 17:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A report with an error because there is an existing report disappears from the LHN.

### What is the root cause of that problem?
Once we receive the error, the report has a `errorFields.notFound` data. Based on this condition, if the report has a not found error, then it won't be shown on the LHN.
https://github.com/Expensify/App/blob/b1882434a26e24a159322962597f07251d8365ea/src/libs/ReportUtils.ts#L5942-L5944
https://github.com/Expensify/App/blob/b1882434a26e24a159322962597f07251d8365ea/src/libs/ReportUtils.ts#L5769-L5777

But previously, we always included the report even if the error is a not found error, but we updated it by adding `isReportInAccessible` condition in https://github.com/Expensify/App/pull/47340.
https://github.com/Expensify/App/blob/b1882434a26e24a159322962597f07251d8365ea/src/libs/SidebarUtils.ts#L116-L130

### What changes do you think we should make in order to solve the problem?

We can follow the condition from the report screen to hide the LHN by only hide it if the report error is only not found.
https://github.com/Expensify/App/blob/b1882434a26e24a159322962597f07251d8365ea/src/pages/home/ReportScreen.tsx#L297-L298

https://github.com/Expensify/App/blob/b1882434a26e24a159322962597f07251d8365ea/src/libs/ReportUtils.ts#L5942-L5944

```
const hasHelpfulErrors = Object.keys(report?.errorFields ?? {}).some((key) => key !== 'notFound');
if (!hasHelpfulErrors && !canAccessReport(report, policies, betas)) {
    return false;
}
```

In our case, we have `createChat` and `notFound` error, so it will be shown on the LHN.

**Comment by JmillsExpensify** [comment] 2024-09-04 14:07
Went ahead and opened this up for proposals.

**Comment by rushatgabhane** [comment] 2024-09-09 16:41
@JmillsExpensify @bernhardoj i think this is how it should work -

1. If a report has 404 error.
2. Then it should have a RBR error that can be dismissed from the report.
3. Dismissing that error should hide the report from LHN

What do you think?

**Comment by JmillsExpensify** [comment] 2024-09-18 15:11
@rushatgabhane I agree with your suggestion.

**Comment by JmillsExpensify** [comment] 2024-09-25 17:21
Same as last week.

**Comment by JmillsExpensify** [comment] 2024-10-09 20:33
Actually this is an IOU so I'm inclined to close this as it's an edge case.

**Closed by JmillsExpensify** 2024-10-09 20:33 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
