### ISSUE TITLE
[HOLD for payment 2024-06-03] [$250] Group chat - App redirects to Concierge chat when leaving group chat and room

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41128] opened 2024-04-27 09:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Visit a few reports.
3. Go to FAB > Start chat.
4. Create a group chat.
5. Click on the chat header.
6. Click Leave.

## Expected Result:
- When a user leaves a room/group, we should navigate them to their last opened report
- If it's a new user who opens the link from incognito mode and then leaves the room, they will be directed to the concierge

## Actual Result:
- User is always redirected to Concierge chat, the same issue happens when leaving the room
    - On Android app, it redirects to the previous report, but it opens Concierge chat when tapping back button on the previous report.
    - On iOS app, it returns to group details page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/72c339dc-5f39-4aa9-8434-079d590d95ba

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01de0c9a8aaa7e6078</li>
        <li>Upwork Job ID: 1784843922902315008</li>
        <li>Last Price Increase: 2024-04-29</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 0</li>
<li>Nodebrute | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by izarutskaya** [comment] 2024-04-27 09:35
@dylanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-27 09:36
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-04-27 09:36
Production

https://github.com/Expensify/App/assets/115492554/8f91f94c-ce06-4752-b1dc-b22b836ca288

**Comment by Julesssss** [comment] 2024-04-29 07:15
Not critical enough to block deploy. Opening up to contributors.

**Comment by Julesssss** [comment] 2024-04-29 07:18
Shared with C+ team [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1714375059943879).

**Comment by Nodebrute** [comment] 2024-04-29 08:50
@shubham1206agra Hi, I tested it locally, and it seems this https://github.com/Expensify/App/pull/40701 is causing the problem.

**Comment by Nodebrute** [comment] 2024-04-29 08:52
To test quickly, just revert the changes in this block, and you'll see the issue is resolved.
https://github.com/Expensify/App/pull/40701/files#diff-ce6bb391d0654bf99a360da7d25fd73b85bb120211c8b4c2432ef7c7d8c708f3R2471-R2474

**Comment by Nodebrute** [comment] 2024-04-29 09:05
@Julesssss @ahmedGaber93 @shubham1206agra 
**results**

https://github.com/Expensify/App/assets/93134676/1fb53811-f8c3-4bd1-b0d2-0111fbafb362

**Comment by dylanexpensify** [comment] 2024-04-29 09:55
@shubham1206agra mind confirming? Nice catch @Nodebrute!

**Comment by Nodebrute** [comment] 2024-04-29 11:28
@shubham1206agra I just tested, and it's not reproducible in production.

**Comment by Pujan92** [comment] 2024-04-29 12:34
@MonilBhavsar Seems an issue comes out after our PR but while debugging I see that this part of the ReportScreen gets executed which is responsible for navigating to the ConciergeChat.

https://github.com/Expensify/App/blob/6a37cd86f89e22f09b018cc756f4347b7a3004b7/src/pages/home/ReportScreen.tsx#L514-L538

I am not sure but something looks fishy with the navigation and it triggering above while passing the fallbackRoute for goBack.

**Comment by Nodebrute** [comment] 2024-04-29 12:38
@shubham1206agra With the fallback route added, this code block is executed. I'm not sure why, but when the fallback route is added, we end up navigating to Concierge. It looks like this issue was already present, and this PR made it more noticeable.
https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/libs/Navigation/Navigation.ts#L218-L221
<img width="667" alt="Screenshot 2024-04-29 at 5 34 12 PM" src="https://github.com/Expensify/App/assets/93134676/15391091-d1f3-48fe-aa8b-a6609adfc9ac">

**Comment by Pujan92** [comment] 2024-04-29 13:04
@Nodebrute I don't think we can remove that bcoz it is added for the below reason

https://github.com/Expensify/App/blob/6a37cd86f89e22f09b018cc756f4347b7a3004b7/src/pages/home/ReportScreen.tsx#L514

**Comment by dylanexpensify** [comment] 2024-05-01 07:35
Bump @marcaaron [when you ](https://github.com/Expensify/App/issues/41128#issuecomment-2082674698)can 🙇‍♂️

**Comment by marcaaron** [comment] 2024-05-01 18:56
@shubham1206agra I'm not sure what you want me to look into, but happy to answer a more specific question if you've got one, thanks!

**Comment by Julesssss** [comment] 2024-05-03 13:06
Okay, so the issue is resolved for me when reverting https://github.com/Expensify/App/pull/40701, however that PR doesn't seem to have introduced the issue: 

> It looks like this issue was already present, and this PR made it more noticeable.

 @Nodebrute as you have correctly located two potential causes already, maybe you want to suggest another fix?

**Comment by Nodebrute** [comment] 2024-05-03 14:26
@Julesssss This PR https://github.com/Expensify/App/pull/40701 fixed an issue where we had no routes in the navigator. However, it introduced a regression. Previously, we used this goBack to pop the current route, but with the added fallbackRoute, we're now navigating to the last read report, adding an extra route to the navigation stack instead of popping it.
https://github.com/Expensify/App/blob/3b188e74f9ef7088f4c3f3a3fafc7f4f316e7298/src/libs/actions/Report.ts#L2510-L2513


I recommend we avoid using goBack() when it's the first route in the navigator and remove the fallbackRoute altogether. This change will resolve two issues https://github.com/Expensify/App/issues/41128 https://github.com/Expensify/App/issues/40680

**Comment by Nodebrute** [comment] 2024-05-03 14:35
https://github.com/Expensify/App/assets/93134676/64c80cac-587d-4407-84fe-1cf7827fd4e9

**Comment by Julesssss** [comment] 2024-05-03 15:17
Thanks @Nodebrute, that sounds good solution to me. Would you mind submitting a new proposal like you did [here](https://github.com/Expensify/App/issues/41128#issuecomment-2082171836) so we can review your new suggestion? Thanks.

**Comment by Nodebrute** [comment] 2024-05-06 02:01
@Julesssss working on it.

**Comment by ahmedGaber93** [comment] 2024-05-06 16:45
@shubham1206agra let me know your answer here https://github.com/Expensify/App/issues/41128#issuecomment-2082633177.

**Comment by Julesssss** [comment] 2024-05-07 08:17
Hi @ahmedGaber93 can you please take a look at these proposals? This updated[ proposal](https://github.com/Expensify/App/issues/41128#issuecomment-2082171836) from @Nodebrute is the one I prefer currently.

**Comment by ahmedGaber93** [comment] 2024-05-07 08:23
@Julesssss I will review it today.

**Comment by ahmedGaber93** [comment] 2024-05-08 03:01
@Nodebrute Thanks for your proposal update.

Related to your RCA, I think you missed updating it, you just say `It's coming from this PR #40701`, I read the full discussion here, and it has a lot of different thoughts, so please make sure to update your proposal with the explained root cause.
 
 Besides, your fix failed to pass https://github.com/Expensify/App/pull/40701 tests from 1 to 6, your video here https://github.com/Expensify/App/issues/41128#issuecomment-2093151005 seem follow different steps.
1. Create a public room as an admin
2. As a user A, join the public room
3. Copy the public room URL and signout
4. Paste the URL and signin
5. Leave the room
6. Ensure you're redirected to Concierge chat


https://github.com/Expensify/App/assets/41129870/299c7a43-5ab5-4078-9099-a7c126ea9a91

**Comment by Nodebrute** [comment] 2024-05-08 03:16
@ahmedGaber93 Hey, I don't think users should be redirected to the concierge chat after leaving a room. That's not the current behaviour in our app.

After leaving room the user should be navigated to most recent report
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/libs/actions/Report.ts#L2646

**Comment by ahmedGaber93** [comment] 2024-05-08 03:17
@Julesssss this issue is a regression from #40701, should we fix it here or by the #40701?

**Comment by ahmedGaber93** [comment] 2024-05-08 03:26
> Hey, I don't think users should be redirected to the concierge chat after leaving a room. That's not the current behaviour in our app.

What I'm understanding from #40701 QA steps is we have two cases.
 - After user login and he didn't visit any report (step 1 to 6), user should redirect to redirected to Concierge chat.
 - if user visit some reports before the room he leaves it (steps 7-10), user should be navigated to most recent report

**Comment by Nodebrute** [comment] 2024-05-08 06:03
When a user leaves a room/group, we navigate them to their last read report. In this scenario, the user will be directed to their last read report regardless of the device/tab/incognito they use to leave the room.

If it's a new user who opens the link from incognito mode and then leaves the group, they will be directed to the concierge.

@Julesssss, could you please confirm if this behavior aligns with the desired outcome?

Additionally, if we want to direct users to the concierge instead of their last read report when they leave the room in a new tab/incognito session, we can utilize the same check `isFirstRoute`

https://github.com/Expensify/App/blob/cd9a9ad735605624623ccf2ee4f9e6c0cda57af7/src/libs/actions/Report.ts#L2515

**Comment by Julesssss** [comment] 2024-05-08 09:21
> @Julesssss this issue is a regression from https://github.com/Expensify/App/pull/40701, should we fix it here 

We don't want to revert that PR as because it was an important fix and it has been too long to safely revert. Also we seem to have a simple proposal to fix.

> @Julesssss, could you please confirm if this behavior aligns with the desired outcome?

@Nodebrute yeah I agree that this is the desired behaviour 👍 I updated the issue description to make this clearer

**Comment by ahmedGaber93** [comment] 2024-05-08 11:30
> @ahmedGaber93 we don't want to revert that PR as because it was an important fix and it has been too long to safely revert. Also we seem to have a simple proposal to fix.

@Julesssss I just think it will be better if the issue fixed by #40701 author and C+ as they work on it before on some hours and have the full context of the issue instead of new contributors.

Also, the above proposal tries to make code works without finding the root cause of the issue and fix it.


@Nodebrute can you explain the root cause of the issue, the code which navigate to concierge is in [ReportScreen.tsx](https://github.com/Expensify/App/blob/6a37cd86f89e22f09b018cc756f4347b7a3004b7/src/pages/home/ReportScreen.tsx#L536) 
and it targets another goal below
https://github.com/Expensify/App/blob/6a37cd86f89e22f09b018cc756f4347b7a3004b7/src/pages/home/ReportScreen.tsx#L514

Why we need to edit `navigateToMostRecentReport` instead of `ReportScreen.tsx`?

Also, the first route condition should be `=== 0` and not  `=== 1` 
```
  const isFirstRoute = navigationRef.current?.getState().index === 1;
```

@Nodebrute hope you do not take my words as if I am trying to fight you with words or trying to prove you wrong, I just want us to work together to understand the root cause of the problem to make sure that what we are doing is the right solution.

Thanks!

**Comment by ahmedGaber93** [comment] 2024-05-08 11:50
After last test in the latest main in web, I found the issue is not reproduced when leaving room, regardless it is the first root or not, but reproduced when leaving group.

Both action leaving room and leaving group use the same function `navigateToMostRecentReport`, why it works on room and failed in group?

I think we may have a hidden issue in some place that lead to this behavior.


https://github.com/Expensify/App/assets/41129870/77d8c8d2-86c6-42d4-b3db-ab266dae8fcb

**Comment by Nodebrute** [comment] 2024-05-08 11:57
@ahmedGaber93 No probs. I have updated my RCA.

**Comment by Julesssss** [comment] 2024-05-08 12:05
> @Julesssss I just think it will be better if the issue fixed by https://github.com/Expensify/App/pull/40701 author and C+ as they work on it before on some hours and have the full context

I get your point, but internal employees are very busy with other internal tasks currently. I'll ask Monil to take a look at the most recent proposal once it has been reviewed though. @Nodebrute could you please link to the most recent RCA? I'm struggling to find which of your comments was most recently updated. Thanks

**Comment by Nodebrute** [comment] 2024-05-08 12:06
@Julesssss I've just updated the RCA, feel free to check it out.

**Comment by Nodebrute** [comment] 2024-05-08 12:09
> Also, the first route condition should be `=== 0` and not `=== 1`
<img width="1388" alt="Screenshot 2024-05-08 at 5 01 31 PM" src="https://github.com/Expensify/App/assets/93134676/2a24cb24-2e11-4417-a7fd-e15c83172bee">
 @ahmedGaber93 The bottom tab navigator will be at index 0, so we should check for index 1.

**Comment by ahmedGaber93** [comment] 2024-05-08 12:16
> The bottom tab navigator will be at index 0, so we should check for index 1. 

@Nodebrute So why it works on leaving room but failed on leaving group, see https://github.com/Expensify/App/issues/41128#issuecomment-2100402495

**Comment by Nodebrute** [comment] 2024-05-08 12:31
@ahmedGaber93 I've explained this in my RCA. The issue is caused by the code below, which becomes true for groups, explaining why it happens only for groups.
https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/pages/home/ReportScreen.tsx#L513-L515

Also, try these steps: create a room, copy the link, open the room in an incognito or new tab, then leave the room. The user will be redirected to concierge instead of the lastAccessedReport.

**Comment by Nodebrute** [comment] 2024-05-08 12:35
@ahmedGaber93 Feel free to reach out with any questions.

**Comment by ahmedGaber93** [comment] 2024-05-08 12:56
Thanks @Nodebrute, your root cause is correct.

But after apply the fix, when the user open room from deep link then signin then leave, User redirected to lastAccessedReport instead of concierge (video and steps here https://github.com/Expensify/App/issues/41128#issuecomment-2099651019), could you explain your fix for this here https://github.com/Expensify/App/issues/41128#issuecomment-2099805541?

**Comment by Nodebrute** [comment] 2024-05-08 13:18
@ahmedGaber93 Oh, never mind. I only added this https://github.com/Expensify/App/issues/41128#issuecomment-2099805541 in case we needed to redirect the user to concierge chat after following these https://github.com/Expensify/App/issues/41128#issuecomment-2099651019 steps. Since we now want to redirect them to the last accessed report, we don't need it anymore.

The only fix I'm suggesting is outlined in my proposal; there's nothing else needed.

**Comment by ahmedGaber93** [comment] 2024-05-08 13:23
> Since we now want to redirect them to the last accessed report, we don't need it anymore.

The expected behavior have this now
If it's a new user who opens the link from incognito mode and then leaves the room, they will be directed to the concierge.

So we need to fix it. Or I missed something?

**Comment by Nodebrute** [comment] 2024-05-08 13:58
@ahmedGaber93 This function sorts reports by last read, and we pass all reports to it. When a new user leaves a room in incognito mode, This function arranges the reports, with the concierge report ending up at index 0, indicating it's the last accessed report. So there's no need to fix this; it's already taken care of.
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/libs/actions/Report.ts#L2498

**Comment by ahmedGaber93** [comment] 2024-05-08 14:12
@Nodebrute thanks for your patience, your RCA is correct and the soluation works good.

@Nodebrute's [proposal](https://github.com/Expensify/App/issues/41128#issuecomment-2082171836) LGTM!

🎀 👀 🎀 C+ reviewed

**Comment by dylanexpensify** [comment] 2024-05-14 09:46
@Nodebrute @ahmedGaber93 can we get an update and eta on getting this mrged?

**Comment by ahmedGaber93** [comment] 2024-05-14 10:41
@dylanexpensify I reviewed the PR yesterday and left some comments, and I am waiting @Nodebrute response

**Comment by Nodebrute** [comment] 2024-05-14 12:14
@dylanexpensify I'm currently working on it.

**Comment by dylanexpensify** [comment] 2024-05-21 18:19
Sounds great!

**Comment by dylanexpensify** [comment] 2024-05-29 07:02
upcoming!

**Comment by dylanexpensify** [comment] 2024-06-05 09:20
Payment coming today!

**Comment by Julesssss** [comment] 2024-06-10 09:55
Only overdue for payment. Commenting to remove the label and I'll bump Dylan in Slack.

**Comment by dylanexpensify** [comment] 2024-06-10 10:20
Apologies, paid!

**Closed by dylanexpensify** 2024-06-10 10:20 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
