### ISSUE TITLE
[$250] Offline default avatar changes to square shape reported by @thesahindia 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12713] opened 2022-11-14 17:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Action Performed:

1. Login to an account which has more than 20 chats
2. Disconnect the internet connection
3. Navigate to search page
4. Scroll and select a chat with offline default avatar
5. Press back button to close the chat
6. Observe the avatar at chat list

## Expected Result: 
It should be circular

## Actual Result: 
It isn't circular

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.27-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201721927-b1bdd3cd-9f00-44c1-a262-65065566d98e.mp4

https://user-images.githubusercontent.com/43996225/201721957-17a5f6e8-53e6-41eb-a356-04e61dcf0b27.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668379315853719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01e68d1172df17e655
- Upwork Job ID: 1593679383488397312

**Comment by yuwenmemon** [comment] 2022-11-15 04:38
Looking into this one. Interesting that it only happens on small window frames:

https://user-images.githubusercontent.com/4741899/201827464-36774540-1f1a-4e79-aad8-962ddc779b11.mp4

**Comment by yuwenmemon** [comment] 2022-11-15 06:49
Hmmmm... I set a break point here for any sort of modification to the node that wraps the default avatar and it's children (which should capture SVG changes, etc):
<img width="914" alt="Screenshot 2022-11-14 at 10 47 23 PM" src="https://user-images.githubusercontent.com/4741899/201848406-394b1403-5df1-479d-8527-37a89b60a36c.png">

But nothing seems to happen at all when I switch between the narrow and wide views:
<img width="820" alt="Screenshot 2022-11-14 at 10 47 43 PM" src="https://user-images.githubusercontent.com/4741899/201848546-83e25b35-a18a-4b0a-a7a7-e6dd3de34fd7.png">

So that would make me _guess_ that it's some sort of style coming from higher above when the width of the view changes?

Maybe @shawnborton you might have a clue or two?

**Comment by shawnborton** [comment] 2022-11-15 14:06
Hmm honestly I am a bit stumped here. In the video, it looks like it was circular at first and then it ended up being a square? What styles would change when going back and forth from chat list to chat and then back to list?

**Comment by yuwenmemon** [comment] 2022-11-15 17:58
Yeah, maybe someone else will know what's causing it - going to see if any contributors have any idea.

**Comment by Dima-Kevanishvili** [comment] 2022-11-15 21:53
**Proposal**

The issue at hand is caused by ID collisions in the SVGs.
In the fallback avatar SVG file, there is a mask with id `mask0_1416_1459_00000085944631733157358140000010502756902080826784_`
When the screen is small enough to only display the sidebar when report is open we have this id collision and the masking for avatars get messed up.
There are numerous issues reported on this problem.
As the app uses svgr/webpack we could wait for https://github.com/gregberge/svgr/issues/322 to be implemented. 
For a quick solution we can just edit the svg file to not need a mask, that fixed the issue on my end:

```diff
diff --git a/assets/images/avatars/fallback-avatar.svg b/assets/images/avatars/fallback-avatar.svg
index dc1a1497c..9220429ae 100644
--- a/assets/images/avatars/fallback-avatar.svg
+++ b/assets/images/avatars/fallback-avatar.svg
@@ -1,25 +1,19 @@
 <?xml version="1.0" encoding="utf-8"?>
-<!-- Generator: Adobe Illustrator 26.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
-<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
-        viewBox="0 0 40 40" style="enable-background:new 0 0 40 40;" xml:space="preserve">
-<style type="text/css">
-       .st0{fill:#2ECB70;filter:url(#Adobe_OpacityMaskFilter);}
-       .st1{mask:url(#mask0_1416_1459_00000085944631733157358140000010502756902080826784_);}
-       .st2{fill:#C6C9CA;}
-       .st3{fill:#FFFFFF;}
-</style>
-<defs>
-       <filter id="Adobe_OpacityMaskFilter" filterUnits="userSpaceOnUse" x="0" y="0" width="40" height="40">
-               <feColorMatrix  type="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 1 0"/>
-       </filter>
-</defs>
-<mask maskUnits="userSpaceOnUse" x="0" y="0" width="40" height="40" id="mask0_1416_1459_00000085944631733157358140000010502756902080826784_">
-       <circle class="st0" cx="20" cy="20" r="20"/>
-</mask>
-<g class="st1">
-       <rect y="0" class="st2" width="40" height="40"/>
-       <path class="st3" d="M32.8,31.2C29.7,34.7,25.1,37,20,37c-5,0-9.5-2.2-12.6-5.6c3.1-3.6,7.7-5.9,12.8-5.9
-               C25.2,25.5,29.7,27.7,32.8,31.2z"/>
-       <path class="st3" d="M20.2,22.7c4.7,0,8.4-3.8,8.4-8.4s-3.8-8.4-8.4-8.4s-8.4,3.8-8.4,8.4S15.6,22.7,20.2,22.7z"/>
-</g>
-</svg>
+<svg viewBox="0 0 40 40" style="enable-background:new 0 0 40 40;" xmlns="http://www.w3.org/2000/svg">
+       <defs>
+               <filter id="Adobe_OpacityMaskFilter" filterUnits="userSpaceOnUse" x="0" y="0" width="40" height="40">
+                       <feColorMatrix type="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 1 0" />
+               </filter>
+               <style type="text/css">
+                       .st3 {
+                               fill: #FFFFFF;
+                       }
+               </style>
+       </defs>
+       <g class="st1">
+               <ellipse style="fill: rgb(198, 201, 202);" cx="20" cy="20" rx="20" ry="20" />
+               <path class="st3"
+                       d="M32.8,31.2C29.7,34.7,25.1,37,20,37c-5,0-9.5-2.2-12.6-5.6c3.1-3.6,7.7-5.9,12.8-5.9 C25.2,25.5,29.7,27.7,32.8,31.2z" />
+               <path class="st3" d="M20.2,22.7c4.7,0,8.4-3.8,8.4-8.4s-3.8-8.4-8.4-8.4s-8.4,3.8-8.4,8.4S15.6,22.7,20.2,22.7z" />
+       </g>
+</svg>
```

This would really be fixing a symptom instead of the problem but it is a solution.

**Comment by yuwenmemon** [comment] 2022-11-15 21:58
@Dima-Kevanishvili thank you for the great explanation here. Yeah, it looks like that svgr issue hasn't gotten any traction in a few months so maybe just editing the SVG itself to not have a mask is the way to go. @shawnborton is this something we'd want to actually edit on the SVG file itself then?

**Comment by shawnborton** [comment] 2022-11-15 22:25
Oh wow, super interesting. Yeah, I think we could just edit the contents of
the SVG file?

**Comment by yuwenmemon** [comment] 2022-11-15 22:39
Great! @Dima-Kevanishvili you're hired!

**Comment by Dima-Kevanishvili** [comment] 2022-11-15 22:48
@yuwenmemon Thanks! Is there a job listing for this on upwork?

**Comment by yuwenmemon** [comment] 2022-11-15 22:55
@Dima-Kevanishvili Feel free to move forward and we'll get one created in any case.

@maddylewis Can we create an Upwork job for this and hire @Dima-Kevanishvili?

**Comment by Dima-Kevanishvili** [comment] 2022-11-16 01:16
I will add the pull request for review and apply for the Upwork job tomorrow(It's 5 AM here atm).  Sorry for the delay in advance.

**Comment by yuwenmemon** [comment] 2022-11-16 02:47
All good :+1:

**Comment by Dima-Kevanishvili** [comment] 2022-11-16 16:17
To update the status here: 
I have the fix ready, I'm just waiting for slack invite email response in order to test the fix out with a High Traffic Account as instructed in the contributing guidelines and I'll open the PR.
I'm also waiting for the Upwork job link to apply, but as instructed I will move forward and make the PR without it if the slack invite comes first.

**Comment by yuwenmemon** [comment] 2022-11-17 00:54
Thanks, @Dima-Kevanishvili - just a heads up that I'm going OOO until the 28th so hopefully @maddylewis will be able to help find another engineer to sign off and merge your PR when it's ready.

**Comment by Dima-Kevanishvili** [comment] 2022-11-17 08:49
@aimane-chnaif Yes, I've seen that and was keen on doing this quickly, but as I stated I don't have a High Traffic Account which was also stated in the contributing guidelines and is one of the checkboxes I need to tick in the PR body. 

I've sent the email and I'm waiting for the slack invite.

If it is okay to create a PR for this particular issue without testing it with a High Traffic Account, please confirm so and I will create the PR

**Comment by Dima-Kevanishvili** [comment] 2022-11-17 08:58
@aimane-chnaif sure. Thanks!

**Comment by Dima-Kevanishvili** [comment] 2022-11-18 09:50
Hey @aimane-chnaif, can I lend that HT account today? Still haven't received an invitation

**Comment by maddylewis** [comment] 2022-11-18 18:51
sorry for the delay / thanks for the bump! 

looks like i need to post the job to Upwork and hire @Dima-Kevanishvili. let me do that now!

**Comment by thienlnam** [comment] 2022-11-18 19:00
@maddylewis Just a heads up, the automation created a job with the new updated price of $1000 for new bugs but since this is an old bug we should revert it to the default $250

**Comment by maddylewis** [comment] 2022-11-18 19:00
@thesahindia - ah, okay. let me review the job in UW. thanks for the heads up!

**Comment by maddylewis** [comment] 2022-11-18 19:05
@youssef-lr - you were auto-assigned when i added the `External` label to create the job in Upwork. I'll keep you assigned so you can assist with https://github.com/Expensify/App/issues/12713#issuecomment-1317896178: 
> Thanks, @Dima-Kevanishvili - just a heads up that I'm going OOO until the 28th so hopefully @maddylewis will be able to help find another engineer to sign off and merge your PR when it's ready.

**Comment by Dima-Kevanishvili** [comment] 2022-11-18 19:11
@maddylewis I applied for the job listing on Upwork. Is there anything more needed?

**Comment by maddylewis** [comment] 2022-11-18 19:25
@Dima-Kevanishvili - i'll need to hire you to the job. im not seeing a pending application in Upwork though. Can you double-check that you applied to the job? ty!

**Comment by Dima-Kevanishvili** [comment] 2022-11-18 19:35
@maddylewis 
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/35175081/202787767-6f0bdd60-a0d7-4f08-b9cd-b324f33cd814.png">
Also I don't know if it will redirect you to the actual proposal, but here's the link of it https://www.upwork.com/ab/proposals/1593683145336705025

**Comment by maddylewis** [comment] 2022-11-18 19:40
okay let me take another look.

**Comment by maddylewis** [comment] 2022-11-18 19:43
offer sent!

**Comment by maddylewis** [comment] 2022-11-18 19:55
I processed the payment to you already 👍 

You should receive some notification from Upwork confirming the status of it i believe!

**Comment by Dima-Kevanishvili** [comment] 2022-11-18 19:58
@aimane-chnaif Yes, I've read that, it's just that Upwork was asking whether I wanted to submit for payment or not, so I wasn't sure what to do knowing that rule.

**Comment by Dima-Kevanishvili** [comment] 2022-11-18 20:35
@aimane-chnaif Yeah it is. I always worked for a company before. Thanks for the clarification!

**Comment by shawnborton** [comment] 2022-11-22 16:39
So we're actually going to be replacing this icon with a new one for our new branding, so I would suggest we pay @Dima-Kevanishvili for the work done so far but just close this out entirely given that https://github.com/Expensify/App/pull/12796#issuecomment-1323933679 will be merged in the next day or so (cc @grgia )

Let me know what you think @maddylewis @yuwenmemon

**Comment by maddylewis** [comment] 2022-11-22 17:48
that sounds good to me - the contributor has already been paid here - https://github.com/Expensify/App/issues/12713#issuecomment-1320463568

I'll let @youssef-lr chime in before closing (@yuwenmemon is OOO for the next little while i believe).

**Comment by Dima-Kevanishvili** [comment] 2022-11-22 18:25
Hi @maddylewis , I've actually never received any notifications about that. Is it possible to double check? Or would it be better to write you on upwork about the payment?

**Comment by youssef-lr** [comment] 2022-11-22 18:38
@shawnborton @maddylewis Considering we're implementing new icons I'm good with closing this as well!

**Comment by Dima-Kevanishvili** [comment] 2022-11-23 22:33
> Hi @maddylewis , I've actually never received any notifications about that. Is it possible to double check? Or would it be better to write you on upwork about the payment?

@maddylewis Any updates on this? I appreciate you are busy, but the weekend is coming, and I'd be very thankful if we could resolve this before that.
If not, of course, it is alright.

**Comment by JmillsExpensify** [comment] 2022-11-26 22:11
Quick heads up that our US offices were closed most of this week due to national holidays.

**Comment by maddylewis** [comment] 2022-11-28 14:09
@Dima-Kevanishvili - sorry for the delay here! i thought i'd sent payment to you already! the payment should have now been processed successfully. please confirm!

**Comment by maddylewis** [comment] 2022-11-28 14:38
@Dima-Kevanishvili i would reach out to Upwork if you have additional questions about the payment. the job has been marked as paid on this end: 
<img width="639" alt="image" src="https://user-images.githubusercontent.com/38016013/204304693-58606140-bcf9-4a44-859c-7cb1eb1b4045.png">
<img width="631" alt="image" src="https://user-images.githubusercontent.com/38016013/204304736-4660132a-2529-4263-b5af-f7d56436350c.png">

**Comment by maddylewis** [comment] 2022-11-28 14:47
yep, here's the link to the new job https://www.upwork.com/jobs/~015e733169d218dbdc

will you apply there and then ill process the payment.

**Comment by maddylewis** [comment] 2022-11-28 15:03
@aimane-chnaif - paid!

**Closed** 2022-11-30 15:37 UTC
Labels: Reviewing, External, Daily, Improvement, Bug
