### ISSUE TITLE
[HOLD for payment 2023-06-23] [HOLD for payment 2023-06-21] [$2000]  Sign up for public rooms does not work correctly when using Mobile Google Chrome

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20586] opened 2023-06-12 14:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigated to a public room using a URL to enter on incognito (feel free to use this public room https://new.expensify.com/r/7012466542331406)
2. I need incognito because I’m signed in otherwise.
3. It showed the room correctly with the sign up option
4. I clicked sign up using [danrvidal+cpatest2@gmail.com](mailto:danrvidal+cpatest2@gmail.com), input my magic link

## Expected Result:
Drop me back into the public room I signed up in.

## Actual Result: 

Then I was dropped into the LHN with no more public room, all I can see is my chat concierge and when I search, I cannot find it.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (1)](https://github.com/Expensify/App/assets/43996225/67555db1-f946-4fba-a9fb-c27685feac2e)
![image](https://github.com/Expensify/App/assets/43996225/e29a6380-0ab1-47bd-b69d-c677f14ee4d1)

https://github.com/Expensify/App/assets/43996225/e1b36f10-e65e-43aa-874d-bee73e12ab5c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686348829281759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f234df843f030f2</li>
        <li>Upwork Job ID: 1668264099274833920</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-06-12 14:28
cc @marcochavezf

**Comment by mountiny** [comment] 2023-06-12 14:33
That was a github blip sorry.

**Comment by marcochavezf** [comment] 2023-06-12 16:36
Hi guys, I'm already working on a backend fix for this. The problem is that we're storing the public room ID in Onyx when the unauthenticated user wants to sign-up, but when the magic link is sent, the user could open another browser, and the public room ID could not exist on that session. I will mark this as internal.

**Comment by marcochavezf** [comment] 2023-06-12 16:50
I think yes, the solution could work when the user opens the magic link on the same browser, but it won't handle the case, for example, when an unauthenticated user opens a public room in their phone and then opens the magic link on their computer. The original plan is to remove `lastOpenedPublicRoomID` and handle that logic on the server.

**Comment by marcochavezf** [comment] 2023-06-12 18:35
Hi guys, changing my mind here, since this is a feature that's currently used for some users, and the backend fix will still take a few days, we'll need to fix this asap on the front-end.

**Comment by marcochavezf** [comment] 2023-06-12 18:43
Sounds good, yeah I also agree with the RCA since there have been major changes in the navigation. Let's do it @hoangzinh 🚀

**Comment by trjExpensify** [comment] 2023-06-12 23:04
Awesome! This is a critical bug ahead of an upcoming conference. @hoangzinh do you think you'll be able to get that PR up and in review today? Thanks!

**Comment by marcochavezf** [comment] 2023-06-16 17:35
The navigation updates introduced this regression, since this was a big refactor it was expected that there would be side effects with the navigation. Also, I already created a [GH issue](https://github.com/Expensify/Expensify/issues/292513) to add the open room cases as unauthenticated users. So I'm checking off the list.

**Comment by trjExpensify** [comment] 2023-06-21 22:58
Okay, so this one is ready for payments. That said, I'm a little unclear. Did this PR introduce a regression? https://github.com/Expensify/App/pull/20654#issuecomment-1591943496

**Comment by trjExpensify** [comment] 2023-06-23 20:05
lol, thanks TJ! 

@marcochavezf can you confirm?

**Comment by marcochavezf** [comment] 2023-06-24 14:33
Yeah correct, this PR didn't introduce any regression. In fact it fixed an issues introduced by the navigation changes.

**Comment by trjExpensify** [comment] 2023-06-26 17:01
Okay, thanks for confirming. Going off [this then](https://github.com/Expensify/App/issues/20586#issuecomment-1590144304), the payments due are: 

@hoangzinh - $3,000 for the fix & #urgency bonus 
@allroundexperts - $3,000 for C+ & #urgency bonus 

I've sent the offers [here](https://www.upwork.com/jobs/~012f234df843f030f2).

**Comment by trjExpensify** [comment] 2023-06-26 17:33
Thanks, settled up with you both!

**Closed by trjExpensify** 2023-06-26 17:33 UTC
Labels: External, Daily, Awaiting Payment, Bug
