### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500]  LHN -Task does not appear after self-assigning as a group member

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26762] opened 2023-09-05 11:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and log in
2. As user A create a group with user B
3. Create a task without assignee
4. Log in as user B and assign the ask to yourself

## Expected Result:
The task is displayed in the LHN

## Actual Result:
The task is not shown in the LHN until a comment is added to the task or draft is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/30b1950b-34c9-43c1-af5d-a83c1cb0e775

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153032df4672df452</li>
        <li>Upwork Job ID: 1699725002288009216</li>
        <li>Last Price Increase: 2023-09-14</li>
<li>Automatic offers: </li>
<ul>
<li>StevenKKC | Contributor | 26755200</li>
<li>tienifr | Contributor | 26771899</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-09-05 16:05
## Proposal

### Please state again the problem we are trying to solve in this issue.
Task does not appear on LHN after self-assigning as a group member

### What is the cause of this issue?
After user A create a task without assignee, on user B side `OpenReport` API returns task report data as below.

As you can see, task report has a `hidden` `notificationPreference`.

When user B assign a task to self, we does not set `notificationPreference`.

So the task report does not appear on LHN.

### What changes do you think we should make to solve the problem?
We can set task report's `notificationPreference` as `CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS` if task assignee is current user in `Task.editTaskAssigneeAndNavigate`.
```js
    const optimisticData = [
        ...
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${report.reportID}`,
            value: {
                ...
                notificationPreference: assigneeAccountID === currentUserAccountID ? CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS : CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN,
            },
        },
    ];
```
### What alternative solutions have you investigated? (Optional)
None.

**Comment by bfitzexpensify** [comment] 2023-09-08 11:18
Looks like there are a couple of proposals ready for review when you get a chance @eVoloshchak - thanks!

**Comment by bfitzexpensify** [comment] 2023-09-11 11:20
Friendly bump to review those proposals @eVoloshchak - thank you!

**Comment by bfitzexpensify** [comment] 2023-09-13 11:48
Another bump here @eVoloshchak

**Comment by eVoloshchak** [comment] 2023-09-14 07:15
Reviewing shortly

**Comment by eVoloshchak** [comment] 2023-09-14 20:24
Seems like this has been fixed, I can't reproduce it. @StevenKKC, @tienifr, could you please verify if this is still reproducible for you? Thanks!

https://github.com/Expensify/App/assets/9059945/4d67935a-8033-41a7-b840-0375929b0fdd

**Comment by StevenKKC** [comment] 2023-09-15 06:34
@eVoloshchak Still reproduce for me. You should create a group at first, and then create a task within a group.

**Comment by bfitzexpensify** [comment] 2023-09-18 10:49
I was also able to reproduce - as @StevenKKC pointed out, it seems this is happening specifically within a group, not a 1-to-1 DM

**Comment by eVoloshchak** [comment] 2023-09-19 12:35
Was able to reproduce it, thank you for the clarification 

I think we should proceed with @StevenKKC's [proposal](https://github.com/Expensify/App/issues/26762#issuecomment-1706959735)
While @tienifr's proposal is more detailed, @StevenKKC was the first to correctly identify the root cause and propose an appropriate fix for it

🎀👀🎀 C+ reviewed!

**Comment by StevenKKC** [comment] 2023-09-19 15:40
@eVoloshchak @techievivek 
Thanks for assigning to me, but after testing more, I think this should be fixed by BE.
After self-assigning, if we reopen the task report, `OpenReport` API returns `hidden` `notificationPreference`, so the task report does not appear again on LHN.

**Comment by StevenKKC** [comment] 2023-09-20 07:06
I agree @tienifr's proposal is more suitable than mine.
If @eVoloshchak and @techievivek approve, it would make more sense for @tienifr to fix this issue.

**Comment by techievivek** [comment] 2023-09-20 07:53
I am adding @tienifr to the GH, please collaborate on the PR.

**Comment by StevenKKC** [comment] 2023-09-20 09:44
@techievivek Please let @tienifr work on this issue, and unassign me. Thanks.

**Comment by mvtglobally** [comment] 2023-09-21 03:36
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment] 2023-09-25 13:15
Do we have an issue for the BE fix? If not, is that something you can handle @techievivek?

**Comment by bfitzexpensify** [comment] 2023-09-28 15:18
Bump on the question in https://github.com/Expensify/App/issues/26762#issuecomment-1733691454 @techievivek

**Comment by techievivek** [comment] 2023-09-29 00:22
Hey sorry, I missed the mentions, I can handle the backend fix as part of this same issue.

**Comment by techievivek** [comment] 2023-09-29 00:31
@tienifr Quick question: Given you are already optimistically setting the preference do we need the backend fix here? Does the backend override the notification preference once the requests succeed? I can't see that happening in the backend code.

**Comment by techievivek** [comment] 2023-09-29 00:55
Ok, took a look at the backend code for `openReport` and it looks like we reset the notification preference to` hidden` so I think if it is a task report and if we have shared that with the assignee then we will need to return the preference as `always` and not hidden.

**Comment by bfitzexpensify** [comment] 2023-10-03 16:19
@techievivek is this something we want to handle entirely internally?

**Comment by techievivek** [comment] 2023-10-06 14:41
We will need to make changes on both the sides, I can start working on the backend change and once that is done @tienifr can make the frontend changes.

**Comment by techievivek** [comment] 2023-10-11 12:14
Sorry, lost my focus because of wave8 priorities, will try to get this done soon. Sorry for the delay.

**Comment by techievivek** [comment] 2023-10-18 05:49
Have got some bandwidth to look into it now.

**Comment by bfitzexpensify** [comment] 2023-10-24 22:48
How is this one looking @techievivek?

**Comment by techievivek** [comment] 2023-10-30 09:07
Added the Auth PR here: https://github.com/Expensify/Auth/pull/9069
Sending in the web-e PR to push the updated notification preference.

**Comment by techievivek** [comment] 2023-10-30 09:51
Web-E PR is here: https://github.com/Expensify/Web-Expensify/pull/39438

This is how it looks now.

https://github.com/Expensify/App/assets/35863227/1f9e8c7e-8778-4ec9-96f5-7c482e3d84c3

**Comment by techievivek** [comment] 2023-11-01 08:55
This is still being reviewed, we are hoping to get this merged today.

**Comment by bfitzexpensify** [comment] 2023-11-03 14:33
Nice, looks like it's been merged.

**Comment by bfitzexpensify** [comment] 2023-11-03 18:25
Merged, not overdue

**Comment by techievivek** [comment] 2023-11-06 07:04
@tienifr changes are on staging, you can work on the App PR now.

**Comment by bfitzexpensify** [comment] 2023-12-01 17:52
Payment summary:

Contributor: @tienifr to be paid $500 via Upwork ✅ 
C+: @eVoloshchak to be paid $500 via manual request

**Comment by techievivek** [comment] 2023-12-05 06:58
Not overdue, payment is in progress.

**Comment by techievivek** [comment] 2023-12-11 12:11
Gentle bump @eVoloshchak

**Comment by techievivek** [comment] 2023-12-13 04:39
Not overdue, bumped @eVoloshchak on slack.

**Comment by eVoloshchak** [comment] 2023-12-13 21:11
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that caused this, this is the original implementation for both back- and frontend
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed here

**Regression Test Proposal**

1. Login with A and B
2. On A, go to a group chat with B as a member
3. Create a task without assignee
4. On B, self-assign the task
5. Verify that the task report is displayed in LHN

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment] 2023-12-13 22:44
$500 payment approved for @eVoloshchak based on [this comment](https://github.com/Expensify/App/issues/26762#issuecomment-1836537971).

**Comment by bfitzexpensify** [comment] 2023-12-14 14:29
Regression steps sound good to me. Added them via https://github.com/Expensify/Expensify/issues/349649. Closing this one out, thanks everyone.

**Closed by bfitzexpensify** 2023-12-14 14:29 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
