### ISSUE TITLE
Web - 2FA codes disappear after minimizing screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21803] opened 2023-06-28 14:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open setting
2. Click Security
3. Click Two-factor authentication
4. Shrink the screen again

## Expected Result:
2FA codes not disappear after minimizing screen

## Actual Result:
2FA codes disappear after minimizing screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d686aba2-bc4e-4676-8dd9-d5c9c37e5836

https://github.com/Expensify/App/assets/93399543/b3d6507c-309b-4813-b043-b82c03540708

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687867309909039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nitin-kukreti** [comment] 2023-06-28 15:54
this is duplicate of   #21407

**Comment by nitin-kukreti** [comment] 2023-06-28 16:24
this guy @kavimuru   is posting same issue with different name

**Comment by adelekennedy** [comment] 2023-06-29 23:41
[dupe](https://github.com/Expensify/App/issues/20611)

**Closed by adelekennedy** 2023-06-29 23:41 UTC
Labels: Daily, Bug

**Comment by kavimuru** [comment] 2023-06-30 12:08
@nitin-kukreti FYI: I am not the bug reporter. kbecciv and I are reviewing the bugs posted in the slack channel and creating a GH ticket. I am not sure if you are in that slack channel. We do check for dupes always, sometimes it gets missed. Now there are lots of bugs reported by contributors everyday. Thanks.

**Comment by nitin-kukreti** [comment] 2023-06-30 15:07
@kavimuru  I was misunderstood @esh-g  already informed me about this. I wrote that that because you himself has submitted proposal for this job so I thought it was intentional.
