### ISSUE TITLE
[$1000]  Error in JS console when pressing the "Login" button or the "Create a New Account" link in the footer of Magic Code page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19228] opened 2023-05-18 22:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app.
2. Navigate to the Magic Code page.
3. Scroll down and click on either login or create a new account link.

## Expected Result: 
This should cause no error in the console.
## Actual Result: 
An error is displayed in the console when the login button or the account creation link is clicked.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/faa1c1c1-af2a-4ad5-9fa2-a3e2304281f0

https://github.com/Expensify/App/assets/43996225/0683ce00-72cc-4299-ab08-7c33740eed24

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Harshdeepjoshi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684258502046179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a33b3f9d19c242e2</li>
        <li>Upwork Job ID: 1660556947910672384</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-05-18 23:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error in console when pressing the "Login" button or the "Create a New Account" link in the footer of Magic Code page.
### What is the root cause of that problem?
There is no null check here for this.wrapperView which it may be null between re-render
https://github.com/Expensify/App/blob/2090c0525de9cd87b8c738e9ccb7dafe79a9a229/src/components/Hoverable/index.js#L100-L105
https://github.com/Expensify/App/blob/2090c0525de9cd87b8c738e9ccb7dafe79a9a229/src/components/Hoverable/index.js#L83-L91
### What changes do you think we should make in order to solve the problem?
add null check for this.wrapperView in onBlur statment.
```javascript
onBlur={(el) => {
    if (!_.isNull(this.wrapperView) && this.wrapperView.contains(el.relatedTarget)) {
        return;
    }
    this.setIsHovered(false);
}}
```                
### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2023-05-18 23:48
Commented here: https://expensify.slack.com/archives/C049HHMV9SM/p1684453691932129?thread_ts=1684258502.046179&cid=C049HHMV9SM

**Comment by jliexpensify** [comment] 2023-05-22 03:32
Getting a second opinion from the team here - https://expensify.slack.com/archives/C01SKUP7QR0/p1684725923013839

**Comment by Harshdeepjoshi** [comment] 2023-05-22 10:46
# Proposal 
([Originally posted on Slack with bug report](https://expensify.slack.com/archives/C049HHMV9SM/p1684258719633869?thread_ts=1684258502.046179&cid=C049HHMV9SM))
The issue occurs due to the `this.wrapperView` being set to null by default.
https://github.com/Expensify/App/blob/7ad2be02a9e7c9dc19e8a6556d3c8efde5ba5721/src/components/Hoverable/index.js#L18
so when this check executes. https://github.com/Expensify/App/blob/7ad2be02a9e7c9dc19e8a6556d3c8efde5ba5721/src/components/Hoverable/index.js#LL101C17-L101C17
it gives error
`Cannot read properties of null (reading 'contains')` as the state might not be set yet and still be null
### Solution

We can simply add a null check for this.wrapperView in onBlur statement. (here [src/components/Hoverable/index.js](https://github.com/Expensify/App/blob/7ad2be02a9e7c9dc19e8a6556d3c8efde5ba5721/src/components/Hoverable/index.js#LL101C17-L101C17)) to ensure that this.wrapperView is not null while executing the condition

like this
``` jsx
if (this.wraperView != null && this.wrapperView.contains(el.relatedTarget)) {
return;
}
 ```     
### Result 

https://github.com/Expensify/App/assets/88710727/de1c2206-21fa-4d4d-b700-b78cf5b1429e

**Comment by VitaliiP-0205** [comment] 2023-05-22 12:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error in console when pressing the "Login" button or the "Create a New Account" link in the footer of Magic Code page.
### What is the root cause of that problem?
The issue occurs due to the `this.wrapperView` being set to null by default.
### What changes do you think we should make in order to solve the problem?
This issue can solve by adding null check for this.wrapperView in onblur event.
line 101 in here: [https://github.com/Expensify/App/blob/main/src/components/Hoverable/index.js](url)
<code>if (this.wraperView != null && this.wrapperView.contains(el.relatedTarget)) {
return;
}</code>
### What alternative solutions did you explore? (Optional)

**Comment by mollfpr** [comment] 2023-05-22 13:08
@jliexpensify @dangrous I believe the compensation for console error is $500?

[Proposal](https://github.com/Expensify/App/issues/19228#issuecomment-1553774770) from @ahmedGaber93 looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by dangrous** [comment] 2023-05-22 17:08
Works for me! Assigning now..

**Comment by Harshdeepjoshi** [comment] 2023-05-23 01:19
@dangrous @mollfpr I first proposed similar solution on slack before everyone and I am reporter of this bug as well. I also linked the slack proposal on this issue as per the rules. Shouldn't I be selected for this job ([like here](https://github.com/Expensify/App/issues/14748#issuecomment-1420008526)) if my proposal is correct?

**Comment by mollfpr** [comment] 2023-05-23 02:24
>Note: whilst you may optionally propose a solution for that job on Slack, solutions are ultimately reviewed in GitHub. The onus is on you to propose the solution on GitHub, and/or ensure the issue creator will include a link to your proposal.

@Harshdeepjoshi Sorry, even though you posted the solution first in Slack, the reviewer wouldn't know that, and not possible for us to always check the Slack thread. I even didn't notice that you post a [proposal](https://expensify.slack.com/archives/C049HHMV9SM/p1684258719633869?thread_ts=1684258502.046179&cid=C049HHMV9SM) in Slack, because you're not using the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md), and maybe that's the reason the issue creator didn't include your proposal. 

The idea of leaving a proposal in your bug report is, the issue creator will post it right after the Github issue is created. So, the first proposal is still what we have in the GitHub issue, and following the proposal template is essential to understand your solution.

cc @dangrous @jliexpensify

**Comment by jliexpensify** [comment] 2023-05-23 04:07
@mollfpr , in regards to this:

> I believe the compensation for console error is $500?

Is there a link you can share where this was discussed? This is the first time I've come across a console error, cheers!

**Comment by mollfpr** [comment] 2023-05-23 04:25
@jliexpensify I only have an example of it https://github.com/Expensify/App/issues/17876#issuecomment-1520564078

But I'm not sure because this is not a DEV error 🤷‍♂️

**Comment by jliexpensify** [comment] 2023-05-23 04:55
Cheers, getting some clarity internally here - https://expensify.slack.com/archives/C01SKUP7QR0/p1684817728719929?thread_ts=1684725923.013839&cid=C01SKUP7QR0

**Comment by ahmedGaber93** [comment] 2023-05-23 20:47
@mollfpr [PR](https://github.com/Expensify/App/pull/19488) is ready for review.

**Comment by jliexpensify** [comment] 2023-05-23 22:33
@mollfpr - all good, we can keep these JS issues at $1000 for consistency's sake.

**Comment by dangrous** [comment] 2023-05-25 19:29
Huh, good question. I will start a discussion!

**Comment by jliexpensify** [comment] 2023-05-27 01:20
Good discussion @dangrous - it looks like we will pay this one. 

It looks like the other PR is still ongoing - so maybe let's pay once it's actually deployed to prod and properly tested? @mollfpr and @ahmedGaber93 , can you test this and share an update? Thanks!

**Comment by ahmedGaber93** [comment] 2023-05-28 18:38
@jliexpensify

https://github.com/Expensify/App/assets/41129870/f2f7724f-586d-46b6-b3e2-93f15f1ab7d5

**Comment by jliexpensify** [comment] 2023-05-30 22:38
Thanks for checking!

@mollfpr and @ahmedGaber93 - after discussing it with the team, @dangrous and I will pay 50% (i.e. $500), since this was resolved with the other PR. Sound good?

**Comment by mollfpr** [comment] 2023-05-31 00:05
@jliexpensify sounds good to me!

**Comment by jliexpensify** [comment] 2023-05-31 01:41
@ahmedGaber93 what's your Upworks profile? Cheers

**Comment by ahmedGaber93** [comment] 2023-05-31 01:42
@jliexpensify sounds good to me, too.

**Comment by ahmedGaber93** [comment] 2023-05-31 01:47
@jliexpensify https://www.upwork.com/freelancers/~012883934e2c4dc4e7

**Comment by jliexpensify** [comment] 2023-05-31 02:03
Cheers, invites sent - will pay once accepted.

**Comment by jliexpensify** [comment] 2023-05-31 02:14
Paid, and job closed - thanks everyone!

**Closed by jliexpensify** 2023-05-31 02:14 UTC
Labels: Reviewing, External, Daily, Bug
