### ISSUE TITLE
Android – Sign in – Able to dismiss the Onboarding modal using back button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49990] opened 2024-10-01 13:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5027336
**Email or phone of affected tester (no customers):** ponikarchuks+1311024@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. When Onboarding modal appears tap on back button on your device few times

## Expected Result:
Onboarding modal present

## Actual Result:
Onboarding modal disappears

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/84e8dd2d-2883-44fe-a61c-462b596e386d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by blazejkustra** [comment] 2024-10-01 13:41
I think it is connected to https://github.com/Expensify/App/pull/49586, do you know how we prevented this in the past? @allgandalf

**Comment by johnmlee101** [comment] 2024-10-01 16:32
Bump @allgandalf !

**Comment by jasperhuangg** [comment] 2024-10-01 16:36
This is a previous issue that is similar @johnmlee101 https://github.com/Expensify/App/issues/47246

**Comment by johnmlee101** [comment] 2024-10-01 17:26
Seems like an inconsistent issue. Think we should remove the blocker and just create an issue to fix?

**Comment by johnmlee101** [comment] 2024-10-01 17:27
Or ask for a retest if someone has it up and ready?

**Comment by blazejkustra** [comment] 2024-10-01 18:08
I have a fix for it 🥳 If you look closely at the video the onboarding modal was opened twice which allowed to dismiss the modal. Here is a video when onboarding modal is opened once:

https://github.com/user-attachments/assets/ee240145-9a11-4be5-9c3e-b43dca649a48

**Comment by blazejkustra** [comment] 2024-10-01 18:23
@johnmlee101 I was able to reproduce reliably on android, I would say it is a deploy blocker. PR is ready [here](https://github.com/Expensify/App/pull/50015).

**Comment by johnmlee101** [comment] 2024-10-01 20:43
Put the CP request

**Comment by jasperhuangg** [comment] 2024-10-01 21:27
QA retest request [here](https://expensify.slack.com/archives/C9YU7BX5M/p1727818027479169) cc @Expensify/applause

**Comment by isagoico** [comment] 2024-10-01 21:48
Issue is not reproducible on SG S10+ or Pixel6 🎉 

https://github.com/user-attachments/assets/519190a7-bf60-4124-b0dd-cae5009c5945

**Comment by mountiny** [comment] 2024-10-02 10:32
No payments required here as the authors handled the fix, closing

**Closed by mountiny** 2024-10-02 10:32 UTC
Labels: Reviewing, Engineering, Weekly, Bug

**Comment by alexpensify** [comment] 2024-10-22 18:22
@johnmlee101 - is this notice accurate or a false alarm?

**Comment by johnmlee101** [comment] 2024-11-12 16:39
Looks like a false alarm, I don't see the linked issue at all
