### ISSUE TITLE
[HOLD for payment 2023-07-13] [$1000] Error occurs when sending a message to the same unregistered email address from different accounts

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18800] opened 2023-05-11 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app on Chrome or any platform
2. Sign in with any account
3. Click on the search icon
4. Search for any email address that is not registered with the Expensify app
5. Send any message
6. Next, open the app on any other platform
7. Sign in with any other account
8. Click on the search icon
9. Search for the same email address
10. Send any message

## Expected Result:
The message is sent without any error
## Actual Result:
The message is not sent and an error is displayed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8aa26279-1d56-4065-ad39-f762b3432e22

https://github.com/Expensify/App/assets/43996225/190de738-381e-406d-9bdb-a655ac693f83

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683736386613359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161ab1e5ea20a1e8a</li>
        <li>Upwork Job ID: 1658591249549860864</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-05-16 21:51
Was able to repro this on iOS Safari and iOS Chrome

**Comment by koko57** [comment] 2023-05-18 13:28
Hi I'm Agata from Callstack - expert contributor group - maybe I could help with this one?

**Comment by koko57** [comment] 2023-05-18 14:57
Backend issue? Let's call the first account A and the second - B. For acc. A both OpenReport and AddCommend requests come with 200 jsonCode. For the acc B for the first OpenReport request I get 408

![Screenshot 2023-05-18 at 16 49 08](https://github.com/Expensify/App/assets/28020445/0712a49d-9101-4e9c-aa75-fe74b8ace1fb)
then for AddComment 

![Screenshot 2023-05-18 at 16 49 40](https://github.com/Expensify/App/assets/28020445/2490c29d-5c2f-4cb8-a0d1-1955adcebd94)
and every time I switch to another report and switch back to the report with the issue i get 403

![Screenshot 2023-05-18 at 16 49 59](https://github.com/Expensify/App/assets/28020445/07f34f2f-9307-4f76-b29f-1b5db50e99fc)

Then, I've got an email for the yet non-existing account with the message from the acc. A (the one for which the request succeed) and logged in. I tried to send a message to the acc. B (the one failing) - a second chat was created
 
![Screenshot 2023-05-18 at 16 12 41](https://github.com/Expensify/App/assets/28020445/133143ef-4013-4d11-a38f-edcfdcf6b007)

When I logged out from acc. B and then logged in back the chat with error was gone.

**Comment by koko57** [comment] 2023-05-19 13:49
I still cannot find anything that would indicate that the problem lies on the frontend side.

**Comment by techievivek** [comment] 2023-05-22 12:39
@koko57 Thanks for looking into it. I did some log tracing and this does seem to be related to a recent backend change.

**Comment by stephanieelliott** [comment] 2023-05-24 16:58
Ok, in that case we need to update this one to `Internal`, correct @techievivek?

**Comment by techievivek** [comment] 2023-05-28 06:42
@stephanieelliott Yes, just added the internal label. It is possible that recent changes in the authentication process for Google and Apple sign-in features on newDot may be the cause of this issue. Let me take a look into it.

**Comment by techievivek** [comment] 2023-06-01 04:52
Not overdue, sending a PR today.

**Comment by techievivek** [comment] 2023-06-02 18:15
Bringing a discussion to #eng-chat channel to discuss this further because I am not able to find a straight forward solution for this.

**Comment by stephanieelliott** [comment] 2023-06-05 18:24
Thanks for raising this @techievivek! Hopefully we can source some ideas for this one https://expensify.slack.com/archives/C03TQ48KC/p1685729854661869

**Comment by techievivek** [comment] 2023-06-06 05:34
I have reached out to Marco 1:1 to understand the bug better here and a possible fix for this. Thanks.

**Comment by techievivek** [comment] 2023-06-08 13:07
After discussing this on slack, it looks like we have a potential solution, but I have started another [discussion](https://expensify.slack.com/archives/C03U7DCU4/p1686228770796869) in the product channel to confirm the expected behaviour in case of messaging unregistered users. Once we all agree on an expected behaviour, I can start working on the PR.

**Comment by stephanieelliott** [comment] 2023-06-12 20:34
Seems like there is a consensus[ in Slack](https://expensify.slack.com/archives/C03U7DCU4/p1686228770796869), is there anything else we need in order to solve this @techievivek?

**Comment by stephanieelliott** [comment] 2023-06-14 21:27
Hey @techievivek any update here?

**Comment by techievivek** [comment] 2023-06-15 05:17
@stephanieelliott Sorry I was ooo for last 3 days, we have reached consensus on a solution so I am going to push a PR today.

**Comment by stephanieelliott** [comment] 2023-06-15 19:06
Reapplying the `Bug` label to get another BZ member on this while I am OOO til July 3. Thanks @jliexpensify,  I'll grab this back from you when I return!

**Comment by jliexpensify** [comment] 2023-06-16 07:37
Hi @techievivek just catching up here - since you're pushing the PR, is it internal then?

**Comment by techievivek** [comment] 2023-06-16 07:38
@jliexpensify Yes.

**Comment by jliexpensify** [comment] 2023-06-16 07:58
There isn't any immediate payment/s to @aimane-chnaif right? :)

**Comment by techievivek** [comment] 2023-06-16 08:06
@jliexpensify Currently, there are no pending payments. However, we will need to process a reporting bonus for @adeel0202 once the PRs are deployed. Although @koko57 worked on the issue, as they are part of the expert group (Callstack), I assume we handle their payment separately, correct?

**Comment by jliexpensify** [comment] 2023-06-16 08:16
Ok, awesome! Thanks for catching me up - I see that @adeel0202 has already been invited in Upworks so I can sort that out once you deploy the PR. And yes, Callstack invoices us separately (I believe).

**Comment by techievivek** [comment] 2023-06-19 06:44
Both Auth and Web-E PR are ready for review, and I have bumped the reviewers to take a look at it. Thanks

**Comment by techievivek** [comment] 2023-06-29 03:36
Still being reviewed.

**Comment by jliexpensify** [comment] 2023-07-04 04:32
@stephanieelliott I'm headed OOO this week, but looks like you're back!

**Comment by techievivek** [comment] 2023-07-04 05:29
We are almost there https://github.com/Expensify/Auth/pull/8121#pullrequestreview-1511130409, waiting for John to give it a final review.

**Comment by stephanieelliott** [comment] 2023-07-11 01:15
This was deployed to Auth on July 6! Assuming no regressions, we'll pay this on 6/13

**Comment by stephanieelliott** [comment] 2023-07-17 06:11
Issued payment to @adeel0202 
@aimane-chnaif extended the offer to you on Upwork, can you accept when you get a chance?

**Comment by stephanieelliott** [comment] 2023-07-19 07:42
@aimane-chnaif extended the offer on Upwork, can you accept when you get a chance? https://www.upwork.com/nx/wm/offer/25572330

**Closed** 2023-07-24 19:27 UTC
Labels: Reviewing, Daily, Internal, Bug
