### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] Dev: Android/iOS - Invalid prop console error

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20589] opened 2023-06-12 14:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
## Expected Result: 
No console error
## Actual Result: 
Console error appears (invalid props.style key `cursor`)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25-4
**Reproducible in staging?:**  Dev 
**Reproducible in production?:** Dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/2549cca2-cfe6-4cb9-a9b8-70a7cf7c3dee" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686120988945439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0151ecf2b81452ae95</li>
        <li>Upwork Job ID: 1669423474662707200</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-06-14 21:58
Hey @kavimuru are the repro steps really just `Open any chat`? I am not able to reproduce this on iOS nor Android

**Comment by bernhardoj** [comment] 2023-06-15 03:29
@stephanieelliott yes. You will see the warning box at the bottom when you open a chat (dev only I guess)
<img width="424" alt="image" src="https://github.com/Expensify/App/assets/50919443/da12eaa3-f7da-48c1-aa46-90f8ef1b7788">

**Comment by stephanieelliott** [comment] 2023-06-15 19:16
Reapplying the `Bug` label to get another BZ member on this while I am OOO til July 3. Thanks @joekaufmanexpensify   I'll grab this back from you when I return!

**Comment by joekaufmanexpensify** [comment] 2023-06-15 19:25
Sounds good! I'm going to ask an engineer to repro here, since looks like this is a dev only error.

**Comment by joekaufmanexpensify** [comment] 2023-06-15 19:26
[Asked](https://expensify.slack.com/archives/C03TQ48KC/p1686857196490749)

**Comment by joekaufmanexpensify** [comment] 2023-06-15 20:08
Sounds good! Not sure why an engineer was not assigned after your comment saying you'd reviewed. Assigning one now for sign off on your proposal, per [this](https://expensify.slack.com/archives/C02NK2DQWUX/p1686668655175609)!

**Comment by neil-marcellini** [comment] 2023-06-16 21:42
@dukenv0307 's [proposal](https://github.com/Expensify/App/issues/20589#issuecomment-1587483826) looks good to me too! We should also delete styles.cursorPointer after we update everything to use styles.cursor.cursorPointer.

**Comment by neil-marcellini** [comment] 2023-06-21 16:28
Yes I'm sure there are many other issues but that seems irrelevant.

**Comment by joekaufmanexpensify** [comment] 2023-06-26 13:08
@dukenv0307 offer sent for $1,000! ($500 will be issued as bonus)

**Comment by joekaufmanexpensify** [comment] 2023-06-26 13:09
@parasharrajat offer sent for $1,000! ($500 will be issued as bonus)

**Comment by joekaufmanexpensify** [comment] 2023-06-26 13:10
@bernhardoj offer sent for $250!

**Comment by joekaufmanexpensify** [comment] 2023-06-26 13:10
@parasharrajat Could you please complete your portion of the BZ checklist when you have a chance? Thanks!

**Comment by joekaufmanexpensify** [comment] 2023-06-28 20:01
Great, thanks! BZ checklist is complete.

**Comment by joekaufmanexpensify** [comment] 2023-06-29 18:55
All set to issue payment here (besides Rajat's, which is on hold for the new process).

**Comment by joekaufmanexpensify** [comment] 2023-06-29 19:04
@dukenv0307 $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-06-29 19:05
@bernhardoj $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-06-29 19:06
This one is all set for now. As soon as we're able to pay @parasharrajat , we can close this out!

**Comment by joekaufmanexpensify** [comment] 2023-07-03 13:13
Not overdue. Pending being able to pay rajat here.

**Comment by joekaufmanexpensify** [comment] 2023-07-05 12:53
Payment to rajat still on hold. Bumped in Slack.

**Comment by joekaufmanexpensify** [comment] 2023-07-10 14:03
Still on hold

**Comment by joekaufmanexpensify** [comment] 2023-07-17 13:13
[Bumped in Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1689599617076879)

**Comment by joekaufmanexpensify** [comment] 2023-07-31 13:58
Bumped in Slack.

**Comment by joekaufmanexpensify** [comment] 2023-08-02 19:29
Great, thanks! Copying the payment message down so it's clear for the individual who pays. This qualifies for speed bonus, so we need to issue the following payments here:

- @dukenv0307 - $1,500 (PR +speed bonus). Paid via upwork. 
- @parasharrajat - $1,500 (C+ review + speed bonus). Pending payment via NewDot. 
- @bernhardoj - $250 (reporting bonus). Paid via uppork.

**Comment by joekaufmanexpensify** [comment] 2023-08-02 19:34
Closing for now, since all that's left is NewDot payment (which has been requested)!

**Closed by joekaufmanexpensify** 2023-08-02 19:34 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-03 03:10
Reviewed details for @parasharrajat. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
