### ISSUE TITLE
[HOLD for payment 2024-03-20] [$500] Update archive messages for threads

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#36389] opened 2024-02-13 01:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Latest
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** Part of https://github.com/Expensify/Expensify/issues/308026
**Issue reported by:** @neil-marcellini 
**Slack conversation:**

## Action Performed:

1. Log into new expensify, this account is the admin
2. Create a workspace if needed
3. Invite a member to the workspace (unshare@expensifail.com)
4. On another device (incognito window), log in as the member
5. Make sure you're in the "most recent" priority mode so you can see all chats in the LHN
6. Create a manual money request as the member, sent to the admin workspace
7. Send a message in the top level expense chat, the expense report, and the transaction report
8. Go back to the top level expense chat
9. Create a thread on your own message and leave it open
10. Verify that the top level expense chat, the expense report, and the transaction report show in the LHN
11. As the admin remove the member from the workspace
12. As the member, verify that the thread updates to be archived
13. Verify that the top level expense chat, the expense report, and the transaction report show as **archived** in the LHN
14. Verify the expense chat is archived, as well as all sub reports/chats

## Actual/Expected Result:
- [ ] The archive message says "workspace chat" but it should say only "chat" so it makes sense in general
- [ ] The archive message says "Hidden" instead of the removed user's name/email, in the top level thread and the transaction report, when viewed by the admin
- [ ] The archive messages says the user's name/email instead of "you" in all chats
- [ ] The archive message says "Hidden" instead of "you", in the top level thread and the transaction report, when viewed by the member
- [ ] The archive message displays "Unavailable workspace" in the policy expense chat, when viewed by the member
- [ ] The top level thread and transaction report do not show "(archived)" in the report name for the member

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/Expensify/assets/26260477/ea5a0cdc-5bbf-452e-881c-e9e0bf797a2b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01580b4cfd3788d07f</li>
        <li>Upwork Job ID: 1757211011325919232</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2024-02-16 16:22
> Bump on this @akinwale

Missed this. I'll review soon.

**Comment by akinwale** [comment] 2024-02-18 08:03
@neil-marcellini The video in the OP doesn't seem to be loading.

**Comment by akinwale** [comment] 2024-02-18 08:08
We can move forward with @rayane-djouah's proposal since the suggested solution takes care of the raised items.

@rayane-djouah In the future, please do not create a PR prior to being assigned to an issue, unless you've been explicitly asked to do so.

🎀👀🎀 C+ reviewed.

**Comment by twisterdotcom** [comment] 2024-02-20 16:49
Bump @neil-marcellini

**Comment by twisterdotcom** [comment] 2024-02-23 17:07
@neil-marcellini can we assign @rayane-djouah?

**Comment by neil-marcellini** [comment] 2024-02-23 18:40
Woops sorry for the long delay, looking now

**Comment by neil-marcellini** [comment] 2024-02-23 18:45
I agree that @rayane-djouah's [proposal](https://github.com/Expensify/App/issues/36389#issuecomment-1942380687) looks great! Please go ahead and raise a PR.

**Comment by neil-marcellini** [comment] 2024-03-05 23:29
@rayane-djouah would you please provide an update? Is there a PR in progress yet?

**Comment by neil-marcellini** [comment] 2024-03-11 22:05
Thanks, I lost track of that one.

**Comment by neil-marcellini** [comment] 2024-03-11 22:30
Just merged the PR 🚀

**Comment by akinwale** [comment] 2024-03-20 15:22
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. This is an update for displayed messages and text.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify
2. Log in as the admin of a workspace, or create a workspace if none exist yet.
3. Invite a member to the workspace.
4. Log in as the invited member in a separate browser session.
5. Ensure that the "Most recent" priority mode is enabled in Profile > Preferences > Priority mode.
6. Create a manual money request to the workspace as the invited member.
7. Send a message at the top level chat, the expense report, and the IOU report.
8. Navigate back to the top level expense chat.
9. Create a thread on the message and leave it open.
10. Verify that the top level chat, the expense report, the IOU report and the thread show up in the LHN
11. As the workspace admin, remove the member from the workspace.
12. As the removed member, verify that the thread is archived.
13. Verify that the top level chat, the expense report, and the IOU report are shown as archived in the LHN
14. Verify that the archive message displays only "chat" instead of "workspace chat"
15. Verify that the archive message says removed user's name/email, in the top level thread and the IOU report, when viewed by the workspace admin.
16. Verify that the archive message says "you", in the top level thread and the IOU report, when viewed as the removed member.
17. Verify that the top level thread and IOU report show "(archived)" in the report name.

Do we agree 👍 or 👎?

**Comment by twisterdotcom** [comment] 2024-03-20 16:37
The automatic offers haven't loaded for me all day. @akinwale and @rayane-djouah I assume you just didn't get one right?

I'm gonna just send a fresh one.

**Comment by akinwale** [comment] 2024-03-20 16:40
@twisterdotcom If you're trying to load the offers from the links generated by melvinbot in the GH issue messages, those links are broken.

**Comment by twisterdotcom** [comment] 2024-03-20 16:41
DW, I just found them in Upwork.

**Closed** 2024-03-20 16:44 UTC
Labels: External, Weekly, Awaiting Payment, Bug
