### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] Search - Empty list does not turn to empty state screen until page is revisited

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44803] opened 2024-07-04 04:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #44385 
**Version Number:**  9.0.4-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User has only unpaid expenses.

1. Go to staging.new.expensify.com
2. Go to Search > Shared.
3. Select all the expenses.
4. Click on the dropdown > Delete.
5. Delete the expenses.

## Expected Result:
The empty state screen will show up after deleting all the expenses.

## Actual Result:
The list is empty with field row after deleting all the expenses.
It only shows empty state screen after revisiting the page.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/b3a77ac2-d30f-4e4d-8994-f5a131f97d63

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-07-04 04:05
@MariaHCD  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors


We think that this bug might be related to  #vip-vsb

**Comment by kosmydel** [comment] 2024-07-04 09:44
Hey, I'm from Software Mansion and I will investigate this issue.

**Comment by MariaHCD** [comment] 2024-07-04 09:52
cc: @luacmartins @WojtekBoman for visibility

**Comment by kosmydel** [comment] 2024-07-04 10:57
Hey,

I've prepared a draft of PR with a fix. 

---

However, I have one minor question about the backend response.

The root cause of this issue was that we assumed that the backend clears all unneeded keys in the `SearchResults` `data` snapshot. 

The `data` object:
```
{
    "personalDetailsList": {
        // ...
    },
    "report_3463587888536025": {
        // ...
    },
    "transactions_8980645231662891791": {
        // ...
    }
}
```

The backend response clears only `transactions` key: 
```json
        {
            "key": "snapshot_753841854",
            "onyxMethod": "merge",
            "value": {
                "data": {
                    "transactions_6736520156568300571": null
                }
            }
        }
```

I think that it is fine to leave the `personalDetailsList`, as it might be hard to determine which accounts should be deleted. My question is if we need to remove `report`s.

cc @luacmartins

**Comment by luacmartins** [comment] 2024-07-04 15:21
Nice catch @kosmydel. We should also delete the report data. I'll work on a backend fix for that.

**Comment by luacmartins** [comment] 2024-07-04 16:19
PR [here](https://github.com/Expensify/Auth/pull/11480)

**Comment by luacmartins** [comment] 2024-07-04 20:27
The back end PR won't be enough to fix this since we'll still have data (personalDetailsList) in the snapshot key. Maybe [shouldShowEmptyState](https://github.com/Expensify/App/blob/55546bb6066fcc14a9005d512554e45c1d159166/src/components/Search/index.tsx#L93) should check for the length of the visible data, not just any data in Search

**Comment by kosmydel** [comment] 2024-07-04 20:30
> The back end PR won't be enough to fix this since we'll still have data (personalDetailsList) in the snapshot key. Maybe [shouldShowEmptyState](https://github.com/Expensify/App/blob/55546bb6066fcc14a9005d512554e45c1d159166/src/components/Search/index.tsx#L93) should check for the length of the visible data, not just any data in Search

You are right. In the PR I've added a check for the transactions thread existence.

**Comment by luacmartins** [comment] 2024-07-04 20:40
Hmm I think this is fine for now, but maybe we should think of a more generic solution since we'll support other data types soon. I think using the visible data, e.g. `sortedData` instead of specific keys might be better long term.

**Comment by luacmartins** [comment] 2024-07-04 20:42
Anyways, I merged the PR since that fixes the issue along with the backend PR.

**Comment by mountiny** [comment] 2024-07-05 10:04
Pending a CP validation in staging

**Comment by luacmartins** [comment] 2024-07-05 13:27
FYI this will fail until the Auth PR is deployed

**Comment by sonialiap** [comment] 2024-07-18 10:27
@MariaHCD @luacmartins I see three people on the PR, two are freelancers. I see fedirjh completed the checklist and neonbhai left a comment. Should they both be paid for the review?

**Comment by MariaHCD** [comment] 2024-07-18 12:24
I believe only fedirjh should be compensated for their C+ review. Will let @luacmartins confirm.

**Comment by luacmartins** [comment] 2024-07-18 15:23
Correct, we only need to compensate @fedirjh for the review!

**Comment by sonialiap** [comment] 2024-07-22 10:35
Payment summary:
- @fedirjh $250 - please request in ND

**Comment by JmillsExpensify** [comment] 2024-07-22 20:51
$250 approved for @fedirjh

**Comment by sonialiap** [comment] 2024-07-24 09:39
Last step here is the [checklist](https://github.com/Expensify/App/issues/44803#issuecomment-2229333804)

@fedirjh I believe this falls to you as the C+?

**Comment by sonialiap** [comment] 2024-07-25 15:09
Thanks Fedi!

**Closed by sonialiap** 2024-07-25 15:09 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
