### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Inconsistency issue - No scroll bar for members page on announce room 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23609] opened 2023-07-26 02:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace and invite more than 20 members
2. Go to announce room
2. Click on header > members
## Expected Result: 
There should be a scroll bar since the page is scrollable
## Actual Result: 
No scroll bar is shown. But there is a scroll bar present in the members page of workspace settings if the page is scrollable.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/160d56d9-799b-435e-8768-eef67b9d2f29

https://github.com/Expensify/App/assets/43996225/b51867a1-daf0-4305-ba71-8fa6d98d6912

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690271175444019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fa1be2257dab6e98</li>
        <li>Upwork Job ID: 1684630841116672000</li>
        2023-07-27<li>Automatic offers: </li>
<ul>
<li>nathan-mulugeta | Reporter | 25862754</li>
</ul></li>
    </ul>
</details>

**Comment by neonbhai** [comment] 2023-07-26 03:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency issue: No scroll bar for members page on announce room


### What is the root cause of that problem?
These two lists are rendered by different components. The members' page has the scroll bar turned off explicitly here:
https://github.com/Expensify/App/blob/e32ff5e90fc5b70a802610d2401270f8c4ee03a1/src/components/OptionsList/BaseOptionsList.js#L227


### What changes do you think we should make in order to solve the problem?
We should turn off the scrollbar on the `WorkspaceMembersPage` by passing `scrollbarWidth: 'none',` to the `optionRow` rendering the members' names:
https://github.com/Expensify/App/blob/e32ff5e90fc5b70a802610d2401270f8c4ee03a1/src/pages/workspace/WorkspaceMembersPage.js#L325-L328

### What alternative solutions did you explore? (Optional)
We can turn on the scrollbar in the members' page by removing the prop `showsVerticalScrollIndicator`, but that seems to go against the design of the App, as we never show scrollbars in lists like these.

**Comment by alphaboss1104** [comment] 2023-07-26 14:26
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Inconsistency issue - No scroll bar for members page on announce room
### What is the root cause of that problem?

The root cause of that problem is that the `showsVerticalScrollIndicator` prop in React Native’s ScrollView component (which `SectionList` uses internally) is used to control whether to show the vertical scroll bar.

https://github.com/Expensify/App/blob/3d22f591054e5ace31afa58d965e382768e309d4/src/components/OptionsList/BaseOptionsList.js#L227

When we set `showsVerticalScrollIndicator={false}`, it tells the `SectionList` to hide the vertical scroll bar.
By changing it to `showsVerticalScrollIndicator={true}`, it is telling the `SectionList` to display the vertical scroll bar.
So, the scroll bar visibility is controlled by this property.

### What changes do you think we should make in order to solve the problem?

We can change the code from `showsVerticalScrollIndicator={false}` to `showsVerticalScrollIndicator={true}`. 
However, this approach is not recommended as it goes against the principles of code reuse and modularization.
`BaseOptionsList.js` is the base component file so we should keep the project logic and we should avoid the side-effect.

This can be achieved by passing a new prop from `ReportParticipantsPage` to `OptionsList` and then to `BaseOptionsList` to control the `showsVerticalScrollIndicator` property.

Here’s how we can do it:

1. First, update the `ReportParticipantsPage.js` file to pass a new prop `showScrollIndicator` to `OptionsList`:
    ```js
    <OptionsList
        sections={[
            {
                title: '',
                data: participants,
                shouldShow: true,
                indexOffset: 0,
            },
        ]}
        onSelectRow={(option) => {
            Navigation.navigate(ROUTES.getProfileRoute(option.accountID));
        }}
        hideSectionHeaders
        showTitleTooltip
        disableFocusOptions
        boldStyle
        optionHoveredStyle={styles.hoveredComponentBG}
        contentContainerStyles={[safeAreaPaddingBottomStyle]}
        showScrollIndicator={true} // Add this line
    />
    ```

2. Then, update the `OptionsList.js` and `BaseOptionsList.js` files to pass the new prop down to the `SectionList` component:

    - In `OptionsList.js`:
      ```js
      <BaseOptionsList
          // eslint-disable-next-line react/jsx-props-no-spreading
          {..._.omit(props, 'forwardedRef')}
          ref={props.forwardedRef}
          onScroll={onScroll}
          showScrollIndicator={props.showScrollIndicator} // Add this line
      />
      ```
    - In `BaseOptionsList.js`:
      ```js
      <SectionList
          ref={this.props.innerRef}
          indicatorStyle="white"
          keyboardShouldPersistTaps="always"
          keyboardDismissMode={this.props.keyboardDismissMode}
          onScrollBeginDrag={this.props.onScrollBeginDrag}
          onScroll={this.props.onScroll}
          contentContainerStyle={this.props.contentContainerStyles}
          showsVerticalScrollIndicator={this.props.showScrollIndicator} // Update this line
          sections={this.props.sections}
          keyExtractor={this.extractKey}
          stickySectionHeadersEnabled={false}
          renderItem={this.renderItem}
          getItemLayout={this.getItemLayout}
          renderSectionHeader={this.renderSectionHeader}
          extraData={this.props.focusedIndex}
          initialNumToRender={12}
          maxToRenderPerBatch={5}
          windowSize={5}
          viewabilityConfig={{viewAreaCoveragePercentThreshold: 95}}
          onViewableItemsChanged={this.onViewableItemsChanged}
      />
      ```
    We don’t forget to add the new prop to the propTypes and defaultProps of each component:
    ```js
    propTypes = {
        showScrollIndicator: PropTypes.bool,
        // other props...
    };

    defaultProps = {
        showScrollIndicator: false,
        // other props...
    };
    ```
### What alternative solutions did you explore? (Optional)
None.

**Comment by johncschuster** [comment] 2023-07-30 17:22
@allroundexperts good callout! There was a discussion ([here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667241349993479)) around the inclusion of scroll bars. It seems like we came to the consensus that a scroll bar _should_ be included.

**Comment by marcochavezf** [comment] 2023-07-31 18:13
Thanks for the review @allroundexperts, assigning @alphaboss1104 🚀

**Comment by alphaboss1104** [comment] 2023-08-01 17:44
I sent proposal and I will send the PR till tomorrow.

**Comment by alphaboss1104** [comment] 2023-08-02 23:41
@johncschuster , @marcochavezf , @allroundexperts.  PR(https://github.com/Expensify/App/pull/24082) is ready for review.

**Comment by alphaboss1104** [comment] 2023-08-03 12:52
@allroundexperts  I add the scroll bar to the `invite new member`'s page and update my PR (https://github.com/Expensify/App/pull/24082).

**Comment by alphaboss1104** [comment] 2023-08-03 15:35
@allroundexperts.  I am so sorry about make you confusing. I create a new PR(https://github.com/Expensify/App/pull/24116) because I have some mistake when I create the branch. I hope your understanding and review my new PR(https://github.com/Expensify/App/pull/24116)

**Comment by alphaboss1104** [comment] 2023-08-03 17:23
@marcochavezf Could you review my PR (https://github.com/Expensify/App/pull/24116)?

**Comment by johncschuster** [comment] 2023-08-03 21:31
@alphaboss1104, @allroundexperts is the C+ Reviewer. Let's have him review it.

**Comment by alphaboss1104** [comment] 2023-08-03 21:48
@johncschuster , @allroundexperts is already reviewed my PR and approved it.

**Comment by alphaboss1104** [comment] 2023-08-10 06:03
Can I get bonus if the C+ approved my PR (https://github.com/Expensify/App/pull/24116) within 72 hours of assignment?

**Comment by alphaboss1104** [comment] 2023-08-17 14:18
@johncschuster  The payment date is 2023-08-16. when can I get the payment?

**Comment by alphaboss1104** [comment] 2023-08-21 19:49
This is my first contribution to Expensify so I sent a proposal to the [Upwork Job ](https://www.upwork.com/jobs/~01fa1be2257dab6e98) 3 weeks ago for getting offer.
And my upwork profile is https://www.upwork.com/freelancers/~019d30fdf312447ad4.

**Comment by Nathan-Mulugeta** [comment] 2023-08-21 19:54
Hey @alphaboss1104 , it is pretty usual for the payment date to be pushed for a few days. Internal teams will get to payment processing as soon as they get the time. And if you really want the payment to be processed soon you can email to contributors@expensify.com with this git hub link asking for payment to be processed and they will get back to you ASAP.

**Comment by johncschuster** [comment] 2023-08-21 20:00
Hi @alphaboss1104, I'm sorry for missing your pings. Can you please apply to the [job](https://www.upwork.com/jobs/~01fa1be2257dab6e98)? Once you've applied, I will send the offer and we can get the payment taken care of.

**Comment by alphaboss1104** [comment] 2023-08-21 20:03
Hi @johnschuster, Thanks for your response. I have already applied to the [job](https://www.upwork.com/jobs/~01fa1be2257dab6e98).
My Upwork profile is like [this](https://www.upwork.com/freelancers/~019d30fdf312447ad4).

**Comment by johncschuster** [comment] 2023-08-23 13:47
I have issued payment for @Nathan-Mulugeta and @alphaboss1104. @JmillsExpensify, @allroundexperts will require payment through NewDot 👍

**Comment by JmillsExpensify** [comment] 2023-08-24 05:19
Reviewed the details for @allroundexperts. $1,000 approved for payment in NewDot based on the BZ summary above.

**Comment by MitchExpensify** [comment] 2023-08-29 04:21
Coming from [Inconsistensy Bug - vertical scroll Bar](https://github.com/Expensify/App/issues/26098#top), will this issue add a vertical scroll bar is not appearing in the "workspace" and "preference" page?

**Comment by MitchExpensify** [comment] 2023-09-01 20:22
> Coming from https://github.com/Expensify/App/issues/26098#top, will this issue add a vertical scroll bar is not appearing in the "workspace" and "preference" page?

Curious for your take on this Q @marcochavezf  🙇

**Comment by MitchExpensify** [comment] 2023-09-05 12:29
Should this issue be open @johncschuster ?

**Comment by johncschuster** [comment] 2023-09-05 20:35
Good shout, @MitchExpensify! Now that payment has been issued, we're good to close this one out.

**Closed by johncschuster** 2023-09-05 20:35 UTC
Labels: External, Weekly, Awaiting Payment, Bug
