### ISSUE TITLE
[HOLD for REPORTING payment 2023-07-05] [$1000] reaction does not work for first message of thread in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21598] opened 2023-06-26 18:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. hover on any message and hover on any message and click on reply in thread option
3. go to offline
4. try to react on first message
## Expected Result: 
reaction should be able to be applied in offline mode
## Actual Result: 
reaction does not work in offline mode, in online mode it's working fine

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f171b8dd-14e2-4e55-bc13-9eaaac50402a

https://github.com/Expensify/App/assets/43996225/65c17f4a-ee6b-40f1-881d-d9c36025cf97

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687330842702379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0104c4402630c7d68c</li>
        <li>Upwork Job ID: 1673477181578600448</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-06-26 18:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Reaction does not work for first message of thread in offline mode.

### What is the root cause of that problem?

The root cause of this issue is that, when adding/toggling emoji for the first message of thread in offline mode, we update optimistic data to the `reportID` of thread, see method `getOptimisticDataForReportActionUpdate`

https://github.com/Expensify/App/blob/64b720c5b74c3001bf3f9eceac1f54511611c6b7/src/libs/actions/Report.js#L1485-L1499

, which is wrong because when the first message of thread is a report action from parent report. 

Note that method `getOptimisticDataForReportActionUpdate` is used when adding/removing emoji, see

https://github.com/Expensify/App/blob/64b720c5b74c3001bf3f9eceac1f54511611c6b7/src/libs/actions/Report.js#L1562

and

https://github.com/Expensify/App/blob/64b720c5b74c3001bf3f9eceac1f54511611c6b7/src/libs/actions/Report.js#L1613

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should update optimistic data to `parentReportID` when user is updating the first message of a thread. 

To achieve it, we can improve method  `getOptimisticDataForReportActionUpdate`

https://github.com/Expensify/App/blob/64b720c5b74c3001bf3f9eceac1f54511611c6b7/src/libs/actions/Report.js#L1485-L1499

to

```js
function getOptimisticDataForReportActionUpdate(originalReportAction, message, reportID) {
    const reportActionID = originalReportAction.reportActionID;
    const report = lodashGet(allReports, [reportID], {});

    return [
        {
            onyxMethod: Onyx.METHOD.MERGE,

            // If the reportActionID and parentReportActionID are the same then the user is updating the first message of a
            // thread and we should pass the parentReportID instead of the reportID of the thread
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${report.parentReportActionID === reportActionID ? report.parentReportID : reportID}`,
            value: {
                [reportActionID]: {
                    message: [message],
                },
            },
        },
    ];
}
```

Below is the demo video of the fix

<details>
  <summary>Click to see demo video</summary>

  https://github.com/Expensify/App/assets/117511920/f1cad70d-976f-4139-99b6-2fe6993d7c0f
</details>

### What alternative solutions did you explore? (Optional)

N/A

**Comment by jliexpensify** [comment] 2023-06-26 23:44
I can repro this! I think we should allow reacjis to be used whilst offline and they should automatically apply once the user goes back online.

**Comment by mananjadhav** [comment] 2023-06-27 03:58
Thanks @jliexpensify. @eh2077's proposal [here](https://github.com/Expensify/App/issues/21598#issuecomment-1608003701)  looks good to me. I wonder if we could use `isThreadFirstChat` util. But anyway we can workout the kinks in the PR.

🎀 👀 🎀  C+ Reviewed.

**Comment by mananjadhav** [comment] 2023-06-27 04:16
Thanks @aimane-chnaif for reporting. @jliexpensify Then we should put this on Hold and @kavimuru can we retest this?

**Comment by jliexpensify** [comment] 2023-06-27 07:46
@kavimuru could you re-test this one and verify for us? I just tried on Staging (v1.3.32-5) and can still reproduce the issue.

**Comment by jliexpensify** [comment] 2023-06-27 09:19
@aimane-chnaif - here you go, lmk if I'm testing incorrectly:

https://github.com/Expensify/App/assets/30815269/a9e262bd-9954-4091-8547-1039d58fe577

**Comment by kavimuru** [comment] 2023-06-27 17:07
@jliexpensify I am not able to reproduce now.

https://github.com/Expensify/App/assets/43996225/670a4cfb-dd76-44ab-bffd-f5b14617f839

**Comment by jliexpensify** [comment] 2023-06-28 00:08
Interesting, ok - closing this one. @gadhiyamanan I know you reported this, but a fix was already in place so I don't think you qualify for any bonus here.

**Comment by jliexpensify** [comment] 2023-07-03 05:09
Huh, just checking - there's no payment needed right (based off this [comment](https://github.com/Expensify/App/issues/21598#issuecomment-1608765953))? cc @aimane-chnaif @mananjadhav

**Comment by jliexpensify** [comment] 2023-07-04 04:26
@sonialiap - Hello! I'm OOO for a few days so assigning you in case we need to pay anyone.

I have asked about it here (https://github.com/Expensify/App/issues/21598#issuecomment-1617340616) and I don't think we need to do anything else, so please close this GH once it's confirmed. Thanks!

**Comment by sonialiap** [comment] 2023-07-06 20:58
I'm OOO Fri-Mon so looks like you'll be back before I will, @jliexpensify 😆 adding you to the assignees in case we get a response for your Q before I get back

**Comment by jliexpensify** [comment] 2023-07-10 04:21
Hi @mananjadhav and @aimane-chnaif - [just bumping my question here](https://github.com/Expensify/App/issues/21598#issuecomment-1617340616)!

**Comment by mananjadhav** [comment] 2023-07-10 16:58
That's right no payment for the issue, but I am not sure about the reporting bonus @jliexpensify

**Comment by jliexpensify** [comment] 2023-07-11 01:10
Yep, cool - so you will get a reporting bonus here!

**Comment by jliexpensify** [comment] 2023-07-11 01:12
@mananjadhav invited you to https://www.upwork.com/jobs/~01c1efbf3fb188d93d

**Comment by jliexpensify** [comment] 2023-07-11 01:14
@gadhiyamanan invited you to https://www.upwork.com/jobs/~01c1efbf3fb188d93d

**Comment by gadhiyamanan** [comment] 2023-07-11 02:17
@jliexpensify accepted, thanks!

**Comment by jliexpensify** [comment] 2023-07-11 02:22
Paid and job removed!

**Closed** 2023-07-11 02:22 UTC
Labels: External, Daily, Help Wanted, Awaiting Payment, Bug
