### ISSUE TITLE
[$500] 2 report previews show up in the workspace chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35033] opened 2024-01-24 06:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @luacmartins 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706025763769459

## Action Performed:
1. Create an expense report when there is already an existing report
2. open the expense report in workspace chat
## Expected Result:
Only one report preview shows up
## Actual Result:
2 report preview shows up (reportIDs 233456484066723 and 8816885028416207)
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/Expensify/App/assets/43996225/16783b07-4d8d-4565-986f-ff6d39bc54c8" width="40%" height="40%">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e74917e533c59f01</li>
        <li>Upwork Job ID: 1753236551708610560</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by MahmudjonToraqulov** [comment] 2024-02-02 09:44
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
2 report previews show up in the workspace chat

## What is the root cause of that problem?
We're getting last 3 images here.


## What changes do you think we should make in order to solve the problem?


## What alternative solutions did you explore? (Optional)

## Result

**Comment by luacmartins** [comment] 2024-02-02 15:32
@MahmudjonToraqulov thanks for the proposal, but I think it's not addressing the issue. The issue in the OP is that we have two report previews (one for $66.77 and another for $0.37) when both of them should have been combined since there's an existing report that hasn't been submitted yet.

**Comment by MahmudjonToraqulov** [comment] 2024-02-03 10:23
Hey @luacmartins! I think I misunderstood it. Sorry, Let me re-create another proposal that address the issue. Thanks.

**Comment by isabelastisser** [comment] 2024-02-05 13:21
Any updates @MahmudjonToraqulov? Thanks!

**Comment by rojiphil** [comment] 2024-02-07 15:27
>	1	Create an expense report when there is already an existing report

I am not sure about the above-mentioned OP step
How do we create an expense report when there is already an existing report?
I think clear steps to reproduce will help to take this further

**Comment by isabelastisser** [comment] 2024-02-07 17:29
@luacmartins, can you please follow up on the comment above? Would you mind sharing a recording for more context? Thanks!

**Comment by luacmartins** [comment] 2024-02-08 13:55
@rojiphil that's a good question and I'm not sure what the steps to reproduce are. Maybe it was some network connection thing that led to 2 reports, but unfortunately we don't have clear steps yet.

**Comment by mvtglobally** [comment] 2024-02-13 04:51
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment] 2024-02-14 16:27
Still waiting for proposals.

**Comment by isabelastisser** [comment] 2024-02-20 02:22
No proposals yet.

**Comment by MahmudjonToraqulov** [comment] 2024-02-20 10:29
I think this is not reproducible anymore. 
Have u checked?
Cc: @isabelastisser @aimane-chnaif

**Comment by luacmartins** [comment] 2024-02-20 18:56
I haven't been able to reproduce this. I think we can just close this.

**Closed** 2024-02-20 18:56 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
