### ISSUE TITLE
Comment editing doesn't work when you remove all the text except the backticks - reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8720] opened 2022-04-21 04:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Enter some text inside the backticks to quote it
3. Send the comment
4. Click on the edit comment icon
5. Remove the text inside the backticks. Only keep the backticks.
6. Click on Save changes
7. Notice that the text is still visible on LHN
8. Now switch to any other chat and come back
9. Notice that the comment is reverted back to what it was before editing

## Expected Result:
The comment should be edited when you remove all the text except backticks

## Actual Result:
The comment doesn't edit when you remove  all the text except backticks

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.56-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/164375359-ef6964f7-66ea-47b4-873c-5789abb8f07d.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649176586163199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2022-04-21 09:36
Nicely laid out steps, I can reproduce this consistently on the latest `1.1.56-0` Mac app. Handing over to engineering triage. 👍

**Comment by arosiclair** [comment] 2022-04-21 21:20
Looked into this. This is being caused by rejection of the edited comment by our API. Specifically a comment of just markup tags is considered empty and a 402 response is sent. 

I think it would be appropriate to also consider this an empty comment in the app and prompt for deleting the comment like we do with "truely" empty comments.

**Comment by trjExpensify** [comment] 2022-04-22 17:03
@arosiclair is taking this on, so I'm unassigning myself as a CM isn't required.

**Comment by tgolen** [comment] 2022-04-27 21:27
Hm, yeah I think the UI needs to do a better job of validating the data before it's sent to the server. It looks like this is reproducible with the other formatting options too. 

I think there are two avenues:
1. Let the API accept these as valid comments: `` __ ** 
2. Have the UI prevent the user from sending those comments

For 1) I actually can't think of a good reason why we should prevent a user from making comments like that. It seems legit and I don't want to get in the business of assuming what people intend in their comments all the time.

**Comment by arosiclair** [comment] 2022-04-28 15:13
Did some further testing and it does appear that most empty markdown syntax is not treated as markup:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/6833644/165780830-53179bb9-5c62-40da-8ef3-5e3f8f2ab286.png">

However, empty code (``), codeblock (``````), and link with no text _do_ get converted to markup even though there's no text. `ExpensiMark` sets the regex to match these. Maybe these should just be updated to require text between marks? @tgolen

**Comment by tgolen** [comment] 2022-04-28 15:18
> Maybe these should just be updated to require text between marks?

To make sure I understand your proposal fully, if we did this, what would the outcome be to the user?

**Comment by arosiclair** [comment] 2022-04-28 17:26
It's hard to write when GH keeps changing my markup haha.

But the end goal is to allow 1) that you mentioned before.  Sending backticks with no text between does NOT get converted into an empty codeblock and is just sent as literal backticks. Matches GH's behavior below

``
`code`

**Comment by tgolen** [comment] 2022-04-28 19:53
haha, ok. cool! Let's give that a shot then!

**Comment by adeel0202** [comment] 2022-05-12 06:39
Why is this closed? 👀

**Comment by arosiclair** [comment] 2022-05-12 15:48
My fixes for this we're merged, but not yet deployed.

**Comment by adeel0202** [comment] 2022-05-12 16:35
Shouldn't this be opened until the fixes are deployed to production? I'm asking because I'm eligible for the reporting bonus and if we are to close this one now then I think I should be compensated as well 😄
cc: @trjExpensify

**Comment by trjExpensify** [comment] 2022-05-13 00:07
Ah, apologies @adeel0202. I overlooked who reported this issue! Once it has been deployed to production, you will be compensated for reporting the issue. I've sent you a contract on Upwork 👍

**Comment by adeel0202** [comment] 2022-05-13 06:07
Thanks. I have accepted the contract :)

**Closed** 2022-05-23 09:30 UTC
Labels: Reviewing, Engineering, Weekly, Improvement
