### ISSUE TITLE
[HOLD for payment 2024-02-05] [$500]  Workspace avatar not reverted to default when deleting workspace offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32195] opened 2023-11-29 16:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Disable internet connection
3. Create a workspace
4. Upload an avatar for workspace
5. Navigate to #admins room
6. Tap the header > workspace header
7. Delete the workspace
8. Navigate to #admins room

## Expected Result:
Admin room avatar is reverted to the default one

## Actual Result:
Admin room avatar is not reverted to default, it is still a custom one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6cec038d-392f-4d9d-854a-15e97ed6c4e2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194502a9c1a9e4e7e</li>
        <li>Upwork Job ID: 1729899324299497472</li>
        <li>Last Price Increase: 2023-11-29</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 27987317</li>
<li>FitseTLT | Contributor | 27987320</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-11-29 19:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace avatar not reverted to default when deleting workspace offline

### What is the root cause of that problem?
When we get workspace avatar, we didn't consider `pendingAction` here.
https://github.com/Expensify/App/blob/61ed9009dfcb1882ac540550191777e143575bd8/src/libs/ReportUtils.ts#L1213

### What changes do you think we should make in order to solve the problem?
We need to consider `pendingAction` to get workspace avatar.
```
const policyExpenseChatAvatarSource = allPolicies?.[`${ONYXKEYS.COLLECTION.POLICY}${report?.policyID}`]?.avatar &&
    allPolicies?.[`${ONYXKEYS.COLLECTION.POLICY}${report?.policyID}`]?.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE
        ? allPolicies?.[`${ONYXKEYS.COLLECTION.POLICY}${report?.policyID}`]?.avatar
        : getDefaultWorkspaceAvatar(workspaceName);
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2023-12-03 13:07
I am not replacing I am using onyx merge on policy to reset only `avatar`
of the policy.

**Comment by FitseTLT** [comment] 2023-12-03 16:07
> @FitseTLT why do we need to remove other values from
> 
> https://github.com/Expensify/App/blob/70813dbf3e2f73a73e52f880312bc198b39f4dec/src/libs/actions/Policy.js#L209-L214
> 
> 
> and replace it with only avatar value? are you referring to adding the avatar or replacing the previous value with it.

@getusha I am using `Onyx.METHOD.MERGE` not `Onyx.METHOD.SET` so I am replacing only the value of the avatar (resetting it to '') of the policy 👍

**Comment by getusha** [comment] 2023-12-06 01:32
Thanks for the proposal, @FitseTLT. I agree that we should reset the optimistic data. The [proposal](https://github.com/Expensify/App/issues/32195#issuecomment-1832277451) from @FitseTLT looks good to me and works well.

🎀 👀 🎀 C+ reviewed!

**Comment by FitseTLT** [comment] 2023-12-08 13:03
Will make PR ready tomorrow.

**Comment by muttmuure** [comment] 2023-12-11 20:32
Not overdue

**Comment by getusha** [comment] 2023-12-13 11:05
@FitseTLT any updates? any issues while preparing the PR?

**Comment by FitseTLT** [comment] 2023-12-13 16:19
Sorry for being late 🙏 PR ready

**Comment by getusha** [comment] 2024-01-06 09:46
@madmax330 could you please check this? https://github.com/Expensify/App/pull/32986#issuecomment-1869568728

**Comment by getusha** [comment] 2024-02-06 20:32
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@getusha] The PR that introduced the bug has been identified. Link to the PR: **it is an edge case left unhandled.**
 [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/a**
 [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/a**
 [@getusha] Determine if we should create a regression test for this bug. **a minor issue, i don't think it is worth including it in test rail.**
 [@getusha] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by muttmuure** [comment] 2024-02-07 14:19
Thanks @getusha - handling

**Comment by muttmuure** [comment] 2024-02-07 14:20
$500 - @getusha 
$500 - @FitseTLT

**Comment by FitseTLT** [comment] 2024-02-08 15:00
The previous Upwork offer is still open. @muttmuure Do you prefer me to accept the offer you sent me today?

**Comment by muttmuure** [comment] 2024-02-09 13:48
Oh! For some reason I thought it was closed

**Comment by muttmuure** [comment] 2024-02-09 13:49
Yep, seeing "this post is closed and is no longer accepting proposals."

**Comment by muttmuure** [comment] 2024-02-09 13:49
Sorry it means I need to send out a new offer

**Comment by muttmuure** [comment] 2024-02-09 13:49
Can you accept that one and I'll pay it?

**Comment by FitseTLT** [comment] 2024-02-09 13:54
Accepted

**Comment by muttmuure** [comment] 2024-02-09 14:11
I've been looking around and I can see that I could have paid you through the "All Contracts" page - I'll know for next time!

**Comment by muttmuure** [comment] 2024-02-09 14:15
@getusha I've invited you to a payment issue

**Comment by getusha** [comment] 2024-02-09 14:24
@muttmuure accepted.

**Comment by muttmuure** [comment] 2024-02-12 14:18
OK offer sent

**Comment by getusha** [comment] 2024-02-12 14:44
@muttmuure accented the offer.

**Comment by muttmuure** [comment] 2024-02-12 14:45
Paid

**Closed by muttmuure** 2024-02-12 14:45 UTC
Labels: External, Daily, Awaiting Payment, Bug
