### ISSUE TITLE
[HOLD for payment 2023-12-07] [$500] Go back from `Flag as offensive` doesn't display correct report page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30101] opened 2023-10-20 19:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  @suneox
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697654423349679

## Action Performed:
1. Go to any public room report [exam](https://staging.new.expensify.com/r/8292963527436014)
2. Hold touch on any chat message select "Flag as offensive"
3. Reload page [exam](https://staging.new.expensify.com/flag/8292963527436014/533025741267772385)
4. Select back button
## Expected Result: 
App should display report from `Flag as offensive`
## Actual Result: 
App doesn't display report from `Flag as offensive`
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/8a47ab34-5c7c-4447-8abc-b098b5150329

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/eaa58a6e-b5eb-4774-b9ad-f7db12689630

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/ea864e94-58a3-49e8-b380-93b9214bf574

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bff2f94a7065c212</li>
        <li>Upwork Job ID: 1715445279961526272</li>
        <li>Last Price Increase: 2023-10-20</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Contributor | 27349484</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2023-10-20 19:10
## Proposal from @suneox
### Please re-state the problem that we are trying to solve in this issue.
Go back from `Flag as offensive` doesn’t display correct report page
### What is the root cause of that problem?
In the `HeaderWithBackButton` of the `FlagCommentPage` we dont specify a route for the back action
### What changes do you think we should make in order to solve the problem?
We should handle `onBackButtonPress` go to current report from [HeaderWithBackButton](https://github.com/Expensify/App/blob/4a1e2b3e8a1f73992173264276fef2ded1fd5918/src/pages/FlagCommentPage.js#L163)
```javascript
    <HeaderWithBackButton
        title={props.translate(‘reportActionContextMenu.flagAsOffensive’)}
        onBackButtonPress={() => Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(props.report.reportID))}
    />
```
### What alternative solutions did you explore? (Optional)
```javascript
```

**Comment by mananjadhav** [comment] 2023-10-22 16:25
@suneox's proposal seems good. quick straight forward fix.

🎀 👀 🎀 C+ reviewed.

**Comment by iwiznia** [comment] 2023-10-23 17:42
@mananjadhav I am confused, I see no proposal from @suneox... did you mean to say @m-natarajan and pick [this proposal](https://github.com/Expensify/App/issues/30101#issuecomment-1773268271)?

**Comment by mananjadhav** [comment] 2023-10-23 17:45
@iwiznia Sorry for the confusion, I should've linked the comment.

@m-natarajan is from Applause and @suneox is the reporter who posted the solution on slack.

**Comment by mananjadhav** [comment] 2023-10-24 09:09
@suneox Can you please post a comment with your proposal? So that it can be assigned.

**Comment by mananjadhav** [comment] 2023-10-26 08:16
Discussing the [last comment](https://github.com/Expensify/App/pull/30289#issuecomment-1780244206) change here.  @suneox has added the following change.

```
Browser.isMobile() ? () => Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(props.report.reportID)) : undefined
```

I don't think it's a good idea to push a platform specific check on back button press. I checked further in the code and I don't think we're doing this. @iwiznia what do you think about this?

I did another quick test (which I should've done) for the profile view, it looks like we have the same behavior. So I want to go ask @Christinadobrzyn and @iwiznia, do we want to fix this across the app for other routes as well? I personally think we shouldn't as it is about fresh load of the page.

**Comment by iwiznia** [comment] 2023-10-26 11:30
Yeah, sounds off. @suneox can you explain the problem that prompted you to add that code?

**Comment by mananjadhav** [comment] 2023-11-01 19:49
@suneox Apologies for the delay here. I still am not convinced if we should be fixing this just for this particular use case. Neither do I think we should be exploring a complex navigation solution just for this one.

I'll let @iwiznia comment his thoughts.

**Comment by iwiznia** [comment] 2023-11-02 13:43
So what is your recommendation exactly @mananjadhav?

**Comment by mananjadhav** [comment] 2023-11-07 18:31
@iwiznia I would recommend we do nothing on this one.

**Comment by mananjadhav** [comment] 2023-11-10 21:52
@suneox Thanks for the bump. @iwiznia I went through the conversations and the linked [PR](https://github.com/Expensify/App/pull/29268/files). It looks like we're okay to solve with this approach. Hence, I think we can proceed with the fix here as well? wdyt?

**Comment by mananjadhav** [comment] 2023-11-13 19:51
@iwiznia Quick bump on this one.

**Comment by iwiznia** [comment] 2023-11-13 21:34
> It looks like we're okay to solve with this approach. Hence, I think we can proceed with the fix here as well? 

When you say this approach what do you mean exactly? Are we keeping the isMobile check that was suggested above?

**Comment by mananjadhav** [comment] 2023-11-15 17:14
@iwiznia What @suneox said, using the `topMostReportID` ([revised proposal](https://github.com/Expensify/App/issues/30101#issuecomment-1776964111)) as done in the other PR.

**Comment by iwiznia** [comment] 2023-11-15 20:27
Ah ok, sounds good to me 👍

**Comment by mananjadhav** [comment] 2023-11-16 14:07
@suneox Can you confirm if the PR is created with the revised proposal and synced with the latest main?

**Comment by Christinadobrzyn** [comment] 2023-11-18 01:27
I'm going ooo until Monday Nov 27th so going to assign another BZ teammate to monitor this until I'm back. Thanks!

Status: reviewing PR

**Comment by Christinadobrzyn** [comment] 2023-12-06 01:36
prepping for payment

Payouts due:

Issue Reporter: $50 @suneox (in Upwork)
Contributor: $500 @suneox (in Upwork)
Contributor+: $500 @mananjadhav (in NewExpensify)

Eligible for 50% #urgency bonus? N - PR created Oct 24th and merged Nov 28th

Upwork job is [here](https://www.upwork.com/ab/applicants/1715445279961526272/job-details).

@mananjadhav should there be a regression test?

**Comment by mananjadhav** [comment] 2023-12-06 02:48
Yeah I think it's best we add a regression test. We've updated the back button logic and also added some calls to Navigation. QA steps from the PR body looks fine to me.

There is no offending PR, because I think we didn't consider this case.

**Comment by mananjadhav** [comment] 2023-12-07 05:46
I've raised my request on NewDot.

**Comment by Christinadobrzyn** [comment] 2023-12-08 01:36
just checking @suneox @mananjadhav is there a regression from this?

**Comment by mananjadhav** [comment] 2023-12-08 06:44
No regression here @Christinadobrzyn

**Comment by Christinadobrzyn** [comment] 2023-12-08 17:14
Awesome! let me know if this is ready to be closed!

**Comment by mananjadhav** [comment] 2023-12-08 17:18
@Christinadobrzyn once it is paid out and the regression test is added we can close it.

**Comment by Christinadobrzyn** [comment] 2023-12-08 17:42
Oh gosh, I'm sorry I thought I paid this yesterday! Sorry to keep you waiting, paying now!

**Closed** 2023-12-08 17:46 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-12-11 01:36
$500 payment approved for @mananjadhav based on [this comment](https://github.com/Expensify/App/issues/30101#issuecomment-1841934624).
