### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] IOS - Video - Video sound is not playing when device sound profile is silent mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41204] opened 2024-04-29 12:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!

- Version Number: 1.4.67-0
- Reproducible in staging?: y
- Reproducible in production?: y
- Issue reported by: Applause - Internal Team

### Precondition: Device sound mode is not silent mode.

1. Launch New Expensify app.
2. Go to chat.
3. Upload a video with sound.
4. Play the video.
5. Note that the sound is playing.
6. Change the device sound mode to silent mode.
7. Play the video.

### Expected Result:
The video sound should play as long as the media volume is not zero.

### Actual Result:
The video sound is not playing when device sound profile is silent mode.

### Workaround:
n/a

### Platforms:
Which of our officially supported platforms is this issue occurring on?

- [ ]  Android: Native
- [ ]  Android: mWeb Chrome
- [x] iOS: Native
- [ ]  iOS: mWeb Safari
- [ ]  MacOS: Chrome / Safari
- [ ]  MacOS: Desktop
- [ ] Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5b145ae1-afba-48fa-8d49-5956a0324902

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by kbecciv** [comment] 2024-04-29 12:20
We think that this bug might be related to #vip-vsb

**Comment by abekkala** [comment] 2024-05-02 20:11
@getusha we do have one proposal already for this one!

**Comment by kbecciv** [comment] 2024-05-06 21:26
@abekkala Can you please bring the OP back? Thank you!

**Comment by abekkala** [comment] 2024-05-08 17:53
> @abekkala Can you please bring the OP back? Thank you!

Odd, yes I put it back!

**Comment by getusha** [comment] 2024-05-09 18:47
Will try reproducing this & we have a proposal to review

**Comment by getusha** [comment] 2024-05-12 12:44
Asked another c+ with a physical iOS device https://expensify.slack.com/archives/C02NK2DQWUX/p1715517674210059
@c3024 will take it.

**Comment by c3024** [comment] 2024-05-13 01:24
@ShridharGoel 's [proposal here](https://github.com/Expensify/App/issues/41204#issuecomment-2082648065) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by mvtglobally** [comment] 2024-05-13 14:18
Issue not reproducible during KI retests. (First week)

**Comment by c3024** [comment] 2024-05-13 16:28
Still reproducible.

**Comment by MonilBhavsar** [comment] 2024-05-15 06:07
Is this a feature and not a bug?

**Comment by c3024** [comment] 2024-05-15 09:35
It is a feature of iOS native. 

But this iOS native behaviour is different from Android native, Android Chrome and iOS Safari. In these three, video sound continues to play even after changing the device to silent mode.

**Comment by MonilBhavsar** [comment] 2024-05-15 09:45
Thanks for clarifying!

**Comment by c3024** [comment] 2024-05-17 15:05
@ShridharGoel any update on this?

**Comment by c3024** [comment] 2024-06-06 14:54
>The PR that introduced the bug has been identified. Link to the PR:

No specific PR can be made responsible for this. This is a specific iOS behaviour.

>The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

NA

>A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

No discussion was started as this is a particular iOS specific behaviour and cannot be identified earlier.

>Determine if we should create a regression test for this bug.

Yes

>If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Switch iOS device to silent mode.
2. Keep the media volume on.
3. Go to any chat and play a video with audio.
4. Verify that the sound is audible.

👍 or 👎

**Comment by c3024** [comment] 2024-06-06 14:55
@abekkala thanks, applied.

**Comment by abekkala** [comment] 2024-06-06 15:50
@c3024 - payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment] 2024-06-07 13:40
@ShridharGoel can you please accept the offer in Upwork so that I can submit payment and close this one? [Offer Link](https://www.upwork.com/nx/wm/offer/102625444) thanks!

**Comment by abekkala** [comment] 2024-06-10 15:11
@ShridharGoel payment sent and contract ended - thank you! 🎉

**Closed by abekkala** 2024-06-10 15:11 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
