### ISSUE TITLE
[$1000] Chat - While editing comment, url entered is shown as text instead of link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24258] opened 2023-08-08 12:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the site
2. Tao on a report
3. Enter 2 url in compose box " google.com she.com"
4. Send the message
5. Long press the sent message and tap on "edit comment"
6. Remove the entire comment and re-enter "google.com she.com"
7. Tap tick mark

## Expected Result:
While editing comment, url entered must be shown as link

## Actual Result:
While editing comment, url entered is shown as text instead of link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e9efa2db-35dc-4dae-8337-d2f7e44a7f26

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126942909cb8125dc</li>
        <li>Upwork Job ID: 1691854855721750528</li>
        <li>Last Price Increase: 2023-08-30</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-08-08 14:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
While editing comment, url entered is shown as text instead of link.

### What is the root cause of that problem?
When add a comment, app converts the comment to the html.

But if edit a comment, app does not convert a comment to the html.
So the url is shown as a text instead of link.

### What changes do you think we should make in order to solve the problem?
We should convert a comment to the html when editing a comment.
```js
    const htmlComment = ReportUtils.getParsedComment(reportComment);

    // Optimistically update the reportAction with the new message
    const reportActionID = originalReportAction.reportActionID;
	...
	
-	html: htmlForNewComment,
+	html: htmlComment,

    ...
-   reportComment: htmlForNewComment,
+   reportComment: htmlComment,

```

### What alternative solutions did you explore? (Optional)
None.

**Comment by Ahmed-Abdella** [comment] 2023-08-16 17:11
I think it is an intended behavior, this issue was reported here #16481 and closed as it is an intended behavior and not a bug

**Comment by Santhosh-Sellavel** [comment] 2023-08-16 17:12
@anmurali This is expected not a bug.

**Comment by Santhosh-Sellavel** [comment] 2023-08-22 16:07
Not overdue

**Comment by Santhosh-Sellavel** [comment] 2023-08-28 19:22
Not overdue

**Comment by Santhosh-Sellavel** [comment] 2023-08-30 18:13
bump @anmurali

**Comment by Santhosh-Sellavel** [comment] 2023-09-05 16:05
We can close this one, as this is the expected behaviour

> I think it is an intended behavior, this issue was reported here #16481 and closed as it is an intended behavior and not a bug

**Closed** 2023-09-13 03:44 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
