### ISSUE TITLE
Web - Scan Receipt images aren't shown in proper order in requests thumbnail

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26914] opened 2023-09-06 21:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Note : ( i have used image files <jpg/png> to demonstrate . however its similar case for the file types) . So make sure you have 5/6 images downloaded.
1. go to fab button -> request money -> scan
2. Now click on choose a file and pick a image file.
3. Choose any user to request ( lets say user A here)
4.  it must now redirect to the page showing thumbnail containing the just selected image.
5. Now repeat step 1-4  for about 5 times ( select DIFFERENT files each time )
6.  With every files picked, notice that the thumbnail shows three images but the ordering is random. i.e recently picked files should be shown in order either from left or right.

## Expected Result:
Recently picked files should be shown in order either from left or right.  but sometimes recent picks aren't even shown on display.

## Actual Result:
The requested receipts thumbnail shows display of receipts in random order. Not even latest selects are shown in some case.

## Workaround:
Unknwn

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9c502f17-8705-4e9a-bc1d-76fdeb0525e8

https://github.com/Expensify/App/assets/93399543/33040894-8359-4628-94b8-4d3de8272807

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693673733273299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b5d6aab382e8f96</li>
        <li>Upwork Job ID: 1701195358199992320</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-06 22:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Scan receipt images in the thumbnail for the request preview aren't shown in proper order.

### What is the root cause of that problem?
When retrieving the last 3 transactions in the `ReportUtils#getReportPreviewDisplayTransactions` method, they are not sorted in any order before being returned.

### What changes do you think we should make in order to solve the problem?
Add sorting logic to the transactions retrieved before returning. They can be sorted by transaction date

### What alternative solutions did you explore? (Optional)
None.

**Comment by flaviadefaria** [comment] 2023-09-11 11:25
I'll add the internal label to have an engineer evaluate.

**Comment by youssef-lr** [comment] 2023-09-12 10:36
I'm unable to reproduce this one locally. Closing!

**Closed by youssef-lr** 2023-09-12 10:36 UTC
Labels: Engineering, Daily, Internal, Bug
