### ISSUE TITLE
[$500] Request money - Message grouping incorrectly on receiver side if they send a message right after get a request money

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26104] opened 2023-08-28 16:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a money request from account A to account B
2. On account B, after App show money request, send any chat message

## Expected Result:
The new chat message of account B should displayed as it's come from account B, not both requester & receiver money request.

## Actual Result:
The new chat message is grouped under money request preview. We just change money request preview recently, and it displaying both requester & receiver. If the new chat message is grouped under money request preview. It make our think this new message is come from both requester & receiver.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/15aa22fa-dd0b-4b9b-8adb-0dfc7718d723

https://github.com/Expensify/App/assets/115492554/18d0196a-f21c-4f12-acc2-b8b2fbc106ec

**Expensify/Expensify Issue URL:**

**Issue reported by:** @hoangzinh

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692406833875899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0146dd2cbf64595716</li>
        <li>Upwork Job ID: 1697287661616144384</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-08-28 23:43
Same root cause as below so applying this solution will fix the issue 

https://github.com/Expensify/App/issues/25509#issuecomment-1684907030

> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> If account A makes a money request after sending a message the avatars show up. But if account B replies after account A sent a message then the IOU preview components will not show the two avatars. There should be two avatars (account A's and account B's) on the left side of the IOU preview component
> 
> ### What is the root cause of that problem?
> The primary reason for this discrepancy is the logic inside the `isConsecutiveActionMadeByPreviousActor` function, which decides how avatars should be displayed in the component. The function determines if actions should be grouped or displayed consecutively. The issue arises because, when User A sends a request for money, the `actorAccountID` is assigned User B's ID. This causes the function to interpret that the consecutive actions are not made by the same actor, thus leading to current scenario.
> 
> https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/pages/home/report/ReportActionsList.js#L263
> 
> https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/libs/ReportActionsUtils.js#L255-L288
> 
> ### What changes do you think we should make in order to solve the problem?
> To rectify this:
> 
> **1. Refine the Logic:** Update the `isConsecutiveActionMadeByPreviousActor` function to accurately determine the sequence of actions, especially for IOU-related actions.
> 
> **2. Utilize Existing Structures:** Using the `allReports` structure and the function `getIOUReportIDFromReportActionPreview`, access the necessary data for the current and previous reports.
> 
> **3. Determine IOU Actions:** Introduce a check within the function to determine if the action is related to an IOU report. This can be achieved by evaluating the type of report.
> 
> **4. Compare Relevant Attributes:** For IOU actions, modify the comparison logic to evaluate the correct attributes for the avatars. For instance, consider attributes like `managerID` and `ownerAccountID` to ensure the right display decision is made.
> 
> ```
> 
> // eslint-disable-next-line no-use-before-define
> const currentReport = allReports[getIOUReportIDFromReportActionPreview(currentAction)];
> // eslint-disable-next-line no-use-before-define
> const previousReport = allReports[getIOUReportIDFromReportActionPreview(previousAction)];
> 
> // eslint-disable-next-line es/no-optional-chaining
> if (isIOUReport(currentReport) && !isIOUReport(previousReport)){
>     return false;
> }
> // Can also do this
> //  if ( !isIOUReport(currentReport) && isIOUReport(previousReport)){
> //     return false;
> // }
> 
> if (isIOUReport(currentReport) && isIOUReport(previousAction)) {
>   return currentReport.ownerAccountID === previousReport.ownerAccountID && currentReport.managerID === previousReport.managerID;
> }
> 
> return currentAction.actorAccountID === previousAction.actorAccountID;
> ```
> 
>  https://github.com/Expensify/App/assets/65986357/52d918ff-d5a8-4491-b18b-42bbaa77e3bb

**Comment by slafortune** [comment] 2023-09-08 17:15
Looks like this would be on hold for https://github.com/Expensify/App/issues/15212

Going on sabbatical so assigning a new BZ member.

**Comment by abdulrahuman5196** [comment] 2023-09-11 19:19
> Looks like this would be on hold for #15212

The other issue is closed as a design decision. I doubt the same might be the case for here as well.

@alexpensify Could you kindly check if this is the expected behaviour or a bug indeed?

**Comment by alexpensify** [comment] 2023-09-11 22:13
Thanks, I'll start a discussion in the Slack room and confirm next steps here.

**Comment by alexpensify** [comment] 2023-09-15 00:36
I'm catching up from being OOO but will start the discussion tomorrow.

**Comment by alexpensify** [comment] 2023-09-18 19:05
I've started a convo here: 

https://expensify.slack.com/archives/C01GTK53T8Q/p1695063873406209

**Comment by alexpensify** [comment] 2023-09-18 19:39
Ok, closing! There is no payment here since Vit flagged this issue before this one here.

**Closed by alexpensify** 2023-09-18 19:39 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
