### ISSUE TITLE
[HOLD for payment 2023-12-06] [$500] Web - Signing show empty content when pressing go back from another tab.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30288] opened 2023-10-24 17:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698145969463179

## Action Performed:
Action Performed:
1. Open 2 tabs
2. Try to sign in with expensifail account at the first tab.
3. At first tab, continue to choose `Use magic code`, after that press go back.
4. Now move to the second tab.
5. Notice that content of second tab is empty.

## Expected Result:
Second tab should show the same content with the first tab.

## Actual Result:
 Content of the second tab is empty.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/8346887f-5b30-419e-897e-18e0a792a959

https://github.com/Expensify/App/assets/93399543/6b3c7b44-59a9-4c03-90c3-750c4dc59ac8

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011276a45d6462ac66</li>
        <li>Upwork Job ID: 1716875205299765248</li>
        <li>Last Price Increase: 2023-11-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by wlegolas** [comment] 2023-10-24 18:11
Hi @kbecciv.

Maybe I'm wrong, but I think this is a limitation in the Web application.

In my analysis, I found a comment in the file below that explains why it can be a limitation.

 https://github.com/Expensify/App/blob/main/src/libs/actions/Device/generateDeviceID/index.website.js

Just to bring more context, in my understanding, the `deviceID` is used to connect the current tab to the application state management. As the `deviceID` is the same in both tabs, the tabs will share the same application state.

**Comment by FitseTLT** [comment] 2023-10-24 19:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Sign in page show empty when we go back to login from validate code page in other tab 
### What is the root cause of that problem?
Although this code
https://github.com/Expensify/App/blob/cc3c51c1d58ce013e444b59bd06c87e4b750e550/src/libs/actions/Session/index.ts#L576-L579
is suppose to reset the credential value in onyx to `{}`, Onyx is not updating `credential` prop and rerendering the signin page on the other tab(the tab the user didn't press go back on) 
therefore `shouldShowLoginForm` is set to true in the other tab because in this line 
https://github.com/Expensify/App/blob/cc3c51c1d58ce013e444b59bd06c87e4b750e550/src/pages/signin/SignInPage.js#L119
`hasLogin` will be true for the other tab  (the tab the user didn't press go back) as the credential value is not updated properly in ONYX it still holds on the previous login email inserted from the original tab.
### What changes do you think we should make in order to solve the problem?

Change this line 
https://github.com/FitseTLT/App/blob/cc3c51c1d58ce013e444b59bd06c87e4b750e550/src/libs/actions/Session/index.ts#L578
to
```
        [ONYXKEYS.CREDENTIALS]: null,

```
to properly clear the credential data to the other tab. Now the credential prop updates properly on the other tab. It must be something related to the internal working of Onyx.
OPTIONALLY
Also separting the `multiSet` call
https://github.com/Expensify/App/blob/cc3c51c1d58ce013e444b59bd06c87e4b750e550/src/libs/actions/Session/index.ts#L576-L579
to separate onyx `set`
```
    Onyx.set(ONYXKEYS.ACCOUNT, null);
    Onyx.set(ONYXKEYS.CREDENTIALS, {});
```
updates the credentials prop properly in the other tab and it fixes the problem. 
**(Ofcourse there is some weird unexpected behaviour in the inner working of onyx but we can use either of the workarounds above and both work; here is a testimonial video below)**
POC:

https://github.com/Expensify/App/assets/38649957/c2f5c361-2fd2-4692-b7c0-9c4151af9f64


### What alternative solutions did you explore? (Optional)

**Comment by yh-0218** [comment] 2023-10-24 19:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Sign in page show empty when we go back to login from validate code page in other tab
### What is the root cause of that problem?
when click "go back" on TabA, `credentials.login = null` on TabA, but `credentials.login != null` on TabB.
I think this is issue of `withOnyx` issue
### What changes do you think we should make in order to solve the problem?
We can set individually to avoid this.
```
    Onyx.set(ONYXKEYS.ACCOUNT, null);
    Onyx.set(ONYXKEYS.CREDENTIALS, {});
```
on this.
https://github.com/Expensify/App/blob/f8fc21d373be18e645f4d93099256721914c16f5/src/libs/actions/Session/index.ts#L576-L579
### What alternative solutions did you explore? (Optional)

**Comment by strepanier03** [comment] 2023-10-24 22:36
Okay, we are able to repro this pretty easily but I do wonder if this is a limitation based on the comment from @wlegolas [here](https://github.com/Expensify/App/issues/30288#issuecomment-1777768907). Although it does seem like the more recent proposals identify this as an Onyx issue so perhaps there is no limitation?

https://github.com/Expensify/App/assets/10925636/07dbc78d-082e-4284-a50a-82fc3d240a64

I'll wait for @situchan to weigh in because they're going to understand this much better than I do. 

Thanks everyone!

**Comment by hungvu193** [comment] 2023-10-25 02:55
Coming from this discussion here: https://expensify.slack.com/archives/C049HHMV9SM/p1698145969463179

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Signing show empty content when pressing go back from another tab. 
### What is the root cause of that problem?
Recent changes in `react-native-onyx` recently broke the `Onyx.multiset` method this make `credenticals` didn't update in the second tabs which caused this issues.
I assume that it will be the regression of one of these 2 PRs:
https://github.com/Expensify/react-native-onyx/pull/384 and https://github.com/Expensify/react-native-onyx/pull/385
### What changes do you think we should make in order to solve the problem?
Since we used `multiset` in many places in our App so in the meantime, when waiting for this is being fixed in `react-native-onyx`, I suggest that we should revert `react-native-onyx` to version `1.0.98`.
(This issue is still reproducible with react-native-onyx 1.0.109).

### What alternative solutions did you explore? (Optional)
N/A

**Comment by situchan** [comment] 2023-10-30 16:24
Anyone please jump in this issue and fix regression?
cc: @tgolen @ospfranco (tagging you since you were authors of https://github.com/Expensify/react-native-onyx/pull/385, https://github.com/Expensify/react-native-onyx/pull/384)

**Comment by tgolen** [comment] 2023-10-30 16:41
Hm, I don't think those changes would cause this. To my knowledge, those changes aren't rolled out yet because `main` is still using Onyx v `1.0.100`.

**Comment by tgolen** [comment] 2023-10-30 16:41
I would suggest using `git bisect` to try and locate the offending commit.

**Comment by situchan** [comment] 2023-10-31 16:03
Awaiting proposal with correct root cause and solution

**Comment by strepanier03** [comment] 2023-11-03 23:06
All good Melvin, waiting on proposals.

**Comment by strepanier03** [comment] 2023-11-06 18:42
Still waiting on proposals.

**Comment by strepanier03** [comment] 2023-11-10 02:46
Holding until we have some proposals.

**Comment by ospfranco** [comment] 2023-11-10 07:35
Onyxes #384 was reverted, and #385 will not cause that issue. I think at some point the semantics of Onyx changed, setting `null` as stated in [this proposal](https://github.com/Expensify/App/issues/30288#issuecomment-1777899842) no longer clears the values, but it is ignored when merging data inside the database (maybe https://github.com/Expensify/react-native-onyx/pull/353). So I think the proposal is valid, in order to really clear the data one needs to set it to a valid empty object.

**Comment by situchan** [comment] 2023-11-19 20:32
Getting engineer to push this forward 🎀 👀 🎀

Ideally, this should be fixed in Onyx so `multiSet` should work properly.
Otherwise, we can do separate `set` calls like @FitseTLT's [proposal](https://github.com/Expensify/App/issues/30288#issuecomment-1777899842).

**Comment by stitesExpensify** [comment] 2023-11-21 18:53
Let's go with @FitseTLT proposal to set the credentials to null

**Comment by FitseTLT** [comment] 2023-11-23 14:21
@situchan PR ready 👍

**Comment by strepanier03** [comment] 2023-12-06 21:44
The job that was originally created for this in Upwork has been closed and Upwork is erroring when creating a new job. 

I'll come back to this in an hour or two and see if Upwork will let me create the job.

**Comment by situchan** [comment] 2023-12-06 22:12
BZ Checklist:
This came from Onyx. Not regression from app PR.
As this is rare case, it's not worthy of adding regression test.
If disagrees, we can use QA Steps in [PR](https://github.com/Expensify/App/pull/31662) as regression test step.

**Comment by strepanier03** [comment] 2023-12-07 17:20
This is all wrapped up and paid out. Thanks again everyone!

**Closed by strepanier03** 2023-12-07 17:20 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
