### ISSUE TITLE
[$250] Android - Attachment - Video preview is cut off with play menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44293] opened 2024-06-24 18:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a407@gmail.com
**Issue reported by:** Applause -Internal Team

## Action Performed:
1. Navigate to any chat
2. Tap +> Attachment
3. Upload a video file

## Expected Result:
Video preview should be fully visible

## Actual Result:
When upload or play video preview is cut off with play menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0cf15e85-b266-4e57-be06-038d0cc305a1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a1f9aa358cfe3a5</li>
        <li>Upwork Job ID: 1808490119251146982</li>
        <li>Last Price Increase: 2024-07-03</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103036136</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by nkdengineer** [comment] 2024-07-03 14:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When upload or play video preview is cut off with play menu

### What is the root cause of that problem?
For touch screen, the `VideoPlayerControls` is always showing https://github.com/Expensify/App/blob/0e4e2d2874e295a02bf4a0e1a68214c65089761b/src/components/VideoPlayer/BaseVideoPlayer.tsx#L370 (for web it shows on hover)

This will cut into the video displaying space, when the video is vertical.

### What changes do you think we should make in order to solve the problem?

We need to add behavior similar to any other video apps like Youtube or native iOS video player. The video player controls will disappear after a few seconds (let's say 3) when there's no user interaction. If the user taps on the screen, the video player control will show again. This is also the behavior in the Expensify app's Attachment carousel arrow https://github.com/Expensify/App/blob/0e4e2d2874e295a02bf4a0e1a68214c65089761b/src/components/Attachments/AttachmentCarousel/index.native.tsx#L27

Steps:
- Implement a `useVideoPlayerControls` hook like the `useCarouselArrows` hook [here](https://github.com/Expensify/App/blob/main/src/components/Attachments/AttachmentCarousel/useCarouselArrows.ts#L6), with the behavior to auto hide video control, cancel auto hide, ... Or we can rename `useCarouselArrows` to `useAttachmentControls` to be more general-purpose and use for both carousel arrows use case and video player control use case
- Wrap the video in a `MultiGestureCanvas` like done [here](https://github.com/Expensify/App/blob/main/src/components/Lightbox/index.tsx#L212) for image attachment, so we can listen to `onTap` in order to trigger the video player controls to show
- In https://github.com/Expensify/App/blob/main/src/components/VideoPlayer/BaseVideoPlayer.tsx#L370
If it's touch screen, only show the video player controls if `shouldShowVideoPlayerControls` prop exposed from `useVideoPlayerControls` is `true`

### What alternative solutions did you explore? (Optional)

**Comment by isogit123** [comment] 2024-07-05 01:30
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When upload or play video preview is cut off with play menu

### What is the root cause of that problem?
The CSS bottom property of the controls is set to a high value for mobile devices, which lifts the controls up too high.
In the code snippet below, the value is defined as `NATIVE: 32` in line 3930:
https://github.com/Expensify/App/blob/0e4e2d2874e295a02bf4a0e1a68214c65089761b/src/CONST.ts#L3929-L3932
which is referenced in the `BaseVideoPlayer` in line 13 as shown below:
https://github.com/Expensify/App/blob/0e4e2d2874e295a02bf4a0e1a68214c65089761b/src/components/VideoPlayer/index.native.tsx#L8-L14

### What changes do you think we should make in order to solve the problem?
Set the CSS bottom property to a lower value by setting `NATIVE` to 8 as an example in line 3930 in the following code snippet:
https://github.com/Expensify/App/blob/0e4e2d2874e295a02bf4a0e1a68214c65089761b/src/CONST.ts#L3929-L3932

Below is a screenshot of the controls after applying the change:
<img src="https://github.com/Expensify/App/assets/34800355/09582639-b2a5-4aa5-8627-8a7ad5074146" width="300" />


### What alternative solutions did you explore? (Optional)

**Comment by shawnborton** [comment] 2024-07-05 15:13
Hmm I can't quite tell but is the problem that the background color of the control bar is not transparent or something? It feels like that background color is fully opaque? 

At the same time... are we sure this is a bug? All of our videos have controls over them. And when you start playing it, they will fade out at some point right?

**Comment by dubielzyk-expensify** [comment] 2024-07-08 01:03
Yeah, I'm not sure this is a bug from what I understand 🤔  Cause if the controls hide (after that PR has merged) then it wouldn't be cutting off the preview

**Comment by nkdengineer** [comment] 2024-07-11 03:41
@Ollyws this [PR](https://github.com/Expensify/App/pull/45053) is ready for review

**Comment by mvtglobally** [comment] 2024-07-11 03:50
Issue not reproducible during KI retests. (First week)

**Comment by nkdengineer** [comment] 2024-09-30 15:09
@muttmuure Gentle bump on https://github.com/Expensify/App/issues/44293#issuecomment-2324417775

**Comment by muttmuure** [comment] 2024-11-14 13:21
PR was drafted, $250 is due: 

$250 for @Ollyws as C+
$250 for @nkdengineer as C

**Comment by muttmuure** [comment] 2024-11-14 13:23
@Ollyws can request payment on ND

**Comment by muttmuure** [comment] 2024-11-14 13:23
@nkdengineer paid

**Closed by muttmuure** 2024-11-14 13:23 UTC
Labels: Reviewing, External, Monthly, Not a priority, Bug

**Comment by garrettmknight** [comment] 2024-11-26 13:47
$250 approved for @Ollyws
