### ISSUE TITLE
[HOLD #31705][$500] Desktop - Compose Box - When the app reloads, "Write something..." text and the cursor moves up

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31744] opened 2023-11-22 20:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Navigate to any conversation
3. Reload the application(CMD+R)
4. Click on "Go back to home page" (if required)

## Expected Result:
When the application reloads, "Write something..." text and the cursor should be centered in the Compose Box

## Actual Result:
When the application reloads, "Write something..." text and the cursor moves up in the Compose Box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4dcf11b7-6b5c-4c47-95bb-4912a1fe9513

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ec0e25eb59f5d17</li>
        <li>Upwork Job ID: 1727422130676625408</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

**Comment by erquhart** [comment] 2023-11-22 20:26
Not seeing this in dev.

**Comment by sakluger** [comment] 2023-11-27 18:30
First of all, why does reloading the page take you to the "Hmm...it's not here" page? That seems like a bigger bug. Does that only happen on Desktop or on other platforms too?

For the compose box spacing issue, @mkhutornyi do you have any ideas why it's only happening on Desktop and not on other platforms?

**Comment by sakluger** [comment] 2023-12-01 01:22
Thanks for sharing those other issues! I looked but couldn't find them.

@aimane-chnaif what do you think about @mkhutornyi's proposed solution?

**Comment by sakluger** [comment] 2023-12-04 19:59
Put this issue on hold for https://github.com/Expensify/App/issues/31705.

**Comment by sakluger** [comment] 2023-12-13 23:07
Still on hold.

**Comment by sakluger** [comment] 2023-12-25 16:49
Still on hold.

**Comment by sakluger** [comment] 2024-01-03 04:07
Still on hold for https://github.com/Expensify/App/issues/31705.

**Comment by sakluger** [comment] 2024-01-31 02:34
Still on hold.

**Comment by sakluger** [comment] 2024-02-09 16:04
https://github.com/Expensify/App/pull/32461 is still a draft and it looks like a new PR has been raised for that same issue: https://github.com/Expensify/App/pull/35449. Either way, we're still on hold here.

**Comment by sakluger** [comment] 2024-03-11 16:48
The holding PR is merged and deployed, and I can't seem to reproduce this issue. I think it's fixed!

@aimane-chnaif I'm pretty sure no payment is due on this one, can you please confirm before I close the issue?

**Comment by sakluger** [comment] 2024-03-14 19:22
Sounds good. If we need to reopen this issue in the future, can you please bump in Slack instead? I sometimes miss notifications related to closed GH issues.

**Closed by sakluger** 2024-03-14 19:22 UTC
Labels: External, Daily, Help Wanted, Bug
