### ISSUE TITLE
Xero - The app becomes slow/unresponsive after connecting to Xero

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44680] opened 2024-07-01 13:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4682967&group_by=cases:section_id&group_id=309134&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precontidion: Reinstall the app.
1. Open the app
2. Log in with a new account
3. Create a workspace
4. Enable "Accounting" from the workspace settings
5. Navigate to Accounting
6. Connect to Xero
7. Tap on "Other integrations" after Xero finished syncing
8. Tap on "Other integrations" again

## Expected Result:
I should be able to navigate freely without anything slowing down

## Actual Result:
The app becomes slow/unresponsive after connecting to Xero

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/72dcc6df-2467-44ae-aa19-04036efb94a4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-01 13:33
@carlosmiceli  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-01 13:34
We think that this bug might be related to #wave-collect - Release 2

**Comment by carlosmiceli** [comment] 2024-07-01 15:42
Looking into it...

**Comment by carlosmiceli** [comment] 2024-07-01 18:28
Having issues with my local setup, still on it.

**Comment by jasperhuangg** [comment] 2024-07-01 19:33
@carlosmiceli This PR seems related and is on staging: https://github.com/Expensify/App/pull/43820

I'd look there first to see if anything obvious stands out to you.

**Comment by jasperhuangg** [comment] 2024-07-01 19:34
cc @tienifr @Julesssss @rushatgabhane Do you guys mind taking a look to see if this is related/if there's a quick fix we could push out>

**Comment by carlosmiceli** [comment] 2024-07-01 19:36
@jasperhuangg Yeah, did see that one and mentioned it [here](https://expensify.slack.com/archives/C03TQ48KC/p1719858365760589), but can that change make performance of the app so broken? It seemed weird to me... Thanks for checking it out though!

**Comment by jasperhuangg** [comment] 2024-07-01 23:54
This seems like another PR that could be related: https://github.com/Expensify/App/pull/44218

cc @carlosmiceli

**Comment by mananjadhav** [comment] 2024-07-02 00:00
> This seems like another PR that could be related: #44218
> 
> cc @carlosmiceli

Unlikely because we only changed the copies in that PR.

**Comment by mananjadhav** [comment] 2024-07-02 00:02
Also not sure why `Token Input` PR is linked, it's not even merged yet.

**Comment by jasperhuangg** [comment] 2024-07-02 00:04
@mananjadhav There were probably PRs that I linked here that were mentioned in that issue but not directly related, sorry for any confusion.

**Comment by mananjadhav** [comment] 2024-07-02 00:17
I tried reproducing it on my local with Android emulator and **I couldn't**. I even removed the app and reinstalled.

https://github.com/Expensify/App/assets/3069065/f00e8baf-7e68-4c12-897b-dacc8aab2bd7

**Comment by jasperhuangg** [comment] 2024-07-02 00:49
@mananjadhav Did you have the `staging` or `main` branch checked out when you did that?

**Comment by mananjadhav** [comment] 2024-07-02 00:56
I checked main.

**Comment by jasperhuangg** [comment] 2024-07-02 00:59
Removing the deploy blocker label since this doesn't seem to be reproducible on main anymore. Will stick the `retest-weekly` label on and we can check back to see if it crops up again.

**Comment by carlosmiceli** [comment] 2024-07-02 01:21
Will stay assigned to it but will move it to Weekly since you added the retest-weekly label.

**Comment by mvtglobally** [comment] 2024-07-11 03:51
Issue not reproducible during KI retests. (First week)

**Comment by carlosmiceli** [comment] 2024-07-11 13:22
I think we can close this one at this point.

**Closed by carlosmiceli** 2024-07-11 13:22 UTC
Labels: Engineering, Weekly, Overdue, retest-weekly
