### ISSUE TITLE
Payments - Default label isn't stick to the personal account after added as default payment, but it works while offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12950] opened 2022-11-23 00:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Went to Workspace > Connect Bank Account and added a Business bank account
3. Verified it appears in Settings > Payments
4. Tapped on it and verified "Make default payment Method" does not appear
5. From Settings > Payments, added a personal bank account
6. Verified it appears in Settings > Payments
7. Tapped on it and verified "Make default payment Method" appears
8. Put your password and make as default payment
9. Repeat steps 5-8 while offline ( you will notice that default label appears) 

## Expected Result:
Default label is stick to the personal account after added as default payment

## Actual Result:
Default label isn't stick to the personal account after added as default payment, but it works while offline

## Workaround:
Unknown

## Platform:

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.30.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203446141-3367869b-6d71-4a8b-bfcc-7d7a566ab368.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-11-23 00:23
Gonna assign myself to this one since I came back from ooo and I'm looking for WAQ issues to work on.

**Comment by luacmartins** [comment] 2022-11-23 20:00
@kbecciv steps 5-8 don't seem to be available offline as the buttons are disabled. Could you please share a video of the issue?

**Comment by mvtglobally** [comment] 2022-11-23 21:25
@luacmartins, Updated the issue.

**Comment by luacmartins** [comment] 2022-11-23 21:35
Thanks! I'll take a look.

**Comment by luacmartins** [comment] 2022-11-24 00:13
@mvtglobally sorry to bother you again, but can you share the credentials of the account used? I'm having trouble reproducing the error.

**Comment by kbecciv** [comment] 2022-11-24 02:10
Credentials:
applausetester+0901abb@applause.expensifail.com/Feya86Katya

**Comment by luacmartins** [comment] 2022-11-28 21:05
Thanks! I'll get to this tomorrow!

**Comment by luacmartins** [comment] 2022-12-01 21:54
Gonna try to get to this tomorrow!

**Comment by luacmartins** [comment] 2022-12-05 19:35
Closing since this is not an issue!

**Closed by luacmartins** 2022-12-05 19:35 UTC
Labels: Engineering, Daily, Bug
