### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Group chat - User mention is not copied when copying "made an admin" whisper to clipboard

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40477] opened 2024-04-18 16:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Create a group chat with User B.
4. Send a message to the group chat.
5. Click on the chat header > Members.
6. Invite User B.
7. As User B, go to the group chat.
8. Right click on the whisper "made @user an admin" > Copy to clipboard.
9. Paste the content.
## Expected Result:
The user mention in the whisper is copied.

## Actual Result:
The user mention in the whisper is not copied.
The user mention is also missing in LHN.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/800261ee-1d6f-4604-add9-c0d2b5918bc9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c22e43e02e5a0415</li>
        <li>Upwork Job ID: 1785752223998607360</li>
        <li>Last Price Increase: 2024-06-26</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 102966441</li>
<li>ahmedGaber93 | Contributor | 102966443</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by m-natarajan** [comment] 2024-04-18 16:18
@isabelastisser FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment] 2024-04-18 16:18
We think this bug might be related to #vip-vsb

**Comment by francoisl** [comment] 2024-04-18 16:56
I feel like this has to do more with how we copy text from mentions specifically, because the message is in the format `"<muted-text>made <mention-user accountID=NNN></mention-user> an admin</muted-text>"`.

<img width="1020" alt="image" src="https://github.com/Expensify/App/assets/2229301/0fe2fe43-52f3-457b-8dbf-0d7a569c415f">

Not sure it needs to be a blocker as it doesn't stop you from doing anything critical though.
In the meantime, cc @puneetlath if you have any idea off the top of your head what this could be from.

**Comment by ahmedGaber93** [comment] 2024-04-18 17:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Group chat - User mention is not copied when copying "made an admin" whisper to clipboard
### What is the root cause of that problem?
Mentioned user come from backend with different format unlike what we handle it now when get message text to copy it to clipboard.
https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L395-L398
```javascript
<mention-user accountID=123></mention-user> // formate in this issue 
<mention-user>@login</mention-user> // current formate we handle it in copy to clipboard now
```

### What changes do you think we should make in order to solve the problem?
We need to handle this format by edit this `replace` or add extra `replace` to handle it [here](https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L395-L398)
```javascript
// content.replace(/(<mention-user>)(.*?)(<\/mention-user>)/gi, (match, openTag, innerContent, closeTag): string => {
content.replace(/(<mention-user(?:\s+accountID=(\d*))?>)(.*?)(<\/mention-user>)/gi, (match, openTag, accountID, innerContent, closeTag): string => {
    if (accountID){
        const modifiedContent = `@${Str.removeSMSDomain(getLoginsByAccountIDs([accountID])[0])}`
        return openTag + modifiedContent + closeTag || '';
    }
    const modifiedContent = Str.removeSMSDomain(innerContent) || '';
    return openTag + modifiedContent + closeTag || '';
})
```


### What alternative solutions did you explore? (Optional)

**Comment by marcaaron** [comment] 2024-04-18 19:00
I don't think this worth blocking deploy over so gonna demote. Also can we check to see if the behavior works for Rooms?

@francoisl if you want me to grab this I can as it's related to Group Chats.

**Comment by francoisl** [comment] 2024-04-19 04:18
@marcaaron if you have the bandwidth, yes feel free to grab this one 🙏 I'm still catching up on some overdue issues from OOO.

**Comment by puneetlath** [comment] 2024-04-19 17:29
I'm guessing it's something we just haven't built yet for accountID-based mentions.

**Comment by isabelastisser** [comment] 2024-05-01 19:13
@marcaaron, are you able to work on this?

**Comment by marcaaron** [comment] 2024-05-01 19:24
Yeah, let's put an `External` label on it? C+ can review any proposals.

**Comment by ahmedGaber93** [comment] 2024-05-02 23:31
## Proposal
[Updated](https://github.com/Expensify/App/issues/40477#issuecomment-2064649852)

Add alternative solution.

Also, I think we can fix this issue and #40403 in one PR by the alternative solution.

**Comment by eh2077** [comment] 2024-05-03 00:59
> Also, I think we can fix this issue and https://github.com/Expensify/App/issues/40403 in one PR by the alternative solution.

@Santhosh-Sellavel Should we put this issue on hold? I saw you have already started reviewing https://github.com/Expensify/App/issues/40403

**Comment by isabelastisser** [comment] 2024-05-03 15:51
@Santhosh-Sellavel and @marcaaron, should we put this on hold?

**Comment by marcaaron** [comment] 2024-05-03 20:55
@eh2077 can you answer the above please? 

I'll jump back in here when have a proposal that's ready to review.

**Comment by eh2077** [comment] 2024-05-03 21:12
> @Santhosh-Sellavel and @marcaaron, should we put this on hold?

@isabelastisser I think we should put this on hold because the other issue is likely to be ended up a holistic approach that might help with this issue as well.

**Comment by Santhosh-Sellavel** [comment] 2024-05-03 21:46
@eh2077 Yes, the fix should be addressing both issues. So feel free to review proposal if you have bandwidth as I running with less bandwidth. Let's put the other one on hold.

**Comment by marcaaron** [comment] 2024-05-04 00:57
Ok let's actually then just assign whoever is handling that and we can remove the `Help Wanted` label.

**Comment by marcaaron** [comment] 2024-05-04 00:58
Oh, it doesn't look like anyone is assigned. Anyways - @eh2077 let us know what we need to do when this is ready and I can update the assignments. You got this 😉

**Comment by eh2077** [comment] 2024-05-04 01:28
Reviewing proposals

**Comment by ahmedGaber93** [comment] 2024-05-06 04:45
## Proposal
[Updated](https://github.com/Expensify/App/issues/40477#issuecomment-2064649852)

Add the full changes we need it in the alternative solution for `accountIDToName` following the changes here https://github.com/Expensify/App/issues/40403#issuecomment-2091898840 for `reportIdToName`.

**Comment by eh2077** [comment] 2024-05-06 04:53
@ahmedGaber93 Thanks for the update! I'm reviewing the proposal. Will update later

**Comment by eh2077** [comment] 2024-05-07 03:27
@ahmedGaber93 's [proposal](https://github.com/Expensify/App/issues/40477#issuecomment-2064649852) looks good to me. I think we should go with the alternative solution to fix this issue in `ExpensiMark`.
 
Though the solution of https://github.com/Expensify/App/issues/40403 is similar to this one, they don't share same code - they're handled case by case according to the pattern of `ExpensiMark`. That said, it also makes sense to me to fix them separately.

🎀👀🎀 C+ reviewed

**Comment by marcaaron** [comment] 2024-05-07 19:39
Curious to get @puneetlath's input here on that proposal.

>Though the solution of https://github.com/Expensify/App/issues/40403 is similar to this one, they don't share same code - they're handled case by case according to the pattern of ExpensiMark. That said, it also makes sense to me to fix them separately.

I'm not sure if I agree with this statement. We should be trying to write solutions that are holistic wherever possible. Having two separate implementations doing very similar stuff feels like we can come up with one proposal.

We can still treat them like two separate bugs (and get paid for both) - but let's work on the solution a bit more. @ahmedGaber93 What do you think about that?

**Comment by ahmedGaber93** [comment] 2024-05-07 20:18
@marcaaron Yes I agree, the holistic plan makes the development process easier, as the both fixes have the same fix pattern (but not the same code), so I agree to fixing them in one PR in expensify-common and expensify repo.

**Comment by eh2077** [comment] 2024-05-10 12:04
I also agree to fix them together in one PR.

Let me summarise a bit on what the similar fix pattern looks like.

1. Prepare two maps
    - `function getReportIdToName(): Record<string, string> | undefined {`
    - `function getAccountIDToName(currentUserAccountID: number): Record<string, string> | undefined {`
2. From App, pass them to parser
    - `parser.htmlToText(content, {accountIDToName, reportIdToName})`
    - `parser.htmlToMarkdown(content, {accountIDToName, reportIdToName})`
3. Improve the regex rule of `ExpensiMark` if needed
    - [htmlToMarkdownRules](https://github.com/Expensify/expensify-common/blob/1713f28214f0e7176c4fd13433fb0ea15491ebf9/lib/ExpensiMark.js#L467-L490)
    - [htmlToTextRules](https://github.com/Expensify/expensify-common/blob/1713f28214f0e7176c4fd13433fb0ea15491ebf9/lib/ExpensiMark.js#L534-L557)

Currently, I think it looks fine to handle the two mentions in two different tags, `<mention-user>` and `<mention-report>`. 

@marcaaron What do you think?

**Comment by marcaaron** [comment] 2024-05-10 22:43
Yeah that's the general approach I'd take. But I'd like to get @puneetlath's feedback before moving forward. They implemented this feature originally so I think they should have the best context and final say. I don't think this is particularly urgent so let's give it a bit of time.

**Comment by eh2077** [comment] 2024-05-13 14:15
Not overdue, we're waiting for @puneetlath 's input.

**Comment by puneetlath** [comment] 2024-05-13 15:30
That makes sense to me. @robertKozik @rlinoz have we done similar elsewhere?

**Comment by rlinoz** [comment] 2024-05-13 16:27
I think we haven't used the `extras` param yet, but it was added for this kind of situation as far as I can tell https://github.com/Expensify/expensify-common/pull/686

**Comment by robertKozik** [comment] 2024-05-13 17:50
Yes, I've introduced `extras` arguemnt to pass such a data to parser. Currently on main we don't have any usages yet, but this PR will introduce it: https://github.com/Expensify/App/pull/40565. I suggest that we can hold this task until #40565 would be merged as in that PR we will introduce [`OnyxAwareParser`](https://github.com/Expensify/App/pull/40565/files#diff-e558b35a1071080c2151e3572a90d5e8275cc6ab9886bd7ed878f5ddcddeedf3) which would encapsulate creating id maps

**Comment by eh2077** [comment] 2024-05-15 17:09
@marcaaron Should we put this issue and https://github.com/Expensify/App/issues/40403 on hold for https://github.com/Expensify/App/pull/40565?

**Comment by isabelastisser** [comment] 2024-05-17 20:37
@marcaaron, can I put this on hold based on the comments above?

**Comment by marcaaron** [comment] 2024-05-21 20:14
cc @eh2077

**Comment by eh2077** [comment] 2024-06-12 16:11
Melvin this is on hold and we'll revisit this when the linked issue is resolved.

**Comment by lakchote** [comment] 2024-07-01 08:38
@eh2077 #40565 has been merged. cc @marcaaron 

I'm removing the HOLD in the issue's title accordingly.

**Comment by eh2077** [comment] 2024-07-01 11:57
Yes, it's still reproducible 


https://github.com/Expensify/App/assets/117511920/c232ef71-002d-4a90-9b4c-77ccb86befc0

@ahmedGaber93 Can you update your proposal?

**Comment by ahmedGaber93** [comment] 2024-07-01 21:53
## Proposal
[Updated](https://github.com/Expensify/App/issues/40477#issuecomment-2064649852) @eh2077

**Comment by eh2077** [comment] 2024-07-02 01:03
@ahmedGaber93 Thanks for the update!

@ahmedGaber93 's [proposal](https://github.com/Expensify/App/issues/40477#issuecomment-2064649852) looks good to me. Their improved regex works for both self closing and non self closing tags.
<img width="680" alt="image" src="https://github.com/Expensify/App/assets/117511920/dd6144f9-43a6-4d69-9c5e-35ff186e8baf">

We can fix both `<mention-user>` and `<mention-report>` (https://github.com/Expensify/App/issues/40403) tags together.

🎀👀🎀 C+ reviewed

@marcaaron All yours

cc @lakchote

**Comment by ahmedGaber93** [comment] 2024-07-04 18:57
@eh2077 PR https://github.com/Expensify/expensify-common/pull/741 is ready for review

**Comment by eh2077** [comment] 2024-07-09 15:38
The PR for expensify-common has been merged and we're waiting for the PR for App. 

@ahmedGaber93 Friendly bump

**Comment by ahmedGaber93** [comment] 2024-07-10 04:56
@eh2077 we use expensify-common `2.0.26` in E/App now, and PR https://github.com/Expensify/expensify-common/pull/741 is pushed to new version `v2.0.39`. So I think we need to wait for expensify-common bump to `v2.0.39` before create E/App PR.

**Comment by eh2077** [comment] 2024-07-10 05:23
@ahmedGaber93 I think you can just bump the version together with the fix in your PR if there is no ongoing PR to bump the version

**Comment by ahmedGaber93** [comment] 2024-07-10 06:01
@eh2077 I will create the PR today

**Comment by isabelastisser** [comment] 2024-07-18 17:41
I will be OOO tomorrow and next week, so I am reassigning this until I return on July 29. Thanks, @mallenexpensify!


Status: 

- @ahmedGaber93 needs to complete the BZ checklist.
- Payment is due on July 24.

**Comment by ahmedGaber93** [comment] 2024-07-21 11:15
> @ahmedGaber93 needs to complete the BZ checklist.

@eh2077 is the C+ for this issue. @eh2077 Could you please complete it when you have a chance? Thanks!

**Comment by eh2077** [comment] 2024-07-22 14:13
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**I can't figure out the specific PR caused this bug.**_ We have waited for a while to get this fixed based on this [feat](https://github.com/Expensify/App/pull/40565)
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. No, as we have unit tests to cover it.

**Comment by eh2077** [comment] 2024-07-22 14:21
@isabelastisser I think you can handle the payment together with https://github.com/Expensify/App/issues/40403 because we fixed them together here. The bounty should be $250 + $250 = $500 as mentioned earlier, see https://github.com/Expensify/App/issues/40477#issuecomment-2099166245

> We can still treat them like two separate bugs (and get paid for both) - but let's work on the solution a bit more. @ahmedGaber93 What do you think about that?

cc @marcaaron @lakchote

**Comment by mallenexpensify** [comment] 2024-07-22 22:05
@eh2077 is there any reason to keep [the other issue ](https://github.com/Expensify/App/issues/40403)open? Possibly we need a regression test for that use flow?   
If not, lit _seems_ best to close that one and manage payment ($500/each) here.

**Comment by eh2077** [comment] 2024-07-22 23:48
@mallenexpensify Yes, we can close the other issue https://github.com/Expensify/App/issues/40403.

### Regression test

1. Open any workspace chat
2. Send a message contain mention user and mention report and other text `@MENTION_USER text after #MENTION_REPORT text after`
3. Right click on the sent message then Copy to clipboard.
4. Paste the copied text in comopser and Verify the message pasted successfully with mentions

Do we agree 👍 or 👎

**Comment by marcaaron** [comment] 2024-07-23 00:16
LGTM

**Comment by mallenexpensify** [comment] 2024-07-23 00:34
Thanks @eh2077, issue closed, Test case created
- https://github.com/Expensify/Expensify/issues/414530

**Closed** 2024-07-26 22:46 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by eh2077** [comment] 2024-07-27 00:00
@mallenexpensify Can you help to issue the payment as discussed here https://github.com/Expensify/App/issues/40477#issuecomment-2243891712

**Comment by mallenexpensify** [comment] 2024-07-30 21:47
Contributor: @ahmedGaber93  paid $500 via Upwork
Contributor+: @eh2077 paid $500 via Upwork. 

@eh2077 thanks for the reminder, sorry I missed this (likely thought payment was via the other issue)
