### ISSUE TITLE
[HOLD for payment 2024-11-26] [$250] Search - Search icon briefly appears on RHP when report RHP is dismissed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51730] opened 2024-10-30 12:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Н
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Have some expenses
1. Go to staging.new.expensify.com
2. Go to Search
3. Click on any expense
4. Dismiss the RHP

## Expected Result:
Search icon will not appear on RHP when RHP is dismissed

## Actual Result:
Search icon briefly appears on RHP when RHP is dismissed (not the search icon in the background, it appears in the RHP briefly)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

<img width="1438" alt="3 12" src="https://github.com/user-attachments/assets/857424b6-01bf-4c52-8219-5952c8865cbe">

https://github.com/user-attachments/assets/c2f6719b-7cf2-4323-94a2-690b73e608c3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851818502935081343</li>
        <li>Upwork Job ID: 1851818502935081343</li>
        <li>Last Price Increase: 2024-11-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by lanitochka17** [comment] 2024-10-30 12:41
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-10-30 12:42
We think that this bug might be related to #wave-control

**Comment by FitseTLT** [comment] 2024-10-30 12:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Search - Search icon briefly appears on RHP when report RHP is dismissed

### What is the root cause of that problem?
To display the search button we ensure that the report is not opened in RHP
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/components/MoneyRequestHeader.tsx#L68
The `isReportOpenInRHP` determines whether the report is open in RHP using the current navigation root state but the problem is `isReportInRHP` is updated every time there is a re-render so the value is determined on the navigation state at which the rerender happened so if current focused screen is not open in RHP when the re-calculation happened it will update the `isReportInRHP` false and so while the navigate back animation is going the search will be shown because the nav state is updated to make isReportInRHP `false`
### What changes do you think we should make in order to solve the problem?

We should calculate the isReportInRHP value once when the navigation is ready so we should:
```
const [isReportInRHP, setIsReportInRHP] = useState(true);
    useEffect(() => {
        Navigation.isNavigationReady().then(() => {
            setIsReportInRHP(isReportOpenInRHP(navigationRef?.getRootState()));
        });
    }, []);
```
We should do the same [here](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/components/MoneyReportHeader.tsx#L179) and [here](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/pages/home/HeaderView.tsx#L144)
### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-10-30 13:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency in displaying Search icon when returning to expenses opened from Search
### What is the root cause of that problem? 
[Here](https://github.com/Expensify/App/blob/b7c1cfafecd03db14de4a4a30ac155fe4a7fb28b/src/components/MoneyReportHeader.tsx#L179C1-L180C54) we have a check to hide search icon if the report opened in `RHP`.  But this check does not work correct because it checks last route in navigation state  and on navigating back the last route updates faster then the close animation of RHP and causing the [isReportInRHP](https://github.com/Expensify/App/blob/b7c1cfafecd03db14de4a4a30ac155fe4a7fb28b/src/components/MoneyReportHeader.tsx#L179C11-L179C24) become `false`.
### What changes do you think we should make in order to solve the problem?
Add one more check ( if screen is focused ) to [this](https://github.com/Expensify/App/blob/b7c1cfafecd03db14de4a4a30ac155fe4a7fb28b/src/components/MoneyReportHeader.tsx#L180C39-L180C53). 
```
const isFocused = useIsFocused();
... 
isFocused && !isReportInRHP;
```
The same updates needed [here](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/components/MoneyRequestHeader.tsx#L68C1-L69C54) and [here](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/pages/home/HeaderView.tsx#L144C1-L145C54)
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-10-30 13:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search icon appears briefly when report rhp is closing.

### What is the root cause of that problem?
We don't show the search icon if the last route is report RHP.
https://github.com/Expensify/App/blob/803821640f120e5674a8b307e701b4799c1897c0/src/components/MoneyReportHeader.tsx#L179-L180

But because it depends on the last route, when RHP is closing, the last route won't be report RHP anymore, and `isReportInRHP` becomes false, so the search icon is shown.

### What changes do you think we should make in order to solve the problem?

Instead of depending on the last route, we can just check whether it's in report RHP if the page route name is report RHP.
```
const route = useRoute();
const isReportInRHP = route.name === SCREENS.SEARCH.REPORT_RHP;
```

We need to apply to all MoneyReportHeader, MoneyRequestHeader, and HeaderView.

Optionally, we can pass `isReportInRHP` from ReportScreen.

**Comment by jliexpensify** [comment] 2024-10-31 02:52
I can reproduce this one - pretty sure that `search` icon is unnecessary in this context.

**Comment by jjcoffee** [comment] 2024-11-01 14:45
Thanks for the proposals everyone! 

I think the primary root cause here is that `isReportOpenInRHP` shouldn't be used here as it depends on the last route which won't give us the right result whilst the modal is closing. Therefore I think @bernhardoj's [proposal](https://github.com/Expensify/App/issues/51730#issuecomment-2447144551) makes the most sense here as it provides the simple solution of just pulling the current route. 

This is not only simpler, but deals with the primary issue of `isReportOpenInRHP` not being fit for our purposes here, rather than trying to implement workarounds as the other proposals do.

**Comment by jjcoffee** [comment] 2024-11-01 14:47
Most importantly... :sweat_smile: 

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment] 2024-11-05 08:43
We're just waiting for @grgia to assign @bernhardoj.

**Comment by jliexpensify** [comment] 2024-11-07 23:09
Not overdue, bumping @grgia [on this comment](https://github.com/Expensify/App/issues/51730#issuecomment-2456561773)

**Comment by jjcoffee** [comment] 2024-11-11 13:05
@grgia Friendly bump! We just need to assign @bernhardoj here.

**Comment by jjcoffee** [comment] 2024-11-14 09:20
@jliexpensify Should we assign another CME here? It's been 2 weeks since I reviewed. I'm not sure if @grgia is OOO but I've also tried [bumping](https://expensify.slack.com/archives/C02NK2DQWUX/p1731490291883769) on Slack and haven't had any response.

**Comment by jliexpensify** [comment] 2024-11-14 09:42
@jjcoffee I've just DM-ed @grgia, lets give her today to review. She should be online now.

**Comment by grgia** [comment] 2024-11-14 09:48
@jliexpensify @jjcoffee Woah, apologies! This issue completely slipped under my radar. @jliexpensify Please feel free to star me in k2 next time around- I think I had unstarred issues hidden

**Comment by jliexpensify** [comment] 2024-11-25 20:04
@jjcoffee - payment date is tomorrow, so bumping you for the checklist!

**Comment by jliexpensify** [comment] 2024-11-25 20:04
Payment Summary

- C: @bernhardoj $250 (to be paid via ND requests)
- C+: @jjcoffee $250 (to be paid via ND requests)

**Comment by bernhardoj** [comment] 2024-11-26 00:24
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-11-26 08:32
$250 approved for @bernhardoj

**Comment by jjcoffee** [comment] 2024-11-26 09:03
@jliexpensify Done!

**Comment by garrettmknight** [comment] 2024-11-26 14:04
$250 approved for @jjcoffee

**Comment by jliexpensify** [comment] 2024-11-26 22:51
Sweet, closing! Thanks everyone.

**Closed by jliexpensify** 2024-11-26 22:51 UTC
Labels: External, Daily, Awaiting Payment, Bug
