### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Request money - No autofocus blink cursor shown in Request money page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26994] opened 2023-09-07 20:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to fab button -> request money ->Manual
2. Notice that there is no blinking cursor beside the currency symbol .
( however if the request money page was previously set to scan or distance pages, such behaviour doesn't appear. Thus make sure after clicking request money, manual section is opened automatically)
3. Close the RHN and again go to fab button -> split bill
4. Notice that there appears blinking cursor beside currency symbol

## Expected Result:
Consistency in pages in split money and request money ( Manual)

## Actual Result:
No autofocus blink cursor shown in Request money page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.65-6

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/8a75e992-eda4-474b-876d-8af7b483a95e

https://github.com/Expensify/App/assets/115492554/deed1b2f-5f83-48c7-8a6e-99d8ee4573ae

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693742251468319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0c4dd10133dafa2</li>
        <li>Upwork Job ID: 1701221973754032128</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26670391</li>
<li>Krishna2323 | Contributor | 26670393</li>
<li>ashimsharma10 | Reporter | 26670394</li>
</ul></li>
    </ul>
</details>

**Comment by MariaHCD** [comment] 2023-09-14 02:35
Can we recheck if this is still an issue? I wasn't able to see the issue on dev, staging or production:

https://github.com/Expensify/App/assets/12268372/ed478d65-30b0-46d3-9503-c9b8f23cbfe9

**Comment by MariaHCD** [comment] 2023-09-14 03:46
Ah, thanks, @Krishna2323. I totally missed that!

So will your proposal set the `keyboardDismissMode` TopTab.Navigator configuration across the whole app? Does this affect mobile in any way?

**Comment by MariaHCD** [comment] 2023-09-14 04:21
Okay, thanks for clarifying. Could you update your proposal with the exact code changes you're proposing?

**Comment by MariaHCD** [comment] 2023-09-14 09:25
Thanks, the proposal makes sense to me. We'll just have to ensure it does not cause any unexpected side effects.

**Comment by MariaHCD** [comment] 2023-09-22 04:39
@Krishna2323 I believe the additional issue identified had the same root cause so I am not sure this would be eligible for a bonus. We normally pay out bonuses if the issue/solution becomes more complicated/challenging and the contributor has to invest more time/effort into the issue.

However, I will defer to @NicMendonca 

@Krishna2323 could you can explain why you feel your work on this issue deserves a bonus?

**Comment by MariaHCD** [comment] 2023-09-22 05:31
Hmm, so we tried to fix the same issue on iOS native but that led to a bit of a delay in getting the PR merged. I think it's all part of the review process and you did handle addressing the reviews with urgency so I think paying out the bonus in this case is fine. Regardless, I'll leave the final call to @NicMendonca

**Comment by NicMendonca** [comment] 2023-10-02 14:33
@fedirjh bump on the BZ issue ^^

**Comment by NicMendonca** [comment] 2023-10-02 14:36
Reporter: @ashimsharma10 - $50
Contributor: @Krishna2323 - $750
C+ @fedirjh -  $750

**Comment by NicMendonca** [comment] 2023-10-02 14:36
@Krishna2323 @ashimsharma10 - you've both been paid 🎉 


@fedirjh can you please accept the offer in Upwork?

**Comment by NicMendonca** [comment] 2023-10-03 18:47
@fedirjh bump bump on [BZ checklist](https://github.com/Expensify/App/issues/26994#issuecomment-1733260790)

**Comment by NicMendonca** [comment] 2023-10-04 15:50
@fedirjh thanks! You've been paid via Upwork🎉 

All set here ✅

**Closed by NicMendonca** 2023-10-04 15:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
