### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] [MEDIUM] IOU - Money request page displays skeleton in online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26424] opened 2023-08-31 19:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Preferences
4. Toggle on force offline
5. Navigate back to LHN
6. Tap IOU report for request money received
7. Note the IOU report page keeps loading
8. Tap Pay elsewhere
9. Navigate back to LHN and again visit IOU to note page keeps loading
10. Navigate to LHN
11. Tap profile
12. Tap preferences
13. Toggle off force offline
14. Navigate back to LHN
15. Tap IOU report

## Expected Result:
Output of @mountiny & I discussing this one [here](https://github.com/Expensify/App/issues/26424#issuecomment-1776979331) for reference. 

- We have the report total loaded in the iouReport data, so we should show the report total in the report where possible when offline.
-The iouActions we can't load would still show with a skeleton UI as we do today (we agreed just the one request preview component appearing as a skeleton is fine). 
When a new request is added to the request when offline and appears at 50% opacity in the pending create state, so should the report total in the expanded header area.

## Actual Result:
In online, in IOU report for request money, the page keeps on loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b3257238-8c59-4e60-a84b-8dce2d6bc3cf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012efb1896a46c34c4</li>
        <li>Upwork Job ID: 1707346943173816320</li>
        <li>Last Price Increase: 2024-02-13</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment] 2023-09-01 11:36
When I come back online, they eventually load and the skeleton UI goes away, so that's contrary to the bug report. When we can't load the content, the skeleton UI is the correct pattern to use.


https://github.com/Expensify/App/assets/16232057/6fb31b6d-d28b-4081-8a81-8d573e56d31e

I'm curious why the report total extended header in the iouReport isn't available to view offline in the first place though, and whether we can improve that in the spirit of offline-first?

CC: @mountiny @luacmartins @JmillsExpensify

**Comment by luacmartins** [comment] 2023-09-01 16:51
It seems like a regression. I agree they should be working offline.

**Comment by mountiny** [comment] 2023-09-01 17:04
> I'm curious why the report total extended header in the iouReport isn't available to view offline in the first place though, and whether we can improve that in the spirit of offline-first?

Yep I think in offline it can work like that, online we probably still need to show the skeleton

**Comment by trjExpensify** [comment] 2023-09-04 09:45
Can you expand on that, @mountiny? Why do we need to show the skeleton for the report total when online?

**Comment by mountiny** [comment] 2023-09-04 10:51
No we dont have to, sorry we were probably talking about different things

**Comment by trjExpensify** [comment] 2023-09-04 13:40
Cool, so we agree with the below? Then next question, is this going to need backend changes?

**Expected results**
The report total in the expanded header area should be available to view when offline. 

**Actual Results**
The report total doesn't load, and shows a skeleton UI in its place when offline.

**Comment by mountiny** [comment] 2023-09-04 14:04
> The report total in the expanded header area should be available to view when offline.

What if you have exisitng IOU report and you sign out sign back in, you dont go to the IOU report so you dont have the report actions but you have the total.

You are offline, You request more, the total is updated and you see that offline made request but you dont see the previosu messages and there is no indication the report has more report actions while total is more. Is that fine as a feedback to the user while offline?

**Comment by trjExpensify** [comment] 2023-09-04 14:21
You might have to type that out again in steps for me to follow it completely sorry man. Let's park this and focus on the deploy for a sec.

**Comment by trjExpensify** [comment] 2023-09-11 11:21
Okaaaay. @mountiny, circling back here. Mind rephrasing? 😄

**Comment by mountiny** [comment] 2023-09-11 14:37
1. You fresh sign in
2. you have the IOU report data and its total ($50) locally with user B
3. You go offline
4. you request more money $10 from the user B
5. We wont show a skeleton, one report action done optimistically with $10 and total of $60

If there is no skeleton, then it might be confusing to the user as there is only one report action and they cannot see the others

**Comment by shawnborton** [comment] 2023-09-11 14:59
Yeah, I think that makes sense to me.

**Comment by mountiny** [comment] 2023-09-11 15:07
@trjExpensify In this case you have visited the report before you went offline so you had the £50 report action. You could not have that if you would sig in and not open the report and went offline and then go to the report.

Its edge case but thats what we trying to cover here

**Comment by trjExpensify** [comment] 2023-09-11 15:13
I don't think I did visit the iouReport, no. Here's another one:


https://github.com/Expensify/App/assets/16232057/5914c142-4882-452d-864d-53715bef47f6

**Comment by mountiny** [comment] 2023-09-11 15:26
@trjExpensify yeah but you just created it locally so the request is there. You would have to create the request and report, then sign out and sign back in, request from global create from the same person, the historical report actions will be missing I believe because they do not load during openApp

**Comment by trjExpensify** [comment] 2023-09-15 15:52
Going to chat with Vit about this on Monday.

**Comment by mountiny** [comment] 2023-09-25 14:18
Made this one weekly, dont think its daily priority

**Comment by abdulrahuman5196** [comment] 2023-10-01 08:01
@trjExpensify I am not sure on the plan of this issue? Is someone going to pick up this issue internally?

**Comment by trjExpensify** [comment] 2023-10-02 20:52
Yeah, I can't reproduce the OP of this issue, so it's not a bug as reported. I did stumble on something else that Vit and I are talking about above that may or may not need BE changes if we do something about it. 

Things we agree on so far we should change: 

- When you're offline and add a request to a report, the reportTotal should also be at 50% opacity to signal that it's pending, just like the request added to the report that's displayed at 50% opacity.

Outstanding to work through:
- why the report header should show an infinite loading skeleton UI when offline in some case that I'm trying to repro that Vit mentioned above

**Comment by trjExpensify** [comment] 2023-10-06 15:25
No change.

**Comment by trjExpensify** [comment] 2023-10-10 23:31
Maybe Vit and I can talk about this in one of the 42 threads tomorrow!

**Comment by trjExpensify** [comment] 2023-10-17 22:05
Set a NewDot task to bug us, melv.

**Comment by trjExpensify** [comment] 2023-10-24 10:53
Okay, Vit and I caught up. To summarise... 

- We have the report total loaded in the iouReport data, so we should show it in the report where possible when offline
- The iouActions we can't load would still show with a skeleton UI as we do today
- When a new request is added to the request when offline and appears at 50% opacity in the pending create state, so should the report total in the expanded header area

To illustrate that, here's a view of: 

1. Offline, opening a report where you can't load all the iouActions
2. Offline, adding a new request to the report where the request and the report total appear at 50% opacity 
3. coming back online, all the iou actions loading and the pending actions reverting to 100% opacity 

![image](https://github.com/Expensify/App/assets/16232057/1080dbc4-568d-408a-804c-cc77f64d8bf3)

**Comment by trjExpensify** [comment] 2023-10-30 10:30
@mountiny confirming you agree with the accuracy of the above summary? If so, I think we can move this on.

**Comment by mountiny** [comment] 2023-10-30 11:14
Yeah I agree with this, I am just not 100% sure we will know the number of the request. The report preview should have the child request count number so we should be able to, but I think if we cannot do that we should just show one preview skeleton for consistency, otherwise we can move this forwards

**Comment by trjExpensify** [comment] 2023-10-30 14:26
Ah, are you saying in the report view above the loaded iouAction and beneath the loaded report total the whole area is a skeleton versus just the request preview card of each iouAction that hasn't loaded?

**Comment by mountiny** [comment] 2023-11-01 12:16
> Ah, are you saying in the report view above the loaded iouAction and beneath the loaded report total the whole area is a skeleton versus just the request preview card of each iouAction that hasn't loaded?

No, what I meant is that we should either show skeletons of the previews exactly based on the number of requests we know which are in the report, which I believe we should know,

or if we cannot, we should always just show one report preview card skeleton, not more.

Maybe the second version where we only show one report preview card skeleton no matter how many requests there might be in the report might be better as that will enable us to always show the total as well and will be consistent and at the same time will be more performant then showing potentially many skeletons

**Comment by mountiny** [comment] 2023-11-02 15:16
> Otherwise, you kind of think there's just the one if we skelly one preview and not the area above the one loaded and beneath the report total header area.

Is that important though? I think its fine to just show one, we are not indicating in any way there might be comments in between either

**Comment by trjExpensify** [comment] 2023-11-02 15:51
Not sure how important it is, but it's a little inaccurate tis' all. It's a fine starting point and not worth a performance hit if that's the case.

**Comment by mountiny** [comment] 2023-11-03 12:14
Sounds good!

**Comment by trjExpensify** [comment] 2023-11-06 11:37
Perfecto, let's move this on to solicit proposals. Confirming it can go external, right?

**Comment by mountiny** [comment] 2023-11-07 14:49
Yes

**Comment by trjExpensify** [comment] 2023-11-09 00:15
Proposals to review :)

**Comment by abdulrahuman5196** [comment] 2023-11-13 08:39
Hi, Will review today just back from weekend

**Comment by trjExpensify** [comment] 2023-11-14 21:23
@abdulrahuman5196 how's the review going?

**Comment by abdulrahuman5196** [comment] 2023-11-15 18:43
Hi, Will review again in my morning and update tomorrow

**Comment by abdulrahuman5196** [comment] 2023-11-16 16:24
Checking now

**Comment by abdulrahuman5196** [comment] 2023-11-16 18:15
@dukenv0307 Can you explain more on the first point? I am unable to understand this. What is this has to do with showing total from the IOU report data?
 And do double check the code pointer?

>In OpenApp/ReconnectApp, we need to return the CREATED report action of the iou report as well, currently we only return 1 money request report action initially. Once we fix to add CREATED report action in the back-end, then the report total will show fine, according to [this logic](https://github.com/Expensify/App/blob/b5a0a746a82d64104c6d9400d86acc83a7d312a5/src/pages/home/report/ReportActionItem.js#L610)

**Comment by mvtglobally** [comment] 2023-11-18 04:31
Issue not reproducible during KI retests. (First week)

**Comment by abdulrahuman5196** [comment] 2023-11-20 15:40
> Issue not reproducible during KI retests. (First week)

I highly doubt this, It is not reproducible?  Was it fixed somewhere?

**Comment by trjExpensify** [comment] 2023-11-21 14:26
I agree. How are we getting on with the proposal review @abdulrahuman5196?

**Comment by abdulrahuman5196** [comment] 2023-11-21 17:39
I still need to test the first point from the explanation. Will update here once checked.

**Comment by abdulrahuman5196** [comment] 2023-11-24 10:07
Reviewing again

**Comment by abdulrahuman5196** [comment] 2023-11-24 11:26
@dukenv0307 

> The total is displayed in MoneyRequestView which is the created action of the IOU report. So in OpenApp API, we should return the CREATED action of the report to make this can be displayed when we force offline before we go to the IOU report. If not, skeleton will display when we go to this report in offline mode.

Got it on what you are mentioning. Currently we use the 'CREATED' type of reportAction to show the `Total` header, but that is not loaded if we go to the money request page on offline case.

But the concern from OP was

```
We have the report total loaded in the iouReport data, 
so we should show the report total in the report where possible when offline.
```

So, we should check if its possible to show the total amount header with `Total` data used from other places(like iouReport data pointed in OP) apart from the CREATED type of reportAction.

**Comment by abdulrahuman5196** [comment] 2023-11-27 09:14
We don't have proposal to approve. Requested existing proposal to see if we can have any other way as suggested here - https://github.com/Expensify/App/issues/26424#issuecomment-1825535407

**Comment by abdulrahuman5196** [comment] 2023-11-27 10:47
> @abdulrahuman5196 What is the problem with this case? I don't see the problem in this comment [#26424 (comment)](https://github.com/Expensify/App/issues/26424#issuecomment-1825535407) ? Can you explain in more detail on that?

The question was to,
Instead of making BE change to return ReportAction of the 'CREATED' type on OpenApp, can we use other existing data source and display the header? As pointed in the OP.

**Comment by abdulrahuman5196** [comment] 2023-11-27 11:02
@dukenv0307 No.  You will already have the 'Total' data in the previous screens and I suppose report data will also be present. For example.

<img width="983" alt="Screenshot 2023-11-27 at 4 31 13 PM" src="https://github.com/Expensify/App/assets/46707890/0cfc48c2-e216-4783-8487-20643f357c79">


And also for MoneyRequestView we only provide the report

https://github.com/Expensify/App/blob/b5a0a746a82d64104c6d9400d86acc83a7d312a5/src/pages/home/report/ReportActionItem.js#L569

**Comment by trjExpensify** [comment] 2023-11-29 16:19
What's the latest here? @dukenv0307 are you making updates to the proposal or something else?

**Comment by mvtglobally** [comment] 2023-11-30 06:05
Issue not reproducible during KI retests. (Second week)

**Comment by mountiny** [comment] 2023-11-30 13:51
@dukenv0307 can you clarify what you mean exactly I see that we return created report action for expense/ iou reports 
<img width="672" alt="image" src="https://github.com/Expensify/App/assets/36083550/ccf8e282-00f3-4e36-b281-ad71216bac44">

**Comment by mountiny** [comment] 2023-11-30 14:34
the total is not stored in the created report action, maybe we talking about something else

**Comment by mountiny** [comment] 2023-11-30 19:09
Sorry is there some summary of the current problem?

**Comment by trjExpensify** [comment] 2023-12-06 12:07
@dukenv0307 let us know your thoughts on an alt!

**Comment by mountiny** [comment] 2023-12-06 13:11
Lets make a formal proposal and let @abdulrahuman5196 review it

**Comment by mvtglobally** [comment] 2023-12-08 05:02
Issue not reproducible during KI retests. (third week)

**Comment by trjExpensify** [comment] 2023-12-11 10:49
@abdulrahuman5196 can you review this please? https://github.com/Expensify/App/issues/26424#issuecomment-1842864977

**Comment by abdulrahuman5196** [comment] 2023-12-12 18:10
@dukenv0307 The updated point 1 in the proposal will cause a larger code refractor right? Or is it a considerable change?

Could you provide some high level information on the changes required as per the updated proposal?

**Comment by abdulrahuman5196** [comment] 2023-12-14 12:49
Got it. Let me also give a check on current code base to check the feasibility.

**Comment by abdulrahuman5196** [comment] 2023-12-18 07:57
Will check and update on this today https://github.com/Expensify/App/issues/26424#issuecomment-1855793632

**Comment by abdulrahuman5196** [comment] 2023-12-19 09:26
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-12-19 10:08
> You can try to create a new request money which will create new report preview. You will see the total is gray.

I think we can get this information also from other places IMO. But I think the header should be grayed out even if we have some single transaction. But anyways I will post a short summary on next comment.

**Comment by abdulrahuman5196** [comment] 2023-12-19 10:20
Posting a short summary,
I also did a check with the information from @dukenv0307 , And it seems even though `MoneyRequestView`(which displays the total) is only using the report data to show the total.
Our current code displays the  `MoneyRequestView` as part `ReportActionItem` under the `CREATED` reportAction type. 
https://github.com/Expensify/App/blame/9b71f2391c04a00e3a9a69904f1a1f02517494f6/src/pages/home/report/ReportActionItem.js#L621-L625

Approach 1:
As per our current code structure, for the `MoneyRequestView` to display we will need a report Action(atleast a dummy reportAction with `CREATED` type)

Approach 2:
If we need to render the total without report action, then we need to display the `MoneyRequestView` at a higher hierarchy in view atleast while rendering the `ReportActionsList` or above - 
https://github.com/Expensify/App/blob/9b71f2391c04a00e3a9a69904f1a1f02517494f6/src/pages/home/report/ReportActionsList.js#L378

This might bring in code checks which are different from our code structure. Like for eg, TaskView created action header will be rendered in `ReportActionItem` while `MoneyRequestView` will be rendered in `ReportActionsList` view. Or we might need to move all the created type reportActions to separate place which might be a bigger change.


  @mountiny These might cause the code change to be confusing. What do you think of  this? should we proceeding investigating different ways to solve this or should we wait for some other refractors to solve this(I saw in the comments you had mentioned "report pagination")? 

@dukenv0307 Also do point me if I had missed/wrongly interpreted something.

**Comment by abdulrahuman5196** [comment] 2023-12-19 10:37
>Do you think about generating created action for IOU in `ReportActionList` if it doesn't exist? 

Yep. That also comes under approach 1.

**Comment by trjExpensify** [comment] 2023-12-21 16:08
Thoughts on this, @mountiny? 

>@mountiny These might cause the code change to be confusing. What do you think of this? should we proceeding investigating different ways to solve this or should we wait for some other refractors to solve this(I saw in the comments you had mentioned "report pagination")?

**Comment by abdulrahuman5196** [comment] 2023-12-25 12:09
We are waiting on @mountiny 's input here https://github.com/Expensify/App/issues/26424#issuecomment-1862489536.

I think folks are off this week, so could expect delays in responses

**Comment by mountiny** [comment] 2023-12-25 23:44
@abdulrahuman5196 Thanks for the summary, really helpful.

I do think that we should avoid the approach 2 since there might be lots of refactorings and its not clear to me if its worth it.

I think we should just try to go approach 1, I dont think the CREATED action should be a requirement for this

**Comment by abdulrahuman5196** [comment] 2023-12-26 18:40
> I think we should just try to go approach 1, I dont think the CREATED action should be a requirement for this

@mountiny Thank you for the response.
But AFAIK, we would need a CREATED reportAction as pointed here https://github.com/Expensify/App/issues/26424#issuecomment-1862489536. Atleast a "On The Fly" object creation and append it while we pass the data to display the reportActions. 
But do let me know if there is another way to point.

**Comment by mountiny** [comment] 2023-12-26 21:43
I do think think its a weird pattern that we render this as part of the created report action so that could be refactored, I dont think there is any strict need for this is it?

But also we could create some on the fly `created` report actions in case there is no report action

**Comment by abdulrahuman5196** [comment] 2023-12-28 18:10
> I do think think its a weird pattern that we render this as part of the created report action so that could be refactored, I dont think there is any strict need for this is it?
> 
> But also we could create some on the fly `created` report actions in case there is no report action

Yes. I agree on this. But I am afraid this might also could lead to good amount of refractor. But anyways I will also look out for this. 

@dukenv0307 Could you also kindly check and update this as alternate solution if any possible.

**Comment by abdulrahuman5196** [comment] 2024-01-01 17:50
Waiting on @dukenv0307

**Comment by abdulrahuman5196** [comment] 2024-01-04 15:48
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-01-04 15:54
> I do think think its a weird pattern that we render this as part of the created report action so that could be refactored, I dont think there is any strict need for this is it?

Reference: https://github.com/Expensify/App/issues/26424#issuecomment-1869786363

@dukenv0307 Some questions on the same

1) Where you able to check on the above? I didn't see information of the same in the proposal. This could be a long term fix, but i think it could have multiple changes.
2) In the proposal to create On the Fly `CREATED` report actions, I don't think disturbing onyx would be a good idea. Shouldn't we just creating optimistic object and append it to actions list array and pass the same to `ReportActionsList` for it to display, instead of storing something in onyx.

**Comment by abdulrahuman5196** [comment] 2024-01-04 16:07
Thank you for the information @dukenv0307, could you also kindly update on the first question - https://github.com/Expensify/App/issues/26424#issuecomment-1877333201

**Comment by trjExpensify** [comment] 2024-01-08 12:25
Any feedback on that @abdulrahuman5196?

**Comment by mvtglobally** [comment] 2024-01-11 05:58
Issue not reproducible during KI retests. (Fourth week)

**Comment by abdulrahuman5196** [comment] 2024-01-11 10:09
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-01-18 17:11
> @abdulrahuman5196 Because we offline before we opened the report, reportActions of this report are not full. Only some reportActions that are returned in `openApp` API display.

@dukenv0307 We should be showing skeleton UI in this case IMO. I think that is also one of the requirements actually.

**Comment by mountiny** [comment] 2024-01-22 19:46
I would say ideally yes, any reason why not?

**Comment by trjExpensify** [comment] 2024-01-23 17:47
@abdulrahuman5196 we good here?

**Comment by abdulrahuman5196** [comment] 2024-01-29 10:08
Reviewing now

**Comment by mvtglobally** [comment] 2024-01-30 04:53
Issue not reproducible during KI retests. (Fifth week)

**Comment by abdulrahuman5196** [comment] 2024-01-30 15:54
> @abdulrahuman5196 So we can do the same way by generate some money request actions with `originalMessage.IOUTransactionID` is a random transactionID. the number of money request action will be `childMoneyRequestCount` minus the exist money request action returned by `OpenApp` API.

@dukenv0307 I am not super aligned on this. But I assume this is also something we won't have other option to from. (I would recommend to choose other option if any becomes available)

Could you kindly add how you would achieve the same on the proposal?

**Comment by trjExpensify** [comment] 2024-02-01 23:04
Bump on the Q @dukenv0307!

**Comment by abdulrahuman5196** [comment] 2024-02-05 13:49
@dukenv0307 Gentle remainder

**Comment by trjExpensify** [comment] 2024-02-08 10:46
Sweet! @abdulrahuman5196, over to you!

**Comment by abdulrahuman5196** [comment] 2024-02-12 06:14
Will review today. Thank you

**Comment by trjExpensify** [comment] 2024-02-14 02:29
@abdulrahuman5196 how did the review go?

**Comment by abdulrahuman5196** [comment] 2024-02-14 09:37
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-02-14 09:53
@trjExpensify I think @dukenv0307 proposal is good at the moment. 

@trjExpensify I wanted to confirm on one question from the UI here - https://github.com/Expensify/App/issues/26424#issuecomment-1776979331

What if the user had 100s of request not loaded? Showing box skeleton for all those requests doesn't seem good. Should we limit the number of box skeletons shown?

If we have the max number for the box skeletons to show, i am good with approving the proposal and start on the PR.

**Comment by trjExpensify** [comment] 2024-02-14 12:14
Yeah, I think @mountiny and I talked [here](https://github.com/Expensify/App/issues/26424#issuecomment-1790937422) about just using the `1` to address the performance concern, right?

**Comment by mountiny** [comment] 2024-02-14 13:13
yep I think 1 is good to just fulfill the UX need of this

**Comment by abdulrahuman5196** [comment] 2024-02-15 08:50
Thank you for the response. @dukenv0307 's proposal here https://github.com/Expensify/App/issues/26424#issuecomment-1799262109 looks good. 

🎀 👀 🎀
C+ Reviewed

**Comment by trjExpensify** [comment] 2024-02-27 12:31
PR in active review.

**Comment by mountiny** [comment] 2024-04-02 11:30
$500 to @dukenv0307 and to @abdulrahuman5196

**Comment by trjExpensify** [comment] 2024-04-10 14:43
👋 checklist time please, @abdulrahuman5196! 

In the meantime, payment summary will be as follows: 

- $500 to @abdulrahuman5196 for the C+ review
- $500 to @dukenv0307 for the fix

**Comment by abdulrahuman5196** [comment] 2024-04-12 15:34
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Create some money requests in a chat
2. Open the IOU report and send some messages
3. Open another report and send a message
4. Logout and login again with the same account
5. Without opening any other report, go offline
6. Open IOU report that we created above
7.  Verify that the total is displayed and at least one money request appears

@trjExpensify Added checklist. And I am still getting paid via upwork. Kindly process on the same.

**Comment by trjExpensify** [comment] 2024-04-16 00:19
Paid you both! Closing!

**Closed by trjExpensify** 2024-04-16 00:19 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
