### ISSUE TITLE
[$1000] Cursor is barely visible on the next line after pressing 'Enter' in task description while creating it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21449] opened 2023-06-23 19:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into an account that can assign tasks (tasks are still in beta, so this'll need to be done in DEV).
2. Open a report (create one if it doesn't exist), and click the '+' sign in the composer.
3. Choose the 'Assign task' option.
4. Add some text in the 'Description' field and then press 'Enter'.

## Expected Result:
When you press Enter to create a new line in the task description field, the input area should automatically expand to show the full cursor on the next line.

## Actual Result: 
When you press Enter to create a new line, the input area does not auto adjust to the next line until the user starts typing characters on the new line.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.31-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/77319c08-45c4-43cd-aa6c-a15a2534bc41

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687008611679269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6185cdf31429363</li>
        <li>Upwork Job ID: 1674513944297259008</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by Nathan-Mulugeta** [comment] 2023-06-23 20:43
This is a dupe of this [issue](https://expensify.slack.com/archives/C049HHMV9SM/p1686812220519569
)

**Comment by sakluger** [comment] 2023-06-26 22:11
This issue is stemming from [this issue](https://github.com/Expensify/App/issues/19135) - I left a comment over there.

**Comment by sakluger** [comment] 2023-06-29 20:23
Okay this is a new issue, adding external label.

**Comment by Nathan-Mulugeta** [comment] 2023-06-30 04:46
Isn't that in task description page @chiragxarora

**Comment by sakluger** [comment] 2023-07-05 18:23
I agree that this is the same root cause and that we should have a global solution. I'm going to close this issue in favor of https://github.com/Expensify/App/issues/21271, and recommend over there that we create one global solution.

**Closed by sakluger** 2023-07-05 18:23 UTC
Labels: External, Daily, Help Wanted, Bug
