### ISSUE TITLE
[$1000] Request money - '1 Reply' is not shown when money request report is created in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24129] opened 2023-08-03 19:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Click + button > Request moneybags
3. Complete the request money process
4. Repeat Step 2 and 3 in offline modeling 

## Expected Result:
After money request is created in offline mode, the IOU preview will show '1 Reply'

## Actual Result:
After money request is created in offline mode, the IOU preview does not show '1 Reply'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a665776e-db75-4dab-9f64-208927fe009b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017562e6ccd02ef924</li>
        <li>Upwork Job ID: 1691103716394532864</li>
        <li>Last Price Increase: 2023-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>samh-nl | Contributor | 26259731</li>
</ul></li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2023-08-04 19:06
@lanitochka17 mind confirming, we currently see the requests incomplete, which is correct given we're in offline mode. What's the error here? Apologies if I'm missing it!

**Comment by dylanexpensify** [comment] 2023-08-08 08:04
Reviewing this today to post update!

**Comment by dylanexpensify** [comment] 2023-08-10 11:02
Got it, so @dukenv0307 we want to _not_ have the parent report action updated?

**Comment by dylanexpensify** [comment] 2023-08-11 19:53
Didn't get an update today, will on Monday!

**Comment by dylanexpensify** [comment] 2023-08-14 08:18
Reviewing today!

**Comment by dylanexpensify** [comment] 2023-08-14 08:18
Reviewing today!

**Comment by dylanexpensify** [comment] 2023-08-14 14:54
@luacmartins confirmed correct behavior, is a bug! Going to repro now then mark external if all good

**Comment by mananjadhav** [comment] 2023-08-16 04:56
I'll review this today.

**Comment by dylanexpensify** [comment] 2023-08-16 13:43
TY!

**Comment by dylanexpensify** [comment] 2023-08-17 09:39
@mananjadhav mind posting your findings on review today?

**Comment by mananjadhav** [comment] 2023-08-17 15:39
I did review the proposals. Both of them have the correct RCA, and both the solutions work. I will shortlist one of them by EOD/tomorrow morning. Need to implement and test.

**Comment by mananjadhav** [comment] 2023-08-18 16:40
But isn't it because we don't have the optimistic data?

**Comment by mananjadhav** [comment] 2023-08-18 16:48
Thanks considering the RCA and that we've identified multiple properties in this [proposal](https://github.com/Expensify/App/issues/24129#issuecomment-1664669980). I think we are good to use @samh-nl's proposal.

**Comment by mananjadhav** [comment] 2023-08-18 16:48
Thanks considering the RCA and that we've identified multiple properties in this [proposal](https://github.com/Expensify/App/issues/24129#issuecomment-1664669980). I think we are good to use @samh-nl's proposal.

🎀 👀 🎀 C+ reviewed.

**Comment by mananjadhav** [comment] 2023-08-19 18:02
@dukenv0307 This was a tough one for me. As I've mentioned both the proposals had the correct RCA, but both of them weren't completely correct. Considering, that both needed code changes in the PR I decided to use @samh-nl's proposal.

My focus was less on the split bill request.  It's good to fix it, but not the deciding factor. Hope it clarifies my thought process. Rest I'll let @deetergp decide.

**Comment by dylanexpensify** [comment] 2023-08-22 10:05
reviewing

**Comment by mananjadhav** [comment] 2023-08-22 10:51
I did @dukenv0307.  Thanks for the bump. @dylanexpensify I was waiting for @deetergp to go over the conversation before hiring @samh-nl here.

@deetergp Could you please look at the proposals/comments?

**Comment by dylanexpensify** [comment] 2023-08-22 21:05
Apologies - pending Scott review

**Comment by dylanexpensify** [comment] 2023-08-24 10:39
@deetergp can you dig into this today 🙇

**Comment by deetergp** [comment] 2023-08-24 21:29
Thanks for your patience folks, sorry took me this long to get around to looking at this. As I understand it: @samh-nl's proposal was first and correct about needing to update all the fields and @dukenv0307 wouldn't have worked without increasing the number of updated fields, similar to the prior proposal but will handle the (plausible) edge case where an additional money request is sent and the thread count will increase. @samh-nl's proposal would not. Do I have that correct @mananjadhav?

**Comment by mountiny** [comment] 2023-08-25 12:11
I will ask

**Comment by mountiny** [comment] 2023-08-25 13:32
I think there is a new design and we are only showing the comments

**Comment by dylanexpensify** [comment] 2023-08-25 17:49
@mountiny mind recapping where we landed here?

**Comment by deetergp** [comment] 2023-08-25 23:08
These all count as system messages and shouldn't increment the thread count? If that's the case than I agree that this should be closed.

**Comment by dylanexpensify** [comment] 2023-08-28 11:11
updating today!

**Comment by mountiny** [comment] 2023-08-28 16:20
Yep only ADDCOMMENT should be counted so we can close this

**Closed by mountiny** 2023-08-28 16:20 UTC
Labels: External, Engineering, Daily, Bug
