### ISSUE TITLE
[$500] Assigned cards have the bank name only without last 4 digits of card number

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36869] opened 2024-02-20 11:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/35885

**Version Number:** 1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** tester+021924pr@applausecard.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Assign a third party card feed to a test account in OldDot following these steps:
2. Navigate to Settings > Domains > Import Card to add the test card feed
3. Search ‘Discover’
4. Enter the login ‘expensifydemo’ and the password ‘#USD’
5. Assign the single available card to your test account
6. Navigate to NewDot and go to your Wallet > Assigned cards
7. Verify "bankName - lastFourDigits" shown for each card in Assigned cards menu

## Expected Result:
"bankName - lastFourDigits" shown for each card in Assigned cards menu

## Actual Result:
Assigned cards have the bank name only without last 4 digits of card number

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/bbe2a79f-4367-4ee4-8815-3fb6e3db4a26

https://github.com/Expensify/App/assets/115492554/2dfc5186-9f02-4482-97f8-904f2e6355b3

https://github.com/Expensify/App/assets/115492554/984f855d-5188-4105-906c-50670f304071

https://github.com/Expensify/App/assets/115492554/9fcf6966-88d3-4783-b436-546d1f61dcda

https://github.com/Expensify/App/assets/115492554/ffdbcf28-38fe-4558-8577-83dff2db5222

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016608e25454a96698</li>
        <li>Upwork Job ID: 1759902287781416960</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-20 11:25
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by youssef-lr** [comment] 2024-02-20 11:36
@izarutskaya is this reproducible in production? If yes then we can remove the blocker.

**Comment by youssef-lr** [comment] 2024-02-20 18:44
Thanks @GandalfGwaihir! I've let the contributor know.

**Comment by chiragsalian** [comment] 2024-02-21 19:28
I'm unsure why deploy blocker label was removed here. The issue description says its not reproducible on production so i am re-adding the label. If i am mistaken feel free to correct me.

Also adding back external label since it looks like it can be tackled by contributors.

**Comment by godofoutcasts94** [comment] 2024-02-21 20:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Assigned cards have the bank name only without last 4 digits of card number
### What is the root cause of that problem?
The root cause here is that firstly it is coming from the regression of this PR -  [#35885](https://github.com/Expensify/App/pull/35885), we are passing `card.bank`.

https://github.com/Expensify/App/blob/3da8aa3e100214b3cd60de3ff735797b4dcd6ec1/src/pages/settings/Wallet/PaymentMethodList.tsx#L212

### What changes do you think we should make in order to solve the problem?


To resolve this issue, we must pass `card.cardName` instead, this will resolve the issue completely. 

### Result

<img width="1470" alt="Screenshot 2024-02-22 at 1 34 33 AM" src="https://github.com/Expensify/App/assets/158435970/ba40af31-f328-4bef-8a9d-4652424e853d">

### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment] 2024-02-21 20:48
One more thing that I have discovered from the API calls is that, `lastFourPAN` is always empty. That's why I believe it is not possible to display bankName along with lastFourPAN 

<img width="743" alt="Screenshot 2024-02-22 at 2 16 30 AM" src="https://github.com/Expensify/App/assets/158435970/1f25f566-7ff3-463b-acbf-d8118161a348">

**Comment by godofoutcasts94** [comment] 2024-02-21 21:29
updated [Proposal](https://github.com/Expensify/App/issues/36869#issuecomment-1957811947)

**Comment by rushatgabhane** [comment] 2024-02-22 04:59
discussion here https://expensify.slack.com/archives/C01GTK53T8Q/p1708558924151619

**Comment by marcochavezf** [comment] 2024-02-23 02:30
Created a PR to always send the `lastFourPAN` from the backend

**Comment by rushatgabhane** [comment] 2024-02-23 06:42
Thanks a lot @marcochavezf 🙇

**Comment by rushatgabhane** [comment] 2024-02-23 11:24
it's backend only mostly @ntdiary

**Comment by marcochavezf** [comment] 2024-02-23 19:16
This has been addressed in a [backend](https://github.com/Expensify/Auth/pull/10011) fix. Removing the deploy blocker since. @izarutskaya we can check it off since it's not testable now

**Comment by MitchExpensify** [comment] 2024-02-26 23:42
This looks like an improvement but I'm not sure this fits into a wave or VIP 

<img width="731" alt="image" src="https://github.com/Expensify/App/assets/36425901/332ec343-6168-4708-93f8-d80107617049">

**Comment by godofoutcasts94** [comment] 2024-02-27 16:03
Hey @MitchExpensify is this issue still open? Can you please review my [proposal](https://github.com/Expensify/App/issues/36869#issuecomment-1957811947)?

**Comment by youssef-lr** [comment] 2024-02-28 02:21
@marcochavezf we can close this right?

**Comment by youssef-lr** [comment] 2024-02-29 04:52
Nice thanks.

**Comment by youssef-lr** [comment] 2024-02-29 04:53
Assigning you for points :D

**Closed** 2024-02-29 04:53 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
