### ISSUE TITLE
mWeb - When entering sms code via autoForwarded  code From messages, all the digits appear on the 1st dash

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21077] opened 2023-06-19 19:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1Open app with Mobile safari
2 Enter number or email
3 Press to code which came from Messages
## Expected Result: 
6 digit should be entered to 6  lines
## Actual Result: 
For the first line 6 code entered
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** needs reproduction (don't  have iphone with sim card)
**Reproducible in production?:** needs reproduction (don't  have iphone with sim card)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![photo_2023-06-19 12 51 24](https://github.com/Expensify/App/assets/43996225/0296109c-b12e-4a7a-be5d-bfd4c786aa0e)

https://github.com/Expensify/App/assets/43996225/68c2f2bb-100a-4369-b159-0a154485e24c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @narzullome
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686581162989309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment] 2023-06-19 19:57
dupe of https://github.com/Expensify/App/issues/20642

**Closed** 2023-06-20 07:34 UTC
Labels: Daily, Needs Reproduction, Bug
