### ISSUE TITLE
[$250]  Tax - Different tax rate on confirmation page & transaction thread when tax rate is disabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46734] opened 2024-08-02 15:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4808605
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has a few tax rates
- Workspace currency default and Foreign currency default have different tax rate
1. Go to staging.new.expensify.com
2. Go to workspace settings > Taxes
3. Disable the tax rate for Foreign currency default
4. Go to workspace chat
5. Go to + > Split expense
6. Enter amount and select a foreign currency
7. Proceed to confirmation page
8. Note that the tax rate is Foreign currency default even though it is already disabled
9. Split the expense
10. Open the split preview and also transaction thread
11. Note that the tax rate changes to Workspace currency default

## Expected Result:
In Step 8. the tax rate on confirmation page when foreign currency is used should be consistent with the tax rate on split preview and transaction thread (Step 11)

## Actual Result:
In Step 8. the tax rate on confirmation page when foreign currency shows the tax rate for Foreign currency default even though it is already disabled
In Step 11, after splitting the expense, the tax rate changes to Workspace currency default which is not consistent with the rate shown on the confirmation page before splitting

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/52705480-0019-498c-87da-54864ce51376

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b83b7675405b2d3</li>
        <li>Upwork Job ID: 1820469144458744658</li>
        <li>Last Price Increase: 2024-08-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by lanitochka17** [comment] 2024-08-02 15:50
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-08-02 19:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Different tax rate on confirmation page & transaction thread when tax rate is disabled

### What is the root cause of that problem?
We are displaying the foreign default if the policy currency and transaction policy are not the same without check if the foreign default is not disabled in the first place
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/libs/TransactionUtils.ts#L760-L768
But the BE checks that it is disabled and it will default it to the default tax
### What changes do you think we should make in order to solve the problem?

We need to check if the foreign tax is disabled and if it is we should set it to `defaultExternalID`
```
  const defaultExternalID = policy?.taxRates?.defaultExternalID;
    const foreignTaxDefault = policy?.taxRates?.foreignTaxDefault;
    const taxes = policy?.taxRates?.taxes;
    const isForeignDefaultDisabled = taxes?.[foreignTaxDefault ?? '']?.isDisabled;

    return policy?.outputCurrency === (currency ?? getCurrency(transaction)) || isForeignDefaultDisabled ? defaultExternalID : foreignTaxDefault;
}
```

### What alternative solutions did you explore? (Optional)

**Comment by isabelastisser** [comment] 2024-08-08 20:43
@eVoloshchak can you please review the proposals? Thanks!

**Comment by trjExpensify** [comment] 2024-08-09 21:52
CC: @luacmartins @MonilBhavsar for vis!

**Comment by luacmartins** [comment] 2024-08-12 10:15
@MonilBhavsar would you be able to take a look at this since you're more familiar with the tax udf?

**Comment by luacmartins** [comment] 2024-08-14 13:51
Closing as per the comments above.

**Closed by luacmartins** 2024-08-14 13:51 UTC
Labels: External, Daily, Help Wanted, Bug
