### ISSUE TITLE
Web - React navigation leads to unintended NavigationRoot rerender

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25716] opened 2023-08-22 20:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open settings
2. Create a navigation history e.g. Settings -> Workspaces -> Select workspace
3. Go back with browser navigation
4. Go forward
5. Notice that the last forward movement and any other movement after that re-renders the `<NavigationRoot />` component.

## Expected Result:
Navigation should work normally, without re-rendering `<NavigationRoot />`.

## Actual Result:
`<NavigationRoot />` is being re-rendered. This leads to inefficiencies (e.g. OpenReport API request is made after every navigation) and bad user experience e.g. navigation animation is not displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/6c367614-6b15-43d4-ba04-4c2079a4ff6d

https://github.com/Expensify/App/assets/115492554/07e33307-f091-4e8a-9bb0-673bde33cd24

![Screenshot 2023-08-22 224513](https://github.com/Expensify/App/assets/115492554/6e95d39f-6386-4ba3-8ae1-58add22a7cd2)

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @pbkompasz

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691681242411159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d38b5a743c55ae38</li>
        <li>Upwork Job ID: 1696166379404009472</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2023-08-22 21:11
reviewing tomorrow!

**Comment by dylanexpensify** [comment] 2023-08-24 11:01
actioning today!

**Comment by dylanexpensify** [comment] 2023-08-25 17:38
clarifying if bug or polish [internally](https://expensify.slack.com/archives/C03U7DCU4/p1692985085685289)

**Comment by dylanexpensify** [comment] 2023-08-28 11:09
updating today!

**Comment by dylanexpensify** [comment] 2023-08-28 11:10
updating today!

**Comment by mountiny** [comment] 2023-08-28 14:22
I will take this one on as Weekly and ask @adamgrzybowski @WoLewicki to look into this

**Comment by adamgrzybowski** [comment] 2023-08-28 15:06
@izarutskaya  Didn't the browser reload somewhere along the way? I can't reproduce this bug without this.

**Comment by mountiny** [comment] 2023-08-28 15:09
@pbkompasz as the reporter

**Comment by mountiny** [comment] 2023-08-28 15:52
Hopefully, lets wait for @pbkompasz is they can provide any help with reproduction, otherwise we can close

**Comment by mountiny** [comment] 2023-08-31 05:22
I think we can close this one now

**Closed by mountiny** 2023-08-31 05:22 UTC
Labels: Weekly, Internal, Bug
