### ISSUE TITLE
[$500] Attachment - 'New message' button appears when deleting attachment

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39421] opened 2024-04-02 16:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4468722
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to a report has multiple chat
2. Send attachment
3. Delete the attachment
4. Click on 'New messages' button

## Expected Result:
'New messages' button shouldn't appear, and attachment should remain deleted

## Actual Result:
'New messages' button appears, and attachment reappear when clicking 'New messages' button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6830f6a6-bef6-4715-bdaf-8fde3bd6ceb7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010fcec62910c073e7</li>
        <li>Upwork Job ID: 1775234083431460864</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>c3024 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-02 16:24
@garrettmknight I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-02 16:24
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-04-02 16:25
Production 


https://github.com/Expensify/App/assets/115492554/ac5be676-7aac-43b6-8b72-31c8abac07ba

**Comment by deetergp** [comment] 2024-04-02 18:38
I was able to reproduce this locally. Also navigating away from the chat back will cause the supposedly deleted attachment to reappear.

**Comment by garrettmknight** [comment] 2024-04-02 18:49
Rerpo'd it as well. I think this could be `External` so I'll start there.

**Comment by jasperhuangg** [comment] 2024-04-03 19:28
I just reproduced this on prod so it doesn't need to be a blocker

**Comment by jjcoffee** [comment] 2024-04-05 15:05
Reviewing Monday!

**Comment by jjcoffee** [comment] 2024-04-08 17:36
Apologies I had higher priority work to get to today, will get back to this tomorrow! :bow:

**Comment by jjcoffee** [comment] 2024-04-09 08:14
@kaushiktd Thanks for your [proposal](https://github.com/Expensify/App/issues/39421#issuecomment-2039495535)! It's lacking somewhat in details, however. Could I ask you to expand on where the code changes in your solution would go, as well as more detail in your RCA, i.e. what "deletion logic" are you referring to?

**Comment by kaushiktd** [comment] 2024-04-09 08:47
in this file change in  function deleteReportComment()
https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/libs/actions/Report.ts#L1122

i introduce a new variable hasChildReport to identify if a report action has a child report.
add here
https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/libs/actions/Report.ts#L1129

`const hasChildReport = reportAction.childReportID !== null && reportAction.childReportID !== undefined;`

and also
Adjust the condition for deletion in the deleteReportComment function to consider both cases: whether the report action is a parent action of a thread or if it lacks a child report.
https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/libs/actions/Report.ts#L1242
```
const conflictingCommands = (
    (!hasChildReport || isDeletedParentAction)
        ? [WRITE_COMMANDS.UPDATE_COMMENT]
        : [WRITE_COMMANDS.ADD_COMMENT, WRITE_COMMANDS.ADD_ATTACHMENT, WRITE_COMMANDS.UPDATE_COMMENT, WRITE_COMMANDS.DELETE_COMMENT]
) as string[];
```
This modification ensures that the report action will be deleted if it's a parent action of a thread or if it lacks a child report.

**Comment by jjcoffee** [comment] 2024-04-09 09:26
@kaushiktd Sorry, the RCA is still unclear here. Can you update your proposal with a detailed RCA that explains what the issue with `conflictingCommands` as implemented is?

**Comment by jjcoffee** [comment] 2024-04-09 10:04
@kaushiktd `conflictingCommands` was introduced in https://github.com/Expensify/App/pull/39024 to deal with conflicting requests, so it's not a condition for deletion, per se. It _is_ clear that there's an issue with it, but I'm not convinced that you understand what your change does or why it works, because you've not identified a clear RCA here. We do require this clarity of RCA and a clear link to the solution in proposals, so that we can be sure the fix is not just a workaround.

**Comment by bernhardoj** [comment] 2024-04-09 14:56
Maybe related to https://github.com/Expensify/App/issues/39432

**Comment by jjcoffee** [comment] 2024-04-09 15:05
Cheers for the heads up @bernhardoj! It does look very likely that your PR will resolve this issue, so @deetergp can we HOLD this issue for https://github.com/Expensify/App/issues/39432?

**Comment by garrettmknight** [comment] 2024-04-22 17:41
Other issue is deployed, moving to daily to test in the morning.

**Comment by garrettmknight** [comment] 2024-04-23 12:03
I was able to repro this issue. Opening up for help.

**Comment by jjcoffee** [comment] 2024-04-23 12:42
Pinging @bernhardoj and @kaushiktd in case you want to update/add proposals based on the latest changes.

**Comment by kaushiktd** [comment] 2024-04-23 13:54
### Please re-state the problem that we are trying to solve in this issue.
Attachment - 'New message' button appears when deleting attachment

### What is the root cause of that problem?
NewMessage popup appear when we delete the attachment

### What changes do you think we should make in order to solve the problem?
to solve this problem change here
https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/pages/home/report/ReportActionsList.tsx#L614

`const canScrollToNewerComments = isLoadingInitialReportActions && hasNewestReportAction && sortedReportActions.length > 25 && isLastPendingActionIsDelete;`

This condition will allow the new message popup to appear only when the following conditions are met:

- The initial report actions are still loading (isLoadingInitialReportActions).
- There is a newest report action available (hasNewestReportAction).
- The number of sorted report actions is greater than 25 (sortedReportActions.length > 25).
- The last pending action is a deletion (isLastPendingActionIsDelete).

video:-https://drive.google.com/file/d/1dBX9XXeHCps6-OU2qmPJvhpcDts-9p5j/view?usp=sharing

**Comment by kaushiktd** [comment] 2024-04-23 13:55
@jjcoffee i updated my proposal

**Comment by jjcoffee** [comment] 2024-04-24 15:43
Will try to review tomorrow!

**Comment by jjcoffee** [comment] 2024-04-25 15:05
Hmm I'm not able to repro on latest staging. @kaushiktd or @garrettmknight were there any special steps other than those in the issue description?

**Comment by kaushiktd** [comment] 2024-04-25 15:46
@jjcoffee When you delete an attachment, it will no longer reappear. This is a solved issue. However, a new message box still pops up. I have updated my proposal to address this problem.

**Comment by jjcoffee** [comment] 2024-04-26 07:45
@kaushiktd Hmm I'm not seeing that on latest staging. What version of the app are you seeing this behaviour on?

**Comment by kaushiktd** [comment] 2024-04-26 08:28
@jjcoffee 
"name": "new.expensify",
  "version": "1.4.65-5",

I'm checking in 66 version

**Comment by jjcoffee** [comment] 2024-04-29 09:47
@kaushiktd Thanks for retesting! I've managed to reproduce; it seems like it's a requirement to fill the chat with a certain number of messages before it is triggered.

Your [proposal](https://github.com/Expensify/App/issues/39421#issuecomment-2039495535) is lacking in detail. Can you please explain the root cause and how/why the solution handles it? Thanks!

**Comment by kaushiktd** [comment] 2024-04-29 11:28
@jjcoffee  please have a look

### Root Cause Analysis:

The root cause of the issue lies in the incorrect evaluation of the canScrollToNewerComments variable, which determines whether the "scroll to newer comments" button should be displayed. Currently, the condition used to calculate this variable includes checks for isLoadingInitialReportActions, hasNewestReportAction, and isLastPendingActionIsDelete. However, due to the use of the logical NOT operator (!) in front of isLoadingInitialReportActions, hasNewestReportAction, and isLastPendingActionIsDelete, the variable canScrollToNewerComments ends up being true when it should not be.

### Proposed Solution:

To address this issue and ensure that the "scroll to newer comments" button is displayed only when necessary, we need to adjust the condition used to calculate the canScrollToNewerComments variable. Instead of using the logical NOT operator, we should directly evaluate the conditions based on their intended behavior.

We can achieve this by updating the condition to the following:


`const canScrollToNewerComments = isLoadingInitialReportActions && hasNewestReportAction && sortedReportActions.length > 25 && isLastPendingActionIsDelete;`

With this change, the canScrollToNewerComments variable will only be true when all conditions are met, including being in the initial loading state, having a newest report action, having more than 25 sorted report actions, and the last pending action not being a delete action.

By accurately evaluating these conditions, we ensure that the "scroll to newer comments" button is displayed appropriately, addressing the issue and providing the expected behavior for users.

**Comment by jjcoffee** [comment] 2024-04-29 11:59
@kaushiktd Thanks, could you explain though what condition (or combination) is causing the button to display in this particular case? I think it would be reckless to flip the logic on _all_ the conditions without understanding why :smile:

**Comment by kaushiktd** [comment] 2024-04-29 12:45
@jjcoffee 

canScrollToNewerComments: This variable determines whether the "scroll to newer comments" button should be displayed. It evaluates to true if the following conditions are met:

- isLoadingInitialReportActions: Indicates whether the report actions are still loading initially.
- hasNewestReportAction: Indicates whether there is a newest report action available.
- sortedReportActions.length > 25: Ensures that there are more than 25 sorted report actions in the list.
- isLastPendingActionIsDelete: Indicates whether the last pending action is a delete action.
The proposed fix adjusts the canScrollToNewerComments variable to ensure that it evaluates to false when it should not override the other conditions. By modifying the condition to include the correct logic without the use of the logical NOT operator, we ensure that the button is displayed only when necessary.

By accurately evaluating the conditions and addressing the root cause of the issue, we ensure that the button displays correctly in all relevant scenarios

**Comment by jjcoffee** [comment] 2024-04-29 13:48
@kaushiktd Flipping the conditions will likely break the expected behaviour from the comment above the code you're proposing to change:

https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/pages/home/report/ReportActionsList.tsx#L612-L614

**Comment by jjcoffee** [comment] 2024-04-29 13:48
Friendly bump @bernhardoj in case you're available and want to take a look at this, since you worked on a related PR recently.

**Comment by kaushiktd** [comment] 2024-04-29 14:49
> @kaushiktd Flipping the conditions will likely break the expected behaviour from the comment above the code you're proposing to change:
> 
> https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/pages/home/report/ReportActionsList.tsx#L612-L614

@jjcoffee As I've mentioned in my last response, by evacuating the conditions the behaviour is expected and will not break.🙂 Still if there is a way for you to test it, I'd love to see the results because it is working as expected for me.

**Comment by jjcoffee** [comment] 2024-05-01 09:52
@kaushiktd My problem with your [proposal](https://github.com/Expensify/App/issues/39421#issuecomment-2039495535) as it stands is that it lacks a clear RCA and the explanatory link to the solution, i.e. why does it work. If you can explain how flipping the `isLoadingInitialReportActions` and `hasNewestReportAction` conditions won't break the comment linking functionality, that would help. 

In the meantime open to new proposals!

**Comment by brunovjk** [comment] 2024-05-01 10:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After deleting an attachment in a report conversation, the "New Messages" button incorrectly appears, indicating unread messages when there are none.

### What is the root cause of that problem?
- The root cause appears to be the incorrect calculation of the `canScrollToNewerComments` variable. This variable determines the visibility of the "New Messages" button.
- Currently, the negation of certain conditions (`!isLoadingInitialReportActions`,`!hasNewestReportAction`) inadvertently trigger the button's display, even when there shouldn't be unread messages.

### What changes do you think we should make in order to solve the problem?
- Modify the `canScrollToNewerComments` condition:  Replace negation with direct evaluation of the intended conditions:
```
const canScrollToNewerComments = isLoadingInitialReportActions && hasNewestReportAction && sortedReportActions.length > 25 && isLastPendingActionIsDelete;
```
Evaluate if `canScrollToNewerComments` is the most appropriate variable to control the "New Messages" button in all scenarios. There might be a need to introduce a dedicated unread message tracking variable for better accuracy.

- By requiring that `isLoadingInitialReportActions`, `hasNewestReportAction`, and `isLastPendingActionIsDelete` are all simultaneously `true`, we limit display of the button to its intended context—initial loading, the existence of new actions, and sufficient report length.
- Removing negation helps prevent situations where attachment deletion updates unintentionally cause the button to appear.

### What alternative solutions did you explore? (Optional)
Considered creating a more explicit variable named `hasUnreadMessages`. This could provide more reliable tracking and decouple the button's visibility logic.

**Comment by kaushiktd** [comment] 2024-05-01 10:41
@jjcoffee  [proposal updated](https://github.com/Expensify/App/issues/39421#issuecomment-2039495535)

**Comment by c3024** [comment] 2024-05-01 10:45
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
'New messages' floating button appears when the latest message is deleted after crossing a threshold.
### What is the root cause of that problem?
We show the floating message counter when `hasNewestReportAction` is `false` among other things here
https://github.com/Expensify/App/blob/573d9893ae2a8e6e4ebe64088cb2fbf62ce81804/src/pages/home/report/ReportActionsList.tsx#L616-L622
but `hasNewestReportAction` here compares the latest sortedReportAction 
https://github.com/Expensify/App/blob/573d9893ae2a8e6e4ebe64088cb2fbf62ce81804/src/pages/home/report/ReportActionsList.tsx#L203
but latest sortedReportActions include deleted actions and the check fails even though we are already at the latest message and the floating button appears
### What changes do you think we should make in order to solve the problem?
Change the check above to use `sortedVisibleReportActions?.[0].created`
### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment] 2024-05-02 12:58
The approach in @c3024's [proposal](https://github.com/Expensify/App/issues/39421#issuecomment-2088278276) LGTM! It also explains why the scroll button appears after a short delay; `report.lastVisibleActionCreated` is populated once the BE request completes. We have to make sure that any changes to `hasNewestReportAction` don't have knock-on effects, or maybe introduce a new `hasNewestVisibleReportAction` to be safe :smile: 

I don't think we want to rework the whole way this feature works, as @dragnoir [suggests](https://github.com/Expensify/App/issues/39421#issuecomment-2088290949).

@kaushiktd's [proposal](https://github.com/Expensify/App/issues/39421#issuecomment-2039495535) lacks the detail for me to fully analyse it. I strongly doubt it's a workable fix.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment] 2024-05-03 07:49
> Looks like the selected solution is the same as in my PR [here](https://github.com/Expensify/App/pull/41482)

@bernhardoj Thanks for the heads up! Hmm I'm not sure what we'd normally do in this situation. This issue is older so it would normally take precedence, but the [other issue](https://github.com/Expensify/App/issues/40768) is also not a straight dupe of this one...

**Comment by jjcoffee** [comment] 2024-05-03 14:45
Just a heads up I'll be OOO 6-13th (I may have some time on the 6th), so this may need to be reassigned depending on what is decided to do here. cc @garrettmknight

**Comment by kaushiktd** [comment] 2024-05-06 04:06
@garrettmknight I pulled latest code and this issue appears to be fixed!

**Comment by deetergp** [comment] 2024-05-07 03:35
I asked for a re-test here https://expensify.slack.com/archives/C9YU7BX5M/p1715052903386669

**Comment by kavimuru** [comment] 2024-05-07 14:26
Issue is fixed. 

https://github.com/Expensify/App/assets/43996225/c07e6d4a-393c-4371-9093-fa04fad8e74a

**Comment by deetergp** [comment] 2024-05-08 14:50
Is there anything we need to do before closing this one @garrettmknight?

**Comment by garrettmknight** [comment] 2024-05-09 18:33
Just reviewing - doesn't look like we got a PR up or anything so I'm going to just close since this was fixed elsewhere.

**Closed by garrettmknight** 2024-05-09 18:33 UTC
Labels: External, Engineering, Daily, Bug
