### ISSUE TITLE
[$500] Scan - Expense report and transaction report are no longer hidden in LHN when scanning fails

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37296] opened 2024-02-27 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Create a scan request with an invalid receipt that will fail the scanning.
4. Wait for the request to fail.

## Expected Result:
Workspace expense report and transaction report will be hidden in LHN when the scanning fails. (production behavior)

## Actual Result:
Workspace expense report and transaction report appear in LHN when the scanning fails.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e54abee0-197c-46ac-a4d1-97d3c1482913

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b135358baed37a2</li>
        <li>Upwork Job ID: 1762481990262865920</li>
        <li>Last Price Increase: 2024-03-26</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-27 14:17
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by danieldoglas** [comment] 2024-02-27 16:28
Removing the deploy blocker and waiting for QA team to confirm if this was intended or not based on the changes

**Comment by DylanDylann** [comment] 2024-03-01 06:36
@danieldoglas Could you help ping the QA team to verify this issue?

**Comment by danieldoglas** [comment] 2024-03-04 12:08
Added label to retest

**Comment by danieldoglas** [comment] 2024-03-04 16:16
cc @kbecciv

**Comment by kbecciv** [comment] 2024-03-05 17:31
@danieldoglas Issue is reproducible on build 1.4.47.0

https://github.com/Expensify/App/assets/93399543/6a1f5582-44a4-4386-bbd6-b97fc77904e9

**Comment by DylanDylann** [comment] 2024-03-07 09:11
@tienifr Why the detail transaction report is hidden if we click on it and then click on another report?

https://github.com/Expensify/App/assets/141406735/41624002-cd62-4b81-b76b-c91884c25779

**Comment by DylanDylann** [comment] 2024-03-13 10:23
@tienifr Thanks for your update. I prefer your alternative solution but please help to detail more instead of 
> We can migrate the logic to hide option [here](https://github.com/Expensify/App/blob/86a990428df2c923ed4ebc291c0a3a73653cb7fe/src/components/LHNOptionsList/OptionRowLHN.tsx#L61) to shouldHideReport function

**Comment by mvtglobally** [comment] 2024-03-15 03:12
Issue is reproducible during KI retests.

**Comment by roryabraham** [comment] 2024-03-20 17:26
@tienifr bump to add a bit more detail to your proposal

**Comment by danieldoglas** [comment] 2024-03-20 17:47
Again, I'm confused if this is not exactly what is expected. Based [on this](https://github.com/Expensify/Auth/pull/8693/files), we actually add a reportAction on that thread. Considering that the thread is shared with who created the reportAction, it makes sense to me that this is shown in the LHN.

@roryabraham do you disagree?

**Comment by DylanDylann** [comment] 2024-03-22 03:25
It seems this issue is fixed [here](https://github.com/Expensify/App/pull/38656)

**Comment by DylanDylann** [comment] 2024-03-22 09:07
@danieldoglas We can close this one or please add re-test label to make sure this bug isn't reproduced anymore

**Comment by mvtglobally** [comment] 2024-03-28 04:33
Issue is reproducible during KI retests.

Workspace expense report and transaction report does not appear at first when the scanning fails but once user clicks on the IOU preview component to open the expense report the transaction report also shows up on LHN.

https://github.com/Expensify/App/assets/43995119/d6b7b1a9-6a03-44a0-93b1-66f49f7a6f2f

**Comment by DylanDylann** [comment] 2024-04-01 09:30
I also can reproduce this bug. Sorry for my mistake [here](https://github.com/Expensify/App/issues/37296#issuecomment-2014279421). Waiting for proposal

**Comment by DylanDylann** [comment] 2024-04-01 09:50
@tienifr [This PR](https://github.com/Expensify/App/pull/38656) moved the logic that caused this bug to `getOrderedReportIDs` function and **didn't fix this bug**. I checked again and saw that your proposal still be valid. Solution 1 in your proposal looks good to me. Please update the proposal to point out the correct place that caused this bug

**Comment by DylanDylann** [comment] 2024-04-01 10:25
> @tienifr https://github.com/Expensify/App/pull/38656 moved the logic that caused this bug to getOrderedReportIDs function and didn't fix this bug. I checked again and saw that your proposal still be valid. Solution 1 in your proposal looks good to me. Please update the proposal to point out the correct place that caused this bug

As mentioned above. @tienifr's proposal looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-04-29 16:32
@danieldoglas Could you help to handle the payment for this issue?

**Comment by danieldoglas** [comment] 2024-05-04 03:22
Sorry @DylanDylann, forgot to add the bug label. @MitchExpensify can you please help us out on paying this one? Thanks!

**Comment by MitchExpensify** [comment] 2024-05-06 20:42
**Payment summary**

C $500 @tienifr 
C+ $500 @DylanDylann

**Comment by MitchExpensify** [comment] 2024-05-06 20:44
Paid and contract ended

**Closed by MitchExpensify** 2024-05-06 20:44 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
