### ISSUE TITLE
 2fa input code is not automatically focused

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20237] opened 2023-06-06 03:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Begin Sign-in and add your login for an account with 2fa enabled
2. Copy-paste the magic code received in your email
3. Verify that you are now asked to enter your 2fa code
4. Start typing the code without explicitly clicking on the input component
## Expected Result: 
The code should be entered in the input component as I type it
## Actual Result: 
The code is not entered in the input field until I explicitly click on the input field

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.24-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/09716825-2de3-4852-8467-d201e896142c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @cristipaval 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685702165939109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PrashantMangukiya** [comment] 2023-06-06 04:26
This is dupe of https://github.com/Expensify/App/issues/19711

**Closed** 2023-06-06 16:26 UTC
Labels: Daily, Bug
