### ISSUE TITLE
Pay 20 July [$1000] Error is shown in state/province field of Home address, Personal details while changing to a different location than US.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21793] opened 2023-06-28 13:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Make sure, either it's a new account or make Home address field in personal details is all empty.
1. go to settings -> profile -> personal details
2.  Go to home address , MAKE SURE ALL FIELDS ARE EMPTY
3. (Important step) Now before adding any address line 1 or 2 , pick an state ( any US state)
4. Now on address line 1,  type address outside of the US.
for eg : I typed 'gg' and picked an Indonesian address from the autosuggest.
5. Now notice on the state field, state/province is added. However, error is shown saying " This field is required".
Also, if we hit save button, it works. i.e there is no significance of showing error.

## Expected Result:
After changing address to outside of the US and auto-completing state field ,state field should not throw error.

## Actual Result:
Error is shown in state/province field of Home address, Personal details while changing to a different location than US.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4691e662-9812-4da8-a5f1-94d67e1cd5ca

https://github.com/Expensify/App/assets/43996225/89896d72-0973-4815-ae54-ba5fbf6faaa6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687769529515419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014fa6380f209fa35e</li>
        <li>Upwork Job ID: 1674679743848087552</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by kameshwarnayak** [comment] 2023-07-01 13:32
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Error is shown in state/province field of Home address, Personal details while changing to a different location than US

### What is the root cause of that problem?
The root cause of the problem is the behaviour of react hooks. Each render of the component has its own props and state values. (Refer - https://stackoverflow.com/a/60312624) 

Because of this the value of `countryISO` is set to the previous value in the final initiation of `validate` callback. 

<img width="1434" alt="Screenshot 2023-07-01 at 6 39 04 PM" src="https://github.com/Expensify/App/assets/2232432/9bbefb74-502d-4893-8c22-9d03b8291560">

This causes the error

### What changes do you think we should make in order to solve the problem?

To solve the problem, we can use the `values` passed to the `validate` callback instead of the state values

https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L87-L89

The above code becomes

```
if (values.country === CONST.COUNTRY.US && !COMMON_CONST.STATES[values.state]) {
    errors.state = 'common.error.fieldRequired';
}
```

Result :

https://github.com/Expensify/App/assets/2232432/fdb45ab1-18ff-4153-a8e6-55ab9297f596

### What alternative solutions did you explore? (Optional)
None

**Comment by laurenreidexpensify** [comment] 2023-07-03 11:44
@sobitneupane any feedback on the proposal above?

**Comment by sobitneupane** [comment] 2023-07-04 07:39
@dukenv0307 Thanks for your proposal. It is an intended behavior to default country to "US" as most of the clients are from US.

**Comment by sobitneupane** [comment] 2023-07-04 07:40
[Proposal](https://github.com/Expensify/App/issues/21793#issuecomment-1615917357) from @kameshwarnayak looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by Beamanator** [comment] 2023-07-04 08:03
FYI @ashimsharma10 - looks like you're being hired just for the bug bounty, no PR expected 😅  (don't trust Melvin!!)

**Comment by laurenreidexpensify** [comment] 2023-07-19 13:12
oh weird, the automation failed on this. This was deployed to prod on 13 July - https://github.com/Expensify/App/actions/runs/5538073623- so we can issue payment on 20 July

**Comment by laurenreidexpensify** [comment] 2023-07-19 13:14
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@sobitneupane]  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@sobitneupane]  Determine if we should create a regression test for this bug.
- [ ] [@sobitneupane]  If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@laurenreidexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by laurenreidexpensify** [comment] 2023-07-19 13:15
@sobitneupane please request payment in newdot from @anmurali 

@kameshwarnayak I will issue payment for this on 20 July (tomorrow) assuming no regressions found in next 24 hours

**Comment by laurenreidexpensify** [comment] 2023-07-21 16:51
Payment has been issued to @kameshwarnayak 

Waiting on @sobitneupane to complete steps above before closing

**Comment by sobitneupane** [comment] 2023-07-24 15:09
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/14290
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/14290/files#r1272398532

> * [ ]  [@sobitneupane]  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I think this should have been caught in PR review. It is an edge case. So, could have been missed.

> * [ ]  [@sobitneupane]  Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane]  If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-07-24 15:11
**Regression Test Proposal**

1. Go to settings -> profile -> personal details
2. Go to home address , All the fields must be empty
3. Before adding any address line 1 or 2 , pick a state (any US state)
4. Now on address line 1, type address outside of the US and select an address
5. After selecting address, verify that state field is auto-completed and no error is shown in state field.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-07-24 16:50
Payment requested on newDot.

**Comment by ashimsharma10** [comment] 2023-07-24 16:52
I'm the big reporter. Waiting for payment.

**Comment by laurenreidexpensify** [comment] 2023-07-26 19:04
- Bug Reporter @ashimsharma10 paid in Upwork $250
 - Contributor @kameshwarnayak paid in Upwork $1000
 - C+ @sobitneupane being paid in newdot $1000

**Closed by laurenreidexpensify** 2023-07-26 19:04 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by JmillsExpensify** [comment] 2023-07-27 23:53
Reviewed details for @sobitneupane. This is accurate based on summary from Business Reviewer and approved for payment in NewDot.
