### ISSUE TITLE
[hold for payment 2024-05-29] CRITICAL [$500] Provide option to create workspace on workspace selector screen for Categorize and Share

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#40823] opened 2024-04-23 19:41 UTC
Problem:
====
In the track expense flow, when you try to categorize / share a tracked expense from the actionable whispers - you get to choose from existing workspaces. However, there is no way to create a new workspace directly from that screen. To do so, you'd have to go to Profile -> Workspaces -> New Workspace, and then back to your self-DM to select the actionable whisper option again.

<img width="375" alt="Screenshot 2024-04-23 at 12 23 58 PM" src="https://github.com/Expensify/App/assets/30609178/9f4736cc-0ca5-47e0-b38a-c0f51a04d93d">

Solution:
====
Add an option to create a workspace directly within the workspace selector. We'll add one to the workspace selector that says 'New Workspace' in the form of a green button

![image](https://github.com/Expensify/App/assets/30609178/89df9b2d-ac03-4ccb-b62b-7f0ce7be702e)

When pressed, this will create a workspace and automatically use it in the rest of the categorize / share flow 

Note: In the case where there is no workspace, we will still automatically create a workspace for them. This only impacts the flow where there are existing workspaces to choose from already

Now for these cases, we'll add a confirmation page for the workspace name
![image](https://github.com/Expensify/App/assets/30609178/378ec305-c7a6-4344-a844-1577bf137d57)

Going to hold this issue until https://github.com/Expensify/App/issues/40668 is complete - the auto-creation of workspace in no existing workspace flow is more important and so we'd rather have that completed first
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01950277585ef7d30c</li>
        <li>Upwork Job ID: 1787572979628498944</li>
        <li>Last Price Increase: 2024-05-06</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by shawnborton** [comment] 2024-04-24 12:39
I think we'd get something like this:
![CleanShot 2024-04-24 at 08 38 27@2x](https://github.com/Expensify/App/assets/2319350/cb068f26-f1bc-4fa3-b97d-971d871d4136)

cc @Expensify/design for visibility

@thienlnam I also think we should update the label text in the search input, right? Because you can only search for an existing workspace and not `Name, email, or phone number`

**Comment by dannymcclain** [comment] 2024-04-24 13:29
@shawnborton that looks good to me, and I agree about updating the search input label.

Before we go to far though, is this the design pattern we want to use for this? I only ask because the group mock referenced in the description is likely not the pattern we're going to be implementing there, so we don't strictly need to follow that mock/pattern.

I think the solution you've (Shawn) posted is good—just want to make sure we're all on the same page and that you don't have any other/better/different ideas for this interaction.

**Comment by shawnborton** [comment] 2024-04-24 13:37
That's a fair point... I did take a look at the Workspace switcher but the create workspace button feels quite subtle there:
![CleanShot 2024-04-24 at 09 32 51@2x](https://github.com/Expensify/App/assets/2319350/3663f7b7-28ed-455c-b38f-ef47873d6296)

Alternatively we could place a large green button at the bottom, which is a pattern we had previously used in the workspaces list:
![CleanShot 2024-04-24 at 09 35 17@2x](https://github.com/Expensify/App/assets/2319350/ac34efd1-0d82-4be7-9266-9d810463e5b6)


And that might actually work better with an empty state, assuming we'd show one if you didn't have any workspaces? 
![CleanShot 2024-04-24 at 09 37 29@2x](https://github.com/Expensify/App/assets/2319350/b8112a33-c625-48ee-87aa-39d609ed780f)

Or is the plan to automatically create a workspace for someone when they categorize for the first time?

**Comment by shawnborton** [comment] 2024-04-24 14:01
To answer this question though:

> Do you think it's obvious enough that it's a separate action from the list and not related to the items above?

Comparing them:

![CleanShot 2024-04-24 at 10 01 25@2x](https://github.com/Expensify/App/assets/2319350/dcac0172-cee1-4f34-8a3e-374c26559bd0)

I am a bit torn... both could work, and even though the right uses a giant green button, something about the left feels a little more obvious?

**Comment by dannymcclain** [comment] 2024-04-24 14:14
>I am a bit torn... both could work, and even though the right uses a giant green button, something about the left feels a little more obvious?

Yeah this is pretty much exactly how I feel haha

**Comment by thienlnam** [comment] 2024-04-24 20:52
> Or is the plan to automatically create a workspace for someone when they categorize for the first time?

We're going to do both - so
1. When they categorize for the first time and do not have an existing workspace, we'll automatically create one for them
2. If they have existing workspaces, we'll show the screen that y'all are mocking - providing an option to create a workspace or select an existing one

**Comment by quinthar** [comment] 2024-04-25 01:48
Which are we going with, the big green button or the... other one (not sure how to describe)?  I think the BGB is a more common pattern for our app, so I vote we stick with that.

**Comment by shawnborton** [comment] 2024-04-25 11:20
Got it, I think that gives us this as the final mock then: 
![CleanShot 2024-04-25 at 07 20 01@2x](https://github.com/Expensify/App/assets/2319350/f93c828a-75d6-4ff7-a3eb-c14c2a3b6db2)


Are we planning to do any kind of education piece around this one?
> When they categorize for the first time and do not have an existing workspace, we'll automatically create one for them

**Comment by dannymcclain** [comment] 2024-04-25 13:31
Totally down to stick with Big Green.

>Are we planning to do any kind of education piece around this one?
>When they categorize for the first time and do not have an existing workspace, we'll automatically create one for them

To Shawn's question above, I think we'll need to somehow explain what we're doing. Creating a workspace and moving an expense to that workspace (and categorizing it) is kind of a big thing to do with no explanation. I could see that being pretty confusing without an explanation. `:my_two_cents:`

**Comment by dannymcclain** [comment] 2024-04-25 15:33
Oh yeah I do remember that and I love the idea of incorporating that idea here.

**Comment by shawnborton** [comment] 2024-04-25 15:56
Yeah, something like this is what I was thinking:
![CleanShot 2024-04-25 at 11 55 17@2x](https://github.com/Expensify/App/assets/2319350/eddeef72-de46-49de-b79d-6d99d407f71c)

([Figgy](https://www.figma.com/file/ReBRDcqMXgtvPgWBBCmBxs/Wave-9%3A-Track-Expense?type=design&node-id=429%3A8635&mode=design&t=3NVJetdZ3I8nBfdd-1))

**Comment by dubielzyk-expensify** [comment] 2024-04-26 02:37
That looks good. Worth mentioning that we have a screen similar to this in Stage 2 onboarding. I might tweak it or meet halfway here with how it looks and feels. 

![CleanShot 2024-04-26 at 12 36 31@2x](https://github.com/Expensify/App/assets/145416827/02d87e49-5f28-48e0-ac73-17fd73486468)

**Comment by dubielzyk-expensify** [comment] 2024-04-26 02:41
Also for the page header where it says "Workspace details", I kinda feel like it should say `New Workspace` instead. Or something like that to indicate that it's being created

**Comment by quinthar** [comment] 2024-04-27 03:07
Do we have a final plan here?  Who is building this and what is the ETA?

**Comment by shawnborton** [comment] 2024-04-29 12:02
> Also for the page header where it says "Workspace details", I kinda feel like it should say New Workspace instead. Or something like that to indicate that it's being created

Well I think the reality is that we already automatically created the workspace for you, so you aren't really doing anything besides confirming some details or customizing the workspace. So that being said, I don't think "New Workspace" makes the most sense.

> Do we have a final plan here? Who is building this and what is the ETA?

I think the first step of solving the issue for "Provide option to create workspace on workspace selector screen for Categorize and Share" is to just add a green button to the workspace selection list like so:
![CleanShot 2024-04-29 at 08 01 06@2x](https://github.com/Expensify/App/assets/2319350/a225b8a6-c03d-436f-9425-81765ea8a81c)

Then we can follow up and add a "Confirm workspace details" flow for when the user opts to create a new workspace from the Categorize flow, or if the user does not have a workspace and we create one for them automatically:
![CleanShot 2024-04-29 at 08 02 11@2x](https://github.com/Expensify/App/assets/2319350/7052471c-83ee-47c1-8b03-c9626e50942b)

**Comment by dannymcclain** [comment] 2024-04-29 13:44
Ah good point Shawn. I hadn't considered that about the `New workspace` vs `Confirm details` page header. I'm with you. And agree with your next steps.

**Comment by dubielzyk-expensify** [comment] 2024-04-30 03:37
> Well I think the reality is that we already automatically created the workspace for you, so you aren't really doing anything besides confirming some details or customizing the workspace. So that being said, I don't think "New Workspace" makes the most sense.

That's fair. Minor typo in the header:
![CleanShot 2024-04-30 at 13 37 24@2x](https://github.com/Expensify/App/assets/145416827/79a03999-b160-4e13-9515-be0be4f094f6)

**Comment by quinthar** [comment] 2024-05-04 01:09
Ok https://github.com/Expensify/App/issues/40823#issuecomment-2082548200 is the final design, who is implementing?  What are the next steps?

**Comment by joekaufmanexpensify** [comment] 2024-05-06 13:16
@thienlnam can this be external? If so, I will open it up for proposals asap now that we've aligned on the final design

**Comment by thienlnam** [comment] 2024-05-06 19:59
Alright! The holding PR just merged, and we're having @allroundexperts implement this - this is ready to be worked on

**Comment by thienlnam** [comment] 2024-05-06 20:05
Let's also make sure to add the additional screen for workspace name in the mock as well. I created an issue to track this internally [here](https://github.com/Expensify/App/issues/41697)

**Comment by allroundexperts** [comment] 2024-05-06 21:05
@thienlnam @shawnborton In the following mock:
![image](https://github.com/Expensify/App/assets/30054992/0cf866e1-0612-4fc0-83f2-7ff9164df93b)

There isn't any confirmation screen that allows the user to change date, selected category, tag etc. Is that expected? Are we ditching it for this workflow?

**Comment by dannymcclain** [comment] 2024-05-06 21:07
>There isn't any confirmation screen that allows the user to change date, selected category, tag etc. Is that expected? Are we ditching it for this workflow?

Great question, I'll let the others weigh in to see what's expected but I could definitely see us adding the "expense confirmation" screen right after the workspace details step.

**Comment by allroundexperts** [comment] 2024-05-06 21:34
@ishpaul777 @thienlnam Do you know if we have this sort of Alert component already?

<img width="345" alt="Screenshot 2024-05-07 at 2 34 12 AM" src="https://github.com/Expensify/App/assets/30054992/07f813a5-7bcf-4ae3-94da-8715debe46a1">

**Comment by allroundexperts** [comment] 2024-05-06 21:41
@thienlnam @shawnborton Can you also confirm the expected behaviour when the user clicks `create new workspace` button? Should it redirect to the workspace details confirmation page? or the expense confirmation page?

**Comment by shawnborton** [comment] 2024-05-06 23:41
> Do you know if we have this sort of Alert component already?

We basically have this exact same banner in archived or read-only rooms:
![CleanShot 2024-05-06 at 19 30 22@2x](https://github.com/Expensify/App/assets/2319350/c2f2809e-9d5e-400a-bc95-b78d4db8db85)

> There isn't any confirmation screen that allows the user to change date, selected category, tag etc. Is that expected? Are we ditching it for this workflow?

Good catch on that. I think we'd keep the expense confirmation screen as it exists today, and it would show up before the workspace confirmation page

> Can you also confirm the expected behaviour when the user clicks create new workspace button? Should it redirect to the workspace details confirmation page? or the expense confirmation page?

I think it would make sense to go from the workspace selection screen to a "new workspace" screen, and I think it makes sense to just use a text input instead of a push row, thoughts @Expensify/design ?
![CleanShot 2024-05-06 at 19 37 11@2x](https://github.com/Expensify/App/assets/2319350/2f3c4646-8444-4539-b771-e3b9f1a2aae6)

And actually, that makes me think that we should do the same with the flow for when you have no workspace... that would be something like this then? 
![CleanShot 2024-05-06 at 19 41 19@2x](https://github.com/Expensify/App/assets/2319350/2f7229c1-27aa-4b71-a502-c77223627102)

Curious what you think.

**Comment by allroundexperts** [comment] 2024-05-07 08:06
Makes sense to me. I'll start the implementation.

**Comment by dannymcclain** [comment] 2024-05-07 13:12
Yup I like that too

**Comment by thienlnam** [comment] 2024-05-07 18:28
Sorry for the last minute change, but we have decided to forgo the screen to add a workspace name so the flow will instead just look like this

**No existing workspace, auto-create**

![image](https://github.com/Expensify/App/assets/30609178/b4ed9d0f-094b-4d12-ad06-ccb0e237cfd6)


**Existing workspaces, create a new one**
![image](https://github.com/Expensify/App/assets/30609178/2337b42c-3ff1-4b06-841a-a3cd6cd6fdff)


And then the same applied to the 'Share with my accountant' flow

**Comment by allroundexperts** [comment] 2024-05-07 18:33
Ah.... Okay. No worries. I'll make it this way.

**Comment by allroundexperts** [comment] 2024-05-07 20:18
PR: https://github.com/Expensify/App/pull/41811

**Comment by joekaufmanexpensify** [comment] 2024-05-13 14:19
PR in review

**Comment by joekaufmanexpensify** [comment] 2024-05-20 14:25
PR on staging

**Comment by joekaufmanexpensify** [comment] 2024-05-28 14:57
Automation did not work. PR is on prod, and payment is due tomorrow.

**Comment by joekaufmanexpensify** [comment] 2024-05-29 13:58
@ishpaul777 $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-05-29 13:58
Upwork job closed

**Comment by joekaufmanexpensify** [comment] 2024-05-29 13:59
Only thing left is for @allroundexperts to request payment. Going to close the issue for now, since I know you do that in batches. Thanks everyone!

**Comment by joekaufmanexpensify** [comment] 2024-05-29 13:59
Payment summary is [here](https://github.com/Expensify/App/issues/40823#issuecomment-2135445782) too

**Closed by joekaufmanexpensify** 2024-05-29 13:59 UTC
Labels: Reviewing, External, Weekly, NewFeature, Design

**Comment by JmillsExpensify** [comment] 2024-07-09 23:07
$500 approved for @allroundexperts
