### ISSUE TITLE
[HOLD for payment 2023-06-09] [$1000] __fake__ appears on LHN for a moment when the last comment of the chat is deleted

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19629] opened 2023-05-25 20:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a report with no chat history
2. Send a comment
3. Delete the comment

## Expected Result:
__fake__ does not appear on LHN
## Actual Result:
__fake__ appears on LHN for a moment

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8dd09f14-e3bb-4968-8c0d-0d0940a9b597

https://github.com/Expensify/App/assets/43996225/106443bb-0406-4ca1-acb2-f0463961f8a4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:**https://expensify.slack.com/archives/C049HHMV9SM/p1684851576726169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ffa2e3b69d480960</li>
        <li>Upwork Job ID: 1662027990801956864</li>
        <li>Last Price Increase: 2023-05-26</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-05-26 02:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

`__fake__` appears on LHN for a moment when the last comment of the chat is deleted.

### What is the root cause of that problem?

When deleting a comment, in method [deleteReportComment](https://github.com/Expensify/App/blob/6f243fe60311bec9eff6976baceb384b56d53687/src/libs/actions/Report.js#L818)

https://github.com/Expensify/App/blob/6f243fe60311bec9eff6976baceb384b56d53687/src/libs/actions/Report.js#L843-L850

We call method [ReportActionsUtils.getLastVisibleMessageText](https://github.com/Expensify/App/blob/6f243fe60311bec9eff6976baceb384b56d53687/src/libs/ReportActionsUtils.js#L224) to set optimistic `lastMessageText`.

The `__fake__` text is from the `CREATED` type report action

<img width="400" alt="image" src="https://github.com/Expensify/App/assets/117511920/75a103e8-62d0-49b6-a327-ecf20d4dae33">

 which should be hidden.

The root cause of this issue is that we don't filter out report action with `actionName` equal to `CONST.REPORT.ACTIONS.TYPE.CREATED` in method getLastVisibleAction for visibleActions

https://github.com/Expensify/App/blob/6f243fe60311bec9eff6976baceb384b56d53687/src/libs/ReportActionsUtils.js#L210

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should filter out report action with `actionName` equal to  `CONST.REPORT.ACTIONS.TYPE.CREATED` in method getLastVisibleAction for visibleActions. We can change this line 

https://github.com/Expensify/App/blob/6f243fe60311bec9eff6976baceb384b56d53687/src/libs/ReportActionsUtils.js#L210

to

```js
const visibleActions = _.filter(actions, (action) => action.actionName !== CONST.REPORT.ACTIONS.TYPE.CREATED && !isDeletedAction(action));
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by conorpendergrast** [comment] 2023-05-26 09:28
Reproduced, thanks!

**Comment by eh2077** [comment] 2023-05-26 22:25
@luacmartins Thanks for reviewing proposals! 

When I wrote the proposal, I searched the usages of method `getLastVisibleAction` in the codebase and found it's mainly used to format the `lastMessageText` when deleting/editing comment. So, it won’t impact the function you pointed out. I feel your concern but I think it's mainly because the method name `getLastVisibleAction` is more general than what it’s actually used currently.

The key idea of my proposal is to filter out report action with actionName equal to `CONST.REPORT.ACTIONS.TYPE.CREATED` when setting optimistic `lastMessageText`.

**Comment by mananjadhav** [comment] 2023-05-27 14:37
I agree with you @luacmartins. I don't think we would want to filter out the CREATED action, instead returning the empty string sounds better approach to me.

@luacmartins All yours.

**Comment by dukenv0307** [comment] 2023-05-29 03:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
__fake__ appears on LHN for a moment when the last comment of the chat is deleted

### What is the root cause of that problem?
when we remove a message, `lastMessageText`, we will find the previous visible one and update the `lastMessageText` in the LHN. If the removed message is the last one, the previous message will be created action with the  `__fake__ ` in its message

### What changes do you think we should make in order to solve the problem?
I suggest that we should display `[message deleted]` as `lastMessageText` when a message is deleted

If we agree with this approach:
1. When removing a message, 
In here 
https://github.com/Expensify/App/blob/414dc106d707a326094f7227c9dc91597596cd0c/src/libs/actions/Report.js#L839-L843
we always update `lastMessageText` is [message deleted]
2. Update from BE side, If a message is deleted the text should be [message deleted]. And we don't need to filter the deleted message when get `lastMessageText`
### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment] 2023-05-29 15:43
lol I just assigned a contributor to the issue. Not overdue Melvin!

**Comment by conorpendergrast** [comment] 2023-05-31 13:49
Looks like @luacmartins has reviewed [the PR](https://github.com/Expensify/App/pull/19747), and it's pending on @mananjadhav's review now

**Comment by mananjadhav** [comment] 2023-06-09 12:24
@luacmartins I found that we added `__fake__` in optimistic chat creation in this [PR](https://github.com/Expensify/App/pull/9991/files). What I can't figure out is if the any of the delete refactors caused this.

I would say because it is optimistic data creation this is the PR that caused this. I don't see anything that we could update the checklist with. This is a miss in our testing. 

I also think we should add a regression test from the `Test Steps` of the linked PR. Are we good with that @luacmartins @conorpendergrast @hoangzinh ?

**Comment by conorpendergrast** [comment] 2023-06-09 12:48
Looks like this the PR was merged in less than 3 business days after assignment, so adding in the +50% urgency bonus for Contributor @hoangzinh and C+ @mananjadhav.

**Comment by conorpendergrast** [comment] 2023-06-09 12:51
@mananjadhav Sounds like these are the proposed testing steps, correct? 

1. Open a report with no chat history
2. Send a comment
3. Delete the comment
4. Verify that `__fake__` does not appear on LHN
5. Verify that it shows "This is the beginning of your chat with" in LHN
6. Verify that no errors appear in the JS console

**Comment by mananjadhav** [comment] 2023-06-09 13:00
Yes @conorpendergrast, that's right.

**Comment by conorpendergrast** [comment] 2023-06-09 13:06
Sounds great to me 👍

**Comment by conorpendergrast** [comment] 2023-06-09 13:06
Everyone paid here 👍

**Comment by luacmartins** [comment] 2023-06-09 15:29
Those regression test steps seem fine to me. Are we good to close this issue once that's done?

**Comment by conorpendergrast** [comment] 2023-06-09 15:33
Yup! I'll create an issue for that regression test, and then close out this issue

**Comment by conorpendergrast** [comment] 2023-06-09 18:48
Regression test created: https://github.com/Expensify/Expensify/issues/290880

Closing this out, thanks everyone!

**Closed by conorpendergrast** 2023-06-09 18:48 UTC
Labels: External, Daily, Awaiting Payment, Bug
