### ISSUE TITLE
[$250] Android - Chat - Starting chat with email id having apostrophe showing error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39933] opened 2024-04-09 13:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4484121
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap fab-- start chat
3. Enter email id with apostrophe eg: jaihanumanblog+4557'[fgh@gmail.com](mailto:fgh@gmail.com)
4. Select the contact

## Expected Result:
When user enters email id with apostrophe, if it is invalid, it must say invalid id and must not direct to conversation page. If it is valid id, "Auth createaccount returned an error", must not be displayed in conversation page

## Actual Result:
User navigated to conversation page showing error "Auth createaccount returned an error" when starting conversation with user having email id with apostrophe

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/efcfb6f7-f77f-4329-b90f-a063fa1e0ec1

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013af654cc6fe733d4</li>
        <li>Upwork Job ID: 1779877807418626048</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-09 13:27
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-09 13:27
We think that this bug might be related to #vip-vsp

**Comment by miljakljajic** [comment] 2024-04-15 14:22
I think this can be worked on externally - thank you @lanitochka17 !

@getusha - there is a proposal ready to review when you have a chance!

**Comment by SaintSlim** [comment] 2024-04-27 23:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invalid Id's are currently still being redirected to the conversation page and returning Auth createAccount error instead of returning invalid id .

### What is the root cause of that problem?
When a user inputs a name, email, or phone number, if the contact information isn't already in the user's contact list or recent contacts, an optimistic ID is generated. For emails, an optimistic ID is generated and returned only if the email entered by the user conforms to the [Email Base Regex](https://github.com/Expensify/expensify-common/blob/13de5b0606662df33fa1392ad82cc11daadff52e/lib/CONST.jsx#L3-L5l), which permits special characters such as  `#`, `%`, `+`, `'`, and `-`. I believe the Authentication Service restricts account creation with emails containing specific special characters, hence the Auth createaccount error returned.

### What changes do you think we should make in order to solve the problem?
Update the email base REGEX to align with the emails supported by the Authentication Service, and identify and adjust specific use cases where special characters are permitted. For instance, the option for the `+` character to be appended for creating multiple test accounts.

**Comment by miljakljajic** [comment] 2024-04-30 13:45
I agree that this formatting is pretty rare and we could probably close this.

**Comment by getusha** [comment] 2024-05-03 19:00
@miljakljajic we can close this.

**Closed** 2024-05-07 11:16 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
