### ISSUE TITLE
[$1000] Chat - Page not found for valid chat with access if clicking deeplink after invalid chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20722] opened 2023-06-13 22:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/20407

## Action Performed:
1. Login to NewDot Android native
2. From another app tap any invalid (or no access ) chat deeplink
3. Page not found is displayed. Do not click Back button.
4. From another app tap a valid with access chat deeplink

## Expected Result:
Chat should be displayed

## Actual Result:
Page not found is still displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/80d7f950-9201-4499-bf82-38a69031d397

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e33b2003048b6946</li>
        <li>Upwork Job ID: 1673854548230725632</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by deetergp** [comment] 2023-06-13 22:26
This is an edge case similar to https://github.com/Expensify/App/issues/19496 and should be fixed and might be related, but isn't a big enough deal that I would consider it a deploy blocker.

**Comment by kbecciv** [comment] 2023-06-13 22:34
I updated environments, reproduced in Android and iOS native. Deep links work correctly if app is in LHN

**Comment by deetergp** [comment] 2023-06-28 00:43
I'm pretty sure this can be dealt with by a contributor. Marking it external.

**Comment by koko57** [comment] 2023-06-28 15:08
Hi! I'm Agata from Callstack, expert agency, maybe I can help with this issue?

**Comment by NicMendonca** [comment] 2023-06-30 20:28
@hungvu193 yes! Still open for proposals!

@Santhosh-Sellavel can you review please? https://github.com/Expensify/App/issues/20722#issuecomment-1611662134

Hi @koko57 👋 I'll let @Santhosh-Sellavel [decide if we need any extra help here](https://github.com/Expensify/App/issues/20722#issuecomment-1611620498). Ty!

**Comment by Santhosh-Sellavel** [comment] 2023-07-02 21:42
Yes, this seems to duplicate, @hungvu193 Please move your proposal there too. As it sounds like a good option!

@NicMendonca We can close this as it is a duplicate of https://github.com/Expensify/App/issues/20624.

**Closed** 2023-07-03 21:42 UTC
Labels: External, Engineering, Daily, Help Wanted
