### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Web - Split bill - Show more button in split bill has no padding below

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25562] opened 2023-08-21 09:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and split bill
3. Enter any amount and select more then 5 users
4. After selecting users, click next, observe that show more button has no padding below making it look connected to split button
5. Click on split
6. Click on split bill message and observe that due to lack of padding below show more, it appears to be sticked to bottom of screen

## Expected Result:
Show more button should have padding below like we generally have for all buttons to ensure they do not appear adjacent to any interface or bottom or screen

## Actual Result:
Show more button has no padding below making it look adjacent to split button as well as bottom of screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/923fb9b2-98a1-4df1-b22d-325fa3cc515e

https://github.com/Expensify/App/assets/115492554/4e263b6b-694a-426b-985a-06f7b87571f3

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691649933142409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d1ff6c61c186d88</li>
        <li>Upwork Job ID: 1694384587884593152</li>
        <li>Last Price Increase: 2023-08-23</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26307166</li>
<li>c3024 | Contributor | 26307169</li>
<li>Dhanashree-Sawant | Reporter | 26307172</li>
</ul></li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment] 2023-08-21 10:26
@izarutskaya Slack post link? usually there should be a link to the slack post. because of this I couldn't tell it was the same thing and didn't post my proposal. please include the slack links. thank you.

**Comment by AmjedNazzal** [comment] 2023-08-21 10:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Split bill - Show more button in split bill has no padding below

### What is the root cause of that problem?

The reason there is no padding is because although all MenuItemWithTopDescription have mb2, the view used if !showAllFields doesn't have any margin or padding.
https://github.com/Expensify/App/blob/774b78c31c3b4f93585446ed807d07cece4de737/src/components/MoneyRequestConfirmationList.js#L391-L393

### What changes do you think we should make in order to solve the problem?

We should add mb2 to the view to keep things consistant.
```javascript
{!showAllFields && (
    <View style={[..., styles.mb2]}>
```

### Result

https://github.com/Expensify/App/assets/74202751/d04847ca-f4ee-4fd9-9cc7-159249e5073d

**Comment by byobeers** [comment] 2023-08-23 23:28
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**

There are actually 2 problems here. 

1) There is no margin attached to the 'show more' dropdown, as stated and shown above. 

2) The more difficult issue is the way that the window reacts to being shrunk to the minimum height. When that happens, the Button, 'show more' dropdown, and description item above it get shrunk and overlap one another.
<img width="959" alt="image" src="https://github.com/Expensify/App/assets/134170979/420338d2-fd1c-46d4-8123-55c9321b1044">

What is the root cause of that problem?
incorrect handling of window resizing by the objects mentioned above. Adding too many (more than 5) recipients shrinks the available space, and brings up issues with how the window handles and prioritizes the elements.

What changes do you think we should make in order to solve the problem?
As mentioned above, we can add a class like .mb2 to the view on L372. To fix the other issue, we can actually just add .flex0 to the same line. When we do this, the show more button stacks on top of the item above it, as shown here:
<img width="959" alt="image" src="https://github.com/Expensify/App/assets/134170979/e8808fcc-f3ad-4b2e-a3d5-00b0a05283fd">
Nice and neat!


What alternative solutions did you explore? (Optional)
Verified this suggestion from above: We can add space below the button. I think we can add styles.mb2 or styles.mb3 in [here](https://github.com/Expensify/App/blob/043b1eded5eef81d06611df2891b0d6c793b42dd/src/components/MoneyRequestConfirmationList.js#L392)
Also looked at adding the styling in other places, but it makes the most sense to add it here so that it encapsulates the show more dropdown and the horizontal line.

**Comment by byobeers** [comment] 2023-08-23 23:31
Contributor details
Your Expensify account email: bobby.a.beers@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d6eff652c9b8b4fa

please get in touch with me via email before processing any payment. Thanks!

**Comment by byobeers** [comment] 2023-08-24 13:31
and what about the other issue that I found?

**Comment by luacmartins** [comment] 2023-09-15 09:41
Bump @JmillsExpensify

**Comment by luacmartins** [comment] 2023-09-18 08:50
Bumped @JmillsExpensify

**Comment by c3024** [comment] 2023-09-20 01:05
Payment is long overdue. Could you please complete? @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2023-09-20 05:28
Sure thing. Payment summary is as follows:

 - Issue reporter: @dhanashree-sawant $250 (issue created before Sept. 1)
 - Contributor: @c3024 $1,500 (incl. urgency bonus) 
 - Contributor+: @Ollyws $1,500 (incl. urgency bonus)

Upwork job is here: https://www.upwork.com/jobs/~018d1ff6c61c186d88. @dhanashree-sawant has been paid out. @c3024 similarly, it looks like you've been paid $1,000, so you're owed the delta of $500. Is that right?

**Comment by JmillsExpensify** [comment] 2023-09-20 05:29
@Ollyws You have an offer outstanding, right? Let me know once you accept on this issue. 🙌🏼

**Comment by c3024** [comment] 2023-09-20 05:29
Thank you. Yes, $500 bonus yet to be paid.

**Comment by JmillsExpensify** [comment] 2023-09-20 05:31
Great, that's been handled now! All paid.

**Comment by luacmartins** [comment] 2023-09-20 06:56
Cool, I think we're good to close then?

**Comment by luacmartins** [comment] 2023-09-25 07:20
I think payment is handled. Closing the issue. Feel free to reopen if we missed something.

**Comment by luacmartins** [comment] 2023-10-10 16:51
@JmillsExpensify seems like I prematurely closed this one. Could you please help with payment?

**Comment by JmillsExpensify** [comment] 2023-10-12 19:55
Ah opps sorry about that.

**Comment by JmillsExpensify** [comment] 2023-10-12 19:58
Looking into this now in any case

**Comment by JmillsExpensify** [comment] 2023-10-12 20:02
@Ollyws I see what happened now. We owed you $500. I accidentally you sent extra and request a portion of it back. Do you mind refunding that portion? Otherwise we are good here!

**Closed by JmillsExpensify** 2023-10-12 20:02 UTC
Labels: External, Daily, Awaiting Payment, Bug
