### ISSUE TITLE
[$250] mWeb/Chrome - Chat - Emoji can be opened only the second time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11335] opened 2022-09-27 12:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
and login with any account
2. Go to chat with any user
3. Sent a message
4. Select edit the comment you just sent
5. Open Emoji

## Expected Result:
Emoji can be opened the first time

## Actual Result:
Emoji can be opened only the second time

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.7.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192528269-f8798904-5417-46e4-96d4-7a418363e169.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment] 2022-10-03 17:54
Hey sorry for lack of response here, was out sick last week, this looks like an excellent external issue.

I just tried this on web on staging/prod with a desktop sized screen and wasn't able to reproduce, but as soon as I changed the width to a small-screen size it started to happen:

https://user-images.githubusercontent.com/31285285/193644796-8032909b-989d-472a-8d66-26aa2ce28e5b.mov

This leads me to believe that it's not a platform specific issue with iOS/Android native, and is instead probably something wrong with our logic [here](https://github.com/Expensify/App/blob/53f70fe9f758ab145bb2b314811491637552b2d6/src/pages/home/report/ReportActionItemMessageEdit.js#L219-L223)

**Comment by Tushu17** [comment] 2022-10-03 18:36
I've already reported this issue here :-
https://github.com/Expensify/App/issues/10290

**Comment by Santhosh-Sellavel** [comment] 2022-10-03 19:45
Due to Limited Availability will not be able to get this sooner so unassigning this one. Can you reapply the external label to get another C+ assigned thanks!

@michaelhaxhiu @jasperhuangg

**Comment by jasperhuangg** [comment] 2022-10-04 16:49
Ah, according to @Tushu17 this seems like a duplicate of https://github.com/Expensify/App/issues/10290, closing in favor of that one

**Closed by jasperhuangg** 2022-10-04 16:49 UTC
Labels: External, Engineering, Daily, Help Wanted
