### ISSUE TITLE
[HOLD][$500] Chat - When starting chat with anonymous user, mail id is shown for seconds in header

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31746] opened 2023-11-22 20:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab
3. Tap start chat
4. Enter an anonymous user id eg: [56@46.com](mailto:56@46.com)
5.Note the header of 1:1 chat

## Expected Result:
When starting chat with anonymous user id, hidden should be displayed in header

## Actual Result:
When starting chat with anonymous user id , instead of hidden, user mail id is shown for seconds

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/295e5258-dbeb-4151-a8c4-f20377a64cb9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136564f9e3b767f92</li>
        <li>Upwork Job ID: 1727425449409019904</li>
        <li>Last Price Increase: 2023-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28094806</li>
</ul></li>
    </ul>
</details>

**Comment by burczu** [comment] 2023-11-28 13:19
@dukenv0307 Seems like removing `displayName: login,` as you suggested does not fix the issue (the chat closes right after opening), but maybe you wasn't specific enough?

Still waiting for more proposals.

**Comment by burczu** [comment] 2023-11-29 11:40
Alright @dukenv0307, thanks for the update.

Looks like the updated proposal from @dukenv0307 fixes the issue, so I think we could proceed with it.

🎀 👀 🎀 C+ reviewed

**Comment by danieldoglas** [comment] 2023-11-29 16:46
hm, this is an interesting case. Why would we not show the email, considering that the user already knew the email when they started the conversation?

I think we need to discuss this one internally before deciding on the change

**Comment by danieldoglas** [comment] 2023-11-29 18:05
I agree this is from the backend, that's why we're having an internal discussion. I'll send this to weekly and HOLD for now until we reach a conclusion

**Comment by yh-0218** [comment] 2023-12-06 13:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - When starting chat with anonymous user, mail id is shown for seconds in header
### What is the root cause of that problem?
We didn't consider that selected user is first chat member with my account on header.
### What changes do you think we should make in order to solve the problem?
`const interactWithUser = !!props.report.maxSequenceNumber;`
1. update
```
 fullTitle={interactWithUser ? title : ''}
 tooltipEnabled={interactWithUser}
```
https://github.com/Expensify/App/blob/bbe73efdfab056d5ab6d864941fc3da44ec1c084/src/pages/home/HeaderView.js#L243
2. update and fix MultipleAvatars component (when shouldShowTooltip = false, Don't show tooltip or show "hidden" text"
```
shouldShowTooltip={interactWithUser && (!isChatRoom || isChatThread)}
```
https://github.com/Expensify/App/blob/bbe73efdfab056d5ab6d864941fc3da44ec1c084/src/pages/home/HeaderView.js#L236
### What alternative solutions did you explore? (Optional)

**Comment by yh-0218** [comment] 2023-12-06 17:43
@puneetlath I think we can know from `report.maxSequenceNumber` value

**Comment by yh-0218** [comment] 2023-12-06 19:29
@puneetlath `report.maxSequenceNumber` is message count with that user on 1:1 chat.

**Comment by puneetlath** [comment] 2023-12-08 20:09
@burczu @danieldoglas curious what you think about this: https://github.com/Expensify/App/issues/31746#issuecomment-1843337287

**Comment by danieldoglas** [comment] 2023-12-09 01:10
@puneetlath I think that will work, but I don't think that's an ideal solution for 2 reasons:

1. We will need to be careful in all places where we receive personalDetails to guarantee that we're merging the local values to what we're receiving
2. As you mentioned, that only solves for local session, so if the user logs out and in again, the user would see the user as hidden again

Are you suggesting that we do this as a solution for the moment because the backend changes to contain this will take a long time?

**Comment by slafortune** [comment] 2023-12-21 17:27
Let's close this then, since the proposal doesn't really work

**Comment by puneetlath** [comment] 2023-12-28 21:59
Hm, I disagree. I think it's not perfect, but I don't think there's any better idea we've been able to come up with and it's better than what we have now.

**Comment by slafortune** [comment] 2024-01-10 14:35
Hey @danieldoglas are you able to help move this forward?

**Comment by burczu** [comment] 2024-01-11 08:55
@slafortune As I'm not a C+ anymore, please assign another C+ engineer instead of me to this issue. Thank you.

**Comment by situchan** [comment] 2024-01-11 11:01
I can take over as C+

**Comment by danieldoglas** [comment] 2024-01-11 15:09
I can, but I think @puneetlath might have more context to deal with this one. Would you mind if I assign you, Puneet?

**Comment by puneetlath** [comment] 2024-01-12 21:51
Yep, I'll take it. A semi-related issue that @youssef-lr is working on might actually end up fixing this though.

**Comment by youssef-lr** [comment] 2024-01-12 21:53
Yup! This should be worked once [this](https://github.com/Expensify/Web-Expensify/pull/40444) is done.

**Comment by situchan** [comment] 2024-01-25 14:20
Tested on latest main.
Now the behavior is:

> When starting chat with anonymous user id, email is displayed in header

While Expected Result stated in OP is:

> When starting chat with anonymous user id, hidden should be displayed in header

**Comment by youssef-lr** [comment] 2024-01-25 14:47
@situchan try starting a chat with an existing user that's unknown to you, for example, `youssef@expensifail.com`. If you try with a non-existing email, they will become "known" to you because you've technically invited them to the platform.

**Comment by situchan** [comment] 2024-01-25 14:54
> @situchan try starting a chat with an existing user that's unknown to you, for example, `youssef@expensifail.com`. If you try with a non-existing email, they will become "known" to you because you've technically invited them to the platform.

After email is shown for seconds, it changes to display name. Expected?


https://github.com/Expensify/App/assets/108292595/1be6ebf5-49be-4c6f-86a4-c48dd3539e80

**Comment by youssef-lr** [comment] 2024-01-25 15:03
right, now if I remove my display name, you'll see Hidden. Try this account which doesn't have a display name `youssef+44@expensifail.com`

**Comment by situchan** [comment] 2024-01-25 15:07
> right, now if I remove my display name, you'll see Hidden. Try this account which doesn't have a display name `youssef+44@expensifail.com`

https://github.com/Expensify/App/assets/108292595/d897e9ca-0f76-4981-b3d1-90ec5dd9fe01

yes, this is exactly OP.

If this is expected, I am confused what the bug is to fix here

**Closed** 2024-02-07 15:49 UTC
Labels: External, Weekly, Internal, Bug
