### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250] Report fields - Row is not grayed out when added/edited offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44798] opened 2024-07-04 03:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):** n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Workspace settings > Report fields (enable from More features)
3. Go offline.
4. Tap Add field.
5. Add any report field and save it.

## Expected Result:
The row will be grayed out when added offline.

## Actual Result:
The row is not grayed out when added offline. This also applies to List values editor for List report field.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/9e99c34c-8da0-47b2-bd42-ff4d21986c4a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018389cb0ae25e3928</li>
        <li>Upwork Job ID: 1808737930014144742</li>
        <li>Last Price Increase: 2024-07-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by m-natarajan** [comment] 2024-07-04 03:18
@techievivek FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-07-04 03:18
We think that this bug might be related to  #vip-vsb

**Comment by nkdengineer** [comment] 2024-07-04 04:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The row is not grayed out when added offline. This also applies to List values editor for List report field.

### What is the root cause of that problem?
We don't add the `pendingAction` field when we get the list report fields here


https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx#L67
### What changes do you think we should make in order to solve the problem?
We should add `pendingAction` here when we get the list report field to apply the gray out style when this report field is added/edited offline.



https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx#L67


https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/libs/actions/Policy/ReportFields.ts#L162-L164


### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-07-04 04:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Row is not grayed out when added/edited offline
### What is the root cause of that problem?
When creating a report field we are adding a `pendingAction` to `pendingFileds` of a policy with `fieldKey` here
https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/libs/actions/Policy/ReportFields.ts#L162-L163

But when creating a reportFieldList here and pass it selection list we are not including `pendingField `added to the policy as a 'pendingAction' prop
https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx#L67-L73
### What changes do you think we should make in order to solve the problem?
* Use Object.entries instead of Object.values 
* Then destructure the returned array to `[reportKey, reportField`
* Then add `pendingAction: policy?.pendingFields[reportKey] ?? null` below
https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx#L67-L73
### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-07-04 04:14
[Updated Proposal](https://github.com/Expensify/App/issues/44798#issuecomment-2208083255)
* Added video result

**Comment by techievivek** [comment] 2024-07-04 05:41
Adding a C+ so they can review the above proposals and help us fix this ASAP.

**Comment by mollfpr** [comment] 2024-07-04 06:54
Both proposal has the correct RCA, but the @etCoderDysto proposal has more detail for the implementation.

I'll suggest we go with @etCoderDysto [proposal](https://github.com/Expensify/App/issues/44798#issuecomment-2208083255).

🎀 👀 🎀 C+ reviewed!

**Comment by nkdengineer** [comment] 2024-07-04 07:04
@mollfpr I don't think we need more detail here, I also referred the way to get the pending action here.

https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/libs/actions/Policy/ReportFields.ts#L162-L164

**Comment by etCoderDysto** [comment] 2024-07-04 07:07
Raising a PR now.

**Comment by nkdengineer** [comment] 2024-07-04 07:09
@techievivek I believe my proposal is detail enough. I referred the way we add the pending field and I think it's enough to know how we can get this.

**Comment by mollfpr** [comment] 2024-07-04 07:55
>I don't think we need more detail here, I also referred the way to get the pending action here in my proposal.

Yeah, I understand that, but proposing a detailed solution is very helpful for the reviewer.

>We should add pendingAction here when we get the list report field to apply the gray out style when this report field is added/edited offline.

My weighing point is your solution doesn't have much information on how we can get the `pendingFields` into the mapping. I believe you already have the implementation in mind, but it would be great if you put more detail to understand the solution you proposing. A detailed solution is great and gives you a chance to win the issue.

**Comment by nkdengineer** [comment] 2024-07-04 08:05
> Yeah, I understand that, but proposing a detailed solution is very helpful for the reviewer.

@mollfpr Thanks for your feedback, I think this issue is straight forward and the implement detail (the way to get the `pendingFields`) is very simply so it can be done in the PR phrase. The detailer is good but I don't think it's not enough to make a proposal more weight in this case. If the issue is complex, I agree with that.

**Comment by etCoderDysto** [comment] 2024-07-04 13:28
@mollfpr [PR](https://github.com/Expensify/App/pull/44827) is ready for review

**Comment by luacmartins** [comment] 2024-07-04 20:20
Report fields is behind a [beta](https://github.com/Expensify/App/blob/55546bb6066fcc14a9005d512554e45c1d159166/src/CONST.ts#L363) and this is. a minor UI issue. Gonna remove the label.

**Comment by mountiny** [comment] 2024-07-05 09:14
Happy to take this over as I am leading the report fields configuration project

**Comment by mountiny** [comment] 2024-07-05 10:04
Noting $50 payment to @mollfpr for their help on this issue

**Comment by mountiny** [comment] 2024-07-05 13:08
@techievivek with @shubham1206agra and @rezkiy37 @waterim we have discussed handling the offline feedback differently than its done now https://expensify.slack.com/archives/C06ML6X0W9L/p1720172553875929?thread_ts=1719874235.982839&cid=C06ML6X0W9L and we are going to handle it in the report fields configation PRs from Callstack.

As such I think we can provide a partial compensation to @mollfpr and @etCoderDysto for their time $50 each

**Comment by techievivek** [comment] 2024-07-05 13:14
@mountiny sounds good to me. Thanks.

Payment summary:
$50 each to @mollfpr and @etCoderDysto, once payment is made, we close this out.
cc @zanyrenney

**Comment by JmillsExpensify** [comment] 2024-07-08 14:58
$50 approved for @mollfpr

**Comment by Christinadobrzyn** [comment] 2024-07-16 16:38
Hi @mollfpr can you check and see if this deploy blocker relates to this PR? https://github.com/Expensify/App/issues/45461

**Comment by mollfpr** [comment] 2024-07-16 16:44
cc @shubham1206agra https://github.com/Expensify/App/issues/44798#issuecomment-2231369866

**Comment by zanyrenney** [comment] 2024-07-19 13:17
bump @shubham1206agra can you review the comment above as this is being raised as a deploy blocker?

**Comment by zanyrenney** [comment] 2024-07-19 13:23
Ah great, thank you!

**Comment by zanyrenney** [comment] 2024-07-19 13:24
I'll move ahead with the payments in this case 🙇🏼

**Comment by zanyrenney** [comment] 2024-07-19 13:42
have asked @etCoderDysto to apply to job for payout

**Comment by zanyrenney** [comment] 2024-07-19 13:53
Ah okay that's not what the payment summary says: 
![2024-07-19_14-52-55](https://github.com/user-attachments/assets/a644157a-c6c9-460d-9a81-23975afffe03)

But happy to go with that then. I will close this one out!

**Comment by etCoderDysto** [comment] 2024-07-19 13:56
> [$50 approved for @mollfpr](https://github.com/Expensify/App/issues/44798#issuecomment-2214347781)

@zanyrenney  Only mollfpr is paid. I am not paid yet. 
And here is the payment summary 

> [$50 each to @mollfpr and @etCoderDysto, once payment is made, we close this out.
cc @zanyrenney](https://github.com/Expensify/App/issues/44798#issuecomment-2210859417)

**Comment by zanyrenney** [comment] 2024-07-19 14:09
Cool, payment summary:
@mollfpr requires payment through NewDot Manual Requests - paid via ND
@etCoderDysto requires payment (Needs manual offer from BZ) - paid $50 via UPwork.

**Closed by zanyrenney** 2024-07-19 14:09 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
