### ISSUE TITLE
[HOLD for payment 2023-06-12] [$1000] There is no current cell selection identifier on magic code input field once the field displays an error status

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19314] opened 2023-05-19 19:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to Sign in page
2. Enter email and click on 'continue' button
3. Enter a wrong magic code
4. Verify that magic code is marked red
5. Select one of the 6 cells to correct the error

## Expected Result: 
Green dash should be displayed on the selected cell to give feedback on which cell is selected
## Actual Result:  
No selection identifier is applied on the selected cell. Alp cells look the same

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fe326c55-a220-4705-b3f9-f90fee254673

https://github.com/Expensify/App/assets/43996225/45fa6d42-a9f6-4554-9b40-fc989bca4a36

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684314424188259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01975f5e132ef74741</li>
        <li>Upwork Job ID: 1661387113474609152</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by shawnborton** [comment] 2023-05-20 12:23
Why is no cursor being shown?

**Comment by shawnborton** [comment] 2023-05-20 14:15
That seems like a bug as well.

**Comment by shawnborton** [comment] 2023-05-22 10:30
But yeah, I would say we should fix the cursor issue first and start there. Perhaps we can even make the cursor red instead of green for these?

**Comment by anmurali** [comment] 2023-05-24 10:32
I am OOO, not sure why this got auto assigned to me. I am unassigning and rotating.

**Comment by slafortune** [comment] 2023-05-24 15:01
Looks good!

**Comment by PauloGasparSv** [comment] 2023-05-26 20:20
Not overdue! @mananjadhav can you please take a first look at @hoangzinh's [proposal](https://github.com/Expensify/App/issues/19314#issuecomment-1561466506) and let me know what you think?

**Comment by mananjadhav** [comment] 2023-05-27 14:21
I think @hoangzinh's proposal is good here. As soon as we update the digit it'll take the focused style.

**Comment by PauloGasparSv** [comment] 2023-05-29 20:32
> I think @hoangzinh's proposal is good here. As soon as we update the digit it'll take the focused style.

Sorry for the delay, missed this comment!

**Comment by mananjadhav** [comment] 2023-06-11 23:03
@slafortune This is ready for the payout today. Here's are the checklist items

1. Offending PR: https://github.com/Expensify/App/pull/18885
2. Commented on the PR: https://github.com/Expensify/App/pull/18885/files#r1225948462
3. I don't think any updates in the process are required or in the checklist. It's a miss. I would even classify this a feature request. We did add more than a few other behaviors related to button click and then the input focus.
4. I recommend to add a regression test. The test steps from the PR are detailed, and also iterated to cover all the fixes. I think we should use those for regression test.

**Comment by slafortune** [comment] 2023-06-13 17:15
Regression test GH created - 

Offers sent - @Natnael-Guchima @hoangzinh @mananjadhav

**Comment by mananjadhav** [comment] 2023-06-13 17:16
Thanks. Accepted @slafortune

**Comment by Natnael-Guchima** [comment] 2023-06-13 17:22
Accepted.  Thanks @slafortune

**Comment by slafortune** [comment] 2023-06-13 20:45
Paid!

**Closed by slafortune** 2023-06-13 20:45 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by shawnborton** [comment] 2023-07-18 11:12
Sorry to bring this back up again, but it looks like we still aren't showing a cursor in the magic code input boxes. I thought this issue would fix that? Any ideas?

**Comment by shawnborton** [comment] 2023-07-18 11:26
All of our inputs have a cursor in them:
<img width="165" alt="image" src="https://github.com/Expensify/App/assets/2319350/3614cd8f-235c-448c-b060-58b28c28f39a">

So these should as well. This helps you identify which cell you are in.

**Comment by shawnborton** [comment] 2023-07-18 16:58
[I left a comment above specifically asking](https://github.com/Expensify/App/issues/19314#issuecomment-1556971397) for the cursor to be fixed though. So I was anticipating that it would be included in this fix.
