### ISSUE TITLE
[$500] Category - Long category name pinned to the left margin and not has indented

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37446] opened 2024-02-28 17:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-11
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/37389
## Action Performed:
Precondition:
The user is an employee of Collect workspace
The Collect workspace has a long category name
1. Launch App
2. navigate to Workspace chat
3. Open the request money page
4. Tap on "Show more" > Category and scroll to Long Category to check it
4. Create a manual request and proceed to the confirmation page

## Expected Result:
Long category names should be shown for the entire line.
The long one should be indented too after "levels" (in this case)

## Actual Result:
Long category names are pinned to the left margin.
The long one doesn't have indented too after "levels" (in this case)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bd46efc3-f178-419c-9c59-df62881f8658

<img width="404" alt="Bug6395937_1709141208327!Screenshot_2024-02-28_at_10 33 10" src="https://github.com/Expensify/App/assets/78819774/8b81913e-be86-4282-8ec7-04e9b5862aac">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01467b731ab89b66e3</li>
        <li>Upwork Job ID: 1762895812871376896</li>
        <li>Last Price Increase: 2024-03-20</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-28 17:42
We think that this bug might be related to #wave6 
CC @greg-schroeder

**Comment by puneetlath** [comment] 2024-02-28 18:30
@neonbhai this is probably also a regression from your PR. I'm going to mark not a blocker, but let's definitely fix.

**Comment by ikevin127** [comment] 2024-02-29 09:53
Can't reproduce.

<img width="354" alt="Screenshot 2024-02-29 at 11 51 34" src="https://github.com/Expensify/App/assets/56457735/b8e7114e-af13-4dd4-9662-fb2e2ba18729">

**Comment by AndrewGable** [comment] 2024-03-04 18:44
@lanitochka17 - Can you please re-test and see if you can reproduce?

**Comment by lanitochka17** [comment] 2024-03-07 19:26
Issue is not reproducible


https://github.com/Expensify/App/assets/78819774/b5131cef-778f-4cd6-bf13-793c177d18e4

**Comment by mvtglobally** [comment] 2024-03-20 03:40
Issue not reproducible during KI retests. (First week)

**Comment by AndrewGable** [comment] 2024-03-20 22:27
Can reproduce so closing

**Closed by AndrewGable** 2024-03-20 22:27 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue
