### ISSUE TITLE
[HOLD for payment 2024-11-29] [$375] Card - Android - when user goes back to amount step in the flow the cursor is at the beginning instead of the end of the amount

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52029] opened 2024-11-05 11:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Login with account with expensify card enabled with bank account added, and few members invited in workspace
3. Go to workspace settings
4. Tap expensify card
5. Tap issue card
6. Select a user - physical card -monthly
7. Go to confirmation page
8. Navigate tapping app's back button
9. Note cursor shown at beginning at set limit page

## Expected Result:
We should always add the cursor to the end of the amount input field

## Actual Result:
When going back to the amount field, we put the cursor to the start of the amount which is bad UX

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/285fa6d5-23ba-474a-9399-ba0a6bf75e0c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854516214587143362</li>
        <li>Upwork Job ID: 1854516214587143362</li>
        <li>Last Price Increase: 2024-11-14</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 104952317</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by koko57** [comment] 2024-11-05 12:42
Should the value be cleared when we select another assignee? It was not something that was required in the docs. 
I think the form should be cleared only when we exit the flow or we submit the form to issue the card.
And I don't think it's something we would like to change - let's say we went to confirmation step - all the data is ok, but we want to change the assignee only - when we confirm that and we're redirected back to confirmation page the value would be empty. (I wonder if the error would appear, not sure about that). 
The only value we want to change in this case is the default card name (for physical card) to be updated to the newly selected user's name i.e. User's Card to NewUser's Card. It has been already implemented.

cc @mountiny

**Comment by mountiny** [comment] 2024-11-06 02:34
Good questions, I feel like we do not want to reset it, think that you want to go over the step back and to select different value in the previous step and then you continue to the amount again - I would want to keep the amount I already inserted.

@shawnborton do you agree with that expected results, hence close this issue?

**Comment by shawnborton** [comment] 2024-11-06 10:08
Yeah, I agree with your analysis Vit - I don't think we need to reset the limit in this stepped flow personally, I think it makes sense to keep it here. cc @Expensify/design just for visibility but I think they might agree?

**Comment by dannymcclain** [comment] 2024-11-06 14:19
I'm fine with not resetting the value, but isn't the bug that the cursor appears at the front of the amount instead of at the end? I guess it's really not that big of deal. Happy to go with whatever you all think is best!

**Comment by dubielzyk-expensify** [comment] 2024-11-07 01:17
Agree with not reseting it, but would also love to fix what Danny's mentioning to put the cursor at the end of the number input.

**Comment by mountiny** [comment] 2024-11-07 13:31
Agreed, updated the title and steps and we can await proposals. Thanks everyone for chiming in!

**Comment by mananjadhav** [comment] 2024-11-09 17:22
Still going through the issue and proposal.

**Comment by QichenZhu** [comment] 2024-11-14 01:30
@mananjadhav Could you help verify if [this commit](https://github.com/facebook/react-native/commit/ca0abd1b9ea164a566b39cb9090eaa75647aad5a) will resolve the issue?

**Comment by ikevin127** [comment] 2024-11-15 02:18
# Proposal

### Please re-state the problem that we are trying to solve in this issue

When going back to the amount field, we put the cursor to the start of the amount which is bad UX.

### What is the root cause of that problem?

Issue is still reproducible, happens only on Android native and is related to native code - the root cause being:

> On Android, when `ReactEditText` is attached to window, `setTextIsSelectable` moves the caret to the beginning.

This is the [code block](https://github.com/facebook/react-native/blob/74ed831a33d734def76b1a78ef8547c2f093133a/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L1072-L1076) which causes our issue.

### What changes do you think we should make in order to solve the problem?

The fix was merged on `react-native` side in PR https://github.com/facebook/react-native/pull/46948 but we don't know how long I will take until it makes it to the next `react-native` production release and also how long I'll take us to upgrade to that version.

> [!note]
> The fix is expected to make it into `react-native: 0.77` version release according to https://github.com/Expensify/App/issues/50055#issuecomment-2472022537.
> Current `react-native` version used by E/App is `0.75.2`.
> Current `react-native` version is `0.76.2`.

Until we reach the target `react-native` version with the fix, in order to fix the issue for our users, I suggest applying the following patch:

`react-native+0.77+001+ReactEditText.patch`

```diff
diff --git a/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java b/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
index ebd62e6dfa005a..87da1f00fc2d17 100644
--- a/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
+++ b/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
@@ -1053,12 +1053,18 @@ public void onStartTemporaryDetach() {
   public void onAttachedToWindow() {
     super.onAttachedToWindow();
 
+    int selectionStart = getSelectionStart();
+    int selectionEnd = getSelectionEnd();
+
     // Used to ensure that text is selectable inside of removeClippedSubviews
     // See https://github.com/facebook/react-native/issues/6805 for original
     // fix that was ported to here.
 
     super.setTextIsSelectable(true);
 
+    // Restore the selection since `setTextIsSelectable` changed it.
+    setSelection(selectionStart, selectionEnd);
+
     if (mContainsImages) {
       Spanned text = getText();
       TextInlineImageSpan[] spans = text.getSpans(0, text.length(), TextInlineImageSpan.class);
```

**Note**: This will also solve another issue which was put on hold for the `react-native` version upgrade which was not even released yet (`0.77`):
- https://github.com/Expensify/App/issues/50055

### What alternative solutions did you explore? (Optional)

Put the issue on HOLD and wait until Meta deploys the fix to production in version `0.77` and we get to the point where we will upgrade E/App's `react-native` to the version to that which includes the fix.

### Result video (before / after)

<details>
<summary>Android: Native</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/33425a37-bc0a-4fc2-bf84-d67119d9203b"> | <video src="https://github.com/user-attachments/assets/7774c289-71ef-43b6-bdd6-c0d2fcdd6bd2"> |

</details>

**Comment by mountiny** [comment] 2024-11-18 15:18
@ikevin127 @mananjadhav can you please make sure there are no regressions elsewhere in the product from this change? thanks!

**Comment by ikevin127** [comment] 2024-11-18 18:50
Will have a PR open in 1-2 hours.

**Comment by QichenZhu** [comment] 2024-11-18 18:55
@ikevin127 Just for your information, there is an additional related upstream commit https://github.com/facebook/react-native/commit/08759121cda3785e4d7ee1f1c82011a3e3a955a9. Please consider including it if you feel the need to do so.

**Comment by ikevin127** [comment] 2024-11-19 01:57
🚀 PR https://github.com/Expensify/App/pull/52734 is ready for review!

**Note**: I made sure to include the additional [related commit](https://github.com/Expensify/App/issues/52029#issuecomment-2483863161) to the patch, more details in the PR description.

**Comment by greg-schroeder** [comment] 2024-11-20 21:56
Looks ready to merge except for potentially a review by @shawnborton

**Comment by shawnborton** [comment] 2024-11-20 22:40
All good with me!

**Comment by ikevin127** [comment] 2024-11-22 02:46
♻️  **Status update**: PR was merged and deployed to staging yesterday and is now awaiting deploy to production!

**Comment by ikevin127** [comment] 2024-11-29 17:50
cc @muttmuure for visibility

**Comment by ikevin127** [comment] 2024-11-29 19:06
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by muttmuure** [comment] 2024-12-02 13:08
@ikevin127 - $375 C (Paid)
@mananjadhav - $375 C+

**Comment by ikevin127** [comment] 2024-12-04 20:21
Not overdue, this can be set to `Weekly` until the remaining payment is handled.

**Closed** 2024-12-10 12:53 UTC
Labels: External, Weekly, Design, Awaiting Payment, Bug
