### ISSUE TITLE
BA - App crashes after filling out forms offline and select 'Continue with setup'

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28467] opened 2023-09-29 12:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS App or Android App
2. Login with expensifail account
3. Got to existing workspace or create new one
4. Go to Workspace > Bank Account
5. Select 'Connect online with Plaid'
6. Follow the flow until 'Personal Information' page or 'Beneficial owner form'
7. Go Offline
8. Complete 'Personal Information' or 'Beneficial owner form'
9. Reload App
10. Go Online
11. Go to Workspace > Bank Account > Continue with setup

## Expected Result:
User successfully reaches 'Personal Information' page or 'Beneficial owner form'

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f6c19000-ca4b-4692-94c0-a1d7e0737634

https://github.com/Expensify/App/assets/78819774/2a51d09b-67d8-4324-9cbb-70f24865b381

https://github.com/Expensify/App/assets/78819774/4db9fa23-bf73-4b51-9c26-4839a8b7b0cc

[logs.txt](https://github.com/Expensify/App/files/12765045/logs.txt)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-09-29 17:53
Unable to reproduce on 1.3.75-3 on iOS

https://github.com/Expensify/App/assets/93399543/e82e04fe-cacc-4a81-8efe-a6a05827ea05

**Comment by mountiny** [comment] 2023-10-01 07:01
Fixed with the onyx change

**Closed by mountiny** 2023-10-01 07:01 UTC
Labels: Engineering, Hourly, Bug
