### ISSUE TITLE
[$250] Sending a message and then updating it with just "0", deletes the message - reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11366] opened 2022-09-28 04:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send any message e.g. "10"
3. Now edit the message to "0" and save changes

## Expected Result:
The message is updated to "0"

## Actual Result:
The message is deleted

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/192688051-98ba585d-45b6-47d1-b403-880951ac44a2.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663137426224319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment] 2022-09-29 22:40
What a stupid PHP bug, the problem is this [line](https://github.com/Expensify/Web-Expensify/blob/1e53bcea2ac5f9ba02eb0b696130bbcae600fe22/lib/ReportAPI.php#L462). It seems that in PHP:

```
>>> empty("0")
=> true
``

**Comment by pecanoro** [comment] 2022-10-07 19:55
This is in production already! We need to pay the bug bounty for reporting, so assigning a CME!

**Comment by pecanoro** [comment] 2022-10-07 19:58
@joekaufmanexpensify  We just need to pay the reporting bonus since we fixed it internally!

**Comment by joekaufmanexpensify** [comment] 2022-10-10 12:01
Looking into this today.

**Comment by joekaufmanexpensify** [comment] 2022-10-10 21:40
This is my first CME issue, so clarifying some questions [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1665437110890509).

**Comment by joekaufmanexpensify** [comment] 2022-10-11 18:38
Okay confirmed that next steps here are: 

1. Create the job in UW.
2. Hire the contributor (who reported).
3. Pay the contributor/close the job.

Working on that now!

**Comment by joekaufmanexpensify** [comment] 2022-10-11 18:46
[Posted](https://www.upwork.com/jobs/~013acf320257f79f73) in upwork!

**Comment by adeel0202** [comment] 2022-10-11 18:48
Thanks @joekaufmanexpensify. I have applied.

**Comment by joekaufmanexpensify** [comment] 2022-10-11 18:57
Sounds good. I just hired you, LMK when you've accepted!

**Comment by adeel0202** [comment] 2022-10-11 18:59
Accepted.

**Comment by joekaufmanexpensify** [comment] 2022-10-11 19:44
Payment sent!

**Comment by joekaufmanexpensify** [comment] 2022-10-11 19:45
Contract ended, posting removed

**Comment by joekaufmanexpensify** [comment] 2022-10-11 19:45
closing as this is all set!

**Closed by joekaufmanexpensify** 2022-10-11 19:45 UTC
Labels: Reviewing, Engineering, Daily, Improvement
