### ISSUE TITLE
Desktop - Offline - Error message while inviting user to the Workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10552] opened 2022-08-24 20:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Desktop App
2. Go to Setting - Workspace - Members
3. Turn off the network
4. Try to invite user to the workspace

## Expected Result:
Member should be added to the list and still present once device is online

## Actual Result:
Error message appears: "An error occurred inviting the user to the workspace, please try again"

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.89.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186515629-c88f5269-8c15-4a3e-bfe7-6add2e662d8c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment] 2022-08-24 22:21
Wait, is this a blocker? Is the refactor out for this?

Seems like offline handling will be handled in the refactor?

**Comment by ctkochan22** [comment] 2022-08-24 23:38
@arosiclair

**Comment by ctkochan22** [comment] 2022-08-24 23:56
@kbecciv How are you "turning the network off" specifically?

**Comment by kbecciv** [comment] 2022-08-25 01:25
@ctkochan22 Yes, QA team was following the steps in TR.

**Comment by ctkochan22** [comment] 2022-08-25 02:34
Okay. I was just wondering. I tried with using the Network tab in the developer console for desktop and wasn't able to reproduce. Let me try turning off the wifi

**Comment by ctkochan22** [comment] 2022-08-25 02:53
I'm unable to reproduce. Tried turning my computer wifi off. Button is working as expected. Disabled.
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/12980144/186563479-12b09832-ad11-4745-8466-a0c6caa7804d.png">

Can we try this out again?

**Comment by sketchydroide** [comment] 2022-08-25 07:54
I can't replicate this as well, in fact the green button is not even enabled while in offline mode

**Comment by roryabraham** [comment] 2022-08-25 07:59
Not able to reproduce this on desktop

**Comment by sketchydroide** [comment] 2022-08-25 08:00
Removing the blocker, @kbecciv can you please test again on the latest version

**Comment by neil-marcellini** [comment] 2022-08-25 08:09
I was able to reproduce on desktop staging v1.1.89-2

**Offline**
![image](https://user-images.githubusercontent.com/26260477/186610561-406df9bd-4039-4ff5-8d0d-ed51f9078e54.png)

**Back online**
![image](https://user-images.githubusercontent.com/26260477/186610628-36dc4f35-8aca-48dc-8971-1046eb459e9b.png)

**Comment by mountiny** [comment] 2022-08-25 08:33
I think this command is not using a new API yet:

https://github.com/Expensify/App/blob/e7503a0d1ec15d23661b534634524b4b809fd977/src/libs/actions/Policy.js#L322-L370

**Comment by arosiclair** [comment] 2022-08-25 17:29
> I think this command is not using a new API yet:

Yeah this is not supposed to work offline currently. However, the invite button should be blocked while offline to begin with. I was able to repro using **v1.1.91-0** and the offline indicator doesn't always appear when I disable Wi-Fi on my macbook:

![Screen Shot 2022-08-25 at 1 21 03 PM](https://user-images.githubusercontent.com/6833644/186731025-b63a2613-1909-4277-9b34-1f3ce969933e.png)

**Comment by ctkochan22** [comment] 2022-08-25 17:40
Looking at the PR in teh checklist, it could be the case on prod too?

**Comment by neil-marcellini** [comment] 2022-08-29 07:58
Since this is not expected to work offline and the only problem is that the invite button is not disabled, it sounds like the core issue is that the offline status is not detected. I'm closing this in favor of https://github.com/Expensify/App/issues/10524.

**Closed by neil-marcellini** 2022-08-29 07:58 UTC
Labels: Engineering, Weekly
