### ISSUE TITLE
[$500] Android - Report - When you tap on an email, a "New messages" banner appears

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27525] opened 2023-09-15 13:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a New Expensify app
2. Log in with any account
3. Navigate to any report
4. Send any valid e-mail address to the conversation
5. Tap the Compose Box to make the virtual keyboard active
6. Tap the sent email address

## Expected Result:
When you click on an email address with the keyboard open, the "New messages" banner should not appear

## Actual Result:
When you click on an e-mail address with the keyboard open, a "New messages" banner appears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/e6335cd3-b4e2-4d45-b9db-7860ab42558d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e9db11eb21d0150e</li>
        <li>Upwork Job ID: 1711883917812584448</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-10-10 23:18
Missed this during travel last month. I bet we're reseting the scroll position, and as a result, part of the most recent message is out of view. That said, I'll triage it and we can get ideas on what the solution looks like.

**Comment by MrMuzyk** [comment] 2023-10-13 12:43
@izarutskaya 
Hey, I am not able to reproduce that (See the recording). Can you confirm that the issues is still happening?


https://github.com/Expensify/App/assets/23487612/774c574d-02a8-4b7f-bd35-4070aacafbf1

**Comment by JmillsExpensify** [comment] 2023-10-24 22:33
Looks like we're not able to reproduce so closing as a result.

**Closed by JmillsExpensify** 2023-10-24 22:33 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
