### ISSUE TITLE
[HOLD #46835] [CRITICAL] Notification - User received desktop notification for a room a visited but didn't join

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#35000] opened 2024-01-23 20:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Version 1.4.26-1
**Reproducible in staging?:** Unknown
**Reproducible in production?:** Unknown
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705535848446499

**Updated details from [this thread](https://expensify.slack.com/archives/C05LX9D6E07/p1721941417016169?thread_ts=1721846381.961579&cid=C05LX9D6E07) on July 23rd**, inc. rVNP data and more logs. 

## Action Performed:
Precondition: user is part of a workspace that has at least a room that is visible in the workspace
**_Employee_**
1. Navigate to a workspace room but do not join the room
2. Navigate away

_**Another user or workspace admin**_
1. As the workspace admin or another user that is part of the workspace room - Send a message

@mallenexpensify reproduction steps: 
1. Days ago I visited #big-rig room in Expensify Chat workspace, I did not join the room nor was invited nor commented.

## Expected Result:
To not receive desktop/browser notifications when new posts are added to the room

## Actual Result:
User received a notification from the room that they did not join. 

## Workaround:
N/A 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/44479856/8cdc8f2b-2238-4a6c-9e5a-ad608d0a161b)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0125cf67df8d5a6dca</li>
        <li>Upwork Job ID: 1749887918200393728</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by abekkala** [comment] 2024-01-25 21:16
@mallenexpensify  Reproduced!

**Comment by mallenexpensify** [comment] 2024-01-27 17:05
@abdulrahuman5196 any reason you can think that this shouldn't be `External`?

**Comment by abdulrahuman5196** [comment] 2024-01-29 16:35
Sorry the delay. Will check and update before my morning.

**Comment by mallenexpensify** [comment] 2024-01-30 18:32
Just happened again. Got a notification which showed as from Sheena (didn't get screenshot), clicked the notification and it opened #expensipups.  
<img width="850" alt="image" src="https://github.com/Expensify/App/assets/22508304/02232808-9789-44e7-805a-db9603749d46">

@abdulrahuman5196 can you see if you can find a reproduce and provide the steps, if so?    Thx

**Comment by abekkala** [comment] 2024-02-01 19:41
@abdulrahuman5196 can you take a look here please and address?

**Comment by abekkala** [comment] 2024-02-06 20:00
@abdulrahuman5196 do you have an update?

**Comment by abekkala** [comment] 2024-02-08 18:41
@abdulrahuman5196 can you confirm if you were able to reproduce? Otherwise, we can close this out

**Comment by abdulrahuman5196** [comment] 2024-02-08 20:00
Checking again now

**Comment by abdulrahuman5196** [comment] 2024-02-08 20:16
@abekkala @mallenexpensify 
Nope still not able to reproduce. Only after joining I am getting notification

https://github.com/Expensify/App/assets/46707890/23daf37a-3550-491f-a4ac-def0a2897259

**Comment by mallenexpensify** [comment] 2024-02-09 22:32
@abekkala I'm gonna snag this one. I just visited #expensimemes but didn't join the room, and I want to test to see if I get notifications from it. 
<img width="841" alt="image" src="https://github.com/Expensify/App/assets/22508304/d0077de3-d8e2-4ad5-af2d-9c45c3f0726a">

**Comment by abdulrahuman5196** [comment] 2024-02-13 15:51
We are currently checking on reproducibility of the issue.

**Comment by mallenexpensify** [comment] 2024-02-21 01:41
Unsure if this is still happening, going to keep 👀 peeled for notifications for rooms I visited but didn't join.

**Comment by quinthar** [comment] 2024-02-24 01:19
Closing for now; please reopen if we experience it again

**Comment by mallenexpensify** [comment] 2024-07-26 21:31
Coming from this [internal thread, ](https://expensify.slack.com/archives/C05LX9D6E07/p1721846381961579)we're reopening. Updated title to `CRITICAL` assigned to Puneet and moved from #vip-vsb to #newdot-quality   project. I'll update the OP with recent details too

**Comment by mallenexpensify** [comment] 2024-07-26 23:02
Tested in #big-rig today.   
- Confirmed I wasn't a member of the room. 
- Viewed thread and confirmed I wasn't a member of the thread, didn't comment. 
- Got notification in LHN from a comment in the thread.

**Comment by puneetlath** [comment] 2024-07-30 00:44
Started a convo about the ideal solution here: https://expensify.slack.com/archives/C03TQ48KC/p1722285128976689

**Comment by muttmuure** [comment] 2024-08-06 14:58
Being worked on over here: https://github.com/Expensify/App/issues/46835

**Comment by puneetlath** [comment] 2024-08-14 19:55
Linked issue is still in progress.

**Comment by mallenexpensify** [comment] 2024-08-19 18:58
Checking on in the GH we're held on. 
- https://github.com/Expensify/App/issues/46835#issuecomment-2297234299

Hey... our 35,000 issue in this repo 🎉

**Comment by muttmuure** [comment] 2024-08-27 10:00
This PR https://github.com/Expensify/App/pull/47506 is on prod, so I think this issue is completely fixed now?

**Comment by mallenexpensify** [comment] 2024-08-27 17:25
Tested on latest staging build (Version 9.0.25-6), desktop, and confirmed it's fixed!

1. While logged into mallen@expensify.com, went to #justins-test-room, a room on Expensify Chat workspace
2. Didn't send a message or take other actions,
3. Pinged Justin 1:1 to post in the room and confirm when he had
4. Observed that I did **not** get a notification from his post and it doesn't show in LHN (Confirmed he sent the message too)

Couple questions...
1. Do we want a regression test for this?  Or will it take place as part of the below (which is the linked issue for the [PR that fixed this](https://github.com/Expensify/App/pull/47506).)? I'm posting on that issue to check too.  
- https://github.com/Expensify/App/issues/46835 

2. @abdulrahuman5196 , I don't _think_ you're due compensation here, comment if you disagree.

**Comment by mallenexpensify** [comment] 2024-08-30 23:55
Think we're all set here, so closing. 
If we need a regression test, this will get commented on (per [here](https://github.com/Expensify/App/issues/46835#issuecomment-2322609129))  and I'll reopen.

**Comment by puneetlath** [comment] 2024-09-03 18:04
Actually @mallenexpensify I think it'd be good to create a regression test specifically for that case here.

**Comment by mallenexpensify** [comment] 2024-09-04 14:43
@abdulrahuman5196 , plz complete the BZ checklist since we want a test for this.  Thx for chiming in Puneet. 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by mallenexpensify** [comment] 2024-09-04 21:03
@ishpaul777 , 👀 above please.  Also, I'm assuming payment isn't due on this issue and that you'll manage that in[ the main one.](https://github.com/Expensify/App/issues/46835)  Thx

**Comment by mallenexpensify** [comment] 2024-09-07 00:13
Thanks @ishpaul777 , test case created
- https://github.com/Expensify/Expensify/issues/426642

**Comment by muttmuure** [comment] 2024-09-10 09:04
This is still happening as reported here: https://expensify.slack.com/archives/C05LX9D6E07/p1725908484386969?thread_ts=1725899304.608239&cid=C05LX9D6E07

@shubham1206agra could you let us know when your fix is ready?

**Comment by mallenexpensify** [comment] 2024-09-11 21:35
@puneetlath  I'm out til Tuesday, can you keep 👀 on plz? You're already assigned, have context and you're a BZ, so it _makes sense_ to me to not rando-assign to another BZ.

**Comment by mallenexpensify** [comment] 2024-09-17 22:00
Closing, just checked Desktop and haven't seen any notifications/messages from rooms I haven't joined.  Thx @ishpaul777

**Closed by mallenexpensify** 2024-09-17 22:00 UTC
Labels: Engineering, Daily, Internal, Bug
