### ISSUE TITLE
[HOLD for payment 2023-09-08] Use current location waypoint editor button

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22707] opened 2023-07-11 21:33 UTC
Please follow the [plan in the design doc](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.f54rb8cmd9f7).

**Comment by hayata-suenaga** [comment] 2023-08-21 16:57
assigning myself to this issue and labeling the issue back to weekly

**Comment by tgolen** [comment] 2023-08-23 21:34
This is off hold and I'm bumping up to daily

**Comment by hayata-suenaga** [comment] 2023-08-24 14:35
Created an App issue for this: https://github.com/Expensify/App/issues/25855

**Comment by hayata-suenaga** [comment] 2023-09-01 21:23
The location PR has been reverted and the original contributor that made the PR is working on the second PR that includes fixes for all regressions.

**Comment by hayata-suenaga** [comment] 2023-09-11 03:18
Closing this issue because this is a dupe of [this issue](https://github.com/Expensify/App/issues/25855).

**Closed by hayata-suenaga** 2023-09-11 03:18 UTC
Labels: Engineering, Weekly, Overdue
