### ISSUE TITLE
[Distance rates] Workspace - More features: Distance rates are not updating on a second device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38309] opened 2024-03-14 13:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions: Be part of a Control workspace with WS chat enabled
1. Log in as the admin
2. Navigate to Settings - Workspace - More features
3. Navigate to Settings - Workspace - More features on a secondary device with the same account
4. On the main device, toggle Distance rates on
5. Refresh the page or navigate back and to the More features again on the secondary device

## Expected Result:
It should be updating

## Actual Result:
More features: Distance rates are not updating on a second device

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/aa0db9fb-7138-4b16-a626-94c2ad6b2164

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a8735aee06fa7fe</li>
        <li>Upwork Job ID: 1768645210778124288</li>
        <li>Last Price Increase: 2024-03-15</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-14 13:59
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by lanitochka17** [comment] 2024-03-14 13:59
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CortneyOfstad** [comment] 2024-03-14 14:57
@lanitochka17 I checked out the video and i don't see the second device. Can they provide a secondary video showing the updating not happening between both devices using Safari? The uploaded video only shows the tail end of the process and only one device. Thanks!

**Comment by trjExpensify** [comment] 2024-03-14 18:28
Popping it in with no status while you investigate that, Cortney! CC: @mountiny for vis

**Comment by CortneyOfstad** [comment] 2024-03-15 13:55
@lanitochka17 can you provide an update on the comment [here](https://github.com/Expensify/App/issues/38309#issuecomment-1997655433) by EOD? Thanks!

**Comment by mountiny** [comment] 2024-03-15 14:27
Its internal I can handle it, I see where the problem is we changed the name of the variable last minute

**Comment by mountiny** [comment] 2024-03-15 14:31
PR is up

**Comment by mountiny** [comment] 2024-03-15 14:32
Updated the flag in all places missed in the Doc too

**Comment by CortneyOfstad** [comment] 2024-03-15 16:42
Thanks @mountiny!

**Comment by mountiny** [comment] 2024-03-18 11:09
PR is merged, this can be closed

**Closed by mountiny** 2024-03-18 11:09 UTC
Labels: Daily, Internal, Overdue, Bug
