### ISSUE TITLE
[Regression test steps needed]  Border Radius of Popover Menu is incorrect

### ISSUE THREAD

**Issue by Luke9389** [Expensify/App#13213] opened 2022-11-30 21:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

There are two issues:
1. Mini Menu

 - Sign into the app
 - Hover over any message
 - Note that the mini menu looks like this: 
<img width="163" alt="Screen Shot 2022-11-30 at 1 13 35 PM" src="https://user-images.githubusercontent.com/49007721/204909414-5f38b348-d76a-46e8-9237-5123ee8eb55e.png">

2. Link Popover
 -  - Sign into the app
 - Hover over any link
 - Note that it looks like this: 
<img width="373" alt="Screen Shot 2022-11-30 at 1 13 52 PM" src="https://user-images.githubusercontent.com/49007721/204909553-c40f39d5-3aab-4b6d-90d0-b2d5d1879e31.png">

## Expected Result:
Describe what you think should've happened

The border radius for the mini menu should have it appear circluar.

The boarder radius for the link popover should not be a pill shape. 

## Actual Result:
Describe what actually happened

They're both the opposite of the Expected Results.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01cf116c84fb1d9f8a
- Upwork Job ID: 1598266635308433408

**Comment by Luke9389** [comment] 2022-11-30 21:17
Hey @zanyrenney, sorry for the noise, I'm just going to fix this one up real fast.

**Comment by parasharrajat** [comment] 2022-11-30 21:21
Can I be reporter of this as I reported it here https://expensify.slack.com/archives/C049HHMV9SM/p1669645639980109?

**Comment by Luke9389** [comment] 2022-11-30 21:47
Actually @zanyrenney would you be willing to pay out @parasharrajat for reporting this issue?

**Comment by zanyrenney** [comment] 2022-12-01 10:43
Yep, let me mark this as external so it creates the Upwork issue.

**Comment by zanyrenney** [comment] 2022-12-01 10:47
@parasharrajat have invited you to the job on upwork.

**Comment by parasharrajat** [comment] 2022-12-01 10:57
Thanks, @zanyrenney. Please assign me to the issue as well because I am reviewing the PR.

**Comment by sunshine-super** [comment] 2022-12-01 16:31
1. Mini Menu
  When hovering over a message, you can give the border-radius of the object in css.
  
   Example: 
   `.message:hover {
    border-radius: 100px
   }`
2. Link Popover
   You can add popover function by using plugins like bootstrap.

**Comment by parasharrajat** [comment] 2022-12-05 08:05
Can someone add Reviewing label?

**Comment by zanyrenney** [comment] 2022-12-05 10:16
Added that @parasharrajat - thanks!

**Comment by zanyrenney** [comment] 2022-12-21 18:00
Heading OOO so reassigning to get @parasharrajat 's questions answered and paid out.

**Comment by mallenexpensify** [comment] 2022-12-24 00:50
@parasharrajat , I'm helping get issues paid around holidays, how much are you due for this?

**Comment by mallenexpensify** [comment] 2022-12-26 19:24
Thanks @parasharrajat , I'm assuming you meant you're due $1250 in total so I bonused you $1000 to get there.  

@slafortune you or I need to do the regression test.  I'll try to get to this week

**Comment by mallenexpensify** [comment] 2022-12-26 23:32
- Bug:  (Dark Theme) Mini menu hover style is not correct.
- Bug:  (Dark Theme) Padding of multi line tooltip does not look correct.

I can't remember if we ever settled on when to pay for multiple bug reports that are fixed by the same PR.  What we want to avoid is contributors reporting a bunch of variations on the same bug, knowing that it _might_ be fixed by one PR.      @parasharrajat , would you say.... 
1. You or another engineer might or should have known the bugs were related?
2. The two bugs _could_ have been fixed separately but you were able to combine them into one to _make things easier_?

**Comment by mallenexpensify** [comment] 2022-12-27 17:34
Paid @parasharrajat $250, it appears to be an edge case where we chose to fix two bugs in one issue/PR.  

@parasharrajat  @Luke9389 , can you complete the BZ checklist above plz?
https://github.com/Expensify/App/issues/13213#issuecomment-1349861728

**Closed** 2023-01-12 20:12 UTC
Labels: Reviewing, Weekly, Internal, Awaiting Payment, Bug
