### ISSUE TITLE
[Pay 4/29][$500] Wallet - No error when clicking Save & continue button after selecting BA with existing draft

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38518] opened 2024-03-18 20:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > any workspace.
3. Go to Bank account > Connect manually.
4. Add the following bank account (important):
Routing number - 011401533
Account number - 1111222233331111
5. Proceed the setup and quit in the middle of it (by clicking outside RHP).
6. Go to Wallet > Add bank account > Personal bank account.
7. Add any bank account and select Plaid Saving account (ends with 1111).
8. Click Save & continue.

## Expected Result:
App should present an error about unable to proceed with Plaid Saving account (ends with 1111) since there is draft in Step 5.

## Actual Result:
There is no error when clicking Save & continue. Nothing happens when clicking on the button.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/78045ca3-1f78-4b47-8bfc-2c0576f4ac03

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183d2c7f9a0e1aa53</li>
        <li>Upwork Job ID: 1772399631405613056</li>
        <li>Last Price Increase: 2024-03-25</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-18 20:58
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment] 2024-03-18 20:58
@MitchExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment] 2024-03-19 05:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The add personal bank account page doesn't show an error and just looks like do nothing when pressing the button.

### What is the root cause of that problem?
When we press the save button, we actually request the BE to try saving it, and BE already returns the correct error message for us to show.

However, the add personal bank account form has a different key than the BE response. The BE response merges the errors to `personalBankAccount`, but the form has a key of `personalBankAccountForm`.
https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/pages/AddPersonalBankAccountPage.tsx#L82-L83
https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/ONYXKEYS.ts#L408

This happens after this [TS migration PR](https://github.com/Expensify/App/pull/34430) which unnecessarily changes the key.

If we look at the bank account step pages, we can see that they don't add `form` suffix to the key.
https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/pages/ReimbursementAccount/BankInfo/substeps/Manual.tsx#L63-L64
https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/ONYXKEYS.ts#L406

### What changes do you think we should make in order to solve the problem?

Remove the `form` from `ONYXKEYS.FORMS.PERSONAL_BANK_ACCOUNT` and `PERSONAL_BANK_ACCOUNT_DRAFT`

But after fixing this, we will see the error message shown is still incorrect and this is a separate issue that is being handled [here](https://www.github.com/Expensify/App/issues/37623)
<img width="378" alt="image" src="https://github.com/Expensify/App/assets/50919443/b2c53344-c214-4cc9-b0e8-1609927bfeb8">

Result after fixing all:

https://github.com/Expensify/App/assets/50919443/dab31bde-0a0b-4523-b3bd-c7e7ba5a2de1

**Comment by MitchExpensify** [comment] 2024-03-19 16:27
Assigning to VSB as this is a personal account issue more in line with off workspace use

**Comment by cubuspl42** [comment] 2024-03-26 08:43
@bernhardoj 

> This happens after this [TS migration PR](https://github.com/Expensify/App/pull/34430) which unnecessarily changes the key.

Ouch, I reviewed that one.

Honestly, I don't understand how this is a regression. The old JS code didn't include the `'personalBankAccount'` string. The whole diff doesn't include such a string. Could you explain it in more depth?

**Comment by bernhardoj** [comment] 2024-03-26 08:51
Sure, in the [old code](https://github.com/Expensify/App/pull/34430/files#diff-9752e429800913db3c97933de857c756e067076a13b9a4fd30666cab039d8dbfL116-L117), we use `ONYXKEYS.PERSONAL_BANK_ACCOUNT` as the form ID.
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/ONYXKEYS.ts#L206

But the PR replaces it with `ONYXKEYS.FORMS.PERSONAL_BANK_ACCOUNT` which has the `Form` suffix.

**Comment by cubuspl42** [comment] 2024-03-26 09:00
I'm not defending the code that introduces the regression, but it's worth noting that all keys in the `ONYXKEYS.FORMS` subobject have the same `fooForm` / `fooFormDraft` naming.

Could you comment on that? Is this a bigger problem (affecting the whole `ONYXKEYS.FORMS`), or do we have a single case that should opt-out from the naming convention because of the existing, older backend code?

**Comment by cubuspl42** [comment] 2024-03-26 09:01
We should definitely figure this out. Right now, both the `ONYXKEYS.PERSONAL_BANK_ACCOUNT` and  `ONYXKEYS.PERSONAL_BANK_ACCOUNT` keys exist.

**Comment by bernhardoj** [comment] 2024-03-26 09:24
Not all follow the `form`/`formDraft` naming, for example, these two:
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/ONYXKEYS.ts#L358-L359
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/ONYXKEYS.ts#L352-L353
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/ONYXKEYS.ts#L418-L419

(I think the tax name could use `form` naming though)

My guess is, that we can't use the `form` naming if the form relies on BE validation before able to continue, for example, close account page and our case.

**Comment by cubuspl42** [comment] 2024-03-26 10:21
You're right. Thanks for the extra clarification.

I approve the proposal by @bernhardoj

**Comment by MitchExpensify** [comment] 2024-03-27 03:56
I'm not sure why automation is not assigning an internal engineer to review the assignment of @bernhardoj

**Comment by bernhardoj** [comment] 2024-03-27 03:57
I think @cubuspl42 forget to put the "magic" word

**Comment by cubuspl42** [comment] 2024-03-27 08:55
Sorry!

I approve the proposal by @bernhardoj

Wait for it... 🥁

C+ reviewed 🎀 👀 🎀

**Comment by MitchExpensify** [comment] 2024-03-28 21:53
Nice, how does the proposal look to you @Gonals ?

**Comment by MitchExpensify** [comment] 2024-04-01 19:39
Friendly bump @Gonals :)

**Comment by Gonals** [comment] 2024-04-02 09:01
Looks good!

**Comment by bernhardoj** [comment] 2024-04-02 10:46
PR is ready

cc: @cubuspl42

**Comment by MitchExpensify** [comment] 2024-04-25 21:33
Reminder set to pay on 4/29

Payment summary:

$500 Contributor @bernhardoj

**Comment by MitchExpensify** [comment] 2024-05-06 19:56
Paid and contract ended, apologies for the delay

**Closed by MitchExpensify** 2024-05-06 19:56 UTC
Labels: External, Daily, Awaiting Payment, Bug
