### ISSUE TITLE
[HOLD for payment 2022-12-20] Dev: TypeError on dev when workspace settings forms are opened

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13344] opened 2022-12-05 23:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Workspace settings.
2. Click on “General settings.”

Alternately,

1. Go to Workspace settings.
2. Click on “Connect bank account.”
3. Click on “Connect manually.”

## Expected Result:
Form is opened normally

## Actual Result:
Console error on desktop, full page blocking error on iOS (dev) and Android (dev)

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/205765162-1deeebff-27ed-4682-a41c-e10aff8feefa.png" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @dangrous 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670273493519649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01302e69a126221869</li>
        <li>Upwork Job ID: 1605268377985359872</li>
        <li>Last Price Increase: 2022-12-20</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2022-12-05 23:45
I can reproduce this and I'm working on a fix

**Comment by luacmartins** [comment] 2022-12-13 23:17
We are good to close this one since there's no payment needed!

**Comment by mananjadhav** [comment] 2022-12-20 10:33
@luacmartins There will be payment for the C+ review on PR https://github.com/Expensify/App/pull/13348. Can you help with the same?

**Comment by luacmartins** [comment] 2022-12-20 17:08
@mananjadhav thanks for bringing that up to my attention. Sorry that I missed that.

@maddylewis the only thing left to do here is pay @mananjadhav for [this PR review](https://github.com/Expensify/App/pull/13348). Could you help us with that?

**Comment by maddylewis** [comment] 2022-12-20 17:57
yes! let me do that now.

**Comment by maddylewis** [comment] 2022-12-20 18:28
okay, @mananjadhav - can you apply to the job and then i will process payment :)

**Comment by mananjadhav** [comment] 2022-12-20 18:40
Applied @maddylewis

**Comment by maddylewis** [comment] 2022-12-20 19:42
payment sent!

**Comment by maddylewis** [comment] 2022-12-20 20:12
ill go ahead and close this out. if there were any issues receiving payment, feel free to reopen and let me know - thanks, @mananjadhav !

**Closed by maddylewis** 2022-12-20 20:12 UTC
Labels: Reviewing, Engineering, Daily, Internal, Awaiting Payment, Bug

**Comment by mananjadhav** [comment] 2022-12-21 02:18
Received the payment. Thanks @maddylewis for the help here.
