### ISSUE TITLE
Web - No margin between 'Completed task' and title with a long name (works well on shorter title names))

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22143] opened 2023-07-03 21:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Click on FAB icon and click on assign task
3. Enter a very long title and select a assignee and create a task
4. On the task page, mark it as done
5. Notice that there's no margin or padding between the 'Completed task' and 'longer title name'
6. Now follow the same process with shorter assign task title and notice for shorter task there's a small gap between the 'Completed task' and 'Title name' which looks perfect

## Expected Result:
Margin between 'Completed task' and title with a long name

## Actual Result:
No margin between 'Completed task' and title with a long name (works well on shorter title names))

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/db7771d8-ca1c-4295-a694-2f024bbe6f8a

https://github.com/Expensify/App/assets/93399543/cb519e2c-0b0f-40a7-9f1a-b96d5008cafa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688307593566799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-07-03 21:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

No margin between 'Completed task' and title with a long name

### What is the root cause of that problem?

We're now spacing the text(completed task) and title with space character
https://github.com/Expensify/App/blob/3b687018c3d907f1bcdea8f9a4a8cae90101959f/src/components/ReportActionItem/TaskAction.js#L60

When the title gets longer, it'll be splitted into several lines and the first space character doesn't work

This is the root cause

### What changes do you think we should make in order to solve the problem?

We can remove the space character and add gap to the parent view

```
    <View style={[styles.flex1, styles.flexRow, styles.alignItemsCenter, styles.gap1]}>
        <Text style={styles.chatItemMessageLink}>{messageLinkText}</Text>
        <Text style={[styles.chatItemMessage]}>{`${taskReportName}`}</Text>
    </View>
```

This works as expected.

<details>
    <summary>Result</summary>

![image](https://github.com/Expensify/App/assets/126839717/dde1a81e-d9e9-45ba-bcf3-c024bd2a123e)

</details>

### What alternative solutions did you explore? (Optional)

**Comment by conorpendergrast** [comment] 2023-07-04 12:32
I think it looks so weird with the "completed task" wrapped. This should be flowing like a sentence, not like a table. 

eg: 
**completed task** Now follow the same process with shorter assign task title and notice for shorter task there's a small gap between the 'Completed task' and 'Title name' which looks perfect

Rather than: 
| |  |
| ------------- | ------------- |
| completed task  | Now follow the same process with shorter assign task title and notice for shorter task there's a small gap between the 'Completed task' and 'Title name' which looks perfect |

**Comment by conorpendergrast** [comment] 2023-07-04 12:53
Oh, however, similar to [this issue](https://github.com/Expensify/App/issues/22030#issuecomment-1618991773), given [this task detailed view redesign](https://github.com/Expensify/App/issues/19330), I think we're not planning on addressing new fixes for the task detailed view.

**Comment by conorpendergrast** [comment] 2023-07-07 11:54
Ok, we're closing this out without the bug bounty, because the redesign is already in the works. Closing!

**Closed by conorpendergrast** 2023-07-07 11:54 UTC
Labels: Daily, Overdue, Bug
