### ISSUE TITLE
Dev: Web - Deleted workspace still show in the create room dropdown until we refresh the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22446] opened 2023-07-07 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace
2. Create a room and see new workspace in the dropdown
3. Go back and delete the workspace
4. Create the room again, and check the workspace dropdown
5. Reload the page and repeat step 4

## Expected Result:
Deleted workspace should not be shown

## Actual Result:
Describe what actually happened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.36-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c1eb8356-53ab-4121-81a7-1a7edb516e73

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688720860777589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2023-07-10 14:00
Not overdue

**Comment by joekaufmanexpensify** [comment] 2023-07-10 18:59
Also unable to reproduce this. Clarifying in thread.

**Comment by joekaufmanexpensify** [comment] 2023-07-10 19:45
We discussed in the thread and confirmed this is no longer reproducible. Closing as this is all set!

**Closed by joekaufmanexpensify** 2023-07-10 19:45 UTC
Labels: Daily, Needs Reproduction, Bug
