### ISSUE TITLE
Scan - receipt thumbnail is not shown due to a cors policy error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39056] opened 2024-03-27 13:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open a new Gmail account
2. Click on FAB > request money > Scan > upload a receipt that will not fail
3. While on the participants page input 2 new email addresses you did not have history with
4. Confirm the request and wait for the scan to finish
5. Once the scan has finished open the console and click on the split preview component to open the RHP

## Expected Result:
The receipt thumbnail should load

## Actual Result:
The receipt thumbnail does not load due to a cors policy error:
Access to fetch at 'https://www.expensify.com/receipts/w_850728b68d65c07f20d99f83e4b91b01ee49d238.jpg.1024.jpg'
from origin 'https://staging.new.expensify.com'/
has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a608af86-1bec-4a0b-8ced-3860e855837d

![Wallmart Receipt](https://github.com/Expensify/App/assets/78819774/900e1fac-f791-4ef7-a5ae-85880c573b52)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2024-03-28 10:41
@kidroca @aimane-chnaif this looks related to our image caching PR - i wonder if there's an `isAuthTokenRequired` missing somewhere?

**Comment by Beamanator** [comment] 2024-03-28 10:44
Def good questions 🤷  you're right, this could be unrelated

**Comment by Beamanator** [comment] 2024-03-28 15:33
Hmm I can't reproduce this issue

**Comment by Beamanator** [comment] 2024-03-28 15:40
I haven't been able to reproduce and I can see receipt images everywhere at the moment so I think we can call this NAB for now & keep this open a bit in case applause can reproduce

**Comment by Beamanator** [comment] 2024-04-09 08:15
Waiting for applause to re-test to see if this is still a bug or not

**Comment by mvtglobally** [comment] 2024-04-12 05:38
Issue is reproducible during KI retests. 

https://github.com/Expensify/App/assets/43995119/e59a81bf-5520-4716-834a-81abaced92c7

**Comment by anmurali** [comment] 2024-04-17 01:43
Waiting for scan to complete. Will update once it does.

**Comment by Beamanator** [comment] 2024-04-19 19:24
i'm gunna guess we can close this

**Closed** 2024-04-22 09:04 UTC
Labels: Engineering, Daily, Overdue, Bug
