### ISSUE TITLE
[$250] Expense - Mark as unread green line for one transaction is not shown initially

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50568] opened 2024-10-10 13:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.47-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a workspace chat
3. Submit an expense
4. Open the expense
5. Select a category
6. For category selected system message is displayed below, mark it as unread
7. Note new green line not displayed
8. Long press the message and open reply in thread
9. Note you can check new green line in thread page
10. Tap from link and now note for category selected system message, green line displayed now

## Expected Result:
Mark as unread green line for one transaction must be shown initially before opening reply in thread page

## Actual Result:
Mark as unread green line for one transaction is not shown initially before opening reply in thread page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/0b756d09-17e1-43eb-a505-2579e0b9f6be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846309887749659812</li>
        <li>Upwork Job ID: 1846309887749659812</li>
        <li>Last Price Increase: 2024-12-24</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-10-10 13:13
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment] 2024-10-16 09:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mark as unread green line for one transaction is not shown initially before opening reply in thread page

### What is the root cause of that problem?

When users go to one transaction report, we will open iou report and combine the actions from iou report and transaction thread report 

https://github.com/Expensify/App/blob/96ffbfe27c5c1b85b062e6ab50c0adc46b0e94c3/src/pages/home/report/ReportActionsView.tsx#L213

Here is the logic to get unread report action id

https://github.com/Expensify/App/blob/96ffbfe27c5c1b85b062e6ab50c0adc46b0e94c3/src/pages/home/report/ReportActionsList.tsx#L219-L222

we use `unreadMarkerTime` from `report.lastReadTime`

https://github.com/Expensify/App/blob/96ffbfe27c5c1b85b062e6ab50c0adc46b0e94c3/src/pages/home/report/ReportActionsList.tsx#L209

The `report` here is iou report

When users press mark as unread the `category selected system` message, we call `markAsUnread` API, this API will update `report.lastReadTime`, but the updated report is transaction thread report since this message comes from transaction report, not iou report

That why the logic to get `unreadMarkerReportActionID` is not triggered

There's one more issue when we open iouReport for one transaction:

If users add new messages, they would expect to add them in thread report, but they're actually added in iou report -> That causes the confusion


https://github.com/user-attachments/assets/78e9aae9-3ede-4586-a0b2-f40d12b6432f


### What changes do you think we should make in order to solve the problem?


We should go to the transaction report if there'e one transaction

Update [this line](https://github.com/Expensify/App/blob/5cf3d196bde3c364160f7eb8d5be5a9a26c303eb/src/components/ReportActionItem/ReportPreview.tsx#L445) to

```
const transactionThreadReportID = ReportActionsUtils.getOneTransactionThreadReportID(iouReportID ?? '', ReportActionsUtils.getAllReportActions(iouReportID), isOffline);
Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(transactionThreadReportID ?? iouReportID));
```

We also need to update the header to back to ws/1:1 chat

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-10-17 03:27
@dukenv0307 As you can see here's the expense report with one transaction. It's actually the UI of transaction thread report, so I believe when users add new comments here, they would like to add them in transaction report instead of iou report. 


<img width="1026" alt="Screenshot 2024-10-17 at 10 14 02" src="https://github.com/user-attachments/assets/40a08797-7348-4184-8264-bab219b88421">

Furthermore, opening transaction report can make our implementation clearer since we're combining 2 reportActions, but just the actions from transaction thread are shown at the beginning -> Users should realize it's the transaction report

**Comment by shawnborton** [comment] 2024-10-17 08:04
We don't want to change anything about how the transaction or report is displayed. Let's just try to address the fact that the unread marker isn't showing up as it should. But perhaps I am not understanding correctly, so feel free to rephrase if needed :)

**Comment by truph01** [comment] 2024-10-17 09:10
>  Let's just try to address the fact that the unread marker isn't showing up as it should

That because we're showing the iou report, but the action is transaction report

**Comment by thienlnam** [comment] 2024-10-17 23:45
Will let @NikkiWines chime in here, but I am not sure we want to change the view to just the transaction directly. I feel like the intention was to consolidate the one-expense chat experience but anything that happens there is still part of the "report"

**Comment by shawnborton** [comment] 2024-10-18 06:32
Yeah, we definitely do not want to change the view. We need to fix the unread marker without changing anything about the view itself.

**Comment by truph01** [comment] 2024-10-18 10:42
@shawnborton No, I don't want to change the view itself, just change the reportID in the URL cc @NikkiWines

**Comment by truph01** [comment] 2024-10-18 10:56
As you can see in the below video, iou report (first report) has the same view as transaction report (second one). Currently we're showing iou report, so I would like to show transaction report and update the header to be the same as iouReport.

https://github.com/user-attachments/assets/8b4491f7-8662-434d-82a8-2b88d7b986d5

**Comment by shawnborton** [comment] 2024-10-18 13:33
Curious what our engineers think about that. I'm mostly just chiming in from a design perspective that we need to keep the view looking exactly the same but add the ability to have the correct unread/new marker here.

**Comment by dannymcclain** [comment] 2024-10-18 13:35
>Curious what our engineers think about that. I'm mostly just chiming in from a design perspective that we need to keep the view looking exactly the same but add the ability to have the correct unread/new marker here.

+1. It would be great to get some engineering perspectives on this—I feel like there was a fair bit of discussion around how to handle the whole report thread vs transaction thread when we initially implemented this consolidated view.

**Comment by NikkiWines** [comment] 2024-10-18 14:54
> Furthermore, opening transaction report can make our implementation clearer since we're combining 2 reportActions, but just the actions from transaction thread are shown at the beginning -> Users should realize it's the transaction report

This was originally proposed as a flow for the one-transaction view when we first discussed how to implement it way back when, but ultimately the implementation went a different way and opted to combine the view on the IOU report level instead. I don't think we want to change this now (though I'm not opposed to revisiting the need for this view), and so I don't think changing the reportID is the correct route here. 

The intended behavior based on the design brief is that we show the IOU report, and pull in parts of the transaction thread (the ability to select categories, displaying transaction thread report actions, etc.) for a more comprehensive view. However, the location of where those actions occur stay on their requesite reports. If the user changes the category, that's a transaction-level action and the reportAction is ultimately created on the transactionThread. If they comment on the IOU report (even while the view is combined for the one-transaction view) that comment should exist on the IOU report level. 

To me, it sounds like we need to check the `report.lastReadTime` for both the IOU report and transaction thread report to determine if the unread indicator needs to be displayed on the combined view.

**Comment by johncschuster** [comment] 2024-10-28 21:57
Raised this in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1730152607551359) for proposals

**Comment by johncschuster** [comment] 2024-10-28 22:02
bump

**Comment by klajdipaja** [comment] 2024-10-29 10:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we mark unread a message in a transaction the unread marker line does not show up on the message immediately but only after the user leaves the thread and returns to it.

### What is the root cause of that problem?
When the user marks as unread a message a backend action is triggered that updates the lastReadTime of the report and we subscribe to the result of that call in this block https://github.com/Expensify/App/blob/2463bf74b4edabdde887636f7874fdbbfcf9eb2c/src/pages/home/report/ReportActionsList.tsx#L270-L283

For transaction threads the reportId that is used for the action is not the one of the parent but the one of the action itself and since we are using reportId of the chat then we are not getting the result of the API call.
To fix that we need to add subscriptions for the transaction thread as well:

```
   useEffect(() => {
        const unreadActionSubscription = DeviceEventEmitter.addListener(`unreadAction_${report.reportID}`, (newLastReadTime: string) => {
            setUnreadMarkerTime(newLastReadTime);
            userActiveSince.current = DateUtils.getDBTime();
        });
        const readNewestActionSubscription = DeviceEventEmitter.addListener(`readNewestAction_${report.reportID}`, (newLastReadTime: string) => {
            setUnreadMarkerTime(newLastReadTime);
        });

        const unreadActionSubscriptionTransactionThread = DeviceEventEmitter.addListener(`unreadAction_${transactionThreadReport?.reportID}`, (newLastReadTime: string) => {
            setUnreadMarkerTime(newLastReadTime);
            userActiveSince.current = DateUtils.getDBTime();
        });

        const readNewestActionSubscriptionTransactionThread = DeviceEventEmitter.addListener(`readNewestAction_${transactionThreadReport?.reportID}`, (newLastReadTime: string) => {
            setUnreadMarkerTime(newLastReadTime);
        });

        return () => {
            unreadActionSubscription.remove();
            readNewestActionSubscription.remove();
            unreadActionSubscriptionTransactionThread.remove();
            readNewestActionSubscriptionTransactionThread.remove();
        };
    }, [report.reportID, transactionThreadReport?.reportID]);
```

That would ensure that the unread marker time is updated with the latest action.

The other part of the problem is that the `lastReadTime` used throughout the component is the one of the chat report which   needs to be changed in a way that it considers the `lastReadTime` from the `transactionThreadReport` as well.
I suggest remove all occurrences of `report.lastReadTime` with the variable `lastReadTime`, the value of which would be as below:

```
    const lastReadTime = (transactionThreadReport?.lastReadTime ?? '') > (report.lastReadTime ?? '') ? transactionThreadReport?.lastReadTime : report.lastReadTime;
```

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by klajdipaja** [comment] 2024-10-30 09:17
Updated my proposal https://github.com/Expensify/App/issues/50568#issuecomment-2443764382 to refactor the code inside the `useEffect` according to DRY principle

**Comment by mvtglobally** [comment] 2024-10-30 09:44
Issue not reproducible during KI retests. (First week)

**Comment by klajdipaja** [comment] 2024-10-31 08:21
@dukenv0307 I could reproduce it just now on staging.new.expensify.com. Check out the screen recording how I managed to.


https://github.com/user-attachments/assets/33ec4c14-09b2-498a-80c9-ddcb8c4b479c

**Comment by klajdipaja** [comment] 2024-11-01 10:40
Updated proposal https://github.com/Expensify/App/issues/50568#issuecomment-2443764382. As @dukenv0307 has a valid point.

**Comment by klajdipaja** [comment] 2024-11-04 10:09
@dukenv0307 I think that should be in a separate bug ticket it is not directly connected to the bug here but the fact that we can now mark as unread the hold message makes this bug visible. 
The RCA for that is connected to the Optymistic Data. When you hold the mesasge two actions are created:
1. ADDCOMMENT with created time 2024-11-04 09:57:21.184
2. HOLD message with created time 2024-11-04 09:57:21.185
There's only 1 millisecond difference in this dates which collides with the expectantions we have for this dates about the last read time value.

In `report.ts` we set this optimistic value for the last read time:
```
    // We subtract 1 millisecond so that the lastReadTime is updated to just before a given reportAction's created date
    // For example, if we want to mark a report action with ID 100 and created date '2014-04-01 16:07:02.999' unread, we set the lastReadTime to '2014-04-01 16:07:02.998'
    // Since the report action with ID 100 will be the first with a timestamp above '2014-04-01 16:07:02.998', it's the first one that will be shown as unread
    const lastReadTime = DateUtils.subtractMillisecondsFromDateTime(actionCreationTime, 1);
```

We can solve this by adding a bigger artificial difference in the optimist date for the hold comment (2 or 3 milliseconds).

**Comment by klajdipaja** [comment] 2024-11-04 12:57
@dukenv0307 Found the RCA for that but I am not sure if we should include a fix for that case in this ticket.

The issue has to do with how we build the optimistic data for the hold comment (the one that says: `held this expense`).

The optimistic data contains in message empty html which we consider as a comment that has been delete,  here: 
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/libs/ReportActionsUtils.ts#L877.
The thread that you showed has 3 actions - CREATED->HOLD->ADD COMMENT but since the HOLD is considered a deleted action the Comment becomes the first action of the list:
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/pages/home/report/ReportActionsList.tsx#L521

If the action that is marked unread is the first one of the sorted actions then we show the the whole thread as unread which is why you see the marker at the top of the messages.

**Comment by klajdipaja** [comment] 2024-11-06 09:46
@dukenv0307 

> Yes, we need to fix the RCA. We're combining actions from 2 reports (iou and thread), but we just use the lastReadTime of the iou report.

This two sentences not belong on the same line as they are two different things. 

You found this bug after testing my proposal:

> Bug: Mark as unread the hold message shows the wrong unread indicator's position
To which I responded with the RCA here https://github.com/Expensify/App/issues/50568#issuecomment-2454649657 but actually I found out yesterday that is not even that the issue but the BE (or what we expect the BE to return in that case).
The `isDeleted` function returns true due to this 
```   // A legacy deleted comment has either an empty array or an object with html field with empty string as value
    const isLegacyDeletedComment = message.length === 0 || message.at(0)?.html === '';
```
because the response of the BE has empty HTML as you can see in this screenshot:

![image](https://github.com/user-attachments/assets/c3d3d5a8-159a-4bb7-8081-604846ca07ff)

> We're combining actions from 2 reports (iou and thread), but we just use the lastReadTime of the iou report.
> 
> Can we combine them too?

We don't have to combine them to fix the bug in hand. I'm hesitant to change the logic of the lastReadTime as it might cause a regression. If we need to how would you combine them? By taking the greates or smallest of both does not really work because the user can mark unread a message that has come later then the lastReadTime of the IOU report or even earlier. And they can do the same in the message of the main report. One idea could be to do something like `const lastReadTime=ReportActionsUtils.isTransactionThread(parentReportAction)?transactionThead.lastReadTime:iouReport.lastReadTime`.  But again we don't need to do this to fix the bug mentioned in the issue.

**Comment by klajdipaja** [comment] 2024-11-08 08:21
@dukenv0307 I cannot reproduce this any longer on the latest stage.
But you can check on stage that the regression my fix would have caused is not visibile there and the reason why we have that bug now is here: https://github.com/Expensify/App/issues/50568#issuecomment-2454649657

**Comment by thienlnam** [comment] 2024-11-13 18:35
Is this a correct summary? The Hold request doesn't send the correct message in the onyx data? 

cc @robertjchen I believe this is from https://github.com/Expensify/Auth/pull/9698

**Comment by mvtglobally** [comment] 2024-11-16 01:53
Issue not reproducible during KI retests. (Second week)

**Comment by johncschuster** [comment] 2024-11-19 00:09
@robertjchen what are your thoughts on the above?!

**Comment by robertjchen** [comment] 2024-11-20 00:59
I'm not sure what needs to be changed here, given that it's not reproducible? Should the hold action be queueing another Onyx update that's needed?

**Comment by klajdipaja** [comment] 2024-11-20 08:09
I can still reproduce on stage (just now) the issue mentioned in the description and the one we found with the Hold operation.
Mark unread category change message->
https://github.com/user-attachments/assets/9dbcb687-420f-4352-972d-722999d0b092


Mark unread hold expense message->
https://github.com/user-attachments/assets/4057d452-2e38-4839-b0da-138cefbcfdea

**Comment by johncschuster** [comment] 2024-11-21 23:06
@robertjchen ^

**Comment by johncschuster** [comment] 2024-11-25 21:56
Bumping!

**Comment by johncschuster** [comment] 2024-12-02 22:20
I'm catching up from being OOO for the holiday last week. Will get this slotted in tomorrow.

**Comment by johncschuster** [comment] 2024-12-09 22:35
Getting a retest to see if this still persists

**Comment by johncschuster** [comment] 2024-12-13 15:33
Bumped in [Slack](https://expensify.slack.com/archives/C9YU7BX5M/p1734103951262149?thread_ts=1733783717.303789&cid=C9YU7BX5M)

**Comment by mvtglobally** [comment] 2024-12-13 15:59
still reproducible 

https://github.com/user-attachments/assets/1e774dfe-a06b-4e6a-896f-cb316ecba16b

**Comment by johncschuster** [comment] 2024-12-16 23:03
Ok! It looks like this is still reproducible. @thienlnam / @robertjchen what's the next step here?

**Comment by johncschuster** [comment] 2024-12-20 22:41
Heads up, I will be OOO from Monday, December 23, and returning Monday, January 6. I am not reassigning my assigned issues. If you feel this issue needs to be actioned by a Bug Zero team member, please reach out for help from any available team members in #expensify-open-source.

If not, I'll action this as soon as I'm back in office!

**Comment by thienlnam** [comment] 2024-12-25 02:14
Given that this an edge case and not something a real user would actually do, I'm just going to close this for priority

**Closed by thienlnam** 2024-12-25 02:14 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
