### ISSUE TITLE
[$1000] Bug: #announce room not visible when added to a workspace, must refresh the page reported by @Puneet-here 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12027] opened 2022-10-20 01:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with account A > Create a workspace "Abc"
2. Invite account B
3. Login with account B at a new browser
4. Search announce room named "Abc"
5. Verify that there's no room with that workspace name
6. Try reloading > search for the room with workspace name "Abc"

## Expected Result:
You should see the room without reloading

## Actual Result:
You have to reload the page

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**  v1.2.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196832783-dcbb1245-99ae-4eb6-a2dc-d85117c9264e.mov
https://user-images.githubusercontent.com/43996225/196832789-66f8dcb5-245b-4e59-a056-58fba003e241.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666216335774649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2022-10-20 14:57
I was just testing this somewhere else and can confirm the bug. The testing steps I followed were: 

1. Create two accounts, `workspace-owner` and `workspace-employee`.
2. Sign into both accounts in two chrome windows (one incognito)
3. As the `workspace-owner`, create a new workspace.
4. Invite `workspace-employee` to the workspace.
5. As the employee, observe that the #announce room doesn't appear in the LHN
6. Refresh the page 
7. Observe that the #announce room appears in the LHN

**Comment by strepanier03** [comment] 2022-10-20 20:44
Triaging now.

**Comment by strepanier03** [comment] 2022-10-20 22:10
Reproducible:

1. Created a new workspace under strepanier2003.newexpensify@gmail.com
2. Created a new employee account under strepanier2003.newexpensify+employee@gmail.com
3. Invited employee account to workspace
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10925636/197067213-6ad47c37-5ba3-4941-8dec-f90cd9a930f2.png">
4. Confirmed employee account doesn't have #announce room
<img width="1440" alt="2022-10-20_14-58-33" src="https://user-images.githubusercontent.com/10925636/197067470-d42c0294-e355-414d-a894-1401819fee08.png">
5. Refreshed browser page and confirmed #announce room is now visible.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10925636/197067452-a407e5d6-be48-4ec4-bf69-d2e00c09ecc0.png">

----

It does sort of make sense that the #announce room isn't visible to the employee account because they were signed in when it was created and nothing had reset or refreshed their page since. 

I tested to be sure and if the employee is not logged in at the time they are invited and then logs in after they get invited, the #announce room shows up for them without the need to refresh.

**Comment by strepanier03** [comment] 2022-10-20 23:24
@jasperhuangg - If you don't think this should be labeled External just let me know. I plan to make the Upwork job tomorrow morning when I get back online.

**Comment by strepanier03** [comment] 2022-10-21 17:54
Upwork Job [created](https://www.upwork.com/ab/applicants/1583516929391411200/suggested). 

Job posting: https://www.upwork.com/ab/applicants/1583516929391411200/job-details

**Comment by strepanier03** [comment] 2022-10-24 22:01
Job link: https://www.upwork.com/jobs/~01c330d655d6a6977d

**Comment by strepanier03** [comment] 2022-10-28 21:44
Price doubled.

**Comment by strepanier03** [comment] 2022-11-04 20:05
Price doubled - [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667592282601709).

**Comment by mananjadhav** [comment] 2022-11-05 19:01
> do we have some polling or subscription to rooms data?

Not sure what you mean here @Uros787. But we do have chat room creation with Pusher notifications. So that's how the chat/group chats show up. I am guessing this isn't happening for `#announce` room chats.

**Comment by inkmn** [comment] 2022-11-06 02:17
### Proposal
### Problem
The server pushes the empty value to `report_` and `reportIOUs_`.
![Screenshot 2022-11-06 at 08 56 11](https://user-images.githubusercontent.com/6467761/200149150-736e79ec-7f61-465c-8d27-1ef5e0dbd6ce.png)
### Solution
A pusher should receive valid report data from the server
The problem should be solved internally instead of externally

**Comment by mananjadhav** [comment] 2022-11-07 06:21
@jasperhuangg do you have the context on the Pusher notifications data being sent from the backend? Can you confirm here for this issue?

**Comment by strepanier03** [comment] 2022-11-07 19:10
@jasperhuangg - Do you agree this should be turned into an internal job instead of an external job?

**Comment by trjExpensify** [comment] 2022-11-07 19:18
@chiragsalian isn't this a dupe of https://github.com/Expensify/App/issues/11542?

**Comment by strepanier03** [comment] 2022-11-07 19:23
I agree, this looks like a dupe of the one you linked @trjExpensify. Thank you for linking it in.

**Comment by trjExpensify** [comment] 2022-11-07 19:25
Yeah, I think the other `internal` issue linked is incorrectly marked with `Android` in the title, really.

**Comment by chiragsalian** [comment] 2022-11-07 19:31
Ah yup it looks like a dupe, i wasn't sure if the issue was external yet and didn't get the chance to test yet. I suspected the problem could be internal wherein the required pusher onyx data was not sent. But yeah I never confirmed it. 

Nevertheless yes https://github.com/Expensify/App/issues/11542 is a dupe. We could close either, let me know what you guys would prefer as the next step.

**Comment by chiragsalian** [comment] 2022-11-07 19:33
Ah from the discussion it looks like others also feel like the issue is internal. If you guys like you can close out this issue and i can tackle it in https://github.com/Expensify/App/issues/11542.

**Comment by jasperhuangg** [comment] 2022-11-07 21:46
@chiragsalian Thanks for the investigation! Definitely looks like this needs to be fixed internally, and happy to let you do it in https://github.com/Expensify/App/issues/11542 if it won't be too much of a hassle. Closing

**Closed by jasperhuangg** 2022-11-07 21:46 UTC
Labels: External, Daily, Improvement, Help Wanted
