### ISSUE TITLE
Console error when uploading svg as avatar.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19320] opened 2023-05-19 20:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account, try to change avatar with svg image.
2. Notice there's error showing.

## Expected Result:
User can select svg as avatar.
## Actual Result:
There's error showing while choosing svg.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.15-0
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/dea61268-3bc7-4a17-943e-7cf828aded0d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684317060685459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment] 2023-05-21 12:17
I can also reproduce with this svg, so I attached it here incase anyone need it.
![Rectangle 13](https://github.com/Expensify/App/assets/16502320/6282441e-3e5f-41e7-9de0-364f6e1df428)

**Comment by laurenreidexpensify** [comment] 2023-05-22 10:34
I just tested this on staging.new.expensify.com with this file and can't reproduce: 

![2023-05-22_11-31-41 (1)](https://github.com/Expensify/App/assets/62073721/728f3358-37dd-4fa1-9031-a23ea48103d7)

![expensify-app-logo-2019 (1)](https://github.com/Expensify/App/assets/62073721/d9881f75-f923-4fbd-8616-da4b6ad30c3f)

**Comment by laurenreidexpensify** [comment] 2023-05-22 10:35
@kavimuru are you still able to reproduce?

**Comment by laurenreidexpensify** [comment] 2023-05-23 14:39
Closing as cannot reproduce.

**Closed by laurenreidexpensify** 2023-05-23 14:39 UTC
Labels: Daily, Needs Reproduction, Bug

**Comment by hungvu193** [comment] 2023-05-23 15:14
> I can also reproduce with this svg, so I attached it here incase anyone need it. ![Rectangle 13](https://user-images.githubusercontent.com/16502320/239740155-6282441e-3e5f-41e7-9de0-364f6e1df428.svg)

Can you try with this attachment? @laurenreidexpensify , I'm still able to reproduce.
