### ISSUE TITLE
[HOLD on #40181] [$125] mWeb - Chat - Next to emoji entering single alphabet, doesn't turn emoji into small

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48551] opened 2024-09-04 12:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4919658
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch site in both mweb and Android
2. Open a chat
3. Open emoji picker near compose and select an emoji
4. In mweb, after selecting emoji, enter a single letter
5. Note emoji remains big
6. In mweb, after selecting emoji, enter a single number
7. Note emoji turns small
8. In Android, after selecting emoji, enter a single number
9. Note emoji turns small

## Expected Result:
Next to emoji entering single alphabet, must turn emoji into small

## Actual Result:
Next to emoji entering single alphabet, doesn't turn emoji into small in mweb. But emoji turns small in Android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8077fc31-5acf-4680-af7f-91cd19aa69c3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832331364813666635</li>
        <li>Upwork Job ID: 1832331364813666635</li>
        <li>Last Price Increase: 2024-09-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by lanitochka17** [comment] 2024-09-04 12:24
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by twisterdotcom** [comment] 2024-09-07 08:13
Very niche, downgrading to weekly and 125.

**Comment by QasimBham** [comment] 2024-09-07 12:03
Hi !
I'm Qasim from upwork. I saw the complete code and i think i can fix that. The problem you are facing maybe issue of different styling or viewport and screen scaling. I'm confident that i can fix that.

**Comment by QasimBham** [comment] 2024-09-07 12:25
Contributor details 
Your Expensify account email: QasimBham1122@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e6c397b6b9941e91

Hi !
I'm Qasim from upwork. I saw the complete code and i think i can fix that. Ive tested it on mweb and yes the emoji turns small after typing 2 letters. The problem you are facing maybe issue of different styling or viewport and screen scaling. I'm confident that i can fix that. Let me know if you have any further queries.

**Comment by ikevin127** [comment] 2024-09-07 20:53
@QasimBham Please refer to the [Contributor Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and if still interested and you're able to reproduce the issue, you can submit a proposal following the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) -> for clarity, it is recommended to use code examples from the codebase for both root cause and solution questions from the proposal tamplate.

**Comment by ChavdaSachin** [comment] 2024-09-08 19:01
It rather looks like react-native bug. In provided video when typing on web a thin underline is visible under the letter which happens when keyboard is capturing word and no website style is applied to the text yet(means text is not yet captured by web). 
<details><summary>See this screenshot</summary>
![WhatsApp Image 2024-09-09 at 00 11 19](https://github.com/user-attachments/assets/3fa65a8d-ca3e-4b32-9885-4f58e7cba072)
![WhatsApp Image 2024-09-09 at 00 30 07](https://github.com/user-attachments/assets/c2bb447e-49b3-4210-b946-0b475c2116d8)
</details>
See when translator is used and the text is captured by keyboard same issue happens even for other markdown.
This might be caused by how react-native handles text-input on browser and natively.

**Comment by QasimBham** [comment] 2024-09-09 10:33
I think this issue is related to styling and viewport scaling rather than react native because the issue you are facing is in mweb and not in the mobile app.

**Comment by klajdipaja** [comment] 2024-09-09 11:19
@lanitochka17 This is not reproducible in the latest stage on mWeb and there are some commits in the related feature, maybe it was fixed since you opened the issue ?

**Comment by ikevin127** [comment] 2024-09-18 19:28
Still looking for proposals!

Maybe we can ask people that worked / have more context on **react-native-live-markdown** like @BartoszGrajdek for their take on this one and whether or not this is something worth fixing.

**Comment by Skalakid** [comment] 2024-09-20 08:19
Hi @ikevin127, is this issue still reproducible? Everything seems to work fine on the latest main

https://github.com/user-attachments/assets/e8037fc5-90ec-46a0-8ec9-ff70be32fbc3

**Comment by ikevin127** [comment] 2024-09-21 22:55
@Skalakid Hi, yes I'm able to reproduce:

https://github.com/user-attachments/assets/6538be49-9fc5-402e-a86d-d607e1aa8661

Issue seems to be that on Android: mWeb inputting alphabet characters next to emoji -> doesn't size down the emoji within the composer, which does happen on Android: Native.

> [!note]
> ### Observations
> 1. This only happens with alphabet characters, anything else like symbols and numbers do size down the emoji.
> 2. Despite this discrepanci which happens in the Composer, when the message is actually posted -> the emoji is always sized down when there's a character before or next to it.
> 3. (out of scope) The composer height also looks weird on Android: mWeb compared to Android: Native (see below).

| Android: mWeb | Android: Native |
| ------------- | ------------- |
| <img width="360" alt="mweb" src="https://github.com/user-attachments/assets/9fa3fcd8-2110-4e23-a98e-af982147ab29"> | <img width="358" alt="native" src="https://github.com/user-attachments/assets/97cbff38-068d-4a45-b578-724b5302df64"> |

**Comment by Skalakid** [comment] 2024-09-25 09:59
Hmm, I still can't reproduce this on the late main and staging. Also, I've tried to do it on the physical device, but without success. On what device are you checking this?


https://github.com/user-attachments/assets/f0469910-4a33-49ec-874d-26ef06b6d8b8

**Comment by Skalakid** [comment] 2024-09-30 08:57
Reproducible on physical devices with Samsung keyboard, [here is the PR](https://github.com/Expensify/react-native-live-markdown/pull/506) with the fix

![Screenshot_20240930-105308_Chrome-2024-09-30 08_56_11 620](https://github.com/user-attachments/assets/34ad25b5-426d-43bb-94e5-5ef5ed046c0e)

**Comment by twisterdotcom** [comment] 2024-09-30 16:26
Okay, would any of the above proposals resolve it @ikevin127?

**Comment by ikevin127** [comment] 2024-09-30 17:46
@twisterdotcom We don't have any formal proposals to review here, but as I mentioned in a comment above where I reproduced the issue - it's highly likely that the issue is `react-native-live-markdown` (library) related.

This was confirmed by @Skalakid in https://github.com/Expensify/App/issues/48551#issuecomment-2382525215 where they also mentioned that thry already have a PR open with the fix, on the library side.

All that's left to do here is to await for that `react-native-live-markdown` PR to be merged and then for a `react-native-live-markdown` version bump PR on E/App side which will fix our issue.

What we need to figure out next is who's going to handle the E/App version bump PR, if there's already somebody assigned for that or if we need to assign somebody.

**Comment by Skalakid** [comment] 2024-10-01 06:34
@ikevin127 I handled the library version bump [here](https://github.com/Expensify/App/pull/49250). The PR is already merged, so this issue should be fixed now :D

**Comment by ikevin127** [comment] 2024-10-01 17:18
Cool, thanks for handling that!

@twisterdotcom I guess the only thing left to do here is re-test the issue and if we confirm it was fixed then we can close.

Will test it today and get back with my results.

**Comment by thienlnam** [comment] 2024-10-01 22:14
Unfortunately the bump was reverted, so we should put this on hold again

**Comment by mvtglobally** [comment] 2024-10-05 03:08
Issue not reproducible during KI retests. (First week)

**Closed** 2024-12-16 10:02 UTC
Labels: External, Monthly, Help Wanted, Bug
