### ISSUE TITLE
IOU – An error message appears when attempting to add Amount and Merchant to IOU while scanning a receipt

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34534] opened 2024-01-15 20:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.25-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as the WS employee
3. Create scan request
4. Open IOU while the receipt is scanning
5. Edit the missing fields Merchant and then Amount

## Expected Result:
Receipt is edited without error

## Actual Result:
An error message appears when attempting to add Amount and Merchant to IOU while scanning a receipt

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/91434f7d-4e09-4644-836e-8aa4caa0844a)

https://github.com/Expensify/App/assets/93399543/c2d903a5-bb03-4063-9eb7-1dbea316c006

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2024-01-15 23:38
I'm currently unable to reproduce this, going to try updating Auth and Web-E

**Comment by roryabraham** [comment] 2024-01-15 23:42
Yeah, I'm unable to reproduce this on main.

**Comment by roryabraham** [comment] 2024-01-15 23:42
Going to try reproducing locally by checking out the staging branch – maybe this has already been fixed and we just need to CP the appropriate PR?

**Comment by roryabraham** [comment] 2024-01-15 23:45
Yeah, not able to reproduce locally at all.

**Comment by roryabraham** [comment] 2024-01-15 23:49
not able to reproduce on staging either

**Comment by roryabraham** [comment] 2024-01-16 01:04
Given that this isn't preventing the user from completing the flow, and that it's only inconsistently reproducible, I don't think we need to block deploy on this.

**Comment by roryabraham** [comment] 2024-01-16 01:06
cc @cead22 this has to do with violations but is inconsistently reproducible. I'm trying to get more details. Slack context [here](https://expensify.slack.com/archives/C9YU7BX5M/p1705362621332039)

**Comment by cead22** [comment] 2024-01-16 19:12
This is working as designed, and it's not a bug. When you add amount or date to a money request, SmartScan is assumed to be skipped, so the violation message is correct.

Maybe we'll change how this looks visually, but this will all improve as we continue implementing violations, so closing for now

**Closed by cead22** 2024-01-16 19:12 UTC
Labels: Engineering, Daily, Bug
