### ISSUE TITLE
DEV: Not getting updated profile picture in new search chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20684] opened 2023-06-13 15:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Update profile picture of USER A
2. Go to New chat From "+" button in USER B
3. Search USER A
4. Observe the profile picture
## Expected Result: 
updated profile picture should be show
## Actual Result: 
old profile picture is show
Platforms: Android/ IOS Native(Dev)
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev only
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f42adaae-769d-4803-bca0-cd388ecb68dd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686133818411619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment] 2023-06-13 16:37
I can't reproduce bugs in Dev, assigning `Engineering` for help per SO

**Comment by neil-marcellini** [comment] 2023-06-14 17:51
I was not able to reproduce on web. I'll try on iOS too.

https://github.com/Expensify/App/assets/26260477/26fbb20d-5e36-426d-85c2-cf562292da06

I was not able to reproduce on iOS following the exact steps in the video (which are different from those written). This is not a problem, I'm closing this. The bug might have been reported because sometimes the Pusher update with the new photo is slow to arrive.

https://github.com/Expensify/App/assets/26260477/1d75d739-c06d-42b3-aa7a-023f2359ced6

**Closed by neil-marcellini** 2023-06-14 17:51 UTC
Labels: Engineering, Daily, Needs Reproduction, Bug

**Comment by greg-schroeder** [comment] 2023-06-14 20:41
Thanks for your help here @neil-marcellini!
