### ISSUE TITLE
[HOLD for payment 2024-07-24] [$50] Rip out the beta code for REPORT_FIELDS

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#44621] opened 2024-06-28 13:50 UTC
We're no longer using the code for CONST.BETAS.REPORT_FIELDS. This is enabled for everyone internally - so we can just remove the beta code related to CONST.BETAS.REPORT_FIELDS

Note: This is different from the beta REPORT_FIELDS_FEATURE
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108e03ca805bf2401</li>
        <li>Upwork Job ID: 1806686959271564355</li>
        <li>Last Price Increase: 2024-06-28</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 102919536</li>
<li>neonbhai | Contributor | 102919537</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by neonbhai** [comment] 2024-06-28 14:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove the beta code for REPORT_FIELDS

### What is the root cause of that problem?
Feature Request




### What changes do you think we should make in order to solve the problem?
We will remove the code corresponding to `canUseReportFields` beta checks, and its uses in the app

https://github.com/Expensify/App/blob/0c8bae5afb6ea1b487743bb00c994e71b7e85238/src/libs/Permissions.ts#L18-L20

**Comment by c3024** [comment] 2024-06-28 14:44
@neonbhai can be assigned.

🎀 👀 🎀 C+ Reviewed

**Comment by thienlnam** [comment] 2024-07-26 18:49
cc @bfitzexpensify Could we handle payment here? 

$50 to @neonbhai and @c3024.

No regression tests needed for this

**Comment by bfitzexpensify** [comment] 2024-07-30 08:03
Payments complete. Closing this out

**Closed by bfitzexpensify** 2024-07-30 08:03 UTC
Labels: External, Daily, Overdue, Awaiting Payment
