### ISSUE TITLE
[$1000] Web - Workspaces - Page goes to wrong page when clicking go to #admin rooms

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25393] opened 2023-08-17 13:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Click any admin room from LHN
3. Settings > Workspaces
4. select the workspace which is corresponding to the opened room in Step 2
5. click three dots
6. click open #admin room
7. observe the result

## Expected Result:
The room should be opened

## Actual Result:
the wrong page is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/2f08659d-e2e0-4649-a25a-3188b11a6d2d

https://github.com/Expensify/App/assets/115492554/5e4059ea-395d-4848-a536-32540daf94df

**Expensify/Expensify Issue URL:**

**Issue reported by:** @misgana96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692276872694949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d806101ebfe064a7</li>
        <li>Upwork Job ID: 1692634240552304640</li>
        <li>Last Price Increase: 2023-09-01</li>
    </ul>
</details>

**Comment by Pluto0104** [comment] 2023-08-17 20:18
I was able to reproduce the issue, but it appears intermittently and not consistently. Additionally, it occasionally navigates to the settings route.

**Comment by tjferriss** [comment] 2023-08-17 22:31
I'm able to reproduce. It's taking me back to the chat I was last in, instead of the #admins room. 


https://github.com/Expensify/App/assets/8292562/eef66245-660b-4828-90dc-0421efd381bc

**Comment by yuwenmemon** [comment] 2023-08-17 22:59
Weird, I _can't_ seem to reproduce 🤔

**Comment by yuwenmemon** [comment] 2023-08-17 23:05
Ah. I believe the inconsistency of reproducing led us to believe this was staging only but I just verified it on Prod too so removing the blocker label.

**Comment by b4s36t4** [comment] 2023-08-18 13:05
I can't able to re-produce this one prod but dev and staging only. Also it's not just opening settings sometimes it opens wrong report too.

**Comment by b4s36t4** [comment] 2023-08-18 16:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Workspaces - Page goes to wrong page when clicking go to #admin rooms
### What is the root cause of that problem?
We're using multiple navigation states like the following `navigate`, `push` and `pop`. 

As per the documentation of `React Navigation` if we use `navigate` action it will go the screen by screen's `name` and remove all the screens that are on top of it.

Current Flow:
1. Open any report using deeplink
2. Select any `#admin` room (this is PUSH) event, so we update the stack.
3. Now open settings page (RHN will be pushed into stack)
4. Now in settings page when we click on `#admin room` which uses `navigate` action. (now because of Navigation and the screen name is `CentralPaneNavigator`, but in the state we have two reports screen one with deeplink and one is #admin room).

Before clicking on `Goto #admin room` the navigation state is
`[Home, CentralPaneNavigator,CentralPaneNavigator,RightModalNavigator]`

When we click on `Goto #admin room` due the `navigate` action React Navigation is going the first `CentralPaneNavigator` navigator it's seeing which is the screen we opened using deeplink even though we're trying to navigate to the 3rd screen.

This issue happens only when the admin room is in the top of stack, if not we push then there is no problem.

### Video.
https://github.com/Expensify/App/assets/59088937/887803c1-7ed5-47ca-b1d7-b30ff8797cf4

### What changes do you think we should make in order to solve the problem?
Here in this line https://github.com/Expensify/App/blob/f45ddbe78cf00b6a36927aab19422a45cd8a975b/src/libs/Navigation/linkTo.js#L70 we're checking for the latest report and based on that we navigate.

To solve this.. if the latest report is the same as the report we're going to navigate instead of navigate either we push or just dimiss the modal.

But to push can cause re-renders for the report screen which is not intended noting that the last screen is same admin room, so I'd prefer dismissing the modal should do the work.

Following should do the work, we need to update here in this function https://github.com/Expensify/App/blob/f45ddbe78cf00b6a36927aab19422a45cd8a975b/src/pages/workspace/WorkspaceInitialPage.js#L104
```jsx
const currentTopMostReport = Navigation.getTopmostReportId();
if (room.reportID === currentTopMostReport) {
    Navigation.dismissModal();
    return;
}
```



### What alternative solutions did you explore? (Optional)
NA

## Reference
https://reactnavigation.org/docs/navigation-actions#navigate

## Bug
https://github.com/Expensify/App/assets/59088937/2902e83c-66ab-4a7e-973c-e5129e3f3d88

## Result
https://github.com/Expensify/App/assets/59088937/2af6e718-202e-4996-b731-5db527171d0e

**Comment by nekores** [comment] 2023-08-18 21:20
Contributor details
Your Expensify account email: [sajidxullah@gmail.com](mailto:sajidxullah@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/nekores

**Comment by nekores** [comment] 2023-08-18 21:21
Contributor details
Your Expensify account email: sajidxullah@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/nekores

**Comment by b4s36t4** [comment] 2023-08-21 10:29
@aimane-chnaif https://github.com/Expensify/App/issues/25393#issuecomment-1683089847 I don't think this is a regression.

It happens constantly, but to re-produce this you have to be in the `#admin-room` of workspace which you're trying from settings as well then you can re-produce this.

https://user-images.githubusercontent.com/59088937/261664717-2902e83c-66ab-4a7e-973c-e5129e3f3d88.mp4

Please watch this video, you'll get the bug.

**Comment by b4s36t4** [comment] 2023-08-21 10:38
Ok got it.

**Comment by madmax330** [comment] 2023-08-25 12:12
Still waiting on proposals

**Comment by madmax330** [comment] 2023-08-28 21:09
Same

**Comment by Pluto0104** [comment] 2023-09-05 11:08
It's might be fixed by react navigation patch.

**Comment by tjferriss** [comment] 2023-09-05 19:19
I'm not able to reproduce this one so I believe we can close it.

**Closed by tjferriss** 2023-09-05 19:19 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug

**Comment by misgana96** [comment] 2023-09-05 19:22
@tjferriss Am I eligible for a reporter bonus since it is fixed from by react-navigation path?

**Comment by tjferriss** [comment] 2023-09-27 06:19
I'm [asking internally](https://expensify.slack.com/archives/C01SKUP7QR0/p1687779856807209) about this situation. Given the react-navigation patch was deployed before this bug was reported, I don't believe we would pay the reporting bonus.

**Comment by tjferriss** [comment] 2023-09-27 07:10
@misgana96 I confirmed with the team internally. Because the patch was deployed before this issue was reported we will not pay the reporting bonus.

**Comment by misgana96** [comment] 2023-09-27 07:12
> @misgana96 I confirmed with the team internally. Because the patch was deployed before this issue was reported we will not pay the reporting bonus.

Thank you for quick response.
