### ISSUE TITLE
[$250] QAB - Negative amount briefly displayed when Pay someone

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44914] opened 2024-07-05 14:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2990372
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: user did 'Pay someone' to individual chat
1. Click FAB
2. Click QAB > Pay someone
3. Input amount
4. Click Pay elsewhere

## Expected Result:
User navigated to chat with person he payed. Expense preview displays amount

## Actual Result:
User navigated to chat with person he payed. Expense preview briefly displays negative amount (occasionally negative amount may stay)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0d7908b4-380b-47fb-9a5f-fb651a4334e7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee0d66d57ed7a8d9</li>
        <li>Upwork Job ID: 1810894586733112761</li>
        <li>Last Price Increase: 2024-08-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by bernhardoj** [comment] 2024-07-06 12:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Negative amount is shown on the report preview when pay someone.

### What is the root cause of that problem?
The pay amount logic is, if there is a total amount from the IOU report object, then we use that amount, otherwise, we take the amount from the report preview message.
https://github.com/Expensify/App/blob/c5eafd33463b2ba4c0ce2eb0c48261f66b085dc7/src/components/ReportActionItem/ReportPreview.tsx#L206-L232

In the OP video, we can see the amount changes from
UAH xx -> ₴ xx -> -UAH xx

The reason it shows a negative amount is that the IOU report total is 0, so it takes the amount from the report preview message which is negative. If we see some logic related to the money request amount, we take the abs amount if it's an IOU report, which we don't do here.
https://github.com/Expensify/App/blob/c5eafd33463b2ba4c0ce2eb0c48261f66b085dc7/src/libs/ReportUtils.ts#L2408-L2412

But, if we look into the onyx storage, the IOU report actually has a non-zero total, but the data isn't reflected in the report preview component. So, the report preview component holds the old data. It's the withOnyx bug where it doesn't give the most up-to-date data when there are multiple merges happening within a short span of time. It's similar to this [issue](https://github.com/Expensify/App/issues/42153) where the policy data is undefined because `activeWorkspaceID` is initially undefined but then is [updated when the nav state changes](https://github.com/Expensify/App/blob/c5eafd33463b2ba4c0ce2eb0c48261f66b085dc7/src/libs/Navigation/NavigationRoot.tsx#L133-L137), but the policy data stays undefined.

### What changes do you think we should make in order to solve the problem?

As `withOnyx` is officially deprecated, we can just replace it with `useOnyx` for the `ReportPreview` component which doesn't have the bug. This will make the component always stay up-to-date.

However, we still have one problem, that is the amount changing. After we replace it with `useOnyx`, the amount will change from
UAH xx -> ₴ xx -> -UAH xx -> UAH xx

The first amount is the optimistic amount. Then, after the send money request is completed, the send money API response returns multiple Onyx merge requests. The first request merges the IOU report data which has a `total` data of 0. This overwrites the optimistic total.
<img width="186" alt="image" src="https://github.com/Expensify/App/assets/50919443/b839d0b8-ce95-446d-b2ee-60999aab94c2">

Also, notice that the `statusNum` is 1 which is SUBMITTED instead of 4 (REIMBURSED). This makes the `isSettled` state becomes false.

Because the `total` is 0, it will get the amount from the report preview message, but the message from the BE response uses the currency symbol (₴) instead of the currency code (UAH). (the 2nd amount shown)

<img width="278" alt="image" src="https://github.com/Expensify/App/assets/50919443/f459d71e-ecf2-4ea8-b0a2-904f47b70ec6">

The last few merge requests from the API response contain the correct data. (the 3rd (the correct message) and then 4th (the correct iou report total) amount is shown)

This needs a BE fix.

Additionally, we can make sure the amount is never be in negative by making it absolute for IOU report,
https://github.com/Expensify/App/blob/c5eafd33463b2ba4c0ce2eb0c48261f66b085dc7/src/components/ReportActionItem/ReportPreview.tsx#L218-L230

just like we did here.
https://github.com/Expensify/App/blob/c5eafd33463b2ba4c0ce2eb0c48261f66b085dc7/src/libs/ReportUtils.ts#L2412

**Comment by JmillsExpensify** [comment] 2024-07-10 04:31
I'll add the external label. If the solution is straightforward we can fix it.

**Comment by brunovjk** [comment] 2024-07-10 18:57
@bernhardoj Thanks for the proposal. Your RCA is not clear to me yet. I replace `withOnyx` with `useOnyx` in `ReportPreview` and I continue with exactly the same behavior as before, which by the way is a bit different, I go from `$xx` to `-$xx` and I'll stay there. Could you please give me a more detail or share a test branch? Thank you very much.

**Comment by bernhardoj** [comment] 2024-07-12 06:54
Hmm, you're right. Maybe there is something happened when I tested it. I just rechecked that the problem is in `Onyx.connect` which doesn't give us the latest value and I haven't found a solution for that yet..

**Comment by brunovjk** [comment] 2024-07-16 18:21
Still waiting for proposals

**Comment by brunovjk** [comment] 2024-07-16 19:50
> the problem is in `Onyx.connect` which doesn't give us the latest value and I haven't found a solution for that yet..

Any new finds @bernhardoj ? Thank you :D

**Comment by bernhardoj** [comment] 2024-07-17 03:36
Not yet

**Comment by brunovjk** [comment] 2024-07-19 18:23
Not overdue, still looking for proposals

**Comment by brunovjk** [comment] 2024-07-25 11:05
still looking for proposals

**Comment by brunovjk** [comment] 2024-07-30 11:28
Same as above

**Comment by brunovjk** [comment] 2024-07-31 16:19
Bumped on Slack for proposals

**Comment by mvtglobally** [comment] 2024-08-03 04:08
Issue not reproducible during KI retests. (First week)

**Comment by brunovjk** [comment] 2024-08-04 12:27
I wasn't able to reproduce it either (Aug/04 - v9.0.16-3.)

**Comment by brunovjk** [comment] 2024-08-07 18:20
@JmillsExpensify can you reproduce? Thanks

**Comment by mvtglobally** [comment] 2024-08-09 04:25
Issue not reproducible during KI retests. (Second week)

**Comment by brunovjk** [comment] 2024-08-13 18:43
@JmillsExpensify should we wait for **mvtglobally** to complete its weeks, or can we close the issue? We reopen if necessary.

**Comment by mvtglobally** [comment] 2024-08-23 12:04
Issue not reproducible during KI retests. (Third week)

**Comment by brunovjk** [comment] 2024-08-24 11:55
I was unable to reproduce (v9.0.24-1). I believe this issue was being caused by some conflict in the server response, which is why there were times when we were able to reproduce it and others not. I didn't find anything strange about it in FE.

**Comment by brunovjk** [comment] 2024-08-27 14:45
@JmillsExpensify Do you think we can get someone else to reproduce and confirm that the issue still exists? Thank you.

**Closed** 2024-08-28 12:48 UTC
Labels: External, Daily, Help Wanted, Bug
