### ISSUE TITLE
[REPORTING PAYMENT][$500] Web -  Opening the #teachers-unite room directly through the link shows sign in option even when signed in

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26615] opened 2023-09-03 19:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logout if already logged in
2. Go to https://staging.new.expensify.com/r/207591744844000
3. Click on the Sign in button
4. Enter the email and click Continue
5. Enter magic code
6. Next, click on the #teachers-unite room header
7. Click on Leave room
8. Open a new tab and go to https://staging.new.expensify.com/r/207591744844000

## Expected Result:
The sign-in option should not be displayed

## Actual Result:
The sign-in option is displayed. Also, the sign-in modal still has the previously entered magic code (Note: this may not be reproducible on the newest version - https://github.com/Expensify/App/issues/26615#issuecomment-1704428422)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f993d3e4-d8e9-41ae-a8e2-236521bbaf2d

https://github.com/Expensify/App/assets/93399543/07c50721-9c3e-4de7-99a8-65e004db90cc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693382434318589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164d1ccb8bef91f4d</li>
        <li>Upwork Job ID: 1698473014682202112</li>
        <li>Last Price Increase: 2023-09-10</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-09-03 23:01
@adeel0202 @kbecciv on v1.3.62-3, I can reproduce part of this issue - basically, the part I cannot reproduce is showing the Magic Link details prefilled. On the newest staging version, I see this:

![image](https://github.com/Expensify/App/assets/30815269/eb0c233b-ec73-4c06-ab74-fec16fc3f929)

However, leaving the room and opening a new tab and using the URL still shows a "Sign In" button - I think this should be fixed, since you shouldn't need to sign in again as all you've done is left the room.

**Comment by AmjedNazzal** [comment] 2023-09-04 00:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Opening the #teachers-unite room directly through the link shows sign in option even when signed in

### What is the root cause of that problem?

The method in which we check to hide the composer and show sign in button is unreliable, there is no doubt here that we are facing a backend issue where leaving a room in some cases will result in session.authTokenType being returned by the backend as "anonymousAccount" and I believe that should be addressed on an internal level, however I think we should also address this on frontend level to avoid this kind of behaviour in the future as relying on authTokenType isn't the best idea when we have access to two more unique items that will be available when the user is signed in which are CREDENTIALS.login and CREDENTIALS.validateCode.

### What changes do you think we should make in order to solve the problem?

We should refrain from using authTokenType and start using CREDENTIALS when we are checking for credentials as is the case with checking if isAnonymousUser, to do this we can make a change to session.isAnonymousUser to use these credentials for the check.

```javascript
function isAnonymousUser() {
    return !lodashGet(credentials, 'login') && !lodashGet(credentials, 'validateCode');
}
```

Another thing we can change is ReportUtils.shouldDisableWriteActions which uses isAnonymousUser that it calls itself from Onyx which is not good for keeping the code DRY as we are already connecting to the exact same part of Onyx in Session component so we can simply change the check for shouldDisableWriteActions to use the same Session.isAnonymousUser function.

```javascript
function shouldDisableWriteActions(report) {
    const reportErrors = getAddWorkspaceRoomOrChatReportErrors(report);
    return isArchivedRoom .. || Session.isAnonymousUser(); // Changing from local variable to calling Session component
}
```

### Result

https://github.com/Expensify/App/assets/74202751/12081f05-9792-4745-afa2-ad5b5f364e1d

**Comment by kaushiktd** [comment] 2023-09-06 05:37
### Please re-state the problem that we are trying to solve in this issue.
Opening #teachers-unite room directly through the link shows sign in option even when signed in

### What is the root cause of that problem?
The root cause of the problem is the unreliability of the method used to decide whether to show the signup modal in the frontend of the application. The issue is exacerbated by inconsistent data returned from the backend, specifically the session.authTokenType. This inconsistency occurs when leaving a room, resulting in session.authTokenType being sometimes incorrectly set to 'anonymousAccount'.

### What changes do you think we should make in order to solve the problem?
To address this issue effectively, we propose a solution that involves both frontend and potentially backend adjustments:

Frontend Solution:

Enhance Authentication Checks: Instead of relying solely on `session.authTokenType`, which has proven to be unreliable due to backend inconsistencies, prioritize the use of more dependable indicators of user authentication, such as `CREDENTIALS.login` and `CREDENTIALS.validateCode`.

Modify the `isAnonymousUser` Function: Refactor the `isAnonymousUser` function to check the user's anonymity based on the presence of `CREDENTIALS.authTokenType` rather than `session.authTokenType`. This adjustment ensures more accurate identification of anonymous users.
Below is the path for file index
https://github.com/Expensify/App/blob/main/src/libs/actions/Session/index.js

```
function isAnonymousUser(userCredentials) {
    return (
        userCredentials &&
        userCredentials.authTokenType === 'anonymousAccount'
    );
}
```

Update the `shouldDisableWriteActions` Function: In the `shouldDisableWriteActions` function, prioritize checking user authentication based on the existence of `CREDENTIALS.login` and `CREDENTIALS.validateCode.` This change reduces reliance on `session.authTokenType`.
Below is the path for file and code
https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js

```
function shouldDisableWriteActions(report, userCredentials) {
    const reportErrors = getAddWorkspaceRoomOrChatReportErrors(report);

    // Check if the user is authenticated using CREDENTIALS.login and CREDENTIALS.validateCode
    const isAuthenticated = !!userCredentials && !!userCredentials.login && !!userCredentials.validateCode;

    // Additional conditions and logic for disabling write actions
    return (
        isArchivedRoom(report) ||
        !_.isEmpty(reportErrors) ||
        !isAllowedToComment(report) ||
        !isAuthenticated
    );
}
```

Backend Solution (if necessary):

Address Backend Inconsistencies: Investigate and address the root cause of the backend inconsistency where leaving a room results in an `incorrect session.authTokenType`. Implement measures to ensure that user authentication data is consistently and accurately updated.
By implementing these frontend adjustments and, if necessary, addressing backend inconsistencies, you can create a more reliable and resilient authentication and user experience in your application. These changes will help prevent the recurrence of the issue where the signup modal is displayed incorrectly.

Video:
https://drive.google.com/file/d/1_JvY6K3QzcFRzkldx0z8uxuOnaT7DI5I/view?usp=sharing

**Comment by jliexpensify** [comment] 2023-09-06 06:52
Not overdue, but @sobitneupane we have some proposals rolling in!

**Comment by pradeepmdk** [comment] 2023-09-06 08:06
### Proposal
### Please re-state the problem that we are trying to solve in this issue.

Opening the #teachers-unite room directly through the link shows sign in option even when signed 
### What is the root cause of that problem?
authTokenType = 'anonymousAccount' not removing from onyx state 
![Screenshot 2023-09-06 at 1 05 53 PM](https://github.com/Expensify/App/assets/16595846/0b8bfbbf-dbab-47d5-aaf2-21e4ee3b651d)
 when we set Onyx.merge('session', {'authTokenType': null}); means that key should be removed from database but not happing when set this callback triggered without null but database not updating.

### What changes do you think we should make in order to solve the problem?

we should be update the backend passing the empty string for update the onyx 
frontend means:
signinapi success data we should update this empty string;
```javascript
authTokenType:  ''
``` 

Note: after login and refresh the page means it will ask again signin .


this ONYX BUG:
Onyx.merge('session', {'authTokenType': null}); when you set this null means database is not updated. 
but sub level is accepted here 
 Onyx.merge('session', {'authTokenType':{data: null}}); when you set this null means database  will allow to insert

**Comment by sobitneupane** [comment] 2023-09-11 08:00
Thanks for the proposal everyone.

@pradeepmdk Would you mind explaining your proposal. I am trying to understand your proposal. But I am not sure if I am getting your point.

> when we set Onyx.merge('session', {'authTokenType': null}); means that key should be removed from database but not happing when set this callback triggered without null but database not updating.

Where are we calling `Onyx.merge('session', {'authTokenType': null})`? Is the issue existent on Onyx? What is the issue?

**Comment by pradeepmdk** [comment] 2023-09-12 04:04
@sobitneupane already we have PR for this fix https://github.com/Expensify/react-native-onyx/pull/333 we should wait for merging after the upgrade of the onyx lib so this will work.

**Comment by jliexpensify** [comment] 2023-09-12 23:19
Sure thing @sobitneupane and @pradeepmdk - bump me when you want this taken off hold!

**Comment by jliexpensify** [comment] 2023-09-18 00:41
Still on hold

**Comment by pradeepmdk** [comment] 2023-09-26 02:01
@sobitneupane  this is fixed on this version 1.0.89. can I raise the pr for the upgraded version?

**Comment by sobitneupane** [comment] 2023-09-26 04:07
@pradeepmdk I don't think we need to raise PR here. I will be raised in the associated issue for which PR was raised.

**Comment by pradeepmdk** [comment] 2023-09-26 04:56
@sobitneupane this issue was solved only when we upgraded React native Onyx version 1.0.89.

**Comment by sobitneupane** [comment] 2023-09-27 09:22
We will wait for it to update from the associated issue.

**Comment by pradeepmdk** [comment] 2023-09-27 09:25
@sobitneupane Actually I only commented on that. based on my comment they raised the PR.
https://github.com/Expensify/react-native-onyx/pull/333
https://github.com/Expensify/react-native-onyx/pull/333#issuecomment-1722726499
https://github.com/Expensify/react-native-onyx/pull/359

**Comment by pradeepmdk** [comment] 2023-09-28 22:12
@sobitneupane this is fixed now.

**Comment by jliexpensify** [comment] 2023-10-06 03:51
@pradeepmdk thanks for letting us know. Just tried on v1.3.78-4 and can verify it's fixed.

Going to pay @adeel0202 for reporting and then close this out.

**Comment by jliexpensify** [comment] 2023-10-06 03:56
Payment Summary

- Reporter: @adeel0202 $50

[Upworks Job](https://www.upwork.com/jobs/~01d5ef2b2fb5c4462d)

**Comment by jliexpensify** [comment] 2023-10-06 05:04
Paid, job closed!

**Closed by jliexpensify** 2023-10-06 05:04 UTC
Labels: External, Weekly, Awaiting Payment, Bug
