### ISSUE TITLE
[HOLD for payment 2023-10-25] [$500] Chat -  App closes mention suggestions when cursor is between double @

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28754] opened 2023-10-03 21:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Open the app
2. Open any report
3. Write  @, it will trigger mention suggestions
4. Write any letter, number or symbol after it
5. Take it cursor back to position after the @ and observe that app again displays mention suggestions
6. Clear everything and write double @@
7. Take cursor back to position after the first @ and observe that app does not display mention suggestions

## Expected Result:
App should display mention suggestions according to cursor position and text before it

## Actual Result:
App does not display mention suggestions even though @ is present before cursor if @ is also present after cursor

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6481bf51-2a24-4455-9480-dfb517e1db51

https://github.com/Expensify/App/assets/93399543/9b2ffc9a-75df-46f0-ad67-7e98fc4913c4

https://github.com/Expensify/App/assets/93399543/e22e5d60-ef05-45de-8d38-9cdefc64e15a

https://github.com/Expensify/App/assets/93399543/eb8e062b-1873-4578-a337-d0605dc6d9d5

https://github.com/Expensify/App/assets/93399543/a3803ced-3dab-49ff-ac6b-c2662fce899c

https://github.com/Expensify/App/assets/93399543/10d925fb-918c-48a1-ae7d-16441a340f76

https://github.com/Expensify/App/assets/93399543/7c316550-8402-4288-bed1-d5d4ec524af7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696338120628179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e08f14329a2fd98</li>
        <li>Upwork Job ID: 1709321185861791744</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 27123369</li>
<li>dhanashree-sawant | Reporter | 27123379</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-10-03 21:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Placing a caret in-between `@` signs doesn't show the suggestions.  

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/a4f4a7708ba9c2ca7f2d03604c7962c4f3e69def/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L218-L224

### What changes do you think we should make in order to solve the problem?
First of all, it would be nice to know if this is not an expected behavior.

If not – we can remove the `isCursorBeforeTheMention` check as it's not used anywhere else.


### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2023-10-03 23:17
Hey team! Do you think this GH has the same root and therefore the same fix? https://github.com/Expensify/App/issues/28753

**Comment by paultsimura** [comment] 2023-10-03 23:35
Hey @Christinadobrzyn , even though I'm not a part of the Internal team:
https://github.com/Expensify/App/issues/28753 is a regression from the recently merged https://github.com/Expensify/App/pull/28045

And this issue (https://github.com/Expensify/App/issues/28754) existed relatively long before that regression – at least since https://github.com/Expensify/App/pull/25758.

**Comment by paultsimura** [comment] 2023-10-10 23:05
PR's ready: https://github.com/Expensify/App/pull/29239

**Comment by paultsimura** [comment] 2023-10-17 06:51
Melvin, the PR was waiting on the Engineer's approval and merge only. It was ready in 2 days🫡

**Comment by mallenexpensify** [comment] 2023-10-17 21:51
@paultsimura in the future, if you disagree with Melvin (which happens... occassionally) please link to time stamps in the PR. ie. 
- C+ approved PR Oct 12 - https://github.com/Expensify/App/pull/29239#pullrequestreview-1674949005
- No other changes were needed between C+ approval and PR being merged (I think this is correct, from what I can see.  It's a necessary part for reconsidering timing). 
- Internal engineer merged Oct 16th - https://github.com/Expensify/App/pull/29239#pullrequestreview-1681434081

**Comment by paultsimura** [comment] 2023-10-18 07:00
> @paultsimura in the future, if you disagree with Melvin (which happens... occassionally) please link to time stamps in the PR.

Thank you, noted ✅

**Comment by paultsimura** [comment] 2023-10-18 18:39
> ⚠️ Looks like this issue was linked to a **Deploy Blocker** [here](https://github.com/Expensify/App/issues/29884)
> 
> If you are the assigned CME please investigate whether the linked PR caused a regression and leave a comment with the results.
> 
> If a regression has occurred and you are the assigned CM follow the instructions [here](https://stackoverflow.com/c/expensify/questions/13647).
> 
> If this regression could have been avoided please consider also proposing a recommendation to the PR checklist so that we can avoid it in the future.

Responded in the referenced PR.

**Comment by mallenexpensify** [comment] 2023-10-26 17:01
Issue reporter: @dhanashree-sawant paid $50 via Upwork
Contributor: @paultsimura paid $750 via Upwork, inc. urgency bonus (see [above](https://github.com/Expensify/App/issues/28754#issuecomment-1767246598)) @dhanashree-sawant paid $ via Upwork
Contributor+: @parasharrajat due $750 via NewDot

@parasharrajat , can you please fill out the BZ checklist?  Thx

**Comment by madmax330** [comment] 2023-10-30 16:35
@mallenexpensify can you review the BZ checklist when you get a chance?

**Comment by mallenexpensify** [comment] 2023-10-30 23:38
Thanks @parasharrajat !
Regression test GH
- https://github.com/Expensify/Expensify/issues/331503 

[Payment confirmation](https://github.com/Expensify/App/issues/28754#issuecomment-1781504241) above is complete and up to date

**Closed** 2023-10-30 23:38 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-12-11 01:28
$750 payment approved for @parasharrajat based on [this comment](https://github.com/Expensify/App/issues/28754#issuecomment-1781504241).
