### ISSUE TITLE
[$250] Web - Settings/About - "View keyboard shortcuts" is missing in the minimal window

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12571] opened 2022-11-08 21:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> About
4. Verify that "View keyboard shortcuts" is present
5. Minimize the window

## Expected Result:
"View keyboard shortcuts" should be present

## Actual Result:
"View keyboard shortcuts" is missing

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.25.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![full (1)](https://user-images.githubusercontent.com/93399543/200684079-43bd86e4-7c49-4917-8fe0-dee051e4fd3f.png)
![Min](https://user-images.githubusercontent.com/93399543/200684081-385f69b5-3676-4e1e-a466-89c4bd1d24e4.png)

https://user-images.githubusercontent.com/93399543/200684083-fbb7d0b6-a544-4c0b-909e-570547ba0cbc.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment] 2022-11-09 10:28
Well I think that's the feature, not a bug.
https://github.com/Expensify/App/blob/7e8a00d1dbeddb02795bd69161a96e3d63ceef89/src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.js#L1-L15

In case we want to fix this, we can remove checking the isSmallScreenWidth in `getPlatformSpecificMenuItems/index.js` or passing the value `false` to `getPlatformSpecificMenuItems` function in `AboutPage.js`.

```diff
- export default (isSmallScreenWidth) => { 
+  export default () => { 
-     if (isSmallScreenWidth) { 
-         return []; 
-     } 
     return [ 
         { 
             translationKey: 'initialSettingsPage.aboutPage.viewKeyboardShortcuts', 
             icon: Expensicons.Keyboard, 
             action: KeyboardShortcuts.showKeyboardShortcutModal, 
         }, 
     ]; 
 };
```
or in `AboutPage.js`:
```diff
-const platformSpecificMenuItems = getPlatformSpecificMenuItems(props.isSmallScreenWidth);
+const platformSpecificMenuItems = getPlatformSpecificMenuItems(false);
```

https://user-images.githubusercontent.com/16502320/200806364-c6757775-6739-4081-9cec-824867b5f431.mov

**Comment by alexpensify** [comment] 2022-11-10 00:37
@AndrewGable - Assigning External, but can you verify if this is a feature or a bug? Thanks!

**Comment by s77rt** [comment] 2022-11-10 12:45
### Proposal
```diff
diff --git a/src/pages/settings/AboutPage/AboutPage.js b/src/pages/settings/AboutPage/AboutPage.js
index 3ac1564a6..90f708289 100644
--- a/src/pages/settings/AboutPage/AboutPage.js
+++ b/src/pages/settings/AboutPage/AboutPage.js
@@ -26,7 +26,7 @@ const propTypes = {
 };
 
 const AboutPage = (props) => {
-    const platformSpecificMenuItems = getPlatformSpecificMenuItems(props.isSmallScreenWidth);
+    const platformSpecificMenuItems = getPlatformSpecificMenuItems();
 
     const menuItems = [
         {
diff --git a/src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.js b/src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.js
index 52f8ffa22..1e9aad641 100644
--- a/src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.js
+++ b/src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.js
@@ -1,8 +1,9 @@
 import * as KeyboardShortcuts from '../../../../libs/actions/KeyboardShortcuts';
 import * as Expensicons from '../../../../components/Icon/Expensicons';
+import * as Browser from '../../../../libs/Browser';
 
-export default (isSmallScreenWidth) => {
-    if (isSmallScreenWidth) {
+export default () => {
+    if (Browser.isMobile()) {
         return [];
     }
     return [
```

### Details
Conditions that are based on the keyboard are tricky and hard to implement
The safest and the closest things to do is to relay on the user agent.
- Using the window size will fail for small browser windows (this issue)
- Using the touch screen feature will fail for laptops that have touch screen support (@0xmiroslav)

- Using the user agent will cover both issues listed above.

@hungvu193 removing the condition as you suggested will not only fix the bug, but will remove the entire feature.


https://user-images.githubusercontent.com/16493223/201094504-e881e1c6-0241-4884-af16-10704a336a21.mp4

**Comment by s77rt** [comment] 2022-11-10 13:23
I'm not familiar with that component enough to give you my thoughts on that. But in general if compA is implemented in the wrong way does not mean that all follow components must be implemented that wrong way, eventually we will have to fix them all.
I think using `canUseTouchScreen()` for mobile detection is not ideal because as the name suggests, it will tell you if that device has a touch screen or not, not necessary a mobile, i'm aware i described a edge case but still.
To determine if mobile or not, something like that would be better (pseudo code):
```
if (platform is ios or android) {
    return true;
}
if (platform is web) {
    return useragent.isMobile();
}
return undefined;
```

**Comment by thesahindia** [comment] 2022-11-10 16:49
@AndrewGable, I am not sure what we should be done here but we have https://github.com/Expensify/App/issues/6883 to allow using keyboard shortcuts on native devices. I think we should close this issue and leave this to https://github.com/Expensify/App/issues/6883 since it will also revert https://github.com/Expensify/App/pull/6881 which added this logic.

**Comment by mananjadhav** [comment] 2022-11-10 16:51
Thanks for the comment @thesahindia. I was just finding the link because I knew we had a task for keyboard shortcuts to work on native devices. @alexpensify @AndrewGable  I think we can close this in the favour of the linked issue, or atleast put it on Hold.

**Comment by alexpensify** [comment] 2022-11-11 02:16
Closing this in favor of the other issue listed here.

**Closed by alexpensify** 2022-11-11 02:16 UTC
Labels: External, Daily, Help Wanted, Bug
