### ISSUE TITLE
[HOLD for payment 2023-11-06] [$500] Android- 2FA- Input filed hides behind the keyboard

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26695] opened 2023-09-04 17:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Security > Two-factor authentication
2. Copy code and click on Next button

## Expected Result:
Input filed should not behind the keyboard same as other platforms

## Actual Result:
Input filed hide behind the keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b1a869be-191b-4460-9768-98f0f0d7323c

https://github.com/Expensify/App/assets/93399543/38b45167-3a30-484a-9a32-8ae3b45e480b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693029869469049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014386eb856f1f9542</li>
        <li>Upwork Job ID: 1701881478410055680</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by akinwale** [comment] 2023-09-14 22:22
> @akinwale Are we using such pattern anywhere else in our app?

@allroundexperts I could not find anywhere else this pattern is being used. I did find a `KeyboardSpacer` component however, which tries to do something similar with the Keyboard events (adjusting its height), but this component is not being used anywhere. I attempted to place this component at the end of the scroll view, but it still doesn't push the input area up when the keyboard is shown.

**Comment by akinwale** [comment] 2023-09-14 22:36
## Proposal
[Updated](link to proposal)

I've updated my proposal with a second solution. Here's a video showing how that would work. Note that the entire screen (including the footer) will be scrollable when the soft keyboard is visible.

[26695-solution-2.webm](https://github.com/Expensify/App/assets/4160319/fdae5dce-1d5b-4009-aae0-a9312fc1ff42)

**Comment by akinwale** [comment] 2023-09-25 10:17
@allroundexperts bump

**Comment by mvtglobally** [comment] 2023-09-28 03:19
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2023-10-05 03:06
Issue not reproducible during KI retests. (Second week)

**Comment by JmillsExpensify** [comment] 2023-10-10 23:02
Odd that the issue isn't reproducible by QA, but in any case, I think the linked Slack discussion has wrapped up.

**Comment by JmillsExpensify** [comment] 2023-10-16 17:53
@allroundexperts thoughts on this updated proposal?

**Comment by akinwale** [comment] 2023-10-20 03:04
@roryabraham Shall we move forward with this?

**Comment by roryabraham** [comment] 2023-10-20 18:00
It's unclear to me which of the 4 solutions in that proposal we are aligned on here.

**Comment by akinwale** [comment] 2023-10-20 18:02
> It's unclear to me which of the 4 solutions in that proposal we are aligned on here.

Solution 4, based on the discussion in the Slack thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1695719446849569?thread_ts=1695719446.849569&cid=C01GTK53T8Q

**Comment by roryabraham** [comment] 2023-10-20 18:06
ok, I'm not sure I gleaned the same conclusion from the slack thread but solution 4 seems ok to me. Can we be sure to test with the smallest device we can find like an iPhone mini and ensure that the text isn't hidden behind the magic code input when the page first loads?

So let's say the plan is solution 4, but then if the text is hidden behind the magic code input on a very small device, then we pivot and go back to solution 1.

**Comment by akinwale** [comment] 2023-10-20 18:10
> ok, I'm not sure I gleaned the same conclusion from the slack thread but solution 4 seems ok to me. Can we be sure to test with the smallest device we can find like an iPhone mini and ensure that the text isn't hidden behind the magic code input when the page first loads?
> 
> So let's say the plan is solution 4, but then if the text is hidden behind the magic code input on a very small device, then we pivot and go back to solution 1.

I'll verify on a 1st gen iPhone SE simulator. Solution 3 achieves the same result as Solution 1, but with less code, so I'll probably go with that if there's a need for it.

**Comment by akinwale** [comment] 2023-10-20 22:16
@roryabraham This is what it looks like with the Solution 4 approach on the 1st gen iPhone SE simulator. Should we move forward with this?

https://github.com/Expensify/App/assets/4160319/27518f70-b27d-455b-81ad-281c5e22955f

**Comment by roryabraham** [comment] 2023-10-23 18:39
Yeah looks fine to me 👍🏼 

Let's move forward with the PR

**Comment by akinwale** [comment] 2023-10-24 03:03
@allroundexperts My [PR](https://github.com/Expensify/App/pull/30227) is ready for review. Should be a quick one. 🙏🏽

**Comment by JmillsExpensify** [comment] 2023-10-24 18:11
PR review on-going

**Comment by JmillsExpensify** [comment] 2023-11-08 12:28
@allroundexperts Do you mind kicking off the BZ checklist?

**Comment by roryabraham** [comment] 2023-11-13 21:53
@JmillsExpensify bump for payment

**Comment by JmillsExpensify** [comment] 2023-11-22 18:31
Doesn't look like this one got merged in three days, which gives us the following payment summary:

 - Issue reporter: $50 @gadhiyamanan
 - Contributor: $500 @akinwale 
 - Contributor+: $500 @allroundexperts 

If that looks good to everything then I'll issue payouts.

**Comment by JmillsExpensify** [comment] 2023-11-22 19:09
I've sent upwork offers because I didn't see any automatic ones that went out. cc @gadhiyamanan @akinwale

**Comment by gadhiyamanan** [comment] 2023-11-23 05:23
@JmillsExpensify i think reporting bonus should be $250 because it was reported before 30Aug  

![image](https://github.com/Expensify/App/assets/54790231/db1e953f-6eb2-4127-bf94-54bd54c517cd)

**Comment by JmillsExpensify** [comment] 2023-11-24 16:00
@gadhiyamanan That makes sense. Please accept the offer and I'll pay out accordingly.

**Comment by gadhiyamanan** [comment] 2023-11-24 16:03
@JmillsExpensify offer accepted, thanks!

**Comment by JmillsExpensify** [comment] 2023-11-24 16:04
Everyone paid out! Will close after creating the regression test.

**Comment by JmillsExpensify** [comment] 2023-11-24 16:33
Regression test done, so closing!

**Closed by JmillsExpensify** 2023-11-24 16:33 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
