### ISSUE TITLE
Expense - Missing react & reply in thread for system message in one transaction report view

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39459] opened 2024-04-02 22:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat that has no unsettled report.
3. Create a manual request.
4. Click on the request preview to go to one transaction report view.
5. Edit the amount or any other field.
6. Right click on the system message.
7. Note that there is no option to react and reply in thread.
8. Create a second request.
9. Go to transaction thread of first request.
10. Right click on the system message.
11. Now there is option to react and reply in thread.

## Expected Result:
System message for request edit should have the option to react and reply in thread in one transaction report view.

## Actual Result:
System message for request edit does not have the option to react and reply in thread in one transaction report view.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f9d0b249-7210-4896-ad0f-3d9bf4f6df03

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-04-02 22:49
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment] 2024-04-03 13:42
I dont think this has to be a blocker cc @NikkiWines 

Its not really blocking users so much they can normally comment in the report they are in.

**Comment by mountiny** [comment] 2024-04-03 13:43
@NikkiWines I think it might be tricky to allow threading from that comment, as its technically on different report than you are seeing. Going to that thread (which cannot be created now), we would need to make sure the report header links to the expense report and not to the thansaction thread 🤔

**Comment by NikkiWines** [comment] 2024-04-03 17:50
Oof, yeah that's another complexity I don't think we considered when designing this view. We might need to raise in slack the best way to handle this 🤔  I didn't even realize you could comment on system messages 😅 

But yes for now, not a blocker.

**Comment by NikkiWines** [comment] 2024-04-05 18:01
I'm actually not seeing this behavior any more on staging, though i might be seeing a new bug where threads created on the transaction-level system messages can't be deleted. But we also had a bug around deleting messages show up recently so I'm not sure if it's specific to this view or not

(threading and reacting) 
https://github.com/Expensify/App/assets/16747822/96618402-61bc-4a10-bbed-57d858ea8cab

(trying to delete the response)
https://github.com/Expensify/App/assets/16747822/d50a801c-6125-4899-8ec3-bd49e6ad333d

**Comment by thienlnam** [comment] 2024-04-05 18:03
@NikkiWines Can I reassign this to you since it seems like you have the context for this?

**Comment by NikkiWines** [comment] 2024-04-08 18:23
Confirmed that the re-appearing deleted comment occurs on both the single and multiple transaction reports, so it's not a bug tied to the one-transaction view. Looks like we can close this out since the react + reply functionality works fine in both views 👍 

(Standard (multiple) transaction report) 

https://github.com/Expensify/App/assets/16747822/94d98156-ed76-4b95-8aad-3fe760984195

(One-transaction report) 

https://github.com/Expensify/App/assets/16747822/0cced3cf-ceb2-4049-9e27-e47da69f7ccd

**Closed by NikkiWines** 2024-04-08 18:23 UTC
Labels: Engineering, Daily, Improvement, Overdue
