### ISSUE TITLE
Web / Firefox -  Incorrect font on preferred pronouns dropdown in edit profile

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12891] opened 2022-11-21 16:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to edit profile page
2. Open the preferred pronouns dropdown
3. Notice the font is incorrect

## Expected Result: 
The font should be correct

## Actual Result: 
The font is incorrect

## Workaround:
unknown
## Platform:

Where is this issue occurring?

- Web - Firefox

**Version Number:** 1.2.29-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="960" alt="07" src="https://user-images.githubusercontent.com/43996225/203101249-95b3761f-375b-433c-a593-bc08fa51e700.png">

https://user-images.githubusercontent.com/43996225/203101289-6eab0767-2623-4811-92a4-16c5fb385c7c.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668903175494289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment] 2022-11-22 16:50
I can't reproduce, the font looks correct on staging and in production

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/17131195/203373320-a498b4b3-b798-4e51-bd47-86da04ebc029.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/17131195/203371329-cc0bae26-f075-4186-9eb6-540456c64aa8.png">

**Comment by sonialiap** [comment] 2022-11-22 16:55
Can't reproduce, font looks correct on staging in Firefox:

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/17131195/203374173-e0670e41-c814-4a5b-9be7-7851e1af4047.png">

Steps taken:
1. Download Firefox
2. https://staging.new.expensify.com
3. Login
4. Go to Settings > Profile > Pronouns

**Comment by sonialiap** [comment] 2022-11-22 16:55
@kavimuru are you still seeing the incorrect font?

**Comment by sonialiap** [comment] 2022-11-25 11:12
I'm going to close this because I can't reproduce. Feel free to reopen if you're still experiencing this issue @kavimuru!

**Comment by kavimuru** [comment] 2022-11-28 04:54
@sonialiap It happens in windows / Firefox
<img width="960" alt="2" src="https://user-images.githubusercontent.com/43996225/204196909-9da2a656-9b93-4886-bbe8-1677152e21f4.png">

**Comment by JmillsExpensify** [comment] 2022-11-28 15:24
Firefox isn't an officially supported browser, so closing.

**Closed by JmillsExpensify** 2022-11-28 15:24 UTC
Labels: Daily, Bug
