### ISSUE TITLE
[HOLD for payment 2024-09-19][CRITICAL]: Add Pay as Business option for invoices sent to any individual

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#41974] opened 2024-05-10 10:45 UTC
Held on https://github.com/Expensify/App/issues/40438

# Part of the **Invoicing V0.3** project
Main issue: https://github.com/Expensify/Expensify/issues/341717
Doc section: [Invoicing V1](https://docs.google.com/document/d/1HhnjCVUVN8gw3vfxRA4jCXXQvuIfm1puMhzHoOKe5jY/edit#bookmark=id.1pnsna7h8vtu)
Project: [#vip-billpay](https://join.slack.com/share/enQtNjkzNDU4NTI3OTY4Ni03M2RlY2IwNzhjMDEzMGE1NjZmYmM5MGJmZDZmNTc4NjRhYmRlOWM4NzMzYmJmOGUyZDAzNWFiNTgyNjQ0YTg0)

# Feature Description
Enable the Pay as business option in the App for all individuals and optimistically create a collect workspace and set it as primary workspace, when they are not an admin of the primary workspace.

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @VickyStash</details>

**Comment by VickyStash** [comment] 2024-08-09 07:11
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by cristipaval** [comment] 2024-08-09 08:54
I added @jjcoffee as the C+ for this issue since he already has a lot of context on this and did great testing recently.

**Comment by VickyStash** [comment] 2024-08-12 15:18
**Updates:**
- I've added a workspace with related chats creation if the user pays as a business but is not the admin of the primary workspace. The updates can be tracked in this [branch](https://github.com/VickyStash/Expensify/tree/feature/41974-business-pay-invoice).

@cristipaval 
1) Should I optimistically update primary policy (`nvp_expensify_activePolicyID` onyx key)?
2) Should  I optimistically create a whisper message about the created workspace?
![image](https://github.com/user-attachments/assets/fcb02535-f866-4d3c-acc7-eac7aac34e8c)

**Comment by VickyStash** [comment] 2024-08-14 15:22
**Note:** I'm going to be OOO tomorrow (15th of Aug).

@cristipaval Please take a look at my questions above when you have a moment

**Comment by cristipaval** [comment] 2024-08-15 09:52
> * Should I optimistically update primary policy (`nvp_expensify_activePolicyID` onyx key)?
> * Should  I optimistically create a whisper message about the created workspace?

@VickyStash yes to both questions from above

**Comment by VickyStash** [comment] 2024-08-16 14:03
**Updates:** I was focused on other issues, but I'm going to make some updates for this one on Monday

**Comment by VickyStash** [comment] 2024-08-19 16:08
**Minor updates:** Implemented active policy id (`nvp_expensify_activePolicyID`) optimistic update

**Comment by VickyStash** [comment] 2024-08-22 14:48
**Updates:** 
- I've included more policy related params to pass to the API
- Started to combine the Draft PR: https://github.com/Expensify/App/pull/47862

**Comment by VickyStash** [comment] 2024-08-26 15:34
**Updates:**
Waiting for the API updates to open the PR for the review.

**Comment by VickyStash** [comment] 2024-08-28 16:59
The [PR](https://github.com/Expensify/App/pull/47862) has been opened for the review

**Comment by jjcoffee** [comment] 2024-09-10 07:53
@OfstadC Looks like @cristipaval is on parental leave at the moment, is it possible to get another engineer assigned to review the PR?

**Comment by mallenexpensify** [comment] 2024-09-10 21:12
@jjcoffee can you add  " 🎀 👀 🎀 C+ reviewed " to assign a new engineer plz?  i removed Cristi

**Comment by jjcoffee** [comment] 2024-09-11 08:14
:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment] 2024-09-16 13:11
[Deployed](https://github.com/Expensify/App/pull/47862#issuecomment-2347262333) to production Sept 12, so should be due for payment 2024-09-19. Since this is a `CRITICAL` feature for invoicing, I believe it also qualifies for $500, as on the other [invoicing issue](https://github.com/Expensify/App/issues/40438#issuecomment-2296189448) I worked on. cc @OfstadC

**Comment by OfstadC** [comment] 2024-09-16 18:39
Sounds accurate to me! And we need to pay @jjcoffee and @VickyStash, yes? I'll work on the Upwork offers tomorrow since I don't believe one was created for this yet

**Comment by jjcoffee** [comment] 2024-09-17 08:06
@OfstadC Thanks! No need for an Upwork offer for @VickyStash as she is from Callstack.

**Comment by OfstadC** [comment] 2024-09-18 14:04
Upwork Job - https://www.upwork.com/ab/applicants/1836405649803524751/job-details

@jjcoffee Could you please link your Upwork profile here? 😃

**Comment by jjcoffee** [comment] 2024-09-18 14:07
@OfstadC Sure, it's here https://www.upwork.com/freelancers/~01105c8ef30bb852e8

**Comment by OfstadC** [comment] 2024-09-18 15:27
Thanks! I've sent the offer [here](https://www.upwork.com/nx/wm/offer/104021840/need-more-hiring?requestUuid=efd06509330681949a59757d60d6044d&nav_dir=replace)

If you can propose any necessary regression tests, I can issue payment tomorrow 😃

**Comment by jjcoffee** [comment] 2024-09-19 07:40
**Regression Test Proposal**

1. Sign in to the app as User A.
2. Send invoices to:
- User B - who has no workspaces at all
- User C - who has a primary workspace but he is not an admin of it
3. Log in to the app as User B. Pay the invoice as business
4. Verify that a new primary workspace is created for User B and that they are the admin of it. The invoice should be paid by this workspace, and the room should be turned into a B2B invoice room.
5. Log in to the app as User C. Pay the invoice as business.
6. Verify that a new primary workspace is created for User C and that they are the admin of it. The invoice should be paid by this workspace, and the room should be turned into a B2B invoice room.

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2024-09-19 07:40
@OfstadC Offer accepted, thank you!

**Comment by OfstadC** [comment] 2024-09-19 16:20
## Payment Summary
- Paid @jjcoffee $500 via Upwork

**Closed** 2024-09-19 16:22 UTC
Labels: Reviewing, Weekly, NewFeature
