### ISSUE TITLE
[$125] Request money - The 'Enter' key fails to select the email/workspace/phone when requesting money.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34239] opened 2024-01-10 14:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Sign in to staging Expensify
2. Navigate to FAB > Request Money > Add amount, then press 'Enter' to select the email. Observe that the 'Enter' key does not work as expected

## Expected Result:
The 'Enter' key should successfully select the email during the request for money

## Actual Result:
The 'Enter' key does not select the email as intended during the request for money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1fc5c819-3efd-419f-8cee-c43224e825a4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2024-01-10 15:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't select a participant with the enter key.

### What is the root cause of that problem?
This is a regression from https://github.com/Expensify/App/pull/31354.

When we select a participant, we return early if the screen is not focused.
https://github.com/Expensify/App/blob/55746c78a6ef59d9ad636eda8c610023c3cd62ac/src/components/OptionsSelector/BaseOptionsSelector.js#L335-L341

`isFocused` value initially is false.
https://github.com/Expensify/App/blob/55746c78a6ef59d9ad636eda8c610023c3cd62ac/src/components/OptionsSelector/BaseOptionsSelector.js#L87

and updated true inside the `focus` listener, but `focus` listener is called only if the screen is re-focused, not when the page is mounted, so `isFocused` is always false.

### What changes do you think we should make in order to solve the problem?

We can set the initial value of `isFocused` to true, but we still need to duplicate the code from the `focus` listener to the `componentDidMount`

**Comment by bernhardoj** [comment] 2024-01-10 15:23
@youssef-lr should I raise the PR now?

**Comment by situchan** [comment] 2024-01-10 15:35
@hurali97 can you please check this?

**Comment by bernhardoj** [comment] 2024-01-10 17:21
@mountiny I tried switching to the commit before the PR and somehow it still didn't work, but after another refresh, the issue is gone.

**Comment by mountiny** [comment] 2024-01-10 17:57
interesting, we are reverting it so you can confirm then, thank you!

**Comment by situchan** [comment] 2024-01-10 18:13
Interesting. I am not able to reproduce this bug on main but instead enter key doesn't work on this page.
Both pages work fine on staging


https://github.com/Expensify/App/assets/108292595/6ea7576b-e064-4589-bace-a99d0449122e

**Comment by mountiny** [comment] 2024-01-10 18:18
Oh I was testing the amount page before, that was not fixed with the revert

**Comment by situchan** [comment] 2024-01-10 18:19
Seems like the revert [introduced](https://github.com/Expensify/App/issues/34269) this bug as not happening on staging 😄

**Comment by youssef-lr** [comment] 2024-01-11 00:04
Yeah I can't reproduce the original issue, but the `Enter` key in the amount page is broken.

**Comment by youssef-lr** [comment] 2024-01-11 00:07
Actually, I can only reproduce locally, but not on staging. `Enter` key is working fine in both amount page and participants selector.

**Comment by situchan** [comment] 2024-01-11 03:11
> Actually, I can only reproduce locally, but not on staging. `Enter` key is working fine in both amount page and participants selector.

yes, this will become deploy blocker on next deploy 😄

**Comment by bernhardoj** [comment] 2024-01-11 04:51
The enter doesn't work on the amount page is a regression from https://github.com/Expensify/App/pull/33055

The root cause is similar to the previous issue. The `isFocused` ref here is initially false and when we set up the config, the `isActive` is always false.
https://github.com/Expensify/App/blob/7517d7473bce2c32e2bae1cc4822d31aaa0ba267/src/components/Button/index.tsx#L153-L164

Even if the ref is updated, the config memo is never re-calculated.

It's better to use `useIsFocused` hook just like before the PR and add the focused state to the deps. We don't need to worry that it will re-render the Button component because, in that PR, we already separate the shortcut logic into a separate empty component.

But after fixing this, you will notice that pressing enter will show an invalid amount error and that is because the shortcut callback here is never recreated when `onPress` instance is updated.
https://github.com/Expensify/App/blob/7517d7473bce2c32e2bae1cc4822d31aaa0ba267/src/components/Button/index.tsx#L142-L151

The `onPress` will call `submitAndNavigateToNextPage` 
https://github.com/Expensify/App/blob/7517d7473bce2c32e2bae1cc4822d31aaa0ba267/src/pages/iou/steps/MoneyRequestAmountForm.js#L229-L233 
which will check the `currentAmount` state, but it's always empty when executed inside the shortcut callback.

So, we should add `onPress` to the shortcut callback deps.

**Comment by hurali97** [comment] 2024-01-11 07:05
@bernhardoj  Thanks for pin pointing the issue, I have raised a PR fixing this 👍

**Comment by mvtglobally** [comment] 2024-01-30 04:55
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-02-13 04:54
Issue not reproducible during KI retests. (Second week)

**Comment by youssef-lr** [comment] 2024-02-16 12:57
This was fixed.

**Closed by youssef-lr** 2024-02-16 12:57 UTC
Labels: Reviewing, Engineering, Monthly, Help Wanted, Bug
