### ISSUE TITLE
[$500] Workspace - Chat shows both removed user and invited user's message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26316] opened 2023-08-30 18:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Tap profile icon
3. Tap workspaces
4. Tap create new workspace
5. Tap members
6. Tap invite
7. Select an user
8. Tap next
9. Delete the default invite message
10. Enter any message
11. Tap invite
12. Select the invited user
13. Tap remove to remove the user
14. Tap invite
15. Enter the same removed user email id and select
16. Tap next
17. This time with "default invite" Message, tap invite
18. As secondary user, open the invite workspace chat

## Expected Result:
The workspace chat must show only invite message with which user was currently invited ie., default invite message 

## Actual Result:
The workspace chat shows previously invited and removed "custom invite message" and currently invited "default invite message"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7940226c-be2a-4772-8574-00b6eafb9759

https://github.com/Expensify/App/assets/78819774/7ee03c4a-b811-435f-8bd0-cebcd9d7591c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eabdead056f9e1af</li>
        <li>Upwork Job ID: 1699326422015164416</li>
        <li>Last Price Increase: 2023-09-20</li>
    </ul>
</details>

**Comment by anmurali** [comment] 2023-09-06 00:45
I am really swamped right now and have to prep for Saastr keynote day after at some point. So going to rotate this.

**Comment by saifali069** [comment] 2023-09-06 11:55
I want to be a  contributor for your project .

**Comment by saifali069** [comment] 2023-09-06 11:59
i want to be a contributor

**Comment by saifali069** [comment] 2023-09-06 12:01
Contributor details
Your Expensify account email: alihamza891840@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0131169e1e04804037

**Comment by saifali069** [comment] 2023-09-06 12:03
can you assign this job to me ?

**Comment by s77rt** [comment] 2023-09-06 12:22
@saifali069 Thank you for your interest here. Please checkout the [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and follow proposal template.

**Comment by yongwangd** [comment] 2023-09-06 14:57
Contributor details
Your Expensify account email: yongwang.ai@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0170075c594c192a25

**Comment by s77rt** [comment] 2023-09-11 11:12
Still looking for proposals

**Comment by s77rt** [comment] 2023-09-13 15:46
No proposals yet...

**Comment by greg-schroeder** [comment] 2023-09-18 10:56
Might send this over to SWM/CS

**Comment by s77rt** [comment] 2023-09-20 14:06
No progress on this yet Melvin

**Comment by kacper-mikolajczak** [comment] 2023-09-21 09:13
Hi, I am Kacper from Callstack and I would like to work on this issue. 🔧

**Comment by kacper-mikolajczak** [comment] 2023-09-21 10:22
### Please re-state the problem that we are trying to solve in this issue.

User should be able to see only recent Workspace invitation message.

### What is the root cause of that problem?

Response received from call to `api?command=OpenReport` holds entire history of messages in Workspace <-> User context, including ones that were removed by undoing the invitation.

### What changes do you think we should make in order to solve the problem?

In order to solve the problem, we might want to discard previous invitation messages when new invitation comes in. This should be done on backend side, as it involves changes to data integrity/storage logic. 

By doing that, we will receive correct data when calling `api?command=OpenReport`.

### What alternative solutions did you explore?

What is perceived as a bug, might ironically be a feature here - from my investigation, all invitations are made in isolation, with each invitation being separate request, possibly (quite likely) sent at various times. 

System looks like is based on those isolated requests and prohibiting such behaviour seems to be fighting against the tides. If we would like to change that, it will require system-level changes described above.

As a last resort workaround, highly not recommended, we might filter out previous messages on frontend side, but this would require frontend app to distinguish between previous and current invitation message. From my understanding is not currently possible without changing backend response from `api?command=OpenReport`, which will put us at the same spot as with original proposal :D

**Comment by s77rt** [comment] 2023-09-21 21:11
@kacper-mikolajczak Thanks for the proposal. Your RCA makes sense. I think you are right here, we have nothing to do, this is working as expected.

🎀 👀 🎀 C+ reviewed
Asking for confirmation to close this. cc @greg-schroeder

**Comment by greg-schroeder** [comment] 2023-09-25 07:19
Hey @grgia can you help confirm this should be closed per: https://github.com/Expensify/App/issues/26316#issuecomment-1730308624?

**Comment by greg-schroeder** [comment] 2023-09-28 07:27
bump @grgia can you help me confirm this?

**Comment by grgia** [comment] 2023-09-28 07:30
I think we can consider this a feature as of right now, closing.

**Closed by grgia** 2023-09-28 07:30 UTC
Labels: Engineering, Daily, Internal, Bug
