### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$1000] mWeb - Chat – Unable to zoom the image with pinching

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36597] opened 2024-02-15 15:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Interna; Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34080
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login
3. Go to a report with attachments
4. Open an (image) attachment
5. Check that image gestures/transformations are working (pinching)

## Expected Result:
Able to zoom the image with pinching

## Actual Result:
Unable to zoom the image with pinching

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ce464be6-14ca-4d7a-a2eb-598f8ae21ba6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016170309acaa20014</li>
        <li>Upwork Job ID: 1758158238713884672</li>
        <li>Last Price Increase: 2024-06-04</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 0</li>
<li>dukenv0307 | Reviewer | 102684851</li>
<li>ZhenjaHorbach | Contributor | 102711497</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by kbecciv** [comment] 2024-02-15 15:56
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by andreasnw** [comment] 2024-02-16 04:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
gestures won't work when viewing images on the web app

### What is the root cause of that problem?
the `ImageView` element on the web isn't wrapped within the `MultiGestureCanvas` component

https://github.com/Expensify/App/blob/9843f6641f65d11e125c4325df1f95feae9d1259/src/components/ImageView/index.tsx#L194-L213

### What changes do you think we should make in order to solve the problem?

when `canUseTouchScreen` is true, we make sure to enclose the `Image` component within `MultiGestureCanvas` to activate gesture functionalities while viewing images.

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2024-02-18 15:28
I can take over.

We are not yet supporting zoom image in mobile web.
Is it right time to implement this new feature?

**Comment by laurenreidexpensify** [comment] 2024-02-19 17:36
Asking internally here https://expensify.slack.com/archives/C066HJM2CAZ/p1708364190263029 whether we need to fix this

**Comment by laurenreidexpensify** [comment] 2024-02-22 10:12
Still chatting internally

**Comment by laurenreidexpensify** [comment] 2024-02-23 16:30
Bumped thread internally for further clarity

**Comment by laurenreidexpensify** [comment] 2024-02-23 16:52
@situchan confirmed internally - let's do it!

**Comment by situchan** [comment] 2024-02-23 16:54
@laurenreidexpensify thanks

**Comment by situchan** [comment] 2024-02-23 16:54
@andreasnw thanks for the proposal. Please test your solution yourself on android chrome and iOS safari.

**Comment by situchan** [comment] 2024-02-23 16:55
Waiting proposals

**Comment by andreasnw** [comment] 2024-02-25 17:12
## Proposal
[Updated](https://github.com/Expensify/App/issues/36597#issuecomment-1947749686)

**Comment by jeremy-croff** [comment] 2024-02-25 20:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We do not support gestures like pinch-zooming on mobile web.

### What is the root cause of that problem?
We have
https://github.com/Expensify/App/blob/8bdb753045cf0eee6cf1d342adf8b76040cabac4/src/components/ImageView/index.native.tsx#L3
for native devices, to support this. However this is missing for IOS/Android web as it's a new feature.

### What changes do you think we should make in order to solve the problem?
We can quite simply leverage the same code from https://github.com/Expensify/App/blob/8bdb753045cf0eee6cf1d342adf8b76040cabac4/src/components/ImageView/index.native.tsx#L3 but port it to index.ios.ts and index.android.ts to enable this feature.


### What alternative solutions did you explore? (Optional)

**Comment by jeremy-croff** [comment] 2024-02-25 22:09
## Proposal

### What is the root cause of that problem?
We only have gestures like pinch on native because of the lightbox implementation here: https://github.com/Expensify/App/blob/8bdb753045cf0eee6cf1d342adf8b76040cabac4/src/components/ImageView/index.native.tsx

### What changes do you think we should make in order to solve the problem?
1. Similar to @andreasnw, we want to replace the Image component in https://github.com/Expensify/App/blob/8bdb753045cf0eee6cf1d342adf8b76040cabac4/src/components/ImageView/index.tsx#L200

However additionally:
With the lightbox implementation exactly as defined in https://github.com/Expensify/App/blob/8bdb753045cf0eee6cf1d342adf8b76040cabac4/src/components/ImageView/index.native.tsx

2. We should clean up the native implementation as it will be a redudancy.
3. We should ensure that the new lightbox implementation for touch devices, has the default values such as zoomRange with DEFAULT_ZOOM_RANGE from '@components/MultiGestureCanvas'; As well as other's as defined in the native lightbox implementation. 
4. We can remove the existing loading logic from. https://github.com/Expensify/App/blob/8bdb753045cf0eee6cf1d342adf8b76040cabac4/src/components/ImageView/index.tsx#L212 and rely in the Lightbox's loading logic
5. We don't need a zoomScale on lightbox

### What alternative solutions did you explore? (Optional)

**Comment by jeremy-croff** [comment] 2024-02-25 22:12
proposed implementation experience:
https://github.com/Expensify/App/assets/157416545/7f1d7a51-1dc8-4cfb-ac33-8fc24b648368

**Comment by andreasnw** [comment] 2024-02-26 14:04
@jeremy-croff zoomScale is necessary to prevent tiny images from looking like this

![Simulator Screenshot - iPhone 14 - 2024-02-26 at 21 00 30](https://github.com/Expensify/App/assets/60419079/342ef517-062c-45d2-9bf3-56f89faffc37)

**Comment by jeremy-croff** [comment] 2024-02-26 14:19
> @jeremy-croff zoomScale is necessary to . The native implementation does not have this behaviour; either it's intentional, or if we want to add a scale factor, both experiencesges.githubusercontent.com/60419079/307819073-342ef517-062c-45d2-9bf3-56f89faffc37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NTY3NDQsIm5iZiI6MTcwODk1NjQ0NCwicGF0aCI6Ii82MDQxOTA3OS8zMDc4MTkwNzMtMzQyZWY1MTctMDYyYy00NWQyLTliZjMtNTZmODlmYWZmYzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE0MDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0Zjg2MGFlNWRkNDEwZmFkMGVmZDRlM2RlMzYyYTA1NmE5MzJiZWU3MGQ4YmQ1OGI2MGE1YTcxZmQwZjc5Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vg6CjitMNGlPA5VbSgW1FOM-FsdFT2ky1SElXEGUFSE)

Thanks for the example,
So my basis is that it's not a requirement, the native implementation does not have this behaviour either it's intentional, or if we want to add a scale factor both experience will need it.

**Comment by laurenreidexpensify** [comment] 2024-02-27 06:23
@situchan some new proposals to review ^^

**Comment by situchan** [comment] 2024-02-28 13:43
@andreasnw @jeremy-croff do you mind sharing test branches?

**Comment by jeremy-croff** [comment] 2024-02-28 13:55
> @andreasnw @jeremy-croff do you mind sharing test branches?

https://github.com/Expensify/App/pull/37424/files

**Comment by andreasnw** [comment] 2024-02-28 13:58
sure @situchan https://github.com/andreasnw/Expensify/tree/feat/web_app_gesture_handler

**Comment by situchan** [comment] 2024-02-29 15:17
proposals are in review & testing

**Comment by laurenreidexpensify** [comment] 2024-03-04 05:35
@situchan any update on the review and testing yet? thanks

**Comment by situchan** [comment] 2024-03-07 19:13
I will provide feedback by tomorrow.

**Comment by laurenreidexpensify** [comment] 2024-03-11 10:47
waiting on feedback from @situchan

**Comment by situchan** [comment] 2024-03-13 22:39
feedback soon

**Comment by laurenreidexpensify** [comment] 2024-03-14 10:55
@situchan any feedback here from testing?

**Comment by situchan** [comment] 2024-03-14 19:31
updating today

**Comment by situchan** [comment] 2024-03-15 11:41
On web, we want exact replication of native approach so replace Image with Lightbox on touchable devices.
@andreasnw proposed first.
@jeremy-croff I don't find significant difference from your proposal. Please let me know if I am missing anything.

**Comment by jeremy-croff** [comment] 2024-03-15 13:32
> on 

I provided about 4 bullet points of differences, included a major experience change of zoomScale. Do you confirm you don't want any of these differences?

**Comment by situchan** [comment] 2024-03-15 13:39
I checked but all of them look to me minor changes and code refactor which could be addressed in PR review and testing.

**Comment by jeremy-croff** [comment] 2024-03-15 14:29
> I checked but all of them look to me minor changes and code refactor which could be addressed in PR review and testing.

Anything can be addressed in the PR during review, and testing. I believe I added my value by drafting a complete proposal that mentioned key things that have to be done differently that were not done in the proposal. 

When we avoid these steps, the BZ cannot expect that we will address these things during the PR. 

It seems you are not missing anything, @situchan, but do want my proposed changes.  Maybe the nitpick is that you devalued my effort by saying there are no significant changes, did I just wast my time and should not have posted? Should I have suggested these things not in a proposal template? It's actually not about winning the bid, I am happy the original poster got it, but I do believe I have helped them or you.

**Comment by jeremy-croff** [comment] 2024-03-15 14:30
Additionally, why ask me for a branch if it wasn't significant of a change? The UX is actually a significant change based on the zoomScale alone

**Comment by situchan** [comment] 2024-03-15 14:34
@andreasnw @jeremy-croff please update your branches up-to-date with main based on proposals submitted. Please make sure to test yourselves and fix any issues found.
I'd like to test and approve one without any minor regression. While this being new feature, easy to cause regressions.

Regarding UX matter, it should behave exactly same as native in production version.

**Comment by andreasnw** [comment] 2024-03-15 15:32
@situchan 

updated https://github.com/andreasnw/Expensify/tree/feat/web_app_gesture_handler

**Comment by andreasnw** [comment] 2024-03-15 15:37
@situchan 

Out of the four points Jeremy mentioned, the first one seems identical to what I proposed earlier. I didn't include point three because it's quite clear - the app wouldn't function without passing the required properties. I still believe the zoomScale parameter is necessary to avoid the regressions I mentioned previously https://github.com/Expensify/App/issues/36597#issuecomment-1964222929.

**Comment by jeremy-croff** [comment] 2024-03-15 15:57
> 2\. We should clean up the native implementation as it will be a redudancy.



> @situchan
> 
> Out of the four points Jeremy mentioned, the first one seems identical to what I proposed earlier. I didn't include point three because it's quite clear - the app wouldn't function without passing the required properties. I still believe the zoomScale parameter is necessary to avoid the regressions I mentioned previously [#36597 (comment)](https://github.com/Expensify/App/issues/36597#issuecomment-1964222929).

I visually separated the first point from the remaining ones to clearly indicate that it is also part of your proposal!

And yep, the third point you're right about and shouldn't be a detractor.

I'm curious if the zoomScale is desired. It's a major part of your proposal's complexity, but to determine its validity, I brought in native testing for parity to confirm it would actually behave differently from the original. Hence, I view it as a regression, not a feature, since there are no established requirements for this yet.

**Comment by situchan** [comment] 2024-03-18 21:20
Not overdue

**Comment by laurenreidexpensify** [comment] 2024-03-21 14:42
I think this is fine to remain as external for now if we have a chance of resolving. Adding help wanted back. 

@situchan what are you thinking re: latest proposals

**Comment by situchan** [comment] 2024-03-22 10:59
> @jeremy-croff zoomScale is necessary to prevent tiny images from looking like this
> 
> ![Simulator Screenshot - iPhone 14 - 2024-02-26 at 21 00 30](https://private-user-images.githubusercontent.com/60419079/307819073-342ef517-062c-45d2-9bf3-56f89faffc37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDQ3NTUsIm5iZiI6MTcxMTEwNDQ1NSwicGF0aCI6Ii82MDQxOTA3OS8zMDc4MTkwNzMtMzQyZWY1MTctMDYyYy00NWQyLTliZjMtNTZmODlmYWZmYzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEwNDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNzU1NTFjMTZlOTQxNWU3MGFjYmJjM2NlZjg2YzYxMDA4MTliZGI5MTIxZDQzYjUwNDI0NGRhZjUwMmExNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r9V8xdSAdVAeOKT64lYaIGtQZP1a8l2wms2S7Oy1-HA)

@andreasnw your solution still doesn't fix this.

**Comment by situchan** [comment] 2024-03-22 11:06
@jeremy-croff same feedback ^ unless [this](https://github.com/Expensify/App/pull/37424) isn't your up-to-date branch

**Comment by situchan** [comment] 2024-03-22 11:07
@laurenreidexpensify can we double the bounty? We should consider many cases to avoid any regressions.

**Comment by andreasnw** [comment] 2024-03-22 11:39
@situchan , can you confirm whether you've defined zoomScale and applied validation to resizeMode in your code? 
```jsx
const zoomScale = Math.min((canvasSize?.width ?? 0) / (contentSize?.width ?? 0), (canvasSize?.height?? 0) / (contentSize?.height ?? 0));
```

```jsx
 <MultiGestureCanvas
                                isActive={isActive}
                                canvasSize={canvasSize}
                                contentSize={contentSize}
                                zoomRange={zoomRange}
                                pagerRef={pagerRef}
                                shouldDisableTransformationGestures={isPagerScrolling}
                                onTap={onTap}
                                onScaleChanged={scaleChange}
                            >
                                <Image
                                    source={{uri}}
                                    style={contentSize ?? DEFAULT_IMAGE_DIMENSION}
                                    isAuthTokenRequired={isAuthTokenRequired}
                                    onError={onError}
                                    onLoad={updateContentSize}
                                    onLoadEnd={() => {
                                        setLightboxImageLoaded(true);
                                    }}
                                    resizeMode={zoomScale > 1 ? RESIZE_MODES.center : RESIZE_MODES.contain}
                                />
                            </MultiGestureCanvas>
```

The problem seems to have been resolved on my device after both these changes.

https://github.com/Expensify/App/assets/60419079/0991b2c8-740b-4043-b0e2-fea8bc0b23ea

**Comment by situchan** [comment] 2024-03-22 12:48
@andreasnw yes, I tested https://github.com/Expensify/App/compare/main...andreasnw:Expensify:feat/web_app_gesture_handler

Here's image:

<img width="106" alt="tiny" src="https://github.com/Expensify/App/assets/108292595/a94065d6-b9a7-4509-9168-7d983a31b678">

**Comment by andreasnw** [comment] 2024-03-22 14:50
sorry @situchan , still unable to reproduce this on android native with latest main branch. it has the same behavior as the mweb.

https://github.com/Expensify/App/assets/60419079/0c1fd027-3084-4710-b5d6-dfe83dc6d4d5

**Comment by laurenreidexpensify** [comment] 2024-03-25 16:02
Increased bounty

**Comment by jeremy-croff** [comment] 2024-03-28 02:28
> @jeremy-croff same feedback ^ unless [this](https://github.com/Expensify/App/pull/37424) isn't your up-to-date branch

In regards to the "swiping-up" for closing the attachment preview, that was implemented for native approx a month ago: https://github.com/Expensify/App/pull/37080
It's not really related to pinching or lightbox, but if we want to include that feature as well it will be simple as we just need to pass in the onClose call back context for the web flow. I pushed that to my branch so that it starts behaving the same.

https://github.com/Expensify/App/assets/157416545/415063c5-9a3a-4d6e-9921-96f7599b6d9d

In regards to testing everything else, I'm not seeing any major issues or gaps. I've tested it thoroughly. 
However, I found that  PDF's have separate implementations for mobile and web,  so I see that pinching to zoom doesn't work there yet on my branch either.

**Comment by situchan** [comment] 2024-03-28 10:39
@jeremy-croff please check this video. Not able to move to prev/next image via horizontal swipe when not zoomed.


https://github.com/Expensify/App/assets/108292595/4acf8830-18d1-4621-8a12-c1ec4daeaffe

**Comment by mallenexpensify** [comment] 2024-04-01 16:30
@situchan is out OOO, reassigning a C+ via the auto-assigner for fairness.

**Comment by abdulrahuman5196** [comment] 2024-04-07 17:25
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-04-07 17:51
There are 2 proposals here 
1) @andreasnw 's proposal here https://github.com/Expensify/App/issues/36597#issuecomment-1947749686
2) @jeremy-croff 's proposal here https://github.com/Expensify/App/issues/36597#issuecomment-1963077617

On first look, both the proposals are more than 1 month old. And the second proposal is almost similar to 1st.

I also saw multiple discussions around potential solution.


I would request the contributors to update the proposal as per your latest suggestion and add the custom branches which they have already build.

**Comment by laurenreidexpensify** [comment] 2024-04-10 09:28
Waiting for proposal updates

**Comment by laurenreidexpensify** [comment] 2024-04-15 13:01
Waiting for proposals

**Comment by jsdev2547** [comment] 2024-04-16 10:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After opening attachment, on touch screen devices user is unable to zoom the image with pinching.

### What is the root cause of that problem?
For touch screen devices and mobile, the Image is not handling zooming by pinch.

https://github.com/Expensify/App/blob/8bdb753045cf0eee6cf1d342adf8b76040cabac4/src/components/ImageView/index.tsx#L200

### What changes do you think we should make in order to solve the problem?
To zoom the image by using pinch, the PinchGestureHandler needs to be implemented from 'react-native-gesture-handler'.

```
            <Animated.View style={{flex: 1}}>
                <PinchGestureHandler
                    ref={pinchRef}
                    onGestureEvent={onPinchGestureEvent}
                    onHandlerStateChange={onPinchHandlerStateChange}
                >
                    <Animated.View
                        style={[styles.imageViewContainer, styles.overflowHidden]}
                        onLayout={onContainerLayoutChanged}
                    >
                        <Animated.Image
                            source={{uri: isAuthTokenRequired ? addEncryptedAuthTokenToURL(url) : url}}
                            style={[
                                styles.w100,
                                styles.h100,
                                {
                                    transform: [{scale: scale}],
                                },
                            ]}
                            resizeMode={zoomScale > 1 ? RESIZE_MODES.center : RESIZE_MODES.contain}
                            onLoadStart={imageLoadingStart}
                            onLoad={imageLoad}
                            onError={onError}
                        />
                        {(isLoading || zoomScale === 0) && <FullscreenLoadingIndicator style={[styles.opacity1, styles.bgTransparent]} />}
                    </Animated.View>
                </PinchGestureHandler>
            </Animated.View>
```

### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment] 2024-04-17 11:43
@abdulrahuman5196 bump for review ^^

**Comment by laurenreidexpensify** [comment] 2024-04-22 12:33
@abdulrahuman5196 bump for review ^^

**Comment by abdulrahuman5196** [comment] 2024-04-23 11:34
Checking now

**Comment by laurenreidexpensify** [comment] 2024-04-25 11:50
@abdulrahuman5196 bump for review ^^

**Comment by badeggg** [comment] 2024-04-26 07:43
After reading through the whole thread and digging some related code, I don't think it's a good idea to reimplement pinch-to-room feature dedicated for mWeb. Lightbox is an implementation currently used on native, we should use it on mWeb too. While some bugs must be fixed when used on mWeb.

[proposal here](https://github.com/Expensify/App/issues/36597#issuecomment-1947749686) and [here](https://github.com/Expensify/App/issues/36597#issuecomment-1963077617) are doing the similar thing just in difference that "some bugs must be fixed when used on mWeb". The feedback from c+ is that they are similar and both have potential regressions.

I don't dare to put more effort into fixing "bugs that must be fixed when used on mWeb" because I'm afraid getting feedback like "you proposal only has minor changes compared to others and those minor changes and code refactor could be addressed in PR review and testing" like comment in [here](https://github.com/Expensify/App/issues/36597#issuecomment-1999689039)

Can I get clarification about this?

**Comment by abdulrahuman5196** [comment] 2024-04-29 12:24
Checking again

**Comment by abdulrahuman5196** [comment] 2024-04-30 14:55
Checking now

**Comment by abdulrahuman5196** [comment] 2024-04-30 15:14
@jsdev2547 Could you share the test code you had used in a separate branch? It would be time consuming to re-create the proposal for testing.

**Comment by jsdev2547** [comment] 2024-04-30 17:34
@abdulrahuman5196 Please use [branch](https://github.com/jsdev2547/App/tree/pinchZoomImage) for testing. I have tested pinch zoom on ios and android. To test pinch zoom use Option or Control key + left mouse btn.

**Comment by jsdev2547** [comment] 2024-04-30 17:37
@abdulrahuman5196 For testing, please use [branch](https://github.com/jsdev2547/App/tree/pinchZoomImage). I have tested pinch zoom on ios and android. To test pinch zoom use Option or Control key + left mouse btn.

**Comment by badeggg** [comment] 2024-05-01 16:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On mWeb, we can not pinch-to-zoom picture attachments.

### What is the root cause of that problem?
new feature

### What changes do you think we should make in order to solve the problem?
**First of all, LightBox (`src/components/Lightbox/index.tsx`) has implemented pinch-image feature, and native platforms are using it. We definitely don't want to re-create a wheel for mWeb.**

1. In file `src/components/ImageView/index.tsx`, when [touch screen is usable](https://github.com/Expensify/App/blob/a7db2260975ca64734de9fe45ae2d007d0a249fa/src/components/ImageView/index.tsx#L195), we should use `LightBox` instead of `Image`
2. We should wrap [FlatList here](https://github.com/Expensify/App/blob/a7db2260975ca64734de9fe45ae2d007d0a249fa/src/components/Attachments/AttachmentCarousel/index.tsx#L188) in `AttachmentCarouselPagerContext.Provider` and provide proper value. [Problem here](https://github.com/Expensify/App/issues/36597#issuecomment-2014841315) (swiping down the image didn't navigate back to report page) is because mWeb implement carousel pager with react-native built-in `FlatList` and do not provide a AttachmentCarouselPagerContext while native is using `PagerView` of react-native-pager-view in a separative file and provide a proper AttachmentCarouselPagerContext. The AttachmentCarouselPagerContext value should be something like:
```
    const toggleArrows = useCallback(
        (showArrows?: boolean) => {
            if (showArrows === undefined) {
                setShouldShowArrows((prevShouldShowArrows) => !prevShouldShowArrows);
                return;
            }

            setShouldShowArrows(showArrows);
        },
        [setShouldShowArrows],
    );

    const pagerItems = useMemo(() => attachments.map((item, index) => ({source: item.source, index, isActive: index === page})), [page, attachments]);
    const isPagerScrolling = useSharedValue(false);
    const isScrollEnabled = useSharedValue(canUseTouchScreen);
    const scale = useRef(1);

    const scrollHandler = useAnimatedScrollHandler((event) => {
        const { contentOffset } = event;
        isPagerScrolling.value = contentOffset.x !== 0;
    });

    const handleTap = useCallback(() => {
        if (!isScrollEnabled.value) {
            return;
        }

        toggleArrows();
    }, [isScrollEnabled.value, toggleArrows]);

    const handleScaleChange = useCallback(
        (newScale: number) => {
            if (newScale === scale.current) {
                return;
            }

            scale.current = newScale;

            const newIsScrollEnabled = newScale === 1 && canUseTouchScreen;
            if (isScrollEnabled.value === newIsScrollEnabled) {
                return;
            }

            isScrollEnabled.value = newIsScrollEnabled;
            toggleArrows(newIsScrollEnabled);
        },
        [isScrollEnabled, toggleArrows],
    );

    const contextValue = useMemo(
        () => ({
            pagerItems,
            activePage: page,
            isPagerScrolling,
            isScrollEnabled,
            pagerRef: scrollRef,
            onTap: handleTap,
            onSwipeDown: onClose,
            onScaleChanged: handleScaleChange,
        }),
        [pagerItems, page, isPagerScrolling, isScrollEnabled, handleTap, onClose, handleScaleChange],
    );

```
3. Other small changes:
    - We must handle tap like implementation on native(which is shown in code above) to consider scale situation(e.g. when zoom in a image, tap should not show arrows), and delete  [line](https://github.com/Expensify/App/blob/a7db2260975ca64734de9fe45ae2d007d0a249fa/src/components/Attachments/AttachmentCarousel/index.tsx#L148)
    - import necessary component and values
    - define necessary values
    - amend `AttachmentCarouselPagerContextValue`

### What alternative solutions did you explore? (Optional)
N/A

**Comment by badeggg** [comment] 2024-05-01 16:51
- LightBox has implemented pinch-image feature, and native platforms are using it. We definitely don't want to re-create a wheel for mWeb.
- Since my [concern here](https://github.com/Expensify/App/issues/36597#issuecomment-2078817519), I must say that my proposal is **not just similar** to [proposal here](https://github.com/Expensify/App/issues/36597#issuecomment-1947749686) and [here](https://github.com/Expensify/App/issues/36597#issuecomment-1963077617) , I tuned several non-negligible situation that must be considered when pinch-image feature is up for mWeb
- I can create a test branch if needed

**Comment by abdulrahuman5196** [comment] 2024-05-03 18:08
Hi will check the test branch and new proposal in my morning

**Comment by abdulrahuman5196** [comment] 2024-05-05 08:03
Hi, I don't have bandwidth to work on this issue. Unassigning myself.

@laurenreidexpensify Kindly reassign the external label, so that a C+ is assigned randomly.

**Comment by laurenreidexpensify** [comment] 2024-05-07 07:55
@dukenv0307 ypu've been assigned as new C+ - pls confirm if you good to take over. thanks

**Comment by laurenreidexpensify** [comment] 2024-05-08 11:27
Thanks @dukenv0307 pls review latest proposals and provide an update

**Comment by badeggg** [comment] 2024-05-08 12:00
I noticed that some other changes need be made besides the changes listed in my proposal. I will update my proposal in a few days and provide a test branch. Fixing this issue involves too much.

**Comment by jsdev2547** [comment] 2024-05-09 11:52
@dukenv0307 Please also review [proposal](https://github.com/Expensify/App/issues/36597#issuecomment-2058744675) and test [branch](https://github.com/jsdev2547/App/tree/pinchZoomImage).

**Comment by jsdev2547** [comment] 2024-05-09 12:01
@dukenv0307 I have test [branch](https://github.com/jsdev2547/App/tree/pinchZoomImage) and [proposal](https://github.com/Expensify/App/issues/36597#issuecomment-2058744675) ready for review.

**Comment by badeggg** [comment] 2024-05-10 08:14
I am canceling my proposal, because I have run into severe struggling to do lots of workaround. I can share my [_work-in-pregress code branch_](https://github.com/Expensify/App/compare/main...badeggg:expensify-App:fix-36597) if it help the issue.

Unexpected situations(if I'm correct):
- Unable to make FlatList to be part of react-native-gesture-handler's gesture system. 
That's why we can't swipe to switch after change `Image` to `Lightbox`, like [this](https://github.com/badeggg/expensify-App/blob/243153df17f6ed8c73cdf6916553c3f409af6ac8/src/components/ImageView/index.tsx#L198)
I have tried every possible way I can imagine.
So we have to do scrolling by self

-  `manualActivation(true)` of `Gesture.Pan()` not working on mWeb, react-native-gesture-handler version 2.14.1.
Later versions(2.15.0, 2.16.0, 2.16.1, 2.16.2) lead to ios build crash.
We have to manage active state by self.

- double tap `.numberOfTaps(2)` not working on chrome for iOS, does work on safari on iOS
If we want to be compatible with chrome for iOS, one solution is to count tap number
 by hand. Or maybe a latter version of react-native-gesture-handler will be ok,
current react-native-gesture-handler version is 2.14.1. Also notice that few later
versions(2.15.0, 2.16.0, 2.16.1, 2.16.2) lead to iOS build crash.

- react-native-gesture-handler@2.14.1 may not reporting 'allTouches' when onTouchesMove correctly
on mWeb, stale touch may exist.

- maybe more...





cc @dukenv0307 and everyone here

**Comment by jsdev2547** [comment] 2024-05-10 11:02
@dukenv0307 I have added pan gesture handler to test [branch](https://github.com/jsdev2547/App/tree/pinchZoomImage). The image can be dragged or zoomed using pinch.

**Comment by jscoder2151** [comment] 2024-05-20 08:54
@dukenv0307 Please test [branch](https://github.com/jscoder2151/App/tree/handleImageZoom). I have included pan and pinch gesture handlers.

**Comment by laurenreidexpensify** [comment] 2024-05-21 08:10
Still working through solutions

**Comment by jscoder2151** [comment] 2024-05-22 12:18
@dukenv0307 I was able to get the lines when dragging the image. The lines glitch was due to isZoomed prop not getting set. I have resolved the glitch and revised test [branch](https://github.com/jscoder2151/App/tree/handleImageZoom). Please test revised branch.

**Comment by jscoder2151** [comment] 2024-05-23 13:48
@dukenv0307 I have attached video

[android-web.webm](https://github.com/Expensify/App/assets/169826533/8e7bf052-79f9-459b-aed5-d9bf5741ede8)

**Comment by laurenreidexpensify** [comment] 2024-05-24 11:21
Still working through proposals

**Comment by laurenreidexpensify** [comment] 2024-05-28 08:50
Still working through proposals

**Comment by jscoder2151** [comment] 2024-05-30 06:59
@dukenv0307 I have resolved the issue with large image when zooming the image would not zoom and then not pan. Also revised branch.

[android-web.webm](https://github.com/Expensify/App/assets/169826533/f38b8fdb-91be-477a-9a4b-0c796cb7908e)

**Comment by badeggg** [comment] 2024-05-30 08:53
Maybe I'll update my proposal soon, just maybe...

**Comment by laurenreidexpensify** [comment] 2024-05-30 10:45
Still waiting / working through proposals

**Comment by laurenreidexpensify** [comment] 2024-06-04 11:26
Still waiting to finalise proposals

**Comment by jscoder2151** [comment] 2024-06-06 08:58
> Some minor feedbacks before I can accept your proposal
> 1. We should not zoom out the image to be invisible.
> 2. After zoom in, we should not drag the image out of its box

@dukenv0307 I have both the issues resolved, video attached, also revised branch.

[android_web.webm](https://github.com/Expensify/App/assets/169826533/77ca22d3-3eb9-4de0-81ca-b886c6e63e1f)

**Comment by jscoder2151** [comment] 2024-06-07 08:22
@dukenv0307 In the previous video, the image could be dragged down and out of the box and using spring effect was moved back in the box. In the video, the image can no longer be dragged down and out of the box only when zoomed the image can be dragged to the edge but not out of the box.

**Comment by laurenreidexpensify** [comment] 2024-06-07 11:46
Still waiting to finalise proposals

**Comment by jscoder2151** [comment] 2024-06-07 13:17
@dukenv0307 On native please try dragging zoomed image on the y axis. The zoomed image does get dragged out of the box and is moved back in the box using spring effect. I have used clamp effect to limit the zoomed image from leaving the box, but I can use the spring effect along x and y axis so the the zoomed image moves back in the box using spring effect.

[android_web.webm](https://github.com/Expensify/App/assets/169826533/9beaca27-0ed9-49dd-a516-fc55785c3c47)

**Comment by laurenreidexpensify** [comment] 2024-06-10 10:30
Still waiting to finalise proposals

**Comment by jscoder2151** [comment] 2024-06-11 09:19
@dukenv0307 I have added spring effect along x and y axis, the zoomed image springs back if moved out of the box. Added video and also revised branch.

[android_web.webm](https://github.com/Expensify/App/assets/169826533/9b4ec2db-634d-4ddc-9b39-1654dd659359)

**Comment by jscoder2151** [comment] 2024-06-11 10:43
@laurenreidexpensify I get message 'job is no longer available on upwork'. Please open job or send offer to https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by laurenreidexpensify** [comment] 2024-06-11 11:21
@dukenv0307 @jscoder2151 updated upwork link - https://www.upwork.com/jobs/~012edca6feab8f4800

**Comment by jscoder2151** [comment] 2024-06-11 11:45
@laurenreidexpensify I have sent proposal on upwork please accept.

**Comment by badeggg** [comment] 2024-06-18 03:54
If the bug I noticed does not exist any more, maybe it's because dependency version updating.

And, just curious, why the assigned contributor is not the one who proposed the c+ accepted proposal.

**Comment by mallenexpensify** [comment] 2024-07-18 00:27
Contributor: @ZhenjaHorbach paid $1000 via Upwork
Contributor+: @dukenv0307 paid $1000 via Upwork. 

@dukenv0307 plz complete the BZ checklist above.

**Comment by mallenexpensify** [comment] 2024-07-19 00:30
Thanks @dukenv0307 
TestRail update
- https://github.com/Expensify/Expensify/issues/413867

**Closed by mallenexpensify** 2024-07-19 00:30 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
