### ISSUE TITLE
[HOLD for payment 2024-08-07] [$500] Onyx updates are not being queued in the correct order

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#37560] opened 2024-02-29 19:34 UTC
## Problem
When batching update operations (e.g. when coming online), Onyx executes the merge and mergeCollection operations in an incorrect order which leads to data inconsistency. See [this comment](https://github.com/Expensify/App/pull/35268#issuecomment-1961066610) for context.
## Why do we care?
This has caused multiple issues: [this](https://github.com/Expensify/App/issues/33544#issuecomment-1868286445), [this](https://github.com/Expensify/App/issues/28737), and is currently holding [this](https://github.com/Expensify/App/issues/34686).
## What's expected?
The updates should happen in the same exact order as they've been enqueued to guarantee the eventual consistency of the data.

Note: this will probably involve working with the `react-native-onyx` repository

**Issue reported by:** @paultsimura 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1709229991663269?thread_ts=1705484273.717249&cid=C01GTK53T8Q
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fec4289917eb6d71</li>
        <li>Upwork Job ID: 1763289951731056640</li>
        <li>Last Price Increase: 2024-02-29</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>paultsimura | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by blimpich** [comment] 2024-02-29 19:51
@jjcoffee I assigned @paultsimura without proposal since based off [this conversation](https://expensify.slack.com/archives/C01GTK53T8Q/p1709235311515299?thread_ts=1705484273.717249&cid=C01GTK53T8Q). @paultsimura is going to work on this with help from @tgolen.

**Comment by paultsimura** [comment] 2024-02-29 23:10
Hey @tgolen, I'd like to discuss potential ways of fixing this (actually, only one of them worked for me).

This simple change fixes the issue:

```diff
- return clearPromise.then(() => Promise.all(_.map(promises, (p) => p())));
+ return clearPromise.then(() => _.reduce(promises, (p, fn) => p.then(fn), Promise.resolve()));
```

https://github.com/Expensify/react-native-onyx/blob/8cca556b08bf858c17a7d4f5ddd2879ac3f456d4/lib/Onyx.js#L1518


However, it makes all the batched changes execute in sequence, not in parallel, and I guess it's not something we would like, right?

https://github.com/Expensify/App/assets/12595293/45ba5b74-d4cb-4cbd-8494-7345c5722990

**Comment by paultsimura** [comment] 2024-03-01 12:17
Okay, so I've spent a ton of time trying different approaches: using the `SyncQueue,` using the `idb-keyval`'s `update` method, as well as merging each collection key separately instead of bulk.
Unfortunately, nothing worked as expected, and I'm running out of ideas and just wasting a lot of time testing different approaches. 
I think we should make it external and see if somebody can suggest a proper solution here @tgolen.
I will be happy to provide the steps to consistently reproduce the bug though.

**Comment by paultsimura** [comment] 2024-03-05 10:55
Melvin, I'm doing my best with the PR 🙂

**Comment by Christinadobrzyn** [comment] 2024-03-08 03:29
PR is in the works!

**Comment by Christinadobrzyn** [comment] 2024-03-11 04:58
PR is in the works!

**Comment by Christinadobrzyn** [comment] 2024-03-13 03:40
PR in the works!

**Comment by Christinadobrzyn** [comment] 2024-03-14 03:37
The [PR](https://github.com/Expensify/react-native-onyx/pull/490) looks like it's being reviewed so I'm going to add the reviewing label.

**Comment by Christinadobrzyn** [comment] 2024-03-20 07:21
monitoring PR https://github.com/Expensify/react-native-onyx/pull/490

**Comment by Christinadobrzyn** [comment] 2024-03-25 08:31
monitoring PR https://github.com/Expensify/react-native-onyx/pull/490

**Comment by Christinadobrzyn** [comment] 2024-04-02 09:26
monitoring PR https://github.com/Expensify/react-native-onyx/pull/490

**Comment by Christinadobrzyn** [comment] 2024-04-04 08:16
keeping an eye on the PR

**Comment by Christinadobrzyn** [comment] 2024-04-08 06:34
I think https://github.com/Expensify/App/pull/38114 is merged. 

@paultsimura what is next with this? Anything you'd like me to retest?

**Comment by shahinyan11** [comment] 2024-04-25 09:30
HI there. I recently worked on a problem with the same root cause and came up with a solution that differs from the current implementation in [PR](https://github.com/Expensify/react-native-onyx/pull/490).  So I took to share it with you, maybe you will like it.

The main logic is - Add new `mergeUpdates` function which will iterate on updates array and merge all updates with the same key, giving priority to the object whose index is greater. You can see example of `mergeUpdates` function [here](https://github.com/Expensify/App/issues/39354#issuecomment-2033044260)

**Comment by Christinadobrzyn** [comment] 2024-05-08 09:03
looks like we're monitoring - https://github.com/Expensify/react-native-onyx/pull/523

**Comment by Christinadobrzyn** [comment] 2024-05-14 09:01
monitoring - https://github.com/Expensify/react-native-onyx/pull/523

**Comment by Christinadobrzyn** [comment] 2024-05-21 07:49
monitoring - https://github.com/Expensify/react-native-onyx/pull/523

**Comment by mallenexpensify** [comment] 2024-06-03 17:05
[Posted on the PR](https://github.com/Expensify/App/issues/40589) for 👀 from Tim (if it's a priority)

**Comment by Christinadobrzyn** [comment] 2024-06-05 08:40
Monitoring - https://github.com/Expensify/react-native-onyx/pull/490#issuecomment-2145716489

**Comment by Christinadobrzyn** [comment] 2024-06-12 09:10
Monitoring - https://github.com/Expensify/react-native-onyx/pull/490#issuecomment-2145716489

Just a heads up - I'm going to be ooo until June 24th. I'm not going to assign anyone new but if you need a new BZ teammate for any reason please feel free to ask for one to be assigned here.

**Comment by tgolen** [comment] 2024-06-21 17:10
# Weekly Update
- There was a discussion about how to do regression testing with this change [here](https://github.com/Expensify/App/pull/44010#issuecomment-2179109852)
- @paultsimura closed https://github.com/Expensify/App/pull/44010 but I am not sure why. @paultsimura what is the plan with that now?

### Next Steps
- @paultsimura Get an App PR with an ad-hoc build that points to the react-native-onyx code and have Applause do some regression testing against that

#### ETA
- Merged by Wednesday, July 3 (plenty of time for regression testing and any additional bug fixes)

**Comment by tgolen** [comment] 2024-06-24 20:28
Ah, that's a real bummer. I'm sorry to hear that you weren't able to get any further on this. For now, I will close this issue and maybe someone can reopen it if they are able to bring it back to life.

**Comment by Christinadobrzyn** [comment] 2024-07-16 23:29
Thanks for the update @paultsimura!

**Comment by Christinadobrzyn** [comment] 2024-07-23 23:58
Just checking in on this since Melvin will be asking soon - @paultsimura @tgolen do we have an update on this. TY!

**Comment by tgolen** [comment] 2024-07-24 14:08
All the regression testing was finished and no issues were found. The onyx PR was merged an included in version 2.0.57 of Onyx. The current version of Onyx that App is using is 2.0.56, so @paultsimura needs to update App to use this new version of Onyx. Once that's done, then this issue can be closed.

**Comment by tgolen** [comment] 2024-07-24 14:33
I think you need to open a PR. There are no regular bumps for that. @mountiny might know if there are any currently open PRs that bump the version, but I am not aware of any.

**Comment by mountiny** [comment] 2024-07-25 23:36
We have just merged a PR from @hannojg but I dont think he started a bump PR yet. So we should make sure we will test for all the merged PRs in onyx compared to the one used in App now

**Comment by tgolen** [comment] 2024-07-26 16:03
I don't think we need to have a C+ if it's just a version bump.

**Comment by Christinadobrzyn** [comment] 2024-08-06 22:55
Payouts due:

- [ ] Contributor: $250 @paultsimura (Upwork offer - https://www.upwork.com/nx/wm/offer/101149714)
- [ ] Contributor+: $250 @jjcoffee (Upwork offer - https://www.upwork.com/nx/wm/offer/101149710)

Do we need a regression test @paultsimura?

**Comment by jjcoffee** [comment] 2024-08-07 07:26
@Christinadobrzyn No payment due to me as I never reviewed anything in the end :pray:

**Comment by Christinadobrzyn** [comment] 2024-08-07 15:35
Thanks @paultsimura and @jjcoffee - are we paying someone else? @sobitneupane I see you on the PR, were you the C+ for this?

**Comment by Christinadobrzyn** [comment] 2024-08-07 15:49
Ah okay! Thanks @paultsimura! 

I paid this out based on this [payment summary](https://github.com/Expensify/App/issues/37560#issuecomment-2272295560). The [regression test](https://github.com/Expensify/Expensify/issues/418518) is created so I think this is good to close. Let me know if I'm missing anything!

**Closed by Christinadobrzyn** 2024-08-07 15:49 UTC
Labels: External, Daily, Awaiting Payment, Bug
