### ISSUE TITLE
 [HOLD for payment 2023-11-17] [$500] Distance - Route Rerender and Waypoints grey out when add an empty stop

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30176] opened 2023-10-23 13:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rakshitjain13
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697893765172309

## Action Performed:
1. Click '+' icon on LHS Bar
2. Click on Request Money
3. Select Distance Tab
4. Click on Start and fill Mumbai , Maharashtra , India
5. Click on Finish and fill Delhi ,India
6. Click on Add Stop
7. Don't type anything , just click on Save and Observe

## Expected Result:
Route should not get re-render and waypoints fields should not be grey out

## Actual Result:
Route getting fetched again and waypoints fields become grey out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/6e9f167d-0438-488b-972a-52b518bc1b6c

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/83ce0166-6879-4911-9098-1121a0e4f28b

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/0f0e4eeb-f6ed-4a43-93eb-e72ddb26a102

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/3916d891-da5a-4872-8c47-cffe804ee6f6

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/8b11a96f-f191-4f3b-be85-31edede1cec3

https://github.com/Expensify/App/assets/93399543/42b773cb-d281-44fc-8c2d-99a0395c87d5

https://github.com/Expensify/App/assets/93399543/3feb401b-954c-40a7-b642-c32b92ca2f58

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/28b3213d-e0b7-4c56-9834-7708f6e2cdbc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0133cf45668e492c7f</li>
        <li>Upwork Job ID: 1716448459730763776</li>
        <li>Last Price Increase: 2023-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 27480023</li>
<li>rakshitjain13 | Reporter | 27480027</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-10-23 13:37
Proposal by: @rakshitjain13
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1697893765172309

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Route Rerender and Waypoints grey out when add an empty stop
### What is the root cause of that problem?
In ```src/pages/iou/WaypointEditor.js``` we allow empty waypoint and do a removeWaypoint Transaction
https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/iou/WaypointEditor.js#L136-L138
In removeWaypoint function , we update the onyx state and set coordinates to null
https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/libs/actions/Transaction.ts#L104-L155
Now in ```src/components/DistanceRequest/index.js``` we check if the route is present or not.
https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/components/DistanceRequest/index.js#L86
As in removeWaypoint we have removed route the below situation become true and leads to refetch
https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/components/DistanceRequest/index.js#L90-L91
### What changes do you think we should make in order to solve the problem?
We should not to do any transaction on empty waypoint thus this can be done by removing these lines
https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/iou/WaypointEditor.js#L136-L138
Solution Video:
https://github.com/Expensify/App/assets/54314936/2dcee9f5-a7fe-4c14-9867-60b25656c4f5

### What alternative solutions did you explore? (Optional)
We can cache the distance Coordinates and use that again if waypoints didn't change

**Comment by paultsimura** [comment] 2023-10-23 14:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When adding an empty waypoint, existing waypoints flicker

### What is the root cause of that problem?
We are executing a transaction Onyx operation on waypoint removal here:

https://github.com/Expensify/App/blob/1c6b610f211060904ec6976be363f4e88ede7329/src/pages/iou/WaypointEditor.js#L136-L138



### What changes do you think we should make in order to solve the problem?

We should add an early return in case if no waypoint was removed here:

```diff
    const removed = waypointValues.splice(index, 1);
+    if (removed.length === 0) {
+        return;
+    }
```

https://github.com/Expensify/App/blob/01016dcaf4da744fe554cc839b47b5780f01c637/src/libs/actions/Transaction.ts#L104-L113



### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-10-24 08:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Route Rerender and Waypoints grey out when add an empty stop

### What is the root cause of that problem?
Let's see this logic
https://github.com/Expensify/App/blob/4430ae2a37728c8996776310f6944dbeaa7a3216/src/pages/iou/WaypointEditor.js#L135-L138

Currently, with this logic, the user can remove the waypoint by clearing the search input and clicking save button.

Other way, this logic causes this bug because removeWaypoint function make the route is fetch again

### What changes do you think we should make in order to solve the problem?

In here
https://github.com/Expensify/App/blob/4430ae2a37728c8996776310f6944dbeaa7a3216/src/pages/iou/WaypointEditor.js#L135-L138
We only run removeWaypoint if the user edits the old waypoint. If user click add stop button (create new waypoint) and leave the input empty and click save, we will don't run removeWaypoint function 

Note that: Current logic, we have Start point (index: 0) and finish point (index: 1), when clicking Add Stop the App will redirect to WaypointEditor with index: 2

So that if waypointIndex < _.size(allWaypoints) It mean that user are editing old waypoint.

Update code like this
```
if (waypointValue === '' && waypointIndex < _.size(allWaypoints)) {
            Transaction.removeWaypoint(transactionID, waypointIndex);
        }
```




### What alternative solutions did you explore? (Optional)

**Comment by neil-marcellini** [comment] 2023-10-25 23:05
Removing form the project since it's a very minor bug and more related to performance (preventing re-renders)

**Comment by sakluger** [comment] 2023-10-28 01:11
Hey @eVoloshchak, looks like we have a few proposals to review, mind taking a look on Monday?

**Comment by eVoloshchak** [comment] 2023-10-30 12:13
I think we should proceed with @paultsimura's [proposal](https://github.com/Expensify/App/issues/30176#issuecomment-1775289490) 
This is the most simple and straightforward approach

🎀👀🎀 C+ reviewed!

**Comment by NikkiWines** [comment] 2023-10-30 21:27
Oh, that's an interesting point about the `Save` button. When an address is added, the user doesn't actually click `Save` (on any platform, at least from my tests) to use the address. So, the only reason the user would press that button is if the value is empty or the user is offline. 

I don't think we should completely hide the button, but I think it's more in line with our existing forms to disable that button when there's no value entered instead of allowing the user to "save" a value that doesn't exist. 

If the re-render issue still exists when using `<` to go back (which it doesn't seem to), we could implement one of the above proposals. 

@sakluger @neil-marcellini @eVoloshchak, what do you think?

**Comment by paultsimura** [comment] 2023-10-30 21:47
@NikkiWines handling an empty waypoint was implemented specifically to allow removing existing waypoints (in edit mode) by entering an empty value. It's a handy feature, and disabling the "save" button for empty values will basically remove this feature, won't it?


https://github.com/Expensify/App/assets/12595293/e34fd566-c941-46a3-a73c-3f0f05727766

**Comment by NikkiWines** [comment] 2023-10-30 22:10
Ah good point, @paultsimura, that's fair. Though, IMO, that's a bit of an odd flow to go through to remove a waypoint. But I wasn't involved in the design for this feature, so I'll lean on @neil-marcellini's expertise here to determine how we want to move forward

**Comment by paultsimura** [comment] 2023-10-30 22:26
> that's a bit of an odd flow to go through to remove a waypoint

Just my 5 cents here: I have been using this feature a lot during development – it's much easier to remove the address & submit than to click three dots – remove the waypoint – confirm the popup.

**Comment by neil-marcellini** [comment] 2023-11-01 16:44
I was tagged from Slack to check this out, so let's discuss in [the thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1698856026807879).

**Comment by NikkiWines** [comment] 2023-11-01 22:52
@neil-marcellini clarified the expected flow in that thread and sounds like we do allow pressing `Save` with an empty input to remove a waypoint. In that case, @paultsimura's proposal looks good!!

**Comment by paultsimura** [comment] 2023-11-02 13:14
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/30754

**Comment by NikkiWines** [comment] 2023-11-09 00:51
Doesn't appear to be the root cause of the blocker 👍

**Comment by paultsimura** [comment] 2023-11-13 15:01
@NikkiWines the PR is in production already, but the automation didn't update the [HOLD for payment] title, could you please check? 🙏

**Comment by NikkiWines** [comment] 2023-11-13 22:29
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.3.97-7 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/30754

If no regressions arise, payment will be issued on 2023-11-17. :confetti_ball:

After the hold period is over and BZ checklist items are completed, please complete any of the applicable payments for this issue, and check them off once done.
- [ ] External issue reporter
- [ ] Contributor that fixed the issue
- [ ] Contributor+ that helped on the issue and/or PR

**Comment by NikkiWines** [comment] 2023-11-13 22:31
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@eVoloshchak] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@eVoloshchak] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@eVoloshchak] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@eVoloshchak] Determine if we should create a regression test for this bug.
- [ ] [@eVoloshchak] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@sakluger] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by NikkiWines** [comment] 2023-11-13 22:35
Not sure why it didn't get updated, looks like everything was linked appropriately. Added all the requisite details

**Comment by rakshitjain13** [comment] 2023-11-21 11:44
@NikkiWines Friendly Bump

**Comment by NikkiWines** [comment] 2023-11-21 18:17
@sakluger can you issue payments here please 🙇

**Comment by sakluger** [comment] 2023-11-22 01:55
Sorry for the delay! I've paid out the reporter and contributor. @eVoloshchak mind finishing the BZ checklist then requesting payment via manual request?

**Comment by eVoloshchak** [comment] 2023-11-22 15:39
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27496
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27496/files#r1402251064
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed in this case
-  Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No_
The bug has near-zero impact, doesn't break the UX and doesn't prevent user from using the app, I think a regression test is not needed here

**Comment by JmillsExpensify** [comment] 2023-11-22 18:20
Issue is missing a payment summary.

**Comment by sakluger** [comment] 2023-11-22 19:08
@JmillsExpensify here you go!

**Summarizing payouts for this issue:**

Reporter: @rakshitjain13 $50 (paid via Upwork)
Contributor: @paultsimura $500 (paid via Upwork)
Contributor+: @eVoloshchak $500 (requires payment via Manual Request)

**Comment by JmillsExpensify** [comment] 2023-11-23 17:39
$500 payment approved for @eVoloshchak based on comment above.

**Closed** 2023-11-27 17:44 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
