### ISSUE TITLE
[HOLD for payment 2023-10-25] [$500] IOU - In Header Workspace, members are not shown and IOU delivered to them

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27090] opened 2023-09-09 16:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Login secondary device
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap workspaces
4. Tap any workspace
5. Invite a member
6. Navigate to LHN
7. Open Workspace chat
8. Tap request money and create an IOU
9. Tap header -members to note number of members and details
10. Open invited member account - primary device
11. Open Workspace chat

## Expected Result:
In header of Workspace chat, all members should be shown. And IOU created must to delivered to its members

## Actual Result:
In header of Workspace chat, member are not shown. And IOU created in Workspace chat, not delivered to its members

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9509cc20-cc20-4308-8a8d-042a371512a5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b02d428c60467905</li>
        <li>Upwork Job ID: 1704060529674792960</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by dylanexpensify** [comment] 2023-09-12 11:26
reviewing today

**Comment by dylanexpensify** [comment] 2023-09-19 07:55
[Posted in slack internal](https://expensify.slack.com/archives/C02NK2DQWUX/p1695110107215079) to have someone test since you need two android phones!

**Comment by zukilover** [comment] 2023-09-19 10:26
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
In Header Workspace, members are not shown and IOU delivered to them

### What is the root cause of that problem?
It does not show the complete members because the list of participants is only derived from the report instance itself, and not from the workspace data:

https://github.com/Expensify/App/blob/56271f0b1a60a2ea17b418b458648bbdf4fde483/src/pages/ReportParticipantsPage.js#L96-L99

### What changes do you think we should make in order to solve the problem?
If this is a report from a workspace, we should populate the members from the correct policy members, e.g.:

- connect with the policy members information:
```
policyMembers: {
            key: (props) => `${ONYXKEYS.COLLECTION.POLICY_MEMBERS}${props.report.policyID}`,
        },
```

- populate workspace members:
```
const getMemberOptions = () => {
        let result = [];

        _.each(props.policyMembers, (_, accountID) => {
            const details = props.personalDetails[accountID] || {};

            result.push({
                keyForList: accountID,
                accountID: Number(accountID),
                text: details.displayName,
                displayName: details.displayName,
                alternateText: details.login,
            });
        });

        result = _.sortBy(result, (value) => (value.text || '').toLowerCase());

        return result;
    };
```

- and show the appropriate list of participants:
```
const data = props.report.policyID 
        ? getMemberOptions() 
        : getAllParticipants(props.report, props.personalDetails, props.translate);

const participants = _.map(data, (participant) => ({
            ...participant,
            isDisabled: ReportUtils.isOptimisticPersonalDetail(participant.accountID),
        }))
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by dylanexpensify** [comment] 2023-09-21 14:37
@burczu mind giving the above proposal a review soon? 🙇‍♂️

**Comment by burczu** [comment] 2023-09-27 08:26
Hey @zukilover! I've finally reviewed [your proposal](https://github.com/Expensify/App/issues/27090#issuecomment-1725237525) and I think it's in general correct direction. There is missing `icons` property in objects returned by `getMemberOptions` function - it crashes the app when you enter members sidebar. Also, when I have workspace with one invited participant and click the header of the workspace chat - I see three members instead of two (invited participant is shown twice) - please see the image below:

![Screenshot 2023-09-27 at 10 23 57](https://github.com/Expensify/App/assets/7771498/51454375-ae3a-4332-8988-a050b72da66e)

**Comment by zukilover** [comment] 2023-09-27 09:47
@burczu You're right. I've updated proposal to cover those cases above (i.e. missing icons, crashes, and duplicate entries).

### Proposal
[Updated](https://github.com/Expensify/App/issues/27090#issuecomment-1725237525)

**Comment by dylanexpensify** [comment] 2023-10-03 17:44
@burczu can we get re review asap please?

**Comment by burczu** [comment] 2023-10-04 06:57
Ahh, yes - I'll review it today!

**Comment by burczu** [comment] 2023-10-04 07:20
@zukilover I've just reviewed your updated proposal and can confirm that the issues I've mentioned in my previous comment are now addressed. I've noticed one more thing - when you click on header of the workspace chat and the right side appears it shows incorrect number of members in the `Members` row (please check the video below) - I think this should be also addressed in this issue to make the whole flow consistent:

https://github.com/Expensify/App/assets/7771498/a3e43e99-9ca7-4563-b975-08027d4e9a13

**Comment by zukilover** [comment] 2023-10-05 12:00
@burczu I've updated my proposal to fix the incorrect number of members.

As for the IOU delivery issue, I really think this is an API problem. Given the policyID is passed from the chat report, it should broadcast the IOU to all of the workspace members.

https://github.com/Expensify/App/blob/25f7ac14d3dcadbb60e24074494b12d181567ba3/src/libs/actions/IOU.js#L835-L839

I suggest this to be investigated as a separate issue internally.

**Comment by burczu** [comment] 2023-10-09 12:31
I've just re-reviewed [the proposal](https://github.com/Expensify/App/issues/27090#issuecomment-1725237525) from @zukilover and after update I can confirm it fixes the issue with workspace members, so I think we can proceed with it.

I also agree that the issue with not delivering IOU's to workspace members may not be related to this issue and we should treat it separately.

🎀 👀 🎀 C+ reviewed

**Comment by dylanexpensify** [comment] 2023-10-10 18:45
Nice! @deetergp to review/confirm!

**Comment by deetergp** [comment] 2023-10-11 18:50
Nice. I agree that @zukilover's proposal makes sense.

**Comment by zukilover** [comment] 2023-10-12 06:07
PR will be ready in 3 hrs

**Comment by jasperhuangg** [comment] 2023-10-17 21:26
We don't share workspace rooms with everyone in the workspace by default anymore

The fix for this issue should be reverted.

**Comment by jasperhuangg** [comment] 2023-10-17 21:29
cc @deetergp @zukilover

**Comment by jasperhuangg** [comment] 2023-10-17 21:36
@dylanexpensify 
I think we can pay everyone out as normal. There was no way they could have known.

@burczu @zukilover moving forward, let's be sure we have full context on a feature before we decide to fix it. Here, we could have used the response from the back-end to see that workspace rooms weren't being shared with everyone by default on creation anymore.

**Comment by francoisl** [comment] 2023-10-18 23:43
Hi everyone, the QA team [reported](https://github.com/Expensify/App/issues/29837#issuecomment-1768350398) that the issue is still happening on Android and iOS - can someone double-check if there's still something to fix here please?

**Comment by dylanexpensify** [comment] 2023-10-24 22:53
payment tomorrow!

**Comment by dylanexpensify** [comment] 2023-10-30 09:50
Payment Summary:

- Contributor: @zukilover $500

Please apply!

**Comment by dylanexpensify** [comment] 2023-10-30 09:50
Before payment, @zukilover @burczu can you confirm [if this is true](https://github.com/Expensify/App/issues/27090#issuecomment-1769586401)?

**Comment by zukilover** [comment] 2023-10-30 10:22
Hi @dylanexpensify, the PR has been reverted in https://github.com/Expensify/App/commit/351c98aafa675adf3640e329d3810a920829bb05, so the 'Not Fixed' comment should be irrelevant now.

Also, [the job](https://www.upwork.com/jobs/~01b02d428c60467905) in Upwork is no longer available, please advise on how to proceed with the application.

**Comment by mallenexpensify** [comment] 2023-11-01 16:06
@dylanexpensify can you address @zukilover 's comment above plz, thx

**Comment by dylanexpensify** [comment] 2023-11-06 09:16
Sorry team, was OOO sick last week! @zukilover can you confirm then if the PR caused a regression? Seems so given we had to revert?

**Comment by zukilover** [comment] 2023-11-06 09:18
@dylanexpensify The reversal was not due a regression but a decision to not include the PR at all as it was not actually required. This is a per: https://github.com/Expensify/App/issues/27090#issuecomment-1767215384

**Comment by dylanexpensify** [comment] 2023-11-06 09:24
Got it - @zukilover what's your name for Upwork invite

**Comment by zukilover** [comment] 2023-11-06 09:25
Here is my [Upwork profile](https://www.upwork.com/freelancers/~01cd037fceac95593a).

Thanks @dylanexpensify

**Comment by dylanexpensify** [comment] 2023-11-06 09:27
invited!

**Comment by dylanexpensify** [comment] 2023-11-06 09:33
Done

**Closed by dylanexpensify** 2023-11-06 09:33 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
