### ISSUE TITLE
[$500] Web - Disable button's text is overflowing in Spanish

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27577] opened 2023-09-16 14:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Click on Settings > Security > 2FA
3. Complete the setup

## Expected Result:
Different copy like "Disable 2FA" in Spanish is used or it's two lines

## Actual Result:
Text overflow is visible and part of the text is missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (42)](https://github.com/Expensify/App/assets/93399543/8976f35a-fb61-4366-b9a3-008428486067)

![image](https://github.com/Expensify/App/assets/93399543/b9fb693d-424c-4361-a4d4-975f78715de8)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684441372492789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab79eed49b9345ae</li>
        <li>Upwork Job ID: 1703049779643518976</li>
        <li>Last Price Increase: 2023-09-16</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-16 14:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Disable button's text is overflowing in Spanish 

### What is the root cause of that problem?
The text too long
### What changes do you think we should make in order to solve the problem?
Update the text to :
English: Disable 2FA
Spanish: Deshabilitar 2FA

### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment] 2023-09-21 10:23
Hmm, I think we probably still wouldn't be fixing this - I read the other GH issue and I think @jliexpensify explanation still makes sense. Closing!

**Closed by zanyrenney** 2023-09-21 10:23 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
