### ISSUE TITLE
Dev: 'Total will update when you're back online' is not displayed for send money in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18610] opened 2023-05-08 21:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to web chrome
2. Go offline
3. Go to any chat
4. First request money in a different currency and not your default currency and notice that it displays 'Total will update when you're back online'
5. But now, send money with a different currency again (and not your default curency) and notice that 'Total will update when you're back online' is not shown while sending money. Now, if you go online, it actually updates the amount in your own default currency. Thus, it should have shown the text ''Total will update when you're back online' in the previous case while sending money in offline mode

## Expected Result:
Total will update when you're back online' should also be displayed for send money in offline mode
## Actual Result:
 Total will update when you're back online' is not displayed for send money in offline mode

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236946601-782ede9d-5081-4e82-9790-09e19e33a737.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683530506313509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment] 2023-05-09 03:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev: 'Total will update when you're back online' is not displayed for send money in offline mode
### What is the root cause of that problem?
We are checking the variable `shouldShowPendingConversionMessage` in order to show the "Total will update...." message here:
https://github.com/Expensify/App/blob/5e69967c90456682a94d28dd2825d773fe851c88/src/components/ReportActionItem/IOUPreview.js#L216-L220
https://github.com/Expensify/App/blob/7fb641e058f792d2e6da62a72f2f3b25171b5416/src/components/ReportActionItem/IOUAction.js#L83-L93
At line 88, `isMostRecentIOUReportAction` is the latest `CONST.IOU.REPORT_ACTION_TYPE.CREATE` Or `CONST.IOU.REPORT_ACTION_TYPE.SPLIT` action is calculated here:
https://github.com/Expensify/App/blob/7fb641e058f792d2e6da62a72f2f3b25171b5416/src/libs/ReportActionsUtils.js#L84-L94
Because of that, we didn't calculate the latest action for `CONST.IOU.REPORT_ACTION_TYPE.PAY` request, that's why this message only shows when it's Split or Request action.
### What changes do you think we should make in order to solve the problem?
#### Solution 1:
We can implement it similar with the way we implement the prop `isMostRecentIOUReportAction`, let call it `isMostRecentIOUSendReportAction`
1. we should update `shouldShowPendingConversionMessage` condition:
```javascript
 if (
        !_.isEmpty(props.iouReport)
        && !_.isEmpty(props.reportActions)
        && props.chatReport.hasOutstandingIOU
        && (props.isMostRecentIOUReportAction || props.isMostRecentIOUSendReportAction)
        && props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD
        && props.network.isOffline
    ) {
        shouldShowPendingConversionMessage = IOUUtils.isIOUReportPendingCurrencyConversion(props.reportActions, props.iouReport);
    }
```
2. Update `isIOUReportPendingCurrencyConversion` function, because it's now only calculate the pending diff currency for type `CONST.IOU.REPORT_ACTION_TYPE.CREATE`. So the way we calculate the `pendingRequestsInDifferentCurrency` will look like this:
```javascript
    const pendingRequestsInDifferentCurrency = _.chain(getIOUReportActions(
        reportActions,
        iouReport,
        [CONST.IOU.REPORT_ACTION_TYPE.CREATE, CONST.IOU.REPORT_ACTION_TYPE.PAY],
        CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD,
        true,
    )).map(action => action.originalMessage.IOUTransactionID)
        .sort()
        .value();
    // Pending deleted money requests that are in a different currency
    const pendingDeletedRequestsInDifferentCurrency = _.chain(getIOUReportActions(
        reportActions,
        iouReport,
        [CONST.IOU.REPORT_ACTION_TYPE.DELETE],
        CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD,
        true,
    )).map(action => action.originalMessage.IOUTransactionID)
        .sort()
        .value();
```
3. Update `getIOUReportActions`'s params `types`, so we can pass the `types` as an array of actions like step 2:

```javascript
function getIOUReportActions(reportActions, iouReport, types = [], pendingAction = '', filterRequestsInDifferentCurrency = false) {
    return _.chain(reportActions)
        .filter(action => action.originalMessage
            && action.actionName === CONST.REPORT.ACTIONS.TYPE.IOU
            && (!_.isEmpty(types) ? types.includes(action.originalMessage.type) : true))
        .filter(action => action.originalMessage.IOUReportID.toString() === iouReport.reportID.toString())
        .filter(action => (!_.isEmpty(pendingAction) ? action.pendingAction === pendingAction : true))
        .filter(action => (filterRequestsInDifferentCurrency ? action.originalMessage.currency !== iouReport.currency : true))
        .value();
```
4. And finally, remove the `!isCurrentUserManager` inside `IOUPreview`.
```javascript
                    {props.shouldShowPendingConversionMessage && (
                        <Text style={[styles.textLabel, styles.colorMuted]}>
                            {props.translate('iou.pendingConversionMessage')}
                        </Text>
                    )}
```
#### Solution 2:
Update the `isMostRecentIOUReportAction` report ReportActionList props instead of creating a new props.
1. Update isMostRecentIOUReportAction props inside `ReportActionList`,`mostRecentIOUSendReportActionId` is the latest send report action.
```javascript
isMostRecentIOUReportAction={reportAction.reportActionID === mostRecentIOUReportActionID || reportAction.reportActionID === mostRecentIOUSendReportActionId}
```
2. Do the step 2,3,4 in the  <b>Solution 1</b>

### What alternative solutions did you explore? (Optional)
None.

### Result:

https://user-images.githubusercontent.com/16502320/236990092-ae2648dc-f0a0-424c-ae59-df7364f0dc8c.mov

**Comment by priya-zha** [comment] 2023-05-10 03:16
@mallenexpensify Yep, that makes sense. However, my perspective on this was, while you go online after sending the money in an offline mode, it actually updates and converts the currency as well as the amount. Thus, initially my idea was, at least it should have displayed something or alerted the user while sending money in an offline mode in a similar way how it does in the request money by displaying 'Total will update when you're back online' or any other text.

But if this was on purpose by the team and if it's not a bug, we can close this out then :smiley: :smiley:

**Comment by mallenexpensify** [comment] 2023-05-12 00:36
Thanks @priya-zha , I'm going to close for now as it _appears_ to be working as expected.

**Closed by mallenexpensify** 2023-05-12 00:36 UTC
Labels: Daily, Needs Reproduction, Bug
