### ISSUE TITLE
[$500] Emoji Picker - Emoji recents has been wiped, no new recents stored

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#34592] opened 2024-01-16 17:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.24-7
**Reproducible in staging?:** Unknown
**Reproducible in production?:** Unknown 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705221634718409

## Action Performed:
1. Open App
2. Go to any chat
3. Access comment action menu
4. Choose emoji option

## Expected Result:
All of a user’s most frequent emojis appear

## Actual Result:
Every recently-used emoji has been wiped, and only the laughing emoji appears

## Workaround:
N/A 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image](https://github.com/Expensify/App/assets/44479856/d3e352d9-d410-4364-9e63-0790b845e109)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f55fadddcc0d33f2</li>
        <li>Upwork Job ID: 1747311920114589696</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by isagoico** [comment] 2024-01-16 17:37
I'm checking with the tester team if anyone is experiencing the same issue on any of their test accounts.

**Comment by nabhiraj** [comment] 2024-01-16 18:30
i am not able to reproduce this 
![image](https://github.com/Expensify/App/assets/20871387/b533aac7-4ae1-4888-82f6-caa9d0aa6565)

also can someone send me a invite to the slack open source channel, its almost a month i am have not got the reply :(, i am very interested in regularly contributing to the project so please send me a invite, my slack email id nabhinewton04@gmail.com

**Comment by isagoico** [comment] 2024-01-16 19:50
So far no one has experienced a similar issue in the tester team. The only known account affected by this is @JmillsExpensify's atm.

**Comment by trjExpensify** [comment] 2024-01-17 16:11
Asking @stitesExpensify who was close to this implementation to see if he might have an indication as to what conditions could cause us to wipe the emoji favourites: https://expensify.slack.com/archives/C049HHMV9SM/p1705507817127169?thread_ts=1705221634.718409&cid=C049HHMV9SM

**Comment by trjExpensify** [comment] 2024-01-23 17:46
Still trying to figure this out in the slack thread, as only Mills is experiencing it.

**Comment by stitesExpensify** [comment] 2024-01-23 17:49
I also wanted to mention here that not only where his emojis wiped, but all new emojis used are also not being added to his frequently used...

**Comment by mvtglobally** [comment] 2024-01-30 04:48
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment] 2024-01-30 11:32
Confirmed that Jason's favourite emojis were wiped, so that's still something we need to try and figure out. @stitesExpensify perhaps we can add some logging or something, so we have a better handle on investigating it if it ever happens again?

**Comment by trjExpensify** [comment] 2024-02-01 22:59
Bump on that question, @stitesExpensify.

**Comment by trjExpensify** [comment] 2024-02-05 13:14
Asked in [thread](https://expensify.slack.com/archives/C049HHMV9SM/p1707138787682529?thread_ts=1705221634.718409&cid=C049HHMV9SM) about adding logging or something!

**Comment by stitesExpensify** [comment] 2024-02-05 22:55
Responded in slack. I don't think that this is worth addressing right now given that we only have a single case, is not associated with any wave, and requires backend work

**Comment by trjExpensify** [comment] 2024-02-06 11:03
Cool, I'm going to close it for now then.

**Closed by trjExpensify** 2024-02-06 11:03 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
