### ISSUE TITLE
Sign in - User is not navigated to home page when authenticating with magic link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37752] opened 2024-03-05 14:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Navigate to sign in page
2. Enter email > click on 'Continue' button
3. Copy magic link > open new tab > prefix the link with 'staging' > paste to address bar > press enter
4. Switch to the tab where you are originally signing in

## Expected Result:
User should be navigated to home page

## Actual Result:
User remains at sign in page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cfbc793c-594b-4579-903e-9dbbd1a14387

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-03-05 14:27
We think that this bug might be related to #wave9-collect-signup
@MitchExpensify

**Comment by arosiclair** [comment] 2024-03-05 19:39
Reproduced in staging **v1.4.47-3**:

https://github.com/Expensify/App/assets/6833644/f1953fa0-a038-4b06-96ac-55e3d339637d

Not reproducible in prod **v1.4.46-2**

**Comment by arosiclair** [comment] 2024-03-05 20:33
I am trying to reproduce this in dev

**Comment by tgolen** [comment] 2024-03-05 22:19
Looks like this was caused by https://github.com/Expensify/react-native-onyx/pull/475 so we are going to revert that change.

**Comment by mvtglobally** [comment] 2024-03-06 03:11
Issue is only partially fixed. User has to refresh the page to login. Loading screen displayed after navigating back 

https://github.com/Expensify/App/assets/43995119/1f138646-ef00-471b-8606-1517ee4d9934

**Comment by paultsimura** [comment] 2024-03-06 06:44
> Issue is only partially fixed. User has to refresh the page to login. Loading screen displayed after navigating back 


This is reproducible in Production as well, so shouldn't be a blocker. @mvtglobally could you please double-check and confirm?🙏🏼

**Comment by arosiclair** [comment] 2024-03-06 13:59
Yes I also reproduced the loading screen in prod **v1.4.46-2**:

<img width="1337" alt="Screenshot 2024-03-06 at 8 58 34 AM" src="https://github.com/Expensify/App/assets/6833644/a6c66e59-9457-4263-a772-15607da75a14">

Do we already have a bug for that?

**Comment by arosiclair** [comment] 2024-03-06 14:07
> Do we already have a bug for that?

Found it: https://github.com/Expensify/App/issues/37351

So the Onyx part of this problem was a real blocker that should be fixed now. The rest should get fixed in that issue. Closing this out!

**Closed by arosiclair** 2024-03-06 14:07 UTC
Labels: DeployBlockerCash, Engineering, Hourly
