### ISSUE TITLE
[$1000] User2 sees an empty task header when not in the room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20427] opened 2023-06-08 00:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new room in the "New room" section
2. Navigate to the "Assign Task" section of the room
3. Enter the task title and proceed by clicking the "Next" button
4. Select user2 as the assignee by clicking on "Assignee"
5. Confirm the task by clicking "Confirm task"
6. Open user2's account and open the assigned task
## Expected Result: 
The task header should display the room name
## Actual Result: 
User2 sees an empty task header when not in the room
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/beb8b467-3a38-4cef-a997-5a8c24c8a337

https://github.com/Expensify/App/assets/43996225/00ac7013-1dd8-43f5-9f3b-0f0fa79d143b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685908232398379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7b1e9657582f1f6</li>
        <li>Upwork Job ID: 1667178700513918976</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2023-06-08 09:30
This issue also happens in a group chat. I guess it happens on every chat which the user is not in that chat (group, room, thread, etc.).

**Comment by zanyrenney** [comment] 2023-06-09 14:36
tested and agree - external to work on fixing this!

**Comment by neil-marcellini** [comment] 2023-06-09 20:31
@dukenv0307 [thinks](https://github.com/Expensify/App/issues/19773#issuecomment-1583895784) we might be able to fix the issue while fixing #19773.

**Comment by zanyrenney** [comment] 2023-06-12 10:27
Ah, cool @neil-marcellini - can you clarify what action you're suggesting here then please? How can we determine 100% if it can be fixed with the other issue?

**Comment by youssef-lr** [comment] 2023-06-14 20:23
Not overdue.

**Comment by neil-marcellini** [comment] 2023-06-16 16:43
Let's retest now that https://github.com/Expensify/App/pull/20562 is on staging and should fix this.

**Comment by zanyrenney** [comment] 2023-06-19 11:12
hey @neil-marcellini - who are you directing your comment at here? Please can you clarify!

**Comment by neil-marcellini** [comment] 2023-06-19 16:21
I was speaking to anyone who is assigned to this issue. I wanted to let you all decide. I supposed it is a good idea to name someone specifically to prevent a tragedy of the commons. Re-testing is kind of like checking for reproducibility, which is a bug zero task, so @zanyrenney would you please see if you can reproduce the bug on staging?

**Comment by zanyrenney** [comment] 2023-06-22 11:39
Sure thing! Let me test this now 🎉 @neil-marcellini

**Comment by zanyrenney** [comment] 2023-06-22 11:50
Okay awesome yep! I can't reproduce this on staging!

**Comment by zanyrenney** [comment] 2023-06-22 11:56
Let me chat to @youssef-lr and confirm!

**Comment by zanyrenney** [comment] 2023-06-22 13:14
Hey, I am heading OOO shortly, so assigning another bug0 team member to help watch over this issue whilst I am OOO. Thank you! I DM'd Youssef about this so probably just chat to him to confirm his thoughts on the payouts, please!

**Comment by joekaufmanexpensify** [comment] 2023-06-22 13:28
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2023-06-22 13:39
Chatted about this internally, and our general policy is that we compensate per PR, rather than per the number of bugs a PR fixes. Given this bug was already going to be fixed by another issue's PR, it's somewhat like a duplicate of that one. So no action is needed here. 

Closing!

**Closed by joekaufmanexpensify** 2023-06-22 13:39 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by youssef-lr** [comment] 2023-06-22 13:47
I'm agreeing with Greg [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1685721163636409?thread_ts=1685711548.218919&cid=C01GTK53T8Q) and I think this applies to our case?

> I mean I think if your PR solves multiple issues, and Expensify/C+ both agree that each individual bug report is due to a different root cause, then you should receive the bounty for each issue.
> But, if your PR solves multiple issues, but each bug report is due to the same root cause, then you should only receive one bounty.
> So maybe in other words: If your PR resolves multiple bug report issues, you should receive a bounty for each issue resolved with a different root cause.

Please correct me if I'm wrong, but I think both issues have the same root cause?
