### ISSUE TITLE
[HOLD for payment 2024-07-30] [$250] Distance - Route in distance editor doesn't load after fresh sign in

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44156] opened 2024-06-21 13:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9-0-0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4620930
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a distance expense.
4. Go to transaction thread.
5. Click Distance.
6. Note that the green route is shown.
7. Sign out and back in
8. Go to the transaction thread in Step 3.
9. Click Distance.

## Expected Result:
The route will load

## Actual Result:
The route does not load

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/26260477/339b183d-d86e-4f03-8b62-2af4067d61de

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a809b3d1bd11c266</li>
        <li>Upwork Job ID: 1807822900424921117</li>
        <li>Last Price Increase: 2024-07-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by izarutskaya** [comment] 2024-06-21 13:04
We think this issue might be related to the #collect project.

**Comment by johncschuster** [comment] 2024-06-24 20:39
@neil-marcellini I'm curious about your thoughts here. Would you expect the green route to persist after the user clears their cache?

**Comment by johncschuster** [comment] 2024-06-27 21:09
@neil-marcellini Assigning to you just to make sure my question is on your radar. Please feel free to drop off after!

**Comment by neil-marcellini** [comment] 2024-07-01 17:05
We shouldn't really report bugs which include a debug only feature like clearing the cache. I was tempted to close the issue, but first I checked if a similar problem was reproducible after signing out. It looks like that does in fact present a real issue, so I'm going to update the description. I'm happy to stay on to manage this externally.

https://github.com/Expensify/App/assets/26260477/339b183d-d86e-4f03-8b62-2af4067d61de

**Comment by izarutskaya** [comment] 2024-07-04 09:27
The team discovered the route also does not generate after changing waypoints in offline mode. 

https://github.com/Expensify/App/assets/115492554/8ceb7e34-aba5-4bf1-b308-025220fc3005

**Comment by bernhardoj** [comment] 2024-07-04 11:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The distance green line route disappears after re-login.

### What is the root cause of that problem?
The green line route is coming from the transaction route coordinate data.
https://github.com/Expensify/App/blob/a84f68eeb1f72d0ca3308a4bdc9dc78e59a46d2e/src/components/DistanceRequest/DistanceRequestFooter.tsx#L112

The coordinate data is retrieved from GetRoute/Draft API. However, the data (routes) isn't saved on the BE and lost when we re-login as pointed out in [here](https://github.com/Expensify/App/issues/43569#issuecomment-2207055931).

The GetRoute/Draft API is only called when the waypoints are changed.
https://github.com/Expensify/App/blob/a84f68eeb1f72d0ca3308a4bdc9dc78e59a46d2e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L93

But because we don't change it, the coordinate data stays empty and the route green line is gone.

### What changes do you think we should make in order to solve the problem?

Trigger the GetRoute/Draft API if the routes data is missing.
```
const shouldFetchRoute = (!transaction?.routes || isRouteAbsentWithoutErrors || haveValidatedWaypointsChanged) && !isLoadingRoute && Object.keys(validatedWaypoints).length > 1;
```

**Comment by neil-marcellini** [comment] 2024-07-09 01:23
> @bernhardoj's [proposal](https://github.com/Expensify/App/issues/44156#issuecomment-2208774179) looks good to me!
> 
> 🎀 👀 🎀 C+ reviewed

I agree, hiring!

**Comment by bernhardoj** [comment] 2024-07-10 08:11
PR is ready

cc: @thesahindia

**Comment by bernhardoj** [comment] 2024-07-17 09:29
@thesahindia @neil-marcellini I found an issue with our PR, so I create a follow up [here](https://github.com/Expensify/App/pull/45579)

**Comment by johncschuster** [comment] 2024-07-17 14:37
Thanks for the new PR! I'll issue payment once that PR passes the regression threshold.

**Comment by johncschuster** [comment] 2024-07-22 15:03
Looks like we're a deploy to prod

**Comment by johncschuster** [comment] 2024-07-25 14:49
Downgrading the label while we wait for the payment date. We're still on track to pay this out on the 30th

**Comment by johncschuster** [comment] 2024-07-30 14:37
## Payment Summary:
Contributor: @bernhardoj paid $250 via Upwork
Contributor+: @thesahindia owed $250 via NewDot

**Comment by johncschuster** [comment] 2024-07-30 14:38
@thesahindia can you complete the BZ Checklist above? Thank you!

**Comment by bernhardoj** [comment] 2024-07-30 14:46
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-07-30 17:01
$250 approved for @bernhardoj

**Comment by johncschuster** [comment] 2024-08-01 14:09
@thesahindia bump on the BZ Checklist

**Comment by johncschuster** [comment] 2024-08-05 14:26
Sweet. Thank you for clarifying that! We're all done here!

**Closed by johncschuster** 2024-08-05 14:26 UTC
Labels: Reviewing, External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-20 17:29
$250 approved for @thesahindia
