### ISSUE TITLE
[QBO] App crashes when toggling on "Sync reimbursed reports"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41894] opened 2024-05-09 11:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** [applausetester+kh250402@applause.expensifail.com](mailto:applausetester+kh250402@applause.expensifail.com)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856 
[logs Web.docx](https://github.com/Expensify/App/files/15261868/logs.Web.docx)
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Account is connected to QBO,
1. Launch New Expensify app.
2. Log in to [applausetester+kh250402@applause.expensifail.com](mailto:applausetester+kh250402@applause.expensifail.com)
3. Go to Account settings > Workspaces > any workspace.
4. Go to Accounting.
5. Click Advanced.
6. Toggle on "Sync reimbursed reports".

## Expected Result:
"Sync reimbursed reports" can be toggled on.

## Actual Result:
App crashes.
On web, it shows console error.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/359171d4-9452-4971-912c-0e240dc33cfe

https://github.com/Expensify/App/assets/93399543/c57a32ea-0b11-4061-acd4-452ee8724354

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-05-09 12:02
@anmurali FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by trjExpensify** [comment] 2024-05-14 22:36
👋 @kbecciv can you share with us which Applause QBO account you used to connect here? 

I tried the one under "Applause QBO" with applausetester+qbo@applause.expensifail.com in 1Password, and I can't reproduce it:

https://github.com/Expensify/App/assets/16232057/f75e784c-764d-46a4-a15b-d30d1e394255

**Comment by anmurali** [comment] 2024-05-15 01:09
This is still being worked on, so not overdue.

**Comment by trjExpensify** [comment] 2024-05-15 17:34
^^ confirming if this is Android only or something [in thread](https://expensify.slack.com/archives/C9YU7BX5M/p1715726253576039).

**Comment by trjExpensify** [comment] 2024-05-15 18:51
Alrighty, turns out they [weren't trying with a new connection](https://expensify.slack.com/archives/C9YU7BX5M/p1715798515489709?thread_ts=1715726253.576039&cid=C9YU7BX5M) and that explains why I wasn't able to reproduce it repeatedly using the same QBO account. Closing!

**Closed by trjExpensify** 2024-05-15 18:51 UTC
Labels: Daily, Bug
