### ISSUE TITLE
[HOLD #18647] [$500] Room - Message about exceeding length of welcome message is displayed only after opening it again

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33436] opened 2023-12-21 18:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any Expensifail account
3. Open any room
4. Click on the room's header -> Settings -> Welcome message
5. Enter any long text -> Save
6. Open Welcome message again

## Expected Result:
A message about exceeding the length of the welcome message is displayed when you try to save it

## Actual Result:
Message about exceeding the length of the welcome message is displayed only after opening it again.
+ incorrect error message displayed, I was expecting a message that the welcome message is too long, but it shows a message that the room name is too long

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/3ac9f561-62bd-4641-873e-d6075af0921e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b9540602d7d80bc9</li>
        <li>Upwork Job ID: 1737896870541582336</li>
        <li>Last Price Increase: 2023-12-21</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-21 18:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
The BE's limit for the welcome message's length is lower than the one set on the form.

### What changes do you think we should make in order to solve the problem?
We do have the maxLength set for the welcome message field. We can just adjust this value to the one that's accepted by BE so we'll avoid failing with the error:

https://github.com/Expensify/App/blob/fd71747303cd8df7fc1dfc9b010752e5635b2684/src/pages/ReportWelcomeMessagePage.js#L106

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-12-21 18:14
It needs to be handled in https://github.com/Expensify/App/issues/18647

**Comment by FlorianWueest** [comment] 2023-12-21 20:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue: 
When we save a long text to welcome message, we will see the error message only after reopening the page. Also, the wrong error gets displayed (room name, not welcome message). 

### What is the root cause of that problem?
In fact, no error should be displayed in the first place. The welcome message gets treated as a comment, with '    MAX_COMMENT_LENGTH: 10000', whereas the room name has a max name of 'MAX_ROOM_NAME_LENGTH: 79'. The tester above typed in a message of a character length of 85, which is above max_room_name_length but vastly below max_comment_length.

### What changes do you think we should make in order to solve the problem?
Install front-end checks (currently backend seems to define error messages, which are not fine-tuned for maxLength property https://github.com/Expensify/App/issues/18647). Install the front-end checks in the function: 'updateWelcomeMessage', by adding an additional prop 'maxLength' - and checking if 'newValue' before parsing is smaller than MAX_ROOM_NAME_LENGTH.

**Comment by FlorianWueest** [comment] 2023-12-21 20:37
Contributor details
Your Expensify account email: florian.wueest@gmx.ch
Upwork Profile Link: https://www.upwork.com/freelancers/~012a0720a0e6c74f6a

**Comment by youssef-lr** [comment] 2023-12-25 06:25
Should be fixed here https://github.com/Expensify/App/issues/18647.

**Closed** 2023-12-28 13:49 UTC
Labels: External, Weekly, Help Wanted, Bug
