### ISSUE TITLE
Profile - Status - User status clears itself after about 5-15 sec

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37474] opened 2024-02-29 07:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Open App or go to staging.new.expensify.com
2. Login with any account
3. Go to Settings > Profile > Status
4. Select Emoji and add message.
5. Leave "Clear after" field at its default of Today
6. Tap "Save"
7. Wait about 5-15 sec

## Expected Result:
User status has not changed

## Actual Result:
User status clears itself after about 5-15 sec
=====
Perhaps this issue depends on the time zone or location.
Tester locations - USA, Chicago area. Time zone - CDT.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9610c51d-c698-4db5-89a6-94c7ec7729fa

https://github.com/Expensify/App/assets/115492554/ff13cf06-f5b9-47e1-b383-082a62a9928f

https://github.com/Expensify/App/assets/115492554/b105729c-a6e0-4bab-93bf-7bb98f3014a1

https://github.com/Expensify/App/assets/115492554/e07da1a6-91be-40a2-8e6e-1eab5415d3ac

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment] 2024-03-06 10:39
Apologies, I've been OOO sick, but am reviewing today!

**Comment by dylanexpensify** [comment] 2024-03-11 10:06
Closing - cannot reproduce and seems low

**Closed by dylanexpensify** 2024-03-11 10:06 UTC
Labels: Daily, Overdue, Bug
