### ISSUE TITLE
[HOLD for payment 2023-10-25] [HOLD for payment 2023-10-24] [$500]  LHN-App crashes on long pressing any report in the LHN

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29746] opened 2023-10-17 10:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Launch app
2. Long press any report in the LHN

## Expected Result:
App must not crash on long pressing any report in the LHN. It must show options to pin and mark as unread.

## Actual Result:
App crashes on long pressing any report in the LHN instead of showing options to pin and mark as unread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/1312bd94-d73e-4527-9861-24a2d2bd1ad4

[logg.txt](https://github.com/Expensify/App/files/12927397/logg.txt)

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb485ef172e2dd5f</li>
        <li>Upwork Job ID: 1714222478975524864</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-17 10:12
Not replroducible in production

https://github.com/Expensify/App/assets/115492554/83e05b08-fe68-4678-ba77-13a25ab587ae

**Comment by pradeepmdk** [comment] 2023-10-17 10:14
this PR cause regression https://github.com/Expensify/App/pull/28846

**Comment by pradeepmdk** [comment] 2023-10-17 10:19
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
LHN-App crashes on long pressing any report in the LHN

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/main/src/libs/DomUtils/index.native.ts
https://github.com/Expensify/App/blob/91e2120e647aa9ee22171b6dbb772b4aebe64992/src/components/LHNOptionsList/OptionRowLHN.js#L189

here DomUtils.getActiveElement() will be null in the native devices 


### What changes do you think we should make in order to solve the problem?
```javascript
DomUtils.getActiveElement() && DomUtils.getActiveElement().blur()
``` 
or we can add if condiiton 
```javascript
if(DomUtils.getActiveElement()) {
DomUtils.getActiveElement().blur()
```

**Comment by jjcoffee** [comment] 2023-10-17 10:52
The author of the [PR](https://github.com/Expensify/App/pull/28846) that caused this regression will be fixing this.

**Comment by astrohunter62** [comment] 2023-10-17 11:44
@narefyev91
Can you review this [PR](https://github.com/Expensify/App/pull/29752)?

**Comment by narefyev91** [comment] 2023-10-17 11:48
> @narefyev91 Can you review this [PR](https://github.com/Expensify/App/pull/29752)?

On it

**Comment by narefyev91** [comment] 2023-10-17 12:23
## Reviewer Checklist
- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>


https://github.com/Expensify/App/assets/28352309/ccce8010-c1e2-444d-ac7e-5e3396f53e5d


https://github.com/Expensify/App/assets/28352309/efa36df7-d4b2-42a4-85d4-fc5987f2732c




</details>

<details>
<summary>Mobile Web - Chrome</summary>


https://github.com/Expensify/App/assets/28352309/e4d0911d-b7be-49ed-a83e-f58cefad84ed




</details>

<details>
<summary>Mobile Web - Safari</summary>


https://github.com/Expensify/App/assets/28352309/747423cb-237e-4724-bfe6-607b9adcec7f




</details>

<details>
<summary>Desktop</summary>


https://github.com/Expensify/App/assets/28352309/9d58eac4-03bf-4214-9414-92b12787acca




</details>

<details>
<summary>iOS</summary>


https://github.com/Expensify/App/assets/28352309/10487bdc-6b14-4891-aa68-7339bc393caf




</details>

<details>
<summary>Android</summary>




</details>

**Comment by dylanexpensify** [comment] 2023-10-30 09:30
@narefyev91 to complete checklist then we can close!

**Comment by narefyev91** [comment] 2023-10-30 09:46
- The PR that introduced the bug has been identified. Link to the PR - https://github.com/Expensify/App/pull/28846
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment https://github.com/Expensify/App/issues/29746#issuecomment-1766106884
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A - it was quickly fixed in staging
- Determine if we should create a regression test for this bug - N/A

**Closed** 2023-11-06 10:14 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Awaiting Payment, Bug
