### ISSUE TITLE
[HOLD #350244] [$500] [HIGH] Backwards Compaitibility: "Hmm..." page is still appearing when clicking on the expense that has already been deleted in Olddot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34738] opened 2024-01-18 15:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705507296776909

## Action Performed:
1. Log in NewDot as employee
2. Open Workspace and create the expense report
3. Login in Olddot as employee and delete the expense report
4. Go back to NewDot as employee and click on expense report

## Expected Result:
The expense should not be present in NewDot

## Actual Result:
Hmm... the page is still appearing when clicking on the expense that has already been deleted in Olddot

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2024-01-17 at 3 59 35 PM](https://github.com/Expensify/App/assets/93399543/f9fb608b-ff33-45c2-9f00-b49ff3531abf)

https://github.com/Expensify/App/assets/93399543/b3c0e564-d57f-4eb9-a5c4-f8be9210fcf2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a180f5aca41b5c9</li>
        <li>Upwork Job ID: 1748008521163730944</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2024-01-22 15:08
This will be resolved with backwards compatibility soon hopefully

**Comment by greg-schroeder** [comment] 2024-01-24 13:21
I think we should hold this on https://github.com/Expensify/Expensify/issues/350244 no?

**Comment by mountiny** [comment] 2024-01-24 20:58
Sounds good!

**Comment by puneetlath** [comment] 2024-02-06 20:42
I think we can go ahead and close this as a dupe of https://github.com/Expensify/Expensify/issues/350244. Reopen if you disagree!

**Closed by puneetlath** 2024-02-06 20:42 UTC
Labels: Monthly, Internal, Bug
