### ISSUE TITLE
[$500] Chat - Display name takes full width in mention suggestions

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30120] opened 2023-10-21 14:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697848345101969

## Action Performed:
1. Change your display name to some long text
2. Go to any report
3. Open mention suggestions by typing "@" and start of your email in composer
4. Observe the display name takes full width

## Expected Result:
 Display name & email both should be visible.

## Actual Result:
Only display name is visible.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/72b1d10a-a1ce-4486-a497-ad3ecf6608a8

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/f0e68bac-6f66-4731-90b1-cb31be3cfba0

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/f18fdd82-0d4c-4389-95b4-8c7d2b0267e3

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/5facf0d2-9320-4b03-80f2-8496afeb1f86

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110519c5e515237f8</li>
        <li>Upwork Job ID: 1715744363137363968</li>
        <li>Last Price Increase: 2023-10-28</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-10-21 14:59
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
Display name takes full width in mention suggestions

### What is the root cause of that problem?
We don't have any width limitation for display name `Text` container and we are also apply `styles.flexShrink1`.

https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/components/MentionSuggestions.js#L84-L85

### What changes do you think we should make in order to solve the problem?

### Option 1
We can set `maxWidth` style for display name `Text` container.

### Option 2
Or we can apply `styles.flexShrink1` or `styles.flexShrink0` to `Text` container of email address.

### Result

**Comment by s-alves10** [comment] 2023-10-23 00:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?

https://github.com/Expensify/App/blob/f4b3bef54c14740cbdb1bd380e53dd6c2c7a71b1/src/components/MentionSuggestions.js#L85
https://github.com/Expensify/App/blob/f4b3bef54c14740cbdb1bd380e53dd6c2c7a71b1/src/components/MentionSuggestions.js#L98
As you can see, `displayName` and `email` has different style.
For `displayName`, `flexShrink: 1` means `flexBasis` is `auto`, which means that the size of the element will be based on its content. And for email, `flex: 1` means `flexBasis` is `0%`. So the base size of these two elements are different(one is full content size, one is 0) and this affects the final sizes of two elements adjusted by `flexShrink` and `flexGrow`

This is the root cause

### What changes do you think we should make in order to solve the problem?

We can set `flexBasis: 'auto'` for email so that the base size of the email text would be based on its content size
Update
https://github.com/Expensify/App/blob/f4b3bef54c14740cbdb1bd380e53dd6c2c7a71b1/src/components/MentionSuggestions.js#L98
to
```
        style={[styles.mentionSuggestionsText, styles.flex1, styles.flexBasisAuto]}
```

Update
https://github.com/Expensify/App/blob/f4b3bef54c14740cbdb1bd380e53dd6c2c7a71b1/src/components/MentionSuggestions.js#L85
to
```
        style={[styles.mentionSuggestionsText, styles.flex1, styles.flexBasisAuto]}
```

This solution makes the base sizes of email and displayName based on its content size and adjusts the final size flexibly

<details>
    <summary>Result</summary>

![image](https://github.com/Expensify/App/assets/126839717/882bd2f1-6cae-4a07-8214-add092befeec)

</details>

### What alternative solutions did you explore? (Optional)
We can apply `styles.flex1` to the `displayName` so that both `displayName` and `email`'s base size is `0%`. This solution works fine as well, but it has a drawback in the case displayName is long and email is much short as you can see below
![image](https://github.com/Expensify/App/assets/126839717/462317bf-c4ae-4224-acfb-281c2f5fe1d4)

**Comment by situchan** [comment] 2023-10-24 12:38
@Expensify/design can you please confirm the expected behavior here?

**Comment by shawnborton** [comment] 2023-10-24 13:15
Hmm I don't know that this is even a bug. @puneetlath do you have strong feelings here?

**Comment by puneetlath** [comment] 2023-10-25 15:35
I guess we could truncate it. I don't have strong feelings. 

All the long names in the examples seem to be fake. Are we aware of any real names that would cause this problem?

**Comment by greg-schroeder** [comment] 2023-10-27 16:51
Hmm. Maybe this could be closed... I don't feel super strongly about this one either.

**Comment by situchan** [comment] 2023-10-31 13:52
Let's close this then

**Closed** 2023-10-31 16:27 UTC
Labels: External, Daily, Help Wanted, Bug
