### ISSUE TITLE
[HOLD for payment 2024-04-30][$500] Tag - Tag in Parent: Child format is displayed as Parent/: Child in Tag list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37847] opened 2024-03-06 23:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an admin of Collect workspace with tags.
- The tags include tag in Parent: Child format.
1. Go to staging.new.expensify.com
2. Go to Workspace settings > Collect workspace.
3. Go to Tags.

## Expected Result:
Tag in Parent: Child format is displayed correctly.

## Actual Result:
Tag in Parent: Child format is displayed as Parent/: Child.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/10de8b48-9892-4020-b95f-34512a30b757)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c364cca7b2db41ce</li>
        <li>Upwork Job ID: 1767986259945525248</li>
        <li>Last Price Increase: 2024-03-13</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-06 23:07
We think that this bug might be related to #wave8-collect-admins
@zanyrenney

**Comment by marcaaron** [comment] 2024-03-06 23:52
cc @luacmartins @waterim might be able to triage this faster than me. Will take a look soon if not.

**Comment by luacmartins** [comment] 2024-03-06 23:56
we're discussing this internally since multi-level tags were out of scope for the doc

**Comment by luacmartins** [comment] 2024-03-07 01:39
We've discussed this internally and the solution we're going with is to just hide any tags that are on level 2 or above, so we only want to display the root level for now.

**Comment by Tony-MK** [comment] 2024-03-07 02:01
@luacmartins, I updated my proposal.

**Comment by luacmartins** [comment] 2024-03-07 02:30
We're still discussing some nuances for this case. I'll circle back once we made a decision on the expected behavior

**Comment by luacmartins** [comment] 2024-03-07 03:09
@kbecciv how did you set up that `Parent: Child` tag?

**Comment by roryabraham** [comment] 2024-03-07 18:50
@luacmartins is this a blocker? Tags are a collect policy feature and thus in order to use them in NewDot you have to run a JS snippet in OldDot. Right?

**Comment by luacmartins** [comment] 2024-03-07 19:42
Yea, let's demote this.

**Comment by Tony-MK** [comment] 2024-03-07 23:15
Hi @luacmartins, I imported a sample CSV file seen below into OD.

![Screenshot 2024-03-08 at 02 13 43](https://github.com/Expensify/App/assets/22982173/27a32625-dbfd-482e-8a19-47bd2c3927b9)

**Comment by luacmartins** [comment] 2024-03-13 05:49
This is a polish item, will make external

**Comment by adelekennedy** [comment] 2024-03-13 18:49
adding external label for proposals and C+

**Comment by Tony-MK** [comment] 2024-03-14 00:14
# Updated Proposal

Link: https://github.com/Expensify/App/issues/37847#issuecomment-1982018079

**Comment by allroundexperts** [comment] 2024-03-18 13:05
@Tony-MK I think as per https://github.com/Expensify/App/issues/37847#issuecomment-1982183268, we don't want to hide the multi level tag entirely. Rather, we just want to display the root tag. You might want to update your proposal.

**Comment by allroundexperts** [comment] 2024-03-18 13:43
@luacmartins Can you confirm if we want to completely hide the `Parent: Child` format tag or just display `Parent` in the list?

**Comment by luacmartins** [comment] 2024-03-18 19:37
@allroundexperts we'd completely hide `Parent: Child` from the tag list

**Comment by allroundexperts** [comment] 2024-03-18 19:39
Gotcha. Thanks for the confirmation.

In that case, @Tony-MK's [proposal](https://github.com/Expensify/App/issues/37847#issuecomment-1982018079) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by adelekennedy** [comment] 2024-03-20 23:20
@Tony-MK manually invited you to the job on Upwork!

**Comment by allroundexperts** [comment] 2024-03-20 23:26
@luacmartins I think this issue would solve https://github.com/Expensify/App/issues/38683

**Comment by luacmartins** [comment] 2024-03-21 00:45
Makes sense. I'll put that on hold

**Comment by Tony-MK** [comment] 2024-03-22 00:23
@allroundexperts, the [PR](https://github.com/Expensify/App/pull/38759) is ready review.

**Comment by luacmartins** [comment] 2024-03-29 15:12
Reassigning as per https://expensify.slack.com/archives/C02NK2DQWUX/p1711707769397279

**Comment by adelekennedy** [comment] 2024-04-30 22:16
payments made - @luacmartins are we good to close?

**Comment by luacmartins** [comment] 2024-04-30 23:10
Yes, should be good to close.

**Closed by luacmartins** 2024-04-30 23:10 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
