### ISSUE TITLE
Split/Group - Selected user is not visible for split bill/create a group chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9598] opened 2022-06-28 17:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot
2.  Select green + and then Split Bill
3. Input amount and click Next
4. Select users

## Expected Result:
Selected users are displayed at the top

## Actual Result:
Selected users are NOT displayed at the top

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/176240546-511e8fd6-e5f2-446d-b8d1-1288d103dd13.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rushatgabhane** [comment] 2022-06-29 02:07
Probably not a blocker. It's a known limitation of #7702 

We should get it fixed though. cc: @roryabraham

**Comment by sketchydroide** [comment] 2022-06-29 10:31
@roryabraham do you have any input on this
it sounds broken, but wander if  @rushatgabhane comments are correct.

**Comment by sketchydroide** [comment] 2022-06-29 15:32
I think @rushatgabhane was trying to say that #7702 has a similiar known limitation on Android, but I'm not sure this is related, might be...

**Comment by roryabraham** [comment] 2022-06-29 15:32
Yes, I can confirm that this shouldn't be a deploy blocker but a separate ticket. It was a bug we knew about in https://github.com/Expensify/App/pull/7702 that we decided to fix separately because that PR was so big already.

**Comment by roryabraham** [comment] 2022-06-29 15:49
@puneetlath I've got a fix for this

**Comment by roryabraham** [comment] 2022-06-29 15:57
Put up a [PR](https://github.com/Expensify/App/pull/9626) to fix this. I can confirm the issue is platform-agnostic and happened on all platforms, not just Android

**Closed** 2022-07-05 22:34 UTC
Labels: Reviewing, Engineering, Daily
