### ISSUE TITLE
[HOLD for payment 2022-12-15] DEV - building desktop staging locally on a M1 mac crashes App at launch

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12930] opened 2022-11-22 15:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Build desktop staging locally

## Expected Result:
App should not crash

## Actual Result:
App crashed

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @kidroca
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669051761252729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johncschuster** [comment] 2022-11-23 03:28
From Slack, it looks like these are @kidroca's repro steps:

Steps:
On a M1 mac
1. run npm run desktop-build-staging
2. Navigate to desktop-build and launch the built app
3. It immediately crashes

**Comment by johncschuster** [comment] 2022-11-23 03:30
@danieldoglas, I have an M1, but I'm not 100% sure I know what to expect to see if I were to run these steps and get a success or failure. Can you try following @kidroca's steps [here](https://github.com/Expensify/App/issues/12930#issuecomment-1324505061) to see if you can reproduce the reported behavior?

**Comment by kidroca** [comment] 2022-11-23 18:37
I can capture a video 
The slack thread also has a link to a fix

**Comment by danieldoglas** [comment] 2022-11-28 14:29
Looking into this today.

**Comment by danieldoglas** [comment] 2022-11-28 14:52
Interesting, even considering I am a developer and I have apple certificates, it also breaks for me.

**Comment by danieldoglas** [comment] 2022-11-28 15:07
@kidroca just to confirm: did you follow the instructions [here](https://github.com/Expensify/App/tree/main/desktop#setting-up-credentials-for-notarizing-your-build) when doing your build?

**Comment by danieldoglas** [comment] 2022-11-28 15:14
just adding Kidroca`s comment [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667938393491319?thread_ts=1667938306.012479&cid=C01GTK53T8Q). 

```
In any case I found this ticket on Electron's repo and it solved the problem for me
ticket https://github.com/electron/electron/issues/35355
fix: https://github.com/electron/electron/issues/35355#issuecomment-1227574710

**Comment by kidroca** [comment] 2022-11-28 17:55
Yeah, I think this is the related electron issue
- https://github.com/electron/electron/issues/35355

This is what I've found out so far: 

We're using `hardenedRuntime`: 
https://github.com/Expensify/App/blob/a3e8db6fbc11658ff25c6513534ea664de29d1e6/config/electronBuilder.config.js#L36

https://developer.apple.com/documentation/security/hardened_runtime
> The Hardened Runtime doesn’t affect the operation of most apps, but it does disallow certain less common capabilities, like just-in-time (JIT) compilation. If your app relies on a capability that the Hardened Runtime restricts, add an entitlement to disable an individual protection. 

I think the fix I shared earlier https://github.com/electron/electron/issues/35355#issuecomment-1227574710 is valid because:

https://developer.apple.com/documentation/apple-silicon/porting-just-in-time-compilers-to-apple-silicon/
>  For example, a web browser uses JIT compilation to transform a web page’s script code into runnable code when the user interacts with the appropriate page elements.

Desktop is using Electron, and Electron works like a browser so it needs to have the JIT entitlement enabled 

```xml
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
```

---

Actually even if `hardenedRuntime` is `false` we have to enable JIT to support apple silicon

[https://developer.apple.com/documentation/apple-silicon/porting-just-in-time-compilers-to-apple-silicon](https://developer.apple.com/documentation/apple-silicon/porting-just-in-time-compilers-to-apple-silicon/#:~:text=Because%20JIT%20compilation%20uses%20some%20techniques%20that%20the%20Hardened%20Runtime%20capability%20specifically%20disallows%2C%20you%20must%20update%20your%20app%20if%20it%20supports%20that%20capability.%20Even%20if%20your%20app%20doesn%E2%80%99t%20adopt%20the%20Hardened%20Runtime%2C%20you%20must%20still%20make%20changes%20to%20support%20Apple%20silicon.)
> Because JIT compilation uses some techniques that the Hardened Runtime capability specifically disallows, you must update your app if it supports that capability. Even if your app doesn’t adopt the Hardened Runtime, you must still make changes to support Apple silicon.

---

Another point of view is "Why then the Desktop app works when it's downloaded from web?" 
The published app isn't affected by this crash
Maybe because it's built for x86 and not for arm64 architecture, then if you open App on a Apple Silicon mac, it's running through Rosetta 
The CI builds x86 because the target arch is picked up automatically based on the current machine running the build 
while my mac builds arm64.

I guess an alternative fix would be to set the target as x86 explicitly
Though one day if we decide to build for arm64 we'll hit this problem again

**Comment by danieldoglas** [comment] 2022-11-28 17:59
@kidroca thanks for further explaining. I think we can apply that solution, since I was able to simulate it as well.

Do you want to bring up a PR?

**Comment by kidroca** [comment] 2022-11-28 18:01
Yes, though I can submit a PR tomorrow, is that OK?

**Comment by danieldoglas** [comment] 2022-11-28 18:01
Yep, no problem!

**Comment by danieldoglas** [comment] 2022-11-30 18:07
Adding external tag since it's external, but no `help wanted` since Kidroca is going to work on it.

**Comment by kidroca** [comment] 2022-11-30 18:11
PR Ready
- https://github.com/Expensify/App/pull/13199

**Comment by danieldoglas** [comment] 2022-12-05 12:23
Closing this

**Comment by sobitneupane** [comment] 2022-12-16 03:20
@johncschuster I was C+ reviewer in the [PR](https://github.com/Expensify/App/pull/13199) of this issue. I guess payment will be made through this issue.

**Comment by sobitneupane** [comment] 2023-01-04 17:54
@johncschuster @danieldoglas 


> @johncschuster I was C+ reviewer in the [PR](https://github.com/Expensify/App/pull/13199) of this issue. I guess payment will be made through this issue.
> 
> Also, since it was merged within 3 business days, is it eligible for bonus?
> 
> > Merged PR within 3 business days of assignment - 50% bonus

**Comment by danieldoglas** [comment] 2023-01-04 19:15
sorry for the delay @sobitneupane, I'll check that out and answer you!

**Comment by johncschuster** [comment] 2023-01-04 19:57
Hi @sobitneupane! I'm so sorry for the delay on this! Can you apply to the job in Upwork? I'll get payment issued right away!

https://www.upwork.com/jobs/~01808b0e49ef63488b

**Comment by sobitneupane** [comment] 2023-01-05 03:41
@johncschuster Thanks. Submitted proposal.

**Comment by sobitneupane** [comment] 2023-01-05 16:10
@johncschuster Accepted offer.

**Comment by johncschuster** [comment] 2023-01-05 16:25
Paid! 🎉

**Comment by sobitneupane** [comment] 2023-01-05 16:27
Thanks @johncschuster

**Comment by johncschuster** [comment] 2023-01-13 23:18
@danieldoglas Does this issue require regression steps? I'm thinking "no" because it doesn't have to do with new.expensify.com, but I'm willing to be wrong!

**Comment by danieldoglas** [comment] 2023-01-14 02:53
@johncschuster i don't think so. We can close this!

**Comment by danieldoglas** [comment] 2023-01-23 17:31
Closing this since I think we just missed closing it.

**Closed by danieldoglas** 2023-01-23 17:31 UTC
Labels: Engineering, Weekly, Overdue, Awaiting Payment, Bug
