### ISSUE TITLE
Focus mode showing tons of unread reports that I have no idea why are there

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#30781] opened 2023-11-02 14:22 UTC
Some context https://expensify.slack.com/archives/C049HHMV9SM/p1698933470963439?thread_ts=1698924304.893529&cid=C049HHMV9SM

Happening on staging but not prod (only tested web).
I see a ton of unread chats on focus mode that should not be shown at all

![image](https://github.com/Expensify/App/assets/521248/eaf74845-977a-4302-b0fc-355ee9f8ef05)

**Comment by Julesssss** [comment] 2023-11-02 14:38
Agree this is a deploy blocker. 

For me, all of the unread reports are of type chat report. And I'm pretty sure some at least one of them cannot have had an IOU shared between them (Clem). Additionally, @iwiznia is one of my broken chats, but I am not one of his broken chats...

<img width="298" alt="Screenshot 2023-11-02 at 14 35 14" src="https://github.com/Expensify/App/assets/10736861/09698e10-38a1-43e4-bea9-1b6a67e55196">

**Comment by Julesssss** [comment] 2023-11-02 14:45
@Beamanator FYI new blocker

**Comment by arosiclair** [comment] 2023-11-02 14:49
Not seeing this with my expensify or my expensifail accounts. I'm attending an interview atm so can't really investigate. Can one of you take over on this? @iwiznia @Julesssss or anyone?

**Comment by iwiznia** [comment] 2023-11-02 14:53
Not me, sorry. 
BTW you can still work while attending the interview, you don't have to be looking at what they are doing for 1 hour...

**Comment by Julesssss** [comment] 2023-11-02 15:01
Sorry, I'm also busy and only have an hour left in my day.

**Comment by puneetlath** [comment] 2023-11-02 15:20
@Julesssss the green dot issue is likely this issue which I'm working on https://github.com/Expensify/App/issues/30775

**Comment by Julesssss** [comment] 2023-11-02 15:31
Oh nice. Thanks, I didn't see that issue.

**Comment by Beamanator** [comment] 2023-11-02 16:20
I also can't reproduce this on my account, I'll check my expensifail now

**Comment by arosiclair** [comment] 2023-11-02 21:07
Asked for any others that are seeing this issue [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1698957406128389). If we don't have many people experiencing this, let's remove the blocker label. I also do not see any PR's in this deploy that could've caused this.

**Comment by marcaaron** [comment] 2023-11-02 22:13
>unread chats on focus mode that should not be shown at all

Are we just talking about archived ones? And are we sure that someone did not just delete a workspace that @iwiznia is on? 

>Happening on staging but not prod (only tested web).

I am confused about why they would not show on production. Archived unread chats currently will show on production IIRC.

So, it's expected - but we're changing that behavior here - https://github.com/Expensify/App/pull/30795

**Comment by sakluger** [comment] 2023-11-02 23:43
To add to what @marcaaron said, I think this is a duplicate of https://github.com/Expensify/Expensify/issues/325443 (the PR he linked is an initial fix for that issue).

**Comment by Beamanator** [comment] 2023-11-03 06:04
Groovy so I'll remove the blocker label for now, while y'all decide if we should close this or not :D

**Comment by MonilBhavsar** [comment] 2023-11-03 06:28
Ionatan's unread chats are mostly archived chat reports. @iwiznia are you not able to see those on Production? Yes, it is known bug https://github.com/Expensify/Expensify/issues/325443

**Comment by Julesssss** [comment] 2023-11-03 08:25
Is it really just us two that are facing this? One thing me and @iwiznia have in common is that we both worked on the very first IOU reports and probably have a lot of malformed reports in our accounts...

**Comment by Julesssss** [comment] 2023-11-03 09:06
@MonilBhavsar I see the same as @iwiznia but only on staging.

**Comment by iwiznia** [comment] 2023-11-03 15:32
So we removed the deploy blocker because we believe no one except me and Jules will experience this?

Also, if you check my screenshot you can see it is not only archived chats, the 3rd and 4th chat in the list seem like just empty chats (workspace chat?) with people I never spoke to...

**Comment by arosiclair** [comment] 2023-11-03 21:24
To clear things up @Julesssss issue was with GBR's not unread reports and it should be fixed by the other issue. 

@iwiznia's unread reports issue seems to be 99% dupe of https://github.com/Expensify/Expensify/issues/325443. 

For the non-archived workspace chats I'm not sure (though it might be the same root cause as the archived problem). Is there something special about those chats @iwiznia? Do you know of any way to reproduce them?

**Comment by arosiclair** [comment] 2023-11-06 19:12
Bump @iwiznia ^

**Comment by iwiznia** [comment] 2023-11-07 12:05
Nothing special I can tell and no, I have no idea how to reproduce this

**Closed** 2023-11-07 14:49 UTC
Labels: Engineering, Daily
