### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] Chat - Conversations do not load if you interrupt the Internet connection when logging in

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27054] opened 2023-09-08 19:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a New Expensify app
2. Log in with HT account
3. Turn off the internet for 5 seconds when the download starts
4. Turn the internet back on

## Expected Result:
The app should in all situations download the entire conversation history if online

## Actual Result:
If you turn off the internet when logging into your HT account and then turn it back on, the app can't load the conversation history and only loads the last active one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.66-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b33318cc-fb57-4c1f-be78-2e81f2288563

https://github.com/Expensify/App/assets/78819774/812105a6-6040-4ada-a279-8266b41ab3a4

Production

https://github.com/Expensify/App/assets/78819774/dd24a794-92eb-4fb9-b0f2-5eb60d59e34f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159e32a8761c731e6</li>
        <li>Upwork Job ID: 1701890298391609344</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26751852</li>
</ul></li>
    </ul>
</details>

**Comment by deetergp** [comment] 2023-09-11 02:09
I pretty sure I was able to recreate this on production… So I'm not sure it's a DeployBlocker.

**Comment by deetergp** [comment] 2023-09-13 09:27
I'm going to mark this as External and see what our contributors can do with it.

**Comment by nahid633** [comment] 2023-09-13 10:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Conversations do not load if you interrupt the Internet connection when logging in
### What is the root cause of that problem?

in [AuthScreen.js](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/AuthScreens.js) 
line 140 there is          `NetworkConnection.onReconnect(() => {}) ` function listen for reconnect and call the function. inside that function  `App.reconnectApp` is called. What i get from my investigation is that App.reconnectApp() and App.openApp command returns different data therefore we don't see the all convestions history.

### What changes do you think we should make in order to solve the problem?

if we are solving this issue in FE. adding   App.openApp(); next to App.reconnectApp() will get latest results and conversations.
line 142    ` App.openApp();`

### What alternative solutions did you explore? (Optional)

Other solution is to fix ReconnectApp api response to get same results as OpenApp().



https://github.com/Expensify/App/assets/22540272/c355c0f2-e683-43dd-b68f-0da129022954

**Comment by narefyev91** [comment] 2023-09-13 14:48
Proposal from @tienifr looks good to me https://github.com/Expensify/App/issues/27054#issuecomment-1717447113
We should separate usage of App.openApp(); and App.reconnectApp(this.props.lastUpdateIDAppliedToClient); - and not try to make them working as a one call or combine both in one
🎀 👀 🎀 C+ reviewed

**Comment by nahid633** [comment] 2023-09-13 18:36
> Proposal from @tienifr looks good to me [#27054 (comment)](https://github.com/Expensify/App/issues/27054#issuecomment-1717447113)
> We should separate usage of App.openApp(); and App.reconnectApp(this.props.lastUpdateIDAppliedToClient); - and not try to make them working as a one call or combine both in one
> 🎀 👀 🎀 C+ reviewed

Adding IS_LOADING_APP  is good idea but there is one problem with 

isLoadingApp? App.openApp(): App.reconnectApp(this.props.lastUpdateIDAppliedToClient)
        });
        
After successfully login if there is network lost and then it is not gonna able to call APP.write so we will lose data. I would suggest to add.

App.reconnectApp(this.props.lastUpdateIDAppliedToClient)  });

if(!isLoadingApp) {
App.openApp(): 
}

**Comment by deetergp** [comment] 2023-09-19 09:42
Your solution looks good @tienifr, thanks!

**Comment by bfitzexpensify** [comment] 2023-10-02 17:54
Payment complete to @tienifr. 

No payment required to @narefyev91.

Think we're now good to close this out.

**Closed by bfitzexpensify** 2023-10-02 17:54 UTC
Labels: External, Engineering, Daily, Awaiting Payment
