### ISSUE TITLE
Workspace - Custom avatar uploaded offline is inconsistent after deleting workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35177] opened 2024-01-25 19:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32986

## Action Performed:
Precondition: There is no workspace.
1. Go offline.
2. Create a new workspace.
3. Upload a custom avatar for the workspace.
4. Delete the workspace.
5. Go to the archived workspace chat or room like #admin.
6. Click room header.
7. Click on the avatar.
8. Go online.

## Expected Result:
n Step 7, the default avatar should be the same in full screen view.
In Step 8. after going online, the default avatar should remain.

## Actual Result:
n Step 7, the default avatar is different in the full screen view (different background color).
In Step 8. after going online, the avatar reverts to custom avatar that is uploaded offline.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/796c8605-74e8-4fdc-8401-ef8042aa0750

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-01-25 19:21
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by rlinoz** [comment] 2024-01-25 21:02
This is an edge case and not blocking the users, so I am demoting this one.

**Comment by getusha** [comment] 2024-01-26 07:29
Raised this in the PR https://github.com/Expensify/App/pull/32986#issuecomment-1868960994
Decided to go with creating another issue for it @madmax330 @FitseTLT

**Comment by FitseTLT** [comment] 2024-01-26 12:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Custom avatar uploaded offline is inconsistent after deleting workspace

### What is the root cause of that problem?
This a BE issue where if the workspace is all created, update avatar and delete workspace offline and it sets the avatar to the non-default avatar set by the user. I think the reason might be related to the order of the requests of the `Updating of the Avatar` and `Deletion of the workspace`.
### What changes do you think we should make in order to solve the problem?

This should be fixed in BE but there is a simple fix in FE we can follow, which is to check if it is an archived workspace before returning the workspace avatar here
https://github.com/Expensify/App/blob/83a7535cf5b691fc8965607327d651d10a283bd8/src/libs/ReportUtils.ts#L1450-L1453
```
 const policyExpenseChatAvatarSource =
        allPolicies?.[`${ONYXKEYS.COLLECTION.POLICY}${report?.policyID}`]?.avatar && !isArchivedRoom(report)
            ? allPolicies?.[`${ONYXKEYS.COLLECTION.POLICY}${report?.policyID}`]?.avatar
            : getDefaultWorkspaceAvatar(workspaceName);
```
### What alternative solutions did you explore? (Optional)

**Comment by rlinoz** [comment] 2024-01-29 21:03
I will try to find a wave/vip to put this into, but I checked and we are not blocking policy changes if the policy is deleted, so we might want to start doing that.

**Comment by rlinoz** [comment] 2024-02-01 15:59
bumped this in #vip-vsb today.

**Comment by rlinoz** [comment] 2024-02-05 12:54
Hey @miljakljajic do you think we have a wave for this or maybe we should close this?

**Comment by miljakljajic** [comment] 2024-02-07 16:37
I think we can close - feels more like polish to me. Thank you @rlinoz!

**Closed by miljakljajic** 2024-02-07 16:37 UTC
Labels: Engineering, Daily, Overdue, Bug
