### ISSUE TITLE
Web - User's Last name is not showing in the Group chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23753] opened 2023-07-27 18:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
PRECONDITION: There are users with both First Name and Last Name.
1. Login to an account.
2. Create a new group chat.
3. Add any user who has First Name and Last Name to the Group
4. Check the user's name shown in the chat.

## Expected Result:
 User's First Name and Last Name should be showing

## Actual Result:
Only the user's First Name is showing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6701133e-9265-4135-b9cb-9a5a06cb863f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690392466311909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016780f7041d36076c</li>
        <li>Upwork Job ID: 1687118721482678272</li>
        <li>Last Price Increase: 2023-08-03</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-27 19:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User's Last name is not showing in the Group chat.

### What is the root cause of that problem?
We fetch user's icon information in `ReportUtils.getIconsForParticipants`.
We fetch user's first name instead of user's display name.
So the user's last name is not showing in the group chat.
### What changes do you think we should make in order to solve the problem?
We should retrieve the user's display name.
```js
-	lodashGet(personalDetails, [accountID, 'firstName'], ''),
+	lodashGet(personalDetails, [accountID, 'displayName'], ''),
    };
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by daordonez11** [comment] 2023-07-27 19:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Full display name is not shown in the welcome text component
### What is the root cause of that problem?

Probably this seems to be as designed but the root is:
The component `ReportWelcomeText` uses the method `getDisplayNamesWithTooltips` to bring the information of participants. The second parameter is: `isMultiplePärticipant` since in this case it is true the method `getDisplayNameForParticipant` finally returns `shortName` which is the `firstName` of the participant

### What changes do you think we should make in order to solve the problem?

In case we want to fix this instead of changing root and util methods we can update `ReportWelcomeText` and send `false` instead of `isMultipleParticipant` in the `getDisplayNamesWithTooltips` 

### What alternative solutions did you explore? (Optional)

Probably as designed so, do nothing

**Comment by tranvantoan-qn** [comment] 2023-07-28 04:55
I think this is an issue instead of designed/expected since the **issue only happens for the first user in the list**

Added this image to explain more details:
![image](https://github.com/Expensify/App/assets/10254571/2772fa11-6c6b-4319-a6b4-e5228ad57975)

**Comment by daordonez11** [comment] 2023-07-28 05:10
Hmmm I'll test with multiple users tomorrow but in my case it was showing first name for all participants

**Comment by tranvantoan-qn** [comment] 2023-07-28 05:15
Yeah, it seems like we have a bigger issue to solve then because **it is inconsistent with the tooltip** -  the tooltip shows both the user's first name and last name

**Comment by daordonez11** [comment] 2023-07-28 15:53
You are right! @tranvantoan-qn  Now i See your issue 

![image](https://github.com/Expensify/App/assets/13544910/73f6bcfd-4abc-45ee-b386-11dd265bdfb1)

I think it only happens when you haven't interacted with the other account! Server is responding with this details: 
accountID: 14912234
avatar: "https://d1wpcgnaa73g0y.cloudfront.net/cfe228123ccd5db003db023102c24553a305fdb5.png"
displayName: "First Name Last Name"
isLoading: false
status: null

If there is no first name `getDisplayNameForParticipant` falls back to the display name. Will update the alternate proposal to unify experience in case only one name is desired.

cc @mountiny  Another edge case of creating chat with unknown users. As discussed before this account does not send login and the display name is the one defined by the user. If this is "public" info shouldn't the server send first name?

**Comment by mountiny** [comment] 2023-07-31 15:27
Thats another edge case stemming from the Secure logins project. I think we should add it to some tracking and ask in Slack Alex B and Puneet if this is already covered in some clean up issues or not, I dont have much more context on whats planned in this project

**Comment by lschurr** [comment] 2023-08-02 20:52
Brought this up in Slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1691009540828039

**Comment by daordonez11** [comment] 2023-08-03 15:18
So after final discussions in Slack it is found that the ticket will be managed internally. @Beamanator after the definition do you think I could apply for a 25% contribution? I helped find RCA and evaluate the possible solutions in BE and FE. I also can help with testing whenever it is fixed in the backend.

cc @mountiny

**Comment by mountiny** [comment] 2023-08-06 18:34
Makes sense to me, given Daniel helped to drive this issue forwards and identify path to take from here

**Comment by msapple0338** [comment] 2023-08-09 10:28
Hello daordonez11!
Can you help me?

**Comment by lschurr** [comment] 2023-08-22 04:40
Hey @mountiny @puneetlath - is this bug fixed? Are we ready to issue payment to @daordonez11 per this comment: https://github.com/Expensify/App/issues/23753#issuecomment-1664180158?

**Comment by puneetlath** [comment] 2023-08-31 23:15
Yep, it should be fixed.

**Comment by tranvantoan-qn** [comment] 2023-09-20 01:58
@lschurr Sorry for asking,
But I think we should process the payment for me and @daordonez11 as it is fixed for quite long

**Comment by lschurr** [comment] 2023-09-20 07:04
Ah, sorry I missed this. Will process payment today.

**Comment by lschurr** [comment] 2023-09-20 07:11
The original job posting is expired. Could you apply to this one @tranvantoan-qn @daordonez11 - https://www.upwork.com/jobs/~010816944127f823d2

**Comment by tranvantoan-qn** [comment] 2023-09-20 07:17
I'm getting this error when applying for it `Only invited users can find, view and apply to the job`

**Comment by daordonez11** [comment] 2023-09-20 12:20
Same here @lschurr here is my profile URL https://www.upwork.com/freelancers/~01e96b8da58232f028

**Comment by lschurr** [comment] 2023-09-21 01:28
@tranvantoan-qn can you link your upwork profile here as well?

**Comment by tranvantoan-qn** [comment] 2023-09-21 01:33
@lschurr  It is https://www.upwork.com/freelancers/~012f07ead7068a224c

**Comment by lschurr** [comment] 2023-09-21 03:15
Payment summary:
- Bug reporter: @tranvantoan-qn $250
- Contributor: @daordonez11 $250 (25% as agreed here: https://github.com/Expensify/App/issues/23753#issuecomment-1664180158)

**Comment by tranvantoan-qn** [comment] 2023-09-27 05:50
@lschurr I still didn't get the offer, can you check again to see if you got my Proposal for the job on Upwork?

**Comment by lschurr** [comment] 2023-09-27 07:17
@tranvantoan-qn - you should see the offer now!

**Comment by tranvantoan-qn** [comment] 2023-09-27 07:20
Thank you, I've accepted the offer

**Comment by lschurr** [comment] 2023-09-27 07:43
All paid!

**Closed by lschurr** 2023-09-27 07:43 UTC
Labels: Reviewing, Weekly, Internal, Bug
