### ISSUE TITLE
[$500] Sign out - Blank space appears in settings & login pages on tapping sign out option

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33991] opened 2024-01-05 00:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login with gmail account on ND site
2. Tap settings icon
3. Scroll down & tap on Sign out option

## Expected Result:
No visual issues occur below in settings & log in pages on tapping sign out option

## Actual Result:
Blank space appears below in settings & log in pages on tapping sign out option

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6332686_1704415367301!IMG_1373](https://github.com/Expensify/App/assets/78819774/46236855-d7ed-4db0-9a4e-113a76d29371)

https://github.com/Expensify/App/assets/78819774/194a60ed-353d-48ef-90ca-953939a5f759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d01ddadac95e99c</li>
        <li>Upwork Job ID: 1743072802970316800</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2024-01-06 18:38
I am able to reproduce this on a real iPhone, on Safari staging by also having the staging version of the native app installed.

This happens only in mWeb: Safari because of the **New Expensify - Open in the New Expensify app - OPEN** banner which shows up in this case when the Settings page is opened and disappears when Settings page is closed which also happens when logging out.

Because of the banner being removed from the layout, we see that space briefly until the layout is re-calculated. That block we see is theme dependent, being the `appBG` which is  `productDark100: #061B09` for when dark theme is on and `productLight100: #FCFBF9` on light theme.

This would be the root cause of the issue, the problem in coming up with a solution is that the banner showing up cannot be reproduced on local development (as far as I know) in order to debug / find a fix - hence the issue is almost impossible to tackle.

**Comment by isabelastisser** [comment] 2024-01-08 17:58
@jjcoffee can you please follow up on the comment above? Thanks!

**Comment by jjcoffee** [comment] 2024-01-09 15:37
Hmm I'd say it's a fairly minor bug and I'm not sure it's worth prioritising it if it's overly complex to find a fix!

**Comment by isabelastisser** [comment] 2024-01-09 18:03
Thanks! Closing based on the discussion above.

**Closed by isabelastisser** 2024-01-09 18:03 UTC
Labels: External, Daily, Help Wanted, Bug
