### ISSUE TITLE
Room-Creating public room with invited workspace & renaming it displays error message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37883] opened 2024-03-07 11:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4396592
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch App(android app)
2. Tap settings---workspaces-----workspace
3. Tap members ----- invite
4. Invite user B
5. Go to https://staging.new.expensify.com/
(mweb)
6. Login as user B
7. Tap fab --- start chat --- room
8. Enter a room name
9. Select invited workspace
10. Select visibility "public"
11. Tap create room
12. Tap header--- settings
13. Tap room name
14. Rename the room name and save it

## Expected Result:
Creating public room with invited workspace & renaming room name must not show any error message and user must be able to rename room without any error.

## Actual Result:
Creating public room with invited workspace & renaming room name displays error message "you don't have permission to update this room" with red dot.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/08c663a0-c12e-4f3b-a3ca-f8dd3ca493c4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-07 11:16
@zanyrenney I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by zanyrenney** [comment] 2024-03-11 14:04
Thank you @izarutskaya - let me take a proper look for you now!

**Comment by zanyrenney** [comment] 2024-03-11 14:25
The description of the reproduction steps I'm not sure that this is a real journey that user would take. Could you possibly make this more concise and explain in a bit more detail what the real life scenario would be to lead a user to be doing these two different actions via these two different user journeys at the same time?

There's a chance I'm missing something, but when I'm trying to reproduce this, I'm getting stuck on the longevity of steps and struggling to understand if this is an extreme outlier or a viable flow that a user would be taking.

@izarutskaya

**Comment by zanyrenney** [comment] 2024-03-13 18:34
bump @izarutskaya I can't reproduce this with the steps given above, please re-explain! thanks.

**Comment by zanyrenney** [comment] 2024-03-18 18:27
Closing as I still cannot reproduce and have bumped twice for clearing steps.

**Closed by zanyrenney** 2024-03-18 18:27 UTC
Labels: Daily, Overdue, Bug
