### ISSUE TITLE
[$500] Chat - Thread does not appear immediately in task report screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29356] opened 2023-10-11 18:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697015462532949

## Action Performed:
1. Go to chat with userB
2. Click on + icon and select Assign task
3. Enter title and create task
4. From userB, go to task report screen
5. Send message
6. Create thread
7. Verify comment on task from task creator side

## Expected Result:
Thread should be appear immediately as 1 reply under the comment

## Actual Result:
Thread does not appear immediately as 1 reply under the comment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/284e172e-0482-4300-8a7c-d68c0c39c845

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/64ea92a6-bf00-49b6-876b-c2753a68f990

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/c63f5891-423d-4678-aa71-0054bbed461b

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/a93279a9-4c1f-4453-b853-4f54c95155fc

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/0e59ef26-6fe9-4b97-b86f-506e69ebf379

https://github.com/Expensify/App/assets/93399543/0f913e08-4e93-4dcd-8abc-bbb548392819

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/0af7e8e6-a770-43c3-9e02-7d0af45d6025

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b1b3d5dd35247353</li>
        <li>Upwork Job ID: 1712174666231857152</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-10-12 16:37
This looks like a backend issue. User A doesn't receive any pusher events when user B replies in the thread

**Comment by sonialiap** [comment] 2023-10-17 11:54
moving this to internal

**Comment by sonialiap** [comment] 2023-10-17 11:55
I'm OOO Oct 16-23. Adding leave buddy

Status: looking for proposals

**Comment by garrettmknight** [comment] 2023-10-18 20:37
Adding `Engineering` since this is an internal issue.

**Comment by lakchote** [comment] 2023-10-23 09:37
Checking it today.

**Comment by lakchote** [comment] 2023-10-23 14:36
Bug not that easy to fix.

Will focus on [this](https://github.com/Expensify/Expensify/issues/304892) time sensitive issue, and get back to it after.

Putting it as a weekly in the meantime.

**Comment by lakchote** [comment] 2023-10-27 13:46
Will take a look at it again on Monday.

Didn't have the time to investigate it properly before that.

**Comment by lakchote** [comment] 2023-10-30 08:46
Looking at it today.

**Comment by lakchote** [comment] 2023-10-30 15:55
I've identified the root cause and am looking to find an acceptable solution for this.

When we are posting a comment, we call the method `addComment` in `ReportApi.php`.
which in turns call `CreateReportAction.cpp` here:
https://github.com/Expensify/Web-Expensify/blob/79d6f3edcc9469b469367d63b197c03b6263b0a1/lib/ReportAPI.php#L501

Then it does this to get the participants lists:
https://github.com/Expensify/Auth/blob/04d28c918c70d653bc05d18661dc771e3adeda27/auth/command/CreateReportAction.cpp#L179

This list of IDs is then pushed to Onyx.   

Problem: the task's creator account ID isn't in this list after starting a thread which explains why they don't receive updates.

**Comment by lakchote** [comment] 2023-10-31 06:37
We have the same kind of issue for mention reports & threads [here](https://github.com/Expensify/App/issues/21146).

**Comment by lakchote** [comment] 2023-11-09 09:43
It has been deployed to production 3 days ago.

**Comment by garrettmknight** [comment] 2023-11-15 21:09
@lakchote should we be retesting this one or something else?

**Comment by mvtglobally** [comment] 2023-11-18 04:34
Issue not reproducible during KI retests. (First week)

**Comment by lakchote** [comment] 2023-11-20 14:20
> @lakchote should we be retesting this one or something else?

Sorry Garrett, your reply got swarmed in my GH notifications. I did test that it was working, but it's still a good thing that @ntdiary did it too! 

@ntdiary I'm going to assign myself the issue you've linked since it seems like it has been created a long time ago.

**Comment by garrettmknight** [comment] 2023-11-20 17:09
Cool - so we need to pay the reporter here, but it doesn't look like @ntdiary (was asked to) or reviewed the PR for this one. @sonialiap any idea how we typically handle this?

**Comment by gadhiyamanan** [comment] 2023-12-18 04:58
this is eligible for reporting bonus, can you reopen the issue ...
cc: @garrettmknight @sonialiap @lakchote

**Comment by garrettmknight** [comment] 2023-12-18 13:17
@gadhiyamanan offer out to you.

**Comment by garrettmknight** [comment] 2023-12-18 13:17
https://www.upwork.com/en-gb/ab/applicants/1736736768053436416/job-details for my reference

**Comment by gadhiyamanan** [comment] 2023-12-18 13:25
@garrettmknight offer accepted, thanks!

**Comment by garrettmknight** [comment] 2023-12-18 13:33
Paid, closing

**Closed by garrettmknight** 2023-12-18 13:33 UTC
Labels: Reviewing, Engineering, Daily, Internal, Help Wanted, Bug
