### ISSUE TITLE
[$1000] mweb - App displays same welcome message page on back click on mobile chrome

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22082] opened 2023-07-02 22:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any room
3. Click on room title in header to open room details
4. Open settings
5. Open welcome message
6. Edit welcome message and click on save
7. Again open welcome message
8. Click on back button of your device and observe that it reopens same welcome message page

## Expected Result:
App should display room settings when we click on back on welcome message page

## Actual Result:
 App displays same welcome message page when we save welcome message, reopen it and click on back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/36e02196-eaeb-4977-90d5-55b046eda68c

https://github.com/Expensify/App/assets/93399543/12fa4e3f-2662-47f7-88fe-90bb4c766bed

**Expensify/Expensify Issue URL:**
**Issue reported by:** GH handle - @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688225568421009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01974ff1b6dd73c766</li>
        <li>Upwork Job ID: 1677138510188093440</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-03 21:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When click back button, app displays the same welcome message page
This happens on mac/chrome as well

### What is the root cause of that problem?

`ReportWelcomeMessagePage` and ``ReportSettingsPage` are in different stack navigator

https://github.com/Expensify/App/blob/3b687018c3d907f1bcdea8f9a4a8cae90101959f/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L148-L155

https://github.com/Expensify/App/blob/3b687018c3d907f1bcdea8f9a4a8cae90101959f/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L203-L211

I think the root cause is same as [here](https://github.com/react-navigation/react-navigation/issues/6434)

### What changes do you think we should make in order to solve the problem?

We can replace the current path instead of going back.

1. Replace the below code line
https://github.com/Expensify/App/blob/3b687018c3d907f1bcdea8f9a4a8cae90101959f/src/pages/ReportWelcomeMessagePage.js#L59

with
```
        <HeaderWithBackButton
            title={props.translate('welcomeMessagePage.welcomeMessage')}
            onBackButtonPress={() => Navigation.navigate(ROUTES.getReportSettingsRoute(props.report.reportID, 'UP'))}
        />
```

2. In `updateWelcomeMessage` function in [Report.js](https://github.com/Expensify/App/blob/3b687018c3d907f1bcdea8f9a4a8cae90101959f/src/libs/actions/Report.js#L1119), replace `Navigation.goBack()` with `Navigation.navigate(ROUTES.getReportSettingsRoute(reportID, 'UP'))`

This works as expected.

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/29747860-90a9-4c29-9157-2a780cd08665


</details>

### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment] 2023-07-07 02:13
little glitchy, good to fix

**Comment by adelekennedy** [comment] 2023-07-10 23:17
one proposal to review - not doubling yet!

**Comment by s-alves10** [comment] 2023-07-13 05:50
@parasharrajat 

Please read this
https://github.com/react-navigation/react-navigation/issues/6434

**Comment by ShogunFire** [comment] 2023-07-13 16:19
Can you still reproduce ? I think a change has been made in linkTo and that should solve it:
https://github.com/Expensify/App/blob/main/contributingGuides/NAVIGATION.md#why-we-need-to-use-minimal-action-in-the-linkto-function

**Comment by adelekennedy** [comment] 2023-07-13 18:40
I'm not able to reproduce (but I find the android reproduction steps tricky)

**Comment by s-alves10** [comment] 2023-07-13 20:00
yeah. it's not reproducible now

**Comment by adelekennedy** [comment] 2023-07-14 18:59
I'm going to close this one as I think this has been fixed - I think 25% is still due here for the proposal reviews

**Closed by adelekennedy** 2023-07-14 18:59 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by dhanashree-sawant** [comment] 2023-07-14 19:03
Hi @adelekennedy, @parasharrajat is it eligible for reporting bonus?

**Comment by adelekennedy** [comment] 2023-07-14 19:49
Ah! Yes - thank you fro catching that @dhanashree-sawant

**Comment by anmurali** [comment] 2023-07-21 15:50
Approved $250 based on https://github.com/Expensify/App/issues/22082#issuecomment-1636284267

**Comment by dhanashree-sawant** [comment] 2023-07-21 15:55
Hi @adelekennedy, @anmurali  , sorry I missed that message, if possible, can you send me invite to the job?

**Comment by adelekennedy** [comment] 2023-07-24 02:04
@dhanashree-sawant hired! Please accept and I'll pay out

**Comment by dhanashree-sawant** [comment] 2023-07-24 03:52
Thanks @adelekennedy, 
Offer accepted.

**Comment by dhanashree-sawant** [comment] 2023-08-07 05:46
Hi @adelekennedy, ping for approving the offer on upwork
